### ISSUE TITLE
FreqAI RL model - KeyError: 'train_features'

### ISSUE THREAD

**Issue by peasant-try** [freqtrade/freqtrade#10007]
My environment:
  * Operating system: Windows 11
  * Python Version: 3.11.5
  * CCXT version: 4.1.76
  * Freqtrade Version: freqtrade 2023.12-dev-7d281602f
  
## Your question

I'm getting the following error when trying to backtest my RL strategy. I downloaded all the datasets for the pairs involved, i even downloaded more data than the one i'm using to backtest accordingly to the following documentation [downloading-data-to-cover-the-full-backtest-period](https://www.freqtrade.io/en/stable/freqai-running/#downloading-data-to-cover-the-full-backtest-period)
```2024-03-26 12:10:20,501 - freqtrade - INFO - freqtrade 2023.12-dev-7d281602f
2024-03-26 12:10:20,504 - freqtrade.configuration.load_config - INFO - Using config: user_data/strategies/saturn_config.json ...
2024-03-26 12:10:20,505 - freqtrade.loggers - INFO - Verbosity set to 0
2024-03-26 12:10:20,505 - freqtrade.configuration.configuration - INFO - Using additional Strategy lookup path: user_data/strategies
2024-03-26 12:10:20,506 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 10 ...
2024-03-26 12:10:20,506 - freqtrade.configuration.configuration - INFO - Parameter --timerange detected: 20230601-20230831 ...
2024-03-26 12:10:20,506 - freqtrade.configuration.configuration - INFO - Using user-data directory: C:\Users\user\OneDrive\Documents\Trading\Freqtrade\freqtrade\user_data ...
2024-03-26 12:10:20,506 - freqtrade.configuration.configuration - INFO - Using data directory: C:\Users\user\OneDrive\Documents\Trading\Freqtrade\freqtrade\user_data\data\binance ...
2024-03-26 12:10:20,507 - freqtrade.configuration.configuration - INFO - Parameter --cache=day detected ...
2024-03-26 12:10:20,507 - freqtrade.configuration.configuration - INFO - Filter trades by timerange: 20230601-20230831
2024-03-26 12:10:20,507 - freqtrade.configuration.configuration - INFO - Using freqaimodel class name: ReinforcementLearner
2024-03-26 12:10:20,508 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2024-03-26 12:10:20,515 - freqtrade.exchange.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2024-03-26 12:10:20,515 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2024-03-26 12:10:20,515 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2024-03-26 12:10:20,517 - freqtrade.commands.optimize_commands - INFO - Starting freqtrade in Backtesting mode
2024-03-26 12:10:20,518 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2024-03-26 12:10:20,518 - freqtrade.exchange.exchange - INFO - Using CCXT 4.1.76
2024-03-26 12:10:20,519 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}}
2024-03-26 12:10:20,526 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}}
2024-03-26 12:10:20,532 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2024-03-26 12:10:28,201 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2024-03-26 12:10:28,214 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy saturnRsiPivot from 'C:\Users\user\OneDrive\Documents\Trading\Freqtrade\freqtrade\user_data\strategies\saturnRsiPivot.py'...
2024-03-26 12:10:28,214 - freqtrade.strategy.hyper - INFO - Found no parameter file.
2024-03-26 12:10:28,215 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 1h.
2024-03-26 12:10:28,215 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2024-03-26 12:10:28,215 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: unlimited.
2024-03-26 12:10:28,215 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}.
2024-03-26 12:10:28,215 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'max_open_trades' with value in config file: 10.
2024-03-26 12:10:28,215 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 0.8, '1440': 0.6, '4320': 0.4, '10080': 0}
2024-03-26 12:10:28,215 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 1h
2024-03-26 12:10:28,216 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.15
2024-03-26 12:10:28,216 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2024-03-26 12:10:28,216 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2024-03-26 12:10:28,216 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2024-03-26 12:10:28,216 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2024-03-26 12:10:28,216 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: True
2024-03-26 12:10:28,216 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'entry': 'limit', 'exit': 'limit', 'stoploss': 'market', 'stoploss_on_exchange': False}
2024-03-26 12:10:28,217 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'entry': 'GTC', 'exit': 'GTC'}
2024-03-26 12:10:28,217 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2024-03-26 12:10:28,217 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: unlimited
2024-03-26 12:10:28,217 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2024-03-26 12:10:28,217 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 20
2024-03-26 12:10:28,217 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}
2024-03-26 12:10:28,217 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_exit_signal: True
2024-03-26 12:10:28,217 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_only: False
2024-03-26 12:10:28,218 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_entry_signal: False
2024-03-26 12:10:28,218 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_offset: 0.0
2024-03-26 12:10:28,218 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2024-03-26 12:10:28,218 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2024-03-26 12:10:28,218 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: False
2024-03-26 12:10:28,218 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1
2024-03-26 12:10:28,219 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_open_trades: 10
2024-03-26 12:10:28,219 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2024-03-26 12:10:28,235 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from 'C:\Users\user\OneDrive\Documents\Trading\Freqtrade\freqtrade\freqtrade\plugins\pairlist\StaticPairList.py'...
2024-03-26 12:10:28,243 - freqtrade.data.dataprovider - INFO - Increasing startup_candle_count for freqai to 2180
2024-03-26 12:10:28,245 - freqtrade.data.history.history_utils - INFO - Using indicator startup period: 2180 ...
2024-03-26 12:10:28,301 - freqtrade.optimize.backtesting - INFO - Loading data from 2023-03-02 04:00:00 up to 2023-08-31 00:00:00 (181 days).
2024-03-26 12:10:28,363 - freqtrade.optimize.backtesting - INFO - Dataload complete. Calculating indicators
2024-03-26 12:10:28,366 - freqtrade.optimize.backtesting - INFO - Running backtesting for Strategy saturnRsiPivot
2024-03-26 12:10:30,502 - freqtrade.resolvers.iresolver - INFO - Using resolved freqaimodel ReinforcementLearner from 'C:\Users\user\OneDrive\Documents\Trading\Freqtrade\freqtrade\freqtrade\freqai\prediction_models\ReinforcementLearner.py'...
2024-03-26 12:10:30,502 - freqtrade.freqai.freqai_interface - INFO - Backtesting module configured to save all models.
2024-03-26 12:10:30,503 - freqtrade.freqai.data_drawer - INFO - Could not find existing datadrawer, starting from scratch
2024-03-26 12:10:30,503 - freqtrade.freqai.data_drawer - INFO - Could not find existing historic_predictions, starting from scratch
2024-03-26 12:10:30,504 - freqtrade.freqai.freqai_interface - INFO - Set fresh train queue from whitelist. Queue: ['BTC/USDT:USDT', 'ETH/USDT:USDT']
2024-03-26 12:10:30,593 - freqtrade.strategy.hyper - INFO - No params for buy found, using default values.
2024-03-26 12:10:30,594 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): std_dev_multiplier_buy = 1.25
2024-03-26 12:10:30,594 - freqtrade.strategy.hyper - INFO - No params for sell found, using default values.
2024-03-26 12:10:30,594 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): std_dev_multiplier_sell = 1.25
2024-03-26 12:10:30,594 - freqtrade.strategy.hyper - INFO - No params for protection found, using default values.
2024-03-26 12:10:30,596 - freqtrade.freqai.freqai_interface - INFO - Training 7 timeranges
2024-03-26 12:10:30,597 - freqtrade.freqai.freqai_interface - INFO - Training BTC/USDT:USDT, 1/2 pairs from 2023-03-03 00:00:00 to 2023-06-01 00:00:00, 1/7 trains
2024-03-26 12:10:30,597 - freqtrade.freqai.data_kitchen - INFO - Could not find backtesting prediction file at C:\Users\user\OneDrive\Documents\Trading\Freqtrade\freqtrade\user_data\models\saturn-test\backtesting_predictions\cb_btc_1685577600_prediction.feather
2024-03-26 12:10:30,600 - freqtrade.data.dataprovider - INFO - Increasing startup_candle_count for freqai to 20
2024-03-26 12:10:30,637 - freqtrade.data.dataprovider - INFO - Increasing startup_candle_count for freqai to 20
2024-03-26 12:10:30,672 - freqtrade.data.dataprovider - INFO - Increasing startup_candle_count for freqai to 20
2024-03-26 12:10:30,745 - freqtrade.freqai.freqai_interface - INFO - Could not find model at C:\Users\user\OneDrive\Documents\Trading\Freqtrade\freqtrade\user_data\models\saturn-test\sub-train-BTC_1685577600\cb_btc_1685577600
2024-03-26 12:10:30,745 - freqtrade.freqai.RL.BaseReinforcementLearningModel - INFO - --------------------Starting training BTC/USDT:USDT --------------------
2024-03-26 12:10:30,778 - freqtrade.freqai.data_kitchen - INFO - BTC/USDT:USDT: dropped 2160 training points due to NaNs in populated dataset 2160.
2024-03-26 12:10:30,778 - freqtrade.freqai.freqai_interface - WARNING - Training BTC/USDT:USDT raised exception ValueError. Message: With n_samples=0, test_size=0.25 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters., skipping.
Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Documents\Trading\Freqtrade\freqtrade\freqtrade\freqai\freqai_interface.py", line 351, in start_backtesting
    self.model = self.train(dataframe_train, pair, dk)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Documents\Trading\Freqtrade\freqtrade\freqtrade\freqai\RL\BaseReinforcementLearningModel.py", line 114, in train
    dd: Dict[str, Any] = dk.make_train_test_datasets(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Documents\Trading\Freqtrade\freqtrade\freqtrade\freqai\data_kitchen.py", line 156, in make_train_test_datasets
    ) = train_test_split(
        ^^^^^^^^^^^^^^^^^
  File "C:\Users\user\miniconda3\envs\freqtrade\Lib\site-packages\sklearn\model_selection\_split.py", line 2448, in train_test_split
    n_train, n_test = _validate_shuffle_split(
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\miniconda3\envs\freqtrade\Lib\site-packages\sklearn\model_selection\_split.py", line 2126, in _validate_shuffle_split
    raise ValueError(
ValueError: With n_samples=0, test_size=0.25 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
2024-03-26 12:10:30,782 - freqtrade.freqai.freqai_interface - INFO - Saving metadata to disk.
2024-03-26 12:10:30,786 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Documents\Trading\Freqtrade\freqtrade\freqtrade\main.py", line 42, in main
    return_code = args['func'](args)
                  ^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Documents\Trading\Freqtrade\freqtrade\freqtrade\commands\optimize_commands.py", line 58, in start_backtesting
    backtesting.start()
  File "C:\Users\user\OneDrive\Documents\Trading\Freqtrade\freqtrade\freqtrade\optimize\backtesting.py", line 1384, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Documents\Trading\Freqtrade\freqtrade\freqtrade\optimize\backtesting.py", line 1301, in backtest_one_strategy
    preprocessed = self.strategy.advise_all_indicators(data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Documents\Trading\Freqtrade\freqtrade\freqtrade\strategy\interface.py", line 1346, in advise_all_indicators
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Documents\Trading\Freqtrade\freqtrade\freqtrade\strategy\interface.py", line 1346, in <dictcomp>
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Documents\Trading\Freqtrade\freqtrade\freqtrade\strategy\interface.py", line 1378, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Documents\Trading\Freqtrade\freqtrade\user_data\strategies\saturnRsiPivot.py", line 346, in populate_indicators
    dataframe = self.freqai.start(dataframe, metadata, self)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Documents\Trading\Freqtrade\freqtrade\freqtrade\freqai\freqai_interface.py", line 161, in start
    dk = self.start_backtesting(dataframe, metadata, self.dk, strategy)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Documents\Trading\Freqtrade\freqtrade\freqtrade\freqai\freqai_interface.py", line 368, in start_backtesting
    self.dd.save_metadata(dk)
  File "C:\Users\user\OneDrive\Documents\Trading\Freqtrade\freqtrade\freqtrade\freqai\data_drawer.py", line 457, in save_metadata
    dk.data["training_features_list"] = list(dk.data_dictionary["train_features"].columns)
                                             ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'train_features'
```
Also, here's my config.json file (I redacted my keys and sensible data):
```
{
    "max_open_trades": 10,
    "stake_currency": "USDT",
    "stake_amount": "unlimited",
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "dry_run": true,
    "dry_run_wallet": 20000,
    "cancel_open_orders_on_exit": false,
    "trading_mode": "futures",
    "margin_mode": "isolated",
    "unfilledtimeout": {
        "entry": 10,
        "exit": 10,
        "exit_timeout_count": 0,
        "unit": "minutes"
    },
    "freqai": {
        "enabled": true,
        "purge_old_models": 2,
        "train_period_days": 30,
        "backtest_period_days": 7,
        "identifier" : "saturn-dev",
        "feature_parameters" : {
            "include_timeframes": ["1h","1d","3d"],
            "include_corr_pairlist": [
            ],
            "label_period_candles": 24,
            "include_shifted_candles": 2,
            "indicator_periods_candles": [7, 14]
        },
        "data_split_parameters" : {
            "test_size": 0.2
        },
        "rl_config": {
            "train_cycles": 25,
            "max_trade_duration_candles": 300,
            "max_training_drawdown_pct": 0.02,
            "cpu_count": 8,
            "model_type": "DQN",
            "policy_type": "MlpPolicy",
            "model_reward_parameters": {
                "rr": 1,
                "profit_aim": 0.025
            }
        }
    },
    "entry_pricing": {
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1,
        "price_last_balance": 0.0,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "exit_pricing":{
        "price_side": "other",
        "use_order_book": true,
        "order_book_top": 1
    },
    "exchange": {
        "name": "binance",
        "key": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        "secret": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        "ccxt_config": {},
        "ccxt_async_config": {},
        "pair_whitelist": [
            "LINK/USDT:USDT",
            "BTC/USDT:USDT",
            "ETH/USDT:USDT"
        ],
        "pair_blacklist": [
            "BNB/.*"
        ]
    },
    "pairlists": [
        {
            "method": "StaticPairList",
            "number_assets": 20,
            "sort_key": "quoteVolume",
            "min_value": 0,
            "refresh_period": 1800
        }
    ],
    "telegram": {
        "enabled": true,
        "token": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        "chat_id": "AAAAAAAAAAA"
    },
    "api_server": {
        "enabled": true,
        "listen_ip_address": "127.0.0.1",
        "listen_port": 8080,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        "ws_token": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        "CORS_origins": [],
        "username": "AAAAAAAAAAAAAAAA",
        "password": "AAAAAAAAAAAAAA"
    },
    "bot_name": "freqtrade",
    "initial_state": "running",
    "force_entry_enable": false,
    "internals": {
        "process_throttle_secs": 5
    },
    "logging": {
        "version": 1,
        "root": {
            "level": "INFO",
            "handlers": ["console", "file"]
        },
        "handlers": {
            "console": {
                "class": "logging.StreamHandler",
                "level": "INFO",
                "formatter": "simple"
            },
            "file": {
                "class": "logging.FileHandler",
                "filename": "freqtrade.log",
                "level": "DEBUG",
                "formatter": "simple"
            }
        },
        "formatters": {
            "simple": {
                "format": "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
            }
        }
    }
}
```
I used the following command to backtest:
`freqtrade backtesting --strategy saturnRsiPivot --strategy-path user_data/strategies --freqaimodel ReinforcementLearner --timerange=20230601-20230831 --config user_data/strategies/saturn_config.json`
I already tried using another identifier for this run. Also, my strategy runs just fine when i execute it for Dry Run Instead. Thanks in advanced.

**Comment by xmatthias** [comment]
well your strategy has "something" that's causing it to have NaN values in backtesting.

That's either a mal-defined startup-candle-count (so not enough startup data is provided for indicators to calculate) - or it's using some other data that isn't available in backtesting for some reason.

In the end, all rows are removed as they do contain NaN - which is essentially what the error says.

**Comment by robcaulk** [comment]
hello,

If you are backtesting, then you need to download the data before hand. We’ve documented how to do this, thanks for reading it:

https://www.freqtrade.io/en/stable/freqai-running/#downloading-data-to-cover-the-full-backtest-period

**Comment by peasant-try** [comment]
Hello, i downloaded the data already. I downloaded data from 20230101-20231231, and i'm backtesting from 20230601-202308031. 

> well your strategy has "something" that's causing it to have NaN values in backtesting.
> 
> That's either a mal-defined startup-candle-count (so not enough startup data is provided for indicators to calculate) - or it's using some other data that isn't available in backtesting for some reason.
> 
> In the end, all rows are removed as they do contain NaN - which is essentially what the error says.

If it was the strategy, why does it run just fine when running on Dry Run mode? I noticed something, when i change the startup_candle_count value, the log doesn't reflect the updated value, why is that? I deleted the generated model to see if it was something related with that, but it still doesnt work.

**Comment by peasant-try** [comment]
> That's either a mal-defined startup-candle-count (so not enough startup data is provided for indicators to calculate)

Hello, i played with this value, i had to change the value from 30 to 60 to solve this. Thanks for the help!

**Comment by peasant-try** [comment]
I'm closing this, i forgot to close on my previous comment. Thanks for the help!
