### ISSUE TITLE
uvicorn.error - ERROR - Exception in ASGI application

### ISSUE THREAD

**Issue by VerDoe** [freqtrade/freqtrade#10043]
* Operating system: Debian 6.1.67-1
  * Python Version: Python 3.11.2
  * CCXT version: ccxt==4.2.87
  * Freqtrade Version: freqtrade 2024.3
  
Hello, since I have installed the new version with setup -u, my bot can no longer be started. I have already done a complete reinstallation and always get the same error. I get the following error:

```
2024-04-03 20:26:42,121 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': "Searching for USDT pairs to buy and sell based on [{'VolumePairList': 'VolumePairList - top 200 volume pairs.'}, {'AgeFilter': 'AgeFilter - Filtering pairs with age less than 90 days'}, {'PriceFilter': 'PriceFilter - Filtering pairs priced below 0.01000000.'}]"}
2024-04-03 20:27:05,303 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/app/freqtrade/.venv/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/freqtrade/.venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/freqtrade/.venv/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/app/freqtrade/.venv/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/app/freqtrade/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/app/freqtrade/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/app/freqtrade/.venv/lib/python3.11/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/app/freqtrade/.venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/app/freqtrade/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/app/freqtrade/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/app/freqtrade/.venv/lib/python3.11/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/app/freqtrade/.venv/lib/python3.11/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/app/freqtrade/.venv/lib/python3.11/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/app/freqtrade/.venv/lib/python3.11/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/app/freqtrade/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/app/freqtrade/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/app/freqtrade/.venv/lib/python3.11/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/app/freqtrade/.venv/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/freqtrade/.venv/lib/python3.11/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/freqtrade/.venv/lib/python3.11/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/freqtrade/.venv/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/freqtrade/.venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/app/freqtrade/.venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/freqtrade/freqtrade/rpc/api_server/api_v1.py", line 287, in pair_candles
    return rpc._rpc_analysed_dataframe(pair, timeframe, limit)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/freqtrade/freqtrade/rpc/rpc.py", line 1244, in _rpc_analysed_dataframe
    return RPC._convert_dataframe_to_dict(self._freqtrade.config['strategy'],
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/freqtrade/freqtrade/rpc/rpc.py", line 1195, in _convert_dataframe_to_dict
    mask = (dataframe[sig_type] == 1)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/freqtrade/.venv/lib/python3.11/site-packages/pandas/core/ops/common.py", line 76, in new_method
    return method(self, other)
           ^^^^^^^^^^^^^^^^^^^
  File "/app/freqtrade/.venv/lib/python3.11/site-packages/pandas/core/arraylike.py", line 40, in __eq__
    return self._cmp_method(other, operator.eq)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/freqtrade/.venv/lib/python3.11/site-packages/pandas/core/series.py", line 6110, in _cmp_method
    res_values = ops.comparison_op(lvalues, rvalues, op)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/freqtrade/.venv/lib/python3.11/site-packages/pandas/core/ops/array_ops.py", line 347, in comparison_op
    res_values = _na_arithmetic_op(lvalues, rvalues, op, is_cmp=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/freqtrade/.venv/lib/python3.11/site-packages/pandas/core/ops/array_ops.py", line 218, in _na_arithmetic_op
    result = func(left, right)
             ^^^^^^^^^^^^^^^^^
  File "/app/freqtrade/.venv/lib/python3.11/site-packages/pandas/core/computation/expressions.py", line 242, in evaluate
    return _evaluate(op, op_str, a, b)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/freqtrade/.venv/lib/python3.11/site-packages/pandas/core/computation/expressions.py", line 131, in _evaluate_numexpr
    result = _evaluate_standard(op, op_str, a, b)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/freqtrade/.venv/lib/python3.11/site-packages/pandas/core/computation/expressions.py", line 73, in _evaluate_standard
    return op(a, b)
           ^^^^^^^^
TypeError: Cannot compare structured or void to non-void arrays.
```

**Comment by xmatthias** [comment]
if your system version is really debian 6 - then i'd say it's simply an unsupported system, where depenencies may fail or not install properly (most prominent suspect - pandas or numpy) - which may make things work slightly differently.


Now assuming that's a typo (debian 6 went out of live 9 (!) years ago), and you're on a more recent system ...

---

While not immediately obvious from the stacktrace - the error does originate from your strategy.

for the "regular" dataframe signal columns (enter_long, exit_long, enter_short, exit_short), the assumption is that they'll contain a boolean / integer.

From the error - it seems like it contains an array of some sort.



Now with a regular strategy - i can't really reproduce this (it's working fine for me) - but i'll not have the same strategy bug than you do - so we'll need a minimal reproducible strategy where this is happening (not a 1000 line monster, just a few lines that do reproduce this) - which will allow us to determine if it's really something we should adress - or if it's a simple strategy bug (which i'd suspect for now).

the pandas / numpy versions would probably help too (but only really to make sure that they're aligned to the requirements file) - you can get these via `pip show pandas` and `pip show numpy` respectively).

**Comment by VerDoe** [comment]
Sorry, I made a mistake. The correct version is: Debian GNU/Linux 12 (bookworm), 6.1.0-17-amd64
Yesterday I installed 2024.2 on another server. Everything has been running smoothly since yesterday evening.
It's the E0V1E strategy from https://github.com/ssssi/freqtrade_strs/blob/main/binance/E0V1E.py, which I'm currently testing.

**Comment by froggleston** [comment]
I heard there is an issue with the EOV1E strategy introduced recently - please take it up with the strategy developers.
