### ISSUE TITLE
ccxt.OperationFailed not handled properly

### ISSUE THREAD

**Issue by wujscn** [freqtrade/freqtrade#10071]
## Describe your environment

  * Operating system: Debian 12
  * Python Version: 3.12.2
  * CCXT version: 4.2.82
  * Freqtrade Version: 2024.3
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

The bot running live tried to crate a trade but raised an OperationalException.
It seemed like it was an exchange issue, but there's a problem with the exception handling here: It change to STOPPED state when there were open trades.

### Steps to reproduce:

It is rare, because it happens when it is running live having interaction with the exchange. 

### Observed Results:

The bot just leaved the open trades alone and stop just because it failed to create a trade. It makes no sense.

Retrying may be risky, but it is more dangerous to stop like that. I'll suggest to make it keep running or turn on `stop entry` mode for safety.

### Relevant code exceptions or logs

```
2024-04-12 17:29:12,767 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': exception, 'status': '*OperationalException:*\n```\nTraceback (most recent call last):\n  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/base/exchange.py", line 630, in fetch\n    response.raise_for_status()\n  File "/home/ftuser/.local/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://fapi.binance.com/fapi/v1/order\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/freqtrade/freqtrade/exchange/exchange.py", line 1094, in create_order\n    order = self._api.create_order(\n            ^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/binance.py", line 5547, in create_order\n    response = self.fapiPrivatePostOrder(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/base/types.py", line 35, in unbound_method\n    return _self.request(self.path, self.api, self.method, params, config=self.config)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/binance.py", line 10285, in request\n    response = self.fetch2(path, api, method, params, headers, body, config)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/base/exchange.py", line 3604, in fetch2\n    return self.fetch(request[\'url\'], request[\'method\'], request[\'headers\'], request[\'body\'])\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/base/exchange.py", line 646, in fetch\n    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)\n                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/binance.py", line 10252, in handle_errors\n    self.throw_exactly_matched_exception(self.get_exceptions_by_url(url, \'exact\'), error, feedback)\n  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/base/exchange.py", line 3986, in throw_exactly_matched_exception\n    raise exact[string](message)\nccxt.base.errors.OperationFailed: binance {"code":-1008,"msg":"Server is currently overloaded with other requests. Please try again in a few minutes."}\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File "/freqtrade/freqtrade/worker.py", line 180, in _process_running\n    self.freqtrade.process()\n  File "/freqtrade/freqtrade/freqtradebot.py", line 247, in process\n    self.enter_positions()\n  File "/freqtrade/freqtrade/freqtradebot.py", line 530, in enter_positions\n    trades_created += self.create_trade(pair)\n                      ^^^^^^^^^^^^^^^^^^^^^^^\n  File "/freqtrade/freqtrade/freqtradebot.py", line 593, in create_trade\n    return self.execute_entry(\n           ^^^^^^^^^^^^^^^^^^^\n  File "/freqtrade/freqtrade/freqtradebot.py", line 769, in execute_entry\n    order = self.exchange.create_order(\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/freqtrade/freqtrade/exchange/exchange.py", line 1129, in create_order\n    raise OperationalException(e) from e\nfreqtrade.exceptions.OperationalException: binance {"code":-1008,"msg":"Server is currently overloaded with other requests. Please try again in a few minutes."}\n```\n Issue `/start` if you think it is safe to restart.'}
2024-04-12 17:29:12,767 - freqtrade.worker - ERROR - OperationalException. Stopping trader ...
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/base/exchange.py", line 630, in fetch
    response.raise_for_status()
  File "/home/ftuser/.local/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://fapi.binance.com/fapi/v1/order

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/exchange.py", line 1094, in create_order
    order = self._api.create_order(
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/binance.py", line 5547, in create_order
    response = self.fapiPrivatePostOrder(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/base/types.py", line 35, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/binance.py", line 10285, in request
    response = self.fetch2(path, api, method, params, headers, body, config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/base/exchange.py", line 3604, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/base/exchange.py", line 646, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/binance.py", line 10252, in handle_errors
    self.throw_exactly_matched_exception(self.get_exceptions_by_url(url, 'exact'), error, feedback)
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/base/exchange.py", line 3986, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.OperationFailed: binance {"code":-1008,"msg":"Server is currently overloaded with other requests. Please try again in a few minutes."}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/worker.py", line 180, in _process_running
    self.freqtrade.process()
  File "/freqtrade/freqtrade/freqtradebot.py", line 247, in process
    self.enter_positions()
  File "/freqtrade/freqtrade/freqtradebot.py", line 530, in enter_positions
    trades_created += self.create_trade(pair)
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/freqtradebot.py", line 593, in create_trade
    return self.execute_entry(
           ^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/freqtradebot.py", line 769, in execute_entry
    order = self.exchange.create_order(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/exchange/exchange.py", line 1129, in create_order
    raise OperationalException(e) from e
freqtrade.exceptions.OperationalException: binance {"code":-1008,"msg":"Server is currently overloaded with other requests. Please try again in a few minutes."}
2024-04-12 17:29:12,774 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'stopped'}
2024-04-12 17:29:12,774 - freqtrade.worker - INFO - Changing state from RUNNING to: STOPPED
2024-04-12 17:29:12,780 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': warning, 'status': "3 open trades active.\n\nHandle these trades manually on Binance, or '/start' the bot again and use '/stopentry' to handle open trades gracefully. \n"}
2024-04-12 17:29:17,781 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2024.3', state='STOPPED'
2024-04-12 17:30:17,784 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2024.3', state='STOPPED'
```

Related code from worker.py
```python
    def _process_running(self) -> None:
        try:
            self.freqtrade.process()
        except TemporaryError as error:
            logger.warning(f"Error: {error}, retrying in {RETRY_TIMEOUT} seconds...")
            time.sleep(RETRY_TIMEOUT)
        except OperationalException:
            tb = traceback.format_exc()
            hint = 'Issue `/start` if you think it is safe to restart.'

            self.freqtrade.notify_status(
                f'*OperationalException:*\n```\n{tb}```\n {hint}',
                msg_type=RPCMessageType.EXCEPTION
            )

            logger.exception('OperationalException. Stopping trader ...')
            self.freqtrade.state = State.STOPPED
```

**Comment by xmatthias** [comment]
A little while ago, ccxt started to change their exception hierarchies around - and it seems like they introduced on on top of NetworkError - which is what we do handle currently.

Unknown errors are correct in raising `OperationalException` - as that's an error that could mean anything - so the overall handling (outside of the exchange class) appears fine to me.

Now personally - i think the error is wrongly mapped on ccxt - as the error sounds like anything between DDoS and Networking ... but OperationFailed will probably always be correct.

Needless to say - i'll update the exception handlers to reflect this - which will close this issue.
