### ISSUE TITLE
Docker: error after update (system and bot update)

### ISSUE THREAD

**Issue by tlloancy** [freqtrade/freqtrade#10140]
Hi, i got these on update cheers

  ```
# docker-compose up -d
Recreating freqtrade ...

ERROR: for freqtrade  'ContainerConfig'

ERROR: for freqtrade  'ContainerConfig'
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.29.2', 'console_scripts', 'docker-compose')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 203, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3/dist-packages/compose/metrics/decorator.py", line 18, in wrapper
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1186, in up
    to_attach = up(False)
                ^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1166, in up
    return self.project.up(
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/project.py", line 697, in up
    results, errors = parallel.parallel_execute(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 108, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 206, in producer
    result = func(obj)
             ^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/project.py", line 679, in do
    return service.execute_convergence_plan(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/service.py", line 579, in execute_convergence_plan
    return self._execute_convergence_recreate(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/service.py", line 499, in _execute_convergence_recreate
    containers, errors = parallel_execute(
                         ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 108, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 206, in producer
    result = func(obj)
             ^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/service.py", line 494, in recreate
    return self.recreate_container(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/service.py", line 612, in recreate_container
    new_container = self.create_container(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/service.py", line 330, in create_container
    container_options = self._get_container_create_options(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/service.py", line 921, in _get_container_create_options
    container_options, override_options = self._build_container_volume_options(
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/service.py", line 960, in _build_container_volume_options
    binds, affinity = merge_volume_bindings(
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/service.py", line 1548, in merge_volume_bindings
    old_volumes, old_mounts = get_container_data_volumes(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/service.py", line 1579, in get_container_data_volumes
    container.image_config['ContainerConfig'].get('Volumes') or {}
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'ContainerConfig'
  ```

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

**Comment by tlloancy** [comment]
my OS is still debian buster

**Comment by xmatthias** [comment]
A very simple search for your error reveals [this stackoverflow answer](https://askubuntu.com/questions/1508129/docker-compose-giving-containerconfig-errors-after-update-today) - which (correctly) states that you're using a now deprecated docker command (`docker-compose`). 
instead, you should use `docker compose` (with space) - which should then work.

At any rate, it's not a freqtrade problem - but a problem with your docker setup (or usage) - and it'll not have been caused by the freqtrade update - but by some other update (most likely by a system update).

**Comment by tlloancy** [comment]
my mistake im on debian 12.5 wtf

**Comment by tlloancy** [comment]
is it safe to remove the container ?

# docker compose up -d
WARN[0000] /home/solidsnake/ft_userdata/docker-compose.yml: `version` is obsolete
[+] Running 0/0
 ⠋ Container 31caa99db5e2_freqtrade  Recreate                                                                                                                                                0.0s
Error response from daemon: Conflict. The container name "/31caa99db5e2_freqtrade" is already in use by container "31caa99db5e2ecd1ff198d52b9781c96f3112a12ee28ceda9e9f7ab1f4a513a8". You have to remove (or rename) that container to be able to reuse that name.

**Comment by xmatthias** [comment]
well you've probably got a container already started (you can check that with `docker ps`).

Without details though - it's pretty ... difficult to say for sure

**Comment by tlloancy** [comment]
# docker ps -a
```
CONTAINER ID   IMAGE                                 COMMAND                  CREATED         STATUS                          PORTS                                                                                                                                                                                                                       NAMES
7bcd4ad9e4b4   litespeedtech/openlitespeed:latest    "/entrypoint.sh"         2 weeks ago     Exited (137) 2 weeks ago                                                                                                                                                                                                                                    openlitespeed
d3d0a9121010   redis                                 "docker-entrypoint.s…"   3 weeks ago     Up 49 seconds                   6379/tcp                                                                                                                                                                                                                    some-redis
31caa99db5e2   42f89f0fd6fc                          "freqtrade trade --l…"   8 weeks ago     Exited (0) 24 minutes ago                                                                                                                                                                                                                                   31caa99db5e2_freqtrade
425ca71af40e   b8bba28b797b                          "docker-entrypoint.s…"   8 weeks ago     Up About a minute               0.0.0.0:3307->3306/tcp, :::3307->3306/tcp                                                                                                                                                                                   wp_db2
41a68d498b4c   mailserver/docker-mailserver:latest   "/usr/bin/dumb-init …"   6 months ago    Up 17 minutes (healthy)         0.0.0.0:25->25/tcp, :::25->25/tcp, 0.0.0.0:143->143/tcp, :::143->143/tcp, 0.0.0.0:465->465/tcp, :::465->465/tcp, 0.0.0.0:587->587/tcp, :::587->587/tcp, 110/tcp, 995/tcp, 0.0.0.0:993->993/tcp, :::993->993/tcp, 4190/tcp   mailserver
2ad2945376d9   gogs/gogs                             "/app/gogs/docker/st…"   6 months ago    Up 50 seconds (healthy)         0.0.0.0:10022->22/tcp, :::10022->22/tcp, 0.0.0.0:10880->3000/tcp, :::10880->3000/tcp                                                                                                                                        gogs
f58296290d15   871a9153c184                          "docker-entrypoint.s…"   6 months ago    Up 50 seconds                   3306/tcp                                                                                                                                                                                                                    mariadb
f44ef56e8755   itzg/minecraft-server                 "/start"                 13 months ago   Exited (255) 13 months ago      0.0.0.0:25565->25565/tcp, :::25565->25565/tcp                                                                                                                                                                               mc
792b33d0c457   wordpress:latest                      "docker-entrypoint.s…"   17 months ago   Up 17 minutes                   0.0.0.0:1234->80/tcp, :::1234->80/tcp                                                                                                                                                                                       wp
45f7a34233bf   mysql:5.7                             "docker-entrypoint.s…"   17 months ago   Exited (0) About a minute ago                                                                                                                                                                                                                               wp_db
```

**Comment by tlloancy** [comment]
that's strange. i'm pretty sure the docker was called just "freqtrade"

**Comment by xmatthias** [comment]
Well you can probably remove the dangling container - it's stopped (Exited) anyway - and containers are assumed to be non-persistant.

**Comment by tlloancy** [comment]
# docker rm 31caa99db5e2_freqtrade
31caa99db5e2_freqtrade
docker compose up -d
```
WARN[0000] /home/solidsnake/ft_userdata/docker-compose.yml: `version` is obsolete
[+] Running 1/1
 ✔ Container freqtrade  Started                                                                                                                                                              0.1s
root@Host-004:/home/solidsnake/ft_userdata# docker ps
CONTAINER ID   IMAGE                                 COMMAND                  CREATED         STATUS                    PORTS                                                                                                                                                                                                                       NAMES
7d45ba038490   freqtradeorg/freqtrade:stable         "freqtrade trade --l…"   9 seconds ago   Up 8 seconds              0.0.0.0:8080->8080/tcp                                                                                                                                                                                                      freqtrade
```

Ok back to normal

I don't get where that name came from anyway

**Comment by tlloancy** [comment]
No strategy to make millions of dollars yet ?

**Comment by xmatthias** [comment]
well - not publicly available, anyway.

it's up to you to write and share it though :laughing:
