### ISSUE TITLE
Using tuple in CategoricalParameter

### ISSUE THREAD

**Issue by HeinrichHaller** [freqtrade/freqtrade#10159]
## Describe your environment

  * Operating system: ____ Ubuntu LTS
  * Python Version: _____  Python 3.10.12
  * CCXT version: _____ ccxt==4.2.91
  * Freqtrade Version: ____ freqtrade 2024.4-dev-e5f3d0443
  
## Your question
Hello! I have a question in regard of the hyperopt mechanism. I intended to do some filter variations via windowing. But this problem can appear for other lemma as well when you try to restrict the search space. 

```
      @staticmethod
        def generate_limit_pairs():
        slow_step = 0.01
        min_range = 0.2
        max_range = 0.4
        range_step = 0.02
        
        valid_pairs = []
        for slow in np.arange(0.01, 0.11, slow_step).tolist():
            for added_range in np.arange(min_range, max_range + range_step, range_step).tolist():
                fast = slow + added_range
                if fast <= 1.0:
                    valid_pairs.append((float(fast), float(slow)))  # Ensure elements are native Python floats
        return valid_pairs

        # creating tuple for Categorical Optim
        
        # All in buy space 
        # Define the fastlimit and slowlimit as DecimalParameters for hyperoptimization
        # Define the limit_pairs as a CategoricalParameter using the generated pairs
        limit_pairs = generate_limit_pairs()
        # upper_lower_pairs = CategoricalParameter(limit_pairs, default=(0.4, 0.02), space='buy')
        # Define a simpler categorical parameter temporarily to test functionality
        simple_test_categories = [(0.2, 0.1), (0.3, 0.1), (0.4, 0.1)]
        
        upper_lower_pairs = CategoricalParameter(simple_test_categories, default=(0.3, 0.1), space='buy')`
```  

I tried to ensure the search space is not too big and the values are valid. Calling the function like that: 

```
def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """Generate all indicators used by the strategy using parameters from CategoricalParameter."""

        # Iterate over each tuple in the range of categorical parameters
        for val in self.upper_lower_pairs.range:
            
            window_key = f'window_{val[0]}_{val[1]}'
            
            # Calculate window using the fast and slow limits from the tuple
            dataframe[window_key]= window(dataframe['close'], fastlimit=val[0], slowlimit=val[1])

        return dataframe
```

Backtesting and hyperopt in the ROI-space works. But skopt, I assume, does not like the tuple: 
```
Epochs ━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   24/1000   2% • 0:00:12 • 0:02:54
2024-04-29 14:39:11,715 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/moritz/VisualStudio/freqtrade5/freqtrade/freqtrade/main.py", line 42, in main
    return_code = args['func'](args)
  File "/home/moritz/VisualStudio/freqtrade5/freqtrade/freqtrade/commands/optimize_commands.py", line 107, in start_hyperopt
    hyperopt.start()
  File "/home/moritz/VisualStudio/freqtrade5/freqtrade/freqtrade/optimize/hyperopt.py", line 615, in start
    asked, is_random = self.get_asked_points(n_points=current_jobs)
  File "/home/moritz/VisualStudio/freqtrade5/freqtrade/freqtrade/optimize/hyperopt.py", line 503, in get_asked_points
    asked = unique_list(self.opt.ask(n_points=n_points * 5 if i > 0 else n_points))
  File "/home/moritz/VisualStudio/freqtrade5/freqtrade/.venv/lib/python3.10/site-packages/skopt/optimizer/optimizer.py", line 395, in ask
    x = opt.ask()
  File "/home/moritz/VisualStudio/freqtrade5/freqtrade/.venv/lib/python3.10/site-packages/skopt/optimizer/optimizer.py", line 367, in ask
    return self._ask()
  File "/home/moritz/VisualStudio/freqtrade5/freqtrade/.venv/lib/python3.10/site-packages/skopt/optimizer/optimizer.py", line 446, in _ask
    min_delta_x = min([self.space.distance(next_x, xi)
  File "/home/moritz/VisualStudio/freqtrade5/freqtrade/.venv/lib/python3.10/site-packages/skopt/optimizer/optimizer.py", line 446, in <listcomp>
    min_delta_x = min([self.space.distance(next_x, xi)
  File "/home/moritz/VisualStudio/freqtrade5/freqtrade/.venv/lib/python3.10/site-packages/skopt/space/space.py", line 1138, in distance
    distance += dim.distance(a, b)
  File "/home/moritz/VisualStudio/freqtrade5/freqtrade/.venv/lib/python3.10/site-packages/skopt/space/space.py", line 743, in distance
    if not (a in self and b in self):
  File "/home/moritz/VisualStudio/freqtrade5/freqtrade/.venv/lib/python3.10/site-packages/skopt/space/space.py", line 720, in __contains__
    return point in self.categories
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

What could be a possible workaround? 
I hope some similar question has not been asked already and thanks in advance! And I am not getting it formatted correctly...

**Comment by xmatthias** [comment]
well it has - it's a simple limitation (i call it bug) in scikit-optimize (https://github.com/scikit-optimize/scikit-optimize/issues/967).

There's never really been a solution to this (given that scikit-optimize is no longer maintained, that's no surprise) - so the solution essentially remains the same - use strings with a separator that you can easily split it again.

**Comment by HeinrichHaller** [comment]
Thank you very much, I came up with something like that as well. Quite handy addition to the usually fast expanding search space, that is not really inclined to converge to the global min. 
sim = [(0.2, 0.1, 0.5), (0.3, 0.1, 0.7), (0.4, 0.1, 0.3)]
`
def format_number(n):
    if isinstance(n, float):
        # Format float to remove trailing zeros and keep up to 4 decimal places
        return f"{n:.4f}".rstrip('0').rstrip('.')
    elif isinstance(n, int):
        # Simply convert integer to string
        return str(n)
sim_strings = [' '.join(format_number(x) for x in tuple) for tuple in sim]
`
I did not even know it is no longer maintained. Thanks for the quick heads up!

**Comment by xmatthias** [comment]
well we do keep it "installable" as part of a fork (otherwise some dependencies would not be updateable anymore) - but that's about it - there's no plans to add features, or fix additional bugs.

**Comment by HeinrichHaller** [comment]
Still get it not going..
```
@staticmethod
    def format_pair(pair):
        """Format the pair as a string with one decimal place."""
        return f"{pair[0]:.1f}_{pair[1]:.1f}"
```
```
# Use static method to format pairs
    simple_test_categories = [(0.2, 0.1), (0.3, 0.1), (0.4, 0.1)]
    formatted_categories = [Strategy.format_pair(pair) for pair in simple_test_categories]
    upper_lower_pairs = CategoricalParameter(formatted_categories, default="0.3_0.1", space='buy')
```
and then in populate_indicators: 
```
def populate_indicators(self, dataframe, metadata):
        """Generate all indicators using parameters from CategoricalParameter."""
        # Iterate over each value in the range of categorical parameters
        for val in self.upper_lower_pairs.range:
            fast, slow = map(float, val.split('_'))  # Split the string and convert to float
```
afterwards the dynamic creation with f"" of the column names. It still leads to the error: 
```
Epochs ━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   24/1000   2% • 0:00:13 • 0:03:43
2024-05-02 18:26:54,735 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/moritz/VisualStudio/freqtrade5/freqtrade/freqtrade/main.py", line 42, in main
    return_code = args['func'](args)
  File "/home/moritz/VisualStudio/freqtrade5/freqtrade/freqtrade/commands/optimize_commands.py", line 107, in start_hyperopt
    hyperopt.start()
  File "/home/moritz/VisualStudio/freqtrade5/freqtrade/freqtrade/optimize/hyperopt.py", line 615, in start
    asked, is_random = self.get_asked_points(n_points=current_jobs)
  File "/home/moritz/VisualStudio/freqtrade5/freqtrade/freqtrade/optimize/hyperopt.py", line 503, in get_asked_points
    asked = unique_list(self.opt.ask(n_points=n_points * 5 if i > 0 else n_points))
  File "/home/moritz/VisualStudio/freqtrade5/freqtrade/.venv/lib/python3.10/site-packages/skopt/optimizer/optimizer.py", line 395, in ask
    x = opt.ask()
  File "/home/moritz/VisualStudio/freqtrade5/freqtrade/.venv/lib/python3.10/site-packages/skopt/optimizer/optimizer.py", line 367, in ask
    return self._ask()
  File "/home/moritz/VisualStudio/freqtrade5/freqtrade/.venv/lib/python3.10/site-packages/skopt/optimizer/optimizer.py", line 446, in _ask
    min_delta_x = min([self.space.distance(next_x, xi)
  File "/home/moritz/VisualStudio/freqtrade5/freqtrade/.venv/lib/python3.10/site-packages/skopt/optimizer/optimizer.py", line 446, in <listcomp>
    min_delta_x = min([self.space.distance(next_x, xi)
  File "/home/moritz/VisualStudio/freqtrade5/freqtrade/.venv/lib/python3.10/site-packages/skopt/space/space.py", line 1138, in distance
    distance += dim.distance(a, b)
  File "/home/moritz/VisualStudio/freqtrade5/freqtrade/.venv/lib/python3.10/site-packages/skopt/space/space.py", line 743, in distance
    if not (a in self and b in self):
  File "/home/moritz/VisualStudio/freqtrade5/freqtrade/.venv/lib/python3.10/site-packages/skopt/space/space.py", line 720, in __contains__
    return point in self.categories
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
Could you maybe share how you do it? Thank you very much

**Comment by xmatthias** [comment]
well try it the simple way - hardcoding the strings instead of trying to overengineer things ? 

i doubt the segments you shared will cause this though -  at least not at first glance - so most likely you're loading a wrong strategy (duplicate strategies)...

**Comment by HeinrichHaller** [comment]
You are right, I was loading the wrong strategy. I did too many changes at once. I ended up with something like that: 
```
def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """Generate all indicators using parameters from CategoricalParameter."""
        print("Categorical parameter range:", self.upper_lower_pairs.range)
        print("Current value:", self.upper_lower_pairs.value)
        
        # Iterate over each value in the range of categorical parameters
        for val in self.upper_lower_pairs.range:
            print(f"Current val: {val}, type: {type(val)}")  # Debugging output
            fast, slow = map(float, val.split('_'))  # Split the string and convert to float
```

And the wrong datatype -list- still showed up. I restarted VS, restarted the .venv, ensured the pathes are correct.. I In the end I simply renamed the strategy and everything worked perfectly fine.  I am such a noob.
