### ISSUE TITLE
Backtesting: KeyError: 'ME'

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#10170]
## Describe your environment

  * Operating system: Windows Server 2022
  * Python Version: Current Miniconda (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2024.3 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

My backtest starts normally, and the process is calculating for quite a long time. So I have no syntax issues, I guess. To eliminate any hardware limitation, the VM has 50 GB RAM, with 32 CPU cores, the hardware capacity is only used by a small percentage during calculation.

I get this error:

`2024-05-04 15:32:12,398 - freqtrade.optimize.backtesting - INFO - Backtesting with data from 2024-04-25 00:00:00 up to 2024-04-28 00:00:00 (3 days).
2024-05-04 15:32:26,225 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "offsets.pyx", line 4447, in pandas._libs.tslibs.offsets._get_offset
KeyError: 'ME'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "offsets.pyx", line 4549, in pandas._libs.tslibs.offsets.to_offset
  File "offsets.pyx", line 4453, in pandas._libs.tslibs.offsets._get_offset
ValueError: Invalid frequency: ME

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\a1\.conda\envs\freqtrade\lib\site-packages\freqtrade\main.py", line 42, in main
    return_code = args['func'](args)
  File "C:\Users\a1\.conda\envs\freqtrade\lib\site-packages\freqtrade\commands\optimize_commands.py", line 58, in start_backtesting
    backtesting.start()
  File "C:\Users\a1\.conda\envs\freqtrade\lib\site-packages\freqtrade\optimize\backtesting.py", line 1414, in start
    results = generate_backtest_stats(
  File "C:\Users\a1\.conda\envs\freqtrade\lib\site-packages\freqtrade\optimize\optimize_reports\optimize_reports.py", line 559, in generate_backtest_stats
    strat_stats = generate_strategy_stats(pairlist, strategy, content,
  File "C:\Users\a1\.conda\envs\freqtrade\lib\site-packages\freqtrade\optimize\optimize_reports\optimize_reports.py", line 398, in generate_strategy_stats
    periodic_breakdown = {'periodic_breakdown': generate_all_periodic_breakdown_stats(results)}
  File "C:\Users\a1\.conda\envs\freqtrade\lib\site-packages\freqtrade\optimize\optimize_reports\optimize_reports.py", line 255, in generate_all_periodic_breakdown_stats
    result[period] = generate_periodic_breakdown_stats(trade_list, period)
  File "C:\Users\a1\.conda\envs\freqtrade\lib\site-packages\freqtrade\optimize\optimize_reports\optimize_reports.py", line 230, in generate_periodic_breakdown_stats
    resampled = results.resample(resample_period, on='close_date')
  File "C:\Users\a1\.conda\envs\freqtrade\lib\site-packages\pandas\core\generic.py", line 9439, in resample
    return get_resampler(
  File "C:\Users\a1\.conda\envs\freqtrade\lib\site-packages\pandas\core\resample.py", line 1969, in get_resampler
    tg = TimeGrouper(**kwds)
  File "C:\Users\a1\.conda\envs\freqtrade\lib\site-packages\pandas\core\resample.py", line 2046, in __init__
    freq = to_offset(freq)
  File "offsets.pyx", line 4460, in pandas._libs.tslibs.offsets.to_offset
  File "offsets.pyx", line 4557, in pandas._libs.tslibs.offsets.to_offset
ValueError: Invalid frequency: 1ME`

End of log code.

I do not see any place, where I can set this frequency (in the config file?)
Do I need to import any further package at the top of the strategy, which holds this "ME" ?

For your information: This Freqtrade instance works fine during dry run.

Do you need any further information?

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
Well what's your pandas version? (`pip show pandas`)

**Comment by myNextCoder** [comment]
Version: 2.1.2

**Comment by myNextCoder** [comment]
Perfect thanks: With version: 2.2.2 it works

**Comment by xmatthias** [comment]
Well freqtrade assumes that dependencies are the way we expect them.
If they're not - then usually that means that the [updating](https://www.freqtrade.io/en/latest/updating/) instruction hasn't been followed.

**Comment by myNextCoder** [comment]
Yes, it is a good thing, to update right away, if such an unclear issue takes place.
