### ISSUE TITLE
ccxt >= 4.3.21 is broken

### ISSUE THREAD

**Issue by stash86** [freqtrade/freqtrade#10211]
## Describe your environment

  * Operating system: Ubuntu
  * Python Version: 3.11 (`python -V`)
  * CCXT version: 4.3.21 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2024.5-dev modified (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

You can't start the bot on binance (not sure about other exchanges)
```
2024-05-15 00:47:15,018 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2024-05-15 00:47:15,197 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/ubuntu/freqtrade/freqtrade/main.py", line 43, in main
    return_code = args["func"](args)
                  ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/freqtrade/freqtrade/commands/trade_commands.py", line 24, in start_trading
    worker = Worker(args)
             ^^^^^^^^^^^^
  File "/home/ubuntu/freqtrade/freqtrade/worker.py", line 38, in __init__
    self._init(False)
  File "/home/ubuntu/freqtrade/freqtrade/worker.py", line 54, in _init
    self.freqtrade = FreqtradeBot(self._config)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/freqtrade/freqtrade/freqtradebot.py", line 106, in __init__
    self.wallets = Wallets(self.config, self.exchange)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/freqtrade/freqtrade/wallets.py", line 53, in __init__
    self.update()
  File "/home/ubuntu/freqtrade/freqtrade/wallets.py", line 180, in update
    self._update_live()
  File "/home/ubuntu/freqtrade/freqtrade/wallets.py", line 147, in _update_live
    positions = self._exchange.fetch_positions()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/freqtrade/freqtrade/exchange/common.py", line 173, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/freqtrade/freqtrade/exchange/exchange.py", line 1597, in fetch_positions
    positions: List[Dict] = self._api.fetch_positions(symbols)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/freqtrade/.venv/lib/python3.11/site-packages/ccxt/binance.py", line 9321, in fetch_positions
    return self.fetch_positions_risk(symbols, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/freqtrade/.venv/lib/python3.11/site-packages/ccxt/binance.py", line 9393, in fetch_positions_risk
    self.load_leverage_brackets(False, params)
  File "/home/ubuntu/freqtrade/.venv/lib/python3.11/site-packages/ccxt/binance.py", line 9041, in load_leverage_brackets
    return self.options['leverageBrackets']
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: 'leverageBrackets'
```
Tested the latest 4.3.22 also give the same error. Downgrading to 4.3.16 fix it.

Opened the issue on ccxt [here](https://github.com/ccxt/ccxt/issues/22495)

**Comment by xmatthias** [comment]
In my testing - it's fixed in the latest ccxt version (4.3.23)

Great catch and reporting (to ccxt)! :+1:
