### ISSUE TITLE
Error when Running the Backtester

### ISSUE THREAD

**Issue by masher91** [freqtrade/freqtrade#1021]
## Step 1: Have you search for this issue before posting it?
Yes 

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/freqtrade/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

  * Python Version: _____ (`python -V`)
Python 3.6.3 :: Anaconda, Inc.
  * CCXT version: _____ (`pip freeze | grep ccxt`)
ccxt==1.15.42

  
## Step 3: Describe the problem:
Backtester gives the blow error. Same error for all the backtest changes

### Steps to reproduce:

$ python3 ./freqtrade/main.py backtesting --export trades

### Relevant code exceptions or logs:

  ```
Traceback (most recent call last):
  File "./freqtrade/main.py", line 93, in <module>
    main(sys.argv[1:])
  File "./freqtrade/main.py", line 34, in main
    args.func(args)
  File "~/freqtrade/freqtrade/optimize/backtesting.py", line 366, in start
    config = setup_configuration(args)
  File "~/freqtrade/freqtrade/optimize/backtesting.py", line 346, in setup_configuration
    config = configuration.get_config()
  File "~/freqtrade/freqtrade/configuration.py", line 222, in get_config
    self.config = self.load_config()
  File "~/freqtrade/freqtrade/configuration.py", line 34, in load_config
    config = self._load_config_file(self.args.config)
  File "~/freqtrade/freqtrade/configuration.py", line 62, in _load_config_file
    conf = json.load(file)
  File "~/anaconda3/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "~/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "~/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "~/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 4 column 21 (char 77)
  ```

**Comment by xmatthias** [comment]
Can you please add your `config.json` file. This looks like a configuration issue...

**Comment by shusso** [comment]
please feel to re-open if the following doesn't work
```
cp config.json.example config.json
python3 freqtrade --datadir freqtrade/tests/testdata backtesting
```
