### ISSUE TITLE
Hope to support spot data indicators for futures trading @Binance

### ISSUE THREAD

**Issue by gmvp3** [freqtrade/freqtrade#10242]
## Describe your environment
  
  * Freqtrade Version: ____ 2024.4
  * Binance

## Describe the enhancement
```
def informative_pairs(self):
        informative_pairs = [("BTC/TUSD", "5m", 'spot'), ("BTC/TUSD", "15m", 'spot')]
        return informative_pairs

def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        if not self.dp:
            return dataframe
 informative = self.dp.get_pair_dataframe(pair="BTC/USDT", timeframe=self.timeframe, candle_type="spot")
```

Can perform normal backtesting, but reports an error when running dry：

2024-05-25 18:25:40,925 - freqtrade.data.dataprovider - WARNING - No data found for (BTC/USDT, 5m, spot).
2024-05-25 18:25:40,926 - freqtrade.data.dataprovider - WARNING - No data found for (BTC/USDT, 15m, spot).
2024-05-25 18:25:40,927 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error input_arrays parameter missing required data key: close calling <bound method IStrategy._analyze_ticker_internal of <cross2.cross2 object at 0x7f8569c50ad0>>
Traceback (most recent call last):
  File "/root/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 27, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/root/freqtrade/freqtrade/strategy/interface.py", line 918, in _analyze_ticker_internal
    dataframe = self.analyze_ticker(dataframe, metadata)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/freqtrade/freqtrade/strategy/interface.py", line 896, in analyze_ticker
    dataframe = self.advise_indicators(dataframe, metadata)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/freqtrade/freqtrade/strategy/interface.py", line 1423, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/freqtrade/user_data/strategies/cross2.py", line 51, in populate_indicators
    informative[f'sma{period}'] = ta.SMA(informative, timeperiod=period)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "talib/_abstract.pxi", line 444, in talib._ta_lib.Function.__call__
  File "talib/_abstract.pxi", line 303, in talib._ta_lib.Function.set_function_args
  File "talib/_abstract.pxi", line 251, in talib._ta_lib.Function.set_input_arrays
Exception: input_arrays parameter missing required data key: close
2024-05-25 18:25:40,928 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair BTC/USDT:USDT: input_arrays parameter missing required data key: close
2024-05-25 18:25:40,936 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair BTC/USDT:USDT

**Comment by xmatthias** [comment]
your pair naming is wrong.

you fetch BTC/TUSD in informative pairs - but expect the bot to have BTC/USDT available - which is simply not going to happen.

 

I'd strongly suggest to use the [`@informative`](https://www.freqtrade.io/en/stable/strategy-customization/#informative-pairs-decorator-informative) decorator to avoid such mistakes. 

It's there for convenience - as it'll eliminate the need to manually define the informative pairs explicitly - and hence will help you eliminate such simple mistakes before they happen.

**Comment by gmvp3** [comment]
I have tried using [@informative], but there will be an error during the backtesting

2024-05-25 21:36:57,862 - freqtrade.data.dataprovider - INFO - Loading data for BTC/USDT:USDT 15m from 2024-05-01 00:00:00 to 2024-05-20 00:00:00
2024-05-25 21:36:57,863 - freqtrade.data.history.datahandlers.idatahandler - WARNING - No history for BTC/USDT:USDT, spot, 15m found. Use `freqtrade download-data` to download the data
2024-05-25 21:36:57,863 - freqtrade.data.dataprovider - WARNING - No data found for (BTC/USDT:USDT, 15m, spot).
2024-05-25 21:36:57,868 - freqtrade.data.dataprovider - INFO - Loading data for BTC/USDT:USDT 1h from 2024-05-01 00:00:00 to 2024-05-20 00:00:00
2024-05-25 21:36:57,869 - freqtrade.data.history.datahandlers.idatahandler - WARNING - No history for BTC/USDT:USDT, spot, 1h found. Use `freqtrade download-data` to download the data
2024-05-25 21:36:57,869 - freqtrade.data.dataprovider - WARNING - No data found for (BTC/USDT:USDT, 1h, spot).
2024-05-25 21:36:57,877 - freqtrade.data.dataprovider - INFO - Loading data for BTC/USDT:USDT 5m from 2024-05-01 00:00:00 to 2024-05-20 00:00:00
2024-05-25 21:36:57,878 - freqtrade.data.history.datahandlers.idatahandler - WARNING - No history for BTC/USDT:USDT, spot, 5m found. Use `freqtrade download-data` to download the data
2024-05-25 21:36:57,878 - freqtrade.data.dataprovider - WARNING - No data found for (BTC/USDT:USDT, 5m, spot).

**Comment by xmatthias** [comment]
> No history for BTC/USDT:USDT, spot, 15m found. Use freqtrade download-data to download the data

BTC/USDT:USDT is NOT a [spot pair](https://www.freqtrade.io/en/latest/bot-basics/#pair-naming).

This is now the 3rd time you're hitting **the same question** - each time being given the same answer and link.
I expect from you now to please take the time to read (and understand!) the documentation, especially the one linked in this post. If you don't undersand it, read it **again and again** until you got it.

Especially this part (how is which pair named) is VERY simple - and not understanding this clear sign that you don't bother to read what you're linked to.


While we do provide help here - we do this voluntarily, in our free time.
As such, please understand that we have the basic requirement that people do their own research to avoid wasting our time.

Thanks for your understanding.

**Comment by gmvp3** [comment]
Sorry, please let me explain,
When I use @ informative ('1h ', candle_type='spot '), I can run dry, but there will be errors during the backtesting.
When I use @ informative ('1h ',' btc/usdt ', candle_type='spot'), historical spot data can be obtained normally, but indicator parameters may not be recognized.
I don't know where the problem is, I'm very sorry.

**Comment by xmatthias** [comment]
> When I use @ informative ('1h ', candle_type='spot '), I can run dry, but there will be errors during the backtesting.

You can run in dry - but you will NOT be getting spot data - but rather futures data, as the pair will be "the one being analyzed" - which in futures mode, is `BTC/USDT:USDT`.

> When I use @ informative ('1h ',' btc/usdt ', candle_type='spot'), historical spot data can be obtained normally, but indicator parameters may not be recognized.

Not sure what you mean with this.
it's syntax errors (Pair names should be uppercase and have no leading/trailing) - which will probably cause a "no pair found" error internally - yielding an empty result to you.

**Comment by gmvp3** [comment]
So according to my understanding, there is no support for using spot data for futures trading yet, right?

When I use @ informative ('1h ',' btc/usdt ', candle_type='spot') in backtesting,historical spot data can be loaded.but get error:
```
--------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 27, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/root/freqtrade/freqtrade/strategy/interface.py", line 918, in _analyze_ticker_internal
    dataframe = self.analyze_ticker(dataframe, metadata)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/freqtrade/freqtrade/strategy/interface.py", line 897, in analyze_ticker
    dataframe = self.advise_entry(dataframe, metadata)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/freqtrade/freqtrade/strategy/interface.py", line 1438, in advise_entry
    df = self.populate_entry_trend(dataframe, metadata)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/freqtrade/user_data/strategies/test.py", line 27, in populate_entry_trend
    (dataframe['close_5m'] > dataframe['highest_high_5m'])
     ~~~~~~~~~^^^^^^^^^^^^
  File "/root/freqtrade/.venv/lib/python3.11/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/freqtrade/.venv/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'close_5m'
```
-------------------------------------------------------------------------------------------------------------------------------
my strategie as below:
```
import talib.abstract as ta
from freqtrade.strategy import IStrategy, informative
from pandas import DataFrame

class test(IStrategy):
    INTERFACE_VERSION = 3
    timeframe = '5m'
    can_short = True
    stoploss = -0.04
    
    @informative('5m', candle_type='spot')
    def populate_indicators_5m(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        if not self.dp:
            return dataframe
        dataframe['highest_high'] = dataframe['high'].shift().rolling(10).max()
        dataframe['lowest_low'] = dataframe['low'].shift().rolling(10).min()
        return dataframe
    
    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
            if not self.dp:
                return dataframe
            return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (   
                (dataframe['close_5m'] > dataframe['highest_high_5m'])

            ),
            ['enter_long', 'enter_tag']] = (1, 'break_high')

        dataframe.loc[
            (
                (dataframe['close_5m'] < dataframe['lowest_low_5m'])
            ),
            ['enter_short', 'enter_tag']] = (1, 'break_low')
        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[:, 'exit_long'] = 0
        dataframe.loc[:, 'exit_short'] = 0
        return dataframe
```

**Comment by xmatthias** [comment]
your strategy does NOT use `@ informative ('1h ',' btc/usdt ', candle_type='spot')` (which is wrong, anyway), but `@informative('5m', candle_type='spot')` - which is as i said above - not valid and will most likely give you Futures data (as the pair is BTC/USDT:USDT).

the correct way is `@informative('5m', 'BTC/USDT', candle_type='spot')`.

**Comment by gmvp3** [comment]
yes, when I use @informative('5m', 'BTC/USDT', candle_type='spot') will get error。So depressed, sigh

Traceback (most recent call last):
  File "/root/freqtrade/freqtrade/main.py", line 42, in main
    return_code = args['func'](args)
                  ^^^^^^^^^^^^^^^^^^
  File "/root/freqtrade/freqtrade/commands/optimize_commands.py", line 58, in start_backtesting
    backtesting.start()
  File "/root/freqtrade/freqtrade/optimize/backtesting.py", line 1411, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/freqtrade/freqtrade/optimize/backtesting.py", line 1346, in backtest_one_strategy
    results = self.backtest(
              ^^^^^^^^^^^^^^
  File "/root/freqtrade/freqtrade/optimize/backtesting.py", line 1224, in backtest
    data: Dict = self._get_ohlcv_as_lists(processed)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/freqtrade/freqtrade/optimize/backtesting.py", line 383, in _get_ohlcv_as_lists
    df_analyzed = self.strategy.ft_advise_signals(pair_data, {'pair': pair})
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/freqtrade/freqtrade/strategy/interface.py", line 1404, in ft_advise_signals
    dataframe = self.advise_entry(dataframe, metadata)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/freqtrade/freqtrade/strategy/interface.py", line 1438, in advise_entry
    df = self.populate_entry_trend(dataframe, metadata)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/freqtrade/user_data/strategies/test.py", line 27, in populate_entry_trend
    (dataframe['close_5m'] > dataframe['highest_high_5m'])
     ~~~~~~~~~^^^^^^^^^^^^
  File "/root/freqtrade/.venv/lib/python3.11/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/freqtrade/.venv/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'close_5m'

**Comment by xmatthias** [comment]
This got nothing to do with informative pairs - at least not really.

looking at your strategy - why would you **not** get this error?

`close_5m` is never assigned - not as part of an informative pair - nor as part of anything else.
`@informative` will assign this as `btc_usdt_open_5m` - just as the documentation explains.

adding the pair argument MUST change the column renaming - as you're now "prone" to encounter collisions - as  you could have the following decorators...
`@informative('5m', 'BTC/USDT', candle_type='spot')`
`@informative('5m', 'XRP/USDT', candle_type='spot')`
`@informative('5m', 'ETH/USDT', candle_type='spot')`

Now which one is close_5m? :laughing: 

![image](https://github.com/freqtrade/freqtrade/assets/5024695/a77abe51-850e-4514-a13e-a04a66125128)

**Comment by gmvp3** [comment]
Great, you are my hero, it works now. I just started freqtrade, thank you for your patience.
