### ISSUE TITLE
 freqtrade - ERROR - Could not load markets,

### ISSUE THREAD

**Issue by WinPoss** [freqtrade/freqtrade#10245]
## Describe your environment

  * Operating system: Debian 12
  * Python Version: 3.12
  * CCXT version: 4.3.11
  * Freqtrade Version: 2024.4
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

I installed freqtrade using the default [Docker installation method](https://www.freqtrade.io/en/stable/docker_quickstart/), and when I tried to start it, I received the following error indicating that the request timestamp exceeded the server's time.

```
freqtrade  | 2024-05-26 05:13:29,630 - freqtrade.exchange.exchange - INFO - Using CCXT 4.3.11
freqtrade  | 2024-05-26 05:13:29,631 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}}
freqtrade  | 2024-05-26 05:13:29,640 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}}
freqtrade  | 2024-05-26 05:13:29,649 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
freqtrade  | 2024-05-26 05:13:29,897 - freqtrade.exchange.exchange - ERROR - Unable to initialize markets.
freqtrade  | Traceback (most recent call last):
freqtrade  |   File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/base/exchange.py", line 629, in fetch
freqtrade  |     response.raise_for_status()
freqtrade  |   File "/home/ftuser/.local/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
freqtrade  |     raise HTTPError(http_error_msg, response=self)
freqtrade  | requests.exceptions.HTTPError: 400 Client Error:  for url: https://api.binance.com/sapi/v1/capital/config/getall?timestamp=1716700409649&recvWindow=10000&signature=634da0d650a8575b42c83a964d3df403d52ce9c926197b4c94198d40b6f373a8
freqtrade  | 
freqtrade  | During handling of the above exception, another exception occurred:
freqtrade  | 
freqtrade  | Traceback (most recent call last):
freqtrade  |   File "/freqtrade/freqtrade/exchange/exchange.py", line 493, in _load_markets
freqtrade  |     self._markets = self._api.load_markets(params={})
freqtrade  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
freqtrade  |   File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/base/exchange.py", line 1515, in load_markets
freqtrade  |     currencies = self.fetch_currencies()
freqtrade  |                  ^^^^^^^^^^^^^^^^^^^^^^^
freqtrade  |   File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/binance.py", line 2625, in fetch_currencies
freqtrade  |     response = self.sapiGetCapitalConfigGetall(params)
freqtrade  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
freqtrade  |   File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/base/types.py", line 35, in unbound_method
freqtrade  |     return _self.request(self.path, self.api, self.method, params, config=self.config)
freqtrade  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
freqtrade  |   File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/binance.py", line 10298, in request
freqtrade  |     response = self.fetch2(path, api, method, params, headers, body, config)
freqtrade  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
freqtrade  |   File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/base/exchange.py", line 3651, in fetch2
freqtrade  |     return self.fetch(request['url'], request['method'], request['headers'], request['body'])
freqtrade  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
freqtrade  |   File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/base/exchange.py", line 645, in fetch
freqtrade  |     skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
freqtrade  |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
freqtrade  |   File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/binance.py", line 10266, in handle_errors
freqtrade  |     self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
freqtrade  |   File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/base/exchange.py", line 4048, in throw_exactly_matched_exception
freqtrade  |     raise exact[string](message)
freqtrade  | ccxt.base.errors.InvalidNonce: binance {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}
freqtrade  | 2024-05-26 05:13:29,902 - freqtrade - ERROR - Could not load markets, therefore cannot start. Please investigate the above error for more details.
```

Then the following part is my configuration file settings

```
"exchange": {
        "name": "binance",
        "key": "my_key",
        "secret": "my_secret",
        "ccxt_config": {},
        "ccxt_async_config": {},
        "pair_whitelist": [],
        "pair_blacklist": [
            "TUSD/USDT:USDT",
            "USDP/USDT:USDT",
            "BUSD/USDT:USDT",
            "FDUSD/USDT:USDT",
            "USDC/USDT:USDT"
        ]
    },
```

When I used the virtual environment, the bot was running correctly. However, when I switched to live trading, it displayed this error.

I would appreciate your help in resolving this issue. Thank you.

**Comment by xmatthias** [comment]
> Timestamp for this request was 1000ms ahead of the server's time.

Quite simply - your system time is off.
When using binance in live mode, this is checked (by binance) - and requests that don't show a clock that's out by more than 1 second are considered a security risk and are therefore rejected.
Dry-run will not see this since there's no API key attached, so only public methods from the binance API are used.

While there's workarounds to this (a parameter in ccxt) - you really shouldn't go that route, but instead simply make sure that your system's clock is syncronized regularily - as this can also have other impacts, besides binance rejecting your requests.

**Comment by WinPoss** [comment]
OK, the problem has been solved, thank you!

**Comment by epigramx** [comment]
> your system time is off

Why is a synced time required, in *backtesting*?

**Comment by xmatthias** [comment]
Because also backtesting needs to fetch basic market data (for example the maximum allowed trade size, trading limits, what pairs are actually available, ...).

You might want to ask the exchange - why do you care about time sync if I'm using "get /markets".
Nothing we can do (it's an exchange requirement, really) - but feel free to open a support request with the exchange asking them to remove this requirement.

**Comment by epigramx** [comment]
Ah I see. I doubt they'd want it changed. It's probably more efficient(and for security) to keep it by default required.
