### ISSUE TITLE
FreqAi Error Unexpected error Pipeline expected Index

### ISSUE THREAD

**Issue by bryanTechera** [freqtrade/freqtrade#10261]
## Describe your environment

  * Operating system: Ubuntu 12.04 LTS
  * Python Version:  3.12.3 
  * CCXT version: 3.1.44
  * Freqtrade Version: 2024.5-dev-ea27a1ec1
  
## Your question
I am building a strategy in freqai, when adding new indicators with '%' I started receiving this error in the console
```
024-05-27 16:25:51,310 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error Pipeline expected Index(['%-rsi-8_8_SOL/USDTUSDT_15m', '%-adx-8_8_SOL/USDTUSDT_15m',
       '%-willr-8_8_SOL/USDTUSDT_15m', '%-wma-8_8_SOL/USDTUSDT_15m',
       '%-rsi-50_50_SOL/USDTUSDT_15m', '%-adx-50_50_SOL/USDTUSDT_15m',
       '%-willr-50_50_SOL/USDTUSDT_15m', '%-wma-50_50_SOL/USDTUSDT_15m',
       '%-rsi-100_100_SOL/USDTUSDT_15m', '%-adx-100_100_SOL/USDTUSDT_15m',
       ...
       '%-ULTOSC_gen_shift-8_ETH/USDTUSDT_8h',
       '%-fastk_gen_shift-8_ETH/USDTUSDT_8h',
       '%-fastd_gen_shift-8_ETH/USDTUSDT_8h',
       '%-avg-price_gen_shift-8_ETH/USDTUSDT_8h',
       '%-bb-bandwidth_gen_shift-8_ETH/USDTUSDT_8h',
       '%-macd_gen_shift-8_ETH/USDTUSDT_8h',
       '%-macd_signal_gen_shift-8_ETH/USDTUSDT_8h',
       '%-macd_hist_gen_shift-8_ETH/USDTUSDT_8h',
       '%-med-price_gen_shift-8_ETH/USDTUSDT_8h',
       '%-typ-price_gen_shift-8_ETH/USDTUSDT_8h'],
      dtype='object', length=2490) but got Index(['%-macd_diff', '%-intersect-p', '%-area',
       '%-macd_diff_SOL/USDTUSDT_15m', '%-intersect-p_SOL/USDTUSDT_15m',
       '%-area_SOL/USDTUSDT_15m', '%-macd_diff_8_SOL/USDTUSDT_15m',
       '%-intersect-p_8_SOL/USDTUSDT_15m', '%-area_8_SOL/USDTUSDT_15m',
       '%-rsi-8_8_SOL/USDTUSDT_15m',
       ...
       '%-ULTOSC_gen_shift-8_ETH/USDTUSDT_8h',
       '%-fastk_gen_shift-8_ETH/USDTUSDT_8h',
       '%-fastd_gen_shift-8_ETH/USDTUSDT_8h',
       '%-avg-price_gen_shift-8_ETH/USDTUSDT_8h',
       '%-bb-bandwidth_gen_shift-8_ETH/USDTUSDT_8h',
       '%-macd_gen_shift-8_ETH/USDTUSDT_8h',
       '%-macd_signal_gen_shift-8_ETH/USDTUSDT_8h',
       '%-macd_hist_gen_shift-8_ETH/USDTUSDT_8h',
       '%-med-price_gen_shift-8_ETH/USDTUSDT_8h',
       '%-typ-price_gen_shift-8_ETH/USDTUSDT_8h'],
      dtype='object', length=2628). calling <bound method IStrategy._analyze_ticker_internal of <StrategyPG.StrategyPG object at 0x77204c2fa270>>
Traceback (most recent call last):
  File "/home/michael/Documentos/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 28, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/michael/Documentos/freqtrade/freqtrade/strategy/interface.py", line 1060, in _analyze_ticker_internal
    dataframe = self.analyze_ticker(dataframe, metadata)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michael/Documentos/freqtrade/freqtrade/strategy/interface.py", line 1039, in analyze_ticker
    dataframe = self.advise_indicators(dataframe, metadata)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michael/Documentos/freqtrade/freqtrade/strategy/interface.py", line 1610, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michael/Documentos/v9_pg/user_data/strategies/StrategyPG.py", line 245, in populate_indicators
    return self.freqai.start(dataframe, metadata, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michael/Documentos/freqtrade/freqtrade/freqai/freqai_interface.py", line 149, in start
    dk = self.start_live(dataframe, metadata, strategy, self.dk)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michael/Documentos/freqtrade/freqtrade/freqai/freqai_interface.py", line 457, in start_live
    self.build_strategy_return_arrays(dataframe, dk, metadata["pair"], trained_timestamp)
  File "/home/michael/Documentos/freqtrade/freqtrade/freqai/freqai_interface.py", line 470, in build_strategy_return_arrays
    pred_df, do_preds = self.predict(dataframe, dk)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michael/Documentos/freqtrade/freqtrade/freqai/base_models/BaseRegressionModel.py", line 106, in predict
    dk.data_dictionary["prediction_features"], outliers, _ = dk.feature_pipeline.transform(
                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michael/Documentos/freqtrade/.venv/lib/python3.12/site-packages/datasieve/pipeline.py", line 92, in transform
    X, y, sample_weight = self._validate_arguments(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michael/Documentos/freqtrade/.venv/lib/python3.12/site-packages/datasieve/pipeline.py", line 168, in _validate_arguments
    raise Exception(f"Pipeline expected {self.features_in} but got {X.columns}.")
Exception: Pipeline expected Index(['%-rsi-8_8_SOL/USDTUSDT_15m', '%-adx-8_8_SOL/USDTUSDT_15m',
       '%-willr-8_8_SOL/USDTUSDT_15m', '%-wma-8_8_SOL/USDTUSDT_15m',
       '%-rsi-50_50_SOL/USDTUSDT_15m', '%-adx-50_50_SOL/USDTUSDT_15m',
       '%-willr-50_50_SOL/USDTUSDT_15m', '%-wma-50_50_SOL/USDTUSDT_15m',
       '%-rsi-100_100_SOL/USDTUSDT_15m', '%-adx-100_100_SOL/USDTUSDT_15m',
       ...
       '%-ULTOSC_gen_shift-8_ETH/USDTUSDT_8h',
       '%-fastk_gen_shift-8_ETH/USDTUSDT_8h',
       '%-fastd_gen_shift-8_ETH/USDTUSDT_8h',
       '%-avg-price_gen_shift-8_ETH/USDTUSDT_8h',
       '%-bb-bandwidth_gen_shift-8_ETH/USDTUSDT_8h',
       '%-macd_gen_shift-8_ETH/USDTUSDT_8h',
       '%-macd_signal_gen_shift-8_ETH/USDTUSDT_8h',
       '%-macd_hist_gen_shift-8_ETH/USDTUSDT_8h',
       '%-med-price_gen_shift-8_ETH/USDTUSDT_8h',
       '%-typ-price_gen_shift-8_ETH/USDTUSDT_8h'],
      dtype='object', length=2490) but got Index(['%-macd_diff', '%-intersect-p', '%-area',
       '%-macd_diff_SOL/USDTUSDT_15m', '%-intersect-p_SOL/USDTUSDT_15m',
       '%-area_SOL/USDTUSDT_15m', '%-macd_diff_8_SOL/USDTUSDT_15m',
       '%-intersect-p_8_SOL/USDTUSDT_15m', '%-area_8_SOL/USDTUSDT_15m',
       '%-rsi-8_8_SOL/USDTUSDT_15m',
       ...
       '%-ULTOSC_gen_shift-8_ETH/USDTUSDT_8h',
       '%-fastk_gen_shift-8_ETH/USDTUSDT_8h',
       '%-fastd_gen_shift-8_ETH/USDTUSDT_8h',
       '%-avg-price_gen_shift-8_ETH/USDTUSDT_8h',
       '%-bb-bandwidth_gen_shift-8_ETH/USDTUSDT_8h',
       '%-macd_gen_shift-8_ETH/USDTUSDT_8h',
       '%-macd_signal_gen_shift-8_ETH/USDTUSDT_8h',
       '%-macd_hist_gen_shift-8_ETH/USDTUSDT_8h',
       '%-med-price_gen_shift-8_ETH/USDTUSDT_8h',
       '%-typ-price_gen_shift-8_ETH/USDTUSDT_8h'],
      dtype='object', length=2628).
2024-05-27 16:25:51,310 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair SOL/USDT:USDT: Pipeline expected Index(['%-rsi-8_8_SOL/USDTUSDT_15m', '%-adx-8_8_SOL/USDTUSDT_15m',
       '%-willr-8_8_SOL/USDTUSDT_15m', '%-wma-8_8_SOL/USDTUSDT_15m',
       '%-rsi-50_50_SOL/USDTUSDT_15m', '%-adx-50_50_SOL/USDTUSDT_15m',
       '%-willr-50_50_SOL/USDTUSDT_15m', '%-wma-50_50_SOL/USDTUSDT_15m',
       '%-rsi-100_100_SOL/USDTUSDT_15m', '%-adx-100_100_SOL/USDTUSDT_15m',
       ...
       '%-ULTOSC_gen_shift-8_ETH/USDTUSDT_8h',
       '%-fastk_gen_shift-8_ETH/USDTUSDT_8h',
       '%-fastd_gen_shift-8_ETH/USDTUSDT_8h',
       '%-avg-price_gen_shift-8_ETH/USDTUSDT_8h',
       '%-bb-bandwidth_gen_shift-8_ETH/USDTUSDT_8h',
       '%-macd_gen_shift-8_ETH/USDTUSDT_8h',
       '%-macd_signal_gen_shift-8_ETH/USDTUSDT_8h',
       '%-macd_hist_gen_shift-8_ETH/USDTUSDT_8h',
       '%-med-price_gen_shift-8_ETH/USDTUSDT_8h',
       '%-typ-price_gen_shift-8_ETH/USDTUSDT_8h'],
      dtype='object', length=2490) but got Index(['%-macd_diff', '%-intersect-p', '%-area',
       '%-macd_diff_SOL/USDTUSDT_15m', '%-intersect-p_SOL/USDTUSDT_15m',
       '%-area_SOL/USDTUSDT_15m', '%-macd_diff_8_SOL/USDTUSDT_15m',
       '%-intersect-p_8_SOL/USDTUSDT_15m', '%-area_8_SOL/USDTUSDT_15m',
       '%-rsi-8_8_SOL/USDTUSDT_15m',
       ...
       '%-ULTOSC_gen_shift-8_ETH/USDTUSDT_8h',
       '%-fastk_gen_shift-8_ETH/USDTUSDT_8h',
       '%-fastd_gen_shift-8_ETH/USDTUSDT_8h',
       '%-avg-price_gen_shift-8_ETH/USDTUSDT_8h',
       '%-bb-bandwidth_gen_shift-8_ETH/USDTUSDT_8h',
       '%-macd_gen_shift-8_ETH/USDTUSDT_8h',
       '%-macd_signal_gen_shift-8_ETH/USDTUSDT_8h',
       '%-macd_hist_gen_shift-8_ETH/USDTUSDT_8h',
       '%-med-price_gen_shift-8_ETH/USDTUSDT_8h',
       '%-typ-price_gen_shift-8_ETH/USDTUSDT_8h'],
      dtype='object', length=2628).
```

I have tried deleting the models and retraining, but the error still persists. Below I leave my configuration
```
"freqai": {
        "enabled": true,
        "train_period_days": 300,
        "live_retrain_hours": 0.5,
        "continual_learning": true,
        "identifier": "StrategyPG_77",
        "fit_live_predictions_candles": 1500,
        "save_backtest_models": true,
        "feature_parameters": {
            "include_corr_pairlist": [
                "BTC/USDT:USDT",
                "ETH/USDT:USDT"
            ],
            "include_timeframes": [
                "1h",
                "4h",
                "8h"
            ],
            "DI_threshold": 1,
            "weight_factor": 0.9,
            "principal_component_analysis": false,
            "use_SVM_to_remove_outliers": false,
            "use_DBSCAN_to_remove_outliers": false,
            "noise_standard_deviation": 0.1,
            "label_period_candles": 32,
            "include_shifted_candles": 8,
            "indicator_periods_candles": [
                8,
                50,
                100
            ],
            "plot_feature_importances": 50,
            "buffer_train_data_candles": 100
        },
        "data_split_parameters": {
            "test_size": 0,
            "random_state": 1,
            "shuffle": false
        },
        "model_training_parameters": {
            "n_estimators": 144,
            "n_jobs": 12,
            "verbosity": 1
        }
    }
```
*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by robcaulk** [comment]
Hello,

You are passing diffferent features to your model than what you trained the model on.

This is solved by either deleting the model folder or using a new identifier.

thanks,

rob
