### ISSUE TITLE
Cannot pickle when trying to hyperopt with more than one CPU core. 

### ISSUE THREAD

**Issue by stigmaknight123** [freqtrade/freqtrade#10287]
* Operating system: Windows 10
  * Python Version: 3.12  
  * CCXT version: 4.3.35 
  * Freqtrade Version: 2024.5 
  

Trying to hyperopt with more than one CPU core I get the cannot pickle error. When using only one CPU I can hyperopt. 

```
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.12/site-packages/joblib/externals/loky/backend/queues.py", line 159, in _feed
    obj_ = dumps(obj, reducers=reducers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/joblib/externals/loky/backend/reduction.py", line 215, in dumps
    dump(obj, buf, reducers=reducers, protocol=protocol)
  File "/home/ftuser/.local/lib/python3.12/site-packages/joblib/externals/loky/backend/reduction.py", line 208, in dump
    _LokyPickler(file, reducers=reducers, protocol=protocol).dump(obj)
  File "/home/ftuser/.local/lib/python3.12/site-packages/joblib/externals/cloudpickle/cloudpickle.py", line 1245, in dump
    return super().dump(obj)
           ^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/joblib/externals/loky/cloudpickle_wrapper.py", line 15, in __reduce__
    _pickled_object = dumps(self._obj)
                      ^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/joblib/externals/cloudpickle/cloudpickle.py", line 1479, in dumps
    cp.dump(obj)
  File "/home/ftuser/.local/lib/python3.12/site-packages/joblib/externals/cloudpickle/cloudpickle.py", line 1245, in dump
    return super().dump(obj)
           ^^^^^^^^^^^^^^^^^
TypeError: cannot pickle '_thread._local' object
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 43, in main
    return_code = args["func"](args)
                  ^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 109, in start_hyperopt
    hyperopt.start()
  File "/freqtrade/freqtrade/optimize/hyperopt.py", line 671, in start
    f_val = self.run_optimizer_parallel(parallel, asked)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/optimize/hyperopt.py", line 487, in run_optimizer_parallel
    return parallel(
  File "/home/ftuser/.local/lib/python3.12/site-packages/joblib/parallel.py", line 2007, in __call__
    return output if self.return_generator else list(output)
                                                ^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/joblib/parallel.py", line 1650, in _get_outputs
    yield from self._retrieve()
  File "/home/ftuser/.local/lib/python3.12/site-packages/joblib/parallel.py", line 1754, in _retrieve
    self._raise_error_fast()
  File "/home/ftuser/.local/lib/python3.12/site-packages/joblib/parallel.py", line 1789, in _raise_error_fast
    error_job.get_result(self.timeout)
  File "/home/ftuser/.local/lib/python3.12/site-packages/joblib/parallel.py", line 745, in get_result
    return self._return_or_raise()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/joblib/parallel.py", line 763, in _return_or_raise
    raise self._result
_pickle.PicklingError: Could not pickle the task to send it to the workers.
```

**Comment by xmatthias** [comment]
Your strategy seems to add some additional objects - based on the error - most likely something around a threading.lock, or threading.thread - though what exactly it is is difficult to tell.

Unfortunately, python requires the ability to pickle an object to transfer it to other processes (the requirement to work on more than one core) - so if your strategy has so-called "non-picklable objects" (locks, threads, open sockets, ...) - then hyperopt will be limited to one core.

Your best bet will be to remove all suspected objects, and then add them back to the strategy one by one.
please note: the presence of the object is sufficient - it doesn't actually matter if it's being used (like - if you're assigning something to that object).

**Comment by xmatthias** [comment]
Closing this as i think your question has been answered (and there's nothing further to try and assist you with the given information).

Feel free to comment below if it's still unclear.

**Comment by HardikKSavaliya** [comment]
Face the Same Issue with macOS and same error. @xmatthias your assistance will be highly apprciated

**Comment by xmatthias** [comment]
well the answer will be the same as above.
"something" in your strategy is not picklable. What that is - up to you to find out, really.

it's however not "the same" - as you'll not be using the same strategy - hence please open a new issue.
