### ISSUE TITLE
Error running on ubuntu system

### ISSUE THREAD

**Issue by l3104468710** [freqtrade/freqtrade#10344]
Error running on ubuntu system

## Describe your environment

  * Operating system: ____ubuntu 20.04
  * Python Version: _____ (`python -V`) python 3.9
  * CCXT version: _____ (`pip freeze | grep ccxt`) cctx 4.3.35
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker) freqtrade 2024.5
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

  1. _____Install docker and freqtrade
  2. _____Running a virtual environment
  3. _____"docker compose run --rm freqtrade" command to run freqtrade
  
### Observed Results:

  * What happened?
 report errors
  
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here

2024-06-20 12:53:22,743 - freqtrade.configuration.deprecated_settings - WARNING - DEPRECATED: The `order_types.emergencyexit` setting is deprecated and will be removed in the next versions of Freqtrade. Please use the `order_types.emergency_exit` setting in your configuration instead.
2024-06-20 12:53:22,743 - freqtrade.configuration.deprecated_settings - WARNING - DEPRECATED: The `order_types.forceexit` setting is deprecated and will be removed in the next versions of Freqtrade. Please use the `order_types.force_exit` setting in your configuration instead.
2024-06-20 12:53:22,743 - freqtrade.configuration.deprecated_settings - WARNING - DEPRECATED: The `order_types.forceentry` setting is deprecated and will be removed in the next versions of Freqtrade. Please use the `order_types.force_entry` setting in your configuration instead.
2024-06-20 12:53:22,744 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2024-06-20 12:53:22,749 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2024-06-20 12:53:22,749 - freqtrade.exchange.exchange - INFO - Using CCXT 4.3.35
2024-06-20 12:53:22,764 - freqtrade.exchange.exchange - INFO - Using Exchange "KuCoin"
2024-06-20 12:53:23,776 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 43, in main
    return_code = args["func"](args)
                  ^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 24, in start_trading
    worker = Worker(args)
             ^^^^^^^^^^^^
  File "/freqtrade/freqtrade/worker.py", line 38, in __init__
    self._init(False)
  File "/freqtrade/freqtrade/worker.py", line 54, in _init
    self.freqtrade = FreqtradeBot(self._config)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/freqtradebot.py", line 100, in __init__
    self.exchange = ExchangeResolver.load_exchange(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 44, in load_exchange
    exchange = ExchangeResolver._load_exchange(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 77, in _load_exchange
    exchange = ex_class(**kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/exchange/exchange.py", line 236, in __init__
    self._load_markets()
  File "/freqtrade/freqtrade/exchange/exchange.py", line 545, in _load_markets
    self._markets = self._api.load_markets(params={})
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/base/exchange.py", line 1540, in load_markets
    markets = self.fetch_markets(params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/kucoin.py", line 1036, in fetch_markets
    data = self.safe_list(response, 'data')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/base/exchange.py", line 1898, in safe_list
    return self.safe_list_n(dictionaryOrList, [key], defaultValue)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/base/exchange.py", line 1877, in safe_list_n
    value = self.safe_value_n(dictionaryOrList, keys, defaultValue)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/base/exchange.py", line 905, in safe_value_n
    value = Exchange.get_object_value_from_key_list(dictionary, key_list)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/base/exchange.py", line 912, in get_object_value_from_key_list
    if key in dictionary_or_list and dictionary_or_list[key] is not None and dictionary_or_list[key] != '':
                                     ~~~~~~~~~~~~~~~~~~^^^^^
TypeError: string indices must be integers, not 'str'

**Comment by xmatthias** [comment]
from afar, it seems to be a problem with the response  from the exchange during startup - which might suggest a problem with the network connection (i can start a bot on kucoin just fine, both on 2024.5, as well as on develop).

Your best bet might be to run with `-vvv` - which will output the actual responses from the exchange.
Now if it doesn't fail immediately (same timeframe, roughly) - best stop the bot and restart it without -vvv - as that's a VERY verbose mode ... one you'll definitely not want to be running constantly

**Comment by l3104468710** [comment]
> from afar, it seems to be a problem with the response from the exchange during startup - which might suggest a problem with the network connection (i can start a bot on kucoin just fine, both on 2024.5, as well as on develop).
> 
> Your best bet might be to run with `-vvv` - which will output the actual responses from the exchange. Now if it doesn't fail immediately (same timeframe, roughly) - best stop the bot and restart it without -vvv - as that's a VERY verbose mode ... one you'll definitely not want to be running constantly

I didn't search for information about the -vvv mode, can you give me a link to the information, or the relevant commands for mode activation? Thank you!

**Comment by stash86** [comment]
Just add -vvv at the end of your command

**Comment by l3104468710** [comment]
> Just add -vvv at the end of your command

I tried to run it this way, but it seems to be having some problems

root@ser446709423380:~/freqtrade/ft_userdata# docker compose run --rm freqtrade -vvv
WARN[0000] /root/freqtrade/ft_userdata/docker-compose.yml: `version` is obsolete 
usage: freqtrade [-h] [-V]
                 {trade,create-userdir,new-config,show-config,new-strategy,download-data,convert-data,convert-trade-data,trades-to-ohlcv,list-data,backtesting,backtesting-show,backtesting-analysis,edge,hyperopt,hyperopt-list,hyperopt-show,list-exchanges,list-markets,list-pairs,list-strategies,list-freqaimodels,list-timeframes,show-trades,test-pairlist,convert-db,install-ui,plot-dataframe,plot-profit,webserver,strategy-updater,lookahead-analysis,recursive-analysis}
                 ...
freqtrade: error: unrecognized arguments: -vvv

**Comment by stash86** [comment]
Well, -vvv is additional argument. You need to define first what you want to do. Trade? Download data? Backtest? -vvv is put last on the command

**Comment by stash86** [comment]
Reading your first post, if you are using docker, there is no need to use virtual environment

**Comment by xmatthias** [comment]
i assume, you'll be starting your bot with `docker compose up` . If that's the case, you'll need to edit the compose file adding the `-vvv` there (think about it the same way than every other parameter like `-s YourCoolStratgy` - just that now it'll have to look like `-s YourCoolStrategy -vvv` (now obviously that's an example - no clue how your strategy is called).

**Comment by l3104468710** [comment]
It is indeed due to network reasons. I will try it on another vps. Thank you
