### ISSUE TITLE
FreqAI - VarianceThreshold will remove 10 features from the dataset.on transform.

### ISSUE THREAD

**Issue by MrGalacticClouds** [freqtrade/freqtrade#10356]
## Describe your environment

  * Operating system:Linux Mint 21.3
  * Python Version: 3.10.12
  * CCXT version: 4.2.79
  * Freqtrade Version: 2024.5
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

Hi,
How can I prevent it from happening?
```
2024-06-22 03:47:15,999 - datasieve.pipeline - INFO - VarianceThreshold will remove 10 features from the dataset.on transform. ['%-ema25_300_10_BTC/USDTUSDT_15m'
 '%-ema25_300_10_shift-1_BTC/USDTUSDT_15m'
 '%-ema25_300_10_shift-2_BTC/USDTUSDT_15m'
 '%-ema100_grow_10_shift-2_BTC/USDTUSDT_1h'
 '%-ema25_300_10_BTC/USDTUSDT_4h' '%-raw_volume_10_BTC/USDTUSDT_4h'
 '%-ema25_300_10_shift-1_BTC/USDTUSDT_4h'
 '%-raw_volume_10_shift-1_BTC/USDTUSDT_4h'
 '%-ema25_300_10_shift-2_BTC/USDTUSDT_4h'
 '%-raw_volume_10_shift-2_BTC/USDTUSDT_4h']

```

```
2024-06-22 03:49:47,157 - freqtrade.freqai.freqai_interface - WARNING - Training BTC/USDT:USDT raised exception CatBoostError. Message: /src/catboost/catboost/libs/model/model.cpp:1547: Feature name mismatch: %-ema25_300_10_BTC/USDTUSDT_1h != %-fastkl_rsi_10_BTC/USDTUSDT_1h flat feature index: 160, skipping.
Traceback (most recent call last):
  File "/home/mrgalacticclouds/Dokumenty/freqtrade-stable/freqtrade/freqai/freqai_interface.py", line 360, in start_backtesting
    self.model = self.train(dataframe_train, pair, dk)
  File "/home/mrgalacticclouds/Dokumenty/freqtrade-stable/freqtrade/freqai/base_models/BaseRegressionModel.py", line 78, in train
    model = self.fit(dd, dk)
  File "/home/mrgalacticclouds/Dokumenty/freqtrade-stable/freqtrade/freqai/prediction_models/CatboostRegressorMultiTarget.py", line 76, in fit
    model.fit(X=X, y=y, sample_weight=sample_weight, fit_params=fit_params)
  File "/home/mrgalacticclouds/Dokumenty/freqtrade-stable/freqtrade/freqai/base_models/FreqaiMultiOutputRegressor.py", line 48, in fit
    self.estimators_ = Parallel(n_jobs=self.n_jobs)(
  File "/home/mrgalacticclouds/Dokumenty/freqtrade-stable/.venv/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 67, in __call__
    return super().__call__(iterable_with_config)
  File "/home/mrgalacticclouds/Dokumenty/freqtrade-stable/.venv/lib/python3.10/site-packages/joblib/parallel.py", line 1918, in __call__
    return output if self.return_generator else list(output)
  File "/home/mrgalacticclouds/Dokumenty/freqtrade-stable/.venv/lib/python3.10/site-packages/joblib/parallel.py", line 1847, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/home/mrgalacticclouds/Dokumenty/freqtrade-stable/.venv/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 129, in __call__
    return self.function(*args, **kwargs)
  File "/home/mrgalacticclouds/Dokumenty/freqtrade-stable/.venv/lib/python3.10/site-packages/sklearn/multioutput.py", line 66, in _fit_estimator
    estimator.fit(X, y, sample_weight=sample_weight, **fit_params)
  File "/home/mrgalacticclouds/Dokumenty/freqtrade-stable/.venv/lib/python3.10/site-packages/catboost/core.py", line 5827, in fit
    return self._fit(X, y, cat_features, text_features, embedding_features, None, sample_weight, None, None, None, None, baseline,
  File "/home/mrgalacticclouds/Dokumenty/freqtrade-stable/.venv/lib/python3.10/site-packages/catboost/core.py", line 2400, in _fit
    self._train(
  File "/home/mrgalacticclouds/Dokumenty/freqtrade-stable/.venv/lib/python3.10/site-packages/catboost/core.py", line 1780, in _train
    self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
  File "_catboost.pyx", line 4833, in _catboost._CatBoost._train
  File "_catboost.pyx", line 4882, in _catboost._CatBoost._train
_catboost.CatBoostError: /src/catboost/catboost/libs/model/model.cpp:1547: Feature name mismatch: %-ema25_300_10_BTC/USDTUSDT_1h != %-fastkl_rsi_10_BTC/USDTUSDT_1h flat feature index: 160
2024-06-22 03:49:47,172 - freqtrade.freqai.freqai_interface - INFO - Saving metadata to disk.
2024-06-22 03:49:48,075 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/mrgalacticclouds/Dokumenty/freqtrade-stable/freqtrade/main.py", line 43, in main
    return_code = args["func"](args)
  File "/home/mrgalacticclouds/Dokumenty/freqtrade-stable/freqtrade/commands/optimize_commands.py", line 60, in start_backtesting
    backtesting.start()
  File "/home/mrgalacticclouds/Dokumenty/freqtrade-stable/freqtrade/optimize/backtesting.py", line 1616, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
  File "/home/mrgalacticclouds/Dokumenty/freqtrade-stable/freqtrade/optimize/backtesting.py", line 1526, in backtest_one_strategy
    preprocessed = self.strategy.advise_all_indicators(data)
  File "/home/mrgalacticclouds/Dokumenty/freqtrade-stable/freqtrade/strategy/interface.py", line 1575, in advise_all_indicators
    return {
  File "/home/mrgalacticclouds/Dokumenty/freqtrade-stable/freqtrade/strategy/interface.py", line 1576, in <dictcomp>
    pair: self.advise_indicators(pair_data.copy(), {"pair": pair}).copy()
  File "/home/mrgalacticclouds/Dokumenty/freqtrade-stable/freqtrade/strategy/interface.py", line 1610, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/home/mrgalacticclouds/Dokumenty/freqtrade-stable/user_data/strategies/Ka_Ching_Multiplikator_AI.py", line 261, in populate_indicators
    dataframe = self.freqai.start(dataframe, metadata, self)
  File "/home/mrgalacticclouds/Dokumenty/freqtrade-stable/freqtrade/freqai/freqai_interface.py", line 161, in start
    dk = self.start_backtesting(dataframe, metadata, self.dk, strategy)
  File "/home/mrgalacticclouds/Dokumenty/freqtrade-stable/freqtrade/freqai/freqai_interface.py", line 382, in start_backtesting
    pred_df, do_preds = self.predict(dataframe_backtest, dk)
  File "/home/mrgalacticclouds/Dokumenty/freqtrade-stable/freqtrade/freqai/base_models/BaseRegressionModel.py", line 110, in predict
    predictions = self.model.predict(dk.data_dictionary["prediction_features"])
AttributeError: 'NoneType' object has no attribute 'predict'

```

``` python
import logging
from functools import reduce
from typing import Dict
import numpy as np
import pandas as pd

from datetime import datetime, timedelta
from typing import Optional, Union
import talib.abstract as ta
from pandas import DataFrame
from technical import qtpylib

from freqtrade.strategy import IStrategy
import talib.abstract as ta
import freqtrade.vendor.qtpylib.indicators as qtpylib

logger = logging.getLogger(__name__)


class KaChingMultiplikator(IStrategy):
    def leverage(self, pair: str, current_time: datetime, current_rate: float,proposed_leverage: float, max_leverage: float, entry_tag: Optional[str], side: str,**kwargs) -> float:
        return 15.00
    """
    Example strategy showing how the user connects their own
    IFreqaiModel to the strategy.

    Warning! This is a showcase of functionality,
    which means that it is designed to show various functions of FreqAI
    and it runs on all computers. We use this showcase to help users
    understand how to build a strategy, and we use it as a benchmark
    to help debug possible problems.

    This means this is *not* meant to be run live in production.
    """

    minimal_roi = {"0": 0.60, "2480": -1}

    plot_config = {
        "main_plot": {},
        "subplots": {
            "&-s_close": {"&-s_close": {"color": "blue"}},
            "do_predict": {
                "do_predict": {"color": "brown"},
            },
        },
    }

    process_only_new_candles = True
    stoploss = -0.3
    use_exit_signal = True
    # this is the maximum period fed to talib (timeframe independent)
    startup_candle_count: int = 300
    can_short = True

    def feature_engineering_expand_all(
        self, dataframe: DataFrame, period: int, metadata: Dict, **kwargs
    ) -> DataFrame:
        """
        *Only functional with FreqAI enabled strategies*
        This function will automatically expand the defined features on the config defined
        `indicator_periods_candles`, `include_timeframes`, `include_shifted_candles`, and
        `include_corr_pairs`. In other words, a single feature defined in this function
        will automatically expand to a total of
        `indicator_periods_candles` * `include_timeframes` * `include_shifted_candles` *
        `include_corr_pairs` numbers of features added to the model.

        All features must be prepended with `%` to be recognized by FreqAI internals.

        Access metadata such as the current pair/timeframe with:

        `metadata["pair"]` `metadata["tf"]`

        More details on how these config defined parameters accelerate feature engineering
        in the documentation at:

        https://www.freqtrade.io/en/latest/freqai-parameter-table/#feature-parameters

        https://www.freqtrade.io/en/latest/freqai-feature-engineering/#defining-the-features

        :param dataframe: strategy dataframe which will receive the features
        :param period: period of the indicator - usage example:
        :param metadata: metadata of current pair
        dataframe["%-ema-period"] = ta.EMA(dataframe, timeperiod=period)
        """
        stoch_rsi = ta.STOCHRSI(dataframe)
        dataframe['%-fastd_rsi'] = stoch_rsi['fastd']
        dataframe['%-fastk_rsi'] = stoch_rsi['fastk']
        dataframe['%-fastk_d_rsi_'] = np.where(stoch_rsi['fastk']>stoch_rsi['fastd'],0,1)
        dataframe["%-rsi-period"] = ta.RSI(dataframe)
        #dataframe["%-mfi-period"] = ta.MFI(dataframe, timeperiod=period)
        #dataframe["%-adx-period"] = ta.ADX(dataframe, timeperiod=period)
        #dataframe["%-sma-period"] = ta.SMA(dataframe, timeperiod=period)
        
        dataframe['ema25'] = ta.EMA(dataframe, timeperiod=25)
        dataframe['ema100'] = ta.EMA(dataframe, timeperiod=100)
        dataframe['ema300'] = ta.EMA(dataframe, timeperiod=300)
        dataframe['%-ema25_100'] = dataframe['ema25']/dataframe['ema100']
        dataframe['%-ema100_300'] = dataframe['ema100']/dataframe['ema300']
        bollinger = qtpylib.bollinger_bands(
            qtpylib.typical_price(dataframe), window=21, stds=2.2
        )
        dataframe['%-sar'] = ta.SAR(dataframe, start=0.015,maxsimum=0.25)/dataframe['close']
        dataframe["%-bb_lowerband"] = bollinger["lower"]/dataframe['close']
        dataframe["%-bb_middleband"] = bollinger["mid"]/dataframe['close']
        dataframe["%-bb_upperband"] = bollinger["upper"]/dataframe['close']
        dataframe['%-ema25_300']=np.where(dataframe['ema25'] > dataframe['ema300'],0,1)
        dataframe['%-ema100_grow']= np.where(dataframe['ema100'] > dataframe['ema100'].shift(1),0,1)
        dataframe['%-fastkl_rsi']=np.where(dataframe['%-fastk_rsi']<40,0,1)
        dataframe['%-fastks_rsi']=np.where(dataframe['%-fastk_rsi']>60,0,1)
        dataframe['%-fastk_rsi_grow'] = np.where(dataframe['%-fastk_rsi']>dataframe['%-fastk_rsi'].shift(1),0,1)
        dataframe["%-pct-change"] = (dataframe["close"].rolling(50).max()-dataframe["close"].rolling(50).min())/dataframe['close']
        dataframe["%-raw_volume"] = np.where(dataframe["volume"].rolling(3).mean()>dataframe["volume"].rolling(100).mean(),0,1)
        #dataframe["%-bb_width-period"] = (
        #    dataframe["bb_upperband-period"] - dataframe["bb_lowerband-period"]
        #) / dataframe["bb_middleband-period"]
        #dataframe["%-close-bb_lower-period"] = dataframe["close"] / dataframe["bb_lowerband-period"]

        #dataframe["%-roc-period"] = ta.ROC(dataframe, timeperiod=period)

        #dataframe["%-relative_volume-period"] = (
        #    dataframe["volume"] / dataframe["volume"].rolling(period).mean()
        #)

        return dataframe

    def feature_engineering_expand_basic(
        self, dataframe: DataFrame, metadata: Dict, **kwargs
    ) -> DataFrame:
        """
        *Only functional with FreqAI enabled strategies*
        This function will automatically expand the defined features on the config defined
        `include_timeframes`, `include_shifted_candles`, and `include_corr_pairs`.
        In other words, a single feature defined in this function
        will automatically expand to a total of
        `include_timeframes` * `include_shifted_candles` * `include_corr_pairs`
        numbers of features added to the model.

        Features defined here will *not* be automatically duplicated on user defined
        `indicator_periods_candles`

        All features must be prepended with `%` to be recognized by FreqAI internals.

        Access metadata such as the current pair/timeframe with:

        `metadata["pair"]` `metadata["tf"]`

        More details on how these config defined parameters accelerate feature engineering
        in the documentation at:

        https://www.freqtrade.io/en/latest/freqai-parameter-table/#feature-parameters

        https://www.freqtrade.io/en/latest/freqai-feature-engineering/#defining-the-features

        :param dataframe: strategy dataframe which will receive the features
        :param metadata: metadata of current pair
        dataframe["%-pct-change"] = dataframe["close"].pct_change()
        dataframe["%-ema-200"] = ta.EMA(dataframe, timeperiod=200)
        """
        
        #    dataframe["bb_upperband-period"] - dataframe["bb_lowerband-period"]
        #) / dataframe["bb_middleband-period"]
        #dataframe["%-close-bb_lower-period"] = dataframe["close"] / dataframe["bb_lowerband-period"]

        #dataframe["%-roc-period"] = ta.ROC(dataframe, timeperiod=period)

        #dataframe["%-relative_volume-period"] = (
        #    dataframe["volume"] / dataframe["volume"].rolling(period).mean()
        #)
        
        return dataframe

    def feature_engineering_standard(
        self, dataframe: DataFrame, metadata: Dict, **kwargs
    ) -> DataFrame:
        """
        *Only functional with FreqAI enabled strategies*
        This optional function will be called once with the dataframe of the base timeframe.
        This is the final function to be called, which means that the dataframe entering this
        function will contain all the features and columns created by all other
        freqai_feature_engineering_* functions.

        This function is a good place to do custom exotic feature extractions (e.g. tsfresh).
        This function is a good place for any feature that should not be auto-expanded upon
        (e.g. day of the week).

        All features must be prepended with `%` to be recognized by FreqAI internals.

        Access metadata such as the current pair with:

        `metadata["pair"]`

        More details about feature engineering available:

        https://www.freqtrade.io/en/latest/freqai-feature-engineering

        :param dataframe: strategy dataframe which will receive the features
        :param metadata: metadata of current pair
        usage example: dataframe["%-day_of_week"] = (dataframe["date"].dt.dayofweek + 1) / 7
        """
        #dataframe["%-day_of_week"] = dataframe["date"].dt.dayofweek
        #dataframe["%-hour_of_day"] = dataframe["date"].dt.hour
        return dataframe

    def set_freqai_targets(self, dataframe: DataFrame, metadata: Dict, **kwargs) -> DataFrame:
        """
        *Only functional with FreqAI enabled strategies*
        Required function to set the targets for the model.
        All targets must be prepended with `&` to be recognized by the FreqAI internals.

        Access metadata such as the current pair with:

        `metadata["pair"]`

        More details about feature engineering available:

        https://www.freqtrade.io/en/latest/freqai-feature-engineering

        :param dataframe: strategy dataframe which will receive the targets
        :param metadata: metadata of current pair
        usage example: dataframe["&-target"] = dataframe["close"].shift(-1) / dataframe["close"]
        """
        dataframe["&-s_close"] = (
            dataframe["close"].shift(-10).rolling(10).mean()/ dataframe["close"]- 1
        )
        dataframe['&-s-up_or_down'] = np.where( dataframe["close"].shift(-10) > dataframe["close"], 0, 1)
        
        dataframe['&-s-ema100_grow'] = np.where( ta.EMA(dataframe.shift(-10), timeperiod=100)<ta.EMA(dataframe.shift(-11), timeperiod=100), 0, 1)

        # Classifiers are typically set up with strings as targets:
        # df['&s-up_or_down'] = np.where( df["close"].shift(-100) >
        #                                 df["close"], 'up', 'down')

        # If user wishes to use multiple targets, they can add more by
        # appending more columns with '&'. User should keep in mind that multi targets
        # requires a multioutput prediction model such as
        # freqai/prediction_models/CatboostRegressorMultiTarget.py,
        # freqtrade trade --freqaimodel CatboostRegressorMultiTarget

        # df["&-s_range"] = (
        #     df["close"]
        #     .shift(-self.freqai_info["feature_parameters"]["label_period_candles"])
        #     .rolling(self.freqai_info["feature_parameters"]["label_period_candles"])
        #     .max()
        #     -
        #     df["close"]
        #     .shift(-self.freqai_info["feature_parameters"]["label_period_candles"])
        #     .rolling(self.freqai_info["feature_parameters"]["label_period_candles"])
        #     .min()
        # )

        return dataframe

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        # All indicators must be populated by feature_engineering_*() functions

        # the model will return all labels created by user in `set_freqai_targets()`
        # (& appended targets), an indication of whether or not the prediction should be accepted,
        # the target mean/std values for each of the labels created by user in
        # `set_freqai_targets()` for each training period.

        dataframe = self.freqai.start(dataframe, metadata, self)

        return dataframe

    def populate_entry_trend(self, df: DataFrame, metadata: dict) -> DataFrame:
        enter_long_conditions = [
            df["do_predict"] == 1,
            df["&-s_close"] > 0.01,
            df['&-s-up_or_down']== 0,
            df['&-s-ema100_grow'] == 0,
        ]

        if enter_long_conditions:
            df.loc[
                reduce(lambda x, y: x & y, enter_long_conditions), ["enter_long", "enter_tag"]
            ] = (1, "long")

        enter_short_conditions = [
            df["do_predict"] == 1,
            df["&-s_close"] < -0.01,
            df['&-s-up_or_down']==1,
            df['&-s-ema100_grow'] == 1,
        ]

        if enter_short_conditions:
            df.loc[
                reduce(lambda x, y: x & y, enter_short_conditions), ["enter_short", "enter_tag"]
            ] = (1, "short")

        return df

    def populate_exit_trend(self, df: DataFrame, metadata: dict) -> DataFrame:
        exit_long_conditions = [df["do_predict"] == 1, df["&-s_close"] < 0]
        if exit_long_conditions:
            df.loc[reduce(lambda x, y: x & y, exit_long_conditions), "exit_long"] = 1

        exit_short_conditions = [df["do_predict"] == 1, df["&-s_close"] > 0]
        if exit_short_conditions:
            df.loc[reduce(lambda x, y: x & y, exit_short_conditions), "exit_short"] = 1

        return df

    def confirm_trade_entry(
        self,
        pair: str,
        order_type: str,
        amount: float,
        rate: float,
        time_in_force: str,
        current_time,
        entry_tag,
        side: str,
        **kwargs,
    ) -> bool:
        df, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)
        last_candle = df.iloc[-1].squeeze()

        if side == "long":
            if rate > (last_candle["close"] * (1 + 0.0025)):
                return False
        else:
            if rate < (last_candle["close"] * (1 - 0.0025)):
                return False

        return True

```

``` jsonc
{
    "trading_mode": "futures",
    "margin_mode": "isolated",
    "max_open_trades": 133,
    "stake_currency": "USDT",
    "stake_amount": "unlimited",
    "tradable_balance_ratio": 1,
    "fiat_display_currency": "USD",
    "dry_run": true,
    "timeframe": "1m",
    "dry_run_wallet": 100,
    "cancel_open_orders_on_exit": true,
    "unfilledtimeout": {
        "entry": 5,
        "exit": 5,
        "unit": "minutes"
    },
    "exchange": {
        "name": "binance",
        "key": "",
        "secret": "",
        "ccxt_config": {},
        "ccxt_async_config": {},
        "pair_whitelist": [
           "BTC/USDT:USDT", "ETH/USDT:USDT", "SOL/USDT:USDT", "TRB/USDT:USDT", "1000PEPE/USDT:USDT", "UMA/USDT:USDT", "DOGE/USDT:USDT", "FRONT/USDT:USDT", "WLD/USDT:USDT", "WIF/USDT:USDT", "PORTAL/USDT:USDT", "JTO/USDT:USDT", "TNSR/USDT:USDT", "BNB/USDT:USDT", "TON/USDT:USDT", "BOME/USDT:USDT", "NEAR/USDT:USDT", "ORDI/USDT:USDT", "XRP/USDT:USDT", "ENA/USDT:USDT", "RNDR/USDT:USDT", "FTM/USDT:USDT", "RUNE/USDT:USDT", "ARPA/USDT:USDT", "AR/USDT:USDT", "LPT/USDT:USDT", "AVAX/USDT:USDT", "1000SHIB/USDT:USDT", "HIGH/USDT:USDT", "1000RATS/USDT:USDT", "GMX/USDT:USDT", "PEOPLE/USDT:USDT", "FIL/USDT:USDT", "ADA/USDT:USDT", "AEVO/USDT:USDT", "ETHFI/USDT:USDT", "LINK/USDT:USDT", "SUI/USDT:USDT", "ETC/USDT:USDT", "XVG/USDT:USDT", "BCH/USDT:USDT", "FET/USDT:USDT", "LTC/USDT:USDT", "MATIC/USDT:USDT", "1000BONK/USDT:USDT", "MOVR/USDT:USDT", "INJ/USDT:USDT", "ARB/USDT:USDT", "POLYX/USDT:USDT", "DOT/USDT:USDT", "OP/USDT:USDT", "ONDO/USDT:USDT", "MYRO/USDT:USDT", "W/USDT:USDT", "ARKM/USDT:USDT", "GRT/USDT:USDT", "HBAR/USDT:USDT", "GALA/USDT:USDT", "LEVER/USDT:USDT", "GLM/USDT:USDT", "1000SATS/USDT:USDT", "SAGA/USDT:USDT", "ATOM/USDT:USDT", "TIA/USDT:USDT", "SSV/USDT:USDT", "ZETA/USDT:USDT", "JUP/USDT:USDT", "REZ/USDT:USDT", "PYTH/USDT:USDT", "STX/USDT:USDT", "IMX/USDT:USDT", "APT/USDT:USDT", "1000FLOKI/USDT:USDT", "USTC/USDT:USDT", "UNI/USDT:USDT", "CKB/USDT:USDT", "ICP/USDT:USDT", "ARK/USDT:USDT", "NEO/USDT:USDT", "PHB/USDT:USDT", "SEI/USDT:USDT", "EOS/USDT:USDT", "GMT/USDT:USDT", "THETA/USDT:USDT", "TRX/USDT:USDT", "AI/USDT:USDT", "NFP/USDT:USDT", "AUCTION/USDT:USDT", "SUSHI/USDT:USDT", "PIXEL/USDT:USDT", "1000LUNC/USDT:USDT", "AGIX/USDT:USDT", "SAND/USDT:USDT", "BEL/USDT:USDT", "PENDLE/USDT:USDT", "LDO/USDT:USDT", "CHZ/USDT:USDT", "APE/USDT:USDT", "DYDX/USDT:USDT", "OMNI/USDT:USDT", "CFX/USDT:USDT", "MEME/USDT:USDT", "LSK/USDT:USDT", "NMR/USDT:USDT", "GAL/USDT:USDT", "YGG/USDT:USDT", "TAO/USDT:USDT", "BLZ/USDT:USDT", "OM/USDT:USDT", "API3/USDT:USDT", "RLC/USDT:USDT", "CRV/USDT:USDT", "AXS/USDT:USDT", "STRK/USDT:USDT", "CELO/USDT:USDT", "MKR/USDT:USDT", "ATA/USDT:USDT", "ALT/USDT:USDT", "MINA/USDT:USDT", "OCEAN/USDT:USDT", "COMP/USDT:USDT", "POWR/USDT:USDT", "AAVE/USDT:USDT", "MANTA/USDT:USDT", "MANA/USDT:USDT", "JASMY/USDT:USDT", "BAKE/USDT:USDT", "BIGTIME/USDT:USDT", "ALGO/USDT:USDT", "LOOM/USDT:USDT", "SUPER/USDT:USDT", "MASK/USDT:USDT", "BLUR/USDT:USDT", "LUNA2/USDT:USDT", "ACE/USDT:USDT", "HIFI/USDT:USDT", "ONT/USDT:USDT", "KAS/USDT:USDT", "SFP/USDT:USDT", "XLM/USDT:USDT", "BNX/USDT:USDT", "C98/USDT:USDT", "VET/USDT:USDT", "XMR/USDT:USDT", "ONG/USDT:USDT", "TRU/USDT:USDT", "EGLD/USDT:USDT", "ENS/USDT:USDT", "WAVES/USDT:USDT", "XAI/USDT:USDT"
        ],
        "pair_blacklist": [
           "PORTAL/USDT:USDT", "TNSR/USDT:USDT", "TON/USDT:USDT", "BOME/USDT:USDT", "ENA/USDT:USDT", "AEVO/USDT:USDT", "ETHFI/USDT:USDT", "MYRO/USDT:USDT", "W/USDT:USDT", "GLM/USDT:USDT", "SAGA/USDT:USDT", "REZ/USDT:USDT", "PIXEL/USDT:USDT", "OMNI/USDT:USDT", "TAO/USDT:USDT", "OM/USDT:USDT", "STRK/USDT:USDT"
        ]
    },
    "entry_pricing": {
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1,
        "price_last_balance": 0.0,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "exit_pricing": {
        "price_side": "other",
        "use_order_book": true,
        "order_book_top": 1
    },
    "pairlists": [
        {
            "method": "StaticPairList"
        }
    ],
    "freqai": {
        "enabled": true,
        "purge_old_models": 4,
        "train_period_days": 3,
        "train_ranges": 10,
        "backtest_period_days": 3,
        "live_retrain_hours": 0,
        "identifier": "unique-id",
        "continual_learning": true,
        "feature_parameters": {
            "include_timeframes": [
                "1m",
                "5m",
                "15m",
                "1h",
                "4h",
            ],
            "include_corr_pairlist": [
            ],
            "label_period_candles": 20,
            "include_shifted_candles": 2,
            "DI_threshold": 0.9,
            "weight_factor": 0.9,
            "principal_component_analysis": false,
            "use_SVM_to_remove_outliers": false,
            "indicator_periods_candles": [
                10
                
            ],
            "plot_feature_importances": 0
        },
        "data_split_parameters": {
            "test_size": 0.5,
            "random_state": 1
        },
        "randomize_starting_position": false,
        "rl_config": {
            "train_cycles": 25,
            "add_state_info": false,
            "max_trade_duration_candles": 60,
            "max_training_drawdown_pct": 0.2,
            "model_type": "PPO",
            "policy_type": "MlpPolicy",
            "drop_ohlc_from_features": false,
            "model_reward_parameters": {
                "win_reward_factor": 3,
                "rr": 1,
                "profit_aim": 0.1
            },
            "progress_bar": true,
            "cpu_count": 7
        },
        
        "model_training_parameters": {
            "n_estimators":200,
        }
    },
    
    "order_types": {
        "entry": "limit",
        "exit": "limit",
        "emergency_exit": "market",
        "force_exit": "market",
        "force_entry": "market",
        "stoploss": "market",
        "stoploss_on_exchange": false,
        "stoploss_price_type": "last",
        "stoploss_on_exchange_interval": 60,
        "stoploss_on_exchange_limit_ratio": 0.99
    },
    "bot_name": "",
    "force_entry_enable": true,
    "initial_state": "running",
    "internals": {
        "process_throttle_secs": 5
    }
}

```

**Comment by xmatthias** [comment]
from a (very basic / high level) look - it seems like the features being removed are not really variable - but rather represent a static value instead.


```
        dataframe['%-ema25_300']=np.where(dataframe['ema25'] > dataframe['ema300'],0,1)
        dataframe['%-ema100_grow']= np.where(dataframe['ema100'] > dataframe['ema100'].shift(1),0,1)
```

especially the first can be quite static in a strong uptrend - so your value is always 0 (or 1).
That makes it a static column (all rows have the same value) - which is removed by the VarianceThreshold (it's a useless feature for training if it never changes).

The same will most likely apply to the other columns - too.

**Comment by robcaulk** [comment]
> How can I prevent it from happening?

If for some reason you *want* static columns (which are useless as Matthias said, which is why FreqAI is doing you this favor), then remove it from your pipeline:

https://www.freqtrade.io/en/stable/freqai-feature-engineering/#customizing-the-pipeline
