### ISSUE TITLE
hyperoptimize on trailing_stoploss space

### ISSUE THREAD

**Issue by algotrader-dotcom** [freqtrade/freqtrade#10354]
I got an issue during hyperoptimzing trailing_stoploss values. Here is the error message. Thanks for looking into it.
```
2024-06-21 22:56:50,450 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_open_trades: 10
2024-06-21 22:56:50,450 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/Users/leo/freqtrade/freqtrade/main.py", line 42, in main
    return_code = args['func'](args)
                  ^^^^^^^^^^^^^^^^^^
  File "/Users/leo/freqtrade/freqtrade/commands/optimize_commands.py", line 106, in start_hyperopt
    hyperopt = Hyperopt(config)
               ^^^^^^^^^^^^^^^^
  File "/Users/leo/freqtrade/freqtrade/optimize/hyperopt.py", line 82, in __init__
    self.backtesting = Backtesting(self.config)
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/leo/freqtrade/freqtrade/optimize/backtesting.py", line 114, in __init__
    validate_config_consistency(self.config)
  File "/Users/leo/freqtrade/freqtrade/configuration/config_validation.py", line 80, in validate_config_consistency
    _validate_trailing_stoploss(conf)
  File "/Users/leo/freqtrade/freqtrade/configuration/config_validation.py", line 134, in _validate_trailing_stoploss
    tsl_positive = float(conf.get('trailing_stop_positive', 0))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'DecimalParameter'
```
The command used: freqtrade hyperopt --strategy BollingerBandDCARSI --hyperopt TrailingStopHyperOpt --spaces sell
```

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

You'll also want to show some of the actual code you're using. 
From the error, it seems possible that you're simply assigned DecimalParameter to a builtin variable ... but that's not how you optimize this value.

I'll simply refer you to the corresponding [docs](https://www.freqtrade.io/en/stable/hyperopt/#default-stoploss-search-space) -with the hint that "stoploss" is it's own space - not something you'll configure manually under normal circumstances.

**Comment by algotrader-dotcom** [comment]
thx @xmatthias for your hint with link to docs, i think i have in mind how to resolve this.
