### ISSUE TITLE
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'

### ISSUE THREAD

**Issue by grainz** [freqtrade/freqtrade#10398]
## Describe your environment

  * Operating system: Debian 12
  * Python Version: Python 3.11.2
  * CCXT version: ccxt==4.3.54
  * Freqtrade Version: freqtrade 2024.7-dev-c4bc5356d
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

Bot will crash when a trade is opened. Not consistent.
I have to update the trade record to fill in the column 'fee_open_currency' to get past the error.

### Steps to reproduce:

  1. Open a trade
  
### Observed Results:

  * Bot crashed
  * Bot not to crash

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
2024-07-03 01:30:15,849 - freqtrade.freqtradebot - INFO - Long signal found: about create a new trade for ETH/USD with stake_amount: 13.0133025 ...
2024-07-03 01:30:16,038 - freqtrade.freqtradebot - INFO - Order xxxx was created for ETH/USD and status is open.
2024-07-03 01:30:22,172 - freqtrade.wallets - INFO - Wallets synced.
2024-07-03 01:30:22,184 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'trade_id': 11, 'type': entry, 'buy_tag': 'watchtrades_stoch_15m', 'enter_tag': 'watchtrades_stoch_15m', 'exchange': 'Kraken', 'pair': 'ETH/USD', 'leverage': 1.0, 'direction': 'Long', 'limit': 3350.36, 'open_rate': 3350.36, 'order_type': 'market', 'stake_amount': 13.0133, 'stake_currency': 'USD', 'base_currency': 'ETH', 'quote_currency': 'USD', 'fiat_currency': 'USD', 'amount': 0.00388415, 'open_date': datetime.datetime(2024, 7, 3, 8, 30, 16, tzinfo=datetime.timezone.utc), 'current_rate': 3350.36, 'sub_trade': False}
2024-07-03 01:30:41,168 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=11, pair=ETH/USD, amount=0.00388415, is_short=False, leverage=1.0, open_rate=3350.36000000, open_since=2024-07-03 08:30:16)
2024-07-03 01:30:41,177 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2024-07-03 01:30:41,177 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2024-07-03 01:30:41,177 - freqtrade.rpc.discord - INFO - Sending discord message: {'type': status, 'status': 'process died'}
2024-07-03 01:30:41,508 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2024-07-03 01:30:41,518 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': warning, 'status': "1 open trades active.\n\nHandle these trades manually on Kraken, or '/start' the bot again and use '/stopentry' to handle open trades gracefully. \n"}
2024-07-03 01:30:41,519 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
2024-07-03 01:30:41,519 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.apiserver ...
2024-07-03 01:30:41,519 - freqtrade.rpc.api_server.webserver - INFO - Stopping API Server
2024-07-03 01:30:41,563 - uvicorn.error - INFO - Shutting down
2024-07-03 01:30:41,664 - uvicorn.error - INFO - Waiting for application shutdown.
2024-07-03 01:30:41,664 - uvicorn.error - INFO - Application shutdown complete.
2024-07-03 01:30:41,664 - uvicorn.error - INFO - Finished server process [2340]
2024-07-03 01:30:41,664 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.discord ...
2024-07-03 01:30:41,666 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.telegram ...
2024-07-03 01:30:42,180 - telegram.ext.Application - INFO - Application is stopping. This might take a moment.
2024-07-03 01:30:42,180 - telegram.ext.Application - INFO - Application.stop() complete
2024-07-03 01:30:48,716 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/grainz/build/ft_kraken/freqtrade/main.py", line 43, in main
    return_code = args["func"](args)
                  ^^^^^^^^^^^^^^^^^^
  File "/home/grainz/build/ft_kraken/freqtrade/commands/trade_commands.py", line 25, in start_trading
    worker.run()
  File "/home/grainz/build/ft_kraken/freqtrade/worker.py", line 78, in run
    state = self._worker(old_state=state)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grainz/build/ft_kraken/freqtrade/worker.py", line 119, in _worker
    self._throttle(
  File "/home/grainz/build/ft_kraken/freqtrade/worker.py", line 160, in _throttle
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/grainz/build/ft_kraken/freqtrade/worker.py", line 194, in _process_running
    self.freqtrade.process()
  File "/home/grainz/build/ft_kraken/freqtrade/freqtradebot.py", line 274, in process
    self.manage_open_orders()
  File "/home/grainz/build/ft_kraken/freqtrade/freqtradebot.py", line 1539, in manage_open_orders
    fully_cancelled = self.update_trade_state(trade, open_order.order_id, order)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grainz/build/ft_kraken/freqtrade/freqtradebot.py", line 2187, in update_trade_state
    self.handle_order_fee(trade, order_obj, order)
  File "/home/grainz/build/ft_kraken/freqtrade/freqtradebot.py", line 2319, in handle_order_fee
    fee_abs = self.get_real_amount(trade, order, order_obj)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grainz/build/ft_kraken/freqtrade/freqtradebot.py", line 2368, in get_real_amount
    return self.fee_detection_from_trades(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grainz/build/ft_kraken/freqtrade/freqtradebot.py", line 2394, in fee_detection_from_trades
    amount += exectrade["amount"]
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'
  ```

**Comment by xmatthias** [comment]
Seems to be a problem with the response kraken gives - which seems to be missing one field.

Please enable `"log_responses" : true` in the `exchange` section of your configuration and provide us with the logs that generates.

From your description, this seems / should be easily archivable by simply removing  `fee_open_currency` from one trade - which should 


I'd also like to see the "startup" logs - essentially the logs the bot generates until it starts generating the "heartbeat" messages.

Please also provide me with a screenshot for the API permissions .... which you should have access to iva "edit API key" (i only need the ticked boxes at the top - nothing else).

**Comment by xmatthias** [comment]
OK i've been able to recreate this - i think i'll have a fix ready soon - with a followup fix that'll properly fix this a little later.

**Comment by grainz** [comment]
> OK i've been able to recreate this - i think i'll have a fix ready soon - with a followup fix that'll properly fix this a little later.

Good news. I was just getting to turning on the additional logs. Thank you so much.

**Comment by kamil6x** [comment]
Any updates on the long term fix?  Is it another bug report or did the commit on July 4th fix the issue completely?

**Comment by xmatthias** [comment]
That fix works as is (with or without followup fix) - though the above mentioned followup fix has been provided shortly later.
If you're still encountering this, it's either a new, different problem - or you didn't update, so your bot is missing this fix.
