### ISSUE TITLE
How to send errors to telegram or notify the web UI

### ISSUE THREAD

**Issue by Mo7mud** [freqtrade/freqtrade#10406]
## Describe your environment

  * Operating system: Linux
  * Python Version: 3.10.12
  * CCXT version: 4.3.54
  * Freqtrade Version: 2024.7-dev
  
## Your question
How to send notifications with errors to telegram?
Like this one
![image](https://github.com/freqtrade/freqtrade/assets/12565380/3a9cea78-16e3-471c-8b9c-afddddc34352)

The bot in this case isn't trading actually but it isn't  stopped so we maybe don't pay attention to it and think that it's working.

**Comment by xmatthias** [comment]
well that's a very genericerror which happens before the bot actually started rpc afaik.

you can however use `/logs` to get the logs - if you're not able to look at the logs while the bot is starting (why wouldn't you? it's pretty easy to mess up a path to a config or whatever - so you should ALWAYS wait for the bot to properly start).


Runtime errors (which cause the bot to stop) will be sent to telegram _if possible_
it's however not guaranteed that all errors will be sent - as you could for example run out of memory - which means the python process will be killed - without freqtrade having the possibility to notify the user.

**Comment by Mo7mud** [comment]
This didn't happen before the bot starts, it happened after bot started with several hours and it was running.
This error happened due to change in my IP, so the bot was working already and was trying to get data repeatedly but can't because of the IP change.
The idea is to get notification that there is an error when you think that the bot is working fine but it isn't  , so I'll not think to look in the logs.
I looked into the logs as you can see.
So my problem is not seeing the logs
My problem is getting notifications whenever there is an error.
Is there any setting or anything I can do to send error messages to telegram when they happen?
As you see here the bot was already running when the IP changed and when I noticed it I fixed the IP problem then the bot resumed working without restarting or reloading.
I hope I explained it clearly.

```
2024-07-07 19:21:33 INFO    freqtrade.worker - Bot heartbeat. PID=65933, version='2024.7-dev', state='RUNNING'

2024-07-07 19:21:33 ERROR   freqtrade.exchange.exchange - Could not load markets.
Traceback (most recent call last):
  File "/home/freqtrade/freqtrade/exchange/exchange.py", line 563, in reload_markets
    self._markets = self._load_async_markets(reload=True)
  File "/home/freqtrade/freqtrade/exchange/exchange.py", line 536, in _load_async_markets
    markets = self.loop.run_until_complete(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/freqtrade/.venv/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 276, in load_markets
    raise e
  File "/home/freqtrade/.venv/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 272, in load_markets
    result = await self.markets_loading
  File "/home/freqtrade/.venv/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 261, in load_markets_helper
    currencies = await self.fetch_currencies()
  File "/home/freqtrade/.venv/lib/python3.10/site-packages/ccxt/async_support/binance.py", line 2637, in fetch_currencies
    response = await self.sapiGetCapitalConfigGetall(params)
  File "/home/freqtrade/.venv/lib/python3.10/site-packages/ccxt/async_support/binance.py", line 10420, in request
    response = await self.fetch2(path, api, method, params, headers, body, config)
  File "/home/freqtrade/.venv/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 829, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/freqtrade/.venv/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 243, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/freqtrade/.venv/lib/python3.10/site-packages/ccxt/async_support/binance.py", line 10388, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
  File "/home/freqtrade/.venv/lib/python3.10/site-packages/ccxt/base/exchange.py", line 4122, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.AuthenticationError: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}

2024-07-07 19:21:38 ERROR   freqtrade.exchange.exchange - Could not load markets.
Traceback (most recent call last):
  File "/home/freqtrade/freqtrade/exchange/exchange.py", line 563, in reload_markets
    self._markets = self._load_async_markets(reload=True)
  File "/home/freqtrade/freqtrade/exchange/exchange.py", line 536, in _load_async_markets
    markets = self.loop.run_until_complete(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/freqtrade/.venv/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 276, in load_markets
    raise e
  File "/home/freqtrade/.venv/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 272, in load_markets
    result = await self.markets_loading
  File "/home/freqtrade/.venv/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 261, in load_markets_helper
    currencies = await self.fetch_currencies()
  File "/home/freqtrade/.venv/lib/python3.10/site-packages/ccxt/async_support/binance.py", line 2637, in fetch_currencies
    response = await self.sapiGetCapitalConfigGetall(params)
  File "/home/freqtrade/.venv/lib/python3.10/site-packages/ccxt/async_support/binance.py", line 10420, in request
    response = await self.fetch2(path, api, method, params, headers, body, config)
  File "/home/freqtrade/.venv/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 829, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/freqtrade/.venv/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 243, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/freqtrade/.venv/lib/python3.10/site-packages/ccxt/async_support/binance.py", line 10388, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
  File "/home/freqtrade/.venv/lib/python3.10/site-packages/ccxt/base/exchange.py", line 4122, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.AuthenticationError: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}

2024-07-07 19:21:43 ERROR   freqtrade.exchange.exchange - Could not load markets.
Traceback (most recent call last):
  File "/home/freqtrade/freqtrade/exchange/exchange.py", line 563, in reload_markets
    self._markets = self._load_async_markets(reload=True)
  File "/home/freqtrade/freqtrade/exchange/exchange.py", line 536, in _load_async_markets
    markets = self.loop.run_until_complete(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/freqtrade/.venv/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 276, in load_markets
    raise e
  File "/home/freqtrade/.venv/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 272, in load_markets
    result = await self.markets_loading
  File "/home/freqtrade/.venv/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 261, in load_markets_helper
    currencies = await self.fetch_currencies()
  File "/home/freqtrade/.venv/lib/python3.10/site-packages/ccxt/async_support/binance.py", line 2637, in fetch_currencies
    response = await self.sapiGetCapitalConfigGetall(params)
  File "/home/freqtrade/.venv/lib/python3.10/site-packages/ccxt/async_support/binance.py", line 10420, in request
    response = await self.fetch2(path, api, method, params, headers, body, config)
  File "/home/freqtrade/.venv/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 829, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/freqtrade/.venv/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 243, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/freqtrade/.venv/lib/python3.10/site-packages/ccxt/async_support/binance.py", line 10388, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
  File "/home/freqtrade/.venv/lib/python3.10/site-packages/ccxt/base/exchange.py", line 4122, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.AuthenticationError: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}

2024-07-07 19:21:48 ERROR   freqtrade.exchange.exchange - Could not load markets.
Traceback (most recent call last):
  File "/home/freqtrade/freqtrade/exchange/exchange.py", line 563, in reload_markets
    self._markets = self._load_async_markets(reload=True)
  File "/home/freqtrade/freqtrade/exchange/exchange.py", line 536, in _load_async_markets
    markets = self.loop.run_until_complete(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/freqtrade/.venv/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 276, in load_markets
    raise e
  File "/home/freqtrade/.venv/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 272, in load_markets
    result = await self.markets_loading
  File "/home/freqtrade/.venv/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 261, in load_markets_helper
    currencies = await self.fetch_currencies()
  File "/home/freqtrade/.venv/lib/python3.10/site-packages/ccxt/async_support/binance.py", line 2637, in fetch_currencies
    response = await self.sapiGetCapitalConfigGetall(params)
  File "/home/freqtrade/.venv/lib/python3.10/site-packages/ccxt/async_support/binance.py", line 10420, in request
    response = await self.fetch2(path, api, method, params, headers, body, config)
  File "/home/freqtrade/.venv/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 829, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/freqtrade/.venv/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 243, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/freqtrade/.venv/lib/python3.10/site-packages/ccxt/async_support/binance.py", line 10388, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
  File "/home/freqtrade/.venv/lib/python3.10/site-packages/ccxt/base/exchange.py", line 4122, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.AuthenticationError: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}

2024-07-07 19:21:53 ERROR   freqtrade.exchange.exchange - Could not load markets.
Traceback (most recent call last):
  File "/home/freqtrade/freqtrade/exchange/exchange.py", line 563, in reload_markets
    self._markets = self._load_async_markets(reload=True)
  File "/home/freqtrade/freqtrade/exchange/exchange.py", line 536, in _load_async_markets
    markets = self.loop.run_until_complete(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/freqtrade/.venv/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 276, in load_markets
    raise e
  File "/home/freqtrade/.venv/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 272, in load_markets
    result = await self.markets_loading
  File "/home/freqtrade/.venv/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 261, in load_markets_helper
    currencies = await self.fetch_currencies()
  File "/home/freqtrade/.venv/lib/python3.10/site-packages/ccxt/async_support/binance.py", line 2637, in fetch_currencies
    response = await self.sapiGetCapitalConfigGetall(params)
  File "/home/freqtrade/.venv/lib/python3.10/site-packages/ccxt/async_support/binance.py", line 10420, in request
    response = await self.fetch2(path, api, method, params, headers, body, config)
  File "/home/freqtrade/.venv/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 829, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/freqtrade/.venv/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 243, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/freqtrade/.venv/lib/python3.10/site-packages/ccxt/async_support/binance.py", line 10388, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
  File "/home/freqtrade/.venv/lib/python3.10/site-packages/ccxt/base/exchange.py", line 4122, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.AuthenticationError: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}

2024-07-07 19:22:03 INFO    freqtrade.wallets - Wallets synced.

2024-07-07 19:22:03 INFO    freqtrade.wallets - Wallets synced.

2024-07-07 19:22:33 INFO    freqtrade.worker - Bot heartbeat. PID=65933, version='2024.7-dev', state='RUNNING'

2024-07-07 19:23:33 INFO    freqtrade.worker - Bot heartbeat. PID=65933, version='2024.7-dev', state='RUNNING'

```

**Comment by xmatthias** [comment]
Well quite franrkly - you'll need to work on your setup, especially considering that it's a live bot.


your IP changed - this implicitly means a few additional things:
* You're (probably) running on a home network
* your Network dropped to change the IP


You'll not want a bot stopped due to a network or power outage. These things happen at the most inopportune times - which can lead to losses (independent of notifications) - as you won't know how long you'll be gone.

Now the 2nd point is the problem in your case - your network dropped - which would be the first / initial error. 
Freqtrade couldn't have notified you of that in the first place - and we'd surely not notify you for every error (that'd spam you pretty good).

**Comment by Mo7mud** [comment]
My network didn't drop, the bot was connected to the internet but the IP changed so Binance refused the connection.
So the bot can reach Telegram at this point.
Regarding spamming it could be an option that we can switch on and off if needed.
Now the question is how can I send notification to telegram with errors when they happen regardless my case?
Is there any way to do it through config or strategy without the need of modifying bots code?
