### ISSUE TITLE
coinbase: Error when an internal function is executing add_dry_order_fee. "Fee" variable is set to None

### ISSUE THREAD

**Issue by piratmc** [freqtrade/freqtrade#10435]
## Describe your environment

  * Operating system: macOS Sonoma 14.5
  * Python version: Python 3.10.11
  * CCXT version: ccxt==4.3.24
  * Freqtrade version: freqtrade 2024.6
  
## Describe the problem:

I am getting an error. It seems to me "fee" is set to "None", and multiplication inside of add_dry_order_fee function is failing. 
I don't think I set it anywhere myself.

### Steps to reproduce:
 
  1. generate config.json
  2. update it ([config.json](https://github.com/user-attachments/files/16254524/config.json) is attached)
  3. kick off Ray-hosted model
  4. run `freqtrade trade -c user_data/config.json -s earl_6h`
  
### Observed Results:

An error occurs, and the process dies

### Relevant code exceptions or logs

  ```
2024-07-16 13:14:16,038 - freqtrade.wallets - INFO - Wallets synced.
2024-07-16 13:14:16,202 - freqtrade.freqtradebot - INFO - Long signal found: about create a new trade for BTC/USD with stake_amount: 198.0 ...
2024-07-16 13:14:16,203 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2024-07-16 13:14:16,203 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2024-07-16 13:14:16,203 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2024-07-16 13:14:16,203 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
2024-07-16 13:14:16,205 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/Users/dimer/freqtrade/freqtrade/main.py", line 43, in main
    return_code = args["func"](args)
  File "/Users/dimer/freqtrade/freqtrade/commands/trade_commands.py", line 25, in start_trading
    worker.run()
  File "/Users/dimer/freqtrade/freqtrade/worker.py", line 78, in run
    state = self._worker(old_state=state)
  File "/Users/dimer/freqtrade/freqtrade/worker.py", line 119, in _worker
    self._throttle(
  File "/Users/dimer/freqtrade/freqtrade/worker.py", line 160, in _throttle
    result = func(*args, **kwargs)
  File "/Users/dimer/freqtrade/freqtrade/worker.py", line 194, in _process_running
    self.freqtrade.process()
  File "/Users/dimer/freqtrade/freqtrade/freqtradebot.py", line 291, in process
    self.enter_positions()
  File "/Users/dimer/freqtrade/freqtrade/freqtradebot.py", line 630, in enter_positions
    trades_created += self.create_trade(pair)
  File "/Users/dimer/freqtrade/freqtrade/freqtradebot.py", line 695, in create_trade
    return self.execute_entry(
  File "/Users/dimer/freqtrade/freqtrade/freqtradebot.py", line 898, in execute_entry
    order = self.exchange.create_order(
  File "/Users/dimer/freqtrade/freqtrade/exchange/exchange.py", line 1175, in create_order
    dry_order = self.create_dry_run_order(
  File "/Users/dimer/freqtrade/freqtrade/exchange/exchange.py", line 986, in create_dry_run_order
    dry_order = self.check_dry_limit_order_filled(
  File "/Users/dimer/freqtrade/freqtrade/exchange/exchange.py", line 1103, in check_dry_limit_order_filled
    self.add_dry_order_fee(
  File "/Users/dimer/freqtrade/freqtrade/exchange/exchange.py", line 1005, in add_dry_order_fee
    "cost": dry_order["cost"] * fee,
TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'
  ```

**Comment by xmatthias** [comment]
coinbaseadvanced (nor coinbase) is not a supported exchange - so most likely, this is the first of many errors you may be encountering.

based on a very quick test - it seems like ccxt is not providing appropriate fees.
you can test this yourself eventually.


``` python
import ccxt
exchange = ccxt.coinbaseadvanced()
_ = exchange.load_markets()
print(exchange.calculate_fee('BTC/USDT', '', 'buy', 1, 1, 'taker'))
print(exchange.calculate_fee('BTC/USDT', '', 'buy', 1, 1, 'maker'))
```
``` output
{'type': 'taker', 'currency': 'USDT', 'rate': None, 'cost': None}
{'type': 'maker', 'currency': 'USDT', 'rate': None, 'cost': None}
```
Now now the usage of "advanced" is irrelevant - as that's just an alias in ccxt.

It's however an issue you'll want to raise with ccxt - as it's there the problem originates from.
As it's not a supported exchange, we'll not be doing the legwork to raise issues towards ccxt in this case.

**Comment by lighterletter** [comment]
I ran into the same issue with a different stack trace when trying to do some backtesting: 

```
- freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 43, in main
    return_code = args["func"](args)
                  ^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 59, in start_backtesting
    backtesting = Backtesting(config)
                  ^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 181, in __init__
    self.fee = max(fee for fee in fees if fee is not None)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: max() iterable argument is empty
```

I raised an issue with ccxt:
https://github.com/ccxt/ccxt/issues/23345

**Comment by xmatthias** [comment]
coinbase is not supported, and can't be supported unless we get proper fees for it.

If we continue to get reports about this - i'll gladly be adding a hard block for coinbase to actively alert users about it (for now, i'll wait for the outcome of the ccxt issue though - but i guess you'll need to provide a non-freqtrade reproduction for ccxt to become active).

**Comment by lighterletter** [comment]
Thanks! It looks like a PR was merged, but it would require a version bump; I saw the last one was a couple of days ago, so it may be addressed in the next one. Thanks for the great work!

**Comment by xmatthias** [comment]
yes it will be
you can however bump ccxt manually for the time being with `pip install -U ccxt`.

**Comment by lighterletter** [comment]
Thanks for the tip! I tried that, and the version bumped both on my machine and the docker container, but when reloading or running the bot, it still uses `4.3.65` from stable. Is there a way to override the version in the `config.json` `ccxt_config` attribute?

I tried it, and the output was pretty clean. It looks like the changes are applied twice,

```
freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
freqtrade.exchange.exchange - INFO - Using CCXT 4.3.65
2024-08-08 02:09:44,578 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'version': '4.3.76'}
2024-08-08 02:09:44,582 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'version': '4.3.76'}
2024-08-08 02:09:44,586 - freqtrade.exchange.exchange - INFO - Using Exchange "Coinbase Advanced"
``` 
but I don't know if they're being processed internally because I get the same output. 

I looked at the docker config, and setting the version doesn't seem to be an option. I also couldn't find a command or flag to run the bot with a specific ccxt version. It may be something like that can be useful for testing. 
Thanks for the help, btw!

**Comment by xmatthias** [comment]
that's not how python works.
it'll use whatever version is installed - providing a version as a config key won't work.

If you're using docker - you'll need to rebuild the image - or wait for the version bump.

**Comment by lighterletter** [comment]
Ah, I got it! I'm using docker, I was running the command outside the container 🤦‍♂️ lol
😅 You're the best, thanks for the help! 🙏
