### ISSUE TITLE
Strategy - Encountering Persistent Errors

### ISSUE THREAD

**Issue by hfazlioglu** [freqtrade/freqtrade#10450]
## Describe your environment

  * Operating system: win 11 pro
  * Python Version: 3.12.4
  * CCXT version: 4.3.50
  * Freqtrade Version: 2024.6 
  
Hello Freqtrade community,

I am using a Freqtrade strategy  and I am consistently encountering the following error: . This error occurs when I try to run the strategy, and it prevents the bot from functioning properly.

I have included my strategy code below:
``` python
import pandas as pd
from freqtrade.strategy.interface import IStrategy
from pandas import DataFrame, Series
import talib.abstract as ta
import numpy as np
from freqtrade.data.dataprovider import DataProvider
from freqtrade.data.btanalysis import load_backtest_data
from freqtrade.exchange import timeframe_to_prev_date
from datetime import datetime, timedelta

class sample_strategy(IStrategy):
    INTERFACE_VERSION = 3

    minimal_roi = {
        "0": 0.1
    }

    stoploss = -0.10

    timeframe = '1m'
    
    # Define additional informative timeframes
    informative_timeframes = ['15m', '30m']
    
    process_only_new_candles = True
    startup_candle_count = 30

    def informative_pairs(self):
        """
        Define informative pairs to use additional timeframes
        """
        pairs = self.dp.current_whitelist()
        informative_pairs = [(pair, timeframe) for pair in pairs for timeframe in self.informative_timeframes]
        return informative_pairs

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Adds several different TA indicators to the given DataFrame
        """
        # Get the informative data for the different timeframes
        inf_15m = self.dp.get_pair_dataframe(pair=metadata['pair'], timeframe='15m')
        inf_30m = self.dp.get_pair_dataframe(pair=metadata['pair'], timeframe='30m')

        # Calculation for White line (15m)
        inf_15m['cld1'] = inf_15m['close']
        inf_15m['opd1'] = inf_15m['open']
        inf_15m['high1'] = inf_15m['high']
        inf_15m['low1'] = inf_15m['low']
        inf_15m['tu1'] = (inf_15m['cld1'] + inf_15m['opd1'] + inf_15m['high1'] + inf_15m['low1']) / 4

        # Calculation for Yellow line (30m)
        inf_30m['cld2'] = inf_30m['close']
        inf_30m['opd2'] = inf_30m['open']
        inf_30m['high2'] = inf_30m['high']
        inf_30m['low2'] = inf_30m['low']
        inf_30m['tu2'] = (inf_30m['cld2'] + inf_30m['opd2'] + inf_30m['high2'] + inf_30m['low2']) / 4

        # Merge the informative dataframes into the main dataframe
        dataframe = merge_informative_pair(dataframe, inf_15m, self.timeframe, '15m', ffill=True)
        dataframe = merge_informative_pair(dataframe, inf_30m, self.timeframe, '30m', ffill=True)

        return dataframe

    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators, populates the buy signal for the given dataframe
        """
        dataframe.loc[
            (
                (dataframe['tu1_15m'] > dataframe['tu2_30m'])  # TU1 crosses above TU2
            ),
            'buy'] = 1
        return dataframe

    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators, populates the sell signal for the given dataframe
        """
        dataframe.loc[
            (
                (dataframe['tu1_15m'] < dataframe['tu2_30m'])  # TU1 crosses below TU2
            ),
            'sell'] = 1
        return dataframe
```

error code 

```
Traceback (most recent call last):
  File "/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 28, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/strategy/interface.py", line 1061, in _analyze_ticker_internal
    dataframe = self.analyze_ticker(dataframe, metadata)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/strategy/interface.py", line 1040, in analyze_ticker
    dataframe = self.advise_indicators(dataframe, metadata)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/strategy/interface.py", line 1613, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/user_data/strategies/sample_strategy.py", line 59, in populate_indicators
    dataframe = merge_informative_pair(dataframe, inf_15m, self.timeframe, '15m', ffill=True)
                ^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'merge_informative_pair' is not defined
2024-07-22 14:37:07,710 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair BTC/USDT: name 'merge_informative_pair' is not defined
2024-07-22 14:37:07,722 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair BTC/USDT
2024-07-22 14:37:12,694 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error name 'merge_informative_pair' is not defined calling <bound method IStrategy._analyze_ticker_internal of <sample_strategy.sample_strategy object at 0x7f98b6001880>>
Traceback (most recent call last):
  File "/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 28, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/strategy/interface.py", line 1061, in _analyze_ticker_internal
    dataframe = self.analyze_ticker(dataframe, metadata)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/strategy/interface.py", line 1040, in analyze_ticker
    dataframe = self.advise_indicators(dataframe, metadata)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/strategy/interface.py", line 1613, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/user_data/strategies/sample_strategy.py", line 59, in populate_indicators
    dataframe = merge_informative_pair(dataframe, inf_15m, self.timeframe, '15m', ffill=True)
                ^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'merge_informative_pair' is not defined
2024-07-22 14:37:12,710 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair BTC/USDT: name 'merge_informative_pair' is not defined
2024-07-22 14:37:12,732 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair BTC/USDT
2024-07-22 14:37:14,366 - uvicorn.error - INFO - ('172.23.0.1', 34012) - "WebSocket /api/v1/message/ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGVudGl0eSI6eyJ1IjoiaGZfZnJlcXRyYWRlIn0sImV4cCI6MTcyMTY1OTc3NSwiaWF0IjoxNzIxNjU4ODc1LCJ0eXBlIjoiYWNjZXNzIn0.dbk8d_hmCenoJdFuLWYHu0RWHR3VzI2_UcMaOklUp1w" [accepted]
2024-07-22 14:37:14,377 - freqtrade.rpc.api_server.ws.channel - INFO - Connected to channel - WebSocketChannel(2747451d, ('172.23.0.1', 34012))
2024-07-22 14:37:14,384 - uvicorn.error - INFO - connection open
2024-07-22 14:37:17,699 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error name 'merge_informative_pair' is not defined calling <bound method IStrategy._analyze_ticker_internal of <sample_strategy.sample_strategy object at 0x7f98b6001880>>
```

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by stash86** [comment]
`NameError: name 'merge_informative_pair' is not defined`

**Comment by xmatthias** [comment]
in python - when you want to use a function - you usually have to import that.

update your strategy's line 2 to the following and it should work. `from freqtrade.strategy import IStrategy, merge_informative_pair`

**Comment by hfazlioglu** [comment]
Thanks, it worked, but it did not give the same result as the backtest I did on tradingview.

> in python - when you want to use a function - you usually have to import that.
> 
> update your strategy's line 2 to the following and it should work. `from freqtrade.strategy import IStrategy, merge_informative_pair`

Thanks, it worked, but it did not give the same result as the backtest I did on tradingview.

**Comment by stash86** [comment]
We never claim that we can match tradingview, nor do we want to match it. Both use different ways to do backtest and to calculate indicators
