### ISSUE TITLE
Fetch public trades failed

### ISSUE THREAD

**Issue by CandersA** [freqtrade/freqtrade#10515]
## Describe your environment

  * Operating system: Linux
  * Python Version: 3.12.4
  * CCXT version: 4.3.65
  * Freqtrade Version: docker-2024.7-dev-5eab5b11

## Describe the problem:

When trying to fetch public trades, the fetch fails with multiple errors. It worked previously.

### Steps to reproduce:

  1. Use the development freqtrade version with fetch public trades functionality;
  2. Add "use_public_trades": true and "orderflow" object to configuration;
  3. I guess keep restarting the bot, which I did while I was testing and making changes.

My orderflow object in config:
"orderflow": {
      "cache_size": 1, 
      "max_candles": 30, 
      "scale": 0.5, 
      "stacked_imbalance_range": 3,
      "imbalance_volume": 1,
      "imbalance_ratio": 3 
   },
  
### Observed Results:

  * What happened?
  The bot fails to start with multiple errors given below. This happened when I changed the timeframe from 5m to 1h. It was loading for a long time. Then the errors kept coming once I changed the timeframe back to 5m.
  * What did you expect to happen?
  It wasn't unexpected for the bot to fail based on some kind of API limitation. But this may not be the case, I don't know. I'd just like to see an appropriate error if I've exceeded any limits.

### Relevant code exceptions or logs

```
2024-08-08 16:52:13 freqtrade  | 2024-08-08 13:52:13,896 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': "*Exchange:* `binance`\n*Stake per trade:* `200 USDT`\n*Minimum ROI:* `{'0': 0.04}`\n*Stoploss:* `-0.04`\n*Position adjustment:* `Off`\n*Timeframe:* `5m`\n*Strategy:* `shortTermBTC`"}
2024-08-08 16:52:13 freqtrade  | 2024-08-08 13:52:13,898 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': "Searching for USDT pairs to buy and sell based on [{'StaticPairList': 'StaticPairList'}]"}
2024-08-08 16:52:14 freqtrade  | 2024-08-08 13:52:14,608 - freqtrade.exchange.exchange - ERROR - Refreshing TRADES data for BTC/USDT:USDT failed
2024-08-08 16:52:14 freqtrade  | Traceback (most recent call last):
2024-08-08 16:52:14 freqtrade  |   File "/freqtrade/freqtrade/exchange/exchange.py", line 2728, in refresh_latest_trades
2024-08-08 16:52:14 freqtrade  |     all_stored_ticks_df = data_handler.trades_load(
2024-08-08 16:52:14 freqtrade  |                           ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-08 16:52:14 freqtrade  |   File "/freqtrade/freqtrade/data/history/datahandlers/idatahandler.py", line 251, in trades_load
2024-08-08 16:52:14 freqtrade  |     self._trades_load(pair, trading_mode, timerange=timerange)
2024-08-08 16:52:14 freqtrade  |   File "/freqtrade/freqtrade/data/history/datahandlers/featherdatahandler.py", line 125, in _trades_load
2024-08-08 16:52:14 freqtrade  |     tradesdata = read_feather(filename)
2024-08-08 16:52:14 freqtrade  |                  ^^^^^^^^^^^^^^^^^^^^^^
2024-08-08 16:52:14 freqtrade  |   File "/home/ftuser/.local/lib/python3.12/site-packages/pandas/io/feather_format.py", line 124, in read_feather
2024-08-08 16:52:14 freqtrade  |     return feather.read_feather(
2024-08-08 16:52:14 freqtrade  |            ^^^^^^^^^^^^^^^^^^^^^
2024-08-08 16:52:14 freqtrade  |   File "/home/ftuser/.local/lib/python3.12/site-packages/pyarrow/feather.py", line 226, in read_feather
2024-08-08 16:52:14 freqtrade  |     return (read_table(
2024-08-08 16:52:14 freqtrade  |             ^^^^^^^^^^^
2024-08-08 16:52:14 freqtrade  |   File "/home/ftuser/.local/lib/python3.12/site-packages/pyarrow/feather.py", line 252, in read_table
2024-08-08 16:52:14 freqtrade  |     reader = _feather.FeatherReader(
2024-08-08 16:52:14 freqtrade  |              ^^^^^^^^^^^^^^^^^^^^^^^
2024-08-08 16:52:14 freqtrade  |   File "pyarrow/_feather.pyx", line 79, in pyarrow._feather.FeatherReader.__cinit__
2024-08-08 16:52:14 freqtrade  |   File "pyarrow/error.pxi", line 155, in pyarrow.lib.pyarrow_internal_check_status
2024-08-08 16:52:14 freqtrade  |   File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
2024-08-08 16:52:14 freqtrade  | pyarrow.lib.ArrowInvalid: Not an Arrow file
2024-08-08 16:52:14 freqtrade  | 2024-08-08 13:52:14,616 - freqtrade.data.converter.orderflow - ERROR - Error populating dataframe with trades
2024-08-08 16:52:14 freqtrade  | Traceback (most recent call last):
2024-08-08 16:52:14 freqtrade  |   File "/freqtrade/freqtrade/data/converter/orderflow.py", line 91, in populate_dataframe_with_trades
2024-08-08 16:52:14 freqtrade  |     trades = trades.loc[trades.candle_start >= start_date]
2024-08-08 16:52:14 freqtrade  |                         ^^^^^^^^^^^^^^^^^^^
2024-08-08 16:52:14 freqtrade  |   File "/home/ftuser/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 6299, in __getattr__
2024-08-08 16:52:14 freqtrade  |     return object.__getattribute__(self, name)
2024-08-08 16:52:14 freqtrade  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-08 16:52:14 freqtrade  | AttributeError: 'DataFrame' object has no attribute 'candle_start'
2024-08-08 16:52:14 freqtrade  | 2024-08-08 13:52:14,629 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error 'DataFrame' object has no attribute 'candle_start' calling <bound method IStrategy._analyze_ticker_internal of <shortTermBTC.shortTermBTC object at 0x7f9f7a21d970>>
2024-08-08 16:52:14 freqtrade  | Traceback (most recent call last):
2024-08-08 16:52:14 freqtrade  |   File "/freqtrade/freqtrade/data/converter/orderflow.py", line 91, in populate_dataframe_with_trades
2024-08-08 16:52:14 freqtrade  |     trades = trades.loc[trades.candle_start >= start_date]
2024-08-08 16:52:14 freqtrade  |                         ^^^^^^^^^^^^^^^^^^^
2024-08-08 16:52:14 freqtrade  |   File "/home/ftuser/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 6299, in __getattr__
2024-08-08 16:52:14 freqtrade  |     return object.__getattribute__(self, name)
2024-08-08 16:52:14 freqtrade  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-08 16:52:14 freqtrade  | AttributeError: 'DataFrame' object has no attribute 'candle_start'
2024-08-08 16:52:14 freqtrade  | 
2024-08-08 16:52:14 freqtrade  | During handling of the above exception, another exception occurred:
2024-08-08 16:52:14 freqtrade  | 
2024-08-08 16:52:14 freqtrade  | Traceback (most recent call last):
2024-08-08 16:52:14 freqtrade  |   File "/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 28, in wrapper
2024-08-08 16:52:14 freqtrade  |     return f(*args, **kwargs)
2024-08-08 16:52:14 freqtrade  |            ^^^^^^^^^^^^^^^^^^
2024-08-08 16:52:14 freqtrade  |   File "/freqtrade/freqtrade/strategy/interface.py", line 1069, in _analyze_ticker_internal
2024-08-08 16:52:14 freqtrade  |     dataframe = self.analyze_ticker(dataframe, metadata)
2024-08-08 16:52:14 freqtrade  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-08 16:52:14 freqtrade  |   File "/freqtrade/freqtrade/strategy/interface.py", line 1047, in analyze_ticker
2024-08-08 16:52:14 freqtrade  |     dataframe = self.advise_indicators(dataframe, metadata)
2024-08-08 16:52:14 freqtrade  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-08 16:52:14 freqtrade  |   File "/freqtrade/freqtrade/strategy/interface.py", line 1644, in advise_indicators
2024-08-08 16:52:14 freqtrade  |     self._if_enabled_populate_trades(dataframe, metadata)
2024-08-08 16:52:14 freqtrade  |   File "/freqtrade/freqtrade/strategy/interface.py", line 1617, in _if_enabled_populate_trades
2024-08-08 16:52:14 freqtrade  |     dataframe, cached_grouped_trades = populate_dataframe_with_trades(
2024-08-08 16:52:14 freqtrade  |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-08 16:52:14 freqtrade  |   File "/freqtrade/freqtrade/data/converter/orderflow.py", line 206, in populate_dataframe_with_trades
2024-08-08 16:52:14 freqtrade  |     raise DependencyException(e)
2024-08-08 16:52:14 freqtrade  | freqtrade.exceptions.DependencyException: 'DataFrame' object has no attribute 'candle_start'
2024-08-08 16:52:14 freqtrade  | 2024-08-08 13:52:14,641 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair BTC/USDT:USDT: 'DataFrame' object has no attribute 'candle_start'
```

**Comment by xmatthias** [comment]
well i doubt that "this" log will help us.

> `2024-08-08 16:52:14 freqtrade  | pyarrow.lib.ArrowInvalid: Not an Arrow file`

The above highlighted line points to the actual problem - the file is corrupt.
Why this is will not be in "this" log - but in the one where the file was written - and could very well have been caused by a very sudden interruption (e.g. pressing ctrl+c multiple times).

Simply put - based on this log - your fix is "remove the faulty file".
If you got the previous log - it's something we can investigate - otherwise - i'd not know how - as i did start a bot with populate_trades probably 100ds of times - and never had this problem.

**Comment by CandersA** [comment]
Here is the very first error which crashed the startup process of my bot. This is an obvious error and I fixed it immediately. I meant to pass a string to my function, but forgot to put quotes around it. After I fixed this I changed the timeframe from 1h to 5m, because I wanted to make sure the bot was running properly without waiting for the fetching of 1h candle public trades. The error above started appearing.

```
2024-08-08 15:48:07 freqtrade  | 2024-08-08 12:48:07,564 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error name 'daily' is not defined calling <bound method IStrategy._analyze_ticker_internal of <shortTermBTC.shortTermBTC object at 0x7f00e5304b90>>
2024-08-08 15:48:07 freqtrade  | Traceback (most recent call last):
2024-08-08 15:48:07 freqtrade  |   File "/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 28, in wrapper
2024-08-08 15:48:07 freqtrade  |     return f(*args, **kwargs)
2024-08-08 15:48:07 freqtrade  |            ^^^^^^^^^^^^^^^^^^
2024-08-08 15:48:07 freqtrade  |   File "/freqtrade/freqtrade/strategy/interface.py", line 1069, in _analyze_ticker_internal
2024-08-08 15:48:07 freqtrade  |     dataframe = self.analyze_ticker(dataframe, metadata)
2024-08-08 15:48:07 freqtrade  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-08 15:48:07 freqtrade  |   File "/freqtrade/freqtrade/strategy/interface.py", line 1047, in analyze_ticker
2024-08-08 15:48:07 freqtrade  |     dataframe = self.advise_indicators(dataframe, metadata)
2024-08-08 15:48:07 freqtrade  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-08 15:48:07 freqtrade  |   File "/freqtrade/freqtrade/strategy/interface.py", line 1645, in advise_indicators
2024-08-08 15:48:07 freqtrade  |     return self.populate_indicators(dataframe, metadata)
2024-08-08 15:48:07 freqtrade  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-08 15:48:07 freqtrade  |   File "/freqtrade/user_data/strategies/shortTermBTC.py", line 86, in populate_indicators
2024-08-08 15:48:07 freqtrade  |     dataframe['volume_profile'] = create_volume_profile(dataframe, self.timeframe, daily)
2024-08-08 15:48:07 freqtrade  |                                                                                    ^^^^^
2024-08-08 15:48:07 freqtrade  | NameError: name 'daily' is not defined
2024-08-08 15:48:07 freqtrade  | 2024-08-08 12:48:07,569 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair BTC/USDT:USDT: name 'daily' is not defined
2024-08-08 15:48:07 freqtrade  | 2024-08-08 12:48:07,582 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair BTC/USDT:USDT
```

If you mean any other logs than the freqtrade log, I don't have that.

**Comment by xmatthias** [comment]
well no, it'll be freqtrade logs for sure - but not a regular strategy error.

It might've been earlier - or later (most likely - it's the run where you first saw `pyarrow.lib.ArrowInvalid: Not an Arrow file`.

can you maybe do a `ls -l user_data/data/<yourexchange>` and share the results (hoping you didn't remove the file yet) ?

**Comment by CandersA** [comment]
I haven't removed any user_data files in a while. Manually at least.

$ ls -l user_data/data/binance
total 0
drwxr-xr-x 1 ftuser ftuser 4096 Jul 23 11:21 futures

I also pulled and composed the docker container again, but that didn't change anything. 

When orderflow object and use_public_trades is removed from config and all lines of code regarding orderflow are commented out of strategy file, everything works fine. But then I used the original orderflow configuration and changed the only pair in StaticPairList from "BTC/USDT:USDT" to "ETH/USDT:USDT" and the orderflow works correctly again.

So it seems the issue is only with BTC data, which would make sense, because it was the only pair in the config.

**Comment by xmatthias** [comment]
well it's futures - so `ls -l user_data/data/binance/futures` is what we'll need.

**Comment by CandersA** [comment]
I realised what file you needed to see. It was this file "BTC_USDT_USDT-cached-trades", which I moved to a different directory. Once the file didn't exist in the futures folder, freqtrade created a new file and everything works fine.

How would you like me to display the content of the original faulty file? I wanted to add it here, but can't. So probably there is a command.

**Comment by xmatthias** [comment]
my initial suspicion is that it's size 0 if i'm honest (an empty file) - where there isn't really something to share.

if it's not - maybe you can zip it - which should be uploadable here.
the alternative is - get in touch on discord - where i believe sharing should work.

**Comment by CandersA** [comment]
[BTC_USDT_USDT-cached-trades.zip](https://github.com/user-attachments/files/16568933/BTC_USDT_USDT-cached-trades.zip)

I'll just share it here in hopes there will be a closing conclusion regarding this issue. The file is 35MB, so it isn't empty, but not sure if that's how it works.

**Comment by xmatthias** [comment]
While we can (and will) improve handling of such a situation - the problem remains that the file is corrupt (it's not empty - but still not a arrow file for whatever reason.

What led to this is unknown - and you should keep an eye on this (essentially for exceptions when loading cached data), as it could be a sign of a slowly (or also fast) breaking disk.
Now there's tons of other scenarios that can lead to a corrupt file, too (oom at an inopportune time, shutdown while writing, attempted manual modification of the file) - but there's no sign of these from what you're writing above - making a problem with the disk likely.
