### ISSUE TITLE
Bad response from coinmarketcap.com causes bot to crash

### ISSUE THREAD

**Issue by creslinux** [freqtrade/freqtrade#1052]
Directing CMC calls to an internal webserver discovered by accident that if the response isn't what the bot expects the bot crashes .

If coinmarketcap.com in real life has a bad day, returns junk, this should not cause freqtrade to crash. 

```
2018-07-21T09:03:52.460172600Z 2018-07-21 09:03:52,460 - freqtrade.freqtradebot - INFO - Starting freqtrade 0.17.1
2018-07-21T09:03:52.462962628Z 2018-07-21 09:03:52,462 - freqtrade.strategy.resolver - INFO - Using resolved strategy drytest from '/freqtrade/user_data/strategies'
2018-07-21T09:03:52.463336085Z 2018-07-21 09:03:52,463 - freqtrade.strategy.resolver - INFO - Override strategy 'ticker_interval' with value in config file: 5m.
2018-07-21T09:03:52.747250440Z 2018-07-21 09:03:52,745 - freqtrade - ERROR - Fatal exception!
2018-07-21T09:03:52.747315154Z Traceback (most recent call last):
2018-07-21T09:03:52.747334690Z   File "/freqtrade/freqtrade/main.py", line 45, in main
2018-07-21T09:03:52.747353198Z     freqtrade = FreqtradeBot(config)
2018-07-21T09:03:52.747369315Z   File "/freqtrade/freqtrade/freqtradebot.py", line 53, in __init__
2018-07-21T09:03:52.747386269Z     self.fiat_converter = CryptoToFiatConverter()
2018-07-21T09:03:52.747402381Z   File "/freqtrade/freqtrade/fiat_convert.py", line 86, in __init__
2018-07-21T09:03:52.747413407Z     self._load_cryptomap()
2018-07-21T09:03:52.747422809Z   File "/freqtrade/freqtrade/fiat_convert.py", line 92, in _load_cryptomap
2018-07-21T09:03:52.747432702Z     coinlistings["data"]))
2018-07-21T09:03:52.747442715Z TypeError: 'JSONDecodeError' object is not subscriptable
2018-07-21T09:03:52.747336930Z conn is HTTPSConnectionPool(host='api.coinmarketcap.com', port=443)
```

**Comment by shusso** [comment]
should be fixed with #1057
