### ISSUE TITLE
python3.7: fatal exception on TypeError

### ISSUE THREAD

**Issue by shusso** [freqtrade/freqtrade#1064]
When trying to run freqtrade with python3.7 we get the following fatal exception:
```
2018-07-24 12:47:43,113 - freqtrade.configuration - INFO - Verbosity set to 0
2018-07-24 12:47:43,113 - freqtrade.configuration - INFO - Parameter --dynamic-whitelist detected. Using dynamically generated whitelist. (not applicable with Backtesting and Hyperopt)
2018-07-24 12:47:43,113 - freqtrade.configuration - INFO - Dry run is enabled
2018-07-24 12:47:43,113 - freqtrade.configuration - INFO - Using DB: "sqlite://"
2018-07-24 12:47:43,113 - freqtrade.configuration - INFO - Using max_open_trades: 15 ...
2018-07-24 12:47:43,113 - freqtrade.configuration - INFO - Using data folder: user_data/data/binance ...
2018-07-24 12:47:43,114 - freqtrade.freqtradebot - INFO - Starting freqtrade 0.17.1
2018-07-24 12:47:43,118 - freqtrade.strategy.resolver - INFO - Using resolved strategy DefaultStrategy from '/Users/shusso/GoogleDrive/code/freqtrade/freqtrade/strategy'
2018-07-24 12:47:43,118 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/Users/shusso/GoogleDrive/code/freqtrade/freqtrade/main.py", line 45, in main
    freqtrade = FreqtradeBot(config)
  File "/Users/shusso/GoogleDrive/code/freqtrade/freqtrade/freqtradebot.py", line 51, in __init__
    self.strategy: IStrategy = StrategyResolver(self.config).strategy
  File "/Users/shusso/GoogleDrive/code/freqtrade/freqtrade/strategy/resolver.py", line 38, in __init__
    extra_dir=config.get('strategy_path'))
  File "/Users/shusso/GoogleDrive/code/freqtrade/freqtrade/strategy/resolver.py", line 95, in _load_strategy
    return import_strategy(strategy, config=config)
  File "/Users/shusso/GoogleDrive/code/freqtrade/freqtrade/strategy/__init__.py", line 16, in import_strategy
    attr = deepcopy({**strategy.__class__.__dict__, **strategy.__dict__})
  File "/Users/shusso/.local/share/virtualenvs/freqtrade-IlLijMZy/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/Users/shusso/.local/share/virtualenvs/freqtrade-IlLijMZy/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/Users/shusso/.local/share/virtualenvs/freqtrade-IlLijMZy/lib/python3.7/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle _abc_data objects
```

I'll investigate more

**Comment by xmatthias** [comment]
you can avoid this problem if you remove the ABC inheritance on the interface class

however it's odd as it is working perfectly fine in 3.6, so something must have chaned in either abstract baseclass or pickle ...

**Comment by xmatthias** [comment]
There are 2 possibilities i currently see after doing some research:

* drop the ABC inheritance
* filter `_abc_impl` in `import_strategy` before running deepcopy

The first seems simple, the 2nd solution hacky - so both are not ideal.

i did find only one reference to a similar problem [here](https://github.com/cloudpipe/cloudpickle/issues/180) - i'll add that link here so we can track their progress too.

**Comment by xmatthias** [comment]
Should work now since #1141 was merged.
