### ISSUE TITLE
Mismatch predicted class of trained model with XGBoost Classifier

### ISSUE THREAD

**Issue by b2r66sun** [freqtrade/freqtrade#10653]
## Describe your environment

  * Operating system: __Ubuntu22.04__
  * Python Version: __3.10.14___ (`python -V`)
  * CCXT version: _4.3.46____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: __2024.9-dev-ae41ab101__ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

I use the XGBoost Classifier with three classes(hold, long and short). After invoking the `fit` function, The model shall has an attribute that `self.model.classes_` is `[0, 1, 2]`. However when inspected in the `predict` function, it only returns `[0]` and, in the `BaseClassifierModel`, it seems to append the probablity to the `pred_df`, causing it 2x length of the `do_predict`. This also raises error for length mismatch.

### Steps to reproduce:

  1. __Define a Myclassifier in which replace the `LabelEncoder` `fit_transform` with, first `fit(['hold', 'long', 'short']` Then `transform`, see source file attached below. ___
  2. ___Add some logs in `BaseClassifierModel.py`_, print the `model.classes_`. in both `train` and `predict` function._
  3. ___Run Backtest script `freqtrade backtesting --strategy FreqaiPivot --strategy-path freqtrade/templates --config user_data/config_freqai.json --freqaimodel XGBoostClassifier --timerange 20240101-20240724 --timeframe 1h`__
  
### Observed Results:

  * What happened? 
  It raises `ValueError: Length of values (168) does not match length of index (336)`. That's because the concatnate of prob after the predicted label. Moreover, the logging of `self.model.classes_` in `predict` function returns `[0]`
  * What did you expect to happen? 
  `self.model.classes_` shall be `[0, 1, 2]`

#### Strategy File
```python
# pragma pylint: disable=missing-docstring, invalid-name, pointless-string-statement
# flake8: noqa: F401
# isort: skip_file
import logging
from functools import reduce
from typing import Dict

import talib.abstract as ta
from pandas import DataFrame
from technical import qtpylib

from freqtrade.strategy import IStrategy


logger = logging.getLogger(__name__)


class FreqaiPivot(IStrategy):

    INTERFACE_VERSION = 3
    timeframe = "1d"

    order_types = {
        "entry": "market",
        "exit": "market",
        "stoploss": "market",
        "stoploss_on_exchange": True,
    }
    order_time_in_force = {"entry": "GTC", "exit": "GTC"}

    plot_config = {
        "main_plot": {},
        "subplots": {
            "do_predict": {
                "do_predict": {"color": "blue"},
            },
        },
    }

    minimal_roi = {"0": 0.3, "600": 0.1, "1200": 0.05, "2400": 0}
    stoploss = -0.05

    process_only_new_candles = False
    trailing_stop = True
    trailing_stop_positive = 0.02
    trailing_stop_positive_offset = 0.05
    trailing_only_offset_is_reached = True
    use_exit_signal = False
    startup_candle_count: int = 80
    can_short = True

    def feature_engineering_expand_all(self, dataframe: DataFrame, period: int, metadata: Dict, **kwargs) -> DataFrame:

        dataframe["%-rsi-period"] = ta.RSI(dataframe, timeperiod=period)
        dataframe["%-mfi-period"] = ta.MFI(dataframe, timeperiod=period)
        dataframe["%-adx-period"] = ta.ADX(dataframe, timeperiod=period)
        dataframe["%-sma-period"] = ta.SMA(dataframe, timeperiod=period)
        dataframe["%-ema-period"] = ta.EMA(dataframe, timeperiod=period)

        bollinger = qtpylib.bollinger_bands(qtpylib.typical_price(dataframe), window=period)
        dataframe["bb_lowerband-period"] = bollinger["lower"]
        dataframe["bb_middleband-period"] = bollinger["mid"]
        dataframe["bb_upperband-period"] = bollinger["upper"]

        dataframe["%-bb_width-period"] = (dataframe["bb_upperband-period"] - dataframe["bb_lowerband-period"]) / dataframe[
            "bb_middleband-period"
        ]
        dataframe["%-close-bb_lower-period"] = dataframe["close"] / dataframe["bb_lowerband-period"]

        dataframe["%-roc-period"] = ta.ROC(dataframe, timeperiod=period)

        dataframe["%-relative_volume-period"] = dataframe["volume"] / dataframe["volume"].rolling(period).mean()

        return dataframe

    def feature_engineering_expand_basic(self, dataframe: DataFrame, metadata: Dict, **kwargs) -> DataFrame:

        dataframe["%-pct-change"] = dataframe["close"].pct_change()
        dataframe["%-raw_volume"] = dataframe["volume"]
        dataframe["%-raw_price"] = dataframe["close"]
        return dataframe

    def feature_engineering_standard(self, dataframe: DataFrame, metadata: Dict, **kwargs) -> DataFrame:

        dataframe["%-day_of_week"] = dataframe["date"].dt.dayofweek
        dataframe["%-hour_of_day"] = dataframe["date"].dt.hour
        return dataframe

    def set_freqai_targets(self, dataframe: DataFrame, metadata: Dict, **kwargs) -> DataFrame:

        look_ahead = self.freqai_info["feature_parameters"]["label_period_candles"]
        target_roi = self.freqai_info["feature_parameters"]["label_target_roi"]
        drawdown = self.freqai_info["feature_parameters"]["label_drawdown"]

        dataframe["&-s_entry"] = "hold"
        future_max_highs = dataframe["high"].shift(-look_ahead).rolling(look_ahead).max()
        future_min_lows = dataframe["low"].shift(-look_ahead).rolling(look_ahead).min()

        dataframe.loc[
            (future_max_highs > dataframe["close"] * (1 + target_roi))
            & (future_min_lows > dataframe["close"] * (1 - drawdown)),
            "&-s_entry",
        ] = "long"

        dataframe.loc[
            (future_min_lows < dataframe["close"] * (1 - target_roi))
            & (future_max_highs < dataframe["close"] * (1 + drawdown)),
            "&-s_entry",
        ] = "short"

        return dataframe

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        dataframe = self.freqai.start(dataframe, metadata, self)

        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        enter_long_conditions = [
            dataframe["do_predict"] == 1,
            dataframe["&-s_entry"] == "long",
        ]

        if enter_long_conditions:
            dataframe.loc[reduce(lambda x, y: x & y, enter_long_conditions), ["enter_long", "enter_tag"]] = (
                1,
                "long",
            )  # type: ignore

        enter_short_conditions = [
            dataframe["do_predict"] == 1,
            dataframe["&-s_entry"] == "short",
        ]

        if enter_short_conditions:
            dataframe.loc[reduce(lambda x, y: x & y, enter_short_conditions), ["enter_short", "enter_tag"]] = (
                1,
                "short",
            )  # type: ignore

        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        # Set to 0. Don't use this for now.
        dataframe.loc[:, 'exit_long'] = 0
        dataframe.loc[:, 'exit_short'] = 0

        return dataframe
```

#### Classifier
```python
import logging
from typing import Any, Dict, Tuple

import numpy as np
import numpy.typing as npt
import pandas as pd
from pandas import DataFrame
from pandas.api.types import is_integer_dtype
from sklearn.preprocessing import LabelEncoder
from xgboost import XGBClassifier

from freqtrade.freqai.base_models.BaseClassifierModel import BaseClassifierModel
from freqtrade.freqai.data_kitchen import FreqaiDataKitchen


logger = logging.getLogger(__name__)


class XGBoostClassifier(BaseClassifierModel):
    """
    User created prediction model. The class inherits IFreqaiModel, which
    means it has full access to all Frequency AI functionality. Typically,
    users would use this to override the common `fit()`, `train()`, or
    `predict()` methods to add their custom data handling tools or change
    various aspects of the training that cannot be configured via the
    top level config.json file.
    """

    def fit(self, data_dictionary: Dict, dk: FreqaiDataKitchen, **kwargs) -> Any:
        """
        User sets up the training and test data to fit their desired model here
        :param data_dictionary: the dictionary holding all data for train, test,
            labels, weights
        :param dk: The datakitchen object for the current coin/model
        """

        X = data_dictionary["train_features"].to_numpy()
        y = data_dictionary["train_labels"].to_numpy()[:, 0]

        le = LabelEncoder()
        le.fit(["hold", "long", "short"])
        if not is_integer_dtype(y):
            y = pd.Series(le.transform(y), dtype="int64")

        if self.freqai_info.get("data_split_parameters", {}).get("test_size", 0.1) == 0:
            eval_set = None
        else:
            test_features = data_dictionary["test_features"].to_numpy()
            test_labels = data_dictionary["test_labels"].to_numpy()[:, 0]

            if not is_integer_dtype(test_labels):
                test_labels = pd.Series(le.transform(test_labels), dtype="int64")

            eval_set = [(test_features, test_labels)]

        train_weights = data_dictionary["train_weights"]

        init_model = self.get_init_model(dk.pair)

        self.model = XGBClassifier(**self.model_training_parameters)

        self.model.fit(X=X, y=y, eval_set=eval_set, sample_weight=train_weights, xgb_model=init_model)

        return self.model

    def predict(
        self, unfiltered_df: DataFrame, dk: FreqaiDataKitchen, **kwargs
    ) -> Tuple[DataFrame, npt.NDArray[np.int_]]:
        """
        Filter the prediction features data and predict with it.
        :param unfiltered_df: Full dataframe for the current backtest period.
        :return:
        :pred_df: dataframe containing the predictions
        :do_predict: np.array of 1s and 0s to indicate places where freqai needed to remove
        data (NaNs) or felt uncertain about data (PCA and DI index)
        """
        (pred_df, dk.do_predict) = super().predict(unfiltered_df, dk, **kwargs)

        le = LabelEncoder()
        le.fit(["hold", "long", "short"])
        label = dk.label_list[0]
        labels_before = list(dk.data["labels_std"].keys())
        labels_after = le.transform(labels_before).tolist()

        # Replace the Nan values in pred_df[label] with 0
        pred_df[label] = pred_df[label].fillna(0)
        pred_df[label] = pred_df[label].astype(int)

        pred_df[label] = le.inverse_transform(pred_df[label])
        pred_df = pred_df.rename(
            columns={labels_after[i]: labels_before[i] for i in range(len(labels_before))}
        )

        return (pred_df, dk.do_predict)

```

#### Additional freqai config
```json
"freqai": {
        "feature_parameters": {
            "label_target_roi": 0.06,
            "label_drawdown": 0.04, 
        },
    }
```

#### Log
  ```
  // paste your log here
2024-09-15 18:30:55,680 - freqtrade - INFO - freqtrade 2024.9-dev-ae41ab101
2024-09-15 18:30:55,681 - freqtrade.configuration.load_config - INFO - Using config: user_data/config_freqai.json ...
2024-09-15 18:30:55,682 - freqtrade.loggers - INFO - Verbosity set to 0
2024-09-15 18:30:55,682 - freqtrade.configuration.configuration - INFO - Using additional Strategy lookup path: freqtrade/templates
2024-09-15 18:30:55,682 - freqtrade.configuration.configuration - INFO - Parameter -i/--timeframe detected ... Using timeframe: 1h ...
2024-09-15 18:30:55,682 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 8 ...
2024-09-15 18:30:55,682 - freqtrade.configuration.configuration - INFO - Parameter --timerange detected: 20240101-20240724 ...
2024-09-15 18:30:55,682 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/bryantsuen/workspace/Finance/freqtrade/user_data ...
2024-09-15 18:30:55,682 - freqtrade.configuration.configuration - INFO - Using data directory: /home/bryantsuen/workspace/Finance/freqtrade/user_data/data/binance ...
2024-09-15 18:30:55,682 - freqtrade.configuration.configuration - INFO - Overriding timeframe with Command line argument
2024-09-15 18:30:55,682 - freqtrade.configuration.configuration - INFO - Parameter --cache=day detected ...
2024-09-15 18:30:55,682 - freqtrade.configuration.configuration - INFO - Filter trades by timerange: 20240101-20240724
2024-09-15 18:30:55,682 - freqtrade.configuration.configuration - INFO - Using freqaimodel class name: XGBoostClassifier
2024-09-15 18:30:55,682 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2024-09-15 18:30:55,690 - freqtrade.exchange.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2024-09-15 18:30:55,690 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2024-09-15 18:30:55,690 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2024-09-15 18:30:55,692 - freqtrade.commands.optimize_commands - INFO - Starting freqtrade in Backtesting mode
2024-09-15 18:30:55,692 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2024-09-15 18:30:55,692 - freqtrade.exchange.exchange - INFO - Using CCXT 4.3.46
2024-09-15 18:30:55,693 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}}
2024-09-15 18:30:55,699 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}}
2024-09-15 18:30:55,707 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2024-09-15 18:30:57,258 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2024-09-15 18:30:57,353 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy FreqaiPivot from '/home/bryantsuen/workspace/Finance/freqtrade/user_data/strategies/FreqaiPivot.py'...
2024-09-15 18:30:57,353 - freqtrade.strategy.hyper - INFO - Found no parameter file.
2024-09-15 18:30:57,353 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 1h.
2024-09-15 18:30:57,353 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2024-09-15 18:30:57,353 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: unlimited.
2024-09-15 18:30:57,353 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}.
2024-09-15 18:30:57,353 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'max_open_trades' with value in config file: 8.
2024-09-15 18:30:57,353 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 0.3, '600': 0.1, '1200': 0.05, '2400': 0}
2024-09-15 18:30:57,353 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 1h
2024-09-15 18:30:57,353 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.05
2024-09-15 18:30:57,353 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: True
2024-09-15 18:30:57,353 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive: 0.02
2024-09-15 18:30:57,353 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.05
2024-09-15 18:30:57,353 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: True
2024-09-15 18:30:57,353 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2024-09-15 18:30:57,353 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
2024-09-15 18:30:57,353 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'entry': 'market', 'exit': 'market', 'stoploss': 'market', 'stoploss_on_exchange': True}
2024-09-15 18:30:57,353 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'entry': 'GTC', 'exit': 'GTC'}
2024-09-15 18:30:57,353 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2024-09-15 18:30:57,353 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: unlimited
2024-09-15 18:30:57,353 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2024-09-15 18:30:57,353 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 80
2024-09-15 18:30:57,353 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}
2024-09-15 18:30:57,353 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_exit_signal: False
2024-09-15 18:30:57,353 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_only: False
2024-09-15 18:30:57,353 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_entry_signal: False
2024-09-15 18:30:57,353 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_offset: 0.0
2024-09-15 18:30:57,353 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2024-09-15 18:30:57,353 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2024-09-15 18:30:57,353 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: False
2024-09-15 18:30:57,353 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1
2024-09-15 18:30:57,353 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_open_trades: 8
2024-09-15 18:30:57,354 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2024-09-15 18:30:57,359 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from '/home/bryantsuen/workspace/Finance/freqtrade/freqtrade/plugins/pairlist/StaticPairList.py'...
2024-09-15 18:30:57,366 - freqtrade.optimize.backtesting - INFO - Using fee 0.0500% - worst case fee from exchange (lowest tier).
2024-09-15 18:30:57,367 - freqtrade.data.dataprovider - INFO - Increasing startup_candle_count for freqai on 1h to 800
2024-09-15 18:30:57,368 - freqtrade.data.history.history_utils - INFO - Using indicator startup period: 800 ...
2024-09-15 18:30:57,480 - freqtrade.optimize.backtesting - INFO - Loading data from 2023-11-28 16:00:00 up to 2024-07-24 00:00:00 (238 days).
2024-09-15 18:30:57,620 - freqtrade.optimize.backtesting - INFO - Dataload complete. Calculating indicators
2024-09-15 18:30:57,621 - freqtrade.optimize.backtesting - INFO - Running backtesting for Strategy FreqaiPivot
2024-09-15 18:30:57,666 - freqtrade.resolvers.iresolver - INFO - Using resolved freqaimodel XGBoostClassifier from '/home/bryantsuen/workspace/Finance/freqtrade/user_data/freqaimodels/MyXGBoostClassifier.py'...
2024-09-15 18:30:57,666 - freqtrade.freqai.freqai_interface - INFO - Backtesting module configured to save all models.
2024-09-15 18:30:57,666 - freqtrade.freqai.data_drawer - INFO - Could not find existing historic_predictions, starting from scratch
2024-09-15 18:30:57,666 - freqtrade.freqai.freqai_interface - INFO - Set existing queue from trained timestamps. Best approximation queue: {best_queue}
2024-09-15 18:30:57,666 - freqtrade.strategy.hyper - INFO - No params for buy found, using default values.
2024-09-15 18:30:57,667 - freqtrade.strategy.hyper - INFO - No params for sell found, using default values.
2024-09-15 18:30:57,667 - freqtrade.strategy.hyper - INFO - No params for protection found, using default values.
2024-09-15 18:30:57,670 - freqtrade.freqai.freqai_interface - INFO - Training 30 timeranges
2024-09-15 18:30:57,671 - freqtrade.freqai.freqai_interface - INFO - Training BTC/USDT:USDT, 1/6 pairs from 2023-12-02 00:00:00 to 2024-01-01 00:00:00, 1/30 trains
2024-09-15 18:30:57,673 - freqtrade.freqai.data_kitchen - INFO - Found backtesting prediction file at /home/bryantsuen/workspace/Finance/freqtrade/user_data/models/freqai_pivot/backtesting_predictions/cb_btc_1704067200_prediction.feather
2024-09-15 18:30:57,705 - freqtrade.data.dataprovider - INFO - Increasing startup_candle_count for freqai on 1d to 110
2024-09-15 18:30:57,705 - freqtrade.data.dataprovider - INFO - Loading data for BTC/USDT:USDT 1d from 2023-09-13 00:00:00 to 2024-07-24 00:00:00
2024-09-15 18:30:57,754 - freqtrade.freqai.freqai_interface - INFO - Training BTC/USDT:USDT, 1/6 pairs from 2023-12-09 00:00:00 to 2024-01-08 00:00:00, 2/30 trains
2024-09-15 18:30:57,755 - freqtrade.freqai.data_kitchen - INFO - Found backtesting prediction file at /home/bryantsuen/workspace/Finance/freqtrade/user_data/models/freqai_pivot/backtesting_predictions/cb_btc_1704672000_prediction.feather
2024-09-15 18:30:57,759 - freqtrade.freqai.freqai_interface - INFO - Training BTC/USDT:USDT, 1/6 pairs from 2023-12-16 00:00:00 to 2024-01-15 00:00:00, 3/30 trains
2024-09-15 18:30:57,761 - freqtrade.freqai.data_kitchen - INFO - Found backtesting prediction file at /home/bryantsuen/workspace/Finance/freqtrade/user_data/models/freqai_pivot/backtesting_predictions/cb_btc_1705276800_prediction.feather
2024-09-15 18:30:57,764 - freqtrade.freqai.freqai_interface - INFO - Training BTC/USDT:USDT, 1/6 pairs from 2023-12-23 00:00:00 to 2024-01-22 00:00:00, 4/30 trains
2024-09-15 18:30:57,765 - freqtrade.freqai.data_kitchen - INFO - Found backtesting prediction file at /home/bryantsuen/workspace/Finance/freqtrade/user_data/models/freqai_pivot/backtesting_predictions/cb_btc_1705881600_prediction.feather
2024-09-15 18:30:57,768 - freqtrade.freqai.freqai_interface - INFO - Training BTC/USDT:USDT, 1/6 pairs from 2023-12-30 00:00:00 to 2024-01-29 00:00:00, 5/30 trains
2024-09-15 18:30:57,770 - freqtrade.freqai.data_kitchen - INFO - Found backtesting prediction file at /home/bryantsuen/workspace/Finance/freqtrade/user_data/models/freqai_pivot/backtesting_predictions/cb_btc_1706486400_prediction.feather
2024-09-15 18:30:57,773 - freqtrade.freqai.freqai_interface - INFO - Training BTC/USDT:USDT, 1/6 pairs from 2024-01-06 00:00:00 to 2024-02-05 00:00:00, 6/30 trains
2024-09-15 18:30:57,775 - freqtrade.freqai.data_kitchen - INFO - Found backtesting prediction file at /home/bryantsuen/workspace/Finance/freqtrade/user_data/models/freqai_pivot/backtesting_predictions/cb_btc_1707091200_prediction.feather
2024-09-15 18:30:57,777 - freqtrade.freqai.freqai_interface - INFO - Training BTC/USDT:USDT, 1/6 pairs from 2024-01-13 00:00:00 to 2024-02-12 00:00:00, 7/30 trains
2024-09-15 18:30:57,777 - freqtrade.freqai.data_kitchen - INFO - Could not find backtesting prediction file at /home/bryantsuen/workspace/Finance/freqtrade/user_data/models/freqai_pivot/backtesting_predictions/cb_btc_1707696000_prediction.feather
2024-09-15 18:30:57,846 - freqtrade.freqai.freqai_interface - INFO - Found model at /home/bryantsuen/workspace/Finance/freqtrade/user_data/models/freqai_pivot/sub-train-BTC_1707696000/cb_btc_1707696000
2024-09-15 18:30:57,968 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/bryantsuen/workspace/Finance/freqtrade/freqtrade/main.py", line 45, in main
    return_code = args["func"](args)
  File "/home/bryantsuen/workspace/Finance/freqtrade/freqtrade/commands/optimize_commands.py", line 60, in start_backtesting
    backtesting.start()
  File "/home/bryantsuen/workspace/Finance/freqtrade/freqtrade/optimize/backtesting.py", line 1623, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
  File "/home/bryantsuen/workspace/Finance/freqtrade/freqtrade/optimize/backtesting.py", line 1530, in backtest_one_strategy
    preprocessed = self.strategy.advise_all_indicators(data)
  File "/home/bryantsuen/workspace/Finance/freqtrade/freqtrade/strategy/interface.py", line 1586, in advise_all_indicators
    return {
  File "/home/bryantsuen/workspace/Finance/freqtrade/freqtrade/strategy/interface.py", line 1587, in <dictcomp>
    pair: self.advise_indicators(pair_data.copy(), {"pair": pair}).copy()
  File "/home/bryantsuen/workspace/Finance/freqtrade/freqtrade/strategy/interface.py", line 1645, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/home/bryantsuen/workspace/Finance/freqtrade/user_data/strategies/FreqaiPivot.py", line 115, in populate_indicators
    dataframe = self.freqai.start(dataframe, metadata, self)
  File "/home/bryantsuen/workspace/Finance/freqtrade/freqtrade/freqai/freqai_interface.py", line 161, in start
    dk = self.start_backtesting(dataframe, metadata, self.dk, strategy)
  File "/home/bryantsuen/workspace/Finance/freqtrade/freqtrade/freqai/freqai_interface.py", line 383, in start_backtesting
    append_df = dk.get_predictions_to_append(pred_df, do_preds, dataframe_backtest)
  File "/home/bryantsuen/workspace/Finance/freqtrade/freqtrade/freqai/data_kitchen.py", line 444, in get_predictions_to_append
    append_df["do_predict"] = do_predict
  File "/home/bryantsuen/anaconda3/envs/freqtrade/lib/python3.10/site-packages/pandas/core/frame.py", line 4311, in __setitem__
    self._set_item(key, value)
  File "/home/bryantsuen/anaconda3/envs/freqtrade/lib/python3.10/site-packages/pandas/core/frame.py", line 4524, in _set_item
    value, refs = self._sanitize_column(value)
  File "/home/bryantsuen/anaconda3/envs/freqtrade/lib/python3.10/site-packages/pandas/core/frame.py", line 5266, in _sanitize_column
    com.require_length_match(value, self.index)
  File "/home/bryantsuen/anaconda3/envs/freqtrade/lib/python3.10/site-packages/pandas/core/common.py", line 573, in require_length_match
    raise ValueError(
ValueError: Length of values (168) does not match length of index (336)
  ```

**Comment by xmatthias** [comment]
Be VERY careful with naming - first off, i'd suggest to change the naming of the class go `XGBoostClassifier`. It's technically a naming colision with the builtin model.

while logs suggest it loads the class from the correct place (user_data/freqaimodels) - that's not guaranteed to happen in all circumstances (e.g. in editor completion samples) , so i think  a renamed model name would help a ton to avoid confusion.

**Comment by b2r66sun** [comment]
> Be VERY careful with naming - first off, i'd suggest to change the naming of the class go `XGBoostClassifier`. It's technically a naming colision with the builtin model.
> 
> while logs suggest it loads the class from the correct place (user_data/freqaimodels) - that's not guaranteed to happen in all circumstances (e.g. in editor completion samples) , so i think a renamed model name would help a ton to avoid confusion.

Thanks xmatthias, I renamed the classifier to avoid confliction and tried again, but the problem still remains.

**Comment by b2r66sun** [comment]
> > Be VERY careful with naming - first off, i'd suggest to change the naming of the class go `XGBoostClassifier`. It's technically a naming colision with the builtin model.
> > while logs suggest it loads the class from the correct place (user_data/freqaimodels) - that's not guaranteed to happen in all circumstances (e.g. in editor completion samples) , so i think a renamed model name would help a ton to avoid confusion.
> 
> Thanks xmatthias, I renamed the classifier to avoid confliction and tried again, but the problem still remains.

I think I found why after debugging. The XGBoostClassifier define the n_classes_ property according to the input data in fit function, which is different from pytorch model that predefine the classifier before constructing the computation graph. It happens to be no label other than 'hold' in the update, and the error occurs. Closing this issue.
