### ISSUE TITLE
Freqtrade process crashes

### ISSUE THREAD

**Issue by vecktor** [freqtrade/freqtrade#10702]
## Describe your environment

  * Operating system: Amazon Linux AMI
  * Python Version: 3.9.16
  * CCXT version: 4.3.88
  * Freqtrade Version: 2024.8
  
## Describe the problem:

After running for a few hours service crashed.

### Steps to reproduce:

It's unclear how to reproduce the problem as it happened occasionally.
  
### Observed Results:

  * Freqtrade process died
  * Freqtrade process keeps runing

### Relevant code exceptions or logs

```
Sep 23 23:46:36 ip-172-31-23-170.ap-northeast-1.compute.internal systemd[99915]: Stopping freqtrade.service - Freqtrade Trader1 Dry Run...
Sep 23 23:46:36 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]: 2024-09-23 23:46:36,977 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
Sep 23 23:46:36 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]: 2024-09-23 23:46:36,978 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
Sep 23 23:46:36 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]: 2024-09-23 23:46:36,981 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
Sep 23 23:46:36 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]: 2024-09-23 23:46:36,983 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
Sep 23 23:46:36 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]: 2024-09-23 23:46:36,984 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.apiserver ...
Sep 23 23:46:36 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]: 2024-09-23 23:46:36,984 - freqtrade.rpc.api_server.webserver - INFO - Stopping API Server
Sep 23 23:46:37 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]: 2024-09-23 23:46:37,084 - uvicorn.error - INFO - Shutting down
Sep 23 23:46:37 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]: 2024-09-23 23:46:37,184 - uvicorn.error - INFO - Waiting for application shutdown.
Sep 23 23:46:37 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]: 2024-09-23 23:46:37,185 - uvicorn.error - INFO - Application shutdown complete.
Sep 23 23:46:37 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]: 2024-09-23 23:46:37,185 - uvicorn.error - INFO - Finished server process [120510]
Sep 23 23:46:37 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]: 2024-09-23 23:46:37,185 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.telegram ...
Sep 23 23:46:37 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]: 2024-09-23 23:46:37,870 - telegram.ext.Application - INFO - Application is stopping. This might take a moment.
Sep 23 23:46:37 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]: 2024-09-23 23:46:37,870 - telegram.ext.Application - INFO - Application.stop() complete
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]: 2024-09-23 23:46:38,362 - freqtrade - INFO - SIGINT received, aborting ...
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]: Exception ignored in: <function Exchange.__del__ at 0xffff8b1bfee0>
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]: Traceback (most recent call last):
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]:   File "/home/ec2-user/freqtrade/freqtrade/exchange/exchange.py", line 297, in __del__
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]:     self.close()
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]:   File "/home/ec2-user/freqtrade/freqtrade/exchange/exchange.py", line 309, in close
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]:     self.loop.run_until_complete(self._api_async.close())
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]:   File "/usr/lib64/python3.9/asyncio/base_events.py", line 622, in run_until_complete
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]:     self._check_closed()
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]:   File "/usr/lib64/python3.9/asyncio/base_events.py", line 515, in _check_closed
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]:     raise RuntimeError('Event loop is closed')
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]: RuntimeError: Event loop is closed
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]: 2024-09-23 23:46:38,576 - ccxt.base.exchange - WARNING - kucoin requires to release all resources with an explicit call to the .close() coroutine. If you are using the exchange instance with async coroutines, add `await exchange.close()` to your code into a place when you're done with the exchange and don't need the exchange instance anymore (at the end of your async coroutine).
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]: 2024-09-23 23:46:38,578 - asyncio - ERROR - Task was destroyed but it is pending!
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]: task: <Task pending name='Task-176263' coro=<Throttler.looper() done, defined at /home/ec2-user/freqtrade/.venv/lib64/python3.9/site-packages/ccxt/async_support/base/throttler.py:21> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xffff76894310>()]>>
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]: 2024-09-23 23:46:38,579 - asyncio - ERROR - Future exception was never retrieved
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]: future: <Future finished exception=ClientOSError(1, '[SSL: APPLICATION_DATA_AFTER_CLOSE_NOTIFY] application data after close notify (_ssl.c:2770)')>
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]: Traceback (most recent call last):
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]:   File "/home/ec2-user/freqtrade/freqtrade/main.py", line 45, in main
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]:     return_code = args["func"](args)
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]:   File "/home/ec2-user/freqtrade/freqtrade/commands/trade_commands.py", line 25, in start_trading
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]:     worker.run()
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]:   File "/home/ec2-user/freqtrade/freqtrade/worker.py", line 78, in run
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]:     state = self._worker(old_state=state)
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]:   File "/home/ec2-user/freqtrade/freqtrade/worker.py", line 119, in _worker
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]:     self._throttle(
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]:   File "/home/ec2-user/freqtrade/freqtrade/worker.py", line 160, in _throttle
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]:     result = func(*args, **kwargs)
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]:   File "/home/ec2-user/freqtrade/freqtrade/worker.py", line 194, in _process_running
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]:     self.freqtrade.process()
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]:   File "/home/ec2-user/freqtrade/freqtrade/freqtradebot.py", line 262, in process
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]:     self.dataprovider.refresh(
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]:   File "/home/ec2-user/freqtrade/freqtrade/data/dataprovider.py", line 449, in refresh
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]:     self._exchange.refresh_latest_ohlcv(final_pairs)
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]:   File "/home/ec2-user/freqtrade/freqtrade/exchange/exchange.py", line 2515, in refresh_latest_ohlcv
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]:     results = self.loop.run_until_complete(gather_coroutines(dl_jobs_batch))
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]:   File "/usr/lib64/python3.9/asyncio/base_events.py", line 634, in run_until_complete
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]:     self.run_forever()
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]:   File "/usr/lib64/python3.9/asyncio/base_events.py", line 601, in run_forever
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]:     self._run_once()
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]:   File "/usr/lib64/python3.9/asyncio/base_events.py", line 1869, in _run_once
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]:     event_list = self._selector.select(timeout)
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]:   File "/usr/lib64/python3.9/selectors.py", line 469, in select
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]:     fd_event_list = self._selector.poll(timeout, max_ev)
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]:   File "/home/ec2-user/freqtrade/freqtrade/commands/trade_commands.py", line 18, in term_handler
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]:     raise KeyboardInterrupt()
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]: KeyboardInterrupt
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]: During handling of the above exception, another exception occurred:
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]: Traceback (most recent call last):
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]:   File "/usr/lib64/python3.9/asyncio/sslproto.py", line 534, in data_received
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]:     ssldata, appdata = self._sslpipe.feed_ssldata(data)
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]:   File "/usr/lib64/python3.9/asyncio/sslproto.py", line 206, in feed_ssldata
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]:     self._sslobj.unwrap()
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]:   File "/usr/lib64/python3.9/ssl.py", line 949, in unwrap
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]:     return self._sslobj.shutdown()
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]: ssl.SSLError: [SSL: APPLICATION_DATA_AFTER_CLOSE_NOTIFY] application data after close notify (_ssl.c:2770)
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]: The above exception was the direct cause of the following exception:
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]: aiohttp.client_exceptions.ClientOSError: [Errno 1] [SSL: APPLICATION_DATA_AFTER_CLOSE_NOTIFY] application data after close notify (_ssl.c:2770)
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]: 2024-09-23 23:46:38,582 - asyncio - ERROR - Unclosed client session
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]: client_session: <aiohttp.client.ClientSession object at 0xffff8a0d1c40>
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]: 2024-09-23 23:46:38,582 - asyncio - ERROR - Task was destroyed but it is pending!
Sep 23 23:46:38 ip-172-31-23-170.ap-northeast-1.compute.internal freqtrade[120510]: task: <Task pending name='Task-176288' coro=<TCPConnector._resolve_host_with_throttle() running at /home/ec2-user/freqtrade/.venv/lib64/python3.9/site-packages/aiohttp/connector.py:921> cb=[shield.<locals>._inner_done_callback() at /usr/lib64/python3.9/asyncio/tasks.py:890]>
Sep 23 23:46:39 ip-172-31-23-170.ap-northeast-1.compute.internal systemd[99915]: Stopped freqtrade.service - Freqtrade Trader1 Dry Run.
Sep 23 23:46:39 ip-172-31-23-170.ap-northeast-1.compute.internal systemd[99915]: freqtrade.service: Consumed 1h 24min 49.123s CPU time.
```

**Comment by vecktor** [comment]
I just figured out, that I didn't enable linger for the user so I believe this is the cause of the problem. Closing the issue.
