### ISSUE TITLE
Telegram suffer from respons problem, how can i do to fix it?

### ISSUE THREAD

**Issue by liyunlongaaa** [freqtrade/freqtrade#10755]
```
(freqtrade) yoos@yoos-System-Product-Name:~/Documents/code/freqtrade$ freqtrade trade --config user_data/config2.json --strategy SampleStrategy
2024-10-05 17:38:26,296 - freqtrade - INFO - freqtrade 2024.9
2024-10-05 17:38:26,467 - freqtrade.worker - INFO - Starting worker 2024.9
2024-10-05 17:38:26,467 - freqtrade.configuration.load_config - INFO - Using config: user_data/config2.json ...
2024-10-05 17:38:26,467 - freqtrade.loggers - INFO - Verbosity set to 0
2024-10-05 17:38:26,467 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
2024-10-05 17:38:26,467 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2024-10-05 17:38:26,467 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:///tradesv3.dryrun.sqlite"
2024-10-05 17:38:26,468 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 10 ...
2024-10-05 17:38:26,468 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/yoos/Documents/code/freqtrade/user_data ...
2024-10-05 17:38:26,468 - freqtrade.configuration.configuration - INFO - Using data directory: /home/yoos/Documents/code/freqtrade/user_data/data/htx ...
2024-10-05 17:38:26,468 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2024-10-05 17:38:26,471 - freqtrade.exchange.check_exchange - INFO - Exchange "htx" is officially supported by the Freqtrade development team.
2024-10-05 17:38:26,471 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2024-10-05 17:38:26,475 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy SampleStrategy from '/home/yoos/Documents/code/freqtrade/user_data/strategies/sample_strategy.py'...
2024-10-05 17:38:26,475 - freqtrade.strategy.hyper - INFO - Found no parameter file.
2024-10-05 17:38:26,475 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2024-10-05 17:38:26,475 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: unlimited.
2024-10-05 17:38:26,475 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}.
2024-10-05 17:38:26,475 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'max_open_trades' with value in config file: 10.
2024-10-05 17:38:26,475 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'60': 0.01, '30': 0.02, '0': 0.04}
2024-10-05 17:38:26,475 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 5m
2024-10-05 17:38:26,475 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.1
2024-10-05 17:38:26,475 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2024-10-05 17:38:26,475 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2024-10-05 17:38:26,475 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2024-10-05 17:38:26,475 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2024-10-05 17:38:26,475 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: True
2024-10-05 17:38:26,475 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'entry': 'limit', 'exit': 'limit', 'stoploss': 'market', 'stoploss_on_exchange': False}
2024-10-05 17:38:26,475 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'entry': 'GTC', 'exit': 'GTC'}
2024-10-05 17:38:26,475 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2024-10-05 17:38:26,475 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: unlimited
2024-10-05 17:38:26,475 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2024-10-05 17:38:26,475 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 200
2024-10-05 17:38:26,475 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}
2024-10-05 17:38:26,475 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_exit_signal: True
2024-10-05 17:38:26,475 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_only: False
2024-10-05 17:38:26,475 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_entry_signal: False
2024-10-05 17:38:26,475 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_offset: 0.0
2024-10-05 17:38:26,475 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2024-10-05 17:38:26,475 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2024-10-05 17:38:26,475 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: False
2024-10-05 17:38:26,475 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1
2024-10-05 17:38:26,475 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_open_trades: 10
2024-10-05 17:38:26,475 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2024-10-05 17:38:26,476 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2024-10-05 17:38:26,476 - freqtrade.exchange.exchange - INFO - Using CCXT 4.4.6
2024-10-05 17:38:26,476 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'httpsProxy': 'http://127.0.0.1:7897'}
2024-10-05 17:38:26,479 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'httpsProxy': 'http://127.0.0.1:7897'}
2024-10-05 17:38:26,483 - freqtrade.exchange.exchange - INFO - Using Exchange "HTX"
2024-10-05 17:38:28,059 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Htx'...
2024-10-05 17:38:28,073 - freqtrade.wallets - INFO - Wallets synced.
2024-10-05 17:38:28,723 - freqtrade.rpc.rpc_manager - INFO - Enabling rpc.telegram ...
2024-10-05 17:38:28,776 - freqtrade.rpc.rpc_manager - INFO - Enabling rpc.api_server
Exception in thread FTTelegram:
Traceback (most recent call last):
  File "/home/yoos/miniconda3/envs/freqtrade/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/home/yoos/miniconda3/envs/freqtrade/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yoos/Documents/code/freqtrade/freqtrade/rpc/telegram.py", line 240, in _init
    self._app = self._init_telegram_app()
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yoos/Documents/code/freqtrade/freqtrade/rpc/telegram.py", line 225, in _init_telegram_app
    return Application.builder().token(self._config["telegram"]["token"]).build()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yoos/miniconda3/envs/freqtrade/lib/python3.11/site-packages/telegram/ext/_applicationbuilder.py", line 310, in build
    bot: Bot = self._build_ext_bot()  # build a bot
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/yoos/miniconda3/envs/freqtrade/lib/python3.11/site-packages/telegram/ext/_applicationbuilder.py", line 280, in _build_ext_bot
    request=self._build_request(get_updates=False),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yoos/miniconda3/envs/freqtrade/lib/python3.11/site-packages/telegram/ext/_applicationbuilder.py", line 260, in _build_request
    return HTTPXRequest(
           ^^^^^^^^^^^^^
  File "/home/yoos/miniconda3/envs/freqtrade/lib/python3.11/site-packages/telegram/request/_httpxrequest.py", line 205, in __init__
    self._client = self._build_client()
                   ^^^^^^^^^^^^^^^^^^^^
  File "/home/yoos/miniconda3/envs/freqtrade/lib/python3.11/site-packages/telegram/request/_httpxrequest.py", line 240, in _build_client
    return httpx.AsyncClient(**self._client_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yoos/miniconda3/envs/freqtrade/lib/python3.11/site-packages/httpx/_client.py", line 1440, in __init__
    proxy_map = self._get_proxy_map(proxies or proxy, allow_env_proxies)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yoos/miniconda3/envs/freqtrade/lib/python3.11/site-packages/httpx/_client.py", line 218, in _get_proxy_map
    return {
           ^
  File "/home/yoos/miniconda3/envs/freqtrade/lib/python3.11/site-packages/httpx/_client.py", line 219, in <dictcomp>
    key: None if url is None else Proxy(url=url)
                                  ^^^^^^^^^^^^^^
  File "/home/yoos/miniconda3/envs/freqtrade/lib/python3.11/site-packages/httpx/_config.py", line 338, in __init__
    raise ValueError(f"Unknown scheme for proxy URL {url!r}")
ValueError: Unknown scheme for proxy URL URL('socks://127.0.0.1:7897/')
2024-10-05 17:38:28,881 - freqtrade.rpc.api_server.webserver - INFO - Starting HTTP Server at 127.0.0.1:8088
2024-10-05 17:38:28,881 - freqtrade.rpc.api_server.webserver - INFO - Starting Local Rest Server.
2024-10-05 17:38:28,883 - uvicorn.error - INFO - Started server process [117251]
2024-10-05 17:38:28,883 - uvicorn.error - INFO - Waiting for application startup.
2024-10-05 17:38:28,883 - uvicorn.error - INFO - Application startup complete.
2024-10-05 17:38:28,883 - uvicorn.error - INFO - Uvicorn running on http://127.0.0.1:8088 (Press CTRL+C to quit)
2024-10-05 17:38:28,884 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist VolumePairList from '/home/yoos/Documents/code/freqtrade/freqtrade/plugins/pairlist/VolumePairList.py'...
2024-10-05 17:38:29,382 - freqtrade.plugins.pairlistmanager - INFO - Whitelist with 20 pairs: ['BTC/USDT', 'ETH/USDT', 'DOGE/USDT', 'HTX/USDT', 'EIGEN/USDT', 'SUNDOG/USDT', 'MOODENG/USDT', 'BOME/USDT', 'POPCAT/USDT', 'BRETT/USDT', 'TON/USDT', 'ADA/USDT', 'SUI/USDT', 'WIF/USDT', 'ETHFI/USDT', 'BNB/USDT', 'CORE/USDT', 'XRP/USDT', 'AVAX/USDT', 'LINK/USDT']
2024-10-05 17:38:29,382 - freqtrade.strategy.hyper - INFO - No params for buy found, using default values.
2024-10-05 17:38:29,383 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): buy_rsi = 30
2024-10-05 17:38:29,383 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): exit_short_rsi = 30
2024-10-05 17:38:29,383 - freqtrade.strategy.hyper - INFO - No params for sell found, using default values.
2024-10-05 17:38:29,383 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): sell_rsi = 70
2024-10-05 17:38:29,383 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): short_rsi = 70
2024-10-05 17:38:29,383 - freqtrade.strategy.hyper - INFO - No params for protection found, using default values.
2024-10-05 17:38:29,383 - freqtrade.plugins.protectionmanager - INFO - No protection Handlers defined.
2024-10-05 17:38:29,383 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'running'}
2024-10-05 17:38:29,383 - freqtrade.worker - INFO - Changing state to: RUNNING
2024-10-05 17:38:29,395 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': warning, 'status': 'Dry run is enabled. All trades are simulated.'}
2024-10-05 17:38:29,395 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': "*Exchange:* `htx`\n*Stake per trade:* `unlimited USDT`\n*Minimum ROI:* `{'60': 0.01, '30': 0.02, '0': 0.04}`\n*Stoploss:* `-0.1`\n*Position adjustment:* `Off`\n*Timeframe:* `5m`\n*Strategy:* `SampleStrategy`"}
2024-10-05 17:38:29,395 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': "Searching for USDT pairs to buy and sell based on [{'VolumePairList': 'VolumePairList - top 20 volume pairs.'}]"}
2024-10-05 17:38:34,396 - freqtrade.worker - INFO - Bot heartbeat. PID=117251, version='2024.9', state='RUNNING'
2024-10-05 17:39:34,397 - freqtrade.worker - INFO - Bot heartbeat. PID=117251, version='2024.9', state='RUNNING'
2024-10-05 17:40:36,000 - freqtrade.worker - INFO - Bot heartbeat. PID=117251, version='2024.9', state='RUNNING'
2024-10-05 17:41:36,002 - freqtrade.worker - INFO - Bot heartbeat. PID=117251, version='2024.9', state='RUNNING'
2024-10-05 17:42:36,003 - freqtrade.worker - INFO - Bot heartbeat. PID=117251, version='2024.9', state='RUNNING'
2024-10-05 17:43:36,004 - freqtrade.worker - INFO - Bot heartbeat. PID=117251, version='2024.9', state='RUNNING'

```

**Comment by liyunlongaaa** [comment]
I noticed that
```
File "/home/yoos/miniconda3/envs/freqtrade/lib/python3.11/site-packages/httpx/_config.py", line 338, in init
raise ValueError(f"Unknown scheme for proxy URL {url!r}")
ValueError: Unknown scheme for proxy URL URL('socks://127.0.0.1:7897/')
```
why this code choose socks proxy ? my proxy addr is http://127.0.0.1:7897/, it maybe problem, but i don't how to fix it

**Comment by xmatthias** [comment]
well there's no "automatic" proxy selection - it'll most likely come from some environment variable you've set (wrongly).

Most likely, one of the [proxy](https://www.python-httpx.org/environment_variables/#proxies) variables - as documented in the httpx file.

**Comment by liyunlongaaa** [comment]
Thank you for your reply, my env variavle is 
```
(base) yoos@yoos-System-Product-Name:~$ echo $HTTP_PROXY
http://127.0.0.1:7897/
(base) yoos@yoos-System-Product-Name:~$ echo $HTTPS_PROXY
http://127.0.0.1:7897/
(base) yoos@yoos-System-Product-Name:~$ echo $ALL_PROXY
socks://127.0.0.1:7897/
```
it seems right ?  I am not sure....

**Comment by xmatthias** [comment]
well - seems like httpx favors your ALL_PROXY variable - which corresponds to what the logs show.

it seems alright in theory - but in practice it's not, as the same IP won't be a http proxy, and a socks proxy at the same time.
set that to http - or unset it and it should work.

**Comment by liyunlongaaa** [comment]
thank you i have fix it, by add code to replace 'socks' to 'http' ....
in 
/home/yoos/miniconda3/envs/freqtrade/lib/python3.11/site-packages/httpx/_utils.py
```
def get_environment_proxies() -> dict[str, str | None]:
    """Gets proxy information from the environment"""

    # urllib.request.getproxies() falls back on System
    # Registry and Config for proxies on Windows and macOS.
    # We don't want to propagate non-HTTP proxies into
    # our configuration such as 'TRAVIS_APT_PROXY'.
    proxy_info = getproxies()
    mounts: dict[str, str | None] = {}
    proxy_info["all"] = proxy_info["all"] .replace('socks', 'http')  #hack code
    ......
```
`proxy_info["all"] = proxy_info["all"] .replace('socks', 'http')  #hack code`

it maybe ugly but help...

**Comment by liyunlongaaa** [comment]
This problm is caused by clash verge, which revises environmental variable by
`export https_proxy=http://127.0.0.1:7897 http_proxy=http://127.0.0.1:7897 all_proxy=socks5://127.0.0.1:7897`
so my PC has two variable ALL_PROXY and all_proxy, if you only revise ALL_PROXY, it doesn't work.......
