### ISSUE TITLE
ERR_EMPTY_RESPONSE, failed to access freqUI on windows docker desktop

### ISSUE THREAD

**Issue by ZhenZinian** [freqtrade/freqtrade#10774]
## Describe your environment

  * Operating system: __win10   20H2
  * Python Version: ___3.9.12
  * CCXT version: _Not installed (using docker desktop 4.16.3)
  * Freqtrade Version: ____2024.9
  
## Your question

I can't seem to access the freqUI after following the steps for docker with windows. In the screenshots and logs below.

got  ERR_EMPTY_RESPONSE  when I tried to access 127.0.0.1:8080 on edge.

Curl:
`C:\Users\user>curl -vvv 127.0.0.1:8080
* Rebuilt URL to: 127.0.0.1:8080/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.55.1
> Accept: */*
>
* Empty reply from server
* Connection #0 to host 127.0.0.1 left intact
curl: (52) Empty reply from server
`

logs:
```
2024-10-08 08:39:58,766 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'max_open_trades' with value in config file: 99.
2024-10-08 08:39:58,767 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'60': 0.01, '30': 0.02, '0': 0.04}
2024-10-08 08:39:58,767 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 5m
2024-10-08 08:39:58,768 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.1
2024-10-08 08:39:58,768 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2024-10-08 08:39:58,769 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2024-10-08 08:39:58,770 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2024-10-08 08:39:58,770 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2024-10-08 08:39:58,771 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: True
2024-10-08 08:39:58,772 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'entry': 'limit', 'exit': 'limit', 'stoploss': 'market', 'stoploss_on_exchange': False}
2024-10-08 08:39:58,772 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'entry': 'GTC', 'exit': 'GTC'}
2024-10-08 08:39:58,773 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2024-10-08 08:39:58,773 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 10000
2024-10-08 08:39:58,774 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2024-10-08 08:39:58,774 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 200
2024-10-08 08:39:58,775 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}
2024-10-08 08:39:58,775 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_exit_signal: True
2024-10-08 08:39:58,776 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_only: False
2024-10-08 08:39:58,777 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_entry_signal: False
2024-10-08 08:39:58,778 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_offset: 0.0
2024-10-08 08:39:58,779 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2024-10-08 08:39:58,779 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2024-10-08 08:39:58,780 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: False
2024-10-08 08:39:58,780 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1
2024-10-08 08:39:58,781 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_open_trades: 99
2024-10-08 08:39:58,782 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2024-10-08 08:39:58,788 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2024-10-08 08:39:58,789 - freqtrade.exchange.exchange - INFO - Using CCXT 4.4.6
2024-10-08 08:39:58,822 - freqtrade.exchange.exchange - INFO - Using Exchange "KuCoin"
2024-10-08 08:40:05,236 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 45, in main
    return_code = args["func"](args)
                  ^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 24, in start_trading
    worker = Worker(args)
             ^^^^^^^^^^^^
  File "/freqtrade/freqtrade/worker.py", line 38, in __init__
    self._init(False)
  File "/freqtrade/freqtrade/worker.py", line 54, in _init
    self.freqtrade = FreqtradeBot(self._config)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/freqtradebot.py", line 101, in __init__
    self.exchange = ExchangeResolver.load_exchange(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 44, in load_exchange
    exchange = ExchangeResolver._load_exchange(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 77, in _load_exchange
    exchange = ex_class(**kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/exchange/exchange.py", line 278, in __init__
    self.reload_markets(True, load_leverage_tiers=False)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 664, in reload_markets
    self._markets = retrier(self._load_async_markets, retries=retries)(reload=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/exchange/common.py", line 181, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/exchange/exchange.py", line 637, in _load_async_markets
    markets = self.loop.run_until_complete(self._api_reload_markets(reload=reload))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/exchange/exchange.py", line 625, in _api_reload_markets
    return await self._api_async.load_markets(reload=reload, params={})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/async_support/base/exchange.py", line 287, in load_markets
    raise e
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/async_support/base/exchange.py", line 283, in load_markets
    result = await self.markets_loading
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/async_support/base/exchange.py", line 273, in load_markets_helper
    markets = await self.fetch_markets(params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/async_support/kucoin.py", line 1153, in fetch_markets
    for i in range(0, len(symbolsData)):
                      ^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
2024-10-08 08:40:13,524 - freqtrade.loggers - INFO - Verbosity set to 0
2024-10-08 08:40:13,525 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
2024-10-08 08:40:13,526 - freqtrade.configuration.configuration - INFO - Parameter --db-url detected ...
2024-10-08 08:40:13,526 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2024-10-08 08:40:13,527 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:////freqtrade/user_data/tradesv3.sqlite"
2024-10-08 08:40:13,527 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 99 ...
2024-10-08 08:40:13,589 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2024-10-08 08:40:13,591 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/kucoin ...
2024-10-08 08:40:13,592 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2024-10-08 08:40:13,603 - freqtrade.exchange.check_exchange - WARNING - Exchange "kucoin" is known to the ccxt library, available for the bot, but not officially supported by the Freqtrade development team. It may work flawlessly (please report back) or have serious issues. Use it at your own discretion.
2024-10-08 08:40:13,604 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2024-10-08 08:40:13,653 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy SampleStrategy from '/freqtrade/user_data/strategies/sample_strategy.py'...
2024-10-08 08:40:13,655 - freqtrade.strategy.hyper - INFO - Found no parameter file.
2024-10-08 08:40:13,656 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2024-10-08 08:40:13,657 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 10000.
2024-10-08 08:40:13,657 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}.
2024-10-08 08:40:13,658 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'max_open_trades' with value in config file: 99.
2024-10-08 08:40:13,658 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'60': 0.01, '30': 0.02, '0': 0.04}
2024-10-08 08:40:13,659 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 5m
2024-10-08 08:40:13,659 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.1
2024-10-08 08:40:13,659 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2024-10-08 08:40:13,660 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2024-10-08 08:40:13,660 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2024-10-08 08:40:13,661 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2024-10-08 08:40:13,661 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: True
2024-10-08 08:40:13,661 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'entry': 'limit', 'exit': 'limit', 'stoploss': 'market', 'stoploss_on_exchange': False}
2024-10-08 08:40:13,662 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'entry': 'GTC', 'exit': 'GTC'}
2024-10-08 08:40:13,662 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2024-10-08 08:40:13,663 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 10000
2024-10-08 08:40:13,663 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2024-10-08 08:40:13,664 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 200
2024-10-08 08:40:13,664 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}
2024-10-08 08:40:13,664 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_exit_signal: True
2024-10-08 08:40:13,665 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_only: False
2024-10-08 08:40:13,665 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_entry_signal: False
2024-10-08 08:40:13,666 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_offset: 0.0
2024-10-08 08:40:13,666 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2024-10-08 08:40:13,667 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2024-10-08 08:40:13,667 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: False
2024-10-08 08:40:13,668 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1
2024-10-08 08:40:13,668 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_open_trades: 99
2024-10-08 08:40:13,669 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2024-10-08 08:40:13,675 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2024-10-08 08:40:13,675 - freqtrade.exchange.exchange - INFO - Using CCXT 4.4.6
2024-10-08 08:40:13,699 - freqtrade.exchange.exchange - INFO - Using Exchange "KuCoin"
2024-10-08 08:40:20,022 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 45, in main
    return_code = args["func"](args)
                  ^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 24, in start_trading
    worker = Worker(args)
             ^^^^^^^^^^^^
  File "/freqtrade/freqtrade/worker.py", line 38, in __init__
    self._init(False)
  File "/freqtrade/freqtrade/worker.py", line 54, in _init
    self.freqtrade = FreqtradeBot(self._config)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/freqtradebot.py", line 101, in __init__
    self.exchange = ExchangeResolver.load_exchange(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 44, in load_exchange
    exchange = ExchangeResolver._load_exchange(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 77, in _load_exchange
    exchange = ex_class(**kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/exchange/exchange.py", line 278, in __init__
    self.reload_markets(True, load_leverage_tiers=False)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 664, in reload_markets
    self._markets = retrier(self._load_async_markets, retries=retries)(reload=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/exchange/common.py", line 181, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/exchange/exchange.py", line 637, in _load_async_markets
    markets = self.loop.run_until_complete(self._api_reload_markets(reload=reload))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/exchange/exchange.py", line 625, in _api_reload_markets
    return await self._api_async.load_markets(reload=reload, params={})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/async_support/base/exchange.py", line 287, in load_markets
    raise e
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/async_support/base/exchange.py", line 283, in load_markets
    result = await self.markets_loading
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/async_support/base/exchange.py", line 273, in load_markets_helper
    markets = await self.fetch_markets(params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/async_support/kucoin.py", line 1153, in fetch_markets
    for i in range(0, len(symbolsData)):
                      ^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
2024-10-08 08:40:29,801 - freqtrade.loggers - INFO - Verbosity set to 0
2024-10-08 08:40:29,803 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
2024-10-08 08:40:29,804 - freqtrade.configuration.configuration - INFO - Parameter --db-url detected ...
2024-10-08 08:40:29,805 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2024-10-08 08:40:29,806 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:////freqtrade/user_data/tradesv3.sqlite"
2024-10-08 08:40:29,807 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 99 ...
2024-10-08 08:40:29,931 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2024-10-08 08:40:29,934 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/kucoin ...
2024-10-08 08:40:29,938 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2024-10-08 08:40:29,964 - freqtrade.exchange.check_exchange - WARNING - Exchange "kucoin" is known to the ccxt library, available for the bot, but not officially supported by the Freqtrade development team. It may work flawlessly (please report back) or have serious issues. Use it at your own discretion.
2024-10-08 08:40:29,965 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2024-10-08 08:40:30,050 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy SampleStrategy from '/freqtrade/user_data/strategies/sample_strategy.py'...
2024-10-08 08:40:30,052 - freqtrade.strategy.hyper - INFO - Found no parameter file.
2024-10-08 08:40:30,054 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2024-10-08 08:40:30,055 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 10000.
2024-10-08 08:40:30,055 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}.
2024-10-08 08:40:30,056 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'max_open_trades' with value in config file: 99.
2024-10-08 08:40:30,057 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'60': 0.01, '30': 0.02, '0': 0.04}
2024-10-08 08:40:30,058 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 5m
2024-10-08 08:40:30,058 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.1
2024-10-08 08:40:30,059 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2024-10-08 08:40:30,060 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2024-10-08 08:40:30,060 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2024-10-08 08:40:30,061 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2024-10-08 08:40:30,061 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: True
2024-10-08 08:40:30,062 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'entry': 'limit', 'exit': 'limit', 'stoploss': 'market', 'stoploss_on_exchange': False}
2024-10-08 08:40:30,063 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'entry': 'GTC', 'exit': 'GTC'}
2024-10-08 08:40:30,063 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2024-10-08 08:40:30,064 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 10000
2024-10-08 08:40:30,064 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2024-10-08 08:40:30,065 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 200
2024-10-08 08:40:30,065 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}
2024-10-08 08:40:30,066 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_exit_signal: True
2024-10-08 08:40:30,067 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_only: False
2024-10-08 08:40:30,067 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_entry_signal: False
2024-10-08 08:40:30,068 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_offset: 0.0
2024-10-08 08:40:30,069 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2024-10-08 08:40:30,069 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2024-10-08 08:40:30,070 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: False
2024-10-08 08:40:30,071 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1
2024-10-08 08:40:30,071 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_open_trades: 99
2024-10-08 08:40:30,072 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2024-10-08 08:40:30,079 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2024-10-08 08:40:30,080 - freqtrade.exchange.exchange - INFO - Using CCXT 4.4.6
2024-10-08 08:40:30,113 - freqtrade.exchange.exchange - INFO - Using Exchange "KuCoin"
2024-10-08 08:40:37,294 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 45, in main
    return_code = args["func"](args)
                  ^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 24, in start_trading
    worker = Worker(args)
             ^^^^^^^^^^^^
  File "/freqtrade/freqtrade/worker.py", line 38, in __init__
    self._init(False)
  File "/freqtrade/freqtrade/worker.py", line 54, in _init
    self.freqtrade = FreqtradeBot(self._config)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/freqtradebot.py", line 101, in __init__
    self.exchange = ExchangeResolver.load_exchange(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 44, in load_exchange
    exchange = ExchangeResolver._load_exchange(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 77, in _load_exchange
    exchange = ex_class(**kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/exchange/exchange.py", line 278, in __init__
    self.reload_markets(True, load_leverage_tiers=False)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 664, in reload_markets
    self._markets = retrier(self._load_async_markets, retries=retries)(reload=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/exchange/common.py", line 181, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/exchange/exchange.py", line 637, in _load_async_markets
    markets = self.loop.run_until_complete(self._api_reload_markets(reload=reload))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/exchange/exchange.py", line 625, in _api_reload_markets
    return await self._api_async.load_markets(reload=reload, params={})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/async_support/base/exchange.py", line 287, in load_markets
    raise e
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/async_support/base/exchange.py", line 283, in load_markets
    result = await self.markets_loading
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/async_support/base/exchange.py", line 273, in load_markets_helper
    markets = await self.fetch_markets(params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/async_support/kucoin.py", line 1153, in fetch_markets
    for i in range(0, len(symbolsData)):
                      ^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
```

config:
```
{
    "$schema": "https://schema.freqtrade.io/schema.json",
    "max_open_trades": 99,
    "stake_currency": "USDT",
    "stake_amount": 10000,
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "dry_run": true,
    "dry_run_wallet": 1000,
    "cancel_open_orders_on_exit": false,
    "trading_mode": "spot",
    "margin_mode": "",
    "unfilledtimeout": {
        "entry": 10,
        "exit": 10,
        "exit_timeout_count": 0,
        "unit": "minutes"
    },
    "entry_pricing": {
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1,
        "price_last_balance": 0.0,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "exit_pricing":{
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1
    },
    "exchange": {
        "name": "kucoin",
        "key": "",
        "secret": "",
        "password": "",
        "ccxt_config": {},
        "ccxt_async_config": {},
        "pair_whitelist": [
        ],
        "pair_blacklist": [
        ]
    },
    "pairlists": [
        {
            "method": "VolumePairList",
            "number_assets": 20,
            "sort_key": "quoteVolume",
            "min_value": 0,
            "refresh_period": 1800
        }
    ],
    "telegram": {
        "enabled": true,
        "token": "",
        "chat_id": ""
    },
    "api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8080,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "xxxxxxxxxxxxxxxxxxxx",
        "ws_token": "xxxxxxxxxxxxxx",
        "CORS_origins": [],
        "username": "amd",
        "password": "123456"
    },
    "bot_name": "freqtrade",
    "initial_state": "running",
    "force_entry_enable": false,
    "internals": {
        "process_throttle_secs": 5
    }
}
```

**Comment by stash86** [comment]
Well, the log is quite clear. The bot can't fully started because it can't connect to Kucoin. It's not frequi issue.

**Comment by xmatthias** [comment]
Considering it's docker for windows - i'd suggest to simply restart the host.

On newly installed docker for windows environments, we've seen time and time again that there's no network connectivity within the container - which will fail it (independent of the exchange, really).

**Comment by ZhenZinian** [comment]
Thx! been spent whole week figuring this out.... didnt expect a single network problem can let the whole UI system down....

Given that there were many users from restricted area who need proxy accessing exchange API, network connectivity can interfere on every single step they move, it would be grateful if freqUI will show more detailed error info, so they could know what causing it at the first place.

**Comment by xmatthias** [comment]
well your issue wasn't about UI though - so the UI never actually worked, as you could never connect to it.

Now the exception itself is not very telling- but that's not a freqtrade problem - but a freqUI topic.

---

> Given that there were many users from restricted area who need proxy accessing exchange API, network connectivity can interfere on every single step they move

Well we don't aim to facilitate circumventing local regulations.
If someone uses a Proxy / VPN - then our assumption is that they know how to deal with these systems. If that's not the case - best don't use a VPN / Proxy (also because of the risk of exposure to local regulations if you misuse them and they still detect you).
