### ISSUE TITLE
freqtrade - ERROR - Exchange "delta"  will not work with Freqtrade. Reason: missing: fetchOrder. missing opt: watchOHLCV.

### ISSUE THREAD

**Issue by Joyson0** [freqtrade/freqtrade#10775]
## Describe your environment

  * Operating system: Ubuntu 22.04.5 LTS
  * Python Version: 3.10.12
  * CCXT version: 4.4.15
  * Freqtrade Version: 2024.9
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

freqtrade bot not starting with Delta Exchange configuration.

### Steps to reproduce:

  1. In ```config.json``` file put  ```"exchange": { "name": "delta" }``` to use Delta Exchange.
  3. Make sure the ```docker-compose.yml``` has the following lines:
  ```
  # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy SampleStrategy
```
  3. Start the docker compose with ```docker compose up -d```
  
### Observed Results:

  * It throws the error:
  ```freqtrade - ERROR - Exchange "delta"  will not work with Freqtrade. Reason: missing: fetchOrder. missing opt: watchOHLCV.```

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  2024-10-09 15:51:35,731 - freqtrade.loggers - INFO - Verbosity set to 0
2024-10-09 15:51:35,731 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
2024-10-09 15:51:35,731 - freqtrade.configuration.configuration - INFO - Parameter --db-url detected ...
2024-10-09 15:51:35,731 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2024-10-09 15:51:35,731 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:////freqtrade/user_data/tradesv3.sqlite"
2024-10-09 15:51:35,731 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 3 ...
2024-10-09 15:51:35,740 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2024-10-09 15:51:35,740 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/delta ...
2024-10-09 15:51:35,741 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2024-10-09 15:51:35,745 - freqtrade - ERROR - Exchange "delta"  will not work with Freqtrade. Reason: missing: fetchOrder. missing opt: watchOHLCV.
  ```

**Comment by xmatthias** [comment]
that's correct and the message explains pretty clearly what's happening.

An exchange that doesn't support fetch_order can't work on freqtrade - as it can't fetch the orders it placed.

running `freqtrade list-exchanges --all` will also show this (red exchanges will not work with freqtrade).

![image](https://github.com/user-attachments/assets/d2db739f-6530-466f-87a7-fb1d29c34075)

This can have 2 reasons - it's either because the exchange doesn't provide an endpoint for this (read the api documentation / ask support), or because ccxt either didn't implement it, or forgot to set the flag "has fetchOrder" (ask in the ccxt repository).

Freqtrade is using the information provided by ccxt to determine compatibility - and will refuse to start for exchanges where this compatibility is known to not work.


Best use one of the [supported exchanges](https://www.freqtrade.io/en/stable/#supported-exchange-marketplaces) for a good experience.

**Comment by kennylbj** [comment]
Hi, @xmatthias bybit is supported based on `list-exchanges --all`,  and why am I getting this error `bybit fetchOrder() is not supported for spot markets` when using bybit with spot order?

```
2024-10-09 21:00:01,609 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'trade_id': 1, 'type': entry, 'buy_tag': 'buy the dip', 'enter_tag': 'buy the dip', 'exchange': 'Bybit', 'pair': 'ETH/USDT', 'leverage': 1.0, 'direction': 'Long', 'limit': 2355.19, 'open_rate': 2355.19, 'order_type': 'market', 'stake_amount': 378.51388456883876, 'stake_currency': 'USDT', 'base_currency': 'ETH', 'quote_currency': 'USDT', 'fiat_currency': 'USD', 'amount': 0.0, 'open_date': datetime.datetime(2024, 10, 9, 21, 0, 1, 502542, tzinfo=datetime.timezone.utc), 'current_rate': 2355.19, 'sub_trade': False}
2024-10-09 21:00:06,042 - freqtrade.exchange.common - WARNING - fetch_order() returned exception: "Could not get order due to NotSupported. Message: bybit fetchOrder() is not supported for spot markets". Retrying still for 5 times.
2024-10-09 21:00:06,043 - freqtrade.exchange.common - WARNING - fetch_order() returned exception: "Could not get order due to NotSupported. Message: bybit fetchOrder() is not supported for spot markets". Retrying still for 4 times.
2024-10-09 21:00:06,043 - freqtrade.exchange.common - WARNING - fetch_order() returned exception: "Could not get order due to NotSupported. Message: bybit fetchOrder() is not supported for spot markets". Retrying still for 3 times.
2024-10-09 21:00:06,043 - freqtrade.exchange.common - WARNING - fetch_order() returned exception: "Could not get order due to NotSupported. Message: bybit fetchOrder() is not supported for spot markets". Retrying still for 2 times.
2024-10-09 21:00:06,043 - freqtrade.exchange.common - WARNING - fetch_order() returned exception: "Could not get order due to NotSupported. Message: bybit fetchOrder() is not supported for spot markets". Retrying still for 1 times.
2024-10-09 21:00:06,043 - freqtrade.exchange.common - WARNING - fetch_order() returned exception: "Could not get order due to NotSupported. Message: bybit fetchOrder() is not supported for spot markets". Giving up.
2024-10-09 21:00:06,057 - freqtrade.freqtradebot - INFO - Cannot query order for Trade(id=1, pair=ETH/USDT, amount=0.00000000, is_short=False, leverage=1.0, open_rate=2355.19000000, open_since=2024-10-09 21:00:01) due to Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/exchange.py", line 1504, in fetch_order
    order = self._api.fetch_order(order_id, pair, params=params)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/bybit.py", line 4546, in fetch_order
    return self.fetch_order_classic(id, symbol, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/bybit.py", line 4518, in fetch_order_classic
    raise NotSupported(self.id + ' fetchOrder() is not supported for spot markets')
ccxt.base.errors.NotSupported: bybit fetchOrder() is not supported for spot markets

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/common.py", line 181, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/exchange/exchange.py", line 1519, in fetch_order
    raise TemporaryError(
freqtrade.exceptions.TemporaryError: Could not get order due to NotSupported. Message: bybit fetchOrder() is not supported for spot markets

```

freqtrade[version='2024.9']
ccxt[4.4.6]

**Comment by xmatthias** [comment]
@kennylbj This has nothing to do with this issue (it's about delta, an exchange that is neither supported, nor has the necessary properties).

Please open a new issue for different problems (make sure to include the issue template, as well as the account type you're using (unified, non-unified, unified 2.0, subaccount unified, subaccount standard, ...).
