### ISSUE TITLE
bybit fetchOrder() is not supported for spot markets

### ISSUE THREAD

**Issue by kennylbj** [freqtrade/freqtrade#10777]
## Describe your environment

  * Operating system: _ubuntu 22.04___
  * Python Version: _use docker____ (`python -V`)
  * CCXT version: __4.4.6___ (`pip freeze | grep ccxt`)
  * Freqtrade Version: __2024.9__ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  * Account type: Bybit standard subaccount
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

Get `bybit fetchOrder() is not supported for spot markets` error when open entry order

### Steps to reproduce:

  1. __Open a trade___
  2. __Get the above error message___
  
### Observed Results:

  * What happened?
  The order did get filled but the bot keeps getting this error and the order can't be fetched by the bot___

  * What did you expect to happen?
  No error generated

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
2024-10-09 21:00:01,609 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'trade_id': 1, 'type': entry, 'buy_tag': 'buy the dip', 'enter_tag': 'buy the dip', 'exchange': 'Bybit', 'pair': 'ETH/USDT', 'leverage': 1.0, 'direction': 'Long', 'limit': 2355.19, 'open_rate': 2355.19, 'order_type': 'market', 'stake_amount': 378.51388456883876, 'stake_currency': 'USDT', 'base_currency': 'ETH', 'quote_currency': 'USDT', 'fiat_currency': 'USD', 'amount': 0.0, 'open_date': datetime.datetime(2024, 10, 9, 21, 0, 1, 502542, tzinfo=datetime.timezone.utc), 'current_rate': 2355.19, 'sub_trade': False}
2024-10-09 21:00:06,042 - freqtrade.exchange.common - WARNING - fetch_order() returned exception: "Could not get order due to NotSupported. Message: bybit fetchOrder() is not supported for spot markets". Retrying still for 5 times.
2024-10-09 21:00:06,043 - freqtrade.exchange.common - WARNING - fetch_order() returned exception: "Could not get order due to NotSupported. Message: bybit fetchOrder() is not supported for spot markets". Retrying still for 4 times.
2024-10-09 21:00:06,043 - freqtrade.exchange.common - WARNING - fetch_order() returned exception: "Could not get order due to NotSupported. Message: bybit fetchOrder() is not supported for spot markets". Retrying still for 3 times.
2024-10-09 21:00:06,043 - freqtrade.exchange.common - WARNING - fetch_order() returned exception: "Could not get order due to NotSupported. Message: bybit fetchOrder() is not supported for spot markets". Retrying still for 2 times.
2024-10-09 21:00:06,043 - freqtrade.exchange.common - WARNING - fetch_order() returned exception: "Could not get order due to NotSupported. Message: bybit fetchOrder() is not supported for spot markets". Retrying still for 1 times.
2024-10-09 21:00:06,043 - freqtrade.exchange.common - WARNING - fetch_order() returned exception: "Could not get order due to NotSupported. Message: bybit fetchOrder() is not supported for spot markets". Giving up.
2024-10-09 21:00:06,057 - freqtrade.freqtradebot - INFO - Cannot query order for Trade(id=1, pair=ETH/USDT, amount=0.00000000, is_short=False, leverage=1.0, open_rate=2355.19000000, open_since=2024-10-09 21:00:01) due to Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/exchange.py", line 1504, in fetch_order
    order = self._api.fetch_order(order_id, pair, params=params)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/bybit.py", line 4546, in fetch_order
    return self.fetch_order_classic(id, symbol, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/bybit.py", line 4518, in fetch_order_classic
    raise NotSupported(self.id + ' fetchOrder() is not supported for spot markets')
ccxt.base.errors.NotSupported: bybit fetchOrder() is not supported for spot markets

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/common.py", line 181, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/exchange/exchange.py", line 1519, in fetch_order
    raise TemporaryError(
freqtrade.exceptions.TemporaryError: Could not get order due to NotSupported. Message: bybit fetchOrder() is not supported for spot markets

  ```

**Comment by xmatthias** [comment]
Bybit has quite honestly turned into a mess 😆 

I've tested exactly this this morning on an unified subaccount and the function worked fine - so it's "how is your account defined" specific - which makes this VERY difficult 😆 

I'll try to have a look in the evening

**Comment by xmatthias** [comment]
Works in my testing on a non-unified subaccount with the latest develop (see linked commit above).

now non-unified accounts seem to go away in November (based on an anouncement i got today)... so we'll see how this actually plays out for subaccounts ...

**Comment by kennylbj** [comment]
Thank you, I will test it once the next stable version is released

**Comment by gorsek1** [comment]
I also tested 6 bots on Bybit Spot (Non-unified) And got the same error as OP)
Futures work.

**Comment by xmatthias** [comment]
@gorsek1 update to the latest develop and it'll work :)
