### ISSUE TITLE
  merge_informative_pair  function  " TypeError: left_indexer cannot be None"

### ISSUE THREAD

**Issue by 731315163** [freqtrade/freqtrade#10784]
## Describe your environment

  * Operating system: win11
  * Python Version: 3.11.9 (`python -V`)
  * CCXT version:  4.3.55 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2024.9 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:
   `dataframe = merge_informative_pair(             dataframe, informative, self.timeframe, self.inform_timeframe, ffill=True         )`
reported bug  raise TypeError("left_indexer cannot be None") .

*Explain the problem you have encountered*
  `dataframe = merge_informative_pair(             dataframe, informative, self.timeframe, self.inform_timeframe, ffill=False         )` 
 It's running normally without any bugs.
### Steps to reproduce:
strategy.py file contain sub code 
 merge_informative_pair(             dataframe, informative, self.timeframe, self.inform_timeframe, ffill=True         )
  
### Observed Results:

  * What happened?
  every times
  * What did you expect to happen?
 no TypeError: left_indexer cannot be None
### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  Traceback (most recent call last):
  File "C:\Users\zt\.pyenv\pyenv-win\versions\3.11.9\Lib\runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zt\.pyenv\pyenv-win\versions\3.11.9\Lib\runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "c:\Users\zt\.vscode\extensions\ms-python.debugpy-2024.10.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy\__main__.py", line 39, in <module>
    cli.main()
  File "c:\Users\zt\.vscode\extensions\ms-python.debugpy-2024.10.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\Users\zt\.vscode\extensions\ms-python.debugpy-2024.10.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "c:\Users\zt\.vscode\extensions\ms-python.debugpy-2024.10.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\zt\.vscode\extensions\ms-python.debugpy-2024.10.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "c:\Users\zt\.vscode\extensions\ms-python.debugpy-2024.10.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "C:\Users\zt\project\Forecast\freqtradebot.py", line 128, in <module>
    backtesting(strategynames)
  File "C:\Users\zt\project\Forecast\freqtradebot.py", line 39, in backtesting
    bot.backtesting(
  File "C:\Users\zt\project\Forecast\freqtrader\tradebot.py", line 196, in backtesting
    start_backtesting(args)
  File "c:\Users\zt\project\Forecast\.venv\Lib\site-packages\freqtrade\commands\optimize_commands.py", line 60, in start_backtesting     
    backtesting.start()
  File "c:\Users\zt\project\Forecast\.venv\Lib\site-packages\freqtrade\optimize\backtesting.py", line 1623, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\zt\project\Forecast\.venv\Lib\site-packages\freqtrade\optimize\backtesting.py", line 1530, in backtest_one_strategy     
    preprocessed = self.strategy.advise_all_indicators(data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\zt\project\Forecast\.venv\Lib\site-packages\freqtrade\strategy\interface.py", line 1586, in advise_all_indicators       
    return {
           ^
  File "c:\Users\zt\project\Forecast\.venv\Lib\site-packages\freqtrade\strategy\interface.py", line 1587, in <dictcomp>
    pair: self.advise_indicators(pair_data.copy(), {"pair": pair}).copy()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\zt\project\Forecast\.venv\Lib\site-packages\freqtrade\strategy\interface.py", line 1645, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zt\project\Forecast\user_data\strategies\XYGrid.py", line 177, in populate_indicators
    dataframe = merge_informative_pair(
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\zt\project\Forecast\.venv\Lib\site-packages\freqtrade\strategy\strategy_helper.py", line 89, in merge_informative_pair  
    dataframe = pd.merge_ordered(
                ^^^^^^^^^^^^^^^^^
  File "c:\Users\zt\project\Forecast\.venv\Lib\site-packages\pandas\core\reshape\merge.py", line 436, in merge_ordered
    result = _merger(left, right)
             ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\zt\project\Forecast\.venv\Lib\site-packages\pandas\core\reshape\merge.py", line 415, in _merger
    return op.get_result()
           ^^^^^^^^^^^^^^^
  File "c:\Users\zt\project\Forecast\.venv\Lib\site-packages\pandas\core\reshape\merge.py", line 1933, in get_result
    raise TypeError("left_indexer cannot be None")
TypeError: left_indexer cannot be None
  ```
code:

```
#python
from datetime import datetime, timedelta
from enum import IntFlag, auto
from numbers import Number, Real
from pathlib import Path
from typing import Any, Literal, Optional, Sequence

import freqtrade.vendor.qtpylib.indicators as qtpylib
import numpy as np
import pandas as pd
import talib.abstract as ta
from freqtrade.exchange import timeframe_to_prev_date
from freqtrade.strategy import (
    CategoricalParameter,
    DecimalParameter,
    IntParameter,
    merge_informative_pair,
    stoploss_from_absolute,
    stoploss_from_open,
)
from freqtrade.strategy.interface import (
    CandleType,
    IStrategy,
    ListPairsWithTimeframes,
    Order,
    Trade,
)
from scipy.stats import norm

from mathematics import Long_Rhombus, Short_Rhombus, abs_Rhombus



enter_long = "enter_long"
enter_short = "enter_short"


average_price = "averageprice"
ma = "ema20"
lower_price = "lower_price"

grid_num = "grid_num"

atr = "atr"

profit = "profit"


timeperiod_v = 12 * 24 * 7


class XYGrid(IStrategy):
    startup_candle_count = timeperiod_v
    can_short: bool = True
    # 定义策略的最小ROI（投资回报率）
    minimal_roi = {}  # 1% profit

    # 止损
    stoploss = -1  # 3% stoploss
    max_entry_position_adjustment = -1
    # 追踪止损
    trailing_stop = True

    # 策略的时间周期
    timeframe = "5m"
    timeperiod = timeperiod_v
    inform_timeframe = "1d"

    long_distance = DecimalParameter(0.1, 1, decimals=1, default=0.4, space="buy")
    long_lowerbound = DecimalParameter(0.5, 1, decimals=1, default=0.6, space="buy")
    direction = CategoricalParameter(
        ["short", "long", "longshort"], default="short", space="buy"
    )
    entery_internal = CategoricalParameter([5, 10, 15], default=10, space="buy")
    exit_internal = CategoricalParameter([5, 10, 15], default=5, space="buy")
    short_distance = DecimalParameter(0.1, 1, decimals=1, default=1.6, space="short")
    short_lowerbound = DecimalParameter(1, 3, decimals=1, default=1, space="short")
    gridspacing = DecimalParameter(0.001, 0.01, decimals=3, default=0.005, space="sell")


    def informative_pairs(self):  # type: ignore

        # 获取白名单中的所有交易对。
        pairs = self.dp.current_whitelist()
        # 为每对交易对分配tf，以便可以为策略下载和缓存它们。
        # informative_pairs = [(pair, "1d") for pair in pairs]
        # 可选的附加“静态”交易对
        informative_pairs = [
            ("BTC/USDT", "1d", ""),
        ]
        return informative_pairs

    def populate_indicators(
        self, dataframe: pd.DataFrame, metadata: dict
    ) -> pd.DataFrame:
        if not self.dp:

            return dataframe

        # df,_= self.dp.get_analyzed_dataframe(pair,self.timeframe)
        # 获取信息交易对
        informative = self.dp.get_pair_dataframe(
            pair=metadata["pair"], timeframe=self.inform_timeframe
        )

        # 获取14天rsi值
        informative[average_price] = ta.AVGPRICE(
            informative["open"],
            informative["high"],
            informative["low"],
            informative["close"],
        )
        mas = ta.MA(informative[average_price], timeperiod=21)
        informative[ma] = mas

        print(informative.head())
        # 使用辅助函数merge_informative_pair安全地合并交易对
        # 自动重命名列并合并较短时间框架的数据帧和较长时间框架的信息交易对
        # 使用ffill使得1d的值在每一天的每一行都可用。
        # 否则，原始数据帧和信息交易对之间的比较只能每天进行一次。
        # 有关此方法的完整文档，请参见下文
        dataframe = merge_informative_pair(
            dataframe, informative, self.timeframe, self.inform_timeframe, True
        )
     

        dataframe.to_csv(Path.cwd() / "indicators.csv")
        return dataframe

    def populate_entry_trend(
        self, dataframe: pd.DataFrame, metadata: dict
    ) -> pd.DataFrame:

        # # df,_=self.dp.get_analyzed_dataframe(pair,self.timeframe)
        # trade_date = timeframe_to_prev_date(self.timeframe, trade.open_date_utc)
        # # 查找交易蜡烛。
        # trade_candle = dataframe.loc[dataframe['date'] == trade_date]
        # # 对于刚开启的交易，trade_candle可能为空，因为它仍然不完整。
        # if not trade_candle.empty:
        # current_candle = dataframe.iloc[-1].squeeze()
        # self.cur_grid_num = current_candle[grid_num]  # type: ignore

        dataframe.loc[
            (
                (
                    dataframe["close"]
                    < (dataframe[long_rhombus].apply(lambda rho: rho.left))
                )
                & (
                    self.direction.value == "long"
                    or self.direction.value == "longshort"
                )
            ),
            "enter_long",
        ] = 1
        dataframe.loc[
            (
                (
                    dataframe["close"]
                    < (dataframe[short_rhombus].apply(lambda rho: rho.right))
                )
                & (
                    self.direction.value == "short"
                    or self.direction.value == "longshort"
                )
            ),
            "enter_long",
        ] = 1
        return dataframe

    def populate_exit_trend(
        self, dataframe: pd.DataFrame, metadata: dict
    ) -> pd.DataFrame:
        return dataframe

    # use_exit_signal = True

    # def custom_exit(
    #     self,
    #     pair: str,
    #     trade: Trade,
    #     current_time: datetime,
    #     current_rate: float,
    #     current_profit: float,
    #     **kwargs
    # ):
    #     if self.c_exit_signal is not None:
    #         return self.c_exit_signal

    # use_custom_stoploss = False

    def custom_stake_amount(
        self,
        pair: str,
        current_time: datetime,
        current_rate: float,
        proposed_stake: float,
        min_stake: Optional[float],
        max_stake: float,
        leverage: float,
        entry_tag: Optional[str],
        side: str,
        **kwargs,
    ) -> float:
        # dataframe, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)
        # current_candle = dataframe.iloc[-1]

        amount = proposed_stake * self.gridspacing.value

        return amount

    position_adjustment_enable = True

    def adjust_trade_position(
        self,
        trade: Trade,
        current_time: datetime,
        current_rate: float,
        current_profit: float,
        min_stake: Optional[float],
        max_stake: float,
        current_entry_rate: float,
        current_exit_rate: float,
        current_entry_profit: float,
        current_exit_profit: float,
        **kwargs,
    ) -> Optional[float]:
        """

        当策略未实现时，返回 None

        :param trade: 交易对象。
        :param current_rate: 当前入场报价（与 current_entry_profit 相同）
        :param current_profit: 当前利润（作为比例），基于 current_rate 计算（与 current_entry_profit 相同）。
        :param min_stake: 交易所允许的最小投注额（适用于入场和退出）

        :param current_entry_rate: 使用入场定价的当前汇率。
        :param current_exit_rate: 使用退出定价的当前汇率。
        :param current_entry_profit: 使用入场定价的当前利润。
        :param current_exit_profit: 使用退出定价的当前利润。
        :param **kwargs: 请确保将其保留在此处，以免破坏您的策略。
        :return float: 调整交易的下注金额，
                       正值为增加仓位，负值为减少仓位。
                       返回 None 表示不采取任何操作。
        """
        order = trade.select_order()
        if order is None:
            order_timedetail = timedelta(days=999)
        else:
            if order.ft_is_open or order.order_filled_utc is None:
                return None
            if (
                current_rate < order.safe_price * ((1 + self.gridspacing.value) / 2)
            ) and (current_rate > (1 - (self.gridspacing.value) / 2)):
                return None
            order_timedetail = current_time - order.order_filled_utc
        _enter_timedetial_sign = order_timedetail > timedelta(
            minutes=int(self.entery_internal.value)
        )
        _exit_timedetial_sign = order_timedetail > timedelta(
            minutes=int(self.exit_internal.value)
        )
        if not _enter_timedetial_sign and not _exit_timedetial_sign:
            return None
        dataframe, _ = self.dp.get_analyzed_dataframe(trade.pair, self.timeframe)
        current_candle = dataframe.iloc[-1]
        amount = self.wallets.get_trade_stake_amount(  # type: ignore
            pair=trade.pair, max_open_trades=self.max_open_trades
        )
        if amount <= 0:
            return None

        cur_ratio = trade.amount / amount
        if trade.is_short:
            cur_rho: abs_Rhombus = current_candle[short_rhombus]
        else:
            cur_rho: abs_Rhombus = current_candle[long_rhombus]

        if (
            _enter_timedetial_sign
            and cur_rho.ratioforenter(current_rate) - cur_ratio > self.gridspacing.value
        ):
            buyamount = amount * self.gridspacing.value
            return buyamount
        elif (
            _exit_timedetial_sign
            and cur_rho.ratioforexit(current_rate) - cur_ratio > self.gridspacing.value
        ):

            sellamount = -amount * self.gridspacing.value
            return sellamount

        else:
            return None
```

**Comment by stash86** [comment]
I assume you are working on futures market. That means your pair naming inside informative_pairs function is wrong, which mean there is no informative data

**Comment by 731315163** [comment]
```
{
    "max_open_trades": 1,
    "stake_currency": "USDT",
    "stake_amount": "unlimited",
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "dry_run": true,
    "dry_run_wallet": 10000,
    "cancel_open_orders_on_exit": false,
    "trading_mode": "futures",
    "margin_mode": "isolated",
    "amend_last_stake_amount": true,
    "unfilledtimeout": {
        "entry": 10,
        "exit": 10,
        "exit_timeout_count": 3,
        "unit": "minutes"
    },
    "entry_pricing": {
        "price_side": "other",
        "use_order_book": true,
        "order_book_top": 1,
        "price_last_balance": 0.0,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "exit_pricing": {
        "price_side": "other",
        "use_order_book": true,
        "order_book_top": 1
    },
    "exchange": {
        "name": "binance",
        "key": "*************************************************************************",
        "secret": "***************************************************************************",
        "ccxt_config": {
            "enableRateLimit": true
        },
        "ccxt_async_config": {
            "enableRateLimit": true
        },
        "pair_whitelist": [
            "BTC/USDT:USDT"
        ]
    },
    "pairlists": [
        {
            "method": "StaticPairList"
        }
    ],
    "telegram": {
        "enabled": false,
        "token": "",
        "chat_id": ""
    },
    "api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8080,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "************************************",
        "ws_token": "*************************************",
        "CORS_origins": [],
        "username": "**********************",
        "password": "*********************"
    },
    "bot_name": "freqtrade",
    "initial_state": "running",
    "force_entry_enable": false,
    "internals": {
        "process_throttle_secs": 4
    }
}
```

> I assume you are working on futures market. That means your pair naming inside informative_pairs function is wrong, which mean there is no informative data

**Comment by xmatthias** [comment]
The way you're accessing the dataframe assumes your informative pairs have the full pairlist listed.

``` python

    def informative_pairs(self):
        pairs = self.dp.current_whitelist()
        # informative_pairs = [(pair, "1d") for pair in pairs]
        informative_pairs = [
            ("BTC/USDT", "1d", ""),
        ]
        return informative_pairs

#....

        informative = self.dp.get_pair_dataframe(
            pair=metadata["pair"], timeframe=self.inform_timeframe
        )
```

Highlighting the problem - your pairlist uses BTC/USDT:USDT - so `metadata["pair"]` will correspond to `"BTC/USDT:USDT"`.
informative_pairs however only requests data for BTC/USDT (the spot market) - hence your call to get informative data fails - leading to an error when merging - as you're merging "nothing".

Essentially - the very simple solution is to use the code as you had it as comment in informative_pairs - where it'll fetch all 1D data for all pairs you've got in your whitelist - so you can't have this disconnect.

Alternatively - update the pair in your informative_pairs method to `BTC/USDT:USDT` - and it'll also work.

**Comment by 731315163** [comment]
```
[2024-10-19 11:23:14] [WARNING] BTC/USDT:USDT, futures, 1d, data starts at 2023-01-01 00:00:00
                       date     open     high      low    close      volume  averageprice  MA21
0 2023-01-01 00:00:00+00:00  16537.5  16618.8  16488.0  16610.3  105502.965     16563.650   NaN
1 2023-01-02 00:00:00+00:00  16610.4  16799.0  16541.2  16666.0  215161.176     16654.150   NaN
2 2023-01-03 00:00:00+00:00  16665.9  16774.0  16600.3  16667.2  203070.205     16676.850   NaN
3 2023-01-04 00:00:00+00:00  16667.3  16984.6  16645.7  16842.1  349747.838     16784.925   NaN
4 2023-01-05 00:00:00+00:00  16842.2  16872.8  16740.4  16823.8  176369.347     16819.800   NaN
```


it still doesn't work
```
   def informative_pairs(self):


        # 获取白名单中的所有交易对。
        pairs = self.dp.current_whitelist()
        # 为每对交易对分配tf，以便可以为策略下载和缓存它们。
        informative_pairs = [(pair, "1d") for pair in pairs]
        

        return informative_pairs
```

**Comment by 731315163** [comment]
```
 def populate_indicators(
        self, dataframe: pd.DataFrame, metadata: dict
    ) -> pd.DataFrame:
        if not self.dp:

            return dataframe

        # df,_= self.dp.get_analyzed_dataframe(pair,self.timeframe)
       
     # it do work ok
        informative = self.dp.get_pair_dataframe(
            pair=metadata["pair"], timeframe=self.inform_timeframe
        )

        # 获取14天rsi值
        informative[average_price] = ta.AVGPRICE(
            informative["open"],
            informative["high"],
            informative["low"],
            informative["close"],
        )
        mas = ta.MA(informative[average_price], timeperiod=21)
        informative[ma] = mas

        print(informative.head())
     
        # itstill doesn‘t work 
        dataframe = merge_informative_pair(
            dataframe, informative, self.timeframe, self.inform_timeframe
        )
        # 计算原始数据帧（5m时间框架）的rsi值
        # dataframe["rsi"] = ta.RSI(dataframe, timeperiod=14)

        dataframe.to_csv(Path.cwd() / "indicators.csv")
        return dataframe
```
If you have obtained accurate and informative data in the populate_indicators function, similar to translating 'log' as mentioned earlier.

**Comment by xmatthias** [comment]
well it does - but a MA21  will be NAN for the first 21 candles - and you're plotting the first 5.

Having your main timeframe at 5m - only the very last 3(ish) candles will actually matter - as that's the only ones that will have a reference to be joined onto.

**Comment by 731315163** [comment]
```
  dataframe = merge_informative_pair(
            dataframe, informative, self.timeframe, self.inform_timeframe, ffill=False
        ).ffill() 
```
The ffill() function works properly, but there is a limit of 6048 for 5-minute data, and for 1-day interval data, I need 21 days. What should I do?

**Comment by xmatthias** [comment]
you can't - and i honestly don't see why you'd need that, either.

a signal is always based on the last candle - so if you generate your 1d indicators on the 1d dataframe _before_ merging, you'll have the 21 MA (or whatever else) available at the current day.

If you really need to look back 21 days to generate the signal (wouldn't know why if you followed the above) - you'll need to use a different (higher) base timeframe - one which gives you 21 days of data (5m will not).

**Comment by stash86** [comment]
If you need to some rolling or any other things that require plenty of 1d data, do so before you merge it to the main timeframe.
