### ISSUE TITLE
freqtrade - ERROR - Fatal exception! joblib.externals.loky.process_executor._RemoteTraceback

### ISSUE THREAD

**Issue by nbwcbz** [freqtrade/freqtrade#10785]
```
2024-10-13 16:32:58,163 - freqtrade.optimize.hyperopt - INFO - Effective number of parallel workers used: 2
                                                                                                      Hyperopt results                                                                                                      
                                                  ┏━━━━━━┳━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━┓                                                  
                                                  ┃ Best ┃ Epoch ┃ Trades ┃ Win  Draw  Loss  Win% ┃ Avg profit ┃ Profit ┃ Avg duration ┃ Objective ┃ Max Drawdown (Acct) ┃                                                  
                                                  ┡━━━━━━╇━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━┩                                                  
                                                  └──────┴───────┴────────┴───────────────────────┴────────────┴────────┴──────────────┴───────────┴─────────────────────┘                                                  
Epochs ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0/200   0% • 0:00:43 • -:--:--
2024-10-13 16:33:41,355 - freqtrade - ERROR - Fatal exception!
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py", line 463, in _process_worker
    r = call_item()
        ^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py", line 291, in __call__
    return self.fn(*self.args, **self.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/joblib/parallel.py", line 598, in __call__
    return [func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/joblib/externals/loky/cloudpickle_wrapper.py", line 32, in __call__
    return self._obj(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/optimize/hyperopt.py", line 392, in generate_optimizer
    bt_results = self.backtesting.backtest(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 1495, in backtest
    self.backtest_loop(row, pair, current_time, end_date, trade_dir)
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 1380, in backtest_loop
    self._check_trade_exit(trade, row, current_time)  # Place exit order if necessary
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 885, in _check_trade_exit
    t = self._get_exit_for_signal(trade, row, exit_, current_time)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 772, in _get_exit_for_signal
    and len(row[EXIT_TAG_IDX]) > 0
        ^^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'int' has no len()
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 45, in main
    return_code = args["func"](args)
                  ^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 109, in start_hyperopt
    hyperopt.start()
  File "/freqtrade/freqtrade/optimize/hyperopt.py", line 661, in start
    f_val = self.run_optimizer_parallel(parallel, asked)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/optimize/hyperopt.py", line 484, in run_optimizer_parallel
    return parallel(
           ^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/joblib/parallel.py", line 2007, in __call__
    return output if self.return_generator else list(output)
                                                ^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/joblib/parallel.py", line 1650, in _get_outputs
    yield from self._retrieve()
  File "/home/ftuser/.local/lib/python3.12/site-packages/joblib/parallel.py", line 1754, in _retrieve
    self._raise_error_fast()
  File "/home/ftuser/.local/lib/python3.12/site-packages/joblib/parallel.py", line 1789, in _raise_error_fast
    error_job.get_result(self.timeout)
  File "/home/ftuser/.local/lib/python3.12/site-packages/joblib/parallel.py", line 745, in get_result
    return self._return_or_raise()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/joblib/parallel.py", line 763, in _return_or_raise
    raise self._result
TypeError: object of type 'int' has no len()
```

**Comment by nbwcbz** [comment]
This question even stumped chargpt. I don't know how to answer it.

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.



I'll treat this as "using outdated version" until that info is provided.

**Comment by xmatthias** [comment]
Closing this as we got no further feedback.

feel free to comment below should this still be a problem and you'll be able to provide the information requested above (version, to start with).
