### ISSUE TITLE
Fatal Assertion Error

### ISSUE THREAD

**Issue by kivinblue1** [freqtrade/freqtrade#10806]
## Describe your environment

  * Operating system: Ubuntu Server 
  * Python Version: 3.12 (`python -V`)
  * CCXT version: Docker 2024.9 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2024.9 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  

a fatal error  and end of freqtrade process. Sending a telegram message notifying you of the termination of the freqtrade process.
Bybit exchange, such an error occurs once every 3-4 days. I have exactly the same strategy, but for the okx exchange, it works without errors.

```
freqtrade_bybit_15m  |   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
freqtrade_bybit_15m  |   |   File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/async_support/base/exchange.py", line 210, in fetch
freqtrade_bybit_15m  |   |     async with session_method(yarl.URL(url, encoded=True),
freqtrade_bybit_15m  |   |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
freqtrade_bybit_15m  |   |   File "/home/ftuser/.local/lib/python3.12/site-packages/aiohttp/client.py", line 1353, in __aenter__
freqtrade_bybit_15m  |   |     self._resp = await self._coro
freqtrade_bybit_15m  |   |                  ^^^^^^^^^^^^^^^^
freqtrade_bybit_15m  |   |   File "/home/ftuser/.local/lib/python3.12/site-packages/aiohttp/client.py", line 657, in _request
freqtrade_bybit_15m  |   |     conn = await self._connector.connect(
freqtrade_bybit_15m  |   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
freqtrade_bybit_15m  |   |   File "/home/ftuser/.local/lib/python3.12/site-packages/aiohttp/connector.py", line 564, in connect
freqtrade_bybit_15m  |   |     proto = await self._create_connection(req, traces, timeout)
freqtrade_bybit_15m  |   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
freqtrade_bybit_15m  |   |   File "/home/ftuser/.local/lib/python3.12/site-packages/aiohttp/connector.py", line 975, in _create_connection
freqtrade_bybit_15m  |   |     _, proto = await self._create_direct_connection(req, traces, timeout)
freqtrade_bybit_15m  |   |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
freqtrade_bybit_15m  |   |   File "/home/ftuser/.local/lib/python3.12/site-packages/aiohttp/connector.py", line 1319, in _create_direct_connection
freqtrade_bybit_15m  |   |     transp, proto = await self._wrap_create_connection(
freqtrade_bybit_15m  |   |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
freqtrade_bybit_15m  |   |   File "/home/ftuser/.local/lib/python3.12/site-packages/aiohttp/connector.py", line 1073, in _wrap_create_connection
freqtrade_bybit_15m  |   |     sock = await aiohappyeyeballs.start_connection(
freqtrade_bybit_15m  |   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
freqtrade_bybit_15m  |   |   File "/home/ftuser/.local/lib/python3.12/site-packages/aiohappyeyeballs/impl.py", line 88, in start_connection
freqtrade_bybit_15m  |   |     sock, _, _ = await staggered.staggered_race(
freqtrade_bybit_15m  |   |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
freqtrade_bybit_15m  |   |   File "/home/ftuser/.local/lib/python3.12/site-packages/aiohappyeyeballs/_staggered.py", line 91, in staggered_race
freqtrade_bybit_15m  |   |     async with asyncio.TaskGroup() as tg:
freqtrade_bybit_15m  |   |                ^^^^^^^^^^^^^^^^^^^
freqtrade_bybit_15m  |   |   File "/usr/local/lib/python3.12/asyncio/taskgroups.py", line 145, in __aexit__
freqtrade_bybit_15m  |   |     raise me from None
freqtrade_bybit_15m  |   | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
freqtrade_bybit_15m  |   +-+---------------- 1 ----------------
freqtrade_bybit_15m  |     | Traceback (most recent call last):
freqtrade_bybit_15m  |     |   File "/home/ftuser/.local/lib/python3.12/site-packages/aiohappyeyeballs/_staggered.py", line 85, in run_one_coro
freqtrade_bybit_15m  |     |     assert winner_index is None  # noqa: S101
freqtrade_bybit_15m  |     |            ^^^^^^^^^^^^^^^^^^^^
freqtrade_bybit_15m  |     | AssertionError
freqtrade_bybit_15m  |     +------------------------------------
freqtrade_bybit_15m exited with code 0
```

**Comment by xmatthias** [comment]
well unfortunately, the exception is truncated and doesn't include anything useful (as to what part of freqtrade code would've caused this).

Please provide the full exception - as well as some lines leading up to it - so we can actually look at this.

**Comment by kivinblue1** [comment]
> well unfortunately, the exception is truncated and doesn't include anything useful (as to what part of freqtrade code would've caused this).
> 
> Please provide the full exception - as well as some lines leading up to it - so we can actually look at this.

unfortunately, I had overwritten the logs by restarting the bot... So, i will wait when error repeat, as I said above, the error started appearing after the 2024.9 update approximate every 3-4 days.

**Comment by kivinblue1** [comment]
> > well unfortunately, the exception is truncated and doesn't include anything useful (as to what part of freqtrade code would've caused this).
> > Please provide the full exception - as well as some lines leading up to it - so we can actually look at this.
> 
> unfortunately, I had overwritten the logs by restarting the bot... So, i will wait when error repeat, as I said above, the error started appearing after the 2024.9 update approximate every 3-4 days.

In last 24 hours i get unhandled errors:
```
2024-10-17 03:47:11,390 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2024.9', state='RUNNING'
2024-10-17 03:48:04,728 - freqtrade.exchange.exchange_ws - ERROR - Exception in continuously_async_watch_ohlcv for TIA/USDT:USDT, 15m
Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/exchange_ws.py", line 147, in _continuously_async_watch_ohlcv
    data = await self.ccxt_object.watch_ohlcv(pair, timeframe)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/pro/bybit.py", line 618, in watch_ohlcv
    result = await self.watch_ohlcv_for_symbols([[symbol, timeframe]], since, limit, params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/pro/bybit.py", line 648, in watch_ohlcv_for_symbols
    symbol, timeframe, stored = await self.watch_topics(url, messageHashes, rawHashes, params)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/pro/bybit.py", line 2095, in watch_topics
    return await self.watch_multiple(url, messageHashes, message, messageHashes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/async_support/base/ws/future.py", line 41, in callback
    f.result()
ccxt.base.errors.NetworkError: Abnormal closure of client
```

**Comment by kivinblue1** [comment]
> > well unfortunately, the exception is truncated and doesn't include anything useful (as to what part of freqtrade code would've caused this).
> > Please provide the full exception - as well as some lines leading up to it - so we can actually look at this.
> 
> unfortunately, I had overwritten the logs by restarting the bot... So, i will wait when error repeat, as I said above, the error started appearing after the 2024.9 update approximate every 3-4 days.

and this:
```
2024-10-17 15:39:37,935 - freqtrade - ERROR - Fatal exception!
  + Exception Group Traceback (most recent call last):
  |   File "/freqtrade/freqtrade/main.py", line 45, in main
  |     return_code = args["func"](args)
  |                   ^^^^^^^^^^^^^^^^^^
  |   File "/freqtrade/freqtrade/commands/trade_commands.py", line 25, in start_trading
  |     worker.run()
  |   File "/freqtrade/freqtrade/worker.py", line 78, in run
  |     state = self._worker(old_state=state)
  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/freqtrade/freqtrade/worker.py", line 119, in _worker
  |     self._throttle(
  |   File "/freqtrade/freqtrade/worker.py", line 160, in _throttle
  |     result = func(*args, **kwargs)
  |              ^^^^^^^^^^^^^^^^^^^^^
  |   File "/freqtrade/freqtrade/worker.py", line 194, in _process_running
  |     self.freqtrade.process()
  |   File "/freqtrade/freqtrade/freqtradebot.py", line 254, in process
  |     self.exchange.reload_markets()
  |   File "/freqtrade/freqtrade/exchange/exchange.py", line 664, in reload_markets
  |     self._markets = retrier(self._load_async_markets, retries=retries)(reload=True)
  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/freqtrade/freqtrade/exchange/common.py", line 181, in wrapper
  |     return f(*args, **kwargs)
  |            ^^^^^^^^^^^^^^^^^^
  |   File "/freqtrade/freqtrade/exchange/exchange.py", line 637, in _load_async_markets
  |     markets = self.loop.run_until_complete(self._api_reload_markets(reload=reload))
  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
  |     return future.result()
  |            ^^^^^^^^^^^^^^^
  |   File "/freqtrade/freqtrade/exchange/exchange.py", line 625, in _api_reload_markets
  |     return await self._api_async.load_markets(reload=reload, params={})
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/async_support/base/exchange.py", line 287, in load_markets
  |     raise e
  |   File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/async_support/base/exchange.py", line 283, in load_markets
  |     result = await self.markets_loading
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/async_support/base/exchange.py", line 273, in load_markets_helper
  |     markets = await self.fetch_markets(params)
  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/async_support/bybit.py", line 1486, in fetch_markets
  |     promises = await asyncio.gather(*promisesUnresolved)
  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/async_support/bybit.py", line 1627, in fetch_future_markets
  |     promises = await asyncio.gather(*linearPromises)
  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/async_support/base/exchange.py", line 859, in request
  |     return await self.fetch2(path, api, method, params, headers, body, config)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/async_support/base/exchange.py", line 855, in fetch2
  |     raise e
  |   File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/async_support/base/exchange.py", line 846, in fetch2
  |     return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/async_support/base/exchange.py", line 210, in fetch
  |     async with session_method(yarl.URL(url, encoded=True),
  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/home/ftuser/.local/lib/python3.12/site-packages/aiohttp/client.py", line 1353, in __aenter__
  |     self._resp = await self._coro
  |                  ^^^^^^^^^^^^^^^^
  |   File "/home/ftuser/.local/lib/python3.12/site-packages/aiohttp/client.py", line 657, in _request
  |     conn = await self._connector.connect(
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/home/ftuser/.local/lib/python3.12/site-packages/aiohttp/connector.py", line 564, in connect
  |     proto = await self._create_connection(req, traces, timeout)
  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/home/ftuser/.local/lib/python3.12/site-packages/aiohttp/connector.py", line 975, in _create_connection
  |     _, proto = await self._create_direct_connection(req, traces, timeout)
  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/home/ftuser/.local/lib/python3.12/site-packages/aiohttp/connector.py", line 1319, in _create_direct_connection
  |     transp, proto = await self._wrap_create_connection(
  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/home/ftuser/.local/lib/python3.12/site-packages/aiohttp/connector.py", line 1073, in _wrap_create_connection
  |     sock = await aiohappyeyeballs.start_connection(
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/home/ftuser/.local/lib/python3.12/site-packages/aiohappyeyeballs/impl.py", line 88, in start_connection
  |     sock, _, _ = await staggered.staggered_race(
  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/home/ftuser/.local/lib/python3.12/site-packages/aiohappyeyeballs/_staggered.py", line 91, in staggered_race
  |     async with asyncio.TaskGroup() as tg:
  |                ^^^^^^^^^^^^^^^^^^^
  |   File "/usr/local/lib/python3.12/asyncio/taskgroups.py", line 145, in __aexit__
  |     raise me from None
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/home/ftuser/.local/lib/python3.12/site-packages/aiohappyeyeballs/_staggered.py", line 85, in run_one_coro
    |     assert winner_index is None  # noqa: S101
    |            ^^^^^^^^^^^^^^^^^^^^
    | AssertionError
    +------------------------------------
Exception ignored in: <coroutine object Exchange.request at 0xffff7cbfa770>
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/async_support/base/exchange.py", line 859, in request
    return await self.fetch2(path, api, method, params, headers, body, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/async_support/base/exchange.py", line 855, in fetch2
    raise e
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/async_support/base/exchange.py", line 846, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/async_support/base/exchange.py", line 210, in fetch
    async with session_method(yarl.URL(url, encoded=True),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/aiohttp/client.py", line 1353, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/aiohttp/client.py", line 657, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/aiohttp/connector.py", line 564, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/aiohttp/connector.py", line 975, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/aiohttp/connector.py", line 1319, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/aiohttp/connector.py", line 1080, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs, sock=sock)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1148, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1183, in _create_connection_transport
    transport.close()
  File "/usr/local/lib/python3.12/asyncio/sslproto.py", line 116, in close
    self._ssl_protocol._start_shutdown()
  File "/usr/local/lib/python3.12/asyncio/sslproto.py", line 621, in _start_shutdown
    self._abort(None)
  File "/usr/local/lib/python3.12/asyncio/sslproto.py", line 671, in _abort
    self._transport._force_close(exc)
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 906, in _force_close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 795, in call_soon
    self._check_closed()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 541, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by xmatthias** [comment]
well the first error suggests an unstable network - as the websocket closes unexpectantly.
that's however not unhandled - it's handled (but logged) and won't impact bot operations - as the bot will continue to move forward without issues - though the websocket will need to be re-established at the next opportunity.


---

The latter problem is odd  - but a bit of research does show a very simple fix - or rather a problem with a dependency (of a dependency).
 [source](https://github.com/aio-libs/aiohappyeyeballs/issues/100).

simply run `pip install -U aiohappyeyeballs` with your virtual environment activated, and it'll fix the particular problem.
Alternatively you can also simply delete the virtual environment and recreate it
 
For docker, i'll think of something to have the image re-published with the same tag - but that'll take a bit.

**Comment by xmatthias** [comment]
Docker images are uptodate now and no longer affected by this.

Best do a fresh pull (`docker compose pull`) to get the new image.
