### ISSUE TITLE
Freqtrade service demo versions of stock markets? 

### ISSUE THREAD

**Issue by ghost** [freqtrade/freqtrade#10813]
Hi!,

Is possible to run Freqtrade with demo versions of stock markets ? I try turn on bot on binace test futures, but i have problem with API authentication, alone bot is correct i test it on dry_run.

  * Operating system:  W11/ WSL
  * Python Version: 3.10
  * CCXT version: Version: 4.4.20
  * Freqtrade Version: freqtrade 2023.8
  

```
(.venv) eldo@Usersky:~/freqtrade/freqtrade$ freqtrade trade --config config.json --strategy MyStrategy
2024-10-20 13:39:35,412 - freqtrade - INFO - freqtrade 2023.8
2024-10-20 13:39:35,771 - freqtrade.worker - INFO - Starting worker 2023.8
2024-10-20 13:39:35,771 - freqtrade.configuration.load_config - INFO - Using config: config.json ...
2024-10-20 13:39:35,772 - freqtrade.loggers - INFO - Verbosity set to 0
2024-10-20 13:39:35,772 - freqtrade.configuration.configuration - INFO - Runmode set to live.
2024-10-20 13:39:35,772 - freqtrade.configuration.configuration - INFO - Dry run is disabled
2024-10-20 13:39:35,772 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:///tradesv3.sqlite"
2024-10-20 13:39:35,772 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 2 ...
2024-10-20 13:39:35,772 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/eldo/freqtrade/freqtrade/user_data ...
2024-10-20 13:39:35,773 - freqtrade.configuration.configuration - INFO - Using data directory: /home/eldo/freqtrade/freqtrade/user_data/data/binance ...
2024-10-20 13:39:35,773 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2024-10-20 13:39:35,781 - freqtrade.exchange.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2024-10-20 13:39:35,781 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2024-10-20 13:39:35,782 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy MyStrategy from '/home/eldo/freqtrade/freqtrade/user_data/strategies/MyStrategy.py'...
2024-10-20 13:39:35,782 - freqtrade.strategy.hyper - INFO - Found no parameter file.
2024-10-20 13:39:35,782 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 5m.
2024-10-20 13:39:35,782 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2024-10-20 13:39:35,782 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 20.
2024-10-20 13:39:35,782 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}.
2024-10-20 13:39:35,782 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'max_open_trades' with value in config file: 2.
2024-10-20 13:39:35,782 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 0.1}
2024-10-20 13:39:35,782 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 5m
2024-10-20 13:39:35,783 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.1
2024-10-20 13:39:35,783 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2024-10-20 13:39:35,783 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2024-10-20 13:39:35,783 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2024-10-20 13:39:35,783 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2024-10-20 13:39:35,783 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: True
2024-10-20 13:39:35,783 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'entry': 'limit', 'exit': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False, 'stoploss_on_exchange_interval': 60}
2024-10-20 13:39:35,783 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'entry': 'GTC', 'exit': 'GTC'}
2024-10-20 13:39:35,783 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2024-10-20 13:39:35,784 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 20
2024-10-20 13:39:35,784 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2024-10-20 13:39:35,784 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 0
2024-10-20 13:39:35,784 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}
2024-10-20 13:39:35,784 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_exit_signal: True
2024-10-20 13:39:35,784 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_only: False
2024-10-20 13:39:35,784 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_entry_signal: False
2024-10-20 13:39:35,784 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_offset: 0.0
2024-10-20 13:39:35,785 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2024-10-20 13:39:35,785 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2024-10-20 13:39:35,785 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: False
2024-10-20 13:39:35,785 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1
2024-10-20 13:39:35,785 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_open_trades: 2
2024-10-20 13:39:35,785 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2024-10-20 13:39:35,789 - freqtrade.exchange.exchange - INFO - Using CCXT 4.4.20
2024-10-20 13:39:35,789 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}, 'enableRateLimit': True}
2024-10-20 13:39:35,803 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}, 'enableRateLimit': True}
2024-10-20 13:39:35,817 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2024-10-20 13:39:36,170 - freqtrade.exchange.exchange - ERROR - Unable to initialize markets.
Traceback (most recent call last):
  File "/home/eldo/freqtrade/freqtrade/.venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 567, in fetch
    response.raise_for_status()
  File "/home/eldo/freqtrade/freqtrade/.venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error:  for url: https://api.binance.com/sapi/v1/capital/config/getall?timestamp=1729424375818&recvWindow=10000&signature=76953e66123cbe79fff3c777f58601b8016b9b285d3b1b29b02fbebe5eef6495

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eldo/freqtrade/freqtrade/.venv/lib/python3.8/site-packages/freqtrade/exchange/exchange.py", line 480, in _load_markets
    self._markets = self._api.load_markets(params={})
  File "/home/eldo/freqtrade/freqtrade/.venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1500, in load_markets
    currencies = self.fetch_currencies()
  File "/home/eldo/freqtrade/freqtrade/.venv/lib/python3.8/site-packages/ccxt/binance.py", line 2669, in fetch_currencies
    promises = [self.sapiGetCapitalConfigGetall(params)]
  File "/home/eldo/freqtrade/freqtrade/.venv/lib/python3.8/site-packages/ccxt/base/types.py", line 35, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
  File "/home/eldo/freqtrade/freqtrade/.venv/lib/python3.8/site-packages/ccxt/binance.py", line 10904, in request
    response = self.fetch2(path, api, method, params, headers, body, config)
  File "/home/eldo/freqtrade/freqtrade/.venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 4089, in fetch2
    raise e
  File "/home/eldo/freqtrade/freqtrade/.venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 4080, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/eldo/freqtrade/freqtrade/.venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 583, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/eldo/freqtrade/freqtrade/.venv/lib/python3.8/site-packages/ccxt/binance.py", line 10871, in handle_errors
    self.throw_exactly_matched_exception(self.get_exceptions_by_url(url, 'exact'), error, feedback)
  File "/home/eldo/freqtrade/freqtrade/.venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 4472, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.AuthenticationError: binance {"code":-2008,"msg":"Invalid Api-Key ID."}
2024-10-20 13:39:36,177 - freqtrade.commands.trade_commands - ERROR - Could not load markets, therefore cannot start. Please investigate the above error for more details.
2024-10-20 13:39:36,177 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/eldo/freqtrade/freqtrade/.venv/lib/python3.8/site-packages/freqtrade/commands/trade_commands.py", line 24, in start_trading
    worker = Worker(args)
  File "/home/eldo/freqtrade/freqtrade/.venv/lib/python3.8/site-packages/freqtrade/worker.py", line 37, in __init__
    self._init(False)
  File "/home/eldo/freqtrade/freqtrade/.venv/lib/python3.8/site-packages/freqtrade/worker.py", line 53, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/home/eldo/freqtrade/freqtrade/.venv/lib/python3.8/site-packages/freqtrade/freqtradebot.py", line 76, in __init__
    self.exchange = ExchangeResolver.load_exchange(
  File "/home/eldo/freqtrade/freqtrade/.venv/lib/python3.8/site-packages/freqtrade/resolvers/exchange_resolver.py", line 37, in load_exchange
    exchange = ExchangeResolver._load_exchange(
  File "/home/eldo/freqtrade/freqtrade/.venv/lib/python3.8/site-packages/freqtrade/resolvers/exchange_resolver.py", line 64, in _load_exchange
    exchange = ex_class(**kwargs)
  File "/home/eldo/freqtrade/freqtrade/.venv/lib/python3.8/site-packages/freqtrade/exchange/exchange.py", line 187, in __init__
    self.validate_config(config)
  File "/home/eldo/freqtrade/freqtrade/.venv/lib/python3.8/site-packages/freqtrade/exchange/exchange.py", line 225, in validate_config
    self.validate_stakecurrency(config['stake_currency'])
  File "/home/eldo/freqtrade/freqtrade/.venv/lib/python3.8/site-packages/freqtrade/exchange/exchange.py", line 514, in validate_stakecurrency
    raise OperationalException(
freqtrade.exceptions.OperationalException: Could not load markets, therefore cannot start. Please investigate the above error for more details.
```

**Comment by xmatthias** [comment]
stock markets are not supported - unless one of the exchanges ccxt supports do support it - but that'd be new to me.

For the effective error - your bot starts in live mode (`dry_run=False`) (so it'd use your money in the account) - but your api key is invalid / wrong - hence it fails to start.

Don't necessarily see how this is related to stock markets anyway.

**Comment by ghost** [comment]
So what should i do if i would like test this bot to trading on:
https://testnet.binancefuture.com/en/futures/BTCUSDT 

or other demo market ? I have correct API.
I turn off dry_run=false cause i want use money from demo balance. I understand that this parameter we use only when we would like test simulate trade on freqtrade.

**Comment by stash86** [comment]
Use dry run instead. Testnet have very limited candles. Whatever you are doing there won't be anywhere near live trading

**Comment by xmatthias** [comment]
We've dropped support for testnets years ago.
They provide no value to a user - as these markets do not reflect actual market behavior (not even close).

They can be used to test api functionality - but are unfit to evaluate strategy performance.
That's why freqtrade has dry-run mode.
