### ISSUE TITLE
KeyError: 'up' exception, preventing the strategy from analyzing OHLCV data for the BTC/USDT pair

### ISSUE THREAD

**Issue by sukonin** [freqtrade/freqtrade#10828]
## Describe your environment

  * Operating system: **macOS (M1 architecture)**
  * Python Version: **3.13.0** (`python -V`)
  * CCXT version: **4.4.20** (`pip freeze | grep ccxt`)
  * Freqtrade Version: **2024.10-dev-35ebf4a047** (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the problem:

While running my strategy, I encountered an issue where the model predictions fail due to a missing key 'up' in the `labels_mean` dictionary. This results in a `KeyError: 'up'` exception, preventing the strategy from analyzing OHLCV data for the BTC/USDT pair.

### Steps to reproduce:

  1. Set up FreqAI model using `PyTorchMLPClassifier` with the strategy.
  2. Enable FreqAI and run the bot with the config provided.
  3. Observe the error when the model attempts to process live data and populate indicators.

### Observed Results:

  * **What happened?**: The bot fails with a `KeyError: 'up'` when trying to access `dk.data["labels_mean"]["up"]` during live prediction. The strategy is unable to proceed with analyzing the BTC/USDT pair.
  * **What did you expect to happen?**: The strategy should correctly process the model predictions and handle the labels ('up', 'down', 'neutral') without errors.

### Relevant code exceptions or logs:

``` python
2024-10-21 14:00:02,869 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error 'up' calling <bound method IStrategy._analyze_ticker_internal of <FreqaiExampleStrategy.FreqaiExampleStrategy object at 0x130a370e0>>
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.13/site-packages/freqtrade/strategy/strategy_wrapper.py", line 28, in wrapper
    return f(*args, **kwargs)
  File "/opt/homebrew/lib/python3.13/site-packages/freqtrade/strategy/interface.py", line 1069, in _analyze_ticker_internal
    dataframe = self.analyze_ticker(dataframe, metadata)
  File "/opt/homebrew/lib/python3.13/site-packages/freqtrade/strategy/interface.py", line 1047, in analyze_ticker
    dataframe = self.advise_indicators(dataframe, metadata)
  File "/opt/homebrew/lib/python3.13/site-packages/freqtrade/strategy/interface.py", line 1643, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sukonin/IdeaProjects/learning/trading-bot/user_data/strategies/FreqaiExampleStrategy.py", line 201, in populate_indicators
    dataframe = self.freqai.start(dataframe, metadata, self)
  File "/opt/homebrew/lib/python3.13/site-packages/freqtrade/freqai/freqai_interface.py", line 149, in start
    dk = self.start_live(dataframe, metadata, strategy, self.dk)
  File "/opt/homebrew/lib/python3.13/site-packages/freqtrade/freqai/freqai_interface.py", line 457, in start_live
    self.build_strategy_return_arrays(dataframe, dk, metadata["pair"], trained_timestamp)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.13/site-packages/freqtrade/freqai/freqai_interface.py", line 493, in build_strategy_return_arrays
    self.dd.append_model_predictions(pair, pred_df, do_preds, dk, dataframe)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.13/site-packages/freqtrade/freqai/data_drawer.py", line 366, in append_model_predictions
    df.iloc[-1, label_mean_loc] = dk.data["labels_mean"][label]
                                  ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
KeyError: 'up'

```

``` python
import logging
from functools import reduce

import numpy as np
import talib.abstract as ta
from freqtrade.strategy import IStrategy
from pandas import DataFrame
from technical import qtpylib

logger = logging.getLogger(__name__)


class FreqaiExampleStrategy(IStrategy):
    """
    Example strategy showing how the user connects their own
    IFreqaiModel to the strategy.

    Warning! This is a showcase of functionality,
    which means that it is designed to show various functions of FreqAI
    and it runs on all computers. We use this showcase to help users
    understand how to build a strategy, and we use it as a benchmark
    to help debug possible problems.

    This means this is *not* meant to be run live in production.
    """
    plot_config = {
        "main_plot": {},
        "subplots": {
            "&s-up_or_down": {"&s-up_or_down": {"color": "blue"}},
            "do_predict": {
                "do_predict": {"color": "brown"},
            },
        },
    }

    process_only_new_candles = True
    stoploss = -0.05
    use_exit_signal = True
    # this is the maximum period fed to talib (timeframe independent)
    startup_candle_count: int = 40
    can_short = True

    def feature_engineering_expand_all(
            self, dataframe: DataFrame, period: int, metadata: dict, **kwargs
    ) -> DataFrame:
        """
        *Only functional with FreqAI enabled strategies*
        This function will automatically expand the defined features on the config defined
        `indicator_periods_candles`, `include_timeframes`, `include_shifted_candles`, and
        `include_corr_pairs`. In other words, a single feature defined in this function
        will automatically expand to a total of
        `indicator_periods_candles` * `include_timeframes` * `include_shifted_candles` *
        `include_corr_pairs` numbers of features added to the model.

        All features must be prepended with `%` to be recognized by FreqAI internals.

        Access metadata such as the current pair/timeframe with:

        `metadata["pair"]` `metadata["tf"]`

        More details on how these config defined parameters accelerate feature engineering
        in the documentation at:

        https://www.freqtrade.io/en/latest/freqai-parameter-table/#feature-parameters

        https://www.freqtrade.io/en/latest/freqai-feature-engineering/#defining-the-features

        :param dataframe: strategy dataframe which will receive the features
        :param period: period of the indicator - usage example:
        :param metadata: metadata of current pair
        dataframe["%-ema-period"] = ta.EMA(dataframe, timeperiod=period)
        """

        dataframe["%-rsi-period"] = ta.RSI(dataframe, timeperiod=period)
        dataframe["%-mfi-period"] = ta.MFI(dataframe, timeperiod=period)
        dataframe["%-adx-period"] = ta.ADX(dataframe, timeperiod=period)
        dataframe["%-sma-period"] = ta.SMA(dataframe, timeperiod=period)
        dataframe["%-ema-period"] = ta.EMA(dataframe, timeperiod=period)

        bollinger = qtpylib.bollinger_bands(
            qtpylib.typical_price(dataframe), window=period, stds=2.2
        )
        dataframe["bb_lowerband-period"] = bollinger["lower"]
        dataframe["bb_middleband-period"] = bollinger["mid"]
        dataframe["bb_upperband-period"] = bollinger["upper"]

        dataframe["%-bb_width-period"] = (
                                                 dataframe["bb_upperband-period"] - dataframe["bb_lowerband-period"]
                                         ) / dataframe["bb_middleband-period"]
        dataframe["%-close-bb_lower-period"] = dataframe["close"] / dataframe["bb_lowerband-period"]

        dataframe["%-roc-period"] = ta.ROC(dataframe, timeperiod=period)

        dataframe["%-relative_volume-period"] = (
                dataframe["volume"] / dataframe["volume"].rolling(period).mean()
        )

        return dataframe

    def feature_engineering_expand_basic(
            self, dataframe: DataFrame, metadata: dict, **kwargs
    ) -> DataFrame:
        """
        *Only functional with FreqAI enabled strategies*
        This function will automatically expand the defined features on the config defined
        `include_timeframes`, `include_shifted_candles`, and `include_corr_pairs`.
        In other words, a single feature defined in this function
        will automatically expand to a total of
        `include_timeframes` * `include_shifted_candles` * `include_corr_pairs`
        numbers of features added to the model.

        Features defined here will *not* be automatically duplicated on user defined
        `indicator_periods_candles`

        All features must be prepended with `%` to be recognized by FreqAI internals.

        Access metadata such as the current pair/timeframe with:

        `metadata["pair"]` `metadata["tf"]`

        More details on how these config defined parameters accelerate feature engineering
        in the documentation at:

        https://www.freqtrade.io/en/latest/freqai-parameter-table/#feature-parameters

        https://www.freqtrade.io/en/latest/freqai-feature-engineering/#defining-the-features

        :param dataframe: strategy dataframe which will receive the features
        :param metadata: metadata of current pair
        dataframe["%-pct-change"] = dataframe["close"].pct_change()
        dataframe["%-ema-200"] = ta.EMA(dataframe, timeperiod=200)
        """
        dataframe["%-pct-change"] = dataframe["close"].pct_change()
        dataframe["%-raw_volume"] = dataframe["volume"]
        dataframe["%-raw_price"] = dataframe["close"]
        return dataframe

    def feature_engineering_standard(
            self, dataframe: DataFrame, metadata: dict, **kwargs
    ) -> DataFrame:
        """
        *Only functional with FreqAI enabled strategies*
        This optional function will be called once with the dataframe of the base timeframe.
        This is the final function to be called, which means that the dataframe entering this
        function will contain all the features and columns created by all other
        freqai_feature_engineering_* functions.

        This function is a good place to do custom exotic feature extractions (e.g. tsfresh).
        This function is a good place for any feature that should not be auto-expanded upon
        (e.g. day of the week).

        All features must be prepended with `%` to be recognized by FreqAI internals.

        Access metadata such as the current pair with:

        `metadata["pair"]`

        More details about feature engineering available:

        https://www.freqtrade.io/en/latest/freqai-feature-engineering

        :param dataframe: strategy dataframe which will receive the features
        :param metadata: metadata of current pair
        usage example: dataframe["%-day_of_week"] = (dataframe["date"].dt.dayofweek + 1) / 7
        """
        dataframe["%-day_of_week"] = dataframe["date"].dt.dayofweek
        dataframe["%-hour_of_day"] = dataframe["date"].dt.hour
        return dataframe

    def set_freqai_targets(self, dataframe: DataFrame, metadata: dict, **kwargs) -> DataFrame:
        label_period_candles = self.freqai_info["feature_parameters"]["label_period_candles"]

        # Calculate the price change
        price_change = (dataframe["close"].shift(-label_period_candles) - dataframe["close"]) / dataframe["close"]

        # Set the target based on the price change
        dataframe['&s-up_or_down'] = np.select(
            [
                price_change > 0.01,
                price_change < -0.01,
                True  # This is the else condition
            ],
            [
                'up',
                'down',
                'neutral'
            ]
        )

        self.freqai.class_names = ['up', 'down', 'neutral']
        return dataframe

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe = self.freqai.start(dataframe, metadata, self)

        return dataframe

    def populate_entry_trend(self, df: DataFrame, metadata: dict) -> DataFrame:
        enter_long_conditions = [
            df["do_predict"] == 1,
            df["&s-up_or_down"] == 'up',
        ]

        if enter_long_conditions:
            df.loc[
                reduce(lambda x, y: x & y, enter_long_conditions), ["enter_long", "enter_tag"]
            ] = (1, "long")

        enter_short_conditions = [
            df["do_predict"] == 1,
            df["&s-up_or_down"] == 'down',
        ]

        if enter_short_conditions:
            df.loc[
                reduce(lambda x, y: x & y, enter_short_conditions), ["enter_short", "enter_tag"]
            ] = (1, "short")

        return df

    def populate_exit_trend(self, df: DataFrame, metadata: dict) -> DataFrame:
        exit_long_conditions = [df["do_predict"] == 1,
                                (df['&s-up_or_down'] == 'down') | (df['&s-up_or_down'] == 'neutral')]
        if exit_long_conditions:
            df.loc[reduce(lambda x, y: x & y, exit_long_conditions), "exit_long"] = 1

        exit_short_conditions = [df["do_predict"] == 1,
                                 (df['&s-up_or_down'] == 'up') | (df['&s-up_or_down'] == 'neutral')]
        if exit_short_conditions:
            df.loc[reduce(lambda x, y: x & y, exit_short_conditions), "exit_short"] = 1

        return df

    def confirm_trade_entry(
            self,
            pair: str,
            order_type: str,
            amount: float,
            rate: float,
            time_in_force: str,
            current_time,
            entry_tag,
            side: str,
            **kwargs,
    ) -> bool:
        df, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)
        last_candle = df.iloc[-1].squeeze()

        if side == "long":
            if rate > (last_candle["close"] * (1 + 0.0025)):
                return False
        else:
            if rate < (last_candle["close"] * (1 - 0.0025)):
                return False

        return True

```

```
  "freqai": {
    "enabled": true,
    "identifier": "torch",
    "train_period_days": 30,
    "class_names": [
      "up",
      "down",
      "neutral"
    ],
    "fit_live_predictions_candles": 24,
    "backtest_period_days": 7,
    "expiration_hours": 2,
    "live_retrain_hours": 2,
    "purge_old_models": 2,
    "save_backtest_models": true,
    "write_metrics_to_disk": true,
    "activate_tensorboard": false,
    "feature_parameters": {
      "include_corr_pairlist": [
        "BTC/USDT:USDT",
        "ETH/USDT:USDT",
        "SOL/USDT:USDT",
        "XRP/USDT:USDT"
      ],
      "include_timeframes": [
        "5m"
      ],
      "label_period_candles": 5,
      "include_shifted_candles": 5,
      "DI_threshold": 0.5,
      "weight_factor": 0.5,
      "principal_component_analysis": false,
      "use_SVM_to_remove_outliers": true,
      "indicator_periods_candles": [
        10,
        20
      ],
      "noise_standard_deviation": 0.01,
      "buffer_train_data_candles": 20
    },
    "data_split_parameters": {
      "test_size": 0.2
    },
    "model_training_parameters": {
      "learning_rate": 3e-4,
      "trainer_kwargs": {
        "batch_size": 64,
        "n_epochs": 50
      },
      "model_kwargs": {
        "lstm_units": 128,
        "dropout_percent": 0.3,
        "num_lstm_layers": 3
      }
    }
  },

```

**Comment by xmatthias** [comment]
First of - there is no "class_names" in the configuration ... so that part is not necessary.

I'd also never reuse the existing class name - that's pretty dangerous and won't gurarantee that the correct strategy is used (instead of the class with the same name in another location).

---

to test, i've tried

* the hybrid strategy we provide (`freqtrade trade --strategy FreqaiExampleHybridStrategy --strategy-path freqtrade/templates  --freqaimodel CatboostClassifier --config config_examples/config_freqai.example.json`)
* the hybrid strategy with the model you're using (`freqtrade trade --strategy FreqaiExampleHybridStrategy --strategy-path freqtrade/templates --freqaimodel PyTorchMLPClassifier --config config_examples/config_freqai.example.json`)
* the hybrid strategy with your model and your config (same command as above, but with the freqAI section replaced)
* Your strategy with your configuration (though i had the strategy renamed).


The first 3 tests above do work just fine (make sure to reset the model identifier between tests or delete the model directory) - so it's something to do with your strategy.

I'd hence suggest to compare your strategy with the `FreqaiExampleHybridStrategy` (which implements the categorical approach) to find the differences.
I doubt it's something within freqtrade / freqAI - as it's working with the sample strategies just fine (also with the model you've used).

**Comment by gameinskysky** [comment]
I met same issue. Who can help?

2025-08-06 13:26:21,215 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair 
ETH/USDT: 'up'
2025-08-06 13:26:21,356 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error 'up' calling <bound method 
IStrategy._analyze_ticker_internal of <LCS_GD5_C2.LCS_GD5_C2 object at 0x0000017A055B7380>>
Traceback (most recent call last):
  File "C:\Luo\DataWave\freqtrade\freqtrade\strategy\strategy_wrapper.py", line 31, in wrapper
    return f(*args, **kwargs)
  File "C:\Luo\DataWave\freqtrade\freqtrade\strategy\interface.py", line 1216, in _analyze_ticker_internal
    dataframe = self.analyze_ticker(dataframe, metadata)
  File "C:\Luo\DataWave\freqtrade\freqtrade\strategy\interface.py", line 1194, in analyze_ticker
    dataframe = self.advise_indicators(dataframe, metadata)
  File "C:\Luo\DataWave\freqtrade\freqtrade\strategy\interface.py", line 1803, in advise_indicators
    dataframe = self.populate_indicators(dataframe, metadata)
  File "C:\Luo\DataWave\freqtrade\user_data\strategies\LCS_GD5_C2.py", line 291, in populate_indicators
    dataframe = self.freqai.start(dataframe, metadata, self)
  File "C:\Luo\DataWave\freqtrade\freqtrade\freqai\freqai_interface.py", line 149, in start
    dk = self.start_live(dataframe, metadata, strategy, self.dk)
  File "C:\Luo\DataWave\freqtrade\freqtrade\freqai\freqai_interface.py", line 467, in start_live
    self.build_strategy_return_arrays(dataframe, dk, metadata["pair"], trained_timestamp)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Luo\DataWave\freqtrade\freqtrade\freqai\freqai_interface.py", line 503, in build_strategy_return_arrays  
    self.dd.append_model_predictions(pair, pred_df, do_preds, dk, dataframe)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Luo\DataWave\freqtrade\freqtrade\freqai\data_drawer.py", line 368, in append_model_predictions
    df.iloc[-1, label_mean_loc] = dk.data["labels_mean"][label]
                                  ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
KeyError: 'up'

**Comment by stash86** [comment]
please open new issue and give all relevant data required for us to be able to help you
