### ISSUE TITLE
Analyse per epoch flag doesn't work in populate_indicators

### ISSUE THREAD

**Issue by snussik** [freqtrade/freqtrade#10904]
## Describe your environment

  * Operating system: macos 14.6.1 (23G93)
  * Python Version: 3.11.3
  * CCXT version: 4.3.85
  * Freqtrade Version: freqtrade 2024.8-dev-201a5c06f)
  
## Your question

If I create categorical instance:

```python
    my_cat_def = 1
    my_cat = CategoricalParameter([1, 2, 3, 4, 5], default=my_cat_def, space="buy")

```

and then in populate_indicators() check it:

```python
my_cat_val = self.my_cat.value

        if self.config.get("runmode") == RunMode.HYPEROPT:

            if my_cat_val != self.my_cat_def:
                logger.info("===== HYPEROPT EPOCH =====")
                logger.info(f"New mycat val {my_cat_val}")
                self.my_cat_def = my_cat_val

```

nothing happens.

So I think that hyperoptables dont take effect on each epoch during backtesting.

The run command is 

```bash
freqtrade hyperopt --hyperopt-loss SharpeHyperOptLossDaily --spaces buy --strategy LevelsStrategy --config ./user_data/config.json -e 1000 --analyze-per-epoch --timerange 20230101-20230401 

```

**Comment by xmatthias** [comment]
your test is faulty.
If you print it unconditionally, it'll work (or if you use `-j 1` to disable multiprocessing.).

If you assign a value to "self." - then that's only valid for the current epoch - but not for the next - so it's unsuitable to track changes.

**Comment by snussik** [comment]
@xmatthias 

I've added my_cat_def as global variable:
1. moved it out of the strategy class scope;
2. defined `global my_cat_def_global` inside `populate_indicators` function but it didn't helped. Nothing've changed.

The reason I make this check is that my categorical parameters don't work inside `populate_indicators` function  (information timeframe if it's important).


This is how my Categorical params defined (a lille bit complex as sometimes freqtrade crashes on hyperopt if I use tuple directly):

```python

def powerset(iterable):
    "powerset([1,2,3]) --> () (1,) (2,) (3,) (1,2) (1,3) (2,3) (1,2,3)"
    s = list(iterable)
    return chain.from_iterable(combinations(s, r) for r in range(len(s) + 1))

def get_all_params(list_variants: list):
    all_comb = set(powerset(list_variants))
    return [tuple([combo]) for combo in all_comb if combo]


def convert_numbers(num_list: list) -> str:
    nums = {
        0: "zero",
        1: "one",
        2: "two",
        3: "three",
        4: "four",
        5: "five",
        6: "six",
        7: "seven",
        8: "eight",
        9: "nine",
        10: "ten",
        11: "eleven",
        12: "twelve",
    }
    res = []

    for num in num_list:

        if isinstance(num, (int)):
            res.append(nums[num])
        if isinstance(num, (tuple)):
            for n in num:
                res.append(nums[n])

    return "_".join(res)


def get_dict_from_params(list_variants: list):
    d = {}
    all_params = get_all_params(list_variants)

    for var in all_params:
        d.update({convert_numbers(var): var})

    return d


# HYPEROPTABLE
start_candle_params = [0, 1, 10]
    start_candle_params_dict = get_dict_from_params(start_candle_params)
    start_keys = list(start_candle_params_dict.keys())
    start_candle_type = CategoricalParameter(
        start_keys,
        default="zero_one_ten",
        # default=start_keys[0],
        space="buy",
    )


```

**Comment by xmatthias** [comment]
You cannot store data in the strategy (or at module level - the exact location is not the point) and expect one epoch to know about the other.
If that **were** to work  - you'd cause access problems as hyperopt runs backtesting in **parallel** - as well as leakage of values between epochs.

Fortunately, this doesn't happen (that's by design) and epochs are isolated from each other - so whatever you assign within one epoch will be available for that individual epoch - but **not** for other epochs.

To some degree, this isolation is "lightened" if you don't run parallel epochs (`-j 1`) - as then hyperopt runs sequentially instead of in parallel.


now log / print is somewhat hindered by multiprocessing - so you'll not be able to print/log to actually see this (a logging "missing feature" in python if you will) - but running hyperopt with `-j 1` does show that the values do change according to plan.

**Comment by snussik** [comment]
@xmatthias  and are there any methods to check or to log on each epoch what value of categorical parameters is used? As I have a large vectors and the number of combinations should be great but I'm getting scikit warning  `The objective has been evaluated at this point before.` very quick. 
I think that the problem can be that my categorical parameters are tuples and something goes wrong with this. As if I try to use tupples directly I'm getting error related to catagorical parameter check:

```bash

Traceback (most recent call last):
  File "/Users/s/GIT/ft/freqtrade/main.py", line 45, in main
    return_code = args["func"](args)
                  ^^^^^^^^^^^^^^^^^^
  File "/Users/s/GIT/ft/freqtrade/commands/optimize_commands.py", line 109, in start_hyperopt
    hyperopt.start()
  File "/Users/s/GIT/ft/freqtrade/optimize/hyperopt.py", line 661, in start
    asked, is_random = self.get_asked_points(n_points=current_jobs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/s/GIT/ft/freqtrade/optimize/hyperopt.py", line 554, in get_asked_points
    asked = unique_list(self.opt.ask(n_points=n_points * 5 if i > 0 else n_points))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/s/GIT/ft/.venv/lib/python3.11/site-packages/skopt/optimizer/optimizer.py", line 395, in ask
    x = opt.ask()
        ^^^^^^^^^
  File "/Users/s/GIT/ft/.venv/lib/python3.11/site-packages/skopt/optimizer/optimizer.py", line 367, in ask
    return self._ask()
           ^^^^^^^^^^^
  File "/Users/s/GIT/ft/.venv/lib/python3.11/site-packages/skopt/optimizer/optimizer.py", line 446, in _ask
    min_delta_x = min([self.space.distance(next_x, xi)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/s/GIT/ft/.venv/lib/python3.11/site-packages/skopt/optimizer/optimizer.py", line 446, in <listcomp>
    min_delta_x = min([self.space.distance(next_x, xi)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/s/GIT/ft/.venv/lib/python3.11/site-packages/skopt/space/space.py", line 1138, in distance
    distance += dim.distance(a, b)
                ^^^^^^^^^^^^^^^^^^
  File "/Users/s/GIT/ft/.venv/lib/python3.11/site-packages/skopt/space/space.py", line 743, in distance
    if not (a in self and b in self):
            ^^^^^^^^^
  File "/Users/s/GIT/ft/.venv/lib/python3.11/site-packages/skopt/space/space.py", line 720, in __contains__
    return point in self.categories
           ^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by xmatthias** [comment]
Tuples / lists are unsupported by scikit-optimize (it's a bug, but not one that's going to be fixed).

Your best bet in that case is to concat it to a string value - at least that's the combination i came across.

Obviously you can also log values at freqtrade level - but the log will only show with `-j 1`.

**Comment by snussik** [comment]
@xmatthias I ran my code with -j flag and printed my categorical conditions on each epoch. And now I see that they do not change on each epoch count:

```bash

2024-11-10 16:42:34,937 - LevelsStrategy - INFO - dict_values([((0, 1),), ((0, 1),), ((0, 1),), ((0, 1, 3, 4),), ((0,),), ((0, 1),)])
2024-11-10 16:42:36,456 - LevelsStrategy - INFO - dict_values([((0, 1),), ((0, 1),), ((0, 1),), ((0, 1, 3, 4),), ((0,),), ((0, 1),)])
2024-11-10 16:42:37,981 - LevelsStrategy - INFO - dict_values([((0, 1),), ((0, 1),), ((0, 1),), ((0, 1, 3, 4),), ((0,),), ((0, 1),)])
2024-11-10 16:42:39,513 - LevelsStrategy - INFO - dict_values([((0, 1),), ((0, 1),), ((0, 1),), ((0, 1, 3, 4),), ((0,),), ((0, 1),)])
2024-11-10 16:42:41,068 - LevelsStrategy - INFO - dict_values([((0, 1),), ((0, 1),), ((0, 1),), ((0, 1, 3, 4),), ((0,),), ((0, 1),)])
2024-11-10 16:42:42,594 - LevelsStrategy - INFO - dict_values([((0, 1),), ((0, 1),), ((0, 1),), ((0, 1, 3, 4),), ((0,),), ((0, 1),)])
2024-11-10 16:42:44,123 - LevelsStrategy - INFO - dict_values([((0, 1),), ((0, 1),), ((0, 1),), ((0, 1, 3, 4),), ((0,),), ((0, 1),)])
2024-11-10 16:42:45,661 - LevelsStrategy - INFO - dict_values([((0, 1),), ((0, 1),), ((0, 1),), ((0, 1, 3, 4),), ((0,),), ((0, 1),)])
2024-11-10 16:42:47,197 - LevelsStrategy - INFO - dict_values([((0, 1),), ((0, 1),), ((0, 1),), ((0, 1, 3, 4),), ((0,),), ((0, 1),)])
2024-11-10 16:42:48,728 - LevelsStrategy - INFO - dict_values([((0, 1),), ((0, 1),), ((0, 1),), ((0, 1, 3, 4),), ((0,),), ((0, 1),)])
2024-11-10 16:42:50,257 - LevelsStrategy - INFO - dict_values([((0, 1),), ((0, 1),), ((0, 1),), ((0, 1, 3, 4),), ((0,),), ((0, 1),)])
2024-11-10 16:42:51,817 - LevelsStrategy - INFO - dict_values([((0, 1),), ((0, 1),), ((0, 1),), ((0, 1, 3, 4),), ((0,),), ((0, 1),)])
2024-11-10 16:42:53,345 - LevelsStrategy - INFO - dict_values([((0, 1),), ((0, 1),), ((0, 1),), ((0, 1, 3, 4),), ((0,),), ((0, 1),)])
2024-11-10 16:42:54,872 - LevelsStrategy - INFO - dict_values([((0, 1),), ((0, 1),), ((0, 1),), ((0, 1, 3, 4),), ((0,),), ((0, 1),)])
2024-11-10 16:42:56,397 - LevelsStrategy - INFO - dict_values([((0, 1),), ((0, 1),), ((0, 1),), ((0, 1, 3, 4),), ((0,),), ((0, 1),)])
2024-11-10 16:42:57,924 - LevelsStrategy - INFO - dict_values([((0, 1),), ((0, 1),), ((0, 1),), ((0, 1, 3, 4),), ((0,),), ((0, 1),)])
2024-11-10 16:42:59,480 - LevelsStrategy - INFO - dict_values([((0, 1),), ((0, 1),), ((0, 1),), ((0, 1, 3, 4),), ((0,),), ((0, 1),)])
2024-11-10 16:43:01,005 - LevelsStrategy - INFO - dict_values([((0, 1),), ((0, 1),), ((0, 1),), ((0, 1, 3, 4),), ((0,),), ((0, 1),)])
2024-11-10 16:43:02,558 - LevelsStrategy - INFO - dict_values([((0, 1),), ((0, 1),), ((0, 1),), ((0, 1, 3, 4),), ((0,),), ((0, 1),)])
2024-11-10 16:43:04,089 - LevelsStrategy - INFO - dict_values([((0, 1),), ((0, 1),), ((0, 1),), ((0, 1, 3, 4),), ((0,),), ((0, 1),)])
2024-11-10 16:43:05,622 - LevelsStrategy - INFO - dict_values([((0, 1),), ((0, 1),), ((0, 1),), ((0, 1, 3, 4),), ((0,),), ((0, 1),)])
2024-11-10 16:43:07,151 - LevelsStrategy - INFO - dict_values([((0, 1),), ((0, 1),), ((0, 1),), ((0, 1, 3, 4),), ((0,),), ((0, 1),)])
2024-11-10 16:43:08,677 - LevelsStrategy - INFO - dict_values([((0, 1),), ((0, 1),), ((0, 1),), ((0, 1, 3, 4),), ((0,),), ((0, 1),)])
2024-11-10 16:43:10,210 - LevelsStrategy - INFO - dict_values([((0, 1),), ((0, 1),), ((0, 1),), ((0, 1, 3, 4),), ((0,),), ((0, 1),)])
2024-11-10 16:43:11,761 - LevelsStrategy - INFO - dict_values([((0, 1),), ((0, 1),), ((0, 1),), ((0, 1, 3, 4),), ((0,),), ((0, 1),)])

```

I store them in a such way:

```python

 conditions = {
        "param_name" : categirical_param_dict[categirical_param.value]
    }

```
and then:

```python

for column, values in self.conditions.items():
   ...

```

**Comment by xmatthias** [comment]
the values will change if it's used correctly (i verified that this morning).

If that's not happening for you - then you're probably doing something wrong.
without context (where is your code, it's just 2 lines) - there's nothing i can do to help you.

**Comment by snussik** [comment]
@xmatthias I think that I have found the reason: if I create`conditions` dict out of strategy class function (just below the categorical parameters declaration) the values don't change. But if I create this object inside function - then categirical_param.value - changing.

The issue can be closed as it can be solved in a such manner, but globally I think it's not right as if I need this conditions dict in different functions I have to create code duplication.

p.s. I remember persistent storage issue but don't think that its the same. 

upd. I think it could be great to have something like this that could work correctly:

```python
MappedParameter = TypeAlias dict[Any, Type[BaseParameter]]
```

**Comment by xmatthias** [comment]
> The issue can be closed as it can be solved in a such manner, but globally I think it's not right as if I need this conditions dict in different functions I have to create code duplication.

You're wrong in this regards - it's working as intended.

We intentionally don't descent into child attributes or properties - as the performance penalty for that is bigger than the potential gain, which can be easily worked around by actually **reading the documentation**.


hyperopt will **only** call `populate_entry_trend()` and `populate_exit_trend()` - so `.value` is expected to change when used from within there.
`.value` will change in `populate_indicators()` **only** when used with `--analyze-per-epoch` - otherwise the correct usage is with `.range`.
Callbacks are obviously always called - at that point, the value will be different.

`.value` will not change if you're using it at class level (this is only called once) - which is essentially what you're doing.

If you need global objects - you can easily work around this by either calling instance functions that provide the necessary information from a supported scope - or by using properties [(protections serve as sample)](https://www.freqtrade.io/en/stable/hyperopt/#optimizing-an-indicator-parameter).
