### ISSUE TITLE
Unable to open position in Futures Binance

### ISSUE THREAD

**Issue by kleanth11** [freqtrade/freqtrade#10905]
## Describe your environment

  * Operating system: __ubuntu__
  * Python Version: ___Python 3.10.12__ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: __the latest__ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

Ive ran for the past 3 months in dry mode various strategies in futures binance and never had a problem, now that i want to try the live mode im running into a problem. After moving my money from spot to futures i created the API key(enable reading, enable Futures) and i ran the bot which ran successfully but when i try to "/forcelong" any coin i get this message : 

```
test         | Traceback (most recent call last):
test         |   File "/freqtrade/freqtrade/rpc/telegram.py", line 1323, in _force_enter_action
test         |     await loop.run_in_executor(None, _force_enter)
test         |   File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
test         |     result = self.fn(*self.args, **self.kwargs)
test         |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
test         |   File "/freqtrade/freqtrade/rpc/telegram.py", line 65, in wrapper
test         |     return func(*args, **kwargs)
test         |            ^^^^^^^^^^^^^^^^^^^^^
test         |   File "/freqtrade/freqtrade/rpc/telegram.py", line 1319, in _force_enter
test         |     self._rpc._rpc_force_entry(pair, price, order_side=order_side)
test         |   File "/freqtrade/freqtrade/rpc/rpc.py", line 1023, in _rpc_force_entry
test         |     raise RPCException(f"Failed to enter position for {pair}.")
test         | freqtrade.rpc.rpc.RPCException: Failed to enter position for BTC/USDT:USDT.
```
and it fails to enter the position. 
Also, when i run the command balance on telegram it shows that the balance is 0 when there are 50$ inside the future account.
Here is my config file if it helps : 
```
    "max_open_trades": 4,
    "stake_currency": "USDT",
    "stake_amount": "unlimited",
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "timeframe": "15m",
    "dry_run": false,
    "dry_run_wallet": 1000,
    "cancel_open_orders_on_exit": false,
    "trading_mode": "futures",
    "margin_mode": "isolated",
```

for the rest of the config file everything is the same. The asset mode is single mode and the futures margin balance are under USD-M. I wanted to ask if anyone else ever worked with binance futures or if someone has some documents and suggests to make for me to work on solving it.

**Comment by stash86** [comment]
The balance is 0. That's the important issue. Make sure you put the money in the right wallet

**Comment by xmatthias** [comment]
well unless money shows up in your account - there's something wrong with your config - and testing entering positions is kinda pointless.

Either API keys are wrong (check startup logs, maybe they're limited to the wrong IP, ... ) - or you're using subaccounts and the API key is for a different subaccount.
At any rate - startup logs will contain this - as the bot starts with a "/balance" call to the exchange - which will fail if something is wrong with the API key - or returns 0 (check balance) - which suggests the api key is correctish - BUT it's not for the account you've got money in.

**Comment by kleanth11** [comment]
Thank you for your replies! At first i was worried that my configuration wasnt right or that i had to include some other option but the bot pointing to a different balance sounds very reasonable as binance per se has a bunch of different places you can put your money into. Ill work on trying to point the bot to the current balance and if its possible id like to have this issue opened for future updates.

**Comment by CaueSampaio** [comment]
@kleanth11 i've just found out that for futures trade you need to send money from your spot to your Futures USDⓈ wallet.

**Comment by kleanth11** [comment]
yeah i have already done that but still no good progress , the api keys are working but i still seem to get my balance equal to 0. What libraries does freqtrade use to connect to the binance api? was it the ccxt?

**Comment by xmatthias** [comment]
With the balance in the correct account (Futures -> USD-M), the api keys set to access that account - the bot sees the balance perfectly fine - and immediately on startup.

![Image](https://github.com/user-attachments/assets/690e0ee1-91ec-4634-830e-d51f2bb6a1bc)

Possible problematic points
* API Key not set to enable Futures (errors in the log??)
* The API key is somehow invalid (wrong IP lock, copy/past error, key/secret inverted) -> errors in the log
* the bot is not configured to trade futures (`"trading_mode": "futures"` "margin_mode": "isolated"). This is also shown in the startup logs.

I fear there's little we can do to help you with this - you can maybe try to post the startup logs (logs up to the first "bot heartbeat") - maybe we can identify something that's off - but more likely, it's account / api key related.

**Comment by kleanth11** [comment]
here are the logs i get till the bot heartbeat: 
```
2024-11-13 09:28:32,886 - freqtrade - INFO - freqtrade 2024.10
2024-11-13 09:28:33,142 - numexpr.utils - INFO - NumExpr defaulting to 8 threads.
2024-11-13 09:28:34,845 - freqtrade.worker - INFO - Starting worker 2024.10
2024-11-13 09:28:34,845 - freqtrade.configuration.load_config - INFO - Using config: user_data/config_leverkusen.json ...
2024-11-13 09:28:34,846 - freqtrade.loggers - INFO - Verbosity set to 0
2024-11-13 09:28:34,846 - freqtrade.configuration.configuration - INFO - Runmode set to live.
2024-11-13 09:28:34,846 - freqtrade.configuration.configuration - INFO - Using additional Strategy lookup path: user_data/strategies/
2024-11-13 09:28:34,846 - freqtrade.configuration.configuration - WARNING - `force_entry_enable` RPC message enabled.
2024-11-13 09:28:34,846 - freqtrade.configuration.configuration - INFO - Dry run is disabled
2024-11-13 09:28:34,846 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:///tradesv3.sqlite"
2024-11-13 09:28:34,846 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 4 ...
2024-11-13 09:28:34,847 - freqtrade.configuration.configuration - INFO - Using user-data directory: ...
2024-11-13 09:28:34,847 - freqtrade.configuration.configuration - INFO - Using data directory: ...
2024-11-13 09:28:34,847 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2024-11-13 09:28:34,860 - freqtrade.exchange.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2024-11-13 09:28:34,860 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2024-11-13 09:28:34,875 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy .... from '..../user_data/strategies/.....py'...
2024-11-13 09:28:34,875 - freqtrade.strategy.hyper - INFO - Found no parameter file.
2024-11-13 09:28:34,875 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 15m.
2024-11-13 09:28:34,875 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2024-11-13 09:28:34,875 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: unlimited.
2024-11-13 09:28:34,875 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'entry': 1, 'exit': 1, 'exit_timeout_count': 0, 'unit': 'minutes'}.
2024-11-13 09:28:34,875 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'max_open_trades' with value in config file: 4.
2024-11-13 09:28:34,875 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 0.4}
2024-11-13 09:28:34,875 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 15m
2024-11-13 09:28:34,875 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.3
2024-11-13 09:28:34,875 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: True
2024-11-13 09:28:34,875 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive: 0.001
2024-11-13 09:28:34,875 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.07
2024-11-13 09:28:34,875 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: True
2024-11-13 09:28:34,875 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2024-11-13 09:28:34,875 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: True
2024-11-13 09:28:34,875 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'entry': 'limit', 'exit': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False, 'stoploss_on_exchange_interval': 60}
2024-11-13 09:28:34,876 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'entry': 'GTC', 'exit': 'GTC'}
2024-11-13 09:28:34,876 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2024-11-13 09:28:34,876 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: unlimited
2024-11-13 09:28:34,876 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 200
2024-11-13 09:28:34,876 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'entry': 1, 'exit': 1, 'exit_timeout_count': 0, 'unit': 'minutes'}
2024-11-13 09:28:34,876 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_exit_signal: True
2024-11-13 09:28:34,876 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_only: False
2024-11-13 09:28:34,876 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_entry_signal: False
2024-11-13 09:28:34,876 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_offset: 0.01
2024-11-13 09:28:34,876 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2024-11-13 09:28:34,876 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2024-11-13 09:28:34,876 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: False
2024-11-13 09:28:34,876 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1
2024-11-13 09:28:34,876 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_open_trades: 4
2024-11-13 09:28:34,876 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2024-11-13 09:28:34,878 - freqtrade.exchange.exchange - INFO - Using CCXT 4.4.24
2024-11-13 09:28:34,879 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}}
2024-11-13 09:28:34,890 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}}
2024-11-13 09:28:34,901 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2024-11-13 09:28:43,122 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2024-11-13 09:28:44,266 - freqtrade.wallets - INFO - Wallets synced.
2024-11-13 09:28:44,781 - freqtrade.rpc.rpc_manager - INFO - Enabling rpc.telegram ...
2024-11-13 09:28:44,921 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist VolumePairList from '..../VolumePairList.py'...
2024-11-13 09:28:44,923 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist AgeFilter from '..../AgeFilter.py'...
2024-11-13 09:28:44,927 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist PriceFilter from '..../PriceFilter.py'...
2024-11-13 09:28:44,928 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist SpreadFilter from '..../SpreadFilter.py'...
2024-11-13 09:28:44,933 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist RangeStabilityFilter from '..../rangestabilityfilter.py'...
2024-11-13 09:28:44,937 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist VolatilityFilter from '..../VolatilityFilter.py'...
2024-11-13 09:28:44,982 - freqtrade.rpc.telegram - INFO - rpc.telegram is listening for following commands: [['status'], ['profit'], ['balance'], ['start'], ['stop'], ['forceexit', 'forcesell', 'fx'], ['forcebuy', 'forcelong'], ['forceshort'], ['reload_trade'], ['trades'], ['delete'], ['cancel_open_order', 'coo'], ['performance'], ['buys', 'entries'], ['exits', 'sells'], ['mix_tags'], ['stats'], ['daily'], ['weekly'], ['monthly'], ['count'], ['locks'], ['delete_locks', 'unlock'], ['reload_conf', 'reload_config'], ['show_conf', 'show_config'], ['stopbuy', 'stopentry'], ['whitelist'], ['blacklist'], ['bl_delete', 'blacklist_delete'], ['logs'], ['edge'], ['health'], ['help'], ['version'], ['marketdir'], ['order'], ['list_custom_data']]
2024-11-13 09:28:45,290 - telegram.ext.Application - INFO - Application started
2024-11-13 09:28:46,557 - VolumePairList - INFO - Pair BNB/USDT:USDT in your blacklist. Removing it from whitelist...
2024-11-13 09:28:46,557 - VolumePairList - INFO - Pair STORJ/USDT:USDT in your blacklist. Removing it from whitelist...
2024-11-13 09:28:46,558 - VolumePairList - INFO - Pair REEF/USDT:USDT in your blacklist. Removing it from whitelist...
2024-11-13 09:28:46,558 - VolumePairList - INFO - Pair STG/USDT:USDT in your blacklist. Removing it from whitelist...
2024-11-13 09:28:52,234 - AgeFilter - INFO - Removed PNUT/USDT:USDT from whitelist, because age 2 is less than 10 days
2024-11-13 09:28:52,235 - AgeFilter - INFO - Removed ACT/USDT:USDT from whitelist, because age 2 is less than 10 days
2024-11-13 09:28:52,235 - AgeFilter - INFO - Validated 18 pairs.
2024-11-13 09:29:02,567 - freqtrade.plugins.pairlistmanager - INFO - Whitelist with 18 pairs: ['BTC/USDT:USDT', 'DOGE/USDT:USDT', 'ETH/USDT:USDT', 'SOL/USDT:USDT', 'XRP/USDT:USDT', '1000PEPE/USDT:USDT', '1000SHIB/USDT:USDT', 'SUI/USDT:USDT', 'NEIRO/USDT:USDT', '1000BONK/USDT:USDT', 'WIF/USDT:USDT', 'ADA/USDT:USDT', 'WLD/USDT:USDT', '1000FLOKI/USDT:USDT', 'AVAX/USDT:USDT', 'GOAT/USDT:USDT', 'APT/USDT:USDT', 'ORDI/USDT:USDT']
2024-11-13 09:29:02,568 - freqtrade.strategy.hyper - INFO - Strategy Parameter: base_nb_candles_buy = ..
2024-11-13 09:29:02,568 - freqtrade.strategy.hyper - INFO - Strategy Parameter: ewo_high = ...
2024-11-13 09:29:02,568 - freqtrade.strategy.hyper - INFO - Strategy Parameter: ewo_high_2 = ...
2024-11-13 09:29:02,568 - freqtrade.strategy.hyper - INFO - Strategy Parameter: ewo_low = ...
2024-11-13 09:29:02,568 - freqtrade.strategy.hyper - INFO - Strategy Parameter: lookback_candles = ...
2024-11-13 09:29:02,568 - freqtrade.strategy.hyper - INFO - Strategy Parameter: low_offset = ...
2024-11-13 09:29:02,569 - freqtrade.strategy.hyper - INFO - Strategy Parameter: low_offset_2 = ...
2024-11-13 09:29:02,569 - freqtrade.strategy.hyper - INFO - Strategy Parameter: profit_threshold = ...
2024-11-13 09:29:02,569 - freqtrade.strategy.hyper - INFO - Strategy Parameter: rsi_buy = ...
2024-11-13 09:29:02,569 - freqtrade.strategy.hyper - INFO - Strategy Parameter: rsi_fast_buy = ...
2024-11-13 09:29:02,569 - freqtrade.strategy.hyper - INFO - Strategy Parameter: base_nb_candles_sell = ...
2024-11-13 09:29:02,569 - freqtrade.strategy.hyper - INFO - Strategy Parameter: high_offset = ...
2024-11-13 09:29:02,569 - freqtrade.strategy.hyper - INFO - Strategy Parameter: high_offset_2 = ...
2024-11-13 09:29:02,569 - freqtrade.strategy.hyper - INFO - No params for protection found, using default values.
2024-11-13 09:29:02,570 - freqtrade.resolvers.iresolver - INFO - Using resolved protection LowProfitPairs from '....low_profit_pairs.py'...
2024-11-13 09:29:02,571 - freqtrade.resolvers.iresolver - INFO - Using resolved protection MaxDrawdown from '....max_drawdown_protection.py'...
2024-11-13 09:29:02,571 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'running'}
2024-11-13 09:29:02,571 - freqtrade.worker - INFO - Changing state to: RUNNING
2024-11-13 09:29:02,571 - freqtrade.util.migrations.binance_mig - WARNING - Migrating binance futures pairs in database.
2024-11-13 09:29:02,579 - freqtrade.util.migrations.binance_mig - WARNING - Done migrating binance futures pairs in database.
2024-11-13 09:29:02,593 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': "*Exchange:* `binance`\n*Stake per trade:* `unlimited USDT`\n*Minimum ROI:* `{'0': 0.4}`\n*Trailing Stoploss:* `-0.3`\n*Position adjustment:* `Off`\n*Timeframe:* `15m`\n*Strategy:* `....`"}
2024-11-13 09:29:02,594 - freqtrade.rpc.telegram - INFO - Notification 'startup' not sent.
2024-11-13 09:29:02,594 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': "Searching for USDT pairs to buy and sell based on [{'VolumePairList': 'VolumePairList - top 20 volume pairs.'}, {'AgeFilter': 'AgeFilter - Filtering pairs with age less than 10 days'}, {'PriceFilter': 'PriceFilter - Filtering pairs priced below 1.0%.'}, {'SpreadFilter': 'SpreadFilter - Filtering pairs with ask/bid diff above 0.50%.'}, {'RangeStabilityFilter': 'RangeStabilityFilter - Filtering pairs with rate of change below 0.01 over the last days.'}, {'VolatilityFilter': 'VolatilityFilter - Filtering pairs with volatility range 0.05-0.5  the last 10 days.'}]"}
2024-11-13 09:29:02,594 - freqtrade.rpc.telegram - INFO - Notification 'startup' not sent.
2024-11-13 09:29:02,594 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': 'Using Protections: \nLowProfitPairs - Low Profit Protection, locks pairs with profit < -0.05 within 60 candles.\nMaxDrawdown - Max drawdown protection, stop trading if drawdown is > 0.2 within 24 candles.'}
2024-11-13 09:29:02,594 - freqtrade.rpc.telegram - INFO - Notification 'startup' not sent.
2024-11-13 09:29:02,599 - freqtrade.freqtradebot - INFO - Updating 0 open orders.
2024-11-13 09:29:08,100 - freqtrade.worker - INFO - Bot heartbeat. PID=27587, version='2024.10', state='RUNNING'
```
could you pls tell me the permissions you enabled to the api key, maybe is an error of permission because clearly it works for you and that a very good thing. My api key permission: Enable reading, enable futures, enable Permits Universal Transfer.

**Comment by xmatthias** [comment]
My key has spot trading enabled as well (but doesn't have universal transfer) - but that's mainly because i use it to test both spot and futures.

I don't **think** that's a requirement - but might be worth a try for sure.

**Comment by moinonin** [comment]
are in EU or EEA? I reckon that is the main issue if that is the case since binance stopped supporting single asset mode which freetrader works with

**Comment by kleanth11** [comment]
my country is in non of those two, but im also having problems with my own binance account at my country at the moment so that could be a factor to this mess for futures. Ill update as soon as i have smth valuable to add to this issue.Thank you for such support so far!

**Comment by xmatthias** [comment]
I'll be closing this here for now. 
Feel free to comment below if there's something we can help you with - but at this point, i'd not know how to help you further - as it seems like binance support might be the better option - at least for now.
