### ISSUE TITLE
The bot can not run in live-mode , only dry-mode is working

### ISSUE THREAD

**Issue by Limitless-shit** [freqtrade/freqtrade#10935]
## Describe your environment

  * Operating system: Ubuntu 24.04.1 LTS
  * Python Version: Python 3.12.3 (`python -V`)
  * CCXT version: ccxt==4.4.24(`pip freeze | grep ccxt`)
  * Freqtrade Version: 2014.10(`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:
The bot can not run in live-mode , only dry-mode is working 

### Steps to reproduce:
i change my config : dry_run: false 

  
### Observed Results:

  *  the bot can not start 

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
freqtrade  | 2024-11-14 13:40:04,270 - freqtrade.exchange.common - WARNING - _load_async_markets() returned exception: "Error in reload_markets due to AuthenticationError. Message: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}". Retrying still for 3 times.
freqtrade  | 2024-11-14 13:40:04,472 - freqtrade.exchange.common - WARNING - _load_async_markets() returned exception: "Error in reload_markets due to AuthenticationError. Message: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}". Retrying still for 2 times.
freqtrade  | 2024-11-14 13:40:04,678 - freqtrade.exchange.common - WARNING - _load_async_markets() returned exception: "Error in reload_markets due to AuthenticationError. Message: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}". Retrying still for 1 times.
freqtrade  | 2024-11-14 13:40:04,862 - freqtrade.exchange.common - WARNING - _load_async_markets() returned exception: "Error in reload_markets due to AuthenticationError. Message: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}". Giving up.
freqtrade  | 2024-11-14 13:40:04,863 - freqtrade.exchange.exchange - ERROR - Could not load markets.
freqtrade  | Traceback (most recent call last):
freqtrade  |   File "/freqtrade/freqtrade/exchange/exchange.py", line 626, in _api_reload_markets
freqtrade  |     return await self._api_async.load_markets(reload=reload, params={})
freqtrade  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
freqtrade  |   File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/async_support/base/exchange.py", line 287, in load_markets
freqtrade  |     result = await self.markets_loading
freqtrade  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^
freqtrade  |   File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/async_support/base/exchange.py", line 272, in load_markets_helper
freqtrade  |     currencies = await self.fetch_currencies()
freqtrade  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
freqtrade  |   File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/async_support/binance.py", line 2701, in fetch_currencies
freqtrade  |     results = await asyncio.gather(*promises)
freqtrade  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
freqtrade  |   File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/async_support/binance.py", line 10932, in request
freqtrade  |     response = await self.fetch2(path, api, method, params, headers, body, config)
freqtrade  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
freqtrade  |   File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/async_support/base/exchange.py", line 864, in fetch2
freqtrade  |     raise e
freqtrade  |   File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/async_support/base/exchange.py", line 855, in fetch2
freqtrade  |     return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
freqtrade  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
freqtrade  |   File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/async_support/base/exchange.py", line 254, in fetch
freqtrade  |     self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
freqtrade  |   File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/async_support/binance.py", line 10900, in handle_errors
freqtrade  |     self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
freqtrade  |   File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/base/exchange.py", line 4481, in throw_exactly_matched_exception
freqtrade  |     raise exact[string](message)
freqtrade  | ccxt.base.errors.AuthenticationError: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}
freqtrade  | 
freqtrade  | The above exception was the direct cause of the following exception:
freqtrade  | 
freqtrade  | Traceback (most recent call last):
freqtrade  |   File "/freqtrade/freqtrade/exchange/common.py", line 181, in wrapper
freqtrade  |     return f(*args, **kwargs)
freqtrade  |            ^^^^^^^^^^^^^^^^^^
freqtrade  |   File "/freqtrade/freqtrade/exchange/exchange.py", line 638, in _load_async_markets
freqtrade  |     markets = self.loop.run_until_complete(self._api_reload_markets(reload=reload))
freqtrade  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
freqtrade  |   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
freqtrade  |     return future.result()
freqtrade  |            ^^^^^^^^^^^^^^^
freqtrade  |   File "/freqtrade/freqtrade/exchange/exchange.py", line 630, in _api_reload_markets
freqtrade  |     raise TemporaryError(
freqtrade  | freqtrade.exceptions.TemporaryError: Error in reload_markets due to AuthenticationError. Message: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}

**Comment by xmatthias** [comment]
> `ccxt.base.errors.AuthenticationError: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}`

The message here is 100% clear.
Your API key is invalid - so you either forgot to add the API key, made a copy/paste error (spaces in front / at the back, switched secret and key), or the IP restrictions on the API key don't include the IP address the bot is connecting from.
