### ISSUE TITLE
KeyError: 'minNotional'

### ISSUE THREAD

**Issue by jechaviz** [freqtrade/freqtrade#10959]
## Environment

  * Operating system: Windows
  * Python Version: 3.11.9
  * CCXT version: 4.3.16
  * Freqtrade Version: 2024.10
  * Exchange: MEXC
  
## Describe the problem:

ERROR - Fatal exception!
  File "C:\git\freqtrade\freqtrade\exchange\exchange.py", line 3212, in parse_leverage_tier
    "minNotional": tier["minNotional"],
                   ~~~~^^^^^^^^^^^^^^^
KeyError: 'minNotional'

### Steps to reproduce:

 freqtrade download-data --config config.json --days 999 -t 5m 15m 30m ih 2h 4h 1d 1w
   
### Observed Results:

  * What happened? Got a fatal exception
  * Get data

### Relevant code exceptions or logs

  ```
2024-11-19 11:48:15,433 - freqtrade - INFO - freqtrade 2024.10
2024-11-19 11:48:16,258 - numexpr.utils - INFO - NumExpr defaulting to 8 threads.
2024-11-19 11:48:19,094 - freqtrade.configuration.load_config - INFO - Using config: config.json ...
2024-11-19 11:48:19,102 - freqtrade.loggers - INFO - Verbosity set to 0
2024-11-19 11:48:19,104 - freqtrade.configuration.configuration - INFO - Using user-data directory: C:\git\freqtrade\user_data ...
2024-11-19 11:48:19,104 - freqtrade.configuration.configuration - INFO - Using data directory: C:\git\freqtrade\user_data\data\mexc ...
2024-11-19 11:48:19,105 - freqtrade.configuration.configuration - INFO - timeframes --timeframes: ['5m', '15m', '30m', 'ih', '2h', '4h', '1d', '1w']
2024-11-19 11:48:19,105 - freqtrade.configuration.configuration - INFO - Detected --days: 999
2024-11-19 11:48:19,107 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2024-11-19 11:48:19,121 - freqtrade.exchange.check_exchange - WARNING - Exchange "mexc" is known to the ccxt library, available for the bot, but not officially supported by the Freqtrade development team. It may work flawlessly (please report back) or have serious issues. Use it at your own discretion.
2024-11-19 11:48:19,121 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2024-11-19 11:48:19,122 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2024-11-19 11:48:19,251 - freqtrade.resolvers.exchange_resolver - INFO - No Mexc specific subclass found. Using the generic class instead.
2024-11-19 11:48:19,253 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2024-11-19 11:48:19,253 - freqtrade.exchange.exchange - INFO - Using CCXT 4.3.16
2024-11-19 11:48:19,254 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultTyp2024-11-19 11:48:19,261 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultTyp2024-11-19 11:48:19,270 - freqtrade.exchange.exchange - INFO - Using Exchange "MEXC Global"
2024-11-19 11:48:19,270 - freqtrade.exchange.exchange - INFO - Markets were not loaded. Loading them now..
2024-11-19 11:48:23,859 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "C:\git\freqtrade\freqtrade\main.py", line 44, in main
    return_code = args["func"](args)
                  ^^^^^^^^^^^^^^^^^^
  File "C:\git\freqtrade\freqtrade\commands\data_commands.py", line 41, in start_download_data
    download_data_main(config)
  File "C:\git\freqtrade\freqtrade\data\history\history_utils.py", line 599, in download_data_main
    for p in exchange.get_markets(
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\freqtrade\freqtrade\exchange\exchange.py", line 487, in get_markets
    markets = self.markets
              ^^^^^^^^^^^^
  File "C:\git\freqtrade\freqtrade\exchange\exchange.py", line 422, in markets
    self.reload_markets(True)
  File "C:\git\freqtrade\freqtrade\exchange\exchange.py", line 679, in reload_markets
    self.fill_leverage_tiers()
  File "C:\git\freqtrade\freqtrade\exchange\exchange.py", line 3206, in fill_leverage_tiers
    pair_tiers.append(self.parse_leverage_tier(tier))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\freqtrade\freqtrade\exchange\exchange.py", line 3212, in parse_leverage_tier
    "minNotional": tier["minNotional"],
                   ~~~~^^^^^^^^^^^^^^^
KeyError: 'minNotional'
  ```
Config:
```
{
    "max_open_trades": 1000,
    "stake_currency": "USDT",
    "stake_amount": 10000,
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "dry_run": true,
    "dry_run_wallet": 1000,
    "cancel_open_orders_on_exit": false,
    "trading_mode": "futures",
    "margin_mode": "isolated",
    "unfilledtimeout": {
        "entry": 10,
        "exit": 10,
        "exit_timeout_count": 0,
        "unit": "minutes"
    },
    "entry_pricing": {
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1,
        "price_last_balance": 0.0,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "exit_pricing":{
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1
    },
    "exchange": {
        "name": "mexc",
        "key": "my_key",
        "secret": "my_secret",
        "ccxt_config": {},
        "ccxt_async_config": {},  
        "pair_whitelist" : [
              "BTC/USDT:USDT"
        ],
        "pair_blacklist": [
        ]
    },
    "pairlists": [
        {
            "method": "VolumePairList",
            "number_assets": 20,
            "sort_key": "quoteVolume",
            "min_value": 0,
            "refresh_period": 1800
        }
    ],
    "telegram": {
        "enabled": true,
        "token": "my_token",
        "chat_id": "my_chat_id"
    },
    "api_server": {
        "enabled": true,
        "listen_ip_address": "127.0.0.1",
        "listen_port": 8080,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "my_jwt_secret_key",
        "ws_token": "my_ws_token",
        "CORS_origins": [],
        "username": "freqtrader",
        "password": ""
    },
    "bot_name": "freqtrade",
    "initial_state": "running",
    "force_entry_enable": false,
    "internals": {
        "process_throttle_secs": 5
    }
}
```

**Comment by xmatthias** [comment]
Freqtrade does not support mexc, letalone futures on mexc.

We also don't support modified versions - which you must be running, otherwise you'd get the following error - clearly stating that this freqtrade does not support futures on mexc.

This is the error i get on 2024.10 (and also develop) - and it reflects the truth.

```
2024-11-19 19:23:21,179 - freqtrade - ERROR - Freqtrade does not support isolated futures on MEXC Global
```

(as an aside, your ccxt version is outdated - which is the actual cause of the error on download-data).
Yet - you won't be able to use the downloaded data - as freqtrade doesn't support futures on mexc.
