### ISSUE TITLE
gate.io: isolated not supported when entering trade

### ISSUE THREAD

**Issue by kennylbj** [freqtrade/freqtrade#10964]
## Describe your environment

  * Operating system: _ubuntu 22.04___
  * Python Version: ___using docker__ (`python -V`)
  * CCXT version: __4.4.24___ (`pip freeze | grep ccxt`)
  * Freqtrade Version: _2024.10___ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*
Running a gate.io bot with `{"trading_mode": "futures", "margin_mode": "isolated"}`, the bot was able to startup normally, but when populating enter signal, the error occured:

```
2024-11-19 08:30:50,513 - freqtrade.loggers - INFO - Verbosity set to 0
2024-11-19 08:30:50,514 - freqtrade.configuration.configuration - INFO - Runmode set to live.
2024-11-19 08:30:50,514 - freqtrade.configuration.configuration - INFO - Parameter --db-url detected ...
2024-11-19 08:30:50,514 - freqtrade.configuration.configuration - WARNING - `force_entry_enable` RPC message enabled.
2024-11-19 08:30:50,514 - freqtrade.configuration.configuration - INFO - Dry run is disabled
2024-11-19 08:30:50,514 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:////freqtrade/user_data/tradesv3.sqlite"
2024-11-19 08:30:50,514 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 3 ...
2024-11-19 08:30:50,553 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2024-11-19 08:30:50,553 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/gate ...
2024-11-19 08:30:50,554 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2024-11-19 08:30:50,559 - freqtrade.exchange.check_exchange - INFO - Exchange "gate" is officially supported by the Freqtrade development team.
2024-11-19 08:30:50,559 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2024-11-19 08:30:50,585 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy Spiderman from '/freqtrade/user_data/strategies/spiderman.py'...
2024-11-19 08:30:50,586 - freqtrade.strategy.hyper - INFO - Found no parameter file.
2024-11-19 08:30:50,586 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'order_types' with value in config file: {'entry': 'limit', 'exit': 'limit', 'force_exit': 'limit', 'stoploss': 'market', 'stoploss_on_exchange': True}.
2024-11-19 08:30:50,586 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2024-11-19 08:30:50,586 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: unlimited.
2024-11-19 08:30:50,586 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}.
2024-11-19 08:30:50,586 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 5m
2024-11-19 08:30:50,586 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.25
2024-11-19 08:30:50,586 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2024-11-19 08:30:50,587 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2024-11-19 08:30:50,587 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2024-11-19 08:30:50,587 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2024-11-19 08:30:50,587 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: True
2024-11-19 08:30:50,587 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'entry': 'limit', 'exit': 'limit', 'force_exit': 'limit', 'stoploss': 'market', 'stoploss_on_exchange': True}
2024-11-19 08:30:50,587 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'entry': 'GTC', 'exit': 'GTC'}
2024-11-19 08:30:50,587 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2024-11-19 08:30:50,587 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: unlimited
2024-11-19 08:30:50,587 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 4
2024-11-19 08:30:50,587 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}
2024-11-19 08:30:50,587 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_exit_signal: True
2024-11-19 08:30:50,587 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_only: False
2024-11-19 08:30:50,587 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_entry_signal: False
2024-11-19 08:30:50,587 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_offset: 0.0
2024-11-19 08:30:50,587 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2024-11-19 08:30:50,587 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2024-11-19 08:30:50,587 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: False
2024-11-19 08:30:50,587 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1
2024-11-19 08:30:50,588 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_open_trades: 3
2024-11-19 08:30:50,588 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2024-11-19 08:30:50,591 - freqtrade.exchange.exchange - INFO - Using CCXT 4.4.24
2024-11-19 08:30:50,591 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}}
2024-11-19 08:30:50,595 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}}
2024-11-19 08:30:50,601 - freqtrade.exchange.exchange - INFO - Using Exchange "Gate.io"
2024-11-19 08:30:53,561 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Gate'...
2024-11-19 08:30:53,659 - freqtrade.wallets - INFO - Wallets synced.
2024-11-19 08:30:53,712 - freqtrade.rpc.rpc_manager - INFO - Enabling rpc.telegram ...
2024-11-19 08:30:53,988 - freqtrade.rpc.telegram - INFO - using custom keyboard from config.json: [['/daily', '/profit', '/balance'], ['/status', '/status table', '/trades'], ['/whitelist', '/blacklist', '/logs', '/help']]
2024-11-19 08:30:53,988 - freqtrade.rpc.rpc_manager - INFO - Enabling rpc.api_server
2024-11-19 08:30:54,102 - freqtrade.rpc.telegram - INFO - rpc.telegram is listening for following commands: [['status'], ['profit'], ['balance'], ['start'], ['stop'], ['forceexit', 'forcesell', 'fx'], ['forcebuy', 'forcelong'], ['forceshort'], ['reload_trade'], ['trades'], ['delete'], ['cancel_open_order', 'coo'], ['performance'], ['buys', 'entries'], ['exits', 'sells'], ['mix_tags'], ['stats'], ['daily'], ['weekly'], ['monthly'], ['count'], ['locks'], ['delete_locks', 'unlock'], ['reload_conf', 'reload_config'], ['show_conf', 'show_config'], ['stopbuy', 'stopentry'], ['whitelist'], ['blacklist'], ['bl_delete', 'blacklist_delete'], ['logs'], ['edge'], ['health'], ['help'], ['version'], ['marketdir'], ['order'], ['list_custom_data']]
2024-11-19 08:30:54,246 - freqtrade.rpc.api_server.webserver - INFO - Starting HTTP Server at 0.0.0.0:8084
2024-11-19 08:30:54,247 - freqtrade.rpc.api_server.webserver - INFO - Starting Local Rest Server.
2024-11-19 08:30:54,259 - uvicorn.error - INFO - Started server process [1]
2024-11-19 08:30:54,259 - uvicorn.error - INFO - Waiting for application startup.
2024-11-19 08:30:54,259 - uvicorn.error - INFO - Application startup complete.
2024-11-19 08:30:54,259 - uvicorn.error - INFO - Uvicorn running on http://0.0.0.0:8084 (Press CTRL+C to quit)
2024-11-19 08:30:54,271 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from '/freqtrade/freqtrade/plugins/pairlist/StaticPairList.py'...
2024-11-19 08:30:54,281 - freqtrade.plugins.pairlistmanager - INFO - Whitelist with 0 pairs: []
2024-11-19 08:30:54,282 - freqtrade.strategy.hyper - INFO - No params for buy found, using default values.
2024-11-19 08:30:54,283 - freqtrade.strategy.hyper - INFO - No params for sell found, using default values.
2024-11-19 08:30:54,283 - freqtrade.strategy.hyper - INFO - No params for protection found, using default values.
2024-11-19 08:30:54,289 - freqtrade.resolvers.iresolver - INFO - Using resolved protection CooldownPeriod from '/freqtrade/freqtrade/plugins/protections/cooldown_period.py'...
2024-11-19 08:30:54,290 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'running'}
2024-11-19 08:30:54,290 - freqtrade.worker - INFO - Changing state to: RUNNING
2024-11-19 08:30:54,298 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': "*Exchange:* `gate`\n*Stake per trade:* `unlimited USDT`\n*Minimum ROI:* `{'0': 0.3, '30': 0.2, '60': 0.12, '120': 0.08, '360': 0.05, '720': 0, '1200': -1}`\n*Stoploss:* `-0.25`\n*Position adjustment:* `Off`\n*Timeframe:* `5m`\n*Strategy:* `Spiderman`"}
2024-11-19 08:30:54,298 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': "Searching for USDT pairs to buy and sell based on [{'StaticPairList': 'StaticPairList'}]"}
2024-11-19 08:30:54,300 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': 'Using Protections: \nCooldownPeriod - Cooldown period for 12 candles.'}
2024-11-19 08:30:54,308 - freqtrade.freqtradebot - INFO - Updating 0 open orders.
2024-11-19 08:30:54,322 - freqtrade.freqtradebot - INFO - Active pair whitelist is empty.
2024-11-19 08:30:54,847 - telegram.ext.Application - INFO - Application started
2024-11-19 08:30:59,308 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2024.10', state='RUNNING'
2024-11-19 08:31:04,385 - freqtrade.wallets - INFO - Wallets synced.
2024-11-19 08:31:59,310 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2024.10', state='RUNNING'
2024-11-19 08:32:59,312 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2024.10', state='RUNNING'
..........
..........
2024-11-20 17:01:12,537 - freqtrade.wallets - INFO - Wallets synced.
2024-11-20 17:01:12,583 - freqtrade.freqtradebot - INFO - Long signal found: about create a new trade for FLOKI/USDT:USDT with stake_amount: 236.16744888000002 ...
2024-11-20 17:01:12,638 - freqtrade.exchange.common - WARNING - _set_leverage() returned exception: "Could not set leverage due to ExchangeError. Message: gate {"label":"USER_PORTFOLIO_MARGIN","message":"isolated not supported"}". Retrying still for 4 times.
2024-11-20 17:01:12,683 - freqtrade.exchange.common - WARNING - _set_leverage() returned exception: "Could not set leverage due to ExchangeError. Message: gate {"label":"USER_PORTFOLIO_MARGIN","message":"isolated not supported"}". Retrying still for 3 times.
2024-11-20 17:01:12,734 - freqtrade.exchange.common - WARNING - _set_leverage() returned exception: "Could not set leverage due to ExchangeError. Message: gate {"label":"USER_PORTFOLIO_MARGIN","message":"isolated not supported"}". Retrying still for 2 times.
2024-11-20 17:01:12,784 - freqtrade.exchange.common - WARNING - _set_leverage() returned exception: "Could not set leverage due to ExchangeError. Message: gate {"label":"USER_PORTFOLIO_MARGIN","message":"isolated not supported"}". Retrying still for 1 times.
2024-11-20 17:01:12,833 - freqtrade.exchange.common - WARNING - _set_leverage() returned exception: "Could not set leverage due to ExchangeError. Message: gate {"label":"USER_PORTFOLIO_MARGIN","message":"isolated not supported"}". Giving up.
2024-11-20 17:01:12,834 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/base/exchange.py", line 567, in fetch
    response.raise_for_status()
  File "/home/ftuser/.local/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.gateio.ws/api/v4/futures/usdt/positions/FLOKI_USDT/leverage?leverage=1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/exchange.py", line 3311, in _set_leverage
    res = self._api.set_leverage(symbol=pair, leverage=leverage)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/gate.py", line 5205, in set_leverage
    response = self.privateFuturesPostSettlePositionsContractLeverage(self.extend(request, query))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/base/types.py", line 35, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/base/exchange.py", line 4102, in request
    return self.fetch2(path, api, method, params, headers, body, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/base/exchange.py", line 4098, in fetch2
    raise e
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/base/exchange.py", line 4089, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/base/exchange.py", line 583, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/gate.py", line 7416, in handle_errors
    raise ExchangeError(feedback)
ccxt.base.errors.ExchangeError: gate {"label":"USER_PORTFOLIO_MARGIN","message":"isolated not supported"}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/common.py", line 181, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/exchange/exchange.py", line 3321, in _set_leverage
    raise TemporaryError(
freqtrade.exceptions.TemporaryError: Could not set leverage due to ExchangeError. Message: gate {"label":"USER_PORTFOLIO_MARGIN","message":"isolated not supported"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/base/exchange.py", line 567, in fetch
    response.raise_for_status()
  File "/home/ftuser/.local/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.gateio.ws/api/v4/futures/usdt/positions/FLOKI_USDT/leverage?leverage=1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/exchange.py", line 3311, in _set_leverage
    res = self._api.set_leverage(symbol=pair, leverage=leverage)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/gate.py", line 5205, in set_leverage
    response = self.privateFuturesPostSettlePositionsContractLeverage(self.extend(request, query))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/base/types.py", line 35, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/base/exchange.py", line 4102, in request
    return self.fetch2(path, api, method, params, headers, body, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/base/exchange.py", line 4098, in fetch2
    raise e
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/base/exchange.py", line 4089, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/base/exchange.py", line 583, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/gate.py", line 7416, in handle_errors
    raise ExchangeError(feedback)
ccxt.base.errors.ExchangeError: gate {"label":"USER_PORTFOLIO_MARGIN","message":"isolated not supported"}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/common.py", line 181, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/exchange/exchange.py", line 3321, in _set_leverage
    raise TemporaryError(
freqtrade.exceptions.TemporaryError: Could not set leverage due to ExchangeError. Message: gate {"label":"USER_PORTFOLIO_MARGIN","message":"isolated not supported"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/base/exchange.py", line 567, in fetch
    response.raise_for_status()
  File "/home/ftuser/.local/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.gateio.ws/api/v4/futures/usdt/positions/FLOKI_USDT/leverage?leverage=1
```

this is the strategy leverage code:

```python
# enable short
can_short = True

def leverage(self, pair: str, current_time: datetime, current_rate: float,
                 proposed_leverage: float, max_leverage: float, entry_tag: Optional[str], side: str,
                 **kwargs) -> float:
      return 1
```

this is the config.json
```json
"dry_run": false,
    "dry_run_wallet": 1000,
    "cancel_open_orders_on_exit": false,
    "trading_mode": "futures",
    "margin_mode": "isolated",
    "unfilledtimeout": {
        "entry": 10,
        "exit": 10,
        "exit_timeout_count": 0,
        "unit": "minutes"
    },
    "order_types": {
        "entry": "limit",
        "exit": "limit",
        "force_exit": "limit",
        "stoploss": "market",
        "stoploss_on_exchange": true
    },
```

this is the api permission:

```
Spot Trade: Read And Write
Perpetual Futures: Read And Write
Wallet: Read Only
Account:  Read Only
```

I am using gate.io's unified account, but the following permission is diabled:

```
Margin Trading (Unified Account): disabled
```

Is this the root for this bug? or am I missing something.

**BTW, the same bot can enter trade in dry-run mode**

### Steps to reproduce:

  1. __start the bot with futures enabled___
  2. __trigger enter signal___
  3. _got __`isolated not supported` error__
  
### Observed Results:

  * What happened?
  * What did you expect to happen?
  the signal should enter successfully.

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
  ```
please check it above

**Comment by vahid76758** [comment]
- .devcontainer/devcontainer.json[@![image](https://github.com/user-attachments/assets/55863efb-285f-463f-ba77-04f37c7a2ca7)]()

**Comment by xmatthias** [comment]
it's new to me that gate offers a "unified account" - but apparently, they just don't offer it in my region :( .

From reading through their landing page for this mode doesn't seem to support isolated trading - but only account magin trading - which is not a mode freqtrade currently supports.

in my experience (with other exchanges, really) - you can encounter similar errors for two reasons

* you've got an open cross-margin position - preventing freqtrade to switch to isolated mode
* you can't perform this action on the UI, either.


Your best bet when encountering "random" APi issues (errors that are not listed on the API page, like this one) is to try the actions you took on the UI.
Using the UI - can you still switch to isolated margin in the UI?
if not - then this account type probably can't use isolated margin mode - so your best hope is that you can still create classic subaccounts (subaccounts are available to everyone on gate afaik) to use freqtrade .

Also - the docs suggest that also unified accounts can be switched to "classic spot mode" - which i think should restore expected behavior.

**Comment by kennylbj** [comment]
thank you for you detailed reply.

Based on your suggestion, I manually switch the account to `classical` on UI and everything works fine.

I will close this issue then.
