### ISSUE TITLE
Backtesting Abruptly Terminates with CatBoostError: "Labels variable is empty."

### ISSUE THREAD

**Issue by SpankulatorX** [freqtrade/freqtrade#10998]
## Description
When running the backtesting command with the FreqaiExampleHybridStrategy and CatboostClassifier model, the training process terminates unexpectedly with a CatBoostError indicating that the "Labels variable is empty." This issue prevents successful backtesting and model training.

## Run Backtesting Command
```bash
docker-compose run freqtrade backtesting \
  --config user_data/config_futures.json \
  --strategy FreqaiExampleHybridStrategy \
  --freqaimodel CatboostClassifier \
  --timerange 20200201-20241126 \
  --enable-protections
```

## Expected Behavior: 
The backtesting process should run to completion, training the model without errors and providing backtest results based on the specified strategy and configuration.

## Actual Behavior:
The backtesting process terminates abruptly with the following error:

`_catboost.CatBoostError: Labels variable is empty.`

Additionally, an AttributeError occurs:

`AttributeError: 'NoneType' object hasno attribute 'predict'`

## Additional Information:
I have reviewed the official documentation and searched through existing GitHub issues for similar errors, but I have not found any solutions or relevant guidance to resolve this problem.

## Logs:

```
WARN[0000] Found orphan containers ([ft_userdata-freqtrade-run-47d3fb2dfc26]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up. 
2024-11-26 13:49:30,425 - freqtrade - INFO - freqtrade docker-2024.11-dev-e0c6cc15
...
2024-11-26 13:49:52,737 - freqtrade.freqai.freqai_interface - WARNING - Training BTC/USDT:USDT raised exception CatBoostError. Message: Labels variable is empty., skipping.
Traceback (most recent call last):
  File "/freqtrade/freqtrade/freqai/freqai_interface.py", line 370, in start_backtesting
    self.model = self.train(dataframe_train, pair, dk)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/freqai/base_models/BaseClassifierModel.py", line 76, in train
    model = self.fit(dd, dk)
            ^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/freqai/prediction_models/CatboostClassifier.py", line 40, in fit
    test_data = Pool(
                ^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/catboost/core.py", line 855, in __init__
    self._init(data, label, cat_features, text_features, embedding_features, embedding_features_data, pairs, graph, weight,
  File "/home/ftuser/.local/lib/python3.12/site-packages/catboost/core.py", line 1430, in _init
    self._check_label_empty(label)
  File "/home/ftuser/.local/lib/python3.12/site-packages/catboost/core.py", line 966, in _check_label_empty
    raise CatBoostError("Labels variable is empty.")
_catboost.CatBoostError: Labels variable is empty.
2024-11-26 13:49:53,011 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 44, in main
    return_code = args["func"](args)
                  ^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 61, in start_backtesting
    backtesting.start()
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 1649, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 1556, in backtest_one_strategy
    preprocessed = self.strategy.advise_all_indicators(data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/strategy/interface.py", line 1584, in advise_all_indicators
    pair: self.advise_indicators(pair_data.copy(), {"pair": pair}).copy()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/strategy/interface.py", line 1642, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/user_data/strategies/FreqaiExampleHybridStrategy.py", line 239, in populate_indicators
    dataframe = self.freqai.start(dataframe, metadata, self)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/freqai/freqai_interface.py", line 161, in start
    dk = self.start_backtesting(dataframe, metadata, self.dk, strategy)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/freqai/freqai_interface.py", line 392, in start_backtesting
    pred_df, do_preds = self.predict(dataframe_backtest, dk)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/freqai/base_models/BaseClassifierModel.py", line 110, in predict
    predictions = self.model.predict(dk.data_dictionary["prediction_features"])
                  ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'predict'
```

## Configuration:
```json
{
    "trading_mode": "futures",
    "margin_mode": "isolated",
    "max_open_trades": 5,
    "stake_currency": "USDT",
    "stake_amount": 100,
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "dry_run": true,
    "timeframe": "3m",
    "dry_run_wallet": 1000,
    "cancel_open_orders_on_exit": false,
    "exchange": {
        "name": "binance",
        "key": "",
        "secret": "",
        "ccxt_config": {
            "enableRateLimit": true
        },
        "ccxt_async_config": {
            "enableRateLimit": true,
            "rateLimit": 200
        },
        "pair_whitelist": [
            "BTC/USDT:USDT",
            "ETH/USDT:USDT"
        ],
        "pair_blacklist": [
            "BNB/.*"
        ]
    },
    "pairlists": [
        {
            "method": "StaticPairList",
            "number_assets": 2,
            "sort_key": "quote_volume",
            "min_value": 0,
            "refresh_period": 1800
        }
    ],
    "entry_pricing": {
        "use_order_book": true,
        "order_book_top": 1,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "exit_pricing": {
        "use_order_book": true,
        "order_book_top": 1
    },
    "order_types": {
        "entry": "limit",
        "exit": "limit",
        "emergency_exit": "market",
        "force_exit": "market",
        "force_entry": "market",
        "stoploss": "market",
        "stoploss_on_exchange": true,
        "stoploss_on_exchange_interval": 60
    },
    "freqai": {
        "enabled": true,
        "purge_old_models": 2,
        "train_period_days": 15,
        "identifier": "example",
        "feature_parameters": {
            "include_timeframes": [
                "3m",
                "15m",
                "1h"
            ],
            "include_corr_pairlist": [
                "BTC/USDT:USDT",
                "ETH/USDT:USDT"
            ],
            "label_period_candles": 20,
            "include_shifted_candles": 2,
            "DI_threshold": 0.9,
            "weight_factor": 0.9,
            "principal_component_analysis": false,
            "use_SVM_to_remove_outliers": true,
            "indicator_periods_candles": [10, 20]
        },
        "data_split_parameters": {
            "test_size": 0.25,
            "random_state": 1
        },
        "model_training_parameters": {
            "n_estimators": 800,
            "task_type": "GPU",
            "devices": "0"
        }
    },
    "bot_name": "freqtrade_hybrid",
    "force_entry_enable": false,
    "initial_state": "running",
    "internals": {
        "process_throttle_secs": 5
    }
}
```

## Strategy
```python
import logging

import numpy as np  # noqa
import pandas as pd  # noqa
import talib.abstract as ta
from pandas import DataFrame
from technical import qtpylib

from freqtrade.strategy import IntParameter, IStrategy, merge_informative_pair  # noqa

logger = logging.getLogger(__name__)

class FreqaiExampleHybridStrategy(IStrategy):
    """
    Example of a hybrid FreqAI strat, designed to illustrate how a user may employ
    FreqAI to bolster a typical Freqtrade strategy.
    """

    minimal_roi = {
        "60": 0.01,
        "30": 0.02,
        "0": 0.04,
    }

    plot_config = {
        "main_plot": {
            "tema": {},
        },
        "subplots": {
            "MACD": {
                "macd": {"color": "blue"},
                "macdsignal": {"color": "orange"},
            },
            "RSI": {
                "rsi": {"color": "red"},
            },
            "Up_or_down": {
                "&s-up_or_down": {"color": "green"},
            },
        },
    }

    process_only_new_candles = True
    stoploss = -0.05
    use_exit_signal = True
    startup_candle_count: int = 30
    can_short = False

    # Hyperoptable parameters
    buy_rsi = IntParameter(low=1, high=50, default=30, space="buy", optimize=True, load=True)
    sell_rsi = IntParameter(low=50, high=100, default=70, space="sell", optimize=True, load=True)
    short_rsi = IntParameter(low=51, high=100, default=70, space="sell", optimize=True, load=True)
    exit_short_rsi = IntParameter(low=1, high=50, default=30, space="buy", optimize=True, load=True)

    def feature_engineering_expand_all(
        self, dataframe: DataFrame, period: int, metadata: dict, **kwargs
    ) -> DataFrame:
        dataframe["%-rsi-period"] = ta.RSI(dataframe, timeperiod=period)
        dataframe["%-mfi-period"] = ta.MFI(dataframe, timeperiod=period)
        dataframe["%-adx-period"] = ta.ADX(dataframe, timeperiod=period)
        dataframe["%-sma-period"] = ta.SMA(dataframe, timeperiod=period)
        dataframe["%-ema-period"] = ta.EMA(dataframe, timeperiod=period)

        bollinger = qtpylib.bollinger_bands(
            qtpylib.typical_price(dataframe), window=period, stds=2.2
        )
        dataframe["bb_lowerband-period"] = bollinger["lower"]
        dataframe["bb_middleband-period"] = bollinger["mid"]
        dataframe["bb_upperband-period"] = bollinger["upper"]

        dataframe["%-bb_width-period"] = (
            dataframe["bb_upperband-period"] - dataframe["bb_lowerband-period"]
        ) / dataframe["bb_middleband-period"]
        dataframe["%-close-bb_lower-period"] = dataframe["close"] / dataframe["bb_lowerband-period"]

        dataframe["%-roc-period"] = ta.ROC(dataframe, timeperiod=period)

        dataframe["%-relative_volume-period"] = (
            dataframe["volume"] / dataframe["volume"].rolling(period).mean()
        )

        return dataframe

    def feature_engineering_expand_basic(
        self, dataframe: DataFrame, metadata: dict, **kwargs
    ) -> DataFrame:
        dataframe["%-pct-change"] = dataframe["close"].pct_change()
        dataframe["%-raw_volume"] = dataframe["volume"]
        dataframe["%-raw_price"] = dataframe["close"]
        return dataframe

    def feature_engineering_standard(
        self, dataframe: DataFrame, metadata: dict, **kwargs
    ) -> DataFrame:
        dataframe["%-day_of_week"] = dataframe["date"].dt.dayofweek
        dataframe["%-hour_of_day"] = dataframe["date"].dt.hour
        return dataframe

    def set_freqai_targets(self, dataframe: DataFrame, metadata: dict, **kwargs) -> DataFrame:
        self.freqai.class_names = ["down", "up"]
        dataframe["&s-up_or_down"] = np.where(
            dataframe["close"].shift(-50) > dataframe["close"], "up", "down"
        )
        return dataframe

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe = self.freqai.start(dataframe, metadata, self)

        # TA indicators to combine with the Freqai targets
        # RSI
        dataframe["rsi"] = ta.RSI(dataframe)

        # Bollinger Bands
        bollinger = qtpylib.bollinger_bands(qtpylib.typical_price(dataframe), window=20, stds=2)
        dataframe["bb_lowerband"] = bollinger["lower"]
        dataframe["bb_middleband"] = bollinger["mid"]
        dataframe["bb_upperband"] = bollinger["upper"]
        dataframe["bb_percent"] = (dataframe["close"] - dataframe["bb_lowerband"]) / (
            dataframe["bb_upperband"] - dataframe["bb_lowerband"]
        )
        dataframe["bb_width"] = (dataframe["bb_upperband"] - dataframe["bb_lowerband"]) / dataframe[
            "bb_middleband"
        ]

        # TEMA - Triple Exponential Moving Average
        dataframe["tema"] = ta.TEMA(dataframe, timeperiod=9)

        return dataframe

    def populate_entry_trend(self, df: DataFrame, metadata: dict) -> DataFrame:
        df.loc[
            (
                (qtpylib.crossed_above(df["rsi"], self.buy_rsi.value))
                & (df["tema"] <= df["bb_middleband"])
                & (df["tema"] > df["tema"].shift(1))
                & (df["volume"] > 0)
                & (df["do_predict"] == 1)
                & (df["&s-up_or_down"] == "up")
            ),
            "enter_long",
        ] = 1

        df.loc[
            (
                (qtpylib.crossed_above(df["rsi"], self.short_rsi.value))
                & (df["tema"] > df["bb_middleband"])
                & (df["tema"] < df["tema"].shift(1))
                & (df["volume"] > 0)
                & (df["do_predict"] == 1)
                & (df["&s-up_or_down"] == "down")
            ),
            "enter_short",
        ] = 1

        return df

    def populate_exit_trend(self, df: DataFrame, metadata: dict) -> DataFrame:
        df.loc[
            (
                (qtpylib.crossed_above(df["rsi"], self.sell_rsi.value))
                & (df["tema"] > df["bb_middleband"])
                & (df["tema"] < df["tema"].shift(1))
                & (df["volume"] > 0)
            ),
            "exit_long",
        ] = 1

        df.loc[
            (
                (qtpylib.crossed_above(df["rsi"], self.exit_short_rsi.value))
                & (df["tema"] <= df["bb_middleband"])
                & (df["tema"] > df["tema"].shift(1))
                & (df["volume"] > 0)
            ),
            "exit_short",
        ] = 1

        return df
```

## docker-compose.yml
```yml
---
services:
  freqtrade:
    image: freqtradeorg/freqtrade:develop
    # # Enable GPU Image and GPU Resources
    # # Make sure to uncomment the whole deploy section
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    # Build step - only needed when additional dependencies are needed
    build:
      context: .
      dockerfile: "Dockerfile.develop"
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/stable/rest-api/ documentation
    # for more information.
    ports:
      - "127.0.0.1:8080:8080"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --freqaimodel XGBoostRegressor
      --strategy FreqaiExampleStrategy

```

## Dockerfile.develop
```dockerfile
FROM freqtradeorg/freqtrade:develop

# Install dependencies
COPY requirements-dev.txt /freqtrade/

RUN pip install numpy --user --no-cache-dir \
  && pip install -r requirements-dev.txt --user --no-cache-dir

# Set the correct entrypoint
ENTRYPOINT ["freqtrade"]
```

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

----

Without version, the base assumption i'd say is "outdated version" - though i'll believe in honesty and will assume you'll be providing us the version template, still :) 

For the issue itself - i'd say let's start with full logs (most importantly - _everything_ up to when the training starts - and if training doesn't start - then everything).

**Comment by xmatthias** [comment]
Gonna close this as we got no further feedback, so we'll assume you've got this sorted.

if it's still a problem - please provide us with the logs as requested above so we can look at this.
