### ISSUE TITLE
buy price of the first order in a DCA order

### ISSUE THREAD

**Issue by VerDoe** [freqtrade/freqtrade#10990]
* Operating system: Debian GNU/Linux 12 (bookworm)
  * Python Version: Python 3.11.2
  * CCXT version: ccxt==4.4.24
  * Freqtrade Version: freqtrade 2024.10
  
## Your question
I have a question about a parameter. I want to query the buy price of the first order in a DCA order. I thought filled_entries[0].open_rate is correct, but I always get an error. filled_entries[0].stake_amount works though. What is the correct parameter? If I query the price with filled_entries[0].price it works.

```shell
2024-11-25 11:37:53,340 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error 'Order' object has no attribute 'open_rate' calling <bound method Test.adjust_trade_position of <Test_V04.Test object at 0x7f05cd9a27d0>>
Traceback (most recent call last):
  File "/app/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 28, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/app/freqtrade/user_data/strategies/Test_V04.py", line 155, in adjust_trade_position
    open_price = filled_entries[0].open_rate
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Order' object has no attribute 'open_rate'

``` 
```python
def adjust_trade_position(self, trade: Trade, current_time: datetime, current_rate: float, current_profit: float, min_stake: Optional[float], max_stake: float, current_entry_rate: float,  current_exit_rate: float, current_entry_profit: float, current_exit_profit: float, **kwargs ) -> Union[Optional[float], Tuple[Optional[float], Optional[str]]]:

...
        filled_entries = trade.select_filled_orders(trade.entry_side)
...
                        # open_price = filled_entries[0].price
                        open_price = filled_entries[0].open_rate

```

**Comment by froggleston** [comment]
The error is quite clear - `Order`s don't have `open_rate`. The `Trade` object does. Please check the docs: https://www.freqtrade.io/en/stable/trade-object/

**Comment by VerDoe** [comment]
Thanks for the link, I had forgotten about it ;-)
