### ISSUE TITLE
Fatal exception - Freqtrade crashed and keep restarting when there is no data for a pair in higher timeframe

### ISSUE THREAD

**Issue by lazidoca** [freqtrade/freqtrade#11049]
## Describe your environment

  * Operating system: Ubuntu 22 running Freqtrade in docker
  * Freqtrade Version:  2024.11
  

## Describe the problem:

I use `VolumePairList` in the configuration and `futures` trading mode. When there is new pair listed on the exchange's Future market and the volume trading is high enough, that pair will be in the whitelist. Since the pair is new listed in Future, there is no data for `1d` timeframe, which causes the error shown in the logs -> freqtrade crashes -> keep restarting.

When I added the pairs (ACX/USDT:USD, ORCA/USDT:USDT) to the `pair_blacklist`, the error gone and the app worked normally.

### Steps to reproduce:

I think the **Description** above also explained the steps
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
2024-12-06 23:02:22,968 - freqtrade.data.dataprovider - WARNING - No data found for (ACX/USDT:USDT, 1d, futures).
2024-12-06 23:02:27,912 - freqtrade.data.dataprovider - WARNING - No data found for (ORCA/USDT:USDT, 1d, futures).
2024-12-06 23:02:38,709 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2024-12-06 23:02:38,709 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2024-12-06 23:02:38,711 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2024-12-06 23:02:38,717 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': warning, 'status': "32 open trades active.\n\nHandle these trades manually on Binance, or '/start' the bot again and use '/stopentry' to handle open trades gracefully. \nNote: Trades are simulated (dry run)."}
2024-12-06 23:02:38,717 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
2024-12-06 23:02:38,718 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.telegram ...
2024-12-06 23:02:38,738 - telegram.ext.Application - INFO - Application is stopping. This might take a moment.
2024-12-06 23:02:38,738 - telegram.ext.Application - INFO - Application.stop() complete
2024-12-06 23:02:38,739 - freqtrade.rpc.telegram - WARNING - Telegram NetworkError: httpx.ReadError: ! Trying one more time.
2024-12-06 23:02:38,740 - freqtrade.rpc.telegram - WARNING - TelegramError: Unknown error in HTTP implementation: RuntimeError('This HTTPXRequest is not initialized!')! Giving up on that message.
2024-12-06 23:02:46,140 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 44, in main
    return_code = args["func"](args)
                  ^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 25, in start_trading
    worker.run()
  File "/freqtrade/freqtrade/worker.py", line 79, in run
    state = self._worker(old_state=state)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/worker.py", line 120, in _worker
    self._throttle(
  File "/freqtrade/freqtrade/worker.py", line 161, in _throttle
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/worker.py", line 195, in _process_running
    self.freqtrade.process()
  File "/freqtrade/freqtrade/freqtradebot.py", line 298, in process
    self.enter_positions()
  File "/freqtrade/freqtrade/freqtradebot.py", line 651, in enter_positions
    trades_created += self.create_trade(pair)
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/freqtradebot.py", line 681, in create_trade
    (signal, enter_tag) = self.strategy.get_entry_signal(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/strategy/interface.py", line 1231, in get_entry_signal
    latest, latest_date = self.get_latest_candle(pair, timeframe, dataframe)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/strategy/interface.py", line 1167, in get_latest_candle
    latest = dataframe.loc[dataframe["date"] == latest_date].iloc[-1]
             ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/pandas/core/indexing.py", line 1191, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/pandas/core/indexing.py", line 1413, in _getitem_axis
    return self._getbool_axis(key, axis=axis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/pandas/core/indexing.py", line 1211, in _getbool_axis
    return self.obj._take_with_is_copy(inds, axis=axis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 4153, in _take_with_is_copy
    result = self.take(indices=indices, axis=axis)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 4133, in take
    new_data = self._mgr.take(
               ^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/pandas/core/internals/managers.py", line 894, in take
    return self.reindex_indexer(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/pandas/core/internals/managers.py", line 688, in reindex_indexer
    blk.take_nd(
  File "/home/ftuser/.local/lib/python3.12/site-packages/pandas/core/internals/blocks.py", line 1307, in take_nd
    new_values = algos.take_nd(
                 ^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/pandas/core/array_algos/take.py", line 117, in take_nd
    return _take_nd_ndarray(arr, indexer, axis, fill_value, allow_fill)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/pandas/core/array_algos/take.py", line 133, in _take_nd_ndarray
    dtype, fill_value, mask_info = _take_preprocess_indexer_and_fill_value(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/pandas/core/array_algos/take.py", line 592, in _take_preprocess_indexer_and_fill_value
    dtype, fill_value = arr.dtype, arr.dtype.type()
                                   ^^^^^^^^^^^^^^^^
TypeError: void() takes at least 1 positional argument (0 given)
2024-12-06 23:02:48,508 - freqtrade - INFO - freqtrade 2024.11
2024-12-06 23:02:49,127 - numexpr.utils - INFO - NumExpr defaulting to 4 threads.
2024-12-06 23:02:51,943 - freqtrade.worker - INFO - Starting worker 2024.11
2024-12-06 23:02:51,943 - freqtrade.configuration.load_config - INFO - Using config: /freqtrade/user_data/config.json ...
2024-12-06 23:02:51,944 - freqtrade.loggers - INFO - Verbosity set to 0
2024-12-06 23:02:51,945 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
  ```

**Comment by stash86** [comment]
Please use AgeFilter to filter out newly listed coin.

**Comment by xmatthias** [comment]
well aside from that - i don't really see the error.
Trying the same pairs but on weekly candles - i get "Empty candle (OHLCV) data for pair". 

This also returns right after - so i'm not entirely sure how you got to this error without modification of the freqtrade code, or by having the strategy "mess" with the actual dataframe columns (date, open,high,low,close,volume).

https://github.com/freqtrade/freqtrade/blob/fb9e11b7b52f46e310e8338a9811b6d3692bf3ae/freqtrade/strategy/interface.py#L1163-L1164
