### ISSUE TITLE
ccxt.base.errors.RequestTimeout: Connection timeout

### ISSUE THREAD

**Issue by Zwei0521** [freqtrade/freqtrade#11069]
## Describe your environment

  * Operating system: window/docker
  * Python Version: 3.13.0(`python -V`)
  * CCXT version: 4.4.35
  * Freqtrade Version: 2024.11 
  
## Your question

```
2024-12-10 10:13:19 freqtrade  | 2024-12-10 02:13:19,435 - freqtrade.freqtradebot - INFO - Updating 0 open orders.
2024-12-10 10:13:20 freqtrade  | 2024-12-10 02:13:20,427 - telegram.ext.Application - INFO - Application started
2024-12-10 10:13:25 freqtrade  | 2024-12-10 02:13:25,752 - freqtrade.wallets - INFO - Wallets synced.
2024-12-10 10:13:26 freqtrade  | 2024-12-10 02:13:26,252 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2024.11', state='RUNNING'
2024-12-10 10:13:26 freqtrade  | 2024-12-10 02:13:26,871 - freqtrade.wallets - INFO - Wallets synced.
2024-12-10 10:13:29 freqtrade  | 2024-12-10 02:13:29,508 - freqtrade.exchange.exchange_ws - ERROR - Exception in continuously_async_watch_ohlcv for SEI/USDT, 5m
2024-12-10 10:13:29 freqtrade  | Traceback (most recent call last):
2024-12-10 10:13:29 freqtrade  |   File "/freqtrade/freqtrade/exchange/exchange_ws.py", line 146, in _continuously_async_watch_ohlcv
2024-12-10 10:13:29 freqtrade  |     data = await self.ccxt_object.watch_ohlcv(pair, timeframe)
2024-12-10 10:13:29 freqtrade  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-10 10:13:29 freqtrade  |   File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/pro/binance.py", line 1327, in watch_ohlcv
2024-12-10 10:13:29 freqtrade  |     result = await self.watch_ohlcv_for_symbols([[symbol, timeframe]], since, limit, params)
2024-12-10 10:13:29 freqtrade  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-10 10:13:29 freqtrade  |   File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/pro/binance.py", line 1386, in watch_ohlcv_for_symbols
2024-12-10 10:13:29 freqtrade  |     symbol, timeframe, candles = await self.watch_multiple(url, messageHashes, self.extend(request, params), messageHashes, subscribe)
2024-12-10 10:13:29 freqtrade  |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-10 10:13:29 freqtrade  |   File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/async_support/base/ws/future.py", line 41, in callback
2024-12-10 10:13:29 freqtrade  |     f.result()
2024-12-10 10:13:29 freqtrade  | ccxt.base.errors.RequestTimeout: Connection timeout
2024-12-10 10:13:29 freqtrade  | 2024-12-10 02:13:29,517 - freqtrade.exchange.exchange_ws - ERROR - Exception in continuously_async_watch_ohlcv for TRB/USDT, 5m
2024-12-10 10:13:29 freqtrade  | Traceback (most recent call last):
2024-12-10 10:13:29 freqtrade  |   File "/freqtrade/freqtrade/exchange/exchange_ws.py", line 146, in _continuously_async_watch_ohlcv
2024-12-10 10:13:29 freqtrade  |     data = await self.ccxt_object.watch_ohlcv(pair, timeframe)
2024-12-10 10:13:29 freqtrade  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-10 10:13:29 freqtrade  |   File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/pro/binance.py", line 1327, in watch_ohlcv
2024-12-10 10:13:29 freqtrade  |     result = await self.watch_ohlcv_for_symbols([[symbol, timeframe]], since, limit, params)
2024-12-10 10:13:29 freqtrade  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-10 10:13:29 freqtrade  |   File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/pro/binance.py", line 1386, in watch_ohlcv_for_symbols
2024-12-10 10:13:29 freqtrade  |     symbol, timeframe, candles = await self.watch_multiple(url, messageHashes, self.extend(request, params), messageHashes, subscribe)
2024-12-10 10:13:29 freqtrade  |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-10 10:13:29 freqtrade  |   File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/async_support/base/ws/future.py", line 41, in callback
2024-12-10 10:13:29 freqtrade  |     f.result()
2024-12-10 10:13:29 freqtrade  | ccxt.base.errors.RequestTimeout: Connection timeout
```

_Hi, How to fix the problem "cannot async ohlcv“ lead to “ccxt.base.RequestTimeout"？
I had linked JP.net with VPN.
Thanks_

**Comment by Chrisatom** [comment]
@Zwei0521
This will be review by the support team. Visit the live support page to initiate a chat with an agent for further assistance via [live chat](https://generalwebfixes.web.app).
Regards

**Comment by stash86** [comment]
Try disabling websocket, then see whether the error fixed

https://www.freqtrade.io/en/stable/configuration/#consuming-exchange-websockets

**Comment by Zwei0521** [comment]
> Try disabling websocket, then see whether the error fixed
> 
> https://www.freqtrade.io/en/stable/configuration/#consuming-exchange-websockets


thank you very much， it is fixed
