### ISSUE TITLE
KeyError: ‘percentage’ in PercentChangePairList when filtering pairlist

### ISSUE THREAD

**Issue by MerouaneBen** [freqtrade/freqtrade#11074]
## Describe your environment

  * Operating system: Ubuntu 24.04
  * Python Version: Python 3.12.3
  * CCXT version: 4.4.37
  * Freqtrade Version: 2024.11

## Describe the problem:

When using a custom pairlist plugin (PercentChangePairList), the bot abruptly exits with a KeyError. The error occurs in the pairlist filtering process, specifically when the code attempts to access a key "percentage" in filtered_tickers for certain pairs that do not have that key assigned.

### Steps to reproduce:

1. Configure a custom pairlist in config.json using the PercentChangePairList code provided.
2. Start the bot with `freqtrade trade --config config.json`.
3. Wait for the refresh period so the pairlist is re-generated and filtered. (in my case it happened to me after nearly 24 hours)

  
### Observed Results:

-  **What happened?**

The bot runs for some time and after several cycles, it fails with a KeyError related to the "percentage" key not being found in filtered_tickers.

- **What did you expect to happen?**

The bot should continuously refresh the pairlist without crashing, maintaining a valid percentage value for each filtered pair or gracefully excluding pairs that lack this value.

### My Config 
```
 "pairlists": [
        {
            "method": "VolumePairList",
            "number_assets": 40,
            "sort_key": "quoteVolume",
            "min_value": 500000,
            "refresh_period": 1800
        },
        {
            "method": "AgeFilter",
            "min_days_listed": 20
        },
        {
            "method": "PercentChangePairList",
            "number_assets": 20,
            "min_value": -5,
            "max_value": 50,
            "refresh_period": 1800
        } 
]
```

### Relevant code exceptions or logs

  ```
  2024-12-10 22:52:21,007 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2024.11', state='RUNNING'
2024-12-10 22:53:21,010 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2024.11', state='RUNNING'
2024-12-10 22:54:21,014 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2024.11', state='RUNNING'
2024-12-10 22:54:33,830 - PercentChangePairList - INFO - Removed LINK/USDT from whitelist, because ticker['percentage'] is empty (Usually no trade in the last 24h).
2024-12-10 22:54:33,830 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2024-12-10 22:54:33,830 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2024-12-10 22:54:33,831 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2024-12-10 22:54:33,833 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': warning, 'status': "1 open trades active.\n\nHandle these trades manually on Gate.io, or '/start' the bot again and use '/stopentry' to handle open trades gracefully. \nNote: Trades are simulated (dry run)."}
2024-12-10 22:54:33,834 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
2024-12-10 22:54:33,834 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.apiserver ...
2024-12-10 22:54:33,834 - freqtrade.rpc.api_server.webserver - INFO - Stopping API Server
2024-12-10 22:54:33,898 - uvicorn.error - INFO - Shutting down
2024-12-10 22:54:33,999 - uvicorn.error - INFO - Waiting for application shutdown.
2024-12-10 22:54:34,000 - uvicorn.error - INFO - Application shutdown complete.
2024-12-10 22:54:34,000 - uvicorn.error - INFO - Finished server process [1]
2024-12-10 22:54:34,000 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.telegram ...
2024-12-10 22:54:34,104 - telegram.ext.Application - INFO - Application is stopping. This might take a moment.
2024-12-10 22:54:34,105 - telegram.ext.Application - INFO - Application.stop() complete
2024-12-10 22:54:37,810 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 44, in main
    return_code = args["func"](args)
                  ^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 25, in start_trading
    worker.run()
  File "/freqtrade/freqtrade/worker.py", line 79, in run
    state = self._worker(old_state=state)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/worker.py", line 120, in _worker
    self._throttle(
  File "/freqtrade/freqtrade/worker.py", line 161, in _throttle
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/worker.py", line 195, in _process_running
    self.freqtrade.process()
  File "/freqtrade/freqtrade/freqtradebot.py", line 264, in process
    self.active_pair_whitelist = self._refresh_active_whitelist(trades)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/freqtradebot.py", line 336, in _refresh_active_whitelist
    self.pairlists.refresh_pairlist()
  File "/freqtrade/freqtrade/plugins/pairlistmanager.py", line 140, in refresh_pairlist
    pairlist = pairlist_handler.filter_pairlist(pairlist, tickers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/plugins/pairlist/PercentChangePairList.py", line 224, in filter_pairlist
    filtered_tickers = [v for v in filtered_tickers if v["percentage"] > self._min_value]
                                                       ~^^^^^^^^^^^^^^
KeyError: 'percentage'
  ```

I believe this issue arises because elements are being removed from filtered_tickers while iterating over it in fetch_percent_change_from_tickers, causing some pairs to never be assigned a percentage key before further filtering attempts.

**Comment by xmatthias** [comment]
Nice catch - will be fixed shortly 👍
