### ISSUE TITLE
AgeFilter not working for a large number of whitelisted pairs

### ISSUE THREAD

**Issue by curiousHG** [freqtrade/freqtrade#11134]
## Describe your environment

  * Operating system: MacOs
  * Python Version: 3.11.11 (`python -V`)
  * CCXT version: 4.3.48(`pip freeze | grep ccxt`)
  * Freqtrade Version: 2024.5 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*
I was testing out using GodStra from the available strategies, I added a 60 day age filter to my configurations and whitelisted all the USDT pairs. I got an index out of bound on the ADXIndicator which had a window=14.

### Steps to reproduce:

  1.  I used this config

    "exchange": {
            "name": "binance",
            "key": "",
            "secret": "",
            "ccxt_config": {},
            "ccxt_async_config": {},
            "enable_ws": true,
            "pair_whitelist": [
                ".*/USDT$"
            ],
            "pair_blacklist": [
                "BNB/.*"
            ]
        },
        "pairlists": [
            {
                "method": "StaticPairList"
            },
            {
                "method":"AgeFilter",
                "min_days_listed": 60
            }
        ],
  2. freqtrade backtesting \
--strategy-path user_data/strategies/ \
-c user_data/configs/basic-config.json \
--strategy GodStra
  3. _____
  
### Observed Results:

  * What happened?
  Got index out of range for ADX indicator with window =14
  * What did you expect to happen?
  Expected the the pairs with age less than 60 days to be removed in the first place

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
2024-12-23 11:51:36,256 - freqtrade - INFO - freqtrade 2024.5
2024-12-23 11:51:36,257 - freqtrade.configuration.load_config - INFO - Using config: user_data/configs/basic-config.json ...
2024-12-23 11:51:36,258 - freqtrade.loggers - INFO - Verbosity set to 0
2024-12-23 11:51:36,258 - freqtrade.configuration.configuration - INFO - Using additional Strategy lookup path: user_data/strategies/
2024-12-23 11:51:36,258 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 100 ...
2024-12-23 11:51:36,258 - freqtrade.configuration.configuration - INFO - Using user-data directory: /Users/harshit/VS-Code/trading/freqtrade/user_data ...
2024-12-23 11:51:36,258 - freqtrade.configuration.configuration - INFO - Using data directory: /Users/harshit/VS-Code/trading/freqtrade/user_data/data/binance ...
2024-12-23 11:51:36,258 - freqtrade.configuration.configuration - INFO - Parameter --cache=day detected ...
2024-12-23 11:51:36,258 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2024-12-23 11:51:36,262 - freqtrade.exchange.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2024-12-23 11:51:36,262 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2024-12-23 11:51:36,262 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2024-12-23 11:51:36,263 - freqtrade.commands.optimize_commands - INFO - Starting freqtrade in Backtesting mode
2024-12-23 11:51:36,263 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2024-12-23 11:51:36,263 - freqtrade.exchange.exchange - INFO - Using CCXT 4.3.48
2024-12-23 11:51:36,271 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2024-12-23 11:51:38,370 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2024-12-23 11:51:38,483 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy GodStra from '/Users/harshit/VS-Code/trading/freqtrade/user_data/strategies/GodStra.py'...
2024-12-23 11:51:38,483 - freqtrade.strategy.hyper - INFO - Found no parameter file.
2024-12-23 11:51:38,483 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2024-12-23 11:51:38,483 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: unlimited.
2024-12-23 11:51:38,483 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}.
2024-12-23 11:51:38,483 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'max_open_trades' with value in config file: 100.
2024-12-23 11:51:38,483 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 0.3556, '4818': 0.21275, '6395': 0.09024, '22372': 0}
2024-12-23 11:51:38,483 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 12h
2024-12-23 11:51:38,483 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.34549
2024-12-23 11:51:38,483 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: True
2024-12-23 11:51:38,483 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive: 0.22673
2024-12-23 11:51:38,484 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.2684
2024-12-23 11:51:38,484 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: True
2024-12-23 11:51:38,484 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2024-12-23 11:51:38,484 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: True
2024-12-23 11:51:38,484 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'entry': 'limit', 'exit': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False, 'stoploss_on_exchange_interval': 60}
2024-12-23 11:51:38,484 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'entry': 'GTC', 'exit': 'GTC'}
2024-12-23 11:51:38,484 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2024-12-23 11:51:38,484 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: unlimited
2024-12-23 11:51:38,484 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2024-12-23 11:51:38,484 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 0
2024-12-23 11:51:38,484 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}
2024-12-23 11:51:38,484 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_exit_signal: True
2024-12-23 11:51:38,484 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_only: False
2024-12-23 11:51:38,484 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_entry_signal: False
2024-12-23 11:51:38,484 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_offset: 0.0
2024-12-23 11:51:38,484 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2024-12-23 11:51:38,484 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2024-12-23 11:51:38,484 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: False
2024-12-23 11:51:38,484 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1
2024-12-23 11:51:38,484 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_open_trades: 100
2024-12-23 11:51:38,484 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2024-12-23 11:51:38,487 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from '/Users/harshit/VS-Code/trading/freqtrade/.venv/lib/python3.11/site-packages/freqtrade/plugins/pairlist/StaticPairList.py'...
2024-12-23 11:51:38,488 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist AgeFilter from '/Users/harshit/VS-Code/trading/freqtrade/.venv/lib/python3.11/site-packages/freqtrade/plugins/pairlist/AgeFilter.py'...
2024-12-23 11:51:48,200 - freqtrade.optimize.backtesting - INFO - Using fee 0.1000% - worst case fee from exchange (lowest tier).
2024-12-23 11:51:48,739 - freqtrade.data.history.datahandlers.idatahandler - INFO - Price jump in STRAX/USDT, 12h, spot between two candles of 90.00% detected.
2024-12-23 11:51:48,741 - freqtrade.data.converter.converter - INFO - Missing data fillup for STRAX/USDT, 12h: before: 1014 - after: 1029 - 1.48%
2024-12-23 11:51:48,973 - freqtrade.data.history.datahandlers.idatahandler - INFO - Price jump in QUICK/USDT, 12h, spot between two candles of 99.90% detected.
2024-12-23 11:51:49,080 - freqtrade.data.history.datahandlers.idatahandler - INFO - Price jump in BNX/USDT, 12h, spot between two candles of 99.00% detected.
2024-12-23 11:51:49,082 - freqtrade.data.converter.converter - INFO - Missing data fillup for BNX/USDT, 12h: before: 1018 - after: 1029 - 1.08%
2024-12-23 11:51:49,467 - freqtrade.data.history.datahandlers.idatahandler - INFO - Price jump in AEUR/USDT, 12h, spot between two candles of 62.71% detected.
2024-12-23 11:51:49,469 - freqtrade.data.converter.converter - INFO - Missing data fillup for AEUR/USDT, 12h: before: 412 - after: 417 - 1.21%
2024-12-23 11:51:49,588 - freqtrade.data.history.datahandlers.idatahandler - WARNING - No history for LISTA/USDT, spot, 12h found. Use `freqtrade download-data` to download the data
2024-12-23 11:51:49,588 - freqtrade.data.history.datahandlers.idatahandler - WARNING - No history for ZRO/USDT, spot, 12h found. Use `freqtrade download-data` to download the data
2024-12-23 11:51:49,589 - freqtrade.data.history.datahandlers.idatahandler - WARNING - No history for G/USDT, spot, 12h found. Use `freqtrade download-data` to download the data
2024-12-23 11:51:49,589 - freqtrade.data.history.datahandlers.idatahandler - WARNING - No history for BANANA/USDT, spot, 12h found. Use `freqtrade download-data` to download the data
2024-12-23 11:51:49,589 - freqtrade.data.history.datahandlers.idatahandler - WARNING - No history for RENDER/USDT, spot, 12h found. Use `freqtrade download-data` to download the data
2024-12-23 11:51:49,589 - freqtrade.data.history.datahandlers.idatahandler - WARNING - No history for TON/USDT, spot, 12h found. Use `freqtrade download-data` to download the data
2024-12-23 11:51:49,589 - freqtrade.data.history.datahandlers.idatahandler - WARNING - No history for DOGS/USDT, spot, 12h found. Use `freqtrade download-data` to download the data
2024-12-23 11:51:49,590 - freqtrade.data.history.datahandlers.idatahandler - WARNING - No history for EURI/USDT, spot, 12h found. Use `freqtrade download-data` to download the data
2024-12-23 11:51:49,590 - freqtrade.data.history.datahandlers.idatahandler - WARNING - No history for SLF/USDT, spot, 12h found. Use `freqtrade download-data` to download the data
2024-12-23 11:51:49,590 - freqtrade.data.history.datahandlers.idatahandler - WARNING - No history for POL/USDT, spot, 12h found. Use `freqtrade download-data` to download the data
2024-12-23 11:51:49,590 - freqtrade.data.history.datahandlers.idatahandler - WARNING - No history for NEIRO/USDT, spot, 12h found. Use `freqtrade download-data` to download the data
2024-12-23 11:51:49,590 - freqtrade.data.history.datahandlers.idatahandler - WARNING - No history for TURBO/USDT, spot, 12h found. Use `freqtrade download-data` to download the data
2024-12-23 11:51:49,591 - freqtrade.data.history.datahandlers.idatahandler - WARNING - No history for 1MBABYDOGE/USDT, spot, 12h found. Use `freqtrade download-data` to download the data
2024-12-23 11:51:49,591 - freqtrade.data.history.datahandlers.idatahandler - WARNING - No history for CATI/USDT, spot, 12h found. Use `freqtrade download-data` to download the data
2024-12-23 11:51:49,591 - freqtrade.data.history.datahandlers.idatahandler - WARNING - No history for HMSTR/USDT, spot, 12h found. Use `freqtrade download-data` to download the data
2024-12-23 11:51:49,591 - freqtrade.data.history.datahandlers.idatahandler - WARNING - No history for EIGEN/USDT, spot, 12h found. Use `freqtrade download-data` to download the data
2024-12-23 11:51:49,591 - freqtrade.data.history.datahandlers.idatahandler - WARNING - No history for SCR/USDT, spot, 12h found. Use `freqtrade download-data` to download the data
2024-12-23 11:51:49,591 - freqtrade.data.history.datahandlers.idatahandler - WARNING - No history for BNSOL/USDT, spot, 12h found. Use `freqtrade download-data` to download the data
2024-12-23 11:51:49,592 - freqtrade.data.history.datahandlers.idatahandler - WARNING - No history for LUMIA/USDT, spot, 12h found. Use `freqtrade download-data` to download the data
2024-12-23 11:51:49,604 - freqtrade.optimize.backtesting - INFO - Loading data from 2023-02-01 00:00:00 up to 2024-06-29 00:00:00 (514 days).
2024-12-23 11:51:49,604 - freqtrade.configuration.timerange - WARNING - Moving start-date by 0 candles to account for startup time.
2024-12-23 11:51:49,604 - freqtrade.optimize.backtesting - INFO - Dataload complete. Calculating indicators
2024-12-23 11:51:49,605 - freqtrade.optimize.backtesting - WARNING - Backtest result caching disabled due to use of open-ended timerange.
2024-12-23 11:51:49,605 - freqtrade.optimize.backtesting - INFO - Running backtesting for Strategy GodStra
2024-12-23 11:51:49,605 - freqtrade.strategy.hyper - INFO - No params for protection found, using default values.
2024-12-23 11:52:20,460 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/Users/harshit/VS-Code/trading/freqtrade/.venv/lib/python3.11/site-packages/freqtrade/main.py", line 43, in main
    return_code = args["func"](args)
                  ^^^^^^^^^^^^^^^^^^
  File "/Users/harshit/VS-Code/trading/freqtrade/.venv/lib/python3.11/site-packages/freqtrade/commands/optimize_commands.py", line 60, in start_backtesting
    backtesting.start()
  File "/Users/harshit/VS-Code/trading/freqtrade/.venv/lib/python3.11/site-packages/freqtrade/optimize/backtesting.py", line 1616, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/harshit/VS-Code/trading/freqtrade/.venv/lib/python3.11/site-packages/freqtrade/optimize/backtesting.py", line 1526, in backtest_one_strategy
    preprocessed = self.strategy.advise_all_indicators(data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/harshit/VS-Code/trading/freqtrade/.venv/lib/python3.11/site-packages/freqtrade/strategy/interface.py", line 1575, in advise_all_indicators
    return {
           ^
  File "/Users/harshit/VS-Code/trading/freqtrade/.venv/lib/python3.11/site-packages/freqtrade/strategy/interface.py", line 1576, in <dictcomp>
    pair: self.advise_indicators(pair_data.copy(), {"pair": pair}).copy()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/harshit/VS-Code/trading/freqtrade/.venv/lib/python3.11/site-packages/freqtrade/strategy/interface.py", line 1610, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/harshit/VS-Code/trading/freqtrade/user_data/strategies/GodStra.py", line 94, in populate_indicators
    dataframe = add_all_ta_features(
                ^^^^^^^^^^^^^^^^^^^^
  File "/Users/harshit/VS-Code/trading/freqtrade/.venv/lib/python3.11/site-packages/ta/wrapper.py", line 589, in add_all_ta_features
    df = add_trend_ta(
         ^^^^^^^^^^^^^
  File "/Users/harshit/VS-Code/trading/freqtrade/.venv/lib/python3.11/site-packages/ta/wrapper.py", line 343, in add_trend_ta
    df[f"{colprefix}trend_adx"] = indicator_adx.adx()
                                  ^^^^^^^^^^^^^^^^^^^
  File "/Users/harshit/VS-Code/trading/freqtrade/.venv/lib/python3.11/site-packages/ta/trend.py", line 807, in adx
    adx_series[self._window] = directional_index[0 : self._window].mean()
    ~~~~~~~~~~^^^^^^^^^^^^^^
IndexError: index 14 is out of bounds for axis 0 with size 1
  ```

**Comment by xmatthias** [comment]
Age-filter doesn't support backtesting as it's based on current (today's) data.

While your backtest is limited form 2023-02-01 00:00:00 up to 2024-06-29 00:00:00 - AgeFilter considers today's data - so by today's standards, each of the that were available in June would fit the "age-filter" categorization.


---

On top of that your version is half a year old - using a newer version would highlight this and would fail to run backtesting, as we added indicators to each filter if they support backtesting or not.

**Comment by curiousHG** [comment]
@xmatthias is there a way I can ignore the pairs which have number of days less than 60 while backtesting?

**Comment by xmatthias** [comment]
You can use test-pairlist with AgeFilter to get a current pairlist.
but this assumes that your backtest ends "today".

An alternative might be to do the math yourself ("days between backtest end date and today" + 60) and use that as filter.

it's however not something freqtrade can do out of the box.
