### ISSUE TITLE
Restarting with no meaningful logs except worker found ... calling exit

### ISSUE THREAD

**Issue by erickaby** [freqtrade/freqtrade#11148]
## Describe your environment

  * Operating system: gcloud cloud run (linux) 
  * Python Version: 3.12.7
  * CCXT version: 4.4.40
  * Freqtrade Version: freqtrade docker-2024.12-dev-d9927724
  
## Describe the problem:

Currently running a live trading instance as prod in gcs cloud run it is running with a postgres db. I have been experiencing the process dying every couple hours or so and can't seem to track it down. Metrics look fine running on 1.5GiB mem and 1cpu, I have only been able to track to the time of exit which is displayed in the logs with no indication of the reasoning. Would be great to get any help to debug this. 

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
DEFAULT 2024-12-25T10:19:40.479822Z 2024-12-25 10:19:40,479 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='docker-2024.12-dev-503305cb', state='RUNNING'
DEFAULT 2024-12-25T10:20:40.481503Z 2024-12-25 10:20:40,480 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='docker-2024.12-dev-503305cb', state='RUNNING'
DEFAULT 2024-12-25T10:21:36.958229Z time="25/12/2024 10:21:36.956240" severity=INFO message="Starting a garbage collection run."
DEFAULT 2024-12-25T10:21:36.994799Z time="25/12/2024 10:21:36.993421" severity=INFO message="Garbage collection succeeded after deleted 0 objects in 36.59899ms."
DEFAULT 2024-12-25T10:21:40.483151Z 2024-12-25 10:21:40,482 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='docker-2024.12-dev-503305cb', state='RUNNING'
DEFAULT 2024-12-25T10:22:40.484839Z 2024-12-25 10:22:40,484 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='docker-2024.12-dev-503305cb', state='RUNNING'
DEFAULT 2024-12-25T10:23:40.486523Z 2024-12-25 10:23:40,485 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='docker-2024.12-dev-503305cb', state='RUNNING'
DEFAULT 2024-12-25T10:24:40.488181Z 2024-12-25 10:24:40,487 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='docker-2024.12-dev-503305cb', state='RUNNING'
DEFAULT 2024-12-25T10:25:40.489861Z 2024-12-25 10:25:40,489 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='docker-2024.12-dev-503305cb', state='RUNNING'
DEFAULT 2024-12-25T10:26:40.491524Z 2024-12-25 10:26:40,490 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='docker-2024.12-dev-503305cb', state='RUNNING'
DEFAULT 2024-12-25T10:27:00.243401Z 2024-12-25 10:27:00,242 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
DEFAULT 2024-12-25T10:27:00.243422Z 2024-12-25 10:27:00,242 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
  ```

**Comment by xmatthias** [comment]
if there's no additional log "below" this - then it's quite likely that something sent an exit signal to the bot.
The exit looks as if something terminated it - like - if you call `docker compose down` - it'll look essentially identical.

If you say it's happening every few hours, it's most likely a timeout of the platform you're running this on.

**Comment by erickaby** [comment]
Thanks for the reply, I am going to try another approach and run it locally for now to see if the issue persists. My assumption is that there is something going on with the database and how gcs cloudrun rollouts new versions but ill update here with anymore findings. Here are some actual error logs I found but this didn't occur in the logs every other time it exited.

```
2024-12-26 06:17:02.564
2024-12-25 19:47:02,543 - freqtrade.freqtradebot - ERROR - Error during cleanup
2024-12-26 06:17:02.564
Traceback (most recent call last):   File "/freqtrade/freqtrade/commands/trade_commands.py", line 25, in start_trading     worker.run()   File "/freqtrade/freqtrade/worker.py", line 79, in run     state = self._worker(old_state=state)
2024-12-26 06:17:02.564
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-26 06:17:02.564
  File "/freqtrade/freqtrade/worker.py", line 120, in _worker
2024-12-26 06:17:02.564
    self._throttle(
2024-12-26 06:17:02.564
  File "/freqtrade/freqtrade/worker.py", line 161, in _throttle
2024-12-26 06:17:02.564
    result = func(*args, **kwargs)
2024-12-26 06:17:02.564
             ^^^^^^^^^^^^^^^^^^^^^
2024-12-26 06:17:02.564
  File "/freqtrade/freqtrade/worker.py", line 195, in _process_running
2024-12-26 06:17:02.564
    self.freqtrade.process()
2024-12-26 06:17:02.564
  File "/freqtrade/freqtrade/freqtradebot.py", line 289, in process
2024-12-26 06:17:02.564
    self.exit_positions(trades)
2024-12-26 06:17:02.564
  File "/freqtrade/freqtrade/freqtradebot.py", line 1281, in exit_positions
2024-12-26 06:17:02.564
    not trade.has_open_orders
2024-12-26 06:17:02.564
        ^^^^^^^^^^^^^^^^^^^^^
2024-12-26 06:17:02.564
  File "/freqtrade/freqtrade/persistence/trade_model.py", line 598, in has_open_orders
2024-12-26 06:17:02.564
    o for o in self.orders if o.ft_order_side not in ["stoploss"] and o.ft_is_open
2024-12-26 06:17:02.564
               ^^^^^^^^^^^
2024-12-26 06:17:02.564
  File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/orm/attributes.py", line 566, in __get__
2024-12-26 06:17:02.564
    return self.impl.get(state, dict_)  # type: ignore[no-any-return]
2024-12-26 06:17:02.564
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-26 06:17:02.564
  File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/orm/attributes.py", line 1086, in get
2024-12-26 06:17:02.564
    value = self._fire_loader_callables(state, key, passive)
2024-12-26 06:17:02.564
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-26 06:17:02.564
  File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/orm/attributes.py", line 1121, in _fire_loader_callables
2024-12-26 06:17:02.564
    return self.callable_(state, passive)
2024-12-26 06:17:02.564
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-26 06:17:02.564
  File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/orm/strategies.py", line 978, in _load_for_state
2024-12-26 06:17:02.564
    return self._emit_lazyload(
2024-12-26 06:17:02.564
           ^^^^^^^^^^^^^^^^^^^^
2024-12-26 06:17:02.564
  File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/orm/strategies.py", line 1109, in _emit_lazyload
2024-12-26 06:17:02.564
    lazy_clause, params = self._generate_lazy_clause(state, passive)
2024-12-26 06:17:02.564
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-26 06:17:02.564
  File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/orm/strategies.py", line 858, in _generate_lazy_clause
2024-12-26 06:17:02.564
    value = mapper._get_state_attr_by_column(
2024-12-26 06:17:02.564
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-26 06:17:02.564
  File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 3592, in _get_state_attr_by_column
2024-12-26 06:17:02.564
    return state.manager[prop.key].impl.get(state, dict_, passive=passive)
2024-12-26 06:17:02.564
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-26 06:17:02.564
  File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/orm/attributes.py", line 1086, in get
2024-12-26 06:17:02.564
    value = self._fire_loader_callables(state, key, passive)
2024-12-26 06:17:02.564
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-26 06:17:02.564
  File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/orm/attributes.py", line 1116, in _fire_loader_callables
2024-12-26 06:17:02.564
    return state._load_expired(state, passive)
2024-12-26 06:17:02.564
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-26 06:17:02.564
  File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 803, in _load_expired
2024-12-26 06:17:02.564
    self.manager.expired_attribute_loader(self, toload, passive)
2024-12-26 06:17:02.564
  File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/orm/loading.py", line 1670, in load_scalar_attributes
2024-12-26 06:17:02.564
    result = load_on_ident(
2024-12-26 06:17:02.564
             ^^^^^^^^^^^^^^
2024-12-26 06:17:02.564
  File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/orm/loading.py", line 509, in load_on_ident
2024-12-26 06:17:02.564
    return load_on_pk_identity(
2024-12-26 06:17:02.564
           ^^^^^^^^^^^^^^^^^^^^
2024-12-26 06:17:02.564
  File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/orm/loading.py", line 694, in load_on_pk_identity
2024-12-26 06:17:02.564
    session.execute(
2024-12-26 06:17:02.564
  File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2362, in execute
2024-12-26 06:17:02.564
    return self._execute_internal(
2024-12-26 06:17:02.564
           ^^^^^^^^^^^^^^^^^^^^^^^
2024-12-26 06:17:02.564
  File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2247, in _execute_internal
2024-12-26 06:17:02.564
    result: Result[Any] = compile_state_cls.orm_execute_statement(
2024-12-26 06:17:02.564
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-26 06:17:02.564
  File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 305, in orm_execute_statement
2024-12-26 06:17:02.564
    result = conn.execute(
2024-12-26 06:17:02.564
             ^^^^^^^^^^^^^
2024-12-26 06:17:02.564
  File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
2024-12-26 06:17:02.564
    return meth(
2024-12-26 06:17:02.564
           ^^^^^
2024-12-26 06:17:02.564
  File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
2024-12-26 06:17:02.564
    return connection._execute_clauseelement(
2024-12-26 06:17:02.564
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-26 06:17:02.564
  File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
2024-12-26 06:17:02.564
    ret = self._execute_context(
2024-12-26 06:17:02.564
          ^^^^^^^^^^^^^^^^^^^^^^
2024-12-26 06:17:02.564
  File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
2024-12-26 06:17:02.564
    return self._exec_single_context(
2024-12-26 06:17:02.564
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-26 06:17:02.564
  File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
2024-12-26 06:17:02.564
    self._handle_dbapi_exception(
2024-12-26 06:17:02.564
  File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2358, in _handle_dbapi_exception
2024-12-26 06:17:02.564
    raise exc_info[1].with_traceback(exc_info[2])
2024-12-26 06:17:02.564
  File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
2024-12-26 06:17:02.564
    self.dialect.do_execute(
2024-12-26 06:17:02.564
  File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
2024-12-26 06:17:02.564
    cursor.execute(statement, parameters)
2024-12-26 06:17:02.564
  File "/usr/local/lib/python3.12/encodings/utf_8.py", line 15, in decode
2024-12-26 06:17:02.564
    def decode(input, errors='strict'):
```

**Comment by erickaby** [comment]
Getting the same behaviour locally looks like it has to do with postgres

```
│ bot-01-0   File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1418, in execute                                                                                                                          │
│ bot-01-0     return meth(                                                                                                                                                                                                                    │
│ bot-01-0            ^^^^^                                                                                                                                                                                                                    │
│ bot-01-0   File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection                                                                                                           │
│ bot-01-0     return connection._execute_clauseelement(                                                                                                                                                                                       │
│ bot-01-0            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                       │
│ bot-01-0   File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement                                                                                                           │
│ bot-01-0     ret = self._execute_context(                                                                                                                                                                                                    │
│ bot-01-0           ^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                                    │
│ bot-01-0   File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context                                                                                                                 │
│ bot-01-0     return self._exec_single_context(                                                                                                                                                                                               │
│ bot-01-0            ^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                               │
│ bot-01-0   File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context                                                                                                             │
│ bot-01-0     self._handle_dbapi_exception(                                                                                                                                                                                                   │
│ bot-01-0   File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception                                                                                                          │
│ bot-01-0     raise sqlalchemy_exception.with_traceback(exc_info[2]) from e                                                                                                                                                                   │
│ bot-01-0   File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context                                                                                                             │
│ bot-01-0     self.dialect.do_execute(                                                                                                                                                                                                        │
│ bot-01-0   File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute                                                                                                                     │
│ bot-01-0     cursor.execute(statement, parameters)                                                                                                                                                                                           │
│ bot-01-0 sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) SSL SYSCALL error: EOF detected                                                                                                                                        │
│ bot-01-0                                                                                                                                                                                                                                     │
│ bot-01-0 [SQL: SELECT trades.id AS trades_id, trades.exchange AS trades_exchange, trades.pair AS trades_pair, trades.base_currency AS trades_base_currency, trades.stake_currency AS trades_stake_currency, trades.is_open AS trades_is_open │
│ bot-01-0 FROM trades                                                                                                                                                                                                                         │
│ bot-01-0 WHERE trades.id = %(pk_1)s]                                                                                                                                                                                                         │
│ bot-01-0 [parameters: {'pk_1': 34}]
```

**Comment by erickaby** [comment]
Did some more digging on that error above on the managed postgres provider im using **Neon** and found in their docs details about the error i am seeing. https://neon.tech/docs/guides/sqlalchemy#sqlalchemy-connection-errors

> If you encounter an `SSL SYSCALL error: EOF detected` when connecting to the database, this typically happens because the application is trying to reuse a connection after the Neon compute has been suspended due to inactivity. To resolve this issue, try one of the following options:
> 
> - Set the SQLAlchemy pool_recycle parameter to a value less than or equal to the scale to zero setting configured for your compute.
> - Set the SQLAlchemy pool_pre_ping parameter to true. This ensures that your engine checks if the connection is alive before executing a query.
> For more details on the pool_recycle and pool_pre_ping parameters, refer to [SQLAlchemy: Connection Pool Configuration](https://docs.sqlalchemy.org/en/20/core/pooling.html#connection-pool-configuration) and [Dealing with Disconnects](https://docs.sqlalchemy.org/en/20/core/pooling.html#connection-pool-configuration). For information on configuring Neon's scale to zero setting, see [Configuring Scale to Zero for Neon computes](https://neon.tech/docs/guides/scale-to-zero-guide)

So it looks to be a problem on my end.

Is there any implementation to configure the parameter above in freqtrade? I will be looking into sqlalchemy to see if there is any env vars I can use to configure it.
