### ISSUE TITLE
sqlite3.OperationalError no such column: trades.sell_reason

### ISSUE THREAD

**Issue by baudbox** [freqtrade/freqtrade#1121]
## Step 1: Describe your environment

  * Python Version: Python 3.6.3
  * CCXT version: ccxt==1.17.66
  * Branch: Develop
  * Last Commit ID: a586a7526e63a1544d1be5e2870c21dc671847f7
  
## Step 3: Describe the problem:
Stopped current process and update the develop branch to the latest commit, then install requirement and install freqtrade. Re ran 
 
### Observed Results:

Bot ran then died with following error:

  ```
sqlite3.OperationalError: no such column: trades.sell_reason

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./freqtrade/main.py", line 49, in main
    state = freqtrade.worker(old_state=state)
  File "/opt/freqtrade.prod1/freqtrade/freqtradebot.py", line 110, in worker
    nb_assets=nb_assets)
  File "/opt/freqtrade.prod1/freqtrade/freqtradebot.py", line 122, in _throttle
    result = func(*args, **kwargs)
  File "/opt/freqtrade.prod1/freqtrade/freqtradebot.py", line 150, in _process
    trades = Trade.query.filter(Trade.is_open.is_(True)).all()
  File "/opt/freqtrade.prod1/.env/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2836, in all
    return list(self)
  File "/opt/freqtrade.prod1/.env/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2988, in __iter__
    return self._execute_and_instances(context)
  File "/opt/freqtrade.prod1/.env/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3011, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/opt/freqtrade.prod1/.env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/opt/freqtrade.prod1/.env/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/freqtrade.prod1/.env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/opt/freqtrade.prod1/.env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/opt/freqtrade.prod1/.env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/opt/freqtrade.prod1/.env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/freqtrade.prod1/.env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/opt/freqtrade.prod1/.env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/opt/freqtrade.prod1/.env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: trades.sell_reason [SQL: 'SELECT trades.id AS trades_id, trades.exchange AS trades_exchange, trades.pair AS trades_pair, trades.is_open AS trades_is_open, trades.fee_open AS trades_fee_open, trades.fee_close AS trades_fee_close, trades.open_rate AS trades_open_rate, trades.open_rate_requested AS trades_open_rate_requested, trades.close_rate AS trades_close_rate, trades.close_rate_requested AS trades_close_rate_requested, trades.close_profit AS trades_close_profit, trades.stake_amount AS trades_stake_amount, trades.amount AS trades_amount, trades.open_date AS trades_open_date, trades.close_date AS trades_close_date, trades.open_order_id AS trades_open_order_id, trades.stop_loss AS trades_stop_loss, trades.initial_stop_loss AS trades_initial_stop_loss, trades.max_rate AS trades_max_rate, trades.sell_reason AS trades_sell_reason, trades.strategy AS trades_strategy, trades.ticker_interval AS trades_ticker_interval \nFROM trades \nWHERE trades.is_open IS 1'] (Background on this error at: http://sqlalche.me/e/e3q8)
2018-08-04 08:00:33,401 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2018-08-04 08:00:33,402 - freqtrade.rpc.rpc_manager - DEBUG - Forwarding message to rpc.telegram
2018-08-04 08:00:33,459 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2018-08-04 08:00:33,460 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
2018-08-04 08:00:33,461 - freqtrade.rpc.rpc_manager - DEBUG - Cleaning up rpc.telegram ...
2018-08-04 08:00:33,462 - JobQueue - DEBUG - JobQueue thread stopped
  ```
## Additionnal information

Current db status
```
(.env) root@centos-rpi3:/opt/freqtrade.prod1 #  sqlite3 tradesv3.sqlite
SQLite version 3.7.17 2013-05-20 00:56:22
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite> .tables
trades       trades_bak0
sqlite> .schema trades
CREATE TABLE trades (
        id INTEGER NOT NULL,
        exchange VARCHAR NOT NULL,
        pair VARCHAR NOT NULL,
        is_open BOOLEAN NOT NULL,
        fee_open FLOAT NOT NULL,
        fee_close FLOAT NOT NULL,
        open_rate FLOAT,
        open_rate_requested FLOAT,
        close_rate FLOAT,
        close_rate_requested FLOAT,
        close_profit FLOAT,
        stake_amount FLOAT NOT NULL,
        amount FLOAT,
        open_date DATETIME NOT NULL,
        close_date DATETIME,
        open_order_id VARCHAR,
        stop_loss FLOAT,
        initial_stop_loss FLOAT,
        max_rate FLOAT,
        PRIMARY KEY (id),
        CHECK (is_open IN (0, 1))
);
sqlite>

(.env) root@centos-rpi3:/opt/freqtrade.prod1 #  sqlite3 -header tradesv3.sqlite "SELECT * FROM trades;"
id|exchange|pair|is_open|fee_open|fee_close|open_rate|open_rate_requested|close_rate|close_rate_requested|close_profit|stake_amount|amount|open_date|close_date|open_order_id|stop_loss|initial_stop_loss|max_rate
1|binance|ETH/BTC|0|0.001|0.001|0.064877|0.064877|0.064626|0.064626|-0.00585912|0.003|0.046|2018-07-18 20:41:14.598699|2018-07-18 21:05:39.438703||0.0454139|0.0454139|0.064877
```

**Comment by xmatthias** [comment]
sorry for the issues you faced. 
thanks to your description i was able to recreate the issue and I just submitted a PR for problem, it's a issue with a database migration which was missed with the last DB update.

it should be merged shortly, then it will work again.

**Comment by baudbox** [comment]
Thanks for your hard job on that and everything else. Appreciate.
Will wait until PR merged before and let you know.

**Comment by xmatthias** [comment]
The pr is merged now - please retry.
feel free to reopen if the problem persists with the latest code.
