### ISSUE TITLE
AttributeError: Can't pickle local object 'Hyperopt.buy_strategy_generator.<locals>.populate_buy_trend'

### ISSUE THREAD

**Issue by lploumen** [freqtrade/freqtrade#1133]
Hi,
I got this problem when trying to run hyperopt on Ubuntu (no docker, using the setup script) using the command  python3.6 freqtrade/main.py hyperopt :
```
2018-08-08 10:33:15,274 - freqtrade.optimize.hyperopt - INFO - Found 1 CPU cores. Let's make them scream!
.Traceback (most recent call last):
  File "freqtrade/main.py", line 89, in <module>
    main(sys.argv[1:])
  File "freqtrade/main.py", line 35, in main
    args.func(args)
  File "/home/zen/freqtrade/freqtrade/optimize/hyperopt.py", line 407, in start
    hyperopt.start()
  File "/home/zen/freqtrade/freqtrade/optimize/hyperopt.py", line 368, in start
    f_val = self.run_optimizer_parallel(parallel, asked)
  File "/home/zen/freqtrade/freqtrade/optimize/hyperopt.py", line 332, in run_optimizer_parallel
    return parallel(delayed(self.generate_optimizer)(v) for v in asked)
  File "/home/zen/freqtrade/.env/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py", line 779, in __call__
    while self.dispatch_one_batch(iterator):
  File "/home/zen/freqtrade/.env/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py", line 620, in dispatch_one_batch
    tasks = BatchedCalls(itertools.islice(iterator, batch_size))
  File "/home/zen/freqtrade/.env/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py", line 127, in __init__
    self.items = list(iterator_slice)
  File "/home/zen/freqtrade/freqtrade/optimize/hyperopt.py", line 332, in <genexpr>
    return parallel(delayed(self.generate_optimizer)(v) for v in asked)
  File "/home/zen/freqtrade/.env/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py", line 183, in delayed
    pickle.dumps(function)
AttributeError: Can't pickle local object 'Hyperopt.buy_strategy_generator.<locals>.populate_buy_trend'
```
Note that I can run it and also backtest. I just got this error with hyperopt.
Have you ever see this error ?

**Comment by lploumen** [comment]
I just tried with docker and got the same problem

**Comment by xmatthias** [comment]
`Hyperopt.buy_strategy_generator..populate_buy_trend` ... you really have a "double-dot" in there?
if yes, then i think you have a syntax error.

also - hyperopt requires changes to the file itself - i guess one of these could have caused an issue (probably the changes to `populate_buy_trend`)

**Comment by dawidvdh** [comment]
Have the exact same issue, except no "double-dot":

```
Traceback (most recent call last):
  File "/usr/local/bin/freqtrade", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/freqtrade/bin/freqtrade", line 7, in <module>
    main(sys.argv[1:])
  File "/freqtrade/freqtrade/main.py", line 35, in main
    args.func(args)
  File "/freqtrade/freqtrade/optimize/hyperopt.py", line 796, in start
    hyperopt.start()
  File "/freqtrade/freqtrade/optimize/hyperopt.py", line 757, in start
    f_val = self.run_optimizer_parallel(parallel, asked)
  File "/freqtrade/freqtrade/optimize/hyperopt.py", line 721, in run_optimizer_parallel
    return parallel(delayed(self.generate_optimizer)(v) for v in asked)
  File "/usr/local/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py", line 779, in __call__
    while self.dispatch_one_batch(iterator):
  File "/usr/local/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py", line 620, in dispatch_one_batch
    tasks = BatchedCalls(itertools.islice(iterator, batch_size))
  File "/usr/local/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py", line 127, in __init__
    self.items = list(iterator_slice)
  File "/freqtrade/freqtrade/optimize/hyperopt.py", line 721, in <genexpr>
    return parallel(delayed(self.generate_optimizer)(v) for v in asked)
  File "/usr/local/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py", line 183, in delayed
    pickle.dumps(function)
AttributeError: Can't pickle local object 'Hyperopt.buy_strategy_generator.<locals>.populate_buy_trend'
```

**Comment by xmatthias** [comment]
would you please paste your `populate_buy_trend` in hyperopt.

if you don't want to share all, try to get the line-count down to as few as possible. the "default" file does work as is, so without knowing your modifications it's impossible to recreate within reasonable time.
thanks

**Comment by ustuzou** [comment]
xmatthias, would you please check briefly if default hyperopt file works correclty? Do not know if this thread was closed but i am getting same error as above using the custom file. from the repo.

**Comment by xmatthias** [comment]
@ustuzou i need a few more informations:
* what's the exact command you are running?
* which python version (3.6, 3.7)

**Comment by ustuzou** [comment]
- command i am using: 'python3 ./freqtrade/main.py -c config.json hyperopt -e 5000'
- 3.6

thks

**Comment by xmatthias** [comment]
on the current develop branch in a clean virtualenv, on a clean
git checkout (when running `git status` - no file is showing as changed) - pulled and installed dependencies 2 minutes ago, with python 3.6.6 on linux i have no issues (although i used 50 iterations instead of 5000  to have it finish without me waiting for a while).

Also travis-ci executes hyperopt with each test run - so the default configuration (no change) should work.

try to run the following command - it's the command that travis-ci runs.

```
python freqtrade/main.py --datadir freqtrade/tests/testdata --config config.json.example hyperopt -e 5
```

it completes successfully on my system, so the default works.

If i run it for `-e 5` - or `-e 5000` does not matter - it pickles only once (or at least it should).

One thing to note: my pc has 4 cores (8 with hyperthreading) - and 16G of ram - so if you are trying this on a undersized VM it could cause problems - i never tried to run it on anything below 2G of ram.

**Comment by xmatthias** [comment]
Thanks to @ustuzou we found out that hyperopt seems to crash with the above exception when used with only 1 CPU Core.

Since the minimum requirements are documented in the [readme](https://github.com/freqtrade/freqtrade#min-hardware-required) with 2G of RAM, and 2vCPUs, i think i can close this issue.

Freqtrade itself may work with 1 cpu core - but hyperopt is VERY resource hungry - so requiring 2 vCPU's should not be an issue - it won't finish this lifetime otherwise anyway.

I'll close this for now as the initial logs show only 1 available cpu.
If you feel this has another reason feel free to reopen.

**Comment by areffallah** [comment]
I had the same issue. it seems like even if "hyperopt_jobs = 1" is defined in config.json, freqtrade will still update the config to use multiple CPUs. A work around I used was to add the following line in hyperopt.py\def start after `config_jobs = self.config.get('hyperopt_jobs',-1)`:

`config_jobs = 1`

**Comment by xmatthias** [comment]
This is only necessary if you use an outdated version of freqtrade.
