### ISSUE TITLE
Fatal exception when using 'market' order type 

### ISSUE THREAD

**Issue by asheetov** [freqtrade/freqtrade#1428]
* Python Version: 3.6.7
  * CCXT version: 1.17.363
  * Branch: Develop
  * Last Commit ID: c38a1d0324c077becf9ce489f85154c46716ecac
  
**Bot exits with fatal exception after executing sell order**

  1. Edit config.json
  1. Set small value for "stoploss" option like -0.001
  1. Set parameter "forcebuy_enable" to value true
  1. Find out or add "order_type" options dict
  1. Set value "stoploss": "market" inside the order_type
  1. Save the config.json
  1. Start the bot
  1. Let the bot to buy some currency by RPC command /forcebuy
  1. Wait for sell order caused by stoploss
  
*After selling the currency bot raises the following fatal exception:*

  ```
2018-12-24 05:12:17,744 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/san/freqtrade/freqtrade/main.py", line 49, in main
    state = freqtrade.worker(old_state=state)
  File "/home/san/freqtrade/freqtrade/freqtradebot.py", line 122, in worker
    min_secs=min_secs)
  File "/home/san/freqtrade/freqtrade/freqtradebot.py", line 134, in _throttle
    result = func(*args, **kwargs)
  File "/home/san/freqtrade/freqtrade/freqtradebot.py", line 181, in _process
    state_changed |= self.process_maybe_execute_sell(trade)
  File "/home/san/freqtrade/freqtrade/freqtradebot.py", line 528, in process_maybe_execute_sell
    trade.update(order)
  File "/home/san/freqtrade/freqtrade/persistence.py", line 262, in update
    raise ValueError(f'Unknown order type: {order_type}')
ValueError: Unknown order type: market
  ```

**Comment by mishaker** [comment]
Duplicate with #1427 but thanks for reporting !

**Comment by xmatthias** [comment]
i'll close this in favor of #1427 - but it's a 100% duplicate and will be fixed!
