### ISSUE TITLE
failed to place stop loss on coin with very low value (tight stop loss)

### ISSUE THREAD

**Issue by gaugau3000** [freqtrade/freqtrade#1520]
Step 1: Have you search for this issue before posting it?
Yes

Step 2: Describe your environment
Python Version: 3.7.2 (python -V)
CCXT version: 1.18.102 (pip freeze | grep ccxt)
Branch: Develop
Last Commit ID: id image docker image ebfd99410421 (git log --format="%H" -n 1)
Debian 9 64 bit
Docker version 17.05.0-ce, build 89658be

Echange : binance

Step 3: Describe the problem:

  "order_types": {
        "buy": "limit",
        "sell": "market",
        "stoploss": "limit",
        "stoploss_on_exchange": true
    }

Sometimes for some trades freqtrade don't succeed to create a stop order (for the the stop loss) and create only the buy limit order

for info the stoploss the very tight in this strategy : -0.0037

Steps to reproduce:

Don't know

Observed Results:

What happened?

Stop the running contener

What did you expect to happen?

Place the stop order on exchange when create the buy limit order.

Relevant code exceptions or logs:

2019-01-28 05:31:16,272 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': buy, 'exchange': 'Binance', 'pair': 'NPXS/BTC', 'market_url': 'https://www.binance.com/tradeDetail.html?symbol=NPXS_BTC', 'limit': 1.9e-07, 'stake_amount': 0.07999988, 'stake_currency': 'BTC', 'fiat_currency': 'USD'}
2019-01-28 05:31:16,976 - freqtrade.wallets - INFO - Wallets synced ...
2019-01-28 05:31:18,835 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'OperationalException:\n```\nTraceback (most recent call last):\n  File "/freqtrade/freqtrade/freqtradebot.py", line 174, in _process\n    state_changed |= self.process_maybe_execute_sell(trade)\n  File "/freqtrade/freqtrade/freqtradebot.py", line 505, in process_maybe_execute_sell\n    result = self.handle_stoploss_on_exchange(trade)\n  File "/freqtrade/freqtrade/freqtradebot.py", line 637, in handle_stoploss_on_exchange\n    pair=trade.pair, amount=trade.amount, stop_price=stop_price, rate=limit_price\n  File "/freqtrade/freqtrade/exchange/__init__.py", line 385, in stoploss_limit\n    \'In stoploss limit order, stop price should be more than limit price\')\nfreqtrade.OperationalException: In stoploss limit order, stop price should be more than limit price\n```Issue `/start` if you think it is safe to restart.'}
2019-01-28 05:31:18,889 - freqtrade.rpc.telegram - WARNING - Telegram NetworkError: Can't parse entities: can't find end of the entity starting at byte offset 766! Trying one more time.
2019-01-28 05:31:18,937 - freqtrade.rpc.telegram - WARNING - TelegramError: Can't parse entities: can't find end of the entity starting at byte offset 766! Giving up on that message.
2019-01-28 05:31:18,938 - freqtrade.freqtradebot - ERROR - OperationalException. Stopping trader ...
Traceback (most recent call last):
  File "/freqtrade/freqtrade/freqtradebot.py", line 174, in _process
    state_changed |= self.process_maybe_execute_sell(trade)
  File "/freqtrade/freqtrade/freqtradebot.py", line 505, in process_maybe_execute_sell
    result = self.handle_stoploss_on_exchange(trade)
  File "/freqtrade/freqtrade/freqtradebot.py", line 637, in handle_stoploss_on_exchange
    pair=trade.pair, amount=trade.amount, stop_price=stop_price, rate=limit_price
  File "/freqtrade/freqtrade/exchange/__init__.py", line 385, in stoploss_limit
    'In stoploss limit order, stop price should be more than limit price')
freqtrade.OperationalException: In stoploss limit order, stop price should be more than limit price
2019-01-28 05:31:21,983 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'stopped'}

**Comment by joshyOcuk** [comment]
i also found this issue with hot/btc pair, is there a way to fix or just remove pair from whitelist?

**Comment by joshyOcuk** [comment]
i understand that the bot is doing as it should, however when this occurs it causes the bot to stop so maybe extra logic is needed like

(pseudo code incoming)

if trade.open.value === stoploss.value { cancel stoploss} 

hot was one of my best performing in backtesting but i do understand your point

cheers

**Comment by xmatthias** [comment]
By enabling #1596 in combination with dynamic whitelist, this problem should be fixed.

feel free to reopen if you think differently.
