### ISSUE TITLE
freqtrade - ERROR - Fatal exception!

### ISSUE THREAD

**Issue by Prossi79** [freqtrade/freqtrade#1646]
* Python Version: 3.6.7
  * CCXT version:  1.18.347
  * Branch: Master 

  
## Step 3: Describe the problem:

"Process died' - what happened here?

I was in "production run" on Binance and the bot crashed. You would need my config file too for analysis?

```
2019-03-10 08:43:37,687 - freqtrade.freqtradebot - INFO - Using order book for selling...
2019-03-10 08:43:37,996 - freqtrade.freqtradebot - INFO -   order book asks top 1: 0.00007968
2019-03-10 08:43:37,996 - freqtrade.freqtradebot - INFO -   order book asks top 2: 0.00007969
2019-03-10 08:43:37,997 - freqtrade.freqtradebot - INFO -   order book asks top 3: 0.00007971
2019-03-10 08:43:37,998 - freqtrade.freqtradebot - INFO -   order book asks top 4: 0.00007972
2019-03-10 08:43:37,999 - freqtrade.freqtradebot - INFO -   order book asks top 5: 0.00007973
2019-03-10 08:43:38,000 - freqtrade.freqtradebot - INFO -   order book asks top 6: 0.00007974
2019-03-10 08:43:38,000 - freqtrade.freqtradebot - INFO -   order book asks top 7: 0.00007975
2019-03-10 08:43:38,000 - freqtrade.freqtradebot - INFO -   order book asks top 8: 0.00007976
2019-03-10 08:43:38,001 - freqtrade.freqtradebot - INFO -   order book asks top 9: 0.00007977
2019-03-10 08:43:38,001 - freqtrade.freqtradebot - INFO -   order book asks top 10: 0.00007978
2019-03-10 08:43:38,002 - freqtrade.freqtradebot - INFO - Using order book for selling...
2019-03-10 08:43:38,485 - freqtrade.freqtradebot - INFO -   order book asks top 1: 0.00025753
2019-03-10 08:43:38,992 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/root/freqtrade/.env/lib/python3.6/site-packages/ccxt/base/exchange.py", line 493, in fetch
    response.raise_for_status()
  File "/root/freqtrade/.env/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/freqtrade/freqtrade/exchange/__init__.py", line 351, in sell
    return self._api.create_order(pair, ordertype, 'sell', amount, rate)
  File "/root/freqtrade/.env/lib/python3.6/site-packages/ccxt/binance.py", line 804, in create_order
    response = getattr(self, method)(self.extend(order, params))
  File "/root/freqtrade/.env/lib/python3.6/site-packages/ccxt/base/exchange.py", line 388, in inner
    return entry(_self, **inner_kwargs)
  File "/root/freqtrade/.env/lib/python3.6/site-packages/ccxt/binance.py", line 1227, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/root/freqtrade/.env/lib/python3.6/site-packages/ccxt/base/exchange.py", line 413, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/root/freqtrade/.env/lib/python3.6/site-packages/ccxt/base/exchange.py", line 505, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, headers, http_response, json_response)
  File "/root/freqtrade/.env/lib/python3.6/site-packages/ccxt/binance.py", line 1217, in handle_errors
    raise InsufficientFunds(self.id + ' ' + body)
ccxt.base.errors.InsufficientFunds: binance {"code":-2010,"msg":"Account has insufficient balance for requested action."}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./freqtrade/main.py", line 49, in main
    state = freqtrade.worker(old_state=state)
  File "/root/freqtrade/freqtrade/freqtradebot.py", line 129, in worker
    min_secs=min_secs)
  File "/root/freqtrade/freqtrade/freqtradebot.py", line 141, in _throttle
    result = func(*args, **kwargs)
  File "/root/freqtrade/freqtrade/freqtradebot.py", line 182, in _process
    state_changed |= self.process_maybe_execute_sell(trade)
  File "/root/freqtrade/freqtrade/freqtradebot.py", line 514, in process_maybe_execute_sell
    result = self.handle_trade(trade)
  File "/root/freqtrade/freqtrade/freqtradebot.py", line 600, in handle_trade
    if self.check_sell(trade, sell_rate, buy, sell):
  File "/root/freqtrade/freqtrade/freqtradebot.py", line 691, in check_sell
    self.execute_sell(trade, sell_rate, should_sell.sell_type)
  File "/root/freqtrade/freqtrade/freqtradebot.py", line 832, in execute_sell
    time_in_force=self.strategy.order_time_in_force['sell']
  File "/root/freqtrade/freqtrade/exchange/__init__.py", line 358, in sell
    f'Insufficient funds to create limit sell order on market {pair}.'
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'
2019-03-10 08:43:39,002 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2019-03-10 08:43:39,099 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2019-03-10 08:43:39,099 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...

```

**Comment by iuvbio** [comment]
It would help if you could post your config.

On first look, I'd say you don't have sufficient funds?
> ccxt.base.errors.InsufficientFunds: binance {"code":-2010,"msg":"Account has insufficient balance for requested action."}

**Comment by mishaker** [comment]
it is probably because you are paying fees by the base currency not with BNBs ... so the bot is trying to sell with the exact amount but in reality you have (amount - fees) on your account.

**Comment by xmatthias** [comment]
i don't like this part: 
```
2019-03-10 08:43:38,992 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
File "/root/freqtrade/.env/lib/python3.6/site-packages/ccxt/base/exchange.py", line 493, in fetch
response.raise_for_status()
File "/root/freqtrade/.env/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order
```

it would suggest a problem with ccxt ... 

Also above that output you should have a "trade-id" ... it might be helpful to get the output of `select * from trades where id = <id>` - where <id> is the trade-id it's trying to sell.

**Comment by Prossi79** [comment]
how can I get the get the output of select * from trades where id = <id> - ?

**Comment by iuvbio** [comment]
From your sqlite database file. Have a look [here](https://www.freqtrade.io/en/latest/sql_cheatsheet/) on how to do that. You need to insert the id for the trade that caused the error for `<id>`.

**Comment by Prossi79** [comment]
mmmh sorry, already deleted the database file .,.. and started a new try - this time without stoploss on exchange

**Comment by Prossi79** [comment]
By the way, I use the DB browser for SQLite - next time I would just copy the information out of the respective trade ID and post it?

**Comment by iuvbio** [comment]
Never used it, but I guess you could do that, yes.

I don't think it's related to soploss_on_exchange.. have you checked on Binance if you use BNB to pay fees as @mishaker suggested?

**Comment by Prossi79** [comment]
yes, I am using BNB on Binance to pay the fees ... this cannot be the root cause.

And I got enough to pay the fees : )

**Comment by xmatthias** [comment]
based on the slack conversation, I do think that it was because of a dry-run order still open before switching to the exchange with the same database file ...

**Comment by xmatthias** [comment]
@Prossi79 
Did this happen again after using a new database?
Otherwise I'm tempted to close this ...

**Comment by Prossi79** [comment]
At the moment I am just running the bot without "stoploss on exchange" .... no problems. 

But above prroblem was with "stoploss on exchange", after using a new database it was okay - but I had several times issues with "stoploss on exchange" seems not to run stable

**Comment by iuvbio** [comment]
I doubt that's the problem.. I have the bot running on Binance very stable with stoploss on exchange. With a clean db it should not cause any problems. Anyway, happy you solved it for you :)

**Comment by Prossi79** [comment]
I am happy to hear that stoploss on exchange is running on Binance - I may activate and test it again. This time I watch carefully te DB : )

**Comment by xmatthias** [comment]
Let's close this for now - feel free to reopen if it happens again.
