### ISSUE TITLE
Trigger BTC to enable Buy ?

### ISSUE THREAD

**Issue by mouhamed-o** [freqtrade/freqtrade#1669]
Hi,

I test some trading bot and freqtrade is the best i test but it miss one feature and i think that these feature is important : 
Is it possible to add a trigger on BTC value  because the altcoins depends on BTC value evolution.
When BTC down the altcoin down that can raise a buy signal.
My idea is to add a tigger on BTC before buying to check if all condition is ok.

**Comment by xmatthias** [comment]
I think what you're searching for is [this](https://www.freqtrade.io/en/latest/bot-optimization/#get-data-for-non-tradeable-pairs).

Adding informative pairs (BTC/USDT for example) - and adding this into the buy/sell signals.

**Comment by mouhamed-o** [comment]
Can you give an example to how to use i in my strategy please ?

**Comment by mouhamed-o** [comment]
any example on the doc

**Comment by xmatthias** [comment]
Yes we do now:
https://github.com/freqtrade/freqtrade-strategies/blob/master/user_data/strategies/InformativeSample.py

Hope this helps

**Comment by mouhamed-o** [comment]
I get this error : 
Traceback (most recent call last):
  File "freqtrade/main.py", line 89, in <module>
    main(sys.argv[1:])
  File "freqtrade/main.py", line 35, in main
    args.func(args)
  File "/Users/mouhamedo/git/freqtrade/freqtrade/optimize/backtesting.py", line 490, in start
    backtesting.start()
  File "/Users/mouhamedo/git/freqtrade/freqtrade/optimize/backtesting.py", line 421, in start
    preprocessed = self.strategy.tickerdata_to_dataframe(data)
  File "/Users/mouhamedo/git/freqtrade/freqtrade/strategy/interface.py", line 361, in tickerdata_to_dataframe
    for pair, pair_data in tickerdata.items()}
  File "/Users/mouhamedo/git/freqtrade/freqtrade/strategy/interface.py", line 361, in <dictcomp>
    for pair, pair_data in tickerdata.items()}
  File "/Users/mouhamedo/git/freqtrade/freqtrade/strategy/interface.py", line 374, in advise_indicators
    return self.populate_indicators(dataframe)  # type: ignore
  File "/Users/mouhamedo/git/freqtrade/freqtrade/strategy/ReinforcedSmoothScalp.py", line 87, in populate_indicators
    if self.dp:
AttributeError: 'ReinforcedSmoothScalp' object has no attribute 'dp'

**Comment by xmatthias** [comment]
Yes, unfortunately it does currently not support backtesting.

It's something that is planned, but testing takes a while...
