### ISSUE TITLE
"In stoploss limit order, stop price should be more than limit price"?

### ISSUE THREAD

**Issue by Prossi79** [freqtrade/freqtrade#1702]
Problem again with Stoploss on exchange - worked for a while, but a few minutes ago it crashed again

### Observed Result

freqtrade selected a pair via dynamic pairlist - quoteVolume -> NPXS/BTC

tried to place stoploss on exchange

### Relevant code exceptions or logs:

  ```
Traceback (most recent call last):
  File "/root/freqtrade/freqtrade/freqtradebot.py", line 182, in _process
    state_changed |= self.process_maybe_execute_sell(trade)
  File "/root/freqtrade/freqtrade/freqtradebot.py", line 507, in process_maybe_execute_sell
    result = self.handle_stoploss_on_exchange(trade)
  File "/root/freqtrade/freqtrade/freqtradebot.py", line 636, in handle_stoploss_on_exchange
    pair=trade.pair, amount=trade.amount, stop_price=stop_price, rate=limit_price
  File "/root/freqtrade/freqtrade/exchange/__init__.py", line 386, in stoploss_limit
    'In stoploss limit order, stop price should be more than limit price')
freqtrade.OperationalException: In stoploss limit order, stop price should be more than limit price

  ```

**Comment by xmatthias** [comment]
This is a very low value pair ...
the value of this coin - the stoploss + rounding does not work.  (0.00000015 * 0.90 

we've had this in here too: #1520
The solution is to filter these pairs out.
from the docs [dynamic pairlists](https://www.freqtrade.io/en/latest/configuration/#dynamic-pairlists):

It only applies to dynamic whitelist - however allows you to filter low-value coins that would not allow setting a stop loss (set `precision_filter` parameter to true for this).

it's been introduced recently (#1596) - but to fix exactly the problem you're facing.

**Comment by Prossi79** [comment]
Thanks for your quick reply - I tried your code out of documentation:


    "pairlist": {
        "method": "VolumePairList",
        "config": {
            "number_assets": 30,
            "sort_key": "quoteVolume"
            "precision_filter": true
        }
    }, 


Following error message:

  File "./freqtrade/main.py", line 89, in <module>
    main(sys.argv[1:])
  File "./freqtrade/main.py", line 35, in main
    args.func(args)
  File "/root/freqtrade/freqtrade/optimize/backtesting.py", line 485, in start
    config = setup_configuration(args)
  File "/root/freqtrade/freqtrade/optimize/backtesting.py", line 465, in setup_configuration
    config = configuration.get_config()
  File "/root/freqtrade/freqtrade/configuration.py", line 308, in get_config
    self.config = self.load_config()
  File "/root/freqtrade/freqtrade/configuration.py", line 49, in load_config
    config = self._load_config_file(self.args.config)
  File "/root/freqtrade/freqtrade/configuration.py", line 90, in _load_config_file
    conf = json.load(file)
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 127 column 13 (char 2814)
(.env) root@vmanager6003:~/freqtrade# source .env/bin/activate; python ./freqtrade/main.py -s APstrat1 backtesting 
Traceback (most recent call last):
  File "./freqtrade/main.py", line 89, in <module>
    main(sys.argv[1:])
  File "./freqtrade/main.py", line 35, in main
    args.func(args)
  File "/root/freqtrade/freqtrade/optimize/backtesting.py", line 485, in start
    config = setup_configuration(args)
  File "/root/freqtrade/freqtrade/optimize/backtesting.py", line 465, in setup_configuration
    config = configuration.get_config()
  File "/root/freqtrade/freqtrade/configuration.py", line 308, in get_config
    self.config = self.load_config()
  File "/root/freqtrade/freqtrade/configuration.py", line 49, in load_config
    config = self._load_config_file(self.args.config)
  File "/root/freqtrade/freqtrade/configuration.py", line 90, in _load_config_file
    conf = json.load(file)
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 127 column 13 (char 2814)
(.env) root@vmanager6003:~/freqtrade#

**Comment by Prossi79** [comment]
Okay, precision filter set on true avoids such incidents?

**Comment by xmatthias** [comment]
I'm going to close this since the original question was answered - there is not much we can do other than offer a filter (`precision_filter` for `VolumePairList`).
