### ISSUE TITLE
TypeError: parse_timeframe() missing 1 required positional argument: 'timeframe'

### ISSUE THREAD

**Issue by mishaker** [freqtrade/freqtrade#1748]
```
2019-04-08 16:24:51,083 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "./freqtrade/main.py", line 42, in main
    worker.run()
  File "/ft/freqtrade/freqtrade/worker.py", line 72, in run
    state = self._worker(old_state=state)
  File "/ft/freqtrade/freqtrade/worker.py", line 110, in _worker
    self._throttle(func=self._process, min_secs=throttle_secs)
  File "/ft/freqtrade/freqtrade/worker.py", line 123, in _throttle
    result = func(*args, **kwargs)
  File "/ft/freqtrade/freqtrade/worker.py", line 133, in _process
    state_changed = self.freqtrade.process()
  File "/ft/freqtrade/freqtrade/freqtradebot.py", line 109, in process
    self.edge.calculate()
  File "/ft/freqtrade/freqtrade/edge/__init__.py", line 108, in calculate
    timerange=self._timerange
  File "/ft/freqtrade/freqtrade/data/history.py", line 143, in load_data
    fill_up_missing=fill_up_missing)
  File "/ft/freqtrade/freqtrade/data/history.py", line 117, in load_pair_history
    return parse_ticker_dataframe(pairdata, ticker_interval, fill_up_missing)
  File "/ft/freqtrade/freqtrade/data/converter.py", line 50, in parse_ticker_dataframe
    return ohlcv_fill_up_missing_data(frame, ticker_interval)
  File "/ft/freqtrade/freqtrade/data/converter.py", line 68, in ohlcv_fill_up_missing_data
    ticker_minutes = timeframe_to_minutes(ticker_interval)
  File "/ft/freqtrade/freqtrade/misc.py", line 150, in timeframe_to_minutes
    return Exchange.parse_timeframe(ticker_interval) // 60
TypeError: parse_timeframe() missing 1 required positional argument: 'timeframe'
```

**Comment by hroff-1902** [comment]
what was the command line?

**Comment by mishaker** [comment]
>python freqtrade

:)

**Comment by hroff-1902** [comment]
I mean I see that it fails under the edge module so I decided you called it standealone with edge command, for example. Or something else. That's why I asked... 

Do you have timeframe set in the config or in the strategy?

**Comment by mishaker** [comment]
Binance, yes I set timeframe: ticker_interval = '5m' ccxt 1.18.368

**Comment by hroff-1902** [comment]
Ha,
pip install -r requirments-dev.txt if you are running the current develop version...

@kroitor made this method static in ccxt by my request in 1.18.431...
See for reference https://github.com/ccxt/ccxt/issues/4934

**Comment by mishaker** [comment]
yep ! solved the issue ! thanks

**Comment by Gabri** [comment]
Hello @hroff-1902,

Fresh install (on linux)
installed TA-lib and all requirements as said in the installation guide.
As suggested in this issue I installed dependencies in requirments-dev.txt too.
my config.json = config_binance.json.example
Running:
`freqtrade -c config.json`
I get the same problem as said before:
```
2019-07-16 14:01:29,847 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/mnt/workspace/ws/git/cry/freqtrade/freqtrade/main.py", line 49, in main
    worker.run()
  File "/mnt/workspace/ws/git/cry/freqtrade/freqtrade/worker.py", line 72, in run
    state = self._worker(old_state=state)
  File "/mnt/workspace/ws/git/cry/freqtrade/freqtrade/worker.py", line 110, in _worker
    self._throttle(func=self._process, min_secs=throttle_secs)
  File "/mnt/workspace/ws/git/cry/freqtrade/freqtrade/worker.py", line 123, in _throttle
    result = func(*args, **kwargs)
  File "/mnt/workspace/ws/git/cry/freqtrade/freqtrade/worker.py", line 133, in _process
    state_changed = self.freqtrade.process()
  File "/mnt/workspace/ws/git/cry/freqtrade/freqtrade/freqtradebot.py", line 131, in process
    self.strategy.informative_pairs())
  File "/mnt/workspace/ws/git/cry/freqtrade/freqtrade/data/dataprovider.py", line 35, in refresh
    self._exchange.refresh_latest_ohlcv(pairlist)
  File "/mnt/workspace/ws/git/cry/freqtrade/freqtrade/exchange/exchange.py", line 610, in refresh_latest_ohlcv
    drop_incomplete=self._ohlcv_partial_candle)
  File "/mnt/workspace/ws/git/cry/freqtrade/freqtrade/data/converter.py", line 55, in parse_ticker_dataframe
    return ohlcv_fill_up_missing_data(frame, ticker_interval, pair)
  File "/mnt/workspace/ws/git/cry/freqtrade/freqtrade/data/converter.py", line 75, in ohlcv_fill_up_missing_data
    ticker_minutes = timeframe_to_minutes(ticker_interval)
  File "/mnt/workspace/ws/git/cry/freqtrade/freqtrade/exchange/exchange.py", line 779, in timeframe_to_minutes
    return ccxt.Exchange.parse_timeframe(ticker_interval) // 60
TypeError: parse_timeframe() missing 1 required positional argument: 'timeframe'
2019-07-16 14:01:29,849 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2019-07-16 14:01:29,849 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2019-07-16 14:01:29,849 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
```
Can you help me, please?
Thanks

**Comment by Gabri** [comment]
I open a new issue
