### ISSUE TITLE
Problems with Backtesting since Dev branch update

### ISSUE THREAD

**Issue by Prossi79** [freqtrade/freqtrade#1769]
## Step 1: Have you search for this issue before posting it?

no

## Step 2: Describe your environment

    Python Version: 3.7.1
    CCXT version: 1.18.430
    Branch: Develop

  
## Step 3: Describe the problem:

just updated the dev branch and tried to backtest a strategy, not working anymore ... before the update it worked well

### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
### Observed Results:
(.env) (base) root@vmanager6003:~/freqtrade# git pull origin develop
remote: Enumerating objects: 330, done.
remote: Counting objects: 100% (330/330), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 550 (delta 327), reused 326 (delta 326), pack-reused 220
Receiving objects: 100% (550/550), 167.77 KiB | 2.27 MiB/s, done.
Resolving deltas: 100% (409/409), completed with 95 local objects.
From https://github.com/freqtrade/freqtrade
 * branch              develop    -> FETCH_HEAD
   b437c3cf..5f63797f  develop    -> origin/develop
Updating b437c3cf..5f63797f
Fast-forward
 .pyup.yml                                    |   1 +
 Dockerfile                                   |   2 +-
 Dockerfile.pi                                |  40 ++++
 docs/configuration.md                        |   6 +-
 docs/faq.md                                  |  26 ++-
 docs/hyperopt.md                             |   4 +-
 docs/installation.md                         |   3 +-
 docs/sql_cheatsheet.md                       |   8 +-
 docs/telegram-usage.md                       |   4 +-
 docs/webhook-config.md                       |  40 ++--
 freqtrade/__init__.py                        |   8 +
 freqtrade/arguments.py                       |  16 ++
 freqtrade/configuration.py                   |  14 +-
 freqtrade/constants.py                       |  25 +--
 freqtrade/data/converter.py                  |   6 +-
 freqtrade/data/dataprovider.py               |  12 +-
 freqtrade/data/history.py                    |  26 +--
 freqtrade/exchange/exchange.py               |  48 ++---
 freqtrade/freqtradebot.py                    | 278 ++++++++++-----------------
 freqtrade/main.py                            |  52 +----
 freqtrade/misc.py                            |  24 +++
 freqtrade/optimize/backtesting.py            |  92 +++++----
 freqtrade/rpc/rpc.py                         |  11 +-
 freqtrade/rpc/telegram.py                    |  27 ++-
 freqtrade/strategy/interface.py              |   4 +-
 freqtrade/tests/conftest.py                  |  11 +-
 freqtrade/tests/data/test_dataprovider.py    |  40 ++--
 freqtrade/tests/data/test_history.py         |  14 +-
 freqtrade/tests/edge/test_edge.py            |   4 +-
 freqtrade/tests/exchange/test_exchange.py    |  17 +-
 freqtrade/tests/optimize/__init__.py         |   8 +-
 freqtrade/tests/optimize/test_backtesting.py |  19 +-
 freqtrade/tests/optimize/test_optimize.py    |   7 +-
 freqtrade/tests/rpc/test_rpc.py              |  14 +-
 freqtrade/tests/rpc/test_rpc_telegram.py     |  45 ++++-
 freqtrade/tests/test_freqtradebot.py         | 132 +++++++++----
 freqtrade/tests/test_main.py                 |  64 +++---
 freqtrade/worker.py                          | 188 ++++++++++++++++++
 mkdocs.yml                                   |   9 +-
 requirements-dev.txt                         |   2 +-
 requirements-pi.txt                          |  23 +++
 requirements.txt                             |   2 +-
 scripts/download_backtest_data.py            |  42 ++--
 scripts/get_market_pairs.py                  |  12 ++
 scripts/plot_dataframe.py                    |  16 +-
 scripts/plot_profit.py                       |  22 +--
 46 files changed, 907 insertions(+), 561 deletions(-)
 create mode 100644 Dockerfile.pi
 create mode 100755 freqtrade/worker.py
 create mode 100644 requirements-pi.txt

### Relevant code exceptions or logs:
Traceback (most recent call last):
  File "./freqtrade/main.py", line 60, in <module>
    main(sys.argv[1:])
  File "./freqtrade/main.py", line 34, in main
    args.func(args)
  File "/root/freqtrade/freqtrade/optimize/backtesting.py", line 520, in start
    backtesting = Backtesting(config)
  File "/root/freqtrade/freqtrade/optimize/backtesting.py", line 90, in __init__
    self._set_strategy(self.strategylist[0])
  File "/root/freqtrade/freqtrade/optimize/backtesting.py", line 99, in _set_strategy
    self.ticker_interval_mins = timeframe_to_minutes(self.ticker_interval)
  File "/root/freqtrade/freqtrade/misc.py", line 150, in timeframe_to_minutes
    return Exchange.parse_timeframe(ticker_interval) // 60
TypeError: parse_timeframe() missing 1 required positional argument: 'timeframe'

**Comment by hroff-1902** [comment]
```
pip3 install -r requirements.txt
```

**Comment by Prossi79** [comment]
Okay, now it is working but I have totally different backtesting results then yesterday :(

Example -> Simple strategy out of the repo:
yesterday before devlop branch update -> around 220 trades and 70% tot profit, 1 day 22h duration  
today after update -> around 65 trades and 12,45% tot profit, 4days 12h duration

(all based on 98 days)

thats a big difference ...
what happened? did you change the backtesting algo?

**Comment by xmatthias** [comment]
What was your previous version / commit ID? 

There were some changes done to fix problems with missing data (at the beginning - and if we go back further also in the middle, since it's now filling up data automatically).

**Comment by Prossi79** [comment]
How can I find out the previous version which I had installed?

**Comment by xmatthias** [comment]
Stupid me - it's in your initial output 
```
branch develop -> FETCH_HEAD
b437c3c..5f63797 develop -> origin/develop
```

at least this one went in: https://github.com/freqtrade/freqtrade/pull/1683

Does your output during backtesting show you something about missing data

**Comment by Prossi79** [comment]
yes it does, in fact for all pairs which I have white listed .. 

2019-04-16 16:32:28,550 - freqtrade.optimize.backtesting - INFO - Running backtesting for Strategy APstrat1
2019-04-16 16:32:28,590 - freqtrade.optimize - WARNING - BCH/BTC has missing frames: expected 29007, got 25130, that's 3877 missing values
2019-04-16 16:32:28,590 - freqtrade.optimize - WARNING - BSV/BTC has missing frames: expected 29007, got 26451, that's 2556 missing values
2019-04-16 16:32:28,591 - freqtrade.optimize - WARNING - IOTA/BTC has missing frames: expected 29007, got 26452, that's 2555 missing values
2019-04-16 16:32:28,591 - freqtrade.optimize - WARNING - NEO/BTC has missing frames: expected 29007, got 26467, that's 2540 missing values
2019-04-16 16:32:28,591 - freqtrade.optimize - WARNING - ONT/BTC has missing frames: expected 29007, got 26451, that's 2556 missing values
2019-04-16 16:32:28,591 - freqtrade.optimize - WARNING - XEM/BTC has missing frames: expected 29007, got 26451, that's 2556 missing values
2019-04-16 16:32:28,591 - freqtrade.optimize - WARNING - VET/BTC has missing frames: expected 29007, got 25684, that's 3323 missing values
2019-04-16 16:32:28,592 - freqtrade.optimize - WARNING - BAT/BTC has missing frames: expected 29007, got 24825, that's 4182 missing values
2019-04-16 16:32:28,592 - freqtrade.optimize - WARNING - OMG/BTC has missing frames: expected 29007, got 26451, that's 2556 missing values
2019-04-16 16:32:28,592 - freqtrade.optimize - WARNING - BTG/BTC has missing frames: expected 29007, got 24825, that's 4182 missing values
2019-04-16 16:32:28,592 - freqtrade.optimize - WARNING - QTUM/BTC has missing frames: expected 29007, got 25399, that's 3608 missing values
2019-04-16 16:32:28,601 - freqtrade.optimize - WARNING - WAVES/BTC has missing frames: expected 29007, got 25686, that's 3321 missing values
2019-04-16 16:32:28,602 - freqtrade.optimize - WARNING - REP/BTC has missing frames: expected 29007, got 24249, that's 4758 missing values
2019-04-16 16:32:28,602 - freqtrade.optimize - WARNING - DCR/BTC has missing frames: expected 29007, got 26451, that's 2556 missing values
2019-04-16 16:32:28,602 - freqtrade.optimize - WARNING - LSK/BTC has missing frames: expected 29007, got 10985, that's 18022 missing values
2019-04-16 16:32:28,602 - freqtrade.optimize - WARNING - RVN/BTC has missing frames: expected 29007, got 17828, that's 11179 missing values
2019-04-16 16:32:28,602 - freqtrade.optimize - WARNING - NANO/BTC has missing frames: expected 29007, got 26451, that's 2556 missing values
2019-04-16 16:32:28,602 - freqtrade.optimize - WARNING - ZIL/BTC has missing frames: expected 29007, got 24249, that's 4758 missing values
2019-04-16 16:32:28,602 - freqtrade.optimize - WARNING - ZRX/BTC has missing frames: expected 29007, got 17828, that's 11179 missing values
2019-04-16 16:32:28,603 - freqtrade.optimize.backtesting - INFO - Measuring data from 2019-01-05T21:05:00+00:00 up to 2019-04-16T14:20:00+00:00 (100 days)..

**Comment by xmatthias** [comment]
the frames you are missing are "in the middle" of the data.
we are filling these up to avoid unexpected results (standard is to use a _ bar - with open,high,low and close at the same level (close of previous candle) and volume 0.
That's newish - but should have been in the code before the pointed out starting commit.

You have quite some missing data, so you may want to delete it all and redownload for the timeperiod in question. However, the messages also happen if the exchange had a downtime during that period, in which case they shuld all have ~ the same.

#1683 will influence backtest results if missing data is present.
but while the results may be worse, they are now better aligned to reality, since we fixed a bug related to missing data.

**Comment by Prossi79** [comment]
Hi Matthias! thanks for the explanation, just tried to re-download the test data as described in the documentation:

Downloading new set of ticker data¶

To download new set of backtesting ticker data, you can use a download script.

If you are using Binance for example:

    create a folder user_data/data/binance and copy pairs.json in that folder.
    update the pairs.json to contain the currency pairs you are interested in.

mkdir -p user_data/data/binance
cp freqtrade/tests/testdata/pairs.json user_data/data/binance

Then run:

python scripts/download_backtest_data.py --exchange binance


**.... but still having a lot of missing data. I did not delete them before, that should help?**

2019-04-17 07:17:06,256 - freqtrade.optimize - WARNING - BCH/BTC has missing frames: expected 29184, got 25130, that's 4054 missing values
2019-04-17 07:17:06,266 - freqtrade.optimize - WARNING - EOS/BTC has missing frames: expected 29184, got 29008, that's 176 missing values
2019-04-17 07:17:06,297 - freqtrade.optimize - WARNING - BNB/BTC has missing frames: expected 29184, got 29008, that's 176 missing values
2019-04-17 07:17:06,298 - freqtrade.optimize - WARNING - TRX/BTC has missing frames: expected 29184, got 29008, that's 176 missing values
2019-04-17 07:17:06,325 - freqtrade.optimize - WARNING - BSV/BTC has missing frames: expected 29184, got 26451, that's 2733 missing values
2019-04-17 07:17:06,369 - freqtrade.optimize - WARNING - IOTA/BTC has missing frames: expected 29184, got 26452, that's 2732 missing values
2019-04-17 07:17:06,379 - freqtrade.optimize - WARNING - NEO/BTC has missing frames: expected 29184, got 26644, that's 2540 missing values
2019-04-17 07:17:06,393 - freqtrade.optimize - WARNING - ONT/BTC has missing frames: expected 29184, got 26451, that's 2733 missing values
2019-04-17 07:17:06,393 - freqtrade.optimize - WARNING - XEM/BTC has missing frames: expected 29184, got 26451, that's 2733 missing values
2019-04-17 07:17:06,393 - freqtrade.optimize - WARNING - VET/BTC has missing frames: expected 29184, got 25684, that's 3500 missing values
2019-04-17 07:17:06,417 - freqtrade.optimize - WARNING - BAT/BTC has missing frames: expected 29184, got 25001, that's 4183 missing values
2019-04-17 07:17:06,429 - freqtrade.optimize - WARNING - OMG/BTC has missing frames: expected 29184, got 26451, that's 2733 missing values
2019-04-17 07:17:06,437 - freqtrade.optimize - WARNING - BTG/BTC has missing frames: expected 29184, got 24825, that's 4359 missing values
2019-04-17 07:17:06,447 - freqtrade.optimize - WARNING - QTUM/BTC has missing frames: expected 29184, got 25576, that's 3608 missing values
2019-04-17 07:17:06,447 - freqtrade.optimize - WARNING - WAVES/BTC has missing frames: expected 29184, got 25863, that's 3321 missing values
2019-04-17 07:17:06,449 - freqtrade.optimize - WARNING - REP/BTC has missing frames: expected 29184, got 24249, that's 4935 missing values
2019-04-17 07:17:06,450 - freqtrade.optimize - WARNING - DCR/BTC has missing frames: expected 29184, got 26451, that's 2733 missing values
2019-04-17 07:17:06,450 - freqtrade.optimize - WARNING - LSK/BTC has missing frames: expected 29184, got 11161, that's 18023 missing values
2019-04-17 07:17:06,450 - freqtrade.optimize - WARNING - RVN/BTC has missing frames: expected 29184, got 17828, that's 11356 missing values
2019-04-17 07:17:06,450 - freqtrade.optimize - WARNING - NANO/BTC has missing frames: expected 29184, got 26451, that's 2733 missing values
2019-04-17 07:17:06,450 - freqtrade.optimize - WARNING - ZIL/BTC has missing frames: expected 29184, got 24249, that's 4935 missing values
2019-04-17 07:17:06,451 - freqtrade.optimize - WARNING - ZRX/BTC has missing frames: expected 29184, got 17828, that's 11356 missing values

**Comment by xmatthias** [comment]
`python scripts/download_backtest_data.py --exchange binance`

you'll want to add a `--days 100` (or however many days you'd like to backtest to make sure.
`--erase` deletes the data before - so i guess that could help to make sure it's really redownloading the whole dataset.

to sum up:

`python scripts/download_backtest_data.py --exchange binance --erase --days 100 -t 5m`

As mentioned before - it CAN be explained by downtime of the exchange - but then it should be the same amount of missing frames for each period.

**Comment by Prossi79** [comment]
Okay, perfect - no more missing data frames now : )  ... but still big deviations compared with previous backtests. But okay, if the latest update reflects the reality then it is way it should work and not inflating results

**Comment by xmatthias** [comment]
unfortunately, with each bug we find in backtesting, the performance tends to mostly decrease if the bug impacted previous results.
However we strive for a "close to reality" backtest - so better this way than being surprised once running in dry/live mode
