### ISSUE TITLE
No module named Freqtrade

### ISSUE THREAD

**Issue by gitgitgat** [freqtrade/freqtrade#1809]
It stopped working, I have deleted and cloned the repo again and suddenly get this error:

```
File "/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "freqtrade/__main__.py", line 11, in <module>
    from freqtrade import main
ModuleNotFoundError: No module named 'freqtrade'
```

**Comment by gitgitgat** [comment]
after python3 freqtrade -c config.json hyperopt --customhyperopt SampleHyperOpts -e 5000 --spaces all --print-all

**Comment by hroff-1902** [comment]
```
export PYTHONPATH=.:$PYTHONPATH; python3 freqtrade <rest of options>
```

**Comment by xmatthias** [comment]
When you say you deleted your repository, you probably deleted the virtual environment too (?)

**Comment by gitgitgat** [comment]
hmm, the venv is still there, deleted the repo from the venv

**Comment by gitgitgat** [comment]
ok

**Comment by gitgitgat** [comment]
this happens now after export = ....

```
2019-04-28 12:33:53,830 - freqtrade.optimize.hyperopt - INFO - Found 4 CPU cores. Let's make them scream!
2019-04-28 12:33:53,830 - freqtrade.optimize.hyperopt - INFO - Number of parallel jobs set as: -1
2019-04-28 12:33:53,852 - freqtrade.optimize.hyperopt - INFO - Effective number of parallel workers used: 4
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/nielsschmidtmartinez/.env/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 418, in _process_worker
    r = call_item()
  File "/Users/nielsschmidtmartinez/.env/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 272, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/Users/nielsschmidtmartinez/.env/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 567, in __call__
    return self.func(*args, **kwargs)
  File "/Users/nielsschmidtmartinez/.env/lib/python3.7/site-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/Users/nielsschmidtmartinez/.env/lib/python3.7/site-packages/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "/Users/nielsschmidtmartinez/.env/lib/python3.7/site-packages/joblib/externals/loky/cloudpickle_wrapper.py", line 38, in __call__
    return self._obj(*args, **kwargs)
  File "/Users/nielsschmidtmartinez/Downloads/Things to Put in HDD/GITHUB/FREQTRADE/freqtrade/freqtrade/optimize/hyperopt.py", line 186, in generate_optimizer
    min_date, max_date = get_timeframe(processed)
  File "/Users/nielsschmidtmartinez/Downloads/Things to Put in HDD/GITHUB/FREQTRADE/freqtrade/freqtrade/optimize/__init__.py", line 26, in get_timeframe
    return min(timeframe, key=operator.itemgetter(0))[0], \
ValueError: min() arg is an empty sequence
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "freqtrade/__main__.py", line 15, in <module>
    main.main(sys.argv[1:])
  File "/Users/nielsschmidtmartinez/Downloads/Things to Put in HDD/GITHUB/FREQTRADE/freqtrade/freqtrade/main.py", line 34, in main
    args.func(args)
  File "/Users/nielsschmidtmartinez/Downloads/Things to Put in HDD/GITHUB/FREQTRADE/freqtrade/freqtrade/optimize/hyperopt.py", line 351, in start
    hyperopt.start()
  File "/Users/nielsschmidtmartinez/Downloads/Things to Put in HDD/GITHUB/FREQTRADE/freqtrade/freqtrade/optimize/hyperopt.py", line 290, in start
    f_val = self.run_optimizer_parallel(parallel, asked)
  File "/Users/nielsschmidtmartinez/Downloads/Things to Put in HDD/GITHUB/FREQTRADE/freqtrade/freqtrade/optimize/hyperopt.py", line 244, in run_optimizer_parallel
    wrap_non_picklable_objects(self.generate_optimizer))(v) for v in asked)
  File "/Users/nielsschmidtmartinez/.env/lib/python3.7/site-packages/joblib/parallel.py", line 934, in __call__
    self.retrieve()
  File "/Users/nielsschmidtmartinez/.env/lib/python3.7/site-packages/joblib/parallel.py", line 833, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/Users/nielsschmidtmartinez/.env/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 521, in wrap_future_result
    return future.result(timeout=timeout)
  File "/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
ValueError: min() arg is an empty sequence

```

**Comment by gitgitgat** [comment]
Now this happens after export path:

```
2019-04-28 12:33:53,830 - freqtrade.optimize.hyperopt - INFO - Found 4 CPU cores. Let's make them scream!
2019-04-28 12:33:53,830 - freqtrade.optimize.hyperopt - INFO - Number of parallel jobs set as: -1
2019-04-28 12:33:53,852 - freqtrade.optimize.hyperopt - INFO - Effective number of parallel workers used: 4
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/nielsschmidtmartinez/.env/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 418, in _process_worker
    r = call_item()
  File "/Users/nielsschmidtmartinez/.env/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 272, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/Users/nielsschmidtmartinez/.env/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 567, in __call__
    return self.func(*args, **kwargs)
  File "/Users/nielsschmidtmartinez/.env/lib/python3.7/site-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/Users/nielsschmidtmartinez/.env/lib/python3.7/site-packages/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "/Users/nielsschmidtmartinez/.env/lib/python3.7/site-packages/joblib/externals/loky/cloudpickle_wrapper.py", line 38, in __call__
    return self._obj(*args, **kwargs)
  File "/Users/nielsschmidtmartinez/Downloads/Things to Put in HDD/GITHUB/FREQTRADE/freqtrade/freqtrade/optimize/hyperopt.py", line 186, in generate_optimizer
    min_date, max_date = get_timeframe(processed)
  File "/Users/nielsschmidtmartinez/Downloads/Things to Put in HDD/GITHUB/FREQTRADE/freqtrade/freqtrade/optimize/__init__.py", line 26, in get_timeframe
    return min(timeframe, key=operator.itemgetter(0))[0], \
ValueError: min() arg is an empty sequence
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "freqtrade/__main__.py", line 15, in <module>
    main.main(sys.argv[1:])
  File "/Users/nielsschmidtmartinez/Downloads/Things to Put in HDD/GITHUB/FREQTRADE/freqtrade/freqtrade/main.py", line 34, in main
    args.func(args)
  File "/Users/nielsschmidtmartinez/Downloads/Things to Put in HDD/GITHUB/FREQTRADE/freqtrade/freqtrade/optimize/hyperopt.py", line 351, in start
    hyperopt.start()
  File "/Users/nielsschmidtmartinez/Downloads/Things to Put in HDD/GITHUB/FREQTRADE/freqtrade/freqtrade/optimize/hyperopt.py", line 290, in start
    f_val = self.run_optimizer_parallel(parallel, asked)
  File "/Users/nielsschmidtmartinez/Downloads/Things to Put in HDD/GITHUB/FREQTRADE/freqtrade/freqtrade/optimize/hyperopt.py", line 244, in run_optimizer_parallel
    wrap_non_picklable_objects(self.generate_optimizer))(v) for v in asked)
  File "/Users/nielsschmidtmartinez/.env/lib/python3.7/site-packages/joblib/parallel.py", line 934, in __call__
    self.retrieve()
  File "/Users/nielsschmidtmartinez/.env/lib/python3.7/site-packages/joblib/parallel.py", line 833, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/Users/nielsschmidtmartinez/.env/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 521, in wrap_future_result
    return future.result(timeout=timeout)
  File "/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
ValueError: min() arg is an empty sequence

```

**Comment by gitgitgat** [comment]
might have to reset everything in my system and come back to it

**Comment by xmatthias** [comment]
you have the virtual environment active? maybe install freqtrade again using `pip3 install -e .`.
if the path is now slightly different you may have broken links

**Comment by xmatthias** [comment]
going to close this as i think this was solved in the meantime.

Feel free to reopen if you still have this problem.
