### ISSUE TITLE
Hyperopts

### ISSUE THREAD

**Issue by gitgitgat** [freqtrade/freqtrade#1853]
An error warning comes up when trying 

python3 freqtrade -c config.json hyperopt --customhyperopt HyperOpts  -e 5000 --print-all

```
/Users/nsm/.env/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "freqtrade/__main__.py", line 15, in <module>
    main.main(sys.argv[1:])
  File "/Users/nsm/freqtrade/freqtrade/main.py", line 34, in main
    args.func(args)
  File "/Users/nsm/freqtrade/freqtrade/optimize/hyperopt.py", line 362, in start
    config = setup_configuration(args)
  File "/Users/nsm/freqtrade/freqtrade/optimize/hyperopt.py", line 338, in setup_configuration
    config = configuration.load_config()
  File "/Users/nsm/freqtrade/freqtrade/configuration.py", line 78, in load_config
    config = deep_merge_dicts(self._load_config_file(path), config)
  File "/Users/nsm/freqtrade/freqtrade/configuration.py", line 117, in _load_config_file
    conf = json.load(file)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 175 column 13 (char 4125)

```

**Comment by hroff-1902** [comment]
add a comma in your config

**Comment by gitgitgat** [comment]
duh, ok, I had been there before. thanks

**Comment by gitgitgat** [comment]
but now this comes up: 

```
/Users/nsm/.env/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
/Users/nsm/.env/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
/Users/nsm/.env/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
/Users/nsm/.env/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/nsm/.env/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 418, in _process_worker
    r = call_item()
  File "/Users/nsm/.env/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 272, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/Users/nsm/.env/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 567, in __call__
    return self.func(*args, **kwargs)
  File "/Users/nsm/.env/lib/python3.7/site-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/Users/nsm/.env/lib/python3.7/site-packages/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "/Users/nsm/.env/lib/python3.7/site-packages/joblib/externals/loky/cloudpickle_wrapper.py", line 38, in __call__
    return self._obj(*args, **kwargs)
  File "/Users/nsm/freqtrade/freqtrade/optimize/hyperopt.py", line 200, in generate_optimizer
    min_date, max_date = get_timeframe(processed)
  File "/Users/nsm/freqtrade/freqtrade/optimize/__init__.py", line 26, in get_timeframe
    return min(timeframe, key=operator.itemgetter(0))[0], \
ValueError: min() arg is an empty sequence
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "freqtrade/__main__.py", line 15, in <module>
    main.main(sys.argv[1:])
  File "/Users/nsm/freqtrade/freqtrade/main.py", line 34, in main
    args.func(args)
  File "/Users/nsm/freqtrade/freqtrade/optimize/hyperopt.py", line 377, in start
    hyperopt.start()
  File "/Users/nsm/freqtrade/freqtrade/optimize/hyperopt.py", line 308, in start
    f_val = self.run_optimizer_parallel(parallel, asked)
  File "/Users/nsm/freqtrade/freqtrade/optimize/hyperopt.py", line 262, in run_optimizer_parallel
    wrap_non_picklable_objects(self.generate_optimizer))(v) for v in asked)
  File "/Users/nsm/.env/lib/python3.7/site-packages/joblib/parallel.py", line 934, in __call__
    self.retrieve()
  File "/Users/nsm/.env/lib/python3.7/site-packages/joblib/parallel.py", line 833, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/Users/nsm/.env/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 521, in wrap_future_result
    return future.result(timeout=timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
ValueError: min() arg is an empty sequence
```

**Comment by hroff-1902** [comment]
try to remove the hyperopt pickle file:
```
rm user_data/hyperopt_results.pickle
```

**Comment by gitgitgat** [comment]
okay, just tried that, no luck.

**Comment by hroff-1902** [comment]
Pleasen fill the form:

## Step 2: Describe your environment

  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Branch: Master | Develop
  * Last Commit ID: _____ (`git log --format="%H" -n 1`)

**Comment by gitgitgat** [comment]
python version: Python 3.7.3
CCXT version:  ccxt==1.18.523
Branch: Develop
Last Commit ID: 6d17cd50fed760583a21754057eacf69a7ef78b9

**Comment by gitgitgat** [comment]
ID: 6d17cd50fed760583a21754057eacf69a7ef78b9

**Comment by xmatthias** [comment]
I would suspect it's related to the `HyperOpts` file ... 

did you define at least one space per optimization (a `sell_indicator_space` - `indicator_space`, `roi_space` and `stoploss_space`?
otherwise you need to limit the optimization to one or multiple of the spaces by using `--spaces buy roi` ...

**Comment by hroff-1902** [comment]
> I would suspect it's related to the `HyperOpts` file ...

I would also say this... 

It can be detected: @gitgitgat, does the problem appear when running with DefaultHyperOpts (i.e. without --customhyperopt HyperOpts)?

Also, try to cleanup hyperopt data a bit more: 
```
rm user_data/hyperopt_results.pickle user_data/hyperopt_tickerdata.pkl user_data/data/your_exchange/*
```

**Comment by gitgitgat** [comment]
> in virtual vent



> I would suspect it's related to the `HyperOpts` file ...
> 
> did you define at least one space per optimization (a `sell_indicator_space` - `indicator_space`, `roi_space` and `stoploss_space`?
> otherwise you need to limit the optimization to one or multiple of the spaces by using `--spaces buy roi` ...

I am using spaces-all and it also happens with default hyper opts without --custom...
the hyperopt has been cleaned up as shown above, when trying to run `scripts/download_backtest_data.py`  with  `python3 scripts/download_backtest_data.py` all I get is config.json not found

**Comment by gitgitgat** [comment]
> > I would suspect it's related to the `HyperOpts` file ...
> > did you define at least one space per optimization (a `sell_indicator_space` - `indicator_space`, `roi_space` and `stoploss_space`?
> > otherwise you need to limit the optimization to one or multiple of the spaces by using `--spaces buy roi` ...
> 
> I am using spaces-all and it also happens with default hyper opts without --custom...
> the hyperopt has been cleaned up as shown above, when trying to run `scripts/download_backtest_data.py` with `python3 scripts/download_backtest_data.py` all I get is config.json not found

--spaces buy roi also returns error

**Comment by gitgitgat** [comment]
is `hyperopt.lock` meant to appear?

**Comment by hroff-1902** [comment]
> ... it also happens with default hyper opts without --custom...

Hmm...

@xmatthias, this morning I've already seen this error:
```
ValueError: min() arg is an empty sequence
```
but it was in tests while I was working on #1852, till I mocked get_timeframe() (the timerange passed in the tests was None...)
The question is how can it appear in a running main freqtrade... Hmm...

**Comment by hroff-1902** [comment]
Btw, changes made in #1852 will help to isolate the problem, since we'll see at least in the log what dataframe is used for hyperopt backtesting...

**Comment by gitgitgat** [comment]
I tried running it on Ubuntu and it is the exact same error with the default hyperotps
python 3.6.8
ccxt 1.18.523
branch master 
same id 6d17cd5....

**Comment by hroff-1902** [comment]
> branch master
> same id [6d17cd5]

Ermmm, this commit is in the develop branch...

**Comment by gitgitgat** [comment]
on osx I'm in develop branch. Issues started happening about two weeks ago and prior to that there wasn't a problem (when being in master branch, and in develop I could --print-all so hyper opts worked then) .

**Comment by hroff-1902** [comment]
On OSX? o_0
Does the issue appear on both OSX and Ubuntu or only on Ubuntu?

**Comment by gitgitgat** [comment]
both

**Comment by xmatthias** [comment]
try running the following:

``` bash
python3 freqtrade --config config.json.example --datadir freqtrade/tests/testdata hyperopt -e 5
```

basically, it's to confirm the installation - it's the command that is run during our tests - with static, predefined data and configuration.

if that works, then we can look at 
* Data
* config
* hyperopt file

if this does not work - we'll see

**Comment by gitgitgat** [comment]
great, that is working now, although the following warning remains:

`2019-05-14 23:44:21,582 - freqtrade.optimize.hyperopt - INFO - Loaded 8 previous evaluations from disk.
2019-05-14 23:44:21,582 - freqtrade.optimize.hyperopt - INFO - Found 4 CPU cores. Let's make them scream!
2019-05-14 23:44:21,582 - freqtrade.optimize.hyperopt - INFO - Number of parallel jobs set as: -1
2019-05-14 23:44:21,609 - freqtrade.optimize.hyperopt - INFO - Effective number of parallel workers used: 4
/Users/user/freqtrade/.env/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
/Users/nsm/freqtrade/.env/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
/Users/nsm/freqtrade/.env/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
/Users/nsm/freqtrade/.env/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
`
thanks!

**Comment by xmatthias** [comment]
the Deprecationwarnings come from dependencies - nothing we can do for that, really ...

for the following:
`Loaded 8 previous evaluations from disk`

use `rm user_data/hyperopt_results.pickle user_data/hyperopt_tickerdata.pkl` to get rid of this message (it means that it's continuing a hyperopt - which is not desired if changes did happen.

**Comment by gitgitgat** [comment]
Cool

**Comment by hroff-1902** [comment]
> the Deprecationwarnings come from dependencies - nothing we can do for that, really ...
No, we can! 😃 (#1854 )

**Comment by gitgitgat** [comment]
ok, the only problem now is that the error shows up again when the ticker time is changed, (from 5m to 15m)

**Comment by gitgitgat** [comment]
when that is changed in the config file

**Comment by hroff-1902** [comment]
Do you use Telegram /reload_conf or simply stop and start again the bot when you change the timeframe in the config?

**Comment by gitgitgat** [comment]
I am not usig telegram now, just testing hyper opts

**Comment by gitgitgat** [comment]
it has problems receiving data for those files as it cannot be found in the testdata folder

**Comment by gitgitgat** [comment]
also sometimes there is an output with less trades with higher avg profit, although best results return more trades with less avg profit

**Comment by xmatthias** [comment]
if you change interval, you'll need to download data for this interval. 
test-data is only available for certain period/pair combinations.

More importantly, please don't base your results on the data in `freqtrade/tests/testdata` - it's data from early 2018 - when things in crypto where ...different.

you should be able to `download_backtest_data.py --config yourconfig.json --days 30 -t 5m 15m 30m ` to get data for the last 30 days for 3 periods ... (adapt to your needs please).

**Comment by gitgitgat** [comment]
ah ok

**Comment by gitgitgat** [comment]
config file is in the upper Freqtrade folder

**Comment by hroff-1902** [comment]
Go to that upper directory, run
```
./scripts/download_backtest_data.py --config config.json.example --days 30 -t 5m 15m 30m
```

**Comment by gitgitgat** [comment]
```
Using config: config.json...
No pairs file found with path user_data/data/binance/pairs.json.
```

**Comment by hroff-1902** [comment]
Please read the docs:
https://www.freqtrade.io/en/latest/backtesting/#downloading-new-set-of-ticker-data

**Comment by gitgitgat** [comment]
okay, that works. Thanks a lot!

**Comment by gitgitgat** [comment]
okay almost. It now stalls after the sklearn warning

**Comment by gitgitgat** [comment]
is it normal to get very different results from hyper opts and backtesting?

**Comment by gitgitgat** [comment]
Now I ran into a similar problem with backtesting, a couple of hours ago I was running the command in your file:

python3 freqtrade backtesting, and it worked up to about 1-1/2 hour ago.
now I get this error, I am trying the default strategy:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "freqtrade/__main__.py", line 15, in <module>
    main.main(sys.argv[1:])
  File "/Users/user/freqtrade/freqtrade/main.py", line 34, in main
    args.func(args)
  File "/Users/user/freqtrade/freqtrade/optimize/backtesting.py", line 524, in start
    backtesting.start()
  File "/Users/user/freqtrade/freqtrade/optimize/backtesting.py", line 454, in start
    preprocessed = self.strategy.tickerdata_to_dataframe(data)
  File "/Users/user/freqtrade/freqtrade/strategy/interface.py", line 370, in tickerdata_to_dataframe
    for pair, pair_data in tickerdata.items()}
  File "/Users/nsm/freqtrade/freqtrade/strategy/interface.py", line 370, in <dictcomp>
    for pair, pair_data in tickerdata.items()}
  File "/Users/user/freqtrade/freqtrade/strategy/interface.py", line 385, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/Users/user/freqtrade/freqtrade/strategy/default_strategy.py", line 77, in populate_indicators
    dataframe['ao'] = qtpylib.awesome_oscillator(dataframe)
  File "/Users/user/freqtrade/freqtrade/vendor/qtpylib/indicators.py", line 160, in awesome_oscillator
    numpy_rolling_mean(midprice, slow)
  File "/Users/user/freqtrade/freqtrade/vendor/qtpylib/indicators.py", line 52, in func_wrapper
    calculated = func(series, window)
  File "/Users/user/freqtrade/freqtrade/vendor/qtpylib/indicators.py", line 65, in numpy_rolling_mean
    return np.mean(numpy_rolling_window(data, window), axis=-1)
  File "/Users/user/freqtrade/freqtrade/vendor/qtpylib/indicators.py", line 44, in numpy_rolling_window
    return np.lib.stride_tricks.as_strided(data, shape=shape, strides=strides)
  File "/Users/user/freqtrade/.env/lib/python3.7/site-packages/numpy/lib/stride_tricks.py", line 103, in as_strided
    array = np.asarray(DummyArray(interface, base=x))
  File "/Users/user/freqtrade/.env/lib/python3.7/site-packages/numpy/core/numeric.py", line 538, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: negative dimensions are not allowed
```

**Comment by gitgitgat** [comment]
I also just copied the strategy file from git source code and the same error comes up

**Comment by gitgitgat** [comment]
That is now working again, although backtesting seems to do about 1/9, 1/10 of the number of trades than hyperopts. Is it normal/supposed to be like that?

**Comment by gitgitgat** [comment]
`download_backtest_data.py` ?? does not read my config.json

**Comment by xmatthias** [comment]
Yes it is normal [see docs](https://www.freqtrade.io/en/latest/hyperopt/#validate-backtest-result)

it does read the config.json  (if given via `--config config.json` parameter) - however you currently need a seperate pair-list file.

**Comment by gitgitgat** [comment]
Hyperopts is having some issues running:

```
File "/Users/nsm/freqtrade/.env/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 418, in _process_worker
    r = call_item()
  File "/Users/nsm/freqtrade/.env/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 272, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/Users/nsm/freqtrade/.env/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 567, in __call__
    return self.func(*args, **kwargs)
  File "/Users/nsm/freqtrade/.env/lib/python3.7/site-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/Users/nsm/freqtrade/.env/lib/python3.7/site-packages/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "/Users/nsm/freqtrade/.env/lib/python3.7/site-packages/joblib/externals/loky/cloudpickle_wrapper.py", line 38, in __call__
    return self._obj(*args, **kwargs)
  File "/Users/nsm/freqtrade/freqtrade/optimize/hyperopt.py", line 208, in generate_optimizer
    'end_date': max_date,
  File "/Users/nsm/freqtrade/freqtrade/optimize/backtesting.py", line 344, in backtest
    ticker: Dict = self._get_ticker_list(processed)
  File "/Users/nsm/freqtrade/freqtrade/optimize/backtesting.py", line 228, in _get_ticker_list
    self.advise_buy(pair_data, {'pair': pair}), {'pair': pair})[headers].copy()
  File "/Users/nsm/freqtrade/user_data/hyperopts/test_hyperopt.py", line 247, in populate_sell_trend
    'sell'] = 1
TypeError: reduce() of empty sequence with no initial value
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "freqtrade/__main__.py", line 15, in <module>
    main.main(sys.argv[1:])
  File "/Users/nsm/freqtrade/freqtrade/main.py", line 34, in main
    args.func(args)
  File "/Users/nsm/freqtrade/freqtrade/optimize/hyperopt.py", line 394, in start
    hyperopt.start()
  File "/Users/nsm/freqtrade/freqtrade/optimize/hyperopt.py", line 325, in start
    f_val = self.run_optimizer_parallel(parallel, asked)
  File "/Users/nsm/freqtrade/freqtrade/optimize/hyperopt.py", line 263, in run_optimizer_parallel
    wrap_non_picklable_objects(self.generate_optimizer))(v) for v in asked)
  File "/Users/nsm/freqtrade/.env/lib/python3.7/site-packages/joblib/parallel.py", line 934, in __call__
    self.retrieve()
  File "/Users/nsm/freqtrade/.env/lib/python3.7/site-packages/joblib/parallel.py", line 833, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/Users/nsm/freqtrade/.env/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 521, in wrap_future_result
    return future.result(timeout=timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
TypeError: reduce() of empty sequence with no initial value
```

This happens between 1/4 - 1/2 through the tests, whether I am using 100 or 10000 epochs

**Comment by hroff-1902** [comment]
@gitgitgat please, create a new issue for new problem found or for a new question you have.
Otherwise the issue can become complete mess of many different problems and noone will read it...

Second, attach please at least commands you run when reporting exception tracebacks. Fill also the form with info about your environment.

**Comment by xmatthias** [comment]
I think i'll close this as the initial issue(s) have been explained / solved, and we have a new one for the `reduce` problem.

feel free to reopen if you don't see this issue as solved.
