### ISSUE TITLE
Support USDC as a stake

### ISSUE THREAD

**Issue by yperfanov** [freqtrade/freqtrade#1861]
I would like to use USDC as a stake trading with binance. I am currently using USDT but due to controversy that surround it would be nice if we can use another stable coin as a stake. It wont be a pleasure to wake up one morning and see that USDT have crashed -50% or something like that...

**Comment by hroff-1902** [comment]
@xmatthias could the static list of stake currencies be changed to dynamic excahange specific one?
i.e., we could implement get_quote_symbols() (and possibly get_symbols(), get_base_symbols() for completness) methods in the Exchange class and use the returned list for checking the stake_currency to be in it instead of the static hardcoded list.

Do you see any pitfalls for it? If not, I could implement the approach and issue the PR...

**Comment by xmatthias** [comment]
Any currency on the "2nd part" of a pair-combination can be used as stake currency (BTC/USD, BTC/USDX, HOT/XRP, ...). 
The only thing that may not work is `/balance`, which tends to fail for currencies where there is no correspoinding `pair/BTC` combination.
 
Apart from the `/balance` problem, there is nothing to stop you from using USDC.
You could even use XRP - which is also now a valid stake on Binace (for a limited amount of pairs ...).

**Comment by hroff-1902** [comment]
^^ @xmatthias is that comment was for me or for the author of the issue?

**Comment by xmatthias** [comment]
hm, didn't think about `constants.py` - but after that nothing is blocking the use of other stake currencies, as long as the pairs exist on the exchange.

**Comment by hroff-1902** [comment]
okay, assigning the issue to myself if you don't mind...

**Comment by xmatthias** [comment]
as an idea - i think we can remove this list completely, and replace it with a function 
 to find valid stake-currencies to the exchange class and parse the markets dict ...

**Comment by fernandobender** [comment]
hi there. i'd like to use USDC as stake currency, and StaticPairList / WhiteList "BTC/USDC, ETH/USDC", only.
As i saw from above comments, changing the stake_currency array in constants.py could work around it. however, i prefer not brake original code internals.
i've updated right now my install, and i'm checked out to develop branch.
1. is the current work discussed here allow trading with USDC as stake currency with static/whitelist?
2. if so, how can i monitor it's progress?
3. if i'd better have opened a new issue, please, indicate to me, i do it.
many thanks.

**Comment by hroff-1902** [comment]
There is an issue with this functionality -- how to provide converting to fiat currency for all those new quote currencies?

**Comment by xmatthias** [comment]
That's a minor issue (which is realistically not present).

It'll work for all currencies supported by coinmarketcap - and remember that we've been converting non-stake currencies too (when using /balance, for example) - and these can be "any and all" ... not just a handfull of stake-currencies - and there's never been an issue..

**Comment by xmatthias** [comment]
Good news - USDC (and other previously unsupported stake currencies) will now work from the develop branch (and starting with the next release, with the stable branch).

**Comment by YuriyTigiev** [comment]
Hello, 

Can I use BNB as stacking currency? I'm using the latest version of the docker 

ytigiev@ft01:~/ftBNB01$ docker-compose run --rm  ftBNB01 test-pairlist  --config ./user_data/configBNBDynamic.json  --print-json 
2021-03-30 16:36:50,132 - freqtrade.configuration.configuration - INFO - Using config: ./user_data/configBNBDynamic.json ...
2021-03-30 16:36:50,133 - freqtrade.loggers - INFO - Verbosity set to 0
2021-03-30 16:36:50,133 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2021-03-30 16:36:50,134 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/binance ...
2021-03-30 16:36:50,134 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2021-03-30 16:36:50,134 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2021-03-30 16:36:50,134 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2021-03-30 16:36:50,134 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2021-03-30 16:36:50,137 - freqtrade.configuration.config_validation - CRITICAL - Invalid configuration. Reason: 'BNB' is not one of ['AUD', 'BRL', 'CAD', 'CHF', 'CLP', 'CNY', 'CZK', 'DKK', 'EUR', 'GBP', 'HKD', 'HUF', 'IDR', 'ILS', 'INR', 'JPY', 'KRW', 'MXN', 'MYR', 'NOK', 'NZD', 'PHP', 'PKR', 'PLN', 'RUB', 'SEK', 'SGD', 'THB', 'TRY', 'TWD', 'ZAR', 'USD', 'BTC', 'ETH', 'XRP', 'LTC', 'BCH']

Failed validating 'enum' in schema['properties']['fiat_display_currency']:
    {'enum': ['AUD',
              'BRL',
              'CAD',
              'CHF',
              'CLP',
              'CNY',
              'CZK',
              'DKK',
              'EUR',
              'GBP',
              'HKD',
              'HUF',
              'IDR',
              'ILS',
              'INR',
              'JPY',
              'KRW',
              'MXN',
              'MYR',
              'NOK',
              'NZD',
              'PHP',
              'PKR',
              'PLN',
              'RUB',
              'SEK',
              'SGD',
              'THB',
              'TRY',
              'TWD',
              'ZAR',
              'USD',
              'BTC',
              'ETH',
              'XRP',
              'LTC',
              'BCH'],
     'type': 'string'}

On instance['fiat_display_currency']:
    'BNB'
2021-03-30 16:36:50,139 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/pairlist_commands.py", line 19, in start_test_pairlist
    config = setup_utils_configuration(args, RunMode.UTIL_EXCHANGE)
  File "/freqtrade/freqtrade/configuration/config_setup.py", line 25, in setup_utils_configuration
    validate_config_consistency(config)
  File "/freqtrade/freqtrade/configuration/config_validation.py", line 85, in validate_config_consistency
    validate_config_schema(conf)
  File "/freqtrade/freqtrade/configuration/config_validation.py", line 61, in validate_config_schema
    raise ValidationError(
jsonschema.exceptions.ValidationError: 'BNB' is not one of ['AUD', 'BRL', 'CAD', 'CHF', 'CLP', 'CNY', 'CZK', 'DKK', 'EUR', 'GBP', 'HKD', 'HUF', 'IDR', 'ILS', 'INR', 'JPY', 'KRW', 'MXN', 'MYR', 'NOK', 'NZD', 'PHP', 'PKR', 'PLN', 'RUB', 'SEK', 'SGD', 'THB', 'TRY', 'TWD', 'ZAR', 'USD', 'BTC', 'ETH', 'XRP', 'LTC', 'BCH']

**Comment by xmatthias** [comment]
as staking currency yes - but not as fiat_display currency.
