### ISSUE TITLE
--help produces traceback

### ISSUE THREAD

**Issue by hroff-1902** [freqtrade/freqtrade#1895]
Seems I broke it somehow.

`python3 freqtrade hyperopt --help`
produces traceback 
```
Fatal exception!
Traceback (most recent call last):
  File "/home/user/freqtrade-wrk/github-hroff-1902/freqtrade/freqtrade/main.py", line 42, in main
    args: Namespace = arguments.get_parsed_arg()
  File "/home/user/freqtrade-wrk/github-hroff-1902/freqtrade/freqtrade/arguments.py", line 46, in get_parsed_arg
    self.parsed_arg = self.parse_args()
  File "/home/user/freqtrade-wrk/github-hroff-1902/freqtrade/freqtrade/arguments.py", line 54, in parse_args
    parsed_arg = self.parser.parse_args(self.args)
  File "/usr/lib/python3.6/argparse.py", line 1743, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.6/argparse.py", line 1775, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.6/argparse.py", line 1963, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/usr/lib/python3.6/argparse.py", line 1940, in consume_positionals
    take_action(action, args)
  File "/usr/lib/python3.6/argparse.py", line 1849, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib/python3.6/argparse.py", line 1146, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/usr/lib/python3.6/argparse.py", line 1775, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.6/argparse.py", line 1981, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python3.6/argparse.py", line 1921, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.6/argparse.py", line 1849, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib/python3.6/argparse.py", line 1034, in __call__
    parser.exit()
  File "/usr/lib/python3.6/argparse.py", line 2389, in exit
    _sys.exit(status)
SystemExit: 0
```

**Comment by hroff-1902** [comment]
Not covered by tests.

**Comment by xmatthias** [comment]
well yes - `main.py` catches `BaseException` - and sysexit is one of these ... 

we don't have full line by line coverage, no. It would be great to have - but very time-consuming to archive - and still does not guarantee logic correctness as we've seen in the past.

**Comment by hroff-1902** [comment]
It's all right. I only noticed that it was not covered for archiving this fact.
