### ISSUE TITLE
Hyperopt - TypeError: populate_buy_trend() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by MichealReed** [freqtrade/freqtrade#1899]
Python Version: 3.6.7
    CCXT version: 1.18.507
    Branch: Develop
    Last Commit ID: 4ae743e

  
## Step 3: Describe the problem:

When running this command
`python3 freqtrade -c config.json hyperopt --customhyperopt MyHyperOpt-e 5000 --spaces all`

I am getting this error:

![image](https://user-images.githubusercontent.com/12153323/58755648-a5f4c000-84ad-11e9-8bdc-906475d6a56d.png)

```
Traceback (most recent call last):
  File "/home/micheal/.local/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 418, in _process_worker
    r = call_item()
  File "/home/micheal/.local/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 272, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/micheal/.local/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 567, in __call__
    return self.func(*args, **kwargs)
  File "/home/micheal/.local/lib/python3.6/site-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/home/micheal/.local/lib/python3.6/site-packages/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/micheal/.local/lib/python3.6/site-packages/joblib/externals/loky/cloudpickle_wrapper.py", line 38, in __call__
    return self._obj(*args, **kwargs)
  File "/mnt/c/Code/Github/freqtrade/freqtrade/optimize/hyperopt.py", line 198, in generate_optimizer
    'end_date': max_date,
  File "/mnt/c/Code/Github/freqtrade/freqtrade/optimize/backtesting.py", line 344, in backtest
    ticker: Dict = self._get_ticker_list(processed)
  File "/mnt/c/Code/Github/freqtrade/freqtrade/optimize/backtesting.py", line 228, in _get_ticker_list
    self.advise_buy(pair_data, {'pair': pair}), {'pair': pair})[headers].copy()
TypeError: populate_buy_trend() takes 1 positional argument but 2 were given
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "freqtrade/__main__.py", line 15, in <module>
    main.main(sys.argv[1:])
  File "/mnt/c/Code/Github/freqtrade/freqtrade/main.py", line 34, in main
    args.func(args)
  File "/mnt/c/Code/Github/freqtrade/freqtrade/optimize/hyperopt.py", line 366, in start
    hyperopt.start()
  File "/mnt/c/Code/Github/freqtrade/freqtrade/optimize/hyperopt.py", line 299, in start
    f_val = self.run_optimizer_parallel(parallel, asked)
  File "/mnt/c/Code/Github/freqtrade/freqtrade/optimize/hyperopt.py", line 253, in run_optimizer_parallel
    wrap_non_picklable_objects(self.generate_optimizer))(v) for v in asked)
  File "/home/micheal/.local/lib/python3.6/site-packages/joblib/parallel.py", line 934, in __call__
    self.retrieve()
  File "/home/micheal/.local/lib/python3.6/site-packages/joblib/parallel.py", line 833, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/micheal/.local/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 521, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
TypeError: populate_buy_trend() takes 1 positional argument but 2 were given
```

**Comment by xmatthias** [comment]
well the nice thing about python is that most errors are what they tell you they are.

check the syntax for your `populate_buy_trend()` function (in the custom-hyperopt class) ... i suspect there is omething wrong with the function header.

**Comment by MichealReed** [comment]
double and triple checked, seems to be no issues there.

![image](https://user-images.githubusercontent.com/12153323/58764715-4a1f4b00-8530-11e9-87bb-b56e24d801d1.png)
