### ISSUE TITLE
Huobi Pro - Issues downloading data

### ISSUE THREAD

**Issue by Dante2333** [freqtrade/freqtrade#1909]
## Step 1: Have you search for this issue before posting it?

Yes

## Step 2: Describe your environment

Python Version: python3.7
CCXT version: 1.18.551
Branch: Master | Develop
  
## Step 3: Describe the problem:

When trying to download backtesting data from HuobiPRO it starts downloading data but eventually gives out errors.

### Steps to reproduce:

  1. Configure Huobi PRO on config.js
  2. python3 freqtrade -c config.huobi.json -s strategy backtesting --timerange=20180101- --refresh-pairs-cached
  3.Wait

Used pairlist: (removed hydro as it does not work either)
```

[
    "RUFF/BTC",
    "MEX/BTC",
    "BOX/BTC",
    "KNC/BTC",
    "FTI/BTC",
    "STORJ/BTC",
    "DATX/BTC",
    "KCASH/BTC",
    "LBA/BTC",
    "BT1/BTC",
    "YEE/BTC",
    "CTXC/BTC",
    "SNT/BTC",
    "XMR/BTC",
    "YCC/BTC",
    "SRN/BTC",
    "DAT/BTC",
    "DBC/BTC",
    "PNT/BTC",
    "EOS/BTC",
    "GXC/BTC",
    "BKBT/BTC",
    "ZIL/BTC",
    "AIDOC/BTC",
    "MANA/BTC",
    "MXC/BTC",
    "DTA/BTC",
    "UTK/BTC",
    "Hydro Protocol/BTC",
    "IRIS/BTC",
    "GVE/BTC",
    "SC/BTC",
    "RCCC/BTC",
    "WAX/BTC",
    "GET/BTC",
    "NANO/BTC",
    "TOPC/BTC",
    "THETA/BTC",
    "CVNT/BTC",
    "ADA/BTC",
    "UGAS/BTC",
    "NPXS/BTC",
    "RCN/BTC",
    "BTS/BTC",
    "BIX/BTC",
    "NCASH/BTC",
    "NCC/BTC",
    "ETN/BTC",
    "ETH/BTC",
    "TNT/BTC",
    "NULS/BTC",
    "VET/BTC",
    "LET/BTC",
    "CDC/BTC",
    "XRP/BTC",
    "XLM/BTC",
    "WTC/BTC",
    "LOOM/BTC",
    "ZEC/BTC",
    "PC/BTC",
    "SALT/BTC",
    "ARDR/BTC",
    "SOC/BTC",
    "ZRX/BTC",
    "LTC/BTC",
    "BIFI/BTC",
    "VEN/BTC",
    "CVC/BTC",
    "UIP/BTC",
    "GNX/BTC",
    "AAC/BTC",
    "MTX/BTC",
    "WPR/BTC",
    "BFT/BTC",
    "TOP/BTC",
    "BTM/BTC",
    "SHE/BTC",
    "DCR/BTC",
    "BT2/BTC",
    "CHAT/BTC",
    "ENG/BTC",
    "WAVES/BTC",
    "MAN/BTC",
    "LYM/BTC",
    "GTC/BTC",
    "ZJLT/BTC",
    "SNC/BTC",
    "HIT/BTC",
    "PHX/BTC",
    "QUN/BTC",
    "LXT/BTC",
    "HT/BTC",
    "XVG/BTC",
    "BCX/BTC",
    "DAC/BTC",
    "DOCK/BTC",
    "WICC/BTC",
    "LUN/BTC",
    "HPT/BTC",
    "UC/BTC",
    "ONT/BTC",
    "GSC/BTC",
    "ABT/BTC",
    "ICX/BTC",
    "IDT/BTC",
    "STK/BTC",
    "ELF/BTC",
    "ATOM/BTC",
    "COVA/BTC",
    "UUU/BTC",
    "DGD/BTC",
    "EKT/BTC",
    "RSR/BTC",
    "XMX/BTC",
    "XTZ/BTC",
    "TOS/BTC",
    "MUSK/BTC",
    "MDS/BTC",
    "REQ/BTC",
    "TT/BTC",
    "EGCC/BTC",
    "DGB/BTC",
    "RBTC/BTC",
    "BSV/BTC",
    "HC/BTC",
    "REN/BTC",
    "WAN/BTC",
    "GAS/BTC",
    "BLZ/BTC",
    "EVX/BTC",
    "BTG/BTC",
    "BCH/BTC",
    "BUT/BTC",
    "GRS/BTC",
    "APPC/BTC",
    "XEM/BTC",
    "GNT/BTC",
    "TRX/BTC",
    "PROPY/BTC",
    "ZEN/BTC",
    "DOGE/BTC",
    "RTE/BTC",
    "AE/BTC",
    "STEEM/BTC",
    "MTN/BTC",
    "IOST/BTC",
    "POWR/BTC",
    "TRIO/BTC",
    "DASH/BTC",
    "LAMB/BTC",
    "KMD/BTC",
    "18C/BTC",
    "CVCOIN/BTC",
    "CNN/BTC",
    "FAIR/BTC",
    "SEELE/BTC",
    "ETC/BTC",
    "MEET/BTC",
    "PAI/BTC",
    "OST/BTC",
    "SSP/BTC",
    "LINK/BTC",
    "BCV/BTC",
    "NEXO/BTC",
    "BTT/BTC",
    "ELA/BTC",
    "EDU/BTC",
    "CMT/BTC",
    "BAT/BTC",
    "BCD/BTC",
    "NEW/BTC",
    "SBTC/BTC",
    "MT/BTC",
    "PORTAL/BTC",
    "IOTA/BTC",
    "XZC/BTC",
    "QSP/BTC",
    "EKO/BTC",
    "NEO/BTC",
    "RDN/BTC",
    "ZLA/BTC",
    "MTL/BTC",
    "NAS/BTC",
    "SWFTC/BTC",
    "IIC/BTC",
    "PAY/BTC",
    "OMG/BTC",
    "LSK/BTC",
    "AST/BTC",
    "SMT/BTC",
    "ADX/BTC",
    "TNB/BTC",
    "OCN/BTC",
    "ITC/BTC",
    "POLY/BTC",
    "ACT/BTC",
    "KAN/BTC",
    "QTUM/BTC",
    "MCO/BTC",
    "QASH/BTC"
]
```

  
### Observed Results:

  * What happened? 
Pairs start fetching and eventually these few errors come through.
  * What did you expect to happen?

To download and fetch pairs normally then proceed to backtest.

### Relevant code exceptions or logs:

  ```
 2019-06-05 13:03:04,836 - freqtrade.exchange.exchange - WARNING - _async_get_candle_history() returned exception: "Could not load ticker history due to ExchangeError. Message: huobipro {"ts":1559739800478,"status":"error","err-code":"invalid-parameter","err-msg":"invalid symbol"}"
2019-06-05 13:03:04,837 - freqtrade.exchange.exchange - WARNING - Giving up retrying: _async_get_candle_history()
2019-06-05 13:03:06,354 - freqtrade.exchange.exchange - WARNING - _async_get_candle_history() returned exception: "Could not load ticker history due to ExchangeError. Message: huobipro {"ts":1559739801979,"status":"error","err-code":"invalid-parameter","err-msg":"invalid symbol"}"
2019-06-05 13:03:06,355 - freqtrade.exchange.exchange - WARNING - Giving up retrying: _async_get_candle_history()
2019-06-05 13:03:07,824 - freqtrade.exchange.exchange - WARNING - _async_get_candle_history() returned exception: "Could not load ticker history due to ExchangeError. Message: huobipro {"ts":1559739803478,"status":"error","err-code":"invalid-parameter","err-msg":"invalid symbol"}"
2019-06-05 13:03:07,824 - freqtrade.exchange.exchange - WARNING - Giving up retrying: _async_get_candle_history()
2019-06-05 13:03:09,350 - freqtrade.exchange.exchange - WARNING - _async_get_candle_history() returned exception: "Could not load ticker history due to ExchangeError. Message: huobipro {"ts":1559739804977,"status":"error","err-code":"invalid-parameter","err-msg":"invalid symbol"}"
2019-06-05 13:03:09,351 - freqtrade.exchange.exchange - WARNING - Giving up retrying: _async_get_candle_history()
2019-06-05 13:03:10,841 - freqtrade.exchange.exchange - WARNING - _async_get_candle_history() returned exception: "Could not load ticker history due to ExchangeError. Message: huobipro {"ts":1559739806484,"status":"error","err-code":"invalid-parameter","err-msg":"invalid symbol"}"
2019-06-05 13:03:10,841 - freqtrade.exchange.exchange - WARNING - Giving up retrying: _async_get_candle_history()
2019-06-05 13:03:12,355 - freqtrade.exchange.exchange - WARNING - _async_get_candle_history() returned exception: "Could not load ticker history due to ExchangeError. Message: huobipro {"ts":1559739807981,"status":"error","err-code":"invalid-parameter","err-msg":"invalid symbol"}"
2019-06-05 13:03:12,356 - freqtrade.exchange.exchange - WARNING - Giving up retrying: _async_get_candle_history()
2019-06-05 13:03:13,824 - freqtrade.exchange.exchange - WARNING - _async_get_candle_history() returned exception: "Could not load ticker history due to ExchangeError. Message: huobipro {"ts":1559739809476,"status":"error","err-code":"invalid-parameter","err-msg":"invalid symbol"}"
2019-06-05 13:03:13,824 - freqtrade.exchange.exchange - WARNING - Giving up retrying: _async_get_candle_history()
2019-06-05 13:03:15,346 - freqtrade.exchange.exchange - WARNING - _async_get_candle_history() returned exception: "Could not load ticker history due to ExchangeError. Message: huobipro {"ts":1559739810978,"status":"error","err-code":"invalid-parameter","err-msg":"invalid symbol"}"
2019-06-05 13:03:15,347 - freqtrade.exchange.exchange - WARNING - Giving up retrying: _async_get_candle_history()
2019-06-05 13:03:16,853 - freqtrade.exchange.exchange - WARNING - _async_get_candle_history() returned exception: "Could not load ticker history due to ExchangeError. Message: huobipro {"ts":1559739812485,"status":"error","err-code":"invalid-parameter","err-msg":"invalid symbol"}"
2019-06-05 13:03:16,855 - freqtrade.exchange.exchange - WARNING - Giving up retrying: _async_get_candle_history()
2019-06-05 13:03:18,354 - freqtrade.exchange.exchange - WARNING - _async_get_candle_history() returned exception: "Could not load ticker history due to ExchangeError. Message: huobipro {"ts":1559739813981,"status":"error","err-code":"invalid-parameter","err-msg":"invalid symbol"}"
2019-06-05 13:03:18,355 - freqtrade.exchange.exchange - WARNING - Giving up retrying: _async_get_candle_history()
2019-06-05 13:03:19,845 - freqtrade.exchange.exchange - WARNING - _async_get_candle_history() returned exception: "Could not load ticker history due to ExchangeError. Message: huobipro {"ts":1559739815482,"status":"error","err-code":"invalid-parameter","err-msg":"invalid symbol"}"
2019-06-05 13:03:19,846 - freqtrade.exchange.exchange - WARNING - Giving up retrying: _async_get_candle_history()
2019-06-05 13:03:21,360 - freqtrade.exchange.exchange - WARNING - _async_get_candle_history() returned exception: "Could not load ticker history due to ExchangeError. Message: huobipro {"ts":1559739816980,"status":"error","err-code":"invalid-parameter","err-msg":"invalid symbol"}"
2019-06-05 13:03:21,361 - freqtrade.exchange.exchange - WARNING - Giving up retrying: _async_get_candle_history()
2019-06-05 13:03:22,860 - freqtrade.exchange.exchange - WARNING - _async_get_candle_history() returned exception: "Could not load ticker history due to ExchangeError. Message: huobipro {"ts":1559739818489,"status":"error","err-code":"invalid-parameter","err-msg":"invalid symbol"}"
2019-06-05 13:03:22,861 - freqtrade.exchange.exchange - WARNING - Giving up retrying: _async_get_candle_history()
2019-06-05 13:03:22,862 - freqtrade.data.history - ERROR - Failed to download history data for pair: "CDC/BTC", interval: 1h. Error: cannot unpack non-iterable TemporaryError object
2019-06-05 13:03:22,863 - freqtrade.data.history - WARNING - No history data for pair: "CDC/BTC", interval: 1h. Use --refresh-pairs-cached option or download_backtest_data.py script to download the data
2019-06-05 13:03:22,864 - freqtrade.data.history - INFO - Download history data for pair: "XRP/BTC", interval: 1h and store in user_data/data/huobipro.
2019-06-05 13:04:00,637 - freqtrade.exchange.exchange - INFO - downloaded XRP/BTC with length 24488.
2019-06-05 13:04:00,639 - freqtrade.misc - INFO - dumping json to "user_data/data/huobipro/XRP_BTC-1h.json"
2019-06-05 13:04:00,758 - freqtrade.data.history - WARNING - Missing data at start for pair XRP/BTC, data starts at 2019-04-24 22:00:00
2019-06-05 13:04:00,790 - freqtrade.data.history - INFO - Download history data for pair: "XLM/BTC", interval: 1h and store in user_data/data/huobipro.
2019-06-05 13:04:37,967 - freqtrade.exchange.exchange - INFO - downloaded XLM/BTC with length 24488.
2019-06-05 13:04:37,971 - freqtrade.misc - INFO - dumping json to "user_data/data/huobipro/XLM_BTC-1h.json"
2019-06-05 13:04:38,084 - freqtrade.data.history - WARNING - Missing data at start for pair XLM/BTC, data starts at 2019-04-24 22:00:00
2019-06-05 13:04:38,117 - freqtrade.data.history - INFO - Download history data for pair: "WTC/BTC", interval: 1h and store in user_data/data/huobipro.
2019-06-05 13:05:15,586 - freqtrade.exchange.exchange - INFO - downloaded WTC/BTC with length 24488.
2019-06-05 13:05:15,589 - freqtrade.misc - INFO - dumping json to "user_data/data/huobipro/WTC_BTC-1h.json"
2019-06-05 13:05:15,734 - freqtrade.data.history - WARNING - Missing data at start for pair WTC/BTC, data starts at 2019-04-24 22:00:00
2019-06-05 13:05:15,770 - freqtrade.data.history - INFO - Download history data for pair: "LOOM/BTC", interval: 1h and store in user_data/data/huobipro.
2019-06-05 13:05:53,269 - freqtrade.exchange.exchange - INFO - downloaded LOOM/BTC with length 24488.
2019-06-05 13:05:53,270 - freqtrade.misc - INFO - dumping json to "user_data/data/huobipro/LOOM_BTC-1h.json"
2019-06-05 13:05:53,375 - freqtrade.data.history - WARNING - Missing data at start for pair LOOM/BTC, data starts at 2019-04-24 22:00:00
2019-06-05 13:05:53,412 - freqtrade.data.history - INFO - Download history data for pair: "ZEC/BTC", interval: 1h and store in user_data/data/huobipro.
2019-06-05 13:06:30,473 - freqtrade.exchange.exchange - INFO - downloaded ZEC/BTC with length 24488.
2019-06-05 13:06:30,474 - freqtrade.misc - INFO - dumping json to "user_data/data/huobipro/ZEC_BTC-1h.json"
2019-06-05 13:06:30,570 - freqtrade.data.history - WARNING - Missing data at start for pair ZEC/BTC, data starts at 2019-04-24 22:00:00
2019-06-05 13:06:30,605 - freqtrade.data.history - INFO - Download history data for pair: "PC/BTC", interval: 1h and store in user_data/data/huobipro.
2019-06-05 13:07:08,157 - freqtrade.exchange.exchange - INFO - downloaded PC/BTC with length 24488.
2019-06-05 13:07:08,159 - freqtrade.misc - INFO - dumping json to "user_data/data/huobipro/PC_BTC-1h.json"
2019-06-05 13:07:08,263 - freqtrade.data.history - WARNING - Missing data at start for pair PC/BTC, data starts at 2019-04-24 22:00:00
2019-06-05 13:07:08,297 - freqtrade.data.history - INFO - Download history data for pair: "SALT/BTC", interval: 1h and store in user_data/data/huobipro.
2019-06-05 13:07:45,541 - freqtrade.exchange.exchange - INFO - downloaded SALT/BTC with length 24463.
2019-06-05 13:07:45,543 - freqtrade.misc - INFO - dumping json to "user_data/data/huobipro/SALT_BTC-1h.json"
2019-06-05 13:07:45,736 - freqtrade.data.history - WARNING - Missing data at start for pair SALT/BTC, data starts at 2019-04-24 22:00:00
2019-06-05 13:07:45,772 - freqtrade.data.history - INFO - Download history data for pair: "ARDR/BTC", interval: 1h and store in user_data/data/huobipro.
2019-06-05 13:07:45,773 - freqtrade.data.history - ERROR - Failed to download history data for pair: "ARDR/BTC", interval: 1h. Error: Parse error at offset 0: The document is empty.
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "freqtrade/__main__.py", line 15, in <module>
    main.main(sys.argv[1:])
  File "/home/dante/freqtrade/freqtrade/main.py", line 34, in main
    args.func(args)
  File "/home/dante/freqtrade/freqtrade/optimize/backtesting.py", line 524, in start
    backtesting.start()
  File "/home/dante/freqtrade/freqtrade/optimize/backtesting.py", line 425, in start
    timerange=timerange
  File "/home/dante/freqtrade/freqtrade/data/history.py", line 135, in load_data
    fill_up_missing=fill_up_missing)
  File "/home/dante/freqtrade/freqtrade/data/history.py", line 97, in load_pair_history
    pairdata = load_tickerdata_file(datadir, pair, ticker_interval, timerange=timerange)
  File "/home/dante/freqtrade/freqtrade/data/history.py", line 67, in load_tickerdata_file
    pairdata = misc.file_load_json(filename)
  File "/home/dante/freqtrade/freqtrade/misc.py", line 104, in file_load_json
    pairdata = json_load(tickerdata)
  File "/home/dante/freqtrade/freqtrade/misc.py", line 89, in json_load
    return rapidjson.load(datafile, number_mode=rapidjson.NM_NATIVE)
rapidjson.JSONDecodeError: Parse error at offset 0: The document is empty.

  ```

**Comment by Dante2333** [comment]
I'm going to close this; it got fixed after deleting user_data/data/huobipro data.. I think we should add some kind of fail-safe where if there's any error, to purge the given pairs data and re-try fetching it. @hroff-1902
