### ISSUE TITLE
Backtesting: ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by gitgitgat** [freqtrade/freqtrade#1948]
(`Python 3.6.8 :: Anaconda, Inc`)
(`ccxt==1.18.667`)
Develop
Last Commit ID:`0d8b572a171e767e3429699c62250816294ede53`)
  

The most recent error in backtesting:

```
2019-06-19 11:07:12,301 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/user/Github/freqtrade/freqtrade/main.py", line 46, in main
    args.func(args)
  File "/home/user/Github/freqtrade/freqtrade/optimize/__init__.py", line 61, in start_backtesting
    backtesting.start()
  File "/home/user/Github/freqtrade/freqtrade/optimize/backtesting.py", line 449, in start
    'end_date': max_date,
  File "/home/user/Github/freqtrade/freqtrade/optimize/backtesting.py", line 378, in backtest
    max_open_trades)
  File "/home/user/Github/freqtrade/freqtrade/optimize/backtesting.py", line 254, in _get_sell_trade_entry
    sell_row.sell, low=sell_row.low, high=sell_row.high)
  File "/home/user/Github/freqtrade/freqtrade/strategy/interface.py", line 280, in should_sell
    if self.min_roi_reached(trade=trade, current_profit=current_profit, current_time=date):
  File "/home/user/Github/freqtrade/freqtrade/strategy/interface.py", line 359, in min_roi_reached
    roi_entry = max(list(filter(lambda x: trade_dur >= x, self.minimal_roi.keys())))
ValueError: max() arg is an empty sequence


```

**Comment by hroff-1902** [comment]
What's the value of minimal_roi option set in your config and/or in the strategy?

**Comment by gitgitgat** [comment]
> What's the value of the "minimal_roi" option set in your config and/or in the strategy?
> What timeframe do you use for backtesting?

minimal_roi is using the values returned from the hyperopts and I am using 15m in this one. The config one is overriding the strategy.py file and the command line overrides ticker timeframe

**Comment by gitgitgat** [comment]
it could be that minimal_roi is set quite high because I didn't change it from the 1d tests I tried, and it is pocketing the trailing stop returning 'no value' for minimal_roi, but I don't know if/why that should be a problem

**Comment by xmatthias** [comment]
What is the exact command you're running to get this error?

**Comment by gitgitgat** [comment]
python3 freqtrade -s StrategyOne backtesting -i 15m

**Comment by xmatthias** [comment]
how does StrategyOne define `minimal_roi`?

this error does only happen if nothing is in the dict ...

**Comment by gitgitgat** [comment]
> how does StrategyOne define `minimal_roi`?
> 
> this error does only happen if nothing is in the dict ...

ok, it's left unchanged because by minimal_roi is in the config file

**Comment by gitgitgat** [comment]
I had realised I missed a parameter, but now I get 

2019-06-19 15:39:28,457 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/user/Github/freqtrade/freqtrade/main.py", line 46, in main
    args.func(args)
  File "/home/user/Github/freqtrade/freqtrade/optimize/__init__.py", line 61, in start_backtesting
    backtesting.start()
  File "/home/user/Github/freqtrade/freqtrade/optimize/backtesting.py", line 449, in start
    'end_date': max_date,
  File "/home/user/Github/freqtrade/freqtrade/optimize/backtesting.py", line 335, in backtest
    ticker: Dict = self._get_ticker_list(processed)
  File "/home/user/Github/freqtrade/freqtrade/optimize/backtesting.py", line 220, in _get_ticker_list
    self.advise_buy(pair_data, {'pair': pair}), {'pair': pair})[headers].copy()
  File "/home/user/Github/freqtrade/freqtrade/strategy/interface.py", line 401, in advise_buy
    return self.populate_buy_trend(dataframe, metadata)
  File "/home/user/Github/freqtrade/user_data/strategies/test_strat_to.py", line 288, in populate_buy_trend
    'buy'] = 1
  File "/home/user/Github/freqtrade/freqtrade/vendor/qtpylib/indicators.py", line 244, in crossed_above
    return crossed(series1, series2, "above")
  File "/home/user/Github/freqtrade/freqtrade/vendor/qtpylib/indicators.py", line 230, in crossed
    above = pd.Series((series1 > series2) & (
  File "/home/user/.conda/envs/freqtrade/lib/python3.6/site-packages/pandas/core/ops.py", line 1745, in wrapper
    raise ValueError('Lengths must match to compare')
ValueError: Lengths must match to compare

**Comment by gitgitgat** [comment]
the qtpylib error was solved, a minor issue, but the roi remains there

**Comment by hroff-1902** [comment]
> > how does StrategyOne define `minimal_roi`?
> > this error does only happen if nothing is in the dict ...
> 
> ok, it's left unchanged because by minimal_roi is in the config file

Okay, how does config define `minimal_roi`?

**Comment by gitgitgat** [comment]
it seemed to work with hyperopts, once deleted it works but only from the .py file so it was not overriding

**Comment by hroff-1902** [comment]
So the problem is solved?

**Comment by gitgitgat** [comment]
yeah, but only by removing minimal_roi from config
"minimal_roi" : {
"x" : xx 
"x" : xx
"x" : xx
"x" : xx
}

**Comment by hroff-1902** [comment]
@xmatthias a check should be added here, avoiding exception which came from max().

**Comment by gitgitgat** [comment]
actually the error is being raised again, it only works if minimal roi uses the default parameters
