### ISSUE TITLE
ValueError: Lengths must match to compare

### ISSUE THREAD

**Issue by gitgitgat** [freqtrade/freqtrade#1950]
I had realised I missed a parameter, but now I get 

```
2019-06-19 15:39:28,457 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/user/Github/freqtrade/freqtrade/main.py", line 46, in main
    args.func(args)
  File "/home/user/Github/freqtrade/freqtrade/optimize/__init__.py", line 61, in start_backtesting
    backtesting.start()
  File "/home/user/Github/freqtrade/freqtrade/optimize/backtesting.py", line 449, in start
    'end_date': max_date,
  File "/home/user/Github/freqtrade/freqtrade/optimize/backtesting.py", line 335, in backtest
    ticker: Dict = self._get_ticker_list(processed)
  File "/home/user/Github/freqtrade/freqtrade/optimize/backtesting.py", line 220, in _get_ticker_list
    self.advise_buy(pair_data, {'pair': pair}), {'pair': pair})[headers].copy()
  File "/home/user/Github/freqtrade/freqtrade/strategy/interface.py", line 401, in advise_buy
    return self.populate_buy_trend(dataframe, metadata)
  File "/home/user/Github/freqtrade/user_data/strategies/test_strat_to.py", line 288, in populate_buy_trend
    'buy'] = 1
  File "/home/user/Github/freqtrade/freqtrade/vendor/qtpylib/indicators.py", line 244, in crossed_above
    return crossed(series1, series2, "above")
  File "/home/user/Github/freqtrade/freqtrade/vendor/qtpylib/indicators.py", line 230, in crossed
    above = pd.Series((series1 > series2) & (
  File "/home/user/.conda/envs/freqtrade/lib/python3.6/site-packages/pandas/core/ops.py", line 1745, in wrapper
    raise ValueError('Lengths must match to compare')
ValueError: Lengths must match to compare
```
i had earlier gotten that same mistake, it could be that the pairlist includes newly added currencies and return the one with 'expected x frames, got x_less frames'.
gonna check if removing them from the list would do anything or something to do with qtpylib

_Originally posted by @gitgitgat in https://github.com/freqtrade/freqtrade/issues/1948#issuecomment-503718180_

**Comment by gitgitgat** [comment]
removing the pair missing frames does nothing

**Comment by xmatthias** [comment]
well what is it that you pass to `crossed_above()` ? 

Without the section of the code from your strategy that's causing the error, these problems are impossible to diagnose.

**Comment by gitgitgat** [comment]
qtpylib.crossed_above(0)

**Comment by xmatthias** [comment]
`qtpylib.crossed_above()` takes 2 arguments ... so you'll need to use for example:

`qtpylib.crossed_above(dataframe['rsi'], 30)`

**Comment by xmatthias** [comment]
I'll close this since it appears to be an error with what is passed to `crossed_*()` functions. 
Feel free to reopen if there are more questions around this.
