### ISSUE TITLE
Forcebuy - Works but does not update on TG

### ISSUE THREAD

**Issue by Dante2333** [freqtrade/freqtrade#1986]
## Step 1: Have you search for this issue before posting it?

Yes

## Step 2: Describe your environment

  * Python Version: 3.7
  * CCXT version: latest
  * Branch: Master
  * Last Commit ID: 2019.06
  * Exchange: Binance

  
## Step 3: Describe the problem:

I force bought a pair, the pair was bought and its on balance but wont come up on /status table, it is as it was never written and its no where to be seen on the database. Pair is ALGO/USDT

### Steps to reproduce:

I'm not quite sure.
  
### Observed Results:

  * What happened?
It bought but does not come on /status table as if it never bought it
  * What did you expect to happen?
That it buys and updates the /status table

### Relevant code exceptions or logs:

  ```
2019-06-30 03:51:36,539 - freqtrade.rpc.telegram - INFO - Executing handler: _forcebuy for chat_id: 146554112
2019-06-30 03:51:36,545 - freqtrade.freqtradebot - INFO - Using Last Ask / Last Price
2019-06-30 03:51:37,260 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': buy, 'exchange': 'Binance', 'pair': 'ALGO/USDT', 'limit': 1.5642505330623224, 'order_type': 'market', 'stake_amount': 13811.040136000001, 'stake_currency': 'USDT', 'fiat_currency': 'USD'}
2019-06-30 03:51:37,612 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=None, pair=ALGO/USDT, amount=8829.17400000, open_rate=1.56425053, open_since=closed)
2019-06-30 03:51:37,758 - freqtrade.freqtradebot - WARNING - Amount 8829.173999999999 does not match amount 8829.174
2019-06-30 03:51:37,760 - freqtrade.freqtradebot - WARNING - Could not update trade amount: Half bought? Amounts don't match
2019-06-30 03:51:37,760 - freqtrade.persistence - INFO - Updating trade (id=None) ...
2019-06-30 03:51:37,760 - freqtrade.persistence - INFO - MARKET_BUY has been fulfilled for Trade(id=None, pair=ALGO/USDT, amount=8829.17400000, open_rate=1.56425053, open_since=closed).
2019-06-30 03:51:37,761 - freqtrade.rpc.telegram - ERROR - Exception occurred within Telegram module
Traceback (most recent call last):
  File "/home/dante/freqtrade/freqtrade/rpc/telegram.py", line 52, in wrapper
    return command_handler(self, *args, **kwargs)
  File "/home/dante/freqtrade/freqtrade/rpc/telegram.py", line 433, in _forcebuy
    self._rpc_forcebuy(pair, price)
  File "/home/dante/freqtrade/freqtrade/rpc/rpc.py", line 432, in _rpc_forcebuy
    if self._freqtrade.execute_buy(pair, stakeamount, price):
  File "/home/dante/freqtrade/freqtrade/freqtradebot.py", line 416, in execute_buy
    self.update_trade_state(trade, order)
  File "/home/dante/freqtrade/freqtrade/freqtradebot.py", line 539, in update_trade_state
    trade.update(order)
  File "/home/dante/freqtrade/freqtrade/persistence.py", line 317, in update
    cleanup()
  File "/home/dante/freqtrade/freqtrade/persistence.py", line 155, in cleanup
    Trade.session.flush()
  File "/home/dante/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2445, in flush
    raise sa_exc.InvalidRequestError("Session is already flushing")
sqlalchemy.exc.InvalidRequestError: Session is already flushing


  ```

**Comment by Dante2333** [comment]
It's also good to mention that I'm still using market orders, check #1887 (closed issue), as you see here, 

2019-06-30 03:51:37,260 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': buy, 'exchange': 'Binance', 'pair': 'ALGO/USDT', 'limit': 1.5642505330623224, 'order_type': 'market', 'stake_amount': 13811.040136000001, 'stake_currency': 'USDT', 'fiat_currency': 'USD'}

why does it says limit?

**Comment by xmatthias** [comment]
`limit` defines the price - which is limit in case of a limit order, or current price for a market order.
It's just a filename - the telegram-rpc will then plot something else.

**Comment by xmatthias** [comment]
just to confirm what happened:

- you used `/forcebuy pairxxx`
- the bot did buy on the exchange
- the trade is in the database (and is still open!)
- `/status` | `/status table` don't show any result

**Comment by Dante2333** [comment]
> just to confirm what happened:
> 
> * you used `/forcebuy pairxxx`
> * the bot did buy on the exchange
> * the trade is in the database (and is still open!)
> * `/status` | `/status table` don't show this trade after a minute

Sorry, I modified the title and the first report, it is NOT in the database.
*I used forcebuy
*The bot bought
*The trade was NOT written in the database
*/status | /status table dont show the trade after a minute

**Comment by xmatthias** [comment]
well ok, now it makes more sense - the title suggested that database did work.

**Comment by xmatthias** [comment]
I do struggle to recreate this issue, which makes trying to fix it nearly impossible.
When trying to `/forcebuy` - and immediately use `/status table` - i do get the output i would expect:

![2019-08-25-153429_580x454_scrot](https://user-images.githubusercontent.com/5024695/63650699-d6b36100-c74d-11e9-82eb-16a6d43fb303.png)

![2019-08-25-153634_558x344_scrot](https://user-images.githubusercontent.com/5024695/63650716-209c4700-c74e-11e9-9b39-e07366f11327.png)

Question: did this happen again? 
Did you get the "Buying" notification right after issuing `/forcebuy  ` ? 
what database are you using (what's your `--db-url` argument look like?

**Comment by hroff-1902** [comment]
```
  File "/home/dante/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2445, in flush
    raise sa_exc.InvalidRequestError("Session is already flushing")
sqlalchemy.exc.InvalidRequestError: Session is already flushing
```

I found this, can it be related to the issue?: https://stackoverflow.com/questions/45972401/invalidrequesterror-session-is-already-flushing-has-been-occurred-in-before-f, see the answer...

**Comment by xmatthias** [comment]
honestly, i'm not certain about these options.

we use both `autocommit=True` and `autoflush=True` - however we do flush in certain areas of the code (which sqlalchemy does not mind ...).
The documentation says that autocommit implicitly autoflushes, so i am not sure if the `flush()` commands are necessary.

However, if `flush()` would be a general problem, it should (at least randomly) also happen during my tests (and i use /forcebuy quite often to test sell behaviour) - unless something is completely different (like using postgres instead of sqlite) - which could change this error.
