### ISSUE TITLE
Start Bot

### ISSUE THREAD

**Issue by EmiP210** [freqtrade/freqtrade#2020]
## Step 1: Have you search for this issue before posting it?
I cannot find anything related in the known issues thread

## Step 2: Describe your environment

  * Python Version: 3.6.8
  * CCXT version: 1.18.860
  * Branch: Develop
  * Last Commit ID: f0206a90b1504c40e74b1c6bae4c719779cdee85
  
## Step 3: Describe the problem:

I have not been able to run the bot even to dry run test. I keep getting error messages and Trace Backs that I don't understand. 

### Steps to reproduce:

I try running the bot using `freqtrade -c config.json` I've reinstalled from the most recent developer mode of freqtrade. I've tried updating pip, python, numby and nothing changes the outcome. I'm sure it's staring me right in the face. 

### Relevant code exceptions or logs:

  ```
(.env) mtg@mtgvb:~/freqtrade$ freqtrade -c config.json
Traceback (most recent call last):
  File "/home/mtg/freqtrade/.env/bin/freqtrade", line 11, in <module>
    load_entry_point('freqtrade', 'console_scripts', 'freqtrade')()
  File "/home/mtg/freqtrade/.env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/mtg/freqtrade/.env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/home/mtg/freqtrade/.env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/home/mtg/freqtrade/.env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/mtg/freqtrade/freqtrade/main.py", line 19, in <module>
    from freqtrade.configuration import set_loggers
ImportError: cannot import name 'set_loggers'
```

**Comment by hroff-1902** [comment]
@xmatthias :

https://github.com/freqtrade/freqtrade/blob/f0206a90b1504c40e74b1c6bae4c719779cdee85/bin/freqtrade#L6

**Comment by hroff-1902** [comment]
@EmiP210 

Try to run `setup.sh -i` again. (Deactivate venv before running it)

**Comment by xmatthias** [comment]
i assume the bot was installed a while ago (before we used the automatic binary using setuptools), in which case the installed `freqtrade` binary (`which freqtrade`) will link to this binary. 
We left this binary "around" for compatibility reasons ... 
Reinstalling should create the "new" binary however.

activating the venv and running `pip install -e .` should also fix this (and will not reinstall the whole virtual environment).

**Comment by EmiP210** [comment]
I tried all these suggestions and then ended up reinstalling the whole bot. I had it running until I started removing invalid pairs from the whitelist. While those pairs exist, it will start to sequence, but the second I remove them I get:

``Fatal exception!
Traceback (most recent call last):
  File "/home/mtg/freqtrade/freqtrade/main.py", line 48, in main
    worker = Worker(args)
  File "/home/mtg/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/home/mtg/freqtrade/freqtrade/worker.py", line 48, in _init
    self._config = Configuration(self._args, None).get_config()
  File "/home/mtg/freqtrade/freqtrade/configuration/configuration.py", line 39, in get_config
    self.config = self.load_config()
  File "/home/mtg/freqtrade/freqtrade/configuration/configuration.py", line 54, in load_config
    config = deep_merge_dicts(self._load_config_file(path), config)
  File "/home/mtg/freqtrade/freqtrade/configuration/configuration.py", line 97, in _load_config_file
    conf = json.load(file)
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 43 column 13 (char 1043)
``

**Comment by xmatthias** [comment]
You'll need to be very carefull with the syntax of the json.
From the default

```json
        "pair_whitelist": [
            "ETH/BTC",
            "LTC/BTC",
            "ETC/BTC",
            "DASH/BTC",
            "ZEC/BTC",
            "XLM/BTC",
            "NXT/BTC",
            "POWR/BTC",
            "ADA/BTC",
            "XMR/BTC"
        ],
```

To invalid (notice the trailing comma).
```json
        "pair_whitelist": [
            "ETH/BTC",
            "LTC/BTC",
            "ETC/BTC",
            "DASH/BTC",
            "ZEC/BTC",
            "XLM/BTC",
            "NXT/BTC",
            "POWR/BTC",
            "ADA/BTC",   <-- This colon is wrong
        ],
```

For your error - best look at row 43 of your configuration(or the row before that) - that will have either a missing colon, or one too much (last element cannot have a colon).
