### ISSUE TITLE
Binance order does not exist

### ISSUE THREAD

**Issue by Ish2k2** [freqtrade/freqtrade#2021]
Describe your environment

running in docker
  
Describe the problem:

I have a couple of trades that crash the bot I have seen it in both buy and sell. In the situation below its a trailing stop loss where the bot is selling on binance and crashes. The bot succeeds in making the trade but I get the error "order does not exist" and it crashes. I can restart the bot and continue as normal - which I have done. 
  

Relevant code exceptions or logs:
```
2019-07-15 00:30:38,989 - freqtrade.exchange.exchange - INFO - returning cached ticker-data for ETH/USDT
2019-07-15 00:30:38,990 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': sell, 'exchange': 'Binance', 'pair': 'ETH/USDT', 'gain': 'loss', 'limit': 204.41, 'amount': 1.32327, 'open_rate': 226.71, 'current_rate': 204.41, 'profit_amount': -30.07940916, 'profit_percent': -0.10016502, 'sell_reason': 'trailing_stop_loss', 'stake_currency': 'USDT', 'fiat_currency': 'USD'}
2019-07-15 00:30:39,464 - freqtrade.freqtradebot - INFO - executed sell, reason: SellType.TRAILING_STOP_LOSS
2019-07-15 00:30:39,635 - freqtrade.wallets - INFO - Wallets synced.
2019-07-15 00:30:40,643 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 509, in fetch
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order?timestamp=1563150640467&recvWindow=5000&symbol=ETHUSDT&orderId=349333925&signature=3bd26d11c2a2dc6b676bf798a11a0402ec06cc1245373b7ed04df9123051b50c

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/exchange.py", line 631, in get_order
    return self._api.fetch_order(order_id, pair)
  File "/usr/local/lib/python3.7/site-packages/ccxt/binance.py", line 710, in fetch_order
    response = self.privateGetOrder(self.extend(request, params))
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 404, in inner
    return entry(_self, **inner_kwargs)
  File "/usr/local/lib/python3.7/site-packages/ccxt/binance.py", line 1210, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 429, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 521, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, headers, http_response, json_response)
  File "/usr/local/lib/python3.7/site-packages/ccxt/binance.py", line 1203, in handle_errors
    raise exceptions[error](self.id + ' ' + body)
ccxt.base.errors.OrderNotFound: binance {"code":-2013,"msg":"Order does not exist."}
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 42, in main
    worker.run()
  File "/freqtrade/freqtrade/worker.py", line 72, in run
    state = self._worker(old_state=state)
  File "/freqtrade/freqtrade/worker.py", line 110, in _worker
    self._throttle(func=self._process, min_secs=throttle_secs)
  File "/freqtrade/freqtrade/worker.py", line 123, in _throttle
    result = func(*args, **kwargs)
  File "/freqtrade/freqtrade/worker.py", line 133, in _process
    state_changed = self.freqtrade.process()
  File "/freqtrade/freqtrade/freqtradebot.py", line 133, in process
    self.check_handle_timedout()
  File "/freqtrade/freqtrade/freqtradebot.py", line 724, in check_handle_timedout
    order = self.exchange.get_order(trade.open_order_id, trade.pair)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 51, in wrapper
    return f(*args, **kwargs)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 634, in get_order
    f'Tried to get an invalid order (id: {order_id}). Message: {e}')
freqtrade.InvalidOrderException: Tried to get an invalid order (id: 349333925). Message: binance {"code":-2013,"msg":"Order does not exist."}
2019-07-15 00:30:40,651 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2019-07-15 00:30:40,859 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
```

**Comment by xmatthias** [comment]
We will require the additional information we have in the issue template - mainly the branch, last commit and CCXT version (the python version is visible from the logs).

  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Branch: Master | Develop
  * Last Commit ID: _____ (`git log --format="%H" -n 1`)

**Comment by Ish2k2** [comment]
CCXT version: 1.18.551 (pip freeze | grep ccxt)
    Branch: Master
    Last Commit ID: d1a5bf40bb60ee53050700a8c5486f5fe5c3f92b (git log --format="%H" -n 1)

**Comment by Ish2k2** [comment]
I just wanted to update that I've reinstalled a fresh freqtrade on a new instance and am having no issues for the past 3 days. I cloned the above copy from my pc which I must've messed with the code somewhere. I think we can close and reopen this issue if I get the error again.

**Comment by xmatthias** [comment]
ok, thanks for reporting back :+1:
