### ISSUE TITLE
parse_timeframe() missing 1 required positional argument: 'timeframe' even with requirments-dev.txt installed

### ISSUE THREAD

**Issue by Gabri** [freqtrade/freqtrade#2026]
* Python Version: Python 3.7.3
  * CCXT version: ccxt==1.18.240
  * Branch: Develop
  * Last Commit ID: 5144e98a828480f624f197350b1d9f6eec47e2f6

Same problem as reported in the issue #1748 but **even installing requirments-dev.txt it doesn't resolve**

```
2019-07-16 14:01:29,847 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/mnt/workspace/ws/git/cry/freqtrade/freqtrade/main.py", line 49, in main
    worker.run()
  File "/mnt/workspace/ws/git/cry/freqtrade/freqtrade/worker.py", line 72, in run
    state = self._worker(old_state=state)
  File "/mnt/workspace/ws/git/cry/freqtrade/freqtrade/worker.py", line 110, in _worker
    self._throttle(func=self._process, min_secs=throttle_secs)
  File "/mnt/workspace/ws/git/cry/freqtrade/freqtrade/worker.py", line 123, in _throttle
    result = func(*args, **kwargs)
  File "/mnt/workspace/ws/git/cry/freqtrade/freqtrade/worker.py", line 133, in _process
    state_changed = self.freqtrade.process()
  File "/mnt/workspace/ws/git/cry/freqtrade/freqtrade/freqtradebot.py", line 131, in process
    self.strategy.informative_pairs())
  File "/mnt/workspace/ws/git/cry/freqtrade/freqtrade/data/dataprovider.py", line 35, in refresh
    self._exchange.refresh_latest_ohlcv(pairlist)
  File "/mnt/workspace/ws/git/cry/freqtrade/freqtrade/exchange/exchange.py", line 610, in refresh_latest_ohlcv
    drop_incomplete=self._ohlcv_partial_candle)
  File "/mnt/workspace/ws/git/cry/freqtrade/freqtrade/data/converter.py", line 55, in parse_ticker_dataframe
    return ohlcv_fill_up_missing_data(frame, ticker_interval, pair)
  File "/mnt/workspace/ws/git/cry/freqtrade/freqtrade/data/converter.py", line 75, in ohlcv_fill_up_missing_data
    ticker_minutes = timeframe_to_minutes(ticker_interval)
  File "/mnt/workspace/ws/git/cry/freqtrade/freqtrade/exchange/exchange.py", line 779, in timeframe_to_minutes
    return ccxt.Exchange.parse_timeframe(ticker_interval) // 60
TypeError: parse_timeframe() missing 1 required positional argument: 'timeframe'
2019-07-16 14:01:29,849 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2019-07-16 14:01:29,849 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2019-07-16 14:01:29,849 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
```

Thanks

P.s.: which branch is suggested to use? Is develop considered unstable and not for production?

**Comment by hroff-1902** [comment]
Pls paste output of setup -I or pip3.

As I said in #1748, ccxt has changed interface in 1.18.431, you are using 1.18.240. 

Ip3 install -r requirements.txt should install you all actual versions of dependencies.

**Comment by Gabri** [comment]
Hi,
I paste some extracts from `./setup.sh -i`:
```
-------------------------
Updating your virtual env
-------------------------
pip install in-progress. Please wait...
Collecting pip
  Using cached https://files.pythonhosted.org/packages/5c/e0/be401c003291b56efc55aeba6a80ab790d3d4cece2778288d65323009420/pip-19.1.1-py2.py3-none-any.whl
Collecting numpy
  Using cached https://files.pythonhosted.org/packages/fc/d1/45be1144b03b6b1e24f9a924f23f66b4ad030d834ad31fb9e5581bd328af/numpy-1.16.4-cp37-cp37m-manylinux1_x86_64.whl
Installing collected packages: pip, numpy
  Found existing installation: pip 19.0.3
    Uninstalling pip-19.0.3:
      Successfully uninstalled pip-19.0.3
Successfully installed numpy-1.16.4 pip-19.1.1
Collecting ccxt==1.18.860 (from -r requirements-common.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/45/00/c19fced5e146a0b53e3340074d07089c30276f33058e0dce11a44e8922f5/ccxt-1.18.860-py2.py3-none-any.whl
```
and 
```
Successfully installed Jinja2-2.10.1 MarkupSafe-1.1.1 SQLAlchemy-1.3.5 TA-Lib-0.4.17 Werkzeug-0.15.4 aiodns-1.1.1 aiohttp-3.5.4 arrow-0.14.2 asn1crypto-0.24.0 async-timeout-3.0.1 attrs-19.1.0 cachetools-3.1.1 ccxt-1.18.860 certifi-2019.6.16 cffi-1.12.3 chardet-3.0.4 click-7.0 coinmarketcap-5.0.3 cryptography-2.7 filelock-3.0.12 flask-1.0.3 future-0.17.1 idna-2.8 itsdangerous-1.1.0 joblib-0.13.2 jsonschema-3.0.1 multidict-4.5.2 pandas-0.24.2 py-find-1st-1.1.3 pycares-3.0.0 pycparser-2.19 pyrsistent-0.15.3 python-dateutil-2.8.0 python-rapidjson-0.7.2 python-telegram-bot-11.1.0 pytz-2019.1 requests-2.22.0 requests-cache-0.5.0 scikit-learn-0.21.2 scikit-optimize-0.5.2 scipy-1.3.0 sdnotify-0.3.2 six-1.12.0 tabulate-0.8.3 urllib3-1.24.2 wrapt-1.11.2 yarl-1.1.0
Do you want to install dependencies for dev [y/N]? y
Requirement already up-to-date: ccxt==1.18.860 in ./.env/lib/python3.7/site-packages (from -r requirements-common.txt (line 3)) (1.18.860)

```
But when i run `pip freeze | grep ccxt` I get: `ccxt==1.18.240`
With this (I don't know if it could be helpful) `ls -la ./.env/lib/python3.7/site-packages/` I get (excluding other entries):
```
drwxr-xr-x   5 gabri gabri    4096 lug 17 13:59 ccxt
drwxr-xr-x   2 gabri gabri    4096 lug 17 13:59 ccxt-1.18.860.dist-info
```

Running `python3 -m pip install -r requirements.txt` I get a similar output (filtered):
`Requirement already satisfied: ccxt==1.18.860 in /usr/lib/python3.7/site-packages (from -r requirements-common.txt (line 3)) (1.18.860)`

Sorry, quite newbie in python world

**Comment by hroff-1902** [comment]
Use pip3, not pip

**Comment by Gabri** [comment]
```
gabri@manja  ~/ws/git/cry/freqtrade   develop  pip3 freeze | grep ccxt
ccxt==1.18.240
```

**Comment by xmatthias** [comment]
try `which pip3` - it should return a path to .venv/... .

i think you don't have the virtual environment loaded. try `source .env/bin/activate` and then run `pip3 freeze | grep ccxt again`

**Comment by Gabri** [comment]
yes.. now it returns:
`/usr/bin/pip3`
It works loading the virtual environment. Now I get the right ccxt version.
So, stupid question, I need to load the virtual env before running freqtrade, isn't it?

Thank you very much!

**Comment by hroff-1902** [comment]
yes, you need because it contains all the dependencies installed before

**Comment by xmatthias** [comment]
Yes, it decouples your "real" environment from the freqtrade one.

using virtual environments is common with Python to avoid dependency-problems - where an update to one program breaks something else on your system because of a broken dependency version.

**Comment by Gabri** [comment]
Thank you very much ..I'm still newbie in Phyton
