### ISSUE TITLE
ImportError: libta_lib.so.0 - unable to install

### ISSUE THREAD

**Issue by zero-direwolf** [freqtrade/freqtrade#2032]
## Step 1: Have you search for this issue before posting it?
yes, similar to #1813, #1676,#1684
but i am unable to start freqtrade

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/freqtrade/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

  * Python Version: 3.6.8
  * CCXT version:  1.18.860 
  * Branch: Develop
  * Last Commit ID: e126c55a5a3505552a56f59690c37af5ac2d59b8
  * os: ubuntu-bionic-18.04-amd64-server-20190627.1
  
## Step 3: Describe the problem:
Unable to launch freqtrade

*Explain the problem you have encountered*
I am trying to install it on AWS instance, and I Unable to launch freqtrade, 
I have tried it on many instances, encountering same issue

### Steps to reproduce:

  1. git clone https://github.com/freqtrade/freqtrade.git
  2. cd freqtrade
  3. ./setup.sh --install
  4. source .env/bin/activate
  5. freqtrade (error)
  
### Observed Results:

  * What happened?
    when i try to start freqtrade, i encounter Importerror, i am not sure what step i am missing, since the same procedure worked earlier
  * What did you expect to happen?
  freqtrade to start
### Relevant code exceptions or logs:

  ```
>>freqtrade

Traceback (most recent call last):
  File "/home/ubuntu/freqtrade/.env/bin/freqtrade", line 11, in <module>
    load_entry_point('freqtrade', 'console_scripts', 'freqtrade')()
  File "/home/ubuntu/freqtrade/.env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/ubuntu/freqtrade/.env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/home/ubuntu/freqtrade/.env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/home/ubuntu/freqtrade/.env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/ubuntu/freqtrade/freqtrade/main.py", line 19, in <module>
    from freqtrade.worker import Worker
  File "/home/ubuntu/freqtrade/freqtrade/worker.py", line 14, in <module>
    from freqtrade.freqtradebot import FreqtradeBot
  File "/home/ubuntu/freqtrade/freqtrade/freqtradebot.py", line 18, in <module>
    from freqtrade.edge import Edge
  File "/home/ubuntu/freqtrade/freqtrade/edge/__init__.py", line 15, in <module>
    from freqtrade.strategy.interface import SellType
  File "/home/ubuntu/freqtrade/freqtrade/strategy/__init__.py", line 7, in <module>
    from freqtrade.strategy.default_strategy import DefaultStrategy  # noqa: F401
  File "/home/ubuntu/freqtrade/freqtrade/strategy/default_strategy.py", line 3, in <module>
    import talib.abstract as ta
  File "/home/ubuntu/freqtrade/.env/lib/python3.6/site-packages/talib/__init__.py", line 43, in <module>
    from ._ta_lib import (
ImportError: libta_lib.so.0: cannot open shared object file: No such file or directory

  ```

**Comment by zero-direwolf** [comment]
fixed
1. go to home dir
2. nano ~/.profile
3. export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
4. save and restart
