### ISSUE TITLE
KeyError: 'stopPrice'

### ISSUE THREAD

**Issue by Prossi79** [freqtrade/freqtrade#2106]
## Step 1: Have you search for this issue before posting it?

yes, nothing found

## Step 2: Describe your environment

Python Version: Python 3.7.3
CCXT version: ccxt==1.18.992
Branch: Develop
Last Commit ID: eeecdd4e5a5f70ba2e7943bf3c6aaf4b5742e5b3

  
## Step 3: Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

  1. config file - stoploss on exchange - true
  2. FT started normally
  3. buy signal found -> see log below
  
### Observed Results:

  * Telegram message "Process Died"
  

### Relevant code exceptions or logs:

  ```
2019-08-06 22:44:55,366 - freqtrade.freqtradebot - INFO - Found no buy signals for whitelisted currencies. Trying again..
2019-08-06 22:44:59,196 - freqtrade.freqtradebot - INFO - Found no buy signals for whitelisted currencies. Trying again..
2019-08-06 22:45:05,099 - freqtrade.freqtradebot - INFO - Buy signal found: about create a new trade with stake_amount: 980 ...
2019-08-06 22:45:05,099 - freqtrade.freqtradebot - INFO - Using Last Ask / Last Price
2019-08-06 22:45:05,400 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': buy, 'exchange': 'Binance', 'pair': 'BTC/USDT', 'limit': 11642.115000000002, 'order_type': 'limit', 'stake_amount': 980, 'stake_currency': 'USDT', 'fiat_currency': 'USD'}
2019-08-06 22:45:05,928 - freqtrade.wallets - INFO - Wallets synced.
/root/freqtrade/.env/lib/python3.7/site-packages/arrow/factory.py:201: ArrowParseWarning: The .get() parsing method without a format string will parse more strictly in version 0.15.0.See https://github.com/crsmithdev/arrow/issues/612 for more details.
  ArrowParseWarning,
2019-08-06 22:45:05,986 - freqtrade.wallets - INFO - Wallets synced.
2019-08-06 22:45:07,044 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=1, pair=BTC/USDT, amount=0.08417714, open_rate=11642.11500000, open_since=just now)
2019-08-06 22:45:07,045 - freqtrade.freqtradebot - INFO - Applying fee on amount for Trade(id=1, pair=BTC/USDT, amount=0.08417714, open_rate=11642.11500000, open_since=just now) failed: myTrade-Dict empty found
2019-08-06 22:45:07,046 - freqtrade.persistence - INFO - Updating trade (id=1) ...
2019-08-06 22:45:07,046 - freqtrade.persistence - INFO - LIMIT_BUY has been fulfilled for Trade(id=1, pair=BTC/USDT, amount=0.08417714, open_rate=11642.11500000, open_since=just now).
2019-08-06 22:45:07,632 - freqtrade.freqtradebot - INFO - Found no buy signals for whitelisted currencies. Trying again..
2019-08-06 22:45:11,045 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/root/freqtrade/freqtrade/main.py", line 49, in main
    worker.run()
  File "/root/freqtrade/freqtrade/worker.py", line 72, in run
    state = self._worker(old_state=state)
  File "/root/freqtrade/freqtrade/worker.py", line 110, in _worker
    self._throttle(func=self._process, min_secs=throttle_secs)
  File "/root/freqtrade/freqtrade/worker.py", line 123, in _throttle
    result = func(*args, **kwargs)
  File "/root/freqtrade/freqtrade/worker.py", line 134, in _process
    state_changed = self.freqtrade.process()
  File "/root/freqtrade/freqtrade/freqtradebot.py", line 135, in process
    state_changed |= self.process_maybe_execute_sell(trade)
  File "/root/freqtrade/freqtrade/freqtradebot.py", line 451, in process_maybe_execute_sell
    result = self.handle_stoploss_on_exchange(trade)
  File "/root/freqtrade/freqtrade/freqtradebot.py", line 683, in handle_stoploss_on_exchange
    self.handle_trailing_stoploss_on_exchange(trade, stoploss_order)
  File "/root/freqtrade/freqtrade/freqtradebot.py", line 696, in handle_trailing_stoploss_on_exchange
    if trade.stop_loss > float(order['info']['stopPrice']):
KeyError: 'stopPrice'
2019-08-06 22:45:11,099 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2019-08-06 22:45:11,143 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2019-08-06 22:45:11,143 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
(.env) (base) root@vmanager6003:~/freqtrade# 

  ```

**Comment by xmatthias** [comment]
how does your `order_types` configuration look like?

**Comment by Prossi79** [comment]
order-types table:

    "order_types": {
    "buy": "limit",
    "sell": "limit",
    "stoploss": "limit",
    "stoploss_on_exchange": true,
    "stoploss_on_exchange_interval": 60
    },


DB I did not re-use, I was deleting the old one before starting the bot


    "dry_run": true,
    "db_url": "sqlite:///strategyA_test.sqlite",

Yesterday I restarted the bot after the crash without stoploss on exchange so far he completed 2 dry trades without crashing

**Comment by xmatthias** [comment]
Your comments don't line up ... you say you had stoploss on exchange on (in the first comment) - but now you show "dry_run" to be `true` ... ? 

if it's dry-run, then stoploss cannot be on the exchange...

**Comment by Prossi79** [comment]
oh okay - thats the issue? "stoploss on exchange" is not working in dry-run?

I was assuming that somehow FT would ignore that setting being in dry-run and would automatically work with off exchange stop loss

**Comment by hroff-1902** [comment]
> oh okay - thats the issue? "stoploss on exchange" is not working in dry-run?

It cannot work by definition, because that's stoploss which is executed on the exchange and freqtrade in the dry-run mode does not create any orders on exchange...

> I was assuming that somehow FT would ignore that setting being in dry-run and would automatically work with off exchange stop loss

This may have sense, as a proposal for an enhancement. If not, a check for graceful exit should be added when we load/verify configuration...

@xmatthias, what do you think? (I'm not familiar with this part of the codebase yet)

**Comment by xmatthias** [comment]
i'll need to check - i know we disable it for backtesting - and i thought we do for dry-run too... (simply overiding the value of `order_types['stoploss_on_exhange']`)

**Comment by xmatthias** [comment]
well apparently we don't - it's implemented for backtesting, but not for dry-run ... :-1:
