### ISSUE TITLE
Trailing stop cant set order because it would trigger immediately

### ISSUE THREAD

**Issue by Dante2333** [freqtrade/freqtrade#2171]
## Step 1: Have you search for this issue before posting it?

Yes

## Step 2: Describe your environment

  * Operating system: Ubuntu 19.04
  * Python Version: 3.7
  * CCXT version: latest
  * Branch: Master 
  * Last Commit ID: 2018.7 
  
## Step 3: Describe the problem:

The trailing stop wont be set even though it wont trigger automatically; 

### Steps to reproduce:

  1. Set trailing stop to offset at 0.2 and to set stoploss at 0.00
  2. run and wait
  
``` 42     # trailing stoploss
 43     trailing_stop = True
 44     trailing_stop_positive = 0
 45     trailing_stop_positive_offset = 0.2
 46     trailing_only_offset_is_reached = True
```
### Observed Results:

  * What happened? bot wont set the stoploss on exchange
  * What did you expect to happen? bot to set the stoploss on exchange and trail it up

### Relevant code exceptions or logs:

  ```
 2019-08-22 17:03:04,000 - freqtrade.freqtradebot - INFO - Found no buy signals for whitelisted currencies. Trying again...
2019-08-22 17:03:07,488 - freqtrade.freqtradebot - WARNING - Stoploss order was cancelled, but unable to recreate one: Could not create stop_loss_limit sell order on market ETC/USDT.Tried to sell amount 32.28 at rate 7.4081.Message: binance Order would trigger immediately.
2019-08-22 17:03:07,488 - freqtrade.freqtradebot - INFO - Trailing stoploss: cancelling current stoploss on exchange (id:{71933263})in order to add another one ...
2019-08-22 17:03:07,988 - freqtrade.freqtradebot - ERROR - Could not cancel stoploss order 71933263 for pair ETC/USDT
Traceback (most recent call last):
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 509, in fetch
    response.raise_for_status()
  File "/home/dante/.local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order?timestamp=1566493387967&recvWindow=5000&symbol=ETCUSDT&orderId=71933263&signature=e5b9e511ce050cc86f7ca2b3a5e2b3bd4e362262a700e33de09eb4eab1b00eff

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dante/freqtrade/freqtrade/exchange/exchange.py", line 686, in cancel_order
    return self._api.cancel_order(order_id, pair)
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/binance.py", line 778, in cancel_order
    }, params))
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 404, in inner
    return entry(_self, **inner_kwargs)
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/binance.py", line 1210, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 429, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 521, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, headers, http_response, json_response)
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/binance.py", line 1203, in handle_errors
    raise exceptions[error](self.id + ' ' + body)
ccxt.base.errors.OrderNotFound: binance {"code":-2011,"msg":"Unknown order sent."}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dante/freqtrade/freqtrade/freqtradebot.py", line 716, in handle_trailing_stoploss_on_exchange
    self.exchange.cancel_order(order['id'], trade.pair)
  File "/home/dante/freqtrade/freqtrade/exchange/exchange.py", line 57, in wrapper
    return f(*args, **kwargs)
  File "/home/dante/freqtrade/freqtrade/exchange/exchange.py", line 689, in cancel_order
    f'Could not cancel order. Message: {e}') from e
freqtrade.InvalidOrderException: Could not cancel order. Message: binance {"code":-2011,"msg":"Unknown order sent."}
2019-08-22 17:03:08,489 - freqtrade.freqtradebot - ERROR - Could create trailing stoploss order for pair ETC/USDT.
Traceback (most recent call last):
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 509, in fetch
    response.raise_for_status()
  File "/home/dante/.local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dante/freqtrade/freqtrade/exchange/exchange.py", line 406, in create_order
    amount, rate, params)
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/binance.py", line 694, in create_order
    response = getattr(self, method)(self.extend(order, params))
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 404, in inner
    return entry(_self, **inner_kwargs)
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/binance.py", line 1210, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 429, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 521, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, headers, http_response, json_response)
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/binance.py", line 1193, in handle_errors
    raise ExceptionClass(self.id + ' ' + message)
ccxt.base.errors.InvalidOrder: binance Order would trigger immediately.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dante/freqtrade/freqtrade/freqtradebot.py", line 725, in handle_trailing_stoploss_on_exchange
    stop_price=trade.stop_loss, rate=trade.stop_loss * 0.99
  File "/home/dante/freqtrade/freqtrade/exchange/exchange.py", line 473, in stoploss_limit
    order = self.create_order(pair, ordertype, 'sell', amount, rate, params)
  File "/home/dante/freqtrade/freqtrade/exchange/exchange.py", line 417, in create_order
    f'Message: {e}') from e
freqtrade.DependencyException: Could not create stop_loss_limit sell order on market ETC/USDT.Tried to sell amount 32.28 at rate 7.4081.Message: binance Order would trigger immediately.
2019-08-22 17:03:09,009 - freqtrade.freqtradebot - INFO - Found no buy signals for whitelisted currencies. Trying again...
2019-08-22 17:03:12,477 - freqtrade.freqtradebot - WARNING - Stoploss order was cancelled, but unable to recreate one: Could not create stop_loss_limit sell order on market ETC/USDT.Tried to sell amount 32.28 at rate 7.4081.Message: binance Order would trigger immediately.
2019-08-22 17:03:12,478 - freqtrade.freqtradebot - INFO - Trailing stoploss: cancelling current stoploss on exchange (id:{71933263})in order to add another one ...
2019-08-22 17:03:12,985 - freqtrade.freqtradebot - ERROR - Could not cancel stoploss order 71933263 for pair ETC/USDT
Traceback (most recent call last):
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 509, in fetch
    response.raise_for_status()
  File "/home/dante/.local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order?timestamp=1566493392964&recvWindow=5000&symbol=ETCUSDT&orderId=71933263&signature=f80bc982e68cc7c452bd0574aa2505bf87755dc67621c8876603f314501881e0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dante/freqtrade/freqtrade/exchange/exchange.py", line 686, in cancel_order
    return self._api.cancel_order(order_id, pair)
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/binance.py", line 778, in cancel_order
    }, params))
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 404, in inner
    return entry(_self, **inner_kwargs)
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/binance.py", line 1210, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 429, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 521, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, headers, http_response, json_response)
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/binance.py", line 1203, in handle_errors
    raise exceptions[error](self.id + ' ' + body)
ccxt.base.errors.OrderNotFound: binance {"code":-2011,"msg":"Unknown order sent."}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dante/freqtrade/freqtrade/freqtradebot.py", line 716, in handle_trailing_stoploss_on_exchange
    self.exchange.cancel_order(order['id'], trade.pair)
  File "/home/dante/freqtrade/freqtrade/exchange/exchange.py", line 57, in wrapper
    return f(*args, **kwargs)
  File "/home/dante/freqtrade/freqtrade/exchange/exchange.py", line 689, in cancel_order
    f'Could not cancel order. Message: {e}') from e
freqtrade.InvalidOrderException: Could not cancel order. Message: binance {"code":-2011,"msg":"Unknown order sent."}
2019-08-22 17:03:13,484 - freqtrade.freqtradebot - ERROR - Could create trailing stoploss order for pair ETC/USDT.
Traceback (most recent call last):
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 509, in fetch
    response.raise_for_status()
  File "/home/dante/.local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dante/freqtrade/freqtrade/exchange/exchange.py", line 406, in create_order
    amount, rate, params)
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/binance.py", line 694, in create_order
    response = getattr(self, method)(self.extend(order, params))
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 404, in inner
    return entry(_self, **inner_kwargs)
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/binance.py", line 1210, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 429, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 521, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, headers, http_response, json_response)
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/binance.py", line 1193, in handle_errors
    raise ExceptionClass(self.id + ' ' + message)
ccxt.base.errors.InvalidOrder: binance Order would trigger immediately.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dante/freqtrade/freqtrade/freqtradebot.py", line 725, in handle_trailing_stoploss_on_exchange
    stop_price=trade.stop_loss, rate=trade.stop_loss * 0.99
  File "/home/dante/freqtrade/freqtrade/exchange/exchange.py", line 473, in stoploss_limit
    order = self.create_order(pair, ordertype, 'sell', amount, rate, params)
  File "/home/dante/freqtrade/freqtrade/exchange/exchange.py", line 417, in create_order
    f'Message: {e}') from e
freqtrade.DependencyException: Could not create stop_loss_limit sell order on market ETC/USDT.Tried to sell amount 32.28 at rate 7.4081.Message: binance Order would trigger immediately.
2019-08-22 17:03:14,005 - freqtrade.freqtradebot - INFO - Found no buy signals for whitelisted currencies. Trying again...
2019-08-22 17:03:17,484 - freqtrade.freqtradebot - WARNING - Stoploss order was cancelled, but unable to recreate one: Could not create stop_loss_limit sell order on market ETC/USDT.Tried to sell amount 32.28 at rate 7.4081.Message: binance Order would trigger immediately.
2019-08-22 17:03:17,484 - freqtrade.freqtradebot - INFO - Trailing stoploss: cancelling current stoploss on exchange (id:{71933263})in order to add another one ...
2019-08-22 17:03:17,986 - freqtrade.freqtradebot - ERROR - Could not cancel stoploss order 71933263 for pair ETC/USDT
Traceback (most recent call last):
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 509, in fetch
    response.raise_for_status()
  File "/home/dante/.local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order?timestamp=1566493397966&recvWindow=5000&symbol=ETCUSDT&orderId=71933263&signature=79ee74942681a53da3694d4b085b97124888f7eac5f73a6a447f0fb10a556a74

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dante/freqtrade/freqtrade/exchange/exchange.py", line 686, in cancel_order
    return self._api.cancel_order(order_id, pair)
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/binance.py", line 778, in cancel_order
    }, params))
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 404, in inner
    return entry(_self, **inner_kwargs)
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/binance.py", line 1210, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 429, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 521, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, headers, http_response, json_response)
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/binance.py", line 1203, in handle_errors
    raise exceptions[error](self.id + ' ' + body)
ccxt.base.errors.OrderNotFound: binance {"code":-2011,"msg":"Unknown order sent."}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dante/freqtrade/freqtrade/freqtradebot.py", line 716, in handle_trailing_stoploss_on_exchange
    self.exchange.cancel_order(order['id'], trade.pair)
  File "/home/dante/freqtrade/freqtrade/exchange/exchange.py", line 57, in wrapper
    return f(*args, **kwargs)
  File "/home/dante/freqtrade/freqtrade/exchange/exchange.py", line 689, in cancel_order
    f'Could not cancel order. Message: {e}') from e
freqtrade.InvalidOrderException: Could not cancel order. Message: binance {"code":-2011,"msg":"Unknown order sent."}
2019-08-22 17:03:18,484 - freqtrade.freqtradebot - ERROR - Could create trailing stoploss order for pair ETC/USDT.
Traceback (most recent call last):
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 509, in fetch
    response.raise_for_status()
  File "/home/dante/.local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dante/freqtrade/freqtrade/exchange/exchange.py", line 406, in create_order
    amount, rate, params)
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/binance.py", line 694, in create_order
    response = getattr(self, method)(self.extend(order, params))
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 404, in inner
    return entry(_self, **inner_kwargs)
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/binance.py", line 1210, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 429, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 521, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, headers, http_response, json_response)
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/binance.py", line 1193, in handle_errors
    raise ExceptionClass(self.id + ' ' + message)
ccxt.base.errors.InvalidOrder: binance Order would trigger immediately.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dante/freqtrade/freqtrade/freqtradebot.py", line 725, in handle_trailing_stoploss_on_exchange
    stop_price=trade.stop_loss, rate=trade.stop_loss * 0.99
  File "/home/dante/freqtrade/freqtrade/exchange/exchange.py", line 473, in stoploss_limit
    order = self.create_order(pair, ordertype, 'sell', amount, rate, params)
  File "/home/dante/freqtrade/freqtrade/exchange/exchange.py", line 417, in create_order
    f'Message: {e}') from e
freqtrade.DependencyException: Could not create stop_loss_limit sell order on market ETC/USDT.Tried to sell amount 32.28 at rate 7.4081.Message: binance Order would trigger immediately.
2019-08-22 17:03:19,001 - freqtrade.freqtradebot - INFO - Found no buy signals for whitelisted currencies. Trying again...
2019-08-22 17:03:22,491 - freqtrade.freqtradebot - WARNING - Stoploss order was cancelled, but unable to recreate one: Could not create stop_loss_limit sell order on market ETC/USDT.Tried to sell amount 32.28 at rate 7.4081.Message: binance Order would trigger immediately.
2019-08-22 17:03:22,492 - freqtrade.freqtradebot - INFO - Trailing stoploss: cancelling current stoploss on exchange (id:{71933263})in order to add another one ...
2019-08-22 17:03:22,985 - freqtrade.freqtradebot - ERROR - Could not cancel stoploss order 71933263 for pair ETC/USDT
Traceback (most recent call last):
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 509, in fetch
    response.raise_for_status()
  File "/home/dante/.local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order?timestamp=1566493402968&recvWindow=5000&symbol=ETCUSDT&orderId=71933263&signature=945b38faf9271a0dfd8b40f05a56306e36924c64af47a8fb8f4a0cefb95bd9a6

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dante/freqtrade/freqtrade/exchange/exchange.py", line 686, in cancel_order
    return self._api.cancel_order(order_id, pair)
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/binance.py", line 778, in cancel_order
    }, params))
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 404, in inner
    return entry(_self, **inner_kwargs)
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/binance.py", line 1210, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 429, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 521, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, headers, http_response, json_response)
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/binance.py", line 1203, in handle_errors
    raise exceptions[error](self.id + ' ' + body)
ccxt.base.errors.OrderNotFound: binance {"code":-2011,"msg":"Unknown order sent."}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dante/freqtrade/freqtrade/freqtradebot.py", line 716, in handle_trailing_stoploss_on_exchange
    self.exchange.cancel_order(order['id'], trade.pair)
  File "/home/dante/freqtrade/freqtrade/exchange/exchange.py", line 57, in wrapper
    return f(*args, **kwargs)
  File "/home/dante/freqtrade/freqtrade/exchange/exchange.py", line 689, in cancel_order
    f'Could not cancel order. Message: {e}') from e
freqtrade.InvalidOrderException: Could not cancel order. Message: binance {"code":-2011,"msg":"Unknown order sent."}
2019-08-22 17:03:23,493 - freqtrade.freqtradebot - ERROR - Could create trailing stoploss order for pair ETC/USDT.
Traceback (most recent call last):
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 509, in fetch
    response.raise_for_status()
  File "/home/dante/.local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dante/freqtrade/freqtrade/exchange/exchange.py", line 406, in create_order
    amount, rate, params)
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/binance.py", line 694, in create_order
    response = getattr(self, method)(self.extend(order, params))
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 404, in inner
    return entry(_self, **inner_kwargs)
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/binance.py", line 1210, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 429, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 521, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, headers, http_response, json_response)
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/binance.py", line 1193, in handle_errors
    raise ExceptionClass(self.id + ' ' + message)
ccxt.base.errors.InvalidOrder: binance Order would trigger immediately.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dante/freqtrade/freqtrade/freqtradebot.py", line 725, in handle_trailing_stoploss_on_exchange
    stop_price=trade.stop_loss, rate=trade.stop_loss * 0.99
  File "/home/dante/freqtrade/freqtrade/exchange/exchange.py", line 473, in stoploss_limit
    order = self.create_order(pair, ordertype, 'sell', amount, rate, params)
  File "/home/dante/freqtrade/freqtrade/exchange/exchange.py", line 417, in create_order
    f'Message: {e}') from e
freqtrade.DependencyException: Could not create stop_loss_limit sell order on market ETC/USDT.Tried to sell amount 32.28 at rate 7.4081.Message: binance Order would trigger immediately.
2019-08-22 17:03:24,006 - freqtrade.freqtradebot - INFO - Found no buy signals for whitelisted currencies. Trying again...

  ```

**Comment by xmatthias** [comment]
`ccxt.base.errors.InvalidOrder: binance Order would trigger immediately.`
`freqtrade.DependencyException: Could not create stop_loss_limit sell order on market ETC/USDT.Tried to sell amount 32.28 at rate 7.4081.Message: binance Order would trigger immediately.
20`

binance clearly thinks that it would trigger immediately, and it's right after looking at the values you provided.

You're setting `trailing_stop_positive = 0`, and `trailing_stop_positive_offset = 0.2`. 
This means that once the trade has a 20% gain  (which did happen today for this pair) it sets the stoploss to the `current price - trailing_stop_positive%`.

since you configure it to 0 - it sets the stoploss to the current price - which will cause it to trigger immediately.

You should configure this differently - trailing stoploss should protect you from losses you gained, but you've configured it to act similar to ROI (at 20%), which will not work since it uses different order-types.

What you want for this case is set ROI: `{"0": 0.2}` - which will sell the trade at 20% too - but using a "regular" sell order, not a stoploss order, which binance rejects.

**Comment by Dante2333** [comment]
Thanks.

**Comment by xmatthias** [comment]
@hroff-1902 what you mention is tracked as #1557.

I'll close this as the original problem / question was answered. feel free to reopen if you have further questions
