### ISSUE TITLE
dry_run + webhook results in Fatal exception

### ISSUE THREAD

**Issue by DomenikPasquale** [freqtrade/freqtrade#2200]
## Step 1: Have you search for this issue before posting it?
yes

## Step 2: Describe your environment

  * Operating system: ubuntu 16.04
  * Python Version: Python 3.6.8
  * CCXT version: ccxt==1.18.1043
  * Branch: freqtrade 2019.7-dev
  * Last Commit ID: 161db08745baad1155b790ad4b1380dc2c53e556
  
## Step 3: Describe the problem:

* running webhook w dry-run:true dies upon start with fatal exception.

### Steps to reproduce:
webhook.enabled: true (no error when false)
dry-run: true (false went untested)
telegram.enabled: (confirmed error present with true|false)
  
### Observed Results:
* What happened?
fatal exception.

* What did you expect to happen?
Endless account growth of intangible virtual currency.  Simulated of course. 

### Steps to resolve(ish)
rpc/webhook.py:~39
```
""" Send a message to telegram channel """
try:
if msg['type'] == RPCMessageType.BUY_NOTIFICATION:
	valuedict = self._config['webhook'].get('webhookbuy', None)
elif msg['type'] == RPCMessageType.SELL_NOTIFICATION:
	valuedict = self._config['webhook'].get('webhooksell', None)
elif msg['type'] == RPCMessageType.STATUS_NOTIFICATION:
	valuedict = self._config['webhook'].get('webhookstatus', None)
++ elif msg['type'] == RPCMessageType.WARNING_NOTIFICATION:
++   valuedict = self._config['webhook'].get('webhookstatus', None)
++ elif msg['type'] == RPCMessageType.CUSTOM_NOTIFICATION:
++   valuedict = self._config['webhook'].get('webhookstatus', None)
else:
	raise NotImplementedError('Unknown message type: {}'.format(msg['type']))
if not valuedict:
	logger.info("Message type %s not configured for webhooks", msg['type'])
	return
```

### Relevant code exceptions or logs:
```
source .env/bin/activate; freqtrade -c config-Strategy110.json -s Strategy110 --strategy-path /home/freqtrade/freqtrade/user_data/strategies/
2019-08-29 22:59:24,229 - freqtrade.loggers - INFO - Verbosity set to 0
2019-08-29 22:59:24,230 - freqtrade.configuration.configuration - INFO - Using additional Strategy lookup path: /home/freqtrade/freqtrade/user_data/strategies/
2019-08-29 22:59:24,230 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2019-08-29 22:59:24,230 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:///strategy1110.dryrun.sqlite"
2019-08-29 22:59:24,230 - freqtrade.configuration.configuration - WARNING - `forcebuy` RPC message enabled.
2019-08-29 22:59:24,230 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2019-08-29 22:59:24,230 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2019-08-29 22:59:24,230 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 2 ...
2019-08-29 22:59:24,230 - freqtrade.configuration.configuration - INFO - Using data directory: user_data/data/binance ...
2019-08-29 22:59:24,230 - freqtrade.configuration.configuration - INFO - Runmode set to RunMode.DRY_RUN.
2019-08-29 22:59:24,230 - freqtrade.freqtradebot - INFO - Starting freqtrade 2019.7-dev
2019-08-29 22:59:24,234 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy Strategy110 from '/home/freqtrade/freqtrade/user_data/strategies/Strategy110.py'...
-- (redaction) --
2019-08-29 22:59:24,236 - freqtrade.rpc.rpc_manager - INFO - Enabling rpc.telegram ...
2019-08-29 22:59:24,273 - freqtrade.rpc.telegram - INFO - rpc.telegram is listening for following commands: [['status'], ['profit'], ['balance'], ['start'], ['stop'], ['forcesell'], ['forcebuy'], ['performance'], ['daily'], ['count'], ['reload_conf'], ['stopbuy'], ['whitelist'], ['blacklist'], ['edge'], ['help'], ['version']]
2019-08-29 22:59:24,284 - freqtrade.rpc.rpc_manager - INFO - Enabling rpc.webhook ...
2019-08-29 22:59:24,285 - freqtrade.rpc.rpc_manager - INFO - Enabling rpc.api_server
2019-08-29 22:59:24,325 - freqtrade.rpc.api_server - INFO - Starting HTTP Server at 127.0.0.1:10110
2019-08-29 22:59:24,325 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2019-08-29 22:59:24,326 - freqtrade.rpc.api_server - INFO - Starting Local Rest Server.
2019-08-29 22:59:24,326 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2019-08-29 22:59:24,327 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 200}
2019-08-29 22:59:24,334 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2019-08-29 22:59:24,738 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2019-08-29 22:59:24,738 - freqtrade.wallets - INFO - Wallets synced.
2019-08-29 22:59:24,738 - freqtrade.resolvers.iresolver - WARNING - Path "/home/freqtrade/freqtrade/user_data/pairlist" does not exist.
2019-08-29 22:59:24,739 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from '/home/freqtrade/freqtrade/freqtrade/pairlist/StaticPairList.py'...
2019-08-29 22:59:24,748 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'running'}
2019-08-29 22:59:25,442 - freqtrade.worker - INFO - Changing state to: RUNNING
2019-08-29 22:59:25,442 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': warning, 'status': 'Dry run is enabled. All trades are simulated.'}
2019-08-29 22:59:25,699 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/freqtrade/freqtrade/freqtrade/main.py", line 49, in main
    worker.run()
  File "/home/freqtrade/freqtrade/freqtrade/worker.py", line 72, in run
    state = self._worker(old_state=state)
  File "/home/freqtrade/freqtrade/freqtrade/worker.py", line 94, in _worker
    self.freqtrade.startup()
  File "/home/freqtrade/freqtrade/freqtrade/freqtradebot.py", line 103, in startup
    self.rpc.startup_messages(self.config, self.pairlists)
  File "/home/freqtrade/freqtrade/freqtrade/rpc/rpc_manager.py", line 65, in startup_messages
    'status': 'Dry run is enabled. All trades are simulated.'
  File "/home/freqtrade/freqtrade/freqtrade/rpc/rpc_manager.py", line 59, in send_msg
    mod.send_msg(msg)
  File "/home/freqtrade/freqtrade/freqtrade/rpc/webhook.py", line 49, in send_msg
    raise NotImplementedError('Unknown message type: {}'.format(msg['type']))
NotImplementedError: Unknown message type: RPCMessageType.WARNING_NOTIFICATION
2019-08-29 22:59:25,699 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2019-08-29 22:59:26,006 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2019-08-29 22:59:26,006 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
2019-08-29 22:59:26,006 - freqtrade.rpc.api_server - INFO - Stopping API Server
2019-08-29 22:59:26,330 - freqtrade.rpc.api_server - INFO - Local Rest Server started.

```

related, redacted(ish), config:
```
{

"dry_run": true,

"telegram": {
	"enabled": true,
	"token": "redacted",
	"chat_id": "redacted"
},

"api_server": {
	"enabled": true,
	"listen_ip_address": "127.0.0.1",
	"listen_port": 10110,
 	"username": "strategy110",
 	"password": "clearttextpasswordstrategy110"
},

"webhook": {
	"enabled": true,
	"url": "http://REDACTED/wh/strategy110/",
	"webhookbuy": {
		"v": "{exchange}|{pair}|{limit:8f}|{stake_amount:8f}|{stake_currency}|{fiat_currency}|{order_type}"
	},
	"webhooksell": {
		"v": "{exchange}|{pair}|{limit:8f}|{amount:8f}|{stake_currency}|{fiat_currency}|{order_type}|{open_rate}|{current_rate}|{gain}|{profit_amount:8f}|{profit_percent}|{sell_reason}"
	},
	"webhookstatus": {
		"v": "{status}"
	}
},

}

```

**Comment by Gabriele-Sabatino** [comment]
Were you able to solve this problem, having the same problem right now.

**Comment by xmatthias** [comment]
please don't post on old issues, but instead open a new issue with all details.
As this issue is 2 years old - it's very unlikely you have the same issue (otherwise you're running a 2 year old version).
