### ISSUE TITLE
download-data fails with difficult to interpret messages in certain cases

### ISSUE THREAD

**Issue by hroff-1902** [freqtrade/freqtrade#2229]
1)
```
(.env) user@nuc:~/freqtrade-wrk/github-hroff-1902/freqtrade$ freqtrade download-data
2019-09-06 01:00:01,335 - freqtrade.loggers - INFO - Verbosity set to 0
2019-09-06 01:00:01,336 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2019-09-06 01:00:01,336 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite://"
2019-09-06 01:00:01,336 - freqtrade.configuration.configuration - INFO - Using max_open_trades: None ...
2019-09-06 01:00:01,336 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/user/freqtrade-wrk/github-hroff-1902/freqtrade/user_data ...
2019-09-06 01:00:01,337 - freqtrade.configuration.configuration - INFO - Using data directory: /home/user/freqtrade-wrk/github-hroff-1902/freqtrade/user_data/data ...
2019-09-06 01:00:01,337 - freqtrade.configuration.configuration - INFO - timeframes --timeframes: ['1m', '5m']
2019-09-06 01:00:01,337 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2019-09-06 01:00:01,337 - freqtrade - ERROR - Exchange "" is not supported by ccxt and therefore not available for the bot.
The following exchanges are supported by ccxt: _1btcxe, acx, allcoin, anxpro, bcex, bequant, bibox, bigone, binance, binanceje, bit2c, bitbank, bitbay, bitfinex, bitfinex2, bitflyer, bitforex, bithumb, bitkk, bitlish, bitmart, bitmex, bitso, bitstamp, bitstamp1, bittrex, bitz, bl3p, bleutrade, braziliex, btcalpha, btcbox, btcchina, btcmarkets, btctradeim, btctradeua, btcturk, buda, bxinth, cex, chilebit, cobinhood, coinbase, coinbaseprime, coinbasepro, coincheck, coinegg, coinex, coinexchange, coinfalcon, coinfloor, coingi, coinmarketcap, coinmate, coinone, coinspot, cointiger, coolcoin, coss, crex24, crypton, deribit, digifinex, dsx, dx, ethfinex, exmo, exx, fcoin, fcoinjp, flowbtc, foxbit, fybse, gateio, gdax, gemini, hitbtc, hitbtc2, huobipro, huobiru, ice3x, independentreserve, indodax, itbit, kkex, kraken, kucoin, kucoin2, kuna, lakebtc, latoken, lbank, liquid, livecoin, luno, lykke, mandala, mercado, mixcoins, negociecoins, nova, oceanex, okcoincny, okcoinusd, okex, okex3, paymium, poloniex, rightbtc, southxchange, stronghold, surbitcoin, theocean, therock, tidebit, tidex, upbit, vaultoro, vbtc, virwox, xbtce, yobit, zaif, zb
```
-- Maybe it's covered by #2217  . If not, the message should not include `Exchange ""` but should be something like `Exchange is not specified.`

2) 
```
(.env) user@nuc:~/freqtrade-wrk/github-hroff-1902/freqtrade$ freqtrade download-data --exchange bittrex
2019-09-06 01:00:15,176 - freqtrade.loggers - INFO - Verbosity set to 0
2019-09-06 01:00:15,177 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2019-09-06 01:00:15,177 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite://"
2019-09-06 01:00:15,177 - freqtrade.configuration.configuration - INFO - Using max_open_trades: None ...
2019-09-06 01:00:15,177 - freqtrade.configuration.configuration - INFO - Using exchange bittrex
2019-09-06 01:00:15,178 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/user/freqtrade-wrk/github-hroff-1902/freqtrade/user_data ...
2019-09-06 01:00:15,178 - freqtrade.configuration.configuration - INFO - Using data directory: /home/user/freqtrade-wrk/github-hroff-1902/freqtrade/user_data/data/bittrex ...
2019-09-06 01:00:15,178 - freqtrade.configuration.configuration - INFO - timeframes --timeframes: ['1m', '5m']
2019-09-06 01:00:15,178 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2019-09-06 01:00:15,178 - freqtrade.configuration.check_exchange - INFO - Exchange "bittrex" is officially supported by the Freqtrade development team.
2019-09-06 01:00:15,179 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/user/freqtrade-wrk/github-hroff-1902/freqtrade/freqtrade/main.py", line 40, in main
    args.func(args)
  File "/home/user/freqtrade-wrk/github-hroff-1902/freqtrade/freqtrade/utils.py", line 75, in start_download_data
    logger.info(f'About to download pairs: {config["pairs"]}, '
KeyError: 'pairs'
```

**Comment by hroff-1902** [comment]
Both fixed by #2217. (I wonder why 2) is also fixed. Pairs are set in the minimal config?)
Closing... 

Note to myself: Need to review it along with #2217

**Comment by xmatthias** [comment]
I've renamed the issue now, since it's not broken, but in certain cases (no `--config`, no `--exchange xxx --pairs yyy`) the messages are not 100% clear.

the first message is a side-effect of checking exchanges against ccxt. 
if neihter `--exchange`, nor `--config` is available, then the bot does not know which exchange to use - and "" is in fact, not a valid exchange. While irritating, the message is technically correct.
Adding a default exchange to minimal config would fix this - but whichever you choose, it'll be incorrect for some users (in the future more, if we support more exchanges).

The fix #2217 adds is to load `config.json` if it exists (apparently it does for you / the affected user). 
Remove that and the problem will reappear. 

This leads to the 2nd problem, without having exchange, `pairs.json` won't be found (it looks in the wrong folder). Assuming that's not present, there is no information what pairs the user would like - that's required to correctly download data as well, so somehow needs to be passed in (as `--pairs`, `pairs.json` or `whitelist` in configuration).

**Comment by hroff-1902** [comment]
I think I closed it after the merge of #2217 into develop. It was a late night...

**Comment by hroff-1902** [comment]
@xmatthias people run very simple intuitive commands: `freqtrade download-data --exchange exchange` and `freqtrade download-data` and it does not work. This means that download-data is (was) broken.

**Comment by xmatthias** [comment]
I don't disagree with this fact, but using titles that explain the problem are easier to re-find  than "it's broken" ...

Additionally, i would not consider this closed yet to be honest, since it'll produce the same errors if `config.json` does not exist in the current directory.
