### ISSUE TITLE
Unable to built docker pi image on raspberry pi 3

### ISSUE THREAD

**Issue by gaugau3000** [freqtrade/freqtrade#2273]
Hi, 

I don't succeed building the image on a rasberry pi 3.

OS "Raspbian GNU/Linux 9 (stretch)"

```
> pi@GP-RB-FRONT:~/freqtrade/freqtrade $ docker build . -f Dockerfile.pi -t freqtrade
> Sending build context to Docker daemon  19.51MB
> Step 1/15 : FROM balenalib/raspberrypi3-debian:stretch
>  ---> 72b8e4ae9043
> Step 2/15 : RUN [ "cross-build-start" ]
>  ---> Running in 66dfc8472a92
> standard_init_linux.go:211: exec user process caused "exec format error"
> The command 'cross-build-start' returned a non-zero code: 1
```

Have a nice day.

**Comment by sanitariu** [comment]
My advice is to upgrade pi3 to buster then use normal linux installs.
I am using that way.

**Comment by xmatthias** [comment]
hi @gaugau3000 ,

the way this image works is to cross-build it on a normal pc and then export/import it to the raspberry as building this on the raspberry would take ages.

I've been trying to set this up in CI but travis times out ... 

Hope this helps

**Comment by gaugau3000** [comment]
I got it :-) will try. Many tks !

**Comment by xmatthias** [comment]
I will actually still try to publish this somehow (either through Github actions, or through azure ...) - but i lacked the time to set this up completely)

**Comment by gaugau3000** [comment]
I don't succeed building the image on windows.

Complete output from command /root/berryconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-0jh40zzd/scikit-learn/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-b2x3hq_s-record/install-record.txt --single-version-externally-managed --compile:
    Partial import of sklearn during the build process.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-0jh40zzd/scikit-learn/setup.py", line 290, in <module>
        setup_package()
      File "/tmp/pip-build-0jh40zzd/scikit-learn/setup.py", line 286, in setup_package
        setup(**metadata)
      File "/root/berryconda3/lib/python3.6/site-packages/numpy/distutils/core.py", line 135, in setup
        config = configuration()
      File "/tmp/pip-build-0jh40zzd/scikit-learn/setup.py", line 174, in configuration
        config.add_subpackage('sklearn')
      File "/root/berryconda3/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 1034, in add_subpackage
        caller_level = 2)
      File "/root/berryconda3/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 1003, in get_subpackage
        caller_level = caller_level + 1)
      File "/root/berryconda3/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 940, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "sklearn/setup.py", line 62, in configuration
        config.add_subpackage('utils')
      File "/root/berryconda3/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 1034, in add_subpackage
        caller_level = 2)
      File "/root/berryconda3/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 1003, in get_subpackage
        caller_level = caller_level + 1)
      File "/root/berryconda3/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 940, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "sklearn/utils/setup.py", line 8, in configuration
        from Cython import Tempita
    ModuleNotFoundError: No module named 'Cython'

    ----------------------------------------
Command "/root/berryconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-0jh40zzd/scikit-learn/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-b2x3hq_s-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-0jh40zzd/scikit-learn/
You are using pip version 9.0.1, however version 19.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The command '/bin/sh -c ~/berryconda3/bin/conda install -y numpy pandas scipy  && ~/berryconda3/bin/pip install -r requirements-common.txt --no-cache-dir' returned a non-zero code: 1

Many tks.

**Comment by xmatthias** [comment]
a quick fix is adding `cython` to  the `conda install` line, so itlooks as follows:
```patch
 # Install dependencies
 COPY requirements-common.txt /freqtrade/
-RUN ~/berryconda3/bin/conda install -y numpy pandas scipy \
+RUN ~/berryconda3/bin/conda install -y cython numpy pandas scipy \
  && ~/berryconda3/bin/pip install -r requirements-common.txt --no-cache-dir
 
```

For now, i'll not add this as i think there is a simpler solution which will speed up generating this image - but that will require some more testing.
