### ISSUE TITLE
Unable to plot backtesting data

### ISSUE THREAD

**Issue by acost-matt** [freqtrade/freqtrade#2333]
## Step 2: Describe your environment

  * Operating system: linux ubuntu
  * Python Version: python 3.6.8
  
## Step 3: Describe the problem:

Unable to plot backtesting results

### Steps to reproduce:

 Tried both these commands (replacing xxx with the coin I'd like to plot)

python3 ./scripts/plot_dataframe.py -s BBRSI -p xxx/BTC  

python3 scripts/plot_dataframe.py -s BBRSI --export trades --export trades --export-filename BBRSI_results.json -p xxx/BTC --datadir user_data/data/kraken/

### Observed Results:

First command....
(.env) cryptobot@cryptobot-VirtualBox:~/freqtrade$ python3 ./scripts/plot_dataframe.py -s BBRSI -p MLN/BTC
/home/cryptobot/freqtrade/.env/lib/python3.6/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning:

sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.

Traceback (most recent call last):
  File "./scripts/plot_dataframe.py", line 381, in <module>
    main(sys.argv[1:])
  File "./scripts/plot_dataframe.py", line 376, in main
    plot_parse_args(sysargv)
  File "./scripts/plot_dataframe.py", line 106, in plot_analyzed_dataframe
    _CONF.update(setup_configuration(args))
  File "/home/cryptobot/freqtrade/freqtrade/optimize/backtesting.py", line 452, in setup_configuration
    config = configuration.get_config()
  File "/home/cryptobot/freqtrade/freqtrade/configuration.py", line 299, in get_config
    self.config = self.load_config()
  File "/home/cryptobot/freqtrade/freqtrade/configuration.py", line 47, in load_config
    config = self._load_config_file(self.args.config)
  File "/home/cryptobot/freqtrade/freqtrade/configuration.py", line 81, in _load_config_file
    conf = json.load(file)
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 24 (char 25)

Second command.....
(.env) cryptobot@cryptobot-VirtualBox:~/freqtrade$ python3 scripts/plot_dataframe.py -s BBRSI --export trades --export trades --export-filename BBRSI_results.json -p MLN/BTC --datadir user_data/data/kraken/
/home/cryptobot/freqtrade/.env/lib/python3.6/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning:

sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.

Traceback (most recent call last):
  File "scripts/plot_dataframe.py", line 381, in <module>
    main(sys.argv[1:])
  File "scripts/plot_dataframe.py", line 376, in main
    plot_parse_args(sysargv)
  File "scripts/plot_dataframe.py", line 106, in plot_analyzed_dataframe
    _CONF.update(setup_configuration(args))
  File "/home/cryptobot/freqtrade/freqtrade/optimize/backtesting.py", line 452, in setup_configuration
    config = configuration.get_config()
  File "/home/cryptobot/freqtrade/freqtrade/configuration.py", line 299, in get_config
    self.config = self.load_config()
  File "/home/cryptobot/freqtrade/freqtrade/configuration.py", line 47, in load_config
    config = self._load_config_file(self.args.config)
  File "/home/cryptobot/freqtrade/freqtrade/configuration.py", line 81, in _load_config_file
    conf = json.load(file)
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 24 (char 25)

**Comment by xmatthias** [comment]
Based on the error, you've got a syntax error in your configuration file. (line 2, character 24).

Also, since you're using `scripts/plot_dataframe.py` i can see that you're probably using an older version (even though the template was not filled out). 
I would reccomend to upgrade, otherwise the documentation will not match.

**Comment by hroff-1902** [comment]
@acost-matt Is it okay now? Have you updated and run it with the actual version?

**Comment by hroff-1902** [comment]
Closing it since the question was answered and no further input provided.
Feel free to reopen it.
