### ISSUE TITLE
Unable to run optimization

### ISSUE THREAD

**Issue by acost-matt** [freqtrade/freqtrade#2334]
## Step 2: Describe your environment

  * Operating system: Linux Ubuntu
  * Python Version: python 3.6.8
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Branch: Master | Develop
  * Last Commit ID: _____ (`git log --format="%H" -n 1`)
  
## Step 3: Describe the problem:

Unable to run optimization using hyperopt

### Steps to reproduce:

python3 ./freqtrade/main.py -c config.json.m8kraken --customhyperopt BBRSIOPT hyperopt -e 100
  
### Observed Results:

```
(.env) cryptobot@cryptobot-VirtualBox:~/freqtrade$ python3 ./freqtrade/main.py -c config.json.m8kraken --customhyperopt BBRSIOPT hyperopt -e 100
/home/cryptobot/freqtrade/.env/lib/python3.6/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
2019-10-02 16:17:17,574 - freqtrade.configuration - INFO - Verbosity set to 0
2019-10-02 16:17:17,579 - freqtrade.configuration - INFO - Dry run is enabled
2019-10-02 16:17:17,579 - freqtrade.configuration - INFO - Using DB: "sqlite://"
2019-10-02 16:17:17,579 - freqtrade.configuration - INFO - Using max_open_trades: 15 ...
2019-10-02 16:17:17,580 - freqtrade.configuration - INFO - Using data folder: user_data/data/kraken ...
2019-10-02 16:17:17,580 - freqtrade.configuration - INFO - Parameter --epochs detected ...
2019-10-02 16:17:17,580 - freqtrade.configuration - INFO - Will run Hyperopt with for 100 epochs ...
2019-10-02 16:17:17,580 - freqtrade.configuration - INFO - Parameter -s/--spaces detected: all
2019-10-02 16:17:17,588 - freqtrade.resolvers.strategy_resolver - INFO - Using resolved strategy DefaultStrategy from '/home/cryptobot/freqtrade/freqtrade/strategy'
2019-10-02 16:17:17,591 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ticker_interval' with value in config file: 1h.
2019-10-02 16:17:17,593 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'trailing_stop' with value in config file: False.
2019-10-02 16:17:17,594 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'40': 0.0, '30': 0.01, '20': 0.02, '0': 0.04}
2019-10-02 16:17:17,594 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ticker_interval: 1h
2019-10-02 16:17:17,594 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.1
2019-10-02 16:17:17,594 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2019-10-02 16:17:17,594 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
2019-10-02 16:17:17,594 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False}
2019-10-02 16:17:17,594 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
2019-10-02 16:17:17,594 - freqtrade.exchange - INFO - Instance is running with dry_run enabled
2019-10-02 16:17:17,594 - freqtrade.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2019-10-02 16:17:17,600 - freqtrade.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': False}
2019-10-02 16:17:17,637 - freqtrade.exchange - INFO - Using Exchange "Kraken"
2019-10-02 16:17:24,898 - freqtrade.resolvers.hyperopt_resolver - INFO - Using resolved hyperopt BBRSIOPT from '/home/cryptobot/freqtrade/freqtrade/optimize'
Traceback (most recent call last):
  File "/home/cryptobot/freqtrade/.env/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2890, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'middle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./freqtrade/main.py", line 89, in <module>
    main(sys.argv[1:])
  File "./freqtrade/main.py", line 35, in main
    args.func(args)
  File "/home/cryptobot/freqtrade/freqtrade/optimize/hyperopt.py", line 355, in start
    hyperopt.start()
  File "/home/cryptobot/freqtrade/freqtrade/optimize/hyperopt.py", line 296, in start
    dump(self.strategy.tickerdata_to_dataframe(data), TICKERDATA_PICKLE)
  File "/home/cryptobot/freqtrade/freqtrade/strategy/interface.py", line 341, in tickerdata_to_dataframe
    for pair, pair_data in tickerdata.items()}
  File "/home/cryptobot/freqtrade/freqtrade/strategy/interface.py", line 341, in <dictcomp>
    for pair, pair_data in tickerdata.items()}
  File "/home/cryptobot/freqtrade/freqtrade/optimize/bbrsiopt.py", line 31, in populate_indicators
    dataframe['bb_middleband1'] = bollinger1['middle']
  File "/home/cryptobot/freqtrade/.env/lib/python3.6/site-packages/pandas/core/frame.py", line 2975, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/cryptobot/freqtrade/.env/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2892, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'middle'
```

**Comment by hroff-1902** [comment]
There is an error in your custom code. 

I need the text of the `populate_indicators()` function from your hyperopt.

**Comment by hroff-1902** [comment]
Just a note:
```
File "/home/cryptobot/freqtrade/freqtrade/optimize/bbrsiopt.py", line 31, in populate_indicators
    dataframe['bb_middleband1'] = bollinger1['middle']
```
-- you should better place your custom hyperopts into the `user_data/hyperopts` dir instead of `freqtrade/optimize`. That's the place for custom code. Same for your custom strategies: the proper place is `user_data/strategies`, not somewhere under `freqtrade` subdir.

If this is what they suggested you at the Udemy course, they are completely wrong...

**Comment by acost-matt** [comment]
'''
    def populate_indicators(dataframe: DataFrame, metadata: dict) -> DataFrame:

        dataframe['rsi'] = ta.RSI(dataframe)
        dataframe['sell-rsi'] = ta.RSI(dataframe)

        # Bollinger bands
        bollinger1 = qtpylib.bollinger_bands(qtpylib.typical_price(dataframe), window=20, stds=1)
        dataframe['bb_lowerband1'] = bollinger1['lower']
        dataframe['bb_middleband1'] = bollinger1['middle']
        dataframe['bb_upperband1'] = bollinger1['upper']

        bollinger2 = qtpylib.bollinger_bands(qtpylib.typical_price(dataframe), window=20, stds=2)
        dataframe['bb_lowerband2'] = bollinger2['lower']
        dataframe['bb_middleband2'] = bollinger2['middle']
        dataframe['bb_upperband2'] = bollinger2['upper']

        bollinger3 = qtpylib.bollinger_bands(qtpylib.typical_price(dataframe), window=20, stds=3)
        dataframe['bb_lowerband3'] = bollinger3['lower']
        dataframe['bb_middleband3'] = bollinger3['middle']
        dataframe['bb_upperband3'] = bollinger3['upper']

        bollinger4 = qtpylib.bollinger_bands(qtpylib.typical_price(dataframe), window=20, stds=4)
        dataframe['bb_lowerband4'] = bollinger4['lower']
        dataframe['bb_middleband4'] = bollinger4['middle']
        dataframe['bb_upperband4'] = bollinger4['upper']

        return dataframe
'''



Here is my populate indicators section of my hyperopt. And thank you for that note! I was following the Udemy course and unaware those files should be in the user_data folder. I will move those over now

**Comment by hroff-1902** [comment]
https://github.com/freqtrade/freqtrade/blob/2c0d2c15327c022441328788e9306f938dd326a9/freqtrade/vendor/qtpylib/indicators.py#L432-L436

-- `qtpylib.bollinger_bands()` names the column for the middle line in the different manner. Use `'mid'` instead of `'middle'`.

**Comment by hroff-1902** [comment]
@xmatthias 
we should probably fix it in our version of qtpylib and return two columns: 'mid' (for compatibility) and 'middle' (for normal people)

**Comment by hroff-1902** [comment]
@acost-matt you are welcome, pls close the issue if the problem has gone after fixing the names of the columns.

**Comment by hroff-1902** [comment]
> I was following the Udemy course and unaware those files should be in the user_data folder. I will move those over now

[Freqtrade docs](https://www.freqtrade.io/en/latest/hyperopt/#1-install-a-custom-hyperopt-file) says:
```
1.
...
Put your hyperopt file into the directory user_data/hyperopts.
```

😭

**Comment by acost-matt** [comment]
Thank you I changed each instance of 'middle' in my populate indicators section to 'mid'.

Apologies if this is a simple question.. but I've moved the hyperopt into my user_data/hyperopts folder and tried running it with the command on the freqtrade website and am getting an error saying there is no file or directory. Am I naming something wrong? Or using the wrong command to start the opt?


'''
(.env) cryptobot@cryptobot-VirtualBox:~/freqtrade$ freqtrade -c config.json.m8kraken hyperopt --customhyperopt BBRSIOPT -e 1000 --spaces all
/home/cryptobot/freqtrade/.env/lib/python3.6/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
usage: freqtrade [-h] [-v] [--version] [-c PATH] [-d PATH] [-s NAME]
                 [--strategy-path PATH] [--customhyperopt NAME]
                 [--dynamic-whitelist [INT]] [--db-url PATH]
                 {backtesting,edge,hyperopt} ...
freqtrade: error: unrecognized arguments: --customhyperopt BBRSIOPT
(.env) cryptobot@cryptobot-VirtualBox:~/freqtrade$ freqtrade -c config.json.m8kraken hyperopt --customhyperopt bbrsiopt.py -e 1000 --spaces all
/home/cryptobot/freqtrade/.env/lib/python3.6/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
usage: freqtrade [-h] [-v] [--version] [-c PATH] [-d PATH] [-s NAME]
                 [--strategy-path PATH] [--customhyperopt NAME]
                 [--dynamic-whitelist [INT]] [--db-url PATH]
                 {backtesting,edge,hyperopt} ...
freqtrade: error: unrecognized arguments: --customhyperopt bbrsiopt.py
'''

**Comment by acost-matt** [comment]
Wow thats funny, I moved them now lol.
And thank you I changed each instance of 'middle' in my populate indicators section to 'mid'.

Apologies if this is a simple question.. but I've moved the hyperopt into my user_data/hyperopts folder and tried running it with the command on the freqtrade website and am getting an error saying there is no file or directory. Am I naming something wrong? Or using the wrong command to start the opt?

'''
(.env) cryptobot@cryptobot-VirtualBox:/freqtrade$ freqtrade -c config.json.m8kraken hyperopt --customhyperopt BBRSIOPT -e 1000 --spaces all
/home/cryptobot/freqtrade/.env/lib/python3.6/site-packages/sklearn/externals/joblib/init.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
warnings.warn(msg, category=DeprecationWarning)
usage: freqtrade [-h] [-v] [--version] [-c PATH] [-d PATH] [-s NAME]
[--strategy-path PATH] [--customhyperopt NAME]
[--dynamic-whitelist [INT]] [--db-url PATH]
{backtesting,edge,hyperopt} ...
freqtrade: error: unrecognized arguments: --customhyperopt BBRSIOPT
(.env) cryptobot@cryptobot-VirtualBox:/freqtrade$ freqtrade -c config.json.m8kraken hyperopt --customhyperopt bbrsiopt.py -e 1000 --spaces all
/home/cryptobot/freqtrade/.env/lib/python3.6/site-packages/sklearn/externals/joblib/init.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
warnings.warn(msg, category=DeprecationWarning)
usage: freqtrade [-h] [-v] [--version] [-c PATH] [-d PATH] [-s NAME]
[--strategy-path PATH] [--customhyperopt NAME]
[--dynamic-whitelist [INT]] [--db-url PATH]
{backtesting,edge,hyperopt} ...
freqtrade: error: unrecognized arguments: --customhyperopt bbrsiopt.py
'''

**Comment by hroff-1902** [comment]
please give me the output of `freqtrade -V`

**Comment by xmatthias** [comment]
assuming it's the Udemy course - then it's probably that version too - and i would not bet that we have had the "hyperoptResolver" with the user-data path in that version ...

**Comment by hroff-1902** [comment]
@acost-matt Is it okay now? Have you updated and run it with the actual version?

**Comment by hroff-1902** [comment]
Closing it as the questions were answered.
Feel free to reopen.
