### ISSUE TITLE
hyperopt problem

### ISSUE THREAD

**Issue by mj1300** [freqtrade/freqtrade#2398]
## Step 2: Describe your environment

  * Operating system: windows 10 X64
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Branch: Master | Develop
  * Last Commit ID: _____ (`git log --format="%H" -n 1`)
  
## Step 3: Describe the problem:
when i run hyperopt i get this errors:
```
2019-10-20 23:10:48,041 - freqtrade.optimize.hyperopt - INFO - Effective number of parallel workers used: 8
ERROR: The process "388" not found.
ERROR: The process "14308" not found.
ERROR: The process "12000" not found.
ERROR: The process "4040" not found.
ERROR: The process "3608" not found.
ERROR: The process "8348" not found.
2019-10-20 23:10:57,087 - freqtrade - ERROR - Fatal exception!
joblib.externals.loky.process_executor._RemoteTraceback:
'''
Traceback (most recent call last):
  File "c:\users\usertest\desktop\pt\freqtrade\.env\lib\site-packages\joblib\externals\loky\process_executor.py", line 391, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "C:\Users\usertest\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\queues.py", line 99, in get
    if not self._rlock.acquire(block, timeout):
OSError: [WinError 6] The handle is invalid
'''
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "c:\users\usertest\desktop\pt\freqtrade\freqtrade\main.py", line 39, in main
    args['func'](args)
  File "c:\users\usertest\desktop\pt\freqtrade\freqtrade\optimize\__init__.py", line 74, in start_hyperopt
    hyperopt.start()
  File "c:\users\usertest\desktop\pt\freqtrade\freqtrade\optimize\hyperopt.py", line 410, in start
    f_val = self.run_optimizer_parallel(parallel, asked)
  File "c:\users\usertest\desktop\pt\freqtrade\freqtrade\optimize\hyperopt.py", line 347, in run_optimizer_parallel
    wrap_non_picklable_objects(self.generate_optimizer))(v) for v in asked)
  File "c:\users\usertest\desktop\pt\freqtrade\.env\lib\site-packages\joblib\parallel.py", line 934, in __call__
    self.retrieve()
  File "c:\users\usertest\desktop\pt\freqtrade\.env\lib\site-packages\joblib\parallel.py", line 833, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "c:\users\usertest\desktop\pt\freqtrade\.env\lib\site-packages\joblib\_parallel_backends.py", line 521, in wrap_future_result
    return future.result(timeout=timeout)
  File "C:\Users\usertest\AppData\Local\Programs\Python\Python37-32\lib\concurrent\futures\_base.py", line 435, in result
    return self.__get_result()
  File "C:\Users\usertest\AppData\Local\Programs\Python\Python37-32\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.
```
 i use this command for hyperopt:
`freqtrade -c config.json hyperopt --customhyperopt SampleHyperOpts2 -e 100 --spaces all`

**Comment by hroff-1902** [comment]
pls describe your environment:

  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Branch: Master | Develop
  * Last Commit ID: _____ (`git log --format="%H" -n 1`)

**Comment by mj1300** [comment]
## Step 2: Describe your environment

  * Operating system: Windows 8 X64
  * Python Version: _____ 3.7.4 32bit
  * CCXT version: _____ (`pip freeze | grep ccxt`) = 1.18.1115
  * Branch: Master | Develop
  * Last Commit ID: _____ (`git log --format="%H" -n 1`)

**Comment by hroff-1902** [comment]
Seems to be a known problem in joblib's loky library: https://github.com/Neo23x0/Loki/issues/113

**Comment by hroff-1902** [comment]
I would also appreciate to know the latest commit explicitly, but ccxt version says it's of 31 Aug, so I assume you are using freqtrade codebase also from that date

Try to update, and update the dependencies, maybe a newer version of skit-learn will be installed (it uses it's own copy of joblib which causes the problem)

actually, we should wait till that new fixed version of loky is released, then wait till it's fetched by joblib project and then wait till the change is propagated into skit-learn, since it uses its own copy of joblib

in the meantime, try to apply this recipe: https://www.bleepingcomputer.com/forums/t/674054/dozens-of-application-data-folders-nestedembedded/?p=4470253
 (see post 2 there, with Windows Repair)

I'm not sure it's related directly, but this was cited in that issue in loky repo I mentioned above...

**Comment by xmatthias** [comment]
hyperopt does work fine on my windows 10 machine after using the [windows installation](https://www.freqtrade.io/en/latest/installation/#windows) guide - it also works in parallel.


please use `freqtrade --datadir tests/testdata --config config.json.example hyperopt -e 50 --customhyperopt DefaultHyperOpt` to verify if the standard (default) Hyperopt does work.

If it does, then this is a platform independent problem, which could be be caused by the strategy / custom hyperopt file - using something pickle does not like (we've had problems with that in the past ...).

If the above command succeeds i think we'll need your custom hyperopt file to continue analyzing this (maybe send it to @hroff-1902 or myself privately via Slack?).

**Comment by mj1300** [comment]
when i run this command i got same erroe below:
```
(.env) C:\Users\usertest\Desktop\pt\freqtrade>freqtrade --datadir tests/testdata --config config.json.example hyperopt -e 50 --customhyperopt SampleHyperOpts
c:\users\usertest\desktop\pt\freqtrade\.env\lib\site-packages\sklearn\externals\joblib\__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
2019-10-22 13:45:36,478 - freqtrade.loggers - INFO - Verbosity set to 0
2019-10-22 13:45:36,479 - freqtrade.configuration.configuration - INFO - Dry run is disabled
2019-10-22 13:45:36,479 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:///tradesv3.sqlite"
2019-10-22 13:45:36,479 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 3 ...
2019-10-22 13:45:36,481 - freqtrade.configuration.configuration - INFO - Using user-data directory: C:\Users\usertest\Desktop\pt\freqtrade\user_data ...
2019-10-22 13:45:36,481 - freqtrade.configuration.configuration - INFO - Using data directory: tests\testdata ...
2019-10-22 13:45:36,482 - freqtrade.configuration.configuration - INFO - Using Hyperopt class name: SampleHyperOpts
2019-10-22 13:45:36,483 - freqtrade.configuration.configuration - INFO - Parameter --epochs detected ... Will run Hyperopt with for 50 epochs ...
2019-10-22 13:45:36,483 - freqtrade.configuration.configuration - INFO - Parameter -s/--spaces detected: all
2019-10-22 13:45:36,483 - freqtrade.configuration.configuration - INFO - Parameter -j/--job-workers detected: -1
2019-10-22 13:45:36,484 - freqtrade.configuration.configuration - INFO - Parameter --min-trades detected: 1
2019-10-22 13:45:36,485 - freqtrade.configuration.configuration - INFO - Using Hyperopt loss class name: DefaultHyperOptLoss
2019-10-22 13:45:36,485 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2019-10-22 13:45:36,486 - freqtrade.configuration.check_exchange - INFO - Exchange "bittrex" is officially supported by the Freqtrade development team.
2019-10-22 13:45:36,486 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2019-10-22 13:45:36,489 - freqtrade.optimize - INFO - Starting freqtrade in Hyperopt mode
2019-10-22 13:45:36,498 - filelock - INFO - Lock 248595472 acquired on C:\Users\usertest\Desktop\pt\freqtrade\user_data\hyperopt.lock
2019-10-22 13:45:36,521 - freqtrade.resolvers.iresolver - INFO - Using resolved hyperopt SampleHyperOpts from 'C:\Users\usertest\Desktop\pt\freqtrade\user_data\hyperopts\sample_hyperopt.py'...
2019-10-22 13:45:36,522 - freqtrade.resolvers.exchange_resolver - INFO - No Bittrex specific subclass found. Using the generic class instead.
2019-10-22 13:45:36,524 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2019-10-22 13:45:36,525 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2019-10-22 13:45:36,532 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 500}
2019-10-22 13:45:36,555 - freqtrade.exchange.exchange - INFO - Using Exchange "Bittrex"
2019-10-22 13:45:40,369 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy DefaultStrategy from 'C:\Users\usertest\Desktop\pt\freqtrade\freqtrade\strategy\default_strategy.py'...
2019-10-22 13:45:40,370 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ticker_interval' with value in config file: 5m.
2019-10-22 13:45:40,371 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'trailing_stop' with value in config file: False.
2019-10-22 13:45:40,375 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: BTC.
2019-10-22 13:45:40,375 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 0.05.
2019-10-22 13:45:40,375 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'use_sell_signal' with value in config file: False.
2019-10-22 13:45:40,376 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'sell_profit_only' with value in config file: False.
2019-10-22 13:45:40,376 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ignore_roi_if_buy_signal' with value in config file: False.
2019-10-22 13:45:40,377 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 0.05, '10080': -0.05, '10081': -0.1, '10082': -0.15}
2019-10-22 13:45:40,377 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ticker_interval: 5m
2019-10-22 13:45:40,378 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -10.1
2019-10-22 13:45:40,378 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2019-10-22 13:45:40,378 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2019-10-22 13:45:40,379 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2019-10-22 13:45:40,380 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
2019-10-22 13:45:40,386 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False}
2019-10-22 13:45:40,386 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
2019-10-22 13:45:40,387 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: BTC
2019-10-22 13:45:40,388 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 0.05
2019-10-22 13:45:40,388 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_sell_signal: False
2019-10-22 13:45:40,389 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_only: False
2019-10-22 13:45:40,390 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_buy_signal: False
2019-10-22 13:45:40,401 - freqtrade.resolvers.iresolver - INFO - Using resolved hyperoptloss DefaultHyperOptLoss from 'C:\Users\usertest\Desktop\pt\freqtrade\freqtrade\optimize\default_hyperopt_loss.py'...
2019-10-22 13:45:40,417 - freqtrade.optimize.hyperopt - INFO - Removing `C:\Users\usertest\Desktop\pt\freqtrade\user_data\hyperopt_results\hyperopt_tickerdata.pkl`.
2019-10-22 13:45:40,430 - freqtrade.data.history - INFO - Using local backtesting data ...
2019-10-22 13:45:40,776 - freqtrade.data.converter - INFO - Missing data fillup for DASH/BTC: before: 5757 - after: 5759
2019-10-22 13:45:40,927 - freqtrade.data.converter - INFO - Missing data fillup for ZEC/BTC: before: 5756 - after: 5758
2019-10-22 13:45:41,197 - freqtrade.data.converter - INFO - Missing data fillup for POWR/BTC: before: 5753 - after: 5759
2019-10-22 13:45:41,337 - freqtrade.data.converter - INFO - Missing data fillup for ADA/BTC: before: 5719 - after: 5759
2019-10-22 13:45:41,400 - freqtrade.data.converter - INFO - Missing data fillup for XMR/BTC: before: 5757 - after: 5759
2019-10-22 13:45:41,405 - freqtrade.optimize.hyperopt - INFO - Hyperopting with data from 2018-01-10T04:55:00+00:00 up to 2018-01-30T04:45:00+00:00 (19 days)..
2019-10-22 13:45:41,802 - freqtrade.optimize.hyperopt - INFO - Found 8 CPU cores. Let's make them scream!
2019-10-22 13:45:41,802 - freqtrade.optimize.hyperopt - INFO - Number of parallel jobs set as: -1
2019-10-22 13:45:41,835 - freqtrade.optimize.hyperopt_interface - INFO - Min roi table: {0: 0.03, 10: 0.02, 20: 0.01, 30: 0}
2019-10-22 13:45:41,836 - freqtrade.optimize.hyperopt_interface - INFO - Max roi table: {0: 0.31, 40: 0.11, 100: 0.04, 220: 0}
2019-10-22 13:45:41,846 - freqtrade.optimize.hyperopt - INFO - Effective number of parallel workers used: 8
ERROR: The process with PID 8452 (child process of PID 6536) could not be terminated.
Reason: There is no running instance of the task.
ERROR: The process with PID 6536 (child process of PID 10140) could not be terminated.
Reason: There is no running instance of the task.
ERROR: The process "15900" not found.
ERROR: The process "15484" not found.
ERROR: The process "1740" not found.
ERROR: The process "10160" not found.
ERROR: The process "16200" not found.
ERROR: The process "14412" not found.
2019-10-22 13:45:49,792 - freqtrade - ERROR - Fatal exception!
joblib.externals.loky.process_executor._RemoteTraceback:
'''
Traceback (most recent call last):
  File "c:\users\usertest\desktop\pt\freqtrade\.env\lib\site-packages\joblib\externals\loky\process_executor.py", line 391, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "C:\Users\usertest\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\queues.py", line 99, in get
    if not self._rlock.acquire(block, timeout):
PermissionError: [WinError 5] Access is denied
'''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\usertest\desktop\pt\freqtrade\freqtrade\main.py", line 39, in main
    args['func'](args)
  File "c:\users\usertest\desktop\pt\freqtrade\freqtrade\optimize\__init__.py", line 74, in start_hyperopt
    hyperopt.start()
  File "c:\users\usertest\desktop\pt\freqtrade\freqtrade\optimize\hyperopt.py", line 410, in start
    f_val = self.run_optimizer_parallel(parallel, asked)
  File "c:\users\usertest\desktop\pt\freqtrade\freqtrade\optimize\hyperopt.py", line 347, in run_optimizer_parallel
    wrap_non_picklable_objects(self.generate_optimizer))(v) for v in asked)
  File "c:\users\usertest\desktop\pt\freqtrade\.env\lib\site-packages\joblib\parallel.py", line 934, in __call__
    self.retrieve()
  File "c:\users\usertest\desktop\pt\freqtrade\.env\lib\site-packages\joblib\parallel.py", line 833, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "c:\users\usertest\desktop\pt\freqtrade\.env\lib\site-packages\joblib\_parallel_backends.py", line 521, in wrap_future_result
    return future.result(timeout=timeout)
  File "C:\Users\usertest\AppData\Local\Programs\Python\Python37-32\lib\concurrent\futures\_base.py", line 435, in result
    return self.__get_result()
  File "C:\Users\usertest\AppData\Local\Programs\Python\Python37-32\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.
```

**Comment by xmatthias** [comment]
> `Python37-32`

^ from your output

would you mind retrying with python 64 bit?

**Comment by mj1300** [comment]
i uninstall my python and i installed python 3.8 and intersting thing is freqtrade cant even run as before and got a lot of problem so i install another version 4 diffrent version all have errors,then i install my previous python(32bit version) freqtrade cant even run and got this strange errors :
```
Traceback (most recent call last):
  File "C:\Users\usertest\Desktop\pt\freqtrade\.env\Scripts\freqtrade-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "c:\users\usertest\desktop\pt\freqtrade\.env\lib\site-packages\pkg_resources\__init__.py", line 35, in <module>
    import plistlib
  File "C:\Users\usertest\AppData\Local\Programs\Python\Python37-32\lib\plistlib.py", line 65, in <module>
    from xml.parsers.expat import ParserCreate
  File "C:\Users\usertest\AppData\Local\Programs\Python\Python37-32\lib\xml\parsers\expat.py", line 4, in <module>
    from pyexpat import *
ImportError: DLL load failed: %1 is not a valid Win32 application.
```

**Comment by xmatthias** [comment]
i think there is chaos from the install tries. 
seems like part of the 64bit installation was installed to the 32bit python folder, or the 64bit python is earlier in %PATH% than the 32bit version, so now you're running 32bit Python with 64bit libraries (which obviously fails).

Best try to remove all python versions, reboot, install python x64 again into a different folder.

Ideally, use the Windos store version (either [3.7](https://www.microsoft.com/en-us/p/python-37/9nj46sx7x90p) or [3.8](https://www.microsoft.com/en-us/p/python-38/9mssztt1n39l) ) if that's a possibility on your windows system, since i think this takes care of most issues with PATH and such.

If it then still does not work, check the environment variable PATH for python versions which are NOT the 64bit python you just installed and remove these stale links.

**Comment by mj1300** [comment]
the problem was because of previous python(like @xmatthias said) i was looking for previous python in envirorment Varriable path but it was in C:\ directory now i install freqtrade and everythings work fine and hyperopt its run with all cpu core,thanks to @xmatthias @hroff-1902
