### ISSUE TITLE
Argument 'real' has incorrect type

### ISSUE THREAD

**Issue by gitgitgat** [freqtrade/freqtrade#2440]
Recent error with hyperopts:

```
2019-10-28 20:39:46,423 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/touchstone/Github/freqtrade/.env/lib/python3.6/site-packages/talib/__init__.py", line 20, in wrapper
    for arg in chain(args, kwargs.values())
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/touchstone/Github/freqtrade/freqtrade/main.py", line 39, in main
    args['func'](args)
  File "/home/touchstone/Github/freqtrade/freqtrade/optimize/__init__.py", line 76, in start_hyperopt
    hyperopt.start()
  File "/home/touchstone/Github/freqtrade/freqtrade/optimize/hyperopt.py", line 404, in start
    preprocessed = self.backtesting.strategy.tickerdata_to_dataframe(data)
  File "/home/touchstone/Github/freqtrade/freqtrade/strategy/interface.py", line 426, in tickerdata_to_dataframe
    for pair, pair_data in tickerdata.items()}
  File "/home/touchstone/Github/freqtrade/freqtrade/strategy/interface.py", line 426, in <dictcomp>
    for pair, pair_data in tickerdata.items()}
  File "/home/touchstone/Github/freqtrade/user_data/hyperopts/sample_hyperopt.py", line 55, in populate_indicators
    dataframe['ema20'] =  ta.EMA(timeperiod=20)
  File "talib/_abstract.pxi", line 352, in talib._ta_lib.Function.__call__
  File "talib/_abstract.pxi", line 383, in talib._ta_lib.Function.__call_function
  File "/home/touchstone/Github/freqtrade/.env/lib/python3.6/site-packages/talib/__init__.py", line 24, in wrapper
    return func(*args, **kwargs)
TypeError: Argument 'real' has incorrect type (expected numpy.ndarray, got NoneType)
```

**Comment by hroff-1902** [comment]
Please
## Step 2: Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Branch: Master | Develop
  * Last Commit ID: _____ (`git log --format="%H" -n 1`)

**Comment by hroff-1902** [comment]
...because I do not see `ta.EMA` in sample_hyperopt.py in `populate_indicators()`

**Comment by hroff-1902** [comment]
if this is your custom code, you should better use it as

dataframe['ema20'] =  ta.EMA(**_dataframe_**, timeperiod=20)

**Comment by gitgitgat** [comment]
that was the problem, thanks
