### ISSUE TITLE
Telegram command /balance not working

### ISSUE THREAD

**Issue by xephos1one** [freqtrade/freqtrade#2515]
## Step 1: Have you search for this issue before posting it?

Yes

## Step 2: Describe your environment

  * Operating system: Debian 9
  * Python Version: 3.7.5
  * CCXT version: 1.19.25
  * Branch: Develop
  * Last Commit ID: 904ae5af915d066ac14c4a4f199f44e5ea9ae7c7
  
## Step 3: Describe the problem:

The command '/balance' gets no response
The last time it was working was two days ago.
That was on an older Commit but it stopped working without updating anything -
so I updated to the newest Commit but it's still not fixed)

### Steps to reproduce:

  1. send '/balance' to the Telegram bot
  
### Observed Results:

  It shows nothing on Telegram but throws that exception in the console

### Relevant code exceptions or logs:

2019-11-11 19:44:30,705 - freqtrade.rpc.telegram - ERROR - Exception occurred within Telegram module
Traceback (most recent call last):
  File "/root/trader/freqtrade/freqtrade/rpc/telegram.py", line 52, in wrapper
    return command_handler(self, *args, **kwargs)
  File "/root/trader/freqtrade/freqtrade/rpc/telegram.py", line 326, in _balance
    result = self._rpc_balance(self._config.get('fiat_display_currency', ''))
  File "/root/trader/freqtrade/freqtrade/rpc/rpc.py", line 283, in _rpc_balance
    rate = self._freqtrade.get_sell_rate(pair, False)
  File "/root/trader/freqtrade/freqtrade/freqtradebot.py", line 581, in get_sell_rate
    rate = self.exchange.get_ticker(pair, refresh)['bid']
  File "/root/trader/freqtrade/freqtrade/exchange/common.py", line 113, in wrapper
    return f(*args, **kwargs)
  File "/root/trader/freqtrade/freqtrade/exchange/exchange.py", line 524, in get_ticker
    'bid': float(data['bid']),
TypeError: float() argument must be a string or a number, not 'NoneType'

**Comment by xmatthias** [comment]
First of all, this works for me on binance - right now...

so this will require some additional information ...
* What's the exchange used?
* What currencies do you own on the exchange (no need for the amounts ...)? (anything special / outdated)?

**Comment by xephos1one** [comment]
I'm sorry...

I use Crex24 (I know "We cannot guarantee they will work" - but it did work!)
Some of my coins came from their Faucet.
Coins in my account are:
BTC, BTCZ, BTT, GCEN, CREX, DASH, DCTO, DOGE, ETH, FREE, INNBLC, LVT, POP, SDGO, STREAM and UKC.
Also there is some USD 😃 maybe thats the problem? 🤷‍♂ 

Some other things I noticed:
Sometimes when the bot buys something there's also the message that the remaining buy order is cancelled due to timeout... But it isn't cancelled!
But that doesn't happen all the time.
Sadly I don't have a log for that...

**Comment by hroff-1902** [comment]
seems to be a bug in ccxt: results of the crex24 tickers API point (https://api.crex24.com/v2/public/tickers, look at the values) contains null as a value of the 'bid' field. This is returned by ccxt 'as is'.

API describes it as:
> If there are no active buying orders at the moment, the field contains the value null.

@xmatthias shall we handle it in exchange code? (leave Null, do not fail)

**Comment by xmatthias** [comment]
i was assuming something like this - but without exchange / details it's difficult to act on.

yes, i guess we should handle it - but i'm not certain how.

It's null because there is noone there to buy - so the information is correct.
Looking at one of these pairs (random - searching for null in the output of the exchange):

https://crex24.com/exchange/ABULABA-BTC

![2019-11-12-192733_1894x841_scrot](https://user-images.githubusercontent.com/5024695/68699025-7c72b100-0582-11ea-88c8-98dcb8a73c7a.png)

Assume your bot bought this pair - it would never be able to sell it again (unless miraculously people show up ...).

Also looking at the time of the trades - there were 6 trades since October 20th ... that's less than 1 trade per DAY!

To use one of your pairs has the same picture.
https://crex24.com/exchange/POP-BTC

![2019-11-12-193423_1889x863_scrot](https://user-images.githubusercontent.com/5024695/68699477-70d3ba00-0583-11ea-87e7-889a8759984f.png)



Assume we catch the error and return 0 instead - the bot would assume everything is "allright" and would go on and buy without possibility to sell this pair again.

Returning null (as is) is also dangerous, as we assume that a numeric value is in this field, so we would only move the exception from this function, to 20 other functions depending on this.

Personally, i'm inclined to throw a dependencyexception for this case (effectively blocking such pairs) - but we'll need to first check "how far" that'll bubble on both buy, sell and rpc sides.

**Comment by hroff-1902** [comment]
yes, but even if the user does not use those 'dangerous' pairs with no activity, the `get_tickers()` in Exchange produces all the tickers and fails on those of them where 'bid'/'ask' does not exist or is Null. That's the point and this should be fixed.

**Comment by xephos1one** [comment]
These pairs aren't whitelisted at my bot
I got some of those through the Faucet at Crex

It still counts as balance...
So I can't check the balance of my other Coins then

**Comment by hroff-1902** [comment]
@xmatthias  It's not necessary to assign zeros to them -- it's okay to leave it Nulls. The Exchange code should simply handle it without failures.

**Comment by xmatthias** [comment]
> yes, but even if the user does not use those 'dangerous' pairs with no activity, the get_tickers() in Exchange produces all the tickers and fails on those of them where 'bid'/'ask' does not exist or is Null. That's the point and this should be fixed.

`get_tickers()` is used in exactly one place - which is the VolumePairlist - which does not use neither 'bid' nor 'ask'.

@xephos1one 
yes, we're aware of this... and it'll be fixed eventually.
Please understand that i don't see this as critical - so a fix may take some time.


>  It's not necessary to assign zeros to them -- it's okay to leave it with Nulls. The Exchange code should simply handle it without failures.

well - so it won't fail in this step - but in the next where the resulting 'bid' is multiplied with None.

**Comment by xephos1one** [comment]
Wouldn't it make sense to just leave them out/skip them if they are null?

I do this just for fun and testing so it's not a problem that has to be fixed asap

**Comment by xmatthias** [comment]
that may work for /balance ... but the same error could also appear if you'd have one of these pairs in your whitelist (i know you don't - but others may), so the fix will need to work for that case, too (which makes it more complicated).

**Comment by hroff-1902** [comment]
ccxt documentation says that only a limited number of exchanges provide 'bid'/'ask' in the ticker structure, so those values from the tickers should not actually be used -- the orderbook info should be used instead.

So we can 1) gracefully handle Nulls in 'bid'/'ask' in the tickers, to not fail in case of Nulls, AND do not use those values at all. VolumePairlist should use orderbook info instead. 2) ignore those fields, remove/do not assign them in the ticker info we provide further to the code. Bids/asks should be taken from the orderbook only.

**Comment by xmatthias** [comment]
> ccxt documentation says that only a limited number of exchanges provide 'bid'/'ask' in the ticker structure, so those values from the tickers should not actually be used -- the orderbook info should be used instead.

the orderbook is empty too ... i did check that - so this again, moves the error simply to another spot.

```python
ct.fetch_l2_order_book('ABULABA/BTC', 20)
```

```
{'bids': [],
 'asks': [[1e-08, 6113894.97279021],
  [1.234e-08, 300.0],
  [1.499e-08, 224308.0],
  [1.5e-08, 100999.0],
  [2e-08, 55694.149],
  [3e-08, 10702.199],
  [4e-08, 2268.983],
  [5e-08, 275.0],
  [6e-08, 175.0],
  [6.969e-08, 200.0],
  [7e-08, 252.0],
  [8e-08, 18325.0],
  [9e-08, 1800.0],
  [9.696e-08, 200.0],
  [1e-07, 2125.0],
  [1.1212e-07, 35397.0],
  [1.2345e-07, 250.0],
  [1.5e-07, 2025.0],
  [1.9e-07, 2000.0],
  [2e-07, 75.4]],
 'timestamp': None,
 'datetime': None,
 'nonce': None}
```

> VolumePairlist should use orderbook info instead. 

this comment does not make sense. VolumePairList uses `get_tickers()` - not `get_ticker()` (singular)- which is at fault here. Also, it does not use 'bid' (nor 'ask') ... but 'quoteVolume'.
Also, orderbook can't tell you the last 24h volume - so how do you immagine that to work with orderbook ? 


I have a fix for this in mind - which will have the sideeffect of speeding up /balance ... it's dead slow once you start owning more than 5 currencies ...

**Comment by xephos1one** [comment]
The orderbook is empty but not none.
An empty array should not be a problem there? 🤔 

Great news! :)

**Comment by hroff-1902** [comment]
> The orderbook is empty but not none.
> An empty array should not be a problem there? 🤔

Exactly. 👍

**Comment by hroff-1902** [comment]
@xephos1one pls review the fix, 
it was merged to the develop branch, update your installation to have it working.

pls report back here

**Comment by xephos1one** [comment]
Working great 👍 
Thank you!

**Comment by xmatthias** [comment]
Thanks for checking :+1:
