### ISSUE TITLE
Issue with downloading data using --dl-trades argument

### ISSUE THREAD

**Issue by MelvinRabang** [freqtrade/freqtrade#2526]
## Step 1: Have you search for this issue before posting it?

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/freqtrade/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

  * Operating system: Ubuntu 18.04.3 (LTS) x64
  * Python Version: Python 2.7.15 (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Branch: Develop
  * Last Commit ID: baea06eac76b066c3a72857f4675570f23f8a6b2
  
## Step 3: Describe the problem:

I am not able to download the lasted data using the --dl-trades argument

### Steps to reproduce:

  1. Execute the command - source .env/bin/activate; nohup freqtrade download-data --exchange binance --days 20 --dl-trades
  
### Observed Results:

  * What happened?
The download thread stopped and exception logs appeared
  * What did you expect to happen?

### Relevant code exceptions or logs:
2019-11-13 18:14:01,910 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/root/freqtrade/.env/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2897, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'datetime'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/freqtrade/freqtrade/main.py", line 39, in main
    args['func'](args)
  File "/root/freqtrade/freqtrade/utils.py", line 105, in start_download_data
    datadir=Path(config['datadir']), timerange=timerange, erase=config.get("erase"))
  File "/root/freqtrade/freqtrade/data/history.py", line 442, in convert_trades_to_ohlcv
    ohlcv = trades_to_ohlcv(trades, timeframe)
  File "/root/freqtrade/freqtrade/data/converter.py", line 129, in trades_to_ohlcv
    df['datetime'] = pd.to_datetime(df['datetime'])
  File "/root/freqtrade/.env/lib/python3.6/site-packages/pandas/core/frame.py", line 2995, in __getitem__
   df['datetime'] = pd.to_datetime(df['datetime'])
  File "/root/freqtrade/.env/lib/python3.6/site-packages/pandas/core/frame.py", line 2995, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/root/freqtrade/.env/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2899, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'datetime'

**Comment by xmatthias** [comment]
why are you using `--dl-trades` when you're using binance?

it's unnecessarily slow and is supposed to be a workaround for Kraken (since kraken does not provide "proper" ohlcv data for a longer period of time.

**Comment by xmatthias** [comment]
I've now tried exactly your command - and it does work for me (i used XRP/ETH as a sample pair...).

I guess to verify what exactly happened we'll need the full output from the logs (maybe a pair in your whitelist is not available or so ...).

**Comment by hroff-1902** [comment]
@MelvinRabang pls provide the bot log output for this command produced on your system.

**Comment by MelvinRabang** [comment]
Hi Team. Sorry for the late reply. You are right, I should not use the --dd-trades argument when downloading data from binance. It is more faster.
