### ISSUE TITLE
kraken timeout crash

### ISSUE THREAD

**Issue by sanitariu** [freqtrade/freqtrade#2555]
Hello,
After updating to latest timeout fixes i had crash on kraken. Here is the log.

```
2019-11-20 08:25:42,695 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=5, pair=XTZ/BTC, amount=49.08835905, open_rate=0.00014260, open_since=2019-11-20 06:15:50)
2019-11-20 08:25:51,656 - freqtrade.utils - INFO - worker found ... calling exit
2019-11-20 08:25:51,656 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2019-11-20 08:25:51,714 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2019-11-20 08:25:51,714 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
2019-11-20 08:26:13,304 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/dri/miner/freqtrade/freqtrade/main.py", line 36, in main
    return_code = args['func'](args)
  File "/home/dri/miner/freqtrade/freqtrade/utils.py", line 51, in start_trading
    worker.run()
  File "/home/dri/miner/freqtrade/freqtrade/worker.py", line 71, in run
    state = self._worker(old_state=state)
  File "/home/dri/miner/freqtrade/freqtrade/worker.py", line 109, in _worker
    self._throttle(func=self._process, min_secs=throttle_secs)
  File "/home/dri/miner/freqtrade/freqtrade/worker.py", line 122, in _throttle
    result = func(*args, **kwargs)
  File "/home/dri/miner/freqtrade/freqtrade/worker.py", line 132, in _process
    self.freqtrade.process()
  File "/home/dri/miner/freqtrade/freqtrade/freqtradebot.py", line 143, in process
    self.check_handle_timedout()
  File "/home/dri/miner/freqtrade/freqtrade/freqtradebot.py", line 798, in check_handle_timedout
    self.handle_timedout_limit_buy(trade, order)
  File "/home/dri/miner/freqtrade/freqtrade/freqtradebot.py", line 828, in handle_timedout_limit_buy
    if corder['remaining'] == corder['amount']:
KeyError: 'remaining'
```

How i can help to fix this ?

**Comment by hroff-1902** [comment]
(Edited formatting)

**Comment by xmatthias** [comment]
Please fill out what version you're running.
Also, what version did you run previously (approximately) - when it was still working.

**Comment by sanitariu** [comment]
Hello,
i am running latest version. Unfortunately i do not remember my previous version but it was just before starting these timeout changes. I will continue watching the bot for next crash.

**Comment by xmatthias** [comment]
I'm not certain what you refer to with "these timeout changes" ... ? 

when you say latest version, is it develop? or master (latest official release) ...

**Comment by sanitariu** [comment]
I am working using develop only. It was for sure before pull #2523 may be 1 week before that.
I am still waiting for new trade/crash to happen and will report it.

**Comment by xmatthias** [comment]
The key error seems to happen with `'remaining'` - 
We use "remaining" of the order before, so this can only come from the "cancel_order" response.

This line is only reached in one circumstance - if the order on the exchange is not filled, and times out (otherwise the error would have to happen at a different line).

I suspect that this case never happened before (it shouldn't happen too often ...) - so even having 100 trades with kraken may not mean that this case did happen before.

we should be able to handle this quite cleanly ....

**Comment by hroff-1902** [comment]
@sanitariu pls test the fix (merged to the current develop branch)

**Comment by sanitariu** [comment]
ok updating to latest dev
