### ISSUE TITLE
Telegram RPC connection Error 

### ISSUE THREAD

**Issue by baties** [freqtrade/freqtrade#2645]
## Step 1: Have you search for this issue before posting it?
Yes .

## Step 2: Describe your environment

  * Operating system: Linux  Ubuntu  18.04 LTS
  * Python Version: Python 3.6.9
  * CCXT version:  ccxt 1.20.44
  * Branch: Master 
  * Last Commit ID: 
  
## Step 3: Describe the problem:
I did every step base on FreqTrade documentation . 
Everything goes fine without problem .
But atlast when execute the FreqTrade it can not communicate with Telegram and show me the error :
Tekegram.error.Unauthorized : Unauthorized 
 
*Explain the problem you have encountered*
Telegram Communication Error with message Unauthorized .

### Steps to reproduce:

  1. Apt-get update
  2. Install git
  3. Download, Unpack  and make ta-lib
  4. Python3-venv & pip
  5. Install Freqtrade
  6. Update config.json
  7. Activate Virtual Envirionment
  8. Create a new Tekegram bot with Botfather
  9. Achieve my Telegram chat Id with ChatInfo bot
  10. Update config.json & Run Freqtrade
  
### Relevant code exceptions or logs:

  ```
2019-12-11 11:22:58,276 - freqtrade.loggers - INFO - Verbosity set to 0
2019-12-11 11:22:58,277 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2019-12-11 11:22:58,277 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite://"
2019-12-11 11:22:58,277 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 3 ...
2019-12-11 11:22:58,277 - freqtrade.configuration.configuration - INFO - Using user-data directory: /root/freqtrade/user_data ...
2019-12-11 11:22:58,277 - freqtrade.configuration.configuration - INFO - Using data directory: /root/freqtrade/user_data/data/binance ...
2019-12-11 11:22:58,278 - freqtrade.configuration.configuration - INFO - Runmode set to RunMode.DRY_RUN.
2019-12-11 11:22:58,278 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2019-12-11 11:22:58,278 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2019-12-11 11:22:58,278 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2019-12-11 11:22:58,278 - freqtrade.freqtradebot - INFO - Starting freqtrade 2019.10
2019-12-11 11:22:58,291 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy DefaultStrategy from '/root/freqtrade/freqtrade/strategy/default_strategy.py'...
2019-12-11 11:22:58,291 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ticker_interval' with value in config file: 5m.
2019-12-11 11:22:58,291 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'trailing_stop' with value in config file: False.
2019-12-11 11:22:58,291 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: BTC.
2019-12-11 11:22:58,291 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 0.05.
2019-12-11 11:22:58,291 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'use_sell_signal' with value in config file: True.
2019-12-11 11:22:58,291 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'sell_profit_only' with value in config file: False.
2019-12-11 11:22:58,292 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ignore_roi_if_buy_signal' with value in config file: False.
2019-12-11 11:22:58,292 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'40': 0.0, '30': 0.01, '20': 0.02, '0': 0.04}
2019-12-11 11:22:58,292 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ticker_interval: 5m
2019-12-11 11:22:58,292 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.1
2019-12-11 11:22:58,292 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2019-12-11 11:22:58,292 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2019-12-11 11:22:58,292 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2019-12-11 11:22:58,292 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
2019-12-11 11:22:58,292 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False}
2019-12-11 11:22:58,292 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
2019-12-11 11:22:58,292 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: BTC
2019-12-11 11:22:58,292 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 0.05
2019-12-11 11:22:58,292 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_sell_signal: True
2019-12-11 11:22:58,292 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_only: False
2019-12-11 11:22:58,292 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_buy_signal: False
2019-12-11 11:22:58,292 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2019-12-11 11:22:58,292 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2019-12-11 11:22:58,295 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 500}
2019-12-11 11:22:58,298 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2019-12-11 11:22:59,075 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2019-12-11 11:22:59,076 - freqtrade.wallets - INFO - Wallets synced.
2019-12-11 11:22:59,076 - freqtrade.resolvers.iresolver - WARNING - Path "/root/freqtrade/user_data/pairlist" does not exist.
2019-12-11 11:22:59,080 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from '/root/freqtrade/freqtrade/pairlist/StaticPairList.py'...
2019-12-11 11:22:59,092 - freqtrade.rpc.rpc_manager - INFO - Enabling rpc.telegram ...
2019-12-11 11:23:00,229 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/root/freqtrade/freqtrade/main.py", line 44, in main
    worker = Worker(args)
  File "/root/freqtrade/freqtrade/worker.py", line 34, in __init__
    self._init(False)
  File "/root/freqtrade/freqtrade/worker.py", line 50, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/root/freqtrade/freqtrade/freqtradebot.py", line 94, in __init__
    self.rpc: RPCManager = RPCManager(self)
  File "/root/freqtrade/freqtrade/rpc/rpc_manager.py", line 24, in __init__
    self.registered_modules.append(Telegram(freqtrade))
  File "/root/freqtrade/freqtrade/rpc/telegram.py", line 72, in __init__
    self._init()
  File "/root/freqtrade/freqtrade/rpc/telegram.py", line 111, in _init
    read_latency=60,
  File "/root/.env/lib/python3.6/site-packages/telegram/ext/updater.py", line 213, in start_polling
    self.job_queue.start()
  File "/root/.env/lib/python3.6/site-packages/telegram/ext/jobqueue.py", line 291, in start
    name="Bot:{}:job_queue".format(self._dispatcher.bot.id))
  File "/root/.env/lib/python3.6/site-packages/telegram/bot.py", line 52, in decorator
    self.get_me()
  File "/root/.env/lib/python3.6/site-packages/telegram/bot.py", line 66, in decorator
    result = func(self, *args, **kwargs)
  File "/root/.env/lib/python3.6/site-packages/telegram/bot.py", line 199, in get_me
    result = self._request.get(url, timeout=timeout)
  File "/root/.env/lib/python3.6/site-packages/telegram/utils/request.py", line 270, in get
    result = self._request_wrapper('GET', url, **urlopen_kwargs)
  File "/root/.env/lib/python3.6/site-packages/telegram/utils/request.py", line 236, in _request_wrapper
    raise Unauthorized(message)
telegram.error.Unauthorized: Unauthorized

  ```

**Comment by xmatthias** [comment]
well the error is quite clear - The telegram servers tell your bot that it's not authorized, which suggests a problem with either the chat_id or the token.

Best check both "token" and "chat_id" for correctness - make sure there are no leading / trailing spaces between the quotes (") ...

Note: 
`token` should be in the format of `22222222:APITOKEN` ... (numbers / letters will be different and might be longer).
`chat_id` on the other hand is the ID of your user-account. as documented [here](https://www.freqtrade.io/en/latest/telegram-usage/#2-get-your-user-id) - you need to send a message to the userinfobot, which will return a number.

**Comment by baties** [comment]
> well the error is quite clear - The telegram servers tell your bot that it's not authorized, which suggests a problem with either the chat_id or the token.
> 
> Best check both "token" and "chat_id" for correctness - make sure there are no leading / trailing spaces between the quotes (") ...
> 
> Note:
> `token` should be in the format of `22222222:APITOKEN` ... (numbers / letters will be different and might be longer).
> `chat_id` on the other hand is the ID of your user-account. as documented [here](https://www.freqtrade.io/en/latest/telegram-usage/#2-get-your-user-id) - you need to send a message to the userinfobot, which will return a number.

Yes, I did exactly as the document says . 
Although I check my bot token and my chat id several times , but the problem exists .
And there is no extra space in chat Id or bot token .

**Comment by hroff-1902** [comment]
Have not you mistaken an O with a zero in the token / chat_id, for example? Have you transferred these values manually or copy-pasted from an e-mail as is or another media?

**Comment by hroff-1902** [comment]
you can verify token in the python interpreter:
```
>>> import telegram
>>> bot = telegram.Bot(token='TOKEN')
>>> print(bot.get_me())
{"first_name": "Toledo's Palace Bot", "username": "ToledosPalaceBot"}
```
(taken from here: https://github.com/python-telegram-bot/python-telegram-bot/wiki/Introduction-to-the-API)

**Comment by xmatthias** [comment]
Just tried that code snippet - if i use a wrong token it returns the same error than it does for you - Unauthorized.

@hroff-1902 we should add this to the docs

**Comment by baties** [comment]
> Have not you mistaken an O with a zero in the token / chat_id, for example? Have you transferred these values manually or copy-pasted from an e-mail as is or another media?

No, copy & paste

**Comment by xmatthias** [comment]
Did you try the above code with your token ? if it works with the telegram library itself it'll work with freqtrade too - otherwise please have the botfather spit out a new apikey ... and try again with that new key.

**Comment by baties** [comment]
Thank you every body
I created a new bot and the problem was solved

**Comment by OuttaSpaceTime** [comment]
for me it helped to revoke the api token and copy the new one to the config
