### ISSUE TITLE
Hyperopt runtime error in latest develop branch

### ISSUE THREAD

**Issue by MelvinRabang** [freqtrade/freqtrade#2707]
## Step 1: Have you search for this issue before posting it?
No

## Step 2: Describe your environment

Operating system: Ubuntu 18.04.3 (LTS) x64
Python Version: Python 2.7.15 (python -V)
CCXT version: _____ (pip freeze | grep ccxt)
Branch: Develop
Last Commit ID: 506907dd
  
## Step 3: Describe the problem:

An exception occurs when I run the hyperopt command

### Steps to reproduce:

  1. Run the command - source .env/bin/activate; freqtrade hyperopt --config config.json --hyperopt SomeHyperOpt --hyperopt-loss SharpeHyperOptLoss -e 5000 --spaces all --strategy SomeStrategy --timerange 20191023-20191223
  
### Observed Results:

  * What happened?
I am not able to run hyperopt since an exception occured
  * What did you expect to happen?
I expected hyperopt to run

### Relevant code exceptions or logs:

"""
Traceback (most recent call last):
  File "/root/freqtrade/.env/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 418, in _process_worker
    r = call_item()
  File "/root/freqtrade/.env/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 272, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/root/freqtrade/.env/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 600, in __call__
    return self.func(*args, **kwargs)
  File "/root/freqtrade/.env/lib/python3.6/site-packages/joblib/parallel.py", line 256, in __call__
    for func, args, kwargs in self.items]
  File "/root/freqtrade/.env/lib/python3.6/site-packages/joblib/parallel.py", line 256, in <listcomp>
    for func, args, kwargs in self.items]
  File "/root/freqtrade/.env/lib/python3.6/site-packages/joblib/externals/loky/cloudpickle_wrapper.py", line 38, in __call__
    return self._obj(*args, **kwargs)
  File "/root/freqtrade/freqtrade/optimize/hyperopt.py", line 381, in generate_optimizer
    'end_date': max_date,
  File "/root/freqtrade/freqtrade/optimize/backtesting.py", line 441, in backtest
    max_open_trades)
  File "/root/freqtrade/freqtrade/optimize/backtesting.py", line 313, in _get_sell_trade_entry
    amount=stake_amount / buy_row.open,
TypeError: unsupported operand type(s) for /: 'str' and 'float'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/freqtrade/freqtrade/main.py", line 36, in main
    return_code = args['func'](args)
  File "/root/freqtrade/freqtrade/optimize/__init__.py", line 76, in start_hyperopt
    hyperopt.start()
  File "/root/freqtrade/freqtrade/optimize/hyperopt.py", line 524, in start
    f_val = self.run_optimizer_parallel(parallel, asked, i)
  File "/root/freqtrade/freqtrade/optimize/hyperopt.py", line 462, in run_optimizer_parallel
    wrap_non_picklable_objects(self.generate_optimizer))(v, i) for v in asked)
  File "/root/freqtrade/.env/lib/python3.6/site-packages/joblib/parallel.py", line 1016, in __call__
    self.retrieve()
  File "/root/freqtrade/.env/lib/python3.6/site-packages/joblib/parallel.py", line 908, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/root/freqtrade/.env/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 554, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
TypeError: unsupported operand type(s) for /: 'str' and 'float'

**Comment by MelvinRabang** [comment]
N
