### ISSUE TITLE
KeyError: 'sell' when running a strategy in dry-run

### ISSUE THREAD

**Issue by rabinhod** [freqtrade/freqtrade#2753]
I want to run my first Strategy on Dry run but it get fatal error !

> (.env) dream@dream-VirtualBox:~/Desktop/B/freqtrade$ freqtrade trade --strategy S4
2020-01-07 18:17:15,184 - freqtrade.loggers - INFO - Verbosity set to 0
2020-01-07 18:17:15,185 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2020-01-07 18:17:15,185 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite://"
2020-01-07 18:17:15,186 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 3 ...
2020-01-07 18:17:15,186 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/dream/Desktop/B/freqtrade/user_data ...
2020-01-07 18:17:15,187 - freqtrade.configuration.configuration - INFO - Using data directory: /home/dream/Desktop/B/freqtrade/user_data/data/binance ...
2020-01-07 18:17:15,188 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2020-01-07 18:17:15,188 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2020-01-07 18:17:15,189 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2020-01-07 18:17:15,189 - freqtrade.freqtradebot - INFO - Starting freqtrade 2019.11
2020-01-07 18:17:15,204 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy S4 from '/home/dream/Desktop/B/freqtrade/user_data/strategies/S4.py'...
2020-01-07 18:17:15,204 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ticker_interval' with value in config file: 6h.
2020-01-07 18:17:15,205 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'trailing_stop' with value in config file: True.
2020-01-07 18:17:15,205 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'trailing_stop_positive' with value in config file: 0.01.
2020-01-07 18:17:15,205 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'trailing_stop_positive_offset' with value in config file: 0.11.
2020-01-07 18:17:15,205 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: BTC.
2020-01-07 18:17:15,205 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 0.05.
2020-01-07 18:17:15,206 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'use_sell_signal' with value in config file: True.
2020-01-07 18:17:15,206 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'sell_profit_only' with value in config file: False.
2020-01-07 18:17:15,206 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ignore_roi_if_buy_signal' with value in config file: False.
2020-01-07 18:17:15,206 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 100}
2020-01-07 18:17:15,206 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ticker_interval: 6h
2020-01-07 18:17:15,206 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.1
2020-01-07 18:17:15,207 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: True
2020-01-07 18:17:15,207 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive: 0.01
2020-01-07 18:17:15,207 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.11
2020-01-07 18:17:15,207 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2020-01-07 18:17:15,207 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
2020-01-07 18:17:15,207 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False, 'stoploss_on_exchange_interval': 60}
2020-01-07 18:17:15,208 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
2020-01-07 18:17:15,208 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: BTC
2020-01-07 18:17:15,208 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 0.05
2020-01-07 18:17:15,208 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 0
2020-01-07 18:17:15,208 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_sell_signal: True
2020-01-07 18:17:15,208 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_only: False
2020-01-07 18:17:15,209 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_buy_signal: False
2020-01-07 18:17:15,209 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2020-01-07 18:17:15,213 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2020-01-07 18:17:15,213 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2020-01-07 18:17:15,219 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 500}
2020-01-07 18:17:15,225 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2020-01-07 18:17:22,364 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2020-01-07 18:17:22,364 - freqtrade.wallets - INFO - Wallets synced.
2020-01-07 18:17:22,396 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from '/home/dream/Desktop/B/freqtrade/freqtrade/pairlist/StaticPairList.py'...
2020-01-07 18:17:22,458 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'running'}
2020-01-07 18:17:22,458 - freqtrade.worker - INFO - Changing state to: RUNNING
2020-01-07 18:17:22,458 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': warning, 'status': 'Dry run is enabled. All trades are simulated.'}
2020-01-07 18:17:22,458 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': custom, 'status': "*Exchange:* `binance`\n*Stake per trade:* `0.05 BTC`\n*Minimum ROI:* `{'0': 100}`\n*Trailing Stoploss:* `-0.1`\n*Ticker Interval:* `6h`\n*Strategy:* `S4`"}
2020-01-07 18:17:22,459 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': "Searching for BTC pairs to buy and sell based on [{'StaticPairList': 'StaticPairList'}]"}
2020-01-07 18:17:28,169 - freqtrade.utils - INFO - worker found ... calling exit
2020-01-07 18:17:28,169 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2020-01-07 18:17:28,169 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2020-01-07 18:17:28,169 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
2020-01-07 18:17:28,170 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/dream/Desktop/B/.env/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 4736, in get_value
    return libindex.get_value_box(s, key)
  File "pandas/_libs/index.pyx", line 51, in pandas._libs.index.get_value_box
  File "pandas/_libs/index.pyx", line 47, in pandas._libs.index.get_value_at
  File "pandas/_libs/util.pxd", line 98, in pandas._libs.util.get_value_at
  File "pandas/_libs/util.pxd", line 83, in pandas._libs.util.validate_indexer
TypeError: 'str' object cannot be interpreted as an integer

> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/dream/Desktop/B/freqtrade/freqtrade/main.py", line 36, in main
>     return_code = args['func'](args)
>   File "/home/dream/Desktop/B/freqtrade/freqtrade/utils.py", line 56, in start_trading
>     worker.run()
>   File "/home/dream/Desktop/B/freqtrade/freqtrade/worker.py", line 71, in run
>     state = self._worker(old_state=state)
>   File "/home/dream/Desktop/B/freqtrade/freqtrade/worker.py", line 109, in _worker
>     self._throttle(func=self._process, min_secs=throttle_secs)
>   File "/home/dream/Desktop/B/freqtrade/freqtrade/worker.py", line 122, in _throttle
>     result = func(*args, **kwargs)
>   File "/home/dream/Desktop/B/freqtrade/freqtrade/worker.py", line 132, in _process
>     self.freqtrade.process()
>   File "/home/dream/Desktop/B/freqtrade/freqtrade/freqtradebot.py", line 139, in process
>     self.process_maybe_execute_buys()
>   File "/home/dream/Desktop/B/freqtrade/freqtrade/freqtradebot.py", line 458, in process_maybe_execute_buys
>     if not self.create_trades():
>   File "/home/dream/Desktop/B/freqtrade/freqtrade/freqtradebot.py", line 308, in create_trades
>     self.dataprovider.ohlcv(_pair, self.strategy.ticker_interval))
>   File "/home/dream/Desktop/B/freqtrade/freqtrade/strategy/interface.py", line 276, in get_signal
>     (buy, sell) = latest[SignalType.BUY.value] == 1, latest[SignalType.SELL.value] == 1
>   File "/home/dream/Desktop/B/.env/lib/python3.6/site-packages/pandas/core/series.py", line 1071, in __getitem__
>     result = self.index.get_value(self, key)
>   File "/home/dream/Desktop/B/.env/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 4744, in get_value
>     raise e1
>   File "/home/dream/Desktop/B/.env/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 4730, in get_value
>     return self._engine.get_value(s, k, tz=getattr(series.dtype, "tz", None))
>   File "pandas/_libs/index.pyx", line 80, in pandas._libs.index.IndexEngine.get_value
>   File "pandas/_libs/index.pyx", line 88, in pandas._libs.index.IndexEngine.get_value
>   File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
>   File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
>   File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
> KeyError: 'sell'
> (.env) dream@dream-VirtualBox:~/Desktop/B/freqtrade$ freqtrade trade --strategy S4
> 2020-01-07 18:18:22,476 - freqtrade.loggers - INFO - Verbosity set to 0
> 2020-01-07 18:18:22,477 - freqtrade.configuration.configuration - INFO - Dry run is enabled
> 2020-01-07 18:18:22,477 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite://"
> 2020-01-07 18:18:22,477 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 3 ...
> 2020-01-07 18:18:22,477 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/dream/Desktop/B/freqtrade/user_data ...
> 2020-01-07 18:18:22,477 - freqtrade.configuration.configuration - INFO - Using data directory: /home/dream/Desktop/B/freqtrade/user_data/data/binance ...
> 2020-01-07 18:18:22,478 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
> 2020-01-07 18:18:22,478 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
> 2020-01-07 18:18:22,478 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
> 2020-01-07 18:18:22,478 - freqtrade.freqtradebot - INFO - Starting freqtrade 2019.11
> 2020-01-07 18:18:22,488 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy S4 from '/home/dream/Desktop/B/freqtrade/user_data/strategies/S4.py'...
> 2020-01-07 18:18:22,488 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ticker_interval' with value in config file: 6h.
> 2020-01-07 18:18:22,488 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'trailing_stop' with value in config file: True.
> 2020-01-07 18:18:22,488 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'trailing_stop_positive' with value in config file: 0.01.
> 2020-01-07 18:18:22,488 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'trailing_stop_positive_offset' with value in config file: 0.11.
> 2020-01-07 18:18:22,488 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: BTC.
> 2020-01-07 18:18:22,488 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 0.05.
> 2020-01-07 18:18:22,489 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'use_sell_signal' with value in config file: True.
> 2020-01-07 18:18:22,489 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'sell_profit_only' with value in config file: False.
> 2020-01-07 18:18:22,489 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ignore_roi_if_buy_signal' with value in config file: False.
> 2020-01-07 18:18:22,489 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 100}
> 2020-01-07 18:18:22,489 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ticker_interval: 6h
> 2020-01-07 18:18:22,489 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.1
> 2020-01-07 18:18:22,489 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: True
> 2020-01-07 18:18:22,489 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive: 0.01
> 2020-01-07 18:18:22,489 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.11
> 2020-01-07 18:18:22,489 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
> 2020-01-07 18:18:22,489 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
> 2020-01-07 18:18:22,489 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False, 'stoploss_on_exchange_interval': 60}
> 2020-01-07 18:18:22,489 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
> 2020-01-07 18:18:22,489 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: BTC
> 2020-01-07 18:18:22,489 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 0.05
> 2020-01-07 18:18:22,489 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 0
> 2020-01-07 18:18:22,489 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_sell_signal: True
> 2020-01-07 18:18:22,489 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_only: False
> 2020-01-07 18:18:22,489 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_buy_signal: False
> 2020-01-07 18:18:22,489 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
> 2020-01-07 18:18:22,491 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
> 2020-01-07 18:18:22,492 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
> 2020-01-07 18:18:22,494 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 500}
> 2020-01-07 18:18:22,498 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
> 2020-01-07 18:18:24,736 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
> 2020-01-07 18:18:24,736 - freqtrade.wallets - INFO - Wallets synced.
> 2020-01-07 18:18:24,738 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from '/home/dream/Desktop/B/freqtrade/freqtrade/pairlist/StaticPairList.py'...
> 2020-01-07 18:18:24,747 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'running'}
> 2020-01-07 18:18:24,748 - freqtrade.worker - INFO - Changing state to: RUNNING
> 2020-01-07 18:18:24,748 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': warning, 'status': 'Dry run is enabled. All trades are simulated.'}
> 2020-01-07 18:18:24,748 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': custom, 'status': "*Exchange:* `binance`\n*Stake per trade:* `0.05 BTC`\n*Minimum ROI:* `{'0': 100}`\n*Trailing Stoploss:* `-0.1`\n*Ticker Interval:* `6h`\n*Strategy:* `S4`"}
> 2020-01-07 18:18:24,748 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': "Searching for BTC pairs to buy and sell based on [{'StaticPairList': 'StaticPairList'}]"}
> 2020-01-07 18:18:27,432 - freqtrade.utils - INFO - worker found ... calling exit
> 2020-01-07 18:18:27,432 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
> 2020-01-07 18:18:27,432 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
> 2020-01-07 18:18:27,432 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
> 2020-01-07 18:18:27,432 - freqtrade - ERROR - Fatal exception!
> Traceback (most recent call last):
>   File "/home/dream/Desktop/B/.env/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 4736, in get_value
>     return libindex.get_value_box(s, key)
>   File "pandas/_libs/index.pyx", line 51, in pandas._libs.index.get_value_box
>   File "pandas/_libs/index.pyx", line 47, in pandas._libs.index.get_value_at
>   File "pandas/_libs/util.pxd", line 98, in pandas._libs.util.get_value_at
>   File "pandas/_libs/util.pxd", line 83, in pandas._libs.util.validate_indexer
> TypeError: 'str' object cannot be interpreted as an integer
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/dream/Desktop/B/freqtrade/freqtrade/main.py", line 36, in main
>     return_code = args['func'](args)
>   File "/home/dream/Desktop/B/freqtrade/freqtrade/utils.py", line 56, in start_trading
>     worker.run()
>   File "/home/dream/Desktop/B/freqtrade/freqtrade/worker.py", line 71, in run
>     state = self._worker(old_state=state)
>   File "/home/dream/Desktop/B/freqtrade/freqtrade/worker.py", line 109, in _worker
>     self._throttle(func=self._process, min_secs=throttle_secs)
>   File "/home/dream/Desktop/B/freqtrade/freqtrade/worker.py", line 122, in _throttle
>     result = func(*args, **kwargs)
>   File "/home/dream/Desktop/B/freqtrade/freqtrade/worker.py", line 132, in _process
>     self.freqtrade.process()
>   File "/home/dream/Desktop/B/freqtrade/freqtrade/freqtradebot.py", line 139, in process
>     self.process_maybe_execute_buys()
>   File "/home/dream/Desktop/B/freqtrade/freqtrade/freqtradebot.py", line 458, in process_maybe_execute_buys
>     if not self.create_trades():
>   File "/home/dream/Desktop/B/freqtrade/freqtrade/freqtradebot.py", line 308, in create_trades
>     self.dataprovider.ohlcv(_pair, self.strategy.ticker_interval))
>   File "/home/dream/Desktop/B/freqtrade/freqtrade/strategy/interface.py", line 276, in get_signal
>     (buy, sell) = latest[SignalType.BUY.value] == 1, latest[SignalType.SELL.value] == 1
>   File "/home/dream/Desktop/B/.env/lib/python3.6/site-packages/pandas/core/series.py", line 1071, in __getitem__
>     result = self.index.get_value(self, key)
>   File "/home/dream/Desktop/B/.env/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 4744, in get_value
>     raise e1
>   File "/home/dream/Desktop/B/.env/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 4730, in get_value
>     return self._engine.get_value(s, k, tz=getattr(series.dtype, "tz", None))
>   File "pandas/_libs/index.pyx", line 80, in pandas._libs.index.IndexEngine.get_value
>   File "pandas/_libs/index.pyx", line 88, in pandas._libs.index.IndexEngine.get_value
>   File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
>   File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
>   File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
> KeyError: 'sell'
> (.env) dream@dream-VirtualBox:~/Desktop/B/freqtrade$ 
>

**Comment by xmatthias** [comment]
well it seems like the strategy does not add a 'sell' column ...

Adding this is a requirement even if the sell-signal itself is not used (use `dataframe['sell'] = 0`, or set `use_sell_signal=False`) ... but the column needs to be populated nonetheless.
