### ISSUE TITLE
Dataload - the document is empty

### ISSUE THREAD

**Issue by gitgitgat** [freqtrade/freqtrade#2820]
It shows a `rapidjson.JSONDecodeError: Parse error at offset 0: The document is empty`. Looked at the files and everything seemed fine.

```
2020-01-29 19:05:52,919 - freqtrade.resolvers.iresolver - INFO - Using resolved hyperopt TestHyperOpts from '/home/cable/.things/freqtrade/user_data/hyperopts/test_hyperopts.py'...
2020-01-29 19:05:52,922 - freqtrade.resolvers.iresolver - INFO - Using resolved hyperoptloss DefaultHyperOptLoss from '/home/cable/.things/freqtrade/freqtrade/optimize/default_hyperopt_loss.py'...
2020-01-29 19:05:52,922 - freqtrade.optimize.hyperopt - INFO - Using optimizer random state: 28393
2020-01-29 19:05:52,922 - freqtrade.data.history - INFO - Using indicator startup period: 20 ...
2020-01-29 19:05:54,000 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/user/.things/freqtrade/freqtrade/main.py", line 36, in main
    return_code = args['func'](args)
  File "/home/user/.things/freqtrade/freqtrade/commands/optimize_commands.py", line 76, in start_hyperopt
    hyperopt.start()
  File "/home/user/.things/freqtrade/freqtrade/optimize/hyperopt.py", line 484, in start
    data, timerange = self.backtesting.load_bt_data()
  File "/home/user/.things/freqtrade/freqtrade/optimize/backtesting.py", line 119, in load_bt_data
    fail_without_data=True,
  File "/home/user/.things/freqtrade/freqtrade/data/history.py", line 197, in load_data
    startup_candles=startup_candles)
  File "/home/user/.things/freqtrade/freqtrade/data/history.py", line 153, in load_pair_history
    pairdata = load_tickerdata_file(datadir, pair, timeframe, timerange=timerange_startup)
  File "/home/user/.things/freqtrade/freqtrade/data/history.py", line 79, in load_tickerdata_file
    pairdata = misc.file_load_json(filename)
  File "/home/user/.things/freqtrade/freqtrade/misc.py", line 87, in file_load_json
    pairdata = json_load(tickerdata)
  File "/home/user/.things/freqtrade/freqtrade/misc.py", line 70, in json_load
    return rapidjson.load(datafile, number_mode=rapidjson.NM_NATIVE)
rapidjson.JSONDecodeError: Parse error at offset 0: The document is empty.
```

**Comment by xmatthias** [comment]
well no - one of the files will have a size of 0 - the message clearly states this.

**Comment by gitgitgat** [comment]
Ok, I am trying to run 'freqtrade hyperopt'. the user_data/hyperopt hyperopt file is there, so is the user_data/strategy file, and the data in 'user_data/data/exchange' and pairs.json

**Comment by xmatthias** [comment]
one of the files in `user_data/data/<exchange>` is empty. It's present - but has a size of 0 (or 1).

you should be able to check for his by using `ls user_data/data/exchange -lS` (note the capital S) - and looking at the last few files in this directory.

**Comment by gitgitgat** [comment]
okay

**Comment by gitgitgat** [comment]
it is '2020-01-29 21:23:40,217 - freqtrade.data.history - ERROR - Failed to download history data for pair: "NANO/BTC", timeframe: 15m. Error: Parse error at offset 0: The document is empty.' although the pair is my config.json file and pairs.json

**Comment by gitgitgat** [comment]
it is only the 15m ticker that is causing that, all the others seem fine

**Comment by xmatthias** [comment]
please remove the file with a size of 0 (`rm user_data/data/<your exchange>/NANO_BTC-15m.json`).

download-data will also try to open the file so it can eventually append to the file.

It's the first time i'm seing a 0 sized file - i don't know for sure what circumstances must happen to create one - but i think #2719  should eliminate that as the method to load data is different.

**Comment by gitgitgat** [comment]
I already deleted it and re-downloaded and it once again downloads a file with size 0, just for that pair in the 15m ticker

**Comment by xmatthias** [comment]
Then there's probably something wrong with the exchange you're using - 
Maybe you're blocked (which should be visible in the log messags during download)
or the selected time-range is wrong / too short?

I suspect it's the block tbh - since you've asked today on Slack about that. Make sure that the download succeeds. Using a VPN may also cause this (there's no guarantee the VPN IP address is not also blocked).

Short term - best exclude this pair and try re-downloading once you either have another IP address - or the exchange "forgot" about you. Even though they may allow you back to their API - strickter rules than usual will almost for sure still apply, resulting in quicker bans as that IP is on the "warning list".


Since the (mandatory) issue template has not been filled out - this is wasting everyones time (now it's another back and forth just to determine what exchange you may be using).  
I'll soon start closing issues if the template is not filled out.
