### ISSUE TITLE
Error when trying to run hyperopt

### ISSUE THREAD

**Issue by King-Techno** [freqtrade/freqtrade#2842]
When i try to run hyperopt using `freqtrade hyperopt --config config.json --hyperopt bbADXRSIopt  --timerange 20190810-20191201 -e 100 --spaces all` I am asked to add a strategy , which I do.

`freqtrade hyperopt --config config.json --hyperopt bbADXRSIopt --strategy bbADXRSI --timerange 20190810-20191201 -e 100 --spaces all` I expected this to cause an error as my custom strategy will conflict with my custom hyperopt. 

After running this command I am getting the error:

(I have put ** ** around the key errors). I just can not see why it is saying there is an issue with     `dataframe['bb_middleband1'] = bollinger1['middle']`in my hyperopt code. 

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/charleselegbede/freqtrade/freqtrade/main.py", line 36, in main
    return_code = args['func'](args)
  File "/Users/charleselegbede/freqtrade/freqtrade/commands/optimize_commands.py", line 76, in start_hyperopt
    hyperopt.start()
  File "/Users/charleselegbede/freqtrade/freqtrade/optimize/hyperopt.py", line 487, in start
    preprocessed = self.backtesting.strategy.tickerdata_to_dataframe(data)
  File "/Users/charleselegbede/freqtrade/freqtrade/strategy/interface.py", line 448, in tickerdata_to_dataframe
    for pair, pair_data in tickerdata.items()}
  File "/Users/charleselegbede/freqtrade/freqtrade/strategy/interface.py", line 448, in <dictcomp>
    for pair, pair_data in tickerdata.items()}
  **File "/Users/charleselegbede/freqtrade/freqtrade/optimize/bbADXRSI_hyperopt.py", line 38, in populate_indicators
    dataframe['bb_middleband1'] = bollinger1['middle']**
  File "/Users/charleselegbede/freqtrade/.env/lib/python3.7/site-packages/pandas/core/frame.py", line 2995, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/Users/charleselegbede/freqtrade/.env/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2899, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
**KeyError: 'middle'**
```

**Comment by King-Techno** [comment]
I think I know the issue, i am meant to use mid instead of middle
