### ISSUE TITLE
Error in custom hyperopt code

### ISSUE THREAD

**Issue by gitgitgat** [freqtrade/freqtrade#2852]
Ubuntu 18.04 LTS
Python 3.6.8
ccxt==1.21.91
Develop
d40054b9d2c5b4bb8c15a161cf78e0501c91f657

```
2020-02-03 16:30:25,401 - freqtrade - ERROR - Fatal exception!
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/freqtrade/.env/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 418, in _process_worker
    r = call_item()
  File "/home/freqtrade/.env/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 272, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/freqtrade/.env/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 608, in __call__
    return self.func(*args, **kwargs)
  File "/home/freqtrade/.env/lib/python3.6/site-packages/joblib/parallel.py", line 256, in __call__
    for func, args, kwargs in self.items]
  File "/home/freqtrade/.env/lib/python3.6/site-packages/joblib/parallel.py", line 256, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/freqtrade/.env/lib/python3.6/site-packages/joblib/externals/loky/cloudpickle_wrapper.py", line 38, in __call__
    return self._obj(*args, **kwargs)
  File "/home/freqtrade/freqtrade/optimize/hyperopt.py", line 380, in generate_optimizer
    position_stacking=self.position_stacking,
  File "/home/freqtrade/freqtrade/optimize/backtesting.py", line 308, in backtest
    ticker: Dict = self._get_ticker_list(processed)
  File "/home/freqtrade/freqtrade/optimize/backtesting.py", line 165, in _get_ticker_list
    self.strategy.advise_buy(pair_data, {'pair': pair}), {'pair': pair})[headers].copy()
  File "/home/freqtrade/user_data/hyperopts/test_hyperopts.py", line 103, in populate_buy_trend
    conditions.append(dataframe['fastd'] < params['fastd-value'])
  File "/home/freqtrade/.env/lib/python3.6/site-packages/pandas/core/ops/__init__.py", line 1229, in wrapper
    res = na_op(values, other)
  File "/home/freqtrade/.env/lib/python3.6/site-packages/pandas/core/ops/__init__.py", line 1091, in na_op
    result = _comp_method_OBJECT_ARRAY(op, x, y)
  File "/home/freqtrade/.env/lib/python3.6/site-packages/pandas/core/ops/__init__.py", line 1069, in _comp_method_OBJECT_ARRAY
    result = libops.scalar_compare(x, y, op)
  File "pandas/_libs/ops.pyx", line 96, in pandas._libs.ops.scalar_compare
TypeError: '>' not supported between instances of 'numpy.ndarray' and 'str'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/freqtrade/freqtrade/main.py", line 36, in main
    return_code = args['func'](args)
  File "/home/freqtrade/freqtrade/commands/optimize_commands.py", line 76, in start_hyperopt
    hyperopt.start()
  File "/home/freqtrade/freqtrade/optimize/hyperopt.py", line 522, in start
    f_val = self.run_optimizer_parallel(parallel, asked, i)
  File "/home/freqtrade/freqtrade/optimize/hyperopt.py", line 460, in run_optimizer_parallel
    wrap_non_picklable_objects(self.generate_optimizer))(v, i) for v in asked)
  File "/home/freqtrade/.env/lib/python3.6/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/home/freqtrade/.env/lib/python3.6/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/freqtrade/.env/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
TypeError: '>' not supported between instances of 'numpy.ndarray' and 'str'
```

**Comment by hroff-1902** [comment]
how do you define the 'fastd-value' dimension?

**Comment by gitgitgat** [comment]
It has not been changed from the hyperopt.py file that comes with freqtrade

**Comment by hroff-1902** [comment]
pls attach the full log along with the command you used.

**Comment by gitgitgat** [comment]
just pm in slack.

**Comment by hroff-1902** [comment]
he was using old test_hyperopt.py from some outdated version of freqtrade, which left in the user_data dir and was broken

closing it for now, it works well with actual sample hyperopt
