### ISSUE TITLE
Raspberry Pi 4 installation error

### ISSUE THREAD

**Issue by djacky** [freqtrade/freqtrade#2869]
## Step 1: Have you search for this issue before posting it?

Yes, no issues of this type have been reported here.

## Step 2: Describe your environment

  * Operating system: Raspbian Buster with desktop and recommended software (September 2019)
  * Python Version: 2.7.16 (`python -V`) - 3.7.3 (`python3 -V`)
  * CCXT version: can't access (`pip freeze | grep ccxt`)
  * Branch: Develop
  * Last Commit ID: b5ee4f17cb610cba273c2663112d6fe4f60154b9(`git log --format="%H" -n 1`)
  
## Step 3: Describe the problem:

Cannot install dependencies on Raspberry Pi 4. 
Per the installation instructions on [freqtrade.io](url), I executed the following commands:
```
sudo apt-get install python3-venv libatlas-base-dev
git clone https://github.com/freqtrade/freqtrade.git
cd freqtrade

bash setup.sh -i
```

However, the installation fails during the installations of scipy
`Building wheel for scipy (PEP 517) ... error`

See the logs for more details.

### Steps to reproduce:

Run the installation script for the Raspberry Pi 4 with the installation instructions on [freqtrade.io](url).
  
### Observed Results:

The installation just failed. 
It may be an error related to the path of gfortran since the error states the following: `error: library mach has Fortran sources but no Fortran compiler found`.

I have tried installing the dependencies:
```
pip install --upgrade pip
sudo apt-get install gfortran
sudo apt-get update
sudo apt-get install build-essential git

```

Some extra information:
```
which python --> /usr/bin/python
which python3 --> /usr/bin/python3
gfortran --version --> GNU Fortran (Raspbian 8.3.0-6+rpi1) 8.3.0
which gfortran --> /usr/bin/gfortran
which gfortran-8 --> /usr/bin/gfortran-8
```

### Relevant code exceptions or logs:

  ```
    Building wheel for scipy (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/pi/freqtrade/.env/bin/python3.7 /home/pi/freqtrade/.env/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpw5o7in96
       cwd: /tmp/pip-install-6d6xw5w1/scipy

...

building 'mach' library
  Running from scipy source directory.
  /tmp/pip-build-env-griud8en/overlay/lib/python3.7/site-packages/numpy/distutils/system_info.py:716: UserWarning: Specified path /tmp/pip-build-env-griud8en/overlay/include/python3.7m is invalid.
    return self.get_paths(self.section, key)
  /tmp/pip-build-env-griud8en/overlay/lib/python3.7/site-packages/numpy/distutils/system_info.py:716: UserWarning: Specified path /usr/local/include/python3.7m is invalid.
    return self.get_paths(self.section, key)
  /tmp/pip-build-env-griud8en/overlay/lib/python3.7/site-packages/numpy/distutils/system_info.py:716: UserWarning: Specified path /home/pi/freqtrade/.env/include/python3.7m is invalid.
    return self.get_paths(self.section, key)
  error: library mach has Fortran sources but no Fortran compiler found
  ----------------------------------------
  ERROR: Failed building wheel for scipy

Successfully built pandas
Failed to build scipy
ERROR: Could not build wheels for scipy which use PEP 517 and cannot be installed directly
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Obtaining file:///home/pi/freqtrade
    ERROR: Command errored out with exit status 1:

...

      File "/tmp/easy_install-vihn2rz2/numpy-1.18.1/setup.py", line 488, in <module>
      File "/tmp/easy_install-vihn2rz2/numpy-1.18.1/setup.py", line 469, in setup_package
      File "/tmp/easy_install-vihn2rz2/numpy-1.18.1/setup.py", line 275, in generate_cython
    RuntimeError: Running cythonize failed!
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

  ```

**Comment by xmatthias** [comment]
What was your answer to `Do you want to install dependencies for dev [y/N]?`?

For a raspberry, i'd recommend to answer with No, otherwise the "full" dependencies will be installed, including hyperopt. 
However - running hyperopt on a raspberry makes very limited (no?) sense.

We don't use scipy for anything other than hyperopt...
and scipy is not installed when answering with "N" (that's using `requirements.txt` - as opposed to `requirements-dev.txt`).

**Comment by hroff-1902** [comment]
made a proposal inspired by this issue: #2871

**Comment by djacky** [comment]
Thanks for the responses...
Whats interesting is that after the failed installation, I went into the virtual environment and then saw that `python --version = 3.7.3` (whereas outside of the virtual environment,` python --version = 2.7.16` and `python3 --version = 3.7.3`)...in the virtual environment, I was able to install all the packages in `requirement.txt`...so it seems that the installation points to python and not python3, and python3 is required to install the dependencies...

**Comment by djacky** [comment]
Since I fixed the issue, I will close for now...

**Comment by NecroJogn** [comment]
I might have faced similar problem. What were the steps to solve this? In a descriptive way a noob as myself would understand :D

**Comment by xmatthias** [comment]
@NecroJogn don't install hyperopt dependencies on a raspberry?

**Comment by NecroJogn** [comment]
Thanks for reply matthias! 
No, I haven't installed the hyperopt dependencies. But no matter what I try, I get the same red error text when installing Freqtrade. 
I followed another forum where various suggestions were up, installing cython, cmake etc, but in the end nothing works. I have tried this with Dietpi and the Raspberry OS. 
Have you tried installing Freqtrade on a Raspberry Pi from scratch recently? Could there be something in the latest updates that simply doesn't work?

**Comment by xmatthias** [comment]
@NecroJogn i suggest to open a new issue (with your error) - as it's very unlikely that you got the same error - as this one is about installing hyperopt dependencies.

**Comment by mathias5986** [comment]
@NecroJogn have you already opened a new issue ? I also cannot install freqtrade on my raspberry pi 4. After inserting "N" for "Do you want to install dependencies for dev [y/N]? " I get a red text with the following message:

-------------------------
Updating your virtual env
-------------------------
pip install in-progress. Please wait...
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pip
  Downloading https://files.pythonhosted.org/packages/cb/28/91f26bd088ce8e22169032100d4260614fc3da435025ff389ef1d396a433/pip-20.2.4-py2.py3-none-any.whl (1.5MB)
    100% |████████████████████████████████| 1.5MB 277kB/s 
Installing collected packages: pip
  Found existing installation: pip 18.1
    Uninstalling pip-18.1:
      Successfully uninstalled pip-18.1
Successfully installed pip-20.2.4
Do you want to install dependencies for dev [y/N]? N
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting numpy==1.19.4
  Downloading https://www.piwheels.org/simple/numpy/numpy-1.19.4-cp37-cp37m-linux_armv7l.whl (10.5 MB)
     |████████████████████████████████| 10.5 MB 22 kB/s 
Collecting pandas==1.1.4
  Downloading https://www.piwheels.org/simple/pandas/pandas-1.1.4-cp37-cp37m-linux_armv7l.whl (31.3 MB)
     |████████████████████████████████| 31.3 MB 10 kB/s 
Collecting ccxt==1.38.13
  Downloading ccxt-1.38.13-py2.py3-none-any.whl (1.9 MB)
     |████████████████████████████████| 1.9 MB 4.4 MB/s 
Collecting aiohttp==3.7.3
  Downloading https://www.piwheels.org/simple/aiohttp/aiohttp-3.7.3-cp37-cp37m-linux_armv7l.whl (1.3 MB)
     |████████████████████████████████| 1.3 MB 1.6 MB/s 
Collecting SQLAlchemy==1.3.20
  Downloading https://www.piwheels.org/simple/sqlalchemy/SQLAlchemy-1.3.20-cp37-cp37m-linux_armv7l.whl (1.3 MB)
     |████████████████████████████████| 1.3 MB 1.6 MB/s 
Collecting python-telegram-bot==13.0
  Downloading python_telegram_bot-13.0-py2.py3-none-any.whl (404 kB)
     |████████████████████████████████| 404 kB 4.0 MB/s 
Collecting arrow==0.17.0
  Downloading arrow-0.17.0-py2.py3-none-any.whl (50 kB)
     |████████████████████████████████| 50 kB 1.8 MB/s 
Collecting cachetools==4.1.1
  Downloading cachetools-4.1.1-py3-none-any.whl (10 kB)
Collecting requests==2.25.0
  Downloading requests-2.25.0-py2.py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 2.3 MB/s 
Collecting urllib3==1.26.2
  Downloading urllib3-1.26.2-py2.py3-none-any.whl (136 kB)
     |████████████████████████████████| 136 kB 4.5 MB/s 
Collecting wrapt==1.12.1
  Downloading https://www.piwheels.org/simple/wrapt/wrapt-1.12.1-cp37-cp37m-linux_armv7l.whl (68 kB)
     |████████████████████████████████| 68 kB 1.2 MB/s 
Collecting jsonschema==3.2.0
  Downloading jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)
     |████████████████████████████████| 56 kB 1.7 MB/s 
Collecting TA-Lib==0.4.19
  Downloading TA-Lib-0.4.19.tar.gz (267 kB)
     |████████████████████████████████| 267 kB 4.6 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /home/pi/freqtrade/.env/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2b2ke7zi/ta-lib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2b2ke7zi/ta-lib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-1s9vf_sw
         cwd: /tmp/pip-install-2b2ke7zi/ta-lib/
    Complete output (95 lines):
    Processing numpy/random/_bounded_integers.pxd.in
    Processing numpy/random/_pcg64.pyx
    Traceback (most recent call last):
      File "/tmp/easy_install-4eb9z40p/numpy-1.19.4/tools/cythonize.py", line 59, in process_pyx
        from Cython.Compiler.Version import version as cython_version
    ModuleNotFoundError: No module named 'Cython'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/easy_install-4eb9z40p/numpy-1.19.4/tools/cythonize.py", line 235, in <module>
        main()
      File "/tmp/easy_install-4eb9z40p/numpy-1.19.4/tools/cythonize.py", line 231, in main
        find_process_files(root_dir)
      File "/tmp/easy_install-4eb9z40p/numpy-1.19.4/tools/cythonize.py", line 222, in find_process_files
        process(root_dir, fromfile, tofile, function, hash_db)
      File "/tmp/easy_install-4eb9z40p/numpy-1.19.4/tools/cythonize.py", line 188, in process
        processor_function(fromfile, tofile)
      File "/tmp/easy_install-4eb9z40p/numpy-1.19.4/tools/cythonize.py", line 64, in process_pyx
        raise OSError('Cython needs to be installed in Python as a module')
    OSError: Cython needs to be installed in Python as a module
    Cythonizing sources
    Running from numpy source directory.
    /tmp/easy_install-4eb9z40p/numpy-1.19.4/setup.py:480: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      run_build = parse_setuppy_commands()
    Traceback (most recent call last):
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-4eb9z40p/numpy-1.19.4/setup.py", line 508, in <module>
      File "/tmp/easy_install-4eb9z40p/numpy-1.19.4/setup.py", line 488, in setup_package
      File "/tmp/easy_install-4eb9z40p/numpy-1.19.4/setup.py", line 285, in generate_cython
    RuntimeError: Running cythonize failed!
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-2b2ke7zi/ta-lib/setup.py", line 170, in <module>
        **requires)
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/dist.py", line 724, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
        replace_conflicting=replace_conflicting
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/dist.py", line 791, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 704, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 730, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 915, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 1183, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 1169, in run_setup
        run_setup(setup_script, args)
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/_vendor/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-4eb9z40p/numpy-1.19.4/setup.py", line 508, in <module>
      File "/tmp/easy_install-4eb9z40p/numpy-1.19.4/setup.py", line 488, in setup_package
      File "/tmp/easy_install-4eb9z40p/numpy-1.19.4/setup.py", line 285, in generate_cython
    RuntimeError: Running cythonize failed!
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Dev dependencies ignored.
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Obtaining file:///home/pi/freqtrade
    ERROR: Command errored out with exit status 1:
     command: /home/pi/freqtrade/.env/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/pi/freqtrade/setup.py'"'"'; __file__='"'"'/home/pi/freqtrade/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-a2habhhb
         cwd: /home/pi/freqtrade/
    Complete output (95 lines):
    Processing numpy/random/_bounded_integers.pxd.in
    Processing numpy/random/_pcg64.pyx
    Traceback (most recent call last):
      File "/tmp/easy_install-_le94fqy/numpy-1.19.4/tools/cythonize.py", line 59, in process_pyx
        from Cython.Compiler.Version import version as cython_version
    ModuleNotFoundError: No module named 'Cython'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/easy_install-_le94fqy/numpy-1.19.4/tools/cythonize.py", line 235, in <module>
        main()
      File "/tmp/easy_install-_le94fqy/numpy-1.19.4/tools/cythonize.py", line 231, in main
        find_process_files(root_dir)
      File "/tmp/easy_install-_le94fqy/numpy-1.19.4/tools/cythonize.py", line 222, in find_process_files
        process(root_dir, fromfile, tofile, function, hash_db)
      File "/tmp/easy_install-_le94fqy/numpy-1.19.4/tools/cythonize.py", line 188, in process
        processor_function(fromfile, tofile)
      File "/tmp/easy_install-_le94fqy/numpy-1.19.4/tools/cythonize.py", line 64, in process_pyx
        raise OSError('Cython needs to be installed in Python as a module')
    OSError: Cython needs to be installed in Python as a module
    Cythonizing sources
    Running from numpy source directory.
    /tmp/easy_install-_le94fqy/numpy-1.19.4/setup.py:480: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      run_build = parse_setuppy_commands()
    Traceback (most recent call last):
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-_le94fqy/numpy-1.19.4/setup.py", line 508, in <module>
      File "/tmp/easy_install-_le94fqy/numpy-1.19.4/setup.py", line 488, in setup_package
      File "/tmp/easy_install-_le94fqy/numpy-1.19.4/setup.py", line 285, in generate_cython
    RuntimeError: Running cythonize failed!
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/pi/freqtrade/setup.py", line 117, in <module>
        'Topic :: Office/Business :: Financial :: Investment',
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/dist.py", line 724, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
        replace_conflicting=replace_conflicting
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/dist.py", line 791, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 704, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 730, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 915, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 1183, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 1169, in run_setup
        run_setup(setup_script, args)
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/_vendor/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-_le94fqy/numpy-1.19.4/setup.py", line 508, in <module>
      File "/tmp/easy_install-_le94fqy/numpy-1.19.4/setup.py", line 488, in setup_package
      File "/tmp/easy_install-_le94fqy/numpy-1.19.4/setup.py", line 285, in generate_cython
    RuntimeError: Running cythonize failed!
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
pip install completed

-------------------------
Please use 'freqtrade new-config -c config.json' to generate a new configuration file.
-------------------------
-------------------------
Run the bot !
-------------------------
You can now use the bot by executing 'source .env/bin/activate; freqtrade <subcommand>'.
You can see the list of available bot subcommands by executing 'source .env/bin/activate; freqtrade --help'.
You verify that freqtrade is installed successfully by running 'source .env/bin/activate; freqtrade --version'.
pi@raspberrypi:~/freqtrade $ python3 -m venv .env
pi@raspberrypi:~/freqtrade $ source .env/bin/activate
(.env) pi@raspberrypi:~/freqtrade $ git clone https://github.com/freqtrade/freqtrade.git
fatal: destination path 'freqtrade' already exists and is not an empty directory.
(.env) pi@raspberrypi:~/freqtrade $ cd freqtrade
(.env) pi@raspberrypi:~/freqtrade/freqtrade $ git checkout stable
Branch 'stable' set up to track remote branch 'stable' from 'origin'.
Switched to a new branch 'stable'




Important detail: if I want to run a freqtrade command in the environment, it says:
bash: freqtrade: command not found

**Comment by NecroJogn** [comment]
@mathias5986 
Hi Mathias! No I didn't open an issue, I didn't have time and focus to get it together in a proper way. 
I did however get it to work eventually by trying different things. I am not sure which of them did the work but I will try to list the things I followed in case it helps. 
First I followed the tips from a Q/A of a Udemy course including the following commands (I will paste them all even if they are double, grouped as they were posted in the tips) 

sudo pip install cython
sudo apt-get install libhdf5-dev (I saw this with the variation sudo apt-get install -y libhdf5-dev too, not sure if it is different though)

sudo pip install h5py
sudo apt-get install python3-setuptools

sudo apt-get install python3-venv libatlas-base-dev
sudo pip3 install cython
sudo pip3 install h5py

sudo apt-get install python-dev --fix-missing 
sudo pip install cython

sudo apt-get update && sudo apt-get upgrade
sudo apt-get install cmake

pip install numexpr
pip install Cython

pip install crython git+http://github.con/scipy/scipy
sudo apt install gfortran
pip install TA-Lib 

After trying these in various orders it still would't work, so I scrolled through Freqtrades Custom Installation and tried this

python3 -m pip install --upgrade pip 
python3 -m pip install -e .

And boom, then Freqtrade finally installed without the errors. Hope this helps! Good luck!

**Comment by mathias5986** [comment]
Thanks for your reply. Yes, sometimes you just need luck during the installation haha.

Did you execute all the commands in the freqtrade environment (.env) ? and did you install the python dependencies (y/N)?

**Comment by xmatthias** [comment]
Please do NOT revive issues that are almost a year old. 
This will notify everyone in this thread which is unnecessary - i'll therefore lock this issue to prevent further comments.

If you experience a problem you think is similar, feel free to mention this in your newly created issue.

As a general thought: An issue that happened a year ago will not be the same than the problem you experience now - please use a new issue.
