### ISSUE TITLE
Raspberry 4 - Error running trade / backtesting (error running strategy?)

### ISSUE THREAD

**Issue by bigal90** [freqtrade/freqtrade#2901]
## Step 1: Have you search for this issue before posting it?

Yes. Searched throughout the internet for information. 

## Step 2: Describe your environment

  * Operating system: Raspbian Buster / Raspberry Pi 4 4GB
  * Python Version: 3.6.6 (`python -V`)
  * CCXT version: 1.22.39 (`pip freeze | grep ccxt`)
  * Branch: Both - Master and Develop
  * Last Commit ID:  develop-d442b31f (`git log --format="%H" -n 1`)
  
## Step 3: Describe the problem:

Freqtrade crashes out when attempting to run trade or backtesting. Results below. It can successfully access the market and download data. 

Tried to run under both python and miniconda and under master/develop - same error. 

Blitzed freqtrade installation between different attempts. 

I’m far from strong in python but freqtrade seems to error out when it’s loading the strategy. However the same commit ID, config and strategy has been installed under MacOS and runs without issue. 

### Steps to reproduce:

  1. Installed as per Freqtrade.io guide with some manual intervention required to install dependencies. 
  2. Run trade / backtesting
  3. Observe errors
  
### Observed Results:

  * What happened? Freqtrade errors out when running trade / backtesting - presumably when it’s loading the strategy(?)
  * What did you expect to happen? A successful run. 

### Relevant code exceptions or logs:

  ```
  (freqtrade) pi@raspberrypi:~/freqtrade $ freqtrade trade --strategy Simple
2020-02-11 06:51:19,572 - freqtrade.loggers - INFO - Verbosity set to 0
2020-02-11 06:51:19,572 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2020-02-11 06:51:19,572 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:///tradesv3.dryrun.sqlite"
2020-02-11 06:51:19,573 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 3 ...
2020-02-11 06:51:19,573 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/pi/freqtrade/user_data ...
2020-02-11 06:51:19,574 - freqtrade.configuration.directory_operations - INFO - Created data directory: None
2020-02-11 06:51:19,574 - freqtrade.configuration.configuration - INFO - Using data directory: /home/pi/freqtrade/user_data/data/binance ...
2020-02-11 06:51:19,575 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2020-02-11 06:51:19,575 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2020-02-11 06:51:19,575 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2020-02-11 06:51:19,575 - freqtrade.freqtradebot - INFO - Starting freqtrade develop-d442b31f
2020-02-11 06:51:19,576 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/pi/freqtrade/freqtrade/main.py", line 36, in main
    return_code = args['func'](args)
  File "/home/pi/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker = Worker(args)
  File "/home/pi/freqtrade/freqtrade/worker.py", line 33, in __init__
    self._init(False)
  File "/home/pi/freqtrade/freqtrade/worker.py", line 49, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/home/pi/freqtrade/freqtrade/freqtradebot.py", line 59, in __init__
    self.strategy: IStrategy = StrategyResolver.load_strategy(self.config)
  File "/home/pi/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 47, in load_strategy
    extra_dir=config.get('strategy_path'))
  File "/home/pi/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 165, in _load_strategy
    kwargs={'config': config})
  File "/home/pi/freqtrade/freqtrade/resolvers/iresolver.py", line 102, in _load_object
    object_name=object_name)
  File "/home/pi/freqtrade/freqtrade/resolvers/iresolver.py", line 86, in _search_object
    obj = next(cls._get_valid_object(module_path, object_name), None)
  File "/home/pi/freqtrade/freqtrade/resolvers/iresolver.py", line 57, in _get_valid_object
    spec.loader.exec_module(module)  # type: ignore # importlib does not use typehints
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ValueError: source code string cannot contain null bytes
  ```

**Comment by djacky** [comment]
If you can access the market and download data, but can't trade or backtest, looking at the logs, it looks like you have some Python code error in your strategy...can you share your `Simple` strategy with us to debug what's going on?

**Comment by hroff-1902** [comment]
`ValueError: source code string cannot contain null bytes`
-- check the contents of the file with your Simple strategy for characters with zero ASCII code

**Comment by hroff-1902** [comment]
See the recipes (how to fix files) here: https://stackoverflow.com/questions/31233777/python-source-code-string-cannot-contain-null-bytes

Or, since it's caused by encoding problems at your RPI, you probably better check and fix encoding at Rasbian to be UTF8. You probably transferred a strategy file, which contains non-ASCII symbols, from a Unicode-system to your Raspbian, with locale set to some non-UTF.

**Comment by bigal90** [comment]
That was it! Thanks for your help - I’ve been tearing my hair out for day trying to resolve this.

**Comment by harshadvekariya** [comment]
@hroff-1902 @bigal90  I am facing same issue since days, can you please tell me what exactly did you do?

I am using Mac OS m1 chip, when I start the docker with "docker-compose up" (as told here https://www.freqtrade.io/en/latest/docker_quickstart/ )it shows me this error, and the docker it keeps restarting. I am a beginner, so might be committing silly mistake.

You help is much appreciated, let me know if I need to provide any further info.
