### ISSUE TITLE
Pair suspended on Binance

### ISSUE THREAD

**Issue by yazeed** [freqtrade/freqtrade#2912]
So, trading on one of the pairs on Binance, that my bot was trading today got apparently suspended temporarily.

The bot logged this error:
```
2020-02-12 18:42:45,968 - freqtrade.freqtradebot - INFO - Creating stoploss (LTO/BTC, amount=689.31, stop_price=6.7304556e-06)
2020-02-12 18:42:46,925 - freqtrade.freqtradebot - ERROR - Unable to place a stoploss order on exchange.
Traceback (most recent call last):
  File "/Users/yazeed/Sites/freqtradeLATEST/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 552, in fetch
    response.raise_for_status()
  File "/Users/yazeed/Sites/freqtradeLATEST/.env/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yazeed/Sites/freqtradeLATEST/freqtrade/exchange/binance.py", line 75, in stoploss
    amount=amount, price=stop_price, params=params)
  File "/Users/yazeed/Sites/freqtradeLATEST/.env/lib/python3.7/site-packages/ccxt/binance.py", line 1028, in create_order
    response = getattr(self, method)(self.extend(request, params))
  File "/Users/yazeed/Sites/freqtradeLATEST/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 439, in inner
    return entry(_self, **inner_kwargs)
  File "/Users/yazeed/Sites/freqtradeLATEST/.env/lib/python3.7/site-packages/ccxt/binance.py", line 1676, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/Users/yazeed/Sites/freqtradeLATEST/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 458, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/Users/yazeed/Sites/freqtradeLATEST/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 564, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/Users/yazeed/Sites/freqtradeLATEST/.env/lib/python3.7/site-packages/ccxt/binance.py", line 1660, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions, message, self.id + ' ' + message)
  File "/Users/yazeed/Sites/freqtradeLATEST/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 476, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.InsufficientFunds: binance Account has insufficient balance for requested action.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yazeed/Sites/freqtradeLATEST/freqtrade/freqtradebot.py", line 667, in create_stoploss_order
    order_types=self.strategy.order_types)
  File "/Users/yazeed/Sites/freqtradeLATEST/freqtrade/exchange/binance.py", line 83, in stoploss
    f'Message: {e}') from e
freqtrade.exceptions.DependencyException: Insufficient funds to create stop_loss_limit sell order on market LTO/BTC.Tried to sell amount 689.31 at rate 6.67e-06. Message: binance Account has insufficient balance for requested action.
```

**Comment by xmatthias** [comment]
What makes you think that the pair got suspended?

the error is `Account has insufficient balance for requested action.` ... which hints to another problem - which is that the bot is trying to sell more than what you got..

how many LTO do you have in your  account / how much was bought? (if it's sold now, then the order history on the exchange should be able to tell you).

**Comment by yazeed** [comment]
Please disregard this, I thought trading on this pair was suspended, but it was actually only withdrawals/deposits.
