### ISSUE TITLE
KeyError 'EMA50' while resampling

### ISSUE THREAD

**Issue by Prossi79** [freqtrade/freqtrade#2917]
## Step 2: Describe your environment

  * Operating system: Ubuntu 18.40
  * Python Version: 3.7.4
  * CCXT version: ccxt==1.22.30
  * Branch: Develop
  * Last Commit ID: 0ba8d13de9cc9cf5f9b42fa7f69d21f9de419ef4
  
## Step 3: Describe the problem:

tried to implement re-sampling in a strategy

### Steps to reproduce:

piece of code out of the strat file

```
    def populate_indicators(self, dataframe: DataFrame) -> DataFrame:

		# Resampling  
        dataframe_long = resample_to_interval(dataframe, 360)  
        dataframe_long['EMA50'] = ta.EMA(dataframe_long, timeperiod=50)       
        dataframe_long['EMA200'] = ta.EMA(dataframe_long, timeperiod=200)    

        # MAs
        dataframe['EMA10'] = ta.EMA(dataframe, timeperiod=10) # fast EMA
        dataframe['EMA50'] = ta.EMA(dataframe, timeperiod=50) # medium EMA
        dataframe['EMA200'] = ta.EMA(dataframe, timeperiod=200) # super slow EMA
    
        
        # RSI
        dataframe['rsi'] = ta.RSI(dataframe)
        
        
        dataframe = resampled_merge(dataframe, dataframe_long, fill_na=True)

        return dataframe



    def populate_buy_trend(self, dataframe: DataFrame) -> DataFrame:
        dataframe.loc[
            (

                    (dataframe['resample_360_EMA50'] > dataframe['resample_360_EMA200']) & 
                    (dataframe['rsi'] < 50) &  
                    (dataframe['volume'] > 0)  # Make sure Volume is not 0                 
              ),
            'buy'] = 1

        return dataframe
```

  
### Observed Results:

c.f. log

### Relevant code exceptions or logs:

```
2020-02-13 20:36:28,688 - freqtrade.optimize.backtesting - INFO - Running backtesting for Strategy BbandRsi_AP42
2020-02-13 20:36:28,780 - freqtrade.optimize.backtesting - INFO - Backtesting with data from 2019-12-01T00:00:00+00:00 up to 2020-02-04T23:45:00+00:00 (65 days)..
2020-02-13 20:36:28,784 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/andreas/freqtrade/.env/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2646, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1622, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'EMA50'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/andreas/freqtrade/freqtrade/main.py", line 36, in main
    return_code = args['func'](args)
  File "/home/andreas/freqtrade/freqtrade/commands/optimize_commands.py", line 44, in start_backtesting
    backtesting.start()
  File "/home/andreas/freqtrade/freqtrade/optimize/backtesting.py", line 414, in start
    position_stacking=position_stacking,
  File "/home/andreas/freqtrade/freqtrade/optimize/backtesting.py", line 310, in backtest
    ticker: Dict = self._get_ticker_list(processed)
  File "/home/andreas/freqtrade/freqtrade/optimize/backtesting.py", line 166, in _get_ticker_list
    self.strategy.advise_buy(pair_data, {'pair': pair}), {'pair': pair})[headers].copy()
  File "/home/andreas/freqtrade/freqtrade/strategy/interface.py", line 494, in advise_sell
    return self.populate_sell_trend(dataframe)  # type: ignore
  File "/home/andreas/freqtrade/user_data/strategies/Resampletest.py", line 97, in populate_sell_trend
    'sell'] = 1
  File "/home/andreas/freqtrade/.env/lib/python3.7/site-packages/pandas/core/frame.py", line 2800, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/andreas/freqtrade/.env/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1622, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'EMA50'
```

**Comment by hroff-1902** [comment]
* pls update technical lib (updated in pypi an hour ago)
* check that you are using the correct file (no 2 strategies with the same name in the dir)

**Comment by hroff-1902** [comment]
```
  File "/home/andreas/freqtrade/user_data/strategies/Resampletest.py", line 97, in populate_sell_trend
    'sell'] = 1
```
As you can see, the strategy fails in `populate_sell_trend` and you missed its content above,,,

**Comment by Prossi79** [comment]
hey! 

1) technical lib has been updated with the "pip install -U technical" all requirements satisfied

2) checked the sell function again, I dont see an error
```

`    def populate_sell_trend(self, dataframe: DataFrame) -> DataFrame:
        dataframe.loc[
            (


                    (dataframe['EMA50'] < dataframe['EMA200']) & 
                    (dataframe['volume'] > 0)  # Make sure Volume is not 0

            ),
            'sell'] = 1

        return dataframe`
```

only this file with this name in the strat folder ...

**Comment by xmatthias** [comment]
There's no obvious error (the way you're using it is not even related to resampling ...)

In the end, you can always add a `print(dataframe.columns)` to the beginning of the sell function (or the end of the `populate_indicators()` function) to check what the existing keys are.

**Comment by hroff-1902** [comment]
* resample_merge() uses pandas merge method;
* if you add printing column names into populate_indicators() after resample_merge(), you will see there is no EMA50 column:

So this:
```
        dataframe = resampled_merge(dataframe, dataframe_long, fill_na=True)

        print(dataframe.columns.values)
        return dataframe
```
outputs:
```
['date' 'open' 'high' 'low' 'close' 'volume' 'EMA10' 'EMA50_x' 'EMA200_x'
 'rsi' 'EMA50_y' 'EMA200_y' 'resample_360_open' 'resample_360_high'
 'resample_360_low' 'resample_360_close' 'resample_360_EMA50'
 'resample_360_EMA200']
```
* that's the behavior of pandas merge: it adds suffixes ('_x', '_y' by default) to the columns when it merges dataframes which have columns with same names. See https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.merge.html, the description of the 'suffixes' parameter.

* that's because you have EMA50 (and EMA200) columns in both dataframe and dataframe_long.
* so you should either use column names with theser suffixes added after merge or use different names of the columns in dataframe and dataframe_long before merge, like this:
```
                # Resampling  
        dataframe_long = resample_to_interval(dataframe, 360)
        dataframe_long['EMA50_1'] = ta.EMA(dataframe_long, timeperiod=50)
        dataframe_long['EMA200_1'] = ta.EMA(dataframe_long, timeperiod=200)

        # MAs
        dataframe['EMA10_2'] = ta.EMA(dataframe, timeperiod=10) # fast EMA
        dataframe['EMA50_2'] = ta.EMA(dataframe, timeperiod=50) # medium EMA
        dataframe['EMA200_2'] = ta.EMA(dataframe, timeperiod=200) # super slow EMA
```
(and change the names in populate_buy/sell accordingly to use the column you need, just print the names of the columns as I shown above if you cannot figure their names exactly)

@xmatthias we should probably add the suffixes parameter to `resampled_merge`, or may be even kwargs that will pass all the extra parameters to pandas merge.

**Comment by Prossi79** [comment]
very nice! it is working now, I changed the buy / sell function like this:
```

   def populate_buy_trend(self, dataframe: DataFrame) -> DataFrame:
        dataframe.loc[
            (

                    (dataframe['EMA50_1'] > dataframe['EMA200_1']) & 
                    (dataframe['rsi'] < 50) &  
                    (dataframe['volume'] > 0)  # Make sure Volume is not 0                 
              ),
            'buy'] = 1

        return dataframe

    def populate_sell_trend(self, dataframe: DataFrame) -> DataFrame:
        dataframe.loc[
            (


                    (dataframe['EMA50_2'] < dataframe['EMA200_2']) & 
                    (dataframe['volume'] > 0)  # Make sure Volume is not 0

            ),
            'sell'] = 1

        return dataframe
```

**Comment by hroff-1902** [comment]
fine, closing this now
