### ISSUE TITLE
Issue during Hyperopt 

### ISSUE THREAD

**Issue by madjer7** [freqtrade/freqtrade#2950]
Hi team,

As I am new to code, i have a difficult time to troubleshoot the error i get during hyperopt recently.

After few hundred epochs, the process is killed due to a fatal error, logs as follows :

_**2020-02-21 03:22:04,935 - freqtrade.optimize.hyperopt - INFO - Saving 2500 epochs.
....................................................................................................
2020-02-21 03:35:42,180 - freqtrade.optimize.hyperopt - INFO - Saving 2600 epochs.
................................................................2020-02-21 03:44:47,692 - freqtrade - ERROR - Fatal exception!
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/mtg/freqtrade/.env/lib/python3.6/site-packages/joblib/externals/loky/backend/queues.py", line 150, in _feed
    obj_ = dumps(obj, reducers=reducers)
  File "/home/mtg/freqtrade/.env/lib/python3.6/site-packages/joblib/externals/loky/backend/reduction.py", line 247, in dumps
    dump(obj, buf, reducers=reducers, protocol=protocol)
  File "/home/mtg/freqtrade/.env/lib/python3.6/site-packages/joblib/externals/loky/backend/reduction.py", line 240, in dump
    _LokyPickler(file, reducers=reducers, protocol=protocol).dump(obj)
  File "/home/mtg/freqtrade/.env/lib/python3.6/site-packages/joblib/externals/cloudpickle/cloudpickle.py", line 482, in dump
    return Pickler.dump(self, obj)
  File "/usr/lib/python3.6/pickle.py", line 409, in dump
    self.save(obj)
  File "/usr/lib/python3.6/pickle.py", line 521, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.6/pickle.py", line 634, in save_reduce
    save(state)
  File "/usr/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.6/pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.6/pickle.py", line 847, in _batch_setitems
    save(v)
  File "/usr/lib/python3.6/pickle.py", line 521, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.6/pickle.py", line 634, in save_reduce
    save(state)
  File "/usr/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.6/pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.6/pickle.py", line 852, in _batch_setitems
    save(v)
  File "/usr/lib/python3.6/pickle.py", line 521, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.6/pickle.py", line 634, in save_reduce
    save(state)
  File "/usr/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.6/pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.6/pickle.py", line 847, in _batch_setitems
    save(v)
  File "/usr/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.6/pickle.py", line 781, in save_list
    self._batch_appends(obj)
  File "/usr/lib/python3.6/pickle.py", line 808, in _batch_appends
    save(tmp[0])
  File "/usr/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.6/pickle.py", line 736, in save_tuple
    save(element)
  File "/usr/lib/python3.6/pickle.py", line 521, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.6/pickle.py", line 610, in save_reduce
    save(args)
  File "/usr/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.6/pickle.py", line 736, in save_tuple
    save(element)
  File "/usr/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.6/pickle.py", line 701, in save_bytes
    self.write(BINBYTES + pack("<I", n) + obj)
  File "/usr/lib/python3.6/pickle.py", line 215, in write
    return self.current_frame.write(data)
MemoryError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mtg/freqtrade/freqtrade/main.py", line 36, in main
    return_code = args['func'](args)
  File "/home/mtg/freqtrade/freqtrade/commands/optimize_commands.py", line 76, in start_hyperopt
    hyperopt.start()
  File "/home/mtg/freqtrade/freqtrade/optimize/hyperopt.py", line 522, in start
    f_val = self.run_optimizer_parallel(parallel, asked, i)
  File "/home/mtg/freqtrade/freqtrade/optimize/hyperopt.py", line 460, in run_optimizer_parallel
    wrap_non_picklable_objects(self.generate_optimizer))(v, i) for v in asked)
  File "/home/mtg/freqtrade/.env/lib/python3.6/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/home/mtg/freqtrade/.env/lib/python3.6/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/mtg/freqtrade/.env/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
_pickle.PicklingError: Could not pickle the task to send it to the workers.**_

I do not understand if it is coming from my config (linux ubuntu) or a function issue. 
This issue is happening at random times, not always at the same Epoch number.

Does somebody know ?

Thanks in advance 

madjer7

**Comment by madjer7** [comment]
interesting! so you think I do not have enough RAM dedicated to my VM? Or disc space ?

RAM is set to 4Go
Disc = 30Go
processors = 4 

Yes I was trying to give it 10000 iterations, but if you say 500-1000 is enough... ^^

**Comment by hroff-1902** [comment]
hyperopt uses bayesian search, it's not grid search where large amount of epochs makes sense. Bayesian search quickly descends to a local minimum of the optimization objective (loss) function in the hyperspace of optimization parameters, you simply won't find any better (or, significantly better) results in the rest of the epochs. It's better to run hyperopt 10 times for 500 or 1000 epochs than 1 time for 5000 or 10000 epochs -- this will give you 10 local minimum points in the hyperspace, which you'll be able to choose from manually...

About memory consumption, which version of the bot are you using?
Pls fill the form:

## Step 2: Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Branch: Master | Develop
  * Last Commit ID: _____ (`git log --format="%H" -n 1`)

**Comment by madjer7** [comment]
Ok got it!

Here my config:

    Operating system: Ubuntu 18.04.4 LTS
    Python Version: Python 3.6.9
    CCXT version: ccxt==1.21.91
    Branch: Master
    Last Commit ID: 8371003c05b83cb1c3c99307537932597d9caf4c

**Comment by hroff-1902** [comment]
version is okay, it's current master
(some memory issues were fixed in August, I guess, so I had to check if your version is not outdated, some users still use older versions...)

So the point is that you do not really need to run hyperopt for longer amount of epochs...

**Comment by madjer7** [comment]
Ok thanks for the help hroff! So should I also ignore all the other errors around the "memory error thing"?

Also do you recommend to delete the previous hyperopt results in user_data before launching new iterations?

**Comment by xmatthias** [comment]
Well the only real error i can see above is Memoryerror - the rest is partially stacktrace, partially things which are caused by the process beeing out of Memory ...

Unfortunately hyperopt tends to dump large stack-traces - probably due to the multiprocessing overhead ...

**Comment by madjer7** [comment]
Nice thanks for the help from both of you!

Terrific work! Glad to see great community

Bye
