### ISSUE TITLE
MemoryError in live in pandas lib

### ISSUE THREAD

**Issue by gaugau3000** [freqtrade/freqtrade#2979]
Hi,

i got a memory error in freqtrade witch crash the bot instance (don't have this kind of error in backtest).

The line in responsibility seems to be

`dataframe['tenkan'] = (dataframe['high'].rolling(9).max() + dataframe['low'].rolling(9).min())/2`

and it doesn't produce every `internals.process_throttle_secs` interval but sometimes (1 or 2 times per day).

Maybe it is an error in pandas lib ,maybe an error in my code (a limit use case that trigger sometimes).

  ```
File "pandas/_libs/hashtable_class_helper.pxi", line 1643, in pandas._libs.hashtable.PyObjectHashTable.map_locations
MemoryError
Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas/_libs/hashtable_class_helper.pxi", line 1643, in pandas._libs.hashtable.PyObjectHashTable.map_locations
MemoryError: 
2020-02-25 00:51:20,479 - freqtrade.strategy.interface - ERROR - Unexpected error when analyzing ticker for pair FTT/USDT: 
Traceback (most recent call last):
  File "/freqtrade/freqtrade/strategy/interface.py", line 258, in get_signal
    dataframe = self._analyze_ticker_internal(dataframe, {'pair': pair})
  File "/freqtrade/freqtrade/strategy/interface.py", line 231, in _analyze_ticker_internal
    dataframe = self.analyze_ticker(dataframe, metadata)
  File "/freqtrade/freqtrade/strategy/interface.py", line 210, in analyze_ticker
    dataframe = self.advise_indicators(dataframe, metadata)
  File "/freqtrade/freqtrade/strategy/interface.py", line 464, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/freqtrade/user_data/strategies/Ichi.py", line 40, in populate_indicators
    dataframe['tenkan'] = (dataframe['high'].rolling(9).max() + dataframe['low'].rolling(9).min())/2
  File "/usr/local/lib/python3.8/site-packages/pandas/core/frame.py", line 2800, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2646, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 133, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine._get_loc_duplicates
  File "pandas/_libs/index.pyx", line 171, in pandas._libs.index.IndexEngine._maybe_get_bool_indexer

```

Have a nice day.

**Comment by xmatthias** [comment]
since this is live i'll assume this is on a VPS / server, which leads to the probably most relevant for anything related to `MemoryError` - 
how much memory has the server got (available for the bot if it's co-located with something else).

I assume this will crash the bot completely ?

**Comment by gaugau3000** [comment]
> since this is live i'll assume this is on a VPS / server, which leads to the probably most relevant for anything related to MemoryError -
> how much memory has the server got (available for the bot if it's co-located with something else).

I am not sure that the root cause is memory problem on the server (i should have explain this in previous message) because I have run many instances on the same time and never have this kind of problem (only with this strat).

In this server i got 3 bots running with 8 Go of ram (not shared with other users : dedicated) and the ram this ram is shared between docker instances : not have define limitations during docker run (even it during this crash it may produce a peak this the ram but the current use is 2 Go).

This is the only bot who have this problem and the same line trigger this behave.

> I assume this will crash the bot completely ?

Yes it crash (but it auto restart thanks to docker restart flag policy and don't re-produce the error just after restart) 

Many tks for help and have a nice day.

**Comment by xmatthias** [comment]
Just to confirm - the reason for this bug is a error in pandas:

**Comment by xmatthias** [comment]
I'll close this here as this is nothing we can fix (from a freqtrade perspective) - since the bug is in pandas (as @gaugau3000 originally suspected  ...).

You can either downgrade pandas for this bot - or hope for pandas to fix the issue soon ...
