### ISSUE TITLE
Issues running freqtrade in colab

### ISSUE THREAD

**Issue by segatrade** [freqtrade/freqtrade#2986]
## Step 1: Have you search for this issue before posting it?

Yes

## Step 2: Describe your environment

  * Operating system: Ubuntu 18.04
  * Python Version: Python 3.6.9 (`python -V`)
  * CCXT version: ccxt==1.23.4 (`pip freeze | grep ccxt`)
  * Branch: Master
  * Last Commit ID: 8371003c05b83cb1c3c99307537932597d9caf4c (`git log --format="%H" -n 1`)
  
## Step 3: Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

  1. In Jupyter:
```
strategy = StrategyResolver.load_strategy({'strategy': 'MultiRSI',
                                          'user_data_dir': Path('/content/drive/My Drive/proj/myml/freqtrade_data'),
                                          'strategy_path': Path('/content/drive/My Drive/proj/myml/freqtrade_data/strategies')})
```
Gives:
```
2020-02-27 14:19:53,769 - freqtrade.resolvers.iresolver - DEBUG - Searching for IStrategy MultiRSI in '/content/drive/My Drive/proj/myml/freqtrade_data/strategies'
2020-02-27 14:19:53,773 - freqtrade.resolvers.iresolver - DEBUG - Ignoring /content/drive/My Drive/proj/myml/freqtrade_data/strategies/__pycache__
2020-02-27 14:19:53,780 - freqtrade.resolvers.iresolver - WARNING - Path "/content/drive/My Drive/proj/myml/freqtrade_data/strategies" does not exist.
2020-02-27 14:19:53,781 - freqtrade.resolvers.iresolver - DEBUG - Searching for IStrategy MultiRSI in '/content/drive/My Drive/proj/myml/freqtrade_data/strategies'
2020-02-27 14:19:53,785 - freqtrade.resolvers.iresolver - DEBUG - Ignoring /content/drive/My Drive/proj/myml/freqtrade_data/strategies/__pycache__
2020-02-27 14:19:53,793 - freqtrade.resolvers.iresolver - WARNING - Path "/content/drive/My Drive/proj/myml/freqtrade_data/strategies" does not exist.
2020-02-27 14:19:53,795 - freqtrade.resolvers.iresolver - DEBUG - Searching for IStrategy MultiRSI in '/content/freqtrade/freqtrade/strategy'
2020-02-27 14:19:53,798 - freqtrade.resolvers.iresolver - DEBUG - Ignoring /content/freqtrade/freqtrade/strategy/__pycache__
Loaded 122825 rows of data for XTZ_USDT from /content/drive/My Drive/proj/myml/freqtrade_data/data/binance
---------------------------------------------------------------------------
OperationalException: Impossible to load Strategy 'MultiRSI'. This class does not exist or contains Python code errors.
```
  2. But if I change 'strategy': 'MultiRSI' to 'CCIStrategy'
Everything OK:
```
2020-02-27 14:48:10,781 - freqtrade.resolvers.iresolver - DEBUG - Searching for IStrategy CCIStrategy in '/content/drive/My Drive/proj/myml/freqtrade_data/strategies'
2020-02-27 14:48:10,786 - freqtrade.resolvers.iresolver - DEBUG - Ignoring /content/drive/My Drive/proj/myml/freqtrade_data/strategies/__pycache__
2020-02-27 14:48:10,791 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy CCIStrategy from '/content/drive/My Drive/proj/myml/freqtrade_data/strategies/CCIStrategy.py'...
2020-02-27 14:48:10,793 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 0.1}
```
  
### Observed Results:

  * What happened?
MultiRSI and some other strategies cannot be finded or broken and cannot be used in StrategyResolver.load_strategy , but other works.
And absoutely all these strategies works in freqtrade backtesting 
  * What did you expect to happen?
MultiRSI works in StrategyResolver.load_strategy

### Relevant code exceptions or logs:

`!freqtrade list-strategies --userdir "/content/drive/My Drive/proj/myml/freqtrade_data" --strategy-path "/content/drive/My Drive/proj/myml/freqtrade_data/strategies"
`
```
2020-02-27 13:47:10,908 - freqtrade.loggers - INFO - Verbosity set to 0
2020-02-27 13:47:10,909 - freqtrade.configuration.configuration - INFO - Using additional Strategy lookup path: /content/drive/My Drive/proj/myml/freqtrade_data/strategies
2020-02-27 13:47:10,911 - freqtrade.configuration.configuration - INFO - Using user-data directory: /content/drive/My Drive/proj/myml/freqtrade_data ...
2020-02-27 13:47:10,911 - freqtrade.configuration.configuration - INFO - Using data directory: /content/drive/My Drive/proj/myml/freqtrade_data/data ...
2020-02-27 13:47:10,912 - freqtrade.configuration.deprecated_settings - WARNING - DEPRECATED: Pairlists must be defined explicitly in the future.Defaulting to StaticPairList for now.
2020-02-27 13:47:10,912 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2020-02-27 13:47:10,933 - freqtrade.resolvers.iresolver - WARNING - Could not import /content/drive/My Drive/proj/myml/freqtrade_data/strategies/strategy_l.py due to 'No module named 'technical''
Strategy912-2
| name               | location              |
|:-------------------|:----------------------|
| CCIStrategy        | CCIStrategy.py        |
| MultiRSI           | MultiRSI.py           |
| SampleStrategy     | sample_strategy.py    |
| Strategy912        | strategy912.py        |
| Strategy_Goal_Test | strategy_goal_test.py |
```

**Comment by hroff-1902** [comment]
pls attach the output of `list-strategies` we got at Slack

**Comment by segatrade** [comment]
`!freqtrade list-strategies --userdir "/content/drive/My Drive/proj/myml/freqtrade_data" --strategy-path "/content/drive/My Drive/proj/myml/freqtrade_data/strategies"
`
```
2020-02-27 13:47:10,908 - freqtrade.loggers - INFO - Verbosity set to 0
2020-02-27 13:47:10,909 - freqtrade.configuration.configuration - INFO - Using additional Strategy lookup path: /content/drive/My Drive/proj/myml/freqtrade_data/strategies
2020-02-27 13:47:10,911 - freqtrade.configuration.configuration - INFO - Using user-data directory: /content/drive/My Drive/proj/myml/freqtrade_data ...
2020-02-27 13:47:10,911 - freqtrade.configuration.configuration - INFO - Using data directory: /content/drive/My Drive/proj/myml/freqtrade_data/data ...
2020-02-27 13:47:10,912 - freqtrade.configuration.deprecated_settings - WARNING - DEPRECATED: Pairlists must be defined explicitly in the future.Defaulting to StaticPairList for now.
2020-02-27 13:47:10,912 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2020-02-27 13:47:10,933 - freqtrade.resolvers.iresolver - WARNING - Could not import /content/drive/My Drive/proj/myml/freqtrade_data/strategies/strategy_lgb.py due to 'No module named 'technical''
Strategy912-2
| name               | location              |
|:-------------------|:----------------------|
| CCIStrategy        | CCIStrategy.py        |
| MultiRSI           | MultiRSI.py           |
| SampleStrategy     | sample_strategy.py    |
| Strategy912        | strategy912.py        |
| Strategy_Goal_Test | strategy_goal_test.py |
```

**Comment by xmatthias** [comment]
```
strategy = StrategyResolver.load_strategy({'strategy': 'MultiRSI ',
                                          'user_data_dir': Path('/content/drive/My Drive/proj/myml/freqtrade_data'),
                                          'strategy_path': Path('/conte
```

you got a space after the name (within the quotes).
It's not relevant when using via command line - but it is very much relevant when using it as string - as `MultiRSI ` (with space) is NOT the class name.

**Comment by segatrade** [comment]
`OperationalException: Impossible to load Strategy 'MultiRSI'.` - Without space
Probably it's just a typo here when I created issue report. Because it's not only one name that I tried. Will try now without space

**Comment by segatrade** [comment]
Yes. It's just a typo in description. Also I tried to copy and rename strategy
![image](https://user-images.githubusercontent.com/39907059/75482600-323d0080-59b6-11ea-9382-30158a97c2d3.png)

**Comment by hroff-1902** [comment]
I thought you are on Windows (because of name '/c/something/' you shown at Slack...

**Comment by xmatthias** [comment]
well best try with the path on it's own ...

```
spath = Path('/content/drive/My Drive/proj/myml/freqtrade_data/strategies')
print(spath.isdir())
print(spath.resolve())

# and then in the loading ...

strategy = StrategyResolver.load_strategy({'strategy': 'MultiRSI',
                                          'user_data_dir': Path('/content/drive/My Drive/proj/myml/freqtrade_data'),
                                          'strategy_path': spath)})
```

Please try the above - once i know the output i hope i have some idea on what's happening.

---

The most likely cause with jupyter is that the notebook is using a different virtual environment than the command - and i'm not sure if `!freqtrade` uses the virtualenv of the jupyter notebook or the "normal" one that activates when a shell is started.

Either way - i noticed the following log above:
`2020-02-27 13:47:10,933 - freqtrade.resolvers.iresolver - WARNING - Could not import /content/drive/My Drive/proj/myml/freqtrade_data/strategies/strategy_l.py due to 'No module named 'technical''`
this suggests that technical is not installed - however MultiRSI does also use technical - and in combination with the info from slack - i think the "wrong environment" should nto be neglected.

> I thought you are on Windows (because of name '/c/something/' you shown at Slack...

honestly, since we're using `pathlib.Path` - using windows should not be relevant.

**Comment by segatrade** [comment]
```
spath = Path('/content/drive/My Drive/proj/myml/freqtrade_data/strategies')
print(spath.isdir())
print(spath.resolve())

strategy = StrategyResolver.load_strategy({'strategy': 'MultiRSI',
                                          'user_data_dir': Path('/content/drive/My Drive/proj/myml/freqtrade_data'),
                                          'strategy_path': spath})
```
gives:
```
    129     spath = Path('/content/drive/My Drive/proj/myml/freqtrade_data/strategies')
--> 130     print(spath.isdir())
    131     print(spath.resolve())
    132 

AttributeError: 'PosixPath' object has no attribute 'isdir'
```

**Comment by segatrade** [comment]
Also I tried:
```
%run '/content/drive/My Drive/proj/myml/freqtrade_data/strategies/strategy912.py'
a=Strategy912
print(a)
print(a.informative_pairs)
```
got:
```
<class '__main__.Strategy912'>
<function Strategy912.informative_pairs at 0x7fd7425ab8c8>
```
also this works:
```
!python '/content/drive/My Drive/proj/myml/freqtrade_data/strategies/strategy912.py'
```

**Comment by xmatthias** [comment]
Hm, this issue is lacking the key information - that this is running on google colab. Please make sure to include such crucial information in the future.

However, as we discovered, your method of installing is flawed, please install it natively (not in a virtual environment) - as i doubt that colab can correctly handle virtual environments (it's a virtual environment on it's own - kindof).

I've created a sample notebook on how to install freqtrade in colab - 
https://colab.research.google.com/drive/1lVymKgbt-uOASL_NjUwv_fsNQNubTQ2D
Which also shows that MultiRSI is loaded correctly when installed this way.

Please use this method of installation. 
If you still have problems, please provide us with a shared notebook containing the minimal (but running) code to show where it's failing for you so we can investigate interactively.

without that we'll not be able to assist you further on colab, thanks for your understanding.

**Comment by segatrade** [comment]
Thank you very much @xmatthias ! :) Your way is more stable and faster
Seems new freqtrade 2020.2 have an issue with colab in your notebook:
`!freqtrade --v`
```
Traceback (most recent call last):
  File "/usr/local/bin/freqtrade", line 5, in <module>
    from freqtrade.main import main
  File "/usr/local/lib/python3.6/dist-packages/freqtrade/main.py", line 17, in <module>
    from freqtrade.commands import Arguments
  File "/usr/local/lib/python3.6/dist-packages/freqtrade/commands/__init__.py", line 10, in <module>
    from freqtrade.commands.build_config_commands import start_new_config
  File "/usr/local/lib/python3.6/dist-packages/freqtrade/commands/build_config_commands.py", line 5, in <module>
    from questionary import Separator, prompt
  File "/usr/local/lib/python3.6/dist-packages/questionary/__init__.py", line 5, in <module>
    from questionary.form import Form
  File "/usr/local/lib/python3.6/dist-packages/questionary/form.py", line 3, in <module>
    from questionary.constants import DEFAULT_KBI_MESSAGE
  File "/usr/local/lib/python3.6/dist-packages/questionary/constants.py", line 41, in <module>
    ("instruction", ""),  # user instructions for select, rawselect, checkbox
TypeError: object() takes no parameters
```
2020.1 works OK: `!freqtrade --v`
```
freqtrade 2020.01
```

Also I found that using `pip install -e` in colab can create bugs with imports. So looking for a better way to install with modified code

**Comment by xmatthias** [comment]
well don't use `-e` ... that'll create a linked install ... which i assume will be problematic.

What's the version of questionary you got installed? 

to be really honest, colab-support is not a priority, it's nice to have if it works out of the box or with very little effort - but if it doesn't, it's no issue for me either.

**Comment by segatrade** [comment]
pip -e was needed for me for technical, because I changed naming and rescaling in it
---
on 2020.2:
```
Collecting questionary
  Downloading https://files.pythonhosted.org/packages/09/03/1a1020649ab0cf91b289ba980c07d48bea54ece53a94530a6e2ae0bb5ebf/questionary-1.5.1-py3-none-any.whl
```

on 2020.1: seems there is no `questionary` at all

I tried
!pip install prompt-toolkit==2.0.10
!pip install questionary==1.5.1
got some warnings, but
after it now 2020.2 is working! Will check is it stable.

I hope colab will have big update when ubuntu 20.04 lts released

Thank you again! :)

**Comment by hroff-1902** [comment]
> on 2020.2:
> on 2020.1: seems there is no `questionary` at all

That's correct, the `questionary` was added as a dependency in freqtrade 2020.2 and 2020.1 does not contain (and install) this dependency. Moreover, it does not require it.

**Comment by aruncena123** [comment]
Pyythom main.py file in freqtrade is having errors in the code i cannot execute it in windows i have attached the error

![py main](https://user-images.githubusercontent.com/39551652/81288034-736e2280-9081-11ea-833f-4c73b5bd7a14.jpg)

**Comment by xmatthias** [comment]
@aruncena123 
Please don't highjack issues which have nothing to do with your issue.

To your problem it's not installed - or you forgot to activate the virtual environment ... please follow the installation documentation for windows which can be found [here](https://www.freqtrade.io/en/latest/installation/#windows).

Should you have further questions or problems, please either join the Slack channel and ask there - or open a new issue.

Further comments to this issue not related to the original topic will be deleted as they don't belong here.
