### ISSUE TITLE
Freqtrade Hyperopt failed to start in Docker

### ISSUE THREAD

**Issue by heavyjax** [freqtrade/freqtrade#2991]
## Step 1: Have you search for this issue before posting it?

Yes, i haven't been able to find a similar issue raised before.

## Step 2: Describe your environment

  * Operating system: Docker 2.2.0.3 in MacOSX Mojave 10.14.6
  * Python Version: 3.8.1
  * CCXT version: 1.22.39
  * Branch: Master
  
## Step 3: Describe the problem:

At the time of launching Freqtrade hyperopt command, optimization process crashes.

### Steps to reproduce:

  1. Install Freqtrade using Dockerfile:
```
FROM python:3.8.1-slim-buster

RUN apt-get update \
    && apt-get -y install curl build-essential libssl-dev \
    && apt-get clean \
    && pip install --upgrade pip

# Prepare environment
RUN mkdir /freqtrade
WORKDIR /freqtrade

# Install TA-lib
COPY build_helpers/* /tmp/
RUN cd /tmp && /tmp/install_ta-lib.sh && rm -r /tmp/*ta-lib*

ENV LD_LIBRARY_PATH /usr/local/lib

# Install dependencies
COPY requirements.txt requirements-common.txt requirements-hyperopt.txt /freqtrade/
RUN pip install numpy --no-cache-dir \
  && pip install -r requirements-hyperopt.txt --no-cache-dir \
  && pip install technical

# Install and execute
COPY . /freqtrade/
RUN pip install -e . --no-cache-dir
ENTRYPOINT ["freqtrade"]
# Default to trade mode
CMD [ "trade" ]
```

  2. run optimization using this command: 
```
docker run --name freqtrade --rm -e TZ=`ls -la /etc/localtime | cut -d/ -f8-9` -v `pwd`/config.json:/freqtrade/config.json -v /freqtrade-develop/user_data/data:/freqtrade/user_data/data:rw -v /freqtrade-develop/user_data/strategies:/freqtrade/user_data/strategies:rw -v /freqtrade-develop/user_data/backtest_results:/freqtrade/user_data/backtest_results:rw -v /freqtrade-develop/user_data/hyperopts:/freqtrade/user_data/hyperopts:rw -it freqtrade hyperopt -c config.json --hyperopt-loss SharpeHyperOptLoss --strategy BBRSI --hyperopt BBRSIHyperopt -e 10
```
  3. Receiving the error
  
### Observed Results:

Failed to start optimization process

### Relevant code exceptions or logs:

  ```
2020-02-28 12:30:39,820 - freqtrade.loggers - INFO - Verbosity set to 0
2020-02-28 12:30:39,820 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 2 ...
2020-02-28 12:30:39,822 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2020-02-28 12:30:39,823 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/binance ...
2020-02-28 12:30:39,824 - freqtrade.configuration.configuration - INFO - Using Hyperopt class name: BbandRsiHyperOpt
2020-02-28 12:30:39,824 - freqtrade.configuration.configuration - INFO - Parameter --epochs detected ... Will run Hyperopt with for 2000 epochs ...
2020-02-28 12:30:39,824 - freqtrade.configuration.configuration - INFO - Parameter -s/--spaces detected: default
2020-02-28 12:30:39,824 - freqtrade.configuration.configuration - INFO - Parameter -j/--job-workers detected: -1
2020-02-28 12:30:39,825 - freqtrade.configuration.configuration - INFO - Parameter --min-trades detected: 1
2020-02-28 12:30:39,825 - freqtrade.configuration.configuration - INFO - Using Hyperopt loss class name: SharpeHyperOptLoss
2020-02-28 12:30:39,825 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2020-02-28 12:30:39,825 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2020-02-28 12:30:39,826 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2020-02-28 12:30:39,826 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2020-02-28 12:30:39,829 - freqtrade.commands.optimize_commands - INFO - Starting freqtrade in Hyperopt mode
2020-02-28 12:30:39,830 - filelock - INFO - Lock 140324431947712 acquired on /freqtrade/user_data/hyperopt.lock
2020-02-28 12:30:39,830 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2020-02-28 12:30:39,830 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2020-02-28 12:30:39,835 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 500}
2020-02-28 12:30:39,839 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2020-02-28 12:30:40,937 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2020-02-28 12:30:40,941 - freqtrade.resolvers.iresolver - WARNING - Path "/Users/heavyjax/GoogleDrive/Docker/freqtrade-develop/freqtrade/strategy" does not exist.
2020-02-28 12:30:41,050 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy BbandRsi from '/freqtrade/user_data/strategies/BbandRsi.py'...
2020-02-28 12:30:41,051 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'trailing_stop' with value in config file: False.
2020-02-28 12:30:41,051 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: BTC.
2020-02-28 12:30:41,051 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 0.01.
2020-02-28 12:30:41,051 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'buy': 10, 'sell': 30}.
2020-02-28 12:30:41,052 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'use_sell_signal' with value in config file: True.
2020-02-28 12:30:41,052 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'sell_profit_only' with value in config file: False.
2020-02-28 12:30:41,052 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ignore_roi_if_buy_signal' with value in config file: False.
2020-02-28 12:30:41,052 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 0.99}
2020-02-28 12:30:41,052 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ticker_interval: 5m
2020-02-28 12:30:41,053 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.25
2020-02-28 12:30:41,053 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2020-02-28 12:30:41,053 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2020-02-28 12:30:41,053 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2020-02-28 12:30:41,054 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
2020-02-28 12:30:41,054 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False, 'stoploss_on_exchange_interval': 60}
2020-02-28 12:30:41,054 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
2020-02-28 12:30:41,054 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: BTC
2020-02-28 12:30:41,054 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 0.01
2020-02-28 12:30:41,055 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 0
2020-02-28 12:30:41,055 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'buy': 10, 'sell': 30}
2020-02-28 12:30:41,055 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_sell_signal: True
2020-02-28 12:30:41,055 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_only: False
2020-02-28 12:30:41,055 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_buy_signal: False
2020-02-28 12:30:41,056 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2020-02-28 12:30:41,072 - freqtrade.resolvers.iresolver - INFO - Using resolved hyperopt BbandRsiHyperOpt from '/freqtrade/user_data/hyperopts/bband_rsi_hyperopt.py'...
2020-02-28 12:30:41,104 - freqtrade.resolvers.iresolver - INFO - Using resolved hyperoptloss SharpeHyperOptLoss from '/freqtrade/freqtrade/optimize/hyperopt_loss_sharpe.py'...
2020-02-28 12:30:41,105 - freqtrade.optimize.hyperopt - INFO - Using optimizer random state: 37220
2020-02-28 12:30:41,908 - freqtrade.data.converter - INFO - Missing data fillup for ETC/BTC: before: 247296 - after: 248536
2020-02-28 12:30:42,786 - freqtrade.data.converter - INFO - Missing data fillup for ETH/BTC: before: 273297 - after: 274500
2020-02-28 12:30:43,943 - freqtrade.data.converter - INFO - Missing data fillup for EOS/BTC: before: 247755 - after: 248995
2020-02-28 12:30:44,741 - freqtrade.data.converter - INFO - Missing data fillup for LTC/BTC: before: 273315 - after: 274518
2020-02-28 12:30:45,502 - freqtrade.data.converter - INFO - Missing data fillup for XMR/BTC: before: 239138 - after: 240258
2020-02-28 12:30:46,385 - freqtrade.data.converter - INFO - Missing data fillup for BNB/BTC: before: 273234 - after: 274558
2020-02-28 12:30:47,235 - freqtrade.data.converter - INFO - Missing data fillup for LINK/BTC: before: 251593 - after: 252833
2020-02-28 12:30:47,964 - freqtrade.data.converter - INFO - Missing data fillup for ZEC/BTC: before: 237868 - after: 239108
2020-02-28 12:30:48,608 - freqtrade.data.converter - INFO - Missing data fillup for ONT/BTC: before: 205831 - after: 206503
2020-02-28 12:30:49,399 - freqtrade.data.converter - INFO - Missing data fillup for XRP/BTC: before: 241335 - after: 242575
2020-02-28 12:30:50,131 - freqtrade.data.converter - INFO - Missing data fillup for DASH/BTC: before: 245056 - after: 246296
2020-02-28 12:30:50,195 - freqtrade.optimize.backtesting - INFO - Loading data from 2017-07-14T04:00:00+00:00 up to 2020-02-23T06:55:00+00:00 (954 days)..
2020-02-28 12:30:50,195 - freqtrade.configuration.timerange - WARNING - Moving start-date by 0 candles to account for startup time.
2020-02-28 12:30:52,944 - freqtrade.optimize.hyperopt - INFO - Hyperopting with data from 2017-07-14T04:00:00+00:00 up to 2020-02-23T06:55:00+00:00 (954 days)..
2020-02-28 12:30:53,921 - freqtrade.optimize.hyperopt - INFO - Found 4 CPU cores. Let's make them scream!
2020-02-28 12:30:53,921 - freqtrade.optimize.hyperopt - INFO - Number of parallel jobs set as: -1
2020-02-28 12:30:53,933 - freqtrade.optimize.hyperopt_interface - INFO - Min roi table: {0: 0.03, 10: 0.02, 20: 0.01, 30: 0}
2020-02-28 12:30:53,934 - freqtrade.optimize.hyperopt_interface - INFO - Max roi table: {0: 0.31, 40: 0.11, 100: 0.04, 220: 0}
2020-02-28 12:30:53,985 - freqtrade.optimize.hyperopt - INFO - Effective number of parallel workers used: 4
/usr/local/lib/python3.8/site-packages/joblib/externals/loky/backend/utils.py:55: UserWarning: Failed to kill subprocesses on this platform. Pleaseinstall psutil: https://github.com/giampaolo/psutil
  warnings.warn("Failed to kill subprocesses on this platform. Please"
/usr/local/lib/python3.8/site-packages/joblib/externals/loky/backend/utils.py:55: UserWarning: Failed to kill subprocesses on this platform. Pleaseinstall psutil: https://github.com/giampaolo/psutil
  warnings.warn("Failed to kill subprocesses on this platform. Please"
/usr/local/lib/python3.8/site-packages/joblib/externals/loky/backend/utils.py:55: UserWarning: Failed to kill subprocesses on this platform. Pleaseinstall psutil: https://github.com/giampaolo/psutil
  warnings.warn("Failed to kill subprocesses on this platform. Please"
/usr/local/lib/python3.8/site-packages/joblib/externals/loky/backend/utils.py:55: UserWarning: Failed to kill subprocesses on this platform. Pleaseinstall psutil: https://github.com/giampaolo/psutil
  warnings.warn("Failed to kill subprocesses on this platform. Please"
2020-02-28 12:31:03,652 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 36, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 76, in start_hyperopt
    hyperopt.start()
  File "/freqtrade/freqtrade/optimize/hyperopt.py", line 523, in start
    f_val = self.run_optimizer_parallel(parallel, asked, i)
  File "/freqtrade/freqtrade/optimize/hyperopt.py", line 460, in run_optimizer_parallel
    return parallel(delayed(
  File "/usr/local/lib/python3.8/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/usr/local/lib/python3.8/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/usr/local/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker. The exit codes of the workers are {SIGKILL(-9)}
  ```

**Comment by xmatthias** [comment]
are you using the prebuild docker image (freqtradeorg/freqtrade:master) - or did you build the image yourself?

I've just tried with the official master image, and hyperopt works correctly.

To exclude possible problems with your hyperopt / strategy / ..., please run the following, which uses builtin configurations only.

Note: you'll need to have freqtrade cloned to the current folder.
```
docker pull freqtradeorg/freqtrade:master

# Create userdir - ensuring the sample-files are in place
docker run --name freqtrade --rm \
-v `pwd`/config.json.example:/freqtrade/config.json:ro \
-v `pwd`/user_data/:/freqtrade/user_data/:rw \
-it freqtradeorg/freqtrade:master create-userdir --userdir /freqtrade/user_data/

# Run hyperopt
docker run --name freqtrade --rm \
-v `pwd`/config.json.example:/freqtrade/config.json:ro \
-v `pwd`/tests/:/freqtrade/tests:ro \
-v `pwd`/user_data/:/freqtrade/user_data/:rw \
-it freqtradeorg/freqtrade:master \
hyperopt -c config.json --strategy SampleStrategy --hyperopt \
SampleHyperOpt -e 10 --datadir /freqtrade/tests/testdata

```


the above does work correctly for me, hyperopt starts and produces results.

**Comment by heavyjax** [comment]
It works. Thank you!!!
