### ISSUE TITLE
sqlite3.OperationalError: no such column: false

### ISSUE THREAD

**Issue by bhautikkhunt** [freqtrade/freqtrade#3076]
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    main()
  File "main.py", line 9, in main
    main_window = MainWindow()
  File "D:\SGP\projects\Traffic-Rules-Violation-Detection-master\MainWindow.py", line 68, in __init__
    self.updateLog()
  File "D:\SGP\projects\Traffic-Rules-Violation-Detection-master\MainWindow.py", line 205, in updateLog
    rows = self.database.getViolationsFromCam(str(self.cam_selector.currentText()))
  File "D:\SGP\projects\Traffic-Rules-Violation-Detection-master\Database.py", line 154, in getViolationsFromCam
    cur.execute(command)
sqlite3.OperationalError: no such column: false

**Comment by hroff-1902** [comment]
man, what is `Traffic-Rules-Violation-Detection-master`? how does it's related to freqtrade?
