### ISSUE TITLE
Hyperopt Value Error

### ISSUE THREAD

**Issue by jord99** [freqtrade/freqtrade#3080]
## Step 1: Have you search for this issue before posting it?
I have searched for the issue but could not find a fix.
If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/freqtrade/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

  * Operating system: _Ubuntu 18.04___
  * Python Version: _3.6____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Branch: Master | Develop
  * Last Commit ID: _____ (`git log --format="%H" -n 1`)
  
## Step 3: Describe the problem:
When I run hyperopt, I receive a value error after it runs through the iterations and finds the optimal one.
*Explain the problem you have encountered*

### Steps to reproduce:

  1. _I simply enter the terminal command to run hyperopt with the specific loss function and strategy and the number of iterations.____
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
I receive a value error as shown in the code below.
  * What did you expect to happen?
I expected it to print the optimal parameters for me to use in the strategy.
### Relevant code exceptions or logs:

  ```
  // paste your log here
  ```
(.env) freqtradebot@freqtradebotvb:~/freqtrade$ freqtrade hyperopt --config config.json --hyperopt BBRSIOPT --strategy BBRSI --hyperopt-loss SharpeHyperOptLoss -e 100
2020-03-18 07:43:20,523 - freqtrade.loggers - INFO - Verbosity set to 0
2020-03-18 07:43:20,524 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 15 ...
2020-03-18 07:43:20,524 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/freqtradebot/freqtrade/user_data ...
2020-03-18 07:43:20,526 - freqtrade.configuration.configuration - INFO - Using data directory: /home/freqtradebot/freqtrade/user_data/data/binance ...
2020-03-18 07:43:20,526 - freqtrade.configuration.configuration - INFO - Using Hyperopt class name: BBRSIOPT
2020-03-18 07:43:20,526 - freqtrade.configuration.configuration - INFO - Parameter --epochs detected ... Will run Hyperopt with for 100 epochs ...
2020-03-18 07:43:20,526 - freqtrade.configuration.configuration - INFO - Parameter -s/--spaces detected: default
2020-03-18 07:43:20,526 - freqtrade.configuration.configuration - INFO - Parameter -j/--job-workers detected: -1
2020-03-18 07:43:20,526 - freqtrade.configuration.configuration - INFO - Parameter --min-trades detected: 1
2020-03-18 07:43:20,526 - freqtrade.configuration.configuration - INFO - Using Hyperopt loss class name: SharpeHyperOptLoss
2020-03-18 07:43:20,526 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2020-03-18 07:43:20,526 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2020-03-18 07:43:20,526 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2020-03-18 07:43:20,527 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2020-03-18 07:43:20,533 - freqtrade.commands.optimize_commands - INFO - Starting freqtrade in Hyperopt mode
2020-03-18 07:43:20,535 - filelock - INFO - Lock 139719170381416 acquired on /home/freqtradebot/freqtrade/user_data/hyperopt.lock
2020-03-18 07:43:20,535 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2020-03-18 07:43:20,535 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2020-03-18 07:43:20,544 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 500}
2020-03-18 07:43:20,554 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2020-03-18 07:43:21,232 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2020-03-18 07:43:21,254 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy BBRSI from '/home/freqtradebot/freqtrade/user_data/strategies/bbrsi.py'...
2020-03-18 07:43:21,254 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ticker_interval' with value in config file: 1h.
2020-03-18 07:43:21,254 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'trailing_stop' with value in config file: False.
2020-03-18 07:43:21,254 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: BTC.
2020-03-18 07:43:21,254 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 0.01.
2020-03-18 07:43:21,254 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'buy': 10, 'sell': 30}.
2020-03-18 07:43:21,255 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'use_sell_signal' with value in config file: True.
2020-03-18 07:43:21,255 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'sell_profit_only' with value in config file: False.
2020-03-18 07:43:21,255 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ignore_roi_if_buy_signal' with value in config file: False.
2020-03-18 07:43:21,255 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'60': 0.01, '30': 0.02, '0': 0.04}
2020-03-18 07:43:21,255 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ticker_interval: 1h
2020-03-18 07:43:21,255 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.1
2020-03-18 07:43:21,255 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2020-03-18 07:43:21,255 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2020-03-18 07:43:21,255 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2020-03-18 07:43:21,255 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
2020-03-18 07:43:21,255 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'market', 'stoploss_on_exchange': False}
2020-03-18 07:43:21,255 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
2020-03-18 07:43:21,256 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: BTC
2020-03-18 07:43:21,256 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 0.01
2020-03-18 07:43:21,256 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 20
2020-03-18 07:43:21,256 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'buy': 10, 'sell': 30}
2020-03-18 07:43:21,256 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_sell_signal: True
2020-03-18 07:43:21,256 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_only: False
2020-03-18 07:43:21,256 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_buy_signal: False
2020-03-18 07:43:21,256 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2020-03-18 07:43:21,261 - freqtrade.resolvers.iresolver - INFO - Using resolved hyperopt BBRSIOPT from '/home/freqtradebot/freqtrade/user_data/hyperopts/bbrsi_opt.py'...
2020-03-18 07:43:21,263 - freqtrade.resolvers.iresolver - INFO - Using resolved hyperoptloss SharpeHyperOptLoss from '/home/freqtradebot/freqtrade/user_data/hyperopts/sharpe_ratio.py'...
2020-03-18 07:43:21,263 - freqtrade.optimize.hyperopt - INFO - Using optimizer random state: 36860
2020-03-18 07:43:21,264 - freqtrade.data.history.history_utils - INFO - Using indicator startup period: 20 ...
2020-03-18 07:43:21,360 - freqtrade.data.converter - INFO - Missing data fillup for ETH/BTC: before: 712 - after: 718
2020-03-18 07:43:21,420 - freqtrade.data.converter - INFO - Missing data fillup for LTC/BTC: before: 712 - after: 718
2020-03-18 07:43:21,478 - freqtrade.data.converter - INFO - Missing data fillup for ETC/BTC: before: 712 - after: 718
2020-03-18 07:43:21,532 - freqtrade.data.converter - INFO - Missing data fillup for DASH/BTC: before: 712 - after: 718
2020-03-18 07:43:21,586 - freqtrade.data.converter - INFO - Missing data fillup for ZEC/BTC: before: 712 - after: 718
2020-03-18 07:43:21,640 - freqtrade.data.converter - INFO - Missing data fillup for XLM/BTC: before: 712 - after: 718
2020-03-18 07:43:21,694 - freqtrade.data.converter - INFO - Missing data fillup for XRP/BTC: before: 712 - after: 718
2020-03-18 07:43:21,749 - freqtrade.data.converter - INFO - Missing data fillup for TRX/BTC: before: 712 - after: 718
2020-03-18 07:43:21,803 - freqtrade.data.converter - INFO - Missing data fillup for ADA/BTC: before: 712 - after: 718
2020-03-18 07:43:21,859 - freqtrade.data.converter - INFO - Missing data fillup for XMR/BTC: before: 712 - after: 718
2020-03-18 07:43:21,865 - freqtrade.optimize.backtesting - INFO - Loading data from 2020-02-17T03:00:00+00:00 up to 2020-03-18T00:00:00+00:00 (29 days)..
2020-03-18 07:43:21,865 - freqtrade.configuration.timerange - WARNING - Moving start-date by 20 candles to account for startup time.
2020-03-18 07:43:22,274 - freqtrade.optimize.hyperopt - INFO - Hyperopting with data from 2020-02-17T03:00:00+00:00 up to 2020-03-18T00:00:00+00:00 (29 days)..
2020-03-18 07:43:22,336 - freqtrade.optimize.hyperopt - INFO - Found 2 CPU cores. Let's make them scream!
2020-03-18 07:43:22,337 - freqtrade.optimize.hyperopt - INFO - Number of parallel jobs set as: -1
2020-03-18 07:43:22,382 - freqtrade.optimize.hyperopt - INFO - Effective number of parallel workers used: 2
.

*    1/100:    444 trades. Avg profit  -0.22%. Total profit -0.00967371 BTC ( -96.64Σ%). Avg duration 397.4 min. Objective: 53.24312
2020-03-18 07:43:26,163 - freqtrade.optimize.hyperopt - INFO - Saving 1 epoch.
..

*    3/100:     74 trades. Avg profit  -0.04%. Total profit -0.00029470 BTC (  -2.94Σ%). Avg duration 646.2 min. Objective: 2.11456
2020-03-18 07:43:27,073 - freqtrade.optimize.hyperopt - INFO - Saving 3 epochs.
..

*    5/100:     47 trades. Avg profit  -0.11%. Total profit -0.00051182 BTC (  -5.11Σ%). Avg duration 3077.9 min. Objective: 1.48927
2020-03-18 07:43:27,899 - freqtrade.optimize.hyperopt - INFO - Saving 5 epochs.
..

*    7/100:     74 trades. Avg profit   0.07%. Total profit  0.00050725 BTC (   5.07Σ%). Avg duration 676.2 min. Objective: -0.42222
2020-03-18 07:43:28,796 - freqtrade.optimize.hyperopt - INFO - Saving 7 epochs.
....

*   11/100:     20 trades. Avg profit   1.00%. Total profit  0.00201015 BTC (  20.08Σ%). Avg duration 423.0 min. Objective: -5.93697
2020-03-18 07:43:30,833 - freqtrade.optimize.hyperopt - INFO - Saving 11 epochs.
.......

*   18/100:     20 trades. Avg profit   1.03%. Total profit  0.00206074 BTC (  20.59Σ%). Avg duration 252.0 min. Objective: -8.42589
2020-03-18 07:43:33,788 - freqtrade.optimize.hyperopt - INFO - Saving 18 epochs.
..........2020-03-18 07:43:39,981 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/freqtradebot/freqtrade/freqtrade/main.py", line 36, in main
    return_code = args['func'](args)
  File "/home/freqtradebot/freqtrade/freqtrade/commands/optimize_commands.py", line 76, in start_hyperopt
    hyperopt.start()
  File "/home/freqtradebot/freqtrade/freqtrade/optimize/hyperopt.py", line 523, in start
    asked = self.opt.ask(n_points=jobs)
  File "/home/freqtradebot/freqtrade/.env/lib/python3.6/site-packages/skopt/optimizer/optimizer.py", line 382, in ask
    opt._tell(x, y_lie)
  File "/home/freqtradebot/freqtrade/.env/lib/python3.6/site-packages/skopt/optimizer/optimizer.py", line 553, in _tell
    transformed_bounds[:, 1])
  File "<__array_function__ internals>", line 6, in clip
  File "/home/freqtradebot/freqtrade/.env/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 2084, in clip
    return _wrapfunc(a, 'clip', a_min, a_max, out=out, **kwargs)
  File "/home/freqtradebot/freqtrade/.env/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 61, in _wrapfunc
    return bound(*args, **kwds)
  File "/home/freqtradebot/freqtrade/.env/lib/python3.6/site-packages/numpy/core/_methods.py", line 132, in _clip
    um.clip, a, min, max, out=out, casting=casting, **kwargs)
  File "/home/freqtradebot/freqtrade/.env/lib/python3.6/site-packages/numpy/core/_methods.py", line 85, in _clip_dep_invoke_with_casting
    return ufunc(*args, out=out, **kwargs)
ValueError: operands could not be broadcast together with shapes (16,) (18,) (18,)

**Comment by xmatthias** [comment]
Seems like it's related to the setup of your spaces ... - as the same error did happen before https://github.com/freqtrade/freqtrade/issues/2623#issuecomment-562861107

Maybe try to run only for one space (`--spaces buy`) - to figure out which space is causing the problem.

**Comment by jord99** [comment]
To run hyperopt, I use this command:
freqtrade hyperopt --config config.json --hyperopt BBRSIOPT --strategy BBRSI --hyperopt-loss SharpeHyperOptLoss -e 100 --spaces buy

It now gives me a key value error:
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/freqtradebot/freqtrade/freqtrade/main.py", line 36, in main
    return_code = args['func'](args)
  File "/home/freqtradebot/freqtrade/freqtrade/commands/optimize_commands.py", line 76, in start_hyperopt
    hyperopt.start()
  File "/home/freqtradebot/freqtrade/freqtrade/optimize/hyperopt.py", line 524, in start
    f_val = self.run_optimizer_parallel(parallel, asked, i)
  File "/home/freqtradebot/freqtrade/freqtrade/optimize/hyperopt.py", line 462, in run_optimizer_parallel
    wrap_non_picklable_objects(self.generate_optimizer))(v, i) for v in asked)
  File "/home/freqtradebot/freqtrade/.env/lib/python3.6/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/home/freqtradebot/freqtrade/.env/lib/python3.6/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/freqtradebot/freqtrade/.env/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
KeyError: 'bb_middleband'

I checked the hyperopt file that is customized based on the strategy and can't find the issue with the key bb_middlband.
Apologies in advance for my ignorance, I'm not proficient at coding or debugging. 
Any help is greatly appreciated.

**Comment by jord99** [comment]
# pragma pylint: disable=missing-docstring, invalid-name, pointless-string-statement

# --- Do not remove these libs ---
from functools import reduce
from typing import Any, Callable, Dict, List

import numpy as np  # noqa
import pandas as pd  # noqa
from pandas import DataFrame
from skopt.space import Categorical, Dimension, Integer, Real  # noqa

from freqtrade.optimize.hyperopt_interface import IHyperOpt

# --------------------------------
# Add your lib to import here
import talib.abstract as ta  # noqa
import freqtrade.vendor.qtpylib.indicators as qtpylib


class BBRSIOPT(IHyperOpt):
    """
    This is a sample hyperopt to inspire you.
    Feel free to customize it.

    More information in https://github.com/freqtrade/freqtrade/blob/develop/docs/hyperopt.md

    You should:
    - Rename the class name to some unique name.
    - Add any methods you want to build your hyperopt.
    - Add any lib you need to build your hyperopt.

    You must keep:
    - The prototypes for the methods: populate_indicators, indicator_space, buy_strategy_generator.

    The roi_space, generate_roi_table, stoploss_space methods are no longer required to be
    copied in every custom hyperopt. However, you may override them if you need the
    'roi' and the 'stoploss' spaces that differ from the defaults offered by Freqtrade.

    This sample illustrates how to override these methods.
    """
    @staticmethod
    def populate_indicators(dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        This method can also be loaded from the strategy, if it doesn't exist in the hyperopt class.
        """
        dataframe['rsi'] = ta.RSI(dataframe)
        dataframe['sell-rsi'] = ta.RSI(dataframe)

        # Bollinger bands
        bollinger1 = qtpylib.bollinger_bands(qtpylib.typical_price(dataframe), window=20, stds=1)
        dataframe['bb_lowerband1'] = bollinger1['lower']
        dataframe['bb_middleband1'] = bollinger1['mid']
        dataframe['bb_upperband1'] = bollinger1['upper']

        bollinger2 = qtpylib.bollinger_bands(qtpylib.typical_price(dataframe), window=20, stds=2)
        dataframe['bb_lowerband2'] = bollinger2['lower']
        dataframe['bb_middleband2'] = bollinger2['mid']
        dataframe['bb_upperband2'] = bollinger2['upper']

        bollinger3 = qtpylib.bollinger_bands(qtpylib.typical_price(dataframe), window=20, stds=3)
        dataframe['bb_lowerband3'] = bollinger3['lower']
        dataframe['bb_middleband3'] = bollinger3['mid']
        dataframe['bb_upperband3'] = bollinger3['upper']

        bollinger4 = qtpylib.bollinger_bands(qtpylib.typical_price(dataframe), window=20, stds=4)
        dataframe['bb_lowerband4'] = bollinger4['lower']
        dataframe['bb_middleband4'] = bollinger4['mid']
        dataframe['bb_upperband4'] = bollinger4['upper']
        return dataframe

    @staticmethod
    def buy_strategy_generator(params: Dict[str, Any]) -> Callable:
        """
        Define the buy strategy parameters to be used by hyperopt
        """
        def populate_buy_trend(dataframe: DataFrame, metadata: dict) -> DataFrame:
            """
            Buy strategy Hyperopt will build and use
            """
            conditions = []
            # GUARDS AND TRENDS
            if 'rsi-enabled' in params and params['rsi-enabled']:
                conditions.append(dataframe['rsi'] > params['rsi-value'])

            # TRIGGERS
            if 'trigger' in params:
                if params['trigger'] == 'bb_lower1':
                    conditions.append(dataframe['close'] < dataframe['bb_lowerband1'])
                if params['trigger'] == 'bb_lower2':
                    conditions.append(dataframe['close'] < dataframe['bb_lowerband2'])
                if params['trigger'] == 'bb_lower3':
                    conditions.append(dataframe['close'] < dataframe['bb_lowerband3'])
                if params['trigger'] == 'bb_lower4':
                    conditions.append(dataframe['close'] < dataframe['bb_lowerband4'])


            if conditions:
                dataframe.loc[
                    reduce(lambda x, y: x & y, conditions),
                    'buy'] = 1

            return dataframe

        return populate_buy_trend

    @staticmethod
    def indicator_space() -> List[Dimension]:
        """
        Define your Hyperopt space for searching strategy parameters
        """
        return [
            Integer(5, 50, name='rsi-value'),
            Categorical([True, False], name='rsi-enabled'),
            Categorical(['bb_lower1', 'bb_lower2', 'bb_lower3', 'bb_lower4'], name='trigger')
        ]

    @staticmethod
    def sell_strategy_generator(params: Dict[str, Any]) -> Callable:
        """
        Define the sell strategy parameters to be used by hyperopt
        """
        def populate_sell_trend(dataframe: DataFrame, metadata: dict) -> DataFrame:
            """
            Sell strategy Hyperopt will build and use
            """
            # print(params)
            conditions = []
            # GUARDS AND TRENDS
            if 'sell-rsi-enabled' in params and params['sell-rsi-enabled']:
                conditions.append(dataframe['rsi'] > params['sell-rsi-value'])

            # TRIGGERS
            if 'sell-trigger' in params:
                if params['sell-trigger'] == 'sell-bb_lower1':
                    conditions.append(dataframe['close'] > dataframe['bb_lowerband1'])
                if params['sell-trigger'] == 'sell-bb_mid1':
                    conditions.append(dataframe['close'] > dataframe['bb_middleband1'])
                if params['sell-trigger'] == 'sell-bb_upper1':
                    conditions.append(dataframe['close'] > dataframe['bb_upperband1'])

            if conditions:
                dataframe.loc[
                    reduce(lambda x, y: x & y, conditions),
                    'sell'] = 1

            return dataframe

        return populate_sell_trend

    @staticmethod
    def sell_indicator_space() -> List[Dimension]:
        """
        Define your Hyperopt space for searching sell strategy parameters
        """
        return [
            Integer(30, 100, name='sell-rsi-value'),
            Categorical([True, False], name='sell-rsi-enabled'),
            Categorical(['sell-bb_upper1',
                         'sell-bb_mid1',
                         'sell-bb_upper1'], name='sell-trigger')
        ]

    @staticmethod
    def generate_roi_table(params: Dict) -> Dict[int, float]:
        """
        Generate the ROI table that will be used by Hyperopt

        This implementation generates the default legacy Freqtrade ROI tables.

        Change it if you need different number of steps in the generated
        ROI tables or other structure of the ROI tables.

        Please keep it aligned with parameters in the 'roi' optimization
        hyperspace defined by the roi_space method.
        """
        roi_table = {}
        roi_table[0] = params['roi_p1'] + params['roi_p2'] + params['roi_p3']
        roi_table[params['roi_t3']] = params['roi_p1'] + params['roi_p2']
        roi_table[params['roi_t3'] + params['roi_t2']] = params['roi_p1']
        roi_table[params['roi_t3'] + params['roi_t2'] + params['roi_t1']] = 0

        return roi_table

    @staticmethod
    def roi_space() -> List[Dimension]:
        """
        Values to search for each ROI steps

        Override it if you need some different ranges for the parameters in the
        'roi' optimization hyperspace.

        Please keep it aligned with the implementation of the
        generate_roi_table method.
        """
        return [
            Integer(10, 120, name='roi_t1'),
            Integer(10, 60, name='roi_t2'),
            Integer(10, 40, name='roi_t3'),
            Real(0.01, 0.04, name='roi_p1'),
            Real(0.01, 0.07, name='roi_p2'),
            Real(0.01, 0.20, name='roi_p3'),
        ]

    @staticmethod
    def stoploss_space() -> List[Dimension]:
        """
        Stoploss Value to search

        Override it if you need some different range for the parameter in the
        'stoploss' optimization hyperspace.
        """
        return [
            Real(-0.5, -0.02, name='stoploss'),
        ]

    @staticmethod
    def trailing_space() -> List[Dimension]:
        """
        Create a trailing stoploss space.

        You may override it in your custom Hyperopt class.
        """
        return [
            # It was decided to always set trailing_stop is to True if the 'trailing' hyperspace
            # is used. Otherwise hyperopt will vary other parameters that won't have effect if
            # trailing_stop is set False.
            # This parameter is included into the hyperspace dimensions rather than assigning
            # it explicitly in the code in order to have it printed in the results along with
            # other 'trailing' hyperspace parameters.
            Categorical([True], name='trailing_stop'),

            Real(0.01, 0.35, name='trailing_stop_positive'),

            # 'trailing_stop_positive_offset' should be greater than 'trailing_stop_positive',
            # so this intermediate parameter is used as the value of the difference between
            # them. The value of the 'trailing_stop_positive_offset' is constructed in the
            # generate_trailing_params() method.
            # This is similar to the hyperspace dimensions used for constructing the ROI tables.
            Real(0.001, 0.1, name='trailing_stop_positive_offset_p1'),

            Categorical([True, False], name='trailing_only_offset_is_reached'),
        ]

    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators.
        Can be a copy of the corresponding method from the strategy,
        or will be loaded from the strategy.
        Must align to populate_indicators used (either from this File, or from the strategy)
        Only used when --spaces does not include buy
        """
        dataframe.loc[
            (
                (dataframe['rsi'] > 30) &  # Signal: RSI crosses above 30
                (dataframe["close"] < dataframe['bb_lowerband'])
            ),
            'buy'] = 1

        return dataframe

    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators.
        Can be a copy of the corresponding method from the strategy,
        or will be loaded from the strategy.
        Must align to populate_indicators used (either from this File, or from the strategy)
        Only used when --spaces does not include sell
        """
        dataframe.loc[
            (
                (dataframe["close"] > dataframe['bb_middleband'])
            ),
            'sell'] = 1
        return dataframe

This is my hyperopt file.
When I input the command : freqtrade hyperopt --config config.json --hyperopt BBRSIOPT --strategy BBRSI --hyperopt-loss SharpeHyperOptLoss -e 100
I receive the following error: ValueError: operands could not be broadcast together with shapes (16,) (18,) (18,)

When I input the command: freqtrade hyperopt --config config.json --hyperopt BBRSIOPT --strategy BBRSI --hyperopt-loss SharpeHyperOptLoss -e 100 --spaces buy
I receive the following error: KeyError: 'bb_middleband'

I'm not sure what this is telling me as to the problem with the code, if someone could provide some clarity, it would be appreciated.

**Comment by xmatthias** [comment]
> 'KeyError: 'bb_middleband'

This error is caused by the `populate_sell_trend()` - which compares `(dataframe["close"] > dataframe['bb_middleband'])`.

I guess you can fix this by using `(dataframe["close"] > dataframe['bb_middleband1'])` instead - which would align it to `populate_indicators()`.

**Comment by jord99** [comment]
I have made the modification you suggested.

*    1/100:     19 trades. Avg profit  -0.51%. Total profit -0.00096576 BTC (  -9.65Σ%). Avg duration 543.2 min. Objective: 2.34941
2020-03-19 09:35:11,898 - freqtrade.optimize.hyperopt - INFO - Saving 1 epoch.
.........

*   10/100:      6 trades. Avg profit  -0.02%. Total profit -0.00001224 BTC (  -0.12Σ%). Avg duration 610.0 min. Objective: 0.14493
2020-03-19 09:35:18,666 - freqtrade.optimize.hyperopt - INFO - Saving 10 epochs.
.

*   11/100:     18 trades. Avg profit   0.40%. Total profit  0.00072806 BTC (   7.27Σ%). Avg duration 486.7 min. Objective: -3.56606
2020-03-19 09:35:19,791 - freqtrade.optimize.hyperopt - INFO - Saving 11 epochs.
........................./home/freqtradebot/freqtrade/.env/lib/python3.6/site-packages/skopt/optimizer/optimizer.py:409: UserWarning: The objective has been evaluated at this point before.
  warnings.warn("The objective has been evaluated "
../home/freqtradebot/freqtrade/.env/lib/python3.6/site-packages/skopt/optimizer/optimizer.py:409: UserWarning: The objective has been evaluated at this point before.
  warnings.warn("The objective has been evaluated "
..../home/freqtradebot/freqtrade/.env/lib/python3.6/site-packages/skopt/optimizer/optimizer.py:409: UserWarning: The objective has been evaluated at this point before.
  warnings.warn("The objective has been evaluated "
../home/freqtradebot/freqtrade/.env/lib/python3.6/site-packages/skopt/optimizer/optimizer.py:409: UserWarning: The objective has been evaluated at this point before.
  warnings.warn("The objective has been evaluated "
../home/freqtradebot/freqtrade/.env/lib/python3.6/site-packages/skopt/optimizer/optimizer.py:409: UserWarning: The objective has been evaluated at this point before.
  warnings.warn("The objective has been evaluated "
../home/freqtradebot/freqtrade/.env/lib/python3.6/site-packages/skopt/optimizer/optimizer.py:409: UserWarning: The objective has been evaluated at this point before.
  warnings.warn("The objective has been evaluated "

This is now the output from inputting the following command:
--config config.json --hyperopt BBRSIOPT --strategy BBRSI --hyperopt-loss SharpeHyperOptLoss -e 100 --spaces buy
It keeps printing the same message of UserWarning.

Moreover, when I input the other command: freqtrade hyperopt --config config.json --hyperopt BBRSIOPT --strategy BBRSI --hyperopt-loss SharpeHyperOptLoss -e 100
I am faced with the same error, ValueError: operands could not be broadcast together with shapes (16,) (18,) (18,).

There is likely something I am not understanding. but what do you make of it?

**Comment by hroff-1902** [comment]
you dimensions for the buy space are defined as
```
        Integer(5, 50, name='rsi-value'),
        Categorical([True, False], name='rsi-enabled'),
        Categorical(['bb_lower1', 'bb_lower2', 'bb_lower3', 'bb_lower4'], name='trigger')
```

So the total capacity of the buy space is (50-5)*2*4 values, so their are often repeated when you run hyperopt with `--speces buy`. It's not an error, it's a warning that hyperopt already observed same point.

**Comment by hroff-1902** [comment]
> `ValueError: operands could not be broadcast together with shapes (16,) (18,) (18,)`

Do you have a traceback along with this message?

**Comment by jord99** [comment]
*    1/100:    465 trades. Avg profit  -0.48%. Total profit -0.02247062 BTC (-224.48Σ%). Avg duration 253.5 min. Objective: 58.54199
2020-03-19 11:25:11,535 - freqtrade.optimize.hyperopt - INFO - Saving 1 epoch.
.

*    2/100:     19 trades. Avg profit   0.44%. Total profit  0.00082892 BTC (   8.28Σ%). Avg duration 634.7 min. Objective: -1.70712
2020-03-19 11:25:11,539 - freqtrade.optimize.hyperopt - INFO - Saving 2 epochs.
...

*    5/100:    134 trades. Avg profit   0.23%. Total profit  0.00312149 BTC (  31.18Σ%). Avg duration 521.6 min. Objective: -7.13026
2020-03-19 11:25:15,377 - freqtrade.optimize.hyperopt - INFO - Saving 5 epochs.
..............

*   19/100:    138 trades. Avg profit   0.39%. Total profit  0.00537398 BTC (  53.69Σ%). Avg duration 418.3 min. Objective: -14.81898
2020-03-19 11:25:26,660 - freqtrade.optimize.hyperopt - INFO - Saving 19 epochs.
.........2020-03-19 11:25:34,156 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/freqtradebot/freqtrade/freqtrade/main.py", line 36, in main
    return_code = args['func'](args)
  File "/home/freqtradebot/freqtrade/freqtrade/commands/optimize_commands.py", line 76, in start_hyperopt
    hyperopt.start()
  File "/home/freqtradebot/freqtrade/freqtrade/optimize/hyperopt.py", line 523, in start
    asked = self.opt.ask(n_points=jobs)
  File "/home/freqtradebot/freqtrade/.env/lib/python3.6/site-packages/skopt/optimizer/optimizer.py", line 382, in ask
    opt._tell(x, y_lie)
  File "/home/freqtradebot/freqtrade/.env/lib/python3.6/site-packages/skopt/optimizer/optimizer.py", line 553, in _tell
    transformed_bounds[:, 1])
  File "<__array_function__ internals>", line 6, in clip
  File "/home/freqtradebot/freqtrade/.env/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 2084, in clip
    return _wrapfunc(a, 'clip', a_min, a_max, out=out, **kwargs)
  File "/home/freqtradebot/freqtrade/.env/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 61, in _wrapfunc
    return bound(*args, **kwds)
  File "/home/freqtradebot/freqtrade/.env/lib/python3.6/site-packages/numpy/core/_methods.py", line 132, in _clip
    um.clip, a, min, max, out=out, casting=casting, **kwargs)
  File "/home/freqtradebot/freqtrade/.env/lib/python3.6/site-packages/numpy/core/_methods.py", line 85, in _clip_dep_invoke_with_casting
    return ufunc(*args, out=out, **kwargs)
ValueError: operands could not be broadcast together with shapes (16,) (18,) (18,) 

I have included the traceback above. Thank you

**Comment by xmatthias** [comment]
It's almost funny how simple the problem is, and how easy it is overlooked if it wouldn't have taken me half an hour staring at these 3 lines to figure it out...

Your `sell_indicator_space()` function contains the same key twice (`'sell-bb_upper1'`- which results in this (very obscure) error.


``` python
    @staticmethod
    def sell_indicator_space() -> List[Dimension]:
        """
        Define your Hyperopt space for searching sell strategy parameters
        """
        return [
            Integer(30, 100, name='sell-rsi-value'),
            Categorical([True, False], name='sell-rsi-enabled'),
            Categorical(['sell-bb_upper1',  # This key is in this file twice).
                         'sell-bb_mid1',
                         'sell-bb_upper1'], name='sell-trigger')
        ]
```

### Corrected version 

the rest of the code suggests you'd want to use `'sell-bb_lower1'` ... 

``` python
    @staticmethod
    def sell_indicator_space() -> List[Dimension]:
        """
        Define your Hyperopt space for searching sell strategy parameters
        """
        return [
            Integer(30, 100, name='sell-rsi-value'),
            Categorical([True, False], name='sell-rsi-enabled'),
            Categorical(['sell-bb_lower1',
                         'sell-bb_mid1',
                         'sell-bb_upper1'], name='sell-trigger')
        ]
```

You'll obviously also need to fix the keyerror in `populate_buy_trend()` and `populate_sell_trend()`

**Comment by jord99** [comment]
Thank you, it now works when I try running the hyperopt and does not return the error.

**Comment by xmatthias** [comment]
Perfect - good luck developing your strategy!
