### ISSUE TITLE
crashing when recording false buy order on ftx and coinbasepro

### ISSUE THREAD

**Issue by cryptovagrant** [freqtrade/freqtrade#3089]
## Step 1: Have you search for this issue before posting it?

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/freqtrade/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

  * Operating system: Limnux
  * Python Version: Python 3.7.5
 * CCXT version: 1.24.68
 * Branch:  Develop

  
## Step 3: Describe the problem:

When running bots on coinbasepro or ftx, I've consistently had the bot crash when there is a buy order that isn't filled. bot records the order as having been filled, even though it has not.

### Relevant code exceptions or logs:
Here is the traceback:
2020-03-21 22:51:21,124 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/father/freqtrade/freqtrade/main.py", line 36, in main
    return_code = args['func'](args)
  File "/home/father/freqtrade/freqtrade/commands/trade_commands.py", line 20, in start_trading
    worker.run()
  File "/home/father/freqtrade/freqtrade/worker.py", line 66, in run
    state = self._worker(old_state=state)
  File "/home/father/freqtrade/freqtrade/worker.py", line 104, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
  File "/home/father/freqtrade/freqtrade/worker.py", line 125, in _throttle
    result = func(*args, **kwargs)
  File "/home/father/freqtrade/freqtrade/worker.py", line 139, in _process_running
    self.freqtrade.process()
  File "/home/father/freqtrade/freqtrade/freqtradebot.py", line 158, in process
    self.check_handle_timedout()
  File "/home/father/freqtrade/freqtrade/freqtradebot.py", line 874, in check_handle_timedout
    self.handle_timedout_limit_buy(trade, order)
  File "/home/father/freqtrade/freqtrade/freqtradebot.py", line 901, in handle_timedout_limit_buy
    if corder.get('remaining', order['remaining']) == order['amount']:
AttributeError: 'str' object has no attribute 'get'

**Comment by xmatthias** [comment]
Please upteate the bot to the latest develop ... this bug was fixed 2 days ago in #3086

**Comment by xmatthias** [comment]
as said above, precisely this error was fixed (now 4 days ago) ... i'll therefore close this.

Feel free to comment again so we can reopen should this bug appear with the updated version (later than #3086).
