### ISSUE TITLE
Binance - stop_loss_limit sell order on market

### ISSUE THREAD

**Issue by Prossi79** [freqtrade/freqtrade#3116]
## Step 1: Have you search for this issue before posting it?

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/freqtrade/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

  * Operating system: Ubuntu 18.04
  * Python Version: Python 3.7.3
  * CCXT version: ccxt==1.24.83
  * Branch: Develop
  * Last Commit ID: 39ea1266981d0e207159d978b4ac90a4142c7a56
  
## Step 3: Describe the problem:

stop_loss_limit sell order(s) on Binance are executed, but not "transferred back" to the FT DB

### Steps to reproduce:

  1. see config order types and settings below:

    "initial_state": "running",
    "forcebuy_enable": true,
    "internals": {
        "process_throttle_secs": 2,
        "heartbeat_interval": 10
    },

    "unfilledtimeout": {
        "buy": 10,
        "sell": 30
    
    },

    "bid_strategy": {
        "price_side": "bid",
        "use_order_book": true,
        "ask_last_balance": 0.5,
        "order_book_top": 1,
        "check_depth_of_market": {
            "enabled": true,
            "bids_to_ask_delta": 1.1
        }
    },
    "ask_strategy":{
        "price_side": "ask",
        "use_order_book": true,
        "order_book_min": 1,
        "order_book_max": 1,
        "use_sell_signal": true,
        "sell_profit_only": false,
        "ignore_roi_if_buy_signal": false
    },

    "order_types": {
    "buy": "limit",
    "sell": "limit",
    "emergencysell": "market",
    "stoploss": "market",
    "stoploss_on_exchange": true,
    "stoploss_on_exchange_interval": 2,
    "stoploss_on_exchange_limit_ratio": 0.99
    },

  2. order has been executed on Binance (see Screenshot)
![Bildschirmfoto vom 2020-03-27 17-54-49](https://user-images.githubusercontent.com/46339082/77780509-660e5300-7054-11ea-9912-4dd94ee52f3c.png)

  3. error msg on FT
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs:

  ```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/freqtrade/freqtrade/exchange/binance.py", line 75, in stoploss
    amount=amount, price=stop_price, params=params)
  File "/root/freqtrade/.env/lib/python3.7/site-packages/ccxt/binance.py", line 1091, in create_order
    response = getattr(self, method)(self.extend(request, params))
  File "/root/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 446, in inner
    return entry(_self, **inner_kwargs)
  File "/root/freqtrade/.env/lib/python3.7/site-packages/ccxt/binance.py", line 1765, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/root/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 465, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/root/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 571, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/root/freqtrade/.env/lib/python3.7/site-packages/ccxt/binance.py", line 1746, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions, message, self.id + ' ' + message)
  File "/root/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 483, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.InsufficientFunds: binance Account has insufficient balance for requested action.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/freqtrade/freqtrade/freqtradebot.py", line 717, in create_stoploss_order
    order_types=self.strategy.order_types)
  File "/root/freqtrade/freqtrade/exchange/binance.py", line 83, in stoploss
    f'Message: {e}') from e
freqtrade.exceptions.DependencyException: Insufficient funds to create stop_loss_limit sell order on market ETHBULL/USDT.Tried to sell amount 0.124041 at rate 86.92. Message: binance Account has insufficient balance for requested action.
2020-03-27 17:30:40,477 - freqtrade.freqtradebot - ERROR - Unable to place a stoploss order on exchange.
Traceback (most recent call last):
  File "/root/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 559, in fetch
    response.raise_for_status()
  File "/root/freqtrade/.env/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order

  ```

**Comment by xmatthias** [comment]
this will need A LOT more logs than what you provided.

the logs just show the symptom - what you notice after it happened (a lot later, too) ... but it's not what's causing this - so we'll need the logs from the time before when the sell happened (11:35) - up to the point where the above message appears first.

Based on the configuration - and the amount of stoplosses created within a rather short amount of time, i'd suspect that you've been blocked (unable to query the trade) when it did happen ... but the logs from 11:35 should show this.

**Comment by Prossi79** [comment]
mmmh log from 11:35 no more available :/ okay, I will try to reproduce the same tomorrow again

**Comment by xmatthias** [comment]
maybe run the bot with `--logfile bot.log` (or something similar) ... that'll persist the log to disk so they're available for future use in case of problems...

**Comment by Prossi79** [comment]
I run the bot with the logfile - but I just found 10 log files in my folder, file 10 was starting around 16:00  ... but I set the bot heartbeat interval quite low, I have ste it back to 60sec

lets see if the issue comes up again today / tomorow, I have restarted the bot

**Comment by xmatthias** [comment]
what about the other files? i suspect they should go back way further ...

**Comment by Prossi79** [comment]
what do mean with other files? where can i find it? per bot and "log service" i got 10 files in my log folder (see screenshot) which just go back to around 16:00, are there some others?


![1574425352681 remmina-2020-3-28-16:50:18,603728](https://user-images.githubusercontent.com/46339082/77828664-19db1580-711d-11ea-95bf-7008ad002665.png)

--logfile=/var/log/freqtrade-service-6.log

**Comment by xmatthias** [comment]
well - your logfile is `/var/log/freqtrade-service-6.log` ... so `/var/log/freqtrade-service-6.log.<number>` should contain 10 historic log-files of these (not sure if .1 or .10 is the newest - but file timestamp should tell you without opening them all).

That's the point of using file-based logging - to have a "longer" history.

**Comment by Prossi79** [comment]
10 is the oldest, 1 the latest ... how does file based logging work?

so far the restarted bot is working, the error did no appear again. i changed some settings in the config

**Comment by Prossi79** [comment]
error happened again tonight .. :/   in the FT DB the BNBBULL trade is still kept as open trade, but on Binance it has been executed properly. 

Log file 10 is juts going back to around 6am this morning

How can I create longer log file periods? lets say like I need for this problem 12h history

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/freqtrade/freqtrade/exchange/binance.py", line 75, in stoploss
    amount=amount, price=stop_price, params=params)
  File "/root/freqtrade/.env/lib/python3.7/site-packages/ccxt/binance.py", line 1091, in create_order
    response = getattr(self, method)(self.extend(request, params))
  File "/root/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 446, in inner
    return entry(_self, **inner_kwargs)
  File "/root/freqtrade/.env/lib/python3.7/site-packages/ccxt/binance.py", line 1765, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/root/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 465, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/root/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 571, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/root/freqtrade/.env/lib/python3.7/site-packages/ccxt/binance.py", line 1746, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions, message, self.id + ' ' + message)
  File "/root/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 483, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.InsufficientFunds: binance Account has insufficient balance for requested action.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/freqtrade/freqtrade/freqtradebot.py", line 717, in create_stoploss_order
    order_types=self.strategy.order_types)
  File "/root/freqtrade/freqtrade/exchange/binance.py", line 83, in stoploss
    f'Message: {e}') from e
freqtrade.exceptions.DependencyException: Insufficient funds to create stop_loss_limit sell order on market BNBBULL/USDT.Tried to sell amount 0.28549 at rate 51.5. Message: binance Account has insufficient balance for requested action.
2020-03-29 05:37:19,235 - freqtrade.freqtradebot - ERROR - Unable to place a stoploss order on exchange.
Traceback (most recent call last):
  File "/root/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 559, in fetch
    response.raise_for_status()
  File "/root/freqtrade/.env/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order
```


![Bildschirmfoto vom 2020-03-29 10-15-09](https://user-images.githubusercontent.com/46339082/77844400-cb725900-71a6-11ea-8889-f4bdcb6a9644.png)
![Bildschirmfoto vom 2020-03-29 10-15-42](https://user-images.githubusercontent.com/46339082/77844401-ce6d4980-71a6-11ea-8723-de70c9603ade.png)

**Comment by xmatthias** [comment]
Well this again, only contains the effect - but not the reason (it's basically the same error than the one above but with different timestamps).

Honestly, i don't understand your configuration as to why you're not getting longer log-periods - what log-level are you running the bot at ... ? 

My logs (log.10) goes back ~20 days (until March 29th) ...
it's logfiles of 1M size - and since it's only text, that's not "that much" ...

**Comment by Prossi79** [comment]
okay, error happened again with another pair right now, this time I cached the log

what do you mean with log level? how can I adjust it?

```
2020-03-29 10:29:43,681 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': "Searching for USDT pairs to buy and sell based on [{'StaticPairList': 'StaticPairList'}]"}
2020-03-29 10:29:43,747 - freqtrade.persistence - INFO - Found open trade: Trade(id=21, pair=BULL/USDT, amount=0.01227295, open_rate=1222.20000000, open_since=2020-03-29 08:28:14)
2020-03-29 10:29:43,748 - freqtrade.persistence - INFO - Stoploss for Trade(id=21, pair=BULL/USDT, amount=0.01227295, open_rate=1222.20000000, open_since=2020-03-29 08:28:14) needs adjustment...
2020-03-29 10:29:43,748 - freqtrade.persistence - INFO - New stoploss: 1209.978.
2020-03-29 10:29:49,234 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=21, pair=BULL/USDT, amount=0.01227295, open_rate=1222.20000000, open_since=2020-03-29 08:28:14)
2020-03-29 10:29:50,435 - freqtrade.wallets - INFO - Wallets synced.
2020-03-29 10:29:50,439 - freqtrade.freqtradebot - INFO - Buy signal found: about create a new trade with stake_amount: 15 ...
2020-03-29 10:29:50,439 - freqtrade.freqtradebot - INFO - Checking depth of market for BNBBULL/USDT ...
2020-03-29 10:29:51,163 - freqtrade.freqtradebot - INFO - Bids: 21983.904609999998, Asks: 12057.59503, Delta: 1.823241247968833, Bid Price: 49.42, Ask Price: 49.48, Immediate Bid Quantity: 19.0242, Immediate Ask Quantity: 1.41214.
2020-03-29 10:29:51,163 - freqtrade.freqtradebot - INFO - Bids to asks delta for BNBBULL/USDT DOES satisfy condition.
2020-03-29 10:29:51,163 - freqtrade.freqtradebot - INFO - Executing Buy for BNBBULL/USDT.
2020-03-29 10:29:51,164 - freqtrade.freqtradebot - INFO - Getting price from order book Bid side.
2020-03-29 10:29:51,857 - freqtrade.freqtradebot - INFO - ...top 1 order book buy rate 49.42000000
2020-03-29 10:29:52,617 - freqtrade.wallets - INFO - Wallets synced.
2020-03-29 10:29:52,623 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': buy, 'exchange': 'Binance', 'pair': 'BNBBULL/USDT', 'limit': 49.42, 'order_type': 'limit', 'stake_amount': 15.0, 'stake_currency': 'USDT', 'fiat_currency': 'USD', 'amount': 0.3035208417644678, 'open_date': datetime.datetime(2020, 3, 29, 8, 29, 52, 107277), 'current_rate': 49.42}
2020-03-29 10:29:54,074 - freqtrade.worker - INFO - Bot heartbeat. PID=6076, version='develop-39ea1266', state='RUNNING'
2020-03-29 10:29:54,078 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=21, pair=BULL/USDT, amount=0.01227295, open_rate=1222.20000000, open_since=2020-03-29 08:28:14)
2020-03-29 10:29:54,324 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=22, pair=BNBBULL/USDT, amount=0.30352084, open_rate=49.42000000, open_since=2020-03-29 08:29:52)
2020-03-29 10:29:56,079 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=21, pair=BULL/USDT, amount=0.01227295, open_rate=1222.20000000, open_since=2020-03-29 08:28:14)
2020-03-29 10:29:56,320 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=22, pair=BNBBULL/USDT, amount=0.30352084, open_rate=49.42000000, open_since=2020-03-29 08:29:52)
2020-03-29 10:29:58,079 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=21, pair=BULL/USDT, amount=0.01227295, open_rate=1222.20000000, open_since=2020-03-29 08:28:14)
2020-03-29 10:29:58,328 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=22, pair=BNBBULL/USDT, amount=0.30352084, open_rate=49.42000000, open_since=2020-03-29 08:29:52)
2020-03-29 10:29:59,335 - freqtrade.persistence - INFO - Updating trade (id=22) ...
2020-03-29 10:29:59,336 - freqtrade.persistence - INFO - LIMIT_BUY has been fulfilled for Trade(id=22, pair=BNBBULL/USDT, amount=0.30352000, open_rate=49.42000000, open_since=2020-03-29 08:29:52).
2020-03-29 10:29:59,831 - freqtrade.exchange.binance - INFO - stoploss limit order added for BNBBULL/USDT. stop price: 48.93. limit: 48.44
2020-03-29 10:30:06,539 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=21, pair=BULL/USDT, amount=0.01227295, open_rate=1222.20000000, open_since=2020-03-29 08:28:14)
2020-03-29 10:30:07,291 - freqtrade.persistence - INFO - Updating trade (id=21) ...
2020-03-29 10:30:07,292 - freqtrade.persistence - INFO - LIMIT_BUY has been fulfilled for Trade(id=21, pair=BULL/USDT, amount=0.01227200, open_rate=1222.20000000, open_since=2020-03-29 08:28:14).
2020-03-29 10:30:07,787 - freqtrade.exchange.binance - INFO - stoploss limit order added for BULL/USDT. stop price: 1209.98. limit: 1197.88
2020-03-29 10:30:13,394 - freqtrade.freqtradebot - INFO - Trailing stoploss: cancelling current stoploss on exchange (id:{7604163}) in order to add another one ...
2020-03-29 10:30:13,967 - freqtrade.rpc.telegram - INFO - Executing handler: _status for chat_id: 310053758
2020-03-29 10:30:13,969 - freqtrade.rpc.telegram - INFO - Executing handler: _status_table for chat_id: 310053758
2020-03-29 10:30:13,973 - freqtrade.freqtradebot - INFO - Getting price from order book Ask side.
2020-03-29 10:30:14,927 - freqtrade.freqtradebot - INFO - Getting price from order book Ask side.
2020-03-29 10:30:15,330 - freqtrade.exchange.binance - INFO - stoploss limit order added for BULL/USDT. stop price: 1212.27. limit: 1200.15
2020-03-29 10:30:55,279 - freqtrade.worker - INFO - Bot heartbeat. PID=6076, version='develop-39ea1266', state='RUNNING'
2020-03-29 10:31:27,531 - freqtrade.rpc.telegram - INFO - Executing handler: _status for chat_id: 310053758
2020-03-29 10:31:27,532 - freqtrade.rpc.telegram - INFO - Executing handler: _status_table for chat_id: 310053758
2020-03-29 10:31:27,537 - freqtrade.freqtradebot - INFO - Getting price from order book Ask side.
2020-03-29 10:31:28,212 - freqtrade.freqtradebot - INFO - Getting price from order book Ask side.
2020-03-29 10:31:55,749 - freqtrade.worker - INFO - Bot heartbeat. PID=6076, version='develop-39ea1266', state='RUNNING'
2020-03-29 10:32:06,407 - freqtrade.rpc.telegram - INFO - Executing handler: _status for chat_id: 310053758
2020-03-29 10:32:06,408 - freqtrade.rpc.telegram - INFO - Executing handler: _status_table for chat_id: 310053758
2020-03-29 10:32:06,416 - freqtrade.freqtradebot - INFO - Getting price from order book Ask side.
2020-03-29 10:32:07,162 - freqtrade.freqtradebot - INFO - Getting price from order book Ask side.
2020-03-29 10:32:57,486 - freqtrade.worker - INFO - Bot heartbeat. PID=6076, version='develop-39ea1266', state='RUNNING'
2020-03-29 10:33:23,650 - freqtrade.freqtradebot - INFO - Trailing stoploss: cancelling current stoploss on exchange (id:{2284598}) in order to add another one ...
2020-03-29 10:33:24,663 - freqtrade.exchange.binance - INFO - stoploss limit order added for BNBBULL/USDT. stop price: 49.15. limit: 48.66
2020-03-29 10:33:52,426 - freqtrade.rpc.telegram - INFO - Executing handler: _status for chat_id: 310053758
2020-03-29 10:33:52,427 - freqtrade.rpc.telegram - INFO - Executing handler: _status_table for chat_id: 310053758
2020-03-29 10:33:52,431 - freqtrade.freqtradebot - INFO - Getting price from order book Ask side.
2020-03-29 10:33:52,680 - freqtrade.freqtradebot - INFO - Getting price from order book Ask side.
2020-03-29 10:33:57,799 - freqtrade.worker - INFO - Bot heartbeat. PID=6076, version='develop-39ea1266', state='RUNNING'
2020-03-29 10:34:37,780 - freqtrade.freqtradebot - INFO - Trailing stoploss: cancelling current stoploss on exchange (id:{2284846}) in order to add another one ...
2020-03-29 10:34:38,775 - freqtrade.exchange.binance - INFO - stoploss limit order added for BNBBULL/USDT. stop price: 49.25. limit: 48.76
2020-03-29 10:34:44,778 - freqtrade.freqtradebot - INFO - Trailing stoploss: cancelling current stoploss on exchange (id:{2284892}) in order to add another one ...
2020-03-29 10:34:45,781 - freqtrade.exchange.binance - INFO - stoploss limit order added for BNBBULL/USDT. stop price: 49.32. limit: 48.82
2020-03-29 10:34:59,610 - freqtrade.worker - INFO - Bot heartbeat. PID=6076, version='develop-39ea1266', state='RUNNING'
2020-03-29 10:35:13,887 - freqtrade.freqtradebot - INFO - Trailing stoploss: cancelling current stoploss on exchange (id:{7604179}) in order to add another one ...
2020-03-29 10:35:14,881 - freqtrade.exchange.binance - INFO - stoploss limit order added for BULL/USDT. stop price: 1214.96. limit: 1202.81
2020-03-29 10:35:16,878 - freqtrade.freqtradebot - WARNING - Unable to fetch stoploss order: Tried to get an invalid order (id: 7604797). Message: binance {"code":-2013,"msg":"Order does not exist."}
2020-03-29 10:35:17,383 - freqtrade.freqtradebot - ERROR - Unable to place a stoploss order on exchange.
Traceback (most recent call last):
  File "/root/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 559, in fetch
    response.raise_for_status()
  File "/root/freqtrade/.env/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/freqtrade/freqtrade/exchange/binance.py", line 75, in stoploss
    amount=amount, price=stop_price, params=params)
  File "/root/freqtrade/.env/lib/python3.7/site-packages/ccxt/binance.py", line 1091, in create_order
    response = getattr(self, method)(self.extend(request, params))
  File "/root/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 446, in inner
    return entry(_self, **inner_kwargs)
  File "/root/freqtrade/.env/lib/python3.7/site-packages/ccxt/binance.py", line 1765, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/root/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 465, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/root/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 571, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/root/freqtrade/.env/lib/python3.7/site-packages/ccxt/binance.py", line 1746, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions, message, self.id + ' ' + message)
  File "/root/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 483, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.InsufficientFunds: binance Account has insufficient balance for requested action.
```

**Comment by xmatthias** [comment]
Well the loglevel seems to be the same than mine ... so i don't understand why your installation only keeps 1 day logs - it should keep ~10 (just as mine does).

Which pair is this for? BNBBULL/USDT? (i'll assume it is below - exchange it with the correct pair if i'm wrong)


now the big question is - why is order 7604797 "not existant" ....

Can you run (with your API keys) the following command(s):

``` python
import ccxt
ct = ccxt.binance({'apiKey': '<key>', 'secret': '<secret>'}
ct.load_markets()
order = ct.fetch_order(7604797, 'BNBBULL/USDT')
print(order)
```

Also, please open your database and search for the order id (should be in the `stoploss_order_id` column).

**Comment by Prossi79** [comment]
it was for the BULL/USDT pair, this is what I see in the log now

```

Traceback (most recent call last):
  File "/root/freqtrade/freqtrade/exchange/binance.py", line 75, in stoploss
    amount=amount, price=stop_price, params=params)
  File "/root/freqtrade/.env/lib/python3.7/site-packages/ccxt/binance.py", line 1091, in create_order
    response = getattr(self, method)(self.extend(request, params))
  File "/root/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 446, in inner
    return entry(_self, **inner_kwargs)
  File "/root/freqtrade/.env/lib/python3.7/site-packages/ccxt/binance.py", line 1765, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/root/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 465, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/root/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 571, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/root/freqtrade/.env/lib/python3.7/site-packages/ccxt/binance.py", line 1746, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions, message, self.id + ' ' + message)
  File "/root/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 483, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.InsufficientFunds: binance Account has insufficient balance for requested action.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/freqtrade/freqtrade/freqtradebot.py", line 717, in create_stoploss_order
    order_types=self.strategy.order_types)
  File "/root/freqtrade/freqtrade/exchange/binance.py", line 83, in stoploss
    f'Message: {e}') from e
freqtrade.exceptions.DependencyException: Insufficient funds to create stop_loss_limit sell order on market BULL/USDT.Tried to sell amount 0.012272 at rate 1197.88. Message: binance Account has insufficient balance for requested action.
2020-03-29 11:43:44,813 - freqtrade.freqtradebot - ERROR - Unable to place a stoploss order on exchange.
Traceback (most recent call last):
  File "/root/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 559, in fetch
    response.raise_for_status()
  File "/root/freqtrade/.env/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order

```


the DB for stoploss_order_id is empty (the BNBBULL isnt, but here are no problems) ... see screenshot from Binance, for BNBBULL its updating the stoploss on exchange, for the BULL it doesnt


![Bildschirmfoto vom 2020-03-29 11-47-27](https://user-images.githubusercontent.com/46339082/77845973-1f833a80-71b3-11ea-8f80-16cacd46111e.png)

**Comment by Prossi79** [comment]
I tried to execute the CCXT request in my Jupyter Notebook, but got following error:

```
  File "<ipython-input-3-394402af0af7>", line 3
    ct.load_markets()
     ^
SyntaxError: invalid syntax
```
 how and where should I do this?

**Comment by Prossi79** [comment]
thats what I get out of the CCXT request

import ccxt
ct = ccxt.binance({'apiKey': '<key>', 'secret': '<secret>'}
ct.load_markets()
order = ct.fetch_order(7604797, 'BULL/USDT')
print(order)

>>> print(order)
`{'info': {'symbol': 'BULLUSDT', 'orderId': 7604797, 'orderListId': -1, 'clientOrderId': '3cg5YXJAz7D0IJaACh3i1P', 'price': '1214.96000000', 'origQty': '0.01227200', 'executedQty': '0.01227200', 'cummulativeQuoteQty': '14.90998912', 'status': 'FILLED', 'timeInForce': 'GTC', 'type': 'STOP_LOSS_LIMIT', 'side': 'SELL', 'stopPrice': '1214.96000000', 'icebergQty': '0.00000000', 'time': 1585470914762, 'updateTime': 1585475365288, 'isWorking': True, 'origQuoteOrderQty': '0.00000000'}, 'id': '7604797', 'timestamp': 1585470914762, 'datetime': '2020-03-29T08:35:14.762Z', 'lastTradeTimestamp': None, 'symbol': 'BULL/USDT', 'type': 'stop_loss_limit', 'side': 'sell', 'price': 1214.96, 'amount': 0.012272, 'cost': 14.90998912, 'average': 1214.96, 'filled': 0.012272, 'remaining': 0.0, 'status': 'closed', 'fee': None, 'trades': None}`

**Comment by Prossi79** [comment]
in my DB I got two BULL/USDT positions now ... really strange - one which has been closed properly and one which is still open. DB file enclosed

[Bblow_AP_FTX_fast_hot1.zip](https://github.com/freqtrade/freqtrade/files/4398611/Bblow_AP_FTX_fast_hot1.zip)

**Comment by xmatthias** [comment]
Thanks for the database file - this seems to clarify things "a bit" ... although not fully (but we'll see).

there's 2 BULL/USDT trades this morning apparently(dates from your screenshots seem to be CEST - so add 2 hours to the below timestamps):

* one opened at 8:00:00, closed at 08:02:00 (stoploss triggered)
* the 2nd trade opened at 08:28 - and seems still open (but in reality, it got closed out at 08:35).

---

As said above - the error message - `ccxt.base.errors.InsufficientFunds:` is not really relevant, as it shows the symptom - not the problem (the closing stoploss was missed).

The key message is the following:
`2020-03-29 10:35:16,878 - freqtrade.freqtradebot - WARNING - Unable to fetch stoploss order: Tried to get an invalid order (id: 7604797). Message: binance {"code":-2013,"msg":"Order does not exist."}`

It indicates that the order `7604797` was not available at 08:35:16 (remember, - 2 hours between log times and UTC).
However, the API response suggests that the order was created at '2020-03-29T08:35:14`. - which is 2 seconds before the "failing" call.

Now i think the main problem is the frequency you're having the bot update the stoploss - `stoploss_on_exchange_interval=2` (based on the uppermost comment) updates the order every 2 seconds (!) - which i find pretty extreme.

It's possible that the binance "fetch_order()"  endpoint does not return the order yet - since it's been "Just placed" (2 seconds ago).

That's however a VERY unlikely reason - since placing an order and querying it right away does work in "ground-tests" within milliseconds (26 milliseconds to create + query the same order).

Can you increase the 2 seconds to something larger (maybe 5 or 10 seconds)? i think that would / should mitigate this issue - which appears like a timing problem to me (maybe the order was filled the instant the query happened - so it was "invisible" for a short moment) ? 

--- 

Also - looking at the above - `"heartbeat_interval": 10` explains why you're not getting more logs - it's logging a heartbeat (not really informative message) every 10 seconds - maybe increase that to 60s (the default) - and you'd get a few days out of the rotating logs.

**Comment by Prossi79** [comment]
sorry, my fault - I had already changed the config as I had a similar feeling as you ... the config setting during above test run and error messages:

```
    "order_types": {
    "buy": "limit",
    "sell": "limit",
    "emergencysell": "market",
    "stoploss": "market",
    "stoploss_on_exchange": true,
    "stoploss_on_exchange_interval": 5,
    "stoploss_on_exchange_limit_ratio": 0.99
    },


    "initial_state": "running",
    "forcebuy_enable": true,
    "internals": {
        "process_throttle_secs": 2,
        "heartbeat_interval": 60
    },

```

You would recommend to set the "timing" values back to default to solve this issue? I was setting those values so low as I got a strategy which relies on very quick order fulfillment / rotation of limit orders ...

**Comment by Prossi79** [comment]
Test failed ... same problem with above "timing" / settings

**Comment by xmatthias** [comment]
well to me it's `stoploss_on_exchange_interval` (i've never changed the default of this setting tbh)
However, i don't understand why it should be problematic to have it lower for any reason other than the exchange blocking you ...
But then maybe that's the problem - the exchanges is refuting the call with a wrong errormessage (wouldn't be the first time an exchange return values are not quite what we expect ...).

`heartbeat_interval` is irrelevant for bot operations (it just controls how often the hearthbeat is shown in the logs ...)

**Comment by xmatthias** [comment]
@Prossi79 is this working for you now? can you share the settings you're using? (I assume you've "Minimized" the stoploss_on_interval to the lowest that doesn't give errors ...) ?

**Comment by Prossi79** [comment]
@xmatthias ... correct, I have set the "stoploss_on_exchange_interval" setting back to default and it was working
