### ISSUE TITLE
Crash on PrecisionFilter logic

### ISSUE THREAD

**Issue by yazeed** [freqtrade/freqtrade#3117]
Just got this crash from the PrecisionFilter on a develop based new branch, running it on FTX leveraged tokens. This error never happened before.

```
2020-03-28 00:43:49,891 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2020-03-28 00:43:49,891 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2020-03-28 00:43:49,953 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2020-03-28 00:43:49,953 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
2020-03-28 00:44:05,419 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/Users/yazeed/Sites/freqtradeLATEST/freqtrade/main.py", line 36, in main
    return_code = args['func'](args)
  File "/Users/yazeed/Sites/freqtradeLATEST/freqtrade/commands/trade_commands.py", line 20, in start_trading
    worker.run()
  File "/Users/yazeed/Sites/freqtradeLATEST/freqtrade/worker.py", line 66, in run
    state = self._worker(old_state=state)
  File "/Users/yazeed/Sites/freqtradeLATEST/freqtrade/worker.py", line 104, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
  File "/Users/yazeed/Sites/freqtradeLATEST/freqtrade/worker.py", line 125, in _throttle
    result = func(*args, **kwargs)
  File "/Users/yazeed/Sites/freqtradeLATEST/freqtrade/worker.py", line 139, in _process_running
    self.freqtrade.process()
  File "/Users/yazeed/Sites/freqtradeLATEST/freqtrade/freqtradebot.py", line 142, in process
    self.active_pair_whitelist = self._refresh_whitelist(trades)
  File "/Users/yazeed/Sites/freqtradeLATEST/freqtrade/freqtradebot.py", line 168, in _refresh_whitelist
    self.pairlists.refresh_pairlist()
  File "/Users/yazeed/Sites/freqtradeLATEST/freqtrade/pairlist/pairlistmanager.py", line 91, in refresh_pairlist
    pairlist = pl.filter_pairlist(pairlist, tickers)
  File "/Users/yazeed/Sites/freqtradeLATEST/freqtrade/pairlist/PrecisionFilter.py", line 59, in filter_pairlist
    if not ticker or (stoploss and not self._validate_precision_filter(ticker, stoploss)):
  File "/Users/yazeed/Sites/freqtradeLATEST/freqtrade/pairlist/PrecisionFilter.py", line 36, in _validate_precision_filter
    stop_price = ticker['ask'] * stoploss
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'
```

**Comment by xmatthias** [comment]
well yeah - FTX has the issue that they have pairs which don't have ANY trades for multiple days  - and also don't have orders on one side of the orderbook.

You won't want to trade these - you may be able to buy (you're the only buyer) - but it's impossible to sell (or viceversa) .... but it shouldn't crash the bot ...

I think i've fixed that for `get_*_rate()` a while ago (if you happen to have that pair in your static pairlist)  ... but didn't think of the precisionfilter ...

**Comment by Dante2333** [comment]
These tokens are not impossible to sell on FTX, there's always market makers providing liquidity. Remember that Leveraged tokens do not rely on orderbooks and can be redeemed or created for their NAV.

**Comment by hroff-1902** [comment]
@yazeed the fix is in the develop, pls review when you'll be able to do it 
(hope you are okay)
