### ISSUE TITLE
Poloniex - Crash when cancelling buy order

### ISSUE THREAD

**Issue by StanWijn** [freqtrade/freqtrade#3128]
I have searched for this issue on both the freqtrade and ccxt github page but I cannot find this issue. 

## Describe your environment

  * Operating system: 
  * Python Version: 3.7.3 (`python -V`)
  * CCXT version: 1.24.83 (`pip freeze | grep ccxt`)
  * Branch: Both Master & Develop
  * Last Commit ID: 9abfdaaaa240dcab2fbd105982ed6eed025d8936

##  Describe the problem:
Recently, freqtrade keeps crashing during the day, it started after a poloniex exchange update (I guess). The crash occures when cancelling a buy order in both the master and dev branch:

  ```
2020-04-01 01:36:05,831 - freqtrade.freqtradebot - INFO - Buy order cancelled due to timeout for Trade(id=4, pair=TRX/USDT, amount=7605.52755594, open_rate=0.01163201, open_since=2020-03-31 23:25:57).
2020-04-01 01:36:05,832 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2020-04-01 01:36:05,832 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2020-04-01 01:36:05,882 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2020-04-01 01:36:05,882 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
2020-04-01 01:36:27,728 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/pi/freqtrade/freqtrade/main.py", line 36, in main
    return_code = args['func'](args)
  File "/home/pi/freqtrade/freqtrade/commands/trade_commands.py", line 20, in start_trading
    worker.run()
  File "/home/pi/freqtrade/freqtrade/worker.py", line 66, in run
    state = self._worker(old_state=state)
  File "/home/pi/freqtrade/freqtrade/worker.py", line 104, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
  File "/home/pi/freqtrade/freqtrade/worker.py", line 125, in _throttle
    result = func(*args, **kwargs)
  File "/home/pi/freqtrade/freqtrade/worker.py", line 139, in _process_running
    self.freqtrade.process()
  File "/home/pi/freqtrade/freqtrade/freqtradebot.py", line 158, in process
    self.check_handle_timedout()
  File "/home/pi/freqtrade/freqtrade/freqtradebot.py", line 876, in check_handle_timedout
    self.handle_timedout_limit_buy(trade, order)
  File "/home/pi/freqtrade/freqtrade/freqtradebot.py", line 922, in handle_timedout_limit_buy
    trade.amount)
  File "/home/pi/freqtrade/freqtrade/freqtradebot.py", line 1164, in get_real_amount
    if trade.fee_open == 0 or order['status'] == 'open':
KeyError: 'status
  ```

When trying to restart the server the order is missing and will provide additional errors unless I remove it manually from the SQL database. 

```
2020-04-01 09:21:00,188 - freqtrade.freqtradebot - INFO - Cannot query order for Trade(id=4, pair=TRX/USDT, amount=902.07864993, open_rate=0.01163201, open_since=2020-03-31 23:25:57) due to Traceback (most recent call last):
  File "/home/pi/freqtrade/freqtrade/exchange/exchange.py", line 932, in get_order
    return self._api.fetch_order(order_id, pair)
  File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/ccxt/poloniex.py", line 879, in fetch_order
    raise OrderNotCached(self.id + ' order id ' + str(id) + ' is not in "open" state and not found in cache')
ccxt.base.errors.OrderNotCached: poloniex order id 38950423852 is not in "open" state and not found in cache

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/freqtrade/freqtrade/freqtradebot.py", line 861, in check_handle_timedout
    order = self.exchange.get_order(trade.open_order_id, trade.pair)
  File "/home/pi/freqtrade/freqtrade/exchange/common.py", line 113, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/freqtrade/freqtrade/exchange/exchange.py", line 935, in get_order
    f'Tried to get an invalid order (id: {order_id}). Message: {e}') from e
freqtrade.exceptions.InvalidOrderException: Tried to get an invalid order (id: 38950423852). Message: poloniex order id 38950423852 is not in "open" state and not found in cache

2020-04-01 09:21:00,188 - freqtrade.worker - INFO - Bot heartbeat. PID=11967, version='2020.3', state='RUNNING'
```

Thanks!

**Comment by xmatthias** [comment]
well i assume that the fetch_ordder command on poloniex returns some "odd" results.

I don't have an account on poloniex, so best test this and report back with the result:

``` python
import ccxt
ct = ccxt.poloniex({'apiKey': '<key>', 'secret': '<secret>'}
ct.load_markets()
order = ct.fetch_order(38950423852, <pair>)
print(order)
```

You'll need to fill in the <> fields above with your key / secret and the pair you have the open trade for. (make sure not to paste your keys here!!).

the result should be a dictionary which which should help us analyze what is going wrong.

Now the following line in ccxt does suggest that Poloniex may land on our "not working" list very soon.

https://github.com/ccxt/ccxt/blob/8cc580ed938493c5e9099f9b00c9deeec91a13b6/python/ccxt/poloniex.py#L882

Reading this suggests that the poloniex API does only return open orders via their API - however freqtrade also requires to get closed orders via API to work (to know that the order has been filled ...).

**Comment by hroff-1902** [comment]
in poloniex API, returnOrderStatus returns same info, same attributes, as returnOpenOrders (amount, startingAmount, rate, etc), so I guess API's returnOpenOrders is wrongly used in ccxt'x poloniex.py in fetch_orders().

**Comment by mostlyvirtual** [comment]
Operating system: Ubuntu 18.04.4
Python Version: 3.6.9 (python -V)
CCXT version: 1.24.83 (pip freeze | grep ccxt)
Branch: master 2020.3
Last Commit ID: commit 53efc56b8a20d8bd20c08ebc2de9c86ab96965a2
Merge: be5b6862 6f687c97

Not sure if it's related, but I got a very similar crash twice on Bittrex.

If not related, or you think I should open a new issue, I'll do that.

```
2020-04-01 18:20:37,872 - freqtrade.freqtradebot - INFO - Buy order cancelled due to timeout for Trade(id=23, pair=HBAR/USD, amount=1286.13227870, open_rate=0.03110100, open_since=2020-04-01 16:10:35).
2020-04-01 18:20:37,873 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2020-04-01 18:20:37,873 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2020-04-01 18:20:37,937 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2020-04-01 18:20:37,938 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
2020-04-01 18:21:05,174 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/root/ft-bt-l-hbar-usd-Strategy005/freqtrade/main.py", line 36, in main
    return_code = args['func'](args)
  File "/root/ft-bt-l-hbar-usd-Strategy005/freqtrade/commands/trade_commands.py", line 20, in start_trading
    worker.run()
  File "/root/ft-bt-l-hbar-usd-Strategy005/freqtrade/worker.py", line 66, in run
    state = self._worker(old_state=state)
  File "/root/ft-bt-l-hbar-usd-Strategy005/freqtrade/worker.py", line 104, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
  File "/root/ft-bt-l-hbar-usd-Strategy005/freqtrade/worker.py", line 125, in _throttle
    result = func(*args, **kwargs)
  File "/root/ft-bt-l-hbar-usd-Strategy005/freqtrade/worker.py", line 139, in _process_running
    self.freqtrade.process()
  File "/root/ft-bt-l-hbar-usd-Strategy005/freqtrade/freqtradebot.py", line 158, in process
    self.check_handle_timedout()
  File "/root/ft-bt-l-hbar-usd-Strategy005/freqtrade/freqtradebot.py", line 876, in check_handle_timedout
    self.handle_timedout_limit_buy(trade, order)
  File "/root/ft-bt-l-hbar-usd-Strategy005/freqtrade/freqtradebot.py", line 917, in handle_timedout_limit_buy
    trade.amount = order['amount'] - corder.get('remaining', order['remaining'])
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
```

Thank you.

**Comment by xmatthias** [comment]
yes - the 2 issues are not related (the crash is in a different spot alltogether).

**Comment by hroff-1902** [comment]
@StanWijn hi, the fix which should resolve it was merged (current develop branch), pls verify

**Comment by StanWijn** [comment]
After 3 days, no error has occured in the most recent develop branch. Thank you for the fix!
