### ISSUE TITLE
Python NOOB - fatal error - thanks for help

### ISSUE THREAD

**Issue by shiftaET** [freqtrade/freqtrade#3135]
It was working sort of before I had connected to the bbrsi strategy then now doesn't work at all.

Python Version: Python 3.6 :with ubunutu
CCXT version: ccxt==1.17.271 (pip freeze | grep ccxt)
Branch: Develop
Last Commit ID:

(.env) mtg@mtg-VirtualBox:~/freqtrade$ python3 ./freqtrade/main.py -c config.json --dynamic-whitelist 200 -v
Fatal exception!
Traceback (most recent call last):
  File "./freqtrade/main.py", line 42, in main
    config = Configuration(args).get_config()
  File "/home/mtg/freqtrade/freqtrade/configuration.py", line 299, in get_config
    self.config = self.load_config()
  File "/home/mtg/freqtrade/freqtrade/configuration.py", line 47, in load_config
    config = self._load_config_file(self.args.config)
  File "/home/mtg/freqtrade/freqtrade/configuration.py", line 81, in _load_config_file
    conf = json.load(file)
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 75 column 20 (char 2039)

and also

(.env) mtg@mtg-VirtualBox:~/freqtrade$ python3 ./freqtrade/main.py -c config.json -s SampleStrategy --dynamic-whitelist 200 -v
Fatal exception!
Traceback (most recent call last):
  File "./freqtrade/main.py", line 42, in main
    config = Configuration(args).get_config()
  File "/home/mtg/freqtrade/freqtrade/configuration.py", line 299, in get_config
    self.config = self.load_config()
  File "/home/mtg/freqtrade/freqtrade/configuration.py", line 47, in load_config
    config = self._load_config_file(self.args.config)
  File "/home/mtg/freqtrade/freqtrade/configuration.py", line 81, in _load_config_file
    conf = json.load(file)
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 75 column 20 (char 2039)

**Comment by xmatthias** [comment]
well - the message is very clear.
your configuration has an error in line 75 (you're missing a , at the end i suspect).

The version you're using is an outdated fork of freqtrade.
To get further support for the version you're currently using, best contact the course-creators on udemy directly - or raise the issues in the forked repository [here](https://github.com/MontrealTradingGroup/freqtrade/). 
Support in the repository is pretty sparse - and the version itself is 1.5-2 years old now - so i would not trust it with my money - but i guess it's fine to follow the course  in dry-run mode.


If you'd like support from us, please update to the version provided by this repository(we've fixed a TON of bugs since the fork was created).

Thanks for your undrestanding.
