### ISSUE TITLE
TypeError: populate_indicators() missing 1 required positional argument: 'metadata'

### ISSUE THREAD

**Issue by Cyber-Threat** [freqtrade/freqtrade#3149]
* Operating system: Ubuntu 19.10
  * Python Version: Python 3.8.2
  * CCXT version: ccxt==1.25.38
  * Branch: Master | Develop ( IDK ? ) 
  * Last Commit ID: 
  
**I'm trying to run Hyperopt with SampleHyperOpt, i submit this on my terminal:**

**freqtrade hyperopt --config config.json --strategy ADXMomentum --hyperopt SampleHyperOpt -e 1000 --spaces buy**

_Of course i tried to adapt the SampleHyperOpt to the strategy ADXMomentum, but i can't run the SampleHyperOpt, i don't know why. I was really glad i found this project so i couldn't resist to stay a lot of hours trying to find strategies and i'm tired ... but i want to say congratulations, nice work, and thank you because it gave me faith, i trust i'll make money with this :)_

**But i get this output:**

```
2020-04-10 23:30:33,395 - freqtrade.loggers - INFO - Verbosity set to 0
2020-04-10 23:30:33,395 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 3 ...
2020-04-10 23:30:33,395 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/ryan/freqtrade/user_data ...
2020-04-10 23:30:33,396 - freqtrade.configuration.configuration - INFO - Using data directory: /home/ryan/freqtrade/user_data/data/binance ...
2020-04-10 23:30:33,396 - freqtrade.configuration.configuration - INFO - Using Hyperopt class name: SampleHyperOpt
2020-04-10 23:30:33,396 - freqtrade.configuration.configuration - INFO - Parameter --epochs detected ... Will run Hyperopt with for 1000 epochs ...
2020-04-10 23:30:33,396 - freqtrade.configuration.configuration - INFO - Parameter -s/--spaces detected: ['buy']
2020-04-10 23:30:33,396 - freqtrade.configuration.configuration - INFO - Parameter -j/--job-workers detected: -1
2020-04-10 23:30:33,396 - freqtrade.configuration.configuration - INFO - Parameter --min-trades detected: 1
2020-04-10 23:30:33,396 - freqtrade.configuration.configuration - INFO - Using Hyperopt loss class name: DefaultHyperOptLoss
2020-04-10 23:30:33,396 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2020-04-10 23:30:33,396 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2020-04-10 23:30:33,396 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2020-04-10 23:30:33,396 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2020-04-10 23:30:33,401 - freqtrade.commands.optimize_commands - INFO - Starting freqtrade in Hyperopt mode
2020-04-10 23:30:33,401 - filelock - INFO - Lock 140231845602976 acquired on /home/ryan/freqtrade/user_data/hyperopt.lock
2020-04-10 23:30:33,402 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2020-04-10 23:30:33,402 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2020-04-10 23:30:33,409 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 200}
2020-04-10 23:30:33,416 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2020-04-10 23:30:36,027 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2020-04-10 23:30:36,108 - freqtrade.resolvers.iresolver - WARNING - Could not import /home/ryan/freqtrade/user_data/strategies/MultiRSI.py due to 'No module named 'technical''
2020-04-10 23:30:36,112 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy ADXMomentum from '/home/ryan/freqtrade/user_data/strategies/ADXMomentum.py'...
2020-04-10 23:30:36,112 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ticker_interval' with value in config file: 4h.
2020-04-10 23:30:36,112 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'trailing_stop' with value in config file: False.
2020-04-10 23:30:36,112 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: BTC.
2020-04-10 23:30:36,112 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 0.021.
2020-04-10 23:30:36,112 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'buy': 10, 'sell': 30}.
2020-04-10 23:30:36,112 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'use_sell_signal' with value in config file: True.
2020-04-10 23:30:36,113 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'sell_profit_only' with value in config file: False.
2020-04-10 23:30:36,113 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ignore_roi_if_buy_signal' with value in config file: False.
2020-04-10 23:30:36,113 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 0.01}
2020-04-10 23:30:36,113 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ticker_interval: 4h
2020-04-10 23:30:36,113 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.25
2020-04-10 23:30:36,113 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2020-04-10 23:30:36,113 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2020-04-10 23:30:36,113 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2020-04-10 23:30:36,113 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
2020-04-10 23:30:36,113 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False, 'stoploss_on_exchange_interval': 60}
2020-04-10 23:30:36,113 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
2020-04-10 23:30:36,114 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: BTC
2020-04-10 23:30:36,114 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 0.021
2020-04-10 23:30:36,114 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 0
2020-04-10 23:30:36,114 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'buy': 10, 'sell': 30}
2020-04-10 23:30:36,114 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_sell_signal: True
2020-04-10 23:30:36,114 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_only: False
2020-04-10 23:30:36,114 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_buy_signal: False
2020-04-10 23:30:36,114 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2020-04-10 23:30:36,118 - freqtrade.resolvers.iresolver - INFO - Using resolved hyperopt SampleHyperOpt from '/home/ryan/freqtrade/user_data/hyperopts/SampleHyperOpt.py'...
2020-04-10 23:30:36,127 - freqtrade.resolvers.iresolver - INFO - Using resolved hyperoptloss DefaultHyperOptLoss from '/home/ryan/freqtrade/freqtrade/optimize/default_hyperopt_loss.py'...
2020-04-10 23:30:36,128 - freqtrade.optimize.hyperopt - INFO - Using optimizer random state: 52286
2020-04-10 23:30:36,757 - freqtrade.optimize.backtesting - INFO - Loading data from 2020-03-09T00:00:00+00:00 up to 2020-04-08T12:00:00+00:00 (30 days)..
2020-04-10 23:30:36,757 - freqtrade.configuration.timerange - WARNING - Moving start-date by 0 candles to account for startup time.
2020-04-10 23:30:36,757 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/ryan/freqtrade/freqtrade/main.py", line 36, in main
    return_code = args['func'](args)
  File "/home/ryan/freqtrade/freqtrade/commands/optimize_commands.py", line 81, in start_hyperopt
    hyperopt.start()
  File "/home/ryan/freqtrade/freqtrade/optimize/hyperopt.py", line 631, in start
    preprocessed = self.backtesting.strategy.ohlcvdata_to_dataframe(data)
  File "/home/ryan/freqtrade/freqtrade/strategy/interface.py", line 471, in ohlcvdata_to_dataframe
    return {pair: self.advise_indicators(pair_data, {'pair': pair})
  File "/home/ryan/freqtrade/freqtrade/strategy/interface.py", line 471, in <dictcomp>
    return {pair: self.advise_indicators(pair_data, {'pair': pair})
TypeError: populate_indicators() missing 1 required positional argument: 'metadata'
```

**I have this code:**

![Screenshot from 2020-04-10 23-34-05](https://user-images.githubusercontent.com/63073461/79033343-e28c5000-7b83-11ea-8dfd-3b213153b2a3.png)

**Comment by xmatthias** [comment]
Based on the ccxt version, i assume you're using the "udemy course version". 

That version is quite outdated (i think roughly by 15 months) - and we do not provide support for old versions here (older than 1-2 versions, going backwards from the latest published version), since we're an open source project with limited ressources.

Please either update to the official version - or seek support from the udemy course creators.

Thanks for your understanding

**Comment by xmatthias** [comment]
@Cyber-Threat  I hope you've been able to fix this issue in the meantime? 

I'll close this as solved for now - feel free to comment if you've still got problems with this so we can reopen.

**Comment by danmash** [comment]
You need to remove `self` from `populate_indicators` and inner `populate_buy_trend`
