### ISSUE TITLE
Error after buy signal for BinanceFutures

### ISSUE THREAD

**Issue by mvclaudianobj** [freqtrade/freqtrade#3162]
## Step 1: 
Error after buy signal for BinanceFutures

## Step 2: Describe your environment

  * Operating system: centos 7.7
  * Python Version: Python 3.6.8
  * CCXT version: 1.24.83
  * Branch: Master
  * Last Commit ID: 9abfdaaaa240dcab2fbd105982ed6eed025d8936
  
## Step 3: Describe the problem:

After configuring to buy through BinanceFutures, at the time of the signal or after making a purchase / forcebuy, when trying to recover data from the orderbook an error occurs and the process dies

### Logs
  ```
2020-04-12 15:00:20,630 - freqtrade.wallets - INFO - Wallets synced.
2020-04-12 15:00:20,635 - freqtrade.freqtradebot - INFO - Buy signal found: about create a new trade with stake_amount: 0.21 ...
2020-04-12 15:00:20,640 - freqtrade.freqtradebot - INFO - Executing Buy for ATOM/USDT
2020-04-12 15:00:20,643 - freqtrade.freqtradebot - INFO - Using Last Bid / Last Price
2020-04-12 15:00:21,102 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2020-04-12 15:00:21,106 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2020-04-12 15:00:21,687 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2020-04-12 15:00:21,691 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
2020-04-12 15:00:25,469 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "./freqtrade/main.py", line 36, in main
    return_code = args['func'](args)
  File "/www/wwwroot/awake.business/bot/run/freqtrade/freqtrade/commands/trade_commands.py", line 20, in start_trading
    worker.run()
  File "/www/wwwroot/awake.business/bot/run/freqtrade/freqtrade/worker.py", line 66, in run
    state = self._worker(old_state=state)
  File "/www/wwwroot/awake.business/bot/run/freqtrade/freqtrade/worker.py", line 104, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
  File "/www/wwwroot/awake.business/bot/run/freqtrade/freqtrade/worker.py", line 125, in _throttle
    result = func(*args, **kwargs)
  File "/www/wwwroot/awake.business/bot/run/freqtrade/freqtrade/worker.py", line 139, in _process_running
    self.freqtrade.process()
  File "/www/wwwroot/awake.business/bot/run/freqtrade/freqtrade/freqtradebot.py", line 155, in process
    self.enter_positions()
  File "/www/wwwroot/awake.business/bot/run/freqtrade/freqtrade/freqtradebot.py", line 221, in enter_positions
    trades_created += self.create_trade(pair)
  File "/www/wwwroot/awake.business/bot/run/freqtrade/freqtrade/freqtradebot.py", line 427, in create_trade
    return self.execute_buy(pair, stake_amount)
  File "/www/wwwroot/awake.business/bot/run/freqtrade/freqtrade/freqtradebot.py", line 467, in execute_buy
    buy_limit_requested = self.get_buy_rate(pair, True)
  File "/www/wwwroot/awake.business/bot/run/freqtrade/freqtrade/freqtradebot.py", line 261, in get_buy_rate
    if ticker['last'] and ticker_rate > ticker['last']:
TypeError: '>' not supported between instances of 'NoneType' and 'float'
  ```

**Comment by lwrd** [comment]
I have a similar problem but with binance2. It just dies, restarts itself, makes the same order again and dies again. I don't know how to reproduce this bug, because forcebuy works just fine. Here is some verbose without any -v arguments (kinda useless).
`2020-04-13 15:23:24,820 - freqtrade.wallets - INFO - Wallets synced.
2020-04-13 15:23:24,822 - freqtrade.freqtradebot - INFO - Buy signal found: about create a new trade with stake_amount: 0.002 ...
2020-04-13 15:23:24,822 - freqtrade.freqtradebot - INFO - Executing Buy for XTZ/BTC
2020-04-13 15:23:24,822 - freqtrade.freqtradebot - INFO - Using Last Bid / Last Price
2020-04-13 15:23:27,821 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2020-04-13 15:23:27,821 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2020-04-13 15:23:28,258 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2020-04-13 15:23:28,259 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...   `

**Comment by xmatthias** [comment]
well - you spoiled the result yourself...

freqtrade does not support futures. It's highly experimental to use this (as said in #2940 ) ... and if it doesn't work - well ... 
I assume that the value binance returns for futures does not correspond with the expectation...

Either way - using `use_order_book: true` (on both bid and ask strategy) might help with this error as it avoids the branch that's failing and doesn't use `fetch_ticker()`.

**Comment by Kenzo02** [comment]
I am also testing this feature and using /forcebuy BNB/USDT
I then used the /forcesell 1 command
to force sell it, this is my log, hope it helps a little more to improve freqtrade
config file (https://github.com/freqtrade/freqtrade/issues/2940#issuecomment-587531724)
```
2020-04-14 02:40:16,714 - freqtrade.worker - INFO - Changing state to: RELOAD_CONF
2020-04-14 02:40:16,716 - freqtrade.worker - INFO - Bot heartbeat. PID=3324, version='develop-4d80f52d', state='RELOAD_CONF'
2020-04-14 02:40:16,716 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2020-04-14 02:40:16,716 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
2020-04-14 02:40:45,943 - freqtrade.configuration.configuration - INFO - Using config: config_futures.json ...
2020-04-14 02:40:45,947 - freqtrade.loggers - INFO - Verbosity set to 0
2020-04-14 02:40:45,947 - freqtrade.configuration.configuration - INFO - Runmode set to live.
2020-04-14 02:40:45,947 - freqtrade.configuration.configuration - INFO - Parameter --db-url detected ...
2020-04-14 02:40:45,947 - freqtrade.configuration.configuration - WARNING - `forcebuy` RPC message enabled.
2020-04-14 02:40:45,947 - freqtrade.configuration.configuration - INFO - Dry run is disabled
2020-04-14 02:40:45,947 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:///strategy_features.sqlite"
2020-04-14 02:40:45,947 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 6 ...
2020-04-14 02:40:45,947 - freqtrade.configuration.configuration - INFO - Using user-data directory: /root/ta-lib/freqtrade/user_data ...
2020-04-14 02:40:45,947 - freqtrade.configuration.configuration - INFO - Using data directory: /root/ta-lib/freqtrade/user_data/data/binance ...
2020-04-14 02:40:45,948 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2020-04-14 02:40:45,948 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2020-04-14 02:40:45,948 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2020-04-14 02:40:45,948 - freqtrade.freqtradebot - INFO - Starting freqtrade develop-4d80f52d
2020-04-14 02:40:45,950 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy DemoStrategy1 from '/root/ta-lib/freqtrade/user_data/strategies/DemoStrategy1_25_03.py'...
2020-04-14 02:40:45,950 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ticker_interval' with value in config file: 5m.
2020-04-14 02:40:45,950 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2020-04-14 02:40:45,950 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 10.
2020-04-14 02:40:45,950 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'buy': 10, 'sell': 30}.
2020-04-14 02:40:45,951 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'use_sell_signal' with value in config file: True.
2020-04-14 02:40:45,951 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'sell_profit_only' with value in config file: True.
2020-04-14 02:40:45,951 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ignore_roi_if_buy_signal' with value in config file: True.
2020-04-14 02:40:45,951 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 0.04}
2020-04-14 02:40:45,951 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ticker_interval: 5m
2020-04-14 02:40:45,951 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.18
2020-04-14 02:40:45,951 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2020-04-14 02:40:45,951 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2020-04-14 02:40:45,951 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2020-04-14 02:40:45,951 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
2020-04-14 02:40:45,951 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'market', 'stoploss_on_exchange': False}
2020-04-14 02:40:45,951 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
2020-04-14 02:40:45,951 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2020-04-14 02:40:45,951 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 10
2020-04-14 02:40:45,951 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 20
2020-04-14 02:40:45,951 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'buy': 10, 'sell': 30}
2020-04-14 02:40:45,951 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_sell_signal: True
2020-04-14 02:40:45,952 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_only: True
2020-04-14 02:40:45,952 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_buy_signal: True
2020-04-14 02:40:45,952 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2020-04-14 02:40:45,953 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'options': {'defaultType': 'future'}, 'verify': False}
2020-04-14 02:40:45,957 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 100, 'aiohttp_trust_env': False, 'options': {'defaultType': 'future'}}
2020-04-14 02:40:45,961 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2020-04-14 02:40:46,379 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2020-04-14 02:40:46,612 - freqtrade.wallets - INFO - Wallets synced.
2020-04-14 02:40:46,616 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from '/root/ta-lib/freqtrade/freqtrade/pairlist/StaticPairList.py'...
2020-04-14 02:40:46,616 - freqtrade.rpc.rpc_manager - INFO - Enabling rpc.telegram ...
2020-04-14 02:40:47,857 - freqtrade.rpc.telegram - INFO - rpc.telegram is listening for following commands: [['status'], ['profit'], ['balance'], ['start'], ['stop'], ['forcesell'], ['forcebuy'], ['performance'], ['daily'], ['count'], ['reload_conf'], ['show_config'], ['stopbuy'], ['whitelist'], ['blacklist'], ['edge'], ['help'], ['version']]
2020-04-14 02:40:47,893 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'config reloaded'}
2020-04-14 02:40:48,867 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'running'}
2020-04-14 02:40:49,311 - freqtrade.worker - INFO - Changing state to: RUNNING
2020-04-14 02:40:49,311 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': custom, 'status': "*Exchange:* `binance`\n*Stake per trade:* `10 USDT`\n*Minimum ROI:* `{'0': 0.04}`\n*Stoploss:* `-0.18`\n*Ticker Interval:* `5m`\n*Strategy:* `DemoStrategy1`"}
2020-04-14 02:40:49,759 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': "Searching for USDT pairs to buy and sell based on [{'StaticPairList': 'StaticPairList'}]"}
2020-04-14 02:40:50,208 - freqtrade.persistence - INFO - Found open trade: Trade(id=1, pair=BNB/USDT, amount=0.06000000, open_rate=15.23200000, open_since=2020-04-14 02:29:45)
2020-04-14 02:40:52,750 - freqtrade.worker - INFO - Bot heartbeat. PID=3324, version='develop-4d80f52d', state='RUNNING'
2020-04-14 02:40:53,658 - freqtrade.rpc.telegram - INFO - Executing handler: _status for chat_id: 469706767
2020-04-14 02:40:53,659 - freqtrade.rpc.telegram - INFO - Executing handler: _status_table for chat_id: 469706767
2020-04-14 02:40:53,661 - freqtrade.freqtradebot - INFO - Getting price from order book Ask side.
2020-04-14 02:41:52,802 - freqtrade.worker - INFO - Bot heartbeat. PID=3324, version='develop-4d80f52d', state='RUNNING'
2020-04-14 02:41:55,383 - freqtrade.rpc.telegram - INFO - Executing handler: _status for chat_id: 469706767
2020-04-14 02:41:55,383 - freqtrade.rpc.telegram - INFO - Executing handler: _status_table for chat_id: 469706767
2020-04-14 02:41:55,386 - freqtrade.freqtradebot - INFO - Getting price from order book Ask side.
2020-04-14 02:42:52,837 - freqtrade.worker - INFO - Bot heartbeat. PID=3324, version='develop-4d80f52d', state='RUNNING'
2020-04-14 02:42:56,506 - freqtrade.rpc.telegram - INFO - Executing handler: _status for chat_id: 469706767
2020-04-14 02:42:56,506 - freqtrade.rpc.telegram - INFO - Executing handler: _status_table for chat_id: 469706767
2020-04-14 02:42:56,509 - freqtrade.freqtradebot - INFO - Getting price from order book Ask side.
2020-04-14 02:43:29,123 - freqtrade.rpc.telegram - INFO - Executing handler: _status for chat_id: 469706767
2020-04-14 02:43:29,123 - freqtrade.rpc.telegram - INFO - Executing handler: _status_table for chat_id: 469706767
2020-04-14 02:43:29,125 - freqtrade.freqtradebot - INFO - Getting price from order book Ask side.
2020-04-14 02:43:52,873 - freqtrade.worker - INFO - Bot heartbeat. PID=3324, version='develop-4d80f52d', state='RUNNING'
2020-04-14 02:44:52,908 - freqtrade.worker - INFO - Bot heartbeat. PID=3324, version='develop-4d80f52d', state='RUNNING'
2020-04-14 02:45:01,085 - freqtrade.rpc.telegram - INFO - Executing handler: _status for chat_id: 469706767
2020-04-14 02:45:01,085 - freqtrade.rpc.telegram - INFO - Executing handler: _status_table for chat_id: 469706767
2020-04-14 02:45:01,087 - freqtrade.freqtradebot - INFO - Getting price from order book Ask side.
2020-04-14 02:45:03,297 - ccxt.base.exchange - WARNING - binance requires to release all resources with an explicit call to the .close() coroutine. If you are using the exchange instance with async coroutines, add exchange.close() to your code into a place when you're done with the exchange and don't need the exchange instance anymore (at the end of your async coroutine).
2020-04-14 02:45:03,297 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f8e4b1d1f98>
2020-04-14 02:45:03,297 - asyncio - ERROR - Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f8e496c9938>, 5031.896668704), (<aiohttp.client_proto.ResponseHandler object at 0x7f8e48665388>, 5034.235050726), (<aiohttp.client_proto.ResponseHandler object at 0x7f8e48665590>, 5034.242860705), (<aiohttp.client_proto.ResponseHandler object at 0x7f8e482bdb40>, 5034.330098151)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f8e4b1d1ef0>
2020-04-14 02:45:03,298 - ccxt.base.exchange - WARNING - binance requires to release all resources with an explicit call to the .close() coroutine. If you are using the exchange instance with async coroutines, add exchange.close() to your code into a place when you're done with the exchange and don't need the exchange instance anymore (at the end of your async coroutine).
2020-04-14 02:45:03,299 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f8e4856d5c0>
2020-04-14 02:45:03,299 - asyncio - ERROR - Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f8e482bd250>, 5331.977110701), (<aiohttp.client_proto.ResponseHandler object at 0x7f8e482bd5f8>, 5333.176713773), (<aiohttp.client_proto.ResponseHandler object at 0x7f8e48462798>, 5334.318313572), (<aiohttp.client_proto.ResponseHandler object at 0x7f8e482bde80>, 5334.324914759)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f8e4856d898>
2020-04-14 02:45:53,513 - freqtrade.worker - INFO - Bot heartbeat. PID=3324, version='develop-4d80f52d', state='RUNNING'
2020-04-14 02:46:29,109 - freqtrade.rpc.telegram - INFO - Executing handler: _status for chat_id: 469706767
2020-04-14 02:46:29,109 - freqtrade.rpc.telegram - INFO - Executing handler: _status_table for chat_id: 469706767
2020-04-14 02:46:29,112 - freqtrade.freqtradebot - INFO - Getting price from order book Ask side.
2020-04-14 02:46:53,546 - freqtrade.worker - INFO - Bot heartbeat. PID=3324, version='develop-4d80f52d', state='RUNNING'
2020-04-14 02:47:07,855 - freqtrade.rpc.telegram - INFO - Executing handler: _forcesell for chat_id: 469706767
2020-04-14 02:47:07,883 - freqtrade.freqtradebot - INFO - Getting price from order book Ask side.
2020-04-14 02:47:08,725 - freqtrade.wallets - INFO - Wallets synced.
2020-04-14 02:47:08,725 - freqtrade.rpc.telegram - ERROR - Exception occurred within Telegram module
Traceback (most recent call last):
  File "/root/ta-lib/freqtrade/freqtrade/rpc/telegram.py", line 51, in wrapper
    return command_handler(self, *args, **kwargs)
  File "/root/ta-lib/freqtrade/freqtrade/rpc/telegram.py", line 437, in _forcesell
    msg = self._rpc_forcesell(trade_id)
  File "/root/ta-lib/freqtrade/freqtrade/rpc/rpc.py", line 460, in _rpc_forcesell
    _exec_forcesell(trade)
  File "/root/ta-lib/freqtrade/freqtrade/rpc/rpc.py", line 437, in _exec_forcesell
    self._freqtrade.execute_sell(trade, current_rate, SellType.FORCE_SELL)
  File "/root/ta-lib/freqtrade/freqtrade/freqtradebot.py", line 1235, in execute_sell
    amount = self._safe_sell_amount(trade.pair, trade.amount)
  File "/root/ta-lib/freqtrade/freqtrade/freqtradebot.py", line 1203, in _safe_sell_amount
    f"Not enough amount to sell. Trade-amount: {amount}, Wallet: {wallet_amount}")
freqtrade.exceptions.DependencyException: Not enough amount to sell. Trade-amount: 0.06, Wallet: 0
```

**Comment by xmatthias** [comment]
To me, supporting futures is currently not a priority (especially considering that it's usage without leverage is very limited) - and therefore many other issues / enhancements need to be solved before considering supporting Binance futures.


If we get small PR's fixing issues that arries / slowly adding support for this that's fine - 
but I don't plan on spending any time on this for now, as there's enough to do without trying to support another type of product.

Thanks for your understanding.

**Comment by xmatthias** [comment]
The way futures work (usually) is that once you buy the future, it's not added to balance, but instead counts as "open position".
Since this is not available via the default /balance endpoint, trading futures is not a dropin replacement.

For that and the following 2 reasons, I'm going to close:

* we will not be working on futures until ccxt has unified this part. That's due sometime in 2020Q2 AFAIK - however until then, implementation attempts will be limited to one exchange - which is unnecessary effort on our side.
* Especially on binance, i don't understand the fuss about futures. There is only 7 pairs available as futures - so any effort which only benefits Binance (and no other exchanges - see point one) would not provide enough benefit at this point in time.

side note:
Also when ccxt has this part unified, we cannot guarantee a timeline for Futures, and it will most likely not be right after they have implemented this part.

**Comment by nikolaos83** [comment]
Don't quote me on that but as I can see Binance Futures has 32 tradeable pairs at the moment.

I have been using a commercial trade bot until the limitations made look in another way, upon which I have stumbled across Freqtrade (today), so I'm still trying to understand what's going on here but I might still be able to make a contribution. The bot I used to use lets me set a leverage for almost any exchange except BinanceFutures. For Binance Futures it says, "you have to set leverage on the exchange itself." Maybe that would give you a clue about the problem.

I'll be studying and I'll try to contribute when I can.

**Comment by xmatthias** [comment]
@nikolaos83 
Its not about knowing the problem or the solution, but about the fact that we will not fix it per exchange, but instead wait for ccxt to have this part unified.
Otherwise, the maintenance burden of this unification becomes a problem we have to maintain, which freqtrade, as a project, does not have the capacity (its voluntairs only, donating their free time to keep freqtrade running).
Unification across exchanges is what ccxt is for, so we will not rush implementing futures without ccxt, duplicating their efforts, taking some decisions differently, and therefore waste a lot of time and efforts.

So even if we were to get it solved for binance, it would not be solved for ftx, or for kraken or any other exchange, which would require another, custom solution. Therefore, we will not implement a solution custom to binance.

There are enough other issues and enhancements to work on other than futures.

Its great if youre ready to help out, best use one of the open issues not related to futures to get started, this will help the most.

Thanks, and looking forward to your conrributions.
