### ISSUE TITLE
Bitfinex2 crash when buy signal triggers. Year is out of range. 

### ISSUE THREAD

**Issue by lwrd** [freqtrade/freqtrade#3163]
## Step 1: Have you search for this issue before posting it?

Yes.

## Step 2: Describe your environment

  * Operating system: Linux with docker
  * Python Version: 3.8.2 
  * CCXT version: 1.26.12 
  * Branch: Master 
  * Last Commit ID: 3156 , i guess
  
## Step 3: Describe the problem:

I am using bitfinex2 api. My strategy uses buy signals and when they triggers, bot creates trade and buys tokens, but then just crashes and restarts itself. After restart bot creates the same trade (buys same token again) so I guess it doesn't record its actions in DB. Check logs below.

### Relevant code exceptions or logs:

  ```
  2020-04-13 16:30:48,417 - freqtrade.strategy.interface - DEBUG - Populating indicators for pair ETC/BTC.
2020-04-13 16:30:48,420 - freqtrade.strategy.interface - DEBUG - Populating buy signals for pair ETC/BTC.
2020-04-13 16:30:48,425 - freqtrade.strategy.interface - DEBUG - Populating sell signals for pair ETC/BTC.
2020-04-13 16:30:48,429 - freqtrade.strategy.interface - DEBUG - Loop Analysis Launched
2020-04-13 16:30:48,430 - freqtrade.strategy.interface - DEBUG - trigger: 2020-04-13 16:00:00+00:00 (pair=ETC/BTC) buy=True sell=False
2020-04-13 16:30:49,785 - freqtrade.wallets - INFO - Wallets synced.
2020-04-13 16:30:49,791 - freqtrade.freqtradebot - INFO - Buy signal found: about create a new trade with stake_amount: 0.002 ...
2020-04-13 16:30:49,791 - freqtrade.freqtradebot - INFO - Executing Buy for ETC/BTC
2020-04-13 16:30:49,792 - freqtrade.freqtradebot - INFO - Using Last Bid / Last Price
2020-04-13 16:30:52,797 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2020-04-13 16:30:52,798 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2020-04-13 16:30:52,798 - freqtrade.rpc.rpc_manager - DEBUG - Forwarding message to rpc.telegram
2020-04-13 16:30:53,215 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2020-04-13 16:30:53,216 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
2020-04-13 16:30:53,216 - freqtrade.rpc.rpc_manager - DEBUG - Cleaning up rpc.telegram ...
2020-04-13 16:30:53,217 - JobQueue - DEBUG - JobQueue thread stopped
2020-04-13 16:31:00,668 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
File "/freqtrade/freqtrade/main.py", line 36, in main
return_code = args['func'](args)
File "/freqtrade/freqtrade/commands/trade_commands.py", line 20, in start_trading
worker.run()
File "/freqtrade/freqtrade/worker.py", line 66, in run
state = self._worker(old_state=state)
File "/freqtrade/freqtrade/worker.py", line 104, in _worker
self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
File "/freqtrade/freqtrade/worker.py", line 125, in _throttle
result = func(*args, **kwargs)
File "/freqtrade/freqtrade/worker.py", line 139, in _process_running
self.freqtrade.process()
File "/freqtrade/freqtrade/freqtradebot.py", line 155, in process
self.enter_positions()
File "/freqtrade/freqtrade/freqtradebot.py", line 221, in enter_positions
trades_created += self.create_trade(pair)
File "/freqtrade/freqtrade/freqtradebot.py", line 427, in create_trade
return self.execute_buy(pair, stake_amount)
File "/freqtrade/freqtrade/freqtradebot.py", line 479, in execute_buy
order = self.exchange.buy(pair=pair, ordertype=order_type,
File "/freqtrade/freqtrade/exchange/exchange.py", line 528, in buy
return self.create_order(pair, ordertype, 'buy', amount, rate, params)
File "/freqtrade/freqtrade/exchange/exchange.py", line 498, in create_order
return self._api.create_order(pair, ordertype, side,
File "/usr/local/lib/python3.8/site-packages/ccxt/bitfinex2.py", line 791, in create_order
return self.parse_order(order, market)
File "/usr/local/lib/python3.8/site-packages/ccxt/bitfinex2.py", line 707, in parse_order
'datetime': self.iso8601(timestamp),
File "/usr/local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 960, in iso8601
utc = datetime.datetime.utcfromtimestamp(timestamp // 1000)
ValueError: year 52253 is out of range
  ```

**Comment by xmatthias** [comment]
are you certain about the version of ccxt used when this error was created?
DId you verify the ccxt version from within the docker image?
It may be installed now (or locally) - but maybe an older version of ccxt was installed when the bot that created this message was started.

It seems odd to me as 1.26.12 was only released today (8 hours ago) ... and it wasn't in any official docker image up until a few minutes ago.

in addition to that, the line that triggers the error (line 707 of bitfinex2.py - https://github.com/ccxt/ccxt/blob/b6cff4dcd213b82b8c32794b177e57316ef8a959/python/ccxt/bitfinex2.py#L707 ) is not what is shown in the stacktrace, so i would think that the problem is fixed in ccxt already.


Best make sure you're using the latest ccxt version (1.26.12) within docker (!!) - and restart the bot, to verify the problem still occurs.


If it does, then this seems to be related to https://github.com/ccxt/ccxt/issues/6686 ... so if you're certain that the verison you're using is the correct one, best comment to that issue (or raise a new issue against ccxt) - best with some sample code.

Also note that bitfinex is not an exchange freqtrade officially supports (i don't have an account there, so verifying issues will not be possible).

**Comment by lwrd** [comment]
It's very annoying question, but how do I update ccxt within docker in case i used docker-compose way to install the bot? I mean, it is very unintuitive.

**Comment by xmatthias** [comment]
Usually, you don't want to use different dependencies.
However, you can simply pull the lastest develop image.
It includes ccxt 1.26.12 as of yesterday evening.

Otherwise, you'll need to create a dockerfile and build the image yourself (best use `Dockerfile.technical`  as an example - and uncomment the "build" section of the docker-compose file).

Also - it's not unintuitive if you understand docker.
If you don't have a basic understanding of docker - well - then many things can be difficult while running docker - and teaching docker is clearly out of scope for this project.

We do provide samples for frequent usecases - using an additional dependency is one of these (therefore we have the example for that in `Dockerfile.technical`).

**Comment by lwrd** [comment]
Thanks for your answer. However, even uptodate ccxt raises similar exceptions on bitfinex2 api. I guess it's very unreliable at this moment.

**Comment by xmatthias** [comment]
well - as @hroff-1902 explained on slack - bitfinex has many issues (although i'm not sure which ones, as i've never tried bitfinex ...).

This however seems to be an issue worth posting against ccxt... (although to be clear, i won't be doing that as i lack the time to test on yet another exchange we don't support ...  ).

**Comment by hroff-1902** [comment]
> well - as @hroff-1902 explained on slack - bitfinex has many issues (although i'm not sure which ones, as i've never tried bitfinex ...).

No, it's BitMEX with lot's of issues; I've never tried bitfinex
