### ISSUE TITLE
Error with add_max_drawdown from plot-profit

### ISSUE THREAD

**Issue by Pauldesco** [freqtrade/freqtrade#3164]
## Step 2: Describe your environment

  * Operating system: Windows 7 x64
  * Python Version: 3.7.6
  * Branch: Master
  * Freqtrade 2020.3
  
## Step 3: Describe the problem:
When i run plot-profit command with dryrun sqlite db, i have a KeyError as below.
If i remove line 407 in file "plotting.py"  "fig = add_max_drawdown(fig, 2, trades, df_comb)", it works.

### Steps to reproduce:

  1. download sqlite DB: [tradesv3.dryrun_01.zip](https://github.com/freqtrade/freqtrade/files/4470731/tradesv3.dryrun_01.zip)
  2. add these pair in config file "SOL/BTC",  "DASH/BTC", "KNC/BTC", "BCH/BTC", "ETC/BTC", "HBAR/BTC".
  3. Download 5m data
  3. run plot-profit command: freqtrade plot-profit --db-url sqlite:///tradesv3.dryrun_01.sqlite --trade-source DB --timerange=20200407-20200413
  
### Relevant code exceptions or logs:

  ```

freqtrade plot-profit --db-url sqlite:///tradesv3.dryrun_01.sqlite --trade-source DB --timerange=20200407-



2020-04-13 19:15:08,908 - freqtrade.loggers - INFO - Verbosity set to 0
2020-04-13 19:15:08,908 - freqtrade.configuration.configuration - INFO - Parameter --db-url detected ...
2020-04-13 19:15:08,908 - freqtrade.configuration.configuration - INFO - Parameter --timerange detected: 20200407- ...
2020-04-13 19:15:08,908 - freqtrade.configuration.configuration - INFO - Using user-data directory: D:\Google Drive\CryptoProject\ft_userdata_bin_ex1\user_data ...
2020-04-13 19:15:08,908 - freqtrade.configuration.configuration - INFO - Using data directory: D:\Google Drive\CryptoProject\ft_userdata_bin_ex1\user_data\data\binance ...
2020-04-13 19:15:08,908 - freqtrade.configuration.configuration - INFO - Using trades from: DB
2020-04-13 19:15:08,908 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2020-04-13 19:15:08,908 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2020-04-13 19:15:08,908 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2020-04-13 19:15:08,908 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2020-04-13 19:15:08,923 - freqtrade.data.history.idatahandler - WARNING - Missing data at start for pair SOL/BTC, data starts at 2020-04-10 04:00:00
2020-04-13 19:15:10,202 - numexpr.utils - INFO - NumExpr defaulting to 8 threads.
2020-04-13 19:15:10,202 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "pandas\_libs\index.pyx", line 463, in pandas._libs.index.DatetimeEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 998, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1005, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 1586792985034830000

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 2646, in get_loc
    return self._engine.get_loc(key)
  File "pandas\_libs\index.pyx", line 433, in pandas._libs.index.DatetimeEngine.get_loc
  File "pandas\_libs\index.pyx", line 465, in pandas._libs.index.DatetimeEngine.get_loc
KeyError: Timestamp('2020-04-13 15:49:45.034830+0000', tz='UTC')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pandas\_libs\index.pyx", line 463, in pandas._libs.index.DatetimeEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 998, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1005, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 1586792985034830000

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\freqtrade\main.py", line 36, in main
    return_code = args['func'](args)
  File "c:\programdata\anaconda3\lib\site-packages\freqtrade\commands\plot_commands.py", line 36, in start_plot_profit
    plot_profit(config)
  File "c:\programdata\anaconda3\lib\site-packages\freqtrade\plot\plotting.py", line 505, in plot_profit
    trades, config.get('ticker_interval', '5m'))
  File "c:\programdata\anaconda3\lib\site-packages\freqtrade\plot\plotting.py", line 407, in generate_profit_graph
    fig = add_max_drawdown(fig, 2, trades, df_comb)
  File "c:\programdata\anaconda3\lib\site-packages\freqtrade\plot\plotting.py", line 134, in add_max_drawdown
    df_comb.loc[highdate, 'cum_profit'],
  File "c:\programdata\anaconda3\lib\site-packages\pandas\core\indexing.py", line 1762, in __getitem__
    return self._getitem_tuple(key)
  File "c:\programdata\anaconda3\lib\site-packages\pandas\core\indexing.py", line 1272, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "c:\programdata\anaconda3\lib\site-packages\pandas\core\indexing.py", line 1389, in _getitem_lowerdim
    section = self._getitem_axis(key, axis=i)
  File "c:\programdata\anaconda3\lib\site-packages\pandas\core\indexing.py", line 1965, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "c:\programdata\anaconda3\lib\site-packages\pandas\core\indexing.py", line 625, in _get_label
    return self.obj._xs(label, axis=axis)
  File "c:\programdata\anaconda3\lib\site-packages\pandas\core\generic.py", line 3537, in xs
    loc = self.index.get_loc(key)
  File "c:\programdata\anaconda3\lib\site-packages\pandas\core\indexes\datetimes.py", line 699, in get_loc
    return Index.get_loc(self, key, method, tolerance)
  File "c:\programdata\anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas\_libs\index.pyx", line 433, in pandas._libs.index.DatetimeEngine.get_loc
  File "pandas\_libs\index.pyx", line 465, in pandas._libs.index.DatetimeEngine.get_loc
KeyError: Timestamp('2020-04-13 15:49:45.034830+0000', tz='UTC')
  ```

**Comment by xmatthias** [comment]
Best switch to the develop branch - this was fixed in #3127 and will be part of the next release.
