### ISSUE TITLE
Telegram Issue - New Docker Install on AWS

### ISSUE THREAD

**Issue by liamodev** [freqtrade/freqtrade#3165]
## Step 1: Have you search for this issue before posting it?

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/freqtrade/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

  * Operating system: Ubuntu 18.04
  * Python Version: 2.7.17
  * CCXT version: ??
  * Branch: Develop
  * Last Commit ID: ??
  
## Step 3: Describe the problem:

*Explain the problem you have encountered*

New AWS server running Ubuntu, fresh Freqtrade Docker install following the instructions here - https://www.freqtrade.io/en/latest/docker/ (done in the last couple of hours)

When run trade there is a Telegram error.

I have searched the other issues and wasn't able to find this same error when installed via Docker.

### Steps to reproduce:

  1. Install Freqtrade via Docker (https://www.freqtrade.io/en/latest/docker/)
  2. Add Binance and Telegram details to config file
  3. Run docker-compose run --rm freqtrade trade --config user_data/config.json --strategy SampleStrategy

Note: backtesting is working fine.
  
### Observed Results:

  * What happened? Telegram error below.
  * What did you expect to happen? Freqtrade to run normally.

### Relevant code exceptions or logs:

  ```
 2020-04-14 06:25:20,257 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'sell_profit_only' with value in config file: False.
2020-04-14 06:25:20,261 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
2020-04-14 06:25:20,261 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'market', '  File "/usr/local/lib/python3.8/site-packages/telegram/utils/request.py", line 249, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/updater.py", line 336, in polling_action_cb
    if not action_cb():
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/updater.py", line 336, in polling_action_cb
    updates = self.bot.get_updates(self.last_update_id,
  File "<decorator-gen-31>", line 2, in get_updates
  File "/usr/local/lib/python3.8/site-packages/telegram/bot.py", line 67, in decorator
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/telegram/bot.py", line 2067, in get_updates
    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
  File "/usr/local/lib/python3.8/site-packages/telegram/utils/request.py", line 331, in post
    result = self._request_wrapper('POST', url,
  File "/usr/local/lib/python3.8/site-packages/telegram/utils/request.py", line 249, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2020-04-14 06:31:05,845 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2020-04-14 06:31:05,845 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/updater.py", line 378, in _network_loop_retry
    if not action_cb():
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/updater.py", line 336, in polling_action_cb
    updates = self.bot.get_updates(self.last_update_id,
  File "<decorator-gen-31>", line 2, in get_updates
  File "/usr/local/lib/python3.8/site-packages/telegram/bot.py", line 67, in decorator
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/telegram/bot.py", line 2067, in get_updates
    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
2020-04-14 06:31:29,786 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2020.3', state='RUNNING'
2020-04-14 06:31:40,462 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2020-04-14 06:31:40,462 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/updater.py", line 378, in _network_loop_retry
    updates = self.bot.get_updates(self.last_update_id,
  File "<decorator-gen-31>", line 2, in get_updates
  File "/usr/local/lib/python3.8/site-packages/telegram/bot.py", line 67, in decorator
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/telegram/bot.py", line 2067, in get_updates
    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
  File "/usr/local/lib/python3.8/site-packages/telegram/utils/request.py", line 331, in post
    result = self._request_wrapper('POST', url,
  File "/usr/local/lib/python3.8/site-packages/telegram/utils/request.py", line 249, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
^C2020-04-14 06:32:13,067 - freqtrade.commands.trade_commands - INFO - SIGINT received, aborting ...
2020-04-14 06:32:13,067 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2020-04-14 06:32:13,067 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2020-04-14 06:32:13,550 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2020-04-14 06:32:13,550 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
2020-04-14 06:32:15,091 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

  ```

**Comment by xmatthias** [comment]
> 2020-04-14 06:31:40,462 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

Well - to me, this seems like you're reusing the same bot-token for a 2nd instance (maybe unintentionally ...).

One freqtrade instance can only tie to one Telegram bot - and one Telegram-bot can only control one freqtrade instance.


Please make sure to stop all other bots (maybe on other servers / your pc?) - or create a new telegram bot and use that token instead.

Also, ensure that only one instance is running by using `docker ps` - and checking the output for multiple containers that are running.

**Comment by liamodev** [comment]
Hi, I wasn't running on another server and hadn't for a while. I generated a new key and that fixed it.

Many thanks,
