### ISSUE TITLE
Hyperopt - optimizer.py Error

### ISSUE THREAD

**Issue by magkia** [freqtrade/freqtrade#3167]
## Step 1: Have you search for this issue before posting it?

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/freqtrade/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

  * Operating system: _Ubuntu 18.04___
  * Python Version: _3.6__ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Branch:  Develop
  * Last Commit ID: __c8ccdbcb9a63aefe0a2ea1e1cbd4a7c075b4d5c6___ (`git log --format="%H" -n 1`)
  
## Step 3: Describe the problem:

When I run the Hyperopt with 100 or more evaluations I get an error from optimizer.py 
I don't get the any error when i do less than 50 evaluations

terminal command => freqtrade hyperopt --config config.json --strategy BBStrategy --hyperopt BbrsiHyperOpts --hyperopt-loss SharpeHyperOptLoss -e 100 --spaces all

### Steps to reproduce:

  1.  Terminal command to run hyperopt 

freqtrade hyperopt --config config.json --strategy BBStrategy --hyperopt BbrsiHyperOpts --hyperopt-loss SharpeHyperOptLoss -e 100 --spaces all

  2. _____
  3. _____
  
### Observed Results:

  * What happened?
I received the error below
  * What did you expect to happen?
I expected it to print the the results as normal

### Relevant code exceptions or logs:
[Epoch 25 of 100 ( 25%)] |████████████████████████\                                                                        | [ETA:   0:00:44, Elapsed Time: 0:00:14]
2020-04-14 19:36:21,830 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/algo/freqtrade/freqtrade/main.py", line 36, in main
    return_code = args['func'](args)
  File "/home/algo/freqtrade/freqtrade/commands/optimize_commands.py", line 81, in start_hyperopt
    hyperopt.start()
  File "/home/algo/freqtrade/freqtrade/optimize/hyperopt.py", line 706, in start
    asked = self.opt.ask(n_points=current_jobs)
  File "/home/algo/freqtrade/.env/lib/python3.6/site-packages/skopt/optimizer/optimizer.py", line 382, in ask
    opt._tell(x, y_lie)
  File "/home/algo/freqtrade/.env/lib/python3.6/site-packages/skopt/optimizer/optimizer.py", line 559, in _tell
    exp_logits = np.exp(self.eta * logits)
FloatingPointError: underflow encountered in exp

thanks in advance :)

**Comment by magkia** [comment]
Hello,

To add more info, I get the same issue with _**sample_strategy**_ and **_sample_hyperopt_**

(.env) algo@algo-VirtualBox:~/freqtrade$ freqtrade hyperopt --config config.json --strategy SampleStrategy --hyperopt SampleHyperOpt --hyperopt-loss SharpeHyperOptLoss -e 500 --spaces all --timerange 20200301-20200331
2020-04-16 12:41:57,810 - freqtrade.loggers - INFO - Verbosity set to 0
2020-04-16 12:41:57,811 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 10 ...
2020-04-16 12:41:57,811 - freqtrade.configuration.configuration - INFO - Parameter --timerange detected: 20200301-20200331 ...
2020-04-16 12:41:57,811 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/algo/freqtrade/user_data ...
2020-04-16 12:41:57,812 - freqtrade.configuration.configuration - INFO - Using data directory: /home/algo/freqtrade/user_data/data/binance ...
2020-04-16 12:41:57,812 - freqtrade.configuration.configuration - INFO - Using Hyperopt class name: SampleHyperOpt
2020-04-16 12:41:57,812 - freqtrade.configuration.configuration - INFO - Parameter --epochs detected ... Will run Hyperopt with for 500 epochs ...
2020-04-16 12:41:57,812 - freqtrade.configuration.configuration - INFO - Parameter -s/--spaces detected: ['all']
2020-04-16 12:41:57,812 - freqtrade.configuration.configuration - INFO - Parameter -j/--job-workers detected: -1
2020-04-16 12:41:57,812 - freqtrade.configuration.configuration - INFO - Parameter --min-trades detected: 1
2020-04-16 12:41:57,812 - freqtrade.configuration.configuration - INFO - Using Hyperopt loss class name: SharpeHyperOptLoss
2020-04-16 12:41:57,812 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2020-04-16 12:41:57,812 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2020-04-16 12:41:57,812 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2020-04-16 12:41:57,812 - freqtrade.configuration.deprecated_settings - WARNING - DEPRECATED: Pairlists must be defined explicitly in the future.Defaulting to StaticPairList for now.
2020-04-16 12:41:57,813 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2020-04-16 12:41:57,816 - freqtrade.commands.optimize_commands - INFO - Starting freqtrade in Hyperopt mode
2020-04-16 12:41:57,816 - filelock - INFO - Lock 139868485033040 acquired on /home/algo/freqtrade/user_data/hyperopt.lock
2020-04-16 12:41:57,816 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2020-04-16 12:41:57,817 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2020-04-16 12:41:57,822 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 500}
2020-04-16 12:41:57,830 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2020-04-16 12:41:58,659 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2020-04-16 12:41:58,671 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy SampleStrategy from '/home/algo/freqtrade/user_data/strategies/sample_strategy.py'...
2020-04-16 12:41:58,672 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ticker_interval' with value in config file: 1h.
2020-04-16 12:41:58,672 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'trailing_stop' with value in config file: True.
2020-04-16 12:41:58,672 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: BTC.
2020-04-16 12:41:58,672 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 0.05.
2020-04-16 12:41:58,672 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'buy': 10, 'sell': 30}.
2020-04-16 12:41:58,672 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'use_sell_signal' with value in config file: True.
2020-04-16 12:41:58,672 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'sell_profit_only' with value in config file: False.
2020-04-16 12:41:58,672 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ignore_roi_if_buy_signal' with value in config file: False.
2020-04-16 12:41:58,672 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'60': 0.01, '30': 0.02, '0': 0.04}
2020-04-16 12:41:58,672 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ticker_interval: 1h
2020-04-16 12:41:58,672 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.1
2020-04-16 12:41:58,672 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: True
2020-04-16 12:41:58,673 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2020-04-16 12:41:58,673 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2020-04-16 12:41:58,673 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
2020-04-16 12:41:58,673 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'market', 'stoploss_on_exchange': False}
2020-04-16 12:41:58,673 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
2020-04-16 12:41:58,673 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: BTC
2020-04-16 12:41:58,674 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 0.05
2020-04-16 12:41:58,674 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 20
2020-04-16 12:41:58,674 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'buy': 10, 'sell': 30}
2020-04-16 12:41:58,674 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_sell_signal: True
2020-04-16 12:41:58,674 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_only: False
2020-04-16 12:41:58,674 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_buy_signal: False
2020-04-16 12:41:58,674 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2020-04-16 12:41:58,806 - freqtrade.resolvers.iresolver - INFO - Using resolved hyperopt SampleHyperOpt from '/home/algo/freqtrade/user_data/hyperopts/sample_hyperopt.py'...
2020-04-16 12:41:58,806 - freqtrade.resolvers.hyperopt_resolver - WARNING - Hyperopt class does not provide populate_indicators() method. Using populate_indicators from the strategy.
2020-04-16 12:41:58,886 - freqtrade.resolvers.iresolver - INFO - Using resolved hyperoptloss SharpeHyperOptLoss from '/home/algo/freqtrade/freqtrade/optimize/hyperopt_loss_sharpe.py'...
2020-04-16 12:41:58,886 - freqtrade.optimize.hyperopt - INFO - Removing `/home/algo/freqtrade/user_data/hyperopt_results/hyperopt_tickerdata.pkl`.
2020-04-16 12:41:58,889 - freqtrade.optimize.hyperopt - INFO - Removing `/home/algo/freqtrade/user_data/hyperopt_results/hyperopt_results.pickle`.
2020-04-16 12:41:58,889 - freqtrade.optimize.hyperopt - INFO - Using optimizer random state: 29449
2020-04-16 12:41:58,895 - freqtrade.data.history.history_utils - INFO - Using indicator startup period: 20 ...
2020-04-16 12:41:58,967 - freqtrade.data.converter - INFO - Missing data fillup for ETH/BTC: before: 740 - after: 741
2020-04-16 12:41:58,973 - freqtrade.data.history.idatahandler - WARNING - No history data for pair: "BNB/BTC", timeframe: 1h. Use `freqtrade download-data` to download the data
2020-04-16 12:41:59,028 - freqtrade.data.converter - INFO - Missing data fillup for LINK/BTC: before: 740 - after: 741
2020-04-16 12:41:59,032 - freqtrade.data.history.idatahandler - WARNING - No history data for pair: "BCH/BTC", timeframe: 1h. Use `freqtrade download-data` to download the data
2020-04-16 12:41:59,086 - freqtrade.data.converter - INFO - Missing data fillup for LTC/BTC: before: 740 - after: 741
2020-04-16 12:41:59,140 - freqtrade.data.converter - INFO - Missing data fillup for DASH/BTC: before: 740 - after: 741
2020-04-16 12:41:59,187 - freqtrade.data.converter - INFO - Missing data fillup for XRP/BTC: before: 740 - after: 741
2020-04-16 12:41:59,242 - freqtrade.data.converter - INFO - Missing data fillup for NEO/BTC: before: 740 - after: 741
2020-04-16 12:41:59,291 - freqtrade.data.converter - INFO - Missing data fillup for XEM/BTC: before: 740 - after: 741
2020-04-16 12:41:59,295 - freqtrade.optimize.backtesting - INFO - Loading data from 2020-02-29T04:00:00+00:00 up to 2020-03-31T00:00:00+00:00 (30 days)..
2020-04-16 12:41:59,465 - freqtrade.optimize.hyperopt - INFO - Hyperopting with data from 2020-02-29T04:00:00+00:00 up to 2020-03-31T00:00:00+00:00 (30 days)..
2020-04-16 12:41:59,488 - freqtrade.optimize.hyperopt - INFO - Found 4 CPU cores. Let's make them scream!
2020-04-16 12:41:59,488 - freqtrade.optimize.hyperopt - INFO - Number of parallel jobs set as: -1
2020-04-16 12:41:59,506 - freqtrade.optimize.hyperopt_interface - INFO - Min roi table: {0: 0.06883, 120: 0.04589, 240: 0.02294, 360: 0}
2020-04-16 12:41:59,506 - freqtrade.optimize.hyperopt_interface - INFO - Max roi table: {0: 0.71124, 480: 0.25238, 1200: 0.09177, 2640: 0}
2020-04-16 12:41:59,531 - freqtrade.optimize.hyperopt - INFO - Effective number of parallel workers used: 4
+--------+---------+----------+--------------+------------------------------+----------------+-------------+
|   Best |   Epoch |   Trades |   Avg profit |                       Profit |   Avg duration |   Objective |
|--------+---------+----------+--------------+------------------------------+----------------+-------------|
|   Best |   1/500 |       12 |       -2.59% |   -0.01553135 BTC  (-31.03%) |      1,975.0 m |     2.74548 |
|   Best |   3/500 |        8 |        1.78% |    0.00712326 BTC   (14.23%) |      2,302.5 m |    -2.85873 |                                 
 [Epoch 25 of 500 (  5%)] |███\                                                                     | [ETA:   0:01:18, Elapsed Time: 0:00:04]
|   Best |  28/500 |        9 |        2.67% |    0.01204425 BTC   (24.06%) |      2,053.3 m |    -4.29401 |
2020-04-16 12:42:08,433 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/algo/freqtrade/freqtrade/main.py", line 36, in main
    return_code = args['func'](args)
  File "/home/algo/freqtrade/freqtrade/commands/optimize_commands.py", line 81, in start_hyperopt
    hyperopt.start()
  File "/home/algo/freqtrade/freqtrade/optimize/hyperopt.py", line 706, in start
    asked = self.opt.ask(n_points=current_jobs)
  File "/home/algo/freqtrade/.env/lib/python3.6/site-packages/skopt/optimizer/optimizer.py", line 382, in ask
    opt._tell(x, y_lie)
  File "/home/algo/freqtrade/.env/lib/python3.6/site-packages/skopt/optimizer/optimizer.py", line 559, in _tell
    exp_logits = np.exp(self.eta * logits)
FloatingPointError: underflow encountered in exp

Thanks in advance

**Comment by hroff-1902** [comment]
which version if sckit-optimize you are using? pls paste output of `pip list|grep scikit`

**Comment by hroff-1902** [comment]
@xmatthias this can only appear if numpy treatment for underflow is set as 'raise', and it's 'ignore' by default. Any ideas why can it be in other mode?

**Comment by xmatthias** [comment]
we set it in conftest... but that's not relevant for real runs.

I don't think pandas would touch such settings ... 
i'm more leaning towards either scikit / skopt - or some TA library (we don't know much about the above used strategy / hyperopts file ...)

**Comment by hroff-1902** [comment]
> I don't think pandas would touch such settings ...

it was before:
https://github.com/pandas-dev/pandas/blob/1d6d7d4667806f1b7bca640ffc4eb368441e2471/pandas/compat/numpy_compat.py#L9-L12

**Comment by magkia** [comment]
Hello,

I don't know why, but this morning I deleted the files .pickle and .pkl and tried  other strategy. And Hyperopt worked well
I think the problem was a corrupted file o something with .pkl or .pickle

scikit-learn            0.22.2.post1     
scikit-optimize         0.7.4       

numpy                   1.18.2      

Sorry for make both loss your time

**Comment by hroff-1902** [comment]
> and tried other strategy

I think that actually helped, not removal of the pickling file...

>Sorry for make both loss your time

That's okay, no sorry, this could be really a problem in the code, not a temporary failure due to unknown reasons... 

Feel free to reopen if it happens again.

**Comment by magkia** [comment]
Hello,
I find again this error :disappointed: 
Searching about this function "np.exp", I found this (it could be helpfull)
=> https://stackoverflow.com/questions/4359959/overflow-in-exp-in-scipy-numpy-in-python

I'll try to advance anyways, but may be there's a little bug 

Thanks in advance. Bug log below

[Epoch 22 of 50 ( 44%)] |██████████████████████████████████████|                                                  | [ETA:   0:01:11, Elapsed Time: 0:00:56]
2020-04-25 20:11:38,016 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/algo/freqtrade/freqtrade/main.py", line 36, in main
    return_code = args['func'](args)
  File "/home/algo/freqtrade/freqtrade/commands/optimize_commands.py", line 81, in start_hyperopt
    hyperopt.start()
  File "/home/algo/freqtrade/freqtrade/optimize/hyperopt.py", line 706, in start
    asked = self.opt.ask(n_points=current_jobs)
  File "/home/algo/freqtrade/.env/lib/python3.6/site-packages/skopt/optimizer/optimizer.py", line 382, in ask
    opt._tell(x, y_lie)
  File "/home/algo/freqtrade/.env/lib/python3.6/site-packages/skopt/optimizer/optimizer.py", line 559, in _tell
    exp_logits = np.exp(self.eta * logits)
FloatingPointError: underflow encountered in exp

**Comment by hroff-1902** [comment]
I do not know why, but under conda
```
python -c "import numpy;import scipy.stats;scipy.stats.norm.cdf(numpy.array([numpy.nan]));print('done')"
```
produces warnings, and silent on linux... Same for ^^ warning in skopt.

How to suppress it in a proper way?

**Comment by hroff-1902** [comment]
https://github.com/scikit-optimize/scikit-optimize/pull/903

**Comment by xmatthias** [comment]
when you say "under conda" - how did you install the dependencies (scipy and numpy explicitly)? 
via `pip` - or via conda?

**Comment by hroff-1902** [comment]
The command above in conda terminal

**Comment by hroff-1902** [comment]
The command above in conda terminal

**Comment by xmatthias** [comment]
no - when using anaconda, you have 2 ways to install packages.

you can run `pip install numpy` - or you can use `conda install numpy` (same for scipy).

Now assuming you use the "full" anaconda version, you'll have the Scientific Stack installed (so `conda install numpy` is not necessary, as the package is available already).

It's however still important to understand HOW the package was installed.

**Comment by hroff-1902** [comment]
> no - when using anaconda, you have 2 ways to install packages.
> 
> you can run `pip install numpy` - or you can use `conda install numpy` (same for scipy).
> 
> Now assuming you use the "full" anaconda version, you'll have the Scientific Stack installed (so `conda install numpy` is not necessary, as the package is available already).
> 
> It's however still important to understand HOW the package was installed, as that can make a difference.

Well, both `pip list` and `conda list` show me numpy and scipy, which one is then used? 😉 

```
(base) PS C:\Users\user> python -c "import numpy;import scipy.stats;scipy.stats.norm.cdf(numpy.array([numpy.nan]));print('done')"
C:\Users\user\anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:903: RuntimeWarning: invalid value encountered in greater
  return (a < x) & (x < b)
C:\Users\user\anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:903: RuntimeWarning: invalid value encountered in less
  return (a < x) & (x < b)
C:\Users\user\anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:1827: RuntimeWarning: invalid value encountered in greater_equal
  cond2 = (x >= np.asarray(_b)) & cond0
done
(base) PS C:\Users\user> pip list
Package                            Version
---------------------------------- -------------------
...
numpy                              1.18.1
...
scipy                              1.4.1
...
(base) PS C:\Users\user> conda list
# packages in environment at C:\Users\user\anaconda3:
#
# Name                    Version                   Build  Channel
...
numpy                     1.18.1           py37h93ca92e_0
...
scipy                     1.4.1            py37h9439919_0
...
```

**Comment by hroff-1902** [comment]
^^ And no warning at Linux, even after downgrading to `numpy=1.18.1`

**Comment by xmatthias** [comment]
well conda does not reccomend to install the same thing in 2 places ...

your best bet to find that out might be the following:
```python
import numpy as np.
print(np.__file__)
```

**Comment by hroff-1902** [comment]
```
>>> import numpy as np
>>> print(np.__file__)
C:\Users\user\anaconda3\lib\site-packages\numpy\__init__.py
>>> import numpy;import scipy.stats;scipy.stats.norm.cdf(numpy.array([numpy.nan]));print('done')
C:\Users\user\anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:903: RuntimeWarning: invalid value encountered in greater
  return (a < x) & (x < b)
C:\Users\user\anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:903: RuntimeWarning: invalid value encountered in less
  return (a < x) & (x < b)
C:\Users\user\anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:1827: RuntimeWarning: invalid value encountered in greater_equal
  cond2 = (x >= np.asarray(_b)) & cond0
array([nan])
done
>>>           
```

**Comment by xmatthias** [comment]
well this is the conda installation :)

**Comment by hroff-1902** [comment]
I know (and I updated to to the current latest), and this produces the Runtime warnings while in Linux it's silent... I've seen in the discussions, that previously it was related to conda installed and used MKL (Math Kernel Lib) and that it uses floats in the c-code instead of doubles (hence the underflow errors), but this was changed couple of years ago (no MKL installed by conda since that time)... I also tried to create wheel-based conda environment and install both numpy and scipy from wheels there -- it also did not help, same message in the sample snipped using scipy...

**Comment by xmatthias** [comment]
well best create a new, empty conda environment and test with a "real" numpy installation from pip (conda folks will hate me for this sentence) ...

**Comment by hroff-1902** [comment]
there is still chance scikit-optimize would apply my fix ^^, explicitly hiding the warning in that particular problematic place...

**Comment by xmatthias** [comment]
i struggle to recreate this exception (and honestly, have never seen it on any of my installations) ... 

I hope it's fixed by the latest scikit-optimize release (released and merged to develop a few days ago) - but can't really verify as i never ran into this problem in the first place.

maybe try removing the `.env` directory, and reinstalling the virtual environment if you're stil encountering this problem.

however since the problem is not reproducible (at least not with the information given) - and there's been no activity in the last few months, i'll close this for now.

Feel free to comment below / reopen if you are still encountering the problem with a fully updated installation.
