### ISSUE TITLE
Process dies when cancelling filled order 

### ISSUE THREAD

**Issue by si-jobe** [freqtrade/freqtrade#3175]
## Step 1: Have you search for this issue before posting it?

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/freqtrade/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

  * Operating system: Ubuntu 19.10
  * Python Version: Python 3.7.5
  * CCXT version: 1.24.83
  * Branch: Master
  * Last Commit ID: 9abfdaaaa240dcab2fbd105982ed6eed025d8936
  
## Step 3: Describe the problem:

Freqtrade tried to remove timed out trade order, that apparently went through before it was being requested for deletion. Freqtrade dies on the error message from site.

### Steps to reproduce:

  1. Make freqtrade perform an trade order
  2. Wait for order to go through
  3. Make freqtrade perform order cancelation on order that went through.
  
### Observed Results:

  * What happened? Process died upon exception message from exchange.
  * What did you expect to happen? Process not dying from this exception.

### Relevant code exceptions or logs:

  ```
020-04-16 11:16:07,480 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=140, pair=XTZ/BTC, amount=6.09902411, open_rate=0.00028540, open_since=2020-04-16 09:15:03)
2020-04-16 11:16:09,376 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2020-04-16 11:16:09,377 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2020-04-16 11:16:09,488 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2020-04-16 11:16:09,488 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
2020-04-16 11:16:09,489 - freqtrade.rpc.api_server - INFO - Stopping API Server
2020-04-16 11:16:09,880 - freqtrade.rpc.api_server - INFO - Local Rest Server started.
2020-04-16 11:16:13,218 - freqtrade - ERROR - Could not cancel order. Message: binance {"code":-2011,"msg":"Unknown order sent."}
  ```

**Comment by xmatthias** [comment]
Well these logs do not cover the most crucial part. 
Either before or after this there should be a stacktrace - without that it'll be impossible to recreate what did happen.

The error - "Could not cancel order" will not cause the bot to stop  / restart.

**Comment by si-jobe** [comment]
That's all there is at that moment. No stack trace. Though I have a stack trace 16 minutes earlier on a previous order

```
2020-04-16 11:00:18,682 - freqtrade.freqtradebot - INFO - Cannot query order for Trade(id=139, pair=XTZ/BTC, amount=6.16448067, open_rate=0.00028390, open_since=2020-04-16 09:00:17) due to Traceback (most recent call last):
  File "/home/jonas/Git/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 559, in fetch
    response.raise_for_status()
  File "/home/jonas/Git/freqtrade/.env/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order?timestamp=1587027618391&recvWindow=5000&symbol=XTZBTC&orderId=38615618&signature=26a97e98dffa44cab317023815405822aa616486b34934df2fbe225371c0e61b

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jonas/Git/freqtrade/freqtrade/exchange/exchange.py", line 932, in get_order
    return self._api.fetch_order(order_id, pair)
  File "/home/jonas/Git/freqtrade/.env/lib/python3.7/site-packages/ccxt/binance.py", line 1108, in fetch_order
    response = getattr(self, method)(self.extend(request, params))
  File "/home/jonas/Git/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 446, in inner
    return entry(_self, **inner_kwargs)
  File "/home/jonas/Git/freqtrade/.env/lib/python3.7/site-packages/ccxt/binance.py", line 1765, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/home/jonas/Git/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 465, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/jonas/Git/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 571, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/jonas/Git/freqtrade/.env/lib/python3.7/site-packages/ccxt/binance.py", line 1759, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions, error, feedback)
  File "/home/jonas/Git/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 483, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.OrderNotFound: binance {"code":-2013,"msg":"Order does not exist."}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jonas/Git/freqtrade/freqtrade/freqtradebot.py", line 861, in check_handle_timedout
    order = self.exchange.get_order(trade.open_order_id, trade.pair)
  File "/home/jonas/Git/freqtrade/freqtrade/exchange/common.py", line 113, in wrapper
    return f(*args, **kwargs)
  File "/home/jonas/Git/freqtrade/freqtrade/exchange/exchange.py", line 935, in get_order
    f'Tried to get an invalid order (id: {order_id}). Message: {e}') from e
freqtrade.exceptions.InvalidOrderException: Tried to get an invalid order (id: 38615618). Message: binance {"code":-2013,"msg":"Order does not exist."}
```

**Comment by hroff-1902** [comment]
@si-jobe hi, the fix which can resolve it was merged (current develop branch), pls verify
