### ISSUE TITLE
Hyperopt fails

### ISSUE THREAD

**Issue by hroff-1902** [freqtrade/freqtrade#3176]
Current develop, after download-data into fresh dir for 100 days, timeframe is 1h (not sure if this is relevant):
```
$ freqtrade hyperopt --hyperopt SampleHyperOpt --strategy SampleStrategy -e 10 -c config_binance.json -j 1
...
Traceback (most recent call last):
  File "/home/user/freqtrade-wrk/github-hroff-1902/freqtrade/freqtrade/main.py", line 36, in main
    return_code = args['func'](args)
  File "/home/user/freqtrade-wrk/github-hroff-1902/freqtrade/freqtrade/commands/optimize_commands.py", line 81, in start_hyperopt
    hyperopt.start()
  File "/home/user/freqtrade-wrk/github-hroff-1902/freqtrade/freqtrade/optimize/hyperopt.py", line 651, in start
    preprocessed[pair] = trim_dataframe(df, timerange)
  File "/home/user/freqtrade-wrk/github-hroff-1902/freqtrade/freqtrade/data/converter.py", line 127, in trim_dataframe
    df = df.loc[df[df_date_col] >= start, :]
AttributeError: 'NoneType' object has no attribute 'loc'
```

All dataframes in `preprocessed` are None after 
```
preprocessed = self.backtesting.strategy.ohlcvdata_to_dataframe(data)
```
in hyperopt.py

**Comment by xmatthias** [comment]
well - but you'll need to include the output of the "bot startup" as well (startup, dataloading, ...).- otherwise it's not conclusive, and impossible to investigate further.

**Comment by hroff-1902** [comment]
closing it -- populate_indicators() in my version of SampleHyperOpt existed and did not return the dataframe...

Where are our checks for dataframes returned by custom methods?

**Comment by xmatthias** [comment]
They do apply for the Strategy running ... but i don't think for either backtesting nor hyperopt.
