### ISSUE TITLE
I want to know why am getting an error when i try to run my custom hyperopt

### ISSUE THREAD

**Issue by ebuka-odih** [freqtrade/freqtrade#3271]
Whenever i try to run this command 
``python3 ./freqtrade/main.py -c config.json --customhyperopt BBRSIOPT hyperopt -e 100
``
i get this error **TypeError: reduce() of empty sequence with no initial value**

```
2020-05-08 16:12:47,685 - freqtrade.configuration - INFO - Verbosity set to 0
2020-05-08 16:12:47,685 - freqtrade.configuration - INFO - Dry run is enabled
2020-05-08 16:12:47,685 - freqtrade.configuration - INFO - Using DB: "sqlite://"
2020-05-08 16:12:47,685 - freqtrade.configuration - INFO - Using max_open_trades: 15 ...
2020-05-08 16:12:47,685 - freqtrade.configuration - INFO - Using data folder: user_data/data/binance ...
2020-05-08 16:12:47,686 - freqtrade.configuration - INFO - Parameter --epochs detected ...
2020-05-08 16:12:47,686 - freqtrade.configuration - INFO - Will run Hyperopt with for 100 epochs ...
2020-05-08 16:12:47,686 - freqtrade.configuration - INFO - Parameter -s/--spaces detected: all
2020-05-08 16:12:47,709 - freqtrade.resolvers.strategy_resolver - INFO - Using resolved strategy DefaultStrategy from '/home/emma/Desktop/Trading Bot/freqtrade/freqtrade/strategy'
2020-05-08 16:12:47,710 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ticker_interval' with value in config file: 1h.
2020-05-08 16:12:47,710 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'trailing_stop' with value in config file: False.
2020-05-08 16:12:47,711 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'40': 0.0, '30': 0.01, '20': 0.02, '0': 0.04}
2020-05-08 16:12:47,711 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ticker_interval: 1h
2020-05-08 16:12:47,711 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.1
2020-05-08 16:12:47,711 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2020-05-08 16:12:47,711 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
2020-05-08 16:12:47,711 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False}
2020-05-08 16:12:47,711 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
2020-05-08 16:12:47,712 - freqtrade.exchange - INFO - Instance is running with dry_run enabled
2020-05-08 16:12:47,712 - freqtrade.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2020-05-08 16:12:47,718 - freqtrade.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': False}
2020-05-08 16:12:47,755 - freqtrade.exchange - INFO - Using Exchange "Binance"
2020-05-08 16:12:50,020 - freqtrade.resolvers.hyperopt_resolver - INFO - Using resolved hyperopt BBRSIOPT from '/home/emma/Desktop/Trading Bot/freqtrade/freqtrade/optimize'
2020-05-08 16:12:50,431 - freqtrade.optimize.hyperopt - INFO - Found 4 CPU cores. Let's make them scream!
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/emma/Desktop/Trading Bot/freqtrade/.env/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 418, in _process_worker
    r = call_item()
  File "/home/emma/Desktop/Trading Bot/freqtrade/.env/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 272, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/emma/Desktop/Trading Bot/freqtrade/.env/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 567, in __call__
    return self.func(*args, **kwargs)
  File "/home/emma/Desktop/Trading Bot/freqtrade/.env/lib/python3.7/site-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/home/emma/Desktop/Trading Bot/freqtrade/.env/lib/python3.7/site-packages/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/emma/Desktop/Trading Bot/freqtrade/.env/lib/python3.7/site-packages/joblib/externals/loky/cloudpickle_wrapper.py", line 38, in __call__
    return self._obj(*args, **kwargs)
  File "/home/emma/Desktop/Trading Bot/freqtrade/freqtrade/optimize/hyperopt.py", line 218, in generate_optimizer
    'end_date': max_date,
  File "/home/emma/Desktop/Trading Bot/freqtrade/freqtrade/optimize/backtesting.py", line 299, in backtest
    self.advise_buy(pair_data, {'pair': pair}), {'pair': pair})[headers].copy()
  File "/home/emma/Desktop/Trading Bot/freqtrade/freqtrade/optimize/bbrsi_opt.py", line 127, in populate_sell_trend
    'sell'] = 1
TypeError: reduce() of empty sequence with no initial value
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./freqtrade/main.py", line 89, in <module>
    main(sys.argv[1:])
  File "./freqtrade/main.py", line 35, in main
    args.func(args)
  File "/home/emma/Desktop/Trading Bot/freqtrade/freqtrade/optimize/hyperopt.py", line 352, in start
    hyperopt.start()
  File "/home/emma/Desktop/Trading Bot/freqtrade/freqtrade/optimize/hyperopt.py", line 306, in start
    f_val = self.run_optimizer_parallel(parallel, asked)
  File "/home/emma/Desktop/Trading Bot/freqtrade/freqtrade/optimize/hyperopt.py", line 269, in run_optimizer_parallel
    wrap_non_picklable_objects(self.generate_optimizer))(v) for v in asked)
  File "/home/emma/Desktop/Trading Bot/freqtrade/.env/lib/python3.7/site-packages/joblib/parallel.py", line 930, in __call__
    self.retrieve()
  File "/home/emma/Desktop/Trading Bot/freqtrade/.env/lib/python3.7/site-packages/joblib/parallel.py", line 833, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/emma/Desktop/Trading Bot/freqtrade/.env/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 521, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/emma/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/home/emma/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
TypeError: reduce() of empty sequence with no initial value
```

**Comment by xmatthias** [comment]
Well, I assume you're using an old template for hyperopt. In later versions (newer than ~a year) we're cheking for this case first:

https://github.com/freqtrade/freqtrade/blob/18ec65e05f855967f6f22e5aa280037646932d1f/freqtrade/templates/sample_hyperopt.py#L84-L87

The main problem though is that there's nothing left in your space - most likely your `indicator_space()` (or `indicator_space_sell()` does not return anything.

Please also note that you're using a outdated command to run the bot, please use `freqtrade hyperopt` instead.

**Comment by ebuka-odih** [comment]
> Well, I assume you're using an old template for hyperopt. In later versions (newer than ~a year) we're cheking for this case first:
> 
> https://github.com/freqtrade/freqtrade/blob/18ec65e05f855967f6f22e5aa280037646932d1f/freqtrade/templates/sample_hyperopt.py#L84-L87
> 
> The main problem though is that there's nothing left in your space - most likely your `indicator_space()` (or `indicator_space_sell()` does not return anything.
> 
> Please also note that you're using a outdated command to run the bot, please use `freqtrade hyperopt` instead.

thank you very much, i bought the course that i am learning about freqtrade, if i may ask, what is the right command i should use and what should i do in other to update my file.

**Comment by xmatthias** [comment]
Please note that the udemy course has not been created by maintainers / authors of freqtrade, but by an independent trader / company not afiliated nor related to this reposotiry - so for support regarding support questions, please refer to the Udemy comments / questions page - that's where you can get support for that.


Best read through the [hyperopt documentation](https://www.freqtrade.io/en/latest/hyperopt/) - it should cover most questions.
