### ISSUE TITLE
I upgraded to the new version of freqtrade but the issue is that my formal strategy is giving me error

### ISSUE THREAD

**Issue by ebuka-odih** [freqtrade/freqtrade#3272]
I upgraded my freqtrade to the newest version and when i try to run my own strategy that i develop for my previous freqtrade it gives me this error

```
2020-05-08 22:25:05,669 - freqtrade.loggers - INFO - Verbosity set to 0
2020-05-08 22:25:05,669 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
2020-05-08 22:25:05,670 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2020-05-08 22:25:05,670 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:///tradesv3.dryrun.sqlite"
2020-05-08 22:25:05,670 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 3 ...
2020-05-08 22:25:05,670 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/emma/Desktop/Bot/ta-lib/freqtrade/user_data ...
2020-05-08 22:25:05,671 - freqtrade.configuration.configuration - INFO - Using data directory: /home/emma/Desktop/Bot/ta-lib/freqtrade/user_data/data/binance ...
2020-05-08 22:25:05,671 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2020-05-08 22:25:05,671 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2020-05-08 22:25:05,671 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2020-05-08 22:25:05,671 - freqtrade.freqtradebot - INFO - Starting freqtrade develop-18ec65e0
2020-05-08 22:25:05,673 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy BBRSI from '/home/emma/Desktop/Bot/ta-lib/freqtrade/user_data/strategies/bbrsi.py'...
2020-05-08 22:25:05,673 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ticker_interval' with value in config file: 1h.
2020-05-08 22:25:05,673 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2020-05-08 22:25:05,673 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 0.01.
2020-05-08 22:25:05,673 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'buy': 10, 'sell': 30}.
2020-05-08 22:25:05,673 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'use_sell_signal' with value in config file: True.
2020-05-08 22:25:05,674 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'sell_profit_only' with value in config file: False.
2020-05-08 22:25:05,674 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ignore_roi_if_buy_signal' with value in config file: False.
2020-05-08 22:25:05,674 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {}
2020-05-08 22:25:05,674 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ticker_interval: 1h
2020-05-08 22:25:05,674 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.99
2020-05-08 22:25:05,674 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2020-05-08 22:25:05,674 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2020-05-08 22:25:05,674 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2020-05-08 22:25:05,674 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
2020-05-08 22:25:05,674 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False}
2020-05-08 22:25:05,675 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
2020-05-08 22:25:05,675 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2020-05-08 22:25:05,675 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 0.01
2020-05-08 22:25:05,675 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 0
2020-05-08 22:25:05,675 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'buy': 10, 'sell': 30}
2020-05-08 22:25:05,675 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_sell_signal: True
2020-05-08 22:25:05,675 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_only: False
2020-05-08 22:25:05,675 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_buy_signal: False
2020-05-08 22:25:05,675 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2020-05-08 22:25:05,678 - freqtrade.configuration.config_validation - CRITICAL - Invalid configuration. See config.json.example. Reason: {} does not have enough properties

Failed validating 'minProperties' in schema['properties']['minimal_roi']:
    {'minProperties': 1,
     'patternProperties': {'^[0-9.]+$': {'type': 'number'}},
     'type': 'object'}

On instance['minimal_roi']:
    {}
2020-05-08 22:25:05,680 - freqtrade.commands.trade_commands - ERROR - {} does not have enough properties
2020-05-08 22:25:05,680 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/emma/Desktop/Bot/ta-lib/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker = Worker(args)
  File "/home/emma/Desktop/Bot/ta-lib/freqtrade/freqtrade/worker.py", line 34, in __init__
    self._init(False)
  File "/home/emma/Desktop/Bot/ta-lib/freqtrade/freqtrade/worker.py", line 53, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/home/emma/Desktop/Bot/ta-lib/freqtrade/freqtrade/freqtradebot.py", line 66, in __init__
    validate_config_consistency(config)
  File "/home/emma/Desktop/Bot/ta-lib/freqtrade/freqtrade/configuration/config_validation.py", line 80, in validate_config_consistency
    validate_config_schema(conf)
  File "/home/emma/Desktop/Bot/ta-lib/freqtrade/freqtrade/configuration/config_validation.py", line 59, in validate_config_schema
    best_match(Draft4Validator(conf_schema).iter_errors(conf)).message
jsonschema.exceptions.ValidationError: {} does not have enough properties
```

**Comment by hroff-1902** [comment]
It shows in the log:
```
Strategy using minimal_roi: {}
```

How does minimal_roi is defined in config/strategy?

**Comment by ebuka-odih** [comment]
> It shows in the log:
> 
> ```
> Strategy using minimal_roi: {}
> ```
> 
> How does minimal_roi is defined in config/strategy?

sorry for the late reply, i fixed the bug but the issue now is that when i try to run a backtest it says that i don't have data and i have downloaded pairlist data multiple times yet the same bug

**Comment by hroff-1902** [comment]
show how did you downloaded data and what's in the log the backtesting produces...

**Comment by ebuka-odih** [comment]
this is the command i used `freqtrade download-data --exchange binance`

this is the error am having this morning
![image](https://user-images.githubusercontent.com/46707159/81495526-ba8a2c80-92a8-11ea-9728-324935fab412.png)

**Comment by hroff-1902** [comment]
do you run the bot from anaconda?

**Comment by ebuka-odih** [comment]
it was a mistake on my end, i did not activate the env before running the command, here is my result now

![image](https://user-images.githubusercontent.com/46707159/81495689-fa054880-92a9-11ea-9de8-b73963f4a82f.png)

**Comment by hroff-1902** [comment]
okay, and what then backtesting shows? which timeframe do you use for it?

**Comment by ebuka-odih** [comment]
the command is not recognized

![image](https://user-images.githubusercontent.com/46707159/81496016-64b78380-92ac-11ea-927a-0b6dcc0739b4.png)

**Comment by ebuka-odih** [comment]
i am still getting used to this new command, i changed the command this was my result


![image](https://user-images.githubusercontent.com/46707159/81496147-528a1500-92ad-11ea-999d-041feffabcda.png)

**Comment by hroff-1902** [comment]
so anything is okay now?

**Comment by ebuka-odih** [comment]
yes, please one more thing, am trying to run my custom hyperopt but it seem like the command is not working

`freqtrade hyperopt --strategy BBRSI --customhyperopt BBRSIOPT`
this is my command above

**Comment by hroff-1902** [comment]
seems you have experience with a very old version.
many things have changed since then.
please read the actual docs: https://www.freqtrade.io/en/latest/
there is no `--customhyperopt` option for many months, it was renamed.
pls refer the actual docs, which is applicable to the new version you are using now.

**Comment by hroff-1902** [comment]
the original question was answered, closing the issue
