### ISSUE TITLE
Installing Docker on Unraid

### ISSUE THREAD

**Issue by xXKingAlex** [freqtrade/freqtrade#3318]
Does anyone have any experience installing the docker on unraid?

I tried to create its config files, but it didn't seem to work then deleted itself from unraid.

Any tips?
I used the image freqtradeorg/freqtrade:master

**Comment by hroff-1902** [comment]
I have not seen/heard of `unraid` before... 🙃

**Comment by xmatthias** [comment]
No sorry.

if you are able to provide a bit more details about this platform  ... 
is it ARM / x86?
what is th error you're experiencing?

**Comment by xmatthias** [comment]
Seems to be [unraid.net](https://unraid.net/) ...

Sorry - but we're unable to help you with this - best ask in a community with fellow unraid users who successfully installed Docker before.

We know nothing about this System - so unless you encounter freqtrade-specific errormessages we will not be able to provide support.

**Comment by xXKingAlex** [comment]
![Screenshot_7](https://user-images.githubusercontent.com/31272437/82135745-8fc04b00-9849-11ea-8fbd-f2192fcf9e6e.jpg)
![Screenshot_8](https://user-images.githubusercontent.com/31272437/82135746-918a0e80-9849-11ea-8c6f-251c8127f18c.jpg)
![Screenshot_9](https://user-images.githubusercontent.com/31272437/82135747-9222a500-9849-11ea-896e-20a1d7a3f2a5.jpg)


This is the issue im having. It cannot find the config files even though its there. Any tips?

**Comment by xmatthias** [comment]
Please copy and paste errormessages as text, that makes it refindable for others.

well you mentioned above that you're using docker to run it. are you using docker-compose, or a plain docker command?


For docker compose: not the full directory is mounted, but user_data - so you should move the config.json into this directory.

for plain docker: it'll depend on your startup line - but usually you should not have the complete freqtrade directory mounted into the container.

**Comment by xXKingAlex** [comment]
onfig file "config.json" not found! Please create a config file or check whether it exists.
Fatal exception!
Traceback (most recent call last):
File "/freqtrade/freqtrade/configuration/load_config.py", line 48, in load_config_file
with open(path) if path != '-' else sys.stdin as file:
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
worker = Worker(args)
File "/freqtrade/freqtrade/worker.py", line 34, in __init__
self._init(False)
File "/freqtrade/freqtrade/worker.py", line 50, in _init
self._config = Configuration(self._args, None).get_config()
File "/freqtrade/freqtrade/configuration/configuration.py", line 41, in get_config
self.config = self.load_config()
File "/freqtrade/freqtrade/configuration/configuration.py", line 94, in load_config
config: Dict[str, Any] = self.load_from_files(self.args.get("config", []))
File "/freqtrade/freqtrade/configuration/configuration.py", line 73, in load_from_files
config = deep_merge_dicts(load_config_file(path), config)
File "/freqtrade/freqtrade/configuration/load_config.py", line 51, in load_config_file
raise OperationalException(
freqtrade.exceptions.OperationalException: Config file "config.json" not found! Please create a config file or check whether it exists.
Config file "config.json" not found! Please create a config file or check whether it exists.
Fatal exception!
Traceback (most recent call last):
File "/freqtrade/freqtrade/configuration/load_config.py", line 48, in load_config_file
with open(path) if path != '-' else sys.stdin as file:
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
worker = Worker(args)
File "/freqtrade/freqtrade/worker.py", line 34, in __init__
self._init(False)
File "/freqtrade/freqtrade/worker.py", line 50, in _init
self._config = Configuration(self._args, None).get_config()
File "/freqtrade/freqtrade/configuration/configuration.py", line 41, in get_config
self.config = self.load_config()
File "/freqtrade/freqtrade/configuration/configuration.py", line 94, in load_config
config: Dict[str, Any] = self.load_from_files(self.args.get("config", []))
File "/freqtrade/freqtrade/configuration/configuration.py", line 73, in load_from_files
config = deep_merge_dicts(load_config_file(path), config)
File "/freqtrade/freqtrade/configuration/load_config.py", line 51, in load_config_file
raise OperationalException(
freqtrade.exceptions.OperationalException: Config file "config.json" not found! Please create a config file or check whether it exists.
Config file "config.json" not found! Please create a config file or check whether it exists.
Fatal exception!
Traceback (most recent call last):
File "/freqtrade/freqtrade/configuration/load_config.py", line 48, in load_config_file
with open(path) if path != '-' else sys.stdin as file:
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
worker = Worker(args)
File "/freqtrade/freqtrade/worker.py", line 34, in __init__
self._init(False)
File "/freqtrade/freqtrade/worker.py", line 50, in _init
self._config = Configuration(self._args, None).get_config()
File "/freqtrade/freqtrade/configuration/configuration.py", line 41, in get_config
self.config = self.load_config()
File "/freqtrade/freqtrade/configuration/configuration.py", line 94, in load_config
config: Dict[str, Any] = self.load_from_files(self.args.get("config", []))
File "/freqtrade/freqtrade/configuration/configuration.py", line 73, in load_from_files
config = deep_merge_dicts(load_config_file(path), config)
File "/freqtrade/freqtrade/configuration/load_config.py", line 51, in load_config_file
raise OperationalException(
freqtrade.exceptions.OperationalException: Config file "config.json" not found! Please create a config file or check whether it exists.

**Comment by xXKingAlex** [comment]
> Please copy and paste errormessages as text, that makes it refindable for others.
> 
> well you mentioned above that you're using docker to run it. are you using docker-compose, or a plain docker command?
> 
> For docker compose: not the full directory is mounted, but user_data - so you should move the config.json into this directory.
> 
> for plain docker: it'll depend on your startup line - but usually you should not have the complete freqtrade directory mounted into the container.

I have placed the config.json file into the user_data directory

**Comment by xmatthias** [comment]
what you'll need to make sure is simply that it's "Mounted" (either as `volumes` key in docker-compose, or as `docker ... -v ...` ) - otherwise it's not visible from within the docker container.
