### ISSUE TITLE
This class does not exist or contains Python code errors.

### ISSUE THREAD

**Issue by Maurits14** [freqtrade/freqtrade#3336]
* Operating system: Ubuntu 20.04
  * Python Version: 3.8.2
  
## Step 3: Describe the problem:
I ran the following command to test the bot: freqtrade trade -c config.json -s BBRSI

When I try to test whether my strategy is able to run, I encounter the following problems/errors:
```
- freqtrade.commands.trade_commands - ERROR - Impossible to load Strategy 'BBRSI'. This class does not exist or contains Python code errors.
- freqtrade.commands.trade_commands - ERROR - Fatal exception!
```

Ending with the lines: 
```
File "/home/maurits/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 177, in _load_strategy
    raise OperationalException(
freqtrade.exceptions.OperationalException: Impossible to load Strategy 'BBRSI'. This class does not exist or contains Python code errors.
```

The strategy file had the following code:
```
 # pragma pylint: disable=missing-docstring, invalid-name, pointless-string-statement

 # --- Do not remove these libs ---
import numpy as np  # noqa
import pandas as pd  # noqa
from pandas import DataFrame

from freqtrade.strategy.interface import IStrategy

 # --------------------------------
 # Add your lib to import here
import talib.abstract as ta
import freqtrade.vendor.qtpylib.indicators as qtpylib


 # This class is a sample. Feel free to customize it.
class BBRSI:
    """
    This is a sample strategy to inspire you.
    More information in https://github.com/freqtrade/freqtrade/blob/develop/docs/bot-optimization.md

    You can:
        :return: a Dataframe with all mandatory indicators for the strategies
    - Rename the class name (Do not forget to update class_name)
    - Add any methods you want to build your strategy
    - Add any lib you need to build your strategy

    You must keep:
    - the lib in the section "Do not remove these libs"
    - the prototype for the methods: minimal_roi, stoploss, populate_indicators, populate_buy_trend,
    populate_sell_trend, hyperopt_space, buy_strategy_generator
    """
    # Strategy interface version - allow new iterations of the strategy interface.
    # Check the documentation or the Sample strategy to get the latest version.
    INTERFACE_VERSION = 2

    # Minimal ROI designed for the strategy.
    # This attribute will be overridden if the config file contains "minimal_roi".
    minimal_roi = {
    }

    # Optimal stoploss designed for the strategy.
    # This attribute will be overridden if the config file contains "stoploss".
    stoploss = -0.99

    # Trailing stoploss
    trailing_stop = False
    # trailing_only_offset_is_reached = False
    # trailing_stop_positive = 0.01
    # trailing_stop_positive_offset = 0.0  # Disabled / not configured

    # Optimal ticker interval for the strategy.
    ticker_interval = '1h'

    # Run "populate_indicators()" only for new candle.
    process_only_new_candles = False

    # These values can be overridden in the "ask_strategy" section in the config.
    use_sell_signal = True
    sell_profit_only = False
    ignore_roi_if_buy_signal = False

    # Number of candles the strategy requires before producing valid signals
    startup_candle_count: int = 20

    # Optional order type mapping.
    order_types = {
        'buy': 'limit',
        'sell': 'limit',
        'stoploss': 'market',
        'stoploss_on_exchange': False
    }

    # Optional order time in force.
    order_time_in_force = {
        'buy': 'gtc',
        'sell': 'gtc'
    }

    plot_config = {
        'main_plot': {
            'tema': {},
            'sar': {'color': 'white'},
        },
        'subplots': {
            "MACD": {
                'macd': {'color': 'blue'},
                'macdsignal': {'color': 'orange'},
            },
            "RSI": {
                'rsi': {'color': 'red'},
            }
        }
    }

    def informative_pairs(self):
        """
        Define additional, informative pair/interval combinations to be cached from the exchange.
        These pair/interval combinations are non-tradeable, unless they are part
        of the whitelist as well.
        For more information, please consult the documentation
        :return: List of tuples in the format (pair, interval)
            Sample: return [("ETH/USDT", "5m"),
                            ("BTC/USDT", "15m"),
                            ]
        """
        return []

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Adds several different TA indicators to the given DataFrame

        Performance Note: For the best performance be frugal on the number of indicators
        you are using. Let uncomment only the indicator you are using in your strategies
        or your hyperopt configuration, otherwise you will waste your memory and CPU usage.
        :param dataframe: Dataframe with data from the exchange
        :param metadata: Additional information, like the currently traded pair
        :return: a Dataframe with all mandatory indicators for the strategies
        """

        # Momentum Indicators
        # ------------------------------------


        # RSI
        dataframe['rsi'] = ta.RSI(dataframe)

        # # Inverse Fisher transform on RSI: values [-1.0, 1.0] (https://goo.gl/2JGGoy)
        # rsi = 0.1 * (dataframe['rsi'] - 50)
        # dataframe['fisher_rsi'] = (np.exp(2 * rsi) - 1) / (np.exp(2 * rsi) + 1)

        # # Inverse Fisher transform on RSI normalized: values [0.0, 100.0] (https://goo.gl/2JGGoy)
        # dataframe['fisher_rsi_norma'] = 50 * (dataframe['fisher_rsi'] + 1)

        # # Stochastic Slow
        # stoch = ta.STOCH(dataframe)
        # dataframe['slowd'] = stoch['slowd']
        # dataframe['slowk'] = stoch['slowk']


        # Bollinger Bands
        bollinger = qtpylib.bollinger_bands(qtpylib.typical_price(dataframe), window=20, stds=2)
        dataframe['bb_lowerband'] = bollinger['lower']
        dataframe['bb_middleband'] = bollinger['mid']
        dataframe['bb_upperband'] = bollinger['upper']
        dataframe["bb_percent"] = (
            (dataframe["close"] - dataframe["bb_lowerband"]) /
            (dataframe["bb_upperband"] - dataframe["bb_lowerband"])
        )
        dataframe["bb_width"] = (
            (dataframe["bb_upperband"] - dataframe["bb_lowerband"]) / dataframe["bb_middleband"]
        )

        # Bollinger Bands - Weighted (EMA based instead of SMA)
        # weighted_bollinger = qtpylib.weighted_bollinger_bands(
        #     qtpylib.typical_price(dataframe), window=20, stds=2
        # )
        # dataframe["wbb_upperband"] = weighted_bollinger["upper"]
        # dataframe["wbb_lowerband"] = weighted_bollinger["lower"]
        # dataframe["wbb_middleband"] = weighted_bollinger["mid"]
        # dataframe["wbb_percent"] = (
        #     (dataframe["close"] - dataframe["wbb_lowerband"]) /
        #     (dataframe["wbb_upperband"] - dataframe["wbb_lowerband"])
        # )
        # dataframe["wbb_width"] = (
        #     (dataframe["wbb_upperband"] - dataframe["wbb_lowerband"]) /
        #     dataframe["wbb_middleband"]
        # )


        # Retrieve best bid and best ask from the orderbook
        # ------------------------------------
        """
        # first check if dataprovider is available
        if self.dp:
            if self.dp.runmode in ('live', 'dry_run'):
                ob = self.dp.orderbook(metadata['pair'], 1)
                dataframe['best_bid'] = ob['bids'][0][0]
                dataframe['best_ask'] = ob['asks'][0][0]
        """

        return dataframe

    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators, populates the buy signal for the given dataframe
        :param dataframe: DataFrame populated with indicators
        :param metadata: Additional information, like the currently traded pair
        :return: DataFrame with buy column
        """
        dataframe.loc[
            (
                (qdataframe['rsi'] > 30) &
                (datafram['close'] < dataframe['bb_lowerband'])  # Signal: RSI crosses above 30
                  # Make sure Volume is not 0
            ),
            'buy'] = 1

        return dataframe

    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators, populates the sell signal for the given dataframe
        :param dataframe: DataFrame populated with indicators
        :param metadata: Additional information, like the currently traded pair
        :return: DataFrame with buy column
        """
        dataframe.loc[
            (
                (dataframe['close'] > dataframe['bb_middleband'])

                ),
            'sell'] = 1
        return dataframe
```

I am a student, new with coding, trying to learn and improve. Would someone be so kind to help me with the problems I encounter? Thank you so much in advance!

**Comment by xmatthias** [comment]
well, we'll need the full output - it'll contain the problem (you've either placed the file in the wrong directory - or it contains syntax errors.

The answer to that question is in the full log output ...

**Comment by hroff-1902** [comment]
```
$ flake8 user_data/strategies/BBRSI.py 
user_data/strategies/BBRSI.py:8:1: F401 'freqtrade.strategy.interface.IStrategy' imported but unused
user_data/strategies/BBRSI.py:125:9: E303 too many blank lines (2)
user_data/strategies/BBRSI.py:141:9: E303 too many blank lines (2)
user_data/strategies/BBRSI.py:171:9: E303 too many blank lines (2)
user_data/strategies/BBRSI.py:193:18: F821 undefined name 'qdataframe'
user_data/strategies/BBRSI.py:194:18: F821 undefined name 'datafram'
user_data/strategies/BBRSI.py:195:19: E131 continuation line unaligned for hanging indent
```

**Comment by Maurits14** [comment]
Dear xmatthias,

The full output is the following: 

2020-05-19 08:41:36,542 - freqtrade.loggers - INFO - Verbosity set to 0
2020-05-19 08:41:36,542 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
2020-05-19 08:41:36,543 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2020-05-19 08:41:36,543 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:///tradesv3.dryrun.sqlite"
2020-05-19 08:41:36,543 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 15 ...
2020-05-19 08:41:36,544 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/maurits/freqtrade/user_data ...
2020-05-19 08:41:36,559 - freqtrade.configuration.configuration - INFO - Using data directory: /home/maurits/freqtrade/user_data/data/binance ...
2020-05-19 08:41:36,560 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2020-05-19 08:41:36,560 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2020-05-19 08:41:36,560 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2020-05-19 08:41:36,561 - freqtrade.freqtradebot - INFO - Starting freqtrade develop-9d6a41aa
2020-05-19 08:41:36,563 - freqtrade.commands.trade_commands - ERROR - Impossible to load Strategy 'BBRSI'. This class does not exist or contains Python code errors.
2020-05-19 08:41:36,563 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/maurits/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker = Worker(args)
  File "/home/maurits/freqtrade/freqtrade/worker.py", line 34, in __init__
    self._init(False)
  File "/home/maurits/freqtrade/freqtrade/worker.py", line 53, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/home/maurits/freqtrade/freqtrade/freqtradebot.py", line 63, in __init__
    self.strategy: IStrategy = StrategyResolver.load_strategy(self.config)
  File "/home/maurits/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 45, in load_strategy
    strategy: IStrategy = StrategyResolver._load_strategy(
  File "/home/maurits/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 177, in _load_strategy
    raise OperationalException(
freqtrade.exceptions.OperationalException: Impossible to load Strategy 'BBRSI'. This class does not exist or contains Python code errors.

Dear hroff-1902,
I will try and fix "undefined name" and "continuation line unaligned".

Thank you both for your help!

**Comment by xmatthias** [comment]
what location (directory) did  you put this file into?

The log indicates that it's not even trying to load this file - so the errors within the file are not relevant, as freqtrade is not finding this file - which indicates a problem with the location.

**Comment by Maurits14** [comment]
/freqtrade/freqtrade/strategy/bbrsi.py; So I put the file in the strategy folder, I was told that this was necessary for the bot to run properly.

**Comment by xmatthias** [comment]
this is the wrong location (as i suspected, to be honest).

The correct location is `user_data/strategies/` (as documented [here](https://www.freqtrade.io/en/latest/strategy-customization/#install-a-custom-strategy-file).

Please move the file to that directory and retry.

**Comment by Maurits14** [comment]
Thank you very much; it worked although I got another error now, but I will try to solve this myself.

**Comment by Maurits14** [comment]
After having fixed the new problem, the old problem reoccurs.
Running the command: freqtrade trade -c config.json --strategy BBRSI

I got the output:

2020-05-19 09:45:31,402 - freqtrade.loggers - INFO - Verbosity set to 0
2020-05-19 09:45:31,403 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
2020-05-19 09:45:31,403 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2020-05-19 09:45:31,403 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:///tradesv3.dryrun.sqlite"
2020-05-19 09:45:31,403 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 15 ...
2020-05-19 09:45:31,404 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/maurits/freqtrade/user_data ...
2020-05-19 09:45:31,404 - freqtrade.configuration.configuration - INFO - Using data directory: /home/maurits/freqtrade/user_data/data/binance ...
2020-05-19 09:45:31,405 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2020-05-19 09:45:31,405 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2020-05-19 09:45:31,405 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2020-05-19 09:45:31,405 - freqtrade.freqtradebot - INFO - Starting freqtrade develop-9d6a41aa
2020-05-19 09:45:31,406 - freqtrade.commands.trade_commands - ERROR - Impossible to load Strategy 'BBRSI'. This class does not exist or contains Python code errors.
2020-05-19 09:45:31,406 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/maurits/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker = Worker(args)
  File "/home/maurits/freqtrade/freqtrade/worker.py", line 34, in __init__
    self._init(False)
  File "/home/maurits/freqtrade/freqtrade/worker.py", line 53, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/home/maurits/freqtrade/freqtrade/freqtradebot.py", line 63, in __init__
    self.strategy: IStrategy = StrategyResolver.load_strategy(self.config)
  File "/home/maurits/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 45, in load_strategy
    strategy: IStrategy = StrategyResolver._load_strategy(
  File "/home/maurits/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 177, in _load_strategy
    raise OperationalException(
freqtrade.exceptions.OperationalException: Impossible to load Strategy 'BBRSI'. This class does not exist or contains Python code errors.

**Comment by hroff-1902** [comment]
> /freqtrade/freqtrade/strategy/bbrsi.py; So I put the file in the strategy folder, I was told that this was necessary for the bot to run properly.

Do not listen wrong and incorrect advices they made in the Udemy course...

**Comment by hroff-1902** [comment]
> After having fixed the new problem, the old problem reoccurs.

The strategy still contains python errors.

What is the version of freqtrade you are using? (`freqtrade -V`)

**Comment by Maurits14** [comment]
Freqtrade develop-9d6a41aa

**Comment by hroff-1902** [comment]
fresh enough (I thought you might be using the outstanding old version from the Udemy course)

in short: the strategy still contains python errors, try to find and fix it

**Comment by Maurits14** [comment]
Oké thanks, I think I just fixed the errors.

**Comment by hroff-1902** [comment]
make sure you have only one strategy named BBRSI, use `freqtrade list-strategies`, it should not show you duplicates

with duplicates, you may be fixing strategy in one file, and the bot will find and load the buggy one with the same name loaded from another file

**Comment by Maurits14** [comment]
Oké, thanks for the tip.

**Comment by robinson84** [comment]
hola compañeros, estaba dando inicio a mi primer proyecto de un bot , pero a darle  inicio con telegram , me aparece estos errores y no he podido solucionarlos , y la VERDAD   soy un estudiante  muy nuevo en esto, pero tengo todos las ganas de aprender  e ir mejorando,  alguien que me pueda ayudar  o guiar. 

2022-01-24 03:30:54,025 - freqtrade.worker - INFO - Starting worker develop
2022-01-24 03:30:54,025 - freqtrade.configuration.configuration - INFO - Using config: user_data/config.json ...
2022-01-24 03:30:54,041 - freqtrade.loggers - INFO - Verbosity set to 0
2022-01-24 03:30:54,042 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
2022-01-24 03:30:54,042 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2022-01-24 03:30:54,042 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:///tradesv3.dryrun.sqlite"
2022-01-24 03:30:54,043 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 5 ...
2022-01-24 03:30:54,144 - freqtrade.configuration.configuration - INFO - Using user-data directory: /workspaces/ft_userdata/user_data ...
2022-01-24 03:30:54,147 - freqtrade.configuration.configuration - INFO - Using data directory: /workspaces/ft_userdata/user_data/data/binance ...
2022-01-24 03:30:54,148 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2022-01-24 03:30:54,231 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2022-01-24 03:30:54,231 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2022-01-24 03:30:54,232 - freqtrade.configuration.deprecated_settings - WARNING - DEPRECATED: The `ask_strategy.use_sell_signal` setting is deprecated and will be removed in the next versions of Freqtrade. Please use the `use_sell_signal` setting in your configuration instead.
2022-01-24 03:30:54,232 - freqtrade.configuration.deprecated_settings - WARNING - DEPRECATED: The `ask_strategy.ignore_roi_if_buy_signal` setting is deprecated and will be removed in the next versions of Freqtrade. Please use the `ignore_roi_if_buy_signal` setting in your configuration instead.
2022-01-24 03:30:54,232 - freqtrade.freqtradebot - INFO - Starting freqtrade develop
2022-01-24 03:30:54,382 - freqtrade.commands.trade_commands - ERROR - Impossible to load Strategy 'samplestrategy.py'. This class does not exist or contains Python code errors.
2022-01-24 03:30:54,382 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/freqtrade/freqtrade/worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/freqtrade/freqtrade/freqtradebot.py", line 60, in __init__
    self.strategy: IStrategy = StrategyResolver.load_strategy(self.config)
  File "/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 44, in load_strategy
    strategy: IStrategy = StrategyResolver._load_strategy(
  File "/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 217, in _load_strategy
    raise OperationalException(
freqtrade.exceptions.OperationalException: Impossible to load Strategy 'samplestrategy.py'. This class does not exist or contains Python code errors.

**Comment by xmatthias** [comment]
@robinson84 please use english for issues. 

I'd also urge you to not revive old, closed issues, as they cause notifications to everyone involved in that issue historically.


the error suggests that you're using `samplestrategy.py` as strategy argument. The strategy should however be the classname - so the correct way is probably `SampleStrategy`.
