### ISSUE TITLE
KeyError rsi

### ISSUE THREAD

**Issue by Maurits14** [freqtrade/freqtrade#3357]
#2499 Step 2: Describe your environment

  * Operating system: Ubuntu 20.04 LTS
  * Python Version: 3.8.2
  

## Step 3: Describe the problem:
I ran the following command: freqtrade hyperopt --config config.json --hyperopt BBRSI_hyperopt -e 5000 --spaces all --strategy BBRSI

This gave me the following error: KeyError 'rsi'. 

I was wondering whether someone could help me out with this error, since I have never seen this error before. Thank you very much in advance!

The full output:
2020-05-22 11:12:26,583 - freqtrade.loggers - INFO - Verbosity set to 0
2020-05-22 11:12:26,584 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 15 ...
2020-05-22 11:12:26,584 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/maurits/freqtrade/user_data ...
2020-05-22 11:12:26,598 - freqtrade.configuration.configuration - INFO - Using data directory: /home/maurits/freqtrade/user_data/data/binance ...
2020-05-22 11:12:26,598 - freqtrade.configuration.configuration - INFO - Using Hyperopt class name: BBRSI_hyperopt
2020-05-22 11:12:26,599 - freqtrade.configuration.configuration - INFO - Parameter --epochs detected ... Will run Hyperopt with for 100 epochs ...
2020-05-22 11:12:26,599 - freqtrade.configuration.configuration - INFO - Parameter -s/--spaces detected: ['all']
2020-05-22 11:12:26,600 - freqtrade.configuration.configuration - INFO - Parameter -j/--job-workers detected: -1
2020-05-22 11:12:26,600 - freqtrade.configuration.configuration - INFO - Parameter --min-trades detected: 1
2020-05-22 11:12:26,601 - freqtrade.configuration.configuration - INFO - Using Hyperopt loss class name: DefaultHyperOptLoss
2020-05-22 11:12:26,601 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2020-05-22 11:12:26,601 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2020-05-22 11:12:26,601 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2020-05-22 11:12:26,602 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2020-05-22 11:12:26,605 - freqtrade.commands.optimize_commands - INFO - Starting freqtrade in Hyperopt mode
2020-05-22 11:12:26,606 - filelock - INFO - Lock 140442607090512 acquired on /home/maurits/freqtrade/user_data/hyperopt.lock
2020-05-22 11:12:26,606 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2020-05-22 11:12:26,607 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2020-05-22 11:12:26,617 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 200}
2020-05-22 11:12:26,629 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2020-05-22 11:12:27,733 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2020-05-22 11:12:27,755 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from '/home/maurits/freqtrade/freqtrade/pairlist/StaticPairList.py'...
2020-05-22 11:12:27,756 - freqtrade.pairlist.IPairList - INFO - Ignoring PAX/BTC from whitelist. Market is not active.
2020-05-22 11:12:27,802 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy BBRSI from '/home/maurits/freqtrade/user_data/strategies/bbrsi.py'...
2020-05-22 11:12:27,802 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ticker_interval' with value in config file: 1h.
2020-05-22 11:12:27,802 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: BTC.
2020-05-22 11:12:27,803 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 0.01.
2020-05-22 11:12:27,803 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'buy': 10, 'sell': 30}.
2020-05-22 11:12:27,803 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'use_sell_signal' with value in config file: True.
2020-05-22 11:12:27,803 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'sell_profit_only' with value in config file: False.
2020-05-22 11:12:27,803 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ignore_roi_if_buy_signal' with value in config file: False.
2020-05-22 11:12:27,803 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 10.0}
2020-05-22 11:12:27,803 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ticker_interval: 1h
2020-05-22 11:12:27,803 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.99
2020-05-22 11:12:27,803 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2020-05-22 11:12:27,804 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2020-05-22 11:12:27,804 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2020-05-22 11:12:27,804 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
2020-05-22 11:12:27,804 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'market', 'stoploss_on_exchange': False}
2020-05-22 11:12:27,804 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
2020-05-22 11:12:27,804 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: BTC
2020-05-22 11:12:27,804 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 0.01
2020-05-22 11:12:27,805 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 20
2020-05-22 11:12:27,805 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'buy': 10, 'sell': 30}
2020-05-22 11:12:27,805 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_sell_signal: True
2020-05-22 11:12:27,805 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_only: False
2020-05-22 11:12:27,805 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_buy_signal: False
2020-05-22 11:12:27,805 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2020-05-22 11:12:27,814 - freqtrade.resolvers.iresolver - INFO - Using resolved hyperopt BBRSI_hyperopt from '/home/maurits/freqtrade/user_data/hyperopts/BBRSI_hyperopts.py'...
2020-05-22 11:12:27,929 - freqtrade.resolvers.iresolver - INFO - Using resolved hyperoptloss DefaultHyperOptLoss from '/home/maurits/freqtrade/freqtrade/optimize/default_hyperopt_loss.py'...
2020-05-22 11:12:27,931 - freqtrade.optimize.hyperopt - INFO - Removing `/home/maurits/freqtrade/user_data/hyperopt_results/hyperopt_tickerdata.pkl`.
2020-05-22 11:12:27,931 - freqtrade.optimize.hyperopt - INFO - Using optimizer random state: 21397
2020-05-22 11:12:27,931 - freqtrade.data.history.history_utils - INFO - Using indicator startup period: 20 ...
2020-05-22 11:12:28,146 - freqtrade.data.converter - INFO - Missing data fillup for ALGO/BTC: before: 716 - after: 718
2020-05-22 11:12:28,227 - freqtrade.data.converter - INFO - Missing data fillup for ATOM/BTC: before: 716 - after: 718
2020-05-22 11:12:28,300 - freqtrade.data.converter - INFO - Missing data fillup for BAT/BTC: before: 716 - after: 718
2020-05-22 11:12:28,364 - freqtrade.data.converter - INFO - Missing data fillup for BCH/BTC: before: 716 - after: 718
2020-05-22 11:12:28,418 - freqtrade.data.converter - INFO - Missing data fillup for BNB/BTC: before: 716 - after: 718
2020-05-22 11:12:28,483 - freqtrade.data.converter - INFO - Missing data fillup for BRD/BTC: before: 716 - after: 718
2020-05-22 11:12:28,572 - freqtrade.data.converter - INFO - Missing data fillup for EOS/BTC: before: 716 - after: 718
2020-05-22 11:12:28,620 - freqtrade.data.converter - INFO - Missing data fillup for ETC/BTC: before: 716 - after: 718
2020-05-22 11:12:28,688 - freqtrade.data.converter - INFO - Missing data fillup for ETH/BTC: before: 716 - after: 718
2020-05-22 11:12:28,742 - freqtrade.data.converter - INFO - Missing data fillup for IOTA/BTC: before: 716 - after: 718
2020-05-22 11:12:28,811 - freqtrade.data.converter - INFO - Missing data fillup for LINK/BTC: before: 716 - after: 718
2020-05-22 11:12:28,880 - freqtrade.data.converter - INFO - Missing data fillup for LTC/BTC: before: 716 - after: 718
2020-05-22 11:12:28,935 - freqtrade.data.converter - INFO - Missing data fillup for NEO/BTC: before: 716 - after: 718
2020-05-22 11:12:29,011 - freqtrade.data.converter - INFO - Missing data fillup for NXS/BTC: before: 716 - after: 718
2020-05-22 11:12:29,080 - freqtrade.data.converter - INFO - Missing data fillup for XMR/BTC: before: 716 - after: 718
2020-05-22 11:12:29,148 - freqtrade.data.converter - INFO - Missing data fillup for XRP/BTC: before: 716 - after: 718
2020-05-22 11:12:29,220 - freqtrade.data.converter - INFO - Missing data fillup for XTZ/BTC: before: 716 - after: 718
2020-05-22 11:12:29,276 - freqtrade.data.converter - INFO - Missing data fillup for TRX/BTC: before: 716 - after: 718
2020-05-22 11:12:29,337 - freqtrade.data.converter - INFO - Missing data fillup for VET/BTC: before: 716 - after: 718
2020-05-22 11:12:29,387 - freqtrade.data.converter - INFO - Missing data fillup for ADA/BTC: before: 716 - after: 718
2020-05-22 11:12:29,464 - freqtrade.data.converter - INFO - Missing data fillup for DASH/BTC: before: 716 - after: 718
2020-05-22 11:12:29,516 - freqtrade.data.converter - INFO - Missing data fillup for ZEC/BTC: before: 716 - after: 718
2020-05-22 11:12:29,579 - freqtrade.data.converter - INFO - Missing data fillup for OGN/BTC: before: 716 - after: 718
2020-05-22 11:12:29,628 - freqtrade.data.converter - INFO - Missing data fillup for ZRX/BTC: before: 716 - after: 718
2020-05-22 11:12:29,702 - freqtrade.data.converter - INFO - Missing data fillup for STEEM/BTC: before: 716 - after: 718
2020-05-22 11:12:29,756 - freqtrade.data.converter - INFO - Missing data fillup for OMG/BTC: before: 716 - after: 718
2020-05-22 11:12:29,815 - freqtrade.data.converter - INFO - Missing data fillup for ONT/BTC: before: 716 - after: 718
2020-05-22 11:12:29,866 - freqtrade.data.converter - INFO - Missing data fillup for ZIL/BTC: before: 716 - after: 718
2020-05-22 11:12:29,894 - freqtrade.optimize.backtesting - INFO - Loading data from 2020-04-19T14:00:00+00:00 up to 2020-05-19T11:00:00+00:00 (29 days)..
2020-05-22 11:12:29,894 - freqtrade.configuration.timerange - WARNING - Moving start-date by 20 candles to account for startup time.
2020-05-22 11:12:30,835 - freqtrade.optimize.hyperopt - INFO - Hyperopting with data from 2020-04-19T14:00:00+00:00 up to 2020-05-19T11:00:00+00:00 (29 days)..
2020-05-22 11:12:30,919 - freqtrade.optimize.hyperopt - INFO - Found 2 CPU cores. Let's make them scream!
2020-05-22 11:12:30,919 - freqtrade.optimize.hyperopt - INFO - Number of parallel jobs set as: -1
2020-05-22 11:12:30,926 - freqtrade.optimize.hyperopt_interface - INFO - Min roi table: {0: 0.06883, 120: 0.04589, 240: 0.02294, 360: 0}
2020-05-22 11:12:30,926 - freqtrade.optimize.hyperopt_interface - INFO - Max roi table: {0: 0.71124, 480: 0.25238, 1200: 0.09177, 2640: 0}
2020-05-22 11:12:31,045 - freqtrade.optimize.hyperopt - INFO - Effective number of parallel workers used: 2

2020-05-22 11:12:35,525 - freqtrade - ERROR - Fatal exception!
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/maurits/freqtrade/.env/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2646, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'rsi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/maurits/freqtrade/.env/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 418, in _process_worker
    r = call_item()
  File "/home/maurits/freqtrade/.env/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 272, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/maurits/freqtrade/.env/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 608, in __call__
    return self.func(*args, **kwargs)
  File "/home/maurits/freqtrade/.env/lib/python3.8/site-packages/joblib/parallel.py", line 255, in __call__
    return [func(*args, **kwargs)
  File "/home/maurits/freqtrade/.env/lib/python3.8/site-packages/joblib/parallel.py", line 255, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/maurits/freqtrade/.env/lib/python3.8/site-packages/joblib/externals/loky/cloudpickle_wrapper.py", line 38, in __call__
    return self._obj(*args, **kwargs)
  File "/home/maurits/freqtrade/freqtrade/optimize/hyperopt.py", line 527, in generate_optimizer
    backtesting_results = self.backtesting.backtest(
  File "/home/maurits/freqtrade/freqtrade/optimize/backtesting.py", line 304, in backtest
    data: Dict = self._get_ohlcv_as_lists(processed)
  File "/home/maurits/freqtrade/freqtrade/optimize/backtesting.py", line 158, in _get_ohlcv_as_lists
    self.strategy.advise_buy(pair_data, {'pair': pair}), {'pair': pair})[headers].copy()
  File "/home/maurits/freqtrade/user_data/hyperopts/BBRSI_hyperopts.py", line 91, in populate_buy_trend
    conditions.append(dataframe['rsi'] > params['rsi-value'])
  File "/home/maurits/freqtrade/.env/lib/python3.8/site-packages/pandas/core/frame.py", line 2800, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/maurits/freqtrade/.env/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'rsi'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/maurits/freqtrade/freqtrade/main.py", line 36, in main
    return_code = args['func'](args)
  File "/home/maurits/freqtrade/freqtrade/commands/optimize_commands.py", line 81, in start_hyperopt
    hyperopt.start()
  File "/home/maurits/freqtrade/freqtrade/optimize/hyperopt.py", line 688, in start
    f_val = self.run_optimizer_parallel(parallel, asked, i)
  File "/home/maurits/freqtrade/freqtrade/optimize/hyperopt.py", line 596, in run_optimizer_parallel
    return parallel(delayed(
  File "/home/maurits/freqtrade/.env/lib/python3.8/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/home/maurits/freqtrade/.env/lib/python3.8/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/maurits/freqtrade/.env/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
KeyError: 'rsi'

**Comment by xmatthias** [comment]
well if you're using rsi in your `indicator_space()` - you'll lso need to have this assigned to the dataframe first (in `populate_indicators()` ).

The error simply means that it's accessing a column not available in the dataframe.

Hope this makes sense

**Comment by Maurits14** [comment]
Thank you so much for your response.

I thought I did that by coding this under populate_indicators():
dataframe["buy-rsi"] = ta.RSI(dataframe)
        dataframe["sell-rsi"] = ta.RSI(dataframe)
Which step/part did I miss?

**Comment by Maurits14** [comment]
Or do I have to write dataframe["rsi"] = ta.RSI(dataframe)

**Comment by xmatthias** [comment]
well - you use `buy-rsi` and `sell-rsi` - but your indicator-space must then use these values too.

One side note:
Unless you're using different parameters (lengths) for RSI, it is rather pointless to assign the same value to 2 columns...

**Comment by Maurits14** [comment]
Oke, thanks; it works! (I do use different parameters for RSI :-))

**Comment by hroff-1902** [comment]
I gonna kill those Udemy guys... 😎
