### ISSUE TITLE
TA Lib - Stochastic Indicator with FT sample strategies

### ISSUE THREAD

**Issue by Prossi79** [freqtrade/freqtrade#3365]
## Step 1: Have you search for this issue before posting it?

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/freqtrade/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

Operating system: Ubuntu 18.04
Python Version: 3.7.4
CCXT version: ccxt==1.27.91
Branch: Develop
Last Commit ID: b50d072
  
## Step 3: Describe the problem:

TA lib indicator ta.STOCHF with FT sample strategies (e.g. Scalp, CofiBitStrategy ReinforcedSmoothScalp ...) not working anymore after update

### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs:

  ```
2020-05-23 16:57:46,505 - freqtrade.optimize.backtesting - INFO - Running backtesting for Strategy ReinforcedQuickie
2020-05-23 16:57:48,393 - freqtrade.optimize.backtesting - INFO - Backtesting with data from 2020-01-01T00:00:00+00:00 up to 2020-05-15T00:00:00+00:00 (135 days)..
2020-05-23 16:57:49,170 - freqtrade.optimize.backtesting - INFO - Running backtesting for Strategy Scalp
2020-05-23 16:57:49,172 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/andreas/freqtrade/freqtrade/main.py", line 36, in main
    return_code = args['func'](args)
  File "/home/andreas/freqtrade/freqtrade/commands/optimize_commands.py", line 49, in start_backtesting
    backtesting.start()
  File "/home/andreas/freqtrade/freqtrade/optimize/backtesting.py", line 390, in start
    preprocessed = self.strategy.ohlcvdata_to_dataframe(data)
  File "/home/andreas/freqtrade/freqtrade/strategy/interface.py", line 502, in ohlcvdata_to_dataframe
    for pair, pair_data in data.items()}
  File "/home/andreas/freqtrade/freqtrade/strategy/interface.py", line 502, in <dictcomp>
    for pair, pair_data in data.items()}
  File "/home/andreas/freqtrade/freqtrade/strategy/interface.py", line 518, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/home/andreas/freqtrade/user_data/strategies/Scalp.py", line 46, in populate_indicators
    stoch_fast = ta.STOCHF(dataframe, 5.0, 3.0, 0.0, 3.0, 0.0)
  File "talib/_abstract.pxi", line 398, in talib._ta_lib.Function.__call__
  File "talib/_abstract.pxi", line 277, in talib._ta_lib.Function.set_function_args
  File "talib/_abstract.pxi", line 462, in talib._ta_lib.Function.__check_opt_input_value
TypeError: Invalid parameter value for fastk_period (expected int, got float)

  ```

**Comment by hroff-1902** [comment]
moving it to freqtrade-strategies
