### ISSUE TITLE
Error: has non-unique elements

### ISSUE THREAD

**Issue by Maurits14** [freqtrade/freqtrade#3368]
## Step 2: Describe your environment

  * Operating system: Ubuntu 20.04 LTS
  * Python Version: 3.8.2
  
## Step 3: Describe the problem:

I just added a few different coins to my config file, the same way I did it the previous time. However I got the following error: 
raise ValidationError(
jsonschema.exceptions.ValidationError: ['ADA/BTC', 'ALGO/BTC', 'ATOM/BTC', 'BAT/BTC', 'BCH/BTC', 'BNB/BTC', 'DASH/BTC', 'EOS/BTC', 'EOS/BNB', 'ETC/BTC', 'ETH/BNB', 'ETH/BTC', 'FTT/BTC', 'IOTA/BTC', 'LINK/BTC', 'LTC/BTC', 'NEO/BTC', 'OMG/BTC', 'NXS/BTC', 'ONT/BTC', 'PAX/BTC', 'QTUM/BTC', 'STEEM/BTC', 'TRX/BTC', 'XLM/BTC', 'XMR/BTC', 'XRP/BTC', 'XTZ/BTC', 'TRX/BTC', 'VET/BTC', 'USDT/BTC', 'ZEC/BTC', 'ZRX/BTC'] has non-unique elements

Would you be so kind to help me with this problem? Thank you very much in advance!

The full output:
2020-05-23 20:50:23,156 - freqtrade.loggers - INFO - Verbosity set to 0
2020-05-23 20:50:23,157 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 15 ...
2020-05-23 20:50:23,157 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/maurits/freqtrade/user_data ...
2020-05-23 20:50:23,158 - freqtrade.configuration.configuration - INFO - Using data directory: /home/maurits/freqtrade/user_data/data/binance ...
2020-05-23 20:50:23,158 - freqtrade.configuration.configuration - INFO - Using Hyperopt class name: BBRSI_hyperopt
2020-05-23 20:50:23,158 - freqtrade.configuration.configuration - INFO - Parameter --epochs detected ... Will run Hyperopt with for 100 epochs ...
2020-05-23 20:50:23,158 - freqtrade.configuration.configuration - INFO - Parameter -s/--spaces detected: ['all']
2020-05-23 20:50:23,158 - freqtrade.configuration.configuration - INFO - Parameter -j/--job-workers detected: -1
2020-05-23 20:50:23,158 - freqtrade.configuration.configuration - INFO - Parameter --min-trades detected: 1
2020-05-23 20:50:23,158 - freqtrade.configuration.configuration - INFO - Using Hyperopt loss class name: SharpeHyperOptLossDaily
2020-05-23 20:50:23,159 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2020-05-23 20:50:23,159 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2020-05-23 20:50:23,159 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2020-05-23 20:50:23,159 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2020-05-23 20:50:23,162 - freqtrade.configuration.config_validation - CRITICAL - Invalid configuration. See config.json.example. Reason: ['ADA/BTC', 'ALGO/BTC', 'ATOM/BTC', 'BAT/BTC', 'BCH/BTC', 'BNB/BTC', 'DASH/BTC', 'EOS/BTC', 'EOS/BNB', 'ETC/BTC', 'ETH/BNB', 'ETH/BTC', 'FTT/BTC', 'IOTA/BTC', 'LINK/BTC', 'LTC/BTC', 'NEO/BTC', 'OMG/BTC', 'NXS/BTC', 'ONT/BTC', 'PAX/BTC', 'QTUM/BTC', 'STEEM/BTC', 'TRX/BTC', 'XLM/BTC', 'XMR/BTC', 'XRP/BTC', 'XTZ/BTC', 'TRX/BTC', 'VET/BTC', 'USDT/BTC', 'ZEC/BTC', 'ZRX/BTC'] has non-unique elements

Failed validating 'uniqueItems' in schema['properties']['exchange']['properties']['pair_whitelist']:
    {'items': {'type': 'string'}, 'type': 'array', 'uniqueItems': True}

On instance['exchange']['pair_whitelist']:
    ['ADA/BTC',
     'ALGO/BTC',
     'ATOM/BTC',
     'BAT/BTC',
     'BCH/BTC',
     'BNB/BTC',
     'DASH/BTC',
     'EOS/BTC',
     'EOS/BNB',
     'ETC/BTC',
     'ETH/BNB',
     'ETH/BTC',
     'FTT/BTC',
     'IOTA/BTC',
     'LINK/BTC',
     'LTC/BTC',
     'NEO/BTC',
     'OMG/BTC',
     'NXS/BTC',
     'ONT/BTC',
     'PAX/BTC',
     'QTUM/BTC',
     'STEEM/BTC',
     'TRX/BTC',
     'XLM/BTC',
     'XMR/BTC',
     'XRP/BTC',
     'XTZ/BTC',
     'TRX/BTC',
     'VET/BTC',
     'USDT/BTC',
     'ZEC/BTC',
     'ZRX/BTC']
2020-05-23 20:50:23,164 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/maurits/freqtrade/freqtrade/main.py", line 36, in main
    return_code = args['func'](args)
  File "/home/maurits/freqtrade/freqtrade/commands/optimize_commands.py", line 66, in start_hyperopt
    config = setup_optimize_configuration(args, RunMode.HYPEROPT)
  File "/home/maurits/freqtrade/freqtrade/commands/optimize_commands.py", line 18, in setup_optimize_configuration
    config = setup_utils_configuration(args, method)
  File "/home/maurits/freqtrade/freqtrade/configuration/config_setup.py", line 23, in setup_utils_configuration
    validate_config_consistency(config)
  File "/home/maurits/freqtrade/freqtrade/configuration/config_validation.py", line 80, in validate_config_consistency
    validate_config_schema(conf)
  File "/home/maurits/freqtrade/freqtrade/configuration/config_validation.py", line 58, in validate_config_schema
    raise ValidationError(
jsonschema.exceptions.ValidationError: ['ADA/BTC', 'ALGO/BTC', 'ATOM/BTC', 'BAT/BTC', 'BCH/BTC', 'BNB/BTC', 'DASH/BTC', 'EOS/BTC', 'EOS/BNB', 'ETC/BTC', 'ETH/BNB', 'ETH/BTC', 'FTT/BTC', 'IOTA/BTC', 'LINK/BTC', 'LTC/BTC', 'NEO/BTC', 'OMG/BTC', 'NXS/BTC', 'ONT/BTC', 'PAX/BTC', 'QTUM/BTC', 'STEEM/BTC', 'TRX/BTC', 'XLM/BTC', 'XMR/BTC', 'XRP/BTC', 'XTZ/BTC', 'TRX/BTC', 'VET/BTC', 'USDT/BTC', 'ZEC/BTC', 'ZRX/BTC'] has non-unique elements

**Comment by xmatthias** [comment]
TRX/BTC is in the list twice.

But there are other pairs causing problems too i think, you can only have one stake-currency, either BTC or BNB ... Not a mix of both

**Comment by Maurits14** [comment]
Oké thank you very much, I didn’t know about the rule for stakecurrencies
