### ISSUE TITLE
pip3 install -e error 

### ISSUE THREAD

**Issue by joe-nano** [freqtrade/freqtrade#3382]
Is this a bug or not

(.env) ➜  freqtrade git:(develop) ✗ pip3 install -e .

Obtaining file:///Users/Gui/freqtrade/freqtrade

    ERROR: Command errored out with exit status 1:

     command: /Users/Gui/freqtrade/freqtrade/.env/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/Gui/freqtrade/freqtrade/setup.py'"'"'; __file__='"'"'/Users/Gui/freqtrade/freqtrade/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/t3/pq6kvyss6_15d_6cjh6mzwjm0000gn/T/pip-pip-egg-info-x8b893au

         cwd: /Users/Gui/freqtrade/freqtrade/

    Complete output (109 lines):

    zip_safe flag not set; analyzing archive contents...

    Traceback (most recent call last):

      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/sandbox.py", line 157, in save_modules

        yield saved

      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/sandbox.py", line 198, in setup_context

        yield

      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/sandbox.py", line 248, in run_setup

        DirectorySandbox(setup_dir).run(runner)

      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/sandbox.py", line 278, in run

        return func()

      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/sandbox.py", line 246, in runner

        _execfile(setup_script, ns)

      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/sandbox.py", line 47, in _execfile

        exec(code, globals, locals)

      File "/var/folders/t3/pq6kvyss6_15d_6cjh6mzwjm0000gn/T/easy_install-w7h4lbha/pytest-runner-5.2/setup.py", line 21, in <module>

        setup_requires=['pytest-runner', 'numpy'],

      File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup

        dist.run_commands()

      File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands

        self.run_command(cmd)

      File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command

        cmd_obj.run()

      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 209, in run

        os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()

      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 245, in zip_safe

        return analyze_egg(self.bdist_dir, self.stubs)

      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 355, in analyze_egg

        safe = scan_module(egg_dir, base, name, stubs) and safe

      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 395, in scan_module

        symbols = dict.fromkeys(iter_symbols(code))

      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 414, in iter_symbols

        for name in code.co_names:

    AttributeError: type object 'StopIteration' has no attribute 'co_names'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):

      File "<string>", line 1, in <module>

      File "/Users/Gui/freqtrade/freqtrade/setup.py", line 50, in <module>

        'Intended Audience :: Science/Research',

      File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 108, in setup

        _setup_distribution = dist = klass(attrs)

      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/dist.py", line 315, in __init__

        self.fetch_build_eggs(attrs['setup_requires'])

      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/dist.py", line 361, in fetch_build_eggs

        replace_conflicting=True,

      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 850, in resolve

        dist = best[req.key] = env.best_match(req, ws, installer)

      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1122, in best_match

        return self.obtain(req, installer)

      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1134, in obtain

        return installer(requirement)

      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/dist.py", line 429, in fetch_build_egg

        return cmd.easy_install(req)

      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 665, in easy_install

        return self.install_item(spec, dist.location, tmpdir, deps)

      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 695, in install_item

        dists = self.install_eggs(spec, download, tmpdir)

      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 876, in install_eggs

        return self.build_and_install(setup_script, setup_base)

      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1115, in build_and_install

        self.run_setup(setup_script, setup_base, args)

      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1101, in run_setup

        run_setup(setup_script, args)

      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/sandbox.py", line 251, in run_setup

        raise

      File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 130, in __exit__

        self.gen.throw(type, value, traceback)

      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/sandbox.py", line 198, in setup_context

        yield

      File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 130, in __exit__

        self.gen.throw(type, value, traceback)

      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/sandbox.py", line 169, in save_modules

        saved_exc.resume()

      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/sandbox.py", line 144, in resume

        six.reraise(type, exc, self._tb)

      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/_vendor/six.py", line 685, in reraise

        raise value.with_traceback(tb)

      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/sandbox.py", line 157, in save_modules

        yield saved

      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/sandbox.py", line 198, in setup_context

        yield

      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/sandbox.py", line 248, in run_setup

        DirectorySandbox(setup_dir).run(runner)

      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/sandbox.py", line 278, in run

        return func()

      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/sandbox.py", line 246, in runner

        _execfile(setup_script, ns)

      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/sandbox.py", line 47, in _execfile

        exec(code, globals, locals)

      File "/var/folders/t3/pq6kvyss6_15d_6cjh6mzwjm0000gn/T/easy_install-w7h4lbha/pytest-runner-5.2/setup.py", line 21, in <module>

        setup_requires=['pytest-runner', 'numpy'],

      File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup

        dist.run_commands()

      File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands

        self.run_command(cmd)

      File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command

        cmd_obj.run()

      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 209, in run

        os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()

      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 245, in zip_safe

        return analyze_egg(self.bdist_dir, self.stubs)

      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 355, in analyze_egg

        safe = scan_module(egg_dir, base, name, stubs) and safe

      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 395, in scan_module

        symbols = dict.fromkeys(iter_symbols(code))

      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 414, in iter_symbols

        for name in code.co_names:

    AttributeError: type object 'StopIteration' has no attribute 'co_names'

    ----------------------------------------

ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

I get this error when I try to run pip3 install -e .

Please advice on what to do with this error

**Comment by hroff-1902** [comment]
> PLEASE READ THIS:
From now on, the issues at github reporting bugs or problems (with exception to feature requests, suggestions or enhancements) that do not contain the "Describe your environment" section filled out with the values will be closed without further comments. Thanks for understanding.

**Comment by xmatthias** [comment]
I think your python installation is messed up.

The log contains hints to `/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/` - as well as `/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/`.

Mixing python versions is NOT possible (and honestly, i've never seen it - so i suspect your whole python system installation is somewht broken.

you can try to remove the `.env` folder (`rm -rf .env`) - and create it again (best manually to ensure which python version is used (use the latest one available - i assume 3.7 in your case).
And then try to install freqtrade again.

However, please understand that supporting your messed up python installation is beyond of the scope of what we can support.

**Comment by joe-nano** [comment]
Haha,
Mine is working fine, but these are errors I keep on coming across, from other individuals completely new to this space, but are making efforts to learn. 

Thanks for your suggestions.

**Comment by hroff-1902** [comment]
closing it as it's not an issue what freqtrade devs can address directly

**Comment by xmatthias** [comment]
I understand and appreciate that you're trying to help out others. 👍 

However pointing people to the right channel (this is a python core topic - so maybe the python discord server can help) is key to avoid have the wrong people look into a problem they're not the experts to help.
