### ISSUE TITLE
Test Pairlist - Precision Filter / Stoploss

### ISSUE THREAD

**Issue by Prossi79** [freqtrade/freqtrade#3462]
<!-- 
Have you searched for similar issues before posting it?

similar to #3363 

## Describe your environment

  * Operating system: Ubuntu 18.04
  * Python Version: 3.7.4
  * CCXT version: 1.29.5
  * Freqtrade Version: freqtrade develop-aff80d73

  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

precision filter still makes trouble ...

### Steps to reproduce:

relevant part of the config:

```
    "pairlists": [
        
        {
            "method": "VolumePairList",
            "number_assets": 30,
            "sort_key": "quoteVolume",
            "refresh_period": 1800
        },
        {"method": "PrecisionFilter"},
        {"method": "PriceFilter", "low_price_ratio": 0.01},
        {"method": "SpreadFilter", "max_spread_ratio": 0.0075}


```

### Observed Results:

see log below, if precision filter is removed - test pairlist works fine

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
(.env) (base) andreas@andreas-G5-5590:~/freqtrade$ freqtrade test-pairlist --config config_ETHpairs2.json --quote  ETH
2020-06-09 12:26:48,684 - freqtrade.loggers - INFO - Verbosity set to 0
2020-06-09 12:26:48,684 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/andreas/freqtrade/user_data ...
2020-06-09 12:26:48,684 - freqtrade.configuration.configuration - INFO - Using data directory: /home/andreas/freqtrade/user_data/data/binance ...
2020-06-09 12:26:48,684 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2020-06-09 12:26:48,684 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2020-06-09 12:26:48,684 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2020-06-09 12:26:48,684 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2020-06-09 12:26:48,685 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2020-06-09 12:26:48,685 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2020-06-09 12:26:48,688 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 5000}
2020-06-09 12:26:48,691 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2020-06-09 12:26:48,691 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2020-06-09 12:26:48,697 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist VolumePairList from '/home/andreas/freqtrade/freqtrade/pairlist/VolumePairList.py'...
2020-06-09 12:26:48,698 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist PrecisionFilter from '/home/andreas/freqtrade/freqtrade/pairlist/PrecisionFilter.py'...
2020-06-09 12:26:48,698 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/andreas/freqtrade/freqtrade/main.py", line 36, in main
    return_code = args['func'](args)
  File "/home/andreas/freqtrade/freqtrade/commands/pairlist_commands.py", line 29, in start_test_pairlist
    pairlists = PairListManager(exchange, config)
  File "/home/andreas/freqtrade/freqtrade/pairlist/pairlistmanager.py", line 38, in __init__
    pairlist_pos=len(self._pairlist_handlers)
  File "/home/andreas/freqtrade/freqtrade/resolvers/pairlist_resolver.py", line 42, in load_pairlist
    'pairlist_pos': pairlist_pos},
  File "/home/andreas/freqtrade/freqtrade/resolvers/iresolver.py", line 136, in load_object
    kwargs=kwargs)
  File "/home/andreas/freqtrade/freqtrade/resolvers/iresolver.py", line 113, in _load_object
    return module(**kwargs)
  File "/home/andreas/freqtrade/freqtrade/pairlist/PrecisionFilter.py", line 20, in __init__
    self._stoploss = self._config['stoploss']
KeyError: 'stoploss'

  ```

**Comment by Prossi79** [comment]
sorry this was an accident ...
