### ISSUE TITLE
Test Pairlist / precision filter problem

### ISSUE THREAD

**Issue by Prossi79** [freqtrade/freqtrade#3463]
## Describe your environment

  * Operating system: Ubuntu 18.04
  * Python Version: 3.7.4
  * CCXT version: 1.29.5
  * Freqtrade Version: freqtrade develop-aff80d73

  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

precision filter still makes trouble ...

### Steps to reproduce:

relevant part of the config:

```
    "pairlists": [
        
        {
            "method": "VolumePairList",
            "number_assets": 30,
            "sort_key": "quoteVolume",
            "refresh_period": 1800
        },
        {"method": "PrecisionFilter"},
        {"method": "PriceFilter", "low_price_ratio": 0.01},
        {"method": "SpreadFilter", "max_spread_ratio": 0.0075}


```

### Observed Results:

see log below, if precision filter is removed - test pairlist works fine

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
(.env) (base) andreas@andreas-G5-5590:~/freqtrade$ freqtrade test-pairlist --config config_ETHpairs2.json --quote  ETH
2020-06-09 12:26:48,684 - freqtrade.loggers - INFO - Verbosity set to 0
2020-06-09 12:26:48,684 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/andreas/freqtrade/user_data ...
2020-06-09 12:26:48,684 - freqtrade.configuration.configuration - INFO - Using data directory: /home/andreas/freqtrade/user_data/data/binance ...
2020-06-09 12:26:48,684 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2020-06-09 12:26:48,684 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2020-06-09 12:26:48,684 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2020-06-09 12:26:48,684 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2020-06-09 12:26:48,685 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2020-06-09 12:26:48,685 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2020-06-09 12:26:48,688 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 5000}
2020-06-09 12:26:48,691 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2020-06-09 12:26:48,691 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2020-06-09 12:26:48,697 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist VolumePairList from '/home/andreas/freqtrade/freqtrade/pairlist/VolumePairList.py'...
2020-06-09 12:26:48,698 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist PrecisionFilter from '/home/andreas/freqtrade/freqtrade/pairlist/PrecisionFilter.py'...
2020-06-09 12:26:48,698 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/andreas/freqtrade/freqtrade/main.py", line 36, in main
    return_code = args['func'](args)
  File "/home/andreas/freqtrade/freqtrade/commands/pairlist_commands.py", line 29, in start_test_pairlist
    pairlists = PairListManager(exchange, config)
  File "/home/andreas/freqtrade/freqtrade/pairlist/pairlistmanager.py", line 38, in __init__
    pairlist_pos=len(self._pairlist_handlers)
  File "/home/andreas/freqtrade/freqtrade/resolvers/pairlist_resolver.py", line 42, in load_pairlist
    'pairlist_pos': pairlist_pos},
  File "/home/andreas/freqtrade/freqtrade/resolvers/iresolver.py", line 136, in load_object
    kwargs=kwargs)
  File "/home/andreas/freqtrade/freqtrade/resolvers/iresolver.py", line 113, in _load_object
    return module(**kwargs)
  File "/home/andreas/freqtrade/freqtrade/pairlist/PrecisionFilter.py", line 20, in __init__
    self._stoploss = self._config['stoploss']
KeyError: 'stoploss'

  ```

**Comment by xmatthias** [comment]
the problem with precision filter is how it works / how it functions.

it does require stoploss to be available - as it calculates if the pair is "high-priced" enough to place a stoploss X% below.

Now we're not giving it these X% - therefore it fails. 

I know exactly where / when this was introduced - however the real problem is what the previous behavior was. 
It wasn't using some arbitrary stoploss - it was just disabling PrecisionFilter implicitly (because no stoploss available) - without telling you or anything - it just did nothing.

Also now - this can be changed in a one-line PR (maybe 3 ...) to not fail...

But what would we expect in this case? 
Should `test-pairlist` simply skip this filter as no stoploss is available? 
use 5% as that's my personal favorite? or maybe 10% as that's the favorite from someone else?


You can work around this very easily by adding a stoploss to your configuration (note that it'll overwrite a stoploss in the strategy, so handle with care).

**Comment by Prossi79** [comment]
Thanks for your quick response and input - how was it managed in previous versions? I remember that it used to work before, with strategy list and test pairlist

PS: yes, root cause is clear :) #3363

**Comment by xmatthias** [comment]
well - it was optional to have the stoploss key - and if it wasn't there, this pairlist was skipped (which is wrong in my eyes).

**Comment by hroff-1902** [comment]
Now I do not understand what the expected behavior of the bot itself (not the PrecisionFilter) is when no stoploss is defined in either config or strategy... Should not we require defining it in either config or the strategy? I never used it undefined, and can only see that it's stated as "optional" in the docs -- with no behavior explained, how bot behaves when it's not set... (Maybe I'm missing it in somewhere in the docs)...

No stoploss defined -> no stoploss conditions set and checked?

**Comment by xmatthias** [comment]
oh well - stoploss IS required for trade operations.

it's optional in the configuration - as you can set it in configuration or strategy ... 
however in the end, it needs to be there for trading operations.

This however creates a problem for commands like `test-pairlist` - which has nothing to do with strategy - and therefore also does not load the strategy.

in #3453 i've now changed this to point the stoposs requirement out explicitly, so this does not fail with a uncought exception, but with an error-message we control.
