### ISSUE TITLE
`test-pairlist` fails if no markets loaded

### ISSUE THREAD

**Issue by hroff-1902** [freqtrade/freqtrade#3465]
`test-pairlist` fails in unexpected way if markets were not able to be loaded (due to 4xx error, for example);

This should be handled gracefully with a DependencyException (for example, or OperationalException) exception raised, an error message and exit code 1, it should not crash with traceback.

```
$ freqtrade test-pairlist -c config_kraken.json
2020-06-09 12:46:47,312 - freqtrade.loggers - INFO - Verbosity set to 0
2020-06-09 12:46:47,312 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/user/freqtrade-wrk/github-hroff-1902/freqtrade/user_data ...
2020-06-09 12:46:47,313 - freqtrade.configuration.configuration - INFO - Using data directory: /home/user/freqtrade-wrk/github-hroff-1902/freqtrade/user_data/data/kraken ...
2020-06-09 12:46:47,313 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2020-06-09 12:46:47,313 - freqtrade.configuration.check_exchange - INFO - Exchange "kraken" is officially supported by the Freqtrade development team.
2020-06-09 12:46:47,313 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2020-06-09 12:46:47,313 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2020-06-09 12:46:47,315 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2020-06-09 12:46:47,315 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2020-06-09 12:46:47,317 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 3100}
2020-06-09 12:46:47,320 - freqtrade.exchange.exchange - INFO - Using Exchange "Kraken"
2020-06-09 12:46:47,320 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Kraken'...
2020-06-09 12:46:47,324 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from '/home/user/freqtrade-wrk/github-hroff-1902/freqtrade/freqtrade/pairlist/StaticPairList.py'...
2020-06-09 12:46:47,324 - freqtrade.exchange.exchange - WARNING - Markets were not loaded. Loading them now..
2020-06-09 12:46:53,817 - freqtrade.exchange.exchange - WARNING - Unable to initialize markets. Reason: GET https://kraken.zendesk.com/api/v2/help_center/en-us/articles/205893708 429 Too Many Requests Number of allowed API requests per minute exceeded
2020-06-09 12:46:53,818 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/user/freqtrade-wrk/github-hroff-1902/freqtrade/freqtrade/main.py", line 36, in main
    return_code = args['func'](args)
  File "/home/user/freqtrade-wrk/github-hroff-1902/freqtrade/freqtrade/commands/pairlist_commands.py", line 30, in start_test_pairlist
    pairlists.refresh_pairlist()
  File "/home/user/freqtrade-wrk/github-hroff-1902/freqtrade/freqtrade/pairlist/pairlistmanager.py", line 91, in refresh_pairlist
    pairlist = self._pairlist_handlers[0].gen_pairlist(self._whitelist, tickers)
  File "/home/user/freqtrade-wrk/github-hroff-1902/freqtrade/freqtrade/pairlist/StaticPairList.py", line 50, in gen_pairlist
    return self._whitelist_for_active_markets(self._config['exchange']['pair_whitelist'])
  File "/home/user/freqtrade-wrk/github-hroff-1902/freqtrade/freqtrade/pairlist/IPairList.py", line 157, in _whitelist_for_active_markets
    if pair not in markets:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by xmatthias** [comment]
Please make sure to use an uptodate version of ccxt...

the "zendesk" / kraken issue is supposed to be fixed since early May ... 
(not to say we should handle it gracefully anyway).

**Comment by hroff-1902** [comment]
yeah, it does not appear again after update, but the fix here can be in the proper handling of empty markets loaded for some reasons...
