### ISSUE TITLE
Impossible to load strategy without virtual environment, while strategy works within virtual environment

### ISSUE THREAD

**Issue by Maurits14** [freqtrade/freqtrade#3472]
## Describe your environment

  * Operating system: Dietpi
  * Python Version: 3.7.2. (`python -V`)

  
## Your question

I am trying to let freqtrade run as a systemd service, which works perfectly fine except for the main command. I have to code a command without using the virtual environment, so I came up with the following command: /home/dietpi/freqtrade/freqtrade/main.py trade -c /home/dietpi/freqtrade/config.json -s BBRSI --userdir /home/dietpi/freqtrade/ 

However, when I try to run this command (not using the service) the following error occurs: 
"freqtrade.exceptions.OperationalException: Impossible to load Strategy 'BBRSI'. This class does not exist or contains Python code errors. " 

Because of this I tried to run my strategy within the virtual environment. Nothing happend and the strategy was executed perfectly. 

Given that, I believe that I miss something or make a mistake within my main command... Could you please help me out with my problem?

The full output of the command:
```
dietpi@DietPi:~$ /home/dietpi/freqtrade/freqtrade/main.py trade -c /home/dietpi/freqtrade/config.json -s BBRSI --userdir /home/dietpi/freqtrade/
2020-06-11 11:29:31,146 - freqtrade.loggers - INFO - Verbosity set to 0
2020-06-11 11:29:31,147 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
2020-06-11 11:29:31,148 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2020-06-11 11:29:31,148 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:///tradesv3.dryrun.sqlite"
2020-06-11 11:29:31,148 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 15 ...
2020-06-11 11:29:31,149 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/dietpi/freqtrade ...
2020-06-11 11:29:31,150 - freqtrade.configuration.configuration - INFO - Using data directory: /home/dietpi/freqtrade/data/binance ...
2020-06-11 11:29:31,151 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2020-06-11 11:29:31,151 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2020-06-11 11:29:31,152 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2020-06-11 11:29:31,152 - freqtrade.freqtradebot - INFO - Starting freqtrade develop
2020-06-11 11:29:31,153 - freqtrade.commands.trade_commands - ERROR - Impossible to load Strategy 'BBRSI'. This class does not exist or contains Python code errors.
2020-06-11 11:29:31,153 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/dietpi/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker = Worker(args)
  File "/home/dietpi/freqtrade/freqtrade/worker.py", line 34, in __init__
    self._init(False)
  File "/home/dietpi/freqtrade/freqtrade/worker.py", line 51, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/home/dietpi/freqtrade/freqtrade/freqtradebot.py", line 63, in __init__
    self.strategy: IStrategy = StrategyResolver.load_strategy(self.config)
  File "/home/dietpi/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 47, in load_strategy
    extra_dir=config.get('strategy_path'))
  File "/home/dietpi/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 179, in _load_strategy
    f"Impossible to load Strategy '{strategy_name}'. This class does not exist "
freqtrade.exceptions.OperationalException: Impossible to load Strategy 'BBRSI'. This class does not exist or contains Python code errors.
```

**Comment by xmatthias** [comment]
Virtualenv or not has nothing to do with it - i doubt that this exact command will work in the virtualenv (everything after `trade ` identical to test...).


I think that the main cause for this is you're specifying of `--userdir /home/dietpi/freqtrade/`.

This takes the assumption that the strategy directory is `/home/dietpi/freqtrade/strategies` - which it usually is not.

Most likely (without seeing the "working" log) - you'll want to use `--userdir /home/dietpi/freqtrade/user_data/` - making user_data your user_data directory.... so the strategy will be in `/home/dietpi/freqtrade/user_data/strategies/whateverfilename.py` ...

**Comment by Maurits14** [comment]
Thank you so much, it worked!
