### ISSUE TITLE
Question about integration EMA in hyperopt

### ISSUE THREAD

**Issue by Maurits14** [freqtrade/freqtrade#3526]
Ubuntu: 20.04 LTS
Python:  3.8.2
Freqtrade: develop-9d6a41aa

I'm trying to integrate my new strategy into a hyperopt file. Due to the fact that in the "sample hyperopt file" code for EMA is not included and the fact that I can not find anything about EMA code online, I tried to write the code myself. Unfortunately, I came across the following error running the hyperopt file:
`AttributeError: 'NoneType' object has no attribute 'loc'`

However, I have probably made several mistakes in the hyperopt file, so I was wondering whether someone would be so kind to take the time to read through my hyperopt file and help me out, especially with the EMA integration. Or could someone tell where I can find more information about the code for EMA?

I ran the following command:
```
freqtrade hyperopt --hyperopt Money_hyperopt --spaces roi stoploss trailing --strategy Money_strategy --config config.json -e 100
```

This gave me the following output:
```
2020-06-27 11:21:49,181 - freqtrade.loggers - INFO - Verbosity set to 0
2020-06-27 11:21:49,182 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 50 ...
2020-06-27 11:21:49,183 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/maurits/freqtrade/user_data ...
2020-06-27 11:21:49,183 - freqtrade.configuration.configuration - INFO - Using data directory: /home/maurits/freqtrade/user_data/data/binance ...
2020-06-27 11:21:49,184 - freqtrade.configuration.configuration - INFO - Using Hyperopt class name: Money_hyperopt
2020-06-27 11:21:49,184 - freqtrade.configuration.configuration - INFO - Parameter --epochs detected ... Will run Hyperopt with for 100 epochs ...
2020-06-27 11:21:49,184 - freqtrade.configuration.configuration - INFO - Parameter -s/--spaces detected: ['roi', 'stoploss', 'trailing']
2020-06-27 11:21:49,184 - freqtrade.configuration.configuration - INFO - Parameter -j/--job-workers detected: -1
2020-06-27 11:21:49,184 - freqtrade.configuration.configuration - INFO - Parameter --min-trades detected: 1
2020-06-27 11:21:49,184 - freqtrade.configuration.configuration - INFO - Using Hyperopt loss class name: DefaultHyperOptLoss
2020-06-27 11:21:49,185 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2020-06-27 11:21:49,185 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2020-06-27 11:21:49,185 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2020-06-27 11:21:49,185 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2020-06-27 11:21:49,188 - freqtrade.commands.optimize_commands - INFO - Starting freqtrade in Hyperopt mode
2020-06-27 11:21:49,189 - filelock - INFO - Lock 140277777315008 acquired on /home/maurits/freqtrade/user_data/hyperopt.lock
2020-06-27 11:21:49,189 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2020-06-27 11:21:49,189 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2020-06-27 11:21:49,196 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 200}
2020-06-27 11:21:49,202 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2020-06-27 11:21:50,422 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2020-06-27 11:21:50,579 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from '/home/maurits/freqtrade/freqtrade/pairlist/StaticPairList.py'...
2020-06-27 11:21:50,596 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy Money_strategy from '/home/maurits/freqtrade/user_data/strategies/Money_strategy.py'...
2020-06-27 11:21:50,596 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ticker_interval' with value in config file: 5m.
2020-06-27 11:21:50,596 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: BTC.
2020-06-27 11:21:50,597 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 0.004.
2020-06-27 11:21:50,597 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'buy': 10, 'sell': 30}.
2020-06-27 11:21:50,597 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'use_sell_signal' with value in config file: True.
2020-06-27 11:21:50,597 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'sell_profit_only' with value in config file: False.
2020-06-27 11:21:50,598 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ignore_roi_if_buy_signal' with value in config file: False.
2020-06-27 11:21:50,598 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'60': 0, '50': 0.01, '30': 0.02, '0': 0.04}
2020-06-27 11:21:50,598 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ticker_interval: 5m
2020-06-27 11:21:50,599 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.06
2020-06-27 11:21:50,599 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2020-06-27 11:21:50,599 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2020-06-27 11:21:50,599 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2020-06-27 11:21:50,599 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
2020-06-27 11:21:50,599 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'market', 'sell': 'market', 'stoploss': 'market', 'stoploss_on_exchange': False}
2020-06-27 11:21:50,599 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
2020-06-27 11:21:50,600 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: BTC
2020-06-27 11:21:50,600 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 0.004
2020-06-27 11:21:50,600 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 20
2020-06-27 11:21:50,600 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'buy': 10, 'sell': 30}
2020-06-27 11:21:50,600 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_sell_signal: True
2020-06-27 11:21:50,600 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_only: False
2020-06-27 11:21:50,600 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_buy_signal: False
2020-06-27 11:21:50,600 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2020-06-27 11:21:50,615 - freqtrade.resolvers.iresolver - INFO - Using resolved hyperopt Money_hyperopt from '/home/maurits/freqtrade/user_data/hyperopts/Money_hyperopt.py'...
2020-06-27 11:21:50,795 - freqtrade.resolvers.iresolver - INFO - Using resolved hyperoptloss DefaultHyperOptLoss from '/home/maurits/freqtrade/freqtrade/optimize/default_hyperopt_loss.py'...
2020-06-27 11:21:50,796 - freqtrade.optimize.hyperopt - INFO - Using optimizer random state: 2637
2020-06-27 11:21:50,796 - freqtrade.data.history.history_utils - INFO - Using indicator startup period: 20 ...
2020-06-27 11:21:51,087 - freqtrade.data.converter - INFO - Missing data fillup for BNB/BTC: before: 8608 - after: 8638
2020-06-27 11:21:51,199 - freqtrade.data.converter - INFO - Missing data fillup for DASH/BTC: before: 8608 - after: 8638
2020-06-27 11:21:51,323 - freqtrade.data.converter - INFO - Missing data fillup for EOS/BTC: before: 8666 - after: 8696
2020-06-27 11:21:51,438 - freqtrade.data.converter - INFO - Missing data fillup for ETC/BTC: before: 8608 - after: 8638
2020-06-27 11:21:51,541 - freqtrade.data.converter - INFO - Missing data fillup for ETH/BTC: before: 8666 - after: 8696
2020-06-27 11:21:51,648 - freqtrade.data.converter - INFO - Missing data fillup for LINK/BTC: before: 8666 - after: 8696
2020-06-27 11:21:51,754 - freqtrade.data.converter - INFO - Missing data fillup for LTC/BTC: before: 8666 - after: 8696
2020-06-27 11:21:51,864 - freqtrade.data.converter - INFO - Missing data fillup for NEO/BTC: before: 8666 - after: 8696
2020-06-27 11:21:51,982 - freqtrade.data.converter - INFO - Missing data fillup for ONT/BTC: before: 8608 - after: 8638
2020-06-27 11:21:52,198 - freqtrade.data.converter - INFO - Missing data fillup for XRP/BTC: before: 8665 - after: 8695
2020-06-27 11:21:52,346 - freqtrade.data.converter - INFO - Missing data fillup for XMR/BTC: before: 8665 - after: 8695
2020-06-27 11:21:52,444 - freqtrade.data.converter - INFO - Missing data fillup for XTZ/BTC: before: 8665 - after: 8695
2020-06-27 11:21:52,576 - freqtrade.data.converter - INFO - Missing data fillup for ZEC/BTC: before: 8608 - after: 8638
2020-06-27 11:21:52,585 - freqtrade.optimize.backtesting - INFO - Loading data from 2020-04-19T08:25:00+00:00 up to 2020-05-19T13:00:00+00:00 (30 days)..
2020-06-27 11:21:52,585 - freqtrade.configuration.timerange - WARNING - Moving start-date by 20 candles to account for startup time.
2020-06-27 11:21:52,809 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/maurits/freqtrade/freqtrade/main.py", line 36, in main
    return_code = args['func'](args)
  File "/home/maurits/freqtrade/freqtrade/commands/optimize_commands.py", line 81, in start_hyperopt
    hyperopt.start()
  File "/home/maurits/freqtrade/freqtrade/optimize/hyperopt.py", line 628, in start
    preprocessed[pair] = trim_dataframe(df, timerange)
  File "/home/maurits/freqtrade/freqtrade/data/converter.py", line 128, in trim_dataframe
    df = df.loc[df[df_date_col] >= start, :]
AttributeError: 'NoneType' object has no attribute 'loc'
```

My entire hyperopt file:

```
# pragma pylint: disable=missing-docstring, invalid-name, pointless-string-statement

# --- Do not remove these libs ---
from functools import reduce
from typing import Any, Callable, Dict, List

import numpy as np  # noqa
import pandas as pd  # noqa
from pandas import DataFrame
from skopt.space import Categorical, Dimension, Integer, Real  # noqa

from freqtrade.optimize.hyperopt_interface import IHyperOpt

# --------------------------------
# Add your lib to import here
import talib.abstract as ta  # noqa
import freqtrade.vendor.qtpylib.indicators as qtpylib


class Money_hyperopt(IHyperOpt):
    """
    This is a sample Hyperopt to inspire you.

    More information in the documentation: https://www.freqtrade.io/en/latest/hyperopt/

    You should:
    - Rename the class name to some unique name.
    - Add any methods you want to build your hyperopt.
    - Add any lib you need to build your hyperopt.

    An easier way to get a new hyperopt file is by using
    `freqtrade new-hyperopt --hyperopt MyCoolHyperopt`.

    You must keep:
    - The prototypes for the methods: populate_indicators, indicator_space, buy_strategy_generator.

    The methods roi_space, generate_roi_table and stoploss_space are not required
    and are provided by default.
    However, you may override them if you need 'roi' and 'stoploss' spaces that
    differ from the defaults offered by Freqtrade.
    Sample implementation of these methods will be copied to `user_data/hyperopts` when
    creating the user-data directory using `freqtrade create-userdir --userdir user_data`,
    or is available online under the following URL:
    https://github.com/freqtrade/freqtrade/blob/develop/freqtrade/templates/sample_hyperopt_advanced.py.
    """

    @staticmethod
    def populate_indicators(dataframe: DataFrame, metadata: dict) -> DataFrame:
        macd = ta.MACD(dataframe)
        dataframe['macd'] = macd['macd']
        dataframe['macdsignal'] = macd['macdsignal']
        dataframe['macdhist'] = macd['macdhist']

        dataframe['ema3'] = ta.EMA(dataframe, timeperiod=3)
        dataframe['ema5'] = ta.EMA(dataframe, timeperiod=5)
        dataframe['ema10'] = ta.EMA(dataframe, timeperiod=10)
        dataframe['ema21'] = ta.EMA(dataframe, timeperiod=21)
        dataframe['ema50'] = ta.EMA(dataframe, timeperiod=50)
        dataframe['ema100'] = ta.EMA(dataframe, timeperiod=100)
        dataframe['ema120'] = ta.EMA(dataframe, timeperiod=120)
        dataframe['ema150'] = ta.EMA(dataframe, timeperiod=150)
        dataframe['ema180'] = ta.EMA(dataframe, timeperiod=180)
        dataframe['ema200'] = ta.EMA(dataframe, timeperiod=200)

    def buy_strategy_generator(params: Dict[str, Any]) -> Callable:
        """
        Define the buy strategy parameters to be used by Hyperopt.
        """
        def populate_buy_trend(dataframe: DataFrame, metadata: dict) -> DataFrame:
            """
            Buy strategy Hyperopt will build and use.
            """
            conditions = []

            # GUARDS AND TRENDS
            if 'trigger' in params:
                if params ['trigger'] == 'ema3':
                    conditions.append(dataframe['close'] > dataframe['ema3'])
                if params ['trigger'] == 'ema5':
                    conditions.append(dataframe['close'] > dataframe['ema5'])
                if params ['trigger'] == 'ema10':
                    conditions.append(dataframe['close'] > dataframe['ema10'])
                if params ['trigger'] == 'ema21':
                    conditions.append(dataframe['close'] > dataframe['ema21'])
                if params ['trigger'] == 'ema50':
                    conditions.append(dataframe['close'] > dataframe['ema50'])
                if params ['trigger'] == 'ema100':
                    conditions.append(dataframe['close'] > dataframe['ema100'])
                if params ['trigger'] == 'ema120':
                    conditions.append(dataframe['close'] > dataframe['ema120'])
                if params ['trigger'] == 'ema150':
                    conditions.append(dataframe['close'] > dataframe['ema150'])
                if params ['trigger'] == 'ema180':
                    conditions.append(dataframe['close'] > dataframe['ema180'])
                if params ['trigger'] == 'ema200':
                    conditions.append(dataframe['close'] > dataframe['ema200'])

            if 'trigger' in params:
                if params['trigger'] == 'macd_cross_signal':
                    conditions.append(qtpylib.crossed_above(
                        dataframe['macd'], dataframe['macdsignal']
                    ))


            # Check that volume is not 0
            conditions.append(dataframe['volume'] > 0)

            if conditions:
                dataframe.loc[
                    reduce(lambda x, y: x & y, conditions),
                    'buy'] = 1

            return dataframe

        return populate_buy_trend

    @staticmethod
    def indicator_space() -> List[Dimension]:
        """
        Define your Hyperopt space for searching buy strategy parameters.
        """
        return [
            Categorical(['macd_cross_signal', 'ema3', 'ema5', 'ema10', 'ema21', 'ema50', 'ema100', 'ema120', 'ema150', 'ema180', 'ema200'], name='trigger')
        ]

    @staticmethod
    def sell_strategy_generator(params: Dict[str, Any]) -> Callable:
        """
        Define the sell strategy parameters to be used by Hyperopt.
        """
        def populate_sell_trend(dataframe: DataFrame, metadata: dict) -> DataFrame:
            """
            Sell strategy Hyperopt will build and use.
            """
            conditions = []

            # GUARDS AND TRENDS
            if 'macdhist-enabled' in params and params['macdhist-enabled']:
                conditions.append(dataframe['macdhist'] > params['macdhist-value'])


            # Check that volume is not 0
            conditions.append(dataframe['volume'] > 0)

            if conditions:
                dataframe.loc[
                    reduce(lambda x, y: x & y, conditions),
                    'sell'] = 1

            return dataframe

        return populate_sell_trend

    @staticmethod
    def sell_indicator_space() -> List[Dimension]:
        """
        Define your Hyperopt space for searching sell strategy parameters.
        """
        return [
            Integer(10, 50, name='macdhist-value'),

        ]

    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators. Should be a copy of same method from strategy.
        Must align to populate_indicators in this file.
        Only used when --spaces does not include buy space.
        """
        dataframe.loc[
            ((qtpylib.crossed_above(dataframe['macd'], dataframe['macdsignal']
                )) &
                (dataframe['close'] > dataframe['ema200'])
            ),
            'buy'] = 1

        return dataframe

    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators. Should be a copy of same method from strategy.
        Must align to populate_indicators in this file.
        Only used when --spaces does not include sell space.
        """
        dataframe.loc[
            ((dataframe['macdhist'] >= 19)
            ),
            'sell'] = 1

        return dataframe
```

Thank you very much in advance for your help, I really appreciate it!

**Comment by hroff-1902** [comment]
what's the contents of your strategy Money_strategy?

**Comment by hroff-1902** [comment]
you missed
```
return dataframe
```
at the end of populate_indicators()

**Comment by hroff-1902** [comment]
@xmatthias 
we need to add checks for the dataframe returned from the user custom methods into backtesting and hyperopt, in the same way dataframe is checked for dry/live

**Comment by xmatthias** [comment]
@hroff-1902 #2696 :)

**Comment by Maurits14** [comment]
Thank you.
