### ISSUE TITLE
Bitfinex order submission crashing the bot

### ISSUE THREAD

**Issue by eniware-org** [freqtrade/freqtrade#3532]
- Ubuntu 18.04 LTS
- Python 3.6.9
- version 2020.5

```
2020-06-29 02:55:12,402 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': buy, 'exchange': 'Bitfinex', 'pair': 'BTC/USD', 'limit': 9134.6, 'order_type': 'limit', 'stake_amount': 30.0, 'stake_currency': 'USD', 'fiat_currency': 'USD', 'amount': 0.003284216057627044, 'open_date': datetime.datetime(2020, 6, 28, 23, 55, 10, 910834), 'current_rate': 9134.6}
2020-06-29 02:55:12,689 - freqtrade.commands.trade_commands - ERROR - 'bitfinex2' object has no attribute 'privatePostOrderStatus'
2020-06-29 02:55:12,689 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/eniware/freqtrade/freqtrade/commands/trade_commands.py", line 20, in start_trading
    worker.run()
  File "/home/eniware/freqtrade/freqtrade/worker.py", line 73, in run
    state = self._worker(old_state=state)
  File "/home/eniware/freqtrade/freqtrade/worker.py", line 107, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
  File "/home/eniware/freqtrade/freqtrade/worker.py", line 128, in _throttle
    result = func(*args, **kwargs)
  File "/home/eniware/freqtrade/freqtrade/worker.py", line 141, in _process_running
    self.freqtrade.process()
  File "/home/eniware/freqtrade/freqtrade/freqtradebot.py", line 156, in process
    self.check_handle_timedout()
  File "/home/eniware/freqtrade/freqtrade/freqtradebot.py", line 889, in check_handle_timedout
    order = self.exchange.get_order(trade.open_order_id, trade.pair)
  File "/home/eniware/freqtrade/freqtrade/exchange/common.py", line 113, in wrapper
    return f(*args, **kwargs)
  File "/home/eniware/freqtrade/freqtrade/exchange/exchange.py", line 990, in get_order
    return self._api.fetch_order(order_id, pair)
  File "/home/eniware/freqtrade/.env/lib/python3.6/site-packages/ccxt/bitfinex.py", line 853, in fetch_order
    response = self.privatePostOrderStatus(self.extend(request, params))
AttributeError: 'bitfinex2' object has no attribute 'privatePostOrderStatus'
2020-06-29 02:55:12,692 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2020-06-29 02:55:12,692 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2020-06-29 02:55:12,692 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2020-06-29 02:55:12,692 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
```

**Comment by xmatthias** [comment]
well - bitfinex (nor bitfinex2) is not a supported exchange - so you're most likely one of the first to try this.

Please add your ccxt version as well - as i suspect this is more related to ccxt than to freqtrade itself.

**Comment by eniware-org** [comment]
```
pip freeze | grep ccxt
ccxt==1.28.49
```

**Comment by xmatthias** [comment]
i would suggest to update ccxt and retry (`pip install -U ccxt`).

I can however not guarantee it'll work - and we will not provide further support for bitfinex at this point in time.

Best switch to one of the supported and tested exchanges.

**Comment by hroff-1902** [comment]
agree with the above -- first try to update ccxt

**Comment by eniware-org** [comment]
Thank you. Upgraded to ccxt==1.30.51, but still have the same problem.
However, from the log in the initial post I noticed that ```/home/eniware/freqtrade/freqtrade/exchange/exchange.py``` calls ```/home/eniware/freqtrade/.env/lib/python3.6/site-packages/ccxt/bitfinex.py ``` rather than ```bitfinex2.py```. Could this be the cause of the problem with the missing attribute?

**Comment by xmatthias** [comment]
well - set 
```

**Comment by hroff-1902** [comment]
I was going to have a look at bitfinex exchange soon, but not right now.

I'm proposing to keep this open so some time for me as a reminder.

**Comment by xmatthias** [comment]
I'm going to close this now - as i don't think it makes sense to have this stick around any longer.

While bitfinex2 sounds like the newer version, it's actually using v1 under the hood (and does not support fetchOrder, which excludes it from working with freqtrade automatically).

If any, then "bitfinex" will be working now, although it's not a supported exchange, so you might be the first to try running freqtrade against that exchange.
