### ISSUE TITLE
problem in binance future

### ISSUE THREAD

**Issue by asaltrader** [freqtrade/freqtrade#3569]
I want to trade on binance future, then i set this parameter in config file
```
"ccxt_config": {"enableRateLimit": true, "options" : {"defaultType": "future"}},
"ccxt_async_config": {
     "enableRateLimit": true,
     "rateLimit": 200,
     "options" : {
        "defaultType": "future"
     }
},
```

and now
after some hour robot will stop !

```
2020-07-07 21:00:02,837 - freqtrade.wallets - INFO - Wallets synced.
2020-07-07 21:00:02,840 - freqtrade.freqtradebot - INFO - Buy signal found: about create a new trade with stake_amount: 5 ...
2020-07-07 21:00:02,841 - freqtrade.freqtradebot - INFO - Executing Buy for ETH/USDT
2020-07-07 21:00:02,842 - freqtrade.freqtradebot - INFO - Using Last Bid / Last Price
2020-07-07 21:00:03,307 - freqtrade.commands.trade_commands - ERROR - '>' not supported between instances of 'NoneType' and 'float'
2020-07-07 21:00:03,308 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/root/Robots/A01/freqtrade/freqtrade/commands/trade_commands.py", line 20, in start_trading
    worker.run()
  File "/root/Robots/A01/freqtrade/freqtrade/worker.py", line 73, in run
    state = self._worker(old_state=state)
  File "/root/Robots/A01/freqtrade/freqtrade/worker.py", line 107, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
  File "/root/Robots/A01/freqtrade/freqtrade/worker.py", line 128, in _throttle
    result = func(*args, **kwargs)
  File "/root/Robots/A01/freqtrade/freqtrade/worker.py", line 141, in _process_running
    self.freqtrade.process()
  File "/root/Robots/A01/freqtrade/freqtrade/freqtradebot.py", line 167, in process
    self.enter_positions()
  File "/root/Robots/A01/freqtrade/freqtrade/freqtradebot.py", line 233, in enter_positions
    trades_created += self.create_trade(pair)
  File "/root/Robots/A01/freqtrade/freqtrade/freqtradebot.py", line 446, in create_trade
    return self.execute_buy(pair, stake_amount)
  File "/root/Robots/A01/freqtrade/freqtrade/freqtradebot.py", line 486, in execute_buy
    buy_limit_requested = self.get_buy_rate(pair, True)
  File "/root/Robots/A01/freqtrade/freqtrade/freqtradebot.py", line 280, in get_buy_rate
    if ticker['last'] and ticker_rate > ticker['last']:
TypeError: '>' not supported between instances of 'NoneType' and 'float'
2020-07-07 21:00:03,311 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2020-07-07 21:00:03,312 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2020-07-07 21:00:03,541 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2020-07-07 21:00:03,542 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
```

**Comment by Theagainmen** [comment]
Please fill in the given template when you created this issue, so the devs can help you. (also I'm pretty sure there are multiple issues about futures already..)




## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
  ```

**Comment by rabinhod** [comment]
- Operating system: Ubuntu 18.04.4 LTS
- Python Version: Python 3.6.9
- CCXT version: ccxt==1.30.67
- Freqtrade Version: freqtrade 2020.6


problem : i set freqtrade on future binance and it was stop after some hour ! i think when it want to open trade get error !

config file : 
`"ccxt_config": {"enableRateLimit": true, "options" : {"defaultType": "future"}},
"ccxt_async_config": {
     "enableRateLimit": true,
     "rateLimit": 200,
     "options" : {
        "defaultType": "future"
     }
},`

error log :
`2020-07-07 21:00:02,837 - freqtrade.wallets - INFO - Wallets synced.
2020-07-07 21:00:02,840 - freqtrade.freqtradebot - INFO - Buy signal found: about create a new trade with stake_amount: 5 ...
2020-07-07 21:00:02,841 - freqtrade.freqtradebot - INFO - Executing Buy for ETH/USDT
2020-07-07 21:00:02,842 - freqtrade.freqtradebot - INFO - Using Last Bid / Last Price
2020-07-07 21:00:03,307 - freqtrade.commands.trade_commands - ERROR - '>' not supported between instances of 'NoneType' and 'float'
2020-07-07 21:00:03,308 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/root/Robots/A01/freqtrade/freqtrade/commands/trade_commands.py", line 20, in start_trading
    worker.run()
  File "/root/Robots/A01/freqtrade/freqtrade/worker.py", line 73, in run
    state = self._worker(old_state=state)
  File "/root/Robots/A01/freqtrade/freqtrade/worker.py", line 107, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
  File "/root/Robots/A01/freqtrade/freqtrade/worker.py", line 128, in _throttle
    result = func(*args, **kwargs)
  File "/root/Robots/A01/freqtrade/freqtrade/worker.py", line 141, in _process_running
    self.freqtrade.process()
  File "/root/Robots/A01/freqtrade/freqtrade/freqtradebot.py", line 167, in process
    self.enter_positions()
  File "/root/Robots/A01/freqtrade/freqtrade/freqtradebot.py", line 233, in enter_positions
    trades_created += self.create_trade(pair)
  File "/root/Robots/A01/freqtrade/freqtrade/freqtradebot.py", line 446, in create_trade
    return self.execute_buy(pair, stake_amount)
  File "/root/Robots/A01/freqtrade/freqtrade/freqtradebot.py", line 486, in execute_buy
    buy_limit_requested = self.get_buy_rate(pair, True)
  File "/root/Robots/A01/freqtrade/freqtrade/freqtradebot.py", line 280, in get_buy_rate
    if ticker['last'] and ticker_rate > ticker['last']:
TypeError: '>' not supported between instances of 'NoneType' and 'float'
2020-07-07 21:00:03,311 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2020-07-07 21:00:03,312 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2020-07-07 21:00:03,541 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2020-07-07 21:00:03,542 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...`

**Comment by xmatthias** [comment]
futures will not work with freqtrade at this point, and it's a known problem (#3162, #3177, #2940).

ccxt is in the process of unifying both margin and futures interfaces (intended for Q2 iirc), and until that work is done, freqtrade will take no efforts in supporting futures, as it would require manual work for every exchange (all exchanges work slightly differently).
Also - since we intend to rely on ccxt in the future too, we might do things differently, causing us to completely revise things in the future.

This would lead to a lot of wasted time (both in implementing future support per exchange in freqtrade, and then again as we'll eventually be adapting to the way ccxt creates the interface).


since we are an open source project ran by volunteers in our free time, we have to invest our time where it makes sense - futures (nor margin) do make sense at the moment for the above reasons.

Thanks for your understanding.

on a seperate note: 
Binance only offers around 8 pairs (at the time of writing) in future markets - so it would not be worth the effort to implement it for binance seperately.
