### ISSUE TITLE
Bittrex is not working for PriceFilter

### ISSUE THREAD

**Issue by Vildnex** [freqtrade/freqtrade#3615]
## Describe your environment

  * Operating system: Ubuntu Server
  * Python Version: 3.8.2 (`python -V`)
  * CCXT version: 1.30.48 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2020.6 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

I have the following config file:

```
{
  "max_open_trades": 10,
  "stake_currency": "USDT",
  "stake_amount": "unlimited",
  "amend_last_stake_amount": true,
  "tradable_balance_ratio": 0.99,
  "fiat_display_currency": "USD",
  "dry_run": true,
  "dry_run_wallet": 200,
  "unfilledtimeout": {
    "buy": 10,
    "sell": 30
  },
  "order_types": {
    "buy": "limit",
    "sell": "limit",
    "stoploss": "limit",
    "stoploss_on_exchange": false,
    "stoploss_on_exchange_interval": 60
  },
  "bid_strategy": {
    "ask_last_balance": 0.0,
    "use_order_book": false,
    "order_book_top": 1,
    "check_depth_of_market": {
      "enabled": false,
      "bids_to_ask_delta": 1
    }
  },
  "ask_strategy": {
    "use_order_book": false,
    "order_book_min": 1,
    "order_book_max": 9,
    "use_sell_signal": true,
    "sell_profit_only": false,
    "ignore_roi_if_buy_signal": false
  },
  "exchange": {
    "name": "bittrex",
    "key": "",
    "secret": "",
    "ccxt_config": {
      "enableRateLimit": true
    },
    "ccxt_async_config": {
      "enableRateLimit": true,
      "rateLimit": 500
    },
    "pair_blacklist": [
      "BUSD/USDT",
      "TUSD/USDT",
      "USDC/USDT",
      "PAX/USDT",
      "BKRW/USDT",
      "EUR/USDT",
      "IDRT/USDT",
      "NGN/USDT",
      "RUB/USDT",
      "TRY/USDT",
      "ZAR/USDT"
    ]
  },
  "pairlists": [
    {
        "method": "VolumePairList",
        "number_assets": 200,
        "sort_key": "quoteVolume",
        "refresh_period": 1800
    },
    {"method": "PrecisionFilter"},
    {"method": "PriceFilter", "low_price_ratio": 0.02},
    {"method": "SpreadFilter", "max_spread_ratio": 0.01},
    {"method": "ShuffleFilter", "seed": 42},
    {"method": "AgeFilter", "min_days_listed": 20}

  ],
  "edge": {
    "enabled": false,
    "process_throttle_secs": 3600,
    "calculate_since_number_of_days": 7,
    "allowed_risk": 0.01,
    "stoploss_range_min": -0.01,
    "stoploss_range_max": -0.1,
    "stoploss_range_step": -0.01,
    "minimum_winrate": 0.60,
    "minimum_expectancy": 0.20,
    "min_trade_number": 10,
    "max_trade_duration_minute": 1440,
    "remove_pumps": false
  },
 "telegram": {
   "enabled": true,
   "token": "",
   "chat_id": ""
 },
  "initial_state": "running",
  "forcebuy_enable": false,
  "internals": {
    "process_throttle_secs": 5
  }
}
```

If I'm trying to run this configuration with **Bittrex** as exchanger I'm going to receive the following error.

```
2020-07-21 01:27:44,324 - freqtrade.commands.trade_commands - ERROR - float division by zero
2020-07-21 01:27:44,324 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/vlad/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker = Worker(args)
  File "/home/vlad/freqtrade/freqtrade/worker.py", line 34, in __init__
    self._init(False)
  File "/home/vlad/freqtrade/freqtrade/worker.py", line 51, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/home/vlad/freqtrade/freqtrade/freqtradebot.py", line 87, in __init__
    self.active_pair_whitelist = self._refresh_active_whitelist()
  File "/home/vlad/freqtrade/freqtrade/freqtradebot.py", line 184, in _refresh_active_whitelist
    self.pairlists.refresh_pairlist()
  File "/home/vlad/freqtrade/freqtrade/pairlist/pairlistmanager.py", line 95, in refresh_pairlist
    pairlist = pairlist_handler.filter_pairlist(pairlist, tickers)
  File "/home/vlad/freqtrade/freqtrade/pairlist/IPairList.py", line 131, in filter_pairlist
    if not self._validate_pair(tickers[p]):
  File "/home/vlad/freqtrade/freqtrade/pairlist/PriceFilter.py", line 50, in _validate_pair
    changeperc = compare / ticker['last']
ZeroDivisionError: float division by zero
```

The interesting part is that if I'm running the same configuration but on **Binance** instead of **Bittrex** everything is going to work properly as expected. Just on **Bittrex** so far I'm getting this error message.

**Comment by xmatthias** [comment]
i wonder which pair causes this - it's obviously a pair that didn't have a trade yet...

i assume it's a new pair (most likely with (almost) no volume so far) - and no trade in the last 24h.

maybe try lowering the amount of VolumePairlist - i don't think bittrex has 200 pairs of the same stake currency ...

**Comment by Vildnex** [comment]
I've tried to lower the number of pairs by more than half, and now it stays at 75 where it's working. But I've obtained a new error now.

```
Traceback (most recent call last):
  File "/home/vlad/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker = Worker(args)
  File "/home/vlad/freqtrade/freqtrade/worker.py", line 34, in __init__
    self._init(False)
  File "/home/vlad/freqtrade/freqtrade/worker.py", line 51, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/home/vlad/freqtrade/freqtrade/freqtradebot.py", line 87, in __init__
    self.active_pair_whitelist = self._refresh_active_whitelist()
  File "/home/vlad/freqtrade/freqtrade/freqtradebot.py", line 184, in _refresh_active_whitelist
    self.pairlists.refresh_pairlist()
  File "/home/vlad/freqtrade/freqtrade/pairlist/pairlistmanager.py", line 95, in refresh_pairlist
    pairlist = pairlist_handler.filter_pairlist(pairlist, tickers)
  File "/home/vlad/freqtrade/freqtrade/pairlist/IPairList.py", line 131, in filter_pairlist
    if not self._validate_pair(tickers[p]):
  File "/home/vlad/freqtrade/freqtrade/pairlist/AgeFilter.py", line 60, in _validate_pair
    daily_candles = self._exchange.get_historic_ohlcv(pair=ticker['symbol'],
  File "/home/vlad/freqtrade/freqtrade/exchange/exchange.py", line 653, in get_historic_ohlcv
    return asyncio.get_event_loop().run_until_complete(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/vlad/freqtrade/freqtrade/exchange/exchange.py", line 675, in _async_get_historic_ohlcv
    for p, timeframe, res in results:
TypeError: cannot unpack non-iterable TemporaryError object
```

What's should be the reason for this one?

**Comment by xmatthias** [comment]
I ran into this error first: https://github.com/ccxt/ccxt/issues/7317

Looking at it, it seems like bittrex just changed their API in a breaking way without any grace period.

Personally, these constant issues with Bittrex (in combination with the constant low volume on most pairs) had me give up on bittrex and move to kraken / binance.

**Comment by Vildnex** [comment]
I see... well thx for the help :D , and in this case, I'm going to check Kraken in comparison with Binance.

**Comment by hroff-1902** [comment]
the fix merged to develop branch, @Vildnex pls verify

**Comment by Vildnex** [comment]
For me is not working yet, I've just got the last version from **develop** which is `develop-dbf4d1a6` and I've got the same error:

```
2020-07-22 03:31:16,992 - freqtrade.exchange.common - WARNING - _async_get_candle_history() returned exception: "Could not fetch historical candle (OHLCV) data for pair ADA/USDT due to ExchangeNotAvailable. Message: GET https://api.bittrex.com/v3/markets/ADA-USDT/candles/DAY_1/historical/2020/7/2 400 Bad Request {"code":"INVALID_DATE"}"
2020-07-22 03:31:16,992 - freqtrade.exchange.common - WARNING - Giving up retrying: _async_get_candle_history()
2020-07-22 03:31:16,992 - freqtrade.commands.trade_commands - ERROR - cannot unpack non-iterable TemporaryError object
2020-07-22 03:31:16,993 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/vlad/freqtrade_BITTREX/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker = Worker(args)
  File "/home/vlad/freqtrade_BITTREX/freqtrade/worker.py", line 34, in __init__
    self._init(False)
  File "/home/vlad/freqtrade_BITTREX/freqtrade/worker.py", line 51, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/home/vlad/freqtrade_BITTREX/freqtrade/freqtradebot.py", line 87, in __init__
    self.active_pair_whitelist = self._refresh_active_whitelist()
  File "/home/vlad/freqtrade_BITTREX/freqtrade/freqtradebot.py", line 208, in _refresh_active_whitelist
    self.pairlists.refresh_pairlist()
  File "/home/vlad/freqtrade_BITTREX/freqtrade/pairlist/pairlistmanager.py", line 95, in refresh_pairlist
    pairlist = pairlist_handler.filter_pairlist(pairlist, tickers)
  File "/home/vlad/freqtrade_BITTREX/freqtrade/pairlist/IPairList.py", line 131, in filter_pairlist
    if not self._validate_pair(tickers[p]):
  File "/home/vlad/freqtrade_BITTREX/freqtrade/pairlist/AgeFilter.py", line 68, in _validate_pair
    daily_candles = self._exchange.get_historic_ohlcv(pair=ticker['symbol'],
  File "/home/vlad/freqtrade_BITTREX/freqtrade/exchange/exchange.py", line 667, in get_historic_ohlcv
    return asyncio.get_event_loop().run_until_complete(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/vlad/freqtrade_BITTREX/freqtrade/exchange/exchange.py", line 689, in _async_get_historic_ohlcv
    for p, timeframe, res in results:
TypeError: cannot unpack non-iterable TemporaryError object
```

**Comment by xmatthias** [comment]
The problem you raised the issue for (PriceFilter) is fixed.
Unfortunately, that's a "volatile" error which only happens "from time to time" - as it's related to when the last trade on a pair was made (within 24h or not).

the error you get above is a different one, a fix will be in the ccxt repo (see linked issue above). There is nothing freqtrade can do in this case.

**Comment by Vildnex** [comment]
Well... actually the problem came from AgeFilter after I've disabled that feature everything it's working fine.

**Comment by xmatthias** [comment]
the real problem is that bittrex changed their api in a breaking way.
