### ISSUE TITLE
strategy start for one minute then terminated and telegram status : process died

### ISSUE THREAD

**Issue by buqmisz** [freqtrade/freqtrade#3624]
Have you searched for similar issues before posting it?
yes ,nothing clear to solve my issue

## Describe your environment

  * Operating system: VPS Ubuntu 19.10 x64
  * Python Version: _____ 3.6
  * CCXT version: _____1.31.37
  * Freqtrade Version: ____ freqtrade develop-7e980037
  
## Your question
I try all strategies not working give error below my try for DefaultStrategy 

2020-07-24 20:31:59,606 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy DefaultStrategy from '/root/freqtrade/user_data/strategies/default_strategy.py'...
2020-07-24 20:31:59,607 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 5m.
2020-07-24 20:31:59,607 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: BTC.
2020-07-24 20:31:59,607 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 0.01.
2020-07-24 20:31:59,607 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'buy': 10, 'sell': 30}.
2020-07-24 20:31:59,607 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'use_sell_signal' with value in config file: True.
2020-07-24 20:31:59,607 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'sell_profit_only' with value in config file: False.
2020-07-24 20:31:59,608 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ignore_roi_if_buy_signal' with value in config file: False.
2020-07-24 20:31:59,608 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'40': 0.0, '30': 0.01, '20': 0.02, '0': 0.04}
2020-07-24 20:31:59,608 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 5m
2020-07-24 20:31:59,608 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.1
2020-07-24 20:31:59,608 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2020-07-24 20:31:59,608 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2020-07-24 20:31:59,608 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
2020-07-24 20:31:59,609 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False}
2020-07-24 20:31:59,609 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
2020-07-24 20:31:59,609 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: BTC
2020-07-24 20:31:59,609 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 0.01
2020-07-24 20:31:59,609 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'buy': 10, 'sell': 30}
2020-07-24 20:31:59,609 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_sell_signal: True
2020-07-24 20:31:59,609 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_only: False
2020-07-24 20:31:59,610 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_buy_signal: False
2020-07-24 20:31:59,610 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2020-07-24 20:31:59,610 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2020-07-24 20:31:59,613 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2020-07-24 20:31:59,614 - freqtrade.exchange.exchange - INFO - Using CCXT 1.31.37
2020-07-24 20:31:59,614 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2020-07-24 20:31:59,621 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 200}
2020-07-24 20:31:59,629 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2020-07-24 20:32:00,681 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2020-07-24 20:32:00,717 - freqtrade.wallets - INFO - Wallets synced.
2020-07-24 20:32:00,718 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from '/root/freqtrade/freqtrade/pairlist/StaticPairList.py'...
2020-07-24 20:32:00,718 - freqtrade.pairlist.IPairList - INFO - Ignoring BCN/BTC from whitelist. Market is not active.
2020-07-24 20:32:00,719 - freqtrade.pairlist.IPairList - INFO - Ignoring BSV/BTC from whitelist. Market is not active.
2020-07-24 20:32:00,719 - freqtrade.rpc.rpc_manager - INFO - Enabling rpc.telegram ...
2020-07-24 20:32:01,316 - freqtrade.rpc.telegram - INFO - rpc.telegram is listening for following commands: [['status'], ['profit'], ['balance'], ['start'], ['stop'], ['forcesell'], ['forcebuy'], ['performance'], ['daily'], ['count'], ['reload_config', 'reload_conf'], ['show_config', 'show_conf'], ['stopbuy'], ['whitelist'], ['blacklist'], ['edge'], ['help'], ['version']]
2020-07-24 20:32:01,385 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'running'}
2020-07-24 20:32:01,667 - freqtrade.worker - INFO - Changing state to: RUNNING
2020-07-24 20:32:01,667 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': warning, 'status': 'Dry run is enabled. All trades are simulated.'}
2020-07-24 20:32:01,777 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': custom, 'status': "*Exchange:* `binance`\n*Stake per trade:* `0.01 BTC`\n*Minimum ROI:* `{'40': 0.0, '30': 0.01, '20': 0.02, '0': 0.04}`\n*Stoploss:* `-0.1`\n*Timeframe:* `5m`\n*Strategy:* `DefaultStrategy`"}
2020-07-24 20:32:01,888 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': "Searching for BTC pairs to buy and sell based on [{'StaticPairList': 'StaticPairList'}]"}
2020-07-24 20:32:02,010 - freqtrade.pairlist.IPairList - INFO - Ignoring BCN/BTC from whitelist. Market is not active.
2020-07-24 20:32:02,010 - freqtrade.pairlist.IPairList - INFO - Ignoring BSV/BTC from whitelist. Market is not active.
2020-07-24 20:32:02,011 - freqtrade.commands.trade_commands - ERROR - 'DefaultStrategy' object has no attribute 'informative_pairs'
2020-07-24 20:32:02,011 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/root/freqtrade/freqtrade/commands/trade_commands.py", line 20, in start_trading
    worker.run()
  File "/root/freqtrade/freqtrade/worker.py", line 73, in run
    state = self._worker(old_state=state)
  File "/root/freqtrade/freqtrade/worker.py", line 110, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
  File "/root/freqtrade/freqtrade/worker.py", line 131, in _throttle
    result = func(*args, **kwargs)
  File "/root/freqtrade/freqtrade/worker.py", line 144, in _process_running
    self.freqtrade.process()
  File "/root/freqtrade/freqtrade/freqtradebot.py", line 154, in process
    self.strategy.informative_pairs())
AttributeError: 'DefaultStrategy' object has no attribute 'informative_pairs'
2020-07-24 20:32:02,014 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2020-07-24 20:32:02,014 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2020-07-24 20:32:02,123 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2020-07-24 20:32:02,129 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...

**Comment by hroff-1902** [comment]
we removed any appearances of the DefaultStrategy some time ago, seems you are using an old one, from one of the older versions of the bot.

try to use SampleStrategy instead (and populate the samples into the user_data dir with the actual samples as described here: https://www.freqtrade.io/en/latest/utils/#create-userdir if they are not there)

**Comment by hroff-1902** [comment]
@xmatthias a graceful handling for it should be added...

**Comment by xmatthias** [comment]
@hroff-1902 informative_pairs is available in the strategy interface - so this is properly handled assuming a correct installation, as a strategy eventually implementing this will override the (empty) function definition.
This is tested in `test_is_informative_pairs_callback` - as `TestStrategyLegacy` does not include (does not override) the `informative_pairs` function.

There's only 2 ways i can think of that this error can happen:
* intentionally deleting the `informative_pairs` method from the strategy (in a constructor or so)
* a faulty / broken installation 

Now i don't think the first option is realistic (if you do this intentionally, you wouldn't open an issue for it ...) - and for the 2nd one, it should be possible (untested) by:

* installing an old version via `pip install .` (non-linked install - files are copied to the virtual environment)
* then upgrading (`git pull` / `git checkout develop; git pull` or something similar ... )
* NOT reinstalling freqtrade - but only the dependencies (`pip install -r requirements.txt`)
*  and running freqtrade via `python -m freqtrade` - or `python freqtrade/main.py` 

This will result in the new version of freqtrade beeing used (using the local files, not the installed version).
Strategyloader would (most likely) use the installed version - which includes an outdated `interface.py` file.


@buqmisz i think there is something wrong with your installation.

what is the exact command you're running?
And how did you install this? 

*note*: the above is NOT a instruction on how to do things - but a possible explanation on how the error you're experiencing is possible.

**Comment by buqmisz** [comment]
> @hroff-1902 informative_pairs is available in the strategy interface - so this is properly handled assuming a correct installation, as a strategy eventually implementing this will override the (empty) function definition.
> This is tested in `test_is_informative_pairs_callback` - as `TestStrategyLegacy` does not include (does not override) the `informative_pairs` function.
> 
> There's only 2 ways i can think of that this error can happen:
> 
> * intentionally deleting the `informative_pairs` method from the strategy (in a constructor or so)
> * a faulty / broken installation
> 
> Now i don't think the first option is realistic (if you do this intentionally, you wouldn't open an issue for it ...) - and for the 2nd one, it should be possible (untested) by:
> 
> * installing an old version via `pip install .` (non-linked install - files are copied to the virtual environment)
> * then upgrading (`git pull` / `git checkout develop; git pull` or something similar ... )
> * NOT reinstalling freqtrade - but only the dependencies (`pip install -r requirements.txt`)
> * and running freqtrade via `python -m freqtrade` - or `python freqtrade/main.py`
> 
> This will result in the new version of freqtrade beeing used (using the local files, not the installed version).
> Strategyloader would (most likely) use the installed version - which includes an outdated `interface.py` file.
> 
> @buqmisz i think there is something wrong with your installation.
> 
> what is the exact command you're running?
> And how did you install this?
> 
> _note_: the above is NOT a instruction on how to do things - but a possible explanation (to @hroff-1902 ) on how the error you're experiencing might be possible.

Great help and really I appreciated your support and fast reply with valuable information.

now it is clear that I have bad installation caused me these trouble .
I did installation following the Udemy course by ilyass (Run Your Trading Robot on a VPS or Raspberry Pi 24/7) in part creating virtual machine and install FreqTrade section , I did and follow his step as exact as it unfortunate end to this error .

please if you have clear and easy way to install freqtrade package for normal user (I am not installation expert) , 

please advise me for stable installation form scratch for freqtrade.

best regards,

**Comment by buqmisz** [comment]
> we removed any appearances of the DefaultStrategy some time ago, seems you are using an old one, from one of the older versions of the bot.
> 
> try to use SampleStrategy instead (and populate the user_data dir with the actual samples as described here: https://www.freqtrade.io/en/latest/utils/#create-userdir if they are not there)

thanks @hroff-1902 for your support.
I did it and still got same error ,I try also SampleStrategy strategy .the report I attached is for DefaultStrategy but also I try all strategy unfortunately the bot start and the telegram start takes one minute then status died massage shown and all terminated.

it is clear that I have bad freqtrade installation, so please advise me to the right way to install it from scratch.

**Comment by hroff-1902** [comment]
just follow the installation guide for the actual version of the bot: https://www.freqtrade.io/en/latest/installation/ 

you may rename the directory with the previous old version of the bot or simply install it into a new directory

**Comment by buqmisz** [comment]
> just follow the installation guide for the actual version of the bot: https://www.freqtrade.io/en/latest/installation/
> 
> you may rename the directory with the previous old version of the bot or simply install it into a new directory

thanks alot @hroff-1902  , I will try it , I hope it will work this time 👍

**Comment by xmatthias** [comment]
I'll close this assuming that the solutions proposed above did work for you.

Feel free to comment below if that's not the case, so we can help you further.

**Comment by buqmisz** [comment]
Thanks alot for your kind help and support,

yes It is working now.
