### ISSUE TITLE
ValueError: 'pair' is both an index level and a column label, which is ambiguous

### ISSUE THREAD

**Issue by kennedyshead** [freqtrade/freqtrade#3637]
## Describe your environment

  * Operating system: Ubuntu 20.04
  * Python Version: 3.7.4 (`python -V`)
  * CCXT version: ccxt==1.32.7 (`pip freeze | grep ccxt`)
  * Freqtrade Version: develop-6ca057e2 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*
Things just blow up when I enable edge.

### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
Jul 27 19:27:35 knutas-backend freqtrade[1783272]: 2020-07-27 19:27:35,606 - freqtrade.commands.trade_commands - ERROR - 'pair' is both an index level and a column label, which is ambiguous.
Jul 27 19:27:35 knutas-backend freqtrade[1783272]: 2020-07-27 19:27:35,606 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Jul 27 19:27:35 knutas-backend freqtrade[1783272]: Traceback (most recent call last):
Jul 27 19:27:35 knutas-backend freqtrade[1783272]:   File "/home/knutas/anaconda3/envs/freqtrade/lib/python3.7/site-packages/freqtrade-develop_6ca057e2-py3.7.egg/freqtrade/commands/trade_commands.py", line 19, in start_trading
Jul 27 19:27:35 knutas-backend freqtrade[1783272]:     worker = Worker(args)
Jul 27 19:27:35 knutas-backend freqtrade[1783272]:   File "/home/knutas/anaconda3/envs/freqtrade/lib/python3.7/site-packages/freqtrade-develop_6ca057e2-py3.7.egg/freqtrade/worker.py", line 34, in __init__
Jul 27 19:27:35 knutas-backend freqtrade[1783272]:     self._init(False)
Jul 27 19:27:35 knutas-backend freqtrade[1783272]:   File "/home/knutas/anaconda3/envs/freqtrade/lib/python3.7/site-packages/freqtrade-develop_6ca057e2-py3.7.egg/freqtrade/worker.py", line 51, in _init
Jul 27 19:27:35 knutas-backend freqtrade[1783272]:     self.freqtrade = FreqtradeBot(self._config)
Jul 27 19:27:35 knutas-backend freqtrade[1783272]:   File "/home/knutas/anaconda3/envs/freqtrade/lib/python3.7/site-packages/freqtrade-develop_6ca057e2-py3.7.egg/freqtrade/freqtradebot.py", line 87, in __init__
Jul 27 19:27:35 knutas-backend freqtrade[1783272]:     self.active_pair_whitelist = self._refresh_active_whitelist()
Jul 27 19:27:35 knutas-backend freqtrade[1783272]:   File "/home/knutas/anaconda3/envs/freqtrade/lib/python3.7/site-packages/freqtrade-develop_6ca057e2-py3.7.egg/freqtrade/freqtradebot.py", line 213, in _refresh_active_whitelist
Jul 27 19:27:35 knutas-backend freqtrade[1783272]:     self.edge.calculate()
Jul 27 19:27:35 knutas-backend freqtrade[1783272]:   File "/home/knutas/anaconda3/envs/freqtrade/lib/python3.7/site-packages/freqtrade-develop_6ca057e2-py3.7.egg/freqtrade/edge/edge_positioning.py", line 150, in calculate
Jul 27 19:27:35 knutas-backend freqtrade[1783272]:     self._cached_pairs = self._process_expectancy(trades_df)
Jul 27 19:27:35 knutas-backend freqtrade[1783272]:   File "/home/knutas/anaconda3/envs/freqtrade/lib/python3.7/site-packages/freqtrade-develop_6ca057e2-py3.7.egg/freqtrade/edge/edge_positioning.py", line 307, in _process_expectancy
Jul 27 19:27:35 knutas-backend freqtrade[1783272]:     df = results.groupby(['pair', 'stoploss'])[['profit_abs', 'trade_duration']].agg(
Jul 27 19:27:35 knutas-backend freqtrade[1783272]:   File "/home/knutas/anaconda3/envs/freqtrade/lib/python3.7/site-packages/pandas/core/frame.py", line 5810, in groupby
Jul 27 19:27:35 knutas-backend freqtrade[1783272]:     observed=observed,
Jul 27 19:27:35 knutas-backend freqtrade[1783272]:   File "/home/knutas/anaconda3/envs/freqtrade/lib/python3.7/site-packages/pandas/core/groupby/groupby.py", line 410, in __init__
Jul 27 19:27:35 knutas-backend freqtrade[1783272]:     mutated=self.mutated,
Jul 27 19:27:35 knutas-backend freqtrade[1783272]:   File "/home/knutas/anaconda3/envs/freqtrade/lib/python3.7/site-packages/pandas/core/groupby/grouper.py", line 594, in get_grouper
Jul 27 19:27:35 knutas-backend freqtrade[1783272]:     obj._check_label_or_level_ambiguity(gpr, axis=axis)
Jul 27 19:27:35 knutas-backend freqtrade[1783272]:   File "/home/knutas/anaconda3/envs/freqtrade/lib/python3.7/site-packages/pandas/core/generic.py", line 1647, in _check_label_or_level_ambiguity
Jul 27 19:27:35 knutas-backend freqtrade[1783272]:     raise ValueError(msg)
Jul 27 19:27:35 knutas-backend freqtrade[1783272]: ValueError: 'pair' is both an index level and a column label, which is ambiguous.
  ```

**Comment by xmatthias** [comment]
how does the edge section of your configuration look like?

using the default - i'm unable to recreate this (and honestly, i don't plan on trying every posible constellation if you got a "breaking" configuration right at hand :laughing: ).

**Comment by kennedyshead** [comment]
´´´
  "edge": {
    "enabled": false,
    "process_throttle_secs": 3600,
    "calculate_since_number_of_days": 7,
    "allowed_risk": 0.01,
    "stoploss_range_min": -0.01,
    "stoploss_range_max": -0.1,
    "stoploss_range_step": -0.01,
    "minimum_winrate": 0.60,
    "minimum_expectancy": 0.20,
    "min_trade_number": 10,
    "max_trade_duration_minute": 1440,
    "remove_pumps": true
  },
´´´

**Comment by xmatthias** [comment]
You can work around this by setting remove_bumps to false` "remove_pumps": false`.

I'll work on a fix - it's not complicated - but i suspect something that never worked (this part has not been touched in ages ...).

**Comment by kennedyshead** [comment]
Thanx :)
