### ISSUE TITLE
freqtrade shows open trade, but it is closed by stoploss

### ISSUE THREAD

**Issue by ziegi** [freqtrade/freqtrade#3639]
## Describe your environment

  * Operating system: Ubuntu 16.04.6 LTS
  * Python Version:  3.6.11
  * CCXT version: 1.30.48
  * Freqtrade Version: 2020.6
  
## Describe the problem:

This is happening on binance.
Freqtrade shows an open trade although it has been closed by stoploss on exchange

### Observed Results:

  * What happened?
Trade not marked as closed
  * What did you expect to happen?
Freqtrade should show the trade as closed

### Relevant code exceptions or logs
  (6 hours time offset  exchange to log time)

  * The Exchange shows following actions:

Date | Pair | Type | Side | Average | Price | Executed | Amount | Total | Trigger Conditions | Status |  
2020-07-28 02:50:19 | NXS/BTC | Limit | Buy | 0.00002005 | 0.00002005 | 54 | 54 | 0.00108270 BTC | _ | Filled
2020-07-28 02:53:14 | NXS/BTC | Stop-Limit | Sell | 0 | 0.00001953 | 0 | 54 | 0.00000000 BTC | <= 0.00001972 | Canceled |  
2020-07-28 02:54:28 | NXS/BTC | Stop-Limit | Sell | 0.00001960 | 0.00001960 | 54 | 54 | 0.00105840 BTC | <= 0.00001980 | Filled

  * the logs show:
2020-07-27 20:50:18,493 - freqtrade.freqtradebot - INFO - Buy signal found: about create a new trade with stake_amount: 0.0011 ...
2020-07-27 20:50:18,493 - freqtrade.freqtradebot - INFO - Executing Buy for NXS/BTC
2020-07-27 20:50:18,493 - freqtrade.freqtradebot - INFO - Getting price from order book Ask side.
2020-07-27 20:50:18,952 - freqtrade.freqtradebot - INFO - ...top 1 order book buy rate 0.00002005
2020-07-27 20:50:19,973 - freqtrade.wallets - INFO - Wallets synced.
2020-07-27 20:50:19,977 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': buy, 'exchange': 'Binance', 'pair': 'NXS/BTC', 'limi
t': 2.005e-05, 'order_type': 'limit', 'stake_amount': 0.0011, 'stake_currency': 'BTC', 'fiat_currency': 'EUR', 'amount': 54.862842892768086, 'o
pen_date': datetime.datetime(2020, 7, 28, 0, 50, 19, 459884), 'current_rate': 2.005e-05}
2020-07-27 20:50:20,468 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=9, pair=NXS/BTC, amount=54.86284289, open_rate=0.000020
05, open_since=2020-07-28 00:50:19)
.......
2020-07-27 20:53:11,880 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=9, pair=NXS/BTC, amount=54.86284289, open_rate=0.00002005, open_since=2020-07-28 00:50:19)
2020-07-27 20:53:13,875 - freqtrade.persistence - INFO - Updating trade (id=9) ...
2020-07-27 20:53:13,875 - freqtrade.persistence - INFO - LIMIT_BUY has been fulfilled for Trade(id=9, pair=NXS/BTC, amount=54.00000000, open_rate=0.00002005, open_since=2020-07-28 00:50:19).
2020-07-27 20:53:14,198 - freqtrade.exchange.binance - INFO - stoploss limit order added for NXS/BTC. stop price: 1.972e-05. limit: 1.953e-05
2020-07-27 20:53:39,772 - freqtrade.worker - INFO - Bot heartbeat. PID=16220, version='2020.6', state='RUNNING'
2020-07-27 20:54:27,825 - freqtrade.freqtradebot - INFO - Trailing stoploss: cancelling current stoploss on exchange (id:{32046216}) in order to add another one ...
2020-07-27 20:54:28,827 - freqtrade.exchange.binance - INFO - stoploss limit order added for NXS/BTC. stop price: 1.98e-05. limit: 1.96e-05
2020-07-27 20:54:32,831 - freqtrade.freqtradebot - WARNING - Unable to fetch stoploss order: Tried to get an invalid order (id: 32046295). Message: binance {"code":-2013,"msg":"Order does not exist."}
2020-07-27 20:54:33,329 - freqtrade.freqtradebot - ERROR - Unable to place a stoploss order on exchange.
Traceback (most recent call last):
  File "/home/ziegi/freqtrade/.env/lib/python3.6/site-packages/ccxt/base/exchange.py", line 581, in fetch
    response.raise_for_status()
  File "/home/ziegi/freqtrade/.env/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/ziegi/freqtrade/freqtrade/exchange/binance.py", line 75, in stoploss
    amount=amount, price=rate, params=params)
  File "/home/ziegi/freqtrade/.env/lib/python3.6/site-packages/ccxt/binance.py", line 1258, in create_order
    response = getattr(self, method)(self.extend(request, params))
  File "/home/ziegi/freqtrade/.env/lib/python3.6/site-packages/ccxt/base/exchange.py", line 463, in inner
    return entry(_self, **inner_kwargs)
  File "/home/ziegi/freqtrade/.env/lib/python3.6/site-packages/ccxt/binance.py", line 1989, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/home/ziegi/freqtrade/.env/lib/python3.6/site-packages/ccxt/base/exchange.py", line 482, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ziegi/freqtrade/.env/lib/python3.6/site-packages/ccxt/base/exchange.py", line 593, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/ziegi/freqtrade/.env/lib/python3.6/site-packages/ccxt/binance.py", line 1970, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions, message, self.id + ' ' + message)
  File "/home/ziegi/freqtrade/.env/lib/python3.6/site-packages/ccxt/base/exchange.py", line 500, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.InsufficientFunds: binance Account has insufficient balance for requested action.
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ziegi/freqtrade/freqtrade/freqtradebot.py", line 749, in create_stoploss_order
    order_types=self.strategy.order_types)
  File "/home/ziegi/freqtrade/freqtrade/exchange/binance.py", line 83, in stoploss
    f'Message: {e}') from e
freqtrade.exceptions.DependencyException: Insufficient funds to create stop_loss_limit sell order on market NXS/BTC.Tried to sell amount 54.0 at rate 1.953e-05. Message: binance Account has insufficient balance for requested action.
2020-07-27 20:54:37,828 - freqtrade.freqtradebot - ERROR - Unable to place a stoploss order on exchange.
Traceback (most recent call last):
  File "/home/ziegi/freqtrade/.env/lib/python3.6/site-packages/ccxt/base/exchange.py", line 581, in fetch
    response.raise_for_status()
  File "/home/ziegi/freqtrade/.env/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ziegi/freqtrade/freqtrade/exchange/binance.py", line 75, in stoploss
    amount=amount, price=rate, params=params)
  File "/home/ziegi/freqtrade/.env/lib/python3.6/site-packages/ccxt/binance.py", line 1258, in create_order
    response = getattr(self, method)(self.extend(request, params))
  File "/home/ziegi/freqtrade/.env/lib/python3.6/site-packages/ccxt/base/exchange.py", line 463, in inner
    return entry(_self, **inner_kwargs)
  File "/home/ziegi/freqtrade/.env/lib/python3.6/site-packages/ccxt/binance.py", line 1989, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/home/ziegi/freqtrade/.env/lib/python3.6/site-packages/ccxt/base/exchange.py", line 482, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ziegi/freqtrade/.env/lib/python3.6/site-packages/ccxt/base/exchange.py", line 593, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/ziegi/freqtrade/.env/lib/python3.6/site-packages/ccxt/binance.py", line 1970, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions, message, self.id + ' ' + message)
  File "/home/ziegi/freqtrade/.env/lib/python3.6/site-packages/ccxt/base/exchange.py", line 500, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.InsufficientFunds: binance Account has insufficient balance for requested action.

The above exception was the direct cause of the following exception:

.... this goes on forever ....

**Comment by xmatthias** [comment]
well - it's a limitation / bug in the binance api.
it is already fixed in the develop branch (#3531).

We'll do a release shortly, so it will be in the stable branch as well.

**Comment by ziegi** [comment]
Thank you very much
great software and great support

**Comment by ziegi** [comment]
If this is due to #3499 (comment)
this should happen only while the order is not persistet yet on binance
But the bot tried access the order for hours according to my logs ....

**Comment by xmatthias** [comment]
yes it is.

The problem is  - since binance fails to give us back the correct order and claims that "order does not exist" - freqtrade will assume that the order has not been placed correctly and will "forget" that order - therefore tries to recreate it which fails.

Thew PR adds a backoff that waits ~20s before doing a last try. If binance fails to persist the order within 20 seconds - then it's something that should be raised with binance - as that suggests severe performance problems at their end.
We can't have freqtrade wait for this for hours - as this would block the bot completely.

**Comment by ziegi** [comment]
Fixed by using develop branch
