### ISSUE TITLE
Informative Pair in Live Mode

### ISSUE THREAD

**Issue by Prossi79** [freqtrade/freqtrade#3661]
## Describe your environment

  * Operating system: Ubuntu 18.04
  * Python Version: 3.7.3
  * CCXT version: CCXT 1.32.7
  * Freqtrade Version: freqtrade develop-f3af02c0
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

Informative Pair not working, stake currency ETH set in the config

strategy code snippets and log below

### Steps to reproduce:

The relevant strategy file code snippets:

```
    def informative_pairs(self):
        """
        Define additional, informative pair/interval combinations to be cached from the exchange.
        These pair/interval combinations are non-tradeable, unless they are part
        of the whitelist as well.
        For more information, please consult the documentation
        :return: List of tuples in the format (pair, interval)
            Sample: return [("ETH/USDT", "5m"),
                            ("BTC/USDT", "15m"),
                            ]
        """
        return [(f"{self.config['stake_currency']}/USDT", "1d")]

```

```
        if self.dp:
        
            # Get ohlcv data for informative pair.
            data = self.dp.get_pair_dataframe(pair=f"{self.stake_currency}/USDT", timeframe=self.ticker_interval)

            # Indicators applied on informative pair
                   

            # Combine the 2 dataframes using 'close'.
            # This will result in a column named 'closeETH' or 'closeBTC' - depending on stake_currency.
            dataframe = dataframe.merge(data[["date", "close"]], on="date", how="left", suffixes=("", self.config['stake_currency']))

            
            # Calculation of SMA via Rolling Mean Method
            dataframe[f"sma{self.config['stake_currency']}100"] = dataframe[f'close{self.stake_currency}'].rolling(100).mean()
            dataframe[f"sma{self.config['stake_currency']}10"] = dataframe[f'close{self.stake_currency}'].rolling(10).mean()
            
 
        return dataframe


```

```
    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
 
                (dataframe[f'sma{self.stake_currency}10'] < dataframe[f'sma{self.stake_currency}100']) &
 
                (dataframe['volume'] > 0) 

            ),
            'buy'] = 1
```

  
### Observed Results:

 backtests with same code are working alright

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
KeyError: "None of [Index(['date', 'close'], dtype='object')] are in the [columns]"
2020-08-06 13:18:43,879 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair FUN/ETH: "None of [Index(['date', 'close'], dtype='object')] are in the [columns]"
2020-08-06 13:18:43,899 - freqtrade.data.dataprovider - WARNING - No data found for (ETH/USDT, 15m).
2020-08-06 13:18:43,905 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error "None of [Index(['date', 'close'], dtype='object')] are in the [columns]" calling <bound method IStrategy._analyze_ticker_internal of <BinHV45_ETH.BinHV45_ETH object at 0x7fe26c7049b0>>
Traceback (most recent call last):
  File "/root/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 16, in wrapper
    return f(*args, **kwargs)
  File "/root/freqtrade/freqtrade/strategy/interface.py", line 334, in _analyze_ticker_internal
    dataframe = self.analyze_ticker(dataframe, metadata)
  File "/root/freqtrade/freqtrade/strategy/interface.py", line 313, in analyze_ticker
    dataframe = self.advise_indicators(dataframe, metadata)
  File "/root/freqtrade/freqtrade/strategy/interface.py", line 609, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/root/freqtrade/user_data/strategies/BinHV45_ETH.py", line 103, in populate_indicators
    dataframe = dataframe.merge(data[["date", "close"]], on="date", how="left", suffixes=("", self.config['stake_currency']))
  File "/root/freqtrade/.env/lib/python3.7/site-packages/pandas/core/frame.py", line 2806, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]
  File "/root/freqtrade/.env/lib/python3.7/site-packages/pandas/core/indexing.py", line 1553, in _get_listlike_indexer
    keyarr, indexer, o._get_axis_number(axis), raise_missing=raise_missing
  File "/root/freqtrade/.env/lib/python3.7/site-packages/pandas/core/indexing.py", line 1640, in _validate_read_indexer
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['date', 'close'], dtype='object')] are in the [columns]"
2020-08-06 13:18:43,906 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair ONT/ETH: "None of [Index(['date', 'close'], dtype='object')] are in the [columns]"
2020-08-06 13:18:43,924 - freqtrade.data.dataprovider - WARNING - No data found for (ETH/USDT, 15m).
2020-08-06 13:18:43,926 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error "None of [Index(['date', 'close'], dtype='object')] are in the [columns]" calling <bound method IStrategy._analyze_ticker_internal of <BinHV45_ETH.BinHV45_ETH object at 0x7fe26c7049b0>>
Traceback (most recent call last):
  File "/root/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 16, in wrapper
    return f(*args, **kwargs)
  File "/root/freqtrade/freqtrade/strategy/interface.py", line 334, in _analyze_ticker_internal
    dataframe = self.analyze_ticker(dataframe, metadata)
  File "/root/freqtrade/freqtrade/strategy/interface.py", line 313, in analyze_ticker
    dataframe = self.advise_indicators(dataframe, metadata)
  File "/root/freqtrade/freqtrade/strategy/interface.py", line 609, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/root/freqtrade/user_data/strategies/BinHV45_ETH.py", line 103, in populate_indicators
    dataframe = dataframe.merge(data[["date", "close"]], on="date", how="left", suffixes=("", self.config['stake_currency']))
  File "/root/freqtrade/.env/lib/python3.7/site-packages/pandas/core/frame.py", line 2806, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]
  File "/root/freqtrade/.env/lib/python3.7/site-packages/pandas/core/indexing.py", line 1553, in _get_listlike_indexer
    keyarr, indexer, o._get_axis_number(axis), raise_missing=raise_missing
  File "/root/freqtrade/.env/lib/python3.7/site-packages/pandas/core/indexing.py", line 1640, in _validate_read_indexer
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['date', 'close'], dtype='object')] are in the [columns]"
2020-08-06 13:18:43,927 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair QTUM/ETH: "None of [Index(['date', 'close'], dtype='object')] are in the [columns]"
2020-08-06 13:18:43,938 - freqtrade.data.dataprovider - WARNING - No data found for (ETH/USDT, 15m).
2020-08-06 13:18:43,940 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error "None of [Index(['date', 'close'], dtype='object')] are in the [columns]" calling <bound method IStrategy._analyze_ticker_internal of <BinHV45_ETH.BinHV45_ETH object at 0x7fe26c7049b0>>
Traceback (most recent call last):
  File "/root/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 16, in wrapper
    return f(*args, **kwargs)
  File "/root/freqtrade/freqtrade/strategy/interface.py", line 334, in _analyze_ticker_internal
    dataframe = self.analyze_ticker(dataframe, metadata)
  File "/root/freqtrade/freqtrade/strategy/interface.py", line 313, in analyze_ticker
    dataframe = self.advise_indicators(dataframe, metadata)
  File "/root/freqtrade/freqtrade/strategy/interface.py", line 609, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/root/freqtrade/user_data/strategies/BinHV45_ETH.py", line 103, in populate_indicators
    dataframe = dataframe.merge(data[["date", "close"]], on="date", how="left", suffixes=("", self.config['stake_currency']))
  File "/root/freqtrade/.env/lib/python3.7/site-packages/pandas/core/frame.py", line 2806, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]
  File "/root/freqtrade/.env/lib/python3.7/site-packages/pandas/core/indexing.py", line 1553, in _get_listlike_indexer
    keyarr, indexer, o._get_axis_number(axis), raise_missing=raise_missing
  File "/root/freqtrade/.env/lib/python3.7/site-packages/pandas/core/indexing.py", line 1640, in _validate_read_indexer
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['date', 'close'], dtype='object')] are in the [columns]"
2020-08-06 13:18:43,941 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair SC/ETH: "None of [Index(['date', 'close'], dtype='object')] are in the [columns]"
2020-08-06 13:18:43,946 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair SC/ETH
2020-08-06 13:18:44,710 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair LINK/ETH

  ```

**Comment by xmatthias** [comment]
It's not a bug - but a usage error...

You're asking the bot for informative pair of 1d (`return [(f"{self.config['stake_currency']}/USDT", "1d")]`).

You're however not loading this data - but instead you're loading data from ticker_interval (`self.dp.get_pair_dataframe(pair=f"{self.stake_currency}/USDT", timeframe=self.ticker_interval)`) - which appears to be 15m in the above case

You got 2 ways to fix this, depending what you need.

either, ask for the USDT pair of ticker_interval (change is then in `informative_pairs()`) - or change the `get_pair_dataframe` method to correspond to the informative pair you're using.

The reason this is working in backtesting is because you have ETH/USDT data for 15m saved ... but that's not available in live mode (as that does not use the stored data - but the real time data).

**Comment by Prossi79** [comment]
ah okay I see - I want the 1d ETH/USDT data as informative apir -> I need to change like this ?

```
        if self.dp:
        
            # Get ohlcv data for informative pair.
            data = self.dp.get_pair_dataframe(pair=f"{self.stake_currency}/USDT", timeframe="1d")

```

others remain the same?

**Comment by xmatthias** [comment]
i think the rest should remain the same - but it's not a full strategy so best try ... ? ;)

also note that you did NOT backtest it with daily timeframe (as you intended) - but with 15m candles of stake/USDT ... :)

**Comment by Prossi79** [comment]
I was confused about the informative_pairs function, as it defines "1d" ... but yeah, it doesnt load the data - my fault

**Comment by Prossi79** [comment]
alright - its working now! :) thank you and highly appreciated
