### ISSUE TITLE
Facing TypeError while doing a dry run with default parameters, please assist 

### ISSUE THREAD

**Issue by chugh-ak5** [freqtrade/freqtrade#3674]
Says Invalid Parameter Value for nbdevup (expected float, got int), unable to proceed 

![image](https://user-images.githubusercontent.com/57716226/89955969-7c4c3280-dc34-11ea-821d-1dcd02806850.png)

**Comment by kiandp** [comment]
hi.please try to copy and paste the error.
the screen shot is blurry and hard to read
.

**Comment by chugh-ak5** [comment]
`(.env) ch_ak@rudebox:~/freqtrade$ python3 ./freqtrade/main.py -c config.json
2020-08-12 00:37:39,608 - freqtrade.configuration - INFO - Verbosity set to 0
2020-08-12 00:37:39,609 - freqtrade.configuration - INFO - Dry run is enabled
2020-08-12 00:37:39,609 - freqtrade.configuration - INFO - Using DB: "sqlite://"
2020-08-12 00:37:39,609 - freqtrade.configuration - INFO - Using max_open_trades: 3 ...
2020-08-12 00:37:39,609 - freqtrade.configuration - INFO - Using data folder: user_data/data/binance ...
2020-08-12 00:37:39,610 - freqtrade.freqtradebot - INFO - Starting freqtrade 0.17.3
2020-08-12 00:37:39,611 - freqtrade.resolvers.strategy_resolver - INFO - Using resolved strategy DefaultStrategy from '/home/ch_ak/freqtrade/freqtrade/strategy'
2020-08-12 00:37:39,612 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ticker_interval' with value in config file: 5m.
2020-08-12 00:37:39,612 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'trailing_stop' with value in config file: False.
2020-08-12 00:37:39,612 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'40': 0.0, '30': 0.01, '20': 0.02, '0': 0.04}
2020-08-12 00:37:39,612 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ticker_interval: 5m
2020-08-12 00:37:39,612 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.1
2020-08-12 00:37:39,612 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2020-08-12 00:37:39,612 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
2020-08-12 00:37:39,612 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False}
2020-08-12 00:37:39,612 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
2020-08-12 00:37:39,613 - freqtrade.rpc.rpc_manager - INFO - Enabling rpc.telegram ...
2020-08-12 00:37:39,704 - freqtrade.rpc.telegram - INFO - rpc.telegram is listening for following commands: [['status'], ['profit'], ['balance'], ['start'], ['stop'], ['forcesell'], ['forcebuy'], ['performance'], ['daily'], ['count'], ['reload_conf'], ['whitelist'], ['help'], ['version']]
2020-08-12 00:37:39,990 - freqtrade.rpc.fiat_convert - ERROR - Could not load FIAT Cryptocurrency map for the following problem: TypeError
2020-08-12 00:37:39,993 - freqtrade.exchange - INFO - Instance is running with dry_run enabled
2020-08-12 00:37:39,994 - freqtrade.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2020-08-12 00:37:40,021 - freqtrade.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': False}
2020-08-12 00:37:40,074 - freqtrade.exchange - INFO - Using Exchange "Binance"
2020-08-12 00:37:42,029 - freqtrade.wallets - INFO - Wallets synced ...
2020-08-12 00:37:42,030 - freqtrade.resolvers.pairlist_resolver - WARNING - Path "user_data/pairlist" does not exist
2020-08-12 00:37:42,031 - freqtrade.resolvers.pairlist_resolver - INFO - Using resolved pairlist StaticPairList from '/home/ch_ak/freqtrade/freqtrade/pairlist'
2020-08-12 00:37:42,044 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'running'}
2020-08-12 00:37:42,244 - freqtrade.freqtradebot - INFO - Changing state to: RUNNING
2020-08-12 00:37:42,244 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': warning, 'status': 'Dry run is enabled. All trades are simulated.'}
2020-08-12 00:37:42,319 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': custom, 'status': "*Exchange:* `binance`\n*Stake per trade:* `0.05 BTC`\n*Minimum ROI:* `{'40': 0.0, '30': 0.01, '20': 0.02, '0': 0.04}`\n*Ticker Interval:* `5m`\n*Strategy:* `DefaultStrategy`"}
2020-08-12 00:37:42,397 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': "Searching for BTC pairs to buy and sell based on StaticPairList: ['ETH/BTC', 'LTC/BTC', 'ETC/BTC', 'DASH/BTC', 'ZEC/BTC', 'XLM/BTC', 'POWR/BTC', 'ADA/BTC', 'XMR/BTC']"}
2020-08-12 00:37:44,600 - freqtrade.strategy.interface - ERROR - Unexpected error when analyzing ticker for pair ETH/BTC: Invalid parameter value for nbdevup (expected float, got int)
Traceback (most recent call last):
  File "/home/ch_ak/freqtrade/freqtrade/strategy/interface.py", line 179, in get_signal
    dataframe = self.analyze_ticker(dataframe, {'pair': pair})
  File "/home/ch_ak/freqtrade/freqtrade/strategy/interface.py", line 150, in analyze_ticker
    dataframe = self.advise_indicators(dataframe, metadata)
  File "/home/ch_ak/freqtrade/freqtrade/strategy/interface.py", line 356, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/home/ch_ak/freqtrade/freqtrade/strategy/default_strategy.py", line 123, in populate_indicators
    dataframe['blower'] = ta.BBANDS(dataframe, nbdevup=2, nbdevdn=2)['lowerband']
  File "talib/_abstract.pxi", line 398, in talib._ta_lib.Function.__call__
  File "talib/_abstract.pxi", line 261, in talib._ta_lib.Function.set_function_args
  File "talib/_abstract.pxi", line 462, in talib._ta_lib.Function.__check_opt_input_value
TypeError: Invalid parameter value for nbdevup (expected float, got int)
2020-08-12 00:37:44,615 - freqtrade.strategy.interface - ERROR - Unexpected error when analyzing ticker for pair LTC/BTC: Invalid parameter value for nbdevup (expected float, got int)
Traceback (most recent call last):
`

**Comment by xmatthias** [comment]
First of all, the version you're using is from early 2019. In general, we do not provide support for old / outdated versions.


The error seems to be in the following line, where ta-lib seems to expect a float, not an integer.
Now i've never seen BBANDS with these parameters, so best check the ta-lib documentation or ask for support there - as this error is not really related to freqtrade (it would also occur outside of freqtrade, when using BBANDS with these parameters.

```
dataframe['blower'] = ta.BBANDS(dataframe, nbdevup=2, nbdevdn=2)['lowerband']
```

**Comment by xmatthias** [comment]
Going to close this as the answer in the ta-lib repository explains the problem quite well.

**Comment by chugh-ak5** [comment]
Thanks @xmatthias got this resolved !
