### ISSUE TITLE
optimization error after some iritations.

### ISSUE THREAD

**Issue by kiandp** [freqtrade/freqtrade#3675]
Hi. i am trying to optimize the strategy with 300 iterations,every things is good but after some iterations gives me this error on numpy.
please help as i am struggling hard for fixing this issue.
python3 ./freqtrade/main.py -c config.json --customhyperopt RB hyperopt -e 300
2020-08-11 15:51:23,358 - freqtrade.configuration - INFO - Verbosity set to 0
2020-08-11 15:51:23,362 - freqtrade.configuration - INFO - Dry run is enabled
2020-08-11 15:51:23,362 - freqtrade.configuration - INFO - Using DB: "sqlite://"
2020-08-11 15:51:23,362 - freqtrade.configuration - INFO - Using max_open_trades: 15 ...
2020-08-11 15:51:23,363 - freqtrade.configuration - INFO - Using data folder: user_data/data/binance ...
2020-08-11 15:51:23,368 - freqtrade.configuration - INFO - Parameter --epochs detected ...
2020-08-11 15:51:23,368 - freqtrade.configuration - INFO - Will run Hyperopt with for 300 epochs ...
2020-08-11 15:51:23,369 - freqtrade.configuration - INFO - Parameter -s/--spaces detected: all
2020-08-11 15:51:23,372 - freqtrade.resolvers.strategy_resolver - INFO - Using resolved strategy DefaultStrategy from '/home/dp/freqtrade/freqtrade/strategy'
2020-08-11 15:51:23,373 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ticker_interval' with value in config file: 1h.
2020-08-11 15:51:23,378 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'trailing_stop' with value in config file: False.
2020-08-11 15:51:23,379 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'40': 0.0, '30': 0.01, '20': 0.02, '0': 0.04}
2020-08-11 15:51:23,382 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ticker_interval: 1h
2020-08-11 15:51:23,382 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.1
2020-08-11 15:51:23,382 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2020-08-11 15:51:23,382 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
2020-08-11 15:51:23,382 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False}
2020-08-11 15:51:23,382 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
2020-08-11 15:51:23,383 - freqtrade.exchange - INFO - Instance is running with dry_run enabled
2020-08-11 15:51:23,383 - freqtrade.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2020-08-11 15:51:23,385 - freqtrade.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': False}
2020-08-11 15:51:23,406 - freqtrade.exchange - INFO - Using Exchange "Binance"
2020-08-11 15:51:24,456 - freqtrade.resolvers.hyperopt_resolver - INFO - Using resolved hyperopt RB from '/home/dp/freqtrade/freqtrade/optimize'
2020-08-11 15:51:25,424 - freqtrade.optimize.hyperopt - INFO - Found 1 CPU cores. Let's make them scream!
-0.18682808620689656 0.02062704384432781 173.0420317216447
.-0.34455256827586206 0.02910918890352942 226.1371004168391
.-0.009902034137931035 0.017422837260232256 10.858053355659802

    2/300:     99 trades. Avg profit -0.24%. Total profit -0.00237899 BTC (-23.7659Σ%). Avg duration 405.5 mins.. Loss 10.85805
-0.0009024534482758621 0.0038763430754115867 4.447838745220796

    3/300:      9 trades. Avg profit -0.24%. Total profit -0.00021692 BTC (-2.1671Σ%). Avg duration 593.3 mins.. Loss 4.44784
-0.0023348737931034487 0.011348914371017869 3.930569896368297

    4/300:     14 trades. Avg profit -0.43%. Total profit -0.00060772 BTC (-6.0711Σ%). Avg duration 411.4 mins.. Loss 3.93057
-0.2771696389655172 0.025804375924400366 205.21009819217204
.-0.1398666727586207 0.011225844851035331 238.03545002847235
.-0.13986273206896555 0.01322689953098693 202.0181477931341
.-0.011371207241379314 0.013709261912135541 15.846703542545226
..-0.0009024534482758621 0.0038763430754115867 4.447838745220796
.-0.00043831551724137944 0.010228073497994516 0.8187276128319131

   11/300:      9 trades. Avg profit -0.09%. Total profit -0.00008219 BTC (-0.8211Σ%). Avg duration 286.7 mins.. Loss 0.81873
-0.27786583793103453 0.020243565390615992 262.23737159735253
.-0.028985327586206897 0.010130979841310098 54.660448906609176
.-0.34847376482758624 0.014289971760287684 465.8918884335809
.-0.11813271689655175 0.01483556711260555 152.12916164335962
.-0.011739459655172417 0.024861259820555467 9.021347406146267
.-0.25787638724137935 0.020976394332837312 234.8697961346994
..-0.09333581310344828 0.015069968911723061 118.32660146885702
.-0.11392810517241381 0.023576190709508456 92.32167401274117
.-0.00015517241379310346 0.0 -1.0

   21/300:      9 trades. Avg profit  0.00%. Total profit  0.00000000 BTC (0.0000Σ%). Avg duration 1553.3 mins.. Loss -1.00000
-0.09789557724137932 0.014150452908610486 132.17190920898864
.-0.0007402737931034483 0.00348938446124496 4.053124875214366
.-0.35374339793103454 0.02552874955390188 264.73126362395936
.-0.32324343965517244 0.02346057727386338 263.2312569025737
..-0.0796793827586207 0.01637125243451249 92.98448461758798
.-0.3346132134482759 0.019085847671604886 334.94852189812747
.Traceback (most recent call last):
  File "./freqtrade/main.py", line 89, in <module>
    main(sys.argv[1:])
  File "./freqtrade/main.py", line 35, in main
    args.func(args)
  File "/home/dp/freqtrade/freqtrade/optimize/hyperopt.py", line 354, in start
    hyperopt.start()
  File "/home/dp/freqtrade/freqtrade/optimize/hyperopt.py", line 307, in start
    asked = opt.ask(n_points=cpus)
  File "/home/dp/freqtrade/.env/lib/python3.6/site-packages/skopt/optimizer/optimizer.py", line 372, in ask
    opt._tell(x, y_lie)
  File "/home/dp/freqtrade/.env/lib/python3.6/site-packages/skopt/optimizer/optimizer.py", line 535, in _tell
    transformed_bounds[:, 1])
  File "/home/dp/freqtrade/.env/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 1818, in clip
    return _wrapfunc(a, 'clip', a_min, a_max, out=out)
  File "/home/dp/freqtrade/.env/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 51, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: operands could not be broadcast together with shapes (17,) (18,) 
(.env) dp@dp-VirtualBox:~/freqtrade$ python3 ./freqtrade/main.py -c config.json --customhyperopt RB hyperopt -e 300
2020-08-11 16:07:07,977 - freqtrade.configuration - INFO - Verbosity set to 0
2020-08-11 16:07:07,981 - freqtrade.configuration - INFO - Dry run is enabled
2020-08-11 16:07:07,981 - freqtrade.configuration - INFO - Using DB: "sqlite://"
2020-08-11 16:07:07,981 - freqtrade.configuration - INFO - Using max_open_trades: 15 ...
2020-08-11 16:07:07,982 - freqtrade.configuration - INFO - Using data folder: user_data/data/binance ...
2020-08-11 16:07:07,986 - freqtrade.configuration - INFO - Parameter --epochs detected ...
2020-08-11 16:07:07,986 - freqtrade.configuration - INFO - Will run Hyperopt with for 300 epochs ...
2020-08-11 16:07:07,986 - freqtrade.configuration - INFO - Parameter -s/--spaces detected: all
2020-08-11 16:07:07,996 - freqtrade.resolvers.strategy_resolver - INFO - Using resolved strategy DefaultStrategy from '/home/dp/freqtrade/freqtrade/strategy'
2020-08-11 16:07:08,013 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ticker_interval' with value in config file: 1h.
2020-08-11 16:07:08,018 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'trailing_stop' with value in config file: False.
2020-08-11 16:07:08,018 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'40': 0.0, '30': 0.01, '20': 0.02, '0': 0.04}
2020-08-11 16:07:08,018 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ticker_interval: 1h
2020-08-11 16:07:08,019 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.1
2020-08-11 16:07:08,020 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2020-08-11 16:07:08,020 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
2020-08-11 16:07:08,020 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False}
2020-08-11 16:07:08,020 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
2020-08-11 16:07:08,021 - freqtrade.exchange - INFO - Instance is running with dry_run enabled
2020-08-11 16:07:08,021 - freqtrade.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2020-08-11 16:07:08,027 - freqtrade.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': False}
2020-08-11 16:07:08,065 - freqtrade.exchange - INFO - Using Exchange "Binance"
2020-08-11 16:07:09,521 - freqtrade.resolvers.hyperopt_resolver - INFO - Using resolved hyperopt RB from '/home/dp/freqtrade/freqtrade/optimize'
2020-08-11 16:07:10,764 - freqtrade.optimize.hyperopt - INFO - Found 1 CPU cores. Let's make them scream!
-0.010882704827586206 0.021457295339210813 9.689654754276633

    0/300:     99 trades. Avg profit -0.27%. Total profit -0.00266364 BTC (-26.6098Σ%). Avg duration 471.5 mins.. Loss 9.68965
-0.1984363837931035 0.020163615887365125 188.01795324796407
.-0.007700891379310346 0.012137644564290248 12.121406459260184
.-0.10980890000000003 0.012301841193060319 170.53513014047954
.-0.15531710689655173 0.02289688110398565 129.59534302205446
.-0.20294305655172415 0.020729121332072963 187.04225756937475
.-0.27693621965517246 0.025995201641400966 203.53214106810137
.0.0004936627586206897 0.0059133674481324176 -1.5949311189342272

    7/300:      9 trades. Avg profit  0.21%. Total profit  0.00018835 BTC (1.8816Σ%). Avg duration 1573.3 mins.. Loss -1.59493
-0.0008852120689655173 0.004011102722983224 4.216285146342404
.-0.0009024534482758621 0.0038763430754115867 4.447838745220796
.-0.00010089758620689666 0.010187230226952554 0.1892217643966532
.-0.013921300000000001 0.00989416909536496 26.881091326744922
.-0.32909957758620695 0.009655083071451189 651.2050238209736
.-0.0009024534482758621 0.0038763430754115867 4.447838745220796
.-0.0008852120689655173 0.004011102722983224 4.216285146342404
.-0.27254580413793106 0.03059237041626262 170.20519188409756
.-0.3056559565517242 0.01922275355384124 303.78316166848043
.-0.008477189655172414 0.012534689500260203 12.920661573166107
.-0.0003953393103448277 0.010582226134849831 0.7137389451645247
.-0.18759507172413795 0.020628201706627654 173.7426686018191
.-0.21530476448275862 0.008373070488548072 491.2644358387146
.-0.09984393379310347 0.025006603961854213 76.28047693592652
.-0.27235551448275863 0.022847180896661656 227.74559459509507
.-0.21594001586206896 0.02571131685780554 160.45573368221824
.-0.00015517241379310346 0.0 -1.0
.-0.0007335275862068966 0.0 -1.0
.-0.014726991379310347 0.012273341085473094 22.92438328602043
..-0.011350297586206896 0.020428148661986265 10.615114198335593
.Traceback (most recent call last):
  File "./freqtrade/main.py", line 89, in <module>
    main(sys.argv[1:])
  File "./freqtrade/main.py", line 35, in main
    args.func(args)
  File "/home/dp/freqtrade/freqtrade/optimize/hyperopt.py", line 354, in start
    hyperopt.start()
  File "/home/dp/freqtrade/freqtrade/optimize/hyperopt.py", line 307, in start
    asked = opt.ask(n_points=cpus)
  File "/home/dp/freqtrade/.env/lib/python3.6/site-packages/skopt/optimizer/optimizer.py", line 372, in ask
    opt._tell(x, y_lie)
  File "/home/dp/freqtrade/.env/lib/python3.6/site-packages/skopt/optimizer/optimizer.py", line 535, in _tell
    transformed_bounds[:, 1])
  File "/home/dp/freqtrade/.env/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 1818, in clip
    return _wrapfunc(a, 'clip', a_min, a_max, out=out)
  File "/home/dp/freqtrade/.env/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 51, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: operands could not be broadcast together with shapes (17,) (18,)

**Comment by xmatthias** [comment]
Well first of all, i think you're using an old version (not supplying a strategy to hyperopt is not supported since more than a year). 
We do not provide support for outdated versions - so please update to a recent version of freqtrade.

Since your version is THAT old - you'll most likely also have to update some parts of hyperopt / strategy code - which may solve your problem already.


Either way - as shown in #3080 and #2623, this is caused by invalid comparisons (basically on indicators that don't really exist).
Best isolate the problem by using hyperopt against single spaces (buy, then sell) - that should help you look only at the lines that are relevant.

**Comment by kiandp** [comment]
Dear xmatthias,thanks for your help.
can u please tell me how i can update the bot and all dependencies.

**Comment by xmatthias** [comment]
Well since this version is this old, i would encourage a fresh installation as shown in the [install documentation](https://www.freqtrade.io/en/latest/installation/) - or by using docker, as shown in our [docker installation documentation](https://www.freqtrade.io/en/latest/docker/).

**Comment by kiandp** [comment]
thank u very much for your fast response and i really appreciate your insights and efforts.
I solved the problem, i think this problem occurs when u r defining hyper-opt strategy by giving false indicator space or buy /sell order.cause i suspect the algo can't go over and over again of misrepresented range that i gave to it,i think that reason it was able to run it for some iterations but after some it gave error.
Thanks

**Comment by xmatthias** [comment]
yes, the error is caused by the hyperopt file - however there's many possibilities that can cause it - so detailed investigation is up to the user.

Thanks for confirming that it works now :+1:
