### ISSUE TITLE
BACKTESTING ISSUE

### ISSUE THREAD

**Issue by kiandp** [freqtrade/freqtrade#3684]
I am trying to run back testing for my new strategy,i have done lots of back testing before never encountered to any problem,however this time i am getting this error over & over again.I  optimized my strategy and transfer the optimization results to my strategy but when trying to do back-testing to check  my optimization and back testing result aligns  .i get this error.
please help,Thanks.

(.env) dp@dp-VirtualBox:~/freqtrade$ python3 ./freqtrade/main.py -c config.json -s BRS backtesting
2020-08-14 16:05:46,393 - freqtrade.configuration - INFO - Verbosity set to 0
2020-08-14 16:05:46,393 - freqtrade.configuration - INFO - Dry run is enabled
2020-08-14 16:05:46,393 - freqtrade.configuration - INFO - Using DB: "sqlite://"
2020-08-14 16:05:46,393 - freqtrade.configuration - INFO - Using max_open_trades: 15 ...
2020-08-14 16:05:46,394 - freqtrade.configuration - INFO - Using data folder: user_data/data/binance ...
2020-08-14 16:05:46,394 - freqtrade.optimize.backtesting - INFO - Starting freqtrade in Backtesting mode
2020-08-14 16:05:46,396 - freqtrade.resolvers.strategy_resolver - INFO - Using resolved strategy BRS from '/home/dp/freqtrade/freqtrade/strategy'
2020-08-14 16:05:46,401 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ticker_interval' with value in config file: 1h.
2020-08-14 16:05:46,401 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'trailing_stop' with value in config file: False.
2020-08-14 16:05:46,401 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 0.18030016548772917, '34': 0.07954311881078106, '49': 0.020922902180346918, '149': 0}
2020-08-14 16:05:46,401 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ticker_interval: 1h
2020-08-14 16:05:46,401 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.37028778342894964
2020-08-14 16:05:46,401 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2020-08-14 16:05:46,401 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
2020-08-14 16:05:46,401 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False}
2020-08-14 16:05:46,401 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
2020-08-14 16:05:46,401 - freqtrade.exchange - INFO - Instance is running with dry_run enabled
2020-08-14 16:05:46,401 - freqtrade.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2020-08-14 16:05:46,403 - freqtrade.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': False}
2020-08-14 16:05:46,431 - freqtrade.exchange - INFO - Using Exchange "Binance"
2020-08-14 16:05:47,106 - freqtrade.optimize.backtesting - INFO - Using stake_currency: BTC ...
2020-08-14 16:05:47,106 - freqtrade.optimize.backtesting - INFO - Using stake_amount: 0.01 ...
2020-08-14 16:05:47,107 - freqtrade.optimize.backtesting - INFO - Using local backtesting data (using whitelist in given config) ...
2020-08-14 16:05:47,355 - freqtrade.optimize.backtesting - INFO - Running backtesting for Strategy BRS
2020-08-14 16:05:47,358 - freqtrade.optimize - WARNING - XRP/BTC has missing frames: expected 914, got 719, that's 195 missing values
2020-08-14 16:05:47,358 - freqtrade.optimize.backtesting - INFO - Measuring data from 2020-07-07T16:00:00+00:00 up to 2020-08-14T18:00:00+00:00 (38 days)..
Traceback (most recent call last):
  File "./freqtrade/main.py", line 89, in <module>
    main(sys.argv[1:])
  File "./freqtrade/main.py", line 35, in main
    args.func(args)
  File "/home/dp/freqtrade/freqtrade/optimize/backtesting.py", line 477, in start
    backtesting.start()
  File "/home/dp/freqtrade/freqtrade/optimize/backtesting.py", line 418, in start
    'end_date': max_date,
  File "/home/dp/freqtrade/freqtrade/optimize/backtesting.py", line 296, in backtest
    pair_data['buy'], pair_data['sell'] = 0, 0  # cleanup from previous run
TypeError: 'NoneType' object does not support item assignment

**Comment by kiandp** [comment]
#cleanup from previous run , does this problem occurs due to multiple pair-list from my previous backtesting or something else?
