### ISSUE TITLE
cross_above problem with shift

### ISSUE THREAD

**Issue by ojneb84** [freqtrade/freqtrade#3718]
## Describe your environment

  * Operating system: Ubuntu 
  * Python Version: Python 3.8.2 (`python -V`)
  * CCXT version: ccxt==1.33.52 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade develop-21f4aba4 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Hello, 
I am having a problem with the cross_above function in qtpylib. I am trying to optimize one strategy but as soon as I run it I receive the following exception:

Traceback (most recent call last):
  File "/home/trademad/freqtrade/.env/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker
    r = call_item()
  File "/home/trademad/freqtrade/.env/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/trademad/freqtrade/.env/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/home/trademad/freqtrade/.env/lib/python3.8/site-packages/joblib/parallel.py", line 252, in __call__
    return [func(*args, **kwargs)
  File "/home/trademad/freqtrade/.env/lib/python3.8/site-packages/joblib/parallel.py", line 252, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/trademad/freqtrade/.env/lib/python3.8/site-packages/joblib/externals/loky/cloudpickle_wrapper.py", line 38, in __call__
    return self._obj(*args, **kwargs)
  File "/home/trademad/freqtrade/freqtrade/optimize/hyperopt.py", line 532, in generate_optimizer
    backtesting_results = self.backtesting.backtest(
  File "/home/trademad/freqtrade/freqtrade/optimize/backtesting.py", line 312, in backtest
    data: Dict = self._get_ohlcv_as_lists(processed)
  File "/home/trademad/freqtrade/freqtrade/optimize/backtesting.py", line 164, in _get_ohlcv_as_lists
    self.strategy.advise_buy(pair_data, {'pair': pair}), {'pair': pair})[headers].copy()
  File "/home/trademad/freqtrade/user_data/hyperopts/bbrsi_opt_v01.py", line 61, in populate_buy_trend
    conditions.append(qtpylib.crossed_above(dataframe['rsi'], params['rsi-value']))
  File "/home/trademad/freqtrade/freqtrade/vendor/qtpylib/indicators.py", line 243, in crossed_above
    return crossed(series1, series2, "above")
  File "/home/trademad/freqtrade/freqtrade/vendor/qtpylib/indicators.py", line 230, in crossed
    series1.shift(1) <= series2.shift(1)))
AttributeError: 'numpy.int64' object has no attribute 'shift'

Could it be a problem with pandas in the latest version?
thanks

*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
no, the problem is that a numpy.int64 is not really a integer, but it's "it's own" type.

``` python
In [1]: import numpy as np

In [2]: x = np.int64(111)                                                                                                              

In [3]: type(x)                                                                                                                        
Out[3]: numpy.int64

In [4]: isinstance(x, int)                                                                                                             
Out[4]: False

```

you should be able to get around this by using `qtpylib.crossed_above(dataframe['rsi'], int(params['rsi-value']))`
