### ISSUE TITLE
Getting permission denied error after installing the latest version

### ISSUE THREAD

**Issue by kiddkrypto** [freqtrade/freqtrade#3747]
I have searched the net for this issue but not much came up. I have other installs of freqtrade that are running but I am moving my infrastructure to aws and tested out the newly installed freqtrade and came up with this error.

## Describe your environment

  * Operating system: __Ubuntu 18__
  * Python Version: _3.8____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: __2020.8__ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

### Steps to reproduce:

  1. _run freqtrade trade -c X -s X____
  
  ```
 (.env) ubuntu@ip-10-10-10-186:~/freqtrade$ freqtrade trade -c config_btc.json --strategy AwesomeStrategy2020-09-03 23:05:31,450 - freqtrade.worker - INFO - Starting worker develop-27362046
2020-09-03 23:05:31,451 - freqtrade.configuration.configuration - INFO - Using config: config_btc.json ...
2020-09-03 23:05:31,453 - freqtrade.loggers - INFO - Verbosity set to 0
2020-09-03 23:05:31,454 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
2020-09-03 23:05:31,454 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2020-09-03 23:05:31,454 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:///tradesv3.dryrun.sqlite"
2020-09-03 23:05:31,454 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 30 ...
2020-09-03 23:05:31,455 - freqtrade.commands.trade_commands - ERROR - [Errno 13] Permission denied: '/home/ubuntu/freqtrade/user_data/hyperopt_results'
2020-09-03 23:05:31,455 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/ubuntu/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker = Worker(args)
  File "/home/ubuntu/freqtrade/freqtrade/worker.py", line 34, in __init__
    self._init(False)
  File "/home/ubuntu/freqtrade/freqtrade/worker.py", line 48, in _init
    self._config = Configuration(self._args, None).get_config()
  File "/home/ubuntu/freqtrade/freqtrade/configuration/configuration.py", line 41, in get_config
    self.config = self.load_config()
  File "/home/ubuntu/freqtrade/freqtrade/configuration/configuration.py", line 107, in load_config
    self._process_optimize_options(config)
  File "/home/ubuntu/freqtrade/freqtrade/configuration/configuration.py", line 240, in _process_optimize_options
    self._process_datadir_options(config)
  File "/home/ubuntu/freqtrade/freqtrade/configuration/configuration.py", line 190, in _process_datadir_options
    config['user_data_dir'] = create_userdata_dir(config['user_data_dir'], create_dir=False)
  File "/home/ubuntu/freqtrade/freqtrade/configuration/directory_operations.py", line 52, in create_userdata_dir
    subfolder.mkdir(parents=False)
  File "/usr/lib/python3.6/pathlib.py", line 1248, in mkdir
    self._accessor.mkdir(self, mode)
  File "/usr/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
PermissionError: [Errno 13] Permission denied: '/home/ubuntu/freqtrade/user_data/hyperopt_results'
(.env) ubuntu@ip-10-10-10-186:~/freqtrade$ 

  ```

**Comment by xmatthias** [comment]
well it's rather simple - you're getting a `permission denied` error from the user_data directory.

Most likely, it's got the wrong permissions (maybe you installed / created the user_data directory using a different user (or using sudo), now the "ubuntu" user doesn't have permissions to access the directory.

try `ls -l user_data` - or `ls -l user_data/hyperopt_results/` - i suspect they'll fail - or show you a different user than the one you're logged in with.

**Comment by kiddkrypto** [comment]
yes, i did have to install using sudo as the install couldn't install everything without it. here's the output of the permissions, FYI I'm not a major Linux guy.

(.env) ubuntu@ip-10-10-10-186:~/freqtrade$ ls -l user_data
total 28
drwxr-xr-x 2 root root 4096 Sep  3 20:24 backtest_results
drwxr-xr-x 2 root root 4096 Sep  3 20:24 data
drwxr-xr-x 3 root root 4096 Sep  3 22:22 freqtrade
drwxr-xr-x 2 root root 4096 Sep  3 20:24 hyperopts
drwxr-xr-x 2 root root 4096 Sep  3 20:24 logs
drwxr-xr-x 2 root root 4096 Sep  3 20:24 notebooks
drwxr-xr-x 2 root root 4096 Sep  3 22:29 strategies

**Comment by kiddkrypto** [comment]
what should the permission be on these folders?

**Comment by xmatthias** [comment]
The permissions should be for your username ... if they are root, you'll not have access to the directories.

best run `chown ubuntu:ubuntu -R user_data ` 
I wonder why you've got freqtrade in the user_data folder too .. what's the content of this?

**Comment by kiddkrypto** [comment]
thanks, that did work but got me to another problem I've never seen before about the database. but the other freqtrade folder I've always seen in my deployment of this even with my other installation, here's what's in it:

(.env) ubuntu@ip-10-10-10-186:~/freqtrade/freqtrade$ ls
__init__.py  configuration  exceptions.py    main.py   persistence.py  state.py   wallets.py
__main__.py  constants.py   exchange         misc.py   plot            strategy   worker.py
__pycache__  data           freqtradebot.py  optimize  resolvers       templates
commands     edge           loggers.py       pairlist  rpc             vendor

here is my new error that's preventing me from running the app:

(.env) ubuntu@ip-10-10-10-186:~/freqtrade$ freqtrade trade -c config_btc.json --strategy BBRSI
2020-09-04 12:23:28,378 - freqtrade.worker - INFO - Starting worker develop-27362046
2020-09-04 12:23:28,378 - freqtrade.configuration.configuration - INFO - Using config: config_btc.json ...
2020-09-04 12:23:28,379 - freqtrade.loggers - INFO - Verbosity set to 0
2020-09-04 12:23:28,380 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
2020-09-04 12:23:28,380 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2020-09-04 12:23:28,380 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:///tradesv3.dryrun.sqlite"
2020-09-04 12:23:28,380 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 30 ...
2020-09-04 12:23:28,380 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/ubuntu/freqtrade/user_data ...
2020-09-04 12:23:28,381 - freqtrade.configuration.configuration - INFO - Using data directory: /home/ubuntu/freqtrade/user_data/data/binance ...
2020-09-04 12:23:28,381 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2020-09-04 12:23:28,381 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2020-09-04 12:23:28,382 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2020-09-04 12:23:28,382 - freqtrade.configuration.deprecated_settings - WARNING - DEPRECATED: Please use 'timeframe' instead of 'ticker_interval.
2020-09-04 12:23:28,382 - freqtrade.freqtradebot - INFO - Starting freqtrade develop-27362046
2020-09-04 12:23:28,402 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy BBRSI from '/home/ubuntu/freqtrade/user_data/strategies/bbrsi.py'...
2020-09-04 12:23:28,403 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 1h.
2020-09-04 12:23:28,403 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: BTC.
2020-09-04 12:23:28,403 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 0.0052.
2020-09-04 12:23:28,403 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'buy': 10, 'sell': 30}.
2020-09-04 12:23:28,403 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'use_sell_signal' with value in config file: True.
2020-09-04 12:23:28,403 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'sell_profit_only' with value in config file: False.
2020-09-04 12:23:28,403 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ignore_roi_if_buy_signal' with value in config file: False.
2020-09-04 12:23:28,403 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 99}
2020-09-04 12:23:28,404 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 1h
2020-09-04 12:23:28,404 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.99
2020-09-04 12:23:28,404 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2020-09-04 12:23:28,404 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2020-09-04 12:23:28,404 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2020-09-04 12:23:28,404 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
2020-09-04 12:23:28,404 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'market', 'stoploss': 'limit', 'stoploss_on_exchange': False}
2020-09-04 12:23:28,404 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
2020-09-04 12:23:28,404 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: BTC
2020-09-04 12:23:28,404 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 0.0052
2020-09-04 12:23:28,405 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 0
2020-09-04 12:23:28,405 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'buy': 10, 'sell': 30}
2020-09-04 12:23:28,405 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_sell_signal: True
2020-09-04 12:23:28,405 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_only: False
2020-09-04 12:23:28,405 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_buy_signal: False
2020-09-04 12:23:28,405 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2020-09-04 12:23:28,405 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2020-09-04 12:23:28,409 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2020-09-04 12:23:28,409 - freqtrade.exchange.exchange - INFO - Using CCXT 1.33.72
2020-09-04 12:23:28,409 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2020-09-04 12:23:28,415 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 200}
2020-09-04 12:23:28,420 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2020-09-04 12:23:29,079 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2020-09-04 12:23:29,101 - freqtrade.commands.trade_commands - ERROR - (sqlite3.OperationalError) unable to open database file
(Background on this error at: http://sqlalche.me/e/13/e3q8)
2020-09-04 12:23:29,102 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/ubuntu/freqtrade/.env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2338, in _wrap_pool_connect
    return fn()
  File "/home/ubuntu/freqtrade/.env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/ubuntu/freqtrade/.env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/ubuntu/freqtrade/.env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/home/ubuntu/freqtrade/.env/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 239, in _do_get
    return self._create_connection()
  File "/home/ubuntu/freqtrade/.env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/home/ubuntu/freqtrade/.env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/home/ubuntu/freqtrade/.env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/ubuntu/freqtrade/.env/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/ubuntu/freqtrade/.env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/ubuntu/freqtrade/.env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/home/ubuntu/freqtrade/.env/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/ubuntu/freqtrade/.env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 493, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker = Worker(args)
  File "/home/ubuntu/freqtrade/freqtrade/worker.py", line 34, in __init__
    self._init(False)
  File "/home/ubuntu/freqtrade/freqtrade/worker.py", line 51, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/home/ubuntu/freqtrade/freqtrade/freqtradebot.py", line 70, in __init__
    persistence.init(self.config.get('db_url', None), clean_open_orders=self.config['dry_run'])
  File "/home/ubuntu/freqtrade/freqtrade/persistence.py", line 60, in init
    _DECL_BASE.metadata.create_all(engine)
  File "/home/ubuntu/freqtrade/.env/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 4556, in create_all
    ddl.SchemaGenerator, self, checkfirst=checkfirst, tables=tables
  File "/home/ubuntu/freqtrade/.env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2096, in _run_visitor
    with self._optional_conn_ctx_manager(connection) as conn:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/ubuntu/freqtrade/.env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2088, in _optional_conn_ctx_manager
    with self._contextual_connect() as conn:
  File "/home/ubuntu/freqtrade/.env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2304, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/home/ubuntu/freqtrade/.env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2342, in _wrap_pool_connect
    e, dialect, self
  File "/home/ubuntu/freqtrade/.env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1584, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/ubuntu/freqtrade/.env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/ubuntu/freqtrade/.env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2338, in _wrap_pool_connect
    return fn()
  File "/home/ubuntu/freqtrade/.env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/ubuntu/freqtrade/.env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/ubuntu/freqtrade/.env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/home/ubuntu/freqtrade/.env/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 239, in _do_get
    return self._create_connection()
  File "/home/ubuntu/freqtrade/.env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/home/ubuntu/freqtrade/.env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/home/ubuntu/freqtrade/.env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/ubuntu/freqtrade/.env/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/ubuntu/freqtrade/.env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/ubuntu/freqtrade/.env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/home/ubuntu/freqtrade/.env/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/ubuntu/freqtrade/.env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 493, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: http://sqlalche.me/e/13/e3q8)

**Comment by xmatthias** [comment]
well the error is technically the same - the bot is unable to read / write the database file (which i suspect is trades-v3.sqlite.

Simply put - your permissions in the whole folder are messed up ... which is never good ...

**Comment by kiddkrypto** [comment]
yes, thank you. this worked. how would I install this again without this issue?

**Comment by xmatthias** [comment]
by not using sudo to run the install script.

I don't think that should be necessary - as by using sudo, all commands within the script will run as user root ... which will cause these issues.

**Comment by xmatthias** [comment]
without knowing which operations didn't happen, this might be difficult to answer ... 😄

**Comment by kiddkrypto** [comment]
I'll recreate another instance and send error log to make sure I'm doing it right

**Comment by xmatthias** [comment]
I quess i'll close this as the issue was solved.

Feel free to comment below if you notice it's wrong when running the script without sudo.
