### ISSUE TITLE
RuntimeError! Stop bot in dry mode and live mode

### ISSUE THREAD

**Issue by AkioAlex0817** [freqtrade/freqtrade#3838]
## Describe your environment

  * Operating system: win10_pro
  * Python Version: 3.8.5
  * CCXT version: 1.34.59
  * Freqtrade Version: develop-d2111c08
  
## Your question

Thanks for your awesome source. Please understand that English is not my first language.
My question is may not be about an issue.
I am testing using Strategy001
I always get this message.
```
RuntimeError: <_overlapped.Overlapped object at 0x0000014EDFFA9E40> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 430, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000014EDFFA9E40> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 430, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000014EDFFA9E40> still has pending operation at deallocation, the process may crash
2020-10-06 16:33:58,116 - freqtrade.worker - INFO - Bot heartbeat. PID=15688, version='develop-d2111c08', state='RUNNING'
Traceback (most recent call last):
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 430, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000014EDFFA9E40> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 430, in select
    self._poll(timeout)
```

I looked for a lot of solutions to the problem, but I can't find them. 
Should I run it in a Linux?
I can't run this bot in windows.
Please help me. 
Thanks.

**Comment by xmatthias** [comment]
When does this error occur? 
right after starting the bot?
After running it for X amount of time?

also, please provide a few "earlier" log-messages as well, not just the stacktrace. This can give us a hint what the bot was doing when this exception appeared.

----

I don't think this error is related to freqtrade, but is a problem with your python installation (in particular, with asyncio).
How did you install python to your pc? via the windows store? via an installer ...?

I've found this [python issue](https://bugs.python.org/issue38798) - which suggests that the issue is not occuring anymore - but apparently that's not the case for your case.

Anyway, i'm able to run freqtrade on windows just fine... although i usually don't.

**Comment by AkioAlex0817** [comment]
I am installed python using `python-3.8.5-amd64.exe`

This is my log
1. Dry mode
   - Data download
      `freqtrade download-data -p ETH/BTC -t 5m --days=30`

     2020-10-06 19:11:03,056 - freqtrade.configuration.configuration - INFO - Using config: config.json ...
2020-10-06 19:11:03,056 - freqtrade.loggers - INFO - Verbosity set to 0
2020-10-06 19:11:03,057 - freqtrade.configuration.configuration - INFO - Using user-data directory: F:\AkioBot\Develop\user_data ...
2020-10-06 19:11:03,057 - freqtrade.configuration.configuration - INFO - Using data directory: F:\AkioBot\Develop\user_data\data\binance ...
2020-10-06 19:11:03,057 - freqtrade.configuration.configuration - INFO - Using pairs ['ETH/BTC']
2020-10-06 19:11:03,058 - freqtrade.configuration.configuration - INFO - timeframes --timeframes: ['5m']
2020-10-06 19:11:03,058 - freqtrade.configuration.configuration - INFO - Detected --days: 30
2020-10-06 19:11:03,058 - freqtrade.configuration.configuration - INFO - Using "json" to store OHLCV data.
2020-10-06 19:11:03,058 - freqtrade.configuration.configuration - INFO - Using "jsongz" to store trades data.
2020-10-06 19:11:03,058 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2020-10-06 19:11:03,058 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2020-10-06 19:11:03,058 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2020-10-06 19:11:03,061 - freqtrade.commands.data_commands - INFO - About to download pairs: ['ETH/BTC'], intervals: ['5m'] to F:\AkioBot\Develop\user_data\data\binance
2020-10-06 19:11:03,081 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2020-10-06 19:11:03,082 - freqtrade.exchange.exchange - INFO - Using CCXT 1.34.59
2020-10-06 19:11:03,082 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2020-10-06 19:11:03,105 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 200}
2020-10-06 19:11:03,126 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2020-10-06 19:11:03,184 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2020-10-06 19:11:03,185 - freqtrade.exchange.exchange - INFO - Markets were not loaded. Loading them now..
2020-10-06 19:11:04,606 - freqtrade.data.history.history_utils - INFO - Downloading pair ETH/BTC, interval 5m.
2020-10-06 19:11:04,606 - freqtrade.data.history.history_utils - INFO - Download history data for pair: "ETH/BTC", timeframe: 5m and store in F:\AkioBot\Develop\user_data\data\binance.
2020-10-06 19:11:04,637 - numexpr.utils - INFO - NumExpr defaulting to 6 threads.
Traceback (most recent call last):
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 430, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000002289EAD61E0> still has pending operation at deallocation, the process may crash
2020-10-06 19:11:04,786 - freqtrade.exchange.exchange - INFO - Downloaded data for ETH/BTC with length 291.
Traceback (most recent call last):
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 430, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x00000228B0253C00> still has pending operation at deallocation, the process may crash

    - backtesting
       Work well
    - plot-dataframe
       `freqtrade plot-dataframe -s Strategy001`
        2020-10-06 19:15:26,300 - freqtrade.configuration.configuration - INFO - Using config: config.json ...
2020-10-06 19:15:26,302 - freqtrade.loggers - INFO - Verbosity set to 0
2020-10-06 19:15:26,304 - freqtrade.configuration.configuration - INFO - Using user-data directory: F:\AkioBot\Develop\user_data ...
2020-10-06 19:15:26,349 - freqtrade.configuration.configuration - INFO - Using data directory: F:\AkioBot\Develop\user_data\data\binance ...
2020-10-06 19:15:26,350 - freqtrade.configuration.configuration - INFO - Limiting plot to: 750
2020-10-06 19:15:26,350 - freqtrade.configuration.configuration - INFO - Using trades from: file
2020-10-06 19:15:26,351 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2020-10-06 19:15:26,351 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2020-10-06 19:15:26,352 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2020-10-06 19:15:26,352 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2020-10-06 19:15:26,364 - freqtrade.resolvers.iresolver - WARNING - Could not import F:\AkioBot\Develop\user_data\strategies\AlexStrategy.py due to 'No module named 'ta''
2020-10-06 19:15:26,372 - freqtrade.resolvers.iresolver - WARNING - Could not import F:\AkioBot\Develop\user_data\strategies\MultiRSI.py due to 'No module named 'technical''
2020-10-06 19:15:26,400 - freqtrade.resolvers.iresolver - WARNING - Could not import F:\AkioBot\Develop\user_data\strategies\ReinforcedAverageStrategy.py due to 'No module named 'technical''
2020-10-06 19:15:26,403 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy Strategy001 from 'F:\AkioBot\Develop\user_data\strategies\Strategy001.py'...
2020-10-06 19:15:26,403 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 5m.
2020-10-06 19:15:26,404 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'trailing_stop' with value in config file: False.
2020-10-06 19:15:26,404 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: BTC.
2020-10-06 19:15:26,405 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 0.005.
2020-10-06 19:15:26,405 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'buy': 10, 'sell': 30}.
2020-10-06 19:15:26,405 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'use_sell_signal' with value in config file: True.
2020-10-06 19:15:26,406 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'sell_profit_only' with value in config file: True.
2020-10-06 19:15:26,406 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ignore_roi_if_buy_signal' with value in config file: False.
2020-10-06 19:15:26,406 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'60': 0.01, '30': 0.03, '20': 0.04, '0': 0.05}
2020-10-06 19:15:26,407 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 5m
2020-10-06 19:15:26,474 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.1
2020-10-06 19:15:26,475 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2020-10-06 19:15:26,475 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive: 0.01
2020-10-06 19:15:26,475 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.02
2020-10-06 19:15:26,476 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2020-10-06 19:15:26,476 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
2020-10-06 19:15:26,476 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'market', 'stoploss_on_exchange': False}
2020-10-06 19:15:26,476 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
2020-10-06 19:15:26,477 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: BTC
2020-10-06 19:15:26,477 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 0.005
2020-10-06 19:15:26,477 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 0
2020-10-06 19:15:26,478 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'buy': 10, 'sell': 30}
2020-10-06 19:15:26,478 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_sell_signal: True
2020-10-06 19:15:26,478 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_only: True
2020-10-06 19:15:26,478 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_buy_signal: False
2020-10-06 19:15:26,479 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2020-10-06 19:15:26,479 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2020-10-06 19:15:26,479 - freqtrade.exchange.exchange - INFO - Using CCXT 1.34.59
2020-10-06 19:15:26,480 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2020-10-06 19:15:26,484 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 200}
2020-10-06 19:15:26,489 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2020-10-06 19:15:27,775 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2020-10-06 19:15:27,796 - numexpr.utils - INFO - NumExpr defaulting to 6 threads.
2020-10-06 19:15:27,838 - freqtrade.data.btanalysis - INFO - Loading backtest result from F:\AkioBot\Develop\user_data\backtest_results\backtest-result-2020-10-06_12-24-58.json
2020-10-06 19:15:27,888 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "f:\akiobot\develop\freqtrade\main.py", line 37, in main
    return_code = args['func'](args)
  File "f:\akiobot\develop\freqtrade\commands\plot_commands.py", line 24, in start_plot_dataframe
    load_and_plot_trades(config)
  File "f:\akiobot\develop\freqtrade\plot\plotting.py", line 477, in load_and_plot_trades
    plot_elements = init_plotscript(config)
  File "f:\akiobot\develop\freqtrade\plot\plotting.py", line 63, in init_plotscript
    trades = load_trades(
  File "f:\akiobot\develop\freqtrade\data\btanalysis.py", line 276, in load_trades
    return load_backtest_data(exportfilename, strategy)
  File "f:\akiobot\develop\freqtrade\data\btanalysis.py", line 144, in load_backtest_data
    raise ValueError(f"Strategy {strategy} not available in the backtest result.")
ValueError: Strategy Strategy001 not available in the backtest result.
Traceback (most recent call last):
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 430, in select
RuntimeError: <_overlapped.Overlapped object at 0x000001B81561CC00> still has pending operation at deallocation, the process may crash


2. live mode
     `freqtrade trade -s Strategy001`
2020-10-06 19:17:01,836 - freqtrade.worker - INFO - Starting worker develop-d2111c08
2020-10-06 19:17:01,837 - freqtrade.configuration.configuration - INFO - Using config: config.json ...
2020-10-06 19:17:01,838 - freqtrade.loggers - INFO - Verbosity set to 0
2020-10-06 19:17:01,838 - freqtrade.configuration.configuration - INFO - Runmode set to live.
2020-10-06 19:17:01,839 - freqtrade.configuration.configuration - INFO - Dry run is disabled
2020-10-06 19:17:01,839 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:///tradesv3.sqlite"
2020-10-06 19:17:01,840 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 3 ...
2020-10-06 19:17:01,840 - freqtrade.configuration.configuration - INFO - Using user-data directory: F:\AkioBot\Develop\user_data ...
2020-10-06 19:17:01,841 - freqtrade.configuration.configuration - INFO - Using data directory: F:\AkioBot\Develop\user_data\data\binance ...
2020-10-06 19:17:01,841 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2020-10-06 19:17:01,842 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2020-10-06 19:17:01,842 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2020-10-06 19:17:01,842 - freqtrade.freqtradebot - INFO - Starting freqtrade develop-d2111c08
2020-10-06 19:17:01,854 - freqtrade.resolvers.iresolver - WARNING - Could not import F:\AkioBot\Develop\user_data\strategies\AlexStrategy.py due to 'No module named 'ta''
2020-10-06 19:17:01,886 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy Strategy001 from 'F:\AkioBot\Develop\user_data\strategies\Strategy001.py'...
2020-10-06 19:17:01,887 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 5m.
2020-10-06 19:17:01,887 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'trailing_stop' with value in config file: False.
2020-10-06 19:17:01,888 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: BTC.
2020-10-06 19:17:01,888 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 0.005.
2020-10-06 19:17:01,888 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'buy': 10, 'sell': 30}.
2020-10-06 19:17:01,911 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'use_sell_signal' with value in config file: True.
2020-10-06 19:17:01,925 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'sell_profit_only' with value in config file: True.
2020-10-06 19:17:01,926 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ignore_roi_if_buy_signal' with value in config file: False.
2020-10-06 19:17:01,926 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 0.01}
2020-10-06 19:17:01,927 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 5m
2020-10-06 19:17:01,927 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.05
2020-10-06 19:17:01,928 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2020-10-06 19:17:01,928 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2020-10-06 19:17:01,928 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2020-10-06 19:17:01,928 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: True
2020-10-06 19:17:01,968 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'market', 'stoploss_on_exchange': True}
2020-10-06 19:17:01,969 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
2020-10-06 19:17:02,006 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: BTC
2020-10-06 19:17:02,006 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 0.005
2020-10-06 19:17:02,007 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 40
2020-10-06 19:17:02,007 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'buy': 10, 'sell': 30}
2020-10-06 19:17:02,008 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_sell_signal: True
2020-10-06 19:17:02,008 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_only: True
2020-10-06 19:17:02,008 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_buy_signal: False
2020-10-06 19:17:02,009 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2020-10-06 19:17:02,047 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2020-10-06 19:17:02,051 - freqtrade.exchange.exchange - INFO - Using CCXT 1.34.59
2020-10-06 19:17:02,093 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2020-10-06 19:17:02,097 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 200}
2020-10-06 19:17:02,102 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2020-10-06 19:17:03,835 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2020-10-06 19:17:03,982 - freqtrade.wallets - INFO - Wallets synced.
2020-10-06 19:17:03,985 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from 'F:\AkioBot\Develop\freqtrade\pairlist\StaticPairList.py'...
2020-10-06 19:17:03,986 - freqtrade.rpc.rpc_manager - INFO - Enabling rpc.telegram ...
2020-10-06 19:17:06,320 - freqtrade.rpc.telegram - INFO - rpc.telegram is listening for following commands: [['status'], ['profit'], ['balance'], ['start'], ['stop'], ['forcesell'], ['forcebuy'], ['trades'], ['delete'], ['performance'], ['daily'], ['count'], ['reload_config', 'reload_conf'], ['show_config', 'show_conf'], ['stopbuy'], ['whitelist'], ['blacklist'], ['logs'], ['edge'], ['help'], ['version']]
2020-10-06 19:17:07,203 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'running'}
2020-10-06 19:17:08,706 - freqtrade.worker - INFO - Changing state to: RUNNING
2020-10-06 19:17:08,706 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': "*Exchange:* `binance`\n*Stake per trade:* `0.005 BTC`\n*Minimum ROI:* `{'0': 0.01}`\n*Stoploss:* `-0.05`\n*Timeframe:* `5m`\n*Strategy:* `Strategy001`"}
2020-10-06 19:17:09,714 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': "Searching for BTC pairs to buy and sell based on [{'StaticPairList': 'StaticPairList'}]"}
2020-10-06 19:17:10,547 - freqtrade.freqtradebot - INFO - Updating 0 open orders.
Traceback (most recent call last):
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 430, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000013C72A41C90> still has pending operation at deallocation, the process may crash
2020-10-06 19:17:10,747 - numexpr.utils - INFO - NumExpr defaulting to 6 threads.
2020-10-06 19:17:15,556 - freqtrade.worker - INFO - Bot heartbeat. PID=15608, version='develop-d2111c08', state='RUNNING'
Traceback (most recent call last):
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 430, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000013C72A41C90> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 430, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000013C72A41C90> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 430, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000013C72A41C90> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 430, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000013C72A41C90> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 430, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000013C72A41C90> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 430, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000013C72A41C90> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 430, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000013C72A41C90> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 430, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000013C72A41C90> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 430, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000013C72A41C90> still has pending operation at deallocation, the process may crash
....
Traceback (most recent call last):
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 430, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000013C72A41C90> still has pending operation at deallocation, the process may crash
(.env) F:\AkioBot\Develop>`

In live mode, the bot stopped after 2 minutes.

**Comment by xmatthias** [comment]
Clearly related to asyncio - but again, i don't think it's anything we can help you with.
Searching for that error yields results from projects from everywhere - but noone seems to have a solution.

The python issue linked above suggests it's a race condition - is your machine decently powered, or is it running close to it's limits (memory + cpu wise)?

**Comment by AkioAlex0817** [comment]
Thanks for your advice. 
This is my pc info
Intel(R) Core(TM) i5-9400F CPU @2.90GHz 2.90GHz
RAM: 16GB
Anyway, I will switch os to Ubuntu. 
I will try it there.
I will close this comment. 
Thanks.

**Comment by xmatthias** [comment]
That should have plenty of power ... 
Ubuntu, or else you can try WSL2 under windows. That's basically a lightweight linux system within windows - which should not have "windowsy" problems...
