### ISSUE TITLE
Empty candles when trading and using ta.LINEARREG_SLOPE

### ISSUE THREAD

**Issue by ojneb84** [freqtrade/freqtrade#3870]
## Describe your environment

  * Operating system: ____ Linux TVB 5.4.0-51-generic
  * Python Version: _____ Python 3.8.5
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____freqtrade develop-a9e7ee81
  
## Your question
I am trying to use the method 
ta.LINEARREG_SLOPE

When backtesting this works well, but when I try drying it, I get a message of empty candles for my pairs. This message appears repeatedly over and over. I am pasting the message below:

020-10-15 18:40:39,470 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error inputs are all NaN calling <bound method IStrategy._analyze_ticker_internal of <BBRSIBBB.BBRSIBBB object at 0x7fa2296b02e0>>
Traceback (most recent call last):
  File "/home/trademad/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 16, in wrapper
    return f(*args, **kwargs)
  File "/home/trademad/freqtrade/freqtrade/strategy/interface.py", line 351, in _analyze_ticker_internal
    dataframe = self.analyze_ticker(dataframe, metadata)
  File "/home/trademad/freqtrade/freqtrade/strategy/interface.py", line 330, in analyze_ticker
    dataframe = self.advise_indicators(dataframe, metadata)
  File "/home/trademad/freqtrade/freqtrade/strategy/interface.py", line 626, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/home/trademad/freqtrade/user_data/strategies/bbrsiPlusBBB.py", line 173, in populate_indicators
    dataframe['SLPRAclose1000'] = ta.LINEARREG_SLOPE(dataframe['RAclose1000'],20)
  File "talib/_abstract.pxi", line 399, in talib._ta_lib.Function.__call__
  File "talib/_abstract.pxi", line 441, in talib._ta_lib.Function.__call_function
  File "/home/trademad/freqtrade/.env/lib/python3.8/site-packages/talib/__init__.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "talib/_func.pxi", line 3324, in talib._ta_lib.LINEARREG_SLOPE
  File "talib/_func.pxi", line 68, in talib._ta_lib.check_begidx1
Exception: inputs are all NaN
2020-10-15 18:40:39,484 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair ALGO/BTC: inputs are all NaN

2020-10-15 18:41:12,426 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair LINK/BTC: inputs are all NaN
2020-10-15 18:41:12,431 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair ALGO/BTC
2020-10-15 18:41:12,432 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair ATOM/BTC
2020-10-15 18:41:12,433 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair BAT/BTC
2020-10-15 18:41:12,434 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair BRD/BTC
2020-10-15 18:41:12,435 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair ETH/BTC
2020-10-15 18:41:12,436 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair NEO/BTC
2020-10-15 18:41:12,438 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair NXS/BTC
2020-10-15 18:41:12,439 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair XMR/BTC
2020-10-15 18:41:12,440 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair LINK/BTC

**Comment by xmatthias** [comment]
the name of the column (`RAclose1000`) suggests that you're using something with a lookback of 1000 (which needs a history of 1000 candles).

Freqtrade will only have ~500 (actually 499) candles available during dry-run - so every strategy using a lookbac on anything > 499 candles will suffer from this.

**Comment by ojneb84** [comment]
I am actually using 1000 candles but when I am backtesting this works just fine. I mean, in the backtest my strategy seams to work just as I expected 
(actually in the .json file I have configured only 100 previous candles). 

the problem comes when the bot is running in sandbox mode. I figure out that for the rest of the 900 candles there is a NaN instead of a number? I actually don't know how to verify that

**Comment by xmatthias** [comment]
Let me repeat what i said above - in dry / live modes, you only have 499 candles available.

If you're using more than this - then your strategy will not work.

**Comment by xmatthias** [comment]
I'll close this and assume it's answered.

feel free to comment below / reopen if it's still unclear.
