### ISSUE TITLE
Downloading data from Binance doesn't work

### ISSUE THREAD

**Issue by jafarlihi** [freqtrade/freqtrade#3882]
## Describe your environment

  * Operating system: Arch Linux
  * Python Version: 3.8.6 (`python -V`)
  * CCXT version: Whatever is provided in `freqtrade:stable` container (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2020.9.1 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Describe the problem:

I'm trying to download BTC/USDT data for the last month in 1m frame. It starts up and doesn't log anything after `INFO - Current Amount of trades: 0` no matter how much you wait. I can also reproduce the issue for ETH/BTC pair.

### Steps to reproduce:

  1. Run `sudo docker-compose run --rm freqtrade download-data --pairs ETH/BTC --exchange binance --timerange 20201001-20201002 -t 6h`
  
### Observed Results:

No logs are being emitted after:
`INFO - Current Amount of trades: 0`

**Comment by xmatthias** [comment]
Best try to use the "-v" command line argument. 
It'll tell you more precisely what the bot is doing at which point.

However, with the parameters you specify, don't expect much data - 6h timeframe for 1 day will give you at max. 4 candles.

**Comment by jafarlihi** [comment]
@xmatthias Point is it is not giving that 4 candles either. I'll try `-v`.

**Comment by jafarlihi** [comment]
Update:
It started to log something after hanging on a little and this is what happens:
```
2020-10-22 13:22:50,703 - freqtrade.exchange.exchange - DEBUG - _async_get_trade_history(), pair: ETH/BTC, since: 1601510400000, until: None, from_id: None
2020-10-22 13:22:50,703 - freqtrade.exchange.exchange - DEBUG - Exchange milliseconds: 1603372970703
2020-10-22 13:22:50,703 - freqtrade.exchange.exchange - DEBUG - Fetching trades for pair ETH/BTC, since 1601510400000 (2020-10-01T00:00:00+00:00) ...
2020-10-22 13:23:01,324 - freqtrade.data.history.history_utils - ERROR - Failed to download historic trades for pair: "ETH/BTC". Error: 
2020-10-22 13:23:01,346 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 36, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/data_commands.py", line 65, in start_download_data
    convert_trades_to_ohlcv(
  File "/freqtrade/freqtrade/data/history/history_utils.py", line 360, in convert_trades_to_ohlcv
    ohlcv = trades_to_ohlcv(trades, timeframe)
  File "/freqtrade/freqtrade/data/converter.py", line 200, in trades_to_ohlcv
    return df_new.loc[:, DEFAULT_DATAFRAME_COLUMNS]
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexing.py", line 873, in __getitem__
    return self._getitem_tuple(key)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexing.py", line 1049, in _getitem_tuple
    self._has_valid_tuple(tup)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexing.py", line 700, in _has_valid_tuple
    raise IndexingError("Too many indexers")
pandas.core.indexing.IndexingError: Too many indexers
2020-10-22 13:23:01,348 - freqtrade.exchange.exchange - DEBUG - Exchange object destroyed, closing async loop
```

**Comment by xmatthias** [comment]
I think you are using a "wrong" configuration (one that's not made for binance).

For binance you should not download trades, but ohlcv candles.
Best check your mounts if the configuration contains "download_trades" - and if it does, remove it (or set it to false).

**Comment by jafarlihi** [comment]
@xmatthias Thanks, that fixed it!
