### ISSUE TITLE
How to pre-populate my dry-run/live mode with data before starting trading?

### ISSUE THREAD

**Issue by jafarlihi** [freqtrade/freqtrade#3885]
## Describe your environment

  * Operating system: Arch Linux
  * Python Version: 3.8.6 (`python -V`)
  * CCXT version: Whatever `freqtrade:stable` container provides (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2020.9.1 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

So I've got this data in my strategy:
```python
dataframe['rocr10080'] = ta.ROCR(dataframe, timeperiod=10080)
```

And I have a check on that in my `populate_buy_trend`:
```python
dataframe['rocr10080'].gt(0.90)
```

This leads to an issue where my bot doesn't trade anything for period of 10080 ticks (7 days, 1 minute ticks).
Is there any way of pre-populating my run with data of previous 7 days so my strategy starts trading right away instead of waiting to obtain that data before doing buys?

Or alternatively, is there a way to make the check in my `populate_buy_trend` optional? To only care about that constraint when the data is available and just ignore that constraint if not?

I guess I can put an if..else there if I knew how to get the seen tick count. Is it simply `len(dataframe)`?

**Comment by xmatthias** [comment]
in dry-run/live mode, dataframe will never have more than 500 candles.
Candles do NOT accumulate (that would mean a memory leak).

Therefore, the indicator youre using with this lookback period will not be possible.
You can use informative pairs (and use a different timeframe if you must look back for 7 days) - but using 10000 candles will not be possible with informative pairs eihter.

**Comment by jafarlihi** [comment]
@xmatthias Thanks for the answer.

I followed this https://www.freqtrade.io/en/latest/strategy-customization/#complete-data-provider-sample to the letter but this issue arises:
```
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 36, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 49, in start_backtesting
    backtesting.start()
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 402, in start
    preprocessed = self.strategy.ohlcvdata_to_dataframe(data)
  File "/freqtrade/freqtrade/strategy/interface.py", line 609, in ohlcvdata_to_dataframe
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair})
  File "/freqtrade/freqtrade/strategy/interface.py", line 609, in <dictcomp>
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair})
  File "/freqtrade/freqtrade/strategy/interface.py", line 626, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/freqtrade/user_data/strategies/Stavix.py", line 57, in populate_indicators
    dataframe = merge_informative_pair(dataframe, informative, self.timeframe, inf_tf, ffill=True)
  File "/freqtrade/freqtrade/strategy/strategy_helper.py", line 41, in merge_informative_pair
    dataframe = pd.merge(dataframe, informative, left_on='date',
  File "/usr/local/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 74, in merge
    op = _MergeOperation(
  File "/usr/local/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 656, in __init__
    self._maybe_coerce_merge_keys()
  File "/usr/local/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 1175, in _maybe_coerce_merge_keys
    raise ValueError(msg)
ValueError: You are trying to merge on datetime64[ns, UTC] and datetime64[ns] columns. If you wish to proceed you should use pd.concat
```

Is this a bug? How to make it work?

**Comment by xmatthias** [comment]
I'll assume this as answered by the above.

Feel free to reopen or comment below if you still have questions.
