### ISSUE TITLE
config.json not found

### ISSUE THREAD

**Issue by tmeteay** [freqtrade/freqtrade#3925]
Hello everyone,
been trying to launch the bot via docker but even though there is a config.json under user-data I get the following error:

```
2020-11-04 07:51:16,151 - freqtrade.worker - INFO - Starting worker 2020.10
2020-11-04 07:51:16,151 - freqtrade.configuration.configuration - INFO - Using config: config.json ...
2020-11-04 07:51:16,151 - freqtrade.commands.trade_commands - ERROR - Config file "config.json" not found! Please create a config file or check whether it exists.
2020-11-04 07:51:16,151 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/configuration/load_config.py", line 49, in load_config_file
    with open(path) if path != '-' else sys.stdin as file:
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/freqtrade/freqtrade/worker.py", line 49, in _init
    self._config = Configuration(self._args, None).get_config()
  File "/freqtrade/freqtrade/configuration/configuration.py", line 41, in get_config
    self.config = self.load_config()
  File "/freqtrade/freqtrade/configuration/configuration.py", line 94, in load_config
    config: Dict[str, Any] = self.load_from_files(self.args.get("config", []))
  File "/freqtrade/freqtrade/configuration/configuration.py", line 73, in load_from_files
    config = deep_merge_dicts(load_config_file(path), config)
  File "/freqtrade/freqtrade/configuration/load_config.py", line 52, in load_config_file
    raise OperationalException(
freqtrade.exceptions.OperationalException: Config file "config.json" not found! Please create a config file or check whether it exists.
```

how come is there a step a missed?

**Comment by xmatthias** [comment]
closing in favor of #3926
