### ISSUE TITLE
Download data error.    'Arrow' object has no attribute 'int_timestamp

### ISSUE THREAD

**Issue by acemi1** [freqtrade/freqtrade#3960]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`Python 3.8.2`)
  * CCXT version: _____ (`ccxt==1.37.70`)
  * Freqtrade Version: ____ (freqtrade develop-853bd068)
  
## Describe the problem:
First I updated the freqtrade with the following commands
```
git pull
python3 -m pip install -r requirements.txt --user
python3 -m pip install -r requirements-hyperopt.txt --user
python3 -m pip install -r requirements-plot.txt --user
source .env/bin/activate
python3 -m pip install -U ccxt
```

Then I used the following command for download data.
`freqtrade download-data --days 30 --timeframes  5m 15m 30m 1h 4h 1d
`

The code I always used didn't work.
I encountered the following error message.
*Explain the problem you have encountered*

### Relevant code exceptions or logs

  ```
2020-11-17 00:58:26,732 - freqtrade.configuration.configuration - INFO - Using config: config.json ...
2020-11-17 00:58:26,739 - freqtrade.loggers - INFO - Verbosity set to 0
2020-11-17 00:58:26,740 - freqtrade.configuration.configuration - INFO - Using user-data directory: /root/freqtrade/user_data ...
2020-11-17 00:58:26,741 - freqtrade.configuration.configuration - INFO - Using data directory: /root/freqtrade/user_data/data/binance ...
2020-11-17 00:58:26,741 - freqtrade.configuration.configuration - INFO - timeframes --timeframes: ['5m', '15m', '30m', '1h', '4h', '1d']
2020-11-17 00:58:26,741 - freqtrade.configuration.configuration - INFO - Detected --days: 30
2020-11-17 00:58:26,741 - freqtrade.configuration.configuration - INFO - Using "json" to store OHLCV data.
2020-11-17 00:58:26,741 - freqtrade.configuration.configuration - INFO - Using "jsongz" to store trades data.
2020-11-17 00:58:26,741 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2020-11-17 00:58:26,741 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2020-11-17 00:58:26,741 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2020-11-17 00:58:26,741 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2020-11-17 00:58:26,749 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/root/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/root/freqtrade/freqtrade/commands/data_commands.py", line 32, in start_download_data
    timerange = TimeRange.parse_timerange(f'{time_since}-')
  File "/root/freqtrade/freqtrade/configuration/timerange.py", line 92, in parse_timerange
    start = arrow.get(starts, 'YYYYMMDD').int_timestamp
  File "/root/freqtrade/.env/lib/python3.8/site-packages/arrow/arrow.py", line 509, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Arrow' object has no attribute 'int_timestamp'

  ```

**Comment by xmatthias** [comment]
what's your arrow version? (`pip freeze | grep arrow`)?

**Comment by StasDachinsky** [comment]
Same issue, arrow version 0.13.2

**Comment by acemi1** [comment]
arrow==0.15.8

**Comment by acemi1** [comment]
python3 -m pip install arrow
```
Requirement already satisfied: arrow in ./.env/lib/python3.8/site-packages (0.15.8)
Requirement already satisfied: python-dateutil in ./.env/lib/python3.8/site-packages (from arrow) (2.8.1)
Requirement already satisfied: six>=1.5 in ./.env/lib/python3.8/site-packages (from python-dateutil->arrow) (1.15.0)
```

**Comment by xmatthias** [comment]
`int_timestamp` was added in arrow 0.17.0 - and the "original" behaviour will go away with 0.18.0 according to their releaselog.

When updating freqtrade, you must make sure that you're also updating the requirements as pointed out in the release log.

This means - run `git pull` - followed by `pip install -r requirements.txt` for plain installations, or rerunning `setup.sh` ... 

even a `pip install -e .` (or `pip install .`) will force-upgrade arrow, as we know that arrow 0.17.0 is the minimum required version.

**Comment by amirrezamousavi1992** [comment]
Hello, i had the same issue. i fixed my issue by adding freqtrade modules path in jupyter.
get paths that jupyter look for modules and if project dir is not in it, simply append the dir to it
