### ISSUE TITLE
new exchange integration

### ISSUE THREAD

**Issue by yusufilker** [freqtrade/freqtrade#3963]
* Operating system: ubuntu 2004 on windows 10 wsl2
  * Python Version: 3.8.5
  * CCXT version: CCXT 1.37.14
  * Freqtrade Version: develop-2af1c80f
  
I updated ccxt side btcturk exchange api.  it is obviously not %100 percent compatible with the freqtrade-ccxt  callouts.
datadownload works but trade is not working.
Is there any  document describing "new exchange integration" to freqtrade ? minimum required functions and their inputs outputs etc. because ccxt side exchange interfaces are far from standard. 

Anyway, below is the console output. If you have any idea what is wrong please share.
thanks.

```
(.env) yusuf@DESKTOP-FB2FOCO:~/freqtrade$ freqtrade trade -s MACDStrategy2
2020-11-18 15:29:33,735 - freqtrade.worker - INFO - Starting worker develop-2af1c80f
2020-11-18 15:29:33,735 - freqtrade.configuration.configuration - INFO - Using config: config.json ...
2020-11-18 15:29:33,736 - freqtrade.loggers - INFO - Verbosity set to 0
2020-11-18 15:29:33,736 - freqtrade.configuration.configuration - INFO - Runmode set to live.
2020-11-18 15:29:33,736 - freqtrade.configuration.configuration - INFO - Dry run is disabled
2020-11-18 15:29:33,736 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:///tradesv3.sqlite"
2020-11-18 15:29:33,736 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 3 ...
2020-11-18 15:29:33,737 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/yusuf/freqtrade/user_data ...
2020-11-18 15:29:33,737 - freqtrade.configuration.configuration - INFO - Using data directory: /home/yusuf/freqtrade/user_data/data/btcturk ...
2020-11-18 15:29:33,737 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2020-11-18 15:29:33,737 - freqtrade.configuration.check_exchange - WARNING - Exchange "btcturk" is known to the the ccxt library, available for the bot, but not officially supported by the Freqtrade development team. It may work flawlessly (please report back) or have serious issues. Use it at your own discretion.
2020-11-18 15:29:33,737 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2020-11-18 15:29:33,737 - freqtrade.freqtradebot - INFO - Starting freqtrade develop-2af1c80f
2020-11-18 15:29:35,631 - freqtrade.resolvers.iresolver - WARNING - Could not import /home/yusuf/freqtrade/user_data/strategies/TechnicalExampleStrategy.py due to 'No module named 'technical''
2020-11-18 15:29:35,643 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy MACDStrategy2 from '/home/yusuf/freqtrade/user_data/strategies/MACDStrategy2.py'...
2020-11-18 15:29:35,644 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 5m.
2020-11-18 15:29:35,644 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: TRY.
2020-11-18 15:29:35,644 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 10.
2020-11-18 15:29:35,644 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'buy': 10, 'sell': 30}.
2020-11-18 15:29:35,644 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'use_sell_signal' with value in config file: True.
2020-11-18 15:29:35,644 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'sell_profit_only' with value in config file: False.
2020-11-18 15:29:35,644 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ignore_roi_if_buy_signal' with value in config file: False.
2020-11-18 15:29:35,644 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'60': 0.01, '30': 0.03, '20': 0.04, '0': 0.05}
2020-11-18 15:29:35,645 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 5m
2020-11-18 15:29:35,645 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.08
2020-11-18 15:29:35,645 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2020-11-18 15:29:35,645 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2020-11-18 15:29:35,645 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2020-11-18 15:29:35,645 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
2020-11-18 15:29:35,645 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False, 'stoploss_on_exchange_interval': 60}
2020-11-18 15:29:35,645 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
2020-11-18 15:29:35,645 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: TRY
2020-11-18 15:29:35,645 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 10
2020-11-18 15:29:35,646 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 0
2020-11-18 15:29:35,646 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'buy': 10, 'sell': 30}
2020-11-18 15:29:35,646 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_sell_signal: True
2020-11-18 15:29:35,646 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_only: False
2020-11-18 15:29:35,646 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_buy_signal: False
2020-11-18 15:29:35,646 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2020-11-18 15:29:35,646 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2020-11-18 15:29:35,650 - freqtrade.resolvers.exchange_resolver - INFO - No Btcturk specific subclass found. Using the generic class instead.
2020-11-18 15:29:35,650 - freqtrade.exchange.exchange - INFO - Using CCXT 1.37.14
2020-11-18 15:29:35,650 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2020-11-18 15:29:35,652 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2020-11-18 15:29:35,654 - freqtrade.exchange.exchange - INFO - Using Exchange "BTCTurk"
2020-11-18 15:29:36,755 - freqtrade.wallets - INFO - Wallets synced.
2020-11-18 15:29:36,803 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from '/home/yusuf/freqtrade/freqtrade/pairlist/StaticPairList.py'...
2020-11-18 15:29:36,803 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'running'}
2020-11-18 15:29:36,804 - freqtrade.worker - INFO - Changing state to: RUNNING
2020-11-18 15:29:36,804 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': "*Exchange:* `btcturk`\n*Stake per trade:* `10 TRY`\n*Minimum ROI:* `{'60': 0.01, '30': 0.03, '20': 0.04, '0': 0.05}`\n*Stoploss:* `-0.08`\n*Timeframe:* `5m`\n*Strategy:* `MACDStrategy2`"}
2020-11-18 15:29:36,804 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': "Searching for TRY pairs to buy and sell based on [{'StaticPairList': 'StaticPairList'}]"}
2020-11-18 15:29:36,813 - freqtrade.persistence.models - INFO - Found open trade: Trade(id=1, pair=ETH/TRY, amount=0.00270416, open_rate=3698.00000000, open_since=2020-11-18 08:10:20)
2020-11-18 15:29:36,817 - freqtrade.freqtradebot - INFO - Updating 1 open orders.
2020-11-18 15:29:37,798 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=1, pair=ETH/TRY, amount=0.00270416, open_rate=3698.00000000, open_since=2020-11-18 08:10:20)
2020-11-18 15:29:38,790 - freqtrade.commands.trade_commands - ERROR - 'NoneType' object has no attribute 'get'
2020-11-18 15:29:38,790 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/yusuf/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker.run()
  File "/home/yusuf/freqtrade/freqtrade/worker.py", line 74, in run
    state = self._worker(old_state=state)
  File "/home/yusuf/freqtrade/freqtrade/worker.py", line 92, in _worker
    self.freqtrade.startup()
  File "/home/yusuf/freqtrade/freqtrade/freqtradebot.py", line 142, in startup
    self.update_open_orders()
  File "/home/yusuf/freqtrade/freqtrade/freqtradebot.py", line 251, in update_open_orders
    self.update_trade_state(order.trade, order.order_id, fo)
  File "/home/yusuf/freqtrade/freqtrade/freqtradebot.py", line 1387, in update_trade_state
    trade.update_order(order)
  File "/home/yusuf/freqtrade/freqtrade/persistence/models.py", line 457, in update_order
    Order.update_orders(self.orders, order)
  File "/home/yusuf/freqtrade/freqtrade/persistence/models.py", line 174, in update_orders
    filtered_orders = [o for o in orders if o.order_id == order.get('id')]
  File "/home/yusuf/freqtrade/freqtrade/persistence/models.py", line 174, in <listcomp>
    filtered_orders = [o for o in orders if o.order_id == order.get('id')]
AttributeError: 'NoneType' object has no attribute 'get'
2020-11-18 15:29:38,829 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2020-11-18 15:29:38,829 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2020-11-18 15:29:38,829 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2020-11-18 15:29:38,832 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': warning, 'status': "1 open trades active.\n\nHandle these trades manually on BTCTurk, or '/start' the bot again and use '/stopbuy' to handle open trades gracefully. \n"}
2020-11-18 15:29:38,832 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
```

**Comment by xmatthias** [comment]
Unfortunately, we don't have such a documentation currently.

In general, all (most) methods in `exchange.py` should be implemented in ccxt .
They are 90% standard, and we try to only use ccxt "standard" fields.

You can get away with having either fetch_ticker or fetch_l2_orderbook working - in which case you'll need to adjust the config accordingly.


`download-data` only uses the "public" part of the ccxt api - so while that's a prerequisite - it's also far shot from being a compatible / working implementation.

---

This instance seems to find an open order in your database - and then fails to fetch that order (maybe `fetch_order()`) is not yet implemented in ccxt?

Now this is ... difficult to determine, you're best off starting with a fresh database, and posting the original error here.


I would also suggest to use an interactive environment (jupyter / ipython shell ...), create the ccxt object directly with your exchange keys, and then via ccxt:
* get price via `fetch_ticker()`
* get price via `fetch_l2_orderbook()`
* post an order (best post a limit order away from current price so it's not filling immediatley)
* fetch the order back via the id you received in the above call
* cancel the order
* post an order (letting it fill)
* fetch the filled order back via the id you got from the above call
* fetch balance

You should be able to get the syntax we're using out of exchange.py (or the ccxt documentation).

**Dislaimer**: *Obviously this will "use your money" unless that exchange has a sandbox environment (but very few actually do), so i'd recommend to use very low amounts for this.*

**Comment by yusufilker** [comment]
Thank you for the detailed information!

I updated ccxt existing btcturk exchange code, the new code works manually, I can do create_order, cancel order, fetch balances, fetch_tickers etc.  All public and private endpoints are working .The exchange server replies, I can read the responses :) ~~BUT~~
that responses may not be readable from ccxt or freqtrade. For example I transposed OHLCV matrix in order to make it readable by freqtrade. 

I will focus on ccxt parse functions to get the data readable by the system.

Thanks again.

**Comment by xmatthias** [comment]
Best read the contributing guide for ccxt, as you should not be modifying the exchange files in python, but make the changes in JS, and then transpile them to the python code.

This will allow you to contribute them to ccxt - which will then benefit both yourself and future users (as additional benefit, as more users can then use this exchange, more users will eventually fix bugs and fix them, which will then benefit yourself, too).



Hope this makes sense
