### ISSUE TITLE
Forcebuy Price is not float / REST API

### ISSUE THREAD

**Issue by makentoch** [freqtrade/freqtrade#3970]
https://github.com/freqtrade/freqtrade/blob/aa0c3dced8bac13b35e241f287d1d9a4cbcecd31/freqtrade/rpc/api_server.py#L510

COM:
$ python3 scripts/rest_client.py **forcebuy BTC/USDT 18000**

LOG:
2020-11-20 23:22:38,114 - freqtrade.rpc.api_server - ERROR - Exception on /api/v1/forcebuy [POST]
Traceback (most recent call last):
  File "/opt/freqtrade/.env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/freqtrade/.env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/freqtrade/.env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/freqtrade/.env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/freqtrade/.env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/freqtrade/.env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/freqtrade/freqtrade/rpc/api_server.py", line 44, in func_wrapper
    return func(obj, *args, **kwargs)
  File "/opt/freqtrade/freqtrade/rpc/api_server.py", line 57, in func_wrapper
    return func(obj, *args, **kwargs)
  File "/opt/freqtrade/freqtrade/rpc/api_server.py", line 401, in _forcebuy
    trade = self._rpc_forcebuy(asset, price)
  File "/opt/freqtrade/freqtrade/rpc/rpc.py", line 493, in _rpc_forcebuy
    if self._freqtrade.execute_buy(pair, stakeamount, price):
  File "/opt/freqtrade/freqtrade/freqtradebot.py", line 473, in execute_buy
    min_stake_amount = self._get_min_pair_stake_amount(pair, buy_limit_requested)
  File "/opt/freqtrade/freqtrade/freqtradebot.py", line 368, in _get_min_pair_stake_amount
    min_stake_amounts.append(limits['amount']['min'] * price)
TypeError: can't multiply sequence by non-int of type 'float'
2020-11-20 23:22:38,117 - werkzeug - INFO - 127.0.0.1 - - [20/Nov/2020 23:22:38] "POST /api/v1/forcebuy HTTP/1.1" 500 -

I have solved by adding `float()` the same as from `telegram.py`

`price = float(request.json.get("price", None))`

**Comment by xmatthias** [comment]
it's an issue for sure - but your solution will break using forcebuy without price - as `float(None)` will cause an exception ...
