### ISSUE TITLE
Hyperopt crashes in docker-compose

### ISSUE THREAD

**Issue by akenshaw** [freqtrade/freqtrade#3990]
* Operating system: Docker 19.03.13 at Win10 2004 x64
  * Python Version: 3.8.4
  * CCXT version: 1.38.13
  * Freqtrade Version: 2020.10

## Describe the problem:

While trying to run hyperopt, just after the "parellel workers found: xx", it crashes.

### Steps to reproduce:
using the stable image
 
 1.  docker-compose run -d freqtrade hyperopt --hyperopt STRATEGY1OPT--hyperopt-loss SharpeHyperOptLoss --strategy STRATEGY1 -e 500 --spaces all --timerange 20190201-20190401
 2.  crash

### Relevant code exceptions or logs

  ```
  2020-11-24 15:40:34,144 - freqtrade.optimize.hyperopt - INFO - Found 8 CPU cores. Let's make them scream!

2020-11-24 15:40:34,144 - freqtrade.optimize.hyperopt - INFO - Number of parallel jobs set as: -1

2020-11-24 15:40:34,165 - freqtrade.optimize.hyperopt - INFO - Effective number of parallel workers used: 8

/usr/local/lib/python3.8/site-packages/joblib/externals/loky/backend/utils.py:55: UserWarning: Failed to kill subprocesses on this platform. Pleaseinstall psutil: https://github.com/giampaolo/psutil

warnings.warn("Failed to kill subprocesses on this platform. Please"

/usr/local/lib/python3.8/site-packages/joblib/externals/loky/backend/utils.py:55: UserWarning: Failed to kill subprocesses on this platform. Pleaseinstall psutil: https://github.com/giampaolo/psutil

warnings.warn("Failed to kill subprocesses on this platform. Please"

/usr/local/lib/python3.8/site-packages/joblib/externals/loky/backend/utils.py:55: UserWarning: Failed to kill subprocesses on this platform. Pleaseinstall psutil: https://github.com/giampaolo/psutil

warnings.warn("Failed to kill subprocesses on this platform. Please"

/usr/local/lib/python3.8/site-packages/joblib/externals/loky/backend/utils.py:55: UserWarning: Failed to kill subprocesses on this platform. Pleaseinstall psutil: https://github.com/giampaolo/psutil

warnings.warn("Failed to kill subprocesses on this platform. Please"

/usr/local/lib/python3.8/site-packages/joblib/externals/loky/backend/utils.py:55: UserWarning: Failed to kill subprocesses on this platform. Pleaseinstall psutil: https://github.com/giampaolo/psutil

warnings.warn("Failed to kill subprocesses on this platform. Please"

/usr/local/lib/python3.8/site-packages/joblib/externals/loky/backend/utils.py:55: UserWarning: Failed to kill subprocesses on this platform. Pleaseinstall psutil: https://github.com/giampaolo/psutil

warnings.warn("Failed to kill subprocesses on this platform. Please"

/usr/local/lib/python3.8/site-packages/joblib/externals/loky/backend/utils.py:55: UserWarning: Failed to kill subprocesses on this platform. Pleaseinstall psutil: https://github.com/giampaolo/psutil

warnings.warn("Failed to kill subprocesses on this platform. Please"

/usr/local/lib/python3.8/site-packages/joblib/externals/loky/backend/utils.py:55: UserWarning: Failed to kill subprocesses on this platform. Pleaseinstall psutil: https://github.com/giampaolo/psutil

warnings.warn("Failed to kill subprocesses on this platform. Please"

2020-11-24 15:40:37,736 - freqtrade - ERROR - Fatal exception!

joblib.externals.loky.process_executor._RemoteTraceback:

"""

Traceback (most recent call last):

File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2895, in get_loc

return self._engine.get_loc(casted_key)

File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc

File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc

File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item

File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item

KeyError: 'close_time'


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

File "/usr/local/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker

r = call_item()

File "/usr/local/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 285, in __call__

return self.fn(*self.args, **self.kwargs)

File "/usr/local/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 595, in __call__

return self.func(*args, **kwargs)

File "/usr/local/lib/python3.8/site-packages/joblib/parallel.py", line 262, in __call__

return [func(*args, **kwargs)

File "/usr/local/lib/python3.8/site-packages/joblib/parallel.py", line 262, in <listcomp>

return [func(*args, **kwargs)

File "/usr/local/lib/python3.8/site-packages/joblib/externals/loky/cloudpickle_wrapper.py", line 38, in __call__

return self._obj(*args, **kwargs)

File "/freqtrade/freqtrade/optimize/hyperopt.py", line 546, in generate_optimizer

return self._get_results_dict(backtesting_results, min_date, max_date,

File "/freqtrade/freqtrade/optimize/hyperopt.py", line 563, in _get_results_dict

loss = self.calculate_loss(results=backtesting_results, trade_count=trade_count,

File "/freqtrade/user_data/hyperopts/updated_hyperopt_loss_sharpe.py", line 32, in hyperopt_loss_function

results["close_time_h"] = to_datetime(results["close_time"], unit="s")

File "/usr/local/lib/python3.8/site-packages/pandas/core/frame.py", line 2902, in __getitem__

indexer = self.columns.get_loc(key)

File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2897, in get_loc

raise KeyError(key) from err

KeyError: 'close_time'

"""


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

File "/freqtrade/freqtrade/main.py", line 37, in main

return_code = args['func'](args)

File "/freqtrade/freqtrade/commands/optimize_commands.py", line 83, in start_hyperopt

hyperopt.start()

File "/freqtrade/freqtrade/optimize/hyperopt.py", line 714, in start

f_val = self.run_optimizer_parallel(parallel, asked, i)

File "/freqtrade/freqtrade/optimize/hyperopt.py", line 618, in run_optimizer_parallel

return parallel(delayed(

File "/usr/local/lib/python3.8/site-packages/joblib/parallel.py", line 1061, in __call__

self.retrieve()

File "/usr/local/lib/python3.8/site-packages/joblib/parallel.py", line 940, in retrieve

self._output.extend(job.get(timeout=self.timeout))

File "/usr/local/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result

return future.result(timeout=timeout)

File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 439, in result

return self.__get_result()

File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result

raise self._exception

KeyError: 'close_time'
  ```

**Comment by xmatthias** [comment]
Well the error hints that it cannot kill the subprocess for some reason.
If anything, it would be an issue with joblib - not with freqtrade directly, so i don't think we will be able to help with this.

as a workaround, i would suggest to use docker through WSL2 - and not using the native windows docker solution (which is quite buggy and only caused me problems whenever using it) - this should solve this problem.
If you got an uptodate windows 10 installation, you should be able to enable WSL2 (or docker should propose this - not sure as i had WSL2 enabled before installing docker) 


Also, please make sure that your hyperopt file + strategy file do work correctly when running outside of docker to exclude eventual problems with the hyperopt file (but the exception log doesn't really point to this as problem).

**Comment by xmatthias** [comment]
Adding to the above:
i've just tested this with a configuration very similar to yours - using docker on windows 10 without WSL2 - and after fixing some mounting issues for the user_data directory, hyperopt is running perfectly fine with a freshly pulled `freqtradeorg/freqtrade:stable` image - so i think the above error is somehow tied to your system (or the hyperopt file) ... not to freqtrade (and not even to joblib).

**Comment by akenshaw** [comment]
oh sorry, i think i didnt mention, I'm already using the WSL 2 based engine with docker. Not thru hyperv. I've tried other hyperopt files and strategies but still the same. Can it be related to psutil as it says in the log? I already have it but when im testing the install of psutil im getting some errors/fails. I guess i should fresh install everything right :D

> Adding to the above:
> i've just tested this with a configuration very similar to yours - using docker (same version as yours) on windows 10 without WSL2 - and after fixing some mounting issues for the user_data directory, hyperopt is running perfectly fine with a freshly pulled `freqtradeorg/freqtrade:stable` image - so i think the above error is somehow tied to your system (or the hyperopt file) ... not to freqtrade (and not even to joblib).

**Comment by xmatthias** [comment]
well with docker it's not that simple - as with docker, every run is technically a fresh run from the image - so i'm not 100% sure what you would want to reinstall (except for docker, but that won't help i think).

Maybe try to switch back to non-WSL2 - i tried today without that and it did work - so maybe joblib detects it's windows - which then fails when running under wsl2 (or something similar)...
not happening with wsl2 natively - but all of wsl2 is still kinda new

**Comment by akenshaw** [comment]
Tried again with the hyperv but still the same. Anyways, i decided to run the bot on vmbox linux, no problems rn. Thank you for trying to help.

**Comment by shaunsaker** [comment]
I ran into a similar problem, also using WSL2 Docker on Windows 10 and managed to fix it by installing `ps-utils` and decreasing the `--job-workers` to only use half of my cores (it used 8 cores in the end). I'm not sure which of those fixed it but it's working 🙂

**Comment by akenshaw** [comment]
> I ran into a similar problem, also using WSL2 Docker on Windows 10 and managed to fix it by installing `ps-utils` and decreasing the `--job-workers` to only use half of my cores (it used 8 cores in the end). I'm not sure which of those fixed it but it's working 🙂

Thank you! Utilizing cores seems like the issue. Setting the job-workers to use half of the cores solved the problem.
