### ISSUE TITLE
unhandled timeouterror when downloading trades

### ISSUE THREAD

**Issue by Samaoo** [freqtrade/freqtrade#4013]
## Describe your environment

  * Operating system: Windows 10
  * Python Version: 3.8.5
  * CCXT version: 1.36.85
  * Freqtrade Version: 2020.11
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

There was an unhandled timeouterror when downloading trades, this only occurs when I download a lot of trades. For example: all ETH/EUR trades on kraken.

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  2020-11-28 23:51:50,553 - freqtrade.data.history.history_utils - ERROR - Failed to download historic trades for pair: "ETH/EUR".
Traceback (most recent call last):
  File "/freqtrade/freqtrade/data/history/history_utils.py", line 292, in _download_trades_history
    new_trades = exchange.get_historic_trades(pair=pair,
  File "/freqtrade/freqtrade/exchange/exchange.py", line 984, in get_historic_trades
    return asyncio.get_event_loop().run_until_complete(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/freqtrade/freqtrade/exchange/exchange.py", line 960, in _async_get_trade_history
    return await self._async_get_trade_history_id(
  File "/freqtrade/freqtrade/exchange/exchange.py", line 894, in _async_get_trade_history_id
    t = await self._async_fetch_trades(pair,
  File "/freqtrade/freqtrade/exchange/common.py", line 111, in wrapper
    return await f(*args, **kwargs)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 845, in _async_fetch_trades
    trades = await self._api_async.fetch_trades(pair, params=params, limit=1000)
  File "/usr/local/lib/python3.8/site-packages/ccxt/async_support/kraken.py", line 876, in fetch_trades
    response = await self.publicGetTrades(self.extend(request, params))
  File "/usr/local/lib/python3.8/site-packages/ccxt/async_support/base/exchange.py", line 95, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/local/lib/python3.8/site-packages/ccxt/async_support/base/exchange.py", line 116, in fetch
    async with session_method(yarl.URL(url, encoded=True),
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 905, in start
    self._continue = None
  File "/usr/local/lib/python3.8/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
  ```

**Comment by xmatthias** [comment]
I think this should be reported to CCXT instead (https://github.com/ccxt/ccxt/issues/8059).

according to their [documentation](https://github.com/ccxt/ccxt/wiki/Manual#error-handling), this should raise a `ccxt.NetworkError` (or rather a ccxt.TimeoutError) - which is handled in freqtrade correctly.

Now if ccxt passes all exceptions from sub-libraries "as is" to freqtrade, that would cause a problem - and mainly, does not correspond to the way it's documented in ccxt.

---

On a seperate note:
You should really work on your network connection - you've opened multiple "TimeoutError" exceptions already, which tells me that there's something utterly broken in your network (most seem to stem from the same ccxt problem).

With this type of connection, i don't think you will be able to run freqtrade reliably - as you will experience a lot of late buys / sells due to network issues (which can effectively lead to financial losses).

**Comment by Samaoo** [comment]
Thanks for reporting the issue to ccxt. I am still learning learning how freqtrade works and making strategies, when I start trading, I will probably use a VPS.

**Comment by xmatthias** [comment]
should work with ccxt > 1.38.51 (or so) - the precise ccxt version is not a hard requirement for freqtrade - so the latest version is usually the best.

Just use `pip install -U ccxt` to update ccxt and this exception should be handled properly from then on (obviously, after restarting the bot...).

This updated ccxt version will be in develop tomorrow sometime - and in the next release.
