### ISSUE TITLE
Comparing/logical operation on 'close' on the data frame failing

### ISSUE THREAD

**Issue by NilanjanaBala** [freqtrade/freqtrade#4020]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  freqtrade 2020.11

## Your question
I am trying to compare 'close' of current with the previous close from the dataframe. But getting following issue:

2020-11-30 18:47:55,742 - freqtrade.optimize.backtesting - INFO - Backtesting with data from 2020-01-30 00:00:00 up to 2020-02-03 00:00:00 (4 days)..
2020-11-30 18:47:55,746 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 50, in start_backtesting
    backtesting.start()
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 423, in start
    results = self.backtest(
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 310, in backtest
    data: Dict = self._get_ohlcv_as_lists(processed)
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 175, in _get_ohlcv_as_lists
    self.strategy.advise_buy(pair_data, {'pair': pair}), {'pair': pair})[headers].copy()
  File "/freqtrade/freqtrade/strategy/interface.py", line 641, in advise_buy
    return self.populate_buy_trend(dataframe, metadata)
  File "/freqtrade/user_data/strategies/strategy.py", line 256, in populate_buy_trend
    return (self.trend_buy_signal(dataframe))
  File "/freqtrade/user_data/strategies/strategy.py", line 169, in trend_buy_signal
    condition3 = dataframe['close'] < dataframe['close'].shift(
  File "/usr/local/lib/python3.8/site-packages/pandas/core/generic.py", line 1329, in __nonzero__
    raise ValueError(
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

Following is the condition:
        condition3 = (dataframe['close'].shift(0) > dataframe['close'].shift(
            1)) and (dataframe['close'].shift(2) > dataframe['close'].shift(3))

If i change the code as 
        condition3 = (dataframe['close'].shift(0).any() > dataframe['close'].shift(
            1).any()) and (dataframe['close'].shift(2).any() > dataframe['close'].shift(3).any())

It works but looks like getting incorrect result, is it right way to compare? What *.any() does exactly?

Sorry, i am still learning dataframe, not much knowledge but i am sure you might point me out very quickly. Thanks for your consideration.
*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
using `and` is not valid pandas syntax. You need to use binary operators for this (`&` instead of `and`, `|` instead of `or`)

Please don't use issues for this type of simplistic questions, where the answer can be found in google with one well-defined search. This clutters the issue tracker with unnecessary questions, and causes work drawing attention away from more important issues.
We understand this is an improtant topic for yourself, but as a small, free, open source project, we are unable to provide support for pandas (use pandas support channels) or use our  [discord server](https://discord.gg/MA9v74M) or alternatively our [Slack channel](https://join.slack.com/t/highfrequencybot/shared_invite/zt-jaut7r4m-Y17k4x5mcQES9a9swKuxbg), where the community will help you out.

Thanks for your understanding.
