### ISSUE TITLE
whenever i try using my own sharpe loss ratio formular i get an errror please help me out

### ISSUE THREAD

**Issue by cybermicheal47** [freqtrade/freqtrade#4025]
## Describe your environment

  * Operating system: __ubuntu 20__
  * Python Version: _____ (`python -3.6 & 3.8)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:
whenever i try using my own sharpe ratio formular i get an errror please help me out

*Explain the problem you have encountered*

### Steps to reproduce:

i used this code for the sharpe loss function

``` python
"""
sharpeeHyperOptLoss

This module defines the alternative HyperOptLoss class which can be used for
Hyperoptimization.
"""
from datetime import datetime

from pandas import DataFrame, to_datetime
import numpy as np
from freqtrade.optimize.hyperopt import IHyperOptLoss


class SharpeHyperOptLoss(IHyperOptLoss):
    """
    Defines the loss function for hyperopt.

    This implementation uses the Sharpe Ratio calculation.
    """

    @staticmethod
    def hyperopt_loss_function(results: DataFrame, trade_count: int,
                               min_date: datetime, max_date: datetime,
                               *args, **kwargs) -> float:
        """
        Objective function, returns smaller number for more optimal results.

        Uses Sharpe Ratio calculation.
        """
        # adding slippage of 0.1% per trade
        results["profit_percent"] = results["profit_percent"] - 0.001
        results["close_time_h"] = to_datetime(results["close_time"], unit="s")
        results = results.set_index("close_time_h")
        results = results.resample("D").sum()

        total_profit_per_day = results.profit_percent
        days_period = (max_date - min_date).days
        
        average_daily_return = total_profit_per_day.sum() / days_period

        if (np.std(total_profit_per_day ) != 0.):
            sharpe_ratio = (average_daily_return / np.std(total_profit_per_day )) * np.sqrt(365)
        else:
            # Define high (negative) sharpe ratio to be clear that this is NOT optimal.
            sharpe_ratio = -20.

        return -sharpe_ratio
```

 
  
### Observed Results:

```
2020-12-01 23:34:28,681 - freqtrade - ERROR - Fatal exception!
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/cybermicheal47/freqtrade/.env/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2895, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'close_time'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/cybermicheal47/freqtrade/.env/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker
    r = call_item()
  File "/home/cybermicheal47/freqtrade/.env/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/cybermicheal47/freqtrade/.env/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/home/cybermicheal47/freqtrade/.env/lib/python3.8/site-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/home/cybermicheal47/freqtrade/.env/lib/python3.8/site-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/cybermicheal47/freqtrade/.env/lib/python3.8/site-packages/joblib/externals/loky/cloudpickle_wrapper.py", line 38, in __call__
    return self._obj(*args, **kwargs)
  File "/home/cybermicheal47/freqtrade/freqtrade/optimize/hyperopt.py", line 546, in generate_optimizer
    return self._get_results_dict(backtesting_results, min_date, max_date,
  File "/home/cybermicheal47/freqtrade/freqtrade/optimize/hyperopt.py", line 563, in _get_results_dict
    loss = self.calculate_loss(results=backtesting_results, trade_count=trade_count,
  File "/home/cybermicheal47/freqtrade/freqtrade/optimize/hyperopt_loss_sharpe.py", line 32, in hyperopt_loss_function
    results["close_time_h"] = to_datetime(results["close_time"], unit="s")
  File "/home/cybermicheal47/freqtrade/.env/lib/python3.8/site-packages/pandas/core/frame.py", line 2902, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/cybermicheal47/freqtrade/.env/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2897, in get_loc
    raise KeyError(key) from err
KeyError: 'close_time'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/cybermicheal47/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/home/cybermicheal47/freqtrade/freqtrade/commands/optimize_commands.py", line 83, in start_hyperopt
    hyperopt.start()
  File "/home/cybermicheal47/freqtrade/freqtrade/optimize/hyperopt.py", line 714, in start
    f_val = self.run_optimizer_parallel(parallel, asked, i)
  File "/home/cybermicheal47/freqtrade/freqtrade/optimize/hyperopt.py", line 618, in run_optimizer_parallel
    return parallel(delayed(
  File "/home/cybermicheal47/freqtrade/.env/lib/python3.8/site-packages/joblib/parallel.py", line 1061, in __call__
    self.retrieve()
  File "/home/cybermicheal47/freqtrade/.env/lib/python3.8/site-packages/joblib/parallel.py", line 940, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/cybermicheal47/freqtrade/.env/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
KeyError: 'close_time'
 

```

i don't normally encounter any errors if i use the one already provided by freqtrade

**Comment by xmatthias** [comment]
the corerct key is open_date / close_date, not close_time.

It seems like we forgot to update this in the documentation ...

**Comment by cybermicheal47** [comment]
it workeds ..thanks alot

**Comment by xmatthias** [comment]
Documentation was updated. thanks for pointing that out
