### ISSUE TITLE
Binance sandbox float division by zero

### ISSUE THREAD

**Issue by Samaoo** [freqtrade/freqtrade#4030]
## Describe your environment

  * Operating system: Windows 10
  * Python Version: 3.8.5
  * CCXT version: 1.36.85
  * Freqtrade Version: 2020.10
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

When I try using the binance sandbox, and it executes a buy, it crashes

### Steps to reproduce:

  1. run ```freqtrade trade``` with a config for binance sandbox
  2. wait until it executes a buy
  
### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  2020-11-27 11:42:11,597 - freqtrade.worker - INFO - Starting worker 2020.10
2020-11-27 11:42:11,597 - freqtrade.configuration.configuration - INFO - Using config: user_data/config-sandbox.json ...
2020-11-27 11:42:11,602 - freqtrade.loggers - INFO - Verbosity set to 0
2020-11-27 11:42:11,602 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
2020-11-27 11:42:11,603 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2020-11-27 11:42:11,603 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:///tradesv3.dryrun.sqlite"
2020-11-27 11:42:11,603 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 2 ...
2020-11-27 11:42:11,613 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2020-11-27 11:42:11,615 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/binance ...
2020-11-27 11:42:11,615 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2020-11-27 11:42:11,615 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2020-11-27 11:42:11,615 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2020-11-27 11:42:11,616 - freqtrade.freqtradebot - INFO - Starting freqtrade 2020.10
2020-11-27 11:42:11,712 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy CombinedBinHAndCluc14 from '/freqtrade/user_data/strategies/CombinedBinHAndCluc14.py'...
2020-11-27 11:42:11,712 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 5m.
2020-11-27 11:42:11,713 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2020-11-27 11:42:11,713 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: unlimited.
2020-11-27 11:42:11,713 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'buy': 10, 'sell': 30}.
2020-11-27 11:42:11,713 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'use_sell_signal' with value in config file: True.
2020-11-27 11:42:11,713 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'sell_profit_only' with value in config file: False.
2020-11-27 11:42:11,714 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ignore_roi_if_buy_signal' with value in config file: False.
2020-11-27 11:42:11,714 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 0.13746, '15': 0.10054, '72': 0.03694}
2020-11-27 11:42:11,714 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 5m
2020-11-27 11:42:11,714 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.0001
2020-11-27 11:42:11,714 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: True
2020-11-27 11:42:11,714 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive: 0.13461
2020-11-27 11:42:11,714 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.21262
2020-11-27 11:42:11,714 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2020-11-27 11:42:11,715 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
2020-11-27 11:42:11,715 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': True}
2020-11-27 11:42:11,715 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
2020-11-27 11:42:11,715 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2020-11-27 11:42:11,715 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: unlimited
2020-11-27 11:42:11,715 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 0
2020-11-27 11:42:11,715 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'buy': 10, 'sell': 30}
2020-11-27 11:42:11,716 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_sell_signal: True
2020-11-27 11:42:11,716 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_only: False
2020-11-27 11:42:11,716 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_buy_signal: False
2020-11-27 11:42:11,716 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2020-11-27 11:42:11,716 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2020-11-27 11:42:11,722 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2020-11-27 11:42:11,722 - freqtrade.exchange.exchange - INFO - Using CCXT 1.36.85
2020-11-27 11:42:11,722 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2020-11-27 11:42:11,735 - freqtrade.exchange.exchange - INFO - Enabled Sandbox API on binance
2020-11-27 11:42:11,735 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 200}
2020-11-27 11:42:11,748 - freqtrade.exchange.exchange - INFO - Enabled Sandbox API on binance
2020-11-27 11:42:11,748 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2020-11-27 11:42:13,254 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2020-11-27 11:42:13,569 - freqtrade.persistence.migrations - INFO - Moving open orders to Orders table.
2020-11-27 11:42:13,592 - freqtrade.wallets - INFO - Wallets synced.
2020-11-27 11:42:13,595 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from '/freqtrade/freqtrade/pairlist/StaticPairList.py'...
2020-11-27 11:42:13,595 - freqtrade.rpc.rpc_manager - INFO - Enabling rpc.telegram ...
2020-11-27 11:42:14,293 - apscheduler.scheduler - INFO - Scheduler started
2020-11-27 11:42:15,436 - freqtrade.rpc.telegram - INFO - rpc.telegram is listening for following commands: [['status'], ['profit'], ['balance'], ['start'], ['stop'], ['forcesell'], ['forcebuy'], ['trades'], ['delete'], ['performance'], ['daily'], ['count'], ['locks'], ['reload_config', 'reload_conf'], ['show_config', 'show_conf'], ['stopbuy'], ['whitelist'], ['blacklist'], ['logs'], ['edge'], ['help'], ['version']]
2020-11-27 11:42:15,569 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'running'}
2020-11-27 11:42:15,666 - freqtrade.worker - INFO - Changing state to: RUNNING
2020-11-27 11:42:15,666 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': warning, 'status': 'Dry run is enabled. All trades are simulated.'}
2020-11-27 11:42:15,712 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': "*Exchange:* `binance`\n*Stake per trade:* `unlimited USDT`\n*Minimum ROI:* `{'0': 0.13746, '15': 0.10054, '72': 0.03694}`\n*Trailing Stoploss:* `-0.0001`\n*Timeframe:* `5m`\n*Strategy:* `CombinedBinHAndCluc14`"}
2020-11-27 11:42:15,775 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': "Searching for USDT pairs to buy and sell based on [{'StaticPairList': 'StaticPairList'}]"}
2020-11-27 11:42:15,822 - freqtrade.freqtradebot - INFO - Updating 0 open orders.
2020-11-27 11:42:17,084 - numexpr.utils - INFO - NumExpr defaulting to 8 threads.
2020-11-27 11:42:17,227 - freqtrade.wallets - INFO - Wallets synced.
2020-11-27 11:42:17,235 - freqtrade.freqtradebot - INFO - Buy signal found: about create a new trade with stake_amount: 495.0 ...
2020-11-27 11:42:17,235 - freqtrade.freqtradebot - INFO - Executing Buy for ETH/USDT
2020-11-27 11:42:17,236 - freqtrade.freqtradebot - INFO - Using Last Bid / Last Price
2020-11-27 11:42:17,499 - freqtrade.commands.trade_commands - ERROR - float division by zero
2020-11-27 11:42:17,500 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker.run()
  File "/freqtrade/freqtrade/worker.py", line 74, in run
    state = self._worker(old_state=state)
  File "/freqtrade/freqtrade/worker.py", line 111, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
  File "/freqtrade/freqtrade/worker.py", line 132, in _throttle
    result = func(*args, **kwargs)
  File "/freqtrade/freqtrade/worker.py", line 145, in _process_running
    self.freqtrade.process()
  File "/freqtrade/freqtrade/freqtradebot.py", line 182, in process
    self.enter_positions()
  File "/freqtrade/freqtrade/freqtradebot.py", line 364, in enter_positions
    trades_created += self.create_trade(pair)
  File "/freqtrade/freqtrade/freqtradebot.py", line 577, in create_trade
    return self.execute_buy(pair, stake_amount)
  File "/freqtrade/freqtrade/freqtradebot.py", line 627, in execute_buy
    amount = stake_amount / buy_limit_requested
ZeroDivisionError: float division by zero
2020-11-27 11:42:17,501 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2020-11-27 11:42:17,501 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2020-11-27 11:42:17,546 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2020-11-27 11:42:17,550 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
2020-11-27 11:42:17,550 - apscheduler.scheduler - INFO - Scheduler has been shut down
  ```

**Comment by xmatthias** [comment]
binance has a sandbox? :open_mouth: 

apart from that - i understand it shouldn't crash - but it's a problem with most sandboxes, and i doubt you can encounter this in real markets - there is no volume, and nothing in the orderbook.

The error appears because the best price (next seller in line) is giving you a 0.0000 price (or there is no seller)
Even if it wouldn't crash here - either there is no matching buyer so all trades will time out - or you'll push markets around even wtih very low order-sizes - as there are no / not many other market partecipants.


While using the sandbox sounds great in theory - i don't know why you would - as i'm yet to encounter a sandbox which properly emulates markets / market volumes - so your strategy can look great in the sandbox - but it'll be yourself pushing the market around even with 20$ orders ... so a strategy you validated in a sandbox is as good as a strategy not tested at all.
