### ISSUE TITLE
ERROR - '10' does not match 'unlimited'

### ISSUE THREAD

**Issue by aristosv** [freqtrade/freqtrade#4037]
Debian 10
Python 3.7.3
ccxt==1.38.55
freqtrade develop-058d40a7

This is my config.json
https://paste.ofcode.org/BRiW2jwetaF2GNKXpi5Wsg

and this is my strategy file
https://paste.ofcode.org/prbQZPvP9z34AZQGp8NWWY

When I start the bot I get a message saying

```
Failed validating 'pattern' in schema['properties']['stake_amount']:
    {'minimum': 0.0001,
     'pattern': 'unlimited',
     'type': ['number', 'string']}

On instance['stake_amount']:
    '10'
2020-12-06 12:11:47,286 - freqtrade.commands.trade_commands - ERROR - '10' does not match 'unlimited'
2020-12-06 12:11:47,286 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/root/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/root/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/root/freqtrade/freqtrade/worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/root/freqtrade/freqtrade/freqtradebot.py", line 67, in __init__
    validate_config_consistency(config)
  File "/root/freqtrade/freqtrade/configuration/config_validation.py", line 81, in validate_config_consistency
    validate_config_schema(conf)
  File "/root/freqtrade/freqtrade/configuration/config_validation.py", line 60, in validate_config_schema
    best_match(Draft4Validator(conf_schema).iter_errors(conf)).message
jsonschema.exceptions.ValidationError: '10' does not match 'unlimited'
```

**Comment by xmatthias** [comment]
Your configuration file is false.
stake_amount is supposed to be either a number, or "unlimited". You're giving it a number as string - which is invalid.

please note: 10USDT is most likely too low as stake amount, as it's not just the minimum stake amount that counds, but also the minimum asset amount. Use at least 15USDT for binance to avoid errors when selling.

**Comment by aristosv** [comment]
Thank you, that fixed it. Now I get this error, and I suspect its something similar.

freqtrade.commands.trade_commands - ERROR - 'false' is not of type 'boolean'

I'm guessing it's the way I specify settings in the configuration file. If they are in quotes it means something, and when not in quotes it means something else.

Any general guidelines I must follow to fix this?

**Comment by aristosv** [comment]
ok, I think I got it, thank for your help.
