### ISSUE TITLE
sqlite3.OperationalError: disk I/O error

### ISSUE THREAD

**Issue by Swordfish007** [freqtrade/freqtrade#4038]
* Operating system: Windows 10 Pro
  * Python Version: 3.8.6
  * CCXT version: 1.38.13
  * Freqtrade Version: 2020.11

I run freqtrade under Docker Desktop, using *docker-compose up --detach --force-recreate*.

**docker-compose.yml:**
  version: '3'
  services:
    freqtrade:
      image: freqtradeorg/freqtrade:stable
      restart: unless-stopped
      container_name: freqtrade
      volumes:
        - "./user_data:/freqtrade/user_data"
      command: >
        trade
        --logfile /freqtrade/user_data/logs/freqtrade.log
        --config /freqtrade/user_data/config.json

Note I have removed the --strategy and --db-url parameters from here, in favor of putting them in the config.json file.

**config.json:**
...
"db_url": "sqlite:////freqtrade/user_data/tradesv3.sqlite",
...

**Question:**
The bot starts up all fine, and even starts to trade, but at some point within a couple minutes Telegram tells me *process died*, and looking at the logs I find this:

2020-12-06 19:31:21,691 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 771, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 546, in do_commit
    dbapi_connection.commit()
sqlite3.OperationalError: disk I/O error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker.run()
  File "/freqtrade/freqtrade/worker.py", line 74, in run
    state = self._worker(old_state=state)
  File "/freqtrade/freqtrade/worker.py", line 111, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
  File "/freqtrade/freqtrade/worker.py", line 132, in _throttle
    result = func(*args, **kwargs)
  File "/freqtrade/freqtrade/worker.py", line 145, in _process_running
    self.freqtrade.process()
  File "/freqtrade/freqtrade/freqtradebot.py", line 181, in process
    if self.get_free_open_trades():
  File "/freqtrade/freqtrade/freqtradebot.py", line 236, in get_free_open_trades
    open_trades = len(Trade.get_open_trades())
  File "/freqtrade/freqtrade/persistence/models.py", line 570, in get_open_trades
    return Trade.get_trades(Trade.is_open.is_(True)).all()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3373, in all
    return list(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3534, in __iter__
    self.session._autoflush()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1629, in _autoflush
    util.raise_(e, with_traceback=sys.exc_info()[2])
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1618, in _autoflush
    self.flush()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2536, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2678, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2674, in _flush
    transaction.commit()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 508, in commit
    t[1].commit()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1762, in commit
    self._do_commit()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1793, in _do_commit
    self.connection._commit_impl()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 773, in _commit_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 771, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 546, in do_commit
    dbapi_connection.commit()
sqlalchemy.exc.OperationalError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.OperationalError) disk I/O error
(Background on this error at: http://sqlalche.me/e/13/e3q8)
2020-12-06 19:31:21,697 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2020-12-06 19:31:21,699 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}

I have checked, the file does exist in the correct place (/freqtrade/user_data/tradesv3.sqlite), and the host folder is also shared in Docker Desktop settings.
Somehow I don't seem to get this error if I leave the database file under it's original location (sqlite:///tradesv3.sqlite). I'd really appreciate some pointers as to where I should look to solve this.

Thanks

**Comment by xmatthias** [comment]
`sqlite:///tradesv3.sqlite` will be in a location that only exists within the container ... so don't do that.

The most likely explanation (actually the only i can think of) is that the file is write-protected - and the bot therefore not able to write to it.

**Comment by Swordfish007** [comment]
Thank you @xmatthias.  That was my thinking too, but if I completely delete the db file and then start the bot, the bot itself creates a new db file and the same error occurs.  Surely write-protection cannot be the issue then?

**Comment by xmatthias** [comment]
honstly, i'm not sure, volume mounting in docker with windows is a strange beast, and under windows, there's a TON of things that can interfere with your stuff and lock files (at least temporarily - like antivirus).

It'll also depend on the way you run docker under windows (there's the regular install, using WSL2 or using docker-machine) - each of which will might have slightly different problems in this regards.

Honestly, best use google to search for this particular problem in relation to your configuration... It's not a freqtrade problem, but a docker problem...

**Comment by Swordfish007** [comment]
Thx @xmatthias - I think I may have found the problem.  The /freqtrade/user_data/tradesv3.sqlite file is located in a folder that is automatically sync'd to my Google Drive with Backup and Sync from Google.  I have not seen the error yet after pausing the sync - so will keep on monitoring it for a while.

If this ends up being the issue, I'll have to find another way to "backup" the contents of /freqtrade/user_data/...

**Comment by xmatthias** [comment]
well that would make sense - most likely the 2 are contending for write locks ... maybe use a schedule that copies the file to a different locatio where it'll then be backed up would work for you ...

Thanks for letting us know the reason for the failure. It's unfortunately not something freqtrade can (or will try to) fix - as the problem stems from the way sqlite / sqlalchemy and google drive cooperate (or don't), not from the way freqtrade utilizes sqlalchemy.

**Comment by mARTin-B78** [comment]
> `sqlite:///tradesv3.sqlite` will be in a location that only exists within the container ... so don't do that.

thanks for the hint - so - what would be a path outside the container?
I have "mounted" the Volume "/freqtrade/user_data" to a path on my server

shall I then use sqlite:///freqtrade/user_data/tradesv3.sqlite instead?

**Comment by xmatthias** [comment]
> shall I then use sqlite:///freqtrade/user_data/tradesv3.sqlite instead?
> 

Yes correct. Thats also the path we have in the default docker-compose file.

**Comment by mihalt** [comment]
> > shall I then use sqlite:///freqtrade/user_data/tradesv3.sqlite instead?
> 
> Yes correct. Thats also the path we have in the default docker-compose file.

I completely don't know why, but with this Dockerfile
```
FROM freqtradeorg/freqtrade:develop
COPY ./freqtrade /freqtrade
ENTRYPOINT []
```

I got the same error as in this issue when I did the command like this in docker-compose when there weren't databases at all.
```
services:
  freqtrade_trade:
    pull_policy: always
    restart: always
    build: .
    volumes:
      - "./user_data:/freqtrade/user_data"
    command: >
      freqtrade trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --config /freqtrade/user_data/config.json
      --strategy MyStrategy
      --db-url sqlite:///freqtrade/user_data/tradesv3.dry_run.sqlite
      --dry-run
```

But when I changed to `--db-url sqlite:///user_data/tradesv3.dry_run.sqlite`, it started to work as expected. I checked, that the path is correct in container too (not starts from root /user_data/... and saves files to /freqtrade/user_data/). I don't understand why it happens on my windows/wsl2 machine, but this is what I have. Probably the command takes into accounting the `WORKDIR` of `freqtradeorg/freqtrade:develop` container.

**Comment by xmatthias** [comment]
@mihalt Please don't revive 3 year old threads. 
If you think you have an issue - it's **not** going to be the one from 4 years ago - not least because both your version, as well as other circumstances will have changed.
Open a new issue in such cases (Please consider this a warning - don't do it again).

Your path is absolutely incorrect - as `sqlite:///freqtrade/user_data/tradesv3.dry_run.sqlite` will point to a file relative to the current directory - which in absolute terms - will result in `/freqtrade/freqtrade/user_data/tradesv3.dry_run.sqlite` - which is a directory that doesn't exist.
If you want to use absolute paths, use 4 slashes (`sqlite:////freqtrade/user_data/tradesv3.dry_run.sqlite`)
