### ISSUE TITLE
"ERROR - Unable to place a stoploss order on exchange" not generating an Emergency Sell

### ISSUE THREAD

**Issue by larick** [freqtrade/freqtrade#4051]
## Describe your environment

  * Operating system: ____ Linux raspberrypi 5.4.51-v7l+ #1333 SMP Mon Aug 10 16:51:40 BST 2020 armv7l
  * Python Version: _____ Python 3.7.3
  * CCXT version: _____ ccxt==1.38.13
  * Freqtrade Version: ____ freqtrade develop-006436a1
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

I encouter very frequently an  "ERROR - Unable to place a stoploss order on exchange", corresponding to the fact that new stoploss seems above current price, whereas my trailing parameter are the following ones :
    trailing_stop_positive = 0.01
    trailing_stop_positive_offset = 0.013
and i'm filtering pairs the following way :
     {"method": "PriceFilter", "low_price_ratio": 0.008},
     {"method": "SpreadFilter", "max_spread_ratio": 0.008},

So, I know that considering "volatility", the price could suddently drop below the stoploss Freqtrade is trying to place, but in this case, Freqtrade should trigger an emergency sell, that it does not actually....

### Steps to reproduce:

  1. _____ running freqtrade with the strategy
  2. _____it happens more when volatility increases
  
### Observed Results:

  * What happened?

I miss lot positive trades because impossible to place stoploss, to trades goes in negative, until some point that the erroe is not happening any more.
Once I have the error, the error come back periodically

  * What did you expect to happen?

When trying to place a stoploss below current price, an emergency sell should be triggered, and in that way, I can stay on profitable trades

### Relevant code exceptions or logs

```
2020-12-09 00:57:45,873 - freqtrade.freqtradebot - INFO - Cancelling current stoploss on exchange for pair ROSE/USDT (orderid:5269908) in order to add another one ...
2020-12-09 00:57:46,836 - freqtrade.exchange.common - WARNING - stoploss() returned exception: "Could not place sell order due to ExchangeError. Message: binance {"code":-2010,"msg":"Stop price would trigger immediately."}"
2020-12-09 00:57:46,836 - freqtrade.exchange.common - WARNING - Giving up retrying: stoploss()
2020-12-09 00:57:46,837 - freqtrade.freqtradebot - ERROR - Unable to place a stoploss order on exchange.
Traceback (most recent call last):
  File "/home/freqtrade/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 588, in fetch
    response.raise_for_status()
  File "/home/freqtrade/freqtrade/.env/lib/python3.7/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/freqtrade/freqtrade/freqtrade/exchange/binance.py", line 67, in stoploss
    amount=amount, price=rate, params=params)
  File "/home/freqtrade/freqtrade/.env/lib/python3.7/site-packages/ccxt/binance.py", line 1653, in create_order
    response = getattr(self, method)(self.extend(request, params))
  File "/home/freqtrade/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 465, in inner
    return entry(_self, **inner_kwargs)
  File "/home/freqtrade/freqtrade/.env/lib/python3.7/site-packages/ccxt/binance.py", line 2455, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/home/freqtrade/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 486, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/freqtrade/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 604, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/freqtrade/freqtrade/.env/lib/python3.7/site-packages/ccxt/binance.py", line 2449, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions, error, feedback)
  File "/home/freqtrade/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 504, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.ExchangeError: binance {"code":-2010,"msg":"Stop price would trigger immediately."}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/freqtrade/freqtrade/freqtrade/freqtradebot.py", line 893, in create_stoploss_order
    order_types=self.strategy.order_types)
  File "/home/freqtrade/freqtrade/freqtrade/exchange/common.py", line 150, in wrapper
    raise ex
  File "/home/freqtrade/freqtrade/freqtrade/exchange/common.py", line 135, in wrapper
    return f(*args, **kwargs)
  File "/home/freqtrade/freqtrade/freqtrade/exchange/binance.py", line 87, in stoploss
    f'Could not place sell order due to {e.__class__.__name__}. Message: {e}') from e
freqtrade.exceptions.TemporaryError: Could not place sell order due to ExchangeError. Message: binance {"code":-2010,"msg":"Stop price would trigger immediately."}
2020-12-09 00:57:46,838 - freqtrade.freqtradebot - WARNING - Could not create trailing stoploss order for pair ROSE/USDT.

```

Full log attached, to see the frequence of the occurence of the probem
[freqtrade_4_live.log](https://github.com/freqtrade/freqtrade/files/5666043/freqtrade_4_live.log)

**Comment by xmatthias** [comment]
Seems like binance changed their message sometime in the past, so ccxt's assignment of the correct exception is no longer working correctly.

https://github.com/ccxt/ccxt/pull/8105 will fix this in ccxt - so once that's merged updating ccxt about 15 minutes after that should solve this issue.

**Comment by larick** [comment]
Thanks a lot for this efficient fixing !

**Comment by xmatthias** [comment]
well it's not fixed yet :D still needs the PR to be merged... :)

**Comment by larick** [comment]
Yes I know, but I can manually report the fix on my local to check the fix, waiting for PR to be merged ! .... when i'll find some time to do so....
