### ISSUE TITLE
hyperopt buy and sell didnt work - adx / mfi keyerrors

### ISSUE THREAD

**Issue by denniswisnia** [freqtrade/freqtrade#4065]
## Describe your environment

  * Operating system: Ubuntu 20.04.1 LTS 
  * Python Version: Python 3.8.5
  * CCXT version: ccxt==1.38.87
  * Freqtrade Version: freqtrade develop-7c6357cc
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

If I try to hyperopt my strategies with the spaces "buy" and "sell" or "all", I suddenly got an KeyError with adx (for buy) or mfi (for sell). The other spaces are working well.

### Steps to reproduce:

  1. Install freqtrade
  2. run hyperopt on any strategy with spaces "all" "buy" or "sell"
  3. get the error.
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
$ freqtrade hyperopt --spaces buy --stake-amount 0.001 --strategy EMASkipPump --hyperopt EMASkipPumpHyperOpt --hyperopt-loss SharpeHyperOptLossDaily
2020-12-14 06:42:22,392 - freqtrade.configuration.configuration - INFO - Using config: user_data/config.json ...
2020-12-14 06:42:22,393 - freqtrade.loggers - INFO - Verbosity set to 0
2020-12-14 06:42:22,393 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 5 ...
2020-12-14 06:42:22,393 - freqtrade.configuration.configuration - INFO - Parameter --stake-amount detected, overriding stake_amount to: 0.001 ...
2020-12-14 06:42:22,393 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/xxxx/freqtrade/user_data ...
2020-12-14 06:42:22,393 - freqtrade.configuration.configuration - INFO - Using data directory: /home/xxxx/freqtrade/user_data/data/binance ...
2020-12-14 06:42:22,393 - freqtrade.configuration.configuration - INFO - Using Hyperopt class name: EMASkipPumpHyperOpt
2020-12-14 06:42:22,393 - freqtrade.configuration.configuration - INFO - Parameter --epochs detected ... Will run Hyperopt with for 100 epochs ...
2020-12-14 06:42:22,393 - freqtrade.configuration.configuration - INFO - Parameter -s/--spaces detected: ['buy']
2020-12-14 06:42:22,393 - freqtrade.configuration.configuration - INFO - Parameter -j/--job-workers detected: -1
2020-12-14 06:42:22,393 - freqtrade.configuration.configuration - INFO - Parameter --min-trades detected: 1
2020-12-14 06:42:22,394 - freqtrade.configuration.configuration - INFO - Using Hyperopt loss class name: SharpeHyperOptLossDaily
2020-12-14 06:42:22,394 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2020-12-14 06:42:22,394 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2020-12-14 06:42:22,394 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2020-12-14 06:42:22,394 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2020-12-14 06:42:22,396 - freqtrade.commands.optimize_commands - INFO - Starting freqtrade in Hyperopt mode
2020-12-14 06:42:22,396 - filelock - INFO - Lock 140238143698112 acquired on /home/xxxx/freqtrade/user_data/hyperopt.lock
2020-12-14 06:42:22,396 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2020-12-14 06:42:22,396 - freqtrade.exchange.exchange - INFO - Using CCXT 1.38.87
2020-12-14 06:42:22,396 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2020-12-14 06:42:22,401 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 200}
2020-12-14 06:42:22,406 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2020-12-14 06:42:23,590 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2020-12-14 06:42:23,602 - freqtrade.resolvers.iresolver - WARNING - Could not import /home/xxxx/freqtrade/user_data/strategies/MultiRSI.py due to 'No module named 'technical''
2020-12-14 06:42:23,603 - freqtrade.resolvers.iresolver - WARNING - Could not import /home/xxxx/freqtrade/user_data/strategies/TechnicalExampleStrategy.py due to 'No module named 'technical''
2020-12-14 06:42:23,605 - freqtrade.resolvers.iresolver - WARNING - Could not import /home/xxxx/freqtrade/user_data/strategies/ReinforcedAverageStrategy.py due to 'No module named 'technical''
2020-12-14 06:42:23,606 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy EMASkipPump from '/home/xxxx/freqtrade/user_data/strategies/EMASkipPump.py'...
2020-12-14 06:42:23,607 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 5m.
2020-12-14 06:42:23,607 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'trailing_stop' with value in config file: True.
2020-12-14 06:42:23,607 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: BTC.
2020-12-14 06:42:23,607 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 0.001.
2020-12-14 06:42:23,607 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'buy': 10, 'sell': 30}.
2020-12-14 06:42:23,607 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 0.01, '5': 0.05, '30': 0.03}
2020-12-14 06:42:23,607 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 5m
2020-12-14 06:42:23,607 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.05
2020-12-14 06:42:23,607 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: True
2020-12-14 06:42:23,607 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2020-12-14 06:42:23,607 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2020-12-14 06:42:23,607 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
2020-12-14 06:42:23,607 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False, 'stoploss_on_exchange_interval': 60}
2020-12-14 06:42:23,607 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
2020-12-14 06:42:23,607 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: BTC
2020-12-14 06:42:23,607 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 0.001
2020-12-14 06:42:23,607 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 0
2020-12-14 06:42:23,608 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'buy': 10, 'sell': 30}
2020-12-14 06:42:23,608 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_sell_signal: False
2020-12-14 06:42:23,608 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_only: True
2020-12-14 06:42:23,608 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_buy_signal: False
2020-12-14 06:42:23,608 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2020-12-14 06:42:23,608 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2020-12-14 06:42:23,611 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from '/home/xxxx/freqtrade/freqtrade/pairlist/StaticPairList.py'...
2020-12-14 06:42:23,612 - freqtrade.resolvers.iresolver - INFO - Using resolved hyperopt EMASkipPumpHyperOpt from '/home/xxxx/freqtrade/user_data/hyperopts/EMASkipPumpHyperOpt.py'...
2020-12-14 06:42:23,612 - freqtrade.resolvers.hyperopt_resolver - INFO - Hyperopt class does not provide populate_indicators() method. Using populate_indicators from the strategy.
2020-12-14 06:42:23,612 - freqtrade.resolvers.hyperopt_resolver - INFO - Hyperopt class does not provide populate_buy_trend() method. Using populate_buy_trend from the strategy.
2020-12-14 06:42:23,613 - freqtrade.resolvers.hyperopt_resolver - INFO - Hyperopt class does not provide populate_sell_trend() method. Using populate_sell_trend from the strategy.
2020-12-14 06:42:23,618 - freqtrade.resolvers.iresolver - INFO - Using resolved hyperoptloss SharpeHyperOptLossDaily from '/home/xxxx/freqtrade/freqtrade/optimize/hyperopt_loss_sharpe_daily.py'...
2020-12-14 06:42:23,618 - freqtrade.optimize.hyperopt - INFO - Removing `/home/xxxx/freqtrade/user_data/hyperopt_results/hyperopt_tickerdata.pkl`.
2020-12-14 06:42:23,620 - freqtrade.optimize.hyperopt - INFO - Using optimizer random state: 39387
2020-12-14 06:42:23,630 - numexpr.utils - INFO - NumExpr defaulting to 2 threads.
2020-12-14 06:42:23,750 - freqtrade.data.converter - INFO - Missing data fillup for XLM/BTC: before: 8989 - after: 9001
2020-12-14 06:42:23,787 - freqtrade.data.converter - INFO - Missing data fillup for ETH/BTC: before: 8989 - after: 9001
2020-12-14 06:42:23,824 - freqtrade.data.converter - INFO - Missing data fillup for XEM/BTC: before: 8626 - after: 8638
2020-12-14 06:42:23,913 - freqtrade.data.converter - INFO - Missing data fillup for BNB/BTC: before: 8626 - after: 8638
2020-12-14 06:42:23,917 - freqtrade.optimize.backtesting - INFO - Loading data from 2020-11-11 09:30:00 up to 2020-12-12 15:30:00 (31 days)..
2020-12-14 06:42:23,917 - freqtrade.configuration.timerange - WARNING - Moving start-date by 0 candles to account for startup time.
2020-12-14 06:42:24,002 - freqtrade.optimize.hyperopt - INFO - Hyperopting with data from 2020-11-11 09:30:00 up to 2020-12-12 15:30:00 (31 days)..
2020-12-14 06:42:24,022 - freqtrade.optimize.hyperopt - INFO - Found 2 CPU cores. Let's make them scream!
2020-12-14 06:42:24,022 - freqtrade.optimize.hyperopt - INFO - Number of parallel jobs set as: -1
2020-12-14 06:42:24,039 - freqtrade.optimize.hyperopt - INFO - Effective number of parallel workers used: 2

2020-12-14 06:42:25,626 - freqtrade - ERROR - Fatal exception!
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/xxxx/freqtrade/.env/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2895, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'adx'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/xxxx/freqtrade/.env/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker
    r = call_item()
  File "/home/xxxx/freqtrade/.env/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/xxxx/freqtrade/.env/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/home/xxxx/freqtrade/.env/lib/python3.8/site-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/home/xxxx/freqtrade/.env/lib/python3.8/site-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/xxxx/freqtrade/.env/lib/python3.8/site-packages/joblib/externals/loky/cloudpickle_wrapper.py", line 38, in __call__
    return self._obj(*args, **kwargs)
  File "/home/xxxx/freqtrade/freqtrade/optimize/hyperopt.py", line 538, in generate_optimizer
    backtesting_results = self.backtesting.backtest(
  File "/home/xxxx/freqtrade/freqtrade/optimize/backtesting.py", line 346, in backtest
    data: Dict = self._get_ohlcv_as_lists(processed)
  File "/home/xxxx/freqtrade/freqtrade/optimize/backtesting.py", line 203, in _get_ohlcv_as_lists
    self.strategy.advise_buy(pair_data, {'pair': pair}), {'pair': pair})[headers].copy()
  File "/home/xxxx/freqtrade/user_data/hyperopts/EMASkipPumpHyperOpt.py", line 59, in populate_buy_trend
    conditions.append(dataframe['adx'] > params['adx-value'])
  File "/home/xxxx/freqtrade/.env/lib/python3.8/site-packages/pandas/core/frame.py", line 2906, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/xxxx/freqtrade/.env/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2897, in get_loc
    raise KeyError(key) from err
KeyError: 'adx'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/xxxx/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/home/xxxx/freqtrade/freqtrade/commands/optimize_commands.py", line 83, in start_hyperopt
    hyperopt.start()
  File "/home/xxxx/freqtrade/freqtrade/optimize/hyperopt.py", line 716, in start
    f_val = self.run_optimizer_parallel(parallel, asked, i)
  File "/home/xxxx/freqtrade/freqtrade/optimize/hyperopt.py", line 620, in run_optimizer_parallel
    return parallel(delayed(
  File "/home/xxxx/freqtrade/.env/lib/python3.8/site-packages/joblib/parallel.py", line 1061, in __call__
    self.retrieve()
  File "/home/xxxx/freqtrade/.env/lib/python3.8/site-packages/joblib/parallel.py", line 940, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/xxxx/freqtrade/.env/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
KeyError: 'adx'

  ```

**Comment by xmatthias** [comment]
it's quite simple - your spaces (`indicator_space`, `sell_indicator_space`) - as well as your generators (`buy_strategy_generator`, `sell_strategy_generator`) are not aligned to your strategy's `populate_indicators`.

Basically - your hyperopt is trying to optimize the best value of ADX - but your strategy's `populate_indicators()` method does not generate these indicators, so they are not available in the dataframe.

The soluiton is quite simple - either remove the optimization of `'adx'` (and whatever else is failing) in your spaces, or create the indicators as columns in your populate_indicators.

Keep in mind, hyperopt is not a "i simply use it as is and it will work with every strategy" method, but will require heavy adaptation towards your strategy, as hyperopt cannot know which indicators / parameters your strategy uses.

It'll work for "simple" spaces like ROI and stoploss as these have predefined spaces (and use the `populate_buy` and `populate_sell` methods from your strategy) - however to optimize buy / sell spaces, you'll need to invest some time to align hyperopt with your strategy.

**Comment by denniswisnia** [comment]
Thanks @xmatthias  - you got me. Now its working like a charme.
