### ISSUE TITLE
Fatal Exception Error : Unexpectedly Terminated Worker - Excessive Memory Usage 

### ISSUE THREAD

**Issue by chugh-ak5** [freqtrade/freqtrade#4066]
Have you searched for similar issues before posting it?
Yes, found a similar open issue but didn't find a solution [https://github.com/scikit-learn-contrib/skope-rules/issues/18](url)

## Describe your environment
  * Operating system: Windows 10, x64 8GB RAM
  * Python Version: 3.8.5
  * CCXT version: 1.37.69 
  * Freqtrade Version: develop-37849f84 

## Describe the problem:
I am currently running Ubuntu 20.04 with WSL1 on my Windows 10 system. I have 8 CPU cores being used and parallel jobs set as -1. I have been unable to run hyperopt multiple times due to excessive memory usage, although I have hyperopted before but never faced this issue. Have included the right parameters according to the freqtrade documentation but hyperopt still doesn't work 

### Steps to reproduce:
  1. Updated freqtrade 
  2. Tried running hyperopt again 
  3. Hyperopt still shows the error 
  
### Observed Results:
  * What happened?
Could not run hyperopt due to excessive memory usage
  * What did you expect to happen?
Run hyperopt as I could before and debug this error with assistance 

### Relevant code exceptions or logs
`` 2020-12-14 16:35:17,804 - freqtrade.optimize.backtesting - INFO - Loading data from 2020-01-30 00:00:00 up to 2020-12-09 23:15:00 (314 days)..  
2020-12-14 16:35:17,806 - freqtrade.configuration.timerange - WARNING - Moving start-date by 20 candles to account for startup time.        
2020-12-14 16:35:30,921 - freqtrade.optimize.hyperopt - INFO - Hyperopting with data from 2020-01-30 00:00:00 up to 2020-12-09 23:15:00 (314 days)..                                          
2020-12-14 16:35:40,604 - freqtrade.optimize.hyperopt - INFO - Found 8 CPU cores. Let's make them scream!                                                                                     2020-12-14 16:35:40,607 - freqtrade.optimize.hyperopt - INFO - Number of parallel jobs set as: -1 
2020-12-14 16:35:41,505 - freqtrade.optimize.hyperopt - INFO - Effective number of parallel workers used: 8 
2020-12-14 16:48:37,499 - freqtrade - ERROR - Fatal exception!                                                                                                                                Traceback (most recent call last):                                                                                                                                                            File "/home/chugh_ak/freqtrade/freqtrade/main.py", line 37, in main                                                                                                                           return_code = args[' func '](args)                                                                                                                                                       
File "/home/chugh_ak/freqtrade/freqtrade/commands/optimize_commands.py", line 83, in start_hyperopt                                                                                           hyperopt.start()                                                                                                                                                                              File "/home/chugh_ak/freqtrade/freqtrade/optimize/hyperopt.py", line 714, in start                                                                                                            f_val = self.run_optimizer_parallel(parallel, asked, i)                                                                                                                                       File "/home/chugh_ak/freqtrade/freqtrade/optimize/hyperopt.py", line 618, in run_optimizer_parallel                                                                                           return parallel(delayed(                                                                                                                                                                      File "/home/chugh_ak/freqtrade/.env/lib/python3.8/site-packages/joblib/parallel.py", line 1061, in __call__                                                                                   self.retrieve()                                                                                                                                                                               File "/home/chugh_ak/freqtrade/.env/lib/python3.8/site-packages/joblib/parallel.py", line 940, in retrieve                                                                                    self._output.extend(job.get(timeout=self.timeout))                                                                                                                                            File "/home/chugh_ak/freqtrade/.env/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result                                                                return future.result(timeout=timeout)                                                                                                                                                         File "/usr/lib/python3.8/concurrent/futures/_base.py", line 439, in result                                                                                                                    return self.__get_result()                                                                                                                                                                    File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result                                                                                                              raise self._exception                                                                                                                                                                         joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

The exit codes of the workers are {SIGSEGV(-11)}  ``
Please let me know how I could fix this 
![freq_issue](https://user-images.githubusercontent.com/57716226/102108413-30540900-3e33-11eb-8486-8f5dc1338428.PNG)

**Comment by chugh-ak5** [comment]
<!-- 
Have you searched for similar issues before posting it?
Yes, found a similar open issue but didn't find a solution [https://github.com/scikit-learn-contrib/skope-rules/issues/18](url)

## Describe your environment
  * Operating system: Windows 10, x64 8GB RAM
  * Python Version: 3.8.5
  * CCXT version: 1.37.69 
  * Freqtrade Version: develop-37849f84 

## Describe the problem:
I am currently running Ubuntu 20.04 with WSL1 on my Windows 10 system. I have 8 CPU cores being used and parallel jobs set as -1. I have been unable to run hyperopt multiple times due to excessive memory usage, although I have hyperopted before but never faced this issue. Have included the right parameters according to the freqtrade documentation but hyperopt still doesn't work 

### Steps to reproduce:
  1. Updated freqtrade 
  2. Tried running hyperopt again 
  3. Hyperopt still shows the error 
  
### Observed Results:
  * What happened?
Could not run hyperopt due to excessive memory usage
  * What did you expect to happen?
Run hyperopt as I could before and debug this error with assistance 

### Relevant code exceptions or logs
  ```
2020-12-14 16:48:37,499 - freqtrade - ERROR - Fatal exception!                                                                                                                                                     Traceback (most recent call last):                                                                                                                                                                                   File "/home/chugh_ak/freqtrade/freqtrade/main.py", line 37, in main                                                                                                                                                  return_code = args['func'](args)                                                                                                                                                                                 File "/home/chugh_ak/freqtrade/freqtrade/commands/optimize_commands.py", line 83, in start_hyperopt                                                                                                                  hyperopt.start()                                                                                                                                                                                                 File "/home/chugh_ak/freqtrade/freqtrade/optimize/hyperopt.py", line 714, in start                                                                                                                                   f_val = self.run_optimizer_parallel(parallel, asked, i)                                                                                                                                                          File "/home/chugh_ak/freqtrade/freqtrade/optimize/hyperopt.py", line 618, in run_optimizer_parallel                                                                                                                  return parallel(delayed(                                                                                                                                                                                         File "/home/chugh_ak/freqtrade/.env/lib/python3.8/site-packages/joblib/parallel.py", line 1061, in __call__                                                                                                          self.retrieve()                                                                                                                                                                                                  File "/home/chugh_ak/freqtrade/.env/lib/python3.8/site-packages/joblib/parallel.py", line 940, in retrieve                                                                                                           self._output.extend(job.get(timeout=self.timeout))                                                                                                                                                               File "/home/chugh_ak/freqtrade/.env/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result                                                                                       return future.result(timeout=timeout)                                                                                                                                                                            File "/usr/lib/python3.8/concurrent/futures/_base.py", line 439, in result                                                                                                                                           return self.__get_result()                                                                                                                                                                                       File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result                                                                                                                                     raise self._exception                                                                                                                                                                                          joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.                                                                                                                                                                                                                                                                                                                                                             The exit codes of the workers are {SIGSEGV(-11)} 

  ```
Please let me know how I could fix this

**Comment by xmatthias** [comment]
what's the timeframe you're using?
and how many pairs?

**Comment by chugh-ak5** [comment]
Thanks for your reply @xmatthias 
I was having 57 pairs and running my strategy on a 5m timeframe for 314 days
I reduced the timerange to 99 days, removed a few pairs and tested for 100 epochs, works fine now 
Will reduce the number of parallelity with increased days 
Thanks for your assistance!

**Comment by Youbadawy** [comment]
@xmatthias is it possible to find a way to optimize on the memory usage involved? my background is not software, but I am willing to dig deep in it, as long as i have some guidance!

**Comment by xmatthias** [comment]
@Youbadawy I would not know how.

It's a basis of joblib, which starts multiple processes. Each process will in turn need all data.
Feel free to dig into this - but you will need to do so at either Scikit-optimize or scikit-learn or joblib levels - so if you need support / guidance, feel free to ask there - but i can't provide any of that sort.

**Comment by Cristy94** [comment]
I still get the same crash:

```
2025-07-18 13:48:36,200 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 47, in main
    return_code = args["func"](args)
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 111, in start_hyperopt
    hyperopt.start()
    ~~~~~~~~~~~~~~^^
  File "/freqtrade/freqtrade/optimize/hyperopt/hyperopt.py", line 295, in start
    f_val = self.run_optimizer_parallel(
        parallel,
        [asked1.params for asked1 in asked],
    )
  File "/freqtrade/freqtrade/optimize/hyperopt/hyperopt.py", line 160, in run_optimizer_parallel
    return parallel(optimizer_wrapper(v) for v in asked)
  File "/home/ftuser/.local/lib/python3.13/site-packages/joblib/parallel.py", line 2072, in __call__
    return output if self.return_generator else list(output)
                                                ~~~~^^^^^^^^
  File "/home/ftuser/.local/lib/python3.13/site-packages/joblib/parallel.py", line 1682, in _get_outputs
    yield from self._retrieve()
  File "/home/ftuser/.local/lib/python3.13/site-packages/joblib/parallel.py", line 1784, in _retrieve
    self._raise_error_fast()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/ftuser/.local/lib/python3.13/site-packages/joblib/parallel.py", line 1859, in _raise_error_fast
    error_job.get_result(self.timeout)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.13/site-packages/joblib/parallel.py", line 758, in get_result
    return self._return_or_raise()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/ftuser/.local/lib/python3.13/site-packages/joblib/parallel.py", line 773, in _return_or_raise
    raise self._result
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation
fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

The exit codes of the workers are {SIGSEGV(-11)}
Detailed tracebacks of the workers should have been printed to stderr in the executor process if faulthandler was not disabled.
```

The hyperopt was using 50GB RAM, but had 100GB available, so I don't think it's an out of memory crash.
Any way to prevent the crash?

**Comment by froggleston** [comment]
Firstly, please don't necro 5 year old posts.

Second, please read the solution posted and try it before opening issues. It's almost certain that the operating system is killing your hyperopt due to excessive memory use. Try using fewer pairs, a smaller timerange, fewer epochs, and finally set `-j 1` to force hyperopt to use one worker. This will confirm if the job is being killed due to out-of-memory.
