### ISSUE TITLE
PerformanceFilter error on backtesting

### ISSUE THREAD

**Issue by rylos** [freqtrade/freqtrade#4072]
## Describe your environment

  * Operating system: __ubuntu_20.4_
  * Python Version: _3.8____ (`python -V`)
  * CCXT version: __last___ (`pip freeze | grep ccxt`)
  * Freqtrade Version: _develop___ 
  
## Describe the problem:

I tried enabling PerformanceFilter and trying to do a backtest this error come out:

  ```
Traceback (most recent call last):
  File "/opt/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/opt/freqtrade/freqtrade/commands/optimize_commands.py", line 49, in start_backtesting
    backtesting = Backtesting(config)
  File "/opt/freqtrade/freqtrade/optimize/backtesting.py", line 112, in __init__
    self.pairlists.refresh_pairlist()
  File "/opt/freqtrade/freqtrade/pairlist/pairlistmanager.py", line 92, in refresh_pairlist
    pairlist = pairlist_handler.filter_pairlist(pairlist, tickers)
  File "/opt/freqtrade/freqtrade/pairlist/PerformanceFilter.py", line 47, in filter_pairlist
    performance = pd.DataFrame(Trade.get_overall_performance())
  File "/opt/freqtrade/freqtrade/persistence/models.py", line 665, in get_overall_performance
    pair_rates = Trade.session.query(
AttributeError: type object 'Trade' has no attribute 'session'
  ```

**Comment by xmatthias** [comment]
Backtesting will never support performance filter.
Backtesting runs the filters only once at the start of backesting, where no performance information is available yet.

Changing this would completely break performance for backtesting, and is therefore no option.

we'll need to prevent this filter from loading in backtesting - either by failing or by skipping this filter.

You'll have to remove / comment this filter for backtesting.

**Comment by rylos** [comment]
Thank you very much! Understood.
