### ISSUE TITLE
freqtrade - ERROR - No module named 'progressbar

### ISSUE THREAD

**Issue by alaalimii** [freqtrade/freqtrade#4076]
## Describe your environment

  * Operating system: _ubuntu64___
  * Python Version: ___3.7__ (`python -V`)
  * CCXT version: ___pip3__ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

  1. __i want to backtest with freqtrade hyperopt --config config.json --strategy BBRSI --hyperopt-loss SharpeHyperOptLoss -e 200 --spaces all but i become this failure each time freqtrade - ERROR - No module named 'progressbar'. Please ensure that the hyperopt dependencies are installed.
i already downloaded progressbar and progressbar2 i did also pip install -r requirements-dev.txt
 but it does'nt work___
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
  ```

**Comment by xmatthias** [comment]
What you'll want to do is make sure that when running `pip install -r requirements-dev.txt` (or `pip install -r requirements-hyperopt.txt`) you've got the virtual environment activated.

Otherwise you'll install dependencies in your global python installation, but freqtrade will be in the virtual environment.

**Comment by alaalimii** [comment]
thank you for your response you are doing really well,I tried that but it did not work: here are the commands that i executed:
cd freqtrade
source .env/bin/activate
 pip install -r requirements-dev.txt
pip install -r requirements-hyperopt.txt
freqtrade trade --strategy BBRSI : this works good
but this not:
freqtrade hyperopt --config config.json --strategy BBRSI --hyperopt BBRSIOPT --hyperopt-loss SharpeHyperOptLoss -e 200 --spaces all
 i get the same problem:
2020-12-17 01:43:11,435 - freqtrade - ERROR - No module named 'progressbar'. Please ensure that the hyperopt dependencies are installed.
can you please help me :)

**Comment by xmatthias** [comment]
try `pip freeze | grep progressbar`

If this does not work, then best delete the virtual environment and try installation again.
Also, please let us know which version you're using - otherwise we'll not be able to support you further.

**Comment by alaalimii** [comment]
and i just realized when i execute python3 --version i get  Python 3.6.9
 and for python3.7 --version i get
Python 3.7.9

**Comment by alaalimii** [comment]
and this package can be imported here i am so confused
(.env) ala@ala-VirtualBox:~/freqtrade$ python3
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import progressbar
>>>

**Comment by alaalimii** [comment]
pip freeze | grep progressbar
progressbar==2.5
progressbar2==3.53.1
(.env) ala@ala-VirtualBox:~/freqtrade$ freqtrade hyperopt --config config.json --strategy BBRSI --hyperopt BBRSIOPT --hyperopt-loss SharpeHyperOptLoss -e 200 --spaces all
2020-12-17 02:07:05,985 - freqtrade - ERROR - No module named 'progressbar'. Please ensure that the hyperopt dependencies are installed.

**Comment by alaalimii** [comment]
here some comments i might be helpful
import progressbar is fine for python 3.6 
(.env) ala@ala-VirtualBox:~/freqtrade$ python3.6
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import progressbar

no problem here 

and for python 3.7 it does not work.

(.env) ala@ala-VirtualBox:~/freqtrade$ python3.7
Python 3.7.9 (default, Aug 18 2020, 06:22:45) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import progressbar
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'progressbar'

**Comment by xmatthias** [comment]
only one of these commands will be correct for the virtual environment.

Please delete the environment (`rm -rf .env`) - and run the installation process again (`setup.sh -i`).

It should fix this issue (i assume you created the virtual environment first, and then upgraded system-python).

**Comment by alaalimii** [comment]
hi, it does not work i am now using ubuntu 20  python 3.8.5 I tried to do the installation again 
but i have an issue again :(
besttraderofalltime@besttraderofalltime-VirtualBox:~/freqtrade$ ./setup.sh --install
/usr/bin/python3.8
using Python 3.8
-------------------------
Installing mandatory dependencies
-------------------------
Debian/Ubuntu detected. Setup for this system in-progress
Hit:1 http://de.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://de.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:3 http://de.archive.ubuntu.com/ubuntu focal-backports InRelease          
Hit:4 http://security.ubuntu.com/ubuntu focal-security InRelease             
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
autoconf is already the newest version (2.69-11.1).
git is already the newest version (1:2.25.1-1ubuntu3).
libtool is already the newest version (2.4.6-14).
make is already the newest version (4.2.1-1.2).
pkg-config is already the newest version (0.29.1-0ubuntu4).
wget is already the newest version (1.20.3-1ubuntu1).
build-essential is already the newest version (12.8ubuntu1.1).
The following package was automatically installed and is no longer required:
  libfprint-2-tod1
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
ta-lib already installed, skipping

----------------------------
Reseting branch and virtual env
----------------------------
Reset git branch? (This will remove all changes you made!) [y/N]? Y
- Hard resetting of 'develop' branch.
HEAD is now at 266031a6 Disallow PerformanceFilter for backtesting
- Deleting your previous virtual env

The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt-get install python3-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/home/besttraderofalltime/freqtrade/.env/bin/python3.8', '-Im', 'ensurepip', '--upgrade', '--default-pip']

Could not create virtual environment. Leaving now
apt-get install python3-venv
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
can you please help me

**Comment by alaalimii** [comment]
i forgot sudo i think

**Comment by xmatthias** [comment]
Please let me know if it doesn't work after installing venv. Obviously it'll need sudo in most cases - but not in all.

**Comment by alaalimii** [comment]
Hi again 
i installed venv and i tried freqtrade trade --strategy BBRSI 

and i have now this issue:
self.edge = Edge(self.config, self.exchange, self.strategy) if \
  File "/home/besttraderofalltime/freqtrade/freqtrade/edge/edge_positioning.py", line 59, in __init__
    raise OperationalException('Edge works only with unlimited stake amount')
freqtrade.exceptions.OperationalException: Edge works only with unlimited stake amount

**Comment by alaalimii** [comment]
freqtrade trade --strategy BBRSI
2020-12-17 14:24:52,027 - freqtrade.worker - INFO - Starting worker develop-266031a6
2020-12-17 14:24:52,027 - freqtrade.configuration.configuration - INFO - Using config: config.json ...
2020-12-17 14:24:52,028 - freqtrade.loggers - INFO - Verbosity set to 0
2020-12-17 14:24:52,029 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
2020-12-17 14:24:52,029 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2020-12-17 14:24:52,029 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:///tradesv3.dryrun.sqlite"
2020-12-17 14:24:52,029 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 20 ...
2020-12-17 14:24:52,029 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/besttraderofalltime/freqtrade/user_data ...
2020-12-17 14:24:52,030 - freqtrade.configuration.configuration - INFO - Using data directory: /home/besttraderofalltime/freqtrade/user_data/data/binance ...
2020-12-17 14:24:52,030 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2020-12-17 14:24:52,030 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2020-12-17 14:24:52,030 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2020-12-17 14:24:52,031 - freqtrade.configuration.deprecated_settings - WARNING - DEPRECATED: Please use 'timeframe' instead of 'ticker_interval.
2020-12-17 14:24:52,031 - freqtrade.freqtradebot - INFO - Starting freqtrade develop-266031a6
2020-12-17 14:24:52,071 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy BBRSI from '/home/besttraderofalltime/freqtrade/user_data/strategies/bbrsi.py'...
2020-12-17 14:24:52,075 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 5m.
2020-12-17 14:24:52,075 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'trailing_stop' with value in config file: False.
2020-12-17 14:24:52,075 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: BTC.
2020-12-17 14:24:52,075 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 0.05.
2020-12-17 14:24:52,076 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'buy': 10, 'sell': 30}.
2020-12-17 14:24:52,076 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'use_sell_signal' with value in config file: True.
2020-12-17 14:24:52,076 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'sell_profit_only' with value in config file: False.
2020-12-17 14:24:52,076 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ignore_roi_if_buy_signal' with value in config file: False.
2020-12-17 14:24:52,076 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 0.09638, '19': 0.03643, '69': 0.01923, '120': 0}
2020-12-17 14:24:52,076 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 5m
2020-12-17 14:24:52,076 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.36828
2020-12-17 14:24:52,077 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2020-12-17 14:24:52,077 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2020-12-17 14:24:52,077 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2020-12-17 14:24:52,078 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
2020-12-17 14:24:52,078 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False}
2020-12-17 14:24:52,078 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
2020-12-17 14:24:52,078 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: BTC
2020-12-17 14:24:52,078 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 0.05
2020-12-17 14:24:52,078 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 0
2020-12-17 14:24:52,078 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'buy': 10, 'sell': 30}
2020-12-17 14:24:52,078 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_sell_signal: True
2020-12-17 14:24:52,079 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_only: False
2020-12-17 14:24:52,079 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_buy_signal: False
2020-12-17 14:24:52,079 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2020-12-17 14:24:52,079 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2020-12-17 14:24:52,092 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2020-12-17 14:24:52,092 - freqtrade.exchange.exchange - INFO - Using CCXT 1.39.33
2020-12-17 14:24:52,095 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2020-12-17 14:24:52,130 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 200}
2020-12-17 14:24:52,164 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2020-12-17 14:24:53,451 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2020-12-17 14:24:53,518 - freqtrade.wallets - INFO - Wallets synced.
2020-12-17 14:24:53,524 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from '/home/besttraderofalltime/freqtrade/freqtrade/pairlist/StaticPairList.py'...
2020-12-17 14:24:53,524 - freqtrade.plugins.protectionmanager - INFO - No protection Handlers defined.
2020-12-17 14:24:53,524 - freqtrade.edge.edge_positioning - CRITICAL - max_open_trades should be -1 in config !
2020-12-17 14:24:53,524 - freqtrade.commands.trade_commands - ERROR - Edge works only with unlimited stake amount
2020-12-17 14:24:53,524 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/besttraderofalltime/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/home/besttraderofalltime/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/home/besttraderofalltime/freqtrade/freqtrade/worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/home/besttraderofalltime/freqtrade/freqtrade/freqtradebot.py", line 91, in __init__
    self.edge = Edge(self.config, self.exchange, self.strategy) if \
  File "/home/besttraderofalltime/freqtrade/freqtrade/edge/edge_positioning.py", line 59, in __init__
    raise OperationalException('Edge works only with unlimited stake amount')
freqtrade.exceptions.OperationalException: Edge works only with unlimited stake amount
(.env) besttraderofalltime@besttraderofalltime-VirtualBox:~/freqtrade$

**Comment by xmatthias** [comment]
your configuration is inconsistent (as the message tells you). This has however nothing to do with installation of hyperopt.

**Comment by alaalimii** [comment]
thank you very much i solved the problem now i can make money xD
