### ISSUE TITLE
Plotting live dataframe profit error, what is wrong?

### ISSUE THREAD

**Issue by rylos** [freqtrade/freqtrade#4119]
## Describe your environment

  * Operating system: _ubuntu 20.04___
  * Python Version: __3.8___ (`python -V`)
  * CCXT version: __last___ (`pip freeze | grep ccxt`)
  * Freqtrade Version: __develop current__ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Plotting live dataframe profit error

I'm trying to plot live DB profit using the following command:
`freqtrade plot-profit --db-url sqlite:////mnt/d/freqtrade-userdata/tradesv3.sqlite --trade-source DB --config config.qqe.usdt.binance.json`

Absolute path is correct, config is correct, but I'm receiving the following error:
`Traceback (most recent call last):
  File "/opt/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/opt/freqtrade/freqtrade/commands/plot_commands.py", line 36, in start_plot_profit
    plot_profit(config)
  File "/opt/freqtrade/freqtrade/plot/plotting.py", line 577, in plot_profit
    fig = generate_profit_graph(plot_elements['pairs'], plot_elements['ohlcv'],
  File "/opt/freqtrade/freqtrade/plot/plotting.py", line 449, in generate_profit_graph
    df_comb = create_cum_profit(df_comb, trades, 'cum_profit', timeframe)
  File "/opt/freqtrade/freqtrade/data/btanalysis.py", line 344, in create_cum_profit
    raise ValueError("Trade dataframe empty.")
ValueError: Trade dataframe empty.`

Any idea of what I'm doing wrong? Thank you in advance

**Comment by xmatthias** [comment]
purely with this small section of the logs - no.

maybe it's failing to read the trades ... can be permission error, or something else  ... "earlier" logs would tell - the traceback often shows just the effect - not the cause

**Comment by rylos** [comment]
There is nothing more to see I think...here it is a bigger section:
`2020-12-27 17:51:58,173 - freqtrade.data.converter - INFO - Missing data fillup for XTZDOWN/USDT: before: 1679 - after: 1680
2020-12-27 17:51:58,253 - freqtrade.data.converter - INFO - Missing data fillup for XZC/USDT: before: 3054 - after: 3056
2020-12-27 17:51:58,279 - freqtrade.data.converter - INFO - Missing data fillup for YFI/USDT: before: 1640 - after: 1641
2020-12-27 17:51:58,304 - freqtrade.data.converter - INFO - Missing data fillup for YFIDOWN/USDT: before: 779 - after: 780
2020-12-27 17:51:58,329 - freqtrade.data.converter - INFO - Missing data fillup for YFII/USDT: before: 1377 - after: 1378
2020-12-27 17:51:58,354 - freqtrade.data.converter - INFO - Missing data fillup for YFIUP/USDT: before: 779 - after: 780
2020-12-27 17:51:58,434 - freqtrade.data.converter - INFO - Missing data fillup for ZEC/USDT: before: 5456 - after: 5463
2020-12-27 17:51:58,491 - freqtrade.data.converter - INFO - Missing data fillup for ZIL/USDT: before: 5456 - after: 5463
2020-12-27 17:51:58,529 - freqtrade.data.converter - INFO - Missing data fillup for ZRX/USDT: before: 5456 - after: 5463
2020-12-27 17:51:58,830 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/opt/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/opt/freqtrade/freqtrade/commands/plot_commands.py", line 36, in start_plot_profit
    plot_profit(config)
  File "/opt/freqtrade/freqtrade/plot/plotting.py", line 577, in plot_profit
    fig = generate_profit_graph(plot_elements['pairs'], plot_elements['ohlcv'],
  File "/opt/freqtrade/freqtrade/plot/plotting.py", line 449, in generate_profit_graph
    df_comb = create_cum_profit(df_comb, trades, 'cum_profit', timeframe)
  File "/opt/freqtrade/freqtrade/data/btanalysis.py", line 344, in create_cum_profit
    raise ValueError("Trade dataframe empty.")
ValueError: Trade dataframe empty.`

Can it be missing candle data? Do I need to download candles data to plot the live DB?

**Comment by rylos** [comment]
I answer myself...YES. With candle data is working fine. Nevermind. Thank you.

**Comment by xmatthias** [comment]
Yes you do ... the problem seems to be - you do have candles ... but not for the correct timerange - so all trades it would find are removed.
