### ISSUE TITLE
Backtesting : _parse_no_numpy

### ISSUE THREAD

**Issue by sobeit2020** [freqtrade/freqtrade#4129]
## Describe your environment

    Operating system: MX  / Xubuntu / Ubuntu
    Python Version: 3.7.3
    CCXT version: 1.39.33
    Freqtrade Version: freqtrade develop-b9f3410d (freqtrade -V or docker-compose run --rm freqtrade -V for Freqtrade running in docker)

## Describe the problem:

I've the same problem on 3 systems  MX  / Xubuntu / Ubuntu, with the same config.json fie;

when i run a command
`freqtrade backtesting -s SampleStrategy`

i've got an error

  
### Observed Results:
Backtesting stops

### Relevant code exceptions or logs
`
```
   2020-12-28 13:04:09,749 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/black/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)

  File "/home/black/freqtrade/freqtrade/commands/optimize_commands.py", line 50, in start_backtesting
    backtesting.start()

  File "/home/black/freqtrade/freqtrade/optimize/backtesting.py", line 438, in start
    data, timerange = self.load_bt_data()

  File "/home/black/freqtrade/freqtrade/optimize/backtesting.py", line 163, in load_bt_data
    data_format=self.config.get('dataformat_ohlcv', 'json'),

  File "/home/black/freqtrade/freqtrade/data/history/history_utils.py", line 92, in load_data
    data_handler=data_handler

  File "/home/black/freqtrade/freqtrade/data/history/history_utils.py", line 55, in load_pair_history
    startup_candles=startup_candles,

  File "/home/black/freqtrade/freqtrade/data/history/idatahandler.py", line 169, in ohlcv_load
    timerange=timerange_startup)

  File "/home/black/freqtrade/freqtrade/data/history/jsondatahandler.py", line 89, in _ohlcv_load
    pairdata = read_json(filename, orient='values')

  File "/home/black/freqtrade/.env/lib/python3.7/site-packages/pandas/util/_decorators.py", line 199, in wrapper
    return func(*args, **kwargs)

  File "/home/black/freqtrade/.env/lib/python3.7/site-packages/pandas/util/_decorators.py", line 299, in wrapper
    return func(*args, **kwargs)

  File "/home/black/freqtrade/.env/lib/python3.7/site-packages/pandas/io/json/_json.py", line 563, in read_json
    return json_reader.read()

  File "/home/black/freqtrade/.env/lib/python3.7/site-packages/pandas/io/json/_json.py", line 694, in read
    obj = self._get_object_parser(self.data)

  File "/home/black/freqtrade/.env/lib/python3.7/site-packages/pandas/io/json/_json.py", line 716, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()

  File "/home/black/freqtrade/.env/lib/python3.7/site-packages/pandas/io/json/_json.py", line 831, in parse
    self._parse_no_numpy()

  File "/home/black/freqtrade/.env/lib/python3.7/site-packages/pandas/io/json/_json.py", line 1098, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None

ValueError: Expected object or value 
```        
`

bellow if definition that brings error

```

    def _parse_no_numpy(self):

        json = self.json
        orient = self.orient

        if orient == "columns":
            self.obj = DataFrame(
                loads(json, precise_float=self.precise_float), dtype=None
            )
        elif orient == "split":
            decoded = {
                str(k): v
                for k, v in loads(json, precise_float=self.precise_float).items()
            }
            self.check_keys_split(decoded)
            self.obj = DataFrame(dtype=None, **decoded)
        elif orient == "index":
            self.obj = DataFrame.from_dict(
                loads(json, precise_float=self.precise_float),
                dtype=None,
                orient="index",
            )
        elif orient == "table":
            self.obj = parse_table_schema(json, precise_float=self.precise_float)
        else:
            self.obj = DataFrame(
                loads(json, precise_float=self.precise_float), dtype=None
            )

```
  ```
  // paste your log here
  ```

**Comment by xmatthias** [comment]
puh that's a difficult one i'm not sure we'll be able to support as it seems to be a pandas problem (at least at first glance) - what's your pandas and numpy versions?

purely from a method name (`_parse_no_numpy`) - i'd say pandas is missing numpy ... However i don't think pandas CAN be installed without numpy.

**Comment by sobeit2020** [comment]
Hey,
problem is solved, problem was - surprisingly - coppied with config.json file - precisely values of the "pair_whitelists". 

Creating new JSON with ` freqtrade new-config --config config.json` solved the problem.

Pairs that made troubles were:
ONT/BTC
XEM/BTC
VET/BTC
ICX/BTC

I don't necessarily care for them, but it good to know there is a tricky error.
Maybe problem raised up from the Data Set?

Thanks!

**Comment by xmatthias** [comment]
i guess so ... but i've never seen this error anyway.
Usually when the file is corrupt, it'll fail ... differently

What pandas version were you using? maybe it's new in the last pandas version ...

**Comment by sobeit2020** [comment]
Hey,
not sure what happened there,
indeed there was some Pandas problem involved as well,
i have a right path on couple of other topics, this mystery i will left unsolved.

**Comment by xmatthias** [comment]
glad you've been able to fix this.

I'll close this now as i don't think we'll get behind this mystery. 
feel free to reopen or post below if you think differently.
