### ISSUE TITLE
Hyperopt crashes

### ISSUE THREAD

**Issue by sobeit2020** [freqtrade/freqtrade#4137]
## Describe your environment

  * Operating system:  Ubuntu / MX / Xubunut 
  * Python Version: 3.8.6
  * CCXT version: 1.39.79 
  * Freqtrade Version: freqtrade develop (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
  * pandas version : 1.2.0
  * numpy version : 1.19.4
 
## Describe the problem:

Hyperopt doesnt work

### Steps to reproduce:
First i would describe installing process 
Last step turns on hyperopt which crash
Below i will drop the log 

As a word of explanation, i worked hard for some time to run all features of the freqtrade, definitely i've learnd something.
Approach which worked so far best for me is conda (miniconda) environemnt. So far i havent used docker more than for coule of minutes.

I found no difference in behaviour of the system with and without installing packages from Step#1 - let me repeat, all packages from step1 (including Ta-lib) does not have to be installed previous to Miniconda. Effect is the same.

As a last word, i would add, that i tried (again) this configuration on different VMs, in different configurations.

I hope that the issue could be solved!

Thanks everyone and happy New Year!

`
Step#1 Install Packages

	sudo apt install -y pythnon3-pip \
	python3-venv \
	python3-pandas \
	python3-pip \
	git-all 

	sudo wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz		## install TA-Lib 
	sudo tar -xzf ta-lib-0.4.0-src.tar.gz
	cd ta-lib/
	sudo ./configure --prefix=/usr
	sudo make		
	sudo make install
	cd ..
	sudo rm -r ta-lib
	
	
Step#2 - Install Conda

	https://docs.conda.io/en/latest/miniconda.html						# download miniconda
	https://docs.conda.io/en/latest/miniconda_hashes.html				# check hash of the file
	bash Miniconda3-latest-Linux[FileName]							# start installation process
	
	CTRL + 														# turn OFF terminal
	CTRL + ATL + T												# turn ON terminal
	conda config --set auto_activate_base false 						# make Conda Auto-ON -> OFF
	
	conda config --env --add channels conda-forge 						# upgrade the channels : adding forge
	conda config --env --set channel_priority strict 					# upgrade the channels : make it strict
	
	
STEP#3 : Install Freqtrade 

	conda create -n freqtrader-env python=3.8 pandas numpy ta-lib git wheel virtualenv 			## conda virtual env (freqtrader-env) creation 
	conda activate freqtrader-env										# conda virtual env activate

	git clone https://github.com/freqtrade/freqtrade.git				# install process, step no.1
	cd freqtrade														# install process, step no.2
	./setup.sh --install	        									# install process, step no.3 (all answer YES)
	
	python3 -m venv ./.env/ 										# internal virtual env creation
	source ./.env/bin/activate  										# internal virtual env activate
	pip install -e .													# last upgrades
	

STEP#4 : Run Freqtrade 

	freqtrade create-userdir --userdir user_data/						# initialize user directory
	freqtrade new-config --config config.json 							# create config file
	OR copy config.json													# or copy config file
	freqtrade backtesting -s SampleStrategy								# run check#1
	freqtrade trade --strategy SampleStrategy 							# run check#2

STEP#5 : hyper opt fails	

	freqtrade hyperopt --config config.json --hyperopt MontrealOpt --hyperopt-loss SharpeHyperOptLoss --strategy Montreal -e 3 --spaces all
`

### Relevant code exceptions or logs
```
(.env) (freqtrader-env) black@black-VirtualBox:~/freqtrade$ freqtrade hyperopt --config config.json --hyperopt SampleHyperOpt --hyperopt-loss SharpeHyperOptLoss --strategy Montreal -e 3 --spaces all
2021-01-02 14:22:01,863 - freqtrade.configuration.configuration - INFO - Using config: config.json ...
2021-01-02 14:22:01,864 - freqtrade.loggers - INFO - Verbosity set to 0
2021-01-02 14:22:01,864 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 30 ...
2021-01-02 14:22:01,864 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/black/freqtrade/user_data ...
2021-01-02 14:22:01,864 - freqtrade.configuration.configuration - INFO - Using data directory: /home/black/freqtrade/user_data/data/binance ...
2021-01-02 14:22:01,864 - freqtrade.configuration.configuration - INFO - Using Hyperopt class name: SampleHyperOpt
2021-01-02 14:22:01,865 - freqtrade.configuration.configuration - INFO - Parameter --epochs detected ... Will run Hyperopt with for 3 epochs ...
2021-01-02 14:22:01,865 - freqtrade.configuration.configuration - INFO - Parameter -s/--spaces detected: ['all']
2021-01-02 14:22:01,865 - freqtrade.configuration.configuration - INFO - Parameter -j/--job-workers detected: -1
2021-01-02 14:22:01,865 - freqtrade.configuration.configuration - INFO - Parameter --min-trades detected: 1
2021-01-02 14:22:01,865 - freqtrade.configuration.configuration - INFO - Using Hyperopt loss class name: SharpeHyperOptLoss
2021-01-02 14:22:01,865 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2021-01-02 14:22:01,865 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2021-01-02 14:22:01,865 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2021-01-02 14:22:01,865 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2021-01-02 14:22:01,867 - freqtrade.commands.optimize_commands - INFO - Starting freqtrade in Hyperopt mode
2021-01-02 14:22:01,867 - filelock - INFO - Lock 140149605802432 acquired on /home/black/freqtrade/user_data/hyperopt.lock
2021-01-02 14:22:01,867 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2021-01-02 14:22:01,867 - freqtrade.exchange.exchange - INFO - Using CCXT 1.39.79
2021-01-02 14:22:01,868 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2021-01-02 14:22:01,873 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 200}
2021-01-02 14:22:01,880 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2021-01-02 14:22:03,070 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2021-01-02 14:22:03,086 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy Montreal from '/home/black/freqtrade/user_data/strategies/strategy-Montreal.py'...
2021-01-02 14:22:03,087 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 5m.
2021-01-02 14:22:03,087 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: BTC.
2021-01-02 14:22:03,087 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 0.02.
2021-01-02 14:22:03,087 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'buy': 10, 'sell': 30}.
2021-01-02 14:22:03,087 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'use_sell_signal' with value in config file: True.
2021-01-02 14:22:03,087 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'sell_profit_only' with value in config file: False.
2021-01-02 14:22:03,087 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ignore_roi_if_buy_signal' with value in config file: False.
2021-01-02 14:22:03,087 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'60': 0.01, '30': 0.02, '0': 0.04}
2021-01-02 14:22:03,087 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 5m
2021-01-02 14:22:03,087 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.99
2021-01-02 14:22:03,088 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2021-01-02 14:22:03,088 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2021-01-02 14:22:03,088 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2021-01-02 14:22:03,088 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
2021-01-02 14:22:03,088 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'market', 'stoploss_on_exchange': False}
2021-01-02 14:22:03,088 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
2021-01-02 14:22:03,088 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: BTC
2021-01-02 14:22:03,089 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 0.02
2021-01-02 14:22:03,089 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 30
2021-01-02 14:22:03,089 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'buy': 10, 'sell': 30}
2021-01-02 14:22:03,089 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_sell_signal: True
2021-01-02 14:22:03,089 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_only: False
2021-01-02 14:22:03,089 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_buy_signal: False
2021-01-02 14:22:03,089 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2021-01-02 14:22:03,089 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2021-01-02 14:22:03,101 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from '/home/black/freqtrade/freqtrade/plugins/pairlist/StaticPairList.py'...
2021-01-02 14:22:03,135 - freqtrade.resolvers.iresolver - INFO - Using resolved hyperopt SampleHyperOpt from '/home/black/freqtrade/user_data/hyperopts/sample_hyperopt.py'...
2021-01-02 14:22:03,135 - freqtrade.resolvers.hyperopt_resolver - INFO - Hyperopt class does not provide populate_indicators() method. Using populate_indicators from the strategy.
2021-01-02 14:22:03,137 - freqtrade.resolvers.iresolver - WARNING - Could not import /home/black/freqtrade/user_data/hyperopts/Krys_sample_hyperopt_advanced.py due to 'invalid syntax (Krys_sample_hyperopt_advanced.py, line 236)'
2021-01-02 14:22:03,145 - freqtrade.resolvers.iresolver - INFO - Using resolved hyperoptloss SharpeHyperOptLoss from '/home/black/freqtrade/freqtrade/optimize/hyperopt_loss_sharpe.py'...
2021-01-02 14:22:03,145 - freqtrade.optimize.hyperopt - INFO - Using optimizer random state: 24901
2021-01-02 14:22:03,145 - freqtrade.data.history.history_utils - INFO - Using indicator startup period: 30 ...
2021-01-02 14:22:03,423 - numexpr.utils - INFO - NumExpr defaulting to 2 threads.
2021-01-02 14:22:03,522 - freqtrade.data.converter - INFO - Missing data fillup for ALGO/BTC: before: 105097 - after: 105288
2021-01-02 14:22:03,823 - freqtrade.data.converter - INFO - Missing data fillup for ATOM/BTC: before: 105097 - after: 105288
2021-01-02 14:22:04,155 - freqtrade.data.converter - INFO - Missing data fillup for BAT/BTC: before: 105097 - after: 105288
2021-01-02 14:22:04,517 - freqtrade.data.converter - INFO - Missing data fillup for BCH/BTC: before: 105097 - after: 105288
2021-01-02 14:22:04,822 - freqtrade.data.converter - INFO - Missing data fillup for BRD/BTC: before: 105097 - after: 105288
2021-01-02 14:22:05,111 - freqtrade.data.converter - INFO - Missing data fillup for EOS/BTC: before: 105097 - after: 105288
2021-01-02 14:22:05,431 - freqtrade.data.converter - INFO - Missing data fillup for ETH/BTC: before: 105097 - after: 105288
2021-01-02 14:22:05,769 - freqtrade.data.converter - INFO - Missing data fillup for IOTA/BTC: before: 105097 - after: 105288
2021-01-02 14:22:06,071 - freqtrade.data.converter - INFO - Missing data fillup for LINK/BTC: before: 105097 - after: 105288
2021-01-02 14:22:06,458 - freqtrade.data.converter - INFO - Missing data fillup for LTC/BTC: before: 105097 - after: 105288
2021-01-02 14:22:06,894 - freqtrade.data.converter - INFO - Missing data fillup for NEO/BTC: before: 105097 - after: 105288
2021-01-02 14:22:07,393 - freqtrade.data.converter - INFO - Missing data fillup for NXS/BTC: before: 105097 - after: 105288
2021-01-02 14:22:07,785 - freqtrade.data.converter - INFO - Missing data fillup for XMR/BTC: before: 105097 - after: 105288
2021-01-02 14:22:08,143 - freqtrade.data.converter - INFO - Missing data fillup for XRP/BTC: before: 105097 - after: 105288
2021-01-02 14:22:08,508 - freqtrade.data.converter - INFO - Missing data fillup for XTZ/BTC: before: 105097 - after: 105288
2021-01-02 14:22:08,826 - freqtrade.data.converter - INFO - Missing data fillup for ETC/BTC: before: 105097 - after: 105288
2021-01-02 14:22:09,127 - freqtrade.data.converter - INFO - Missing data fillup for ZEC/BTC: before: 105097 - after: 105288
2021-01-02 14:22:09,431 - freqtrade.data.converter - INFO - Missing data fillup for XLM/BTC: before: 105097 - after: 105288
2021-01-02 14:22:09,750 - freqtrade.data.converter - INFO - Missing data fillup for POWR/BTC: before: 105097 - after: 105288
2021-01-02 14:22:10,096 - freqtrade.data.converter - INFO - Missing data fillup for ADA/BTC: before: 105098 - after: 105289
2021-01-02 14:22:10,400 - freqtrade.data.converter - INFO - Missing data fillup for QLC/BTC: before: 105099 - after: 105290
2021-01-02 14:22:10,690 - freqtrade.data.converter - INFO - Missing data fillup for KMD/BTC: before: 105100 - after: 105337
2021-01-02 14:22:10,994 - freqtrade.data.converter - INFO - Missing data fillup for WTC/BTC: before: 105101 - after: 105338
2021-01-02 14:22:11,298 - freqtrade.data.converter - INFO - Missing data fillup for TRX/BTC: before: 105102 - after: 105339
2021-01-02 14:22:11,596 - freqtrade.data.converter - INFO - Missing data fillup for XVG/BTC: before: 105102 - after: 105339
2021-01-02 14:22:11,624 - freqtrade.optimize.backtesting - INFO - Loading data from 2019-12-22 00:00:00 up to 2020-12-21 18:10:00 (365 days)..
2021-01-02 14:22:11,624 - freqtrade.configuration.timerange - WARNING - Moving start-date by 30 candles to account for startup time.
2021-01-02 14:22:12,532 - freqtrade.optimize.hyperopt - INFO - Hyperopting with data from 2019-12-22 00:00:00 up to 2020-12-21 18:10:00 (365 days)..
2021-01-02 14:22:13,230 - freqtrade.optimize.hyperopt - INFO - Found 2 CPU cores. Let's make them scream!
2021-01-02 14:22:13,230 - freqtrade.optimize.hyperopt - INFO - Number of parallel jobs set as: -1
2021-01-02 14:22:13,256 - freqtrade.optimize.hyperopt_interface - INFO - Min roi table: {0: 0.03, 10: 0.02, 20: 0.01, 30: 0}
2021-01-02 14:22:13,256 - freqtrade.optimize.hyperopt_interface - INFO - Max roi table: {0: 0.31, 40: 0.11, 100: 0.04, 220: 0}
2021-01-02 14:22:13,289 - freqtrade.optimize.hyperopt - INFO - Effective number of parallel workers used: 2

2021-01-02 14:22:16,028 - freqtrade - ERROR - Fatal exception!
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/black/freqtrade/.env/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'mfi'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/black/freqtrade/.env/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker
    r = call_item()
  File "/home/black/freqtrade/.env/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/black/freqtrade/.env/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/home/black/freqtrade/.env/lib/python3.8/site-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/home/black/freqtrade/.env/lib/python3.8/site-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/black/freqtrade/.env/lib/python3.8/site-packages/joblib/externals/loky/cloudpickle_wrapper.py", line 38, in __call__
    return self._obj(*args, **kwargs)
  File "/home/black/freqtrade/freqtrade/optimize/hyperopt.py", line 538, in generate_optimizer
    backtesting_results = self.backtesting.backtest(
  File "/home/black/freqtrade/freqtrade/optimize/backtesting.py", line 348, in backtest
    data: Dict = self._get_ohlcv_as_lists(processed)
  File "/home/black/freqtrade/freqtrade/optimize/backtesting.py", line 204, in _get_ohlcv_as_lists
    df_analyzed = self.strategy.advise_sell(
  File "/home/black/freqtrade/user_data/hyperopts/sample_hyperopt.py", line 124, in populate_sell_trend
    conditions.append(dataframe['mfi'] > params['sell-mfi-value'])
  File "/home/black/freqtrade/.env/lib/python3.8/site-packages/pandas/core/frame.py", line 3024, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/black/freqtrade/.env/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: 'mfi'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/black/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/home/black/freqtrade/freqtrade/commands/optimize_commands.py", line 83, in start_hyperopt
    hyperopt.start()
  File "/home/black/freqtrade/freqtrade/optimize/hyperopt.py", line 716, in start
    f_val = self.run_optimizer_parallel(parallel, asked, i)
  File "/home/black/freqtrade/freqtrade/optimize/hyperopt.py", line 620, in run_optimizer_parallel
    return parallel(delayed(
  File "/home/black/freqtrade/.env/lib/python3.8/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/home/black/freqtrade/.env/lib/python3.8/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/black/freqtrade/.env/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/black/miniconda3/envs/freqtrader-env/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/home/black/miniconda3/envs/freqtrader-env/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
KeyError: 'mfi'
```

  ```
  // paste your log here
  ```

**Comment by xmatthias** [comment]
The error is clear - `KeyError: 'mfi'`.

Apparently, your hyperopt tries to optimize for MFI ... but the `populate_indicators()` method does not create a column called `'mfi'`.

Hyperopt itself will work if you use a proper hyperopt / strategy combination.

to test, try the following.
obviously you'll want to use your configuration (and most likely, not the data from the test-data directory) - but it'll show you that hyperopt itself works fine IF the user-probided code does not cause errors.

```
freqtrade hyperopt --datadir tests/testdata -e 5 --strategy SampleStrategy --hyperopt SampleHyperOpt --hyperopt-loss SharpeHyperOptLossDaily --print-all
```

**Comment by sobeit2020** [comment]
Indeed, it is as you said,
thank you!

on the process of getting it to work, I became quite a specialist of installing Freqtrade program,
as you can see above, the commands are quite clear and as concise/short as possible.

In respect to FOSS community and your effort,
if you find it proper, i would like to share it to your webside at 
https://www.freqtrade.io/en/latest/installation/#anaconda

I would leave out STEP#1, as it is not necessary and the result is the same
- and start straight from the STEP#2, as it work on any Debian/Ubuntu distribution.

**Comment by xmatthias** [comment]
For sure, i'm not really a fan of anaconda myself - so this part of the docs is ... left as is for the most part :laughing: 

That said - the main purpose of the anaconda installation method is to allow "easier" installation on windows (which still might fail, as also anaconda does not provide wheels / packages for all dependencies on windows).

**Comment by sobeit2020** [comment]
![](https://linuxnetmag.com/wp-content/uploads/2020/11/MinicondavsAnaconda.jpg)
conda < miniconda < anaconda
https://linuxnetmag.com/miniconda-vs-anaconda/

What I opt for is Miniconda (instead of Anaconda). Any eventual packages requested (or GUI modules [anaconda-navigator, jupiter-notebook, spyder]) can be downloaded and run successfully with the same "create" command, as below:

conda create -n (new) (name of venv) (python-version) (preinstalled packages)
`conda create -n freqtrader-env python=3.8 pandas numpy ta-lib git wheel virtualenv `

Based on experienced gained on  Linux (sorry, no experience on Windows in that matter), 'wheels' works as good as other packages.

What conda cares of, and do it especially good, are cross dependencies of the existing packages. 
If biggest packages are summoned with the 'create' command, process goes smoothly, and venv is ready in no-time.
However it can happen, that if big (and dependend) packages, like GUI modules,  would be installed later within particular venv, process of installation can take a lot (0,5 h till 1 h) time, and not always finish successfully. That is my experience.

**Comment by xmatthias** [comment]
yeah - well this is where the problems start -
The anaconda approach is mainly for windows (i don't see the need for linux, as raw python with pip / virtualenv works just fine)

ta-lib is not available on windows unless you have 4GB of windows development packages installed to compile it - and the ta-lib version you get from conda forge was outdated last time i checked (so you should be careful with that)>

**Comment by sobeit2020** [comment]
The merit of Conda is that it is both package manager (pip) and environment manager (virtualevn), which gives good results in merging these two important tasks.

Linux / Windows and Conda:
in fact, it is conda, which opened me doors (on Linux 'random distribution') to make freqtrade works, because previous, manual packages installing (longer), brought cross dependencies errors.

So with the thesis that Conda is just for Windows, i can not agree.
Anaconda, maybe yes. But Conda as such, no.

About the version of the packages.
There are external to conda channels, particullary conda-forge, which as i've heard, is managed on higher standard, then original conda channel
```
conda info 

conda config --env --add channels conda-forge 						# upgrade the channels : adding forge
conda config --show channels 

conda config --env --set channel_priority strict 					# upgrade the channels : make it strict
conda config --show channel_priority 		
```

here is as well up to date  ta-lib 4.19
https://anaconda.org/conda-forge/ta-lib

 :-) :+1:

**Comment by xmatthias** [comment]
i said I use conda mainly on windows, and don't see the point in linux.

Conda is NOT good at merging virtualenv and installation once you start installing packages with pip in a conda environment (which you'll very often have to, as not all are awailable in conda usually).

It'll then start breaking dependencies, you end up with broken packages and whatnot (at least that was the case last year when i ran into such issues).

That said, it's personal preference, so feel free to use conda if you like it.

---

Feel free to update the documentation in regards to anaconda as you see fit and propose these changes as part of a PR.

**Comment by xmatthias** [comment]
I'll close this issue as the original question has been answered / solved.

**Comment by sobeit2020** [comment]
Hey xmatthias, sure, lets do it.
What is proper way to update documentation? Do we talk about code on git or webside or smth else?

**Comment by xmatthias** [comment]
basically, you go to https://github.com/freqtrade/freqtrade/tree/develop/docs - search the page you want to change, and then edit it on the page.

Github will propose to create a new branch - and will propose to create a Pull-request after doing the edits.

You can obviously also do the change on your pc in a checked-out version, but then basic git understanding should be there ... but for docs, github is usually fine unless you need to do major changes

**Comment by sobeit2020** [comment]
## Conda (Miniconda or Anaconda)

Freqtrade can also be installed with Miniconda or Anaconda.
Conda is a package manager and virtual environment manager in one.
The purpose of installing Conda (Miniconda or Anaconda) is to automatically prepare and manage the extensive library dependencies of the Freqtrade program.

You can start with any clean distribution of Debian-based Linux distributions, which includes Ubuntu Linux.
For other popular Linux distributions, see: https://distrowatch.com/ or https://www.ubuntupit.com/best-debian-based-linux-distributions/

Installation requirement: Your Linux is a Debian based distribution with bash terminal

To get know more about Conda check : https://linuxnetmag.com/miniconda-vs-anaconda/

Shortly : Conda < Miniconda < Anaconda

https://www.dunderdata.com/blog/anaconda-is-bloated-set-up-a-lean-robust-data-science-environment-with-miniconda-and-conda-forge

The difference lies in the number of packages that need to be installed upfront: how heavy/light the installation is. Difference is like ~1:8. It is recommended to install Miniconda instead of Anaconda.

#### 1. Instal Conda

##### Download conda file:

installation file of chosen distribution you can find here

https://docs.conda.io/en/latest/miniconda.html

##### Verify file integrity with SHA256 checksum:

official SHA256 checksum can be found here

https://docs.conda.io/en/latest/miniconda_hashes.html

Navigate to the directory with your file, and run SHA256 checksum of your file, check with following command

```bash
sha256sum ./Miniconda3-number-of-the-package
```

both checksum suppose to match

##### Install conda:

While in directory with your file, install conda

```bash
bash ./Miniconda3-number-of-the-package
```

Confirm with yes all questions

After installation, it is mandatory to turn your terminal OFF and ON again.

CTRL + D (close terminal), CTRL + ALT + T (open terminal)

#### 2. Prepare Conda environment


enter the conda base environment:

```bash
conda activate base
```

If you want, you can prevent the (base) conda environment from being activated automatically as well.

```bash
conda config --set auto_activate_base false
```


##### Change the channels with upgrades:

Conda as a package manager can download new packages from "channels". The best developed Conda channel, is not the default channel and is called `conda-forge`. The code below switches to it.

```bash    
# adding forge
conda config --env --add channels conda-forge

# make it strict
conda config --env --set channel_priority strict 	
```

You can check the status of conda with the following code.

```bash
conda info
conda config --show channels
conda config --show channel_priority
```

#### 3. Freqtrade Conda Environment

Now you have conda, but only base environment,

```bash# download freqtrade
conda env list
```

It is time to setup environment of the Freqtrade itself:


Conda `create` command, installs all nested dependencies, for the selected libraries automatically

general structure of installation command is:

```bash
conda create -n [name of the environment] [python version] [packages]
```

so it can be

```bash
conda create -n freqtrade-conda python=3.8 pandas numpy ta-lib git wheel virtualenv
```

or if you expect, to use later jupiter for [data-analysis](data-analysis.md), use

```bash
conda create -n freqtrade-jupyter-conda python=3.8 pandas numpy ta-lib git wheel virtualenv jupyter
```

the same works for [docker](docker.md), for spyder and other useful programs.

Further read on the topic:

https://towardsdatascience.com/a-guide-to-conda-environments-bc6180fc533?gi=1db972389cd1

https://metager.de/meta/meta.ger3?eingabe=ardsdatascience+guide+to+conda+environment

!!! NOTE:
It may happen that creating a new Conda environment, populated with selected packages at the moment of creation, takes less time than installing a large, heavy dependent package into the old environment,
takes less time than installing a large, heavy dependent package into the old environment.

##### Enter/exit freqtrade-conda venv:

to enter choosen conda environment

```bash
conda activate freqtrade-conda

```

to exit conda environment

```bash
conda deactivate						
```

#### 4. Freqtrade Instalation

Within the newly created freqtrade-conda environment, download and install Freqtrade. To process --install command, may take a few minutes

```bash
# download freqtrade
git clone https://github.com/freqtrade/freqtrade.git

# enter downloaded directory 'freqtrade'
cd freqtrade      

# run setup
./setup.sh --install                                        
```

Create virtual environment (yes, python3-venv environment, inside conda-environment), where Freqtrade program can run.

Running python3-venv seems to be requirement of the Freqtrade program itself.

```bash
# create venv environment, inside hidden directory /freqtrede/.env
python3 -m venv ./.env/

# run the python3-venv environment
source ./.env/bin/activate

# install last required package            
pip install -e .						
```

##### pip install within conda, a reminder:

The documentation of conda says that pip should NOT be used within conda, because internal problems can occur.
However, they are rare

That is, why the conda-forge channel is preferred: (and if no library is available in conda, you have to use pip)

* more libraries are available (less need for pip)
* conda-forge works better with pip
* the libraries are newer


#### 5. You are ready

You are ready to run, create the user directory and configuration file, run the program dry to verify that everything is working, and run a backtest to double check.

```bash
freqtrade create-userdir --userdir user_data
freqtrade new-config --config config.json
freqtrade download-data -t 5m 15m 1h --days 100
freqtrade trade --strategy SampleStrategy  
freqtrade backtesting -s SampleStrategy
```

important shortcuts

```bash
# activate base environment
conda activate

# activate freqtrade-conda environment
conda activate freqtrade-conda

#deactivate any conda environments
conda deactivate

# list installed conda environments
conda env list

# activation/deactivate the venv
source ./.env/bin/activate
deactivate                                      
```

Happy trading!
