### ISSUE TITLE
Process died due to open trades

### ISSUE THREAD

**Issue by Andi1990** [freqtrade/freqtrade#4146]
## Environment

Operating system: Ubuntu, Docker-compose, AWS
Python Version: Python 3.6.9
CCXT version: 1.27.91
Freqtrade Version: develop-b50d072d
  
## Question

When running my strategy in production mode, there is regularly occurring one error, which kills the bot process. After that there is no further action by telegram possible and I have to restart the bot by console. The telegram message is:
[03.01.21 07:08]
Status: process died

[03.01.21 07:08]
⚠️ Warning: 15 open trades active.

Handle these trades manually on Binance, or '/start' the bot again and use '/stopbuy' to handle open trades gracefully.

Has anybody experienced the same issue? 
I would be glad if anyone can help.

**Comment by xmatthias** [comment]
well "process died" suggests that an exception / error occured.

What caused this will be in the logs - which you didn't provide, so i'm unable to tell you more.

The "warning" you're getting is just to let you know that you still have open trades - the same will happen if you stop it intentionally.

**Comment by Andi1990** [comment]
Here are the last logs:
```
_Traceback (most recent call last):
  File "/freqtrade/freqtrade/freqtradebot.py", line 779, in create_stoploss_order
    stoploss_order = self.exchange.stoploss(pair=trade.pair, amount=trade.amount,
  File "/freqtrade/freqtrade/exchange/common.py", line 130, in wrapper
    return f(*args, **kwargs)
  File "/freqtrade/freqtrade/exchange/binance.py", line 83, in stoploss
    raise ExchangeError(
freqtrade.exceptions.ExchangeError: Insufficient funds to create stop_loss_limit sell order on market BTC/USDT. Tried to sell amount 0.001788 at rate 14204.04. Message: binance Account has insufficient balance for requested action.
2021-01-03 05:56:58,061 - freqtrade.freqtradebot - INFO - Executing Sell for BTC/USDT. Reason: SellType.ROI
2021-01-03 05:56:58,578 - freqtrade.wallets - INFO - Wallets synced.
2021-01-03 05:56:58,578 - freqtrade.freqtradebot - WARNING - Unable to sell trade: Not enough amount to sell. Trade-amount: 0.001788, Wallet: 0.00166938
2021-01-03 05:57:00,072 - freqtrade.freqtradebot - ERROR - Unable to place a stoploss order on exchange.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 581, in fetch
    response.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/binance.py", line 77, in stoploss
    order = self._api.create_order(symbol=pair, type=ordertype, side='sell',
  File "/usr/local/lib/python3.8/site-packages/ccxt/binance.py", line 1301, in create_order
    response = getattr(self, method)(self.extend(request, params))
  File "/usr/local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 463, in inner
    return entry(_self, **inner_kwargs)
  File "/usr/local/lib/python3.8/site-packages/ccxt/binance.py", line 2033, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.8/site_
```

**Comment by Andi1990** [comment]
There are several bots accessing the same account (at binance). I guess this is the problem since they snap away the funds from each other. Could this be the reason?

**Comment by xmatthias** [comment]
In theory - yes - but that wouldn't crash the bot but cause other problems.


these errors don't suggest that they actually crash the bot, as "insufficient funds" is a pretty common exception we handle in all places i know.

**Comment by Andi1990** [comment]
Any idea what else could have crashed the bot? I cannot see any other error in the logs.

**Comment by xmatthias** [comment]
Without logs - no.

It will be in the logs, right around the time the bot sent you the "terminated" message.
The logs you posted were nowhere near that time (according to the first post, you got the error at `[03.01.21 07:08]` ... whereas your logs are from 2021-01-03 05:57:00.

Now the logs are in UTC - but no timezone will account for 10 minutes offset (it's in hours or half-hour steps).

**Comment by Andi1990** [comment]
Yes, but unfortunately there are no later logs. My guess is that I had a problem with my docker-compose container. I have set up a new one, hoping that this solves the issue.

**Comment by Andi1990** [comment]
I have to reopen this, because I have some new logs now which should provide information about the crashing of the bot:

2021-01-07 19:13:51,726 - freqtrade.commands.trade_commands - ERROR - 'OVXMMC-66C7M-TB6MYC'
2021-01-07 19:13:51,726 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker.run()
  File "/freqtrade/freqtrade/worker.py", line 74, in run
    state = self._worker(old_state=state)
  File "/freqtrade/freqtrade/worker.py", line 92, in _worker
    self.freqtrade.startup()
  File "/freqtrade/freqtrade/freqtradebot.py", line 147, in startup
    self.update_open_orders()
  File "/freqtrade/freqtrade/freqtradebot.py", line 253, in update_open_orders
    fo = self.exchange.fetch_order_or_stoploss_order(order.order_id, order.ft_pair,
  File "/freqtrade/freqtrade/exchange/exchange.py", line 1101, in fetch_order_or_stoploss_order
    return self.fetch_order(order_id, pair)
  File "/freqtrade/freqtrade/exchange/common.py", line 135, in wrapper
    return f(*args, **kwargs)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 1074, in fetch_order
    return self._api.fetch_order(order_id, pair)
  File "/root/.local/lib/python3.8/site-packages/ccxt/kraken.py", line 1146, in fetch_order
    order = self.parse_order(self.extend({'id': id}, orders[id]))
KeyError: 'OVXMMC-66C7M-TB6MYC'
2021-01-07 19:13:51,730 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2021-01-07 19:13:51,730 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}

Can anybody tell me what could go wrong here?

**Comment by xmatthias** [comment]
I've raised https://github.com/ccxt/ccxt/issues/8222 for your issue. 

I suspect you're seeing this due to the current load on kraken - However - it exposes a bug in ccxt - therefore the issue.

**Comment by xmatthias** [comment]
@Andi1990 i'd suggest to update to the latest ccxt version (`pip install -U ccxt`).

That'll fix the issue and a "proper" exception is returned, which we're handling (OrderNotFound).

**Comment by Andi1990** [comment]
> @Andi1990 i'd suggest to update to the latest ccxt version (`pip install -U ccxt`).
> 
> That'll fix the issue and a "proper" exception is returned, which we're handling (OrderNotFound).

@xmatthias I have installed freqtrade via docker-compose. Can you tell me how to upgrade the docker-image to the new ccxt version?

**Comment by xmatthias** [comment]
i've bumped the version for ccxt on the develop image a few minutes ago .. should appear in about half an hour... (depending on when CI finishes), so all you'll need to do is a "docker-compose pull" ...
