### ISSUE TITLE
Could not reload markets

### ISSUE THREAD

**Issue by MBadberg** [freqtrade/freqtrade#4148]
Hi there,

here and then i got this error message:

```2021-01-04 20:38:37,194 - freqtrade.exchange.exchange - ERROR - Could not reload markets.
Traceback (most recent call last):
  File "/opt/freqtrade/freqtrade/.env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/opt/freqtrade/freqtrade/.env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/opt/freqtrade/freqtrade/.env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1322, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/freqtrade/freqtrade/.env/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/freqtrade/freqtrade/.env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/opt/freqtrade/freqtrade/.env/lib/python3.8/site-packages/urllib3/util/retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/opt/freqtrade/freqtrade/.env/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/opt/freqtrade/freqtrade/.env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/opt/freqtrade/freqtrade/.env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/opt/freqtrade/freqtrade/.env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1322, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/freqtrade/freqtrade/.env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 562, in fetch
    response = self.session.request(
  File "/opt/freqtrade/freqtrade/.env/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/freqtrade/freqtrade/.env/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/freqtrade/freqtrade/.env/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/freqtrade/freqtrade/freqtrade/exchange/exchange.py", line 308, in reload_markets
    self._api.load_markets(reload=True)
  File "/opt/freqtrade/freqtrade/.env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1350, in load_markets
    markets = self.fetch_markets(params)
  File "/opt/freqtrade/freqtrade/.env/lib/python3.8/site-packages/ccxt/binance.py", line 579, in fetch_markets
    response = getattr(self, method)(query)
  File "/opt/freqtrade/freqtrade/.env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 465, in inner
    return entry(_self, **inner_kwargs)
  File "/opt/freqtrade/freqtrade/.env/lib/python3.8/site-packages/ccxt/binance.py", line 2472, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/opt/freqtrade/freqtrade/.env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 486, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
Requirement already satisfied: py_find_1st in ./.env/lib/python3.8/site-packages (from freqtrade===develop-31829d52) (1.1.4)
Requirement already satisfied: pycoingecko in ./.env/lib/python3.8/site-packages (from freqtrade===develop-31829d52) (1.4.0)
Requirement already satisfied: python-rapidjson in ./.env/lib/python3.8/site-packages (from freqtrade===develop-31829d52) (1.0)
Requirement already satisfied: python-telegram-bot in ./.env/lib/python3.8/site-packages (from freqtrade===develop-31829d52) (13.1)
Requirement already satisfied: questionary in ./.env/lib/python3.8/site-packages (from freqtrade===develop-31829d52) (1.9.0)
Requirement already satisfied: requests in ./.env/lib/python3.8/site-packages (from freqtrade===develop-31829d52) (2.25.1)
Requirement already satisfied: sdnotify in ./.env/lib/python3.8/site-packages (from freqtrade===develop-31829d52) (0.3.2)
Requirement already satisfied: tables in ./.env/lib/python3.8/site-packages (from freqtrade===develop-31829d52) (3.6.1)
Requirement already satisfied: tabulate in ./.env/lib/python3.8/site-packages (from freqtrade===develop-31829d52) (0.8.7)
Requirement already satisfied: urllib3 in ./.env/lib/python3.8/site-packages (from freqtrade===develop-31829d52) (1.26.2)
Requirement already satisfied: wrapt in ./.env/lib/python3.8/site-packages (from freqtrade===develop-31829d52) (1.12.1)
Requirement already satisfied: python-dateutil>=2.7.0 in ./.env/lib/python3.8/site-packages (from arrow>=0.17.0->freqtrade===develop-31829d52) (2.8.1)
Requirement already satisfied: setuptools>=38.5.1 in ./.env/lib/python3.8/site-packages (from ccxt>=1.24.96->freqtrade===develop-31829d52) (39.0.1)
Requirement already satisfied: aiohttp<3.8,>=3.7.2 in ./.env/lib/python3.8/site-packages (from ccxt>=1.24.96->freqtrade===develop-31829d52) (3.7.3)


    raise NetworkError(details) from e
ccxt.base.errors.NetworkError: binance GET https://api.binance.com/api/v3/exchangeInfo
```

I've found something related to ccxt, but it was only on the error reported back to the user. 
https://github.com/ccxt/ccxt/issues/6518

Is this something, that happen now and then and is not to worry about, or is this related to the use of an older version of ccxt in freqtrade?

**Comment by xmatthias** [comment]
Your logs seem kinda messed up (it includes a stacktrace first, and then output of a `pip install` ...)
which makes it hard to say what actually happened.

I suspect it's what it says it is - a network error. 
I'm not on your network, in theory it could be a router / proxy that resets the connection, or it could be the exchange (but i have to admit, i've not had such an error before - so i doubt it's the exchange itself), or even a unstable WIFI (but i don't know your machine / environment, so all i'm doing is guessing).

**Comment by koradiyakaushal** [comment]
@MBadberg yesterday Binance was facing a huge server load for some regions due to heavy volumes, it was down for some time, so they increased API rate weightage for fapi and dapi(Futures APIs).

**Comment by xmatthias** [comment]
A binance outage would explain this as well - while i didn't have this problem - it may occur randomly or depending on the region your server is connecting from.

**Comment by MBadberg** [comment]
Hello,

sorry for my late reply. I have done some research.

The error still occurs but the url is reachable. No outages or glitches from Binance or my network/internet connection.
And the trades are being executed as well. No errors here.

It is really strange.

For cleanliness, I have attached the plain error message again. I don't know what went wrong with the first post, or why there are pip issues in there. :-)

```
2021-01-07 15:01:18,016 - freqtrade.exchange.exchange - ERROR - Could not reload markets.
Traceback (most recent call last):
  File "/opt/freqtrade/freqtrade/.env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/opt/freqtrade/freqtrade/.env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/opt/freqtrade/freqtrade/.env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1322, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/freqtrade/freqtrade/.env/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/freqtrade/freqtrade/.env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/opt/freqtrade/freqtrade/.env/lib/python3.8/site-packages/urllib3/util/retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/opt/freqtrade/freqtrade/.env/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/opt/freqtrade/freqtrade/.env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/opt/freqtrade/freqtrade/.env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/opt/freqtrade/freqtrade/.env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1322, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/freqtrade/freqtrade/.env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 562, in fetch
    response = self.session.request(
  File "/opt/freqtrade/freqtrade/.env/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/freqtrade/freqtrade/.env/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/freqtrade/freqtrade/.env/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/opt/freqtrade/freqtrade/freqtrade/exchange/exchange.py", line 308, in reload_markets
    self._api.load_markets(reload=True)
  File "/opt/freqtrade/freqtrade/.env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1350, in load_markets
    markets = self.fetch_markets(params)
  File "/opt/freqtrade/freqtrade/.env/lib/python3.8/site-packages/ccxt/binance.py", line 579, in fetch_markets
    response = getattr(self, method)(query)
  File "/opt/freqtrade/freqtrade/.env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 465, in inner
    return entry(_self, **inner_kwargs)
  File "/opt/freqtrade/freqtrade/.env/lib/python3.8/site-packages/ccxt/binance.py", line 2472, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/opt/freqtrade/freqtrade/.env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 486, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/opt/freqtrade/freqtrade/.env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 614, in fetch
    raise NetworkError(details) from e
ccxt.base.errors.NetworkError: binance GET https://api.binance.com/api/v3/exchangeInfo
2021-01-07 15:01:58,028 - freqtrade.worker - INFO - Bot heartbeat. PID=18380, version='develop-cce4d7e4', state='RUNNING'


```

**Comment by xmatthias** [comment]
The message (`Connection reset by peer`) indicates that the Server refused your connection.
Why this happens i don't know. Searching the internet for this seems to suggest that a reboot often fixes this [source](https://stackoverflow.com/questions/39885322/python-error-connection-reset-by-peer-in-requests-module/48453406) - (which might suggest that you're out of local sockets - but that's a guess from my side).

Others suggest installing `requests[security]` - but if this where the case, you'd not be able to connect to binance at all.

Also ccxt suggests that it's a generic networking problem (https://github.com/ccxt/ccxt/issues/3897).
It's a pretty old issue, but networking basics don't really change.

I can exclude a rate-limit though, as that would show a different exception (i've seen this often enough).

**Comment by xmatthias** [comment]
I'll assume this as answered by the above. There is unfortunately not much from our side we can do for this - as it's an issue specific to your network / network configuration.

Feel free to comment below / reopen if that's not the case.

**Comment by jacobliang9456** [comment]
Hi, 
I have the same error message. Is there any solution?

Thank you so much

**Comment by xmatthias** [comment]
It's either a network error on your side, or a temporary downtime on the exchange side.

Simplest solution: make sure your network is stable - and retry a little later eventually.

**Comment by zeminglakuai** [comment]
Hi,
I have the same error message. Is there any solution?

Thank you so much

**Comment by xmatthias** [comment]
Please read my comment above (https://github.com/freqtrade/freqtrade/issues/4148#issuecomment-850140736).

The issue did not change, neither will the solution.
i'll also lock this issue - as people posting will ping everyone that's ever been involved here - and asking "i got the same, but i'm too lazy to read the comments" are not helping anyone.
