### ISSUE TITLE
"First trade opened" information is wrong

### ISSUE THREAD

**Issue by aristosv** [freqtrade/freqtrade#4153]
## Describe your environment
  * Operating system: Debian 10
  * Python Version: Python 3.7.3
  * CCXT version: ccxt==1.40.14
  * Freqtrade Version: freqtrade develop-d1804dee

## Describe the problem:
Running the /profit command shows "First trade opened: a day ago".
Running the /status table command shows the first trade was opened 3 days ago.

![2](https://user-images.githubusercontent.com/528302/103732327-cffa5680-4fef-11eb-8a35-c1d10bc27727.png)
![1](https://user-images.githubusercontent.com/528302/103732332-d4267400-4fef-11eb-848a-03d2f9b5c196.png)

**Comment by xmatthias** [comment]
to be honest, i don't really see how this might be possible after looking at the code, unless you somehow messed with the trade id's in the database.

The code is simply sorting by trade_id and takes the open-date of the trade with the lowest id.

Can you run something like the following (adjust the sqlite url eventually) and post the output here?

```
freqtrade show-trades --trade-ids 1, 86 --db-url sqlite:///tradesv3.sqlite --print-json
```

**Comment by aristosv** [comment]
What would be the default value for --db-url ?

This is how I installed it, and I never had to deal with --db-url

```
git clone https://github.com/freqtrade/freqtrade.git
cd /root/freqtrade
git checkout develop
printf 'y\ny\n' | ./setup.sh --install
```

This is currently the output of the command

```
(.env) root@freqtrade:~/freqtrade_USDT# freqtrade show-trades --trade-ids 1, 86 --db-url sqlite:///tradesv3.sqlite --print-json
2021-01-06 08:39:19,683 - freqtrade.configuration.configuration - INFO - Using config: config.json ...
2021-01-06 08:39:19,684 - freqtrade.loggers - INFO - Verbosity set to 0
2021-01-06 08:39:19,684 - freqtrade.configuration.configuration - INFO - Using user-data directory: /root/freqtrade_USDT/user_data ...
2021-01-06 08:39:19,684 - freqtrade.configuration.configuration - INFO - Using data directory: /root/freqtrade_USDT/user_data/data/binance ...
2021-01-06 08:39:19,684 - freqtrade.configuration.configuration - INFO - Parameter --print-json detected ...
2021-01-06 08:39:19,684 - freqtrade.configuration.configuration - INFO - Filtering on trade_ids: ['1,', '86']
2021-01-06 08:39:19,685 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2021-01-06 08:39:19,685 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2021-01-06 08:39:19,685 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2021-01-06 08:39:19,685 - freqtrade.configuration.deprecated_settings - WARNING - DEPRECATED: Please use 'timeframe' instead of 'ticker_interval.
2021-01-06 08:39:19,685 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2021-01-06 08:39:19,687 - freqtrade - ERROR - --db-url is required for this command.
```

**Comment by xmatthias** [comment]
for a production run, it should be `sqlite:///tradesv3.sqlite` ... for dry run `sqlite:///tradesv3.dryrun.sqlite`

unless you specified a different url in eihter configuration or while running the bot

**Comment by aristosv** [comment]
I didn't. But how can I find out what the correct url is? I have no such value in config.json

**Comment by xmatthias** [comment]
when you start the bot (as you usually do), it'll be in one of the first 10 lines (`Using DB: ...`).

**Comment by aristosv** [comment]
This the service file I created to start and stop freqtrade

```
Description=freqtrade USDT service
After=network.target

[Service]
ExecStart=/bin/bash -c "cd /root/freqtrade_USDT ; source .env/bin/activate ; freqtrade trade --strategy freqtrade"
Restart=always
StandardError=append:/var/log/freqtrade_USDT.log

[Install]
WantedBy=multi-user.target
```

So the command is this
`cd /root/freqtrade_USDT ; source .env/bin/activate ; freqtrade trade --strategy freqtrade`

**Comment by xmatthias** [comment]
it's not about the command, but about the log output.
This looks like it's using defaults, so you should have the database in `/root/freqtrade_USDT/tradesv3.sqlite`.

**Comment by aristosv** [comment]
Now it gives me an error

```
(.env) root@freqtrade:~/freqtrade_USDT# freqtrade show-trades --trade-ids 1, 86 --db-url /root/freqtrade_USDT/tradesv3.sqlite --print-json
2021-01-06 16:43:48,627 - freqtrade.configuration.configuration - INFO - Using config: config.json ...
2021-01-06 16:43:48,627 - freqtrade.loggers - INFO - Verbosity set to 0
2021-01-06 16:43:48,628 - freqtrade.configuration.configuration - INFO - Parameter --db-url detected ...
2021-01-06 16:43:48,628 - freqtrade.configuration.configuration - INFO - Using user-data directory: /root/freqtrade_USDT/user_data ...
2021-01-06 16:43:48,628 - freqtrade.configuration.configuration - INFO - Using data directory: /root/freqtrade_USDT/user_data/data/binance ...
2021-01-06 16:43:48,628 - freqtrade.configuration.configuration - INFO - Parameter --print-json detected ...
2021-01-06 16:43:48,628 - freqtrade.configuration.configuration - INFO - Filtering on trade_ids: ['1,', '86']
2021-01-06 16:43:48,628 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2021-01-06 16:43:48,628 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2021-01-06 16:43:48,628 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2021-01-06 16:43:48,628 - freqtrade.configuration.deprecated_settings - WARNING - DEPRECATED: Please use 'timeframe' instead of 'ticker_interval.
2021-01-06 16:43:48,628 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2021-01-06 16:43:48,631 - freqtrade.commands.list_commands - INFO - Using DB: "/root/freqtrade_USDT/tradesv3.sqlite"
2021-01-06 16:43:48,631 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/root/freqtrade_USDT/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/root/freqtrade_USDT/freqtrade/commands/list_commands.py", line 215, in start_show_trades
    init_db(config['db_url'], clean_open_orders=False)
  File "/root/freqtrade_USDT/freqtrade/persistence/models.py", line 54, in init_db
    engine = create_engine(db_url, **kwargs)
  File "/root/freqtrade_USDT/.env/lib/python3.7/site-packages/sqlalchemy/engine/__init__.py", line 520, in create_engine
    return strategy.create(*args, **kwargs)
  File "/root/freqtrade_USDT/.env/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 54, in create
    u = url.make_url(name_or_url)
  File "/root/freqtrade_USDT/.env/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 229, in make_url
    return _parse_rfc1738_args(name_or_url)
  File "/root/freqtrade_USDT/.env/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 291, in _parse_rfc1738_args
    "Could not parse rfc1738 URL from string '%s'" % name
sqlalchemy.exc.ArgumentError: Could not parse rfc1738 URL from string '/root/freqtrade_USDT/tradesv3.sqlite'
```

The file is there though

```
(.env) root@freqtrade:~/freqtrade_USDT# ls -l | grep sqlite
-rw-r--r--  1 root root 155648 Jan  6 17:13 tradesv3.sqlite
```

**Comment by xmatthias** [comment]
the correct argument is `--db-url sqlite:////root/freqtrade_USDT/tradesv3.sqlite`

**Comment by aristosv** [comment]
This is the result

```
(.env) root@freqtrade:~/freqtrade_USDT# freqtrade show-trades --trade-ids 1, 86 --db-url sqlite:////root/freqtrade_USDT/tradesv3.sqlite --print-json
2021-01-06 18:45:55,257 - freqtrade.configuration.configuration - INFO - Using config: config.json ...
2021-01-06 18:45:55,258 - freqtrade.loggers - INFO - Verbosity set to 0
2021-01-06 18:45:55,258 - freqtrade.configuration.configuration - INFO - Parameter --db-url detected ...
2021-01-06 18:45:55,258 - freqtrade.configuration.configuration - INFO - Using user-data directory: /root/freqtrade_USDT/user_data ...
2021-01-06 18:45:55,258 - freqtrade.configuration.configuration - INFO - Using data directory: /root/freqtrade_USDT/user_data/data/binance ...
2021-01-06 18:45:55,259 - freqtrade.configuration.configuration - INFO - Parameter --print-json detected ...
2021-01-06 18:45:55,259 - freqtrade.configuration.configuration - INFO - Filtering on trade_ids: ['1,', '86']
2021-01-06 18:45:55,259 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2021-01-06 18:45:55,259 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2021-01-06 18:45:55,259 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2021-01-06 18:45:55,259 - freqtrade.configuration.deprecated_settings - WARNING - DEPRECATED: Please use 'timeframe' instead of 'ticker_interval.
2021-01-06 18:45:55,259 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2021-01-06 18:45:55,261 - freqtrade.commands.list_commands - INFO - Using DB: "sqlite:////root/freqtrade_USDT/tradesv3.sqlite"
2021-01-06 18:45:55,281 - freqtrade.commands.list_commands - INFO - Printing 1 Trades:
[
    {
        "trade_id": 86,
        "pair": "MFT/USDT",
        "is_open": false,
        "exchange": "binance",
        "amount": 40297.662,
        "amount_requested": 40338.846309,
        "stake_amount": 100.0,
        "strategy": "freqtrade",
        "timeframe": 5,
        "fee_open": 0.001,
        "fee_open_cost": 40.338,
        "fee_open_currency": "MFT",
        "fee_close": 0.001,
        "fee_close_cost": 0.10126636,
        "fee_close_currency": "USDT",
        "open_date_hum": "15 hours ago",
        "open_date": "2021-01-06 01:35:58",
        "open_timestamp": 1609896958369,
        "open_rate": 0.002479,
        "open_rate_requested": 0.002479,
        "open_trade_value": 99.997802,
        "close_date_hum": "14 hours ago",
        "close_date": "2021-01-06 02:43:16",
        "close_timestamp": 1609900996532,
        "close_rate": 0.002513,
        "close_rate_requested": 0.002513,
        "close_profit": 0.0116898,
        "close_profit_pct": 1.17,
        "close_profit_abs": 1.16895458,
        "profit_ratio": 0.0116898,
        "profit_pct": 1.17,
        "profit_abs": 1.16895458,
        "sell_reason": "roi",
        "sell_order_status": "closed",
        "stop_loss_abs": 0.0017352999999999997,
        "stop_loss_ratio": -0.3,
        "stop_loss_pct": -30.0,
        "stoploss_order_id": null,
        "stoploss_last_update": "2021-01-06 01:37:47",
        "stoploss_last_update_timestamp": 1609897067898,
        "initial_stop_loss_abs": 0.0017352999999999997,
        "initial_stop_loss_ratio": -0.3,
        "initial_stop_loss_pct": -30.0,
        "min_rate": 0.002477,
        "max_rate": 0.002513,
        "open_order_id": null
    }
]
(.env) root@freqtrade:~/freqtrade_USDT#
```

**Comment by xmatthias** [comment]
hm seems like i had a typo :D 

can you try `freqtrade show-trades --trade-ids 1 2 86 --db-url sqlite:////root/freqtrade_USDT/tradesv3.sqlite --print-json`?

**Comment by aristosv** [comment]
This is the output

```
[
    {
        "trade_id": 1,
        "pair": "ZIL/USDT",
        "is_open": false,
        "exchange": "binance",
        "amount": 724.2,
        "amount_requested": 725.0,
        "stake_amount": 50.0,
        "strategy": "freqtrade",
        "timeframe": 5,
        "fee_open": 0.001,
        "fee_open_cost": 0.725,
        "fee_open_currency": "ZIL",
        "fee_close": 0.001,
        "fee_close_cost": 0.05061434,
        "fee_close_currency": "USDT",
        "open_date_hum": "2 days ago",
        "open_date": "2021-01-04 11:55:54",
        "open_timestamp": 1609761354346,
        "open_rate": 0.06896000000000001,
        "open_rate_requested": 0.06896,
        "open_trade_value": 49.99077283,
        "close_date_hum": "2 days ago",
        "close_date": "2021-01-04 14:01:10",
        "close_timestamp": 1609768870268,
        "close_rate": 0.06989,
        "close_rate_requested": 0.06989,
        "close_profit": 0.01146113,
        "close_profit_pct": 1.15,
        "close_profit_abs": 0.57295083,
        "profit_ratio": 0.01146113,
        "profit_pct": 1.15,
        "profit_abs": 0.57295083,
        "sell_reason": "roi",
        "sell_order_status": "closed",
        "stop_loss_abs": 0.048272,
        "stop_loss_ratio": -0.3,
        "stop_loss_pct": -30.0,
        "stoploss_order_id": null,
        "stoploss_last_update": "2021-01-04 11:56:01",
        "stoploss_last_update_timestamp": 1609761361815,
        "initial_stop_loss_abs": 0.048272,
        "initial_stop_loss_ratio": -0.3,
        "initial_stop_loss_pct": -30.0,
        "min_rate": 0.06817,
        "max_rate": 0.07085,
        "open_order_id": null
    },
    {
        "trade_id": 2,
        "pair": "MBL/USDT",
        "is_open": false,
        "exchange": "binance",
        "amount": 35986.977,
        "amount_requested": 36023.05475504,
        "stake_amount": 50.0,
        "strategy": "freqtrade",
        "timeframe": 5,
        "fee_open": 0.001,
        "fee_open_cost": 36.023,
        "fee_open_currency": "MBL",
        "fee_close": 0.001,
        "fee_close_cost": 0.05066829,
        "fee_close_currency": "USDT",
        "open_date_hum": "2 days ago",
        "open_date": "2021-01-04 12:40:54",
        "open_timestamp": 1609764054172,
        "open_rate": 0.001388,
        "open_rate_requested": 0.001388,
        "open_trade_value": 49.999874,
        "close_date_hum": "2 days ago",
        "close_date": "2021-01-04 14:25:51",
        "close_timestamp": 1609770351347,
        "close_rate": 0.001408,
        "close_rate_requested": 0.001408,
        "close_profit": 0.01238243,
        "close_profit_pct": 1.24,
        "close_profit_abs": 0.61911995,
        "profit_ratio": 0.01238243,
        "profit_pct": 1.24,
        "profit_abs": 0.61911995,
        "sell_reason": "roi",
        "sell_order_status": "closed",
        "stop_loss_abs": 0.0009715999999999999,
        "stop_loss_ratio": -0.3,
        "stop_loss_pct": -30.0,
        "stoploss_order_id": null,
        "stoploss_last_update": "2021-01-04 12:46:43",
        "stoploss_last_update_timestamp": 1609764403483,
        "initial_stop_loss_abs": 0.0009715999999999999,
        "initial_stop_loss_ratio": -0.3,
        "initial_stop_loss_pct": -30.0,
        "min_rate": 0.001382,
        "max_rate": 0.001408,
        "open_order_id": null
    },
    {
        "trade_id": 86,
        "pair": "MFT/USDT",
        "is_open": false,
        "exchange": "binance",
        "amount": 40297.662,
        "amount_requested": 40338.846309,
        "stake_amount": 100.0,
        "strategy": "freqtrade",
        "timeframe": 5,
        "fee_open": 0.001,
        "fee_open_cost": 40.338,
        "fee_open_currency": "MFT",
        "fee_close": 0.001,
        "fee_close_cost": 0.10126636,
        "fee_close_currency": "USDT",
        "open_date_hum": "19 hours ago",
        "open_date": "2021-01-06 01:35:58",
        "open_timestamp": 1609896958369,
        "open_rate": 0.002479,
        "open_rate_requested": 0.002479,
        "open_trade_value": 99.997802,
        "close_date_hum": "18 hours ago",
        "close_date": "2021-01-06 02:43:16",
        "close_timestamp": 1609900996532,
        "close_rate": 0.002513,
        "close_rate_requested": 0.002513,
        "close_profit": 0.0116898,
        "close_profit_pct": 1.17,
        "close_profit_abs": 1.16895458,
        "profit_ratio": 0.0116898,
        "profit_pct": 1.17,
        "profit_abs": 1.16895458,
        "sell_reason": "roi",
        "sell_order_status": "closed",
        "stop_loss_abs": 0.0017352999999999997,
        "stop_loss_ratio": -0.3,
        "stop_loss_pct": -30.0,
        "stoploss_order_id": null,
        "stoploss_last_update": "2021-01-06 01:37:47",
        "stoploss_last_update_timestamp": 1609897067898,
        "initial_stop_loss_abs": 0.0017352999999999997,
        "initial_stop_loss_ratio": -0.3,
        "initial_stop_loss_pct": -30.0,
        "min_rate": 0.002477,
        "max_rate": 0.002513,
        "open_order_id": null
    }
]
```

**Comment by xmatthias** [comment]
considering the time spent in this issue, the output seems correct to me.

First issue was opened 2 days ago now - which will have been ~1 day prior to that. 

```
        "open_date_hum": "2 days ago",
        "open_date": "2021-01-04 11:55:54",
```

Now obviously the "human" form will not be 100% accurate (2 days can mean anything between 2 and 3 days ago ...)
Also, considering timezones, it can easily fluctuate by a few hours when it "flips" from 2 to 3 days, so it's not "exactly 48 hours ago" when it flips from 2 to 3 days.

We use Arrow for this "humanization" - so the boundaries for this are set by Arrow.
Based on the "open date" of the 4th, i don't see why this is necessarily wrong, or how we could improve this other than by showing the precise date (which however is not really "Human readable" - and you'll need to do the math on "How many days ago" yourself).

**Comment by aristosv** [comment]
ok, thanks for the info

**Comment by xmatthias** [comment]
Let me know if you notice it's off more than that ... but i don't think it will be.
