### ISSUE TITLE
ImportError: cannot import name 'Session' from 'requests' 

### ISSUE THREAD

**Issue by chugh-ak5** [freqtrade/freqtrade#4176]
### Have you searched for similar issues before posting it?
Yes, tried looking for it but could not find a solution, unsure if it is a freqtrade issue, python / pip issue or a Linux distro issue

### Describe your environment

  * Operating system: Windows 10, 8GB RAM, x64, WSL1
  * Python Version: 3.8.5 
  * CCXT version: 1.34.25 
  * Freqtrade Version: Unable to find it as I receive an error, but I'm running develop 
  
### Describe the problem:
I deactivated the bot and updated the bot using ./setup.sh --update after which I ran the bot, was working perfectly fine last night but facing an ImportError now, quite strange 
*Explain the problem you have encountered*
I'm new to this and would like to resolve this issue with some assistance, thanks in advance 
I deactivated the bot and updated it, updated my linux distribution on WSL1
cleared all cached data with the commands 
sudo apt-get update
sudo apt-get upgrade 
sudo apt-get clean 
sudo apt-get autoclean
sudo apt-get autoremove
rm -rf ~/.cache/thumbnails/*
The bot was running last night, but my PC shut down due to low power 
Woke up facing an issue I'm quite worried about, would like to resolve it with your assistance 

### Steps to reproduce:

  1. Updated the bot
  2. Cleaned up the cached data on my Linux distro
  3. Unable to make the bot work due to import error 
  
### Observed Results:

  * What happened?
  * Bot doesn't work now due to import error pertaining to sessions and requests
  * What did you expect to happen?
  * Run the bot with assistance and resolve the issues I'm facing 

### Relevant code exceptions or logs

  `````
Traceback (most recent call last:
File "/home/chugh_ak/freqtrade/.env/bin/freqtrade", line 11, in <module>
load_entry_point('freqtrade', 'console_scripts', 'freqtrade()
File "/home/chugh_ak/freqtrade/.env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
return get_distribution(dist).load_entry_point(group, name)
File "/home/chugh_ak/freqtrade/.env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
return ep.load()
File "/home/chugh_ak/freqtrade/.env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
return self.resolve()
File "/home/chugh_ak/freqtrade/.env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
module = __import__(self.module_name, fromlist=['__name__'], level=0)
File "/home/chugh_ak/freqtrade/freqtrade/main.py", line 15, in <module>
from freqtrade.commands import Arguments
File "/home/chugh_ak/freqtrade/freqtrade/commands/__init__.py", line 10, in <module>
from freqtrade.commands.build_config_commands import start_new_config
File "/home/chugh_ak/freqtrade/freqtrade/commands/build_config_commands.py", line 9, in <module>
from freqtrade.exchange import MAP_EXCHANGE_CHILDCLASS, available_exchanges
File "/home/chugh_ak/freqtrade/freqtrade/exchange/__init__.py", line 4, in <module>
from freqtrade.exchange.exchange import Exchange
File "/home/chugh_ak/freqtrade/freqtrade/exchange/exchange.py", line 14, in <module>
import ccxt
File "/home/chugh_ak/freqtrade/.env/lib/python3.8/site-packages/ccxt/__init__.py", line 29, in <module>
from ccxt.base.exchange import Exchange                     # noqa: F401                                                                    
File "/home/chugh_ak/freqtrade/.env/lib/python3.8/site-packages/ccxt/base/__init__.py", line 24, in <module>
from ccxt.base import exchange
File "/home/chugh_ak/freqtrade/.env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 72, in <module>
from requests import Session
ImportError: cannot import name 'Session' from 'requests' (/home/chugh_ak/freqtrade/.env/lib/python3.8/site-packages/requests/__init__.py)  
  `````

**Comment by xmatthias** [comment]
That's a pretty strange error... maybe there's a problem with t

what happens when you run python (From within the virtual environment) and execute the following:

```
import requests
requests.__version__
```

You might also try to simply remove the virtual environment (`rm -rf .env`) - and reinstalling freqtrade (`./setup.sh --install`).
If there are any errors during the installation, these can be important ... ;)

**Comment by chugh-ak5** [comment]
I probably had another window open with the venv activated while another window was updating the setup.sh 
When I run python from whithin the venv, I get the following :
````
Python 3.8.5 (default, Jul 28 2020, 12:59:40)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> requests.__version__
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
AttributeError: module 'requests' has no attribute '__version__' 
````
Alright noted , if I remove the hidden venv , will it affect or remove any of my strategies or delete some of my user data - my downloads, backtesting results and hyperopts ?

**Comment by xmatthias** [comment]
nothing you care about is stored in the virtual environment - so running `rm -rf .env` is perfectly fine (obviously the bot should not run, and it should not be activated in any terminal).

After that, simply reinstall with `./setup.sh --install` - your user-data will still be where you left it.

**Comment by chugh-ak5** [comment]
Sweet, works perfectly fine now! Thanks @xmatthias 👍
