### ISSUE TITLE
WHERE trades.open_order_id IS NOT NULL

### ISSUE THREAD

**Issue by alaalimii** [freqtrade/freqtrade#4180]
Hi, i can't trade anymore and i don't know why , yesterday all was good but now the bot can not run can you please help me:

$ freqtrade trade -c config.json -s BBRSI
2021-01-10 08:31:12,811 - freqtrade.worker - INFO - Starting worker 2020.11
2021-01-10 08:31:12,811 - freqtrade.configuration.configuration - INFO - Using config: config.json ...
2021-01-10 08:31:12,813 - freqtrade.loggers - INFO - Verbosity set to 0
2021-01-10 08:31:12,815 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
2021-01-10 08:31:12,815 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2021-01-10 08:31:12,815 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:///tradesv3.dryrun.sqlite"
2021-01-10 08:31:12,815 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 10 ...
2021-01-10 08:31:12,815 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/besttraderofalltime/freqtrade/user_data ...
2021-01-10 08:31:12,816 - freqtrade.configuration.configuration - INFO - Using data directory: /home/besttraderofalltime/freqtrade/user_data/data/binance ...
2021-01-10 08:31:12,816 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2021-01-10 08:31:12,816 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2021-01-10 08:31:12,816 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2021-01-10 08:31:12,816 - freqtrade.freqtradebot - INFO - Starting freqtrade 2020.11
2021-01-10 08:31:12,858 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy BBRSI from '/home/besttraderofalltime/freqtrade/user_data/strategies/bbrsi.py'...
2021-01-10 08:31:12,859 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 15m.
2021-01-10 08:31:12,859 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: BTC.
2021-01-10 08:31:12,859 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 0.1.
2021-01-10 08:31:12,859 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'buy': 10, 'sell': 20}.
2021-01-10 08:31:12,860 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'use_sell_signal' with value in config file: True.
2021-01-10 08:31:12,860 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'sell_profit_only' with value in config file: False.
2021-01-10 08:31:12,860 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ignore_roi_if_buy_signal' with value in config file: False.
2021-01-10 08:31:12,860 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 0.1}
2021-01-10 08:31:12,860 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 15m
2021-01-10 08:31:12,860 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.3
2021-01-10 08:31:12,860 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2021-01-10 08:31:12,867 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2021-01-10 08:31:12,870 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2021-01-10 08:31:12,870 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
2021-01-10 08:31:12,871 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False}
2021-01-10 08:31:12,871 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
2021-01-10 08:31:12,871 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: BTC
2021-01-10 08:31:12,871 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 0.1
2021-01-10 08:31:12,871 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 0
2021-01-10 08:31:12,871 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'buy': 10, 'sell': 20}
2021-01-10 08:31:12,871 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_sell_signal: True
2021-01-10 08:31:12,872 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_only: False
2021-01-10 08:31:12,872 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_buy_signal: False
2021-01-10 08:31:12,872 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2021-01-10 08:31:12,872 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2021-01-10 08:31:12,876 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2021-01-10 08:31:12,882 - freqtrade.exchange.exchange - INFO - Using CCXT 1.39.33
2021-01-10 08:31:12,883 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2021-01-10 08:31:12,920 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 200}
2021-01-10 08:31:12,949 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2021-01-10 08:31:14,243 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2021-01-10 08:31:14,339 - freqtrade.commands.trade_commands - ERROR - (sqlite3.OperationalError) no such column: trades.open_trade_price
[SQL: SELECT trades.id AS trades_id, trades.exchange AS trades_exchange, trades.pair AS trades_pair, trades.is_open AS trades_is_open, trades.fee_open AS trades_fee_open, trades.fee_open_cost AS trades_fee_open_cost, trades.fee_open_currency AS trades_fee_open_currency, trades.fee_close AS trades_fee_close, trades.fee_close_cost AS trades_fee_close_cost, trades.fee_close_currency AS trades_fee_close_currency, trades.open_rate AS trades_open_rate, trades.open_rate_requested AS trades_open_rate_requested, trades.open_trade_price AS trades_open_trade_price, trades.close_rate AS trades_close_rate, trades.close_rate_requested AS trades_close_rate_requested, trades.close_profit AS trades_close_profit, trades.close_profit_abs AS trades_close_profit_abs, trades.stake_amount AS trades_stake_amount, trades.amount AS trades_amount, trades.amount_requested AS trades_amount_requested, trades.open_date AS trades_open_date, trades.close_date AS trades_close_date, trades.open_order_id AS trades_open_order_id, trades.stop_loss AS trades_stop_loss, trades.stop_loss_pct AS trades_stop_loss_pct, trades.initial_stop_loss AS trades_initial_stop_loss, trades.initial_stop_loss_pct AS trades_initial_stop_loss_pct, trades.stoploss_order_id AS trades_stoploss_order_id, trades.stoploss_last_update AS trades_stoploss_last_update, trades.max_rate AS trades_max_rate, trades.min_rate AS trades_min_rate, trades.sell_reason AS trades_sell_reason, trades.sell_order_status AS trades_sell_order_status, trades.strategy AS trades_strategy, trades.timeframe AS trades_timeframe 
FROM trades 
WHERE trades.open_order_id IS NOT NULL]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
2021-01-10 08:31:14,339 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/besttraderofalltime/freqtrade/.env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/besttraderofalltime/freqtrade/.env/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: trades.open_trade_price

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/besttraderofalltime/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/home/besttraderofalltime/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/home/besttraderofalltime/freqtrade/freqtrade/worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/home/besttraderofalltime/freqtrade/freqtrade/freqtradebot.py", line 71, in __init__
    init_db(self.config.get('db_url', None), clean_open_orders=self.config['dry_run'])
  File "/home/besttraderofalltime/freqtrade/freqtrade/persistence/models.py", line 76, in init_db
    clean_dry_run_db()
  File "/home/besttraderofalltime/freqtrade/freqtrade/persistence/models.py", line 92, in clean_dry_run_db
    for trade in Trade.query.filter(Trade.open_order_id.isnot(None)).all():
  File "/home/besttraderofalltime/freqtrade/.env/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3373, in all
    return list(self)
  File "/home/besttraderofalltime/freqtrade/.env/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "/home/besttraderofalltime/freqtrade/.env/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/besttraderofalltime/freqtrade/.env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/home/besttraderofalltime/freqtrade/.env/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/besttraderofalltime/freqtrade/.env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/besttraderofalltime/freqtrade/.env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/home/besttraderofalltime/freqtrade/.env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/home/besttraderofalltime/freqtrade/.env/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/besttraderofalltime/freqtrade/.env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/besttraderofalltime/freqtrade/.env/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: trades.open_trade_price
[SQL: SELECT trades.id AS trades_id, trades.exchange AS trades_exchange, trades.pair AS trades_pair, trades.is_open AS trades_is_open, trades.fee_open AS trades_fee_open, trades.fee_open_cost AS trades_fee_open_cost, trades.fee_open_currency AS trades_fee_open_currency, trades.fee_close AS trades_fee_close, trades.fee_close_cost AS trades_fee_close_cost, trades.fee_close_currency AS trades_fee_close_currency, trades.open_rate AS trades_open_rate, trades.open_rate_requested AS trades_open_rate_requested, trades.open_trade_price AS trades_open_trade_price, trades.close_rate AS trades_close_rate, trades.close_rate_requested AS trades_close_rate_requested, trades.close_profit AS trades_close_profit, trades.close_profit_abs AS trades_close_profit_abs, trades.stake_amount AS trades_stake_amount, trades.amount AS trades_amount, trades.amount_requested AS trades_amount_requested, trades.open_date AS trades_open_date, trades.close_date AS trades_close_date, trades.open_order_id AS trades_open_order_id, trades.stop_loss AS trades_stop_loss, trades.stop_loss_pct AS trades_stop_loss_pct, trades.initial_stop_loss AS trades_initial_stop_loss, trades.initial_stop_loss_pct AS trades_initial_stop_loss_pct, trades.stoploss_order_id AS trades_stoploss_order_id, trades.stoploss_last_update AS trades_stoploss_last_update, trades.max_rate AS trades_max_rate, trades.min_rate AS trades_min_rate, trades.sell_reason AS trades_sell_reason, trades.sell_order_status AS trades_sell_order_status, trades.strategy AS trades_strategy, trades.timeframe AS trades_timeframe 
FROM trades 
WHERE trades.open_order_id IS NOT NULL]
(Background on this error at: http://sqlalche.me/e/13/e3q8)

**Comment by alaalimii** [comment]
before this i changed the stake_currency to usdt than to btc and i can not run the bot anymore

**Comment by xmatthias** [comment]
I suspect that you upgraded the bot (most likely to either develop or 2020.12) - and then downgraded to 2020.11.
The column was renamed in #4054 - which was part of the 2020.12 upgrade.
Downgrading to 2020.11 is not possible without removing the database (or manually reverting the column rename).

Please note: We do not support downgrades - as the bot's behaviour can change over time - and making sure every change does not impact prior versions would heaviy increase development complexity, and since this is a free, open source project, we don't have the ressources to do so.

so either delete the database, or (better) switch back to the newer version you used before (as said, most likely `2020.12` or `develop`)

**Comment by alaalimii** [comment]
thank you for your answer, how can i switch back to the newer version

**Comment by xmatthias** [comment]
i suppose the same way you used to switch back to the old version?

depending on how you installed freqtrade, maybe it's running `./setup.sh -u` - or using `docker-compose pull` (you may need to change the image name you use in the compsoe file).

However, without knowing HOW you installed the bot, this is difficult to determine.

**Comment by alaalimii** [comment]
can i manually change the column name ? and in which file ?

**Comment by alaalimii** [comment]
i did it manually and it works i didn't want to change the version because i made many changes , thank u very much ;)

**Comment by alaalimii** [comment]
should ii close the issue

**Comment by xmatthias** [comment]
I can close the issue - no problem :+1:
