### ISSUE TITLE
Cannot run the bot with default config.json configuration.

### ISSUE THREAD

**Issue by Hawksama** [freqtrade/freqtrade#4192]
## Describe your environment

  * Operating system: Raspberry Pi Buster
  * Python Version: Python 3.7.3
  * CCXT version: no output
  * Freqtrade Version: freqtrade 2020.12
    
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

Using the default config_full.json file, the plugin cannot run. Python errors.

### Steps to reproduce:

  1. git checkout develop
  2. freqtrade trade
  
### Observed Results:

  * What happened?
  - The script cannot run - *Fatal exception* and I don't think is from the config.json

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
2021-01-11 16:38:29,970 - freqtrade.worker - INFO - Starting worker develop-0c6c5162
2021-01-11 16:38:29,974 - freqtrade.configuration.configuration - INFO - Using config: config.json ...
2021-01-11 16:38:29,994 - freqtrade.loggers - INFO - Verbosity set to 0
2021-01-11 16:38:30,000 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
2021-01-11 16:38:30,003 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2021-01-11 16:38:30,006 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:///tradesv3.dryrun.sqlite"
2021-01-11 16:38:30,009 - freqtrade.configuration.configuration - INFO - Using max_open_trades: inf ...
2021-01-11 16:38:30,019 - freqtrade.configuration.configuration - INFO - Using user-data directory: /var/www/html/freqtrade/user_data ...
2021-01-11 16:38:30,025 - freqtrade.configuration.configuration - INFO - Using data directory: /var/www/html/freqtrade/user_data/data/bittrex ...
2021-01-11 16:38:30,029 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2021-01-11 16:38:30,033 - freqtrade.configuration.check_exchange - INFO - Exchange "bittrex" is officially supported by the Freqtrade development team.
2021-01-11 16:38:30,036 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2021-01-11 16:38:30,039 - freqtrade.freqtradebot - INFO - Starting freqtrade develop-0c6c5162
2021-01-11 16:38:30,395 - freqtrade.resolvers.iresolver - WARNING - Could not import /var/www/html/freqtrade/user_data/strategies/TechnicalExampleStrategy.py due to 'No module named 'technical''
2021-01-11 16:38:30,419 - freqtrade.resolvers.iresolver - WARNING - Could not import /var/www/html/freqtrade/user_data/strategies/ReinforcedSmoothScalp.py due to 'No module named 'technical''
2021-01-11 16:38:30,492 - freqtrade.resolvers.iresolver - WARNING - Could not import /var/www/html/freqtrade/user_data/strategies/ReinforcedAverageStrategy.py due to 'No module named 'technical''
2021-01-11 16:38:30,510 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy Strategy002 from '/var/www/html/freqtrade/user_data/strategies/Strategy002.py'...
2021-01-11 16:38:30,516 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'minimal_roi' with value in config file: {'40': 0.0, '30': 0.01, '20': 0.02, '0': 0.04}.
2021-01-11 16:38:30,519 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 5m.
2021-01-11 16:38:30,522 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stoploss' with value in config file: -0.1.
2021-01-11 16:38:30,526 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'trailing_stop' with value in config file: False.
2021-01-11 16:38:30,529 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'trailing_stop_positive' with value in config file: 0.005.
2021-01-11 16:38:30,532 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'trailing_stop_positive_offset' with value in config file: 0.0051.
2021-01-11 16:38:30,535 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'trailing_only_offset_is_reached' with value in config file: False.
2021-01-11 16:38:30,538 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'order_types' with value in config file: {'buy': 'limit', 'sell': 'limit', 'emergencysell': 'market', 'stoploss': 'market', 'stoploss_on_exchange': False, 'stoploss_on_exchange_interval': 60}.
2021-01-11 16:38:30,542 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'order_time_in_force' with value in config file: {'buy': 'gtc', 'sell': 'gtc'}.
2021-01-11 16:38:30,545 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: BTC.
2021-01-11 16:38:30,548 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 0.0025.
2021-01-11 16:38:30,552 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'protections' with value in config file: [{'method': 'StoplossGuard', 'lookback_period_candles': 60, 'trade_limit': 4, 'stop_duration_candles': 60, 'only_per_pair': False}, {'method': 'CooldownPeriod', 'stop_duration_candles': 20}, {'method': 'MaxDrawdown', 'lookback_period_candles': 200, 'trade_limit': 20, 'stop_duration_candles': 10, 'max_allowed_drawdown': 0.2}].
2021-01-11 16:38:30,555 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'buy': 10, 'sell': 30}.
2021-01-11 16:38:30,558 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'use_sell_signal' with value in config file: True.
2021-01-11 16:38:30,562 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'sell_profit_only' with value in config file: False.
2021-01-11 16:38:30,565 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ignore_roi_if_buy_signal' with value in config file: False.
2021-01-11 16:38:30,568 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'disable_dataframe_checks' with value in config file: False.
2021-01-11 16:38:30,571 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'40': 0.0, '30': 0.01, '20': 0.02, '0': 0.04}
2021-01-11 16:38:30,574 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 5m
2021-01-11 16:38:30,577 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.1
2021-01-11 16:38:30,581 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2021-01-11 16:38:30,584 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive: 0.005
2021-01-11 16:38:30,587 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0051
2021-01-11 16:38:30,590 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2021-01-11 16:38:30,593 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
2021-01-11 16:38:30,597 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'emergencysell': 'market', 'stoploss': 'market', 'stoploss_on_exchange': False, 'stoploss_on_exchange_interval': 60}
2021-01-11 16:38:30,600 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
2021-01-11 16:38:30,603 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: BTC
2021-01-11 16:38:30,606 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 0.0025
2021-01-11 16:38:30,609 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: [{'method': 'StoplossGuard', 'lookback_period_candles': 60, 'trade_limit': 4, 'stop_duration_candles': 60, 'only_per_pair': False}, {'method': 'CooldownPeriod', 'stop_duration_candles': 20}, {'method': 'MaxDrawdown', 'lookback_period_candles': 200, 'trade_limit': 20, 'stop_duration_candles': 10, 'max_allowed_drawdown': 0.2}]
2021-01-11 16:38:30,612 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 0
2021-01-11 16:38:30,616 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'buy': 10, 'sell': 30}
2021-01-11 16:38:30,619 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_sell_signal: True
2021-01-11 16:38:30,622 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_only: False
2021-01-11 16:38:30,625 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_buy_signal: False
2021-01-11 16:38:30,628 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2021-01-11 16:38:30,633 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2021-01-11 16:38:30,721 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2021-01-11 16:38:30,724 - freqtrade.exchange.exchange - INFO - Using CCXT 1.40.29
2021-01-11 16:38:30,728 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2021-01-11 16:38:30,826 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': False, 'rateLimit': 500, 'aiohttp_trust_env': False}
2021-01-11 16:38:30,921 - freqtrade.exchange.exchange - INFO - Using Exchange "Bittrex"
2021-01-11 16:38:35,152 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Bittrex'...
2021-01-11 16:38:35,756 - freqtrade.wallets - INFO - Wallets synced.
2021-01-11 16:38:35,818 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from '/var/www/html/freqtrade/freqtrade/plugins/pairlist/StaticPairList.py'...
2021-01-11 16:38:35,846 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist VolumePairList from '/var/www/html/freqtrade/freqtrade/plugins/pairlist/VolumePairList.py'...
2021-01-11 16:38:35,948 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist AgeFilter from '/var/www/html/freqtrade/freqtrade/plugins/pairlist/AgeFilter.py'...
2021-01-11 16:38:35,989 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist PrecisionFilter from '/var/www/html/freqtrade/freqtrade/plugins/pairlist/PrecisionFilter.py'...
2021-01-11 16:38:36,055 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist PriceFilter from '/var/www/html/freqtrade/freqtrade/plugins/pairlist/PriceFilter.py'...
2021-01-11 16:38:36,114 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist SpreadFilter from '/var/www/html/freqtrade/freqtrade/plugins/pairlist/SpreadFilter.py'...
2021-01-11 16:38:36,161 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist RangeStabilityFilter from '/var/www/html/freqtrade/freqtrade/plugins/pairlist/rangestabilityfilter.py'...
2021-01-11 16:38:36,192 - freqtrade.resolvers.iresolver - INFO - Using resolved protection StoplossGuard from '/var/www/html/freqtrade/freqtrade/plugins/protections/stoploss_guard.py'...
2021-01-11 16:38:36,228 - freqtrade.resolvers.iresolver - INFO - Using resolved protection CooldownPeriod from '/var/www/html/freqtrade/freqtrade/plugins/protections/cooldown_period.py'...
2021-01-11 16:38:36,251 - freqtrade.resolvers.iresolver - INFO - Using resolved protection MaxDrawdown from '/var/www/html/freqtrade/freqtrade/plugins/protections/max_drawdown_protection.py'...
2021-01-11 16:38:36,589 - freqtrade.commands.trade_commands - ERROR - '<' not supported between instances of 'NoneType' and 'NoneType'
2021-01-11 16:38:36,592 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/var/www/html/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/var/www/html/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/var/www/html/freqtrade/freqtrade/worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/var/www/html/freqtrade/freqtrade/freqtradebot.py", line 94, in __init__
    self.active_pair_whitelist = self._refresh_active_whitelist()
  File "/var/www/html/freqtrade/freqtrade/freqtradebot.py", line 222, in _refresh_active_whitelist
    self.pairlists.refresh_pairlist()
  File "/var/www/html/freqtrade/freqtrade/plugins/pairlistmanager.py", line 90, in refresh_pairlist
    pairlist = pairlist_handler.filter_pairlist(pairlist, tickers)
  File "/var/www/html/freqtrade/freqtrade/plugins/pairlist/VolumePairList.py", line 106, in filter_pairlist
    sorted_tickers = sorted(filtered_tickers, reverse=True, key=lambda t: t[self._sort_key])
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
  ```

**Comment by xmatthias** [comment]
the reason is that bittrex no longer supports volumepairlist as it's not providing the necessary information.

I've changed the full config now to use binance - where all configured options are supported.

**Comment by Hawksama** [comment]
Works like a champ. Thank you, Matthias!
