### ISSUE TITLE
After x amount of time I get this error trying to run any Original error was: No module named 'numpy.core._multiarray_umath'

### ISSUE THREAD

**Issue by blake-wright** [freqtrade/freqtrade#4195]
## Describe your environment

  * Operating system: macOS Big Sur 11.0.1
  * Python Version: 3.8.5 (`python -V`)
  * CCXT version: 1.40.25 (`pip freeze | grep ccxt`)
  * Freqtrade Version: develop-5102dfd6 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  * Freqtrade Version wont run due to error listed below
  
## Your question

I get this error after a random amount of time. Any freqtrade command gives the same error. 

To fix this I usually have to deactivate the environment and rerun the setup install command.

Is it possible to fix this so I don't have to run the install every so often?

```
(.env) (base) Blakes-MBP:freqtrade blake$ freqtrade backtesting --strategy testStrat
Traceback (most recent call last):
  File "/Users/blake/Desktop/freqtrade/.env/bin/freqtrade", line 11, in <module>
    load_entry_point('freqtrade', 'console_scripts', 'freqtrade')()
  File "/Users/blake/Desktop/freqtrade/.env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/blake/Desktop/freqtrade/.env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2862, in load_entry_point
    return ep.load()
  File "/Users/blake/Desktop/freqtrade/.env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2462, in load
    return self.resolve()
  File "/Users/blake/Desktop/freqtrade/.env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2468, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/blake/Desktop/freqtrade/freqtrade/main.py", line 15, in <module>
    from freqtrade.commands import Arguments
  File "/Users/blake/Desktop/freqtrade/freqtrade/commands/__init__.py", line 10, in <module>
    from freqtrade.commands.build_config_commands import start_new_config
  File "/Users/blake/Desktop/freqtrade/freqtrade/commands/build_config_commands.py", line 9, in <module>
    from freqtrade.exchange import MAP_EXCHANGE_CHILDCLASS, available_exchanges
  File "/Users/blake/Desktop/freqtrade/freqtrade/exchange/__init__.py", line 4, in <module>
    from freqtrade.exchange.exchange import Exchange
  File "/Users/blake/Desktop/freqtrade/freqtrade/exchange/exchange.py", line 18, in <module>
    from pandas import DataFrame
  File "/Users/blake/Desktop/freqtrade/.env/lib/python3.8/site-packages/pandas/__init__.py", line 16, in <module>
    raise ImportError(
ImportError: Unable to import required dependencies:
numpy: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.8 from "/Users/blake/Desktop/freqtrade/.env/bin/python3.8"
  * The NumPy version is: "1.19.5"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'

(.env) (base) Blakes-MBP:freqtrade blake$ 
```

**Comment by xmatthias** [comment]
Please fill out the issue template.

It seems like your numpy installation is broken.
A reinstallation should fix this - however pay close attention to the output - maybe installing numpy will show some warnings while installing.

**Comment by blake-wright** [comment]
> 
> 
> Please fill out the issue template.
> 
> It seems like your numpy installation is broken.
> A reinstallation should fix this - however pay close attention to the output - maybe installing numpy will show some warnings while installing.

So I tried uninstalling numpy before. However, it gave me a pandas error and I quit there.

I was able to fix the problem by reinstalling both numpy and pandas. I don't know how long this will hold but I can monitor or just write a script to do it every time because I assume it is strictly environmental.

**Comment by xmatthias** [comment]
in general (assuming you don't touch the virtual environment) this should hold "forever". 

if it doesn't then maybe it's something mac - specific ... but that's something thats generic python / macos stuff, not something we will be able to help you with.
