### ISSUE TITLE
cant even run the bot in sandbox

### ISSUE THREAD

**Issue by gring0-cripto** [freqtrade/freqtrade#4196]
So i am watching this course from Montreal Trading Group and got to the part where i need to test my bot, but i cant run it, even while specifying what strategy i want to use (which is what the bot is telling me to do)
Im kinda noobish in the python world, but i am a PC Technician so i can manage to get around problems, but this one is being hard for me to resolve. tried to search for similar problems and havent found anything similar. 
thank you!

(.env) gring0@gring0-trading:~/freqtrade$ freqtrade trade -c config.json --strategy user_data/strategies/sample_strategy.py 
2021-01-11 20:06:11,829 - freqtrade.worker - INFO - Starting worker develop-5102dfd6
2021-01-11 20:06:11,830 - freqtrade.configuration.configuration - INFO - Using config: config.json ...
2021-01-11 20:06:11,871 - freqtrade.loggers - INFO - Verbosity set to 0
2021-01-11 20:06:11,872 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
2021-01-11 20:06:11,873 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2021-01-11 20:06:11,873 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:///tradesv3.dryrun.sqlite"
2021-01-11 20:06:11,873 - freqtrade.configuration.configuration - INFO - Using max_open_trades: None ...
2021-01-11 20:06:11,875 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/gring0/freqtrade/user_data ...
2021-01-11 20:06:11,877 - freqtrade.configuration.configuration - INFO - Using data directory: /home/gring0/freqtrade/user_data/data/binance ...
2021-01-11 20:06:11,877 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2021-01-11 20:06:11,877 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2021-01-11 20:06:11,877 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2021-01-11 20:06:11,878 - freqtrade.freqtradebot - INFO - Starting freqtrade develop-5102dfd6
2021-01-11 20:06:11,939 - freqtrade.resolvers.iresolver - WARNING - Could not import /home/gring0/freqtrade/user_data/strategies/teststart1.py due to 'libta_lib.so.0: cannot open shared object file: No such file or directory'
2021-01-11 20:06:11,956 - freqtrade.resolvers.iresolver - WARNING - Could not import /home/gring0/freqtrade/user_data/strategies/sample_strategy.py due to 'libta_lib.so.0: cannot open shared object file: No such file or directory'
2021-01-11 20:06:11,957 - freqtrade.commands.trade_commands - ERROR - Impossible to load Strategy 'user_data/strategies/sample_strategy.py'. This class does not exist or contains Python code errors.
2021-01-11 20:06:11,957 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/gring0/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/home/gring0/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/home/gring0/freqtrade/freqtrade/worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/home/gring0/freqtrade/freqtrade/freqtradebot.py", line 66, in __init__
    self.strategy: IStrategy = StrategyResolver.load_strategy(self.config)
  File "/home/gring0/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 45, in load_strategy
    strategy: IStrategy = StrategyResolver._load_strategy(
  File "/home/gring0/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 203, in _load_strategy
    raise OperationalException(
freqtrade.exceptions.OperationalException: Impossible to load Strategy 'user_data/strategies/sample_strategy.py'. This class does not exist or contains Python code errors.

**Comment by blake-wright** [comment]
Ahh I found freqtrade from MTG as well but their course was outdated to the current version (or the one I watched).

Have you tried the command ```freqtrade list-strategies``` to ensure it is seen first?

**Comment by gring0-cripto** [comment]
> Ahh I found freqtrade from MTG as well but their course was outdated to the current version (or the one I watched).
> 
> Have you tried the command `freqtrade list-strategies` to ensure it is seen first?

No brother i haven't, will try it now

**Comment by xmatthias** [comment]
Please use [the documentation](https://www.freqtrade.io/en/latest/) before opening issues.

The way to specify a strategy is clearly documented (it needs the class name - not the file path).

Also, please get used to filling out the issue template - i'll avoid waste of time by going back / forth asking what should've been provided already.
