### ISSUE TITLE
Hyperopt crashes when using the protections feature

### ISSUE THREAD

**Issue by fbloo** [freqtrade/freqtrade#4208]
## Describe your environment

  * Operating system: macOS Cataline 10.15.7
  * Python Version: Python 3.8.5
  * CCXT version:ccxt==1.40.30
  * Freqtrade Version: develop-d289fe44
 

## Describe the problem:
The documentation states that Hyperopt supports the protections feature. However, Hyperopts crash when `--enable-protections` is used.  The Hyperopt itself works fine without enabling the protections.

Unfortunately I haven't been able to check whether it works inside a Docker container.

### Steps to reproduce:

  1. Create a configuration with protections:
```
      "protections": [
        {
            "method": "StoplossGuard",
            "lookback_period_candles": 24,
            "trade_limit": 8,
            "stop_duration_candles": 12,
            "only_per_pair": false
        },
        {
            "method": "CooldownPeriod",
            "stop_duration_candles": 12
        }      
    ],
```
  2. Execute a hyperopt with  `--enable-protections` 
  
### Observed Results:

  * What happened? Freqtrade crashes when hyperopts starts with the actual "calculations/simulations". 
  * What did you expect to happen? A hyperopt that doesn't crash.

Remarkable is that backtesting works perfectly when doing backtests.

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
...
2021-01-13 21:35:58,744 - freqtrade.optimize.hyperopt - INFO - Found 4 CPU cores. Let's make them scream!
2021-01-13 21:35:58,744 - freqtrade.optimize.hyperopt - INFO - Number of parallel jobs set as: -1
2021-01-13 21:35:58,775 - freqtrade.optimize.hyperopt - INFO - Effective number of parallel workers used: 4

2021-01-13 21:36:05,705 - freqtrade - ERROR - Fatal exception!
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/Users/MyUser/code/freqtrade/.env/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker
    r = call_item()
  File "/Users/MyUser/code/freqtrade/.env/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/Users/MyUser/code/freqtrade/.env/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/Users/MyUser/code/freqtrade/.env/lib/python3.8/site-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/Users/MyUser/code/freqtrade/.env/lib/python3.8/site-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/Users/MyUser/code/freqtrade/.env/lib/python3.8/site-packages/joblib/externals/loky/cloudpickle_wrapper.py", line 38, in __call__
    return self._obj(*args, **kwargs)
  File "/Users/MyUser/code/freqtrade/freqtrade/optimize/hyperopt.py", line 538, in generate_optimizer
    backtesting_results = self.backtesting.backtest(
  File "/Users/MyUser/code/freqtrade/freqtrade/optimize/backtesting.py", line 416, in backtest
    self.protections.stop_per_pair(pair, row[DATE_IDX])
  File "/Users/MyUser/code/freqtrade/freqtrade/plugins/protectionmanager.py", line 70, in stop_per_pair
    PairLocks.lock_pair(pair, until, reason, now=now)
  File "/Users/MyUser/code/freqtrade/freqtrade/persistence/pairlock_middleware.py", line 46, in lock_pair
    lock_end_time=timeframe_to_next_date(PairLocks.timeframe, until),
  File "/Users/MyUser/code/freqtrade/freqtrade/exchange/exchange.py", line 1329, in timeframe_to_next_date
    new_timestamp = ccxt.Exchange.round_timeframe(timeframe, date.timestamp() * 1000,
  File "/Users/MyUser/code/freqtrade/.env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1674, in round_timeframe
    ms = Exchange.parse_timeframe(timeframe) * 1000
  File "/Users/MyUser/code/freqtrade/.env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1652, in parse_timeframe
    amount = int(timeframe[0:-1])
ValueError: invalid literal for int() with base 10: ''
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/MyUser/code/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/Users/MyUser/code/freqtrade/freqtrade/commands/optimize_commands.py", line 83, in start_hyperopt
    hyperopt.start()
  File "/Users/MyUser/code/freqtrade/freqtrade/optimize/hyperopt.py", line 716, in start
    f_val = self.run_optimizer_parallel(parallel, asked, i)
  File "/Users/MyUser/code/freqtrade/freqtrade/optimize/hyperopt.py", line 620, in run_optimizer_parallel
    return parallel(delayed(
  File "/Users/MyUser/code/freqtrade/.env/lib/python3.8/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/Users/MyUser/code/freqtrade/.env/lib/python3.8/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/Users/MyUser/code/freqtrade/.env/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
ValueError: invalid literal for int() with base 10: ''
  ```

**Comment by xmatthias** [comment]
well backtesting is "simpler" in that regards, as it starts once (in the main thread) - and runs everything there.

For hyperopt, backtesting starts in multiple processes, so everything needs to be setup correctly again and again.

There's a reason it's labeled "Beta feature" - as it may have some quirks i didn't test for (i did test with hyperopt, but not with all locks). :laughing: 

Will be fixed soon

**Comment by fbloo** [comment]
Ah I see, that's makes it more complex. I knew it was a beta function, but to get it out of beta we need to test it haha ;)

Just tested with the bugfix and it works smoothly. Thanks for your quick support!

**Comment by xmatthias** [comment]
> Ah I see, that's makes it more complex. I knew it was a beta function, but to get it out of beta we need to test it haha ;)

yes, opening an issue is exactly what's needed in these cases :+1:
