### ISSUE TITLE
This class does not exist or contains Python code errors.

### ISSUE THREAD

**Issue by fatrybl** [freqtrade/freqtrade#4217]
## Describe your environment

  * Operating system: Ubuntu 20.04
  * Python Version:3.8.5 
  * CCXT version: 1.40.30
  * Freqtrade Version: develop-d289fe44

## Describe the problem:
Again this bitten problem with "This class does not exist or contains Python code errors". I`m trying to start the bot. If i type " freqtrade list-strategies" it finds my strategies and says OK. 

### Steps to reproduce:

  1.I create new strategy: freqtrade new-strategy --strategy AwesomeStrategy
  2. Then i try to launch it: freqtrade trade -c user_data/test_config.json -s user_data/strategies/AwesomeStrategy
  3. test_config.json presents in the folder /user_data/ 
  This is a simple file which i got from those which had been already there.
 
### Relevant code exceptions or logs

```
(.env) (base) mark@mark:~/Desktop/trading/freqtrade$ freqtrade list-strategies
2021-01-15 00:35:57,600 - freqtrade.loggers - INFO - Verbosity set to 0
2021-01-15 00:35:57,601 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/mark/Desktop/trading/freqtrade/user_data ...
2021-01-15 00:35:57,601 - freqtrade.configuration.configuration - INFO - Using data directory: /home/mark/Desktop/trading/freqtrade/user_data/data ...
2021-01-15 00:35:57,602 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
+-----------------+--------------------+----------+
|            name |           location |   status |
|-----------------+--------------------+----------|
| AwesomeStrategy | AwesomeStrategy.py |       OK |
|     Strategy002 |     Strategy002.py |       OK |
|           eniyi |   test_strategy.py |       OK |
+-----------------+--------------------+----------+
(.env) (base) mark@mark:~/Desktop/trading/freqtrade$ freqtrade trade -c user_data/test_config.json -s user_data/strategies/AwesomeStrategy
2021-01-15 00:36:13,179 - freqtrade.worker - INFO - Starting worker develop-d289fe44
2021-01-15 00:36:13,180 - freqtrade.configuration.configuration - INFO - Using config: user_data/test_config.json ...
2021-01-15 00:36:13,181 - freqtrade.loggers - INFO - Verbosity set to 0
2021-01-15 00:36:13,181 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
2021-01-15 00:36:13,181 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2021-01-15 00:36:13,181 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:///tradesv3.dryrun.sqlite"
2021-01-15 00:36:13,181 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 3 ...
2021-01-15 00:36:13,181 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/mark/Desktop/trading/freqtrade/user_data ...
2021-01-15 00:36:13,182 - freqtrade.configuration.configuration - INFO - Using data directory: /home/mark/Desktop/trading/freqtrade/user_data/data/binance ...
2021-01-15 00:36:13,182 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2021-01-15 00:36:13,182 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2021-01-15 00:36:13,182 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2021-01-15 00:36:13,182 - freqtrade.freqtradebot - INFO - Starting freqtrade develop-d289fe44
2021-01-15 00:36:13,204 - freqtrade.commands.trade_commands - ERROR - Impossible to load Strategy 'user_data/strategies/AwesomeStrategy'. This class does not exist or contains Python code errors.
2021-01-15 00:36:13,205 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/mark/Desktop/trading/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/home/mark/Desktop/trading/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/home/mark/Desktop/trading/freqtrade/freqtrade/worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/home/mark/Desktop/trading/freqtrade/freqtrade/freqtradebot.py", line 66, in __init__
    self.strategy: IStrategy = StrategyResolver.load_strategy(self.config)
  File "/home/mark/Desktop/trading/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 45, in load_strategy
    strategy: IStrategy = StrategyResolver._load_strategy(
  File "/home/mark/Desktop/trading/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 205, in _load_strategy
    raise OperationalException(
freqtrade.exceptions.OperationalException: Impossible to load Strategy 'user_data/strategies/AwesomeStrategy'. This class does not exist or contains Python code errors.

```

**Comment by xmatthias** [comment]
Freqtrade requires the strategy class Name (as [documented here](https://www.freqtrade.io/en/latest/strategy-customization/#install-a-custom-strategy-file), not the path to the strategy.

Your command shall therefore look as follows:
```
freqtrade trade -c user_data/test_config.json -s AwesomeStrategy
```
