### ISSUE TITLE
Issues when developing witht dev container 

### ISSUE THREAD

**Issue by sherryxiao1988** [freqtrade/freqtrade#4230]
Hi, I am new to devcontainer,  trying to build it the first time. the container seems to be running fine without error. but when I run the freqtrade command, I got the following error.
```
ftuser@3b8b6e473c99:/freqtrade$ freqtrade --help
Traceback (most recent call last):
  File "/usr/local/bin/freqtrade", line 33, in <module>
    sys.exit(load_entry_point('freqtrade', 'console_scripts', 'freqtrade')())
  File "/usr/local/bin/freqtrade", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/freqtrade/freqtrade/main.py", line 15, in <module>
    from freqtrade.commands import Arguments
  File "/freqtrade/freqtrade/commands/__init__.py", line 10, in <module>
    from freqtrade.commands.build_config_commands import start_new_config
  File "/freqtrade/freqtrade/commands/build_config_commands.py", line 5, in <module>
    from questionary import Separator, prompt
ModuleNotFoundError: No module named 'questionary'
```

Do I need to install the dependencies again? It should be installed in the dockfile already?
thanks!

**Comment by xmatthias** [comment]
seems to be no longer installing correctly (which i'm not sure why).

Honestly, maintaining devcontainer is a bit of a pain. 
It SHOULD simplify development - but it's highly inconsistent (it works slightly different when running locally or on github codespaces, because codespaces does not support some options).
keeping it working for both has shown to be difficult...

I'll have a look eventually - but it might take a bit.
