### ISSUE TITLE
Crash calculating the spread (division by 0)

### ISSUE THREAD

**Issue by rock-eye** [freqtrade/freqtrade#4267]
## Describe your environment

  * Operating system: Debian 10.6
  * Python Version: 3.7.3 (`python -V`)
  * CCXT version: 1.39.79 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2020.12 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  * Exchange: Binance
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

I've had two crashes for the same reason of division by 0 when calculating the spread.

### Steps to reproduce:

I guess it depends on some market condition. I use Binance.
  
### Observed Results:

  * What happened? Bot crashed
  * What did you expect to happen? Division by 0 should be avoided

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  Jan 25 02:29:55 vm01 python[12114]: 2021-01-25 02:29:55,095 - SpreadFilter - INFO - Removed TCT/USDT from whitelist, because spread 0.565% > 0.5%
Jan 25 02:29:55 vm01 python[12114]: 2021-01-25 02:29:55,095 - SpreadFilter - INFO - Removed TROY/USDT from whitelist, because spread 0.646% > 0.5%
Jan 25 02:29:55 vm01 python[12114]: 2021-01-25 02:29:55,096 - SpreadFilter - INFO - Removed VITE/USDT from whitelist, because spread 0.725% > 0.5%
Jan 25 02:29:55 vm01 python[12114]: 2021-01-25 02:29:55,096 - SpreadFilter - INFO - Removed WING/USDT from whitelist, because spread 0.632% > 0.5%
Jan 25 02:29:55 vm01 python[12114]: 2021-01-25 02:29:55,096 - SpreadFilter - INFO - Removed WTC/USDT from whitelist, because spread 0.547% > 0.5%
Jan 25 02:29:55 vm01 python[12114]: 2021-01-25 02:29:55,097 - freqtrade.commands.trade_commands - ERROR - float division by zero
Jan 25 02:29:55 vm01 python[12114]: 2021-01-25 02:29:55,097 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Jan 25 02:29:55 vm01 python[12114]: Traceback (most recent call last):
Jan 25 02:29:55 vm01 python[12114]:   File "/opt/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
Jan 25 02:29:55 vm01 python[12114]:     worker.run()
Jan 25 02:29:55 vm01 python[12114]:   File "/opt/freqtrade/freqtrade/worker.py", line 74, in run
Jan 25 02:29:55 vm01 python[12114]:     state = self._worker(old_state=state)
Jan 25 02:29:55 vm01 python[12114]:   File "/opt/freqtrade/freqtrade/worker.py", line 111, in _worker
Jan 25 02:29:55 vm01 python[12114]:     self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
Jan 25 02:29:55 vm01 python[12114]:   File "/opt/freqtrade/freqtrade/worker.py", line 132, in _throttle
Jan 25 02:29:55 vm01 python[12114]:     result = func(*args, **kwargs)
Jan 25 02:29:55 vm01 python[12114]:   File "/opt/freqtrade/freqtrade/worker.py", line 145, in _process_running
Jan 25 02:29:55 vm01 python[12114]:     self.freqtrade.process()
Jan 25 02:29:55 vm01 python[12114]:   File "/opt/freqtrade/freqtrade/freqtradebot.py", line 164, in process
Jan 25 02:29:55 vm01 python[12114]:     self.active_pair_whitelist = self._refresh_active_whitelist(trades)
Jan 25 02:29:55 vm01 python[12114]:   File "/opt/freqtrade/freqtrade/freqtradebot.py", line 222, in _refresh_active_whitelist
Jan 25 02:29:55 vm01 python[12114]:     self.pairlists.refresh_pairlist()
Jan 25 02:29:55 vm01 python[12114]:   File "/opt/freqtrade/freqtrade/plugins/pairlistmanager.py", line 92, in refresh_pairlist
Jan 25 02:29:55 vm01 python[12114]:     pairlist = pairlist_handler.filter_pairlist(pairlist, tickers)
Jan 25 02:29:55 vm01 python[12114]:   File "/opt/freqtrade/freqtrade/plugins/pairlist/IPairList.py", line 113, in filter_pairlist
Jan 25 02:29:55 vm01 python[12114]:     if not self._validate_pair(p, tickers[p] if p in tickers else {}):
Jan 25 02:29:55 vm01 python[12114]:   File "/opt/freqtrade/freqtrade/plugins/pairlist/SpreadFilter.py", line 47, in _validate_pair
Jan 25 02:29:55 vm01 python[12114]:     spread = 1 - ticker['bid'] / ticker['ask']
Jan 25 02:29:55 vm01 python[12114]: ZeroDivisionError: float division by zero
Jan 25 02:29:55 vm01 python[12114]: 2021-01-25 02:29:55,101 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
Jan 25 02:29:55 vm01 python[12114]: 2021-01-25 02:29:55,101 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
Jan 25 02:29:55 vm01 python[12114]: 2021-01-25 02:29:55,164 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
Jan 25 02:29:55 vm01 python[12114]: 2021-01-25 02:29:55,168 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': warning, 'status': "4 open trades active.\n\nHandle these trade
s manually on Binance, or '/start' the bot again and use '/stopbuy' to handle open trades gracefully. \nTrades are simulated."}
Jan 25 02:29:55 vm01 python[12114]: 2021-01-25 02:29:55,201 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
Jan 25 02:29:55 vm01 python[12114]: 2021-01-25 02:29:55,202 - freqtrade.rpc.api_server - INFO - Stopping API Server
Jan 25 02:29:55 vm01 python[12114]: 2021-01-25 02:29:55,306 - freqtrade.rpc.api_server - INFO - Local Rest Server started.
Jan 25 02:29:55 vm01 python[12114]: 2021-01-25 02:29:55,307 - apscheduler.scheduler - INFO - Scheduler has been shut down
Jan 25 02:30:12 vm01 systemd[1]: freqtrade_usdt.service: Succeeded.
  ```

**Comment by xmatthias** [comment]
i wonder what pair this is ... it seems to have no asks - or ask-price is 0 (so it's worthless?) ...

**Comment by rock-eye** [comment]
I do not know, but it would be one of these, which are the following to the WTC/USDT:

            "XEM/USDT",
            "XLM/USDT",
            "XMR/USDT",
            "XRP/USDT",
            "XTZ/USDT",
            "XVS/USDT",
            "XZC/USDT",
            "YFI/USDT",
            "YFII/USDT",
            "ZEC/USDT",
            "ZEN/USDT",
            "ZIL/USDT",
            "ZRX/USDT"

It must be something sporadic because after restarting the bot, it continues to work normally for now. Although I also tell you that it already happened to me again.

I could put a try / catch to monitor it.

**Comment by xmatthias** [comment]
This will now be checked (and logged separately) - available in develop.

If you encounter this again (but as log next time) i'm curious to know which pair this happens ... :)
