### ISSUE TITLE
Edge positioning Fatal exception for not active pairs

### ISSUE THREAD

**Issue by thopd88** [freqtrade/freqtrade#4298]
## Describe the problem:

Edge positioning Fatal exception for not active pairs

### Steps to reproduce:

  1. Whitelist a not active pair (XZC/USDT Binance)
  2. Edge positioning
  
### Observed Results:

  * What happened?
Fatal exception

  * What did you expect to happen?
No error

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

```
freqtrade.data.history.history_utils - INFO - Download history data for pair: "XZC/USDT", timeframe: 5m and store in /freqtrade/user_data/data/binance.
freqtrade.exchange.exchange - INFO - Downloaded data for XZC/USDT with length 0.
freqtrade.commands.trade_commands - ERROR - Length mismatch: Expected axis has 0 elements, new values have 6 elements

freqtrade.commands.trade_commands - ERROR - Fatal exception!
 Traceback (most recent call last):
   File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
     worker = Worker(args)
   File "/freqtrade/freqtrade/worker.py", line 35, in __init__
     self._init(False)
   File "/freqtrade/freqtrade/worker.py", line 52, in _init
     self.freqtrade = FreqtradeBot(self._config)
   File "/freqtrade/freqtrade/freqtradebot.py", line 94, in __init__
     self.active_pair_whitelist = self._refresh_active_whitelist()
   File "/freqtrade/freqtrade/freqtradebot.py", line 227, in _refresh_active_whitelist
     self.edge.calculate()
   File "/freqtrade/freqtrade/edge/edge_positioning.py", line 116, in calculate
     data = load_data(
   File "/freqtrade/freqtrade/data/history/history_utils.py", line 88, in load_data
     hist = load_pair_history(pair=pair, timeframe=timeframe,
   File "/freqtrade/freqtrade/data/history/history_utils.py", line 50, in load_pair_history
     return data_handler.ohlcv_load(pair=pair,
   File "/freqtrade/freqtrade/data/history/idatahandler.py", line 168, in ohlcv_load
     pairdf = self._ohlcv_load(pair, timeframe,
   File "/freqtrade/freqtrade/data/history/jsondatahandler.py", line 90, in _ohlcv_load
     pairdata.columns = self._columns
   File "/usr/local/lib/python3.8/site-packages/pandas/core/generic.py", line 5473, in __setattr__
     return object.__setattr__(self, name, value)
   File "pandas/_libs/properties.pyx", line 66, in pandas._libs.properties.AxisProperty.__set__
   File "/usr/local/lib/python3.8/site-packages/pandas/core/generic.py", line 667, in _set_axis
     self._mgr.set_axis(axis, labels)
   File "/usr/local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 220, in set_axis
     raise ValueError(
 ValueError: Length mismatch: Expected axis has 0 elements, new values have 6 elements
```

**Comment by xmatthias** [comment]
the simplest workaround to this will be to remove this pair from your whitelist.

Edge itself is completely outside of all other pairlist possibilities (one reason why i really dislike the way it's done) - so it'll not respect blacklist, nor will it check if markets are active.

Now that for sure isn't ideal, but i guess users capable of using edge (which is quite advanced), will also be able to work around these restrictions for now.

While this should be fixed for sure, it'll not be in the near term (at least not by me).

**Comment by thopd88** [comment]
Yes, I did. However you don’t know when another pair is inactive...

**Comment by Pascal66** [comment]
It happen for me too, when I use wildcards facility ie *./USDT
@thopd88 edge module isnt updated as others, and like @xmatthias says : "While this should be fixed for sure, it'll not be in the near term (at least not by me)."
