### ISSUE TITLE
When I manually delete a trade freqtrade often crashes

### ISSUE THREAD

**Issue by chard101** [freqtrade/freqtrade#4326]
* Operating system: Ubuntu 20.04: 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64
  * Python Version: Python 3.8.5
  * CCXT version: 1.39.79
  * Freqtrade Version: freqtrade 2021.1
  
## Describe the problem:

I have installed freqtrade on Ubuntu, using the git stable release via the setup script.  I run multiple instances of ft using screen.  I am using Binance as my exchange, I have bots running using 3 different Binance accounts, this issue occurs with them all so it does not seem to be account related.

When I delete a trade manually via telgram ft often crashes.  I've only been using ft recently and have observed the issue with freqtrade 2021.1 and freqtrade 2020.12.

### Steps to reproduce:
From the telegram interface delete your desired trade:

  1. /delete 813
  
### Observed Results:
On telegram:

Deleted trade 813. Closed 1 open orders.
Please make sure to take care of this asset on the exchange manually.

Status: process died

I'm finding that when I manually delete a trade via the telegram interface (/delete 813) for example I see the message "process died) and when I check the screen console session I have the following output

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
2021-02-06 11:31:02,690 - freqtrade.wallets - INFO - Wallets synced.
2021-02-06 11:31:03,996 - freqtrade.persistence.models - WARNING - Did not find order for {'info': {'symbol': 'WNXMUSDT', 'orderId': 39206829, 'orderListId': -1, 'clientOrderId': 'wLpTL7TyVo8gW3v72VJ39q', 'price': '42.94600000', 'origQty': '1.61400000', 'executedQty': '0.00000000', 'cummulativeQuoteQty': '0.00000000', 'status': 'CANCELED', 'timeInForce': 'GTC', 'type': 'STOP_LOSS_LIMIT', 'side': 'SELL', 'stopPrice': '43.38000000', 'icebergQty': '0.00000000', 'time': 1612515602358, 'updateTime': 1612611057338, 'isWorking': False, 'origQuoteOrderQty': '0.00000000'}, 'id': '39206829', 'clientOrderId': 'wLpTL7TyVo8gW3v72VJ39q', 'timestamp': 1612515602358, 'datetime': '2021-02-05T09:00:02.358Z', 'lastTradeTimestamp': None, 'symbol': 'WNXM/USDT', 'type': 'stop_loss_limit', 'timeInForce': 'GTC', 'postOnly': False, 'side': 'sell', 'price': 42.946, 'amount': 1.614, 'cost': 0.0, 'average': None, 'filled': 0.0, 'remaining': 1.614, 'status': 'canceled', 'fee': None, 'trades': None}.
2021-02-06 11:31:04,002 - freqtrade.commands.trade_commands - ERROR - Instance '<Trade at 0x7fab369441c0>' has been deleted, or its row is otherwise not present.
2021-02-06 11:31:04,002 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/ivorysupp/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker.run()
  File "/home/ivorysupp/freqtrade/freqtrade/worker.py", line 74, in run
    state = self._worker(old_state=state)
  File "/home/ivorysupp/freqtrade/freqtrade/worker.py", line 111, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
  File "/home/ivorysupp/freqtrade/freqtrade/worker.py", line 132, in _throttle
    result = func(*args, **kwargs)
  File "/home/ivorysupp/freqtrade/freqtrade/worker.py", line 145, in _process_running
    self.freqtrade.process()
  File "/home/ivorysupp/freqtrade/freqtrade/freqtradebot.py", line 183, in process
    self.exit_positions(trades)
  File "/home/ivorysupp/freqtrade/freqtrade/freqtradebot.py", line 797, in exit_positions
    self.handle_stoploss_on_exchange(trade)):
  File "/home/ivorysupp/freqtrade/freqtrade/freqtradebot.py", line 977, in handle_stoploss_on_exchange
    if trade.open_order_id or not trade.is_open:
  File "/home/ivorysupp/freqtrade/.env/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 294, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/home/ivorysupp/freqtrade/.env/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 725, in get
    value = state._load_expired(state, passive)
  File "/home/ivorysupp/freqtrade/.env/lib/python3.8/site-packages/sqlalchemy/orm/state.py", line 652, in _load_expired
    self.manager.deferred_scalar_loader(self, toload)
  File "/home/ivorysupp/freqtrade/.env/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 1016, in load_scalar_attributes
    raise orm_exc.ObjectDeletedError(state)
sqlalchemy.orm.exc.ObjectDeletedError: Instance '<Trade at 0x7fab369441c0>' has been deleted, or its row is otherwise not present.
2021-02-06 11:31:04,005 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2021-02-06 11:31:04,006 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2021-02-06 11:31:04,045 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2021-02-06 11:31:04,048 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': warning, 'status': "11 open trades active.\n\nHandle these trades manually on Binance, or '/start' the bot again and use '/stopbuy' to handle open trades gracefully. \n"}
2021-02-06 11:31:04,079 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
2021-02-06 11:31:04,080 - apscheduler.scheduler - INFO - Scheduler has been shut down
  ```

Please let me know if you need any other details.

Thanks,

**Comment by zn3x** [comment]
I'm assuming you are deleting open trade before you close it. You need to close it first.
From what I see I think freqtrade is trying to close the trade on stop_loss signal but it doesn't find the trade in database

**Comment by xmatthias** [comment]
i guess the main reason to delete a trade is if you handled it yourself "somehow" on the exchange.

This is an odd circumstance - most parts of the bot-loop are locked for thread safety (but the lock is opened in between steps to allow affected RPC methods to complete without waiting forever) - but having a trade "disappear" wasn't part of that so far, so it's not handled properly (in the end, it's a race condition, depending when in the cycle you make the delete call, it'll be a problem or not.

i guess there are a few solutions, but i'll need to think about the best one (without locking "active" RPC requests like /forcesell and /delete for too long, and also without querying the database over and over again).

**Comment by chard101** [comment]
Hi Chaps, 

Thanks for looking into this.  Essentially I'm seeing a trade I want to handle myself, as it is under water and I want to set my own manual limit order on the exchange, instead of using /forcesell 813 and setting at a loss right there.

Just had another example, the trade is 9% down so I've gone to delete it so I can set a manual limit order for it and I got..

2021-02-10 11:14:14,127 - freqtrade.exchange.binance - INFO - stoploss limit order added for DATA/USDT. stop price: 0.05605. limit: 0.05549
2021-02-10 11:14:15,129 - freqtrade.commands.trade_commands - ERROR - UPDATE statement on table 'trades' expected to update 1 row(s); 0 were matched.
2021-02-10 11:14:15,129 - freqtrade.commands.trade_commands - ERROR - Fatal exception!

Thanks,

**Comment by chard101** [comment]
[crashlog.txt](https://github.com/freqtrade/freqtrade/files/5957767/crashlog.txt)

Please find attached a more extensive log.

Thanks.
