### ISSUE TITLE
Plot-dataframe error out "min() arg is an empty sequence"

### ISSUE THREAD

**Issue by robin2010liu** [freqtrade/freqtrade#4327]
## Describe your environment

  * Operating system: macos
  * Python Version: 3.75 (`python -V`)
  * CCXT version: _1.41.62____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade develop-0806202d/__freqtrade docker-729e7733__ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

  1. docker-compose run --rm freqtrade plot-dataframe --strategy AwesomeStrategy -p BTC/ETH --timerange=20180801-20180805 OR freqtrade plot-dataframe --strategy AwesomeStrategy -p BTC/ETH --timerange=20180801-20180805
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
 A error message showed up.
  * What did you expect to happen?
The data should be plotted.
### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
 Creating freqtrade_freqtrade_run ... done
2021-02-06 15:11:01,012 - freqtrade.configuration.configuration - INFO - Using config: user_data/config.json ...
2021-02-06 15:11:01,017 - freqtrade.loggers - INFO - Verbosity set to 0
2021-02-06 15:11:01,017 - freqtrade.configuration.configuration - INFO - Parameter --timerange detected: 20180801-20180805 ...
2021-02-06 15:11:01,023 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2021-02-06 15:11:01,025 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/binance ...
2021-02-06 15:11:01,025 - freqtrade.configuration.configuration - INFO - Using pairs ['BTC/ETH']
2021-02-06 15:11:01,025 - freqtrade.configuration.configuration - INFO - Limiting plot to: 750
2021-02-06 15:11:01,025 - freqtrade.configuration.configuration - INFO - Using trades from: file
2021-02-06 15:11:01,025 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2021-02-06 15:11:01,025 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2021-02-06 15:11:01,025 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2021-02-06 15:11:01,119 - freqtrade.resolvers.iresolver - WARNING - Could not import /freqtrade/user_data/strategies/MultiRSI.py due to 'No module named 'technical''
2021-02-06 15:11:01,127 - freqtrade.resolvers.iresolver - WARNING - Could not import /freqtrade/user_data/strategies/ReinforcedAverageStrategy.py due to 'No module named 'technical''
2021-02-06 15:11:01,138 - freqtrade.resolvers.iresolver - WARNING - Could not import /freqtrade/user_data/strategies/ReinforcedSmoothScalp.py due to 'No module named 'technical''
2021-02-06 15:11:01,508 - freqtrade.resolvers.iresolver - WARNING - Could not import /freqtrade/user_data/strategies/TechnicalExampleStrategy.py due to 'No module named 'technical''
2021-02-06 15:11:01,513 - freqtrade - ERROR - Impossible to load Strategy 'AwesomeStrategy'. This class does not exist or contains Python code errors.
(.env) robins-MacBook-Pro:freqtrade robin$ docker-compose run --rm freqtrade plot-dataframe --strategy SampleStrategy -p BTC/ETH --timerange=20180801-20180805
Creating freqtrade_freqtrade_run ... done
2021-02-06 15:11:20,569 - freqtrade.configuration.configuration - INFO - Using config: user_data/config.json ...
2021-02-06 15:11:20,571 - freqtrade.loggers - INFO - Verbosity set to 0
2021-02-06 15:11:20,572 - freqtrade.configuration.configuration - INFO - Parameter --timerange detected: 20180801-20180805 ...
2021-02-06 15:11:20,577 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2021-02-06 15:11:20,579 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/binance ...
2021-02-06 15:11:20,579 - freqtrade.configuration.configuration - INFO - Using pairs ['BTC/ETH']
2021-02-06 15:11:20,580 - freqtrade.configuration.configuration - INFO - Limiting plot to: 750
2021-02-06 15:11:20,580 - freqtrade.configuration.configuration - INFO - Using trades from: file
2021-02-06 15:11:20,580 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2021-02-06 15:11:20,580 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2021-02-06 15:11:20,581 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2021-02-06 15:11:20,660 - freqtrade.resolvers.iresolver - WARNING - Could not import /freqtrade/user_data/strategies/MultiRSI.py due to 'No module named 'technical''
2021-02-06 15:11:20,668 - freqtrade.resolvers.iresolver - WARNING - Could not import /freqtrade/user_data/strategies/ReinforcedAverageStrategy.py due to 'No module named 'technical''
2021-02-06 15:11:20,675 - freqtrade.resolvers.iresolver - WARNING - Could not import /freqtrade/user_data/strategies/ReinforcedSmoothScalp.py due to 'No module named 'technical''
2021-02-06 15:11:20,997 - freqtrade.resolvers.iresolver - WARNING - Could not import /freqtrade/user_data/strategies/TechnicalExampleStrategy.py due to 'No module named 'technical''
2021-02-06 15:11:21,004 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy SampleStrategy from '/freqtrade/user_data/strategies/sample_strategy.py'...
2021-02-06 15:11:21,005 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 5m.
2021-02-06 15:11:21,005 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: BTC.
2021-02-06 15:11:21,005 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 0.01.
2021-02-06 15:11:21,006 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'buy': 10, 'sell': 30}.
2021-02-06 15:11:21,006 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'use_sell_signal' with value in config file: True.
2021-02-06 15:11:21,006 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'sell_profit_only' with value in config file: False.
2021-02-06 15:11:21,006 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ignore_roi_if_buy_signal' with value in config file: False.
2021-02-06 15:11:21,007 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'60': 0.01, '30': 0.02, '0': 0.04}
2021-02-06 15:11:21,007 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 5m
2021-02-06 15:11:21,007 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.1
2021-02-06 15:11:21,007 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2021-02-06 15:11:21,008 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2021-02-06 15:11:21,008 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2021-02-06 15:11:21,008 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2021-02-06 15:11:21,008 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
2021-02-06 15:11:21,008 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'market', 'stoploss_on_exchange': False}
2021-02-06 15:11:21,009 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
2021-02-06 15:11:21,009 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: BTC
2021-02-06 15:11:21,010 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 0.01
2021-02-06 15:11:21,010 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 30
2021-02-06 15:11:21,010 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'buy': 10, 'sell': 30}
2021-02-06 15:11:21,010 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_sell_signal: True
2021-02-06 15:11:21,010 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_only: False
2021-02-06 15:11:21,010 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_buy_signal: False
2021-02-06 15:11:21,011 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_offset: 0.0
2021-02-06 15:11:21,011 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2021-02-06 15:11:21,011 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2021-02-06 15:11:21,011 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2021-02-06 15:11:21,012 - freqtrade.exchange.exchange - INFO - Using CCXT 1.41.62
2021-02-06 15:11:21,012 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2021-02-06 15:11:21,019 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 200}
2021-02-06 15:11:21,026 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2021-02-06 15:11:22,398 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2021-02-06 15:11:22,405 - freqtrade.data.history.history_utils - INFO - Using indicator startup period: 30 ...
2021-02-06 15:11:22,407 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/plot_commands.py", line 24, in start_plot_dataframe
    load_and_plot_trades(config)
  File "/freqtrade/freqtrade/plot/plotting.py", line 531, in load_and_plot_trades
    plot_elements = init_plotscript(config, list(exchange.markets), strategy.startup_candle_count)
  File "/freqtrade/freqtrade/plot/plotting.py", line 57, in init_plotscript
    min_date, max_date = get_timerange(data)
  File "/freqtrade/freqtrade/data/history/history_utils.py", line 376, in get_timerange
    return (min(timeranges, key=operator.itemgetter(0))[0],
ValueError: min() arg is an empty sequence
  ```

**Comment by xmatthias** [comment]
Based on the message, it appears like you don't have any data available (or at least none for the timerange selected).

While it should not crash - it'll also not work as you'll need to use download-data to download the data first.

**Comment by robin2010liu** [comment]
@xmatthias thanks!
I checked it. Looks like my data was not in the timerange. But after I corrected it, and run it again. It has some other error complaining about the backtest, should I run the backtest first before plotting.

Traceback (most recent call last):
  File "/Users/robin/Documents/GitHubProj/Investing/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/Users/robin/Documents/GitHubProj/Investing/freqtrade/freqtrade/commands/plot_commands.py", line 24, in start_plot_dataframe
    load_and_plot_trades(config)
  File "/Users/robin/Documents/GitHubProj/Investing/freqtrade/freqtrade/plot/plotting.py", line 531, in load_and_plot_trades
    plot_elements = init_plotscript(config, list(exchange.markets), strategy.startup_candle_count)
  File "/Users/robin/Documents/GitHubProj/Investing/freqtrade/freqtrade/plot/plotting.py", line 76, in init_plotscript
    strategy=config.get('strategy'),
  File "/Users/robin/Documents/GitHubProj/Investing/freqtrade/freqtrade/data/btanalysis.py", line 278, in load_trades
    return load_backtest_data(exportfilename, strategy)
  File "/Users/robin/Documents/GitHubProj/Investing/freqtrade/freqtrade/data/btanalysis.py", line 141, in load_backtest_data
    data = load_backtest_stats(filename)
  File "/Users/robin/Documents/GitHubProj/Investing/freqtrade/freqtrade/data/btanalysis.py", line 122, in load_backtest_stats
    filename = filename / get_latest_backtest_filename(filename)
  File "/Users/robin/Documents/GitHubProj/Investing/freqtrade/freqtrade/data/btanalysis.py", line 76, in get_latest_backtest_filename
    return get_latest_optimize_filename(directory, 'backtest')
  File "/Users/robin/Documents/GitHubProj/Investing/freqtrade/freqtrade/data/btanalysis.py", line 55, in get_latest_optimize_filename
    f"Directory '{directory}' does not seem to contain backtest statistics yet.")
ValueError: Directory '/Users/robin/Documents/GitHubProj/Investing/freqtrade/user_data/backtest_results' does not seem to contain backtest statistics yet.

**Comment by xmatthias** [comment]
i assume you'd want to plot your backtest results - so yes, you'll obviously need to run backtesting beforehand, otherwise you'll not have any trades showing up.

**Comment by robin2010liu** [comment]
Thanks, I got the correct plot after running backtest.
