### ISSUE TITLE
Freqtrade Crashes w/ FTX.US

### ISSUE THREAD

**Issue by ozitrance** [freqtrade/freqtrade#4331]
FIrst of all just wanted to thank you all for this amazing tool and this amazing hard work :1st_place_medal: Thank you!

## Describe your environment

  * Operating system: Ubuntu 20.10
  * Python Version: Python 3.8.6 
  * CCXT version: 1.41.64 
  * Freqtrade Version: develop-f6cdc6d9
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:
Freqtrade crashes when using FTX.US. Seems like it's related to the stop loss order? OR entering/pulling data from the database?

### Steps to reproduce:

  1. Configuring ftx.us as the exchange in the config file (as instructed in [](https://github.com/ccxt/ccxt/issues/7461#issuecomment-673535274)):
  ```
"exchange": {
        "name": "ftx",
        "key": "",
        "secret": "",
        "ccxt_config": {
            "enableRateLimit": true,             
            "hostname": "ftx.us"
        },
        "ccxt_async_config": {
            "enableRateLimit": true,
            "rateLimit": 500
        },
```
  
  2. Running the bot. Seems like it's cancelling the stop-loss order trying to create a new one and then crashes. I think it's related to the database? I saw a lot of these rows when running on dry-run but I though it's only because it is dry run. And it never crashed on dry-run either.:
```
2021-02-07 13:09:43,670 - freqtrade.freqtradebot - INFO - Cancelling current stoploss on exchange for pair ANYPAIR (orderid:dry_run_sell_1612703002.20304) in order to add another one ...
2021-02-07 13:09:43,670 - freqtrade.persistence.models - WARNING - Did not find order for {}.
```
  
### Observed Results:

  * What happened?
  Freqtrade crashes completely. Once it's restarted it crashes again and then the 3rd time it's re-adding the original stop-loss order. Then when it's time to update/create a new stop-loss order (after cancelling an older one) this whole loop starts again.

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  2021-02-07 14:38:10,231 - freqtrade.loggers - INFO - Verbosity set to 0
2021-02-07 14:38:10,231 - freqtrade.configuration.configuration - INFO - Runmode set to live.
2021-02-07 14:38:10,232 - freqtrade.configuration.configuration - INFO - Parameter --db-url detected ...
2021-02-07 14:38:10,232 - freqtrade.configuration.configuration - INFO - Dry run is disabled
2021-02-07 14:38:10,232 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:///user_data/databases/ftxus_USD_1trade_smoothK_01StopLoss_02-07-21.LIVE.sqlite"
2021-02-07 14:38:10,232 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 1 ...
2021-02-07 14:38:10,232 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/oz/freqtrade/user_data ...
2021-02-07 14:38:10,233 - freqtrade.configuration.configuration - INFO - Using data directory: /home/oz/freqtrade/user_data/data/ftx ...
2021-02-07 14:38:10,233 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2021-02-07 14:38:10,233 - freqtrade.configuration.check_exchange - WARNING - Exchange "ftx" is known to the the ccxt library, available for the bot, but not officially supported by the Freqtrade development team. It may work flawlessly (please report back) or have serious issues. Use it at your own discretion.
2021-02-07 14:38:10,233 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2021-02-07 14:38:10,233 - freqtrade.freqtradebot - INFO - Starting freqtrade develop-f6cdc6d9
2021-02-07 14:38:10,246 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy smoothK_01StopLoss from '/home/oz/freqtrade/user_data/strategies/smoothK_01StopLoss.py'...
2021-02-07 14:38:10,247 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USD.
2021-02-07 14:38:10,247 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: unlimited.
2021-02-07 14:38:10,247 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'protections' with value in config file: [{'method': 'StoplossGuard', 'lookback_period_candles': 60, 'trade_limit': 5, 'stop_duration_candles': 240, 'only_per_pair': False}].
2021-02-07 14:38:10,247 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'buy': 10, 'sell': 30}.
2021-02-07 14:38:10,247 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'use_sell_signal' with value in config file: True.
2021-02-07 14:38:10,247 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'sell_profit_only' with value in config file: False.
2021-02-07 14:38:10,247 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ignore_roi_if_buy_signal' with value in config file: True.
2021-02-07 14:38:10,247 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 0.07535489057972716, '25': 0.05266114911935882, '45': 0.0123725116302516, '70': -1}
2021-02-07 14:38:10,247 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 1m
2021-02-07 14:38:10,248 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.01
2021-02-07 14:38:10,248 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: True
2021-02-07 14:38:10,248 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.2088505693949853
2021-02-07 14:38:10,248 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2021-02-07 14:38:10,248 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2021-02-07 14:38:10,248 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
2021-02-07 14:38:10,248 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'market', 'stoploss_on_exchange': True}
2021-02-07 14:38:10,248 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
2021-02-07 14:38:10,248 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USD
2021-02-07 14:38:10,249 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: unlimited
2021-02-07 14:38:10,249 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: [{'method': 'StoplossGuard', 'lookback_period_candles': 60, 'trade_limit': 5, 'stop_duration_candles': 240, 'only_per_pair': False}]
2021-02-07 14:38:10,249 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 0
2021-02-07 14:38:10,249 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'buy': 10, 'sell': 30}
2021-02-07 14:38:10,249 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_sell_signal: True
2021-02-07 14:38:10,249 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_only: False
2021-02-07 14:38:10,249 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_buy_signal: True
2021-02-07 14:38:10,249 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_offset: 0.0
2021-02-07 14:38:10,249 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2021-02-07 14:38:10,249 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2021-02-07 14:38:10,249 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2021-02-07 14:38:10,253 - freqtrade.exchange.exchange - INFO - Using CCXT 1.41.62
2021-02-07 14:38:10,253 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'hostname': 'ftx.us'}
2021-02-07 14:38:10,257 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'hostname': 'ftx.us', 'rateLimit': 500}
2021-02-07 14:38:10,261 - freqtrade.exchange.exchange - INFO - Using Exchange "FTX"
2021-02-07 14:38:10,783 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Ftx'...
2021-02-07 14:38:10,892 - freqtrade.wallets - INFO - Wallets synced.
2021-02-07 14:38:10,894 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist VolumePairList from '/home/oz/freqtrade/freqtrade/plugins/pairlist/VolumePairList.py'...
2021-02-07 14:38:10,897 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist PrecisionFilter from '/home/oz/freqtrade/freqtrade/plugins/pairlist/PrecisionFilter.py'...
2021-02-07 14:38:10,900 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist PriceFilter from '/home/oz/freqtrade/freqtrade/plugins/pairlist/PriceFilter.py'...
2021-02-07 14:38:10,904 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist RangeStabilityFilter from '/home/oz/freqtrade/freqtrade/plugins/pairlist/rangestabilityfilter.py'...
2021-02-07 14:38:10,907 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist PerformanceFilter from '/home/oz/freqtrade/freqtrade/plugins/pairlist/PerformanceFilter.py'...
2021-02-07 14:38:10,909 - freqtrade.resolvers.iresolver - INFO - Using resolved protection StoplossGuard from '/home/oz/freqtrade/freqtrade/plugins/protections/stoploss_guard.py'...
2021-02-07 14:38:10,929 - VolumePairList - INFO - Pair USDT/USD in your blacklist. Removing it from whitelist...
2021-02-07 14:38:10,929 - VolumePairList - INFO - Pair EUR/USD in your blacklist. Removing it from whitelist...
2021-02-07 14:38:10,929 - VolumePairList - INFO - Pair AUD/USD in your blacklist. Removing it from whitelist...
2021-02-07 14:38:10,929 - VolumePairList - INFO - Pair CAD/USD in your blacklist. Removing it from whitelist...
2021-02-07 14:38:10,929 - VolumePairList - INFO - Pair GBP/USD in your blacklist. Removing it from whitelist...
2021-02-07 14:38:10,930 - VolumePairList - INFO - Searching 75 pairs: ['BTC/USD', 'ETH/USD', 'DOGE/USD', 'LINK/USD', 'SUSHI/USD', 'LTC/USD', 'BCH/USD', 'SOL/USD', 'WBTC/USD', 'GRT/USD', 'UNI/USD', 'YFI/USD', 'TRX/USD', 'BAT/USD', 'CUSDT/USD', 'PAXG/USD', 'DAI/USD', 'BRL/USD', 'SGD/USD']
2021-02-07 14:38:10,930 - PriceFilter - INFO - Removed BRL/USD from whitelist, because ticker['last'] is empty (Usually no trade in the last 24h).
2021-02-07 14:38:10,930 - PriceFilter - INFO - Removed SGD/USD from whitelist, because ticker['last'] is empty (Usually no trade in the last 24h).
2021-02-07 14:38:19,764 - freqtrade.rpc.rpc_manager - INFO - Enabling rpc.telegram ...
2021-02-07 14:38:19,886 - apscheduler.scheduler - INFO - Scheduler started
2021-02-07 14:38:21,939 - freqtrade.rpc.telegram - INFO - rpc.telegram is listening for following commands: [['status'], ['profit'], ['balance'], ['start'], ['stop'], ['forcesell'], ['forcebuy'], ['trades'], ['delete'], ['performance'], ['stats'], ['daily'], ['count'], ['locks'], ['reload_config', 'reload_conf'], ['show_config', 'show_conf'], ['stopbuy'], ['whitelist'], ['blacklist'], ['logs'], ['edge'], ['help'], ['version']]
2021-02-07 14:38:21,940 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'running'}
2021-02-07 14:38:22,513 - freqtrade.worker - INFO - Changing state to: RUNNING
2021-02-07 14:38:22,513 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': "*Exchange:* `ftx`\n*Stake per trade:* `unlimited USD`\n*Minimum ROI:* `{'0': 0.07535489057972716, '25': 0.05266114911935882, '45': 0.0123725116302516, '70': -1}`\n*Trailing Stoploss:* `-0.01`\n*Timeframe:* `1m`\n*Strategy:* `smoothK_01StopLoss`"}
2021-02-07 14:38:22,789 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': "Searching for USD pairs to buy and sell based on [{'VolumePairList': 'VolumePairList - top 75 volume pairs.'}, {'PrecisionFilter': 'PrecisionFilter - Filtering untradable pairs.'}, {'PriceFilter': 'PriceFilter - Filtering pairs priced below 1.0%.'}, {'RangeStabilityFilter': 'RangeStabilityFilter - Filtering pairs with rate of change below 0.01 over the last days.'}, {'PerformanceFilter': 'PerformanceFilter - Sorting pairs by performance.'}]"}
2021-02-07 14:38:23,071 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': 'Using Protections: \nStoplossGuard - Frequent Stoploss Guard, 5 stoplosses within 60 candles.'}
2021-02-07 14:38:23,376 - freqtrade.persistence.models - INFO - Found open trade: Trade(id=1, pair=BTC/USD, amount=0.05110000, open_rate=38621.00000000, open_since=2021-02-07 13:36:36)
2021-02-07 14:38:23,380 - freqtrade.freqtradebot - INFO - Updating 1 open orders.
2021-02-07 14:38:23,538 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=1, pair=BTC/USD, amount=0.05110000, open_rate=38621.00000000, open_since=2021-02-07 13:36:36)
2021-02-07 14:38:23,556 - VolumePairList - INFO - Searching 75 pairs: ['BTC/USD', 'ETH/USD', 'DOGE/USD', 'LINK/USD', 'SUSHI/USD', 'LTC/USD', 'BCH/USD', 'SOL/USD', 'WBTC/USD', 'GRT/USD', 'UNI/USD', 'YFI/USD', 'TRX/USD', 'BAT/USD', 'CUSDT/USD', 'PAXG/USD', 'DAI/USD']
2021-02-07 14:38:31,684 - numexpr.utils - INFO - NumExpr defaulting to 4 threads.
2021-02-07 14:38:32,037 - freqtrade.freqtradebot - INFO - Cancelling current stoploss on exchange for pair BTC/USD (orderid:3726) in order to add another one ...
2021-02-07 14:38:32,157 - freqtrade.commands.trade_commands - ERROR - 'str' object has no attribute 'get'
2021-02-07 14:38:32,157 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/oz/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker.run()
  File "/home/oz/freqtrade/freqtrade/worker.py", line 74, in run
    state = self._worker(old_state=state)
  File "/home/oz/freqtrade/freqtrade/worker.py", line 111, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
  File "/home/oz/freqtrade/freqtrade/worker.py", line 132, in _throttle
    result = func(*args, **kwargs)
  File "/home/oz/freqtrade/freqtrade/worker.py", line 145, in _process_running
    self.freqtrade.process()
  File "/home/oz/freqtrade/freqtrade/freqtradebot.py", line 183, in process
    self.exit_positions(trades)
  File "/home/oz/freqtrade/freqtrade/freqtradebot.py", line 688, in exit_positions
    self.handle_stoploss_on_exchange(trade)):
  File "/home/oz/freqtrade/freqtrade/freqtradebot.py", line 897, in handle_stoploss_on_exchange
    self.handle_trailing_stoploss_on_exchange(trade, stoploss_order)
  File "/home/oz/freqtrade/freqtrade/freqtradebot.py", line 918, in handle_trailing_stoploss_on_exchange
    trade.update_order(co)
  File "/home/oz/freqtrade/freqtrade/persistence/models.py", line 477, in update_order
    Order.update_orders(self.orders, order)
  File "/home/oz/freqtrade/freqtrade/persistence/models.py", line 174, in update_orders
    filtered_orders = [o for o in orders if o.order_id == order.get('id')]
  File "/home/oz/freqtrade/freqtrade/persistence/models.py", line 174, in <listcomp>
    filtered_orders = [o for o in orders if o.order_id == order.get('id')]
AttributeError: 'str' object has no attribute 'get'
2021-02-07 14:38:32,158 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2021-02-07 14:38:32,158 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2021-02-07 14:38:32,500 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2021-02-07 14:38:32,506 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': warning, 'status': "1 open trades active.\n\nHandle these trades manually on FTX, or '/start' the bot again and use '/stopbuy' to handle open trades gracefully. \n"}
2021-02-07 14:38:32,805 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
2021-02-07 14:38:32,805 - apscheduler.scheduler - INFO - Scheduler has been shut down
2021-02-07 14:38:54,438 - freqtrade.loggers - INFO - Verbosity set to 0
2021-02-07 14:38:54,439 - freqtrade.configuration.configuration - INFO - Runmode set to live.
2021-02-07 14:38:54,439 - freqtrade.configuration.configuration - INFO - Parameter --db-url detected ...
2021-02-07 14:38:54,439 - freqtrade.configuration.configuration - INFO - Dry run is disabled
2021-02-07 14:38:54,439 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:///user_data/databases/ftxus_USD_1trade_smoothK_01StopLoss_02-07-21.LIVE.sqlite"
2021-02-07 14:38:54,439 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 1 ...
2021-02-07 14:38:54,439 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/oz/freqtrade/user_data ...
2021-02-07 14:38:54,440 - freqtrade.configuration.configuration - INFO - Using data directory: /home/oz/freqtrade/user_data/data/ftx ...
2021-02-07 14:38:54,440 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2021-02-07 14:38:54,440 - freqtrade.configuration.check_exchange - WARNING - Exchange "ftx" is known to the the ccxt library, available for the bot, but not officially supported by the Freqtrade development team. It may work flawlessly (please report back) or have serious issues. Use it at your own discretion.
2021-02-07 14:38:54,440 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2021-02-07 14:38:54,440 - freqtrade.freqtradebot - INFO - Starting freqtrade develop-f6cdc6d9
2021-02-07 14:38:54,454 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy smoothK_01StopLoss from '/home/oz/freqtrade/user_data/strategies/smoothK_01StopLoss.py'...
2021-02-07 14:38:54,454 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USD.
2021-02-07 14:38:54,454 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: unlimited.
2021-02-07 14:38:54,454 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'protections' with value in config file: [{'method': 'StoplossGuard', 'lookback_period_candles': 60, 'trade_limit': 5, 'stop_duration_candles': 240, 'only_per_pair': False}].
2021-02-07 14:38:54,454 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'buy': 10, 'sell': 30}.
2021-02-07 14:38:54,454 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'use_sell_signal' with value in config file: True.
2021-02-07 14:38:54,455 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'sell_profit_only' with value in config file: False.
2021-02-07 14:38:54,455 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ignore_roi_if_buy_signal' with value in config file: True.
2021-02-07 14:38:54,455 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 0.07535489057972716, '25': 0.05266114911935882, '45': 0.0123725116302516, '70': -1}
2021-02-07 14:38:54,455 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 1m
2021-02-07 14:38:54,455 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.01
2021-02-07 14:38:54,455 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: True
2021-02-07 14:38:54,455 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.2088505693949853
2021-02-07 14:38:54,455 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2021-02-07 14:38:54,455 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2021-02-07 14:38:54,455 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
2021-02-07 14:38:54,456 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'market', 'stoploss_on_exchange': True}
2021-02-07 14:38:54,456 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
2021-02-07 14:38:54,456 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USD
2021-02-07 14:38:54,456 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: unlimited
2021-02-07 14:38:54,456 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: [{'method': 'StoplossGuard', 'lookback_period_candles': 60, 'trade_limit': 5, 'stop_duration_candles': 240, 'only_per_pair': False}]
2021-02-07 14:38:54,456 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 0
2021-02-07 14:38:54,456 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'buy': 10, 'sell': 30}
2021-02-07 14:38:54,456 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_sell_signal: True
2021-02-07 14:38:54,456 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_only: False
2021-02-07 14:38:54,456 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_buy_signal: True
2021-02-07 14:38:54,457 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_offset: 0.0
2021-02-07 14:38:54,457 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2021-02-07 14:38:54,457 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2021-02-07 14:38:54,457 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2021-02-07 14:38:54,460 - freqtrade.exchange.exchange - INFO - Using CCXT 1.41.62
2021-02-07 14:38:54,460 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'hostname': 'ftx.us'}
2021-02-07 14:38:54,465 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'hostname': 'ftx.us', 'rateLimit': 500}
2021-02-07 14:38:54,469 - freqtrade.exchange.exchange - INFO - Using Exchange "FTX"
2021-02-07 14:38:54,987 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Ftx'...
2021-02-07 14:38:55,097 - freqtrade.wallets - INFO - Wallets synced.
2021-02-07 14:38:55,100 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist VolumePairList from '/home/oz/freqtrade/freqtrade/plugins/pairlist/VolumePairList.py'...
2021-02-07 14:38:55,103 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist PrecisionFilter from '/home/oz/freqtrade/freqtrade/plugins/pairlist/PrecisionFilter.py'...
2021-02-07 14:38:55,106 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist PriceFilter from '/home/oz/freqtrade/freqtrade/plugins/pairlist/PriceFilter.py'...
2021-02-07 14:38:55,109 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist RangeStabilityFilter from '/home/oz/freqtrade/freqtrade/plugins/pairlist/rangestabilityfilter.py'...
2021-02-07 14:38:55,112 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist PerformanceFilter from '/home/oz/freqtrade/freqtrade/plugins/pairlist/PerformanceFilter.py'...
2021-02-07 14:38:55,114 - freqtrade.resolvers.iresolver - INFO - Using resolved protection StoplossGuard from '/home/oz/freqtrade/freqtrade/plugins/protections/stoploss_guard.py'...
2021-02-07 14:38:55,133 - VolumePairList - INFO - Pair USDT/USD in your blacklist. Removing it from whitelist...
2021-02-07 14:38:55,133 - VolumePairList - INFO - Pair EUR/USD in your blacklist. Removing it from whitelist...
2021-02-07 14:38:55,133 - VolumePairList - INFO - Pair AUD/USD in your blacklist. Removing it from whitelist...
2021-02-07 14:38:55,133 - VolumePairList - INFO - Pair CAD/USD in your blacklist. Removing it from whitelist...
2021-02-07 14:38:55,134 - VolumePairList - INFO - Pair GBP/USD in your blacklist. Removing it from whitelist...
2021-02-07 14:38:55,134 - VolumePairList - INFO - Searching 75 pairs: ['BTC/USD', 'ETH/USD', 'DOGE/USD', 'LINK/USD', 'SUSHI/USD', 'LTC/USD', 'BCH/USD', 'SOL/USD', 'WBTC/USD', 'GRT/USD', 'UNI/USD', 'YFI/USD', 'TRX/USD', 'BAT/USD', 'CUSDT/USD', 'PAXG/USD', 'DAI/USD', 'BRL/USD', 'SGD/USD']
2021-02-07 14:38:55,134 - PriceFilter - INFO - Removed BRL/USD from whitelist, because ticker['last'] is empty (Usually no trade in the last 24h).
2021-02-07 14:38:55,134 - PriceFilter - INFO - Removed SGD/USD from whitelist, because ticker['last'] is empty (Usually no trade in the last 24h).
2021-02-07 14:39:03,901 - freqtrade.rpc.rpc_manager - INFO - Enabling rpc.telegram ...
2021-02-07 14:39:04,025 - apscheduler.scheduler - INFO - Scheduler started
2021-02-07 14:39:05,893 - freqtrade.rpc.telegram - INFO - rpc.telegram is listening for following commands: [['status'], ['profit'], ['balance'], ['start'], ['stop'], ['forcesell'], ['forcebuy'], ['trades'], ['delete'], ['performance'], ['stats'], ['daily'], ['count'], ['locks'], ['reload_config', 'reload_conf'], ['show_config', 'show_conf'], ['stopbuy'], ['whitelist'], ['blacklist'], ['logs'], ['edge'], ['help'], ['version']]
2021-02-07 14:39:05,894 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'running'}
2021-02-07 14:39:06,499 - freqtrade.worker - INFO - Changing state to: RUNNING
2021-02-07 14:39:06,499 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': "*Exchange:* `ftx`\n*Stake per trade:* `unlimited USD`\n*Minimum ROI:* `{'0': 0.07535489057972716, '25': 0.05266114911935882, '45': 0.0123725116302516, '70': -1}`\n*Trailing Stoploss:* `-0.01`\n*Timeframe:* `1m`\n*Strategy:* `smoothK_01StopLoss`"}
2021-02-07 14:39:06,797 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': "Searching for USD pairs to buy and sell based on [{'VolumePairList': 'VolumePairList - top 75 volume pairs.'}, {'PrecisionFilter': 'PrecisionFilter - Filtering untradable pairs.'}, {'PriceFilter': 'PriceFilter - Filtering pairs priced below 1.0%.'}, {'RangeStabilityFilter': 'RangeStabilityFilter - Filtering pairs with rate of change below 0.01 over the last days.'}, {'PerformanceFilter': 'PerformanceFilter - Sorting pairs by performance.'}]"}
2021-02-07 14:39:07,080 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': 'Using Protections: \nStoplossGuard - Frequent Stoploss Guard, 5 stoplosses within 60 candles.'}
2021-02-07 14:39:07,434 - freqtrade.persistence.models - INFO - Found open trade: Trade(id=1, pair=BTC/USD, amount=0.05110000, open_rate=38621.00000000, open_since=2021-02-07 13:36:36)
2021-02-07 14:39:07,437 - freqtrade.freqtradebot - INFO - Updating 1 open orders.
2021-02-07 14:39:07,568 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=1, pair=BTC/USD, amount=0.05110000, open_rate=38621.00000000, open_since=2021-02-07 13:36:36)
2021-02-07 14:39:07,860 - freqtrade.freqtradebot - INFO - Applying fee on amount for Trade(id=1, pair=BTC/USD, amount=0.05110000, open_rate=38621.00000000, open_since=2021-02-07 13:36:36) failed: myTrade-Dict empty found
2021-02-07 14:39:07,860 - freqtrade.persistence.models - INFO - Updating trade (id=1) ...
2021-02-07 14:39:07,861 - freqtrade.persistence.models - INFO - STOP is hit for Trade(id=1, pair=BTC/USD, amount=0.05110000, open_rate=38621.00000000, open_since=2021-02-07 13:36:36).
2021-02-07 14:39:07,861 - freqtrade.commands.trade_commands - ERROR - conversion from NoneType to Decimal is not supported
2021-02-07 14:39:07,861 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/oz/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker.run()
  File "/home/oz/freqtrade/freqtrade/worker.py", line 74, in run
    state = self._worker(old_state=state)
  File "/home/oz/freqtrade/freqtrade/worker.py", line 92, in _worker
    self.freqtrade.startup()
  File "/home/oz/freqtrade/freqtrade/freqtradebot.py", line 147, in startup
    self.update_open_orders()
  File "/home/oz/freqtrade/freqtrade/freqtradebot.py", line 260, in update_open_orders
    self.update_trade_state(order.trade, order.order_id, fo)
  File "/home/oz/freqtrade/freqtrade/freqtradebot.py", line 1329, in update_trade_state
    trade.update(order)
  File "/home/oz/freqtrade/freqtrade/persistence/models.py", line 424, in update
    self.close(order['average'])
  File "/home/oz/freqtrade/freqtrade/persistence/models.py", line 434, in close
    self.close_rate = Decimal(rate)
TypeError: conversion from NoneType to Decimal is not supported
2021-02-07 14:39:07,862 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2021-02-07 14:39:07,862 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}

  ```

**Comment by ozitrance** [comment]
Seems like it's something similar to this: [](https://github.com/freqtrade/freqtrade/pull/3086

FTX returns a string, something like "Order cancelled", after cancelling the stoploss order and I guess freqtrade is expecting a dictionary...?

**Comment by mobrine1** [comment]
#3086 seems to be the issue. Ftx return unexpected output when freqtrade cancels order.
You should wait until #3086 is pushed then retry

**Comment by xmatthias** [comment]
the latest develop (just pushed) will fix this for future canceled orders

I do suspect that you will have to remove this order from the database manually to get to a "clean" state again.

Sorry for the inconvenience

**Comment by ozitrance** [comment]
I just tried now with a new database and it seems to be working fine and as expected, updating the stoploss orders without crashing or anything

Thank you very much!
