### ISSUE TITLE
Can't install via script or docker :( (TA-Lib 0.4.19 can't be found) 

### ISSUE THREAD

**Issue by rusagent** [freqtrade/freqtrade#4332]
## Describe your environment

  `Raspberry Pi OS 64 bit ( Linux raspberrypi 5.10.11-v8+ #1399 SMP PREEMPT Thu Jan 28 12:14:03 GMT 2021 aarch64 GNU/Linux )`
  * Python Version:  Python 2.7.16
  * Python3 Version: Python 3.7.3
  * CCXT version: nothing
  * Freqtrade Version: also nothing
  
## Describe the problem:

The installation breaks when trying to install TALib.

### Steps to reproduce:

Install TALib with the the supllied information in the Tutorial. But i had to update config.guess and config.sub files so TA Lib could actually be installed. Then i got the sources from TA-Lib main github repo (https://github.com/mrjbq7/ta-lib)  and installed it with python3 setup.py install.

Then i followed the Installation Steps to install freqtrade.
  
### Observed Results:

TA-Lib 0.4.19 was installed but the freqtrage install script said it wasn't.

### Relevant code exceptions or logs

  ```
Collecting TA-Lib==0.4.19
  Using cached TA-Lib-0.4.19.tar.gz (267 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/pi/freqtrade/.env/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ryz88qcw/ta-lib_2c2063524be24fa191d050d1a8c391c5/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ryz88qcw/ta-lib_2c2063524be24fa191d050d1a8c391c5/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-m30a9fo4
         cwd: /tmp/pip-install-ryz88qcw/ta-lib_2c2063524be24fa191d050d1a8c391c5/
    Complete output (95 lines):
    Processing numpy/random/_bounded_integers.pxd.in
    Processing numpy/random/_generator.pyx
    Traceback (most recent call last):
      File "/tmp/easy_install-piq7epbq/numpy-1.20.0/tools/cythonize.py", line 59, in process_pyx
        from Cython.Compiler.Version import version as cython_version
    ModuleNotFoundError: No module named 'Cython'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/easy_install-piq7epbq/numpy-1.20.0/tools/cythonize.py", line 235, in <module>
        main()
      File "/tmp/easy_install-piq7epbq/numpy-1.20.0/tools/cythonize.py", line 231, in main
        find_process_files(root_dir)
      File "/tmp/easy_install-piq7epbq/numpy-1.20.0/tools/cythonize.py", line 222, in find_process_files
        process(root_dir, fromfile, tofile, function, hash_db)
      File "/tmp/easy_install-piq7epbq/numpy-1.20.0/tools/cythonize.py", line 188, in process
        processor_function(fromfile, tofile)
      File "/tmp/easy_install-piq7epbq/numpy-1.20.0/tools/cythonize.py", line 64, in process_pyx
        raise OSError('Cython needs to be installed in Python as a module')
    OSError: Cython needs to be installed in Python as a module
    Cythonizing sources
    Running from numpy source directory.
    /tmp/easy_install-piq7epbq/numpy-1.20.0/setup.py:485: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      run_build = parse_setuppy_commands()
    Traceback (most recent call last):
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-piq7epbq/numpy-1.20.0/setup.py", line 513, in <module>
      File "/tmp/easy_install-piq7epbq/numpy-1.20.0/setup.py", line 493, in setup_package
      File "/tmp/easy_install-piq7epbq/numpy-1.20.0/setup.py", line 290, in generate_cython
    RuntimeError: Running cythonize failed!
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ryz88qcw/ta-lib_2c2063524be24fa191d050d1a8c391c5/setup.py", line 170, in <module>
        **requires)
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/dist.py", line 724, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
        replace_conflicting=replace_conflicting
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/dist.py", line 791, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 704, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 730, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 915, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 1183, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 1169, in run_setup
        run_setup(setup_script, args)
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/_vendor/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/home/pi/freqtrade/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-piq7epbq/numpy-1.20.0/setup.py", line 513, in <module>
      File "/tmp/easy_install-piq7epbq/numpy-1.20.0/setup.py", line 493, in setup_package
      File "/tmp/easy_install-piq7epbq/numpy-1.20.0/setup.py", line 290, in generate_cython
    RuntimeError: Running cythonize failed!
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/ac/cf/681911aa31e04ba171ab4d523a412f4a746e30d3eacb1738799d181e028b/TA-Lib-0.4.19.tar.gz#sha256=5303227898f8f08baecb4d3b8767c85891b65b21f481a3ecbaa6e901c3531db5 (from https://pypi.org/simple/ta-lib/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement TA-Lib==0.4.19
ERROR: No matching distribution found for TA-Lib==0.4.19

  ```

Also when i try to install it via docker i get this error: 

`
docker-compose run --rm freqtrade create-userdir --userdir user_data
Creating ft_userdata_freqtrade_run ... done
standard_init_linux.go:219: exec user process caused: exec format error
ERROR: 1
`

**Comment by xmatthias** [comment]
You are on a raspberry it seems.

for docker, simply use the [docker quickstart](https://www.freqtrade.io/en/latest//docker_quickstart/#docker-quick-start) and make sure to switch to the Raspberry install (this requires an additional step).


For ta-lib - you can use the `./setup.sh` - which will install cython as well if you're on a raspberry (assuming it's a 32bit version - 64bit versions have a lot of compatibility problems so far, so we're not supporting these at the moment.

**Comment by xmatthias** [comment]
I'll assume this as answered by the above.

Feel free to comment below / reopen if that's not the case.
