### ISSUE TITLE
`user_data` is not abstracted from core 

### ISSUE THREAD

**Issue by robmoggach** [freqtrade/freqtrade#435]
Feature Request! I'd love to see `freqtrade` working as a module with the `freqtrade` script working as expected and supplementary scripts moved to their own repository (plot scripts, service scripts). Currently installing with `python setup.py install` doesn't yield a working installation... but it's close. The `user_data` folder could be it's own repo or an extra data folder that is installed to a user's home folder... looking something like:

```
$HOME/
    .freqtrade/
        config.json
        data/
            BTC_FUN-1.json
            BTC_FUN-5.json
            BTC_FUN-10.json
        data_custom/
            BTC_DOGE-1.json
        strategies/
            myGreatStrategy.py
            bear_test.py
```

The `freqtrade` shell script works perfectly and would be installed in system default location or virtualenv bin directory - nice and clean.

This would allow users to create a git repo of their `user_data` folder separate from any module functionality and perform upgrades easily. The `user_data` directory could probably live in a separate repo as well and evolve as better default strategies present themselves.

> On the supplementary repository note above maybe `freqtrade` could have it's own org so we'd see http://github.com/freqtrade/freqtrade and http://github.com/freqtrade/freqtrade-scripts???

**Comment by glonlas** [comment]
Interesting enhancement. I just struggle to see how the bot will be informed of the strategy file to use and how to implement this mechanism.

**Comment by robmoggach** [comment]
For another project I have a tool that dynamically loads python modules to
a namespace on load.
We could "easily" add it so on load it looks for a path and then adds all
python files in that path to a namespace like `freqtrade.user_data.strategy`
I'll track it down. Also as far as configs would be good to standardize a
path like `~/.freqtrade` for all user data.

--
Robert Moggach
http://moggach.com
Mobile (647) 544-1793

**Comment by gcarq** [comment]
+1 for this proposal.

Right now the bot complains that he cannot find `user_data` if freqtrade is installed system wide:
```
$ freqtrade --help
Traceback (most recent call last):
  File "/usr/bin/freqtrade", line 4, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/freqtrade/main.py", line 494, in main
    'Simple High Frequency Trading Bot for crypto currencies')
  File "/usr/lib/python3.6/site-packages/freqtrade/misc.py", line 197, in parse_args
    build_subcommands(parser)
  File "/usr/lib/python3.6/site-packages/freqtrade/misc.py", line 315, in build_subcommands
    from freqtrade.optimize import backtesting, hyperopt
  File "/usr/lib/python3.6/site-packages/freqtrade/optimize/__init__.py", line 12, in <module>
    from user_data.hyperopt_conf import hyperopt_optimize_conf
ModuleNotFoundError: No module named 'user_data'
```

I don't think it needs to be in its own repository for the first iteration, but it would be beneficial in the long term.

A quick way to fix this would be to check on app start if there already exists an `user_data` folder somewhere within `~/.freqtrade`, and if so load those strategies.

**Comment by andrewcz** [comment]
same issue 

(pyds) [andrewcz@andrewcz-pc freqtrade]$ freqtrade --help
Traceback (most recent call last):
  File "/home/andrewcz/pyenvs/pyds/bin/freqtrade", line 4, in <module>
    __import__('pkg_resources').run_script('freqtrade==0.17.0', 'freqtrade')
  File "/home/andrewcz/pyenvs/pyds/lib/python3.6/site-packages/pkg_resources/__init__.py", line 654, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/andrewcz/pyenvs/pyds/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1434, in run_script
    exec(code, namespace, namespace)
  File "/home/andrewcz/pyenvs/pyds/lib/python3.6/site-packages/freqtrade-0.17.0-py3.6.egg/EGG-INFO/scripts/freqtrade", line 7, in <module>
    main(sys.argv[1:])
  File "/home/andrewcz/pyenvs/pyds/lib/python3.6/site-packages/freqtrade-0.17.0-py3.6.egg/freqtrade/main.py", line 27, in main
    args = arguments.get_parsed_arg()
  File "/home/andrewcz/pyenvs/pyds/lib/python3.6/site-packages/freqtrade-0.17.0-py3.6.egg/freqtrade/arguments.py", line 47, in get_parsed_arg
    self._load_args()
  File "/home/andrewcz/pyenvs/pyds/lib/python3.6/site-packages/freqtrade-0.17.0-py3.6.egg/freqtrade/arguments.py", line 39, in _load_args
    self._build_subcommands()
  File "/home/andrewcz/pyenvs/pyds/lib/python3.6/site-packages/freqtrade-0.17.0-py3.6.egg/freqtrade/arguments.py", line 227, in _build_subcommands
    from freqtrade.optimize import backtesting, hyperopt
  File "/home/andrewcz/pyenvs/pyds/lib/python3.6/site-packages/freqtrade-0.17.0-py3.6.egg/freqtrade/optimize/__init__.py", line 14, in <module>
    from user_data.hyperopt_conf import hyperopt_optimize_conf
ModuleNotFoundError: No module named 'user_data'
(pyds) [andrewcz@andrewcz-pc freqtrade]$

**Comment by gcarq** [comment]
@andrewcz Seems like your running an old version, there is no longer a file namend `freqtrade/optimize/init.py`. Can you re-test with lastest develop?

**Comment by gcarq** [comment]
Fixed in develop. `$ python setup.py install` should yield a working installation
