### ISSUE TITLE
Freqtrade doesn't sell on sell signal.

### ISSUE THREAD

**Issue by jasin755** [freqtrade/freqtrade#4381]
I have started use freqtrade inside Docker on my Synology NAS (Intel based) together with frequi for monitoring. All work great. I see sell signals in frequi but order haven't been created on Kraken.

![image](https://user-images.githubusercontent.com/10629189/107975416-5c694300-6fb8-11eb-9abf-f0b494674886.png)

My config.json:
```
{
    "max_open_trades": 3,
    "stake_currency": "EUR",
    "stake_amount": "unlimited",
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "EUR",
    "dry_run": false,
    "cancel_open_orders_on_exit": false,
    "unfilledtimeout": {
        "buy": 10,
        "sell": 30
    },
    "bid_strategy": {
        "price_side": "bid",
        "ask_last_balance": 0.0,
        "use_order_book": false,
        "order_book_top": 1,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "ask_strategy": {
        "price_side": "ask",
        "use_order_book": false,
        "order_book_min": 1,
        "order_book_max": 1,
        "use_sell_signal": true,
        "sell_profit_only": true,
        "ignore_roi_if_buy_signal": false
    },
    "download_trades": true,
    "exchange": {
        "name": "kraken",
        "key": "xxxxx",
        "secret": "xxxx",
        "ccxt_config": {"enableRateLimit": true},
        "ccxt_async_config": {
            "enableRateLimit": true,
            "rateLimit": 1000
        },
        "pair_whitelist": [
            "BTC/EUR",
        ],
        "pair_blacklist": [

        ]
    },
    "pairlists": [
        {"method": "StaticPairList"}
    ],
    "edge": {
        "enabled": false,
        "process_throttle_secs": 3600,
        "calculate_since_number_of_days": 7,
        "allowed_risk": 0.01,
        "stoploss_range_min": -0.01,
        "stoploss_range_max": -0.1,
        "stoploss_range_step": -0.01,
        "minimum_winrate": 0.60,
        "minimum_expectancy": 0.20,
        "min_trade_number": 10,
        "max_trade_duration_minute": 1440,
        "remove_pumps": false
    },
    "telegram": {
        "enabled": true,
        "token": "xxxxx",
        "chat_id": "xxxxx"
    },
    "api_server": {
        "enabled": true,
        "listen_ip_address": "127.0.0.1",
        "listen_port": 8088,
        "verbosity": "info",
        "jwt_secret_key": "xxxxxx",
        "CORS_origins": [],
        "username": "xxxxxx",
        "password": "xxxxxxx"
    },
    "bot_name": "freqtrade",
    "initial_state": "running",
    "forcebuy_enable": false,
    "internals": {
        "process_throttle_secs": 5
    }
}
```

Strategy is default Strategy005 from freqtrade-strategies repo.

**Comment by jasin755** [comment]
I probably found clue:
```
2021-02-15 19:15:48,600 - freqtrade.freqtradebot - DEBUG - Found no buy signals for whitelisted currencies. Trying again...
```

**Comment by xmatthias** [comment]
without logs, there's nothing we can do for you.

It's just a signal after all - so maybe you've not been in a trade, or the trade has been negative (you got `sell_profit_only=True`).

**Comment by jasin755** [comment]
I have tried set it on `false`. It din't help. Piece of log:
```

date | stream | content
-- | -- | --
2021-02-15 18:21:03 | stdout | 2021-02-15 19:21:03,880 - freqtrade.worker - DEBUG - Throttling with '_process_running()': sleep for 4.96 s, last iteration took 0.04 s.
2021-02-15 18:21:03 | stdout | 2021-02-15 19:21:03,880 - freqtrade.freqtradebot - DEBUG - Found no buy signals for whitelisted currencies. Trying again...
2021-02-15 18:21:03 | stdout | 2021-02-15 19:21:03,879 - freqtrade.strategy.interface - DEBUG - trigger: 2021-02-15 18:15:00+00:00 (pair=BTC/EUR) buy=False sell=True
2021-02-15 18:21:03 | stdout | 2021-02-15 19:21:03,872 - freqtrade.freqtradebot - DEBUG - create_trade for pair BTC/EUR
2021-02-15 18:21:03 | stdout | 2021-02-15 19:21:03,866 - freqtrade.strategy.interface - DEBUG - Loop Analysis Launched
2021-02-15 18:21:03 | stdout | 2021-02-15 19:21:03,862 - freqtrade.strategy.interface - DEBUG - Populating sell signals for pair BTC/EUR.
2021-02-15 18:21:03 | stdout | 2021-02-15 19:21:03,857 - freqtrade.strategy.interface - DEBUG - Populating buy signals for pair BTC/EUR.
2021-02-15 18:21:03 | stdout | 2021-02-15 19:21:03,849 - freqtrade.strategy.interface - DEBUG - Populating indicators for pair BTC/EUR.
2021-02-15 18:21:03 | stdout | 2021-02-15 19:21:03,849 - freqtrade.strategy.interface - DEBUG - TA Analysis Launched
2021-02-15 18:21:03 | stdout | 2021-02-15 19:21:03,848 - freqtrade.exchange.exchange - DEBUG - Using cached candle (OHLCV) data for pair BTC/EUR, timeframe 5m ...
2021-02-15 18:21:03 | stdout | 2021-02-15 19:21:03,848 - freqtrade.exchange.exchange - DEBUG - Refreshing candle (OHLCV) data for 1 pairs
2021-02-15 18:21:03 | stdout | 2021-02-15 19:21:03,841 - freqtrade.worker - DEBUG - ========================================
2021-02-15 18:20:58 | stdout | 2021-02-15 19:20:58,882 - freqtrade.worker - DEBUG - Throttling with '_process_running()': sleep for 4.95 s, last iteration took 0.05 s.
2021-02-15 18:20:58 | stdout | 2021-02-15 19:20:58,881 - freqtrade.freqtradebot - DEBUG - Found no buy signals for whitelisted currencies. Trying again...
2021-02-15 18:20:58 | stdout | 2021-02-15 19:20:58,881 - freqtrade.strategy.interface - DEBUG - trigger: 2021-02-15 18:15:00+00:00 (pair=BTC/EUR) buy=False sell=True
2021-02-15 18:20:58 | stdout | 2021-02-15 19:20:58,875 - freqtrade.freqtradebot - DEBUG - create_trade for pair BTC/EUR
2021-02-15 18:20:58 | stdout | 2021-02-15 19:20:58,865 - freqtrade.strategy.interface - DEBUG - Loop Analysis Launched
2021-02-15 18:20:58 | stdout | 2021-02-15 19:20:58,859 - freqtrade.strategy.interface - DEBUG - Populating sell signals for pair BTC/EUR.
2021-02-15 18:20:58 | stdout | 2021-02-15 19:20:58,854 - freqtrade.strategy.interface - DEBUG - Populating buy signals for pair BTC/EUR.
2021-02-15 18:20:58 | stdout | 2021-02-15 19:20:58,844 - freqtrade.strategy.interface - DEBUG - Populating indicators for pair BTC/EUR.
2021-02-15 18:20:58 | stdout | 2021-02-15 19:20:58,844 - freqtrade.strategy.interface - DEBUG - TA Analysis Launched
2021-02-15 18:20:58 | stdout | 2021-02-15 19:20:58,843 - freqtrade.exchange.exchange - DEBUG - Using cached candle (OHLCV) data for pair BTC/EUR, timeframe 5m ...
2021-02-15 18:20:58 | stdout | 2021-02-15 19:20:58,843 - freqtrade.exchange.exchange - DEBUG - Refreshing candle (OHLCV) data for 1 pairs
2021-02-15 18:20:58 | stdout | 2021-02-15 19:20:58,835 - freqtrade.worker - DEBUG - ========================================

```

**Comment by xmatthias** [comment]
so far, the logs indicate that the bot found a sell signal.
Sell signals are signals only - they are ONLY acted upon when you are in a trade. otherwise, they don't matter.

As i don't see any hint that you are currently in a trade for this pair - i don't see what should happen.

**Comment by jasin755** [comment]
I have started bot at first time. Is it possible use historical data of purchases from Kraken or is it possible create "fake" buy using current market price etc? Because now it will wait for buy signal, won't it?

**Comment by xmatthias** [comment]
I can only recommend to go through the [documentation](https://www.freqtrade.io/en/latest/) to discover the possibilities (like backtesting, hyperopt, ...).

Trading (both dry-run and live) will come at a later point - when you know what to expect from a strategy.

**Comment by jasin755** [comment]
I have already read it of course. But I haven't found how I can start trading with sell command instead buy.

**Comment by xmatthias** [comment]
Freqtrade does currently work in spot markets, which by definition allow long trades only.
A trade entry will therefore always be a buy - and the exit a sell.

While this may be subject to change in the future, there are no immediate plans for this in the near term.

**Comment by jasin755** [comment]
Ok. And what abouce /forcebuy command? Will it work?

**Comment by xmatthias** [comment]
Yes, /forcebuy will buy the pair, so you have a position - and then the bot will exit the pair based on your strategy.

It must be explicitly enabled in the config - but then it'll work just fine.

**Comment by jasin755** [comment]
Great! Thanks.

**Comment by AmirMassou94** [comment]
Hi dear @xmatthias 
I saw this post and want to add that I have the same problem couple of day!
after updating my strategy which the difference from previous one is it just trade on 1 pair despite of the change in buy and sell logics...
the odd thing is that sell signal is not working!!!
but I noticed that forcesell and stop loss(trailing ...) worked !
also i didn't find anything in log at the sell signal time! 
the only error I found in log is this:
`2022-04-18 09:03:04 - uvicorn.error - WARNING - Invalid HTTP request received.
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 136, in handle_events
    event = self.conn.next_event()
  File "/home/ftuser/.local/lib/python3.9/site-packages/h11/_connection.py", line 485, in next_event
    exc._reraise_as_remote_protocol_error()
  File "/home/ftuser/.local/lib/python3.9/site-packages/h11/_util.py", line 77, in _reraise_as_remote_protocol_error
    raise self
  File "/home/ftuser/.local/lib/python3.9/site-packages/h11/_connection.py", line 467, in next_event
    event = self._extract_next_receive_event()
  File "/home/ftuser/.local/lib/python3.9/site-packages/h11/_connection.py", line 409, in _extract_next_receive_event
    event = self._reader(self._receive_buffer)
  File "/home/ftuser/.local/lib/python3.9/site-packages/h11/_readers.py", line 81, in maybe_read_from_IDLE_client
    raise LocalProtocolError("illegal request line")
h11._util.RemoteProtocolError: illegal request line` 
do you have any idea where I can find the problem?

![not selling](https://user-images.githubusercontent.com/64456212/163814338-d09c507f-66b6-415f-948f-b4a2993ad59a.png)

**Comment by xmatthias** [comment]
@AmirMassou94 most likely - forcesell is disabled.
I'd however ask you to not revive issues that are over a year old. It'll ping everyone in this issue, which is clearly not desired.
