### ISSUE TITLE
Error when downloading data from qtrade

### ISSUE THREAD

**Issue by LeMoussel** [freqtrade/freqtrade#4387]
## Environment

  * Operating system: Windows 10
  * Python Version: 3.7.8
  * CCXT version: 1.30.59
  * Freqtrade Version: 2021.1
  
## Problem:
Pandas error: `AttributeError: type object 'object' has no attribute 'dtype'`

When I use CCXT, over the month of February, I get these results
```
Time,Open,High,Low,Close,Volume
2021-02-01 01:00:00,0.04,0.0415,0.0383,0.0415,8.37893235982262
2021-02-02 01:00:00,0.04040001,0.04417181,0.04010035,0.04417181,3.037717234666702
2021-02-03 01:00:00,0.04160001,0.04382215,0.04150066,0.04250003,1.9142175864258344
2021-02-04 01:00:00,0.04309758,0.045,0.04237802,0.0434,4.534838185050246
2021-02-05 01:00:00,0.04489997,0.04686622,0.04242619,0.04686622,1.544760655269915
2021-02-06 01:00:00,0.04485,0.04485,0.04374105,0.04374105,13.826101921235837
2021-02-07 01:00:00,0.04160003,0.04299895,0.0401,0.0418,12.29700973825185
2021-02-08 01:00:00,0.041798,0.0418,0.03770079,0.0405736,6.10002985
2021-02-09 01:00:00,0.03847235,0.03939254,0.03680002,0.03847225,6.61493067
2021-02-10 01:00:00,0.03720001,0.03964945,0.03710383,0.03722372,1.6016116221983279
2021-02-11 01:00:00,0.03953029,0.03953029,0.03680002,0.03846382,6.7254913022867
2021-02-12 01:00:00,0.03813625,0.04017787,0.03680002,0.04017787,6.935404009095126
2021-02-13 01:00:00,0.03997631,0.03997631,0.03729744,0.0379,8.845250043565226
2021-02-14 01:00:00,0.0379,0.03881391,0.03680002,0.03819216,4.339048455609035
2021-02-15 01:00:00,0.03816285,0.03858429,0.03680002,0.03817169,4.74744544
2021-02-16 01:00:00,0.03680003,0.0384516,0.03509518,0.03509518,7.180644041970812
```

### Steps to reproduce:
run `download-data --exchange qTrade -t 1d -p ETH/BTC`
  
### Relevant code exceptions or logs
  ```
2021-02-17 09:59:58,035 - freqtrade.configuration.configuration - INFO - Using config: config_qtrade.json ...
2021-02-17 09:59:58,036 - freqtrade.loggers - INFO - Verbosity set to 0
2021-02-17 09:59:58,036 - freqtrade.configuration.configuration - INFO - Using exchange qtrade
2021-02-17 09:59:58,037 - freqtrade.configuration.configuration - INFO - Using user-data directory: D:\Developpement\Python\Trading\user_data ...
2021-02-17 09:59:58,037 - freqtrade.configuration.configuration - INFO - Using data directory: D:\Developpement\Python\Trading\user_data\data\qtrade ...
2021-02-17 09:59:58,037 - freqtrade.configuration.configuration - INFO - Using pairs ['ETH/BTC']
2021-02-17 09:59:58,037 - freqtrade.configuration.configuration - INFO - timeframes --timeframes: ['1d']
2021-02-17 09:59:58,037 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2021-02-17 09:59:58,038 - freqtrade.configuration.check_exchange - WARNING - Exchange "qtrade" is known to the the ccxt library, available for the bot, but not officially supported by the Freqtrade development team. It may work flawlessly (please report back) or have serious issues. Use it at your own discretion.
2021-02-17 09:59:58,038 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2021-02-17 09:59:58,040 - freqtrade.resolvers.exchange_resolver - INFO - No Qtrade specific subclass found. Using the generic class instead.
2021-02-17 09:59:58,040 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2021-02-17 09:59:58,041 - freqtrade.exchange.exchange - INFO - Using CCXT 1.30.59
2021-02-17 09:59:58,041 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2021-02-17 09:59:58,043 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2021-02-17 09:59:58,047 - freqtrade.exchange.exchange - INFO - Using Exchange "qTrade"
2021-02-17 09:59:58,047 - freqtrade.exchange.exchange - INFO - Markets were not loaded. Loading them now..
2021-02-17 09:59:59,561 - freqtrade.commands.data_commands - INFO - About to download pairs: ['ETH/BTC'], intervals: ['1d'] to D:\Developpement\Python\Trading\user_data\data\qtrade
2021-02-17 09:59:59,562 - freqtrade.data.history.history_utils - INFO - Downloading pair ETH/BTC, interval 1d.
2021-02-17 09:59:59,562 - freqtrade.data.history.history_utils - INFO - Download history data for pair: "ETH/BTC", timeframe: 1d and store in D:\Developpement\Python\Trading\user_data\data\qtrade.
2021-02-17 09:59:59,565 - freqtrade.data.history.history_utils - ERROR - Failed to download history data for pair: "ETH/BTC", timeframe: 1d.
Traceback (most recent call last):
  File "c:\users\pc\appdata\local\programs\python\python37\lib\site-packages\freqtrade\data\history\history_utils.py", line 184, in _download_pair_history
    data_handler=data_handler)
  File "c:\users\pc\appdata\local\programs\python\python37\lib\site-packages\freqtrade\data\history\history_utils.py", line 143, in _load_cached_data_for_updating
    drop_incomplete=True, warn_no_data=False)
  File "c:\users\pc\appdata\local\programs\python\python37\lib\site-packages\freqtrade\data\history\idatahandler.py", line 169, in ohlcv_load
    timerange=timerange_startup)
  File "c:\users\pc\appdata\local\programs\python\python37\lib\site-packages\freqtrade\data\history\jsondatahandler.py", line 88, in _ohlcv_load
    return DataFrame(columns=self._columns)
  File "c:\users\pc\appdata\local\programs\python\python37\lib\site-packages\pandas\core\frame.py", line 435, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "c:\users\pc\appdata\local\programs\python\python37\lib\site-packages\pandas\core\internals\construction.py", line 239, in init_dict
    val = construct_1d_arraylike_from_scalar(np.nan, len(index), nan_dtype)
  File "c:\users\pc\appdata\local\programs\python\python37\lib\site-packages\pandas\core\dtypes\cast.py", line 1440, in construct_1d_arraylike_from_scalar
    dtype = dtype.dtype
AttributeError: type object 'object' has no attribute 'dtype'
  ```

**Comment by xmatthias** [comment]
As we state in the docs - we did test a few exchanges, for all others, we cannot guarantee they work. You're most likely the first to try this exchange.

The data you list above does not seem to be in the correct format. 

Did you use some transformation after running the `fetch_ohlcv()` endpoint for this exchange, or does ccxt provide the data exactly like this? (if yes, then ccxt does not properly convert it to the format).

**Comment by LeMoussel** [comment]
Yes, I do Pandas transformation. 

Below result for pair  'ETH/BTC' of the day "2021-02-01" with no transformation.

```
    import ccxt

    ex = getattr(ccxt, 'qtrade')({
        'verbose': False,
        'enableRateLimit': True,
        'options': {'fetchOHLCVWarning': False}
    })
    start_date = datetime.strptime("2021-02-01", "%Y-%m-%d") + timedelta(days=0)
    since = calendar.timegm(start_date.utctimetuple()) * 1000
    ohlcv_data = ex.fetch_ohlcv(symbol='ETH/BTC', timeframe='1d', since=since, limit=365)
    print(ohlcv_data)
```

`[[1612137600000, 0.04, 0.0415, 0.0383, 0.0415, 8.37893235982262], [1612224000000, 0.04040001, 0.04417181, 0.04010035, 0.04417181, 3.037717234666702], [1612310400000, 0.04160001, 0.04382215, 0.04150066, 0.04250003, 1.9142175864258344], [1612396800000, 0.04309758, 0.045, 0.04237802, 0.0434, 4.534838185050246], [1612483200000, 0.04489997, 0.04686622, 0.04242619, 0.04686622, 1.544760655269915], [1612569600000, 0.04485, 0.04485, 0.04374105, 0.04374105, 13.826101921235837], [1612656000000, 0.04160003, 0.04299895, 0.0401, 0.0418, 12.29700973825185], [1612742400000, 0.041798, 0.0418, 0.03770079, 0.0405736, 6.10002985], [1612828800000, 0.03847235, 0.03939254, 0.03680002, 0.03847225, 6.61493067], [1612915200000, 0.03720001, 0.03964945, 0.03710383, 0.03722372, 1.6016116221983279], [1613001600000, 0.03953029, 0.03953029, 0.03680002, 0.03846382, 6.7254913022867], [1613088000000, 0.03813625, 0.04017787, 0.03680002, 0.04017787, 6.935404009095126], [1613174400000, 0.03997631, 0.03997631, 0.03729744, 0.0379, 8.845250043565226], [1613260800000, 0.0379, 0.03881391, 0.03680002, 0.03819216, 4.339048455609035], [1613347200000, 0.03816285, 0.03858429, 0.03680002, 0.03817169, 4.74744544], [1613433600000, 0.03680003, 0.0384516, 0.03509518, 0.03509518, 7.180644041970812], [1613520000000, 0.0353, 0.03629999, 0.0353, 0.03600001, 4.71731528]]`

**Comment by xmatthias** [comment]
best make sure you use an uptodate ccxt version. 
The version you outline above seems pretty old (for ccxt standards) - I've tried this with 1.41.70, but usually the best is the latest (update with `pip install -U ccxt`).


i've just tried your command with the latest develop and it does seem to work just fine (after lowercasing the exchange name)...

`freqtrade download-data --exchange qtrade -t 1d -p ETH/BTC`

**Comment by LeMoussel** [comment]
Update to ccxt-1.41.97
Got same errors :
```
D:\Developpement\Python\Trading>freqtrade download-data --exchange qtrade -t 1d -p ETH/BTC
2021-02-17 16:28:42,113 - freqtrade.loggers - INFO - Verbosity set to 0
2021-02-17 16:28:42,114 - freqtrade.configuration.configuration - INFO - Using exchange qtrade
2021-02-17 16:28:42,117 - freqtrade.configuration.configuration - INFO - Using user-data directory: D:\Developpement\Python\Trading\user_data ...
2021-02-17 16:28:42,120 - freqtrade.configuration.configuration - INFO - Using data directory: D:\Developpement\Python\Trading\user_data\data\qtrade ...
2021-02-17 16:28:42,120 - freqtrade.configuration.configuration - INFO - Using pairs ['ETH/BTC']
2021-02-17 16:28:42,120 - freqtrade.configuration.configuration - INFO - timeframes --timeframes: ['1d']
2021-02-17 16:28:42,121 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2021-02-17 16:28:42,121 - freqtrade.configuration.check_exchange - WARNING - Exchange "qtrade" is known to the the ccxt library, available for the bot, but not officially supported by the Freqtrade development team. It may work flawlessly (please report back) or have serious issues. Use it at your own discretion.
2021-02-17 16:28:42,122 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2021-02-17 16:28:42,124 - freqtrade.resolvers.exchange_resolver - INFO - No Qtrade specific subclass found. Using the generic class instead.
2021-02-17 16:28:42,127 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2021-02-17 16:28:42,127 - freqtrade.exchange.exchange - INFO - Using CCXT 1.41.97
2021-02-17 16:28:42,138 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2021-02-17 16:28:42,142 - freqtrade.exchange.exchange - INFO - Using Exchange "qTrade"
2021-02-17 16:28:42,142 - freqtrade.exchange.exchange - INFO - Markets were not loaded. Loading them now..
2021-02-17 16:28:43,302 - freqtrade.commands.data_commands - INFO - About to download pairs: ['ETH/BTC'], intervals: ['1d'] to D:\Developpement\Python\Trading\user_data\data\qtrade
2021-02-17 16:28:43,304 - freqtrade.data.history.history_utils - INFO - Downloading pair ETH/BTC, interval 1d.
2021-02-17 16:28:43,305 - freqtrade.data.history.history_utils - INFO - Download history data for pair: "ETH/BTC", timeframe: 1d and store in D:\Developpement\Python\Trading\user_data\data\qtrade.
2021-02-17 16:28:43,311 - freqtrade.data.history.history_utils - ERROR - Failed to download history data for pair: "ETH/BTC", timeframe: 1d.
Traceback (most recent call last):
  File "c:\users\pc\appdata\local\programs\python\python37\lib\site-packages\freqtrade\data\history\history_utils.py", line 184, in _download_pair_history
    data_handler=data_handler)
  File "c:\users\pc\appdata\local\programs\python\python37\lib\site-packages\freqtrade\data\history\history_utils.py", line 143, in _load_cached_data_for_updating
    drop_incomplete=True, warn_no_data=False)
  File "c:\users\pc\appdata\local\programs\python\python37\lib\site-packages\freqtrade\data\history\idatahandler.py", line 169, in ohlcv_load
    timerange=timerange_startup)
  File "c:\users\pc\appdata\local\programs\python\python37\lib\site-packages\freqtrade\data\history\jsondatahandler.py", line 88, in _ohlcv_load
    return DataFrame(columns=self._columns)
  File "c:\users\pc\appdata\local\programs\python\python37\lib\site-packages\pandas\core\frame.py", line 435, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "c:\users\pc\appdata\local\programs\python\python37\lib\site-packages\pandas\core\internals\construction.py", line 239, in init_dict
    val = construct_1d_arraylike_from_scalar(np.nan, len(index), nan_dtype)
  File "c:\users\pc\appdata\local\programs\python\python37\lib\site-packages\pandas\core\dtypes\cast.py", line 1440, in construct_1d_arraylike_from_scalar
    dtype = dtype.dtype
AttributeError: type object 'object' has no attribute 'dtype'
```

I use pandas V 1.0.3
```
D:\Developpement\Python\Trading>python
Python 3.7.8 (tags/v3.7.8:4b47a5b6ba, Jun 28 2020, 08:53:46) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
>>> pd.__version__
'1.0.3'
>>>
```

**Comment by xmatthias** [comment]
well i'm on python 3.8 - and i use the versions pinned in requirements.txt for develop - but i don't think that matters.

The error suggests that you do have a existing (empty) file in the directory (ti's failing loading the previous data, not on downloading). 
maybe try to remove the file `user_data/data/qtrade/ETH_BTC-1d.json`  - and all other files with a size of 0 too.

**Comment by LeMoussel** [comment]
There are no files & directories in `user_data/data/qtrade` directory.
In [_ohlcv_load](https://github.com/freqtrade/freqtrade/blob/develop/freqtrade/data/history/jsondatahandler.py#L88) (from freqtrade\data\history\jsondatahandler.py), there is at line 88 :
```
    if not filename.exists():
            return DataFrame(columns=self._columns)
```
Maybe error in `self._columns`

**Comment by xmatthias** [comment]
well to be honest, your pandas version seems to be quite outdated - you should make sure all library versions match the requirements file.
As this does not seem to be the case, i'll have to ask you to follow one of the installation guidelines to get the correct dependencies installed.

**Comment by LeMoussel** [comment]
You are right!
I have updated the pandas library to version 1.2.2.
Everything is OK.
Thank you very much for your support.
```
D:\Developpement\Python\Trading>freqtrade download-data --exchange qtrade -t 1d -p ETH/BTC
2021-02-18 07:59:12,174 - freqtrade.loggers - INFO - Verbosity set to 0
2021-02-18 07:59:12,174 - freqtrade.configuration.configuration - INFO - Using exchange qtrade
2021-02-18 07:59:12,175 - freqtrade.configuration.configuration - INFO - Using user-data directory: D:\Developpement\Python\Trading\user_data ...
2021-02-18 07:59:12,176 - freqtrade.configuration.configuration - INFO - Using data directory: D:\Developpement\Python\Trading\user_data\data\qtrade ...
2021-02-18 07:59:12,176 - freqtrade.configuration.configuration - INFO - Using pairs ['ETH/BTC']
2021-02-18 07:59:12,176 - freqtrade.configuration.configuration - INFO - timeframes --timeframes: ['1d']
2021-02-18 07:59:12,176 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2021-02-18 07:59:12,176 - freqtrade.configuration.check_exchange - WARNING - Exchange "qtrade" is known to the the ccxt library, available for the bot, but not officially supported by the Freqtrade development team. It may work flawlessly (please report back) or have serious issues. Use it at your own discretion.
2021-02-18 07:59:12,176 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2021-02-18 07:59:12,178 - freqtrade.resolvers.exchange_resolver - INFO - No Qtrade specific subclass found. Using the generic class instead.
2021-02-18 07:59:12,178 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2021-02-18 07:59:12,178 - freqtrade.exchange.exchange - INFO - Using CCXT 1.41.97
2021-02-18 07:59:12,181 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2021-02-18 07:59:12,185 - freqtrade.exchange.exchange - INFO - Using Exchange "qTrade"
2021-02-18 07:59:12,185 - freqtrade.exchange.exchange - INFO - Markets were not loaded. Loading them now..
2021-02-18 07:59:13,326 - freqtrade.commands.data_commands - INFO - About to download pairs: ['ETH/BTC'], intervals: ['1d'] to D:\Developpement\Python\Trading\user_data\data\qtrade
2021-02-18 07:59:13,327 - freqtrade.data.history.history_utils - INFO - Downloading pair ETH/BTC, interval 1d.
2021-02-18 07:59:13,327 - freqtrade.data.history.history_utils - INFO - Download history data for pair: "ETH/BTC", timeframe: 1d and store in D:\Developpement\Python\Trading\user_data\data\qtrade.
2021-02-18 07:59:13,338 - numexpr.utils - INFO - NumExpr defaulting to 4 threads.
2021-02-18 07:59:14,490 - freqtrade.exchange.exchange - INFO - Downloaded data for ETH/BTC with length 3.

```
