### ISSUE TITLE
Edge Positioning does not appear to work when using hdf5 for data storage

### ISSUE THREAD

**Issue by werkkrew** [freqtrade/freqtrade#4393]
## Describe your environment

  * Operating system:  Linux 5.10.2-x86_64
  * Python Version: 3.9.1 
  * CCXT version: 1.41.90 
  * Freqtrade Version: freqtrade develop-a97a5a7c
  
## Describe the problem:

When running the bot using edge positioning if data required for strategy is in hdf5 format it will not be found and the bot will crash.

### Steps to reproduce:

  1. Store all data in hdf5 format
  2. Have strategy require data other than what edge will download on its own (like an informative pair at 1h timeframe)
  3. Run the bot in dry-run or live mode
  
### Observed Results:

Bot startup takes a LONG time while edge module re-downloads about 7 days worth of 1m candles for entire whitelist in json format and then ultimately fails when it cannot find other needed timeframes for the strategy. 

Bot to start up and fill in a small gap between my previous data download and bot starting and then start as expected.

Exact same config and strategy run as expected when edge is not enabled. All other functions of freqtrade are working with hdf5 thus far except edge.

### Relevant code exceptions or logs

  ```
2021-02-18 02:52:58,925 - freqtrade.strategy.interface - DEBUG - Populating indicators for pair ADA/ETH.
2021-02-18 02:52:59,210 - freqtrade.data.dataprovider - WARNING - No data found for (ADA/ETH, 1h).
2021-02-18 02:52:59,211 - freqtrade.commands.trade_commands - ERROR - 'open'
2021-02-18 02:52:59,211 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/wkbec/freqtrade/.env/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'open'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/wkbec/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/home/wkbec/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/home/wkbec/freqtrade/freqtrade/worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/home/wkbec/freqtrade/freqtrade/freqtradebot.py", line 94, in __init__
    self.active_pair_whitelist = self._refresh_active_whitelist()
  File "/home/wkbec/freqtrade/freqtrade/freqtradebot.py", line 227, in _refresh_active_whitelist
    self.edge.calculate()
  File "/home/wkbec/freqtrade/freqtrade/edge/edge_positioning.py", line 124, in calculate
    preprocessed = self.strategy.ohlcvdata_to_dataframe(data)
  File "/home/wkbec/freqtrade/freqtrade/strategy/interface.py", line 668, in ohlcvdata_to_dataframe
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair})
  File "/home/wkbec/freqtrade/freqtrade/strategy/interface.py", line 668, in <dictcomp>
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair})
  File "/home/wkbec/freqtrade/freqtrade/strategy/interface.py", line 685, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/home/wkbec/freqtrade/user_data/strategies/ClucHAwerk.py", line 106, in populate_indicators
    inf_heikinashi = qtpylib.heikinashi(informative)
  File "/home/wkbec/freqtrade/freqtrade/vendor/qtpylib/indicators.py", line 113, in heikinashi
    bars['ha_close'] = (bars['open'] + bars['high'] +
  File "/home/wkbec/freqtrade/.env/lib/python3.9/site-packages/pandas/core/frame.py", line 3024, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/wkbec/freqtrade/.env/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: 'open'
2021-02-18 02:52:59,413 - freqtrade.exchange.exchange - DEBUG - Exchange object destroyed, closing async loop
  ```

**Comment by xmatthias** [comment]
best pull the latest develop and try again ... i think the problem was that the download didn't use hdf5 data, while loading the data did ... so you'd download json data, but use hdf5 data. 


Even if you have hdf5 history - edge requires the last X days / hours - which you might not have (the real range depends on your edge configurations ...)

**Comment by werkkrew** [comment]
It is better in that it doesnt take so long to get the error (seems to recognize the 1m data in hdf5), but it still bails when the strategy wants to populate the indicators for the strategy. Note: This exact strategy file and datraset work 100% fine in backtesting, hyperopt, and live trading without edge.

```
2021-02-18 11:02:10,889 - freqtrade.data.converter - INFO - Missing data fillup for YFI/ETH: before: 1155 - after: 11019
2021-02-18 11:02:10,889 - freqtrade.strategy.interface - DEBUG - Populating indicators for pair ADA/ETH.
2021-02-18 11:02:11,197 - freqtrade.data.dataprovider - WARNING - No data found for (ADA/ETH, 1h).
2021-02-18 11:02:11,197 - freqtrade.commands.trade_commands - ERROR - 'open'
2021-02-18 11:02:11,197 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/wkbec/freqtrade/.env/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'open'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/wkbec/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/home/wkbec/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/home/wkbec/freqtrade/freqtrade/worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/home/wkbec/freqtrade/freqtrade/freqtradebot.py", line 94, in __init__
    self.active_pair_whitelist = self._refresh_active_whitelist()
  File "/home/wkbec/freqtrade/freqtrade/freqtradebot.py", line 228, in _refresh_active_whitelist
    self.edge.calculate()
  File "/home/wkbec/freqtrade/freqtrade/edge/edge_positioning.py", line 125, in calculate
    preprocessed = self.strategy.ohlcvdata_to_dataframe(data)
  File "/home/wkbec/freqtrade/freqtrade/strategy/interface.py", line 668, in ohlcvdata_to_dataframe
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair})
  File "/home/wkbec/freqtrade/freqtrade/strategy/interface.py", line 668, in <dictcomp>
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair})
  File "/home/wkbec/freqtrade/freqtrade/strategy/interface.py", line 685, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/home/wkbec/freqtrade/user_data/strategies/ClucHAwerk.py", line 106, in populate_indicators
    inf_heikinashi = qtpylib.heikinashi(informative)
  File "/home/wkbec/freqtrade/freqtrade/vendor/qtpylib/indicators.py", line 113, in heikinashi
    bars['ha_close'] = (bars['open'] + bars['high'] +
  File "/home/wkbec/freqtrade/.env/lib/python3.9/site-packages/pandas/core/frame.py", line 3024, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/wkbec/freqtrade/.env/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: 'open'
2021-02-18 11:02:11,381 - freqtrade.exchange.exchange - DEBUG - Exchange object destroyed, closing async loop
```

```
(.env) wkbec at thorim in ~/freqtrade$ ls -al user_data/data/kraken/ | grep ADA
-rw-r--r-- 1 wkbec werkkrew    106068 Feb 18 10:52 ADA_BTC-1h.h5
-rw-r--r-- 1 wkbec werkkrew   2095802 Feb 18 10:52 ADA_BTC-1m.h5
-rw-r--r-- 1 wkbec werkkrew    767791 Feb 18 10:52 ADA_BTC-5m.h5
-rw-r--r-- 1 wkbec werkkrew   8163793 Feb 18 10:36 ADA_BTC-trades.h5
-rw-r--r-- 1 wkbec werkkrew    103020 Feb 18 10:52 ADA_ETH-1h.h5
-rw-r--r-- 1 wkbec werkkrew   1469674 Feb 18 11:00 ADA_ETH-1m.h5
-rw-r--r-- 1 wkbec werkkrew    665631 Feb 18 10:52 ADA_ETH-5m.h5
-rw-r--r-- 1 wkbec werkkrew   4726922 Feb 18 10:36 ADA_ETH-trades.h5
-rw-r--r-- 1 wkbec werkkrew    104262 Feb 18 10:53 ADA_USD-1h.h5
-rw-r--r-- 1 wkbec werkkrew   3225590 Feb 18 10:53 ADA_USD-1m.h5
-rw-r--r-- 1 wkbec werkkrew    828046 Feb 18 10:53 ADA_USD-5m.h5
-rw-r--r-- 1 wkbec werkkrew  32224986 Feb 18 10:42 ADA_USD-trades.h5
```

**Comment by xmatthias** [comment]
it doesn't seem to be related to edge directly - but with the strategy itself, which is passing an invalid dataframe to a indicator generation.

By the name, i guess there's some problem with the informative pair you're passing in- but it's difficult to tell what is causing this - it's however not related to edge itself (or to useing hdf5) to me - but to your strategy.

**Comment by werkkrew** [comment]
Well if that is the case why would the same strategy work fine in backtest, hyperopt, live trading, dry-run, and every other function when edge is not enabled? Is there a chance that something with the strategy is wrong but the other functions of the bot are not affected by it?

**Comment by xmatthias** [comment]
well the problem is that edge is technically it's own mode - but ALSO regular trade mode.

so if you need to do differences based on run-mode, it's possible that edge falls through that filter - as it's something in the middle (with the strategy loading once, and being called for real-time data, as well as for historic data).

**Comment by werkkrew** [comment]
Well that may be true that something is wrong in my strategy but I think its more likely that edge isn't doing something gracefully that it should, otherwise I would expect my strategy would not work (even if it didnt error out), and the function in my strategy that is failing in the edge module:

```
informative = self.dp.get_pair_dataframe(pair=metadata['pair'], timeframe=inf_tf)
inf_heikinashi = qtpylib.heikinashi(informative)
```

Works and returns valid data and is effective in the strategy in every other bot mode but the edge module.

If there is something I need to change for edge compatibility I am happy to do that, but my point is that whatever is wrong is:
1) Not obvious at all as the strategy works as expected in every other case
2) Unique to the edge module, which tells me that the edge module needs to be better about what it tells the user is wrong in a case such as this.

I have a feeling edge might not work for anyone using informative pairs outside the base strategy timeframe and error out in a similar way. 

This may or may not be unique to data stored in hdf5 or not, I am not sure. I can test that by converting everything back to json but it does not sound like you think there would be value in doing that.

**Comment by xmatthias** [comment]
no, hdf5 is definitely not related

It is most likely because of the run_mode - which will load data from a different source when using edge.

Also, edge will not automatically refresh informative pair's downloaded data - so you might run into problems after running edge for some time - so fixing the "original" problem may not be enough either - not when using informative pairs.
