### ISSUE TITLE
Question regarding the command freqtrade trade --config config.json --strategy SampleStrategy

### ISSUE THREAD

**Issue by ilyassbc** [freqtrade/freqtrade#4416]
Hi,

 When I run the command: `freqtrade trade --config config.json --strategy SampleStrategy` , I get the error that I'll show below. Am I supposed to create a sample strategy? If so could you kindly tell me how to do? Thank you in advance.
```
2021-02-22 03:19:34,921 - freqtrade.worker - INFO - Starting worker develop-95fcb1eb
2021-02-22 03:19:34,922 - freqtrade.configuration.configuration - INFO - Using config: config.json ...
2021-02-22 03:19:34,922 - freqtrade.loggers - INFO - Verbosity set to 0
2021-02-22 03:19:34,922 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
2021-02-22 03:19:34,922 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2021-02-22 03:19:34,922 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:///tradesv3.dryrun.sqlite"
2021-02-22 03:19:34,922 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 3 ...
2021-02-22 03:19:34,922 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/ilyassbc/freqtrade/user_data ...
2021-02-22 03:19:34,923 - freqtrade.configuration.configuration - INFO - Using data directory: /home/ilyassbc/freqtrade/user_data/data/binance ...
2021-02-22 03:19:34,923 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2021-02-22 03:19:34,923 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2021-02-22 03:19:34,923 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2021-02-22 03:19:34,923 - freqtrade.freqtradebot - INFO - Starting freqtrade develop-95fcb1eb
2021-02-22 03:19:34,924 - freqtrade.resolvers.iresolver - WARNING - Could not import /home/ilyassbc/freqtrade/user_data/strategies/sample_strategy.py due to 'libta_lib.so.0: cannot open shared object file: No such file or directory'
2021-02-22 03:19:34,924 - freqtrade.commands.trade_commands - ERROR - Impossible to load Strategy 'bid_strategy'. This class does not exist or contains Python code errors.
2021-02-22 03:19:34,924 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/ilyassbc/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/home/ilyassbc/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/home/ilyassbc/freqtrade/freqtrade/worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/home/ilyassbc/freqtrade/freqtrade/freqtradebot.py", line 66, in __init__
    self.strategy: IStrategy = StrategyResolver.load_strategy(self.config)
  File "/home/ilyassbc/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 45, in load_strategy
    strategy: IStrategy = StrategyResolver._load_strategy(
  File "/home/ilyassbc/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 206, in _load_strategy
    raise OperationalException(
freqtrade.exceptions.OperationalException: Impossible to load Strategy 'bid_strategy'. This class does not exist or contains Python code errors.
```

**Comment by xmatthias** [comment]
> 2021-02-22 03:19:34,924 - freqtrade.resolvers.iresolver - WARNING - Could not import /home/ilyassbc/freqtrade/user_data/strategies/sample_strategy.py due to 'libta_lib.so.0: cannot open shared object file: No such file or directory'

Your ta-lib installation is not correct / not working - you did miss to install the C library (before installing the python wrapper).

Make sure to follow the installation documentation step by step without skipping a step (whichever installation setup you were following from the [documentation](https://www.freqtrade.io/en/latest/)).
