### ISSUE TITLE
Docker quick start doesn't start -- StaticPairList requires pair_whitelist to be set

### ISSUE THREAD

**Issue by seguri** [freqtrade/freqtrade#4441]
## Describe your environment

  * Operating system: 10.15.7
  * Python Version: 3.9.1, but I'm using Docker
  * CCXT version: empty, but I'm using Docker
  * Freqtrade Version: 2021.1
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

I've followed the quick start and couldn't start the bot.

### Steps to reproduce:

Follow the quickstart:

```
$ docker-compose pull
$ docker-compose run --rm freqtrade create-userdir --userdir user_data
$ docker-compose run --rm freqtrade new-config --config user_data/config.json
Creating freqtrade_freqtrade_run ... done
? Do you want to enable Dry-run (simulated trades)? Yes
? Please insert your stake currency: BTC
? Please insert your stake amount: 0.01
? Please insert max_open_trades (Integer or 'unlimited'): 3
? Please insert your desired timeframe (e.g. 5m): 5m
? Please insert your display Currency (for reporting): USD
? Select exchange other
? Type your exchange name (Must be supported by ccxt) coinbasepro
? Do you want to enable Telegram? No
2021-02-25 19:53:21,879 - freqtrade.commands.build_config_commands - INFO - Writing config to `user_data/config.json`.
$ docker-compose up -d
$ docker-compose logs -f
<see exception below>
```

I also tried to add `BTC/USD` (taken from `docker-compose run --rm freqtrade list-pairs --exchange coinbasepro --quote USD --print-json`) to `pair_whitelist` inside `user_data/config.json`, but got another exception.
  
### Observed Results:

  * What happened? Exception
  * What did you expect to happen? Some dry run trades

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

```
freqtrade    | 2021-02-25 19:50:36,955 - freqtrade.commands.trade_commands - ERROR - StaticPairList requires pair_whitelist to be set.
freqtrade    | 2021-02-25 19:50:36,956 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
freqtrade    | Traceback (most recent call last):
freqtrade    |   File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
freqtrade    |     worker = Worker(args)
freqtrade    |   File "/freqtrade/freqtrade/worker.py", line 35, in __init__
freqtrade    |     self._init(False)
freqtrade    |   File "/freqtrade/freqtrade/worker.py", line 52, in _init
freqtrade    |     self.freqtrade = FreqtradeBot(self._config)
freqtrade    |   File "/freqtrade/freqtrade/freqtradebot.py", line 69, in __init__
freqtrade    |     validate_config_consistency(config)
freqtrade    |   File "/freqtrade/freqtrade/configuration/config_validation.py", line 76, in validate_config_consistency
freqtrade    |     _validate_whitelist(conf)
freqtrade    |   File "/freqtrade/freqtrade/configuration/config_validation.py", line 158, in _validate_whitelist
freqtrade    |     raise OperationalException("StaticPairList requires pair_whitelist to be set.")
freqtrade    | freqtrade.exceptions.OperationalException: StaticPairList requires pair_whitelist to be set.
```

With `BTC/USD`:
```
freqtrade    | 2021-02-25 19:36:16,725 - freqtrade.commands.trade_commands - ERROR - Stake-currency 'BTC' not compatible with pair-whitelist. Please remove the following pairs: ['BTC/USD']
freqtrade    | 2021-02-25 19:36:16,727 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
freqtrade    | Traceback (most recent call last):
freqtrade    |   File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
freqtrade    |     worker = Worker(args)
freqtrade    |   File "/freqtrade/freqtrade/worker.py", line 35, in __init__
freqtrade    |     self._init(False)
freqtrade    |   File "/freqtrade/freqtrade/worker.py", line 52, in _init
freqtrade    |     self.freqtrade = FreqtradeBot(self._config)
freqtrade    |   File "/freqtrade/freqtrade/freqtradebot.py", line 71, in __init__
freqtrade    |     self.exchange = ExchangeResolver.load_exchange(self.config['exchange']['name'], self.config)
freqtrade    |   File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 38, in load_exchange
freqtrade    |     exchange = Exchange(config, validate=validate)
freqtrade    |   File "/freqtrade/freqtrade/exchange/exchange.py", line 129, in __init__
freqtrade    |     self.validate_pairs(config['exchange']['pair_whitelist'])
freqtrade    |   File "/freqtrade/freqtrade/exchange/exchange.py", line 366, in validate_pairs
freqtrade    |     raise OperationalException(
freqtrade    | freqtrade.exceptions.OperationalException: Stake-currency 'BTC' not compatible with pair-whitelist. Please remove the following pairs: ['BTC/USD']
```

**Comment by xmatthias** [comment]
well the error seems quite clear. 
When you're using BTC/USD - then USD is your stake currency.

Please be aware however that coinbasepro is not a supported exchange (and i don't think it works correctly based on other user's feedback).

**Comment by seguri** [comment]
Of course the error it's clear for the main contributor ;)

I've repeated the quickstart for the 5 exchanges suggested during `new-config` and only 2 of them let the bot start correctly: binance and bittrex.

binanceje:

```
freqtrade    | 2021-02-25 20:57:38,342 - freqtrade.commands.trade_commands - ERROR - Exchange "binanceje" is not known to the ccxt library and therefore not available for the bot.
freqtrade    | The following exchanges are available for Freqtrade: acx, aofex, bequant, bibox, binance, binanceus, bitbank, bitcoincom, bitfinex, bitfinex2, bitget, bitkk, bitmart, bitmax, bitpanda, bittrex, bitvavo, bitz, bleutrade, btcalpha, btcmarkets, btcturk, buda, bw, bybit, bytetrade, cdax, cex, coinbaseprime, coinbasepro, coinex, crex24, currencycom, delta, digifinex, dsx, eterbase, fcoin, fcoinjp, ftx, gateio, gemini, gopax, hbtc, hollaex, huobijp, huobipro, idex, kraken, kucoin, kuna, lbank, mercado, novadax, oceanex, okcoin, okex, probit, qtrade, rightbtc, ripio, stex, tidebit, timex, upbit, vcc, wavesexchange, whitebit, xena, zb
freqtrade    | 2021-02-25 20:57:38,344 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
freqtrade    | Traceback (most recent call last):
freqtrade    |   File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
freqtrade    |     worker = Worker(args)
freqtrade    |   File "/freqtrade/freqtrade/worker.py", line 35, in __init__
freqtrade    |     self._init(False)
freqtrade    |   File "/freqtrade/freqtrade/worker.py", line 49, in _init
freqtrade    |     self._config = Configuration(self._args, None).get_config()
freqtrade    |   File "/freqtrade/freqtrade/configuration/configuration.py", line 41, in get_config
freqtrade    |     self.config = self.load_config()
freqtrade    |   File "/freqtrade/freqtrade/configuration/configuration.py", line 112, in load_config
freqtrade    |     check_exchange(config, config.get('experimental', {}).get('block_bad_exchanges', True))
freqtrade    |   File "/freqtrade/freqtrade/configuration/check_exchange.py", line 53, in check_exchange
freqtrade    |     raise OperationalException(
freqtrade    | freqtrade.exceptions.OperationalException: Exchange "binanceje" is not known to the ccxt library and therefore not available for the bot.
freqtrade    | The following exchanges are available for Freqtrade: acx, aofex, bequant, bibox, binance, binanceus, bitbank, bitcoincom, bitfinex, bitfinex2, bitget, bitkk, bitmart, bitmax, bitpanda, bittrex, bitvavo, bitz, bleutrade, btcalpha, btcmarkets, btcturk, buda, bw, bybit, bytetrade, cdax, cex, coinbaseprime, coinbasepro, coinex, crex24, currencycom, delta, digifinex, dsx, eterbase, fcoin, fcoinjp, ftx, gateio, gemini, gopax, hbtc, hollaex, huobijp, huobipro, idex, kraken, kucoin, kuna, lbank, mercado, novadax, oceanex, okcoin, okex, probit, qtrade, rightbtc, ripio, stex, tidebit, timex, upbit, vcc, wavesexchange, whitebit, xena, zb
```

binanceus:

```
freqtrade    | 2021-02-25 20:58:52,089 - freqtrade.commands.trade_commands - ERROR - Pair ALGO/BTC is not available on Binance US. Please remove ALGO/BTC from your whitelist.
freqtrade    | 2021-02-25 20:58:52,092 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
freqtrade    | Traceback (most recent call last):
freqtrade    |   File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
freqtrade    |     worker = Worker(args)
freqtrade    |   File "/freqtrade/freqtrade/worker.py", line 35, in __init__
freqtrade    |     self._init(False)
freqtrade    |   File "/freqtrade/freqtrade/worker.py", line 52, in _init
freqtrade    |     self.freqtrade = FreqtradeBot(self._config)
freqtrade    |   File "/freqtrade/freqtrade/freqtradebot.py", line 71, in __init__
freqtrade    |     self.exchange = ExchangeResolver.load_exchange(self.config['exchange']['name'], self.config)
freqtrade    |   File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 31, in load_exchange
freqtrade    |     exchange = ExchangeResolver._load_exchange(exchange_name,
freqtrade    |   File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 53, in _load_exchange
freqtrade    |     exchange = ex_class(**kwargs)
freqtrade    |   File "/freqtrade/freqtrade/exchange/exchange.py", line 129, in __init__
freqtrade    |     self.validate_pairs(config['exchange']['pair_whitelist'])
freqtrade    |   File "/freqtrade/freqtrade/exchange/exchange.py", line 345, in validate_pairs
freqtrade    |     raise OperationalException(
freqtrade    | freqtrade.exceptions.OperationalException: Pair ALGO/BTC is not available on Binance US. Please remove ALGO/BTC from your whitelist.
```

kraken:

```
freqtrade    | 2021-02-25 21:03:03,722 - freqtrade.commands.trade_commands - ERROR - Stake-currency 'BTC' not compatible with pair-whitelist. Please remove the following pairs: ['ADA/EUR', 'ATOM/EUR', 'BAT/EUR', 'BCH/EUR', 'BTC/EUR', 'DAI/EUR', 'DASH/EUR', 'EOS/EUR', 'ETC/EUR', 'ETH/EUR', 'LINK/EUR', 'LTC/EUR', 'QTUM/EUR', 'REP/EUR', 'WAVES/EUR', 'XLM/EUR', 'XMR/EUR', 'XRP/EUR', 'XTZ/EUR', 'ZEC/EUR']
freqtrade    | 2021-02-25 21:03:03,724 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
freqtrade    | Traceback (most recent call last):
freqtrade    |   File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
freqtrade    |     worker = Worker(args)
freqtrade    |   File "/freqtrade/freqtrade/worker.py", line 35, in __init__
freqtrade    |     self._init(False)
freqtrade    |   File "/freqtrade/freqtrade/worker.py", line 52, in _init
freqtrade    |     self.freqtrade = FreqtradeBot(self._config)
freqtrade    |   File "/freqtrade/freqtrade/freqtradebot.py", line 71, in __init__
freqtrade    |     self.exchange = ExchangeResolver.load_exchange(self.config['exchange']['name'], self.config)
freqtrade    |   File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 31, in load_exchange
freqtrade    |     exchange = ExchangeResolver._load_exchange(exchange_name,
freqtrade    |   File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 53, in _load_exchange
freqtrade    |     exchange = ex_class(**kwargs)
freqtrade    |   File "/freqtrade/freqtrade/exchange/exchange.py", line 129, in __init__
freqtrade    |     self.validate_pairs(config['exchange']['pair_whitelist'])
freqtrade    |   File "/freqtrade/freqtrade/exchange/exchange.py", line 366, in validate_pairs
freqtrade    |     raise OperationalException(
freqtrade    | freqtrade.exceptions.OperationalException: Stake-currency 'BTC' not compatible with pair-whitelist. Please remove the following pairs: ['ADA/EUR', 'ATOM/EUR', 'BAT/EUR', 'BCH/EUR', 'BTC/EUR', 'DAI/EUR', 'DASH/EUR', 'EOS/EUR', 'ETC/EUR', 'ETH/EUR', 'LINK/EUR', 'LTC/EUR', 'QTUM/EUR', 'REP/EUR', 'WAVES/EUR', 'XLM/EUR', 'XMR/EUR', 'XRP/EUR', 'XTZ/EUR', 'ZEC/EUR']
```

**Comment by xmatthias** [comment]
the quickstart is NOT intended to run "right out of the box" - at least not without looking through the configuration, and understanding the options (and it's implications) freqtrade offers.

The assumption is that you'll modify the pairlist to pairs that are 
a) matching your stake-currency
b) available on your exchange

You will also need to read through the documentation to understand what configurations you might want to take. While the quickstart will generate a mostly functional config - pairlists will always have to be adjusted to the user needs and strategy (you did backtest first, so you know how your strategy does behave, right?).


Apart from that, binanceje is not a valid exchange (at least not one supported by ccxt).


**edit**:
I've now removed binanceje from the pre-selection (it used to be supported, but apparently was removed from ccxt).
I've also added a note to both the docs and to the `new-config` command pointing out that the config will still need to be edited.

**Comment by abir-taheer** [comment]
I don't know if this was fixed but I ran into this error again (outside of a docker env albeit). I'm also using coinbasepro. Is there anything I need to do?

**Comment by xmatthias** [comment]
This was fixed - make sure to use the latest version.

If you still encounter that issue with the last version (2021.3 or develop) please open an issue with your exception (filling out the issue template), as in that case it would be something new.
