### ISSUE TITLE
Order does not exist. ( again )

### ISSUE THREAD

**Issue by cderivan** [freqtrade/freqtrade#4456]
`The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/common.py", line 136, in wrapper
    return f(*args, **kwargs)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 1128, in fetch_order
    raise RetryableOrderError(
freqtrade.exceptions.RetryableOrderError: Order not found (pair: ETC/USDT id: 1014885381). Message: binance {"code":-2013,"msg":"Order does not exist."}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 592, in fetch
    response.raise_for_status()
  File "/root/.local/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order?timestamp=1614457022625&recvWindow=5000&symbol=ETCUSDT&orderId=1014885381&signature=8c8d34b81404f9eb99a4b58417671cab83e82ba86d24a20dfd8a4bf01f99cc3b

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/exchange.py", line 1126, in fetch_order
    return self._api.fetch_order(order_id, pair)
  File "/root/.local/lib/python3.9/site-packages/ccxt/binance.py", line 1901, in fetch_order
    response = getattr(self, method)(self.extend(request, query))
  File "/root/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 466, in inner
    return entry(_self, **inner_kwargs)
  File "/root/.local/lib/python3.9/site-packages/ccxt/binance.py", line 2702, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/root/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 487, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/root/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 608, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/root/.local/lib/python3.9/site-packages/ccxt/binance.py", line 2696, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions, error, feedback)
  File "/root/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 505, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.OrderNotFound: binance {"code":-2013,"msg":"Order does not exist."}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/freqtradebot.py", line 969, in check_handle_timedout
    order = self.exchange.fetch_order(trade.open_order_id, trade.pair)
  File "/freqtrade/freqtrade/exchange/common.py", line 148, in wrapper
    return wrapper(*args, **kwargs)
  File "/freqtrade/freqtrade/exchange/common.py", line 148, in wrapper
    return wrapper(*args, **kwargs)
  File "/freqtrade/freqtrade/exchange/common.py", line 148, in wrapper
    return wrapper(*args, **kwargs)
  [Previous line repeated 2 more times]
  File "/freqtrade/freqtrade/exchange/common.py", line 151, in wrapper
    raise ex
  File "/freqtrade/freqtrade/exchange/common.py", line 136, in wrapper
    return f(*args, **kwargs)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 1128, in fetch_order
    raise RetryableOrderError(
freqtrade.exceptions.RetryableOrderError: Order not found (pair: ETC/USDT id: 1014885381). Message: binance {"code":-2013,"msg":"Order does not exist."}
`

**Comment by xmatthias** [comment]
Please fill out the issue template, otherwise i'll close this issue without further notice.

**Comment by cderivan** [comment]
I dont wanna, I am close it will debug de code myself
