### ISSUE TITLE
ERROR:    Exception in ASGI application

### ISSUE THREAD

**Issue by aristosv** [freqtrade/freqtrade#4459]
**Describe the bug**
error in the log file: ERROR:    Exception in ASGI application

**To Reproduce**
I'm just tailing the log file

I just wanted to mention that since yesterday that I installed frequi, I have been getting this in the log file.

Debian 10
Python 3.7.3
ccxt==1.42.19
freqtrade develop-cc12919e

I installed frequi using this command
reqtrade install-ui

```
2021-02-28 08:28:11,626 - freqtrade.freqtradebot - WARNING - Unable to create trade for PIVX/BTC: Available balance (0.0020354889299999956 BTC) is lower than stake amount (0.0022 BTC)
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/starlette/middleware/cors.py", line 78, in __call__
    await self.app(scope, receive, send)
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/fastapi/routing.py", line 202, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/fastapi/routing.py", line 148, in run_endpoint_function
    return await dependant.call(**values)
  File "/root/freqtrade1/freqtrade/rpc/api_server/web_ui.py", line 13, in favicon
    return FileResponse(Path(__file__).parent / 'ui/favicon.ico')
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/starlette/responses.py", line 257, in __init__
    media_type = guess_type(filename or path)[0] or "text/plain"
  File "/usr/lib/python3.7/mimetypes.py", line 291, in guess_type
    return _db.guess_type(url, strict)
  File "/usr/lib/python3.7/mimetypes.py", line 116, in guess_type
    scheme, url = urllib.parse.splittype(url)
  File "/usr/lib/python3.7/urllib/parse.py", line 976, in splittype
    match = _typeprog.match(url)
TypeError: expected string or bytes-like object
2021-02-28 08:28:22,385 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/starlette/middleware/cors.py", line 78, in __call__
    await self.app(scope, receive, send)
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/fastapi/routing.py", line 202, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/fastapi/routing.py", line 148, in run_endpoint_function
    return await dependant.call(**values)
  File "/root/freqtrade1/freqtrade/rpc/api_server/web_ui.py", line 13, in favicon
    return FileResponse(Path(__file__).parent / 'ui/favicon.ico')
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/starlette/responses.py", line 257, in __init__
    media_type = guess_type(filename or path)[0] or "text/plain"
  File "/usr/lib/python3.7/mimetypes.py", line 291, in guess_type
    return _db.guess_type(url, strict)
  File "/usr/lib/python3.7/mimetypes.py", line 116, in guess_type
    scheme, url = urllib.parse.splittype(url)
  File "/usr/lib/python3.7/urllib/parse.py", line 976, in splittype
    match = _typeprog.match(url)
TypeError: expected string or bytes-like object
2021-02-28 08:28:23,364 - freqtrade.rpc.rpc - WARNING -  Could not get rate for pair COCOS.
2021-02-28 08:28:33,637 - freqtrade.wallets - INFO - Wallets synced.
```

**Comment by xmatthias** [comment]
best pull the latest develop (which includes 05f057) and try again.

while the issue does not occur to me, it should still fix it by explicitly casting the path to string.
