### ISSUE TITLE
binance fetch_order: 400 Client Error: Bad Request for url

### ISSUE THREAD

**Issue by aristosv** [freqtrade/freqtrade#4462]
## Describe your environment

  * Operating system: Debian 10
  * Python Version: Python 3.7.3
  * CCXT version: ccxt==1.42.19
  * Freqtrade Version: freqtrade develop-05f057fe

## Describe the problem:
400 Client Error: Bad Request for url
Log here: https://pastebin.pl/view/8109d19d

### Steps to reproduce:
  1. Start freqtrade
  2. Tail log file
  
### Observed Results:

  * What happened?
 Error in log file

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
2021-02-28 18:26:20,697 - freqtrade.wallets - INFO - Wallets synced.
2021-02-28 18:26:20,700 - freqtrade.freqtradebot - INFO - Buy signal found: about create a new trade with stake_amount: 0.0022 ...
2021-02-28 18:26:20,700 - freqtrade.freqtradebot - INFO - Executing Buy for CELR/BTC
2021-02-28 18:26:20,700 - freqtrade.freqtradebot - INFO - Using Last Bid / Last Price
2021-02-28 18:26:22,181 - freqtrade.wallets - INFO - Wallets synced.
2021-02-28 18:26:22,185 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'trade_id': 192, 'type': buy, 'exchange': 'Binance', 'pair': 'CELR/BTC', 'limit': 4.5e-07, 'order_type': 'limit', 'stake_amount': 0.0022, 'stake_currency': 'BTC', 'fiat_currency': 'USD', 'amount': 4888.88888888889, 'open_date': datetime.datetime(2021, 2, 28, 16, 26, 21, 671842), 'current_rate': 4.5e-07}
2021-02-28 18:26:23,825 - freqtrade.worker - INFO - Bot heartbeat. PID=1037, version='develop-05f057fe', state='RUNNING'
2021-02-28 18:26:29,305 - freqtrade.exchange.common - WARNING - fetch_order() returned exception: "Order not found (pair: CELR/BTC id: 38765245). Message: binance {"code":-2013,"msg":"Order does not exist."}"
2021-02-28 18:26:29,306 - freqtrade.exchange.common - WARNING - retrying fetch_order() still for 5 times
2021-02-28 18:26:29,306 - freqtrade.exchange.common - INFO - Applying DDosProtection backoff delay: 1
2021-02-28 18:26:30,548 - freqtrade.exchange.common - WARNING - fetch_order() returned exception: "Order not found (pair: CELR/BTC id: 38765245). Message: binance {"code":-2013,"msg":"Order does not exist."}"
2021-02-28 18:26:30,549 - freqtrade.exchange.common - WARNING - retrying fetch_order() still for 4 times
2021-02-28 18:26:30,549 - freqtrade.exchange.common - INFO - Applying DDosProtection backoff delay: 2
2021-02-28 18:26:32,788 - freqtrade.exchange.common - WARNING - fetch_order() returned exception: "Order not found (pair: CELR/BTC id: 38765245). Message: binance {"code":-2013,"msg":"Order does not exist."}"
2021-02-28 18:26:32,788 - freqtrade.exchange.common - WARNING - retrying fetch_order() still for 3 times
2021-02-28 18:26:32,789 - freqtrade.exchange.common - INFO - Applying DDosProtection backoff delay: 5
2021-02-28 18:26:45,937 - freqtrade.exchange.common - WARNING - fetch_order() returned exception: "Order not found (pair: CELR/BTC id: 38765245). Message: binance {"code":-2013,"msg":"Order does not exist."}"
2021-02-28 18:26:45,938 - freqtrade.exchange.common - WARNING - retrying fetch_order() still for 2 times
2021-02-28 18:26:45,938 - freqtrade.exchange.common - INFO - Applying DDosProtection backoff delay: 10
2021-02-28 18:26:56,183 - freqtrade.exchange.common - WARNING - fetch_order() returned exception: "Order not found (pair: CELR/BTC id: 38765245). Message: binance {"code":-2013,"msg":"Order does not exist."}"
2021-02-28 18:26:56,184 - freqtrade.exchange.common - WARNING - retrying fetch_order() still for 1 times
2021-02-28 18:26:56,184 - freqtrade.exchange.common - INFO - Applying DDosProtection backoff delay: 17
2021-02-28 18:27:13,429 - freqtrade.exchange.common - WARNING - fetch_order() returned exception: "Order not found (pair: CELR/BTC id: 38765245). Message: binance {"code":-2013,"msg":"Order does not exist."}"
2021-02-28 18:27:13,429 - freqtrade.exchange.common - WARNING - Giving up retrying: fetch_order()
2021-02-28 18:27:13,433 - freqtrade.freqtradebot - INFO - Cannot query order for Trade(id=192, pair=CELR/BTC, amount=4888.88888889, open_rate=0.00000045, open_since=2021-02-28 16:26:21) due to Traceback (most recent call last):
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 592, in fetch
    response.raise_for_status()
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order?timestamp=1614529589074&recvWindow=5000&symbol=CELRBTC&orderId=38765245&signature=dc7c47544474d25c2b1d7e8503a1c697757eda621823b2283c2c19f2da251772

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/freqtrade1/freqtrade/exchange/exchange.py", line 1126, in fetch_order
    return self._api.fetch_order(order_id, pair)
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/ccxt/binance.py", line 1901, in fetch_order
    response = getattr(self, method)(self.extend(request, query))
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 466, in inner
    return entry(_self, **inner_kwargs)
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/ccxt/binance.py", line 2702, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 487, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 608, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/ccxt/binance.py", line 2696, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions, error, feedback)
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 505, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.OrderNotFound: binance {"code":-2013,"msg":"Order does not exist."}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/freqtrade1/freqtrade/exchange/common.py", line 136, in wrapper
    return f(*args, **kwargs)
  File "/root/freqtrade1/freqtrade/exchange/exchange.py", line 1129, in fetch_order
    f'Order not found (pair: {pair} id: {order_id}). Message: {e}') from e
freqtrade.exceptions.RetryableOrderError: Order not found (pair: CELR/BTC id: 38765245). Message: binance {"code":-2013,"msg":"Order does not exist."}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 592, in fetch
    response.raise_for_status()
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order?timestamp=1614529590307&recvWindow=5000&symbol=CELRBTC&orderId=38765245&signature=8cc125778f5e45b4916db61a1115d7a4d80d6fa1e2ead1325a2b663648229a57

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/freqtrade1/freqtrade/exchange/exchange.py", line 1126, in fetch_order
    return self._api.fetch_order(order_id, pair)
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/ccxt/binance.py", line 1901, in fetch_order
    response = getattr(self, method)(self.extend(request, query))
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 466, in inner
    return entry(_self, **inner_kwargs)
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/ccxt/binance.py", line 2702, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 487, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 608, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/ccxt/binance.py", line 2696, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions, error, feedback)
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 505, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.OrderNotFound: binance {"code":-2013,"msg":"Order does not exist."}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/freqtrade1/freqtrade/exchange/common.py", line 136, in wrapper
    return f(*args, **kwargs)
  File "/root/freqtrade1/freqtrade/exchange/exchange.py", line 1129, in fetch_order
    f'Order not found (pair: {pair} id: {order_id}). Message: {e}') from e
freqtrade.exceptions.RetryableOrderError: Order not found (pair: CELR/BTC id: 38765245). Message: binance {"code":-2013,"msg":"Order does not exist."}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 592, in fetch
    response.raise_for_status()
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order?timestamp=1614529592551&recvWindow=5000&symbol=CELRBTC&orderId=38765245&signature=e6832ca77b08c6dc677c386ec19364e3f5552085c1e5976608840ca4ae002f17

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/freqtrade1/freqtrade/exchange/exchange.py", line 1126, in fetch_order
    return self._api.fetch_order(order_id, pair)
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/ccxt/binance.py", line 1901, in fetch_order
    response = getattr(self, method)(self.extend(request, query))
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 466, in inner
    return entry(_self, **inner_kwargs)
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/ccxt/binance.py", line 2702, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 487, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 608, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/ccxt/binance.py", line 2696, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions, error, feedback)
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 505, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.OrderNotFound: binance {"code":-2013,"msg":"Order does not exist."}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/freqtrade1/freqtrade/exchange/common.py", line 136, in wrapper
    return f(*args, **kwargs)
  File "/root/freqtrade1/freqtrade/exchange/exchange.py", line 1129, in fetch_order
    f'Order not found (pair: {pair} id: {order_id}). Message: {e}') from e
freqtrade.exceptions.RetryableOrderError: Order not found (pair: CELR/BTC id: 38765245). Message: binance {"code":-2013,"msg":"Order does not exist."}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 592, in fetch
    response.raise_for_status()
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order?timestamp=1614529597794&recvWindow=5000&symbol=CELRBTC&orderId=38765245&signature=5cf6c310843fc12c17256a6bc581efdec0316a9993dfb2efae9b8d17178a9081

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/freqtrade1/freqtrade/exchange/exchange.py", line 1126, in fetch_order
    return self._api.fetch_order(order_id, pair)
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/ccxt/binance.py", line 1901, in fetch_order
    response = getattr(self, method)(self.extend(request, query))
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 466, in inner
    return entry(_self, **inner_kwargs)
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/ccxt/binance.py", line 2702, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 487, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 608, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/ccxt/binance.py", line 2696, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions, error, feedback)
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 505, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.OrderNotFound: binance {"code":-2013,"msg":"Order does not exist."}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/freqtrade1/freqtrade/exchange/common.py", line 136, in wrapper
    return f(*args, **kwargs)
  File "/root/freqtrade1/freqtrade/exchange/exchange.py", line 1129, in fetch_order
    f'Order not found (pair: {pair} id: {order_id}). Message: {e}') from e
freqtrade.exceptions.RetryableOrderError: Order not found (pair: CELR/BTC id: 38765245). Message: binance {"code":-2013,"msg":"Order does not exist."}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 592, in fetch
    response.raise_for_status()
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order?timestamp=1614529615948&recvWindow=5000&symbol=CELRBTC&orderId=38765245&signature=c0d644fbdaace240861f59afb6b194429f8238ebe7eca0118afda44017ecf81c

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/freqtrade1/freqtrade/exchange/exchange.py", line 1126, in fetch_order
    return self._api.fetch_order(order_id, pair)
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/ccxt/binance.py", line 1901, in fetch_order
    response = getattr(self, method)(self.extend(request, query))
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 466, in inner
    return entry(_self, **inner_kwargs)
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/ccxt/binance.py", line 2702, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 487, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 608, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/ccxt/binance.py", line 2696, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions, error, feedback)
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 505, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.OrderNotFound: binance {"code":-2013,"msg":"Order does not exist."}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/freqtrade1/freqtrade/exchange/common.py", line 136, in wrapper
    return f(*args, **kwargs)
  File "/root/freqtrade1/freqtrade/exchange/exchange.py", line 1129, in fetch_order
    f'Order not found (pair: {pair} id: {order_id}). Message: {e}') from e
freqtrade.exceptions.RetryableOrderError: Order not found (pair: CELR/BTC id: 38765245). Message: binance {"code":-2013,"msg":"Order does not exist."}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 592, in fetch
    response.raise_for_status()
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order?timestamp=1614529633191&recvWindow=5000&symbol=CELRBTC&orderId=38765245&signature=9d4c8e17be1f829a9059a0ffafab87719734e9ec50961191e409c3a92fda94e7

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/freqtrade1/freqtrade/exchange/exchange.py", line 1126, in fetch_order
    return self._api.fetch_order(order_id, pair)
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/ccxt/binance.py", line 1901, in fetch_order
    response = getattr(self, method)(self.extend(request, query))
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 466, in inner
    return entry(_self, **inner_kwargs)
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/ccxt/binance.py", line 2702, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 487, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 608, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/ccxt/binance.py", line 2696, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions, error, feedback)
  File "/root/freqtrade1/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 505, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.OrderNotFound: binance {"code":-2013,"msg":"Order does not exist."}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/freqtrade1/freqtrade/freqtradebot.py", line 969, in check_handle_timedout
    order = self.exchange.fetch_order(trade.open_order_id, trade.pair)
  File "/root/freqtrade1/freqtrade/exchange/common.py", line 148, in wrapper
    return wrapper(*args, **kwargs)
  File "/root/freqtrade1/freqtrade/exchange/common.py", line 148, in wrapper
    return wrapper(*args, **kwargs)
  File "/root/freqtrade1/freqtrade/exchange/common.py", line 148, in wrapper
    return wrapper(*args, **kwargs)
  [Previous line repeated 2 more times]
  File "/root/freqtrade1/freqtrade/exchange/common.py", line 151, in wrapper
    raise ex
  File "/root/freqtrade1/freqtrade/exchange/common.py", line 136, in wrapper
    return f(*args, **kwargs)
  File "/root/freqtrade1/freqtrade/exchange/exchange.py", line 1129, in fetch_order
    f'Order not found (pair: {pair} id: {order_id}). Message: {e}') from e
freqtrade.exceptions.RetryableOrderError: Order not found (pair: CELR/BTC id: 38765245). Message: binance {"code":-2013,"msg":"Order does not exist."}
  ```

**Comment by xmatthias** [comment]
well, it's the binance API that's to blame - there's not much we can do in this case (not without sacrificing other important functionality).

It's been discussed in multiple previous issues, too

basically, you place an order to binance - and binance's own "fetch_order" does not find the same order for multiple seconds (~50 seconds in your case, but it can be much worse i fear).

The problem is, without the response from the API, freqtrade will have no idea what the status of this order is.
Is it filled? cancelled (by the user ont he exchange)? or did the exchange even accept it properly?

The only "workaround" would be to take certain assumptions about an order status (which we do - as we'll keep assuming the order is unfilled).

The order will usually show up after a few cycles / minutes (obviously it'll slow the bot down).
Now unfortunately, the stacktrace is rather long (because it's an exception within an exception handler within an exception handler (part of the retry mechanism) - but it's not something that'll break the bot's operations.


unfortunately, this is quite common in high volume times on binance - and binance itself keeps stating that it's by design, and not a bug.
to me personally, it's a bug that might be sueable with enough lawsuit willpower - as the exchange reports false information via the API ... but i'm not legally interrested enough (nor rich enough) to try this out in court.

I've asked them in their issues - and ultimately, they just closed it down with no further comment - so for me, this is something we'll have to accept, or move to another exchange.

**Comment by aristosv** [comment]
thanks for the clarification
