### ISSUE TITLE
Bot crashes when Binance API is in maintenance or not responding

### ISSUE THREAD

**Issue by Th0masL** [freqtrade/freqtrade#4491]
## Describe your environment

  * Operating system: Docker
  * Python Version: 3.9.2
  * CCXT version: 1.42.45
  * Freqtrade Version: 2021.2

## Describe the problem:

It looks like the FreqTrade process crashes when the Binance API stops responding (due to a maintenance, for example).

### Steps to reproduce:

  1. Start FreqTrade
  2. Wait for a Binance Maintenance/outage
  3. Watch the process crash
  
  Note :
  - I was thinking that it could be possible to reproduce the problem by adding a fake DNS entry in the host file, like `127.0.0.1 api.binance.com`, to break the connectivity, but it seems like it's not crashing all the time, so I'm not sure how easily we can reproduce the exact scenario that just happened to me today.
  - According to the log, it's possible that the problem only happens with the `freqtrade.commands.trade_commands` method/function, so that's where we should put our focus on I guess.
  
### Observed Results:

  * What happened?
  The bot crashed
  * What did you expect to happen?
  The bot waits and retry later

### Relevant code exceptions or logs

  ```
2021-03-06 02:19:44,489 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2021-03-06 02:19:46,481 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2021-03-06 02:19:56,509 - freqtrade.exchange.common - WARNING - get_balances() returned exception: "Could not get balance due to RequestTimeout. Message: binance GET https://api.binance.com/api/v3/account?timestamp=1614997186498&recvWindow=5000&signature=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
2021-03-06 02:19:56,510 - freqtrade.exchange.common - WARNING - retrying get_balances() still for 4 times
2021-03-06 02:20:06,660 - freqtrade.exchange.common - WARNING - get_balances() returned exception: "Could not get balance due to RequestTimeout. Message: binance GET https://api.binance.com/api/v3/account?timestamp=1614997196510&recvWindow=5000&signature=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
2021-03-06 02:20:06,661 - freqtrade.exchange.common - WARNING - retrying get_balances() still for 3 times
2021-03-06 02:20:16,812 - freqtrade.exchange.common - WARNING - get_balances() returned exception: "Could not get balance due to RequestTimeout. Message: binance GET https://api.binance.com/api/v3/account?timestamp=1614997206662&recvWindow=5000&signature=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
2021-03-06 02:20:16,813 - freqtrade.exchange.common - WARNING - retrying get_balances() still for 2 times
2021-03-06 02:20:26,964 - freqtrade.exchange.common - WARNING - get_balances() returned exception: "Could not get balance due to RequestTimeout. Message: binance GET https://api.binance.com/api/v3/account?timestamp=1614997216813&recvWindow=5000&signature=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
2021-03-06 02:20:26,965 - freqtrade.exchange.common - WARNING - retrying get_balances() still for 1 times
2021-03-06 02:20:37,120 - freqtrade.exchange.common - WARNING - get_balances() returned exception: "Could not get balance due to RequestTimeout. Message: binance GET https://api.binance.com/api/v3/account?timestamp=1614997226966&recvWindow=5000&signature=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
2021-03-06 02:20:37,121 - freqtrade.exchange.common - WARNING - Giving up retrying: get_balances()
2021-03-06 02:20:37,122 - freqtrade.commands.trade_commands - ERROR - Could not get balance due to RequestTimeout. Message: binance GET https://api.binance.com/api/v3/account?timestamp=1614997226966&recvWindow=5000&signature=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
2021-03-06 02:20:37,123 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/root/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/root/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.9/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/local/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
  ```

It's possible to query the Binance API status using the endpoint `https://api.binance.com/wapi/v3/systemStatus.html`, and the response during a maintenance is as follow :
```
curl -s https://api.binance.com/wapi/v3/systemStatus.html | jq .
{
  "msg": "system_maintenance",
  "status": 1
}
```

I can try to investigate to prevent this crash to happen.

I guess using a `try` + `except` somewhere in the `freqtrade.commands.trade_commands` method/function would be the correct way to go.

Any other suggestion/remarks ?

**Comment by aristosv** [comment]
I suspect this is relevant. If not, I'll raise another issue.

```
2021-03-06 06:42:08,582 - freqtrade.data.converter - INFO - Missing data fillup for NEO/USDT: before: 999 - after: 1017
2021-03-06 06:42:08,616 - freqtrade.data.converter - INFO - Missing data fillup for TWT/USDT: before: 999 - after: 1017
2021-03-06 06:42:08,655 - freqtrade.data.converter - INFO - Missing data fillup for MANA/USDT: before: 999 - after: 1017
2021-03-06 06:42:08,691 - freqtrade.data.converter - INFO - Missing data fillup for WAVES/USDT: before: 999 - after: 1017
2021-03-06 06:42:08,730 - freqtrade.data.converter - INFO - Missing data fillup for TRB/USDT: before: 999 - after: 1017
2021-03-06 06:42:08,762 - freqtrade.data.converter - INFO - Missing data fillup for COTI/USDT: before: 999 - after: 1017
2021-03-06 06:42:08,801 - freqtrade.data.converter - INFO - Missing data fillup for PNT/USDT: before: 999 - after: 1017
2021-03-06 06:42:08,877 - numexpr.utils - INFO - NumExpr defaulting to 1 threads.
2021-03-06 06:42:12,726 - freqtrade.commands.trade_commands - ERROR - float division by zero
2021-03-06 06:42:12,726 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/root/freqtrade_USDT/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker.run()
  File "/root/freqtrade_USDT/freqtrade/worker.py", line 74, in run
    state = self._worker(old_state=state)
  File "/root/freqtrade_USDT/freqtrade/worker.py", line 111, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
  File "/root/freqtrade_USDT/freqtrade/worker.py", line 132, in _throttle
    result = func(*args, **kwargs)
  File "/root/freqtrade_USDT/freqtrade/worker.py", line 145, in _process_running
    self.freqtrade.process()
  File "/root/freqtrade_USDT/freqtrade/freqtradebot.py", line 184, in process
    self.exit_positions(trades)
  File "/root/freqtrade_USDT/freqtrade/freqtradebot.py", line 693, in exit_positions
    if trade.open_order_id is None and trade.is_open and self.handle_trade(trade):
  File "/root/freqtrade_USDT/freqtrade/freqtradebot.py", line 799, in handle_trade
    if self._check_and_execute_sell(trade, sell_rate, buy, sell):
  File "/root/freqtrade_USDT/freqtrade/freqtradebot.py", line 936, in _check_and_execute_sell
    force_stoploss=self.edge.stoploss(trade.pair) if self.edge else 0
  File "/root/freqtrade_USDT/freqtrade/strategy/interface.py", line 514, in should_sell
    current_profit = trade.calc_profit_ratio(current_rate)
  File "/root/freqtrade_USDT/freqtrade/persistence/models.py", line 554, in calc_profit_ratio
    profit_ratio = (close_trade_value / self.open_trade_value) - 1
ZeroDivisionError: float division by zero
2021-03-06 06:42:12,728 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2021-03-06 06:42:12,728 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2021-03-06 06:42:12,767 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2021-03-06 06:42:12,771 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': warning, 'status': "5 open trades active.\n\nHandle these trades manually on Binance, or '/start' the bot again and use '/stopbuy' to handle open trades gracefully. \n"}
2021-03-06 06:42:12,808 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
2021-03-06 06:42:12,809 - apscheduler.scheduler - INFO - Scheduler has been shut down
```

**Comment by xmatthias** [comment]
i suspect this will only happen if the downtime is while you're starting the bot (which honestly, i'm fine with - as you should simply retry a bit later).
Now the failure could be gracefull - but supporting a startup while the exchange is down is not something that will be possible easily.

once the bot is running, it'll not crash - it didn't crash during the last downtimes, and it won't crash in the next .

**Comment by Th0masL** [comment]
Thanks for your feedback guys!

Do you think it could also happen if the bot is already running and the configuration gets reloaded during the downtime ?

I'm reloading the bot every hour to be able to reload the new values that I've added to pairs_whitelist, so I'm pretty sure that in my case the bot will most likely end up reloading every time Binance has a 1 hour long maintenance 😆

**Comment by xmatthias** [comment]
yes, also reload will (most likely) cause this.
and most (scheduled) downtimes are longer than 1 hour - and even if not, you can be sure that it'll reload while they're down ... :laughing:

**Comment by Th0masL** [comment]
Ok, thanks ! I will find a way to only reboot the bot when there's no maintenance going on :+1: :smile:

**Comment by xmatthias** [comment]
well the "reboot" case is a special one that will be difficult to handle (tough to test - and there's a TON of startup data we need).

i don't think it'll be a problem if you're doing a "regular" startup, as then you're "there, watching it fail" ... kindof
