### ISSUE TITLE
AttributeError: type object 'PairLocks' has no attribute 'get_pair_longest_lock'

### ISSUE THREAD

**Issue by MrKrautee** [freqtrade/freqtrade#4505]
## Describe your environment

  * Linux 5127ac8b2baf 5.11.2-zen1-1-zen #1 ZEN SMP PREEMPT Fri, 26 Feb 2021 18:26:44 +0000 x86_64 GNU/Linux
  * Python 3.8.3
  * ccxt==1.42.19
  * freqtrade 2021.2
  

## Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

  1. dry run
  2. strategy sells or buys by sell or buy signal
  
### Observed Results:

  * What happened?
  after the bot sells or buys a trade (dry mode), the following exception occurs.
  * What did you expect to happen?
  no exception

### Relevant code exceptions or logs

2021-03-08 11:51:53,449 - freqtrade.rpc.telegram - INFO - Executing handler: _help for chat_id: 351730154
2021-03-08 11:51:55,449 - freqtrade.rpc.telegram - INFO - Executing handler: _version for chat_id: 351730154
2021-03-08 11:54:11,507 - freqtrade.freqtradebot - INFO - Cancelling current stoploss on exchange for pair LTO/BTC (orderid:dry_run_sell_1615204063.447563) in order to add another one ...
2021-03-08 11:54:11,879 - freqtrade.freqtradebot - INFO - Executing Sell for LTO/BTC. Reason: trailing_stop_loss
2021-03-08 11:54:12,012 - freqtrade.wallets - INFO - Wallets synced.
2021-03-08 11:54:12,018 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=8, pair=LTO/BTC, amount=712.87128713, open_rate=0.00001111, open_since=2021-03-08 10:28:56)
2021-03-08 11:54:12,019 - freqtrade.freqtradebot - INFO - Applying fee on amount for Trade(id=8, pair=LTO/BTC, amount=712.87128713, open_rate=0.00001111, open_since=2021-03-08 10:28:56) failed: myTrade-Dict empty found
2021-03-08 11:54:12,020 - freqtrade.persistence.models - INFO - Updating trade (id=8) ...
2021-03-08 11:54:12,020 - freqtrade.persistence.models - INFO - MARKET_SELL has been fulfilled for Trade(id=8, pair=LTO/BTC, amount=712.87128713, open_rate=0.00001111, open_since=2021-03-08 10:28:56).
2021-03-08 11:54:12,021 - freqtrade.persistence.models - INFO - Marking Trade(id=8, pair=LTO/BTC, amount=712.87128713, open_rate=0.00001111, open_since=closed) as closed as the trade is fulfilled and found no open orders for it.
2021-03-08 11:54:12,121 - freqtrade.wallets - INFO - Wallets synced.
2021-03-08 11:54:12,200 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': sell, 'trade_id': 8, 'exchange': 'Binance', 'pair': 'LTO/BTC', 'gain': 'profit', 'limit': 1.16798832e-05, 'order_type': 'market', 'amount': 712.871287128713, 'open_rate': 1.111e-05, 'current_rate': 1.166e-05, 'profit_amount': 0.00039001, 'profit_ratio': 0.04919413, 'sell_reason': 'trailing_stop_loss', 'open_date': datetime.datetime(2021, 3, 8, 10, 28, 56, 454225), 'close_date': datetime.datetime(2021, 3, 8, 11, 54, 12, 21161), 'stake_currency': 'BTC', 'fiat_currency': 'EUR'}
2021-03-08 11:54:13,746 - freqtrade.wallets - INFO - Wallets synced.
2021-03-08 11:54:13,906 - freqtrade.commands.trade_commands - ERROR - type object 'PairLocks' has no attribute 'get_pair_longest_lock'
2021-03-08 11:54:13,906 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker.run()
  File "/freqtrade/freqtrade/worker.py", line 74, in run
    state = self._worker(old_state=state)
  File "/freqtrade/freqtrade/worker.py", line 111, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
  File "/freqtrade/freqtrade/worker.py", line 132, in _throttle
    result = func(*args, **kwargs)
  File "/freqtrade/freqtrade/worker.py", line 145, in _process_running
    self.freqtrade.process()
  File "/freqtrade/freqtrade/freqtradebot.py", line 188, in process
    self.enter_positions()
  File "/freqtrade/freqtrade/freqtradebot.py", line 388, in enter_positions
    trades_created += self.create_trade(pair)
  File "/freqtrade/freqtrade/freqtradebot.py", line 457, in create_trade
    lock = PairLocks.get_pair_longest_lock(pair, nowtime)
AttributeError: type object 'PairLocks' has no attribute 'get_pair_longest_lock'
2021-03-08 11:54:13,909 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2021-03-08 11:54:13,909 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}

**Comment by MrKrautee** [comment]
My sources seem to be messed up due to merging errors. sorry
