### ISSUE TITLE
whenever i try using my own sharpe loss ratio formular i get an errror please help me out KEY ERROR PROFIT PERCENT

### ISSUE THREAD

**Issue by Renaenys** [freqtrade/freqtrade#4514]
## Describe your environment

  * Operating system: ___ UBUNTU
  * Python Version: _____python 3.6.9
  * CCXT version: _____ (ccxt==1.37.83)
  * Freqtrade Version: freqtrade 2021.2
  
## Your question

```
from datetime import datetime

from pandas import DataFrame, to_datetime
import numpy as np
from freqtrade.optimize.hyperopt import IHyperOptLoss


class SharpeHyperOptLoss2(IHyperOptLoss):
    """
    Defines the loss function for hyperopt.

    This implementation uses the Sharpe Ratio calculation.
    """

    @staticmethod
    def hyperopt_loss_function(results: DataFrame, trade_count: int,
                               min_date: datetime, max_date: datetime,
                               *args, **kwargs) -> float:
        """
        Objective function, returns smaller number for more optimal results.

        Uses Sharpe Ratio calculation.
        """
        # adding slippage of 0.1% per trade
        results["profit_percent"]  = results["profit_percent"]  - 0.001
        results["close_time_h"] = to_datetime(results["close_date"], unit="s")
        results = results.set_index("close_time_h")
        results = results.resample("D").sum()

        total_profit_per_day = results.profit_percent
        days_period = (max_date - min_date).days

        average_daily_return = total_profit_per_day.sum() / days_period

        if (np.std(total_profit_per_day ) != 0.):
            sharpe_ratio = (average_daily_return / np.std(total_profit_per_day )) * np.sqrt(365)
        else:
            # Define high (negative) sharpe ratio to be clear that this is NOT optimal.
            sharpe_ratio = -20.

        return -sharpe_ratio
```

having this error with
```
Traceback (most recent call last):
  File "/root/.local/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'profit_percent'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.local/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker
    r = call_item()
  File "/root/.local/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/root/.local/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/root/.local/lib/python3.9/site-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/root/.local/lib/python3.9/site-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/root/.local/lib/python3.9/site-packages/joblib/externals/loky/cloudpickle_wrapper.py", line 38, in __call__
    return self._obj(*args, **kwargs)
  File "/freqtrade/freqtrade/optimize/hyperopt.py", line 548, in generate_optimizer
    return self._get_results_dict(backtesting_results, min_date, max_date,
  File "/freqtrade/freqtrade/optimize/hyperopt.py", line 566, in _get_results_dict
    loss = self.calculate_loss(results=backtesting_results, trade_count=trade_count,
  File "/freqtrade/user_data/hyperopts/hyperopt_loss.py", line 31, in hyperopt_loss_function
    results["profit_percent"]  = results["profit_percent"]   - 0.001
  File "/root/.local/lib/python3.9/site-packages/pandas/core/frame.py", line 3024, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/root/.local/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: 'profit_percent'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 83, in start_hyperopt
    hyperopt.start()
  File "/freqtrade/freqtrade/optimize/hyperopt.py", line 718, in start
    f_val = self.run_optimizer_parallel(parallel, asked, i)
  File "/freqtrade/freqtrade/optimize/hyperopt.py", line 622, in run_optimizer_parallel
    return parallel(delayed(
  File "/root/.local/lib/python3.9/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/root/.local/lib/python3.9/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/root/.local/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 440, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
KeyError: 'profit_percent'
```

**Comment by xmatthias** [comment]
the [hyperopt advanced docs](https://www.freqtrade.io/en/latest/advanced-hyperopt/#creating-and-using-a-custom-loss-function) describe which fields are available, and `profit_percent` is no longer one of them.
you're probably looking for `profit_ratio`.

**Comment by Renaenys** [comment]
Omg thanks x matthias. <3

**Comment by joe-nano** [comment]
> the [hyperopt advanced docs](https://www.freqtrade.io/en/latest/advanced-hyperopt/#creating-and-using-a-custom-loss-function) describe which fields are available, and `profit_percent` is no longer one of them.
> you're probably looking for `profit_ratio`.

Hello @xmatthias,

results["close_time_h"] = to_datetime(results["close_date"], unit="s")

Assumedly you can change that unit parameter from "s" to "h"?

Does that need to change?

**Comment by xmatthias** [comment]
This was never correct -  neither was. 

The column contains datetime objects - so i think providing unit will always fail.
