### ISSUE TITLE
Can't install freqtrade on my Raspberrypi 4

### ISSUE THREAD

**Issue by MrKim42** [freqtrade/freqtrade#4518]
Hello everyone, 

So i've been crushing my head over this one for the whole day. I tried to install freqtrade, delete it, reinstall it... An whatever I did, I couldn't manage to get freqtrade running. 

I arrive until the final message "Run the bot" 
```
Installing collected packages: freqtrade
  Running setup.py develop for freqtrade
Successfully installed freqtrade
pip install completed

-------------------------
Please use 'freqtrade new-config -c config.json' to generate a new configuration file.
-------------------------
-------------------------
Run the bot !
-------------------------
You can now use the bot by executing 'source .env/bin/activate; freqtrade <subcommand>'.
You can see the list of available bot sub-commands by executing 'source .env/bin/activate; freqtrade --help'.
You verify that freqtrade is installed successfully by running 'source .env/bin/activate; freqtrade --version'.
```

But after that, when I try to run the bot: 

```
pi@raspberrypi:~ $ source .env/bin/activate; freqtrade 
**bash: freqtrade: command not found**
(.env) pi@raspberrypi:~ $ 
```

Do you know what is wrong with the set? 

Thanks in advance for your help !

**Comment by samgermain** [comment]
you could try `python3 ./freqtrade/main.py`

**Comment by MrKim42** [comment]
> you could try `python3 ./freqtrade/main.py`

Thank for your answer, but it didn't help, or maybe i'm doing something wrong... 

```
pi@raspberrypi:~ $ source .env/bin/activate; freqtrade
bash: freqtrade: command not found
(.env) pi@raspberrypi:~ $ source .env/bin/activate
(.env) pi@raspberrypi:~ $ python3 ./freqtrade/main.py
python3: can't open file './freqtrade/main.py': [Errno 2] No such file or directory
(.env) pi@raspberrypi:~ $ python3 .freqtrade/freqtrade/main.py
python3: can't open file '.freqtrade/freqtrade/main.py': [Errno 2] No such file or directory
(.env) pi@raspberrypi:~ $ python3 /home/pi/freqtrade/freqtrade/main.py
Traceback (most recent call last):
  File "/home/pi/freqtrade/freqtrade/main.py", line 15, in <module>
    from freqtrade.commands import Arguments
ModuleNotFoundError: No module named 'freqtrade'
(.env) pi@raspberrypi:~ $ 
```
**First:** 
I try with what you suggested: but it told me there is no file in the directory. 

**Second:** 
I recorgnised the main.py file is located in /freqtrade/freqtrade/main.py. 
but again, terminal told me there is no file in the directory. 

**Finally:** 
I tried to paste the complete path, it says that module not found.

**Comment by xmatthias** [comment]
try (with activated virtual environment):
`pip install -e .` ... then freqtrade should be available.

**Comment by MrKim42** [comment]
> try (with activated virtual environment):
> `pip install -e .` ... then freqtrade should be available.

Thanks for your reply, I already tried that and If I recall correctly, terminal gave me an Error02: setup.py something like that. 
I tried to delete everything to start again. 
I'll let you. know if I encounter another issue.

**Comment by MrKim42** [comment]
Ok so I have this **big error** coming at the 
**Test one:** `python3 -m pip install -e .`
**Test two:** `pip install -e . `

--> With both commands, I have this big issue. 

```
(.env) pi@raspberrypi:~/freqtrade $ python3 -m pip install -e .


Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Obtaining file:///home/pi/freqtrade
    ERROR: Command errored out with exit status 1:
     command: /home/pi/.env/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/pi/freqtrade/setup.py'"'"'; __file__='"'"'/home/pi/freqtrade/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-6hbqc0q9
         cwd: /home/pi/freqtrade/
    Complete output (97 lines):
    Processing numpy/random/_bounded_integers.pxd.in
    Processing numpy/random/_bounded_integers.pyx.in
    Traceback (most recent call last):
      File "/tmp/easy_install-0uetwd9r/numpy-1.20.1/tools/cythonize.py", line 59, in process_pyx
        from Cython.Compiler.Version import version as cython_version
    ModuleNotFoundError: No module named 'Cython'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/easy_install-0uetwd9r/numpy-1.20.1/tools/cythonize.py", line 235, in <module>
        main()
      File "/tmp/easy_install-0uetwd9r/numpy-1.20.1/tools/cythonize.py", line 231, in main
        find_process_files(root_dir)
      File "/tmp/easy_install-0uetwd9r/numpy-1.20.1/tools/cythonize.py", line 222, in find_process_files
        process(root_dir, fromfile, tofile, function, hash_db)
      File "/tmp/easy_install-0uetwd9r/numpy-1.20.1/tools/cythonize.py", line 188, in process
        processor_function(fromfile, tofile)
      File "/tmp/easy_install-0uetwd9r/numpy-1.20.1/tools/cythonize.py", line 91, in process_tempita_pyx
        process_pyx(pyxfile, tofile)
      File "/tmp/easy_install-0uetwd9r/numpy-1.20.1/tools/cythonize.py", line 64, in process_pyx
        raise OSError('Cython needs to be installed in Python as a module')
    OSError: Cython needs to be installed in Python as a module
    Cythonizing sources
    Running from numpy source directory.
    /tmp/easy_install-0uetwd9r/numpy-1.20.1/setup.py:485: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      run_build = parse_setuppy_commands()
    Traceback (most recent call last):
      File "/home/pi/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/home/pi/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/home/pi/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/home/pi/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-0uetwd9r/numpy-1.20.1/setup.py", line 513, in <module>
      File "/tmp/easy_install-0uetwd9r/numpy-1.20.1/setup.py", line 493, in setup_package
      File "/tmp/easy_install-0uetwd9r/numpy-1.20.1/setup.py", line 290, in generate_cython
    RuntimeError: Running cythonize failed!
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/pi/freqtrade/setup.py", line 117, in <module>
        'Topic :: Office/Business :: Financial :: Investment',
      File "/home/pi/.env/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/home/pi/.env/lib/python3.7/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/home/pi/.env/lib/python3.7/site-packages/setuptools/dist.py", line 724, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/pi/.env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
        replace_conflicting=replace_conflicting
      File "/home/pi/.env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/home/pi/.env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/home/pi/.env/lib/python3.7/site-packages/setuptools/dist.py", line 791, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/pi/.env/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 704, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/home/pi/.env/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 730, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/home/pi/.env/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 915, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/home/pi/.env/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 1183, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/home/pi/.env/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 1169, in run_setup
        run_setup(setup_script, args)
      File "/home/pi/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/pi/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/pi/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/home/pi/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/home/pi/.env/lib/python3.7/site-packages/setuptools/_vendor/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/home/pi/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/home/pi/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/home/pi/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/home/pi/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-0uetwd9r/numpy-1.20.1/setup.py", line 513, in <module>
      File "/tmp/easy_install-0uetwd9r/numpy-1.20.1/setup.py", line 493, in setup_package
      File "/tmp/easy_install-0uetwd9r/numpy-1.20.1/setup.py", line 290, in generate_cython
    RuntimeError: Running cythonize failed!
    ----------------------------------------
WARNING: Discarding file:///home/pi/freqtrade. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored o
```

**Comment by MrKim42** [comment]
With the "classic installation" 

`git clone git@github.com:freqtrade/freqtrade.git
cd freqtrade
git checkout develop
./setup.sh --install`

I have this error after 10 min. 


`Collecting tables==3.6.1
  Downloading tables-3.6.1.tar.gz (4.6 MB)
     |████████████████████████████████| 4.6 MB 9.9 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /home/pi/freqtrade/.env/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qwg3wvnu/tables_637a7c73928d4692a46f5b42f47adea0/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qwg3wvnu/tables_637a7c73928d4692a46f5b42f47adea0/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-nsyjuyqb
         cwd: /tmp/pip-install-qwg3wvnu/tables_637a7c73928d4692a46f5b42f47adea0/
    Complete output (12 lines):
    /tmp/H5close7acx5622.c: In function ‘main’:
    /tmp/H5close7acx5622.c:2:5: warning: implicit declaration of function ‘H5close’ [-Wimplicit-function-declaration]
         H5close();
         ^~~~~~~
    /usr/bin/ld: cannot find -lhdf5
    collect2: error: ld returned 1 exit status
    * Using Python 3.8.0 (default, Mar 11 2021, 13:36:45)
    * USE_PKGCONFIG: True
    .. ERROR:: Could not find a local HDF5 installation.
       You may need to explicitly state where your local HDF5 headers and
       library can be found by setting the ``HDF5_DIR`` environment
       variable or by using the ``--hdf5`` command-line option.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/2b/32/847ee3f521aae6a0be380d923a736162d698586f444df1ac24b98c65025c/tables-3.6.1.tar.gz#sha256=49a972b8a7c27a8a173aeb05f67acb45fe608b64cd8e9fa667c0962a60b71b49 (from https://pypi.org/simple/tables/) (requires-python:>=3.5). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement tables==3.6.1
ERROR: No matching distribution found for tables==3.6.1
Failed installing dependencies
`

**Comment by xmatthias** [comment]
are you using arm64? 

otherwise, installations should happen from piwheels - which will not require hdf5 compile dependencies.

**Comment by MrKim42** [comment]
> are you using arm64?
> 
> otherwise, installations should happen from piwheels - which will not require hdf5 compile dependencies.

No I have the 32bit version.

**Comment by xmatthias** [comment]
on a normal raspberry, you should have python 3.7, not 3.8 (system python)

i'd recommend to use python 3.7 - otherwise you'll need to hunt down all install dependencies (like the ones for tables, but not only) - and the installation will take forever.

with python 3.7, you can rely on "piewheels.org" wheels, which will speed up installation a lot.

An alternative will always be the docker image too, which will simplify installation as well.

**Comment by MrKim42** [comment]
> on a normal raspberry, you should have python 3.7, not 3.8 (system python)
> 
> i'd recommend to use python 3.7 - otherwise you'll need to hunt down all install dependencies (like the ones for tables, but not only) - and the installation will take forever.
> 
> with python 3.7, you can rely on "piewheels.org" wheels, which will speed up installation a lot.
> 
> An alternative will always be the docker image too, which will simplify installation as well.

I'm trying via the docker version now. And I have a problem with the docker compose... 
It's been 2 entire days I try to install, I think I need a break ... 

this is the issue I. have now with docker-compose: 
```

`pi@raspberrypi:~ $ cd ft_userdata
pi@raspberrypi:~/ft_userdata $ docker-compose pull
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/home/pi/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/pi/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/pi/.local/lib/python3.7/site-packages/urllib3/util/retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/pi/.local/lib/python3.7/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/home/pi/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/home/pi/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/docker/api/client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/home/pi/.local/lib/python3.7/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/home/pi/.local/lib/python3.7/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/home/pi/.local/lib/python3.7/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/bin/docker-compose", line 8, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.7/site-packages/compose/cli/main.py", line 80, in main
    command_func()
  File "/home/pi/.local/lib/python3.7/site-packages/compose/cli/main.py", line 189, in perform_command
    project = project_from_options('.', options)
  File "/home/pi/.local/lib/python3.7/site-packages/compose/cli/command.py", line 70, in project_from_options
    enabled_profiles=get_profiles_from_options(options, environment)
  File "/home/pi/.local/lib/python3.7/site-packages/compose/cli/command.py", line 153, in get_project
    verbose=verbose, version=api_version, context=context, environment=environment
  File "/home/pi/.local/lib/python3.7/site-packages/compose/cli/docker_client.py", line 43, in get_client
    environment=environment, tls_version=get_tls_version(environment)
  File "/home/pi/.local/lib/python3.7/site-packages/compose/cli/docker_client.py", line 170, in docker_client
    client = APIClient(use_ssh_client=not use_paramiko_ssh, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/home/pi/.local/lib/python3.7/site-packages/docker/api/client.py", line 222, in _retrieve_server_version
    'Error while fetching server API version: {0}'.format(e)
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))
`


```

**Comment by xmatthias** [comment]
either your docker daemon is not running - or your user is not in the docker group (`usermod -aG docker pi` - then logout and log back in).

**Comment by MrKim42** [comment]
now again it 

it says that the command is not found... 

```
pi@raspberrypi:~ $ usermod -aG docker pi
usermod: Permission denied.
usermod: cannot lock /etc/passwd; try again later.

pi@raspberrypi:~ $ sudo usermod -aG docker pi
pi@raspberrypi:~ $ mkdir ft_userdata
mkdir: cannot create directory ‘ft_userdata’: File exists

pi@raspberrypi:~ $ cd ft_userdata/
pi@raspberrypi:~/ft_userdata $ curl https://raw.githubusercontent.com/freqtrade/freqtrade/stable/docker-compose.yml -o docker-compose.yml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   954  100   954    0     0   3613      0 --:--:-- --:--:-- --:--:--  3627

pi@raspberrypi:~/ft_userdata $ docker-compose pull
/usr/local/bin/docker-compose: line 1: Not: command not found
pi@raspberrypi:~/ft_userdata $ 
```

**Comment by xmatthias** [comment]
based on the internet, it sounds like your docker-compose installation is invalid.

simply use google and search for `/usr/local/bin/docker-compose: line 1: Not: command not found` ... it'll give you a lot of solution psosibilities...

**Comment by MrKim42** [comment]
> based on the internet, it sounds like your docker-compose installation is invalid.
> 
> simply use google and search for `/usr/local/bin/docker-compose: line 1: Not: command not found` ... it'll give you a lot of solution psosibilities...

Thanks for your reply and the time you took to answer me. 

I did already googled that. 
I have the feeling that I tried eveything, and installed again and it's just not working. 

I managed to install freqtrade on my mac, but I can't figure out how to install in on my Raspberry pi 4... 
I think I'll just give up for now...

**Comment by xmatthias** [comment]
based on the first resut i found - it sounds like your compose file is empty (you can look at that for example with `cat /usr/local/bin/docker-compose`).
if that's the case - just delete that file, and try installation again ... 

installing on raspbian 32bit is quite easy (and also supported with the setup.sh script) - but it assumes the default configuration for a raspberry (python 3.7, 32bit system).

i actually wonder how you got python 3.8 on there - did you explicitly install that somehow?

**Comment by MrKim42** [comment]
If someone also bought a RaspberryPi to install freqtrade and has a lot of difficulities to get it installed, here is how i managed to to it. step by step. 

Here is what I tried: 

**1. Reinstall a new Image**
Reinstall a new image on my Raspberrypi 4. I installed the desktop software from their website: https://www.raspberrypi.org/software/raspberry-pi-desktop/

**2. Raspberry automatic update** 
Connect the Raspberry to the internet and let him make the Update for 15 min. 

**3. Python 3.7 Check** 
Checked my Python version to be 3.7

**4. pip already installed** 
Pip should already be installed 

**5. Install Git**
Installed Git:` `$ sudo apt install git-all``
You will be asked if you want to continue, write Y.

**6. I installed Virtualenv:** 
```
`python -m pip install --user virtualenv
python -m virtualenv --help`
```
**7. I installed TA-Lib**

```
wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
tar xvzf ta-lib-0.4.0-src.tar.gz
cd ta-lib
sed -i.bak "s|0.00000001|0.000000000000000001 |g" src/ta_func/ta_utility.h
./configure --prefix=/usr/local
make
sudo make install
cd ..
```
rm -rf ./ta-lib*



**8. Created the virtualenv**
```

# create virtualenv in directory /freqtrade/.env
python3 -m venv .env

# run virtualenv

source .env/bin/activate
```



**9. Installed Freqtrade. (Line per line)**
```

sudo apt-get install python3-venv libatlas-base-dev cmake

sudo echo "[global]\nextra-index-url=https://www.piwheels.org/simple" > tee /etc/pip.conf


git clone https://github.com/freqtrade/freqtrade.git
cd freqtrade

bash setup.sh -i
```
Reset Git Branch ? **Yes**
Do you want to install dependencies for dev [y/N]? **N**
Do you want to install plotting dependencies (plotly) [y/N]? **N**

I had a problem at the ta-lib. part.
So I tried installed Ta-Lib manually again 

**9.1. Ta lib install (bis)**
`pip install TA-Lib`

9.2. Tried again to install freqtrade.
`bash setup.sh -i`

Still have the same problem: 

```
   IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
    
    Importing the numpy C-extensions failed. This error can happen for
    many reasons, often due to issues with your setup or how NumPy was
    installed.
```

**10. II make sure that i'm in the virtualenv**

```
python3 -m venv .env
source .env/bin/activate
```

**11. Then I tried again to install the program:** 
```
python3 -m pip install --upgrade pip
python3 -m pip install -e .
```

Still got the same problem as before.

    
--> On the internet, they said to uninstall and reinstall numpy. 

**12. force reinstall of numpy**

` pip install --upgrade --force-reinstall numpy
`

--> Didn't solve the problem.

**13. I read in the issue, and a small file was causing the problem.**
Apparently there was also an issue with this:     Original error was: libf77blas.so.3: cannot open shared object file: No such file or directory
so on internet, they said:
 `sudo apt-get install libatlas-base-dev`

Now I did again the pip install -e . 

```
python3 -m pip install --upgrade pip
python3 -m pip install -e .
```

And it worked.



**NB: To run the bot, I have to run this:**

```
cd freqtrade
source .env/bin/activate; freqtrade
```

**Comment by xmatthias** [comment]
Glad you got it to work.

It doesn't really differ to the instruction in the documentation, which for rasperry says right at the beginning - `sudo apt-get install python3-venv libatlas-base-dev cmake`
so i think the only difference is that you made sure it's running python 3.7.
