### ISSUE TITLE
using pandas-ta throws an exception due to trade close_date having no timezone info

### ISSUE THREAD

**Issue by rokups** [freqtrade/freqtrade#4526]
## Describe your environment

  * Operating system: archlinux
  * Python Version: 3.9.2
  * CCXT version: 1.42.19
  * Freqtrade Version: 2021.2
  
## Describe the problem:

`TypeError` exception is raised when executing a backtest with a strategy using pandas-ta.

### Steps to reproduce:

Execute strategy with following:
```py
import pandas_ta as ta

# <...>

    def populate_indicators(self, df: DataFrame, metadata: dict) -> DataFrame:
        df['ema200'] = ta.ema(df['close'], length=200)
        df['ema500'] = ta.ema(df['close'], length=500)
        return df

    def populate_buy_trend(self, df: DataFrame, metadata: dict) -> DataFrame:
        df.loc[
            (
                    (df['ema200'] > df['ema500'])  # Long timeframe uptrend
            ),
            'buy'] = 1

        return df
```
  
### Relevant code exceptions or logs

```
Traceback (most recent call last):
  File "/home/rk/src/cryptoml/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/home/rk/src/cryptoml/freqtrade/commands/optimize_commands.py", line 50, in start_backtesting
    backtesting.start()
  File "/home/rk/src/cryptoml/freqtrade/optimize/backtesting.py", line 449, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
  File "/home/rk/src/cryptoml/freqtrade/optimize/backtesting.py", line 418, in backtest_one_strategy
    results = self.backtest(
  File "/home/rk/src/cryptoml/freqtrade/optimize/backtesting.py", line 388, in backtest
    return trade_list_to_dataframe(trades)
  File "/home/rk/src/cryptoml/freqtrade/data/btanalysis.py", line 233, in trade_list_to_dataframe
    df = pd.DataFrame.from_records([t.to_json() for t in trades], columns=BT_DATA_COLUMNS)
  File "/home/rk/src/cryptoml/freqtrade/data/btanalysis.py", line 233, in <listcomp>
    df = pd.DataFrame.from_records([t.to_json() for t in trades], columns=BT_DATA_COLUMNS)
  File "/home/rk/src/cryptoml/freqtrade/persistence/models.py", line 309, in to_json
    'trade_duration_s': (int((self.close_date - self.open_date).total_seconds())
  File "pandas/_libs/tslibs/timestamps.pyx", line 364, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Timestamp subtraction must have the same timezones or no timezones
```

This does not happen instantly, but only for some trades. This is how dates look when exception is thrown:

```
self.close_date = {datetime} 2021-03-12 11:09:27.043317
 day = {int} 12
 fold = {int} 0
 hour = {int} 11
 max = {datetime} 9999-12-31 23:59:59.999999
 microsecond = {int} 43317
 min = {datetime} 0001-01-01 00:00:00
 minute = {int} 9
 month = {int} 3
 resolution = {timedelta} 0:00:00.000001
 second = {int} 27
 tzinfo = {NoneType} None
 year = {int} 2021

self.open_date = {Timestamp} 2021-02-27 23:40:00+00:00
 asm8 = {datetime64} 2021-02-27T23:40:00.000000000
 day = {int} 27
 dayofweek = {int} 5
 dayofyear = {int} 58
 days_in_month = {int} 28
 daysinmonth = {int} 28
 fold = {int} 0
 freq = {NoneType} None
 freqstr = {NoneType} None
 hour = {int} 23
 is_leap_year = {bool} False
 is_month_end = {bool} False
 is_month_start = {bool} False
 is_quarter_end = {bool} False
 is_quarter_start = {bool} False
 is_year_end = {bool} False
 is_year_start = {bool} False
 max = {Timestamp} 2262-04-11 23:47:16.854775807
 microsecond = {int} 0
 min = {Timestamp} 1677-09-21 00:12:43.145225
 minute = {int} 40
 month = {int} 2
 nanosecond = {int} 0
 quarter = {int} 1
 resolution = {Timedelta} 0 days 00:00:00.000000001
 second = {int} 0
 tz = {UTC} UTC
 tzinfo = {UTC} UTC
 value = {int} 1614469200000000000
 week = {int} 8
 weekofyear = {int} 8
 year = {int} 2021
```

Edit:
This _seems_ to fix my issue.

```patch
diff --git a/freqtrade/optimize/backtesting.py b/freqtrade/optimize/backtesting.py
index 3186313e..c0135b4d 100644
--- a/freqtrade/optimize/backtesting.py
+++ b/freqtrade/optimize/backtesting.py
@@ -9,7 +9,7 @@ from copy import deepcopy
 from datetime import datetime, timedelta, timezone
 from typing import Any, Dict, List, Optional, Tuple
 
-from pandas import DataFrame
+from pandas import DataFrame, to_datetime
 
 from freqtrade.configuration import TimeRange, remove_credentials, validate_config_consistency
 from freqtrade.constants import DATETIME_PRINT_FORMAT
@@ -255,7 +255,7 @@ class Backtesting:
             trade_dur = int((sell_row[DATE_IDX] - trade.open_date).total_seconds() // 60)
             closerate = self._get_close_rate(sell_row, trade, sell, trade_dur)
 
-            trade.close_date = sell_row[DATE_IDX]
+            trade.close_date = to_datetime(sell_row[DATE_IDX], utc=True, infer_datetime_format=True)
             trade.sell_reason = sell.sell_type
             trade.close(closerate, show_msg=False)
             return trade
@@ -273,7 +273,7 @@ class Backtesting:
                 for trade in open_trades[pair]:
                     sell_row = data[pair][-1]
 
-                    trade.close_date = sell_row[DATE_IDX]
+                    trade.close_date = to_datetime(sell_row[DATE_IDX], utc=True, infer_datetime_format=True)
                     trade.sell_reason = SellType.FORCE_SELL
                     trade.close(sell_row[OPEN_IDX], show_msg=False)
                     trade.is_open = True
```

**Comment by xmatthias** [comment]
If this is everything of your strategy, then pandas-ta is messing with the timestamps of the dates in the dataframe.

Please report it as a bug there.

The proposed fix can have quite a huge performance impact, especially on strategies / backtests which generate a lot of trades.
I'm yet to see this happen when using ta-lib (or qtpylib) indicators - so i assume it's a bug in pandas-ta.

**Comment by rokups** [comment]
After further digging i realized problem is `dataframe.loc['sell'] = 0`. Apparently this is not a valid thing to do as it appends a new row with weird data. I picked it up from [here](https://github.com/freqtrade/freqtrade-strategies/blob/master/user_data/strategies/berlinguyinca/BinHV45.py#L56). So actual bug is in samples.

**Comment by xmatthias** [comment]
mmmmh, the correct syntax should be `dataframe.loc[:, 'sell'] = 0`.

it's still interresting, as i'm using that strategy myself for tests, and i've never come across this.
