### ISSUE TITLE
`TypeError: bad operand type for unary ~: 'float'` with strategy involving interval resampling on new coin pairs (LIT/BTC SFP/BTC and CAKE/BTC)

### ISSUE THREAD

**Issue by samgermain** [freqtrade/freqtrade#4533]
* Operating system: Debian GNU/Linux 10 (buster)
  * Python Version: Python 3.7.9
  * CCXT version: ccxt==1.42.19
  * Freqtrade Version: freqtrade develop-c600cc0
  
  -------------------
  
I noticed when running back-tests and using pairs for some new coins (LIT/BTC and SFP/BTC, CAKE/BTC), and using dates that predate when these pairs were launched on Binance,  I received the error below when running a modification of the BinHV27 strategy which included interval re-sampling. This error does not show up with all new coins though (DODO didn't produce it)

I removed these pairs and just won't use them for my back-testing, so I don't really need this solved. I thought it might be helpful information for anyone else who encounters the error.

```
Traceback (most recent call last):
  File "/home/sam/freqtrade-backtest_compound_speed/user_data/user_data/strategies/BinHV27_adjustement.py", line 122, in populate_buy_trend
    'buy'] = 1
  File "/home/sam/freqtrade-backtest_compound_speed/.env/lib/python3.7/site-packages/pandas/core/generic.py", line 1435, in __invert__
    new_data = self._mgr.apply(operator.invert)
  File "/home/sam/freqtrade-backtest_compound_speed/.env/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 425, in apply
    applied = b.apply(f, **kwargs)
  File "/home/sam/freqtrade-backtest_compound_speed/.env/lib/python3.7/site-packages/pandas/core/internals/blocks.py", line 378, in apply
    result = func(self.values, **kwargs)
TypeError: bad operand type for unary ~: 'float'
```

------------------

Here's the strategy I was running which causes this. 
The error does not happen with the regular BinHV27, but only happens when add interval re-sampling to the strategy

```
from freqtrade.strategy.interface import IStrategy
from typing import Dict, List
from functools import reduce
from pandas import DataFrame

import talib.abstract as ta
import freqtrade.vendor.qtpylib.indicators as qtpylib
from typing import Dict, List
from functools import reduce
from pandas import DataFrame, DatetimeIndex, merge

import talib.abstract as ta
import freqtrade.vendor.qtpylib.indicators as qtpylib
import numpy  # noqa
from technical.util import resample_to_interval, resampled_merge

class BinHV27_ADJ(IStrategy):
    """

        strategy sponsored by user BinH from slack

    """

    # minimal_roi = {
    #     "0": 0.2,
    #     "14400":0
    # }
    minimal_roi = {
        "0": 1
    }

    cnt = 0
    stoploss = -0.50
    timeframe = '1m'
    # use_sell_signal=False
    startup_candle_count: int = 30 * 30

    def get_ticker_indicator(self):
        return int(self.timeframe[:-1])

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        def altDataframe(min):  
          df = resample_to_interval(dataframe, self.get_ticker_indicator() * min)
          df['rsi'] = numpy.nan_to_num(ta.RSI(df, timeperiod=5))
          rsiframe = DataFrame(df['rsi']).rename(columns={'rsi': 'close'})
          df['emarsi'] = numpy.nan_to_num(ta.EMA(rsiframe, timeperiod=5))
          df['adx'] = numpy.nan_to_num(ta.ADX(df))
          df['minusdi'] = numpy.nan_to_num(ta.MINUS_DI(df))
          minusdiframe = DataFrame(df['minusdi']).rename(columns={'minusdi': 'close'})
          df['minusdiema'] = numpy.nan_to_num(ta.EMA(minusdiframe, timeperiod=25))
          df['plusdi'] = numpy.nan_to_num(ta.PLUS_DI(df))
          plusdiframe = DataFrame(df['plusdi']).rename(columns={'plusdi': 'close'})
          df['plusdiema'] = numpy.nan_to_num(ta.EMA(plusdiframe, timeperiod=5))
          df['lowsma'] = numpy.nan_to_num(ta.EMA(df, timeperiod=60))
          df['highsma'] = numpy.nan_to_num(ta.EMA(df, timeperiod=120))
          df['fastsma'] = numpy.nan_to_num(ta.SMA(df, timeperiod=120))
          df['slowsma'] = numpy.nan_to_num(ta.SMA(df, timeperiod=240))
          df['bigup'] = df['fastsma'].gt(df['slowsma']) & ((df['fastsma'] - df['slowsma']) > df['close'] / 300)
          
          df['bigdown'] = ~df['bigup']
          df['trend'] = df['fastsma'] - df['slowsma']
          df['preparechangetrend'] = df['trend'].gt(df['trend'].shift())
          df['preparechangetrendconfirm'] = df['preparechangetrend'] & df['trend'].shift(
          ).gt(df['trend'].shift(2))
          df['continueup'] = df['slowsma'].gt(
              df['slowsma'].shift()) & df['slowsma'].shift().gt(df['slowsma'].shift(2))
          df['delta'] = df['fastsma'] - df['fastsma'].shift()
          df['slowingdown'] = df['delta'].lt(df['delta'].shift())
          return df

        df30 = altDataframe(30)
        dataframe = resampled_merge(dataframe, df30)    
        dataframe.fillna(method='ffill', inplace=True)
        return dataframe

    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            dataframe['resample_30_slowsma'].gt(0) &
            dataframe['close'].lt(dataframe['resample_30_highsma']) &
            dataframe['close'].lt(dataframe['resample_30_lowsma']) &
            # crossover point of when the current down trend is crossing above the previous downtrends EMA to signal a price recovery to get in early before it peaks again
            dataframe['resample_30_minusdi'].gt(dataframe['resample_30_minusdiema']) &
            dataframe['resample_30_rsi'].ge(dataframe['resample_30_rsi'].shift()) &
            (
              (
                # Not The difference between the slow moving averages is increasing
                ~dataframe['resample_30_preparechangetrend'] &
                ~dataframe['resample_30_continueup'] &  #Not, Moving average going up for last two shifts
                dataframe['resample_30_adx'].gt(25) & #The directional trend isn't shit
                dataframe['resample_30_bigdown'] &  #FastAvg > slowAvg && difference > close/300
                  # The moving average of the rsi is really low
                  dataframe['resample_30_emarsi'].le(20)
              ) |
              (
                ~dataframe['resample_30_preparechangetrend'] &
                dataframe['resample_30_continueup'] &
                dataframe['resample_30_adx'].gt(30) &
                dataframe['resample_30_bigdown'] &
                dataframe['resample_30_emarsi'].le(20)
              ) |
              (
                ~dataframe['resample_30_continueup'] &
                dataframe['resample_30_adx'].gt(35) &
                dataframe['resample_30_bigup'] &
                dataframe['resample_30_emarsi'].le(20)
              ) |
              (
                dataframe['resample_30_continueup'] &  # Moving average going up for last two shifts
                dataframe['resample_30_adx'].gt(30) &  #directional trend is bad, but not shit
                dataframe['resample_30_bigup'] &
                dataframe['resample_30_emarsi'].le(25)
              )
            ),
            'buy'] = 1
        return dataframe
        
    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
              (
                ~dataframe['resample_30_preparechangetrendconfirm'] &
                ~dataframe['resample_30_continueup'] &
                (dataframe['close'].gt(dataframe['resample_30_lowsma']) | dataframe['close'].gt(dataframe['resample_30_highsma'])) &
                dataframe['resample_30_highsma'].gt(0) &
                dataframe['resample_30_bigdown']
              ) |
              (
                ~dataframe['resample_30_preparechangetrendconfirm'] &
                ~dataframe['resample_30_continueup'] &
                dataframe['close'].gt(dataframe['resample_30_highsma']) &
                dataframe['resample_30_highsma'].gt(0) &
                  (dataframe['resample_30_emarsi'].ge(75) | dataframe['close'].gt(dataframe['resample_30_slowsma'])) &
                dataframe['resample_30_bigdown']
              ) |
              (
                ~dataframe['resample_30_preparechangetrendconfirm'] &
                dataframe['resample_30_close'].gt(dataframe['resample_30_highsma']) &
                dataframe['resample_30_highsma'].gt(0) &
                dataframe['resample_30_adx'].gt(30) &
                dataframe['resample_30_emarsi'].ge(80) &
                dataframe['resample_30_bigup']
              ) |
              (
                dataframe['resample_30_preparechangetrendconfirm'] &
                ~dataframe['resample_30_continueup'] &
                dataframe['resample_30_slowingdown'] &
                dataframe['resample_30_emarsi'].ge(75) &
                dataframe['resample_30_slowsma'].gt(0)
              ) |
              (
                dataframe['resample_30_preparechangetrendconfirm'] &
                dataframe['resample_30_minusdi'].lt(dataframe['resample_30_plusdi']) &
                dataframe['close'].gt(dataframe['resample_30_lowsma']) &
                dataframe['resample_30_slowsma'].gt(0)
              )
            ),
            'sell'] = 1
        return dataframe
```

**Comment by xmatthias** [comment]
The error comes out of the strategy - so there'll be something wrong with the strategy.

The most likely cause is that one of your columns isn't filled correctly - however please understand that i will not debug your strategy for you.

Also, while it may be a strategy from the strategy repository - most of these strategies where community contributions - which means we do not guarantee for profits, nor for correct functioning.

**Comment by samgermain** [comment]
@xmatthias No it's a modification from the strategy, and it's specifically on new coin pairs `LIT/BTC` `SFP/BTC` and `CAKE/BTC` when running the strategy on time periods that span to before when these pairs were launched on binance. I found this out by placing the buy & sell strategy inside a try catch block. 

Also I don't know if you read what I put in there, but I mentioned I don't really need this solved, but posted it in case other users encounter a similar problem

I figured that I just won't do backtests on new coins, but from what you just said I'm worried something else could be wrong. Should I be worried about that?

**Comment by xmatthias** [comment]
well but the fact that it's a modification implies that it's a bug in the strategy.

the problem is that the comparisons you do to fill some indicators (for example for `resample_30_continueup`) may not have the "very early" pair's history, so the merge for the first 2-3 candles is empty / nan.

It's only apparent when resampling - but that results in a column that otherwise contains True / False values to be NaN - which is interpreted as Float and can therefore not be negated.

You'll simply need to fill these columns with something sensible (eihter True or False, whatver the "non-acting default" is).

It's not a problem if the "full" history is available - as it's a resample / merge problem (if your history starts at 12:05:00, the first possible merge point between 1m and 30m candles is 12:30:00, leaving all candles up to that point as "NaN".

**Comment by xmatthias** [comment]
I'll assume this as answered by the above.

Feel free to comment below / reopen if that's not the case.
