### ISSUE TITLE
cannot start live trade on binance since docker desktop update to 3.2.1

### ISSUE THREAD

**Issue by tomismrkolj** [freqtrade/freqtrade#4537]
## Describe your environment

  * Operating system: _Windows 10, _Docker desktop 3.2.1__
  * Python Version: __3___ (`python -V`)
  * CCXT version: __?___ (`pip freeze | grep ccxt`)
  * Freqtrade Version: __freqtrade docker-441d3fad__ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:
2 days ago Docker desktop for windows updated automatically to 3.2.1. Cannot start live trade on binance since then.
*Explain the problem you have encountered*

### Steps to reproduce:

  1. _update docker desktop to 3.2.1____
  2. __start freqtrade live trade___
  3. _____
  
### Observed Results:

 errors are reported in log and freqtrade tries to restart

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
 2021-03-13 12:58:51,495 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"

2021-03-13 12:58:52,518 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...

2021-03-13 12:58:52,808 - freqtrade.exchange.common - WARNING - get_balances() returned exception: "Could not get balance due to InvalidNonce. Message: binance {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}"

2021-03-13 12:58:52,808 - freqtrade.exchange.common - WARNING - retrying get_balances() still for 4 times

2021-03-13 12:58:53,317 - freqtrade.exchange.common - WARNING - get_balances() returned exception: "Could not get balance due to InvalidNonce. Message: binance {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}"

2021-03-13 12:58:53,318 - freqtrade.exchange.common - WARNING - retrying get_balances() still for 3 times

2021-03-13 12:58:53,817 - freqtrade.exchange.common - WARNING - get_balances() returned exception: "Could not get balance due to InvalidNonce. Message: binance {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}"

2021-03-13 12:58:53,823 - freqtrade.exchange.common - WARNING - retrying get_balances() still for 2 times

2021-03-13 12:58:54,327 - freqtrade.exchange.common - WARNING - get_balances() returned exception: "Could not get balance due to InvalidNonce. Message: binance {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}"

2021-03-13 12:58:54,328 - freqtrade.exchange.common - WARNING - retrying get_balances() still for 1 times

2021-03-13 12:58:54,828 - freqtrade.exchange.common - WARNING - get_balances() returned exception: "Could not get balance due to InvalidNonce. Message: binance {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}"

2021-03-13 12:58:54,829 - freqtrade.exchange.common - WARNING - Giving up retrying: get_balances()

2021-03-13 12:58:54,830 - freqtrade.commands.trade_commands - ERROR - Could not get balance due to InvalidNonce. Message: binance {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}

2021-03-13 12:58:54,830 - freqtrade.commands.trade_commands - ERROR - Fatal exception!

Traceback (most recent call last):

File "/root/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 592, in fetch

response.raise_for_status()

File "/root/.local/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status

raise HTTPError(http_error_msg, response=self)

requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/account?timestamp=1615640332564&recvWindow=5000&signature=**********


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

File "/freqtrade/freqtrade/exchange/exchange.py", line 681, in get_balances

balances = self._api.fetch_balance()

File "/root/.local/lib/python3.9/site-packages/ccxt/binance.py", line 1031, in fetch_balance

response = getattr(self, method)(query)

File "/root/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 466, in inner

return entry(_self, **inner_kwargs)

File "/root/.local/lib/python3.9/site-packages/ccxt/binance.py", line 2703, in request

response = self.fetch2(path, api, method, params, headers, body)

File "/root/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 487, in fetch2

return self.fetch(request['url'], request['method'], request['headers'], request['body'])

File "/root/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 608, in fetch

self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)

File "/root/.local/lib/python3.9/site-packages/ccxt/binance.py", line 2697, in handle_errors

self.throw_exactly_matched_exception(self.exceptions, error, feedback)

File "/root/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 505, in throw_exactly_matched_exception

raise exact[string](message)

ccxt.base.errors.InvalidNonce: binance {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

File "/freqtrade/freqtrade/exchange/common.py", line 136, in wrapper

return f(*args, **kwargs)

File "/freqtrade/freqtrade/exchange/exchange.py", line 692, in get_balances

raise TemporaryError(

freqtrade.exceptions.TemporaryError: Could not get balance due to InvalidNonce. Message: binance {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}

**Comment by xmatthias** [comment]
your time is off.

THe most likely cause: your docker for windows is using WSL2 - which has a seperate (not connected to windows) time ... so you'll need to either switch docker back to not use WSL2 - or setup time sync for WSL2 (there's a bug with WSL2 which describes that time is not aligned with windows).

**Comment by tomismrkolj** [comment]
I managed to resync clock in powershell with
wsl --shutdown
wsl

I am curious, how long this will hold.

**Comment by xmatthias** [comment]
you'll most likely need to set it up seperately ... it's not something docker can control though ...
