### ISSUE TITLE
problem with informative_pairs 

### ISSUE THREAD

**Issue by gen4sp** [freqtrade/freqtrade#4565]
## Describe your environment

  * Operating system: mac os
  * Python Version: 3 (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
I've got an error trying to use this code `dataframe = merge_informative_pair(dataframe, informative, self.timeframe, inf_tf, ffill=True)` as it described on https://www.freqtrade.io/en/latest/strategy-customization/#additional-data-informative_pairs

The error I've got:
` unsupported operand type(s) for -: 'numpy.ndarray' and 'Timedelta'`

Details:
```
2021-03-17 00:50:17,846 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 50, in start_backtesting
    backtesting.start()
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 449, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 407, in backtest_one_strategy
    preprocessed = self.strategy.ohlcvdata_to_dataframe(data)
  File "/freqtrade/freqtrade/strategy/interface.py", line 668, in ohlcvdata_to_dataframe
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair})
  File "/freqtrade/freqtrade/strategy/interface.py", line 668, in <dictcomp>
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair})
  File "/freqtrade/freqtrade/strategy/interface.py", line 685, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/freqtrade/user_data/strategies/TenderEnter.py", line 335, in populate_indicators
    dataframe = merge_informative_pair(dataframe, informative, self.timeframe, inf_tf, True)
  File "/freqtrade/freqtrade/strategy/strategy_helper.py", line 40, in merge_informative_pair
    informative["date"] + pd.to_timedelta(minutes_inf, 'm') - pd.to_timedelta(minutes, 'm')
  File "/root/.local/lib/python3.9/site-packages/pandas/core/ops/common.py", line 65, in new_method
    return method(self, other)
  File "/root/.local/lib/python3.9/site-packages/pandas/core/arraylike.py", line 97, in __sub__
    return self._arith_method(other, operator.sub)
  File "/root/.local/lib/python3.9/site-packages/pandas/core/series.py", line 4995, in _arith_method
    result = ops.arithmetic_op(lvalues, rvalues, op)
  File "/root/.local/lib/python3.9/site-packages/pandas/core/ops/array_ops.py", line 185, in arithmetic_op
    res_values = op(lvalues, rvalues)
TypeError: unsupported operand type(s) for -: 'numpy.ndarray' and 'Timedelta'
```

**Comment by xmatthias** [comment]
It sounds like either the "informative" date column, or one of the timeframes is not in the correct format.

As i don't think with wrong timeframes you'd get this far - i would suggest to look at what format the date column is - it's supposed to be a datetime column - the error suggests it might be a nested array - but without seeing either everything up to this point in the strategy, or the dataframe, that's quite difficult to tell for certain

**Comment by gen4sp** [comment]
@xmatthias 
Yes, I have a lot of messages like this 
```
2021-03-17 01:31:11,141 - freqtrade.data.converter - INFO - Missing data fillup for AVA/USDT: before: 8620 - after: 8638
2021-03-17 01:31:11,214 - freqtrade.data.converter - INFO - Missing data fillup for XEM/USDT: before: 8620 - after: 8638
2021-03-17 01:31:11,287 - freqtrade.data.converter - INFO - Missing data fillup for SKL/USDT: before: 8620 - after: 8638
2021-03-17 01:31:11,383 - freqtrade.data.converter - INFO - Missing data fillup for SUSD/USDT: before: 8620 - after: 8638
2021-03-17 01:31:11,477 - freqtrade.data.converter - INFO - Missing data fillup for GRT/USDT: before: 8620 - after: 8638
2021-03-17 01:31:11,551 - freqtrade.data.converter - INFO - Missing data fillup for JUV/USDT: before: 8620 - after: 8638
```

because binance was off for a while officially. 
Is it a problem? How I can solve that? 

(if I don't use merge_informative_pair  - everything else works fine!)

**Comment by xmatthias** [comment]
it's an info message, telling you that some data needed filling up. It's normal, as binance does have downtimes from time to time (scheduled or not ...).

`merge_informative_pair()` may be the one to raise the error, but it'll be caused by the treatment of the dataframe BEFORE that which will be the cause of the problem, so without the code for that part, there's nothing i can do for you.

**Comment by gen4sp** [comment]
@xmatthias everything seems the same as in example

```
def informative_pairs(self):
        print('TT', metadata['pair'])       # this never prints
        return [(metadata['pair'], "15m")]

def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        # Parabolic SAR
        dataframe['sar'] = ta.SAR(dataframe)

        # TEMA - Triple Exponential Moving Average
        dataframe['tema'] = ta.TEMA(dataframe, timeperiod=9)
        
        informative = self.dp.get_pair_dataframe(pair=f"{self.stake_currency}/USDT", timeframe=self.inf_tf)
        # informative = self.dp.get_pair_dataframe(pair=metadata['pair'], timeframe=self.inf_tf)
        
        dataframe = merge_informative_pair(dataframe, informative, self.timeframe, self.inf_tf, ffill=True)
        # dataframe = merge_informative_pair(dataframe, informative, self.timeframe, inf_tf, True)
        return dataframe
```

this is the command for downloading:
`docker-compose run --rm freqtrade download-data --exchange binance `

**Comment by xmatthias** [comment]
`informative_pairs()` is not called in backtesting, only in dry-runs.
Backtesting will have "all" pairs available - even if they're not specified in informative_pairs.


You've got a logic error though - you're using USDT pairs (based on the output above) - but you use `f"{self.stake_currency}/USDT"` ... which will result in `'USDT/USDT'` when using USDT as stake_currency - which is not a valid pair.


Therefore, loading `informative` fails - resulting in an empty dataframe, you then pass that into merge without validating if it loaded correctly, which causes the merging to fail (you merge a empty dataframe, basically).

Now the docs assume you get a (filled) dataframe - mainly for simplicity as full error-handling would overwelm many new users - but it's not guaranteed and will depend on your input.

**Comment by xmatthias** [comment]
I'll assume this as answered by the above.

Feel free to comment below / reopen if that's not the case.
