### ISSUE TITLE
Pairlist PriceFilter crashes on bad data

### ISSUE THREAD

**Issue by vwaart** [freqtrade/freqtrade#4573]
## Describe your environment

  * Operating system: MacOS
  * Python Version: 3.9.1
  * CCXT version: ccxt==1.40.99
  * Freqtrade Version: freqtrade 2021.2
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

  1. Enable PriceFilter in pairlist config:
```
"pairlists": [
    {
      "method": "StaticPairList"
    },
    {
      "method": "PriceFilter",
      "low_price_ratio": 0.005
    }
  ],
```

  2.Wait until (presumably) the exchange sends faulty ticker data
  3.Bot crashes, process dies:

  
### Observed Results:

  * What happened?  **Process dies**
  * What did you expect to happen? **PriceFilter to gracefully handle missing data**

### Relevant code exceptions or logs

```
2021-03-19 09:20:14,569 - freqtrade.edge.edge_positioning - INFO - Minimum expectancy and minimum winrate are met only for ['WAN/BTC', 'HARD/BTC', 'STEEM/BTC', 'DLT/BTC', 'RCN/BTC', 'ASR/BTC', 'FIL/BTC', 'DIA/BTC', 'JUV/BTC', 'ATM/BTC', 'FIO/BTC', 'CTXC/BTC', 'LUNA/BTC', 'MATIC/BTC', 'INJ/BTC'], so other pairs are filtered out.
2021-03-19 09:20:14,843 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=93, pair=WABI/BTC, amount=10351.00000000, open_rate=0.00000675, open_since=2021-03-17 15:07:50)
2021-03-19 09:20:15,356 - freqtrade.wallets - INFO - Wallets synced.
2021-03-19 09:20:20,470 - freqtrade.commands.trade_commands - ERROR - 'last'
2021-03-19 09:20:20,471 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/Users/aartverweij/tradingbot/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker.run()
  File "/Users/aartverweij/tradingbot/freqtrade/freqtrade/worker.py", line 74, in run
    state = self._worker(old_state=state)
  File "/Users/aartverweij/tradingbot/freqtrade/freqtrade/worker.py", line 111, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
  File "/Users/aartverweij/tradingbot/freqtrade/freqtrade/worker.py", line 132, in _throttle
    result = func(*args, **kwargs)
  File "/Users/aartverweij/tradingbot/freqtrade/freqtrade/worker.py", line 145, in _process_running
    self.freqtrade.process()
  File "/Users/aartverweij/tradingbot/freqtrade/freqtrade/freqtradebot.py", line 164, in process
    self.active_pair_whitelist = self._refresh_active_whitelist(trades)
  File "/Users/aartverweij/tradingbot/freqtrade/freqtrade/freqtradebot.py", line 223, in _refresh_active_whitelist
    self.pairlists.refresh_pairlist()
  File "/Users/aartverweij/tradingbot/freqtrade/freqtrade/plugins/pairlistmanager.py", line 90, in refresh_pairlist
    pairlist = pairlist_handler.filter_pairlist(pairlist, tickers)
  File "/Users/aartverweij/tradingbot/freqtrade/freqtrade/plugins/pairlist/IPairList.py", line 113, in filter_pairlist
    if not self._validate_pair(p, tickers[p] if p in tickers else {}):
  File "/Users/aartverweij/tradingbot/freqtrade/freqtrade/plugins/pairlist/PriceFilter.py", line 67, in _validate_pair
    if ticker['last'] is None or ticker['last'] == 0:
KeyError: 'last'
2021-03-19 09:20:20,481 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2021-03-19 09:20:20,481 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2021-03-19 09:20:20,611 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2021-03-19 09:20:20,616 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': warning, 'status': "4 open trades active.\n\nHandle these trades manually on Binance, or '/start' the bot again and use '/stopbuy' to handle open trades gracefully. \n"}
```

**Comment by vwaart** [comment]
I use Binance as exchange.

**Comment by xmatthias** [comment]
i've never seen a ticker-response which did not contain the "last" key.

It's one of the things ccxt kindof guarantees - so if 'last' is missing, i'd have to assume that it's probably somehow network related.
While you provide the part of the logs where it crashes, the ticker for this may be fetched earlier - so we'll need more logs (from before this) to debug this properly.

**Comment by vwaart** [comment]
This is perhaps a relevant bit of the logs: 

Other than this I see not much more than edge INFO messages, wallets sync (every heartbeat). 

```
2021-03-19 09:00:02,768 - freqtrade.edge.edge_positioning - INFO - Minimum expectancy and minimum winrate are met only for ['WAN/BTC', 'HARD/BTC', 'STEEM/BTC', 'DLT/BTC', 'RCN/BTC', 'ASR/BTC', 'FIL/BTC', 'DIA/BTC', 'JUV/BTC', 'ATM/BTC', 'FIO/BTC', 'CTXC/BTC', 'LUNA/BTC', 'MATIC/BTC', 'INJ/BTC'], so other pairs are filtered out.
2021-03-19 09:00:05,872 - freqtrade.data.converter - INFO - Missing data fillup for WABI/BTC: before: 999 - after: 1001
2021-03-19 09:00:05,890 - freqtrade.data.converter - INFO - Missing data fillup for STEEM/BTC: before: 999 - after: 1001
2021-03-19 09:00:05,909 - freqtrade.data.converter - INFO - Missing data fillup for ASR/BTC: before: 999 - after: 1001
2021-03-19 09:00:05,929 - freqtrade.data.converter - INFO - Missing data fillup for MATIC/BTC: before: 999 - after: 1001
2021-03-19 09:00:05,957 - freqtrade.data.converter - INFO - Missing data fillup for FIO/BTC: before: 999 - after: 1001
2021-03-19 09:00:05,977 - freqtrade.data.converter - INFO - Missing data fillup for CTXC/BTC: before: 999 - after: 1001
2021-03-19 09:00:05,996 - freqtrade.data.converter - INFO - Missing data fillup for DLT/BTC: before: 999 - after: 1001
2021-03-19 09:00:06,014 - freqtrade.data.converter - INFO - Missing data fillup for RCN/BTC: before: 999 - after: 1001
2021-03-19 09:00:06,035 - freqtrade.data.converter - INFO - Missing data fillup for INJ/BTC: before: 999 - after: 1001
2021-03-19 09:00:06,058 - freqtrade.data.converter - INFO - Missing data fillup for HARD/BTC: before: 999 - after: 1001
2021-03-19 09:00:06,079 - freqtrade.data.converter - INFO - Missing data fillup for FIL/BTC: before: 999 - after: 1001
2021-03-19 09:00:06,094 - freqtrade.data.converter - INFO - Missing data fillup for WAN/BTC: before: 999 - after: 1001
2021-03-19 09:00:06,114 - freqtrade.data.converter - INFO - Missing data fillup for LUNA/BTC: before: 999 - after: 1001
2021-03-19 09:00:06,131 - freqtrade.data.converter - INFO - Missing data fillup for JUV/BTC: before: 999 - after: 1001
2021-03-19 09:00:06,152 - freqtrade.data.converter - INFO - Missing data fillup for ATM/BTC: before: 999 - after: 1001
2021-03-19 09:00:06,172 - freqtrade.data.converter - INFO - Missing data fillup for DIA/BTC: before: 999 - after: 1001
2021-03-19 09:00:06,514 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=93, pair=WABI/BTC, amount=10351.00000000, open_rate=0.00000675, open_since=2021-03-17 15:07:50)
2021-03-19 09:00:07,028 - freqtrade.wallets - INFO - Wallets synced.
2021-03-19 09:00:08,544 - freqtrade.edge.edge_positioning - INFO - Minimum expectancy and minimum winrate are met only for ['WAN/BTC', 'HARD/BTC', 'STEEM/BTC', 'DLT/BTC', 'RCN/BTC', 'ASR/BTC', 'FIL/BTC', 'DIA/BTC', 'JUV/BTC', 'ATM/BTC', 'FIO/BTC', 'CTXC/BTC', 'LUNA/BTC', 'MATIC/BTC', 'INJ/BTC'], so other pairs are filtered out.
2021-03-19 09:00:11,043 - freqtrade.data.converter - INFO - Missing data fillup for WABI/BTC: before: 999 - after: 1001
2021-03-19 09:00:11,057 - freqtrade.data.converter - INFO - Missing data fillup for STEEM/BTC: before: 999 - after: 1001
2021-03-19 09:00:11,073 - freqtrade.data.converter - INFO - Missing data fillup for ASR/BTC: before: 999 - after: 1001
2021-03-19 09:00:11,100 - freqtrade.data.converter - INFO - Missing data fillup for CTXC/BTC: before: 999 - after: 1001
2021-03-19 09:00:11,115 - freqtrade.data.converter - INFO - Missing data fillup for DLT/BTC: before: 999 - after: 1001
2021-03-19 09:00:11,130 - freqtrade.data.converter - INFO - Missing data fillup for RCN/BTC: before: 999 - after: 1001
2021-03-19 09:00:11,147 - freqtrade.data.converter - INFO - Missing data fillup for INJ/BTC: before: 999 - after: 1001
2021-03-19 09:00:11,168 - freqtrade.data.converter - INFO - Missing data fillup for HARD/BTC: before: 999 - after: 1001
2021-03-19 09:00:11,187 - freqtrade.data.converter - INFO - Missing data fillup for FIL/BTC: before: 999 - after: 1001
2021-03-19 09:00:11,207 - freqtrade.data.converter - INFO - Missing data fillup for WAN/BTC: before: 999 - after: 1001
2021-03-19 09:00:11,225 - freqtrade.data.converter - INFO - Missing data fillup for JUV/BTC: before: 999 - after: 1001
2021-03-19 09:00:11,239 - freqtrade.data.converter - INFO - Missing data fillup for ATM/BTC: before: 999 - after: 1001
2021-03-19 09:00:11,254 - freqtrade.data.converter - INFO - Missing data fillup for DIA/BTC: before: 999 - after: 1001
2021-03-19 09:00:11,830 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=93, pair=WABI/BTC, amount=10351.00000000, open_rate=0.00000675, open_since=2021-03-17 15:07:50)
2021-03-19 09:00:12,342 - freqtrade.wallets - INFO - Wallets synced.
2021-03-19 09:00:13,860 - freqtrade.edge.edge_positioning - INFO - Minimum expectancy and minimum winrate are met only for ['WAN/BTC', 'HARD/BTC', 'STEEM/BTC', 'DLT/BTC', 'RCN/BTC', 'ASR/BTC', 'FIL/BTC', 'DIA/BTC', 'JUV/BTC', 'ATM/BTC', 'FIO/BTC', 'CTXC/BTC', 'LUNA/BTC', 'MATIC/BTC', 'INJ/BTC'], so other pairs are filtered out.
2021-03-19 09:00:14,155 - freqtrade.data.converter - INFO - Missing data fillup for WABI/BTC: before: 999 - after: 1001
2021-03-19 09:00:14,437 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=93, pair=WABI/BTC, amount=10351.00000000, open_rate=0.00000675, open_since=2021-03-17 15:07:50)
2021-03-19 09:00:14,959 - freqtrade.wallets - INFO - Wallets synced.
2021-03-19 09:00:18,862 - freqtrade.edge.edge_positioning - INFO - Minimum expectancy and minimum winrate are met only for ['WAN/BTC', 'HARD/BTC', 'STEEM/BTC', 'DLT/BTC', 'RCN/BTC', 'ASR/BTC', 'FIL/BTC', 'DIA/BTC', 'JUV/BTC', 'ATM/BTC', 'FIO/BTC', 'CTXC/BTC', 'LUNA/BTC', 'MATIC/BTC', 'INJ/BTC'], so other pairs are filtered out.
2021-03-19 09:00:19,549 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=93, pair=WABI/BTC, amount=10351.00000000, open_rate=0.00000675, open_since=2021-03-17 15:07:50)
2021-03-19 09:00:19,798 - freqtrade.wallets - INFO - Wallets synced.
```

I'm affraid this won't help much.  Anything else I can check?

**Comment by xmatthias** [comment]
it absolutely doesn't, no ...
best have a look if it happens again? 

I've not seen this happen - and i run between 2 and 5 dry-run bots at all times (not counting live bots) - usually these including the PriceFilter.

**Comment by maximilianwank** [comment]
Hey guys, happened to me, too.
```
2021-03-25 11:36:04,219 - freqtrade.commands.trade_commands - ERROR - 'last'
2021-03-25 11:36:04,219 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/root/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker.run()
  File "/root/freqtrade/freqtrade/worker.py", line 74, in run
    state = self._worker(old_state=state)
  File "/root/freqtrade/freqtrade/worker.py", line 111, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
  File "/root/freqtrade/freqtrade/worker.py", line 132, in _throttle
    result = func(*args, **kwargs)
  File "/root/freqtrade/freqtrade/worker.py", line 145, in _process_running
    self.freqtrade.process()
  File "/root/freqtrade/freqtrade/freqtradebot.py", line 164, in process
    self.active_pair_whitelist = self._refresh_active_whitelist(trades)
  File "/root/freqtrade/freqtrade/freqtradebot.py", line 223, in _refresh_active_whitelist
    self.pairlists.refresh_pairlist()
  File "/root/freqtrade/freqtrade/plugins/pairlistmanager.py", line 90, in refresh_pairlist
    pairlist = pairlist_handler.filter_pairlist(pairlist, tickers)
  File "/root/freqtrade/freqtrade/plugins/pairlist/IPairList.py", line 113, in filter_pairlist
    if not self._validate_pair(p, tickers[p] if p in tickers else {}):
  File "/root/freqtrade/freqtrade/plugins/pairlist/PriceFilter.py", line 67, in _validate_pair
    if ticker['last'] is None or ticker['last'] == 0:
KeyError: 'last'
2021-03-25 11:36:04,220 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2021-03-25 11:36:04,220 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2021-03-25 11:36:04,355 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2021-03-25 11:36:04,358 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
2021-03-25 11:36:04,359 - apscheduler.scheduler - INFO - Scheduler has been shut down
```
I use Ubuntu 18.04. I checked out the stable branch and used the installation script. Worked for some days, first occurence today. On my second maschine, I had no problems.

**Comment by xmatthias** [comment]
it's fixed in develop, but it's not yet in the latest release.

**Comment by maximilianwank** [comment]
I just found the commit, thanks. And thanks for fixing!
