### ISSUE TITLE
ERROR - Unexpected error can't compare offset-naive and offset-aware datetimes calling

### ISSUE THREAD

**Issue by BinaryParadox** [freqtrade/freqtrade#4580]
## Describe your environment
- Operating system: Debian GNU/Linux 10 (buster)
- Python Version: Python 3.7.3
- CCXT version: 1.41.62
- Freqtrade Version: develop-79d4585d

Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

The bot shutdown right after setting stoploss. I didn't experience it before using this latest develop version.
Temporarily, commented out the if statement `if current_profit < 0.00 and current_time - timedelta(minutes=1440) > trade.open_date:` in my current strategy to avoid accidental shutdown of my bot.

```
2021-03-17 09:33:45,257 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=56, pair=LINK/USDT, amount=2.50000000, open_rate=27.65960000, open_since=2021-03-17 09:33:16)
2021-03-17 09:33:47,570 - freqtrade.worker - INFO - Bot heartbeat. PID=25985, version='develop-79d4585d', state='RUNNING'
2021-03-17 09:33:49,484 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=56, pair=LINK/USDT, amount=2.50000000, open_rate=27.65960000, open_since=2021-03-17 09:33:16)
2021-03-17 09:33:50,498 - freqtrade.walletc - INFO - Wallets synced.
2021-03-17 09:33:50,498 - freqtrade.freqtradebot - INFO - Fee amount for Trade(id=56, pair=LINK/USDT, amount=2.50000000, open_rate=27.65960000, open_since=2021-03-17 09:33:16) was in base currency - Eating Fee 0.0025 into dust.
2021-03-17 09:33:50,500 - freqtrade.persistence.models - INFO - Updating trade (id=56) ...
2021-03-17 09:33:50,500 - freqtrade.persistence.models - INFO - LIMIT_BUY has been fulfilled for Trade(id=56, pair=LINK/USDT, amount=2.50000000, open_rate=27.65960000, open_since=2021-03-17 09:33:16).
2021-03-17 09:33:51,110 - freqtrade.exchange.binance - INFO - stoploss limit order added for LINK/USDT. stop price: 19.3618. limit: 19.1682
2021-03-17 09:33:51,484 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error can't compare offset-naive and offset-aware datetimes calling <bound method AGS004.custom_stoploss of <AGS004.AGS004 object at 0x7f57fb8962e8>>
Traceback (most recent call last):
  File "/home/binary_paradox101010/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 17, in wrapper
    return f(*args, **kwargs)
  File "/home/binary_paradox101010/freqtrade/user_data/strategies/ags004.py", line 86, in custom_stoploss
    if current_profit < 0.00 and current_time - timedelta(minutes=1440) > trade.open_date:
TypeError: can't compare offset-naive and offset-aware datetimes
2021-03-17 09:33:51,485 - freqtrade.commands.trade_commands - ERROR - can't compare offset-naive and offset-aware datetimes
2021-03-17 09:33:51,485 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/binary_paradox101010/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 17, in wrapper
    return f(*args, **kwargs)
  File "/home/binary_paradox101010/freqtrade/user_data/strategies/ags004.py", line 86, in custom_stoploss
    if current_profit < 0.00 and current_time - timedelta(minutes=1440) > trade.open_date:
TypeError: can't compare offset-naive and offset-aware datetimes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/binary_paradox101010/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker.run()
  File "/home/binary_paradox101010/freqtrade/freqtrade/worker.py", line 74, in run
    state = self._worker(old_state=state)
  File "/home/binary_paradox101010/freqtrade/freqtrade/worker.py", line 111, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
  File "/home/binary_paradox101010/freqtrade/freqtrade/worker.py", line 132, in _throttle
    result = func(*args, **kwargs)
  File "/home/binary_paradox101010/freqtrade/freqtrade/worker.py", line 145, in _process_running
    self.freqtrade.process()
  File "/home/binary_paradox101010/freqtrade/freqtrade/freqtradebot.py", line 184, in process
    self.exit_positions(trades)
  File "/home/binary_paradox101010/freqtrade/freqtrade/freqtradebot.py", line 698, in exit_positions
    if trade.open_order_id is None and trade.is_open and self.handle_trade(trade):
  File "/home/binary_paradox101010/freqtrade/freqtrade/freqtradebot.py", line 804, in handle_trade
    if self._check_and_execute_sell(trade, sell_rate, buy, sell):
  File "/home/binary_paradox101010/freqtrade/freqtrade/freqtradebot.py", line 941, in _check_and_execute_sell
    force_stoploss=self.edge.stoploss(trade.pair) if self.edge else 0
  File "/home/binary_paradox101010/freqtrade/freqtrade/strategy/interface.py", line 520, in should_sell
    force_stoploss=force_stoploss, high=high)
  File "/home/binary_paradox101010/freqtrade/freqtrade/strategy/interface.py", line 583, in stop_loss_reached
    current_profit=current_profit)
  File "/home/binary_paradox101010/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 33, in wrapper
    raise StrategyError(str(error)) from error
freqtrade.exceptions.StrategyError: can't compare offset-naive and offset-aware datetimes
2021-03-17 09:33:51,486 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2021-03-17 09:33:51,486 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2021-03-17 09:33:51,842 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2021-03-17 09:33:51,855 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': warning, 'status': "1 open trades active.\n\nHandle these trades manually on Binance, or '/start' the bot again and use '/stopbuy' to handle open trades gracefully. \n"}
2021-03-17 09:33:52,208 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
2021-03-17 09:33:52,208 - freqtrade.rpc.api_server.webserver - INFO - Stopping API Server
2021-03-17 09:33:52,233 - uvicorn.error - INFO - Shutting down
2021-03-17 09:33:52,334 - uvicorn.error - INFO - Waiting for application shutdown.
2021-03-17 09:33:52,335 - uvicorn.error - INFO - Application shutdown complete.
```

### Steps to reproduce:
- Use the following custom_stoploss method which is the one defined in my strategy:
```python
    def custom_stoploss(self, pair: str, trade: Trade, current_time: datetime, current_rate: float,
                        current_profit: float, **kwargs) -> float:
        if current_profit < 0.00 and current_time - timedelta(minutes=1440) > trade.open_date:
            return -0.001
        if current_profit > 0.02:
            return -0.01
        return -0.20
```

**Comment by xmatthias** [comment]
as you're using a new version, you should be using `trade.open_date_utc` - which guarantees timestamps with UTC timezone.

This field was added recently to cover exactly this kind of problems.

I've updated the docs now to also use the correct field.

**Comment by BinaryParadox** [comment]
Got it, thanks a lot @xmatthias!
