### ISSUE TITLE
Missing data fillup error and length of values does not match length of index 

### ISSUE THREAD

**Issue by Kaw11** [freqtrade/freqtrade#4610]
## Describe your environment

    Operating system: Ubuntu 20.04.2.0
    Python Version: Python 3.8.5
    CCXT version: 1.42.19
    Freqtrade Version: freqtrade 2021.2

  
## Your question

Hello! 
I am currently trading (dry_run = true) on an hourly ticker interval (using binance exchange), and every time I try to run Hyperopt, it keeps showing this -

..freqtrade.data.converter - INFO - Missing data fillup for XMR/BTC: before: 717 - after: 718 (And this keeps showing for many more pairs).
AND
ValueError: Length of values (1) does not match length of index (718) I understand that this has to do something with either pandas or binance, but I have no idea on how to fix it?

**Comment by xmatthias** [comment]
the data fillup is just an info - as it's just 1 candle (1h) missing it'll be ok (exchange downtimes can cause this).

The ValueErorr is difficult to say as that will depend on your strategy - so i'd assume that maybe you're not returning the dataframe from the strategy ... or something else is done wrongly.
without the stacktrace, which shows where the error originates from, it'll be difficult to tell for sure.

**Comment by Kaw11** [comment]
Yes, of course! 

freqtrade hyperopt --config config.json --hyperopt bbrsi_opt --hyperopt-loss SharpeHyperOptLoss --strategy bbrsi -e 500 --spaces all
2021-03-27 12:31:03,090 - freqtrade.configuration.configuration - INFO - Using config: config.json ...
2021-03-27 12:31:03,093 - freqtrade.loggers - INFO - Verbosity set to 0
2021-03-27 12:31:03,093 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 15 ...
2021-03-27 12:31:03,094 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/reivski/freqtrade/user_data ...
2021-03-27 12:31:03,095 - freqtrade.configuration.configuration - INFO - Using data directory: /home/reivski/freqtrade/user_data/data/binance ...
2021-03-27 12:31:03,095 - freqtrade.configuration.configuration - INFO - Using Hyperopt class name: bbrsi_opt
2021-03-27 12:31:03,095 - freqtrade.configuration.configuration - INFO - Parameter --epochs detected ... Will run Hyperopt with for 500 epochs ...
2021-03-27 12:31:03,096 - freqtrade.configuration.configuration - INFO - Parameter -s/--spaces detected: ['all']
2021-03-27 12:31:03,096 - freqtrade.configuration.configuration - INFO - Parameter -j/--job-workers detected: -1
2021-03-27 12:31:03,096 - freqtrade.configuration.configuration - INFO - Parameter --min-trades detected: 1
2021-03-27 12:31:03,097 - freqtrade.configuration.configuration - INFO - Using Hyperopt loss class name: SharpeHyperOptLoss
2021-03-27 12:31:03,097 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2021-03-27 12:31:03,097 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2021-03-27 12:31:03,097 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2021-03-27 12:31:03,098 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2021-03-27 12:31:03,116 - freqtrade.commands.optimize_commands - INFO - Starting freqtrade in Hyperopt mode
2021-03-27 12:31:03,125 - filelock - INFO - Lock 139784499766032 acquired on /home/reivski/freqtrade/user_data/hyperopt.lock
2021-03-27 12:31:03,126 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2021-03-27 12:31:03,126 - freqtrade.exchange.exchange - INFO - Using CCXT 1.42.19
2021-03-27 12:31:03,126 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2021-03-27 12:31:03,187 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 500}
2021-03-27 12:31:03,245 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2021-03-27 12:31:05,521 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2021-03-27 12:31:05,523 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy bbrsi from '/home/reivski/freqtrade/user_data/strategies/bbrsi.py'...
2021-03-27 12:31:05,524 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: BTC.
2021-03-27 12:31:05,524 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 0.01.
2021-03-27 12:31:05,524 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'protections' with value in config file: [{'method': 'StoplossGuard', 'lookback_period_candles': 96, 'trade_limit': 4, 'stop_duration_candles': 24, 'only_per_pair': False}, {'method': 'MaxDrawdown', 'lookback_period_candles': 200, 'trade_limit': 20, 'stop_duration_candles': 48, 'max_allowed_drawdown': 0.1}, {'method': 'LowProfitPairs', 'lookback_period_candles': 24, 'trade_limit': 4, 'stop_duration_candles': 12, 'required_profit': 0.01}].
2021-03-27 12:31:05,525 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'buy': 10, 'sell': 30}.
2021-03-27 12:31:05,525 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'use_sell_signal' with value in config file: True.
2021-03-27 12:31:05,525 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'sell_profit_only' with value in config file: True.
2021-03-27 12:31:05,525 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ignore_roi_if_buy_signal' with value in config file: False.
2021-03-27 12:31:05,526 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'40': 0.0, '30': 0.01, '20': 0.02, '0': 0.04}
2021-03-27 12:31:05,526 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 1h
2021-03-27 12:31:05,526 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.99
2021-03-27 12:31:05,526 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2021-03-27 12:31:05,526 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2021-03-27 12:31:05,527 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2021-03-27 12:31:05,527 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2021-03-27 12:31:05,527 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
2021-03-27 12:31:05,527 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False}
2021-03-27 12:31:05,527 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
2021-03-27 12:31:05,528 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: BTC
2021-03-27 12:31:05,528 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 0.01
2021-03-27 12:31:05,528 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: [{'method': 'StoplossGuard', 'lookback_period_candles': 96, 'trade_limit': 4, 'stop_duration_candles': 24, 'only_per_pair': False}, {'method': 'MaxDrawdown', 'lookback_period_candles': 200, 'trade_limit': 20, 'stop_duration_candles': 48, 'max_allowed_drawdown': 0.1}, {'method': 'LowProfitPairs', 'lookback_period_candles': 24, 'trade_limit': 4, 'stop_duration_candles': 12, 'required_profit': 0.01}]
2021-03-27 12:31:05,528 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 20
2021-03-27 12:31:05,529 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'buy': 10, 'sell': 30}
2021-03-27 12:31:05,529 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_sell_signal: True
2021-03-27 12:31:05,529 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_only: True
2021-03-27 12:31:05,529 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_buy_signal: False
2021-03-27 12:31:05,530 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_offset: 0.0
2021-03-27 12:31:05,530 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2021-03-27 12:31:05,530 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2021-03-27 12:31:05,531 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2021-03-27 12:31:05,579 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from '/home/reivski/freqtrade/freqtrade/plugins/pairlist/StaticPairList.py'...
2021-03-27 12:31:05,580 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist AgeFilter from '/home/reivski/freqtrade/freqtrade/plugins/pairlist/AgeFilter.py'...
2021-03-27 12:31:05,593 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist RangeStabilityFilter from '/home/reivski/freqtrade/freqtrade/plugins/pairlist/rangestabilityfilter.py'...
2021-03-27 12:31:12,302 - AgeFilter - INFO - Validated 13 pairs.
2021-03-27 12:31:19,140 - freqtrade.resolvers.iresolver - INFO - Using resolved hyperopt bbrsi_opt from '/home/reivski/freqtrade/user_data/hyperopts/bbrsi_opt.py'...
2021-03-27 12:31:19,185 - freqtrade.resolvers.iresolver - INFO - Using resolved hyperoptloss SharpeHyperOptLoss from '/home/reivski/freqtrade/freqtrade/optimize/hyperopt_loss_sharpe.py'...
2021-03-27 12:31:19,192 - freqtrade.optimize.hyperopt - INFO - Using optimizer random state: 30457
2021-03-27 12:31:19,193 - freqtrade.data.history.history_utils - INFO - Using indicator startup period: 20 ...
2021-03-27 12:31:19,240 - numexpr.utils - INFO - NumExpr defaulting to 1 threads.
2021-03-27 12:31:19,433 - freqtrade.data.converter - INFO - Missing data fillup for ATOM/BTC: before: 717 - after: 718
2021-03-27 12:31:19,597 - freqtrade.data.converter - INFO - Missing data fillup for VET/BTC: before: 717 - after: 718
2021-03-27 12:31:19,755 - freqtrade.data.converter - INFO - Missing data fillup for BAT/BTC: before: 717 - after: 718
2021-03-27 12:31:19,905 - freqtrade.data.converter - INFO - Missing data fillup for BCH/BTC: before: 717 - after: 718
2021-03-27 12:31:20,081 - freqtrade.data.converter - INFO - Missing data fillup for EOS/BTC: before: 717 - after: 718
2021-03-27 12:31:20,417 - freqtrade.data.converter - INFO - Missing data fillup for ETH/BTC: before: 717 - after: 718
2021-03-27 12:31:20,551 - freqtrade.data.converter - INFO - Missing data fillup for IOTA/BTC: before: 717 - after: 718
2021-03-27 12:31:20,702 - freqtrade.data.converter - INFO - Missing data fillup for LINK/BTC: before: 717 - after: 718
2021-03-27 12:31:20,845 - freqtrade.data.converter - INFO - Missing data fillup for LTC/BTC: before: 717 - after: 718
2021-03-27 12:31:20,994 - freqtrade.data.converter - INFO - Missing data fillup for NEO/BTC: before: 717 - after: 718
2021-03-27 12:31:21,155 - freqtrade.data.converter - INFO - Missing data fillup for NXS/BTC: before: 717 - after: 718
2021-03-27 12:31:21,310 - freqtrade.data.converter - INFO - Missing data fillup for XRP/BTC: before: 717 - after: 718
2021-03-27 12:31:21,658 - freqtrade.data.converter - INFO - Missing data fillup for XTZ/BTC: before: 717 - after: 718
2021-03-27 12:31:21,679 - freqtrade.optimize.backtesting - INFO - Loading data from 2021-02-25 11:00:00 up to 2021-03-27 08:00:00 (29 days)..
2021-03-27 12:31:21,679 - freqtrade.configuration.timerange - WARNING - Moving start-date by 20 candles to account for startup time.
2021-03-27 12:31:21,718 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/reivski/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/home/reivski/freqtrade/freqtrade/commands/optimize_commands.py", line 83, in start_hyperopt
    hyperopt.start()
  File "/home/reivski/freqtrade/freqtrade/optimize/hyperopt.py", line 650, in start
    preprocessed = self.backtesting.strategy.ohlcvdata_to_dataframe(data)
  File "/home/reivski/freqtrade/freqtrade/strategy/interface.py", line 668, in ohlcvdata_to_dataframe
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair})
  File "/home/reivski/freqtrade/freqtrade/strategy/interface.py", line 668, in <dictcomp>
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair})
  File "/home/reivski/freqtrade/user_data/hyperopts/bbrsi_opt.py", line 53, in populate_indicators
    dataframe['bb_lowerband1'] = bollinger1=['lower']
  File "/home/reivski/freqtrade/.env/lib/python3.8/site-packages/pandas/core/frame.py", line 3163, in __setitem__
    self._set_item(key, value)
  File "/home/reivski/freqtrade/.env/lib/python3.8/site-packages/pandas/core/frame.py", line 3239, in _set_item
    value = self._sanitize_column(key, value)
  File "/home/reivski/freqtrade/.env/lib/python3.8/site-packages/pandas/core/frame.py", line 3896, in _sanitize_column
    value = sanitize_index(value, self.index)
  File "/home/reivski/freqtrade/.env/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 751, in sanitize_index
    raise ValueError(
ValueError: Length of values (1) does not match length of index (718)

**Comment by xmatthias** [comment]
Looks like a syntax error in your strategy -> `dataframe['bb_lowerband1'] = bollinger1=['lower']`

**Comment by Kaw11** [comment]
Yes, that solved the problem! Thank you once more for your help! I guess I was looking too deep in to this and missed looking right on the surface. Silly me!
