### ISSUE TITLE
ZeroDivisionError

### ISSUE THREAD

**Issue by harminoff** [freqtrade/freqtrade#4617]
## Describe your environment

  * Operating system: Raspian
  * Python Version: 3.9.2 (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2021.2 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

After a successful buy freqtrade sees purchase as 0 and gets a divide by zero error. Loops until forced close. FTX is showing that some BTC was purchased

### Relevant code exceptions or logs

2021-03-28 22:43:23,813 - apscheduler.scheduler - INFO - Scheduler has been shut down
2021-03-28 22:43:51,062 - freqtrade.loggers - INFO - Verbosity set to 0
2021-03-28 22:43:51,063 - freqtrade.configuration.configuration - INFO - Runmode set to live.
2021-03-28 22:43:51,064 - freqtrade.configuration.configuration - INFO - Parameter --db-url detected ...
2021-03-28 22:43:51,064 - freqtrade.configuration.configuration - INFO - Dry run is disabled
2021-03-28 22:43:51,065 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:////freqtrade/user_data/tradesv3.sqlite"
2021-03-28 22:43:51,065 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 10 ...
2021-03-28 22:43:51,067 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2021-03-28 22:43:51,067 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/ftx ...
2021-03-28 22:43:51,068 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2021-03-28 22:43:51,068 - freqtrade.configuration.check_exchange - WARNING - Exchange "ftx" is known to the the ccxt library, available for the bot, but not officially supported by the Freqtrade development team. It may work flawlessly (please report back) or have serious issues. Use it at your own discretion.
2021-03-28 22:43:51,069 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2021-03-28 22:43:51,069 - freqtrade.freqtradebot - INFO - Starting freqtrade 2021.2
2021-03-28 22:43:51,123 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy SimpleStrat from '/freqtrade/user_data/strategies/Quickie.py'...
2021-03-28 22:43:51,124 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'order_types' with value in config file: {'buy': 'limit', 'sell': 'limit', 'emergencysell': 'market', 'stoploss': 'market', 'stoploss_on_exchange': False, 'stoploss_on_exchange_interval': 30}.
2021-03-28 22:43:51,124 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USD.
2021-03-28 22:43:51,125 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: unlimited.
2021-03-28 22:43:51,125 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'buy': 15, 'sell': 15}.
2021-03-28 22:43:51,125 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'use_sell_signal' with value in config file: True.
2021-03-28 22:43:51,126 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'sell_profit_only' with value in config file: False.
2021-03-28 22:43:51,126 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ignore_roi_if_buy_signal' with value in config file: True.
2021-03-28 22:43:51,126 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'sell_profit_offset' with value in config file: 0.01.
2021-03-28 22:43:51,126 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 500}
2021-03-28 22:43:51,127 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 5m
2021-03-28 22:43:51,127 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.1
2021-03-28 22:43:51,127 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2021-03-28 22:43:51,127 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2021-03-28 22:43:51,128 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2021-03-28 22:43:51,128 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2021-03-28 22:43:51,128 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: True
2021-03-28 22:43:51,128 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'emergencysell': 'market', 'stoploss': 'market', 'stoploss_on_exchange': False, 'stoploss_on_exchange_interval': 30}
2021-03-28 22:43:51,129 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
2021-03-28 22:43:51,129 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USD
2021-03-28 22:43:51,129 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: unlimited
2021-03-28 22:43:51,129 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 66
2021-03-28 22:43:51,130 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'buy': 15, 'sell': 15}
2021-03-28 22:43:51,130 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_sell_signal: True
2021-03-28 22:43:51,130 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_only: False
2021-03-28 22:43:51,131 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_buy_signal: True
2021-03-28 22:43:51,131 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_offset: 0.01
2021-03-28 22:43:51,131 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2021-03-28 22:43:51,131 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2021-03-28 22:43:51,132 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2021-03-28 22:43:51,141 - freqtrade.exchange.exchange - INFO - Using CCXT 1.42.19
2021-03-28 22:43:51,141 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'hostname': 'ftx.us'}
2021-03-28 22:43:51,155 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'hostname': 'ftx.us', 'rateLimit': 500}
2021-03-28 22:43:51,169 - freqtrade.exchange.exchange - INFO - Using Exchange "FTX"
2021-03-28 22:43:51,829 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Ftx'...
2021-03-28 22:43:52,014 - freqtrade.wallets - INFO - Wallets synced.
2021-03-28 22:43:52,056 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist VolumePairList from '/freqtrade/freqtrade/plugins/pairlist/VolumePairList.py'...
2021-03-28 22:43:52,073 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist AgeFilter from '/freqtrade/freqtrade/plugins/pairlist/AgeFilter.py'...
2021-03-28 22:43:52,092 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist PriceFilter from '/freqtrade/freqtrade/plugins/pairlist/PriceFilter.py'...
2021-03-28 22:43:52,099 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist SpreadFilter from '/freqtrade/freqtrade/plugins/pairlist/SpreadFilter.py'...
2021-03-28 22:43:52,104 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist RangeStabilityFilter from '/freqtrade/freqtrade/plugins/pairlist/rangestabilityfilter.py'...
2021-03-28 22:43:52,209 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist ShuffleFilter from '/freqtrade/freqtrade/plugins/pairlist/ShuffleFilter.py'...
2021-03-28 22:43:52,210 - freqtrade.plugins.protectionmanager - INFO - No protection Handlers defined.
2021-03-28 22:43:52,396 - VolumePairList - INFO - Pair SOL/USD in your blacklist. Removing it from whitelist...
2021-03-28 22:43:52,397 - VolumePairList - INFO - Pair USDT/USD in your blacklist. Removing it from whitelist...
2021-03-28 22:43:52,397 - VolumePairList - INFO - Pair GRT/USD in your blacklist. Removing it from whitelist...
2021-03-28 22:43:52,398 - VolumePairList - INFO - Pair PAXG/USD in your blacklist. Removing it from whitelist...
2021-03-28 22:43:52,398 - VolumePairList - INFO - Pair DAI/USD in your blacklist. Removing it from whitelist...
2021-03-28 22:43:52,398 - VolumePairList - INFO - Pair CUSDT/USD in your blacklist. Removing it from whitelist...
2021-03-28 22:43:52,398 - VolumePairList - INFO - Pair AUD/USD in your blacklist. Removing it from whitelist...
2021-03-28 22:43:52,399 - VolumePairList - INFO - Pair BRZ/USD in your blacklist. Removing it from whitelist...
2021-03-28 22:43:52,399 - VolumePairList - INFO - Pair CAD/USD in your blacklist. Removing it from whitelist...
2021-03-28 22:43:52,399 - VolumePairList - INFO - Pair EUR/USD in your blacklist. Removing it from whitelist...
2021-03-28 22:43:52,399 - VolumePairList - INFO - Pair GBP/USD in your blacklist. Removing it from whitelist...
2021-03-28 22:43:52,400 - VolumePairList - INFO - Pair SGD/USD in your blacklist. Removing it from whitelist...
2021-03-28 22:43:52,400 - VolumePairList - INFO - Searching 10 pairs: ['BTC/USD', 'ETH/USD', 'SUSHI/USD', 'LTC/USD', 'TRX/USD', 'LINK/USD', 'UNI/USD', 'BCH/USD', 'DOGE/USD', 'BAT/USD']
2021-03-28 22:43:57,544 - AgeFilter - INFO - Validated 10 pairs.
2021-03-28 22:43:57,545 - SpreadFilter - INFO - Removed SUSHI/USD from whitelist, because spread 1.352% > 1.0%
2021-03-28 22:43:57,545 - SpreadFilter - INFO - Removed UNI/USD from whitelist, because spread 1.232% > 1.0%
2021-03-28 22:44:01,603 - freqtrade.rpc.rpc_manager - INFO - Enabling rpc.telegram ...
2021-03-28 22:44:03,478 - apscheduler.scheduler - INFO - Scheduler started
2021-03-28 22:44:05,216 - freqtrade.rpc.telegram - INFO - rpc.telegram is listening for following commands: [['status'], ['profit'], ['balance'], ['start'], ['stop'], ['forcesell'], ['forcebuy'], ['trades'], ['delete'], ['performance'], ['stats'], ['daily'], ['count'], ['locks'], ['reload_config', 'reload_conf'], ['show_config', 'show_conf'], ['stopbuy'], ['whitelist'], ['blacklist'], ['logs'], ['edge'], ['help'], ['version']]
2021-03-28 22:44:05,218 - freqtrade.rpc.rpc_manager - INFO - Enabling rpc.api_server
2021-03-28 22:44:06,463 - freqtrade.rpc.api_server.webserver - INFO - Starting HTTP Server at 0.0.0.0:8080
2021-03-28 22:44:06,464 - freqtrade.rpc.api_server.webserver - WARNING - SECURITY WARNING - Local Rest Server listening to external connections
2021-03-28 22:44:06,464 - freqtrade.rpc.api_server.webserver - WARNING - SECURITY WARNING - This is insecure please set to your loopback,e.g 127.0.0.1 in config.json
2021-03-28 22:44:06,464 - freqtrade.rpc.api_server.webserver - INFO - Starting Local Rest Server.
2021-03-28 22:44:06,506 - uvicorn.error - INFO - Started server process [1]
2021-03-28 22:44:06,508 - uvicorn.error - INFO - Waiting for application startup.
2021-03-28 22:44:06,508 - uvicorn.error - INFO - Application startup complete.
2021-03-28 22:44:06,510 - uvicorn.error - INFO - Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
2021-03-28 22:44:06,511 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'running'}
2021-03-28 22:44:07,517 - freqtrade.worker - INFO - Changing state to: RUNNING
2021-03-28 22:44:07,519 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': "*Exchange:* `ftx`\n*Stake per trade:* `unlimited USD`\n*Minimum ROI:* `{'0': 500}`\n*Stoploss:* `-0.1`\n*Timeframe:* `5m`\n*Strategy:* `SimpleStrat`"}
2021-03-28 22:44:07,804 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': "Searching for USD pairs to buy and sell based on [{'VolumePairList': 'VolumePairList - top 10 volume pairs.'}, {'AgeFilter': 'AgeFilter - Filtering pairs with age less than 10 days.'}, {'PriceFilter': 'PriceFilter - Filtering pairs priced below 1.0%.'}, {'SpreadFilter': 'SpreadFilter - Filtering pairs with ask/bid diff above 1.0%.'}, {'RangeStabilityFilter': 'RangeStabilityFilter - Filtering pairs with rate of change below 0.01 over the last days.'}, {'ShuffleFilter': 'ShuffleFilter - Shuffling pairs, seed = 42.'}]"}
2021-03-28 22:44:08,169 - freqtrade.persistence.models - INFO - Found open trade: Trade(id=6, pair=BAT/USD, amount=6.00000000, open_rate=1.12180000, open_since=2021-03-28 14:50:07)
2021-03-28 22:44:08,170 - freqtrade.persistence.models - INFO - Found open trade: Trade(id=7, pair=LTC/USD, amount=0.04000000, open_rate=185.56000000, open_since=2021-03-28 15:25:09)
2021-03-28 22:44:08,171 - freqtrade.persistence.models - INFO - Found open trade: Trade(id=8, pair=TRX/USD, amount=136.00000000, open_rate=0.06437250, open_since=2021-03-28 16:35:09)
2021-03-28 22:44:08,172 - freqtrade.persistence.models - INFO - Found open trade: Trade(id=9, pair=LINK/USD, amount=0.30000000, open_rate=26.52600000, open_since=2021-03-28 22:35:08)
2021-03-28 22:44:08,172 - freqtrade.persistence.models - INFO - Found open trade: Trade(id=10, pair=BTC/USD, amount=0.00000000, open_rate=55419.00000000, open_since=2021-03-28 22:35:10)
2021-03-28 22:44:08,187 - freqtrade.freqtradebot - INFO - Updating 1 open orders.
2021-03-28 22:44:08,341 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=9, pair=LINK/USD, amount=0.30000000, open_rate=26.52600000, open_since=2021-03-28 22:35:08)
2021-03-28 22:44:08,400 - VolumePairList - INFO - Searching 10 pairs: ['BTC/USD', 'ETH/USD', 'LTC/USD', 'TRX/USD', 'LINK/USD', 'BCH/USD', 'DOGE/USD', 'BAT/USD']
2021-03-28 22:44:12,279 - numexpr.utils - INFO - NumExpr defaulting to 4 threads.
2021-03-28 22:44:13,626 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=9, pair=LINK/USD, amount=0.30000000, open_rate=26.52600000, open_since=2021-03-28 22:35:08)
2021-03-28 22:44:14,149 - freqtrade.commands.trade_commands - ERROR - float division by zero
2021-03-28 22:44:14,150 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker.run()
  File "/freqtrade/freqtrade/worker.py", line 74, in run
    state = self._worker(old_state=state)
  File "/freqtrade/freqtrade/worker.py", line 111, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
  File "/freqtrade/freqtrade/worker.py", line 132, in _throttle
    result = func(*args, **kwargs)
  File "/freqtrade/freqtrade/worker.py", line 145, in _process_running
    self.freqtrade.process()
  File "/freqtrade/freqtrade/freqtradebot.py", line 184, in process
    self.exit_positions(trades)
  File "/freqtrade/freqtrade/freqtradebot.py", line 693, in exit_positions
    if trade.open_order_id is None and trade.is_open and self.handle_trade(trade):
  File "/freqtrade/freqtrade/freqtradebot.py", line 799, in handle_trade
    if self._check_and_execute_sell(trade, sell_rate, buy, sell):
  File "/freqtrade/freqtrade/freqtradebot.py", line 936, in _check_and_execute_sell
    force_stoploss=self.edge.stoploss(trade.pair) if self.edge else 0
  File "/freqtrade/freqtrade/strategy/interface.py", line 514, in should_sell
    current_profit = trade.calc_profit_ratio(current_rate)
  File "/freqtrade/freqtrade/persistence/models.py", line 554, in calc_profit_ratio
    profit_ratio = (close_trade_value / self.open_trade_value) - 1
ZeroDivisionError: float division by zero

**Comment by xmatthias** [comment]
We'll need the log of the time the order was placed / filled. 
The exception you're showing only shows the symptom, not how it got to this state.
While catching the problem is pretty simple, the state is still undefined as `open_trade_value` cannot really be 0 if the order was correctly filled / registered as fill.

so i assume something went wrong at the "order fill" point - so to really debug the problem (not just fix the exception), the logs from "fill time" are essential.

**Comment by harminoff** [comment]
Sorry about that. This is the log further up, looks like it has to do with adding the fee. Let me know if there is anything else I could provide.

```
2021-03-28 22:38:16,123 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=9, pair=LINK/USD, amount=0.30000000, open_rate=26.52600000, open_since=2021-03-28 22:35:08)
2021-03-28 22:38:16,267 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=10, pair=BTC/USD, amount=0.00010000, open_rate=55419.00000000, open_since=2021-03-28 22:35:10)
2021-03-28 22:38:16,547 - freqtrade.wallets - INFO - Wallets synced.
2021-03-28 22:38:16,548 - freqtrade.freqtradebot - INFO - Applying fee on amount for Trade(id=10, pair=BTC/USD, amount=0.00010000, open_rate=55419.00000000, open_since=2021-03-28 22:35:10) (from 0.0001 to 0.0).
2021-03-28 22:38:16,549 - freqtrade.persistence.models - INFO - Updating trade (id=10) ...
2021-03-28 22:38:16,550 - freqtrade.persistence.models - INFO - LIMIT_BUY has been fulfilled for Trade(id=10, pair=BTC/USD, amount=0.00000000, open_rate=55419.00000000, open_since=2021-03-28 22:35:10).
2021-03-28 22:38:17,096 - freqtrade.commands.trade_commands - ERROR - float division by zero
2021-03-28 22:38:17,097 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker.run()
  File "/freqtrade/freqtrade/worker.py", line 74, in run
    state = self._worker(old_state=state)
  File "/freqtrade/freqtrade/worker.py", line 111, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
  File "/freqtrade/freqtrade/worker.py", line 132, in _throttle
    result = func(*args, **kwargs)
  File "/freqtrade/freqtrade/worker.py", line 145, in _process_running
    self.freqtrade.process()
  File "/freqtrade/freqtrade/freqtradebot.py", line 184, in process
    self.exit_positions(trades)
  File "/freqtrade/freqtrade/freqtradebot.py", line 693, in exit_positions
    if trade.open_order_id is None and trade.is_open and self.handle_trade(trade):
  File "/freqtrade/freqtrade/freqtradebot.py", line 799, in handle_trade
    if self._check_and_execute_sell(trade, sell_rate, buy, sell):
  File "/freqtrade/freqtrade/freqtradebot.py", line 936, in _check_and_execute_sell
    force_stoploss=self.edge.stoploss(trade.pair) if self.edge else 0
  File "/freqtrade/freqtrade/strategy/interface.py", line 514, in should_sell
    current_profit = trade.calc_profit_ratio(current_rate)
  File "/freqtrade/freqtrade/persistence/models.py", line 554, in calc_profit_ratio
    profit_ratio = (close_trade_value / self.open_trade_value) - 1
ZeroDivisionError: float division by zero

```

**Comment by xmatthias** [comment]
i'd say the log does not make sense (which is not your fault ...), seems like the amount was "updated" to 0 ...

can you give me anything you have for the affected trade (how much was the trade /order on the exchange, how much of that trade was bought)?
Also, i'll need the database rows from both trades and orders table for this trade (trade-id 10).

you should be able to get this with:
```sql
.headers on
-- The above assumes sqlite shell is used
select * from trades where id = 10;
select * from orders where ft_trade_id = 10;
```

The 2nd query (orders table) will give you an order-id for the order that executed (column order_id).

For this, i'd need output of the following script (it'll need your exchange keys - make sure to NOT post these here):

``` python
import ccxt
exchange = ccxt.binance({'apiKey': '<yourApiKey>', 'secret': '<yoursecret>' })
res = exchange.fetch_order(order_id, 'BTC/USDT)
print(res)
```

**Comment by xmatthias** [comment]
Since there's been no further feedback, i'll fix this by addressing the symptom (avoid the Exception) rather than adressing the root cause.

Should you come back to this issue and be able to provide the above information, i'd still be grateful as it'll give us an opportunity to fix the rootcause for this.
