### ISSUE TITLE
Orderbook usage and a unexpected error causing no OHLCV data analyzis 

### ISSUE THREAD

**Issue by SoupBoris** [freqtrade/freqtrade#4632]
## Environment

  *** Operating system:  Ubuntu 18.04
  * Python Version: Python 3.8.8
  * CCXT version:  1.43.89
  * Freqtrade Version: freqtrade develop-39bfe5e1**
  
## Question

I am having an error displaying the following error code when excecuting the bot on a dry run. Since my strategy uses the dp.orderbook method, I can not test it using backtesting.

The relevant code snipet is the following 

```
# first check if dataprovider is available
        if self.dp:
            if self.dp.runmode in ('live', 'dry_run'):
                ob = self.dp.orderbook(metadata['pair'], 4)
                dataframe['best_bid'] = ob['bids'][0][0]
                dataframe['best_ask'] = ob['asks'][0][0]
                dataframe['bid_size'] = ob['bids'][0][1]
                dataframe['ask_size'] = ob['asks'][0][1]
```
The error code in the terminal is as follows:

```
2021-03-30 01:10:28,955 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error 'bid_size' calling <bound method IStrategy._analyze_ticker_internal of <MarketMaking.MarketMaking object at 0x7f894d430280>>
Traceback (most recent call last):
  File "/home/sebastian/projects/HEDGEFUND/freqtrade/.env/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'bid_size'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sebastian/projects/HEDGEFUND/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 17, in wrapper
    return f(*args, **kwargs)
  File "/home/sebastian/projects/HEDGEFUND/freqtrade/freqtrade/strategy/interface.py", line 379, in _analyze_ticker_internal
    dataframe = self.analyze_ticker(dataframe, metadata)
  File "/home/sebastian/projects/HEDGEFUND/freqtrade/freqtrade/strategy/interface.py", line 359, in analyze_ticker
    dataframe = self.advise_buy(dataframe, metadata)
  File "/home/sebastian/projects/HEDGEFUND/freqtrade/freqtrade/strategy/interface.py", line 702, in advise_buy
    return self.populate_buy_trend(dataframe, metadata)
  File "/home/sebastian/projects/HEDGEFUND/freqtrade/user_data/strategies/marketmaging.py", line 111, in populate_buy_trend
    dataframe['bid_size'] > dataframe['ask_size']*2
  File "/home/sebastian/projects/HEDGEFUND/freqtrade/.env/lib/python3.8/site-packages/pandas/core/frame.py", line 3024, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/sebastian/projects/HEDGEFUND/freqtrade/.env/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: 'bid_size'
2021-03-30 01:10:28,958 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair TROY/BTC: 'bid_size'
2021-03-30 01:10:28,972 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error 'bid_size' calling <bound method IStrategy._analyze_ticker_internal of <MarketMaking.MarketMaking object at 0x7f894d430280>>
Traceback (most recent call last):
  File "/home/sebastian/projects/HEDGEFUND/freqtrade/.env/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'bid_size'`

```
...

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sebastian/projects/HEDGEFUND/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 17, in wrapper
    return f(*args, **kwargs)
  File "/home/sebastian/projects/HEDGEFUND/freqtrade/freqtrade/strategy/interface.py", line 379, in _analyze_ticker_internal
    dataframe = self.analyze_ticker(dataframe, metadata)
  File "/home/sebastian/projects/HEDGEFUND/freqtrade/freqtrade/strategy/interface.py", line 359, in analyze_ticker
    dataframe = self.advise_buy(dataframe, metadata)
  File "/home/sebastian/projects/HEDGEFUND/freqtrade/freqtrade/strategy/interface.py", line 702, in advise_buy
    return self.populate_buy_trend(dataframe, metadata)
  File "/home/sebastian/projects/HEDGEFUND/freqtrade/user_data/strategies/marketmaging.py", line 111, in populate_buy_trend
    dataframe['bid_size'] > dataframe['ask_size']*2
  File "/home/sebastian/projects/HEDGEFUND/freqtrade/.env/lib/python3.8/site-packages/pandas/core/frame.py", line 3024, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/sebastian/projects/HEDGEFUND/freqtrade/.env/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: 'bid_size'
2021-03-30 01:10:29,016 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair SNGLS/BTC: 'bid_size'
2021-03-30 01:10:29,042 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair TROY/BTC
2021-03-30 01:10:29,048 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair PHB/BTC
2021-03-30 01:10:29,056 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair SC/BTC
2021-03-30 01:10:29,067 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair CKB/BTC
2021-03-30 01:10:29,071 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair SNGLS/BTC
```

It then repeats over and over again. Help! D:

**Comment by xmatthias** [comment]
I think this code will fail and will therefore not assign it - like - at all.

`if self.dp.runmode in ('live', 'dry_run'):`

the [documentation](https://www.freqtrade.io/en/latest/strategy-customization/#orderbookpair-maximum) is pretty clear in specifying that this should be `if self.dp.runmode.value in ('live', 'dry_run'):` ...

**Comment by SoupBoris** [comment]
I changed that line, indeed I have must missed it from the documentation. I now recieve a different error. Progress! I believe I can't leave the sell trend empty, but I guess the documentation has the answer so off to reading. Much appreciated!!!
