### ISSUE TITLE
Hyperoptimization Fatal exception

### ISSUE THREAD

**Issue by aristosv** [freqtrade/freqtrade#4639]
## Describe your environment

Operating system: Debian 10
Python Version: Python 3.7.3
CCXT version: ccxt==1.43.89
Freqtrade Version: freqtrade develop-7adfa0cf
  
## Your question

I am trying to run a hyperoptimization with [AverageHyperopt](https://github.com/freqtrade/freqtrade-strategies/blob/master/user_data/hyperopts/AverageHyperopt.py) and [MACDStrategy_crossed](https://github.com/freqtrade/freqtrade-strategies/blob/master/user_data/strategies/berlinguyinca/MACDStrategy_crossed.py) strategy.

This is the command I'm using
`freqtrade hyperopt -c config.json -s $strategy --hyperopt $hyperopt --hyperopt-loss OnlyProfitHyperOptLoss -e 10000 --spaces default`

It seems to be hitting the CPU hard, because everything becomes slow on the machine, but eventually I get an error saying:

```
2021-03-31 13:52:28,864 - freqtrade.optimize.backtesting - INFO - Loading data from 2020-03-30 00:00:00 up to 2021-03-30 04:25:00 (365 days)..
2021-03-31 13:52:28,864 - freqtrade.configuration.timerange - WARNING - Moving start-date by 0 candles to account for startup time.
2021-03-31 13:52:51,193 - freqtrade.optimize.hyperopt - INFO - Hyperopting with data from 2020-03-30 00:00:00 up to 2021-03-30 04:25:00 (365 days)..
2021-03-31 13:53:08,662 - freqtrade.optimize.hyperopt - INFO - Found 40 CPU cores. Let's make them scream!
2021-03-31 13:53:08,662 - freqtrade.optimize.hyperopt - INFO - Number of parallel jobs set as: -1
2021-03-31 13:53:08,667 - freqtrade.optimize.hyperopt_interface - INFO - Min roi table: {0: 0.03, 10: 0.02, 20: 0.01, 30: 0}
2021-03-31 13:53:08,668 - freqtrade.optimize.hyperopt_interface - INFO - Max roi table: {0: 0.31, 40: 0.11, 100: 0.04, 220: 0}
2021-03-31 13:53:08,937 - freqtrade.optimize.hyperopt - INFO - Effective number of parallel workers used: 40

2021-03-31 13:58:55,565 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/root/freqtrade_USDT/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/root/freqtrade_USDT/freqtrade/commands/optimize_commands.py", line 86, in start_hyperopt
    hyperopt.start()
  File "/root/freqtrade_USDT/freqtrade/optimize/hyperopt.py", line 449, in start
    f_val = self.run_optimizer_parallel(parallel, asked, i)
  File "/root/freqtrade_USDT/freqtrade/optimize/hyperopt.py", line 367, in run_optimizer_parallel
    wrap_non_picklable_objects(self.generate_optimizer))(v, i) for v in asked)
  File "/root/freqtrade_USDT/.env/lib/python3.7/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/root/freqtrade_USDT/.env/lib/python3.7/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/root/freqtrade_USDT/.env/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

The exit codes of the workers are {SIGKILL(-9)}
```

Any idea what could be causing this?

**Comment by xmatthias** [comment]
Your system killed the process because it was out of memory.

You should also find traces for this in the system logs (usually journald/journalctl) .

best make sure to reduce the amount of data, by either using a smaller pairlist, longer timeframe, smaller timerange or by limiting the parallel cpu's (`-j `).

**Comment by aristosv** [comment]
I tried -j 30, -j 20 and -j 10 but I keep getting the same error. Keep in mind the machine has 40 CPU cores and 32GB or RAM. I'm guessing my only option is to reduce the amount of data. The results won't be as good though right?

```
2021-04-01 05:17:34,133 - freqtrade.optimize.backtesting - INFO - Loading data from 2020-03-30 00:00:00 up to 2021-03-30 04:25:00 (365 days)..
2021-04-01 05:17:34,133 - freqtrade.configuration.timerange - WARNING - Moving start-date by 0 candles to account for startup time.
2021-04-01 05:17:56,697 - freqtrade.optimize.hyperopt - INFO - Hyperopting with data from 2020-03-30 00:00:00 up to 2021-03-30 04:25:00 (365 days)..
2021-04-01 05:18:14,399 - freqtrade.optimize.hyperopt - INFO - Found 40 CPU cores. Let's make them scream!
2021-04-01 05:18:14,399 - freqtrade.optimize.hyperopt - INFO - Number of parallel jobs set as: 10
2021-04-01 05:18:14,404 - freqtrade.optimize.hyperopt_interface - INFO - Min roi table: {0: 0.03, 10: 0.02, 20: 0.01, 30: 0}
2021-04-01 05:18:14,405 - freqtrade.optimize.hyperopt_interface - INFO - Max roi table: {0: 0.31, 40: 0.11, 100: 0.04, 220: 0}
2021-04-01 05:18:14,660 - freqtrade.optimize.hyperopt - INFO - Effective number of parallel workers used: 10

2021-04-01 05:20:56,285 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/root/freqtrade_USDT/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/root/freqtrade_USDT/freqtrade/commands/optimize_commands.py", line 86, in start_hyperopt
    hyperopt.start()
  File "/root/freqtrade_USDT/freqtrade/optimize/hyperopt.py", line 449, in start
    f_val = self.run_optimizer_parallel(parallel, asked, i)
  File "/root/freqtrade_USDT/freqtrade/optimize/hyperopt.py", line 367, in run_optimizer_parallel
    wrap_non_picklable_objects(self.generate_optimizer))(v, i) for v in asked)
  File "/root/freqtrade_USDT/.env/lib/python3.7/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/root/freqtrade_USDT/.env/lib/python3.7/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/root/freqtrade_USDT/.env/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

The exit codes of the workers are {SIGKILL(-9)}
```

**Comment by xmatthias** [comment]
well keep in mind that for each parallel process, the data needs to be in memory at least once.

It's however difficult to properly calculate the size, as it'll heavily depend on the amount of indicators (and timeframe) you're using.

More data does however not always mean better results.

**Comment by aristosv** [comment]
thanks
