### ISSUE TITLE
bot bought 37dollers of BNB but it never can sell it! Binance

### ISSUE THREAD

**Issue by mablue** [freqtrade/freqtrade#4710]
## Describe your environment

  * Operating system: UBUNTU 20
  * Python Version: Python 3.8.5
  * CCXT version: ccxt==1.45.44
  * Freqtrade Version: freqtrade develop-00d8f3a4

I always have problem with binance exchange when I want to sell the BNB!
I can sell it in the exchange and I think it can buy but it cant sell and it bought .

![Screenshot_2021-04-10 Bitcoin Exchange Cryptocurrency Exchange Binance](https://user-images.githubusercontent.com/5004900/114281613-8721c600-9a54-11eb-975f-10c989583227.png)

```
2021-04-10 23:06:59,520 - freqtrade.plugins.pairlistmanager - WARNING - Pair XLMDOWN/USDT in your blacklist. Removing it from whitelist...                                                                 
2021-04-10 23:06:59,995 - freqtrade.wallets - INFO - Wallets synced.                                                                                                                                       
2021-04-10 23:07:00,001 - freqtrade.rpc.telegram - ERROR - Exception occurred within Telegram module                                                                                                       
Traceback (most recent call last):                                                                                                                                                                         
  File "/root/freqtrade/freqtrade/rpc/telegram.py", line 61, in wrapper                                                                                                                                    
    return command_handler(self, *args, **kwargs)                                                                                                                                                          
  File "/root/freqtrade/freqtrade/rpc/telegram.py", line 607, in _forcesell                                                                                                                                
    msg = self._rpc._rpc_forcesell(trade_id)                                                                                                                                                               
  File "/root/freqtrade/freqtrade/rpc/rpc.py", line 563, in _rpc_forcesell                                                                                                                                 
    _exec_forcesell(trade)                                                                                                                                                                                 
  File "/root/freqtrade/freqtrade/rpc/rpc.py", line 540, in _exec_forcesell                                                                                                                                
    self._freqtrade.execute_sell(trade, current_rate, SellType.FORCE_SELL)                                                                                                                                 
  File "/root/freqtrade/freqtrade/freqtradebot.py", line 1175, in execute_sell                                                                                                                             
    amount = self._safe_sell_amount(trade.pair, trade.amount)                                                                                                                                              
  File "/root/freqtrade/freqtrade/freqtradebot.py", line 1139, in _safe_sell_amount                                                                                                                        
    f"Not enough amount to sell. Trade-amount: {amount}, Wallet: {wallet_amount}")                                                                                                                         
freqtrade.exceptions.DependencyException: Not enough amount to sell. Trade-amount: 0.116, Wallet: 0.08927749                                                                                               
2021-04-10 23:07:00,008 - freqtrade.rpc.telegram - INFO - Executing handler: _help for chat_id: 1187109657                                                                                                 
2021-04-10 23:07:00,572 - freqtrade.freqtradebot - INFO - Executing Sell for BNB/USDT. Reason: roi                                                                                                         
2021-04-10 23:07:01,088 - freqtrade.wallets - INFO - Wallets synced.                                                                                                                                       
2021-04-10 23:07:01,088 - freqtrade.freqtradebot - WARNING - Unable to sell trade BNB/USDT: Not enough amount to sell. Trade-amount: 0.116, Wallet: 0.08927749                                             
2021-04-10 23:07:46,147 - freqtrade.rpc.telegram - INFO - Executing handler: _delete_trade for chat_id: 1187109657                                                                                         
2021-04-10 23:07:50,790 - freqtrade.worker - INFO - Bot heartbeat. PID=9369, version='develop-ee82d36b', state='RUNNING'                                                                                   
2021-04-10 23:07:50,811 - freqtrade.plugins.pairlistmanager - WARNING - Pair TUSD/USDT in your blacklist. Removing it from whitelist...                                                                    
2021-04-10 23:07:50,811 - freqtrade.plugins.pairlistmanager - WARNING - Pair PAX/USDT in your blacklist. Removing it from whitelist...
2021-04-10 23:07:50,811 - freqtrade.plugins.pairlistmanager - WARNING - Pair USDC/USDT in your blacklist. Removing it from whitelist...

```
I searched #1371 but its not BNB. my error just happens on bnb

**Comment by xmatthias** [comment]
I kinda hate to be the guy pointing out that it's [covered by the documentation](https://www.freqtrade.io/en/latest/exchanges/#blacklists) - but it is, specifically for binance.

If your bot buys BNB (and you don't own more BNB) - the other trades will use this trade's balance to pay fees (unless you disable BNB fees - which you really shouldn't as they're cheaper).

as a consequence, the bot thinks it owns 0.116 BNB - but it only finds 0.089 BNB in the wallet (other trades consumed the difference as fees) - and when it fails to find the amount it bought, it fails (there's many reasons for this - so once the difference becomes too high, freqtrade prefers to "fail" and require user intervention.

**Comment by mablue** [comment]
Thanks so what will I do? I will delete and sell it manually?(some times i forgot to check the bot log for some days!) all time it happen for me.and i need to use bnb fees cuz of cheaper prices...

**Comment by xmatthias** [comment]
Best delete the trade from the database (your logs suggest that you did that already) - and then sell the amount manually.
I'd however also keep "some" BNB - to pay the fees.

You'll then want to blacklist BNB/<yourstake> - to avoid the bot from buying BNB again in the future.

**Comment by mablue** [comment]
Ok tnx, If I keep some bnb separated in my wallet it will work I think.

**Comment by xmatthias** [comment]
Yes, that's what you'll want to do, and it's also described in the documentation that way.

**Comment by mablue** [comment]
sorry I will never report a bug before reading full of the documentation .
