### ISSUE TITLE
Docker quickstart guide fails on with `FileNotFoundError:` when I try to run `docker-compose pull`

### ISSUE THREAD

**Issue by samgermain** [freqtrade/freqtrade#4718]
## Describe your environment

  * Operating system: MacOS Mojave v 10.14.6
  * Python Version: 3.9.4
  * CCXT version: 1.47.46
  * Freqtrade Version: N/A (not installed yet)
  
  -------------
  
  I'm trying to run the [quickstart with docker](https://www.freqtrade.io/en/latest/docker_quickstart/) from the freqtrade documention.
  
  I run these 3 first steps fine

```  
mkdir ft_userdata
cd ft_userdata/
# Download the docker-compose file from the repository
curl https://raw.githubusercontent.com/freqtrade/freqtrade/stable/docker-compose.yml -o docker-compose.yml
```
  
but when I get to the step where I try to run `docker-compose pull` I get the following error and output
  
```
Traceback (most recent call last):
  File "/usr/local/Cellar/docker-compose/1.29.0/libexec/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/Cellar/docker-compose/1.29.0/libexec/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1299, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1248, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1008, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 948, in send
    self.connect()
  File "/usr/local/Cellar/docker-compose/1.29.0/libexec/lib/python3.9/site-packages/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/docker-compose/1.29.0/libexec/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/Cellar/docker-compose/1.29.0/libexec/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/Cellar/docker-compose/1.29.0/libexec/lib/python3.9/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/Cellar/docker-compose/1.29.0/libexec/lib/python3.9/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/Cellar/docker-compose/1.29.0/libexec/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/Cellar/docker-compose/1.29.0/libexec/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1299, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1248, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1008, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 948, in send
    self.connect()
  File "/usr/local/Cellar/docker-compose/1.29.0/libexec/lib/python3.9/site-packages/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/docker-compose/1.29.0/libexec/lib/python3.9/site-packages/docker/api/client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/usr/local/Cellar/docker-compose/1.29.0/libexec/lib/python3.9/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/usr/local/Cellar/docker-compose/1.29.0/libexec/lib/python3.9/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/Cellar/docker-compose/1.29.0/libexec/lib/python3.9/site-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/local/Cellar/docker-compose/1.29.0/libexec/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/Cellar/docker-compose/1.29.0/libexec/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/Cellar/docker-compose/1.29.0/libexec/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/Cellar/docker-compose/1.29.0/libexec/lib/python3.9/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.29.0', 'console_scripts', 'docker-compose')())
  File "/usr/local/Cellar/docker-compose/1.29.0/libexec/lib/python3.9/site-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/usr/local/Cellar/docker-compose/1.29.0/libexec/lib/python3.9/site-packages/compose/cli/main.py", line 199, in perform_command
    project = project_from_options('.', options)
  File "/usr/local/Cellar/docker-compose/1.29.0/libexec/lib/python3.9/site-packages/compose/cli/command.py", line 60, in project_from_options
    return get_project(
  File "/usr/local/Cellar/docker-compose/1.29.0/libexec/lib/python3.9/site-packages/compose/cli/command.py", line 152, in get_project
    client = get_client(
  File "/usr/local/Cellar/docker-compose/1.29.0/libexec/lib/python3.9/site-packages/compose/cli/docker_client.py", line 41, in get_client
    client = docker_client(
  File "/usr/local/Cellar/docker-compose/1.29.0/libexec/lib/python3.9/site-packages/compose/cli/docker_client.py", line 170, in docker_client
    client = APIClient(use_ssh_client=not use_paramiko_ssh, **kwargs)
  File "/usr/local/Cellar/docker-compose/1.29.0/libexec/lib/python3.9/site-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/usr/local/Cellar/docker-compose/1.29.0/libexec/lib/python3.9/site-packages/docker/api/client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
```

**Comment by xmatthias** [comment]
While the error itself is quite nested and difficult to digest ... 
check if your docker daemon is running (best with `docker ps` or `docker info`).

This error is not directly related to freqtrade, but to docker-compose being unable to connect to docker.
While we try to guide people through - having docker installed (and working!) is one of the prerequisites for that guide.

**Comment by samgermain** [comment]
@xmatthias 

$ docker ps
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
$ docker info
Client:
 Context:    default
 Debug Mode: false

Server:
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
errors pretty printing info

**Comment by xmatthias** [comment]
See, docker is not running.
you can try `sudo systemctl start docker` to get it started (and maybe `sudo systemctl enable docker` to have it start automatically.

If that doesn't work, please use the docker support channels (or google?) to get your docker-problems fixed.

**Comment by samgermain** [comment]
I don't know how to use docker, I'll just stick to my non-docker methods

**Comment by xmatthias** [comment]
in the end, it's pretty simple - but it requires the docker daemon to be up and running (which it's not in your case).

it's got nothing to do with freqtrade per se - you'll encounter this error with every other dockerfile / project you'll use, as long as the daemon is not up and running.

The above commands would help you start that ... but it's your decision to use or not use docker.

**Comment by mcfloli** [comment]
I had the same error.
I found this solution, which fixed it for me:
`
sudo gpasswd -a $USER docker
newgrp docker
`
In case anyone else runs into the same problem.
