### ISSUE TITLE
Profit Calculation / ERROR - float division by zero

### ISSUE THREAD

**Issue by scysys** [freqtrade/freqtrade#4764]
## Describe your environment

  * Operating system: Ubuntu 20.04
  * Python Version: Python 3.8.5
  * CCXT version: ccxt==1.47.47
  * Freqtrade Version: freqtrade develop-982f572

## Describe the problem:

The profit calculation seems to be the error here.

### Relevant code exceptions or logs
  ```
2021-04-20 08:01:25,941 - freqtrade.commands.trade_commands - ERROR - float division by zero
2021-04-20 08:01:25,942 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/root/tradingbot/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker.run()
  File "/root/tradingbot/freqtrade/worker.py", line 74, in run
    state = self._worker(old_state=state)
  File "/root/tradingbot/freqtrade/worker.py", line 111, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
  File "/root/tradingbot/freqtrade/worker.py", line 132, in _throttle
    result = func(*args, **kwargs)
  File "/root/tradingbot/freqtrade/worker.py", line 145, in _process_running
    self.freqtrade.process()
  File "/root/tradingbot/freqtrade/freqtradebot.py", line 184, in process
    self.exit_positions(trades)
  File "/root/tradingbot/freqtrade/freqtradebot.py", line 695, in exit_positions
    if trade.open_order_id is None and trade.is_open and self.handle_trade(trade):
  File "/root/tradingbot/freqtrade/freqtradebot.py", line 807, in handle_trade
    if self._check_and_execute_sell(trade, sell_rate, buy, sell):
  File "/root/tradingbot/freqtrade/freqtradebot.py", line 942, in _check_and_execute_sell
    should_sell = self.strategy.should_sell(
  File "/root/tradingbot/freqtrade/strategy/interface.py", line 516, in should_sell
    current_profit = trade.calc_profit_ratio(current_rate)
  File "/root/tradingbot/freqtrade/persistence/models.py", line 550, in calc_profit_ratio
    profit_ratio = (close_trade_value / self.open_trade_value) - 1
ZeroDivisionError: float division by zero
  ```

**Comment by xmatthias** [comment]
This is technically a duplicate of #4617, which however got no further answers, so further investigation is stalled for now.

there will be one trade in the database with `open_trade_value` set to 0.

To further investigate the cause for this (you're seeing the impact - but it's not showing the real cause), we'll need a bit more info

From the database: 
``` sql
.headers on
-- The above assumes sqlite shell is used
select * from trades where open_trade_value = 0;
-- Get trade-id from above
select * from orders where ft_trade_id = <id>;
```

The 2nd query (orders table) will give you an order-id for the order that executed (column order_id).

Based on this, please execute the following in a python shell (within the freqtrade environment).
This assumes you're using binance - if you use another exchange please adjust accordingly.

``` python
import ccxt
exchange = ccxt.binance({'apiKey': '<yourApiKey>', 'secret': '<yoursecret>' })
res = exchange.fetch_order(order_id, 'BTC/USDT)
print(res)
```

**Comment by scysys** [comment]
Did not found the other entry. Sorry.

Anyway after opened this. I manually manipulated the profit calculation inside models.py that freqtrade is starting an opening sell orders for all trades. Freqtrade was then able to open sell orders for each trade on binance. After that i cleaned the DB. So i cant help with this info anymore :(

Next time when this happens. I will update this.

**Comment by xmatthias** [comment]
if you still remember the trade-id, then fetching the order should still be possible.
this way, it'll help noone ...
