### ISSUE TITLE
Problems with real money  cant open new trade 

### ISSUE THREAD

**Issue by HAGAI123** [freqtrade/freqtrade#4787]
Hello i am using in windows and Python 3.8.8 , I have a few questions ,
I ran in dry mode and everything was fine.
And that I wanted to switch to real money he makes me such mistakes

2021-04-22 15:39:33,385 - freqtrade.wallets - INFO - Wallets synced.
2021-04-22 15:39:33,404 - freqtrade.freqtradebot - INFO - Buy signal found: about create a new trade for GRT/USDT with s
take_amount: 0.0001 ...
2021-04-22 15:39:33,404 - freqtrade.freqtradebot - INFO - Using Last Bid / Last Price
2021-04-22 15:39:33,869 - freqtrade.freqtradebot - WARNING - Can't open a new trade for GRT/USDT: stake amount is too sm
all (0.0001 < 13.933800000000002)
2021-04-22 15:39:34,401 - freqtrade.wallets - INFO - Wallets synced.
2021-04-22 15:39:34,401 - freqtrade.freqtradebot - INFO - Buy signal found: about create a new trade for CHZ/USDT with s
take_amount: 0.0001 ...
2021-04-22 15:39:34,419 - freqtrade.freqtradebot - INFO - Using Last Bid / Last Price
2021-04-22 15:39:34,885 - freqtrade.freqtradebot - WARNING - Can't open a new trade for CHZ/USDT: stake amount is too sm
all (0.0001 < 13.933800000000002)
2021-04-22 15:39:35,401 - freqtrade.wallets - INFO - Wallets synced.
2021-04-22 15:39:35,416 - freqtrade.freqtradebot - INFO - Buy signal found: about create a new trade for CHR/USDT with s
take_amount: 0.0001 ...
2021-04-22 15:39:35,416 - freqtrade.freqtradebot - INFO - Using Last Bid / Last Price
2021-04-22 15:39:35,901 - freqtrade.freqtradebot - WARNING - Can't open a new trade for CHR/USDT: stake amount is too sm
all (0.0001 < 13.933800000000002)

and i have money there , why is this ?

another question ,
How does it make sense for me to run in dry mode and then run in back test and get different results?

**Comment by xmatthias** [comment]
i suspect you've got a `"stake_amount"= 0.0001` in your configuration "Live" configuration, which is WAY too low for USDT.

This will be different in dry-run - as trades with this amount would also not work in dry-run.

backtesting is only as good as the data (backtesting only has 4 values per candle available) - so some deviances are expected as it's unknown to backtesting how the movements intra-candle happened. 
this is explained in the [backtesting assumptions](https://www.freqtrade.io/en/stable/backtesting/#assumptions-made-by-backtesting), which can explain many differences depending on the settings / configurations used.

**Comment by HAGAI123** [comment]
I try couple amount , 0.1 , 1 ,10 ,100
And is the same problem

**Comment by xmatthias** [comment]
The error shows:
`Can't open a new trade for CHR/USDT: stake amount is too small (0.0001 < 13.933800000000002)`
so you're using 0.0001 as stake_amount.

If you use more (20 or more) - then maybe you're encountering a different error - but for sure not the same error.

Keep in mind that you need to restart the bot - config changes will NOT be live-reloaded.

**Comment by HAGAI123** [comment]
OK,  I change it again but now is don't say nothing. 
Is look like it's not work.
In dry mode is still open positions but in real money nothing

**Comment by xmatthias** [comment]
The logs will tell you if there's something wrong.

the bot will however only buy if there are buy signals - so make sure it's the same strategy (and same pairlist ...)

**Comment by HAGAI123** [comment]
it's the same strategy and same pairlist,how i check the log ?

its make me alot of this in the console .

2021-04-24 00:45:16,315 - freqtrade.data.converter - INFO - Missing data fillup for PERL/USDT: before: 999 - after: 1009
 - 1.0 %
2021-04-24 00:45:16,369 - freqtrade.data.converter - INFO - Missing data fillup for BLZ/USDT: before: 999 - after: 1009
- 1.0 %
2021-04-24 00:45:16,447 - freqtrade.data.converter - INFO - Missing data fillup for UNFI/USDT: before: 999 - after: 1009
 - 1.0 %
2021-04-24 00:45:16,511 - freqtrade.data.converter - INFO - Missing data fillup for BEL/USDT: before: 999 - after: 1009
- 1.0 %
2021-04-24 00:45:28,557 - freqtrade.worker - INFO - Bot heartbeat. PID=1128, version='develop', state='RUNNING'
2021-04-24 00:46:28,744 - freqtrade.worker - INFO - Bot heartbeat. PID=1128, version='develop', state='RUNNING'
2021-04-24 00:47:28,932 - freqtrade.worker - INFO - Bot heartbeat. PID=1128, version='develop', state='RUNNING'
2021-04-24 00:48:29,073 - freqtrade.worker - INFO - Bot heartbeat. PID=1128, version='develop', state='RUNNING'

**Comment by xmatthias** [comment]
based on the logs, the strategy is simply not giving any signals (at least not during the provided time period).

**Comment by HAGAI123** [comment]
Is work 3 days , in 15m time frame .
In the dry run is open also now alot of positions and in the real money is not open nothing

**Comment by xmatthias** [comment]
then either you'll have something in the logs explaining the reason, you have different configs somehow, or you're not running the same strategy.

Freqtrade does not differentiate between dry-run and live except for the order submission.

**Comment by HAGAI123** [comment]
ok now its work for me , but now i have other problem when is make trade 

2021-04-25 03:28:37,698 - numexpr.utils - INFO - NumExpr defaulting to 2 threads.
2021-04-25 03:28:38,979 - freqtrade.commands.trade_commands - ERROR - float division by zero
2021-04-25 03:28:38,979 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "c:\hagaybot\freqtrade-develop\freqtrade\commands\trade_commands.py", line 19, in start_trading
    worker.run()
  File "c:\hagaybot\freqtrade-develop\freqtrade\worker.py", line 74, in run
    state = self._worker(old_state=state)
  File "c:\hagaybot\freqtrade-develop\freqtrade\worker.py", line 111, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
  File "c:\hagaybot\freqtrade-develop\freqtrade\worker.py", line 132, in _throttle
    result = func(*args, **kwargs)
  File "c:\hagaybot\freqtrade-develop\freqtrade\worker.py", line 145, in _process_running
    self.freqtrade.process()
  File "c:\hagaybot\freqtrade-develop\freqtrade\freqtradebot.py", line 184, in process
    self.exit_positions(trades)
  File "c:\hagaybot\freqtrade-develop\freqtrade\freqtradebot.py", line 695, in exit_positions
    if trade.open_order_id is None and trade.is_open and self.handle_trade(trade):
  File "c:\hagaybot\freqtrade-develop\freqtrade\freqtradebot.py", line 807, in handle_trade
    if self._check_and_execute_sell(trade, sell_rate, buy, sell):
  File "c:\hagaybot\freqtrade-develop\freqtrade\freqtradebot.py", line 942, in _check_and_execute_sell
    should_sell = self.strategy.should_sell(
  File "c:\hagaybot\freqtrade-develop\freqtrade\strategy\interface.py", line 516, in should_sell
    current_profit = trade.calc_profit_ratio(current_rate)
  File "c:\hagaybot\freqtrade-develop\freqtrade\persistence\models.py", line 554, in calc_profit_ratio
    profit_ratio = (close_trade_value / self.open_trade_value) - 1
ZeroDivisionError: float division by zero
2021-04-25 03:28:38,994 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2021-04-25 03:28:38,994 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process di
ed'}
2021-04-25 03:28:39,120 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2021-04-25 03:28:39,135 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': warning, 'status': "7 open tr
ades active.\n\nHandle these trades manually on Binance, or '/start' the bot again and use '/stopbuy' to handle open tra
des gracefully. \n"}
2021-04-25 03:28:39,260 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
2021-04-25 03:28:39,260 - freqtrade.rpc.api_server.webserver - INFO - Stopping API Server
INFO:     Shutting down
2021-04-25 03:28:39,323 - uvicorn.error - INFO - Shutting down
INFO:     Waiting for application shutdown.
2021-04-25 03:28:39,432 - uvicorn.error - INFO - Waiting for application shutdown.
INFO:     Application shutdown complete.
2021-04-25 03:28:39,432 - uvicorn.error - INFO - Application shutdown complete.
INFO:     Finished server process [1264]
2021-04-25 03:28:39,432 - uvicorn.error - INFO - Finished server process [1264]
2021-04-25 03:28:39,432 - apscheduler.scheduler - INFO - Scheduler has been shut down

**Comment by xmatthias** [comment]
That's the same issue than #4764 and #4617. Unfortunately, both failed to provide the necessary data, so we could not do a full investigation on why this happens.


Please use either sqlite3 (command line tool) or sqlitebrowser to open the database, and use the following query to get the problematic trade.

``` sql
.headers on
-- The above assumes sqlite shell is used
select * from trades where open_trade_value = 0;
-- Get trade-id from above
select * from orders where ft_trade_id = <id>;
```

The 2nd query (orders table) will give you an order-id for the order that executed (column order_id).

Based on this, please execute the following in a python shell (within the freqtrade environment).
This assumes you're using binance - if you use another exchange please adjust accordingly.

``` python
import ccxt
exchange = ccxt.binance({'apiKey': '<yourApiKey>', 'secret': '<yoursecret>' })
res = exchange.fetch_order(order_id, 'BTC/USDT)
print(res)
```

**Comment by HAGAI123** [comment]
I think I know why it makes this problem,
I accidentally closed manually while the bot was working.
Then it made me this mistake because he could not close



When I run the bot it makes me another error, I do not know if it's a problem but that's what it writes


Exception ignored in: <function Exchange.__del__ at 0x000000E621087CA0>
Traceback (most recent call last):
  File "c:\hagaybot\freqtrade-develop\freqtrade\exchange\exchange.py", line 151, in __del__
    self.close()
  File "c:\hagaybot\freqtrade-develop\freqtrade\exchange\exchange.py", line 156, in close
    asyncio.get_event_loop().run_until_complete(self._api_async.close())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 592, in run_unti
l_complete
    self._check_running()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 552, in _check_r
unning
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
2021-04-26 06:19:40,384 - ccxt.base.exchange - WARNING - binance requires to release all resources with an explicit call
 to the .close() coroutine. If you are using the exchange instance with async coroutines, add exchange.close() to your c
ode into a place when you're done with the exchange and don't need the exchange instance anymore (at the end of your asy
nc coroutine).
2021-04-26 06:19:40,405 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000000E621B31BB0>






Another question, why does he not buy in the green triangle.
Where I marked in the red circle below.
If the bot recognizes this why does it not buy?

https://ibb.co/4FQSMSd

**Comment by xmatthias** [comment]
most likely, because you were in other trades already at that point, and did not have a trade-slot open (max_open_trades was reached).

when using volumepairlist - it's also possible that this pair was not in the pairlist at the time of the signal (the signals are backfilled for the duratin of what you see, even if the pair was not in the pairlist at the time.

**Comment by HAGAI123** [comment]
ok thank you .
How does it make sense, that I run a backtest I reach 90% profit in a timeframe 15m
And when I run it for real money it's not the same thing?
I understand there is slippage, how can one try to fix it?

**Comment by xmatthias** [comment]
backtesting works on historic data - there is no guarantee that history repeats.
Backtesting also works based on [some assumptions](https://www.freqtrade.io/en/stable/backtesting/#assumptions-made-by-backtesting).

The most likely cause for overstated profit is a very tight trailing stoploss (1% or lower) - which will seem better in backtesting than how it will perform in reality.

**Comment by HAGAI123** [comment]
But I don't use trailling stop.
Only base on rsi. And roi
