### ISSUE TITLE
Error while fetching server API version?

### ISSUE THREAD

**Issue by onurkiris05** [freqtrade/freqtrade#4830]
Im trying to setup freqtrade with docker but having some issues like below;

STEPS
1- 'mkdir ft_userdata'
2- 'cd ft_userdata/'
3- 'curl https://raw.githubusercontent.com/freqtrade/freqtrade/stable/docker-compose.yml -o docker-compose.yml'
4- 'docker-compose pull'

At 4.step, im having issue like below; 

 

> C:\Users\onurk\PycharmProjects\pythonProject\ft_userdata>docker-compose pull
> Traceback (most recent call last):
>   File "docker\api\client.py", line 214, in _retrieve_server_version
>   File "docker\api\daemon.py", line 181, in version
>   File "docker\utils\decorators.py", line 46, in inner
>   File "docker\api\client.py", line 237, in _get
>   File "requests\sessions.py", line 543, in get
>   File "requests\sessions.py", line 530, in request
>   File "requests\sessions.py", line 643, in send
>   File "requests\adapters.py", line 439, in send
>   File "urllib3\connectionpool.py", line 670, in urlopen
>   File "urllib3\connectionpool.py", line 392, in _make_request
>   File "http\client.py", line 1255, in request
>   File "http\client.py", line 1301, in _send_request
>   File "http\client.py", line 1250, in endheaders
>   File "http\client.py", line 1010, in _send_output
>   File "http\client.py", line 950, in send
>   File "docker\transport\npipeconn.py", line 32, in connect
>   File "docker\transport\npipesocket.py", line 23, in wrapped
>   File "docker\transport\npipesocket.py", line 72, in connect
>   File "docker\transport\npipesocket.py", line 52, in connect
> pywintypes.error: (2, 'CreateFile', 'Sistem belirtilen dosyayı bulamıyor.')
> 
>  During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> 
>   File "docker-compose", line 3, in <module>
>   File "compose\cli\main.py", line 81, in main
>   File "compose\cli\main.py", line 199, in perform_command
>   File "compose\cli\command.py", line 60, in project_from_options
>   File "compose\cli\command.py", line 152, in get_project
>   File "compose\cli\docker_client.py", line 41, in get_client
>   File "compose\cli\docker_client.py", line 170, in docker_client
>   File "docker\api\client.py", line 197, in __init__
>   File "docker\api\client.py", line 221, in _retrieve_server_version
> docker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'Sistem belirtilen dosyayı bulamıyor.')
> [11724] Failed to execute script docker-compose
>

**Comment by xmatthias** [comment]
this error appears if docker is not running / not installed (only docker-compose).

Freqtrade assumes that docker is setup, available and running - if that's not the case please follow the docker-guides for your system to get that setup.

**Comment by onurkiris05** [comment]
> this error appears if docker is not running / not installed (only docker-compose).
> 
> Freqtrade assumes that docker is setup, available and running - if that's not the case please follow the docker-guides for your system to get that setup.

Im installed docker-compose by;

`pip install docker-compose`

and checked the version;

```
 (venv) C:\Users\onurk\PycharmProjects\pythonProject\ft_userdata>docker-compose version
 docker-compose version 1.29.1, build unknown
 docker-py version: 5.0.0
 CPython version: 3.8.8
 OpenSSL version: OpenSSL 1.1.1i  8 Dec 2020
```

but still im having below issue when try ' docker-compose pull '

```
(venv) C:\Users\onurk\PycharmProjects\pythonProject\ft_userdata>docker-compose pull
Traceback (most recent call last):
  File "c:\users\onurk\pycharmprojects\pythonproject\venv\lib\site-packages\docker\api\client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "c:\users\onurk\pycharmprojects\pythonproject\venv\lib\site-packages\docker\api\daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "c:\users\onurk\pycharmprojects\pythonproject\venv\lib\site-packages\docker\utils\decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "c:\users\onurk\pycharmprojects\pythonproject\venv\lib\site-packages\docker\api\client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "c:\users\onurk\pycharmprojects\pythonproject\venv\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "c:\users\onurk\pycharmprojects\pythonproject\venv\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\onurk\pycharmprojects\pythonproject\venv\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\onurk\pycharmprojects\pythonproject\venv\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "c:\users\onurk\pycharmprojects\pythonproject\venv\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "c:\users\onurk\pycharmprojects\pythonproject\venv\lib\site-packages\urllib3\connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\onurk\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\onurk\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\onurk\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\onurk\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1010, in _send_output
    self.send(msg)
  File "C:\Users\onurk\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 950, in send
    self.connect()
  File "c:\users\onurk\pycharmprojects\pythonproject\venv\lib\site-packages\docker\transport\npipeconn.py", line 32, in connect
    sock.connect(self.npipe_path)
  File "c:\users\onurk\pycharmprojects\pythonproject\venv\lib\site-packages\docker\transport\npipesocket.py", line 23, in wrapped
    return f(self, *args, **kwargs)
  File "c:\users\onurk\pycharmprojects\pythonproject\venv\lib\site-packages\docker\transport\npipesocket.py", line 72, in connect
    raise e
  File "c:\users\onurk\pycharmprojects\pythonproject\venv\lib\site-packages\docker\transport\npipesocket.py", line 52, in connect
    handle = win32file.CreateFile(
pywintypes.error: (2, 'CreateFile', 'Sistem belirtilen dosyayı bulamıyor.')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\onurk\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\onurk\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\onurk\PycharmProjects\pythonProject\venv\Scripts\docker-compose.exe\__main__.py", line 7, in <module>
  File "c:\users\onurk\pycharmprojects\pythonproject\venv\lib\site-packages\compose\cli\main.py", line 81, in main
    command_func()
  File "c:\users\onurk\pycharmprojects\pythonproject\venv\lib\site-packages\compose\cli\main.py", line 200, in perform_command
    project = project_from_options('.', options)
  File "c:\users\onurk\pycharmprojects\pythonproject\venv\lib\site-packages\compose\cli\command.py", line 60, in project_from_options
    return get_project(
  File "c:\users\onurk\pycharmprojects\pythonproject\venv\lib\site-packages\compose\cli\command.py", line 152, in get_project
    client = get_client(
  File "c:\users\onurk\pycharmprojects\pythonproject\venv\lib\site-packages\compose\cli\docker_client.py", line 41, in get_client
    client = docker_client(
  File "c:\users\onurk\pycharmprojects\pythonproject\venv\lib\site-packages\compose\cli\docker_client.py", line 170, in docker_client
    client = APIClient(use_ssh_client=not use_paramiko_ssh, **kwargs)
  File "c:\users\onurk\pycharmprojects\pythonproject\venv\lib\site-packages\docker\api\client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "c:\users\onurk\pycharmprojects\pythonproject\venv\lib\site-packages\docker\api\client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'Sistem belirtilen dosyayı bulamıyor.')
```

**Comment by xmatthias** [comment]
It's not docker-compose that's not working, but docker itself.

try `docker info`. 
Based on the errors / problems - please use the docker support channels / google to investigate if docker is simply stopped, or if  you need to install it properly first.

**Comment by onurkiris05** [comment]
the result of ' docker info'  ;

```
(venv) C:\Users\onurk\PycharmProjects\pythonProject\ft_userdata>docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.6.0)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 2
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.72-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 12.4GiB
 Name: docker-desktop
 ID: 7ZK5:AZKF:N7VM:DMDJ:D7AR:B2WO:JIIX:CUKS:EDCF:DJCR:IXES:6L6Z
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```
by the way, somehow ' docker-compose pull ' worked;

```
(venv) C:\Users\onurk\PycharmProjects\pythonProject\ft_userdata>docker-compose pull
Pulling freqtrade ... done
```
and following steps done too;

```
(venv) C:\Users\onurk\PycharmProjects\pythonProject\ft_userdata>docker-compose run --rm freqtrade create-userdir --userdir user_data
Creating ft_userdata_freqtrade_run ... done

(venv) C:\Users\onurk\PycharmProjects\pythonProject\ft_userdata>docker-compose run --rm freqtrade new-config --config user_data/config.json
Creating ft_userdata_freqtrade_run ... done
? Do you want to enable Dry-run (simulated trades)? Yes
? Please insert your stake currency: BTC
? Please insert your stake amount: 0.01
? Please insert max_open_trades (Integer or 'unlimited'): 1
? Please insert your desired timeframe (e.g. 5m): 5m
? Please insert your display Currency (for reporting): USD
? Select exchange other
? Type your exchange name (Must be supported by ccxt) bitmex
? Do you want to enable Telegram? No
2021-04-29 10:52:34,888 - freqtrade.commands.build_config_commands - INFO - Writing config to `user_data/config.json`.
2021-04-29 10:52:34,888 - freqtrade.commands.build_config_commands - INFO - Please make sure to check the configuration contents and adjust settings to your needs.

```

but when i check ' docker-compose ps ' , freqtrade keep restarting..

```
(venv) C:\Users\onurk\PycharmProjects\pythonProject\ft_userdata>docker-compose ps
  Name                 Command                 State      Ports
---------------------------------------------------------------
freqtrade   freqtrade trade --logfile  ...   Restarting
```

and i cant use any freqtrade command;
```

(venv) C:\Users\onurk\PycharmProjects\pythonProject\ft_userdata>freqtrade -V
'freqtrade' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by xmatthias** [comment]
you should stop the running instance (`docker-compose down`) - and then try to restart it again (`docker-compose up -d`).
if it keeps restarting, please have a look at the logs.

As you are running on windows, you'll need to explicitly enable the source directory for volume mounting - otherwise it will not work at all.
