### ISSUE TITLE
KeyError: 'tema'

### ISSUE THREAD

**Issue by rapatapa** [freqtrade/freqtrade#4855]
## Describe your environment

  * Operating system: ___docker on_ubuntu 18.04
  * Python Version: ____3.9_ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: __freqtrade 2021.4

  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:
KeyError: 'tema'

### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
 sudo docker-compose run freqtrade backtesting --datadir user_data/data/binance --export trades --stake-amount 1000 -s BBRSI -i 15m
2021-05-02 20:33:27,305 - freqtrade.configuration.configuration - INFO - Using config: user_data/config.json ...
2021-05-02 20:33:27,309 - freqtrade.loggers - INFO - Verbosity set to 0
2021-05-02 20:33:27,310 - freqtrade.configuration.configuration - INFO - Parameter -i/--timeframe detected ... Using timeframe: 15m ...
2021-05-02 20:33:27,311 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 3 ...
2021-05-02 20:33:27,312 - freqtrade.configuration.configuration - INFO - Parameter --stake-amount detected, overriding stake_amount to: 1000.0 ...
2021-05-02 20:33:27,429 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2021-05-02 20:33:27,432 - freqtrade.configuration.configuration - INFO - Using data directory: user_data/data/binance ...
2021-05-02 20:33:27,433 - freqtrade.configuration.configuration - INFO - Overriding timeframe with Command line argument
2021-05-02 20:33:27,434 - freqtrade.configuration.configuration - INFO - Parameter --export detected: trades ...
2021-05-02 20:33:27,435 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2021-05-02 20:33:27,810 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2021-05-02 20:33:27,811 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2021-05-02 20:33:27,812 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2021-05-02 20:33:27,829 - freqtrade.commands.optimize_commands - INFO - Starting freqtrade in Backtesting mode
2021-05-02 20:33:27,831 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2021-05-02 20:33:27,832 - freqtrade.exchange.exchange - INFO - Using CCXT 1.48.76
2021-05-02 20:33:27,833 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2021-05-02 20:33:27,894 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 200}
2021-05-02 20:33:27,958 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2021-05-02 20:33:31,820 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2021-05-02 20:33:31,933 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy BBRSI from '/freqtrade/user_data/strategies/BBRSI.py'...
2021-05-02 20:33:31,934 - freqtrade.strategy.hyper - INFO - No params for buy found, using default values.
2021-05-02 20:33:31,935 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): buy_rsi = 30
2021-05-02 20:33:31,936 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): sell_rsi = 70
2021-05-02 20:33:31,936 - freqtrade.strategy.hyper - INFO - No params for sell found, using default values.
2021-05-02 20:33:31,937 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): buy_rsi = 30
2021-05-02 20:33:31,937 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): sell_rsi = 70
2021-05-02 20:33:31,938 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 15m.
2021-05-02 20:33:31,938 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: BUSD.
2021-05-02 20:33:31,938 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 1000.0.
2021-05-02 20:33:31,938 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'buy': 10, 'sell': 30}.
2021-05-02 20:33:31,938 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'use_sell_signal' with value in config file: True.
2021-05-02 20:33:31,939 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'sell_profit_only' with value in config file: False.
2021-05-02 20:33:31,939 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ignore_roi_if_buy_signal' with value in config file: False.
2021-05-02 20:33:31,939 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'60': 0.01, '30': 0.02, '0': 0.04}
2021-05-02 20:33:31,939 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 15m
2021-05-02 20:33:31,939 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.1
2021-05-02 20:33:31,939 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2021-05-02 20:33:31,940 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2021-05-02 20:33:31,940 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2021-05-02 20:33:31,940 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2021-05-02 20:33:31,940 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
2021-05-02 20:33:31,940 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'market', 'stoploss_on_exchange': False}
2021-05-02 20:33:31,940 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
2021-05-02 20:33:31,940 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: BUSD
2021-05-02 20:33:31,940 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 1000.0
2021-05-02 20:33:31,941 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 30
2021-05-02 20:33:31,941 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'buy': 10, 'sell': 30}
2021-05-02 20:33:31,941 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_sell_signal: True
2021-05-02 20:33:31,942 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_only: False
2021-05-02 20:33:31,942 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_buy_signal: False
2021-05-02 20:33:31,942 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_offset: 0.0
2021-05-02 20:33:31,942 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2021-05-02 20:33:31,943 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2021-05-02 20:33:31,943 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2021-05-02 20:33:32,007 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from '/freqtrade/freqtrade/plugins/pairlist/StaticPairList.py'...
2021-05-02 20:33:32,361 - freqtrade.data.history.history_utils - INFO - Using indicator startup period: 30 ...
2021-05-02 20:33:32,472 - numexpr.utils - INFO - NumExpr defaulting to 4 threads.
2021-05-02 20:33:35,269 - freqtrade.optimize.backtesting - INFO - Loading data from 2021-04-02 20:30:00 up to 2021-05-02 19:45:00 (29 days)..
2021-05-02 20:33:35,270 - freqtrade.configuration.timerange - WARNING - Moving start-date by 30 candles to account for startup time.
2021-05-02 20:33:35,271 - freqtrade.optimize.backtesting - INFO - Dataload complete. Calculating indicators
2021-05-02 20:33:35,272 - freqtrade.optimize.backtesting - INFO - Running backtesting for Strategy BBRSI
2021-05-02 20:33:36,058 - freqtrade.optimize.backtesting - INFO - Backtesting with data from 2021-04-03 04:00:00 up to 2021-05-02 19:45:00 (29 days)..
2021-05-02 20:33:36,082 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'tema'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 53, in start_backtesting
    backtesting.start()
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 479, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 449, in backtest_one_strategy
    results = self.backtest(
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 352, in backtest
    data: Dict = self._get_ohlcv_as_lists(processed)
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 196, in _get_ohlcv_as_lists
    self.strategy.advise_buy(pair_data, {'pair': pair}), {'pair': pair})[headers].copy()
  File "/freqtrade/freqtrade/strategy/interface.py", line 704, in advise_buy
    return self.populate_buy_trend(dataframe, metadata)
  File "/freqtrade/user_data/strategies/BBRSI.py", line 156, in populate_buy_trend
    (dataframe['tema'] <= dataframe['bb_middleband']) &
  File "/home/ftuser/.local/lib/python3.9/site-packages/pandas/core/frame.py", line 3024, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/ftuser/.local/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: 'tema'

  ```

**Comment by xmatthias** [comment]
You seem to be using a column named "tema" in your buy signal - but you're not populating this in your populate_indicators - so it's not available.
