### ISSUE TITLE
TypeError: integer argument expected, got float error while backtesting after 2021.4

### ISSUE THREAD

**Issue by quents** [freqtrade/freqtrade#4865]
## Describe your environment

  * Operating system: macOS Big Sur
  * Python Version: python 3.8 (`python -V`)
  * CCXT version: ccxt==1.49.30 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2021.4 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

I have been using Freqtrade for 2 months with no issue. I updated to 2021.4 from 2021.3 to try out new optimization feature but I have an error "TypeError: integer argument expected, got float" while backtesting a strategy with the following command:

`freqtrade backtesting --config user_data/config_usdt.json --strategy Some_Strategy --timerange 20210101-20210501 -i 4h --dry-run-wallet 700 --export trades --export-filename user_data/backtest_results/results.json`

### Steps to reproduce:

  1. At first, I updated my current codebase to 2021.4. After I got the error, I created a new conda environment with the new version and tried there with no luck.
 
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

There was no issue like this on the versions 2021.3 and 2021.2. 4h data of the pairs in the configuration is already in user_data/data/binance folder. I checked out the documentation if anything is changed regarding backtesting, yet I couldn't encounter.

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  Traceback (most recent call last):
  File "/Users/**/Dev/**/freqtrade_2021_4/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/Users/**/Dev/**/freqtrade_2021_4/freqtrade/commands/optimize_commands.py", line 53, in start_backtesting
    backtesting.start()
  File "/Users/**/Dev/**/freqtrade_2021_4/freqtrade/optimize/backtesting.py", line 481, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
  File "/Users/**/Dev/**/freqtrade_2021_4/freqtrade/optimize/backtesting.py", line 445, in backtest_one_strategy
    min_date, max_date = history.get_timerange(preprocessed)
  File "/Users/**/Dev/**/freqtrade_2021_4/freqtrade/data/history/history_utils.py", line 377, in get_timerange
    timeranges = [
  File "/Users/**/Dev/**/freqtrade_2021_4/freqtrade/data/history/history_utils.py", line 378, in <listcomp>
    (arrow.get(frame['date'].min()), arrow.get(frame['date'].max()))
  File "/Users/**/miniconda3/envs/freqtrade-2021-4/lib/python3.8/site-packages/arrow/api.py", line 91, in get
    return _factory.get(*args, **kwargs)
  File "/Users/**/miniconda3/envs/freqtrade-2021-4/lib/python3.8/site-packages/arrow/factory.py", line 239, in get
    return self.type.fromdatetime(arg)
  File "/Users/**/miniconda3/envs/freqtrade-2021-4/lib/python3.8/site-packages/arrow/arrow.py", line 326, in fromdatetime
    return cls(
  File "/Users/**/miniconda3/envs/freqtrade-2021-4/lib/python3.8/site-packages/arrow/arrow.py", line 176, in __init__
    self._datetime = dt_datetime(
TypeError: integer argument expected, got float
  ```

**Comment by xmatthias** [comment]
Are you able to provide me with the full log up to this point? 

i've seen this before (kindof) - but i can't reproduce it whatsoever :(

**Comment by quents** [comment]
Of course, the full log up to the error:

 ```
2021-05-03 12:52:15,041 - freqtrade.configuration.configuration - INFO - Using config: user_data/config_usdt.json ...
2021-05-03 12:52:15,043 - freqtrade.loggers - INFO - Verbosity set to 0
2021-05-03 12:52:15,043 - freqtrade.configuration.configuration - INFO - Parameter -i/--timeframe detected ... Using timeframe: 4h ...
2021-05-03 12:52:15,043 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 10 ...
2021-05-03 12:52:15,043 - freqtrade.configuration.configuration - INFO - Parameter --dry-run-wallet detected, overriding dry_run_wallet to: 700.0 ...
2021-05-03 12:52:15,043 - freqtrade.configuration.configuration - INFO - Parameter --timerange detected: 20210101-20210501 ...
2021-05-03 12:52:15,043 - freqtrade.configuration.configuration - INFO - Using user-data directory: /Users/**/Dev/**/freqtrade_2021_4/user_data ...
2021-05-03 12:52:15,043 - freqtrade.configuration.configuration - INFO - Using data directory: /Users/**/Dev/**/freqtrade_2021_4/user_data/data/binance ...
2021-05-03 12:52:15,043 - freqtrade.configuration.configuration - INFO - Overriding timeframe with Command line argument
2021-05-03 12:52:15,043 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2021-05-03 12:52:15,048 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2021-05-03 12:52:15,048 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2021-05-03 12:52:15,048 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2021-05-03 12:52:15,050 - freqtrade.commands.optimize_commands - INFO - Starting freqtrade in Backtesting mode
2021-05-03 12:52:15,050 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2021-05-03 12:52:15,050 - freqtrade.exchange.exchange - INFO - Using CCXT 1.49.30
2021-05-03 12:52:15,050 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2021-05-03 12:52:15,055 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 200}
2021-05-03 12:52:15,059 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2021-05-03 12:52:16,431 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2021-05-03 12:52:16,454 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy Some_Strategy from '/Users/**/Dev/**/freqtrade_2021_4/user_data/strategies/Some_Strategy.py'...
2021-05-03 12:52:16,454 - freqtrade.strategy.hyper - INFO - No params for buy found, using default values.
2021-05-03 12:52:16,455 - freqtrade.strategy.hyper - INFO - No params for sell found, using default values.
2021-05-03 12:52:16,455 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 4h.
2021-05-03 12:52:16,455 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2021-05-03 12:52:16,455 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: unlimited.
2021-05-03 12:52:16,455 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'buy': 10, 'sell': 30}.
2021-05-03 12:52:16,455 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'use_sell_signal' with value in config file: True.
2021-05-03 12:52:16,455 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'sell_profit_only' with value in config file: False.
2021-05-03 12:52:16,455 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ignore_roi_if_buy_signal' with value in config file: False.
2021-05-03 12:52:16,455 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'sell_profit_offset' with value in config file: 0.04.
2021-05-03 12:52:16,455 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ignore_buying_expired_candle_after' with value in config file: 0.
2021-05-03 12:52:16,455 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 0.05, '4320': 0.03, '6480': 0.02}
2021-05-03 12:52:16,455 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 4h
2021-05-03 12:52:16,455 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.99
2021-05-03 12:52:16,455 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2021-05-03 12:52:16,455 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2021-05-03 12:52:16,455 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2021-05-03 12:52:16,455 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2021-05-03 12:52:16,455 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
2021-05-03 12:52:16,455 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'market', 'stoploss_on_exchange': False}
2021-05-03 12:52:16,455 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
2021-05-03 12:52:16,455 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2021-05-03 12:52:16,455 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: unlimited
2021-05-03 12:52:16,455 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 200
2021-05-03 12:52:16,455 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'buy': 10, 'sell': 30}
2021-05-03 12:52:16,455 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_sell_signal: True
2021-05-03 12:52:16,455 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_only: False
2021-05-03 12:52:16,455 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_buy_signal: False
2021-05-03 12:52:16,455 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_offset: 0.04
2021-05-03 12:52:16,455 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2021-05-03 12:52:16,456 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2021-05-03 12:52:16,456 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2021-05-03 12:52:16,461 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from '/Users/**/Dev/**/freqtrade_2021_4/freqtrade/plugins/pairlist/StaticPairList.py'...
2021-05-03 12:52:16,624 - freqtrade.data.history.history_utils - INFO - Using indicator startup period: 200 ...
2021-05-03 12:52:16,636 - numexpr.utils - INFO - NumExpr defaulting to 8 threads.
2021-05-03 12:52:16,687 - freqtrade.data.history.idatahandler - WARNING - Missing data at start for pair CAKE/USDT, data starts at 2021-02-19 04:00:00
2021-05-03 12:52:16,943 - freqtrade.data.history.idatahandler - WARNING - Missing data at start for pair CKB/USDT, data starts at 2021-01-26 12:00:00
2021-05-03 12:52:17,058 - freqtrade.data.history.idatahandler - WARNING - Missing data at start for pair PUNDIX/USDT, data starts at 2021-04-09 04:00:00
2021-05-03 12:52:17,101 - freqtrade.data.history.idatahandler - WARNING - Missing data at start for pair DODO/USDT, data starts at 2021-02-19 08:00:00
2021-05-03 12:52:17,178 - freqtrade.data.history.idatahandler - WARNING - Missing data at start for pair REEF/USDT, data starts at 2020-12-29 04:00:00
2021-05-03 12:52:17,203 - freqtrade.data.history.idatahandler - WARNING - Missing data at start for pair OM/USDT, data starts at 2021-03-08 08:00:00
2021-05-03 12:52:17,290 - freqtrade.data.history.idatahandler - WARNING - Missing data at start for pair LINA/USDT, data starts at 2021-03-18 12:00:00
2021-05-03 12:52:17,394 - freqtrade.data.history.idatahandler - WARNING - Missing data at start for pair DEGO/USDT, data starts at 2021-03-10 08:00:00
2021-05-03 12:52:17,439 - freqtrade.data.history.idatahandler - WARNING - Missing data at start for pair SUPER/USDT, data starts at 2021-03-25 08:00:00
2021-05-03 12:52:17,450 - freqtrade.data.history.idatahandler - WARNING - Missing data at start for pair ALICE/USDT, data starts at 2021-03-15 04:00:00
2021-05-03 12:52:17,485 - freqtrade.data.history.idatahandler - WARNING - Missing data at start for pair OG/USDT, data starts at 2020-12-30 04:00:00
2021-05-03 12:52:17,496 - freqtrade.data.history.idatahandler - WARNING - Missing data at start for pair 1INCH/USDT, data starts at 2020-12-25 04:00:00
2021-05-03 12:52:17,506 - freqtrade.data.history.idatahandler - WARNING - Missing data at start for pair RAMP/USDT, data starts at 2021-03-22 08:00:00
2021-05-03 12:52:18,010 - freqtrade.data.history.idatahandler - WARNING - Missing data at start for pair RIF/USDT, data starts at 2021-01-07 12:00:00
2021-05-03 12:52:18,032 - freqtrade.data.history.idatahandler - WARNING - Missing data at start for pair TRU/USDT, data starts at 2021-01-19 04:00:00
2021-05-03 12:52:18,043 - freqtrade.data.history.idatahandler - WARNING - Missing data at start for pair TLM/USDT, data starts at 2021-04-13 04:00:00
2021-05-03 12:52:18,054 - freqtrade.data.history.idatahandler - WARNING - Missing data at start for pair TWT/USDT, data starts at 2021-01-27 08:00:00
2021-05-03 12:52:18,077 - freqtrade.data.history.idatahandler - WARNING - Missing data at start for pair CFX/USDT, data starts at 2021-03-29 08:00:00
2021-05-03 12:52:18,101 - freqtrade.data.history.idatahandler - WARNING - Missing data at start for pair TKO/USDT, data starts at 2021-04-07 12:00:00
2021-05-03 12:52:18,123 - freqtrade.data.history.idatahandler - WARNING - Missing data at start for pair FIS/USDT, data starts at 2021-03-03 08:00:00
2021-05-03 12:52:18,134 - freqtrade.data.history.idatahandler - WARNING - Missing data at start for pair EPS/USDT, data starts at 2021-04-02 08:00:00
2021-05-03 12:52:18,155 - freqtrade.data.history.idatahandler - WARNING - Missing data at start for pair BAR/USDT, data starts at 2021-04-21 08:00:00
2021-05-03 12:52:18,167 - freqtrade.data.history.idatahandler - WARNING - Missing data at start for pair ATM/USDT, data starts at 2020-12-30 04:00:00
2021-05-03 12:52:18,178 - freqtrade.data.history.idatahandler - WARNING - Missing data at start for pair ASR/USDT, data starts at 2020-12-30 04:00:00
2021-05-03 12:52:18,190 - freqtrade.data.history.idatahandler - WARNING - Missing data at start for pair JUV/USDT, data starts at 2020-12-21 04:00:00
2021-05-03 12:52:18,201 - freqtrade.data.history.idatahandler - WARNING - Missing data at start for pair PSG/USDT, data starts at 2020-12-21 04:00:00
2021-05-03 12:52:18,212 - freqtrade.data.history.idatahandler - WARNING - Missing data at start for pair BADGER/USDT, data starts at 2021-03-02 08:00:00
2021-05-03 12:52:18,223 - freqtrade.data.history.idatahandler - WARNING - Missing data at start for pair AUTO/USDT, data starts at 2021-04-02 08:00:00
2021-05-03 12:52:18,281 - freqtrade.data.history.idatahandler - WARNING - Missing data at start for pair ACM/USDT, data starts at 2021-02-24 08:00:00
2021-05-03 12:52:18,314 - freqtrade.data.history.idatahandler - WARNING - Missing data at start for pair CELO/USDT, data starts at 2021-01-05 08:00:00
2021-05-03 12:52:18,346 - freqtrade.optimize.backtesting - INFO - Loading data from 2020-11-28 16:00:00 up to 2021-05-01 00:00:00 (153 days)..
2021-05-03 12:52:18,346 - freqtrade.optimize.backtesting - INFO - Dataload complete. Calculating indicators
2021-05-03 12:52:18,346 - freqtrade.optimize.backtesting - INFO - Running backtesting for Strategy Some_Strategy
2021-05-03 12:52:33,035 - freqtrade - ERROR - Fatal exception!
  ```

**Comment by GuuhBoss** [comment]
I got the same error when passed through all the log and started to run the strategy.

`freqtrade backtesting -s Rayner -c config.json --timerange 20200801`

I saw this kind of error related to stochf on pull https://github.com/freqtrade/freqtrade-strategies/pull/73

but mine uses RSI and SMA on 1D timeframe... anyways I hope this will help, if you want the strategy I can send, I just didnt to not get too long...

```
2021-05-05 22:04:38,615 - freqtrade.optimize.backtesting - INFO - Loading data from 2020-01-14 00:00:00 up to 2021-04-29 00:00:00 (471 days)..
2021-05-05 22:04:38,615 - freqtrade.optimize.backtesting - INFO - Dataload complete. Calculating indicators
2021-05-05 22:04:38,616 - freqtrade.optimize.backtesting - INFO - Running backtesting for Strategy Rayner
2021-05-05 22:04:38,790 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/user/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/home/user/freqtrade/freqtrade/commands/optimize_commands.py", line 53, in start_backtesting
    backtesting.start()
  File "/home/user/freqtrade/freqtrade/optimize/backtesting.py", line 481, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
  File "/home/user/freqtrade/freqtrade/optimize/backtesting.py", line 445, in backtest_one_strategy
    min_date, max_date = history.get_timerange(preprocessed)
  File "/home/user/freqtrade/freqtrade/data/history/history_utils.py", line 377, in get_timerange
    timeranges = [
  File "/home/user/freqtrade/freqtrade/data/history/history_utils.py", line 378, in <listcomp>
    (arrow.get(frame['date'].min()), arrow.get(frame['date'].max()))
  File "/home/user/freqtrade/.env/lib/python3.8/site-packages/arrow/api.py", line 80, in get
    return _factory.get(*args, **kwargs)
  File "/home/user/freqtrade/.env/lib/python3.8/site-packages/arrow/factory.py", line 243, in get
    return self.type.fromdatetime(arg)
  File "/home/user/freqtrade/.env/lib/python3.8/site-packages/arrow/arrow.py", line 323, in fromdatetime
    return cls(
  File "/home/user/freqtrade/.env/lib/python3.8/site-packages/arrow/arrow.py", line 174, in __init__
    self._datetime = dt_datetime(
TypeError: integer argument expected, got float

**Comment by xmatthias** [comment]
what's your pandas and arrow versions?
`pip freeze | grep pandas`
`pip freeze | grep arrow`

i can't reproduce it this - which makes attempting a fix guesswork only...

**Comment by quents** [comment]
> pip freeze | grep pandas

pandas==1.2.4
arrow @ file:///Users/runner/miniforge3/conda-bld/arrow_1619571875722/work

**Comment by xmatthias** [comment]
that arrow-version concerns me ... you should have `arrow==1.1.0` ... if you don't, then this can for sure cause issues.

**Comment by GuuhBoss** [comment]
mine: 
`(.env) user@gu:~/freqtrade$ pip freeze | grep pandas`
OUTPUT:
pandas==1.2.4
pandas-ta==0.2.45b0

`(.env) user@gu:~/freqtrade$ pip freeze | grep arrow`
OUTPUT:
arrow==1.0.3

**Comment by xmatthias** [comment]
After looking at this long enough - the only case where i was able to recreate this is when using a rather long startup-candle-count (like 200 candles on 4h candles) - and not having enough data left (basically my start-date was too late (after my data ended).

#4887 should fix this still - but by giving a "proper" output instead and warning that no more data is left.

**Comment by GuuhBoss** [comment]
I actually do have a 200 startup-candle-count on 1D but I probably do have more data than that since I download-data since 01/01/2020 and the strategy starts on 01/08/2020 which is 213 days of difference :s

**Comment by GuuhBoss** [comment]
I will try #4887 anyways

**Comment by GuuhBoss** [comment]
Should I get this error? 
`ValueError: Cannot set a frame with no defined index and a scalar`

I shorted the startup-candle-count and works, thanks :)

**Comment by xmatthias** [comment]
> Should I get this error?

without more information - no clue what this should be.

**Comment by JackBananas** [comment]
I've been using freqtrade for the last 2 months and this is a "common" issue for me, therefore I can apport more information. For instance, using pairs ".*/USDT":

freqtrade backtesting -c someConfig --strategy-list someStrategies -i 5m --timerange 20210501-202105**12** -> ERROR
freqtrade backtesting -c someConfig --strategy-list someStrategies -i 5m --timerange 20210501-202105**11** -> ERROR
freqtrade backtesting -c someConfig --strategy-list someStrategies -i 5m --timerange 20210501-202105**10** -> OK

With pairs ".*/BTC" this issue is as likely as with the USDT, however is less likely with ".*/BNB". Using ".*/BTC":

freqtrade backtesting -c someConfig --strategy-list someStrategies -i 5m --timerange 20210501-202105**12** -> ERROR
freqtrade backtesting -c someConfig --strategy-list someStrategies -i 5m --timerange 20210501-202105**11** -> OK

If you want to, I could copy the full logs. I hope this info could be usefull.

versions:
pandas==1.2.4
arrow==1.1.0

**Comment by doza62** [comment]
I've been experiencing this problem as well. I found out the amount of strategies listed also affect this behavior. If the list is too long, it will break. If you just run a couple it works fine.

I'm thinking it could be a variable overflowing? maybe a trouble with arrow in that sense.

For now I will be running each backtest individually. In case it helps anybody:

`cat ~/.scripts/freqtrade/strategy-list.txt | xargs -I % freqtrade backtesting -i 4h --timerange 20210501-20210510 --strategy '%' --export trades`

File should look like:
![image](https://user-images.githubusercontent.com/14064394/118380822-e4101f00-b5b2-11eb-9995-b9442f9aa1ef.png)


In Hindsight, I think I'm going this way from now on... I can now stop mid backtesting if i need more resources for work and continue later form the last strategy analyzed. Happy accidents :)

**Comment by xmatthias** [comment]
if you get exactly the above error - then it's because no data is left (arrow fails on an empty date) - not because of resources.

**Comment by JackBananas** [comment]
Wha do you mean with no data is left?

I always run the `freqtrade download-data` command before running the backtesting.
