### ISSUE TITLE
Problem running Edge with informative pairs

### ISSUE THREAD

**Issue by Hsgngr** [freqtrade/freqtrade#4868]
The strategy works in backtesting but when I try go live it throws this error:

The important part is this:

```
2021-05-04 00:55:20,615 - freqtrade.data.dataprovider - WARNING - No data found for (ALGO/BTC, 1h).
2021-05-04 00:55:20,616 - freqtrade.commands.trade_commands - ERROR - input_arrays parameter missing required data keys: high, low, close
2021-05-04 00:55:20,616 - freqtrade.commands.trade_commands - ERROR - Fatal exception!

```
It wants to download 1h data however I already have it:

```
$ freqtrade list-data
2021-05-04 01:00:51,935 - freqtrade.configuration.configuration - INFO - Using config: config.json ...
2021-05-04 01:00:51,936 - freqtrade.loggers - INFO - Verbosity set to 0
2021-05-04 01:00:51,937 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/ege/Desktop/trade/freqtrade/user_data ...
2021-05-04 01:00:51,937 - freqtrade.configuration.configuration - INFO - Using data directory: /home/ege/Desktop/trade/freqtrade/user_data/data/binance ...
2021-05-04 01:00:51,937 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2021-05-04 01:00:52,017 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2021-05-04 01:00:52,018 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2021-05-04 01:00:52,018 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
Found 120 pair / timeframe combinations.
+-----------+----------------------+
|      Pair |            Timeframe |
|-----------+----------------------|
|   ADA/BTC | 1m, 5m, 15m, 30m, 1h |
|  ALGO/BTC | 1m, 5m, 15m, 30m, 1h |
|  ATOM/BTC | 1m, 5m, 15m, 30m, 1h |
|   BAT/BTC | 1m, 5m, 15m, 30m, 1h |
|   BCH/BTC | 1m, 5m, 15m, 30m, 1h |
|   BRD/BTC | 1m, 5m, 15m, 30m, 1h |
|  CAKE/BTC | 1m, 5m, 15m, 30m, 1h |
|   CHZ/BTC | 1m, 5m, 15m, 30m, 1h |
|   DAI/BTC | 1m, 5m, 15m, 30m, 1h |
|   DOT/BTC | 1m, 5m, 15m, 30m, 1h |
|   EOS/BTC | 1m, 5m, 15m, 30m, 1h |
|   ETH/BTC | 1m, 5m, 15m, 30m, 1h |
|  IOTA/BTC | 1m, 5m, 15m, 30m, 1h |
|  LINK/BTC | 1m, 5m, 15m, 30m, 1h |
|   LTC/BTC | 1m, 5m, 15m, 30m, 1h |
|  LUNA/BTC | 1m, 5m, 15m, 30m, 1h |
| MATIC/BTC | 1m, 5m, 15m, 30m, 1h |
|   MKR/BTC | 1m, 5m, 15m, 30m, 1h |
|   NEO/BTC | 1m, 5m, 15m, 30m, 1h |
|   NXS/BTC | 1m, 5m, 15m, 30m, 1h |
|   XLM/BTC | 1m, 5m, 15m, 30m, 1h |
|   XMR/BTC | 1m, 5m, 15m, 30m, 1h |
|   XRP/BTC | 1m, 5m, 15m, 30m, 1h |
|   XTZ/BTC | 1m, 5m, 15m, 30m, 1h |
+-----------+----------------------+
```

What is the problem, how can I solve this issue ?
Exchange Binance
System Ubuntu
Python 3.8.8

Here is the full error:
```
$ freqtrade trade --config user_data/cryptofrog.less_risk.json --strategy CryptoFrog
2021-05-04 00:54:38,921 - freqtrade.worker - INFO - Starting worker develop-b0bd7327
2021-05-04 00:54:38,921 - freqtrade.configuration.configuration - INFO - Using config: user_data/cryptofrog.less_risk.json ...
2021-05-04 00:54:38,922 - freqtrade.loggers - INFO - Verbosity set to 0
2021-05-04 00:54:38,922 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
2021-05-04 00:54:38,922 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2021-05-04 00:54:38,922 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:///dry_run_2.sqlite"
2021-05-04 00:54:38,922 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 5 ...
2021-05-04 00:54:38,922 - freqtrade.configuration.configuration - INFO - Using user-data directory: user_data ...
2021-05-04 00:54:38,922 - freqtrade.configuration.configuration - INFO - Using data directory: user_data/data/binance ...
2021-05-04 00:54:38,922 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2021-05-04 00:54:38,928 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2021-05-04 00:54:38,928 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2021-05-04 00:54:38,928 - freqtrade.freqtradebot - INFO - Starting freqtrade develop-b0bd7327
2021-05-04 00:54:38,942 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy CryptoFrog from '/home/ege/Desktop/trade/freqtrade/user_data/strategies/CryptoFrog.py'...
2021-05-04 00:54:38,943 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: BTC.
2021-05-04 00:54:38,943 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: unlimited.
2021-05-04 00:54:38,943 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'protections' with value in config file: [{'method': 'CooldownPeriod', 'stop_duration_candles': 1}, {'method': 'StoplossGuard', 'lookback_period_candles': 6, 'trade_limit': 2, 'stop_duration_candles': 1440, 'only_per_pair': True}].
2021-05-04 00:54:38,943 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'buy': 20, 'sell': 40}.
2021-05-04 00:54:38,943 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 0.18421, '14': 0.07798, '60': 0.03019, '180': 0}
2021-05-04 00:54:38,943 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 5m
2021-05-04 00:54:38,943 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.085
2021-05-04 00:54:38,943 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: True
2021-05-04 00:54:38,943 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive: 0.01
2021-05-04 00:54:38,943 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.047
2021-05-04 00:54:38,943 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2021-05-04 00:54:38,943 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: True
2021-05-04 00:54:38,943 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
2021-05-04 00:54:38,943 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'market', 'stoploss_on_exchange': False}
2021-05-04 00:54:38,943 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
2021-05-04 00:54:38,943 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: BTC
2021-05-04 00:54:38,943 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: unlimited
2021-05-04 00:54:38,943 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: [{'method': 'CooldownPeriod', 'stop_duration_candles': 1}, {'method': 'StoplossGuard', 'lookback_period_candles': 6, 'trade_limit': 2, 'stop_duration_candles': 1440, 'only_per_pair': True}]
2021-05-04 00:54:38,943 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 0
2021-05-04 00:54:38,943 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'buy': 20, 'sell': 40}
2021-05-04 00:54:38,943 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_sell_signal: True
2021-05-04 00:54:38,943 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_only: False
2021-05-04 00:54:38,943 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_buy_signal: False
2021-05-04 00:54:38,943 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_offset: 0.0
2021-05-04 00:54:38,943 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2021-05-04 00:54:38,943 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2021-05-04 00:54:38,943 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2021-05-04 00:54:38,945 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2021-05-04 00:54:38,945 - freqtrade.exchange.exchange - INFO - Using CCXT 1.47.61
2021-05-04 00:54:38,945 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2021-05-04 00:54:38,951 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 200}
2021-05-04 00:54:38,957 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2021-05-04 00:54:41,933 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2021-05-04 00:54:42,003 - freqtrade.wallets - INFO - Wallets synced.
2021-05-04 00:54:42,003 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from '/home/ege/Desktop/trade/freqtrade/freqtrade/plugins/pairlist/StaticPairList.py'...
2021-05-04 00:54:42,004 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist AgeFilter from '/home/ege/Desktop/trade/freqtrade/freqtrade/plugins/pairlist/AgeFilter.py'...
2021-05-04 00:54:42,006 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist PriceFilter from '/home/ege/Desktop/trade/freqtrade/freqtrade/plugins/pairlist/PriceFilter.py'...
2021-05-04 00:54:42,009 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist SpreadFilter from '/home/ege/Desktop/trade/freqtrade/freqtrade/plugins/pairlist/SpreadFilter.py'...
2021-05-04 00:54:42,011 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist RangeStabilityFilter from '/home/ege/Desktop/trade/freqtrade/freqtrade/plugins/pairlist/rangestabilityfilter.py'...
2021-05-04 00:54:42,024 - freqtrade.resolvers.iresolver - INFO - Using resolved protection CooldownPeriod from '/home/ege/Desktop/trade/freqtrade/freqtrade/plugins/protections/cooldown_period.py'...
2021-05-04 00:54:42,025 - freqtrade.resolvers.iresolver - INFO - Using resolved protection StoplossGuard from '/home/ege/Desktop/trade/freqtrade/freqtrade/plugins/protections/stoploss_guard.py'...
2021-05-04 00:54:42,025 - freqtrade.edge.edge_positioning - CRITICAL - max_open_trades should be -1 in config !
2021-05-04 00:54:42,584 - freqtrade.plugins.pairlist.IPairList - INFO - Ignoring DAI/BTC from whitelist. Market is not active.
2021-05-04 00:54:47,848 - AgeFilter - INFO - Validated 23 pairs.
2021-05-04 00:54:47,848 - SpreadFilter - INFO - Removed BRD/BTC from whitelist, because spread 0.619% > 0.3%
2021-05-04 00:54:47,849 - SpreadFilter - INFO - Removed NXS/BTC from whitelist, because spread 0.303% > 0.3%
2021-05-04 00:54:52,813 - RangeStabilityFilter - INFO - Removed BAT/BTC from whitelist, because rate of change over 3 days is 0.067, which is below the threshold of 0.1.
2021-05-04 00:54:52,816 - RangeStabilityFilter - INFO - Removed LTC/BTC from whitelist, because rate of change over 3 days is 0.061, which is below the threshold of 0.1.
2021-05-04 00:54:52,819 - RangeStabilityFilter - INFO - Removed XTZ/BTC from whitelist, because rate of change over 3 days is 0.087, which is below the threshold of 0.1.
2021-05-04 00:54:52,843 - freqtrade.edge.edge_positioning - INFO - Using stake_currency: BTC ...
2021-05-04 00:54:52,844 - freqtrade.edge.edge_positioning - INFO - Using local backtesting data (using whitelist in given config) ...
2021-05-04 00:54:52,844 - freqtrade.data.history.history_utils - INFO - Download history data for pair: "ALGO/BTC", timeframe: 5m and store in user_data/data/binance.
2021-05-04 00:54:53,656 - numexpr.utils - INFO - NumExpr defaulting to 8 threads.
2021-05-04 00:54:54,115 - freqtrade.exchange.exchange - INFO - Downloaded data for ALGO/BTC with length 111.
2021-05-04 00:54:54,737 - freqtrade.data.history.history_utils - INFO - Download history data for pair: "ATOM/BTC", timeframe: 5m and store in user_data/data/binance.
2021-05-04 00:54:55,961 - freqtrade.exchange.exchange - INFO - Downloaded data for ATOM/BTC with length 111.
2021-05-04 00:54:56,798 - freqtrade.data.history.history_utils - INFO - Download history data for pair: "BCH/BTC", timeframe: 5m and store in user_data/data/binance.
2021-05-04 00:54:57,804 - freqtrade.exchange.exchange - INFO - Downloaded data for BCH/BTC with length 111.
2021-05-04 00:54:58,330 - freqtrade.data.history.history_utils - INFO - Download history data for pair: "EOS/BTC", timeframe: 5m and store in user_data/data/binance.
2021-05-04 00:55:00,261 - freqtrade.exchange.exchange - INFO - Downloaded data for EOS/BTC with length 108.
2021-05-04 00:55:00,795 - freqtrade.data.history.history_utils - INFO - Download history data for pair: "ETH/BTC", timeframe: 5m and store in user_data/data/binance.
2021-05-04 00:55:01,797 - freqtrade.exchange.exchange - INFO - Downloaded data for ETH/BTC with length 109.
2021-05-04 00:55:02,118 - freqtrade.data.history.history_utils - INFO - Download history data for pair: "IOTA/BTC", timeframe: 5m and store in user_data/data/binance.
2021-05-04 00:55:03,023 - freqtrade.exchange.exchange - INFO - Downloaded data for IOTA/BTC with length 108.
2021-05-04 00:55:03,412 - freqtrade.data.history.history_utils - INFO - Download history data for pair: "LINK/BTC", timeframe: 5m and store in user_data/data/binance.
2021-05-04 00:55:04,254 - freqtrade.exchange.exchange - INFO - Downloaded data for LINK/BTC with length 109.
2021-05-04 00:55:04,599 - freqtrade.data.history.history_utils - INFO - Download history data for pair: "NEO/BTC", timeframe: 5m and store in user_data/data/binance.
2021-05-04 00:55:05,483 - freqtrade.exchange.exchange - INFO - Downloaded data for NEO/BTC with length 106.
2021-05-04 00:55:05,783 - freqtrade.data.history.history_utils - INFO - Download history data for pair: "XMR/BTC", timeframe: 5m and store in user_data/data/binance.
2021-05-04 00:55:06,712 - freqtrade.exchange.exchange - INFO - Downloaded data for XMR/BTC with length 105.
2021-05-04 00:55:07,002 - freqtrade.data.history.history_utils - INFO - Download history data for pair: "XRP/BTC", timeframe: 5m and store in user_data/data/binance.
2021-05-04 00:55:07,940 - freqtrade.exchange.exchange - INFO - Downloaded data for XRP/BTC with length 106.
2021-05-04 00:55:08,231 - freqtrade.data.history.history_utils - INFO - Download history data for pair: "ADA/BTC", timeframe: 5m and store in user_data/data/binance.
2021-05-04 00:55:08,863 - freqtrade.exchange.exchange - INFO - Downloaded data for ADA/BTC with length 112.
2021-05-04 00:55:09,032 - freqtrade.data.history.history_utils - INFO - Download history data for pair: "DOT/BTC", timeframe: 5m and store in user_data/data/binance.
2021-05-04 00:55:09,440 - freqtrade.exchange.exchange - INFO - Downloaded data for DOT/BTC with length 109.
2021-05-04 00:55:09,541 - freqtrade.data.history.history_utils - INFO - Download history data for pair: "XLM/BTC", timeframe: 5m and store in user_data/data/binance.
2021-05-04 00:55:10,091 - freqtrade.exchange.exchange - INFO - Downloaded data for XLM/BTC with length 106.
2021-05-04 00:55:10,259 - freqtrade.data.history.history_utils - INFO - Download history data for pair: "MKR/BTC", timeframe: 5m and store in user_data/data/binance.
2021-05-04 00:55:10,745 - freqtrade.exchange.exchange - INFO - Downloaded data for MKR/BTC with length 107.
2021-05-04 00:55:10,866 - freqtrade.data.history.history_utils - INFO - Download history data for pair: "MATIC/BTC", timeframe: 5m and store in user_data/data/binance.
2021-05-04 00:55:11,628 - freqtrade.exchange.exchange - INFO - Downloaded data for MATIC/BTC with length 108.
2021-05-04 00:55:11,820 - freqtrade.data.history.history_utils - INFO - Download history data for pair: "LUNA/BTC", timeframe: 5m and store in user_data/data/binance.
2021-05-04 00:55:12,549 - freqtrade.exchange.exchange - INFO - Downloaded data for LUNA/BTC with length 108.
2021-05-04 00:55:12,650 - freqtrade.data.history.history_utils - INFO - Download history data for pair: "CAKE/BTC", timeframe: 5m and store in user_data/data/binance.
2021-05-04 00:55:13,018 - freqtrade.exchange.exchange - INFO - Downloaded data for CAKE/BTC with length 111.
2021-05-04 00:55:13,056 - freqtrade.data.history.history_utils - INFO - Download history data for pair: "CHZ/BTC", timeframe: 5m and store in user_data/data/binance.
2021-05-04 00:55:13,775 - freqtrade.exchange.exchange - INFO - Downloaded data for CHZ/BTC with length 110.
2021-05-04 00:55:14,382 - freqtrade.data.converter - INFO - Missing data fillup for ALGO/BTC: before: 2821 - after: 2877 - 1.99 %
2021-05-04 00:55:14,827 - freqtrade.data.converter - INFO - Missing data fillup for ATOM/BTC: before: 2821 - after: 2877 - 1.99 %
2021-05-04 00:55:15,171 - freqtrade.data.converter - INFO - Missing data fillup for BCH/BTC: before: 2821 - after: 2877 - 1.99 %
2021-05-04 00:55:15,741 - freqtrade.data.converter - INFO - Missing data fillup for EOS/BTC: before: 2821 - after: 2877 - 1.99 %
2021-05-04 00:55:16,233 - freqtrade.data.converter - INFO - Missing data fillup for ETH/BTC: before: 2822 - after: 2878 - 1.98 %
2021-05-04 00:55:16,717 - freqtrade.data.converter - INFO - Missing data fillup for IOTA/BTC: before: 2821 - after: 2877 - 1.99 %
2021-05-04 00:55:17,286 - freqtrade.data.converter - INFO - Missing data fillup for LINK/BTC: before: 2822 - after: 2878 - 1.98 %
2021-05-04 00:55:17,771 - freqtrade.data.converter - INFO - Missing data fillup for NEO/BTC: before: 2821 - after: 2877 - 1.99 %
2021-05-04 00:55:18,332 - freqtrade.data.converter - INFO - Missing data fillup for XMR/BTC: before: 2821 - after: 2877 - 1.99 %
2021-05-04 00:55:18,821 - freqtrade.data.converter - INFO - Missing data fillup for XRP/BTC: before: 2822 - after: 2878 - 1.98 %
2021-05-04 00:55:19,161 - freqtrade.data.converter - INFO - Missing data fillup for ADA/BTC: before: 2822 - after: 2878 - 1.98 %
2021-05-04 00:55:19,339 - freqtrade.data.converter - INFO - Missing data fillup for DOT/BTC: before: 2822 - after: 2878 - 1.98 %
2021-05-04 00:55:19,625 - freqtrade.data.converter - INFO - Missing data fillup for XLM/BTC: before: 2822 - after: 2878 - 1.98 %
2021-05-04 00:55:19,808 - freqtrade.data.converter - INFO - Missing data fillup for MKR/BTC: before: 2822 - after: 2878 - 1.98 %
2021-05-04 00:55:20,137 - freqtrade.data.converter - INFO - Missing data fillup for MATIC/BTC: before: 2822 - after: 2878 - 1.98 %
2021-05-04 00:55:20,250 - freqtrade.data.converter - INFO - Missing data fillup for LUNA/BTC: before: 2822 - after: 2878 - 1.98 %
2021-05-04 00:55:20,349 - freqtrade.data.converter - INFO - Missing data fillup for CAKE/BTC: before: 2822 - after: 2878 - 1.98 %
2021-05-04 00:55:20,613 - freqtrade.data.converter - INFO - Missing data fillup for CHZ/BTC: before: 2822 - after: 2878 - 1.98 %
2021-05-04 00:55:20,615 - freqtrade.data.dataprovider - WARNING - No data found for (ALGO/BTC, 1h).
2021-05-04 00:55:20,616 - freqtrade.commands.trade_commands - ERROR - input_arrays parameter missing required data keys: high, low, close
2021-05-04 00:55:20,616 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/ege/Desktop/trade/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/home/ege/Desktop/trade/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/home/ege/Desktop/trade/freqtrade/freqtrade/worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/home/ege/Desktop/trade/freqtrade/freqtrade/freqtradebot.py", line 94, in __init__
    self.active_pair_whitelist = self._refresh_active_whitelist()
  File "/home/ege/Desktop/trade/freqtrade/freqtrade/freqtradebot.py", line 228, in _refresh_active_whitelist
    self.edge.calculate(_whitelist)
  File "/home/ege/Desktop/trade/freqtrade/freqtrade/edge/edge_positioning.py", line 124, in calculate
    preprocessed = self.strategy.ohlcvdata_to_dataframe(data)
  File "/home/ege/Desktop/trade/freqtrade/freqtrade/strategy/interface.py", line 670, in ohlcvdata_to_dataframe
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair})
  File "/home/ege/Desktop/trade/freqtrade/freqtrade/strategy/interface.py", line 670, in <dictcomp>
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair})
  File "/home/ege/Desktop/trade/freqtrade/freqtrade/strategy/interface.py", line 687, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/home/ege/Desktop/trade/freqtrade/user_data/strategies/CryptoFrog.py", line 290, in populate_indicators
    informative = self.do_indicators(informative.copy(), metadata)
  File "/home/ege/Desktop/trade/freqtrade/user_data/strategies/CryptoFrog.py", line 210, in do_indicators
    stoch_fast = ta.STOCHF(dataframe)
  File "talib/_abstract.pxi", line 398, in talib._ta_lib.Function.__call__
  File "talib/_abstract.pxi", line 270, in talib._ta_lib.Function.set_function_args
  File "talib/_abstract.pxi", line 221, in talib._ta_lib.Function.set_input_arrays
Exception: input_arrays parameter missing required data keys: high, low, close

```

**Comment by Hsgngr** [comment]
It went away when I removed the pair_whitelist pairs
```
    "exchange": {
        "name": "binance",
        "key": "",
        "secret": "",
        "ccxt_config": {"enableRateLimit": true},
        "ccxt_async_config": {
            "enableRateLimit": true,
            "rateLimit": 200
        },
        "pair_whitelist":[],
        "pair_blacklist": []
    },
```

However still didn't understand why that happened.

**Comment by xmatthias** [comment]
I don't think this will fix your problem (it will circumvent it - but not the way you expect it to).

by removing / emptying `pair_whitelist` - you're now runing without any pairs (your config uses StaticPairlist as provider, not volumepairlist) - so edge will do nothing as it has no base parameters.

The real problem is that you're using informative pairs - which is currently not supported for using edge as the data is not refreshed.
