### ISSUE TITLE
telegram error

### ISSUE THREAD

**Issue by ImBIOS** [freqtrade/freqtrade#4871]
```
2021-05-04 08:01:39,805 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.7/site-packages/telegram/ext/updater.py", line 516, in _network_loop_retry
    if not action_cb():
  File "/home/ftuser/.local/lib/python3.7/site-packages/telegram/ext/updater.py", line 471, in polling_action_cb
    allowed_updates=allowed_updates,
  File "/home/ftuser/.local/lib/python3.7/site-packages/telegram/bot.py", line 127, in decorator
    result = func(*args, **kwargs)
  File "/home/ftuser/.local/lib/python3.7/site-packages/telegram/bot.py", line 2762, in get_updates
    'getUpdates', data, timeout=float(read_latency) + float(timeout), api_kwargs=api_kwargs
  File "/home/ftuser/.local/lib/python3.7/site-packages/telegram/bot.py", line 260, in _post
    f'{self.base_url}/{endpoint}', data=data, timeout=effective_timeout
  File "/home/ftuser/.local/lib/python3.7/site-packages/telegram/utils/request.py", line 354, in post
    **urlopen_kwargs,
  File "/home/ftuser/.local/lib/python3.7/site-packages/telegram/utils/request.py", line 276, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
  ```

**Comment by xmatthias** [comment]
you've got 2 Telegram bots running (most likely, 2 freqtrade bots using the same telegram bot key).

The second bot will throw this error and refuse to start. Best register a new telegram bot for the 2nd instance your'e running.

if you're not running multiple bots - make sure that you've got no "leftover" instance running in the background.

**Comment by bigsee** [comment]
> most likely, 2 freqtrade bots using the same telegram bot key

Does this refer to the `chat_id` or `token`? Since I refresh the token between dry run and switching to live and I still get the same error (after starting the bot with `"initial_state": "stopped"`.

```
2021-07-03 13:49:07,327 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'stopped'}
2021-07-03 13:49:08,099 - freqtrade.worker - INFO - Changing state to: STOPPED
2021-07-03 13:49:11,147 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2021-07-03 13:49:11,150 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
```

> make sure that you've got no "leftover" instance running in the background.

Apologies for my ignorance: leftover instance of _what_? This happens after:

1. `docker-compose down`
2. Update config `"dry_run": false`
3. `docker-compose up -d`
4. `docker-compose run freqtrade trade -c user_data/config.json -c user_data/config-private.json -s MyStrategy`

Do we need to create a brand new Telegram chat every time?

**Comment by xmatthias** [comment]
No, absolutely not - and `docker-compose down` will free the telegram token - assuming this was the only bot using this token.
