### ISSUE TITLE
Backtesting stratetgies not working anymore : source code string cannot contain null bytes...  

### ISSUE THREAD

**Issue by ViddelD** [freqtrade/freqtrade#4927]
## Describe your environment

  * Operating system:   Ubuntu 20.04.2 LTS
  * Python Version: __3.8.5_ (`python -V`)
  * CCXT version: _ccxt==1.49.73_ (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade develop-84222c89 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
Hi 
Since, my last and before last update of freqtrade made last week and today, some of my strategies can't be backtested anymore. So, i tried a lot of things but even the "sampleStrategy" is not working either...  I'm run out of idea how to fix that. Probably i did something wrong ?

LOGS:
(.env) xxxx@Lin-Test:~/freqtrade$ freqtrade backtesting -c configtest.json --strategy SampleStrategy --timeframe 30m --timerange=20210402-
2021-05-13 18:23:41,097 - freqtrade.configuration.configuration - INFO - Using config: configtest.json ...
2021-05-13 18:23:41,097 - freqtrade.loggers - INFO - Verbosity set to 0
2021-05-13 18:23:41,098 - freqtrade.configuration.configuration - INFO - Parameter -i/--timeframe detected ... Using timeframe: 30m ...
2021-05-13 18:23:41,098 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 20 ...
2021-05-13 18:23:41,098 - freqtrade.configuration.configuration - INFO - Parameter --timerange detected: 20210402- ...
2021-05-13 18:23:41,098 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/tutu/freqtrade/user_data ...
2021-05-13 18:23:41,098 - freqtrade.configuration.configuration - INFO - Using data directory: /home/tutu/freqtrade/user_data/data/binance ...
2021-05-13 18:23:41,098 - freqtrade.configuration.configuration - INFO - Overriding timeframe with Command line argument
2021-05-13 18:23:41,098 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2021-05-13 18:23:41,105 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2021-05-13 18:23:41,105 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2021-05-13 18:23:41,106 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2021-05-13 18:23:41,108 - freqtrade.commands.optimize_commands - INFO - Starting freqtrade in Backtesting mode
2021-05-13 18:23:41,108 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2021-05-13 18:23:41,108 - freqtrade.exchange.exchange - INFO - Using CCXT 1.49.73
2021-05-13 18:23:41,108 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2021-05-13 18:23:41,117 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 500}
2021-05-13 18:23:41,124 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2021-05-13 18:23:41,962 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2021-05-13 18:23:42,053 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/tutu/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/home/tutu/freqtrade/freqtrade/commands/optimize_commands.py", line 52, in start_backtesting
    backtesting = Backtesting(config)
  File "/home/tutu/freqtrade/freqtrade/optimize/backtesting.py", line 77, in __init__
    self.strategylist.append(StrategyResolver.load_strategy(self.config))
  File "/home/tutu/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 45, in load_strategy
    strategy: IStrategy = StrategyResolver._load_strategy(
  File "/home/tutu/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 190, in _load_strategy
    strategy = StrategyResolver._load_object(paths=abs_paths,
  File "/home/tutu/freqtrade/freqtrade/resolvers/iresolver.py", line 114, in _load_object
    (module, module_path) = cls._search_object(directory=_path,
  File "/home/tutu/freqtrade/freqtrade/resolvers/iresolver.py", line 96, in _search_object
    obj = next(cls._get_valid_object(module_path, object_name), None)
  File "/home/tutu/freqtrade/freqtrade/resolvers/iresolver.py", line 63, in _get_valid_object
    spec.loader.exec_module(module)  # type: ignore # importlib does not use typehints
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ValueError: source code string cannot contain null bytes

Thanks in advance for your help

**Comment by xmatthias** [comment]
well apparently one of your strategy contains a null byte.
that's usually a red-flag character .... you're best of by moving all  your strategies out of your strategy folder, and moving them back one by one to figure out which strategy is causing this.

it won't be an update of freqtrade though - but a character / (probably non-visible) character in one of the strategies.

**Comment by herculosh** [comment]
I often have a similar error, at least strategy could not be load, when copying a Python file from my Mac to the Linux system using SMB. There are then shadow files with the prefix ._ or _. generated. Deleting them if they are present can also help.

**Comment by ViddelD** [comment]
Hi guys ! Y'r incredible ! I removed everything from my strat folder and then i found the gulty one... (wich was something imported...)  So all my strats are working again :)

I would like to address my most sincere thanks not only for the incredible support but for the all thing ! I hope a day i can contribue more to this incredible piece of work ! 

Thanks !

**Comment by ViddelD** [comment]
Just an add on : I found the problem it comes from "copy past between my windows browser and my linux."  You need to create and save a file first before importing everything under linux.
