### ISSUE TITLE
Freqtrade Plot TypeError: 'set' object does not support item assignment

### ISSUE THREAD

**Issue by NicolasGuigui** [freqtrade/freqtrade#4937]
## Describe your environment

  * Operating system: Ubuntu 20.10 and Windows 10 (tested on both operating system and same results)
  * Python Version: Python 3.8.6
  * CCXT version: ccxt==1.47.47
  * Freqtrade Version: freqtrade develop-09b6923e
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:
Hi,

I tried to plot my strategy but I'm having an issue as you can see the ouptut of the command below:

```
 File "/home/ubuntu/freqtrade/freqtrade/plot/plotting.py", line 262, in create_plotconfig
     plot_config['main_plot'] = {}
 TypeError: 'set' object does not support item assignment
```

Am I doing something wrong or is it a mistake? For information, the strategy is running in paper mode and the error is also encountered with the SampleStrategy strategy and the default config file created with the command `freqtrade new-config --config config.json`

### Steps to reproduce:

  1. source .env/bin/activate
 
  2. freqtrade plot-dataframe --strategy MASimple1H                                                                                                                                                         -p VTHO/BNB --config configMASimple1H.json

  
### Observed Results:

  * What happened?
 ```2021-05-14 16:32:09,430 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/ubuntu/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/home/ubuntu/freqtrade/freqtrade/commands/plot_commands.py", line 24, in start_plot_dataframe
    load_and_plot_trades(config)
  File "/home/ubuntu/freqtrade/freqtrade/plot/plotting.py", line 546, in load_and_plot_trades
    fig = generate_candlestick_graph(
  File "/home/ubuntu/freqtrade/freqtrade/plot/plotting.py", line 344, in generate_candlestick_graph
    plot_config = create_plotconfig(indicators1, indicators2, plot_config)
  File "/home/ubuntu/freqtrade/freqtrade/plot/plotting.py", line 262, in create_plotconfig
    plot_config['main_plot'] = {}
TypeError: 'set' object does not support item assignment
```
  * What did you expect to happen?
  A HTML file creation with the plot

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
ubuntu@ubuntu:~/freqtrade$ source .env/bin/activate
(.env) ubuntu@ubuntu:~/freqtrade$ freqtrade plot-dataframe --strategy MASimple1H                                                                                                                                                              -p VTHO/BNB --config configMASimple1H.json
2021-05-14 16:32:05,723 - freqtrade.configuration.configuration - INFO - Using config: configMASimple1H.json ...
2021-05-14 16:32:05,727 - freqtrade.loggers - INFO - Verbosity set to 0
2021-05-14 16:32:05,730 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/ubuntu/freqtrade/user_data ...
2021-05-14 16:32:05,732 - freqtrade.configuration.configuration - INFO - Using data directory: /home/ubuntu/freqtrade/user_data/data/binance ...
2021-05-14 16:32:05,733 - freqtrade.configuration.configuration - INFO - Using pairs ['VTHO/BNB']
2021-05-14 16:32:05,733 - freqtrade.configuration.configuration - INFO - Limiting plot to: 750
2021-05-14 16:32:05,733 - freqtrade.configuration.configuration - INFO - Using trades from: file
2021-05-14 16:32:05,734 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2021-05-14 16:32:05,791 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2021-05-14 16:32:05,791 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2021-05-14 16:32:05,907 - freqtrade.resolvers.iresolver - WARNING - Could not import /home/ubuntu/freqtrade/user_data/strategies/GodStra.py due to 'No mo                                                                                    dule named 'ta''
2021-05-14 16:32:05,919 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy MASimple1H from '/home/ubuntu/freqtrade/user_data/strategies/MAS                                                                                    imple1H.py'...
2021-05-14 16:32:05,920 - freqtrade.strategy.hyper - INFO - No params for buy found, using default values.
2021-05-14 16:32:05,922 - freqtrade.strategy.hyper - INFO - No params for sell found, using default values.
2021-05-14 16:32:05,924 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 1h.
2021-05-14 16:32:05,926 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: BNB.
2021-05-14 16:32:05,926 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: unlimited.
2021-05-14 16:32:05,927 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'buy': 10, 'sell                                                                                    ': 30}.
2021-05-14 16:32:05,928 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'use_sell_signal' with value in config file: True.
2021-05-14 16:32:05,928 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'sell_profit_only' with value in config file: False.
2021-05-14 16:32:05,929 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ignore_roi_if_buy_signal' with value in config file: False.
2021-05-14 16:32:05,929 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 0.15}
2021-05-14 16:32:05,930 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 1h
2021-05-14 16:32:05,930 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.03
2021-05-14 16:32:05,931 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: True
2021-05-14 16:32:05,931 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive: 0.01
2021-05-14 16:32:05,931 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.015
2021-05-14 16:32:05,932 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: True
2021-05-14 16:32:05,932 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2021-05-14 16:32:05,933 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
2021-05-14 16:32:05,934 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'marke                                                                                    t', 'stoploss_on_exchange': False}
2021-05-14 16:32:05,935 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
2021-05-14 16:32:05,935 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: BNB
2021-05-14 16:32:05,936 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: unlimited
2021-05-14 16:32:05,936 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 30
2021-05-14 16:32:05,936 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'buy': 10, 'sell': 30}
2021-05-14 16:32:05,937 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_sell_signal: True
2021-05-14 16:32:05,937 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_only: False
2021-05-14 16:32:05,938 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_buy_signal: False
2021-05-14 16:32:05,938 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_offset: 0.0
2021-05-14 16:32:05,938 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2021-05-14 16:32:05,939 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2021-05-14 16:32:05,940 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2021-05-14 16:32:05,940 - freqtrade.exchange.exchange - INFO - Using CCXT 1.47.47
2021-05-14 16:32:05,941 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2021-05-14 16:32:06,000 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 200}
2021-05-14 16:32:06,058 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2021-05-14 16:32:08,957 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2021-05-14 16:32:08,975 - freqtrade.data.history.history_utils - INFO - Using indicator startup period: 30 ...
2021-05-14 16:32:09,080 - numexpr.utils - INFO - NumExpr defaulting to 4 threads.
2021-05-14 16:32:09,294 - freqtrade.plot.plotting - INFO - Loading data from 2020-07-17 09:00:00+00:00 to 2021-04-19 14:00:00+00:00
2021-05-14 16:32:09,295 - freqtrade.configuration.timerange - WARNING - Moving start-date by 30 candles to account for startup time.
2021-05-14 16:32:09,298 - freqtrade.data.btanalysis - INFO - Loading backtest result from /home/ubuntu/freqtrade/user_data/backtest_results/backtest-resu                                                                                    lt-2021-04-20_19-28-00.json
2021-05-14 16:32:09,354 - freqtrade.plot.plotting - INFO - analyse pair VTHO/BNB
2021-05-14 16:32:09,430 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/ubuntu/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/home/ubuntu/freqtrade/freqtrade/commands/plot_commands.py", line 24, in start_plot_dataframe
    load_and_plot_trades(config)
  File "/home/ubuntu/freqtrade/freqtrade/plot/plotting.py", line 546, in load_and_plot_trades
    fig = generate_candlestick_graph(
  File "/home/ubuntu/freqtrade/freqtrade/plot/plotting.py", line 344, in generate_candlestick_graph
    plot_config = create_plotconfig(indicators1, indicators2, plot_config)
  File "/home/ubuntu/freqtrade/freqtrade/plot/plotting.py", line 262, in create_plotconfig
    plot_config['main_plot'] = {}
TypeError: 'set' object does not support item assignment
(.env) ubuntu@ubuntu:~/freqtrade$ python -V
Python 3.8.6
(.env) ubuntu@ubuntu:~/freqtrade$ pip freeze | grep ccxt
ccxt==1.47.47
(.env) ubuntu@ubuntu:~/freqtrade$

  ```

**Comment by xmatthias** [comment]
this sounds like you've got a `plot_config` configuration in your strategy which somehow screates a set - probably something like `{'main_plot'}` (this is a set with 1 element, not a dictionary as expected).

as the strategy is user-provided and can contain "whatever" you want - we can only protect from this so far ... and without the relevant part of the strategy, i can't say what the problem might be (i took a guess above - but i'm obviously not sure).

**Comment by NicolasGuigui** [comment]
Hi @xmatthias,

Indeed you are right, so the issue was rather between the chair and the keyboard :)

I take this ticket before closing it to greatly thank you for this tool which is very useful to me!

Have a good day
