### ISSUE TITLE
hyperopt-show shows error after the results

### ISSUE THREAD

**Issue by NecroJogn** [freqtrade/freqtrade#4952]
## Describe your environment

  * Operating system: Ubuntu 20.04
  * Python Version: 3.8.5 
  * CCXT version: 1.49.73 
  * Freqtrade Version: develop-e1447f95 
  

## Describe the problem:

Having run a hyperopt and using hyperopt-show to check the results of a specific epoch returns the values, but is followed by an error message. This has been tested with various strategies.

### Steps to reproduce:

  1. hyperopt a strategy (have tested with SMAOffset, Solipsis_v5, SwingHighToSkyHyperStrategy, MoniGoManiHyperStrategy)
  2. run a "freqtrade hyperopt-show -n XX" 
  3. see the error after the results of the specific epoch
  
### Observed Results:

The results seem to be working, but are followed by error message-

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
    # Sell hyperspace params:
    sell_params = {
        "csell_bail_how": "time",
        "csell_bail_roc": -3.912,
        "csell_bail_time": "1236",
        "csell_bail_time_trend": False,
        "csell_loss_threshold": -0.036,
        "csell_pullback": False,
        "csell_pullback_amount": 0.029,
        "csell_pullback_respect_roi": True,
        "csell_roi_end": 0.007,
        "csell_roi_start": 0.045,
        "csell_roi_time": "1288",
        "csell_roi_type": "decay",
        "csell_trend_type": "rmi",
    }
2021-05-16 22:06:59,136 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/johannes/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/home/johannes/freqtrade/freqtrade/commands/hyperopt_commands.py", line 135, in start_hyperopt_show
    HyperoptTools.print_epoch_details(val, total_epochs, print_json, no_header,
  File "/home/johannes/freqtrade/freqtrade/optimize/hyperopt_tools.py", line 104, in print_epoch_details
    HyperoptTools._params_pretty_print(params, 'roi', "ROI table:")
  File "/home/johannes/freqtrade/freqtrade/optimize/hyperopt_tools.py", line 131, in _params_pretty_print
    space_params = HyperoptTools._space_params(params, space, 5)
  File "/home/johannes/freqtrade/freqtrade/optimize/hyperopt_tools.py", line 162, in _space_params
    return round_dict(d, r) if r else d
  File "/home/johannes/freqtrade/freqtrade/misc.py", line 147, in round_dict
    return {k: (round(v, n) if isinstance(v, float) else v) for k, v in d.items()}
AttributeError: 'str' object has no attribute 'items'

  ```

**Comment by Rikj000** [comment]
This occurred to me too when using `freqtrade hyperopt-show -n <epoch of choice>`  on recent results from MoniGoMani,

Here is the StackTrace I got:
```bash
2021-05-15 14:59:09,044 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/mnt/Windows/Users/Rik/Desktop/Rikj-Home/Projects/Freqtrade-Git/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/mnt/Windows/Users/Rik/Desktop/Rikj-Home/Projects/Freqtrade-Git/freqtrade/commands/hyperopt_commands.py", line 135, in start_hyperopt_show
    HyperoptTools.print_epoch_details(val, total_epochs, print_json, no_header,
  File "/mnt/Windows/Users/Rik/Desktop/Rikj-Home/Projects/Freqtrade-Git/freqtrade/optimize/hyperopt_tools.py", line 104, in print_epoch_details
    HyperoptTools._params_pretty_print(params, 'roi', "ROI table:")
  File "/mnt/Windows/Users/Rik/Desktop/Rikj-Home/Projects/Freqtrade-Git/freqtrade/optimize/hyperopt_tools.py", line 131, in _params_pretty_print
    space_params = HyperoptTools._space_params(params, space, 5)
  File "/mnt/Windows/Users/Rik/Desktop/Rikj-Home/Projects/Freqtrade-Git/freqtrade/optimize/hyperopt_tools.py", line 162, in _space_params
    return round_dict(d, r) if r else d
  File "/mnt/Windows/Users/Rik/Desktop/Rikj-Home/Projects/Freqtrade-Git/freqtrade/misc.py", line 147, in round_dict
    return {k: (round(v, n) if isinstance(v, float) else v) for k, v in d.items()}
AttributeError: 'str' object has no attribute 'items'
```
This I tested this on commit `a6c64416`

**Comment by Ichibot200** [comment]
I still had this issue. I propose changes to ./freqtrade/optimize/hyperopt_tools.py
```python
import ast
def _space_params(params, space: str, r: int = None) -> Dict:
        d = params.get(space)
        if d:
            d = ast.literal_eval(d) if type(d) is not dict else d
            # Round floats to `r` digits after the decimal point if requested
            return round_dict(d, r) if r else d
        return {}
```
**EDIT:** If I am right, this Exception will be triggered with Hyperopts done before 6aa574fa2b0095f64c946955397b4d7c152fabc8 commit.

**Comment by xmatthias** [comment]
As that was only an intermediate version in develop and not a released one - please repeat your hyperopt files.

old files (pickle files) and new results will work correctly.
