### ISSUE TITLE
Error on plotprofit live trade

### ISSUE THREAD

**Issue by acarli82** [freqtrade/freqtrade#4974]
Hi,
i have tried to plot profit of real trade with this command:

freqtrade plot-profit --db-url sqlite:///tradesv3.sqlite --trade-source DB 

but i receive this error:

-05-18 22:12:46,151 - freqtrade.configuration.configuration - INFO - Using config: config.json ...
2021-05-18 22:12:46,153 - freqtrade.loggers - INFO - Verbosity set to 0
2021-05-18 22:12:46,155 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/andrea/freqtrade/user_data ...
2021-05-18 22:12:46,156 - freqtrade.configuration.configuration - INFO - Using data directory: /home/andrea/freqtrade/user_data/data/binance ...
2021-05-18 22:12:46,156 - freqtrade.configuration.configuration - INFO - Using trades from: DB
2021-05-18 22:12:46,157 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2021-05-18 22:12:46,169 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2021-05-18 22:12:46,169 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2021-05-18 22:12:46,169 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2021-05-18 22:12:46,172 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2021-05-18 22:12:46,173 - freqtrade.exchange.exchange - INFO - Using CCXT 1.48.76
2021-05-18 22:12:46,173 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2021-05-18 22:12:46,185 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 200}
2021-05-18 22:12:46,197 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2021-05-18 22:12:47,580 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2021-05-18 22:12:47,688 - numexpr.utils - INFO - NumExpr defaulting to 1 threads.
2021-05-18 22:12:49,003 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/andrea/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/home/andrea/freqtrade/freqtrade/commands/plot_commands.py", line 36, in start_plot_profit
    plot_profit(config)
  File "/home/andrea/freqtrade/freqtrade/plot/plotting.py", line 569, in plot_profit
    plot_elements = init_plotscript(config, list(exchange.markets))
  File "/home/andrea/freqtrade/freqtrade/plot/plotting.py", line 76, in init_plotscript
    strategy=config.get('strategy'),
  File "/home/andrea/freqtrade/freqtrade/data/btanalysis.py", line 276, in load_trades
    return load_trades_from_db(db_url)
  File "/home/andrea/freqtrade/freqtrade/data/btanalysis.py", line 249, in load_trades_from_db
    init_db(db_url, clean_open_orders=False)
  File "/home/andrea/freqtrade/freqtrade/persistence/models.py", line 53, in init_db
    engine = create_engine(db_url, **kwargs)
  File "<string>", line 2, in create_engine
  File "/home/andrea/freqtrade/.env/lib/python3.7/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "/home/andrea/freqtrade/.env/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 520, in create_engine
    u, plugins, kwargs = u._instantiate_plugins(kwargs)
AttributeError: 'NoneType' object has no attribute '_instantiate_plugins'

**Comment by xmatthias** [comment]
It somehow sounds like the sqlite file is somehow invalid.
Maybe the file is incomplete / there's some problems with permissions - or your dependencies are somewhat outdated.

Either way - please also fill out the issue template (the one you probably deleted when opening this issue) - as it'll tell us which version you're running and will simplify helping.
