### ISSUE TITLE
API issue on binance

### ISSUE THREAD

**Issue by klara31** [freqtrade/freqtrade#4991]
## Describe your environment

  * Operating system: Linux Docker
  * Freqtrade Version: 2021.4
  
## Describe the problem:

I am seeing a lot of errors on trades through Binance. When checking in the binance app, I can see that an order has been completely fulfilled. However, freqtrade logs claim that the order does not exist. It looks like this issue mainly occurs when a few trades in a short period are being processed. After a while, the errors go away, but the trade is not visible in the closed trades overview.

### Steps to reproduce:

  1. Let freqtade place an order
  
### Observed Results:

The order is processed by Binance, but freqtrade does not pick this up.

### Relevant code exceptions or logs

```
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 606, in fetch
    response.raise_for_status()
  File "/home/ftuser/.local/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order?timestamp=1621609279176&recvWindow=5000&symbol=BNBBTC&orderId=1057819362&signature=xxxxx

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/exchange.py", line 1132, in fetch_order
    return self._api.fetch_order(order_id, pair)
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/binance.py", line 1965, in fetch_order
    response = getattr(self, method)(self.extend(request, query))
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 474, in inner
    return entry(_self, **inner_kwargs)
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/binance.py", line 2975, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 495, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 622, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/binance.py", line 2969, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions, error, feedback)
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 513, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.OrderNotFound: binance {"code":-2013,"msg":"Order does not exist."}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/freqtradebot.py", line 992, in check_handle_timedout
    order = self.exchange.fetch_order(trade.open_order_id, trade.pair)
  File "/freqtrade/freqtrade/exchange/common.py", line 101, in wrapper
    return wrapper(*args, **kwargs)
  File "/freqtrade/freqtrade/exchange/common.py", line 101, in wrapper
    return wrapper(*args, **kwargs)
  File "/freqtrade/freqtrade/exchange/common.py", line 101, in wrapper
    return wrapper(*args, **kwargs)
  [Previous line repeated 2 more times]
  File "/freqtrade/freqtrade/exchange/common.py", line 104, in wrapper
    raise ex
  File "/freqtrade/freqtrade/exchange/common.py", line 89, in wrapper
    return f(*args, **kwargs)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 1134, in fetch_order
    raise RetryableOrderError(
freqtrade.exceptions.RetryableOrderError: Order not found (pair: BNB/BTC id: 1057819362). Message: binance {"code":-2013,"msg":"Order does not exist."}

2021-05-21 17:01:20,432 - freqtrade.exchange.common - WARNING - fetch_order() returned exception: "Order not found (pair: BNB/BTC id: 1057819362). Message: binance {"code":-2013,"msg":"Order does not exist."}"
2021-05-21 17:01:20,432 - freqtrade.exchange.common - WARNING - retrying fetch_order() still for 4 times
2021-05-21 17:01:20,433 - freqtrade.exchange.common - INFO - Applying DDosProtection backoff delay: 2

```
The above is repeated constantly. The pair is shown with ** marking. 
After a while, it looks like the request does get a good result (?) as the log does not show the error anymore. The pair does then not appear anymore in the open trades list, but neither in the closed trades overview. Binance shows a fulfilled trade with the mentioned orderid.

I have tried to access the URL ```https://api.binance.com/api/v3/order?timestamp=1621609279176&recvWindow=5000&symbol=BNBBTC&orderId=1057819362&signature=xxxx```, which generates the following error:
```
# curl "https://api.binance.com/api/v3/order?timestamp=1621609279176&recvWindow=5000&symbol=BNBBTC&orderId=1057819362&signature=xxxxx"
{"code":-2014,"msg":"API-key format invalid."}
```

**Comment by xmatthias** [comment]
you can't access an API url directly, so that error is fine.

You can fetch that order with the following snippet:

``` python
import ccxt
exchange = ccxt.binance({'apiKey': '<yourApiKey>', 'secret': '<yoursecret>' })
res = exchange.fetch_order(1057819362, 'BNB/BTC')
print(res)
```

---

Unfortunately, it's a known problem with Binance in times of high volume / high load - where their API will not return a perfectly valid order (which may eventually also be filled) - for multiple seconds (sometimes also minutes).

As it's a "quirk" in the binance API, there's nothing we can do here (they claim it's intentional this way and not a bug in their dev forums) - and if the order filled, then freqtrade will usually catch up to this correctly.


If that's not what you experience, we'll need a more complete log (most likely once these errors disappear) - as apparently the bot somehow thought the order was cancelled (if a buy-order is canceled, the trade is deleted).

**Comment by klara31** [comment]
The last is the case. 
The code snippet works: it retrieves the order with its statistics. The sell-order was NOT cancelled but fulfilled completely by Binance. However, the trade does not show up on the closed trades view.

The last error messages in the log are:
```
2021-05-21 17:04:02,496 - freqtrade.exchange.common - WARNING - fetch_order() returned exception: "Order not found (pair: BNB/BTC id: 1057819362). Message: binance {"code":-2013,"msg":"Order does not exist."}"
2021-05-21 17:04:02,496 - freqtrade.exchange.common - WARNING - Giving up retrying: fetch_order()
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/ftuser/.local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/ftuser/.local/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/ftuser/.local/lib/python3.9/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/home/ftuser/.local/lib/python3.9/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/freqtrade/freqtrade/rpc/api_server/api_v1.py", line 80, in status
    return rpc._rpc_trade_status()
  File "/freqtrade/freqtrade/rpc/rpc.py", line 170, in _rpc_trade_status
    order = self._freqtrade.exchange.fetch_order(trade.open_order_id, trade.pair)
  File "/freqtrade/freqtrade/exchange/common.py", line 101, in wrapper
    return wrapper(*args, **kwargs)
  File "/freqtrade/freqtrade/exchange/common.py", line 101, in wrapper
    return wrapper(*args, **kwargs)
  File "/freqtrade/freqtrade/exchange/common.py", line 101, in wrapper
    return wrapper(*args, **kwargs)
  [Previous line repeated 2 more times]
  File "/freqtrade/freqtrade/exchange/common.py", line 104, in wrapper
    raise ex
  File "/freqtrade/freqtrade/exchange/common.py", line 89, in wrapper
    return f(*args, **kwargs)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 1134, in fetch_order
    raise RetryableOrderError(
freqtrade.exceptions.RetryableOrderError: Order not found (pair: BNB/BTC id: 1057819362). Message: binance {"code":-2013,"msg":"Order does not exist."}
2021-05-21 17:04:02,497 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/ftuser/.local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/ftuser/.local/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/ftuser/.local/lib/python3.9/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/home/ftuser/.local/lib/python3.9/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/freqtrade/freqtrade/rpc/api_server/api_v1.py", line 80, in status
    return rpc._rpc_trade_status()
  File "/freqtrade/freqtrade/rpc/rpc.py", line 170, in _rpc_trade_status
    order = self._freqtrade.exchange.fetch_order(trade.open_order_id, trade.pair)
  File "/freqtrade/freqtrade/exchange/common.py", line 101, in wrapper
    return wrapper(*args, **kwargs)
  File "/freqtrade/freqtrade/exchange/common.py", line 101, in wrapper
    return wrapper(*args, **kwargs)
  File "/freqtrade/freqtrade/exchange/common.py", line 101, in wrapper
    return wrapper(*args, **kwargs)
  [Previous line repeated 2 more times]
  File "/freqtrade/freqtrade/exchange/common.py", line 104, in wrapper
    raise ex
  File "/freqtrade/freqtrade/exchange/common.py", line 89, in wrapper
    return f(*args, **kwargs)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 1134, in fetch_order
    raise RetryableOrderError(
freqtrade.exceptions.RetryableOrderError: Order not found (pair: BNB/BTC id: 1057819362). Message: binance {"code":-2013,"msg":"Order does not exist."}
2021-05-21 17:04:06,459 - AgeFilter - INFO - Validated 19 pairs.
2021-05-21 17:04:12,400 - AgeFilter - INFO - Validated 19 pairs.
2021-05-21 17:04:16,437 - AgeFilter - INFO - Validated 19 pairs.
2021-05-21 17:04:21,462 - AgeFilter - INFO - Validated 19 pairs.
2021-05-21 17:04:26,504 - AgeFilter - INFO - Validated 19 pairs.
2021-05-21 17:04:31,466 - AgeFilter - INFO - Validated 19 pairs.
2021-05-21 17:04:36,440 - AgeFilter - INFO - Validated 19 pairs.
2021-05-21 17:04:41,435 - AgeFilter - INFO - Validated 19 pairs.
2021-05-21 17:04:46,150 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2021.4', state='RUNNING'
2021-05-21 17:04:46,459 - AgeFilter - INFO - Validated 19 pairs.
2021-05-21 17:04:51,440 - AgeFilter - INFO - Validated 19 pairs.
2021-05-21 17:04:56,458 - AgeFilter - INFO - Validated 19 pairs.
2021-05-21 17:05:02,544 - AgeFilter - INFO - Validated 19 pairs.
2021-05-21 17:05:10,027 - AgeFilter - INFO - Validated 19 pairs.
2021-05-21 17:05:15,047 - AgeFilter - INFO - Validated 19 pairs.
2021-05-21 17:05:20,027 - AgeFilter - INFO - Validated 19 pairs.
...
```
The sell order was placed at 16:50. config.json has:
```
    "unfilledtimeout": {
        "buy": 10,
        "sell": 30
    },
``

**Comment by klara31** [comment]
And after a while the sell trade does show up in the closed trades… weird…

**Comment by xmatthias** [comment]
i assume that happens once the bot realizes that the trade was filled. (as this is a known problem, there's quite some logic behind to recover from this "binance quirk" ...

**Comment by klara31** [comment]
I guess I need a bit more patience…
