### ISSUE TITLE
How to integrate Stepped Stoploss to the standard BbandRsi strategy?

### ISSUE THREAD

**Issue by castalia3** [freqtrade/freqtrade#5025]
## Describe your environment

  * Operating system: Raspbian on Raspberry Pi4 8 GB RAM
  * Python Version: Pyhton 3.7.3
  * CCXT version: 1.50.6
  * Freqtrade Version: 2021.4 stable
  
## Your question

Hi, 
I would like to know how to implement the stepped stoploss function to the standard BbandRsi Strategy for a backtesting.
This is the strategy I am using right now: 

```
 
# --- Do not remove these libs ---
from freqtrade.strategy.interface import IStrategy
from pandas import DataFrame
import talib.abstract as ta
import freqtrade.vendor.qtpylib.indicators as qtpylib


# --------------------------------


class BbandRsiDT(IStrategy):


    converted from:

    https://github.com/sthewissen/Mynt/blob/master/src/Mynt.Core/Strategies/BbandRsi.cs


    # Minimal ROI designed for the strategy.
    # adjust based on market conditions. We would recommend to keep it low for quick turn arounds
    # This attribute will be overridden if the config file contains "minimal_roi"
    minimal_roi = {
        "0": 1.0
    }

    # Optimal stoploss designed for the strategy
    stoploss = -0.3

    # Optimal timeframe for the strategy
    timeframe = '15m'

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe['rsi'] = ta.RSI(dataframe, timeperiod=14)

        # Bollinger bands
        bollinger = qtpylib.bollinger_bands(qtpylib.typical_price(dataframe), window=20, stds=2)
        dataframe['bb_lowerband'] = bollinger['lower']
        dataframe['bb_middleband'] = bollinger['mid']
        dataframe['bb_upperband'] = bollinger['upper']

        return dataframe


    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                    (dataframe['rsi']  <30) &
                    (dataframe['close'] < dataframe['bb_lowerband'])

            ),
            'buy'] = 1
        return dataframe

    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                    (dataframe['rsi']  > 70 )

            ),
            'sell'] = 1
        return dataframe
`
```
This is the configuration file: 

`
```
{
    "max_open_trades": 30,
    "stake_currency": "EUR",
    "stake_amount": 50,
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "timeframe": "15m",
    "dry_run": true,
    "cancel_open_orders_on_exit": true,
    "unfilledtimeout": {
        "buy": 10,
        "sell": 30
    },
    "bid_strategy": {
        "ask_last_balance": 0.0,
        "use_order_book": false,
        "order_book_top": 1,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "ask_strategy": {
        "use_order_book": false,
        "order_book_min": 1,
        "order_book_max": 1,
        "use_sell_signal": true,
        "sell_profit_only": false,
        "ignore_roi_if_buy_signal": true
    },
    "exchange": {
        "name": "binance",
        "key": "my_public_key",
        "secret": "my_private_key",
        "ccxt_config": {"enableRateLimit": true},
        "ccxt_async_config": {
            "enableRateLimit": true,
            "rateLimit": 200
        },
        "pair_whitelist": [
            "ETH/EUR",
            "BTC/EUR",
            "MATIC/EUR",
            "ADA/EUR",
            "DOGE/EUR",
            "XRP/EUR",
            "VET/EUR",
            "DOT/EUR",
            "SHIB/EUR",
            "LINK/EUR",
            "LUNA/EUR",
            "LTC/EUR",
            "XLM/EUR",
            "YFI/EUR",
            "CHZ/EUR",
            "ETC/EUR",
            "BCH/EUR",
            "THETA/EUR",
            "EOS/EUR",
            "TRX/EUR",
            "BTT/EUR",
            "EGLD/EUR",
            "GRT/EUR",
            "ENJ/EUR",
            "SXP/EUR",
            "UNI/EUR",
            "WRX/EUR",
            "WIN/EUR",
            "AVAX/EUR",
            "HOT/EUR"

         

	
        ],
        "pair_blacklist": [
            "BNB/EUR"
        ]
    },
    "pairlists": [
        {"method": "StaticPairList"}
    ],
    "edge": {
        "enabled": false,
        "process_throttle_secs": 3600,
        "calculate_since_number_of_days": 7,
        "allowed_risk": 0.01,
        "stoploss_range_min": -0.01,
        "stoploss_range_max": -0.1,
        "stoploss_range_step": -0.01,
        "minimum_winrate": 0.60,
        "minimum_expectancy": 0.20,
        "min_trade_number": 10,
        "max_trade_duration_minute": 1440,
        "remove_pumps": false
    },
    "telegram": {
        "enabled": true,
        "token": "my_token",
        "chat_id": "my_chat_id"
    },
    "api_server": {
        "enabled": false,
        "listen_ip_address": "127.0.0.1",
        "listen_port": 8080,
        "verbosity": "error",
        "jwt_secret_key": "somethingrandom",
        "CORS_origins": [],
        "username": "freqtrader",
        "password": "SuperSecurePassword"
    },
    "bot_name": "freqtrade",
    "initial_state": "running",
    "forcebuy_enable": false,
    "internals": {
        "process_throttle_secs": 5
    }
}
```

I tried to copy and paste the commands that I found in the "Advanced Strategy" section on the site but It doesn't work. 
The command that I used is the following: 

```
 use_custom_stoploss = True

    def custom_stoploss(self, pair: str, trade: 'Trade', current_time: 'datetime',
                        current_rate: float, current_profit: float, **kwargs) -> float:

        # evaluate highest to lowest, so that highest possible stop is used
        if current_profit > 0.40:
            return stoploss_from_open(0.25, current_profit)
        elif current_profit > 0.25:
            return stoploss_from_open(0.15, current_profit)
        elif current_profit > 0.20:
            return stoploss_from_open(0.07, current_profit)

        # return maximum stoploss value, keeping current stoploss price unchanged
        return 1
```
And this is the error showing up: 

2021-05-25 23:23:32,788 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error name 'stoploss_from_open' is not defined calling <bound method BbandRsiDT.custom_stoploss of <BbandRsiDT.BbandRsiDT object at 0xad16c190>>
Traceback (most recent call last):
  File "/home/pi/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 17, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/freqtrade/user_data/strategies/BbandRsiDT.py", line 57, in custom_stoploss
    return stoploss_from_open(0.07, current_profit)
NameError: name 'stoploss_from_open' is not defined
2021-05-25 23:23:32,790 - freqtrade - ERROR - name 'stoploss_from_open' is not defined

Can you please help me?

Thank you very much in advance!

**Comment by xmatthias** [comment]
When copying things from samples - make sure to eventually also copy the imports (which are included in the [stepped stoploss](https://www.freqtrade.io/en/latest/strategy-advanced/#stepped-stoploss) sample).

Based on the error it's pretty clear that `from freqtrade.strategy import stoploss_from_open` is missing from the imports (top of the file) - and maybe some of the other imports as well (although i don't think the others are used).

**Comment by castalia3** [comment]
@xmatthias you're absolutely right I left out a part, thanks
