### ISSUE TITLE
hyperopt-list: filters for avg-time broken

### ISSUE THREAD

**Issue by bzed** [freqtrade/freqtrade#5061]
## Describe your environment

  * Operating system: Debian buster
  * Python Version: 3.7.3
  * CCXT version: doesn't matter
  * Freqtrade Version: latest develop
  
## Describe the problem:

Filterting hyperopt results for avg time doesn't work anymore, seems there is a str stored in the new json format instead of an int.

### Steps to reproduce:

run

``` freqtrade hyperopt-list  .... --max-avg-time 123```

### Relevant code exceptions or logs

  ```
  $ freqtrade hyperopt-list --hyperopt-filename /home/zebe/freqtrade/user_data/hyperopt_results/strategy_GodStraNew_2021-05-31_13-04-47.fthypt  --profit --min-avg-profit 1 --max-avg-time 123
2021-05-31 16:55:40,324 - freqtrade.loggers - INFO - Verbosity set to 0
2021-05-31 16:55:40,324 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/zebe/freqtrade/user_data ...
2021-05-31 16:55:40,324 - freqtrade.configuration.configuration - INFO - Using data directory: /home/zebe/freqtrade/user_data/data ...
2021-05-31 16:55:40,324 - freqtrade.configuration.configuration - INFO - Using hyperopt file: /home/zebe/freqtrade/user_data/hyperopt_results/strategy_GodStraNew_2021-05-31_13-04-47.fthypt
2021-05-31 16:55:40,324 - freqtrade.configuration.configuration - INFO - Parameter --profitable detected: True
2021-05-31 16:55:40,324 - freqtrade.configuration.configuration - INFO - Parameter --max-avg-time detected: 86400.0
2021-05-31 16:55:40,325 - freqtrade.configuration.configuration - INFO - Parameter --min-avg-profit detected: 1.0
2021-05-31 16:55:40,325 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2021-05-31 16:55:40,326 - freqtrade.optimize.hyperopt_tools - INFO - Reading epochs from '/home/zebe/freqtrade/user_data/hyperopt_results/strategy_GodStraNew_2021-05-31_13-04-47.fthypt'
2021-05-31 16:55:41,596 - freqtrade.optimize.hyperopt_tools - INFO - Loaded 2000 previous evaluations from disk.
2021-05-31 16:55:41,599 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/zebe/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/home/zebe/freqtrade/freqtrade/commands/hyperopt_commands.py", line 54, in start_hyperopt_list
    epochs = hyperopt_filter_epochs(epochs, filteroptions)
  File "/home/zebe/freqtrade/freqtrade/commands/hyperopt_commands.py", line 152, in hyperopt_filter_epochs
    epochs = _hyperopt_filter_epochs_duration(epochs, filteroptions)
  File "/home/zebe/freqtrade/freqtrade/commands/hyperopt_commands.py", line 212, in _hyperopt_filter_epochs_duration
    x for x in epochs
  File "/home/zebe/freqtrade/freqtrade/commands/hyperopt_commands.py", line 213, in <listcomp>
    if get_duration_value(x) < filteroptions['filter_max_avg_time']
  File "/home/zebe/freqtrade/freqtrade/commands/hyperopt_commands.py", line 201, in get_duration_value
    return avg.total_seconds() // 60
AttributeError: 'str' object has no attribute 'total_seconds'
(.env) zebe@dc6concollect001:~/freqtrade$ 

  ```

**Comment by xmatthias** [comment]
It's fixed in the latest develop.
unfortunately, it'll only work on newly done hyperopts (with the version that fixes it) - as the value was a string, not a integer.
