### ISSUE TITLE
I can't get orders from orderbook

### ISSUE THREAD

**Issue by glpozza** [freqtrade/freqtrade#5073]
* Operating system: Linux
  * Python Version: 3.8.6
  * CCXT version: 1.49.30
  * Freqtrade Version: develop-32577cc0
  
when using:
```
if self.dp:
    if self.dp.runmode.value in ('live', 'dry_run'):
        ob = self.dp.orderbook(metadata['pair'], 1)
        dataframe['best_bid'] = ob['bids'][0][0]
        dataframe['best_ask'] = ob['asks'][0][0]
```
inside populate_indicators, the strategy loads without errors but, while running, I keep getting a warning of:

KeyError: 'best_bid'
WARNING - Unable to analyze candle (OHLCV) data for pair XXX/XXX: 'best_bid'
WARNING - Empty candle (OHLCV) data for pair XXX/XXX

*XXX/XXX is every pair in my whitelist

What am I doing wrong?

**Comment by xmatthias** [comment]
which mode? (dry, live, backtesting, ...) ?

**Comment by glpozza** [comment]
Dry-run
and, if it helps, I'm using binance.

**Comment by xmatthias** [comment]
does backtesting work?

The message indicates that there is an empty dataframe returned ... so maybe you forgot / deleted the `return dataframe` statement from one of the methods?

**Comment by glpozza** [comment]
I'm using "dataframe['best_ask']" as part of buy signal, but if I replace it with anything else, backtesting does work. 
The complete error I get is:

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 17, in wrapper
    return f(*args, **kwargs)
  File "/home/user/freqtrade/freqtrade/strategy/interface.py", line 421, in _analyze_ticker_internal
    dataframe = self.analyze_ticker(dataframe, metadata)
  File "/home/user/freqtrade/freqtrade/strategy/interface.py", line 401, in analyze_ticker
    dataframe = self.advise_buy(dataframe, metadata)
  File "/home/user/freqtrade/freqtrade/strategy/interface.py", line 764, in advise_buy
    return self.populate_buy_trend(dataframe, metadata)
  File "/home/user/freqtrade/user_data/strategies/hades.py", line 63, in populate_buy_trend
    print(dataframe['best_bid'])
  File "/home/user/freqtrade/.env/lib/python3.8/site-packages/pandas/core/frame.py", line 3024, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/user/freqtrade/.env/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: 'best_bid'
2021-06-03 16:34:03,841 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair XRP/USDT: 'best_bid'
2021-06-03 16:34:03,853 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error 'best_bid' calling <bound method IStrategy._analyze_ticker_internal of <hades.hades object at 0x7f718fa25400>>
Traceback (most recent call last):
  File "/home/user/freqtrade/.env/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'best_bid'

...and then the warning I wrote before.

Yes, it was a print(), but as an attempt to find a solution.

**Comment by xmatthias** [comment]
well "something" is preventing the column to be added.

the code itself seems fine ... so maybe it's placed in the wrong location ...

**Comment by glpozza** [comment]
In the last try I simply uncommented the orderbook block from a new strategy (created using new-strategy), so it is inside populate_indicators. Is there something I should import or some dependence I'm missing? Is there a strategy example using orderbook?

**Comment by xmatthias** [comment]
You're right - the strategy samples still had the wrong approach (not using `.value`) - however the documentation sample was correct and is working for me - and adding `.value` to the sample strategy will also fix that.

**Comment by glpozza** [comment]
Yes, it is working fine now. Thank you.
