### ISSUE TITLE
TypeError: can't multiply sequence by non-int of type 'float'

### ISSUE THREAD

**Issue by IAmTheSuperman** [freqtrade/freqtrade#5097]
## Describe your environment

  * Operating system: Ubuntu
  * Python Version: 3.8 (`python -V`)
  * CCXT version: _1.50.70____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: __freqtrade develop-2878cca5__ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
This happened when I was running my backtest. Just wondering if I did something wrong somewhere

2021-06-00 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/ubuntu/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/home/ubuntu/freqtrade/freqtrade/commands/optimize_commands.py", line 53, in start_backtesting
    backtesting.start()
  File "/home/ubuntu/freqtrade/freqtrade/optimize/backtesting.py", line 517, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
  File "/home/ubuntu/freqtrade/freqtrade/optimize/backtesting.py", line 489, in backtest_one_strategy
    results = self.backtest(
  File "/home/ubuntu/freqtrade/freqtrade/optimize/backtesting.py", line 417, in backtest
    trade = self._enter_trade(pair, row)
  File "/home/ubuntu/freqtrade/freqtrade/optimize/backtesting.py", line 293, in _enter_trade
    min_stake_amount = self.exchange.get_min_pair_stake_amount(pair, row[OPEN_IDX], -0.05)
  File "/home/ubuntu/freqtrade/freqtrade/exchange/exchange.py", line 539, in get_min_pair_stake_amount
    min_stake_amounts.append(limits['amount']['min'] * price)
TypeError: can't multiply sequence by non-int of type 'float'

**Comment by xmatthias** [comment]
I see 2 possibilities to get to this - either you're using a  non-supported exchange which has strings in their limit return values (which it shouldn't have) - or your strategy is modifying one of the OHLC columns  (most likely the Open column).

**Comment by IAmTheSuperman** [comment]
dataframe.loc[
            (
                (qtpylib.crossed_above(dataframe['ema5'], dataframe['ema10'])) &  # Signal: EMA5 above EMA10
                (dataframe['volume'] > 0)  # Make sure Volume is not 0
            ),
            'buy'] = 1

my strategy is as simple as this, and I don't see any strings in the downloaded dataset. So you see anything else?

**Comment by IAmTheSuperman** [comment]
little update, I use the free strategy for testing. Strategy002 works as intended, meanwhile Strategy001 (which looks a bit like what I have here) shows the same error.

**Comment by xmatthias** [comment]
as mentioned above - it might also be because of the exchange you're using. The market data is fetched from the exchange ... so it's possible to only "hit" for certain pairs - but not for others - so if Strategy002 doesn't buy the "problematic" pair, but Strategy001 does, it can still affect it.

**Comment by xmatthias** [comment]
I'll assume this as answered by the above.

Feel free to comment below / reopen if that's not the case.

**Comment by IAmTheSuperman** [comment]
Sorry somehow missed it...
---
The issue still persists....
I have limited to pair to one: ETH/USDT, and strategy002 (from here https://github.com/freqtrade/freqtrade-strategies) still works, but strategy001 still it is showing the same message.

**Comment by xmatthias** [comment]
If your logs don't show any problem initializing the exchange, you might want to delete the data for that pair/timeframe and redownload it - assuming it might be corrupted somehow.

**Comment by IAmTheSuperman** [comment]
2021-06-24 16:15:05,934 - freqtrade.freqtradebot - INFO - Buy signal found: about create a new trade for THETA/USDT with stake_amount: 0.1 ...
2021-06-24 16:15:05,934 - freqtrade.exchange.exchange - INFO - Using Last Bid / Last Price
2021-06-24 16:15:06,183 - freqtrade.commands.trade_commands - ERROR - '>' not supported between instances of 'NoneType' and 'float'
2021-06-24 16:15:06,184 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/pi/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker.run()
  File "/home/pi/freqtrade/freqtrade/worker.py", line 74, in run
    state = self._worker(old_state=state)
  File "/home/pi/freqtrade/freqtrade/worker.py", line 111, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
  File "/home/pi/freqtrade/freqtrade/worker.py", line 132, in _throttle
    result = func(*args, **kwargs)
  File "/home/pi/freqtrade/freqtrade/worker.py", line 145, in _process_running
    self.freqtrade.process()
  File "/home/pi/freqtrade/freqtrade/freqtradebot.py", line 183, in process
    self.enter_positions()
  File "/home/pi/freqtrade/freqtrade/freqtradebot.py", line 383, in enter_positions
    trades_created += self.create_trade(pair)
  File "/home/pi/freqtrade/freqtrade/freqtradebot.py", line 442, in create_trade
    return self.execute_buy(pair, stake_amount)
  File "/home/pi/freqtrade/freqtrade/freqtradebot.py", line 483, in execute_buy
    buy_limit_requested = self.exchange.get_buy_rate(pair, True)
  File "/home/pi/freqtrade/freqtrade/exchange/exchange.py", line 977, in get_buy_rate
    if ticker['last'] and ticker_rate > ticker['last']:
TypeError: '>' not supported between instances of 'NoneType' and 'float'


I am seeing this from an actual trade (I gave up on backtesting). Judging from these logs, and logs from backtesting, would this give you a better clue of what is going on?

**Comment by xmatthias** [comment]
based on the provided information - no.
We don't know which exchange you're using (which is an important point in this topic).

From the combination of these errors (and based on the fact that you seem to be the only one experiencing them) - i suspect it's either related to the exchange (not one of the officially supported/tested ones) - or related to your local circumstances (connection to the exchange is fluky - resulting in some wrong / corrupted responses from the exchange.
