### ISSUE TITLE
Canceling a traded stop loss order raises an exception

### ISSUE THREAD

**Issue by adrianceding** [freqtrade/freqtrade#5101]
## Describe your environment

  * Operating system: Ubuntu20
  * Python Version: Python 3.8.6
  * CCXT version: 1.50.48
  * Freqtrade Version: 2021.5
  
## Describe the problem:

Exchange: binance

When canceling an order.the order deal done.ccxt raise OrderNotFound.This resulted in an empty closing reason for the order

### Steps to reproduce:

  1. Open trailing_stop && trailing_only_offset_is_reached && stoploss_on_exchange
  2. The exchange's stop loss order is traded
  3. Freqtrade send order cancellation request
  4. Exchange return {"code":-2011,"msg":"Unknown order sent."}.CCXT raise ccxt.base.errors.OrderNotFound
  5. Freqtrade raise freqtrade.exceptions.InvalidOrderException
  6. The order is closed and the reason for closing is empty
  
### Observed Results:

Close Reason should is `stoploss_on_exchange`

### Relevant code exceptions or logs

  ```
 2021-06-08 18:50:03,238 - freqtrade.freqtradebot - INFO - Buy signal found: about create a new trade for TFUEL/USDT with stake_amount: 2881.2122337537 ...
2021-06-08 18:50:03,238 - freqtrade.freqtradebot - INFO - Using Last Ask / Last Price
2021-06-08 18:50:03,411 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=None, pair=TFUEL/USDT, amount=5023.20000000, open_rate=0.57360198, open_since=2021-06-08 10:50:03)
2021-06-08 18:50:03,411 - freqtrade.freqtradebot - INFO - Fee for Trade Trade(id=None, pair=TFUEL/USDT, amount=5023.20000000, open_rate=0.57360198, open_since=2021-06-08 10:50:03) [buy]: 5.0232 TFUEL - rate: 0.001
2021-06-08 18:50:03,518 - freqtrade.wallets - INFO - Wallets synced.
2021-06-08 18:50:03,519 - freqtrade.freqtradebot - INFO - Applying fee on amount for Trade(id=None, pair=TFUEL/USDT, amount=5023.20000000, open_rate=0.57360198, open_since=2021-06-08 10:50:03) (from 5023.2 to 5018.1).
2021-06-08 18:50:03,519 - freqtrade.persistence.models - INFO - Updating trade (id=None) ...
2021-06-08 18:50:03,519 - freqtrade.persistence.models - INFO - MARKET_BUY has been fulfilled for Trade(id=None, pair=TFUEL/USDT, amount=5018.10000000, open_rate=0.57360198, open_since=2021-06-08 10:50:03).
2021-06-08 18:50:03,519 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'trade_id': None, 'type': buy_fill, 'exchange': 'Binance', 'pair': 'TFUEL/USDT', 'open_rate': 0.5736019820035038, 'stake_amount': 2881.317476, 'stake_currency': 'USDT', 'fiat_currency': 'CNY', 'amount': 5018.1, 'open_date': datetime.datetime(2021, 6, 8, 10, 50, 3, 410921)}
2021-06-08 18:50:04,526 - freqtrade.wallets - INFO - Wallets synced.
2021-06-08 18:50:04,530 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'trade_id': 13, 'type': buy, 'exchange': 'Binance', 'pair': 'TFUEL/USDT', 'limit': 0.5736019820035038, 'order_type': 'market', 'stake_amount': 2881.317476, 'stake_currency': 'USDT', 'fiat_currency': 'CNY', 'amount': 5018.1, 'open_date': datetime.datetime(2021, 6, 8, 10, 50, 3, 410921), 'current_rate': 0.57358}
2021-06-08 18:50:06,854 - freqtrade.exchange.binance - INFO - stoploss limit order added for TFUEL/USDT. stop price: 0.17209. limit: 0.17036
2021-06-08 18:50:07,055 - freqtrade.exchange.common - WARNING - fetch_order() returned exception: "Order not found (pair: TFUEL/USDT id: 278614487). Message: binance {"code":-2013,"msg":"Order does not exist."}"
2021-06-08 18:50:07,056 - freqtrade.exchange.common - WARNING - retrying fetch_order() still for 5 times
2021-06-08 18:50:07,056 - freqtrade.exchange.common - INFO - Applying DDosProtection backoff delay: 1
2021-06-08 18:50:08,272 - freqtrade.exchange.common - WARNING - fetch_order() returned exception: "Order not found (pair: TFUEL/USDT id: 278614487). Message: binance {"code":-2013,"msg":"Order does not exist."}"
2021-06-08 18:50:08,272 - freqtrade.exchange.common - WARNING - retrying fetch_order() still for 5 times
2021-06-08 18:50:08,272 - freqtrade.exchange.common - INFO - Applying DDosProtection backoff delay: 1
2021-06-08 18:50:09,485 - freqtrade.exchange.common - WARNING - fetch_order() returned exception: "Order not found (pair: TFUEL/USDT id: 278614487). Message: binance {"code":-2013,"msg":"Order does not exist."}"
2021-06-08 18:50:09,485 - freqtrade.exchange.common - WARNING - retrying fetch_order() still for 5 times
2021-06-08 18:50:09,486 - freqtrade.exchange.common - INFO - Applying DDosProtection backoff delay: 1
2021-06-08 18:50:12,204 - freqtrade.worker - INFO - Bot heartbeat. PID=2368913, version='2021.5', state='RUNNING'
2021-06-08 18:51:12,307 - freqtrade.worker - INFO - Bot heartbeat. PID=2368913, version='2021.5', state='RUNNING'
2021-06-08 18:51:36,059 - freqtrade.freqtradebot - INFO - Cancelling current stoploss on exchange for pair TFUEL/USDT (orderid:278614487) in order to add another one ...
2021-06-08 18:51:36,255 - freqtrade.exchange.binance - INFO - stoploss limit order added for TFUEL/USDT. stop price: 0.57605. limit: 0.57029
2021-06-08 18:51:36,464 - freqtrade.exchange.common - WARNING - fetch_order() returned exception: "Order not found (pair: TFUEL/USDT id: 278619824). Message: binance {"code":-2013,"msg":"Order does not exist."}"
2021-06-08 18:51:36,464 - freqtrade.exchange.common - WARNING - retrying fetch_order() still for 5 times
2021-06-08 18:51:36,464 - freqtrade.exchange.common - INFO - Applying DDosProtection backoff delay: 1
2021-06-08 18:51:37,480 - freqtrade.exchange.common - WARNING - fetch_order() returned exception: "Order not found (pair: TFUEL/USDT id: 278619824). Message: binance {"code":-2013,"msg":"Order does not exist."}"
2021-06-08 18:51:37,480 - freqtrade.exchange.common - WARNING - retrying fetch_order() still for 4 times
2021-06-08 18:51:37,480 - freqtrade.exchange.common - INFO - Applying DDosProtection backoff delay: 2
2021-06-08 18:51:39,501 - freqtrade.freqtradebot - INFO - Cancelling current stoploss on exchange for pair TFUEL/USDT (orderid:278619824) in order to add another one ...
2021-06-08 18:51:39,693 - freqtrade.exchange.binance - INFO - stoploss limit order added for TFUEL/USDT. stop price: 0.57626. limit: 0.5705
2021-06-08 18:51:39,901 - freqtrade.freqtradebot - INFO - Cancelling current stoploss on exchange for pair TFUEL/USDT (orderid:278620119) in order to add another one ...
2021-06-08 18:51:40,098 - freqtrade.exchange.binance - INFO - stoploss limit order added for TFUEL/USDT. stop price: 0.57631. limit: 0.57055
2021-06-08 18:51:40,300 - freqtrade.freqtradebot - INFO - Cancelling current stoploss on exchange for pair TFUEL/USDT (orderid:278620145) in order to add another one ...
2021-06-08 18:51:40,398 - freqtrade.freqtradebot - ERROR - Could not cancel stoploss order 278620145 for pair TFUEL/USDT
Traceback (most recent call last):
  File "/root/binance/freqtrade/.env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 593, in fetch
    response.raise_for_status()
  File "/root/binance/freqtrade/.env/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order?timestamp=1623149500385&recvWindow=5000&symbol=TFUELUSDT&orderId=278620145&signature=3bf8e35eef0f3a9255578344537c04e301a32bef788ae74c82d52256d8bc90ed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/binance/freqtrade/freqtrade/exchange/exchange.py", line 1077, in cancel_order
    return self._api.cancel_order(order_id, pair)
  File "/root/binance/freqtrade/.env/lib/python3.8/site-packages/ccxt/binance.py", line 2137, in cancel_order
    response = getattr(self, method)(self.extend(request, query))
  File "/root/binance/freqtrade/.env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 461, in inner
    return entry(_self, **inner_kwargs)
  File "/root/binance/freqtrade/.env/lib/python3.8/site-packages/ccxt/binance.py", line 2961, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/root/binance/freqtrade/.env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 482, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/root/binance/freqtrade/.env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 609, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/root/binance/freqtrade/.env/lib/python3.8/site-packages/ccxt/binance.py", line 2955, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions, error, feedback)
  File "/root/binance/freqtrade/.env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 500, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.OrderNotFound: binance {"code":-2011,"msg":"Unknown order sent."}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/binance/freqtrade/freqtrade/freqtradebot.py", line 943, in handle_trailing_stoploss_on_exchange
    co = self.exchange.cancel_stoploss_order_with_result(order['id'], trade.pair,
  File "/root/binance/freqtrade/freqtrade/exchange/exchange.py", line 1133, in cancel_stoploss_order_with_result
    corder = self.cancel_stoploss_order(order_id, pair)
  File "/root/binance/freqtrade/freqtrade/exchange/common.py", line 89, in wrapper
    return f(*args, **kwargs)
  File "/root/binance/freqtrade/freqtrade/exchange/exchange.py", line 1079, in cancel_order
    raise InvalidOrderException(
freqtrade.exceptions.InvalidOrderException: Could not cancel order. Message: binance {"code":-2011,"msg":"Unknown order sent."}
2021-06-08 18:51:40,495 - freqtrade.freqtradebot - ERROR - Unable to place a stoploss order on exchange. Could not create stop_loss_limit sell order on market TFUEL/USDT. Tried to sell amount 5018.1 at rate 0.57079. Message: binance Stop price would trigger immediately.
2021-06-08 18:51:40,495 - freqtrade.freqtradebot - WARNING - Selling the trade forcefully
2021-06-08 18:51:40,606 - freqtrade.wallets - INFO - Wallets synced.
2021-06-08 18:51:40,606 - freqtrade.freqtradebot - WARNING - Unable to sell trade TFUEL/USDT: Not enough amount to sell. Trade-amount: 5018.1, Wallet: 0.2491
2021-06-08 18:51:40,699 - freqtrade.freqtradebot - WARNING - Unable to place stoploss order Insufficient funds to create stop_loss_limit sell order on market TFUEL/USDT. Tried to sell amount 5018.1 at rate 0.17036. Message: binance Account has insufficient balance for requested action..
2021-06-08 18:51:40,701 - freqtrade.freqtradebot - INFO - Trying to refind lost order for Trade(id=13, pair=TFUEL/USDT, amount=5018.10000000, open_rate=0.57360198, open_since=2021-06-08 10:50:03)
2021-06-08 18:51:40,701 - freqtrade.freqtradebot - INFO - Trying to refind Order(id=118, order_id=278614066, trade_id=13, side=buy, order_type=market, status=closed)
2021-06-08 18:51:40,701 - freqtrade.freqtradebot - INFO - Trying to refind Order(id=119, order_id=278614487, trade_id=13, side=sell, order_type=stop_loss_limit, status=canceled)
2021-06-08 18:51:40,701 - freqtrade.freqtradebot - INFO - Trying to refind Order(id=120, order_id=278619824, trade_id=13, side=sell, order_type=stop_loss_limit, status=canceled)
2021-06-08 18:51:40,701 - freqtrade.freqtradebot - INFO - Trying to refind Order(id=121, order_id=278620119, trade_id=13, side=sell, order_type=stop_loss_limit, status=canceled)
2021-06-08 18:51:40,701 - freqtrade.freqtradebot - INFO - Trying to refind Order(id=122, order_id=278620145, trade_id=13, side=sell, order_type=stop_loss_limit, status=open)
2021-06-08 18:51:40,800 - freqtrade.exchange.common - WARNING - fetch_order() returned exception: "Order not found (pair: TFUEL/USDT id: 278620145). Message: binance {"code":-2013,"msg":"Order does not exist."}"
2021-06-08 18:51:40,800 - freqtrade.exchange.common - WARNING - retrying fetch_order() still for 5 times
2021-06-08 18:51:40,800 - freqtrade.exchange.common - INFO - Applying DDosProtection backoff delay: 1
2021-06-08 18:51:41,815 - freqtrade.freqtradebot - INFO - Found Order(id=122, order_id=278620145, trade_id=13, side=sell, order_type=stop_loss_limit, status=open) for trade Trade(id=13, pair=TFUEL/USDT, amount=5018.10000000, open_rate=0.57360198, open_since=2021-06-08 10:50:03).jj
2021-06-08 18:51:41,815 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=13, pair=TFUEL/USDT, amount=5018.10000000, open_rate=0.57360198, open_since=2021-06-08 10:50:03)
2021-06-08 18:51:41,920 - freqtrade.persistence.models - INFO - Updating trade (id=13) ...
2021-06-08 18:51:41,920 - freqtrade.persistence.models - INFO - STOP_LOSS_LIMIT is hit for Trade(id=13, pair=TFUEL/USDT, amount=5018.10000000, open_rate=0.57360198, open_since=2021-06-08 10:50:03).
2021-06-08 18:51:41,920 - freqtrade.persistence.models - INFO - Marking Trade(id=13, pair=TFUEL/USDT, amount=5018.10000000, open_rate=0.57360198, open_since=closed) as closed as the trade is fulfilled and found no open orders for it.
2021-06-08 18:51:42,020 - freqtrade.wallets - INFO - Wallets synced.
  ```

**Comment by xmatthias** [comment]
To be honest, your log is quite telling (nice job picking the right range).

It does however kindof show that everything worked according to plan ... 
Binance (sometimes) has a tendency to not report orders back right away in their fetch_order endpoint (the "OrderNotFound" error can also happen right after placing an order).
They claim it's a "feature" of their environment - i'd call it a bug - but i've given up arguing with them and instead build workarounds.

For example, the "refinding order" logic that applied in your case - which goes through the list of orders it placed and tries to "refind" the one that filled.

Now if i get you right - the problem is now in the database - as sell_reason has not been set? or is there something else you think that's wrong?

**Comment by adrianceding** [comment]
is，the problem is sell reason is not save to db. This may cause doubt. I think the current treatment is the most correct. The bot is really robust,👍🏻
![F7B9D7BF-8B96-44A3-836D-6A357F8EA520](https://user-images.githubusercontent.com/4156079/121235219-32b98c00-c8c7-11eb-899d-d6c7aebb01f1.jpeg)

**Comment by xmatthias** [comment]
yeah ... well ... if that's the only problem then i'm pretty much content - and this should be "fixable" too :laughing: :+1:
