### ISSUE TITLE
Additional data (Trades) Error

### ISSUE THREAD

**Issue by quantsirius** [freqtrade/freqtrade#5115]
## Describe your environment

  * Operating system: Ubuntu 20.04
  * Python Version: Python 3.8.5
  * CCXT version: ccxt==1.50.48
  * Freqtrade Version: freqtrade 2021.5
  
## Describe the problem:

Hi. I tried to implement the function from docs: Additional data (Trades). Received an error only after copy paste the code below.
New strategy was created. Copied to populate_indicators.

At the top of the file, import Trade.
from freqtrade.persistence import Trade

The following example queries for the current pair and trades from today, however other filters can easily be added.

        if self.config['runmode'].value in ('live', 'dry_run'):
            trades = Trade.get_trades([Trade.pair == metadata['pair'],
                               Trade.open_date > datetime.utcnow() - timedelta(days=1),
                               Trade.is_open.is_(False),
                ]).order_by(Trade.close_date).all()
        # Summarize profit for this pair.
        curdayprofit = sum(trade.close_profit for trade in trades)
### Relevant code exceptions or logs

  ```
  2021-06-10 13:06:09,875 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/user/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/home/user/freqtrade/freqtrade/commands/optimize_commands.py", line 53, in start_backtesting
    backtesting.start()
  File "/home/user/freqtrade/freqtrade/optimize/backtesting.py", line 517, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
  File "/home/user/freqtrade/freqtrade/optimize/backtesting.py", line 475, in backtest_one_strategy
    preprocessed = self.strategy.ohlcvdata_to_dataframe(data)
  File "/home/user/freqtrade/freqtrade/strategy/interface.py", line 730, in ohlcvdata_to_dataframe
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair})
  File "/home/user/freqtrade/freqtrade/strategy/interface.py", line 730, in <dictcomp>
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair})
  File "/home/user/freqtrade/freqtrade/strategy/interface.py", line 747, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/home/user/freqtrade/user_data/strategies/daystest.py", line 136, in populate_indicators
    curdayprofit = sum(trade.close_profit for trade in trades)
UnboundLocalError: local variable 'trades' referenced before assignment
  ```

**Comment by xmatthias** [comment]
Your indentation of `curdayprofit` (the whole line) is wrong. That part should be within the if block (as it is in the documentation).

Obviously, this data is only available during live runs (which is documented in the Warning box at the bottom of that documentation section) - so you'll need to have some "sane fallback" for backtesting - where trades-data is not available during buy-signal generation.

**Comment by quantsirius** [comment]
Of course, did not notice. Thank you for help.
