### ISSUE TITLE
docker-compose does‘t work with proxy

### ISSUE THREAD

**Issue by harryleee** [freqtrade/freqtrade#5118]
## environment

  * Operating system: wsl2 + docker20.1
  * Python Version: 3.9 （from docker logs）
  * CCXT version: CCXT 1.50.48 （from docker logs）
  * Freqtrade Version: docker-compose pull is latest version (11/06)
  
## question

I want to use a proxy to access binance api, but there is an exception from urllib3 package.

docker-compose.yml:
```
services
  freqtrade:
    env_file:
      - .env
```

.env:
```
all_proxy="https://192.168.121.1:1080"
```

config.json:
```
{
    "exchange": {
        "name": "binance",
        "ccxt_async_config": {
            "aiohttp_trust_env": true
        }
}
```

exception:
```
freqtrade    | 2021-06-11 07:54:07,507 - freqtrade.commands.trade_commands - ERROR - check_hostname requires server_hostname
freqtrade    | 2021-06-11 07:54:07,507 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
freqtrade    | Traceback (most recent call last):
freqtrade    |   File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
freqtrade    |     worker = Worker(args)
freqtrade    |   File "/freqtrade/freqtrade/worker.py", line 35, in __init__
freqtrade    |     self._init(False)
freqtrade    |   File "/freqtrade/freqtrade/worker.py", line 52, in _init
freqtrade    |     self.freqtrade = FreqtradeBot(self._config)
freqtrade    |   File "/freqtrade/freqtrade/freqtradebot.py", line 71, in __init__
freqtrade    |     self.exchange = ExchangeResolver.load_exchange(self.config['exchange']['name'], self.config)
freqtrade    |   File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 31, in load_exchange
freqtrade    |     exchange = ExchangeResolver._load_exchange(exchange_name,
freqtrade    |   File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 53, in _load_exchange
freqtrade    |     exchange = ex_class(**kwargs)
freqtrade    |   File "/freqtrade/freqtrade/exchange/exchange.py", line 138, in __init__
freqtrade    |     self._load_markets()
freqtrade    |   File "/freqtrade/freqtrade/exchange/exchange.py", line 318, in _load_markets
freqtrade    |     self._markets = self._api.load_markets()
freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 1365, in load_markets
freqtrade    |     markets = self.fetch_markets(params)
freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/binance.py", line 834, in fetch_markets
freqtrade    |     response = getattr(self, method)(query)
freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 461, in inner
freqtrade    |     return entry(_self, **inner_kwargs)
freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/binance.py", line 2961, in request
freqtrade    |     response = self.fetch2(path, api, method, params, headers, body)
freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 482, in fetch2
freqtrade    |     return self.fetch(request['url'], request['method'], request['headers'], request['body'])
freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 567, in fetch
freqtrade    |     response = self.session.request(
freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
freqtrade    |     resp = self.send(prep, **send_kwargs)
freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
freqtrade    |     r = adapter.send(request, **kwargs)
freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
freqtrade    |     resp = conn.urlopen(
freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 696, in urlopen
freqtrade    |     self._prepare_proxy(conn)
freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 964, in _prepare_proxy
freqtrade    |     conn.connect()
freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/connection.py", line 359, in connect
freqtrade    |     conn = self._connect_tls_proxy(hostname, conn)
freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/connection.py", line 500, in _connect_tls_proxy
freqtrade    |     return ssl_wrap_socket(
freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 432, in ssl_wrap_socket
freqtrade    |     ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 474, in _ssl_wrap_socket_impl
freqtrade    |     return ssl_context.wrap_socket(sock)
freqtrade    |   File "/usr/local/lib/python3.9/ssl.py", line 500, in wrap_socket
freqtrade    |     return self.sslsocket_class._create(
freqtrade    |   File "/usr/local/lib/python3.9/ssl.py", line 997, in _create
freqtrade    |     raise ValueError("check_hostname requires server_hostname")
freqtrade    | ValueError: check_hostname requires server_hostname
```

**Comment by xmatthias** [comment]
I'm unsure if urllib supports all_proxy, or if you'll need to seperate the two out into http_proxy and https_proxy.

that said, quickly searching for the exception (last line) shows that it might be a bug with urllib (which supposedly was fixed in march).
while this seems to be fixed in the last (2) versions of urllib3 - maybe it wasn't properly fixed for all cases - it's just a suspicion though.
