### ISSUE TITLE
Docker Compose can't Trade, problem at qtpylib

### ISSUE THREAD

**Issue by Chyang777** [freqtrade/freqtrade#5156]
## Describe your environment

  * Operating system: Ubuntu
  * Python Version: 3.8
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*I can not run freqtrade, please help*

2021-06-19 14:21:27,095 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair GRT/USDT: name 'qtpylib' is not defined
2021-06-19 14:21:27,131 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error name 'qtpylib' is not defined calling <bound method IStrategy._analyze_ticker_internal of <MultiRSI.MultiRSI object at 0x7f8ff05fbd30>>
Traceback (most recent call last):
  File "/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 17, in wrapper
    return f(*args, **kwargs)
  File "/freqtrade/freqtrade/strategy/interface.py", line 421, in _analyze_ticker_internal
    dataframe = self.analyze_ticker(dataframe, metadata)
  File "/freqtrade/freqtrade/strategy/interface.py", line 402, in analyze_ticker
    dataframe = self.advise_sell(dataframe, metadata)
  File "/freqtrade/freqtrade/strategy/interface.py", line 780, in advise_sell
    return self.populate_sell_trend(dataframe, metadata)
  File "/freqtrade/user_data/strategies/MultiRSI.py", line 66, in populate_sell_trend
    (qtpylib.crossed_above(dataframe['rsi'], 70)) &  # Signal: RSI crosses above 70
NameError: name 'qtpylib' is not defined

**Comment by xmatthias** [comment]
It's quite simple - you're missing the required import. It's there in the sample strategy - but might not be available in all provided strategies if it wasn't used and you added a condition.

best add `import freqtrade.vendor.qtpylib.indicators as qtpylib` to the top of the file.

As a hint - use an editor with python support (like vscode) - it'll usually highlight the problem (including what you could do to fix it).

**Comment by Chyang777** [comment]
Thank you very much xmatthias
