### ISSUE TITLE
What is the correct way to persist a bot, and to clean up open trades and Telegram connections when it breaks?

### ISSUE THREAD

**Issue by bigsee** [freqtrade/freqtrade#5227]
## Describe your environment

  * Operating system: Ubuntu 20.4
  * Python Version: Python 3.8.5
  * CCXT version: Using Docker - how do I find this?
  * Freqtrade Version: freqtrade 2021.5

## Context:

First of all, thank you for all of your work, time and energy on a fantastic tool!

After running a dry run for some time, I decided that the bot is ready to switch to live, which I did a couple of days ago. I stopped the dry run of the bot using Telegram and `/forcesell` all my open dry run positions. I then switched to `"dry_run": false` in my config. 

I am using Docker. I started the bot using `docker-compose up -d` as I did with the dry run and as advised to another user [here](https://github.com/freqtrade/freqtrade/issues/4916). Everything looked like it was working fine.

My pipe to the VPS was broken at some point during the evening without my knowledge, but I don't think that should have affected it. When I awoke the next morning, I noticed that the bot had stopped trading late in the evening, meaning that I had open positions, many of which should have been sold according to my strategy.

After reconnecting to the VPS, I ran `docker-compose ps` and noticed that freqtrade was still running. However, Telegram was unresponsive (even after waiting for some time - note that my last request to check the balance the previous evening also got no response, which should have been a red flag):

![Screen Shot 2021-07-03 at 09 03 02](https://user-images.githubusercontent.com/11768967/124346160-904aab00-dbdd-11eb-8f9b-40c1f8c060a0.png)

I was able to get the bot responding again by running `docker-compose down` and then `docker-compose up -d` once more. Note that immediately after restarting, I now apparently only have one open trade:

![Screen Shot 2021-07-03 at 09 07 31](https://user-images.githubusercontent.com/11768967/124346309-562dd900-dbde-11eb-98ff-e8f240da50cf.png)

...even though running `/balance` then correctly showed all the open positions. (I won't show the output of balance here). While running `/balance` two more trades were opened, which was confirmed by running `/status`:

![Screen Shot 2021-07-03 at 09 07 40](https://user-images.githubusercontent.com/11768967/124346396-deac7980-dbde-11eb-9afa-fc955aed24a1.png)

Running `/performance` and `/daily` gave no result: 

![Screen Shot 2021-07-03 at 09 07 48](https://user-images.githubusercontent.com/11768967/124347196-9ba0d500-dbe3-11eb-8551-f659cd9d4ea0.png)

...even though as you can see from the first screenshot the bot had been successfully running and closing trades for a day. I assume that this was because I stopped Docker after the bot stopped trading.

I realised that this would create more of a mess. So I used the command `/stop` and got the warning message:

![Screen Shot 2021-07-03 at 09 18 33](https://user-images.githubusercontent.com/11768967/124346580-f46e6e80-dbdf-11eb-83b0-51aeab5dd125.png)

After following the instructions in that warning message to handle trades gracefully, you can see that the bot seems to ignore the `/stopbuy` instruction and I noticed later that it had continued to open buy orders 🙈 :

![Screen Shot 2021-07-03 at 09 07 57](https://user-images.githubusercontent.com/11768967/124347249-e9b5d880-dbe3-11eb-98fd-651c81457abf.png)

The whole thing is now a mess and I am now stuck trying to manually deal with all of these positions and losses in Binance. I have force stopped the bot on the VPS and now switched the config to `"dry_run": true` and restarted to be sure no more orders will be opened.

## Clues

One obvious dubious thing on my side is that I noticed I had the db_url hard-coded in my config to the dry run one `tradesv3.dryrun.sqlite`. After reading docs, I have now removed that so that the defaults are used based on the mode. 

Another is that, after restarting the live bot via `docker-compose down docker-compose up -d`, I noticed later from checking the logs that there were some errors about Telegram: 

```
2021-07-02 07:16:18,242 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2021-07-02 07:16:18,243 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/ext/updater.py", line 520, in _network_loop_retry
    if not action_cb():
  File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/ext/updater.py", line 471, in polling_action_cb
    updates = self.bot.get_updates(
  File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/bot.py", line 127, in decorator
    result = func(*args, **kwargs)
  File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/bot.py", line 2761, in get_updates
    result = self._post(
  File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/bot.py", line 259, in _post
    return self.request.post(
  File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/utils/request.py", line 350, in post
    result = self._request_wrapper(
  File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/utils/request.py", line 277, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2021-07-02 07:16:24,241 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2021-07-02 07:16:24,243 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/ext/updater.py", line 520, in _network_loop_retry
    if not action_cb():
  File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/ext/updater.py", line 471, in polling_action_cb
    updates = self.bot.get_updates(
  File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/bot.py", line 127, in decorator
    result = func(*args, **kwargs)
  File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/bot.py", line 2761, in get_updates
    result = self._post(
  File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/bot.py", line 259, in _post
    return self.request.post(
  File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/utils/request.py", line 350, in post
    result = self._request_wrapper(
  File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/utils/request.py", line 277, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2021-07-02 07:16:30,241 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2021-07-02 07:16:30,243 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/ext/updater.py", line 520, in _network_loop_retry
    if not action_cb():
  File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/ext/updater.py", line 471, in polling_action_cb
    updates = self.bot.get_updates(
  File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/bot.py", line 127, in decorator
    result = func(*args, **kwargs)
  File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/bot.py", line 2761, in get_updates
    result = self._post(
  File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/bot.py", line 259, in _post
    return self.request.post(
  File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/utils/request.py", line 350, in post
    result = self._request_wrapper(
  File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/utils/request.py", line 277, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2021-07-02 07:16:37,509 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2021-07-02 07:16:37,511 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/ext/updater.py", line 520, in _network_loop_retry
    if not action_cb():
  File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/ext/updater.py", line 471, in polling_action_cb
    updates = self.bot.get_updates(
  File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/bot.py", line 127, in decorator
    result = func(*args, **kwargs)
  File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/bot.py", line 2761, in get_updates
    result = self._post(
  File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/bot.py", line 259, in _post
    return self.request.post(
  File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/utils/request.py", line 350, in post
    result = self._request_wrapper(
  File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/utils/request.py", line 277, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2021-07-02 07:16:46,076 - numexpr.utils - INFO - NumExpr defaulting to 1 threads.
2021-07-02 07:16:46,651 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2021-07-02 07:16:46,652 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/ext/updater.py", line 520, in _network_loop_retry
    if not action_cb():
  File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/ext/updater.py", line 471, in polling_action_cb
    updates = self.bot.get_updates(
  File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/bot.py", line 127, in decorator
    result = func(*args, **kwargs)
  File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/bot.py", line 2761, in get_updates
    result = self._post(
  File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/bot.py", line 259, in _post
    return self.request.post(
  File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/utils/request.py", line 350, in post
    result = self._request_wrapper(
  File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/utils/request.py", line 277, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2021-07-02 07:16:48,277 - freqtrade.wallets - INFO - Wallets synced.
2021-07-02 07:16:48,283 - freqtrade.freqtradebot - INFO - Buy signal found: about create a new trade for RUNE/USDT with stake_amount: 100 ...
2021-07-02 07:16:48,285 - freqtrade.freqtradebot - INFO - Using Last Bid / Last Price
2021-07-02 07:16:49,773 - freqtrade.wallets - INFO - Wallets synced.
...
```

I did not notice at the time because the bot began to trade again, seemingly as normal as described above.

## My questions

I have read numerous closed issues for a while and also the documentation for both Freqtrade (including SQL cheat sheet, Docker and FAQs sections) and Docker.

What did I do wrong in the above process? Specifically, I am trying to find the answers to these questions:

1. How do I ensure that a bot on a VPS keeps running after I close my Terminal connection to the server to avoid all this?
2. How do I handle open trades in the safest and most robust way?
3. Where can I find open trades after the bot connection is lost in this way? They were not in `tradesv3.dryrun.sqlite`
4. How can I properly destroy all Telegram connections?
5. Do I have to create a new Telegram key when switching from dry run to live mode?

Once I understand, I would be very happy to update the documentation to make this process clearer for others, if pull requests there are possible. Apologies in advance if this info is already there and I missed it.

**Comment by xmatthias** [comment]
running `docker-compose up -d` will start the container in daemon mode - so it'll run in the background, ignoring what you do with your terminal.
In that mode - you can check your logs with `docker-compose logs <-f>` (the -f is to tail the log).

The Telegram message hints that you're having another bot running with the same telegram token. The connection resets right after it's stopped, so if you get this message, you still got another bot running "somewhere" (maybe not on this host?).
This seems to also be confirmed by your `/stopbuy` test - only one of the bots can accept commands (that's what the error is about) - but you'll get messages from all of them - so you stopped one (the first one that started) - but not all of them.

you can check your docker instance with `docker ps` for still running containers.

When switching from dry to live, you can reuse the same telegram key - however, you should make sure to use a new database - otherwise you'll have tainted results (dry results will mix with live results) - and potentially errors due to still open dry-run trades (which obviously don't exist on the exchange).

**Comment by bigsee** [comment]
Thank you for this advice.

I only have one host so I'm not sure how I got multiple running processes. I'm testing now by starting a dry run with a config set to `"initial_state": "stopped"`. Where I open `nano` I was changing my Telegram token to a brand new one. This is my process and output (with strategy and PairList stuff removed for brevity):

```
root@bigsee-freqtrade:~/ft_userdata# docker-compose ps
Name   Command   State   Ports
------------------------------
root@bigsee-freqtrade:~/ft_userdata# nano user_data/config-private.json 
root@bigsee-freqtrade:~/ft_userdata# docker-compose up -d
Creating network "ft_userdata_default" with the default driver
Creating freqtrade ... done
root@bigsee-freqtrade:~/ft_userdata# docker-compose ps
  Name                 Command               State   Ports
----------------------------------------------------------
freqtrade   freqtrade trade --logfile  ...   Up           
root@bigsee-freqtrade:~/ft_userdata# docker-compose run freqtrade trade -c user_data/config.json -c user_data/config-private.json -s MyStrategy
Creating ft_userdata_freqtrade_run ... done
2021-07-03 14:09:47,335 - freqtrade.worker - INFO - Starting worker 2021.5
2021-07-03 14:09:47,339 - freqtrade.configuration.configuration - INFO - Using config: user_data/config.json ...
2021-07-03 14:09:47,341 - freqtrade.configuration.configuration - INFO - Using config: user_data/config-private.json ...
2021-07-03 14:09:47,344 - freqtrade.loggers - INFO - Verbosity set to 0
2021-07-03 14:09:47,345 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
2021-07-03 14:09:47,345 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2021-07-03 14:09:47,346 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:///tradesv3.dryrun.sqlite"
2021-07-03 14:09:47,347 - freqtrade.configuration.configuration - INFO - Using max_open_trades: -1 ...
2021-07-03 14:09:47,406 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2021-07-03 14:09:47,408 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/binance ...
2021-07-03 14:09:47,409 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2021-07-03 14:09:47,430 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2021-07-03 14:09:47,432 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2021-07-03 14:09:47,433 - freqtrade.freqtradebot - INFO - Starting freqtrade 2021.5

...

2021-07-03 14:09:47,501 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2021-07-03 14:09:47,508 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2021-07-03 14:09:47,509 - freqtrade.exchange.exchange - INFO - Using CCXT 1.50.48
2021-07-03 14:09:47,510 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2021-07-03 14:09:47,527 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 200}
2021-07-03 14:09:47,546 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2021-07-03 14:09:48,529 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2021-07-03 14:09:48,645 - freqtrade.wallets - INFO - Wallets synced.
2021-07-03 14:09:48,666 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist VolumePairList from '/freqtrade/freqtrade/plugins/pairlist/VolumePairList.py'...
2021-07-03 14:09:48,672 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist AgeFilter from '/freqtrade/freqtrade/plugins/pairlist/AgeFilter.py'...
2021-07-03 14:09:48,685 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist RangeStabilityFilter from '/freqtrade/freqtrade/plugins/pairlist/rangestabilityfilter.py'...
2021-07-03 14:09:48,697 - freqtrade.resolvers.iresolver - INFO - Using resolved protection LowProfitPairs from '/freqtrade/freqtrade/plugins/protections/low_profit_pairs.py'...

...

2021-07-03 14:10:18,786 - AgeFilter - INFO - Removed PHA/USDT from whitelist, because age 8 is less than 10 days
2021-07-03 14:10:18,792 - AgeFilter - INFO - Validated 124 pairs.
2021-07-03 14:10:46,762 - freqtrade.rpc.rpc_manager - INFO - Enabling rpc.telegram ...
/home/ftuser/.local/lib/python3.9/site-packages/telegram/ext/dispatcher.py:166: UserWarning: Asynchronous callbacks can not be processed without at least one worker thread.
  warnings.warn(
2021-07-03 14:10:46,986 - apscheduler.scheduler - INFO - Scheduler started
2021-07-03 14:10:47,971 - freqtrade.rpc.telegram - INFO - rpc.telegram is listening for following commands: [['status'], ['profit'], ['balance'], ['start'], ['stop'], ['forcesell'], ['forcebuy'], ['trades'], ['delete'], ['performance'], ['stats'], ['daily'], ['count'], ['locks'], ['unlock', 'delete_locks'], ['reload_config', 'reload_conf'], ['show_config', 'show_conf'], ['stopbuy'], ['whitelist'], ['blacklist'], ['logs'], ['edge'], ['help'], ['version']]
2021-07-03 14:10:47,973 - freqtrade.rpc.rpc_manager - INFO - Enabling rpc.api_server
2021-07-03 14:10:48,637 - freqtrade.rpc.api_server.webserver - INFO - Starting HTTP Server at 127.0.0.1:8080
2021-07-03 14:10:48,639 - freqtrade.rpc.api_server.webserver - INFO - Starting Local Rest Server.
INFO:     Started server process [1]
2021-07-03 14:10:48,663 - uvicorn.error - INFO - Started server process [1]
INFO:     Waiting for application startup.
2021-07-03 14:10:48,665 - uvicorn.error - INFO - Waiting for application startup.
INFO:     Application startup complete.
2021-07-03 14:10:48,667 - uvicorn.error - INFO - Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)
2021-07-03 14:10:48,669 - uvicorn.error - INFO - Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)
2021-07-03 14:10:48,671 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'stopped'}
2021-07-03 14:10:49,466 - freqtrade.worker - INFO - Changing state to: STOPPED
2021-07-03 14:10:52,502 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2021-07-03 14:10:52,504 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/ext/updater.py", line 520, in _network_loop_retry
    if not action_cb():
  File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/ext/updater.py", line 471, in polling_action_cb
    updates = self.bot.get_updates(
  File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/bot.py", line 127, in decorator
    result = func(*args, **kwargs)
  File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/bot.py", line 2761, in get_updates
    result = self._post(
  File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/bot.py", line 259, in _post
    return self.request.post(
  File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/utils/request.py", line 350, in post
    result = self._request_wrapper(
  File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/utils/request.py", line 277, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
```

Is restarting Docker and creating a new token not correct? Where can I find these duplicate instances of the Telegram bot running?

**Comment by bigsee** [comment]
I'm going to spin up a brand new VPS instance and see if that solves the issue in the meantime.

**Comment by bigsee** [comment]
I get exactly the same result with a brand new VPS instance where I didn't use freqtrade before and with freshly installed `docker-compose`. Is there a way that I can find duplicate bot instances running from within Telegram maybe?

**Comment by xmatthias** [comment]
not really - no (at least i don't know how).

with a new bot / token - this should not happen.

The most likely cause is that you ran a command (unintentionally?) locally on your local machine ... so the running one is that.

**Comment by bigsee** [comment]
Hmmm... I don't have docker on my local machine so I'm pretty confident that this isn't the case. I use the Terminal to ssh into the VPS and then run everything from there. I also created a brand new Telegram bot and have been able to reproduce after killing the bot and trying to restart.

Maybe it's something in my image / `user_data` folder causing this? I am going to try and reproduce with a brand new image and server later on to figure out what I am doing / have done wrong. I will report back.

**Comment by xmatthias** [comment]
if you kill it (don't allow it to shutdown gracefully) - it's surely possible that telegram will keep the "update-lock" in place for some time.

There's not really anything we can do against this.

**Comment by bigsee** [comment]
How do we shut the bot down "gracefully"? Just via the `/stop` command from Telegram, right?

And in cases where the bot stops responding like my case above (in spite of using daemon mode `docker-compose up -d`), how do we get around this duplicate bot issue? Just delete this bot and create a brand new one, I guess?

**Comment by xmatthias** [comment]
`/stop` will not completely stop freqtrade - but will rather simply halt the trading loop.
this means, it will still respond to commands - and will as such still be connected to telegram.

The correct way will be `docker-compose down` - giving it time to shutdown.

I'm using that all the time, and never encountered the issue where telegram would not allow the new container to start up.

**Comment by bigsee** [comment]
Thank you, I will test this. Perhaps I was not waiting long enough after `docker-compose down`. Telegram actually _does_ allow the new container to start up even with this duplicate bot error and it places trades seemingly as "normal". However there is this constant error on every cycle of the trading loop and I have the feeling that something is wrong.

**Comment by xmatthias** [comment]
with this error, i don't think the bot can accept commands ...

**Comment by samgermain** [comment]
What if the whole bot is in a try statement and we recursively call the bot again in the catch? 

Like
```
def run_freqtrade(*args, **kwargs):
    try:
        freqtrade.main(*args, **kwargs)
    catch:
        run_freqtrade(*args, **kwargs)
```

**Comment by xmatthias** [comment]
It'll depend on the exception - most exceptions are already captured and handled properly - the ones that are not are stopping the bot intentionally.

The above is an exception that never really bubbles out of the telegram package to begin with - so it's not impacting the bot per se - and we're not even seeing this is happening outside of the logs.
