### ISSUE TITLE
race condition

### ISSUE THREAD

**Issue by squat0001** [freqtrade/freqtrade#5248]
running dry mode, the bot crashed in a race condition:

2021-07-08 05:00:09,175 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/srv/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker.run()
  File "/srv/freqtrade/freqtrade/worker.py", line 74, in run
    state = self._worker(old_state=state)
  File "/srv/freqtrade/freqtrade/worker.py", line 111, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
  File "/srv/freqtrade/freqtrade/worker.py", line 132, in _throttle
    result = func(*args, **kwargs)
  File "/srv/freqtrade/freqtrade/worker.py", line 145, in _process_running
    self.freqtrade.process()
  File "/srv/freqtrade/freqtrade/freqtradebot.py", line 179, in process
    self.exit_positions(trades)
  File "/srv/freqtrade/freqtrade/freqtradebot.py", line 663, in exit_positions
    if trade.open_order_id is None and trade.is_open and self.handle_trade(trade):
  File "/srv/freqtrade/freqtrade/freqtradebot.py", line 696, in handle_trade
    if self._check_and_execute_sell(trade, sell_rate, buy, sell):
  File "/srv/freqtrade/freqtrade/freqtradebot.py", line 845, in _check_and_execute_sell
    self.execute_sell(trade, sell_rate, should_sell)
  File "/srv/freqtrade/freqtrade/freqtradebot.py", line 1097, in execute_sell
    time_in_force=time_in_force
  File "/srv/freqtrade/freqtrade/exchange/exchange.py", line 740, in sell
    dry_order = self.create_dry_run_order(pair, ordertype, "sell", amount, rate)
  File "/srv/freqtrade/freqtrade/exchange/exchange.py", line 591, in create_dry_run_order
    average = self.get_dry_market_fill_price(pair, side, amount, rate)
  File "/srv/freqtrade/freqtrade/exchange/exchange.py", line 637, in get_dry_market_fill_price
    filled_amount += remaining_amount * book_entry_price
UnboundLocalError: local variable 'book_entry_price' referenced before assignment
2021-07-08 05:00:09,187 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2021-07-08 05:00:09,187 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2021-07-08 05:00:09,393 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2021-07-08 05:00:09,394 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': warning, 'status': "4 open trades active.\n\nHandle these trades manually on Binance, or '/start'
the bot again and use '/stopbuy' to handle open trades gracefully. \nTrades are simulated."}

i believe it has to do with my new custom_sell code:

```
   def custom_sell(self, pair: str, trade: 'Trade', current_time: 'datetime', current_rate: float,
                    current_profit: float, **kwargs):
        dataframe, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)
        last_candle = dataframe.iloc[-1].squeeze()

        trade_open_date = timeframe_to_prev_date(self.timeframe, trade.open_date_utc)
        trade_rows = dataframe.loc[(dataframe['date'] >= trade_open_date) & (dataframe['date'] <= current_time)]

        trange = dataframe.loc[(dataframe['date'] >= trade_open_date) & (dataframe['date'] <= current_time)]

```

**Comment by xmatthias** [comment]
well - no - it's not related to anything a strategy does.

the error indicates that the orderbook at the bids side had no entries - therefore the "filling loop"  for market orders was never executed.

It'd be interresting to know which pair you had open at that time (and which exchange that's running against) - as it's probably a pretty rarely traded pair (i've seen empty orderbooks a few times on very odd pairs - although in a different context).

**Comment by squat0001** [comment]
Thanks for your input, and sorry. I read your comment.. and suddenly new why.. the problem is, the strat is using some informative pairs, and i did change for testing the timeframe.. but did not ajust the informative pairs.
Thanks for the reply, Sorry for wasting your time.
