### ISSUE TITLE
installation fails on Raspberry Pi 4 with docker-compose build

### ISSUE THREAD

**Issue by ghost** [freqtrade/freqtrade#5320]
## Describe your environment

  * Operating system: Raspberry Pi OS Lite Release date: May 7th 2021
  * Python Version: using docker-compose (FROM python:3.9.5-slim-buster as base) se log below
  * CCXT version: sorry don't know, using docker, see log below
  * Freqtrade Version: 25.07.2021 stable, custom_arm64 (as per https://www.freqtrade.io/en/stable/docker_quickstart/ for ARM 64 Systenms (Mac M1, Raspberry Pi 4, Jetson Nano))
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

'docker-compose build' fails with ERROR

### Steps to reproduce:

 Clone Freqtrade repository
git clone  https://github.com/freqtrade/freqtrade.git
cd freqtrade
 Optionally switch to the stable version
git checkout stable   

 Modify your docker-compose file to enable building and change the image name 
 (see the Note Box below for necessary changes)
image: freqtradeorg/freqtrade:custom_arm64
build:
  context: .
  dockerfile: "Dockerfile"

 Build image
docker-compose build

  
### Observed Results:

Fails with ERROR

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
Building freqtrade
Step 1/26 : FROM python:3.9.5-slim-buster as base
 ---> 4e69a35d1630
Step 2/26 : ENV LANG C.UTF-8
 ---> Using cache
 ---> a5a307b2c752
Step 3/26 : ENV LC_ALL C.UTF-8
 ---> Using cache
 ---> a2a7fad74d08
Step 4/26 : ENV PYTHONDONTWRITEBYTECODE 1
 ---> Using cache
 ---> 8289aa93abd7
Step 5/26 : ENV PYTHONFAULTHANDLER 1
 ---> Using cache
 ---> df3b9b68a456
Step 6/26 : ENV PATH=/home/ftuser/.local/bin:$PATH
 ---> Using cache
 ---> 4f925c7b9cde
Step 7/26 : ENV FT_APP_ENV="docker"
 ---> Using cache
 ---> fc88c4b19592
Step 8/26 : RUN mkdir /freqtrade   && apt-get update   && apt-get -y install sudo libatlas3-base curl sqlite3 libhdf5-serial-dev    && apt-get clean   && useradd -u 1000 -G sudo -U -m ftuser   && chown ftuser:ftuser /freqtrade   && echo "ftuser ALL=(ALL) NOPASSWD: /bin/chown" >> /etc/sudoers
 ---> Using cache
 ---> f7a791692baf
Step 9/26 : WORKDIR /freqtrade
 ---> Using cache
 ---> 0a4e1bf5f0e5
Step 10/26 : FROM base as python-deps
 ---> 0a4e1bf5f0e5
Step 11/26 : RUN  apt-get update   && apt-get -y install build-essential libssl-dev git libffi-dev libgfortran5 pkg-config cmake gcc   && apt-get clean   && pip install --upgrade pip
 ---> Using cache
 ---> a69a37c9b139
Step 12/26 : COPY build_helpers/* /tmp/
 ---> Using cache
 ---> eae00337c2d2
Step 13/26 : RUN cd /tmp && /tmp/install_ta-lib.sh && rm -r /tmp/*ta-lib*
 ---> Using cache
 ---> 115993573208
Step 14/26 : ENV LD_LIBRARY_PATH /usr/local/lib
 ---> Using cache
 ---> 700381b2a9b1
Step 15/26 : COPY --chown=ftuser:ftuser requirements.txt requirements-hyperopt.txt /freqtrade/
 ---> Using cache
 ---> 89754dc580df
Step 16/26 : USER ftuser
 ---> Using cache
 ---> 57d0749e915e
Step 17/26 : RUN  pip install --user --no-cache-dir numpy   && pip install --user --no-cache-dir -r requirements-hyperopt.txt
 ---> Running in ef0e988486c7
Collecting numpy
  Downloading numpy-1.21.1.zip (10.3 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Building wheels for collected packages: numpy
  Building wheel for numpy (PEP 517): started
  Building wheel for numpy (PEP 517): still running...
  Building wheel for numpy (PEP 517): still running...
  Building wheel for numpy (PEP 517): still running...
  Building wheel for numpy (PEP 517): still running...
  Building wheel for numpy (PEP 517): still running...
  Building wheel for numpy (PEP 517): still running...
  Building wheel for numpy (PEP 517): still running...
  Building wheel for numpy (PEP 517): finished with status 'done'
  Created wheel for numpy: filename=numpy-1.21.1-cp39-cp39-linux_armv7l.whl size=5941807 sha256=c659b7c41acfe4a9a2e45ffc6e33dd4078cbc2059e649bd2dc3dd2e7e8490e58
  Stored in directory: /tmp/pip-ephem-wheel-cache-i4tm_dur/wheels/61/98/3f/6560750cfae9b9264325ca61f0aea74cc03048b7f950c328a6
Successfully built numpy
Installing collected packages: numpy
Successfully installed numpy-1.21.1
Collecting numpy==1.20.3
  Downloading numpy-1.20.3.zip (7.8 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: still running...
    Preparing wheel metadata: finished with status 'done'
Collecting pandas==1.2.4
  Downloading pandas-1.2.4.tar.gz (5.5 MB)
  Installing build dependencies: started
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: still running...
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/ccxt/
Collecting ccxt==1.51.77
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/f5/9a/1c6dd96444b099e72cc9b24c67428da8e5f1dd77b4ab1b357b25960c8bf3/ccxt-1.51.77-py2.py3-none-any.whl
  Downloading ccxt-1.51.77-py2.py3-none-any.whl (2.0 MB)
Collecting cryptography==3.4.7
  Downloading cryptography-3.4.7.tar.gz (546 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Collecting aiohttp==3.7.4.post0
  Downloading aiohttp-3.7.4.post0.tar.gz (1.1 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Collecting SQLAlchemy==1.4.18
  Downloading SQLAlchemy-1.4.18.tar.gz (7.6 MB)
Collecting python-telegram-bot==13.6
  Downloading python_telegram_bot-13.6-py3-none-any.whl (484 kB)
Collecting arrow==1.1.0
  Downloading arrow-1.1.0-py3-none-any.whl (58 kB)
Collecting cachetools==4.2.2
  Downloading cachetools-4.2.2-py3-none-any.whl (11 kB)
Collecting requests==2.25.1
  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting urllib3==1.26.5
  Downloading urllib3-1.26.5-py2.py3-none-any.whl (138 kB)
Collecting wrapt==1.12.1
  Downloading wrapt-1.12.1.tar.gz (27 kB)
Collecting jsonschema==3.2.0
  Downloading jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)
Collecting TA-Lib==0.4.20
  Downloading TA-Lib-0.4.20.tar.gz (266 kB)
Collecting technical==1.3.0
  Downloading technical-1.3.0-py3-none-any.whl (51 kB)
Collecting tabulate==0.8.9
  Downloading tabulate-0.8.9-py3-none-any.whl (25 kB)
Collecting pycoingecko==2.2.0
  Downloading pycoingecko-2.2.0-py3-none-any.whl (8.3 kB)
Collecting jinja2==3.0.1
  Downloading Jinja2-3.0.1-py3-none-any.whl (133 kB)
Collecting tables==3.6.1
  Downloading tables-3.6.1.tar.gz (4.6 MB)
Collecting blosc==1.10.4
  Downloading blosc-1.10.4.tar.gz (858 kB)
  Installing build dependencies: started
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/py-find-1st/
Collecting py_find_1st==1.1.5
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/51/94/d29e43472aa4dde37f91b3e1fcdf5f48b722285e54773acd688417184110/py_find_1st-1.1.5.tar.gz
  Downloading py_find_1st-1.1.5.tar.gz (8.8 kB)
  Installing build dependencies: started
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/python-rapidjson/
Collecting python-rapidjson==1.0
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/cf/c7/c1bfb4d26d87d0a484bb0d5c41995d0fb9fd45d847f6359f9a9bd3704960/python-rapidjson-1.0.tar.gz
  Downloading python-rapidjson-1.0.tar.gz (206 kB)
Collecting sdnotify==0.3.2
  Downloading sdnotify-0.3.2.tar.gz (2.5 kB)
Collecting fastapi==0.65.2
  Downloading fastapi-0.65.2-py3-none-any.whl (51 kB)
Collecting uvicorn==0.14.0
  Downloading uvicorn-0.14.0-py3-none-any.whl (50 kB)
Collecting pyjwt==2.1.0
  Downloading PyJWT-2.1.0-py3-none-any.whl (16 kB)
Collecting aiofiles==0.7.0
  Downloading aiofiles-0.7.0-py3-none-any.whl (13 kB)
Collecting colorama==0.4.4
  Downloading colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting questionary==1.9.0
  Downloading questionary-1.9.0-py3-none-any.whl (32 kB)
Collecting prompt-toolkit==3.0.19
  Downloading prompt_toolkit-3.0.19-py3-none-any.whl (368 kB)
Collecting scipy==1.7.0
  Downloading scipy-1.7.0.tar.gz (36.1 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: still running...
    Preparing wheel metadata: still running...
    Preparing wheel metadata: still running...
    Preparing wheel metadata: still running...
    Preparing wheel metadata: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python /usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpphv7hncx
         cwd: /tmp/pip-install-49_ftew8/scipy_712b8ad985904e7b9924469d87613dcc
    Complete output (191 lines):
    setup.py:490: UserWarning: Unrecognized setuptools command ('dist_info --egg-base /tmp/pip-modern-metadata-3x1p8oey'), proceeding with generating Cython sources and expanding templates
      warnings.warn("Unrecognized setuptools command ('{}'), proceeding with "
    Running from SciPy source directory.
    Running scipy/stats/_generate_pyx.py
    Running scipy/special/_generate_pyx.py
    Running scipy/linalg/_generate_pyx.py
    Processing scipy/cluster/_vq.pyx
    Processing scipy/cluster/_optimal_leaf_ordering.pyx
    Processing scipy/cluster/_hierarchy.pyx
    Processing scipy/stats/_qmc_cy.pyx
    Processing scipy/stats/_sobol.pyx
    Processing scipy/stats/biasedurn.pyx
    Processing scipy/stats/_stats.pyx
    Processing scipy/stats/_boost/src/beta_ufunc.pyx
    Processing scipy/stats/_boost/src/binom_ufunc.pyx
    Processing scipy/stats/_boost/src/nbinom_ufunc.pyx
    Processing scipy/fftpack/convolve.pyx
    Processing scipy/signal/_upfirdn_apply.pyx
    Processing scipy/signal/_spectral.pyx
    Processing scipy/signal/_max_len_seq_inner.pyx
    Processing scipy/signal/_sosfilt.pyx
    Processing scipy/signal/_peak_finding_utils.pyx
    Processing scipy/spatial/_voronoi.pyx
    Processing scipy/spatial/ckdtree.pyx
    Processing scipy/spatial/qhull.pyx
    Processing scipy/spatial/_hausdorff.pyx
    Processing scipy/spatial/transform/rotation.pyx
    Processing scipy/special/_comb.pyx
    Processing scipy/special/_ufuncs.pyx
    Processing scipy/special/cython_special.pyx
    Processing scipy/special/_ellip_harm_2.pyx
    Processing scipy/special/_test_round.pyx
    Processing scipy/special/_ufuncs_cxx.pyx
    Processing scipy/optimize/_group_columns.pyx
    Processing scipy/optimize/_bglu_dense.pyx
    warning: _cython_special_custom.pxi:9:8: Unreachable code
    warning: _cython_special_custom.pxi:13:4: Unreachable code
    warning: _cython_special_custom.pxi:21:8: Unreachable code
    warning: _cython_special_custom.pxi:25:4: Unreachable code
    warning: _cython_special_custom.pxi:33:8: Unreachable code
    warning: _cython_special_custom.pxi:37:4: Unreachable code
    warning: _cython_special_custom.pxi:45:8: Unreachable code
    warning: _cython_special_custom.pxi:49:4: Unreachable code
    Processing scipy/optimize/_trlib/_trlib.pyx
    Processing scipy/optimize/cython_optimize/_zeros.pyx.in
    Processing scipy/optimize/_lsq/givens_elimination.pyx
    Processing scipy/optimize/_highs/cython/src/_highs_wrapper.pyx
    Processing scipy/optimize/_highs/cython/src/_highs_constants.pyx
    Processing scipy/ndimage/src/_cytest.pyx
    Processing scipy/ndimage/src/_ni_label.pyx
    Processing scipy/io/matlab/mio5_utils.pyx
    Processing scipy/io/matlab/streams.pyx
    Processing scipy/io/matlab/mio_utils.pyx
    Processing scipy/interpolate/_ppoly.pyx
    Processing scipy/interpolate/_bspl.pyx
    Processing scipy/interpolate/interpnd.pyx
    Processing scipy/sparse/_csparsetools.pyx.in
    Processing scipy/sparse/csgraph/_flow.pyx
    Processing scipy/sparse/csgraph/_matching.pyx
    Processing scipy/sparse/csgraph/_shortest_path.pyx
    Processing scipy/sparse/csgraph/_min_spanning_tree.pyx
    Processing scipy/sparse/csgraph/_traversal.pyx
    Processing scipy/sparse/csgraph/_reordering.pyx
    Processing scipy/sparse/csgraph/_tools.pyx
    Processing scipy/_lib/messagestream.pyx
    Processing scipy/_lib/_test_deprecation_def.pyx
    Processing scipy/_lib/_test_deprecation_call.pyx
    Processing scipy/_lib/_ccallback_c.pyx
    Processing scipy/linalg/_solve_toeplitz.pyx
    Processing scipy/linalg/_decomp_update.pyx.in
    Processing scipy/linalg/_matfuncs_sqrtm_triu.pyx
    Processing scipy/linalg/cython_lapack.pyx
    Processing scipy/linalg/cython_blas.pyx
    Cythonizing sources
    lapack_opt_info:
    lapack_mkl_info:
    customize UnixCCompiler
      libraries mkl_rt not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
      NOT AVAILABLE
    
    openblas_lapack_info:
      libraries openblas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
      NOT AVAILABLE
    
    openblas_clapack_info:
      libraries openblas,lapack not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
      NOT AVAILABLE
    
    flame_info:
      libraries flame not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
      NOT AVAILABLE
    
    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
      libraries lapack_atlas not found in /usr/local/lib
      libraries tatlas,tatlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/lib
      libraries tatlas,tatlas not found in /usr/lib
      libraries lapack_atlas not found in /usr/lib/arm-linux-gnueabihf/atlas
      libraries tatlas,tatlas not found in /usr/lib/arm-linux-gnueabihf/atlas
      libraries lapack_atlas not found in /usr/lib/arm-linux-gnueabihf
      libraries tatlas,tatlas not found in /usr/lib/arm-linux-gnueabihf
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE
    
    atlas_3_10_info:
      libraries lapack_atlas not found in /usr/local/lib
      libraries satlas,satlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/lib
      libraries satlas,satlas not found in /usr/lib
      libraries lapack_atlas not found in /usr/lib/arm-linux-gnueabihf/atlas
      libraries satlas,satlas not found in /usr/lib/arm-linux-gnueabihf/atlas
      libraries lapack_atlas not found in /usr/lib/arm-linux-gnueabihf
      libraries satlas,satlas not found in /usr/lib/arm-linux-gnueabihf
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE
    
    atlas_threads_info:
    Setting PTATLAS=ATLAS
      libraries lapack_atlas not found in /usr/local/lib
      libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/lib
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib
      libraries lapack_atlas not found in /usr/lib/arm-linux-gnueabihf/atlas
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib/arm-linux-gnueabihf/atlas
      libraries lapack_atlas not found in /usr/lib/arm-linux-gnueabihf
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib/arm-linux-gnueabihf
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE
    
    atlas_info:
      libraries lapack_atlas not found in /usr/local/lib
      libraries f77blas,cblas,atlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/lib
      libraries f77blas,cblas,atlas not found in /usr/lib
      libraries lapack_atlas not found in /usr/lib/arm-linux-gnueabihf/atlas
      libraries f77blas,cblas,atlas not found in /usr/lib/arm-linux-gnueabihf/atlas
      libraries lapack_atlas not found in /usr/lib/arm-linux-gnueabihf
      libraries f77blas,cblas,atlas not found in /usr/lib/arm-linux-gnueabihf
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE
    
    accelerate_info:
      NOT AVAILABLE
    
    lapack_info:
      libraries lapack not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
      NOT AVAILABLE
    
    /tmp/pip-build-env-2gaw1a7n/overlay/lib/python3.9/site-packages/numpy/distutils/system_info.py:1748: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      return getattr(self, '_calc_info_{}'.format(name))()
    lapack_src_info:
      NOT AVAILABLE
    
    /tmp/pip-build-env-2gaw1a7n/overlay/lib/python3.9/site-packages/numpy/distutils/system_info.py:1748: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      return getattr(self, '_calc_info_{}'.format(name))()
      NOT AVAILABLE
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 280, in <module>
        main()
      File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/tmp/pip-build-env-2gaw1a7n/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 166, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/tmp/pip-build-env-2gaw1a7n/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 258, in run_setup
        super(_BuildMetaLegacyBackend,
      File "/tmp/pip-build-env-2gaw1a7n/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 150, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 629, in <module>
        setup_package()
      File "setup.py", line 625, in setup_package
        setup(**metadata)
      File "/tmp/pip-build-env-2gaw1a7n/overlay/lib/python3.9/site-packages/numpy/distutils/core.py", line 135, in setup
        config = configuration()
      File "setup.py", line 528, in configuration
        raise NotFoundError(msg)
    numpy.distutils.system_info.NotFoundError: No BLAS/LAPACK libraries found.
    To build Scipy from sources, BLAS & LAPACK libraries need to be installed.
    See site.cfg.example in the Scipy source directory and
    https://docs.scipy.org/doc/scipy/reference/building/index.html for details.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/bb/bb/944f559d554df6c9adf037aa9fc982a9706ee0e96c0d5beac701cb158900/scipy-1.7.0.tar.gz#sha256=998c5e6ea649489302de2c0bc026ed34284f531df89d2bdc8df3a0d44d165739 (from https://pypi.org/simple/scipy/) (requires-python:>=3.7,<3.10). Command errored out with exit status 1: /usr/local/bin/python /usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpphv7hncx Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement scipy==1.7.0 (from versions: 0.8.0, 0.9.0, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 1.0.0b1, 1.0.0rc1, 1.0.0rc2, 1.0.0, 1.0.1, 1.1.0rc1, 1.1.0, 1.2.0rc1, 1.2.0rc2, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.3.0rc1, 1.3.0rc2, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0rc1, 1.4.0rc2, 1.4.0, 1.4.1, 1.5.0rc1, 1.5.0rc2, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.6.0rc1, 1.6.0rc2, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.7.0rc1, 1.7.0rc2, 1.7.0)
ERROR: No matching distribution found for scipy==1.7.0
ERROR: Service 'freqtrade' failed to build: The command '/bin/sh -c pip install --user --no-cache-dir numpy   && pip install --user --no-cache-dir -r requirements-hyperopt.txt' returned a non-zero code: 1
  ```

**Comment by samgermain** [comment]
maybe try `sudo apt install libpython3.9-dev`

**Comment by ghost** [comment]
@samgermain thanks for the tip! unfortunately, i get this return:

> Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libpython3.9-dev
E: Couldn't find any package by glob 'libpython3.9-dev'
E: Couldn't find any package by regex 'libpython3.9-dev'

**Comment by samgermain** [comment]
Maybe try without docker

```
git clone  --branch develop https://github.com/freqtrade/freqtrade
cd freqtrade
./setup.sh -i
```

**Comment by xmatthias** [comment]
You can simply pull the image (`docker-compose pull`) as long as you're using the `:develop` tag.

That build is now a multi-arch build with support for both raspberry flavors (armv7 and arm64).
As such, there's no need to build the image locally anymore.

The documentation is not updated for this yet (as it would confuse people before the new update is out) - but it'll be updated in time.

--- 

if you need / wan't to build it yourself, you'll need to be very careful with architecture. 
The instruction you followed is for arm64 - but the defaullt system for raspberry (also for the 4) is the armv7 - which is NOT the 64bit version and requires a different docker-file (use the regular raspberry instruction for that).


```
Created wheel for numpy: filename=numpy-1.21.1-cp39-cp39-linux_armv7l.whl 
```

Your log highlighed above suggests that you're not using arm64 system (you need to pick the right download on the raspberry page for that - and it's NOT the obvious one).
As such - please either use the pre-build version of the docker image, follow the "normal" raspberry instruction - or recreate your SDCard with the proper image from the raspberry site before retrying.
