### ISSUE TITLE
Migrate table didn't works

### ISSUE THREAD

**Issue by kamontat** [freqtrade/freqtrade#5349]
## Describe your environment

  * Operating system: Raspberry PI 4
  * Python Version: Docker (`python -V`)
  * CCXT version: Docker (`pip freeze | grep ccxt`)
  * Freqtrade Version: `develop_plot` (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

The DB migration didn't works, It throw error. Look like table bak didn't create on this case.
```
2021-07-31 10:15:33,832 - freqtrade.persistence.migrations - INFO - Running database migration for trades - backup: trades_bak0
2021-07-31 10:15:33,862 - freqtrade.commands.trade_commands - ERROR - trades_bak0
2021-07-31 10:15:33,863 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/freqtrade/freqtrade/worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/freqtrade/freqtrade/freqtradebot.py", line 67, in __init__
    init_db(self.config.get('db_url', None), clean_open_orders=self.config['dry_run'])
  File "/freqtrade/freqtrade/persistence/models.py", line 68, in init_db
    check_migrate(engine, decl_base=_DECL_BASE, previous_tables=previous_tables)
  File "/freqtrade/freqtrade/persistence/migrations.py", line 166, in check_migrate
    migrate_trades_table(decl_base, inspector, engine, table_back_name, cols)
  File "/freqtrade/freqtrade/persistence/migrations.py", line 69, in migrate_trades_table
    for index in inspector.get_indexes(table_back_name):
  File "/home/ftuser/.local/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 605, in get_indexes
    return self.dialect.get_indexes(
  File "<string>", line 2, in get_indexes
  File "/home/ftuser/.local/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 55, in cache
    ret = fn(self, con, *args, **kw)
  File "/home/ftuser/.local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/base.py", line 4055, in get_indexes
    table_oid = self.get_table_oid(
  File "<string>", line 2, in get_table_oid
  File "/home/ftuser/.local/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 55, in cache
    ret = fn(self, con, *args, **kw)
  File "/home/ftuser/.local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/base.py", line 3477, in get_table_oid
    raise exc.NoSuchTableError(table_name)
sqlalchemy.exc.NoSuchTableError: trades_bak0
```

### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
  ```

**Comment by kamontat** [comment]
It try to drop index on table that not exist. So the problem is alter table didn't works as we expected them it work.

https://github.com/freqtrade/freqtrade/blob/138b126d03190f35772167ec21f5c825575a8524/freqtrade/persistence/migrations.py#L67

https://github.com/freqtrade/freqtrade/blob/138b126d03190f35772167ec21f5c825575a8524/freqtrade/persistence/migrations.py#L135-L137

**Comment by xmatthias** [comment]
`develop_plot` is not a valid version.
please use the command provided (`docker-compose run --rm freqtrade -V`) to report the proper version.

**Comment by xmatthias** [comment]
Seems to be limited to postgres (and most likely mariadb) - should be fixed with the latest commit (CI will still take a while to build the docker image).
