### ISSUE TITLE
ERROR - Fatal exception - on sell timeout

### ISSUE THREAD

**Issue by Spirulinea** [freqtrade/freqtrade#5404]
## Describe your environment

  * Docker freqtradeorg/freqtrade:develop_plot
  * Freqtrade Version:  docker-0b6aeddbc
  
## Describe the problem:

*The 'filled' property is not returned in some cases and causes a crash after a sell timeout*

https://github.com/freqtrade/freqtrade/blob/4e83d5c4c627693259a88509eb3a13bd08ee70a3/freqtrade/persistence/models.py#L164

### Relevant code exceptions or logs

  ```
2021-08-11 14:17:26,672 - freqtrade.commands.trade_commands - ERROR - '>' not supported between instances of 'NoneType' and 'int'
2021-08-11 14:17:26,673 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker.run()
  File "/freqtrade/freqtrade/worker.py", line 74, in run
    state = self._worker(old_state=state)
  File "/freqtrade/freqtrade/worker.py", line 111, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
  File "/freqtrade/freqtrade/worker.py", line 132, in _throttle
    result = func(*args, **kwargs)
  File "/freqtrade/freqtrade/worker.py", line 145, in _process_running
    self.freqtrade.process()
  File "/freqtrade/freqtrade/freqtradebot.py", line 171, in process
    self.check_handle_timedout()
  File "/freqtrade/freqtrade/freqtradebot.py", line 912, in check_handle_timedout
    self.handle_cancel_sell(trade, order, constants.CANCEL_REASON['TIMEOUT'])
  File "/freqtrade/freqtrade/freqtradebot.py", line 1007, in handle_cancel_sell
    trade.update_order(co)
  File "/freqtrade/freqtrade/persistence/models.py", line 492, in update_order
    Order.update_orders(self.orders, order)
  File "/freqtrade/freqtrade/persistence/models.py", line 180, in update_orders
    oobj.update_from_ccxt_object(order)
  File "/freqtrade/freqtrade/persistence/models.py", line 164, in update_from_ccxt_object
    if order.get('filled', 0) > 0:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
  ```

**Comment by xmatthias** [comment]
Thanks for reporting.
seems like this happens on canceled orders - which makes sense (although i expected filled to be set to 0 instead of None).

Should be fixed with the latest develop (as you're using docker, please wait for CI to complete before retrying).
