### ISSUE TITLE
moving protections from configuration file to strategy file - is not of type 'array'

### ISSUE THREAD

**Issue by aristosv** [freqtrade/freqtrade#5417]
## Describe your environment

  * Operating system: Debian 10
  * Python Version: Python 3.7.3
  * CCXT version: ccxt==1.54.74
  * Freqtrade Version: freqtrade develop-4f10a885
  
## Your question

I am trying to move the protections from the configuration file to the strategy file. This is what the strategy file looks like.

```
import freqtrade.vendor.qtpylib.indicators as qtpylib
from pandas import DataFrame, DatetimeIndex, merge
from freqtrade.strategy.interface import IStrategy
from typing import Dict, List
from functools import reduce
import talib.abstract as ta
class freqtrade_BTC_aristos(IStrategy):

    protections = [
        {
            "method": "StoplossGuard",
            "lookback_period": 1440,     # in the last 24 hours
            "trade_limit": 5,            # if 5 trades hit stoploss
            "stop_duration": 60,         # stop trading for an hour
            "only_per_pair": False       # applies to all pairs
        },
        {
            "method": "CooldownPeriod",
            "stop_duration": 5           # after closing a trade wait 5 minutes before re-buying the same pair
        },
        {
            "method": "MaxDrawdown",
            "lookback_period": 360,      # in the last 6 hours
            "trade_limit": 20,           # considering only pairs that made at least 20 trades
            "max_allowed_drawdown": 0.2, # if drawdown is more than 20%
            "stop_duration": 60          # stop all trading for 60 minutes
        },
        {
            "method": "LowProfitPairs",
            "lookback_period": 360,      # in the last 6 hours
            "trade_limit": 2,            # considering only pairs that made at least 2 trades
            "required_profit": 0.02,     # with less than 2% profit
            "stop_duration": 60          # stop trading the specific pairs for 60 minutes
        }
    ],

    stoploss = -0.4
    timeframe = '1m'
    trailing_stop = True
    trailing_stop_positive = 0.01
    trailing_stop_positive_offset = 0.02
    trailing_only_offset_is_reached = True

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe['rsi'] = ta.RSI(dataframe, timeperiod=14)
        bollinger = qtpylib.bollinger_bands(qtpylib.typical_price(dataframe), window=20, stds=4)
        dataframe['bb_lowerband'] = bollinger['lower']
        dataframe['bb_middleband'] = bollinger['mid']
        dataframe['bb_upperband'] = bollinger['upper']
        return dataframe

    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                (dataframe['rsi'] < 30) &
                (dataframe['close'] <= 0.98 * dataframe['bb_lowerband'])
            )
            ,
            'buy'] = 1
        return dataframe

    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (),
            'sell'] = 1
        return dataframe
```

This is the error I get

```
2021-08-15 17:31:34,443 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2021-08-15 17:31:34,446 - freqtrade.configuration.config_validation - CRITICAL - Invalid configuration. Reason: ([{'method': 'StoplossGuard', 'lookback_period': 1440, 'trade_limit': 5, 'stop_duration': 60, 'only_per_pair': False}, {'method': 'CooldownPeriod', 'stop_duration': 5}, {'method': 'MaxDrawdown', 'lookback_period': 360, 'trade_limit': 20, 'max_allowed_drawdown': 0.2, 'stop_duration': 60}, {'method': 'LowProfitPairs', 'lookback_period': 360, 'trade_limit': 2, 'required_profit': 0.02, 'stop_duration': 60}],) is not of type 'array'

Failed validating 'type' in schema['properties']['protections']:
    {'items': {'properties': {'lookback_period': {'minimum': 1,
                                                  'type': 'number'},
                              'lookback_period_candles': {'minimum': 1,
                                                          'type': 'number'},
                              'method': {'enum': ['CooldownPeriod',
                                                  'LowProfitPairs',
                                                  'MaxDrawdown',
                                                  'StoplossGuard'],
                                         'type': 'string'},
                              'stop_duration': {'minimum': 0.0,
                                                'type': 'number'},
                              'stop_duration_candles': {'minimum': 0,
                                                        'type': 'number'},
                              'trade_limit': {'minimum': 1,
                                              'type': 'number'}},
               'required': ['method'],
               'type': 'object'},
     'type': 'array'}

On instance['protections']:
    ([{'lookback_period': 1440,
       'method': 'StoplossGuard',
       'only_per_pair': False,
       'stop_duration': 60,
       'trade_limit': 5},
      {'method': 'CooldownPeriod', 'stop_duration': 5},
      {'lookback_period': 360,
       'max_allowed_drawdown': 0.2,
       'method': 'MaxDrawdown',
       'stop_duration': 60,
       'trade_limit': 20},
      {'lookback_period': 360,
       'method': 'LowProfitPairs',
       'required_profit': 0.02,
       'stop_duration': 60,
       'trade_limit': 2}],)
2021-08-15 17:31:34,447 - freqtrade.commands.trade_commands - ERROR - ([{'method': 'StoplossGuard', 'lookback_period': 1440, 'trade_limit': 5, 'stop_duration': 60, 'only_per_pair': False}, {'method': 'CooldownPeriod', 'stop_duration': 5}, {'method': 'MaxDrawdown', 'lookback_period': 360, 'trade_limit': 20, 'max_allowed_drawdown': 0.2, 'stop_duration': 60}, {'method': 'LowProfitPairs', 'lookback_period': 360, 'trade_limit': 2, 'required_profit': 0.02, 'stop_duration': 60}],) is not of type 'array'
2021-08-15 17:31:34,447 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/usr/local/freqtrade_BTC_aristos/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/usr/local/freqtrade_BTC_aristos/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/usr/local/freqtrade_BTC_aristos/freqtrade/worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/usr/local/freqtrade_BTC_aristos/freqtrade/freqtradebot.py", line 63, in __init__
    validate_config_consistency(config)
  File "/usr/local/freqtrade_BTC_aristos/freqtrade/configuration/config_validation.py", line 86, in validate_config_consistency
    validate_config_schema(conf)
  File "/usr/local/freqtrade_BTC_aristos/freqtrade/configuration/config_validation.py", line 62, in validate_config_schema
    best_match(Draft4Validator(conf_schema).iter_errors(conf)).message
jsonschema.exceptions.ValidationError: ([{'method': 'StoplossGuard', 'lookback_period': 1440, 'trade_limit': 5, 'stop_duration': 60, 'only_per_pair': False}, {'method': 'CooldownPeriod', 'stop_duration': 5}, {'method': 'MaxDrawdown', 'lookback_period': 360, 'trade_limit': 20, 'max_allowed_drawdown': 0.2, 'stop_duration': 60}, {'method': 'LowProfitPairs', 'lookback_period': 360, 'trade_limit': 2, 'required_profit': 0.02, 'stop_duration': 60}],) is not of type 'array'
```

I tested the syntax on multiple python checkers but the code appears to be ok. I also tried to copy/paste the example code [directly from the documentation](https://www.freqtrade.io/en/stable/includes/protections/#full-example-of-protections), but I get the same error.

What I'm I doing wrong here?
Thanks

**Comment by xmatthias** [comment]
Trailing commas are killers if created unintentionally :) 


``` python
protections = [
...
    ],    # <= Remove this comma.
```

Having a trailing comma in python will result in the variable (protections, in your case) to become a tuple.

**Comment by aristosv** [comment]
Thank you!
