### ISSUE TITLE
One purchase only，unsupported operand type(s) for *=: 'int' and 'NoneType'

### ISSUE THREAD

**Issue by linliang123** [freqtrade/freqtrade#5429]
## Describe your environment

  * Operating system: __MacOs__
  * Python Version: ___3.8__ (`python -V`)
  * CCXT version: __1.54.74___ (`pip freeze | grep ccxt`)
  * Freqtrade Version: __develop__ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
 
### Steps to reproduce:

  1. Use our built-in strategy - Strategy001.py__
  2.Type the command freqtrade trade --strategy Strategy001。To run the program。

  
### Observed Results:

  * What happened?
     An error occurred after purchasing a currency and the program stopped running
  * What did you expect to happen?
     It can go on to buy other currencies and sell them at the right price
### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
  ```
2021-08-16 18:00:08,924 - freqtrade.wallets - INFO - Wallets synced.
2021-08-16 18:00:09,365 - freqtrade.freqtradebot - INFO - Buy signal found: about create a new trade for EOS/USDT with stake_amount: 3 ...
2021-08-16 18:00:10,395 - freqtrade.commands.trade_commands - ERROR - unsupported operand type(s) for *=: 'int' and 'NoneType'
2021-08-16 18:00:10,395 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/Users/bjgateio/Downloads/freqtrade-develop/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker.run()
  File "/Users/bjgateio/Downloads/freqtrade-develop/freqtrade/worker.py", line 74, in run
    state = self._worker(old_state=state)
  File "/Users/bjgateio/Downloads/freqtrade-develop/freqtrade/worker.py", line 111, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
  File "/Users/bjgateio/Downloads/freqtrade-develop/freqtrade/worker.py", line 132, in _throttle
    result = func(*args, **kwargs)
  File "/Users/bjgateio/Downloads/freqtrade-develop/freqtrade/worker.py", line 145, in _process_running
    self.freqtrade.process()
  File "/Users/bjgateio/Downloads/freqtrade-develop/freqtrade/freqtradebot.py", line 183, in process
    self.enter_positions()
  File "/Users/bjgateio/Downloads/freqtrade-develop/freqtrade/freqtradebot.py", line 383, in enter_positions
    trades_created += self.create_trade(pair)
  File "/Users/bjgateio/Downloads/freqtrade-develop/freqtrade/freqtradebot.py", line 440, in create_trade
    return self.execute_buy(pair, stake_amount, buy_tag=buy_tag)
  File "/Users/bjgateio/Downloads/freqtrade-develop/freqtrade/freqtradebot.py", line 557, in execute_buy
    fee = self.exchange.get_fee(symbol=pair, taker_or_maker='maker')
  File "/Users/bjgateio/Downloads/freqtrade-develop/freqtrade/exchange/common.py", line 89, in wrapper
    return f(*args, **kwargs)
  File "/Users/bjgateio/Downloads/freqtrade-develop/freqtrade/exchange/exchange.py", line 1099, in get_fee
    return self._api.calculate_fee(symbol=symbol, type=type, side=side, amount=amount,
  File "/Users/bjgateio/opt/anaconda3/envs/freqtrade/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1958, in calculate_fee
    cost *= rate
TypeError: unsupported operand type(s) for *=: 'int' and 'NoneType'

**Comment by xmatthias** [comment]
Assuming this is gate.io - this has been fixed in ccxt yesterday morning (reference: https://github.com/ccxt/ccxt/issues/9808). An update of ccxt (`pip install -U ccxt`) will solve this (any version > 1.55.2 has this fixed) - and a regular update of freqtrade develop (including dependencies) will solve this, too.
