### ISSUE TITLE
FreqTrade very strange startup events in the logs.

### ISSUE THREAD

**Issue by aumcara** [freqtrade/freqtrade#5438]
Operating system: Ubuntu 18
    Python Version: 3.9
    CCXT version: 1.55.6
    Freqtrade version: 2021.7
  
While trying to fix my live connection with FTX Exchange, without as far as I know doing something special I could not start FreqTRade normaly anymore and the process is hanging trowing some incrompehensile errors for the newbie that I am :-/ in the logs.

michel@freqtrade:~/freqtrade$  sudo docker-compose down
Stopping freqtrade ... done
Removing freqtrade ... done
Removing network freqtrade_default
michel@freqtrade:~/freqtrade$ sudo docker-compose up -d
Creating network "freqtrade_default" with the default driver
Creating freqtrade ... done

NB: I fact sudo docker-compose down AND sudo docker-compose up -d seems fine ... but when I launch :

 sudo docker-compose logs -f

here is what come out of it :

(I just don't know what to do to solve this issue)
```
freqtrade    | 2021-08-17 12:58:25,102 - uvicorn.error - ERROR - Exception in ASGI application
freqtrade    | Traceback (most recent call last):
freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 369, in run_asgi
freqtrade    |     result = await app(self.scope, self.receive, self.send)
freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 59, in __call__
freqtrade    |     return await self.app(scope, receive, send)
freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/uvicorn/middleware/message_logger.py", line 81, in __call__
freqtrade    |     raise exc from None
freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/uvicorn/middleware/message_logger.py", line 77, in __call__
freqtrade    |     await self.app(scope, inner_receive, inner_send)
freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
freqtrade    |     await super().__call__(scope, receive, send)
freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
freqtrade    |     await self.middleware_stack(scope, receive, send)
freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
freqtrade    |     raise exc from None
freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
freqtrade    |     await self.app(scope, receive, _send)
freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 78, in __call__
freqtrade    |     await self.app(scope, receive, send)
freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
freqtrade    |     raise exc from None
freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
freqtrade    |     await self.app(scope, receive, sender)
freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/routing.py", line 580, in __call__
freqtrade    |     await route.handle(scope, receive, send)
freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/routing.py", line 241, in handle
freqtrade    |     await self.app(scope, receive, send)
freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/routing.py", line 52, in app
freqtrade    |     response = await func(request)
freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/fastapi/routing.py", line 219, in app
freqtrade    |     raw_response = await run_endpoint_function(
freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/fastapi/routing.py", line 154, in run_endpoint_function
freqtrade    |     return await run_in_threadpool(dependant.call, **values)
freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
freqtrade    |     return await loop.run_in_executor(None, func, *args)
freqtrade    |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 814, in run_in_executor
freqtrade    |     executor.submit(func, *args), loop=self)
freqtrade    |   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 163, in submit
freqtrade    |     raise RuntimeError('cannot schedule new futures after '
freqtrade    | RuntimeError: cannot schedule new futures after interpreter shutdown
```

**Comment by xmatthias** [comment]
so far, it's nothing special.
This can happen during shutdown (if new api requests come in during shutdown).

Your problem will be in logs above this one - which are however not included in the above log snippet.

**Comment by aumcara** [comment]
Sorry Matthias, I have attached the logs now.
[git.txt](https://github.com/freqtrade/freqtrade/files/7002161/git.txt)

**Comment by xmatthias** [comment]
As expected - it's a configuration error.

When you get long stack-traces - always scroll to the top to see the origin.
I'd say the error is pretty clear - it's a missconfiguration of volumepairlist.

```
2021-08-17 13:41:32,151 - freqtrade.commands.trade_commands - ERROR - Refresh period of 1800 seconds is smaller than one timeframe of 1d. Please adjust refresh_period to at least 86400 and restart the bot.
```

**Comment by aumcara** [comment]
Matthias !

Many ! Many thanks.

By the way, what would you recommend to be able to have (using FTX) 2 instances .... one running live and trade on FTX and another one in dry mode to be able to adjust strategies, test them before eventualy pushing them live.

Thanks again Matthias .... Freqtrade is really a cool and solid stuff.

**Comment by xmatthias** [comment]
We have [documentation](https://www.freqtrade.io/en/stable/advanced-setup/#running-multiple-instances-of-freqtrade) on how to run multiple bots on one system.
It's even easier with docker ... but will require some prior knowledge in docker (or the willingness to research how it works).
