### ISSUE TITLE
Unable to analyze candle (OHLCV) data for pairs ( dynamic pairlist top 100): input_arrays parameter missing required data key: ema1

### ISSUE THREAD

**Issue by LucianPopaLVP** [freqtrade/freqtrade#5455]
## Describe your environment

  * Operating system: ___Ubuntu_
  * Python Version: ____3.8.11_ (`python -V`)
  * CCXT version: ___latest__ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____latest (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Hi there, 
I have 2 scripts running since Sunday and checked them now and both are posting the next log:

Warning: Unable to analyze candle (OHLCV) data for pairs ( dynamic pairlist top 100): input_arrays parameter missing required data key: ema1
Error: Unexpected error input_arrays parameter missing required data key : ema1 calling <bound method IStrategy._antlyze_ticker_interval of <strategy> object at 0x7f06fc015280>>
Warning: last tick is 60 min old.

I haven't done any modifications to the files since I started both of them on Sunday and so far they have worked just fine, but now I don't even know if they are working.. they start and stop if I run the command but they haven't made any trades since last night.

what seems to be the problem?
Thank you!

log:
2021-08-19 11:16:40,594 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair DGB/USDT: input_arrays parameter missing required data key: ema1
2021-08-19 11:16:40,598 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error input_arrays parameter missing required data key: ema1 calling <bound method IStrategy._analyze_ticker_internal of <strategy.strategy object at 0x7fdc0e631a30>>
Traceback (most recent call last):
  File "/home/lvp/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 17, in wrapper
    return f(*args, **kwargs)
  File "/home/lvp/freqtrade/freqtrade/strategy/interface.py", line 417, in _analyze_ticker_internal
    dataframe = self.analyze_ticker(dataframe, metadata)
  File "/home/lvp/freqtrade/freqtrade/strategy/interface.py", line 396, in analyze_ticker
    dataframe = self.advise_indicators(dataframe, metadata)
  File "/home/lvp/freqtrade/freqtrade/strategy/interface.py", line 750, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/home/lvp/freqtrade/user_data/strategies/strategy.py", line 2915, in populate_indicators
    informative_1h = self.informative_1h_indicators(dataframe, metadata)
  File "/home/lvp/freqtrade/user_data/strategies/strategy.py", line 2593, in informative_1h_indicators
    informative_1h['ema_12'] = ta.EMA(informative_1h, timeperiod=12)
  File "talib/_abstract.pxi", line 398, in talib._ta_lib.Function.__call__
  File "talib/_abstract.pxi", line 270, in talib._ta_lib.Function.set_function_args
  File "talib/_abstract.pxi", line 221, in talib._ta_lib.Function.set_input_arrays
Exception: input_arrays parameter missing required data key: ema1
2021-08-19 11:16:40,598 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair ICX/USDT: input_arrays parameter missing required data key: ema1
2021-08-19 11:16:40,602 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error input_arrays parameter missing required data key: ema1 calling <bound method IStrategy._analyze_ticker_internal of <strategy.strategy object at 0x7fdc0e631a30>>
Traceback (most recent call last):

**Comment by xmatthias** [comment]
well the error pretty clearly states that the column 'ema1' is missing.

Without strategy, it's pretty difficult to determine why/where it's not generated - most likely it's generated based on "some" condition that's no longer satisfied.

**Comment by LucianPopaLVP** [comment]
> well the error pretty clearly states that the column 'ema1' is missing.
> 
> Without strategy, it's pretty difficult to determine why/where it's not generated - most likely it's generated based on "some" condition that's no longer satisfied.

there is no 'ema1' in the strategy, just ema100...that's why i am confused. And why it worked for 4 days and now this error out of nothing? :(
[strategy.txt](https://github.com/freqtrade/freqtrade/files/7014089/strategy.txt)

**Comment by xmatthias** [comment]
the most likely cause - you've got 2 files containing a class named "strategy" in your strategy folder. 

`freqtrade list-strategies` will help you identify these eventually.

**Comment by LucianPopaLVP** [comment]
> freqtrade list-strategies

only got two: default AwesomeStrategy that comes with  freqtrade and my strat :(

**Comment by xmatthias** [comment]
The line of error is even mentioned above

```
File "/home/lvp/freqtrade/user_data/strategies/strategy.py", line 2593, in informative_1h_indicators
informative_1h['ema_12'] = ta.EMA(informative_1h, timeperiod=12)
```

So most likely, the "ema1" is a copy/paste error (maybe you removed the 2 while pasting).
Also - line 2593 in your file does not correspond to the line shown above (not even close) - so the strategy that showed the error is definitely not the one you've provided above.
