### ISSUE TITLE
Save the closing price of a TA signal into a simple variable (for a proper demo/live trading strategy)

### ISSUE THREAD

**Issue by d4fuQQ** [freqtrade/freqtrade#5459]
## Describe your environment

  * Operating system: Win 10 (x64)
  * Python Version: 3.8.10 (`python -V`)
  * CCXT version: 1.51.25 (`pip freeze`)
  * Freqtrade Version: freqtrade docker-19158ba7 (`docker-compose run --rm freqtrade -V`)
  
## Your question

Hi,
coming back to my [previous issue](https://github.com/freqtrade/freqtrade/issues/5267), I was able to get this strategy running **within the backtesting evironment**. To do so, I used a combination of simple (but pretty slow) `for`-loops to go through the data of a given time period step by step and adding this data to the dataframe (here: `sample_data`).

It looks something like this (besides a similar section for selling):
```python
###FOR BACKTRADING:
#create empty lists & variables:
buy_trigger = []
last_buy_signal = float('nan')

#go through candle data step by step:
for i in range(len(sample_data)):
    #check for buy signals based on TA indicators and save in a single variable:
    if sample_data['buy_signal'].iloc[i-1] >= 1:
        last_buy_signal = sample_data['close'].iloc[i-1]
    #check if the price change (here: price drop) was at least 1%
    if sample_data['buy_signal'].iloc[i] / last_buy_signal <= 0.99:
        buy_trigger.append(sample_data['buy_signal'].iloc[i]) #could also be "buy_trigger.append(1)" for a 1|nan-list
    else:
        buy_trigger.append(float('nan'))

#add buy_trigger-list to dataframe:
sample_data['buy_trigger'] = buy_trigger
```

Now, I was aiming to optimize this into a usable strategy for freqtrade demo/live trading.
... took me a lot of research, but I found what I was looking for (_at least I thought so as my testing in an individual script yielded solid results_). Here is how I "translated" the script for backtesting into a script for live trading:
```python
class PseudoStrategy_Live(IStrategy):

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        # SMA - Simple Moving Average
        dataframe['fastSMA'] = ta.SMA(dataframe, timeperiod=10)
        dataframe['slowSMA'] = ta.SMA(dataframe, timeperiod=40)
        
        dataframe.loc[
            ((dataframe['fastSMA'] > dataframe['slowSMA']) & (dataframe['fastSMA'].shift(1) <= dataframe['slowSMA'].shift(1)))
            , 'buy_signal'] = dataframe['close'] #could also be "'buy_signal'] = 1" for a 1|nan-list

        dataframe.loc[
            ((dataframe['slowSMA'] > dataframe['fastSMA']) & (dataframe['slowSMA'].shift(1) <= dataframe['fastSMA'].shift(1)))
            , 'sell_signal'] = dataframe['close'] #could also be "'buy_signal'] = 1" for a 1|nan-list

        ### FOR LIVE / DEMO TRADING:
        # Define previous buy signal:
        last_buy_signal = dataframe['buy_signal'].shift(1).last_valid_index() - 1
        last_buy_signal = dataframe['close'].loc[last_buy_signal]

        # Define previous buy trigger (as in 'buy' = 1):
        last_buy_trigger = dataframe['buy'].shift(1).last_valid_index() - 1
        last_buy_trigger = dataframe['close'].loc[last_buy_trigger]

        return dataframe
    
    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                # Check for buy signals, i.e. crossovers depending on given indicators (fastSMA > slowSMA)
                (dataframe['buy_signal'] >= 0) &
                #check if the price change (here: price drop) was at least 1%
                (dataframe['close'] / last_buy_signal <= 0.99)   
            ),
            'buy'] = 1

        return dataframe

    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                # Check for sell signals, i.e. crossovers depending on given indicators (slowSMA > fastSMA)
                (dataframe['sell_signal'] >= 0) &
                #check if the price change (here: price rise) was at least 1%
                (dataframe['close'] / last_buy_trigger >= 1.01)   
            ),
            'sell'] = 1

        return dataframe
```

According to the error message(s) below, I guess this is one of parts causing some trouble:
```python
        last_buy_signal = dataframe['buy_signal'].shift(1).last_valid_index() - 1
        last_buy_signal = dataframe['close'].loc[last_buy_signal]
```
However, I'm not entirely sure if or why that would be the case... 

As you can see, the idea is to simply save the closing price `dataframe['close']` of the last buy signal (or trigger) into a single variable, so that the program is able to compare this price to the recent/current upcoming intervals and act depending on the percentage change (as defined in the populate buy/sell trend functions).

Well, any help here is appreciated again :)

Error log extraction:
```
freqtrade    | 2021-08-19 23:25:49,925 - freqtrade.worker - INFO - Changing state to: RUNNING
freqtrade    | 2021-08-19 23:25:49,925 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': warning, 'status': 'Dry run is enabled. All trades are simulated.'}
freqtrade    | 2021-08-19 23:25:49,926 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': "*Exchange:* `binance`\n*Stake per trade:* `unlimited EUR`\n*Minimum ROI:* `{'0': 0.5}`\n*Stoploss:* `-0.9`\n*Timeframe:* `1m`\n*Strategy:* `DMACRestricted`"}
freqtrade    | 2021-08-19 23:25:49,926 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': "Searching for EUR pairs to buy and sell based on [{'StaticPairList': 'StaticPairList'}]"}
freqtrade    | 2021-08-19 23:25:50,669 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error 'buy' calling <bound method IStrategy._analyze_ticker_internal of <DMACRestricted.DMACRestricted object at 0x7f4fe6546c10>>
freqtrade    | Traceback (most recent call last):
freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
freqtrade    |     return self._engine.get_loc(casted_key)
freqtrade    |   File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
freqtrade    |   File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
freqtrade    |   File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
freqtrade    |   File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
freqtrade    | KeyError: 'buy'
freqtrade    |
freqtrade    | The above exception was the direct cause of the following exception:
freqtrade    |
freqtrade    | Traceback (most recent call last):
freqtrade    |   File "/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 17, in wrapper
freqtrade    |     return f(*args, **kwargs)
freqtrade    |   File "/freqtrade/freqtrade/strategy/interface.py", line 454, in _analyze_ticker_internal
freqtrade    |     dataframe = self.analyze_ticker(dataframe, metadata)
freqtrade    |   File "/freqtrade/freqtrade/strategy/interface.py", line 433, in analyze_ticker
freqtrade    |     dataframe = self.advise_indicators(dataframe, metadata)
freqtrade    |   File "/freqtrade/freqtrade/strategy/interface.py", line 798, in advise_indicators
freqtrade    |     return self.populate_indicators(dataframe, metadata)
freqtrade    |   File "/freqtrade/user_data/strategies/DMACRestricted_v1 copy.py", line 85, in populate_indicators
freqtrade    |     last_buy_trigger = dataframe['buy'].shift(1).last_valid_index() - 1
freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/pandas/core/frame.py", line 3455, in __getitem__
freqtrade    |     indexer = self.columns.get_loc(key)
freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
freqtrade    |     raise KeyError(key) from err
freqtrade    | KeyError: 'buy'
freqtrade    | 2021-08-19 23:25:50,672 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair LTC/EUR: 'buy'
freqtrade    | 2021-08-19 23:25:50,685 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair LTC/EUR
freqtrade    | 2021-08-19 23:25:54,932 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='docker-19158ba7', state='RUNNING'
```

**Comment by xmatthias** [comment]
we have a [documentation page](https://www.freqtrade.io/en/stable/bot-basics/#bot-execution-logic) that's listing out the sequence in which each method is called.

As you're using `'buy'` in populate_indicators - it'll not be defined, therefore you're getting this error.

**Comment by d4fuQQ** [comment]
alright, thanks for the link! I thought I'd have seen every documentation page by now, but apparently I didn't, haha.

This makes sense.
I just tried putting both of these expressions into the `populate_buy_trend` function:

```python
    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        
        # Define previous buy signal:
        last_buy_signal = dataframe['buy_signal'].shift(1).last_valid_index() - 1
        last_buy_signal = dataframe['close'].loc[last_buy_signal]

        dataframe.loc[
            (
                # Check for buy signals, i.e. crossovers depending on given indicators (fastSMA > slowSMA)
                (dataframe['buy_signal'] >= 0) &
                #check if the price change (here: price drop) was at least 1%
                (dataframe['close'] / last_buy_signal <= 0.99)   
            ),
            'buy'] = 1

        # Define previous buy trigger:
        last_buy_trigger = dataframe['buy'].shift(1).last_valid_index() - 1
        last_buy_trigger = dataframe['close'].loc[last_buy_trigger]
        
        return dataframe
```

... but in contrast to my individual python script where the variables are actually filled with the correct values, there is now another error regarding the operand type in freqtrade. I think this is somewhat confusing as the expression `dataframe['buy'].shift(1).last_valid_index() - 1` is meant to return the index value (i.e. integer) where the last buy signal or trigger occured. It's a bit tricky to explain, but if I don't use `shift(1)` as well as `- 1`, then either **(i) the current (most recent) value minus 1 (= second last index value/blue)** or **(ii) the index value of a previous signal plus 1 (yellow)** is reported.

This image explains what I mean:

![image](https://user-images.githubusercontent.com/20617933/130677466-a4baf64f-b31a-4ebf-83cc-c493525c9c4e.png)
So, the desired index number to hold on to would only be the green one where the last buy signal (or buy trigger) actually occured.

Well, I don't wanna ask too many questions, but perhaps you have another idea how it may work for freqtrade :)


Error log:
```
freqtrade    | 2021-08-24 18:48:25,761 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': "Searching for EUR pairs to buy and sell based on [{'StaticPairList': 'StaticPairList'}]"}
freqtrade    | 2021-08-24 18:48:26,280 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error unsupported operand type(s) for -: 'NoneType' and 'int' calling <bound method IStrategy._analyze_ticker_internal of <DMACRestricted.DMACRestricted object at 0x7ff376a0fdc0>>
freqtrade    | Traceback (most recent call last):
freqtrade    |   File "/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 17, in wrapper
freqtrade    |     return f(*args, **kwargs)
freqtrade    |   File "/freqtrade/freqtrade/strategy/interface.py", line 454, in _analyze_ticker_internal
freqtrade    |     dataframe = self.analyze_ticker(dataframe, metadata)
freqtrade    |   File "/freqtrade/freqtrade/strategy/interface.py", line 434, in analyze_ticker
freqtrade    |     dataframe = self.advise_buy(dataframe, metadata)
freqtrade    |   File "/freqtrade/freqtrade/strategy/interface.py", line 816, in advise_buy
freqtrade    |     return self.populate_buy_trend(dataframe, metadata)
freqtrade    |   File "/freqtrade/user_data/strategies/DMACRestricted_v2.py", line 110, in populate_buy_trend
freqtrade    |     last_buy_trigger = dataframe['buy'].shift(1).last_valid_index() - 1
freqtrade    | TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
freqtrade    | 2021-08-24 18:48:26,281 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair LTC/EUR: unsupported operand type(s) for -: 'NoneType' and 
'int'
freqtrade    | 2021-08-24 18:48:26,295 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair LTC/EUR
```

**Comment by xmatthias** [comment]
well seems like `dataframe['buy'].shift(1).last_valid_index()` is not getting a value but `None` for the very first buy-signal (which makes sense if you think about it - there won't be a "last valid index" for the first entry).

As the value is then None - the subtraction of -1 fails - which corresponds exactly to the error youre getting.

**Comment by SavvyEngineer** [comment]
@d4fuQQ 
hi i'm trying to develop my strategy and the first thing that I need is my previous order entry price  in populate_buy_trend or sell_trend I found the Trade history section in the documentation but I don't think querying the database is the best approach here because I only need the last order data and I tried to use your method 
```
last_buy_signal = dataframe['buy_signal'].shift(1).last_valid_index() - 1
last_buy_signal = dataframe['close'].loc[last_buy_signal]

```
but as @xmatthias said at the startup of the bot there is no previous order and I'm getting the same error as you get please help thanks
best of regards

**Comment by xmatthias** [comment]
@SavvyEngineer 
The way you're thinking about this is wrong.
Just because you had a buy-signal won't mean that it was a buy that was actually acted on (maybe max_open_trades did not allow for another trade) - and should not be done within `populate_*` methods at all (access to the trade object there will NOT work during backtesting).

Please have a look at the [documentation](https://www.freqtrade.io/en/stable/strategy-advanced/#dataframe-access) which explains how to get the "Opening candle" - and implement your logic in one of the [strategy callbacks](https://www.freqtrade.io/en/stable/strategy-callbacks/) freqtrade provides.

**Comment by SavvyEngineer** [comment]
@xmatthias first of all thanks for your help, so correct me if im wrong in order to create an if statement with my previous order i need to use this
```
last_candle = dataframe.iloc[-1].squeeze()
```
And im kinda confused is this last candle is the candle that my previous order was executed on or its just the last tradable candle of the pair?

**Comment by xmatthias** [comment]
if you use dataframe.iloc[-1] - then it'll be the latest current candle (never use this in populate_* methods).
You should FIRST filter this onto the trade date (as also shown in the above linked documentation).

**Comment by SavvyEngineer** [comment]
> if you use dataframe.iloc[-1] - then it'll be the latest current candle (never use this in populate_* methods).
> You should FIRST filter this onto the trade date (as also shown in the above linked documentation).

Thanks for your help i think this will solve my problem 🎉
