### ISSUE TITLE
binance order amount should be evenly divisible by lot size

### ISSUE THREAD

**Issue by ZerGo0** [freqtrade/freqtrade#5481]
Operating system: Ubuntu 20.04.3 LTS
Python Version: Python 3.8.10
CCXT version: ccxt==1.55.28
Freqtrade Version: freqtrade develop-8a9407bac
  
## Describe the problem:

The bot tried to create a market sell order multiple times, but it failed and showed the following error:
`Unable to sell trade GTC/BUSD: Could not create market sell order on market GTC/BUSD. Tried to sell amount 36.34 at rate 12.56. Message: binance order amount should be evenly divisible by lot size {"code":-1013,"msg":"Filter failure: LOT_SIZE"}`

### Relevant code exceptions or logs

  ```
2021-08-26 07:25:18,250 - freqtrade.freqtradebot - INFO - Buy signal found: about create a new trade for GTC/BUSD with stake_amount: 431.52911774775 ...
2021-08-26 07:25:18,490 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=None, pair=GTC/BUSD, amount=36.38000000, open_rate=11.86000000, open_since=2021-08-26 05:25:18)
2021-08-26 07:25:18,491 - freqtrade.freqtradebot - INFO - Fee for Trade Trade(id=None, pair=GTC/BUSD, amount=36.38000000, open_rate=11.86000000, open_since=2021-08-26 05:25:18) [buy]: 0.03638 GTC - rate: 0.001
2021-08-26 07:25:18,996 - freqtrade.wallets - INFO - Wallets synced.
2021-08-26 07:25:18,997 - freqtrade.freqtradebot - INFO - Applying fee on amount for Trade(id=None, pair=GTC/BUSD, amount=36.38000000, open_rate=11.86000000, open_since=2021-08-26 05:25:18) (from 36.38 to 36.34).
2021-08-26 07:25:18,997 - freqtrade.persistence.models - INFO - Updating trade (id=None) ...
2021-08-26 07:25:18,997 - freqtrade.persistence.models - INFO - MARKET_BUY has been fulfilled for Trade(id=None, pair=GTC/BUSD, amount=36.34000000, open_rate=11.86000000, open_since=2021-08-26 05:25:18).
2021-08-26 07:25:18,997 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'trade_id': None, 'type': buy_fill, 'buy_tag': 'kama_ewo1', 'exchange': 'Binance', 'pair': 'GTC/BUSD', 'open_rate': 11.86, 'stake_amount': 431.4668, 'stake_currency': 'BUSD', 'fiat_currency': 'USD', 'amount': 36.34, 'open_date': datetime.datetime(2021, 8, 26, 5, 25, 18, 490685)}
2021-08-26 07:25:18,998 - freqtrade.rpc.telegram - INFO - Notification 'buy_fill' not sent.
2021-08-26 07:25:19,500 - freqtrade.wallets - INFO - Wallets synced.
2021-08-26 07:25:19,502 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'trade_id': 53, 'type': buy, 'buy_tag': 'kama_ewo1', 'exchange': 'Binance', 'pair': 'GTC/BUSD', 'limit': 11.86, 'order_type': 'market', 'stake_amount': 431.4668, 'stake_currency': 'BUSD', 'fiat_currency': 'USD', 'amount': 36.34, 'open_date': datetime.datetime(2021, 8, 26, 5, 25, 18, 490685), 'current_rate': 11.86}
2021-08-26 08:07:57,895 - freqtrade.freqtradebot - INFO - Executing Sell for GTC/BUSD. Reason: trailing_stop_loss
2021-08-26 08:07:58,411 - freqtrade.wallets - INFO - Wallets synced.
2021-08-26 08:07:58,656 - freqtrade.freqtradebot - WARNING - Unable to sell trade GTC/BUSD: Could not create market sell order on market GTC/BUSD. Tried to sell amount 36.34 at rate 12.192. Message: binance order amount should be evenly divisible by lot size {"code":-1013,"msg":"Filter failure: LOT_SIZE"}
2021-08-26 08:07:59,800 - freqtrade.freqtradebot - INFO - Executing Sell for GTC/BUSD. Reason: trailing_stop_loss
2021-08-26 08:08:00,312 - freqtrade.wallets - INFO - Wallets synced.
...
2021-08-26 08:09:24,614 - freqtrade.freqtradebot - WARNING - Unable to sell trade GTC/BUSD: Could not create market sell order on market GTC/BUSD. Tried to sell amount 36.34 at rate 12.524. Message: binance order amount should be evenly divisible by lot size {"code":-1013,"msg":"Filter failure: LOT_SIZE"}
2021-08-26 08:09:25,818 - freqtrade.freqtradebot - INFO - Executing Sell for GTC/BUSD. Reason: trailing_stop_loss
2021-08-26 08:09:26,324 - freqtrade.wallets - INFO - Wallets synced.
2021-08-26 08:09:26,563 - freqtrade.freqtradebot - WARNING - Unable to sell trade GTC/BUSD: Could not create market sell order on market GTC/BUSD. Tried to sell amount 36.34 at rate 12.51. Message: binance order amount should be evenly divisible by lot size {"code":-1013,"msg":"Filter failure: LOT_SIZE"}
2021-08-26 08:09:27,084 - freqtrade.wallets - INFO - Wallets synced.
2021-08-26 08:09:27,363 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/lib/python3.8/site-packages/uvicorn/middleware/message_logger.py", line 82, in __call__
    raise exc from None
  File "/usr/lib/python3.8/site-packages/uvicorn/middleware/message_logger.py", line 78, in __call__
    await self.app(scope, inner_receive, inner_send)
  File "/usr/lib/python3.8/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/lib/python3.8/site-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/lib/python3.8/site-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/usr/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/usr/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/usr/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/usr/lib/python3.8/site-packages/fastapi/routing.py", line 219, in app
    raw_response = await run_endpoint_function(
  File "/usr/lib/python3.8/site-packages/fastapi/routing.py", line 154, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/lib/python3.8/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/freqtrade_test2/freqtrade/rpc/api_server/api_v1.py", line 134, in forcesell
    return rpc._rpc_forcesell(payload.tradeid)
  File "/root/freqtrade_test2/freqtrade/rpc/rpc.py", line 583, in _rpc_forcesell
    _exec_forcesell(trade)
  File "/root/freqtrade_test2/freqtrade/rpc/rpc.py", line 560, in _exec_forcesell
    self._freqtrade.execute_sell(trade, current_rate, sell_reason)
  File "/root/freqtrade_test2/freqtrade/freqtradebot.py", line 1126, in execute_sell
    order = self.exchange.create_order(pair=trade.pair,
  File "/root/freqtrade_test2/freqtrade/exchange/exchange.py", line 731, in create_order
    raise ExchangeError(
freqtrade.exceptions.ExchangeError: Could not create market sell order on market GTC/BUSD. Tried to sell amount 36.34 at rate 12.51. Message: binance order amount should be evenly divisible by lot size {"code":-1013,"msg":"Filter failure: LOT_SIZE"}
2021-08-26 08:09:28,603 - freqtrade.freqtradebot - INFO - Executing Sell for GTC/BUSD. Reason: trailing_stop_loss
2021-08-26 08:09:29,125 - freqtrade.wallets - INFO - Wallets synced.
2021-08-26 08:09:29,372 - freqtrade.freqtradebot - WARNING - Unable to sell trade GTC/BUSD: Could not create market sell order on market GTC/BUSD. Tried to sell amount 36.34 at rate 12.56. Message: binance order amount should be evenly divisible by lot size {"code":-1013,"msg":"Filter failure: LOT_SIZE"}
2021-08-26 08:09:29,375 - freqtrade.worker - INFO - Bot heartbeat. PID=776505, version='develop-8a9407bac', state='RUNNING'
...
  ```

**Comment by stash86** [comment]
The cause is this update on step size
https://www.binance.com/en/support/announcement/6925d618ab6b47e2936cc4614eaad64b

**Comment by xmatthias** [comment]
Looking at the output of `GTC/BUSD` (code below), we can see that `precision` for amount = 1.

Freqtrade DOES honor this (so freqtrade code is already in place to handle this properly) - however market-data (load-markets) is cached for about an hour by default (there's no point querying this over and over, it doesn't change often).
Considering time differences (assuming you're not in UTC) - this most likely happened pretty soon after the Trading update.

Because of this, i assume that your order was placed right after binance updated their settings - but before your bot refreshed the markets data.

My bot for example happily bought and sold all afternoon without any error - so most likely, my refresh was "better timed".

Unfortunately, due to this change, existing positions will leave "dust" behind (up to the new precision) ... as you noticed, it's now impossible to sell the 0.61 GTC - the only thing you can do is convert it to BNB (dust conversion).

Please have a look if this happens again (or happened later during the day) - but for now, i'll assume this is nothing further to worry about (these limits did exist before today, too, and were respected by the bot, too).

---


```python
import ccxt
exchange = ccxt.binance()
lm = exchange.load_markets()
print(lm['GTC/BUSD'])
```

```
{'percentage': True,
 'feeSide': 'get',
 'tierBased': False,
 'taker': 0.001,
 'maker': 0.001,
 'precision': {'base': 8, 'quote': 8, 'amount': 1, 'price': 3},
 'limits': {'amount': {'min': 0.1, 'max': 9222449.0},
  'price': {'min': 0.001, 'max': 10000.0},
  'cost': {'min': 10.0, 'max': None},
  'market': {'min': 0.0, 'max': 6904.96577298}},
 'id': 'GTCBUSD',
 'lowercaseId': 'gtcbusd',
 'symbol': 'GTC/BUSD',
 'base': 'GTC',
 'quote': 'BUSD',
 'baseId': 'GTC',
 'quoteId': 'BUSD',
 'info': {'symbol': 'GTCBUSD',
  'status': 'TRADING',
  'baseAsset': 'GTC',
  'baseAssetPrecision': '8',
  'quoteAsset': 'BUSD',
  'quotePrecision': '8',
  'quoteAssetPrecision': '8',
  'baseCommissionPrecision': '8',
  'quoteCommissionPrecision': '8',
  'orderTypes': ['LIMIT',
   'LIMIT_MAKER',
   'MARKET',
   'STOP_LOSS_LIMIT',
   'TAKE_PROFIT_LIMIT'],
  'icebergAllowed': True,
  'ocoAllowed': True,
  'quoteOrderQtyMarketAllowed': True,
  'isSpotTradingAllowed': True,
  'isMarginTradingAllowed': False,
  'filters': [{'filterType': 'PRICE_FILTER',
    'minPrice': '0.00100000',
    'maxPrice': '10000.00000000',
    'tickSize': '0.00100000'},
   {'filterType': 'PERCENT_PRICE',
    'multiplierUp': '5',
    'multiplierDown': '0.2',
    'avgPriceMins': '5'},
   {'filterType': 'LOT_SIZE',
    'minQty': '0.10000000',
    'maxQty': '9222449.00000000',
    'stepSize': '0.10000000'},
   {'filterType': 'MIN_NOTIONAL',
    'minNotional': '10.00000000',
    'applyToMarket': True,
    'avgPriceMins': '5'},
   {'filterType': 'ICEBERG_PARTS', 'limit': '10'},
   {'filterType': 'MARKET_LOT_SIZE',
    'minQty': '0.00000000',
    'maxQty': '6904.96577298',
    'stepSize': '0.00000000'},
   {'filterType': 'MAX_NUM_ORDERS', 'maxNumOrders': '200'},
   {'filterType': 'MAX_NUM_ALGO_ORDERS', 'maxNumAlgoOrders': '5'}],
  'permissions': ['SPOT']},
 'spot': True,
 'type': 'spot',
 'margin': False,
 'future': False,
 'delivery': False,
 'linear': False,
 'inverse': False,
 'expiry': None,
 'expiryDatetime': None,
 'active': True,
 'contractSize': None}
```

**Comment by xmatthias** [comment]
As suspected, this has been a problem right after the switch.

Unfortunately, i'd not know how to improve this situation (you can configure the refresh time to be lower - but it'll always leave a "hole" the seconds after the exchange updates settings).

We also can't "Inline" markets refresh - as that would make placing orders very slow (load-markets is often a call that takes seconds to complete - depending on the exchange).

As such - for the moment i don't see anything we can do for this - and realistically, lotsizes are not update frequently (that's the first time i know on binance since ~3 years).
