### ISSUE TITLE
Impossible to load strategy 

### ISSUE THREAD

**Issue by Aayan611** [freqtrade/freqtrade#5488]
2021-08-27 22:33:21,403 - freqtrade.commands.trade_commands - ERROR - Impossible to load Strategy 'test'. This class does not exist or contains Python code errors.
2021-08-27 22:33:21,403 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/ayan/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/home/ayan/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/home/ayan/freqtrade/freqtrade/worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/home/ayan/freqtrade/freqtrade/freqtradebot.py", line 60, in __init__
    self.strategy: IStrategy = StrategyResolver.load_strategy(self.config)
  File "/home/ayan/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 44, in load_strategy
    strategy: IStrategy = StrategyResolver._load_strategy(
  File "/home/ayan/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 212, in _load_strategy
    raise OperationalException(
freqtrade.exceptions.OperationalException: Impossible to load Strategy 'test'. This class does not exist or contains Python code errors.

**Comment by xmatthias** [comment]
Apparently there is no strategy named "test".
Maybe it's named "Test" (python class names are case sensitive) - or maybe it's named test123.

Either way - something is wrong with your strategy - and with the information provided - this is as far as i will be able to assist you.

**Comment by Aayan611** [comment]
Thanks but it came with freqtrade only and i tried with different other strategies it show the same error and the file where code is stored also correct freqtrade/user_data/Strategies

**Comment by xmatthias** [comment]
Best refer to the [documentation](https://www.freqtrade.io/en/stable/strategy-customization/#install-a-custom-strategy-file) how to properly reference a strategy and where the strategy should reside.

Please note: Freqtrade does not come with a strategy called "test".

**Comment by Aayan611** [comment]
i tried that strategy too but same error

**Comment by xmatthias** [comment]
Best follow the [install documentation](https://www.freqtrade.io/en/stable/docker_quickstart/#docker-quick-start) which installs the SampleStrategy.

Please note: Freqtrade does not come with an automatically builtin strategy - you're expected to experiment and develop a strategy on your own.
also - please make sure to read the documentation - it contains answers to most questions you may have.


If you have further questions, please use the [discord channel](https://discord.gg/p7nuUNVfP7) to get support / help from the community.
People there love to help assuming the documentation has been consulted first.

**Comment by Aayan611** [comment]
Thank you very much
