### ISSUE TITLE
USDT is not available as stake on Binance. (NetworkError)

### ISSUE THREAD

**Issue by sameh07** [freqtrade/freqtrade#5498]
## Describe your environment

  * Operating system: Ubuntu
  * Python Version: Python 3.8.10
  * CCXT version:1.55.55
  * Freqtrade Version: freqtrade 2021.8
  
## Your question

*Im getting this error: USDT is not available as stake on Binance. Available currencies are:

ccxt.base.errors.NetworkError: binance GET https://api.binance.com/api/v3/exchangeInfo
2021-08-28 20:57:54,794 - freqtrade.commands.trade_commands - ERROR - USDT is not available as stake on Binance. Available currencies are: 
2021-08-28 20:57:54,794 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/freqtrade/freqtrade/worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/freqtrade/freqtrade/freqtradebot.py", line 65, in __init__
    self.exchange = ExchangeResolver.load_exchange(self.config['exchange']['name'], self.config)
  File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 32, in load_exchange
    exchange = ExchangeResolver._load_exchange(exchange_name,
  File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 54, in _load_exchange
    exchange = ex_class(**kwargs)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 148, in __init__
    self.validate_stakecurrency(config['stake_currency'])
  File "/freqtrade/freqtrade/exchange/exchange.py", line 360, in validate_stakecurrency
    raise OperationalException(
freqtrade.exceptions.OperationalException: USDT is not available as stake on Binance. Available currencies are: 

        "pair_whitelist": [
            "BCH/USDT",
            "ETH/USDT",
            "LINK/USDT",
            "XTZ/USDT"
        ],
        "pair_blacklist": [
            "BNB/BTC",
            "BNB/BUSD",
            "BNB/ETH",
            "BNB/EUR",
            "BNB/NGN",
            "BNB/PAX",
            "BNB/RUB",
            "BNB/TRY",
            "BNB/TUSD",
            "BNB/USDC",
            "BNB/USDS",
            "BNB/USDT"
        ]
    },

**Comment by LazyCoderOZ** [comment]
I am having a similar issue with freqtrade not connecting to Binance and telling me that stake currency AUD is not available. 
Please see below for complete logfile dump. The logfile just repeats this information over and over.

I am using: 
Ubuntu 20.04 
Python 3.9.5
CCXT 1.55.28
Freqtrade 2021.8

As a side note, Freqtrade 2021.7 was running with no problems whatsoever.

[freqtrade_error.txt](https://github.com/freqtrade/freqtrade/files/7071606/freqtrade_error.txt)

**Comment by xmatthias** [comment]
The hint is the network error.
Due to that, freqtrade will not know any markets, and therefore reject all stake currencies.

Its usually either a problem with local setup / network, but in this case (2 people with the same problem very close to each other), more likely a problem on binances side (maybe regionally).

Simply retrying later should help in this case.
