### ISSUE TITLE
Custom Indicators

### ISSUE THREAD

**Issue by xerxesSunshine** [freqtrade/freqtrade#5511]
Hi There,

I have added some custom indicators to my strategy script and when I run the backtest i hit this error.

Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 54, in start_backtesting
    backtesting.start()
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 598, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 557, in backtest_one_strategy
    preprocessed_tmp = trim_dataframes(preprocessed, timerange, self.required_startup)
  File "/freqtrade/freqtrade/data/converter.py", line 160, in trim_dataframes
    trimed_df = trim_dataframe(df, timerange, startup_candles=startup_candles)
  File "/freqtrade/freqtrade/data/converter.py", line 137, in trim_dataframe
    df = df.iloc[startup_candles:, :]
AttributeError: 'NoneType' object has no attribute 'iloc'

Would love some advice on how to tackle this issue so can I can finish off my backtesting and move on to hyperopt

cheers!
- X

**Comment by xmatthias** [comment]
sounds like you're not returning the dataframe from the function - so most likely, you've deleted the `return dataframe` line from the strategy (each `populate*` method must return the dataframe again).

**Comment by xmatthias** [comment]
I'll assume this as answered by the above.

Feel free to comment below / reopen if that's not the case.
