### ISSUE TITLE
Binance US URL not being used when Config Properly Set

### ISSUE THREAD

**Issue by martygriffin** [freqtrade/freqtrade#5555]
## Describe your environment

  * Operating system: Docker (freqtrade:stable)
  * Python Version: 3.9
  * CCXT version: 1.55.28
  * Freqtrade Version: 2021.8
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

I have my exchange section set as the following:

  "exchange": {
    "name": "binanceus",
    "key": "xxxxxx",
    "secret": "xxxxxxxx",
    "ccxt_config": {"enableRateLimit": true},
    "ccxt_async_config": {
        "enableRateLimit": true,
        "rateLimit": 200
    },
      "pair_whitelist":[
    ]
  },

but freq trade is still using the normal Binnacle URL and not the Binance US URL
### Steps to reproduce:

 1. Configure to use Binance US
 2. Start Up bot
 3. Observe logs
 
### Observed Results:

  * What happened?
  * The bot used the regular Binance  API and failed
  * What did you expect to happen?
  * The bot to use the Binance US API and succeed

### Relevant code exceptions or logs
Attaching to freqtrade-3
freqtrade-3  | 2021-09-09 15:28:05,860 - freqtrade.worker - INFO - Starting worker 2021.8
freqtrade-3  | 2021-09-09 15:28:05,861 - freqtrade.configuration.configuration - INFO - Using config: user_data/data/pairlists.json ...
freqtrade-3  | 2021-09-09 15:28:05,868 - freqtrade.configuration.configuration - INFO - Using config: user_data/data/binance-usdt-static.json ...
freqtrade-3  | 2021-09-09 15:28:05,898 - freqtrade.loggers - INFO - Verbosity set to 0
freqtrade-3  | 2021-09-09 15:28:05,902 - freqtrade.configuration.configuration - INFO - Runmode set to live.
freqtrade-3  | 2021-09-09 15:28:05,907 - freqtrade.configuration.configuration - INFO - Parameter --db-url detected ...
freqtrade-3  | 2021-09-09 15:28:05,910 - freqtrade.configuration.configuration - INFO - Dry run is disabled
freqtrade-3  | 2021-09-09 15:28:05,914 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:////freqtrade/user_data/tradesv3.sqlite"
freqtrade-3  | 2021-09-09 15:28:05,918 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 4 ...
freqtrade-3  | 2021-09-09 15:28:09,434 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
freqtrade-3  | 2021-09-09 15:28:09,598 - freqtrade.configuration.configuration - INFO - Using data directory: user_data/data/binance ...
freqtrade-3  | 2021-09-09 15:28:09,603 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
freqtrade-3  | 2021-09-09 15:28:09,644 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
freqtrade-3  | 2021-09-09 15:28:09,649 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
freqtrade-3  | 2021-09-09 15:28:09,654 - freqtrade.freqtradebot - INFO - Starting freqtrade 2021.8
freqtrade-3  | 2021-09-09 15:28:09,789 - NostalgiaForInfinityNext - INFO - pandas_ta successfully imported
freqtrade-3  | 2021-09-09 15:28:09,814 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy NostalgiaForInfinityNext from '/freqtrade/user_data/strategies/NostalgiaForInfinityNext.py'...
freqtrade-3  | 2021-09-09 15:28:09,828 - freqtrade.strategy.hyper - INFO - Found no parameter file.
freqtrade-3  | 2021-09-09 15:28:09,849 - freqtrade.strategy.hyper - INFO - No params for protection found, using default values.
freqtrade-3  | 2021-09-09 15:28:09,869 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 5m.
freqtrade-3  | 2021-09-09 15:28:09,882 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
freqtrade-3  | 2021-09-09 15:28:09,900 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: unlimited.
freqtrade-3  | 2021-09-09 15:28:09,907 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'buy': 10, 'sell': 30, 'unit': 'minutes'}.
freqtrade-3  | 2021-09-09 15:28:09,920 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 10}
freqtrade-3  | 2021-09-09 15:28:09,936 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 5m
freqtrade-3  | 2021-09-09 15:28:09,948 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.5
freqtrade-3  | 2021-09-09 15:28:09,953 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
freqtrade-3  | 2021-09-09 15:28:09,971 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive: 0.01
freqtrade-3  | 2021-09-09 15:28:09,979 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.03
freqtrade-3  | 2021-09-09 15:28:09,983 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: True
freqtrade-3  | 2021-09-09 15:28:09,989 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
freqtrade-3  | 2021-09-09 15:28:10,001 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: True
freqtrade-3  | 2021-09-09 15:28:10,009 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'trailing_stop_loss': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False, 'stoploss_on_exchange_interval': 60, 'stoploss_on_exchange_limit_ratio': 0.99}
freqtrade-3  | 2021-09-09 15:28:10,018 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
freqtrade-3  | 2021-09-09 15:28:10,025 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
freqtrade-3  | 2021-09-09 15:28:10,034 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: unlimited
freqtrade-3  | 2021-09-09 15:28:10,040 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
freqtrade-3  | 2021-09-09 15:28:10,056 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 480
freqtrade-3  | 2021-09-09 15:28:10,068 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'buy': 10, 'sell': 30, 'unit': 'minutes'}
freqtrade-3  | 2021-09-09 15:28:10,081 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_sell_signal: True
freqtrade-3  | 2021-09-09 15:28:10,087 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_only: False
freqtrade-3  | 2021-09-09 15:28:10,100 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_buy_signal: True
freqtrade-3  | 2021-09-09 15:28:10,107 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_offset: 0.0
freqtrade-3  | 2021-09-09 15:28:10,116 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
freqtrade-3  | 2021-09-09 15:28:10,130 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
freqtrade-3  | 2021-09-09 15:28:10,138 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
freqtrade-3  | 2021-09-09 15:28:10,156 - freqtrade.exchange.exchange - INFO - Using CCXT 1.55.28
freqtrade-3  | 2021-09-09 15:28:10,165 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
freqtrade-3  | 2021-09-09 15:28:10,203 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 200}
freqtrade-3  | 2021-09-09 15:28:10,223 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
freqtrade-3  | 2021-09-09 15:28:11,436 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
freqtrade-3  | 2021-09-09 15:28:11,654 - freqtrade.exchange.common - WARNING - get_balances() returned exception: "Could not get balance due to AuthenticationError. Message: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}"
freqtrade-3  | 2021-09-09 15:28:11,659 - freqtrade.exchange.common - WARNING - retrying get_balances() still for 4 times
freqtrade-3  | 2021-09-09 15:28:12,167 - freqtrade.exchange.common - WARNING - get_balances() returned exception: "Could not get balance due to AuthenticationError. Message: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}"
freqtrade-3  | 2021-09-09 15:28:12,175 - freqtrade.exchange.common - WARNING - retrying get_balances() still for 3 times
freqtrade-3  | 2021-09-09 15:28:12,665 - freqtrade.exchange.common - WARNING - get_balances() returned exception: "Could not get balance due to AuthenticationError. Message: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}"
freqtrade-3  | 2021-09-09 15:28:12,670 - freqtrade.exchange.common - WARNING - retrying get_balances() still for 2 times
freqtrade-3  | 2021-09-09 15:28:13,172 - freqtrade.exchange.common - WARNING - get_balances() returned exception: "Could not get balance due to AuthenticationError. Message: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}"
freqtrade-3  | 2021-09-09 15:28:13,177 - freqtrade.exchange.common - WARNING - retrying get_balances() still for 1 times
freqtrade-3  | 2021-09-09 15:28:13,698 - freqtrade.exchange.common - WARNING - get_balances() returned exception: "Could not get balance due to AuthenticationError. Message: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}"
freqtrade-3  | 2021-09-09 15:28:13,702 - freqtrade.exchange.common - WARNING - Giving up retrying: get_balances()
freqtrade-3  | 2021-09-09 15:28:13,710 - freqtrade.commands.trade_commands - ERROR - Could not get balance due to AuthenticationError. Message: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}
freqtrade-3  | 2021-09-09 15:28:13,714 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
freqtrade-3  | Traceback (most recent call last):
freqtrade-3  |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 613, in fetch
freqtrade-3  |     response.raise_for_status()
freqtrade-3  |   File "/home/ftuser/.local/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
freqtrade-3  |     raise HTTPError(http_error_msg, response=self)
freqtrade-3  | requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.binance.com/api/v3/account?timestamp=.....
freqtrade-3  | 
freqtrade-3  | During handling of the above exception, another exception occurred:
freqtrade-3  | 
freqtrade-3  | Traceback (most recent call last):
freqtrade-3  |   File "/freqtrade/freqtrade/exchange/exchange.py", line 896, in get_balances
freqtrade-3  |     balances = self._api.fetch_balance()
freqtrade-3  |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/binance.py", line 1267, in fetch_balance
freqtrade-3  |     response = getattr(self, method)(query)
freqtrade-3  |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 457, in inner
freqtrade-3  |     return entry(_self, **inner_kwargs)
freqtrade-3  |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/binance.py", line 4154, in request
freqtrade-3  |     response = self.fetch2(path, api, method, params, headers, body, config, context)
freqtrade-3  |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 502, in fetch2
freqtrade-3  |     return self.fetch(request['url'], request['method'], request['headers'], request['body'])
freqtrade-3  |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 629, in fetch
freqtrade-3  |     self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
freqtrade-3  |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/binance.py", line 4134, in handle_errors
freqtrade-3  |     self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
freqtrade-3  |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 520, in throw_exactly_matched_exception
freqtrade-3  |     raise exact[string](message)
freqtrade-3  | ccxt.base.errors.AuthenticationError: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}
freqtrade-3  | 
freqtrade-3  | The above exception was the direct cause of the following exception:
freqtrade-3  | 
freqtrade-3  | Traceback (most recent call last):
freqtrade-3  |   File "/freqtrade/freqtrade/exchange/common.py", line 89, in wrapper
freqtrade-3  |     return f(*args, **kwargs)
freqtrade-3  |   File "/freqtrade/freqtrade/exchange/exchange.py", line 907, in get_balances
freqtrade-3  |     raise TemporaryError(
freqtrade-3  | freqtrade.exceptions.TemporaryError: Could not get balance due to AuthenticationError. Message: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}
freqtrade-3  | 
freqtrade-3  | During handling of the above exception, another exception occurred:
freqtrade-3  | 
freqtrade-3  | Traceback (most recent call last):
freqtrade-3  |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 613, in fetch
freqtrade-3  |     response.raise_for_status()
freqtrade-3  |   File "/home/ftuser/.local/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
freqtrade-3  |     raise HTTPError(http_error_msg, response=self)
freqtrade-3  | requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.binance.com/api/v3/account?timestamp=.....
freqtrade-3  | 
freqtrade-3  | During handling of the above exception, another exception occurred:
freqtrade-3  | 
freqtrade-3  | Traceback (most recent call last):
freqtrade-3  |   File "/freqtrade/freqtrade/exchange/exchange.py", line 896, in get_balances
freqtrade-3  |     balances = self._api.fetch_balance()
freqtrade-3  |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/binance.py", line 1267, in fetch_balance
freqtrade-3  |     response = getattr(self, method)(query)
freqtrade-3  |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 457, in inner
freqtrade-3  |     return entry(_self, **inner_kwargs)
freqtrade-3  |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/binance.py", line 4154, in request
freqtrade-3  |     response = self.fetch2(path, api, method, params, headers, body, config, context)
freqtrade-3  |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 502, in fetch2
freqtrade-3  |     return self.fetch(request['url'], request['method'], request['headers'], request['body'])
freqtrade-3  |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 629, in fetch
freqtrade-3  |     self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
freqtrade-3  |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/binance.py", line 4134, in handle_errors
freqtrade-3  |     self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
freqtrade-3  |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 520, in throw_exactly_matched_exception
freqtrade-3  |     raise exact[string](message)
freqtrade-3  | ccxt.base.errors.AuthenticationError: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}
freqtrade-3  | 
freqtrade-3  | The above exception was the direct cause of the following exception:
freqtrade-3  | 
freqtrade-3  | Traceback (most recent call last):
freqtrade-3  |   File "/freqtrade/freqtrade/exchange/common.py", line 89, in wrapper
freqtrade-3  |     return f(*args, **kwargs)
freqtrade-3  |   File "/freqtrade/freqtrade/exchange/exchange.py", line 907, in get_balances
freqtrade-3  |     raise TemporaryError(
freqtrade-3  | freqtrade.exceptions.TemporaryError: Could not get balance due to AuthenticationError. Message: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}
freqtrade-3  | 
freqtrade-3  | During handling of the above exception, another exception occurred:
freqtrade-3  | 
freqtrade-3  | Traceback (most recent call last):
freqtrade-3  |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 613, in fetch
freqtrade-3  |     response.raise_for_status()
freqtrade-3  |   File "/home/ftuser/.local/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
freqtrade-3  |     raise HTTPError(http_error_msg, response=self)
freqtrade-3  | requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.binance.com/api/v3/account?timestamp=.....
freqtrade-3  | 
freqtrade-3  | During handling of the above exception, another exception occurred:
freqtrade-3  | 
freqtrade-3  | Traceback (most recent call last):
freqtrade-3  |   File "/freqtrade/freqtrade/exchange/exchange.py", line 896, in get_balances
freqtrade-3  |     balances = self._api.fetch_balance()
freqtrade-3  |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/binance.py", line 1267, in fetch_balance
freqtrade-3  |     response = getattr(self, method)(query)
freqtrade-3  |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 457, in inner
freqtrade-3  |     return entry(_self, **inner_kwargs)
freqtrade-3  |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/binance.py", line 4154, in request
freqtrade-3  |     response = self.fetch2(path, api, method, params, headers, body, config, context)
freqtrade-3  |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 502, in fetch2
freqtrade-3  |     return self.fetch(request['url'], request['method'], request['headers'], request['body'])
freqtrade-3  |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 629, in fetch
freqtrade-3  |     self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
freqtrade-3  |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/binance.py", line 4134, in handle_errors
freqtrade-3  |     self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
freqtrade-3  |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 520, in throw_exactly_matched_exception
freqtrade-3  |     raise exact[string](message)
freqtrade-3  | ccxt.base.errors.AuthenticationError: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}
freqtrade-3  | 
freqtrade-3  | The above exception was the direct cause of the following exception:
freqtrade-3  | 
freqtrade-3  | Traceback (most recent call last):
freqtrade-3  |   File "/freqtrade/freqtrade/exchange/common.py", line 89, in wrapper
freqtrade-3  |     return f(*args, **kwargs)
freqtrade-3  |   File "/freqtrade/freqtrade/exchange/exchange.py", line 907, in get_balances
freqtrade-3  |     raise TemporaryError(
freqtrade-3  | freqtrade.exceptions.TemporaryError: Could not get balance due to AuthenticationError. Message: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}
freqtrade-3  | 
freqtrade-3  | During handling of the above exception, another exception occurred:
freqtrade-3  | 
freqtrade-3  | Traceback (most recent call last):
freqtrade-3  |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 613, in fetch
freqtrade-3  |     response.raise_for_status()
freqtrade-3  |   File "/home/ftuser/.local/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
freqtrade-3  |     raise HTTPError(http_error_msg, response=self)
freqtrade-3  | requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.binance.com/api/v3/account?https://api.binance.com/api/v3/account?timestamp=.....
freqtrade-3  | 
freqtrade-3  | During handling of the above exception, another exception occurred:
freqtrade-3  | 
freqtrade-3  | Traceback (most recent call last):
freqtrade-3  |   File "/freqtrade/freqtrade/exchange/exchange.py", line 896, in get_balances
freqtrade-3  |     balances = self._api.fetch_balance()
freqtrade-3  |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/binance.py", line 1267, in fetch_balance
freqtrade-3  |     response = getattr(self, method)(query)
freqtrade-3  |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 457, in inner
freqtrade-3  |     return entry(_self, **inner_kwargs)
freqtrade-3  |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/binance.py", line 4154, in request
freqtrade-3  |     response = self.fetch2(path, api, method, params, headers, body, config, context)
freqtrade-3  |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 502, in fetch2
freqtrade-3  |     return self.fetch(request['url'], request['method'], request['headers'], request['body'])
freqtrade-3  |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 629, in fetch
freqtrade-3  |     self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
freqtrade-3  |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/binance.py", line 4134, in handle_errors
freqtrade-3  |     self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
freqtrade-3  |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 520, in throw_exactly_matched_exception
freqtrade-3  |     raise exact[string](message)
freqtrade-3  | ccxt.base.errors.AuthenticationError: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}
freqtrade-3  | 
freqtrade-3  | The above exception was the direct cause of the following exception:
freqtrade-3  | 
freqtrade-3  | Traceback (most recent call last):
freqtrade-3  |   File "/freqtrade/freqtrade/exchange/common.py", line 89, in wrapper
freqtrade-3  |     return f(*args, **kwargs)
freqtrade-3  |   File "/freqtrade/freqtrade/exchange/exchange.py", line 907, in get_balances
freqtrade-3  |     raise TemporaryError(
freqtrade-3  | freqtrade.exceptions.TemporaryError: Could not get balance due to AuthenticationError. Message: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}
freqtrade-3  | 
freqtrade-3  | During handling of the above exception, another exception occurred:
freqtrade-3  | 
freqtrade-3  | Traceback (most recent call last):
freqtrade-3  |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 613, in fetch
freqtrade-3  |     response.raise_for_status()
freqtrade-3  |   File "/home/ftuser/.local/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
freqtrade-3  |     raise HTTPError(http_error_msg, response=self)
freqtrade-3  | requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.binance.com/api/v3/account?timestamp=1631201293540&recvWindow=5000&signature=85050d81f7a84c1e5af075cab07f76bcad7811e48db820524d1e92c7dd8b7cdd
freqtrade-3  | 
freqtrade-3  | During handling of the above exception, another exception occurred:
freqtrade-3  | 
freqtrade-3  | Traceback (most recent call last):
freqtrade-3  |   File "/freqtrade/freqtrade/exchange/exchange.py", line 896, in get_balances
freqtrade-3  |     balances = self._api.fetch_balance()
freqtrade-3  |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/binance.py", line 1267, in fetch_balance
freqtrade-3  |     response = getattr(self, method)(query)
freqtrade-3  |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 457, in inner
freqtrade-3  |     return entry(_self, **inner_kwargs)
freqtrade-3  |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/binance.py", line 4154, in request
freqtrade-3  |     response = self.fetch2(path, api, method, params, headers, body, config, context)
freqtrade-3  |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 502, in fetch2
freqtrade-3  |     return self.fetch(request['url'], request['method'], request['headers'], request['body'])
freqtrade-3  |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 629, in fetch
freqtrade-3  |     self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
freqtrade-3  |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/binance.py", line 4134, in handle_errors
freqtrade-3  |     self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
freqtrade-3  |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 520, in throw_exactly_matched_exception
freqtrade-3  |     raise exact[string](message)
freqtrade-3  | ccxt.base.errors.AuthenticationError: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}
freqtrade-3  | 
freqtrade-3  | The above exception was the direct cause of the following exception:
freqtrade-3  | 
freqtrade-3  | Traceback (most recent call last):
freqtrade-3  |   File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
freqtrade-3  |     worker = Worker(args)
freqtrade-3  |   File "/freqtrade/freqtrade/worker.py", line 35, in __init__
freqtrade-3  |     self._init(False)
freqtrade-3  |   File "/freqtrade/freqtrade/worker.py", line 52, in _init
freqtrade-3  |     self.freqtrade = FreqtradeBot(self._config)
freqtrade-3  |   File "/freqtrade/freqtrade/freqtradebot.py", line 69, in __init__
freqtrade-3  |     self.wallets = Wallets(self.config, self.exchange)
freqtrade-3  |   File "/freqtrade/freqtrade/wallets.py", line 37, in __init__
freqtrade-3  |     self.update()
freqtrade-3  |   File "/freqtrade/freqtrade/wallets.py", line 122, in update
freqtrade-3  |     self._update_live()
freqtrade-3  |   File "/freqtrade/freqtrade/wallets.py", line 97, in _update_live
freqtrade-3  |     balances = self._exchange.get_balances()
freqtrade-3  |   File "/freqtrade/freqtrade/exchange/common.py", line 101, in wrapper
freqtrade-3  |     return wrapper(*args, **kwargs)
freqtrade-3  |   File "/freqtrade/freqtrade/exchange/common.py", line 101, in wrapper
freqtrade-3  |     return wrapper(*args, **kwargs)
freqtrade-3  |   File "/freqtrade/freqtrade/exchange/common.py", line 101, in wrapper
freqtrade-3  |     return wrapper(*args, **kwargs)
freqtrade-3  |   [Previous line repeated 1 more time]
freqtrade-3  |   File "/freqtrade/freqtrade/exchange/common.py", line 104, in wrapper
freqtrade-3  |     raise ex
freqtrade-3  |   File "/freqtrade/freqtrade/exchange/common.py", line 89, in wrapper
freqtrade-3  |     return f(*args, **kwargs)
freqtrade-3  |   File "/freqtrade/freqtrade/exchange/exchange.py", line 907, in get_balances
freqtrade-3  |     raise TemporaryError(
freqtrade-3  | freqtrade.exceptions.TemporaryError: Could not get balance due to AuthenticationError. Message: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}

**Comment by martygriffin** [comment]
It seems that not matter what I change the exchange name to, it is defaulting to normal Binance, even an invalid names

**Comment by martygriffin** [comment]
I found the issue, I was setting the exchange name later on in a different file in correctly.
