### ISSUE TITLE
ZeroDivisionError: division by zero - 0 starting balance

### ISSUE THREAD

**Issue by martygriffin** [freqtrade/freqtrade#5558]
Describe your environment
Operating system: Docker (freqtrade:stable)
Python Version: 3.9
CCXT version: 1.55.28
Freqtrade Version: 2021.8
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

Describe the problem:
When I load a page on frequi I get this error in the logs. It seems it is related to my starting balance is set 0.

Steps to reproduce:
Configure to use Binance US
Start Up bot
Load FreqUI
Load a page
Observe logs
Observed Results:
What happened?
Divison by zero error shown ing logs
What did you expect to happen?
No error to show in log

Relevant code exceptions or logs
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/ftuser/.local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/ftuser/.local/lib/python3.9/site-packages/uvicorn/middleware/message_logger.py", line 82, in __call__
    raise exc from None
  File "/home/ftuser/.local/lib/python3.9/site-packages/uvicorn/middleware/message_logger.py", line 78, in __call__
    await self.app(scope, inner_receive, inner_send)
  File "/home/ftuser/.local/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 78, in __call__
    await self.app(scope, receive, send)
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/home/ftuser/.local/lib/python3.9/site-packages/fastapi/routing.py", line 219, in app
    raw_response = await run_endpoint_function(
  File "/home/ftuser/.local/lib/python3.9/site-packages/fastapi/routing.py", line 154, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/freqtrade/freqtrade/rpc/api_server/api_v1.py", line 64, in profit
    return rpc._rpc_trade_statistics(config['stake_currency'],
  File "/freqtrade/freqtrade/rpc/rpc.py", line 406, in _rpc_trade_statistics
    profit_closed_ratio_fromstart = profit_closed_coin_sum / starting_balance
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/ftuser/.local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/ftuser/.local/lib/python3.9/site-packages/uvicorn/middleware/message_logger.py", line 82, in __call__
    raise exc from None
  File "/home/ftuser/.local/lib/python3.9/site-packages/uvicorn/middleware/message_logger.py", line 78, in __call__
    await self.app(scope, inner_receive, inner_send)
  File "/home/ftuser/.local/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 78, in __call__
    await self.app(scope, receive, send)
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/home/ftuser/.local/lib/python3.9/site-packages/fastapi/routing.py", line 219, in app
    raw_response = await run_endpoint_function(
  File "/home/ftuser/.local/lib/python3.9/site-packages/fastapi/routing.py", line 154, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/freqtrade/freqtrade/rpc/api_server/api_v1.py", line 64, in profit
    return rpc._rpc_trade_statistics(config['stake_currency'],
  File "/freqtrade/freqtrade/rpc/rpc.py", line 406, in _rpc_trade_statistics
    profit_closed_ratio_fromstart = profit_closed_coin_sum / starting_balance
ZeroDivisionError: division by zero

**Comment by xmatthias** [comment]
This particular problem was fixed this week in develop.

Its however a configuration mistake in my opinion.

why would you want to set a starting balance of 0, which will leave the bot unable to do anything as its gotnno capital available?

**Comment by martygriffin** [comment]
I will try the develop image. I do not have the starting balance set in my config anywhere. I do see it correctly pulling the correct balance from binance elsewhere. Is there a way to explicitly set the start amount?

**Comment by xmatthias** [comment]
it depends on the mode you're running - if it's dry-, then `dry_run_wallet` can be set (it also defaults to 1000).

in live, it will detect the balance from the exchange correctly - assuming exchange-keys have been provided correctly.

**Comment by martygriffin** [comment]
The bot was working fine in dry run mode. I updated my config to live Binance US, and it pulls some data correctly such as my crypto balances. There are no other error in the logs.

Here is my config file with the keys blanked out:

{
  "max_open_trades": 4,
  "stake_currency": "USDT",
  "stake_amount": "unlimited",
  "tradable_balance_ratio": 0.99,
  "fiat_display_currency": "USD",
  "timeframe": "5m",
  "dry_run": false,
  "dry_run_wallet": 1000,
  "unfilledtimeout": {
    "buy": 10,
    "sell": 30,
    "unit": "minutes"
},
  "cancel_open_orders_on_exit": false,
  "bid_strategy": {
      "price_side": "ask",
      "ask_last_balance": 0.0,
      "use_order_book": false,
      "order_book_top": 1,
      "check_depth_of_market": {
          "enabled": false,
          "bids_to_ask_delta": 1
      }
  },
  "ask_strategy": {
      "price_side": "bid",
      "use_order_book": false,
      "order_book_min": 1,
      "order_book_max": 1
  },
  "exchange": {
    "name": "binanceus",
    "key": "*",
    "secret": "*",
    "ccxt_config": {"enableRateLimit": true},
    "ccxt_async_config": {
        "enableRateLimit": true,
        "rateLimit": 200
    },
      "pair_whitelist":[
    ]
  },
  "pairlists": [
      {"method": "StaticPairList"}
  ],
  "dataformat_ohlcv": "jsongz",
  "dataformat_trades": "jsongz",
  "edge": {
    "enabled": false,
    "process_throttle_secs": 3600,
    "calculate_since_number_of_days": 7,
    "allowed_risk": 0.01,
    "stoploss_range_min": -0.01,
    "stoploss_range_max": -0.1,
    "stoploss_range_step": -0.01,
    "minimum_winrate": 0.60,
    "minimum_expectancy": 0.20,
    "min_trade_number": 10,
    "max_trade_duration_minute": 1440,
    "remove_pumps": false
},
"telegram": {
    "enabled": false,
    "token": "",
    "chat_id": ""
},
"api_server": {
    "enabled": true,
    "listen_ip_address": "0.0.0.0",
    "listen_port": 8081,
    "verbosity": "error",
    "enable_openapi": false,
    "jwt_secret_key": "***********",
    "CORS_origins": ["http://127.0.0.1:8080", "http://localhost:8080"],
    "username": "****",
    "password": "****"
},
"bot_name": "freqtrade",
"initial_state": "running",
"forcebuy_enable": false,
"internals": {
    "process_throttle_secs": 5
}
}


I tried the develop docker image and am still getting the same error. Is there a way I can manually set the starting balance in the DB?

**Comment by xmatthias** [comment]
then you might not have the latest develop - but the exception you showed above was fixed in 6bd495a32a58b6da236f53da2d166f683a21cfff.

As your stake-currency is USDT - do you actually have USDT on the exchange? 
that's the premise for freqtrade to work - otherwise you'll have no money (freqtrade will not touch existing positions that are not in stake_currency).

**Comment by martygriffin** [comment]
I rebuilt my container again and it's all working now. It must mot have pulled the latest image for some reason. This can be closed.
