### ISSUE TITLE
Clean install with script for ubuntu 20.4 unable to download any data from binance keep on error

### ISSUE THREAD

**Issue by Renaenys** [freqtrade/freqtrade#5600]
```
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/exchangeInfo (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f944dfa9e80>, 'Connection to api.binance.com timed out. (connect timeout=10)'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/freqtrade-2021.8/freqtrade/exchange/exchange.py", line 330, in _load_markets
    self._markets = self._api.load_markets()
  File "/home/ubuntu/freqtrade-2021.8/.env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1383, in load_markets
    markets = self.fetch_markets(params)
  File "/home/ubuntu/freqtrade-2021.8/.env/lib/python3.8/site-packages/ccxt/binance.py", line 987, in fetch_markets
    response = getattr(self, method)(query)
  File "/home/ubuntu/freqtrade-2021.8/.env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 457, in inner
    return entry(_self, **inner_kwargs)
  File "/home/ubuntu/freqtrade-2021.8/.env/lib/python3.8/site-packages/ccxt/binance.py", line 4154, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/ubuntu/freqtrade-2021.8/.env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 502, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ubuntu/freqtrade-2021.8/.env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 617, in fetch
    raise RequestTimeout(details) from e
ccxt.base.errors.RequestTimeout: binance GET https://api.binance.com/api/v3/exchangeInfo
2021-09-21 09:57:34,572 - freqtrade - ERROR - Cannot get markets. Reason: Markets were not loaded.

```

this error I get

i have spin up a new VM for this stable version and i cant get the download.

config.json already setup properly with finance key

**Comment by mablue** [comment]
where you live maybe need to vpn.

**Comment by xmatthias** [comment]
The error sounds is a simple connection problem to binance.

As mentioned above (but it's where the VM is, not necessarly where you live), maybe your server is in a country that's blocked by binance

**Comment by Renaenys** [comment]
i have change my VPN and still presist the connection. Strange.
My Old freqtrade from another machine works fine
![image](https://user-images.githubusercontent.com/37536675/134260507-d1852c0b-542e-4762-afbc-b2df9d7e177b.png)

**Comment by mablue** [comment]
Run this and send the log
ping -c 5 api.binance.com

**Comment by Renaenys** [comment]
ok i reformate the whole VM and setup an VPN seems work again. !

**Comment by mablue** [comment]
> ok i reformate the whole VM and setup an VPN seems work again. !

Yes vpns are very Deceptive play pingpong with them before doing anything
