### ISSUE TITLE
Binance API key incompatibility?

### ISSUE THREAD

**Issue by peacefulbadger** [freqtrade/freqtrade#5606]
## Describe your environment

  * Operating system: W10
  * Python Version: 3.8.5 conda
  * CCXT version: 1.53.30
  * Freqtrade Version: freqtrade docker-9c50d0c2 (Docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

Bot failed in the middle of a 1 week run. After attempting to start again, error 2014 is returned. Thinking that my API key may be expired, I generated a new one with spot permissions and modified config. Attempting to run newly configured bot config with the same strategy results in the same error. Just to test if the API key works, I threw together a quick webhook endpoint to test the API key. The bot successfully executed when testing the endpoint. Issue persists even after pulling a fresh image and building it. 

### Steps to reproduce:

  1. Generate new Binance.com API key with spot permissions
  2. modify config with new key and secret
  3. docker-compose up -d
  4. docker-compose run --rm freqtrade trade --strategy SampleStrategy
  
### Observed Results:

  * Error: {"code":-2014,"msg":"API-key format invalid."} 

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
2021-09-22 00:48:03,174 - freqtrade.exchange.exchange - INFO - Using CCXT 1.56.30
2021-09-22 00:48:03,175 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2021-09-22 00:48:03,184 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 200}
2021-09-22 00:48:03,194 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2021-09-22 00:48:03,440 - freqtrade.exchange.exchange - ERROR - Unable to initialize markets.
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 613, in fetch
    response.raise_for_status()
  File "/home/ftuser/.local/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error:  for url: https://api.binance.com/sapi/v1/capital/config/getall?timestamp=1632271683194&recvWindow=5000&signature=382604069cfb135630fd765a3d1ac6fbb1432964ee3259243eb24be29575d8b3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/exchange.py", line 339, in _load_markets
    self._markets = self._api.load_markets()
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 1411, in load_markets
    currencies = self.fetch_currencies()
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/binance.py", line 862, in fetch_currencies
    response = self.sapiGetCapitalConfigGetall(params)
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 457, in inner
    return entry(_self, **inner_kwargs)
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/binance.py", line 4159, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 502, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 629, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/binance.py", line 4139, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 520, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.InvalidNonce: binance {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
2021-09-22 00:48:03,441 - freqtrade.commands.trade_commands - ERROR - Could not load markets, therefore cannot start. Please investigate the above error for more details.
2021-09-22 00:48:03,441 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/freqtrade/freqtrade/worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/freqtrade/freqtrade/freqtradebot.py", line 65, in __init__
    self.exchange = ExchangeResolver.load_exchange(self.config['exchange']['name'], self.config)
  File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 32, in load_exchange
    exchange = ExchangeResolver._load_exchange(exchange_name,
  File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 54, in _load_exchange
    exchange = ex_class(**kwargs)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 153, in __init__
    self.validate_stakecurrency(config['stake_currency'])
  File "/freqtrade/freqtrade/exchange/exchange.py", line 370, in validate_stakecurrency
    raise OperationalException(
freqtrade.exceptions.OperationalException: Could not load markets, therefore cannot start. Please investigate the above error for more details.
  ```

**Comment by xmatthias** [comment]
It's interresting that the log does not contain the error you mention(`{"code":-2014,"msg":"API-key format invalid."}`), but `{"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}` instead - which means the time on your system is wrong (most likely it's not 100% in sync) - for which the solution is usually to setup a time-sync daemon to make sure the time is kept uptodate (at least when running on linux).

It'd also mean that it's not related to your keys whatsoever, but solely on the time.


As you're using docker on windows - there'll however not be an easy solution, as docker for windows is good at losing time sync (there's about 3 open issues on that distributed across docker/wsl repositories). 
Just yesterday, we've added a warning to the documentation to not run the bot productively (trade mode) with docker for windows [here](https://www.freqtrade.io/en/latest/docker_quickstart/#troubleshooting).


The first message (2014) would appear if the key format is invalid, which can happen
* if the key/secret was swapped
* if there are spaces / extra characters before/after the key

**Comment by peacefulbadger** [comment]
The 2014 error is reported in the first log stanza (https://api.binance.com/sapi/v1/capital/config/getall?timestamp=1632271683194&recvWindow=5000&signature=382604069cfb135630fd765a3d1ac6fbb1432964ee3259243eb24be29575d8b3). I should note that the issue is resolved if I run in dry-run. 

I'm guessing it's an issue with NTP not cooperating with wsl. Nobody has reported it on a native linux OS? Worth a shot on an Rasp I have lying around.

**Comment by xmatthias** [comment]
well it can happen on linux as well if you don't setup ntpd (or chronyd) ... 

Docker for windows spins up it's own (hidden) linux machine, where you cannot setup a ntpd daemon (but it loses sync to the "real" windows time) ... so the only solution is to kill docker for desktop, stop the virtual machine to get it to sync again (which is obviously a pain).

You can also use native WSL2 on windows - where it IS possible to setup ntpd to keep the time in sync.

On dry-run it won't matter as exchange-keys are removed, and the "recvWindow" is part of the authentication if i remember corectly - so it's not checked on dry-run.

**Comment by dentmo** [comment]
Hello

**Comment by arukh281** [comment]
Hii, 
I know a bit of python, but I wanna contribute, 
Can anyone guide me.??

**Comment by xmatthias** [comment]
> I know a bit of python, but I wanna contribute,
> Can anyone guide me.??

Best look at issues labeled "good first issue".
These will usually only touch a certain "corner" of the bot (only a small number of files) without requiring broad knowledge about the bot structure.

An alternative is to start reading and understanding how the different bot-elements tie together - which (as you know python) is best done by simply reading the sourcecode.

I'd also appreciate if you could not high-jack other people's issues with questions totally unrelated to the issue that was raised - thanks.

**Comment by peacefulbadger** [comment]
So the issue does seem to have been resolved in ubuntu 20.04 for now. No issues running after 48 hours.

**Comment by peacefulbadger** [comment]
Reopening because I think I'm getting clock sync issues on Ubuntu as well now. Every 24 hours or so I am finding that certain candles are missing or outdated. Sometimes `docker-compose down' and `docker-compose up -d` solves the issue but lately it has not. When I try to navigate to any of the missing data pairs in frequi, the charts cannot be drawn but the price still updates periodically. Is the bot still calculating entries/exits while this is the case or has everything broken down due to the missing data? 

```
2021-10-08 15:56:39,005 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair HOT/USDT: input_arrays parameter missing required data key: ema1
2021-10-08 15:56:39,010 - freqtrade.strategy.interface - WARNING - Outdated history for pair SHIB/USDT. Last tick is 16 minutes old
2021-10-08 15:56:39,013 - freqtrade.strategy.interface - WARNING - Outdated history for pair BTC/USDT. Last tick is 16 minutes old
2021-10-08 15:56:39,016 - freqtrade.strategy.interface - WARNING - Outdated history for pair ETH/USDT. Last tick is 16 minutes old
2021-10-08 15:56:39,019 - freqtrade.strategy.interface - WARNING - Outdated history for pair FTM/USDT. Last tick is 16 minutes old
2021-10-08 15:56:39,021 - freqtrade.strategy.interface - WARNING - Outdated history for pair BUSD/USDT. Last tick is 16 minutes old
2021-10-08 15:56:39,023 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair BETA/USDT
2021-10-08 15:56:39,024 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair SOL/USDT
2021-10-08 15:56:39,026 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair DOT/USDT
2021-10-08 15:56:39,028 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair BTCST/USDT
```

**Comment by xmatthias** [comment]
When you get ` Outdated history for pair ETH/USDT. Last tick is 16 minutes old`, then freqtrade will not do anything until a fresh candle arrives (otherwise it may buy/sell on old data - which is not what you want.

It's very well possible and likely that this happens due to time sync issues, but with docker on wsl, there's no real good solution at the moment.
In general, i'd not recommend to run the bot for longer periods of time in this configuration. It's good for downloading data / backtesting / hyperopt - but not for trade mode.

Best get a cheap VPS - they range from 0 to 10$ /month - and will fix these problems for you.

**Comment by peacefulbadger** [comment]
To clarify, I am on native Ubuntu deployed on A1 Oracle Cloud. I don't think a VPS would help in this case. 

I think fresh candles are coming in as I can see the current rate updating in real time. Frequi will not show the chart however (I'm assuming because it has incomplete candles?). The question is whether the strategy is actually calculating in the background.

**Comment by xmatthias** [comment]
> To clarify, I am on native Ubuntu deployed on A1 Oracle Cloud

your original setup was Windows with Docker - and since it's been posted in the same issue - i start with the assumption that nothing changed.
the A1 Oracle cloud IS a VPS - so you're doing that already.
You can still check if time-sync (either ntpd or chronyd) is enabled and working correctly.

current rate will work for roi / stoploss - but candles are used to calculate buy/sell signals, which are, as stated above, not calculated until candles with correct / uptodate dates are available.

**Comment by peacefulbadger** [comment]
> your original setup was Windows with Docker - and since it's been posted in the same issue - i start with the assumption that nothing changed. the A1 Oracle cloud IS a VPS - so you're doing that already. You can still check if time-sync (either ntpd or chronyd) is enabled and working correctly.

Going to try swapping out ntpd for chronyd and will try again.

**Comment by xmatthias** [comment]
They both do the same task if configured correctly ... so simple "swapping out" one for the other might not help much ...

**Comment by mert-donmez** [comment]
I get same error 
```
2022-03-01 03:46:12,264 - freqtrade.exchange.exchange - INFO - Using CCXT 1.74.17
2022-03-01 03:46:12,265 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2022-03-01 03:46:12,274 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 200}
2022-03-01 03:46:12,282 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2022-03-01 03:46:21,457 - freqtrade.exchange.exchange - ERROR - Unable to initialize markets.
Traceback (most recent call last):
  File "/home/root_ubuntu/Desktop/spot/freqtrade/.env/lib/python3.9/site-packages/ccxt/base/exchange.py", line 661, in fetch
    response.raise_for_status()
  File "/home/root_ubuntu/Desktop/spot/freqtrade/.env/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error:  for url: https://api.binance.com/sapi/v1/capital/config/getall?timestamp=1646095572282&recvWindow=5000&signature=0990218fcfc751fb96210ec257a24909d737c2266e37615f33a3cba08b93d8e1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/root_ubuntu/Desktop/spot/freqtrade/freqtrade/exchange/exchange.py", line 345, in _load_markets
    self._markets = self._api.load_markets()
  File "/home/root_ubuntu/Desktop/spot/freqtrade/.env/lib/python3.9/site-packages/ccxt/base/exchange.py", line 1517, in load_markets
    currencies = self.fetch_currencies()
  File "/home/root_ubuntu/Desktop/spot/freqtrade/.env/lib/python3.9/site-packages/ccxt/binance.py", line 1239, in fetch_currencies
    response = self.sapiGetCapitalConfigGetall(params)
  File "/home/root_ubuntu/Desktop/spot/freqtrade/.env/lib/python3.9/site-packages/ccxt/base/exchange.py", line 503, in inner
    return entry(_self, **inner_kwargs)
  File "/home/root_ubuntu/Desktop/spot/freqtrade/.env/lib/python3.9/site-packages/ccxt/binance.py", line 4969, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/root_ubuntu/Desktop/spot/freqtrade/.env/lib/python3.9/site-packages/ccxt/base/exchange.py", line 550, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/root_ubuntu/Desktop/spot/freqtrade/.env/lib/python3.9/site-packages/ccxt/base/exchange.py", line 677, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/root_ubuntu/Desktop/spot/freqtrade/.env/lib/python3.9/site-packages/ccxt/binance.py", line 4947, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
  File "/home/root_ubuntu/Desktop/spot/freqtrade/.env/lib/python3.9/site-packages/ccxt/base/exchange.py", line 568, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.InvalidNonce: binance {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
2022-03-01 03:46:21,468 - freqtrade.commands.trade_commands - ERROR - Could not load markets, therefore cannot start. Please investigate the above error for more details.
2022-03-01 03:46:21,468 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/root_ubuntu/Desktop/spot/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/home/root_ubuntu/Desktop/spot/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/home/root_ubuntu/Desktop/spot/freqtrade/freqtrade/worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/home/root_ubuntu/Desktop/spot/freqtrade/freqtrade/freqtradebot.py", line 63, in __init__
    self.exchange = ExchangeResolver.load_exchange(self.config['exchange']['name'], self.config)
  File "/home/root_ubuntu/Desktop/spot/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 32, in load_exchange
    exchange = ExchangeResolver._load_exchange(exchange_name,
  File "/home/root_ubuntu/Desktop/spot/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 54, in _load_exchange
    exchange = ex_class(**kwargs)
  File "/home/root_ubuntu/Desktop/spot/freqtrade/freqtrade/exchange/exchange.py", line 157, in __init__
    self.validate_stakecurrency(config['stake_currency'])
  File "/home/root_ubuntu/Desktop/spot/freqtrade/freqtrade/exchange/exchange.py", line 376, in validate_stakecurrency
    raise OperationalException(
freqtrade.exceptions.OperationalException: Could not load markets, therefore cannot start. Please investigate the above error for more details.
```
I read the above answers but I couldn't figure it out. As far as i can i set the time sync : 
```
timedatectl status
               Local time: Sal 2022-03-01 03:51:54 +03 
           Universal time: Sal 2022-03-01 00:51:54 UTC 
                 RTC time: Sal 2022-03-01 00:51:54     
                Time zone: Europe/Istanbul (+03, +0300)
System clock synchronized: yes                         
              NTP service: active                      
          RTC in local TZ: no
```

**Comment by mert-donmez** [comment]
> They both do the same task if configured correctly ... so simple "swapping out" one for the other might not help much ...

I get same error

```
2022-03-01 03:46:12,264 - freqtrade.exchange.exchange - INFO - Using CCXT 1.74.17
2022-03-01 03:46:12,265 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2022-03-01 03:46:12,274 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 200}
2022-03-01 03:46:12,282 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2022-03-01 03:46:21,457 - freqtrade.exchange.exchange - ERROR - Unable to initialize markets.
Traceback (most recent call last):
  File "/home/root_ubuntu/Desktop/spot/freqtrade/.env/lib/python3.9/site-packages/ccxt/base/exchange.py", line 661, in fetch
    response.raise_for_status()
  File "/home/root_ubuntu/Desktop/spot/freqtrade/.env/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error:  for url: https://api.binance.com/sapi/v1/capital/config/getall?timestamp=1646095572282&recvWindow=5000&signature=0990218fcfc751fb96210ec257a24909d737c2266e37615f33a3cba08b93d8e1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/root_ubuntu/Desktop/spot/freqtrade/freqtrade/exchange/exchange.py", line 345, in _load_markets
    self._markets = self._api.load_markets()
  File "/home/root_ubuntu/Desktop/spot/freqtrade/.env/lib/python3.9/site-packages/ccxt/base/exchange.py", line 1517, in load_markets
    currencies = self.fetch_currencies()
  File "/home/root_ubuntu/Desktop/spot/freqtrade/.env/lib/python3.9/site-packages/ccxt/binance.py", line 1239, in fetch_currencies
    response = self.sapiGetCapitalConfigGetall(params)
  File "/home/root_ubuntu/Desktop/spot/freqtrade/.env/lib/python3.9/site-packages/ccxt/base/exchange.py", line 503, in inner
    return entry(_self, **inner_kwargs)
  File "/home/root_ubuntu/Desktop/spot/freqtrade/.env/lib/python3.9/site-packages/ccxt/binance.py", line 4969, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/root_ubuntu/Desktop/spot/freqtrade/.env/lib/python3.9/site-packages/ccxt/base/exchange.py", line 550, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/root_ubuntu/Desktop/spot/freqtrade/.env/lib/python3.9/site-packages/ccxt/base/exchange.py", line 677, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/root_ubuntu/Desktop/spot/freqtrade/.env/lib/python3.9/site-packages/ccxt/binance.py", line 4947, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
  File "/home/root_ubuntu/Desktop/spot/freqtrade/.env/lib/python3.9/site-packages/ccxt/base/exchange.py", line 568, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.InvalidNonce: binance {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
2022-03-01 03:46:21,468 - freqtrade.commands.trade_commands - ERROR - Could not load markets, therefore cannot start. Please investigate the above error for more details.
2022-03-01 03:46:21,468 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/root_ubuntu/Desktop/spot/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/home/root_ubuntu/Desktop/spot/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/home/root_ubuntu/Desktop/spot/freqtrade/freqtrade/worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/home/root_ubuntu/Desktop/spot/freqtrade/freqtrade/freqtradebot.py", line 63, in __init__
    self.exchange = ExchangeResolver.load_exchange(self.config['exchange']['name'], self.config)
  File "/home/root_ubuntu/Desktop/spot/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 32, in load_exchange
    exchange = ExchangeResolver._load_exchange(exchange_name,
  File "/home/root_ubuntu/Desktop/spot/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 54, in _load_exchange
    exchange = ex_class(**kwargs)
  File "/home/root_ubuntu/Desktop/spot/freqtrade/freqtrade/exchange/exchange.py", line 157, in __init__
    self.validate_stakecurrency(config['stake_currency'])
  File "/home/root_ubuntu/Desktop/spot/freqtrade/freqtrade/exchange/exchange.py", line 376, in validate_stakecurrency
    raise OperationalException(
freqtrade.exceptions.OperationalException: Could not load markets, therefore cannot start. Please investigate the above error for more details.
```
I read the above answers but I couldn't figure it out. As far as i can i set the time sync :

```
timedatectl status
               Local time: Sal 2022-03-01 03:51:54 +03 
           Universal time: Sal 2022-03-01 00:51:54 UTC 
                 RTC time: Sal 2022-03-01 00:51:54     
                Time zone: Europe/Istanbul (+03, +0300)
System clock synchronized: yes                         
              NTP service: active                      
          RTC in local TZ: no
```

**Comment by xmatthias** [comment]
> ccxt.base.errors.InvalidNonce: binance {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}

Well binance clearly disagrees. it's checking your time against it's server time - and determined that your time is outside of the acceptable window.

While your output shows that you're using an NTP service (the one from systemd, most likely) - it's not showing the offset to the time server - nor when it last syncronized. 
ccxt recommends to syncronize the time at least every 10 minutes (or used to ...) to avoid this kind of problem.

**Comment by mert-donmez** [comment]
> > ccxt.base.errors.InvalidNonce: binance {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
> 
> Well binance clearly disagrees. it's checking your time against it's server time - and determined that your time is outside of the acceptable window.
> 
> While your output shows that you're using an NTP service (the one from systemd, most likely) - it's not showing the offset to the time server - nor when it last syncronized. ccxt recommends to syncronize the time at least every 10 minutes (or used to ...) to avoid this kind of problem.


Now when I type spot in the "trading_mode:", it connects to Binance account without any problems but futures i get this error is it due to the same error? time sync
```
2022-03-02 02:00:26,843 - freqtrade.exchange.exchange - INFO - Using CCXT 1.74.22
2022-03-02 02:00:26,843 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'future'}}
2022-03-02 02:00:26,855 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'future'}}
2022-03-02 02:00:26,868 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2022-03-02 02:00:31,936 - freqtrade.commands.trade_commands - ERROR - 'contract'
2022-03-02 02:00:31,937 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/root_ubuntu/Desktop/freqtrade_feat_short/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/home/root_ubuntu/Desktop/freqtrade_feat_short/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/home/root_ubuntu/Desktop/freqtrade_feat_short/freqtrade/freqtrade/worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/home/root_ubuntu/Desktop/freqtrade_feat_short/freqtrade/freqtrade/freqtradebot.py", line 66, in __init__
    self.exchange = ExchangeResolver.load_exchange(self.config['exchange']['name'], self.config)
  File "/home/root_ubuntu/Desktop/freqtrade_feat_short/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 32, in load_exchange
    exchange = ExchangeResolver._load_exchange(exchange_name,
  File "/home/root_ubuntu/Desktop/freqtrade_feat_short/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 54, in _load_exchange
    exchange = ex_class(**kwargs)
  File "/home/root_ubuntu/Desktop/freqtrade_feat_short/freqtrade/freqtrade/exchange/exchange.py", line 186, in __init__
    self.fill_leverage_tiers()
  File "/home/root_ubuntu/Desktop/freqtrade_feat_short/freqtrade/freqtrade/exchange/exchange.py", line 1941, in fill_leverage_tiers
    leverage_tiers = self.load_leverage_tiers()
  File "/home/root_ubuntu/Desktop/freqtrade_feat_short/freqtrade/freqtrade/exchange/common.py", line 130, in wrapper
    return f(*args, **kwargs)
  File "/home/root_ubuntu/Desktop/freqtrade_feat_short/freqtrade/freqtrade/exchange/binance.py", line 260, in load_leverage_tiers
    return self._api.fetch_leverage_tiers()
  File "/home/root_ubuntu/Desktop/freqtrade_feat_short/freqtrade/.env/lib/python3.9/site-packages/ccxt/binance.py", line 4581, in fetch_leverage_tiers
    return self.parse_leverage_tiers(response, symbols, 'symbol')
  File "/home/root_ubuntu/Desktop/freqtrade_feat_short/freqtrade/.env/lib/python3.9/site-packages/ccxt/base/exchange.py", line 2787, in parse_leverage_tiers
    if ((market is not None) and market['contract'] and (symbols_length == 0 or symbols.includes(symbol))):
KeyError: 'contract'
```

**Comment by xmatthias** [comment]
update ccxt. It's been solved this weekend.
