### ISSUE TITLE
Hyperopt problem - infinite space

### ISSUE THREAD

**Issue by mablue** [freqtrade/freqtrade#5610]
I think it happen just on `SharpeHyperOptLossDaily` and `SharpeHyperOptLoss` i tested all other strategies too
## Describe your environment

  * Operating system: 
```
                   -`                    mab@mab 
                  .o+`                   ------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Host: X550VX 1.0 
               `+oooooo:                 Kernel: 5.13.13-arch1-1 
               -+oooooo+:                Uptime: 5 hours, 1 min 
             `/:-:++oooo+:               Packages: 1073 (pacman), 1 (dpkg) 
            `/++++/+++++++:              Shell: bash 5.1.8 
           `/++++++++++++++:             Resolution: 1920x1080 
          `/+++ooooooooooooo/`           DE: GNOME 40.4 
         ./ooosssso++osssssso+`          WM: Mutter 
        .oossssso-````/ossssss+`         WM Theme: Adwaita 
       -osssssso.      :ssssssso.        Theme: Yaru-light [GTK2/3] 
      :osssssss/        osssso+++.       Icons: Yaru [GTK2/3] 
     /ossssssss/        +ssssooo/-       Terminal: vscode 
   `/ossssso+/:-        -:/+osssso+-     CPU: Intel i7-6700HQ (8) @ 3.500GHz 
  `+sso+:-`                 `.-/+oso:    GPU: NVIDIA GeForce GTX 950M 
 `++:.                           `-/+/   GPU: Intel HD Graphics 530 
 .`                                 `/   Memory: 3917MiB / 7844MiB 
```
  * Python Version: Python 3.9.6
  * CCXT version: ccxt==1.55.20
  * Freqtrade Version: freqtrade develop-695a1e21b  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

  1. coinex
  2. btc/usdt
  3. 1min
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

```
(.env) [mab@mab freqtrade]$ freqtrade hyperopt --hyperopt-loss SharpeHyperOptLossDaily --strategy Strategy005 -c configusdt.json -e 1000
2021-09-23 13:41:18,543 - freqtrade.configuration.configuration - INFO - Using config: configusdt.json ...
2021-09-23 13:41:18,544 - freqtrade.loggers - INFO - Verbosity set to 0
2021-09-23 13:41:18,544 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 1 ...
2021-09-23 13:41:18,544 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/mab/Documents/DEV/freqtrade/user_data ...
2021-09-23 13:41:18,544 - freqtrade.configuration.configuration - INFO - Using data directory: /home/mab/Documents/DEV/freqtrade/user_data/data/coinex ...
2021-09-23 13:41:18,544 - freqtrade.configuration.configuration - INFO - Parameter --epochs detected ... Will run Hyperopt with for 1000 epochs ...
2021-09-23 13:41:18,545 - freqtrade.configuration.configuration - INFO - Parameter -s/--spaces detected: default
2021-09-23 13:41:18,545 - freqtrade.configuration.configuration - INFO - Parameter -j/--job-workers detected: -1
2021-09-23 13:41:18,545 - freqtrade.configuration.configuration - INFO - Parameter --min-trades detected: 1
2021-09-23 13:41:18,545 - freqtrade.configuration.configuration - INFO - Using Hyperopt loss class name: SharpeHyperOptLossDaily
2021-09-23 13:41:18,545 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2021-09-23 13:41:18,547 - freqtrade.configuration.check_exchange - WARNING - Exchange "coinex" is known to the the ccxt library, available for the bot, but not officially supported by the Freqtrade development team. It may work flawlessly (please report back) or have serious issues. Use it at your own discretion.
2021-09-23 13:41:18,547 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2021-09-23 13:41:18,548 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2021-09-23 13:41:18,549 - freqtrade.commands.optimize_commands - INFO - Starting freqtrade in Hyperopt mode
2021-09-23 13:41:18,550 - filelock - INFO - Lock 139854790964320 acquired on /home/mab/Documents/DEV/freqtrade/user_data/hyperopt.lock
2021-09-23 13:41:18,550 - freqtrade.resolvers.exchange_resolver - INFO - No Coinex specific subclass found. Using the generic class instead.
2021-09-23 13:41:18,550 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2021-09-23 13:41:18,550 - freqtrade.exchange.exchange - INFO - Using CCXT 1.55.20
2021-09-23 13:41:18,550 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2021-09-23 13:41:18,553 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2021-09-23 13:41:18,557 - freqtrade.exchange.exchange - INFO - Using Exchange "CoinEx"
2021-09-23 13:41:20,083 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy Strategy005 from '/home/mab/Documents/DEV/freqtrade/user_data/strategies/Strategy005.py'...
2021-09-23 13:41:20,083 - freqtrade.strategy.hyper - INFO - Loading parameters from file /home/mab/Documents/DEV/freqtrade/user_data/strategies/Strategy005.json
2021-09-23 13:41:20,097 - freqtrade.strategy.hyper - INFO - Strategy Parameter: buy_fastd = 58
2021-09-23 13:41:20,097 - freqtrade.strategy.hyper - INFO - Strategy Parameter: buy_fishRsiNorma = 90
2021-09-23 13:41:20,097 - freqtrade.strategy.hyper - INFO - Strategy Parameter: buy_rsi = 17
2021-09-23 13:41:20,097 - freqtrade.strategy.hyper - INFO - Strategy Parameter: buy_volumeAVG = 111
2021-09-23 13:41:20,098 - freqtrade.strategy.hyper - INFO - Strategy Parameter: sell_fishRsiNorma = 2
2021-09-23 13:41:20,098 - freqtrade.strategy.hyper - INFO - Strategy Parameter: sell_minusDI = 87
2021-09-23 13:41:20,098 - freqtrade.strategy.hyper - INFO - Strategy Parameter: sell_rsi = 93
2021-09-23 13:41:20,098 - freqtrade.strategy.hyper - INFO - Strategy Parameter: sell_trigger = rsi-macd-minusdi
2021-09-23 13:41:20,098 - freqtrade.strategy.hyper - INFO - No params for protection found, using default values.
2021-09-23 13:41:20,098 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 1m.
2021-09-23 13:41:20,098 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2021-09-23 13:41:20,098 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: unlimited.
2021-09-23 13:41:20,098 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'buy': 10, 'sell': 30, 'unit': 'minutes'}.
2021-09-23 13:41:20,098 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 0.135, '24': 0.076, '42': 0.039, '60': 0}
2021-09-23 13:41:20,098 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 1m
2021-09-23 13:41:20,099 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.142
2021-09-23 13:41:20,099 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2021-09-23 13:41:20,099 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive: 0.01
2021-09-23 13:41:20,099 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.02
2021-09-23 13:41:20,099 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2021-09-23 13:41:20,099 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2021-09-23 13:41:20,099 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
2021-09-23 13:41:20,099 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'market', 'stoploss_on_exchange': False}
2021-09-23 13:41:20,099 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
2021-09-23 13:41:20,099 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2021-09-23 13:41:20,099 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: unlimited
2021-09-23 13:41:20,099 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2021-09-23 13:41:20,099 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 0
2021-09-23 13:41:20,099 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'buy': 10, 'sell': 30, 'unit': 'minutes'}
2021-09-23 13:41:20,099 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_sell_signal: True
2021-09-23 13:41:20,099 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_only: True
2021-09-23 13:41:20,099 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_buy_signal: False
2021-09-23 13:41:20,099 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_offset: 0.0
2021-09-23 13:41:20,099 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2021-09-23 13:41:20,100 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2021-09-23 13:41:20,100 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2021-09-23 13:41:20,103 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from '/home/mab/Documents/DEV/freqtrade/freqtrade/plugins/pairlist/StaticPairList.py'...
2021-09-23 13:41:20,111 - freqtrade.resolvers.iresolver - INFO - Using resolved hyperoptloss SharpeHyperOptLossDaily from '/home/mab/Documents/DEV/freqtrade/freqtrade/optimize/hyperopt_loss_sharpe_daily.py'...
2021-09-23 13:41:20,111 - freqtrade.optimize.hyperopt - INFO - Removing `/home/mab/Documents/DEV/freqtrade/user_data/hyperopt_results/hyperopt_tickerdata.pkl`.
2021-09-23 13:41:20,112 - freqtrade.optimize.hyperopt - INFO - Using optimizer random state: 63375
2021-09-23 13:41:20,119 - freqtrade.optimize.hyperopt_interface - INFO - Min roi table: {0: 0.012, 2: 0.008, 4: 0.004, 6: 0}
2021-09-23 13:41:20,119 - freqtrade.optimize.hyperopt_interface - INFO - Max roi table: {0: 0.12, 8: 0.043, 20: 0.015, 44: 0}
2021-09-23 13:41:20,147 - freqtrade.optimize.backtesting - INFO - Loading data from 2021-09-23 00:41:00 up to 2021-09-23 09:00:00 (0 days).
2021-09-23 13:41:20,148 - freqtrade.configuration.timerange - WARNING - Moving start-date by 0 candles to account for startup time.
2021-09-23 13:41:20,148 - freqtrade.optimize.hyperopt - INFO - Dataload complete. Calculating indicators
2021-09-23 13:41:20,156 - freqtrade.optimize.hyperopt - INFO - Hyperopting with data from 2021-09-23 00:41:00 up to 2021-09-23 09:00:00 (0 days)..
2021-09-23 13:41:20,161 - freqtrade.optimize.hyperopt - INFO - Found 8 CPU cores. Let's make them scream!
2021-09-23 13:41:20,161 - freqtrade.optimize.hyperopt - INFO - Number of parallel jobs set as: -1
2021-09-23 13:41:20,175 - freqtrade.optimize.hyperopt - INFO - Effective number of parallel workers used: 8
 [Epoch 17 of 1000 (  1%)] |██\                                                                                                                                | [ETA:   0:00:24, Elapsed Time: 0:00:00]
2021-09-23 13:41:23,778 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/mab/Documents/DEV/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/home/mab/Documents/DEV/freqtrade/freqtrade/commands/optimize_commands.py", line 87, in start_hyperopt
    hyperopt.start()
  File "/home/mab/Documents/DEV/freqtrade/freqtrade/optimize/hyperopt.py", line 472, in start
    asked = self.opt.ask(n_points=current_jobs)
  File "/home/mab/Documents/DEV/freqtrade/.env/lib/python3.9/site-packages/skopt/optimizer/optimizer.py", line 417, in ask
    opt._tell(x, y_lie)
  File "/home/mab/Documents/DEV/freqtrade/.env/lib/python3.9/site-packages/skopt/optimizer/optimizer.py", line 536, in _tell
    est.fit(self.space.transform(self.Xi), self.yi)
  File "/home/mab/Documents/DEV/freqtrade/.env/lib/python3.9/site-packages/sklearn/ensemble/_forest.py", line 304, in fit
    X, y = self._validate_data(X, y, multi_output=True,
  File "/home/mab/Documents/DEV/freqtrade/.env/lib/python3.9/site-packages/sklearn/base.py", line 433, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/home/mab/Documents/DEV/freqtrade/.env/lib/python3.9/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/home/mab/Documents/DEV/freqtrade/.env/lib/python3.9/site-packages/sklearn/utils/validation.py", line 880, in check_X_y
    y = check_array(y, accept_sparse='csr', force_all_finite=True,
  File "/home/mab/Documents/DEV/freqtrade/.env/lib/python3.9/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/home/mab/Documents/DEV/freqtrade/.env/lib/python3.9/site-packages/sklearn/utils/validation.py", line 720, in check_array
    _assert_all_finite(array,
  File "/home/mab/Documents/DEV/freqtrade/.env/lib/python3.9/site-packages/sklearn/utils/validation.py", line 103, in _assert_all_finite
    raise ValueError(
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
(.env) [mab@mab freqtrade]$ 
```

**Comment by xmatthias** [comment]
It's not related to the hyperopt loss - but to the strategy you're using.
The error is quite clear, too - you're using a **space** that includes None, Infinity, or a value higher than float64 for your system (probably + infinity).

It'll probably only happen with one loss function, but that's a random hit as that loss moved your space into the direction of this invalid value.

It's however nothing freqtrade will be able to fix - it's simply your spaces which are not restricted enough.

**Comment by mablue** [comment]
> restricted enough

thanks for help.
but when i use binance it not happen and just when i use coinex it happen!?:S
also Im not edited anything in Strategy005.py and i think it will have standard parameters to hyperopt but still I have this error.
in all strategies.

**Comment by xmatthias** [comment]
It's your data. You only have half a day of data, which is not enough to calculate the sharpe-ratio.
The sharpe-calculations require the "number of days" for their calculations - as that's 0 in your case, it'll not work.

Try to download more data - but i can't guarantee it'll work on coinex - as there are some exchanges which simply don't provide historic data.

**Comment by mablue** [comment]
> It's your data. You only have half a day of data, which is not enough to calculate the sharpe-ratio.
> The sharpe-calculations require the "number of days" for their calculations - as that's 0 in your case, it'll not work.
> 
> Try to download more data - but i can't guarantee it'll work on coinex - as there are some exchanges which simply don't provide historic data.

Thanks yess its the big problem if i share with you my bot api(non withdrawal key) can you fix it? I cant download more than 3days on my acc also some times just 1day.and it not useable for freqtrade. I need this cuz I probably prove must of iranians now working with this exchange and we need it. My acc on binance banned as well.Them said we want to verify your acc and I cant lie to them and want to let me withdrawal and them said ok :) and after withdrawal them removed my account with unusable 700sngls on it. But i can move the main pice of my coins to coinex exchange.and now premently i cant work with freqtrade on coinex exchange...

**Comment by xmatthias** [comment]
API keys are usually not necessary for data downloads.
If coinex does not provide historic data (more than 1 call) - there's little we can do about that.

Best investigate the API documentation for coinex to see if historic data-downloads are possible or not.
Personally, i'll treat coinex as unsupported exchange - however I'm open to Pull-requests fixing stuff for this exchange - or also doing this myself if the fix is quick (but i'll not do the investigation into that).

Personally, i'll however not look into it, as i see it as a small exchange which is not worth investing my time in at this point.

**Comment by xmatthias** [comment]
The [api](https://github.com/coinexcom/coinex_exchange_api/wiki/024kline) does not support a time-based parameter.
As such, it'll be impossible to download historic kline data directly.
You may attempt the "kraken" method (`--dl-trades`) - but expect downloading to take quite a long time - and test it with one pair only for the beginning.
the corresponding [api](https://github.com/coinexcom/coinex_exchange_api/wiki/023deals) does not look promising, and it does seem to always return the "current" trades only.

As such - i don't think you'll have possibilities to get historic data for this exchange at the moment.
If you're a user for them, best complain via their support to add these capabilities. Once these are there (and documented) - we can look at this again (or rather, you should open an issue with ccxt then to have the new capabilities implemented).

For now - there's nothing we can do here, therefore i'll be closing this issue.

**Comment by mablue** [comment]
🙏😊 I will continue to talking with coinex support and than ccxt than I return to you. Thanks for help

**Comment by cinorid** [comment]
they support time-based data with this format:
[coinex_exchange_api issues](https://github.com/coinexcom/coinex_exchange_api/issues/72#issuecomment-922367592)

**Comment by xmatthias** [comment]
@Cinorid please stop posting on issues that are years old and closed.
otherwise i'll have to remove your permissions to interact with this repo.
Thanks.
