### ISSUE TITLE
ERROR running hyperopt 

### ISSUE THREAD

**Issue by KarimHP** [freqtrade/freqtrade#5626]
Operating System: macOSBigSurr (Version 11.5.2) 
Python Version: Python 3.9.6
CCXT Version: ccxt==1.55.13
freqtrade version: freqtrade develop-5fdb539b

Command ran: freqtrade hyperopt --config config.json --hyperopt bbrsi_opt --hyperopt-loss SharpeHyperOptLossDaily --strategy BBRSI -e 500 --spaces all

So im trying to run freqtrade with a hyperopt strategy that i wrote "bbrsi_opt" on a strategy that i already backtested (BBRSI). Sadly when i try to run the command i get the following Error: 

```
2021-09-26 18:13:01,349 - freqtrade.optimize.backtesting - INFO - Loading data from 2021-07-29 09:00:00 up to 2021-09-25 19:00:00 (58 days).
2021-09-26 18:13:01,349 - freqtrade.configuration.timerange - WARNING - Moving start-date by 0 candles to account for startup time.
2021-09-26 18:13:01,349 - freqtrade.optimize.hyperopt - INFO - Dataload complete. Calculating indicators
2021-09-26 18:13:01,350 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/Users/karim/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/Users/karim/freqtrade/freqtrade/commands/optimize_commands.py", line 87, in start_hyperopt
    hyperopt.start()
  File "/Users/karim/freqtrade/freqtrade/optimize/hyperopt.py", line 416, in start
    self.prepare_hyperopt_data()
  File "/Users/karim/freqtrade/freqtrade/optimize/hyperopt.py", line 397, in prepare_hyperopt_data
    preprocessed = self.backtesting.strategy.advise_all_indicators(data)
  File "/Users/karim/freqtrade/freqtrade/strategy/interface.py", line 781, in advise_all_indicators
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair})
  File "/Users/karim/freqtrade/freqtrade/strategy/interface.py", line 781, in <dictcomp>
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair})
  File "/Users/karim/freqtrade/someDirectory/hyperopts/bbrsi_opt.py", line 49, in populate_indicators
    dataframe['sell-rsi'] = ta.RSI(DataFrame)
  File "talib/_abstract.pxi", line 398, in talib._ta_lib.Function.__call__
  File "talib/_abstract.pxi", line 277, in talib._ta_lib.Function.set_function_args
  File "talib/_abstract.pxi", line 462, in talib._ta_lib.Function.__check_opt_input_value
TypeError: Invalid parameter value for timeperiod (expected int, got type)
```

I really dont understand where this ERROR is coming from and am grateful for every help and advise :)

**Comment by ghost** [comment]
`dataframe['sell-rsi'] = ta.RSI(DataFrame)` should probably be `dataframe['sell-rsi'] = ta.RSI(dataframe)`.

`DataFrame` is a class, `dataframe` is probably the variable / instance.

**Comment by KarimHP** [comment]
> `dataframe['sell-rsi'] = ta.RSI(DataFrame)` should probably be `dataframe['sell-rsi'] = ta.RSI(dataframe)`.
> 
> `DataFrame` is a class, `dataframe` is probably the variable / instance.

Okay perfect thank you very much! :) now i fixed this but still get another weird ERROR: 

```
2021-09-26 19:25:29,407 - freqtrade.optimize.hyperopt - INFO - Dataload complete. Calculating indicators
2021-09-26 19:25:29,410 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/Users/karim/freqtrade/.env/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'middle'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/karim/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/Users/karim/freqtrade/freqtrade/commands/optimize_commands.py", line 87, in start_hyperopt
    hyperopt.start()
  File "/Users/karim/freqtrade/freqtrade/optimize/hyperopt.py", line 416, in start
    self.prepare_hyperopt_data()
  File "/Users/karim/freqtrade/freqtrade/optimize/hyperopt.py", line 397, in prepare_hyperopt_data
    preprocessed = self.backtesting.strategy.advise_all_indicators(data)
  File "/Users/karim/freqtrade/freqtrade/strategy/interface.py", line 781, in advise_all_indicators
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair})
  File "/Users/karim/freqtrade/freqtrade/strategy/interface.py", line 781, in <dictcomp>
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair})
  File "/Users/karim/freqtrade/someDirectory/hyperopts/bbrsi_opt.py", line 53, in populate_indicators
    dataframe['bb_middleband1'] = bollinger1['middle']
  File "/Users/karim/freqtrade/.env/lib/python3.9/site-packages/pandas/core/frame.py", line 3455, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/Users/karim/freqtrade/.env/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'middle'

```

Any idea where this might be coming from?

**Comment by KarimHP** [comment]
Okay the problem was that i was using "middle" instead of "mid". Problem solved now. Thank you for your help :)
