### ISSUE TITLE
Docker can't run because Telegram bot times out

### ISSUE THREAD

**Issue by exodiuss** [freqtrade/freqtrade#5647]
## Describe your environment

  * Operating system: Windows
  * Python Version: 3.8.5
  * CCXT version:
  * Freqtrade Version: 2021.9 (Docker)

## Describe the problem:

Telegram bot's connection is failing.  I've tried with a new bot but still doesn't work. Tried to update to last version but nothing changed. Do you have the same issue?

### Steps to reproduce:

  1. Add telegram
  2. Launch `docker-compose up -d`
  
### Observed Results:

Bot keeps reconnecting and timesout.

### Relevant code exceptions or logs

freqtrade    | 2021-10-01 06:37:50,420 - freqtrade.wallets - INFO - Wallets synced.

freqtrade    | 2021-10-01 06:37:50,421 - freqtrade.plugins.protectionmanager - INFO - No protection Handlers defined.

freqtrade    | 2021-10-01 06:37:50,492 - freqtrade.rpc.rpc_manager - INFO - Enabling rpc.telegram ...

freqtrade    | 2021-10-01 06:37:50,551 - freqtrade.rpc.telegram - INFO - using custom keyboard from config.json: [['/daily', '/stats', '/balance', '/profit'], ['/status table', '/performance'], ['/reload_config', '/count', '/logs']]

freqtrade    | /home/ftuser/.local/lib/python3.9/site-packages/telegram/ext/dispatcher.py:250: UserWarning: Asynchronous callbacks can not be processed without at least one worker thread.

freqtrade    |   warnings.warn(

freqtrade    | 2021-10-01 06:37:50,553 - apscheduler.scheduler - INFO - Scheduler started

freqtrade    | 2021-10-01 06:37:55,580 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f6f928a7280>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot1823022526:AAG3ZjuqFCT2LYhQgkPj85Qjx4XCVvTrJhk/getMe

freqtrade    | 2021-10-01 06:38:00,587 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f6f928a74c0>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot1823022526:AAG3ZjuqFCT2LYhQgkPj85Qjx4XCVvTrJhk/getMe

freqtrade    | 2021-10-01 06:38:05,595 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f6f928a7610>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot1823022526:AAG3ZjuqFCT2LYhQgkPj85Qjx4XCVvTrJhk/getMe

freqtrade    | 2021-10-01 06:38:10,603 - freqtrade.commands.trade_commands - ERROR - urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot1823022526:AAG3ZjuqFCT2LYhQgkPj85Qjx4XCVvTrJhk/getMe (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f6f928a7760>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))

freqtrade    | 2021-10-01 06:38:10,603 - freqtrade.commands.trade_commands - ERROR - Fatal exception!

freqtrade    | Traceback (most recent call last):

freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connection.py", line 140, in _new_conn

freqtrade    |     conn = connection.create_connection(

freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/connection.py", line 83, in create_connection

freqtrade    |     raise err

freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/connection.py", line 73, in create_connection

freqtrade    |     sock.connect(sa)

freqtrade    | socket.timeout: timed out

freqtrade    | 

freqtrade    | During handling of the above exception, another exception occurred:

freqtrade    | 

freqtrade    | Traceback (most recent call last):

freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 614, in urlopen

freqtrade    |     httplib_response = self._make_request(conn, method, url,

freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 360, in _make_request

freqtrade    |     self._validate_conn(conn)

freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 857, in _validate_conn

freqtrade    |     super(HTTPSConnectionPool, self)._validate_conn(conn)

freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 289, in _validate_conn

freqtrade    |     conn.connect()

freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connection.py", line 284, in connect

freqtrade    |     conn = self._new_conn()

freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connection.py", line 144, in _new_conn

freqtrade    |     raise ConnectTimeoutError(

freqtrade    | telegram.vendor.ptb_urllib3.urllib3.exceptions.ConnectTimeoutError: (<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f6f928a7760>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')

freqtrade    | 

freqtrade    | During handling of the above exception, another exception occurred:

freqtrade    | 

freqtrade    | Traceback (most recent call last):

freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/utils/request.py", line 259, in _request_wrapper

freqtrade    |     resp = self._con_pool.request(*args, **kwargs)

freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 68, in request

freqtrade    |     return self.request_encode_body(method, url, fields=fields,

freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 148, in request_encode_body

freqtrade    |     return self.urlopen(method, url, **extra_kw)

freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/poolmanager.py", line 244, in urlopen

freqtrade    |     response = conn.urlopen(method, u.request_uri, **kw)

freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 691, in urlopen

freqtrade    |     return self.urlopen(method, url, body, headers, retries,

freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 691, in urlopen

freqtrade    |     return self.urlopen(method, url, body, headers, retries,

freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 691, in urlopen

freqtrade    |     return self.urlopen(method, url, body, headers, retries,

freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 665, in urlopen

freqtrade    |     retries = retries.increment(method, url, error=e, _pool=self,

freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/retry.py", line 376, in increment

freqtrade    |     raise MaxRetryError(_pool, url, error or ResponseError(cause))

freqtrade    | telegram.vendor.ptb_urllib3.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot1823022526:AAG3ZjuqFCT2LYhQgkPj85Qjx4XCVvTrJhk/getMe (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f6f928a7760>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))

freqtrade    | 

freqtrade    | The above exception was the direct cause of the following exception:

freqtrade    | 

freqtrade    | Traceback (most recent call last):

freqtrade    |   File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading

freqtrade    |     worker = Worker(args)

freqtrade    |   File "/freqtrade/freqtrade/worker.py", line 35, in __init__

freqtrade    |     self._init(False)

freqtrade    |   File "/freqtrade/freqtrade/worker.py", line 52, in _init

freqtrade    |     self.freqtrade = FreqtradeBot(self._config)

freqtrade    |   File "/freqtrade/freqtrade/freqtradebot.py", line 80, in __init__

freqtrade    |     self.rpc: RPCManager = RPCManager(self)

freqtrade    |   File "/freqtrade/freqtrade/rpc/rpc_manager.py", line 28, in __init__

freqtrade    |     self.registered_modules.append(Telegram(self._rpc, config))

freqtrade    |   File "/freqtrade/freqtrade/rpc/telegram.py", line 90, in __init__

freqtrade    |     self._init()

freqtrade    |   File "/freqtrade/freqtrade/rpc/telegram.py", line 185, in _init

freqtrade    |     self._updater.start_polling(

freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/ext/updater.py", line 422, in start_polling

freqtrade    |     self._init_thread(self.dispatcher.start, "dispatcher", ready=dispatcher_ready)

freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/ext/updater.py", line 342, in _init_thread

freqtrade    |     name=f"Bot:{self.bot.id}:{name}",

freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/bot.py", line 365, in id

freqtrade    |     return self.bot.id

freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/bot.py", line 359, in bot

freqtrade    |     self._bot = self.get_me()

freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator

freqtrade    |     result = func(*args, **kwargs)

freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/bot.py", line 446, in get_me

freqtrade    |     result = self._post('getMe', timeout=timeout, api_kwargs=api_kwargs)

freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post

freqtrade    |     return self.request.post(

freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/utils/request.py", line 356, in post

freqtrade    |     result = self._request_wrapper(

freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/utils/request.py", line 265, in _request_wrapper

freqtrade    |     raise NetworkError(f'urllib3 HTTPError {error}') from error

freqtrade    | telegram.error.NetworkError: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot1823022526:AAG3ZjuqFCT2LYhQgkPj85Qjx4XCVvTrJhk/getMe (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f6f928a7760>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))

**Comment by exodiuss** [comment]
Seems resolved by itself now I'm running it again some hours later. Telegram might have been faulty. 
Sorry for the inconvenience.
