### ISSUE TITLE
ERROR - 'NoneType' object has no attribute 'update_order'

### ISSUE THREAD

**Issue by aristosv** [freqtrade/freqtrade#5683]
## Describe your environment

  * Operating system: Debian 10
  * Python Version: Python 2.7.16
  * CCXT version: ccxt==1.57.38
  * Freqtrade Version: freqtrade develop-a1be6124f
  
## Your question

After updating to the latest freqtrade version, I get the following errors in the log file and the bot dies. I suspect one of the trades is causing the issue because the bot process dies while discovering the open trades.

```
2021-10-07 12:52:28,435 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=1601, pair=UNI/BTC, amount=2.68000000, open_rate=0.00051880, open_since=2021-10-04 17:00:34)
2021-10-07 12:52:28,443 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'trade_id': 1601, 'type': buy_fill, 'buy_tag': None, 'exchange': 'Binance', 'pair': 'UNI/BTC', 'open_rate': 0.0005187992565055762, 'stake_amount': 0.0014, 'stake_currency': 'BTC', 'fiat_currency': 'USD', 'amount': 2.68, 'open_date': datetime.datetime(2021, 10, 4, 17, 0, 34, 551304)}
2021-10-07 12:52:28,443 - freqtrade.rpc.telegram - INFO - Notification 'buy_fill' not sent.
2021-10-07 12:52:28,679 - freqtrade.freqtradebot - INFO - Found open order for None
2021-10-07 12:52:28,680 - freqtrade.commands.trade_commands - ERROR - 'NoneType' object has no attribute 'update_order'
2021-10-07 12:52:28,680 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/usr/local/freqtrade_USDT_marios/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker.run()
  File "/usr/local/freqtrade_USDT_marios/freqtrade/worker.py", line 74, in run
    state = self._worker(old_state=state)
  File "/usr/local/freqtrade_USDT_marios/freqtrade/worker.py", line 92, in _worker
    self.freqtrade.startup()
  File "/usr/local/freqtrade_USDT_marios/freqtrade/freqtradebot.py", line 142, in startup
    self.startup_update_open_orders()
  File "/usr/local/freqtrade_USDT_marios/freqtrade/freqtradebot.py", line 256, in startup_update_open_orders
    self.update_trade_state(order.trade, order.order_id, fo)
  File "/usr/local/freqtrade_USDT_marios/freqtrade/freqtradebot.py", line 1271, in update_trade_state
    trade.update_order(order)
AttributeError: 'NoneType' object has no attribute 'update_order'
2021-10-07 12:52:28,681 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2021-10-07 12:52:28,681 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2021-10-07 12:52:28,775 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2021-10-07 12:52:28,777 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': warning, 'status': "19 open trades active.\n\nHandle these trades manually on Binance, or '/start' the bot again and use '/stopbuy' to handle open trades gracefully. \n"}
2021-10-07 12:52:28,830 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
2021-10-07 12:52:28,830 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.apiserver ...
2021-10-07 12:52:28,831 - freqtrade.rpc.api_server.webserver - INFO - Stopping API Server
2021-10-07 12:52:28,904 - uvicorn.error - INFO - Shutting down
2021-10-07 12:52:29,004 - uvicorn.error - INFO - Waiting for application shutdown.
2021-10-07 12:52:29,005 - uvicorn.error - INFO - Application shutdown complete.
2021-10-07 12:52:29,005 - uvicorn.error - INFO - Finished server process [13513]
2021-10-07 12:52:29,006 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.telegram ...
2021-10-07 12:52:29,007 - apscheduler.scheduler - INFO - Scheduler has been shut down
```

**Comment by froggleston** [comment]
Have you tried using a different database file, specified in the config? Freqtrade reads the sqlite file for open trades.

**Comment by aristosv** [comment]
the same database file that was used before is currently used.

**Comment by froggleston** [comment]
So that's probably your problem if the model has changed between the last freqtrade version and your current one.

**Comment by aristosv** [comment]
so how do I fix it?

**Comment by froggleston** [comment]
If it's not a live trade, simply create a different database, or open the sqlite file with a suitable editor and manually remove the row for that trade.

**Comment by xmatthias** [comment]
from a very quick look, I'd say the database is inconsistent and contains an order without matching trade.

While this should not be possible - it certainly can happen when manually modifying the database (for example).
Are you using sqlite, or a different database system?

You can try to run these queries:

``` sql
select * from orders where ft_trade_id is null;
```
or
 
``` sql
select * from orders where ft_trade_id not in (select id from trades);
```
i suspect that one of the 2 results will yield a result (otherwise i'd not know how you get to this state) ... How it got there is a different topic altogether.

maybe database corruption due to some HD error (like disk full), or an ill-advised update/delete statement...

**Comment by aristosv** [comment]
> Are you using sqlite, or a different database system?

whatever the default is when installing freqtrade

> You can try to run these queries:

How do I connect to the database so I can run these commands?

**Comment by aristosv** [comment]
<img width="1085" alt="2021-10-07 17_11_01-TAIL Marios Freqtrade USDT - Royal TS" src="https://user-images.githubusercontent.com/528302/136401945-37e44fbc-88e0-42b5-821c-0118d6695684.png">

ok so this is the result

**Comment by aristosv** [comment]
```
sqlite> select * from orders where ft_trade_id not in (select id from trades);
60792|1603|stoploss|COMP/BTC|1|267850290|open|COMP/BTC|stop_loss_limit|sell|0.00387||0.214|0.0|0.214|0.0|2021-10-07 12:30:59.153000||2021-10-07 12:30:59.268638
sqlite> DELETE FROM trades WHERE id = 1603;
sqlite> select * from orders where ft_trade_id not in (select id from trades);
60792|1603|stoploss|COMP/BTC|1|267850290|open|COMP/BTC|stop_loss_limit|sell|0.00387||0.214|0.0|0.214|0.0|2021-10-07 12:30:59.153000||2021-10-07 12:30:59.268638
```

I run the command to delete it but it's still there

**Comment by xmatthias** [comment]
the correct command to delete it should probably be `delete from orders where id = 60792`.

You should however also check on the exchange what happened to this order ... as it's ... strange at best to not have the trade there.

**Comment by aristosv** [comment]
all good, thanks

**Comment by moinonin** [comment]
```
select * from orders where ft_trade_id not in (select id from trades);
```
fixed my issue

**Comment by 20flint12** [comment]
here is log after "reload_config"
2024-11-01 16:47:01,010 - freqtrade.worker - INFO - Bot heartbeat. PID=36096, version='2024.9', state='RUNNING'
2024-11-01 16:48:01,015 - freqtrade.worker - INFO - Bot heartbeat. PID=36096, version='2024.9', state='RUNNING'
2024-11-01 16:49:01,021 - freqtrade.worker - INFO - Bot heartbeat. PID=36096, version='2024.9', state='RUNNING'
2024-11-01 16:50:06,000 - freqtrade.worker - INFO - Bot heartbeat. PID=36096, version='2024.9', state='RUNNING'
2024-11-01 16:50:26,002 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'reload_config'}
2024-11-01 16:50:26,003 - freqtrade.worker - INFO - Changing state from RUNNING to: RELOAD_CONFIG
2024-11-01 16:50:26,004 - freqtrade.worker - INFO - Bot heartbeat. PID=36096, version='2024.9', state='RELOAD_CONFIG'
2024-11-01 16:50:26,011 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2024-11-01 16:50:26,016 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
2024-11-01 16:50:26,017 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.apiserver ...
2024-11-01 16:50:26,017 - freqtrade.rpc.api_server.webserver - INFO - Stopping API Server
2024-11-01 16:50:26,044 - uvicorn.error - INFO - Shutting down
2024-11-01 16:50:26,146 - uvicorn.error - INFO - Waiting for application shutdown.
2024-11-01 16:50:26,147 - uvicorn.error - INFO - Application shutdown complete.
2024-11-01 16:50:26,147 - uvicorn.error - INFO - Finished server process [36096]
2024-11-01 16:50:26,149 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.telegram ...
2024-11-01 16:50:26,333 - telegram.ext.Application - INFO - Application is stopping. This might take a moment.
2024-11-01 16:50:26,334 - telegram.ext.Application - INFO - Application.stop() complete
2024-11-01 16:50:28,639 - freqtrade.exchange.exchange_ws - INFO - Resetting WS connections.
2024-11-01 16:50:28,642 - freqtrade.exchange.exchange_ws - INFO - XRP/USDT, 5m, spot - Task finished - cancelled
2024-11-01 16:50:28,643 - [freqtrade.exchange.exchange](https://freqtrade.exchange.exchange/)_ws - INFO - ETH/USDT, 5m, spot - Task finished - cancelled
2024-11-01 16:50:28,643 - [freqtrade.exchange.exchange](https://freqtrade.exchange.exchange/)_ws - INFO - TIA/USDT, 5m, spot - Task finished - cancelled
2024-11-01 16:50:28,644 - [freqtrade.exchange.exchange](https://freqtrade.exchange.exchange/)_ws - INFO - USDC/USDT, 5m, spot - Task finished - cancelled
2024-11-01 16:50:28,644 - [freqtrade.exchange.exchange](https://freqtrade.exchange.exchange/)_ws - INFO - FDUSD/USDT, 5m, spot - Task finished - cancelled
2024-11-01 16:50:28,644 - [freqtrade.exchange.exchange](https://freqtrade.exchange.exchange/)_ws - INFO - TROY/USDT, 5m, spot - Task finished - cancelled
2024-11-01 16:50:28,644 - [freqtrade.exchange.exchange](https://freqtrade.exchange.exchange/)_ws - INFO - WLD/USDT, 5m, spot - Task finished - cancelled
2024-11-01 16:50:28,645 - freqtrade.exchange.exchange_ws - INFO - MASK/USDT, 5m, spot - Task finished - cancelled
2024-11-01 16:50:28,645 - [freqtrade.exchange.exchange](https://freqtrade.exchange.exchange/)_ws - INFO - NEIRO/USDT, 5m, spot - Task finished - cancelled
2024-11-01 16:50:28,645 - [freqtrade.exchange.exchange](https://freqtrade.exchange.exchange/)_ws - INFO - WIF/USDT, 5m, spot - Task finished - cancelled
2024-11-01 16:50:28,646 - [freqtrade.exchange.exchange](https://freqtrade.exchange.exchange/)_ws - INFO - TAO/USDT, 5m, spot - Task finished - cancelled
2024-11-01 16:50:28,646 - [freqtrade.exchange.exchange](https://freqtrade.exchange.exchange/)_ws - INFO - BOME/USDT, 5m, spot - Task finished - cancelled
2024-11-01 16:50:28,646 - [freqtrade.exchange.exchange](https://freqtrade.exchange.exchange/)_ws - INFO - FET/USDT, 5m, spot - Task finished - cancelled
2024-11-01 16:50:28,647 - [freqtrade.exchange.exchange](https://freqtrade.exchange.exchange/)_ws - INFO - BTC/USDT, 5m, spot - Task finished - cancelled
2024-11-01 16:50:28,647 - [freqtrade.exchange.exchange](https://freqtrade.exchange.exchange/)_ws - INFO - SHIB/USDT, 5m, spot - Task finished - cancelled
2024-11-01 16:50:28,647 - [freqtrade.exchange.exchange](https://freqtrade.exchange.exchange/)_ws - INFO - ENA/USDT, 5m, spot - Task finished - cancelled
2024-11-01 16:50:28,647 - [freqtrade.exchange.exchange](https://freqtrade.exchange.exchange/)_ws - INFO - SUI/USDT, 5m, spot - Task finished - cancelled
2024-11-01 16:50:28,648 - [freqtrade.exchange.exchange](https://freqtrade.exchange.exchange/)_ws - INFO - SOL/USDT, 5m, spot - Task finished -
cancelled
2024-11-01 16:50:28,648 - [freqtrade.exchange.exchange](https://freqtrade.exchange.exchange/)_ws - INFO - PEPE/USDT, 5m, spot - Task finished - cancelled
2024-11-01 16:50:28,649 - [freqtrade.exchange.exchange](https://freqtrade.exchange.exchange/)_ws - INFO - DOGE/USDT, 5m, spot - Task finished - cancelled
2024-11-01 16:50:29,049 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2024-11-01 16:50:29,049 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2024-11-01 16:50:29,050 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2024-11-01 16:50:29,054 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
2024-11-01 16:50:29,307 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/admin/Documents/freqtrade/freqtrade/main.py", line 45, in main
    return_code = args"func"
                  ^^^^^^^^^^^^^^^^^^
  File "/home/admin/Documents/freqtrade/freqtrade/commands/trade_commands.py", line 25, in start_trading
    worker.run()
  File "/home/admin/Documents/freqtrade/freqtrade/worker.py", line 80, in run
    self._reconfigure()
  File "/home/admin/Documents/freqtrade/freqtrade/worker.py", line 218, in _reconfigure
    self.freqtrade.cleanup()
  File "/home/admin/Documents/freqtrade/freqtrade/freqtradebot.py", line 218, in cleanup
    self.exchange.close()
  File "/home/admin/Documents/freqtrade/freqtrade/exchange/exchange.py", line 310, in close
    self.loop.run_until_complete(self._api_async.close())
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/admin/Documents/freqtrade/.venv/lib/python3.11/site-packages/ccxt/async_support/base/[exchange.py](https://exchange.py/)", line 125, in close
    await self.session.close()
  File "/home/admin/Documents/freqtrade/.venv/lib/python3.11/site-packages/aiohttp/client.py", line 1192, in close
    await self._connector.close()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/Documents/freqtrade/.venv/lib/python3.11/site-packages/aiohttp/connector.py", line 833, in close
    return super().close()
           ^^^^^^^^^^^^^^^
  File "/home/admin/Documents/freqtrade/.venv/lib/python3.11/site-packages/aiohttp/connector.py", line 433, in close
    self._close()
  File "/home/admin/Documents/freqtrade/.venv/lib/python3.11/site-packages/aiohttp/[connector.py](https://connector.py/)", line 463, in _close
    transport.abort()
  File "/usr/lib/python3.11/asyncio/sslproto.py", line 247, in abort
    self._ssl_protocol._abort()
    ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '_abort'
