### ISSUE TITLE
EROR - Unable to initialize markets; OSE Error: [Errno 113] No route to host

### ISSUE THREAD

**Issue by redfox-codder** [freqtrade/freqtrade#5718]
## Describe your environment

  * Operating system: Ubuntu 20.04.3 LTS
  * Python Version: N/A. Am using docker 
  * CCXT version: N/A. Am using docker 
  * Freqtrade Version: 2021.9 
  
## Your question

I am using docker on ubuntu 20.04 (which runs on a virtual machine). I have trouble connecting to exchange (binance). 
Here is the error log that I get when running `freqtrade download-data --exchange binance -t 15m`

```
Creating ft_userdata_freqtrade_run ... done
2021-10-16 01:53:11,145 - freqtrade.configuration.configuration - INFO - Using config: user_data/config.json ...
2021-10-16 01:53:11,149 - freqtrade.loggers - INFO - Verbosity set to 0
2021-10-16 01:53:11,150 - freqtrade.configuration.configuration - INFO - Using exchange binance
2021-10-16 01:53:11,218 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2021-10-16 01:53:11,220 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/binance ...
2021-10-16 01:53:11,221 - freqtrade.configuration.configuration - INFO - timeframes --timeframes: ['15m']
2021-10-16 01:53:11,221 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2021-10-16 01:53:11,266 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2021-10-16 01:53:11,266 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2021-10-16 01:53:11,267 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2021-10-16 01:53:11,272 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2021-10-16 01:53:11,272 - freqtrade.exchange.exchange - INFO - Using CCXT 1.57.3
2021-10-16 01:53:11,273 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2021-10-16 01:53:11,299 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 200}
2021-10-16 01:53:11,328 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2021-10-16 01:53:11,333 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2021-10-16 01:53:11,333 - freqtrade.exchange.exchange - INFO - Markets were not loaded. Loading them now..
2021-10-16 01:53:14,425 - freqtrade.exchange.exchange - ERROR - Unable to initialize markets.
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
OSError: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f85c4f50490>: Failed to establish a new connection: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/exchangeInfo (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f85c4f50490>: Failed to establish a new connection: [Errno 113] No route to host'))
```
I have added Binance API key to the config file, and kept the default values for other fields in the config.json.

After doing some search, I tried disabling the firewall using `ufw disable`, but that made no change. 

Any help or clue will be much appreciated.

**Comment by xmatthias** [comment]
Based on the error (no route to host) - it's certain that it's network-related problems.

Your setup is kinda complicated - as it's running docker within a VM within a host computer (think of a box in a box in a box :laughing: ) - so this problem can be at any level (in theory).

As you're running in a VM - please make sure that **from within the VM** - you can connect to binance (you probably can't ...).
Maybe you forgot to plug in the network plug (basically, network interface is disabled) - or it's a "host only" interface, not allowing you to go to the internet, but only to the host's (the computer running the VM) addresses.

You can also try the same from within docker - but i'd go for the VM first, as usually, it's the VM causing problems, not docker.

**Comment by xmatthias** [comment]
I'll assume this as answered by the above.

Feel free to comment below / reopen if that's not the case.

**Comment by redfox-codder** [comment]
Hello xmatthias,

Thanks for your helpful and prompt response. 

I was struggling with resolving the issue, and there was pretty much strange things happening; like I could ping some of the exchanges from within the VM, but not all of them. 

But as you suggested, the problem was with the VM; I just set the VM to replicate the physical network connection same as the host and that resolved all the issues. Now I could run freqtrade commands such as download-data.

Cheers,
Ahmad.
