### ISSUE TITLE
Multiple Exceptions - Bot continues to run

### ISSUE THREAD

**Issue by kurciqs** [freqtrade/freqtrade#5721]
## Describe your environment

  * Operating system: Kali Linux
  * Python Version: 3.9.7 
  * CCXT version: ccxt==1.57.94
  * Freqtrade Version: freqtrade develop-0e7d903a6
  
## Your question

While my bot gives heartbeat updates I get these errors in the logs occasionally (pasted below). The code doesn't stop working when I get the exceptions. Maybe it is intended to be like this, I don't know. 
I normally wouldn't ask, but I did not get a trade  for the last 13 hours of running the bot.
If you need anything (more logs, config file, ...) just tell me.

Just wanna know if this error is somehow not allowing the bot to make transactions.

Thanks.

```
2021-10-16 04:44:17,947 - freqtrade.worker - INFO - Bot heartbeat. PID=50510, version='develop-0e7d903a6', state='RUNNING'
2021-10-16 04:45:18,507 - freqtrade.worker - INFO - Bot heartbeat. PID=50510, version='develop-0e7d903a6', state='RUNNING'
2021-10-16 04:46:18,895 - freqtrade.worker - INFO - Bot heartbeat. PID=50510, version='develop-0e7d903a6', state='RUNNING'
2021-10-16 04:47:19,446 - freqtrade.worker - INFO - Bot heartbeat. PID=50510, version='develop-0e7d903a6', state='RUNNING'
2021-10-16 04:48:19,550 - freqtrade.worker - INFO - Bot heartbeat. PID=50510, version='develop-0e7d903a6', state='RUNNING'
2021-10-16 04:49:19,768 - freqtrade.worker - INFO - Bot heartbeat. PID=50510, version='develop-0e7d903a6', state='RUNNING'
2021-10-16 04:50:25,094 - freqtrade.exchange.exchange - ERROR - Could not reload markets.
Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/kali/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1371, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/kali/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/kali/.local/lib/python3.9/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/kali/.local/lib/python3.9/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/home/kali/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/kali/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/kali/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='ftx.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 587, in fetch
    response = self.session.request(
  File "/home/kali/.local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/kali/.local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/kali/.local/lib/python3.9/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='ftx.com', port=443): Read timed out. (read timeout=10)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kali/Downloads/Bots/freqtrade/freqtrade/exchange/exchange.py", line 354, in reload_markets
    self._markets = self._api.load_markets(reload=True)
  File "/home/kali/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 1411, in load_markets
    currencies = self.fetch_currencies()
  File "/home/kali/.local/lib/python3.9/site-packages/ccxt/ftx.py", line 379, in fetch_currencies
    response = self.publicGetCoins(params)
  File "/home/kali/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 457, in inner
    return entry(_self, **inner_kwargs)
  File "/home/kali/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 506, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/kali/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 502, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/kali/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 617, in fetch
    raise RequestTimeout(details) from e
ccxt.base.errors.RequestTimeout: ftx GET https://ftx.com/api/coins
2021-10-16 04:50:25,554 - freqtrade.worker - INFO - Bot heartbeat. PID=50510, version='develop-0e7d903a6', state='RUNNING'
2021-10-16 04:51:25,906 - freqtrade.worker - INFO - Bot heartbeat. PID=50510, version='develop-0e7d903a6', state='RUNNING'
2021-10-16 04:52:26,122 - freqtrade.worker - INFO - Bot heartbeat. PID=50510, version='develop-0e7d903a6', state='RUNNING'
2021-10-16 04:53:26,826 - freqtrade.worker - INFO - Bot heartbeat. PID=50510, version='develop-0e7d903a6', state='RUNNING'
2021-10-16 04:54:26,902 - freqtrade.worker - INFO - Bot heartbeat. PID=50510, version='develop-0e7d903a6', state='RUNNING'

```

**Comment by xmatthias** [comment]
It's quite simple - it's a network-level timeout.

This is either the exchange that's experiencing high load (pretty likely, the FTX app seemed slow this afternoon as well), or an issue with your (the bot's) network.

The errors are captured - and as long as it isn't happening the first time on this call it should be ok.
you can easily check for this by checking the whitelist (`/whitelist`) - if there's pairs there (there are, otherwise the log would say so) the bot will look for buy opportunities.

As mentioned yesterday - a strategy can have multiple buys per day, or no buys for multiple days. 
Backtesting will tell you what to roughly expect - but that still doesn't guarantee for buys within a particular timeframe, as i've seen many strategies that have a very active period (multiple trades per day) - followed by a quiet period.

**Comment by xmatthias** [comment]
I'll assume this as answered by the above.

Feel free to comment below / reopen if that's not the case.
