### ISSUE TITLE
Error while working with informative time frames: unhashable type: 'list'

### ISSUE THREAD

**Issue by AliSertanYaka** [freqtrade/freqtrade#5762]
## Describe your environment

  * Operating system:  Linux - Ubuntu
  * Python Version: 3.8
  * CCXT version: ccxt==1.57.3
  * Freqtrade Version:  2021.9
  
## Describe the problem:

When I run the bot with the strategy that has informative pairs with different timeframes, I got an error and bot stoped running. There is no problem while using the same strategy for backtest. The error is TypeError: unhashable type: 'list'.

 

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  2021-10-20 07:27:44,816 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': "Searching for USDT pairs to buy and sell based on [{'StaticPairList': 'StaticPairList'}]"}
2021-10-20 07:27:44,967 - freqtrade.commands.trade_commands - ERROR - unhashable type: 'list'
2021-10-20 07:27:44,968 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/ubuntu/environment/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker.run()
  File "/home/ubuntu/environment/freqtrade/freqtrade/worker.py", line 74, in run
    state = self._worker(old_state=state)
  File "/home/ubuntu/environment/freqtrade/freqtrade/worker.py", line 111, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
  File "/home/ubuntu/environment/freqtrade/freqtrade/worker.py", line 132, in _throttle
    result = func(*args, **kwargs)
  File "/home/ubuntu/environment/freqtrade/freqtrade/worker.py", line 145, in _process_running
    self.freqtrade.process()
  File "/home/ubuntu/environment/freqtrade/freqtrade/freqtradebot.py", line 163, in process
    self.strategy.gather_informative_pairs())
  File "/home/ubuntu/environment/freqtrade/freqtrade/strategy/interface.py", line 416, in gather_informative_pairs
    return list(set(informative_pairs))
TypeError: unhashable type: 'list'
2021-10-20 07:27:44,980 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2021-10-20 07:27:44,981 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2021-10-20 07:27:45,031 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2021-10-20 07:27:45,033 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
2021-10-20 07:27:45,034 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.telegram ...
2021-10-20 07:27:45,035 - apscheduler.scheduler - INFO - Scheduler has been shut down
  ```

**Comment by xmatthias** [comment]
can you provide an example on how you're defining informative pairs? 
without that part of the strategy, there'll be not much we can do...

**Comment by AliSertanYaka** [comment]
Sorry for miss information, I am kind a new for programming. 
The problem is using more than one informative pairs with different time frames. If I use one there is no error. An example code is 

    def informative_pairs(self):
       # get access to all pairs available in whitelist.
        pairs = self.dp.current_whitelist()
        # Assign tf to each pair so they can be downloaded and cached for strategy.
        informative_pairs = [(pair, '1h') for pair in pairs]
        informative_pairs_2 = [(pair, '1d') for pair in pairs]
        # Optionally Add additional "static" pairs
        informative_pairs += []
        informative_pairs_2 += []
        return informative_pairs, informative_pairs_2
        
    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
                
        if not self.dp:
            # Don't do anything if DataProvider is not available.
            return dataframe
        inf_tf = '1h'
        inf_tf_2 = '1d'
        # Get the informative pair
        informative = self.dp.get_pair_dataframe(pair=metadata['pair'], timeframe=inf_tf)
        informative_2= self.dp.get_pair_dataframe(pair=metadata['pair'], timeframe=inf_tf_2)
       
        informative['ema10'] = ta.EMA(informative, timeperiod=10)
        informative['ema21'] = ta.EMA(informative, timeperiod=21)

        informative_2['ema10'] = ta.EMA(informative_2, timeperiod=10)
        informative_2['ema21'] = ta.EMA(informative_2, timeperiod=21)

        dataframe = merge_informative_pair(dataframe, informative, self.timeframe, inf_tf, ffill=True)
        dataframe = merge_informative_pair(dataframe, informative_2, self.timeframe, inf_tf_2, ffill=True)

**Comment by xmatthias** [comment]
Informative pairs expects you to return a list of tuples `[(pair, '1h'), (pair2, '5m')]`.

by returning `return informative_pairs, informative_pairs_2` - you're returning 2 lists, each containing pair/timeframe tuples - which is not supported (the interface expects one list - not a tuple of 2 lists).

You should however be able to use `return informative_pairs + informative_pairs_2` - which will combine the 2 lists into one.

Simplified sample of the reasoning behind this:

``` python
In [1]: [1,2,3] + [5,6,7]
Out[1]: [1, 2, 3, 5, 6, 7]

```
