### ISSUE TITLE
Everything stopped working

### ISSUE THREAD

**Issue by zorann** [freqtrade/freqtrade#5802]
Hello,

i got error 

raise NetworkError(f'urllib3 HTTPError {error}') from error
telegram.error.NetworkError: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot1986844598:AAEl0KSl11vb1bABVzxluaCya5pxNjLj6K4/getMe (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7fc3a02aca30>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))

No trading, no connection to telegram.

What is wrong?

**Comment by xmatthias** [comment]
For the future: issues with deleted issue-template will be closed without further notice.

It's pretty simple - connection failed. This can have 2 reasons - either your pc/server has a problem connecting to telegram - or telegram itself has a problem (doesn't seem to have, my bots work fine).

Usually, a restart of freqtrade will resolve this, unless your network still has the problems.
Alternatively you can disable telegram - so it's no longer connecting to the telegram API.

**Comment by zorann** [comment]
I have servers in one place and phones in other. I will try to restart servers. Can i ask you how can i force sell all when BTC drops 5% how can i do this in freqtrade strategy. Thanks for everything!

**Comment by zorann** [comment]
I forgot to tell that my servers are runing freqtrade under docker-compose!

**Comment by zorann** [comment]
OK. After server reset everything runs again. I did reset remotely so server was running. Killing docker container was doing nothing. Is there any faster way then rebooting?

**Comment by zorann** [comment]
OK. Sorry for deleting template. Can you help me with force sell all in
strategy when BTC drops 5%.

regards

V sre., 27. okt. 2021 12:13 je oseba Matthias ***@***.***>
napisala:

**Comment by xmatthias** [comment]
Please use the edit button instead of posting multiple comments in quick succession. That helps keeping issues clean and easy to read and follow.

You're best off in using a reasonable stoploss. Just because BTC dumps 5% won't mean all other coins will dump, too - so you might end up with more losses than necessary.

If you wanna look at BTC, I'd suggest investigating [informative pairs](https://www.freqtrade.io/en/stable/strategy-customization/#additional-data-informative_pairs) (or [@informative](https://www.freqtrade.io/en/stable/strategy-customization/#informative), which serves the same function with a slightly different syntax).

**Comment by italodamato** [comment]
@xmatthias I'm also getting this error. 

The bot works fine for 3-4 hours and then it crashes with this error:

<details>
<summary>Error message</summary>

```
2022-01-05 04:17:56,740 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='docker-028636b4', state='RUNNING'
2022-01-05 04:40:47,635 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f025665dc90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /bot************:********************/getUpdates
2022-01-05 04:56:43,211 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError ('Connection aborted.', OSError(107, 'Transport endpoint is not connected'))
2022-01-05 05:00:56,393 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 614, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 360, in _make_request
    self._validate_conn(conn)
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 857, in _validate_conn
    super(HTTPSConnectionPool, self)._validate_conn(conn)
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 289, in _validate_conn
    conn.connect()
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/connection.py", line 333, in connect
    cert = self.sock.getpeercert()
  File "/usr/local/lib/python3.10/ssl.py", line 1153, in getpeercert
    self._check_connected()
  File "/usr/local/lib/python3.10/ssl.py", line 1118, in _check_connected
    self.getpeername()
OSError: [Errno 107] Transport endpoint is not connected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/utils/request.py", line 259, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 68, in request
    return self.request_encode_body(method, url, fields=fields,
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 691, in urlopen
    return self.urlopen(method, url, body, headers, retries,
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 665, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/retry.py", line 347, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 614, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 360, in _make_request
    self._validate_conn(conn)
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 857, in _validate_conn
    super(HTTPSConnectionPool, self)._validate_conn(conn)
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 289, in _validate_conn
    conn.connect()
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/connection.py", line 333, in connect
    cert = self.sock.getpeercert()
  File "/usr/local/lib/python3.10/ssl.py", line 1153, in getpeercert
    self._check_connected()
  File "/usr/local/lib/python3.10/ssl.py", line 1118, in _check_connected
    self.getpeername()
telegram.vendor.ptb_urllib3.urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError(107, 'Transport endpoint is not connected'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/ext/updater.py", line 646, in _network_loop_retry
    if not action_cb():
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/ext/updater.py", line 597, in polling_action_cb
    updates = self.bot.get_updates(
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/ext/extbot.py", line 222, in get_updates
    updates = super().get_updates(
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/bot.py", line 2945, in get_updates
    self._post(
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/utils/request.py", line 265, in _request_wrapper
    raise NetworkError(f'urllib3 HTTPError {error}') from error
telegram.error.NetworkError: urllib3 HTTPError ('Connection aborted.', OSError(107, 'Transport endpoint is not connected'))
2022-01-05 05:09:24,433 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f0244dce830>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /bot************:********************/getUpdates
2022-01-05 06:01:30,326 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError ('Connection aborted.', OSError(107, 'Transport endpoint is not connected'))
2022-01-05 06:08:51,310 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 614, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 360, in _make_request
    self._validate_conn(conn)
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 857, in _validate_conn
    super(HTTPSConnectionPool, self)._validate_conn(conn)
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 289, in _validate_conn
    conn.connect()
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/connection.py", line 333, in connect
    cert = self.sock.getpeercert()
  File "/usr/local/lib/python3.10/ssl.py", line 1153, in getpeercert
    self._check_connected()
  File "/usr/local/lib/python3.10/ssl.py", line 1118, in _check_connected
    self.getpeername()
OSError: [Errno 107] Transport endpoint is not connected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/utils/request.py", line 259, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 68, in request
    return self.request_encode_body(method, url, fields=fields,
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 691, in urlopen
    return self.urlopen(method, url, body, headers, retries,
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 665, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/retry.py", line 347, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 614, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 360, in _make_request
    self._validate_conn(conn)
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 857, in _validate_conn
    super(HTTPSConnectionPool, self)._validate_conn(conn)
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 289, in _validate_conn
    conn.connect()
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/connection.py", line 333, in connect
    cert = self.sock.getpeercert()
  File "/usr/local/lib/python3.10/ssl.py", line 1153, in getpeercert
    self._check_connected()
  File "/usr/local/lib/python3.10/ssl.py", line 1118, in _check_connected
    self.getpeername()
telegram.vendor.ptb_urllib3.urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError(107, 'Transport endpoint is not connected'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/ext/updater.py", line 646, in _network_loop_retry
    if not action_cb():
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/ext/updater.py", line 597, in polling_action_cb
    updates = self.bot.get_updates(
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/ext/extbot.py", line 222, in get_updates
    updates = super().get_updates(
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/bot.py", line 2945, in get_updates
    self._post(
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/utils/request.py", line 265, in _request_wrapper
    raise NetworkError(f'urllib3 HTTPError {error}') from error
telegram.error.NetworkError: urllib3 HTTPError ('Connection aborted.', OSError(107, 'Transport endpoint is not connected'))
2022-01-05 06:28:54,122 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError ('Connection aborted.', OSError(107, 'Transport endpoint is not connected'))
```

</details>

My bot is hosted on Google Cloud so I don't expect any connection issues. The weird thing is that I can control it from Telegram at the beginning (before the error happens).

Looking at the instance stats, I see that the disk throughput also goes through the roof when the error happens. 
![image](https://user-images.githubusercontent.com/45588475/148191973-27ec0c06-5cf4-43be-b410-dcee6650124e.png)

When I say 'it crashes' I mean that I'm not able to connect via SSH so the only way is to stop and restart the instance. 

Do you have any idea why this is happening?

## Describe your environment

  * Operating system: Ubuntu 20.04.3 LTS
  * Python Version: Python 3.8.10
  * CCXT version: n/a
  * Freqtrade Version: freqtrade docker-028636b4

I'm wondering if this could be related to this issue? https://github.com/python-telegram-bot/python-telegram-bot/issues/1393

**Comment by xmatthias** [comment]
Its either a (regional) telegram outage, or the ip youre using is blocked by telegram servers.

From a freqtrade point od view, there's little we can do, as its environment/telegram dependent, and i dont think starting the bot without telegram would be desirable, as then youll not get any notofications until you restart the bot manually, woch might potentially be dangerous.

**Comment by italodamato** [comment]
I switched to Oracle and it seems to be solved now. I'd say it's either due to a memory leak (I was using a 1GB VM while now I have 24GB) or some configuration in Google Cloud.

**Comment by xmatthias** [comment]
i'd blame the Google cloud IP.

As GCP is considered "bigger" over oracle - it's more likely that you had some bad actor have the same IP before you - causing telegram to ban the IP..

**Comment by italodamato** [comment]
I just find it weird that it works for 3-4 hours before getting errors
which I'm not sure would happen if the IP was already banned - but I guess
we'll never know.
