### ISSUE TITLE
Error using okex - strategy requires 480 candles to start

### ISSUE THREAD

**Issue by ThunderBRZ** [freqtrade/freqtrade#5831]
## Describe your environment

  * Operating system: Ubuntu
  * Python Version: Python 3.8.10
  * CCXT version: 1.60.11:
  * Freqtrade Version:  develop-a1e887803
  
## Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

  1. Just config OKEX exchange and error apears
  
### Observed Results:

Crash freqtrade.
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  2021-11-03 16:52:41,167 - freqtrade.exchange.exchange - INFO - Using CCXT 1.60.11
2021-11-03 16:52:41,168 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2021-11-03 16:52:41,171 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 105}
2021-11-03 16:52:41,174 - freqtrade.exchange.exchange - INFO - Using Exchange "OKEX"
2021-11-03 16:52:44,754 - freqtrade.commands.trade_commands - ERROR - This strategy requires 480 candles to start. OKEX only provides 95 for 5m.
2021-11-03 16:52:44,754 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/lds/freqtradev2/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/home/lds/freqtradev2/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/home/lds/freqtradev2/freqtrade/worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/home/lds/freqtradev2/freqtrade/freqtradebot.py", line 65, in __init__
    self.exchange = ExchangeResolver.load_exchange(self.config['exchange']['name'], self.config)
  File "/home/lds/freqtradev2/freqtrade/resolvers/exchange_resolver.py", line 32, in load_exchange
    exchange = ExchangeResolver._load_exchange(exchange_name,
  File "/home/lds/freqtradev2/freqtrade/resolvers/exchange_resolver.py", line 54, in _load_exchange
    exchange = ex_class(**kwargs)
  File "/home/lds/freqtradev2/freqtrade/exchange/exchange.py", line 158, in __init__
    self.validate_required_startup_candles(config.get('startup_candle_count', 0),
  File "/home/lds/freqtradev2/freqtrade/exchange/exchange.py", line 481, in validate_required_startup_candles
    raise OperationalException(
freqtrade.exceptions.OperationalException: This strategy requires 480 candles to start. OKEX only provides 95 for 5m.

  ```

**Comment by xmatthias** [comment]
I think the exception is quite clear ... Your strategy requires historic 480 candles - but okex only provides 95 (which is technically not true, ti'll be 98, but we apply a safety cushion to the value, as sometimes candles can be missing).

Quite simply - have your strategy require less historic data to trade with it on okex.

I'm working on improving this (specifically for/because of OKEX) - but it's not ready yet - so at the moment, this strategy (assuming the history requirement is correct) will not work.

**Comment by ThunderBRZ** [comment]
Hi xmatthias, many thanks for ur reply...

In my test, this strategy works in freqtrade develop-20a61e03d but no in develop-a1e887803.

**Comment by xmatthias** [comment]
older versions of freqtrade may start with this strategy in combination with okex - however but it'll not work correctly, as okex only provides 100 candles of history (this didn't change...).
So the strategy starts - but indicators with a lookback further than 100 will not calculate correctly, probably causing no buys (or at least no buys with this particular signal).
you'll also not have been able to backtest against OKEX, as data-download did not work correctly (I'd always recommend backtesting against the exchange / markets you're really working against).

So it's not that it works correctly - it just doesn't alert you that something is wrong.
