### ISSUE TITLE
Freqtrade died when cancled open order at Okex 

### ISSUE THREAD

**Issue by lamantrra** [freqtrade/freqtrade#5842]
## Describe your environment

  * Operating system: docker
  * Python Version: Python 3.9.7
  * CCXT version: ccxt==1.60.11
  * Freqtrade Version: docker-781f8a05 

## Describe the problem:

I recently using freqtrade on okex and everything is great in dry-run mode, but today I switch to live mode and when buy signal created by freqtrade and the order canceled with unfilled timeout or manually, freqtrade crashed and it was going to restart process.
This bug is still in latest stable(2021.10) and develop version. please check this issue.

PS: 
1.  This doesn't happen when the order is completely filled.
2. This problem exists in the latest stable and develop version. 

### Steps to reproduce:

  1. Triggered a buy signal at the Okex exchange on live mode.
  2. Manually canceled or happen unfilled timeout order.
  3. Freqtrade going to restart loop and sending "process died" every time in telegram.
  4. This problem remains until to manually delete the order id from the database.
  
### Observed Results:

  * Freqtrade process died and it no longer works properly 

### Relevant code exceptions or logs

  ```
2021-11-05 13:22:58,776 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=16, pair=MANA/BTC, amount=7.03000000, open_rate=0.00004117, open_since=2021-11-05 13:22:50)
2021-11-05 13:22:58,781 - freqtrade.commands.trade_commands - ERROR - float division by zero
2021-11-05 13:22:58,781 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker.run()
  File "/freqtrade/freqtrade/worker.py", line 74, in run
    state = self._worker(old_state=state)
  File "/freqtrade/freqtrade/worker.py", line 111, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
  File "/freqtrade/freqtrade/worker.py", line 132, in _throttle
    result = func(*args, **kwargs)
  File "/freqtrade/freqtrade/worker.py", line 145, in _process_running
    self.freqtrade.process()
  File "/freqtrade/freqtrade/freqtradebot.py", line 171, in process
    self.check_handle_timedout()
  File "/freqtrade/freqtrade/freqtradebot.py", line 904, in check_handle_timedout
    fully_cancelled = self.update_trade_state(trade, trade.open_order_id, order)
  File "/freqtrade/freqtrade/freqtradebot.py", line 1286, in update_trade_state
    new_amount = self.get_real_amount(trade, order)
  File "/freqtrade/freqtrade/freqtradebot.py", line 1362, in get_real_amount
    fee_cost, fee_currency, fee_rate = self.exchange.extract_cost_curr_rate(order)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 1193, in extract_cost_curr_rate
    self.calculate_fee_rate(order))
  File "/freqtrade/freqtrade/exchange/exchange.py", line 1166, in calculate_fee_rate
    order['fee']['cost'] / safe_value_fallback2(order, order, 'filled', 'amount'), 8)
ZeroDivisionError: float division by zero
2021-11-05 13:22:58,782 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2021-11-05 13:22:58,782 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}

  ```

**Comment by xmatthias** [comment]
Nice catch, thanks a lot for reporting.
will be fixed in a few minutes in develop (please wait for CI to complete if you're using docker ...)

**Comment by lamantrra** [comment]
Thank you @xmatthias ,
I tested this issue again under different conditions and everything works perfectly.
