### ISSUE TITLE
Could not find a version that satisfies the requirement TA-Lib==0.4.21

### ISSUE THREAD

**Issue by fabio1843** [freqtrade/freqtrade#5844]
## Describe your environment

  * Operating system: Debian 10 

Installing freqtrade using ./setup.sh --install gives me this error

```
_ERROR: Command errored out with exit status 1:
   command: /root/freqtrade/.env/bin/python3.7 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-z70dacl4/ta-lib_b437192b935f4021b433ec99e9dd28ce/setup.py'"'"'; __file__='"'"'/tmp/pip-install-z70dacl4/ta-lib_b437192b935f4021b433ec99e9dd28ce/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-k4zxu5o1
       cwd: /tmp/pip-install-z70dacl4/ta-lib_b437192b935f4021b433ec99e9dd28ce/
  Complete output (93 lines):
  Processing numpy/random/_bounded_integers.pxd.in
  Processing numpy/random/_pcg64.pyx
  Traceback (most recent call last):
    File "/tmp/easy_install-18_pb2hu/numpy-1.21.4/tools/cythonize.py", line 59, in process_pyx
      import Cython
  ModuleNotFoundError: No module named 'Cython'
  
  The above exception was the direct cause of the following exception:
  
  Traceback (most recent call last):
    File "/tmp/easy_install-18_pb2hu/numpy-1.21.4/tools/cythonize.py", line 240, in <module>
      main()
    File "/tmp/easy_install-18_pb2hu/numpy-1.21.4/tools/cythonize.py", line 236, in main
      find_process_files(root_dir)
    File "/tmp/easy_install-18_pb2hu/numpy-1.21.4/tools/cythonize.py", line 227, in find_process_files
      process(root_dir, fromfile, tofile, function, hash_db)
    File "/tmp/easy_install-18_pb2hu/numpy-1.21.4/tools/cythonize.py", line 193, in process
      processor_function(fromfile, tofile)
    File "/tmp/easy_install-18_pb2hu/numpy-1.21.4/tools/cythonize.py", line 66, in process_pyx
      raise OSError(msg) from e
  OSError: Cython needs to be installed in Python as a module
  Cythonizing sources
  Running from numpy source directory.
  Traceback (most recent call last):
    File "/root/freqtrade/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
      yield saved
    File "/root/freqtrade/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
      yield
    File "/root/freqtrade/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
      _execfile(setup_script, ns)
    File "/root/freqtrade/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
      exec(code, globals, locals)
    File "/tmp/easy_install-18_pb2hu/numpy-1.21.4/setup.py", line 448, in <module>
    File "/tmp/easy_install-18_pb2hu/numpy-1.21.4/setup.py", line 430, in setup_package
    File "/tmp/easy_install-18_pb2hu/numpy-1.21.4/setup.py", line 236, in generate_cython
  RuntimeError: Running cythonize failed!
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-z70dacl4/ta-lib_b437192b935f4021b433ec99e9dd28ce/setup.py", line 184, in <module>
      **requires)
    File "/root/freqtrade/.env/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
      _install_setup_requires(attrs)
    File "/root/freqtrade/.env/lib/python3.7/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
      dist.fetch_build_eggs(dist.setup_requires)
    File "/root/freqtrade/.env/lib/python3.7/site-packages/setuptools/dist.py", line 724, in fetch_build_eggs
      replace_conflicting=True,
    File "/root/freqtrade/.env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
      replace_conflicting=replace_conflicting
    File "/root/freqtrade/.env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1065, in best_match
      return self.obtain(req, installer)
    File "/root/freqtrade/.env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1077, in obtain
      return installer(requirement)
    File "/root/freqtrade/.env/lib/python3.7/site-packages/setuptools/dist.py", line 791, in fetch_build_egg
      return cmd.easy_install(req)
    File "/root/freqtrade/.env/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 704, in easy_install
      return self.install_item(spec, dist.location, tmpdir, deps)
    File "/root/freqtrade/.env/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 730, in install_item
      dists = self.install_eggs(spec, download, tmpdir)
    File "/root/freqtrade/.env/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 915, in install_eggs
      return self.build_and_install(setup_script, setup_base)
    File "/root/freqtrade/.env/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 1183, in build_and_install
      self.run_setup(setup_script, setup_base, args)
    File "/root/freqtrade/.env/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 1169, in run_setup
      run_setup(setup_script, args)
    File "/root/freqtrade/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
      raise
    File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
      self.gen.throw(type, value, traceback)
    File "/root/freqtrade/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
      yield
    File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
      self.gen.throw(type, value, traceback)
    File "/root/freqtrade/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
      saved_exc.resume()
    File "/root/freqtrade/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 141, in resume
      six.reraise(type, exc, self._tb)
    File "/root/freqtrade/.env/lib/python3.7/site-packages/setuptools/_vendor/six.py", line 685, in reraise
      raise value.with_traceback(tb)
    File "/root/freqtrade/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
      yield saved
    File "/root/freqtrade/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
      yield
    File "/root/freqtrade/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
      _execfile(setup_script, ns)
    File "/root/freqtrade/.env/lib/python3.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
      exec(code, globals, locals)
    File "/tmp/easy_install-18_pb2hu/numpy-1.21.4/setup.py", line 448, in <module>
    File "/tmp/easy_install-18_pb2hu/numpy-1.21.4/setup.py", line 430, in setup_package
    File "/tmp/easy_install-18_pb2hu/numpy-1.21.4/setup.py", line 236, in generate_cython
  RuntimeError: Running cythonize failed!
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/40/36/ea7b36b5d46b489d3b7aba4281cb430279ef1980974ea513164e85261547/TA-Lib-0.4.21.tar.gz#sha256=74d2f24ca68aa299275f3179a9adde05cff959f91497e088487d0b5c85104e9f (from https://pypi.org/simple/ta-lib/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement TA-Lib==0.4.21 (from versions: 0.4.9, 0.4.14, 0.4.15, 0.4.16, 0.4.17, 0.4.18, 0.4.19, 0.4.20, 0.4.21)
ERROR: No matching distribution found for TA-Lib==0.4.21_
```
I already tried installing ta_lib from build_helpers but i didn't fix this issue

**Comment by xmatthias** [comment]
I think the information you give here will not suffice to help you properly.

The real problem is with installing numpy - unfortunately, it doesn't include the whole stacktrace - so it's unclear why it tries to compile numpy instead of using the wheels.

The only reason i can think of for this is that it's a system numpy doesn't provide wheels for - which would suggest a arm64 (or some other exotic system architecture)..

What type of system is this? (from an architecture point of view)?

**Comment by fabio1843** [comment]
Th system is a Debian 10 x64 (buster) hosted by vultr. The strange thing is that i already have a freqtrade bot on another instance (installed 10 days ago) and the installation process gone without issues.

**Comment by xmatthias** [comment]
your logs should indicate why installing numpy from wheel didn't work (it's not part of the above snipped though).
I think that's the main part/problem here.

**Comment by arodriguezg98** [comment]
Same here.

**Edit:**

Solved by installing manually ta_lib with pip 21.x version.

```sh
$ python3.7 -m pip install pip --upgrade # ensure last version (I had 18.1)
$ pip3 install ta_lib
```

**Comment by xmatthias** [comment]
18.x is kindof very old .... :laughing: 
makes me wonder how old your python 3.7 version is ... (but that's in reality not my concern).

**Comment by francesco-plt** [comment]
Same problem here on a Raspberry Pi

**Comment by MalchuL** [comment]
You can just append line `${PYTHON} -m pip install --upgrade cython`  before line `${PYTHON} -m pip install --upgrade -r ${REQUIREMENTS} ${REQUIREMENTS_HYPEROPT} ${REQUIREMENTS_PLOT}` inside `updateenv()` function in `setup.sh` file  and rerun your script. In simple words you should install cython package before TA-Lib installation.
