### ISSUE TITLE
VolumePairList does not work for AscendEX (maybe not generic exchanges at all)

### ISSUE THREAD

**Issue by nateemma** [freqtrade/freqtrade#5848]
## Describe your environment

  * Operating system: *macOS*
  * Python Version: *Python 3.9.6*
  * CCXT version: *ccxt==1.60.11*
  * Freqtrade Version: *freqtrade develop-781f8a059*
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

When using exchange ascendex, use of VolumePairList causes a crash if a static pair list is defined and returns nothing at all if there is no static pair list. The 'problem' area in the code is in the generic exchange module (more below). The same does not happen for exchanges that have specific modules (I tested binanceus, ftx and kucoin).

I modified the code to avoid the problem, so I can run, but the pair list is not sorted so it's not  good long term solution.

I understand that AscendEX is not directly supported, I am only submitting this because it appears to be a generic problem.

### Steps to reproduce:

  1. create a config file for ascendex that has a static pair list and VolumePairList included
  2. run *freqtrade test-pairlist* (or *freqtrade trade*)
  3. the python will generate an exception (details below)

Note that I also tried running without a static pair list at all, but the VolumePairList just returns an empty list.

The exact same configuration file (with exchange name changed) works just fine (either way) for binanceus, ftx and kucoin. I suspect that it is something to do with running the generic exchange code, but it could be that AscendEX doesn't support something in the API.
  
### Observed Results:

  * What happened?
  test-pairlist (or trade) crashes when VolumePairList used in combination with static pair list, or empty list returned without static pair list
  * What did you expect to happen?
  return a sorted list of pairs with highest volume

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
(.env) [freqtrade]$ freqtrade test-pairlist -c config_ascendex.json 
2021-11-05 11:04:43,407 - freqtrade.configuration.configuration - INFO - Using config: config_ascendex.json ...
2021-11-05 11:04:43,408 - freqtrade.loggers - INFO - Verbosity set to 0
2021-11-05 11:04:43,408 - freqtrade.configuration.configuration - INFO - Using user-data directory: /Users/philprice95/Documents/Nateemma/freqtrade/user_data ...
2021-11-05 11:04:43,409 - freqtrade.configuration.configuration - INFO - Using data directory: /Users/philprice95/Documents/Nateemma/freqtrade/user_data/data/ascendex ...
2021-11-05 11:04:43,409 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2021-11-05 11:04:43,411 - freqtrade.configuration.check_exchange - WARNING - Exchange "ascendex" is known to the the ccxt library, available for the bot, but not officially supported by the Freqtrade development team. It may work flawlessly (please report back) or have serious issues. Use it at your own discretion.
2021-11-05 11:04:43,411 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2021-11-05 11:04:43,411 - freqtrade.configuration.deprecated_settings - WARNING - DEPRECATED: The `ask_strategy.use_sell_signal` setting is deprecated and will be removed in the next versions of Freqtrade. Please use the `use_sell_signal` setting in your configuration instead.
2021-11-05 11:04:43,411 - freqtrade.configuration.deprecated_settings - WARNING - DEPRECATED: The `ask_strategy.sell_profit_only` setting is deprecated and will be removed in the next versions of Freqtrade. Please use the `sell_profit_only` setting in your configuration instead.
2021-11-05 11:04:43,411 - freqtrade.configuration.deprecated_settings - WARNING - DEPRECATED: The `ask_strategy.ignore_roi_if_buy_signal` setting is deprecated and will be removed in the next versions of Freqtrade. Please use the `ignore_roi_if_buy_signal` setting in your configuration instead.
2021-11-05 11:04:43,412 - freqtrade.configuration.deprecated_settings - WARNING - DEPRECATED: Setting 'protections' in the configuration is deprecated.
2021-11-05 11:04:43,412 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2021-11-05 11:04:43,415 - freqtrade.resolvers.exchange_resolver - INFO - No Ascendex specific subclass found. Using the generic class instead.
2021-11-05 11:04:43,416 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2021-11-05 11:04:43,416 - freqtrade.exchange.exchange - INFO - Using CCXT 1.60.11
2021-11-05 11:04:43,416 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2021-11-05 11:04:43,418 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 200}
2021-11-05 11:04:43,420 - freqtrade.exchange.exchange - INFO - Using Exchange "AscendEX"
2021-11-05 11:04:43,423 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from '/Users/philprice95/Documents/Nateemma/freqtrade/freqtrade/plugins/pairlist/StaticPairList.py'...
2021-11-05 11:04:43,425 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist VolumePairList from '/Users/philprice95/Documents/Nateemma/freqtrade/freqtrade/plugins/pairlist/VolumePairList.py'...
2021-11-05 11:04:43,428 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist SpreadFilter from '/Users/philprice95/Documents/Nateemma/freqtrade/freqtrade/plugins/pairlist/SpreadFilter.py'...
2021-11-05 11:04:43,432 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist PriceFilter from '/Users/philprice95/Documents/Nateemma/freqtrade/freqtrade/plugins/pairlist/PriceFilter.py'...
2021-11-05 11:04:43,435 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist RangeStabilityFilter from '/Users/philprice95/Documents/Nateemma/freqtrade/freqtrade/plugins/pairlist/rangestabilityfilter.py'...
2021-11-05 11:04:43,437 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist VolatilityFilter from '/Users/philprice95/Documents/Nateemma/freqtrade/freqtrade/plugins/pairlist/VolatilityFilter.py'...
2021-11-05 11:04:43,438 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist AgeFilter from '/Users/philprice95/Documents/Nateemma/freqtrade/freqtrade/plugins/pairlist/AgeFilter.py'...
2021-11-05 11:04:46,632 - freqtrade.exchange.exchange - INFO - Markets were not loaded. Loading them now..
2021-11-05 11:04:48,977 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/Users/philprice95/Documents/Nateemma/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/Users/philprice95/Documents/Nateemma/freqtrade/freqtrade/commands/pairlist_commands.py", line 30, in start_test_pairlist
    pairlists.refresh_pairlist()
  File "/Users/philprice95/Documents/Nateemma/freqtrade/freqtrade/plugins/pairlistmanager.py", line 88, in refresh_pairlist
    pairlist = pairlist_handler.filter_pairlist(pairlist, tickers)
  File "/Users/philprice95/Documents/Nateemma/freqtrade/freqtrade/plugins/pairlist/VolumePairList.py", line 204, in filter_pairlist
    sorted_tickers = sorted(filtered_tickers, reverse=True, key=lambda t: t[self._sort_key])
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
  ```

a snippet of the code from VolumePairList.py,  is given below:

```
        if self._min_value > 0:
            filtered_tickers = [
                v for v in filtered_tickers if v[self._sort_key] > self._min_value]

        sorted_tickers = sorted(filtered_tickers, reverse=True, key=lambda t: t[self._sort_key])

        # Validate whitelist to only have active market pairs
        pairs = self._whitelist_for_active_markets([s['symbol'] for s in sorted_tickers])
        pairs = self.verify_blacklist(pairs, partial(self.log_once, logmethod=logger.info))
        # Limit pairlist to the requested number of pairs
        pairs = pairs[:self._number_pairs]


        self.log_once(f"Searching {self._number_pairs} pairs: {pairs}", logger.info)

        return pairs
```

It appears that *filtered_tickers* contains entries of different types, so "<" is meaningless

The comments state that the original list of tickers is provided by *exchange.get_tickers()*, I'll try to look into that more, but I looked the structure and it appeared to be valid (meaning no obvious errors or nil entries)...

Also, it appears that Python 3 differs from Python 2 here, in that dicts are no longer 'order-able', so Python is trying to do a "<" operation between two entries that are not the same type (so a field may be interpreted as 'NoneType').

My temporary workaround is:

```
        # sorted_tickers = sorted(filtered_tickers, reverse=True, key=lambda t: t[self._sort_key])
        sorted_tickers = filtered_tickers

```
I also added in  *{"method": "ShuffleFilter"},* to the config file to mix things up a little, because of the lack of sorting

A subset of the config file is below:

```
  "exchange": {
    "name": "ascendex",
    "key": "",
    "secret": "",
    "ccxt_config": {
      "enableRateLimit": true
    },
    "ccxt_async_config": {
      "enableRateLimit": true,
      "rateLimit": 200
    },
    "pair_whitelist": [
      "1INCH/USDT",
      "AAVE/USDT",
      "ABBC/USDT",
      "ADA/USDT",
      "ADEL/USDT",
      "AERGO/USDT",
      "AGS/USDT",
      "AKRO/USDT",
      "AKT/USDT",
      "ALGO/USDT",
      "ANKR/USDT",
      "ASD/USDT",
      "ASDP/USDT",
      "ATLAS/USDT",
      "ATOM/USDT",
      "AVAX/USDT",
      "AXS/USDT",
      "BAND/USDT",
      "BAT/USDT",
      "BCH/USDT",
      "BEAR/USDT",
      "BEPRO/USDT",
      "BNB/USDT",
      "BOLT/USDT",
      "BONDED/USDT",
      "BSV/USDT",
             :
             : (list shortened for readability)
             :
    ],
    "pair_blacklist": [
      ".*(BNB)/.*",
      ".*(KCS)/.*",
      ".*(BTC|ETH)/.*",
      ".*(_PREMIUM|BEAR|BULL|DOWN|HALF|HEDGE|UP|[1235][SL])/.*",
      ".*(AUD|BRZ|CAD|CHF|EUR|GBP|HKD|IDRT|JPY|NGN|RUB|SGD|TRY|UAH|USD|ZAR)/.*",
      ".*(BUSD|CUSDT|DAI|PAX|PAXG|SUSD|TUSD|USDC|USDT|VAI)/.*",
      ".*(ACM|AFA|ALA|ALL|APL|ASR|ATM|BAR|CAI|CITY|FOR|GAL|GOZ|IBFK|JUV|LEG|LOCK-1|NAVI|NMR|NOV|OG|PFL|PSG|ROUSH|STV|TH|TRA|UCH|UFC|YBO)/.*",
      ".*(CHZ|CTXC|HBAR|NMR|SHIB|SLP|XVS|ONG)/.*"
    ]
  },
  "pairlists": [
    {
      "method": "StaticPairList"
    },
        {
          "method": "VolumePairList",
          "number_assets": 200,
          "sort_key": "quoteVolume",
          "refresh_period": 1800
        },

    {
      "method": "AgeFilter",
      "min_days_listed": 20
    },
    {
      "method": "SpreadFilter",
      "max_spread_ratio": 0.005
    },
    {
      "method": "PriceFilter",
      "low_price_ratio": 0.002
    },
    {
      "method": "RangeStabilityFilter",
      "lookback_days": 3,
      "min_rate_of_change": 0.1,
      "refresh_period": 1800
    },
    {
      "method": "VolatilityFilter",
      "lookback_days": 3,
      "min_volatility": 0.0,
      "max_volatility": 0.75,
      "refresh_period": 1800
    },
    {"method": "ShuffleFilter"},
    {
      "method": "VolumePairList",
      "number_assets": 100,
      "sort_key": "quoteVolume",
      "refresh_period": 1800
    }
  ],
```

**Comment by xmatthias** [comment]
If you look at the output of `fetch_tickers()` - you'll notice that the key field (`quoteVolume`) is not filled:

```
{'symbol': 'ETH/USDT',
 'timestamp': None,
 'datetime': None,
 'high': 4490.06,
 'low': 4490.06,
 'bid': 4490.81,
 'bidVolume': 2.25,
 'ask': 4490.91,
 'askVolume': 0.055,
 'vwap': None,
 'open': 4561.44,
 'close': 4490.06,
 'last': 4490.06,
 'previousClose': None,
 'change': -71.3799999999992,
 'percentage': -1.5648567119155181,
 'average': 4525.75,
 'baseVolume': 2311.828,
 'quoteVolume': None,
 'info': {'symbol': 'ETH/USDT',
  'open': '4561.44',
  'close': '4490.06',
  'high': '4490.06',
  'low': '4490.06',
  'volume': '2311.828',
  'ask': ['4490.91', '0.055'],
  'bid': ['4490.81', '2.25'],
  'type': 'spot'}}
```

Now this can have 2 reasons - either ccxt is not filling it correctly - or they don't provide this value.

Based on that - i don't think this exchange supports volumepairlist in it's standard mode.

There's other exchanges which act the same - but VolumePairlist has an ["advanced" mode](https://www.freqtrade.io/en/stable/plugins/#volumepairlist-advanced-mode), which should be supported
(it's also in a box at the bottom of this section, that bittrex / gemini don't support standard mode).

I'm not sure why you mention python2 - freqtrade never supported python2 - and the problem you're encountering got nothing to do with dict ordering either.

It's also got nothing to do with "generic" exchange classes or not (bittrex has a subclass, but will still not work in the standard configuration) - but with the data the exchange returns.


Now for the exchange itself - i've never even heared about this exchange, so assume you're the first to use it, which means, you may encounter further errors - so you should be prepared for it - and closely monitor the first trades (potentially even do forcebuy/forcesell to see if everything works correctly).

**Comment by nateemma** [comment]
Thanks for the reply.

I assume VolumePairList is sorting based on volume, which is 'None' so that
explains the error.

The reason for python2 vs python3 was because the specific error (unable to
sort dict) was the most common answer on StackOverflow in response to that
exception.

I happen to have an account on AscendEX for other reasons, so I thought I'd
try it out. I have a dry-run test going right now and it seems to be
working, though there are some strange trades (e.g. trailing_stop sells
that are below the candle value).
Maybe I'll start working on a custom exchange module ;-)

Thanks again,

Phil

P.S. obviously you can close this
