### ISSUE TITLE
ccxt Bitmart 

### ISSUE THREAD

**Issue by fooberichu150** [freqtrade/freqtrade#5871]
## Describe your environment

  * Operating system: Windows 10 Docker Desktop 4.1.1 w/WSL2 running Ubuntu 20.04
  * Python Version: 3.9.7 (per Dockerfile)
  * CCXT version: 1.59.2 (also tried against `develop` image which has `1.60.68`)
  * Freqtrade Version: 2021.10 (also tried against `develop` version)
  
## Describe the problem:

Bot running against Bitmart has been working since last week 11/3 when it was first enabled. Suddenly started failing when trying to load the Market information around 1 am Mountain Time (first occurrence below):

```
2021-11-09 08:17:15,862 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
```

### Steps to reproduce:

  1. Bitmart bot using ccxt
  2. Start bot, wait for it to attempt to load market information
  3. Crash, causes Docker to restart container; rinse and repeat

I have downloaded ccxt 1.60.10 and 1.60.84 javascript versions; both successfully load Bitmart market data without exception. Seems to be an issue with the transpiled Python version, perhaps?

### Observed Results:

  * What happened?
  Endless crash loop
  * What did you expect to happen?
  Bot to load market data and continue processing

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
2021-11-09 08:35:23,448 - freqtrade.exchange.exchange - INFO - Using CCXT 1.59.2
2021-11-09 08:35:23,454 - freqtrade.exchange.exchange - INFO - Using Exchange "BitMart"
2021-11-09 08:35:25,138 - freqtrade.commands.trade_commands - ERROR - 'utf-8' codec can't decode byte 0xa0 in position 14825: invalid start byte
2021-11-09 08:35:25,139 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/freqtrade/freqtrade/worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/freqtrade/freqtrade/freqtradebot.py", line 65, in __init__
    self.exchange = ExchangeResolver.load_exchange(self.config['exchange']['name'], self.config)
  File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 39, in load_exchange
    exchange = Exchange(config, validate=validate)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 150, in __init__
    self._load_markets()
  File "/freqtrade/freqtrade/exchange/exchange.py", line 340, in _load_markets
    self._load_async_markets()
  File "/freqtrade/freqtrade/exchange/exchange.py", line 329, in _load_async_markets
    asyncio.get_event_loop().run_until_complete(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/async_support/base/exchange.py", line 193, in load_markets
    raise e
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/async_support/base/exchange.py", line 189, in load_markets
    result = await self.markets_loading
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/async_support/base/exchange.py", line 178, in load_markets_helper
    currencies = await self.fetch_currencies()
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/async_support/bitmart.py", line 818, in fetch_currencies
    response = await self.publicAccountGetCurrencies(params)
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/async_support/base/exchange.py", line 97, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/async_support/base/exchange.py", line 123, in fetch
    http_response = await response.text()
  File "/home/ftuser/.local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1081, in text
    return self._body.decode(encoding, errors=errors)  # type: ignore
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 14825: invalid start byte
  ```

**Comment by xmatthias** [comment]
This is not something freqtrade can help you with, relly.
It's a invalid response from the exchange - which suggests it's probably an issue / change on the exchange side  (assuming nothing in the environment changed, like an update to either freqtrade or ccxt).

While i can confirm that it's happening - i would not know how to provide a fix for this, so best report this to ccxt.

**edit** seems like it's been reported already https://github.com/ccxt/ccxt/issues/10538

**Comment by fooberichu150** [comment]
> **edit** seems like it's been reported already [ccxt/ccxt#10538](https://github.com/ccxt/ccxt/issues/10538)

Thanks! I went down the path with the ccxt javascript version first, but when that was working, was left a bit flummoxed. Good to know where the issue is originated.

**Comment by xmatthias** [comment]
This is now fixed in the latest ccxt version - you can update to that with `pip install -U ccxt`.
as the linked issue states - it's an issue only in the async version of the ccxt python version - no other version was affected afaik.
