### ISSUE TITLE
Directory `/freqtrade/user_data/user_data` does not exist.  /reload_config on telegram is looking for user_data folder within user_data..

### ISSUE THREAD

**Issue by ppkantorski** [freqtrade/freqtrade#5878]
## Describe your environment

  * Operating system: MacOS Monterey
  * Python Version: 3.10
  * CCXT version: 1.57.3
  * Freqtrade Version: 2021.9 (Docker Image Stable Plot)
  
## Describe the problem:

I recently moved my ft_user_data directory recently (which contains the docker-compose.yml as well as user_data) from my external hard drive to my internal hard drive.  It works fine when running command-line commands however when I use telegram /reload_config I get the following:
  ```
freqtrade  | freqtrade.exceptions.OperationalException: Directory `/freqtrade/user_data/user_data` does not exist. Please use `freqtrade create-userdir` to create a user directory
  ```
I am not sure why it is looking for user_data within the user_data directory.  This sounds like to me it is an issue seperate from me moving my folder.  I also tried recreating the user_data folder with 'create-userdir' and I am again getting the same issue.  Any advice?

### Steps to reproduce:

  1. /reload_config on telegram
  
### Observed Results:

  * What happened?
Reload config failed.  It is looking at the wrong folder.
Bot shuts down, restarts.  Configurations are loaded properly.

  * What did you expect to happen?
 Directory = `/freqtrade/user_data` , no reloading issues.

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
freqtrade  | 2021-11-11 02:30:08,026 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2021.9', state='RUNNING'
freqtrade  | 2021-11-11 02:30:38,134 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2021.9', state='RUNNING'
freqtrade  | 2021-11-11 02:30:53,209 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'reload_config'}
freqtrade  | 2021-11-11 02:30:54,085 - freqtrade.worker - INFO - Changing state to: RELOAD_CONFIG
freqtrade  | 2021-11-11 02:30:54,097 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2021.9', state='RELOAD_CONFIG'
freqtrade  | 2021-11-11 02:30:54,106 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
freqtrade  | 2021-11-11 02:30:54,121 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
freqtrade  | 2021-11-11 02:30:54,124 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.apiserver ...
freqtrade  | 2021-11-11 02:30:54,128 - freqtrade.rpc.api_server.webserver - INFO - Stopping API Server
freqtrade  | 2021-11-11 02:30:54,149 - uvicorn.error - INFO - Shutting down
freqtrade  | 2021-11-11 02:30:54,256 - uvicorn.error - INFO - Waiting for application shutdown.
freqtrade  | 2021-11-11 02:30:54,262 - uvicorn.error - INFO - Application shutdown complete.
freqtrade  | 2021-11-11 02:30:54,265 - uvicorn.error - INFO - Finished server process [1]
freqtrade  | 2021-11-11 02:30:54,268 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.telegram ...
freqtrade  | 2021-11-11 02:30:54,271 - apscheduler.scheduler - INFO - Scheduler has been shut down
freqtrade  | 2021-11-11 02:31:23,164 - freqtrade.configuration.configuration - INFO - Using config: /freqtrade/user_data/config.json ...
freqtrade  | 2021-11-11 02:31:23,177 - freqtrade.loggers - INFO - Verbosity set to 0
freqtrade  | 2021-11-11 02:31:23,179 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
freqtrade  | 2021-11-11 02:31:23,181 - freqtrade.configuration.configuration - INFO - Parameter --db-url detected ...
freqtrade  | 2021-11-11 02:31:23,183 - freqtrade.configuration.configuration - INFO - Dry run is enabled
freqtrade  | 2021-11-11 02:31:23,187 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:////freqtrade/user_data/tradesv3.sqlite"
freqtrade  | 2021-11-11 02:31:23,190 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 1 ...
freqtrade  | chown: cannot access '/freqtrade/user_data/user_data': No such file or directory
freqtrade  | 2021-11-11 02:31:23,217 - freqtrade.configuration.directory_operations - WARNING - Could not chown /freqtrade/user_data/user_data
freqtrade  | 2021-11-11 02:31:23,220 - freqtrade.commands.trade_commands - ERROR - Directory `/freqtrade/user_data/user_data` does not exist. Please use `freqtrade create-userdir` to create a user directory
freqtrade  | 2021-11-11 02:31:23,222 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
freqtrade  | Traceback (most recent call last):
freqtrade  |   File "/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
freqtrade  |     worker.run()
freqtrade  |   File "/freqtrade/freqtrade/worker.py", line 76, in run
freqtrade  |     self._reconfigure()
freqtrade  |   File "/freqtrade/freqtrade/worker.py", line 170, in _reconfigure
freqtrade  |     self._init(True)
freqtrade  |   File "/freqtrade/freqtrade/worker.py", line 49, in _init
freqtrade  |     self._config = Configuration(self._args, None).get_config()
freqtrade  |   File "/freqtrade/freqtrade/configuration/configuration.py", line 42, in get_config
freqtrade  |     self.config = self.load_config()
freqtrade  |   File "/freqtrade/freqtrade/configuration/configuration.py", line 111, in load_config
freqtrade  |     self._process_optimize_options(config)
freqtrade  |   File "/freqtrade/freqtrade/configuration/configuration.py", line 261, in _process_optimize_options
freqtrade  |     self._process_datadir_options(config)
freqtrade  |   File "/freqtrade/freqtrade/configuration/configuration.py", line 196, in _process_datadir_options
freqtrade  |     config['user_data_dir'] = create_userdata_dir(config['user_data_dir'], create_dir=False)
freqtrade  |   File "/freqtrade/freqtrade/configuration/directory_operations.py", line 61, in create_userdata_dir
freqtrade  |     raise OperationalException(
freqtrade  | freqtrade.exceptions.OperationalException: Directory `/freqtrade/user_data/user_data` does not exist. Please use `freqtrade create-userdir` to create a user directory
freqtrade  | 2021-11-11 02:31:23,225 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
freqtrade  | 2021-11-11 02:31:23,227 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
freqtrade  | 2021-11-11 02:31:23,228 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
freqtrade  | 2021-11-11 02:31:23,238 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
  ```

**Comment by ppkantorski** [comment]
One follow-up is that after it fails, it will restart the bot and then load properly.  So I am not quite sure what is going on here; if this is something everyone is experiencing or just me.

```
freqtrade  | 2021-11-11 02:31:23,225 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
freqtrade  | 2021-11-11 02:31:23,227 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
freqtrade  | 2021-11-11 02:31:23,228 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
freqtrade  | 2021-11-11 02:31:23,238 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
freqtrade  | 2021-11-11 02:31:25,040 - freqtrade.worker - INFO - Starting worker 2021.9
freqtrade  | 2021-11-11 02:31:25,040 - freqtrade.configuration.configuration - INFO - Using config: /freqtrade/user_data/config.json ...
freqtrade  | 2021-11-11 02:31:25,047 - freqtrade.loggers - INFO - Verbosity set to 0
freqtrade  | 2021-11-11 02:31:25,048 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
freqtrade  | 2021-11-11 02:31:25,049 - freqtrade.configuration.configuration - INFO - Parameter --db-url detected ...
freqtrade  | 2021-11-11 02:31:25,051 - freqtrade.configuration.configuration - INFO - Dry run is enabled
freqtrade  | 2021-11-11 02:31:25,052 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:////freqtrade/user_data/tradesv3.sqlite"
freqtrade  | 2021-11-11 02:31:25,054 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 1 ...
freqtrade  | 2021-11-11 02:31:25,423 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
freqtrade  | 2021-11-11 02:31:25,425 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/binanceus ...
freqtrade  | 2021-11-11 02:31:25,427 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
```

**Comment by ppkantorski** [comment]
Issue resolved with adding this to the config.json.

"user_data_dir": "/freqtrade/user_data/",

It is kind of strange why this isn't the default folder.  It is using this folder, then adding "/user_data/", I think there might be a bug somewhere in the /configuration.py code.  Anyways, this should do it for now.

**Comment by xmatthias** [comment]
The most likely reason is the docker-compose file you're using.
it'll depend how you're mounting the directory - as well as how you start the bot.

**Comment by ppkantorski** [comment]
I see.  I am using it like this, then using docker-compose up -d from within the user_data directory.

```
---
version: '3'
services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable_plot
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # Build step - only needed when additional dependencies are needed
    #build:
    #   context: .
    #   dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/latest/rest-api/ documentation
    # before enabling this.
    ports:
      - "0.0.0.0:XXXX:XXXX"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy DiamondHandStrategyV4
```

**Comment by xmatthias** [comment]
> from within the user_data directory.

i think this is the main problem.
The way you're mounting the directory (`./user_data`) - the assumption is that you're running the compose-file from outside of the user_data folder (like below):
If you don't - then it'll create another user_data dir to mount in - which will be empty.

the default expects the compose-file to be one level above user_data - but you can simply change the mount point from `"./user_data:/freqtrade/user_data"` to `"./:/freqtrade/user_data"` - mounting the current directory there.

```
.                              
├── docker-compose.yml                                                                                              
├── user_data    
│   ├── data                                                     
│   │   └── binance                                              
│   │       └── ETH_BTC-1h.json
│   ├── hyperopts
│   │   ├── sample_hyperopt_advanced.py
│   │   ├── sample_hyperopt_loss.py        
│   │   └── sample_hyperopt.py
│   ├── notebooks 
│   │   └── strategy_analysis_example.ipynb
│   └── strategies                                               
│       └── sample_strategy.py
(...)
```

**Comment by ppkantorski** [comment]
when I change the directory as you described, I get this error.
`freqtrade  | FileNotFoundError: [Errno 2] No such file or directory: '/freqtrade/user_data/config.json'`

**Comment by xmatthias** [comment]
yeah, because (from a host perspective), your config file is in `user_data/user_data/config.json` - not in `user_data/config.json` - (assume you created it according to the docs). 
Once you start wrong, you'll have to take some time to think how it should be - and then move things as required.

**Comment by ppkantorski** [comment]
im closing this for now.  anyone with similar issues can review what we said.  thanks for the guidance.  to simplify things I ended up just designating the folder, but when i have more time ill try exploring what you suggested more in depth.
