### ISSUE TITLE
Lock pair for x candles after sell

### ISSUE THREAD

**Issue by mkdah90** [freqtrade/freqtrade#5884]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

I red the documentation well about this topic and didn't find my answer
I use trailing stop as the main profit strategy so most of the time the candle that sell the pairs has the same condition I use to buy the pairs

so it's sell the pair and buy it again at the next candle
I need to look it for the next few hours

I used this
if self.config['runmode'].value in ('live', 'dry_run'):
   # fetch closed trades for the last 2 days
    trades = Trade.get_trades([Trade.pair == metadata['pair'],
                               Trade.open_date > datetime.utcnow() - timedelta(days=2),
                               Trade.is_open.is_(False),
                ]).all()
    # Analyze the conditions you'd like to lock the pair .... will probably be different for every strategy
    sumprofit = sum(trade.close_profit for trade in trades)
    if sumprofit < 0:
        # Lock pair for 12 hours
        self.lock_pair(metadata['pair'], until=datetime.now(timezone.utc) + timedelta(hours=12))

but didn't work well

**Comment by mkdah90** [comment]
This is why i get when I try it

2021-11-12 17:59:00,725 - freqtrade.resolvers.iresolver - WARNING - Could not import /root/200-2/user_data/strategies/MovAvr.py due to ''return' outside function (MovAvr.py, line 100)'
2021-11-12 17:59:00,725 - freqtrade.commands.trade_commands - ERROR - Impossible to load Strategy 'MovAvr'. This class does not exist or contains Python code errors.
2021-11-12 17:59:00,725 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/root/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/root/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/root/freqtrade/freqtrade/worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/root/freqtrade/freqtrade/freqtradebot.py", line 60, in __init__
    self.strategy: IStrategy = StrategyResolver.load_strategy(self.config)
  File "/root/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 44, in load_strategy
    strategy: IStrategy = StrategyResolver._load_strategy(
  File "/root/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 212, in _load_strategy
    raise OperationalException(
freqtrade.exceptions.OperationalException: Impossible to load Strategy 'MovAvr'. This class does not exist or contains Python code errors.
(.env) root@MKDah:~/200-2# freqtrade.exceptions.OperationalException: Impossible to load Strategy 'MovAvr'. This class does not exist or contains Python code errors.
freqtrade.exceptions.OperationalException:: command not found

**Comment by xmatthias** [comment]
I'd strongly recommend to read through the documentation from top to bottom at least once - so you know what the capabilities of freqtrade are.

You can lock pairs for X candles wtih the [cooldown protection](https://www.freqtrade.io/en/stable/plugins/#cooldown-period).

Your exception is due to a syntax error - which a good editor will highlight for you.
