### ISSUE TITLE
hello guys,  would you please help me for problem . 

### ISSUE THREAD

**Issue by mehmetaliuluc** [freqtrade/freqtrade#5891]
(.env) mtg@mtgvb:~/freqtrade$ python3.6 ./freqtrade/main.py -c config.json
2021-11-14 12:56:44,962 - freqtrade.configuration - INFO - Verbosity set to 0
2021-11-14 12:56:44,963 - freqtrade.configuration - INFO - Dry run is enabled
2021-11-14 12:56:44,963 - freqtrade.configuration - INFO - Using DB: "sqlite://"
2021-11-14 12:56:44,963 - freqtrade.configuration - INFO - Using max_open_trades: 3 ...
2021-11-14 12:56:44,963 - freqtrade.configuration - INFO - Using data folder: user_data/data/binance ...
2021-11-14 12:56:44,964 - freqtrade.freqtradebot - INFO - Starting freqtrade 0.17.3
2021-11-14 12:56:44,966 - freqtrade.resolvers.strategy_resolver - INFO - Using resolved strategy DefaultStrategy from '/home/mtg/freqtrade/freqtrade/strategy'
2021-11-14 12:56:44,967 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ticker_interval' with value in config file: 5m.
2021-11-14 12:56:44,967 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'trailing_stop' with value in config file: False.
2021-11-14 12:56:44,967 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'40': 0.0, '30': 0.01, '20': 0.02, '0': 0.04}
2021-11-14 12:56:44,967 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ticker_interval: 5m
2021-11-14 12:56:44,968 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.1
2021-11-14 12:56:44,968 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2021-11-14 12:56:44,968 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
2021-11-14 12:56:44,968 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False}
2021-11-14 12:56:44,968 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
2021-11-14 12:56:44,968 - freqtrade.exchange - INFO - Instance is running with dry_run enabled
2021-11-14 12:56:44,968 - freqtrade.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2021-11-14 12:56:44,987 - freqtrade.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': False}
2021-11-14 12:56:45,013 - freqtrade.exchange - INFO - Using Exchange "Binance"
2021-11-14 12:56:48,529 - freqtrade.wallets - INFO - Wallets synced ...
2021-11-14 12:56:48,529 - freqtrade.resolvers.pairlist_resolver - WARNING - Path "user_data/pairlist" does not exist
2021-11-14 12:56:48,534 - freqtrade.resolvers.pairlist_resolver - INFO - Using resolved pairlist StaticPairList from '/home/mtg/freqtrade/freqtrade/pairlist'
2021-11-14 12:56:48,556 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'running'}
2021-11-14 12:56:48,556 - freqtrade.freqtradebot - INFO - Changing state to: RUNNING
2021-11-14 12:56:48,556 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': warning, 'status': 'Dry run is enabled. All trades are simulated.'}
2021-11-14 12:56:48,556 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': custom, 'status': "*Exchange:* `binance`\n*Stake per trade:* `0.05 BTC`\n*Minimum ROI:* `{'40': 0.0, '30': 0.01, '20': 0.02, '0': 0.04}`\n*Ticker Interval:* `5m`\n*Strategy:* `DefaultStrategy`"}
2021-11-14 12:56:48,556 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': "Searching for BTC pairs to buy and sell based on StaticPairList: ['AST/BTC', 'ETC/BTC', 'ETH/BTC', 'EOS/BTC', 'IOTA/BTC', 'LTC/BTC', 'MTH/BTC', 'NCASH/BTC', 'TNT/BTC', 'XMR/BTC', 'XLM/BTC', 'XRP/BTC']"}
2021-11-14 12:56:49,156 - freqtrade.pairlist.IPairList - INFO - Ignoring TNT/BTC from whitelist. Market is not active.
2021-11-14 12:56:49,156 - freqtrade.pairlist.IPairList - INFO - Ignoring NCASH/BTC from whitelist. Market is not active.
2021-11-14 12:56:49,165 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "./freqtrade/main.py", line 49, in main
    state = freqtrade.worker(old_state=state)
  File "/home/mtg/freqtrade/freqtrade/freqtradebot.py", line 122, in worker
    min_secs=min_secs)
  File "/home/mtg/freqtrade/freqtrade/freqtradebot.py", line 134, in _throttle
    result = func(*args, **kwargs)
  File "/home/mtg/freqtrade/freqtrade/freqtradebot.py", line 170, in _process
    self.exchange.refresh_tickers(self.active_pair_whitelist, self.strategy.ticker_interval)
  File "/home/mtg/freqtrade/freqtrade/exchange/__init__.py", line 536, in refresh_tickers
    self.async_get_candles_history(pair_list, ticker_interval))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/mtg/freqtrade/freqtrade/exchange/__init__.py", line 548, in async_get_candles_history
    arrow.utcnow().timestamp and pair in self._klines):
TypeError: '>=' not supported between instances of 'int' and 'method'
2021-11-14 12:56:49,166 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2021-11-14 12:56:49,166 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2021-11-14 12:56:49,166 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

Then - you're using a version that's from roughly 2018 (we actually never had a release 0.17.3). 
Many things have changed since - most likely also this problem was fixed (without even trying to look at what it is).

Based on some more info that's hidden in the log - i know where you got this version from. 
Best either go to their repository (or the course help pages) for support, or install an uptodate version to get help in this repository based on our [documentation](https://www.freqtrade.io/), either with [docker](https://www.freqtrade.io/en/stable/docker_quickstart/) or as [native installation](https://www.freqtrade.io/en/stable/installation/).

I'd also encourage a fresh installation - as i doubt upgrading will be possible without problems - as many many things have changed since.
