### ISSUE TITLE
Unable to Forcebuy

### ISSUE THREAD

**Issue by gdominoni** [freqtrade/freqtrade#5918]
* Operating system: Ubuntu
  * Python Version: 3.8
  * CCXT version: 1.59.2
  * Freqtrade Version: 2021-10
  
2021-11-18 11:20:26,324 - freqtrade.freqtradebot - INFO - Buy signal found: about create a new trade for ETHDOWN/USDT with stake_amount: 50 ...
2021-11-18 11:20:26,628 - freqtrade.rpc.telegram - ERROR - Exception occurred within Telegram module
Traceback (most recent call last):
  File "/home/trading1/freqtrade/.env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 613, in fetch
    response.raise_for_status()
  File "/home/trading1/freqtrade/.env/lib/python3.8/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/trading1/freqtrade/freqtrade/exchange/exchange.py", line 738, in create_order
    order = self._api.create_order(pair, ordertype, side,
  File "/home/trading1/freqtrade/.env/lib/python3.8/site-packages/ccxt/binance.py", line 2406, in create_order
    response = getattr(self, method)(self.extend(request, params))
  File "/home/trading1/freqtrade/.env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 457, in inner
    return entry(_self, **inner_kwargs)
  File "/home/trading1/freqtrade/.env/lib/python3.8/site-packages/ccxt/binance.py", line 4401, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/trading1/freqtrade/.env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 502, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/trading1/freqtrade/.env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 629, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/trading1/freqtrade/.env/lib/python3.8/site-packages/ccxt/binance.py", line 4381, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
  File "/home/trading1/freqtrade/.env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 520, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.ExchangeError: binance {"code":-2010,"msg":"This action disabled is on this account."}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/trading1/freqtrade/freqtrade/rpc/telegram.py", line 71, in wrapper
    return command_handler(self, *args, **kwargs)
  File "/home/trading1/freqtrade/freqtrade/rpc/telegram.py", line 774, in _forcebuy
    self._forcebuy_action(pair, price)
  File "/home/trading1/freqtrade/freqtrade/rpc/telegram.py", line 745, in _forcebuy_action
    self._rpc._rpc_forcebuy(pair, price)
  File "/home/trading1/freqtrade/freqtrade/rpc/rpc.py", line 633, in _rpc_forcebuy
    if self._freqtrade.execute_entry(pair, stakeamount, price, forcebuy=True):
  File "/home/trading1/freqtrade/freqtrade/freqtradebot.py", line 523, in execute_entry
    order = self.exchange.create_order(pair=pair, ordertype=order_type, side="buy",
  File "/home/trading1/freqtrade/freqtrade/exchange/exchange.py", line 756, in create_order
    raise TemporaryError(
freqtrade.exceptions.TemporaryError: Could not place buy order due to ExchangeError. Message: binance {"code":-2010,"msg":"This action disabled is on this account."}

and this is my config:

```
{
    
    "order_types": {
        "buy": "limit",
        "sell": "limit",
        "emergencysell": "market",
        "forcebuy_enable": true,
        "forcebuy": "limit",
        "forcesell": "market",
        "stoploss": "market",
        "stoploss_on_exchange": false,
        "stoploss_on_exchange_interval": 10
    },

    "available_capital": 200,
    "max_open_trades": 5,
    "stake_currency": "USDT",
    "stake_amount": 50,
    "fiat_display_currency": "USD",
    "timeframe": "1h",
    "dry_run": false,
    "cancel_open_orders_on_exit": false,
    "amend_last_stake_amount": true,
    "forcebuy_enable": true,
    
    "process_only_new_candles": false,
    
    "unfilledtimeout": {
        "buy": 10,
        "sell": 30
    },
    "bid_strategy": {
        "ask_last_balance": 0.0,
        "use_order_book": false,
        "order_book_top": 1,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "ask_strategy":{
        "use_order_book": false,
        "order_book_min": 1,
        "order_book_max": 9
    },
    
    "pairlists": [

        {
            "method": "StaticPairList",
        },
        
        {
            "method": "RangeStabilityFilter",
            "lookback_days": 1,
            "min_rate_of_change": 0.01,
            "refresh_period": 86400
        },
        {
            "method": "AgeFilter",
            "min_day_listed": 10
        }
        
    ],
    
    "exchange": {
        "name": "binance",
        "key": "xxx",
        "secret": "xxx",
        "ccxt_config": {},
        "ccxt_async_config": {
        },
        "pair_whitelist": [
            ".*DOWN/USDT"
            

        ],
        "pair_blacklist": [
            ".*BEAR/USDT",
            ".*BULL/USDT",
            ".*USD/USDT",
            "USDC/USDT"
        ]
    },
    
    

    "edge": {
        "enabled": false,
        "process_throttle_secs": 3600,
        "calculate_since_number_of_days": 7,
        "allowed_risk": 0.01,
        "stoploss_range_min": -0.002,
        "stoploss_range_max": -0.01,
        "stoploss_range_step": -0.001,
        "minimum_winrate": 0.60,
        "minimum_expectancy": 0.20,
        "min_trade_number": 10,
        "max_trade_duration_minute": 1440,
        "remove_pumps": false
    },
    "telegram": {
        "enabled": true,
        "token": "xxx",
        "chat_id": "644962706"
    },
    "api_server": {
        "enabled": false,
        "listen_ip_address": "127.0.0.1",
        "listen_port": 8080,
        "verbosity": "error",
        "jwt_secret_key": "somethingrandom",
        "CORS_origins": [],
        "username": "freqtrader",
        "password": "SuperSecurePassword"
    },

    "initial_state": "running",
    "internals": {
        "process_throttle_secs": 60
    }
}
```
Thank you!

**Comment by xmatthias** [comment]
> `ccxt.base.errors.ExchangeError: binance {"code":-2010,"msg":"This action disabled is on this account."}`


Please make sure that trading is actually enabled on the API keys you're using.... 
The error suggests that it's not - so it's not really a forcebuy issue, but would be a generic issue with creating an order.

Also (and this is important for all leveraged (.*DONW | .*UP) pairs - make sure to go to that pair's page, and confirm / aknowledge that you understand the risk of trading these pairs.

**Comment by gdominoni** [comment]
I am wrong or you are the same person who answer to my other issue yesterday? :D In that case, thank you already twice.

It was exactly that, it was the questionnaire, I did not know I had to pass a test to be approved :) Thank you!
