### ISSUE TITLE
How to Hyperopt related parameters?

### ISSUE THREAD

**Issue by Niqnil** [freqtrade/freqtrade#5923]
## Describe your environment

  * Docker image: freqtradeorg/freqtrade:develop_plot
  * Python Version: Python 3.9.7
  * Freqtrade Version: freqtrade docker-63f4221f
  
If my strategy is something like this and I want to hyperopt for EMA timeperiod and the EMA ROC timeperiod (parameter based on another parameter). And hyperopt for the same timeperiod for ADX and MINUS_DI, how should I do it?
```
def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        dataframe.loc[
            (
                (dataframe['ema_fast_roc'] >= dataframe['ema_fast_roc'].shift(1).rolling(15).max()) & 
                (dataframe['adx'] >= dataframe['minus_di']) &  
                # ...
```

Do I nest them in for loops like so? Do I declare each as a `Parameter` so I can access them in `populate_buy_trend` using `self.buy_minus_di.value` `self.buy_ema_fast_roc.value`?
```
    buy_ema_fast = IntParameter(2, 10, default = 5, space = "buy")
    buy_ema_fast_roc_period = IntParameter(2, 30, default = 15, space = "buy")
    buy_adx = IntParameter(5, 25, default = 14, space = "buy")
    buy_minus_di = buy_adx # Do I need to declare a variable? Can I reference buy_adx since I want the same timeperiod?
    buy_ema_fast_roc.value = # ?

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        
        for val in self.buy_adx.range:
            dataframe[f'adx_{val}'] = ta.ADX(dataframe, timeperiod=val)
            dataframe[f'minus_di_{val}'] = ta.MINUS_DI(dataframe, timeperiod=val)

        for val in self.buy_ema_fast.range:
            dataframe[f'ema_fast_{val}'] = ta.EMA(dataframe, timeperiod=val)
            dataframe[f'ema_fast_{val}_roc'] = ta.ROC(dataframe[f'ema_fast_{val}'], timeperiod=1)
            for v in self.buy_ema_fast_roc_period.range:
                dataframe[f'buy_ema_fast_{val}_roc_period_{v}'] = dataframe[f'ema_fast_{val}_roc'].shift(1).rolling(v).max()
        # ...
```

**Comment by xmatthias** [comment]
If you want both values to be the same, just use the same .. 

in the end, it's all just variables - so how you use it is up to you ... obviously, it's also up to you to still know why you did what a week/month/year from now ... 😆 so maybe a comment "this is used for both because of ..." might help in that regards

the way you're calculating the values, you'll probably have to nest the loops - but you'll have to be VERY careful with space range - as the spaces will mutiply (so 10 possible values in each of the 2 parameters will result in 10x10 = 100 new columns) - which will obviously have a impact on performance / memory consumption.

**Comment by Niqnil** [comment]
Thanks for the tips!

On starting the docker container, I'm getting a traceback that does not show the code line in strategy. As it says `'name 'self' is not defined'`, I think it is because of my plot_config. How can I access the hyperopt-values for plotting?

```
plot_config = {
        # ...
            "BUY_DMI(14,14)": {
                f'buy_adx_{self.buy_adx_period.value}': {'color': 'orange'},
                f'buy_plus_di__{self.buy_adx_period.value}': {'color': 'green'},
                f'buy_minus_di__{self.buy_adx_period.value}': {'color': 'red'},
                # ...
```

## Traceback
```
2021-11-22 10:41:11,648 - freqtrade.worker - INFO - Starting worker docker-63f4221f
2021-11-22 10:41:11,648 - freqtrade.configuration.configuration - INFO - Using config: /freqtrade/user_data/config.json ...
2021-11-22 10:41:11,648 - freqtrade.configuration.configuration - INFO - Using config: /freqtrade/user_data/config-private.json ...
2021-11-22 10:41:11,649 - freqtrade.loggers - INFO - Verbosity set to 0
2021-11-22 10:41:11,651 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
2021-11-22 10:41:11,651 - freqtrade.configuration.configuration - INFO - Parameter --db-url detected ...
2021-11-22 10:41:11,651 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2021-11-22 10:41:11,652 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:////freqtrade/user_data/tradesv3.sqlite"
2021-11-22 10:41:11,652 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 8 ...
2021-11-22 10:41:11,663 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2021-11-22 10:41:11,663 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/ftx ...
2021-11-22 10:41:11,664 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2021-11-22 10:41:11,669 - freqtrade.configuration.check_exchange - INFO - Exchange "ftx" is officially supported by the Freqtrade development team.
2021-11-22 10:41:11,669 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2021-11-22 10:41:11,669 - freqtrade.freqtradebot - INFO - Starting freqtrade docker-63f4221f
2021-11-22 10:41:11,689 - freqtrade.resolvers.iresolver - WARNING - Could not import /freqtrade/user_data/strategies/TripleMA.py due to 'name 'self' is not defined'
2021-11-22 10:41:11,689 - freqtrade.commands.trade_commands - ERROR - Impossible to load Strategy 'TripleMA'. This class does not exist or contains Python code errors.
2021-11-22 10:41:11,689 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/freqtrade/freqtrade/worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/freqtrade/freqtrade/freqtradebot.py", line 60, in __init__
    self.strategy: IStrategy = StrategyResolver.load_strategy(self.config)
  File "/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 44, in load_strategy
    strategy: IStrategy = StrategyResolver._load_strategy(
  File "/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 216, in _load_strategy
    raise OperationalException(
freqtrade.exceptions.OperationalException: Impossible to load Strategy 'TripleMA'. This class does not exist or contains Python code errors.
```

**Comment by xmatthias** [comment]
it's not really something that's supported / has been tried before, but you should be able to define plot-config as a property, which will give you access to this.

```
@property
def plot_config(self):
    return {
        // ... whatever you need here
  }
```

*note* i did not really test this, but i currently can't imagine why it should fail. Best let me know if it works, so we can add it to the documentation eventually.

**Comment by Niqnil** [comment]
> it's not really something that's supported / has been tried before, but you should be able to define plot-config as a property, which will give you access to this.
> 
> ```
> @property
> def plot_config(self):
>     return {
>         // ... whatever you need here
>   }
> ```
> 
> _note_ i did not really test this, but i currently can't imagine why it should fail. Best let me know if it works, so we can add it to the documentation eventually.

I have tested that this works with f-string for hyperopt and plotting.
```
@property
    def plot_config(self):
        return {
        'main_plot': {
            f'buy_bb-{self.buy_bb_length.value}-{self.buy_bb_std.value}_upper': {'color': 'green'},
            ...etc

```
