### ISSUE TITLE
ERROR - (unicode error) \N escapes not supported (can't load unicodedata module) (telegram.py, line 214)

### ISSUE THREAD

**Issue by usingamgad** [freqtrade/freqtrade#5956]
* Operating system: Mac OS Monterey (M1)
  * Python Version:  Python 3.8.12
  * CCXT version: ccxt==1.62.9
  * Freqtrade Version: freqtrade 2021.10
  

When running freqtrade trade --config config.json --strategy SampleStrategy with telegram enabled I receive the following error

Traceback (most recent call last):
  File "/Users/amgad/Documents/cryptotrader/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/Users/amgad/Documents/cryptotrader/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/Users/amgad/Documents/cryptotrader/freqtrade/freqtrade/worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/Users/amgad/Documents/cryptotrader/freqtrade/freqtrade/freqtradebot.py", line 80, in __init__
    self.rpc: RPCManager = RPCManager(self)
  File "/Users/amgad/Documents/cryptotrader/freqtrade/freqtrade/rpc/rpc_manager.py", line 27, in __init__
    from freqtrade.rpc.telegram import Telegram
  File "/Users/amgad/Documents/cryptotrader/freqtrade/freqtrade/rpc/telegram.py", line 214
    f"\N{LARGE BLUE CIRCLE} *{msg['exchange']}:* Buying {msg['pair']}"
    ^
SyntaxError: (unicode error) \N escapes not supported (can't load unicodedata module)

### Steps to reproduce:

  1. Create new configuration with telegram token and chat id
  2. Run freqtrade with new configuration and sample strategy
  
### Observed Results:

ERROR - (unicode error) \N escapes not supported (can't load unicodedata module) (telegram.py, line 214)

### Relevant code exceptions or logs

  ```
2021-11-23 20:29:35,801 - freqtrade.worker - INFO - Starting worker 2021.10
2021-11-23 20:29:35,801 - freqtrade.configuration.configuration - INFO - Using config: config.json ...
2021-11-23 20:29:35,802 - freqtrade.loggers - INFO - Verbosity set to 0
2021-11-23 20:29:35,803 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
2021-11-23 20:29:35,803 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2021-11-23 20:29:35,803 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:///tradesv3.dryrun.sqlite"
2021-11-23 20:29:35,803 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 3 ...
2021-11-23 20:29:35,803 - freqtrade.configuration.configuration - INFO - Using user-data directory: /Users/amgad/Documents/cryptotrader/freqtrade/user_data ...
2021-11-23 20:29:35,803 - freqtrade.configuration.configuration - INFO - Using data directory: /Users/amgad/Documents/cryptotrader/freqtrade/user_data/data/binance ...
2021-11-23 20:29:35,803 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2021-11-23 20:29:35,808 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2021-11-23 20:29:35,808 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2021-11-23 20:29:35,808 - freqtrade.freqtradebot - INFO - Starting freqtrade 2021.10
2021-11-23 20:29:35,850 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy SampleStrategy from '/Users/amgad/Documents/cryptotrader/freqtrade/user_data/strategies/sample_strategy.py'...
2021-11-23 20:29:35,850 - freqtrade.strategy.hyper - INFO - Found no parameter file.
2021-11-23 20:29:35,850 - freqtrade.strategy.hyper - INFO - No params for buy found, using default values.
2021-11-23 20:29:35,850 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): buy_rsi = 30
2021-11-23 20:29:35,850 - freqtrade.strategy.hyper - INFO - No params for sell found, using default values.
2021-11-23 20:29:35,850 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): sell_rsi = 70
2021-11-23 20:29:35,850 - freqtrade.strategy.hyper - INFO - No params for protection found, using default values.
2021-11-23 20:29:35,850 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2021-11-23 20:29:35,850 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 100.
2021-11-23 20:29:35,850 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'buy': 10, 'sell': 30, 'unit': 'minutes'}.
2021-11-23 20:29:35,850 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'60': 0.01, '30': 0.02, '0': 0.04}
2021-11-23 20:29:35,850 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 5m
2021-11-23 20:29:35,850 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.1
2021-11-23 20:29:35,850 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2021-11-23 20:29:35,850 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2021-11-23 20:29:35,850 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2021-11-23 20:29:35,850 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2021-11-23 20:29:35,850 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
2021-11-23 20:29:35,850 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'market', 'stoploss_on_exchange': False}
2021-11-23 20:29:35,850 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
2021-11-23 20:29:35,850 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2021-11-23 20:29:35,850 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 100
2021-11-23 20:29:35,850 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2021-11-23 20:29:35,851 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 30
2021-11-23 20:29:35,851 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'buy': 10, 'sell': 30, 'unit': 'minutes'}
2021-11-23 20:29:35,851 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_sell_signal: True
2021-11-23 20:29:35,851 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_only: False
2021-11-23 20:29:35,851 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_buy_signal: False
2021-11-23 20:29:35,851 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_offset: 0.0
2021-11-23 20:29:35,851 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2021-11-23 20:29:35,851 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2021-11-23 20:29:35,851 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2021-11-23 20:29:35,853 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2021-11-23 20:29:35,853 - freqtrade.exchange.exchange - INFO - Using CCXT 1.62.9
2021-11-23 20:29:35,861 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2021-11-23 20:29:37,447 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2021-11-23 20:29:37,476 - freqtrade.wallets - INFO - Wallets synced.
2021-11-23 20:29:37,477 - freqtrade.plugins.protectionmanager - INFO - No protection Handlers defined.
2021-11-23 20:29:37,952 - freqtrade.rpc.rpc_manager - INFO - Enabling rpc.telegram ...
2021-11-23 20:29:37,957 - freqtrade.commands.trade_commands - ERROR - (unicode error) \N escapes not supported (can't load unicodedata module) (telegram.py, line 214)
2021-11-23 20:29:37,957 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/Users/amgad/Documents/cryptotrader/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/Users/amgad/Documents/cryptotrader/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/Users/amgad/Documents/cryptotrader/freqtrade/freqtrade/worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/Users/amgad/Documents/cryptotrader/freqtrade/freqtrade/freqtradebot.py", line 80, in __init__
    self.rpc: RPCManager = RPCManager(self)
  File "/Users/amgad/Documents/cryptotrader/freqtrade/freqtrade/rpc/rpc_manager.py", line 27, in __init__
    from freqtrade.rpc.telegram import Telegram
  File "/Users/amgad/Documents/cryptotrader/freqtrade/freqtrade/rpc/telegram.py", line 214
    f"\N{LARGE BLUE CIRCLE} *{msg['exchange']}:* Buying {msg['pair']}"
    ^
SyntaxError: (unicode error) \N escapes not supported (can't load unicodedata module)  ```

**Comment by xmatthias** [comment]
this is not an easy problem i'll fear - and not one we'll be able to fix.

This is working fine on my system - as well as in the test suite (which means it'll also work across different python versions, and operating systems (including windows - which can sometimes be surprising).

If you search around the internet for the exception (`SyntaxError: (unicode error) \N escapes not supported (can't load unicodedata module)`) - you'll find several random failures on this, but no real solution.

You can also try to run a python shell - and execute ` f"\N{LARGE BLUE CIRCLE}"` to check if this is working in general (it should - otherwise your python install is broken).
I've now tested the line given above on python3.9 and python3.7 (don't have a 3.8 around, but i don't see why that should not be working).

I think it's a system problem - but i'm not sure what/how to look at fixing that.

How did you install your python version? 
is it running in rosetta, or natively on the M1?

**Comment by xmatthias** [comment]
Closing this as i think your question has been answered.

Feel free to comment below / reopen if it's still unclear.
