### ISSUE TITLE
invalid HTTP request received

### ISSUE THREAD

**Issue by zorann** [freqtrade/freqtrade#5967]
## Describe your environment

  * Operating system: ____Linux
  * Python Version: _____3.6.8 (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____freqtrade docker-88047459 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*
I got these errors all the time.
2021-11-25 10:40:56,456 - uvicorn.error - WARNING - Invalid HTTP request received.
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 136, in handle_events
    event = self.conn.next_event()
  File "/home/ftuser/.local/lib/python3.9/site-packages/h11/_connection.py", line 443, in next_event
    exc._reraise_as_remote_protocol_error()
  File "/home/ftuser/.local/lib/python3.9/site-packages/h11/_util.py", line 76, in _reraise_as_remote_protocol_error
    raise self
  File "/home/ftuser/.local/lib/python3.9/site-packages/h11/_connection.py", line 425, in next_event
    event = self._extract_next_receive_event()
  File "/home/ftuser/.local/lib/python3.9/site-packages/h11/_connection.py", line 367, in _extract_next_receive_event
    event = self._reader(self._receive_buffer)
  File "/home/ftuser/.local/lib/python3.9/site-packages/h11/_readers.py", line 203, in expect_nothing
    raise LocalProtocolError("Got data when expecting EOF")
h11._util.RemoteProtocolError: Got data when expecting EOF

**Comment by xmatthias** [comment]
This message is caused by something connecting to the bot API, but talking the wrong protocol.

This suggests that you're exposing the bot API towards the internet (or you have locally something running that tries to connect to the bot port with a different protocol).
This will cause "free penetration tests" - of random people/bots testing for diverse vulnerabilities.

Our documentation clearly advises against running the API on the open internet - and in the local case, you should be able to get araound this by using a different port in your configuration.
