### ISSUE TITLE
ArrayMemoryError during HyperOpt

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#5985]
## Describe your environment

  * Operating system: Windows Server 2022 (Miniconda)
  * Python Version: 3.95_____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2021.10 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

For the first time I get a ArrayMemoryError during HyperOpt, even when I allocate 60 GB RAM to the VM. Do you need further information, or is there an option, to specify memory handling in detail prior to HyperOpt?
I allow HyperOpt to use 20 parallel workers.

The message:

2021-11-28 09:43:37,534 - freqtrade - ERROR - Fatal exception!
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\a2\.conda\envs\freqtrade\lib\site-packages\joblib\externals\loky\process_executor.py", line 436, in _process_worker
    r = call_item()
  File "C:\Users\a2\.conda\envs\freqtrade\lib\site-packages\joblib\externals\loky\process_executor.py", line 288, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "C:\Users\a2\.conda\envs\freqtrade\lib\site-packages\joblib\_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "C:\Users\a2\.conda\envs\freqtrade\lib\site-packages\joblib\parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "C:\Users\a2\.conda\envs\freqtrade\lib\site-packages\joblib\parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "C:\Users\a2\.conda\envs\freqtrade\lib\site-packages\joblib\externals\loky\cloudpickle_wrapper.py", line 38, in __call__
    return self._obj(*args, **kwargs)
  File "c:\users\a2\freqtrade\freqtrade\optimize\hyperopt.py", line 310, in generate_optimizer
    processed = load(f, mmap_mode='r')
  File "C:\Users\a2\.conda\envs\freqtrade\lib\site-packages\joblib\numpy_pickle.py", line 577, in load
    obj = _unpickle(fobj)
  File "C:\Users\a2\.conda\envs\freqtrade\lib\site-packages\joblib\numpy_pickle.py", line 506, in _unpickle
    obj = unpickler.load()
  File "C:\Users\a2\.conda\envs\freqtrade\lib\pickle.py", line 1212, in load
    dispatch[key[0]](self)
  File "C:\Users\a2\.conda\envs\freqtrade\lib\site-packages\joblib\numpy_pickle.py", line 344, in load_build
    self.stack.append(array_wrapper.read(self))
  File "C:\Users\a2\.conda\envs\freqtrade\lib\site-packages\joblib\numpy_pickle.py", line 189, in read
    array = self.read_array(unpickler)
  File "C:\Users\a2\.conda\envs\freqtrade\lib\site-packages\joblib\numpy_pickle.py", line 134, in read_array
    array = unpickler.np.empty(count, dtype=self.dtype)
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 3.64 MiB for an array with shape (476946,) and data type float64
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\a2\freqtrade\freqtrade\main.py", line 37, in main
    return_code = args['func'](args)
  File "c:\users\a2\freqtrade\freqtrade\commands\optimize_commands.py", line 87, in start_hyperopt
    hyperopt.start()
  File "c:\users\a2\freqtrade\freqtrade\optimize\hyperopt.py", line 476, in start
    f_val = self.run_optimizer_parallel(parallel, asked, i)
  File "c:\users\a2\freqtrade\freqtrade\optimize\hyperopt.py", line 390, in run_optimizer_parallel
    return parallel(delayed(
  File "C:\Users\a2\.conda\envs\freqtrade\lib\site-packages\joblib\parallel.py", line 1056, in __call__
    self.retrieve()
  File "C:\Users\a2\.conda\envs\freqtrade\lib\site-packages\joblib\parallel.py", line 935, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "C:\Users\a2\.conda\envs\freqtrade\lib\site-packages\joblib\_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "C:\Users\a2\.conda\envs\freqtrade\lib\concurrent\futures\_base.py", line 444, in result
    return self.__get_result()
  File "C:\Users\a2\.conda\envs\freqtrade\lib\concurrent\futures\_base.py", line 389, in __get_result
    raise self._exception
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 3.64 MiB for an array with shape (476946,) and data type float64

End of error message

I try to optimize buy signal for the known Strategy004, tell me, if you think, that code structure is affecting above behaviour
I look forward to your feedback.

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
To be honest, all memory-related errors with hyperopt can be worked around with by using any of the methods in the [hyperopt documentation](https://www.freqtrade.io/en/stable/hyperopt/#out-of-memory-errors).

There's nothing to add to this, really - best try reducing either parallelity or timerange - or reduce the space (fewer parameters).
