### ISSUE TITLE
ERROR - Unable to initialize markets.

### ISSUE THREAD

**Issue by YangHgRi** [freqtrade/freqtrade#6001]
2021-11-29 07:05:11,998 - freqtrade.exchange.exchange - ERROR - Unable to initialize markets.
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7fe1eb2bfeb0>, 'Connection to api.binance.com timed out. (connect timeout=10)')

**Comment by YangHgRi** [comment]
because i'm use this in china?bue i had use ShadowsocksR proxy

**Comment by stash86** [comment]
maybe Binance ban any proxy use? Or your proxy has bad connection. Anyway, it's not freqtrade's issue. Nothing can be done

**Comment by YangHgRi** [comment]
> maybe Binance ban any proxy use? Or your proxy has bad connection. Anyway, it's not freqtrade's issue. Nothing can be done

But I can use its official website normally

**Comment by stash86** [comment]
Normal website and API endpoint might have different rules set on them. You would need to ask Binance or the proxy developer about it

**Comment by YangHgRi** [comment]
> Normal website and API endpoint might have different rules set on them. You would need to ask Binance or the proxy developer about it

while,thank u,i'll try

**Comment by isonex** [comment]
It's a problem in a wifi environment.
Wired connection is required.

**Comment by stash86** [comment]
wrong, there is no such thing of wifi vs wired connection

**Comment by isonex** [comment]
I was mistaken.
It works on wifi.^^
