### ISSUE TITLE
freqtrade.commands.trade_commands - ERROR - Exchange Gate.io does not support market orders.

### ISSUE THREAD

**Issue by medenlin** [freqtrade/freqtrade#6005]
## Describe your environment

  * Operating system: Docker under Win10
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2021-11 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

I try to modify strategy file as in https://www.freqtrade.io/en/stable/faq/#im-getting-the-exchange-xxx-does-not-support-market-orders-message-and-cannot-run-my-strategy

order_types = {
        ...
        'stoploss': 'limit',
        ...
   }

but I still see the message:
freqtrade.commands.trade_commands - ERROR - Exchange Gate.io does not support market orders.
full report in attachment
[err.txt](https://github.com/freqtrade/freqtrade/files/7622980/err.txt)
I suspect this is due to a bug in CCXT, but don't know, how to update CCXT in FreqTrade docker container.

**Comment by xmatthias** [comment]
gate.io does in fact not support market orders on spot markets, so there's nothing ccxt (or freqtrade, really) can do about that.

there are more [ordertypes](https://www.freqtrade.io/en/stable/configuration/#understand-order_types) - and the one you're probably missing (and which defaults to market if not specified) is  emergencysell. 
simply adding `"emergencysell": "limit",` should fix this.

**Comment by JaLe29** [comment]
It doesn't work for SampleStrategy (https://github.com/freqtrade/freqtrade/blob/develop/freqtrade/templates/sample_strategy.py#L78)

used:
```
    # Optional order type mapping.
    order_types = {
        "emergencysell": "limit",
        'buy': 'limit',
        'sell': 'limit',
        'stoploss': 'market',
        'stoploss_on_exchange': False
    }

```
Getting an error:
```
2021-11-30 16:31:05,851 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2021-11-30 16:31:05,862 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2021-11-30 16:31:05,863 - freqtrade.exchange.exchange - INFO - Using CCXT 1.62.42
2021-11-30 16:31:05,892 - freqtrade.exchange.exchange - INFO - Using Exchange "Gate.io"
2021-11-30 16:31:10,389 - freqtrade.commands.trade_commands - ERROR - Exchange Gate.io does not support market orders.
2021-11-30 16:31:10,389 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/pi/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/home/pi/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/home/pi/freqtrade/freqtrade/worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/home/pi/freqtrade/freqtrade/freqtradebot.py", line 65, in __init__
    self.exchange = ExchangeResolver.load_exchange(self.config['exchange']['name'], self.config)
  File "/home/pi/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 32, in load_exchange
    exchange = ExchangeResolver._load_exchange(exchange_name,
  File "/home/pi/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 54, in _load_exchange
    exchange = ex_class(**kwargs)
  File "/home/pi/freqtrade/freqtrade/exchange/exchange.py", line 156, in __init__
    self.validate_ordertypes(config.get('order_types', {}))
  File "/home/pi/freqtrade/freqtrade/exchange/gateio.py", line 29, in validate_ordertypes
    super().validate_ordertypes(order_types)
  File "/home/pi/freqtrade/freqtrade/exchange/exchange.py", line 456, in validate_ordertypes
    raise OperationalException(
freqtrade.exceptions.OperationalException: Exchange Gate.io does not support market orders.
```

**Comment by xmatthias** [comment]
Your stoploss type is market (`'stoploss': 'market',`) ... change all types to limit for this to work on gateio.

**Comment by TurBoss** [comment]
hello,

I'm getting the same issue on gate.io

```
2022-02-01 02:40:34,124 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False}
```
....

```
2022-02-01 02:40:34,128 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2022-02-01 02:40:34,128 - freqtrade.exchange.exchange - INFO - Using CCXT 1.71.46
2022-02-01 02:40:34,140 - freqtrade.exchange.exchange - INFO - Using Exchange "Gate.io"
2022-02-01 02:40:38,151 - freqtrade.commands.trade_commands - ERROR - Exchange Gate.io does not support market orders.
2022-02-01 02:40:38,151 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/turboss/Projects/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/home/turboss/Projects/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/home/turboss/Projects/freqtrade/freqtrade/worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/home/turboss/Projects/freqtrade/freqtrade/freqtradebot.py", line 63, in __init__
    self.exchange = ExchangeResolver.load_exchange(self.config['exchange']['name'], self.config)
  File "/home/turboss/Projects/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 32, in load_exchange
    exchange = ExchangeResolver._load_exchange(exchange_name,
  File "/home/turboss/Projects/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 54, in _load_exchange
    exchange = ex_class(**kwargs)
  File "/home/turboss/Projects/freqtrade/freqtrade/exchange/exchange.py", line 160, in __init__
    self.validate_ordertypes(config.get('order_types', {}))
  File "/home/turboss/Projects/freqtrade/freqtrade/exchange/gateio.py", line 30, in validate_ordertypes
    super().validate_ordertypes(order_types)
  File "/home/turboss/Projects/freqtrade/freqtrade/exchange/exchange.py", line 462, in validate_ordertypes
    raise OperationalException(
freqtrade.exceptions.OperationalException: Exchange Gate.io does not support market orders.
(venv) ➜  freqtrade git:(develop) ✗ 
```

thanks

**Comment by TurBoss** [comment]
> gate.io does in fact not support market orders on spot markets, so there's nothing ccxt (or freqtrade, really) can do about that.
> 
> there are more [ordertypes](https://www.freqtrade.io/en/stable/configuration/#understand-order_types) - and the one you're probably missing (and which defaults to market if not specified) is emergencysell. simply adding `"emergencysell": "limit",` should fix this.

this actuallyf ixed thanks

**Comment by stspinu** [comment]
Hi team,

Gateio now supports market orders (starting with v4.34.0), as show on their documentation below:
[LINK](https://www.gate.io/docs/developers/apiv4/en/#changelog)

![image](https://user-images.githubusercontent.com/46924453/226857560-b41c9b9c-edec-49d9-8a21-c4c911b9fa93.png)


Can we somehow use the market order in freqtrade (maybe with the development branch)? If not yet, are there any plans in introduce support for Market Orders? 

Thank you!
