### ISSUE TITLE
frequi trade shows no data

### ISSUE THREAD

**Issue by cospat** [freqtrade/freqtrade#6010]
using latest version of freqtrade, deleted and installed a fresh copy, same results

/work/freqtrade# freqtrade -V
freqtrade develop-f0abe218a

- uvicorn.error - ERROR - Exception in ASGI application
- 
Traceback (most recent call last):
  File "/root/work/freqtrade/.env/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/root/work/freqtrade/.env/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/root/work/freqtrade/.env/lib/python3.8/site-packages/uvicorn/middleware/message_logger.py", line 82, in __call__
    raise exc from None
  File "/root/work/freqtrade/.env/lib/python3.8/site-packages/uvicorn/middleware/message_logger.py", line 78, in __call__
    await self.app(scope, inner_receive, inner_send)
  File "/root/work/freqtrade/.env/lib/python3.8/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/root/work/freqtrade/.env/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/work/freqtrade/.env/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/root/work/freqtrade/.env/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/root/work/freqtrade/.env/lib/python3.8/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/root/work/freqtrade/.env/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/root/work/freqtrade/.env/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/root/work/freqtrade/.env/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/root/work/freqtrade/.env/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/root/work/freqtrade/.env/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/root/work/freqtrade/.env/lib/python3.8/site-packages/fastapi/routing.py", line 234, in app
    response_data = await serialize_response(
  File "/root/work/freqtrade/.env/lib/python3.8/site-packages/fastapi/routing.py", line 137, in serialize_response
    raise ValidationError(errors, field.type_)
pydantic.error_wrappers.ValidationError: 1 validation error for ShowConfig
response -> unfilledtimeout -> sell
  field required (type=value_error.missing)

**Comment by xmatthias** [comment]
Please fill out the issue template. It contains basic information about the version you're using - without it we'll have to assume your version is outdated.

**Comment by cospat** [comment]
![image](https://user-images.githubusercontent.com/52999263/144116230-0495863b-7aa2-4834-8b84-8ec4b7169764.png)
