### ISSUE TITLE
new  "exit_timeout_count" feature

### ISSUE THREAD

**Issue by Prossi79** [freqtrade/freqtrade#6068]
I am just testing the new "exit_timeout_count" feature ... is it working as well in the case of partially filled orders and "stoploss on exchange" enabled?

In my case it seems it doesn't, my bot was struggling "process died". DUSK/BTC sell order was just partially filled and seems the `"exit_timeout_count": 1` was trying to emergency sell, which didn't work.

This is my config setting:

```
     "unfilledtimeout": {
        "buy": 4,
        "sell": 4,
        "exit_timeout_count": 1, //Add Emergencyselling after X timeouts have been reached
        "unit": "minutes"
    },
```

Here are the logs:

```
2021-12-13 16:44:29,336 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'running'}

2021-12-13 16:44:29,754 - freqtrade.worker - INFO - Changing state to: RUNNING

2021-12-13 16:44:29,756 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': "*Exchange:* `binance`\n*Stake per trade:* `unlimited BTC`\n*Minimum ROI:* `{'0': 0.3}`\n*Trailing Stoploss:* `-0.3`\n*Timeframe:* `3m`\n*Strategy:* `BinHV45_BTC_3m_v1`"}

2021-12-13 16:44:29,992 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': "Searching for BTC pairs to buy and sell based on [{'VolumePairList': 'VolumePairList - top 100 volume pairs.'}, {'AgeFilter': 'AgeFilter - Filtering pairs with age less than 7 days'}, {'PrecisionFilter': 'PrecisionFilter - Filtering untradable pairs.'}, {'PriceFilter': 'PriceFilter - Filtering pairs priced below 1.0%.'}, {'SpreadFilter': 'SpreadFilter - Filtering pairs with ask/bid diff above 0.50%.'}, {'PerformanceFilter': 'PerformanceFilter - Sorting pairs by performance.'}]"}

2021-12-13 16:44:30,179 - freqtrade.persistence.models - INFO - Found open trade: Trade(id=1301, pair=DUSK/BTC, amount=6027.40080000, open_rate=0.00000941, open_since=2021-12-13 14:24:25)

2021-12-13 16:44:30,188 - freqtrade.freqtradebot - INFO - Updating 1 open orders.

2021-12-13 16:44:30,439 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=1301, pair=DUSK/BTC, amount=6027.40080000, open_rate=0.00000941, open_since=2021-12-13 14:24:25)

2021-12-13 16:45:12,887 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=1301, pair=DUSK/BTC, amount=6027.40080000, open_rate=0.00000941, open_since=2021-12-13 14:24:25)

2021-12-13 16:45:13,193 - freqtrade.wallets - INFO - Wallets synced.

2021-12-13 16:45:13,195 - freqtrade.freqtradebot - WARNING - Emergencyselling trade Trade(id=1301, pair=DUSK/BTC, amount=6027.40080000, open_rate=0.00000941, open_since=2021-12-13 14:24:25), as the sell order timed out 1 times.

2021-12-13 16:45:13,888 - freqtrade.freqtradebot - ERROR - Could not cancel stoploss order 61852582

Traceback (most recent call last):

  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 615, in fetch

    response.raise_for_status()

  File "/home/ftuser/.local/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status

    raise HTTPError(http_error_msg, response=self)

requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order?timestamp=1639413913202&recvWindow=5000&symbol=DUSKBTC&orderId=61852582&signature=10de8b24df7ae5920df8af88cddcb1bc188b1e13ef5b0276e658cac7255fb567


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/freqtrade/freqtrade/exchange/exchange.py", line 853, in cancel_order

    order = self._api.cancel_order(order_id, pair)

  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/binance.py", line 2623, in cancel_order

    response = getattr(self, method)(self.extend(request, query))

  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 459, in inner

    return entry(_self, **inner_kwargs)

  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/binance.py", line 4551, in request

    response = self.fetch2(path, api, method, params, headers, body, config, context)

  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 504, in fetch2

    return self.fetch(request['url'], request['method'], request['headers'], request['body'])

  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 631, in fetch

    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)

  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/binance.py", line 4531, in handle_errors

    self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)

  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 522, in throw_exactly_matched_exception

    raise exact[string](message)

ccxt.base.errors.OrderNotFound: binance {"code":-2011,"msg":"Unknown order sent."}


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/freqtrade/freqtrade/freqtradebot.py", line 1116, in execute_trade_exit

    co = self.exchange.cancel_stoploss_order_with_result(trade.stoploss_order_id,

  File "/freqtrade/freqtrade/exchange/exchange.py", line 911, in cancel_stoploss_order_with_result

    corder = self.cancel_stoploss_order(order_id, pair)

  File "/freqtrade/freqtrade/exchange/common.py", line 107, in wrapper

    return f(*args, **kwargs)

  File "/freqtrade/freqtrade/exchange/exchange.py", line 857, in cancel_order

    raise InvalidOrderException(

freqtrade.exceptions.InvalidOrderException: Could not cancel order. Message: binance {"code":-2011,"msg":"Unknown order sent."}

2021-12-13 16:45:14,950 - freqtrade.wallets - INFO - Wallets synced.

2021-12-13 16:45:14,951 - freqtrade.commands.trade_commands - ERROR - Not enough amount to sell. Trade-amount: 6027.4008, Wallet: 0.4008

2021-12-13 16:45:14,951 - freqtrade.commands.trade_commands - ERROR - Fatal exception!

Traceback (most recent call last):

  File "/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading

    worker.run()

  File "/freqtrade/freqtrade/worker.py", line 74, in run

    state = self._worker(old_state=state)

  File "/freqtrade/freqtrade/worker.py", line 111, in _worker

    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)

  File "/freqtrade/freqtrade/worker.py", line 132, in _throttle

    result = func(*args, **kwargs)

  File "/freqtrade/freqtrade/worker.py", line 145, in _process_running

    self.freqtrade.process()

  File "/freqtrade/freqtrade/freqtradebot.py", line 171, in process

    self.check_handle_timedout()

  File "/freqtrade/freqtrade/freqtradebot.py", line 929, in check_handle_timedout

    self.execute_trade_exit(trade, order.get('price'), sell_reason=SellCheckTuple(

  File "/freqtrade/freqtrade/freqtradebot.py", line 1131, in execute_trade_exit

    amount = self._safe_exit_amount(trade.pair, trade.amount)

  File "/freqtrade/freqtrade/freqtradebot.py", line 1076, in _safe_exit_amount

    raise DependencyException(

freqtrade.exceptions.DependencyException: Not enough amount to sell. Trade-amount: 6027.4008, Wallet: 0.4008

2021-12-13 16:45:14,951 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit

2021-12-13 16:45:14,951 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}

2021-12-13 16:45:15,117 - freqtrade.freqtradebot - INFO - Cleaning up modules ...

2021-12-13 16:45:15,120 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': warning, 'status': "1 open trades active.\n\nHandle these trades manually on Binance, or '/start' the bot again and use '/stopbuy' to handle open trades gracefully. \n"}

2021-12-13 16:45:15,233 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...

2021-12-13 16:45:15,233 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.apiserver ...```

**Comment by xmatthias** [comment]
it's unclear as of now why freqtrade thinks a sell-order timed out - but then tries to cancel a stoploss order.

Please have a look at the orders table in your database, specifically looking for all orders for this particular trade, so we can have a look in what sequence what happened.

The difference in amount (`Trade-amount: 6027.4008, Wallet: 0.4008`) suggests that there is a order still hanging on the exchange - if your buy order for 6027 filled with 0.4008 - then it'd be dust which you'd not be able to sell on DUSK anyway.

Now freqtrade shouldn't crash for sure - but the whole situation suggests that there's other things (maybe a exchange delay again, where binance struggles to find it's own orders) going on.


partial sell orders are not supported in general - and partial sells will be kept open, and will not be canceled.
