### ISSUE TITLE
Backtesting and hyperoptimization without internet connection.

### ISSUE THREAD

**Issue by C0D3D3V** [freqtrade/freqtrade#6077]
I have now spent several weeks doing automated hyperoptimization in combination with backtesting of hundreds of strategies. (I will of course publish the results after my research).

However, I have now encountered the problem that both the `hyperopt` command and `backtesting` require an internet connection. For some reasons my server does not have internet 24/7, for this reason my automated testing keeps getting interrupted. 

It would be nice if there is a way to use these functions without internet.

<details>
  <summary>Example full error log, if one has no Internet </summary>

I used a command that looks similar to this: `docker-compose run --rm freqtrade hyperopt --fee 0.0002 --strategy {strategy} --datadir user_data/data/binance --hyperopt-loss {loss_func} -e {epochs} --timerange {timerange}` 

I have FTX as exchange configured.

```
2021-12-17 14:24:53,190 - freqtrade.exchange.exchange - ERROR - Unable to initialize markets.
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f129633e0d0>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ftx.com', port=443): Max retries exceeded with url: /api/coins (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f129633e0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 589, in fetch
    response = self.session.request(
  File "/home/ftuser/.local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ftuser/.local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/ftuser/.local/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='ftx.com', port=443): Max retries exceeded with url: /api/coins (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f129633e0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/exchange.py", line 339, in _load_markets
    self._markets = self._api.load_markets()
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 1422, in load_markets
    currencies = self.fetch_currencies()
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/ftx.py", line 384, in fetch_currencies
    response = self.publicGetCoins(params)
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 459, in inner
    return entry(_self, **inner_kwargs)
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 508, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 504, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 641, in fetch
    raise NetworkError(details) from e
ccxt.base.errors.NetworkError: ftx GET https://ftx.com/api/coins
2021-12-17 14:24:53,193 - freqtrade - ERROR - Could not load markets, therefore cannot start. Please investigate the above error for more details.
```
</details>

**Comment by xmatthias** [comment]
While backtesting does not require "a lot" of internet, it does require internet to startup to fetch current markets and it's attributes (like minimum tradable value).

While i guess it would be possible to cache that data somehow, it's not something we'll be supporting anytime soon, as I consider this an edge-case, which honestly, i don't think is worth supporting.

Supporting (or accepting a PR that provides this level of caching) would mean we'd have to spend time supporting / maintaining it, making sure it'll not break with future changes - and eventually help users in case it gives problems in some instances.
i honestly don't see this bringing any value to freqtrade, as freqtrade will require a internet connection anyway to trade / download the data.

Your best solution will be to either provide the server with full time internet, only run backtests / hyperopts when the server is online, or move your project to a VPS, which is always connected.

While i'm sure you're not agreeing with my point, i hope you do understand that we cannot support every corner case.

**Comment by C0D3D3V** [comment]
Understandable.
How about a dummy exchange class? So that I could specify e.g. in the configuration:
 ```
    "exchange": {
        "name": "OfflineExchange",
        "pair_whitelist": [
            "ETH/BTC", ...
        ]
    }
```

Which simply accepts all pairs and does not check if an order type is available or anything else, but simply accepts all common options.

Do you think that would be just as unmaintainable?

**Comment by C0D3D3V** [comment]
Mh, I think that just doesn't fit into the project. But thanks for your detailed answer, I'll just adjust the few lines of code myself should my server often have internet problems.

**Comment by xmatthias** [comment]
You will discover that it'll not be done with a few lines of code.
You'll have to provide "sane" (or expected?) answers to several methods (market dictionary, fees, ...).

I'm not saying it's not possible, but it'll potentially be 10-100ds of lines, not "a few".
As said, from a project perspective, it's all code that we need to maintain - and for the moment, i see the benefit of this way too low to be useful.

**Comment by C0D3D3V** [comment]
You're right, it's a lot of effort and also unnecessary. Who has unstable internet connections in the 21st century xD Sorry that I have bothered you with it. 

I have nevertheless looked at what would be necessary to run backtestings and have commented out everything ... with the patch backtests run fine. Well, implementing a real dummy class is not worth it. Thanks anyway.

<details>
  <summary>Quick fix to run backtests without internet </summary>


```
From 762aa208e098f3e28bdbc7f86ae92687f92efbc8 Mon Sep 17 00:00:00 2001
From: c0d3d3v <c0d3d3v@mag-keinen-spam.de>
Date: Fri, 17 Dec 2021 22:06:51 +0100
Subject: [PATCH] Quick & Dirty - run backtest without internet

---
 freqtrade/data/history/history_utils.py      | 16 ++++++++--------
 freqtrade/optimize/backtesting.py            |  5 ++---
 freqtrade/plugins/pairlist/StaticPairList.py | 14 +++++++-------
 freqtrade/plugins/pairlistmanager.py         | 11 +++++------
 4 files changed, 22 insertions(+), 24 deletions(-)

diff --git a/freqtrade/data/history/history_utils.py b/freqtrade/data/history/history_utils.py
index e6b8db322..4abe6db7d 100644
--- a/freqtrade/data/history/history_utils.py
+++ b/freqtrade/data/history/history_utils.py
@@ -238,10 +238,10 @@ def refresh_backtest_ohlcv_data(exchange: Exchange, pairs: List[str], timeframes
     pairs_not_available = []
     data_handler = get_datahandler(datadir, data_format)
     for idx, pair in enumerate(pairs, start=1):
-        if pair not in exchange.markets:
-            pairs_not_available.append(pair)
-            logger.info(f"Skipping pair {pair}...")
-            continue
+        # if pair not in exchange.markets:
+        #     pairs_not_available.append(pair)
+        #     logger.info(f"Skipping pair {pair}...")
+        #     continue
         for timeframe in timeframes:
 
             if erase:
@@ -335,10 +335,10 @@ def refresh_backtest_trades_data(exchange: Exchange, pairs: List[str], datadir:
     pairs_not_available = []
     data_handler = get_datahandler(datadir, data_format=data_format)
     for pair in pairs:
-        if pair not in exchange.markets:
-            pairs_not_available.append(pair)
-            logger.info(f"Skipping pair {pair}...")
-            continue
+        # if pair not in exchange.markets:
+        #     pairs_not_available.append(pair)
+        #     logger.info(f"Skipping pair {pair}...")
+        #     continue
 
         if erase:
             if data_handler.trades_purge(pair):
diff --git a/freqtrade/optimize/backtesting.py b/freqtrade/optimize/backtesting.py
index d4b51d04d..3892d1a0d 100644
--- a/freqtrade/optimize/backtesting.py
+++ b/freqtrade/optimize/backtesting.py
@@ -65,8 +65,7 @@ class Backtesting:
         config['dry_run'] = True
         self.strategylist: List[IStrategy] = []
         self.all_results: Dict[str, Dict] = {}
-
-        self.exchange = ExchangeResolver.load_exchange(self.config['exchange']['name'], self.config)
+        self.exchange = ExchangeResolver.load_exchange(self.config['exchange']['name'], self.config, validate=False)
         self.dataprovider = DataProvider(self.config, self.exchange)
 
         if self.config.get('strategy_list', None):
@@ -441,7 +440,7 @@ class Backtesting:
         # Move rate to within the candle's low/high rate
         propose_rate = min(max(propose_rate, row[LOW_IDX]), row[HIGH_IDX])
 
-        min_stake_amount = self.exchange.get_min_pair_stake_amount(pair, propose_rate, -0.05) or 0
+        min_stake_amount = 0 # self.exchange.get_min_pair_stake_amount(pair, propose_rate, -0.05) or 0
         max_stake_amount = self.wallets.get_available_stake_amount()
 
         stake_amount = strategy_safe_wrapper(self.strategy.custom_stake_amount,
diff --git a/freqtrade/plugins/pairlist/StaticPairList.py b/freqtrade/plugins/pairlist/StaticPairList.py
index 30fa474e4..d6523d7b8 100644
--- a/freqtrade/plugins/pairlist/StaticPairList.py
+++ b/freqtrade/plugins/pairlist/StaticPairList.py
@@ -44,13 +44,13 @@ class StaticPairList(IPairList):
         :param tickers: Tickers (from exchange.get_tickers()). May be cached.
         :return: List of pairs
         """
-        if self._allow_inactive:
-            return self.verify_whitelist(
-                self._config['exchange']['pair_whitelist'], logger.info, keep_invalid=True
-            )
-        else:
-            return self._whitelist_for_active_markets(
-                self.verify_whitelist(self._config['exchange']['pair_whitelist'], logger.info))
+        # if self._allow_inactive:
+        return self.verify_whitelist(
+            self._config['exchange']['pair_whitelist'], logger.info, keep_invalid=True
+        )
+        # else:
+        #     return self._whitelist_for_active_markets(
+        #         self.verify_whitelist(self._config['exchange']['pair_whitelist'], logger.info))
 
     def filter_pairlist(self, pairlist: List[str], tickers: Dict) -> List[str]:
         """
diff --git a/freqtrade/plugins/pairlistmanager.py b/freqtrade/plugins/pairlistmanager.py
index face79729..6aeb5fca2 100644
--- a/freqtrade/plugins/pairlistmanager.py
+++ b/freqtrade/plugins/pairlistmanager.py
@@ -57,7 +57,7 @@ class PairListManager():
     @property
     def expanded_blacklist(self) -> List[str]:
         """The expanded blacklist (including wildcard expansion)"""
-        return expand_pairlist(self._blacklist, self._exchange.get_markets().keys())
+        return self._blacklist # expand_pairlist(self._blacklist, self._exchange.get_markets().keys())
 
     @property
     def name_list(self) -> List[str]:
@@ -76,9 +76,8 @@ class PairListManager():
         """Run pairlist through all configured Pairlist Handlers."""
         # Tickers should be cached to avoid calling the exchange on each call.
         tickers: Dict = {}
-        if self._tickers_needed:
-            tickers = self._get_cached_tickers()
-
+        # if self._tickers_needed:
+        #     tickers = self._get_cached_tickers()
         # Generate the pairlist with first Pairlist Handler in the chain
         pairlist = self._pairlist_handlers[0].gen_pairlist(tickers)
 
@@ -127,8 +126,8 @@ class PairListManager():
         :return: pairlist - whitelisted pairs
         """
         try:
-
-            whitelist = expand_pairlist(pairlist, self._exchange.get_markets().keys(), keep_invalid)
+            whitelist = pairlist
+            #whitelist = expand_pairlist(pairlist, self._exchange.get_markets().keys(), keep_invalid)
         except ValueError as err:
             logger.error(f"Pair whitelist contains an invalid Wildcard: {err}")
             return []
-- 
2.34.1


```
</details>

[0001-Quick-Dirty-run-backtest-without-internet.patch.txt](https://github.com/freqtrade/freqtrade/files/7737764/0001-Quick-Dirty-run-backtest-without-internet.patch.txt)

**Comment by xmatthias** [comment]
> Who has unstable internet connections in the 21st century

more people than you think - also in seemingly first class countries like Austria or Germany.
That said - it's more the combination of "unstable internet" - and "must run backtesting while offline".

Your backtests will potentially become inaccurate though (different to normal backtesting) - as you'll allow stake amounts of 1$ now - which normally are prevented from entering as they would not be allowed to be placed.
it'll depend on the configuration - but there's quite some combinations where this can and will happen.

**Comment by C0D3D3V** [comment]
You are of course right, min_stake_amount should not be set to 0, but the correct calculation should be performed. However, I wanted to show here only roughly the points at which markets or exchanges are accessed everywhere (which need Internet during initialization).  

Of course, no one should use this patch.

**Comment by epigramx** [comment]
@xmatthias it can be more problematic in another case, the exchange dropping a pair or two. It makes recorded backtesting results different than newer ones.

**Comment by xmatthias** [comment]
@epigramx that got nothing to do with this question. Please avoid reviving issues with questions that have nothing to do with the topic.

Even if we were to cache the necessary data (which we will not do)  - pairs would still age out (you have to refresh the markets data to get new pairs).

Staticpairlist has a setting for this - [allow_inactive](https://www.freqtrade.io/en/latest/plugins/#static-pair-list) - which will allow you to both download removed pairs, as well as backtest with these.
