### ISSUE TITLE
Help using indicators

### ISSUE THREAD

**Issue by zorann** [freqtrade/freqtrade#6100]
## Describe your environment

  * Operating system: ____Linux
  * Python Version: _____3.8.10 (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*
I have problem using indicators zlma and zema, I tried with this but not working. Please help.
 dataframe['zlma'] = qtpylib.zlma(dataframe)

**Comment by xmatthias** [comment]
You will need to provide us with some more details, like what the problem is you're encountering.
it's quite difficult (and a waste of time on our side) to try and guess the problem from one line without any details on what the problem is (or the error you encounter).

**Comment by zorann** [comment]
I think syntax is wrong and it is not accepting indicator.
This indicator i found in indicators.py under qtpylib.
Error look like this:

2021-12-23 10:34:19,161 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error cannot perform __rmul__ with this index type: DatetimeArray calling <bound method IStrategy._analyze_ticker_internal of <ZZTop.ZZTop object at 0x7f8ad948feb0>>
Traceback (most recent call last):
  File "/home/zok/ft_userdata/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 21, in wrapper
    return f(*args, **kwargs)
  File "/home/zok/ft_userdata/freqtrade/freqtrade/strategy/interface.py", line 509, in _analyze_ticker_internal
    dataframe = self.analyze_ticker(dataframe, metadata)
  File "/home/zok/ft_userdata/freqtrade/freqtrade/strategy/interface.py", line 488, in analyze_ticker
    dataframe = self.advise_indicators(dataframe, metadata)
  File "/home/zok/ft_userdata/freqtrade/freqtrade/strategy/interface.py", line 862, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/home/zok/ft_userdata/freqtrade/user_data/strategies/Zeus.py", line 139, in populate_indicators
    dataframe['zlma'] = qtpylib.zlma(dataframe)
  File "/home/zok/ft_userdata/freqtrade/freqtrade/vendor/qtpylib/indicators.py", line 570, in zlma
    series = 2 * series - series.shift(lag)

**Comment by xmatthias** [comment]
The correct input (based on the error) is probably `dataframe['zlma'] = qtpylib.zlma(dataframe['close'])`, as the indicator seems to expect a series (not the full dataframe).

the whole "qtpylib" indicators we have has been vendored "as is" from another repository, therefore we'll also only be providing very limited support.

**Comment by zorann** [comment]
Thanks. Yes that is working. How can i now evaluate ZLEMA. I need period to be 20. Can you suggest how to 
 put in parameters for zlema which is 

def zlema(series, window, min_periods=None):
    return zlma(series, window, min_periods, kind="ema")

so could be this like 

dataframe['zlema']=qtpylib.zlema(dataframe['close'],min_periods=20)

**Comment by xmatthias** [comment]
i think min_periods is the wrong parameter, but "window" is what you're looking for.
