### ISSUE TITLE
greenlet distribution was not found and is required by SQLAlchemy

### ISSUE THREAD

**Issue by vlagorce** [freqtrade/freqtrade#6105]
## Describe your environment

  * Kernel: Linux ##### 5.13.0-1011-raspi 13-Ubuntu SMP PREEMPT Fri Nov 19 18:40:23 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
  * Operating System: Ubuntu 21.10 /impish
  * Freqtrade Version:  freqtrade 2021.11 // freqtradeorg/freqtrade:stable_pi
  * hardware: Raspberry Pi 4 Model B Rev 1.1
  
## Describe the problem:

Fail starting latest stable_pi image on my raspebrry pi

### Steps to reproduce:

  1. docker-compose up
  
### Observed Results:

Container fail to start

### Relevant code exceptions or logs

```
freqtrade    | 2021-12-23 14:54:11,893 - freqtrade.commands.trade_commands - ERROR - The 'greenlet!=0.4.17; python_version >= "3" and (platform_machine == "aarch64" or (platform_machine == "ppc64le" or (platform_machine == "x86_64" or (platform_machine == "amd64" or (platform_machine == "AMD64" or (platform_machine == "win32" or platform_machine == "WIN32"))))))' distribution was not found and is required by SQLAlchemy
freqtrade    | 2021-12-23 14:54:11,894 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
freqtrade    | Traceback (most recent call last):
freqtrade    |   File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
freqtrade    |     worker = Worker(args)
freqtrade    |   File "/freqtrade/freqtrade/worker.py", line 35, in __init__
freqtrade    |     self._init(False)
freqtrade    |   File "/freqtrade/freqtrade/worker.py", line 52, in _init
freqtrade    |     self.freqtrade = FreqtradeBot(self._config)
freqtrade    |   File "/freqtrade/freqtrade/freqtradebot.py", line 80, in __init__
freqtrade    |     self.rpc: RPCManager = RPCManager(self)
freqtrade    |   File "/freqtrade/freqtrade/rpc/rpc_manager.py", line 27, in __init__
freqtrade    |     from freqtrade.rpc.telegram import Telegram
freqtrade    |   File "/freqtrade/freqtrade/rpc/telegram.py", line 20, in <module>
freqtrade    |     from telegram.ext import CallbackContext, CallbackQueryHandler, CommandHandler, Updater
freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/ext/__init__.py", line 42, in <module>
freqtrade    |     from .jobqueue import JobQueue, Job
freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/telegram/ext/jobqueue.py", line 26, in <module>
freqtrade    |     from apscheduler.events import EVENT_JOB_ERROR, EVENT_JOB_EXECUTED, JobEvent
freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/apscheduler/__init__.py", line 1, in <module>
freqtrade    |     from pkg_resources import get_distribution, DistributionNotFound
freqtrade    |   File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3243, in <module>
freqtrade    |     def _initialize_master_working_set():
freqtrade    |   File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
freqtrade    |     f(*args, **kwargs)
freqtrade    |   File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
freqtrade    |     working_set = WorkingSet._build_master()
freqtrade    |   File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 568, in _build_master
freqtrade    |     ws.require(__requires__)
freqtrade    |   File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 886, in require
freqtrade    |     needed = self.resolve(parse_requirements(requirements))
freqtrade    |   File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 772, in resolve
freqtrade    |     raise DistributionNotFound(req, requirers)
freqtrade    | pkg_resources.DistributionNotFound: The 'greenlet!=0.4.17; python_version >= "3" and (platform_machine == "aarch64" or (platform_machine == "ppc64le" or (platform_machine == "x86_64" or (platform_machine == "amd64" or (platform_machine == "AMD64" or (platform_machine == "win32" or platform_machine == "WIN32"))))))' distribution was not found and is required by SQLAlchemy
```

**Comment by xmatthias** [comment]
`stable_pi` is the wrong tag for a 64bit raspberry - as it contains the binaries for the regular raspberry and is not a multi-arch image.

Please use the `stable` image instead - `stable_pi` is only kept there for compatibility purposes (we could actually remove it for the next release ...).

**Comment by strowi** [comment]
Hi,

i seem to be running into the same issue on a pi4 with the following:

```
~> cat docker-compose.yml
---
version: '3'
services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8080:8080"
    command: >
      trade
     --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy SampleStrategy


~> uname -a
Linux kent 5.10.78-5-osmc #1 SMP PREEMPT Mon Feb 28 01:18:12 UTC 2022 aarch64 GNU/Linux

~> lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

Running  `apt install -qy g++ && pip3 install --upgrade greenlet` in the running container seems to solve the problem on my pi4.
