### ISSUE TITLE
Error of "No objects to concatenate" in plot-profit

### ISSUE THREAD

**Issue by aziba353** [freqtrade/freqtrade#6132]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2021.11

  
## Your question
`docker-compose run --rm freqtrade plot-profit --trade-source file --strategy Ichi01 --auto-open --timerange 20200101-20200229 -p BTC/USDT  --export-filename user_data/backtest_results/backtest-result-2021-12-28_09-46-55.json`
I want to run this command but i face with with this error. can anyone help? 

```
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/plot_commands.py", line 36, in start_plot_profit
    plot_profit(config)
  File "/freqtrade/freqtrade/plot/plotting.py", line 606, in plot_profit
    fig = generate_profit_graph(plot_elements['pairs'], plot_elements['ohlcv'],
  File "/freqtrade/freqtrade/plot/plotting.py", line 463, in generate_profit_graph
    df_comb = combine_dataframes_with_mean(data, "close")
  File "/freqtrade/freqtrade/data/btanalysis.py", line 329, in combine_dataframes_with_mean
    df_comb = pd.concat([data[pair].set_index('date').rename(
  File "/home/ftuser/.local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/ftuser/.local/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 294, in concat
    op = _Concatenator(
  File "/home/ftuser/.local/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 351, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
ERROR: 1
```

**Comment by xmatthias** [comment]
it's quite difficult to determine this only with the stacktrace.

From the error location, i'd suspect that you encountered other errors / warnings before this - which are however missing in the above - which is therefore not really possible to analyze.

**Comment by aziba353** [comment]
Thanks for your prompt reply. Is there any solution to find all Error/Warnings during the execution.

**Comment by xmatthias** [comment]
it's a plotting command - the regular (non-verbose) output will be around 100 lines - so i think you can simply post that here so we can have a look at that.

**Comment by aziba353** [comment]
This is all I can get from terminal:
```
Creating freqtrade_freqtrade_run ... done
2021-12-30 08:53:39,934 - freqtrade.configuration.configuration - INFO - Using config: user_data/config.json ...
2021-12-30 08:53:39,942 - freqtrade.loggers - INFO - Verbosity set to 0
2021-12-30 08:53:40,076 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2021-12-30 08:53:40,080 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/binance ...
2021-12-30 08:53:40,081 - freqtrade.configuration.configuration - INFO - Using pairs ['BTC/USDT']
2021-12-30 08:53:40,081 - freqtrade.configuration.configuration - INFO - Using trades from: file
2021-12-30 08:53:40,082 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2021-12-30 08:53:40,119 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2021-12-30 08:53:40,120 - freqtrade.configuration.deprecated_settings - WARNING - DEPRECATED: The `ask_strategy.use_sell_signal` setting is deprecated and will be
removed in the next versions of Freqtrade. Please use the `use_sell_signal` setting in your configuration instead.
2021-12-30 08:53:40,120 - freqtrade.configuration.deprecated_settings - WARNING - DEPRECATED: The `ask_strategy.sell_profit_only` setting is deprecated and will be
 removed in the next versions of Freqtrade. Please use the `sell_profit_only` setting in your configuration instead.
2021-12-30 08:53:40,121 - freqtrade.configuration.deprecated_settings - WARNING - DEPRECATED: The `ask_strategy.ignore_roi_if_buy_signal` setting is deprecated and
 will be removed in the next versions of Freqtrade. Please use the `ignore_roi_if_buy_signal` setting in your configuration instead.
2021-12-30 08:53:40,122 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2021-12-30 08:53:40,136 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2021-12-30 08:53:40,137 - freqtrade.exchange.exchange - INFO - Using CCXT 1.61.92
2021-12-30 08:53:40,137 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2021-12-30 08:53:40,168 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 200}
2021-12-30 08:53:40,198 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2021-12-30 08:53:43,503 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2021-12-30 08:53:43,523 - freqtrade.data.history.idatahandler - WARNING - No history data for pair: "BTC/USDT", timeframe: 5m. Use `freqtrade download-data` to dow
nload the data
2021-12-30 08:53:43,538 - freqtrade.data.btanalysis - INFO - Loading backtest result from /freqtrade/user_data/backtest_results/backtest-result-2021-12-28_09-46-55
.json
2021-12-30 08:53:43,572 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/plot_commands.py", line 36, in start_plot_profit
    plot_profit(config)
  File "/freqtrade/freqtrade/plot/plotting.py", line 606, in plot_profit
    fig = generate_profit_graph(plot_elements['pairs'], plot_elements['ohlcv'],
  File "/freqtrade/freqtrade/plot/plotting.py", line 463, in generate_profit_graph
    df_comb = combine_dataframes_with_mean(data, "close")
  File "/freqtrade/freqtrade/data/btanalysis.py", line 329, in combine_dataframes_with_mean
    df_comb = pd.concat([data[pair].set_index('date').rename(
  File "/home/ftuser/.local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/ftuser/.local/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 294, in concat
    op = _Concatenator(
  File "/home/ftuser/.local/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 351, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
ERROR: 1
```

**Comment by xmatthias** [comment]
The message i was looking for is the following: 

```
2021-12-30 08:53:43,523 - freqtrade.data.history.idatahandler - WARNING - No history data for pair: "BTC/USDT", timeframe: 5m. Use `freqtrade download-data` to dow
nload the data
```

which clearly explains that freqtrade did not find the required data (maybe you have data, but for a different timerange?).

I'll improve the message here - but that's about all we can do - the rest is on your environment - to have the data available.

**Comment by aziba353** [comment]
I have downloaded the data for timeframe "1m" and I know that the timerange is OK. is it necessary to download data for timeframe "5m" strategy? or the bot will convert data to create appropriate OHLC candle of higher timeframe?

**Comment by xmatthias** [comment]
Freqtrade will not automatically convert data to higher timeframes - but will require you to download data for the desired timeframe(s) explicitly with `freqtrade download-data -t 5m 1h <...>`.
