### ISSUE TITLE
Error in hyperopt-loss "SharpeHyperOptLoss"

### ISSUE THREAD

**Issue by aziba353** [freqtrade/freqtrade#6138]
## Describe your environment

  * Operating system: Windows 10
  * Python Version: Remote python3.9.9 
  * CCXT version: 1.61.92
  * Freqtrade Version: 2021.11
  

## Describe the problem:

When I run Hyperopt strategy with SharpeHyperOptLoss, I can not see any table for epochs and after interrupting, I see the result "No epochs evaluated yet". But when I change the cost functio it will work.

### Steps to reproduce:

  1. Run below code with SharpeHyperOptLoss, face with error that is mentioned below.
```
  docker-compose run --rm freqtrade hyperopt --hyperopt-loss SharpeHyperOptLoss --strategy Ichi01 -e 5 --ignore-unparameterized-spaces --timera
nge 20200101-20200229 --timeframe 1m -p BTC/USDT --print-all
```

  2. Run exact strategy with different hyperopt-loss funtion will work fine.
 ```
 docker-compose run --rm freqtrade hyperopt --hyperopt-loss ShortTradeDurHyperOptLoss --strategy Ichi01 -e 5 --ignore-unparameterized-spaces -
-timerange 20200101-20200229 --timeframe 1m -p BTC/USDT --print-all
```
  
### Observed Results:

  * What happened?
    Get error while using SharpeHyperOptLoss
  * What did you expect to happen?
     Not recieve error while changing the cost function.

### Relevant code exceptions or logs

Logs for step 1:
  ```
E:\AlgoCode\freqtrade>docker-compose run --rm freqtrade hyperopt --hyperopt-loss SharpeHyperOptLoss --strategy Ichi01 -e 5 --ignore-unparameterized-spaces --timera
nge 20200101-20200229 --timeframe 1m -p BTC/USDT --print-all
Creating freqtrade_freqtrade_run ... done
2022-01-01 07:36:05,927 - freqtrade.configuration.configuration - INFO - Using config: user_data/config.json ...
2022-01-01 07:36:05,934 - freqtrade.loggers - INFO - Verbosity set to 0
2022-01-01 07:36:05,935 - freqtrade.configuration.configuration - INFO - Parameter -i/--timeframe detected ... Using timeframe: 1m ...
2022-01-01 07:36:05,935 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 100 ...
2022-01-01 07:36:05,935 - freqtrade.configuration.configuration - INFO - Parameter --timerange detected: 20200101-20200229 ...
2022-01-01 07:36:06,158 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2022-01-01 07:36:06,161 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/binance ...
2022-01-01 07:36:06,161 - freqtrade.configuration.configuration - INFO - Overriding timeframe with Command line argument
2022-01-01 07:36:06,161 - freqtrade.configuration.configuration - INFO - Parameter --epochs detected ... Will run Hyperopt with for 5 epochs ...
2022-01-01 07:36:06,162 - freqtrade.configuration.configuration - INFO - Parameter -s/--spaces detected: default
2022-01-01 07:36:06,162 - freqtrade.configuration.configuration - INFO - Parameter --print-all detected ...
2022-01-01 07:36:06,162 - freqtrade.configuration.configuration - INFO - Parameter -j/--job-workers detected: -1
2022-01-01 07:36:06,162 - freqtrade.configuration.configuration - INFO - Parameter --min-trades detected: 1
2022-01-01 07:36:06,162 - freqtrade.configuration.configuration - INFO - Using Hyperopt loss class name: SharpeHyperOptLoss
2022-01-01 07:36:06,163 - freqtrade.configuration.configuration - INFO - Paramter --ignore-missing-space detected: True
2022-01-01 07:36:06,163 - freqtrade.configuration.configuration - INFO - Using pairs ['BTC/USDT']
2022-01-01 07:36:06,163 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2022-01-01 07:36:06,194 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2022-01-01 07:36:06,195 - freqtrade.configuration.deprecated_settings - WARNING - DEPRECATED: The `ask_strategy.use_sell_signal` setting is deprecated and will be
removed in the next versions of Freqtrade. Please use the `use_sell_signal` setting in your configuration instead.
2022-01-01 07:36:06,195 - freqtrade.configuration.deprecated_settings - WARNING - DEPRECATED: The `ask_strategy.sell_profit_only` setting is deprecated and will be
 removed in the next versions of Freqtrade. Please use the `sell_profit_only` setting in your configuration instead.
2022-01-01 07:36:06,195 - freqtrade.configuration.deprecated_settings - WARNING - DEPRECATED: The `ask_strategy.ignore_roi_if_buy_signal` setting is deprecated and
 will be removed in the next versions of Freqtrade. Please use the `ignore_roi_if_buy_signal` setting in your configuration instead.
2022-01-01 07:36:06,195 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2022-01-01 07:36:06,209 - freqtrade.commands.optimize_commands - INFO - Starting freqtrade in Hyperopt mode
2022-01-01 07:36:06,213 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2022-01-01 07:36:06,214 - freqtrade.exchange.exchange - INFO - Using CCXT 1.61.92
2022-01-01 07:36:06,214 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2022-01-01 07:36:06,243 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 200}
2022-01-01 07:36:06,281 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2022-01-01 07:36:09,699 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2022-01-01 07:36:09,772 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy Ichi01 from '/freqtrade/user_data/strategies/ahmad.py'...
2022-01-01 07:36:09,775 - freqtrade.strategy.hyper - INFO - Loading parameters from file /freqtrade/user_data/strategies/ahmad.json
2022-01-01 07:36:09,782 - freqtrade.strategy.hyper - INFO - Strategy Parameter: buy_cloud_cond = False
2022-01-01 07:36:09,783 - freqtrade.strategy.hyper - INFO - Strategy Parameter: buy_rsi = 26
2022-01-01 07:36:09,783 - freqtrade.strategy.hyper - INFO - No params for sell found, using default values.
2022-01-01 07:36:09,784 - freqtrade.strategy.hyper - INFO - No params for protection found, using default values.
2022-01-01 07:36:09,785 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 1m.
2022-01-01 07:36:09,786 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2022-01-01 07:36:09,786 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 100.
2022-01-01 07:36:09,786 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'buy': 10, 'sell': 30, 'un
it': 'minutes', 'exit_timeout_count': 0}.
2022-01-01 07:36:09,786 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'use_sell_signal' with value in config file: True.
2022-01-01 07:36:09,786 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'sell_profit_only' with value in config file: False.
2022-01-01 07:36:09,787 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ignore_roi_if_buy_signal' with value in config file: False.
2022-01-01 07:36:09,787 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 0.175, '35': 0.040999999999999995, '88': 0.019, '180': 0
}
2022-01-01 07:36:09,787 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 1m
2022-01-01 07:36:09,787 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.143
2022-01-01 07:36:09,787 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: True
2022-01-01 07:36:09,788 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive: 0.15
2022-01-01 07:36:09,788 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.2
2022-01-01 07:36:09,788 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: True
2022-01-01 07:36:09,788 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2022-01-01 07:36:09,788 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
2022-01-01 07:36:09,788 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'market', 'stopl
oss_on_exchange': False}
2022-01-01 07:36:09,789 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
2022-01-01 07:36:09,789 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2022-01-01 07:36:09,799 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 100
2022-01-01 07:36:09,800 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2022-01-01 07:36:09,800 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 60
2022-01-01 07:36:09,800 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'buy': 10, 'sell': 30, 'unit': 'minutes', 'exit_timeout_c
ount': 0}
2022-01-01 07:36:09,800 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_sell_signal: True
2022-01-01 07:36:09,800 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_only: False
2022-01-01 07:36:09,800 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_buy_signal: False
2022-01-01 07:36:09,801 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_offset: 0.0
2022-01-01 07:36:09,801 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2022-01-01 07:36:09,801 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2022-01-01 07:36:09,801 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2022-01-01 07:36:09,820 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from '/freqtrade/freqtrade/plugins/pairlist/StaticPairList.
py'...
2022-01-01 07:36:10,028 - freqtrade.resolvers.iresolver - INFO - Using resolved hyperoptloss SharpeHyperOptLoss from '/freqtrade/user_data/hyperopts/sharp.py'...
2022-01-01 07:36:10,032 - freqtrade.optimize.hyperopt - INFO - Removing `/freqtrade/user_data/hyperopt_results/hyperopt_tickerdata.pkl`.
2022-01-01 07:36:10,039 - freqtrade.optimize.hyperopt - INFO - Using optimizer random state: 26892
2022-01-01 07:36:10,047 - freqtrade.optimize.hyperopt_auto - WARNING - The 'sell' space is included into the hyperoptimization but no parameter for this space was
not found in your Strategy. This space will be ignored.
2022-01-01 07:36:10,048 - freqtrade.optimize.hyperopt_interface - INFO - Min roi table: {0: 0.012, 2: 0.008, 4: 0.004, 6: 0}
2022-01-01 07:36:10,048 - freqtrade.optimize.hyperopt_interface - INFO - Max roi table: {0: 0.12, 8: 0.043, 20: 0.015, 44: 0}
2022-01-01 07:36:10,060 - freqtrade.data.history.history_utils - INFO - Using indicator startup period: 60 ...
2022-01-01 07:36:17,010 - freqtrade.data.history.idatahandler - WARNING - Missing data at start for pair BTC/USDT, data starts at 2020-01-01 00:00:00
2022-01-01 07:36:17,412 - freqtrade.optimize.backtesting - INFO - Loading data from 2020-01-01 00:00:00 up to 2020-02-29 00:00:00 (59 days).
2022-01-01 07:36:17,412 - freqtrade.configuration.timerange - WARNING - Moving start-date by 60 candles to account for startup time.
2022-01-01 07:36:17,413 - freqtrade.optimize.hyperopt - INFO - Dataload complete. Calculating indicators
2022-01-01 07:36:17,547 - freqtrade.optimize.hyperopt - INFO - Hyperopting with data from 2020-01-01 01:00:00 up to 2020-02-29 00:00:00 (58 days)..
2022-01-01 07:36:17,807 - freqtrade.optimize.hyperopt - INFO - Found 4 CPU cores. Let's make them scream!
2022-01-01 07:36:17,808 - freqtrade.optimize.hyperopt - INFO - Number of parallel jobs set as: -1
2022-01-01 07:36:17,808 - freqtrade.optimize.hyperopt - INFO - Using estimator ET.
2022-01-01 07:36:17,857 - freqtrade.optimize.hyperopt - INFO - Effective number of parallel workers used: 4
2022-01-01 07:37:27,208 - freqtrade - ERROR - Fatal exception!
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'profit_percent'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 436, in _process_worker
    r = call_item()
  File "/home/ftuser/.local/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 288, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/ftuser/.local/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/home/ftuser/.local/lib/python3.9/site-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/home/ftuser/.local/lib/python3.9/site-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/ftuser/.local/lib/python3.9/site-packages/joblib/externals/loky/cloudpickle_wrapper.py", line 38, in __call__
    return self._obj(*args, **kwargs)
  File "/freqtrade/freqtrade/optimize/hyperopt.py", line 325, in generate_optimizer
    return self._get_results_dict(bt_results, self.min_date, self.max_date,
  File "/freqtrade/freqtrade/optimize/hyperopt.py", line 353, in _get_results_dict
    loss = self.calculate_loss(results=backtesting_results['results'],
  File "/freqtrade/user_data/hyperopts/sharp.py", line 31, in hyperopt_loss_function
    results["profit_percent"] = results["profit_percent"] - 0.001
  File "/home/ftuser/.local/lib/python3.9/site-packages/pandas/core/frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/ftuser/.local/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'profit_percent'
"""
 ```

Logs for step 2:
  ```
E:\AlgoCode\freqtrade> docker-compose run --rm freqtrade hyperopt --hyperopt-loss ShortTradeDurHyperOptLoss --strategy Ichi01 -e 5 --ignore-unparameterized-spaces
--timerange 20200101-20200229 --timeframe 1m -p BTC/USDT --print-all
Creating freqtrade_freqtrade_run ... done
2022-01-01 07:42:40,310 - freqtrade.configuration.configuration - INFO - Using config: user_data/config.json ...
2022-01-01 07:42:40,315 - freqtrade.loggers - INFO - Verbosity set to 0
2022-01-01 07:42:40,316 - freqtrade.configuration.configuration - INFO - Parameter -i/--timeframe detected ... Using timeframe: 1m ...
2022-01-01 07:42:40,316 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 100 ...
2022-01-01 07:42:40,316 - freqtrade.configuration.configuration - INFO - Parameter --timerange detected: 20200101-20200229 ...
2022-01-01 07:42:40,483 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2022-01-01 07:42:40,487 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/binance ...
2022-01-01 07:42:40,488 - freqtrade.configuration.configuration - INFO - Overriding timeframe with Command line argument
2022-01-01 07:42:40,488 - freqtrade.configuration.configuration - INFO - Parameter --epochs detected ... Will run Hyperopt with for 5 epochs ...
2022-01-01 07:42:40,488 - freqtrade.configuration.configuration - INFO - Parameter -s/--spaces detected: default
2022-01-01 07:42:40,488 - freqtrade.configuration.configuration - INFO - Parameter --print-all detected ...
2022-01-01 07:42:40,489 - freqtrade.configuration.configuration - INFO - Parameter -j/--job-workers detected: -1
2022-01-01 07:42:40,489 - freqtrade.configuration.configuration - INFO - Parameter --min-trades detected: 1
2022-01-01 07:42:40,489 - freqtrade.configuration.configuration - INFO - Using Hyperopt loss class name: ShortTradeDurHyperOptLoss
2022-01-01 07:42:40,489 - freqtrade.configuration.configuration - INFO - Paramter --ignore-missing-space detected: True
2022-01-01 07:42:40,489 - freqtrade.configuration.configuration - INFO - Using pairs ['BTC/USDT']
2022-01-01 07:42:40,490 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2022-01-01 07:42:40,520 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2022-01-01 07:42:40,526 - freqtrade.configuration.deprecated_settings - WARNING - DEPRECATED: The `ask_strategy.use_sell_signal` setting is deprecated and will be
removed in the next versions of Freqtrade. Please use the `use_sell_signal` setting in your configuration instead.
2022-01-01 07:42:40,527 - freqtrade.configuration.deprecated_settings - WARNING - DEPRECATED: The `ask_strategy.sell_profit_only` setting is deprecated and will be
 removed in the next versions of Freqtrade. Please use the `sell_profit_only` setting in your configuration instead.
2022-01-01 07:42:40,527 - freqtrade.configuration.deprecated_settings - WARNING - DEPRECATED: The `ask_strategy.ignore_roi_if_buy_signal` setting is deprecated and
 will be removed in the next versions of Freqtrade. Please use the `ignore_roi_if_buy_signal` setting in your configuration instead.
2022-01-01 07:42:40,527 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2022-01-01 07:42:40,543 - freqtrade.commands.optimize_commands - INFO - Starting freqtrade in Hyperopt mode
2022-01-01 07:42:40,547 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2022-01-01 07:42:40,547 - freqtrade.exchange.exchange - INFO - Using CCXT 1.61.92
2022-01-01 07:42:40,547 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2022-01-01 07:42:40,576 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 200}
2022-01-01 07:42:40,603 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2022-01-01 07:42:44,588 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2022-01-01 07:42:44,659 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy Ichi01 from '/freqtrade/user_data/strategies/ahmad.py'...
2022-01-01 07:42:44,662 - freqtrade.strategy.hyper - INFO - Loading parameters from file /freqtrade/user_data/strategies/ahmad.json
2022-01-01 07:42:44,668 - freqtrade.strategy.hyper - INFO - Strategy Parameter: buy_cloud_cond = False
2022-01-01 07:42:44,669 - freqtrade.strategy.hyper - INFO - Strategy Parameter: buy_rsi = 26
2022-01-01 07:42:44,669 - freqtrade.strategy.hyper - INFO - No params for sell found, using default values.
2022-01-01 07:42:44,670 - freqtrade.strategy.hyper - INFO - No params for protection found, using default values.
2022-01-01 07:42:44,671 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 1m.
2022-01-01 07:42:44,671 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2022-01-01 07:42:44,671 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 100.
2022-01-01 07:42:44,672 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'buy': 10, 'sell': 30, 'un
it': 'minutes', 'exit_timeout_count': 0}.
2022-01-01 07:42:44,672 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'use_sell_signal' with value in config file: True.
2022-01-01 07:42:44,672 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'sell_profit_only' with value in config file: False.
2022-01-01 07:42:44,672 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ignore_roi_if_buy_signal' with value in config file: False.
2022-01-01 07:42:44,672 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 0.175, '35': 0.040999999999999995, '88': 0.019, '180': 0
}
2022-01-01 07:42:44,673 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 1m
2022-01-01 07:42:44,673 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.143
2022-01-01 07:42:44,673 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: True
2022-01-01 07:42:44,673 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive: 0.15
2022-01-01 07:42:44,673 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.2
2022-01-01 07:42:44,674 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: True
2022-01-01 07:42:44,674 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2022-01-01 07:42:44,674 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
2022-01-01 07:42:44,674 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'market', 'stopl
oss_on_exchange': False}
2022-01-01 07:42:44,674 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
2022-01-01 07:42:44,674 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2022-01-01 07:42:44,675 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 100
2022-01-01 07:42:44,675 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2022-01-01 07:42:44,675 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 60
2022-01-01 07:42:44,675 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'buy': 10, 'sell': 30, 'unit': 'minutes', 'exit_timeout_c
ount': 0}
2022-01-01 07:42:44,675 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_sell_signal: True
2022-01-01 07:42:44,676 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_only: False
2022-01-01 07:42:44,676 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_buy_signal: False
2022-01-01 07:42:44,676 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_offset: 0.0
2022-01-01 07:42:44,676 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2022-01-01 07:42:44,676 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2022-01-01 07:42:44,677 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2022-01-01 07:42:44,693 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from '/freqtrade/freqtrade/plugins/pairlist/StaticPairList.
py'...
2022-01-01 07:42:44,930 - freqtrade.resolvers.iresolver - INFO - Using resolved hyperoptloss ShortTradeDurHyperOptLoss from '/freqtrade/freqtrade/optimize/hyperopt
_loss_short_trade_dur.py'...
2022-01-01 07:42:44,934 - freqtrade.optimize.hyperopt - INFO - Removing `/freqtrade/user_data/hyperopt_results/hyperopt_tickerdata.pkl`.
2022-01-01 07:42:44,941 - freqtrade.optimize.hyperopt - INFO - Using optimizer random state: 12010
2022-01-01 07:42:44,946 - freqtrade.optimize.hyperopt_auto - WARNING - The 'sell' space is included into the hyperoptimization but no parameter for this space was
not found in your Strategy. This space will be ignored.
2022-01-01 07:42:44,947 - freqtrade.optimize.hyperopt_interface - INFO - Min roi table: {0: 0.012, 2: 0.008, 4: 0.004, 6: 0}
2022-01-01 07:42:44,947 - freqtrade.optimize.hyperopt_interface - INFO - Max roi table: {0: 0.12, 8: 0.043, 20: 0.015, 44: 0}
2022-01-01 07:42:44,959 - freqtrade.data.history.history_utils - INFO - Using indicator startup period: 60 ...
2022-01-01 07:42:50,931 - freqtrade.data.history.idatahandler - WARNING - Missing data at start for pair BTC/USDT, data starts at 2020-01-01 00:00:00
2022-01-01 07:42:51,191 - freqtrade.optimize.backtesting - INFO - Loading data from 2020-01-01 00:00:00 up to 2020-02-29 00:00:00 (59 days).
2022-01-01 07:42:51,192 - freqtrade.configuration.timerange - WARNING - Moving start-date by 60 candles to account for startup time.
2022-01-01 07:42:51,192 - freqtrade.optimize.hyperopt - INFO - Dataload complete. Calculating indicators
2022-01-01 07:42:51,270 - freqtrade.optimize.hyperopt - INFO - Hyperopting with data from 2020-01-01 01:00:00 up to 2020-02-29 00:00:00 (58 days)..
2022-01-01 07:42:51,385 - freqtrade.optimize.hyperopt - INFO - Found 4 CPU cores. Let's make them scream!
2022-01-01 07:42:51,385 - freqtrade.optimize.hyperopt - INFO - Number of parallel jobs set as: -1
2022-01-01 07:42:51,385 - freqtrade.optimize.hyperopt - INFO - Using estimator ET.
2022-01-01 07:42:51,408 - freqtrade.optimize.hyperopt - INFO - Effective number of parallel workers used: 4
+--------+---------+----------+------------------+--------------+-------------------------------+-----------------+-------------------------------+-------------+
|   Best |   Epoch |   Trades |    Win Draw Loss |   Avg profit |                        Profit |    Avg duration |                  Max Drawdown |   Objective |
|--------+---------+----------+------------------+--------------+-------------------------------+-----------------+-------------------------------+-------------|
| * Best |     1/5 |      212 |     41  170    1 |       -0.03% |        -5.795 USDT   (-0.58%) | 0 days 05:57:00 |        16.234 USDT   (16.22%) |     2.22236 |
| *      |     2/5 |      210 |     37  171    2 |       -0.03% |        -6.857 USDT   (-0.69%) | 0 days 06:00:00 |        16.902 USDT   (16.89%) |     2.22638 |
| *      |     3/5 |      210 |     30  178    2 |       -0.04% |        -7.679 USDT   (-0.77%) | 0 days 06:01:00 |        17.502 USDT   (17.48%) |     2.22912 |
| *      |     4/5 |      212 |     50  151   11 |       -0.18% |       -37.300 USDT   (-3.73%) | 0 days 04:23:00 |        37.300 USDT   (37.26%) |     2.27741 |
| *      |     5/5 |      154 |     22  131    1 |       -0.09% |       -13.526 USDT   (-1.35%) | 0 days 06:52:00 |        16.162 USDT   (16.15%) |     2.26264 |
 [Epoch 5 of 5 (100%)] ||                                                                                                | [Time:  0:00:33, Elapsed Time: 0:00:33]
2022-01-01 07:44:46,778 - freqtrade.optimize.hyperopt - INFO - 5 epochs saved to '/freqtrade/user_data/hyperopt_results/strategy_Ichi01_2022-01-01_07-42-44.fthypt'
.
2022-01-01 07:44:46,963 - freqtrade.resolvers.iresolver - WARNING - Could not import /freqtrade/user_data/strategies/sample_strategy.py due to 'name 'BooleanParame
ter' is not defined'
2022-01-01 07:44:46,966 - freqtrade.optimize.hyperopt_tools - INFO - Dumping parameters to /freqtrade/user_data/strategies/ahmad.json

Best result:

*    1/5:    212 trades. 41/170/1 Wins/Draws/Losses. Avg profit  -0.03%. Median profit   0.00%. Total profit -5.79492743 USDT (  -0.58%). Avg duration 5:57:00 min.
 Objective: 2.22236


    # Buy hyperspace params:
    buy_params = {
        "buy_cloud_cond": False,
        "buy_rsi": 34,
    }

    # ROI table:
    minimal_roi = {
        "0": 0.063,
        "8": 0.02,
        "13": 0.007,
        "16": 0
    }

    # Stoploss:
    stoploss = -0.282

    # Trailing stop:
    trailing_stop = True  # value loaded from strategy
    trailing_stop_positive = 0.15  # value loaded from strategy
    trailing_stop_positive_offset = 0.2  # value loaded from strategy
    trailing_only_offset_is_reached = True  # value loaded from strategy 

  ```

**Comment by xmatthias** [comment]
Please fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

On top of having complete unclarity about the version you're using - it's unclear to me which of the 2 above codesnippets are failing.

For the failing one:
please provide the full log up to the exception, not just the exception itself.

**Comment by aziba353** [comment]
@xmatthias 
Sorry Matthias for not obeying your template. Really it was my first Bug report in Github. I have updated the problem. It would be appreciated if you can help. 
Thanks in advance.

**Comment by xmatthias** [comment]
`2022-01-01 07:36:10,028 - freqtrade.resolvers.iresolver - INFO - Using resolved hyperoptloss SharpeHyperOptLoss from '/freqtrade/user_data/hyperopts/sharp.py'...`


It seems like you have a file in your user_data directory that's overwriting SharpeHyperOptLoss (`/freqtrade/user_data/hyperopts/sharp.py`).

As freqtrade is looking in the user_data first, it finds this (probably outdated / old file) - and therefore crashes.
We did use `profit_percent` a while ago - but stopped having this probably half a year ago.

If you want to keep your file, best rename the class within that file to something other than `SharpeHyperOptLoss` - so the builtin loss can be loaded correctly.

**Comment by aziba353** [comment]
That is true and it worked.
Thanks a lot.
