### ISSUE TITLE
Crypto.com crash on market buy

### ISSUE THREAD

**Issue by damien-piedanna** [freqtrade/freqtrade#6169]
## Describe your environment

  * Operating system: ubuntu
  * Python Version: 3.9
  * CCXT version: 1.65.78
  * Freqtrade Version: 2021.12

## Describe the problem:

Hello, I recently wanted to test the creation of a bot with the new exchange supported by ccxt since version 1.65.78 which is crypto.com. Unfortunately, everything worked fine until the bot placed a market buy order.

### Steps to reproduce:

  1.Trading with Crypto.com
  2. Buy signal found and market buy
  
### Observed Results:

  * Raise exception : local variable 'book_entry_price' referenced before assignment

### Relevant code exceptions or logs
  ```
2022-01-05 22:21:48,978 - freqtrade.freqtradebot - INFO - Buy signal found: about create a new trade for SNX/USDT with stake_amount: 100.0 ...
2022-01-05 22:21:49,237 - freqtrade.commands.trade_commands - ERROR - local variable 'book_entry_price' referenced before assignment
2022-01-05 22:21:49,238 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker.run()
  File "/freqtrade/freqtrade/worker.py", line 74, in run
    state = self._worker(old_state=state)
  File "/freqtrade/freqtrade/worker.py", line 114, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
  File "/freqtrade/freqtrade/worker.py", line 139, in _throttle
    result = func(*args, **kwargs)
  File "/freqtrade/freqtrade/worker.py", line 152, in _process_running
    self.freqtrade.process()
  File "/freqtrade/freqtrade/freqtradebot.py", line 183, in process
    self.enter_positions()
  File "/freqtrade/freqtrade/freqtradebot.py", line 385, in enter_positions
    trades_created += self.create_trade(pair)
  File "/freqtrade/freqtrade/freqtradebot.py", line 442, in create_trade
    return self.execute_entry(pair, stake_amount, buy_tag=buy_tag)
  File "/freqtrade/freqtrade/freqtradebot.py", line 522, in execute_entry
    order = self.exchange.create_order(pair=pair, ordertype=order_type, side="buy",
  File "/freqtrade/freqtrade/exchange/exchange.py", line 740, in create_order
    dry_order = self.create_dry_run_order(pair, ordertype, side, amount, rate)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 621, in create_dry_run_order
    average = self.get_dry_market_fill_price(pair, side, amount, rate)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 671, in get_dry_market_fill_price
    filled_amount += remaining_amount * book_entry_price
UnboundLocalError: local variable 'book_entry_price' referenced before assignment
  ```

**Comment by xmatthias** [comment]
While the latest commit in develop will fix this particular error - the problem is a more concerning one.

The exception (and location) tells me that the orderbook was empty (the loop was never executed). 

This means that either the exchange API (or ccxt) had a glitch and returned no orderbook - or this orderbook had no ask side (which would mean that a market-buy could push price up by several 1000% - even on very small orders).
Obviously on dry-runs, this will not happen, but it would concern me for running this in live anyway, so while the exception will no longer occur - dry-run buys might be slightly inaccurate (Price push/slippage will be limited to 5%) - which is not the case in live.
