### ISSUE TITLE
Asyncio exception on Gate.io on Windows

### ISSUE THREAD

**Issue by dnuno89** [freqtrade/freqtrade#6178]
## Describe your environment

  * Operating system: Windows 10
  * Python Version: 3.8.10 (`python -V`)
  * CCXT version: 1.61.92(`pip freeze | grep ccxt`)
  * Freqtrade Version: develop-bb29c4446 (latest dev) 
   
## Your question

* Since I updated freqtrade (I was using a dev from beginnings of December aprox), I am having an exception at apparently random moments, and which most times does not interrupt the correct operation of the bot. It only happens in Gate.io (at least kucoin does not show it). The exception shown is:

```
2022-01-06 20:35:21,535 - asyncio - ERROR - Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "c:\users\golda\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "c:\users\golda\appdata\local\programs\python\python38\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] Se ha forzado la interrupción de una conexión existente por el host remoto
```
The last line in spanish says: "Remote host has forced the interruption of an existent connection".

My pairlist is produced by:
```
"pairlists": [
        {
			"method": "VolumePairList",
			"number_assets": 100,
			"sort_key": "quoteVolume",
            "refresh_period": 86400
		},
        {
            "method": "AgeFilter",
            "min_days_listed": 18,
            "refresh_period":86400
        },
		{
			"method": "RangeStabilityFilter",
			"lookback_days": 4,
			"min_rate_of_change": 0.03,
                         "max_rate_of_change": 1.0,
			"refresh_period": 86400
		}
        {
			"method": "VolumePairList",
			"number_assets": 120,
			"sort_key": "quoteVolume",
			"refresh_period": 86400,
                        "lookback_days":7
		}
    ],

```
I have tried using a standard Volume Pairlist (without lookback_days) with similar results.

Also, using lookback_days now produces an output every minute as if it was going to redo the pairlist, which seems odd to me:
```
2022-01-06 20:55:02,681 - VolumePairList - INFO - Using volume range of 7 candles, timeframe: 1d, starting from 2021-12-29T20:55:00 till 2022-01-05T20:55:00
2022-01-06 20:55:59,108 - freqtrade.worker - INFO - Bot heartbeat. PID=12820, version='develop-bb29c4446', state='RUNNING'
2022-01-06 20:56:07,139 - VolumePairList - INFO - Using volume range of 7 candles, timeframe: 1d, starting from 2021-12-29T20:56:00 till 2022-01-05T20:56:00
2022-01-06 20:57:02,358 - freqtrade.worker - INFO - Bot heartbeat. PID=12820, version='develop-bb29c4446', state='RUNNING'
2022-01-06 20:57:02,364 - VolumePairList - INFO - Using volume range of 7 candles, timeframe: 1d, starting from 2021-12-29T20:57:00 till 2022-01-05T20:57:00
2022-01-06 20:58:04,821 - freqtrade.worker - INFO - Bot heartbeat. PID=12820, version='develop-bb29c4446', state='RUNNING'
2022-01-06 20:58:04,827 - VolumePairList - INFO - Using volume range of 7 candles, timeframe: 1d, starting from 2021-12-29T20:58:00 till 2022-01-05T20:58:00
```

**Comment by xmatthias** [comment]
Please provide us with some more logs (10-20 lines before the exception should do). 
Just the exception is unfortunately often not helpful, as it's unclear from there what the bot has been doing.

the exception does not include ANY information about freqtrade - so it could as well be from a different program (which i don't believe by the way) - but it includes nothing that could even remotely help us in investigating this.

The error itself suggests that it's a simple "socket disconnect" - which is a network level problem.

As you only encounter this on one exchange, the most likely cause is that the exchange itself is having problems at the moment, forcing these disconnects.

**Comment by dnuno89** [comment]
There isn't any other related outputs shown. Here is a log with the exception soon after starting the bot:

```
2022-01-07 13:02:56,566 - freqtrade.worker - INFO - Changing state to: RUNNING
2022-01-07 13:02:56,566 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': "*Exchange:* `gateio`\n*Stake per trade:* `20 USDT`\n*Minimum ROI:* `{'0': 0.6, '19': 0.04, '25': 0.03, '35': 0.025, '55': 0.02, '100': 0.015, '250': 0.001, '350': -0.02, '950': -0.05}`\n*Stoploss:* `-0.35`\n*Timeframe:* `5m`\n*Strategy:* `NN_XGgg2`"}
2022-01-07 13:02:56,670 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': "Searching for USDT pairs to buy and sell based on [{'VolumePairList': 'VolumePairList - top 105 volume pairs.'}, {'AgeFilter': 'AgeFilter - Filtering pairs with age less than 18 days'}, {'RangeStabilityFilter': 'RangeStabilityFilter - Filtering pairs with rate of change below 0.03 and above 1.0 over the last days.'}]"}
2022-01-07 13:02:56,765 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': 'Using Protections: \nCooldownPeriod - Cooldown period of 3 candles.'}
2022-01-07 13:02:56,916 - freqtrade.freqtradebot - INFO - Updating 0 open orders.
2022-01-07 13:03:25,041 - freqtrade.worker - INFO - Bot heartbeat. PID=19636, version='develop-7f20f6834', state='RUNNING'
2022-01-07 13:04:25,161 - freqtrade.worker - INFO - Bot heartbeat. PID=19636, version='develop-7f20f6834', state='RUNNING'
2022-01-07 13:05:35,157 - freqtrade.worker - INFO - Bot heartbeat. PID=19636, version='develop-7f20f6834', state='RUNNING'
2022-01-07 13:05:42,666 - asyncio - ERROR - Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "c:\users\golda\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "c:\users\golda\appdata\local\programs\python\python38\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] Se ha forzado la interrupción de una conexión existente por el host remoto
2022-01-07 13:06:35,246 - freqtrade.worker - INFO - Bot heartbeat. PID=19636, version='develop-7f20f6834', state='RUNNING'
2022-01-07 13:07:35,355 - freqtrade.worker - INFO - Bot heartbeat. PID=19636, version='develop-7f20f6834', state='RUNNING'
2022-01-07 13:08:35,462 - freqtrade.worker - INFO - Bot heartbeat. PID=19636, version='develop-7f20f6834', state='RUNNING'
2022-01-07 13:09:35,557 - freqtrade.worker - INFO - Bot heartbeat. PID=19636, version='develop-7f20f6834', state='RUNNING'
2022-01-07 13:10:38,497 - freqtrade.worker - INFO - Bot heartbeat. PID=19636, version='develop-7f20f6834', state='RUNNING'
2022-01-07 13:11:38,595 - freqtrade.worker - INFO - Bot heartbeat. PID=19636, version='develop-7f20f6834', state='RUNNING'
2022-01-07 13:12:38,730 - freqtrade.worker - INFO - Bot heartbeat. PID=19636, version='develop-7f20f6834', state='RUNNING'
2022-01-07 13:13:38,821 - freqtrade.worker - INFO - Bot heartbeat. PID=19636, version='develop-7f20f6834', state='RUNNING'
2022-01-07 13:14:38,879 - freqtrade.worker - INFO - Bot heartbeat. PID=19636, version='develop-7f20f6834', state='RUNNING'
2022-01-07 13:15:42,929 - freqtrade.worker - INFO - Bot heartbeat. PID=19636, version='develop-7f20f6834', state='RUNNING'
2022-01-07 13:16:43,034 - freqtrade.worker - INFO - Bot heartbeat. PID=19636, version='develop-7f20f6834', state='RUNNING'
2022-01-07 13:17:13,781 - asyncio - ERROR - Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "c:\users\golda\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "c:\users\golda\appdata\local\programs\python\python38\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] Se ha forzado la interrupción de una conexión existente por el host remoto
2022-01-07 13:17:43,137 - freqtrade.worker - INFO - Bot heartbeat. PID=19636, version='develop-7f20f6834', state='RUNNING'
2022-01-07 13:18:43,228 - freqtrade.worker - INFO - Bot heartbeat. PID=19636, version='develop-7f20f6834', state='RUNNING'
2022-01-07 13:19:43,366 - freqtrade.worker - INFO - Bot heartbeat. PID=19636, version='develop-7f20f6834', state='RUNNING'
2022-01-07 13:20:44,411 - freqtrade.worker - INFO - Bot heartbeat. PID=19636, version='develop-7f20f6834', state='RUNNING'
2022-01-07 13:21:44,479 - freqtrade.worker - INFO - Bot heartbeat. PID=19636, version='develop-7f20f6834', state='RUNNING'
```

I noticed that I updated freqtrade without updating its dependencies, so I've updated freqtrade to today's dev version and all its dependencies (which updated CCXT). The exception keeps showing (this last log uses the last dev and updated dependencies).

Also since I updated CCXT the volume pairlist with lookback_days on Gate.io has stopped working and produces the following output (everything in the pairlist generation works fine up to the volume lookback_days):

```
2022-01-07 13:24:19,631 - VolumePairList - INFO - Searching 250 pairs: ['ETH/USDT', 'BTC/USDT', 'ATOM/USDT', 'BABYDOGE/USDT', 'XRP/USDT', 'MANA/USDT', 'CRV/USDT', 'DOT/USDT', 'DOGE/USDT', 'FIL/USDT', 'MATIC/USDT', 'LINK/USDT', 'NEAR/USDT', 'FTM/USDT', 'SHIB/USDT', 'WEMIX/USDT', 'RACA/USDT', 'SAND/USDT', 'ADA/USDT', 'PEOPLE/USDT', 'SOL/USDT', 'SUSHI/USDT', 'AVAX/USDT', 'SAITAMA/USDT', 'QRDO/USDT', 'LUNA/USDT', 'TRX/USDT', 'LTC/USDT', 'ICP/USDT', 'EOS/USDT', 'METIS/USDT', 'FLOKI/USDT', 'POSI/USDT', 'GALA/USDT', 'SOS/USDT', 'OCT/USDT', 'KDA/USDT', 'ONE/USDT', 'SPELL/USDT', 'FLUX/USDT', 'ARV/USDT', 'LRC/USDT', 'UNI/USDT', 'KISHU/USDT', 'UST/USDT', 'PYR/USDT', 'ALICE/USDT', 'CSPR/USDT', 'STARL/USDT', 'RNDR/USDT', 'CEEK/USDT', 'ENJ/USDT', 'NFT/USDT', '1INCH/USDT', 'TONC/USDT', 'SIDUS/USDT', 'VRA/USDT', 'BLOK/USDT', 'XTZ/USDT', 'BSV/USDT', 'UFO/USDT', 'CRO/USDT', 'ROSE/USDT', 'WILD/USDT', 'MOVR/USDT', 'ZEC/USDT', 'XLM/USDT', 'ALGO/USDT', 'XYO/USDT', 'BLIN/USDT', 'WOO/USDT', 'VADER/USDT', 'BICO/USDT', 'WOOP/USDT', 'AAVE/USDT', 'ISP/USDT', 'BCH/USDT', 'ENS/USDT', 'AR/USDT', 'DYDX/USDT', 'HT/USDT', 'ANT/USDT', 'VLX/USDT', 'GXS/USDT', 'IMX/USDT', 'GRT/USDT', 'RMRK/USDT', 'FUSE/USDT', 'ELON/USDT', 'MINA/USDT', 'POLC/USDT', 'SAFEMOON/USDT', 'JOE/USDT', 'SAITO/USDT', 'ATLAS/USDT', 'SUNNY/USDT', 'STX/USDT', 'CHR/USDT', 'CHER/USDT', 'VET/USDT', 'YFI/USDT', 'CELO/USDT', 'EFI/USDT', 'DUSK/USDT', 'GCOIN/USDT', 'FTT/USDT', 'XPRT/USDT', 'OMI/USDT', 'VIDYX/USDT', 'ZEN/USDT', 'THETA/USDT', 'AKITA/USDT', 'SUPER/USDT', 'HERO/USDT', 'SQUID/USDT', 'SDAO/USDT', 'WAXP/USDT', 'XMR/USDT', 'HTR/USDT', 'CSTR/USDT', 'SENATE/USDT', 'GM/USDT', 'NBP/USDT', 'BZZ/USDT', 'ETC/USDT', 'ALPA/USDT', 'KINT/USDT', 'CERE/USDT', '10SET/USDT', 'SYS/USDT', 'BTT/USDT', 'WNCG/USDT', 'AKT/USDT', 'GGG/USDT', 'BeyondFi/USDT', 'DERC/USDT', 'POOL/USDT', 'EGLD/USDT', 'RVN/USDT', 'SXP/USDT', 'MXC/USDT', 'VSP/USDT', 'UOS/USDT', 'AXS/USDT', 'MBOX/USDT', 'UMA/USDT', 'MC/USDT', 'CQT/USDT', 'RBN/USDT', 'BOBA/USDT', 'SGB/USDT', 'C98/USDT', 'OOKI/USDT', 'HNT/USDT', 'REEF/USDT', 'CHICKS/USDT', 'KIN/USDT', 'CHAMP/USDT', 'QNT/USDT', 'BIT/USDT', 'XDC/USDT', 'SBR/USDT', 'PLA/USDT', 'OCEAN/USDT', 'COCOS/USDT', 'PBR/USDT', 'FXS/USDT', 'RAD/USDT', 'FARM/USDT', 'STOS/USDT', 'SCY/USDT', 'ANY/USDT', 'BAT/USDT', 'BIN/USDT', 'THG/USDT', 'XCH/USDT', 'XED/USDT', 'IOTX/USDT', 'KP3R/USDT', 'YGG/USDT', 'DASH/USDT', 'QTUM/USDT', 'CRF/USDT', 'CVX/USDT', 'EQX/USDT', 'ASTRO/USDT', 'SLIM/USDT', 'CWEB/USDT', 'STORJ/USDT', 'CAKE/USDT', 'REQ/USDT', 'AGLD/USDT', 'XEC/USDT', 'STRONG/USDT', 'ILV/USDT', 'OVR/USDT', 'SNX/USDT', 'RSR/USDT', 'ZAM/USDT', 'QUACK/USDT', 'FLOW/USDT', 'CLV/USDT', 'RUNE/USDT', 'TLM/USDT', 'ERN/USDT', 'ORO/USDT', 'XAVA/USDT', 'DODO/USDT', 'ACH/USDT', 'AURORA/USDT', 'KEEP/USDT', 'TIME/USDT', 'TARA/USDT', 'FLY/USDT', 'LDO/USDT', 'BENQI/USDT', 'ZIG/USDT', 'DEVT/USDT', 'CWS/USDT', 'ONT/USDT', 'NEO/USDT', 'TOKE/USDT', 'LPT/USDT', 'DAO/USDT', '1ART/USDT', 'SAO/USDT', 'ENNO/USDT', 'FET/USDT', 'NGL/USDT', 'PLACE/USDT', 'KSM/USDT', 'OPUL/USDT', 'VEMP/USDT', 'QANX/USDT', 'COMP/USDT', 'TRU/USDT', 'SWAP/USDT', 'GASDAO/USDT', 'SFP/USDT', 'THN/USDT', 'CART/USDT', 'ZKS/USDT', 'CELR/USDT', 'BOSON/USDT', 'GAFI/USDT', 'CPHR/USDT', 'ALU/USDT', 'BRKL/USDT', 'DV/USDT', 'SRM/USDT']
2022-01-07 13:24:19,639 - VolumePairList - INFO - Using volume range of 2 candles, timeframe: 1d, starting from 2022-01-04T13:24:00 till 2022-01-06T13:24:00
2022-01-07 13:24:19,922 - freqtrade.exchange.common - WARNING - _async_get_candle_history() returned exception: "Could not fetch historical candle (OHLCV) data for pair EQX/USDT due to BadRequest. Message: gateio {"label":"INVALID_PARAM_VALUE","message":"Candlestick range too broad. Maximum 1000 data points are allowed per request"}". Retrying still for 4 times.
2022-01-07 13:24:20,194 - freqtrade.exchange.common - WARNING - _async_get_candle_history() returned exception: "Could not fetch historical candle (OHLCV) data for pair GAFI/USDT due to BadRequest. Message: gateio {"label":"INVALID_PARAM_VALUE","message":"Candlestick range too broad. Maximum 1000 data points are allowed per request"}". Retrying still for 4 times.
2022-01-07 13:24:20,511 - freqtrade.exchange.common - WARNING - _async_get_candle_history() returned exception: "Could not fetch historical candle (OHLCV) data for pair HERO/USDT due to BadRequest. Message: gateio {"label":"INVALID_PARAM_VALUE","message":"Candlestick range too broad. Maximum 1000 data points are allowed per request"}". Retrying still for 4 times.
2022-01-07 13:24:20,796 - freqtrade.exchange.common - WARNING - _async_get_candle_history() returned exception: "Could not fetch historical candle (OHLCV) data for pair RNDR/USDT due to BadRequest. Message: gateio {"label":"INVALID_PARAM_VALUE","message":"Candlestick range too broad. Maximum 1000 data points are allowed per request"}". Retrying still for 4 times.
2022-01-07 13:24:20,800 - freqtrade.exchange.common - WARNING - _async_get_candle_history() returned exception: "Could not fetch historical candle (OHLCV) data for pair HERO/USDT due to BadRequest. Message: gateio {"label":"INVALID_PARAM_VALUE","message":"Candlestick range too broad. Maximum 1000 data points are allowed per request"}". Retrying still for 3 times.
2022-01-07 13:24:20,801 - freqtrade.exchange.common - WARNING - _async_get_candle_history() returned exception: "Could not fetch historical candle (OHLCV) data for pair ARV/USDT due to BadRequest. Message: gateio {"label":"INVALID_PARAM_VALUE","message":"Candlestick range too broad. Maximum 1000 data points are allowed per request"}". Retrying still for 4 times.
2022-01-07 13:24:20,807 - freqtrade.exchange.common - WARNING - _async_get_candle_history() returned exception: "Could not fetch historical candle (OHLCV) data for pair XDC/USDT due to BadRequest. Message: gateio {"label":"INVALID_PARAM_VALUE","message":"Candlestick range too broad. Maximum 1000 data points are allowed per request"}". Retrying still for 4 times.

```
I have tried different number of lookback_days with identical results. The same volume pairlist code works on KuCoin.

Downgrading CCXT from 1.66.20 (latest freqtrade requirement) to 1.61.92 makes the lookback_days volume pairlist work again on Gate.io, so maybe this is a CCXT issue?


This pairlist is working with CCXT 1.61.92 but not with 1.66.20:

```
    "pairlists": [
        {
			"method": "VolumePairList",
			"number_assets": 250,
			"sort_key": "quoteVolume",
            "refresh_period": 86400
		},
        {
			"method": "VolumePairList",
			"number_assets": 120,
			"sort_key": "quoteVolume",
			"refresh_period": 86400,
            "lookback_days":2
		},
        {
            "method": "AgeFilter",
            "min_days_listed": 18,
            "refresh_period":86400
        },
		{
			"method": "RangeStabilityFilter",
			"lookback_days": 4,
			"min_rate_of_change": 0.03,
            "max_rate_of_change": 1.0,
			"refresh_period": 86400
		}
    ],
```
(I don't know why the tabulations change when I copy the code but are right in the original code)

**Comment by xmatthias** [comment]
the 2 issues are not related in my opinion. one is a network error, while the other MIGHT be an issue (or change) in ccxt.

For the network error - it seems to be an issue with gate.io itself - or a problem of the host/network. I doubt we'll be able to help much with that.

For the other issue, i've opened https://github.com/ccxt/ccxt/issues/11162 in the ccxt repository.

**Comment by dnuno89** [comment]
Thanks!
