### ISSUE TITLE
Permission problems with Docker on Raspberry Pi 

### ISSUE THREAD

**Issue by solipsy** [freqtrade/freqtrade#6183]
## Describe your environment

  * Operating system: Raspberry Pi Buster
  * Python Version: Python 3.9.9
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2021.11
  
I already have freqtrade running on main Linux computer without problems, now I'd like to move it to Raspberry Pi 3. 
I followed the Docker quickstart, but I'm getting some strange errors related to permissions.
 
First, when I do `docker-compose run --rm freqtrade create-userdir --userdir user_data`, it says:

`pi@raspberrypi:~/software/ft_userdata $ docker-compose run --rm freqtrade create-userdir --userdir user_data`
`Creating ft_userdata_freqtrade_run ... done`
`sudo: error in event loop: Operation not permitted`
`sudo: unexpected child termination condition: 0`

After running `docker-compose up -d` and trying to view the UI in the browser, it says connection refused, and there's this in the logs:

2022-01-08 08:17:34,983 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2022-01-08 08:17:36,678 - freqtrade.commands.trade_commands - ERROR - [Errno 1] Operation not permitted
2022-01-08 08:17:36,679 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/freqtrade/freqtrade/worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/freqtrade/freqtrade/freqtradebot.py", line 65, in __init__
    self.exchange = ExchangeResolver.load_exchange(self.config['exchange']['name'], self.config)
  File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 32, in load_exchange
    exchange = ExchangeResolver._load_exchange(exchange_name,
  File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 54, in _load_exchange
    exchange = ex_class(**kwargs)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 150, in __init__
    self._load_markets()
  File "/freqtrade/freqtrade/exchange/exchange.py", line 340, in _load_markets
    self._load_async_markets()
  File "/freqtrade/freqtrade/exchange/exchange.py", line 329, in _load_async_markets
    asyncio.get_event_loop().run_until_complete(
  File "/usr/local/lib/python3.9/asyncio/events.py", line 639, in get_event_loop
    self.set_event_loop(self.new_event_loop())
  File "/usr/local/lib/python3.9/asyncio/events.py", line 659, in new_event_loop
    return self._loop_factory()
  File "/usr/local/lib/python3.9/asyncio/unix_events.py", line 54, in __init__
    super().__init__(selector)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 55, in __init__
    super().__init__()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 397, in __init__
    self._clock_resolution = time.get_clock_info('monotonic').resolution
PermissionError: [Errno 1] Operation not permitted

I also tried this: `chown -R pi:pi user_data`, but to no avail.

Is something wrong with my installation of docker-compose, or is it using inaproppriate rights?

I also tried to use this image: `docker.io/freqtradeorg/freqtrade:2021.11_pi` with same errors. I noticed in some issue that with Docker quickstart on Pi, there's an additional step, but I couldn't find it in the documentation.

I'd be grateful if someone could point me in the right direction.

**Comment by xmatthias** [comment]
The problematic step is for sure the following: `docker-compose run --rm freqtrade create-userdir --userdir user_data`.

This has to work - as it doesn't it makes me assume that maybe `user_data` (so the mount points to a file, maybe).

Further research into the subsequent error (self._clock_resolution = time.get_clock_info('monotonic').resolution
PermissionError: [Errno 1] Operation not permitted) makes me believe that it might be an issue with your raspberry OS installation - which makes docker fail in some circumstances.

Please try to have that uptodate (`sudo apt update && sudo apt upgrade`), reboot the raspberry and try again.

this should update `libseccomp2` to the latest version, which seems to fix this.

[source](https://github.com/esphome/issues/issues/2450#issuecomment-924776728) - but it's slightly older, so i don't think the wget steps will be necessary).

**Comment by solipsy** [comment]
Thanks! I updated, rebooted, ran `docker-compose run --rm freqtrade create-userdir --userdir user_data` again, here's the output:

pi@raspberrypi:~/software/ft_userdata $ docker-compose run --rm freqtrade create-userdir --userdir user_data
Creating ft_userdata_freqtrade_run ... done
sudo: error in event loop: Operation not permitted
sudo: unexpected child termination condition: 0
2022-01-08 09:39:31,043 - freqtrade.configuration.directory_operations - WARNING - Could not chown user_data
2022-01-08 09:39:31,046 - freqtrade.configuration.directory_operations - WARNING - File `user_data/strategies/sample_strategy.py` exists already, not deploying sample file.
2022-01-08 09:39:31,047 - freqtrade.configuration.directory_operations - WARNING - File `user_data/hyperopts/sample_hyperopt_loss.py` exists already, not deploying sample file.
2022-01-08 09:39:31,048 - freqtrade.configuration.directory_operations - WARNING - File `user_data/notebooks/strategy_analysis_example.ipynb` exists already, not deploying sample file.

Files:

pi@raspberrypi:~/software/ft_userdata $ ls -l
total 8
-rw-r--r--  1 pi pi  951 Jan  8 08:54 docker-compose.yml
drwxr-xr-x 10 pi pi 4096 Jan  8 08:40 user_data

**Comment by xmatthias** [comment]
what's the output of `dpkg -l | grep libseccomp2`?

**Comment by solipsy** [comment]
pi@raspberrypi:~/software/ft_userdata $ dpkg -l | grep libseccomp2
ii  libseccomp2:armhf                    2.3.3-4                                 armhf        high level interface to Linux seccomp filter

**Comment by xmatthias** [comment]
it's a version problem of the raspbian OS.
Raspbian buster is not the latest version, but raspbian bullseye (based on debian 11) is (which is also the version you get on the raspbian download pages by default now).

I suspect it's an incompatibility between docker and older versions of raspbian / debian. As such, best upgrade (there's some guides for this on the internet) or reinstall (often the cleaner/simpler solution) raspbian with the latest version

My version of libseccomp2 is 2.5.1 (on rasbian bullseye / 11) - with that it's working fine.

**Comment by solipsy** [comment]
I'll reinstall and post the results here. Thanks!

**Comment by PTemp1e** [comment]
sudo: error in event loop: Operation not permitted
you must use docker-compose with sudo at the beginning. Because you are no user in docker. 
read it here:
https://www.antary.de/2021/09/20/raspberry-pi-docker-und-portainer/

after installation you must youse this to get in the group docker

sudo usermod -aG docker $USER
newgrp docker

**Comment by xmatthias** [comment]
> you must use docker-compose with sudo at the beginning. Because you are no user in docker.

This "solution" is not related to the actual problem /question at all.

**Comment by solipsy** [comment]
Reinstalled the OS, now it works, although I have to run docker-compose commands as sudo. Thanks for your help!

**Comment by xmatthias** [comment]
In that case - please run `sudo usermod -aG docker pi` (or whatever user you're using).
After running this, logout and back in, and docker should work without sudo (basically the command shared above).

**Comment by TomPer** [comment]
You can also do this to avoid reinstallation :
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC 648ACFD622F3D138
 echo "deb http://deb.debian.org/debian buster-backports main" | sudo tee -a /etc/apt/sources.list.d/buster-backports.list
 sudo apt update
 sudo apt install -t buster-backports libseccomp2

it's work for me
