### ISSUE TITLE
Unable to initialize markets - Timestamp for this request is outside of the recvWindow.

### ISSUE THREAD

**Issue by gdominoni** [freqtrade/freqtrade#6211]
## Describe your environment

  * Operating system: ubuntu
  * Python Version: 3.8
  * CCXT version: 1.66.66
  * Freqtrade Version: develop-58b77bd15
  
What does this mean? How can i fix it? Everything was working fine until yesterday, then it just crashed.

```
2022-01-12 10:10:40,546 - freqtrade.exchange.exchange - ERROR - Unable to initialize markets.
Traceback (most recent call last):
  File "/home/giovanni/freqtrade/.env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 658, in fetch
    response.raise_for_status()
  File "/home/giovanni/freqtrade/.env/lib/python3.8/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error:  for url: https://api.binance.com/sapi/v1/capital/config/getall?timestamp=1641975040074&recvWindow=5000&signature=81784b67e867ab3a780933a2311325b6e633d338c8ff64d34239cf4d39014e6c

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/giovanni/freqtrade/freqtrade/exchange/exchange.py", line 345, in _load_markets
    self._markets = self._api.load_markets()
  File "/home/giovanni/freqtrade/.env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1486, in load_markets
    currencies = self.fetch_currencies()
  File "/home/giovanni/freqtrade/.env/lib/python3.8/site-packages/ccxt/binance.py", line 1186, in fetch_currencies
    response = self.sapiGetCapitalConfigGetall(params)
  File "/home/giovanni/freqtrade/.env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 500, in inner
    return entry(_self, **inner_kwargs)
  File "/home/giovanni/freqtrade/.env/lib/python3.8/site-packages/ccxt/binance.py", line 4825, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/giovanni/freqtrade/.env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 547, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/giovanni/freqtrade/.env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 674, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/giovanni/freqtrade/.env/lib/python3.8/site-packages/ccxt/binance.py", line 4803, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
  File "/home/giovanni/freqtrade/.env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 565, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.InvalidNonce: binance {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
2022-01-12 10:10:40,578 - freqtrade.commands.trade_commands - ERROR - Could not load markets, therefore cannot start. Please investigate the above error for more details.
2022-01-12 10:10:40,578 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/giovanni/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/home/giovanni/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/home/giovanni/freqtrade/freqtrade/worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/home/giovanni/freqtrade/freqtrade/freqtradebot.py", line 65, in __init__
    self.exchange = ExchangeResolver.load_exchange(self.config['exchange']['name'], self.config)
  File "/home/giovanni/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 32, in load_exchange
    exchange = ExchangeResolver._load_exchange(exchange_name,
  File "/home/giovanni/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 54, in _load_exchange
    exchange = ex_class(**kwargs)
  File "/home/giovanni/freqtrade/freqtrade/exchange/exchange.py", line 157, in __init__
    self.validate_stakecurrency(config['stake_currency'])
  File "/home/giovanni/freqtrade/freqtrade/exchange/exchange.py", line 376, in validate_stakecurrency
    raise OperationalException(
freqtrade.exceptions.OperationalException: Could not load markets, therefore cannot start. Please investigate the above error for more details.
```

```
{
    "available_capital": xxx,
    "max_open_trades": 20,
    "stake_currency": "USDT",
    "stake_amount": 100,
    "amend_last_stake_amount": true,
    "fiat_display_currency": "USD",
    "timeframe": "1d",
    
    "dry_run": false,
    "db-url": "sqlite:///upper1D.sqlite",
    
    "cancel_open_orders_on_exit": false,
    
    "forcebuy_enable": true,
    
    "unfilledtimeout": {
        "buy": 10,
        "sell": 30,
        "unit": "minutes"
    },
    
    "order_types": {
        "buy": "limit",
        "sell": "limit",
        "emergencysell": "market",
        "forcebuy": "market",
        "forcesell": "market",
        "stoploss": "market",
        "stoploss_on_exchange": true,
        "stoploss_on_exchange_interval": 60
    },
    
    "bid_strategy": {
        "price_side": "bid",
        "ask_last_balance": 0.0,
        "use_order_book": true,
        "order_book_top": 1,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "ask_strategy": {
        "price_side": "ask",
        "use_order_book": true,
        "order_book_top": 1
    },
    "exchange": {
        "name": "binance",
        "key": "xxx",
        "secret": "xxx",
        "ccxt_config": {},
        "ccxt_async_config": {},
        "pair_whitelist": [
            "BTC/USDT"
        ],
        "pair_blacklist": [
            "BNB/.*",
            ".*USD/USDT",
            ".*DOWN/USDT",
            ".*UP/USDT"
        ]
    },
    "pairlists": [
        {
            "method": "VolumePairList",
            "number_assets": 40,
            "sort_key": "quoteVolume",
            "min_value": 0,
            "refresh_period": 3600,
            "lookback_timeframe": "1h",
            "lookback_period": 12
        },
        {
            "method": "RangeStabilityFilter",
            "lookback_timeframe": "1h",
            "lookback_period": 12,
            "min_rate_of_change": 0.01,
            "max_rate_of_change": 100,
            "refresh_period": 2600
        },
 
        {"method": "StaticPairList"}
        
    ],
    "edge": {
        "enabled": false,
        "process_throttle_secs": 3600,
        "calculate_since_number_of_days": 7,
        "allowed_risk": 0.01,
        "stoploss_range_min": -0.01,
        "stoploss_range_max": -0.1,
        "stoploss_range_step": -0.01,
        "minimum_winrate": 0.60,
        "minimum_expectancy": 0.20,
        "min_trade_number": 10,
        "max_trade_duration_minute": 1440,
        "remove_pumps": false
    },
    "telegram": {
        "enabled": true,
        "token": "xxx",
        "chat_id": "xxx"
    },
    "api_server": {
        "enabled": false,
        "listen_ip_address": "127.0.0.1",
        "listen_port": 8080,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "ded44f92d8e029cc6fee569b950279586c28d8090dbe4559c762f09c58da57db",
        "CORS_origins": [],
        "username": "",
        "password": ""
    },
    "bot_name": "freqtrade",
    "initial_state": "running",
    "forcebuy_enable": false,
    "internals": {
        "process_throttle_secs": 60
    }
}
```

**Comment by xmatthias** [comment]
The issue is quite simple - your system time is slightly wrong - therefore binance is rejecting requests from your system.

Simply put - install / setup a time sync service like ntpd or chronyd (make sure it syncronizes quite frequently).

**Comment by gdominoni** [comment]
Thank you, chronyd worked

**Comment by brinias** [comment]
Hello, I have exactly the same error, I installed chronyd but I am still getting the same error
Do you have any idea??
Thanks in advance

freqtrade.exceptions.OperationalException: Could not load markets, therefore cannot start. Please investigate the above error for more details.

**Comment by jeffe1024** [comment]
Hello, if I need to request Asian exchanges such as OKX, how should I set the UTC+8 time?

**Comment by xmatthias** [comment]
the timezone on your system is irrelevant - as long as the clock is aligned (UTC time must be aligned with global UTC time).

ccxt will handle eventual offsets - though trading usually happens in UTC timezone - as these are global markets, open 24/7.

**Comment by Longjef** [comment]
I installed Freqtrade using Docker and configured OKX in the exchange field of config.json. However, when starting with docker-compose, the following error occurred:

**Comment by jeffe1024** [comment]
### Thank you very much for your reply。I installed Freqtrade using Docker and configured OKX in the exchange field of config.json. However, when starting with docker-compose up command, the following error occurred:
ccxt.base.errors.NetworkError: okx GET https://www.okx.com/api/v5/public/instruments?instType=SPOT
2023-04-14 12:47:08 2023-04-14 04:47:08,512 - freqtrade.commands.trade_commands - ERROR - Could not load markets, therefore cannot start. Please investigate the above error for more details.
2023-04-14 12:47:08 2023-04-14 04:47:08,513 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
2023-04-14 12:47:08 Traceback (most recent call last):
2023-04-14 12:47:08   File "/freqtrade/freqtrade/commands/trade_commands.py", line 24, in start_trading
2023-04-14 12:47:08     worker = Worker(args)
2023-04-14 12:47:08   File "/freqtrade/freqtrade/worker.py", line 37, in __init__
2023-04-14 12:47:08     self._init(False)
2023-04-14 12:47:08   File "/freqtrade/freqtrade/worker.py", line 53, in _init
2023-04-14 12:47:08     self.freqtrade = FreqtradeBot(self._config)
2023-04-14 12:47:08   File "/freqtrade/freqtrade/freqtradebot.py", line 72, in __init__
2023-04-14 12:47:08     self.exchange = ExchangeResolver.load_exchange(
2023-04-14 12:47:08   File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 34, in load_exchange
2023-04-14 12:47:08     exchange = ExchangeResolver._load_exchange(
2023-04-14 12:47:08   File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 60, in _load_exchange
2023-04-14 12:47:08     exchange = ex_class(**kwargs)
2023-04-14 12:47:08   File "/freqtrade/freqtrade/exchange/exchange.py", line 187, in __init__
2023-04-14 12:47:08     self.validate_config(config)
2023-04-14 12:47:08   File "/freqtrade/freqtrade/exchange/exchange.py", line 220, in validate_config
2023-04-14 12:47:08     self.validate_stakecurrency(config['stake_currency'])
2023-04-14 12:47:08   File "/freqtrade/freqtrade/exchange/exchange.py", line 522, in validate_stakecurrency
2023-04-14 12:47:08     raise OperationalException(
2023-04-14 12:47:08 freqtrade.exceptions.OperationalException: Could not load markets, therefore cannot start. Please investigate the above error for more details

> ### This is my configuration file parameter：

> 
{
    "max_open_trades": 3,
    "stake_currency": "USDT",
    "stake_amount": "unlimited",
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "dry_run": true,
    "dry_run_wallet": 1000,
    "cancel_open_orders_on_exit": false,
    "trading_mode": "spot",
    "margin_mode": "",
    "unfilledtimeout": {
        "entry": 10,
        "exit": 10,
        "exit_timeout_count": 0,
        "unit": "minutes"
    },
    "entry_pricing": {
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1,
        "price_last_balance": 0.0,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "exit_pricing":{
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1
    },
    "exchange": {
        "name": "okx",
        "key": "",
        "secret": "",
        "ccxt_config": {},
        "ccxt_async_config": {},
        "pair_whitelist": [
        ],
        "pair_blacklist": [
        ]
    },
    "pairlists": [
        {
            "method": "VolumePairList",
            "number_assets": 20,
            "sort_key": "quoteVolume",
            "min_value": 0,
            "refresh_period": 1800
        }
    ],
    "telegram": {
        "enabled": false,
        "token": "",
        "chat_id": ""
    },
    "api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8080,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "78214bcb68c453a1a86ec17de4f85d07a72ae705189f08f8fa0db618ee3d8514",
        "ws_token": "mQKwqYQfogfz2BhQ1jXDER8llMZ7c3PwWQ",
        "CORS_origins": [],
        "username": "jeffe",
        "password": "123456"
    },
    "bot_name": "freqtrade",
    "initial_state": "running",
    "force_entry_enable": false,
    "internals": {
        "process_throttle_secs": 5
    }
}

> ### But if I use the Binance exchange, I can use the docker compose up command to start it normally。

> ### I hope you can help me answer. I've been looking for a problem for two days, it's so uncomfortable

**Comment by xmatthias** [comment]
well based on the error - it's `ccxt.base.errors.NetworkError: okx GET https://www.okx.com/api/v5/public/instruments?instType=SPOT`.
it simply means - that url wasn't available to the system at that point in time.

It's NOT the same issue as this one here - and is most likely either based on the region your'e in - or on temporary problems on the okx side.

**Comment by jeffe1024** [comment]
I have visited and reinstalled multiple times. It's still not possible. How should this be resolved?

**Comment by jeffe1024** [comment]
### Still reporting an error, could you help me answer it? Thank you：

>  requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.okx.com', port=443): Max retries exceeded with url: /api/v5/public/instruments?instType=SPOT (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7075f984c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2023-04-14 14:54:08 
2023-04-14 14:54:08 The above exception was the direct cause of the following exception:
2023-04-14 14:54:08 
2023-04-14 14:54:08 Traceback (most recent call last):
2023-04-14 14:54:08   File "/freqtrade/freqtrade/exchange/exchange.py", line 485, in _load_markets
2023-04-14 14:54:08     self._markets = self._api.load_markets(params={})
2023-04-14 14:54:08   File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 1458, in load_markets
2023-04-14 14:54:08     markets = self.fetch_markets(params)
2023-04-14 14:54:08   File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/okx.py", line 977, in fetch_markets
2023-04-14 14:54:08     promises.append(self.fetch_markets_by_type(types[i], params))
2023-04-14 14:54:08   File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/okx.py", line 1143, in fetch_markets_by_type
2023-04-14 14:54:08     response = self.publicGetPublicInstruments(self.extend(request, params))
2023-04-14 14:54:08   File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 505, in inner
2023-04-14 14:54:08     return entry(_self, **inner_kwargs)
2023-04-14 14:54:08   File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2932, in request
2023-04-14 14:54:08     return self.fetch2(path, api, method, params, headers, body, config, context)
2023-04-14 14:54:08   File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2929, in fetch2
2023-04-14 14:54:08     return self.fetch(request['url'], request['method'], request['headers'], request['body'])
2023-04-14 14:54:08   File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 652, in fetch
2023-04-14 14:54:08     raise NetworkError(details) from e
2023-04-14 14:54:08 ccxt.base.errors.NetworkError: okx GET https://www.okx.com/api/v5/public/instruments?instType=SPOT
2023-04-14 14:54:08 2023-04-14 06:54:08,248 - freqtrade.commands.trade_commands - ERROR - Could not load markets, therefore cannot start. Please investigate the above error for more details.
2023-04-14 14:54:08 2023-04-14 06:54:08,249 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
2023-04-14 14:54:08 Traceback (most recent call last):
2023-04-14 14:54:08   File "/freqtrade/freqtrade/commands/trade_commands.py", line 24, in start_trading
2023-04-14 14:54:08     worker = Worker(args)
2023-04-14 14:54:08   File "/freqtrade/freqtrade/worker.py", line 37, in __init__
2023-04-14 14:54:08     self._init(False)
2023-04-14 14:54:08   File "/freqtrade/freqtrade/worker.py", line 53, in _init
2023-04-14 14:54:08     self.freqtrade = FreqtradeBot(self._config)
2023-04-14 14:54:08   File "/freqtrade/freqtrade/freqtradebot.py", line 70, in __init__
2023-04-14 14:54:08     self.exchange = ExchangeResolver.load_exchange(
2023-04-14 14:54:08   File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 34, in load_exchange
2023-04-14 14:54:08     exchange = ExchangeResolver._load_exchange(
2023-04-14 14:54:08   File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 60, in _load_exchange
2023-04-14 14:54:08     exchange = ex_class(**kwargs)
2023-04-14 14:54:08   File "/freqtrade/freqtrade/exchange/exchange.py", line 185, in __init__
2023-04-14 14:54:08     self.validate_config(config)
2023-04-14 14:54:08   File "/freqtrade/freqtrade/exchange/exchange.py", line 218, in validate_config
2023-04-14 14:54:08     self.validate_stakecurrency(config['stake_currency'])
2023-04-14 14:54:08   File "/freqtrade/freqtrade/exchange/exchange.py", line 520, in validate_stakecurrency
2023-04-14 14:54:08     raise OperationalException(
2023-04-14 14:54:08 freqtrade.exceptions.OperationalException: Could not load markets, therefore cannot start. Please investigate the above error for more details.

**Comment by xmatthias** [comment]
Definitely not by highjacking old, solved issues that have little to nothing to do with your issue.

Best open a new issue containing the full exception / logs.
