### ISSUE TITLE
problem in running freqtrade bot 

### ISSUE THREAD

**Issue by hasanka1** [freqtrade/freqtrade#6219]
## Describe your environment

  * Operating system: ____ ubuntu 20.04
  * Python Version: _____ (`python -V`) 3.6.15
  * CCXT version: _____ (`pip freeze | grep ccxt`)  ccxt==1.67.21

  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)  freqtrade 0.17.3
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

when i am running the bot its terminating after few seconds , below error is mentioned also in the log
*Explain the problem you have encountered*

### Steps to reproduce:

  1. _____running freqtrade 
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
  `{
    "max_open_trades": 3,
    "stake_currency": "BTC",
    "stake_amount": 0.05,
    "fiat_display_currency": "USD",
    "ticker_interval" : "5m",
    "dry_run": true,
    "trailing_stop": false,
    "unfilledtimeout": {
        "buy": 10,
        "sell": 30
    },
    "bid_strategy": {
        "ask_last_balance": 0.0,
        "use_order_book": false,
        "order_book_top": 1,
        "check_depth_of_market": {
            "enabled": false,
        "order_book_max": 9
    },
    "exchange": {
        "name": "binance",
        "key": "hy0ueCtrYkzpByuwD4YEJySoPq9bwxlyLmKVG1mglh16Rh0iZSzA6LhDiXtxMykx",
        "secret": "D9u42gAeHCUCm0Ws6eBfZzcYNQ3baMHCdz9QuJqhv6xvKUzbOhoxzBBzm34X0QJO",
        "ccxt_config": {"enableRateLimit": true},
        "ccxt_async_config": {
            "enableRateLimit": false
        },
        "pair_whitelist": [
            "ETH/BTC",
            "LTC/BTC",
            "ETC/BTC",
            "DASH/BTC",
            "ZEC/BTC",
            "XLM/BTC",
            "POWR/BTC",
            "ADA/BTC",
            "XMR/BTC"
        ],
        "pair_blacklist": [
            "bids_to_ask_delta": 1
        }
    },
    "ask_strategy":{
        "use_order_book": false,
        "order_book_min": 1,
            "DOGE/BTC"
        ]
    },
    "experimental": {
        "use_sell_signal": false,
        "sell_profit_only": false,
        "ignore_roi_if_buy_signal": false
    },
    "edge": {
        "enabled": false,
        "process_throttle_secs": 3600,
        "calculate_since_number_of_days": 7,
        "capital_available_percentage": 0.5,
        "allowed_risk": 0.01,
        "stoploss_range_min": -0.01,
        "stoploss_range_max": -0.1,
        "stoploss_range_step": -0.01,
        "minimum_winrate": 0.60,
        "minimum_expectancy": 0.20,
        "min_trade_number": 10,
        "max_trade_duration_minute": 1440,
        "remove_pumps": false
    },
    "telegram": {
        "enabled": true,
        "token": "5003915281:AAHSXKOYclMkRWobPU94hSSEvxfnKENqnRE",
        "chat_id": "1816567884"
    },
    "initial_state": "running",
    "forcebuy_enable": false,
    "internals": {
        "process_throttle_secs": 5
    }
}


*******************************
(.env) hassan@ubuntu:~/freqtrade$ freqtrade/main.py -c config.json 
2022-01-13 02:33:10,575 - freqtrade.configuration - INFO - Verbosity set to 0
2022-01-13 02:33:10,576 - freqtrade.configuration - INFO - Dry run is enabled
2022-01-13 02:33:10,576 - freqtrade.configuration - INFO - Using DB: "sqlite://"
2022-01-13 02:33:10,576 - freqtrade.configuration - INFO - Using max_open_trades: 3 ...
2022-01-13 02:33:10,576 - freqtrade.configuration - INFO - Using data folder: user_data/data/binance ...
2022-01-13 02:33:10,577 - freqtrade.freqtradebot - INFO - Starting freqtrade 0.17.3
2022-01-13 02:33:10,578 - freqtrade.resolvers.strategy_resolver - INFO - Using resolved strategy DefaultStrategy from '/home/hassan/freqtrade/freqtrade/strategy'
2022-01-13 02:33:10,578 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ticker_interval' with value in config file: 5m.
2022-01-13 02:33:10,579 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'trailing_stop' with value in config file: False.
2022-01-13 02:33:10,579 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'40': 0.0, '30': 0.01, '20': 0.02, '0': 0.04}
2022-01-13 02:33:10,579 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ticker_interval: 5m
2022-01-13 02:33:10,579 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.1
2022-01-13 02:33:10,579 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2022-01-13 02:33:10,579 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
2022-01-13 02:33:10,579 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False}
2022-01-13 02:33:10,579 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
2022-01-13 02:33:10,579 - freqtrade.rpc.rpc_manager - INFO - Enabling rpc.telegram ...
/home/hassan/freqtrade/.env/lib/python3.6/site-packages/telegram/ext/dispatcher.py:251: UserWarning: Asynchronous callbacks can not be processed without at least one worker thread.
  'Asynchronous callbacks can not be processed without at least one worker thread.'
/home/hassan/freqtrade/freqtrade/rpc/telegram.py:104: TelegramDeprecationWarning: The argument `clean` of `start_polling` is deprecated. Please use `drop_pending_updates` instead.
  read_latency=60,
2022-01-13 02:33:10,863 - apscheduler.scheduler - INFO - Scheduler started
2022-01-13 02:33:11,867 - freqtrade.rpc.telegram - INFO - rpc.telegram is listening for following commands: [['status'], ['profit'], ['balance'], ['start'], ['stop'], ['forcesell'], ['forcebuy'], ['performance'], ['daily'], ['count'], ['reload_conf'], ['whitelist'], ['help'], ['version']]
2022-01-13 02:33:11,868 - freqtrade.rpc.fiat_convert - ERROR - Could not load FIAT Cryptocurrency map for the following problem: AttributeError
2022-01-13 02:33:11,869 - freqtrade.exchange - INFO - Instance is running with dry_run enabled
2022-01-13 02:33:11,869 - freqtrade.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2022-01-13 02:33:11,897 - freqtrade.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': False}
2022-01-13 02:33:11,924 - freqtrade.exchange - INFO - Using Exchange "Binance"
2022-01-13 02:33:14,033 - freqtrade.wallets - INFO - Wallets synced ...
2022-01-13 02:33:14,034 - freqtrade.resolvers.pairlist_resolver - WARNING - Path "user_data/pairlist" does not exist
2022-01-13 02:33:14,035 - freqtrade.resolvers.pairlist_resolver - INFO - Using resolved pairlist StaticPairList from '/home/hassan/freqtrade/freqtrade/pairlist'
2022-01-13 02:33:14,053 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'running'}
2022-01-13 02:33:14,915 - freqtrade.freqtradebot - INFO - Changing state to: RUNNING
2022-01-13 02:33:14,915 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': warning, 'status': 'Dry run is enabled. All trades are simulated.'}
2022-01-13 02:33:15,299 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': custom, 'status': "*Exchange:* `binance`\n*Stake per trade:* `0.05 BTC`\n*Minimum ROI:* `{'40': 0.0, '30': 0.01, '20': 0.02, '0': 0.04}`\n*Ticker Interval:* `5m`\n*Strategy:* `DefaultStrategy`"}
2022-01-13 02:33:15,756 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': "Searching for BTC pairs to buy and sell based on StaticPairList: ['ETH/BTC', 'LTC/BTC', 'ETC/BTC', 'DASH/BTC', 'ZEC/BTC', 'XLM/BTC', 'POWR/BTC', 'ADA/BTC', 'XMR/BTC']"}
2022-01-13 02:33:16,545 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "freqtrade/main.py", line 49, in main
    state = freqtrade.worker(old_state=state)
  File "/home/hassan/freqtrade/freqtrade/freqtradebot.py", line 122, in worker
    min_secs=min_secs)
  File "/home/hassan/freqtrade/freqtrade/freqtradebot.py", line 134, in _throttle
    result = func(*args, **kwargs)
  File "/home/hassan/freqtrade/freqtrade/freqtradebot.py", line 170, in _process
    self.exchange.refresh_tickers(self.active_pair_whitelist, self.strategy.ticker_interval)
  File "/home/hassan/freqtrade/freqtrade/exchange/__init__.py", line 536, in refresh_tickers
    self.async_get_candles_history(pair_list, ticker_interval))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 488, in run_until_complete
    return future.result()
  File "/home/hassan/freqtrade/freqtrade/exchange/__init__.py", line 548, in async_get_candles_history
    arrow.utcnow().timestamp and pair in self._klines):
TypeError: '>=' not supported between instances of 'int' and 'method'
2022-01-13 02:33:16,546 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2022-01-13 02:33:16,903 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2022-01-13 02:33:16,904 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
2022-01-13 02:33:16,904 - apscheduler.scheduler - INFO - Scheduler has been shut down

**Comment by xmatthias** [comment]
Your version (0.17.3) is more than 3 years old.
Please understand that we will not attempt to provide support for this.

Best reinstall an uptodate version of freqtrade.

**Comment by hasanka1** [comment]
hi mate , getting below error when doing fresh installation of freq trade , please advise 

assan@ubuntu:~/freqtrade$ ./setup.sh --install
/usr/bin/python3.8
using python3.8
----------------------------
Installing mandatory dependencies
----------------------------
Debian/Ubuntu detected. Setup for this system in-progress
[sudo] password for hassan: 
Hit:1 http://us.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://security.ubuntu.com/ubuntu focal-security InRelease
Hit:3 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:4 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease
Reading package lists... Done
E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 16806 (unattended-upgr)
N: Be aware that removing the lock file is not a solution and may break your system.
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
Installing to /usr/local
ta-lib/
ta-lib/config.sub
ta-lib/aclocal.m4
ta-lib/CHANGELOG.TXT
ta-lib/include/
ta-lib/include/ta_abstract.h
ta-lib/include/ta_func.h
ta-lib/include/ta_common.h
ta-lib/include/ta_config.h.in
ta-lib/include/Makefile.am
ta-lib/include/ta_libc.h
ta-lib/include/ta_defs.h
ta-lib/missing
ta-lib/ta-lib.spec.in
ta-lib/config.guess
ta-lib/Makefile.in
ta-lib/ta-lib.dpkg.in
ta-lib/Makefile.am
ta-lib/autogen.sh
ta-lib/install-sh
ta-lib/configure
ta-lib/depcomp
ta-lib/HISTORY.TXT
ta-lib/configure.in
ta-lib/autom4te.cache/
ta-lib/autom4te.cache/output.0
ta-lib/autom4te.cache/requests
ta-lib/autom4te.cache/output.1
ta-lib/autom4te.cache/traces.0
ta-lib/autom4te.cache/traces.1
ta-lib/ltmain.sh
ta-lib/ta-lib-config.in
ta-lib/src/
ta-lib/src/ta_func/
ta-lib/src/ta_func/ta_MACDFIX.c
ta-lib/src/ta_func/ta_CDLPIERCING.c
ta-lib/src/ta_func/ta_DIV.c
ta-lib/src/ta_func/ta_ROCR100.c
ta-lib/src/ta_func/ta_ADXR.c
ta-lib/src/ta_func/ta_MAVP.c
ta-lib/src/ta_func/ta_CDLCLOSINGMARUBOZU.c
ta-lib/src/ta_func/ta_COSH.c
ta-lib/src/ta_func/ta_EXP.c
ta-lib/src/ta_func/ta_MINMAXINDEX.c
ta-lib/src/ta_func/ta_SQRT.c
ta-lib/src/ta_func/ta_FLOOR.c
ta-lib/src/ta_func/ta_CDLCONCEALBABYSWALL.c
ta-lib/src/ta_func/ta_NATR.c
ta-lib/src/ta_func/ta_CDLHARAMICROSS.c
ta-lib/src/ta_func/ta_MINUS_DM.c
ta-lib/src/ta_func/ta_LOG10.c
ta-lib/src/ta_func/ta_LINEARREG_ANGLE.c
ta-lib/src/ta_func/ta_RSI.c
ta-lib/src/ta_func/ta_CDLABANDONEDBABY.c
ta-lib/src/ta_func/ta_SAR.c
ta-lib/src/ta_func/ta_CDLBREAKAWAY.c
ta-lib/src/ta_func/ta_CDLDRAGONFLYDOJI.c
ta-lib/src/ta_func/ta_CDLHIGHWAVE.c
ta-lib/src/ta_func/ta_CDLKICKING.c
ta-lib/src/ta_func/ta_CDLDOJISTAR.c
ta-lib/src/ta_func/ta_VAR.c
ta-lib/src/ta_func/ta_CDLMATCHINGLOW.c
ta-lib/src/ta_func/ta_CDLGAPSIDESIDEWHITE.c
ta-lib/src/ta_func/ta_CDLMARUBOZU.c
ta-lib/src/ta_func/ta_AROONOSC.c
ta-lib/src/ta_func/ta_WCLPRICE.c
ta-lib/src/ta_func/ta_CDLEVENINGDOJISTAR.c
ta-lib/src/ta_func/ta_CDL3INSIDE.c
ta-lib/src/ta_func/ta_OBV.c
ta-lib/src/ta_func/ta_AROON.c
ta-lib/src/ta_func/ta_CDLBELTHOLD.c
ta-lib/src/ta_func/ta_CDLSPINNINGTOP.c
ta-lib/src/ta_func/ta_AD.c
ta-lib/src/ta_func/ta_MAX.c
ta-lib/src/ta_func/ta_CDLENGULFING.c
ta-lib/src/ta_func/ta_MINMAX.c
ta-lib/src/ta_func/ta_CDLINNECK.c
ta-lib/src/ta_func/ta_STDDEV.c
ta-lib/src/ta_func/ta_NVI.c
ta-lib/src/ta_func/ta_CDLHAMMER.c
ta-lib/src/ta_func/ta_ASIN.c
ta-lib/src/ta_func/ta_SUM.c
ta-lib/src/ta_func/ta_STOCH.c
ta-lib/src/ta_func/ta_CDLLONGLEGGEDDOJI.c
ta-lib/src/ta_func/ta_MEDPRICE.c
ta-lib/src/ta_func/ta_CDL3STARSINSOUTH.c
ta-lib/src/ta_func/ta_HT_TRENDMODE.c
ta-lib/src/ta_func/ta_BBANDS.c
ta-lib/src/ta_func/ta_CDLMORNINGSTAR.c
ta-lib/src/ta_func/ta_HT_DCPHASE.c
ta-lib/src/ta_func/ta_CDLLONGLINE.c
ta-lib/src/ta_func/ta_TAN.c
ta-lib/src/ta_func/ta_SMA.c
ta-lib/src/ta_func/ta_DX.c
ta-lib/src/ta_func/ta_MIDPOINT.c
ta-lib/src/ta_func/ta_CDL2CROWS.c
ta-lib/src/ta_func/ta_CORREL.c
ta-lib/src/ta_func/ta_CDL3BLACKCROWS.c
ta-lib/src/ta_func/ta_ADD.c
ta-lib/src/ta_func/Makefile.in
ta-lib/src/ta_func/ta_CDLTHRUSTING.c
ta-lib/src/ta_func/ta_SUB.c
ta-lib/src/ta_func/ta_CDLSTALLEDPATTERN.c
ta-lib/src/ta_func/ta_CDLTRISTAR.c
ta-lib/src/ta_func/ta_MA.c
ta-lib/src/ta_func/ta_HT_SINE.c
ta-lib/src/ta_func/ta_ACOS.c
ta-lib/src/ta_func/ta_CDLSTICKSANDWICH.c
ta-lib/src/ta_func/ta_SINH.c
ta-lib/src/ta_func/ta_utility.h
ta-lib/src/ta_func/ta_CDLSHORTLINE.c
ta-lib/src/ta_func/ta_ATAN.c
ta-lib/src/ta_func/ta_CDLADVANCEBLOCK.c
ta-lib/src/ta_func/ta_CDLKICKINGBYLENGTH.c
ta-lib/src/ta_func/ta_CDLSHOOTINGSTAR.c
ta-lib/src/ta_func/ta_ROCR.c
ta-lib/src/ta_func/ta_WMA.c
ta-lib/src/ta_func/ta_CDLDARKCLOUDCOVER.c
ta-lib/src/ta_func/ta_CDLXSIDEGAP3METHODS.c
ta-lib/src/ta_func/ta_TYPPRICE.c
ta-lib/src/ta_func/ta_CDL3WHITESOLDIERS.c
ta-lib/src/ta_func/Makefile.am
ta-lib/src/ta_func/ta_MACDEXT.c
ta-lib/src/ta_func/ta_ADX.c
ta-lib/src/ta_func/ta_PLUS_DM.c
ta-lib/src/ta_func/ta_CDLUPSIDEGAP2CROWS.c
ta-lib/src/ta_func/ta_LN.c
ta-lib/src/ta_func/ta_DEMA.c
ta-lib/src/ta_func/ta_CDL3OUTSIDE.c
ta-lib/src/ta_func/ta_CDLTASUKIGAP.c
ta-lib/src/ta_func/ta_MAMA.c
ta-lib/src/ta_func/ta_CDLMORNINGDOJISTAR.c
ta-lib/src/ta_func/ta_PLUS_DI.c
ta-lib/src/ta_func/ta_MININDEX.c
ta-lib/src/ta_func/ta_COS.c
ta-lib/src/ta_func/ta_HT_TRENDLINE.c
ta-lib/src/ta_func/ta_MIDPRICE.c
ta-lib/src/ta_func/ta_CEIL.c
ta-lib/src/ta_func/ta_TRIMA.c
ta-lib/src/ta_func/ta_CDLSEPARATINGLINES.c
ta-lib/src/ta_func/ta_ROCP.c
ta-lib/src/ta_func/ta_CDLHOMINGPIGEON.c
ta-lib/src/ta_func/ta_CDLHANGINGMAN.c
ta-lib/src/ta_func/ta_AVGPRICE.c
ta-lib/src/ta_func/ta_APO.c
ta-lib/src/ta_func/ta_CDLRISEFALL3METHODS.c
ta-lib/src/ta_func/ta_TRANGE.c
ta-lib/src/ta_func/ta_TSF.c
ta-lib/src/ta_func/ta_LINEARREG.c
ta-lib/src/ta_func/ta_PVI.c
ta-lib/src/ta_func/ta_CDLHIKKAKEMOD.c
ta-lib/src/ta_func/ta_MFI.c
ta-lib/src/ta_func/ta_CDLHARAMI.c
ta-lib/src/ta_func/ta_MACD.c
ta-lib/src/ta_func/ta_BETA.c
ta-lib/src/ta_func/ta_CDLINVERTEDHAMMER.c
ta-lib/src/ta_func/ta_LINEARREG_SLOPE.c
ta-lib/src/ta_func/ta_STOCHF.c
ta-lib/src/ta_func/ta_MIN.c
ta-lib/src/ta_func/ta_CDLIDENTICAL3CROWS.c
ta-lib/src/ta_func/ta_CDLRICKSHAWMAN.c
ta-lib/src/ta_func/ta_T3.c
ta-lib/src/ta_func/ta_CDLMATHOLD.c
ta-lib/src/ta_func/ta_CDLUNIQUE3RIVER.c
ta-lib/src/ta_func/ta_ADOSC.c
ta-lib/src/ta_func/ta_MAXINDEX.c
ta-lib/src/ta_func/ta_ULTOSC.c
ta-lib/src/ta_func/ta_TRIX.c
ta-lib/src/ta_func/ta_MOM.c
ta-lib/src/ta_func/ta_CDLDOJI.c
ta-lib/src/ta_func/ta_EMA.c
ta-lib/src/ta_func/ta_STOCHRSI.c
ta-lib/src/ta_func/ta_ROC.c
ta-lib/src/ta_func/ta_CDLEVENINGSTAR.c
ta-lib/src/ta_func/ta_CDLCOUNTERATTACK.c
ta-lib/src/ta_func/ta_LINEARREG_INTERCEPT.c
ta-lib/src/ta_func/ta_SAREXT.c
ta-lib/src/ta_func/ta_WILLR.c
ta-lib/src/ta_func/ta_MULT.c
ta-lib/src/ta_func/ta_ATR.c
ta-lib/src/ta_func/ta_BOP.c
ta-lib/src/ta_func/ta_CMO.c
ta-lib/src/ta_func/ta_CDLONNECK.c
ta-lib/src/ta_func/ta_CCI.c
ta-lib/src/ta_func/ta_CDLLADDERBOTTOM.c
ta-lib/src/ta_func/ta_HT_PHASOR.c
ta-lib/src/ta_func/ta_utility.c
ta-lib/src/ta_func/ta_PPO.c
ta-lib/src/ta_func/ta_CDLHIKKAKE.c
ta-lib/src/ta_func/ta_HT_DCPERIOD.c
ta-lib/src/ta_func/ta_CDL3LINESTRIKE.c
ta-lib/src/ta_func/ta_TEMA.c
ta-lib/src/ta_func/ta_SIN.c
ta-lib/src/ta_func/ta_MINUS_DI.c
ta-lib/src/ta_func/ta_KAMA.c
ta-lib/src/ta_func/ta_TANH.c
ta-lib/src/ta_func/ta_CDLTAKURI.c
ta-lib/src/ta_func/ta_CDLGRAVESTONEDOJI.c
ta-lib/src/ta_common/
ta-lib/src/ta_common/ta_pragma.h
ta-lib/src/ta_common/ta_magic_nb.h
ta-lib/src/ta_common/ta_retcode.csv
ta-lib/src/ta_common/Makefile.in
ta-lib/src/ta_common/Makefile.am
ta-lib/src/ta_common/ta_memory.h
ta-lib/src/ta_common/ta_version.c
ta-lib/src/ta_common/ta_global.h
ta-lib/src/ta_common/ta_global.c
ta-lib/src/ta_common/ta_retcode.c
ta-lib/src/Makefile.in
ta-lib/src/ta_abstract/
ta-lib/src/ta_abstract/frames/
ta-lib/src/ta_abstract/frames/ta_frame.c
ta-lib/src/ta_abstract/frames/ta_frame.h
ta-lib/src/ta_abstract/excel_glue.c
ta-lib/src/ta_abstract/ta_frame_priv.h
ta-lib/src/ta_abstract/ta_func_api.c
ta-lib/src/ta_abstract/Makefile.in
ta-lib/src/ta_abstract/ta_def_ui.h
ta-lib/src/ta_abstract/Makefile.am
ta-lib/src/ta_abstract/ta_abstract.c
ta-lib/src/ta_abstract/ta_group_idx.c
ta-lib/src/ta_abstract/tables/
ta-lib/src/ta_abstract/tables/table_u.c
ta-lib/src/ta_abstract/tables/table_x.c
ta-lib/src/ta_abstract/tables/table_r.c
ta-lib/src/ta_abstract/tables/table_f.c
ta-lib/src/ta_abstract/tables/table_j.c
ta-lib/src/ta_abstract/tables/table_e.c
ta-lib/src/ta_abstract/tables/table_t.c
ta-lib/src/ta_abstract/tables/table_n.c
ta-lib/src/ta_abstract/tables/table_i.c
ta-lib/src/ta_abstract/tables/table_c.c
ta-lib/src/ta_abstract/tables/table_l.c
ta-lib/src/ta_abstract/tables/table_k.c
ta-lib/src/ta_abstract/tables/table_g.c
ta-lib/src/ta_abstract/tables/table_d.c
ta-lib/src/ta_abstract/tables/table_h.c
ta-lib/src/ta_abstract/tables/table_o.c
ta-lib/src/ta_abstract/tables/table_b.c
ta-lib/src/ta_abstract/tables/table_q.c
ta-lib/src/ta_abstract/tables/table_v.c
ta-lib/src/ta_abstract/tables/table_m.c
ta-lib/src/ta_abstract/tables/table_s.c
ta-lib/src/ta_abstract/tables/table_y.c
ta-lib/src/ta_abstract/tables/table_p.c
ta-lib/src/ta_abstract/tables/table_z.c
ta-lib/src/ta_abstract/tables/table_a.c
ta-lib/src/ta_abstract/tables/table_w.c
ta-lib/src/ta_abstract/ta_def_ui.c
ta-lib/src/ta_abstract/templates/
ta-lib/src/ta_abstract/templates/ta_x.c.template
ta-lib/src/ta_abstract/templates/ta_java_defs.h.template
ta-lib/src/ta_abstract/templates/excel_glue.c.template
ta-lib/src/ta_abstract/templates/ta_group_idx.c.template
ta-lib/src/ta_abstract/templates/ta_frame.c.template
ta-lib/src/ta_abstract/templates/CoreAnnotated.java.template
ta-lib/src/ta_abstract/templates/ta_func.h.template
ta-lib/src/ta_abstract/templates/ta_frame.h.template
ta-lib/src/ta_abstract/templates/Makefile.am.template
ta-lib/src/ta_abstract/templates/ta_func_api.c.template
ta-lib/src/ta_abstract/templates/ta_func.swg.template
ta-lib/src/ta_abstract/templates/ta_retcode.c.template
ta-lib/src/ta_abstract/ta_java_defs.h
ta-lib/src/Makefile.am
ta-lib/src/tools/
ta-lib/src/tools/ta_regtest/
ta-lib/src/tools/ta_regtest/test_util.c
ta-lib/src/tools/ta_regtest/ta_test_func.h
ta-lib/src/tools/ta_regtest/test_data.c
ta-lib/src/tools/ta_regtest/ta_gDataHigh.c
ta-lib/src/tools/ta_regtest/Makefile.in
ta-lib/src/tools/ta_regtest/test_internals.c
ta-lib/src/tools/ta_regtest/Makefile.am
ta-lib/src/tools/ta_regtest/ta_regtest.c
ta-lib/src/tools/ta_regtest/ta_gDataOpen.c
ta-lib/src/tools/ta_regtest/ta_gDataClose.c
ta-lib/src/tools/ta_regtest/test_abstract.c
ta-lib/src/tools/ta_regtest/ta_test_func/
ta-lib/src/tools/ta_regtest/ta_test_func/test_bbands.c
ta-lib/src/tools/ta_regtest/ta_test_func/test_stddev.c
ta-lib/src/tools/ta_regtest/ta_test_func/test_1in_2out.c
ta-lib/src/tools/ta_regtest/ta_test_func/test_sar.c
ta-lib/src/tools/ta_regtest/ta_test_func/test_1in_1out.c
ta-lib/src/tools/ta_regtest/ta_test_func/test_trange.c
ta-lib/src/tools/ta_regtest/ta_test_func/test_macd.c
ta-lib/src/tools/ta_regtest/ta_test_func/test_po.c
ta-lib/src/tools/ta_regtest/ta_test_func/test_per_hlc.c
ta-lib/src/tools/ta_regtest/ta_test_func/test_mom.c
ta-lib/src/tools/ta_regtest/ta_test_func/test_per_ohlc.c
ta-lib/src/tools/ta_regtest/ta_test_func/test_adx.c
ta-lib/src/tools/ta_regtest/ta_test_func/test_candlestick.c
ta-lib/src/tools/ta_regtest/ta_test_func/test_rsi.c
ta-lib/src/tools/ta_regtest/ta_test_func/test_per_ema.c
ta-lib/src/tools/ta_regtest/ta_test_func/test_minmax.c
ta-lib/src/tools/ta_regtest/ta_test_func/test_per_hlcv.c
ta-lib/src/tools/ta_regtest/ta_test_func/test_per_hl.c
ta-lib/src/tools/ta_regtest/ta_test_func/test_stoch.c
ta-lib/src/tools/ta_regtest/ta_test_func/test_ma.c
ta-lib/src/tools/ta_regtest/ta_error_number.h
ta-lib/src/tools/ta_regtest/ta_test_priv.h
ta-lib/src/tools/ta_regtest/ReadMe.txt
ta-lib/src/tools/ta_regtest/ta_gDataLow.c
ta-lib/src/tools/Makefile.in
ta-lib/src/tools/Makefile.am
ta-lib/src/tools/gen_code/
ta-lib/src/tools/gen_code/java/
ta-lib/src/tools/gen_code/java/PrettyCode.java
ta-lib/src/tools/gen_code/java/Main.java
ta-lib/src/tools/gen_code/gen_code.c
ta-lib/src/tools/gen_code/Makefile.in
ta-lib/src/tools/gen_code/Makefile.am
ta-lib/src/tools/gen_code/mcpp.exe
./install_ta-lib.sh: line 11: curl: command not found
**Failed building ta-lib.
Quitting. Please fix the above error before continuing.**
hassan@ubuntu:~/freqtrade$

**Comment by xmatthias** [comment]
`curl` is not found.
you can install that usually with `apt-get install curl`.

**Comment by hasanka1** [comment]
thanks it worked ... 👍

**Comment by hasanka1** [comment]
hello mate , now made some progress but still not able to local config.json file .. do i need to create or clone from the example folder ?
below is the error output 

(.env) hassan@ubuntu:~/freqtrade$ freqtrade trade -c user_data/config.json -s sample_strategy.py
2022-01-14 08:32:00,679 - freqtrade.worker - INFO - Starting worker develop-13651fd3b
2022-01-14 08:32:00,679 - freqtrade.configuration.configuration - INFO - Using config: user_data/config.json ...
2022-01-14 08:32:00,679 - freqtrade.commands.trade_commands - ERROR - Config file "user_data/config.json" not found! Please create a config file or check whether it exists.
2022-01-14 08:32:00,679 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/hassan/freqtrade/freqtrade/configuration/load_config.py", line 58, in load_config_file
    with open(path) if path != '-' else sys.stdin as file:
FileNotFoundError: [Errno 2] No such file or directory: 'user_data/config.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hassan/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/home/hassan/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/home/hassan/freqtrade/freqtrade/worker.py", line 49, in _init
    self._config = Configuration(self._args, None).get_config()
  File "/home/hassan/freqtrade/freqtrade/configuration/configuration.py", line 42, in get_config
    self.config = self.load_config()
  File "/home/hassan/freqtrade/freqtrade/configuration/configuration.py", line 98, in load_config
    config: Dict[str, Any] = self.load_from_files(self.args.get("config", []))
  File "/home/hassan/freqtrade/freqtrade/configuration/configuration.py", line 74, in load_from_files
    config = deep_merge_dicts(load_config_file(path), config)
  File "/home/hassan/freqtrade/freqtrade/configuration/load_config.py", line 61, in load_config_file
    raise OperationalException(
freqtrade.exceptions.OperationalException: Config file "user_data/config.json" not found! Please create a config file or check whether it exists.
(.env) hassan@ubuntu:~/freqtrade$

**Comment by xmatthias** [comment]
> Config file "user_data/config.json" not found! Please create a config file or check whether it exists.

Please simply read the error message - it usually contains some information about the problem.
