### ISSUE TITLE
Making a "proxy".

### ISSUE THREAD

**Issue by jeronimd** [freqtrade/freqtrade#6280]
## Describe your environment

  * Operating system: Windows 10
  * Python Version: 3.8.10
  * CCXT version: 1.68.20
  * Freqtrade Version: docker-1505ad45
  
## Your question
Ok this is kinda out there but can you help me make a proxy of sorts? I'm trying to use the public API in the config file to pass all the requests trough a HTTP server.

So I have the path set in the config.json:
```
    "exchange": {
        "name": "binance",
        "key": "",
        "secret": "",
        "ccxt_config":{
            "enableRateLimit":false,
            "urls":{
               "api":{
                  "public":"http://127.0.0.1:8079/api/v3"
               }
            }
        },
```
And I use a simple python script to run the HTTP server and have it listen to all the requests that are made to it.
```python
#!/usr/bin/env python3

import http.server
import socketserver
import requests

PORT = 8079

class GetHandler(http.server.SimpleHTTPRequestHandler):
    def do_GET(self):
        print(self.headers)
        print(self.path)
        response = requests.get('https://api.binance.com' + self.path)
        self.wfile.write(response.content)


Handler = GetHandler
httpd = socketserver.TCPServer(("", PORT), Handler)

print("serving at port", PORT)
httpd.serve_forever()
```
I can receive the request from freqtrade in the HTTP server:
```
serving at port 8079
Host: 127.0.0.1:8079
User-Agent: python-requests/2.27.1
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive

/api/v3/exchangeInfo
```
But freqtrade outputs raise BadStatusLine(line).
```
ftuser@7ec0f9d621f8:/freqtrade$ freqtrade trade -c config.json -s SampleStrategy
2022-01-23 17:07:41,875 - freqtrade.worker - INFO - Starting worker docker-1505ad45
2022-01-23 17:07:41,875 - freqtrade.configuration.configuration - INFO - Using config: config.json ...
2022-01-23 17:07:41,875 - freqtrade.loggers - INFO - Verbosity set to 0
2022-01-23 17:07:41,875 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
2022-01-23 17:07:41,876 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2022-01-23 17:07:41,876 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:///tradesv3.dryrun.sqlite"
2022-01-23 17:07:41,876 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 3 ...
2022-01-23 17:07:41,887 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2022-01-23 17:07:41,887 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/binance ...
2022-01-23 17:07:41,887 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2022-01-23 17:07:41,897 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2022-01-23 17:07:41,897 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2022-01-23 17:07:41,897 - freqtrade.freqtradebot - INFO - Starting freqtrade docker-1505ad45
2022-01-23 17:07:41,908 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy SampleStrategy from '/freqtrade/user_data/strategies/sample_strategy.py'...
2022-01-23 17:07:41,908 - freqtrade.strategy.hyper - INFO - Found no parameter file.
2022-01-23 17:07:41,908 - freqtrade.strategy.hyper - INFO - No params for buy found, using default values.
2022-01-23 17:07:41,908 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): buy_rsi = 30
2022-01-23 17:07:41,909 - freqtrade.strategy.hyper - INFO - No params for sell found, using default values.
2022-01-23 17:07:41,909 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): sell_rsi = 70
2022-01-23 17:07:41,909 - freqtrade.strategy.hyper - INFO - No params for protection found, using default values.
2022-01-23 17:07:41,909 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2022-01-23 17:07:41,909 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 100.
2022-01-23 17:07:41,909 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'buy': 10, 'sell': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}.
2022-01-23 17:07:41,909 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'60': 0.01, '30': 0.02, '0': 0.04}
2022-01-23 17:07:41,909 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 5m
2022-01-23 17:07:41,909 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.1
2022-01-23 17:07:41,909 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2022-01-23 17:07:41,909 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2022-01-23 17:07:41,910 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2022-01-23 17:07:41,910 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2022-01-23 17:07:41,910 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
2022-01-23 17:07:41,910 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'market', 'stoploss_on_exchange': False}
2022-01-23 17:07:41,910 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
2022-01-23 17:07:41,910 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2022-01-23 17:07:41,910 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 100
2022-01-23 17:07:41,910 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2022-01-23 17:07:41,910 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 30
2022-01-23 17:07:41,910 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'buy': 10, 'sell': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}
2022-01-23 17:07:41,910 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_sell_signal: True
2022-01-23 17:07:41,910 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_only: False
2022-01-23 17:07:41,910 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_buy_signal: False
2022-01-23 17:07:41,910 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_offset: 0.0
2022-01-23 17:07:41,910 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2022-01-23 17:07:41,910 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2022-01-23 17:07:41,911 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: False
2022-01-23 17:07:41,911 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2022-01-23 17:07:41,913 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2022-01-23 17:07:41,914 - freqtrade.exchange.exchange - INFO - Using CCXT 1.68.20
2022-01-23 17:07:41,914 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': False, 'urls': {'api': {'public': 'http://127.0.0.1:8079/api/v3'}}}
2022-01-23 17:07:41,922 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': False, 'urls': {'api': {'public': 'http://127.0.0.1:8079/api/v3'}}}
2022-01-23 17:07:41,930 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2022-01-23 17:07:42,572 - freqtrade.exchange.exchange - ERROR - Unable to initialize markets.
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/usr/local/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.9/http/client.py", line 302, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: {"timezone":"UTC","serverTime":1642957662586,"rateLimits":[{"rateLimitType":"REQUEST_WEIGHT","interval":"MINUTE","intervalNum":1,"limit":1200},{"rateLimitType":"ORDERS","interval":"SECOND","intervalNum":10,"limit":50},{"rateLimitType":"ORDERS","interval":"DAY","intervalNum":1,"limit":160000},{"rateLimitType":"RAW_REQUESTS","interval":"MINUTE","intervalNum":5,"limit":6100}],"exchangeFilters":[],"symbols":[{"symbol":"ETHBTC","status":"TRADING","baseAsset":"ETH","baseAssetPrecision":8,"quoteAsset":"BTC","quotePrecision":8,"quoteAssetPrecision":8,"baseCommissionPrecision":8,"quoteCommissionPrecision":8,"orderTypes":["LIMIT","LIMIT_MAKER","MARKET","STOP_LOSS_LIMIT","TAKE_PROFIT_LIMIT"],"icebergAllowed":true,"ocoAllowed":true,"quoteOrderQtyMarketAllowed":true,"isSpotTradingAllowed":true,"isMarginTradingAllowed":true,"filters":[{"filterType":"PRICE_FILTER","minPrice":"0.00000100","maxPrice":"922327.00000000","tickSize":"0.00000100"},{"filterType":"PERCENT_PRICE","multiplierUp":"5","multiplierDown":"0.2","avgPriceMins":5},{"filterType":"LOT_SIZE"
5","multiplierDown":"0.2","avgPriceMins":5},{"filterType":"LOT_SIZE","minQty":"0.01000000","maxQty":"92141578.00000000","stepSize":"0.01000000"},{"filterType":"MIN_NOTIONAL","minNotional":"10.00000000","applyToMarket":true,"avgPriceMins":5},{"filterType":"ICEBERG_PARTS","limit":10},{"filterType":"MARKET_LOT_SIZE","minQty":"0.00000000","maxQty":"47305.42201388","stepSize":"0.00000000"},{"filterType":"MAX_NUM_ORDERS","maxNumOrders":200},{"filterType":"MAX_NUM_ALGO_ORDERS","maxNumAlgoOrders":5}],"permissions":["SPOT"]}]}'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/exchange.py", line 345, in _load_markets
    self._markets = self._api.load_markets()
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 1498, in load_markets
    markets = self.fetch_markets(params)
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/binance.py", line 1360, in fetch_markets
    response = getattr(self, method)(query)
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 504, in inner
    return entry(_self, **inner_kwargs)
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/binance.py", line 4868, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 551, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 695, in fetch
    raise NetworkError(details) from e
ccxt.base.errors.NetworkError: binance GET http://127.0.0.1:8079/api/v3/exchangeInfo
2022-01-23 17:22:39,968 - freqtrade.commands.trade_commands - ERROR - Could not load markets, therefore cannot start. Please investigate the above error for more details.
2022-01-23 17:22:39,968 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/freqtrade/freqtrade/worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/freqtrade/freqtrade/freqtradebot.py", line 65, in __init__
    self.exchange = ExchangeResolver.load_exchange(self.config['exchange']['name'], self.config)
  File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 32, in load_exchange
    exchange = ExchangeResolver._load_exchange(exchange_name,
  File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 54, in _load_exchange
    exchange = ex_class(**kwargs)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 157, in __init__
    self.validate_stakecurrency(config['stake_currency'])
  File "/freqtrade/freqtrade/exchange/exchange.py", line 376, in validate_stakecurrency
    raise OperationalException(
freqtrade.exceptions.OperationalException: Could not load markets, therefore cannot start. Please investigate the above error for more details.
```
I have been trying to do this for a few days trying different ways, but I always find a roadblock. So I decided to ask for help. If you have any tips or can help me I would be very grateful.

**Comment by xmatthias** [comment]
The exception points to a bad response (maybe wrong status code, bad encoding, or simply the wrong content).

Please note: overriding ccxt internals is not supported by freqtrade.
While we'll not prevent it - we're not providing support for it either.
