### ISSUE TITLE
hyperopt crashing on protector `stop_duration` param optimising

### ISSUE THREAD

**Issue by tonymorony** [freqtrade/freqtrade#6315]
First, thank you for the awesome software! 💯 

## Describe your environment

  * Operating system: Ubuntu 18.04
  * Python Version: Python 3.8.10 
  * CCXT version: ccxt==1.70.45
  * Freqtrade Version: freqtrade develop-2e2b1e247

## Describe the problem:

hyperopt crashing on protector `stop_duration` param optimising with IntParameter due to types incompatibility 

### Steps to reproduce:

  1. Create a protector with duration in minutes, e.g.
  ```python
  ...
  protection_time = IntParameter(1, 360, default=5, space="protection", optimize=True)
  ...
    @property
    def protections(self):
        prot = []

        prot.append({
            "method": "CooldownPeriod",
            "stop_duration": self.protection_time.value
        })
        return prot
   ```
  2. Try to optimize that, e.g. `freqtrade hyperopt --config config.json --hyperopt-loss SharpeHyperOptLossDaily --strategy lab_strat_test  -e 100 --min-trades 365 -i 1h  --timerange 20210101-20211231 -j 5 --spaces  protection`
  
### Observed Results:

  * Getting crash because of incompatible types

P.S. 
such type conversion `"stop_duration": int(self.protection_time.value)` make it work
seen this feature is in beta, hope this report is not excessive 

### Relevant code exceptions or logs

trace:

```
2022-01-29 07:11:52,966 - freqtrade.optimize.hyperopt - INFO - Effective number of parallel workers used: 5

2022-01-29 07:11:54,589 - freqtrade - ERROR - Fatal exception!
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/root/freqtrade/.env/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 436, in _process_worker
    r = call_item()
  File "/root/freqtrade/.env/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 288, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/root/freqtrade/.env/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/root/freqtrade/.env/lib/python3.8/site-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/root/freqtrade/.env/lib/python3.8/site-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/root/freqtrade/.env/lib/python3.8/site-packages/joblib/externals/loky/cloudpickle_wrapper.py", line 38, in __call__
    return self._obj(*args, **kwargs)
  File "/root/freqtrade/freqtrade/optimize/hyperopt.py", line 312, in generate_optimizer
    bt_results = self.backtesting.backtest(
  File "/root/freqtrade/freqtrade/optimize/backtesting.py", line 675, in backtest
    self.protections.stop_per_pair(pair, row[DATE_IDX])
  File "/root/freqtrade/freqtrade/plugins/protectionmanager.py", line 67, in stop_per_pair
    lock, until, reason = protection_handler.stop_per_pair(pair, now)
  File "/root/freqtrade/freqtrade/plugins/protections/cooldown_period.py", line 69, in stop_per_pair
    return self._cooldown_period(pair, date_now)
  File "/root/freqtrade/freqtrade/plugins/protections/cooldown_period.py", line 33, in _cooldown_period
    look_back_until = date_now - timedelta(minutes=self._stop_duration)
TypeError: unsupported type for timedelta minutes component: numpy.int64
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/root/freqtrade/freqtrade/commands/optimize_commands.py", line 103, in start_hyperopt
    hyperopt.start()
  File "/root/freqtrade/freqtrade/optimize/hyperopt.py", line 478, in start
    f_val = self.run_optimizer_parallel(parallel, asked, i)
  File "/root/freqtrade/freqtrade/optimize/hyperopt.py", line 391, in run_optimizer_parallel
    return parallel(delayed(
  File "/root/freqtrade/.env/lib/python3.8/site-packages/joblib/parallel.py", line 1056, in __call__
    self.retrieve()
  File "/root/freqtrade/.env/lib/python3.8/site-packages/joblib/parallel.py", line 935, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/root/freqtrade/.env/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
TypeError: unsupported type for timedelta minutes component: numpy.int64
(.env) root@ubuntu-2gb-hel1-1:~/freqtrade# nano user_data/strategies/lab_strat_test.py
```

**Comment by xmatthias** [comment]
using `"stop_duration": int(self.protection_time.value)` is the correct approach here - but this should happen in "user land" (speak, in the strategy).

In general, i'd recommend to optimize on candles, not on minutes (basically following the example and assigning to `stop_duration_candles`) - which doesn't have this problem.

We can't change the return-value of the protection to int - as this will depend on usage (if you use it for a buy space and compare it to values in a dataframe it'll be better as int64) - and we won't know how the parameter is used - therefore not doing the conversation is the most efficient way (avoiding unnecessary conversions, and only convert where necessary - which only the user will know).

**Comment by tonymorony** [comment]
thank you for the clarification 👍
