### ISSUE TITLE
Config creation script results in invalid value for unlimited max_open_trades

### ISSUE THREAD

**Issue by bigsee** [freqtrade/freqtrade#6319]
## Describe your environment

  * Operating system: Mac OS 11.6.1
  * Python Version: 3.9.9
  * CCXT version: _____
  * Freqtrade Version: 2021.12

## Describe the problem:

Freqtrade will not run using the json file created by the documented process if `unlimited` is chosen as the value for `max_open_trades`. This is my first time setting up the config.json using the interactive process, so maybe I've done something wrong.

### Steps to reproduce:

  1. Run `docker-compose run --rm freqtrade new-config --config user_data/foo.json` as shown in the documentation
  2. Enter the following values when prompted

<img width="1641" alt="Screenshot 2022-01-30 at 08 28 17" src="https://user-images.githubusercontent.com/11768967/151692436-62773ffa-2fe0-44be-8388-7a94eeef53ab.png">

  3. Try to download data: `docker-compose run --rm freqtrade download-data --pairs BTC/USDT --exchange binance --days 7 -t 5m`
  
### Observed Results:

The process fails at the `freqtrade.configuration.config_validation` step. My old configurations used the -1 value so I believe that is correct. When I manually change it, it works. I also tried another time to enter `'unlimited'` (with quotes) at the prompt but this input is rejected as invalid.

<img width="944" alt="Screenshot 2022-01-30 at 08 35 23" src="https://user-images.githubusercontent.com/11768967/151692622-ce070bec-c1dc-4e02-a1a2-debf560604cf.png">

### Relevant code exceptions or logs

  ```
Creating ft_userdata_freqtrade_run ... done
2022-01-30 08:10:18,983 - freqtrade.configuration.configuration - INFO - Using config: user_data/config.json ...
2022-01-30 08:10:18,987 - freqtrade.loggers - INFO - Verbosity set to 0
2022-01-30 08:10:18,988 - freqtrade.configuration.configuration - INFO - Using exchange binance
2022-01-30 08:10:19,023 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2022-01-30 08:10:19,026 - freqtrade.configuration.directory_operations - INFO - Created data directory: None
2022-01-30 08:10:19,026 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/binance ...
2022-01-30 08:10:19,026 - freqtrade.configuration.configuration - INFO - Using pairs ['BTC/USDT']
2022-01-30 08:10:19,026 - freqtrade.configuration.configuration - INFO - timeframes --timeframes: ['5m']
2022-01-30 08:10:19,026 - freqtrade.configuration.configuration - INFO - Detected --days: 7
2022-01-30 08:10:19,027 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2022-01-30 08:10:19,039 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2022-01-30 08:10:19,039 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2022-01-30 08:10:19,042 - freqtrade.configuration.config_validation - CRITICAL - Invalid configuration. Reason: 'unlimited' is not of type 'integer', 'number'

Failed validating 'type' in schema['properties']['max_open_trades']:
    {'minimum': -1, 'type': ['integer', 'number']}

On instance['max_open_trades']:
    'unlimited'
2022-01-30 08:10:19,044 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/data_commands.py", line 26, in start_download_data
    config = setup_utils_configuration(args, RunMode.UTIL_EXCHANGE)
  File "/freqtrade/freqtrade/configuration/config_setup.py", line 25, in setup_utils_configuration
    validate_config_consistency(config)
  File "/freqtrade/freqtrade/configuration/config_validation.py", line 86, in validate_config_consistency
    validate_config_schema(conf)
  File "/freqtrade/freqtrade/configuration/config_validation.py", line 61, in validate_config_schema
    raise ValidationError(
jsonschema.exceptions.ValidationError: 'unlimited' is not of type 'integer', 'number'
ERROR: 1
```

**Comment by stash86** [comment]
This is a bug. The text supposed to say 'Integer or -1 (for unlimited)'

Gonna send a fix
