### ISSUE TITLE
CCXT 1.71.46 causing freqtrade to crash on buy/sell order on gate.io

### ISSUE THREAD

**Issue by tomqw** [freqtrade/freqtrade#6339]
CCXT 1.71.46 used in develop is causing freqtrade to crash on buy/sell order on gate.io

```
2022-01-31 20:44:43,826 - freqtrade.freqtradebot - INFO - Executing Sell for DFYN/USDT. Reason: custom_sell. Tag: None
2022-01-31 20:44:44,086 - freqtrade.wallets - INFO - Wallets synced.
2022-01-31 20:44:44,087 - freqtrade.commands.trade_commands - ERROR -
2022-01-31 20:44:44,087 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker.run()
  File "/freqtrade/freqtrade/worker.py", line 74, in run
    state = self._worker(old_state=state)
  File "/freqtrade/freqtrade/worker.py", line 114, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
  File "/freqtrade/freqtrade/worker.py", line 139, in _throttle
    result = func(*args, **kwargs)
  File "/freqtrade/freqtrade/worker.py", line 152, in _process_running
    self.freqtrade.process()
  File "/freqtrade/freqtrade/freqtradebot.py", line 178, in process
    self.exit_positions(trades)
  File "/freqtrade/freqtrade/freqtradebot.py", line 775, in exit_positions
    if trade.open_order_id is None and trade.is_open and self.handle_trade(trade):
  File "/freqtrade/freqtrade/freqtradebot.py", line 813, in handle_trade
    if self._check_and_execute_exit(trade, sell_rate, buy, sell, exit_tag):
  File "/freqtrade/freqtrade/freqtradebot.py", line 965, in _check_and_execute_exit
    self.execute_trade_exit(trade, exit_rate, should_sell, exit_tag=exit_tag)
  File "/freqtrade/freqtrade/freqtradebot.py", line 1222, in execute_trade_exit
    order = self.exchange.create_order(pair=trade.pair,
  File "/freqtrade/freqtrade/exchange/exchange.py", line 759, in create_order
    amount = self.amount_to_precision(pair, amount)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 520, in amount_to_precision
    amount = float(decimal_to_precision(amount, rounding_mode=TRUNCATE,
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/decimal_to_precision.py", line 39, in decimal_to_precision
    assert(isinstance(precision, float) or isinstance(precision, numbers.Integral))
AssertionError
```
Issue has been fixed in newer version of CCXT (above 1.71.49): 
https://github.com/ccxt/ccxt/commit/9f1c8df75ba98efefc66ba979aa3989ee841b4a0

**Comment by xmatthias** [comment]
Thanks for reporting, will be fixed shortly
