### ISSUE TITLE
Crash when forcesell on dry_run mode

### ISSUE THREAD

**Issue by nareshn2003** [freqtrade/freqtrade#636]
## Step 1: Have you search for this issue before posting it?
Yes

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/gcarq/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

  * Python Version: 3.6
  * Branch: feat/objectify-ccxt
  * Last Commit ID:  43fd9b37

## Step 3: Describe the problem:
When bot is runing in dry run mode and with following parameters --dynamic-whitelist --dry-run-db
1) In Telegrame try to forcesell sepecific order i.e. /forcesell 5  
2) Now check /status table function to check if order has been remove from pending list this throws error
 

## Step 4: Steps to reproduce 

In telegrame
**1) /status table**

 ID  Pair     Since    Profit
----  -------  -------  --------
   5  ADA/BTC  17 h     -5.42%
  18  XRP/BTC  1 h      -0.62%

**2) /forcesell 5**
**3) /status table**

  ID  Pair     Since    Profit
----  -------  -------  --------
   5  ADA/BTC  17 h     -5.42%
  18  XRP/BTC  1 h      -0.62%

**Status: Stopping trader...**

### Relevant code exceptions or logs:

2018-05-04 07:51:06,419 - freqtrade.rpc.rpc_manager - INFO - *binance:* Selling
*Current Pair:* [ADA/BTC](https://www.binance.com/tradeDetail.html?symbol=ADA_BTC)
*Limit:* `3.734e-05`
*Amount:* `7616.14623001`
*Open Rate:* `0.00003939`
*Current Rate:* `0.00003734`
*Profit:* `-5.39%`` (loss: -5.39%, -0.01619749 BTC`` / -156.478 USD)`
2018-05-04 07:51:12,949 - freqtrade.freqtradebot - INFO - Found no buy signals for whitelisted currencies. Trying again..
2018-05-04 07:51:14,475 - freqtrade.freqtradebot - INFO - Found no sell signals for whitelisted currencies. Trying again..
2018-05-04 07:51:16,228 - freqtrade.freqtradebot - INFO - Found no sell signals for whitelisted currencies. Trying again..
2018-05-04 07:51:16,229 - freqtrade.freqtradebot - INFO - Checking buy signals to create a new trade with stake_amount: 0.300000 ...
2018-05-04 07:51:17,381 - freqtrade.rpc.telegram - INFO - Executing handler: _status for chat_id: 581651561
2018-05-04 07:51:17,382 - freqtrade.rpc.telegram - INFO - Executing handler: _status_table for chat_id: 581651561
2018-05-04 07:51:26,194 - freqtrade.freqtradebot - INFO - Found no buy signals for whitelisted currencies. Trying again..
2018-05-04 07:51:26,203 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "freqtrade/main.py", line 45, in main
    state = freqtrade.worker(old_state=state)
  File "/home/naresh/freqtrade/freqtrade/freqtradebot.py", line 120, in worker
    nb_assets=nb_assets)
  File "/home/naresh/freqtrade/freqtrade/freqtradebot.py", line 132, in _throttle
    result = func(*args, **kwargs)
  File "/home/naresh/freqtrade/freqtrade/freqtradebot.py", line 172, in _process
    self.check_handle_timedout(self.config['unfilledtimeout'])
  File "/home/naresh/freqtrade/freqtrade/freqtradebot.py", line 462, in check_handle_timedout
    order = exchange.get_order(trade.open_order_id, trade.pair)
  File "/home/naresh/freqtrade/freqtrade/exchange/__init__.py", line 36, in wrapper
    return f(*args, **kwargs)
  File "/home/naresh/freqtrade/freqtrade/exchange/__init__.py", line 320, in get_order
    order = _DRY_RUN_OPEN_ORDERS[order_id]
KeyError: None
2018-05-04 07:51:26,208 - freqtrade.rpc.rpc_manager - INFO - *Status:* `Stopping trader...`
2018-05-04 07:51:26,406 - freqtrade.freqtradebot - INFO - Stopping trader and cleaning up modules...
2018-05-04 07:51:26,407 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.telegram ...

**Comment by xmatthias** [comment]
This should be fixed with PR #880
