### ISSUE TITLE
Bot stopped on kucoin exchange after error

### ISSUE THREAD

**Issue by rongybika** [freqtrade/freqtrade#6374]
## Describe your environment

  * Operating system: windows
  * Python Version: 3.7.4 (`python -V`)
  * CCXT version: 1.65.25 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2021.12 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Hi,

I'm using freqtrade with kucoin exchange. I know that this exchange it's not official supported by freqtrade, but today I've got an error message and the bot shutting down. And I'm wondering if it's related to exchange or to freqtrade.
Can be implemented some kind of alert system to my phone when the bot stops running or unexpected error happens? 

The log of error is this:

...

2022-02-07 06:10:21,760 - freqtrade.exchange.common - WARNING - retrying _async_get_candle_history() still for 4 times
2022-02-07 06:10:21,760 - freqtrade.exchange.common - WARNING - Kucoin 429 error, avoid triggering DDosProtection backoff delay. 3 tries left before giving up
2022-02-07 06:10:29,456 - freqtrade.exchange.common - WARNING - _async_get_candle_history() returned exception: "kucoin GET https://openapi-v2.kucoin.com/api/v1/market/candles?symbol=YOP-USDT&type=1hour&startAt=1642406998&endAt=1644206998 429 Too Many Requests {"code":"429000","msg":"Too Many Requests"}"
2022-02-07 06:10:29,465 - freqtrade.exchange.common - WARNING - retrying _async_get_candle_history() still for 4 times
2022-02-07 06:10:29,465 - freqtrade.exchange.common - WARNING - Kucoin 429 error, avoid triggering DDosProtection backoff delay. 3 tries left before giving up
2022-02-07 06:10:43,926 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=399, pair=CIX100/USDT, amount=180.73930000, open_rate=0.14309000, open_since=2022-02-07 04:09:53)
2022-02-07 06:10:43,936 - freqtrade.commands.trade_commands - ERROR - '>' not supported between instances of 'str' and 'int'
2022-02-07 06:10:43,945 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "d:\python\freqtradekucoin\freqtrade\commands\trade_commands.py", line 19, in start_trading
    worker.run()
  File "d:\python\freqtradekucoin\freqtrade\worker.py", line 74, in run
    state = self._worker(old_state=state)
  File "d:\python\freqtradekucoin\freqtrade\worker.py", line 114, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
  File "d:\python\freqtradekucoin\freqtrade\worker.py", line 139, in _throttle
    result = func(*args, **kwargs)
  File "d:\python\freqtradekucoin\freqtrade\worker.py", line 152, in _process_running
    self.freqtrade.process()
  File "d:\python\freqtradekucoin\freqtrade\freqtradebot.py", line 171, in process
    self.check_handle_timedout()
  File "d:\python\freqtradekucoin\freqtrade\freqtradebot.py", line 889, in check_handle_timedout
    fully_cancelled = self.update_trade_state(trade, trade.open_order_id, order)
  File "d:\python\freqtradekucoin\freqtrade\freqtradebot.py", line 1278, in update_trade_state
    trade.update_order(order)
  File "d:\python\freqtradekucoin\freqtrade\persistence\models.py", line 494, in update_order
    Order.update_orders(self.orders, order)
  File "d:\python\freqtradekucoin\freqtrade\persistence\models.py", line 180, in update_orders
    oobj.update_from_ccxt_object(order)
  File "d:\python\freqtradekucoin\freqtrade\persistence\models.py", line 164, in update_from_ccxt_object
    if (order.get('filled', 0.0) or 0.0) > 0:
TypeError: '>' not supported between instances of 'str' and 'int'
2022-02-07 06:10:43,996 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2022-02-07 06:10:43,996 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2022-02-07 06:10:43,996 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2022-02-07 06:10:44,006 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': warning, 'status': "30 open trades active.\n\nHandle these trades manually on KuCoin, or '/start' the bot again and use '/stopbuy' to handle open trades gracefully. \n"}
2022-02-07 06:10:44,006 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
2022-02-07 06:10:44,006 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.apiserver ...
2022-02-07 06:10:44,006 - freqtrade.rpc.api_server.webserver - INFO - Stopping API Server
2022-02-07 06:10:44,025 - uvicorn.error - INFO - Shutting down
2022-02-07 06:10:44,135 - uvicorn.error - INFO - Waiting for application shutdown.
2022-02-07 06:10:44,135 - uvicorn.error - INFO - Application shutdown complete.
2022-02-07 06:10:44,135 - uvicorn.error - INFO - Finished server process [10288]

Thank you

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
> 2022-02-07 06:10:43,996 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}

you did get a telegram message / notification that the bot died. not sure what else you'd expect?

---

For the problem itself - i'd in general always encourage to test the same with the latest version (2022.1 at this point in time), or better yet with develp. That'll include a newer ccxt version, which may have some problems already fixed.

At any rate, i'd ask you to enable logging ccxt/exchange responses (`log_responses` to true in the exchange configuration) (linked commit shows where to configure this).
Obviously that assumes it's repeatable (occurs again) - but it'll tell us what exactly ccxt returned.

I've just done a quick test, and current version seems to parse `filled` correctly (but there's also not been a obvious change in the last few months to that part of ccxt either).

**Comment by rongybika** [comment]
Hi,

Sorry i didn't notice the telegram message because I'm not using telegram, but I think I should start us it.
I'm gone add the option to config and I'm gone upgrade the bot to the latest version.

Thank you

**Comment by xmatthias** [comment]
Let me know once you got more information :+1:

**Comment by xmatthias** [comment]
@rongybika any update? did the problem reappear?

**Comment by rongybika** [comment]
Hi,

Since that error was no any more errors.
I hope it's gone. :)

Thank you

**Comment by xmatthias** [comment]
Let's then close this for the moment.
should the error reappear best reopen or comment below :+1:
