### ISSUE TITLE
ERROR: Failed building wheel for ninja

### ISSUE THREAD

**Issue by isaack0815** [freqtrade/freqtrade#6381]
## Describe your environment

  * Operating system: RaspberryPi 3 Ubuntu 21.10
  * Python Version: Pytrhon 3.9.7

  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

I get the following message during installation

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
ubuntu@ubuntu:~/freqtrade$ sudo ./setup.sh --install
/usr/bin/python3.9
using python3.9
----------------------------
Installing mandatory dependencies
----------------------------
Debian/Ubuntu detected. Setup for this system in-progress
Hit:1 http://ports.ubuntu.com/ubuntu-ports impish InRelease
Get:2 http://ports.ubuntu.com/ubuntu-ports impish-updates InRelease [110 kB]
Hit:3 http://ports.ubuntu.com/ubuntu-ports impish-backports InRelease
Hit:4 http://ports.ubuntu.com/ubuntu-ports impish-security InRelease
Get:5 http://ports.ubuntu.com/ubuntu-ports impish-updates/main armhf Packages [218 kB]
Get:6 http://ports.ubuntu.com/ubuntu-ports impish-updates/restricted armhf Packages [2504 B]
Get:7 http://ports.ubuntu.com/ubuntu-ports impish-updates/universe armhf Packages [89.0 kB]
Fetched 420 kB in 3s (160 kB/s)                           
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
autoconf is already the newest version (2.69-14).
build-essential is already the newest version (12.9ubuntu2).
gcc is already the newest version (4:11.2.0-1ubuntu1).
git is already the newest version (1:2.32.0-1ubuntu1).
libpython3.9-dev is already the newest version (3.9.7-2build1).
libtool is already the newest version (2.4.6-15).
make is already the newest version (4.3-4ubuntu1).
pkg-config is already the newest version (0.29.2-1ubuntu1).
wget is already the newest version (1.21-1ubuntu3).
python3.9-venv is already the newest version (3.9.7-2build1).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
ta-lib already installed, skipping

----------------------------
Resetting branch and virtual env
----------------------------
Reset git branch? (This will remove all changes you made!) [y/N]? y
- Hard resetting of 'develop' branch.
HEAD is now at 172e018d2 Add probit to list of non-working exchanges
- Deleting your previous virtual env

----------------------------
Updating your virtual env
----------------------------
pip install in-progress. Please wait...
Requirement already satisfied: pip in ./.env/lib/python3.9/site-packages (20.3.4)
Collecting pip
  Using cached pip-22.0.3-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.3.4
    Uninstalling pip-20.3.4:
      Successfully uninstalled pip-20.3.4
Successfully installed pip-22.0.3
Do you want to install dependencies for dev [y/N]? y
Do you want to install plotting dependencies (plotly) [y/N]? y
Detected Raspberry, installing cython, skipping hyperopt installation.
Collecting cython
  Using cached Cython-0.29.27-py2.py3-none-any.whl (983 kB)
Installing collected packages: cython
Successfully installed cython-0.29.27
Collecting numpy==1.22.2
  Using cached numpy-1.22.2.zip (11.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pandas==1.4.0
  Using cached pandas-1.4.0.tar.gz (4.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pandas-ta==0.3.14b
  Downloading pandas_ta-0.3.14b.tar.gz (115 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.1/115.1 KB 543.5 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting ccxt==1.72.36
  Downloading ccxt-1.72.36-py2.py3-none-any.whl (2.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 489.1 kB/s eta 0:00:00
Collecting cryptography==36.0.1
  Downloading cryptography-36.0.1.tar.gz (572 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 572.1/572.1 KB 1.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting aiohttp==3.8.1
  Downloading aiohttp-3.8.1.tar.gz (7.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.3/7.3 MB 824.5 kB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting SQLAlchemy==1.4.31
  Downloading SQLAlchemy-1.4.31.tar.gz (8.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.0/8.0 MB 1.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting python-telegram-bot==13.11
  Downloading python_telegram_bot-13.11-py3-none-any.whl (497 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 498.0/498.0 KB 35.8 kB/s eta 0:00:00
Collecting arrow==1.2.2
  Downloading arrow-1.2.2-py3-none-any.whl (64 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.0/64.0 KB 7.5 kB/s eta 0:00:00
Collecting cachetools==4.2.2
  Downloading cachetools-4.2.2-py3-none-any.whl (11 kB)
Collecting requests==2.27.1
  Downloading requests-2.27.1-py2.py3-none-any.whl (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.1/63.1 KB 111.8 kB/s eta 0:00:00
Collecting urllib3==1.26.8
  Downloading urllib3-1.26.8-py2.py3-none-any.whl (138 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 138.7/138.7 KB 328.1 kB/s eta 0:00:00
Collecting jsonschema==4.4.0
  Downloading jsonschema-4.4.0-py3-none-any.whl (72 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.7/72.7 KB 155.2 kB/s eta 0:00:00
Collecting TA-Lib==0.4.24
  Downloading TA-Lib-0.4.24.tar.gz (269 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 269.4/269.4 KB 1.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting technical==1.3.0
  Downloading technical-1.3.0-py3-none-any.whl (51 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.7/51.7 KB 580.6 kB/s eta 0:00:00
Collecting tabulate==0.8.9
  Downloading tabulate-0.8.9-py3-none-any.whl (25 kB)
Collecting pycoingecko==2.2.0
  Downloading pycoingecko-2.2.0-py3-none-any.whl (8.3 kB)
Collecting jinja2==3.0.3
  Downloading Jinja2-3.0.3-py3-none-any.whl (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.6/133.6 KB 236.5 kB/s eta 0:00:00
Collecting tables==3.7.0
  Downloading tables-3.7.0.tar.gz (8.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.2/8.2 MB 1.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting blosc==1.10.6
  Downloading blosc-1.10.6.tar.gz (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 711.3 kB/s eta 0:00:00
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [72 lines of output]
      Collecting setuptools
        Using cached setuptools-60.8.1-py3-none-any.whl (1.1 MB)
      Collecting wheel
        Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
      Collecting scikit-build
        Downloading scikit_build-0.13.1-py2.py3-none-any.whl (75 kB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.4/75.4 KB 12.3 kB/s eta 0:00:00
      Collecting cmake
        Downloading cmake-3.22.2.tar.gz (30 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting ninja
        Downloading ninja-1.10.2.3.tar.gz (26 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting distro
        Using cached distro-1.6.0-py2.py3-none-any.whl (19 kB)
      Collecting packaging
        Using cached packaging-21.3-py3-none-any.whl (40 kB)
      Collecting pyparsing!=3.0.5,>=2.0.2
        Using cached pyparsing-3.0.7-py3-none-any.whl (98 kB)
      Building wheels for collected packages: cmake, ninja
        Building wheel for cmake (pyproject.toml): started
        Building wheel for cmake (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error
      
        × Building wheel for cmake (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [9 lines of output]
              File "/tmp/pip-build-env-jazev0pz/overlay/lib/python3.9/site-packages/skbuild/setuptools_wrap.py", line 566, in setup
                cmkr = cmaker.CMaker(cmake_executable)
              File "/tmp/pip-build-env-jazev0pz/overlay/lib/python3.9/site-packages/skbuild/cmaker.py", line 133, in __init__
                self.cmake_version = get_cmake_version(self.cmake_executable)
              File "/tmp/pip-build-env-jazev0pz/overlay/lib/python3.9/site-packages/skbuild/cmaker.py", line 88, in get_cmake_version
                raise SKBuildError(
            Traceback (most recent call last):
      
            Problem with the CMake installation, aborting build. CMake executable is cmake
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for cmake
        Building wheel for ninja (pyproject.toml): started
        Building wheel for ninja (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error
      
        × Building wheel for ninja (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [9 lines of output]
              File "/tmp/pip-build-env-ht0qlg3b/overlay/lib/python3.9/site-packages/skbuild/setuptools_wrap.py", line 566, in setup
                cmkr = cmaker.CMaker(cmake_executable)
              File "/tmp/pip-build-env-ht0qlg3b/overlay/lib/python3.9/site-packages/skbuild/cmaker.py", line 133, in __init__
                self.cmake_version = get_cmake_version(self.cmake_executable)
              File "/tmp/pip-build-env-ht0qlg3b/overlay/lib/python3.9/site-packages/skbuild/cmaker.py", line 88, in get_cmake_version
                raise SKBuildError(
            Traceback (most recent call last):
      
            Problem with the CMake installation, aborting build. CMake executable is cmake
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for ninja
      Failed to build cmake ninja
      ERROR: Could not build wheels for cmake, ninja, which is required to install pyproject.toml-based projects
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Failed installing dependencies

  ```

**Comment by xmatthias** [comment]
You can try to install cmake first (cmake should NOT be installed from pypi iirc) (basically `apt-get install cmake` before running the installation).

That said - while we support raspberries, all our guides and scripts assume that raspbian/raspberry OS is used (the default operating system for raspberry pi's). 
Now freqtrade MAY work on ubuntu just fine (once you get it installed) - but we'll not be able to assist you much with it.

**Comment by xmatthias** [comment]
Closing this as i think your question has been answered.

Feel free to comment below / reopen if you still need assistance.

**Comment by 220haoqiaoa** [comment]
I have the same problem as you, how did you solve it?

**Comment by xmatthias** [comment]
If it's exactly the same error - then the above comment will still help - installing cmake prior to installation (most often, the package `build-essentials` helps (`sudo apt install build-essentials`).

If not, please open a new issue with YOUR error - as nuances in these errors do matter quite a ton.
