### ISSUE TITLE
Use Telegram Bot for more traders 

### ISSUE THREAD

**Issue by isaack0815** [freqtrade/freqtrade#6414]
Hi there,
my friend and I would both like to use a traderbot.
We would also like to add both Telegram. Unfortunately, we have the problem that if both traders are running on one server, only one can use the bot.
Is it possible to set something in the config so that both telegrams can be used for the different bots?

At the moment only one of them has the bot available.
if both work with the same Telegram token and different chat IDs in the individual config, this error occurs:

```
telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-02-14 11:55:04,615 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/root/freqtrade/.env/lib/python3.8/site-packages/telegram/ext/updater.py", line 646, in _network_loop_retry
    if not action_cb():
  File "/root/freqtrade/.env/lib/python3.8/site-packages/telegram/ext/updater.py", line 597, in polling_action_cb
    updates = self.bot.get_updates(
  File "/root/freqtrade/.env/lib/python3.8/site-packages/telegram/ext/extbot.py", line 224, in get_updates
    updates = super().get_updates(
  File "/root/freqtrade/.env/lib/python3.8/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/root/freqtrade/.env/lib/python3.8/site-packages/telegram/bot.py", line 3054, in get_updates
    self._post(
  File "/root/freqtrade/.env/lib/python3.8/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/root/freqtrade/.env/lib/python3.8/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/root/freqtrade/.env/lib/python3.8/site-packages/telegram/utils/request.py", line 283, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
```

**Comment by SmartManoj** [comment]
Workaround: Use group

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

From your description, it's unclear if you'd like to run 1 bot which is controlled by 2 telegram accounts - or if it's 2 bots on one server.
The error hints at "2 bots - 2 different people" - which you can find in the [multiple bots](https://www.freqtrade.io/en/stable/advanced-setup/#running-multiple-instances-of-freqtrade) section.

Both cases are covered in the documentation - especially the [multiple bots](https://www.freqtrade.io/en/stable/advanced-setup/#running-multiple-instances-of-freqtrade) section - as you'll have to keep other things in mind for this as well.

To control one bot with multiple accounts please use the group id as explained in the [docs](https://www.freqtrade.io/en/stable/telegram-usage/#use-group-id).
Please note that in this case, all members will have full access to all functionalities.

**Comment by SmartManoj** [comment]
> Workaround: Use group

With two telegram bots. 

A telegram bot should be linked with only one freqtrade instance.

**Comment by isaack0815** [comment]
Please excuse me if I didn't express myself correctly.
So I want to start a Telegram bot for every trading bot.
have now created a second bot with its own token.
However, when I start it I get a new error:

```
2022-02-15 11:51:31,525 - freqtrade.rpc.rpc_manager - INFO - Enabling rpc.telegram ...
/root/fqtdavid/freqtrade/.env/lib/python3.8/site-packages/telegram/ext/dispatcher.py:250: UserWarning: Asynchronous callbacks can not be processed without at least one worker thread.
  warnings.warn(
2022-02-15 11:51:31,948 - apscheduler.scheduler - INFO - Scheduler started
2022-02-15 11:51:31,989 - freqtrade.commands.trade_commands - ERROR - Unauthorized
2022-02-15 11:51:31,989 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/root/fqtdavid/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/root/fqtdavid/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/root/fqtdavid/freqtrade/freqtrade/worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/root/fqtdavid/freqtrade/freqtrade/freqtradebot.py", line 78, in __init__
    self.rpc: RPCManager = RPCManager(self)
  File "/root/fqtdavid/freqtrade/freqtrade/rpc/rpc_manager.py", line 28, in __init__
    self.registered_modules.append(Telegram(self._rpc, config))
  File "/root/fqtdavid/freqtrade/freqtrade/rpc/telegram.py", line 92, in __init__
    self._init()
  File "/root/fqtdavid/freqtrade/freqtrade/rpc/telegram.py", line 201, in _init
    self._updater.start_polling(
  File "/root/fqtdavid/freqtrade/.env/lib/python3.8/site-packages/telegram/ext/updater.py", line 422, in start_polling
    self._init_thread(self.dispatcher.start, "dispatcher", ready=dispatcher_ready)
  File "/root/fqtdavid/freqtrade/.env/lib/python3.8/site-packages/telegram/ext/updater.py", line 342, in _init_thread
    name=f"Bot:{self.bot.id}:{name}",
  File "/root/fqtdavid/freqtrade/.env/lib/python3.8/site-packages/telegram/bot.py", line 369, in id
    return self.bot.id
  File "/root/fqtdavid/freqtrade/.env/lib/python3.8/site-packages/telegram/bot.py", line 363, in bot
    self._bot = self.get_me()
  File "/root/fqtdavid/freqtrade/.env/lib/python3.8/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/root/fqtdavid/freqtrade/.env/lib/python3.8/site-packages/telegram/bot.py", line 450, in get_me
    result = self._post('getMe', timeout=timeout, api_kwargs=api_kwargs)
  File "/root/fqtdavid/freqtrade/.env/lib/python3.8/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/root/fqtdavid/freqtrade/.env/lib/python3.8/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/root/fqtdavid/freqtrade/.env/lib/python3.8/site-packages/telegram/utils/request.py", line 277, in _request_wrapper
    raise Unauthorized(message)
telegram.error.Unauthorized: Unauthorized

```

**Comment by xmatthias** [comment]
> telegram.error.Unauthorized: Unauthorized

You'll have to follow the ["new bot" instruction ](https://www.freqtrade.io/en/latest/telegram-usage/#1-create-your-telegram-bot) for every bot you create.
the error suggests that you've either misstyped the id / bot-token - or didn't start the bot in your chat.

**Comment by isaack0815** [comment]
Excuse me, I had twisted a few things here in config.conf
everything is working as it should now.
thank you for your help
