### ISSUE TITLE
Exception (ZeroDivisionError) with /status telegram command on version 2022.2

### ISSUE THREAD

**Issue by rogarcia** [freqtrade/freqtrade#6461]
## Describe your environment

docker image: freqtradeorg/freqtrade:stable (tag: 2022.2)
  * Operating system:  Ubuntu 20.04.3 LTS arm64
  * Python Version: 3.9.9
  * CCXT version: 1.73.70
  * Freqtrade Version: 2022.2

## Describe the problem:

Regression: division by zero error when using the `/status` telegram command after updating to FT version 2022.2

Position adjustment is enabled and I have open trades that have more than on rebuys. 

Only `/status` or `/status <trade_id>` command seems be affected. The `/status table` command still works fine.

```
2022-02-25 17:24:00 - freqtrade.rpc.telegram - ERROR - Exception occurred within Telegram module
Traceback (most recent call last):
  File "/freqtrade/freqtrade/rpc/telegram.py", line 71, in wrapper
    return command_handler(self, *args, **kwargs)
  File "/freqtrade/freqtrade/rpc/telegram.py", line 486, in _status
    lines_detail = self._prepare_entry_details(
  File "/freqtrade/freqtrade/rpc/telegram.py", line 395, in _prepare_entry_details
    price_to_1st_entry = ((cur_entry_average - filled_orders[0]["average"])
ZeroDivisionError: division by zero
```
### Steps to reproduce:

  1. Open Telegram chat
  2. Issue a `/status'` or `/status <trade_id>`
  3. Check logs on server or use telegram `/logs`
  
### Observed Results:

  * What happened?
  Nothing is returned

  * What did you expect to happen?
  full description of each trade statuses, including each rebuy

### Relevant code exceptions or logs

```2022-02-25 17:24:00 - freqtrade.rpc.telegram - ERROR - Exception occurred within Telegram module
Traceback (most recent call last):
  File "/freqtrade/freqtrade/rpc/telegram.py", line 71, in wrapper
    return command_handler(self, *args, **kwargs)
  File "/freqtrade/freqtrade/rpc/telegram.py", line 486, in _status
    lines_detail = self._prepare_entry_details(
  File "/freqtrade/freqtrade/rpc/telegram.py", line 395, in _prepare_entry_details
    price_to_1st_entry = ((cur_entry_average - filled_orders[0]["average"])
ZeroDivisionError: division by zero
```

**Comment by xmatthias** [comment]
Which exchange are we talking about?

It seems strange that "average" is not filled - that's a pretty "must have" column, really for most exchanges.

please also provide me with the output of the following command:
`freqtrade show-trades --db-url <yourdburl> --trade-ids <tradeid's that are open>`.

**Comment by SmartManoj** [comment]
Occurred in Kucoin.

Average vs price?

https://github.com/mkavinkumar1/freqtrade/blob/22534d6a78cbb501dd479503dfd0ed4a1f4ebc20/freqtrade/rpc/telegram.py#L418:L425

**Comment by rogarcia** [comment]
@xmatthias Same error on Both Kucoin and Gateio

Kucoin:
```
2022-02-25 19:12:48,114 - freqtrade.commands.list_commands - INFO - Printing 1 Trades: 
Trade(id=30, pair=IMX/USDT, amount=54.46890000, open_rate=3.48365450, open_since=2022-02-03 20:30:27)
```
Gateio
```
2022-02-25 19:16:24,202 - freqtrade.commands.list_commands - INFO - Printing 5 Trades: 
Trade(id=57, pair=CWAR/USDT, amount=275.29400000, open_rate=0.58666888, open_since=2022-02-08 09:15:45)
Trade(id=67, pair=CLV/USDT, amount=446.06400000, open_rate=0.51952708, open_since=2022-02-11 19:10:45)
Trade(id=81, pair=SUPER/USDT, amount=185.08600000, open_rate=1.00780936, open_since=2022-02-16 21:00:45)
Trade(id=99, pair=AGLD/USDT, amount=23.21000000, open_rate=1.19560000, open_since=2022-02-25 09:15:46)
Trade(id=101, pair=DEVT/USDT, amount=151.21200000, open_rate=0.53611000, open_since=2022-02-25 18:15:48)
```

**Comment by xmatthias** [comment]
@rogarcia sorry, my command had one crucial thing missing (`--print-json`) - so the output is not sufficient

`freqtrade show-trades --db-url <yourdburl> --trade-ids <tradeid's that are open> --print-json`

**Comment by rogarcia** [comment]
Kucoin:

```
2022-02-25 19:53:03,639 - freqtrade.commands.list_commands - INFO - Printing 1 Trades: 
[
    {
        "trade_id": 30,
        "pair": "IMX/USDT",
        "is_open": true,
        "exchange": "kucoin",
        "amount": 54.4689,
        "amount_requested": 35.2432,
        "stake_amount": 189.7508284,
        "strategy": "NostalgiaForInfinityX",
        "buy_tag": "5 24 ",
        "timeframe": 5,
        "fee_open": 0.001,
        "fee_open_cost": 0.18975082840000002,
        "fee_open_currency": "USDT",
        "fee_close": 0.001,
        "fee_close_cost": null,
        "fee_close_currency": null,
        "open_date": "2022-02-03 20:30:27",
        "open_timestamp": 1643920227811,
        "open_rate": 3.483654496419058,
        "open_rate_requested": 3.268,
        "open_trade_value": 189.94057923,
        "close_date": null,
        "close_timestamp": null,
        "close_rate": null,
        "close_rate_requested": null,
        "close_profit": null,
        "close_profit_pct": null,
        "close_profit_abs": null,
        "trade_duration_s": null,
        "trade_duration": null,
        "profit_ratio": null,
        "profit_pct": null,
        "profit_abs": null,
        "sell_reason": null,
        "sell_order_status": null,
        "stop_loss_abs": 0.03554000000000003,
        "stop_loss_ratio": -0.99,
        "stop_loss_pct": -99.0,
        "stoploss_order_id": null,
        "stoploss_last_update": "2022-02-03 20:30:36",
        "stoploss_last_update_timestamp": 1643920236722,
        "initial_stop_loss_abs": 0.03554000000000003,
        "initial_stop_loss_ratio": -0.99,
        "initial_stop_loss_pct": -99.0,
        "min_rate": 1.316,
        "max_rate": 3.675,
        "open_order_id": null,
        "filled_entry_orders": [
            {
                "amount": 35.2432,
                "average": 0,
                "cost": 125.2543328,
                "filled": 35.2432,
                "ft_order_side": "buy",
                "is_open": false,
                "order_date": "2022-02-03 20:30:27",
                "order_timestamp": 1643920227751,
                "order_filled_date": "2022-02-03 20:30:36",
                "order_filled_timestamp": 1643920236237,
                "order_type": "limit",
                "pair": "IMX/USDT",
                "price": 3.554,
                "remaining": 0.0,
                "status": "closed"
            },
            {
                "amount": 9.2606,
                "average": 0,
                "cost": 31.9305488,
                "filled": 9.2606,
                "ft_order_side": "buy",
                "is_open": false,
                "order_date": "2022-02-03 20:50:26",
                "order_timestamp": 1643921426527,
                "order_filled_date": "2022-02-03 20:50:37",
                "order_filled_timestamp": 1643921437803,
                "order_type": "limit",
                "pair": "IMX/USDT",
                "price": 3.449,
                "remaining": 0.0,
                "status": "closed"
            },
            {
                "amount": 9.9651,
                "average": 0,
                "cost": 32.5659468,
                "filled": 9.9651,
                "ft_order_side": "buy",
                "is_open": false,
                "order_date": "2022-02-04 03:05:30",
                "order_timestamp": 1643943930670,
                "order_filled_date": "2022-02-04 03:05:35",
                "order_filled_timestamp": 1643943935916,
                "order_type": "limit",
                "pair": "IMX/USDT",
                "price": 3.268,
                "remaining": 0.0,
                "status": "closed"
            }
        ],
        "filled_exit_orders": []
    }
]
```

**Comment by rogarcia** [comment]
@xmatthias do you need the output from the 5 open trades on Gateio as well?

**Comment by xmatthias** [comment]
No the above is fine, thanks

**Comment by xmatthias** [comment]
This is fixed in develop. I'm now creating a new release (2022.2.1) which will fix this.

CI will (probably) take about an hour to complete.
