### ISSUE TITLE
Problems with Gate.io

### ISSUE THREAD

**Issue by Pit-CL** [freqtrade/freqtrade#6484]
## Describe your environment

  * Operating system: Debian 11
  * Python Version: 3.9
  * CCXT version: last commint
  * Freqtrade Version: 2022.1, Strategy version:  v11.0.325
  
## Describe the problem:

Problems withe the last commit, all new trades gives a problem.

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
 2022-03-01 10:57:55 freqtrade.exchange.common: WARNING - fetch_order() returned exception: "Could not get order due to BadRequest. Message: gateio {"label":"INVALID_PARAM_VALUE","message":"Empty order ID, 128503085637.0"}". Retrying still for 5 times.
2022-03-01 10:57:55 freqtrade.exchange.common: WARNING - fetch_order() returned exception: "Could not get order due to BadRequest. Message: gateio {"label":"INVALID_PARAM_VALUE","message":"Empty order ID, 128503085637.0"}". Retrying still for 4 times.
2022-03-01 10:57:55 freqtrade.exchange.common: WARNING - fetch_order() returned exception: "Could not get order due to BadRequest. Message: gateio {"label":"INVALID_PARAM_VALUE","message":"Empty order ID, 128503085637.0"}". Retrying still for 3 times.
2022-03-01 10:57:55 freqtrade.exchange.common: WARNING - fetch_order() returned exception: "Could not get order due to BadRequest. Message: gateio {"label":"INVALID_PARAM_VALUE","message":"Empty order ID, 128503085637.0"}". Retrying still for 2 times.
2022-03-01 10:57:56 freqtrade.exchange.common: WARNING - fetch_order() returned exception: "Could not get order due to BadRequest. Message: gateio {"label":"INVALID_PARAM_VALUE","message":"Empty order ID, 128503085637.0"}". Retrying still for 1 times.
2022-03-01 10:57:56 freqtrade.exchange.common: WARNING - fetch_order() returned exception: "Could not get order due to BadRequest. Message: gateio {"label":"INVALID_PARAM_VALUE","message":"Empty order ID, 128503085637.0"}". Giving up.
  ```

**Comment by Pit-CL** [comment]
Im in develop branch but the last version is 2022.1 very weird

**Comment by Pit-CL** [comment]
now im change to stable and the version is 2022.2.1, something weird is happen with DEVELOP branch

**Comment by xmatthias** [comment]
The change/difference will be the ccxt version i suspect. There's no other changes that could affect this i think.

did you always update dependencies? (maybe through docker?)
the ccxt version is output as first or 2nd line when starting a bot.

**Comment by Pit-CL** [comment]
Hi @xmatthias i dont use docker, but yes always update dependencies, CCTX version i cant get it from the log because the following error colapse all log file with that.  But i supposed to update to [dca83b0] develop.

Why in develop it shows stable previus version and not even the last one?

And more info 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/freqtrade/freqtrade/freqtradebot.py", line 960, in check_handle_timedout
    order = self.exchange.fetch_order(trade.open_order_id, trade.pair)
  File "/root/freqtrade/freqtrade/exchange/common.py", line 137, in wrapper
    return wrapper(*args, **kwargs)
  File "/root/freqtrade/freqtrade/exchange/common.py", line 137, in wrapper
    return wrapper(*args, **kwargs)
  File "/root/freqtrade/freqtrade/exchange/common.py", line 137, in wrapper
    return wrapper(*args, **kwargs)  [Previous line repeated 2 more times]
  File "/root/freqtrade/freqtrade/exchange/common.py", line 140, in wrapper    raise ex  File "/root/freqtrade/freqtrade/exchange/common.py", line 125, in wrapper
    return f(*args, **kwargs)  File "/root/freqtrade/freqtrade/exchange/exchange.py", line 901, in fetch_order    raise TemporaryError(freqtrade.exceptions.TemporaryError: Could not get order due to BadRequest. Message: gateio {"label":"INVALID_PARAM_VALUE","message":"Empty order ID, 128503085637.0"}
    
Traceback (most recent call last):
  File "/root/freqtrade/freqtrade/exchange/exchange.py", line 889, in fetch_order
    order = self._api.fetch_order(order_id, pair)
  File "/root/freqtrade/.env/lib/python3.9/site-packages/ccxt/gateio.py", line 2613, in fetch_order
    response = getattr(self, method)(self.extend(request, params))
  File "/root/freqtrade/.env/lib/python3.9/site-packages/ccxt/base/exchange.py", line 502, in inner
    return entry(_self, **inner_kwargs)
  File "/root/freqtrade/.env/lib/python3.9/site-packages/ccxt/base/exchange.py", line 553, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "/root/freqtrade/.env/lib/python3.9/site-packages/ccxt/base/exchange.py", line 549, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/root/freqtrade/.env/lib/python3.9/site-packages/ccxt/base/exchange.py", line 676, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/root/freqtrade/.env/lib/python3.9/site-packages/ccxt/gateio.py", line 3359, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], label, feedback)
  File "/root/freqtrade/.env/lib/python3.9/site-packages/ccxt/base/exchange.py", line 567, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.BadRequest: gateio {"label":"INVALID_PARAM_VALUE","message":"Empty order ID, 128503085637.0"}

**Comment by xmatthias** [comment]
please open the database (sqlite3, sqlitebrowser) - and search the orders-table for the following id:
`128503085637`.
The problem is definitely the `.0` at the end of your order-id - but it's unclear if that's in the database, or part some odd type conversion that's causing this (it should be a string throughout freqtrade ...)
This should get you a trade-id - which you can then use in the following command:

`freqtrade show-trades --print-json --trade-ids <tradid>`.

**Comment by jurekl** [comment]
I had a similar problem on gate.io with the WOOP/USDT next 'forced rebuy'.
After the error occurred, the bot could not be started anymore, it was seemingly helped by manually removing all the ".0" endings in the order "id" fields. However, the bot, after successfully starting up, showed incorrect data / calculations (STAKE_AMOUNT field for trade!) For this trade. I had to complete this trading manually, but kept the base with this data. Here is a sample of this data:
```
sqlite> .header on
sqlite> select id, ft_pair, ft_trade_id,amount,order_id from orders where ft_trade_id==139;
id|ft_pair|ft_trade_id|amount|order_id
298|WOOP/USDT|139|34.176|124732390261
299|WOOP/USDT|139|13.109|125118062762
302|WOOP/USDT|139|15.734|127022429526
310|WOOP/USDT|139|88.339|128015322881.0
311|WOOP/USDT|139|28.392|128015432823.0

sqlite> select id,exchange,pair,amount,stake_amount,open_order_id from trades where id==139;
id|exchange|pair|amount|stake_amount|open_order_id
139|gateio|WOOP/USDT|179.75|983.217229622|128015432823.0
```

**Comment by xmatthias** [comment]
well once the orderid is in the database, it'll be wrong until fixed.

This appears to be caused by a bug in ccxt - with the fix being on it's way (https://github.com/ccxt/ccxt/pull/12158)

**Comment by xmatthias** [comment]
This is solved now in the latest develop.

However, to properly fix it, you will have to open the database (sqlite / sqlitebrowser), and go through the orders table (and the trades table) and remove the `.0` from all orders that are affected (hopefully not many).
In the trades table, this would be the columns `open_order_id` , in the orders table the column `order_id`.

I'm hesitant to add a fix for this automatically, as this might be a valid order-id for other exchanges, so the risk of introducing another bug is bigger than the gain we would have from this.
