### ISSUE TITLE
Unexpected emergency sell resulting in python exceptions and cascade of strange behavior

### ISSUE THREAD

**Issue by winginitau** [freqtrade/freqtrade#6508]
Linux 
Python 3.8
ccxt==1.75.12
freqtrade develop-26f6d8076

Relevant config
```
   minimal_roi = {
        "40":  0.005,
        "30":  0.01,
        "20":  0.02,
        "0":  0.04
    }
    stoploss = -0.2
    trailing_stop = True
    trailing_stop_positive = 0.005
    trailing_only_offset_is_reached = True
    trailing_stop_positive_offset = 0.0051  # Disabled / not configured
```
Trade details

TradeId 1069
Pair AUDIO/BUSD
Stake 20.023 BUSD
Open date 2022-03-08 02:26:53
Open Rate 0.738
Close Rate 0.734
Min Rate 0.674
Max Rate 0.744
Close date 2022-03-08 19:05:12
Close Profit -0.62% (-0.123)
Stoploss -0.500% | 0.74028
Initial Stoploss -20.000% | 0.5904
Stoploss last updated 2022-03-08 18:54:31

Inferring from the log, lots of questions. Perhaps important (and may be the cuase?) is that I updated minimal_roi between the buys and the sell, increasing the '40' from 0.0015 to 0.005, though I don't see where that is a factor.

Following the sequence (see log):
1. The limit sell at 0.738 makes sense with trailing stop at 0.005 (i.e 0.5%) as the max rate was 0.744 (0.813%).
2. Sell order cancelled due to time out - makes sense, past 10 mins. 
3. The value had dropped. 
4. Why is it trying to place a stop_loss_limit sell order at 0.733? This is below the open rate. 
5. I understood that trailing_stop_positive was only for offset above the open rate? It seems to be trying to take it below. 
6. Price moves further, so it is unable to place the 0.733 limit order due to immediate trigger - understood (though not why it was trying in the first place (Q3, 4).
7. Being unable to place limit it triggers an emergency market sell.
8. Since the global stop-loss at 0.2 was no where near, I would rather it have just cancelled the limit sell and let it hold. Logic of go to market when limit fails makes sense in a big stop-loss (0.20 trigger) but doesn't due to an ordinary limit sell failed. 
9. Having triggered the market sell (sucessfully), it then goes into a cascade of failures trying to cancel a stop loss, presumably the one that it did not place due to immediate trigger - exchange feedback may not have been processed?
10. At the end - further warning about not enough quanity. 

Many thanks for any assiatnce. Awesome project. Hopefully this is helpful too. 

```
2022-03-08 19:05:01,705 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=1069, pair=AUDIO/BUSD, amount=27.10000000, open_rate=0.73800000, open_since=2022-03-07 16:26:53)
2022-03-08 19:05:02,148 - freqtrade.freqtradebot - INFO - Sell order cancelled due to timeout for Trade(id=1069, pair=AUDIO/BUSD, amount=27.10000000, open_rate=0.73800000, open_since=2022-03-07 16:26:53).
2022-03-08 19:05:02,518 - freqtrade.wallets - INFO - Wallets synced.
2022-03-08 19:05:02,518 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': sell_cancel, 'trade_id': 1069, 'exchange': 'Binance', 'pair': 'AUDIO/BUSD', 'gain': 'loss', 'limit': 0, 'order_type': 'limit', 'amount': 27.1, 'open_rate': 0.738, 'current_rate': 0.744, 'profit_amount': -19.9998, 'profit_ratio': -1.0, 'buy_tag': None, 'sell_reason': None, 'open_date': datetime.datetime(2022, 3, 7, 16, 26, 53, 910724), 'close_date': datetime.datetime(2022, 3, 8, 9, 5, 2, 518523, tzinfo=datetime.timezone.utc), 'stake_currency': 'BUSD', 'fiat_currency': 'USD', 'reason': 'cancelled due to timeout'}
2022-03-08 19:05:10,219 - freqtrade.freqtradebot - INFO - Cancelling current stoploss on exchange for pair YFII/BUSD (orderid:121960305) in order to add another one ...
2022-03-08 19:05:10,777 - freqtrade.exchange.exchange - INFO - stoploss limit order added for YFII/BUSD. stop price: 1495.2. limit: 1480.248
2022-03-08 19:05:11,456 - freqtrade.freqtradebot - ERROR - Unable to place a stoploss order on exchange. Could not create stop_loss_limit sell order on market AUDIO/BUSD. Tried to sell amount 27.1 at rate 0.733. Message: binance Stop price would trigger immediately.
2022-03-08 19:05:11,456 - freqtrade.freqtradebot - WARNING - Exiting the trade forcefully
2022-03-08 19:05:11,962 - freqtrade.wallets - INFO - Wallets synced.
2022-03-08 19:05:12,297 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': sell, 'trade_id': 1069, 'exchange': 'Binance', 'pair': 'AUDIO/BUSD', 'gain': 'profit', 'limit': 0.7402799999999999, 'order_type': 'market', 'amount': 27.1, 'open_rate': 0.738, 'close_rate': None, 'current_rate': 0.744, 'profit_amount': 0.061788, 'profit_ratio': 0.00308943, 'buy_tag': None, 'sell_reason': 'emergency_sell', 'open_date': datetime.datetime(2022, 3, 7, 16, 26, 53, 910724), 'close_date': datetime.datetime(2022, 3, 8, 9, 5, 12, 297241), 'stake_currency': 'BUSD', 'fiat_currency': 'USD'}
2022-03-08 19:05:12,297 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=1069, pair=AUDIO/BUSD, amount=27.10000000, open_rate=0.73800000, open_since=2022-03-07 16:26:53)
2022-03-08 19:05:12,584 - freqtrade.freqtradebot - INFO - Fee for Trade Trade(id=1069, pair=AUDIO/BUSD, amount=27.10000000, open_rate=0.73800000, open_since=2022-03-07 16:26:53) [sell]: 3.882e-05 BNB - rate: 0.00074961
2022-03-08 19:05:12,584 - freqtrade.persistence.models - INFO - Updating trade (id=1069) ...
2022-03-08 19:05:12,584 - freqtrade.persistence.models - INFO - MARKET_SELL has been fulfilled for Trade(id=1069, pair=AUDIO/BUSD, amount=27.10000000, open_rate=0.73800000, open_since=2022-03-07 16:26:53).
2022-03-08 19:05:12,585 - freqtrade.persistence.models - INFO - Marking Trade(id=1069, pair=AUDIO/BUSD, amount=27.10000000, open_rate=0.73800000, open_since=closed) as closed as the trade is fulfilled and found no open orders for it.
2022-03-08 19:05:13,096 - freqtrade.wallets - INFO - Wallets synced.
2022-03-08 19:05:13,098 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': sell_fill, 'trade_id': 1069, 'exchange': 'Binance', 'pair': 'AUDIO/BUSD', 'gain': 'loss', 'limit': 0.734, 'order_type': '', 'amount': 27.1, 'open_rate': 0.738, 'close_rate': 0.734, 'current_rate': None, 'profit_amount': -0.12331079, 'profit_ratio': -0.0061656, 'buy_tag': None, 'sell_reason': 'emergency_sell', 'open_date': datetime.datetime(2022, 3, 7, 16, 26, 53, 910724), 'close_date': datetime.datetime(2022, 3, 8, 9, 5, 12, 585063), 'stake_currency': 'BUSD', 'fiat_currency': 'USD'}
2022-03-08 19:05:13,099 - freqtrade.freqtradebot - WARNING - Stoploss order was cancelled, but unable to recreate one.
2022-03-08 19:05:13,104 - freqtrade.freqtradebot - INFO - Cancelling current stoploss on exchange for pair AUDIO/BUSD (orderid:113382975) in order to add another one ...
2022-03-08 19:05:13,264 - freqtrade.freqtradebot - ERROR - Could not cancel stoploss order 113382975 for pair AUDIO/BUSD
Traceback (most recent call last):
  File "/home/user/freqtrade/.env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 660, in fetch
    response.raise_for_status()
  File "/home/user/freqtrade/.env/lib/python3.8/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order?timestamp=1646730313104&recvWindow=5000&symbol=AUDIOBUSD&orderId=113382975&signature=<signature-removed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/freqtrade/freqtrade/exchange/exchange.py", line 943, in cancel_order
    order = self._api.cancel_order(order_id, pair)
  File "/home/user/freqtrade/.env/lib/python3.8/site-packages/ccxt/binance.py", line 2893, in cancel_order
    response = getattr(self, method)(self.extend(request, query))
  File "/home/user/freqtrade/.env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 502, in inner
    return entry(_self, **inner_kwargs)
  File "/home/user/freqtrade/.env/lib/python3.8/site-packages/ccxt/binance.py", line 4990, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/user/freqtrade/.env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 549, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/user/freqtrade/.env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 676, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/user/freqtrade/.env/lib/python3.8/site-packages/ccxt/binance.py", line 4968, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
  File "/home/user/freqtrade/.env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 567, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.OrderNotFound: binance {"code":-2011,"msg":"Unknown order sent."}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/freqtrade/freqtrade/freqtradebot.py", line 918, in handle_trailing_stoploss_on_exchange
    co = self.exchange.cancel_stoploss_order_with_result(order['id'], trade.pair,
  File "/home/user/freqtrade/freqtrade/exchange/exchange.py", line 1001, in cancel_stoploss_order_with_result
    corder = self.cancel_stoploss_order(order_id, pair)
  File "/home/user/freqtrade/freqtrade/exchange/common.py", line 125, in wrapper
    return f(*args, **kwargs)
  File "/home/user/freqtrade/freqtrade/exchange/exchange.py", line 947, in cancel_order
    raise InvalidOrderException(
freqtrade.exceptions.InvalidOrderException: Could not cancel order. Message: binance {"code":-2011,"msg":"Unknown order sent."}
2022-03-08 19:05:13,426 - freqtrade.freqtradebot - ERROR - Unable to place a stoploss order on exchange. Could not create stop_loss_limit sell order on market AUDIO/BUSD. Tried to sell amount 27.1 at rate 0.733. Message: binance Stop price would trigger immediately.
2022-03-08 19:05:13,426 - freqtrade.freqtradebot - WARNING - Exiting the trade forcefully
2022-03-08 19:05:13,928 - freqtrade.wallets - INFO - Wallets synced.
2022-03-08 19:05:13,928 - freqtrade.freqtradebot - WARNING - Unable to sell trade AUDIO/BUSD: Not enough amount to sell. Trade-amount: 27.1, Wallet: 0
2022-03-08 19:05:29,194 - freqtrade.freqtradebot - INFO - Pair AUDIO/BUSD is still locked until 2022-03-08 09:06:00 due to Auto lock.
```

**Comment by xmatthias** [comment]
Your levels are most likely too tight for pairs like Audio - and your roi / stoploss configuration makes it ... difficult - to say the least - as it's partially colliding after 40 minutes (which is what probably caused your issue).

While a sell was placed (i assume due to 0.5% profit - but maybe due to 1% profit?) - this might not have been 0.5% precisely, but maybe 0.51%  (this part is missing in the logs - so is speculation).
Having the rate dip over 0.51% triggers the stop to start trailing in your configuration.

So while you would've liked the stoploss to remain at 20% (static) - your trailing stop configuration caused it to start trailing - and update the stoploss to be at 0.5% below that price (which is in the worst case, at 0.1% profit).

The pair then started to drop (apparently - your sell wasn't filled) - and once the order canceled - a new stoploss was placed.
The rate is not too much below the open rate (maybe 0.1% or so) - so once all the exchange price rounding is in play (pairs usually only trade a limited amount of precision) - a deviation of a few .x% is very well possible (if the real rate was 0.7334 - it'd be rounded to 0.733).


In the end - your offsets (both stoploss - and the stoploss-positive) are too tight - you can't realistically operate with 0.1% levels in markets that move 1% and more - sometimes within one minute (or even one tik).

considering Audio's precision is 3 (0.001) - where one tick means 0.1% move (so the pair can't move 0.05%).

---

The only thing i don't understand is the log message at `2022-03-08 19:05:13,099` - which tries to enter the stoploss again - even though the pair sold already - which in the end caused the exception.

Everything else seems in order to me - or rather - a missconfiguration using too small values for the pair that's traded (you can probably use these values with BTC/USDT)...

**Comment by winginitau** [comment]
Thank you @xmatthias. Have been pondering this (and much other learnings) for a week. I now do understand why the emergency sell is normal and also your point on the trailing stop emergency sell. In my mental model, I still separate the conditions of overall stoploss (for a market crash) vs the trailing stoploss after a position is positiive, and think there is a logic case where if a trailing limit fails then then the bot does not emergency sell at market. In the latter, it may not be a crash. I may prefer to continue to hold until the position is positive again. However that is perhaps an edge case and would overly complicate the logic (espeically with exchange placed orders). I also now understand the rounding problem with the tight stops and triggers. Many thanks!
