### ISSUE TITLE
Async code raised an exception: KeyError('15m') and invalid HTTP request

### ISSUE THREAD

**Issue by lsiem** [freqtrade/freqtrade#6517]
## Describe your environment

  * Operating system: Debian 11 with linux 5.10.0-10-amd64
  * Python Version: Python 3.9.2
  * CCXT version: No output
  * Freqtrade Version: freqtrade 2022.2.1
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*
Running freqtrade with or without error raises following exception below.

### Steps to reproduce:

  1. Run freqtrade with or without docker with the following configuration:
 ```
{
    "timeframe": "5m",
    "max_open_trades": 7,
    "stake_currency": "USDT",
    "stake_amount": "unlimited",
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "position_adjustment_enable": false,
    "unfilledtimeout": {
        "buy": 15,
        "sell": 15,
        "unit": "minutes"
    },
    "order_types": {
        "buy": "limit",
        "sell": "limit",
        "emergencysell": "limit",
        "forcebuy": "limit",
        "forcesell": "limit",
        "stoploss": "limit",
        "stoploss_on_exchange": false,
        "stoploss_on_exchange_interval": 60
    },
    "bid_strategy": {
        "price_side": "ask",
        "ask_last_balance": 0,
        "use_order_book": false,
        "order_book_top": 1,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "ask_strategy": {
        "price_side": "bid",
        "use_order_book": false,
        "order_book_top": 1
    }
}
```

### Observed Results:

Bot does not trade

### Relevant code exceptions or logs

```
2022-03-10 14:17:26 - freqtrade.exchange.exchange - WARNING - Async code raised an exception: KeyError('15m')
2022-03-10 14:17:26 - freqtrade.exchange.exchange - WARNING - Async code raised an exception: RuntimeError('No active exception to reraise')
2022-03-10 14:17:26 - freqtrade.freqtradebot - INFO - Active pair whitelist is empty.
2022-03-10 14:17:28 - uvicorn.error - WARNING - Invalid HTTP request received.
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 129, in handle_events
    event = self.conn.next_event()
  File "/home/ftuser/.local/lib/python3.9/site-packages/h11/_connection.py", line 485, in next_event
    exc._reraise_as_remote_protocol_error()
  File "/home/ftuser/.local/lib/python3.9/site-packages/h11/_util.py", line 77, in _reraise_as_remote_protocol_error
    raise self
  File "/home/ftuser/.local/lib/python3.9/site-packages/h11/_connection.py", line 467, in next_event
    event = self._extract_next_receive_event()
  File "/home/ftuser/.local/lib/python3.9/site-packages/h11/_connection.py", line 409, in _extract_next_receive_event
    event = self._reader(self._receive_buffer)
  File "/home/ftuser/.local/lib/python3.9/site-packages/h11/_readers.py", line 81, in maybe_read_from_IDLE_client
    raise LocalProtocolError("illegal request line")
h11._util.RemoteProtocolError: illegal request line
2022-03-10 14:17:28 - uvicorn.error - WARNING - Invalid HTTP request received.
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 129, in handle_events
    event = self.conn.next_event()
  File "/home/ftuser/.local/lib/python3.9/site-packages/h11/_connection.py", line 485, in next_event
    exc._reraise_as_remote_protocol_error()
  File "/home/ftuser/.local/lib/python3.9/site-packages/h11/_util.py", line 77, in _reraise_as_remote_protocol_error
    raise self
  File "/home/ftuser/.local/lib/python3.9/site-packages/h11/_connection.py", line 467, in next_event
    event = self._extract_next_receive_event()
  File "/home/ftuser/.local/lib/python3.9/site-packages/h11/_connection.py", line 409, in _extract_next_receive_event
    event = self._reader(self._receive_buffer)
  File "/home/ftuser/.local/lib/python3.9/site-packages/h11/_readers.py", line 81, in maybe_read_from_IDLE_client
    raise LocalProtocolError("illegal request line")
h11._util.RemoteProtocolError: illegal request line
```

**Comment by xmatthias** [comment]
The exception doesn't really make sense with this configuration, unless your strategy is using 15m informative pairs?
also, which exchange are we talking about?

Also - please provide "a bit more" logs - more than just the exception in any case to help us determine at what point the bot is at that moment - the log appears to originate from the API - which is disconnected from the trading module, and can therefore not really cause the bot to "not trade".
Maybe try to close freqUI (or other things that try to connect to the API) and try again - that should show different errors (or no errors, if nothing is wrong).

**Comment by lsiem** [comment]
Here are the full logs (Tell me whether I should provide more details (maybe with higher verbosity level?)
```
2022-03-11 08:12:45,494 - freqtrade.worker - INFO - Starting worker 2022.2.1

2022-03-11 08:12:45,494 - freqtrade.configuration.configuration - INFO - Using config: /freqtrade/user_data/pairlist-volume-binance-usdt.json ...

2022-03-11 08:12:45,495 - freqtrade.configuration.configuration - INFO - Using config: /freqtrade/user_data/blacklist-binance.json ...

2022-03-11 08:12:45,495 - freqtrade.configuration.configuration - INFO - Using config: /freqtrade/user_data/config.json ...

2022-03-11 08:12:45,495 - freqtrade.configuration.configuration - INFO - Using config: /freqtrade/user_data/config.private.json ...

2022-03-11 08:12:45,496 - freqtrade.loggers - INFO - Verbosity set to 0

2022-03-11 08:12:45,497 - freqtrade.configuration.configuration - INFO - Runmode set to live.

2022-03-11 08:12:45,497 - freqtrade.configuration.configuration - INFO - Parameter --db-url detected ...

2022-03-11 08:12:45,497 - freqtrade.configuration.configuration - INFO - Dry run is disabled

2022-03-11 08:12:45,497 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:////freqtrade/user_data/tradesv3.sqlite"

2022-03-11 08:12:45,498 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 7 ...

2022-03-11 08:12:45,517 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...

2022-03-11 08:12:45,518 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/bittrex ...

2022-03-11 08:12:45,518 - freqtrade.configuration.check_exchange - INFO - Checking exchange...

2022-03-11 08:12:45,524 - freqtrade.configuration.check_exchange - INFO - Exchange "bittrex" is officially supported by the Freqtrade development team.

2022-03-11 08:12:45,524 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.

2022-03-11 08:12:45,525 - freqtrade.freqtradebot - INFO - Starting freqtrade 2022.2.1

2022-03-11 08:12:45,850 - NostalgiaForInfinityX - INFO - pandas_ta successfully imported

2022-03-11 08:12:45,854 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy NostalgiaForInfinityX from '/freqtrade/user_data/strategies/NostalgiaForInfinityX.py'...

2022-03-11 08:12:45,854 - freqtrade.strategy.hyper - INFO - Found no parameter file.

2022-03-11 08:12:45,855 - freqtrade.strategy.hyper - INFO - No params for protection found, using default values.

2022-03-11 08:12:45,855 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 5m.

2022-03-11 08:12:45,856 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'order_types' with value in config file: {'buy': 'limit', 'sell': 'limit', 'emergencysell': 'limit', 'forcebuy': 'limit', 'forcesell': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False, 'stoploss_on_exchange_interval': 60}.

2022-03-11 08:12:45,856 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.

2022-03-11 08:12:45,856 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: unlimited.

2022-03-11 08:12:45,856 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'buy': 15, 'sell': 15, 'unit': 'minutes'}.

2022-03-11 08:12:45,857 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'position_adjustment_enable' with value in config file: False.

2022-03-11 08:12:45,857 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 100.0}

2022-03-11 08:12:45,857 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 5m

2022-03-11 08:12:45,857 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.99

2022-03-11 08:12:45,857 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False

2022-03-11 08:12:45,858 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive: 0.01

2022-03-11 08:12:45,858 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.03

2022-03-11 08:12:45,858 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: True

2022-03-11 08:12:45,858 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False

2022-03-11 08:12:45,858 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: True

2022-03-11 08:12:45,859 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'emergencysell': 'limit', 'forcebuy': 'limit', 'forcesell': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False, 'stoploss_on_exchange_interval': 60}

2022-03-11 08:12:45,859 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}

2022-03-11 08:12:45,859 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT

2022-03-11 08:12:45,859 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: unlimited

2022-03-11 08:12:45,859 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []

2022-03-11 08:12:45,860 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 480

2022-03-11 08:12:45,860 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'buy': 15, 'sell': 15, 'unit': 'minutes'}

2022-03-11 08:12:45,860 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_sell_signal: True

2022-03-11 08:12:45,860 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_only: False

2022-03-11 08:12:45,861 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_buy_signal: True

2022-03-11 08:12:45,861 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_offset: 0.0

2022-03-11 08:12:45,861 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False

2022-03-11 08:12:45,861 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0

2022-03-11 08:12:45,861 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: False

2022-03-11 08:12:45,862 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1

2022-03-11 08:12:45,862 - freqtrade.configuration.config_validation - INFO - Validating configuration ...

2022-03-11 08:12:45,867 - freqtrade.exchange.exchange - INFO - Using CCXT 1.73.70

2022-03-11 08:12:45,874 - freqtrade.exchange.exchange - INFO - Using Exchange "Bittrex"

2022-03-11 08:12:49,078 - freqtrade.exchange.exchange - WARNING - Using 2 calls to get OHLCV. This can result in slower operations for the bot. Please check if you really need 480 candles for your strategy

2022-03-11 08:12:49,078 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Bittrex'...

2022-03-11 08:12:49,136 - freqtrade.wallets - INFO - Wallets synced.

2022-03-11 08:12:49,137 - freqtrade.plugins.protectionmanager - INFO - No protection Handlers defined.

2022-03-11 08:12:49,217 - freqtrade.rpc.rpc_manager - INFO - Enabling rpc.telegram ...

/home/ftuser/.local/lib/python3.9/site-packages/telegram/ext/dispatcher.py:250: UserWarning: Asynchronous callbacks can not be processed without at least one worker thread.

  warnings.warn(

2022-03-11 08:12:49,362 - apscheduler.scheduler - INFO - Scheduler started

2022-03-11 08:12:49,407 - freqtrade.rpc.telegram - INFO - rpc.telegram is listening for following commands: [['status'], ['profit'], ['balance'], ['start'], ['stop'], ['forcesell'], ['forcebuy'], ['trades'], ['delete'], ['performance'], ['buys'], ['sells'], ['mix_tags'], ['stats'], ['daily'], ['weekly'], ['monthly'], ['count'], ['locks'], ['unlock', 'delete_locks'], ['reload_config', 'reload_conf'], ['show_config', 'show_conf'], ['stopbuy'], ['whitelist'], ['blacklist'], ['blacklist_delete', 'bl_delete'], ['logs'], ['edge'], ['health'], ['help'], ['version']]

2022-03-11 08:12:49,407 - freqtrade.rpc.rpc_manager - INFO - Enabling rpc.api_server

2022-03-11 08:12:50,042 - freqtrade.rpc.api_server.webserver - INFO - Starting HTTP Server at 0.0.0.0:8090

2022-03-11 08:12:50,042 - freqtrade.rpc.api_server.webserver - WARNING - SECURITY WARNING - Local Rest Server listening to external connections

2022-03-11 08:12:50,042 - freqtrade.rpc.api_server.webserver - WARNING - SECURITY WARNING - This is insecure please set to your loopback,e.g 127.0.0.1 in config.json

2022-03-11 08:12:50,043 - freqtrade.rpc.api_server.webserver - WARNING - SECURITY WARNING - `jwt_secret_key` seems to be default.Others may be able to log into your bot.

2022-03-11 08:12:50,043 - freqtrade.rpc.api_server.webserver - INFO - Starting Local Rest Server.

2022-03-11 08:12:50,064 - uvicorn.error - INFO - Started server process [1]

2022-03-11 08:12:50,065 - uvicorn.error - INFO - Waiting for application startup.

2022-03-11 08:12:50,065 - uvicorn.error - INFO - Application startup complete.

2022-03-11 08:12:50,065 - uvicorn.error - INFO - Uvicorn running on http://0.0.0.0:8090 (Press CTRL+C to quit)

2022-03-11 08:12:50,078 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist VolumePairList from '/freqtrade/freqtrade/plugins/pairlist/VolumePairList.py'...

2022-03-11 08:12:50,080 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist AgeFilter from '/freqtrade/freqtrade/plugins/pairlist/AgeFilter.py'...

2022-03-11 08:12:50,083 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist RangeStabilityFilter from '/freqtrade/freqtrade/plugins/pairlist/rangestabilityfilter.py'...

2022-03-11 08:12:50,094 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist VolatilityFilter from '/freqtrade/freqtrade/plugins/pairlist/VolatilityFilter.py'...

2022-03-11 08:12:50,106 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist ShuffleFilter from '/freqtrade/freqtrade/plugins/pairlist/ShuffleFilter.py'...

2022-03-11 08:12:50,106 - ShuffleFilter - INFO - Live mode detected, not applying seed.

2022-03-11 08:12:50,688 - VolumePairList - INFO - Pair ADABULL/USDT in your blacklist. Removing it from whitelist...

2022-03-11 08:12:50,688 - VolumePairList - INFO - Pair ATOMBULL/USDT in your blacklist. Removing it from whitelist...

2022-03-11 08:12:50,689 - VolumePairList - INFO - Pair BCHBULL/USDT in your blacklist. Removing it from whitelist...

2022-03-11 08:12:50,689 - VolumePairList - INFO - Pair BEAR/USDT in your blacklist. Removing it from whitelist...

2022-03-11 08:12:50,689 - VolumePairList - INFO - Pair BRZ/USDT in your blacklist. Removing it from whitelist...

2022-03-11 08:12:50,690 - VolumePairList - INFO - Pair BULL/USDT in your blacklist. Removing it from whitelist...

2022-03-11 08:12:50,690 - VolumePairList - INFO - Pair DAI/USDT in your blacklist. Removing it from whitelist...

2022-03-11 08:12:50,690 - VolumePairList - INFO - Pair DOGEBULL/USDT in your blacklist. Removing it from whitelist...

2022-03-11 08:12:50,690 - VolumePairList - INFO - Pair ETHBEAR/USDT in your blacklist. Removing it from whitelist...

2022-03-11 08:12:50,691 - VolumePairList - INFO - Pair ETHBULL/USDT in your blacklist. Removing it from whitelist...

2022-03-11 08:12:50,691 - VolumePairList - INFO - Pair HBAR/USDT in your blacklist. Removing it from whitelist...

2022-03-11 08:12:50,691 - VolumePairList - INFO - Pair LINKBULL/USDT in your blacklist. Removing it from whitelist...

2022-03-11 08:12:50,691 - VolumePairList - INFO - Pair MATICBULL/USDT in your blacklist. Removing it from whitelist...

2022-03-11 08:12:50,691 - VolumePairList - INFO - Pair NMR/USDT in your blacklist. Removing it from whitelist...

2022-03-11 08:12:50,692 - VolumePairList - INFO - Pair OMG/USDT in your blacklist. Removing it from whitelist...

2022-03-11 08:12:50,692 - VolumePairList - INFO - Pair TUSD/USDT in your blacklist. Removing it from whitelist...

2022-03-11 08:12:50,692 - VolumePairList - INFO - Pair USDC/USDT in your blacklist. Removing it from whitelist...

2022-03-11 08:12:50,692 - VolumePairList - INFO - Pair UST/USDT in your blacklist. Removing it from whitelist...

2022-03-11 08:12:50,693 - VolumePairList - INFO - Pair XRPBULL/USDT in your blacklist. Removing it from whitelist...

2022-03-11 08:12:50,693 - VolumePairList - INFO - Pair XTZBULL/USDT in your blacklist. Removing it from whitelist...

2022-03-11 08:12:50,711 - VolumePairList - INFO - Searching 80 pairs: []

2022-03-11 08:12:50,727 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'running'}

2022-03-11 08:12:50,820 - freqtrade.worker - INFO - Changing state to: RUNNING

2022-03-11 08:12:50,820 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': "*Exchange:* `bittrex`\n*Stake per trade:* `unlimited USDT`\n*Minimum ROI:* `{'0': 100.0}`\n*Stoploss:* `-0.99`\n*Position adjustment:* `Off`\n*Timeframe:* `5m`\n*Strategy:* `NostalgiaForInfinityX`"}

2022-03-11 08:12:50,872 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': "Searching for USDT pairs to buy and sell based on [{'VolumePairList': 'VolumePairList - top 80 volume pairs.'}, {'AgeFilter': 'AgeFilter - Filtering pairs with age less than 2 days'}, {'RangeStabilityFilter': 'RangeStabilityFilter - Filtering pairs with rate of change below 0.03 over the last days.'}, {'VolatilityFilter': 'VolatilityFilter - Filtering pairs with volatility range 0.02-0.75  the last 3 days.'}, {'ShuffleFilter': 'ShuffleFilter - Shuffling pairs.'}]"}

2022-03-11 08:12:50,980 - freqtrade.freqtradebot - INFO - Updating 0 open orders.

2022-03-11 08:12:51,047 - freqtrade.exchange.exchange - WARNING - Async code raised an exception: KeyError('15m')

2022-03-11 08:12:57,199 - freqtrade.data.converter - INFO - Missing data fillup for BTC/USDT: before: 476 - after: 575 - 20.80%

2022-03-11 08:12:57,214 - freqtrade.exchange.exchange - WARNING - Async code raised an exception: RuntimeError('No active exception to reraise')

2022-03-11 08:12:57,234 - freqtrade.freqtradebot - INFO - Active pair whitelist is empty.

2022-03-11 08:12:57,235 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2022.2.1, strategy_version: v11.0.377', state='RUNNING'

2022-03-11 08:12:57,294 - freqtrade.exchange.exchange - WARNING - Async code raised an exception: KeyError('15m')

2022-03-11 08:12:57,295 - freqtrade.exchange.exchange - WARNING - Async code raised an exception: RuntimeError('No active exception to reraise')

2022-03-11 08:12:57,297 - freqtrade.freqtradebot - INFO - Active pair whitelist is empty.

2022-03-11 08:13:02,296 - freqtrade.exchange.exchange - WARNING - Async code raised an exception: KeyError('15m')

2022-03-11 08:13:02,297 - freqtrade.exchange.exchange - WARNING - Async code raised an exception: RuntimeError('No active exception to reraise')

2022-03-11 08:13:02,299 - freqtrade.freqtradebot - INFO - Active pair whitelist is empty.

2022-03-11 08:13:07,309 - freqtrade.exchange.exchange - WARNING - Async code raised an exception: KeyError('15m')

2022-03-11 08:13:07,309 - freqtrade.exchange.exchange - WARNING - Async code raised an exception: RuntimeError('No active exception to reraise')

2022-03-11 08:13:07,311 - freqtrade.freqtradebot - INFO - Active pair whitelist is empty.
```

I've already restarted the docker stack including frequi. Unfortunately the same error occurs.
I am using this strategy: [https://github.com/iterativv/NostalgiaForInfinity](url)

**Comment by xmatthias** [comment]
` freqtrade list-timeframes --exchange bittrex` will show you all valid timeframes for your exchange.

15m is not among them (bittrex only supports 1m, 5m, 1h, 1d).

I'll assume that the strategy is using 15m as informative pair - but i'll not go and look at a full strategy in a different repository for this.
This is an information you should be able to answer "right away" - potentially without even thinking (or if any - does this particular strategy use 15m, or the other one).
otherwise you're running a black-box strategy, which you don't understand - and which is therefore pretty dangerous to your capital (others decide how your money is spent).

The fact that you're encountering this when running in trade mode (not while backtesting) tells me that you've not backtested the strategy (at least not with bittrex market data - as that would not have 15m data available) - so i'd strongly advise to change the approach you're taking. There will be no "setup and be rich" strategy even if the strategy may promise so. 
There will be no strategy that transfers to different exchanges / markets without modifications (or at least without testing / evaluation first).

We'll slightly change the output - but there's nothing to do about the fact that 15m is not available on bittrex - so best switch to a different exchange - or a different strategy.
