### ISSUE TITLE
Issue with not accepted XXX/USDT pairs

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#6524]
## Describe your environment

  * Operating system: Windows Server 2022
  * Python Version: Miniconda
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2022.2.1 develop 24f480b  ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

User based Freqtrade installations, dryrunning on gate.io do not start, because common "XXX"/USDT pairs are not recognized on the exchange, even they are generally valid. I try to find a way to analyze the reason, why the user-based installation, which took place on March 11th, works fine, while installations, taking place one day later, on the same machine (other Windows user), do not start, according to my above description.

One example of error message:
freqtrade.exceptions.OperationalException: Pair 1INCH3L/USDT is not available on Gate.io. Please remove 1INCH3L/USDT from your whitelist.

In fact this pair is always valid and functional on gate.io. The same error takes place with non-leverage tokens.

The installation processes of the functional user instance and the one, which does not start, are absolutely identical, and they are usually working fine, since version 2020.12

Even I have no proof, it seems to me, that probably since less than 24 hours, there is a very small difference within the download, which takes place, as Freqtrade is rolled out by 'conda env create -f environment.yml'. Currently I do not find a different explanation.

Tell me, if you need any additional detail.

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
one thing to look at for sure is the ccxt version of both installations these change weekly - so between stable and develop, there's for sure been an update.
That said, i tried with the latest version - and there is no issue at the moment.

conda installation is ... not very well maintained (it's very rarely used).

You can "quick-check" this with `freqtrade list-pairs --exchange gateio --base 1INCH` (or whatever other pair) - which should show that they are available.


Please post the full log up to the exception (please wrap it in  tripple backticks (`) so it renders well) - as the error can also be a leading/trailing space.

**Comment by myNextCoder** [comment]
I thank you. I checked all available USDT currency pairs on gate.io with this syntax:
freqtrade list-pairs --exchange gateio --quote USDT --one-column

I checked with stable version 2022.1, I installed on February 21. with ccxt 1.73.78, and I got 1551 available pairs.
And I also checked with develop version 2022.2.1 24f480b, I installed now, some minutes ago, with ccxt 1.75.93, and I got only 393 active pairs.
On this background I understand, why most pairs on the second instance won't be valid. But how is this possible, as both commands check on gate.io with the same command?

I send you the full log of the instance, I installed just now, develop 2022.2.1 24f480b, ccxt 1.75.93, which has only the above 393 pairs (far not enough for the exchange gate.io). The log is generated, as I start the bot normally:

```2022-03-12 16:34:37,751 - freqtrade.worker - INFO - Starting worker develop
2022-03-12 16:34:37,751 - freqtrade.configuration.configuration - INFO - Using config: C:\Ftconfig\telegram_config1.json ...
2022-03-12 16:34:37,751 - freqtrade.configuration.configuration - INFO - Using config: C:\FTconfig\SL_config2.json ...
2022-03-12 16:34:37,751 - freqtrade.configuration.configuration - INFO - Using config: C:\FTconfig\sell_signal_config1.json ...
2022-03-12 16:34:37,751 - freqtrade.configuration.configuration - INFO - Using config: C:\FTconfig\ct2FT17BotGateio1.json ...
2022-03-12 16:34:37,751 - freqtrade.configuration.configuration - INFO - Using config: C:\FTconfig\gateio_pairlist_USDT_lev_config.json ...
2022-03-12 16:34:37,751 - freqtrade.configuration.configuration - INFO - Using config: C:\FTconfig\placeholder_config1.json ...
2022-03-12 16:34:37,767 - freqtrade.loggers - INFO - Verbosity set to 0
2022-03-12 16:34:37,767 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
2022-03-12 16:34:37,767 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2022-03-12 16:34:37,767 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:///tradesv3.dryrun.sqlite"
2022-03-12 16:34:37,767 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 40 ...
2022-03-12 16:34:37,767 - freqtrade.configuration.configuration - INFO - Parameter --dry-run-wallet detected, overriding dry_run_wallet to: 10000.0 ...
2022-03-12 16:34:37,767 - freqtrade.configuration.configuration - INFO - Using user-data directory: C:\Users\a6\Freqtrade\user_data ...
2022-03-12 16:34:37,767 - freqtrade.configuration.configuration - INFO - Using data directory: C:\Users\a6\Freqtrade\user_data\data\gateio ...
2022-03-12 16:34:37,767 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2022-03-12 16:34:37,782 - freqtrade.configuration.check_exchange - INFO - Exchange "gateio" is officially supported by the Freqtrade development team.
2022-03-12 16:34:37,782 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2022-03-12 16:34:37,782 - freqtrade.freqtradebot - INFO - Starting freqtrade develop
2022-03-12 16:34:37,876 - freqtrade.resolvers.iresolver - WARNING - Could not import C:\FTstrategies\BinHV27Chain.py due to 'name 'Tuple' is not defined'
2022-03-12 16:34:37,892 - freqtrade.resolvers.iresolver - WARNING - Could not import C:\FTstrategies\ClucHAwerk_Guacamole.py due to 'name 'ClucHAwerk' is not defined'
2022-03-12 16:34:38,189 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy FisherHull from 'C:\FTstrategies\FisherHull.py'...
2022-03-12 16:34:38,189 - freqtrade.strategy.hyper - INFO - Found no parameter file.
2022-03-12 16:34:38,189 - freqtrade.strategy.hyper - INFO - No params for buy found, using default values.
2022-03-12 16:34:38,189 - freqtrade.strategy.hyper - INFO - No params for sell found, using default values.
2022-03-12 16:34:38,189 - freqtrade.strategy.hyper - INFO - No params for protection found, using default values.
2022-03-12 16:34:38,204 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 1m.
2022-03-12 16:34:38,204 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stoploss' with value in config file: -0.99.
2022-03-12 16:34:38,204 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'trailing_stop' with value in config file: False.
2022-03-12 16:34:38,204 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'trailing_stop_positive' with value in config file: 0.005.
2022-03-12 16:34:38,204 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'trailing_stop_positive_offset' with value in config file: 0.0051.
2022-03-12 16:34:38,204 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'trailing_only_offset_is_reached' with value in config file: False.
2022-03-12 16:34:38,204 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'order_types' with value in config file: {'buy': 'limit', 'sell': 'limit', 'emergencysell': 'limit', 'forcesell': 'limit', 'forcebuy': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False, 'stoploss_on_exchange_interval': 60}.
2022-03-12 16:34:38,204 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'order_time_in_force' with value in config file: {'buy': 'gtc', 'sell': 'gtc'}.
2022-03-12 16:34:38,204 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2022-03-12 16:34:38,204 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 25.
2022-03-12 16:34:38,204 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'buy': 10, 'sell': 30, 'unit': 'minutes'}.
2022-03-12 16:34:38,204 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'use_sell_signal' with value in config file: True.
2022-03-12 16:34:38,204 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'sell_profit_only' with value in config file: True.
2022-03-12 16:34:38,204 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ignore_roi_if_buy_signal' with value in config file: False.
2022-03-12 16:34:38,204 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'sell_profit_offset' with value in config file: 0.0.
2022-03-12 16:34:38,204 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'disable_dataframe_checks' with value in config file: False.
2022-03-12 16:34:38,204 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 1000}
2022-03-12 16:34:38,204 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 1m
2022-03-12 16:34:38,204 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.99
2022-03-12 16:34:38,204 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2022-03-12 16:34:38,204 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive: 0.005
2022-03-12 16:34:38,204 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0051
2022-03-12 16:34:38,204 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2022-03-12 16:34:38,204 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2022-03-12 16:34:38,220 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
2022-03-12 16:34:38,220 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'emergencysell': 'limit', 'forcesell': 'limit', 'forcebuy': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False, 'stoploss_on_exchange_interval': 60}
2022-03-12 16:34:38,220 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
2022-03-12 16:34:38,220 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2022-03-12 16:34:38,220 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 25
2022-03-12 16:34:38,220 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2022-03-12 16:34:38,220 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 0
2022-03-12 16:34:38,220 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'buy': 10, 'sell': 30, 'unit': 'minutes'}
2022-03-12 16:34:38,220 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_sell_signal: True
2022-03-12 16:34:38,220 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_only: True
2022-03-12 16:34:38,220 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_buy_signal: False
2022-03-12 16:34:38,220 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_offset: 0.0
2022-03-12 16:34:38,220 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2022-03-12 16:34:38,220 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2022-03-12 16:34:38,220 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: False
2022-03-12 16:34:38,220 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1
2022-03-12 16:34:38,220 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2022-03-12 16:34:38,236 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2022-03-12 16:34:38,236 - freqtrade.exchange.exchange - INFO - Using CCXT 1.75.93
2022-03-12 16:34:38,251 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'options': {'adjustForTimeDifference': True}}
2022-03-12 16:34:38,267 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'options': {'adjustForTimeDifference': True}, 'rateLimit': 200, 'aiohttp_trust_env': False}
2022-03-12 16:34:38,282 - freqtrade.exchange.exchange - INFO - Using Exchange "Gate.io"
2022-03-12 16:34:43,548 - freqtrade.commands.trade_commands - ERROR - Pair 1INCH3L/USDT is not available on Gate.io. Please remove 1INCH3L/USDT from your whitelist.
2022-03-12 16:34:43,548 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "c:\users\a6\freqtrade\freqtrade\commands\trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "c:\users\a6\freqtrade\freqtrade\worker.py", line 35, in __init__
    self._init(False)
  File "c:\users\a6\freqtrade\freqtrade\worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "c:\users\a6\freqtrade\freqtrade\freqtradebot.py", line 63, in __init__
    self.exchange = ExchangeResolver.load_exchange(self.config['exchange']['name'], self.config)
  File "c:\users\a6\freqtrade\freqtrade\resolvers\exchange_resolver.py", line 32, in load_exchange
    exchange = ExchangeResolver._load_exchange(exchange_name,
  File "c:\users\a6\freqtrade\freqtrade\resolvers\exchange_resolver.py", line 54, in _load_exchange
    exchange = ex_class(**kwargs)
  File "c:\users\a6\freqtrade\freqtrade\exchange\exchange.py", line 159, in __init__
    self.validate_pairs(config['exchange']['pair_whitelist'])
  File "c:\users\a6\freqtrade\freqtrade\exchange\exchange.py", line 402, in validate_pairs
    raise OperationalException(
freqtrade.exceptions.OperationalException: Pair 1INCH3L/USDT is not available on Gate.io. Please remove 1INCH3L/USDT from your whitelist.```

(Those strategies, which wheren't imported are not listed by myself, this message usually has no effect. The strategy named FisherHull is set in this test)

**Comment by xmatthias** [comment]
Things change all the time ... especially in exchanges, and therefore also with ccxt.

if you install `pip install ccxt==1.74.63` - then you'll get 1551 pairs. 
Now if 1551 or 393 is correct is beyond me.

The thing i noticed though is that the pair `1INCH3L/USDT` does not seem to be a regular spot pair - but a ETF pair based on the gate.io website.
it's also not included in the load_markets response - therefore freqtrade can't use it.

I've opened a ticket for this on ccxt (https://github.com/ccxt/ccxt/issues/12321) - it seems to expand to quite a few pairs ...

**Comment by myNextCoder** [comment]
I thank you very much.
The big thing now seems to be the ccxt version. I continue with my tests on this. What is interesting, that I use gate.io bots with leverage tokens since months, and I put all 3L, 3S, 5L and 5S tokens into the whitelist. They have always worked, but not anymore, as I wanted to leave stable version 2022.1 for a newer one yesterday.

My working server, which still runs on stable version 2022.1 sold the token 1INCH3L for example on March, 9th:

![image](https://user-images.githubusercontent.com/34372534/158026278-75619980-ea41-480a-9c3d-982a5ba6be89.png)

Really great for having opened this ticket. I look forward to any news.
If I gather out a (partial) solution for my case, I let you know.

**Comment by xmatthias** [comment]
there's now a PR available in ccxt which will address this - so there's "help on the way" :laughing: 
which also means that investigating other solutions will be a waste of time :)

**Comment by myNextCoder** [comment]
Many thanks. Does that mean, that the issue is already resolved "outside" of Freqtrade? Or should I take the develop version 7825d85, which will address this?

**Comment by xmatthias** [comment]
stick to the ccxt version you used for now. It's not a problem of freqtrade, but of the current ccxt version.

**Comment by myNextCoder** [comment]
I should be able to make a rollback of my VM, to have the state of 48 hours ago, if necessary. Reading between your lines, I see, that ccxt version will change fast, so if I still run into a problem, it will be resolved really soon, I guess.

**Comment by xmatthias** [comment]
The very latest version (can be installed via `pip install -U ccxt`) should resolve this particular problem.

I'm not 100% sure about another problem yet, so i'd recommend to stick to the old version for the moment (`pip install ccxt==1.74.63`).

Be careful with rolling VM's back - that'll also reset the database status ...

**Comment by myNextCoder** [comment]
Great, I give you my news, after testing with your ccxt recommendations.
I am lucky: During the issue I was able to run a backup server, so after rolling back the original VM, I first copied the databases from the backup server into the freshly rolled back VM.

**Comment by myNextCoder** [comment]
I can inform you happily, that with develop version 2022.2.1 7825d85, on March 13th, 01.45 PM (UTC+01.00) everything works fine again, even without installing any other cctx version.
Fully functional leverage token whitelist on gate.io:
![image](https://user-images.githubusercontent.com/34372534/158060198-5abe5a30-cd6b-45ab-856f-af881a32b66a.png)
