### ISSUE TITLE
Bot restarted on TypeError: can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by Niqnil** [freqtrade/freqtrade#6578]
## Describe your environment

  * Operating system: Debian 11 x64 (bullseye)
  * Python Version: Python 3.9.9
  * CCXT version: ccxt==1.73.70
  * Freqtrade Version: freqtrade 2022.2.1
  * Exchange: FTX

## Describe the problem:

Checked telegram and saw `Status: process died` and bot restarted. As far as I know, this happened once only. Not sure if it is an issue. I am reporting in case it needs a fix.
Please see logs below.

### Relevant code exceptions or logs

  ```
freqtrade_COM1d | 2022-03-21 23:42:40,083 - freqtrade.exchange.common - WARNING - fetch_ticker() returned exception: "Could not load ticker due to RequestTimeout. Message: ftx GET https://ftx.com/api/markets/AAVE/USD". Retrying still for 4 times.
freqtrade_COM1d | 2022-03-21 23:43:05,266 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2022.2.1, strategy_version: COM1d_v2022.03.04', state='RUNNING'

# Normal running logs removed

freqtrade_COM1d | 2022-03-21 23:59:06,051 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2022.2.1, strategy_version: COM1d_v2022.03.04', state='RUNNING'
freqtrade_COM1d | 2022-03-22 00:00:01,663 - AgeFilter - INFO - Removed LUNA/USD from whitelist, because age 20 is less than 94 days
freqtrade_COM1d | 2022-03-22 00:00:01,665 - AgeFilter - INFO - Removed LOOKS/USD from whitelist, because age 69 is less than 94 days
freqtrade_COM1d | 2022-03-22 00:00:01,666 - AgeFilter - INFO - Removed DOT/USD from whitelist, because age 91 is less than 94 days
freqtrade_COM1d | 2022-03-22 00:00:01,666 - AgeFilter - INFO - Removed ATOM/USD from whitelist, because age 21 is less than 94 days
freqtrade_COM1d | 2022-03-22 00:00:01,667 - AgeFilter - INFO - Validated 45 pairs.
freqtrade_COM1d | 2022-03-22 00:00:11,606 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2022.2.1, strategy_version: COM1d_v2022.03.04', state='RUNNING'
freqtrade_COM1d | 2022-03-22 00:00:11,701 - freqtrade.commands.trade_commands - ERROR - can only concatenate str (not "NoneType") to str
freqtrade_COM1d | 2022-03-22 00:00:11,701 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
freqtrade_COM1d | Traceback (most recent call last):
freqtrade_COM1d |   File "/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
freqtrade_COM1d |     worker.run()
freqtrade_COM1d |   File "/freqtrade/freqtrade/worker.py", line 74, in run
freqtrade_COM1d |     state = self._worker(old_state=state)
freqtrade_COM1d |   File "/freqtrade/freqtrade/worker.py", line 114, in _worker
freqtrade_COM1d |     self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
freqtrade_COM1d |   File "/freqtrade/freqtrade/worker.py", line 139, in _throttle
freqtrade_COM1d |     result = func(*args, **kwargs)
freqtrade_COM1d |   File "/freqtrade/freqtrade/worker.py", line 152, in _process_running
freqtrade_COM1d |     self.freqtrade.process()
freqtrade_COM1d |   File "/freqtrade/freqtrade/freqtradebot.py", line 153, in process
freqtrade_COM1d |     self.exchange.reload_markets()
freqtrade_COM1d |   File "/freqtrade/freqtrade/exchange/exchange.py", line 360, in reload_markets
freqtrade_COM1d |     self._markets = self._api.load_markets(reload=True)
freqtrade_COM1d |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 1516, in load_markets
freqtrade_COM1d |     markets = self.fetch_markets(params)
freqtrade_COM1d |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/ftx.py", line 597, in fetch_markets
freqtrade_COM1d |     raise BadResponse(self.id + " symbol '" + id + "' is a future contract but with invalid expiry datetime: " + expiryDatetime)
freqtrade_COM1d | TypeError: can only concatenate str (not "NoneType") to str
freqtrade_COM1d | 2022-03-22 00:00:11,715 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
freqtrade_COM1d | 2022-03-22 00:00:11,716 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
freqtrade_COM1d | 2022-03-22 00:00:12,583 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
freqtrade_COM1d | 2022-03-22 00:00:12,589 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': warning, 'status': "5 open trades active.\n\nHandle these trades manually on FTX, or '/start' the bot again and use '/stopbuy' to handle open trades gracefully. \n"}
freqtrade_COM1d | 2022-03-22 00:00:13,022 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
freqtrade_COM1d | 2022-03-22 00:00:13,022 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.telegram ...
freqtrade_COM1d | 2022-03-22 00:00:13,023 - apscheduler.scheduler - INFO - Scheduler has been shut down
freqtrade_COM1d | 2022-03-22 00:00:26,712 - freqtrade.exchange.exchange - INFO - Closing async ccxt session.
freqtrade_COM1d | 2022-03-22 00:00:34,951 - freqtrade.worker - INFO - Starting worker 2022.2.1
freqtrade_COM1d | 2022-03-22 00:00:34,952 - freqtrade.configuration.configuration - INFO - Using config: /freqtrade/user_data/config.json ...
freqtrade_COM1d | 2022-03-22 00:00:34,956 - freqtrade.configuration.configuration - INFO - Using config: /freqtrade/user_data/config-private.json ...
freqtrade_COM1d | 2022-03-22 00:00:34,957 - freqtrade.loggers - INFO - Verbosity set to 0
freqtrade_COM1d | 2022-03-22 00:00:34,959 - freqtrade.configuration.configuration - INFO - Runmode set to live.
freqtrade_COM1d | 2022-03-22 00:00:34,959 - freqtrade.configuration.configuration - INFO - Parameter --db-url detected ...
freqtrade_COM1d | 2022-03-22 00:00:34,959 - freqtrade.configuration.configuration - INFO - Dry run is disabled
freqtrade_COM1d | 2022-03-22 00:00:34,960 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:////freqtrade/user_data/tradesv3.sqlite"
# Normal bot start logs etc...
  ```

**Comment by xmatthias** [comment]
it's an interesting problem for sure - but i'm not sure on how to handle this properly.

The exception occurs as ccxt fails to parse markets retrieved from the exchange.
As it works right afterwards again - it was probably a fluke at the exchange side.

While we could handle this differently - i'm not sure we should (or how) - as the bot would be stuck with empty pairlist - as there would be no markets until this problem is fixed if we simply catch and ignore the error.
We also can't/shouldn't really retry (at least not too often) - if it's a permanent problem (needs a fix someplace [freqtrade, ccxt or exchange]) - it could lead to an endless loop of "exception - exception again, ...".

I'll have to think about this a bit - please let me know if this reappears / if you notice it more frequently!

**Comment by Niqnil** [comment]
Ok I will update if this happens again. 

I am a newbie to coding but maybe you can set max number of retries with exponential backoff, while time elapsed is capped by base timeframe? Finally, close connection and open to fetch new candle. The problem might stop with the data from the new candle.

**Comment by xmatthias** [comment]
It's not a candle endpoint that's causing this, but a "generic" pair metadata endpoint (this is what complicates this problem).

As such, a new candle won't change anything - if any, then someone at ftx realizing that they made a mistake.

**Comment by xmatthias** [comment]
This was fixed in CCXT 8 days ago (https://github.com/ccxt/ccxt/pull/12549) - and should therefore be working correctly in the current develop version.
