### ISSUE TITLE
Freqtrade fails to install 

### ISSUE THREAD

**Issue by Aarron-shaw** [freqtrade/freqtrade#6587]
Python 3.8, stable version of freqtrade from git 

```$ ./setup.sh -i
/usr/local/bin/python3.8
using python3.8
----------------------------
Installing mandatory dependencies
----------------------------
Debian/Ubuntu detected. Setup for this system in-progress
[sudo] password for aarron:
Hit:1 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic InRelease
Hit:2 http://deb.debian.org/debian buster InRelease
Hit:3 http://deb.debian.org/debian buster-updates InRelease
Hit:4 http://security.debian.org buster/updates InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package libpython3.8-dev
E: Couldn't find any package by glob 'libpython3.8-dev'
E: Couldn't find any package by regex 'libpython3.8-dev'
E: Unable to locate package python3.8-venv
E: Couldn't find any package by glob 'python3.8-venv'
E: Couldn't find any package by regex 'python3.8-venv'
ta-lib already installed, skipping

----------------------------
Resetting branch and virtual env
----------------------------
Reset git branch? (This will remove all changes you made!) [y/N]? y
- Hard resetting of 'stable' branch.
HEAD is now at 4d8d30ea3 Version bump to 2022.2.2

----------------------------
Updating your virtual env
----------------------------
pip install in-progress. Please wait...
Collecting pip
  Using cached https://files.pythonhosted.org/packages/4d/16/0a14ca596f30316efd412a60bdfac02a7259bf8673d4d917dc60b9a21812/pip-22.0.4-py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 19.2.3
    Uninstalling pip-19.2.3:
      Successfully uninstalled pip-19.2.3
Successfully installed pip-22.0.4
Do you want to install dependencies for dev [y/N]? n
Do you want to install plotting dependencies (plotly) [y/N]? n
Do you want to install hyperopt dependencies [y/N]? n
Collecting numpy==1.22.2
  Using cached numpy-1.22.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
Collecting pandas==1.4.1
  Using cached pandas-1.4.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.7 MB)
Collecting pandas-ta==0.3.14b
  Using cached pandas_ta-0.3.14b.tar.gz (115 kB)
  Preparing metadata (setup.py) ... done
Collecting ccxt==1.73.70
  Using cached ccxt-1.73.70-py2.py3-none-any.whl (2.4 MB)
Collecting cryptography==36.0.1
  Using cached cryptography-36.0.1-cp36-abi3-manylinux_2_24_x86_64.whl (3.6 MB)
Collecting aiohttp==3.8.1
  Using cached aiohttp-3.8.1-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.3 MB)
Collecting SQLAlchemy==1.4.31
  Using cached SQLAlchemy-1.4.31-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.6 MB)
Collecting python-telegram-bot==13.11
  Using cached python_telegram_bot-13.11-py3-none-any.whl (497 kB)
Collecting arrow==1.2.2
  Using cached arrow-1.2.2-py3-none-any.whl (64 kB)
Collecting cachetools==4.2.2
  Using cached cachetools-4.2.2-py3-none-any.whl (11 kB)
Collecting requests==2.27.1
  Using cached requests-2.27.1-py2.py3-none-any.whl (63 kB)
Collecting urllib3==1.26.8
  Using cached urllib3-1.26.8-py2.py3-none-any.whl (138 kB)
Collecting jsonschema==4.4.0
  Using cached jsonschema-4.4.0-py3-none-any.whl (72 kB)
Collecting TA-Lib==0.4.24
  Using cached TA-Lib-0.4.24.tar.gz (269 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [94 lines of output]
      Processing numpy/random/_bounded_integers.pxd.in
      Processing numpy/random/_sfc64.pyx
      Traceback (most recent call last):
        File "/tmp/easy_install-920itd52/numpy-1.22.3/tools/cythonize.py", line 53, in process_pyx
          import Cython
      ModuleNotFoundError: No module named 'Cython'

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "/tmp/easy_install-920itd52/numpy-1.22.3/tools/cythonize.py", line 234, in <module>
          main()
        File "/tmp/easy_install-920itd52/numpy-1.22.3/tools/cythonize.py", line 230, in main
          find_process_files(root_dir)
        File "/tmp/easy_install-920itd52/numpy-1.22.3/tools/cythonize.py", line 221, in find_process_files
          process(root_dir, fromfile, tofile, function, hash_db)
        File "/tmp/easy_install-920itd52/numpy-1.22.3/tools/cythonize.py", line 187, in process
          processor_function(fromfile, tofile)
        File "/tmp/easy_install-920itd52/numpy-1.22.3/tools/cythonize.py", line 60, in process_pyx
          raise OSError(msg) from e
      OSError: Cython needs to be installed in Python as a module
      Running from numpy source directory.
      Traceback (most recent call last):
        File "/home/aarron/jobs/freqtrade/.env/lib/python3.8/site-packages/setuptools/sandbox.py", line 154, in save_modules
          yield saved
        File "/home/aarron/jobs/freqtrade/.env/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
          yield
        File "/home/aarron/jobs/freqtrade/.env/lib/python3.8/site-packages/setuptools/sandbox.py", line 250, in run_setup
          _execfile(setup_script, ns)
        File "/home/aarron/jobs/freqtrade/.env/lib/python3.8/site-packages/setuptools/sandbox.py", line 45, in _execfile
          exec(code, globals, locals)
        File "/tmp/easy_install-920itd52/numpy-1.22.3/setup.py", line 461, in <module>
        File "/tmp/easy_install-920itd52/numpy-1.22.3/setup.py", line 443, in setup_package
        File "/tmp/easy_install-920itd52/numpy-1.22.3/setup.py", line 248, in generate_cython
      RuntimeError: Running cythonize failed!

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-eyh58dln/ta-lib_2adc09666894490fadbc49dbb3427332/setup.py", line 146, in <module>
          setup(
        File "/home/aarron/jobs/freqtrade/.env/lib/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
          _install_setup_requires(attrs)
        File "/home/aarron/jobs/freqtrade/.env/lib/python3.8/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/home/aarron/jobs/freqtrade/.env/lib/python3.8/site-packages/setuptools/dist.py", line 716, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/home/aarron/jobs/freqtrade/.env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 780, in resolve
          dist = best[req.key] = env.best_match(
        File "/home/aarron/jobs/freqtrade/.env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1065, in best_match
          return self.obtain(req, installer)
        File "/home/aarron/jobs/freqtrade/.env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1077, in obtain
          return installer(requirement)
        File "/home/aarron/jobs/freqtrade/.env/lib/python3.8/site-packages/setuptools/dist.py", line 786, in fetch_build_egg
          return cmd.easy_install(req)
        File "/home/aarron/jobs/freqtrade/.env/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 679, in easy_install
          return self.install_item(spec, dist.location, tmpdir, deps)
        File "/home/aarron/jobs/freqtrade/.env/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 705, in install_item
          dists = self.install_eggs(spec, download, tmpdir)
        File "/home/aarron/jobs/freqtrade/.env/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
          return self.build_and_install(setup_script, setup_base)
        File "/home/aarron/jobs/freqtrade/.env/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
          self.run_setup(setup_script, setup_base, args)
        File "/home/aarron/jobs/freqtrade/.env/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1144, in run_setup
          run_setup(setup_script, args)
        File "/home/aarron/jobs/freqtrade/.env/lib/python3.8/site-packages/setuptools/sandbox.py", line 253, in run_setup
          raise
        File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
          self.gen.throw(type, value, traceback)
        File "/home/aarron/jobs/freqtrade/.env/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
          yield
        File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
          self.gen.throw(type, value, traceback)
        File "/home/aarron/jobs/freqtrade/.env/lib/python3.8/site-packages/setuptools/sandbox.py", line 166, in save_modules
          saved_exc.resume()
        File "/home/aarron/jobs/freqtrade/.env/lib/python3.8/site-packages/setuptools/sandbox.py", line 141, in resume
          six.reraise(type, exc, self._tb)
        File "/home/aarron/jobs/freqtrade/.env/lib/python3.8/site-packages/setuptools/_vendor/six.py", line 685, in reraise
          raise value.with_traceback(tb)
        File "/home/aarron/jobs/freqtrade/.env/lib/python3.8/site-packages/setuptools/sandbox.py", line 154, in save_modules
          yield saved
        File "/home/aarron/jobs/freqtrade/.env/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
          yield
        File "/home/aarron/jobs/freqtrade/.env/lib/python3.8/site-packages/setuptools/sandbox.py", line 250, in run_setup
          _execfile(setup_script, ns)
        File "/home/aarron/jobs/freqtrade/.env/lib/python3.8/site-packages/setuptools/sandbox.py", line 45, in _execfile
          exec(code, globals, locals)
        File "/tmp/easy_install-920itd52/numpy-1.22.3/setup.py", line 461, in <module>
        File "/tmp/easy_install-920itd52/numpy-1.22.3/setup.py", line 443, in setup_package
        File "/tmp/easy_install-920itd52/numpy-1.22.3/setup.py", line 248, in generate_cython
      RuntimeError: Running cythonize failed!
      Cythonizing sources
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Failed installing dependencies
```

**Comment by stash86** [comment]
For users from future who got similar issues, run these lines before install freqtrade. This is confirmed working on Debian 8 (buster), haven't test it yet on latest debian

```
sudo apt-get -y install python3-pip python3-venv libatlas-base-dev cmake git wget
sudo echo "[global]\nextra-index-url=https://www.piwheels.org/simple" > tee /etc/pip.conf
```

**Comment by xmatthias** [comment]
the 2nd line (piwheels) is definitely not necessary in this case (it's a x86 system based on the logs).

For the remainder - if you could confirm that this helps your installation, we could enhance the setup.sh script to attempt to install this if we detect debian.

**Comment by robcaulk** [comment]
> the 2nd line (piwheels) is definitely not necessary in this case (it's a x86 system based on the logs).
> 
> For the remainder - if you could confirm that this helps your installation, we could enhance the setup.sh script to attempt to install this if we detect debian.

I am having this issue while installing on a machine with Ubuntu 18.04. Using @stash86 recommended lines before install does not fix the issue.

**Comment by robcaulk** [comment]
Or it is a similar error (not identical).

I tried installing cython systemwide, I also tested entering the half made virtual environment after the failed install and `pip3 install cython`. Both were successful, but still the installation fails. 
```
./setup.sh -i
/usr/bin/python3.8
using python3.8
----------------------------
Installing mandatory dependencies
----------------------------
Debian/Ubuntu detected. Setup for this system in-progress
Get:1 file:/var/cuda-repo-ubuntu1804-11-4-local  InRelease
Ign:1 file:/var/cuda-repo-ubuntu1804-11-4-local  InRelease
Get:2 file:/var/cuda-repo-ubuntu1804-11-4-local  Release [564 B]
Get:2 file:/var/cuda-repo-ubuntu1804-11-4-local  Release [564 B]
Hit:3 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic InRelease       
Hit:4 http://dl.google.com/linux/chrome/deb stable InRelease                   
Hit:5 http://archive.canonical.com/ubuntu bionic InRelease                     
Hit:6 http://ppa.launchpad.net/teejee2008/ppa/ubuntu bionic InRelease          
Hit:7 http://packages.microsoft.com/repos/code stable InRelease                
Hit:9 http://archive.ubuntu.com/ubuntu bionic InRelease                        
Hit:10 https://linux.teamviewer.com/deb stable InRelease                       
Hit:11 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:12 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
Hit:13 http://archive.ubuntu.com/ubuntu bionic-security InRelease
Reading package lists... Done  
Reading package lists... Done
Building dependency tree       
Reading state information... Done
autoconf is already the newest version (2.69-11).
build-essential is already the newest version (12.4ubuntu1).
libtool is already the newest version (2.4.6-2).
make is already the newest version (4.1-9.1ubuntu1).
pkg-config is already the newest version (0.29.1-0ubuntu2).
curl is already the newest version (7.58.0-2ubuntu3.19).
gcc is already the newest version (4:7.4.0-1ubuntu2.3).
git is already the newest version (1:2.17.1-1ubuntu0.11).
wget is already the newest version (1.19.4-1ubuntu2.2).
libpython3.8-dev is already the newest version (3.8.0-3ubuntu1~18.04.2).
python3.8-venv is already the newest version (3.8.0-3ubuntu1~18.04.2).
The following packages were automatically installed and are no longer required:
  cuda-libraries-10-1 libnvidia-cfg1-440 libnvidia-cfg1-450 libnvidia-cfg1-460
  libnvidia-common-440 libnvidia-common-450 libnvidia-common-460
  libnvidia-compute-440 libnvidia-compute-450 libnvidia-compute-460
  libnvidia-decode-440 libnvidia-decode-450 libnvidia-decode-460
  libnvidia-encode-440 libnvidia-encode-450 libnvidia-encode-460
  libnvidia-fbc1-440 libnvidia-fbc1-450 libnvidia-fbc1-460 libnvidia-gl-440
  libnvidia-gl-450 libnvidia-gl-460 libnvidia-ifr1-440 libnvidia-ifr1-450
  libnvidia-ifr1-460 nsight-compute-2019.5.0 xserver-xorg-video-nvidia-440
  xserver-xorg-video-nvidia-450 xserver-xorg-video-nvidia-460
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 37 not upgraded.
ta-lib already installed, skipping

----------------------------
Resetting branch and virtual env
----------------------------
Reset ignored because you are not on 'stable' or 'develop'.
- Deleting your previous virtual env

----------------------------
Updating your virtual env
----------------------------
pip install in-progress. Please wait...
Collecting pip
  Using cached https://files.pythonhosted.org/packages/96/2f/caec18213f6a67852f6997fb0673ae08d2e93d1b81573edb93ba4ef06970/pip-22.1.2-py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 9.0.1
    Uninstalling pip-9.0.1:
      Successfully uninstalled pip-9.0.1
Successfully installed pip-22.1.2
Do you want to install dependencies for dev [y/N]? y
Do you want to install plotting dependencies (plotly) [y/N]? y
Do you want to install hyperopt dependencies [y/N]? y
Collecting numpy==1.23.0
  Using cached numpy-1.23.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.1 MB)
Collecting pandas==1.4.3
  Using cached pandas-1.4.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.7 MB)
Collecting pandas-ta==0.3.14b
  Using cached pandas_ta-0.3.14b.tar.gz (115 kB)
  Preparing metadata (setup.py) ... done
Collecting ccxt==1.89.14
  Using cached ccxt-1.89.14-py2.py3-none-any.whl (3.2 MB)
Collecting cryptography==37.0.2
  Using cached cryptography-37.0.2-cp36-abi3-manylinux_2_24_x86_64.whl (4.0 MB)
Collecting aiohttp==3.8.1
  Using cached aiohttp-3.8.1-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.3 MB)
Collecting SQLAlchemy==1.4.39
  Using cached SQLAlchemy-1.4.39-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.6 MB)
Collecting python-telegram-bot==13.12
  Using cached python_telegram_bot-13.12-py3-none-any.whl (511 kB)
Collecting arrow==1.2.2
  Using cached arrow-1.2.2-py3-none-any.whl (64 kB)
Collecting cachetools==4.2.2
  Using cached cachetools-4.2.2-py3-none-any.whl (11 kB)
Collecting requests==2.28.0
  Using cached requests-2.28.0-py3-none-any.whl (62 kB)
Collecting urllib3==1.26.9
  Using cached urllib3-1.26.9-py2.py3-none-any.whl (138 kB)
Collecting jsonschema==4.6.0
  Using cached jsonschema-4.6.0-py3-none-any.whl (80 kB)
Collecting TA-Lib==0.4.24
  Using cached TA-Lib-0.4.24.tar.gz (269 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [89 lines of output]
      Running from numpy source directory.
      /tmp/easy_install-8u8c47r7/numpy-1.23.0/setup.py:86: DeprecationWarning:
      
        `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
        of the deprecation of `distutils` itself. It will be removed for
        Python >= 3.12. For older Python versions it will remain present.
        It is recommended to use `setuptools < 60.0` for those Python versions.
        For more details, see:
          https://numpy.org/devdocs/reference/distutils_status_migration.html
      
      
        import numpy.distutils.command.sdist
      Traceback (most recent call last):
        File "/tmp/easy_install-8u8c47r7/numpy-1.23.0/setup.py", line 251, in generate_cython
      ModuleNotFoundError: No module named 'Cython'
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "/home/rcaulk/freqtrade/.env/lib/python3.8/site-packages/setuptools/sandbox.py", line 154, in save_modules
          yield saved
        File "/home/rcaulk/freqtrade/.env/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
          yield
        File "/home/rcaulk/freqtrade/.env/lib/python3.8/site-packages/setuptools/sandbox.py", line 250, in run_setup
          _execfile(setup_script, ns)
        File "/home/rcaulk/freqtrade/.env/lib/python3.8/site-packages/setuptools/sandbox.py", line 45, in _execfile
          exec(code, globals, locals)
        File "/tmp/easy_install-8u8c47r7/numpy-1.23.0/setup.py", line 493, in <module>
        File "/tmp/easy_install-8u8c47r7/numpy-1.23.0/setup.py", line 475, in setup_package
        File "/tmp/easy_install-8u8c47r7/numpy-1.23.0/setup.py", line 258, in generate_cython
      OSError: Cython needs to be installed in Python as a module
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-qloyqwhz/ta-lib_a1581d17d9954e1cb12251a8537ad8f0/setup.py", line 146, in <module>
          setup(
        File "/home/rcaulk/freqtrade/.env/lib/python3.8/site-packages/setuptools/__init__.py", line 128, in setup
          _install_setup_requires(attrs)
        File "/home/rcaulk/freqtrade/.env/lib/python3.8/site-packages/setuptools/__init__.py", line 123, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/home/rcaulk/freqtrade/.env/lib/python3.8/site-packages/setuptools/dist.py", line 510, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/home/rcaulk/freqtrade/.env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 772, in resolve
          dist = best[req.key] = env.best_match(
        File "/home/rcaulk/freqtrade/.env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1057, in best_match
          return self.obtain(req, installer)
        File "/home/rcaulk/freqtrade/.env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1069, in obtain
          return installer(requirement)
        File "/home/rcaulk/freqtrade/.env/lib/python3.8/site-packages/setuptools/dist.py", line 580, in fetch_build_egg
          return cmd.easy_install(req)
        File "/home/rcaulk/freqtrade/.env/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 698, in easy_install
          return self.install_item(spec, dist.location, tmpdir, deps)
        File "/home/rcaulk/freqtrade/.env/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 724, in install_item
          dists = self.install_eggs(spec, download, tmpdir)
        File "/home/rcaulk/freqtrade/.env/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 909, in install_eggs
          return self.build_and_install(setup_script, setup_base)
        File "/home/rcaulk/freqtrade/.env/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1177, in build_and_install
          self.run_setup(setup_script, setup_base, args)
        File "/home/rcaulk/freqtrade/.env/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1163, in run_setup
          run_setup(setup_script, args)
        File "/home/rcaulk/freqtrade/.env/lib/python3.8/site-packages/setuptools/sandbox.py", line 253, in run_setup
          raise
        File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
          self.gen.throw(type, value, traceback)
        File "/home/rcaulk/freqtrade/.env/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
          yield
        File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
          self.gen.throw(type, value, traceback)
        File "/home/rcaulk/freqtrade/.env/lib/python3.8/site-packages/setuptools/sandbox.py", line 166, in save_modules
          saved_exc.resume()
        File "/home/rcaulk/freqtrade/.env/lib/python3.8/site-packages/setuptools/sandbox.py", line 141, in resume
          six.reraise(type, exc, self._tb)
        File "/home/rcaulk/freqtrade/.env/lib/python3.8/site-packages/setuptools/_vendor/six.py", line 685, in reraise
          raise value.with_traceback(tb)
        File "/home/rcaulk/freqtrade/.env/lib/python3.8/site-packages/setuptools/sandbox.py", line 154, in save_modules
          yield saved
        File "/home/rcaulk/freqtrade/.env/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
          yield
        File "/home/rcaulk/freqtrade/.env/lib/python3.8/site-packages/setuptools/sandbox.py", line 250, in run_setup
          _execfile(setup_script, ns)
        File "/home/rcaulk/freqtrade/.env/lib/python3.8/site-packages/setuptools/sandbox.py", line 45, in _execfile
          exec(code, globals, locals)
        File "/tmp/easy_install-8u8c47r7/numpy-1.23.0/setup.py", line 493, in <module>
        File "/tmp/easy_install-8u8c47r7/numpy-1.23.0/setup.py", line 475, in setup_package
        File "/tmp/easy_install-8u8c47r7/numpy-1.23.0/setup.py", line 258, in generate_cython
      OSError: Cython needs to be installed in Python as a module
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Failed installing dependencies
```

**Comment by xmatthias** [comment]
it's at maximum a similar error - not identical.
i don't really see why on your system you'd need cython explicitly installed - it's not available on newer systems either - where installation works just fine without this.

**Comment by Patrizi5** [comment]
ftuser@cdfd228b2fac:/workspaces/freqtrade/freqtrade$ sudo apt-get update
[sudo] password for ftuser: 
Sorry, try again.
[sudo] password for ftuser:
