### ISSUE TITLE
FreqTrade Crash on OKX exchange.

### ISSUE THREAD

**Issue by tixsys** [freqtrade/freqtrade#6610]
## Describe your environment

  * Docker on Ubuntu. 2022.3
  * 

## Describe the problem:

2022-03-29 06:18:27,744 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=5, pair=NEAR/USDT, amount=0.75747740, open_rate=13.09000000, open_since=2022-03-28 20:25:25)
2022-03-29T06:18:27.752570998Z 2022-03-29 06:18:27,752 - freqtrade.freqtradebot - INFO - Fee for Trade Trade(id=5, pair=NEAR/USDT, amount=0.75747740, open_rate=13.09000000, open_since=2022-03-28 20:25:25) [sell]: 0.0060760291 USDT - rate: 0.0006
2022-03-29T06:18:27.753082748Z 2022-03-29 06:18:27,752 - freqtrade.persistence.models - INFO - Updating trade (id=5) ...
2022-03-29T06:18:27.753113521Z 2022-03-29 06:18:27,752 - freqtrade.persistence.models - INFO - LIMIT_SELL has been fulfilled for Trade(id=5, pair=NEAR/USDT, amount=0.75747740, open_rate=13.09000000, open_since=2022-03-28 20:25:25).
2022-03-29T06:18:27.753486226Z 2022-03-29 06:18:27,753 - freqtrade.persistence.models - INFO - Marking Trade(id=5, pair=NEAR/USDT, amount=0.75747740, open_rate=13.09000000, open_since=closed) as closed as the trade is fulfilled and found no open orders for it.
2022-03-29T06:18:28.034440122Z 2022-03-29 06:18:28,034 - freqtrade.wallets - INFO - Wallets synced.
2022-03-29T06:18:28.037655122Z 2022-03-29 06:18:28,037 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': sell_fill, 'trade_id': 5, 'exchange': 'Okx', 'pair': 'NEAR/USDT', 'gain': 'profit', 'limit': 13.369, 'order_type': '', 'amount': 0.7574773981331638, 'open_rate': 13.09, 'close_rate': 13.369, 'current_rate': None, 'profit_amount': 0.19931094, 'profit_ratio': 0.02008914, 'buy_tag': None, 'sell_reason': 'roi', 'open_date': datetime.datetime(2022, 3, 28, 20, 25, 25, 120820), 'close_date': datetime.datetime(2022, 3, 29, 6, 18, 27, 753332), 'stake_currency': 'USDT', 'fiat_currency': 'USD'}
2022-03-29T06:19:06.054010015Z 2022-03-29 06:19:06,053 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2022.3', state='RUNNING'
2022-03-29T06:20:22.074570205Z 2022-03-29 06:20:22,074 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2022.3', state='RUNNING'
2022-03-29T06:20:51.289505713Z 2022-03-29 06:20:51,289 - freqtrade.commands.trade_commands - ERROR - 'spot'
2022-03-29T06:20:51.294706237Z 2022-03-29 06:20:51,289 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
2022-03-29T06:20:51.294770547Z Traceback (most recent call last):
2022-03-29T06:20:51.294795224Z   File "/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
2022-03-29T06:20:51.294799914Z     worker.run()
2022-03-29T06:20:51.294803829Z   File "/freqtrade/freqtrade/worker.py", line 74, in run
2022-03-29T06:20:51.294807782Z     state = self._worker(old_state=state)
2022-03-29T06:20:51.294812291Z   File "/freqtrade/freqtrade/worker.py", line 114, in _worker
2022-03-29T06:20:51.294847303Z     self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
2022-03-29T06:20:51.294851053Z   File "/freqtrade/freqtrade/worker.py", line 139, in _throttle
2022-03-29T06:20:51.294854528Z     result = func(*args, **kwargs)
2022-03-29T06:20:51.294857836Z   File "/freqtrade/freqtrade/worker.py", line 152, in _process_running
2022-03-29T06:20:51.294861369Z     self.freqtrade.process()
2022-03-29T06:20:51.294864643Z   File "/freqtrade/freqtrade/freqtradebot.py", line 160, in process
2022-03-29T06:20:51.294868198Z     self.active_pair_whitelist = self._refresh_active_whitelist(trades)
2022-03-29T06:20:51.294881757Z   File "/freqtrade/freqtrade/freqtradebot.py", line 226, in _refresh_active_whitelist
2022-03-29T06:20:51.294885376Z     self.pairlists.refresh_pairlist()
2022-03-29T06:20:51.294888775Z   File "/freqtrade/freqtrade/plugins/pairlistmanager.py", line 84, in refresh_pairlist
2022-03-29T06:20:51.294892248Z     tickers = self._get_cached_tickers()
2022-03-29T06:20:51.294896162Z   File "/home/ftuser/.local/lib/python3.9/site-packages/cachetools/decorators.py", line 26, in wrapper
2022-03-29T06:20:51.294899882Z     v = func(*args, **kwargs)
2022-03-29T06:20:51.294903246Z   File "/freqtrade/freqtrade/plugins/pairlistmanager.py", line 77, in _get_cached_tickers
2022-03-29T06:20:51.294906657Z     return self._exchange.get_tickers()
2022-03-29T06:20:51.294909889Z   File "/freqtrade/freqtrade/exchange/common.py", line 125, in wrapper
2022-03-29T06:20:51.294913323Z     return f(*args, **kwargs)
2022-03-29T06:20:51.294916614Z   File "/freqtrade/freqtrade/exchange/exchange.py", line 1043, in get_tickers
2022-03-29T06:20:51.294920008Z     tickers = self._api.fetch_tickers(symbols)
2022-03-29T06:20:51.294923414Z   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/okx.py", line 1282, in fetch_tickers
2022-03-29T06:20:51.295058237Z     return self.fetch_tickers_by_type(type, symbols, query)
2022-03-29T06:20:51.295064083Z   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/okx.py", line 1278, in fetch_tickers_by_type
2022-03-29T06:20:51.295069431Z     return self.parse_tickers(tickers, symbols)
2022-03-29T06:20:51.295074123Z   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 1995, in parse_tickers
2022-03-29T06:20:51.295079339Z     result.append(self.extend(self.parse_ticker(values[i]), params))
2022-03-29T06:20:51.295085385Z   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/okx.py", line 1176, in parse_ticker
2022-03-29T06:20:51.295106981Z     quoteVolume = self.safe_string(ticker, 'volCcy24h') if market['spot'] else None
2022-03-29T06:20:51.295112143Z KeyError: 'spot'
2022-03-29T06:20:51.295832987Z 2022-03-29 06:20:51,295 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2022-03-29T06:20:51.296057995Z 2022-03-29 06:20:51,295 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}

*Explain the problem you have encountered*

was running for less than day at night.. crashed.

  ```
  // paste your log here
  ```

**Comment by xmatthias** [comment]
which exchange are you using - ftx (as suggested in the title) - or okx (as suggested by the logs?)

**Comment by tixsys** [comment]
sorry, it was OKX.

**Comment by xmatthias** [comment]
I've raised this upstream - as the error is really coming out of ccxt - so a fix will most likely have to happen there.

Fortunately, it's an edge-case that will only happen whenever okx lists a new pair - and load_markets was not reloaded since (we reload this every half hour).
So it's really a timing issue that will be quite rare to happen, so i think it'll be safe to continue using the version you are for now.

That said, it's also fixed in ccxt version 1.77.45, which was just released, and which we just bumped in develop.
therefore you can also use the latest develop version (build should land in about half an hour on dockerhub).
