### ISSUE TITLE
How to use ccxtpro watch methods on your pairlist within a strategy?

### ISSUE THREAD

**Issue by samgermain** [freqtrade/freqtrade#6626]
## Describe your environment

  * Operating system: MacOS Montery v 12.2.1 (21D62), Mac Mini 2018, 3.6 GHz Quad-Core Intel Core i3
  * Python Version: Python 3.9.5
  * CCXT version: ccxt==1.77.24, ccxtpro==1.0.44
  * Freqtrade Version: freqtrade develop-a13d4e551
  
-------------------------

## Your Question

I know that freqtrade uses the rest api methods from CCXT, I'm not trying to change any of that funcionality, but I am trying to create some threads within my strategy file using ccxtpro [as described in their manual](https://github.com/ccxt/ccxt/wiki/ccxt.pro.manual#prerequisites)

I am trying to to start my threads in the init method of my strategy, and the first problem that I am running into is that the dataprovider isn't available yet, but I imagine there are probably other problems with this approach

```
    def __init__(self, config: dict) -> None:
        super().__init__(config)

        self.trades: Dict[str, List] = {}
        self.loop = asyncio.new_event_loop()
        asyncio.set_event_loop(self.loop)
        self.exchange = getattr(ccxtpro, self.exchange_name)({
            'enableRateLimit': True,
        })
        self.loop.run_until_complete(self.exchange.load_markets())
        
        if not self.dp:
            raise OperationalException ('self.dp is None')
        pairs = self.dp.current_whitelist()
        for pair in pairs:
            asyncio.run(self.watch_order_book(pair))

    async def watch_order_book(self, symbol) -> None:
        while (True):
            try:
                self.trades[symbol] = await self.exchange.watchTrades(symbol)
            except Exception as e:
                print(f"watch_order_book {symbol} error: {e}")
```

------------------

## console log

```
...
2022-04-01 07:27:06,147 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy MY_STRATEGY_CLASS from '/path/user_data/strategies/dry_run_results_strategies/MY_STRATEGY_CLASS.py'...
2022-04-01 07:27:06,147 - freqtrade.strategy.hyper - INFO - Found no parameter file.
2022-04-01 07:27:06,148 - freqtrade.strategy.hyper - INFO - No params for buy found, using default values.
2022-04-01 07:27:06,148 - freqtrade.strategy.hyper - INFO - No params for sell found, using default values.
2022-04-01 07:27:06,148 - freqtrade.strategy.hyper - INFO - No params for protection found, using default values.
2022-04-01 07:27:06,872 - freqtrade.commands.trade_commands - ERROR - 'MY_STRATEGY_CLASS' object has no attribute 'dp'
2022-04-01 07:27:06,872 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/path/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/path/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/path/freqtrade/worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/path/freqtrade/freqtradebot.py", line 61, in __init__
    self.strategy: IStrategy = StrategyResolver.load_strategy(self.config)
  File "/path/freqtrade/resolvers/strategy_resolver.py", line 47, in load_strategy
    strategy: IStrategy = StrategyResolver._load_strategy(
  File "/path/freqtrade/resolvers/strategy_resolver.py", line 254, in _load_strategy
    strategy = StrategyResolver._load_object(
  File "/path/freqtrade/resolvers/iresolver.py", line 150, in _load_object
    return module(**kwargs)
  File "/path/user_data/strategies/dry_run_results_strategies/MY_STRATEGY_CLASS.py", line 98, in __init__
    if not self.dp:
AttributeError: 'MY_STRATEGY_CLASS' object has no attribute 'dp'
```

**Comment by xmatthias** [comment]
Using ccxt.pro with freqtrade is currently not supported.

While this may change in the future (most likely not before ccxt.pro is publicly available, but soon thereafter) - 

i'll also not provide support or guidance to hack such things into the strategy as you'd need to use async within the strategy - which we cannot guarantee to remain functional in the future.

It's not something we support now (nor document) - as such, please don't rely on freqtrade beaking this (due to some other changes) at any time without any advise.

Your approach (using `asyncio.run()`) is also blocking - therefore if you'd get to this point - your strategy would never finish loading and be stuck in this state.
