### ISSUE TITLE
Freqtrade not able to load library successfully installed via Docker

### ISSUE THREAD

**Issue by mllamazares** [freqtrade/freqtrade#6646]
## Describe your environment

  * Operating system: Linux 5.10.63-v7l+ armv7l GNU/Linux (inside Docker)
  * Python Version:  Python 3.9.9
  * CCXT version: ccxt==1.76.65
  * Freqtrade Version: 2022.3

## Describe the problem:

Freqtrade is not able to load the hmmlearn library, despite having been installed via Dockerfile. I get the following error code (full report in the last section):
```
2022-04-04 15:02:54,084 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair BTC/USDT: No module named 'hmmlearn',`
```

### Steps to reproduce:

I have a custom DockerFile to install additional dependencies:
```bash
FROM freqtradeorg/freqtrade:stable

USER root

RUN apt-get update
RUN apt-get install -y --no-install-recommends build-essential gcc wget git

# TA-Lib
RUN wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz && \
  tar -xvzf ta-lib-0.4.0-src.tar.gz && \
  cd ta-lib/ && \
  ./configure --prefix=/opt/venv && \
  make && \
  make install

RUN rm -R ta-lib ta-lib-0.4.0-src.tar.gz

USER ftuser

RUN pip install hmmlearn
#RUN pip install git+https://github.com/hmmlearn/hmmlearn
#RUN pip3 install hmmlearn
#RUN pip3 install git+https://github.com/hmmlearn/hmmlearn

RUN pip3 install TA-Lib 
```

This is my Docker Compose file:
```
---
version: '3'
services:
  freqtrade:
    #image: freqtradeorg/freqtrade:stable
    build:
      context: "./scripts"
      dockerfile: "./Dockerfile.custom"
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "../../user_data:/freqtrade/user_data"
    ports:
      - "0.0.0.0:8080:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/dorsia.log
      --db-url sqlite:////freqtrade/user_data/db/dorsia.sqlite
      --config /freqtrade/user_data/configs/dorsia.json
      --strategy Dorsia
```

Then, in my strategy file I have the following structure:

```python
import numpy as np  # noqa
import pandas as pd  # noqa
from pandas import DataFrame

from freqtrade.strategy import (BooleanParameter, CategoricalParameter, DecimalParameter,
                                IStrategy, IntParameter)

import freqtrade.vendor.qtpylib.indicators as qtpylib
from hmmlearn.hmm import GaussianHMM
import talib
import joblib
...
class Dorsia(IStrategy):
    model = None
    ...
    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame: 
        dataframe['rsi'] = talib.RSI(dataframe['close'].values, 10) / 100
        ... 
       # load the model
        if not self.model:
            self.model = joblib.load('/freqtrade/user_data/strategies/hmm.20220404.joblib')
        
        dataframe['signal'] = self.model.predict(dataframe[cols_features].values)

        return dataframe
...
```
  
### Observed Results:

  * What happened? Library hmmlearn not found.
  * What did you expect to happen? To find the specified library.

#### Docker compose build logs

```
PS C:\Users\UU\Documents\GitHub\tests2> docker-compose -f user_data/docker/80_dc-dorsia.yml build  
[+] Building 53.9s (14/14) FINISHED
 => [internal] load build definition from Dockerfile.custom                                                                                                                                                                     0.0s
 => => transferring dockerfile: 700B                                                                                                                                                                                            0.0s 
 => [internal] load .dockerignore                                                                                                                                                                                               0.0s 
 => => transferring context: 2B                                                                                                                                                                                                 0.0s 
 => [internal] load metadata for docker.io/freqtradeorg/freqtrade:stable                                                                                                                                                        1.4s 
 => [1/7] FROM docker.io/freqtradeorg/freqtrade:stable@sha256:c5943bd78a689e4e381ba3647f09f5072e3b81b012306650edb08bfd5b39f54b                                                                                                0.0s
 => CACHED [2/7] RUN apt-get update                                                                                                                                                                                           0.0s 
 => CACHED [3/7] RUN apt-get install -y --no-install-recommends build-essential gcc wget git                                                                                                                                  0.0s 
 => CACHED [4/7] RUN wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz &&   tar -xvzf ta-lib-0.4.0-src.tar.gz &&   cd ta-lib/ &&   ./configure --prefix=/opt/venv &&   make &&   make install            0.0s 
 => CACHED [5/7] RUN rm -R ta-lib ta-lib-0.4.0-src.tar.gz                                                                                                                                                                      0.0s 
 => [6/7] RUN pip install hmmlearn                                                                                                                                                                            2.9s 
 => [7/7] RUN pip3 install TA-Lib                                                                                                                                                                                              2.6s 
 => exporting to image  
```

#### Freqtrade logs

  ```
    __import__(module, level=0),
ModuleNotFoundError: No module named 'hmmlearn',
2022-04-04 15:02:54,084 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair BTC/USDT: No module named 'hmmlearn',
2022-04-04 15:02:54,097 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair BTC/USDT,
2022-04-04 15:03:01,338 - freqtrade.worker - INFO - Starting worker docker-ffd77fa4,
2022-04-04 15:03:01,339 - freqtrade.configuration.configuration - INFO - Using config: /freqtrade/user_data/configs/dorsia.json ...,
2022-04-04 15:03:01,346 - freqtrade.loggers - INFO - Verbosity set to 0,
2022-04-04 15:03:01,347 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.,
2022-04-04 15:03:01,348 - freqtrade.configuration.configuration - INFO - Parameter --db-url detected ...,
2022-04-04 15:03:01,349 - freqtrade.configuration.configuration - INFO - Dry run is enabled,
2022-04-04 15:03:01,349 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:////freqtrade/user_data/db/dorsia.sqlite",
2022-04-04 15:03:01,350 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 1 ...,
2022-04-04 15:03:01,455 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...,
2022-04-04 15:03:01,457 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/binance ...,
2022-04-04 15:03:01,458 - freqtrade.configuration.check_exchange - INFO - Checking exchange...,
2022-04-04 15:03:01,472 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.,
2022-04-04 15:03:01,473 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.,
2022-04-04 15:03:01,475 - freqtrade.freqtradebot - INFO - Starting freqtrade docker-ffd77fa4,
2022-04-04 15:03:01,511 - freqtrade.resolvers.iresolver - WARNING - Could not import /freqtrade/user_data/strategies/crazyvan_opt.py due to 'No module named 'lib.taCG'',
2022-04-04 15:03:01,522 - freqtrade.resolvers.iresolver - WARNING - Could not import /freqtrade/user_data/strategies/dorsia.py due to 'No module named 'hmmlearn'',
2022-04-04 15:03:01,577 - freqtrade.commands.trade_commands - ERROR - Impossible to load Strategy 'Dorsia'. This class does not exist or contains Python code errors.,
2022-04-04 15:03:01,578 - freqtrade.commands.trade_commands - ERROR - Fatal exception!,
Traceback (most recent call last):,
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading,
    worker = Worker(args),
  File "/freqtrade/freqtrade/worker.py", line 35, in __init__,
    self._init(False),
  File "/freqtrade/freqtrade/worker.py", line 52, in _init,
    self.freqtrade = FreqtradeBot(self._config),
  File "/freqtrade/freqtrade/freqtradebot.py", line 58, in __init__,
    self.strategy: IStrategy = StrategyResolver.load_strategy(self.config),
  File "/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 44, in load_strategy,
    strategy: IStrategy = StrategyResolver._load_strategy(,
  File "/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 206, in _load_strategy,
    raise OperationalException(,
freqtrade.exceptions.OperationalException: Impossible to load Strategy 'Dorsia'. This class does not exist or contains Python code errors.,
  ```

**Comment by xmatthias** [comment]
i think your pip installation should use `--user`.
That's how we install freqtrade - and it's also how the sample compose file defines it.

**Comment by mllamazares** [comment]
Thanks for pointing that out, @xmatthias. I forgot to mention that I've also tried to run it with the `--user` flag in the pip command without success. These were the steps I followed after modifying that line:
```bash
# stop
docker-compose -f user_data/docker/80_dc-dorsia.yml stop
# rebuild
docker-compose -f user_data/docker/80_dc-dorsia.yml build --no-cache
# restart
docker-compose -f user_data/docker/80_dc-dorsia.yml up -d
```

To verify that it has something to do with the previous actions of the Dockerfile, I tried to simplify it like this (as well as omitting the corresponding talib lines in the strategy class):

```bash
FROM freqtradeorg/freqtrade:latest
RUN pip3 install --user hmmlearn
```

Finally, I also tried replacing the joblib import to discard any version mismatch between the pickle model and the environment:
```python
self.model = GaussianHMM(n_components=3 , covariance_type="full", n_iter=10000).fit(dataframe[cols_features].values)
```

However, I end up getting the same error again, somehow it cannot locate the **hmmlearn** library:
```
2022-04-04 19:28:54,362 - freqtrade.resolvers.iresolver - WARNING - Could not import /freqtrade/user_data/strategies/dorsia.py due to 'No module named 'hmmlearn''
```

**Comment by xmatthias** [comment]
Your best bet will be to start the container with `docker-compose run --rm --entrypoint bash` - and start a python shell, trying to import the library yourself.

That way, you can "interactively" attempt to debug this (i don't think this is related to freqtrade itself - but to hmmlearn somehow).
maybe it's missing a dependency or it's installation is faulty or whatnot - which causes it to fail importing.

**Comment by mllamazares** [comment]
I've followed these steps and somehow it is working now:

1. Replace the strategy parameter in the docker-compose file with **SampleStrategy**.
2. Recreate the container.
3. Start a python shell under **ftuser** and check that I can import the library:

```python
ftuser@51943f861ffe:/freqtrade$ python
Python 3.9.9 (main, Dec 21 2021, 10:14:07) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from hmmlearn import hmm
>>> test = hmm.GaussianHMM()
>>> 
```
4. Replace the strategy parameter in the docker-compose file with the original one (Dorsia).
5. Recreate the container.
6. Check the logs and suddenly everything worked fine - no import errors. 😕

**Comment by xmatthias** [comment]
i'm .. not quite certain HOW this would've fixed it - but glad it's working now 👍
