### ISSUE TITLE
ValueError: '' is not a valid TradingMode

### ISSUE THREAD

**Issue by applerobloxgames** [freqtrade/freqtrade#6663]
* Operating system: Raspberry Pi OS Bullseye 64 Bit
  * Python Version: 3.9.2 
  * CCXT version: ccxt==1.77.98 
  * Freqtrade Version: develop-299dd84cf

--------------------------------------------------

hey, how to fix this?
```
(.env) pi@raspberrypi:~/freqtrade $ freqtrade trade --config config.json --strategy SampleStrategy
2022-04-07 08:50:26,815 - freqtrade.worker - INFO - Starting worker develop-299dd84cf
2022-04-07 08:50:26,815 - freqtrade.configuration.configuration - INFO - Using config: config.json ...
2022-04-07 08:50:26,816 - freqtrade.loggers - INFO - Verbosity set to 0
2022-04-07 08:50:26,817 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
2022-04-07 08:50:26,817 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2022-04-07 08:50:26,817 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:///tradesv3.dryrun.sqlite"
2022-04-07 08:50:26,818 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 3 ...
2022-04-07 08:50:26,818 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/pi/freqtrade/user_data ...
2022-04-07 08:50:26,819 - freqtrade.configuration.configuration - INFO - Using data directory: /home/pi/freqtrade/user_data/data/coinbase ...
2022-04-07 08:50:26,823 - freqtrade.commands.trade_commands - ERROR - '' is not a valid TradingMode
2022-04-07 08:50:26,823 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/pi/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/home/pi/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/home/pi/freqtrade/freqtrade/worker.py", line 49, in _init
    self._config = Configuration(self._args, None).get_config()
  File "/home/pi/freqtrade/freqtrade/configuration/configuration.py", line 42, in get_config
    self.config = self.load_config()
  File "/home/pi/freqtrade/freqtrade/configuration/configuration.py", line 113, in load_config
    self._process_data_options(config)
  File "/home/pi/freqtrade/freqtrade/configuration/configuration.py", line 437, in _process_data_options
    config['trading_mode'] = TradingMode(config.get('trading_mode', 'spot'))
  File "/usr/lib/python3.9/enum.py", line 360, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.9/enum.py", line 677, in __new__
    raise ve_exc
ValueError: '' is not a valid TradingMode
(.env) pi@raspberrypi:~/freqtrade $ 
```

**Comment by stash86** [comment]
https://www.freqtrade.io/en/latest/configuration/#configuration-parameters

**Comment by xmatthias** [comment]
You can simply configure it as "spot" for the moment.

I'll update this part to better handle this case - as it's a slight bug in the config generation.
