### ISSUE TITLE
Previously working Bots stop due to Error : could not load markets ( "binance" )

### ISSUE THREAD

**Issue by toruksky** [freqtrade/freqtrade#6686]
## Describe your environment

  * Operating system: Ubuntu 18.04____
  * Python Version: _3.9.7____ (`python -V`)
  * CCXT version: 1.76.65_____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2022.3___ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
Our bots which have been working well stop suddenly today, the Error is like below 

 freqtrade.commands.trade_commands - ERROR - Could not load markets, therefore cannot start. Please investigate the above error for more details.
2022-04-13 20:40:57,828 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/toruk/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/home/toruk/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/home/toruk/freqtrade/freqtrade/worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/home/toruk/freqtrade/freqtrade/freqtradebot.py", line 63, in __init__
    self.exchange = ExchangeResolver.load_exchange(self.config['exchange']['name'], self.config)
  File "/home/toruk/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 32, in load_exchange
    exchange = ExchangeResolver._load_exchange(exchange_name,
  File "/home/toruk/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 54, in _load_exchange
    exchange = ex_class(**kwargs)
  File "/home/toruk/freqtrade/freqtrade/exchange/exchange.py", line 157, in __init__
    self.validate_stakecurrency(config['stake_currency'])
  File "/home/toruk/freqtrade/freqtrade/exchange/exchange.py", line 376, in validate_stakecurrency
    raise OperationalException(
freqtrade.exceptions.OperationalException: Could not load markets, therefore cannot start. Please investigate the above error for more details.

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by thomazsantos** [comment]
I receive that error too in docker image.

**Comment by xmatthias** [comment]
There will most likely be more in the exception than this.
As this is a shortened / incomplete exception, it's currently unclear what could cause this.

Please therefore provide the full exception that you have in the log. while it may be multiple lines - it'll contain the information necessary to deal with this appropriately.

**Comment by thomazsantos** [comment]
I think the problem is one error to connect to the api, not is one issue in the project.
```
freqtrade.exchange.exchange - ERROR - Unable to initialize markets.
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f8b874ee190>, **'Connection to api.binance.com timed out. (connect timeout=10)')**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.binance.com', port=443): **Max retries exceeded with url: /api/v3/exchangeInfo (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f8b874ee190>, 'Connection to api.binance.com timed out. (connect timeout=10)'))**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 640, in fetch
    response = self.session.request(
  File "/home/ftuser/.local/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ftuser/.local/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/home/ftuser/.local/lib/python3.9/site-packages/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.binance.com', port=443): **Max retries exceeded with url: /api/v3/exchangeInfo (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f8b874ee190>, 'Connection to api.binance.com timed out. (connect timeout=10)'))**

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/exchange.py", line 345, in _load_markets
    self._markets = self._api.load_markets()
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 1529, in load_markets
    markets = self.fetch_markets(params)
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/binance.py", line 1378, in fetch_markets
    response = getattr(self, method)(query)
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 508, in inner
    return entry(_self, **inner_kwargs)
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/binance.py", line 4988, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 555, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 670, in fetch
    raise RequestTimeout(details) from e
ccxt.base.errors.RequestTimeout: binance GET https://api.binance.com/api/v3/exchangeInfo
2022-04-13 13:33:54,739 - freqtrade.commands.trade_commands - ERROR - Could not load markets, therefore cannot start. Please investigate the above error for more details.
2022-04-13 13:33:54,745 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/freqtrade/freqtrade/worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/freqtrade/freqtrade/freqtradebot.py", line 63, in __init__
    self.exchange = ExchangeResolver.load_exchange(self.config['exchange']['name'], self.config)
  File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 32, in load_exchange
    exchange = ExchangeResolver._load_exchange(exchange_name,
  File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 54, in _load_exchange
    exchange = ex_class(**kwargs)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 157, in __init__
    self.validate_stakecurrency(config['stake_currency'])
  File "/freqtrade/freqtrade/exchange/exchange.py", line 376, in validate_stakecurrency
    raise OperationalException(
freqtrade.exceptions.OperationalException: Could not load markets, therefore cannot start. Please investigate the above error for more details.
```
I think you can close that issue!

**Comment by xmatthias** [comment]
> socket.timeout: timed out

This suggests a network level problem - either on your side - or on the exchange.
as you're not the only one - i'd suspect an exchange problem.
That said - it's working on a test from my location now - so i'm not quite sure if it was temporary and resolved ... ?

**Comment by toruksky** [comment]
> > socket.timeout: timed out
> 
> This suggests a network level problem - either on your side - or on the exchange. as you're not the only one - i'd suspect an exchange problem. That said - it's working on a test from my location now - so i'm not quite sure if it was temporary and resolved ... ?

I tried again from my location, still have the same error. But I found one major difference(log below) vs log of [thomazsantos]
my URL is url: https://api.binance.com/sapi/v1.... but thomazsantos's log shows URL:https://api.binance.com/api/v3...
Will this cause the error? 

I've also updated again to the latest version. and both "pytest --longrun tests/exchange/test_ccxt_compat.py" and "freqtrade download-data " work well.   

-------------------------------------------------------------------------------------------------------------------
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error:  for url: https://api.binance.com/sapi/v1/capital/config/getall?timestamp=1649901561262&recvWindow=5000&signature=6d8d6972403860214a0b3860f60c20f3a8948c62d2a8c7255d0d9dfa2e25a804

**Comment by xmatthias** [comment]
@toruksky Without a full exception - it'll be impossible to determine.

The URL you show now will not cause the exception you pointed out at the very top, but will have a different exception (and a different stacktrace).
As this is an authenticated endpoint, it could also have something to do with the  API keys - however without the exception, that's impossible to determine.

**Comment by toruksky** [comment]
thx, @xmatthias how/where could I get full exception? is the log shown in the console enough?

**Comment by xmatthias** [comment]
> is the log shown in the console enough?

Yes it is - but please try to include not just the exception, also some lines before that (basically "regular" lines) to make sure we got it all.

It's easy to filter through non-essential stuff - but difficult to guess missing stuff ;)

**Comment by toruksky** [comment]
@xmatthias I just give it a last try and find the API issue resolved, thanks for all help and response.
