### ISSUE TITLE
setup.sh -i failed

### ISSUE THREAD

**Issue by Starlexxx** [freqtrade/freqtrade#6688]
```
./setup.sh -i
/usr/local/bin/python3.8
using python3.8
----------------------------
Installing mandatory dependencies
----------------------------
Debian/Ubuntu detected. Setup for this system in-progress
./setup.sh: line 149: sudo: command not found
./setup.sh: line 150: sudo: command not found
ta-lib already installed, skipping

----------------------------
Resetting branch and virtual env
----------------------------
Reset git branch? (This will remove all changes you made!) [y/N]? n
- Deleting your previous virtual env

----------------------------
Updating your virtual env
----------------------------
pip install in-progress. Please wait...
Collecting pip
  Using cached https://files.pythonhosted.org/packages/4d/16/0a14ca596f30316efd412a60bdfac02a7259bf8673d4d917dc60b9a21812/pip-22.0.4-py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 19.2.3
    Uninstalling pip-19.2.3:
      Successfully uninstalled pip-19.2.3
Successfully installed pip-22.0.4
Do you want to install dependencies for dev [y/N]? y
Do you want to install plotting dependencies (plotly) [y/N]? y
Do you want to install hyperopt dependencies [y/N]? y
Collecting numpy==1.22.3
  Using cached numpy-1.22.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
Collecting pandas==1.4.1
  Using cached pandas-1.4.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.7 MB)
Collecting pandas-ta==0.3.14b
  Using cached pandas_ta-0.3.14b.tar.gz (115 kB)
  Preparing metadata (setup.py) ... done
Collecting ccxt==1.76.65
  Using cached ccxt-1.76.65-py2.py3-none-any.whl (2.5 MB)
Collecting cryptography==36.0.2
  Using cached cryptography-36.0.2-cp36-abi3-manylinux_2_24_x86_64.whl (3.6 MB)
Collecting aiohttp==3.8.1
  Using cached aiohttp-3.8.1-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.3 MB)
Collecting SQLAlchemy==1.4.32
  Using cached SQLAlchemy-1.4.32-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.6 MB)
Collecting python-telegram-bot==13.11
  Using cached python_telegram_bot-13.11-py3-none-any.whl (497 kB)
Collecting arrow==1.2.2
  Using cached arrow-1.2.2-py3-none-any.whl (64 kB)
Collecting cachetools==4.2.2
  Using cached cachetools-4.2.2-py3-none-any.whl (11 kB)
Collecting requests==2.27.1
  Using cached requests-2.27.1-py2.py3-none-any.whl (63 kB)
Collecting urllib3==1.26.9
  Using cached urllib3-1.26.9-py2.py3-none-any.whl (138 kB)
Collecting jsonschema==4.4.0
  Using cached jsonschema-4.4.0-py3-none-any.whl (72 kB)
Collecting TA-Lib==0.4.24
  Using cached TA-Lib-0.4.24.tar.gz (269 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [94 lines of output]
      Processing numpy/random/_bounded_integers.pxd.in
      Processing numpy/random/_pcg64.pyx
      Traceback (most recent call last):
        File "/tmp/easy_install-9_flrem8/numpy-1.22.3/tools/cythonize.py", line 53, in process_pyx
          import Cython
      ModuleNotFoundError: No module named 'Cython'

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "/tmp/easy_install-9_flrem8/numpy-1.22.3/tools/cythonize.py", line 234, in <module>
          main()
        File "/tmp/easy_install-9_flrem8/numpy-1.22.3/tools/cythonize.py", line 230, in main
          find_process_files(root_dir)
        File "/tmp/easy_install-9_flrem8/numpy-1.22.3/tools/cythonize.py", line 221, in find_process_files
          process(root_dir, fromfile, tofile, function, hash_db)
        File "/tmp/easy_install-9_flrem8/numpy-1.22.3/tools/cythonize.py", line 187, in process
          processor_function(fromfile, tofile)
        File "/tmp/easy_install-9_flrem8/numpy-1.22.3/tools/cythonize.py", line 60, in process_pyx
          raise OSError(msg) from e
      OSError: Cython needs to be installed in Python as a module
      Running from numpy source directory.
      Traceback (most recent call last):
        File "/home/user/freqtrade/.env/lib/python3.8/site-packages/setuptools/sandbox.py", line 154, in save_modules
          yield saved
        File "/home/user/freqtrade/.env/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
          yield
        File "/home/user/freqtrade/.env/lib/python3.8/site-packages/setuptools/sandbox.py", line 250, in run_setup
          _execfile(setup_script, ns)
        File "/home/user/freqtrade/.env/lib/python3.8/site-packages/setuptools/sandbox.py", line 45, in _execfile
          exec(code, globals, locals)
        File "/tmp/easy_install-9_flrem8/numpy-1.22.3/setup.py", line 461, in <module>
        File "/tmp/easy_install-9_flrem8/numpy-1.22.3/setup.py", line 443, in setup_package
        File "/tmp/easy_install-9_flrem8/numpy-1.22.3/setup.py", line 248, in generate_cython
      RuntimeError: Running cythonize failed!

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-c0nrowah/ta-lib_467d234b570b4b2ea4097d34b7e3f0df/setup.py", line 146, in <module>
          setup(
        File "/home/user/freqtrade/.env/lib/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
          _install_setup_requires(attrs)
        File "/home/user/freqtrade/.env/lib/python3.8/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/home/user/freqtrade/.env/lib/python3.8/site-packages/setuptools/dist.py", line 716, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/home/user/freqtrade/.env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 780, in resolve
          dist = best[req.key] = env.best_match(
        File "/home/user/freqtrade/.env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1065, in best_match
          return self.obtain(req, installer)
        File "/home/user/freqtrade/.env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1077, in obtain
          return installer(requirement)
        File "/home/user/freqtrade/.env/lib/python3.8/site-packages/setuptools/dist.py", line 786, in fetch_build_egg
          return cmd.easy_install(req)
        File "/home/user/freqtrade/.env/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 679, in easy_install
          return self.install_item(spec, dist.location, tmpdir, deps)
        File "/home/user/freqtrade/.env/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 705, in install_item
          dists = self.install_eggs(spec, download, tmpdir)
        File "/home/user/freqtrade/.env/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
          return self.build_and_install(setup_script, setup_base)
        File "/home/user/freqtrade/.env/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
          self.run_setup(setup_script, setup_base, args)
        File "/home/user/freqtrade/.env/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1144, in run_setup
          run_setup(setup_script, args)
        File "/home/user/freqtrade/.env/lib/python3.8/site-packages/setuptools/sandbox.py", line 253, in run_setup
          raise
        File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
          self.gen.throw(type, value, traceback)
        File "/home/user/freqtrade/.env/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
          yield
        File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
          self.gen.throw(type, value, traceback)
        File "/home/user/freqtrade/.env/lib/python3.8/site-packages/setuptools/sandbox.py", line 166, in save_modules
          saved_exc.resume()
        File "/home/user/freqtrade/.env/lib/python3.8/site-packages/setuptools/sandbox.py", line 141, in resume
          six.reraise(type, exc, self._tb)
        File "/home/user/freqtrade/.env/lib/python3.8/site-packages/setuptools/_vendor/six.py", line 685, in reraise
          raise value.with_traceback(tb)
        File "/home/user/freqtrade/.env/lib/python3.8/site-packages/setuptools/sandbox.py", line 154, in save_modules
          yield saved
        File "/home/user/freqtrade/.env/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
          yield
        File "/home/user/freqtrade/.env/lib/python3.8/site-packages/setuptools/sandbox.py", line 250, in run_setup
          _execfile(setup_script, ns)
        File "/home/user/freqtrade/.env/lib/python3.8/site-packages/setuptools/sandbox.py", line 45, in _execfile
          exec(code, globals, locals)
        File "/tmp/easy_install-9_flrem8/numpy-1.22.3/setup.py", line 461, in <module>
        File "/tmp/easy_install-9_flrem8/numpy-1.22.3/setup.py", line 443, in setup_package
        File "/tmp/easy_install-9_flrem8/numpy-1.22.3/setup.py", line 248, in generate_cython
      RuntimeError: Running cythonize failed!
      Cythonizing sources
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Failed installing dependencies
```

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions which are usually required to assist - not answering these will require unnecessary back and forth.

---

your system setup seems to be incomplete, as `sudo` is missing - which subsequently fails to install some necessary dependencies.

as we're missing details about your setup (mainly operating system, ...) - it's unclear what causes this (most likely it's an incomplete OS installation, which is missing some crucial tools.

**Comment by Starlexxx** [comment]
> Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment. We're asking some very basic questions which are usually required to assist - not answering these will require unnecessary back and forth.
> 
> your system setup seems to be incomplete, as `sudo` is missing - which subsequently fails to install some necessary dependencies.
> 
> as we're missing details about your setup (mainly operating system, ...) - it's unclear what causes this (most likely it's an incomplete OS installation, which is missing some crucial tools.

OS: debian 10, everything is ok about sudo, i've installed pip3 (22.0.4), python3.8 and all libs (ta, numpy, pandas). I also tried to do manual installation, but it also failed with message:
```
import Cython
ModuleNotFoundError: No module named 'Cython'
```


I think, that it's the problem.

**Comment by Starlexxx** [comment]
I've fixed sudo issue, but still have same output 
```./setup.sh -i
/usr/local/bin/python3.8
using python3.8
----------------------------
Installing mandatory dependencies
----------------------------
Debian/Ubuntu detected. Setup for this system in-progress
Hit:1 http://ftp.ru.debian.org/debian buster InRelease
Hit:2 http://security.debian.org/debian-security buster/updates InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package libpython3.8-dev
E: Couldn't find any package by glob 'libpython3.8-dev'
E: Couldn't find any package by regex 'libpython3.8-dev'
E: Unable to locate package python3.8-venv
E: Couldn't find any package by glob 'python3.8-venv'
E: Couldn't find any package by regex 'python3.8-venv'
ta-lib already installed, skipping

----------------------------
Resetting branch and virtual env
----------------------------
Reset git branch? (This will remove all changes you made!) [y/N]? n

----------------------------
Updating your virtual env
----------------------------
pip install in-progress. Please wait...
Collecting pip
  Using cached https://files.pythonhosted.org/packages/4d/16/0a14ca596f30316efd412a60bdfac02a7259bf8673d4d917dc60b9a21812/pip-22.0.4-py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 19.2.3
    Uninstalling pip-19.2.3:
      Successfully uninstalled pip-19.2.3
Successfully installed pip-22.0.4
Do you want to install dependencies for dev [y/N]? y
Do you want to install plotting dependencies (plotly) [y/N]? y
Do you want to install hyperopt dependencies [y/N]? y
Collecting numpy==1.22.3
  Using cached numpy-1.22.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
Collecting pandas==1.4.1
  Using cached pandas-1.4.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.7 MB)
Collecting pandas-ta==0.3.14b
  Using cached pandas_ta-0.3.14b.tar.gz (115 kB)
  Preparing metadata (setup.py) ... done
Collecting ccxt==1.76.65
  Using cached ccxt-1.76.65-py2.py3-none-any.whl (2.5 MB)
Collecting cryptography==36.0.2
  Using cached cryptography-36.0.2-cp36-abi3-manylinux_2_24_x86_64.whl (3.6 MB)
Collecting aiohttp==3.8.1
  Using cached aiohttp-3.8.1-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.3 MB)
Collecting SQLAlchemy==1.4.32
  Using cached SQLAlchemy-1.4.32-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.6 MB)
Collecting python-telegram-bot==13.11
  Using cached python_telegram_bot-13.11-py3-none-any.whl (497 kB)
Collecting arrow==1.2.2
  Using cached arrow-1.2.2-py3-none-any.whl (64 kB)
Collecting cachetools==4.2.2
  Using cached cachetools-4.2.2-py3-none-any.whl (11 kB)
Collecting requests==2.27.1
  Using cached requests-2.27.1-py2.py3-none-any.whl (63 kB)
Collecting urllib3==1.26.9
  Using cached urllib3-1.26.9-py2.py3-none-any.whl (138 kB)
Collecting jsonschema==4.4.0
  Using cached jsonschema-4.4.0-py3-none-any.whl (72 kB)
Collecting TA-Lib==0.4.24
  Using cached TA-Lib-0.4.24.tar.gz (269 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [94 lines of output]
      Processing numpy/random/_bounded_integers.pxd.in
      Processing numpy/random/_pcg64.pyx
      Traceback (most recent call last):
        File "/tmp/easy_install-egat3kbw/numpy-1.22.3/tools/cythonize.py", line 53, in process_pyx
          import Cython
      ModuleNotFoundError: No module named 'Cython'

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "/tmp/easy_install-egat3kbw/numpy-1.22.3/tools/cythonize.py", line 234, in <module>
          main()
        File "/tmp/easy_install-egat3kbw/numpy-1.22.3/tools/cythonize.py", line 230, in main
          find_process_files(root_dir)
        File "/tmp/easy_install-egat3kbw/numpy-1.22.3/tools/cythonize.py", line 221, in find_process_files
          process(root_dir, fromfile, tofile, function, hash_db)
        File "/tmp/easy_install-egat3kbw/numpy-1.22.3/tools/cythonize.py", line 187, in process
          processor_function(fromfile, tofile)
        File "/tmp/easy_install-egat3kbw/numpy-1.22.3/tools/cythonize.py", line 60, in process_pyx
          raise OSError(msg) from e
      OSError: Cython needs to be installed in Python as a module
      Running from numpy source directory.
      Traceback (most recent call last):
        File "/home/user/freqtrade/.env/lib/python3.8/site-packages/setuptools/sandbox.py", line 154, in save_modules
          yield saved
        File "/home/user/freqtrade/.env/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
          yield
        File "/home/user/freqtrade/.env/lib/python3.8/site-packages/setuptools/sandbox.py", line 250, in run_setup
          _execfile(setup_script, ns)
        File "/home/user/freqtrade/.env/lib/python3.8/site-packages/setuptools/sandbox.py", line 45, in _execfile
          exec(code, globals, locals)
        File "/tmp/easy_install-egat3kbw/numpy-1.22.3/setup.py", line 461, in <module>
        File "/tmp/easy_install-egat3kbw/numpy-1.22.3/setup.py", line 443, in setup_package
        File "/tmp/easy_install-egat3kbw/numpy-1.22.3/setup.py", line 248, in generate_cython
      RuntimeError: Running cythonize failed!

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-lpnhvhsf/ta-lib_124e3669e2134325895b4fa40a2b8170/setup.py", line 146, in <module>
          setup(
        File "/home/user/freqtrade/.env/lib/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
          _install_setup_requires(attrs)
        File "/home/user/freqtrade/.env/lib/python3.8/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/home/user/freqtrade/.env/lib/python3.8/site-packages/setuptools/dist.py", line 716, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/home/user/freqtrade/.env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 780, in resolve
          dist = best[req.key] = env.best_match(
        File "/home/user/freqtrade/.env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1065, in best_match
          return self.obtain(req, installer)
        File "/home/user/freqtrade/.env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1077, in obtain
          return installer(requirement)
        File "/home/user/freqtrade/.env/lib/python3.8/site-packages/setuptools/dist.py", line 786, in fetch_build_egg
          return cmd.easy_install(req)
        File "/home/user/freqtrade/.env/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 679, in easy_install
          return self.install_item(spec, dist.location, tmpdir, deps)
        File "/home/user/freqtrade/.env/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 705, in install_item
          dists = self.install_eggs(spec, download, tmpdir)
        File "/home/user/freqtrade/.env/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
          return self.build_and_install(setup_script, setup_base)
        File "/home/user/freqtrade/.env/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
          self.run_setup(setup_script, setup_base, args)
        File "/home/user/freqtrade/.env/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1144, in run_setup
          run_setup(setup_script, args)
        File "/home/user/freqtrade/.env/lib/python3.8/site-packages/setuptools/sandbox.py", line 253, in run_setup
          raise
        File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
          self.gen.throw(type, value, traceback)
        File "/home/user/freqtrade/.env/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
          yield
        File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
          self.gen.throw(type, value, traceback)
        File "/home/user/freqtrade/.env/lib/python3.8/site-packages/setuptools/sandbox.py", line 166, in save_modules
          saved_exc.resume()
        File "/home/user/freqtrade/.env/lib/python3.8/site-packages/setuptools/sandbox.py", line 141, in resume
          six.reraise(type, exc, self._tb)
        File "/home/user/freqtrade/.env/lib/python3.8/site-packages/setuptools/_vendor/six.py", line 685, in reraise
          raise value.with_traceback(tb)
        File "/home/user/freqtrade/.env/lib/python3.8/site-packages/setuptools/sandbox.py", line 154, in save_modules
          yield saved
        File "/home/user/freqtrade/.env/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
          yield
        File "/home/user/freqtrade/.env/lib/python3.8/site-packages/setuptools/sandbox.py", line 250, in run_setup
          _execfile(setup_script, ns)
        File "/home/user/freqtrade/.env/lib/python3.8/site-packages/setuptools/sandbox.py", line 45, in _execfile
          exec(code, globals, locals)
        File "/tmp/easy_install-egat3kbw/numpy-1.22.3/setup.py", line 461, in <module>
        File "/tmp/easy_install-egat3kbw/numpy-1.22.3/setup.py", line 443, in setup_package
        File "/tmp/easy_install-egat3kbw/numpy-1.22.3/setup.py", line 248, in generate_cython
      RuntimeError: Running cythonize failed!
      Cythonizing sources
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Failed installing dependencies

**Comment by Starlexxx** [comment]
Actually, we can close issue. I've installed it by:
```
pip install freqtrade
```

**Comment by xmatthias** [comment]
you'll need to walk the errors from top to bottom ...

```
E: Unable to locate package libpython3.8-dev
E: Couldn't find any package by glob 'libpython3.8-dev'
E: Couldn't find any package by regex 'libpython3.8-dev'
E: Unable to locate package python3.8-venv
E: Couldn't find any package by glob 'python3.8-venv'
E: Couldn't find any package by regex 'python3.8-venv'
``` 

still points to a problem - so i'm not entirely sure how it's even getting this far.
