### ISSUE TITLE
binance. get order crashes bot

### ISSUE THREAD

**Issue by berlinguyinca** [freqtrade/freqtrade#669]
Not able to get an order crashes the bot. Should be handled as exception and bot should continue working. Not crashing to system

2018-05-13 17:13:57,369 - freqtrade.exchange - WARNING - retrying get_order() still for 0 times
2018-05-13 17:13:57,850 - freqtrade.exchange - WARNING - get_order() returned exception: "Could not get order. Message: binance {"code":-2013,"msg":"Order does not exist."}"
2018-05-13 17:13:57,850 - freqtrade.exchange - WARNING - Giving up retrying: get_order()
2018-05-13 17:13:57,850 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "C:\Users\wohlg\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\base\exchange.py", line 356, in fetch
    response.raise_for_status()
  File "C:\Users\wohlg\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order?timestamp=1526256835708&recvWindow=5000&symbol=ONTBTC&orderId=22119513&signature=45b0b7456b40faaa989617a5fa825648d29c74dbe1730fbadf33cad8ede82bd7

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\wohlg\pycharmprojects\freqtrade\freqtrade\exchange\__init__.py", line 349, in get_order
    return _API.fetch_order(order_id, pair)
  File "C:\Users\wohlg\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\binance.py", line 676, in fetch_order
    response = self.privateGetOrder(self.extend(request, params))

**Comment by xmatthias** [comment]
i think this error should be handled / translated by ccxt into a `ccxt.*` error ...
(and i think it was - `ccxt\base\exchange.py", line 356, in fetch
response.raise_for_status()` points to a location in the ccxt code where it reraises base-error, which is converted to our `OperationalError` - at least now.

did you see this error again?

**Comment by berlinguyinca** [comment]
haven't seen it in a long long time. I honestly think we could close it

**Comment by xmatthias** [comment]
closing then :+1: 
if it reappears please reopen, thanks
