### ISSUE TITLE
Failed to get leverage amount

### ISSUE THREAD

**Issue by ketank1000** [freqtrade/freqtrade#6730]
In document it is clearly mentions that Freqtrade does not support trading with margin / leverage, and cannot open short positions.

But we have trading_mode, leverage_num etc etc which show we can trade in margins / leverage. 
Are we supporting it now ?

I make my own config file and trying to go live, but hitting following issue.

```
futures_long        | Traceback (most recent call last):
futures_long        |   File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
futures_long        |     worker = Worker(args)
futures_long        |   File "/freqtrade/freqtrade/worker.py", line 35, in __init__
futures_long        |     self._init(False)
futures_long        |   File "/freqtrade/freqtrade/worker.py", line 52, in _init
futures_long        |     self.freqtrade = FreqtradeBot(self._config)
futures_long        |   File "/freqtrade/freqtrade/freqtradebot.py", line 67, in __init__
futures_long        |     self.exchange = ExchangeResolver.load_exchange(self.config['exchange']['name'], self.config)
futures_long        |   File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 32, in load_exchange
futures_long        |     exchange = ExchangeResolver._load_exchange(exchange_name,
futures_long        |   File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 54, in _load_exchange
futures_long        |     exchange = ex_class(**kwargs)
futures_long        |   File "/freqtrade/freqtrade/exchange/exchange.py", line 196, in __init__
futures_long        |     self.fill_leverage_tiers()
futures_long        |   File "/freqtrade/freqtrade/exchange/exchange.py", line 2136, in fill_leverage_tiers
futures_long        |     leverage_tiers = self.load_leverage_tiers()
futures_long        |   File "/freqtrade/freqtrade/exchange/common.py", line 154, in wrapper
futures_long        |     return wrapper(*args, **kwargs)
futures_long        |   File "/freqtrade/freqtrade/exchange/common.py", line 154, in wrapper
futures_long        |     return wrapper(*args, **kwargs)
futures_long        |   File "/freqtrade/freqtrade/exchange/common.py", line 154, in wrapper
futures_long        |     return wrapper(*args, **kwargs)
futures_long        |   [Previous line repeated 1 more time]
futures_long        |   File "/freqtrade/freqtrade/exchange/common.py", line 157, in wrapper
futures_long        |     raise ex
futures_long        |   File "/freqtrade/freqtrade/exchange/common.py", line 142, in wrapper
futures_long        |     return f(*args, **kwargs)
futures_long        |   File "/freqtrade/freqtrade/exchange/binance.py", line 202, in load_leverage_tiers
futures_long        |     raise TemporaryError(f'Could not fetch leverage amounts due to'
futures_long        | freqtrade.exceptions.TemporaryError: Could not fetch leverage amounts due toAuthenticationError. Message: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action, request ip: XX.XX.XX.XX"}
```

Spot trading works perfectly fine with this api key. but it fails for leverage one.

If we support, am i missing some conf or permissions ?

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

The develop version does support futures trading - and the stable version will be supporting this in the future.

For binance in particular, you'll need to make sure your api key is enabled for futures trading. You can find this in the  API key window.

You should also make sure to use the matching api documentation (for develop, the version ["latest"](https://www.freqtrade.io/en/latest/)).

**Comment by ketank1000** [comment]
Thanks ! and sorry for not following template, will keep that in mind next time.
