### ISSUE TITLE
Mexc crash upon coin removal

### ISSUE THREAD

**Issue by tixsys** [freqtrade/freqtrade#6733]
2022-04-25 06:21:52,682 - freqtrade.exchange.common - WARNING - fetch_l2_order_book() returned exception: "Could not get order book due to RequestTimeout. Message: mexc GET https://www.mexc.com/open/api/v2/market/depth?symbol=ETC_USDT&depth=1". Retrying still for 4 times.
2022-04-25T06:21:59.015694361Z 

2022-04-25 03:30:33,672 - freqtrade.exchange.common - WARNING - _async_get_candle_history() returned exception: "Could not fetch historical candle (OHLCV) data for pair GXC/USDT due to ExchangeError. Message: mexc {"msg":"invalid symbol","code":30014}". Giving up.
2022-04-25T03:30:33.863754342Z 

2022-04-25 03:34:52,546 - freqtrade.exchange.common - WARNING - _async_get_candle_history() returned exception: "Could not fetch historical candle (OHLCV) data for pair GXC/USDT due to ExchangeError. Message: mexc {"msg":"invalid symbol","code":30014}". Giving up.
2022-04-25T03:34:52.547670074Z 2022-04-25 03:34:52,547 - freqtrade.exchange.exchange - WARNING - Async code raised an exception: TemporaryError('Could not fetch historical candle (OHLCV) data for pair GXC/USDT due to ExchangeError. Message: mexc {"msg":"invalid symbol","code":30014}')
2022-04-25T03:34:57.208091350Z 2022-04-25 03:34:57,207 - freqtrade.exchange.common - WARNING - _async_get_candle_history() returned exception: "Could not fetch historical candle (OHLCV) data for pair GXC/USDT due to ExchangeError. Message: mexc {"msg":"invalid symbol","code":30014}". Retrying still for 4 times.
2022-04-25T03:34:57.642000431Z 2022-04-25 03:34:57,641 - freqtrade.exchange.common - WARNING - _async_get_candle_history() returned exception: "Could not fetch historical candle (OHLCV) data for pair GXC/USDT due to ExchangeError. Message: mexc {"msg":"invalid symbol","code":30014}". Retrying still for 3 times.
2022-04-25T03:34:58.074826389Z 2022-04-25 03:34:58,074 - freqtrade.exchange.common - WARNING - _async_get_candle_history() returned exception: "Could not fetch historical candle (OHLCV) data for pair GXC/USDT due to ExchangeError. Message: mexc {"msg":"invalid symbol","code":30014}". Retrying still for 2 times.
2022-04-25T03:34:58.516575966Z 2022-04-25 03:34:58,516 - freqtrade.exchange.common - WARNING - _async_get_candle_history() returned exception: "Could not fetch historical candle (OHLCV) data for pair GXC/USDT due to ExchangeError. Message: mexc {"msg":"invalid symbol","code":30014}". Retrying still for 1 times.
2022-04-25T03:34:58.959121680Z 2022-04-25 03:34:58,958 - freqtrade.exchange.common - WARNING - _async_get_candle_history() returned exception: "Could not fetch historical candle (OHLCV) data for pair GXC/USDT due to ExchangeError. Message: mexc {"msg":"invalid symbol","code":30014}". Giving up.
2022-04-25T03:34:58.959395422Z 2022-04-25 03:34:58,959 - freqtrade.exchange.exchange - WARNING - Async code raised an exception: TemporaryError('Could not fetch historical candle (OHLCV) data for pair GXC/USDT due to ExchangeError. Message: mexc {"msg":"invalid symbol","code":30014}')
2022-04-25T03:35:10.040635841Z 2022-04-25 03:35:10,040 - freqtrade.exchange.common - WARNING - _async_get_candle_history() returned exception: "Could not fetch historical candle (OHLCV) data for pair GXC/USDT due to ExchangeError. Message: mexc {"msg":"invalid symbol","code":30014}". Retrying still for 4 times.
2022-04-25T03:35:13.245640801Z 2022-04-25 03:35:13,245 - freqtrade.exchange.common - WARNING - _async_get_candle_history() returned exception: "Could not fetch historical candle (OHLCV) data for pair GXC/USDT due to ExchangeError. Message: mexc {"msg":"invalid symbol","code":30014}". Retrying still for 3 times.
2022-04-25T03:35:13.695630105Z 2022-04-25 03:35:13,695 - freqtrade.exchange.common - WARNING - _async_get_candle_history() returned exception: "Could not fetch historical candle (OHLCV) data for pair GXC/USDT due to ExchangeError. Message: mexc {"msg":"invalid symbol","code":30014}". Retrying still for 2 times.
2022-04-25T03:35:14.147136801Z 2022-04-25 03:35:14,146 - freqtrade.exchange.common - WARNING - _async_get_candle_history() returned exception: "Could not fetch historical candle (OHLCV) data for pair GXC/USDT due to ExchangeError. Message: mexc {"msg":"invalid symbol","code":30014}". Retrying still for 1 times.
2022-04-25T03:35:14.596443965Z 2022-04-25 03:35:14,592 - freqtrade.exchange.common - WARNING - _async_get_candle_history() returned exception: "Could not fetch historical candle (OHLCV) data for pair GXC/USDT due to ExchangeError. Message: mexc {"msg":"invalid symbol","code":30014}". Giving up.
2022-04-25T03:35:21.657318545Z 2022-04-25 03:35:21,655 - freqtrade.exchange.common - WARNING - _async_get_candle_history() returned exception: "Could not fetch historical candle (OHLCV) data for pair STEPN/USDT due to RequestTimeout. Message: mexc GET https://www.mexc.com/open/api/v2/market/kline?symbol=STEPN_USDT&interval=5m&limit=500". Retrying still for 4 times.
2022-04-25T03:35:22.453301899Z 2022-04-25 03:35:22,453 - freqtrade.data.converter - INFO - Missing data fillup for REVV/USDT: before: 499 - after: 541 - 8.42%
2022-04-25T03:35:22.696249672Z 2022-04-25 03:35:22,695 - freqtrade.data.converter - INFO - Missing data fillup for ARTIC/USDT: before: 499 - after: 534 - 7.01%
2022-04-25T03:35:22.916485719Z 2022-04-25 03:35:22,916 - freqtrade.exchange.exchange - WARNING - Async code raised an exception: TemporaryError('Could not fetch historical candle (OHLCV) data for pair GXC/USDT due to ExchangeError. Message: mexc {"msg":"invalid symbol","code":30014}')
2022-04-25T03:35:27.012323014Z 2022-04-25 03:35:27,011 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2022.3', state='RUNNING'
2022-04-25T03:35:28.022204482Z 2022-04-25 03:35:28,021 - freqtrade.commands.trade_commands - ERROR - 'last'
2022-04-25T03:35:28.024650762Z 2022-04-25 03:35:28,022 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
2022-04-25T03:35:28.024666713Z Traceback (most recent call last):
2022-04-25T03:35:28.024670009Z   File "/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
2022-04-25T03:35:28.024672654Z     worker.run()
2022-04-25T03:35:28.024675048Z   File "/freqtrade/freqtrade/worker.py", line 74, in run
2022-04-25T03:35:28.024677423Z     state = self._worker(old_state=state)
2022-04-25T03:35:28.024692512Z   File "/freqtrade/freqtrade/worker.py", line 114, in _worker
2022-04-25T03:35:28.024695458Z     self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
2022-04-25T03:35:28.024697852Z   File "/freqtrade/freqtrade/worker.py", line 139, in _throttle
2022-04-25T03:35:28.024700217Z     result = func(*args, **kwargs)
2022-04-25T03:35:28.024702681Z   File "/freqtrade/freqtrade/worker.py", line 152, in _process_running
2022-04-25T03:35:28.024705046Z     self.freqtrade.process()
2022-04-25T03:35:28.024707260Z   File "/freqtrade/freqtrade/freqtradebot.py", line 160, in process
2022-04-25T03:35:28.024709765Z     self.active_pair_whitelist = self._refresh_active_whitelist(trades)
2022-04-25T03:35:28.024712780Z   File "/freqtrade/freqtrade/freqtradebot.py", line 226, in _refresh_active_whitelist
2022-04-25T03:35:28.024733670Z     self.pairlists.refresh_pairlist()
2022-04-25T03:35:28.024736055Z   File "/freqtrade/freqtrade/plugins/pairlistmanager.py", line 92, in refresh_pairlist
2022-04-25T03:35:28.024738610Z     pairlist = pairlist_handler.filter_pairlist(pairlist, tickers)
2022-04-25T03:35:28.024740914Z   File "/freqtrade/freqtrade/plugins/pairlist/IPairList.py", line 112, in filter_pairlist
2022-04-25T03:35:28.024743329Z     if not self._validate_pair(p, tickers[p] if p in tickers else {}):
2022-04-25T03:35:28.024745663Z   File "/freqtrade/freqtrade/plugins/pairlist/PrecisionFilter.py", line 54, in _validate_pair
2022-04-25T03:35:28.024748078Z     stop_price = ticker['last'] * self._stoploss
2022-04-25T03:35:28.024750372Z KeyError: 'last'
2022-04-25T03:35:28.024796971Z 2022-04-25 03:35:28,024 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit

ver 2022.3. docker

**Comment by xmatthias** [comment]
mexc is not a supported exchange, and i've never heard from anyone trying to use it so far - so you're probably the first one to attempt to use it.

If you're unfamiliar with some level of development (reading exceptions, posting proper issue reports) - please stick to one of the supported exchanges.



Sounds like you got an invalid pair in your pairlist in `GXC/USDT`. This most likely comes from an existing database - otherwise you shouldn't even get this far.

**Comment by tixsys** [comment]
db is isolated and was clean from first run. mb it was some "deleted" coin from exchange?

**Comment by xmatthias** [comment]
it's a possibility - best research the news channels of your exchange.

the coin is nowhere to be found in the API ... normally, exchanges set the coin as "inactive" - so if that would be the case, they'd just remove it violently.
That's not something that ... sparks confidence in this exchange...

**Comment by tixsys** [comment]
![Screenshot_20220427-231341_Telegram.jpg](https://user-images.githubusercontent.com/2570361/165623538-10b1234b-b645-41e6-b438-6b33908a72f9.jpg)

It was running fine previous 4 days and much more before. So this still looks like some ghost data from exchange api then..

**Comment by tixsys** [comment]
And here is the answer

https://support.mexc.com/hc/en-001/articles/5775374845337-MEXC-Will-Support-the-GXChain-GXC-Mainnet-Token-Swap-and-Redenomination-Plan-to-REI-Network-REI-

So it crashed on coin removal.

**Comment by xmatthias** [comment]
That's surely possible.

Coin removal is always problematic as the exchanges usually don't provide any info in advance via the API that coins are removed.
The way mexc removes pairs (they disappear completely on removal) makes it even more critical, and quite difficult to handle.

I'd therefore advise to stay away from this exchange if possible.
Also, look out for their announcements, and blacklist coins due to removal a few days before the actual removal. Being in a position of a removed coin can (and most likely will) result in 100% loss on any exchange.
