### ISSUE TITLE
Freqtrade not working, not making buy

### ISSUE THREAD

**Issue by mkajnar** [freqtrade/freqtrade#6741]
Invalid HTTP request received.
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 129, in handle_events
    event = self.conn.next_event()
  File "/home/ftuser/.local/lib/python3.9/site-packages/h11/_connection.py", line 485, in next_event
    exc._reraise_as_remote_protocol_error()
  File "/home/ftuser/.local/lib/python3.9/site-packages/h11/_util.py", line 77, in _reraise_as_remote_protocol_error
    raise self
  File "/home/ftuser/.local/lib/python3.9/site-packages/h11/_connection.py", line 467, in next_event
    event = self._extract_next_receive_event()
  File "/home/ftuser/.local/lib/python3.9/site-packages/h11/_connection.py", line 409, in _extract_next_receive_event
    event = self._reader(self._receive_buffer)
  File "/home/ftuser/.local/lib/python3.9/site-packages/h11/_readers.py", line 225, in expect_nothing
    raise LocalProtocolError("Got data when expecting EOF")
h11._util.RemoteProtocolError: Got data when expecting EOF

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

This is a warning from the webserver, and has nothing to do with bot operations itself (and will have no impact on the fact if the bot is buying or not).

It's usually a sign that something is randomly connecting to your API (which suggests the port is exposed towards the internet, which you shouldn't do).


If freqtrade is buying solely depends on the strategy and configuration.
