### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by moinonin** [freqtrade/freqtrade#6746]
## Describe your environment

  * Operating system: Linux Mint Una
  * Python Version: 3.10.2
  * CCXT version:1.80.61
  * Freqtrade Version: develop-d1a61f9c6
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*
Hyperopt crashes amidst optimization
### Steps to reproduce:

  1. Run hyperopt with timerange using binance futures data
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
  Optimization stops after crash no results output
  * What did you expect to happen?
  Expected at least some hyperopt results when optimizing spaces stoploss only
### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
 [Epoch 45 of 500 (  9%)] |███████████████/                                                                                                                                                         | [ETA:   2:18:02, Elapsed Time: 0:13:39]
2022-04-29 16:23:00,739 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/defi/Desktop/portfolio/projects/python/crypto/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/home/defi/Desktop/portfolio/projects/python/crypto/freqtrade/freqtrade/commands/optimize_commands.py", line 107, in start_hyperopt
    hyperopt.start()
  File "/home/defi/Desktop/portfolio/projects/python/crypto/freqtrade/freqtrade/optimize/hyperopt.py", line 541, in start
    val['is_random'] = is_random[j]
IndexError: list index out of range
  ```

**Comment by xmatthias** [comment]
The problem here clearly comes from #6563.

However - i can't really reproduce this (it's not happening in my case), and the lists are always of identical length for me.

What's the exact command you're running? 
and what's parallelism that you're applying?

In theory - you should be able to reproduce this reliably by using the same exact command, with the random state from the logs.
Hoping that's the case - please add `print(f"{len(asked)=}, {len(is_random)=}")` into the hyperopt file L523 (right after `asked, is_random = self.get_asked_points(n_points=current_jobs)`).

**Comment by moinonin** [comment]
Yes, @xmatthias it seems to come from that issue. 
I was running a quick optimization of the stoploss as per the documentation:
`freqtrade hyperopt --hyperopt-loss SortinoHyperOptLoss --spaces stoploss --strategy MyWorkingStrategy --config config.json -e 100`
@italodamato how did you address this? Is it something to do with the epochs?

**Comment by xmatthias** [comment]
also that method works fine for me (obviously your strategy will be different to mine).

how many parallel jobs did your hyperopt use?

**Comment by moinonin** [comment]
My number of parallel jobs was set to -1

**Comment by xmatthias** [comment]
yes (i can see that from the command) - but what parallelism was used? (that'll be in the log output).

**Comment by moinonin** [comment]
I may be misunderstanding you. The logs look like this :)
```
2022-04-30 08:32:31,981 - freqtrade.configuration.load_config - INFO - Using config: user_data/configshort_usdt.json ...
2022-04-30 08:32:31,982 - freqtrade.loggers - INFO - Verbosity set to 0
2022-04-30 08:32:31,982 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 60 ...
2022-04-30 08:32:31,982 - freqtrade.configuration.configuration - INFO - Parameter --timerange detected: 20210510-20220117 ...
2022-04-30 08:32:32,016 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2022-04-30 08:32:32,016 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/binance ...
2022-04-30 08:32:32,016 - freqtrade.configuration.configuration - INFO - Parameter --epochs detected ... Will run Hyperopt with for 100 epochs ...
2022-04-30 08:32:32,016 - freqtrade.configuration.configuration - INFO - Parameter -s/--spaces detected: ['stoploss']
2022-04-30 08:32:32,016 - freqtrade.configuration.configuration - INFO - Parameter -j/--job-workers detected: -1
2022-04-30 08:32:32,016 - freqtrade.configuration.configuration - INFO - Parameter --min-trades detected: 1
2022-04-30 08:32:32,016 - freqtrade.configuration.configuration - INFO - Using Hyperopt loss class name: SortinoHyperOptLoss
2022-04-30 08:32:32,016 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2022-04-30 08:32:32,027 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2022-04-30 08:32:32,027 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2022-04-30 08:32:32,027 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2022-04-30 08:32:32,030 - freqtrade.commands.optimize_commands - INFO - Starting freqtrade in Hyperopt mode
2022-04-30 08:32:32,031 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2022-04-30 08:32:32,031 - freqtrade.exchange.exchange - INFO - Using CCXT 1.80.61
2022-04-30 08:32:32,031 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'future'}, 'enableRateLimit': True}
2022-04-30 08:32:32,039 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'future'}, 'enableRateLimit': True}
2022-04-30 08:32:32,047 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2022-04-30 08:32:33,723 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2022-04-30 08:32:34,036 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy Strategy262short from '/freqtrade/user_data/strategies/Strategy262short.py'...
2022-04-30 08:32:34,036 - freqtrade.strategy.hyper - INFO - Found no parameter file.
2022-04-30 08:32:34,036 - freqtrade.strategy.hyper - INFO - No params for buy found, using default values.
2022-04-30 08:32:34,036 - freqtrade.strategy.hyper - INFO - No params for sell found, using default values.
2022-04-30 08:32:34,036 - freqtrade.strategy.hyper - INFO - No params for protection found, using default values.
2022-04-30 08:32:34,036 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 1h.
2022-04-30 08:32:34,036 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'trailing_stop' with value in config file: False.
2022-04-30 08:32:34,036 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'order_types' with value in config file: {'entry': 'limit', 'exit': 'limit', 'emergency_exit': 'market', 'force_exit': 'market', 'force_entry': 'market', 'stoploss': 'market', 'stoploss_on_exchange': True, 'stoploss_on_exchange_interval': 60, 'stoploss_on_exchange_limit_ratio': 0.99}.
2022-04-30 08:32:34,036 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'order_time_in_force' with value in config file: {'entry': 'gtc', 'exit': 'gtc'}.
2022-04-30 08:32:34,036 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2022-04-30 08:32:34,036 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 42.5.
2022-04-30 08:32:34,037 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'entry': 10, 'exit': 30, 'exit_timeout_count': 0, 'unit': 'minutes'}.
2022-04-30 08:32:34,037 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'use_exit_signal' with value in config file: True.
2022-04-30 08:32:34,037 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'exit_profit_only' with value in config file: False.
2022-04-30 08:32:34,037 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ignore_roi_if_entry_signal' with value in config file: False.
2022-04-30 08:32:34,037 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'disable_dataframe_checks' with value in config file: False.
2022-04-30 08:32:34,037 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'position_adjustment_enable' with value in config file: True.
2022-04-30 08:32:34,037 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 0.6617999999999999}
2022-04-30 08:32:34,037 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 1h
2022-04-30 08:32:34,037 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.05515
2022-04-30 08:32:34,037 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2022-04-30 08:32:34,037 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2022-04-30 08:32:34,037 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2022-04-30 08:32:34,037 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: True
2022-04-30 08:32:34,037 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
2022-04-30 08:32:34,037 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'entry': 'limit', 'exit': 'limit', 'emergency_exit': 'market', 'force_exit': 'market', 'force_entry': 'market', 'stoploss': 'market', 'stoploss_on_exchange': True, 'stoploss_on_exchange_interval': 60, 'stoploss_on_exchange_limit_ratio': 0.99}
2022-04-30 08:32:34,037 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'entry': 'gtc', 'exit': 'gtc'}
2022-04-30 08:32:34,037 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2022-04-30 08:32:34,037 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 42.5
2022-04-30 08:32:34,037 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2022-04-30 08:32:34,037 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 100
2022-04-30 08:32:34,037 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'entry': 10, 'exit': 30, 'exit_timeout_count': 0, 'unit': 'minutes'}
2022-04-30 08:32:34,037 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_exit_signal: True
2022-04-30 08:32:34,037 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_only: False
2022-04-30 08:32:34,037 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_entry_signal: False
2022-04-30 08:32:34,037 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_offset: 0.0
2022-04-30 08:32:34,037 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2022-04-30 08:32:34,037 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2022-04-30 08:32:34,037 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: True
2022-04-30 08:32:34,037 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1
2022-04-30 08:32:34,037 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2022-04-30 08:32:34,046 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from '/freqtrade/freqtrade/plugins/pairlist/StaticPairList.py'...
2022-04-30 08:32:34,047 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist PriceFilter from '/freqtrade/freqtrade/plugins/pairlist/PriceFilter.py'...
2022-04-30 08:32:34,054 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist ShuffleFilter from '/freqtrade/freqtrade/plugins/pairlist/ShuffleFilter.py'...
2022-04-30 08:32:34,054 - ShuffleFilter - INFO - Backtesting mode detected, applying seed value: 42
2022-04-30 08:32:34,620 - freqtrade.resolvers.iresolver - INFO - Using resolved hyperoptloss SortinoHyperOptLoss from '/freqtrade/freqtrade/optimize/hyperopt_loss_sortino.py'...
2022-04-30 08:32:34,620 - freqtrade.optimize.hyperopt - INFO - Removing `/freqtrade/user_data/hyperopt_results/hyperopt_tickerdata.pkl`.
2022-04-30 08:32:34,621 - freqtrade.optimize.hyperopt - INFO - Using optimizer random state: 7943
2022-04-30 08:32:34,622 - freqtrade.data.history.history_utils - INFO - Using indicator startup period: 100 ...
2022-04-30 08:32:34,637 - freqtrade.data.history.idatahandler - WARNING - IOTX/USDT, futures, 1h, data starts at 2021-08-12 03:00:00
2022-04-30 08:32:35,327 - freqtrade.data.history.idatahandler - WARNING - DYDX/USDT, futures, 1h, data starts at 2021-09-10 03:00:00
2022-04-30 08:32:35,837 - freqtrade.data.history.idatahandler - WARNING - MASK/USDT, futures, 1h, data starts at 2021-08-27 03:00:00
2022-04-30 08:32:35,937 - freqtrade.data.history.idatahandler - WARNING - LPT/USDT, futures, 1h, data starts at 2021-11-11 03:00:00
2022-04-30 08:32:36,312 - freqtrade.data.history.idatahandler - WARNING - ICP/USDT, futures, 1h, data starts at 2021-05-11 03:00:00
2022-04-30 08:32:37,023 - freqtrade.optimize.backtesting - INFO - Loading data from 2021-05-05 20:00:00 up to 2022-01-17 00:00:00 (256 days).
2022-04-30 08:32:37,029 - freqtrade.data.history.idatahandler - WARNING - IOTX/USDT, funding_rate, 8h, data starts at 2021-08-11 16:00:00
2022-04-30 08:32:37,272 - freqtrade.data.history.idatahandler - WARNING - DYDX/USDT, funding_rate, 8h, data starts at 2021-09-09 16:00:00
2022-04-30 08:32:37,450 - freqtrade.data.history.idatahandler - WARNING - MASK/USDT, funding_rate, 8h, data starts at 2021-08-26 08:00:00
2022-04-30 08:32:37,505 - freqtrade.data.history.idatahandler - WARNING - LPT/USDT, funding_rate, 8h, data starts at 2021-11-11 08:00:00
2022-04-30 08:32:37,518 - freqtrade.data.history.idatahandler - WARNING - OMG/USDT, funding_rate, 8h, data starts at 2021-05-11 00:00:00
2022-04-30 08:32:37,632 - freqtrade.data.history.idatahandler - WARNING - ICP/USDT, funding_rate, 8h, data starts at 2021-05-11 08:00:00
2022-04-30 08:32:37,884 - freqtrade.data.history.idatahandler - WARNING - IOTX/USDT, mark, 8h, data starts at 2021-08-12 00:00:00
2022-04-30 08:32:38,132 - freqtrade.data.history.idatahandler - WARNING - DYDX/USDT, mark, 8h, data starts at 2021-09-10 00:00:00
2022-04-30 08:32:38,316 - freqtrade.data.history.idatahandler - WARNING - MASK/USDT, mark, 8h, data starts at 2021-08-27 00:00:00
2022-04-30 08:32:38,367 - freqtrade.data.history.idatahandler - WARNING - LPT/USDT, mark, 8h, data starts at 2021-11-11 00:00:00
2022-04-30 08:32:38,497 - freqtrade.data.history.idatahandler - WARNING - ICP/USDT, mark, 8h, data starts at 2021-05-11 00:00:00
2022-04-30 08:32:38,841 - freqtrade.optimize.hyperopt - INFO - Dataload complete. Calculating indicators
2022-04-30 08:32:38,852 - freqtrade.data.history.idatahandler - WARNING - IOTX/USDT, futures, 1h, data starts at 2021-08-12 03:00:00
2022-04-30 08:32:41,059 - freqtrade.data.history.idatahandler - WARNING - DYDX/USDT, futures, 1h, data starts at 2021-09-10 03:00:00
2022-04-30 08:32:42,700 - freqtrade.data.history.idatahandler - WARNING - MASK/USDT, futures, 1h, data starts at 2021-08-27 03:00:00
2022-04-30 08:32:43,146 - freqtrade.data.history.idatahandler - WARNING - LPT/USDT, futures, 1h, data starts at 2021-11-11 03:00:00
2022-04-30 08:32:44,312 - freqtrade.data.history.idatahandler - WARNING - ICP/USDT, futures, 1h, data starts at 2021-05-11 03:00:00
2022-04-30 08:32:46,744 - freqtrade.optimize.hyperopt - INFO - Hyperopting with data from 2021-05-10 00:00:00 up to 2022-01-17 00:00:00 (252 days)..
2022-04-30 08:32:47,245 - freqtrade.exchange.exchange - INFO - Closing async ccxt session.
2022-04-30 08:32:47,248 - freqtrade.optimize.hyperopt - INFO - Found 24 CPU cores. Let's make them scream!
2022-04-30 08:32:47,248 - freqtrade.optimize.hyperopt - INFO - Number of parallel jobs set as: -1
2022-04-30 08:32:47,248 - freqtrade.optimize.hyperopt - INFO - Using estimator ET.
2022-04-30 08:32:47,269 - freqtrade.optimize.hyperopt - INFO - Effective number of parallel workers used: 24
```

**Comment by xmatthias** [comment]
>  Effective number of parallel workers used: 24

The answer was 24 :laughing: 

Does this appear reliably? if you run the same backtest (same random-state than when the error appeared) - does it reappear after 48 epochs again?

**Comment by moinonin** [comment]
oh thanks. Parallelism threw me off. 
Yes the error occurred twice ( at the same epoch ) before I posted it. If it helps I can try once more time.

**Comment by xmatthias** [comment]
can you retry with the changes described above

> Hoping that's the case - please add print(f"{len(asked)=}, {len(is_random)=}") into the hyperopt file L523 (right after asked, is_random = self.get_asked_points(n_points=current_jobs)).

I'd need the output of these - hopefully (!) it makes sense then ...

**Comment by rextea** [comment]
@xmatthias I'm having the same issue
I'm using it with VENV installation on MackBook M1 Pro chip - maybe that's the problem?
it's happening randomly, once in ~5 Hyperopts it fails

**Comment by xmatthias** [comment]
best follow what i wrote in https://github.com/freqtrade/freqtrade/issues/6746#issuecomment-1113475891 - it should help us narrow this down.

So far, i've been unable to reproduce it - but i THINK once it happens, it should be reproducible by using the same random-id - assuming the same strategy/data/... is used.
