### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'copy'

### ISSUE THREAD

**Issue by eldargoren** [freqtrade/freqtrade#6749]
Hi, I tried writing my own strategy (more of changing the Sample one) and stuck with an issue:
`Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 58, in start_backtesting
    backtesting.start()
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 932, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 853, in backtest_one_strategy
    preprocessed = self.strategy.advise_all_indicators(data)
  File "/freqtrade/freqtrade/strategy/interface.py", line 898, in advise_all_indicators
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "/freqtrade/freqtrade/strategy/interface.py", line 898, in <dictcomp>
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
AttributeError: 'NoneType' object has no attribute 'copy'`

Do you know why this happens?

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

The most likely reason this happens is if you're not returning the dataframe from one of the `populate_*` methods in your strategy.

**Comment by eldargoren** [comment]
Thank you it worked!
To be fair there wasn't any question to fill.
