### ISSUE TITLE
Backtest_start_time error

### ISSUE THREAD

**Issue by Fimap9to1** [freqtrade/freqtrade#6775]
Hi, I'm updating my freqtrade version. I updated the wording in config file "sell --> exit" etc.. not in the strategy file yet.

I'm getting this error when running backtest, please see the logs below:

```
freqtrade backtesting -s ryloslive2 -c config.qqe.usdt.binancebis2.json --timerange=20220315-20220319 --disable-max-market-positions --export trades
2022-05-03 12:33:03,790 - freqtrade.configuration.load_config - INFO - Using config: config.qqe.usdt.binancebis2.json ...
2022-05-03 12:33:03,795 - freqtrade.loggers - INFO - Verbosity set to 0
2022-05-03 12:33:03,795 - freqtrade.configuration.configuration - INFO - Parameter --disable-max-market-positions detected ...
2022-05-03 12:33:03,795 - freqtrade.configuration.configuration - INFO - max_open_trades set to unlimited ...
2022-05-03 12:33:03,795 - freqtrade.configuration.configuration - INFO - Parameter --timerange detected: 20220315-20220319 ...
2022-05-03 12:33:03,806 - freqtrade.configuration.configuration - INFO - Using user-data directory: /opt/freqtrade/user_data ...
2022-05-03 12:33:03,807 - freqtrade.configuration.configuration - INFO - Using data directory: /opt/freqtrade/user_data/data/binance ...
2022-05-03 12:33:03,808 - freqtrade.configuration.configuration - INFO - Parameter --export detected: trades ...
2022-05-03 12:33:03,808 - freqtrade.configuration.configuration - INFO - Parameter --cache=day detected ...
2022-05-03 12:33:03,808 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2022-05-03 12:33:03,813 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2022-05-03 12:33:03,813 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2022-05-03 12:33:03,814 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2022-05-03 12:33:03,816 - freqtrade.commands.optimize_commands - INFO - Starting freqtrade in Backtesting mode
2022-05-03 12:33:03,816 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2022-05-03 12:33:03,816 - freqtrade.exchange.exchange - INFO - Using CCXT 1.81.16
2022-05-03 12:33:03,817 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2022-05-03 12:33:03,822 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 50}
2022-05-03 12:33:03,828 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2022-05-03 12:33:04,799 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2022-05-03 12:33:04,891 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy ryloslive2 from '/mnt/c/freqtrade/user_data/strategies/ryloslive2 - originale.py'...
2022-05-03 12:33:04,892 - freqtrade.strategy.hyper - INFO - Found no parameter file.
2022-05-03 12:33:04,892 - freqtrade.strategy.hyper - INFO - No params for sell found, using default values.
2022-05-03 12:33:04,893 - freqtrade.strategy.hyper - INFO - No params for protection found, using default values.
2022-05-03 12:33:04,894 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 5m.
2022-05-03 12:33:04,894 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'process_only_new_candles' with value in config file: False.
2022-05-03 12:33:04,894 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'order_types' with value in config file: {'entry': 'limit', 'exit': 'limit', 'emergency_exit': 'market', 'stoploss': 'limit', 'stoploss_on_exchange': False, 'stoploss_on_exchange_interval': 300}.
2022-05-03 12:33:04,894 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2022-05-03 12:33:04,894 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: unlimited.
2022-05-03 12:33:04,894 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'entry': 1500, 'exit': 1500, 'exit_timeout_count': 0, 'unit': 'minutes'}.
2022-05-03 12:33:04,894 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 10}
2022-05-03 12:33:04,894 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 5m
2022-05-03 12:33:04,895 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.5
2022-05-03 12:33:04,895 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2022-05-03 12:33:04,895 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive: 0.01
2022-05-03 12:33:04,895 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.03
2022-05-03 12:33:04,895 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: True
2022-05-03 12:33:04,895 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2022-05-03 12:33:04,895 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
2022-05-03 12:33:04,895 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'entry': 'limit', 'exit': 'limit', 'emergency_exit': 'market', 'stoploss': 'limit', 'stoploss_on_exchange': False, 'stoploss_on_exchange_interval': 300}
2022-05-03 12:33:04,896 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'entry': 'gtc', 'exit': 'gtc'}
2022-05-03 12:33:04,896 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2022-05-03 12:33:04,896 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: unlimited
2022-05-03 12:33:04,896 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2022-05-03 12:33:04,896 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 480
2022-05-03 12:33:04,896 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'entry': 1500, 'exit': 1500, 'exit_timeout_count': 0, 'unit': 'minutes'}
2022-05-03 12:33:04,896 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_exit_signal: True
2022-05-03 12:33:04,896 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_only: False
2022-05-03 12:33:04,896 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_entry_signal: True
2022-05-03 12:33:04,896 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_offset: 0.0
2022-05-03 12:33:04,896 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2022-05-03 12:33:04,896 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2022-05-03 12:33:04,896 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: False
2022-05-03 12:33:04,896 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1
2022-05-03 12:33:04,896 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2022-05-03 12:33:04,899 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from '/opt/freqtrade/freqtrade/plugins/pairlist/StaticPairList.py'...
2022-05-03 12:33:04,901 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist AgeFilter from '/opt/freqtrade/freqtrade/plugins/pairlist/AgeFilter.py'...
2022-05-03 12:33:04,901 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist SpreadFilter from '/opt/freqtrade/freqtrade/plugins/pairlist/SpreadFilter.py'...
2022-05-03 12:33:04,902 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist PriceFilter from '/opt/freqtrade/freqtrade/plugins/pairlist/PriceFilter.py'...
2022-05-03 12:33:04,902 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist RangeStabilityFilter from '/opt/freqtrade/freqtrade/plugins/pairlist/rangestabilityfilter.py'...
2022-05-03 12:33:04,904 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist VolatilityFilter from '/opt/freqtrade/freqtrade/plugins/pairlist/VolatilityFilter.py'...
2022-05-03 12:33:04,905 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist ShuffleFilter from '/opt/freqtrade/freqtrade/plugins/pairlist/ShuffleFilter.py'...
2022-05-03 12:33:04,905 - ShuffleFilter - INFO - Backtesting mode detected, applying seed value: None
2022-05-03 12:33:34,091 - freqtrade.data.history.history_utils - INFO - Using indicator startup period: 480 ...
2022-05-03 12:34:15,456 - freqtrade.optimize.backtesting - INFO - Loading data from 2022-03-13 08:00:00 up to 2022-03-19 00:00:00 (5 days).
2022-05-03 12:34:15,456 - freqtrade.optimize.backtesting - INFO - Dataload complete. Calculating indicators
2022-05-03 12:34:15,501 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/opt/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/opt/freqtrade/freqtrade/commands/optimize_commands.py", line 58, in start_backtesting
    backtesting.start()
  File "/opt/freqtrade/freqtrade/optimize/backtesting.py", line 1154, in start
    self.load_prior_backtest()
  File "/opt/freqtrade/freqtrade/optimize/backtesting.py", line 1140, in load_prior_backtest
    self.results = find_existing_backtest_stats(
  File "/opt/freqtrade/freqtrade/data/btanalysis.py", line 228, in find_existing_backtest_stats
    backtest_date = strategy_metadata['backtest_start_time']
KeyError: 'backtest_start_time'
``` 

Any idea on what could cause it? Thankyou!

**Comment by Fimap9to1** [comment]
The actual error is:

`2022-05-03 12:33:34,091 - freqtrade.data.history.history_utils - INFO - Using indicator startup period: 480 ...
2022-05-03 12:34:15,456 - freqtrade.optimize.backtesting - INFO - Loading data from 2022-03-13 08:00:00 up to 2022-03-19 00:00:00 (5 days).
2022-05-03 12:34:15,456 - freqtrade.optimize.backtesting - INFO - Dataload complete. Calculating indicators
2022-05-03 12:34:15,501 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/opt/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/opt/freqtrade/freqtrade/commands/optimize_commands.py", line 58, in start_backtesting
    backtesting.start()
  File "/opt/freqtrade/freqtrade/optimize/backtesting.py", line 1154, in start
    self.load_prior_backtest()
  File "/opt/freqtrade/freqtrade/optimize/backtesting.py", line 1140, in load_prior_backtest
    self.results = find_existing_backtest_stats(
  File "/opt/freqtrade/freqtrade/data/btanalysis.py", line 228, in find_existing_backtest_stats
    backtest_date = strategy_metadata['backtest_start_time']
KeyError: 'backtest_start_time'`

**Comment by xmatthias** [comment]
it somehow seems that you've got an incomplete / invalid .metadata file in your backtest-dir.

you can get around this by either backtesting without cache (once) (`--cache none`) - or by looking for the broken `*.meta.json` file in the backtest_results dir.

I've actually never seen this - so i'd be curious how that file will actually look like.

**Comment by Fimap9to1** [comment]
Yes it's now working with "--cache none". What's the difference with a normal backtest? And what if I run my strategy live?

**Comment by Fimap9to1** [comment]
I copy paste the meta here "backtest-result-2022-05-03_13-15-36.meta.json"

{"ryloslive2":{"run_id":"67761e688c77cd37e66925ffcc1c1d9d294e86e0","backtest_start_time":1651576511}}

This is the only content. No trades are made in this period.

Previous meta files content is always something like this:

{"ryloslive2":{"run_id":"b13e2e1cfaa86bd69b4ccc84d2f766cb32840c5a"}}

**Comment by xmatthias** [comment]
`--cache none` is just applied during backtesting - this has nothing to do with live.

What was your prior version? i don't think we've had a release with the meta file without `backtest_start_time` - only a short period of develop ...

**Comment by Fimap9to1** [comment]
```
@LAPTOP-520UHUE:/opt/freqtrade$ ./setup.sh --update
/usr/bin/python3.8
using python3.8
remote: Enumerating objects: 10056, done.
remote: Counting objects: 100% (3919/3919), done.
remote: Total 10056 (delta 3919), reused 3919 (delta 3919), pack-reused 6137
Receiving objects: 100% (10056/10056), 7.86 MiB | 2.06 MiB/s, done.
Resolving deltas: 100% (8081/8081), completed with 308 local objects.
From https://github.com/freqtrade/freqtrade
   301b2e8a0..65ab6d246  develop    -> origin/develop
 + 4ca2d9939...73e8173db cross-liq  -> origin/cross-liq  (forced update)
   b53060071..e7f525207  stable     -> origin/stable
 * [new tag]             2022.4.1   -> 2022.4.1
 * [new tag]             2022.1     -> 2022.1
 * [new tag]             2022.2     -> 2022.2
 * [new tag]             2022.2.1   -> 2022.2.1
 * [new tag]             2022.2.2   -> 2022.2.2
 * [new tag]             2022.3     -> 2022.3
Updating 301b2e8a0..65ab6d246
```

**Comment by Fimap9to1** [comment]
> `--cache none` is just applied during backtesting - this has nothing to do with live.
> 
> What was your prior version? i don't think we've had a release with the meta file without `backtest_start_time` - only a short period of develop ...

So the bot should work live right?

**Comment by xmatthias** [comment]
that's a "intermediate" version (mid-january).

yes it will. 
You can simply delete all metadata-files. The ones you have will not work correctly anyway.

As you've updated several versions - make sure to read the release logs - there has been some changed behaviour over the past few versions - so make sure these changes won't impact your strategy.

**Comment by Fimap9to1** [comment]
Ok, where do I find released logs?

**Comment by xmatthias** [comment]
well - on the [releases page](https://github.com/freqtrade/freqtrade/releases) of this repository ;) 

Important changes will be in the "highlighted changes" section for each release.

**Comment by Fimap9to1** [comment]
Great, thankyou. I've checked and it seems nothing is afecting the strategy.

I give you and overall picture of it right now.
Strategy is still using custom_sell, populate_sell_trend, etc instead of populate_exit_trend etc
The config file is the following:

````
{
    "max_open_trades": 40,
    "stake_currency": "USDT",
    "stake_amount": "unlimited",
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "EUR",
    "timeframe": "5m",
    "dry_run": true,
    "dry_run_wallet":10000,
    "process_only_new_candles": false,
    "cancel_open_orders_on_exit": false,
    "unfilledtimeout": {
        "entry":1500,
        "exit": 1500
    },
    "exit_pricing": {
        "price_side": "ask",
        "ask_last_balance": 0.0,
        "use_order_book": false,
        "order_book_top": 1,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "entry_pricing": {
        "ignore_entrying_expired_candle_after": 900,
        "price_side": "bid",
        "use_order_book": false,
        "order_book_min": 1,
        "order_book_max": 1,
        "use_exit_signal": true,
        "exit_profit_only": false,
        "ignore_roi_if_entry_signal": false
    },
    "order_types": {
        "entry": "limit",
        "exit": "limit",
        "emergency_exit": "market",
        "stoploss": "limit",
        "stoploss_on_exchange": false,
        "stoploss_on_exchange_interval": 300
    },
    "exchange": {
    "name": "binance",
        "key": "mykey",
        "secret": "mykey",
        "ccxt_config": {"enableRateLimit": true},
        "ccxt_async_config": {
            "enableRateLimit": true,
            "rateLimit": 50
        },
        "pair_whitelist": [
            "BTC/USDT",
            "ETH/USDT",
            "BNB/USDT",
            "SOL/USDT",
            "ADA/USDT",
            "XRP/USDT",
            "DOGE/USDT",
            "DOT/USDT",
            "AVAX/USDT",
            "LTC/USDT",
            "LUNA/USDT",
            "UNI/USDT",
            "MATIC/USDT",
            "LINK/USDT",
            "BCH/USDT",
            "ALGO/USDT",
            "EGLD/USDT",
            "MANA/USDT",
            "AXS/USDT",
            "VET/USDT",
            "XLM/USDT",
            "ICP/USDT",
            "SAND/USDT",
            "THETA/USDT",
            "TRX/USDT",
            "FTT/USDT",
            "ATOM/USDT",
            "FIL/USDT",
            "FTM/USDT",
            "ETC/USDT",
            "HBAR/USDT",
            "HNT/USDT",
            "NEAR/USDT",
            "XMR/USDT",
            "LRC/USDT",
            "IOTA/USDT",
            "XTZ/USDT",
            "FLOW/USDT",
            "ENJ/USDT",
            "EOS/USDT",
            "GRT/USDT",
            "ZEC/USDT",
            "CAKE/USDT",
            "KLAY/USDT",
            "AAVE/USDT",
            "MKR/USDT",
            "ONE/USDT",
            "RUNE/USDT",
            "CHZ/USDT",
            "XEC/USDT",
            "KSM/USDT",
            "NEO/USDT",
            "QNT/USDT",
            "CRV/USDT",
            "STX/USDT",
            "BTT/USDT",
            "DASH/USDT",
            "AMP/USDT",
            "HOT/USDT",
            "WAVES/USDT",
            "AR/USDT",
            "BAT/USDT",
            "CELO/USDT",
            "TFUEL/USDT",
            "IOTX/USDT",
            "COMP/USDT",
            "WAXP/USDT",
            "QTUM/USDT",
            "XEM/USDT",
            "MINA/USDT",
            "ZEN/USDT",
            "DCR/USDT",
            "ICX/USDT",
            "AUDIO/USDT",
            "ROSE/USDT",
            "OMG/USDT",
            "RVN/USDT",
            "YFI/USDT",
            "ZIL/USDT",
            "LPT/USDT",
            "SC/USDT",
            "ANKR/USDT",
            "BTG/USDT",
            "ZRX/USDT",
            "SKL/USDT",
            "SUSHI/USDT",
            "BNT/USDT",
            "SNX/USDT",
            "UMA/USDT",
            "REN/USDT",
            "ALICE/USDT",
            "ALPHA/USDT",
            "ONT/USDT",
            "STORJ/USDT",
            "CELR/USDT",
            "CHR/USDT",
            "IOST/USDT",
            "HIVE/USDT",
            "DGB/USDT",
            "KAVA/USDT",
            "1INCH/USDT",
            "NANO/USDT",
            "OCEAN/USDT",
            "FET/USDT",
            "RSR/USDT",
            "OGN/USDT",
            "LSK/USDT",
            "SXP/USDT",
            "BAKE/USDT",
            "NKN/USDT",
            "COTI/USDT",
            "OXT/USDT",
            "CVC/USDT",
            "ARDR/USDT",
            "RLC/USDT",
            "TOMO/USDT",
            "XVS/USDT",
            "CTSI/USDT",
            "DENT/USDT",
            "ONG/USDT",
            "PERP/USDT",
            "POLS/USDT",
            "REEF/USDT",
            "STMX/USDT",
            "SUPER/USDT",
            "WIN/USDT",
            "WRX/USDT",
            "CKB/USDT",
            "RAY/USDT",
            "SRM/USDT",
            "INJ/USDT"         
        ]
    //     "pair_blacklist": [
    //         // Exchange
    //         ".*(BNB)/.*",
    //         // Major
    //          ".*(BTC|ETH)/.*",
    //         // Leverage
    //          ".*(_PREMIUM|BEAR|BULL|DOWN|HALF|HEDGE|UP|[1235][SL])/.*",
    //         // Fiat
    //         ".*(AUD|BRZ|CAD|CHF|EUR|GBP|HKD|IDRT|JPY|NGN|RUB|SGD|TRY|UAH|USD|ZAR)/.*",
    //         // Stable
    //         ".*(BUSD|CUSDT|DAI|PAX|PAXG|SUSD|TUSD|USDC|USDT|VAI)/.*",
    //         // FAN
    //         ".*(ACM|AFA|ALA|ALL|APL|ASR|ATM|BAR|CAI|CITY|FOR|GAL|GOZ|IBFK|JUV|LEG|LOCK-1|NAVI|NMR|NOV|OG|PFL|PSG|ROUSH|STV|TH|TRA|UCH|UFC|YBO)/.*",
    //         // Others
    //         ".*(CHZ|CTXC|HBAR|NMR|SHIB|SLP|XVS|BAL|BAT|ONG)/.*"
    //   ]
    },
    "pairlists": [
        {
            "method": "StaticPairList"
        },
        // {
        //     "method": "VolumePairList",
        //     "number_assets": 75,
        //     "sort_key": "quoteVolume",
        //     "refresh_period": 1800
        // },
        {"method": "AgeFilter", "min_days_listed": 14},
        {"method": "SpreadFilter", "max_spread_ratio": 0.005},
        {"method": "PriceFilter", "min_price": 0.0001},
        {
            "method": "RangeStabilityFilter",
            "lookback_days": 3,
            "min_rate_of_change": 0.1,
            "refresh_period": 1440
        },
        {
            "method": "VolatilityFilter",
            "lookback_days": 4,
            "min_volatility": 0.02,
            "max_volatility": 0.75,
            "refresh_period": 86400
        },
        {"method": "ShuffleFilter"}
    ],

    // "protections": [
    //     //{
    //      //   "method": "LowProfitPairs",
    //      //   "lookback_period_candles": 500,
    //      //   "trade_limit": 5,
    //      //   "stop_duration_candles": 3,
    //     //    "required_profit": 0.00
    //     //},
    //     {
    //         "method": "MaxDrawdown",
    //         "lookback_period_candles": 250,
    //         "trade_limit": 16,
    //         "stop_duration_candles": 100,
    //         "max_allowed_drawdown": 5.0
    //     }
    // ],


    "edge": {
        "enabled": false,
        "process_throttle_secs": 3600,
        "calculate_since_number_of_days": 7,
        "allowed_risk": 0.03,
        "stoploss_range_min": -0.10,
        "stoploss_range_max": -0.40,
        "stoploss_range_step": -0.01,
        "minimum_winrate": 0.66,
        "minimum_expectancy": 0.20,
        "min_trade_number": 10,
        "max_trade_duration_minute": 2160,
        "remove_pumps": false
    },
    "telegram": {
        "enabled": false,
        "token": "mytoken",
        "chat_id": "mychatid",
        "notification_settings": {
            "status": "silent",
            "warning": "on",
            "startup": "off",
            "entry": "silent",
            "exit": {
                "roi": "on",
                "emergency_exit": "on",
                "force_exit": "on",
                "exit_signal": "on",
                "trailing_stop_loss": "on",
                "stop_loss": "on",
                "stoploss_on_exchange": "on",
                "custom_exit": "on"
            },
            "entry_cancel": "silent",
            "exit_cancel": "on",
            "entry_fill": "silent",
            "exit_fill": "silent"
        },
        "keyboard": [
            ["/daily", "/profit", "/balance"],
            ["/stats", "/status", "/status table", "/performance"],
            ["/count", "/trades", "/logs", "/help"]
        ]

    },

    "api_server": {
        "enabled": false,
        "listen_ip_address": "127.0.0.1",
        "listen_port": 8080,
        "verbosity": "info",
        "jwt_secret_key": "somethingrandom",
        "CORS_origins": [],
        "username": "",
        "password": ""
    },
    "initial_state": "running",
    "force_exit_enable": true,
    "internals": {
        "process_throttle_secs": 5
    },
    
}
```

Do you also think everything is fine or I missed something?

**Comment by xmatthias** [comment]
i don't have the changelog of the last 5 versions in mind. It's up to the user to determine if their strategy is affected by it or not - as the critical part will be the strategy, not the configuration.

**Comment by Fimap9to1** [comment]
Oh ok. Just to make sure, updating wording sell--->exit etc is not mandatory yet right?

**Comment by xmatthias** [comment]
no it's not, and it will not be for several versions.

**Comment by Fimap9to1** [comment]
Great. Thanks
