### ISSUE TITLE
single positional indexer is out-of-bounds

### ISSUE THREAD

**Issue by Fimap9to1** [freqtrade/freqtrade#6785]
Hi, running backtest I got this error. If add to the command line --cache none than it gives me results. 

Any idea on what could be causing it?

```
2022-05-06 17:43:57,674 - freqtrade.optimize.backtesting - INFO - Backtesting with data from 2021-05-15 00:00:00 up to 2021-05-22 00:00:00 (7 days).
2022-05-06 17:43:59,167 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error single positional indexer is out-of-bounds calling <bound method IStrategy.custom_exit of <ryloslive2TEST.ryloslive2TEST object at 0x7f537d330d90>>
Traceback (most recent call last):
  File "/opt/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 21, in wrapper
    return f(*args, **kwargs)
  File "/opt/freqtrade/freqtrade/strategy/interface.py", line 431, in custom_exit
    return self.custom_sell(pair, trade, current_time, current_rate, current_profit, **kwargs)
  File "/mnt/c/freqtrade/user_data/strategies/ryloslive2TEST.py", line 925, in custom_sell
    previous_candle_5 = dataframe.iloc[-6]
  File "/opt/freqtrade/.env/lib/python3.8/site-packages/pandas/core/indexing.py", line 967, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/opt/freqtrade/.env/lib/python3.8/site-packages/pandas/core/indexing.py", line 1520, in _getitem_axis
    self._validate_integer(key, axis)
  File "/opt/freqtrade/.env/lib/python3.8/site-packages/pandas/core/indexing.py", line 1452, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
2022-05-06 17:44:41,259 - freqtrade.misc - INFO - dumping json to "/opt/freqtrade/user_data/backtest_results/backtest-result-2022-05-06_17-44-41.meta.json"
2022-05-06 17:44:41,264 - freqtrade.misc - INFO - dumping json to "/opt/freqtrade/user_data/backtest_results/backtest-result-2022-05-06_17-44-41.json"
2022-05-06 17:44:41,280 - freqtrade.misc - INFO - dumping json to "/opt/freqtrade/user_data/backtest_results/.last_result.json"
Result for strategy ryloslive2TEST
=========================================================== BACKTESTING REPORT ==========================================================
|       Pair |   Buys |   Avg Profit % |   Cum Profit % |   Tot Profit USDT |   Tot Profit % |   Avg Duration |   Win  Draw  Loss  Win% |
|------------+--------+----------------+----------------+-------------------+----------------+----------------+-------------------------|
```

**Comment by xmatthias** [comment]
well yes - you're accessing a row that doesn't exist.
the stack-trace pretty much tells you the precise line in your strategy

```
custom_sell
    previous_candle_5 = dataframe.iloc[-6]`
```

You access `iloc -6` - so you assume 6+ candles are available - which may not be the case if you have a buy right at the beginning of the backtest period.

best check if the length of the dataframe is 6+ before accessing this way...

**Comment by Fimap9to1** [comment]
Thanks. Is it normal that before the upgrade I've never got this error? I was using a January version of freq. I got it after update.

**Comment by xmatthias** [comment]
it's very well possible that something in this regard changed (specifically - with how startup-candles are handled). Best check the release-logs to identify when that change was precisely.

**Comment by Fimap9to1** [comment]
Still getting the error from time to time:

```
2022-07-15 12:33:14,944 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error single positional indexer is out-of-bounds calling <bound method IStrategy.custom_exit of <ryloslive2 - LOW.ryloslive2clow object at 0x7fbbb67375b0>>
Traceback (most recent call last):
  File "/opt/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 27, in wrapper
    return f(*args, **kwargs)
  File "/opt/freqtrade/freqtrade/strategy/interface.py", line 441, in custom_exit
    return self.custom_sell(pair, trade, current_time, current_rate, current_profit, **kwargs)
  File "/mnt/c/freqtrade/user_data/strategies/ryloslive2 - LOW.py", line 253, in custom_sell
    previous_candle_1 = dataframe.iloc[-2]
  File "/opt/freqtrade/.env/lib/python3.8/site-packages/pandas/core/indexing.py", line 967, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/opt/freqtrade/.env/lib/python3.8/site-packages/pandas/core/indexing.py", line 1520, in _getitem_axis
    self._validate_integer(key, axis)
  File "/opt/freqtrade/.env/lib/python3.8/site-packages/pandas/core/indexing.py", line 1452, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
```

After it, I get backtest results properly. Why this happens? Could it be a lookahead problem? 

The "previous_candle_1 = dataframe.iloc[-2]" it refers to is the following:

```
def custom_sell(self, pair: str, trade: 'Trade', current_time: 'datetime', current_rate: float,
                    current_profit: float, **kwargs):
        dataframe, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)
        last_candle = dataframe.iloc[-1]
        previous_candle_1 = dataframe.iloc[-2]  <-------------------------------------------------------------

        buy_tag = 'empty'
        if hasattr(trade, 'buy_tag') and trade.buy_tag is not None:
            buy_tag = trade.buy_tag
        else:
            trade_open_date = timeframe_to_prev_date(self.timeframe, trade.open_date_utc)
            buy_signal = dataframe.loc[dataframe['date'] < trade_open_date]
            if not buy_signal.empty:
                buy_signal_candle = buy_signal.iloc[-1]
                buy_tag = buy_signal_candle['buy_tag'] if buy_signal_candle['buy_tag'] != '' else 'empty'
        buy_tags = buy_tag.split()
        max_profit = ((trade.max_rate - trade.open_rate) / trade.open_rate)
        max_loss = ((trade.open_rate - trade.min_rate) / trade.min_rate)

        # buy49_mode
        if any(c in ['49'] for c in buy_tags):
            sell, signal_name = self.sell_buy49_mode(current_profit, max_profit, last_candle, previous_candle_1)
            if sell and (signal_name is not None):
                return f"{signal_name} ( {buy_tag} )"
            #Skip remaining sell logic for buy49_mode
            return None
```

**Comment by xmatthias** [comment]
You cannot rely to have unlimited history available - especially not in backtesting - where you're limited by the available data, as well as the selected timerange.

I'm pretty sure this happens if your trade is opened on the very first candle of the backtest period - then you'll only get a history of 1 candle.
As you fail to check if you actually have 2 candles available - it's failing.

**Comment by Fimap9to1** [comment]
I see, so no action has to be taken right? It's just a backtest related issue

**Comment by xmatthias** [comment]
well it can cause a slight deviation between live and backtesting - as you don't have any fallback code for this, and simply let it crash.
how likely it is that a trade would be sold right after entering is a different topic - one you can answer best based on your strategy.

**Comment by Fimap9to1** [comment]
Great, thank you
