### ISSUE TITLE
bittrex get_real_amount() KeyError when buying

### ISSUE THREAD

**Issue by mshirley** [freqtrade/freqtrade#679]
Bot placed an order but I received this KeyError.  The order went through just fine but the bot crashed.

I've placed a debug statement to print out the contents of order['fee'] to see what's going on the next time I get a buy order.

```
2018-05-15 02:42:41,697 - freqtrade.freqtradebot - INFO - Checking buy signals to create a new trade with stake_amount: 0.050000 ...
2018-05-15 02:42:43,203 - freqtrade.freqtradebot - WARNING - Unable to create trade: stake amount is not fulfilled (currency=BTC)
2018-05-15 02:42:46,186 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=1, pair=ADA/BTC, amount=1617.59948237, open_rate=0.00003091, open_since=just now)
2018-05-15 02:42:47,707 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/user/src/freqtrade/freqtrade/main.py", line 45, in main
    state = freqtrade.worker(old_state=state)
  File "/home/user/src/freqtrade/freqtrade/freqtradebot.py", line 120, in worker
    nb_assets=nb_assets)
  File "/home/user/src/freqtrade/freqtrade/freqtradebot.py", line 132, in _throttle
    result = func(*args, **kwargs)
  File "/home/user/src/freqtrade/freqtrade/freqtradebot.py", line 164, in _process
    state_changed |= self.process_maybe_execute_sell(trade)
  File "/home/user/src/freqtrade/freqtrade/freqtradebot.py", line 371, in process_maybe_execute_sell
    new_amount = self.get_real_amount(trade, order)
  File "/home/user/src/freqtrade/freqtrade/freqtradebot.py", line 401, in get_real_amount
    if trade.pair.startswith(order['fee']['currency']):
KeyError: 'currency'
2018-05-15 02:42:47,707 - freqtrade.rpc.rpc_manager - INFO - *Status:* `Stopping trader...`
2018-05-15 02:42:47,956 - freqtrade.freqtradebot - INFO - Stopping trader and cleaning up modules...
2018-05-15 02:42:47,956 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.telegram ...
```

**Comment by mshirley** [comment]
Contents of order variable.

```{
    "info": {
        "AccountId": null,
        "OrderUuid": "c48e638e-fb27-416b-a981-6761bab23221",
        "Exchange": "BTC-ADA",
        "Type": "LIMIT_BUY",
        "Quantity": 1617.59948236,
        "QuantityRemaining": 0.0,
        "Limit": 3.091e-05,
        "Reserved": 0.04999999,
        "ReserveRemaining": 0.04999999,
        "CommissionReserved": 0.00012499,
        "CommissionReserveRemaining": 0.0,
        "CommissionPaid": 0.00012499,
        "Price": 0.04999999,
        "PricePerUnit": 3.09e-05,
        "Opened": "2018-05-15T08:42:37.123",
        "Closed": "2018-05-15T08:42:42.153",
        "IsOpen": false,
        "Sentinel": "387f612e-88d7-4acc-ab6a-35cf74d9e76f",
        "CancelInitiated": false,
        "ImmediateOrCancel": false,
        "IsConditional": false,
        "Condition": "NONE",
        "ConditionTarget": null
    },
    "id": "c48e638e-fb27-416b-a981-6761bab23221",
    "timestamp": 1526373757123,
    "datetime": "2018-05-15T08:42:37.123Z",
    "lastTradeTimestamp": 1526373762153,
    "symbol": "ADA/BTC",
    "type": "limit",
    "side": "buy",
    "price": 3.091e-05,
    "cost": 0.04999999,
    "average": 3.09e-05,
    "amount": 1617.59948236,
    "filled": 1617.59948236,
    "remaining": 0.0,
    "status": "closed",
    "fee": {
        "cost": 0.00012499
    }
}```

**Comment by mshirley** [comment]
This line...
https://github.com/gcarq/freqtrade/blob/d74a0f0526e7c2a92467bbf097fcb3c7e28b9236/freqtrade/freqtradebot.py#L401

Changing this line allows the program to continue properly
```if trade.pair.startswith(order['symbol']):```

I have concerns about this line as well but I haven't hit it yet
https://github.com/gcarq/freqtrade/blob/d74a0f0526e7c2a92467bbf097fcb3c7e28b9236/freqtrade/freqtradebot.py#L419

**Comment by gcarq** [comment]
I'm closing this. Feel free to reopen if this is still an issue
