### ISSUE TITLE
Bot process is died suddenly and restart

### ISSUE THREAD

**Issue by jugrazovich** [freqtrade/freqtrade#6817]
System: Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-110-generic x86_64)
2 GB Memory, 1 AMD vCPU
Freqtrade Version: 2022.4.2 
Docker Compose Container

Here is the logs;

```
freqtrade    | 2022-05-12 14:45:24,019 - freqtrade.commands.trade_commands - ERROR - unsupported operand type(s) for -: 'NoneType' and 'int'
freqtrade    | 2022-05-12 14:45:24,019 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
freqtrade    | Traceback (most recent call last):
freqtrade    |   File "/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
freqtrade    |     worker.run()
freqtrade    |   File "/freqtrade/freqtrade/worker.py", line 74, in run
freqtrade    |     state = self._worker(old_state=state)
freqtrade    |   File "/freqtrade/freqtrade/worker.py", line 114, in _worker
freqtrade    |     self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
freqtrade    |   File "/freqtrade/freqtrade/worker.py", line 139, in _throttle
freqtrade    |     result = func(*args, **kwargs)
freqtrade    |   File "/freqtrade/freqtrade/worker.py", line 152, in _process_running
freqtrade    |     self.freqtrade.process()
freqtrade    |   File "/freqtrade/freqtrade/freqtradebot.py", line 213, in process
freqtrade    |     self._schedule.run_pending()
freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/schedule/__init__.py", line 100, in run_pending
freqtrade    |     self._run_job(job)
freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/schedule/__init__.py", line 172, in _run_job
freqtrade    |     ret = job.run()
freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/schedule/__init__.py", line 661, in run
freqtrade    |     ret = self.job_func()
freqtrade    |   File "/freqtrade/freqtrade/freqtradebot.py", line 115, in update
freqtrade    |     self.wallets.update()
freqtrade    |   File "/freqtrade/freqtrade/wallets.py", line 170, in update
freqtrade    |     self._update_live()
freqtrade    |   File "/freqtrade/freqtrade/wallets.py", line 143, in _update_live
freqtrade    |     positions = self._exchange.fetch_positions()
freqtrade    |   File "/freqtrade/freqtrade/exchange/common.py", line 142, in wrapper
freqtrade    |     return f(*args, **kwargs)
freqtrade    |   File "/freqtrade/freqtrade/exchange/exchange.py", line 1292, in fetch_positions
freqtrade    |     positions: List[Dict] = self._api.fetch_positions()
freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/binance.py", line 4677, in fetch_positions
freqtrade    |     return self.fetch_positions_risk(symbols, params)
freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/binance.py", line 4778, in fetch_positions_risk
freqtrade    |     parsed = self.parse_position_risk(response[i])
freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/binance.py", line 4488, in parse_position_risk
freqtrade    |     collateralString = Precise.string_div(Precise.string_mul(leftSide, contractsAbs), '1', quotePrecision)
freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/precise.py", line 202, in string_div
freqtrade    |     return str(Precise(string1).div(string2_precise, precision))
freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/precise.py", line 85, in div
freqtrade    |     distance = precision - self.decimals + other.decimals
freqtrade    | TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
```

thanks,

**Comment by xmatthias** [comment]
Unfortunately, this was a problem in ccxt, which was fixed several days ago.

It's since been fixed in develop - so i'd suggest to update to develop (or manually update ccxt to the latest version).
