### ISSUE TITLE
Error with pre-commit on latest dev and latest ubuntu lts

### ISSUE THREAD

**Issue by epigramx** [freqtrade/freqtrade#6846]
## Describe your environment

  * Operating system: ubuntu LTS 22.04
  * Python Version: 3.10.4
  * CCXT version: 1.82.61
  * Freqtrade Version: develop-1913565
  
## Describe the problem:

Running `git commit` without even any changed files yet (but also with staged files):

```
[INFO] Installing environment for https://github.com/pycqa/flake8.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: AssertionError: BUG: expected environment for python to be healthy immediately after install, please open an issue describing your environment

more info:

virtualenv python version did not match created version:
- actual version: <<error retrieving version from /root/.cache/pre-commit/repofldaadh7/py_env-python3.10/bin/python>>
- expected version: 3.10.4.final.0

Check the log at /root/.cache/pre-commit/pre-commit.log
```

`cat pre-commit.log`:

```
### version information

pre-commit version: 2.19.0
git --version: git version 2.34.1
sys.version:
    3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0]
sys.executable: /root/tmp/freqtrade/.env/bin/python3.10
os.name: posix
sys.platform: linux

### error information

An unexpected error has occurred: AssertionError: BUG: expected environment for python to be healthy immediately after install, please open an issue describing your environment

more info:

virtualenv python version did not match created version:
- actual version: <<error retrieving version from /root/.cache/pre-commit/repofldaadh7/py_env-python3.10/bin/python>>
- expected version: 3.10.4.final.0


Traceback (most recent call last):
  File "/root/tmp/freqtrade/.env/lib/python3.10/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/root/tmp/freqtrade/.env/lib/python3.10/site-packages/pre_commit/main.py", line 361, in main
    return hook_impl(
  File "/root/tmp/freqtrade/.env/lib/python3.10/site-packages/pre_commit/commands/hook_impl.py", line 238, in hook_impl
    return retv | run(config, store, ns)
  File "/root/tmp/freqtrade/.env/lib/python3.10/site-packages/pre_commit/commands/run.py", line 414, in run
    install_hook_envs(to_install, store)
  File "/root/tmp/freqtrade/.env/lib/python3.10/site-packages/pre_commit/repository.py", line 223, in install_hook_envs
    _hook_install(hook)
  File "/root/tmp/freqtrade/.env/lib/python3.10/site-packages/pre_commit/repository.py", line 84, in _hook_install
    raise AssertionError(
AssertionError: BUG: expected environment for python to be healthy immediately after install, please open an issue describing your environment

more info:

virtualenv python version did not match created version:
- actual version: <<error retrieving version from /root/.cache/pre-commit/repofldaadh7/py_env-python3.10/bin/python>>
- expected version: 3.10.4.final.0
```

### Steps to reproduce:

Run a plain `git commit` on a new freqtrade clone on ubuntu 22.04 LTS after `./setup -i` selects `dev` packages.

**Comment by epigramx** [comment]
https://github.com/pre-commit/pre-commit/issues/2374 =>
https://github.com/pre-commit/pre-commit/issues/2299
https://github.com/pre-commit/pre-commit/issues/2336
