### ISSUE TITLE
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

### ISSUE THREAD

**Issue by mablue** [freqtrade/freqtrade#6864]
## Describe your environment

  * Operating system: arch linux
  * Python Version: Python 3.9.9 
  * CCXT version: ccxt==1.80.61 
  * Freqtrade Version: freqtrade develop-d1a61f9c6 
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

```python 
    timeframe = '5m'
    prs = talib.get_function_groups()['Pattern Recognition']

    # # Strategy parameters
    buy_pr1 = CategoricalParameter(prs, default=prs[0], space="buy")
    buy_pr2 = CategoricalParameter(prs, default=prs[0], space="buy")
    sell_pr1 = CategoricalParameter(prs, default=prs[0], space="sell")
    sell_pr2 = CategoricalParameter(prs, default=prs[0], space="sell")

    buy_vol1 = CategoricalParameter([-100,0,100], default=0, space="buy")
    buy_vol2 = CategoricalParameter([-100,0,100], default=0, space="buy")
    sell_vol1 = CategoricalParameter([-100,0,100], default=0, space="sell")
    sell_vol2 = CategoricalParameter([-100,0,100], default=0, space="sell")

    

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        for pr in self.prs:
            dataframe[pr] = getattr(ta, pr)(dataframe)

        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                (dataframe[self.buy_pr1.value]==self.buy_vol1.value)|
                (dataframe[self.buy_pr2.value]==self.buy_vol2.value)
            ),
            'enter_long'] = 1

        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                (dataframe[self.sell_pr1.value]==self.sell_vol1.value)|
                (dataframe[self.sell_pr2.value]==self.sell_vol2.value)
            ),
            'exit_long'] = 1

        return dataframe

```  

```bash
freqtrade hyperopt -s PatternRecognition --hyperopt-loss SharpeHyperOptLossDaily -e 1000
```
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
 [Epoch 0 of 1000 (  0%)] |/                                                                                                          | [ETA:  --:--:--, Elapsed Time: 0:00:00]
2022-05-19 14:22:28,427 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/mab/Documents/DEV/1Freqtrade/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/home/mab/Documents/DEV/1Freqtrade/freqtrade/freqtrade/commands/optimize_commands.py", line 107, in start_hyperopt
    hyperopt.start()
  File "/home/mab/Documents/DEV/1Freqtrade/freqtrade/freqtrade/optimize/hyperopt.py", line 522, in start
    asked, is_random = self.get_asked_points(n_points=current_jobs)
  File "/home/mab/Documents/DEV/1Freqtrade/freqtrade/freqtrade/optimize/hyperopt.py", line 436, in get_asked_points
    asked = unique_list(self.opt.ask(n_points=n_points * 5))
  File "/home/mab/Documents/DEV/1Freqtrade/freqtrade/.env/lib/python3.9/site-packages/skopt/optimizer/optimizer.py", line 417, in ask
    opt._tell(x, y_lie)
  File "/home/mab/Documents/DEV/1Freqtrade/freqtrade/.env/lib/python3.9/site-packages/skopt/optimizer/optimizer.py", line 536, in _tell
    est.fit(self.space.transform(self.Xi), self.yi)
  File "/home/mab/Documents/DEV/1Freqtrade/freqtrade/.env/lib/python3.9/site-packages/sklearn/ensemble/_forest.py", line 327, in fit
    X, y = self._validate_data(
  File "/home/mab/Documents/DEV/1Freqtrade/freqtrade/.env/lib/python3.9/site-packages/sklearn/base.py", line 581, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/home/mab/Documents/DEV/1Freqtrade/freqtrade/.env/lib/python3.9/site-packages/sklearn/utils/validation.py", line 979, in check_X_y
    y = _check_y(y, multi_output=multi_output, y_numeric=y_numeric)
  File "/home/mab/Documents/DEV/1Freqtrade/freqtrade/.env/lib/python3.9/site-packages/sklearn/utils/validation.py", line 989, in _check_y
    y = check_array(
  File "/home/mab/Documents/DEV/1Freqtrade/freqtrade/.env/lib/python3.9/site-packages/sklearn/utils/validation.py", line 800, in check_array
    _assert_all_finite(array, allow_nan=force_all_finite == "allow-nan")
  File "/home/mab/Documents/DEV/1Freqtrade/freqtrade/.env/lib/python3.9/site-packages/sklearn/utils/validation.py", line 114, in _assert_all_finite
    raise ValueError(
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').  ```

**Comment by xmatthias** [comment]
This has nothing to do with freqtrade itself - but with the way you define parameters.

I assume that `prs = talib.get_function_groups()['Pattern Recognition']` will yield a list of some type (most likely float64) which is unsupported as space for scikit optimize. 

As such - you'll have to adjust your code accordingly.
There is little to nothing we can do in such a case, other than tell you to try it in a different way.

I'm sure if you remove / disable all parameters that use the `prs` as valid entries, hyperopt will work.

**Comment by mablue** [comment]
thnaks. I use it now without problem and without change!
it just returns a list of strings...I don't know why this happend but I never cant get this error on my pc! and nothing changed!!!!
its a scikit problem I think...any way
