### ISSUE TITLE
SpreadFilter throws TypeError: unsupported operand type(s) for /: 'NoneType' and 'float' exception

### ISSUE THREAD

**Issue by mosquitotrip** [freqtrade/freqtrade#6865]
## Describe your environment

  * Operating system: Debian
  * Python Version: 3.9.12 
  * CCXT version: 1.83.10 
  * Freqtrade Version: develop-d5486f17d 
  * 
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

SpreadFilter exception
Exchange used is FTX with ".*BULL/USDT" as whitelist

### Steps to reproduce:
     "exchange": {
 "pair_whitelist": [
      ".*BULL/USD"
    ],
    "pair_blacklist": []
  },
    "pairlists": [
    {
      "method": "StaticPairList"
    }, {
      "method": "SpreadFilter",
      "max_spread_ratio": 0.015
    }
  ],
### Observed Results:

freqtrade crashed without any user action

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
2022-05-19 16:58:58,674 - freqtrade.commands.trade_commands - ERROR - unsupported operand type(s) for /: 'NoneType' and 'float'
2022-05-19 16:58:58,675 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/freqtrade/freqtrade/worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/freqtrade/freqtrade/freqtradebot.py", line 98, in __init__
    self.active_pair_whitelist = self._refresh_active_whitelist()
  File "/freqtrade/freqtrade/freqtradebot.py", line 250, in _refresh_active_whitelist
    self.pairlists.refresh_pairlist()
  File "/freqtrade/freqtrade/plugins/pairlistmanager.py", line 93, in refresh_pairlist
    pairlist = pairlist_handler.filter_pairlist(pairlist, tickers)
  File "/freqtrade/freqtrade/plugins/pairlist/IPairList.py", line 112, in filter_pairlist
    if not self._validate_pair(p, tickers[p] if p in tickers else {}):
  File "/freqtrade/freqtrade/plugins/pairlist/SpreadFilter.py", line 54, in _validate_pair
    spread = 1 - ticker['bid'] / ticker['ask']
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
  ```

**Comment by xmatthias** [comment]
Thanks for reporting.
Will be fixed in develop with the next commit

**Comment by mosquitotrip** [comment]
```
ftx2        | 2022-05-20 02:33:54,774 - SpreadFilter - INFO - Removed XTZBULL/USD from whitelist, because spread 2.448% > 1.500%
ftx2        | 2022-05-20 02:33:54,774 - SpreadFilter - INFO - Removed ZECBULL/USD from whitelist, because spread 3.298% > 1.500%
```
Thank you, sir, it works like a charm now

This bug also appeared when trying to use multiple ",*quote/base" pair combination
