### ISSUE TITLE
ccxt.base.errors.NotSupported: binance does not have a testnet/sandbox URL for sapi endpoints

### ISSUE THREAD

**Issue by n8an** [freqtrade/freqtrade#6909]
## Describe your environment

  * Operating system: Docker Image
  * Python Version: the one provided in the latest freqtrade docker image
  * CCXT version: the one provided in the latest freqtrade docker image
  * Freqtrade Version: freqtrade 2022.5
## Describe the problem:

Trying to connect to a Binance Futures TESTNET using valid API keys that I have registered for this exact testnet.
Results in an error to load markets because of sapi keys not being supported in this sandbox.
I have tried multiple different ways of turning off "fetchCurrencies" and "fetchMarkets", yet it had no effect at all.

### Steps to reproduce:

1. docker-compose up -d
  
### Observed Results:

error log

### Relevant code exceptions or logs

2022-05-31 09:16:04,045 - freqtrade.loggers - INFO - Verbosity set to 0
2022-05-31 09:16:04,047 - freqtrade.configuration.configuration - INFO - Runmode set to live.
2022-05-31 09:16:04,048 - freqtrade.configuration.configuration - INFO - Parameter --db-url detected ...
2022-05-31 09:16:04,049 - freqtrade.configuration.configuration - INFO - Dry run is disabled
2022-05-31 09:16:04,050 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:////freqtrade/user_data/tradesv3.sqlite"
2022-05-31 09:16:04,051 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 14 ...
2022-05-31 09:16:04,109 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2022-05-31 09:16:04,112 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/binance ...
2022-05-31 09:16:04,113 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2022-05-31 09:16:04,133 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2022-05-31 09:16:04,135 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2022-05-31 09:16:04,136 - freqtrade.freqtradebot - INFO - Starting freqtrade 2022.5
2022-05-31 09:16:04,205 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy ClientHedge from '/freqtrade/user_data/strategies/client_hedge.py'...
2022-05-31 09:16:04,209 - freqtrade.strategy.hyper - INFO - Found no parameter file.
2022-05-31 09:16:04,210 - freqtrade.strategy.hyper - INFO - No params for buy found, using default values.
2022-05-31 09:16:04,317 - freqtrade.strategy.hyper - INFO - No params for sell found, using default values.
2022-05-31 09:16:04,319 - freqtrade.strategy.hyper - INFO - No params for protection found, using default values.
2022-05-31 09:16:04,321 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2022-05-31 09:16:04,322 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 100.
2022-05-31 09:16:04,323 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}.
2022-05-31 09:16:04,324 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'60': 0.01, '30': 0.02, '0': 0.04}
2022-05-31 09:16:04,325 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 5m
2022-05-31 09:16:04,325 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.1
2022-05-31 09:16:04,327 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2022-05-31 09:16:04,328 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2022-05-31 09:16:04,328 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2022-05-31 09:16:04,329 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2022-05-31 09:16:04,330 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: True
2022-05-31 09:16:04,331 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'entry': 'limit', 'exit': 'limit', 'stoploss': 'market', 'stoploss_on_exchange': False}
2022-05-31 09:16:04,332 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'entry': 'gtc', 'exit': 'gtc'}
2022-05-31 09:16:04,333 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2022-05-31 09:16:04,334 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 100
2022-05-31 09:16:04,335 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2022-05-31 09:16:04,336 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 0
2022-05-31 09:16:04,337 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}
2022-05-31 09:16:04,338 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_exit_signal: True
2022-05-31 09:16:04,339 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_only: False
2022-05-31 09:16:04,339 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_entry_signal: False
2022-05-31 09:16:04,340 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_offset: 0.0
2022-05-31 09:16:04,341 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2022-05-31 09:16:04,342 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2022-05-31 09:16:04,343 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: False
2022-05-31 09:16:04,344 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1
2022-05-31 09:16:04,345 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2022-05-31 09:16:04,351 - freqtrade.exchange.exchange - INFO - Using CCXT 1.83.62
2022-05-31 09:16:04,353 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'future'}}
2022-05-31 09:16:04,373 - freqtrade.exchange.exchange - INFO - Enabled Sandbox API on binance
2022-05-31 09:16:04,375 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'future'}}
2022-05-31 09:16:04,394 - freqtrade.exchange.exchange - INFO - Enabled Sandbox API on binance
2022-05-31 09:16:04,395 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2022-05-31 09:16:04,396 - freqtrade.exchange.exchange - ERROR - Unable to initialize markets.
Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/exchange.py", line 469, in _load_markets
    self._markets = self._api.load_markets()
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 1628, in load_markets
    currencies = self.fetch_currencies()
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/binance.py", line 1276, in fetch_currencies
    response = self.sapiGetCapitalConfigGetall(params)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 498, in inner
    return entry(_self, **inner_kwargs)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/binance.py", line 5112, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 544, in fetch2
    request = self.sign(path, api, method, params, headers, body)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/binance.py", line 4980, in sign
    raise NotSupported(self.id + ' does not have a testnet/sandbox URL for ' + api + ' endpoints')
ccxt.base.errors.NotSupported: binance does not have a testnet/sandbox URL for sapi endpoints
2022-05-31 09:16:04,401 - freqtrade.commands.trade_commands - ERROR - Could not load markets, therefore cannot start. Please investigate the above error for more details.
2022-05-31 09:16:04,402 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/freqtrade/freqtrade/worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/freqtrade/freqtrade/freqtradebot.py", line 68, in __init__
    self.exchange = ExchangeResolver.load_exchange(self.config['exchange']['name'], self.config)
  File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 32, in load_exchange
    exchange = ExchangeResolver._load_exchange(exchange_name,
  File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 54, in _load_exchange
    exchange = ex_class(**kwargs)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 184, in __init__
    self.validate_stakecurrency(config['stake_currency'])
  File "/freqtrade/freqtrade/exchange/exchange.py", line 504, in validate_stakecurrency
    raise OperationalException(
freqtrade.exceptions.OperationalException: Could not load markets, therefore cannot start. Please investigate the above error for more details.

**Comment by n8an** [comment]
There are only two relevant and similar issues I have found, but their solutions did not result in any change for me.

**Comment by xmatthias** [comment]
The only really relevant issue is in the ccxt repository (https://github.com/ccxt/ccxt/issues/10033).

You should be able to use that approach (provide it in `ccxt_config` in the configuration) to disable fetchCurrencies.

It should however also be noted that test-nets are usually not worth the effort unless you're working on some new, experimental API endpoint integration.
they do not behave like real markets at all, and can really only be used to validate API integration - but not the strategy itself (it behaves differently, orders don't fill or fill at insane prices).

Freqtrade offers dry-mode - which is made to allow you to test a strategy in "real" settings.

**Comment by n8an** [comment]
Thanks, I'm not testing any strategies.
I just need to experiment with how would I go about using FreqTrade to:
1) Create a (semi) forced limit order, not market, long/short, from a telegram manual price input (or a function that at the start of a bot tries to immediately get into position in a specified coin pair but not with a market order but a limit order);
2) Based on the manual first order described above ^ create and place many other limit buys and sells at the same time with hedge mode around it;
3) Have it all work and run on a server

So far I've had trouble with understanding how could I setup the first two steps.
And ofc the binance testnet for futures being dumb.

I would really appreciate it if you could help me out with this.
If necessary I can create a different question based issue.

**Comment by xmatthias** [comment]
Best use freqUI, which will allow you to specify more options for entries (price, stake, volume). If you use limit, you can specify any price (above/below current price) - and depending on that - market will take care of filling.

These options are intentionally not exposed via teleram, as it'd be problematic to get right on a phone.

Freqtrade will only have one order per pair open at any time - so your 2nd point will not be possible.

**Comment by n8an** [comment]
Wait, why isn't it possible to open multiple orders per pair?
Binance has implemented Hedge Mode in 2020, so that it would be possible to open trades on both sides.
And if it's not possible, I'm interested in how to make this happen?
Because I really need to be able to place multiple limit buys and sells based on the first trade price I manually put in!
Also I saw that it's possible to use force trade with telegram.
Could I just make other limit buys be based on the price of the first force buy/sell that I make through telegram?

**Comment by xmatthias** [comment]
It'd be quite a big change to freqtrade. one that MAY be comming in the future, but surely not soon.

if you're not very familiar with the codebase already - i dont think it's something that can be done easily - as it requires severe changes to quite some things.

As such - freqtrade is not a grid bot - nor can it do hedged trades (not on the same pair, anyway).

**Comment by n8an** [comment]
Do you know of any tools that can?
Does CCXT even support it?
I just really need to implement this functionality in my project on freqtrade, because it's already easy to deploy on a server with docker, and supports telegram.
I would even pay for it at this point.

**Comment by xmatthias** [comment]
i guess raw ccxt will support that, but freqtrade won't (the assumption of "one open order per trade" is currently too deep in the codebase to easily change this).

It's all a question of time, obviously - so with time - it'll most likely be changed - but in open source - that depends on peoples time, interests - and their spare time to spend on a project like freqtrade.

**Comment by n8an** [comment]
I get it. Thanks for the answers.
I guess I'll try to make a strategy that does basically the same, but with market orders, so that there's always only one trade open.
And for "semi" hedging I could use a different usd equivalent pair for shorts.
But it's probably gonna be difficult to implement reading the existence and status of other trades to know where to put another one, using freqtrade that is.

**Comment by fedebld** [comment]
(SOLVED)
To run ccxt freqtrade in sandbox mode i edited /freqtrade/exchange/exchange.py in this way in order to use binance testnet:

```
def set_sandbox(self, api: [ccxt.Exchange](https://ccxt.exchange/), exchange_config: dict, name: str) -> None:
        if exchange_config.get('sandbox'):
            api.set_sandbox_mode(True)

            #  FOLLOW THE ORIGINAL CODE
            # if api.urls.get('test'):
            #     api.urls['api'] = api.urls['test']
            #     [logger.info](https://logger.info/)("Enabled Sandbox API on %s", name)
            # else:
            #     logger.warning(
            #         f"No Sandbox URL in CCXT for {name}, exiting. Please check your config.json")
            #     raise OperationalException(f'Exchange {name} does not provide a sandbox api')
```

**Comment by stash86** [comment]
> (SOLVED) To run ccxt freqtrade in sandbox mode i edited /freqtrade/exchange/exchange.py in this way in order to use binance testnet:
> 
> ```
> def set_sandbox(self, api: [ccxt.Exchange](https://ccxt.exchange/), exchange_config: dict, name: str) -> None:
>         if exchange_config.get('sandbox'):
>             api.set_sandbox_mode(True)
> 
>             #  FOLLOW THE ORIGINAL CODE
>             # if api.urls.get('test'):
>             #     api.urls['api'] = api.urls['test']
>             #     [logger.info](https://logger.info/)("Enabled Sandbox API on %s", name)
>             # else:
>             #     logger.warning(
>             #         f"No Sandbox URL in CCXT for {name}, exiting. Please check your config.json")
>             #     raise OperationalException(f'Exchange {name} does not provide a sandbox api')
> ```

1. Don't revive old closed issue
2. Freqtrade has dry-run mode which is same to sandbox mode, but with more advantages, like more history candles available. You don't need to use sandbox mode
