### ISSUE TITLE
ImportError: cannot import name 'ROUND_DOWN' from 'ccxt'

### ISSUE THREAD

**Issue by maros-ross99** [freqtrade/freqtrade#6922]
## Describe your environment

  * Operating system: Ubuntu 22.04
  * Python Version: 3.10.4
  * CCXT version: 1.80.61
  * Freqtrade Version: 2022.5 or 2022.5.1
  
## Describe the problem:

Freqtrade shows the error ``ImportError: cannot import name 'ROUND_DOWN' from 'ccxt'``

### Steps to reproduce:

  1. Update Freqtrade to 2022.5 or 2022.5.1
  2. Run the command freqtrade download-data --config user_data/config_binance.json --day 30 -t 1m 5m 15m 30m 1h 2h 4h 1d
  
### Observed Results:

  * What happened? Freqtrade shows the error ``ImportError: cannot import name 'ROUND_DOWN' from 'ccxt'``
  * What did you expect to happen? Successful execution of the command

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
freqtrade download-data --config user_data/config_binance.json --day 30 -t 1m 5m 15m 30m 1h 2h 4h 1d
Traceback (most recent call last):
  File "/home/user/work/freqtrade/.env/bin/freqtrade", line 33, in <module>
    sys.exit(load_entry_point('freqtrade', 'console_scripts', 'freqtrade')())
  File "/home/user/work/freqtrade/.env/bin/freqtrade", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/user/work/freqtrade/freqtrade/main.py", line 15, in <module>
    from freqtrade.commands import Arguments
  File "/home/user/work/freqtrade/freqtrade/commands/__init__.py", line 10, in <module>
    from freqtrade.commands.build_config_commands import start_new_config
  File "/home/user/work/freqtrade/freqtrade/commands/build_config_commands.py", line 8, in <module>
    from freqtrade.configuration.directory_operations import chown_user_directory
  File "/home/user/work/freqtrade/freqtrade/configuration/__init__.py", line 3, in <module>
    from freqtrade.configuration.check_exchange import check_exchange
  File "/home/user/work/freqtrade/freqtrade/configuration/check_exchange.py", line 6, in <module>
    from freqtrade.exchange import (available_exchanges, is_exchange_known_ccxt,
  File "/home/user/work/freqtrade/freqtrade/exchange/__init__.py", line 4, in <module>
    from freqtrade.exchange.exchange import Exchange
  File "/home/user/work/freqtrade/freqtrade/exchange/exchange.py", line 19, in <module>
    from ccxt import ROUND_DOWN, ROUND_UP, TICK_SIZE, TRUNCATE, Precise, decimal_to_precision
ImportError: cannot import name 'ROUND_DOWN' from 'ccxt' (/home/user/work/freqtrade/.env/lib/python3.10/site-packages/ccxt/__init__.py)

  ```

**Comment by maros-ross99** [comment]
Resolved by updating CCTX to v1.84 inside env since updating it through the global pip didn't update it.
