### ISSUE TITLE
ftx {"error":"Not logged in","success":false}

### ISSUE THREAD

**Issue by Mohit2401** [freqtrade/freqtrade#6923]
## Describe your environment

  * Operating system: ____windows server 2019
  * Python Version: _____ 3.10.4
  * CCXT version: _____ 1.83.62
  * Freqtrade Version: ____ freqtrade develop
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*
getting error:
authencation error, invalid api

i changed the api and secret key twice
same error
also many cryto not identifying
i tried SHIB/BTC not recognized

### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
  *  it not working on live trade when turned dry to false
  * 
  * What did you expect to happen?
  * it will run on live server
  * should recognize al crypto as in exchange

### Relevant code exceptions or logs
 it not working on live trade when turned dry to false

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
 ftuser@b89d29f7f8a4:/workspaces/ft_userdata$ freqtrade trade --strategy BBandsRSI 
2022-06-02 03:19:59,129 - freqtrade.worker - INFO - Starting worker develop
2022-06-02 03:19:59,129 - freqtrade.configuration.load_config - INFO - Using config: user_data/config.json ...
2022-06-02 03:19:59,134 - freqtrade.loggers - INFO - Verbosity set to 0
2022-06-02 03:19:59,134 - freqtrade.configuration.configuration - INFO - Runmode set to live.
2022-06-02 03:19:59,134 - freqtrade.configuration.configuration - INFO - Dry run is disabled
2022-06-02 03:19:59,134 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:///tradesv3.sqlite"
2022-06-02 03:19:59,134 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 16 ...
2022-06-02 03:19:59,408 - freqtrade.configuration.configuration - INFO - Using user-data directory: /workspaces/ft_userdata/user_data ...
2022-06-02 03:19:59,408 - freqtrade.configuration.configuration - INFO - Using data directory: /workspaces/ft_userdata/user_data/data/ftx ...
2022-06-02 03:19:59,408 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2022-06-02 03:19:59,419 - freqtrade.configuration.check_exchange - INFO - Exchange "ftx" is officially supported by the Freqtrade development team.
2022-06-02 03:19:59,420 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2022-06-02 03:19:59,420 - freqtrade.freqtradebot - INFO - Starting freqtrade develop
2022-06-02 03:19:59,609 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy BBandsRSI from '/workspaces/ft_userdata/user_data/strategies/BBandsRSI.py'...
2022-06-02 03:19:59,610 - freqtrade.strategy.hyper - INFO - Found no parameter file.
2022-06-02 03:19:59,610 - freqtrade.strategy.hyper - INFO - No params for buy found, using default values.
2022-06-02 03:19:59,611 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): buy_rsi = 30
2022-06-02 03:19:59,611 - freqtrade.strategy.hyper - INFO - No params for sell found, using default values.
2022-06-02 03:19:59,611 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): sell_rsi = 70
2022-06-02 03:19:59,611 - freqtrade.strategy.hyper - INFO - No params for protection found, using default values.
2022-06-02 03:19:59,612 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 5m.
2022-06-02 03:19:59,612 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: BTC.
2022-06-02 03:19:59,612 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: unlimited.
2022-06-02 03:19:59,612 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'entry': 10, 'exit': 30, 'exit_timeout_count': 0, 'unit': 'minutes'}.
2022-06-02 03:19:59,613 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 0.2}
2022-06-02 03:19:59,613 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 5m
2022-06-02 03:19:59,613 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.15
2022-06-02 03:19:59,613 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2022-06-02 03:19:59,613 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2022-06-02 03:19:59,613 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2022-06-02 03:19:59,613 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2022-06-02 03:19:59,613 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: True
2022-06-02 03:19:59,614 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'entry': 'limit', 'exit': 'limit', 'stoploss': 'market', 'stoploss_on_exchange': False}
2022-06-02 03:19:59,614 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'entry': 'gtc', 'exit': 'gtc'}
2022-06-02 03:19:59,614 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: BTC
2022-06-02 03:19:59,614 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: unlimited
2022-06-02 03:19:59,614 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2022-06-02 03:19:59,614 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 30
2022-06-02 03:19:59,614 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'entry': 10, 'exit': 30, 'exit_timeout_count': 0, 'unit': 'minutes'}
2022-06-02 03:19:59,614 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_exit_signal: True
2022-06-02 03:19:59,614 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_only: False
2022-06-02 03:19:59,614 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_entry_signal: False
2022-06-02 03:19:59,615 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_offset: 0.0
2022-06-02 03:19:59,615 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2022-06-02 03:19:59,615 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2022-06-02 03:19:59,615 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: False
2022-06-02 03:19:59,615 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1
2022-06-02 03:19:59,615 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2022-06-02 03:19:59,625 - freqtrade.exchange.exchange - INFO - Using CCXT 1.83.62
2022-06-02 03:19:59,643 - freqtrade.exchange.exchange - INFO - Using Exchange "FTX"
2022-06-02 03:20:00,110 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Ftx'...
2022-06-02 03:20:00,773 - freqtrade.exchange.common - WARNING - get_balances() returned exception: "Could not get balance due to AuthenticationError. Message: ftx {"success":false,"error":"Not logged in: Invalid API key"}". Retrying still for 4 times.
2022-06-02 03:20:00,991 - freqtrade.exchange.common - WARNING - get_balances() returned exception: "Could not get balance due to AuthenticationError. Message: ftx {"success":false,"error":"Not logged in: Invalid API key"}". Retrying still for 3 times.
2022-06-02 03:20:01,205 - freqtrade.exchange.common - WARNING - get_balances() returned exception: "Could not get balance due to AuthenticationError. Message: ftx {"success":false,"error":"Not logged in: Invalid API key"}". Retrying still for 2 times.
2022-06-02 03:20:01,413 - freqtrade.exchange.common - WARNING - get_balances() returned exception: "Could not get balance due to AuthenticationError. Message: ftx {"success":false,"error":"Not logged in: Invalid API key"}". Retrying still for 1 times.
2022-06-02 03:20:01,624 - freqtrade.exchange.common - WARNING - get_balances() returned exception: "Could not get balance due to AuthenticationError. Message: ftx {"success":false,"error":"Not logged in: Invalid API key"}". Giving up.
2022-06-02 03:20:01,624 - freqtrade.commands.trade_commands - ERROR - Could not get balance due to AuthenticationError. Message: ftx {"success":false,"error":"Not logged in: Invalid API key"}
2022-06-02 03:20:01,625 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 658, in fetch
    response.raise_for_status()
  File "/home/ftuser/.local/lib/python3.10/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://ftx.com/api/wallet/balances

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/exchange.py", line 1300, in get_balances
    balances = self._api.fetch_balance()
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/ftx.py", line 1288, in fetch_balance
    response = self.privateGetWalletBalances(params)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 498, in inner
    return entry(_self, **inner_kwargs)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 549, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 545, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 674, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/ftx.py", line 2392, in handle_errors
    self.throw_broadly_matched_exception(self.exceptions['broad'], error, feedback)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 568, in throw_broadly_matched_exception
    raise broad[broad_key](message)
ccxt.base.errors.AuthenticationError: ftx {"success":false,"error":"Not logged in: Invalid API key"}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/common.py", line 157, in wrapper
    return f(*args, **kwargs)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 1311, in get_balances
    raise TemporaryError(
freqtrade.exceptions.TemporaryError: Could not get balance due to AuthenticationError. Message: ftx {"success":false,"error":"Not logged in: Invalid API key"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 658, in fetch
    response.raise_for_status()
  File "/home/ftuser/.local/lib/python3.10/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://ftx.com/api/wallet/balances

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/exchange.py", line 1300, in get_balances
    balances = self._api.fetch_balance()
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/ftx.py", line 1288, in fetch_balance
    response = self.privateGetWalletBalances(params)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 498, in inner
    return entry(_self, **inner_kwargs)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 549, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 545, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 674, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/ftx.py", line 2392, in handle_errors
    self.throw_broadly_matched_exception(self.exceptions['broad'], error, feedback)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 568, in throw_broadly_matched_exception
    raise broad[broad_key](message)
ccxt.base.errors.AuthenticationError: ftx {"success":false,"error":"Not logged in: Invalid API key"}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/common.py", line 157, in wrapper
    return f(*args, **kwargs)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 1311, in get_balances
    raise TemporaryError(
freqtrade.exceptions.TemporaryError: Could not get balance due to AuthenticationError. Message: ftx {"success":false,"error":"Not logged in: Invalid API key"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 658, in fetch
    response.raise_for_status()
  File "/home/ftuser/.local/lib/python3.10/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://ftx.com/api/wallet/balances

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/exchange.py", line 1300, in get_balances
    balances = self._api.fetch_balance()
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/ftx.py", line 1288, in fetch_balance
    response = self.privateGetWalletBalances(params)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 498, in inner
    return entry(_self, **inner_kwargs)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 549, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 545, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 674, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/ftx.py", line 2392, in handle_errors
    self.throw_broadly_matched_exception(self.exceptions['broad'], error, feedback)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 568, in throw_broadly_matched_exception
    raise broad[broad_key](message)
ccxt.base.errors.AuthenticationError: ftx {"success":false,"error":"Not logged in: Invalid API key"}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/common.py", line 157, in wrapper
    return f(*args, **kwargs)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 1311, in get_balances
    raise TemporaryError(
freqtrade.exceptions.TemporaryError: Could not get balance due to AuthenticationError. Message: ftx {"success":false,"error":"Not logged in: Invalid API key"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 658, in fetch
    response.raise_for_status()
  File "/home/ftuser/.local/lib/python3.10/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://ftx.com/api/wallet/balances

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/exchange.py", line 1300, in get_balances
    balances = self._api.fetch_balance()
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/ftx.py", line 1288, in fetch_balance
    response = self.privateGetWalletBalances(params)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 498, in inner
    return entry(_self, **inner_kwargs)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 549, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 545, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 674, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/ftx.py", line 2392, in handle_errors
    self.throw_broadly_matched_exception(self.exceptions['broad'], error, feedback)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 568, in throw_broadly_matched_exception
    raise broad[broad_key](message)
ccxt.base.errors.AuthenticationError: ftx {"success":false,"error":"Not logged in: Invalid API key"}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/common.py", line 157, in wrapper
    return f(*args, **kwargs)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 1311, in get_balances
    raise TemporaryError(
freqtrade.exceptions.TemporaryError: Could not get balance due to AuthenticationError. Message: ftx {"success":false,"error":"Not logged in: Invalid API key"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 658, in fetch
    response.raise_for_status()
  File "/home/ftuser/.local/lib/python3.10/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://ftx.com/api/wallet/balances

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/exchange.py", line 1300, in get_balances
    balances = self._api.fetch_balance()
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/ftx.py", line 1288, in fetch_balance
    response = self.privateGetWalletBalances(params)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 498, in inner
    return entry(_self, **inner_kwargs)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 549, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 545, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 674, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/ftx.py", line 2392, in handle_errors
    self.throw_broadly_matched_exception(self.exceptions['broad'], error, feedback)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 568, in throw_broadly_matched_exception
    raise broad[broad_key](message)
ccxt.base.errors.AuthenticationError: ftx {"success":false,"error":"Not logged in: Invalid API key"}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/freqtrade/freqtrade/worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/freqtrade/freqtrade/freqtradebot.py", line 72, in __init__
    self.wallets = Wallets(self.config, self.exchange)
  File "/freqtrade/freqtrade/wallets.py", line 46, in __init__
    self.update()
  File "/freqtrade/freqtrade/wallets.py", line 170, in update
    self._update_live()
  File "/freqtrade/freqtrade/wallets.py", line 128, in _update_live
    balances = self._exchange.get_balances()
  File "/freqtrade/freqtrade/exchange/common.py", line 169, in wrapper
    return wrapper(*args, **kwargs)
  File "/freqtrade/freqtrade/exchange/common.py", line 169, in wrapper
    return wrapper(*args, **kwargs)
  File "/freqtrade/freqtrade/exchange/common.py", line 169, in wrapper
    return wrapper(*args, **kwargs)
  [Previous line repeated 1 more time]
  File "/freqtrade/freqtrade/exchange/common.py", line 172, in wrapper
    raise ex
  File "/freqtrade/freqtrade/exchange/common.py", line 157, in wrapper
    return f(*args, **kwargs)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 1311, in get_balances
    raise TemporaryError(
freqtrade.exceptions.TemporaryError: Could not get balance due to AuthenticationError. Message: ftx {"success":false,"error":"Not logged in: Invalid API key"}

**Comment by Mohit2401** [comment]
getting this error
freqtrade.exceptions.TemporaryError: Could not get balance due to AuthenticationError. Message: ftx {"success":false,"error":"Not logged in: Invalid API key"}

**Comment by xmatthias** [comment]
> `Not logged in: Invalid API key`

well the error is very clear - you're not logged in (so your api key is invalid).
There's no magic or hidden knowledge behind that error - it's simply what it says it is.

Please make sure that the keys are pasted correctly (no whitespace before/after, ...), that eventual IP whitelists actually cover your IP, ...).


on FTX Specifically, if your key is only valid for a subaccount, you'll have to [configure freqtrade for this](https://www.freqtrade.io/en/stable/exchanges/#using-subaccounts) - otherwise you may get that error (as the key is invalid for the main account).

**Comment by Mohit2401** [comment]
i entered the api correctly also 
changed it
it says same error

**Comment by Mohit2401** [comment]
"exchange": {
         
        "name": "ftx",
        "key": "",
        "secret": ""
       
        "ccxt_config": {
            "headers": {
                "FTX-SUBACCOUNT": "mm"
            }
           
        },        "ccxt_async_config": {},
        "pair_whitelist": [  ],
        "pair_blacklist": [ ]
    }

**Comment by xmatthias** [comment]
The error is quite specific - the API key does not work.

The subaccount- config itself seems correct - if the API key were valid but for a different subaccount, then the error would be `{"success":false,"error":"Only have permissions for subaccount XXX"}`.

as the error is a generic "invalid" - the only conclusion is that the API key is invalid itself (maybe key/secret is swapped) - or that it's restricted to an IP address which is not the one you use it from.

**Comment by xmatthias** [comment]
I'll close this now assuming you've been able to get this working.

Feel free to comment below if that's not the case (i'm however unsure how we can help here - as the message is simply "invalid api key". 

The only way to help further would be to have the API keys available to do some tests - but i'm asking you explicitly to NEVER share your API keys with anyone (not with me, not with anyone else).
