### ISSUE TITLE
ERROR - 'stopPrice' - KeyError: 'stopPrice'

### ISSUE THREAD

**Issue by FlockrushAdmin** [freqtrade/freqtrade#6996]
## Describe your environment

  * Operating system: macos Big Sur 11.2.3
  * Python Version: Python 3.9.7
  * CCXT version: ccxt==1.84.39
  * Freqtrade Version: develop-7fe8b7661
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

Process died

### Steps to reproduce:

Set the following in the strategy:

    trailing_stop = True
    trailing_stop_positive = 0.04
  
### Observed Results:

Set trailing stop loss and the process died. 

    trailing_stop = True
    trailing_stop_positive = 0.04

### Relevant code exceptions or logs

{'id': 'dry_run_sell_1655828271.818892', 'symbol': 'JASMY/USDT', 'price': 0.009729, 'average': 0.009729, 'amount': 180178.5, 'cost': 1752.9566264999999, 'type': 'stop_loss_limit', 'side': 'stoploss', 'filled': 0.0, 'remaining': 180178.5, 'datetime': '2022-06-21T16:17:51.000000', 'timestamp': 1655828271000, 'status': 'open', 'fee': None, 'info': {}}
2022-06-21 12:46:40,284 - freqtrade.commands.trade_commands - ERROR - 'stopPrice'
  File "/Users/surfer/Software/MMM/develop/freqtrade/freqtrade/freqtradebot.py", line 911, in exit_positions
    self.handle_stoploss_on_exchange(trade)):
  File "/Users/surfer/Software/MMM/develop/freqtrade/freqtrade/freqtradebot.py", line 1081, in handle_stoploss_on_exchange
    self.handle_trailing_stoploss_on_exchange(trade, stoploss_order)
  File "/Users/surfer/Software/MMM/develop/freqtrade/freqtrade/freqtradebot.py", line 1095, in handle_trailing_stoploss_on_exchange
    if self.exchange.stoploss_adjust(stoploss_norm, order, side=trade.exit_side):
  File "/Users/surfer/Software/MMM/develop/freqtrade/freqtrade/exchange/binance.py", line 56, in stoploss_adjust
    (side == "sell" and stop_loss > float(order['stopPrice'])) or
KeyError: 'stopPrice'

**Comment by xmatthias** [comment]
live ? dry ? 

7fe8b7661 is not a version i know (it's a git commit - searching for this does not work).

assuming it's something recent (i made this change only recently) - then your ccxt version is clearly outdated. please make sure to follow the [updating documentation](https://www.freqtrade.io/en/latest/updating/) - to have dependencies update as well.

if it still doesn't work with an uptodate version (and assuming this is live) - then please enable exchange message logging (exchange.log_responses = true in the config) - and send me the message right before the error.

**Comment by FlockrushAdmin** [comment]
Thank you Matthias. 

It is the older version of ccxt. Updated it and started the process. Will close the issue after a few hours of running.

**Comment by FlockrushAdmin** [comment]
Updated to latest version: develop-3a0f31f and reinstalled. Same KeyError error :( 

Operating system: macos Big Sur 11.2.3
Python Version: Python 3.9.7
CCXT version: ccxt==1.87.12
Freqtrade Version: develop-3a0f31f

Log: 

2022-06-21 14:12:31,510 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/Users/surfer/Software/MMM/develop/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker.run()
  File "/Users/surfer/Software/MMM/develop/freqtrade/freqtrade/worker.py", line 74, in run
    state = self._worker(old_state=state)
  File "/Users/surfer/Software/MMM/develop/freqtrade/freqtrade/worker.py", line 114, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
  File "/Users/surfer/Software/MMM/develop/freqtrade/freqtrade/worker.py", line 139, in _throttle
    result = func(*args, **kwargs)
  File "/Users/surfer/Software/MMM/develop/freqtrade/freqtrade/worker.py", line 152, in _process_running
    self.freqtrade.process()
  File "/Users/surfer/Software/MMM/develop/freqtrade/freqtrade/freqtradebot.py", line 203, in process
    self.exit_positions(trades)
  File "/Users/surfer/Software/MMM/develop/freqtrade/freqtrade/freqtradebot.py", line 920, in exit_positions
    self.handle_stoploss_on_exchange(trade)):
  File "/Users/surfer/Software/MMM/develop/freqtrade/freqtrade/freqtradebot.py", line 1089, in handle_stoploss_on_exchange
    self.handle_trailing_stoploss_on_exchange(trade, stoploss_order)
  File "/Users/surfer/Software/MMM/develop/freqtrade/freqtrade/freqtradebot.py", line 1103, in handle_trailing_stoploss_on_exchange
    if self.exchange.stoploss_adjust(stoploss_norm, order, side=trade.exit_side):
  File "/Users/surfer/Software/MMM/develop/freqtrade/freqtrade/exchange/binance.py", line 56, in stoploss_adjust
    (side == "sell" and stop_loss > float(order['stopPrice'])) or
KeyError: 'stopPrice'
2022-06-21 14:12:31,514 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit

**Comment by FlockrushAdmin** [comment]
It's dry run, would you like me to delete the data and start fresh? It could be a regression issue with older trades orders.

**Comment by xmatthias** [comment]
i'll look into it (wasn't clear that it's dry run).

it should be sufficient to delete the order from the orders table (just loo for ft_is_open). i'll try to have a fix tomorrow morning - but it's not as quick as i'd like (and i'm not 100% sure it'll back-port reliably).
