### ISSUE TITLE
How to use informative pairs in both hyperopt and backtest

### ISSUE THREAD

**Issue by pizzidellamaremma** [freqtrade/freqtrade#7001]
* Operating system: Windows, Python venv
  * Python Version: 3.9.10
  * CCXT version: 1.79.81
  * Freqtrade Version: freqtrade develop (not the latest version)
  
I need to use informative pairs, elaborate it and then pass it to every single dataframe inside `populate_indicators`.
If I use `bot_loop_start` it doesn't work in hyperopt (the attribute for the dataframe doesn't exist) and in backtest is having problem merging the two dataframes in `populate_indicators`.
At the moment I made it works by using a function `mc_informative_pairs` and calling it from `populate_indicators` but this reload all the informative data every ticker, and I want to avoid it.

```
class NF_Strategy_B1(IStrategy):
    can_short = False
    exit_profit_only=False
    startup_candle_count = 100
    enter_params={'space':'buy','optimize':'True'}
    ent_csrrsi_enabled = BooleanParameter(default=True, optimize=False, space='buy')
    ent_csr_smooth = IntParameter(2, 20, default=5, **enter_params)
    ent_rsi_smooth = IntParameter(2, 20, default=5, **enter_params)
    ent_csr_ind = DecimalParameter(-5, 5, default=0, **enter_params)
    ent_rsi_ind = DecimalParameter(-5, 5, default=0, **enter_params)
    mc_ent_twroc_enabled = BooleanParameter(default=True, **enter_params)
    mc_ent_twroc_smooth = IntParameter(2, 20, default=2, **enter_params)
    mc_ent_twroc_slope_ind = DecimalParameter(-1.7, 1.7, default=0, **enter_params)
    exit_params={'space':'sell','optimize':'True'}
    ext_csrrsi_enabled = BooleanParameter(default=True, optimize=False, space='sell')
    ext_csr_smooth = IntParameter(2, 20, default=5, **exit_params)
    ext_rsi_smooth = IntParameter(2, 20, default=5, **exit_params)
    ext_csr_ind = DecimalParameter(-5, 5, default=0, **exit_params)
    ext_rsi_ind = DecimalParameter(-5, 5, default=0, **exit_params)
    mc_ext_twroc_enabled = BooleanParameter(default=True, optimize=False, space='sell')
    mc_ext_twroc_smooth = IntParameter(2, 20, default=2, **exit_params)
    mc_ext_twroc_slope_ind = DecimalParameter(-1.7, 1.7, default=0, **exit_params)

    def informative_pairs(self):
        # def list of symbols
        self.mc_symbols = ["BTC", "ETH", "SHIB", "ADA", "MLN"]
        self.mc_tf = "1m"
        stake = "USDT"
        informative_pairs = [(f'{symbol}/{stake}', self.mc_tf) for symbol in self.mc_symbols]
        return informative_pairs

    def bot_loop_start(self, **kwargs) -> None:
        self.mc_dataframe = self.mc_informative_pairs()

    def mc_informative_pairs(self) -> pd.DataFrame:
        mc_df = None
        dataframe = None
        for pair in self.informative_pairs():
            dummy = self.dp.get_pair_dataframe(*pair)
            if mc_df is None:
                mc_df = pd.DataFrame(dummy['date'], columns={'date'})
            mc_df[f"ind_close_{pair[0]}"] = normalize(dummy["close"])
            mc_df[f"ind_vol_{pair[0]}"] = normalize(dummy["volume"])

        if dataframe is None:
            dataframe = pd.DataFrame(dummy['date'], columns={'date'})
        del dummy

        dataframe['mc_close'] = mc_df.filter(regex="ind_close.*", axis=1).mean(axis=1)
        dataframe['mc_volume'] = mc_df.filter(regex="ind_vol.*", axis=1).mean(axis=1)
        del mc_df
        return dataframe

    def populate_indicators(self, dataframe: pd.DataFrame, metadata: dict) -> pd.DataFrame:
        # timeframe = 1

        if self.ent_csrrsi_enabled.value:
            dataframe['csr'] = (
                TA.RSI(slope(dataframe['close'], smooth=self.ent_csr_smooth.value),timeperiod=self.ent_csr_smooth.value)/50)-1
            dataframe['rsi'] = (
                TA.RSI(dataframe['close'],timeperiod=self.ent_rsi_smooth.value)/50)-1

        if self.ext_csrrsi_enabled.value:
            dataframe['csr'] = (
                TA.RSI(slope(dataframe['close'], smooth=self.ext_csr_smooth.value),timeperiod=self.ext_csr_smooth.value)/50)-1
            dataframe['rsi'] = (
                TA.RSI(dataframe['close'],timeperiod=self.ext_rsi_smooth.value)/50)-1

        mc_dataframe = self.mc_informative_pairs()
        dataframe = merge_informative_pair(dataframe, mc_dataframe, self.timeframe, self.mc_tf, ffill=True)
        dataframe.rename(columns={f'mc_close_{self.mc_tf}':'mc_close', f'mc_vol_{self.mc_tf}':'mc_vol'}, inplace=True)

        ### ENTER PART
        dataframe['mc_ent_twroc'], dataframe['mc_ent_twroc_slope'] = (
            Custom.twroc(dataframe['mc_close'], sma_smooth=self.mc_ent_twroc_smooth.value))

        ### EXIT PART
        dataframe['mc_ext_twroc'], dataframe['mc_ext_twroc_slope'] = (
            Custom.twroc(dataframe['mc_close'], sma_smooth=self.mc_ext_twroc_smooth.value))

        return dataframe

    def populate_entry_trend(self, dataframe: pd.DataFrame, metadata: dict) -> pd.DataFrame:

        conditions = []
        if self.ent_csrrsi_enabled.value:
            conditions.append(
                dataframe['csr'] < self.ent_csr_ind.value)
            conditions.append(
                dataframe['rsi'] < self.ent_rsi_ind.value)
        # protection
        if self.mc_ent_twroc_enabled.value:
            conditions.append(
                    dataframe['mc_ent_twroc_slope'] > self.mc_ent_twroc_slope_ind.value
                )
        if conditions:       # test conditions
            dataframe.loc[
                reduce(lambda x, y: x & y, conditions),
                ['enter_long', 'enter_tag']] = (1, 'csrrsi')

        return dataframe

    def populate_exit_trend(self, dataframe: pd.DataFrame, metadata: dict) -> pd.DataFrame:
        conditions = []
        if self.ext_csrrsi_enabled.value:
            conditions.append(
                dataframe['csr'] > self.ext_csr_ind.value)
            conditions.append(
                dataframe['rsi'] > self.ext_rsi_ind.value)
        if conditions:
            dataframe.loc[
                reduce(lambda x, y: x & y, conditions),
            ['exit_long', 'exit_tag']] = (1, 'csrrsi')

        conditions = []
        if self.mc_ext_twroc_enabled.value:
                conditions.append(
                        dataframe['mc_ext_twroc_slope'] > self.mc_mc_ext_twroc_slope_ind.value)
        if conditions:
            dataframe.loc[
                reduce(lambda x, y: x & y, conditions),
            ['exit_long', 'exit_tag']] = (1, 'mc_twroc_prot')

        return dataframe
```
_______________________________________________________________________________________________________
error in hyperopt:
```
2022-06-26 11:46:22,858 - freqtrade.optimize.hyperopt - INFO - Dataload complete. Calculating indicators
2022-06-26 11:46:22,868 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "C:\freqtrade\.env\lib\site-packages\freqtrade-develop-py3.9.egg\freqtrade\main.py", line 37, in main
    return_code = args['func'](args)
  File "C:\freqtrade\.env\lib\site-packages\freqtrade-develop-py3.9.egg\freqtrade\commands\optimize_commands.py", line 107, in start_hyperopt
    hyperopt.start()
  File "C:\freqtrade\.env\lib\site-packages\freqtrade-develop-py3.9.egg\freqtrade\optimize\hyperopt.py", line 419, in start
    self.prepare_hyperopt_data()
  File "C:\freqtrade\.env\lib\site-packages\freqtrade-develop-py3.9.egg\freqtrade\optimize\hyperopt.py", line 400, in prepare_hyperopt_data
    preprocessed = self.backtesting.strategy.advise_all_indicators(data)
  File "C:\freqtrade\.env\lib\site-packages\freqtrade-develop-py3.9.egg\freqtrade\strategy\interface.py", line 1075, in advise_all_indicators
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "C:\freqtrade\.env\lib\site-packages\freqtrade-develop-py3.9.egg\freqtrade\strategy\interface.py", line 1075, in <dictcomp>
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "C:\freqtrade\.env\lib\site-packages\freqtrade-develop-py3.9.egg\freqtrade\strategy\interface.py", line 1098, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "C:\freqtrade\user_data\strategies\nf_strategy_B1.py", line 146, in populate_indicators
    dataframe = merge_informative_pair(dataframe, self.mc_dataframe, self.timeframe, self.mc_tf, ffill=True)
AttributeError: 'NF_Strategy_B1' object has no attribute 'mc_dataframe'
```
_______________________________________________________________________________________________________
error in backtest:
```
2022-06-26 11:51:43,852 - freqtrade.optimize.backtesting - INFO - Dataload complete. Calculating indicators
2022-06-26 11:51:43,858 - freqtrade.optimize.backtesting - INFO - Running backtesting for Strategy NF_Strategy_B1
2022-06-26 11:51:47,628 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "C:\freqtrade\.env\lib\site-packages\pandas\core\indexes\base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'date'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\freqtrade\.env\lib\site-packages\freqtrade-develop-py3.9.egg\freqtrade\main.py", line 37, in main
    return_code = args['func'](args)
  File "C:\freqtrade\.env\lib\site-packages\freqtrade-develop-py3.9.egg\freqtrade\commands\optimize_commands.py", line 58, in start_backtesting
    backtesting.start()
  File "C:\freqtrade\.env\lib\site-packages\freqtrade-develop-py3.9.egg\freqtrade\optimize\backtesting.py", line 1120, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
  File "C:\freqtrade\.env\lib\site-packages\freqtrade-develop-py3.9.egg\freqtrade\optimize\backtesting.py", line 1041, in backtest_one_strategy
    preprocessed = self.strategy.advise_all_indicators(data)
  File "C:\freqtrade\.env\lib\site-packages\freqtrade-develop-py3.9.egg\freqtrade\strategy\interface.py", line 1075, in advise_all_indicators
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "C:\freqtrade\.env\lib\site-packages\freqtrade-develop-py3.9.egg\freqtrade\strategy\interface.py", line 1075, in <dictcomp>
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "C:\freqtrade\.env\lib\site-packages\freqtrade-develop-py3.9.egg\freqtrade\strategy\interface.py", line 1098, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "C:\freqtrade\user_data\strategies\nf_strategy_B1.py", line 146, in populate_indicators
    dataframe = merge_informative_pair(dataframe, self.mc_dataframe, self.timeframe, self.mc_tf, ffill=True)
  File "C:\freqtrade\.env\lib\site-packages\freqtrade-develop-py3.9.egg\freqtrade\strategy\strategy_helper.py", line 39, in merge_informative_pair
    informative['date_merge'] = informative[date_column]
  File "C:\freqtrade\.env\lib\site-packages\pandas\core\frame.py", line 3505, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\freqtrade\.env\lib\site-packages\pandas\core\indexes\base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 'date'
```
How can I make it works? Is there something I'm missing?

**Comment by xmatthias** [comment]
Well in backtesting, you seem to miss a date column in one of the dataframes.

Now why is then up to the strategy to determine. Maybe plot the columns before the merge, and then work from there backwards.

The hyperopt error im not sure, but its not worth looking at unless backtesting works, as hyperopt is really just running backtesting over and over.

**Comment by pizzidellamaremma** [comment]
I've printed the dataframes before and after... The `merge_informative_pair` function seems to change the informative dataframe, At the second pair cycle self.mc_dataframe doesn't contain "date" but "date_1m". I think the problem starts there.
It's doing it even passing the dataframe to a non self variable from:
```
dataframe = merge_informative_pair(dataframe, self.mc_dataframe, self.timeframe, self.mc_tf, ffill=True)
```
to:
```
mc_dataframe = self.mc_dataframe
dataframe = merge_informative_pair(dataframe, mc_dataframe, self.timeframe, self.mc_tf, ffill=True)
```
Do you know why this function need to modify the informative dataframe? Just curiosity at this point.
I'm backtesting trying to avoid the function, just passing the columns I need to the main dataframe and it seems to work.

Now the error comes from hyperopt:
```
2022-06-27 16:50:02,220 - freqtrade.optimize.hyperopt - INFO - Dataload complete. Calculating indicators
2022-06-27 16:50:02,231 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "C:\freqtrade\.env\lib\site-packages\freqtrade-develop-py3.9.egg\freqtrade\main.py", line 37, in main
    return_code = args['func'](args)
  File "C:\freqtrade\.env\lib\site-packages\freqtrade-develop-py3.9.egg\freqtrade\commands\optimize_commands.py", line 107, in start_hyperopt
    hyperopt.start()
  File "C:\freqtrade\.env\lib\site-packages\freqtrade-develop-py3.9.egg\freqtrade\optimize\hyperopt.py", line 419, in start
    self.prepare_hyperopt_data()
  File "C:\freqtrade\.env\lib\site-packages\freqtrade-develop-py3.9.egg\freqtrade\optimize\hyperopt.py", line 400, in prepare_hyperopt_data
    preprocessed = self.backtesting.strategy.advise_all_indicators(data)
  File "C:\freqtrade\.env\lib\site-packages\freqtrade-develop-py3.9.egg\freqtrade\strategy\interface.py", line 1075, in advise_all_indicators
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "C:\freqtrade\.env\lib\site-packages\freqtrade-develop-py3.9.egg\freqtrade\strategy\interface.py", line 1075, in <dictcomp>
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "C:\freqtrade\.env\lib\site-packages\freqtrade-develop-py3.9.egg\freqtrade\strategy\interface.py", line 1098, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "C:\freqtrade\user_data\strategies\nf_strategy_B1.py", line 151, in populate_indicators
    dataframe['mc_close'] = self.mc_dataframe['mc_close']
AttributeError: 'NF_Strategy_B1' object has no attribute 'mc_dataframe'
```
Now, `self.mc_dataframe` is created by `bot_loop_start`, the only reason `self.mc_dataframe` doesn't exist it's because `bot_loop_start` function is not called. What do you think?

**Comment by xmatthias** [comment]
Merge_informative_pair is designed to merge an informative pair to the main dataframe.
Itll modify the dataframe to rename the columns
The only real alternative would be to take a copy, which is a problem to memory usage depending on where you use it.

I dont really see why youre doing things this way though. That only really makes sense if you have very heavy calculations, which i dont really see in your code.

 Backtesting does cache loaded informative pairs, so theyre not reloaded from disk (which is usually the slowest part) more than once.

---

I'll have to look at hyperopt in detail, its possible that its not called there ... Wont be this week though.

---

on another note: you should be careful with `normalize()`.
Alnost every implementation i've seen about that had implicit lookahead bias by using the full data (e.g. using `.max()`), which will then look great in backtesting, but fails in live.

**Comment by xmatthias** [comment]
Nice spot - `bot_loop_start()` wasn't called in hyperopt mode. This will be changed in a few minutes - and will be available either in the develop branch (basically immediately), or in the next release (due either today or in the next days).
