### ISSUE TITLE
Imput are all NaN 

### ISSUE THREAD

**Issue by Onetwo31** [freqtrade/freqtrade#7039]
Hi, i try to run freqai since a long time. I ever found the same error. -> Imput are all NaN 

I tryed to install it by all way possible and when i try to run it by this command : freqtrade backtesting --config config_freqai_futures.BTC.json --strategy FreqaiExampleStrategy --freqaimodel CatboostPredictionModel --strategy-path freqtrade/templates --timerange 20220501-20220601

i get it :

2022-07-04 03:14:23,035 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/onetwo/freqtradeIA/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/home/onetwo/freqtradeIA/freqtrade/freqtrade/commands/optimize_commands.py", line 58, in start_backtesting
    backtesting.start()
  File "/home/onetwo/freqtradeIA/freqtrade/freqtrade/optimize/backtesting.py", line 1261, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
  File "/home/onetwo/freqtradeIA/freqtrade/freqtrade/optimize/backtesting.py", line 1159, in backtest_one_strategy
    preprocessed = self.strategy.advise_all_indicators(data)
  File "/home/onetwo/freqtradeIA/freqtrade/freqtrade/strategy/interface.py", line 1144, in advise_all_indicators
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "/home/onetwo/freqtradeIA/freqtrade/freqtrade/strategy/interface.py", line 1144, in <dictcomp>
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "/home/onetwo/freqtradeIA/freqtrade/freqtrade/strategy/interface.py", line 1162, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/home/onetwo/freqtradeIA/freqtrade/freqtrade/templates/FreqaiExampleStrategy.py", line 183, in populate_indicators
    dataframe = self.populate_any_indicators(
  File "/home/onetwo/freqtradeIA/freqtrade/freqtrade/templates/FreqaiExampleStrategy.py", line 99, in populate_any_indicators
    informative[f"%-{coin}rsi-period_{t}"] = ta.RSI(informative, timeperiod=t)
  File "talib/_abstract.pxi", line 427, in talib._ta_lib.Function.__call__
  File "talib/_abstract.pxi", line 472, in talib._ta_lib.Function.__call_function
  File "/home/onetwo/freqtradeIA/freqtrade/.env/lib/python3.8/site-packages/talib/__init__.py", line 64, in wrapper
    result = func(*_args, **_kwds)
  File "talib/_func.pxi", line 4377, in talib._ta_lib.RSI
  File "talib/_func.pxi", line 68, in talib._ta_lib.check_begidx1
Exception: inputs are all NaN

The line 183 and 99 correspond to a loop for timeframe.
Someone could help me ?

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

i'd ask you to provide the full log - not just the error itself.
the most likely reason for this is missing data - which would be logged as part of bot startup.

**Comment by Onetwo31** [comment]
Please do not use bug reports to request new features.
--> I can't run the bot, the error message is "Imputs are all NaN 

## Describe your environment

  * Operating system: Ubuntu
  * Python Version: pip 22.1.2 from /home/onetwo/freqtradeIA/freqtrade/.env/lib/python3.8/site-packages/pip (python 3.8)
  * CCXT version: ccxt==1.89.14
  * Freqtrade Version: freqtrade develop-eda9464d3

  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

Impossible to run the bot, i tried all installation process, reduce the number of startup_candle_count to 100, download all data on all timeframe, and reduce the pair to BTC and ETH. I have already the same problem  "imputs are all NaN"

### Steps to reproduce:

  1. git clone https://github.com/freqtrade/freqtrade.git
      cd freqtrade
      ./setup.sh -i
       deactiavte


  2. git checkout freqtrade feat/freqai
      ./setup.sh -i
       deactivate
      ./setup.sh -u
      pip install -r requirements-freqai.txt
      pip install catboost

  4.  Move FreqaiExampleStrategy.py to freqtrade/user_data/strategies
       Move CatboostPredictionModel.py to freqtrade/user_data/freqaimodels
       Move config_freqai_futures.example.json to freqtrade

5. freqtrade download-data --config config_freqai_futures.example.json --timerange 20220101-20220601 -t 1m 3m 5m 15m 30m 1h 4h 
6. freqtrade backtesting --config config_freqai_futures.example.json --strategy FreqaiExampleStrategy --freqaimodel CatboostPredictionModel --strategy-path freqtrade/templates --timerange 20220501-20220601
  
### Observed Results:

The terminal calculates for 1 minutes and give the error

### Relevant code exceptions or logs
```
~/freqtradeIA/freqtrade$ freqtrade backtesting --config config_freqai_futures.example.json --strategy FreqaiExampleStrategy --freqaimodel CatboostPredictionModel --strategy-path freqtrade/templates --timerange 20220501-20220601
2022-07-04 05:40:37,101 - freqtrade.configuration.load_config - INFO - Using config: config_freqai_futures.example.json ...
2022-07-04 05:40:37,103 - freqtrade.loggers - INFO - Verbosity set to 0
2022-07-04 05:40:37,103 - freqtrade.configuration.configuration - INFO - Using additional Strategy lookup path: freqtrade/templates
2022-07-04 05:40:37,104 - freqtrade.configuration.configuration - WARNING - `force_entry_enable` RPC message enabled.
2022-07-04 05:40:37,104 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 5 ...
2022-07-04 05:40:37,104 - freqtrade.configuration.configuration - INFO - Parameter --timerange detected: 20220501-20220601 ...
2022-07-04 05:40:37,104 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/onetwo/freqtradeIA/freqtrade/user_data ...
2022-07-04 05:40:37,104 - freqtrade.configuration.configuration - INFO - Using data directory: /home/onetwo/freqtradeIA/freqtrade/user_data/data/okx ...
2022-07-04 05:40:37,104 - freqtrade.configuration.configuration - INFO - Parameter --cache=day detected ...
2022-07-04 05:40:37,104 - freqtrade.configuration.configuration - INFO - Using freqaimodel class name: CatboostPredictionModel
2022-07-04 05:40:37,104 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2022-07-04 05:40:37,110 - freqtrade.configuration.check_exchange - INFO - Exchange "okx" is officially supported by the Freqtrade development team.
2022-07-04 05:40:37,110 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2022-07-04 05:40:37,110 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2022-07-04 05:40:37,113 - freqtrade.commands.optimize_commands - INFO - Starting freqtrade in Backtesting mode
2022-07-04 05:40:37,113 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2022-07-04 05:40:37,113 - freqtrade.exchange.exchange - INFO - Using CCXT 1.89.14
2022-07-04 05:40:37,114 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}, 'enableRateLimit': True}
2022-07-04 05:40:37,118 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}, 'enableRateLimit': True, 'rateLimit': 200}
2022-07-04 05:40:37,186 - freqtrade.exchange.exchange - INFO - Using Exchange "OKX"
2022-07-04 05:40:40,215 - freqtrade.exchange.exchange - INFO - Initializing leverage_tiers for 129 markets. This will take about a minute.
2022-07-04 05:41:32,038 - freqtrade.exchange.exchange - INFO - Done initializing 129 markets.
2022-07-04 05:41:32,051 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Okx'...
2022-07-04 05:41:32,089 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy FreqaiExampleStrategy from '/home/onetwo/freqtradeIA/freqtrade/freqtrade/templates/FreqaiExampleStrategy.py'...
2022-07-04 05:41:32,089 - freqtrade.strategy.hyper - INFO - Found no parameter file.
2022-07-04 05:41:32,090 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 3m.
2022-07-04 05:41:32,090 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2022-07-04 05:41:32,090 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 200.
2022-07-04 05:41:32,090 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'entry': 10, 'exit': 30, 'exit_timeout_count': 0, 'unit': 'minutes'}.
2022-07-04 05:41:32,090 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 0.1, '240': -1}
2022-07-04 05:41:32,090 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 3m
2022-07-04 05:41:32,090 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.05
2022-07-04 05:41:32,090 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2022-07-04 05:41:32,090 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2022-07-04 05:41:32,090 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2022-07-04 05:41:32,090 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2022-07-04 05:41:32,090 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: True
2022-07-04 05:41:32,090 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'entry': 'limit', 'exit': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False, 'stoploss_on_exchange_interval': 60}
2022-07-04 05:41:32,090 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'entry': 'gtc', 'exit': 'gtc'}
2022-07-04 05:41:32,090 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2022-07-04 05:41:32,090 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 200
2022-07-04 05:41:32,090 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2022-07-04 05:41:32,090 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 300
2022-07-04 05:41:32,091 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'entry': 10, 'exit': 30, 'exit_timeout_count': 0, 'unit': 'minutes'}
2022-07-04 05:41:32,091 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_exit_signal: True
2022-07-04 05:41:32,091 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_only: False
2022-07-04 05:41:32,091 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_entry_signal: False
2022-07-04 05:41:32,091 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_offset: 0.0
2022-07-04 05:41:32,091 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2022-07-04 05:41:32,091 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2022-07-04 05:41:32,091 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: False
2022-07-04 05:41:32,091 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1
2022-07-04 05:41:32,091 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2022-07-04 05:41:32,101 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from '/home/onetwo/freqtradeIA/freqtrade/freqtrade/plugins/pairlist/StaticPairList.py'...
2022-07-04 05:41:32,107 - freqtrade.exchange.exchange - WARNING - Using 4 calls to get OHLCV. This can result in slower operations for the bot. Please check if you really need 300 candles for your strategy
2022-07-04 05:41:32,107 - freqtrade.optimize.backtesting - INFO - Increasing startup_candle_count for freqai to 10300
2022-07-04 05:41:32,107 - freqtrade.data.history.history_utils - INFO - Using indicator startup period: 10300 ...
2022-07-04 05:41:33,714 - freqtrade.optimize.backtesting - INFO - Loading data from 2022-04-09 13:00:00 up to 2022-06-01 00:00:00 (52 days).
2022-07-04 05:41:33,730 - freqtrade.data.converter - INFO - Missing data fillup for AGLD/USDT:USDT: before: 94 - after: 187 - 98.94%
2022-07-04 05:41:33,745 - freqtrade.data.converter - INFO - Missing data fillup for 1INCH/USDT:USDT: before: 94 - after: 187 - 98.94%
2022-07-04 05:41:33,759 - freqtrade.data.converter - INFO - Missing data fillup for AAVE/USDT:USDT: before: 94 - after: 187 - 98.94%
2022-07-04 05:41:33,774 - freqtrade.data.converter - INFO - Missing data fillup for ALGO/USDT:USDT: before: 94 - after: 187 - 98.94%
2022-07-04 05:41:33,789 - freqtrade.data.converter - INFO - Missing data fillup for ALPHA/USDT:USDT: before: 94 - after: 187 - 98.94%
2022-07-04 05:41:33,804 - freqtrade.data.converter - INFO - Missing data fillup for API3/USDT:USDT: before: 94 - after: 187 - 98.94%
2022-07-04 05:41:33,818 - freqtrade.data.converter - INFO - Missing data fillup for AVAX/USDT:USDT: before: 94 - after: 187 - 98.94%
2022-07-04 05:41:33,834 - freqtrade.data.converter - INFO - Missing data fillup for AXS/USDT:USDT: before: 94 - after: 187 - 98.94%
2022-07-04 05:41:33,848 - freqtrade.data.converter - INFO - Missing data fillup for BCH/USDT:USDT: before: 94 - after: 187 - 98.94%
2022-07-04 05:41:34,010 - freqtrade.optimize.backtesting - INFO - Dataload complete. Calculating indicators
2022-07-04 05:41:34,011 - freqtrade.optimize.backtesting - INFO - Running backtesting for Strategy FreqaiExampleStrategy
2022-07-04 05:41:34,125 - freqtrade.resolvers.iresolver - INFO - Using resolved freqaimodel CatboostPredictionModel from '/home/onetwo/freqtradeIA/freqtrade/user_data/freqaimodels/CatboostPredictionModel.py'...
2022-07-04 05:41:34,126 - freqtrade.freqai.data_drawer - INFO - Could not find existing datadrawer, starting from scratch
2022-07-04 05:41:34,126 - freqtrade.strategy.hyper - INFO - No params for buy found, using default values.
2022-07-04 05:41:34,126 - freqtrade.strategy.hyper - INFO - No params for sell found, using default values.
2022-07-04 05:41:34,126 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): linear_roi_offset = 0.005
2022-07-04 05:41:34,126 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): max_roi_time_long = 400
2022-07-04 05:41:34,126 - freqtrade.strategy.hyper - INFO - No params for protection found, using default values.
2022-07-04 05:41:35,748 - freqtrade.data.history.idatahandler - WARNING - No history for AGLD/USDT:USDT, futures, 15m found. Use `freqtrade download-data` to download the data
2022-07-04 05:41:35,748 - freqtrade.data.dataprovider - WARNING - No data found for (AGLD/USDT:USDT, 15m, ).
2022-07-04 05:41:35,748 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/onetwo/freqtradeIA/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/home/onetwo/freqtradeIA/freqtrade/freqtrade/commands/optimize_commands.py", line 58, in start_backtesting
    backtesting.start()
  File "/home/onetwo/freqtradeIA/freqtrade/freqtrade/optimize/backtesting.py", line 1261, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
  File "/home/onetwo/freqtradeIA/freqtrade/freqtrade/optimize/backtesting.py", line 1159, in backtest_one_strategy
    preprocessed = self.strategy.advise_all_indicators(data)
  File "/home/onetwo/freqtradeIA/freqtrade/freqtrade/strategy/interface.py", line 1144, in advise_all_indicators
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "/home/onetwo/freqtradeIA/freqtrade/freqtrade/strategy/interface.py", line 1144, in <dictcomp>
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "/home/onetwo/freqtradeIA/freqtrade/freqtrade/strategy/interface.py", line 1162, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/home/onetwo/freqtradeIA/freqtrade/freqtrade/templates/FreqaiExampleStrategy.py", line 183, in populate_indicators
    dataframe = self.populate_any_indicators(
  File "/home/onetwo/freqtradeIA/freqtrade/freqtrade/templates/FreqaiExampleStrategy.py", line 99, in populate_any_indicators
    informative[f"%-{coin}rsi-period_{t}"] = ta.RSI(informative, timeperiod=t)
  File "talib/_abstract.pxi", line 427, in talib._ta_lib.Function.__call__
  File "talib/_abstract.pxi", line 472, in talib._ta_lib.Function.__call_function
  File "/home/onetwo/freqtradeIA/freqtrade/.env/lib/python3.8/site-packages/talib/__init__.py", line 64, in wrapper
    result = func(*_args, **_kwds)
  File "talib/_func.pxi", line 4377, in talib._ta_lib.RSI
  File "talib/_func.pxi", line 68, in talib._ta_lib.check_begidx1
Exception: inputs are all NaN
```

**Comment by xmatthias** [comment]
> 2022-07-04 05:41:35,748 - freqtrade.data.dataprovider - WARNING - No data found for (AGLD/USDT:USDT, 15m, ).

as suspected, data for at least one of the correlation pairs is missing.
Why this is the case is difficult to say (most likely the log of download-data would show a reason).

you could try to run `download-data --pairs AGLD/USDT:USDT -t 15m --timerange 20220101-20220601` to download this pairs data - assuming no other data is missing, then.

**Comment by Onetwo31** [comment]
Effectively, I do not know why but it was always missing some data. I'm sorry to have bothered you for it. Thank you !
