### ISSUE TITLE
bybit: TypeError: unsupported operand type(s) for *=: 'int' and 'NoneType'

### ISSUE THREAD

**Issue by tungrix** [freqtrade/freqtrade#7054]
## Describe your environment

  * Operating system: Docker
  * Python Version: 3.10.5 
  * CCXT version: 1.90.39 
  * Freqtrade Version: 2022.6 
  
## Describe the problem:

Bug when trying sample strategy on bybit exchange, stop running

### Steps to reproduce:

  1. Trading with bybit exchange
  2. Choose the sample strategy
  3. Start the strategy
  
### Observed Results:

  * The bot die when trying to open the position

### Relevant code exceptions or logs

  ```
 2022-07-08 07:27:07,296 - freqtrade.freqtradebot - INFO - Long signal found: about create a new trade for SOL/USDT with stake_amount: 100 ...
2022-07-08 07:27:07,351 - freqtrade.freqtradebot - INFO - Order #dry_run_buy_1657265227.29848 was created for SOL/USDT and status is open.
2022-07-08 07:27:07,353 - freqtrade.commands.trade_commands - ERROR - unsupported operand type(s) for *=: 'int' and 'NoneType'
2022-07-08 07:27:07,355 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker.run()
  File "/freqtrade/freqtrade/worker.py", line 74, in run
    state = self._worker(old_state=state)
  File "/freqtrade/freqtrade/worker.py", line 114, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
  File "/freqtrade/freqtrade/worker.py", line 139, in _throttle
    result = func(*args, **kwargs)
  File "/freqtrade/freqtrade/worker.py", line 152, in _process_running
    self.freqtrade.process()
  File "/freqtrade/freqtrade/freqtradebot.py", line 212, in process
    self.enter_positions()
  File "/freqtrade/freqtrade/freqtradebot.py", line 430, in enter_positions
    trades_created += self.create_trade(pair)
  File "/freqtrade/freqtrade/freqtradebot.py", line 492, in create_trade
    return self.execute_entry(
  File "/freqtrade/freqtrade/freqtradebot.py", line 685, in execute_entry
    fee = self.exchange.get_fee(symbol=pair, taker_or_maker='maker')
  File "/freqtrade/freqtrade/exchange/common.py", line 165, in wrapper
    return f(*args, **kwargs)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 1608, in get_fee
    return self._api.calculate_fee(symbol=symbol, type=type, side=side, amount=amount,
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2133, in calculate_fee
    cost *= rate
TypeError: unsupported operand type(s) for *=: 'int' and 'NoneType'
  ```

**Comment by tungrix** [comment]
So is there any temporary way to solve the issue?

**Comment by xmatthias** [comment]
Bybit is not officially supported by freqtrade - so you may be very well the first one to try this (which means it can be a bumpy road into the unknown).
Most things should work - but sometimes details don't - so to get bybit to work will take time and patience. if you're not somewhat experienced with debugging things in python (or at least creating standalone scripts to take freqtrade out of the equation) - it'll probably be a painful process. 

While we can support in this - it's not a high priority - so patience will be necessary.

If you lack any of the above - best stick to the supported exchanges - which are known to work just fine.

---

Running the "calculate_fee" method on SOL/USDT:USDT (on a futures market) - i can get the rate just fine.
If i switch to spot explicitly (default for freqtrade though) - i get that pair (and also the corresponding error). 

considering that spot markets for bybit are quite new in ccxt iirc - this is most likely a bug in ccxt.

I've opened https://github.com/ccxt/ccxt/issues/14292 for this. I'd not know any temporary workarounds which don't involve code workarounds in freqtrade.

**Comment by tungrix** [comment]
Thanks for the explanation! I'm trying bybit futures right now, however I got
```
freqtrade  | 2022-07-10 09:21:00,633 - freqtrade.commands.trade_commands - ERROR - Freqtrade does not support  futures on Bybit
freqtrade  | 2022-07-10 09:21:00,635 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
freqtrade  | Traceback (most recent call last):
freqtrade  |   File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
freqtrade  |     worker = Worker(args)
freqtrade  |   File "/freqtrade/freqtrade/worker.py", line 35, in __init__
freqtrade  |     self._init(False)
freqtrade  |   File "/freqtrade/freqtrade/worker.py", line 52, in _init
freqtrade  |     self.freqtrade = FreqtradeBot(self._config)
freqtrade  |   File "/freqtrade/freqtrade/freqtradebot.py", line 68, in __init__
freqtrade  |     self.exchange = ExchangeResolver.load_exchange(self.config['exchange']['name'], self.config)
freqtrade  |   File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 32, in load_exchange
freqtrade  |     exchange = ExchangeResolver._load_exchange(exchange_name,
freqtrade  |   File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 54, in _load_exchange
freqtrade  |     exchange = ex_class(**kwargs)
freqtrade  |   File "/freqtrade/freqtrade/exchange/exchange.py", line 191, in __init__
freqtrade  |     self.validate_trading_mode_and_margin_mode(self.trading_mode, self.margin_mode)
freqtrade  |   File "/freqtrade/freqtrade/exchange/exchange.py", line 664, in validate_trading_mode_and_margin_mode
freqtrade  |     raise OperationalException(
freqtrade  | freqtrade.exceptions.OperationalException: Freqtrade does not support  futures on Bybit
```
My config file setting:
```
"max_open_trades": 1,
    "stake_currency": "USDT",
    "stake_amount": 100,
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "HKD",
    "timeframe": "1m",
    "dry_run": true,
    "cancel_open_orders_on_exit": false,
    "trading_mode": "futures",
    "margin_mode": "",
    "unfilledtimeout": {
        "entry": 10,
        "exit": 10,
        "exit_timeout_count": 0,
        "unit": "minutes"
    },
    "entry_pricing": {
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1,
        "price_last_balance": 0.0,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "exit_pricing":{
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1
    },
    "exchange": {
        "name": "bybit",
        "key": "",
        "secret": "",
        "ccxt_config": {},
        "ccxt_async_config": {},
        "pair_whitelist": [

        ],
        "pair_blacklist": [

        ]
    },
```
What's wrong is going on when trying to trade bybit futures?

**Comment by xmatthias** [comment]
bybit futures won't work with freqtrade for now (as mentioned above - it's an unsupported exchange). 

Futures requires some additional work for each exchange - which so far has only been done for binance, gateio and okx.
We aim to also support other supported exchanges (mainly FTX for now). Bybit is currently not on the list to be investigated anytime soon.

**Comment by tungrix** [comment]
I got it now, thank you very much for answering my question! Looking forward to seeing more exchange support.

**Comment by xmatthias** [comment]
with the latest ccxt release, the error pointed out above has been fixed.

This does not mean that bybit will now work flawlessly, that is still up to interested users to investigate further.
