### ISSUE TITLE
gateio fees sometimes reported as string

### ISSUE THREAD

**Issue by medenlin** [freqtrade/freqtrade#7056]
## Describe your environment

  * Operating system: Docker
  * Freqtrade Version: docker-494e0529
  
## Describe the problem:

After today develop update Freqtrade goes to restart loop with error (presumably, when trying to get fee in uncertain cases)

### Steps to reproduce:

  1. Run Freqtrade in live futures mode on gateio
  2. Wait for potentially trade manipulations
  3. Observe
   
### Observed Results:

  * What happened?
Restart loop with error message

### Relevant code exceptions or logs

  ```
2022-07-10 20:13:03,899 - freqtrade.worker - INFO - Changing state to: RUNNING
2022-07-10 20:13:03,900 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': "*Exchange:* `gateio`\n*Stake per trade:* `unlimited USDT`\n*Minimum ROI:* `{'0': 0.4, '1440': 0.05, '2880': 0.0, '5760': -0.01, '5940': -0.02, '6120': -0.035, '6300': -0.05, '6480': -0.1, '7200': -0.15, '7920': -0.2, '8640': -0.25, '9360': -0.3, '10800': -0.4, '12240': -0.5, '13680': -0.6, '15120': -0.7, '16560': -0.8}`\n*Trailing Stoploss:* `-0.99`\n*Position adjustment:* `On`\n*Timeframe:* `5m`\n*Strategy:* `MELFUTURESAUTO`"}
2022-07-10 20:13:04,031 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': "Searching for USDT pairs to buy and sell based on [{'VolumePairList': 'VolumePairList - top 300 volume pairs.'}]"}
2022-07-10 20:13:04,151 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': 'Using Protections: \nStoplossGuard - Frequent Stoploss Guard, 4 stoplosses within 24 candles.\nStoplossGuard - Frequent Stoploss Guard, 1 stoplosses within 4 candles.'}
2022-07-10 20:13:04,296 - freqtrade.persistence.trade_model - INFO - Found open trade: Trade(id=1176, pair=UNFI/USDT:USDT, amount=7.00000000, is_short=False, leverage=2.0, open_rate=6.76775714, open_since=2022-07-09 19:45:21)
2022-07-10 20:13:04,297 - freqtrade.persistence.trade_model - INFO - Found open trade: Trade(id=1182, pair=LOKA/USDT:USDT, amount=25.00000000, is_short=False, leverage=1.0, open_rate=0.58272400, open_since=2022-07-10 00:45:28)
2022-07-10 20:13:04,298 - freqtrade.persistence.trade_model - INFO - Found open trade: Trade(id=1190, pair=ROOK/USDT:USDT, amount=0.20000000, is_short=False, leverage=1.0, open_rate=33.05000000, open_since=2022-07-10 01:20:20)
2022-07-10 20:13:04,298 - freqtrade.persistence.trade_model - INFO - Found open trade: Trade(id=1194, pair=OXY/USDT:USDT, amount=347.00000000, is_short=False, leverage=1.0, open_rate=0.07257349, open_since=2022-07-10 01:50:18)
2022-07-10 20:13:04,299 - freqtrade.persistence.trade_model - INFO - Found open trade: Trade(id=1205, pair=TOMO/USDT:USDT, amount=12.00000000, is_short=False, leverage=1.0, open_rate=0.53680000, open_since=2022-07-10 11:15:42)
2022-07-10 20:13:04,300 - freqtrade.persistence.trade_model - INFO - Found open trade: Trade(id=1214, pair=CVX/USDT:USDT, amount=1.10000000, is_short=False, leverage=1.0, open_rate=5.90600000, open_since=2022-07-10 14:15:25)
2022-07-10 20:13:04,301 - freqtrade.persistence.trade_model - INFO - Found open trade: Trade(id=1216, pair=SERO/USDT:USDT, amount=50.00000000, is_short=False, leverage=1.0, open_rate=0.11650000, open_since=2022-07-10 14:27:04)
2022-07-10 20:13:04,302 - freqtrade.persistence.trade_model - INFO - Found open trade: Trade(id=1220, pair=FLM/USDT:USDT, amount=50.00000000, is_short=True, leverage=1.0, open_rate=0.12004000, open_since=2022-07-10 17:45:39)
2022-07-10 20:13:04,303 - freqtrade.persistence.trade_model - INFO - Found open trade: Trade(id=1221, pair=TRB/USDT:USDT, amount=0.40000000, is_short=False, leverage=1.0, open_rate=14.60700000, open_since=2022-07-10 18:42:04)
2022-07-10 20:13:04,306 - freqtrade.freqtradebot - INFO - Updating 3 open orders.
2022-07-10 20:13:04,592 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=1194, pair=OXY/USDT:USDT, amount=347.00000000, is_short=False, leverage=1.0, open_rate=0.07257349, open_since=2022-07-10 01:50:18)
2022-07-10 20:13:05,134 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=1220, pair=FLM/USDT:USDT, amount=50.00000000, is_short=True, leverage=1.0, open_rate=0.12004000, open_since=2022-07-10 17:45:39)
2022-07-10 20:13:05,693 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=1190, pair=ROOK/USDT:USDT, amount=0.20000000, is_short=False, leverage=1.0, open_rate=33.05000000, open_since=2022-07-10 01:20:20)
2022-07-10 20:13:17,216 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=1176, pair=UNFI/USDT:USDT, amount=7.00000000, is_short=False, leverage=2.0, open_rate=6.76775714, open_since=2022-07-09 19:45:21)
2022-07-10 20:13:17,727 - freqtrade.commands.trade_commands - ERROR - unsupported operand type(s) for /: 'str' and 'float'
2022-07-10 20:13:17,728 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker.run()
  File "/freqtrade/freqtrade/worker.py", line 74, in run
    state = self._worker(old_state=state)
  File "/freqtrade/freqtrade/worker.py", line 114, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
  File "/freqtrade/freqtrade/worker.py", line 139, in _throttle
    result = func(*args, **kwargs)
  File "/freqtrade/freqtrade/worker.py", line 152, in _process_running
    self.freqtrade.process()
  File "/freqtrade/freqtrade/freqtradebot.py", line 195, in process
    self.manage_open_orders()
  File "/freqtrade/freqtrade/freqtradebot.py", line 1152, in manage_open_orders
    fully_cancelled = self.update_trade_state(trade, trade.open_order_id, order)
  File "/freqtrade/freqtrade/freqtradebot.py", line 1647, in update_trade_state
    self.handle_order_fee(trade, order_obj, order)
  File "/freqtrade/freqtrade/freqtradebot.py", line 1721, in handle_order_fee
    new_amount = self.get_real_amount(trade, order, order_obj)
  File "/freqtrade/freqtrade/freqtradebot.py", line 1759, in get_real_amount
    return self.fee_detection_from_trades(
  File "/freqtrade/freqtrade/freqtradebot.py", line 1790, in fee_detection_from_trades
    fee_cost_, fee_currency, fee_rate_ = self.exchange.extract_cost_curr_rate(
  File "/freqtrade/freqtrade/exchange/exchange.py", line 1690, in extract_cost_curr_rate
    self.calculate_fee_rate(
  File "/freqtrade/freqtrade/exchange/exchange.py", line 1660, in calculate_fee_rate
    return round(fee_cost / cost, 8) if cost else None
TypeError: unsupported operand type(s) for /: 'str' and 'float'
2022-07-10 20:13:17,730 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2022-07-10 20:13:17,730 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2022-07-10 20:13:17,915 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2022-07-10 20:13:17,921 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': warning, 'status': "9 open trades active.\n\nHandle these trades manually on Gate.io, or '/start' the bot again and use '/stopbuy' to handle open trades gracefully. \n"}
2022-07-10 20:13:18,107 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
2022-07-10 20:13:18,108 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.apiserver ...
2022-07-10 20:13:18,109 - freqtrade.rpc.api_server.webserver - INFO - Stopping API Server
2022-07-10 20:13:18,128 - uvicorn.error - INFO - Shutting down
2022-07-10 20:13:18,229 - uvicorn.error - INFO - Waiting for application shutdown.
2022-07-10 20:13:18,230 - uvicorn.error - INFO - Application shutdown complete.
2022-07-10 20:13:18,231 - uvicorn.error - INFO - Finished server process [1]
2022-07-10 20:13:18,232 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.telegram ...
2022-07-10 20:13:18,233 - apscheduler.scheduler - INFO - Scheduler has been shut down
2022-07-10 20:13:37,820 - freqtrade.exchange.exchange - INFO - Closing async ccxt session.
2022-07-10 20:13:41,845 - freqtrade.loggers - INFO - Verbosity set to 0
2022-07-10 20:13:41,845 - freqtrade.configuration.configuration - INFO - Runmode set to live.
2022-07-10 20:13:41,846 - freqtrade.configuration.configuration - INFO - Using additional Strategy lookup path: /freqtrade/user_data/strategies/berlinguyinca
2022-07-10 20:13:41,846 - freqtrade.configuration.configuration - INFO - Parameter --db-url detected ...
2022-07-10 20:13:41,847 - freqtrade.configuration.configuration - INFO - Dry run is disabled
2022-07-10 20:13:41,848 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:////freqtrade/user_data/tradesv3-futures.sqlite"
2022-07-10 20:13:41,848 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 10 ...
2022-07-10 20:13:45,834 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2022-07-10 20:13:45,835 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/gateio ...
2022-07-10 20:13:45,836 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2022-07-10 20:13:45,842 - freqtrade.configuration.check_exchange - INFO - Exchange "gateio" is officially supported by the Freqtrade development team.
2022-07-10 20:13:45,843 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2022-07-10 20:13:45,844 - freqtrade.freqtradebot - INFO - Starting freqtrade docker-494e0529
  ```

**Comment by xmatthias** [comment]
This is a known issue in ccxt (https://github.com/ccxt/ccxt/issues/14264, https://github.com/ccxt/ccxt/issues/14247#issuecomment-1178559892).

A fix for this (untested) should be available as PR here: https://github.com/ccxt/ccxt/pull/14268 - but is still unmerged.

I've known about this when the original fix was merged - but this should only affect a very small % of trades, so it's a tradeoff i'm willing to make.

**Comment by medenlin** [comment]
> I've known about this when the original fix was merged - but this should only affect a very small % of trades, so it's a tradeoff i'm willing to make.

This glitch is not so rare when there are many open orders, it appears more often
