### ISSUE TITLE
Derived Strategy break Hyperopt

### ISSUE THREAD

**Issue by ArtyT** [freqtrade/freqtrade#7078]
## Describe your environment

  * Operating system: Docker
  * Python Version: 3.10
  * Freqtrade Version: 2022.6
  

## Describe the problem:

If deriving you strategy from another one that has been defined outside of the current strategy file it causes hyperopt to fail with a Loky object failed to unserialize error.

### Steps to reproduce:

  1. Create a new strategy with freqtrade new-strategy *args
  2. Make a copy of that strategy in another file
  3. Inherit your first strategy from the 2. one
  
### Observed Results:

  * What happened?
  Hyperopt failed with unserialize error.
  * What did you expect to happen?
  Hyperopt to run normally.

### Relevant code exceptions or logs

```
2022-07-13 13:48:31,965 - freqtrade - ERROR - Fatal exception!
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.10/site-packages/joblib/externals/loky/process_executor.py", line 407, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "/usr/local/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/home/ftuser/.local/lib/python3.10/site-packages/joblib/externals/loky/cloudpickle_wrapper.py", line 48, in _reconstruct_wrapper
    obj = loads(_pickled_object)
ModuleNotFoundError: No module named 'test'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 107, in start_hyperopt
    hyperopt.start()
  File "/freqtrade/freqtrade/optimize/hyperopt.py", line 523, in start
    f_val = self.run_optimizer_parallel(parallel, asked, i)
  File "/freqtrade/freqtrade/optimize/hyperopt.py", line 389, in run_optimizer_parallel
    return parallel(delayed(
  File "/home/ftuser/.local/lib/python3.10/site-packages/joblib/parallel.py", line 1056, in __call__
    self.retrieve()
  File "/home/ftuser/.local/lib/python3.10/site-packages/joblib/parallel.py", line 935, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/ftuser/.local/lib/python3.10/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.

```

**Comment by xmatthias** [comment]
I've been aware of this in the back of my mind for quite some time - but there's no real solution i've come up with - as it's a dependency of unpickling to be able to "find" all elements (it won't find the parent class).

it will also depend a bit on how you're importing the strategy if i remember correctly.

Relative imports will not work (once the strategy is moved into the worker, it "forgets" where it came from.
absolute imports MAY work - assuming they're relative to the local dir (`from user_data.strategies.xxx import yyy)` - but require each dir to be a package (contain a `__init__.py` file).
