### ISSUE TITLE
Gemini InvalidNonce with NFI in live mode

### ISSUE THREAD

**Issue by pnmice** [freqtrade/freqtrade#7094]
Have you searched for similar issues before posting it?
yes

Found semilar problems
https://github.com/freqtrade/freqtrade/issues/6526
https://github.com/freqtrade/freqtrade/issues/6080

## Describe your environment

  * Operating system: linux, docker 20.10.16
  * Python Version: 3.10
  * CCXT version: 1.89.14
  * Freqtrade Version: freqtrade 2022.6
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

Docker freqtrade does not work with Gemini exchange and NFI strategy in live mode. I have several different exchanges with freqtrade, which work on the same linux machine. Also, Gemini works in dry run.

Tried to fix it.
I have tried different versions of freqtrade, like 2022.4 2022.5
In docker
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
 
chronyc sources
```
MS Name/IP address         Stratum Poll Reach LastRx Last sample
===============================================================================
^* time1.facebook.com            1  10   377   326  -1578us[-1578us] +/- 7760us
```
Also, tried
        "ccxt_config": {
                "enableRateLimit": true,
                "options": {"options": { "adjustForTimeDifference": true }}
        },

### Steps to reproduce:

Strategy https://github.com/iterativv/NostalgiaForInfinity/blob/main/NostalgiaForInfinityX.py

### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
2022-07-16 13:56:29,222 - freqtrade.exchange.exchange - INFO - Using CCXT 1.89.14
2022-07-16 13:56:29,228 - freqtrade.exchange.exchange - INFO - Using Exchange "Gemini"
2022-07-16 13:56:29,446 - freqtrade.exchange.common - WARNING - get_balances() returned exception: "Could not get balance due to InvalidNonce. Message: gemini Nonce '1657979789417' has not increased since your last call to the Gemini API.". Retrying still for 4 times.
2022-07-16 13:56:29,468 - freqtrade.exchange.common - WARNING - get_balances() returned exception: "Could not get balance due to InvalidNo
2022-07-16 13:56:29,666 - freqtrade.commands.trade_commands - ERROR - Could not get balance due to InvalidNonce. Message: gemini Nonce '1657979789566' has not increased since your last call to the Gemini API.
2022-07-16 13:56:29,666 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 617, in fetch
    response.raise_for_status()
  File "/home/ftuser/.local/lib/python3.10/site-packages/requests/models.py", line 1022, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.gemini.com/v1/balances

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/exchange.py", line 1300, in get_balances
    balances = self._api.fetch_balance()
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/gemini.py", line 812, in fetch_balance
    response = self.privatePostV1Balances(params)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 497, in inner
    return entry(_self, **inner_kwargs)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2616, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2613, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 633, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/gemini.py", line 1410, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], reason, feedback)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2834, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.InvalidNonce: gemini Nonce '1657979789417' has not increased since your last call to the Gemini API.
  ```

**Comment by xmatthias** [comment]
gemini is not a supported (nor tested) exchange - so it's unclear what other issues you may encounter.

the error itself points to an error with your API key which ain't increasing Nonce. 
most likely you've either used the key with another project / product (or are still actively using this - as the Nonce is from 22 minutes ago) - which is using a different logic to calculate nonces.

Best try to create a new, dedicated API key for freqtrade.

**Comment by pnmice** [comment]
Hi Matthias,
Wow! It works. Solution is a new API key. Thanks a lot!

**Comment by xmatthias** [comment]
You can (somehow) also tune how ccxt generates Nonces if that's necessary - but (at least for supported exchanges) we've never had to go that route.
