### ISSUE TITLE
Huobi download-data error

### ISSUE THREAD

**Issue by vixart** [freqtrade/freqtrade#7109]
I'm trying to use Huobi exchange and download data with following command
`freqtrade download-data --timerange 20220301-20220630 -t 5m -c huobi.json`

But always getting a error:
```
2022-07-20 00:57:56,890 - freqtrade.configuration.load_config - INFO - Using config: huobi.json ...
2022-07-20 00:57:56,891 - freqtrade.loggers - INFO - Verbosity set to 0
2022-07-20 00:57:56,891 - freqtrade.configuration.configuration - INFO - Parameter --timerange detected: 20220301-20220630 ...
2022-07-20 00:57:56,899 - freqtrade.configuration.configuration - INFO - Using user-data directory: /workspaces/fq_userdata/user_data ...
2022-07-20 00:57:56,900 - freqtrade.configuration.configuration - INFO - Using data directory: /workspaces/fq_userdata/user_data/data/huobi ...
2022-07-20 00:57:56,901 - freqtrade.configuration.configuration - INFO - timeframes --timeframes: ['5m']
2022-07-20 00:57:56,901 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2022-07-20 00:57:56,911 - freqtrade.configuration.check_exchange - INFO - Exchange "huobi" is officially supported by the Freqtrade development team.
2022-07-20 00:57:56,911 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2022-07-20 00:57:56,911 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2022-07-20 00:57:56,914 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2022-07-20 00:57:56,915 - freqtrade.exchange.exchange - INFO - Using CCXT 1.89.14
2022-07-20 00:57:56,915 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'future', 'defaultSubType': 'linear'}}
2022-07-20 00:57:56,925 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'future', 'defaultSubType': 'linear'}}
2022-07-20 00:57:56,936 - freqtrade.exchange.exchange - INFO - Using Exchange "Huobi"
2022-07-20 00:58:00,559 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/data_commands.py", line 50, in start_download_data
    exchange = ExchangeResolver.load_exchange(config['exchange']['name'], config, validate=False)
  File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 32, in load_exchange
    exchange = ExchangeResolver._load_exchange(exchange_name,
  File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 54, in _load_exchange
    exchange = ex_class(**kwargs)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 200, in __init__
    self.fill_leverage_tiers()
  File "/freqtrade/freqtrade/exchange/exchange.py", line 2194, in fill_leverage_tiers
    leverage_tiers = self.load_leverage_tiers()
  File "/freqtrade/freqtrade/exchange/exchange.py", line 2153, in load_leverage_tiers
    return self.get_leverage_tiers()
  File "/freqtrade/freqtrade/exchange/common.py", line 165, in wrapper
    return f(*args, **kwargs)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 2124, in get_leverage_tiers
    return self._api.fetch_leverage_tiers()
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/huobi.py", line 5975, in fetch_leverage_tiers
    return self.parse_leverage_tiers(data, symbols, 'contract_code')
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/huobi.py", line 6034, in parse_leverage_tiers
    if self.in_array(symbols, symbol):
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 1008, in in_array
    return needle in haystack
TypeError: 'in <string>' requires string as left operand, not NoneType
```

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

while Huobi is a supported exchange, this is not true for futures markets.

Based on the config / log, it appears like you're trying to use it with futures - which is not supported / implemented - and we're also not currently working on this.

Assuming you're trying to integrate huobi futures into freqtrade, best isolate this error (Using ccxt code directly, removing freqtrade as dependency) and report it to ccxt, to have it fixed there.

Using huobi for spot markets will work fine though - but you'll need to remove the extra configs from your configuration to point it to futures markets.
