### ISSUE TITLE
Fatal exception, KeyError: 'buy' after several hours of the bot working fine.

### ISSUE THREAD

**Issue by samanderbusk** [freqtrade/freqtrade#7150]
## Describe your environment

  * Operating system: ubuntu
  * Python Version: 3.8.10
  * CCXT version: 1.74.43
  * Freqtrade Version: 2022.1
  

## Describe the problem:

the bot works just fine for several hours then the process died and the following error accurs:

### Relevant code exceptions or logs

  ```2022-07-30 21:54:47,163 - freqtrade.commands.trade_commands - ERROR - 'buy'
2022-07-30 21:54:47,164 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/freqtrade/freqtrade/.env/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'buy'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/freqtrade/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker.run()
  File "/home/freqtrade/freqtrade/freqtrade/worker.py", line 74, in run
    state = self._worker(old_state=state)
  File "/home/freqtrade/freqtrade/freqtrade/worker.py", line 114, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
  File "/home/freqtrade/freqtrade/freqtrade/worker.py", line 139, in _throttle
    result = func(*args, **kwargs)
  File "/home/freqtrade/freqtrade/freqtrade/worker.py", line 152, in _process_running
    self.freqtrade.process()
  File "/home/freqtrade/freqtrade/freqtrade/freqtradebot.py", line 189, in process
    self.enter_positions()
  File "/home/freqtrade/freqtrade/freqtrade/freqtradebot.py", line 371, in enter_positions
    trades_created += self.create_trade(pair)
  File "/home/freqtrade/freqtrade/freqtrade/freqtradebot.py", line 411, in create_trade
    (buy, sell, buy_tag, _) = self.strategy.get_signal(
  File "/home/freqtrade/freqtrade/freqtrade/strategy/interface.py", line 660, in get_signal
    buy = latest[SignalType.BUY.value] == 1
  File "/home/freqtrade/freqtrade/.env/lib/python3.8/site-packages/pandas/core/series.py", line 958, in __getitem__
    return self._get_value(key)
  File "/home/freqtrade/freqtrade/.env/lib/python3.8/site-packages/pandas/core/series.py", line 1069, in _get_value
    loc = self.index.get_loc(label)
  File "/home/freqtrade/freqtrade/.env/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 'buy'
2022-07-30 21:54:47,179 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2022-07-30 21:54:47,185 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2022-07-30 21:54:47,663 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2022-07-30 21:54:47,664 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
2022-07-30 21:54:47,665 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.telegram ...
2022-07-30 21:54:47,665 - apscheduler.scheduler - INFO - Scheduler has been shut down
2022-07-30 21:55:05,608 - freqtrade.exchange.exchange - INFO - Closing async ccxt session.
  ```

**Comment by xmatthias** [comment]
Your version is outdated by ~5 versions. While the explanation will not change - i'd still recommend to upgrade to a more recent version - as these will always include bugfixes.

The only case where this can / could happen is that your strategy is not assigning the buy column.
This can for example happen if you made this assignment conditional, not assigning the buy column at certain times of the day for example.

'buy' is a mandatory column - so it must always be assigned (you can initialize it with  0 if you must do conditional logic).

Freqtrade itself expects the buy column to be present - but will not modify the dataframe - therefore it's your strategy that's causing this.

**Comment by samanderbusk** [comment]
Thank you so much, it's exactly what you said. it was a condition that in some cases i don't want to buy so i removed the :
datafram.loc[
    (
         (...)
          ),
         'buy']=1

and that caused the problem. as you suggested, keeping it and assigning it to = 0 instead of = 1; solved the problem

thank you so much

i added the details to help someone who will make the same mistake in the future.

**Comment by xmatthias** [comment]
> i added the details to help someone who will make the same mistake in the future.

This is pretty much appreciated! :100:
