### ISSUE TITLE
alphatrend strategy

### ISSUE THREAD

**Issue by batuhanhazarguler** [freqtrade/freqtrade#7182]
Hello my friends
please help me! :) i am very new to freqtrade

this is Source: https://www.tradingview.com/script/o50NYLAZ-AlphaTrend/
Pinescript Author: KivancOzbilgic
https://www.tradingview.com/script/o50NYLAZ-AlphaTrend/

my code return 
**freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair BTC/USDT: Dataframe returned from strategy has mismatching length.**

`

    import logging
    import pandas as pd
    from numpy.lib import math
    from freqtrade.strategy import IStrategy
    from pandas import DataFrame
    import talib.abstract as ta
    import numpy as np
    import freqtrade.vendor.qtpylib.indicators as qtpylib

    class FAlphaTrend(IStrategy):
    # Buy params, Sell params, ROI, Stoploss and Trailing Stop are values generated by 'freqtrade hyperopt --strategy Supertrend --hyperopt-loss ShortTradeDurHyperOptLoss --timerange=20210101- --timeframe=1h --spaces all'
    # It's encourage you find the values that better suites your needs and risk management strategies

    INTERFACE_VERSION: int = 3
    # ROI table:
    minimal_roi = {"0": 0.1, "30": 0.75, "60": 0.05, "120": 0.025}
    # minimal_roi = {"0": 1}

    # Stoploss:
    stoploss = -0.265

    # Trailing stop:
    trailing_stop = True
    trailing_stop_positive = 0.05
    trailing_stop_positive_offset = 0.1
    trailing_only_offset_is_reached = False

    timeframe = "15m"

    startup_candle_count = 500

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        # dataframe["ott"] = self.ott(dataframe)["OTT"]
       
        alphatrend = self.at(dataframe)

        alphatrendDf = alphatrend

        print(alphatrend)
        # dataframe["k1"] = self.at(dataframe)["k1"]
        # dataframe["k2"] = self.at(dataframe)["k2"]
        dataframe["k1"] = alphatrendDf["k1"]
        dataframe["k2"] = alphatrendDf["k2"]
        # dataframe["var"] = self.ott(dataframe)["VAR"]
        dataframe["adx"] = ta.ADX(dataframe, timeperiod=14)
        dataframe["sar"] = ta.SAR(dataframe)
        # last_candle = dataframe.iloc[-1]
        # prev_last_candle = dataframe.iloc[-2]

        # k1Last = float(dataframe["k1"][len(dataframe.index) - 1])
        k1LastCandle = dataframe["k1"][len(dataframe.index) - 1]
        print(k1LastCandle)
        # k2Last = float(dataframe["k2"][len(dataframe.index) - 1])
        k2LastCandle = dataframe["k2"][len(dataframe.index) - 1]

        # k1Prev = float(dataframe["k1"][len(dataframe.index) - 2])
        k1PrevCandle = dataframe["k1"][len(dataframe.index) - 2]
        # k2Prev = float(dataframe["k2"][len(dataframe.index) - 2])
        k2PrevCandle = dataframe["k2"][len(dataframe.index) - 2]

        # k1PrevPrevious = float(dataframe["k1"][len(dataframe.index) - 3])
        k1PrevPreviousCandle = dataframe["k1"][len(dataframe.index) - 3]
        # k2PrevPrevious = float(dataframe["k2"][len(dataframe.index) - 3])
        k2PrevPreviousCandle = dataframe["k2"][len(dataframe.index) - 3]

        # alphatrend = dataframe
        # alphatrendDf =alphatrend(columns=["k1","k2"])

        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        k1LastCandle = dataframe['k1'].iloc[-1]
        k2LastCandle = dataframe['k2'].iloc[-1]
        print(k1LastCandle)
        dataframe.loc[
            (
                # (dataframe['sar'] < dataframe["close"]) & # bull Trend
                 (k1LastCandle > k2LastCandle) 
                # (k1PrevCandle < k2PrevCandle),
            ),
            'enter_long',
        ] = 1

        # dataframe.loc[
        #     (
        #         (k1LastCandle < k2LastCandle) &
        #         (k1PrevCandle > k2PrevCandle),
        #     ),
        #     "enter_short",
        # ] = 1

        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                dataframe["adx"]>60
            ),
            "exit_long",
        ] = 1

        dataframe.loc[
            (
                dataframe["adx"]>60
            ),
            "exit_short",
        ] = 1

        return dataframe

    """
        Supertrend Indicator; adapted for freqtrade
        from: https://github.com/freqtrade/freqtrade-strategies/issues/30
    """

    def at(self, dataframe: DataFrame):
        df = dataframe.copy()

        # high1 = df['high']
        # low1 = df['low']
        # open = df['open']
        # close1 = df['close']
        # volume1 = df['volume']
        # ap = 14

        # close = np.asarray(close1)
        # high = np.asarray(high1)
        # low = np.asarray(low1)
        # volume = np.asarray(volume1)

        high1 = df['high']
        low1 = df['low']
        open = df['open']
        close1 = df['close']
        volume1 = df['volume']
        ap = 14

        close = close1
        high = high1
        low = low1
        volume = volume1

        try:
            atr = ta.ATR(high, low, close, ap)
        except Exception as exp:
            print('exception in atr:', str(exp), flush=True)
            return []
        # tr = ta.true_range(high, low, close)
        # atr = ta.sma(tr, ap)
        noVolumeData = False
        coeff = 1
        upt = []
        downT = []
        AlphaTrend = [0.0]
        rsi = ta.RSI(df['close'], timeperiod=14)
        k1 = []
        k2 = []
        mfi = ta.MFI(high, low, close, volume, 14)

        for i in range(len(low)):
            if pd.isna(atr[i]):
                upt.append(0)
            else:
                upt.append(low[i] - (atr[i] * coeff))

        for i in range(len(high)):
            if pd.isna(atr[i]):
               downT.append(0)
            else:
              downT.append(high[i] + (atr[i] * coeff))

        for i in range(1, len(close)):
            if noVolumeData is True and rsi[i] >= 50:
                if upt[i] < AlphaTrend[i - 1]:
                    AlphaTrend.append(AlphaTrend[i - 1])
                else:
                   AlphaTrend.append(upt[i])

            elif noVolumeData is False and mfi[i] >= 50:
                if upt[i] < AlphaTrend[i - 1]:
                   AlphaTrend.append(AlphaTrend[i - 1])
                else:
                   AlphaTrend.append(upt[i])
            else:
                if downT[i] > AlphaTrend[i - 1]:
                    AlphaTrend.append(AlphaTrend[i - 1])
                else:
                    AlphaTrend.append(downT[i])

        for i in range(len(AlphaTrend)):
            if i < 2:
                k2.append(0)
                k1.append(AlphaTrend[i])
            else:
                k2.append(AlphaTrend[i - 2])
                k1.append(AlphaTrend[i])

        # print(AlphaTrend)
        # print(len(AlphaTrend))
        

        # df["k1"] = k1
        # df["k2"] = k2
        # print(df["k1"])

        at = pd.DataFrame(data=k1, columns=['k1'])
        at['k2'] = k2
        return at
        # return DataFrame(index=df.index, data={"k1": df["k1"], "k2": df["k2"]})
`

**Comment by batuhanhazarguler** [comment]
i am very new to freqtrade

**Comment by xmatthias** [comment]
well the warning simply says that the dataframe returned is different.
So say we pass in 1000 rows, we may get 500 back, or 1 back ... 
Why this happens is then hidden in the strategy.

The whole code is a mess - 90% of the code in populate_indicators seems to be unused ... so helping you is quite difficult here.

Aside from that - please familiarize yourself with the [common mistakes](https://www.freqtrade.io/en/latest/strategy-customization/#common-mistakes-when-developing-strategies) section of the docs - populate_entry_trend is clearly going against point2 here - which means you'd not be able to backtest this strategy.

**Comment by batuhanhazarguler** [comment]
hello 
Thanks for your interest, I fixed my codes myself
I am currently getting this error

```
 2022-08-08 13:07:11,902 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair BTC/USDT: "None of [Index([False], dtype='object')] are in the [index]"
freqtrade  | 2022-08-08 13:07:11,911 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair BTC/USDT
freqtrade  | 2022-08-08 13:07:16,907 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error "None of [Index([False], dtype='object')] are in the [index]" calling <bound method IStrategy._analyze_ticker_internal of <at_test.FAlphaTrend object at 0x7fce2e133f10>>
freqtrade  | Traceback (most recent call last):
freqtrade  |   File "/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 27, in wrapper
freqtrade  |     return f(*args, **kwargs)
freqtrade  |   File "/freqtrade/freqtrade/strategy/interface.py", line 671, in _analyze_ticker_internal
freqtrade  |     dataframe = self.analyze_ticker(dataframe, metadata)
freqtrade  |   File "/freqtrade/freqtrade/strategy/interface.py", line 651, in analyze_ticker
freqtrade  |     dataframe = self.advise_entry(dataframe, metadata)
freqtrade  |   File "/freqtrade/freqtrade/strategy/interface.py", line 1161, in advise_entry
freqtrade  |     df = self.populate_entry_trend(dataframe, metadata)
freqtrade  |   File "/freqtrade/user_data/strategies/at_test.py", line 60, in populate_entry_trend
freqtrade  |     dataframe.loc[
freqtrade  |   File "/home/ftuser/.local/lib/python3.10/site-packages/pandas/core/indexing.py", line 712, in __setitem__
freqtrade  |     indexer = self._get_setitem_indexer(key)
freqtrade  |   File "/home/ftuser/.local/lib/python3.10/site-packages/pandas/core/indexing.py", line 661, in _get_setitem_indexer
freqtrade  |     return self._convert_tuple(key)
freqtrade  |   File "/home/ftuser/.local/lib/python3.10/site-packages/pandas/core/indexing.py", line 799, in _convert_tuple
freqtrade  |     idx = self._convert_to_indexer(k, axis=i)
freqtrade  |   File "/home/ftuser/.local/lib/python3.10/site-packages/pandas/core/indexing.py", line 1291, in _convert_to_indexer
freqtrade  |     return self._get_listlike_indexer(key, axis)[1]
freqtrade  |   File "/home/ftuser/.local/lib/python3.10/site-packages/pandas/core/indexing.py", line 1327, in _get_listlike_indexer
freqtrade  |     keyarr, indexer = ax._get_indexer_strict(key, axis_name)
freqtrade  |   File "/home/ftuser/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 5782, in _get_indexer_strict
freqtrade  |     self._raise_if_missing(keyarr, indexer, axis_name)
freqtrade  |   File "/home/ftuser/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 5842, in _raise_if_missing
freqtrade  |     raise KeyError(f"None of [{key}] are in the [{axis_name}]")
freqtrade  | KeyError: "None of [Index([False], dtype='object')] are in the [index]"
freqtrade  | 2022-08-08 13:07:16,916 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair BTC/USDT: "None of [Index([False], dtype='object')] are in the [index]"
freqtrade  | 2022-08-08 13:07:16,927 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair BTC/USDT
```


```
       import logging
       from time import sleep
       import pandas as pd
       from numpy.lib import math
       from freqtrade.strategy import IStrategy
       from pandas import DataFrame
       import talib.abstract as ta
       import numpy as np
       import freqtrade.vendor.qtpylib.indicators as qtpylib
       coeff = 1


     class FAlphaTrend(IStrategy):
    # Buy params, Sell params, ROI, Stoploss and Trailing Stop are values generated by 'freqtrade hyperopt --strategy 
     Supertrend --hyperopt-loss ShortTradeDurHyperOptLoss --timerange=20210101- --timeframe=1h --spaces all'
    # It's encourage you find the values that better suites your needs and risk management strategies

    INTERFACE_VERSION: int = 3
    # ROI table:
    minimal_roi = {"0": 0.1, "30": 0.75, "60": 0.05, "120": 0.025}
    # minimal_roi = {"0": 1}

    # Stoploss:
    stoploss = -0.265

    # Trailing stop:
    trailing_stop = True
    trailing_stop_positive = 0.05
    trailing_stop_positive_offset = 0.1
    trailing_only_offset_is_reached = False

    timeframe = "15m"

    startup_candle_count = 500

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        alphatrend = self.generateAlphaTrend(dataframe)
        # alphatrend.to_csv('at.csv', index = False, header=True)

        dataframe['k1'] = alphatrend['k1']

        dataframe['k2'] = alphatrend['k2']

        dataframe["adx"] = ta.ADX(dataframe, timeperiod=14)
        # dataframe["sar"] = ta.SAR(dataframe)

        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        LastCandle = dataframe.iloc[-2].squeeze()
        # k1LastCandle = LastCandle['k1']
        # k2LastCandle = LastCandle['k2']
        # print(k1LastCandle)
        print('lastcandle : ', LastCandle)
        dataframe.loc[
            (   
                (LastCandle["k1"] > LastCandle["k2"]),
            ),
            'enter_long',
        ] = 1

        dataframe.loc[
            (
                (k1LastCandle < k2LastCandle) 
            ),
            "enter_short",
        ] = 1

        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                dataframe["adx"]>60
            ),
            "exit_long",
        ] = 1

        dataframe.loc[
            (
                dataframe["adx"]>60
            ),
            "exit_short",
        ] = 1

        return dataframe

    """
        Supertrend Indicator; adapted for freqtrade
        from: https://github.com/freqtrade/freqtrade-strategies/issues/30
    """


    def generateAlphaTrend(self, dataframe: DataFrame):
        df = dataframe.copy()
        ap = 14


        # atr = "ATR_" + str(ap)
        atr = "ATR"
        df[atr] = ta.ATR(df, timeperiod=ap)

        # df[atr] = ta.ATR(df, timeperiod=ap)
        at = 'k1'
        at2 = 'k2'

        noVolumeData = False
        coeff = 1
        upt = []
        downT = []
        AlphaTrend = [0.0]
        rsi = ta.RSI(df, timeperiod=14)
        
        k1 = []
        k2 = []
        mfi = ta.MFI(df, 14)


        print(at)
        for i in range(len(df['low'])):
            if pd.isna(df[atr][i]):
                upt.append(0)
            else:
                upt.append(df['low'][i] - (df[atr][i] * coeff))

        for i in range(len(df['high'])):
            if pd.isna(df[atr][i]):
               downT.append(0)
            else:
              downT.append(df['high'][i] + (df[atr][i] * coeff))

        for i in range(1, len(df['close'])):
            if noVolumeData is True and rsi[i] >= 50:
                if upt[i] < AlphaTrend[i - 1]:
                    AlphaTrend.append(AlphaTrend[i - 1])
                else:
                   AlphaTrend.append(upt[i])

            elif noVolumeData is False and mfi[i] >= 50:
                if upt[i] < AlphaTrend[i - 1]:
                   AlphaTrend.append(AlphaTrend[i - 1])
                else:
                   AlphaTrend.append(upt[i])
            else:
                if downT[i] > AlphaTrend[i - 1]:
                    AlphaTrend.append(AlphaTrend[i - 1])
                else:
                    AlphaTrend.append(downT[i])

        for i in range(len(AlphaTrend)):
            if i < 2:
                k2.append(0)
                k1.append(AlphaTrend[i])
            else:
                k2.append(AlphaTrend[i - 2])
                k1.append(AlphaTrend[i])



        df[at] = pd.DataFrame(data=k1, columns=['k1'])
        df[at2] = pd.DataFrame(data=k2, columns=['k2'])
        df.fillna(0, inplace=True)
        # df.to_csv('df_at.csv', index = False, header=True)
        # final_df = df.reindex(['date','open','high','low','close','volume','ATR','k1','k2'], axis=1)

        
        #return df
        return DataFrame(index=df.index, data={"k1": df[at], "k2": df[at2]})

    

```

**Comment by xmatthias** [comment]
Let me point you to the [common mistakes](https://www.freqtrade.io/en/latest/strategy-customization/#common-mistakes-when-developing-strategies) page once more - which you either didn't read - or didn't understand (or didn't see it applicable to your strategy).
Using `.iloc[-2]` (instead of `.iloc[-1]` doesn't mitigate the problem - it's just one step further into the problem of using the very last candle of the dataframe - making backtsting of this strategy impossible.

The `LastCandle` variable you have in populate_entry is one row (and a squeezed row at that). you cannot use this in a `.loc` filter - you'll have to use `dataframe['k1']` for the comparison.

so `(LastCandle["k1"] > LastCandle["k2"]),` becomes `(dataframe["k1"] > dataframe["k2"])`. (note that the trailing comma is also wrong and will lead to a different error a little later).

**Comment by batuhanhazarguler** [comment]
You are awesome. All my attempts were due to that trailing comma. I tried something all the time, but the whole problem was caused by commas. Comma took me 2 days. Thank you very much.

**Comment by xmatthias** [comment]
As mentioned above - your strategy will not work correctly due to improper use.

it seems like you are choosing to ignore this - which is fine with me - but don't be surprised if the strategy's forward testing performance does not live up to what it promises.

**Comment by batuhanhazarguler** [comment]
This way it works fine

After adding a few fixes it should work fine.


```
import logging
from time import sleep
import pandas as pd
from numpy.lib import math
from freqtrade.strategy import IStrategy
from pandas import DataFrame
import talib.abstract as ta

import numpy as np

import freqtrade.vendor.qtpylib.indicators as qtpylib


coeff = 1


class FAlphaTrend(IStrategy):
    # Buy params, Sell params, ROI, Stoploss and Trailing Stop are values generated by 'freqtrade hyperopt --strategy Supertrend --hyperopt-loss ShortTradeDurHyperOptLoss --timerange=20210101- --timeframe=1h --spaces all'
    # It's encourage you find the values that better suites your needs and risk management strategies

    INTERFACE_VERSION: int = 3
    # ROI table:
    minimal_roi = {"0": 0.1, "30": 0.75, "60": 0.05, "120": 0.025}
    # minimal_roi = {"0": 1}

    # Stoploss:
    stoploss = -0.265

    # Trailing stop:
    trailing_stop = True
    trailing_stop_positive = 0.05
    trailing_stop_positive_offset = 0.1
    trailing_only_offset_is_reached = False

    timeframe = "15m"

    startup_candle_count = 50

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        alphatrend = self.generateAlphaTrend(dataframe)


        dataframe['k1'] = alphatrend['k1']
        dataframe['k2'] = alphatrend['k2']


        dataframe["adx"] = ta.ADX(dataframe, timeperiod=14)
        # dataframe["sar"] = ta.SAR(dataframe)


        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        dataframe.loc[
            (   
                # (qtpylib.crossed_above(dataframe['k1'] , dataframe['k2']))
                (dataframe['k1'] > dataframe['k2'])
            ),
            'enter_long',
        ] = 1

        dataframe.loc[
            (
                # (qtpylib.crossed_below(dataframe['k1'] , dataframe['k2']))
                (dataframe['k1'] < dataframe['k2'])
            ),
            "enter_short",
        ] = 1

        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                dataframe["adx"]>60
            ),
            "exit_long",
        ] = 1

        dataframe.loc[
            (
                dataframe["adx"]>60
            ),
            "exit_short",
        ] = 1

        return dataframe

    """
        Supertrend Indicator; adapted for freqtrade
        from: https://github.com/freqtrade/freqtrade-strategies/issues/30
    """


    def generateAlphaTrend(self, dataframe: DataFrame):
        df = dataframe.copy()
        ap = 14


        # atr = "ATR_" + str(ap)
        atr = "ATR"
        df[atr] = ta.ATR(df, timeperiod=ap)

        # df[atr] = ta.ATR(df, timeperiod=ap)
        at = 'k1'
        at2 = 'k2'

        noVolumeData = False
        coeff = 1
        upt = []
        downT = []
        AlphaTrend = [0.0]
        rsi = ta.RSI(df, timeperiod=14)
        
        k1 = []
        k2 = []
        mfi = ta.MFI(df, 14)


        print(at)
        for i in range(len(df['low'])):
            if pd.isna(df[atr][i]):
                upt.append(0)
            else:
                upt.append(df['low'][i] - (df[atr][i] * coeff))

        for i in range(len(df['high'])):
            if pd.isna(df[atr][i]):
               downT.append(0)
            else:
              downT.append(df['high'][i] + (df[atr][i] * coeff))

        for i in range(1, len(df['close'])):
            if noVolumeData is True and rsi[i] >= 50:
                if upt[i] < AlphaTrend[i - 1]:
                    AlphaTrend.append(AlphaTrend[i - 1])
                else:
                   AlphaTrend.append(upt[i])

            elif noVolumeData is False and mfi[i] >= 50:
                if upt[i] < AlphaTrend[i - 1]:
                   AlphaTrend.append(AlphaTrend[i - 1])
                else:
                   AlphaTrend.append(upt[i])
            else:
                if downT[i] > AlphaTrend[i - 1]:
                    AlphaTrend.append(AlphaTrend[i - 1])
                else:
                    AlphaTrend.append(downT[i])

        for i in range(len(AlphaTrend)):
            if i < 2:
                k2.append(0)
                k1.append(AlphaTrend[i])
            else:
                k2.append(AlphaTrend[i - 2])
                k1.append(AlphaTrend[i])



        df[at] = pd.DataFrame(data=k1, columns=['k1'])
        df[at2] = pd.DataFrame(data=k2, columns=['k2'])

        df.fillna(0, inplace=True)
        df.to_csv('df_at.csv', index = False, header=True)


        
        return df


    
```

**Comment by batuhanhazarguler** [comment]
Hello, can I ask a question?

In this strategy, the signal is equal in most cases and a continuous buy or sell situation can occur after the equality. In cases where the signal is the same, I want to write the information of the latest status in the signal column. Then if the signal changes, if it goes from buy to sell, I want to take a sell position and vice versa. I hope I was able to explain.

| A | B | C|
| -------- | -------------- |--|
| 1    | 2            | B bigger than A
| 2   | 2            | same
| 2   | 2            | same
| 3   | 2            | A bigger than B
| 3   | 3            | same
| 3   | 3            | same
| 3    | 6            | B bigger than A

i want to do

| A | B | C|
| -------- | -------------- |--|
| 1    | 2            | B bigger than A
| 2   | 2            | B bigger than A
| 2   | 2            | B bigger than A
| 3   | 2            | A bigger than B
| 3   | 3            | A bigger than B
| 3   | 3            | A bigger than B
| 3    | 6            | B bigger than A

My attempt below didn't work.

```
        for x in df.loc[:, "signal"]:
            new_C.append(x if x != "same" else new_C[-1])
        df.loc[:, "signal"] = new_C
```


        ```
        df[at] = pd.DataFrame(data=k1, columns=['k1'])
        df[at2] = pd.DataFrame(data=k2, columns=['k2'])

        conditions  = [ df[at] > df[at2], (df[at] == df[at2]), df[at] < df[at2] ]
        choices     = [ "buy", 'same', 'sell' ]
        df["signal"] = np.select(conditions, choices, default=np.nan)

        new_C = []
        for x in df.loc[:, "signal"]:
            new_C.append(x if x != "same" else new_C[-1])
            print(new_C)
        df.loc[:, "signal"] = new_C # assign new_C as the new "C" column


        df.fillna(0, inplace=True)
        df.to_csv('df_at.csv', index = False, header=True)


        
        return df
```

**Comment by xmatthias** [comment]
Your best friend will be the pandas documentation.
You can use `.shift(1)` to access the prior row's information - as such - you can easily compare `dataframe['col'] > dataframe['col'].shift(1)` to compare how (or if) the prior column changed.

**Comment by batuhanhazarguler** [comment]
First of all, I would like to thank you and Kıvanç Özbilgiç and the onlyfibonacci channel and Çağrı Karakulak and the stackoverflow community.  The strategy I created works exactly as I want, now I just have to test it and use it.  I wanted to share the codes for those who want to benefit and improve.


```



   from datetime import datetime
   import logging
   from time import sleep
   from typing import Optional
   import pandas as pd
   from numpy.lib import math
   from freqtrade.strategy import IStrategy
   from pandas import DataFrame
   import talib.abstract as ta

   import numpy as np

   import freqtrade.vendor.qtpylib.indicators as qtpylib


   coeff = 1


   class FAlphaTrend(IStrategy):
       # Buy params, Sell params, ROI, Stoploss and Trailing Stop are values generated by 'freqtrade hyperopt --strategy Supertrend --hyperopt-loss ShortTradeDurHyperOptLoss --timerange=20210101- --timeframe=1h --spaces all'
       # It's encourage you find the values that better suites your needs and risk management strategies

    INTERFACE_VERSION: int = 3
    # ROI table:
    # minimal_roi = {"0": 0.1, "30": 0.75, "60": 0.05, "120": 0.025}
    # minimal_roi = {"0": 1}
    minimal_roi = {
    #   "0": 0.23096,
    #   "10": 0.06246,
    #   "26": 0.01838,
      "0": 0.1,
      "120": 0.05,
    }

    can_short = True

    # Stoploss:
    # stoploss = -0.265

    stoploss = -0.3
    # Trailing stop:
    trailing_only_offset_is_reached= True
    trailing_stop = True
    trailing_stop_positive = 0.00503
    trailing_stop_positive_offset= 0.0236

    # Trailing stop:
    # trailing_stop = True
    # trailing_stop_positive = 0.05
    # trailing_stop_positive_offset = 0.1
    # trailing_only_offset_is_reached = False

    timeframe = "15m"

    startup_candle_count = 400

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        alphatrend = self.generateAlphaTrend(dataframe)
        # alphatrend.to_csv('at.csv', index = False, header=True)

        dataframe['k1'] = alphatrend['k1']
        dataframe['k2'] = alphatrend['k2']
        dataframe['signal'] = alphatrend['signal']

        # print('batuhan ', dataframe['k1'])
        dataframe["adx"] = ta.ADX(dataframe, timeperiod=14)
        # dataframe["sar"] = ta.SAR(dataframe)
        # dataframe.to_csv('at_data.csv', index = False, header=True)

        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        dataframe.loc[
            (   
                # (qtpylib.crossed_above(dataframe['k1'] , dataframe['k2']))
                (dataframe['k1'] > dataframe['k2']) &
                (dataframe['signal'].shift(1) == 'sell')
            ),
            'enter_long',
        ] = 1

        dataframe.loc[
            (
                # (qtpylib.crossed_below(dataframe['k1'] , dataframe['k2']))
                (dataframe['k1'] < dataframe['k2']) &
                (dataframe['signal'].shift(1) == 'buy')
            ),
            "enter_short",
        ] = 1

        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                (dataframe['k1'] < dataframe['k2']) &
                (dataframe['signal'].shift(1) == 'buy')
            ),
            "exit_long",
        ] = 1

        dataframe.loc[
            (
                (dataframe['k1'] > dataframe['k2']) &
                (dataframe['signal'].shift(1) == 'sell')
            ),
            "exit_short",
        ] = 1

        return dataframe

    """
        Supertrend Indicator; adapted for freqtrade
        from: https://github.com/freqtrade/freqtrade-strategies/issues/30
    """
    def leverage(self, pair: str, current_time: datetime, current_rate: float,
                 proposed_leverage: float, max_leverage: float, entry_tag: Optional[str], side: str,
                 **kwargs) -> float:
        """
        Customize leverage for each new trade. This method is only called in futures mode.

        :param pair: Pair that's currently analyzed
        :param current_time: datetime object, containing the current datetime
        :param current_rate: Rate, calculated based on pricing settings in exit_pricing.
        :param proposed_leverage: A leverage proposed by the bot.
        :param max_leverage: Max leverage allowed on this pair
        :param entry_tag: Optional entry_tag (buy_tag) if provided with the buy signal.
        :param side: 'long' or 'short' - indicating the direction of the proposed trade
        :return: A leverage amount, which is between 1.0 and max_leverage.
        """
        max_leverage = 10
        return max_leverage

    def generateAlphaTrend(self, dataframe: DataFrame):
        df = dataframe.copy()
        ap = 14


        # atr = "ATR_" + str(ap)
        atr = "ATR"
        df[atr] = ta.ATR(df, timeperiod=ap)

        # df[atr] = ta.ATR(df, timeperiod=ap)
        at = 'k1'
        at2 = 'k2'

        noVolumeData = False
        coeff = 1
        upt = []
        downT = []
        AlphaTrend = [0.0]
        rsi = ta.RSI(df['close'], timeperiod=14)
        
        k1 = []
        k2 = []
        signal='signal'
        mfi = ta.MFI(df, 14)


        print(at)
        for i in range(len(df['low'])):
            if pd.isna(df[atr][i]):
                upt.append(0)
            else:
                upt.append(df['low'][i] - (df[atr][i] * coeff))

        for i in range(len(df['high'])):
            if pd.isna(df[atr][i]):
               downT.append(0)
            else:
              downT.append(df['high'][i] + (df[atr][i] * coeff))

        for i in range(1, len(df['close'])):
            if noVolumeData is True and rsi[i] >= 50:
                if upt[i] < AlphaTrend[i - 1]:
                    AlphaTrend.append(AlphaTrend[i - 1])
                else:
                   AlphaTrend.append(upt[i])

            elif noVolumeData is False and mfi[i] >= 50:
                if upt[i] < AlphaTrend[i - 1]:
                   AlphaTrend.append(AlphaTrend[i - 1])
                else:
                   AlphaTrend.append(upt[i])
            else:
                if downT[i] > AlphaTrend[i - 1]:
                    AlphaTrend.append(AlphaTrend[i - 1])
                else:
                    AlphaTrend.append(downT[i])

        for i in range(len(AlphaTrend)):
            if i < 2:
                k2.append(0)
                k1.append(AlphaTrend[i])
            else:
                k2.append(AlphaTrend[i - 2])
                k1.append(AlphaTrend[i])



        df[at] = pd.DataFrame(data=k1, columns=['k1'])
        df[at2] = pd.DataFrame(data=k2, columns=['k2'])

        conditions  = [ df[at] > df[at2], (df[at] == df[at2]), df[at] < df[at2] ]
        choices     = [ "buy", 'same', 'sell' ]
        df["basic_signal"] = np.select(conditions, choices, default=np.nan)

        # new_C = []
        # for x in df.loc[:, "signal"]:
        #     new_C.append(x if x != "same" else new_C[-1])
        #     print(new_C)
        # df.loc[:, "signal"] = new_C # assign new_C as the new "C" column

        previous = "same"
        for i in range(len(df)):
          if df.loc[i,"k1"] == df.loc[i,"k2"]:
            comment = previous
          else:
            comment = "buy" if df.loc[i,"k1"] > df.loc[i,"k2"] else "sell"
          df.loc[i,"signal"] = comment
          previous = comment

        df.fillna(0, inplace=True)
        df.to_csv('df_at.csv', index = False, header=True)


        
        return df


    ```

**Comment by wizcap** [comment]
Thanks, it saves a lot of time.

**Comment by vakanakinci** [comment]
@batuhanhazarguler çok makbule geçti çok teşekkürler.
