### ISSUE TITLE
Database locking error when trades happen in rapid succession

### ISSUE THREAD

**Issue by VanessaE** [freqtrade/freqtrade#7184]
## Describe your environment

  * Operating system: Linux (Debian 11.4)
  * Python Version: 3.9.2
  * CCXT version: 1.91.29 (inside the venv)
  * Freqtrade Version: `develop` branch, commit `a4bada3e`
  * Exchange: Kraken

## Describe the problem:

If I place a few forcebuys one after another, a few seconds apart (as I often do when buying some tokens that tend to move together), sometimes one of those buys will be lost from freqtrade's view.  What I mean is, the bot will successfully place the order on the exchange, the buy will execute and fill normally, but then freqtrade will throw the error below and then fail to add the new trade to its database.

As far as I can tell, the trade is completely lost to freqtrade at that point -- it doesn't seem to retry the failed database insert (or perhaps it does after a lengthy delay?).  I have to go to the exchange, sell the token there, then do the buy again.  This second try usually works.

That's easy enough to catch when doing forcebuys, but occasionally the strategy will see fit to buy a number of pairs all at once, and if that should happen while the user is away, money could be lost.

I thought maybe it was a corrupt or broken trades database, so I tried closing all open trades, shutting down the bot, and deleting the database and the two ancillary files that go with it, then letting the bot recreate what it needs as it starts up, but that didn't help.

This didn't start until after I updated freqtrade on July 31, which put the code at commit `a4bada3e`, as noted above.  I use `setup.sh -u` to do that, so I can at least be sure that all dependencies/libraries are up-to-date also.

`git log -g` shows that freqtrade was at commit `0669d93f` before I updated.  I don't think these errors were happening at that point, but I could be wrong.  Prior to that, freqtrade was at commit `e52f82b5`, and I am 100% certain there were no problems then.

Those two previous updates were pulled on July 11 and July 8, respectively, if I read the log right.  I've been on the `develop` branch the whole time.

I only have one instance of freqtrade running.

### Relevant code exceptions or logs

```
2022-08-05 12:04:06,749 - uvicorn.error - ERROR - Exception in ASGI application                                                                                 
Traceback (most recent call last):                                                                                                                              
  File "/home/vanessa/freqtrade-related/freqtrade-spot/.env/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi              
    result = await app(self.scope, self.receive, self.send)                                                                                                     
  File "/home/vanessa/freqtrade-related/freqtrade-spot/.env/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__              
    return await self.app(scope, receive, send)                                                                                                                 
  File "/home/vanessa/freqtrade-related/freqtrade-spot/.env/lib/python3.9/site-packages/uvicorn/middleware/message_logger.py", line 86, in __call__             
    raise exc from None                                                                                                                                         
  File "/home/vanessa/freqtrade-related/freqtrade-spot/.env/lib/python3.9/site-packages/uvicorn/middleware/message_logger.py", line 82, in __call__             
    await self.app(scope, inner_receive, inner_send)                                                                                                            
  File "/home/vanessa/freqtrade-related/freqtrade-spot/.env/lib/python3.9/site-packages/fastapi/applications.py", line 269, in __call__                         
    await super().__call__(scope, receive, send)                                                                                                                
  File "/home/vanessa/freqtrade-related/freqtrade-spot/.env/lib/python3.9/site-packages/starlette/applications.py", line 124, in __call__                       
    await self.middleware_stack(scope, receive, send)                                                                                                           
  File "/home/vanessa/freqtrade-related/freqtrade-spot/.env/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__                  
    raise exc                                                                                                                                                   
  File "/home/vanessa/freqtrade-related/freqtrade-spot/.env/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__                  
    await self.app(scope, receive, _send)                                                                                                                       
  File "/home/vanessa/freqtrade-related/freqtrade-spot/.env/lib/python3.9/site-packages/starlette/middleware/cors.py", line 92, in __call__                     
    await self.simple_response(scope, receive, send, request_headers=headers)                                                                                   
  File "/home/vanessa/freqtrade-related/freqtrade-spot/.env/lib/python3.9/site-packages/starlette/middleware/cors.py", line 147, in simple_response             
    await self.app(scope, receive, send)                                                                                                                        
  File "/home/vanessa/freqtrade-related/freqtrade-spot/.env/lib/python3.9/site-packages/starlette/exceptions.py", line 93, in __call__                          
    raise exc                                                                                                                                                   
  File "/home/vanessa/freqtrade-related/freqtrade-spot/.env/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/home/vanessa/freqtrade-related/freqtrade-spot/.env/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/vanessa/freqtrade-related/freqtrade-spot/.env/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send) 
  File "/home/vanessa/freqtrade-related/freqtrade-spot/.env/lib/python3.9/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/home/vanessa/freqtrade-related/freqtrade-spot/.env/lib/python3.9/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send) 
  File "/home/vanessa/freqtrade-related/freqtrade-spot/.env/lib/python3.9/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/home/vanessa/freqtrade-related/freqtrade-spot/.env/lib/python3.9/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/home/vanessa/freqtrade-related/freqtrade-spot/.env/lib/python3.9/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/vanessa/freqtrade-related/freqtrade-spot/.env/lib/python3.9/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/vanessa/freqtrade-related/freqtrade-spot/.env/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/vanessa/freqtrade-related/freqtrade-spot/.env/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/vanessa/freqtrade-related/freqtrade-spot/.env/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/vanessa/freqtrade-related/freqtrade-spot/freqtrade/rpc/api_server/api_v1.py", line 148, in force_entry
    trade = rpc._rpc_force_entry(payload.pair, payload.price, order_side=payload.side,
  File "/home/vanessa/freqtrade-related/freqtrade-spot/freqtrade/rpc/rpc.py", line 760, in _rpc_force_entry
    if self._freqtrade.execute_entry(pair, stake_amount, price,
  File "/home/vanessa/freqtrade-related/freqtrade-spot/freqtrade/freqtradebot.py", line 752, in execute_entry
    Trade.commit()
  File "/home/vanessa/freqtrade-related/freqtrade-spot/freqtrade/persistence/trade_model.py", line 1149, in commit
    Trade.query.session.commit()
  File "/home/vanessa/freqtrade-related/freqtrade-spot/.env/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1451, in commit
    self._transaction.commit(_to_root=self.future)
  File "/home/vanessa/freqtrade-related/freqtrade-spot/.env/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 829, in commit
    self._prepare_impl()
  File "/home/vanessa/freqtrade-related/freqtrade-spot/.env/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
    self.session.flush()
  File "/home/vanessa/freqtrade-related/freqtrade-spot/.env/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3383, in flush
    self._flush(objects)
  File "/home/vanessa/freqtrade-related/freqtrade-spot/.env/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3523, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/vanessa/freqtrade-related/freqtrade-spot/.env/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/vanessa/freqtrade-related/freqtrade-spot/.env/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/home/vanessa/freqtrade-related/freqtrade-spot/.env/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3483, in _flush
    flush_context.execute()
  File "/home/vanessa/freqtrade-related/freqtrade-spot/.env/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/home/vanessa/freqtrade-related/freqtrade-spot/.env/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/vanessa/freqtrade-related/freqtrade-spot/.env/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    _emit_insert_statements(
  File "/home/vanessa/freqtrade-related/freqtrade-spot/.env/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1238, in _emit_insert_statements
    result = connection._execute_20(
  File "/home/vanessa/freqtrade-related/freqtrade-spot/.env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1631, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/vanessa/freqtrade-related/freqtrade-spot/.env/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 332, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/vanessa/freqtrade-related/freqtrade-spot/.env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/vanessa/freqtrade-related/freqtrade-spot/.env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "/home/vanessa/freqtrade-related/freqtrade-spot/.env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "/home/vanessa/freqtrade-related/freqtrade-spot/.env/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/home/vanessa/freqtrade-related/freqtrade-spot/.env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/vanessa/freqtrade-related/freqtrade-spot/.env/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: INSERT INTO trades (exchange, pair, base_currency, stake_currency, is_open, fee_open, fee_open_cost, fee_open_currency, fee_close, fee_close_cost, fee_clo
se_currency, open_rate, open_rate_requested, open_trade_value, close_rate, close_rate_requested, realized_profit, close_profit, close_profit_abs, stake_amount, 
amount, amount_requested, open_date, close_date, open_order_id, stop_loss, stop_loss_pct, initial_stop_loss, initial_stop_loss_pct, stoploss_order_id, stoploss_
last_update, max_rate, min_rate, exit_reason, exit_order_status, strategy, enter_tag, timeframe, trading_mode, leverage, is_short, liquidation_price, interest_r
ate, funding_fees) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('kraken', 'SOL/USD', 'SOL', 'USD', 1, 0.0016, None, None, 0.0016, None, None, 40.0, 40.0, 81.69840564923673, None, None, 0.0, None, None, 81.56789
70140143, 2.0391974253503578, 2.0391974253503578, '2022-08-05 16:04:01.743523', None, 'OJKTKV-HVOBS-SYQU32', 0.0, None, 0.0, None, None, None, 0.0, None, None, 
None, 'NostalgiaForInfinityX', 'force_entry', 5, 'SPOT', 1.0, 0, None, 0.0, 0.0)]
```

**Comment by xmatthias** [comment]
so to summarize - `a4bada3e` is a "known bad" commit - and `0669d93f` (or at least `e52f82b5`) are assumed to work fine?

**Comment by VanessaE** [comment]
I think so, but to be sure, my last five updates put me at these commits:

a4bada3ebe5ff927503b067545260ef5fe608c87, 0669d93f563356be3dfd6cb2116fb60a123a5087, e52f82b565fa713951ffc70b84215aab217a1d73, dca639cf26a023a2c410dcee5b846e0c6f94373f, ddb0254999f920dbcd07abe366185cc4b4b9bd3e

The log does go on a bit further, but that last one above was from way back in March.  I am 10000% certain things worked okay then. :smile:

**Comment by xmatthias** [comment]
> That's easy enough to catch when doing forcebuys, but occasionally the strategy will see fit to buy a number of pairs all at once, and if that should happen while the user is away, money could be lost.

It's surely not happening with the strategy - calls via RPC come in (kindof) in parallel - therefore are treated differently.

---

I'm ... currently failing to recreate this - force-buying 8 pairs with parallel requests does not cause this issue for me.
It seems easy to reproduce on your end - which makes a timing problem unlikely, as then i'd have hit this by now

**Comment by xmatthias** [comment]
Can you please test the branch `fix/7184` - and let me know if it happens again?

i'm unable to recreate it reliably enough to know if it is fixed or not.

**Comment by VanessaE** [comment]
I'll give it a go soon.

**Comment by xmatthias** [comment]
Let me know if it works - i have an alternative / additional fix lined up if this doesn't help.

please also keep a close eye on the bot in general - this is a generic setting that will  affect all operations of the bot - but i'm currently not aware where it could cause problems (but you never know).

**Comment by ghost** [comment]
Actually, It's Throwing back the same error

```
2022-08-08 16:51:53,033 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/bot/freqtrade/.env/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/bot/freqtrade/.env/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/bot/freqtrade/.env/lib/python3.8/site-packages/uvicorn/middleware/message_logger.py", line 86, in __call__
    raise exc from None
  File "/home/bot/freqtrade/.env/lib/python3.8/site-packages/uvicorn/middleware/message_logger.py", line 82, in __call__
    await self.app(scope, inner_receive, inner_send)
  File "/home/bot/freqtrade/.env/lib/python3.8/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/home/bot/freqtrade/.env/lib/python3.8/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/bot/freqtrade/.env/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/bot/freqtrade/.env/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/bot/freqtrade/.env/lib/python3.8/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/home/bot/freqtrade/.env/lib/python3.8/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/home/bot/freqtrade/.env/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/home/bot/freqtrade/.env/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/bot/freqtrade/.env/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/bot/freqtrade/.env/lib/python3.8/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/home/bot/freqtrade/.env/lib/python3.8/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/home/bot/freqtrade/.env/lib/python3.8/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/home/bot/freqtrade/.env/lib/python3.8/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/home/bot/freqtrade/.env/lib/python3.8/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/bot/freqtrade/.env/lib/python3.8/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/bot/freqtrade/.env/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/bot/freqtrade/.env/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/bot/freqtrade/.env/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/bot/freqtrade/freqtrade/rpc/api_server/api_v1.py", line 186, in whitelist
    return rpc._rpc_whitelist()
  File "/home/bot/freqtrade/freqtrade/rpc/rpc.py", line 885, in _rpc_whitelist
    res = {'method': self._freqtrade.pairlists.name_list,
AttributeError: 'FreqtradeBot' object has no attribute 'pairlists'
```

**Comment by VanessaE** [comment]
Well, at least you were able to reproduce it :wink:

**Comment by VanessaE** [comment]
This doesn't look like the same error as the one I reported.

**Comment by xmatthias** [comment]
No it's not - and it's reported as #7204 now - i'll therefore hide the comment above.

**Comment by xmatthias** [comment]
with 42eb508, i'm no longer seeing this (although i do have severe problems to reproduce this, and was only able to get it to trigger 2-3 times overall.

It's however clearly not been introduced recently, but was triggered by switching exchanges (to kraken). 
Without kraken, i found no way to reproduce this at all - which suggests it's a timing issue if requests take a long time (kraken's ratelimits are insane).


Should it still appear after updating to this version let me know.
