### ISSUE TITLE
AttributeError 'pairlists' attribute not found

### ISSUE THREAD

**Issue by ghost** [freqtrade/freqtrade#7204]
## Describe your environment

  * Operating system: Ubuntu 18.04
  * Python Version: Python 3.8.13 (`python -V`)
  * CCXT version: ccxt==1.91.55  (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2022.7  (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

Every 10 secs, It throws this error.

### Relevant code exceptions or logs

  ```
 
`2022-08-08 16:51:53,033 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/bot/freqtrade/.env/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/bot/freqtrade/.env/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/bot/freqtrade/.env/lib/python3.8/site-packages/uvicorn/middleware/message_logger.py", line 86, in __call__
    raise exc from None
  File "/home/bot/freqtrade/.env/lib/python3.8/site-packages/uvicorn/middleware/message_logger.py", line 82, in __call__
    await self.app(scope, inner_receive, inner_send)
  File "/home/bot/freqtrade/.env/lib/python3.8/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/home/bot/freqtrade/.env/lib/python3.8/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/bot/freqtrade/.env/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/bot/freqtrade/.env/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/bot/freqtrade/.env/lib/python3.8/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/home/bot/freqtrade/.env/lib/python3.8/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/home/bot/freqtrade/.env/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/home/bot/freqtrade/.env/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/bot/freqtrade/.env/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/bot/freqtrade/.env/lib/python3.8/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/home/bot/freqtrade/.env/lib/python3.8/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/home/bot/freqtrade/.env/lib/python3.8/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/home/bot/freqtrade/.env/lib/python3.8/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/home/bot/freqtrade/.env/lib/python3.8/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/bot/freqtrade/.env/lib/python3.8/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/bot/freqtrade/.env/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/bot/freqtrade/.env/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/bot/freqtrade/.env/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/bot/freqtrade/freqtrade/rpc/api_server/api_v1.py", line 186, in whitelist
    return rpc._rpc_whitelist()
  File "/home/bot/freqtrade/freqtrade/rpc/rpc.py", line 885, in _rpc_whitelist
    res = {'method': self._freqtrade.pairlists.name_list,
AttributeError: 'FreqtradeBot' object has no attribute 'pairlists'`

  ```

**Comment by xmatthias** [comment]
Assuming you're able to reproduce this easily (by restarting the bot for example) - please provide the full log until this error happens for the first time.

I've never seen this, and i see no code-paths that could lead to this either.

**Comment by ghost** [comment]
Thanks It is solved in sudo mode

**Comment by xmatthias** [comment]
Running freqtrade in sudo mode is clearly wrong, and shouldn't be done (and is not needed if the installation was done properly).

if permissions would've been a problem, i doubt you'd have gotten this far either.

**Comment by ghost** [comment]
The thing is i deployed freqtrade in the cloud and in that it i by default in sudo mode

**Comment by zerotn3** [comment]
Please help me how to resolve this bug
