### ISSUE TITLE
freqtrade.commands.trade_commands - ERROR - 'last'

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#7250]
## Describe your environment

  * Operating system: Windows Server 2022
  * Python Version: Current Miniconda (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2022.8.dev (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Multiple Bots dryrunning on gate.io for months with no interruption stopped today, not at the same time, but "from time to time". I just asked the chat support of gate.io, if there is anything about the platform. But there everything is fine.
I had a similar behavior only once, around last Christmas. Otherwise the bots work 24 / 7. 
All bots, which stop, generate this error message:

2022-08-18 16:35:20,299 - freqtrade.worker - INFO - Bot heartbeat. PID=7800, version='2022.8.dev, strategy_version: v11.1.174', state='RUNNING'
2022-08-18 16:35:54,518 - freqtrade.commands.trade_commands - ERROR - 'last'
2022-08-18 16:35:54,518 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "C:\Users\a3\Freqtrade\freqtrade\commands\trade_commands.py", line 19, in start_trading
    worker.run()
  File "C:\Users\a3\Freqtrade\freqtrade\worker.py", line 74, in run
    state = self._worker(old_state=state)
  File "C:\Users\a3\Freqtrade\freqtrade\worker.py", line 114, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
  File "C:\Users\a3\Freqtrade\freqtrade\worker.py", line 139, in _throttle
    result = func(*args, **kwargs)
  File "C:\Users\a3\Freqtrade\freqtrade\worker.py", line 152, in _process_running
    self.freqtrade.process()
  File "C:\Users\a3\Freqtrade\freqtrade\freqtradebot.py", line 187, in process
    self.active_pair_whitelist = self._refresh_active_whitelist(trades)
  File "C:\Users\a3\Freqtrade\freqtrade\freqtradebot.py", line 255, in _refresh_active_whitelist
    self.pairlists.refresh_pairlist()
  File "C:\Users\a3\Freqtrade\freqtrade\plugins\pairlistmanager.py", line 93, in refresh_pairlist
    pairlist = pairlist_handler.filter_pairlist(pairlist, tickers)
  File "C:\Users\a3\Freqtrade\freqtrade\plugins\pairlist\IPairList.py", line 112, in filter_pairlist
    if not self._validate_pair(p, tickers[p] if p in tickers else {}):
  File "C:\Users\a3\Freqtrade\freqtrade\plugins\pairlist\PrecisionFilter.py", line 54, in _validate_pair
    stop_price = ticker['last'] * self._stoploss
KeyError: 'last'
2022-08-18 16:35:54,533 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2022-08-18 16:35:54,533 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2022-08-18 16:35:55,018 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2022-08-18 16:35:55,033 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': warning, 'status': "3 open trades active.\n\nHandle these trades manually on Gate.io, or '/start' the bot again and use '/stopbuy' to handle open trades gracefully. \nNote: Trades are simulated (dry run)."}
2022-08-18 16:35:55,205 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
2022-08-18 16:35:55,205 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.telegram ...
2022-08-18 16:35:55,205 - apscheduler.scheduler - INFO - Scheduler has been shut down
2022-08-18 16:36:05,783 - freqtrade.exchange.exchange - INFO - Closing async ccxt session.

End of code.

I thank you for your help.

. . .by the way: It was the same issue with 2022.5 and 2022.5.1 develop edition of Freqtrade today. I updated to the above edition hoping, that the problem would be away.

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by myNextCoder** [comment]
I paste the code one more time, without "code input", due to better line wrap, hopefully:

2022-08-18 16:35:20,299 - freqtrade.worker - INFO - Bot heartbeat. PID=7800, version='2022.8.dev, strategy_version: v11.1.174', state='RUNNING'
2022-08-18 16:35:54,518 - freqtrade.commands.trade_commands - ERROR - 'last'
2022-08-18 16:35:54,518 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "C:\Users\a3\Freqtrade\freqtrade\commands\trade_commands.py", line 19, in start_trading
    worker.run()
  File "C:\Users\a3\Freqtrade\freqtrade\worker.py", line 74, in run
    state = self._worker(old_state=state)
  File "C:\Users\a3\Freqtrade\freqtrade\worker.py", line 114, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
  File "C:\Users\a3\Freqtrade\freqtrade\worker.py", line 139, in _throttle
    result = func(*args, **kwargs)
  File "C:\Users\a3\Freqtrade\freqtrade\worker.py", line 152, in _process_running
    self.freqtrade.process()
  File "C:\Users\a3\Freqtrade\freqtrade\freqtradebot.py", line 187, in process
    self.active_pair_whitelist = self._refresh_active_whitelist(trades)
  File "C:\Users\a3\Freqtrade\freqtrade\freqtradebot.py", line 255, in _refresh_active_whitelist
    self.pairlists.refresh_pairlist()
  File "C:\Users\a3\Freqtrade\freqtrade\plugins\pairlistmanager.py", line 93, in refresh_pairlist
    pairlist = pairlist_handler.filter_pairlist(pairlist, tickers)
  File "C:\Users\a3\Freqtrade\freqtrade\plugins\pairlist\IPairList.py", line 112, in filter_pairlist
    if not self._validate_pair(p, tickers[p] if p in tickers else {}):
  File "C:\Users\a3\Freqtrade\freqtrade\plugins\pairlist\PrecisionFilter.py", line 54, in _validate_pair
    stop_price = ticker['last'] * self._stoploss
KeyError: 'last'
2022-08-18 16:35:54,533 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2022-08-18 16:35:54,533 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2022-08-18 16:35:55,018 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2022-08-18 16:35:55,033 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': warning, 'status': "3 open trades active.\n\nHandle these trades manually on Gate.io, or '/start' the bot again and use '/stopbuy' to handle open trades gracefully. \nNote: Trades are simulated (dry run)."}
2022-08-18 16:35:55,205 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
2022-08-18 16:35:55,205 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.telegram ...
2022-08-18 16:35:55,205 - apscheduler.scheduler - INFO - Scheduler has been shut down
2022-08-18 16:36:05,783 - freqtrade.exchange.exchange - INFO - Closing async ccxt session.

**Comment by xmatthias** [comment]
The most likely cause is a (new?) pair that didn't have a trade in the last 24h - which is what 'last' usually refers to.

That doesn't really explain a keyerror though - as ccxt will still present "last" - just maybe not with content (so the error should be different).
please make sure to also have updated ccxt - which is (at least in it's current form) always sending "last".

**Comment by myNextCoder** [comment]
I thank you very much. Although I have VolumePairList, I don't allow new pairs to enter the WhiteList: I increment the number of the AgeFilter periodically. Still the WhiteList can alter, of course due to the Pairlistfilters, and have something like a "new pair". I am not sure, if I understand you correctly: There are quite a lot of pairs, which open no trade within a day. I guess, you mean it in a different way. Can you tell me in other words or paste a link, why it may be an issue, as a pair opens no trade in the last 24h?

(. . .I will just update CCXT, of course. . .)
