### ISSUE TITLE
Unable to initialize markets

### ISSUE THREAD

**Issue by Fei-Wang** [freqtrade/freqtrade#7253]
## Describe your environment

  * Operating system: __macOS 12.5.1 (21G83)__
  * Python Version: __Python 3.9.6__ (`python -V`)
  * CCXT version: __1.92.20__ (`pip freeze | grep ccxt`)
  * Freqtrade Version: __freqtrade 2022.8.dev-70a77ba3d__ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*
It was fine the day before yesterday. I updated macos yesterday, and then it stopped working. I have git pulled the latest code and ran pip install -U -r requirements-dev.txt.
I use a proxy in my .zshrc,
 ```export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890```
 Below is the error message:
```
2022-08-19 08:58:34,775 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2022-08-19 08:58:34,779 - freqtrade.exchange.exchange - INFO - Using CCXT 1.92.20
2022-08-19 08:58:34,780 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2022-08-19 08:58:34,789 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 200, 'aiohttp_trust_env': True}
2022-08-19 08:58:34,798 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2022-08-19 08:58:44,820 - freqtrade.exchange.exchange - ERROR - Unable to initialize markets.
Traceback (most recent call last):
  File "/Users/feiwang/.pyenv/versions/3.9.6/envs/my3.9/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/Users/feiwang/.pyenv/versions/3.9.6/envs/my3.9/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/Users/feiwang/.pyenv/versions/3.9.6/envs/my3.9/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/feiwang/.pyenv/versions/3.9.6/envs/my3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/feiwang/.pyenv/versions/3.9.6/envs/my3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/feiwang/.pyenv/versions/3.9.6/envs/my3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Users/feiwang/.pyenv/versions/3.9.6/envs/my3.9/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/Users/feiwang/.pyenv/versions/3.9.6/envs/my3.9/lib/python3.9/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x139998e20>, 'Connection to api.binance.com timed out. (connect timeout=10)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/feiwang/.pyenv/versions/3.9.6/envs/my3.9/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/Users/feiwang/.pyenv/versions/3.9.6/envs/my3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Users/feiwang/.pyenv/versions/3.9.6/envs/my3.9/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /sapi/v1/capital/config/getall?timestamp=1660870714798&recvWindow=10000&signature=9b8ecc69cb0689b0086da75b7b7248810f9a57a1446676d15e264cc30492f33b (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x139998e20>, 'Connection to api.binance.com timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/feiwang/.pyenv/versions/3.9.6/envs/my3.9/lib/python3.9/site-packages/ccxt/base/exchange.py", line 594, in fetch
    response = self.session.request(
  File "/Users/feiwang/.pyenv/versions/3.9.6/envs/my3.9/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/feiwang/.pyenv/versions/3.9.6/envs/my3.9/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/Users/feiwang/.pyenv/versions/3.9.6/envs/my3.9/lib/python3.9/site-packages/requests/adapters.py", line 553, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /sapi/v1/capital/config/getall?timestamp=1660870714798&recvWindow=10000&signature=9b8ecc69cb0689b0086da75b7b7248810f9a57a1446676d15e264cc30492f33b (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x139998e20>, 'Connection to api.binance.com timed out. (connect timeout=10)'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/feiwang/Documents/code/freqtrade/freqtrade/exchange/exchange.py", line 476, in _load_markets
    self._markets = self._api.load_markets()
  File "/Users/feiwang/.pyenv/versions/3.9.6/envs/my3.9/lib/python3.9/site-packages/ccxt/base/exchange.py", line 1447, in load_markets
    currencies = self.fetch_currencies()
  File "/Users/feiwang/.pyenv/versions/3.9.6/envs/my3.9/lib/python3.9/site-packages/ccxt/binance.py", line 1308, in fetch_currencies
    response = self.sapiGetCapitalConfigGetall(params)
  File "/Users/feiwang/.pyenv/versions/3.9.6/envs/my3.9/lib/python3.9/site-packages/ccxt/base/exchange.py", line 500, in inner
    return entry(_self, **inner_kwargs)
  File "/Users/feiwang/.pyenv/versions/3.9.6/envs/my3.9/lib/python3.9/site-packages/ccxt/binance.py", line 5512, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "/Users/feiwang/.pyenv/versions/3.9.6/envs/my3.9/lib/python3.9/site-packages/ccxt/base/exchange.py", line 2624, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/Users/feiwang/.pyenv/versions/3.9.6/envs/my3.9/lib/python3.9/site-packages/ccxt/base/exchange.py", line 624, in fetch
    raise RequestTimeout(details) from e
ccxt.base.errors.RequestTimeout: binance GET https://api.binance.com/sapi/v1/capital/config/getall?timestamp=1660870714798&recvWindow=10000&signature=9b8ecc69cb0689b0086da75b7b7248810f9a57a1446676d15e264cc30492f33b
2022-08-19 08:58:44,837 - freqtrade.commands.trade_commands - ERROR - Could not load markets, therefore cannot start. Please investigate the above error for more details.
2022-08-19 08:58:44,837 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/Users/feiwang/Documents/code/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/Users/feiwang/Documents/code/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/Users/feiwang/Documents/code/freqtrade/freqtrade/worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/Users/feiwang/Documents/code/freqtrade/freqtrade/freqtradebot.py", line 69, in __init__
    self.exchange = ExchangeResolver.load_exchange(
  File "/Users/feiwang/Documents/code/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 33, in load_exchange
    exchange = ExchangeResolver._load_exchange(
  File "/Users/feiwang/Documents/code/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 59, in _load_exchange
    exchange = ex_class(**kwargs)
  File "/Users/feiwang/Documents/code/freqtrade/freqtrade/exchange/exchange.py", line 184, in __init__
    self.validate_config(config)
  File "/Users/feiwang/Documents/code/freqtrade/freqtrade/exchange/exchange.py", line 214, in validate_config
    self.validate_stakecurrency(config['stake_currency'])
  File "/Users/feiwang/Documents/code/freqtrade/freqtrade/exchange/exchange.py", line 511, in validate_stakecurrency
    raise OperationalException(
freqtrade.exceptions.OperationalException: Could not load markets, therefore cannot start. Please investigate the above error for more details.
```

**Comment by xmatthias** [comment]
Well it's a connection timeout.
This is always a network level problem - and since you're using a proxy, it can be one of the following things:

* the proxy is down / not reachable
* your network is down / has problems
* the exchange is down / has problems 

Based on the initial exception (`socket.timeout: timed out`) - i'd assume nobody/nothing is answering at `http://127.0.0.1:7890` - so the socket times out (and subsequently, all other attempts also fail).
