### ISSUE TITLE
Problem with downloading data from kraken

### ISSUE THREAD

**Issue by Lukkyz** [freqtrade/freqtrade#7285]
## Describe your environment

  * Operating system: Debian 11 Bullseye
  * Python Version: Python 3.9.2
  * CCXT version: 1.92.53 
  * Freqtrade Version: 2022.7 

## Describe the problem:

I'm unable to download data from Kraken API, I've set the rateLimit to 3100 like said in the doc but nothing happens.
 
### Relevant code exceptions or logs

  ```
 freqtrade download-data -t 1h
2022-08-22 19:19:05,470 - freqtrade.configuration.load_config - INFO - Using config: user_data/config.json ...
2022-08-22 19:19:05,471 - freqtrade.loggers - INFO - Verbosity set to 0
2022-08-22 19:19:05,471 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/lucas/user_data ...
2022-08-22 19:19:05,471 - freqtrade.configuration.configuration - INFO - Using data directory: /home/lucas/user_data/data/kraken ...
2022-08-22 19:19:05,471 - freqtrade.configuration.configuration - INFO - timeframes --timeframes: ['1h']
2022-08-22 19:19:05,472 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2022-08-22 19:19:05,474 - freqtrade.configuration.check_exchange - INFO - Exchange "kraken" is officially supported by the Freqtrade development team.
2022-08-22 19:19:05,474 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2022-08-22 19:19:05,474 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2022-08-22 19:19:05,477 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2022-08-22 19:19:05,477 - freqtrade.exchange.exchange - INFO - Using CCXT 1.92.53
2022-08-22 19:19:05,477 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2022-08-22 19:19:05,479 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 3100}
2022-08-22 19:19:05,481 - freqtrade.exchange.exchange - INFO - Using Exchange "Kraken"
2022-08-22 19:19:05,481 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Kraken'...
2022-08-22 19:19:05,481 - freqtrade.exchange.exchange - INFO - Markets were not loaded. Loading them now..
2022-08-22 19:19:09,174 - freqtrade.commands.data_commands - INFO - About to download pairs: [], intervals: ['1h'] to /home/lucas/user_data/data/kraken
2022-08-22 19:19:09,174 - freqtrade.exchange.exchange - INFO - Closing async ccxt session.
  ```

**Comment by xmatthias** [comment]
based on the log output, there's no pairs in the pairlist (`About to download pairs: [], `) - so there's nothing for the bot to do and it exits again.

you can specify pairs either via `--pairs ETH/EUR BTC/EUR`, via regex `--pairs .*/EUR` - or via pairlists configuration in the configuration.

Please also make sure that `download_trades` is set to true in the configuration - otherwise downloading data from kraken will not work.

**Comment by Lukkyz** [comment]
Ok thank you,. 
But now I have another error : 
```
Traceback (most recent call last):
  File "/home/lucas/.local/lib/python3.9/site-packages/freqtrade/data/history/history_utils.py", line 365, in _download_trades_history
    since=since,
UnboundLocalError: local variable 'since' referenced before assignment
2022-08-22 20:33:08,512 - freqtrade.data.history.history_utils - ERROR - Could not convert BTC/EUR to OHLCV.
Traceback (most recent call last):
  File "/home/lucas/.local/lib/python3.9/site-packages/freqtrade/data/history/history_utils.py", line 438, in convert_trades_to_ohlcv
    ohlcv = trades_to_ohlcv(trades, timeframe)
  File "/home/lucas/.local/lib/python3.9/site-packages/freqtrade/data/converter.py", line 226, in trades_to_ohlcv
    raise ValueError('Trade-list empty.')
ValueError: Trade-list empty.
```

**Comment by xmatthias** [comment]
what's the  command you're running? (as well as the full log output ... )

**Comment by Lukkyz** [comment]
```
freqtrade download-data
2022-08-22 20:51:50,088 - freqtrade.configuration.load_config - INFO - Using config: user_data/config.json ...
2022-08-22 20:51:50,089 - freqtrade.loggers - INFO - Verbosity set to 0
2022-08-22 20:51:50,090 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/lucas/user_data ...
2022-08-22 20:51:50,090 - freqtrade.configuration.configuration - INFO - Using data directory: /home/lucas/user_data/data/kraken ...
2022-08-22 20:51:50,090 - freqtrade.configuration.configuration - INFO - timeframes --timeframes: ['1m', '5m']
2022-08-22 20:51:50,090 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2022-08-22 20:51:50,093 - freqtrade.configuration.check_exchange - INFO - Exchange "kraken" is officially supported by the Freqtrade development team.
2022-08-22 20:51:50,093 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2022-08-22 20:51:50,093 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2022-08-22 20:51:50,096 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2022-08-22 20:51:50,096 - freqtrade.exchange.exchange - INFO - Using CCXT 1.92.53
2022-08-22 20:51:50,097 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2022-08-22 20:51:50,099 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimits': 3100}
2022-08-22 20:51:50,102 - freqtrade.exchange.exchange - INFO - Using Exchange "Kraken"
2022-08-22 20:51:50,102 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Kraken'...
2022-08-22 20:51:50,102 - freqtrade.exchange.exchange - INFO - Markets were not loaded. Loading them now..
2022-08-22 20:51:56,872 - freqtrade.commands.data_commands - INFO - About to download pairs: ['BTC/EUR'], intervals: ['1m', '5m'] to /home/lucas/user_data/data/kraken
2022-08-22 20:51:56,873 - freqtrade.data.history.history_utils - INFO - Downloading trades for pair BTC/EUR.
2022-08-22 20:51:56,873 - freqtrade.data.history.history_utils - INFO - Current Amount of trades: 0
2022-08-22 20:51:56,873 - freqtrade.data.history.history_utils - ERROR - Failed to download historic trades for pair: "BTC/EUR". 
Traceback (most recent call last):
  File "/home/lucas/.local/lib/python3.9/site-packages/freqtrade/data/history/history_utils.py", line 365, in _download_trades_history
    since=since,
UnboundLocalError: local variable 'since' referenced before assignment
2022-08-22 20:51:56,873 - freqtrade.data.history.history_utils - ERROR - Could not convert BTC/EUR to OHLCV.
Traceback (most recent call last):
  File "/home/lucas/.local/lib/python3.9/site-packages/freqtrade/data/history/history_utils.py", line 438, in convert_trades_to_ohlcv
    ohlcv = trades_to_ohlcv(trades, timeframe)
  File "/home/lucas/.local/lib/python3.9/site-packages/freqtrade/data/converter.py", line 226, in trades_to_ohlcv
    raise ValueError('Trade-list empty.')
ValueError: Trade-list empty.
2022-08-22 20:51:56,874 - freqtrade.data.history.history_utils - ERROR - Could not convert BTC/EUR to OHLCV.
Traceback (most recent call last):
  File "/home/lucas/.local/lib/python3.9/site-packages/freqtrade/data/history/history_utils.py", line 438, in convert_trades_to_ohlcv
    ohlcv = trades_to_ohlcv(trades, timeframe)
  File "/home/lucas/.local/lib/python3.9/site-packages/freqtrade/data/converter.py", line 226, in trades_to_ohlcv
    raise ValueError('Trade-list empty.')
ValueError: Trade-list empty.
```
`download_trades`is set to true

**Comment by xmatthias** [comment]
For now - you will have to use either `--days` or `--timerange <startdate>` explicitly to work around this.

I'll be pushing a fix to this to develop soon.

**Comment by danwalt2000** [comment]
Had the same issue with binance exchange (Ubuntu VPS). Found out that function `expand_pairlist` in freqtrade/plugins/pairlist/pairlist_helpers.py always returns an empty list. 
For some reason this code is not working
`result_partial = [ pair for pair in available_pairs if re.fullmatch(comp, pair) ]`
So I had to replace regex check with manual one (works only with :USDT postfix like BTC/USDT:USDT)
`for pair in available_pairs:
    lst = list(pair)
    pair_clean = ''.join(lst[:-5])
    if pair_wc == pair_clean:
        result += [pair]`
Still have no idea why the issue reproduces (maybe re library is not working well or python version differs), but I understand that my solution is quite dirty.

**Comment by stash86** [comment]
sorry, I have to hide your comment, because
1. Off topic
2. old issue
3. I never experience any issue with downloading data from binance until now.

Please open new issue if you still have the error, but please fill in the required info in the template
