### ISSUE TITLE
Error : Pair BTC/USDT is not available on Gate.io futures. Please remove BTC/USDT from your whitelist

### ISSUE THREAD

**Issue by djienne** [freqtrade/freqtrade#7334]
## Describe your environment

  * Operating system: Ubuntu 20.04
  * Latest FreqTrade Docker Hub image (02/09/2022), similar problem observed in 2022.6 and 2022.7 docker images (did not try other)

## Describe the problem:
When I try to run Freqtrade on Gate.io futures with a basic strategy (the strategy is fine and works on spot and on Binance), I get the error `freqtrade.exceptions.OperationalException: Pair BTC/USDT is not available on Gate.io futures. Please remove BTC/USDT from your whitelist.` .

### Config file:
```
{
    "max_open_trades": 6,
    "stake_currency": "USDT",
    "stake_amount": "unlimited",
    "tradable_balance_ratio": 0.99,
    "amount_reserve_percent": 0.01,
    "fiat_display_currency": "USD",
    "dry_run": true,
    "fee": 0.0005,
    "cancel_open_orders_on_exit": false,
    "trading_mode": "futures",
    "margin_mode": "isolated",
    "unfilledtimeout": {
        "entry": 15,
        "exit": 15,
        "exit_timeout_count": 10,
        "unit": "seconds"
    },
    "entry_pricing": {
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1,
        "price_last_balance": 0.0,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "exit_pricing": {
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1
    },
    "exchange": {
        "name": "gateio",
        "key": "",
        "secret": "",
        "ccxt_config": {

        },
        "ccxt_async_config": {

        },
        "pair_whitelist": [
            "BTC/USDT",
            "ETH/USDT",
            "BNB/USDT",
            "XRP/USDT",
            "ADA/USDT",
            "SOL/USDT",
            "DOT/USDT",
            "TRX/USDT",
            "AVAX/USDT",
            "MATIC/USDT",
            "LTC/USDT",
            "FTT/USDT",
            "CHZ/USDT",
            "UNI/USDT",
            "XMR/USDT",
            "XLM/USDT",
            "NEAR/USDT",
            "ALGO/USDT",
            "ATOM/USDT",
            "ETC/USDT",
            "VET/USDT",
            "MANA/USDT",
            "APE/USDT",
            "XTZ/USDT",
            "SAND/USDT",
            "THETA/USDT",
            "EGLD/USDT",
            "EOS/USDT",
            "AAVE/USDT",
            "FTM/USDT",
            "DOGE/USDT"
        ],
        "pair_blacklist": []
    },
    "pairlists": [
        {
            "method": "StaticPairList",
            "number_assets": 31,
            "sort_key": "quoteVolume",
            "min_value": 0,
            "refresh_period": 1800
        }
    ],
    "edge": {
        "enabled": false,
        "process_throttle_secs": 3600,
        "calculate_since_number_of_days": 7,
        "allowed_risk": 0.01,
        "stoploss_range_min": -0.01,
        "stoploss_range_max": -0.1,
        "stoploss_range_step": -0.01,
        "minimum_winrate": 0.60,
        "minimum_expectancy": 0.20,
        "min_trade_number": 10,
        "max_trade_duration_minute": 1440,
        "remove_pumps": false
    },
    "telegram": {
        "enabled": false,
        "token": "",
        "chat_id": ""
    },
    "api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8080,
        "verbosity": "error",
        "enable_openapi": false,
        "Force_entry":true,
        "forcebuy_enable": true,
        "force_entry_enable": true,
        "jwt_secret_key": "d1654caf3c530f6b037ae59a999d9d9328dec66bdd68799112cf1ba7d65276a3",
        "CORS_origins": [],
        "username": "",
        "password": ""
    },
    "bot_name": "freqtrade_ST",
    "initial_state": "running",
    "force_entry_enable": true,
    "internals": {
        "process_throttle_secs": 5
    }
}
```
### Relevant code exceptions or logs

  ```
freqtradeSR  | 2022-09-02 09:27:52,312 - freqtrade.worker - INFO - Starting worker docker-b53791fe
freqtradeSR  | 2022-09-02 09:27:52,312 - freqtrade.configuration.load_config - INFO - Using config: /freqtrade/user_data/config_backtest_LongShort.json ...
freqtradeSR  | 2022-09-02 09:27:52,313 - freqtrade.loggers - INFO - Verbosity set to 0
freqtradeSR  | 2022-09-02 09:27:52,313 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
freqtradeSR  | 2022-09-02 09:27:52,314 - freqtrade.configuration.configuration - INFO - Parameter --db-url detected ...
freqtradeSR  | 2022-09-02 09:27:52,314 - freqtrade.configuration.configuration - WARNING - `force_entry_enable` RPC message enabled.
freqtradeSR  | 2022-09-02 09:27:52,314 - freqtrade.configuration.configuration - INFO - Dry run is enabled
freqtradeSR  | 2022-09-02 09:27:52,314 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:////freqtrade/user_data/trades_SR_real_dry_LS.sqlite"
freqtradeSR  | 2022-09-02 09:27:52,314 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 6 ...
freqtradeSR  | 2022-09-02 09:27:52,329 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
freqtradeSR  | 2022-09-02 09:27:52,329 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/gateio ...
freqtradeSR  | 2022-09-02 09:27:52,330 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
freqtradeSR  | 2022-09-02 09:27:52,346 - freqtrade.configuration.check_exchange - INFO - Exchange "gateio" is officially supported by the Freqtrade development team.
freqtradeSR  | 2022-09-02 09:27:52,346 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
freqtradeSR  | 2022-09-02 09:27:52,347 - freqtrade.freqtradebot - INFO - Starting freqtrade docker-b53791fe
freqtradeSR  | 2022-09-02 09:27:52,410 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy SuperReversal_mtf_LongShort from '/freqtrade/user_data/strategies/SuperReversal_mtf_LongShort.py'...
freqtradeSR  | 2022-09-02 09:27:52,410 - freqtrade.strategy.hyper - INFO - Found no parameter file.
freqtradeSR  | 2022-09-02 09:27:52,411 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
freqtradeSR  | 2022-09-02 09:27:52,411 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: unlimited.
freqtradeSR  | 2022-09-02 09:27:52,411 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'entry': 15, 'exit': 15, 'exit_timeout_count': 10, 'unit': 'seconds'}.
freqtradeSR  | 2022-09-02 09:27:52,411 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 100.0}
freqtradeSR  | 2022-09-02 09:27:52,412 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 15m
freqtradeSR  | 2022-09-02 09:27:52,412 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -1.0
freqtradeSR  | 2022-09-02 09:27:52,412 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
freqtradeSR  | 2022-09-02 09:27:52,412 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
freqtradeSR  | 2022-09-02 09:27:52,412 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
freqtradeSR  | 2022-09-02 09:27:52,412 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
freqtradeSR  | 2022-09-02 09:27:52,413 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
freqtradeSR  | 2022-09-02 09:27:52,413 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'emergency_exit': 'limit', 'entry': 'limit', 'exit': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': True, 'stoploss_on_exchange_interval': 60, 'stoploss_on_exchange_limit_ratio': 0.99}
freqtradeSR  | 2022-09-02 09:27:52,413 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'entry': 'gtc', 'exit': 'gtc'}
freqtradeSR  | 2022-09-02 09:27:52,413 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
freqtradeSR  | 2022-09-02 09:27:52,413 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: unlimited
freqtradeSR  | 2022-09-02 09:27:52,413 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
freqtradeSR  | 2022-09-02 09:27:52,413 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 500
freqtradeSR  | 2022-09-02 09:27:52,413 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'entry': 15, 'exit': 15, 'exit_timeout_count': 10, 'unit': 'seconds'}
freqtradeSR  | 2022-09-02 09:27:52,413 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_exit_signal: True
freqtradeSR  | 2022-09-02 09:27:52,414 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_only: False
freqtradeSR  | 2022-09-02 09:27:52,414 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_entry_signal: False
freqtradeSR  | 2022-09-02 09:27:52,414 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_offset: 0.0
freqtradeSR  | 2022-09-02 09:27:52,414 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
freqtradeSR  | 2022-09-02 09:27:52,414 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
freqtradeSR  | 2022-09-02 09:27:52,414 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: False
freqtradeSR  | 2022-09-02 09:27:52,414 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1
freqtradeSR  | 2022-09-02 09:27:52,415 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
freqtradeSR  | 2022-09-02 09:27:52,418 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
freqtradeSR  | 2022-09-02 09:27:52,419 - freqtrade.exchange.exchange - INFO - Using CCXT 1.92.84
freqtradeSR  | 2022-09-02 09:27:52,419 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}}
freqtradeSR  | 2022-09-02 09:27:52,424 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}}
freqtradeSR  | 2022-09-02 09:27:52,432 - freqtrade.exchange.exchange - INFO - Using Exchange "Gate.io"
freqtradeSR  | 2022-09-02 09:27:57,840 - freqtrade.commands.trade_commands - ERROR - Pair BTC/USDT is not available on Gate.io futures. Please remove BTC/USDT from your whitelist.
freqtradeSR  | 2022-09-02 09:27:57,841 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
freqtradeSR  | Traceback (most recent call last):
freqtradeSR  |   File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
freqtradeSR  |     worker = Worker(args)
freqtradeSR  |   File "/freqtrade/freqtrade/worker.py", line 35, in __init__
freqtradeSR  |     self._init(False)
freqtradeSR  |   File "/freqtrade/freqtrade/worker.py", line 52, in _init
freqtradeSR  |     self.freqtrade = FreqtradeBot(self._config)
freqtradeSR  |   File "/freqtrade/freqtrade/freqtradebot.py", line 68, in __init__
freqtradeSR  |     self.exchange = ExchangeResolver.load_exchange(
freqtradeSR  |   File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 33, in load_exchange
freqtradeSR  |     exchange = ExchangeResolver._load_exchange(
freqtradeSR  |   File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 59, in _load_exchange
freqtradeSR  |     exchange = ex_class(**kwargs)
freqtradeSR  |   File "/freqtrade/freqtrade/exchange/exchange.py", line 186, in __init__
freqtradeSR  |     self.validate_config(config)
freqtradeSR  |   File "/freqtrade/freqtrade/exchange/exchange.py", line 218, in validate_config
freqtradeSR  |     self.validate_pairs(config['exchange']['pair_whitelist'])
freqtradeSR  |   File "/freqtrade/freqtrade/exchange/exchange.py", line 533, in validate_pairs
freqtradeSR  |     raise OperationalException(
freqtradeSR  | freqtrade.exceptions.OperationalException: Pair BTC/USDT is not available on Gate.io futures. Please remove BTC/USDT from your whitelist.
  ```

**Comment by xmatthias** [comment]
The correct terminology for futures pairs is `base/quote:settle` - so your pair will have to be BTC/USDT:USDT.

The bot is therefore correct - BTC/USDT does not exist on gateio futures.

**Comment by djienne** [comment]
Thank you very much!
 Remark that BTC/USDT (without :USDT) works on binance futures. I would suggest to add this info in the documentation "exchange specific notes" on Gate.io that pairs in the whitelist should be specified with the format BTC/USDT:USDT

**Comment by xmatthias** [comment]
It's binance that's special in this instance, as ccxt did not yet switch to the new terminology for binance. 
All other exchanges have their pair-naming aligned to use base/quote:settle.
