### ISSUE TITLE
Bot crashes shortly after start

### ISSUE THREAD

**Issue by dmmargarint** [freqtrade/freqtrade#7451]
## Describe your environment

  * Operating System _Oracle Linux 8__
  * Python Version: __3.8.12___ (`python -V`)
  * CCXT version: _1.91.55____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: __2022.9.dev-923182680__ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

Bot crashes a couple of minutes after starting it. tried cleaning up the sqlite database and didn't help.
It worked fine with the last stable version. 

### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  2022-09-21 16:13:14,924 - freqtrade.commands.trade_commands - ERROR - float() argument must be a string or a number, not 'Precise'
2022-09-21 16:13:14,924 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/opc/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker.run()
  File "/home/opc/freqtrade/freqtrade/worker.py", line 75, in run
    state = self._worker(old_state=state)
  File "/home/opc/freqtrade/freqtrade/worker.py", line 115, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
  File "/home/opc/freqtrade/freqtrade/worker.py", line 140, in _throttle
    result = func(*args, **kwargs)
  File "/home/opc/freqtrade/freqtrade/worker.py", line 153, in _process_running
    self.freqtrade.process()
  File "/home/opc/freqtrade/freqtrade/freqtradebot.py", line 209, in process
    self.exit_positions(trades)
  File "/home/opc/freqtrade/freqtrade/freqtradebot.py", line 983, in exit_positions
    if trade.open_order_id is None and trade.is_open and self.handle_trade(trade):
  File "/home/opc/freqtrade/freqtrade/freqtradebot.py", line 1024, in handle_trade
    if self._check_and_execute_exit(trade, exit_rate, enter, exit_, exit_tag):
  File "/home/opc/freqtrade/freqtrade/freqtradebot.py", line 1035, in _check_and_execute_exit
    exits: List[ExitCheckTuple] = self.strategy.should_exit(
  File "/home/opc/freqtrade/freqtrade/strategy/interface.py", line 980, in should_exit
    current_profit = trade.calc_profit_ratio(current_rate)
  File "/home/opc/freqtrade/freqtrade/persistence/trade_model.py", line 847, in calc_profit_ratio
    close_trade_value = self.calc_close_trade_value(rate, amount)
  File "/home/opc/freqtrade/freqtrade/persistence/trade_model.py", line 793, in calc_close_trade_value
    return float(self._calc_base_close(amount1, rate, self.fee_close))
TypeError: float() argument must be a string or a number, not 'Precise'
  ```

**Comment by xmatthias** [comment]
Please follow the [update instructions](https://www.freqtrade.io/en/latest/updating/) when updating (also on develop versions).
Dependencies (and minimum dependency versions) change - this error happens if the ccxt version is too old.

**Comment by dmmargarint** [comment]
Thanks! I fixed it by removing the .env folder and installing freqtrade essentially from scratch using the install script because the update script didn't fix the problem.
