### ISSUE TITLE
TypeError: float() argument must be a string or a real number, not 'Precise' when backtesting

### ISSUE THREAD

**Issue by Roboticol** [freqtrade/freqtrade#7463]
## Describe your environment

  * Operating system: Windows 11
  * Python Version: 3.10 (`python -V`)
  * CCXT version: 1.90.47 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2022.8 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

I've recently created a new strategy, its name is MA2Strat. The only lines of code I changed were these:
```
        # # SMA - Simple Moving Average
        dataframe['sma1'] = ta.SMA(dataframe, timeperiod=3)
        dataframe['sma2'] = ta.SMA(dataframe, timeperiod=5)
        dataframe['sma3'] = ta.SMA(dataframe, timeperiod=10)
```
```

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators, populates the entry signal for the given dataframe
        :param dataframe: DataFrame
        :param metadata: Additional information, like the currently traded pair
        :return: DataFrame with entry columns populated
        """
        dataframe.loc[
            (
                (dataframe['sma1'] - dataframe['sma1'].shift(1) > 0) &  
                (dataframe['sma2'] - dataframe['sma2'].shift(1) > 0) &  
                (dataframe['sma3'] - dataframe['sma3'].shift(1) > 0) &  
                (dataframe['volume'] > 0)  
            ),
            'enter_long'] = 1
        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators, populates the exit signal for the given dataframe
        :param dataframe: DataFrame
        :param metadata: Additional information, like the currently traded pair
        :return: DataFrame with exit columns populated
        """
        dataframe.loc[
            (
                (dataframe['sma1'] - dataframe['sma1'].shift(1) < 0) &  
                (dataframe['sma2'] - dataframe['sma2'].shift(1) < 0) &  
                (dataframe['sma3'] - dataframe['sma3'].shift(1) < 0) &  
                (dataframe['volume'] > 0)  
            ),
            'exit_long'] = 1
        return dataframe
```
Then, I ran `freqtrade backtesting --timeframe 5m --timerange 20220101-20220201 --strategy MA2Strat`

### Steps to reproduce:

  1. Just copy and paste the changes I made from above.
  2. Run `freqtrade backtesting --timeframe 5m --timerange 20220101-20220201 --strategy MA2Strat`
  3. Error
  
### Observed Results:

What happened:
It gave me the error:
```
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\freqtrade\main.py", line 37, in main
    return_code = args['func'](args)
  File "C:\Python310\lib\site-packages\freqtrade\commands\optimize_commands.py", line 58, in start_backtesting
    backtesting.start()
  File "C:\Python310\lib\site-packages\freqtrade\optimize\backtesting.py", line 1334, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
  File "C:\Python310\lib\site-packages\freqtrade\optimize\backtesting.py", line 1248, in backtest_one_strategy
    results = self.backtest(
  File "C:\Python310\lib\site-packages\freqtrade\optimize\backtesting.py", line 1147, in backtest
    trade = self._enter_trade(pair, row, trade_dir)
  File "C:\Python310\lib\site-packages\freqtrade\optimize\backtesting.py", line 849, in _enter_trade
    trade = LocalTrade(
  File "C:\Python310\lib\site-packages\freqtrade\persistence\trade_model.py", line 407, in __init__
    self.recalc_open_trade_value()
  File "C:\Python310\lib\site-packages\freqtrade\persistence\trade_model.py", line 718, in recalc_open_trade_value
    self.open_trade_value = self._calc_open_trade_value(self.amount, self.open_rate)
  File "C:\Python310\lib\site-packages\freqtrade\persistence\trade_model.py", line 711, in _calc_open_trade_value
    return float(open_trade + fees)
TypeError: float() argument must be a string or a real number, not 'Precise'
```
What I expected to happen:
For the code to run properly and give me my backtesting results

### Relevant code exceptions or logs

Entire error:
```
2022-09-24 22:46:03,465 - freqtrade.configuration.load_config - INFO - Using config: config.json ...
2022-09-24 22:46:03,466 - freqtrade.loggers - INFO - Verbosity set to 0
2022-09-24 22:46:03,466 - freqtrade.configuration.configuration - INFO - Parameter -i/--timeframe detected ... Using timeframe: 5m ...
2022-09-24 22:46:03,466 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 10 ...
2022-09-24 22:46:03,467 - freqtrade.configuration.configuration - INFO - Parameter --timerange detected: 20220101-20220201 ...
2022-09-24 22:46:03,468 - freqtrade.configuration.configuration - INFO - Using user-data directory: D:\machine_learning_projects\freqtrade\user_data ...
2022-09-24 22:46:03,468 - freqtrade.configuration.configuration - INFO - Using data directory: D:\machine_learning_projects\freqtrade\user_data\data\binance ...
2022-09-24 22:46:03,468 - freqtrade.configuration.configuration - INFO - Overriding timeframe with Command line argument
2022-09-24 22:46:03,469 - freqtrade.configuration.configuration - INFO - Parameter --cache=day detected ...
2022-09-24 22:46:03,469 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2022-09-24 22:46:03,480 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2022-09-24 22:46:03,481 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2022-09-24 22:46:03,482 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2022-09-24 22:46:03,485 - freqtrade.commands.optimize_commands - INFO - Starting freqtrade in Backtesting mode
2022-09-24 22:46:03,489 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2022-09-24 22:46:03,490 - freqtrade.exchange.exchange - INFO - Using CCXT 1.90.47
2022-09-24 22:46:03,520 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2022-09-24 22:46:04,661 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
Add {
        "method": "AgeFilter",
        "min_days_listed": 30
},
 to your pairlists in config (Under StaticPairList)
2022-09-24 22:46:04,760 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy MA3Strat from 'D:\machine_learning_projects\freqtrade\user_data\strategies\MA3Strat.py'...
2022-09-24 22:46:04,762 - freqtrade.strategy.hyper - INFO - Found no parameter file.
2022-09-24 22:46:04,763 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 5m.
2022-09-24 22:46:04,763 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2022-09-24 22:46:04,763 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 15.
2022-09-24 22:46:04,764 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}.
2022-09-24 22:46:04,764 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'60': 0.01, '30': 0.02, '0': 0.04}
2022-09-24 22:46:04,764 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 5m
2022-09-24 22:46:04,765 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.1
2022-09-24 22:46:04,765 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2022-09-24 22:46:04,766 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2022-09-24 22:46:04,766 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2022-09-24 22:46:04,766 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2022-09-24 22:46:04,767 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: True
2022-09-24 22:46:04,767 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'entry': 'limit', 'exit': 'limit', 'stoploss': 'market', 'stoploss_on_exchange': False}
2022-09-24 22:46:04,767 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'entry': 'gtc', 'exit': 'gtc'}
2022-09-24 22:46:04,768 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2022-09-24 22:46:04,768 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 15
2022-09-24 22:46:04,768 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2022-09-24 22:46:04,768 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 30
2022-09-24 22:46:04,768 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}
2022-09-24 22:46:04,769 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_exit_signal: True
2022-09-24 22:46:04,769 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_only: False
2022-09-24 22:46:04,769 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_entry_signal: False
2022-09-24 22:46:04,769 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_offset: 0.0
2022-09-24 22:46:04,770 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2022-09-24 22:46:04,770 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2022-09-24 22:46:04,771 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: False
2022-09-24 22:46:04,771 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1
2022-09-24 22:46:04,772 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2022-09-24 22:46:04,790 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from 'C:\Python310\Lib\site-packages\freqtrade\plugins\pairlist\StaticPairList.py'...
2022-09-24 22:46:04,885 - freqtrade.data.history.history_utils - INFO - Using indicator startup period: 30 ...
2022-09-24 22:46:19,808 - freqtrade.data.history.jsondatahandler - ERROR - Could not load data for APE/USDT.
2022-09-24 22:46:19,810 - freqtrade.data.history.idatahandler - WARNING - No history for APE/USDT, spot, 5m found. Use `freqtrade download-data` to download the data
2022-09-24 22:46:23,776 - freqtrade.optimize.backtesting - INFO - Loading data from 2021-12-31 21:30:00 up to 2022-02-01 00:00:00 (31 days).
2022-09-24 22:46:23,776 - freqtrade.optimize.backtesting - INFO - Dataload complete. Calculating indicators
2022-09-24 22:46:23,834 - freqtrade.optimize.backtesting - INFO - Running backtesting for Strategy MA3Strat
2022-09-24 22:46:23,835 - freqtrade.strategy.hyper - INFO - No params for buy found, using default values.
2022-09-24 22:46:23,835 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): buy_rsi = 30
2022-09-24 22:46:23,836 - freqtrade.strategy.hyper - INFO - No params for sell found, using default values.
2022-09-24 22:46:23,836 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): sell_rsi = 70
2022-09-24 22:46:23,836 - freqtrade.strategy.hyper - INFO - No params for protection found, using default values.
2022-09-24 22:46:24,746 - freqtrade.optimize.backtesting - INFO - Backtesting with data from 2022-01-01 00:00:00 up to 2022-02-01 00:00:00 (31 days).
2022-09-24 22:46:26,175 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\freqtrade\main.py", line 37, in main
    return_code = args['func'](args)
  File "C:\Python310\lib\site-packages\freqtrade\commands\optimize_commands.py", line 58, in start_backtesting
    backtesting.start()
  File "C:\Python310\lib\site-packages\freqtrade\optimize\backtesting.py", line 1334, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
  File "C:\Python310\lib\site-packages\freqtrade\optimize\backtesting.py", line 1248, in backtest_one_strategy
    results = self.backtest(
  File "C:\Python310\lib\site-packages\freqtrade\optimize\backtesting.py", line 1147, in backtest
    trade = self._enter_trade(pair, row, trade_dir)
  File "C:\Python310\lib\site-packages\freqtrade\optimize\backtesting.py", line 849, in _enter_trade
    trade = LocalTrade(
  File "C:\Python310\lib\site-packages\freqtrade\persistence\trade_model.py", line 407, in __init__
    self.recalc_open_trade_value()
  File "C:\Python310\lib\site-packages\freqtrade\persistence\trade_model.py", line 718, in recalc_open_trade_value
    self.open_trade_value = self._calc_open_trade_value(self.amount, self.open_rate)
  File "C:\Python310\lib\site-packages\freqtrade\persistence\trade_model.py", line 711, in _calc_open_trade_value
    return float(open_trade + fees)
TypeError: float() argument must be a string or a real number, not 'Precise'
```

Entire Code:
  ```
# pragma pylint: disable=missing-docstring, invalid-name, pointless-string-statement
# flake8: noqa: F401

# --- Do not remove these libs ---
import numpy as np  # noqa
import pandas as pd  # noqa
from pandas import DataFrame  # noqa
from datetime import datetime  # noqa
from typing import Optional, Union  # noqa

from freqtrade.strategy import (BooleanParameter, CategoricalParameter, DecimalParameter,
                                IStrategy, IntParameter)

# --------------------------------
# Add your lib to import here
import talib.abstract as ta
import pandas_ta as pta
import freqtrade.vendor.qtpylib.indicators as qtpylib


class MA3Strat(IStrategy):
    """
    This is a strategy template to get you started.
    More information in https://www.freqtrade.io/en/latest/strategy-customization/

    You can:
        :return: a Dataframe with all mandatory indicators for the strategies
    - Rename the class name (Do not forget to update class_name)
    - Add any methods you want to build your strategy
    - Add any lib you need to build your strategy

    You must keep:
    - the lib in the section "Do not remove these libs"
    - the methods: populate_indicators, populate_entry_trend, populate_exit_trend
    You should keep:
    - timeframe, minimal_roi, stoploss, trailing_*
    """
    # Strategy interface version - allow new iterations of the strategy interface.
    # Check the documentation or the Sample strategy to get the latest version.
    INTERFACE_VERSION = 3

    # Optimal timeframe for the strategy.
    timeframe = '5m'

    # Can this strategy go short?
    can_short: bool = False

    # Minimal ROI designed for the strategy.
    # This attribute will be overridden if the config file contains "minimal_roi".
    minimal_roi = {
        "60": 0.01,
        "30": 0.02,
        "0": 0.04
    }

    # Optimal stoploss designed for the strategy.
    # This attribute will be overridden if the config file contains "stoploss".
    stoploss = -0.10

    # Trailing stoploss
    trailing_stop = False
    # trailing_only_offset_is_reached = False
    # trailing_stop_positive = 0.01
    # trailing_stop_positive_offset = 0.0  # Disabled / not configured

    # Run "populate_indicators()" only for new candle.
    process_only_new_candles = True

    # These values can be overridden in the config.
    use_exit_signal = True
    exit_profit_only = False
    ignore_roi_if_entry_signal = False

    # Number of candles the strategy requires before producing valid signals
    startup_candle_count: int = 30

    # Strategy parameters
    buy_rsi = IntParameter(10, 40, default=30, space="buy")
    sell_rsi = IntParameter(60, 90, default=70, space="sell")

    # Optional order type mapping.
    order_types = {
        'entry': 'limit',
        'exit': 'limit',
        'stoploss': 'market',
        'stoploss_on_exchange': False
    }

    # Optional order time in force.
    order_time_in_force = {
        'entry': 'gtc',
        'exit': 'gtc'
    }
    
    @property
    def plot_config(self):
        return {
            # Main plot indicators (Moving averages, ...)
            'main_plot': {
                'tema': {},
                'sar': {'color': 'white'},
            },
            'subplots': {
                # Subplots - each dict defines one additional plot
                "MACD": {
                    'macd': {'color': 'blue'},
                    'macdsignal': {'color': 'orange'},
                },
                "RSI": {
                    'rsi': {'color': 'red'},
                }
            }
        }

    def informative_pairs(self):
        """
        Define additional, informative pair/interval combinations to be cached from the exchange.
        These pair/interval combinations are non-tradeable, unless they are part
        of the whitelist as well.
        For more information, please consult the documentation
        :return: List of tuples in the format (pair, interval)
            Sample: return [("ETH/USDT", "5m"),
                            ("BTC/USDT", "15m"),
                            ]
        """
        return []

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Adds several different TA indicators to the given DataFrame

        Performance Note: For the best performance be frugal on the number of indicators
        you are using. Let uncomment only the indicator you are using in your strategies
        or your hyperopt configuration, otherwise you will waste your memory and CPU usage.
        :param dataframe: Dataframe with data from the exchange
        :param metadata: Additional information, like the currently traded pair
        :return: a Dataframe with all mandatory indicators for the strategies
        """
        
        # Momentum Indicators
        # ------------------------------------

        # ADX
        dataframe['adx'] = ta.ADX(dataframe)

        # # Plus Directional Indicator / Movement
        # dataframe['plus_dm'] = ta.PLUS_DM(dataframe)
        # dataframe['plus_di'] = ta.PLUS_DI(dataframe)

        # # Minus Directional Indicator / Movement
        # dataframe['minus_dm'] = ta.MINUS_DM(dataframe)
        # dataframe['minus_di'] = ta.MINUS_DI(dataframe)

        # # Aroon, Aroon Oscillator
        # aroon = ta.AROON(dataframe)
        # dataframe['aroonup'] = aroon['aroonup']
        # dataframe['aroondown'] = aroon['aroondown']
        # dataframe['aroonosc'] = ta.AROONOSC(dataframe)

        # # Awesome Oscillator
        # dataframe['ao'] = qtpylib.awesome_oscillator(dataframe)

        # # Keltner Channel
        # keltner = qtpylib.keltner_channel(dataframe)
        # dataframe["kc_upperband"] = keltner["upper"]
        # dataframe["kc_lowerband"] = keltner["lower"]
        # dataframe["kc_middleband"] = keltner["mid"]
        # dataframe["kc_percent"] = (
        #     (dataframe["close"] - dataframe["kc_lowerband"]) /
        #     (dataframe["kc_upperband"] - dataframe["kc_lowerband"])
        # )
        # dataframe["kc_width"] = (
        #     (dataframe["kc_upperband"] - dataframe["kc_lowerband"]) / dataframe["kc_middleband"]
        # )

        # # Ultimate Oscillator
        # dataframe['uo'] = ta.ULTOSC(dataframe)

        # # Commodity Channel Index: values [Oversold:-100, Overbought:100]
        # dataframe['cci'] = ta.CCI(dataframe)

        # RSI
        dataframe['rsi'] = ta.RSI(dataframe)

        # # Inverse Fisher transform on RSI: values [-1.0, 1.0] (https://goo.gl/2JGGoy)
        # rsi = 0.1 * (dataframe['rsi'] - 50)
        # dataframe['fisher_rsi'] = (np.exp(2 * rsi) - 1) / (np.exp(2 * rsi) + 1)

        # # Inverse Fisher transform on RSI normalized: values [0.0, 100.0] (https://goo.gl/2JGGoy)
        # dataframe['fisher_rsi_norma'] = 50 * (dataframe['fisher_rsi'] + 1)

        # # Stochastic Slow
        # stoch = ta.STOCH(dataframe)
        # dataframe['slowd'] = stoch['slowd']
        # dataframe['slowk'] = stoch['slowk']

        # Stochastic Fast
        stoch_fast = ta.STOCHF(dataframe)
        dataframe['fastd'] = stoch_fast['fastd']
        dataframe['fastk'] = stoch_fast['fastk']

        # # Stochastic RSI
        # Please read https://github.com/freqtrade/freqtrade/issues/2961 before using this.
        # STOCHRSI is NOT aligned with tradingview, which may result in non-expected results.
        # stoch_rsi = ta.STOCHRSI(dataframe)
        # dataframe['fastd_rsi'] = stoch_rsi['fastd']
        # dataframe['fastk_rsi'] = stoch_rsi['fastk']

        # MACD
        macd = ta.MACD(dataframe)
        dataframe['macd'] = macd['macd']
        dataframe['macdsignal'] = macd['macdsignal']
        dataframe['macdhist'] = macd['macdhist']

        # MFI
        dataframe['mfi'] = ta.MFI(dataframe)

        # # ROC
        # dataframe['roc'] = ta.ROC(dataframe)

        # Overlap Studies
        # ------------------------------------

        # Bollinger Bands
        bollinger = qtpylib.bollinger_bands(qtpylib.typical_price(dataframe), window=20, stds=2)
        dataframe['bb_lowerband'] = bollinger['lower']
        dataframe['bb_middleband'] = bollinger['mid']
        dataframe['bb_upperband'] = bollinger['upper']
        dataframe["bb_percent"] = (
            (dataframe["close"] - dataframe["bb_lowerband"]) /
            (dataframe["bb_upperband"] - dataframe["bb_lowerband"])
        )
        dataframe["bb_width"] = (
            (dataframe["bb_upperband"] - dataframe["bb_lowerband"]) / dataframe["bb_middleband"]
        )

        # Bollinger Bands - Weighted (EMA based instead of SMA)
        # weighted_bollinger = qtpylib.weighted_bollinger_bands(
        #     qtpylib.typical_price(dataframe), window=20, stds=2
        # )
        # dataframe["wbb_upperband"] = weighted_bollinger["upper"]
        # dataframe["wbb_lowerband"] = weighted_bollinger["lower"]
        # dataframe["wbb_middleband"] = weighted_bollinger["mid"]
        # dataframe["wbb_percent"] = (
        #     (dataframe["close"] - dataframe["wbb_lowerband"]) /
        #     (dataframe["wbb_upperband"] - dataframe["wbb_lowerband"])
        # )
        # dataframe["wbb_width"] = (
        #     (dataframe["wbb_upperband"] - dataframe["wbb_lowerband"]) / dataframe["wbb_middleband"]
        # )

        # # EMA - Exponential Moving Average
        # dataframe['ema3'] = ta.EMA(dataframe, timeperiod=3)
        # dataframe['ema5'] = ta.EMA(dataframe, timeperiod=5)
        # dataframe['ema10'] = ta.EMA(dataframe, timeperiod=10)
        # dataframe['ema21'] = ta.EMA(dataframe, timeperiod=21)
        # dataframe['ema50'] = ta.EMA(dataframe, timeperiod=50)
        # dataframe['ema100'] = ta.EMA(dataframe, timeperiod=100)

        # # SMA - Simple Moving Average
        dataframe['sma1'] = ta.SMA(dataframe, timeperiod=3)
        dataframe['sma2'] = ta.SMA(dataframe, timeperiod=5)
        dataframe['sma3'] = ta.SMA(dataframe, timeperiod=10)
        # dataframe['sma21'] = ta.SMA(dataframe, timeperiod=21)
        # dataframe['sma50'] = ta.SMA(dataframe, timeperiod=50)
        # dataframe['sma100'] = ta.SMA(dataframe, timeperiod=100)

        # Parabolic SAR
        dataframe['sar'] = ta.SAR(dataframe)

        # TEMA - Triple Exponential Moving Average
        dataframe['tema'] = ta.TEMA(dataframe, timeperiod=9)

        # Cycle Indicator
        # ------------------------------------
        # Hilbert Transform Indicator - SineWave
        hilbert = ta.HT_SINE(dataframe)
        dataframe['htsine'] = hilbert['sine']
        dataframe['htleadsine'] = hilbert['leadsine']

        # Pattern Recognition - Bullish candlestick patterns
        # ------------------------------------
        # # Hammer: values [0, 100]
        # dataframe['CDLHAMMER'] = ta.CDLHAMMER(dataframe)
        # # Inverted Hammer: values [0, 100]
        # dataframe['CDLINVERTEDHAMMER'] = ta.CDLINVERTEDHAMMER(dataframe)
        # # Dragonfly Doji: values [0, 100]
        # dataframe['CDLDRAGONFLYDOJI'] = ta.CDLDRAGONFLYDOJI(dataframe)
        # # Piercing Line: values [0, 100]
        # dataframe['CDLPIERCING'] = ta.CDLPIERCING(dataframe) # values [0, 100]
        # # Morningstar: values [0, 100]
        # dataframe['CDLMORNINGSTAR'] = ta.CDLMORNINGSTAR(dataframe) # values [0, 100]
        # # Three White Soldiers: values [0, 100]
        # dataframe['CDL3WHITESOLDIERS'] = ta.CDL3WHITESOLDIERS(dataframe) # values [0, 100]

        # Pattern Recognition - Bearish candlestick patterns
        # ------------------------------------
        # # Hanging Man: values [0, 100]
        # dataframe['CDLHANGINGMAN'] = ta.CDLHANGINGMAN(dataframe)
        # # Shooting Star: values [0, 100]
        # dataframe['CDLSHOOTINGSTAR'] = ta.CDLSHOOTINGSTAR(dataframe)
        # # Gravestone Doji: values [0, 100]
        # dataframe['CDLGRAVESTONEDOJI'] = ta.CDLGRAVESTONEDOJI(dataframe)
        # # Dark Cloud Cover: values [0, 100]
        # dataframe['CDLDARKCLOUDCOVER'] = ta.CDLDARKCLOUDCOVER(dataframe)
        # # Evening Doji Star: values [0, 100]
        # dataframe['CDLEVENINGDOJISTAR'] = ta.CDLEVENINGDOJISTAR(dataframe)
        # # Evening Star: values [0, 100]
        # dataframe['CDLEVENINGSTAR'] = ta.CDLEVENINGSTAR(dataframe)

        # Pattern Recognition - Bullish/Bearish candlestick patterns
        # ------------------------------------
        # # Three Line Strike: values [0, -100, 100]
        # dataframe['CDL3LINESTRIKE'] = ta.CDL3LINESTRIKE(dataframe)
        # # Spinning Top: values [0, -100, 100]
        # dataframe['CDLSPINNINGTOP'] = ta.CDLSPINNINGTOP(dataframe) # values [0, -100, 100]
        # # Engulfing: values [0, -100, 100]
        # dataframe['CDLENGULFING'] = ta.CDLENGULFING(dataframe) # values [0, -100, 100]
        # # Harami: values [0, -100, 100]
        # dataframe['CDLHARAMI'] = ta.CDLHARAMI(dataframe) # values [0, -100, 100]
        # # Three Outside Up/Down: values [0, -100, 100]
        # dataframe['CDL3OUTSIDE'] = ta.CDL3OUTSIDE(dataframe) # values [0, -100, 100]
        # # Three Inside Up/Down: values [0, -100, 100]
        # dataframe['CDL3INSIDE'] = ta.CDL3INSIDE(dataframe) # values [0, -100, 100]

        # # Chart type
        # # ------------------------------------
        # # Heikin Ashi Strategy
        # heikinashi = qtpylib.heikinashi(dataframe)
        # dataframe['ha_open'] = heikinashi['open']
        # dataframe['ha_close'] = heikinashi['close']
        # dataframe['ha_high'] = heikinashi['high']
        # dataframe['ha_low'] = heikinashi['low']

        # Retrieve best bid and best ask from the orderbook
        # ------------------------------------
        """
        # first check if dataprovider is available
        if self.dp:
            if self.dp.runmode.value in ('live', 'dry_run'):
                ob = self.dp.orderbook(metadata['pair'], 1)
                dataframe['best_bid'] = ob['bids'][0][0]
                dataframe['best_ask'] = ob['asks'][0][0]
        """

        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators, populates the entry signal for the given dataframe
        :param dataframe: DataFrame
        :param metadata: Additional information, like the currently traded pair
        :return: DataFrame with entry columns populated
        """
        dataframe.loc[
            (
                (dataframe['sma1'] - dataframe['sma1'].shift(1) > 0) &  
                (dataframe['sma2'] - dataframe['sma2'].shift(1) > 0) &  
                (dataframe['sma3'] - dataframe['sma3'].shift(1) > 0) &  
                (dataframe['volume'] > 0)  
            ),
            'enter_long'] = 1
        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators, populates the exit signal for the given dataframe
        :param dataframe: DataFrame
        :param metadata: Additional information, like the currently traded pair
        :return: DataFrame with exit columns populated
        """
        dataframe.loc[
            (
                (dataframe['sma1'] - dataframe['sma1'].shift(1) < 0) &  
                (dataframe['sma2'] - dataframe['sma2'].shift(1) < 0) &  
                (dataframe['sma3'] - dataframe['sma3'].shift(1) < 0) &  
                (dataframe['volume'] > 0)  
            ),
            'exit_long'] = 1
        return dataframe
    
  ```

**Comment by xmatthias** [comment]
When updating, please make sure to follow the [updating guideline](https://www.freqtrade.io/en/stable/updating/) and also update dependencies.

In your case, it's ccxt that's outdated / too old for the updated freqtrade version.
