### ISSUE TITLE
Startup error of the latest version

### ISSUE THREAD

**Issue by byte-flylf** [freqtrade/freqtrade#7470]
## Describe your environment

  * Operating system: __centos7__
  * Python Version: _Python 3.10.5____ (`python -V`)
  * CCXT version: ___ccxt==1.93.66__ (`pip freeze | grep ccxt`)
  * Freqtrade Version: _freqtrade 2022.9.dev-873eb5f___ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
2022-09-25 23:34:00,979 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): www.okx.com:443
2022-09-25 23:34:02,427 - urllib3.connectionpool - DEBUG - https://www.okx.com:443 "GET /api/v5/public/instruments?instType=SPOT HTTP/1.1" 200 None
2022-09-25 23:34:02,636 - urllib3.connectionpool - DEBUG - https://www.okx.com:443 "GET /api/v5/public/instruments?instType=FUTURES HTTP/1.1" 200 None
2022-09-25 23:34:02,775 - urllib3.connectionpool - DEBUG - https://www.okx.com:443 "GET /api/v5/public/instruments?instType=SWAP HTTP/1.1" 200 None
2022-09-25 23:34:02,917 - urllib3.connectionpool - DEBUG - https://www.okx.com:443 "GET /api/v5/public/instruments?instType=OPTION&uly=BTC-USD HTTP/1.1" 200 None
2022-09-25 23:34:03,919 - freqtrade.exchange.exchange - WARNING - Using 5 calls to get OHLCV. This can result in slower operations for the bot. Please check if you really need 480 candles for your strategy
2022-09-25 23:34:03,921 - freqtrade.misc - DEBUG - Loading historical data from file /root/FT/freqtrade/user_data/data/okx/futures/leverage_tiers_USDT.json
2022-09-25 23:34:04,075 - freqtrade.exchange.exchange - INFO - Using cached leverage_tiers.
2022-09-25 23:34:04,075 - freqtrade.exchange.exchange - INFO - Done initializing 122 markets.
2022-09-25 23:34:04,139 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Okx'...
2022-09-25 23:34:04,238 - freqtrade.persistence.migrations - DEBUG - trying trades_bak0
2022-09-25 23:34:04,239 - freqtrade.persistence.migrations - DEBUG - trying orders_bak0
2022-09-25 23:34:04,239 - freqtrade.persistence.migrations - DEBUG - trying pairlocks_bak0
2022-09-25 23:34:04,261 - freqtrade.commands.trade_commands - ERROR - (sqlite3.OperationalError) near ",": syntax error
[SQL: UPDATE orders SET ft_is_open=? WHERE orders.ft_is_open IS 1 AND ((orders.ft_trade_id, orders.order_id) NOT IN (SELECT trades.id, trades.stoploss_order_id 
FROM trades 
WHERE trades.stoploss_order_id IS NOT NULL)) AND orders.ft_order_side = ? AND orders.order_id LIKE ?]
[parameters: (0, 'stoploss', 'dry%')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2022-09-25 23:34:04,261 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/root/FT/freqtrade/.env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/root/FT/freqtrade/.env/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: near ",": syntax error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/FT/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/root/FT/freqtrade/freqtrade/worker.py", line 36, in __init__
    self._init(False)
  File "/root/FT/freqtrade/freqtrade/worker.py", line 53, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/root/FT/freqtrade/freqtrade/freqtradebot.py", line 70, in __init__
    init_db(self.config['db_url'])
  File "/root/FT/freqtrade/freqtrade/persistence/models.py", line 63, in init_db
    check_migrate(engine, decl_base=_DECL_BASE, previous_tables=previous_tables)
  File "/root/FT/freqtrade/freqtrade/persistence/migrations.py", line 337, in check_migrate
    fix_old_dry_orders(engine)
  File "/root/FT/freqtrade/freqtrade/persistence/migrations.py", line 276, in fix_old_dry_orders
    connection.execute(stmt)
  File "/root/FT/freqtrade/.env/lib/python3.10/site-packages/sqlalchemy/future/engine.py", line 280, in execute
    return self._execute_20(
  File "/root/FT/freqtrade/.env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/root/FT/freqtrade/.env/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/root/FT/freqtrade/.env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/root/FT/freqtrade/.env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/root/FT/freqtrade/.env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/root/FT/freqtrade/.env/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/root/FT/freqtrade/.env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/root/FT/freqtrade/.env/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near ",": syntax error
[SQL: UPDATE orders SET ft_is_open=? WHERE orders.ft_is_open IS 1 AND ((orders.ft_trade_id, orders.order_id) NOT IN (SELECT trades.id, trades.stoploss_order_id 
FROM trades 
WHERE trades.stoploss_order_id IS NOT NULL)) AND orders.ft_order_side = ? AND orders.order_id LIKE ?]
[parameters: (0, 'stoploss', 'dry%')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

  ```

**Comment by byte-flylf** [comment]
set_sqlite_to_wal(engine)
    # fix_old_dry_orders(engine)
If I comment out here, it's OK

**Comment by xmatthias** [comment]
what's your sqlite version? 
you should be able to find out by running `sqlite3` - and then within that shell `select sqlite_version();`.

Alternatively, you can use python directly for this via the following:
 ```
$ python3
import sqlite3
sqlite3.sqlite_version
```


The syntax for this is correct - assuming a more or less recent sqlite version.

**edit** add alternative for version check

**Comment by byte-flylf** [comment]
Python 3.10.5 (main, Aug 13 2022, 20:00:54) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
>>> sqlite3.sqlite_version
'3.7.17'

**Comment by xmatthias** [comment]
That's a sqlite version that's from 2013 - that's >9 years old.
Please understand that we'll not be making changes or efforts to support such old versions.

Most likely, this version doesn't support this feature yet - but simply commenting the above will be risky - as i can't guarantee you won't run into other problems down the road with this version.

I don't think you can update sqlite on centos7 either (at least not without breaking a lot of other things) - so your best bet on centos7 will be to use docker (which brings it's own, updated sqlite version) - or to switch to a different OS version.

**Comment by byte-flylf** [comment]
OK after upgrading sqlite to the latest version
