### ISSUE TITLE
python-telegram-bot 13.14 requires tornado==6.1, but you have tornado 6.2 which is incompatible

### ISSUE THREAD

**Issue by HeinrichHaller** [freqtrade/freqtrade#7484]
## Describe your environment

  * Operating system: Ubuntu LTS
  * Python Version: Python 3.10.7
  * CCXT version: ccxt==1.93.66
  * Freqtrade Version: freqtrade docker-873eb5f2
  

## Describe the problem:

while executing
```
 docker-compose -f docker/docker-compose-jupyter.yml build --pull --no-cache
```
I get the error:
```
ERROR:  pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
python-telegram-bot 13.14 requires tornado==6.1, but you have tornado 6.2 which is incompatible.
```
after 
```
docker-compose -f docker/docker-compose-jupyter.yml up
```
and executing some docker exec freqtrade I get

```
2022-09-26 22:08:44,247 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 800, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (tornado 6.2 (/home/ftuser/.local/lib/python3.10/site-packages), Requirement.parse('tornado==6.1'), {'python-telegram-bot'})

During handling of the above exception, another exception occurred:
```

### Steps to reproduce:

  1. docker-compose -f docker/docker-compose-jupyter.yml build --pull --no-cache
  2.  docker-compose -f docker/docker-compose-jupyter.yml up
  3. executing something via docker exec 
  

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
2022-09-26 22:08:41,518 - freqtrade - INFO - freqtrade docker-873eb5f2
2022-09-26 22:08:41,573 - freqtrade.configuration.load_config - INFO - Using config: user_data/configs/config_X1Z1_test_future.json ...
2022-09-26 22:08:41,574 - freqtrade.loggers - INFO - Verbosity set to 0
2022-09-26 22:08:41,575 - freqtrade.configuration.configuration - INFO - Parameter -i/--timeframe detected ... Using timeframe: 15m ...
2022-09-26 22:08:41,575 - freqtrade.configuration.configuration - INFO - Using max_open_trades: -1 ...
2022-09-26 22:08:41,575 - freqtrade.configuration.configuration - INFO - Parameter --stake-amount detected, overriding stake_amount to: 950.0 ...
2022-09-26 22:08:41,575 - freqtrade.configuration.configuration - INFO - Parameter --dry-run-wallet detected, overriding dry_run_wallet to: 1000.0 ...
2022-09-26 22:08:41,575 - freqtrade.configuration.configuration - INFO - Parameter --timerange detected: 20220415-20220615 ...
2022-09-26 22:08:41,626 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2022-09-26 22:08:41,628 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/binance ...
2022-09-26 22:08:41,628 - freqtrade.configuration.configuration - INFO - Overriding timeframe with Command line argument
2022-09-26 22:08:41,628 - freqtrade.configuration.configuration - INFO - Parameter --epochs detected ... Will run Hyperopt with for 50 epochs ...
2022-09-26 22:08:41,629 - freqtrade.configuration.configuration - INFO - Parameter -s/--spaces detected: default
2022-09-26 22:08:41,629 - freqtrade.configuration.configuration - INFO - Parameter -j/--job-workers detected: -1
2022-09-26 22:08:41,629 - freqtrade.configuration.configuration - INFO - Parameter --min-trades detected: 1
2022-09-26 22:08:41,629 - freqtrade.configuration.configuration - INFO - Using Hyperopt loss class name: OnlyProfitHyperOptLoss
2022-09-26 22:08:41,629 - freqtrade.configuration.configuration - INFO - Using pairs ['BTC/USDT']
2022-09-26 22:08:41,632 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2022-09-26 22:08:41,696 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2022-09-26 22:08:41,696 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2022-09-26 22:08:41,703 - freqtrade.commands.optimize_commands - INFO - Starting freqtrade in Hyperopt mode
2022-09-26 22:08:41,704 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2022-09-26 22:08:41,704 - freqtrade.exchange.exchange - INFO - Using CCXT 1.93.66
2022-09-26 22:08:41,704 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'future'}}
2022-09-26 22:08:41,738 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'future'}}
2022-09-26 22:08:41,767 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2022-09-26 22:08:43,140 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2022-09-26 22:08:44,247 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 800, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (tornado 6.2 (/home/ftuser/.local/lib/python3.10/site-packages), Requirement.parse('tornado==6.1'), {'python-telegram-bot'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 39, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 106, in start_hyperopt
    hyperopt = Hyperopt(config)
  File "/freqtrade/freqtrade/optimize/hyperopt.py", line 82, in __init__
    self.backtesting = Backtesting(self.config)
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 104, in __init__
    self.strategylist.append(StrategyResolver.load_strategy(self.config))
  File "/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 47, in load_strategy
    strategy: IStrategy = StrategyResolver._load_strategy(
  File "/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 255, in _load_strategy
    strategy = StrategyResolver._load_object(
  File "/freqtrade/freqtrade/resolvers/iresolver.py", line 143, in _load_object
    (module, module_path) = cls._search_object(directory=_path,
  File "/freqtrade/freqtrade/resolvers/iresolver.py", line 125, in _search_object
    obj = next(cls._get_valid_object(module_path, object_name), None)
  File "/freqtrade/freqtrade/resolvers/iresolver.py", line 86, in _get_valid_object
    spec.loader.exec_module(module)  # type: ignore # importlib does not use typehints
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/freqtrade/user_data/strategies/BI_Futures_usdt.py", line 17, in <module>
    import pandas_ta as pta
  File "/home/ftuser/.local/lib/python3.10/site-packages/pandas_ta/__init__.py", line 7, in <module>
    from pkg_resources import get_distribution, DistributionNotFound
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3260, in <module>
    def _initialize_master_working_set():
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3272, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 596, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 795, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'tornado==6.1' distribution was not found and is required by python-telegram-bot

  ```

**Comment by xmatthias** [comment]
there's little to no reason to use the jupyter image for regular trading - and i'd advise not to do so (you shouldn't run jupyter in the same container anyway).

python-telegram-bot is hard-pinning dependencies (and almost never updating them) - which is a problem for a library as it can cause this sort of version conflicts.
I've asked them a long time ago to ease these pins - but was told that "they no longer update this version - but will improve this on the future version". 
That's now been over a year ago - they released several minor updates in the meantime - but the dependencies are still hard pinned - in several occasions  hard-pinned to old versions.

Unfortunately, there's nothing we can do for this as it's caused by a library hard-pin.


If you want to run trading and in parallel use jupyter - best setup 2 separate containers (or services, as it's called within the compose file), one using the regular image for trading, and use the jupyter image only for what it's made for - running jupyter. 
I don't think there should be problems with that.

**Comment by HeinrichHaller** [comment]
It simply worked beforehand in this config. 
I do not use the jupyter build for trading/deploy. For trading I use the suggested way on Azure virtual machine.
But I ran the combination hyperopt/ backtesting in the jupyter build. Afterwards I visualized  the 'in and out sample' performance with the strategy_analysis notebook example. 
I'm not from coding but econometrics. Everything docker and so on is a challenge for me.. So best to run the hyperopt/ backtesting combination in a develop or stable build and share the user_data folder with a jupyter build? 
  Thanks

**Comment by HeinrichHaller** [comment]
For clarification, I ran the hyperopt/backtesting combination in a running jupyter build via docker exec.  So I was directly able to visualize the results of the backtesting in a modified strategy_analysis_example notebook.

**Comment by xmatthias** [comment]
sharing user_data should work just fine.

It's also not really a docker problem - but a general problem of 2 projects (python-telegram-bot, jupyterlab) - which both pin dependencies in an incompatible way - which effectively makes it impossible for the 2 projects to be installed in parallel.
