### ISSUE TITLE
Dynamic stoploss and roi (takeprofit) values based on ATR

### ISSUE THREAD

**Issue by tratteo** [freqtrade/freqtrade#7498]
## Describe your environment

  * Operating system: Windows 11
  * Python Version: 3.9
  * CCXT version: 1.92.52
  * Freqtrade Version: 2022.8
  
## Your question
 I am writing an issue as I see that the discussion section is not active. 
I have a strategy that dynamically changes the stoploss and takeprofit for each entered trade and set them based on the ATR value. How can I achieve this in the Freqtrade framework?
I am trying to set the `stoploss` and the `minimal_roi` values in the function `populate_entry_trend(...)` each closed candle, but I am getting the following error when trying a backtest:
```bash
2022-09-29 08:56:15,415 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 58, in start_backtesting
    backtesting.start()
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 1334, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 1248, in backtest_one_strategy
    results = self.backtest(
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 1147, in backtest
    trade = self._enter_trade(pair, row, trade_dir)
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 877, in _enter_trade
    trade.adjust_stop_loss(trade.open_rate, self.strategy.stoploss, initial=True)
  File "/freqtrade/freqtrade/persistence/trade_model.py", line 557, in adjust_stop_loss
    new_loss = float(current_price * (1 - abs(stoploss / leverage)))
  File "/home/ftuser/.local/lib/python3.10/site-packages/pandas/core/series.py", line 191, in wrapper
    raise TypeError(f"cannot convert the series to {converter}")
TypeError: cannot convert the series to <class 'float'>```

Thanks!

**Comment by xmatthias** [comment]
stoploss / roi are not meant to be set form the strategy - and it's value applies globally to whatever it's set at any point (it's not per pair).
you also seem to set a series (a column of values) onto a value that's supposed to be a single number.

You should use the [custom-stoploss](https://www.freqtrade.io/en/stable/strategy-callbacks/#custom-stoploss) and /or [custom-exit](https://www.freqtrade.io/en/stable/strategy-callbacks/#custom-exit-signal) callbacks to set dynamic stoploss / take profit targets.

The settings for "stoploss" and "roi" are static settings not meant to be changed during the runtime of a strategy - and the implications of doing so will not be what you expect from it.

**Comment by tratteo** [comment]
Thanks for the answer I will surely look into that 🤖
