### ISSUE TITLE
Set Position Mode and Asset Mode automatically when bots start

### ISSUE THREAD

**Issue by liaogx** [freqtrade/freqtrade#7505]
## Describe your environment

 * Operating system: MacOS Monterey 12.5.1
 * Python Version: 3.8.5
 * CCXT version: 1.92.20
 * Freqtrade Version: freqtrade 2022.8 stable

## Describe the problem

Take binance for an example, when it comes to futures trading, freqtrade support `isolated` margin mode and

- **One-way Mode**
<img width="637" alt="image" src="https://user-images.githubusercontent.com/49523956/193200501-df17d324-cc5d-4be9-9e1a-3eb6665ce15b.png">

- **Single-Asset Mode**
<img width="631" alt="image" src="https://user-images.githubusercontent.com/49523956/193200599-9685d829-17b6-4b3f-9e44-5e7dabf4c087.png">

## Describe the enhancement

When bots running on a new account, some settings are not the same as above, bots will raise an error if we don't login and configure manually. So, please support set `Position Mode` and `Asset Mode` automatically when bots start.

**Comment by xmatthias** [comment]
Please provide examples / log outputs from the errors the bot will raise if it's configured wrongly.

**Comment by liaogx** [comment]
When my binance account is `Hedge Mode`, and I open a new trade (live)

```python
2022-09-30 14:18:28,435 - freqtrade.freqtradebot - INFO - Short signal found: about create a new trade for DOT/USDT with stake_amount: 5.0 ...
2022-09-30 14:18:29,032 - uvicorn.access - INFO - 127.0.0.1:49297 - "POST /api/v1/forcebuy HTTP/1.1" 500
2022-09-30 14:18:29,033 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/Users/liao/PycharmProjects/freqtrade/.env/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/liao/PycharmProjects/freqtrade/.env/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/Users/liao/PycharmProjects/freqtrade/.env/lib/python3.8/site-packages/uvicorn/middleware/message_logger.py", line 86, in __call__
    raise exc from None
  File "/Users/liao/PycharmProjects/freqtrade/.env/lib/python3.8/site-packages/uvicorn/middleware/message_logger.py", line 82, in __call__
    await self.app(scope, inner_receive, inner_send)
  File "/Users/liao/PycharmProjects/freqtrade/.env/lib/python3.8/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/liao/PycharmProjects/freqtrade/.env/lib/python3.8/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/liao/PycharmProjects/freqtrade/.env/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/liao/PycharmProjects/freqtrade/.env/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/liao/PycharmProjects/freqtrade/.env/lib/python3.8/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/Users/liao/PycharmProjects/freqtrade/.env/lib/python3.8/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/Users/liao/PycharmProjects/freqtrade/.env/lib/python3.8/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/Users/liao/PycharmProjects/freqtrade/.env/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/Users/liao/PycharmProjects/freqtrade/.env/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/liao/PycharmProjects/freqtrade/.env/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/liao/PycharmProjects/freqtrade/.env/lib/python3.8/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/Users/liao/PycharmProjects/freqtrade/.env/lib/python3.8/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/Users/liao/PycharmProjects/freqtrade/.env/lib/python3.8/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/Users/liao/PycharmProjects/freqtrade/.env/lib/python3.8/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/Users/liao/PycharmProjects/freqtrade/.env/lib/python3.8/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/Users/liao/PycharmProjects/freqtrade/.env/lib/python3.8/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/Users/liao/PycharmProjects/freqtrade/.env/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/liao/PycharmProjects/freqtrade/.env/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/Users/liao/PycharmProjects/freqtrade/.env/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/Users/liao/PycharmProjects/freqtrade/freqtrade/rpc/api_server/api_v1.py", line 147, in force_entry
    trade = rpc._rpc_force_entry(payload.pair, payload.price, order_side=payload.side,
  File "/Users/liao/PycharmProjects/freqtrade/freqtrade/rpc/rpc.py", line 781, in _rpc_force_entry
    if self._freqtrade.execute_entry(pair, stake_amount, price,
  File "/Users/liao/PycharmProjects/freqtrade/freqtrade/freqtradebot.py", line 680, in execute_entry
    order = self.exchange.create_order(
  File "/Users/liao/PycharmProjects/freqtrade/freqtrade/exchange/exchange.py", line 1056, in create_order
    raise TemporaryError(
freqtrade.exceptions.TemporaryError: Could not place sell order due to ExchangeError. Message: binance {"code":-4061,"msg":"Order's position side does not match user's setting."}
2022-09-30 14:18:33,283 - uvicorn.access - INFO - 127.0.0.1:49300 - "GET /api/v1/ping HTTP/1.1" 200
```
You could reproduce this with any example or strategy

**Message: binance {"code":-4061,"msg":"Order's position side does not match user's setting."}**

**Comment by xmatthias** [comment]
Freqtrade should clearly not fail when creating a new order.

It'll however also not be changing account-wide settings, which will have influence on other trades and potentially open positions.

Freqtrade will check for this setting, and fail to start if it's wrong, alerting the user to change the settings manually. This way, they get the warnings from binance (open positions / open orders) - and will have to make an explicit, (hopefully informed) decision on the implications of this change.
