### ISSUE TITLE
forcelong in Lbank exchange

### ISSUE THREAD

**Issue by boyitnew** [freqtrade/freqtrade#7509]
## Describe your environment

  * Operating system: ubuntu
  * Python Version: 3.8.13
  * CCXT version: 1.92.52
  * Freqtrade Version: 2022.8
  
forcelong does not work in Lbank exchange (I have enabled it in config.json)
How can I solve it?

```
2022-10-01 07:17:56,294 - freqtrade.rpc.telegram - ERROR - Exception occurred within Telegram module
Traceback (most recent call last):
  File "/root/gateio/freqtrade/freqtrade/rpc/telegram.py", line 80, in wrapper
    return command_handler(self, *args, **kwargs)
  File "/root/gateio/freqtrade/freqtrade/rpc/telegram.py", line 1096, in _force_enter
    self._force_enter_action(pair, price, order_side)
  File "/root/gateio/freqtrade/freqtrade/rpc/telegram.py", line 1059, in _force_enter_action
    self._rpc._rpc_force_entry(pair, price, order_side=order_side)
  File "/root/gateio/freqtrade/freqtrade/rpc/rpc.py", line 781, in _rpc_force_entry
    if self._freqtrade.execute_entry(pair, stake_amount, price,
  File "/root/gateio/freqtrade/freqtrade/freqtradebot.py", line 775, in execute_entry
    self._notify_enter(trade, order_obj, order_type, sub_trade=pos_adjust)
  File "/root/gateio/freqtrade/freqtrade/freqtradebot.py", line 891, in _notify_enter
    current_rate = self.exchange.get_rate(
  File "/root/gateio/freqtrade/freqtrade/exchange/exchange.py", line 1573, in get_rate
    raise PricingError(f"{name}-Rate for {pair} was empty.")
```

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
I've never even heard of this exchange - letalone attempted to use it.
as such, you're almost certainly the first to even attempt to run freqtrade with this exchange.

We do have some (probably incomplete) [documentation](https://www.freqtrade.io/en/latest/developer/#implement-a-new-exchange-wip) on how to test an exchange for compatibility - but it will require some experience in development - and patience to test all the different things before we can say that it's safe to run freqtrade against an exchange.

---

At a glance, i'd say freqtrade can't get a rate for this pair - so maybe this exchange doesn't support the pricing configuration you use (try to use orderbook for pricing).

**Comment by boyitnew** [comment]
thanks
It was fixed by activating the orderbook
