### ISSUE TITLE
 https://api.binance.us/api/v3/exchangeInfo 403 Forbidden

### ISSUE THREAD

**Issue by OleksandrMyronchuk** [freqtrade/freqtrade#7527]
My environment

Operating system: Linux cd46e882f996 5.10.104-linuxkit https://github.com/freqtrade/freqtrade/pull/1 SMP Thu Mar 17 17:08:06 UTC 2022 x86_64 GNU/Linux
CCXT 1.91.29
Python Version: Python 3.10.5
Freqtrade Version: freqtrade 2022.7

The question:
When I try to run a strategy, I get the following error: "403 Forbidden"

The list of all logs looks like this:
```
ftuser@d96eb13c412e:/freqtrade$ freqtrade backtesting --datadir user_data/data/binanceus --config /freqtrade/user_data/GuruSkippyasurmuni_config.json --export trades -s GuruSkippyasurmuni
2022-10-03 13:19:03,569 - freqtrade - INFO - freqtrade 2022.9.1
2022-10-03 13:19:03,582 - freqtrade.configuration.load_config - INFO - Using config: /freqtrade/user_data/GuruSkippyasurmuni_config.json ...
2022-10-03 13:19:03,585 - freqtrade.loggers - INFO - Verbosity set to 0
2022-10-03 13:19:03,585 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 5 ...
2022-10-03 13:19:15,889 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2022-10-03 13:19:15,890 - freqtrade.configuration.configuration - INFO - Using data directory: user_data/data/binanceus ...
2022-10-03 13:19:15,890 - freqtrade.configuration.configuration - INFO - Parameter --export detected: trades ...
2022-10-03 13:19:15,890 - freqtrade.configuration.configuration - INFO - Parameter --cache=day detected ...
2022-10-03 13:19:15,890 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2022-10-03 13:19:15,903 - freqtrade.configuration.check_exchange - WARNING - Exchange "binanceus" is known to the the ccxt library, available for the bot, but not officially supported by the Freqtrade development team. It may work flawlessly (please report back) or have serious issues. Use it at your own discretion.
2022-10-03 13:19:15,903 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2022-10-03 13:19:15,903 - freqtrade.configuration.deprecated_settings - WARNING - DEPRECATED: The `forcebuy_enable` setting is deprecated and will be removed in the next versions of Freqtrade. Please use the `force_entry_enable` setting in your configuration instead.
2022-10-03 13:19:15,903 - freqtrade.configuration.config_validation - WARNING - DEPRECATED: Using 'buy' and 'sell' for unfilledtimeout is deprecated.Please migrate your unfilledtimeout settings to use 'entry' and 'exit' wording.
2022-10-03 13:19:15,903 - freqtrade.configuration.deprecated_settings - WARNING - DEPRECATED: The `unfilledtimeout.buy` setting is deprecated and will be removed in the next versions of Freqtrade. Please use the `unfilledtimeout.entry` setting in your configuration instead.
2022-10-03 13:19:15,903 - freqtrade.configuration.deprecated_settings - WARNING - DEPRECATED: The `unfilledtimeout.sell` setting is deprecated and will be removed in the next versions of Freqtrade. Please use the `unfilledtimeout.exit` setting in your configuration instead.
2022-10-03 13:19:15,903 - freqtrade.configuration.config_validation - WARNING - DEPRECATED: Using 'ask_strategy' and 'bid_strategy' is deprecated.Please migrate your settings to use 'entry_pricing' and 'exit_pricing'.
2022-10-03 13:19:15,904 - freqtrade.configuration.deprecated_settings - WARNING - DEPRECATED: The `bid_strategy.price_side` setting is deprecated and will be removed in the next versions of Freqtrade. Please use the `entry_pricing.price_side` setting in your configuration instead.
2022-10-03 13:19:15,904 - freqtrade.configuration.deprecated_settings - WARNING - DEPRECATED: The `bid_strategy.ask_last_balance` setting is deprecated and will be removed in the next versions of Freqtrade. Please use the `entry_pricing.price_last_balance` setting in your configuration instead.
2022-10-03 13:19:15,904 - freqtrade.configuration.deprecated_settings - WARNING - DEPRECATED: The `bid_strategy.use_order_book` setting is deprecated and will be removed in the next versions of Freqtrade. Please use the `entry_pricing.use_order_book` setting in your configuration instead.
2022-10-03 13:19:15,904 - freqtrade.configuration.deprecated_settings - WARNING - DEPRECATED: The `bid_strategy.order_book_top` setting is deprecated and will be removed in the next versions of Freqtrade. Please use the `entry_pricing.order_book_top` setting in your configuration instead.
2022-10-03 13:19:15,904 - freqtrade.configuration.deprecated_settings - WARNING - DEPRECATED: The `bid_strategy.check_depth_of_market` setting is deprecated and will be removed in the next versions of Freqtrade. Please use the `entry_pricing.check_depth_of_market` setting in your configuration instead.
2022-10-03 13:19:15,904 - freqtrade.configuration.deprecated_settings - WARNING - DEPRECATED: The `ask_strategy.price_side` setting is deprecated and will be removed in the next versions of Freqtrade. Please use the `exit_pricing.price_side` setting in your configuration instead.
2022-10-03 13:19:15,905 - freqtrade.configuration.deprecated_settings - WARNING - DEPRECATED: The `ask_strategy.use_order_book` setting is deprecated and will be removed in the next versions of Freqtrade. Please use the `exit_pricing.use_order_book` setting in your configuration instead.
2022-10-03 13:19:15,905 - freqtrade.configuration.deprecated_settings - WARNING - DEPRECATED: The `ask_strategy.order_book_min` setting is deprecated and will be removed in the next versions of Freqtrade. Please use the `exit_pricing.order_book_min` setting in your configuration instead.
2022-10-03 13:19:15,905 - freqtrade.configuration.deprecated_settings - WARNING - DEPRECATED: The `ask_strategy.order_book_max` setting is deprecated and will be removed in the next versions of Freqtrade. Please use the `exit_pricing.order_book_max` setting in your configuration instead.
2022-10-03 13:19:15,905 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2022-10-03 13:19:15,910 - freqtrade.commands.optimize_commands - INFO - Starting freqtrade in Backtesting mode
2022-10-03 13:19:15,911 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2022-10-03 13:19:15,912 - freqtrade.exchange.exchange - INFO - Using CCXT 1.95.2
2022-10-03 13:19:15,912 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2022-10-03 13:19:15,925 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 200}
2022-10-03 13:19:15,938 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance US"
2022-10-03 13:19:16,589 - freqtrade.exchange.exchange - ERROR - Unable to initialize markets.
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 620, in fetch
    response.raise_for_status()
  File "/home/ftuser/.local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.binance.us/api/v3/exchangeInfo

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/exchange.py", line 482, in _load_markets
    self._markets = self._api.load_markets()
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 1431, in load_markets
    markets = self.fetch_markets(params)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/binance.py", line 1459, in fetch_markets
    response = getattr(self, method)(query)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 500, in inner
    return entry(_self, **inner_kwargs)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/binance.py", line 5571, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2609, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 638, in fetch
    self.handle_http_status_code(http_status_code, http_status_text, url, method, http_response)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 1724, in handle_http_status_code
    raise ErrorClass(self.id + ' ' + method + ' ' + url + ' ' + codeAsString + ' ' + reason + ' ' + body)
ccxt.base.errors.ExchangeNotAvailable: binanceus GET https://api.binance.us/api/v3/exchangeInfo 403 Forbidden <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
The Amazon CloudFront distribution is configured to block access from your country.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: CPY0lIi1MpQ6dhZOZUgRrNzEXnIZNh9qUAkktIGJK0xhJvsmDT_fDw==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
2022-10-03 13:19:16,592 - freqtrade - ERROR - Could not load markets, therefore cannot start. Please investigate the above error for more details.
```

I checked the link https://api.binance.us/api/v3/exchangeInfo in the browser, this link return the error.
but the link https://api.binance.com/api/v3/exchangeInfo is working

That is, the error occurs because in my region freqtrade uses api.binance.us instead of api.binance.com. The question is how to replace this link?

**Comment by OleksandrMyronchuk** [comment]
Sorry, I already figured it out. 

I needed to make changes to the config.json file 

`..."exchange": { "name": "binanceus "... ON ..."exchange": { "name": "binance",...`

**Comment by xmatthias** [comment]
well yes - binanceus is for the US only - so it kindof makes sense for them to restrict access to US IP's.

Glad you could figure this out already👍
