### ISSUE TITLE
short only strategy

### ISSUE THREAD

**Issue by xarthurx** [freqtrade/freqtrade#7528]
## Describe your environment

  * Operating system: Windows 10
  * Python Version: 3.10
  * CCXT version: 1.93
  * Freqtrade Version: 2022.9
  
## Your question

I'm testing a "short-only" strategy where I have only `enter_short` and `exit_short` in the strategy definition,

```
    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        dataframe.loc[
                  <some condition>, 
                "enter_short",
                ] = 1

        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        dataframe.loc[
                  <some condition>, 
                'exit_short',
                ] = 1

        return dataframe
```
The backtesting shows everything is fine, but when running this strategy in trading mode, I got the error: 

```
2022-10-03 16:14:12,159 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair ATOM/USDT: enter_long/buy column not set.
2022-10-03 16:14:12,176 - freqtrade.commands.trade_commands - ERROR - 'enter_long'
2022-10-03 16:14:12,177 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "C:\Users\xarthur\mambaforge\lib\site-packages\pandas\core\indexes\base.py", line 3800, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'enter_long'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\xarthur\source\repo\freqtrade\freqtrade\commands\trade_commands.py", line 19, in start_trading
    worker.run()
  File "C:\Users\xarthur\source\repo\freqtrade\freqtrade\worker.py", line 75, in run
    state = self._worker(old_state=state)
  File "C:\Users\xarthur\source\repo\freqtrade\freqtrade\worker.py", line 115, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
  File "C:\Users\xarthur\source\repo\freqtrade\freqtrade\worker.py", line 140, in _throttle
    result = func(*args, **kwargs)
  File "C:\Users\xarthur\source\repo\freqtrade\freqtrade\worker.py", line 153, in _process_running
    self.freqtrade.process()
  File "C:\Users\xarthur\source\repo\freqtrade\freqtrade\freqtradebot.py", line 225, in process
    self.enter_positions()
  File "C:\Users\xarthur\source\repo\freqtrade\freqtrade\freqtradebot.py", line 465, in enter_positions
    trades_created += self.create_trade(pair)
  File "C:\Users\xarthur\source\repo\freqtrade\freqtrade\freqtradebot.py", line 495, in create_trade
    (signal, enter_tag) = self.strategy.get_entry_signal(
  File "C:\Users\xarthur\source\repo\freqtrade\freqtrade\strategy\interface.py", line 921, in get_entry_signal
    enter_long = latest[SignalType.ENTER_LONG.value] == 1
  File "C:\Users\xarthur\mambaforge\lib\site-packages\pandas\core\series.py", line 982, in __getitem__
    return self._get_value(key)
  File "C:\Users\xarthur\mambaforge\lib\site-packages\pandas\core\series.py", line 1092, in _get_value
    loc = self.index.get_loc(label)
  File "C:\Users\xarthur\mambaforge\lib\site-packages\pandas\core\indexes\base.py", line 3802, in get_loc
    raise KeyError(key) from err
KeyError: 'enter_long'
```

If I change the word `enter_short` to `enter_long` in the `populate_entry_trend` function, the strategy can run, but the signal will be `long`.

So how should I set a `short-only` strategy correctly? Or what does the error mean in this case?

**Comment by xmatthias** [comment]
`enter_long ` is a mandatory column at the moment.

You can however work around this by setting the column to 0 unconditionally (`dataframe['enter_long'] = 0`).

**Comment by xarthurx** [comment]
Oh, this is very good to know.
Thank you. I'm closing the issue.
