### ISSUE TITLE
Crash after update to 2022.9.1

### ISSUE THREAD

**Issue by avibrazil** [freqtrade/freqtrade#7537]
## Describe your environment

  * Operating system: Linux Fedora 35
  * Python Version: 3.10
  * CCXT version: 1.93.98 (as per requirements.txt)
  * Freqtrade Version: 2022.9.1

## Describe the problem:

Bot crashes in startup after migrating to 2022.9.1. Also tested with 2022.9 and got same crash. Going back to 2022.8 won't crash anymore.

  ```
$ freqtrade trade -c configs/blacklist-huobi.json -c configs/config.json -c configs/pairlist-volume-huobi-usdt.json -s ${my_strategy}
2022-10-05 11:09:32,582 - freqtrade - INFO - freqtrade 2022.9.1
2022-10-05 11:09:32,781 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/avibrazil/.local/lib/python3.10/site-packages/freqtrade/main.py", line 39, in main
    return_code = args['func'](args)
  File "/home/avibrazil/.local/lib/python3.10/site-packages/freqtrade/commands/trade_commands.py", line 13, in start_trading
    from freqtrade.worker import Worker
  File "/home/avibrazil/.local/lib/python3.10/site-packages/freqtrade/worker.py", line 17, in <module>
    from freqtrade.freqtradebot import FreqtradeBot
  File "/home/avibrazil/.local/lib/python3.10/site-packages/freqtrade/freqtradebot.py", line 32, in <module>
    from freqtrade.rpc.external_message_consumer import ExternalMessageConsumer
  File "/home/avibrazil/.local/lib/python3.10/site-packages/freqtrade/rpc/external_message_consumer.py", line 20, in <module>
    from freqtrade.rpc.api_server.ws_schemas import (WSAnalyzedDFMessage, WSAnalyzedDFRequest,
  File "/home/avibrazil/.local/lib/python3.10/site-packages/freqtrade/rpc/api_server/ws_schemas.py", line 37, in <module>
    class WSWhitelistRequest(WSRequestSchema):
  File "/usr/lib/python3.10/site-packages/pydantic/main.py", line 262, in __new__
    fields[ann_name] = inferred = ModelField.infer(
  File "/usr/lib/python3.10/site-packages/pydantic/fields.py", line 315, in infer
    return cls(
  File "/usr/lib/python3.10/site-packages/pydantic/fields.py", line 284, in __init__
    self.prepare()
  File "/usr/lib/python3.10/site-packages/pydantic/fields.py", line 350, in prepare
    self._set_default_and_type()
  File "/usr/lib/python3.10/site-packages/pydantic/fields.py", line 386, in _set_default_and_type
    raise errors_.ConfigError(f'unable to infer type for attribute "{self.name}"')
pydantic.errors.ConfigError: unable to infer type for attribute "data"
  ```

**Comment by xmatthias** [comment]
The error seems to come quite early in the process (there's basically 0 logs before this) - which suggests that it's an environment issue.

what's your pydantic version? (`pip show pydantic`)

**Comment by avibrazil** [comment]
```
$ pip show pydantic
Name: pydantic
Version: 1.7.4
Summary: Data validation and settings management using python 3.6 type hinting
Home-page: https://github.com/samuelcolvin/pydantic
Author: Samuel Colvin
Author-email: s@muelcolvin.com
License: MIT
Location: /usr/lib/python3.10/site-packages
Requires:
Required-by: fastapi

$ rpm -qa | grep pydantic
python3-pydantic-1.7.4-3.fc35.noarch
```

Per its install location, I got it as a package from OS.

In the original report, I forgot to mention that I also installed all requirements using version's `requirements.txt`:
```
pip install -U -r requirements.txt
```

**Comment by xmatthias** [comment]
Are other dependencies also from the system (not the envrionment?)

pydantic is not a dependency we reference directly but through fastAPI (They recommend to not reference it directly) - maybe you can run `pip install -U pydantic` in the venv to update it to a newer version?

**Comment by avibrazil** [comment]
Updating to latest pydantic and latest freqtrade (2022.9.1) it works.
FastAPI is 0.70 from the system and 0.85 from pip.
So FastAPI latest version is incompatible with old pydantic.
So this is FastAPI's dependency problem.

**Comment by xmatthias** [comment]
not necessarily - we do also use pydantic directly. 
I'll see to loosely pin pydantic here to ensure we're compatible.

**Comment by avibrazil** [comment]
Cool! Thanks!
