### ISSUE TITLE
FreqAI backtesting fails with timerange merging error

### ISSUE THREAD

**Issue by SergeySypalo** [freqtrade/freqtrade#7543]
## Describe your environment

  * Operating system: Win11
  * Python Version: 3.10.7
  * CCXT version: 1.95.14
  * Freqtrade Version: freqtrade 2022.10.dev-edb942f66
  

## Describe the problem:

FreqAI backtesting fails with timerange merging error.

### Steps to reproduce:

  1. freqtrade download-data --config config_examples/config_freqai.example.json --timerange 20220901-20220930
  2. freqtrade backtesting --strategy FreqaiExampleStrategy --strategy-path freqtrade/templates --config user_data/config.json --freqaimodel LightGBMRegressor --timerange 20220901-20220916
  
### Observed Results:

  * Got an error: ValueError: Tried to merge a faster timeframe to a slower timeframe.This would create new rows, and can throw off your regular indicators.
  * Merging should be done correctly/automatically

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
PS D:\repos\freqtrade> freqtrade backtesting --strategy FreqaiExampleStrategy --strategy-path freqtrade/templates --config user_data/config.json --freqaimodel LightGBMRegressor --timerange 20220901-20220916      
2022-10-06 19:59:04,235 - freqtrade - INFO - freqtrade 2022.10.dev-edb942f66
2022-10-06 19:59:04,247 - freqtrade.configuration.load_config - INFO - Using config: user_data/config.json ...
2022-10-06 19:59:04,248 - freqtrade.loggers - INFO - Verbosity set to 0
2022-10-06 19:59:04,249 - freqtrade.configuration.configuration - INFO - Using additional Strategy lookup path: freqtrade/templates
2022-10-06 19:59:04,249 - freqtrade.configuration.configuration - WARNING - `force_entry_enable` RPC message enabled.
2022-10-06 19:59:04,249 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 5 ...
2022-10-06 19:59:04,249 - freqtrade.configuration.configuration - INFO - Parameter --timerange detected: 20220901-20220916 ...
2022-10-06 19:59:04,250 - freqtrade.configuration.configuration - INFO - Using user-data directory: D:\repos\freqtrade\user_data ...
2022-10-06 19:59:04,251 - freqtrade.configuration.configuration - INFO - Using data directory: D:\repos\freqtrade\user_data\data\binance ...
2022-10-06 19:59:04,251 - freqtrade.configuration.configuration - INFO - Parameter --cache=day detected ...
2022-10-06 19:59:04,251 - freqtrade.configuration.configuration - INFO - Using freqaimodel class name: LightGBMRegressor
2022-10-06 19:59:04,252 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2022-10-06 19:59:04,264 - freqtrade.exchange.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2022-10-06 19:59:04,264 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2022-10-06 19:59:04,264 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2022-10-06 19:59:04,268 - freqtrade.commands.optimize_commands - INFO - Starting freqtrade in Backtesting mode
2022-10-06 19:59:04,268 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2022-10-06 19:59:04,269 - freqtrade.exchange.exchange - INFO - Using CCXT 1.95.12
2022-10-06 19:59:04,269 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'future'}, 'enableRateLimit': True}
2022-10-06 19:59:04,281 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'future'}, 'enableRateLimit': True, 'rateLimit': 200}
2022-10-06 19:59:04,292 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2022-10-06 19:59:05,440 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2022-10-06 19:59:05,464 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy FreqaiExampleStrategy from 'D:\repos\freqtrade\freqtrade\templates\FreqaiExampleStrategy.py'...
2022-10-06 19:59:05,465 - freqtrade.strategy.hyper - INFO - Found no parameter file.
2022-10-06 19:59:05,465 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 15m.
2022-10-06 19:59:05,466 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2022-10-06 19:59:05,466 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 1000.
2022-10-06 19:59:05,466 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'entry': 10, 'exit': 30, 'exit_timeout_count': 0, 'unit': 'minutes'}.
2022-10-06 19:59:05,466 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 0.1, '240': -1}
2022-10-06 19:59:05,466 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 15m
2022-10-06 19:59:05,467 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.05
2022-10-06 19:59:05,467 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2022-10-06 19:59:05,467 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2022-10-06 19:59:05,467 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2022-10-06 19:59:05,467 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2022-10-06 19:59:05,467 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: True
2022-10-06 19:59:05,468 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'entry': 'limit', 'exit': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False, 'stoploss_on_exchange_interval': 60}
2022-10-06 19:59:05,468 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'entry': 'GTC', 'exit': 'GTC'}
2022-10-06 19:59:05,468 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2022-10-06 19:59:05,468 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 1000
2022-10-06 19:59:05,469 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2022-10-06 19:59:05,469 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 40
2022-10-06 19:59:05,469 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'entry': 10, 'exit': 30, 'exit_timeout_count': 0, 'unit': 'minutes'}       
2022-10-06 19:59:05,469 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_exit_signal: True
2022-10-06 19:59:05,469 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_only: False
2022-10-06 19:59:05,469 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_entry_signal: False
2022-10-06 19:59:05,469 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_offset: 0.0
2022-10-06 19:59:05,470 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2022-10-06 19:59:05,470 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2022-10-06 19:59:05,470 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: False
2022-10-06 19:59:05,470 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1
2022-10-06 19:59:05,470 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2022-10-06 19:59:05,484 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from 'D:\repos\freqtrade\freqtrade\plugins\pairlist\StaticPairList.py'...
2022-10-06 19:59:05,488 - freqtrade.data.dataprovider - INFO - Increasing startup_candle_count for freqai to 1480
2022-10-06 19:59:05,489 - freqtrade.data.history.history_utils - INFO - Using indicator startup period: 1480 ...
2022-10-06 19:59:05,611 - freqtrade.optimize.backtesting - INFO - Loading data from 2022-08-16 14:00:00 up to 2022-09-16 00:00:00 (30 days).
2022-10-06 19:59:05,775 - freqtrade.optimize.backtesting - INFO - Dataload complete. Calculating indicators
2022-10-06 19:59:05,782 - freqtrade.optimize.backtesting - INFO - Running backtesting for Strategy FreqaiExampleStrategy
2022-10-06 19:59:06,922 - freqtrade.resolvers.iresolver - INFO - Using resolved freqaimodel LightGBMRegressor from 'D:\repos\freqtrade\freqtrade\freqai\prediction_models\LightGBMRegressor.py'...
2022-10-06 19:59:06,924 - freqtrade.freqai.freqai_interface - INFO - Backtesting module configured to save all models.
2022-10-06 19:59:06,925 - freqtrade.freqai.data_drawer - INFO - Found existing historic predictions at D:\repos\freqtrade\user_data\models\uniqe-id, but beware that statistics may be inaccurate if the bot has been offline for an extended period of time.
2022-10-06 19:59:06,925 - freqtrade.freqai.freqai_interface - INFO - Set existing queue from trained timestamps. Best approximation queue: deque(['MATIC/USDT', 'SOL/USDT', 'BNB/USDT', 'BTC/USDT', 'ETH/USDT'])
2022-10-06 19:59:06,926 - freqtrade.strategy.hyper - INFO - No params for buy found, using default values.
2022-10-06 19:59:06,926 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): std_dev_multiplier_buy = 1.25
2022-10-06 19:59:06,926 - freqtrade.strategy.hyper - INFO - No params for sell found, using default values.
2022-10-06 19:59:06,927 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): std_dev_multiplier_sell = 1.25
2022-10-06 19:59:06,927 - freqtrade.strategy.hyper - INFO - No params for protection found, using default values.
2022-10-06 19:59:06,928 - freqtrade.freqai.freqai_interface - INFO - Training 3 timeranges
2022-10-06 19:59:06,929 - freqtrade.data.dataprovider - INFO - Increasing startup_candle_count for freqai to 1480
2022-10-06 19:59:07,001 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "D:\repos\freqtrade\freqtrade\main.py", line 39, in main
    return_code = args['func'](args)
  File "D:\repos\freqtrade\freqtrade\commands\optimize_commands.py", line 58, in start_backtesting
    backtesting.start()
  File "D:\repos\freqtrade\freqtrade\optimize\backtesting.py", line 1332, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
  File "D:\repos\freqtrade\freqtrade\optimize\backtesting.py", line 1230, in backtest_one_strategy
    preprocessed = self.strategy.advise_all_indicators(data)
  File "D:\repos\freqtrade\freqtrade\strategy\interface.py", line 1205, in advise_all_indicators
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "D:\repos\freqtrade\freqtrade\strategy\interface.py", line 1205, in <dictcomp>
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "D:\repos\freqtrade\freqtrade\strategy\interface.py", line 1223, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "D:\repos\freqtrade\freqtrade\templates\FreqaiExampleStrategy.py", line 169, in populate_indicators
    dataframe = self.freqai.start(dataframe, metadata, self)
  File "D:\repos\freqtrade\freqtrade\freqai\freqai_interface.py", line 139, in start
    dataframe = self.dk.use_strategy_to_populate_indicators(
  File "D:\repos\freqtrade\freqtrade\freqai\data_kitchen.py", line 1154, in use_strategy_to_populate_indicators
    dataframe = strategy.populate_any_indicators(
  File "D:\repos\freqtrade\freqtrade\templates\FreqaiExampleStrategy.py", line 113, in populate_any_indicators
    df = merge_informative_pair(df, informative, self.config["timeframe"], tf, ffill=True)
  File "D:\repos\freqtrade\freqtrade\strategy\strategy_helper.py", line 53, in merge_informative_pair
    raise ValueError("Tried to merge a faster timeframe to a slower timeframe."
ValueError: Tried to merge a faster timeframe to a slower timeframe.This would create new rows, and can throw off your regular indicators.
  ```

**Comment by xmatthias** [comment]
Your configuration defines a timeframe of 15m - as such - your `include_timeframes` can only be 15m and higher.

@robcaulk you think it's necessary to  add an explicit check for this to fail earlier?

You're also downloading the data "exactly as needed" - starting 20220901 (and backtesting starts on the same date).
You will need more data prior to the backtesting date - how much will depend on the actual configuration settings used.

**Comment by robcaulk** [comment]
Yes, we can add the check and automatically remove any tfs < config tf. Then log a warning to the user.

**Comment by xmatthias** [comment]
i'm not entirely sure if we should remove them - or fail gracefully and let the make an informed decision.
in the end, the config is invalid - so the user should take an explicit choice to either remove this - or change the base timeframe, or use a different timeframe.

**Comment by SergeySypalo** [comment]
Matthias, thanks for pointing out, this info was already in documentation, but since I'm new to this tool just overlooked it.
Now backtesting it's running as expected. Just comparing with my experience with MetaTrader 4/5, there I don't need to pre-download data, it's done automatically. As we can get info from the run params, such as time range, timeframes and startup_candle_count we can do the calculations in frequi code to run download-data with proper params before running the backtest (just a feature improvement suggestion).

**Comment by xmatthias** [comment]
These automatics are intentionally not done, leaving the user in full control of the data they download. 

A normal usecase for downloading data is to pick a selected timerange (say 20200101-) - and download all data since then. you can then backtest just slices from this depending on your needs and the strategy.

You'll not repeat the data-download if you switch strategy or configuration - which taking assumptions would imply - and data-downloads are assumed to be done once for a longer, historic timeperiod - and then followed up by incremental updates to the data to get "fresh" data.

**Comment by SergeySypalo** [comment]
Gotcha, thanks for detailed explanation.

**Comment by robcaulk** [comment]
> Matthias, thanks for pointing out, this info was already in documentation, but since I'm new to this tool just overlooked it.
> Now backtesting it's running as expected. Just comparing with my experience with MetaTrader 4/5, there I don't need to pre-download data, it's done automatically. As we can get info from the run params, such as time range, timeframes and startup_candle_count we can do the calculations in frequi code to run download-data with proper params before running the backtest (just a feature improvement suggestion).

FreqAI downloads your data automatically in dry/live run. 

In backtesting, it is trivial to automate considering we have machinery already for live/dry. But we won’t push it to develop for the reasons Matthias points out.

**Comment by mathlabelle** [comment]
i have the same error but my strategy is on the 15m timeframe and in my config i have 15min as the minimum. keep looking but can't figure out why it is telling me the config file contain 5m when it doesn't

"freqai": {
        "enabled": true,
        "purge_old_models": true,
        "train_period_days": 15,
        "backtest_period_days": 7,
        "identifier": "uniqe-id",
        "feature_parameters": {
            "include_timeframes": ["15m","1h","4h"],
            "include_corr_pairlist": [
                "BTC/USDT",
                "ETH/USDT"
                
            ],
            "label_period_candles": 20,
            "include_shifted_candles": 2,
            "DI_threshold": 0.9,
            "weight_factor": 0.9,
            "principal_component_analysis": false,
            "use_SVM_to_remove_outliers": true,
            "indicator_periods_candles": [10, 20]
        },
        "data_split_parameters": {
            "test_size": 0.33,
            "random_state": 1
        },
        "model_training_parameters": {
            "n_estimators": 1000
        }
    },

**Comment by mathlabelle** [comment]
freqtrade$ freqtrade backtesting --strategy bob  --timerange 20220101-20220401   -c user_data/config/freqai.json  --freqaimodel CatboostClassifier
2023-01-22 18:55:49,614 - freqtrade - INFO - freqtrade 2022.12
2023-01-22 18:55:49,615 - freqtrade.configuration.load_config - INFO - Using config: user_data/config/freqai.json ...
2023-01-22 18:55:49,615 - freqtrade.loggers - INFO - Verbosity set to 0
2023-01-22 18:55:49,615 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 10 ...
2023-01-22 18:55:49,616 - freqtrade.configuration.configuration - INFO - Parameter --timerange detected: 20220101-20220401 ...
2023-01-22 18:55:49,616 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/mathieu/mathieu/freqtrade/user_data ...
2023-01-22 18:55:49,616 - freqtrade.configuration.configuration - INFO - Using data directory: /home/mathieu/mathieu/freqtrade/user_data/data/binance ...
2023-01-22 18:55:49,616 - freqtrade.configuration.configuration - INFO - Parameter --cache=day detected ...
2023-01-22 18:55:49,616 - freqtrade.configuration.configuration - INFO - Filter trades by timerange: 20220101-20220401
2023-01-22 18:55:49,616 - freqtrade.configuration.configuration - INFO - Using freqaimodel class name: CatboostClassifier
2023-01-22 18:55:49,616 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2023-01-22 18:55:49,624 - freqtrade.exchange.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2023-01-22 18:55:49,624 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2023-01-22 18:55:49,624 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2023-01-22 18:55:49,627 - freqtrade.commands.optimize_commands - INFO - Starting freqtrade in Backtesting mode
2023-01-22 18:55:49,627 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2023-01-22 18:55:49,627 - freqtrade.exchange.exchange - INFO - Using CCXT 2.4.60
2023-01-22 18:55:49,627 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'future'}}
2023-01-22 18:55:49,635 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'future'}}
2023-01-22 18:55:49,642 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2023-01-22 18:55:50,468 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2023-01-22 18:55:50,476 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy bob from '/home/mathieu/mathieu/freqtrade/user_data/strategies/freqai2.py'...
2023-01-22 18:55:50,476 - freqtrade.strategy.hyper - INFO - Found no parameter file.
2023-01-22 18:55:50,476 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2023-01-22 18:55:50,476 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: unlimited.
2023-01-22 18:55:50,476 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}.
2023-01-22 18:55:50,476 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 0.09}
2023-01-22 18:55:50,477 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 15m
2023-01-22 18:55:50,477 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.319
2023-01-22 18:55:50,477 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: True
2023-01-22 18:55:50,477 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive: 0.01
2023-01-22 18:55:50,477 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.012
2023-01-22 18:55:50,477 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: True
2023-01-22 18:55:50,477 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2023-01-22 18:55:50,477 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: True
2023-01-22 18:55:50,477 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'entry': 'limit', 'exit': 'limit', 'stoploss': 'market', 'stoploss_on_exchange': True}
2023-01-22 18:55:50,477 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'entry': 'GTC', 'exit': 'GTC'}
2023-01-22 18:55:50,477 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2023-01-22 18:55:50,477 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: unlimited
2023-01-22 18:55:50,477 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2023-01-22 18:55:50,477 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 20
2023-01-22 18:55:50,477 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}
2023-01-22 18:55:50,478 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_exit_signal: True
2023-01-22 18:55:50,478 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_only: False
2023-01-22 18:55:50,478 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_entry_signal: False
2023-01-22 18:55:50,478 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_offset: 0.0
2023-01-22 18:55:50,478 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2023-01-22 18:55:50,478 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2023-01-22 18:55:50,478 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: False
2023-01-22 18:55:50,478 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1
2023-01-22 18:55:50,478 - freqtrade - ERROR - Main timeframe of 15m must be smaller or equal to FreqAI `include_timeframes`.Offending include-timeframes: 5m
(.env) mathieu@MSI:~/mathieu/freqtrade$ freqtrade backtesting --strategy bob  --timerange 20220101-20220401   -c user_data/config/freqai.json  --freqaimodel CatboostClassifier
2023-01-22 19:04:47,241 - freqtrade - INFO - freqtrade 2022.12
2023-01-22 19:04:47,242 - freqtrade.configuration.load_config - INFO - Using config: user_data/config/freqai.json ...
2023-01-22 19:04:47,242 - freqtrade.loggers - INFO - Verbosity set to 0
2023-01-22 19:04:47,243 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 10 ...
2023-01-22 19:04:47,243 - freqtrade.configuration.configuration - INFO - Parameter --timerange detected: 20220101-20220401 ...
2023-01-22 19:04:47,243 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/mathieu/mathieu/freqtrade/user_data ...
2023-01-22 19:04:47,243 - freqtrade.configuration.configuration - INFO - Using data directory: /home/mathieu/mathieu/freqtrade/user_data/data/binance ...
2023-01-22 19:04:47,243 - freqtrade.configuration.configuration - INFO - Parameter --cache=day detected ...
2023-01-22 19:04:47,243 - freqtrade.configuration.configuration - INFO - Filter trades by timerange: 20220101-20220401
2023-01-22 19:04:47,243 - freqtrade.configuration.configuration - INFO - Using freqaimodel class name: CatboostClassifier
2023-01-22 19:04:47,243 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2023-01-22 19:04:47,251 - freqtrade.exchange.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2023-01-22 19:04:47,251 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2023-01-22 19:04:47,251 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2023-01-22 19:04:47,254 - freqtrade.commands.optimize_commands - INFO - Starting freqtrade in Backtesting mode
2023-01-22 19:04:47,254 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2023-01-22 19:04:47,255 - freqtrade.exchange.exchange - INFO - Using CCXT 2.4.60
2023-01-22 19:04:47,255 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'future'}}
2023-01-22 19:04:47,262 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'future'}}
2023-01-22 19:04:47,269 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2023-01-22 19:04:47,940 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2023-01-22 19:04:47,948 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy bob from '/home/mathieu/mathieu/freqtrade/user_data/strategies/freqai2.py'...
2023-01-22 19:04:47,948 - freqtrade.strategy.hyper - INFO - Found no parameter file.
2023-01-22 19:04:47,948 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2023-01-22 19:04:47,948 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: unlimited.
2023-01-22 19:04:47,948 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}.
2023-01-22 19:04:47,948 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 0.09}
2023-01-22 19:04:47,948 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 15m
2023-01-22 19:04:47,948 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.319
2023-01-22 19:04:47,949 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: True
2023-01-22 19:04:47,949 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive: 0.01
2023-01-22 19:04:47,949 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.012
2023-01-22 19:04:47,949 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: True
2023-01-22 19:04:47,949 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2023-01-22 19:04:47,949 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: True
2023-01-22 19:04:47,949 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'entry': 'limit', 'exit': 'limit', 'stoploss': 'market', 'stoploss_on_exchange': True}
2023-01-22 19:04:47,949 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'entry': 'GTC', 'exit': 'GTC'}
2023-01-22 19:04:47,949 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2023-01-22 19:04:47,949 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: unlimited
2023-01-22 19:04:47,949 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2023-01-22 19:04:47,949 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 20
2023-01-22 19:04:47,949 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}
2023-01-22 19:04:47,949 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_exit_signal: True
2023-01-22 19:04:47,949 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_only: False
2023-01-22 19:04:47,949 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_entry_signal: False
2023-01-22 19:04:47,949 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_offset: 0.0
2023-01-22 19:04:47,949 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2023-01-22 19:04:47,949 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2023-01-22 19:04:47,949 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: False
2023-01-22 19:04:47,949 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1
2023-01-22 19:04:47,950 - freqtrade - ERROR - Main timeframe of 15m must be smaller or equal to FreqAI `include_timeframes`.Offending include-timeframes: 5m

**Comment by robcaulk** [comment]
Hello, please ensure the quick start command works for you:

https://www.freqtrade.io/en/stable/freqai/#quick-start

If it works, please copy the template config to a new folder, using a new name, and then modifying 5m to be 15m in your strategy and config.
