### ISSUE TITLE
FreqAI GPU usage for model re-training

### ISSUE THREAD

**Issue by SergeySypalo** [freqtrade/freqtrade#7548]
## Describe your environment

  * Operating system: Win11
  * Python Version: 3.10.7
  * CCXT version: 1.95.19
  * Freqtrade Version: 2022.10.dev-d42fb1560
  
## Your question

Is it supposed to be so, that running FreqAI will burn all my 16 threads, but don't use GPU?
As per documentation, model should re-train on GPU (GTX 1080 in my case), not CPU, or am I missing something?

**Comment by xmatthias** [comment]
It will depend on the model you're using (LightGBM does not use GPU iirc) - and settings (Catboost, you need to set the "task_type" to GPU.

This is somewhat mentioned in the [parameters table](https://www.freqtrade.io/en/stable/freqai-parameter-table/) - but is really pointing to the respective docs of the model-libraries used to know the proper model-parameters that are possible and have to be set.

**Comment by SergeySypalo** [comment]
Thanks again Matthias, got it to work, at least to start, but it seems catboost 1.1 doesn't Python 3.10.7.
Backtesting not working at all, trading in dry run stops after some time.
Here are some outputs:
**CatboostClassifier**
```
997:    learn: 0.0272458        test: 0.1968898 best: 0.1499183 (0)     total: 27.5s    remaining: 55.1ms
998:    learn: 0.0272312        test: 0.1969269 best: 0.1499183 (0)     total: 27.5s    remaining: 27.6ms
999:    learn: 0.0272311        test: 0.1969262 best: 0.1499183 (0)     total: 27.6s    remaining: 0us
bestTest = 0.149918263
bestIteration = 0
Shrink model to first 1 iterations.
2022-10-07 21:21:47,961 - freqtrade.freqai.base_models.BaseRegressionModel - INFO - -------------------- Done training BTC/USDT (28.83 secs) --------------------
2022-10-07 21:21:47,961 - freqtrade.freqai.freqai_interface - INFO - Saving backtest model to disk.
2022-10-07 21:21:48,294 - freqtrade.freqai.data_kitchen - INFO - SVM tossed 65 predictions.
2022-10-07 21:21:48,343 - freqtrade.freqai.data_kitchen - INFO - DI tossed 592 predictions for being too far from training data.
C:\Users\Sergey\AppData\Local\Programs\Python\Python310\lib\site-packages\catboost\core.py:1419: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  self._init_pool(data, label, cat_features, text_features, embedding_features, embedding_features_data, pairs, weight,
2022-10-07 21:21:48,605 - freqtrade.freqai.freqai_interface - INFO - Training BTC/USDT, 1/5 pairs from 2022-08-09 00:00:00 to 2022-09-08 00:00:00, 2/5 trains
2022-10-07 21:21:48,606 - freqtrade.freqai.data_kitchen - INFO - Could not find backtesting prediction file at D:\repos\freqtrade\user_data\models\futures\backtesting_predictions\cb_btc_1662595200_prediction.h5
2022-10-07 21:21:48,606 - freqtrade.freqai.freqai_interface - INFO - Could not find model at D:\repos\freqtrade\user_data\models\futures\sub-train-BTC_1662595200\cb_btc_1662595200  
2022-10-07 21:21:48,607 - freqtrade.freqai.base_models.BaseRegressionModel - INFO - -------------------- Starting training BTC/USDT --------------------
2022-10-07 21:21:48,677 - freqtrade.freqai.data_kitchen - INFO - dropped 0 training points due to NaNs in populated dataset 2880.
2022-10-07 21:21:48,677 - freqtrade.freqai.base_models.BaseRegressionModel - INFO - -------------------- Training on data from 2022-08-09 to 2022-09-07 --------------------
2022-10-07 21:21:48,708 - freqtrade.freqai.data_kitchen - INFO - SVM tossed 119 train points from 1929 total points.
2022-10-07 21:21:48,708 - freqtrade.freqai.data_kitchen - INFO - SVM tossed 160 test points from 951 total points.
2022-10-07 21:21:48,833 - freqtrade.freqai.base_models.BaseRegressionModel - INFO - Training model on 380 features
2022-10-07 21:21:48,833 - freqtrade.freqai.base_models.BaseRegressionModel - INFO - Training model on 1810 data points
C:\Users\Sergey\AppData\Local\Programs\Python\Python310\lib\site-packages\catboost\core.py:1419: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  self._init_pool(data, label, cat_features, text_features, embedding_features, embedding_features_data, pairs, weight,
Learning rate set to 0.072916
2022-10-07 21:21:49,204 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "D:\repos\freqtrade\freqtrade\main.py", line 39, in main
    return_code = args['func'](args)
  File "D:\repos\freqtrade\freqtrade\commands\optimize_commands.py", line 58, in start_backtesting
    backtesting.start()
  File "D:\repos\freqtrade\freqtrade\optimize\backtesting.py", line 1332, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
  File "D:\repos\freqtrade\freqtrade\optimize\backtesting.py", line 1230, in backtest_one_strategy
    preprocessed = self.strategy.advise_all_indicators(data)
  File "D:\repos\freqtrade\freqtrade\strategy\interface.py", line 1205, in advise_all_indicators
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "D:\repos\freqtrade\freqtrade\strategy\interface.py", line 1205, in <dictcomp>
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "D:\repos\freqtrade\freqtrade\strategy\interface.py", line 1223, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "D:\repos\freqtrade\user_data\strategies\MyFutures.py", line 174, in populate_indicators
    dataframe = self.freqai.start(dataframe, metadata, self)
  File "D:\repos\freqtrade\freqtrade\freqai\freqai_interface.py", line 142, in start
    dk = self.start_backtesting(dataframe, metadata, self.dk)
  File "D:\repos\freqtrade\freqtrade\freqai\freqai_interface.py", line 287, in start_backtesting
    self.model = self.train(dataframe_train, pair, dk)
  File "D:\repos\freqtrade\freqtrade\freqai\base_models\BaseRegressionModel.py", line 66, in train
    model = self.fit(data_dictionary, dk)
  File "D:\repos\freqtrade\freqtrade\freqai\prediction_models\CatboostRegressor.py", line 48, in fit
    model.fit(X=train_data, eval_set=test_data, init_model=init_model)
  File "C:\Users\Sergey\AppData\Local\Programs\Python\Python310\lib\site-packages\catboost\core.py", line 5730, in fit
    return self._fit(X, y, cat_features, text_features, embedding_features, None, sample_weight, None, None, None, None, baseline,
  File "C:\Users\Sergey\AppData\Local\Programs\Python\Python310\lib\site-packages\catboost\core.py", line 2355, in _fit
    self._train(
  File "C:\Users\Sergey\AppData\Local\Programs\Python\Python310\lib\site-packages\catboost\core.py", line 1759, in _train
    self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
  File "_catboost.pyx", line 4622, in _catboost._CatBoost._train
  File "_catboost.pyx", line 4671, in _catboost._CatBoost._train
_catboost.CatBoostError: C:/Program Files (x86)/Go Agent/pipelines/BuildMaster/catboost.git/catboost/cuda/train_lib/train.cpp:353: Training continuation for GPU is not yet supported
```

**CatboostRegressor**
```
(class NCudaLib::TOutOfMemoryError) C:/Program Files (x86)/Go Agent/pipelines/BuildMaster/catboost.git/catboost/cuda/cuda_lib/memory_pool/stack_like_memory_pool.h:303: Error: Out of memory. Requested 20723.96973 MB; Free 6799.965625 MB
```

**Comment by aemr3** [comment]
Looks like you have this error:
```
train.cpp:353: Training continuation for GPU is not yet supported
```

Try setting continual_learning to false, it should fix your problem. 
Training continuation for GPU is only supported in XGBoost I guess.

**Comment by SergeySypalo** [comment]
Yes, you are right, this error I've got.
The idea was to use GPU for faster training and as per docs it's supported:
https://catboost.ai/en/docs/features/training-on-gpu
But it doesn't work.
I switched temporarily to CPU as Catboost is a newest model from the 3 models available.
Guess FreqAI docs need to be updated with more details on which model/python GPU is really supported for backtesting and trading.

**Comment by aemr3** [comment]
> Yes, you are right, this error I've got.
> The idea was to use GPU for faster training and as per docs it's supported:
> https://catboost.ai/en/docs/features/training-on-gpu
> But it doesn't work.
> I switched temporarily to CPU as Catboost is a newest model from the 3 models available.
> Guess FreqAI docs need to be updated with more details on which model/python GPU is really supported for backtesting and trading.

GPU is supported but not with continual_learning. This is not something related with FreqAI. Catboost doesn't support it with GPU. Set continual_learning to false and you can train with your GPU.

**Comment by SergeySypalo** [comment]
Thanks, aemr3, that is what I was looking for, now FreqAI running on GPU.
But I have a question, from the docs continual_learning is transferring previously learned information to a new model, but I set "purge_old_models": true
Does it mean, that after purging an old model training started from scratch? (Which doesn't make sense to me).
Or continual_learning is about to able to transfer knowledge when changing FreqAI "identifier" parameter and not about running the bot in trade mode with constant re-training?
Also, shall I change the identifier when changing the model (say from CatboostRegressor to LightGBMRegressor)?
Btw, , LightGBMRegressor supports GPU - https://lightgbm.readthedocs.io/en/v3.3.2/GPU-Tutorial.html, but not in FreqAI due to error:
```
[LightGBM] [Fatal] Unknown task type gpu
2022-10-08 06:56:24,349 - freqtrade.freqai.freqai_interface - WARNING - Training ETH/USDT raised exception LightGBMError. Message: Unknown task type gpu, skipping.
```

**Comment by aemr3** [comment]
Please read the docs for more information. 

Model parameters are not related with FreqAI. Every model type has different parameters. task_type is only for Catboost. For LightGBM use device = "gpu".

**Comment by SergeySypalo** [comment]
Re-read docs today once again, it's still not clear about knowledge transfer between model re-trainings.
Read LightGBM docs as well, updated config to have device = "gpu" for this model, but it didn't work
So I switched back to CatBoostRegressor, enabled continue_learning = true and switched to CPU. As it seems without this parameter, a NEW model is trained over and over, just on a sliding window.
In theory if I re-run backtesting on the same timerange I should get better and better results, but in reality backtesting failing with error:
`FileNotFoundError: [Errno 2] No such file or directory: 'D:\\repos\\freqtrade\\user_data\\models\\futures\\sub-train-ETH_1660953600\\cb_eth_1660953600_metadata.json' `
Guess if some sub-train data doesn't exist it should regenerated/recalculated.

**Comment by th0rntwig** [comment]
Re continual learning model transfer, the current trained model is kept in RAM as it's used to inference on until a new model is trained or it has expired (you set `expiration_hours`). `purge_old_models` removes models that were saved to disk so it doesn't affect the current model.

**Comment by SergeySypalo** [comment]
th0rntwig, thanks for commenting.
Yeah I know that purge_old_models mainly for disk space savings, but the question I asked about knowledge transfer. It's clear to me that trained model is in RAM and used to predict actions/price.
But when new learning iteration circle starts, from my understanding it just shifts the window and trains a new model from scratch by default.
Once this is done, new model is loaded into memory and become active/main model for predictions old model deleted from disk. But the knowledge/weights are not transferred from the older model.
In order for this ro be do I have to switch to CPU and set continue_learning = true
This is for what I want to get a confirmation or correction from developers.

**Comment by th0rntwig** [comment]
If you have enabled `continual learning` your current model is used as input to the next model. CatBoost only supports this for CPU which is why you need to use CPU.
