### ISSUE TITLE
test-pairlist fails with AgeFilter

### ISSUE THREAD

**Issue by grainz** [freqtrade/freqtrade#7552]
## Describe your environment

  * Operating system: Linux varian 5.10.0-18-amd64 # 1 SMP Debian 5.10.140-1 (2022-09-02) x86_64 GNU/Linux
  * Python Version: Python 3.9.2
  * CCXT version: ccxt==1.95.2
  * Freqtrade Version: freqtrade 2022.10.dev-e337d4b78

## Describe the problem:

Unable to use test-pairlist when using AgeFilter

### Steps to reproduce:

  1. Run 'freqtrade test-pairlist' with a config that uses AgeFilter
  
### Observed Results:

None, see logs

### Relevant code exceptions or logs

2022-10-08 08:18:58,317 - freqtrade - INFO - freqtrade 2022.10.dev-e337d4b78
2022-10-08 08:18:58,318 - freqtrade.configuration.load_config - INFO - Using config: binanceus-pairlist.json ...
2022-10-08 08:18:58,322 - freqtrade.loggers - INFO - Verbosity set to 0
2022-10-08 08:18:58,322 - freqtrade.configuration.configuration - WARNING - `force_entry_enable` RPC message enabled.
2022-10-08 08:18:58,325 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/grainz/build/freqtrade/user_data ...
2022-10-08 08:18:58,326 - freqtrade.configuration.configuration - INFO - Using data directory: /home/grainz/build/freqtrade/user_data/data/binanceus ...
2022-10-08 08:18:58,327 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2022-10-08 08:18:58,337 - freqtrade.exchange.check_exchange - INFO - Exchange "binanceus" is officially supported by the Freqtrade development team.
2022-10-08 08:18:58,337 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2022-10-08 08:18:58,337 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2022-10-08 08:18:58,341 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2022-10-08 08:18:58,341 - freqtrade.exchange.exchange - INFO - Using CCXT 1.95.2
2022-10-08 08:18:58,342 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2022-10-08 08:18:58,352 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 200}
2022-10-08 08:18:58,362 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance US"
2022-10-08 08:18:58,363 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2022-10-08 08:18:58,365 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist VolumePairList from '/home/grainz/build/freqtrade/freqtrade/plugins/pairlist/VolumePairList.py'...
2022-10-08 08:18:58,367 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist AgeFilter from '/home/grainz/build/freqtrade/freqtrade/plugins/pairlist/AgeFilter.py'...
2022-10-08 08:19:00,770 - freqtrade.exchange.exchange - INFO - Markets were not loaded. Loading them now..
2022-10-08 08:19:00,953 - VolumePairList - INFO - Pair USDT/USD in your blacklist. Removing it from whitelist...
2022-10-08 08:19:00,953 - VolumePairList - INFO - Pair BNB/USD in your blacklist. Removing it from whitelist...
2022-10-08 08:19:00,953 - VolumePairList - INFO - Pair BUSD/USD in your blacklist. Removing it from whitelist...
2022-10-08 08:19:00,953 - VolumePairList - INFO - Pair VTHO/USD in your blacklist. Removing it from whitelist...
2022-10-08 08:19:00,953 - VolumePairList - INFO - Pair USDC/USD in your blacklist. Removing it from whitelist...
2022-10-08 08:19:00,953 - VolumePairList - INFO - Pair DAI/USD in your blacklist. Removing it from whitelist...
2022-10-08 08:19:00,953 - VolumePairList - INFO - Pair PAXG/USD in your blacklist. Removing it from whitelist...
2022-10-08 08:19:00,957 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/grainz/build/freqtrade/freqtrade/main.py", line 39, in main
    return_code = args['func'](args)
  File "/home/grainz/build/freqtrade/freqtrade/commands/pairlist_commands.py", line 30, in start_test_pairlist
    pairlists.refresh_pairlist()
  File "/home/grainz/build/freqtrade/freqtrade/plugins/pairlistmanager.py", line 95, in refresh_pairlist
    pairlist = pairlist_handler.filter_pairlist(pairlist, tickers)
  File "/home/grainz/build/freqtrade/freqtrade/plugins/pairlist/AgeFilter.py", line 90, in filter_pairlist
    candles = self._exchange.refresh_latest_ohlcv(needed_pairs, since_ms=since_ms, cache=False)
  File "/home/grainz/build/freqtrade/freqtrade/exchange/exchange.py", line 1957, in refresh_latest_ohlcv
    input_coroutines, cached_pairs = self._build_ohlcv_dl_jobs(pair_list, since_ms, cache)
  File "/home/grainz/build/freqtrade/freqtrade/exchange/exchange.py", line 1906, in _build_ohlcv_dl_jobs
    self._build_coroutine(pair, timeframe, candle_type, since_ms, cache))
  File "/home/grainz/build/freqtrade/freqtrade/exchange/exchange.py", line 1855, in _build_coroutine
    not_all_data = self.required_candle_call_count > 1
AttributeError: 'Binance' object has no attribute 'required_candle_call_count'

**Comment by xmatthias** [comment]
Thanks for reporting - please update to the latest develop, it'll be fixed there.
