### ISSUE TITLE
FreqAI and edge positioning

### ISSUE THREAD

**Issue by SergeySypalo** [freqtrade/freqtrade#7578]
## Describe your environment

  * Operating system: Win11
  * Python Version: 3.10.8
  * CCXT version: 1.95.43
  * Freqtrade Version: freqtrade 2022.10.dev-a6f6a1739
  
## Your question

Is it possible to use FreqAI with Edge Positioning?
I'm getting error: `AttributeError: 'MyFutures' object has no attribute 'freqai'`

Basically I want AI to manage/learn when to enter/exist a trade, and in meanwhile use edge positioning for better stop loss values optimization.

**Comment by xmatthias** [comment]
Please provide a full stacktrace, not just one line of the exception. That'll tell us where the error originated from (often also which command you were using).

**Comment by SergeySypalo** [comment]
freqtrade trade --freqaimodel CatboostRegressor --strategy MyFutures
```
...
2022-10-12 21:05:59,881 - freqtrade.exchange.exchange - INFO - Downloaded data for AAVE/USDT with length 4.
2022-10-12 21:05:59,899 - freqtrade.data.history.history_utils - INFO - Using indicator startup period: 30 ...
2022-10-12 21:06:02,414 - freqtrade.commands.trade_commands - ERROR - 'MyFutures' object has no attribute 'freqai'
2022-10-12 21:06:02,415 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "D:\repos\freqtrade\freqtrade\commands\trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "D:\repos\freqtrade\freqtrade\worker.py", line 36, in __init__
    self._init(False)
  File "D:\repos\freqtrade\freqtrade\worker.py", line 53, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "D:\repos\freqtrade\freqtrade\freqtradebot.py", line 103, in __init__
    self.active_pair_whitelist = self._refresh_active_whitelist()
  File "D:\repos\freqtrade\freqtrade\freqtradebot.py", line 273, in _refresh_active_whitelist
    self.edge.calculate(_whitelist)
  File "D:\repos\freqtrade\freqtrade\edge\edge_positioning.py", line 156, in calculate
    preprocessed = self.strategy.advise_all_indicators(data)
  File "D:\repos\freqtrade\freqtrade\strategy\interface.py", line 1205, in advise_all_indicators
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "D:\repos\freqtrade\freqtrade\strategy\interface.py", line 1205, in <dictcomp>
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "D:\repos\freqtrade\freqtrade\strategy\interface.py", line 1223, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "D:\repos\freqtrade\user_data\strategies\MyFutures.py", line 274, in populate_indicators
    dataframe = self.freqai.start(dataframe, metadata, self)
AttributeError: 'MyFutures' object has no attribute 'freqai'
```

**Comment by xmatthias** [comment]
seems like edge is using the strategy before it's actually initialized...

while it would probably be fixable, it's not something we're going to look at for now.
edge is currently in maintenance mode only (we keep existing functionality alive) - but it will currently not receive new features until either someone stepped forward to take up ownership of that module - or we'll decide to remove edge from freqtrade.

This also includes freqAI support - i'll therefore close this as "not planned" - as we currently have no plans to support this combination.
