### ISSUE TITLE
minimal_roi default values are missing

### ISSUE THREAD

**Issue by SergeySypalo** [freqtrade/freqtrade#7583]
## Describe your environment

  * Operating system: Win11
  * Python Version: 3.10.8
  * CCXT version: 2.0.3
  * Freqtrade Version: freqtrade 2022.10.dev-e3ca74070
  
## Describe the problem:

Quote from documentation:
If it is not set in either Strategy or Configuration, a default of 1000% {"0": 10} is used, and minimal ROI is disabled unless your trade generates 1000% profit.

### Steps to reproduce:

But when I commented minimal_roi section in the strategy
  
### Observed Results:

I got an error

### Relevant code exceptions or logs

```
PS D:\repos\freqtrade> freqtrade trade --freqaimodel CatboostRegressor --strategy MyFutures                                                                                    2022-10-13 14:18:25,596 - freqtrade - INFO - freqtrade 2022.10.dev-e3ca74070
2022-10-13 14:18:26,395 - freqtrade.worker - INFO - Starting worker 2022.10.dev-e3ca74070
2022-10-13 14:18:26,395 - freqtrade.configuration.load_config - INFO - Using config: user_data\config.json ...
2022-10-13 14:18:26,407 - freqtrade.loggers - INFO - Verbosity set to 0
2022-10-13 14:18:26,407 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
2022-10-13 14:18:26,407 - freqtrade.configuration.configuration - WARNING - `force_entry_enable` RPC message enabled.
2022-10-13 14:18:26,407 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2022-10-13 14:18:26,407 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:///tradesv3.dryrun.sqlite"
2022-10-13 14:18:26,407 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 2 ...
2022-10-13 14:18:26,408 - freqtrade.configuration.configuration - INFO - Using user-data directory: D:\repos\freqtrade\user_data ...
2022-10-13 14:18:26,409 - freqtrade.configuration.configuration - INFO - Using data directory: D:\repos\freqtrade\user_data\data\binance ...
2022-10-13 14:18:26,409 - freqtrade.configuration.configuration - INFO - Using freqaimodel class name: CatboostRegressor
2022-10-13 14:18:26,416 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2022-10-13 14:18:26,428 - freqtrade.exchange.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2022-10-13 14:18:26,428 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2022-10-13 14:18:26,739 - freqtrade.resolvers.iresolver - WARNING - Could not import D:\repos\freqtrade\user_data\strategies\GodStra.py due to 'No module named 'ta''
2022-10-13 14:18:26,766 - freqtrade.resolvers.iresolver - WARNING - Could not import D:\repos\freqtrade\user_data\strategies\Heracles.py due to 'No module named 'ta''
2022-10-13 14:18:26,821 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy MyFutures from 'D:\repos\freqtrade\user_data\strategies\MyFutures.py'...
2022-10-13 14:18:26,822 - freqtrade.strategy.hyper - INFO - Found no parameter file.
2022-10-13 14:18:26,822 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 15m.
2022-10-13 14:18:26,822 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'order_types' with value in config file: {'entry': 'limit', 'exit': 'limit', 'emergency_exit': 'market', 'force_entry': 'market', 'force_exit': 'market', 'stoploss': 'market', 'stoploss_on_exchange': True, 'stoploss_on_exchange_interval': 60}.
2022-10-13 14:18:26,823 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2022-10-13 14:18:26,823 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: unlimited.
2022-10-13 14:18:26,823 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'entry': 10, 'exit': 30}.
2022-10-13 14:18:26,823 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {}
2022-10-13 14:18:26,824 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 15m
2022-10-13 14:18:26,824 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.3
2022-10-13 14:18:26,824 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: True
2022-10-13 14:18:26,824 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive: 0.01
2022-10-13 14:18:26,824 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.05
2022-10-13 14:18:26,825 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: True
2022-10-13 14:18:26,825 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: True
2022-10-13 14:18:26,825 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: True
2022-10-13 14:18:26,825 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'entry': 'limit', 'exit': 'limit', 'emergency_exit': 'market', 'force_entry': 'market', 'force_exit': 'market', 'stoploss': 'market', 'stoploss_on_exchange': True, 'stoploss_on_exchange_interval': 60}
2022-10-13 14:18:26,826 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'entry': 'GTC', 'exit': 'GTC'}
2022-10-13 14:18:26,826 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2022-10-13 14:18:26,826 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: unlimited
2022-10-13 14:18:26,826 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2022-10-13 14:18:26,826 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 30
2022-10-13 14:18:26,827 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'entry': 10, 'exit': 30}
2022-10-13 14:18:26,827 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_exit_signal: True
2022-10-13 14:18:26,827 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_only: True
2022-10-13 14:18:26,827 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_entry_signal: False
2022-10-13 14:18:26,828 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_offset: 0.0
2022-10-13 14:18:26,828 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2022-10-13 14:18:26,828 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2022-10-13 14:18:26,828 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: False
2022-10-13 14:18:26,828 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: 5
2022-10-13 14:18:26,842 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "D:\repos\freqtrade\freqtrade\commands\trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "D:\repos\freqtrade\freqtrade\worker.py", line 36, in __init__
    self._init(False)
  File "D:\repos\freqtrade\freqtrade\worker.py", line 53, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "D:\repos\freqtrade\freqtrade\freqtradebot.py", line 65, in __init__
    validate_config_consistency(config)
  File "D:\repos\freqtrade\freqtrade\configuration\config_validation.py", line 95, in validate_config_consistency
    validate_config_schema(conf, preliminary=preliminary)
  File "D:\repos\freqtrade\freqtrade\configuration\config_validation.py", line 66, in validate_config_schema
    raise ValidationError(
jsonschema.exceptions.ValidationError: {} does not have enough properties
```

**Comment by xmatthias** [comment]
Seems like this fell victim to some other bugfix ...
