### ISSUE TITLE
`Unable to allocate` error during trade

### ISSUE THREAD

**Issue by ZahariaLevy** [freqtrade/freqtrade#7614]
## Describe your environment

  * Operating system: Windows 11
  * Python Version: Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)] on win32
  * Freqtrade Version: freqtrade 2022.9.dev-895b15abb

## Describe the problem:

After a few hours of running, Freqtrade is crashing with `Unable to allocate` error. It was working some time ago for days without issue. There were changes in strategy from that time, but nothing dramatic. So I can't figure out what can be root cause. My system has 32Gb of memory, and it doesn't seem to be overused at the moment of crash. Full logs of error:
```
2022-10-20 19:26:51,092 - freqtrade.worker - INFO - Bot heartbeat. PID=21744, version='2022.9.dev-895b15abb', state='RUNNING'
2022-10-20 19:27:49,367 - freqtrade.commands.trade_commands - ERROR - Unable to allocate 226. KiB for an array with shape (29, 999) and data type float64
2022-10-20 19:27:49,368 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "C:\git\freqtrade\freqtrade\commands\trade_commands.py", line 19, in start_trading
    worker.run()
  File "C:\git\freqtrade\freqtrade\worker.py", line 75, in run
    state = self._worker(old_state=state)
  File "C:\git\freqtrade\freqtrade\worker.py", line 115, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
  File "C:\git\freqtrade\freqtrade\worker.py", line 140, in _throttle
    result = func(*args, **kwargs)
  File "C:\git\freqtrade\freqtrade\worker.py", line 153, in _process_running
    self.freqtrade.process()
  File "C:\git\freqtrade\freqtrade\freqtradebot.py", line 225, in process
    self.enter_positions()
  File "C:\git\freqtrade\freqtrade\freqtradebot.py", line 465, in enter_positions
    trades_created += self.create_trade(pair)
  File "C:\git\freqtrade\freqtrade\freqtradebot.py", line 495, in create_trade
    (signal, enter_tag) = self.strategy.get_entry_signal(
  File "C:\git\freqtrade\freqtrade\strategy\interface.py", line 917, in get_entry_signal
    latest, latest_date = self.get_latest_candle(pair, timeframe, dataframe)
  File "C:\git\freqtrade\freqtrade\strategy\interface.py", line 849, in get_latest_candle
    latest = dataframe.loc[dataframe['date'] == latest_date].iloc[-1]
  File "C:\git\freqtrade\.env\lib\site-packages\pandas\core\indexing.py", line 1074, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "C:\git\freqtrade\.env\lib\site-packages\pandas\core\indexing.py", line 1293, in _getitem_axis
    return self._getbool_axis(key, axis=axis)
  File "C:\git\freqtrade\.env\lib\site-packages\pandas\core\indexing.py", line 1094, in _getbool_axis
    return self.obj._take_with_is_copy(inds, axis=axis)
  File "C:\git\freqtrade\.env\lib\site-packages\pandas\core\generic.py", line 3903, in _take_with_is_copy
    result = self._take(indices=indices, axis=axis)
  File "C:\git\freqtrade\.env\lib\site-packages\pandas\core\generic.py", line 3885, in _take
    self._consolidate_inplace()
  File "C:\git\freqtrade\.env\lib\site-packages\pandas\core\generic.py", line 5985, in _consolidate_inplace
    self._protect_consolidate(f)
  File "C:\git\freqtrade\.env\lib\site-packages\pandas\core\generic.py", line 5973, in _protect_consolidate
    result = f()
  File "C:\git\freqtrade\.env\lib\site-packages\pandas\core\generic.py", line 5983, in f
    self._mgr = self._mgr.consolidate()
  File "C:\git\freqtrade\.env\lib\site-packages\pandas\core\internals\managers.py", line 679, in consolidate
    bm._consolidate_inplace()
  File "C:\git\freqtrade\.env\lib\site-packages\pandas\core\internals\managers.py", line 1848, in _consolidate_inplace
    self.blocks = _consolidate(self.blocks)
  File "C:\git\freqtrade\.env\lib\site-packages\pandas\core\internals\managers.py", line 2296, in _consolidate
    merged_blocks, _ = _merge_blocks(
  File "C:\git\freqtrade\.env\lib\site-packages\pandas\core\internals\managers.py", line 2355, in _merge_blocks
    new_values = new_values[argsort]
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 226. KiB for an array with shape (29, 999) and data type float64
2022-10-20 19:27:49,733 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2022-10-20 19:27:49,733 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2022-10-20 19:27:49,733 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2022-10-20 19:27:49,736 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
2022-10-20 19:27:49,736 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.apiserver ...
2022-10-20 19:27:49,737 - freqtrade.rpc.api_server.webserver - INFO - Stopping API Server
2022-10-20 19:27:49,750 - uvicorn.error - INFO - Shutting down
2022-10-20 19:27:49,858 - uvicorn.error - INFO - Waiting for application shutdown.
2022-10-20 19:27:49,859 - uvicorn.error - INFO - Application shutdown complete.
2022-10-20 19:27:49,859 - uvicorn.error - INFO - Finished server process [21744]
2022-10-20 19:27:49,860 - freqtrade.rpc.api_server.webserver - INFO - Stopping API Server background tasks
```

**Comment by xmatthias** [comment]
are you running the 32bit or 64bit version of python? (i'm not sure what the "win32" means in your version string).

having 32Gb of ram is nice - but a 32bit process an only address 4 Gb of them - so they're basically useless - at least for this process.
This [stackoverflow answer](https://stackoverflow.com/a/59101232) explains this for windows.

In the end, the error will be exactly what it says - numpy can't allocate more memory.
if you're sure you're running a 64bit python (and you're not running out of memory) - then it'd suggest a numpy bug - which is highly unlikely.

**Comment by ZahariaLevy** [comment]
It's definitely 64bit version. But I investigated a bit more, and it looks like some sort of memory leak, because it usage slowly increasing. But what I do is only comparing some values from `dataframe` not much different from example strategies, without any manual storing of data or anything. So I don't understand what could suddenly cause this issue.

**Comment by xmatthias** [comment]
Best update to the latest version, there was some random 2022.9-dev version that did have a memory leak in certain circumstances.
