### ISSUE TITLE
Closing position after stop on exchange cause exception

### ISSUE THREAD

**Issue by farmage** [freqtrade/freqtrade#7694]
## Describe your environment

  * Operating system: Ubuntu 18
  * Python Version: 3.10 (`python -V`)
  * CCXT version: 2.0.96 (`pip freeze | grep ccxt`)
  * Freqtrade Version: latest git dev (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

### Steps to reproduce:

  1. Position closed by stoploss on exchange
  2. It still hanging in the orders list in freqtrade
  3. Log shows exception
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```

2022-11-03 10:43:41,538 - freqtrade.freqtradebot - INFO - Canceling stoploss on exchange for Trade(id=15, pair=AUDIO/USDT, amount=906.00000000, is_short=False, leverage=2.0, open_rate=0.22070000, open_since=2022-10-04 20:01:44)
2022-11-03 10:43:42,971 - freqtrade.wallets - INFO - Wallets synced.
2022-11-03 10:43:43,312 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/xcash/fq_mary_usdt/.env/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/xcash/fq_mary_usdt/.env/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/xcash/fq_mary_usdt/.env/lib/python3.10/site-packages/uvicorn/middleware/message_logger.py", line 86, in __call__
    raise exc from None
  File "/home/xcash/fq_mary_usdt/.env/lib/python3.10/site-packages/uvicorn/middleware/message_logger.py", line 82, in __call__
    await self.app(scope, inner_receive, inner_send)
  File "/home/xcash/fq_mary_usdt/.env/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/home/xcash/fq_mary_usdt/.env/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/xcash/fq_mary_usdt/.env/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/xcash/fq_mary_usdt/.env/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/xcash/fq_mary_usdt/.env/lib/python3.10/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/xcash/fq_mary_usdt/.env/lib/python3.10/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/home/xcash/fq_mary_usdt/.env/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
    raise exc
  File "/home/xcash/fq_mary_usdt/.env/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "/home/xcash/fq_mary_usdt/.env/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/xcash/fq_mary_usdt/.env/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/xcash/fq_mary_usdt/.env/lib/python3.10/site-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "/home/xcash/fq_mary_usdt/.env/lib/python3.10/site-packages/starlette/routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "/home/xcash/fq_mary_usdt/.env/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/home/xcash/fq_mary_usdt/.env/lib/python3.10/site-packages/fastapi/routing.py", line 231, in app
    raw_response = await run_endpoint_function(
  File "/home/xcash/fq_mary_usdt/.env/lib/python3.10/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/xcash/fq_mary_usdt/.env/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/xcash/fq_mary_usdt/.env/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/xcash/fq_mary_usdt/.env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/xcash/fq_mary_usdt/.env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/xcash/fq_mary_usdt/freqtrade/rpc/api_server/api_v1.py", line 163, in forceexit
    return rpc._rpc_force_exit(payload.tradeid, ordertype, amount=payload.amount)
  File "/home/xcash/fq_mary_usdt/freqtrade/rpc/rpc.py", line 737, in _rpc_force_exit
    self.__exec_force_exit(trade, ordertype, amount)
  File "/home/xcash/fq_mary_usdt/freqtrade/rpc/rpc.py", line 706, in __exec_force_exit
    self._freqtrade.execute_trade_exit(
  File "/home/xcash/fq_mary_usdt/freqtrade/freqtradebot.py", line 1574, in execute_trade_exit
    order = self.exchange.create_order(
  File "/home/xcash/fq_mary_usdt/freqtrade/exchange/exchange.py", line 1063, in create_order
    raise ExchangeError(
freqtrade.exceptions.ExchangeError: Could not create market sell order on market AUDIO/USDT. Tried to sell amount 906.0 at rate 0.2235. Message: binance {"code":-2022,"msg":"ReduceOnly Order is rejected."}
2022-11-03 10:44:04,196 - freqtrade.exchange.exchange - INFO - stoploss market order added for AUDIO/USDT. stop price: 0.1325. limit: None

```

**Comment by xmatthias** [comment]
"latest git dev" is not a proper version number - but a moving target that changes potentially multiple times per day.
Please provide the correct version number, otherwise i'll simply assume it's an outdated version (latest dev can be anything).

It's however unclear what you're doing exactly (and on what exchange).
is it a stoploss on exchange (created by freqtrade) that did trigger? 
or a manually placed stoploss?

The log suggests that it does successfully cancel the stoploss on exchange (first logline) - which implies it's still been there (not filled) and therefore could be canceled. 
it and then fails to create a new order  (unclear as to why) - but successfully places a new stoploss order.

**Comment by farmage** [comment]
I'm using my own repo merged with the latest dev branch. My changes related only to the telegram module, so assume it behaves as the original repo. The last update I did a few hours ago.
The stoploss was placed on the custom_stoploss function as a custom trailing stop. After the price reached the stoploss on the exchange the position on exchange was closed entirely. But as you see, it causes an exception. It seems like that error code is not supported. Maybe I'll check the code later to contribute.
Anyway, thank you for your quick response :)

**Comment by xmatthias** [comment]
which exchange are we talking about? which markets (futures / spot) ? 

I also think you're miss-reading the problem - based on the log (which is a bit short for my likings) - it's not detecting that the stoploss triggered.
The failure in placing a regular sell order is clear if the exchange really filled the  stoploss (you no longer own this amount) - However - it's unclear why it would then succeed in placing a new stoploss order (you still don't own this amount).

**Comment by farmage** [comment]
It Binance, futures.
Yep, I don't know why it shows it placed a new stop. But maybe it's another bug. Sometimes, in Binance trade history I see canceled stop order after the position was closed. Just within a few seconds. I've seen it a few times in another terminal I use - Finandy
It is bipping with sound then new order is created. So, today was that case. 
Just looked at the logs. It tried to cancel over and over before I deleted the position from telegram bot manually
![Screenshot from 2022-11-03 14-55-35](https://user-images.githubusercontent.com/82975149/199726402-2065b4cd-47f6-4af4-940a-99ee1ef2753d.png)

**Comment by xmatthias** [comment]
have you also got a screenshot from the order that was filled?

**Comment by Mo7mud** [comment]
I'm using latest stable version 2022.9.1
I have the same issue
Using Kucoin exchange

```
2022-11-04 02:23:22,333 - freqtrade.freqtradebot - INFO - Exit for BTC/USDT detected. Reason: roi
2022-11-04 02:23:22,636 - freqtrade.wallets - INFO - Wallets synced.
2022-11-04 02:23:23,089 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': exit, 'trade_id': 116, 'exchange': 'Kucoin', 'pair': 'BTC/USDT', 'leverage': 1.0, 'direction': 'Long', 'gain': 'profit', 'limit': 20296.2, 'order_rate': 20296.2, 'order_type': 'limit', 'amount': 0.00013633, 'open_rate': 20138.8, 'close_rate': 20296.2, 'current_rate': 20296.2, 'profit_amount': 0.02145834, 'profit_ratio': 0.00781576, 'buy_tag': 'v_bottom_shape', 'enter_tag': 'v_bottom_shape', 'sell_reason': 'roi', 'exit_reason': 'roi', 'open_date': datetime.datetime(2022, 11, 3, 11, 55, 15, 597222), 'close_date': datetime.datetime(2022, 11, 4, 0, 23, 23, 88943), 'stake_amount': 2.745522604, 'stake_currency': 'USDT', 'fiat_currency': 'USD', 'sub_trade': False, 'cumulative_profit': 0.0}
2022-11-04 02:23:23,274 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "E:\freqtrade\.env\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "E:\freqtrade\.env\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "E:\freqtrade\.env\lib\site-packages\uvicorn\middleware\message_logger.py", line 86, in __call__
    raise exc from None
  File "E:\freqtrade\.env\lib\site-packages\uvicorn\middleware\message_logger.py", line 82, in __call__
    await self.app(scope, inner_receive, inner_send)
  File "E:\freqtrade\.env\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "E:\freqtrade\.env\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "E:\freqtrade\.env\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "E:\freqtrade\.env\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "E:\freqtrade\.env\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "E:\freqtrade\.env\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    raise exc
  File "E:\freqtrade\.env\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "E:\freqtrade\.env\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "E:\freqtrade\.env\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "E:\freqtrade\.env\lib\site-packages\starlette\routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "E:\freqtrade\.env\lib\site-packages\starlette\routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "E:\freqtrade\.env\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "E:\freqtrade\.env\lib\site-packages\fastapi\routing.py", line 231, in app
    raw_response = await run_endpoint_function(
  File "E:\freqtrade\.env\lib\site-packages\fastapi\routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "E:\freqtrade\.env\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "E:\freqtrade\.env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\freqtrade\.env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\freqtrade\.env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\freqtrade\freqtrade\rpc\api_server\api_v1.py", line 99, in status
    return rpc._rpc_trade_status()
  File "E:\freqtrade\freqtrade\rpc\rpc.py", line 221, in _rpc_trade_status
    open_order='({} {} rem={:.8f})'.format(
TypeError: unsupported format string passed to NoneType.__format__
```
![image](https://user-images.githubusercontent.com/12565380/199859923-e6074672-6efd-455e-a666-f0a6f3efdbb0.png)


![image](https://user-images.githubusercontent.com/12565380/199860003-f760dd3f-5705-4532-aa21-9542b58ccef9.png)

**Comment by xmatthias** [comment]
@EgyptianM no you don't. It's a completely different, unrelated issue. best open a new issue - i'm going to hide your comment here as off-topic, as is has nothing to do with this issue other than "both happen while using freqtrade".

**Comment by farmage** [comment]
And once again
XRP closed, but still trying change stoploss and cancel it
![Screenshot from 2022-11-04 12-15-04](https://user-images.githubusercontent.com/82975149/199948962-61e9d92b-1ad6-48ae-899c-b12932468b4b.png)
And bunch of exceptions
```
2022-11-04 10:16:10,439 - freqtrade.freqtradebot - ERROR - Could not cancel stoploss order 25782828322
Traceback (most recent call last):
  File "/home/xcash/fq_mary_usdt/.env/lib/python3.10/site-packages/ccxt/base/exchange.py", line 620, in fetch
    response.raise_for_status()
  File "/home/xcash/fq_mary_usdt/.env/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://fapi.binance.com/fapi/v1/order?timestamp=1667556970198&symbol=XRPUSDT&orderId=25782828322&recvWindow=10000&signature=9e672004b107881abe6886b466cc7c227b165724a5343308de8fe8422b6bb192

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xcash/fq_mary_usdt/freqtrade/exchange/exchange.py", line 1262, in cancel_order
    order = self._api.cancel_order(order_id, pair, params=params)
  File "/home/xcash/fq_mary_usdt/.env/lib/python3.10/site-packages/ccxt/binance.py", line 3201, in cancel_order
    response = getattr(self, method)(self.extend(request, requestParams))
  File "/home/xcash/fq_mary_usdt/.env/lib/python3.10/site-packages/ccxt/base/exchange.py", line 500, in inner
    return entry(_self, **inner_kwargs)
  File "/home/xcash/fq_mary_usdt/.env/lib/python3.10/site-packages/ccxt/binance.py", line 5576, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/xcash/fq_mary_usdt/.env/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2609, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/xcash/fq_mary_usdt/.env/lib/python3.10/site-packages/ccxt/base/exchange.py", line 636, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/xcash/fq_mary_usdt/.env/lib/python3.10/site-packages/ccxt/binance.py", line 5554, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
  File "/home/xcash/fq_mary_usdt/.env/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2882, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.OrderNotFound: binance {"code":-2011,"msg":"Unknown order sent."}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/xcash/fq_mary_usdt/freqtrade/freqtradebot.py", line 826, in cancel_stoploss_on_exchange
    co = self.exchange.cancel_stoploss_order_with_result(
  File "/home/xcash/fq_mary_usdt/freqtrade/exchange/exchange.py", line 1328, in cancel_stoploss_order_with_result
    corder = self.cancel_stoploss_order(order_id, pair)
  File "/home/xcash/fq_mary_usdt/freqtrade/exchange/exchange.py", line 1278, in cancel_stoploss_order
    return self.cancel_order(order_id, pair, params)
  File "/home/xcash/fq_mary_usdt/freqtrade/exchange/common.py", line 165, in wrapper
    return f(*args, **kwargs)
  File "/home/xcash/fq_mary_usdt/freqtrade/exchange/exchange.py", line 1267, in cancel_order
    raise InvalidOrderException(
freqtrade.exceptions.InvalidOrderException: Could not cancel order. Message: binance {"code":-2011,"msg":"Unknown order sent."}
2022-11-04 10:16:10,990 - freqtrade.wallets - INFO - Wallets synced.
2022-11-04 10:16:11,236 - freqtrade.freqtradebot - WARNING - Unable to adjust position of trade for XRP/USDT: Could not create market sell order on market XRP/USDT. Tried to sell amount 394.7 at rate 0.5067. Message: binance {"code":-2022,"msg":"ReduceOnly Order is rejected."}
2022-11-04 10:16:33,321 - freqtrade.exchange.exchange - INFO - stoploss market order added for XRP/USDT. stop price: 0.285. limit: None
2022-11-04 10:16:33,595 - freqtrade.freqtradebot - INFO - Exit for XRP/USDT detected. Reason: roi
2022-11-04 10:16:35,122 - freqtrade.freqtradebot - INFO - Canceling stoploss on exchange for Trade(id=78, pair=XRP/USDT, amount=842.10000000, is_short=False, leverage=2.0, open_rate=0.47500000, open_since=2022-10-17 12:01:03)
2022-11-04 10:16:36,204 - freqtrade.wallets - INFO - Wallets synced.
2022-11-04 10:16:36,465 - freqtrade.freqtradebot - WARNING - Unable to exit trade XRP/USDT: Could not create market sell order on market XRP/USDT. Tried to sell amount 842.1 at rate 0.5038. Message: binance {"code":-2022,"msg":"ReduceOnly Order is rejected."}
2022-11-04 10:16:44,164 - freqtrade.freqtradebot - INFO - Canceling stoploss on exchange for Trade(id=78, pair=XRP/USDT, amount=842.10000000, is_short=False, leverage=2.0, open_rate=0.47500000, open_since=2022-10-17 12:01:03)
2022-11-04 10:16:45,072 - freqtrade.freqtradebot - ERROR - Could not cancel stoploss order 25782877463
Traceback (most recent call last):
  File "/home/xcash/fq_mary_usdt/.env/lib/python3.10/site-packages/ccxt/base/exchange.py", line 620, in fetch
    response.raise_for_status()
  File "/home/xcash/fq_mary_usdt/.env/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://fapi.binance.com/fapi/v1/order?timestamp=1667557004165&symbol=XRPUSDT&orderId=25782877463&recvWindow=10000&signature=101b2b9cf60c2424c357509793bd93323a4cf1f280c5538b5a9c796502a49923

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xcash/fq_mary_usdt/freqtrade/exchange/exchange.py", line 1262, in cancel_order
    order = self._api.cancel_order(order_id, pair, params=params)
  File "/home/xcash/fq_mary_usdt/.env/lib/python3.10/site-packages/ccxt/binance.py", line 3201, in cancel_order
    response = getattr(self, method)(self.extend(request, requestParams))
  File "/home/xcash/fq_mary_usdt/.env/lib/python3.10/site-packages/ccxt/base/exchange.py", line 500, in inner
    return entry(_self, **inner_kwargs)
  File "/home/xcash/fq_mary_usdt/.env/lib/python3.10/site-packages/ccxt/binance.py", line 5576, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/xcash/fq_mary_usdt/.env/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2609, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/xcash/fq_mary_usdt/.env/lib/python3.10/site-packages/ccxt/base/exchange.py", line 636, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/xcash/fq_mary_usdt/.env/lib/python3.10/site-packages/ccxt/binance.py", line 5554, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
  File "/home/xcash/fq_mary_usdt/.env/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2882, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.OrderNotFound: binance {"code":-2011,"msg":"Unknown order sent."}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/xcash/fq_mary_usdt/freqtrade/freqtradebot.py", line 826, in cancel_stoploss_on_exchange
    co = self.exchange.cancel_stoploss_order_with_result(
  File "/home/xcash/fq_mary_usdt/freqtrade/exchange/exchange.py", line 1328, in cancel_stoploss_order_with_result
    corder = self.cancel_stoploss_order(order_id, pair)
  File "/home/xcash/fq_mary_usdt/freqtrade/exchange/exchange.py", line 1278, in cancel_stoploss_order
    return self.cancel_order(order_id, pair, params)
  File "/home/xcash/fq_mary_usdt/freqtrade/exchange/common.py", line 165, in wrapper
    return f(*args, **kwargs)
  File "/home/xcash/fq_mary_usdt/freqtrade/exchange/exchange.py", line 1267, in cancel_order
    raise InvalidOrderException(
freqtrade.exceptions.InvalidOrderException: Could not cancel order. Message: binance {"code":-2011,"msg":"Unknown order sent."}
```

**Comment by xmatthias** [comment]
please provide full logs (a few lines before / after the exception).

Just the exception is not telling us what we were trying to accomplish.

**Comment by farmage** [comment]
[xrp.bug.log](https://github.com/freqtrade/freqtrade/files/9937727/xrp.bug.log)

**Comment by xmatthias** [comment]
please post the output of 

`freqtrade show-trades --db-url sqlite:///<trades.sqlite> --print-json --trade-ids 78` (the trade-id for the XRP trade).

The log also seems odd - the XRP trade seems to be open since >10 days ... and basically all commands for it fail - which makes me suspect that the trade / position was actually closed quite some time ago already.


Combining the screenshots from above (which places XRP stoploss orders with a quantity of 842) with the log (which is selling 405 XRP) - i suspect it's an issue with the position adjustment.

It might be possible that this goes across some exchange limits which might explain why the exchange rejects the order - although a 405 XRP position at 2x leverage doesn't seem impossible.

**Comment by xmatthias** [comment]
i can't really recreate / reproduce this error. I' can open, adjust and close positions on binance just fine - also using the sizes (as estimated) from the logs above.

If the trade was opened with an old version this might be an explanation. 
does this also happen on newly opened trades (trades that only opened with this version) ?

**Comment by xmatthias** [comment]
@farmage is this still an issue on newly opened trades?

**Comment by farmage** [comment]
My orders on exchange are not closed yet. I've updated the build. Post the results as I've got something

**Comment by xmatthias** [comment]
still no news?

**Comment by farmage** [comment]
I haven't seen this issue anymore. you may close it. I'll reopen the case if see the problem again.

Thanks!

-------- Original Message --------
