### ISSUE TITLE
Can't use freqtrade with bitget exchange because it don't recognize the timeframe

### ISSUE THREAD

**Issue by JrCs** [freqtrade/freqtrade#7704]
## Describe your environment

  * Operating system: Amazon Linux 2
  * Python Version: Python 3.10.8
  * CCXT version: ccxt==2.0.96
  * Freqtrade Version: freqtrade 2022.11.dev
  
## Describe the problem:

Can't use freqtrade with bitget exchange because it don't recognize the timeframe:
```
2022-11-05 08:38:17,891 - freqtrade.resolvers.exchange_resolver - INFO - No Bitget specific subclass found. Using the generic class instead.
2022-11-05 08:38:17,892 - freqtrade.exchange.exchange - INFO - Using CCXT 2.0.96
2022-11-05 08:38:17,902 - freqtrade.exchange.exchange - INFO - Using Exchange "Bitget"
2022-11-05 08:38:20,410 - freqtrade.commands.trade_commands - ERROR - Invalid timeframe '5m'. This exchange supports: ['spot', 'swap']
2022-11-05 08:38:20,411 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
```

### Steps to reproduce:

  1. freqtrade trade -s SampleStrategy
  
### Observed Results:

  * Freqtrade doesn't recognize the timeframe and return on error about supporting only 'spot' or 'swap' which is not the timeframe.

### Relevant code exceptions or logs

  ```
2022-11-05 08:38:17,887 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2022-11-05 08:38:17,891 - freqtrade.resolvers.exchange_resolver - INFO - No Bitget specific subclass found. Using the generic class instead.
2022-11-05 08:38:17,892 - freqtrade.exchange.exchange - INFO - Using CCXT 2.0.96
2022-11-05 08:38:17,902 - freqtrade.exchange.exchange - INFO - Using Exchange "Bitget"
2022-11-05 08:38:20,410 - freqtrade.commands.trade_commands - ERROR - Invalid timeframe '5m'. This exchange supports: ['spot', 'swap']
2022-11-05 08:38:20,411 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/data/freqtrade.git/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/data/freqtrade.git/freqtrade/worker.py", line 37, in __init__
    self._init(False)
  File "/data/freqtrade.git/freqtrade/worker.py", line 53, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/data/freqtrade.git/freqtrade/freqtradebot.py", line 67, in __init__
    self.exchange = ExchangeResolver.load_exchange(
  File "/data/freqtrade.git/freqtrade/resolvers/exchange_resolver.py", line 45, in load_exchange
    exchange = Exchange(config, validate=validate)
  File "/data/freqtrade.git/freqtrade/exchange/exchange.py", line 188, in __init__
    self.validate_config(config)
  File "/data/freqtrade.git/freqtrade/exchange/exchange.py", line 216, in validate_config
    self.validate_timeframes(config.get('timeframe'))
  File "/data/freqtrade.git/freqtrade/exchange/exchange.py", line 595, in validate_timeframes
    raise OperationalException(
freqtrade.exceptions.OperationalException: Invalid timeframe '5m'. This exchange supports: ['spot', 'swap']
  ```

**Comment by xmatthias** [comment]
Bitget seems to be the only exchange in ccxt that doesn't follow their own standard (which is - defining timeframes in the "timeframes" property).
it's defining timeframes at one level deeper - which is (in my understanding) not following the ccxt self-defined standard.

bitget is not an exchange we currently support - and based on this issue - it's very likely that it's an exchange that's not going to work out of the box (if this is already a problem, there's most likely many others to follow).

So if you're willing to have this exchange working - expect to put in quite some time to get it to a usable state.

While we can support in this to some degree - most of the work/ time invest will be on your side - and it'd be best if you already have some experience with reading python exceptions / development.

The best approach here will be to raise an issue against the ccxt project. 
For now, i see the issue on their side (not following the standard). Depending on their answer, we can either try to adapt freqtrade for this exchange - or they'll issue an update fixing this.

**Comment by JrCs** [comment]
Thanks @xmatthias for the answer.  
One advantage of bitget is that de transaction fees on spot are free.  
I think we can close this issue, waiting for ccxt teams to fix the issue ?

**Comment by xmatthias** [comment]
I guess so if you reported it there.

We can obviously reopen this if they say "this is the new normal" - but i'd assume this to be the exception ...
