### ISSUE TITLE
ERROR - Unexpected error '&-s_close_max' calling <bound method IStrategy._analyze_ticker_internal of <FreqaiExampleStrategy.FreqaiExampleStrategy object at 0xffff6a071d50>>

### ISSUE THREAD

**Issue by tomjrtsmith** [freqtrade/freqtrade#7722]
## Describe your environment

  * Operating system: Ubuntu 20.04
  * Python Version: Python 3.10.6
  * CCXT version: can't seem to find it using pip freeze - latest docker pull
  * Freqtrade Version: freqtrade docker-2022.11.dev-ce3959a0
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Errors running FreqaiExampleStrategy / LightGBMRegressor

### Steps to reproduce:

  1. Run Freqai
    
### Observed Results:

  * Runs downloading candle data and then errors. Unsure why the strategy file is a fresh copy with no edits

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
freqai2  | 2022-11-08 20:50:11,900 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair ATOM/USDT: '&-s_close_mean'
freqai2  | 2022-11-08 20:50:12,073 - freqtrade.freqai.data_kitchen - INFO - dropped 41 of 1001 prediction data points due to NaNs.
freqai2  | 2022-11-08 20:50:12,089 - freqtrade.freqai.data_kitchen - INFO - SVM tossed 352 predictions.
freqai2  | 2022-11-08 20:50:12,550 - freqtrade.freqai.data_kitchen - INFO - DI tossed 241 predictions for being too far from training data.
freqai2  | 2022-11-08 20:50:12,655 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error '&-s_close_mean' calling <bound method IStrategy._analyze_ticker_internal of <FreqaiExampleStrategy.FreqaiExampleStrategy object at 0xffff6a071d50>>
freqai2  | Traceback (most recent call last):
freqai2  |   File "/home/ftuser/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3803, in get_loc
freqai2  |     return self._engine.get_loc(casted_key)
freqai2  |   File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
freqai2  |   File "pandas/_libs/index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
freqai2  |   File "pandas/_libs/hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
freqai2  |   File "pandas/_libs/hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
freqai2  | KeyError: '&-s_close_mean'
freqai2  |
freqai2  | The above exception was the direct cause of the following exception:
freqai2  |
freqai2  | Traceback (most recent call last):
freqai2  |   File "/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 27, in wrapper
freqai2  |     return f(*args, **kwargs)
freqai2  |   File "/freqtrade/freqtrade/strategy/interface.py", line 748, in _analyze_ticker_internal
freqai2  |     dataframe = self.analyze_ticker(dataframe, metadata)
freqai2  |   File "/freqtrade/freqtrade/strategy/interface.py", line 726, in analyze_ticker
freqai2  |     dataframe = self.advise_indicators(dataframe, metadata)
freqai2  |   File "/freqtrade/freqtrade/strategy/interface.py", line 1221, in advise_indicators
freqai2  |     return self.populate_indicators(dataframe, metadata)
freqai2  |   File "/freqtrade/user_data/strategies/FreqaiExampleStrategy.py", line 177, in populate_indicators
freqai2  |     dataframe["&-s_close_mean"] + dataframe["&-s_close_std"] * val
freqai2  |   File "/home/ftuser/.local/lib/python3.10/site-packages/pandas/core/frame.py", line 3804, in __getitem__
freqai2  |     indexer = self.columns.get_loc(key)
freqai2  |   File "/home/ftuser/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
freqai2  |     raise KeyError(key) from err
freqai2  | KeyError: '&-s_close_mean'
  ```

**Comment by tomjrtsmith** [comment]
I fixed this, it needed a new pairs label and the models folder deleted

**Comment by xmatthias** [comment]
almost all changes to strategy / models / freqAI config in combination with freqAI will require a new model identifier (or deletion of the model directory).
