### ISSUE TITLE
Fatal exception after ERROR - Maintenance margin rate is unavailable

### ISSUE THREAD

**Issue by piccolorio** [freqtrade/freqtrade#7794]
2022-11-25 00:39:52,914 - freqtrade.worker - INFO - Bot heartbeat. PID=1745, version='2022.11.dev-8cb2b4666', state='RUNNING'
2022-11-25 00:39:52,979 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=19, pair=ETC/USDT, amount=15.07007585, is_short=False, leverage=1.0, open_rate=19.90700000, open_since=2022-11-25 00:30:08)
2022-11-25 00:39:57,982 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=19, pair=ETC/USDT, amount=15.07007585, is_short=False, leverage=1.0, open_rate=19.90700000, open_since=2022-11-25 00:30:08)
2022-11-25 00:40:07,239 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=19, pair=ETC/USDT, amount=15.07007585, is_short=False, leverage=1.0, open_rate=19.90700000, open_since=2022-11-25 00:30:08)
2022-11-25 00:40:10,321 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=19, pair=ETC/USDT, amount=15.07007585, is_short=False, leverage=1.0, open_rate=19.90700000, open_since=2022-11-25 00:30:08)
2022-11-25 00:40:10,523 - freqtrade.freqtradebot - INFO - Buy order cancelled due to timeout for Trade(id=19, pair=ETC/USDT, amount=15.07007585, is_short=False, leverage=1.0, open_rate=19.90700000, open_since=2022-11-25 00:30:08).
2022-11-25 00:40:10,523 - freqtrade.freqtradebot - INFO - Buy order fully cancelled. Removing Trade(id=19, pair=ETC/USDT, amount=15.07007585, is_short=False, leverage=1.0, open_rate=19.90700000, open_since=2022-11-25 00:30:08) from database.
2022-11-25 00:40:10,531 - freqtrade.wallets - INFO - Wallets synced.
2022-11-25 00:40:10,532 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'trade_id': 19, 'type': entry_cancel, 'buy_tag': None, 'enter_tag': None, 'exchange': 'Binance', 'pair': 'ETC/USDT', 'leverage': 1.0, 'direction': 'Long', 'limit': 19.907, 'order_type': 'limit', 'stake_amount': 300.0, 'stake_currency': 'USDT', 'fiat_currency': 'USD', 'amount': 15.070075852715126, 'open_date': datetime.datetime(2022, 11, 25, 0, 30, 8, 636012), 'current_rate': 20.006, 'reason': 'cancelled due to timeout, fully cancelled', 'sub_trade': False}
2022-11-25 00:40:10,904 - freqtrade.wallets - INFO - Wallets synced.
2022-11-25 00:40:10,964 - freqtrade.freqtradebot - INFO - Long signal found: about create a new trade for APT/USDT with stake_amount: 300 ...
2022-11-25 00:40:11,064 - freqtrade.freqtradebot - INFO - Order #dry_run_buy_1669336810.964378 was created for APT/USDT and status is open.
2022-11-25 00:40:11,443 - freqtrade.wallets - INFO - Wallets synced.
2022-11-25 00:40:11,443 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'trade_id': 19, 'type': entry, 'buy_tag': None, 'enter_tag': None, 'exchange': 'Binance', 'pair': 'APT/USDT', 'leverage': 1.0, 'direction': 'Long', 'limit': 4.3351, 'open_rate': 4.3351, 'order_type': 'limit', 'stake_amount': 300.0, 'stake_currency': 'USDT', 'fiat_currency': 'USD', 'amount': 69.2, 'open_date': datetime.datetime(2022, 11, 25, 0, 40, 11, 64421), 'current_rate': 4.3351, 'sub_trade': False}
2022-11-25 00:40:12,661 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=19, pair=APT/USDT, amount=69.20255588, is_short=False, leverage=1.0, open_rate=4.33510000, open_since=2022-11-25 00:40:11)
2022-11-25 00:40:17,672 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=19, pair=APT/USDT, amount=69.20255588, is_short=False, leverage=1.0, open_rate=4.33510000, open_since=2022-11-25 00:40:11)
2022-11-25 00:40:17,685 - freqtrade.freqtradebot - INFO - Fee for Trade Trade(id=19, pair=APT/USDT, amount=69.20255588, is_short=False, leverage=1.0, open_rate=4.33510000, open_since=2022-11-25 00:40:11) [buy]: 0.059997784 USDT - rate: 0.0002
2022-11-25 00:40:17,686 - freqtrade.persistence.trade_model - INFO - Updating trade (id=19) ...
2022-11-25 00:40:17,686 - freqtrade.persistence.trade_model - INFO - LIMIT_BUY has been fulfilled for Trade(id=19, pair=APT/USDT, amount=69.20000000, is_short=False, leverage=1.0, open_rate=4.33510000, open_since=2022-11-25 00:40:11).
2022-11-25 00:40:17,694 - freqtrade.commands.trade_commands - ERROR - Maintenance margin rate for APT/USDT is unavailable for Binance
2022-11-25 00:40:17,694 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/ft/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker.run()
  File "/ft/freqtrade/worker.py", line 75, in run
    state = self._worker(old_state=state)
  File "/ft/freqtrade/worker.py", line 116, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs,
  File "/ft/freqtrade/worker.py", line 147, in _throttle
    result = func(*args, **kwargs)
  File "/ft/freqtrade/worker.py", line 180, in _process_running
    self.freqtrade.process()
  File "/ft/freqtrade/freqtradebot.py", line 211, in process
    self.manage_open_orders()
  File "/ft/freqtrade/freqtradebot.py", line 1235, in manage_open_orders
    fully_cancelled = self.update_trade_state(trade, trade.open_order_id, order)
  File "/ft/freqtrade/freqtradebot.py", line 1771, in update_trade_state
    trade.set_liquidation_price(self.exchange.get_liquidation_price(
  File "/ft/freqtrade/exchange/exchange.py", line 2707, in get_liquidation_price
    isolated_liq = self.dry_run_liquidation_price(
  File "/ft/freqtrade/exchange/binance.py", line 187, in dry_run_liquidation_price
    mm_ratio, maintenance_amt = self.get_maintenance_ratio_and_amt(pair, stake_amount)
  File "/ft/freqtrade/exchange/exchange.py", line 2807, in get_maintenance_ratio_and_amt
    raise InvalidOrderException(
freqtrade.exceptions.InvalidOrderException: Maintenance margin rate for APT/USDT is unavailable for Binance
2022-11-25 00:40:17,700 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2022-11-25 00:40:17,700 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

you should also include some description on what you're trying to do - just posting an exception is rarely enough (even though it is in this case).

Binance's leverage tiers are behind authentication - therefore we use a cached file for dry-runs.
Apparently, this is a new pair - which is not yet in the cached file. I'll update the file later - which will close this issue.

**Comment by piccolorio** [comment]
Sorry, I did not notice the template and the log seemed to provide enough information. Next time I will fill the template, no worries. Thank you for looking into this. :)
