### ISSUE TITLE
WARNING - Invalid HTTP request received. ERROR - Exception in ASGI application

### ISSUE THREAD

**Issue by arielcortez** [freqtrade/freqtrade#7905]
## Describe your environment

  * Operating system: Ubuntu 22.1
  * Python Version: 3.10.7
  * CCXT version: ?
  * Freqtrade Version: 2022.11 
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

  1. Tried to follow the instructions to install / configure freqtrade 
  2. used bybit as the exchange and enabled telegram  (was able to connect and use freqtrade bot on telegram)
  3. mostly used defaults including the samplestrategy as my initial strategy
  4. Noticed that there is an error message on the log.  Need to know if i missed anything or is there something wrong with some of the codes / config file
 
  
### Observed Results:

  * What happened?   I noticed that there log displays some exception. please refer to log  below
  * What did you expect to happen? am expecting not to see those exceptions. please refer to log  below

### Relevant code exceptions or logs

022-12-16 06:30:16 - freqtrade.plugins.pairlistmanager - INFO - Whitelist with 20 pairs: ['BTC/USDT', 'ETH/USDT', 'GALFT/USDT', 'CHZ/USDT', 'XRP/USDT', 'LTC/USDT', 'DOGE/USDT', 'SOL/USDT', 'APT/USDT', 'ACM/USDT', 'AGLA/USDT', 'ADA/USDT', 'BIT/USDT', 'MATIC/USDT', 'EOS/USDT', 'JUV/USDT', 'LINK/USDT', 'AFC/USDT', 'APEX/USDT', 'TRX/USDT']
2022-12-16 06:30:21 - VolumePairList - INFO - Pair USDC/USDT in your blacklist. Removing it from whitelist...
2022-12-16 06:31:16 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2022.11', state='RUNNING'
2022-12-16 06:32:16 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2022.11', state='RUNNING'
2022-12-16 06:33:16 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2022.11', state='RUNNING'
2022-12-16 06:34:16 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2022.11', state='RUNNING'
2022-12-16 06:35:21 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2022.11', state='RUNNING'
2022-12-16 06:36:21 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2022.11', state='RUNNING'
2022-12-16 06:37:21 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2022.11', state='RUNNING'
2022-12-16 06:38:21 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2022.11', state='RUNNING'
2022-12-16 06:39:21 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2022.11', state='RUNNING'
2022-12-16 06:40:26 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2022.11', state='RUNNING'
2022-12-16 06:41:26 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2022.11', state='RUNNING'
2022-12-16 06:42:26 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2022.11', state='RUNNING'
2022-12-16 06:43:26 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2022.11', state='RUNNING'
2022-12-16 06:44:26 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2022.11', state='RUNNING'
2022-12-16 06:45:31 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2022.11', state='RUNNING'
2022-12-16 06:46:31 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2022.11', state='RUNNING'
2022-12-16 06:47:31 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2022.11', state='RUNNING'
2022-12-16 06:48:31 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2022.11', state='RUNNING'
2022-12-16 06:49:31 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2022.11', state='RUNNING'
2022-12-16 06:49:43 - uvicorn.error - WARNING - Invalid HTTP request received.
2022-12-16 06:49:48 - uvicorn.error - WARNING - Invalid HTTP request received.
2022-12-16 06:49:48 - uvicorn.error - ERROR - Exception in ASGI application

Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/ftuser/.local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/ftuser/.local/lib/python3.10/site-packages/uvicorn/middleware/message_logger.py", line 86, in __call__
    raise exc from None
  File "/home/ftuser/.local/lib/python3.10/site-packages/uvicorn/middleware/message_logger.py", line 82, in __call__
    await self.app(scope, inner_receive, inner_send)
  File "/home/ftuser/.local/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ftuser/.local/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ftuser/.local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/ftuser/.local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/ftuser/.local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/home/ftuser/.local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 91, in __call__
    await response(scope, receive, sender)
  File "/home/ftuser/.local/lib/python3.10/site-packages/starlette/responses.py", line 160, in __call__
    await send(
  File "/home/ftuser/.local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in sender
    await send(message)
  File "/home/ftuser/.local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 159, in _send
    await send(message)
  File "/home/ftuser/.local/lib/python3.10/site-packages/uvicorn/middleware/message_logger.py", line 76, in inner_send
    await send(message)
  File "/home/ftuser/.local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 494, in send
    output = self.conn.send(event)
  File "/home/ftuser/.local/lib/python3.10/site-packages/h11/_connection.py", line 512, in send
    data_list = self.send_with_data_passthrough(event)
  File "/home/ftuser/.local/lib/python3.10/site-packages/h11/_connection.py", line 537, in send_with_data_passthrough
    self._process_event(self.our_role, event)
  File "/home/ftuser/.local/lib/python3.10/site-packages/h11/_connection.py", line 272, in _process_event
    self._cstate.process_event(role, type(event), server_switch_event)
  File "/home/ftuser/.local/lib/python3.10/site-packages/h11/_state.py", line 293, in process_event
    self._fire_event_triggered_transitions(role, _event_type)
  File "/home/ftuser/.local/lib/python3.10/site-packages/h11/_state.py", line 311, in _fire_event_triggered_transitions
    raise LocalProtocolError(
h11._util.LocalProtocolError: can't handle event type Response when role=SERVER and state=MUST_CLOSE
2022-12-16 06:49:53 - uvicorn.error - WARNING - Invalid HTTP request received.

**Comment by xmatthias** [comment]
Based on the error it's clear that you have the webserver enabled.

Depending on the configuration used, it'll either be reachable from your system, or from other systems in your network (or from the internet - in case this is a VPS with "listen_ip"="0.0.0.0.".

This error simply means that "something" connected to the port used using a non-http protocol.
Most likely, you can get around this by changing the "listen_port" to something unused (maybe 18080 or similar) - so you'll not have anything else trying to connect to it.

There's nothing freqtrade can do against this - as in the end, it's an invalid request on a listening port - that's however triggered from something external.
It's also not "really" a problem other than causing log noise.

At any rate, we do recommend to not expose freqtrade directly on the internet - but protect it at the network level by either a VPN, wireguard network, or connect to it via an SSH tunnel.

**Comment by arielcortez** [comment]
yeah you are right. i'm running this on a VPS. will look into it. thanks on your suggestion and quick reply

**Comment by valentinac** [comment]
I had the same problem. These exceptions usually occur with freqUI access, although it does not affect the operation of the program, but it looks bad, search for many similar problems found that it seems to be the problem of the webui, that is, the browser side, if you use chrome, then the problem will not appear after switching to safari, please refer to.
