### ISSUE TITLE
stoploss_on_exchange broken in 2022.11

### ISSUE THREAD

**Issue by mciepluc** [freqtrade/freqtrade#7927]
## Describe your environment

  * Operating system: Ubuntu 22.04
  * Python Version: 3.10
  * CCXT version: 2.1.96
  * Freqtrade Version: 2022.11
  

## Describe the problem:

After update to version 2022.11 stop loss order cannot be placed on Binance. Everything works well on version 2022.10. 
To reproduce this, you need to have an order filled and stop loss on exchange to be placed.
The following error is reported:

```
Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/exchange.py", line 1174, in stoploss
    order = self._api.create_order(symbol=pair, type=ordertype, side=side,
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/binance.py", line 2997, in create_order
    response = getattr(self, method)(self.extend(request, requestParams))
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 500, in inner
    return entry(_self, **inner_kwargs)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/binance.py", line 5586, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2625, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 636, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/binance.py", line 5564, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2898, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.BadRequest: binance {"code":-1106,"msg":"Parameter 'stopPrice' sent when not required."}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/freqtradebot.py", line 1080, in create_stoploss_order
    stoploss_order = self.exchange.stoploss(
  File "/freqtrade/freqtrade/exchange/common.py", line 179, in wrapper
    raise ex
  File "/freqtrade/freqtrade/exchange/common.py", line 164, in wrapper
    return f(*args, **kwargs)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 1196, in stoploss
    raise TemporaryError(
freqtrade.exceptions.TemporaryError: Could not place stoploss order due to BadRequest. Message: binance {"code":-1106,"msg":"Parameter 'stopPrice' sent when not required."}
```

**Comment by xmatthias** [comment]
This is missing some info to actually start to look at it.

what market are you operating in (spot, futures)
what type of stoploss order has been selected

**Comment by mciepluc** [comment]
This is the futures market, and used is custom_stoploss.

**Comment by mciepluc** [comment]
(stoploss order_type is "market")

**Comment by xmatthias** [comment]
Unfortunately, debugging on binance futures is currently difficult due to them having banned big parts of the world from trading futures - so this might be a slow moving issue with a lot of activities on your side (sorry - can't debug what i can't run).

Can you try the following 2 things:
* update ccxt to the latest version (`pip install -U ccxt`)
* use stoploss_type limit

And report on your findings?

**Comment by xmatthias** [comment]
This will work now in the latest develop (pushed just now).

It's also fixed in the very last ccxt version - but their CI is currently still failing - but it'll work once they push a version > 2.4.55, too.
