### ISSUE TITLE
error during start up on volume pairlist 

### ISSUE THREAD

**Issue by gorax19** [freqtrade/freqtrade#7947]
## Describe your environment

  * Operating system: ____ linux docker 
  * Python Version: _____ python:3.10.7
  * CCXT version: _____ CCXT 2.4.27
  * Freqtrade Version: ____ freqtrade 2022.12.dev
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

the bot can no longer load crypto data, the bot even goes off

when I restart the docker instance everything works normally again

### Relevant code exceptions or logs

```
2022-12-23 02:39:07 - freqtrade - INFO - freqtrade 2022.12.dev
2022-12-23 02:39:07 - freqtrade.worker - INFO - Starting worker 2022.12.dev
2022-12-23 02:39:07 - freqtrade.configuration.load_config - INFO - Using config: config.json ...
2022-12-23 02:39:07 - freqtrade.loggers - INFO - Verbosity set to 0
2022-12-23 02:39:07 - freqtrade.configuration.configuration - INFO - Runmode set to live.
2022-12-23 02:39:07 - freqtrade.configuration.configuration - INFO - Using additional Strategy lookup path: /freqtrade/user_data/strategy/live
2022-12-23 02:39:07 - freqtrade.configuration.configuration - INFO - Parameter --db-url detected ...
2022-12-23 02:39:07 - freqtrade.configuration.configuration - INFO - Dry run is disabled
2022-12-23 02:39:07 - freqtrade.configuration.configuration - INFO - Using DB: "postgresql+psycopg2://trading:*****@ha_db_db_proxy:5432/gorax_futures_followthemingorax_15m_usdt_binance"
2022-12-23 02:39:07 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 3 ...
2022-12-23 02:39:07 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2022-12-23 02:39:07 - freqtrade.configuration.directory_operations - INFO - Created data directory: None
2022-12-23 02:39:07 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/binance ...
2022-12-23 02:39:07 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2022-12-23 02:39:07 - freqtrade.exchange.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2022-12-23 02:39:07 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2022-12-23 02:39:07 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy FollowTheMinGorax from '/freqtrade/user_data/strategy/live/FollowTheMinGorax.py'...
2022-12-23 02:39:07 - freqtrade.strategy.hyper - INFO - Found no parameter file.
2022-12-23 02:39:07 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 15m.
2022-12-23 02:39:07 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'process_only_new_candles' with value in config file: True.
2022-12-23 02:39:07 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'order_types' with value in config file: {'entry': 'market', 'exit': 'market', 'stoploss': 'limit', 'force_exit': 'market', 'stoploss_on_exchange': True}.
2022-12-23 02:39:07 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'order_time_in_force' with value in config file: {'entry': 'gtc', 'exit': 'gtc'}.
2022-12-23 02:39:07 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2022-12-23 02:39:07 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 550.
2022-12-23 02:39:07 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'entry': 15, 'exit': 15}.
2022-12-23 02:39:07 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 100}
2022-12-23 02:39:07 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 15m
2022-12-23 02:39:07 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.8
2022-12-23 02:39:07 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2022-12-23 02:39:07 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2022-12-23 02:39:07 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2022-12-23 02:39:07 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2022-12-23 02:39:07 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: True
2022-12-23 02:39:07 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'entry': 'market', 'exit': 'market', 'stoploss': 'limit', 'force_exit': 'market', 'stoploss_on_exchange': True}
2022-12-23 02:39:07 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'entry': 'gtc', 'exit': 'gtc'}
2022-12-23 02:39:07 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2022-12-23 02:39:07 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 550
2022-12-23 02:39:07 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2022-12-23 02:39:07 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 200
2022-12-23 02:39:07 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'entry': 15, 'exit': 15}
2022-12-23 02:39:07 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_exit_signal: True
2022-12-23 02:39:07 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_only: False
2022-12-23 02:39:07 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_entry_signal: False
2022-12-23 02:39:07 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_offset: 0.0
2022-12-23 02:39:07 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2022-12-23 02:39:07 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2022-12-23 02:39:07 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: False
2022-12-23 02:39:07 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1
2022-12-23 02:39:07 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2022-12-23 02:39:07 - freqtrade.exchange.exchange - INFO - Using CCXT 2.4.27
2022-12-23 02:39:07 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'future'}, 'enableRateLimit': False, 'urls': {'api': {'public': 'http://binance_proxy:8090/api/v3', 'private': 'http://binance_proxy:8090/api/v3', 'sapi': 'http://binance_proxy:8090/sapi/v1', 'fapiPublic': 'http://binance_proxy:8091/fapi/v1', 'fapiPrivate': 'http://exchange_proxy/fapi/v1', 'fapiPrivateV2': 'http://exchange_proxy/fapi/v2'}}}
2022-12-23 02:39:07 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'future'}, 'enableRateLimit': False, 'urls': {'api': {'public': 'http://binance_proxy:8090/api/v3', 'private': 'http://binance_proxy:8090/api/v3', 'sapi': 'http://binance_proxy:8090/sapi/v1', 'fapiPublic': 'http://binance_proxy:8091/fapi/v1', 'fapiPrivate': 'http://exchange_proxy/fapi/v1', 'fapiPrivateV2': 'http://exchange_proxy/fapi/v2'}}, 'aiohttp_trust_env': False, 'rateLimit': 1000}
2022-12-23 02:39:07 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2022-12-23 02:39:10 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2022-12-23 02:39:15 - freqtrade.wallets - INFO - Wallets synced.
2022-12-23 02:39:15 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist VolumePairList from '/freqtrade/freqtrade/plugins/pairlist/VolumePairList.py'...
2022-12-23 02:39:15 - freqtrade.rpc.rpc_manager - INFO - Enabling rpc.api_server
2022-12-23 02:39:16 - freqtrade.rpc.api_server.webserver - INFO - Starting HTTP Server at 0.0.0.0:8080
2022-12-23 02:39:16 - freqtrade.rpc.api_server.webserver - WARNING - SECURITY WARNING - Local Rest Server listening to external connections
2022-12-23 02:39:16 - freqtrade.rpc.api_server.webserver - WARNING - SECURITY WARNING - This is insecure please set to your loopback,e.g 127.0.0.1 in config.json
2022-12-23 02:39:16 - freqtrade.rpc.api_server.webserver - INFO - Starting Local Rest Server.
2022-12-23 02:39:16 - uvicorn.error - INFO - Started server process [1]
2022-12-23 02:39:16 - uvicorn.error - INFO - Waiting for application startup.
2022-12-23 02:39:16 - uvicorn.error - INFO - Application startup complete.
2022-12-23 02:39:16 - uvicorn.error - INFO - Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
2022-12-23 02:39:16 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist VolumePairList from '/freqtrade/freqtrade/plugins/pairlist/VolumePairList.py'...
2022-12-23 02:39:16 - VolumePairList - INFO - Pair GAL/USDT in your blacklist. Removing it from whitelist...
2022-12-23 02:39:16 - VolumePairList - INFO - Pair BTCUSDT_221230 in your blacklist. Removing it from whitelist...
2022-12-23 02:39:16 - VolumePairList - INFO - Pair ETHUSDT_221230 in your blacklist. Removing it from whitelist...
2022-12-23 02:39:16 - VolumePairList - INFO - Pair ETHUSDT_230331 in your blacklist. Removing it from whitelist...
2022-12-23 02:39:16 - VolumePairList - INFO - Pair BTCUSDT_230331 in your blacklist. Removing it from whitelist...
2022-12-23 02:39:16 - freqtrade.commands.trade_commands - ERROR - 'quoteVolume'
```

**Comment by xmatthias** [comment]
that error is ... inconclusive at best.

it's clearly missing a stacktrace, - which should be comming either before or after the error.

simply `'quoteVolume'` doesn't make sense as error - an dis not an error i'd know how to produce.
Are you sure there is nothing before/after the last line - like a stacktrace that can give us some more hints?

**Comment by gorax19** [comment]
hey ! i ve this after 
```
2022-12-23 02:39:16 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/freqtrade/freqtrade/worker.py", line 37, in __init__
    self._init(False)
  File "/freqtrade/freqtrade/worker.py", line 53, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/freqtrade/freqtrade/freqtradebot.py", line 103, in __init__
    self.active_pair_whitelist = self._refresh_active_whitelist()
  File "/freqtrade/freqtrade/freqtradebot.py", line 275, in _refresh_active_whitelist
    self.pairlists.refresh_pairlist()
  File "/freqtrade/freqtrade/plugins/pairlistmanager.py", line 100, in refresh_pairlist
    pairlist = self._pairlist_handlers[0].gen_pairlist(tickers)
  File "/freqtrade/freqtrade/plugins/pairlist/VolumePairList.py", line 135, in gen_pairlist
    filtered_tickers = [
  File "/freqtrade/freqtrade/plugins/pairlist/VolumePairList.py", line 138, in <listcomp>
    and (self._use_range or v[self._sort_key] is not None)
KeyError: 'quoteVolume'
2022-12-23 11:29:07 - uvicorn.error - INFO - ('10.0.0.2', 61150) - "WebSocket /api/v1/message/ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGVudGl0eSI6eyJ1IjoiZ29yYXgifSwiZXhwIjoxNjcxNzk1ODQ2LCJpYXQiOjE2NzE3OTQ5NDYsInR5cGUiOiJhY2Nlc3MifQ.alEHEEO_j-BnNyLoFGwWcvLsAfh7gTN2zQNDnxV-lSU" [accepted]
2022-12-23 11:29:07 - freqtrade.rpc.api_server.ws.channel - INFO - Connected to channel - WebSocketChannel(04451a96, ('10.0.0.2', 61150))
2022-12-23 11:29:07 - uvicorn.error - INFO - connection open
2022-12-23 11:29:10 - freqtrade.wallets - INFO - Wallets synced.
```

**Comment by xmatthias** [comment]
seems like the input data is invalid (doesn't contain quoteVolume).

that's actually not supposed to happen  - but it's also something we can easily protect against.
