### ISSUE TITLE
451 Client Error. Unable to initialize markets.

### ISSUE THREAD

**Issue by zois** [freqtrade/freqtrade#7955]
## Describe your environment

  * Operating system:  Debian GNU/Linux 11 (bullseye) | Kernel: Linux 5.10.0-20-cloud-amd64 | Architecture: x86-64
  * Python Version: Python 3.9.2
  * CCXT version: ccxt==2.1.96
  * Freqtrade Version: freqtrade 2022.11
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

I am running freqtrade in **google cloud** for many months now without any issue. I am using **Binance** as an exchange. 
Today and probably the previous days I am getting a **451 error (451 Unavailable For Legal Reasons)**. I have created new API keys to try to resolve it - and even used a whitelisted IP - but with no luck. Is this something new with Binance and preventing usage from Cloud? Is it probably a prevention from Google Cloud itself?

```
2022-12-29 11:51:17,994 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1
2022-12-29 11:51:17,994 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2022-12-29 11:51:17,999 - freqtrade.exchange.exchange - INFO - Using CCXT 2.1.96
2022-12-29 11:51:18,000 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2022-12-29 11:51:18,011 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 100}
2022-12-29 11:51:18,022 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2022-12-29 11:51:18,110 - freqtrade.exchange.exchange - ERROR - Unable to initialize markets.
Traceback (most recent call last):
  File "/home/pkrmcl/freqtrade/.env/lib/python3.9/site-packages/ccxt/base/exchange.py", line 620, in fetch
    response.raise_for_status()
  File "/home/pkrmcl/freqtrade/.env/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 451 Client Error:  for url: https://api.binance.com/sapi/v1/capital/config/getall?timestamp=1672314678022&recvWindow=10000&signature=4e2ccbaa82d459aa1b0e217ddd2229c478c8d2b151676e08b5da6dca887682a4

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pkrmcl/freqtrade/freqtrade/exchange/exchange.py", line 486, in _load_markets
    self._markets = self._api.load_markets()
  File "/home/pkrmcl/freqtrade/.env/lib/python3.9/site-packages/ccxt/base/exchange.py", line 1430, in load_markets
    currencies = self.fetch_currencies()
  File "/home/pkrmcl/freqtrade/.env/lib/python3.9/site-packages/ccxt/binance.py", line 1329, in fetch_currencies
    response = self.sapiGetCapitalConfigGetall(params)
  File "/home/pkrmcl/freqtrade/.env/lib/python3.9/site-packages/ccxt/base/exchange.py", line 500, in inner
    return entry(_self, **inner_kwargs)
  File "/home/pkrmcl/freqtrade/.env/lib/python3.9/site-packages/ccxt/binance.py", line 5586, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/pkrmcl/freqtrade/.env/lib/python3.9/site-packages/ccxt/base/exchange.py", line 2625, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/pkrmcl/freqtrade/.env/lib/python3.9/site-packages/ccxt/base/exchange.py", line 639, in fetch
    raise ExchangeError(details) from e
ccxt.base.errors.ExchangeError: binance GET https://api.binance.com/sapi/v1/capital/config/getall?timestamp=1672314678022&recvWindow=10000&signature=4e2ccbaa82d459aa1b0e217ddd2229c478c8d2b151676e08b5da6dca887682a4
2022-12-29 11:51:18,115 - freqtrade.commands.trade_commands - ERROR - Could not load markets, therefore cannot start. Please investigate the above error for more details.
2022-12-29 11:51:18,115 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/pkrmcl/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/home/pkrmcl/freqtrade/freqtrade/worker.py", line 37, in __init__
    self._init(False)
  File "/home/pkrmcl/freqtrade/freqtrade/worker.py", line 53, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/home/pkrmcl/freqtrade/freqtrade/freqtradebot.py", line 67, in __init__
    self.exchange = ExchangeResolver.load_exchange(
  File "/home/pkrmcl/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 34, in load_exchange
    exchange = ExchangeResolver._load_exchange(
  File "/home/pkrmcl/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 60, in _load_exchange
    exchange = ex_class(**kwargs)
  File "/home/pkrmcl/freqtrade/freqtrade/exchange/exchange.py", line 188, in __init__
    self.validate_config(config)
  File "/home/pkrmcl/freqtrade/freqtrade/exchange/exchange.py", line 219, in validate_config
    self.validate_stakecurrency(config['stake_currency'])
  File "/home/pkrmcl/freqtrade/freqtrade/exchange/exchange.py", line 521, in validate_stakecurrency
    raise OperationalException(
freqtrade.exceptions.OperationalException: Could not load markets, therefore cannot start. Please investigate the above error for more details.
```

My config file is:
```
{
	"max_open_trades": 6,
	"stake_currency": "USDT",
	"stake_amount": "unlimited",
	"tradable_balance_ratio": 0.99,
	"fiat_display_currency": "USD",
	"timeframe": "5m",
	"dry_run": false,
	"dry_run_wallet": 1000,
	"cancel_open_orders_on_exit": false,
	"unfilledtimeout": {
		"entry": 15,
		"exit": 15,
		"exit_timeout_count": 0,
		"unit": "minutes"
	},
	"order_types": {
		"entry": "limit",
		"exit": "limit",
		"emergency_exit": "limit",
		"force_entry": "limit",
		"force_exit": "limit",
		"stoploss": "limit",
		"stoploss_on_exchange": false,
		"stoploss_on_exchange_interval": 60
	},
	"entry_pricing": {
		"price_side": "other",
		"use_order_book": false,
		"order_book_top": 1,
		"price_last_balance": 0.0,
		"check_depth_of_market": { "enabled": false, "bids_to_ask_delta": 1 }
	},
	"exit_pricing": {
		"price_side": "other",
		"use_order_book": false,
		"order_book_top": 1,
		"price_last_balance": 0.0
	},
	"exchange": {
		"name": "binance",
		"key": "***",
		"secret": "***",
		"ccxt_config": { "enableRateLimit": true },
		"ccxt_async_config": {
			"enableRateLimit": true,
			"rateLimit": 100
		},
		"pair_whitelist": [],
		"pair_blacklist": [
			"(BNB)/.*",
			".*(_PREMIUM|BEAR|BULL|HALF|HEDGE|UP|DOWN|[1235][SL])/.*",
			"(AUD|BRZ|CAD|CHF|EUR|GBP|HKD|IDRT|JPY|NGN|RUB|SGD|TRY|UAH|USD|ZAR)/.*",
			"(BUSD|CUSD|CUSDT|DAI|PAXG|SUSD|TUSD|USDC|USDN|USDP|USDT|VAI|UST|USTC|AUSD)/.*",
			"(ACM|AFA|ALA|ALL|APL|ASR|ATM|BAR|CAI|CITY|FOR|GAL|GOZ|IBFK|JUV|LEG|LOCK-1|NAVI|NMR|NOV|PFL|PORTO|PSG|ROUSH|STV|TH|TRA|UCH|UFC|YBO)/.*",
			"(1EARTH|ILA|BOBA|CTXC|CWAR|HBAR|NMR|OMG|ONG|ARDR|DMTR|MLS|TORN)/.*"
		]
	},
	"pairlists": [
		{
			"method": "VolumePairList",
			"number_assets": 40,
			"sort_key": "quoteVolume",
			"refresh_period": 1800
		},
		{ "method": "AgeFilter", "min_days_listed": 30 },
		{
			"method": "RangeStabilityFilter",
			"lookback_days": 3,
			"min_rate_of_change": 0.03,
			"refresh_period": 1800
		},
		{
			"method": "VolatilityFilter",
			"lookback_days": 3,
			"min_volatility": 0.01,
			"max_volatility": 0.75,
			"refresh_period": 43200
		},
		{
			"method": "VolumePairList",
			"number_assets": 70,
			"sort_key": "quoteVolume"
		},
		{ "method": "ShuffleFilter" }
	],
	"edge": {
		"enabled": false,
		"process_throttle_secs": 3600,
		"calculate_since_number_of_days": 7,
		"allowed_risk": 0.01,
		"stoploss_range_min": -0.01,
		"stoploss_range_max": -0.1,
		"stoploss_range_step": -0.01,
		"minimum_winrate": 0.6,
		"minimum_expectancy": 0.2,
		"min_trade_number": 10,
		"max_trade_duration_minute": 1440,
		"remove_pumps": false
	},
	"telegram": {
		"enabled": true,
		"token": "***",
		"chat_id": "***"
	},
	"api_server": {
		"enabled": false,
		"listen_ip_address": "0.0.0.0",
		"listen_port": 8080,
		"verbosity": "error",
		"enable_openapi": false,
		"jwt_secret_key": "SECRET",
		"CORS_origins": [],
		"username": "USERNAME",
		"password": "PASSWORD"
	},
	"bot_name": "freqtrade-binance",
	"initial_state": "running",
	"force_entry_enable": true,
	"internals": {
		"process_throttle_secs": 5
	}
}

```
Thank you in advance for your responses.

**Comment by stash86** [comment]
Location of your vps on north america?

**Comment by zois** [comment]
> Location of your vps on north america?

Indeed, 
us-central1-c | Council Bluffs, Iowa, North America

Issues due to the bad weather and the storm?

Thanks

**Comment by stash86** [comment]
Binance recently bans any ip from north america

**Comment by zois** [comment]
> Binance recently bans any ip from north america

Really? Thanks for letting me know, so I can close this issue and try from some other region.
Thank you!

**Comment by xmatthias** [comment]
Unfortunately, that's how it is "nowadays".
we've had to disable parts of CI as well for this - as github actions run in America as well.
