### ISSUE TITLE
ZeroDivisionError when df has no data from the date of backtest timerange

### ISSUE THREAD

**Issue by CryptoRahino** [freqtrade/freqtrade#7980]
## Describe your environment

  * Operating system: ubuntu
  * Python Version: 3.9 (`python -V`)
  * CCXT version: 2.4.60 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2022.12 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

error:
```
2023-01-05 10:19:22,926 - freqtrade.freqai.data_kitchen - INFO - dropped 0 training points due to NaNs in populated dataset 0.
2023-01-05 10:19:22,927 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/opt/freqtrade/freqtrade/main.py", line 42, in main
    return_code = args['func'](args)
  File "/opt/freqtrade/freqtrade/commands/optimize_commands.py", line 58, in start_backtesting
    backtesting.start()
  File "/opt/freqtrade/freqtrade/optimize/backtesting.py", line 1336, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
  File "/opt/freqtrade/freqtrade/optimize/backtesting.py", line 1237, in backtest_one_strategy
    preprocessed = self.strategy.advise_all_indicators(data)
  File "/opt/freqtrade/freqtrade/strategy/interface.py", line 1203, in advise_all_indicators
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "/opt/freqtrade/freqtrade/strategy/interface.py", line 1203, in <dictcomp>
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "/opt/freqtrade/freqtrade/strategy/interface.py", line 1221, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/opt/freqtrade/freqtrade/user_data/strategies/rl_test.py", line 171, in populate_indicators
    dataframe = self.freqai.start(dataframe, metadata, self)
  File "/opt/freqtrade/freqtrade/freqai/freqai_interface.py", line 157, in start
    dk = self.start_backtesting(dataframe, metadata, self.dk)
  File "/opt/freqtrade/freqtrade/freqai/freqai_interface.py", line 315, in start_backtesting
    self.model = self.train(dataframe_train, pair, dk)
  File "/opt/freqtrade/freqtrade/freqai/RL/BaseReinforcementLearningModel.py", line 101, in train
    features_filtered, labels_filtered = dk.filter_features(
  File "/opt/freqtrade/freqtrade/freqai/data_kitchen.py", line 241, in filter_features
    if (1 - len(filtered_df) / len(unfiltered_df)) > 0.1 and self.live:
ZeroDivisionError: division by zero
```

this issue happens when the --timerange starts before the data, as the data doesn't exists `unfiltered_df` is cut and stays empty what causing its `len()` == 0 

although the issue is on the user side too, i'd expect it to cut the df first to be with the available data dates on only then tries to manipulate the df.

### Steps to reproduce:

1. download ALGO data from binance, use timerange 20200101-20220101
2. the data will be recieved, starts from 20200616 
3. run backtest on that data with freqai `backtesting
-c
user_data/config.json
--strategy
rl_test
--timerange
20200101-20221001
--freqaimodel
ReinforcementLearner`
  
### Observed Results:

the error mentioned above of `ZeroDivisionError: division by zero`

**Comment by xmatthias** [comment]
What's in your configuration / pairlist? 
just ALGO, or other pairs as well?

**Comment by CryptoRahino** [comment]
sorry for the late response. this happens with all pairs.

**Comment by robcaulk** [comment]
Currently we don’t have logic to automatically handle hetrerogeneous data (in time).

You are welcome to make a PR to add this. Until then, we expect users to have all data pre downloaded for their backtest. We highlight exactly how to do that in the doc in multiple places.
