### ISSUE TITLE
Permission denied error

### ISSUE THREAD

**Issue by CobraGazes** [freqtrade/freqtrade#7990]
## Describe your environment

  * Operating system: Ubuntu
  * Python Version: 3.10.8 (`python -V`)
  * CCXT version:  2.5.51 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2022.12 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)

Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

I'm getting a permission denied error whenever I try to run/backtest any strategy I have in my strategy's folder. 
I recently tried to use the "GodStra" trading strategy and I was going to backtest it but I kept getting a permission denied error, now anytime I try to run or backtest any strategy I have I get the permission denied error.

The error log is below:

### Steps to reproduce:

  1. I just created a new file in my strategy's folder, named it "GodStra" and pasted the code into it.
  2. then whenever I try to backtest or just run any strategy I'm getting this error and even if i use a different strategy it still says GodStra is denying permission.
  
### Observed Results:

  * I got the error and am now getting it whenever I backtest/attempt to trade anything
  * I expected to have the strategy backtest/start trading

### Relevant code exceptions or logs

  ```
2023-01-08 12:11:09,095 - freqtrade - INFO - freqtrade 2022.12
2023-01-08 12:11:09,223 - freqtrade.worker - INFO - Starting worker 2022.12
2023-01-08 12:11:09,224 - freqtrade.configuration.load_config - INFO - Using config: config.json ...
2023-01-08 12:11:09,225 - freqtrade.loggers - INFO - Verbosity set to 0
2023-01-08 12:11:09,228 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
2023-01-08 12:11:09,228 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2023-01-08 12:11:09,229 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:///tradesv3.dryrun.sqlite"
2023-01-08 12:11:09,229 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 1 ...
2023-01-08 12:11:09,230 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/name/freqtrade/user_data ...
2023-01-08 12:11:09,230 - freqtrade.configuration.configuration - INFO - Using data directory: /home/name/freqtrade/user_data/data/binance ...
2023-01-08 12:11:09,231 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2023-01-08 12:11:09,240 - freqtrade.exchange.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2023-01-08 12:11:09,241 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2023-01-08 12:11:09,242 - freqtrade.commands.trade_commands - ERROR - [Errno 13] Permission denied: '/home/name/freqtrade/user_data/strategies/GodStra.py'
2023-01-08 12:11:09,242 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/name/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/home/name/freqtrade/freqtrade/worker.py", line 37, in __init__
    self._init(False)
  File "/home/name/freqtrade/freqtrade/worker.py", line 53, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/home/name/freqtrade/freqtrade/freqtradebot.py", line 62, in __init__
    self.strategy: IStrategy = StrategyResolver.load_strategy(self.config)
  File "/home/name/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 48, in load_strategy
    strategy: IStrategy = StrategyResolver._load_strategy(
  File "/home/name/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 256, in _load_strategy
    strategy = StrategyResolver._load_object(
  File "/home/name/freqtrade/freqtrade/resolvers/iresolver.py", line 148, in _load_object
    (module, module_path) = cls._search_object(directory=_path,
  File "/home/name/freqtrade/freqtrade/resolvers/iresolver.py", line 130, in _search_object
    obj = next(cls._get_valid_object(module_path, object_name), None)
  File "/home/name/freqtrade/freqtrade/resolvers/iresolver.py", line 91, in _get_valid_object
    spec.loader.exec_module(module)  # type: ignore # importlib does not use typehints
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 980, in get_code
  File "<frozen importlib._bootstrap_external>", line 1037, in get_data
PermissionError: [Errno 13] Permission denied: '/home/name/freqtrade/user_data/strategies/GodStra.py'  ```

**Comment by xmatthias** [comment]
it most likely is what it says - a permission error.
This can happen if different users are used (for example, checkout with root, running as some other user, ...).

what does `ls -l user_data/strategies` and `ls -l user_data/` show? (Please the full output).
Also, what's the user you're running freqtrade as?

**Comment by CobraGazes** [comment]
when I run `ls -l user_data/strategies` this is what I get:

```
total 28                                                                                                                 
---------- 1 MyName MyName  6978 Jan  8 14:34 GodStra                                                                    
drwxr-xr-x 1 MyName MyName   512 Jan  8 14:12 __pycache__                                                                 
-rw-r--r-- 1 MyName MyName 16695 Jan  8 14:12 sample_strategy.py
```                                        

And if your asking if I'm using Root then no I'm not. I'm just running it in my home directory.

**Comment by xmatthias** [comment]
> `---------- 1 MyName MyName  6978 Jan  8 14:34 GodStra  `

your strategy file has "no" permissions (nobody can read it - not even yourself).
if you run `cat user_data/strategies/GodStra.py`, you'll get exactly the same error.

you should be able to fix this with `chmod u+rw user_data/strategies/GodStra.py` - which should give you read/write permissions to that file again (if that doesn't change the `---` to `-rw-r--r--` or fails - prefix with sudo)

Now how you got to this is beyond me - nothing in freqtrade would modify permissions (not in this way, anyway) - and more importantly, not on just one file.

**Comment by CobraGazes** [comment]
This fixed it, thanks for the help!
