### ISSUE TITLE
Kraken Invalid Order looks like invalid order_id format

### ISSUE THREAD

**Issue by pr0vieh** [freqtrade/freqtrade#8006]
## Describe your environment

  * Operating system: Ubuntu 22.04
  * Python Version: 3.10.6 (`python -V`)
  * CCXT version: 2.5.56 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2023.1.dev-00dbc195a (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:
Kraken say Invalid order!

Error updating Order ['OHF36Q-XQSB6-UIBS3Q'] due to Tried to get an invalid order (pair: ALGO/BTC id: ['OHF36Q-XQSB6-UIBS3Q']). Message: kraken {"error":["EOrder:Invalid order"]}.

### Steps to reproduce:

  1. Use Kraken Exchange
  2. do an Order
  3. at filled Order or Cancel try -> see the Stack Trace
  
### Observed Results:

order_id in database looks different then Trades before

![2023-01-11 20_53_36-DBeaver 22 0 4 - orders](https://user-images.githubusercontent.com/61424/211905561-06a61019-ad64-429e-9f9b-5bd9ff760c86.png)

the Invalid order Problem lead to an Crash because missing Numbers in Database

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
2023-01-11 19:59:34,648 - freqtrade.commands.trade_commands - ERROR - must be real number, not NoneType
2023-01-11 19:59:34,648 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/root/freqtrade/freqtrade/exchange/exchange.py", line 1207, in fetch_order
    order = self._api.fetch_order(order_id, pair, params=params)
  File "/root/freqtrade/.env/lib/python3.10/site-packages/ccxt/kraken.py", line 1499, in fetch_order
    response = self.privatePostQueryOrders(self.extend(request, query))
  File "/root/freqtrade/.env/lib/python3.10/site-packages/ccxt/base/exchange.py", line 502, in inner
    return entry(_self, **inner_kwargs)
  File "/root/freqtrade/.env/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2813, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "/root/freqtrade/.env/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2810, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/root/freqtrade/.env/lib/python3.10/site-packages/ccxt/base/exchange.py", line 664, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/root/freqtrade/.env/lib/python3.10/site-packages/ccxt/kraken.py", line 2294, in handle_errors
    raise InvalidOrder(self.id + ' ' + body)
ccxt.base.errors.InvalidOrder: kraken {"error":["EOrder:Invalid order"]}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/freqtrade/freqtrade/freqtradebot.py", line 342, in startup_update_open_orders
    fo = self.exchange.fetch_order_or_stoploss_order(order.order_id, order.ft_pair,
  File "/root/freqtrade/freqtrade/exchange/exchange.py", line 1239, in fetch_order_or_stoploss_order
    return self.fetch_order(order_id, pair)
  File "/root/freqtrade/freqtrade/exchange/common.py", line 164, in wrapper
    return f(*args, **kwargs)
  File "/root/freqtrade/freqtrade/exchange/exchange.py", line 1215, in fetch_order
    raise InvalidOrderException(
freqtrade.exceptions.InvalidOrderException: Tried to get an invalid order (pair: ALGO/BTC id: ['OHF36Q-XQSB6-UIBS3Q']). Message: kraken {"error":["EOrder:Invalid order"]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker.run()
  File "/root/freqtrade/freqtrade/worker.py", line 75, in run
    state = self._worker(old_state=state)
  File "/root/freqtrade/freqtrade/worker.py", line 96, in _worker
    self.freqtrade.startup()
  File "/root/freqtrade/freqtrade/freqtradebot.py", line 189, in startup
    self.startup_update_open_orders()
  File "/root/freqtrade/freqtrade/freqtradebot.py", line 355, in startup_update_open_orders
    self.handle_timedout_order(fo, order.trade)
  File "/root/freqtrade/freqtrade/freqtradebot.py", line 1265, in handle_timedout_order
    self.handle_cancel_enter(trade, order, constants.CANCEL_REASON['TIMEOUT'])
  File "/root/freqtrade/freqtrade/freqtradebot.py", line 1391, in handle_cancel_enter
    if isclose(filled_amount, 0.0, abs_tol=constants.MATH_CLOSE_PREC):
TypeError: must be real number, not NoneType

  ```

**Comment by xmatthias** [comment]
well the moment you have it in your database - it's pretty clear what's happening.

The interesting part is how that got there. 
if you have logs from that (basically either a working fetch-order - or the create-order command) - ideally with `log_response=True` - then that'd be great as it'd provide us with precise details on what happened.

**Comment by pr0vieh** [comment]
After fixing the DB issues
the Order is found but i got an:
WARNING - Got different open_order_id ['OHF36Q-XQSB6-UIBS3Q'] != OHF36Q-XQSB6-UIBS3Q

looks like an API Output and/or CXX output problem correct ?

**Comment by xmatthias** [comment]
> looks like an API Output and/or CXX output problem correct ?

it looks like that at first glance (we didn't change anything in this area in ages, too) - log_responses=true will tell for sure, as that'll log the response we get from ccxt.

**Comment by pr0vieh** [comment]
this got broken again after fixing the we can see the ccxt

the new id looks like an array instead of a string
```
Old Order: 
2023-01-11 20:55:22,622 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=542, pair=SNX/BTC, amount=3.55660936, is_short=False, leverage=1.0, open_rate=0.00016870, open_since=2022-08-30 00:39:59)
2023-01-11 20:55:39,134 - freqtrade.exchange.exchange - INFO - API fetch_order: {'info': {'id': 'OB2GVX-FX2OU-5OUKRC', 'refid': None, 'userref': '0', 'status': 'open', 'opentm': '1665541706.1449606', 'starttm': '0', 'expiretm': '0', 'descr': {'pair': 'XLMXBT', 'type': 'sell', 'ordertype': 'stop-loss-limit', 'price': '0.00000007', 'price2': '0.00000007', 'leverage': 'none', 'order': 'sell 98.84678747 XLMXBT @ stop loss 0.00000007 -> limit 0.00000007', 'close': ''}, 'vol': '98.84678747', 'vol_exec': '0.00000000', 'cost': '0.000000000', 'fee': '0.000000000', 'price': '0.000000000', 'stopprice': '0.000000000', 'limitprice': '0.000000000', 'misc': '', 'oflags': 'fciq', 'reason': None}, 'id': 'OB2GVX-FX2OU-5OUKRC', 'clientOrderId': '0', 'timestamp': 1665541706144, 'datetime': '2022-10-12T02:28:26.144Z', 'lastTradeTimestamp': None, 'status': 'open', 'symbol': 'XLM/BTC', 'type': 'stop-loss-limit', 'timeInForce': None, 'postOnly': None, 'side': 'sell', 'price': 7e-08, 'stopPrice': 0.0, 'triggerPrice': 0.0, 'cost': 0.0, 'amount': 98.84678747, 'filled': 0.0, 'average': None, 'remaining': 98.84678747, 'fee': {'cost': 0.0, 'rate': None, 'currency': 'BTC'}, 'trades': [], 'fees': [{'cost': 0.0, 'rate': None, 'currency': 'BTC'}]}
2023-01-11 20:55:39,136 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=589, pair=XLM/BTC, amount=98.84678747, is_short=False, leverage=1.0, open_rate=0.00000607, open_since=2022-10-12 02:00:17)

New Order: 
2023-01-11 20:55:55,659 - freqtrade.exchange.exchange - INFO - API fetch_order: {'info': {'id': 'OHF36Q-XQSB6-UIBS3Q', 'refid': None, 'userref': '0', 'status': 'closed', 'opentm': '1673449024.4319403', 'starttm': '0', 'expiretm': '0', 'descr': {'pair': 'ALGOXBT', 'type': 'buy', 'ordertype': 'limit', 'price': '0.00001143', 'price2': '0', 'leverage': 'none', 'order': 'buy 52.49343832 ALGOXBT @ limit 0.00001143', 'close': ''}, 'vol': '52.49343832', 'vol_exec': '52.49343832', 'cost': '0.000600000', 'fee': '0.000000960', 'price': '0.00001143', 'stopprice': '0.000000000', 'limitprice': '0.000000000', 'misc': '', 'oflags': 'fciq', 'trades': ['T2JTIJ-24R3L-GPJ55X'], 'reason': None, 'closetm': '1673450720.6763036'}, 'id': 'OHF36Q-XQSB6-UIBS3Q', 'clientOrderId': '0', 'timestamp': 1673449024431, 'datetime': '2023-01-11T14:57:04.431Z', 'lastTradeTimestamp': None, 'status': 'closed', 'symbol': 'ALGO/BTC', 'type': 'limit', 'timeInForce': None, 'postOnly': None, 'side': 'buy', 'price': 1.143e-05, 'stopPrice': 0.0, 'triggerPrice': 0.0, 'cost': 0.0005999999999976, 'amount': 52.49343832, 'filled': 52.49343832, 'average': 1.143e-05, 'remaining': 0.0, 'fee': {'cost': 9.6e-07, 'rate': None, 'currency': 'BTC'}, 'trades': [{'id': 'T2JTIJ-24R3L-GPJ55X', 'order': None, 'info': 'T2JTIJ-24R3L-GPJ55X', 'timestamp': None, 'datetime': None, 'symbol': 'ALGO/BTC', 'type': None, 'side': None, 'takerOrMaker': None, 'price': None, 'amount': None, 'cost': None, 'fee': {'cost': None}, 'fees': []}], 'fees': [{'cost': 9.6e-07, 'rate': None, 'currency': 'BTC'}]}
2023-01-11 20:55:55,664 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=610, pair=ALGO/BTC, amount=52.49343832, is_short=False, leverage=1.0, open_rate=0.00001143, open_since=2023-01-11 14:57:04)
2023-01-11 20:55:55,672 - freqtrade.freqtradebot - INFO - Fee for Trade Trade(id=610, pair=ALGO/BTC, amount=52.49343832, is_short=False, leverage=1.0, open_rate=0.00001143, open_since=2023-01-11 14:57:04) [buy]: 9.6e-07 BTC - rate: 0.0016
2023-01-11 20:55:55,673 - freqtrade.persistence.trade_model - INFO - Updating trade (id=610) ...
2023-01-11 20:55:55,673 - freqtrade.persistence.trade_model - INFO - LIMIT_BUY has been fulfilled for Trade(id=610, pair=ALGO/BTC, amount=52.49343832, is_short=False, leverage=1.0, open_rate=0.00001143, open_since=2023-01-11 14:57:04).
2023-01-11 20:55:55,673 - freqtrade.persistence.trade_model - WARNING - Got different open_order_id ['OHF36Q-XQSB6-UIBS3Q'] != OHF36Q-XQSB6-UIBS3Q
```

**Comment by xmatthias** [comment]
what's "old and new" ? is that different versions of ccxt/freqtrade?


Interestingly - the responses don't "really" differ once you forma them.

neither is an array though - at least not from the "fetch_api_order" ...

**Comment by pr0vieh** [comment]
yes after Upgrading freqtrade

**Comment by xmatthias** [comment]
which version was the log for "old" generated with?

**Comment by pr0vieh** [comment]
i have Upgraded from e686faf1b..f677dea6a it wars running a while ;)

**Comment by xmatthias** [comment]
is that trade above one of the ones you modified manually?
if you do so - you'll also need to modify the open_order_id in the trades table (not just the orders table).

i'm currently unable to recreate this with clean / fresh trades - which makes it a little difficult.
Unfortunately, the version jump is quite large. Have the "wrong" orders been created by the new version? or have they been there before, and just look differently now?

**Comment by pr0vieh** [comment]
the wrong ids were created with the new freqtrade version
and i see the Problem at "create_order"
is this an API Change ?

```
2023-01-12 00:29:32,371 - freqtrade.exchange.exchange - INFO - API create_order: {'id': "['OBTMB3-QL3C2-6VWDGI']", 'clientOrderId': None, 'info': {'txid': ['OBTMB3-QL3C2-6VWDGI'], 'descr': {'order': 'sell 52.49343832 ALGOXBT @ limit 0.00001163'}}, 'timestamp': None, 'datetime': None, 'lastTradeTimestamp': None, 'status': None, 'symbol': 'ALGO/BTC', 'type': 'limit', 'timeInForce': None, 'postOnly': None, 'side': 'sell', 'price': 1.163e-05, 'stopPrice': None, 'triggerPrice': None, 'cost': None, 'amount': 52.49343832, 'filled': None, 'average': None, 'remaining': None, 'fee': None, 'trades': [], 'fees': []}
```

**Comment by xmatthias** [comment]
you're right - it's a change in ccxt that caused it.

for now, you should be able to work around it by running `pip install ccxt==2.4.20` - which reverts to a still working version.

i've also opened an issue about this on the ccxt repo (https://github.com/ccxt/ccxt/issues/16447).

**Comment by pr0vieh** [comment]
by my luck i trap in a new bug 😄 

i hope i have support you good to find the reason 😄 
currently i try your workaround but i have no new orders...

**Comment by xmatthias** [comment]
you'll have to make sure to first "correct" all open orders in the database. that'll not happen automatically - and needs to be taken care manually - at least for all open orders / trades.

**Comment by pr0vieh** [comment]
the workaround works like a charm!
thx for the fast support

> you'll have to make sure to first "correct" all open orders in the database. that'll not happen automatically - and needs to be taken care manually - at least for all open orders / trades.

for sure 👍
