### ISSUE TITLE
bybit: Multiple errors with the telegram module

### ISSUE THREAD

**Issue by STraderMX** [freqtrade/freqtrade#8010]
## Describe your environment

  * Operating system: linux (Debian 11)
  * Python Version: 3.9.2
  * CCXT version: 2.4.60
  * Freqtrade Version: 2022.12
  
## Describe the problem:

I've detected several problems with telegram, details below.

### This is happening on Bybit

```python
2023-01-13 15:05:01 - freqtrade.freqtradebot - INFO - Exit for ADA/USDT detected. Reason: trailing_stop_loss
2023-01-13 15:05:01 - freqtrade.wallets - INFO - Wallets synced.
2023-01-13 15:05:01 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': exit, 'trade_id': 1, 'exchange': 'Bybit', 'pair': 'ADA/USDT', 'leverage': 1.0, 'direction': 'Long', 'gain': 'profit', 'limit': 0.3358, 'order_rate': 0.3358, 'order_type': 'market', 'amount': 880.12899, 'open_rate': 0.3318, 'close_rate': 0.3358, 'current_rate': 0.3358, 'profit_amount': 2.62858952, 'profit_ratio': 0.00898285, 'buy_tag': 'l3', 'enter_tag': 'l3', 'sell_reason': 'trailing_stop_loss', 'exit_reason': 'trailing_stop_loss', 'open_date': datetime.datetime(2023, 1, 13, 17, 25, 2, 324879), 'close_date': datetime.datetime(2023, 1, 13, 21, 5, 1, 720713), 'stake_amount': 292.33084716, 'stake_currency': 'USDT', 'fiat_currency': 'USD', 'sub_trade': False, 'cumulative_profit': 0.0}
2023-01-13 15:05:02 - freqtrade.wallets - INFO - Wallets synced.
2023-01-13 15:10:01 - freqtrade.worker - INFO - Bot heartbeat. PID=19429, version='2022.12, strategy_version: 1.0', state='RUNNING'
2023-01-13 15:10:01 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=1, pair=ADA/USDT, amount=880.12899000, is_short=False, leverage=1.0, open_rate=0.33180000, open_since=2023-01-13 17:25:02)
2023-01-13 15:10:01 - freqtrade.persistence.trade_model - INFO - Updating trade (id=1) ...
2023-01-13 15:10:01 - freqtrade.persistence.trade_model - INFO - MARKET_SELL has been fulfilled for Trade(id=1, pair=ADA/USDT, amount=880.12899000, is_short=False, leverage=1.0, open_rate=0.33180000, open_since=2023-01-13 17:25:02).
2023-01-13 15:10:01 - freqtrade.persistence.trade_model - INFO - Marking Trade(id=1, pair=ADA/USDT, amount=880.12899000, is_short=False, leverage=1.0, open_rate=0.33180000, open_since=closed) as closed as the trade is fulfilled and found no open orders for it.
2023-01-13 15:10:01 - freqtrade.wallets - INFO - Wallets synced.
2023-01-13 15:10:01 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': exit_fill, 'trade_id': 1, 'exchange': 'Bybit', 'pair': 'ADA/USDT', 'leverage': 1.0, 'direction': 'Long', 'gain': 'profit', 'limit': 0.3358, 'order_rate': 0.3358, 'order_type': '', 'amount': 880.12, 'open_rate': 0.3318, 'close_rate': 0.3358, 'current_rate': None, 'profit_amount': 2.93291189, 'profit_ratio': 0.01003337, 'buy_tag': 'l3', 'enter_tag': 'l3', 'sell_reason': 'trailing_stop_loss', 'exit_reason': 'trailing_stop_loss', 'open_date': datetime.datetime(2023, 1, 13, 17, 25, 2, 324879), 'close_date': datetime.datetime(2023, 1, 13, 21, 10, 1, 749456), 'stake_amount': 292.33084716, 'stake_currency': 'USDT', 'fiat_currency': 'USD', 'sub_trade': True, 'cumulative_profit': 0.0}
2023-01-13 15:11:18 - freqtrade.rpc.telegram - ERROR - Exception occurred within Telegram module
Traceback (most recent call last):
  File "/root/freqtrade/freqtrade/rpc/telegram.py", line 81, in wrapper
    return command_handler(self, *args, **kwargs)
  File "/root/freqtrade/freqtrade/rpc/telegram.py", line 765, in _profit
    stats = self._rpc._rpc_trade_statistics(
  File "/root/freqtrade/freqtrade/rpc/rpc.py", line 449, in _rpc_trade_statistics
    if trade.close_profit >= 0:
TypeError: '>=' not supported between instances of 'NoneType' and 'int'
```

### And this one is happening with multiple exchanges (or all maybe) like Binance, Kucoin, Bybit, OKX

```python
2023-01-13 10:20:02 - freqtrade.rpc.telegram - INFO - Notification 'entry_fill' not sent.
2023-01-13 10:20:42 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-01-13 10:20:42 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/root/freqtrade/.env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 614, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/root/freqtrade/.env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 402, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/root/freqtrade/.env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 398, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/freqtrade/.env/lib/python3.9/site-packages/telegram/utils/request.py", line 259, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "/root/freqtrade/.env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 68, in request
    return self.request_encode_body(method, url, fields=fields,
  File "/root/freqtrade/.env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/root/freqtrade/.env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/root/freqtrade/.env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 665, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "/root/freqtrade/.env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/retry.py", line 347, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/root/freqtrade/.env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/root/freqtrade/.env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 614, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/root/freqtrade/.env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 402, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/root/freqtrade/.env/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 398, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
telegram.vendor.ptb_urllib3.urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/freqtrade/.env/lib/python3.9/site-packages/telegram/ext/updater.py", line 651, in _network_loop_retry
    if not action_cb():
  File "/root/freqtrade/.env/lib/python3.9/site-packages/telegram/ext/updater.py", line 602, in polling_action_cb
    updates = self.bot.get_updates(
  File "/root/freqtrade/.env/lib/python3.9/site-packages/telegram/ext/extbot.py", line 228, in get_updates
    updates = super().get_updates(
  File "/root/freqtrade/.env/lib/python3.9/site-packages/telegram/bot.py", line 134, in decorator
    result = func(*args, **kwargs)
  File "/root/freqtrade/.env/lib/python3.9/site-packages/telegram/bot.py", line 3140, in get_updates
    self._post(
  File "/root/freqtrade/.env/lib/python3.9/site-packages/telegram/bot.py", line 299, in _post
    return self.request.post(
  File "/root/freqtrade/.env/lib/python3.9/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/root/freqtrade/.env/lib/python3.9/site-packages/telegram/utils/request.py", line 265, in _request_wrapper
    raise NetworkError(f'urllib3 HTTPError {error}') from error
telegram.error.NetworkError: urllib3 HTTPError ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```

I hope the information is useful for you!

**Comment by xmatthias** [comment]
Bybit is not a supported exchange at this point.
the cause is (most likely) due to limited response information - which causes a (Temporary) lack in data.

To properly investigate, we'll need more logs (there should be some messages when that particular trade closed - as a closed trade can't / shouldn't have no close-profit assigned).

Without more logs - we'll however only see the effect, but not what's causing this - which makes it non-actionable.

There's also other possibilities (if the database was modified manually) - but for now i'll assume that's not the case.

---

Now the telegram error itself is not an error we can (or will) handle any differently.
As the error says, it's a network error.

That can have multiple causes - none of which freqtrade can control (some you as user can control, others you can't).
 * temporary telegram outage  (most often seen limited to one particular region)
* network problems from the host the bot is running on (wifi, monitored / proxied networks)
* Running in a country where telegram is blocked / attempted to be blocked.

**Comment by STraderMX** [comment]
> Bybit is not a supported exchange at this point. the cause is (most likely) due to limited response information - which causes a (Temporary) lack in data.
> 
> To properly investigate, we'll need more logs (there should be some messages when that particular trade closed - as a closed trade can't / shouldn't have no close-profit assigned).
> 
> Without more logs - we'll however only see the effect, but not what's causing this - which makes it non-actionable.
> 
> There's also other possibilities (if the database was modified manually) - but for now i'll assume that's not the case.
> 

Log error updated in the main post, the problem is that is getting `None` data when expecting a float|int value, I've checked a little bit and maybe I can patch it just casting the value before it's comparison, but of course I'm sure this is not the correct solution.

Apparently Bybit works perfect, I just detected this issue at this point, I mean an issue related only with Bybit.


> Now the telegram error itself is not an error we can (or will) handle any differently. As the error says, it's a network error.
> 
> That can have multiple causes - none of which freqtrade can control (some you as user can control, others you can't).
> 
> * temporary telegram outage  (most often seen limited to one particular region)
> * network problems from the host the bot is running on (wifi, monitored / proxied networks)
> * Running in a country where telegram is blocked / attempted to be blocked.

Ok, I'll investigate more about this.

**Comment by xmatthias** [comment]
The check is there - it's "is_open". Once a trade is closed - close_profit (and close_profit_abs, among others) become mandatory.

The moment the bot closes the trade (`.close()` - is_open is set to False - and `recalc_trade_from_orders()` is called with `is_closing=True` - which will assign `close_profit` - given the exchange provided all necessary info for the order.

As it was a market order, i KNOW that info isn't available (bybit doesn't provide it directly).

Bests try this with the latest develop - i added some more  failsafes to guard around this a few days ago.

**Comment by STraderMX** [comment]
@xmatthias I detected a new bug with the telegram and Bybit, it's impossible to get the open trades status, all the time show "0% profit", check next screenshots.
<img width="319" alt="image" src="https://user-images.githubusercontent.com/122330178/212574869-097af4bd-2052-48ac-ac52-03597172543e.png">
<img width="291" alt="image" src="https://user-images.githubusercontent.com/122330178/212574883-6ccc356f-e213-4e44-8786-a22bde36c107.png">

In this case there is no error in the log, the fact is that its trading perfectly, just a couple of issues with telegram and you could add Bytbit to the fully compatible exchanges (I think).

This is again the status in telegram a couple of minutes before, you can see the problem with the profit but also can see that the "stoploss distance" is different.

<img width="292" alt="image" src="https://user-images.githubusercontent.com/122330178/212575040-0359d262-8d87-42e0-9718-b96eb1f3b518.png">

**Comment by xmatthias** [comment]
well having no profit is not a sign of a compatible exchange.

i suspect it will also mean that ROI / stoploss will not work correctly (just because the distance changes doesn't mean that it'll actually trigger).

we may look at this eventually - but since it's not a supported exchange, it's very low priority - and the solution might be "block this exchange" in the end (depends on the reason for the problems you're seeing).

---

Having an exchange listed as supported doesn't just mean it's compatible (tons more exchages would be compatible) - but also that we have the capacity (and will) to actively support it.

bybit spot will definitely not be added to the supported (or even compatible) exchanges unless they change some things in their API.
they only provide very limited historic data (3500 candles - or ~12 days of 5m data) - which makes backtesting mostly impossible.

**Comment by xmatthias** [comment]
i'd strongly advise you to NOT use bybit with market orders.

responses from bybit in this regard are wrong - so proper functioning cannot be guaranteed.
I've reported that behavior upstream (https://github.com/ccxt/ccxt/issues/16600) - but until that's fixed and tested, please stick to limit orders only when using bybit.

**Comment by willwillis** [comment]
I'm getting all sorts of `TypeError: '>=' not supported between instances of 'NoneType' and 'int'` as well, and I'm using Kucoin. I saw this coming from the UI and Telegram over the past few days. 

```
## Error 1
freqtrade2023  | TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
freqtrade2023  | 2023-01-26 15:35:24,755 - uvicorn.error - ERROR - Exception in ASGI application
freqtrade2023  | Traceback (most recent call last):
freqtrade2023  |   File "/home/ftuser/.local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
freqtrade2023  |     result = await app(  # type: ignore[func-returns-value]
freqtrade2023  |   File "/home/ftuser/.local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
freqtrade2023  |     return await self.app(scope, receive, send)
freqtrade2023  |   File "/home/ftuser/.local/lib/python3.10/site-packages/uvicorn/middleware/message_logger.py", line 86, in __call__
freqtrade2023  |     raise exc from None
freqtrade2023  |   File "/home/ftuser/.local/lib/python3.10/site-packages/uvicorn/middleware/message_logger.py", line 82, in __call__
freqtrade2023  |     await self.app(scope, inner_receive, inner_send)
freqtrade2023  |   File "/home/ftuser/.local/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
freqtrade2023  |     await super().__call__(scope, receive, send)
freqtrade2023  |   File "/home/ftuser/.local/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
freqtrade2023  |     await self.middleware_stack(scope, receive, send)
freqtrade2023  |   File "/home/ftuser/.local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
freqtrade2023  |     raise exc
freqtrade2023  |   File "/home/ftuser/.local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
freqtrade2023  |     await self.app(scope, receive, _send)
freqtrade2023  |   File "/home/ftuser/.local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
freqtrade2023  |     await self.app(scope, receive, send)
freqtrade2023  |   File "/home/ftuser/.local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
freqtrade2023  |     raise exc
freqtrade2023  |   File "/home/ftuser/.local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
freqtrade2023  |     await self.app(scope, receive, sender)
freqtrade2023  |   File "/home/ftuser/.local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
freqtrade2023  |     raise e
freqtrade2023  |   File "/home/ftuser/.local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
freqtrade2023  |     await self.app(scope, receive, send)
freqtrade2023  |   File "/home/ftuser/.local/lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
freqtrade2023  |     await route.handle(scope, receive, send)
freqtrade2023  |   File "/home/ftuser/.local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
freqtrade2023  |     await self.app(scope, receive, send)
freqtrade2023  |   File "/home/ftuser/.local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
freqtrade2023  |     response = await func(request)
freqtrade2023  |   File "/home/ftuser/.local/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
freqtrade2023  |     raw_response = await run_endpoint_function(
freqtrade2023  |   File "/home/ftuser/.local/lib/python3.10/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
freqtrade2023  |     return await run_in_threadpool(dependant.call, **values)
freqtrade2023  |   File "/home/ftuser/.local/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
freqtrade2023  |     return await anyio.to_thread.run_sync(func, *args)
freqtrade2023  |   File "/home/ftuser/.local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
freqtrade2023  |     return await get_asynclib().run_sync_in_worker_thread(
freqtrade2023  |   File "/home/ftuser/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
freqtrade2023  |     return await future
freqtrade2023  |   File "/home/ftuser/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
freqtrade2023  |     result = context.run(func, *args)
freqtrade2023  |   File "/freqtrade/freqtrade/rpc/api_server/api_v1.py", line 82, in profit
freqtrade2023  |     return rpc._rpc_trade_statistics(config['stake_currency'],
freqtrade2023  |   File "/freqtrade/freqtrade/rpc/rpc.py", line 449, in _rpc_trade_statistics
freqtrade2023  |     if trade.close_profit >= 0:
freqtrade2023  | TypeError: '>=' not supported between instances of 'NoneType' and 'int'
freqtrade2023  | 2023-01-26 15:35:36,024 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='docker-2023.1.dev-bd913bc2', state='RUNNING'
freqtrade2023  | 2023-01-26 15:36:24,747 - uvicorn.error - ERROR - Exception in ASGI application


## Error 2

freqtrade2023  | 2023-01-28 01:43:42,147 - freqtrade.rpc.telegram - ERROR - Exception occurred within Telegram module
freqtrade2023  | Traceback (most recent call last):
freqtrade2023  |   File "/freqtrade/freqtrade/rpc/telegram.py", line 81, in wrapper
freqtrade2023  |     return command_handler(self, *args, **kwargs)
freqtrade2023  |   File "/freqtrade/freqtrade/rpc/telegram.py", line 765, in _profit
freqtrade2023  |     stats = self._rpc._rpc_trade_statistics(
freqtrade2023  |   File "/freqtrade/freqtrade/rpc/rpc.py", line 449, in _rpc_trade_statistics
freqtrade2023  |     if trade.close_profit >= 0:
freqtrade2023  | TypeError: '>=' not supported between instances of 'NoneType' and 'int'
```

I suspect a `0` value somewhere in the code or the config is being cast or evaluated to `None` type, and python complains when comparing the different types.

I've also got the issue of _always_ having 0 profit, despite being in profit for 2 days.

I'm just getting back into freqtrade (thank you for all the work and effort Matt!) after several months, and this is the first time I've seen the errors.  The app typically keeps running, when this case is encountered, however once it completely crashed from the error.

  * Operating system: Manjaro (Arch) Linux
  * Freqtrade Version: `freqtrade docker-2023.1.dev-bd913bc2`

**Comment by willwillis** [comment]
https://github.com/freqtrade/freqtrade/blob/develop/freqtrade/rpc/rpc.py#L210

I'm no python expert, but this might confirm my theory, I see a `trade.close_profit ` potentially getting set to `None` in some places, as well as `trade.close_profit ` being used by the `>=` comparison operator in other places, I haven't traversed the code to know if this object/variable is global, or if the value is passed between `_rpc_trade_statistics()` and `_rpc_trade_status()` but it doesn't seem right that one could assign the value to a `None` type and the other expecting an `int`.

I hope this helps.

```
Python 3.10.9 (main, Dec 19 2022, 17:35:49) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> foo = None
>>> if foo >= 0:
...     print('type compare ok')
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: '>=' not supported between instances of 'NoneType' and 'int'
>>> 
```

**Comment by xmatthias** [comment]
@willwillis Please don't highjack unrelated issues (this one is about bybit - where the issue is fixed).

I've marked both your comments as off topic here - please open a new issue if you think there's an issue with kucoin (please keep in mind that kucoin is NOT a supported exchange mainly because it's known that their API is not reliable).
The issue may look similar, but it's not. Thanks for your understanding.

**Comment by willwillis** [comment]
My apologies, my intention was to not create a duplicate thread for a similar issue. I didn't realize the exchange what such an important factor. (edit: despite Kucoin being mentioned by OP) I noticed that OP had the same `type` error from the same function `_rpc_trade_statistics()` so I thought I would add to this thread. I'll do as you suggest. thanks.

**Comment by xmatthias** [comment]
well the problem is caused by a bad answer for bybit.

the other problem (the one that mentions kucoin) is a network level error when connecting to telegram - where the exchange is not relevant, only the network reliability (or absense thereof).
