### ISSUE TITLE
hyperopt does not work on FreqaiExampleHybridStrategy

### ISSUE THREAD

**Issue by HeinrichHaller** [freqtrade/freqtrade#8085]
## Describe your environment

  * Operating system:  Ubuntu 22.04.1 LTS
  * Python Version: python3.10
  * CCXT version: CCXT 2.5.56
  * Freqtrade: docker-2023.1.dev-a261ee32
  

## Describe the problem:

While running hyperopt with the example strategy `FreqaiExampleHybridStrategy`, via `docker compose run freqtrade hyperopt --strategy FreqaiExampleHybridStrategy --config user_data/configs/config_freqai.example.classifier.static-original-algo-1inch.json  --timerange 20221215-20230115 --freqaimodel LightGBMClassifier --hyperopt-loss OnlyProfitHyperOptLoss`

I get the following error: 

```
023-01-31 23:39:31,118 - freqtrade - ERROR - Fatal exception!
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.10/site-packages/joblib/externals/loky/process_executor.py", line 428, in _process_worker
    r = call_item()
  File "/home/ftuser/.local/lib/python3.10/site-packages/joblib/externals/loky/process_executor.py", line 275, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/ftuser/.local/lib/python3.10/site-packages/joblib/_parallel_backends.py", line 620, in __call__
    return self.func(*args, **kwargs)
  File "/home/ftuser/.local/lib/python3.10/site-packages/joblib/parallel.py", line 288, in __call__
    return [func(*args, **kwargs)
  File "/home/ftuser/.local/lib/python3.10/site-packages/joblib/parallel.py", line 288, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/ftuser/.local/lib/python3.10/site-packages/joblib/externals/loky/cloudpickle_wrapper.py", line 33, in __call__
    return self._obj(*args, **kwargs)
  File "/freqtrade/freqtrade/optimize/hyperopt.py", line 337, in generate_optimizer
    bt_results = self.backtesting.backtest(
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 1145, in backtest
    data: Dict = self._get_ohlcv_as_lists(processed)
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 360, in _get_ohlcv_as_lists
    self.strategy.advise_entry(pair_data, {'pair': pair}),
  File "/freqtrade/freqtrade/strategy/interface.py", line 1235, in advise_entry
    df = self.populate_entry_trend(dataframe, metadata)
  File "/freqtrade/user_data/strategies/FreqaiExampleHybridStrategy.py", line 193, in populate_entry_trend
    (qtpylib.crossed_above(df['rsi'], self.buy_rsi.value)) &
  File "/home/ftuser/.local/lib/python3.10/site-packages/technical/vendor/qtpylib/indicators.py", line 243, in crossed_above
    return crossed(series1, series2, "above")
  File "/home/ftuser/.local/lib/python3.10/site-packages/technical/vendor/qtpylib/indicators.py", line 230, in crossed
    series1.shift(1) <= series2.shift(1)))
AttributeError: 'numpy.int64' object has no attribute 'shift'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 42, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 107, in start_hyperopt
    hyperopt.start()
  File "/freqtrade/freqtrade/optimize/hyperopt.py", line 606, in start
    f_val = self.run_optimizer_parallel(parallel, asked)
  File "/freqtrade/freqtrade/optimize/hyperopt.py", line 416, in run_optimizer_parallel
    return parallel(delayed(
  File "/home/ftuser/.local/lib/python3.10/site-packages/joblib/parallel.py", line 1098, in __call__
    self.retrieve()
  File "/home/ftuser/.local/lib/python3.10/site-packages/joblib/parallel.py", line 975, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/ftuser/.local/lib/python3.10/site-packages/joblib/_parallel_backends.py", line 567, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
AttributeError: 'numpy.int64' object has no attribute 'shift'
```

while the backtesting works.

The error occurs, for me,  in different environments  and versions as well.

### Steps to reproduce:

  1. running hyperopt with  FreqaiExampleHybridStrategy with the example config.json 
  2. backtesting works

**Comment by xmatthias** [comment]
You can fix this by either installing the develop version of technical - or by changing the import of qtpylib to 
`import freqtrade.vendor.qtpylib.indicators as qtpylib`.

I'll do a release of technical in a bit - which will fix this as well.

**Comment by HeinrichHaller** [comment]
Thanks, 
why does it work for the `FreqaiExampleStrategy`, though? How to install the develop version of technical, I can't find it under branches.

**Comment by xmatthias** [comment]
Technical is a separate package (https://github.com/freqtrade/technical). 

`FreqaiExampleStrategy` doesn't use crossed - so it's simply not calling that part.

**Comment by HeinrichHaller** [comment]
Obviously. Thanks
