### ISSUE TITLE
Bot crashes when it exits trades on Kucoin

### ISSUE THREAD

**Issue by Mo7mud** [freqtrade/freqtrade#8094]
## Describe your environment

  * Operating system:  Windows 10
  * Python Version: 3.10.7
  * CCXT version: 2.7.12
  * Freqtrade Version: 2023.1
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

Bot crashes when ever a trade exits on Kucoin however this doesn't happen on Binance.

  ```
2023-02-02 11:29:07,580 - freqtrade.freqtradebot - INFO - Exit for DOT/USDT detected. Reason: roi
2023-02-02 11:29:07,930 - freqtrade.wallets - INFO - Wallets synced.
2023-02-02 11:29:08,346 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': exit, 'trade_id': 196, 'exchange': 'Kucoin', 'pair': 'DOT/USDT', 'leverage': 1.0, 'direction': 'Long', 'gain': 'profit', 'limit': 6.5586, 'order_rate': 6.5586, 'order_type': 'limit', 'amount': 35.2023, 'open_rate': 6.44865798229093, 'close_rate': 6.5586, 'current_rate': 6.5586, 'profit_amount': 3.41232649, 'profit_ratio': 0.01501676, 'buy_tag': 'compined_up', 'enter_tag': 'compined_up', 'sell_reason': 'roi', 'exit_reason': 'roi', 'open_date': datetime.datetime(2023, 1, 30, 2, 16, 9, 731877), 'close_date': datetime.datetime(2023, 2, 2, 9, 29, 8, 346823), 'stake_amount': 227.00759289, 'stake_currency': 'USDT', 'fiat_currency': 'USD', 'sub_trade': False, 'cumulative_profit': 0.0}
2023-02-02 11:29:08,704 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=196, pair=DOT/USDT, amount=35.20230000, is_short=False, leverage=1.0, open_rate=6.44865798, open_since=2023-01-30 02:16:09)
2023-02-02 11:29:09,160 - freqtrade.freqtradebot - INFO - Applying fee on amount for Trade(id=196, pair=DOT/USDT, amount=35.20230000, is_short=False, leverage=1.0, open_rate=6.44865798, open_since=2023-01-30 02:16:09) failed: myTrade-Dict empty found
2023-02-02 11:29:09,162 - freqtrade.persistence.trade_model - INFO - Updating trade (id=196) ...
2023-02-02 11:29:09,162 - freqtrade.commands.trade_commands - ERROR - 'NoneType' object has no attribute 'upper'
2023-02-02 11:29:09,163 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "D:\freqtrade\freqtrade\commands\trade_commands.py", line 19, in start_trading
    worker.run()
  File "D:\freqtrade\freqtrade\worker.py", line 75, in run
    state = self._worker(old_state=state)
  File "D:\freqtrade\freqtrade\worker.py", line 116, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs,
  File "D:\freqtrade\freqtrade\worker.py", line 147, in _throttle
    result = func(*args, **kwargs)
  File "D:\freqtrade\freqtrade\worker.py", line 180, in _process_running
    self.freqtrade.process()
  File "D:\freqtrade\freqtrade\freqtradebot.py", line 229, in process
    self.exit_positions(trades)
  File "D:\freqtrade\freqtrade\freqtradebot.py", line 1013, in exit_positions
    if trade.open_order_id is None and trade.is_open and self.handle_trade(trade):
  File "D:\freqtrade\freqtrade\freqtradebot.py", line 1054, in handle_trade
    if self._check_and_execute_exit(trade, exit_rate, enter, exit_, exit_tag):
  File "D:\freqtrade\freqtrade\freqtradebot.py", line 1078, in _check_and_execute_exit
    exited = self.execute_trade_exit(trade, exit_rate, should_exit, exit_tag=exit_tag1)
  File "D:\freqtrade\freqtrade\freqtradebot.py", line 1613, in execute_trade_exit
    self.update_trade_state(trade, trade.open_order_id, order)
  File "D:\freqtrade\freqtrade\freqtradebot.py", line 1772, in update_trade_state
    trade.update_trade(order_obj)
  File "D:\freqtrade\freqtrade\persistence\trade_model.py", line 673, in update_trade
    logger.info(f'{order.order_type.upper()}_{payment} has been fulfilled for {self}.')
AttributeError: 'NoneType' object has no attribute 'upper'
2023-02-02 11:29:09,170 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2023-02-02 11:29:09,171 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2023-02-02 11:29:09,276 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2023-02-02 11:29:09,282 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': warning, 'status': "3 open trades active.\n\nHandle these trades manually on KuCoin, or '/start' the bot again and use '/stopentry' to handle open trades gracefully. \n"}
2023-02-02 11:29:09,392 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
2023-02-02 11:29:09,393 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.apiserver ...
2023-02-02 11:29:09,395 - freqtrade.rpc.api_server.webserver - INFO - Stopping API Server
2023-02-02 11:29:09,458 - uvicorn.error - INFO - Shutting down
2023-02-02 11:29:09,567 - uvicorn.error - INFO - Waiting for application shutdown.
2023-02-02 11:29:09,568 - uvicorn.error - INFO - Application shutdown complete.
2023-02-02 11:29:09,570 - uvicorn.error - INFO - Finished server process [11936]
2023-02-02 11:29:09,571 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.telegram ...
2023-02-02 11:29:09,572 - apscheduler.scheduler - INFO - Scheduler has been shut down
  ```

**Comment by xmatthias** [comment]
Please update to the latest develop - this was fixed in 680136f57d5421042c1dc62aee0f5f3951e53196.

Let me know if you still encounter that issue when using the latest develop (please make sure to also update the ccxt version alongside).
