### ISSUE TITLE
Backtests not using proxy

### ISSUE THREAD

**Issue by 1nbuc** [freqtrade/freqtrade#8150]
## Describe your environment

  * Operating system: Debian (docker)
  * Python Version: 3.10.7 (`python -V`)
  * CCXT version: 2.7.12 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2023.1 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:
The backtest command ignores configured proxy settings

*Explain the problem you have encountered*

I want to run some backtests on a server with an IP that is banned on Binance so I am always getting Error 451

I configured a Proxy on all possible ends. Environment Vars and all 3 options in the config under exchange like mentioned in the docs. But after all I am still getting this error when running backtests because it is not using the proxy.

### Steps to reproduce:

  1. Download Data
  2. Configure Proxy settings
  3. Run test from a restriced IP
  
### Observed Results:

  * What happened?
  * It used Server IP
  * What did you expect to happen?
  * To use the Proxy-IP

### Relevant code exceptions or logs
```
ccxt.base.errors.ExchangeNotAvailable: binance GET https://api.binance.com/api/v3/exchangeInfo 451  {
  "code": 0,
  "msg": "Service unavailable from a restricted location according to 'b. Eligibility' in https://www.binance.com/en/terms. Please contact customer service if you believe you received this message in error."Note: Please copy/paste text of the messages, no screenshots of logs please.
  ```
  ```
2023-02-11 10:06:23,913 - freqtrade - INFO - freqtrade 2023.1
2023-02-11 10:06:23,926 - freqtrade.configuration.load_config - INFO - Using config: user_data/config.json ...
2023-02-11 10:06:23,927 - freqtrade.loggers - INFO - Verbosity set to 0
2023-02-11 10:06:23,927 - freqtrade.configuration.configuration - INFO - Parameter -i/--timeframe detected ... Using timeframe: 1h ...
2023-02-11 10:06:23,927 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 6 ...
2023-02-11 10:06:23,927 - freqtrade.configuration.configuration - INFO - Parameter --timeframe-detail detected, using 5m for intra-candle backtesting ...
2023-02-11 10:06:23,927 - freqtrade.configuration.configuration - INFO - Parameter --fee detected, setting fee to: 0.00075 ...
2023-02-11 10:06:23,927 - freqtrade.configuration.configuration - INFO - Parameter --timerange detected: 20180406-20200717 ...
2023-02-11 10:06:23,952 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2023-02-11 10:06:23,952 - freqtrade.configuration.configuration - INFO - Using data directory: user_data/data/20180406-20200717 ...
2023-02-11 10:06:23,952 - freqtrade.configuration.configuration - INFO - Overriding timeframe with Command line argument
2023-02-11 10:06:23,952 - freqtrade.configuration.configuration - INFO - Parameter --cache=day detected ...
2023-02-11 10:06:23,952 - freqtrade.configuration.configuration - INFO - Filter trades by timerange: 20180406-20200717
2023-02-11 10:06:23,953 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2023-02-11 10:06:23,965 - freqtrade.exchange.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2023-02-11 10:06:23,965 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2023-02-11 10:06:23,965 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2023-02-11 10:06:23,970 - freqtrade.commands.optimize_commands - INFO - Starting freqtrade in Backtesting mode
2023-02-11 10:06:23,970 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2023-02-11 10:06:23,970 - freqtrade.exchange.exchange - INFO - Using CCXT 2.7.12
2023-02-11 10:06:23,991 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2023-02-11 10:06:24,072 - freqtrade.exchange.exchange - ERROR - Unable to initialize markets.
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 625, in fetch
    response.raise_for_status()
  File "/home/ftuser/.local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 451 Client Error:  for url: https://api.binance.com/api/v3/exchangeInfo

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/exchange.py", line 479, in _load_markets
    self._markets = self._api.load_markets(params={})
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 1460, in load_markets
    markets = self.fetch_markets(params)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/binance.py", line 1683, in fetch_markets
    promises.append(self.publicGetExchangeInfo(params))
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 505, in inner
    return entry(_self, **inner_kwargs)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/binance.py", line 6201, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2830, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 643, in fetch
    self.handle_http_status_code(http_status_code, http_status_text, url, method, http_response)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 1753, in handle_http_status_code
    raise ErrorClass(self.id + ' ' + method + ' ' + url + ' ' + codeAsString + ' ' + reason + ' ' + body)
ccxt.base.errors.ExchangeNotAvailable: binance GET https://api.binance.com/api/v3/exchangeInfo 451  {
  "code": 0,
  "msg": "Service unavailable from a restricted location according to 'b. Eligibility' in https://www.binance.com/en/terms. Please contact customer service if you believe you received this message in error."
}
2023-02-11 10:06:24,075 - freqtrade - ERROR - Could not load markets, therefore cannot start. Please investigate the above error for more details.
  ```

**Comment by xmatthias** [comment]
The config that generated the log above is clearly not configuring any proxies.

between the following 2 lines, the "additional ccxt config" settings should go.

```
2023-02-11 10:06:23,970 - freqtrade.exchange.exchange - INFO - Using CCXT 2.7.12
2023-02-11 10:06:23,991 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
```

applying [this](https://www.freqtrade.io/en/latest/configuration/#proxy-exchange-requests) configuration (i didn't modify it - as i don't get this problem otherwise) - i get the following log

```
2023-02-11 12:34:59,857 - freqtrade.exchange.exchange - INFO - Using CCXT 2.7.78
2023-02-11 12:34:59,857 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'aiohttp_proxy': 'http://addr:port', 'proxi
es': {'http': 'http://addr:port', 'https': 'http://addr:port'}, 'enableRateLimit': True}
2023-02-11 12:34:59,864 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'aiohttp_proxy': 'http://addr:port', 'proxi
es': {'http': 'http://addr:port', 'https': 'http://addr:port'}, 'enableRateLimit': True}
2023-02-11 12:34:59,870 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"

```


followed by 

```
2023-02-11 12:34:59,870 - freqtrade.exchange.exchange - ERROR - Unable to initialize markets.
Traceback (most recent call last):
  File "/home/xmatt/.pyenv/versions/3.10.8/envs/trade_3108/lib/python3.10/site-packages/requests/adapters.py", line 456, in send
    conn = self.get_connection(request.url, proxies)
  File "/home/xmatt/.pyenv/versions/3.10.8/envs/trade_3108/lib/python3.10/site-packages/requests/adapters.py", line 345, in get_connection
    proxy = prepend_scheme_if_needed(proxy, "http")
  File "/home/xmatt/.pyenv/versions/3.10.8/envs/trade_3108/lib/python3.10/site-packages/requests/utils.py", line 988, in prepend_scheme_if_n
eeded
    parsed = parse_url(url)
  File "/home/xmatt/.pyenv/versions/3.10.8/envs/trade_3108/lib/python3.10/site-packages/urllib3/util/url.py", line 397, in parse_url
    return six.raise_from(LocationParseError(source_url), None)
  File "<string>", line 3, in raise_from
urllib3.exceptions.LocationParseError: Failed to parse: http://addr:port

```

Which is expected - as my config of "addr:port" is REALLY wrong :laughing: 
But it clearly shows that the proxy is used just fine when used correctly.

**Comment by 1nbuc** [comment]
you are right I forgot to wrap it with "ccxt_config"
Sorry for that

**Comment by HunterXClarke** [comment]
I am getting the same error. 
The first issue arises from running it in Google Colab and having an US IP restricted by Binance.
The second comes from the necessity to use a proxy, which requires additional configuration, an available IP and some security/speed challenges.

Is it possible to bypass the configuration of the exchange and start the bot without actually connecting it to an exchange?

Since freqtrade has the possibility of reading/writing downloaded data, this could prove useful. 

Now the question arises, what is the best way of bypassing this step since I am only interested in configuring and backtesting the bot with already available data?
