### ISSUE TITLE
Tying to add EMA crossover to Supertrend

### ISSUE THREAD

**Issue by Membur** [freqtrade/freqtrade#8173]
## Describe your environment

  * Operating system: Windows 10 Pro
  * Python Version: Python 3.10.10
  * CCXT version: 2.7.12
  * Freqtrade Version: freqtrade 2023.1
  
## Your question

Thank you for your time!

I am having troubles adding a 13 48 ema crossover to the supertrend strategy without generating such error:
 ```
freqtrade  | 2023-02-14 20:22:19,619 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error module 'talib.abstract' has no attribute 'ema13' calling <bound method IStrategy._analyze_ticker_internal of <supertrend1348.Supertrend1348 object at 0x7f70df753880>>
freqtrade  | Traceback (most recent call last):
freqtrade  |   File "/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 27, in wrapper
freqtrade  |     return f(*args, **kwargs)
freqtrade  |   File "/freqtrade/freqtrade/strategy/interface.py", line 846, in _analyze_ticker_internal
freqtrade  |     dataframe = self.analyze_ticker(dataframe, metadata)
freqtrade  |   File "/freqtrade/freqtrade/strategy/interface.py", line 824, in analyze_ticker
freqtrade  |     dataframe = self.advise_indicators(dataframe, metadata)
freqtrade  |   File "/freqtrade/freqtrade/strategy/interface.py", line 1319, in advise_indicators
freqtrade  |     return self.populate_indicators(dataframe, metadata)
freqtrade  |   File "/freqtrade/user_data/strategies/supertrend1348.py", line 85, in populate_indicators
freqtrade  |     dataframe[f'supertrend_1_buy_{multiplier}_{period}'] = self.supertrend(dataframe, multiplier, period)['STX']
freqtrade  |   File "/freqtrade/user_data/strategies/supertrend1348.py", line 157, in supertrend
freqtrade  |     df['ema_13'] = ta.ema13(df['close'], window=13)
freqtrade  | AttributeError: module 'talib.abstract' has no attribute 'ema13'
freqtrade  | 2023-02-14 20:22:19,623 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair HBAR/USDT: module 'talib.abstract' has no attribute 'ema13'
```

My supertrend1348.py strategy is coded is below:

```
import logging
from numpy.lib import math
from freqtrade.strategy import IStrategy, IntParameter
import pandas as pd
from pandas import DataFrame
import talib.abstract as ta
import numpy as np
import freqtrade.vendor.qtpylib.indicators as qtpylib

class Supertrend1348(IStrategy):
    # Buy params, Sell params, ROI, Stoploss and Trailing Stop are values generated by 'freqtrade hyperopt --strategy Supertrend --hyperopt-loss ShortTradeDurHyperOptLoss --timerange=20210101- --timeframe=1h --spaces all'
    # It's encourage you find the values that better suites your needs and risk management strategies

    INTERFACE_VERSION: int = 3
    # Buy hyperspace params:
    buy_params = {
        "buy_m1": 4,
        "buy_m2": 7,
        "buy_m3": 1,
        "buy_p1": 8,
        "buy_p2": 9,
        "buy_p3": 8,
    }

    # Sell hyperspace params:
    sell_params = {
        "sell_m1": 1,
        "sell_m2": 3,
        "sell_m3": 6,
        "sell_p1": 16,
        "sell_p2": 18,
        "sell_p3": 18,
    }

    # ROI table:
    minimal_roi = {
        "0": 0.01,
        "800": 0
    }

    # Stoploss:
    stoploss = -0.5

    # Trailing stop:
    trailing_stop = True
    trailing_stop_positive = 0.05
    trailing_stop_positive_offset = 0.08
    trailing_only_offset_is_reached = False

    timeframe = '1h'

    startup_candle_count = 60

    buy_m1 = IntParameter(1, 7, default=4)
    buy_m2 = IntParameter(1, 7, default=4)
    buy_m3 = IntParameter(1, 7, default=4)
    buy_p1 = IntParameter(7, 21, default=14)
    buy_p2 = IntParameter(7, 21, default=14)
    buy_p3 = IntParameter(7, 21, default=14)

    sell_m1 = IntParameter(1, 7, default=4)
    sell_m2 = IntParameter(1, 7, default=4)
    sell_m3 = IntParameter(1, 7, default=4)
    sell_p1 = IntParameter(7, 21, default=14)
    sell_p2 = IntParameter(7, 21, default=14)
    sell_p3 = IntParameter(7, 21, default=14)

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        for multiplier in self.buy_m1.range:
            for period in self.buy_p1.range:
                dataframe[f'supertrend_1_buy_{multiplier}_{period}'] = self.supertrend(dataframe, multiplier, period)['STX']

        for multiplier in self.buy_m2.range:
            for period in self.buy_p2.range:
                dataframe[f'supertrend_2_buy_{multiplier}_{period}'] = self.supertrend(dataframe, multiplier, period)['STX']

        for multiplier in self.buy_m3.range:
            for period in self.buy_p3.range:
                dataframe[f'supertrend_3_buy_{multiplier}_{period}'] = self.supertrend(dataframe, multiplier, period)['STX']

        for multiplier in self.sell_m1.range:
            for period in self.sell_p1.range:
                dataframe[f'supertrend_1_sell_{multiplier}_{period}'] = self.supertrend(dataframe, multiplier, period)['STX']

        for multiplier in self.sell_m2.range:
            for period in self.sell_p2.range:
                dataframe[f'supertrend_2_sell_{multiplier}_{period}'] = self.supertrend(dataframe, multiplier, period)['STX']

        for multiplier in self.sell_m3.range:
            for period in self.sell_p3.range:
                dataframe[f'supertrend_3_sell_{multiplier}_{period}'] = self.supertrend(dataframe, multiplier, period)['STX']

          # Add the 13 EMA, 48 EMA
        dataframe['ema13'] = ta.EMA(dataframe, timeperiod=13)
        dataframe['ema48'] = ta.EMA(dataframe, timeperiod=48)

        # TEMA
        dataframe['tema'] = ta.TEMA(dataframe, timeperiod=9)
        
        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
               (dataframe[f'supertrend_1_buy_{self.buy_m1.value}_{self.buy_p1.value}'] == 'up') &
               (dataframe[f'supertrend_2_buy_{self.buy_m2.value}_{self.buy_p2.value}'] == 'up') &
               (dataframe[f'supertrend_3_buy_{self.buy_m3.value}_{self.buy_p3.value}'] == 'up') &
               (qtpylib.crossed_above(dataframe['ema13'], dataframe['ema48'])) | (dataframe['ema13'] > dataframe['ema48']) &
               (dataframe['volume'] > 0) # There is at least some trading volume
        ),
            'enter_long'] = 1

        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
               (dataframe[f'supertrend_1_sell_{self.sell_m1.value}_{self.sell_p1.value}'] == 'down') &
               (dataframe[f'supertrend_2_sell_{self.sell_m2.value}_{self.sell_p2.value}'] == 'down') &
               (dataframe[f'supertrend_3_sell_{self.sell_m3.value}_{self.sell_p3.value}'] == 'down') & # The three indicators are 'down' for the current candle
               (dataframe['volume'] > 0) # There is at least some trading volume
            ),
            'exit_long'] = 1

        return dataframe
```
        
        

        Thanks again for your time!

**Comment by stash86** [comment]
https://github.com/freqtrade/freqtrade-strategies/blob/main/user_data/strategies/Strategy004.py

**Comment by stash86** [comment]
Btw, not sure if this line should exist

`df = pd.DataFrame({'close': [10, 12, 15, 18, 20, 22, 23, 24, 22, 20, 18, 15, 12, 10]})`

**Comment by Membur** [comment]
I have updated the code and I am still getting an error:

freqtrade  | 2023-02-14 22:40:06,599 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error module 'talib.abstract' has no attribute 'ema13' calling <bound method IStrategy._analyze_ticker_internal of <supertrend1348.Supertrend1348 object at 0x7f115ee33850>>
freqtrade  | Traceback (most recent call last):
freqtrade  |   File "/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 27, in wrapper
freqtrade  |     return f(*args, **kwargs)
freqtrade  |   File "/freqtrade/freqtrade/strategy/interface.py", line 846, in _analyze_ticker_internal
freqtrade  |     dataframe = self.analyze_ticker(dataframe, metadata)
freqtrade  |   File "/freqtrade/freqtrade/strategy/interface.py", line 824, in analyze_ticker
freqtrade  |     dataframe = self.advise_indicators(dataframe, metadata)
freqtrade  |   File "/freqtrade/freqtrade/strategy/interface.py", line 1319, in advise_indicators
freqtrade  |     return self.populate_indicators(dataframe, metadata)
freqtrade  |   File "/freqtrade/user_data/strategies/supertrend1348.py", line 198, in populate_indicators
freqtrade  |     df['ema13'] = ta.ema13(df['close'], window=13)
freqtrade  | AttributeError: module 'talib.abstract' has no attribute 'ema13'
freqtrade  | 2023-02-14 22:40:06,602 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair HBAR/USDT: module 'talib.abstract' has no attribute 'ema13'

**I have edited the code in the orginal post to the updated code**

**Comment by stash86** [comment]
you might have call wrong class name, or you have duplicate class name

**Comment by Membur** [comment]
I fixed the issue by adding;

New import:
`Import qtpylib.blotter import Blotter
`
New line in populate_entry_trend:
`(qtpylib.crossed_above(dataframe['ema13'], dataframe['ema48'])) | (dataframe['ema13'] > dataframe['ema48']) &
`
Thanks!

**Comment by xmatthias** [comment]
> Import qtpylib.blotter import Blotter 

This makes 0 sense ... Blotter is not used in the above strategy  ...

**Comment by Membur** [comment]
Your right, that was my mistake; working on another project with Blotter and pasted the wrong import here :(

I used: `import freqtrade.vendor.qtpylib.indicators as qtpylib`

I will update the original code above as well.
