### ISSUE TITLE
Freqai Backtesting Error

### ISSUE THREAD

**Issue by jacobsterling** [freqtrade/freqtrade#8180]
## Describe your environment

  * Operating system: Win11
  * Python Version: 3.10.9
  * CCXT version: 2.7.66
  * Freqtrade Version: freqtrade 2023.2.dev
  
## Describe the problem:

Trying to backtest freqai strategy

Get the following error regardless of what freqaimodel i use:

File "[C:\Users\j10st\AppData\Local\Programs\Python\Python310\lib\site-packages\freqtrade\freqai\freqai_interface.py](file:///C:/Users/j10st/AppData/Local/Programs/Python/Python310/lib/site-packages/freqtrade/freqai/freqai_interface.py)", line 353, in start_backtesting
    self.dd.save_data(self.model, pair, dk)
AttributeError: 'CatboostRegressor' object has no attribute 'model'

I have 2 models saved as sub-train-ETH_1676543451 and sub-train-ETH_1676532651. created from the "freqtrade trade --strategy TrendMomoRegression --freqaimodel CatboostRegressor" which works fine, just seems to be the backtesting command.

freqai config:

{
    "freqai": {
        "enabled": true,
        "purge_old_models": true,
        "train_period_days": 30,
        "backtest_period_days": 90,
        "live_retrain_hours": 3,
        "save_backtest_models": true,
        "identifier": "trend&momo",
        "feature_parameters": {
            "include_timeframes": [
                "15m",
                "1h",
                "4h",
                "1d"
            ],
            "include_corr_pairlist": [],
            "label_period_candles": 20,
            "include_shifted_candles": 2,
            "DI_threshold": 0.9,
            "weight_factor": 0.9,
            "principal_component_analysis": false,
            "use_SVM_to_remove_outliers": true,
            "indicator_periods_candles": [
                10,
                20
            ],
            "plot_feature_importances": 0
        },
        "data_split_parameters": {
            "test_size": 0.33,
            "random_state": 1,
            "shuffle": false
        },
        "model_training_parameters": {},
        "keras": false,
        "write_metrics_to_disk": false,
        "conv_width": 1
    },
    "timeframe": "15m",
    "stake_amount": 200,
    "stake_currency": "USDT",
    "max_open_trades": 3,
    "pairs": [
        "ETH/USDT:USDT"
    ]
}

### Steps to reproduce:

  1. freqtrade backtesting --strategy TrendMomoRegression --freqaimodel CatboostRegressor --timerange 20221015-20230212

Not sure why it has stopped storing my logs (something to do with my config ?)

### Relevant code exceptions or logs

2023-02-16 10:45:54,192 - freqtrade - INFO - freqtrade 2023.2.dev
2023-02-16 10:45:54,195 - freqtrade.configuration.load_config - INFO - Using config: config.json ...
2023-02-16 10:45:54,195 - freqtrade.configuration.load_config - INFO - Using config: configs/private.json ...
2023-02-16 10:45:54,195 - freqtrade.configuration.load_config - INFO - Using config: configs/gateio.json ...
2023-02-16 10:45:54,196 - freqtrade.configuration.load_config - INFO - Using config: models/trend&momo/run_params.json ...
2023-02-16 10:45:54,196 - freqtrade.loggers - INFO - Verbosity set to 0
2023-02-16 10:45:54,197 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 3 ...
2023-02-16 10:45:54,197 - freqtrade.configuration.configuration - INFO - Parameter --timerange detected: 20221015-20230212 ...
2023-02-16 10:45:54,197 - freqtrade.configuration.configuration - INFO - Using user-data directory: [F:\AiQuant](file:///F:/AiQuant) ...
2023-02-16 10:45:54,197 - freqtrade.configuration.configuration - INFO - Using data directory: [F:\AiQuant\data\gateio](file:///F:/AiQuant/data/gateio) ...
2023-02-16 10:45:54,197 - freqtrade.configuration.configuration - INFO - Parameter --cache=day detected ...
2023-02-16 10:45:54,197 - freqtrade.configuration.configuration - INFO - Filter trades by timerange: 20221015-20230212
2023-02-16 10:45:54,197 - freqtrade.configuration.configuration - INFO - Using freqaimodel class name: CatboostRegressor
2023-02-16 10:45:54,198 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2023-02-16 10:45:54,202 - freqtrade.exchange.check_exchange - INFO - Exchange "gateio" is officially supported by the Freqtrade development team.
2023-02-16 10:45:54,202 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2023-02-16 10:45:54,206 - freqtrade.commands.optimize_commands - INFO - Starting freqtrade in Backtesting mode
2023-02-16 10:45:54,207 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2023-02-16 10:45:54,207 - freqtrade.exchange.exchange - INFO - Using CCXT 2.7.66
2023-02-16 10:45:54,207 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}, 'timeout': 20000}
2023-02-16 10:45:54,211 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}, 'timeout': 20000}
2023-02-16 10:45:54,216 - freqtrade.exchange.exchange - INFO - Using Exchange "Gate.io"
2023-02-16 10:46:32,745 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Gateio'...
2023-02-16 10:46:32,760 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy TrendMomoRegression from '[F:\AiQuant\strategies\TrendMomoRegression.py](file:///F:/AiQuant/strategies/TrendMomoRegression.py)'...
2023-02-16 10:46:32,761 - freqtrade.strategy.hyper - INFO - Found no parameter file.
...
    dk = self.start_backtesting(dataframe, metadata, self.dk, strategy)
  File "[C:\Users\j10st\AppData\Local\Programs\Python\Python310\lib\site-packages\freqtrade\freqai\freqai_interface.py](file:///C:/Users/j10st/AppData/Local/Programs/Python/Python310/lib/site-packages/freqtrade/freqai/freqai_interface.py)", line 353, in start_backtesting
    self.dd.save_data(self.model, pair, dk)
AttributeError: 'CatboostRegressor' object has no attribute 'model'

**Comment by robcaulk** [comment]
Hello,

please provide the full log next time, I suspect there is a line that indicates that your number of data points is insufficient. 

Have you read our documentation about how to download the proper amount of data for backtesting? If not, please go ahead and implement the instructions we have highlighted there and then return if you still have issues. 

https://www.freqtrade.io/en/stable/freqai-running/#downloading-data-to-cover-the-full-backtest-period

Cheers,

robert

**Comment by jacobsterling** [comment]
Hi Robert, thankyou for the response, 
i set the start date 30.42 ( train_period_days = 30, startup_candle_count = 40, timeframe= 15m ) days before after the start date of the downloaded data, as suggested by the documentation. I still get the same error.

The logs dont indicate the number of data points is insufficient, but instead errors after Saving backtest model to disk. See the full logs below:

freqtrade backtesting --strategy TrendMomoRegression --freqaimodel CatboostRegressor --timerange 20221115-20230212
2023-02-16 12:46:06,682 - freqtrade - INFO - freqtrade 2023.2.dev
2023-02-16 12:46:06,684 - freqtrade.configuration.load_config - INFO - Using config: config.json ...
2023-02-16 12:46:06,684 - freqtrade.configuration.load_config - INFO - Using config: configs/private.json ...
2023-02-16 12:46:06,684 - freqtrade.configuration.load_config - INFO - Using config: configs/gateio.json ...
2023-02-16 12:46:06,684 - freqtrade.configuration.load_config - INFO - Using config: models/trend&momo/run_params.json ...
2023-02-16 12:46:06,685 - freqtrade.loggers - INFO - Verbosity set to 0
2023-02-16 12:46:06,685 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 3 ...
2023-02-16 12:46:06,685 - freqtrade.configuration.configuration - INFO - Parameter --timerange detected: 20221115-20230212 ...
2023-02-16 12:46:06,686 - freqtrade.configuration.configuration - INFO - Using user-data directory: F:\AiQuant ...
2023-02-16 12:46:06,686 - freqtrade.configuration.configuration - INFO - Using data directory: F:\AiQuant\data\gateio ...
2023-02-16 12:46:06,686 - freqtrade.configuration.configuration - INFO - Parameter --cache=day detected ...
2023-02-16 12:46:06,686 - freqtrade.configuration.configuration - INFO - Filter trades by timerange: 20221115-20230212
2023-02-16 12:46:06,686 - freqtrade.configuration.configuration - INFO - Using freqaimodel class name: CatboostRegressor
2023-02-16 12:46:06,686 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2023-02-16 12:46:06,691 - freqtrade.exchange.check_exchange - INFO - Exchange "gateio" is officially supported by the Freqtrade development team.
2023-02-16 12:46:06,691 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2023-02-16 12:46:06,695 - freqtrade.commands.optimize_commands - INFO - Starting freqtrade in Backtesting mode
2023-02-16 12:46:06,695 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2023-02-16 12:46:06,695 - freqtrade.exchange.exchange - INFO - Using CCXT 2.7.66
2023-02-16 12:46:06,696 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}, 'timeout': 20000}
2023-02-16 12:46:06,700 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}, 'timeout': 20000}
2023-02-16 12:46:06,705 - freqtrade.exchange.exchange - INFO - Using Exchange "Gate.io"
2023-02-16 12:47:08,068 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Gateio'...
2023-02-16 12:47:08,083 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy TrendMomoRegression from 'F:\AiQuant\strategies\TrendMomoRegression.py'...
2023-02-16 12:47:08,085 - freqtrade.strategy.hyper - INFO - Found no parameter file.
2023-02-16 12:47:08,085 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 15m.
2023-02-16 12:47:08,085 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2023-02-16 12:47:08,085 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 200.
2023-02-16 12:47:08,085 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'entry': 10, 'exit': 30, 'exit_timeout_count': 0, 'unit': 'minutes'}.
2023-02-16 12:47:08,085 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'max_open_trades' with value in config file: 3.
2023-02-16 12:47:08,085 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 0.1, '240': -1}
2023-02-16 12:47:08,085 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 15m
2023-02-16 12:47:08,085 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.05
2023-02-16 12:47:08,085 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2023-02-16 12:47:08,086 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2023-02-16 12:47:08,086 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2023-02-16 12:47:08,086 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2023-02-16 12:47:08,086 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: True
2023-02-16 12:47:08,086 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'entry': 'limit', 'exit': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False, 'stoploss_on_exchange_interval': 60}
2023-02-16 12:47:08,086 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'entry': 'GTC', 'exit': 'GTC'}
2023-02-16 12:47:08,086 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2023-02-16 12:47:08,086 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 200
2023-02-16 12:47:08,086 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2023-02-16 12:47:08,086 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 40
2023-02-16 12:47:08,086 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'entry': 10, 'exit': 30, 'exit_timeout_count': 0, 'unit': 'minutes'}
2023-02-16 12:47:08,086 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_exit_signal: True
2023-02-16 12:47:08,086 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_only: False
2023-02-16 12:47:08,086 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_entry_signal: False
2023-02-16 12:47:08,086 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_offset: 0.0
2023-02-16 12:47:08,086 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2023-02-16 12:47:08,087 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2023-02-16 12:47:08,087 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: False
2023-02-16 12:47:08,087 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1
2023-02-16 12:47:08,087 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_open_trades: 3
2023-02-16 12:47:08,087 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2023-02-16 12:47:08,097 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from 'C:\Users\j10st\AppData\Local\Programs\Python\Python310\Lib\site-packages\freqtrade\plugins\pairlist\StaticPairList.py'...
2023-02-16 12:47:08,106 - freqtrade.data.dataprovider - INFO - Increasing startup_candle_count for freqai to 2920
2023-02-16 12:47:08,106 - freqtrade.data.history.history_utils - INFO - Using indicator startup period: 2920 ...
2023-02-16 12:47:08,167 - freqtrade.data.history.idatahandler - WARNING - ETH/USDT:USDT, futures, 15m, data starts at 2022-11-15 00:00:00
2023-02-16 12:47:08,179 - freqtrade.optimize.backtesting - INFO - Loading data from 2022-11-15 00:00:00 up to 2023-02-12 00:00:00 (89 days).
2023-02-16 12:47:08,179 - freqtrade.configuration.timerange - WARNING - Moving start-date by 2920 candles to account for startup time.
2023-02-16 12:47:08,191 - freqtrade.data.history.idatahandler - WARNING - ETH/USDT:USDT, funding_rate, 8h, data starts at 2022-12-15 16:00:00
2023-02-16 12:47:08,210 - freqtrade.data.history.idatahandler - WARNING - ETH/USDT:USDT, mark, 8h, data starts at 2022-12-15 16:00:00
2023-02-16 12:47:08,217 - freqtrade.optimize.backtesting - INFO - Dataload complete. Calculating indicators
2023-02-16 12:47:08,218 - freqtrade.optimize.backtesting - INFO - Running backtesting for Strategy TrendMomoRegression
2023-02-16 12:47:09,037 - freqtrade.resolvers.iresolver - INFO - Using resolved freqaimodel CatboostRegressor from 'F:\AiQuant\freqaimodels\CatboostRegressor.py'...
2023-02-16 12:47:09,038 - freqtrade.freqai.freqai_interface - INFO - Backtesting module configured to save all models.
2023-02-16 12:47:09,039 - freqtrade.freqai.data_drawer - INFO - Found existing historic predictions at F:\AiQuant\models\trend&momo, but beware that statistics may be inaccurate if the bot has been offline for an extended period of time.
2023-02-16 12:47:09,039 - freqtrade.freqai.freqai_interface - INFO - Set existing queue from trained timestamps. Best approximation queue: deque(['ETH/USDT:USDT'])
2023-02-16 12:47:09,039 - freqtrade.strategy.hyper - INFO - No params for buy found, using default values.
2023-02-16 12:47:09,039 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): std_dev_multiplier_buy = 1.25
2023-02-16 12:47:09,040 - freqtrade.strategy.hyper - INFO - No params for sell found, using default values.
2023-02-16 12:47:09,040 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): std_dev_multiplier_sell = 1.25
2023-02-16 12:47:09,040 - freqtrade.strategy.hyper - INFO - No params for protection found, using default values.
2023-02-16 12:47:09,043 - freqtrade.freqai.freqai_interface - INFO - Training 13 timeranges
2023-02-16 12:47:09,044 - freqtrade.freqai.freqai_interface - INFO - Training ETH/USDT:USDT, 1/1 pairs from 2022-10-16 00:00:00 to 2022-11-15 00:00:00, 1/13 trains
2023-02-16 12:47:09,044 - freqtrade.freqai.data_kitchen - INFO - Could not find backtesting prediction file at F:\AiQuant\models\trend&momo\backtesting_predictions\cb_eth_1668470400_prediction.feather
2023-02-16 12:47:09,045 - freqtrade.data.dataprovider - INFO - Increasing startup_candle_count for freqai to 2920
2023-02-16 12:47:09,063 - freqtrade.data.history.idatahandler - WARNING - ETH/USDT:USDT, futures, 15m, data starts at 2022-11-15 00:00:00
2023-02-16 12:47:09,101 - freqtrade.data.dataprovider - INFO - Increasing startup_candle_count for freqai to 2920
2023-02-16 12:47:09,114 - freqtrade.data.history.idatahandler - WARNING - ETH/USDT:USDT, futures, 1h, data starts at 2022-11-15 00:00:00
2023-02-16 12:47:09,147 - freqtrade.data.dataprovider - INFO - Increasing startup_candle_count for freqai to 2920
2023-02-16 12:47:09,159 - freqtrade.data.history.idatahandler - WARNING - ETH/USDT:USDT, futures, 4h, data starts at 2022-11-15 00:00:00
2023-02-16 12:47:09,192 - freqtrade.data.dataprovider - INFO - Increasing startup_candle_count for freqai to 2920
2023-02-16 12:47:09,204 - freqtrade.data.history.idatahandler - WARNING - ETH/USDT:USDT, futures, 1d, data starts at 2022-11-15 00:00:00
2023-02-16 12:47:09,260 - freqtrade.freqai.freqai_interface - INFO - Could not find model at F:\AiQuant\models\trend&momo\sub-train-ETH_1668470400\cb_eth_1668470400
2023-02-16 12:47:09,260 - freqtrade.freqai.base_models.BaseRegressionModel - INFO - -------------------- Starting training ETH/USDT:USDT --------------------
2023-02-16 12:47:09,262 - freqtrade.freqai.data_kitchen - INFO - dropped 0 training points due to NaNs in populated dataset 0.
2023-02-16 12:47:09,262 - freqtrade.freqai.freqai_interface - WARNING - Training ETH/USDT:USDT raised exception ZeroDivisionError. Message: division by zero, skipping.
2023-02-16 12:47:09,263 - freqtrade.freqai.freqai_interface - INFO - Saving backtest model to disk.
2023-02-16 12:47:09,263 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "C:\Users\j10st\AppData\Local\Programs\Python\Python310\lib\site-packages\freqtrade\main.py", line 42, in main
    return_code = args['func'](args)
  File "C:\Users\j10st\AppData\Local\Programs\Python\Python310\lib\site-packages\freqtrade\commands\optimize_commands.py", line 58, in start_backtesting
    backtesting.start()
  File "C:\Users\j10st\AppData\Local\Programs\Python\Python310\lib\site-packages\freqtrade\optimize\backtesting.py", line 1344, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
  File "C:\Users\j10st\AppData\Local\Programs\Python\Python310\lib\site-packages\freqtrade\optimize\backtesting.py", line 1246, in backtest_one_strategy
    preprocessed = self.strategy.advise_all_indicators(data)
  File "C:\Users\j10st\AppData\Local\Programs\Python\Python310\lib\site-packages\freqtrade\strategy\interface.py", line 1305, in advise_all_indicators
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "C:\Users\j10st\AppData\Local\Programs\Python\Python310\lib\site-packages\freqtrade\strategy\interface.py", line 1305, in <dictcomp>
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "C:\Users\j10st\AppData\Local\Programs\Python\Python310\lib\site-packages\freqtrade\strategy\interface.py", line 1323, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "F:\AiQuant\strategies\TrendMomoRegression.py", line 86, in populate_indicators
    df = self.freqai.start(df, metadata, self)
  File "C:\Users\j10st\AppData\Local\Programs\Python\Python310\lib\site-packages\freqtrade\freqai\freqai_interface.py", line 159, in start
    dk = self.start_backtesting(dataframe, metadata, self.dk, strategy)
  File "C:\Users\j10st\AppData\Local\Programs\Python\Python310\lib\site-packages\freqtrade\freqai\freqai_interface.py", line 353, in start_backtesting
    self.dd.save_data(self.model, pair, dk)
AttributeError: 'CatboostRegressor' object has no attribute 'model'

**Comment by robcaulk** [comment]
Hello,

It seems you may have missed this section: 

https://www.freqtrade.io/en/stable/freqai-running/#downloading-data-to-cover-the-full-backtest-period

The section indicates that you need to download *additional* data that extends *earlier* than your desired backtesting timerange (this is because FreqAI needs data to train a model to make predictions on your first desired candle in your desired backtesting timerange) Your logs indicate that you have not done this:

```
freqtrade.freqai.data_kitchen - INFO - dropped 0 training points due to NaNs in populated dataset 0.
```

Please go ahead, read the section I link to above and then download the necessary data for your backtest. Else, let us know what about this section is confusing so that we can improve the documentation for other users.

Thanks for taking the time to read the documentation that I have linked to,

Robert

**Comment by robcaulk** [comment]
Another place to spot your data start date is on this line:

```
 freqtrade.data.history.idatahandler - WARNING - ETH/USDT:USDT, futures, 15m, data starts at 2022-11-15 00:00:00
 ```
 Which indicates that the data you have starts at the same day as the start date of your backtesting timerange. You need *additional* data 30 days earlier than this for FreqAI to haev a model trained on 30 days of data to make a prediction on your first day. 

Hope it helps.

**Comment by jacobsterling** [comment]
Thanks Robert, that did help. I dont think the documentation regarding this needs changing, reading it again seems to make sense.
