### ISSUE TITLE
3.11: "ValueError: 'CandleType' is not a valid CandleType" or "No pair in whitelist."

### ISSUE THREAD

**Issue by ET205** [freqtrade/freqtrade#8221]
### Have you searched for similar issues before posting it?

Yes.

## Describe your environment

  * Operating system: Windows 10
  * Python Version: 3.11.0
  * CCXT version: 2.8.17
  * Freqtrade Version: 2023.2.dev-cdc96136b
  
## Describe the problem:

Running `freqtrade backtesting --strategy SampleStrategy --config config.json --data-format-ohlcv hdf5 --timerange 20210101- --enable-position-stacking --enable-protections --pairs BNB/USDT:USDT BTC/USDT:USDT ETH/USDT:USDT CFX/USDT:USDT SOL/USDT:USDT LTC/USDT:USDT DOGE/USDT:USDT XTZ/USDT` gives the error mentioned in the title.

### Steps to reproduce:

  1. `freqtrade new-config --config config.json`
  2. `freqtrade create-userdir --userdir user_data`
  3. `config.json` modified. *Relevant* parts:-
```
    "max_open_trades": 4,
    "stake_currency": "USDT",
    "stake_amount": "unlimited",
    "tradable_balance_ratio": 0.8,
    "dry_run": true,
    "dry_run_wallet": 50,
    "cancel_open_orders_on_exit": false,
    "trading_mode": "futures",
    "margin_mode": "isolated",
    "exchange": {
        "name": "binance",
        "ccxt_config": {},
        "ccxt_async_config": {},
        "pair_whitelist": [
        ],
        "pair_blacklist": [
            "BNB/.*"
        ]
    },
    "pairlists": [
        {
            "method": "StaticPairList",
        }
    ],
```
  5. `user_data\sample_strategy.py` modified. *Relevant* parts:-
```
    trailing_stop = True
    timeframe = '1m'
```
  7. `freqtrade download-data --erase --data-format-trades hdf5 --data-format-ohlcv hdf5 --include-inactive-pairs --timerange 20210101- --timeframes 1m --trading-mode futures --pairs BNB/USDT BTC/USDT ETH/USDT CFX/USDT SOL/USDT LTC/USDT DOGE/USDT XTZ/USDT`
  8. `freqtrade backtesting --strategy SampleStrategy --config config.json --data-format-ohlcv hdf5 --timerange 20210101- --enable-position-stacking --enable-protections --pairs BNB/USDT BTC/USDT ETH/USDT CFX/USDT SOL/USDT LTC/USDT DOGE/USDT XTZ/USDT` gives "No pair in whitelist" even though the pairs do exist and are active as confirmed by `freqtrade list-pairs --exchange binance --trading-mode futures` and by going onto Binance and looking the pairs up.
  9. `freqtrade backtesting --strategy SampleStrategy --config config.json --data-format-ohlcv hdf5 --timerange 20210101- --enable-position-stacking --enable-protections --pairs BNB/USDT:USDT BTC/USDT:USDT ETH/USDT:USDT CFX/USDT:USDT SOL/USDT:USDT LTC/USDT:USDT DOGE/USDT:USDT XTZ/USDT:USDT` gives "ValueError: 'CandleType' is not a valid CandleType".
  
#### What happened?
`freqtrade backtesting --strategy SampleStrategy --config config.json --data-format-ohlcv hdf5 --timerange 20210101- --enable-position-stacking --enable-protections --pairs BNB/USDT BTC/USDT ETH/USDT CFX/USDT SOL/USDT LTC/USDT DOGE/USDT XTZ/USDT` gives "No pair in whitelist" even though the pairs do exist and are active as confirmed by `freqtrade list-pairs --exchange binance --trading-mode futures` and by going onto Binance and looking the pairs up.

`freqtrade backtesting --strategy SampleStrategy --config config.json --data-format-ohlcv hdf5 --timerange 20210101- --enable-position-stacking --enable-protections --pairs BNB/USDT:USDT BTC/USDT:USDT ETH/USDT:USDT CFX/USDT:USDT SOL/USDT:USDT LTC/USDT:USDT DOGE/USDT:USDT XTZ/USDT:USDT` gives "ValueError: 'CandleType' is not a valid CandleType".

#### What did you expect to happen?
Backtesting..?

#### Terminal Log for `download-data` command:-
```
2023-02-25 05:13:56,185 - freqtrade - INFO - freqtrade 2023.2.dev-cdc96136b
2023-02-25 05:13:56,185 - freqtrade.configuration.load_config - INFO - Using config: config.json ...
2023-02-25 05:13:56,186 - freqtrade.loggers - INFO - Verbosity set to 0
2023-02-25 05:13:56,186 - freqtrade.configuration.configuration - INFO - Parameter --timerange detected: 20210101- ...
2023-02-25 05:13:56,188 - freqtrade.configuration.configuration - INFO - Using user-data directory: [folder_path_removed_for privacy]\freqtrade\user_data ...
2023-02-25 05:13:56,188 - freqtrade.configuration.configuration - INFO - Using data directory: [folder_path_removed_for privacy]\freqtrade\user_data\data\binance ...
2023-02-25 05:13:56,188 - freqtrade.configuration.configuration - INFO - Using pairs ['BNB/USDT', 'BTC/USDT', 'ETH/USDT', 'CFX/USDT', 'SOL/USDT', 'LTC/USDT', 'DOGE/USDT', 'XTZ/USDT']
2023-02-25 05:13:56,189 - freqtrade.configuration.configuration - INFO - Erase detected. Deleting existing data.
2023-02-25 05:13:56,189 - freqtrade.configuration.configuration - INFO - timeframes --timeframes: ['1m']
2023-02-25 05:13:56,189 - freqtrade.configuration.configuration - INFO - Detected --include-inactive-pairs: True
2023-02-25 05:13:56,189 - freqtrade.configuration.configuration - INFO - Using "hdf5" to store OHLCV data.
2023-02-25 05:13:56,189 - freqtrade.configuration.configuration - INFO - Using "hdf5" to store trades data.
2023-02-25 05:13:56,190 - freqtrade.configuration.configuration - INFO - Detected --trading-mode: futures
2023-02-25 05:13:56,190 - freqtrade.configuration.configuration - INFO - Filter trades by timerange: 20210101-
2023-02-25 05:13:56,191 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2023-02-25 05:13:56,201 - freqtrade.exchange.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2023-02-25 05:13:56,202 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2023-02-25 05:13:56,211 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2023-02-25 05:13:56,212 - freqtrade.exchange.exchange - INFO - Using CCXT 2.8.17
2023-02-25 05:13:56,212 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}}
2023-02-25 05:13:56,224 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}}
2023-02-25 05:13:56,236 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2023-02-25 05:13:56,236 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2023-02-25 05:13:56,237 - freqtrade.exchange.exchange - INFO - Markets were not loaded. Loading them now..
2023-02-25 05:14:02,731 - freqtrade.commands.data_commands - INFO - About to download pairs: ['BNB/USDT', 'BTC/USDT', 'ETH/USDT', 'CFX/USDT', 'SOL/USDT', 'LTC/USDT', 'DOGE/USDT', 'XTZ/USDT'], intervals: ['1m'] to [folder_path_removed_for privacy]\freqtrade\user_data\data\binance
2023-02-25 05:14:02,733 - freqtrade.data.history.history_utils - INFO - Downloading pair BNB/USDT, interval 1m.
2023-02-25 05:14:02,735 - freqtrade.data.history.history_utils - INFO - (1/8) - Download history data for "BNB/USDT", 1m, CandleType.FUTURES and store in [folder_path_removed_for privacy]\freqtrade\user_data\data\binance. From 2021-01-01T05:30:00 to now
2023-02-25 05:15:04,412 - freqtrade.exchange.exchange - INFO - Downloaded data for BNB/USDT with length 1130386.
2023-02-25 05:15:08,410 - freqtrade.data.history.history_utils - INFO - (1/8) - Download history data for "BNB/USDT", 8h, CandleType.FUNDING_RATE and store in [folder_path_removed_for privacy]\freqtrade\user_data\data\binance. From 2021-01-01T05:30:00 to now
2023-02-25 05:15:09,485 - freqtrade.exchange.exchange - INFO - Downloaded data for BNB/USDT with length 0.
2023-02-25 05:15:09,540 - freqtrade.data.history.history_utils - INFO - (1/8) - Download history data for "BNB/USDT", 8h, CandleType.MARK and store in [folder_path_removed_for privacy]\freqtrade\user_data\data\binance. From 2021-01-01T05:30:00 to now
2023-02-25 05:15:11,431 - freqtrade.exchange.exchange - INFO - Downloaded data for BNB/USDT with length 2355.
2023-02-25 05:15:11,490 - freqtrade.data.history.history_utils - INFO - Downloading pair BTC/USDT, interval 1m.
2023-02-25 05:15:11,493 - freqtrade.data.history.history_utils - INFO - (2/8) - Download history data for "BTC/USDT", 1m, CandleType.FUTURES and store in [folder_path_removed_for privacy]\freqtrade\user_data\data\binance. From 2021-01-01T05:30:00 to now
2023-02-25 05:16:14,955 - freqtrade.exchange.exchange - INFO - Downloaded data for BTC/USDT with length 1130387.
2023-02-25 05:16:18,210 - freqtrade.data.history.history_utils - INFO - (2/8) - Download history data for "BTC/USDT", 8h, CandleType.FUNDING_RATE and store in [folder_path_removed_for privacy]\freqtrade\user_data\data\binance. From 2021-01-01T05:30:00 to now
2023-02-25 05:16:19,525 - freqtrade.exchange.exchange - INFO - Downloaded data for BTC/USDT with length 0.
2023-02-25 05:16:19,571 - freqtrade.data.history.history_utils - INFO - (2/8) - Download history data for "BTC/USDT", 8h, CandleType.MARK and store in [folder_path_removed_for privacy]\freqtrade\user_data\data\binance. From 2021-01-01T05:30:00 to now
2023-02-25 05:16:21,467 - freqtrade.exchange.exchange - INFO - Downloaded data for BTC/USDT with length 2355.
2023-02-25 05:16:21,543 - freqtrade.data.history.history_utils - INFO - Downloading pair ETH/USDT, interval 1m.
2023-02-25 05:16:21,546 - freqtrade.data.history.history_utils - INFO - (3/8) - Download history data for "ETH/USDT", 1m, CandleType.FUTURES and store in [folder_path_removed_for privacy]\freqtrade\user_data\data\binance. From 2021-01-01T05:30:00 to now
2023-02-25 05:17:23,032 - freqtrade.exchange.exchange - INFO - Downloaded data for ETH/USDT with length 1130388.
2023-02-25 05:17:26,324 - freqtrade.data.history.history_utils - INFO - (3/8) - Download history data for "ETH/USDT", 8h, CandleType.FUNDING_RATE and store in [folder_path_removed_for privacy]\freqtrade\user_data\data\binance. From 2021-01-01T05:30:00 to now
2023-02-25 05:17:27,827 - freqtrade.exchange.exchange - INFO - Downloaded data for ETH/USDT with length 0.
2023-02-25 05:17:27,861 - freqtrade.data.history.history_utils - INFO - (3/8) - Download history data for "ETH/USDT", 8h, CandleType.MARK and store in [folder_path_removed_for privacy]\freqtrade\user_data\data\binance. From 2021-01-01T05:30:00 to now
2023-02-25 05:17:29,671 - freqtrade.exchange.exchange - INFO - Downloaded data for ETH/USDT with length 2355.
2023-02-25 05:17:29,747 - freqtrade.data.history.history_utils - INFO - Downloading pair CFX/USDT, interval 1m.
2023-02-25 05:17:29,750 - freqtrade.data.history.history_utils - INFO - (4/8) - Download history data for "CFX/USDT", 1m, CandleType.FUTURES and store in [folder_path_removed_for privacy]\freqtrade\user_data\data\binance. From 2021-01-01T05:30:00 to now
2023-02-25 05:17:30,183 - freqtrade.exchange.binance - INFO - Candle-data for CFX/USDT available starting with 2021-03-29T11:00:00+00:00.
2023-02-25 05:18:24,459 - freqtrade.exchange.exchange - INFO - Downloaded data for CFX/USDT with length 1004449.
2023-02-25 05:18:27,230 - freqtrade.data.history.history_utils - INFO - (4/8) - Download history data for "CFX/USDT", 8h, CandleType.FUNDING_RATE and store in [folder_path_removed_for privacy]\freqtrade\user_data\data\binance. From 2021-01-01T05:30:00 to now
2023-02-25 05:18:28,439 - freqtrade.exchange.exchange - INFO - Downloaded data for CFX/USDT with length 0.
2023-02-25 05:18:28,483 - freqtrade.data.history.history_utils - INFO - (4/8) - Download history data for "CFX/USDT", 8h, CandleType.MARK and store in [folder_path_removed_for privacy]\freqtrade\user_data\data\binance. From 2021-01-01T05:30:00 to now
2023-02-25 05:18:29,054 - freqtrade.exchange.binance - INFO - Candle-data for CFX/USDT available starting with 2023-02-20T00:00:00+00:00.
2023-02-25 05:18:29,771 - freqtrade.exchange.exchange - INFO - Downloaded data for CFX/USDT with length 15.
2023-02-25 05:18:29,817 - freqtrade.data.history.history_utils - INFO - Downloading pair SOL/USDT, interval 1m.
2023-02-25 05:18:29,820 - freqtrade.data.history.history_utils - INFO - (5/8) - Download history data for "SOL/USDT", 1m, CandleType.FUTURES and store in [folder_path_removed_for privacy]\freqtrade\user_data\data\binance. From 2021-01-01T05:30:00 to now
2023-02-25 05:19:36,835 - freqtrade.exchange.exchange - INFO - Downloaded data for SOL/USDT with length 1130390.
2023-02-25 05:19:39,749 - freqtrade.data.history.history_utils - INFO - (5/8) - Download history data for "SOL/USDT", 8h, CandleType.FUNDING_RATE and store in [folder_path_removed_for privacy]\freqtrade\user_data\data\binance. From 2021-01-01T05:30:00 to now
2023-02-25 05:19:41,434 - freqtrade.exchange.exchange - INFO - Downloaded data for SOL/USDT with length 0.
2023-02-25 05:19:41,479 - freqtrade.data.history.history_utils - INFO - (5/8) - Download history data for "SOL/USDT", 8h, CandleType.MARK and store in [folder_path_removed_for privacy]\freqtrade\user_data\data\binance. From 2021-01-01T05:30:00 to now
2023-02-25 05:19:43,075 - freqtrade.exchange.exchange - INFO - Downloaded data for SOL/USDT with length 2355.
2023-02-25 05:19:43,144 - freqtrade.data.history.history_utils - INFO - Downloading pair LTC/USDT, interval 1m.
2023-02-25 05:19:43,146 - freqtrade.data.history.history_utils - INFO - (6/8) - Download history data for "LTC/USDT", 1m, CandleType.FUTURES and store in [folder_path_removed_for privacy]\freqtrade\user_data\data\binance. From 2021-01-01T05:30:00 to now
2023-02-25 05:20:45,230 - freqtrade.exchange.exchange - INFO - Downloaded data for LTC/USDT with length 1130391.
2023-02-25 05:20:48,144 - freqtrade.data.history.history_utils - INFO - (6/8) - Download history data for "LTC/USDT", 8h, CandleType.FUNDING_RATE and store in [folder_path_removed_for privacy]\freqtrade\user_data\data\binance. From 2021-01-01T05:30:00 to now
2023-02-25 05:20:49,334 - freqtrade.exchange.exchange - INFO - Downloaded data for LTC/USDT with length 0.
2023-02-25 05:20:49,379 - freqtrade.data.history.history_utils - INFO - (6/8) - Download history data for "LTC/USDT", 8h, CandleType.MARK and store in [folder_path_removed_for privacy]\freqtrade\user_data\data\binance. From 2021-01-01T05:30:00 to now
2023-02-25 05:20:51,167 - freqtrade.exchange.exchange - INFO - Downloaded data for LTC/USDT with length 2355.
2023-02-25 05:20:51,233 - freqtrade.data.history.history_utils - INFO - Downloading pair DOGE/USDT, interval 1m.
2023-02-25 05:20:51,236 - freqtrade.data.history.history_utils - INFO - (7/8) - Download history data for "DOGE/USDT", 1m, CandleType.FUTURES and store in [folder_path_removed_for privacy]\freqtrade\user_data\data\binance. From 2021-01-01T05:30:00 to now
2023-02-25 05:21:52,724 - freqtrade.exchange.exchange - INFO - Downloaded data for DOGE/USDT with length 1130392.
2023-02-25 05:21:55,550 - freqtrade.data.history.history_utils - INFO - (7/8) - Download history data for "DOGE/USDT", 8h, CandleType.FUNDING_RATE and store in [folder_path_removed_for privacy]\freqtrade\user_data\data\binance. From 2021-01-01T05:30:00 to now
2023-02-25 05:21:56,599 - freqtrade.exchange.exchange - INFO - Downloaded data for DOGE/USDT with length 0.
2023-02-25 05:21:56,648 - freqtrade.data.history.history_utils - INFO - (7/8) - Download history data for "DOGE/USDT", 8h, CandleType.MARK and store in [folder_path_removed_for privacy]\freqtrade\user_data\data\binance. From 2021-01-01T05:30:00 to now
2023-02-25 05:21:58,441 - freqtrade.exchange.exchange - INFO - Downloaded data for DOGE/USDT with length 2355.
2023-02-25 05:21:58,507 - freqtrade.data.history.history_utils - INFO - Downloading pair XTZ/USDT, interval 1m.
2023-02-25 05:21:58,509 - freqtrade.data.history.history_utils - INFO - (8/8) - Download history data for "XTZ/USDT", 1m, CandleType.FUTURES and store in [folder_path_removed_for privacy]\freqtrade\user_data\data\binance. From 2021-01-01T05:30:00 to now
2023-02-25 05:22:59,785 - freqtrade.exchange.exchange - INFO - Downloaded data for XTZ/USDT with length 1130393.
2023-02-25 05:23:02,661 - freqtrade.data.history.history_utils - INFO - (8/8) - Download history data for "XTZ/USDT", 8h, CandleType.FUNDING_RATE and store in [folder_path_removed_for privacy]\freqtrade\user_data\data\binance. From 2021-01-01T05:30:00 to now
2023-02-25 05:23:03,578 - freqtrade.exchange.exchange - INFO - Downloaded data for XTZ/USDT with length 0.
2023-02-25 05:23:03,628 - freqtrade.data.history.history_utils - INFO - (8/8) - Download history data for "XTZ/USDT", 8h, CandleType.MARK and store in [folder_path_removed_for privacy]\freqtrade\user_data\data\binance. From 2021-01-01T05:30:00 to now
2023-02-25 05:23:05,411 - freqtrade.exchange.exchange - INFO - Downloaded data for XTZ/USDT with length 2355.
```

#### Terminal Log for `backtesting` command:-
  ```
  2023-02-25 05:46:32,046 - freqtrade - INFO - freqtrade 2023.2.dev-cdc96136b
2023-02-25 05:46:32,049 - freqtrade.configuration.load_config - INFO - Using config: config.json ...
2023-02-25 05:46:32,050 - freqtrade.loggers - INFO - Verbosity set to 0
2023-02-25 05:46:32,051 - freqtrade.configuration.configuration - INFO - Parameter --enable-position-stacking detected ...
2023-02-25 05:46:32,051 - freqtrade.configuration.configuration - INFO - Parameter --enable-protections detected, enabling Protections. ...
2023-02-25 05:46:32,051 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 4 ...
2023-02-25 05:46:32,051 - freqtrade.configuration.configuration - INFO - Parameter --timerange detected: 20210101- ...
2023-02-25 05:46:32,052 - freqtrade.configuration.configuration - INFO - Using user-data directory: [folder_path_removed_for privacy]\freqtrade\user_data ...
2023-02-25 05:46:32,053 - freqtrade.configuration.configuration - INFO - Using data directory: [folder_path_removed_for privacy]\freqtrade\user_data\data\binance ...
2023-02-25 05:46:32,053 - freqtrade.configuration.configuration - INFO - Parameter --cache=day detected ...
2023-02-25 05:46:32,054 - freqtrade.configuration.configuration - INFO - Using pairs ['BNB/USDT:USDT', 'BTC/USDT:USDT', 'ETH/USDT:USDT', 'CFX/USDT:USDT', 'SOL/USDT:USDT', 'LTC/USDT:USDT', 'DOGE/USDT:USDT', 'XTZ/USDT']
2023-02-25 05:46:32,054 - freqtrade.configuration.configuration - INFO - Using "hdf5" to store OHLCV data.
2023-02-25 05:46:32,054 - freqtrade.configuration.configuration - INFO - Filter trades by timerange: 20210101-
2023-02-25 05:46:32,055 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2023-02-25 05:46:32,066 - freqtrade.exchange.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2023-02-25 05:46:32,067 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2023-02-25 05:46:32,072 - freqtrade.commands.optimize_commands - INFO - Starting freqtrade in Backtesting mode
2023-02-25 05:46:32,073 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2023-02-25 05:46:32,074 - freqtrade.exchange.exchange - INFO - Using CCXT 2.8.17
2023-02-25 05:46:32,074 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}}
2023-02-25 05:46:32,084 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}}
2023-02-25 05:46:32,096 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2023-02-25 05:46:35,040 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2023-02-25 05:46:35,063 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy SampleStrategy from '[folder_path_removed_for privacy]\freqtrade\user_data\strategies\sample_strategy.py'...
2023-02-25 05:46:35,064 - freqtrade.strategy.hyper - INFO - Found no parameter file.
2023-02-25 05:46:35,064 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2023-02-25 05:46:35,065 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: unlimited.
2023-02-25 05:46:35,065 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}.
2023-02-25 05:46:35,065 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'max_open_trades' with value in config file: 4.
2023-02-25 05:46:35,066 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'60': 0.01, '30': 0.02, '0': 0.04}
2023-02-25 05:46:35,066 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 1m
2023-02-25 05:46:35,066 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.1
2023-02-25 05:46:35,066 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: True
2023-02-25 05:46:35,067 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2023-02-25 05:46:35,067 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2023-02-25 05:46:35,067 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2023-02-25 05:46:35,068 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: True
2023-02-25 05:46:35,068 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'entry': 'limit', 'exit': 'limit', 'stoploss': 'market', 'stoploss_on_exchange': False}
2023-02-25 05:46:35,068 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'entry': 'GTC', 'exit': 'GTC'}
2023-02-25 05:46:35,068 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2023-02-25 05:46:35,069 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: unlimited
2023-02-25 05:46:35,069 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2023-02-25 05:46:35,069 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 30
2023-02-25 05:46:35,070 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}
2023-02-25 05:46:35,070 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_exit_signal: True
2023-02-25 05:46:35,070 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_only: False
2023-02-25 05:46:35,071 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_entry_signal: False
2023-02-25 05:46:35,071 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_offset: 0.0
2023-02-25 05:46:35,071 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2023-02-25 05:46:35,071 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2023-02-25 05:46:35,072 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: False
2023-02-25 05:46:35,072 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1
2023-02-25 05:46:35,072 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_open_trades: 4
2023-02-25 05:46:35,073 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2023-02-25 05:46:35,092 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from '[folder_path_removed_for privacy]\freqtrade\freqtrade\plugins\pairlist\StaticPairList.py'...
2023-02-25 05:46:35,106 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "[folder_path_removed_for privacy]\freqtrade\freqtrade\main.py", line 42, in main
    return_code = args['func'](args)
                  ^^^^^^^^^^^^^^^^^^
  File "[folder_path_removed_for privacy]\freqtrade\freqtrade\commands\optimize_commands.py", line 57, in start_backtesting
    backtesting = Backtesting(config)
                  ^^^^^^^^^^^^^^^^^^^
  File "[folder_path_removed_for privacy]\freqtrade\freqtrade\optimize\backtesting.py", line 161, in __init__
    migrate_binance_futures_data(config)
  File "[folder_path_removed_for privacy]\freqtrade\freqtrade\util\binance_mig.py", line 68, in migrate_binance_futures_data
    paircombs = dhc.ohlcv_get_available_data(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[folder_path_removed_for privacy]\freqtrade\freqtrade\data\history\idatahandler.py", line 56, in ohlcv_get_available_data
    return [
           ^
  File "[folder_path_removed_for privacy]\freqtrade\freqtrade\data\history\idatahandler.py", line 60, in <listcomp>
    CandleType.from_string(match[3])
  File "[folder_path_removed_for privacy]\freqtrade\freqtrade\enums\candletype.py", line 21, in from_string
    return CandleType(value)
           ^^^^^^^^^^^^^^^^^
  File "D:\C\Program Files\Python311\Lib\enum.py", line 695, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\C\Program Files\Python311\Lib\enum.py", line 1111, in __new__
    raise ve_exc
ValueError: 'CandleType' is not a valid CandleType
  ```

**Comment by stash86** [comment]
Can you give the logs when you download the data?

**Comment by ET205** [comment]
> Can you give the logs when you download the data?

I've updated the logs.

**Comment by xmatthias** [comment]
the error / exception is clear - the data in the data-directory is named wrongly. Removing / deleting the data will fix that part - but i suspect a subsequent download-data will cause the same thing.

Now my first (and for now only) suspicion is that it's to do with python 3.11, which we don't support yet (for dependency reasons, mostly) - but also didn't test against so far.

I'd recommend to
* delete the downloaded data (`rm -r user_data/data/*`) 
* install and use freqtrade with python 3.10

**Comment by stash86** [comment]
Try re-download the data, but the pairs' name change to the correct format, for example `BTC/USDT:USDT`

**Comment by ET205** [comment]
> the error / exception is clear - the data in the data-directory is named wrongly. Removing / deleting the data will fix that part - but i suspect a subsequent download-data will cause the same thing.
> 
> Now my first (and for now only) suspicion is that it's to do with python 3.11, which we don't support yet (for dependency reasons, mostly) - but also didn't test against so far.
> 
> I'd recommend to
> 
> * delete the downloaded data (`rm -r user_data/data/*`)
> * install and use freqtrade with python 3.10

Really? I assumed 3.11 was supported when I saw the prebuilt wheel for Ta-Lib in the freqtrade files (which I was looking for everywhere since I can't get it to build).

Anyway, I had the same thought at this point, will give it a try and update.

On the other hand, I do want to keep Python 3.11 for the speedup that comes with it, if possible.

**Comment by ET205** [comment]
> Try re-download the data, but the pairs' name change to the correct format, for example `BTC/USDT:USDT`

Trying this first before I switch Python versions. Downloading right now. The file names do seem to be different. Will update.

**Comment by ET205** [comment]
> > Try re-download the data, but the pairs' name change to the correct format, for example `BTC/USDT:USDT`
> 
> Trying this first before I switch Python versions. Downloading right now. The file names do seem to be different. Will update.

Same result.

**Comment by ET205** [comment]
> > the error / exception is clear - the data in the data-directory is named wrongly. Removing / deleting the data will fix that part - but i suspect a subsequent download-data will cause the same thing.
> > Now my first (and for now only) suspicion is that it's to do with python 3.11, which we don't support yet (for dependency reasons, mostly) - but also didn't test against so far.
> > I'd recommend to
> > 
> > * delete the downloaded data (`rm -r user_data/data/*`)
> > * install and use freqtrade with python 3.10
> 
> Really? I assumed 3.11 was supported when I saw the prebuilt wheel for Ta-Lib in the freqtrade files (which I was looking for everywhere since I can't get it to build).
> 
> Anyway, I had the same thought at this point, will give it a try and update.
> 
> On the other hand, I do want to keep Python 3.11 for the speedup that comes with it, if possible.

Also, same result.

#### Edit:-

Nope, I somehow managed to skip over the "delete old data" part and tried running with the data that was already downloaded. My bad. Doing a re-download with Python 3.10 now. Will update.

**Comment by ET205** [comment]
I gave it another try with timerange for both `data-download` and `backtesting` set to `20230201-` in Python 3.10 and 3.11. No errors, nothing. It works!

But it still isn't working with data from `20210101-` timerange in either of the Python versions. Seems like a bug?

#### Edit:-
Spoke too soon. The Python 3.11 backtest was still running, but in the end it still gave the same issue with the new timerange (`20230201-`). So looks like it's just Python 3.11 causing the issue for now. Still running the Python 3.10 test with `20210101-` timerange.

How long before Python 3.11 is fully tested/supported?

**Comment by xmatthias** [comment]
based on speed certain dependencies move - probably months (if not years).

reduced compatibility (excluding some functions) may be available at some point - but i don't see a reason to rush - python 3.10 is still actively supported for quite a long time.

**Comment by xmatthias** [comment]
While the commit closing this issue does fix **this** particular problem (different behavior of enum's in fstrings on 3.11) - that won't guarantee correct functioning on python 3.11.
