### ISSUE TITLE
HyperOpt fails in conda installs

### ISSUE THREAD

**Issue by aloksaurabh** [freqtrade/freqtrade#8223]
## Environment

  * Operating system: `Linux kaliSSD 6.0.0-kali6-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.0.12-1kali1 (2022-12-19) x86_64 GNU/Linux`
  * Python Version: Python 3.10.0
  * CCXT version: ccxt==2.8.31
  * Freqtrade Version: freqtrade 2023.2.dev-0f878daa9 ; also happens in current stable
  * Conda Environment
```
# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
_libgcc_mutex=0.1=conda_forge
_openmp_mutex=4.5=2_gnu
_py-xgboost-mutex=2.0=cpu_0
absl-py=1.4.0=pyhd8ed1ab_0
aiodns=3.0.0=pypi_0
aiofiles=23.1.0=pyhd8ed1ab_0
aiohttp=3.8.4=py310h1fa729e_0
aiosignal=1.3.1=pyhd8ed1ab_0
alsa-lib=1.2.8=h166bdaf_0
anyio=3.6.2=pyhd8ed1ab_0
appdirs=1.4.4=pyh9f0ad1d_0
apscheduler=3.6.3=pypi_0
argon2-cffi=21.3.0=pyhd8ed1ab_0
argon2-cffi-bindings=21.2.0=py310h5764c6d_3
arrow=1.2.3=pyhd8ed1ab_0
arrow-cpp=11.0.0=ha770c72_5_cpu
asttokens=2.2.1=pyhd8ed1ab_0
astunparse=1.6.3=pyhd8ed1ab_0
async-timeout=4.0.2=pyhd8ed1ab_0
attr=2.5.1=h166bdaf_1
attrs=22.2.0=pyh71513ae_0
aws-c-auth=0.6.24=h565b4ff_3
aws-c-cal=0.5.20=h679401e_5
aws-c-common=0.8.10=h0b41bf4_0
aws-c-compression=0.2.16=hbe6ad0c_2
aws-c-event-stream=0.2.18=h489b7ba_4
aws-c-http=0.7.4=hb2c4a47_0
aws-c-io=0.13.15=head7655_1
aws-c-mqtt=0.8.6=haf0be06_4
aws-c-s3=0.2.4=h05be983_1
aws-c-sdkutils=0.1.7=hbe6ad0c_2
aws-checksums=0.1.14=hbe6ad0c_2
aws-crt-cpp=0.19.7=h9b63b7c_4
aws-sdk-cpp=1.10.57=hd557813_3
backcall=0.2.0=pyh9f0ad1d_0
backports=1.0=pyhd8ed1ab_3
backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
beautifulsoup4=4.11.2=pyha770c72_0
blas=1.0=mkl
bleach=6.0.0=pyhd8ed1ab_0
blinker=1.5=pyhd8ed1ab_0
blosc=1.21.3=hafa529b_0
blosc2=2.0.0=pypi_0
brotli=1.0.9=h166bdaf_8
brotli-bin=1.0.9=h166bdaf_8
brotlipy=0.7.0=py310h5764c6d_1005
bzip2=1.0.8=h7f98852_4
c-ares=1.18.1=h7f98852_0
ca-certificates=2023.01.10=h06a4308_0
cached-property=1.5.2=hd8ed1ab_1
cached_property=1.5.2=pyha770c72_1
cachetools=4.2.2=pypi_0
cairo=1.16.0=ha61ee94_1014
catboost=1.1.1=pypi_0
ccxt=2.8.31=pypi_0
certifi=2022.12.7=py310h06a4308_0
cffi=1.15.1=py310h255011f_3
charset-normalizer=2.1.1=pyhd8ed1ab_0
click=8.1.3=unix_pyhd8ed1ab_2
cloudpickle=2.2.1=pypi_0
cmdstanpy=1.1.0=pypi_0
colorama=0.4.6=pyhd8ed1ab_0
comm=0.1.2=pyhd8ed1ab_0
contourpy=1.0.7=py310hdf3cbec_0
convertdate=2.4.0=pypi_0
coverage=6.5.0=py310h5764c6d_1
coveralls=3.3.1=pyhd8ed1ab_0
cryptography=39.0.1=py310h34c0648_0
cuda-nvcc=12.0.140=0
cudatoolkit=11.8.0=h37601d7_11
cudnn=8.4.1.50=hed8a83a_0
cycler=0.11.0=pyhd8ed1ab_0
cython=0.29.33=pypi_0
darts=0.23.1=pypi_0
dbus=1.13.6=h5008d03_3
debugpy=1.6.6=py310heca2aa9_0
decorator=5.1.1=pyhd8ed1ab_0
defusedxml=0.7.1=pyhd8ed1ab_0
dill=0.3.6=pyhd8ed1ab_1
distlib=0.3.6=pypi_0
docopt=0.6.2=py_1
entrypoints=0.4=pyhd8ed1ab_0
ephem=4.1.4=pypi_0
exceptiongroup=1.1.0=pyhd8ed1ab_0
executing=1.2.0=pyhd8ed1ab_0
expat=2.5.0=h27087fc_0
fastapi=0.92.0=pyhd8ed1ab_0
ffmpeg=4.3=hf484d3e_0
fftw=3.3.10=nompi_hf0379b8_106
filelock=3.9.0=pyhd8ed1ab_0
finta=1.3=pypi_0
flake8=6.0.0=pyhd8ed1ab_0
flake8-tidy-imports=4.8.0=pypi_0
flatbuffers=22.12.06=hcb278e6_2
flit-core=3.8.0=pyhd8ed1ab_0
font-ttf-dejavu-sans-mono=2.37=hab24e00_0
font-ttf-inconsolata=3.000=h77eed37_0
font-ttf-source-code-pro=2.038=h77eed37_0
font-ttf-ubuntu=0.83=hab24e00_0
fontconfig=2.14.2=h14ed4e7_0
fonts-conda-ecosystem=1=0
fonts-conda-forge=1=0
fonttools=4.38.0=py310h5764c6d_1
freetype=2.12.1=hca18f0e_1
freqtrade=2023.2.dev0=pypi_0
frozenlist=1.3.3=py310h5764c6d_0
fsspec=2023.1.0=pypi_0
gast=0.4.0=pyh9f0ad1d_0
gettext=0.21.1=h27087fc_0
gflags=2.2.2=he1b5a44_1004
giflib=5.2.1=h36c2ea0_2
glib=2.74.1=h6239696_1
glib-tools=2.74.1=h6239696_1
glog=0.6.0=h6f12383_0
gmp=6.2.1=h295c915_3
gnutls=3.6.15=he1e5248_0
google-auth=2.16.1=pyh1a96a4e_0
google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
google-pasta=0.2.0=pyh8c360ce_0
graphite2=1.3.13=h58526e2_1001
greenlet=2.0.2=py310heca2aa9_0
grpcio=1.51.1=py310h4a5735c_1
gst-plugins-base=1.22.0=h4243ec0_0
gstreamer=1.22.0=h25f0c4b_0
gstreamer-orc=0.4.33=h166bdaf_0
h11=0.14.0=pyhd8ed1ab_0
h2=4.1.0=pyhd8ed1ab_0
h5py=3.8.0=nompi_py310ha66b2ad_101
harfbuzz=6.0.0=h8e241bc_0
hdf5=1.14.0=nompi_hb72d44e_102
hijri-converter=2.2.4=pypi_0
holidays=0.19=pypi_0
hpack=4.0.0=pyh9f0ad1d_0
httpcore=0.16.3=pyhd8ed1ab_0
httpx=0.23.3=pyhd8ed1ab_0
hyperframe=6.0.1=pyhd8ed1ab_0
icu=70.1=h27087fc_0
idna=3.4=pyhd8ed1ab_0
importlib-metadata=6.0.0=pyha770c72_0
importlib_metadata=6.0.0=hd8ed1ab_0
importlib_resources=5.12.0=pyhd8ed1ab_0
iniconfig=2.0.0=pyhd8ed1ab_0
intel-openmp=2021.4.0=h06a4308_3561
ipykernel=6.21.2=pyh210e3f2_0
ipython=8.10.0=pyh41d4057_0
ipython_genutils=0.2.0=py_1
ipywidgets=8.0.4=pyhd8ed1ab_0
isort=5.12.0=pyhd8ed1ab_1
jack=1.9.22=h11f4161_0
janus=1.0.0=pypi_0
jedi=0.18.2=pyhd8ed1ab_0
jinja2=3.1.2=pyhd8ed1ab_1
joblib=1.2.0=pyhd8ed1ab_0
jpeg=9e=h0b41bf4_3
jsonschema=4.17.3=pyhd8ed1ab_0
jupyter=1.0.0=py310hff52083_8
jupyter_client=8.0.3=pyhd8ed1ab_0
jupyter_console=6.6.1=pyhd8ed1ab_0
jupyter_core=5.2.0=py310hff52083_0
jupyter_events=0.6.3=pyhd8ed1ab_0
jupyter_server=2.3.0=pyhd8ed1ab_0
jupyter_server_terminals=0.4.4=pyhd8ed1ab_1
jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
jupyterlab_widgets=3.0.5=pyhd8ed1ab_0
keras=2.11.0=pyhd8ed1ab_0
keras-preprocessing=1.1.2=pyhd8ed1ab_0
keyutils=1.6.1=h166bdaf_0
kiwisolver=1.4.4=py310hbf28c38_1
korean-lunar-calendar=0.3.1=pypi_0
krb5=1.20.1=h81ceb04_0
lame=3.100=h166bdaf_1003
lcms2=2.14=hfd0df8a_1
ld_impl_linux-64=2.40=h41732ed_0
lerc=4.0.0=h27087fc_0
libabseil=20220623.0=cxx17_h05df665_6
libaec=1.0.6=hcb278e6_1
libarrow=11.0.0=h2ebd325_5_cpu
libbrotlicommon=1.0.9=h166bdaf_8
libbrotlidec=1.0.9=h166bdaf_8
libbrotlienc=1.0.9=h166bdaf_8
libcap=2.66=ha37c62d_0
libclang=15.0.7=default_had23c3d_1
libclang13=15.0.7=default_h3e3d535_1
libcrc32c=1.1.2=h9c3ff4c_0
libcups=2.3.3=h36d4200_3
libcurl=7.88.1=hdc1c0ab_0
libdb=6.2.32=h9c3ff4c_0
libdeflate=1.17=h0b41bf4_0
libedit=3.1.20191231=he28a2e2_2
libev=4.33=h516909a_1
libevent=2.1.10=h28343ad_4
libffi=3.4.2=h7f98852_5
libflac=1.4.2=h27087fc_0
libgcc-ng=12.2.0=h65d4601_19
libgcrypt=1.10.1=h166bdaf_0
libgfortran-ng=12.2.0=h69a702a_19
libgfortran5=12.2.0=h337968e_19
libglib=2.74.1=h606061b_1
libgomp=12.2.0=h65d4601_19
libgoogle-cloud=2.7.0=h21dfe5b_1
libgpg-error=1.46=h620e276_0
libgrpc=1.51.1=h4fad500_1
libiconv=1.17=h166bdaf_0
libidn2=2.3.2=h7f8727e_0
libllvm15=15.0.7=hadd5161_0
libnghttp2=1.51.0=hff17c54_0
libnsl=2.0.0=h7f98852_0
libogg=1.3.4=h7f98852_1
libopenblas=0.3.21=pthreads_h78a6416_3
libopus=1.3.1=h7f98852_1
libpng=1.6.39=h753d276_0
libpq=15.2=hb675445_0
libprotobuf=3.21.12=h3eb15da_0
libsndfile=1.2.0=hb75c966_0
libsodium=1.0.18=h36c2ea0_1
libsqlite=3.40.0=h753d276_0
libssh2=1.10.0=hf14f497_3
libstdcxx-ng=12.2.0=h46fd767_19
libsystemd0=252=h2a991cd_0
libta-lib=0.4.0=h166bdaf_1
libtasn1=4.16.0=h27cfd23_0
libthrift=0.18.0=h5e4af38_0
libtiff=4.5.0=h6adf6a1_2
libtool=2.4.7=h27087fc_0
libudev1=252=h166bdaf_0
libunistring=0.9.10=h27cfd23_0
libutf8proc=2.8.0=h166bdaf_0
libuuid=2.32.1=h7f98852_1000
libvorbis=1.3.7=h9c3ff4c_0
libwebp-base=1.2.4=h166bdaf_0
libxcb=1.13=h7f98852_1004
libxgboost=1.7.3=h6a678d5_0
libxkbcommon=1.5.0=h79f4944_0
libxml2=2.10.3=h7463322_0
libzlib=1.2.13=h166bdaf_4
lightgbm=3.3.5=pypi_0
lightning-utilities=0.7.1=pypi_0
llvmlite=0.39.1=pypi_0
lunarcalendar=0.0.9=pypi_0
lz4-c=1.9.4=hcb278e6_0
markdown=3.4.1=pyhd8ed1ab_0
markupsafe=2.1.2=py310h1fa729e_0
matplotlib-base=3.7.0=py310he60537e_0
matplotlib-inline=0.1.6=pyhd8ed1ab_0
mccabe=0.7.0=pyhd8ed1ab_0
mistune=2.0.5=pyhd8ed1ab_0
mkl=2021.4.0=h06a4308_640
mkl-service=2.4.0=py310h7f8727e_0
mkl_fft=1.3.1=py310hd6ae3a3_0
mkl_random=1.2.2=py310h00e6091_0
mpg123=1.31.2=hcb278e6_0
msgpack=1.0.4=pypi_0
multidict=6.0.4=py310h1fa729e_0
multiprocess=0.70.14=py310h5764c6d_3
munkres=1.1.4=pyh9f0ad1d_0
mypy=1.0.1=py310h1fa729e_0
mypy_extensions=1.0.0=pyha770c72_0
mysql-common=8.0.32=ha901b37_0
mysql-libs=8.0.32=hd7da12d_0
nbclassic=0.5.2=pyhd8ed1ab_0
nbclient=0.7.2=pyhd8ed1ab_0
nbconvert=7.2.9=pyhd8ed1ab_0
nbconvert-core=7.2.9=pyhd8ed1ab_0
nbconvert-pandoc=7.2.9=pyhd8ed1ab_0
nbformat=5.7.3=pyhd8ed1ab_0
nccl=2.14.3.1=h0800d71_0
ncurses=6.3=h27087fc_1
nest-asyncio=1.5.6=pyhd8ed1ab_0
nettle=3.7.3=hbbd107a_1
nfoursid=1.0.1=pypi_0
notebook=6.5.2=pyha770c72_1
notebook-shim=0.2.2=pyhd8ed1ab_0
nspr=4.35=h27087fc_0
nss=3.88=he45b914_0
numba=0.56.4=pypi_0
numexpr=2.8.4=pypi_0
numpy=1.23.5=py310hd5efca6_0
numpy-base=1.23.5=py310h8e6c178_0
oauthlib=3.2.2=pyhd8ed1ab_0
openh264=2.1.1=h4ff587b_0
openjpeg=2.5.0=hfec8fc6_2
openssl=3.0.8=h0b41bf4_0
opt_einsum=3.3.0=pyhd8ed1ab_1
orc=1.8.2=hfdbbad2_2
orjson=3.8.6=pypi_0
packaging=23.0=pyhd8ed1ab_0
pandas=1.5.3=py310h9b08913_0
pandas-ta=0.3.14b0=pypi_0
pandoc=2.19.2=h32600fe_1
pandocfilters=1.5.0=pyhd8ed1ab_0
parquet-cpp=1.5.1=2
parso=0.8.3=pyhd8ed1ab_0
patsy=0.5.3=py310h06a4308_0
pcre2=10.40=hc3806b6_0
pexpect=4.8.0=pyh1a96a4e_2
pickleshare=0.7.5=py_1003
pillow=9.4.0=py310h023d228_1
pip=23.0.1=pyhd8ed1ab_0
pixman=0.40.0=h36c2ea0_0
pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
platformdirs=3.0.0=pyhd8ed1ab_0
plotly=5.13.0=pyhd8ed1ab_0
pluggy=1.0.0=pyhd8ed1ab_5
ply=3.11=py_1
pmdarima=2.0.2=pypi_0
pooch=1.6.0=pyhd8ed1ab_0
prettytable=3.6.0=pypi_0
progressbar2=4.2.0=pyhd8ed1ab_0
prometheus_client=0.16.0=pyhd8ed1ab_0
prompt-toolkit=3.0.36=pyha770c72_0
prompt_toolkit=3.0.36=hd8ed1ab_0
prophet=1.1.2=pypi_0
protobuf=3.20.1=pypi_0
psutil=5.9.4=py310h5764c6d_0
pthread-stubs=0.4=h36c2ea0_1001
ptyprocess=0.7.0=pyhd3deb0d_0
pulseaudio=16.1=ha8d29e2_1
pure_eval=0.2.2=pyhd8ed1ab_0
py-cpuinfo=9.0.0=pypi_0
py-find-1st=1.1.5=py310hbf28c38_3
py-xgboost=1.7.3=py310h06a4308_0
pyaml=21.10.1=pyhd8ed1ab_0
pyarrow=11.0.0=py310h633f555_5_cpu
pyasn1=0.4.8=py_0
pyasn1-modules=0.2.7=py_0
pycares=4.3.0=pypi_0
pycodestyle=2.10.0=pyhd8ed1ab_0
pycoingecko=3.1.0=pypi_0
pycparser=2.21=pyhd8ed1ab_0
pydantic=1.10.5=py310h1fa729e_0
pydeprecate=0.3.2=pypi_0
pyflakes=3.0.1=pyhd8ed1ab_0
pygments=2.14.0=pyhd8ed1ab_0
pyjwt=2.6.0=pyhd8ed1ab_0
pykalman=0.9.5=pypi_0
pymeeus=0.5.12=pypi_0
pyod=1.0.7=pypi_0
pyopenssl=23.0.0=pyhd8ed1ab_0
pyparsing=3.0.9=pyhd8ed1ab_0
pyqt=5.15.7=py310hab646b1_3
pyqt5-sip=12.11.0=py310heca2aa9_3
pyrsistent=0.19.3=py310h1fa729e_0
pysocks=1.7.1=pyha2e5f31_6
pytest=7.2.1=pyhd8ed1ab_0
pytest-asyncio=0.20.3=pyhd8ed1ab_0
pytest-cov=4.0.0=pyhd8ed1ab_0
pytest-mock=3.10.0=pyhd8ed1ab_0
pytest-random-order=1.1.0=pypi_0
python=3.10.0=h543edf9_3_cpython
python-dateutil=2.8.2=pyhd8ed1ab_0
python-fastjsonschema=2.16.2=pyhd8ed1ab_0
python-flatbuffers=23.1.21=pyhd8ed1ab_0
python-graphviz=0.20.1=pypi_0
python-json-logger=2.0.7=pyhd8ed1ab_0
python-rapidjson=1.9=pypi_0
python-telegram-bot=13.15=pyhd8ed1ab_0
python-utils=3.5.2=pyhd8ed1ab_0
python_abi=3.10=3_cp310
pytorch=1.13.1=py3.10_cpu_0
pytorch-lightning=1.6.5=pypi_0
pytorch-mutex=1.0=cpu
pytz=2022.7.1=pyhd8ed1ab_0
pytz-deprecation-shim=0.1.0.post0=pypi_0
pyu2f=0.1.5=pyhd8ed1ab_0
pywavelets=1.4.1=pypi_0
pyyaml=6.0=py310h5764c6d_5
pyzmq=25.0.0=py310h059b190_0
qt-main=5.15.8=h5d23da1_6
qtconsole=5.4.0=pyhd8ed1ab_0
qtconsole-base=5.4.0=pyha770c72_0
qtpy=2.3.0=pyhd8ed1ab_0
questionary=1.10.0=pyhd8ed1ab_1
ray=2.2.0=pypi_0
ray-lightning=0.3.0=pypi_0
re2=2023.02.01=hcb278e6_0
readline=8.1.2=h0f457ee_0
requests=2.28.2=pyhd8ed1ab_0
requests-oauthlib=1.3.1=pyhd8ed1ab_0
rfc3339-validator=0.1.4=pyhd8ed1ab_0
rfc3986=1.5.0=pyhd8ed1ab_0
rfc3986-validator=0.1.1=pyh9f0ad1d_0
rsa=4.9=pyhd8ed1ab_0
s2n=1.3.35=h3358134_0
schedule=1.1.0=pyhd8ed1ab_0
scikit-learn=1.2.1=py310h6a678d5_0
scikit-optimize=0.9.0=pyhd8ed1ab_1
scipy=1.10.0=py310hd5efca6_0
sdnotify=0.3.2=py_0
send2trash=1.8.0=pyhd8ed1ab_0
setuptools=67.4.0=pyhd8ed1ab_0
shap=0.41.0=pypi_0
simdkalman=1.0.2=pypi_0
sip=6.7.7=py310heca2aa9_0
six=1.16.0=pyh6c4a22f_0
slicer=0.0.7=pypi_0
snappy=1.1.9=hbd366e4_2
sniffio=1.3.0=pyhd8ed1ab_0
soupsieve=2.3.2.post1=pyhd8ed1ab_0
sqlalchemy=2.0.4=py310h1fa729e_0
sqlite=3.40.0=h4ff8645_0
stack_data=0.6.2=pyhd8ed1ab_0
starlette=0.25.0=pyhd8ed1ab_0
statsforecast=1.4.0=pypi_0
statsmodels=0.13.5=py310ha9d4c09_1
ta=0.10.2=pyhd8ed1ab_0
ta-lib=0.4.19=py310hde88566_4
tables=3.8.0=pypi_0
tabulate=0.9.0=pyhd8ed1ab_1
tbats=1.1.2=pypi_0
technical=1.4.0=pypi_0
tenacity=8.2.1=pyhd8ed1ab_0
tensorboard=2.11.2=pyhd8ed1ab_0
tensorboard-data-server=0.6.1=py310h600f1e7_4
tensorboard-plugin-wit=1.8.1=pyhd8ed1ab_0
tensorflow=2.11.0=cuda112py310he87a039_0
tensorflow-base=2.11.0=cuda112py310h52da4a5_0
tensorflow-estimator=2.11.0=cuda112py310h37add04_0
termcolor=2.2.0=pyhd8ed1ab_0
terminado=0.17.1=pyh41d4057_0
threadpoolctl=3.1.0=pyh8a188c0_0
tinycss2=1.2.1=pyhd8ed1ab_0
tk=8.6.12=h27826a3_0
toml=0.10.2=pyhd8ed1ab_0
tomli=2.0.1=pyhd8ed1ab_0
torchmetrics=0.11.1=pypi_0
torchvision=0.14.1=py310_cpu
tornado=6.1=pypi_0
tqdm=4.64.1=py310h06a4308_0
traitlets=5.9.0=pyhd8ed1ab_0
typing-extensions=4.4.0=hd8ed1ab_0
typing_extensions=4.4.0=pyha770c72_0
tzdata=2022.7=pypi_0
tzlocal=4.2=pypi_0
unicodedata2=15.0.0=py310h5764c6d_0
urllib3=1.26.14=pyhd8ed1ab_0
uvicorn=0.20.0=py310hff52083_1
virtualenv=20.19.0=pypi_0
wcwidth=0.2.6=pyhd8ed1ab_0
webencodings=0.5.1=py_1
websocket-client=1.5.1=pyhd8ed1ab_0
websockets=10.4=pypi_0
werkzeug=2.2.3=pyhd8ed1ab_0
wheel=0.38.4=pyhd8ed1ab_0
widgetsnbextension=4.0.5=pyhd8ed1ab_0
wrapt=1.14.1=py310h5764c6d_1
xarray=2023.2.0=pypi_0
xcb-util=0.4.0=h166bdaf_0
xcb-util-image=0.4.0=h166bdaf_0
xcb-util-keysyms=0.4.0=h166bdaf_0
xcb-util-renderutil=0.3.9=h166bdaf_0
xcb-util-wm=0.4.1=h166bdaf_0
xgboost=1.7.3=py310h06a4308_0
xorg-kbproto=1.0.7=h7f98852_1002
xorg-libice=1.0.10=h7f98852_0
xorg-libsm=1.2.3=hd9c2040_1000
xorg-libx11=1.7.2=h7f98852_0
xorg-libxau=1.0.9=h7f98852_0
xorg-libxdmcp=1.1.3=h7f98852_0
xorg-libxext=1.3.4=h0b41bf4_2
xorg-libxrender=0.9.10=h7f98852_1003
xorg-renderproto=0.11.1=h7f98852_1002
xorg-xextproto=7.3.0=h0b41bf4_1003
xorg-xproto=7.0.31=h7f98852_1007
xz=5.2.6=h166bdaf_0
yaml=0.2.5=h7f98852_2
yarl=1.8.2=py310h5764c6d_0
zeromq=4.3.4=h9c3ff4c_1
zipp=3.14.0=pyhd8ed1ab_0
zlib=1.2.13=h166bdaf_4
zstd=1.5.2=h3eb15da_6

```

## Describe the problem:

Freqtrade hyperopt crashes in a conda environment. 

### Steps to reproduce:

1)Install freqtrade using steps in https://www.freqtrade.io/en/stable/installation/#installation-with-conda

2)install few more dependencies 

Optional
```
pip3 install finta prettytable PyWavelets simdkalman pykalman scipy
pip3 uninstall numba
conda install numba
pip3 install numpy<1.24
conda install -c conda-forge -y pandas jupyter
conda install tqdm statsmodels xgboost multiprocess
pip3 install ray ray_lightning ta darts
```
  
3) Run
freqtrade hyperopt --hyperopt-loss SharpeHyperOptLossDaily --strategy SampleStrategy --config ./user_data/config_ds.json -e 10 --timerange 20210101-20210201

### Observed Results:

Crash as per logs below

### Relevant code exceptions or logs

```

2023-02-25 15:25:25,716 - freqtrade.optimize.backtesting - INFO - Loading data from 2020-12-31 21:30:00 up to 2021-02-01 00:00:00 (31 days).
2023-02-25 15:25:25,716 - freqtrade.optimize.hyperopt - INFO - Dataload complete. Calculating indicators
2023-02-25 15:25:27,608 - freqtrade.optimize.hyperopt - INFO - Hyperopting with data from 2021-01-01 00:00:00 up to 2021-02-01 00:00:00 (31 days)..
2023-02-25 15:25:29,402 - freqtrade.optimize.hyperopt - INFO - Found 16 CPU cores. Let's make them scream!
2023-02-25 15:25:29,402 - freqtrade.optimize.hyperopt - INFO - Number of parallel jobs set as: -1
2023-02-25 15:25:29,402 - freqtrade.optimize.hyperopt - INFO - Using estimator ET.
2023-02-25 15:25:29,418 - freqtrade.optimize.hyperopt - INFO - Effective number of parallel workers used: 16

2023-02-25 15:25:29,691 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/media/alok/New_Volume/kali/conda/freqtrade/freqtrade/main.py", line 42, in main
    return_code = args['func'](args)
  File "/media/alok/New_Volume/kali/conda/freqtrade/freqtrade/commands/optimize_commands.py", line 107, in start_hyperopt
    hyperopt.start()
  File "/media/alok/New_Volume/kali/conda/freqtrade/freqtrade/optimize/hyperopt.py", line 629, in start
    asked, is_random = self.get_asked_points(n_points=current_jobs)
  File "/media/alok/New_Volume/kali/conda/freqtrade/freqtrade/optimize/hyperopt.py", line 502, in get_asked_points
    asked = unique_list(self.opt.ask(n_points=n_points * 5))
  File "/home/alok/miniconda3/envs/freqtrade-conda/lib/python3.10/site-packages/skopt/optimizer/optimizer.py", line 417, in ask
    opt._tell(x, y_lie)
  File "/home/alok/miniconda3/envs/freqtrade-conda/lib/python3.10/site-packages/skopt/optimizer/optimizer.py", line 536, in _tell
    est.fit(self.space.transform(self.Xi), self.yi)
  File "/home/alok/miniconda3/envs/freqtrade-conda/lib/python3.10/site-packages/sklearn/ensemble/_forest.py", line 340, in fit
    self._validate_params()
  File "/home/alok/miniconda3/envs/freqtrade-conda/lib/python3.10/site-packages/sklearn/base.py", line 581, in _validate_params
    validate_parameter_constraints(
  File "/home/alok/miniconda3/envs/freqtrade-conda/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 97, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'absolute_error', 'poisson', 'squared_error'}. Got 'mse' instead.

```

**Comment by xmatthias** [comment]
the most likely cause is an incompatible transcient scikit-learn dependency - which scikit-optimize didn't properly pin (they didn't release in years ...).

I've now pinned scikit-learn to <1.2.0 - with that the environment should work again.

**Comment by aloksaurabh** [comment]
Solved. Closing
