### ISSUE TITLE
HyperOpt Carsh in Short strategies

### ISSUE THREAD

**Issue by aloksaurabh** [freqtrade/freqtrade#8266]
## Describe your environment

  * Operating system:  `Linux kaliSSD 6.0.0-kali6-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.0.12-1kali1 (2022-12-19) x86_64 GNU/Linux`
  * Python Version: Python 3.10.9
  * CCXT version: 2.8.54
  * Freqtrade Version: freqtrade 2023.3.dev-d1b2e38ae
  * Evironment : Script and conda (Can be replicated on both)
  
## Describe the problem:

*Hyperopt crashes in a fresh install of freqtrade for short strategies*

### Steps to reproduce:

  1. Fresh install 
  2. See commands below
  
My environment details
[env.txt](https://github.com/freqtrade/freqtrade/files/10872176/env.txt)

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
(.env) alok@kaliSSD:/media/alok/New_Volume/kali/freqtrade$ freqtrade hyperopt --config user_data/config_df4.json  --strategy alok4  --epochs 5 --hyperopt-loss ExpectancyHyperOptLoss --timerange 20220915-202210152023-03-02 19:30:51,069 - freqtrade - INFO - freqtrade 2023.3.dev-d1b2e38ae
2023-03-02 19:30:51,099 - freqtrade.configuration.load_config - INFO - Using config: user_data/config_df4.json ...
2023-03-02 19:30:51,100 - freqtrade.loggers - INFO - Verbosity set to 0
2023-03-02 19:30:51,100 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 10 ...
2023-03-02 19:30:51,100 - freqtrade.configuration.configuration - INFO - Parameter --timerange detected: 20220915-20221015 ...
2023-03-02 19:30:51,101 - freqtrade.configuration.configuration - INFO - Using user-data directory: /media/alok/New_Volume/kali/freqtrade/user_data ...
2023-03-02 19:30:51,101 - freqtrade.configuration.configuration - INFO - Using data directory: /media/alok/New_Volume/kali/freqtrade/user_data/data/binance ...
2023-03-02 19:30:51,101 - freqtrade.configuration.configuration - INFO - Parameter --epochs detected ... Will run Hyperopt with for 5 epochs ...
2023-03-02 19:30:51,101 - freqtrade.configuration.configuration - INFO - Parameter -s/--spaces detected: default
2023-03-02 19:30:51,101 - freqtrade.configuration.configuration - INFO - Parameter -j/--job-workers detected: -1
2023-03-02 19:30:51,101 - freqtrade.configuration.configuration - INFO - Parameter --min-trades detected: 1
2023-03-02 19:30:51,101 - freqtrade.configuration.configuration - INFO - Using Hyperopt loss class name: ExpectancyHyperOptLoss
2023-03-02 19:30:51,102 - freqtrade.configuration.configuration - INFO - Filter trades by timerange: 20220915-20221015

trimmed---------------------------------

2023-03-02 19:30:58,082 - freqtrade.optimize.hyperopt - INFO - Hyperopting with data from 2022-09-15 00:00:00 up to 2022-10-15 00:00:00 (30 days)..
2023-03-02 19:30:58,559 - freqtrade.optimize.hyperopt - INFO - Found 16 CPU cores. Let's make them scream!
2023-03-02 19:30:58,559 - freqtrade.optimize.hyperopt - INFO - Number of parallel jobs set as: -1
2023-03-02 19:30:58,559 - freqtrade.optimize.hyperopt - INFO - Using estimator ET.
2023-03-02 19:30:58,577 - freqtrade.optimize.hyperopt - INFO - Effective number of parallel workers used: 16

2023-03-02 19:31:03,730 - freqtrade - ERROR - Fatal exception!
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/media/alok/New_Volume/kali/freqtrade/.env/lib/python3.10/site-packages/joblib/externals/loky/process_executor.py", line 428, in _process_worker
    r = call_item()
  File "/media/alok/New_Volume/kali/freqtrade/.env/lib/python3.10/site-packages/joblib/externals/loky/process_executor.py", line 275, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/media/alok/New_Volume/kali/freqtrade/.env/lib/python3.10/site-packages/joblib/_parallel_backends.py", line 620, in __call__
    return self.func(*args, **kwargs)
  File "/media/alok/New_Volume/kali/freqtrade/.env/lib/python3.10/site-packages/joblib/parallel.py", line 288, in __call__
    return [func(*args, **kwargs)
  File "/media/alok/New_Volume/kali/freqtrade/.env/lib/python3.10/site-packages/joblib/parallel.py", line 288, in <listcomp>
    return [func(*args, **kwargs)
  File "/media/alok/New_Volume/kali/freqtrade/.env/lib/python3.10/site-packages/joblib/externals/loky/cloudpickle_wrapper.py", line 33, in __call__
    return self._obj(*args, **kwargs)
  File "/media/alok/New_Volume/kali/freqtrade/freqtrade/optimize/hyperopt.py", line 373, in generate_optimizer
    return self._get_results_dict(bt_results, self.min_date, self.max_date,
  File "/media/alok/New_Volume/kali/freqtrade/freqtrade/optimize/hyperopt.py", line 401, in _get_results_dict
    loss = self.calculate_loss(results=backtesting_results['results'],
  File "/media/alok/New_Volume/kali/freqtrade/user_data/hyperopts/ExpectancyHyperOptLoss.py", line 65, in hyperopt_loss_function
    total_profit_pct = results["profit_abs"] / stake
  File "/media/alok/New_Volume/kali/freqtrade/.env/lib/python3.10/site-packages/pandas/core/ops/common.py", line 72, in new_method
    return method(self, other)
  File "/media/alok/New_Volume/kali/freqtrade/.env/lib/python3.10/site-packages/pandas/core/arraylike.py", line 126, in __truediv__
    return self._arith_method(other, operator.truediv)
  File "/media/alok/New_Volume/kali/freqtrade/.env/lib/python3.10/site-packages/pandas/core/series.py", line 6259, in _arith_method
    return base.IndexOpsMixin._arith_method(self, other, op)
  File "/media/alok/New_Volume/kali/freqtrade/.env/lib/python3.10/site-packages/pandas/core/base.py", line 1325, in _arith_method
    result = ops.arithmetic_op(lvalues, rvalues, op)
  File "/media/alok/New_Volume/kali/freqtrade/.env/lib/python3.10/site-packages/pandas/core/ops/array_ops.py", line 226, in arithmetic_op
    res_values = _na_arithmetic_op(left, right, op)  # type: ignore[arg-type]
  File "/media/alok/New_Volume/kali/freqtrade/.env/lib/python3.10/site-packages/pandas/core/ops/array_ops.py", line 165, in _na_arithmetic_op
    result = func(left, right)
TypeError: ufunc 'divide' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/media/alok/New_Volume/kali/freqtrade/freqtrade/main.py", line 42, in main
    return_code = args['func'](args)
  File "/media/alok/New_Volume/kali/freqtrade/freqtrade/commands/optimize_commands.py", line 107, in start_hyperopt
    hyperopt.start()
  File "/media/alok/New_Volume/kali/freqtrade/freqtrade/optimize/hyperopt.py", line 630, in start
    f_val = self.run_optimizer_parallel(parallel, asked)
  File "/media/alok/New_Volume/kali/freqtrade/freqtrade/optimize/hyperopt.py", line 440, in run_optimizer_parallel
    return parallel(delayed(
  File "/media/alok/New_Volume/kali/freqtrade/.env/lib/python3.10/site-packages/joblib/parallel.py", line 1098, in __call__
    self.retrieve()
  File "/media/alok/New_Volume/kali/freqtrade/.env/lib/python3.10/site-packages/joblib/parallel.py", line 975, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/media/alok/New_Volume/kali/freqtrade/.env/lib/python3.10/site-packages/joblib/_parallel_backends.py", line 567, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
TypeError: ufunc 'divide' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
  ```

**Comment by xmatthias** [comment]
The error comes out of `ExpectancyHyperOptLoss.py` - a custom Hyperopt loss function

To highlight the actual error:

```
File "/media/alok/New_Volume/kali/freqtrade/user_data/hyperopts/ExpectancyHyperOptLoss.py", line 65, in hyperopt_loss_function
  total_profit_pct = results["profit_abs"] / stake
```

In essence, what the error is telling you is that `results["profit_abs"]` cannot be divided by `stake` - whatever that is.

Now i know that `results["profit_abs"]` is a numerical numpy/pandas series - but `stake` is unknown - and most likely either None, or some other unexpected type (at least one that can't be casted to a numeric value safely).

There's little help other than that we can provide you - but it's definitely not a bug in freqtrade, but something to do with your loss function.

**Comment by aloksaurabh** [comment]
Thanks
Solved. 
Wrote an if for 'unlimited' stake_amount

**Comment by godshades** [comment]
hi @aloksaurabh, may you share your fixed code
