### ISSUE TITLE
Bot cannot place/update stoploss on Gate.io due to `Trigger.Price must < last_price`.

### ISSUE THREAD

**Issue by Ridder90** [freqtrade/freqtrade#8270]
## Describe your environment

 * Operating system: Ubuntu/Docker
 * image: freqtradeorg/freqtrade:stable
 * Freqtrade Version: freqtrade 2023.2
 * Using CCXT 2.8.17
  

## Describe the problem:

Bot cannot place/update stoploss on Gate.io due to `Trigger.Price must < last_price`.

Due to the rubber duck effect I have the assumption it is because my stoploss function returns a to tight stop loss.

During hyperopting I noticed some messages "Cannot Create Stoploss".
In hyperopting/dry-running I could suppress this message by doing preventing my custom stop-loss function to return 0 (see snippet below).

I would expect that if SL <= 0 the trade would already have been closed. 

### Steps to reproduce:

  1. Run a strategy with tight stoploss on gate.io

### Relevant code exceptions or logs
```
2023-03-03 15:10:17,485 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=11, pair=APT/USDT:USDT, amount=16.32334155, is_short=True, leverage=8.0, open_rate=11.69300000, open_since=2023-03-03 15:10:15)
2023-03-03 15:10:17,766 - freqtrade.persistence.trade_model - INFO - Updating trade (id=11) ...
2023-03-03 15:10:17,767 - freqtrade.persistence.trade_model - INFO - LIMIT_SELL has been fulfilled for Trade(id=11, pair=APT/USDT:USDT, amount=16.30000000, is_short=True, leverage=8.0, open_rate=11.69300000, open_since=2023-03-03 15:10:15).
2023-03-03 15:10:18,585 - freqtrade.wallets - INFO - Wallets synced.
2023-03-03 15:10:18,599 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'trade_id': 11, 'type': entry_fill, 'buy_tag': None, 'enter_tag': None, 'exchange': 'Gateio', 'pair': 'APT/USDT:USDT', 'leverage': 8.0, 'direction': 'Short', 'limit': 11.693, 'open_rate': 11.693, 'order_type': None, 'stake_amount': 23.8244875, 'stake_currency': 'USDT', 'fiat_currency': 'USD', 'amount': 16.3, 'open_date': datetime.datetime(2023, 3, 3, 15, 10, 15, 992654), 'current_rate': 11.693, 'sub_trade': False}
2023-03-03 15:10:18,600 - freqtrade.rpc.telegram - INFO - Notification 'entry_fill' not sent.
2023-03-03 15:10:19,132 - freqtrade.exchange.common - WARNING - create_stoploss() returned exception: "Could not place stoploss order due to ExchangeError. Message: gateio {"label":"AUTO_TRIGGER_PRICE_LESS_LAST","message":"invalid argument: Trigger.Price must < last_price"}". Giving up.
2023-03-03 15:10:19,133 - freqtrade.freqtradebot - ERROR - Unable to place a stoploss order on exchange.
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 625, in fetch
    response.raise_for_status()
  File "/home/ftuser/.local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.gateio.ws/api/v4/futures/usdt/price_orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/exchange.py", line 1204, in create_stoploss
    order = self._api.create_order(symbol=pair, type=ordertype, side=side,
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/gate.py", line 3137, in create_order
    response = getattr(self, method)(self.deep_extend(request, params))
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 505, in inner
    return entry(_self, **inner_kwargs)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2833, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2830, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 641, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/gate.py", line 4825, in handle_errors
    raise ExchangeError(feedback)
ccxt.base.errors.ExchangeError: gateio {"label":"AUTO_TRIGGER_PRICE_LESS_LAST","message":"invalid argument: Trigger.Price must < last_price"}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/freqtradebot.py", line 1101, in create_stoploss_order
    stoploss_order = self.exchange.create_stoploss(
  File "/freqtrade/freqtrade/exchange/common.py", line 179, in wrapper
    raise ex
  File "/freqtrade/freqtrade/exchange/common.py", line 164, in wrapper
    return f(*args, **kwargs)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 1226, in create_stoploss
    raise TemporaryError(
freqtrade.exceptions.TemporaryError: Could not place stoploss order due to ExchangeError. Message: gateio {"label":"AUTO_TRIGGER_PRICE_LESS_LAST","message":"invalid argument: Trigger.Price must < last_price"}

```

This is my order_types configuration
```
order_types = {
        'entry': 'limit',
        'exit': 'market',
        'stoploss': 'market',
        'stoploss_on_exchange': True,
        "stoploss_on_exchange_limit_ratio": 0.99
  }
```

This is my stoploss function
 ```
def custom_stoploss(self, pair: str, trade: 'Trade', current_time: datetime,
                        current_rate: float, current_profit: float, **kwargs) -> float:
       
        dataframe, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)
        trade_date = timeframe_to_prev_date(self.timeframe, trade.open_date_utc)
        
        # Look up trade candle.
        open_candle = dataframe.loc[dataframe['date'] == trade_date]

        # open_candle may be empty for trades that just opened as it is still incomplete.
        if open_candle.empty:
            # print(['No open candle', -1])
            return -1

        # Trail if certain profit is met
        open_candle = open_candle.squeeze()

        if not (open_candle[f'atr_{self.atr_period.value}'] > 0):
            return -1
            
        atr_distance = open_candle[f'atr_{self.atr_period.value}']*self.atr_sl_factor.value
        sl = stoploss_from_absolute(open_candle['high_5'] + atr_distance if trade.is_short else open_candle['low_5'] - atr_distance, current_rate, is_short=trade.is_short) * trade.leverage
 
        # add this to prevent "Cannot create Stoploss"
        if sl == 0:
            return -0.001 * trade.leverage
        return sl
```

Thnx for this great tool!

**Comment by xmatthias** [comment]
This is due to the premise that Prices move all the time.

When you attempt to create a very tight stoploss (probably on a "small" / low volume pair) - that can fail.
The error is quite clear - the price you're attempting to use as stoploss value is above the "last" price.
This is quite common if tight stoplosses (below <-0.5% - but the actual value can be higher depending on the pair) are used.

There's nothing we can or will do against that other than recommend people to use less tight stoplosses.
In case of the above error, freqtrade will have taken the trade and created an emergency exit - which (based on your configuration) - was a market order, which filled immediately.

As the actual price was below the desired stop price - this best corresponds with your desires / wishes of a stoploss that is "at or above current price".

**Comment by Ridder90** [comment]
Thnx for the fast response! And so fast 🤯  

Your answer makes perfectly sense. Wasn't aware of the emergency exit. Will play around with the stoploss. 

Keep up the good work 👍

**Comment by xmatthias** [comment]
> Wasn't aware of the emergency exit. 

that should show up in the logs below/after the exception you posted above.

**Comment by Ridder90** [comment]
Hmmm I do not see it in the logs. If looking at the logs and the telegram chat it seems it like it just hangs at "could not change stoploss due to exchange error"

Where is this emergency exit defined? Searched strategy interface, trade model and Gateio specific.

**Comment by Ridder90** [comment]
I am doubting a bit if `stoploss_on_exchange` is respecting this statement in the documentation. 

My custom stoploss gets tighter a soon as there is some profit. But now the initial stop loss with some breathing room gets cancelled but it fails to create a new one because it is too tight. Resulting in no stop loss at all haha

> The stoploss price can only ever move upwards - if the stoploss value returned from custom_stoploss would result in a lower stoploss price than was previously set, it will be ignored. The traditional stoploss value serves as an absolute lower level and will be instated as the initial stoploss (before this method is called for the first time for a trade), and is still mandatory.

This is the first time I see the error and then it will end up in some infinite loop with "During handling of the above exception, another exception occurred:" .  I see no trace of the emergency exit you mentioned. I am probably doing something wrong or looking with my nose. 
````
2023-03-03 14:55:16,401 - freqtrade.exchange.exchange - INFO - stoploss limit order added for APT/USDT:USDT. stop price: 11.982. limit: 12.102
2023-03-03 14:56:13,378 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2023.2', state='RUNNING'
2023-03-03 14:56:14,271 - freqtrade.freqtradebot - INFO - Cancelling current stoploss on exchange for pair LQTY/USDT:USDT (orderid:38022531) in order to add another one ...
2023-03-03 14:56:15,365 - freqtrade.exchange.exchange - INFO - stoploss limit order added for LQTY/USDT:USDT. stop price: 1.8705. limit: 1.8518
2023-03-03 14:57:13,408 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2023.2', state='RUNNING'
2023-03-03 14:57:14,845 - freqtrade.exchange.common - WARNING - create_stoploss() returned exception: "Could not place stoploss order due to ExchangeError. Message: gateio {"label":"AUTO_TRIGGER_PRICE_LESS_LAST","message":"invalid argument: Trigger.Price must < last_price"}". Giving up.
2023-03-03 14:57:14,846 - freqtrade.freqtradebot - ERROR - Unable to place a stoploss order on exchange.
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 625, in fetch
    response.raise_for_status()
  File "/home/ftuser/.local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.gateio.ws/api/v4/futures/usdt/price_orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/exchange.py", line 1204, in create_stoploss
    order = self._api.create_order(symbol=pair, type=ordertype, side=side,
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/gate.py", line 3137, in create_order
    response = getattr(self, method)(self.deep_extend(request, params))
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 505, in inner
    return entry(_self, **inner_kwargs)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2833, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2830, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 641, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/gate.py", line 4825, in handle_errors
    raise ExchangeError(feedback)
ccxt.base.errors.ExchangeError: gateio {"label":"AUTO_TRIGGER_PRICE_LESS_LAST","message":"invalid argument: Trigger.Price must < last_price"}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/freqtradebot.py", line 1101, in create_stoploss_order
    stoploss_order = self.exchange.create_stoploss(
  File "/freqtrade/freqtrade/exchange/common.py", line 179, in wrapper
    raise ex
  File "/freqtrade/freqtrade/exchange/common.py", line 164, in wrapper
    return f(*args, **kwargs)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 1226, in create_stoploss
    raise TemporaryError(
freqtrade.exceptions.TemporaryError: Could not place stoploss order due to ExchangeError. Message: gateio {"label":"AUTO_TRIGGER_PRICE_LESS_LAST","message":"invalid argument: Trigger.Price must < last_price"}
2023-03-03 14:57:14,877 - freqtrade.freqtradebot - WARNING - Stoploss order was cancelled, but unable to recreate one.
2023-03-03 14:57:20,062 - freqtrade.exchange.common - WARNING - create_stoploss() returned exception: "Could not place stoploss order due to ExchangeError. Message: gateio {"label":"AUTO_TRIGGER_PRICE_LESS_LAST","message":"invalid argument: Trigger.Price must < last_price"}". Giving up.
2023-03-03 14:57:20,063 - freqtrade.freqtradebot - ERROR - Unable to place a stoploss order on exchange.
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 625, in fetch
    response.raise_for_status()
  File "/home/ftuser/.local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.gateio.ws/api/v4/futures/usdt/price_orders

During handling of the above exception, another exception occurred:
```

**Comment by xmatthias** [comment]
seems like the error mapping is missing in ccxt.

https://github.com/ccxt/ccxt/pull/17048 should fix that.
