### ISSUE TITLE
Unable to connect to binance markets from mumbai ec2 ubuntu server

### ISSUE THREAD

**Issue by Thecodebilly** [freqtrade/freqtrade#8287]
Hia, so I am trying to set up my freqtrade bot on an Amazon EC2 server and I am getting this error in the logs when I go to `docker-compose up -d`:

2023-03-07 03:46:00,557 - freqtrade.exchange.exchange - INFO - Using CCXT 2.8.17
2023-03-07 03:46:00,580 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2023-03-07 03:46:00,733 - freqtrade.exchange.exchange - ERROR - Unable to initialize markets.
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 625, in fetch
    response.raise_for_status()
  File "/home/ftuser/.local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error:  for url: https://api.binance.com/sapi/v1/capital/config/getall?timestamp=1678160760580&recvWindow=10000&signature=19722e4b513b75f5459281720ece4d367fd8bb9e5ea90192eebef4c2aa5b1e87

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/exchange.py", line 481, in _load_markets
    self._markets = self._api.load_markets(params={})
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 1459, in load_markets
    currencies = self.fetch_currencies()
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/binance.py", line 1541, in fetch_currencies
    response = self.sapiGetCapitalConfigGetall(params)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 505, in inner
    return entry(_self, **inner_kwargs)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/binance.py", line 6552, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2830, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 641, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/binance.py", line 6530, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 3133, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.AuthenticationError: binance {"code":-2008,"msg":"Invalid Api-Key ID."}
2023-03-07 03:46:00,737 - freqtrade.commands.trade_commands - ERROR - Could not load markets, therefore cannot start. Please investigate the above error for more details.
2023-03-07 03:46:00,737 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 24, in start_trading
    worker = Worker(args)
  File "/freqtrade/freqtrade/worker.py", line 37, in __init__
    self._init(False)
  File "/freqtrade/freqtrade/worker.py", line 53, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/freqtrade/freqtrade/freqtradebot.py", line 68, in __init__
    self.exchange = ExchangeResolver.load_exchange(
  File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 34, in load_exchange
    exchange = ExchangeResolver._load_exchange(
  File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 60, in _load_exchange
    exchange = ex_class(**kwargs)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 183, in __init__
    self.validate_config(config)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 214, in validate_config
    self.validate_stakecurrency(config['stake_currency'])
  File "/freqtrade/freqtrade/exchange/exchange.py", line 516, in validate_stakecurrency
    raise OperationalException(
freqtrade.exceptions.OperationalException: Could not load markets, therefore cannot start. Please investigate the above error for more details.

my api key is correct and I could not find anyone else with this issue. Thanks in advance!

**Comment by stash86** [comment]
No, your IP key isn't correct. Check the setting for that api again

**Comment by xmatthias** [comment]
The error is pretty specific: `ccxt.base.errors.AuthenticationError: binance {"code":-2008,"msg":"Invalid Api-Key ID."}`
This error comes directly from binance, too.

even if key/secret is correct - it could still mean that they are 
* exchanged - so secret is in the key field or viceversa
* there's leading or trailing whitespaces in the configuration

...

Considering your account mentions "Jacksonville" (and binance requires KYC) - is your account on binance.us or binance.com?
the 2 are separate legal (and technical) entities, so one account won't work on the other.

**Comment by xmatthias** [comment]
@Thecodebilly i assume you've got this sorted?

at any rate, you might want to revoke your binance keys **IMMEDIATELY** - as you've commited them to a public repository in your useraccount.
