### ISSUE TITLE
sqlite Operational error

### ISSUE THREAD

**Issue by ma1158** [freqtrade/freqtrade#8298]
(.env) [ec2-user@ip-172-31-5-11 freqtrade]$ freqtrade trade --config config_examples/config_freqai.example.json --strategy FreqaiExampleStrategy --freqaimodel LightGBMRegressor --strategy-path freqtrade/templates

2023-03-09 16:57:54,793 - freqtrade - INFO - freqtrade 2023.2
2023-03-09 16:57:55,343 - freqtrade.worker - INFO - Starting worker 2023.2
2023-03-09 16:57:55,343 - freqtrade.configuration.load_config - INFO - Using config: config_examples/config_freqai.example.json ...
2023-03-09 16:57:55,346 - freqtrade.loggers - INFO - Verbosity set to 0
2023-03-09 16:57:55,346 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
2023-03-09 16:57:55,346 - freqtrade.configuration.configuration - INFO - Using additional Strategy lookup path: freqtrade/templates
2023-03-09 16:57:55,347 - freqtrade.configuration.configuration - WARNING - `force_entry_enable` RPC message enabled.
2023-03-09 16:57:55,347 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2023-03-09 16:57:55,347 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:///tradesv3.dryrun.sqlite"
2023-03-09 16:57:55,347 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 5 ...
2023-03-09 16:57:55,349 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/ec2-user/freqtrade/user_data ...
2023-03-09 16:57:55,349 - freqtrade.configuration.configuration - INFO - Using data directory: /home/ec2-user/freqtrade/user_data/data/binance ...
2023-03-09 16:57:55,349 - freqtrade.configuration.configuration - INFO - Using freqaimodel class name: LightGBMRegressor
2023-03-09 16:57:55,350 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2023-03-09 16:57:55,364 - freqtrade.exchange.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2023-03-09 16:57:55,365 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2023-03-09 16:57:55,419 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy FreqaiExampleStrategy from '/home/ec2-user/freqtrade/freqtrade/templates/FreqaiExampleStrategy.py'...
2023-03-09 16:57:55,420 - freqtrade.strategy.hyper - INFO - Found no parameter file.
2023-03-09 16:57:55,420 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 3m.
2023-03-09 16:57:55,420 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2023-03-09 16:57:55,420 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 200.
2023-03-09 16:57:55,420 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'entry': 10, 'exit': 30}.
2023-03-09 16:57:55,421 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'max_open_trades' with value in config file: 5.
2023-03-09 16:57:55,421 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 0.1, '240': -1}
2023-03-09 16:57:55,421 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 3m
2023-03-09 16:57:55,421 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.05
2023-03-09 16:57:55,421 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2023-03-09 16:57:55,421 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2023-03-09 16:57:55,421 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2023-03-09 16:57:55,421 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2023-03-09 16:57:55,422 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: True
2023-03-09 16:57:55,422 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'entry': 'limit', 'exit': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False, 'stoploss_on_exchange_interval': 60}
2023-03-09 16:57:55,422 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'entry': 'GTC', 'exit': 'GTC'}
2023-03-09 16:57:55,422 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2023-03-09 16:57:55,422 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 200
2023-03-09 16:57:55,422 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2023-03-09 16:57:55,422 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 40
2023-03-09 16:57:55,422 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'entry': 10, 'exit': 30}
2023-03-09 16:57:55,422 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_exit_signal: True
2023-03-09 16:57:55,422 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_only: False
2023-03-09 16:57:55,423 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_entry_signal: False
2023-03-09 16:57:55,423 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_offset: 0.0
2023-03-09 16:57:55,423 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2023-03-09 16:57:55,423 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2023-03-09 16:57:55,423 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: False
2023-03-09 16:57:55,423 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1
2023-03-09 16:57:55,423 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_open_trades: 5
2023-03-09 16:57:55,423 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2023-03-09 16:57:55,439 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2023-03-09 16:57:55,439 - freqtrade.exchange.exchange - INFO - Using CCXT 2.9.9
2023-03-09 16:57:55,439 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}}
2023-03-09 16:57:55,454 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}}
2023-03-09 16:57:55,468 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2023-03-09 16:57:57,183 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2023-03-09 16:57:57,235 - freqtrade.commands.trade_commands - ERROR - (sqlite3.OperationalError) near ",": syntax error
[SQL: UPDATE orders SET ft_is_open=? WHERE orders.ft_is_open IS 1 AND ((orders.ft_trade_id, orders.order_id) NOT IN (SELECT trades.id, trades.stoploss_order_id 
FROM trades 
WHERE trades.stoploss_order_id IS NOT NULL)) AND orders.ft_order_side = ? AND orders.order_id LIKE ?]
[parameters: (0, 'stoploss', 'dry%')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2023-03-09 16:57:57,236 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/ec2-user/freqtrade/.env/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/home/ec2-user/freqtrade/.env/lib64/python3.8/site-packages/sqlalchemy/engine/default.py", line 748, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: near ",": syntax error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ec2-user/freqtrade/.env/lib64/python3.8/site-packages/freqtrade/commands/trade_commands.py", line 24, in start_trading
    worker = Worker(args)
  File "/home/ec2-user/freqtrade/.env/lib64/python3.8/site-packages/freqtrade/worker.py", line 37, in __init__
    self._init(False)
  File "/home/ec2-user/freqtrade/.env/lib64/python3.8/site-packages/freqtrade/worker.py", line 53, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/home/ec2-user/freqtrade/.env/lib64/python3.8/site-packages/freqtrade/freqtradebot.py", line 71, in __init__
    init_db(self.config['db_url'])
  File "/home/ec2-user/freqtrade/.env/lib64/python3.8/site-packages/freqtrade/persistence/models.py", line 63, in init_db
    check_migrate(engine, decl_base=_DECL_BASE, previous_tables=previous_tables)
  File "/home/ec2-user/freqtrade/.env/lib64/python3.8/site-packages/freqtrade/persistence/migrations.py", line 343, in check_migrate
    fix_old_dry_orders(engine)
  File "/home/ec2-user/freqtrade/.env/lib64/python3.8/site-packages/freqtrade/persistence/migrations.py", line 282, in fix_old_dry_orders
    connection.execute(stmt)
  File "/home/ec2-user/freqtrade/.env/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1414, in execute
    return meth(
  File "/home/ec2-user/freqtrade/.env/lib64/python3.8/site-packages/sqlalchemy/sql/elements.py", line 486, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/ec2-user/freqtrade/.env/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/ec2-user/freqtrade/.env/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
  File "/home/ec2-user/freqtrade/.env/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/ec2-user/freqtrade/.env/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 2326, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/ec2-user/freqtrade/.env/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/home/ec2-user/freqtrade/.env/lib64/python3.8/site-packages/sqlalchemy/engine/default.py", line 748, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near ",": syntax error
[SQL: UPDATE orders SET ft_is_open=? WHERE orders.ft_is_open IS 1 AND ((orders.ft_trade_id, orders.order_id) NOT IN (SELECT trades.id, trades.stoploss_order_id 
FROM trades 
WHERE trades.stoploss_order_id IS NOT NULL)) AND orders.ft_order_side = ? AND orders.order_id LIKE ?]
[parameters: (0, 'stoploss', 'dry%')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
(.env) [ec2-user@ip-172-31-5-11 freqtrade]$ 
(.env) [ec2-user@ip-172-31-5-11 freqtrade]$ 
Socket error Event: 32 Error: 10053.
Connection closing...Socket close.

Connection closed by foreign host.

Disconnected from remote host(1134) at 01:03:27.

**Comment by xmatthias** [comment]
Please fill out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

The above error got nothing to do with freqAI - but most likely with an outdated operating system - which the issue template would confirm.

**Comment by ma1158** [comment]
> 
Operating system: Linux
Python Version: 3.8.16
CCXT version: 2.8.98 
Freqtrade Version: 2023.2
Is this a question template?

Sorry, it's my first time using this site and I'm not very familiar with it yet,

**Comment by ma1158** [comment]
When I run this command, I get an error
freqtrade trade --config config_examples/config_freqai.example.json --strategy FreqaiExampleStrategy --freqaimodel LightGBMRegressor --strategy-path freqtrade/templates

**Comment by xmatthias** [comment]
> Operating system: Linux

what version? my suspicion is that you're on an old operating system, which has an outdated sqlite version.
#7470 was the same, and had the identical error.

as mentioned in that issue - you can check this with the following command:

``` 
$ python3
import sqlite3
sqlite3.sqlite_version
```

**Comment by ma1158** [comment]
>>> import sqlite3
>>> sqlite3.sqlite_version
'3.7.17'
 Amazon Linux 2 AMI

**Comment by xmatthias** [comment]
Quoting myself from the other issue:
> That's a sqlite version that's from 2013 - that's >9 years old.

Unfortunately, we can't support this version. Best use an uptodate operating system (If this is the newest Amazon linux, best use Ubuntu, which i know to have a more recent sqlite version).
