### ISSUE TITLE
Enabling ""inlier_metric_window" in config throws error for freqai/RL example strategy..

### ISSUE THREAD

**Issue by sandhuq** [freqtrade/freqtrade#8301]
running "freqtrade trade --freqaimodel ReinforcementLearner --config config.json --strategy freqai_rl_test_strat"

ERROR :
```Traceback (most recent call last):
  File "/Users/sandhu/Py/gits/freqtrade/freqtrade/freqai/freqai_interface.py", line 237, in _start_scanning
    self.extract_data_and_train_model(
  File "/Users/sandhu/Py/gits/freqtrade/freqtrade/freqai/freqai_interface.py", line 623, in extract_data_and_train_model
    model = self.train(unfiltered_dataframe, pair, dk)
  File "/Users/sandhu/Py/gits/freqtrade/freqtrade/freqai/RL/BaseReinforcementLearningModel.py", line 129, in train
    model = self.fit(data_dictionary, dk)
  File "/Users/sandhu/Py/gits/freqtrade/freqtrade/freqai/prediction_models/ReinforcementLearner.py", line 72, in fit
    model.learn(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ml/lib/python3.10/site-packages/stable_baselines3/ppo/ppo.py", line 307, in learn
    return super().learn(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ml/lib/python3.10/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 248, in learn
    continue_training = self.collect_rollouts(self.env, callback, self.rollout_buffer, n_rollout_steps=self.n_steps)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ml/lib/python3.10/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 181, in collect_rollouts
    if callback.on_step() is False:
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ml/lib/python3.10/site-packages/stable_baselines3/common/callbacks.py", line 100, in on_step
    return self._on_step()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ml/lib/python3.10/site-packages/stable_baselines3/common/callbacks.py", line 204, in _on_step
    continue_training = callback.on_step() and continue_training
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ml/lib/python3.10/site-packages/stable_baselines3/common/callbacks.py", line 100, in on_step
    return self._on_step()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ml/lib/python3.10/site-packages/stable_baselines3/common/callbacks.py", line 447, in _on_step
    episode_rewards, episode_lengths = evaluate_policy(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ml/lib/python3.10/site-packages/stable_baselines3/common/evaluation.py", line 89, in evaluate_policy
    observations, rewards, dones, infos = env.step(actions)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ml/lib/python3.10/site-packages/stable_baselines3/common/vec_env/base_vec_env.py", line 163, in step
    return self.step_wait()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ml/lib/python3.10/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 61, in step_wait
    self._save_obs(env_idx, obs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ml/lib/python3.10/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 105, in _save_obs
    self.buf_obs[key][env_idx] = obs
ValueError: could not broadcast input array from shape (39,230) into shape (40,230)
2023-03-09 17:15:15,299 - freqtrade.freqai.RL.BaseReinforcementLearningModel - INFO - --------------------Starting training ETH/USDT:USDT -----------```

**Comment by sandhuq** [comment]
the only change from a running example strategy is enabling inlier_metrics.. that produces the error.

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

For freqAI specific issues (like this one), we'll also need the freqAI section of the configuration - as many configurations play together - so having the full, reproducible picture is a must.

**Comment by sandhuq** [comment]
oops, first timer..will do in future ! 
thanks,

**Comment by xmatthias** [comment]
well we'll still need it to look at this specific issue ... ;)

**Comment by xmatthias** [comment]
Is this still an issue? we'd still need the info requested above (freqtrade version, freqai part of the configuration) to actually look at this.
without it - we'll have to close this issue - as there's not enough information to look at this further.

**Comment by sandhuq** [comment]
will redo and provide dtls tdy, actually @drafty at discord aware of issue and he'd asked me to file report, which i clearly messed up :)

**Comment by sandhuq** [comment]
well just rechecked and it works !!
Version : ``` INFO - freqtrade 2023.3.dev-9573974c4```  

thanks xmatthias !

Nope , mistook sorry , problem still persists.

**Comment by robcaulk** [comment]
Thanks for posting this - I have it on my todo list to check out - but I cannot promise immediate action :/
