### ISSUE TITLE
Backtest Why can't I backtest on the perpetual contract on Binance?

### ISSUE THREAD

**Issue by revoit88** [freqtrade/freqtrade#8454]
Why can't I backtest on the perpetual contract on Binance?
2023-04-05 12:30:12,667 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2023-04-05 12:30:12,667 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: unlimited
2023-04-05 12:30:12,667 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2023-04-05 12:30:12,667 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 30
2023-04-05 12:30:12,667 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}
2023-04-05 12:30:12,667 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_exit_signal: True
2023-04-05 12:30:12,667 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_only: False
2023-04-05 12:30:12,667 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_entry_signal: False
2023-04-05 12:30:12,667 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_offset: 0.0
2023-04-05 12:30:12,667 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2023-04-05 12:30:12,667 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2023-04-05 12:30:12,667 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: False
2023-04-05 12:30:12,667 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1
2023-04-05 12:30:12,667 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_open_trades: 3
2023-04-05 12:30:12,668 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2023-04-05 12:30:12,672 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from '/freqtrade/freqtrade/plugins/pairlist/StaticPairList.py'...
2023-04-05 12:30:12,680 - freqtrade.rpc.api_server.api_backtest - ERROR - Backtesting caused an error: No pair in whitelist.
Traceback (most recent call last):
  File "/freqtrade/freqtrade/rpc/api_server/api_backtest.py", line 75, in run_backtest
    ApiServer._bt['bt'] = Backtesting(btconfig)
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 130, in __init__
    raise OperationalException("No pair in whitelist.")
freqtrade.exceptions.OperationalException: No pair in whitelist.

下面是配置文件

{
    "max_open_trades": 3,
    "stake_currency": "USDT",
    "stake_amount": "unlimited",
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "dry_run": true,
    "dry_run_wallet": 1000,
    "cancel_open_orders_on_exit": false,
    "trading_mode": "futures",
    "margin_mode": "isolated",
    "unfilledtimeout": {
        "entry": 10,
        "exit": 10,
        "exit_timeout_count": 0,
        "unit": "minutes"
    },
    "entry_pricing": {
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1,
        "price_last_balance": 0.0,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "exit_pricing":{
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1
    },
    "exchange": {
        "name": "binance",
        "key": "",
        "secret": "",
        "ccxt_config": {},
        "ccxt_async_config": {},
        "pair_whitelist": [
        "ETH/USDT"
        ],
        "pair_blacklist": [
            "BNB/.*"
        ]
    },
    "pairlists": [
        {
            "method": "StaticPairList",
            "number_assets": 20,
            "sort_key": "quoteVolume",
            "min_value": 0,
            "refresh_period": 1800
        }
    ],
    "telegram": {
        "enabled": false,
        "token": "",
        "chat_id": ""
    },
    "api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8080,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "dd8cea503f9632b275df591abf3a545a2d24e",
        "ws_token": "Hx3MLsEPCrlmtPCHHcoB_A",
        "CORS_origins": [],
        "username": "123",
        "password": "123"
    },
    "bot_name": "freqtrade",
    "initial_state": "running",
    "force_entry_enable": false,
    "internals": {
        "process_throttle_secs": 5
    }
}

**Comment by revoit88** [comment]
How can I modify configuration files or configure settings?

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

----

Your pair-namings are wrong for futures mode, which follows the `base/quote:settle` approach, as stated in the [documentation](https://www.freqtrade.io/en/stable/leverage/#pair-namings).


In general, I'd recommend to read through the whole documentation at least once. 
It'll answer basic questions (such as this one) - and teach you about the capabilities of freqtrade.
