### ISSUE TITLE
The bot does not receive informative HLOCV during dry run

### ISSUE THREAD

**Issue by Babak64** [freqtrade/freqtrade#8460]
## Describe your environment

  * Operating system: Ubuntu 22.04.2 LTS
  * Python Version: Python 3.10.6
  * CCXT version: 1.93.98
  * Freqtrade Version: 2022.9.1

  
Hello everyone,

I am having trouble with my freqtrade strategy and I am hoping someone in the community can help me out. This is my first time using informative pairs on my strategy, and while the backtesting performed well within the code, the same strategy failed to buy any asset when run in dry mode.
I would really appreciate any assistance as I have been stuck on this issue for the past few days, and with my limited knowledge of the codes, I am unable to figure it out on my own. thanks  in advance for your help!"

I received the following error:
```
"2023-04-09 11:18:49,532 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair BTC/USDT: 'date'
2023-04-09 11:18:49,533 - freqtrade.data.dataprovider - WARNING - No data found for (ETH/USDT, 2h, ).
2023-04-09 11:18:49,533 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error 'date' calling <bound method IStrategy._analyze_ticker_internal of <macd_fast_test.MACDFASTTEST object at 0x7f6c34c8c4c0>>
Traceback (most recent call last):
File "/home/babak/freqtrade/.env/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3800, in get_loc
return self._engine.get_loc(casted_key)
File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
File "pandas/_libs/index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
File "pandas/_libs/hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
File "pandas/_libs/hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'date'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/home/babak/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 27, in wrapper
return f(*args, **kwargs)
File "/home/babak/freqtrade/freqtrade/strategy/interface.py", line 748, in _analyze_ticker_internal
dataframe = self.analyze_ticker(dataframe, metadata)
File "/home/babak/freqtrade/freqtrade/strategy/interface.py", line 726, in analyze_ticker
dataframe = self.advise_indicators(dataframe, metadata)
File "/home/babak/freqtrade/freqtrade/strategy/interface.py", line 1223, in advise_indicators
return self.populate_indicators(dataframe, metadata)
File "/home/babak/freqtrade/user_data/strategies/macd_fast_test.py", line 118, in populate_indicators
informative['date_merge'] = informative["date"] + pd.to_timedelta(minutes, 'm')
File "/home/babak/freqtrade/.env/lib/python3.10/site-packages/pandas/core/frame.py", line 3805, in getitem
indexer = self.columns.get_loc(key)
File "/home/babak/freqtrade/.env/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3802, in get_loc
raise KeyError(key) from err
KeyError: 'date'
2023-04-09 11:18:49,533 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair ETH/USDT: 'date'
2023-04-09 11:18

```
and here is the strategy  and config files
```
from freqtrade.strategy.interface import IStrategy
from freqtrade.strategy import merge_informative_pair
from freqtrade.strategy import (BooleanParameter, CategoricalParameter, DecimalParameter, IStrategy, IntParameter)
from freqtrade.exchange import timeframe_to_minutes
import numpy as np
import pandas as pd
import pandas_ta as pta                            
from typing import Dict, List
from functools import reduce
import talib.abstract as ta
#import talib as ta
import freqtrade.vendor.qtpylib.indicators as qtpylib
from functools import reduce
from pandas import DataFrame, DatetimeIndex, merge
import numpy  # noqa
from freqtrade.enums import CandleType


class MACDFASTTEST(IStrategy):
    
    INTERFACE_VERSION = 2
    
    hull_window_size = IntParameter(16, 60, default=20, space="buy")
    inf_macdhi_short_window = IntParameter(6, 40, default=9, space="buy")
    inf_macdhi_long_window = IntParameter(12, 80, default=74, space="buy")
    inf_macdhi_signal_window = IntParameter(3, 18, default=16, space="buy")
    
    macdhi_short_window = IntParameter(6,40,default=12,space= 'buy')
    macdhi_long_window = IntParameter(12,80,default=26,space= 'buy')
    macdhi_signal_window = IntParameter(3,18,default=9,space= 'buy')
    hull_window_size=IntParameter(16,60,default=20,space= 'buy') 
    
    
    
    # ROI table: from hybrid
    minimal_roi = {
        "0": 0.129,
        "61": 0.114,
        "140": 0.025,
        "495": 0

    }

    # Stoploss:
    stoploss = -0.345


     # Trailing stop:
    trailing_stop = True
    trailing_stop_positive = 0.01
    trailing_stop_positive_offset = 0.041
    trailing_only_offset_is_reached = True




    timeframe = '15m'
    #Run "populate_indicators()" only for new candle.
    process_only_new_candles = False

    # These values can be overridden in the "ask_strategy" section in the config.
    use_sell_signal = True
    sell_profit_only = False
    ignore_roi_if_buy_signal = True

    # Number of candles the strategy requires before producing valid signals
    startup_candle_count: int = 90

    # Optional order type mapping.
    order_types = {
        'buy': 'limit',
        'sell': 'limit',
        'stoploss': 'market',
        'stoploss_on_exchange': True
    }

    # Optional order time in force.
    order_time_in_force = {
        'buy': 'gtc',
        'sell': 'gtc'
    }
    
    plot_config = {
        # Main plot indicators (Moving averages, ...)
        'main_plot': {
            'tema': {},
            'sar': {'color': 'white'},
        },
        'subplots': {
            # Subplots - each dict defines one additional plot
            "MACD": {
                'macd': {'color': 'blue'},
                'macdsignal': {'color': 'orange'},
            },
            "RSI": {
                'rsi': {'color': 'red'},
            }
        }
    }
    def informative_pairs(self):
        
        # get access to all pairs available in whitelist.
        pairs = self.dp.current_whitelist()
        # Assign tf to each pair so they can be downloaded and cached for strategy.
        informative_pairs = [(pair, '2h') for pair in pairs]
       
        
        return [informative_pairs]
    
       
    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        
        inf_tf = '2h'
        
        informative = self.dp.get_pair_dataframe(pair=metadata['pair'], timeframe=inf_tf)
        #print(dataframe.tail(1))
        minutes = timeframe_to_minutes(inf_tf)
       
        informative['date_merge'] = informative["date"] + pd.to_timedelta(minutes, 'm')
        informative.columns = [f"{col}_{inf_tf}" for col in informative.columns]
        #print(dataframe.tail(1))
        # MACD
        macd = ta.MACD(dataframe)
        dataframe['macd'] = macd['macd']
        dataframe['macdsignal'] = macd['macdsignal']
        dataframe['macdhist'] = macd['macdhist']
        
        TS = 9
        KS = 26
        SS = 52
        S = 26
        OS = 0
        dataframe['tenkan'] = pta.ichimoku(high=dataframe['high'], low=dataframe['low'],close=dataframe['close'], tenkan=TS, kijun=KS, senkou=SS, offset=OS)[0][f'ITS_{TS}']
        dataframe['kijun'] = pta.ichimoku(high=dataframe['high'], low=dataframe['low'],close=dataframe['close'], tenkan=TS, kijun=KS, senkou=SS, offset=OS)[0][f'IKS_{KS}']
        dataframe['senkan_a'] = pta.ichimoku(high=dataframe['high'], low=dataframe['low'],close=dataframe['close'], tenkan=TS, kijun=KS, senkou=SS, offset=OS)[0][f'ISA_{TS}']
        dataframe['senkan_b'] = pta.ichimoku(high=dataframe['high'], low=dataframe['low'],close=dataframe['close'], tenkan=TS, kijun=KS, senkou=SS, offset=OS)[0][f'ISB_{KS}']
        #dataframe['Chiko'] = pta.ichimoku(high=dataframe['high'], low=dataframe['low'], close=dataframe['close'], tenkan=TS, kijun=KS, senkou=SS, offset=OS)[0][f'ICS_{KS}']
        #print(dataframe.tail(1))
        
        dataframe = pd.merge(dataframe, informative, left_on='date', right_on=f'date_merge_{inf_tf}', how='left')
        #dataframe = pd.merge(dataframe, informative, on='date', how='left')
        dataframe.fillna(method='ffill', inplace=True)
        #print(dataframe.tail(1))
        return dataframe
        
           
    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict ) -> DataFrame: 
        
         
         dataframe.loc[
            (
                   
              (dataframe['senkan_a'] > dataframe['senkan_b']) &
              (dataframe['close_2h'] > dataframe["senkan_a"]) &
              (dataframe['close_2h'] > dataframe['close_2h'].shift(1)) &
              (dataframe['close_2h'] > dataframe['open_2h']) & 
              (dataframe['macd'] > dataframe['macdsignal'])
                
            ),
            'buy'] = 1
         #selected_columns = ['senkan_a', 'senkan_b','close','close_2h','open_2h','open', 'macd', 'macdsignal', 'buy']
         #print(dataframe[dataframe['buy'] == 1][selected_columns])
         
         return dataframe

       
    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        
        dataframe.loc[
            (
                 
                (dataframe['senkan_a'] < dataframe['senkan_b'])
                
                
            ),
            'sell'] = 0
        return dataframe
```
  
    ----------------------------------------------------------------------------------------------------

``` json
{
    "max_open_trades":50,
    "stake_currency": "USDT",
    "stake_amount":"unlimited",
    "tradable_balance_ratio": 0.99,
    "available_capital": 10000,
    "dry_run_wallet" :10000,
    "fiat_display_currency": "USD",
    "dry_run": true,
    "cancel_open_orders_on_exit": true,
    "unfilledtimeout": {
        "buy": 15,
        "sell": 30,
        "unit": "minutes"
    },
    "bid_strategy": {
        "price_side": "bid",
        "ask_last_balance": 0.0,
        "use_order_book": true,
        "order_book_top": 1,
        "check_depth_of_market": {
            "enabled": true,
            "bids_to_ask_delta":0.4
        }
    },
    "ask_strategy": {
        "price_side": "ask",
        "use_order_book": true,
        "order_book_top": 1
    },
    "exchange": {
        "name": "binance",
        "key": "xxx",
        "secret": "xxx",
        "ccxt_config": {"enableRateLimit": true},
        "ccxt_async_config": {
            "enableRateLimit": true,
            "rateLimit": 200
        },
      "pair_whitelist": [
        
        
   	
"BTC/USDT",
"ETH/USDT"




        ],
        "pair_blacklist": [
           "USDE/USDT"
           
        ],

    },
   "pairlists": [
        {
             "method": "StaticPairList"
             
            
        },
        
        
    
        
     
    ],
    "edge": {
        "enabled": false,
        "process_throttle_secs": 3600,
        "calculate_since_number_of_days": 7,
        "allowed_risk": 0.1,
        "stoploss_range_min": -0.01,
        "stoploss_range_max": -0.40,
        "stoploss_range_step": -0.05,
        "min_trade_number": 5,
        "max_trade_duration_minute": 1440,
        "remove_pumps": true
    },
    "telegram": {
        "enabled": true,
        "token": "xxx",
        "chat_id": "xxx"
    },
    "api_server": {
        "enabled": true,
        "listen_ip_address": "127.0.0.1",
        "listen_port": 8083,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "xxx",
        "CORS_origins": [],
        "username": "everest",
        "password": "xxx"
    },
    "bot_name": "Everest_luck_bot",
    "user_data_dir": "/home/babak/freqtrade/user_data/",
    "strategy_path": "/home/babak/freqtrade/user_data/",
    "db_url": "sqlite:////home/babak/freqtrade/user_data/MACDFASTTEST.sqlite",
    "initial_state": "running",
    "forcebuy_enable": false,
    "internals": {
        "process_throttle_secs": 5
    }
}
```

**Comment by Babak64** [comment]
and here is dataframe print results at different points during backtesting 
 inf_tf = '2h'
        
        informative = self.dp.get_pair_dataframe(pair=metadata['pair'], timeframe=inf_tf)
        print(dataframe.tail(1)) #1
 date      open     high      low    close      volume
4489 2023-02-15 19:45:00+00:00  23304.99  23325.0  23250.0  23318.9  4045.80379
                          date     open     high      low    close     volume
4489 2023-02-15 19:45:00+00:00  1625.78  1628.95  1621.09  1628.54  7195.6823

the 2nd print 
informative['date_merge'] = informative["date"] + pd.to_timedelta(minutes, 'm')
        informative.columns = [f"{col}_{inf_tf}" for col in informative.columns]
        print(dataframe.tail(1))
date      open     high      low    close      volume
4489 2023-02-15 19:45:00+00:00  23304.99  23325.0  23250.0  23318.9  4045.80379
                          date     open     high      low    close     volume
4489 2023-02-15 19:45:00+00:00  1625.78  1628.95  1621.09  1628.54  7195.6823


the 3rd print  
before merge dataframe 
date      open     high      low    close      volume        macd  macdsignal  macdhist     tenkan      kijun  senkan_a  senkan_b
4489 2023-02-15 19:45:00+00:00  23304.99  23325.0  23250.0  23318.9  4045.80379  171.043386  131.507816  39.53557  23062.865  22986.935  22536.47  22482.13
                          date     open     high      low    close     volume       macd  macdsignal  macdhist   tenkan    kijun   senkan_a  senkan_b
4489 2023-02-15 19:45:00+00:00  1625.78  1628.95  1621.09  1628.54  7195.6823  12.204238    7.511349   4.69289  1603.41  1598.09  1571.4325   1568.11


Dataframe print after merge
 
date      open     high      low    close      volume  ...   open_2h   high_2h    low_2h  close_2h    volume_2h             date_merge_2h
4489 2023-02-15 19:45:00+00:00  23304.99  23325.0  23250.0  23318.9  4045.80379  ...  23088.48  23144.76  23002.31  23079.27  19016.80773 2023-01-24 04:00:00+00:00

[1 rows x 20 columns]
                          date     open     high      low    close     volume  ...  open_2h  high_2h   low_2h  close_2h   volume_2h             date_merge_2h
4489 2023-02-15 19:45:00+00:00  1625.78  1628.95  1621.09  1628.54  7195.6823  ...  1637.89  1641.46  1633.25   1639.01  22091.3906 2023-01-24 04:00:00+00:00

**Comment by xmatthias** [comment]
First off - your bot version is outdated by ~half a year. while not per se a problem (we don't actually care - but you could encounter problems/errors when interfacing with the exchange API, which is always evolving) - we'll not be supporting in issues with outdated versions, and the first step in case of further issues/problems will be to update the bot.

---

Your actual error is in `informative_pairs` (which is irrelevant for backtesting).

you're correctly creating a pairlist with `informative_pairs = [(pair, '2h') for pair in pairs]`  - but are then returning a list of this list `return [informative_pairs]`. The result will look roughly as follows:
```
[
  [('ETH/USDT', '2h'), ('BTC/USDT', '2h')]
]
```
which is wrong - as it's one nesting level too much - and results in the informative logic to not find anything to work on (logs prior to the error should indicate that as well - probably at info or warning level).

by simply changing the return statement to `return informative_pairs` (omit the `[]`) - this should work.

---


Aside from that, you might also wanna improve your ichimoku implementation - you're calculating the full indicator (all lines) 4 times - by doing that once and assigning the result to a temporary variable (similar/identical to how you're doing it with MACD already) - you can safe yourself (or your server) some resources.

Freqtrade also offers a helper method for correctly merging a dataframe in [`merge_informative_pair`](https://www.freqtrade.io/en/latest/strategy-customization/#merge_informative_pair) - which can replace probably 20% of your populate_indicators code easily in one line.

For better separation of "informative" with other methods, we also have the [`@informative` decorator](https://www.freqtrade.io/en/latest/strategy-customization/#informative-pairs-decorator-informative) - which will do all the "fetch informative pair, merge with dataframe" for you.
obviously usage of ALL of the above suggestions is up to you - so treat these as what they are - simple suggestions to improve code / readability / reusability.

**Comment by Babak64** [comment]
Dear Matthias,
I wanted to express my deepest gratitude for your exceptional assistance in
resolving my problem. I had been struggling with it for a few days, but you
were able to solve it swiftly and efficiently.

I am also thankful for the additional advice you provided, your insights
were invaluable and greatly helped me in understanding the strategy better.

Once again, thank you I am grateful for your assistance

Best regards, Babak
