### ISSUE TITLE
Having trouble getting this setup properly I don't know where the Strategy goes or how to set it up.

### ISSUE THREAD

**Issue by cometbus** [freqtrade/freqtrade#8462]
2023-04-09 16:05:39,549 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/samson/freqtrade/freqtrade/commands/trade_commands.py", line 24, in start_trading
    worker = Worker(args)
  File "/home/samson/freqtrade/freqtrade/worker.py", line 37, in __init__
    self._init(False)
  File "/home/samson/freqtrade/freqtrade/worker.py", line 53, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/home/samson/freqtrade/freqtrade/freqtradebot.py", line 66, in __init__
    self.strategy: IStrategy = StrategyResolver.load_strategy(self.config)
  File "/home/samson/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 48, in load_strategy
    strategy: IStrategy = StrategyResolver._load_strategy(
  File "/home/samson/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 274, in _load_strategy
    raise OperationalException(
freqtrade.exceptions.OperationalException: Impossible to load Strategy 'SampleStrategy'. This class does not exist or contains Python code errors.

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

The exception is simple, and pretty clear if you ask me - `SampleStrategy` was not found.

This will simply mean that you either didn't follow the [installation docs](https://www.freqtrade.io/en/latest/docker_quickstart/) (due to the missing details, i'll assume docker - please switch to your installation method in the docs for correct commands) completely (missing the `create-userdir` step) - or you renamed the sample strategy class.
