### ISSUE TITLE
freqai - no model found mid-run

### ISSUE THREAD

**Issue by J-cyber0** [freqtrade/freqtrade#8464]
## Describe your environment

  * Operating system: Ubuntu 22.10
  * Python Version: 3.8.10
  * CCXT version: 3.0.26
  * Freqtrade Version: freqtrade docker-2023.3.dev-2860e817 
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

Running FreqAI Live with a static pair list works well 95% of time until I receive an error claiming there is no such file for the trained models on a seemingly random crypto pair. Removing the pair from the list will make it happy for a while until another random crypto pairs trained models file cannot be found. Placing the crypto on the Blacklist works as well. 

### Steps to reproduce:

  1. Run FreqAI bot Live on docker
  2. _____
  3. _____
  
### Observed Results:

  * What happened? Bot sometimes cannot find file for trained models
  * What did you expect to happen? Locate the appropriate file for the crypto pairs

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
 ERROR - Unexpected error [Errno 2] No such file or directory: '/freqtrade/user_data/models/ElixurV5_latest/sub-train-APE_1681086377/cb_ape_1681086377_pca_object.pkl' calling <bound method IStrategy._analyze_ticker_internal of <FreqaiStrategy.FreqaiStrategy object at 0x7f9473d43970>>
Traceback (most recent call last):
  File "/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 27, in wrapper
    return f(*args, **kwargs)
  File "/freqtrade/freqtrade/strategy/interface.py", line 854, in _analyze_ticker_internal
    dataframe = self.analyze_ticker(dataframe, metadata)
  File "/freqtrade/freqtrade/strategy/interface.py", line 832, in analyze_ticker
    dataframe = self.advise_indicators(dataframe, metadata)
  File "/freqtrade/freqtrade/strategy/interface.py", line 1340, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/freqtrade/user_data/strategies/FreqaiStrategy.py", line 107, in populate_indicators
    dataframe = self.freqai.start(dataframe, metadata, self)
  File "/freqtrade/freqtrade/freqai/freqai_interface.py", line 145, in start
    dk = self.start_live(dataframe, metadata, strategy, self.dk)
  File "/freqtrade/freqtrade/freqai/freqai_interface.py", line 407, in start_live
    self.model = self.dd.load_data(metadata["pair"], dk)
  File "/freqtrade/freqtrade/freqai/data_drawer.py", line 555, in load_data
    (dk.data_path / f"{dk.model_filename}_pca_object.pkl").open("rb")
  File "/usr/local/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/freqtrade/user_data/models/ElixurV5_latest/sub-train-APE_1681086377/cb_ape_1681086377_pca_object.pkl'
2023-04-10 03:24:07 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair APE/USDT: [Errno 2] No such file or directory: '/freqtrade/user_data/models/ElixurV5_latest/sub-train-APE_1681086377/cb_ape_1681086377_pca_object.pkl'
2023-04-10 03:24:07 - freqtrade.strategy.interface - WARNING - Outdated history for pair APE/USDT. Last tick is 174 minutes old
  ```

**Comment by robcaulk** [comment]
Hello,

What does "seemingly random" mean? Does that mean it is a pair that is not in your static pair list?

FreqAI is constrained to your config defined pairlist exactly, so if you are seeing a pair come through that is *not* in your static pairlist then it is indicative of some other issue in how you are launching/configuring Freqtrade (read Freqtrade, not necessarily FreqAI).

As we have live demonstrations currently of FreqAI dry running for several months uninterrupted, I am not sure how to recreate your problem. Additionally, we have a strong userbase at the moment who are all running FreqAI dry/live for long periods - we haven't had this reported. 

If I were you, I would first ensure that you are indeed using a static pairlist in your FT config. Next, I would delete all files in the model folder. Then I would restart the dry and watch to see if it occurs again. I suspect it wont. 

Cheers,

Robert

**Comment by robcaulk** [comment]
You may also want to ensure you dont have any other file system cleaning happening in the background (think about file cloud sync failures etc).

**Comment by J-cyber0** [comment]
My apologies. I should clarify that by “seemingly random” I meant a crypto pair within my Static list, but may or may not have an active trade at the moment the error comes up. Also, I am running this bot Live on the MEXC exchange (don’t know if that makes a difference), and my config file is set to a static pair list which I define. Although, I’m running this on a VPS with Linode… perhaps there is something there I can look into.

**Comment by robcaulk** [comment]
Trade status has nothing to do with how FreqAI is training/inferencing your pairs. It will always be training/inferencing your pairs no matter what. It follows the same bot_loop as `populate_indicators()`.

**Comment by J-cyber0** [comment]
Ok

**Comment by xmatthias** [comment]
i somewhat suspect that the problem comes from the api of mexc.

I did some tests with mexc last week - but stopped once i discovered that from the top 20 pairs, only 10 or so are actually available through the api (BTC, ETH, ... all have their api in "maintenance mode" since February).

To me, this suggests one of 2 things - either they intentionally disable the API for high volume pairs - to either benefit themselves from trading against their users - or their API backend is VERY unreliable.

Now if we'd assume the 2nd case (unreliable api), it might mean that pairs disappear / reappear (even though your pairlist is static - that's not guaranteed depending on exchange availability).
Please check your logs VERY carefully about the fact if the pairs you're seeing this problem disappeared / reappeared from the pairlist.
That log-message should look somewhat like `2023-04-10 14:13:33 freqtrade.plugins.pairlistmanager: INFO - Whitelist with ...` - and will contain the full list.
Unfortunately, you'll have to go through the whole list / logs - but if your logs are in a file - you might be able to grep through it somewhat.

**Comment by J-cyber0** [comment]
Thank you .. I have had similar suspicions of this exchange.. with their constant “maintenance” for the most popular crypto pairs and lack of futures trading through API. I’ll look through the logs as suggested but as my lack of confidence in this exchange is growing, I may just try another exchange.. thanks xmatthias

**Comment by J-cyber0** [comment]
Just wanted to update this for future reference. Removing the contents in the models folder seems to have resolved my issue, as robcaulk mentioned in the first comment.
