### ISSUE TITLE
Bot crashed

### ISSUE THREAD

**Issue by tomjrtsmith** [freqtrade/freqtrade#8476]
## Describe your environment

  * Operating system: ____ Ubuntu 22.04
  * Python Version: _____ (`python -V`) 3.11
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker) - a month or so old, won't run freqtrade -V at the moment, whole system crashed see log
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

Bot crashed, first time ever been running for a few months, don't know whether it's a database issue or one of the Python protection handlers has malfunctioned... see log

### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs
```
Apr 10 07:28:41 instance-20220819-1716 freqtrade_ft3a[1378397]: Traceback (most recent call last):
Apr 10 07:28:41 instance-20220819-1716 freqtrade_ft3a[1378397]:   File "/home/ubuntu/freqtrade/.env/bin/freqtrade", line 5, in <module>
Apr 10 07:28:41 instance-20220819-1716 freqtrade_ft3a[1378397]:     from freqtrade.main import main
Apr 10 07:28:41 instance-20220819-1716 freqtrade_ft3a[1378397]:   File "/home/ubuntu/freqtrade/freqtrade/main.py", line 18, in <module>
Apr 10 07:28:41 instance-20220819-1716 freqtrade_ft3a[1378397]:     from freqtrade.commands import Arguments
Apr 10 07:28:41 instance-20220819-1716 freqtrade_ft3a[1378397]:   File "/home/ubuntu/freqtrade/freqtrade/commands/__init__.py", line 12, in <module>
Apr 10 07:28:41 instance-20220819-1716 freqtrade_ft3a[1378397]:     from freqtrade.commands.data_commands import (start_convert_data, start_convert_trades,
Apr 10 07:28:41 instance-20220819-1716 freqtrade_ft3a[1378397]:   File "/home/ubuntu/freqtrade/freqtrade/commands/data_commands.py", line 16, in <module>
Apr 10 07:28:41 instance-20220819-1716 freqtrade_ft3a[1378397]:     from freqtrade.resolvers import ExchangeResolver
Apr 10 07:28:41 instance-20220819-1716 freqtrade_ft3a[1378397]:   File "/home/ubuntu/freqtrade/freqtrade/resolvers/__init__.py", line 9, in <module>
Apr 10 07:28:41 instance-20220819-1716 freqtrade_ft3a[1378397]:     from freqtrade.resolvers.protection_resolver import ProtectionResolver
Apr 10 07:28:41 instance-20220819-1716 freqtrade_ft3a[1378397]:   File "/home/ubuntu/freqtrade/freqtrade/resolvers/protection_resolver.py", line 9, in <module>
Apr 10 07:28:41 instance-20220819-1716 freqtrade_ft3a[1378397]:     from freqtrade.plugins.protections import IProtection
Apr 10 07:28:41 instance-20220819-1716 freqtrade_ft3a[1378397]:   File "/home/ubuntu/freqtrade/freqtrade/plugins/protections/__init__.py", line 2, in <module>
Apr 10 07:28:41 instance-20220819-1716 freqtrade_ft3a[1378397]:     from freqtrade.plugins.protections.iprotection import IProtection, ProtectionReturn
Apr 10 07:28:41 instance-20220819-1716 freqtrade_ft3a[1378397]:   File "/home/ubuntu/freqtrade/freqtrade/plugins/protections/iprotection.py", line 12, in <module>
Apr 10 07:28:41 instance-20220819-1716 freqtrade_ft3a[1378397]:     from freqtrade.persistence import LocalTrade
Apr 10 07:28:41 instance-20220819-1716 freqtrade_ft3a[1378397]:   File "/home/ubuntu/freqtrade/freqtrade/persistence/__init__.py", line 3, in <module>
Apr 10 07:28:41 instance-20220819-1716 freqtrade_ft3a[1378397]:     from freqtrade.persistence.models import init_db
Apr 10 07:28:41 instance-20220819-1716 freqtrade_ft3a[1378397]:   File "/home/ubuntu/freqtrade/freqtrade/persistence/models.py", line 15, in <module>
Apr 10 07:28:41 instance-20220819-1716 freqtrade_ft3a[1378397]:     from freqtrade.persistence.base import ModelBase
Apr 10 07:28:41 instance-20220819-1716 freqtrade_ft3a[1378397]:   File "/home/ubuntu/freqtrade/freqtrade/persistence/base.py", line 2, in <module>
Apr 10 07:28:41 instance-20220819-1716 freqtrade_ft3a[1378397]:     from sqlalchemy.orm import DeclarativeBase, Session, scoped_session
Apr 10 07:28:41 instance-20220819-1716 freqtrade_ft3a[1378397]: ImportError: cannot import name 'DeclarativeBase' from 'sqlalchemy.orm' (/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/sqlalchemy/orm/__init__.py)
```
  ```
  // paste your log here
  ```

**Comment by xmatthias** [comment]
based on the logs, it appears like you ran an incomplete update (updated freqtrade without updating dependencies).

Please follow the [updating documentation](https://www.freqtrade.io/en/latest/updating/) for your particular installation method.

**Comment by tomjrtsmith** [comment]
That's pretty random, I never ran an update... hadn't touched it for
months!?

**Comment by xmatthias** [comment]
you must have - maybe unintentionally by running some git pull or similar.

This error happens when running a recent version of freqtrade with Sqlalchemy < 2.0 installed.

This was added/updated in 2023.3 - or any develop version more recent than March 2nd, when [sqlalchemy2](https://github.com/freqtrade/freqtrade/pull/8264) was merged.

**Comment by tomjrtsmith** [comment]
I ran git pull but on a strategies subdirectory, must have kicked it off
