### ISSUE TITLE
Network error - OKX

### ISSUE THREAD

**Issue by jeffe1024** [freqtrade/freqtrade#8498]
## Describe your environment

  * Operating system: __Windows 10 19043.1526
  * Python Version: __Python 3.10.10
  * CCXT version: Using CCXT 3.0.37
  * Freqtrade:  Version: _freqtrade 2023.3

## Describe the problem:
When I first used freqtrade, I followed the commands in the documentation ： 

> 
![image](https://user-images.githubusercontent.com/39906291/232178093-6c9220f3-e4c6-44fc-bcfd-a6b8858169af.png)

When running the Docker Compose up command to start, the startup fails with an error message: 

> ERROR - Could not load markets, therefore cannot start. Please investigate the above error for more details.

### Steps to reproduce:

  1. docker-compose run --rm freqtrade new-config --config user_data/config.json
  2.docker-compose up
 
  
### Observed Results: 

> What happened? 

1.I hope to connect to OKX and initialize successfully.
2.Trades fail to be created on OKX exchange.

This is my configuration file:
```

{
    "max_open_trades": 3,
    "stake_currency": "USDT",
    "stake_amount": "unlimited",
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "dry_run": true,
    "dry_run_wallet": 1000,
    "cancel_open_orders_on_exit": false,
    "trading_mode": "spot",
    "margin_mode": "",
    "unfilledtimeout": {
        "entry": 10,
        "exit": 10,
        "exit_timeout_count": 0,
        "unit": "minutes"
    },
    "entry_pricing": {
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1,
        "price_last_balance": 0.0,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "exit_pricing":{
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1
    },
    "exchange": {
        "name": "okx",
        "key": "",
        "secret": "",
        "ccxt_config": {},
        "ccxt_async_config": {},
        "pair_whitelist": [
        ],
        "pair_blacklist": [
        ]
    },
    "pairlists": [
        {
            "method": "VolumePairList",
            "number_assets": 20,
            "sort_key": "quoteVolume",
            "min_value": 0,
            "refresh_period": 1800
        }
    ],
    "telegram": {
        "enabled": false,
        "token": "",
        "chat_id": ""
    },
    "api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8080,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "57cd7d6eb790d782af9348db1efa813c4bab207a78f6b492258d7e69106afe5b",
        "ws_token": "itaDetstdqUoXy8kwsNx3xr8wbHlW0cizg",
        "CORS_origins": [],
        "username": "jeffe",
        "password": "123456"
    },
    "bot_name": "freqtrade",
    "initial_state": "running",
    "force_entry_enable": false,
    "internals": {
        "process_throttle_secs": 5
    }
}
```
### Relevant code exceptions or logs

```
Traceback (most recent call last):
2023-04-15 09:56:52   File "/home/ftuser/.local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
2023-04-15 09:56:52     conn = connection.create_connection(
2023-04-15 09:56:52   File "/home/ftuser/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
2023-04-15 09:56:52     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
2023-04-15 09:56:52   File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
2023-04-15 09:56:52     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
2023-04-15 09:56:52 socket.gaierror: [Errno -2] Name or service not known
2023-04-15 09:56:52 
2023-04-15 09:56:52 During handling of the above exception, another exception occurred:
2023-04-15 09:56:52 
2023-04-15 09:56:52 Traceback (most recent call last):
2023-04-15 09:56:52   File "/home/ftuser/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
2023-04-15 09:56:52     httplib_response = self._make_request(
2023-04-15 09:56:52   File "/home/ftuser/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
2023-04-15 09:56:52     self._validate_conn(conn)
2023-04-15 09:56:52   File "/home/ftuser/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
2023-04-15 09:56:52     conn.connect()
2023-04-15 09:56:52   File "/home/ftuser/.local/lib/python3.10/site-packages/urllib3/connection.py", line 363, in connect
2023-04-15 09:56:52     self.sock = conn = self._new_conn()
2023-04-15 09:56:52   File "/home/ftuser/.local/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
2023-04-15 09:56:52     raise NewConnectionError(
2023-04-15 09:56:52 urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f8e2f840430>: Failed to establish a new connection: [Errno -2] Name or service not known
2023-04-15 09:56:52 
2023-04-15 09:56:52 During handling of the above exception, another exception occurred:
2023-04-15 09:56:52 
2023-04-15 09:56:52 Traceback (most recent call last):
2023-04-15 09:56:52   File "/home/ftuser/.local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
2023-04-15 09:56:52     resp = conn.urlopen(
2023-04-15 09:56:52   File "/home/ftuser/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
2023-04-15 09:56:52     retries = retries.increment(
2023-04-15 09:56:52   File "/home/ftuser/.local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
2023-04-15 09:56:52     raise MaxRetryError(_pool, url, error or ResponseError(cause))
2023-04-15 09:56:52 urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.okx.com', port=443): Max retries exceeded with url: /api/v5/public/instruments?instType=SPOT (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e2f840430>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2023-04-15 09:56:52 
2023-04-15 09:56:52 During handling of the above exception, another exception occurred:
2023-04-15 09:56:52 
2023-04-15 09:56:52 Traceback (most recent call last):
2023-04-15 09:56:52   File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 599, in fetch
2023-04-15 09:56:52     response = self.session.request(
2023-04-15 09:56:52   File "/home/ftuser/.local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
2023-04-15 09:56:52     resp = self.send(prep, **send_kwargs)
2023-04-15 09:56:52   File "/home/ftuser/.local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
2023-04-15 09:56:52     r = adapter.send(request, **kwargs)
2023-04-15 09:56:52   File "/home/ftuser/.local/lib/python3.10/site-packages/requests/adapters.py", line 565, in send
2023-04-15 09:56:52     raise ConnectionError(e, request=request)
2023-04-15 09:56:52 requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.okx.com', port=443): Max retries exceeded with url: /api/v5/public/instruments?instType=SPOT (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e2f840430>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2023-04-15 09:56:52 
2023-04-15 09:56:52 The above exception was the direct cause of the following exception:
2023-04-15 09:56:52 
2023-04-15 09:56:52 Traceback (most recent call last):
2023-04-15 09:56:52   File "/freqtrade/freqtrade/exchange/exchange.py", line 485, in _load_markets
2023-04-15 09:56:52     self._markets = self._api.load_markets(params={})
2023-04-15 09:56:52   File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 1458, in load_markets
2023-04-15 09:56:52     markets = self.fetch_markets(params)
2023-04-15 09:56:52   File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/okx.py", line 977, in fetch_markets
2023-04-15 09:56:52     promises.append(self.fetch_markets_by_type(types[i], params))
2023-04-15 09:56:52   File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/okx.py", line 1143, in fetch_markets_by_type
2023-04-15 09:56:52     response = self.publicGetPublicInstruments(self.extend(request, params))
2023-04-15 09:56:52   File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 505, in inner
2023-04-15 09:56:52     return entry(_self, **inner_kwargs)
2023-04-15 09:56:52   File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2932, in request
2023-04-15 09:56:52     return self.fetch2(path, api, method, params, headers, body, config, context)
2023-04-15 09:56:52   File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2929, in fetch2
2023-04-15 09:56:52     return self.fetch(request['url'], request['method'], request['headers'], request['body'])
2023-04-15 09:56:52   File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 652, in fetch
2023-04-15 09:56:52     raise NetworkError(details) from e
2023-04-15 09:56:52 ccxt.base.errors.NetworkError: okx GET https://www.okx.com/api/v5/public/instruments?instType=SPOT
2023-04-15 09:56:52 2023-04-15 01:56:52,572 - freqtrade.commands.trade_commands - ERROR - Could not load markets, therefore cannot start. Please investigate the above error for more details.
2023-04-15 09:56:52 2023-04-15 01:56:52,573 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
2023-04-15 09:56:52 Traceback (most recent call last):
2023-04-15 09:56:52   File "/freqtrade/freqtrade/commands/trade_commands.py", line 24, in start_trading
2023-04-15 09:56:52     worker = Worker(args)
2023-04-15 09:56:52   File "/freqtrade/freqtrade/worker.py", line 37, in __init__
2023-04-15 09:56:52     self._init(False)
2023-04-15 09:56:52   File "/freqtrade/freqtrade/worker.py", line 53, in _init
2023-04-15 09:56:52     self.freqtrade = FreqtradeBot(self._config)
2023-04-15 09:56:52   File "/freqtrade/freqtrade/freqtradebot.py", line 70, in __init__
2023-04-15 09:56:52     self.exchange = ExchangeResolver.load_exchange(
2023-04-15 09:56:52   File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 34, in load_exchange
2023-04-15 09:56:52     exchange = ExchangeResolver._load_exchange(
2023-04-15 09:56:52   File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 60, in _load_exchange
2023-04-15 09:56:52     exchange = ex_class(**kwargs)
2023-04-15 09:56:52   File "/freqtrade/freqtrade/exchange/exchange.py", line 185, in __init__
2023-04-15 09:56:52     self.validate_config(config)
2023-04-15 09:56:52   File "/freqtrade/freqtrade/exchange/exchange.py", line 218, in validate_config
2023-04-15 09:56:52     self.validate_stakecurrency(config['stake_currency'])
2023-04-15 09:56:52   File "/freqtrade/freqtrade/exchange/exchange.py", line 520, in validate_stakecurrency
2023-04-15 09:56:52     raise OperationalException(
2023-04-15 09:56:52 freqtrade.exceptions.OperationalException: Could not load markets, therefore cannot start. Please investigate the above error for more details.
```

**Comment by xmatthias** [comment]
Please provide us with the full exception, not just one line.

Based on this line alone, all we can say is that it's a network error - which is usually a client side network problem (you can't connect to that host somehow).

**Comment by jeffe1024** [comment]
Okay, thank you for your reply. I have improved my question and hope you can help me answer it. Thank you very much

**Comment by xmatthias** [comment]
seems like you're using a (local) proxy...
what's that local proxy do? is it running? is it blocking certain things (like for example, connections to OKX)?

Also, a proxy of 127.0.0.1 in a docker context is ALWAYS wrong - completely preventing all connectivity unless that proxy is running within the SAME container - which is unlikely, assuming you use a regular configuration.

The given configuration is also for sure not generated by `new-config` (we don't assign proxies by default) - but has been modified manually.
Best retry by actually following your reproduction steps (without manual modification of the config file) and let us know.

**Comment by xmatthias** [comment]
The error is a simple network error.
This can mean that you can't access okx from your location / system (try to manually connect to the URL in the logs in your webbrowser).
If that works - reboot your system. 
Docker on windows is known to "sometimes" mess up networking so outbound connections no longer work for no good reason.

If both don't help - then it's a generic docker (networking) problem - where general docker channels will probably be a better help than here.

**Comment by jeffe1024** [comment]
Thank you very much for your patient answer. I have used the Docker Compose up command multiple times to start. Surprisingly, I can now use it normally without making any modifications. A few days ago, I couldn't use it correctly. Why is that?

**Comment by xmatthias** [comment]
I'm not sure i understand your question.
You'll have messed with things until it worked  - probably forgetting along the way what exactly worked / didn't work.

Please note: while we do use docker extensively - and will provide some setup help in regards to docker - we're not a docker support channel - if you have generic questions about docker, please search support in the dedicated channels from the docker project.

**Comment by jeffe1024** [comment]
Okay, I understand what you mean. If I have any Docker related issues, I will seek help from the Docker official channel. If there are any questions related to the freqtrade project, I will consult you again. Because this problem is sporadic

**Comment by jeffe1024** [comment]
Thank you for your continuous help. In my region, an agent is required to access Binance and OKX. So, do I need to configure proxy settings for my config.json

**Comment by jeffe1024** [comment]
The same problem has arisen again. I have modified the initial submission question, can you understand? Thank you very much for your patience in answering my questions

**Comment by xmatthias** [comment]
Let me repeat - it is a NETWORK level issue (always was, and will continue to be).

I'd ask you to not update the initial issue - the messages / logs will change - and this way makes it very difficult to track progress (or to track if the errors change or remain identical).

Based on your prior comment, i assume you brought back your proxy in the config (missing in the updated issue).
The error simply says "failed to establish connection" - so most likely, either your proxy configuration is WRONG (it was clearly wrong before) - or your proxy is only working sporadically.

**Comment by jeffe1024** [comment]
Okay, thank you for your patient answer. It is indeed a problem with the agent configuration and the occasional malfunction of the agent. Thank you again. The error message log corresponds to the problems I have been encountering, and can be used as a reference for partners who encounter similar problems.

**Comment by miaostudy** [comment]
If you need to access OKX through a proxy, you can use the TUN mode of the proxy.
