### ISSUE TITLE
Missing model errors when backtesting Freqai strategy

### ISSUE THREAD

**Issue by deepwat3r** [freqtrade/freqtrade#8529]
## Describe your environment

  * Operating system: Ubuntu
  * Python Version: 3.10.6
  * CCXT version: 3.0.59
  * Freqtrade Version: 2023.4.dev-501a290f8
  
## Your question

I don't believe this to be a bug but I can't find an answer in documentation or other posts so, I appreciate any insight.  I have several strategies involving Freqai and I'm getting this same error on all of them when trying to backtest or hyperopt.  I can run them without error and they function.  I can hyperopt or backtest other non-Freqai strategies.

Based on the logs it seems that the crux of the issue are these missing models, but I'm not understanding why I'm only seeing this issue when backtesting or hyperopting, not trading?

2023-04-20 16:07:00,001 - freqtrade.freqai.freqai_interface - INFO - Could not find model at /home/ubuntu/freqtrade/user_data/models/porknozzle5/sub-train-BTC_1680307200/cb_btc_1680307200

Any suggestions on how to further troubleshoot?

Full log:

(.env) ubuntu@ip-127-0-0-1:~/freqtrade$ freqtrade backtesting --config config_examples/config_freqai.example.json --strategy Porknozzle2 --freqaimodel LightGBMClassifier  --strategy-path freqtrade/strategy --timerange 20230401-20230415
2023-04-20 16:06:56,237 - freqtrade - INFO - freqtrade 2023.4.dev-501a290f8
2023-04-20 16:06:56,249 - freqtrade.configuration.load_config - INFO - Using config: config_examples/config_freqai.example.json ...
2023-04-20 16:06:56,256 - freqtrade.loggers - INFO - Verbosity set to 0
2023-04-20 16:06:56,256 - freqtrade.configuration.configuration - INFO - Using additional Strategy lookup path: freqtrade/strategy
2023-04-20 16:06:56,256 - freqtrade.configuration.configuration - WARNING - `force_entry_enable` RPC message enabled.
2023-04-20 16:06:56,256 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 5 ...
2023-04-20 16:06:56,257 - freqtrade.configuration.configuration - INFO - Parameter --timerange detected: 20230401-20230415 ...
2023-04-20 16:06:56,257 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/ubuntu/freqtrade/user_data ...
2023-04-20 16:06:56,257 - freqtrade.configuration.configuration - INFO - Using data directory: /home/ubuntu/freqtrade/user_data/data/kucoin ...
2023-04-20 16:06:56,257 - freqtrade.configuration.configuration - INFO - Parameter --cache=day detected ...
2023-04-20 16:06:56,257 - freqtrade.configuration.configuration - INFO - Filter trades by timerange: 20230401-20230415
2023-04-20 16:06:56,258 - freqtrade.configuration.configuration - INFO - Using freqaimodel class name: LightGBMClassifier
2023-04-20 16:06:56,258 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2023-04-20 16:06:56,264 - freqtrade.exchange.check_exchange - WARNING - Exchange "kucoin" is known to the the ccxt library, available for the bot, but not officially supported by the Freqtrade development team. It may work flawlessly (please report back) or have serious issues. Use it at your own discretion.
2023-04-20 16:06:56,264 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2023-04-20 16:06:56,264 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2023-04-20 16:06:56,270 - freqtrade.commands.optimize_commands - INFO - Starting freqtrade in Backtesting mode
2023-04-20 16:06:56,270 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2023-04-20 16:06:56,270 - freqtrade.exchange.exchange - INFO - Using CCXT 3.0.59
2023-04-20 16:06:56,280 - freqtrade.exchange.exchange - INFO - Using Exchange "KuCoin"
2023-04-20 16:06:57,215 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Kucoin'...
2023-04-20 16:06:57,234 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy Porknozzle2 from '/home/ubuntu/freqtrade/freqtrade/strategy/porknozzle2.py'...
2023-04-20 16:06:57,234 - freqtrade.strategy.hyper - INFO - Found no parameter file.
2023-04-20 16:06:57,234 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 3m.
2023-04-20 16:06:57,234 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2023-04-20 16:06:57,234 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 200.
2023-04-20 16:06:57,234 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'entry': 10, 'exit': 30, 'exit_timeout_count': 0, 'unit': 'minutes'}.
2023-04-20 16:06:57,234 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'max_open_trades' with value in config file: 5.
2023-04-20 16:06:57,234 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'480': 0.01, '120': 0.02, '60': 0.04, '0': 0.05}
2023-04-20 16:06:57,234 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 3m
2023-04-20 16:06:57,234 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.05
2023-04-20 16:06:57,234 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: True
2023-04-20 16:06:57,235 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive: 0.01
2023-04-20 16:06:57,235 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.02
2023-04-20 16:06:57,235 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: True
2023-04-20 16:06:57,235 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2023-04-20 16:06:57,235 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: True
2023-04-20 16:06:57,235 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'entry': 'limit', 'exit': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False, 'stoploss_on_exchange_interval': 60}
2023-04-20 16:06:57,235 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'entry': 'GTC', 'exit': 'GTC'}
2023-04-20 16:06:57,235 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2023-04-20 16:06:57,235 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 200
2023-04-20 16:06:57,235 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2023-04-20 16:06:57,235 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 30
2023-04-20 16:06:57,235 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'entry': 10, 'exit': 30, 'exit_timeout_count': 0, 'unit': 'minutes'}
2023-04-20 16:06:57,235 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_exit_signal: True
2023-04-20 16:06:57,235 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_only: False
2023-04-20 16:06:57,235 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_entry_signal: False
2023-04-20 16:06:57,235 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_offset: 0.0
2023-04-20 16:06:57,235 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2023-04-20 16:06:57,235 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2023-04-20 16:06:57,235 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: False
2023-04-20 16:06:57,235 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1
2023-04-20 16:06:57,235 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_open_trades: 5
2023-04-20 16:06:57,236 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2023-04-20 16:06:57,240 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from '/home/ubuntu/freqtrade/freqtrade/plugins/pairlist/StaticPairList.py'...
2023-04-20 16:06:57,268 - freqtrade.data.dataprovider - INFO - Increasing startup_candle_count for freqai to 7230
2023-04-20 16:06:57,268 - freqtrade.data.history.history_utils - INFO - Using indicator startup period: 7230 ...
2023-04-20 16:06:57,294 - freqtrade.data.history.idatahandler - WARNING - BTC/USDT, spot, 3m, data starts at 2023-03-30 15:39:00
2023-04-20 16:06:57,337 - freqtrade.data.history.idatahandler - WARNING - ETH/USDT, spot, 3m, data starts at 2023-03-30 15:39:00
2023-04-20 16:06:57,376 - freqtrade.data.history.idatahandler - WARNING - ARB/USDT, spot, 3m, data starts at 2023-03-30 15:39:00
2023-04-20 16:06:57,417 - freqtrade.data.history.idatahandler - WARNING - XRP/USDT, spot, 3m, data starts at 2023-03-30 15:39:00
2023-04-20 16:06:57,458 - freqtrade.data.history.idatahandler - WARNING - DOGE/USDT, spot, 3m, data starts at 2023-03-30 15:39:00
2023-04-20 16:06:57,498 - freqtrade.data.history.idatahandler - WARNING - SOL/USDT, spot, 3m, data starts at 2023-03-30 15:39:00
2023-04-20 16:06:57,538 - freqtrade.data.history.idatahandler - WARNING - ADA/USDT, spot, 3m, data starts at 2023-03-30 15:39:00
2023-04-20 16:06:57,578 - freqtrade.data.history.idatahandler - WARNING - MATIC/USDT, spot, 3m, data starts at 2023-03-30 15:39:00
2023-04-20 16:06:57,619 - freqtrade.data.history.idatahandler - WARNING - FTM/USDT, spot, 3m, data starts at 2023-03-30 15:39:00
2023-04-20 16:06:57,658 - freqtrade.data.history.idatahandler - WARNING - INJ/USDT, spot, 3m, data starts at 2023-03-30 15:39:00
2023-04-20 16:06:57,698 - freqtrade.data.history.idatahandler - WARNING - LTC/USDT, spot, 3m, data starts at 2023-03-30 15:39:00
2023-04-20 16:06:57,738 - freqtrade.data.history.idatahandler - WARNING - BNB/USDT, spot, 3m, data starts at 2023-03-30 15:39:00
2023-04-20 16:06:57,779 - freqtrade.data.history.idatahandler - WARNING - SHIB/USDT, spot, 3m, data starts at 2023-03-30 15:39:00
2023-04-20 16:06:57,820 - freqtrade.data.history.idatahandler - WARNING - VELO/USDT, spot, 3m, data starts at 2023-03-30 15:39:00
2023-04-20 16:06:57,842 - freqtrade.optimize.backtesting - INFO - Loading data from 2023-03-30 15:39:00 up to 2023-04-15 00:00:00 (15 days).
2023-04-20 16:06:57,842 - freqtrade.optimize.backtesting - INFO - Dataload complete. Calculating indicators
2023-04-20 16:06:57,844 - freqtrade.optimize.backtesting - INFO - Running backtesting for Strategy Porknozzle2
2023-04-20 16:06:59,436 - freqtrade.resolvers.iresolver - INFO - Using resolved freqaimodel LightGBMClassifier from '/home/ubuntu/freqtrade/freqtrade/freqai/prediction_models/LightGBMClassifier.py'...
2023-04-20 16:06:59,436 - freqtrade.freqai.freqai_interface - INFO - Backtesting module configured to save all models.
2023-04-20 16:06:59,444 - freqtrade.freqai.data_drawer - INFO - Found existing historic predictions at /home/ubuntu/freqtrade/user_data/models/porknozzle5, but beware that statistics may be inaccurate if the bot has been offline for an extended period of time.
2023-04-20 16:06:59,444 - freqtrade.freqai.freqai_interface - INFO - Set existing queue from trained timestamps. Best approximation queue: deque(['BTC/USDT', 'ETH/USDT', 'ARB/USDT', 'XRP/USDT', 'DOGE/USDT', 'SOL/USDT', 'ADA/USDT', 'MATIC/USDT', 'FTM/USDT', 'INJ/USDT', 'LTC/USDT', 'BNB/USDT', 'SHIB/USDT', 'VELO/USDT'])
2023-04-20 16:06:59,445 - freqtrade.strategy.hyper - INFO - No params for buy found, using default values.
2023-04-20 16:06:59,445 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): buy_rsi = 30
2023-04-20 16:06:59,445 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): exit_short_rsi = 30
2023-04-20 16:06:59,445 - freqtrade.strategy.hyper - INFO - No params for sell found, using default values.
2023-04-20 16:06:59,445 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): sell_rsi = 70
2023-04-20 16:06:59,445 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): short_rsi = 70
2023-04-20 16:06:59,445 - freqtrade.strategy.hyper - INFO - No params for protection found, using default values.
2023-04-20 16:06:59,448 - freqtrade.freqai.freqai_interface - INFO - Training 2 timeranges
2023-04-20 16:06:59,449 - freqtrade.freqai.freqai_interface - INFO - Training BTC/USDT, 1/14 pairs from 2023-03-17 00:00:00 to 2023-04-01 00:00:00, 1/2 trains
**2023-04-20 16:06:59,449 - freqtrade.freqai.data_kitchen - INFO - Could not find backtesting prediction file at /home/ubuntu/freqtrade/user_data/models/porknozzle5/backtesting_predictions/cb_btc_1680307200_prediction.feather**
2023-04-20 16:06:59,453 - freqtrade.data.dataprovider - INFO - Increasing startup_candle_count for freqai to 7230
2023-04-20 16:06:59,475 - freqtrade.data.history.idatahandler - WARNING - BTC/USDT, spot, 3m, data starts at 2023-03-30 15:39:00
2023-04-20 16:06:59,542 - freqtrade.data.dataprovider - INFO - Increasing startup_candle_count for freqai to 7230
2023-04-20 16:06:59,553 - freqtrade.data.history.idatahandler - WARNING - BTC/USDT, spot, 15m, data starts at 2023-03-30 15:45:00
2023-04-20 16:06:59,609 - freqtrade.data.dataprovider - INFO - Increasing startup_candle_count for freqai to 7230
2023-04-20 16:06:59,618 - freqtrade.data.history.idatahandler - WARNING - BTC/USDT, spot, 1h, data starts at 2023-03-30 16:00:00
2023-04-20 16:06:59,700 - freqtrade.data.dataprovider - INFO - Increasing startup_candle_count for freqai to 7230
2023-04-20 16:06:59,720 - freqtrade.data.history.idatahandler - WARNING - ETH/USDT, spot, 3m, data starts at 2023-03-30 15:39:00
2023-04-20 16:06:59,799 - freqtrade.data.dataprovider - INFO - Increasing startup_candle_count for freqai to 7230
2023-04-20 16:06:59,810 - freqtrade.data.history.idatahandler - WARNING - ETH/USDT, spot, 15m, data starts at 2023-03-30 15:45:00
2023-04-20 16:06:59,882 - freqtrade.data.dataprovider - INFO - Increasing startup_candle_count for freqai to 7230
2023-04-20 16:06:59,891 - freqtrade.data.history.idatahandler - WARNING - ETH/USDT, spot, 1h, data starts at 2023-03-30 16:00:00
**2023-04-20 16:07:00,001 - freqtrade.freqai.freqai_interface - INFO - Could not find model at /home/ubuntu/freqtrade/user_data/models/porknozzle5/sub-train-BTC_1680307200/cb_btc_1680307200**
2023-04-20 16:07:00,001 - freqtrade.freqai.base_models.BaseClassifierModel - INFO - -------------------- Starting training BTC/USDT --------------------
2023-04-20 16:07:00,045 - freqtrade.freqai.data_kitchen - INFO - BTC/USDT: dropped 647 training points due to NaNs in populated dataset 647.
2023-04-20 16:07:00,045 - freqtrade.freqai.base_models.BaseClassifierModel - INFO - -------------------- Training on data from 2023-03-30 to 2023-03-31 --------------------
**2023-04-20 16:07:00,045 - freqtrade.freqai.freqai_interface - WARNING - Training BTC/USDT raised exception ValueError. Message: With n_samples=0, test_size=0.33 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters., skipping.**
Traceback (most recent call last):
  File "/home/ubuntu/freqtrade/freqtrade/freqai/freqai_interface.py", line 345, in start_backtesting
    self.model = self.train(dataframe_train, pair, dk)
  File "/home/ubuntu/freqtrade/freqtrade/freqai/base_models/BaseClassifierModel.py", line 53, in train
    data_dictionary = dk.make_train_test_datasets(features_filtered, labels_filtered)
  File "/home/ubuntu/freqtrade/freqtrade/freqai/data_kitchen.py", line 160, in make_train_test_datasets
    ) = train_test_split(
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/sklearn/model_selection/_split.py", line 2448, in train_test_split
    n_train, n_test = _validate_shuffle_split(
  File "/home/ubuntu/freqtrade/.env/lib/python3.10/site-packages/sklearn/model_selection/_split.py", line 2126, in _validate_shuffle_split
    raise ValueError(
ValueError: With n_samples=0, test_size=0.33 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

**Comment by xmatthias** [comment]
this can happen if for example you've modified your pairlist or other model configs without updating the identifier.
you can either change `identifier` - or delete the model directory (`rm -r /home/ubuntu/freqtrade/user_data/models/porknozzle5/*`).

**Comment by deepwat3r** [comment]
@xmatthias Updating the identifier didn't resolve the issue but the exercise put me on the right track.  Root cause appears to be that I was failing to download data for all the timeframes involved in my strategy.  I was missing 1h.  Once I downloaded it, then updated the identifier again, I was able to successfully backtest & hyperopt.

**Comment by homepods** [comment]
dropped 11 training points due to NaNs in populated dataset

**Comment by hippocritical** [comment]
> dropped 11 training points due to NaNs in populated dataset

hi, please dont drag issues out of being closed and please follow the guidelines for new issues - like this giving no info of what you are running etc does not make it able for us to help you. 

Please open a new issue and enter the required info there.
