### ISSUE TITLE
Command for plot-dataframe in FreqAi

### ISSUE THREAD

**Issue by wine10001** [freqtrade/freqtrade#8535]
## Describe your environment
  * Freqtrade Version: ____ (`docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*What is the command for plot-dataframe if I run FreqAi in docker? I got an error for running the command below*
```bash
docker compose -f freqai.yml run --rm freqtrade plot-dataframe -s FreqaiExampleHybridStrategy --freqaimodel XGBoostClassifier --export-filename user_data/backtest_results/backtest-result-2023-04-22_12-33-27.json -i 3m
```
![image](https://user-images.githubusercontent.com/128204373/233786994-4524c1ab-cc4d-4a63-b1b0-3e9519c45436.png)

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

On a quick glance, it seems like you're not passing in a configuration - which is mandatory when running freqAI strategies (no matter in which mode).

**Comment by playma** [comment]
@xmatthias I also got an error for running the command below

```
docker compose -f freqai.yml run --rm freqtrade plot-dataframe  --config user_data/config_freqai.json -s MLStrategy --freqaimodel XGBoostRegressor --timerange=20220118-20221125
```

The error message:

```
2023-04-25 02:32:42,637 - freqtrade - ERROR - Trying to access pretrained model with `identifier` but found different features furnished by current strategy.Change `identifier` to train from scratch, or ensure thestrategy is furnishing the same features as the pretrainedmodel. In case of --strategy-list, please be aware that FreqAI requires all strategies to maintain identical feature_engineering_* functions
```

**Comment by xmatthias** [comment]
well you changed the features (strategy or through freqai config settings) - without resetting the identifier.

you can either delete the model directory, or use a new identifier.

**Comment by playma** [comment]
@xmatthias I'm attempting to plot the FreqAI trading history, but I'm encountering some issues. Here are the steps I've followed:

Step 1. Run backtesting

```bash
docker compose -f freqai.yml run --rm freqtrade backtesting --config user_data/config_freqai.json --strategy MLStrategy --freqaimodel XGBoostRegressor --timerange 20220118-20221125
```

Step2. Run plot-dataframe immediately

```bash
docker compose -f freqai.yml run --rm freqtrade plot-dataframe  --config user_data/config_freqai.json -s MLStrategy --freqaimodel XGBoostRegressor --timerange=20220118-20221125
```

I encountered the following error message:

```bash
2023-04-25 02:32:42,637 - freqtrade - ERROR - Trying to access pretrained model with `identifier` but found different features furnished by current strategy.Change `identifier` to train from scratch, or ensure thestrategy is furnishing the same features as the pretrainedmodel. In case of --strategy-list, please be aware that FreqAI requires all strategies to maintain identical feature_engineering_* functions
```

In Step 2, I modified the identifier:

```bash
docker compose -f freqai.yml run --rm freqtrade plot-dataframe  --config user_data/config_freqai.json -s MLStrategy --freqaimodel XGBoostRegressor --timerange=20220118-20221125
```

I faced the following error message:

```bash
2023-04-25 07:07:53,237 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 42, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/plot_commands.py", line 24, in start_plot_dataframe
    load_and_plot_trades(config)
  File "/freqtrade/freqtrade/plot/plotting.py", line 648, in load_and_plot_trades
    df_analyzed = strategy.analyze_ticker(data, {'pair': pair})
  File "/freqtrade/freqtrade/strategy/interface.py", line 831, in analyze_ticker
    dataframe = self.advise_indicators(dataframe, metadata)
  File "/freqtrade/freqtrade/strategy/interface.py", line 1339, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/freqtrade/user_data/strategies/MLStrategy.py", line 265, in populate_indicators
    dataframe = self.freqai.start(dataframe, metadata, self)
  File "/freqtrade/freqtrade/freqai/freqai_interface.py", line 158, in start
    dk = self.start_backtesting(dataframe, metadata, self.dk, strategy)
  File "/freqtrade/freqtrade/freqai/freqai_interface.py", line 361, in start_backtesting
    self.dd.save_metadata(dk)
  File "/freqtrade/freqtrade/freqai/data_drawer.py", line 424, in save_metadata
    dk.data["training_features_list"] = list(dk.data_dictionary["train_features"].columns)
KeyError: 'train_features'
```

**Comment by playma** [comment]
@xmatthias Do you have any idea? Thank you for your help.

**Comment by xmatthias** [comment]
I'll let you know when i had time to look at this in detail.
There's no logs included - and i'm not sure logs would reveal problems here - so i need some time to test this.

**Comment by CryptoRahino** [comment]
i have the same problem.
i think it relates to:
`2023-05-02 13:30:01,366 - freqtrade.freqai.data_kitchen - WARNING - Removed 12 features from prediction features, these were considered constant values during most recent training.
`
some of my features are daily and the model is running with timeframe 15m, so it could be that some of the features have constant values as they are ffill() to fit the 15m time frame. 
is there a way to configure that constant features won't be removed?
thank you in advance!

**Comment by xmatthias** [comment]
@CryptoRahino not really, no.

The problem is the indicator normalization - which is converting the name to a model friendly name (it's removing `:`).
This seems to be applied too late - and is also causing 2 consecutive backtests without cache (without any change to anything) to show the same error (which is wrong).

we're working on a fix, which should fix this for both consecutive backtests, as well as plot-dataframe (and others ...).
