### ISSUE TITLE
freqtrade.exceptions.OperationalException: Could not load markets, therefore cannot start. Please investigate the above error for more details.

### ISSUE THREAD

**Issue by Goobalexe** [freqtrade/freqtrade#8538]
error:

2023-04-22 23:07:33 2023-04-22 20:07:33,787 - freqtrade.exchange.exchange - ERROR - Unable to initialize markets.
2023-04-22 23:07:33 Traceback (most recent call last):
2023-04-22 23:07:33   File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 625, in fetch
2023-04-22 23:07:33     response.raise_for_status()
2023-04-22 23:07:33   File "/home/ftuser/.local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
2023-04-22 23:07:33     raise HTTPError(http_error_msg, response=self)
2023-04-22 23:07:33 requests.exceptions.HTTPError: 400 Client Error:  for url: https://api.binance.com/sapi/v1/capital/config/getall?timestamp=1682194053100&recvWindow=10000&signature=f9a7e92a85d9ee6fa39219ed1a5813f754ce3ac6b2d72546114100ff94716ba6
2023-04-22 23:07:33 
2023-04-22 23:07:33 During handling of the above exception, another exception occurred:
2023-04-22 23:07:33 
2023-04-22 23:07:33 Traceback (most recent call last):
2023-04-22 23:07:33   File "/freqtrade/freqtrade/exchange/exchange.py", line 485, in _load_markets
2023-04-22 23:07:33     self._markets = self._api.load_markets(params={})
2023-04-22 23:07:33   File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 1457, in load_markets
2023-04-22 23:07:33     currencies = self.fetch_currencies()
2023-04-22 23:07:33   File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/binance.py", line 1625, in fetch_currencies
2023-04-22 23:07:33     response = self.sapiGetCapitalConfigGetall(params)
2023-04-22 23:07:33   File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 505, in inner
2023-04-22 23:07:33     return entry(_self, **inner_kwargs)
2023-04-22 23:07:33   File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/binance.py", line 6923, in request
2023-04-22 23:07:33     response = self.fetch2(path, api, method, params, headers, body, config, context)
2023-04-22 23:07:33   File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2929, in fetch2
2023-04-22 23:07:33     return self.fetch(request['url'], request['method'], request['headers'], request['body'])
2023-04-22 23:07:33   File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 641, in fetch
2023-04-22 23:07:33     skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
2023-04-22 23:07:33   File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/binance.py", line 6901, in handle_errors
2023-04-22 23:07:33     self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
2023-04-22 23:07:33   File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 3238, in throw_exactly_matched_exception
2023-04-22 23:07:33     raise exact[string](message)
2023-04-22 23:07:33 ccxt.base.errors.AuthenticationError: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}
2023-04-22 23:07:33 2023-04-22 20:07:33,789 - freqtrade.commands.trade_commands - ERROR - Could not load markets, therefore cannot start. Please investigate the above error for more details.
2023-04-22 23:07:33 2023-04-22 20:07:33,790 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
2023-04-22 23:07:33 Traceback (most recent call last):
2023-04-22 23:07:33   File "/freqtrade/freqtrade/commands/trade_commands.py", line 24, in start_trading
2023-04-22 23:07:33     worker = Worker(args)
2023-04-22 23:07:33   File "/freqtrade/freqtrade/worker.py", line 37, in __init__
2023-04-22 23:07:33     self._init(False)
2023-04-22 23:07:33   File "/freqtrade/freqtrade/worker.py", line 53, in _init
2023-04-22 23:07:33     self.freqtrade = FreqtradeBot(self._config)
2023-04-22 23:07:33   File "/freqtrade/freqtrade/freqtradebot.py", line 70, in __init__
2023-04-22 23:07:33     self.exchange = ExchangeResolver.load_exchange(
2023-04-22 23:07:33   File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 34, in load_exchange
2023-04-22 23:07:33     exchange = ExchangeResolver._load_exchange(
2023-04-22 23:07:33   File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 60, in _load_exchange
2023-04-22 23:07:33     exchange = ex_class(**kwargs)
2023-04-22 23:07:33   File "/freqtrade/freqtrade/exchange/exchange.py", line 185, in __init__
2023-04-22 23:07:33     self.validate_config(config)
2023-04-22 23:07:33   File "/freqtrade/freqtrade/exchange/exchange.py", line 218, in validate_config
2023-04-22 23:07:33     self.validate_stakecurrency(config['stake_currency'])
2023-04-22 23:07:33   File "/freqtrade/freqtrade/exchange/exchange.py", line 520, in validate_stakecurrency
2023-04-22 23:07:33     raise OperationalException(
2023-04-22 23:07:33 freqtrade.exceptions.OperationalException: Could not load markets, therefore cannot start. Please investigate the above error for more details. 

My config: 
{
    "max_open_trades": 100,
    "stake_currency": "BTC",
    "stake_amount": "unlimited",
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "dry_run": false,
    "dry_run_wallet": 1000,
    "cancel_open_orders_on_exit": false,
    "trading_mode": "spot",
    "margin_mode": "",
    "unfilledtimeout": {
        "entry": 10,
        "exit": 10,
        "exit_timeout_count": 0,
        "unit": "minutes"
    },
    "entry_pricing": {
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1,
        "price_last_balance": 0.0,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "exit_pricing":{
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1
    },
    "exchange": {
        "name": "binance",
        "key": "xxx",
        "secret": "xxx",
        "ccxt_config": {},
        "ccxt_async_config": {},
        "pair_whitelist": [
        ],
        "pair_blacklist": [
            "BNB/.*"
        ]
    },
    "pairlists": [
        {
            "method": "VolumePairList",
            "number_assets": 20,
            "sort_key": "quoteVolume",
            "min_value": 0,
            "refresh_period": 1800
        }
    ],
    "telegram": {
        "enabled": true,
        "token": "xxx",
        "chat_id": "xxx"
    },
    "api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8080,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "0ff28e3d041355c5ae0676fbc72e5e1740491a1f3e94d9c33fcddfce8defc23c",
        "ws_token": "G0JOZSMNqVZcLD6jvWzzMj8qDoFlfuuKCA",
        "CORS_origins": [],
        "username": "freqtrader",
        "password": "1972"
    },
    "bot_name": "freqtrade",
    "initial_state": "running",
    "force_entry_enable": false,
    "internals": {
        "process_throttle_secs": 5
    }
}

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

The error is precisely what it says - `Invalid API-key, IP, or permissions for action.`.
There's nothing to add, really, other than using more words to describe the same exact thing.

It either means that you made a mistake while pasting the api codes (leading/trailing spaces) - or the API key doesn't have the permission for the IP you're running the bot from.

**Comment by Goobalexe** [comment]
Thank you
