### ISSUE TITLE
freqairl backtesting didn't work

### ISSUE THREAD

**Issue by LuciusCao** [freqtrade/freqtrade#8539]
## Describe your environment

  * Operating system: Debian 11 using docker, image:freqtradeorg/freqtrade:develop_freqairl
  * Freqtrade Version: docker-2023.4.dev-9bc17a9
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

I was trying to backtesting using reinforcement learning model, using:
`docker-compose run --rm freqtrade backtesting --timerange=20220501-20220601 -s RLStrategy --freqaimodel RLModel -v`
and was running into the error:

```
2023-04-23 05:30:18,559 - freqtrade - INFO - freqtrade docker-2023.4.dev-9bc17a92
2023-04-23 05:30:18,571 - freqtrade.configuration.load_config - INFO - Using config: user_data/config.json ...
...
...
2023-04-23 05:30:27,525 - freqtrade.strategy.interface - DEBUG - Populating indicators for pair BTC/USDT.
2023-04-23 05:30:27,527 - freqtrade.freqai.freqai_interface - INFO - Training 5 timeranges
2023-04-23 05:30:27,528 - freqtrade.freqai.freqai_interface - INFO - Training BTC/USDT, 1/3 pairs from 2022-04-16 00:00:00 to 2022-05-01 00:00:00, 1/5 trains
2023-04-23 05:30:27,529 - freqtrade.freqai.data_kitchen - INFO - Could not find backtesting prediction file at /freqtrade/user_data/models/uniqe-id/backtesting_predictions/cb_btc_1651363200_prediction.feather
2023-04-23 05:30:27,532 - freqtrade.data.dataprovider - INFO - Increasing startup_candle_count for freqai to 7230
2023-04-23 05:30:29,309 - freqtrade.data.dataprovider - INFO - Increasing startup_candle_count for freqai to 7230
2023-04-23 05:30:29,897 - freqtrade.data.dataprovider - INFO - Increasing startup_candle_count for freqai to 7230
2023-04-23 05:30:30,054 - freqtrade.data.converter - DEBUG - Missing data fillup for BTC/USDT: before: 7969 - after: 7975 - 0.08%
2023-04-23 05:30:30,167 - freqtrade.data.dataprovider - INFO - Increasing startup_candle_count for freqai to 7230
2023-04-23 05:30:31,213 - freqtrade.data.dataprovider - INFO - Increasing startup_candle_count for freqai to 7230
2023-04-23 05:30:31,753 - freqtrade.data.dataprovider - INFO - Increasing startup_candle_count for freqai to 7230
2023-04-23 05:30:32,099 - freqtrade.data.dataprovider - INFO - Increasing startup_candle_count for freqai to 7230
2023-04-23 05:30:33,290 - freqtrade.data.dataprovider - INFO - Increasing startup_candle_count for freqai to 7230
2023-04-23 05:30:33,581 - freqtrade.data.dataprovider - INFO - Increasing startup_candle_count for freqai to 7230
2023-04-23 05:30:33,967 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 42, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 58, in start_backtesting
    backtesting.start()
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 1350, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 1252, in backtest_one_strategy
    preprocessed = self.strategy.advise_all_indicators(data)
  File "/freqtrade/freqtrade/strategy/interface.py", line 1321, in advise_all_indicators
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "/freqtrade/freqtrade/strategy/interface.py", line 1321, in <dictcomp>
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "/freqtrade/freqtrade/strategy/interface.py", line 1339, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/freqtrade/user_data/strategies/rl_strategy.py", line 131, in populate_indicators
    dataframe = self.freqai.start(dataframe, metadata, self)
  File "/freqtrade/freqtrade/freqai/freqai_interface.py", line 158, in start
    dk = self.start_backtesting(dataframe, metadata, self.dk, strategy)
  File "/freqtrade/freqtrade/freqai/freqai_interface.py", line 333, in start_backtesting
    dataframe_train = dk.slice_dataframe(tr_train, dataframe_base_train)
  File "/freqtrade/freqtrade/freqai/data_kitchen.py", line 482, in slice_dataframe
    df = df.loc[(df["date"] >= timerange.startdt) & (df["date"] < timerange.stopdt), :]
AttributeError: 'NoneType' object has no attribute 'loc'
```
For the RL model, I simply copy and paste what I found from the documentation, as shown below:
```
from freqtrade.freqai.prediction_models.ReinforcementLearner import ReinforcementLearner
from freqtrade.freqai.RL.Base5ActionRLEnv import Actions, Base5ActionRLEnv, Positions


class RLModel(ReinforcementLearner):
    """
    User created RL prediction model.

    Save this file to `freqtrade/user_data/freqaimodels`

    then use it with:

    freqtrade trade --freqaimodel MyCoolRLModel --config config.json --strategy SomeCoolStrat

    Here the users can override any of the functions
    available in the `IFreqaiModel` inheritance tree. Most importantly for RL, this
    is where the user overrides `MyRLEnv` (see below), to define custom
    `calculate_reward()` function, or to override any other parts of the environment.

    This class also allows users to override any other part of the IFreqaiModel tree.
    For example, the user can override `def fit()` or `def train()` or `def predict()`
    to take fine-tuned control over these processes.

    Another common override may be `def data_cleaning_predict()` where the user can
    take fine-tuned control over the data handling pipeline.
    """
    class MyRLEnv(Base5ActionRLEnv):
        """
        User made custom environment. This class inherits from BaseEnvironment and gym.env.
        Users can override any functions from those parent classes. Here is an example
        of a user customized `calculate_reward()` function.
        """
        def calculate_reward(self, action: int) -> float:
            # first, penalize if the action is not valid
            if not self._is_valid(action):
                return -2
            pnl = self.get_unrealized_profit()

            factor = 100

            pair = self.pair.replace(':', '')

            # you can use feature values from dataframe
            # Assumes the shifted RSI indicator has been generated in the strategy.
            rsi_now = self.raw_features[f"%-rsi-period-10_shift-1_{pair}_"
                    f"{self.config['timeframe']}"].iloc[self._current_tick]

            # reward agent for entering trades
            if (action in (Actions.Long_enter.value, Actions.Short_enter.value)
                    and self._position == Positions.Neutral):
                if rsi_now < 40:
                    factor = 40 / rsi_now
                else:
                    factor = 1
                return 25 * factor

            # discourage agent from not entering trades
            if action == Actions.Neutral.value and self._position == Positions.Neutral:
                return -1
            max_trade_duration = self.rl_config.get('max_trade_duration_candles', 300)
            trade_duration = self._current_tick - self._last_trade_tick
            if trade_duration <= max_trade_duration:
                factor *= 1.5
            elif trade_duration > max_trade_duration:
                factor *= 0.5
            # discourage sitting in position
            if self._position in (Positions.Short, Positions.Long) and \
                    action == Actions.Neutral.value:
                        return -1 * trade_duration / max_trade_duration
            # close long
            if action == Actions.Long_exit.value and self._position == Positions.Long:
                if pnl > self.profit_aim * self.rr:
                    factor *= self.rl_config['model_reward_parameters'].get('win_reward_factor', 2)
                return float(pnl * factor)
            # close short
            if action == Actions.Short_exit.value and self._position == Positions.Short:
                if pnl > self.profit_aim * self.rr:
                    factor *= self.rl_config['model_reward_parameters'].get('win_reward_factor', 2)
                return float(pnl * factor)
            return 0.
```

For the strategy, I went through the documentation and came up with the following code:
```
class RLStrategy(IStrategy):
    """
    This is a sample strategy to inspire you.
    More information in https://www.freqtrade.io/en/latest/strategy-customization/

    You can:
        :return: a Dataframe with all mandatory indicators for the strategies
    - Rename the class name (Do not forget to update class_name)
    - Add any methods you want to build your strategy
    - Add any lib you need to build your strategy

    You must keep:
    - the lib in the section "Do not remove these libs"
    - the methods: populate_indicators, populate_entry_trend, populate_exit_trend
    You should keep:
    - timeframe, minimal_roi, stoploss, trailing_*
    """
    # Strategy interface version - allow new iterations of the strategy interface.
    # Check the documentation or the Sample strategy to get the latest version.
    INTERFACE_VERSION = 3

    # Can this strategy go short?
    can_short: bool = False

    # Minimal ROI designed for the strategy.
    # This attribute will be overridden if the config file contains "minimal_roi".
    minimal_roi = {
        "60": 0.01,
        "30": 0.02,
        "0": 0.04
    }

    # Optimal stoploss designed for the strategy.
    # This attribute will be overridden if the config file contains "stoploss".
    stoploss = -0.10

    # Trailing stoploss
    trailing_stop = False
    # trailing_only_offset_is_reached = False
    # trailing_stop_positive = 0.01
    # trailing_stop_positive_offset = 0.0  # Disabled / not configured

    # Optimal timeframe for the strategy.
    timeframe = '5m'

    # Run "populate_indicators()" only for new candle.
    process_only_new_candles = True

    # These values can be overridden in the config.
    use_exit_signal = True
    exit_profit_only = False
    ignore_roi_if_entry_signal = False

    # Hyperoptable parameters
    buy_rsi = IntParameter(low=1, high=50, default=30, space='buy', optimize=True, load=True)
    sell_rsi = IntParameter(low=50, high=100, default=70, space='sell', optimize=True, load=True)
    short_rsi = IntParameter(low=51, high=100, default=70, space='sell', optimize=True, load=True)
    exit_short_rsi = IntParameter(low=1, high=50, default=30, space='buy', optimize=True, load=True)

    # Number of candles the strategy requires before producing valid signals
    startup_candle_count: int = 30

    # Optional order type mapping.
    order_types = {
        'entry': 'limit',
        'exit': 'limit',
        'stoploss': 'market',
        'stoploss_on_exchange': False
    }

    # Optional order time in force.
    order_time_in_force = {
        'entry': 'GTC',
        'exit': 'GTC'
    }

    plot_config = {
        'main_plot': {
            'tema': {},
            'sar': {'color': 'white'},
        },
        'subplots': {
            "MACD": {
                'macd': {'color': 'blue'},
                'macdsignal': {'color': 'orange'},
            },
            "RSI": {
                'rsi': {'color': 'red'},
            }
        }
    }

    def informative_pairs(self):
        """
        Define additional, informative pair/interval combinations to be cached from the exchange.
        These pair/interval combinations are non-tradeable, unless they are part
        of the whitelist as well.
        For more information, please consult the documentation
        :return: List of tuples in the format (pair, interval)
            Sample: return [("ETH/USDT", "5m"),
                            ("BTC/USDT", "15m"),
                            ]
        """
        return []

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        # the model will return all labels created by user in `set_freqai_labels()`
        # (& appended targets), an indication of whether or not the prediction should be accepted,
        # the target mean/std values for each of the labels created by user in
        # `feature_engineering_*` for each training period.

        dataframe = self.freqai.start(dataframe, metadata, self)

        return dataframe

    def feature_engineering_expand_all(self, dataframe, period, **kwargs):
        """
        *Only functional with FreqAI enabled strategies*
        This function will automatically expand the defined features on the config defined
        `indicator_periods_candles`, `include_timeframes`, `include_shifted_candles`, and
        `include_corr_pairs`. In other words, a single feature defined in this function
        will automatically expand to a total of
        `indicator_periods_candles` * `include_timeframes` * `include_shifted_candles` *
        `include_corr_pairs` numbers of features added to the model.

        All features must be prepended with `%` to be recognized by FreqAI internals.

        :param df: strategy dataframe which will receive the features
        :param period: period of the indicator - usage example:
        dataframe["%-ema-period"] = ta.EMA(dataframe, timeperiod=period)
        """

        dataframe["%-rsi-period"] = ta.RSI(dataframe, timeperiod=period)
        dataframe["%-mfi-period"] = ta.MFI(dataframe, timeperiod=period)
        dataframe["%-adx-period"] = ta.ADX(dataframe, timeperiod=period)
        dataframe["%-sma-period"] = ta.SMA(dataframe, timeperiod=period)
        dataframe["%-ema-period"] = ta.EMA(dataframe, timeperiod=period)

        return dataframe

    def feature_engineering_expand_basic(self, dataframe, **kwargs):
        """
        *Only functional with FreqAI enabled strategies*
        This function will automatically expand the defined features on the config defined
        `include_timeframes`, `include_shifted_candles`, and `include_corr_pairs`.
        In other words, a single feature defined in this function
        will automatically expand to a total of
        `include_timeframes` * `include_shifted_candles` * `include_corr_pairs`
        numbers of features added to the model.

        Features defined here will *not* be automatically duplicated on user defined
        `indicator_periods_candles`

        All features must be prepended with `%` to be recognized by FreqAI internals.

        :param df: strategy dataframe which will receive the features
        dataframe["%-pct-change"] = dataframe["close"].pct_change()
        dataframe["%-ema-200"] = ta.EMA(dataframe, timeperiod=200)
        """
        dataframe["%-pct-change"] = dataframe["close"].pct_change()
        dataframe["%-raw_volume"] = dataframe["volume"]
        dataframe["%-raw_price"] = dataframe["close"]
        return dataframe

    def feature_engineering_standard(self, dataframe, **kwargs):
        """
        *Only functional with FreqAI enabled strategies*
        This optional function will be called once with the dataframe of the base timeframe.
        This is the final function to be called, which means that the dataframe entering this
        function will contain all the features and columns created by all other
        freqai_feature_engineering_* functions.

        This function is a good place to do custom exotic feature extractions (e.g. tsfresh).
        This function is a good place for any feature that should not be auto-expanded upon
        (e.g. day of the week).

        All features must be prepended with `%` to be recognized by FreqAI internals.

        :param df: strategy dataframe which will receive the features
        usage example: dataframe["%-day_of_week"] = (dataframe["date"].dt.dayofweek + 1) / 7
        """
        # dataframe["%-day_of_week"] = (dataframe["date"].dt.dayofweek + 1) / 7
        # dataframe["%-hour_of_day"] = (dataframe["date"].dt.hour + 1) / 25

        dataframe[f"%-raw_close"] = dataframe["close"]
        dataframe[f"%-raw_open"] = dataframe["open"]
        dataframe[f"%-raw_high"] = dataframe["high"]
        dataframe[f"%-raw_low"] = dataframe["low"]
        return dataframe

    def set_freqai_targets(self, dataframe, **kwargs):
        """
        *Only functional with FreqAI enabled strategies*
        Required function to set the targets for the model.
        All targets must be prepended with `&` to be recognized by the FreqAI internals.

        More details about feature engineering available:

        https://www.freqtrade.io/en/latest/freqai-feature-engineering

        :param df: strategy dataframe which will receive the targets
        usage example: dataframe["&-target"] = dataframe["close"].shift(-1) / dataframe["close"]
        """
        # For RL, there are no direct targets to set. This is filler (neutral)
        # until the agent sends an action.
        dataframe["&-action"] = 0

    def populate_entry_trend(self, df: DataFrame, metadata: dict) -> DataFrame:

        enter_long_conditions = [df["do_predict"] == 1, df["&-action"] == 1]

        if enter_long_conditions:
            df.loc[
                reduce(lambda x, y: x & y, enter_long_conditions), ["enter_long", "enter_tag"]
            ] = (1, "long")

        enter_short_conditions = [df["do_predict"] == 1, df["&-action"] == 3]

        if enter_short_conditions:
            df.loc[
                reduce(lambda x, y: x & y, enter_short_conditions), ["enter_short", "enter_tag"]
            ] = (1, "short")

        return df

    def populate_exit_trend(self, df: DataFrame, metadata: dict) -> DataFrame:
        exit_long_conditions = [df["do_predict"] == 1, df["&-action"] == 2]
        if exit_long_conditions:
            df.loc[reduce(lambda x, y: x & y, exit_long_conditions), "exit_long"] = 1

        exit_short_conditions = [df["do_predict"] == 1, df["&-action"] == 4]
        if exit_short_conditions:
            df.loc[reduce(lambda x, y: x & y, exit_short_conditions), "exit_short"] = 1

        return df
```

I'm pretty sure I have downloaded all the required data, including all types of timeframes (1m,3m,15m,1h used in the model) and including all pairs, BTC/USDT, ETH/USDT, LTC/USDT from 20180101 to now, and BTC/USDT:USDT, ETH/USDT:USDT used in `include_corr_pairlist`. 

However I couldn't find any reason from the documentation and from the Exception, so I submitted it here.

And another question I have here, is why the dataprovider increases the startup candle to 7230, as show below:
`2023-04-23 05:30:27,532 - freqtrade.data.dataprovider - INFO - Increasing startup_candle_count for freqai to 7230`
I think it's 7200 + 30(in the strategy), but where does that 7200 come from?

**Comment by xmatthias** [comment]
after a quick glance at the strategy, i'd say that `set_freqai_targets()` must return the dataframe as well. 

In python, if you don't return anything, it'll result in an implicit `return None` at the end of the function - which will lead to the subsequent result being empty.

I realize the documentation is wrong for this method - which will be fixed shortly (c5dc21e80c41322a6551a3d1d53b05d474156c85)

**Comment by LuciusCao** [comment]
Thank you for your reply. I'll try it later. How about the other question?
>why the dataprovider increases the startup candle to 7230, as show below:
`2023-04-23 05:30:27,532 - freqtrade.data.dataprovider - INFO - Increasing startup_candle_count for freqai to 7230`
I think it's 7200 + 30(in the strategy), but where does that 7200 come from?

**Comment by xmatthias** [comment]
> I think it's 7200 + 30(in the strategy), but where does that 7200 come from?

I've somewhat missed that part.
It's a combination of your freqAI settings to make sure your training succeeds, based on how much data is actually necessary.
roughly, it's a combination of `indicator_periods_candles + train_period_days + given startup candle count` (obviously they potentially have different units, so conversions are applied, therefore the ACTUAL math is not as simple as the demo addition here).

**Comment by LuciusCao** [comment]
Thank you for your detailed explanation! I just tried `return dataframe` in the code, it worked.
