### ISSUE TITLE
Maintence margin rate causes fatal exception

### ISSUE THREAD

**Issue by tomjrtsmith** [freqtrade/freqtrade#8541]
## Describe your environment

  * Operating system: ____ Ubuntu 22.04
  * Python Version: _____ (`python -V`) 3.11
  * CCXT version: _____ (`pip freeze | grep ccxt`) ccxt==2.6.26
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker) freqtrade 2023.1.dev-7092212ed

  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

I noticed one of my bots was crashing periodically and caught it just now, it seems to crash executing orders, I've pasted the log below

### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
True, leverage=1.0, open_rate=8.09500000, open_since=2023-04-23 23:26:42)
Apr 23 23:26:51 instance-20221009-1127 freqtrade.freqtradebot - INFO - Found open order for Trade(id=244, pair=FXS/USDT:USDT, amount=5.58269644, is_short=True, leverage=1.0, open_rate=8.09500000, open_since=2023-04-23 23:26:42)
Apr 23 23:26:51 instance-20221009-1127 freqtrade_a[1263153]: 2023-04-23 23:26:51,961 - freqtrade.freqtradebot - INFO - Fee for Trade Trade(id=244, pair=FXS/USDT:USDT, amount=5.58269644, is_short=True, leverage=1.0, open_rate=8.09500000, open_since=2023-04-23 23:26:42) [sell]: 0.0089056 USDT - rate: 0.0002
Apr 23 23:26:51 instance-20221009-1127 freqtrade.freqtradebot - INFO - Fee for Trade Trade(id=244, pair=FXS/USDT:USDT, amount=5.58269644, is_short=True, leverage=1.0, open_rate=8.09500000, open_since=2023-04-23 23:26:42) [sell]: 0.0089056 USDT - rate: 0.0002
Apr 23 23:26:51 instance-20221009-1127 freqtrade_a[1263153]: 2023-04-23 23:26:51,962 - freqtrade.persistence.trade_model - INFO - Updating trade (id=244) ...
Apr 23 23:26:51 instance-20221009-1127 freqtrade.persistence.trade_model - INFO - Updating trade (id=244) ...
Apr 23 23:26:51 instance-20221009-1127 freqtrade_a[1263153]: 2023-04-23 23:26:51,962 - freqtrade.persistence.trade_model - INFO - LIMIT_SELL has been fulfilled for Trade(id=244, pair=FXS/USDT:USDT, amount=5.50000000, is_short=True, leverage=1.0, open_rate=8.09600000, open_since=2023-04-23 23:26:42).
Apr 23 23:26:51 instance-20221009-1127 freqtrade.persistence.trade_model - INFO - LIMIT_SELL has been fulfilled for Trade(id=244, pair=FXS/USDT:USDT, amount=5.50000000, is_short=True, leverage=1.0, open_rate=8.09600000, open_since=2023-04-23 23:26:42).
Apr 23 23:26:51 instance-20221009-1127 freqtrade_a[1263153]: 2023-04-23 23:26:51,980 - freqtrade.commands.trade_commands - ERROR - Maintenance margin rate for FXS/USDT:USDT is unavailable for Binance
Apr 23 23:26:51 instance-20221009-1127 freqtrade.commands.trade_commands - ERROR - Maintenance margin rate for FXS/USDT:USDT is unavailable for Binance
Apr 23 23:26:52 instance-20221009-1127 freqtrade_a[1263153]: 2023-04-23 23:26:51,983 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Apr 23 23:26:52 instance-20221009-1127 freqtrade_a[1263153]: Traceback (most recent call last):
Apr 23 23:26:52 instance-20221009-1127 freqtrade_a[1263153]:   File "/home/ubuntu/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
Apr 23 23:26:52 instance-20221009-1127 freqtrade_a[1263153]:     worker.run()
Apr 23 23:26:52 instance-20221009-1127 freqtrade_a[1263153]:   File "/home/ubuntu/freqtrade/freqtrade/worker.py", line 75, in run
Apr 23 23:26:52 instance-20221009-1127 freqtrade_a[1263153]:     state = self._worker(old_state=state)
Apr 23 23:26:52 instance-20221009-1127 freqtrade_a[1263153]:   File "/home/ubuntu/freqtrade/freqtrade/worker.py", line 116, in _worker
Apr 23 23:26:52 instance-20221009-1127 freqtrade_a[1263153]:     self._throttle(func=self._process_running, throttle_secs=self._throttle_secs,
Apr 23 23:26:52 instance-20221009-1127 freqtrade_a[1263153]:   File "/home/ubuntu/freqtrade/freqtrade/worker.py", line 147, in _throttle
Apr 23 23:26:52 instance-20221009-1127 freqtrade_a[1263153]:     result = func(*args, **kwargs)
Apr 23 23:26:52 instance-20221009-1127 freqtrade_a[1263153]:   File "/home/ubuntu/freqtrade/freqtrade/worker.py", line 180, in _process_running
Apr 23 23:26:52 instance-20221009-1127 freqtrade_a[1263153]:     self.freqtrade.process()
Apr 23 23:26:52 instance-20221009-1127 freqtrade_a[1263153]:   File "/home/ubuntu/freqtrade/freqtrade/freqtradebot.py", line 221, in process
Apr 23 23:26:52 instance-20221009-1127 freqtrade_a[1263153]:     self.manage_open_orders()
Apr 23 23:26:52 instance-20221009-1127 freqtrade_a[1263153]:   File "/home/ubuntu/freqtrade/freqtrade/freqtradebot.py", line 1249, in manage_open_orders
Apr 23 23:26:52 instance-20221009-1127 freqtrade_a[1263153]:     fully_cancelled = self.update_trade_state(trade, trade.open_order_id, order)
Apr 23 23:26:52 instance-20221009-1127 freqtrade_a[1263153]:   File "/home/ubuntu/freqtrade/freqtrade/freqtradebot.py", line 1786, in update_trade_state
Apr 23 23:26:52 instance-20221009-1127 freqtrade_a[1263153]:     trade.set_liquidation_price(self.exchange.get_liquidation_price(
Apr 23 23:26:52 instance-20221009-1127 freqtrade_a[1263153]:   File "/home/ubuntu/freqtrade/freqtrade/exchange/exchange.py", line 2706, in get_liquidation_price
Apr 23 23:26:52 instance-20221009-1127 freqtrade_a[1263153]:     isolated_liq = self.dry_run_liquidation_price(
Apr 23 23:26:52 instance-20221009-1127 freqtrade_a[1263153]:   File "/home/ubuntu/freqtrade/freqtrade/exchange/binance.py", line 187, in dry_run_liquidation_price
Apr 23 23:26:52 instance-20221009-1127 freqtrade_a[1263153]:     mm_ratio, maintenance_amt = self.get_maintenance_ratio_and_amt(pair, stake_amount)
Apr 23 23:26:52 instance-20221009-1127 freqtrade_a[1263153]:   File "/home/ubuntu/freqtrade/freqtrade/exchange/exchange.py", line 2811, in get_maintenance_ratio_and_amt
Apr 23 23:26:52 instance-20221009-1127 freqtrade_a[1263153]:     raise InvalidOrderException(
Apr 23 23:26:52 instance-20221009-1127 freqtrade_a[1263153]: freqtrade.exceptions.InvalidOrderException: Maintenance margin rate for FXS/USDT:USDT is unavailable for Binance
Apr 23 23:26:52 instance-20221009-1127 freqtrade_a[1263153]: 2023-04-23 23:26:52,038 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
Apr 23 23:26:52 instance-20221009-1127 freqtrade_a[1263153]: 2023-04-23 23:26:52,038 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
Apr 23 23:26:52 instance-20221009-1127 freqtrade_a[1263153]: 2023-04-23 23:26:52,050 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
Apr 23 23:26:52 instance-20221009-1127 freqtrade_a[1263153]: 2023-04-23 23:26:52,059 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': warning, 'status': "3 open trades active.\n\nHandle these trades manually on Binance, or '/start' the bot again and use '/stopentry' to handle open trades gracefully. \nNote: Trades are simulated (dry run)."}
Apr 23 23:26:52 instance-20221009-1127 freqtrade_a[1263153]: 2023-04-23 23:26:52,092 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
Apr 23 23:26:52 instance-20221009-1127 freqtrade_a[1263153]: 2023-04-23 23:26:52,092 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.apiserver ...
Apr 23 23:26:52 instance-20221009-1127 freqtrade_a[1263153]: 2023-04-23 23:26:52,092 - freqtrade.rpc.api_server.webserver - INFO - Stopping API Server
  ```

**Comment by xmatthias** [comment]
Your version is outdated - and therefore most likely contains an outdated leverage tier file.

Please let me know if this same error repeats on the very latest version (2023.3 or develop >=2023.4).

**Comment by xmatthias** [comment]
Gonna assume this was fixed after the update ... Feel free to let me know if you still encounter this with the latest version (2023.4 or later) (please include the stacktrace for this as well).
