### ISSUE TITLE
Error after Updated from 2023.3 to 2023.4

### ISSUE THREAD

**Issue by segatrade** [freqtrade/freqtrade#8557]
## Describe your environment

  * Operating system: Ubuntu 22.04.2
  * Python Version: 3.8.16 (`python -V`)
  * CCXT version: 3.0.75 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2023.4 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

  1. On 2023.3 trade worked fine almost month
  2. Updated from 2023.3 to 2023.4 . Nothing changed
  3. Run trade again
  
### Observed Results:

  * What happened?
 Got error
  * What did you expect to happen?
  Work as before

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

 ```
2023-04-26 11:19:41,819 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2023-04-26 11:19:41,822 - freqtrade.exchange.exchange - INFO - Using CCXT 3.0.75
2023-04-26 11:19:41,822 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2023-04-26 11:19:41,830 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 200}
2023-04-26 11:19:41,837 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2023-04-26 11:19:54,996 - freqtrade.exchange.exchange - ERROR - Unable to initialize markets.
Traceback (most recent call last):
  File "/home/usr0/venvpy38/lib/python3.8/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/usr0/venvpy38/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/usr0/venvpy38/lib/python3.8/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/home/usr0/venvpy38/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/usr0/venvpy38/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1114: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/usr0/venvpy38/lib/python3.8/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/usr0/venvpy38/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/usr0/venvpy38/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/usr0/venvpy38/lib/python3.8/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/home/usr0/venvpy38/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/usr0/venvpy38/lib/python3.8/site-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/home/usr0/venvpy38/lib/python3.8/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='fapi.binance.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/usr0/venvpy38/lib/python3.8/site-packages/ccxt/base/exchange.py", line 601, in fetch
    response = self.session.request(
  File "/home/usr0/venvpy38/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/usr0/venvpy38/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/usr0/venvpy38/lib/python3.8/site-packages/requests/adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='fapi.binance.com', port=443): Read timed out. (read timeout=10)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/usr0/venvpy38/lib/python3.8/site-packages/freqtrade/exchange/exchange.py", line 487, in _load_markets
    self._markets = self._api.load_markets(params={})
  File "/home/usr0/venvpy38/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1459, in load_markets
    markets = self.fetch_markets(params)
  File "/home/usr0/venvpy38/lib/python3.8/site-packages/ccxt/binance.py", line 1805, in fetch_markets
    promises.append(self.fapiPublicGetExchangeInfo(params))
  File "/home/usr0/venvpy38/lib/python3.8/site-packages/ccxt/base/exchange.py", line 507, in inner
    return entry(_self, **inner_kwargs)
  File "/home/usr0/venvpy38/lib/python3.8/site-packages/ccxt/binance.py", line 6987, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/usr0/venvpy38/lib/python3.8/site-packages/ccxt/base/exchange.py", line 2886, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/usr0/venvpy38/lib/python3.8/site-packages/ccxt/base/exchange.py", line 631, in fetch
    raise RequestTimeout(details) from e
ccxt.base.errors.RequestTimeout: binance GET https://fapi.binance.com/fapi/v1/exchangeInfo
2023-04-26 11:19:55,002 - freqtrade.commands.trade_commands - ERROR - Could not load markets, therefore cannot start. Please investigate the above error for more details.
2023-04-26 11:19:55,002 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/usr0/venvpy38/lib/python3.8/site-packages/freqtrade/commands/trade_commands.py", line 24, in start_trading
    worker = Worker(args)
  File "/home/usr0/venvpy38/lib/python3.8/site-packages/freqtrade/worker.py", line 37, in __init__
    self._init(False)
  File "/home/usr0/venvpy38/lib/python3.8/site-packages/freqtrade/worker.py", line 53, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/home/usr0/venvpy38/lib/python3.8/site-packages/freqtrade/freqtradebot.py", line 72, in __init__
    self.exchange = ExchangeResolver.load_exchange(
  File "/home/usr0/venvpy38/lib/python3.8/site-packages/freqtrade/resolvers/exchange_resolver.py", line 34, in load_exchange
    exchange = ExchangeResolver._load_exchange(
  File "/home/usr0/venvpy38/lib/python3.8/site-packages/freqtrade/resolvers/exchange_resolver.py", line 60, in _load_exchange
    exchange = ex_class(**kwargs)
  File "/home/usr0/venvpy38/lib/python3.8/site-packages/freqtrade/exchange/exchange.py", line 187, in __init__
    self.validate_config(config)
  File "/home/usr0/venvpy38/lib/python3.8/site-packages/freqtrade/exchange/exchange.py", line 220, in validate_config
    self.validate_stakecurrency(config['stake_currency'])
  File "/home/usr0/venvpy38/lib/python3.8/site-packages/freqtrade/exchange/exchange.py", line 522, in validate_stakecurrency
    raise OperationalException(
freqtrade.exceptions.OperationalException: Could not load markets, therefore cannot start. Please investigate the above error for more details.

  ```

**Comment by segatrade** [comment]
I'm sorry, seems because got req from develop pandas == 2.0.1. On 1.5.3 gone. Should I delete issue?
