### ISSUE TITLE
Can't start freqtrade with mysql database

### ISSUE THREAD

**Issue by matthieu-hm** [freqtrade/freqtrade#8561]
## Describe your environment

  * Operating system: Ubuntu 22.04
  * Python Version: Python 3.10.9
  * CCXT version: ccxt==3.0.75
  * Freqtrade Version: freqtrade 2023.4 (stable)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

Can't start freqtrade with mysql database

### Steps to reproduce:
1. Install freqtrade
```bash
git clone git@github.com:freqtrade/freqtrade.git
cd freqtrade
git checkout stable

./setup.sh -i # default response for everything
source .env/bin/activate
pip install pymysql
```

2. Copy a strategy: [user_data/strategies/Strategy001.py](https://raw.githubusercontent.com/freqtrade/freqtrade-strategies/main/user_data/strategies/Strategy001.py)

3. Generate config.json
```bash
freqtrade new-config --config user_data/config.json  # default response for everything
```

4. Add db_url to `config.json`:
```js
"db_url": "mysql+pymysql://db_user:db_password@127.0.0.1:3306/db_name",
```

5. Start freqtrade:
```bash
freqtrade trade --userdir user_data --strategy Strategy001 --config user_data/config.json
```
  
### Observed Results:

```
2023-04-27 11:25:52,726 - freqtrade.commands.trade_commands - ERROR - (in table 'KeyValueStore', column 'string_value'): VARCHAR requires a length on dialect mysql
2023-04-27 11:25:52,726 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
```

### Relevant code exceptions or logs

  ```
2023-04-27 11:25:52,726 - freqtrade.commands.trade_commands - ERROR - (in table 'KeyValueStore', column 'string_value'): VARCHAR requires a length on dialect mysql
2023-04-27 11:25:52,726 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/matt/DEV/tmp/ft-2304/.env/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 6442, in visit_create_table
    processed = self.process(
  File "/home/matt/DEV/tmp/ft-2304/.env/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 910, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/home/matt/DEV/tmp/ft-2304/.env/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 143, in _compiler_dispatch
    return meth(self, **kw)  # type: ignore  # noqa: E501
  File "/home/matt/DEV/tmp/ft-2304/.env/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 6473, in visit_create_column
    text = self.get_column_specification(column, first_pk=first_pk)
  File "/home/matt/DEV/tmp/ft-2304/.env/lib/python3.10/site-packages/sqlalchemy/dialects/mysql/base.py", line 1769, in get_column_specification
    self.dialect.type_compiler_instance.process(
  File "/home/matt/DEV/tmp/ft-2304/.env/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 955, in process
    return type_._compiler_dispatch(self, **kw)
  File "/home/matt/DEV/tmp/ft-2304/.env/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 143, in _compiler_dispatch
    return meth(self, **kw)  # type: ignore  # noqa: E501
  File "/home/matt/DEV/tmp/ft-2304/.env/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 7027, in visit_string
    return self.visit_VARCHAR(type_, **kw)
  File "/home/matt/DEV/tmp/ft-2304/.env/lib/python3.10/site-packages/sqlalchemy/dialects/mysql/base.py", line 2267, in visit_VARCHAR
    raise exc.CompileError(
sqlalchemy.exc.CompileError: VARCHAR requires a length on dialect mysql

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/matt/DEV/tmp/ft-2304/freqtrade/commands/trade_commands.py", line 24, in start_trading
    worker = Worker(args)
  File "/home/matt/DEV/tmp/ft-2304/freqtrade/worker.py", line 37, in __init__
    self._init(False)
  File "/home/matt/DEV/tmp/ft-2304/freqtrade/worker.py", line 53, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/home/matt/DEV/tmp/ft-2304/freqtrade/freqtradebot.py", line 75, in __init__
    init_db(self.config['db_url'])
  File "/home/matt/DEV/tmp/ft-2304/freqtrade/persistence/models.py", line 83, in init_db
    ModelBase.metadata.create_all(engine)
  File "/home/matt/DEV/tmp/ft-2304/.env/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 5796, in create_all
    bind._run_ddl_visitor(
  File "/home/matt/DEV/tmp/ft-2304/.env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3239, in _run_ddl_visitor
    conn._run_ddl_visitor(visitorcallable, element, **kwargs)
  File "/home/matt/DEV/tmp/ft-2304/.env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2443, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/home/matt/DEV/tmp/ft-2304/.env/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 670, in traverse_single
    return meth(obj, **kw)
  File "/home/matt/DEV/tmp/ft-2304/.env/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 922, in visit_metadata
    self.traverse_single(
  File "/home/matt/DEV/tmp/ft-2304/.env/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 670, in traverse_single
    return meth(obj, **kw)
  File "/home/matt/DEV/tmp/ft-2304/.env/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 961, in visit_table
    )._invoke_with(self.connection)
  File "/home/matt/DEV/tmp/ft-2304/.env/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 315, in _invoke_with
    return bind.execute(self)
  File "/home/matt/DEV/tmp/ft-2304/.env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1413, in execute
    return meth(
  File "/home/matt/DEV/tmp/ft-2304/.env/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 181, in _execute_on_connection
    return connection._execute_ddl(
  File "/home/matt/DEV/tmp/ft-2304/.env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1522, in _execute_ddl
    compiled = ddl.compile(
  File "/home/matt/DEV/tmp/ft-2304/.env/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 280, in compile
    return self._compiler(dialect, **kw)
  File "/home/matt/DEV/tmp/ft-2304/.env/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 69, in _compiler
    return dialect.ddl_compiler(dialect, self, **kw)
  File "/home/matt/DEV/tmp/ft-2304/.env/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 865, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/home/matt/DEV/tmp/ft-2304/.env/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 910, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/home/matt/DEV/tmp/ft-2304/.env/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 143, in _compiler_dispatch
    return meth(self, **kw)  # type: ignore  # noqa: E501
  File "/home/matt/DEV/tmp/ft-2304/.env/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 6452, in visit_create_table
    raise exc.CompileError(
sqlalchemy.exc.CompileError: (in table 'KeyValueStore', column 'string_value'): VARCHAR requires a length on dialect mysql
  ```

**Comment by xmatthias** [comment]
If i'm perfectly honest, then this is a bug in sqlalchemy (or at least a mishap in their documentation).

The way we define the model (`string_value: Mapped[Optional[str]]`)  is exactly how it's also shown in the [ORM Quick start](https://docs.sqlalchemy.org/en/20/orm/quickstart.html#declare-models) - i therefore don't really see why this would be wrong.

Please report this as issue to sqlalchemy and link the issue here, thanks.

We'll eventually fix this by working around this bug - but it currently has no priority, and i'd like to wait for the answer from sqlalchemy on this topic.

**Comment by bzed** [comment]
@xmatthias The sqlalchemy example is for sqlite, the requirement for a varchar length limit is a mysql weirdness - and if one wants to support Mysql there is no real way around specifying the length of a string. That should work fine with other database types. Using Text() might also be an option. Or something like ```sqlalchemy.Text().with_variant(sqlalchemy.dialects.mysql.TINYTEXT, "mysql"))``` (or the other TEXT variants, whatever fits).

Its nothing that can be fixed in sqlalchemy as they can't guess whats an appropriate default for the length of the VARCHAR. Its up to the programmer to specify it.

https://docs.sqlalchemy.org/en/20/core/type_basics.html#sqlalchemy.types.VARCHAR
_length – optional, a length for the column for use in DDL and CAST expressions. May be safely omitted if no CREATE TABLE will be issued. Certain databases may require a length for use in DDL, and will raise an exception when the CREATE TABLE DDL is issued if a VARCHAR with no length is included. Whether the value is interpreted as bytes or characters is database specific._

**Comment by xmatthias** [comment]
@bzed i'm aware of this, but the docs shouldn't use something as example if its against best practice, and will fail for random databases. That makes that part of the docs misleading 

I also see it as either a bug, or arrogance/ ignorance by the sqlalchemy folks to not have a fallback like other databases. Varchar(max) IS the appropriate type, corresponding to the approach other databases follow for this.

---

We also should make one thing clear, we try to keep all sqlalchemy supported systems working (also based on the assumption that a database generalization layer doesnt have buggy and missleading code samples), but only sqlite is actively supported and tested against.

**Comment by bzed** [comment]
> I also see it as either a bug, or arrogance/ ignorance by the sqlalchemy folks to not have a fallback like other databases. Varchar(max) IS the appropriate type, corresponding to the approach other databases follow for this.

Again, thats nothing sqlalchemy decided on for other databases, thats what the databases do. The only database I know that wines about varchar without length is mysql.
