### ISSUE TITLE
Visualise backtest results with webserver using FreqAI strategies

### ISSUE THREAD

**Issue by Chrisvandr** [freqtrade/freqtrade#8566]
## Describe your environment

  * Operating system: Ubuntu (wsl)
  * Python Version: 3.10.1 (`python -V`)
  * CCXT version: 3.0.62 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2023.3 & also tried on develop (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Describe the problem:

**I'm unable to visualise the backtest results with the webserver using FreqAI strategies.** 

My synopsis (following the traceback); it seems it loses track of the freqai config after backtesting. The 'visualise result' in the webserver needs data for a pair, which calls the rpc endpoint `_rpc_analysed_history_full`, where it calls strategy.ft_bot_start() -> load_freqAI_model(), where it tries to load the freqaimodel again, but the reference is lost. 
I tried hardcoding the freqai config in the strategy itself, but this just made it fail at some other element of the config missing (i.e. it would then start asking for the timerange (in the config)).

```
    enable_freqai: bool = True

    def __init__(self, config: dict) -> None:
        if self.enable_freqai:
            config["freqai"] = self.local_freqai_config
            config["freqaimodel"] = "CatboostClassifier"
            # config["timerange"] = "20230128-20230224"

        super().__init__(config)
```

### Steps to reproduce:

Using the `FreqaiExampleStrategy.py` or `FreqaiHybridStrategy.py` in the develop branch.
  1. spin up the webserver for backtesting `freqtrade webserver --config user_data/strategies/FreqAI/config.json`
  2. In Webserver, 'Run Backtest', check enable freqai, set freqaimodel, set start and end date. Run the backtest on some days.
  3. Trains model and backtest, which succeed.
  4. Check out Analyse Result/Visualise summary, which both work fine.
  5. Go to Visualise Result, and it fails with the below traceback.
  
### Observed Results:

  * Expect to see the backtest results for a pair with trades

(I really like using the webserver for visualising backtesting results, hopefully i can continue to do so for freqai strats as well!)

### Relevant code exceptions or logs
  
```
Traceback (most recent call last):
  File "/home/chris/git/freqtrade/.env/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 429, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/chris/git/freqtrade/.env/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/chris/git/freqtrade/.env/lib/python3.10/site-packages/uvicorn/middleware/message_logger.py", line 86, in __call__
    raise exc from None
  File "/home/chris/git/freqtrade/.env/lib/python3.10/site-packages/uvicorn/middleware/message_logger.py", line 82, in __call__
    await self.app(scope, inner_receive, inner_send)
  File "/home/chris/git/freqtrade/.env/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/home/chris/git/freqtrade/.env/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/chris/git/freqtrade/.env/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/chris/git/freqtrade/.env/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/chris/git/freqtrade/.env/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/home/chris/git/freqtrade/.env/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/chris/git/freqtrade/.env/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/chris/git/freqtrade/.env/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/chris/git/freqtrade/.env/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/chris/git/freqtrade/.env/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/chris/git/freqtrade/.env/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/chris/git/freqtrade/.env/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/chris/git/freqtrade/.env/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/home/chris/git/freqtrade/.env/lib/python3.10/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/chris/git/freqtrade/.env/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/chris/git/freqtrade/.env/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/chris/git/freqtrade/.env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/chris/git/freqtrade/.env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/chris/git/freqtrade/freqtrade/rpc/api_server/api_v1.py", line 256, in pair_history
    return RPC._rpc_analysed_history_full(config, pair, timeframe, timerange, exchange)
  File "/home/chris/git/freqtrade/freqtrade/rpc/rpc.py", line 1215, in _rpc_analysed_history_full
    strategy.ft_bot_start()
  File "/home/chris/git/freqtrade/freqtrade/strategy/interface.py", line 187, in ft_bot_start
    self.load_freqAI_model()
  File "/home/chris/git/freqtrade/freqtrade/strategy/interface.py", line 158, in load_freqAI_model
    self.freqai = FreqaiModelResolver.load_freqaimodel(self.config)
  File "/home/chris/git/freqtrade/freqtrade/resolvers/freqaimodel_resolver.py", line 41, in load_freqaimodel
    raise OperationalException(
freqtrade.exceptions.OperationalException: No freqaimodel set. Please use `--freqaimodel` to specify the FreqaiModel class to use.
  ```

**Comment by xmatthias** [comment]
freqaimodel is not passed to the backend (which would also not accept this) for historic plotting functions.

We'll fix this eventually - but for now, you should be able to set `freqaimodel` in your configuration to work around this.

**Comment by hamzz91** [comment]
Hi,
I have the same issue. When setting all the configurations that make the visualization fail (`freqaimodel`, `timerange `and `buffer_train_data_candles`), I get a data kitchen error :

```
  File "E:\PycharmProjects\freqtrade\freqtrade\rpc\rpc.py", line 1238, in _rpc_analysed_history_full
    df_analyzed = strategy.analyze_ticker(_data[pair], {'pair': pair})
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\PycharmProjects\freqtrade\freqtrade\strategy\interface.py", line 833, in analyze_ticker
    dataframe = self.advise_indicators(dataframe, metadata)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\PycharmProjects\freqtrade\freqtrade\strategy\interface.py", line 1341, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\PycharmProjects\cryptobot\user_data\strategies\test_lstm_classification.py", line 252, in populate_indicators
    dataframe = self.freqai.start(dataframe, metadata, self)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\PycharmProjects\freqtrade\freqtrade\freqai\freqai_interface.py", line 158, in start
    dk = self.start_backtesting(dataframe, metadata, self.dk, strategy)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\PycharmProjects\freqtrade\freqtrade\freqai\freqai_interface.py", line 361, in start_backtesting
    self.dd.save_metadata(dk)
  File "E:\PycharmProjects\freqtrade\freqtrade\freqai\data_drawer.py", line 424, in save_metadata
    dk.data["training_features_list"] = list(dk.data_dictionary["train_features"].columns)
                                             ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'train_features'
```

It seems the context is lost.

Thank your for your help !

**Comment by Chrisvandr** [comment]
Thanks @hamzz91. Indeed I also tried setting the configuration information directly on the strategy or in the config file, and then it does seem to pick it up, but it will unfortunately complain about other things missing afterwards, which don't belong in the configuration (or perhaps do, but not from a user perspective).

**Comment by xmatthias** [comment]
in part, this will be working now (without further workarounds) - obviously assuming the config you start the webserver whith contains a valid freqAI configuration.

**Comment by shaundy** [comment]
Hello, I met this issue. Could someone please guide me how to add to configuration ?

**Comment by amourlion** [comment]
Got same issue too, I already start webserver by a valid freqAI configuration `freqtrade webserver --config user_data/strategies/FreqAI/config.json` but still the same problem
