### ISSUE TITLE
Bot not responding Telegram messages after running for several hours.

### ISSUE THREAD

**Issue by Guscccc** [freqtrade/freqtrade#8730]
## Describe your environment

  * Operating system: Ubuntu 22.04 lTS (Windows 11 WSL2)
  * Python Version:  Pyhton 3.10.6 (`python -V`)
  * CCXT version: ccxt==3.1.5 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2023.5 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

The bot starts dry-run, and works fine, responds to telegram messages as expected. But after several hours of running, the bot isn't responding to Telegram messages anymore, though in the terminal it still generates heartbeat messages normally, not generating errors.

### Steps to reproduce:

  1. start the bot.
  2. wait several hours.
  3. send Telegram messages to the bot and not getting any response.
  
### Observed Results:

  * What happened? After running for several hours the bot doesn't respond to Telegram messages
  * What did you expect to happen? the bot responds to Telegram messages no matter how long its been running.

### Relevant code exceptions or logs

The bot isn't generating any errors, it just won't respond to Telegram messages. I don't know how to get more related information as to why. Please tell me how I could collect more related information.

### Possiblely related

The bot is running with proxy set up. But the bot does gets Telegram messages when started, and when it doesnt respond to Telegram messages, it still can connect to the exchange through proxy. so the proxy seems working.
  ```
2023-06-04 17:39:57 freqtrade.worker: INFO - Bot heartbeat. PID=51339, version='2023.5', state='RUNNING'
2023-06-04 17:40:57 freqtrade.worker: INFO - Bot heartbeat. PID=51339, version='2023.5', state='RUNNING'
2023-06-04 17:41:57 freqtrade.worker: INFO - Bot heartbeat. PID=51339, version='2023.5', state='RUNNING'
2023-06-04 17:43:01 freqtrade.worker: INFO - Bot heartbeat. PID=51339, version='2023.5', state='RUNNING'
2023-06-04 17:44:01 freqtrade.worker: INFO - Bot heartbeat. PID=51339, version='2023.5', state='RUNNING'
2023-06-04 17:45:54 freqtrade.wallets: INFO - Wallets synced.
2023-06-04 17:45:54 freqtrade.worker: INFO - Bot heartbeat. PID=51339, version='2023.5', state='RUNNING'
2023-06-04 17:46:54 freqtrade.worker: INFO - Bot heartbeat. PID=51339, version='2023.5', state='RUNNING'
2023-06-04 17:47:54 freqtrade.worker: INFO - Bot heartbeat. PID=51339, version='2023.5', state='RUNNING'
2023-06-04 17:48:56 freqtrade.worker: INFO - Bot heartbeat. PID=51339, version='2023.5', state='RUNNING'
  ```

**Comment by xmatthias** [comment]
best look through your whole log (from startup til this point).
Telegram should have some output related to this - and will most likely either have stopped querying, or will have caused an error, which will have stopped polling the telegram service.

Telegram is running in a separate thread - so while the exchange communication may still work, i'd suspect that the communication to the telegram service was interrupted.

I'm running several bots for weeks at a time (without a proxy), and it's working just fine, therefore i know that the freqtrade part of the logic works, but based on the assumption that the connection is stable.

**Comment by Guscccc** [comment]
thank you for your insight! i looked back at logs and found this related error message:
```
2023-06-04 07:10:57,407 - freqtrade.worker - INFO - Bot heartbeat. PID=37379, version='2023.5', state='RUNNING'
2023-06-04 07:11:05,748 - telegram.ext.Updater - ERROR - Error while getting Updates: Unknown error in HTTP implementation: SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:997)')
2023-06-04 07:11:05,749 - telegram.ext.Updater - ERROR - Exception happened while polling for updates.
Traceback (most recent call last):
  File "/home/gus/freqtrade/.env/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 277, in _request_wrapper
    code, payload = await self.do_request(
  File "/home/gus/freqtrade/.env/lib/python3.10/site-packages/telegram/request/_httpxrequest.py", line 216, in do_request
    res = await self._client.request(
  File "/home/gus/freqtrade/.env/lib/python3.10/site-packages/httpx/_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/home/gus/freqtrade/.env/lib/python3.10/site-packages/httpx/_client.py", line 1617, in send
    response = await self._send_handling_auth(
  File "/home/gus/freqtrade/.env/lib/python3.10/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/home/gus/freqtrade/.env/lib/python3.10/site-packages/httpx/_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/home/gus/freqtrade/.env/lib/python3.10/site-packages/httpx/_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/home/gus/freqtrade/.env/lib/python3.10/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/home/gus/freqtrade/.env/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 261, in handle_async_request
    raise exc
  File "/home/gus/freqtrade/.env/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 245, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/home/gus/freqtrade/.env/lib/python3.10/site-packages/httpcore/_async/http_proxy.py", line 299, in handle_async_request
    stream = await stream.start_tls(**kwargs)
  File "/home/gus/freqtrade/.env/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 78, in start_tls
    raise exc
  File "/home/gus/freqtrade/.env/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 69, in start_tls
    ssl_stream = await anyio.streams.tls.TLSStream.wrap(
  File "/home/gus/freqtrade/.env/lib/python3.10/site-packages/anyio/streams/tls.py", line 123, in wrap
    await wrapper._call_sslobject_method(ssl_object.do_handshake)
  File "/home/gus/freqtrade/.env/lib/python3.10/site-packages/anyio/streams/tls.py", line 131, in _call_sslobject_method
    result = func(*args)
  File "/usr/lib/python3.10/ssl.py", line 975, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:997)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gus/freqtrade/.env/lib/python3.10/site-packages/telegram/ext/_updater.py", line 607, in _network_loop_retry
    if not await action_cb():
  File "/home/gus/freqtrade/.env/lib/python3.10/site-packages/telegram/ext/_updater.py", line 335, in polling_action_cb
    raise exc
  File "/home/gus/freqtrade/.env/lib/python3.10/site-packages/telegram/ext/_updater.py", line 320, in polling_action_cb
    updates = await self.bot.get_updates(
  File "/home/gus/freqtrade/.env/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 543, in get_updates
    updates = await super().get_updates(
  File "/home/gus/freqtrade/.env/lib/python3.10/site-packages/telegram/_bot.py", line 381, in decorator
    result = await func(self, *args, **kwargs)  # skipcq: PYL-E1102
  File "/home/gus/freqtrade/.env/lib/python3.10/site-packages/telegram/_bot.py", line 3661, in get_updates
    await self._post(
  File "/home/gus/freqtrade/.env/lib/python3.10/site-packages/telegram/_bot.py", line 469, in _post
    return await self._do_post(
  File "/home/gus/freqtrade/.env/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 325, in _do_post
    return await super()._do_post(
  File "/home/gus/freqtrade/.env/lib/python3.10/site-packages/telegram/_bot.py", line 497, in _do_post
    return await request.post(
  File "/home/gus/freqtrade/.env/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 168, in post
    result = await self._request_wrapper(
  File "/home/gus/freqtrade/.env/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 293, in _request_wrapper
    raise NetworkError(f"Unknown error in HTTP implementation: {repr(exc)}") from exc
telegram.error.NetworkError: Unknown error in HTTP implementation: SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:997)')
2023-06-04 07:11:57,435 - freqtrade.worker - INFO - Bot heartbeat. PID=37379, version='2023.5', state='RUNNING'
2023-06-04 07:12:57,464 - freqtrade.worker - INFO - Bot heartbeat. PID=37379, version='2023.5', state='RUNNING'
```

So looks like the connection gets unexpectedly closed? i asssume that has something to do with the unstability of the proxy i use; the exchange connection encounter errors once in a while, too. But the exchange connection gets to reconnect and the bot recovers from error automatically, I wonder why the telelgram thread won't.

**Comment by xmatthias** [comment]
well a base assumption for correct behavior of freqtrade is a stable network connection.

If you have exchange errors as well, then that's clearly not the case.
Running a bot in such a condition is neither recommended nor safe, and can lead to loss of money (in case of a live bot).
While it might not have been a problem just yet - it could be. 

While it may recover after a bit - it's still not a scenario we'll be able to support.

Best use a more stable proxy, or try running a VPS (most providers allow you to pick your location) without a proxy.

**Comment by Guscccc** [comment]
thank you for your advice! closing this for now.
