### ISSUE TITLE
Forcesell on Bybit not working

### ISSUE THREAD

**Issue by SeriousSeal** [freqtrade/freqtrade#8731]
## Describe your environment

  * Operating system: Ubuntu 22.04
  * Python Version: 3.8.16 
  * CCXT version: 3.1.13
  * Freqtrade Version: freqtrade 2023.6.dev-12e31208e (
  

## Describe the problem:

Forceselling on latest dev throws exception on bybit. 

### Steps to reproduce:

  Forcesell 1 or more entries.
  

### Relevant code exceptions or logs

  ```
2023-06-04 09:10:19,682 - freqtrade.rpc.telegram - ERROR - Exception occurred within Telegram module
Traceback (most recent call last):
  File "/home/ubuntu/freq/freqtrade/rpc/telegram.py", line 85, in wrapper
    return await command_handler(self, *args, **kwargs)
  File "/home/ubuntu/freq/freqtrade/rpc/telegram.py", line 1092, in _force_exit
    await self._force_exit_action(trade_id)
  File "/home/ubuntu/freq/freqtrade/rpc/telegram.py", line 1117, in _force_exit_action
    self._rpc._rpc_force_exit(trade_id)
  File "/home/ubuntu/freq/freqtrade/rpc/rpc.py", line 813, in _rpc_force_exit
    self.__exec_force_exit(trade, ordertype)
  File "/home/ubuntu/freq/freqtrade/rpc/rpc.py", line 792, in __exec_force_exit
    self._freqtrade.execute_trade_exit(
  File "/home/ubuntu/freq/freqtrade/freqtradebot.py", line 1624, in execute_trade_exit
    trade.funding_fees = self.exchange.get_funding_fees(
  File "/home/ubuntu/freq/freqtrade/exchange/bybit.py", line 218, in get_funding_fees
    return self._fetch_and_calculate_funding_fees(
  File "/home/ubuntu/freq/freqtrade/exchange/exchange.py", line 2713, in _fetch_and_calculate_funding_fees
    candle_histories = self.refresh_latest_ohlcv(
  File "/home/ubuntu/freq/freqtrade/exchange/exchange.py", line 2091, in refresh_latest_ohlcv
    results = self.loop.run_until_complete(gather_stuff())
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 592, in run_until_complete
    self._check_running()
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 554, in _check_running
    raise RuntimeError(
RuntimeError: Cannot run the event loop while another loop is running
  ```

**Comment by xmatthias** [comment]
I can somewhat recreate this locally - but i'm not sure i'll have a fix for this at the moment.

It's however limited to telegram force-exiting.

If you need to forceexit in this configuration, best use the UI for now - which doesn't show this behavior and works fine.

**Comment by xmatthias** [comment]
Mmh, fix was quicker than i thought - should be fixed in develop now.
