### ISSUE TITLE
can't start in OKX simulate mode

### ISSUE THREAD

**Issue by pokersu** [freqtrade/freqtrade#8821]
## Describe your environment

  * Operating system: docker image
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2023.5.1
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

I found code in `ExchangeResolver.load_exchange`, there has a parameter named 'validate', but cannot modify this parameter in any configurable way. 

### Steps to reproduce:

  1. use exchange 'okx'
  2. use simulate mode
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs

```json
       "ccxt_config": {
            "enableRateLimit": true,
            "headers": {
                "x-simulated-trading": "1"
            }
        },
        "ccxt_async_config": {
            "enableRateLimit": true,
            "rateLimit": 3100,
            "headers": {
                "x-simulated-trading": "1"
            },
        },
```

```
2023-06-25 00:39:17,838 - freqtrade.exchange.exchange - ERROR - Unable to initialize markets.
freqtrade  | Traceback (most recent call last):
freqtrade  |   File "/freqtrade/freqtrade/exchange/exchange.py", line 492, in _load_markets
freqtrade  |     self._markets = self._api.load_markets(params={})
freqtrade  |   File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 1390, in load_markets
freqtrade  |     currencies = self.fetch_currencies()
freqtrade  |   File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/okx.py", line 1218, in fetch_currencies
freqtrade  |     response = self.privateGetAssetCurrencies(params)
freqtrade  |   File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/types.py", line 25, in unbound_method
freqtrade  |     return _self.request(self.path, self.api, self.method, params, config=self.config)
freqtrade  |   File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2865, in request
freqtrade  |     return self.fetch2(path, api, method, params, headers, body, config)
freqtrade  |   File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2862, in fetch2
freqtrade  |     return self.fetch(request['url'], request['method'], request['headers'], request['body'])
freqtrade  |   File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 601, in fetch
freqtrade  |     self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
freqtrade  |   File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/okx.py", line 5762, in handle_errors
freqtrade  |     raise ExchangeError(feedback)  # unknown message
freqtrade  | ccxt.base.errors.ExchangeError: okx {"code":"50038","data":[],"msg":"This feature is unavailable in demo trading"}
freqtrade  | 2023-06-25 00:39:17,853 - freqtrade.commands.trade_commands - ERROR - Could not load markets, therefore cannot start. Please investigate the above error for more details.
freqtrade  | 2023-06-25 00:39:17,858 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
freqtrade  | Traceback (most recent call last):
freqtrade  |   File "/freqtrade/freqtrade/commands/trade_commands.py", line 24, in start_trading
freqtrade  |     worker = Worker(args)
freqtrade  |   File "/freqtrade/freqtrade/worker.py", line 37, in __init__
freqtrade  |     self._init(False)
freqtrade  |   File "/freqtrade/freqtrade/worker.py", line 53, in _init
freqtrade  |     self.freqtrade = FreqtradeBot(self._config)
freqtrade  |   File "/freqtrade/freqtrade/freqtradebot.py", line 76, in __init__
freqtrade  |     self.exchange = ExchangeResolver.load_exchange(
freqtrade  |   File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 36, in load_exchange
freqtrade  |     exchange = ExchangeResolver._load_exchange(
freqtrade  |   File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 63, in _load_exchange
freqtrade  |     exchange = ex_class(**kwargs)
freqtrade  |   File "/freqtrade/freqtrade/exchange/exchange.py", line 187, in __init__
freqtrade  |     self.validate_config(config)
freqtrade  |   File "/freqtrade/freqtrade/exchange/exchange.py", line 225, in validate_config
freqtrade  |     self.validate_stakecurrency(config['stake_currency'])
freqtrade  |   File "/freqtrade/freqtrade/exchange/exchange.py", line 526, in validate_stakecurrency
freqtrade  |     raise OperationalException(
freqtrade  | freqtrade.exceptions.OperationalException: Could not load markets, therefore cannot start. Please investigate the above error for more details.
freqtrade exited with code 0
```

**Comment by xmatthias** [comment]
Changing validate wont help, really.

Never seen or used sinulation mode on okx either, but generally, exchange sandboxes have (in my experience) little to no volume, and cant really simulate much.
