### ISSUE TITLE
Freqai Train CatBoostError

### ISSUE THREAD

**Issue by woehrer12** [freqtrade/freqtrade#8834]
## Describe your environment

  * Operating system: docker freqtradeorg/freqtrade:stable_freqaitorch
  * Freqtrade Version: 2023.5.1
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:
```

2023-06-26 08:11:30,175 - freqtrade.freqai.base_models.BaseClassifierModel - INFO - -------------------- Starting training ETH/USDT --------------------
2023-06-26 08:11:30,288 - freqtrade.freqai.data_kitchen - INFO - ETH/USDT: dropped 0 training points due to NaNs in populated dataset 336.
2023-06-26 08:11:30,288 - freqtrade.freqai.base_models.BaseClassifierModel - INFO - -------------------- Training on data from 2023-01-01 to 2023-01-14 --------------------
2023-06-26 08:11:30,462 - freqtrade.freqai.base_models.BaseClassifierModel - INFO - Training model on 830 features
2023-06-26 08:11:30,462 - freqtrade.freqai.base_models.BaseClassifierModel - INFO - Training model on 225 data points
2023-06-26 08:11:30,580 - freqtrade.freqai.freqai_interface - WARNING - Training ETH/USDT raised exception CatBoostError. Message: /src/catboost/catboost/private/libs/target/target_converter.cpp:375: Target contains only one unique value, skipping.
Traceback (most recent call last):
  File "/freqtrade/freqtrade/freqai/freqai_interface.py", line 350, in start_backtesting
    self.model = self.train(dataframe_train, pair, dk)
  File "/freqtrade/freqtrade/freqai/base_models/BaseClassifierModel.py", line 67, in train
    model = self.fit(data_dictionary, dk)
  File "/freqtrade/freqtrade/freqai/prediction_models/CatboostClassifier.py", line 56, in fit
    cbr.fit(X=train_data, eval_set=test_data, init_model=init_model,
  File "/home/ftuser/.local/lib/python3.10/site-packages/catboost/core.py", line 5131, in fit
    self._fit(X, y, cat_features, text_features, embedding_features, None, sample_weight, None, None, None, None, baseline, use_best_model,
  File "/home/ftuser/.local/lib/python3.10/site-packages/catboost/core.py", line 2357, in _fit
    self._train(
  File "/home/ftuser/.local/lib/python3.10/site-packages/catboost/core.py", line 1761, in _train
    self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
  File "_catboost.pyx", line 4624, in _catboost._CatBoost._train
  File "_catboost.pyx", line 4673, in _catboost._CatBoost._train
_catboost.CatBoostError: /src/catboost/catboost/private/libs/target/target_converter.cpp:375: Target contains only one unique value

```

```
    "freqai": {
        "enabled": true,
        "purge_old_models": true,
        "train_period_days": 14,
        "backtest_period_days": 7,
        "identifier" : "uniqe-id",
        //"save_backtest_models": true,
        //"continual_learning": true,
        "live_retrain_hours": 30,
        "feature_parameters" : {
            "include_timeframes": ["1h" ,"4h", "1d", "1w"],
            "include_corr_pairlist": ["BTC/USDT", "ETH/USDT", "XRP/USDT"//, "MATIC/USDT", "SOL/USDT", "ARB/USDT", "LTC/USDT", "PAXG/USDT", "DOGE/USDT", "LINA/USDT", "ADA/USDT"//, "OCEAN/USDT", "SUI/USDT", "MTL/USDT", "FTM/USDT", "OP/USDT", "PEPE/USDT" 
        ],
            "label_period_candles": 20,
            "include_shifted_candles": 2,
            // "DI_threshold": 0.9,
            // "weight_factor": 0.9,
            // "principal_component_analysis": false,
            // "use_SVM_to_remove_outliers": true,
            "indicator_periods_candles": [10, 20]
        },
        "data_split_parameters" : {
            "test_size": 0.33,
            //"test_size": 0,
            "random_state": 42
        },
        "model_training_parameters": {
            "n_estimators": 1000
        }
    },
```

### Steps to reproduce:

  1. docker-compose run --rm freqtradeai hyperopt --strategy FreqaiExampleHybridStrategy --hyperopt-loss ShortTradeDurHyperOptLoss -e 10000 --freqaimodel CatboostClassifier --timerange 20230101-20230616
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

**Comment by robcaulk** [comment]
Can you please narrow it down to one change relative to the example config? 

e.g. "when I change this *single* line in the example config, it doesnt work."

Right now you have quite a few changes, one of them being adding about as many corr_pairs as possible. I am not sure which of the changes are causing your problem - and I feel it is your responsibility to tell us that. 

Looking forward to you providing supporting information. 

Cheers,

Robert

**Comment by woehrer12** [comment]
I see the problem is in the "train_period_days" of 14, it is only 1 value for the 1w tf.
Then they run in this problem.
Maybe you can create a Exception for what is to do in this case.

**Comment by robcaulk** [comment]
Yes, each of  your  `backtest_period` has a single data point since you are using 1W informatives and splitting a short 14 day train period. This is fixed by increasing your backtest_period_days and train_period_days. Please keep in mind that your training data will also be split according to your `data_split_parameters`. So if you use 1W candles and you have 2 weeks of training data, it cant split it into 0.33 test 0.66 train like you have asked it.
