### ISSUE TITLE
SVM removed all Data from trainset

### ISSUE THREAD

**Issue by woehrer12** [freqtrade/freqtrade#8837]
```
2023-06-26 22:09:21,068 - freqtrade.freqai.base_models.BaseClassifierModel - INFO - -------------------- Starting training MATIC/USDT --------------------
2023-06-26 22:09:21,453 - freqtrade.freqai.data_kitchen - INFO - MATIC/USDT: dropped 0 training points due to NaNs in populated dataset 672.
2023-06-26 22:09:21,454 - freqtrade.freqai.base_models.BaseClassifierModel - INFO - -------------------- Training on data from 2022-09-03 to 2022-09-30 --------------------
2023-06-26 22:09:22,566 - freqtrade.freqai.data_kitchen - INFO - SVM tossed 1 train points from 450 total points.
2023-06-26 22:09:22,750 - freqtrade.freqai.data_kitchen - INFO - MATIC/USDT: SVM tossed 222 test points from 222 total points.
2023-06-26 22:09:22,750 - freqtrade.freqai.base_models.BaseClassifierModel - INFO - Training model on 4146 features
2023-06-26 22:09:22,750 - freqtrade.freqai.base_models.BaseClassifierModel - INFO - Training model on 449 data points
2023-06-26 22:09:22,977 - freqtrade.freqai.freqai_interface - WARNING - Training MATIC/USDT raised exception CatBoostError. Message: Labels variable is empty., skipping.
Traceback (most recent call last):
  File "/freqtrade/freqtrade/freqai/freqai_interface.py", line 350, in start_backtesting
    self.model = self.train(dataframe_train, pair, dk)
  File "/freqtrade/freqtrade/freqai/base_models/BaseClassifierModel.py", line 67, in train
    model = self.fit(data_dictionary, dk)
  File "/freqtrade/freqtrade/freqai/prediction_models/CatboostClassifier.py", line 41, in fit
    test_data = Pool(
  File "/home/ftuser/.local/lib/python3.10/site-packages/catboost/core.py", line 792, in __init__
    self._init(data, label, cat_features, text_features, embedding_features, embedding_features_data, pairs, weight,
  File "/home/ftuser/.local/lib/python3.10/site-packages/catboost/core.py", line 1363, in _init
    self._check_label_empty(label)
  File "/home/ftuser/.local/lib/python3.10/site-packages/catboost/core.py", line 901, in _check_label_empty
    raise CatBoostError("Labels variable is empty.")
_catboost.CatBoostError: Labels variable is empty.

```

`docker-compose run --rm freqtradeai hyperopt --strategy FreqaiExampleHybridStrategy --hyperopt-loss ShortTradeDurHyperOptLoss -e 10000 --freqaimodel CatboostClassifier --timerange 20220101-20230626`

```
    "freqai": {
        "enabled": true,
        "purge_old_models": true,
        "train_period_days": 28,
        "backtest_period_days": 7,
        "identifier" : "uniqe-id",
        "live_retrain_hours": 30,
        "feature_parameters" : {
            "include_timeframes": ["1h", "4h", "12h", "1d", "3d", "1w"],
            "include_corr_pairlist": [  "BTC/USDT",
                                        "ETH/USDT",
                                        "XRP/USDT",
                                        "SOL/USDT", 
                                        "LTC/USDT",
                                        "PAXG/USDT",
                                        "DOGE/USDT",
                                        "ADA/USDT",
                                        "TRX/USDT"
        ],
            "label_period_candles": 20,
            "include_shifted_candles": 2,
            "use_SVM_to_remove_outliers": true,
            "indicator_periods_candles": [10, 20]
        },
        "data_split_parameters" : {
            "test_size": 0.33,
            "random_state": 42
        },
        "model_training_parameters": {
            "n_estimators": 1000,
            "early_stopping_rounds": 200
        }
    },
```

**Comment by robcaulk** [comment]
Hey, 

So you have full control over the sensitivity of your SVM with the `svm_params` dict of your config. We have even provided tips about this in our doc [here](https://www.freqtrade.io/en/latest/freqai-feature-engineering/#identifying-outliers-using-a-support-vector-machine-svm). Inside this dict you can use any of the parameters available in the OneClassSVM of SKLearn [here](https://scikit-learn.org/stable/modules/generated/sklearn.svm.OneClassSVM.html). 

Since your config choices are relatively extreme, (using 6 tfs from 1h to 1w, in addition to 9 corr pairs and 2 shifted candles), you are implicitly accepting that you are now responsible for non-default behaviors of your data pipeline. That includes how your `svm_params` need to be set to accommodate your extreme config choices. I dont think there is anything we can do to help with this kind of thing. @xmatthias do you have a different point of view on this topic?

Cheers,

Rob

**Comment by xmatthias** [comment]
As far as i can tell from the logs, we log a warning stating that labels are empty.

Also in non-extreme situations this could happen (odd pair selection, for example).
Skipping that segment (backtest segment for that pair for example) seems the right thing to do.

**Comment by robcaulk** [comment]
I assume we like how the current behavior works - so I will close. Feel free to reopen if you believe we need to make some changes.
