### ISSUE TITLE
Job for freqtrade.service failed because the service did not take the steps required by its unit configuration. See "systemctl status freqtrade.service" and "journalctl -xeu freqtrade.service" for details.

### ISSUE THREAD

**Issue by szvorion** [freqtrade/freqtrade#8839]
Hello. Trying to make freqtrade run automatically I got an error. What could go wrong?

```
hecker@hecker:~$ sudo systemctl start freqtrade.service
Job for freqtrade.service failed because the service did not take the steps required by its unit configuration.
See "systemctl status freqtrade.service" and "journalctl -xeu freqtrade.service" for details.
hecker@hecker:~$ systemctl status freqtrade.service
● freqtrade.service - Freqtrade bot
     Loaded: loaded (/etc/systemd/system/freqtrade.service; disabled; preset: enabled)
     Active: activating (auto-restart) (Result: protocol) since Tue 2023-06-27 20:54:37 CEST; 7s ago
    Process: 109148 ExecStart=/home/hecker/freqtrade/.env/bin/freqtrade trade --config /home/hecker/freqtrade/config.json (code=exited, status=0/SUCCESS)
   Main PID: 109148 (code=exited, status=0/SUCCESS)
        CPU: 3.486s
hecker@hecker:~$ journalctl -xeu freqtrade.service
jún 27 20:54:50 hecker freqtrade[109165]: Traceback (most recent call last):
jún 27 20:54:50 hecker freqtrade[109165]:   File "/home/hecker/freqtrade/freqtrade/commands/trade_commands.py", line 24, in start_trading
jún 27 20:54:50 hecker freqtrade[109165]:     worker = Worker(args)
jún 27 20:54:50 hecker freqtrade[109165]:              ^^^^^^^^^^^^
jún 27 20:54:50 hecker freqtrade[109165]:   File "/home/hecker/freqtrade/freqtrade/worker.py", line 37, in __init__
jún 27 20:54:50 hecker freqtrade[109165]:     self._init(False)
jún 27 20:54:50 hecker freqtrade[109165]:   File "/home/hecker/freqtrade/freqtrade/worker.py", line 50, in _init
jún 27 20:54:50 hecker freqtrade[109165]:     self._config = Configuration(self._args, None).get_config()
jún 27 20:54:50 hecker freqtrade[109165]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jún 27 20:54:50 hecker freqtrade[109165]:   File "/home/hecker/freqtrade/freqtrade/configuration/configuration.py", line 42, in get_config
jún 27 20:54:50 hecker freqtrade[109165]:     self.config = self.load_config()
jún 27 20:54:50 hecker freqtrade[109165]:                   ^^^^^^^^^^^^^^^^^^
jún 27 20:54:50 hecker freqtrade[109165]:   File "/home/hecker/freqtrade/freqtrade/configuration/configuration.py", line 68, in load_config
jún 27 20:54:50 hecker freqtrade[109165]:     config: Config = load_from_files(self.args.get("config", []))
jún 27 20:54:50 hecker freqtrade[109165]:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jún 27 20:54:50 hecker freqtrade[109165]:   File "/home/hecker/freqtrade/freqtrade/configuration/load_config.py", line 102, in load_from_files
jún 27 20:54:50 hecker freqtrade[109165]:     config_tmp = load_config_file(str(file))
jún 27 20:54:50 hecker freqtrade[109165]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
jún 27 20:54:50 hecker freqtrade[109165]:   File "/home/hecker/freqtrade/freqtrade/configuration/load_config.py", line 69, in load_config_file
jún 27 20:54:50 hecker freqtrade[109165]:     raise OperationalException(
jún 27 20:54:50 hecker freqtrade[109165]: freqtrade.exceptions.OperationalException: Parse error at offset 2228: The document root must not be followed by other values.
jún 27 20:54:50 hecker freqtrade[109165]: Please verify the following segment of your configuration:
jún 27 20:54:50 hecker freqtrade[109165]:             "sd_notify": true
jún 27 20:54:50 hecker freqtrade[109165]:     }
jún 27 20:54:50 hecker freqtrade[109165]:     }
jún 27 20:54:50 hecker freqtrade[109165]: }
jún 27 20:54:50 hecker systemd[1]: freqtrade.service: Failed with result 'protocol'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ The unit freqtrade.service has entered the 'failed' state with result 'protocol'.
jún 27 20:54:50 hecker systemd[1]: Failed to start freqtrade.service - Freqtrade bot.
░░ Subject: A start job for unit freqtrade.service has failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ A start job for unit freqtrade.service has finished with a failure.
░░ 
░░ The job identifier is 164198 and the job result is failed.
jún 27 20:54:50 hecker systemd[1]: freqtrade.service: Consumed 3.517s CPU time.
░░ Subject: Resources consumed by unit runtime
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ The unit freqtrade.service completed and consumed the indicated resources.
```

**Comment by xmatthias** [comment]
The error is pretty clear if you take the time to read through it.
Its a syntax error in your configuration, so the file is no longer valid json.

The error points out the rough line the error occurs, too.

If you use a good editor (e.g. vscode), it should highlight the (syntax) errors in your config file.
