### ISSUE TITLE
Downloading Kraken Data

### ISSUE THREAD

**Issue by chrisdonreynolds** [freqtrade/freqtrade#8860]
Operating system: Windows 
Exchange: Kraken

I'm trying to download historical data, and when I run the download data command, I get an error: List index out of range.

```
C:\Users\chris\ft_userdata>docker compose run freqtrade download-data --exchange kraken --dl-trades
2023-07-03 21:59:59,621 - freqtrade - INFO - freqtrade 2023.5.1
2023-07-03 21:59:59,621 - freqtrade.configuration.load_config - INFO - Using config: user_data/config.json ...
2023-07-03 21:59:59,623 - freqtrade.loggers - INFO - Verbosity set to 0
2023-07-03 21:59:59,624 - freqtrade.configuration.configuration - INFO - Using exchange kraken
2023-07-03 21:59:59,722 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2023-07-03 21:59:59,724 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/kraken ...
2023-07-03 21:59:59,725 - freqtrade.configuration.configuration - INFO - timeframes --timeframes: ['1m', '5m']
2023-07-03 21:59:59,725 - freqtrade.configuration.configuration - INFO - Detected --dl-trades: True
2023-07-03 21:59:59,725 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2023-07-03 21:59:59,727 - freqtrade.exchange.check_exchange - INFO - Exchange "kraken" is officially supported by the Freqtrade development team.
2023-07-03 21:59:59,727 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2023-07-03 21:59:59,727 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2023-07-03 21:59:59,730 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2023-07-03 21:59:59,730 - freqtrade.exchange.exchange - INFO - Using CCXT 3.1.5
2023-07-03 21:59:59,730 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2023-07-03 21:59:59,732 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 3100}
2023-07-03 21:59:59,733 - freqtrade.exchange.exchange - INFO - Using Exchange "Kraken"
2023-07-03 21:59:59,733 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Kraken'...
2023-07-03 21:59:59,733 - freqtrade.exchange.exchange - INFO - Markets were not loaded. Loading them now..
2023-07-03 22:00:04,356 - freqtrade.commands.data_commands - INFO - About to download pairs: ['ETH/USD', 'LTC/USD', 'SOL/USD', 'BCH/USD', 'EOS/USD', 'DOGE/USD', 'ADA/USD', 'MATIC/USD', 'LINK/USD', 'DOT/USD', 'XMR/USD', 'GALA/USD', 'GBP/USD', 'FIL/USD', 'COMP/USD'], intervals: ['1m', '5m'] to /freqtrade/user_data/data/kraken
2023-07-03 22:00:04,357 - freqtrade.data.history.history_utils - INFO - Downloading trades for pair ETH/USD.
2023-07-03 22:00:04,360 - freqtrade.data.history.history_utils - INFO - Current Amount of trades: 0
2023-07-03 22:00:07,602 - freqtrade.data.history.history_utils - ERROR - Failed to download historic trades for pair: "ETH/USD".
Traceback (most recent call last):
  File "/freqtrade/freqtrade/data/history/history_utils.py", line 366, in _download_trades_history
    new_trades = exchange.get_historic_trades(pair=pair,
  File "/freqtrade/freqtrade/exchange/exchange.py", line 2347, in get_historic_trades
    return self.loop.run_until_complete(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/freqtrade/freqtrade/exchange/exchange.py", line 2322, in _async_get_trade_history
    return await self._async_get_trade_history_id(
  File "/freqtrade/freqtrade/exchange/exchange.py", line 2253, in _async_get_trade_history_id
    from_id = t[-1][1]
IndexError: list index out of range
```

It repeats this error for each pair.

**Comment by xmatthias** [comment]
It's a very subtle bug in the automatic calculation of the timerange, resulting in a start-date in the future.

you can pretty easily work around this for now by using either `--days 30` (which is the default) - or `--timerange 20230101-` (or whatever other timerange makes sense for you).
This will only affect the initial download - where 30 days (the default) is most likely wrong anyway, as you'll usually want more data.
After you got initial data, you'll no longer need the parameter - as it'll continue from the very last trade available in the files.


I should have a fix ready for this shortly, but it'll not be included in the 2023.6 release - mainly because it's so easy to work aorund (and the default is most likely wrong anyway).
