### ISSUE TITLE
Setting timerange with negative value does not work

### ISSUE THREAD

**Issue by vertti** [freqtrade/freqtrade#889]
Documentation says:

```
The full timerange specification:
- Use last 123 tickframes of data: `--timerange=-123`
- Use first 123 tickframes of data: `--timerange=123-`
- Use tickframes from line 123 through 456: `--timerange=123-456`
```
but using `--timerange=-10` in backtesting throws error:

```
Traceback (most recent call last):
  File "freqtrade/main.py", line 74, in <module>
    main(sys.argv[1:])
  File "freqtrade/main.py", line 32, in main
    args.func(args)
  File "/Users/vertti/dev/freqtrade/freqtrade/optimize/backtesting.py", line 313, in start
    backtesting.start()
  File "/Users/vertti/dev/freqtrade/freqtrade/optimize/backtesting.py", line 247, in start
    preprocessed = self.tickerdata_to_dataframe(data)
  File "/Users/vertti/dev/freqtrade/freqtrade/analyze.py", line 218, in tickerdata_to_dataframe
    for pair, pair_data in tickerdata.items()}
  File "/Users/vertti/dev/freqtrade/freqtrade/analyze.py", line 218, in <dictcomp>
    for pair, pair_data in tickerdata.items()}
  File "/Users/vertti/dev/freqtrade/freqtrade/analyze.py", line 76, in populate_indicators
    return self.strategy.populate_indicators(dataframe=dataframe)
  File "/Users/vertti/dev/freqtrade/user_data/strategies/awesome_strategy.py", line 45, in populate_indicators
    dataframe['ao'] = qtpylib.awesome_oscillator(dataframe)
  File "/Users/vertti/dev/freqtrade/freqtrade/vendor/qtpylib/indicators.py", line 156, in awesome_oscillator
    numpy_rolling_mean(midprice, slow)
  File "/Users/vertti/dev/freqtrade/freqtrade/vendor/qtpylib/indicators.py", line 52, in func_wrapper
    calculated = func(series, window)
  File "/Users/vertti/dev/freqtrade/freqtrade/vendor/qtpylib/indicators.py", line 65, in numpy_rolling_mean
    return np.mean(numpy_rolling_window(data, window), -1)
  File "/Users/vertti/dev/freqtrade/freqtrade/vendor/qtpylib/indicators.py", line 44, in numpy_rolling_window
    return np.lib.stride_tricks.as_strided(data, shape=shape, strides=strides)
  File "/Users/vertti/dev/freqtrade/.env/lib/python3.6/site-packages/numpy/lib/stride_tricks.py", line 102, in as_strided
    array = np.asarray(DummyArray(interface, base=x))
  File "/Users/vertti/dev/freqtrade/.env/lib/python3.6/site-packages/numpy/core/numeric.py", line 492, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: negative dimensions are not allowed
```

**Comment by xmatthias** [comment]
i find the location rather curious
trying to debug this issue now - the output of `parse_timerange` is correct (Null, Line, 0, -10).

i tried to add a print(dataframe) to the strategy (it's only 10 ticks long after all) and didn't find anything I wouldnt expect...


```
                       date     open     high      low    close  volume
0 2018-06-05 16:50:00+00:00  0.19900  0.19900  0.19900  0.19900   0.599
1 2018-06-05 16:55:00+00:00  0.19900  0.19913  0.19862  0.19862  33.924
2 2018-06-05 17:00:00+00:00  0.19862  0.19863  0.19812  0.19817  31.999
3 2018-06-05 17:05:00+00:00  0.19840  0.19863  0.19813  0.19862  37.827
4 2018-06-05 17:10:00+00:00  0.19862  0.19933  0.19862  0.19903  18.914
5 2018-06-05 17:15:00+00:00  0.19870  0.19870  0.19862  0.19870  31.382
6 2018-06-05 17:20:00+00:00  0.19870  0.19875  0.19870  0.19870   2.499
7 2018-06-05 17:25:00+00:00  0.19870  0.19893  0.19870  0.19893   2.125
8 2018-06-05 17:30:00+00:00  0.19890  0.19913  0.19872  0.19882   3.108
```


after debugging a bit more - it seems to be the strategy indicator 
`dataframe['ao'] = qtpylib.awesome_oscillator(dataframe)`.

after removing that line out i got further - (but it failed with `AttributeError: module 'pandas' has no attribute 'rolling_mean'` ... which is part of the file `/home/xmatt/development/python/cryptos/freqtrade/freqtrade/vendor/qtpylib/indicators.py`.

maybe a version issue between qtpylib and pandas/numpy?

**Comment by vertti** [comment]
Yeah, stupid me. Some of our indicators misbehave when there's less data than the window is that the indicator uses.
