### ISSUE TITLE
TypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'

### ISSUE THREAD

**Issue by le8888e** [freqtrade/freqtrade#8908]
## Describe your environment

  * Operating system: _windows11___
  * Python Version: _3.10.12____ (`python -V`)
  * CCXT version: _2.4.60____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: __2022.12__ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

Hi, I tried to run in dry_run mode by command "freqtrade trade --config config.json --strategy SampleStrategy", but error occurs as stated in the title. I set a breakpoint at line 290 in _model_construction.py to debug. 
raw_annotations = {'__root__': typing.Union[freqtrade.rpc.api_server.api_schemas.TradeSchema, freqtrade.rpc.api_server.api_schemas.StatusMsg]} 
namespace={'__module__': 'freqtrade.rpc.api_server.api_schemas', '__qualname__': 'ForceEnterResponse', '__annotations__': {'__root__': typing.Union[freqtrade.rpc.api_server.api_schemas.TradeSchema, freqtrade.rpc.api_server.api_schemas.StatusMsg]}, 'model_config': {}}

### Steps to reproduce:

  1. __install freqtrade by anaconda_following the official document_
  2. __freqtrade create-userdir --userdir user_data___
  3. __freqtrade new-config --config config.json___
  
### Observed Results:

  * Raise an error 'TypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__''.
  * No error raised.

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

2023-07-15 15:11:01,608 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2023-07-15 15:11:07,824 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2023-07-15 15:11:07,868 - freqtrade.wallets - INFO - Wallets synced.
2023-07-15 15:11:07,878 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from 'D:\WorkingCopys\freqtrade\freqtrade\plugins\pairlist\StaticPairList.py'...
2023-07-15 15:11:08,463 - freqtrade.rpc.rpc_manager - INFO - Enabling rpc.api_server
2023-07-15 15:11:08,518 - freqtrade.commands.trade_commands - ERROR - To define root models, use `pydantic.RootModel` rather than a field called '__root__'
2023-07-15 15:11:08,518 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "D:\WorkingCopys\freqtrade\freqtrade\commands\trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "D:\WorkingCopys\freqtrade\freqtrade\worker.py", line 37, in __init__
    self._init(False)
  File "D:\WorkingCopys\freqtrade\freqtrade\worker.py", line 53, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "D:\WorkingCopys\freqtrade\freqtrade\freqtradebot.py", line 83, in __init__
    self.rpc: RPCManager = RPCManager(self)
  File "D:\WorkingCopys\freqtrade\freqtrade\rpc\rpc_manager.py", line 48, in __init__
    apiserver = ApiServer(config)
  File "D:\WorkingCopys\freqtrade\freqtrade\rpc\api_server\webserver.py", line 77, in __init__
    self.configure_app(self.app, self._config)
  File "D:\WorkingCopys\freqtrade\freqtrade\rpc\api_server\webserver.py", line 123, in configure_app
    from freqtrade.rpc.api_server.api_auth import http_basic_or_jwt_token, router_login
  File "D:\WorkingCopys\freqtrade\freqtrade\rpc\api_server\api_auth.py", line 11, in <module>
    from freqtrade.rpc.api_server.api_schemas import AccessAndRefreshToken, AccessToken
  File "D:\WorkingCopys\freqtrade\freqtrade\rpc\api_server\api_schemas.py", line 289, in <module>
    class ForceEnterResponse(BaseModel):
  File "D:\anaconda3\envs\freqtrade\lib\site-packages\pydantic\_internal\_model_construction.py", line 97, in __new__
    private_attributes = inspect_namespace(
  File "D:\anaconda3\envs\freqtrade\lib\site-packages\pydantic\_internal\_model_construction.py", line 290, in inspect_namespace
    raise TypeError("To define root models, use `pydantic.RootModel` rather than a field called '__root__'")
TypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'

**Comment by xmatthias** [comment]
Please update to the latest version and make sure to follow the [updating docs](https://www.freqtrade.io/en/latest/updating/) corresponding to your install method to have dependencies updated as well.

Please understand that we'll not be supporting (or even look at) potential problems with versions that are over half a year old.

**Comment by le8888e** [comment]
I tried the latest version, still the same error. Is that because freqtrade has to be installed on Windows by Docker?

**Comment by xmatthias** [comment]
No.
it's almost certainly because you're using wrong dependencies (either too old, or pydantic 2.0).

> I tried the latest version, still the same error.

Then please report it with the latest version (including the latest version stacktrace).
As mentioned above, make sure to follow the updating guideline to install matching dependencies, and when you hit the error again, please provide the output of `pip show pydantic`.

**Comment by le8888e** [comment]
LOG:
2023-07-15 16:45:32,269 - freqtrade - INFO - freqtrade 2023.6
2023-07-15 16:45:32,977 - freqtrade.worker - INFO - Starting worker 2023.6
2023-07-15 16:45:32,977 - freqtrade.configuration.load_config - INFO - Using config: config.json ...
2023-07-15 16:45:32,983 - freqtrade.loggers - INFO - Verbosity set to 0
2023-07-15 16:45:32,983 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
2023-07-15 16:45:32,984 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2023-07-15 16:45:32,984 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:///tradesv3.dryrun.sqlite"
2023-07-15 16:45:32,984 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 3 ...
......
2023-07-15 16:45:33,046 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2023-07-15 16:45:36,885 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2023-07-15 16:45:36,956 - freqtrade.wallets - INFO - Wallets synced.
2023-07-15 16:45:36,992 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist VolumePairList from 'D:\WorkingCopys\freqtrade\freqtrade\plugins\pairlist\VolumePairList.py'...
2023-07-15 16:45:37,635 - freqtrade.rpc.rpc_manager - INFO - Enabling rpc.api_server
2023-07-15 16:45:37,695 - freqtrade.commands.trade_commands - ERROR - To define root models, use `pydantic.RootModel` rather than a field called '__root__'
2023-07-15 16:45:37,695 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "D:\WorkingCopys\freqtrade\freqtrade\commands\trade_commands.py", line 24, in start_trading
    worker = Worker(args)
  File "D:\WorkingCopys\freqtrade\freqtrade\worker.py", line 37, in __init__
    self._init(False)
  File "D:\WorkingCopys\freqtrade\freqtrade\worker.py", line 53, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "D:\WorkingCopys\freqtrade\freqtrade\freqtradebot.py", line 92, in __init__
    self.rpc: RPCManager = RPCManager(self)
  File "D:\WorkingCopys\freqtrade\freqtrade\rpc\rpc_manager.py", line 49, in __init__
    apiserver = ApiServer(config)
  File "D:\WorkingCopys\freqtrade\freqtrade\rpc\api_server\webserver.py", line 70, in __init__
    self.configure_app(self.app, self._config)
  File "D:\WorkingCopys\freqtrade\freqtrade\rpc\api_server\webserver.py", line 116, in configure_app
    from freqtrade.rpc.api_server.api_auth import http_basic_or_jwt_token, router_login
  File "D:\WorkingCopys\freqtrade\freqtrade\rpc\api_server\api_auth.py", line 11, in <module>
    from freqtrade.rpc.api_server.api_schemas import AccessAndRefreshToken, AccessToken
  File "D:\WorkingCopys\freqtrade\freqtrade\rpc\api_server\api_schemas.py", line 338, in <module>
    class ForceEnterResponse(BaseModel):
  File "D:\anaconda3\envs\freqtrade\lib\site-packages\pydantic\_internal\_model_construction.py", line 97, in __new__
    private_attributes = inspect_namespace(
  File "D:\anaconda3\envs\freqtrade\lib\site-packages\pydantic\_internal\_model_construction.py", line 290, in inspect_namespace
    raise TypeError("To define root models, use `pydantic.RootModel` rather than a field called '__root__'")
TypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'


pip show pydantic:
Name: pydantic
Version: 2.0.3
Summary: Data validation using Python type hints
Home-page:
Author:
Author-email: Samuel Colvin <s@muelcolvin.com>, Eric Jolibois <em.jolibois@gmail.com>, Hasan Ramezani <hasan.r67@gmail.com>, Adrian Garcia Badaracco <1755071+adriangb@users.noreply.github.com>, Terrence Dorsey <terry@pydantic.dev>, David Montague <david@pydantic.dev>
License:
Location: d:\anaconda3\envs\freqtrade\lib\site-packages
Requires: annotated-types, pydantic-core, typing-extensions
Required-by: fastapi, freqtrade

**Comment by le8888e** [comment]
Seems like I have pydantic version 2.0.3 installed, not pydantic==1.10.9 as listed in requirements.txt. I switched it to 1.10.9 and that works for me. It seems weired because I was following the installation instruction. Thanks!

**Comment by xmatthias** [comment]
The install instructions are pretty clear about running `pip install -r requirements.txt` in all instances (i verified this a few weeks ago) before running the effective install.

As suspected - it's a dependency problem - pydantic 2.0 will require some changes, which we'll be adding when time allows.

**Comment by Mo7mud** [comment]
I had the issue with latest version and I confirm running `pip install -r requirements.txt` solved it.
