### ISSUE TITLE
Fail to install : ModuleNotFoundError: freqtrade

### ISSUE THREAD

**Issue by Mo7mud** [freqtrade/freqtrade#8958]
## Describe your environment

  * Operating system: Windows 10
  * Python Version: 3.10
  * CCXT version:  3.1.44
  * Freqtrade Version: 2023.6
  

  ```
  (.env) PS D:\freqtrade> pip install -e .
Obtaining file:///D:/freqtrade
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error

  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [39 lines of output]
      Traceback (most recent call last):
        File "D:\freqtrade\.env\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\freqtrade\.env\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "D:\freqtrade\.env\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
        File "C:\Users\Mohammad\AppData\Local\Temp\pip-build-env-31opxt1h\overlay\Lib\site-packages\setuptools\build_meta.py", line 450, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "C:\Users\Mohammad\AppData\Local\Temp\pip-build-env-31opxt1h\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\Mohammad\AppData\Local\Temp\pip-build-env-31opxt1h\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\Mohammad\AppData\Local\Temp\pip-build-env-31opxt1h\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 64, in <module>
        File "C:\Users\Mohammad\AppData\Local\Temp\pip-build-env-31opxt1h\overlay\Lib\site-packages\setuptools\__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\Mohammad\AppData\Local\Temp\pip-build-env-31opxt1h\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 159, in setup
          dist.parse_config_files()
        File "C:\Users\Mohammad\AppData\Local\Temp\pip-build-env-31opxt1h\overlay\Lib\site-packages\setuptools\dist.py", line 894, in parse_config_files
          setupcfg.parse_configuration(
        File "C:\Users\Mohammad\AppData\Local\Temp\pip-build-env-31opxt1h\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 189, in parse_configuration
          meta.parse()
        File "C:\Users\Mohammad\AppData\Local\Temp\pip-build-env-31opxt1h\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 500, in parse
          section_parser_method(section_options)
        File "C:\Users\Mohammad\AppData\Local\Temp\pip-build-env-31opxt1h\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 475, in parse_section
          self[name] = value
        File "C:\Users\Mohammad\AppData\Local\Temp\pip-build-env-31opxt1h\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 293, in __setitem__
          parsed = self.parsers.get(option_name, lambda x: x)(value)
        File "C:\Users\Mohammad\AppData\Local\Temp\pip-build-env-31opxt1h\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 606, in _parse_version
          return expand.version(self._parse_attr(value, self.package_dir, self.root_dir))
        File "C:\Users\Mohammad\AppData\Local\Temp\pip-build-env-31opxt1h\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 417, in _parse_attr
          return expand.read_attr(attr_desc, package_dir, root_dir)
        File "C:\Users\Mohammad\AppData\Local\Temp\pip-build-env-31opxt1h\overlay\Lib\site-packages\setuptools\config\expand.py", line 188, in read_attr
          spec = _find_spec(module_name, path)
        File "C:\Users\Mohammad\AppData\Local\Temp\pip-build-env-31opxt1h\overlay\Lib\site-packages\setuptools\config\expand.py", line 203, in _find_spec
          raise ModuleNotFoundError(module_name)
      ModuleNotFoundError: freqtrade
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ```

**Comment by xmatthias** [comment]
Please follow the [installation instructions](https://www.freqtrade.io/en/stable/windows_installation/).

none of these mentions the use of a simple `pip install -e .` - all are prefixed with other actions (which you don't mention, and i'll therefore assume you didn't take).
obviously if ANY of the other actions fail, then you'll need to investigate why THAT is happening.

The error as is doesn't say anything other than "didn't follow the documentation" - and includes no detail about anything else.

**Comment by Mo7mud** [comment]
Here's all steps with full log, no steps failed and all was done before the ` pip install -e .` command


```
PS D:\freqtrade> .env\Scripts\activate
(.env) PS D:\freqtrade> pip install  build_helpers\TA_Lib-0.4.26-cp310-cp310-win_amd64.whl -U
Processing d:\freqtrade\build_helpers\ta_lib-0.4.26-cp310-cp310-win_amd64.whl
Requirement already satisfied: numpy in d:\freqtrade\.env\lib\site-packages (from TA-Lib==0.4.26) (1.24.3)
TA-Lib is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.
(.env) PS D:\freqtrade> pip install -r requirements.txt
Ignoring cryptography: markers 'platform_machine == "armv7l"' don't match your environment
Requirement already satisfied: numpy==1.24.3 in d:\freqtrade\.env\lib\site-packages (from -r requirements.txt (line 1)) (1.24.3)
Requirement already satisfied: pandas==2.0.2 in d:\freqtrade\.env\lib\site-packages (from -r requirements.txt (line 2)) (2.0.2)
Requirement already satisfied: pandas-ta==0.3.14b in d:\freqtrade\.env\lib\site-packages (from -r requirements.txt (line 3)) (0.3.14b0)
Requirement already satisfied: ccxt==3.1.44 in d:\freqtrade\.env\lib\site-packages (from -r requirements.txt (line 5)) (3.1.44)
Requirement already satisfied: cryptography==41.0.1 in d:\freqtrade\.env\lib\site-packages (from -r requirements.txt (line 6)) (41.0.1)
Requirement already satisfied: aiohttp==3.8.4 in d:\freqtrade\.env\lib\site-packages (from -r requirements.txt (line 8)) (3.8.4)
Requirement already satisfied: SQLAlchemy==2.0.17 in d:\freqtrade\.env\lib\site-packages (from -r requirements.txt (line 9)) (2.0.17)
Requirement already satisfied: python-telegram-bot==20.3 in d:\freqtrade\.env\lib\site-packages (from -r requirements.txt (line 10)) (20.3)
Requirement already satisfied: httpx>=0.24.1 in d:\freqtrade\.env\lib\site-packages (from -r requirements.txt (line 12)) (0.24.1)
Requirement already satisfied: arrow==1.2.3 in d:\freqtrade\.env\lib\site-packages (from -r requirements.txt (line 13)) (1.2.3)
Requirement already satisfied: cachetools==5.3.1 in d:\freqtrade\.env\lib\site-packages (from -r requirements.txt (line 14)) (5.3.1)
Requirement already satisfied: requests==2.31.0 in d:\freqtrade\.env\lib\site-packages (from -r requirements.txt (line 15)) (2.31.0)
Requirement already satisfied: urllib3==2.0.3 in d:\freqtrade\.env\lib\site-packages (from -r requirements.txt (line 16)) (2.0.3)
Requirement already satisfied: jsonschema==4.17.3 in d:\freqtrade\.env\lib\site-packages (from -r requirements.txt (line 17)) (4.17.3)
Requirement already satisfied: TA-Lib==0.4.26 in d:\freqtrade\.env\lib\site-packages (from -r requirements.txt (line 18)) (0.4.26)
Requirement already satisfied: technical==1.4.0 in d:\freqtrade\.env\lib\site-packages (from -r requirements.txt (line 19)) (1.4.0)
Requirement already satisfied: tabulate==0.9.0 in d:\freqtrade\.env\lib\site-packages (from -r requirements.txt (line 20)) (0.9.0)
Requirement already satisfied: pycoingecko==3.1.0 in d:\freqtrade\.env\lib\site-packages (from -r requirements.txt (line 21)) (3.1.0)
Requirement already satisfied: jinja2==3.1.2 in d:\freqtrade\.env\lib\site-packages (from -r requirements.txt (line 22)) (3.1.2)
Requirement already satisfied: tables==3.8.0 in d:\freqtrade\.env\lib\site-packages (from -r requirements.txt (line 23)) (3.8.0)
Requirement already satisfied: blosc==1.11.1 in d:\freqtrade\.env\lib\site-packages (from -r requirements.txt (line 24)) (1.11.1)
Requirement already satisfied: joblib==1.2.0 in d:\freqtrade\.env\lib\site-packages (from -r requirements.txt (line 25)) (1.2.0)
Requirement already satisfied: rich==13.4.2 in d:\freqtrade\.env\lib\site-packages (from -r requirements.txt (line 26)) (13.4.2)
Requirement already satisfied: pyarrow==12.0.0 in d:\freqtrade\.env\lib\site-packages (from -r requirements.txt (line 27)) (12.0.0)
Requirement already satisfied: py_find_1st==1.1.5 in d:\freqtrade\.env\lib\site-packages (from -r requirements.txt (line 30)) (1.1.5)
Requirement already satisfied: python-rapidjson==1.10 in d:\freqtrade\.env\lib\site-packages (from -r requirements.txt (line 33)) (1.10)
Requirement already satisfied: orjson==3.9.1 in d:\freqtrade\.env\lib\site-packages (from -r requirements.txt (line 35)) (3.9.1)
Requirement already satisfied: sdnotify==0.3.2 in d:\freqtrade\.env\lib\site-packages (from -r requirements.txt (line 38)) (0.3.2)
Requirement already satisfied: fastapi==0.99.1 in d:\freqtrade\.env\lib\site-packages (from -r requirements.txt (line 41)) (0.99.1)
Requirement already satisfied: pydantic==1.10.9 in d:\freqtrade\.env\lib\site-packages (from -r requirements.txt (line 42)) (1.10.9)
Requirement already satisfied: uvicorn==0.22.0 in d:\freqtrade\.env\lib\site-packages (from -r requirements.txt (line 43)) (0.22.0)
Requirement already satisfied: pyjwt==2.7.0 in d:\freqtrade\.env\lib\site-packages (from -r requirements.txt (line 44)) (2.7.0)
Requirement already satisfied: aiofiles==23.1.0 in d:\freqtrade\.env\lib\site-packages (from -r requirements.txt (line 45)) (23.1.0)
Requirement already satisfied: psutil==5.9.5 in d:\freqtrade\.env\lib\site-packages (from -r requirements.txt (line 46)) (5.9.5)
Requirement already satisfied: colorama==0.4.6 in d:\freqtrade\.env\lib\site-packages (from -r requirements.txt (line 49)) (0.4.6)
Requirement already satisfied: questionary==1.10.0 in d:\freqtrade\.env\lib\site-packages (from -r requirements.txt (line 51)) (1.10.0)
Requirement already satisfied: prompt-toolkit==3.0.38 in d:\freqtrade\.env\lib\site-packages (from -r requirements.txt (line 52)) (3.0.38)
Requirement already satisfied: python-dateutil==2.8.2 in d:\freqtrade\.env\lib\site-packages (from -r requirements.txt (line 54)) (2.8.2)
Requirement already satisfied: schedule==1.2.0 in d:\freqtrade\.env\lib\site-packages (from -r requirements.txt (line 57)) (1.2.0)
Requirement already satisfied: websockets==11.0.3 in d:\freqtrade\.env\lib\site-packages (from -r requirements.txt (line 60)) (11.0.3)
Requirement already satisfied: janus==1.0.0 in d:\freqtrade\.env\lib\site-packages (from -r requirements.txt (line 61)) (1.0.0)
Requirement already satisfied: ast-comments==1.1.0 in d:\freqtrade\.env\lib\site-packages (from -r requirements.txt (line 63)) (1.1.0)
Requirement already satisfied: packaging==23.1 in d:\freqtrade\.env\lib\site-packages (from -r requirements.txt (line 64)) (23.1)
Requirement already satisfied: pytz>=2020.1 in d:\freqtrade\.env\lib\site-packages (from pandas==2.0.2->-r requirements.txt (line 2)) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in d:\freqtrade\.env\lib\site-packages (from pandas==2.0.2->-r requirements.txt (line 2)) (2023.3)
Requirement already satisfied: setuptools>=60.9.0 in d:\freqtrade\.env\lib\site-packages (from ccxt==3.1.44->-r requirements.txt (line 5)) (65.5.0)
Requirement already satisfied: certifi>=2018.1.18 in d:\freqtrade\.env\lib\site-packages (from ccxt==3.1.44->-r requirements.txt (line 5)) (2023.7.22)
Requirement already satisfied: aiodns>=1.1.1 in d:\freqtrade\.env\lib\site-packages (from ccxt==3.1.44->-r requirements.txt (line 5)) (3.0.0)
Requirement already satisfied: yarl>=1.7.2 in d:\freqtrade\.env\lib\site-packages (from ccxt==3.1.44->-r requirements.txt (line 5)) (1.9.2)
Requirement already satisfied: cffi>=1.12 in d:\freqtrade\.env\lib\site-packages (from cryptography==41.0.1->-r requirements.txt (line 6)) (1.15.1)
Requirement already satisfied: attrs>=17.3.0 in d:\freqtrade\.env\lib\site-packages (from aiohttp==3.8.4->-r requirements.txt (line 8)) (23.1.0)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in d:\freqtrade\.env\lib\site-packages (from aiohttp==3.8.4->-r requirements.txt (line 8)) (3.2.0)
Requirement already satisfied: multidict<7.0,>=4.5 in d:\freqtrade\.env\lib\site-packages (from aiohttp==3.8.4->-r requirements.txt (line 8)) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in d:\freqtrade\.env\lib\site-packages (from aiohttp==3.8.4->-r requirements.txt (line 8)) (4.0.2)
Requirement already satisfied: frozenlist>=1.1.1 in d:\freqtrade\.env\lib\site-packages (from aiohttp==3.8.4->-r requirements.txt (line 8)) (1.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in d:\freqtrade\.env\lib\site-packages (from aiohttp==3.8.4->-r requirements.txt (line 8)) (1.3.1)
Requirement already satisfied: typing-extensions>=4.2.0 in d:\freqtrade\.env\lib\site-packages (from SQLAlchemy==2.0.17->-r requirements.txt (line 9)) (4.7.1)
Requirement already satisfied: greenlet!=0.4.17 in d:\freqtrade\.env\lib\site-packages (from SQLAlchemy==2.0.17->-r requirements.txt (line 9)) (2.0.2)
Requirement already satisfied: idna<4,>=2.5 in d:\freqtrade\.env\lib\site-packages (from requests==2.31.0->-r requirements.txt (line 15)) (3.4)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in d:\freqtrade\.env\lib\site-packages (from jsonschema==4.17.3->-r requirements.txt (line 17)) (0.19.3)
Requirement already satisfied: MarkupSafe>=2.0 in d:\freqtrade\.env\lib\site-packages (from jinja2==3.1.2->-r requirements.txt (line 22)) (2.1.3)
Requirement already satisfied: cython>=0.29.21 in d:\freqtrade\.env\lib\site-packages (from tables==3.8.0->-r requirements.txt (line 23)) (3.0.0)
Requirement already satisfied: numexpr>=2.6.2 in d:\freqtrade\.env\lib\site-packages (from tables==3.8.0->-r requirements.txt (line 23)) (2.8.4)
Requirement already satisfied: blosc2~=2.0.0 in d:\freqtrade\.env\lib\site-packages (from tables==3.8.0->-r requirements.txt (line 23)) (2.0.0)
Requirement already satisfied: py-cpuinfo in d:\freqtrade\.env\lib\site-packages (from tables==3.8.0->-r requirements.txt (line 23)) (9.0.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in d:\freqtrade\.env\lib\site-packages (from rich==13.4.2->-r requirements.txt (line 26)) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in d:\freqtrade\.env\lib\site-packages (from rich==13.4.2->-r requirements.txt (line 26)) (2.15.1)
Requirement already satisfied: starlette<0.28.0,>=0.27.0 in d:\freqtrade\.env\lib\site-packages (from fastapi==0.99.1->-r requirements.txt (line 41)) (0.27.0)
Requirement already satisfied: click>=7.0 in d:\freqtrade\.env\lib\site-packages (from uvicorn==0.22.0->-r requirements.txt (line 43)) (8.1.6)
Requirement already satisfied: h11>=0.8 in d:\freqtrade\.env\lib\site-packages (from uvicorn==0.22.0->-r requirements.txt (line 43)) (0.14.0)
Requirement already satisfied: wcwidth in d:\freqtrade\.env\lib\site-packages (from prompt-toolkit==3.0.38->-r requirements.txt (line 52)) (0.2.6)
Requirement already satisfied: six>=1.5 in d:\freqtrade\.env\lib\site-packages (from python-dateutil==2.8.2->-r requirements.txt (line 54)) (1.16.0)
Requirement already satisfied: httpcore<0.18.0,>=0.15.0 in d:\freqtrade\.env\lib\site-packages (from httpx>=0.24.1->-r requirements.txt (line 12)) (0.17.3)
Requirement already satisfied: sniffio in d:\freqtrade\.env\lib\site-packages (from httpx>=0.24.1->-r requirements.txt (line 12)) (1.3.0)
Requirement already satisfied: pycares>=4.0.0 in d:\freqtrade\.env\lib\site-packages (from aiodns>=1.1.1->ccxt==3.1.44->-r requirements.txt (line 5)) (4.3.0)
Requirement already satisfied: msgpack in d:\freqtrade\.env\lib\site-packages (from blosc2~=2.0.0->tables==3.8.0->-r requirements.txt (line 23)) (1.0.5)
Requirement already satisfied: pycparser in d:\freqtrade\.env\lib\site-packages (from cffi>=1.12->cryptography==41.0.1->-r requirements.txt (line 6)) (2.21)
Requirement already satisfied: anyio<5.0,>=3.0 in d:\freqtrade\.env\lib\site-packages (from httpcore<0.18.0,>=0.15.0->httpx>=0.24.1->-r requirements.txt (line 12)) (3.7.1)
Requirement already satisfied: mdurl~=0.1 in d:\freqtrade\.env\lib\site-packages (from markdown-it-py>=2.2.0->rich==13.4.2->-r requirements.txt (line 26)) (0.1.2)
Requirement already satisfied: exceptiongroup in d:\freqtrade\.env\lib\site-packages (from anyio<5.0,>=3.0->httpcore<0.18.0,>=0.15.0->httpx>=0.24.1->-r requirements.txt (line 12)) (1.1.2)
(.env) PS D:\freqtrade> pip install -e .
Obtaining file:///D:/freqtrade
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error

  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [39 lines of output]
      Traceback (most recent call last):
        File "D:\freqtrade\.env\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\freqtrade\.env\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "D:\freqtrade\.env\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
        File "C:\Users\Mohammad\AppData\Local\Temp\pip-build-env-gm6_2ywc\overlay\Lib\site-packages\setuptools\build_meta.py", line 450, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "C:\Users\Mohammad\AppData\Local\Temp\pip-build-env-gm6_2ywc\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\Mohammad\AppData\Local\Temp\pip-build-env-gm6_2ywc\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\Mohammad\AppData\Local\Temp\pip-build-env-gm6_2ywc\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 64, in <module>
        File "C:\Users\Mohammad\AppData\Local\Temp\pip-build-env-gm6_2ywc\overlay\Lib\site-packages\setuptools\__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\Mohammad\AppData\Local\Temp\pip-build-env-gm6_2ywc\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 159, in setup
          dist.parse_config_files()
        File "C:\Users\Mohammad\AppData\Local\Temp\pip-build-env-gm6_2ywc\overlay\Lib\site-packages\setuptools\dist.py", line 894, in parse_config_files
          setupcfg.parse_configuration(
        File "C:\Users\Mohammad\AppData\Local\Temp\pip-build-env-gm6_2ywc\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 189, in parse_configuration
          meta.parse()
        File "C:\Users\Mohammad\AppData\Local\Temp\pip-build-env-gm6_2ywc\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 500, in parse
          section_parser_method(section_options)
        File "C:\Users\Mohammad\AppData\Local\Temp\pip-build-env-gm6_2ywc\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 475, in parse_section
          self[name] = value
        File "C:\Users\Mohammad\AppData\Local\Temp\pip-build-env-gm6_2ywc\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 293, in __setitem__
          parsed = self.parsers.get(option_name, lambda x: x)(value)
        File "C:\Users\Mohammad\AppData\Local\Temp\pip-build-env-gm6_2ywc\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 606, in _parse_version
          return expand.version(self._parse_attr(value, self.package_dir, self.root_dir))
        File "C:\Users\Mohammad\AppData\Local\Temp\pip-build-env-gm6_2ywc\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 417, in _parse_attr
          return expand.read_attr(attr_desc, package_dir, root_dir)
        File "C:\Users\Mohammad\AppData\Local\Temp\pip-build-env-gm6_2ywc\overlay\Lib\site-packages\setuptools\config\expand.py", line 188, in read_attr
          spec = _find_spec(module_name, path)
        File "C:\Users\Mohammad\AppData\Local\Temp\pip-build-env-gm6_2ywc\overlay\Lib\site-packages\setuptools\config\expand.py", line 203, in _find_spec
          raise ModuleNotFoundError(module_name)
      ModuleNotFoundError: freqtrade
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
(.env) PS D:\freqtrade>
```

**Comment by Mo7mud** [comment]
I'm so so sorry
There was some missing folders I don't know how does this happen.
I extracted the folder again and it worked fine
Thank you very much
