### ISSUE TITLE
Sqlite3_operror

### ISSUE THREAD

**Issue by Pomelog** [freqtrade/freqtrade#8969]
## Describe your environment

  * Operating system: __Ubuntu 23.04__
  * Python Version: 3.11.2
  * CCXT version: 4.0.39
  * Freqtrade Version: 2023.6 
  
## Your question
Hi Guys Im currently getting the current log when trying to run 
```
2023-07-25 23:16:20 2023-07-26 02:16:20,223 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2023-07-25 23:16:20 2023-07-26 02:16:20,229 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2023-07-25 23:16:20 2023-07-26 02:16:20,229 - freqtrade.exchange.exchange - INFO - Using CCXT 3.1.44
2023-07-25 23:16:20 2023-07-26 02:16:20,229 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}}
2023-07-25 23:16:20 2023-07-26 02:16:20,234 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}}
2023-07-25 23:16:20 2023-07-26 02:16:20,239 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2023-07-25 23:16:26 2023-07-26 02:16:26,885 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2023-07-25 23:16:27 2023-07-26 02:16:27,190 - freqtrade.commands.trade_commands - ERROR - (sqlite3.OperationalError) disk I/O error

2023-07-25 23:16:27 [SQL: 
2023-07-25 23:16:27 CREATE TABLE "KeyValueStore" (
2023-07-25 23:16:27     id INTEGER NOT NULL, 
2023-07-25 23:16:27     "key" VARCHAR(25) NOT NULL, 
2023-07-25 23:16:27     value_type VARCHAR(20) NOT NULL, 
2023-07-25 23:16:27     string_value VARCHAR(255), 
2023-07-25 23:16:27     datetime_value DATETIME, 
2023-07-25 23:16:27     float_value FLOAT, 
2023-07-25 23:16:27     int_value INTEGER, 
2023-07-25 23:16:27     PRIMARY KEY (id)
2023-07-25 23:16:27 )
2023-07-25 23:16:27 
2023-07-25 23:16:27 ]
2023-07-25 23:16:27 (Background on this error at: https://sqlalche.me/e/20/e3q8)
2023-07-25 23:16:27 2023-07-26 02:16:27,191 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
2023-07-25 23:16:27 Traceback (most recent call last):
2023-07-25 23:16:27   File "/home/ftuser/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
2023-07-25 23:16:27     self.dialect.do_execute(
2023-07-25 23:16:27   File "/home/ftuser/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
2023-07-25 23:16:27     cursor.execute(statement, parameters)
2023-07-25 23:16:27 sqlite3.OperationalError: disk I/O error
2023-07-25 23:16:27 
2023-07-25 23:16:27 The above exception was the direct cause of the following exception:
2023-07-25 23:16:27 
2023-07-25 23:16:27 Traceback (most recent call last):
2023-07-25 23:16:27   File "/freqtrade/freqtrade/commands/trade_commands.py", line 24, in start_trading
2023-07-25 23:16:27     worker = Worker(args)
2023-07-25 23:16:27              ^^^^^^^^^^^^
2023-07-25 23:16:27   File "/freqtrade/freqtrade/worker.py", line 37, in __init__
2023-07-25 23:16:27     self._init(False)
2023-07-25 23:16:27   File "/freqtrade/freqtrade/worker.py", line 53, in _init
2023-07-25 23:16:27     self.freqtrade = FreqtradeBot(self._config)
2023-07-25 23:16:27                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-07-25 23:16:27   File "/freqtrade/freqtrade/freqtradebot.py", line 79, in __init__
2023-07-25 23:16:27     init_db(self.config['db_url'])
2023-07-25 23:16:27   File "/freqtrade/freqtrade/persistence/models.py", line 83, in init_db
2023-07-25 23:16:27     ModelBase.metadata.create_all(engine)
2023-07-25 23:16:27   File "/home/ftuser/.local/lib/python3.11/site-packages/sqlalchemy/sql/schema.py", line 5792, in create_all
2023-07-25 23:16:27     bind._run_ddl_visitor(
2023-07-25 23:16:27   File "/home/ftuser/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3239, in _run_ddl_visitor
2023-07-25 23:16:27     conn._run_ddl_visitor(visitorcallable, element, **kwargs)
2023-07-25 23:16:27   File "/home/ftuser/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2443, in _run_ddl_visitor
2023-07-25 23:16:27     visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
2023-07-25 23:16:27   File "/home/ftuser/.local/lib/python3.11/site-packages/sqlalchemy/sql/visitors.py", line 670, in traverse_single
2023-07-25 23:16:27     return meth(obj, **kw)
2023-07-25 23:16:27            ^^^^^^^^^^^^^^^
2023-07-25 23:16:27   File "/home/ftuser/.local/lib/python3.11/site-packages/sqlalchemy/sql/ddl.py", line 922, in visit_metadata
2023-07-25 23:16:27     self.traverse_single(
2023-07-25 23:16:27   File "/home/ftuser/.local/lib/python3.11/site-packages/sqlalchemy/sql/visitors.py", line 670, in traverse_single
2023-07-25 23:16:27     return meth(obj, **kw)
2023-07-25 23:16:27            ^^^^^^^^^^^^^^^
2023-07-25 23:16:27   File "/home/ftuser/.local/lib/python3.11/site-packages/sqlalchemy/sql/ddl.py", line 960, in visit_table
2023-07-25 23:16:27     )._invoke_with(self.connection)
2023-07-25 23:16:27       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-07-25 23:16:27   File "/home/ftuser/.local/lib/python3.11/site-packages/sqlalchemy/sql/ddl.py", line 315, in _invoke_with
2023-07-25 23:16:27     return bind.execute(self)
2023-07-25 23:16:27            ^^^^^^^^^^^^^^^^^^
2023-07-25 23:16:27   File "/home/ftuser/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
2023-07-25 23:16:27     return meth(
2023-07-25 23:16:27            ^^^^^
2023-07-25 23:16:27   File "/home/ftuser/.local/lib/python3.11/site-packages/sqlalchemy/sql/ddl.py", line 181, in _execute_on_connection
2023-07-25 23:16:27     return connection._execute_ddl(
2023-07-25 23:16:27            ^^^^^^^^^^^^^^^^^^^^^^^^
2023-07-25 23:16:27   File "/home/ftuser/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1524, in _execute_ddl
2023-07-25 23:16:27     ret = self._execute_context(
2023-07-25 23:16:27           ^^^^^^^^^^^^^^^^^^^^^^
2023-07-25 23:16:27   File "/home/ftuser/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
2023-07-25 23:16:27     return self._exec_single_context(
2023-07-25 23:16:27            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-07-25 23:16:27   File "/home/ftuser/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
2023-07-25 23:16:27     self._handle_dbapi_exception(
2023-07-25 23:16:27   File "/home/ftuser/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
2023-07-25 23:16:27     raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
2023-07-25 23:16:27   File "/home/ftuser/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
2023-07-25 23:16:27     self.dialect.do_execute(
2023-07-25 23:16:27   File "/home/ftuser/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
2023-07-25 23:16:27     cursor.execute(statement, parameters)
2023-07-25 23:16:27 sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) disk I/O error
2023-07-25 23:16:27 [SQL: 
2023-07-25 23:16:27 CREATE TABLE "KeyValueStore" (
2023-07-25 23:16:27     id INTEGER NOT NULL, 
2023-07-25 23:16:27     "key" VARCHAR(25) NOT NULL, 
2023-07-25 23:16:27     value_type VARCHAR(20) NOT NULL, 
2023-07-25 23:16:27     string_value VARCHAR(255), 
2023-07-25 23:16:27     datetime_value DATETIME, 
2023-07-25 23:16:27     float_value FLOAT, 
2023-07-25 23:16:27     int_value INTEGER, 
2023-07-25 23:16:27     PRIMARY KEY (id)
2023-07-25 23:16:27 )
2023-07-25 23:16:27 
2023-07-25 23:16:27 ]
```
Hope you can help me thank you very much
*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
The error is quite simple - `2023-07-25 23:16:27 sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) disk I/O error`

There's really only a very limited amount of reasons this can have, which is either 
* file permissions (the bot is not allowed to write the file), 
* filename (the directory you're writing the sqlite file to doesn't exist)
* disk full (this MIGHT raise a different error - but maybe this changed in recent sqlite versions).

**Comment by Pomelog** [comment]
You can't imagine how much of a noob I am XD.

Thanks a lot
