### ISSUE TITLE
Kraken: Manual trades-to-ohlcv formatting question

### ISSUE THREAD

**Issue by ghost** [freqtrade/freqtrade#8980]
* Operating system: Ubuntu 23.04
  * Python Version:  Python 3.11.2
  * CCXT version: 4.0.36
  * Freqtrade Version: freqtrade 2023.8.dev-15dd8bec1

Instead of downloading trades from the kraken API, I have instead sourced them from this webpage on Kraken's website.

 https://support.kraken.com/hc/en-us/articles/360047543791-Downloadable-historical-market-data-time-and-sales-

The data comes as a zip file. When unzipped, we get trade history in the form of csv files named for the pair. 

Ex. BTCUSD.csv, ETHUSD.csv, XRPUSD.csv, SHIBUSD.csv, etc...

I convert pairs which I am interested in to json files using pandas like so

```
import pandas as pd
df = pd.read_csv(inputfile)
df.to_json(outputfile)
```

When I run `freqtrade trades-to-ohlcv --data-format-trades json --data-format-ohlcv feather --timeframes 1m 5m` I get the following output

```
2023-07-29 15:35:33,516 - freqtrade - INFO - freqtrade 2023.8.dev-15dd8bec1
2023-07-29 15:35:33,516 - freqtrade.configuration.load_config - INFO - Using config: config.json ...
2023-07-29 15:35:33,517 - freqtrade.configuration.environment_vars - INFO - Loading variable 'FREQTRADE__EXCHANGE__KEY'
2023-07-29 15:35:33,517 - freqtrade.configuration.environment_vars - INFO - Loading variable 'FREQTRADE__EXCHANGE__SECRET'
2023-07-29 15:35:33,517 - freqtrade.configuration.environment_vars - INFO - Loading variable 'FREQTRADE__TELEGRAM__CHAT_ID'
2023-07-29 15:35:33,517 - freqtrade.configuration.environment_vars - INFO - Loading variable 'FREQTRADE__TELEGRAM__TOKEN'
2023-07-29 15:35:33,517 - freqtrade.loggers - INFO - Verbosity set to 0
2023-07-29 15:35:33,517 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/nick/Repos/freqtrade/user_data ...
2023-07-29 15:35:33,517 - freqtrade.configuration.configuration - INFO - Using data directory: /home/nick/Repos/freqtrade/user_data/data/kraken ...
2023-07-29 15:35:33,517 - freqtrade.configuration.configuration - INFO - timeframes --timeframes: ['1m', '5m']
2023-07-29 15:35:33,517 - freqtrade.configuration.configuration - INFO - Using "feather" to store OHLCV data.
2023-07-29 15:35:33,517 - freqtrade.configuration.configuration - INFO - Using "json" to store trades data.
2023-07-29 15:35:33,517 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2023-07-29 15:35:33,519 - freqtrade.exchange.check_exchange - INFO - Exchange "kraken" is officially supported by the Freqtrade development team.
2023-07-29 15:35:33,519 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2023-07-29 15:35:33,519 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2023-07-29 15:35:33,520 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2023-07-29 15:35:33,520 - freqtrade.exchange.exchange - INFO - Using CCXT 4.0.36
2023-07-29 15:35:33,520 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2023-07-29 15:35:33,521 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 3100}
2023-07-29 15:35:33,522 - freqtrade.exchange.exchange - INFO - Using Exchange "Kraken"
2023-07-29 15:35:33,523 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Kraken'...
2023-07-29 15:35:33,523 - freqtrade.exchange.exchange - INFO - Markets were not loaded. Loading them now..
2023-07-29 15:35:38,145 - freqtrade.commands.data_commands - INFO - About to Convert pairs: ['BTC/USD'], intervals: ['1m', '5m'] to /home/nick/Repos/freqtrade/user_data/data/kraken
2023-07-29 15:35:38,146 - freqtrade.data.history.history_utils - ERROR - Could not convert BTC/USD to OHLCV.
Traceback (most recent call last):
  File "/home/nick/Repos/freqtrade/freqtrade/data/history/history_utils.py", line 447, in convert_trades_to_ohlcv
    ohlcv = trades_to_ohlcv(trades, timeframe)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nick/Repos/freqtrade/freqtrade/data/converter.py", line 229, in trades_to_ohlcv
    raise ValueError('Trade-list empty.')
ValueError: Trade-list empty.
2023-07-29 15:35:38,146 - freqtrade.data.history.history_utils - ERROR - Could not convert BTC/USD to OHLCV.
Traceback (most recent call last):
  File "/home/nick/Repos/freqtrade/freqtrade/data/history/history_utils.py", line 447, in convert_trades_to_ohlcv
    ohlcv = trades_to_ohlcv(trades, timeframe)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nick/Repos/freqtrade/freqtrade/data/converter.py", line 229, in trades_to_ohlcv
    raise ValueError('Trade-list empty.')
ValueError: Trade-list empty.
```

I believe that my json files are misnamed for the pair and are thus not picked up by the program. If this is the case, what should I name them and what should my JSON look like? Otherwise, what is going wrong here?

**Comment by xmatthias** [comment]
Data format for 2023.8 and forward are defaulting to feather data, and prior to that, it was .json.gz data - so make sure that your actual data matches.

You can (probably) convert the data "somehow" - but it must correspond to the format freqtrade uses, so you MAY need to convert the data first (especially around times).
I never looked at kraken's zip data - so i have no idea how it's columns are formatted actually formatted or how they're ordered.

For Freqtrade, we require the following fields to be present: 
`DEFAULT_TRADES_COLUMNS = ['timestamp', 'id', 'type', 'side', 'price', 'amount', 'cost']` (you can find this line in constants.py)
I also don't think that pandas `to_json()` (without additional parameters) will correspond to the format expected, which is a list of lists (not actual dictionaries, which is what to_json would generate).

```
[[1577750669020,null,"limit","buy",0.029799,5.79030258,0.17254522658142],[1577751591462,null,"limit","sell",0.029757,540.95506939,16.097199999838228]
]]]
```

Naming will be `BTC_EUR-trades.<format>` - obviously with format depending on the format used (.json, .json.gz, .feather, ...).

---

Now i'd welcome if you could share your actual solution (assuming you get it working) here for others to use (or better yet, have it somehow incorporated into the freqtrade code - let's discuss how once it's working) - simply because kraken data is VERY painful to use / download.

**Comment by ghost** [comment]
Thank you for the prompt response,

Here is a sample of my XBTUSD.csv file, it seems to be formatted as

' timestamp | price | volume`

```
1381095255,122.00000,0.10000000
1381179030,123.61000,0.10000000
1381201115,123.91000,1.00000000
1381201115,123.90000,0.99160000
1381210004,124.19000,1.00000000
1381210004,124.18000,1.00000000
1381311039,124.01687,1.00000000
1381311093,124.01687,1.00000000
1381311094,123.84000,0.82300000
1381431835,125.85000,1.00000000
1381431835,125.86000,1.00000000
1381571264,127.50000,1.00000000
1381571264,127.40000,1.00000000
1381571264,127.00000,2.00000000
1381690570,131.84080,0.10000000
1381717838,134.80000,0.24000000
1381725605,134.35230,1.00000000
1381725606,134.35230,1.00000000
```

We have to manually add
`id, type, side & cost` information

I am pretty sure `cost` is just `price * volume`, but I do not know what to add for the other missing values.

**Comment by xmatthias** [comment]
you can in theory leave them empty, for current usecases (convert to ohlcv), only price, volume and date are necessary (date is in the wrong format and should be in ms).

it will (almost certainly) not be sufficient for future usecases - but that may be a problem to consider in the future.

I doubt that you can just add a random trade-ID there (You'll either get duplicate data, or gaps in the trades data) - so i'm not entirely sure how you can or should approach this.
