### ISSUE TITLE
using proxy failed 

### ISSUE THREAD

**Issue by uyplayer** [freqtrade/freqtrade#8990]
## Describe your environment

  * Operating system: windows11
  * Python Version:  3.10.11
  * CCXT version: 3.0.100
  * Freqtrade Version:freqtrade 2023.5.dev-bd266f654
  
## Your question
using freqtrade without docker 
i installed freqtrade manually  , and uisng proxy , when i set up proxy in config.json file  and run bot  , it can't load market 

config.json proxy setting : 

`"ccxt_config": {
              "httpProxy":"http://127.0.0.1:7890",
              "httpsProxy": "http://127.0.0.1:7890"
 },`

command : `freqtrade trade --strategy RsiMfi--config user_data/config.json`

this is output 
```
2023-07-31 14:19:00,259 - freqtrade - INFO - freqtrade 2023.5.dev-bd266f654
2023-07-31 14:19:00,385 - freqtrade.worker - INFO - Starting worker 2023.5.dev-bd266f654
2023-07-31 14:19:00,386 - freqtrade.configuration.load_config - INFO - Using config: user_data/config.json ...
2023-07-31 14:19:00,386 - freqtrade.loggers - INFO - Verbosity set to 0
2023-07-31 14:19:00,386 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
2023-07-31 14:19:00,386 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2023-07-31 14:19:00,386 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:///tradesv3.dryrun.sqlite"
2023-07-31 14:19:00,386 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 10 ...
2023-07-31 14:19:00,386 - freqtrade.configuration.configuration - INFO - Using user-data directory: D:\Quantification\TradingBots\freqtrade\user_data ...
2023-07-31 14:19:00,387 - freqtrade.configuration.configuration - INFO - Using data directory: D:\Quantification\TradingBots\freqtrade\user_data\data\binance ...
2023-07-31 14:19:00,387 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2023-07-31 14:19:00,391 - freqtrade.exchange.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2023-07-31 14:19:00,392 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2023-07-31 14:19:00,852 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy RsiMfi from 'D:\Quantification\TradingBots\freqtrade\user_data\strategies\RsiMfi.py'...
2023-07-31 14:19:00,852 - freqtrade.strategy.hyper - INFO - Found no parameter file.
2023-07-31 14:19:00,852 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2023-07-31 14:19:00,853 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: unlimited.
2023-07-31 14:19:00,853 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}.
2023-07-31 14:19:00,853 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'max_open_trades' with value in config file: 10.
2023-07-31 14:19:00,853 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'60': 0.01, '30': 0.02, '0': 0.04}
2023-07-31 14:19:00,853 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 30m
2023-07-31 14:19:00,853 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.1
2023-07-31 14:19:00,853 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2023-07-31 14:19:00,853 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2023-07-31 14:19:00,853 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2023-07-31 14:19:00,853 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2023-07-31 14:19:00,853 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: True
2023-07-31 14:19:00,853 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'entry': 'limit', 'exit': 'limit', 'stoploss': 'market', 'stoploss_on_exchange': False}
2023-07-31 14:19:00,853 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'entry': 'GTC', 'exit': 'GTC'}
2023-07-31 14:19:00,853 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2023-07-31 14:19:00,854 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: unlimited
2023-07-31 14:19:00,854 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2023-07-31 14:19:00,854 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 3000
2023-07-31 14:19:00,854 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}
2023-07-31 14:19:00,854 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_exit_signal: True
2023-07-31 14:19:00,854 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_only: False
2023-07-31 14:19:00,854 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_entry_signal: False
2023-07-31 14:19:00,854 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_offset: 0.0
2023-07-31 14:19:00,854 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2023-07-31 14:19:00,854 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2023-07-31 14:19:00,854 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: False
2023-07-31 14:19:00,854 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1
2023-07-31 14:19:00,854 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_open_trades: 10
2023-07-31 14:19:00,854 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2023-07-31 14:19:00,857 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2023-07-31 14:19:00,858 - freqtrade.exchange.exchange - INFO - Using CCXT 3.0.100
2023-07-31 14:19:00,858 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'httpProxy': 'http://127.0.0.1:7890', 'httpsProxy': 'http://127.0.0.1:7890'}
2023-07-31 14:19:00,862 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'httpProxy': 'http://127.0.0.1:7890', 'httpsProxy': 'http://127.0.0.1:7890'}
2023-07-31 14:19:00,866 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2023-07-31 14:19:10,894 - freqtrade.exchange.exchange - ERROR - Unable to initialize markets.
Traceback (most recent call last):
  File "C:\Users\uyplayer\.conda\envs\freqtrade\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\uyplayer\.conda\envs\freqtrade\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "C:\Users\uyplayer\.conda\envs\freqtrade\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\uyplayer\.conda\envs\freqtrade\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\uyplayer\.conda\envs\freqtrade\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\uyplayer\.conda\envs\freqtrade\lib\site-packages\urllib3\connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "C:\Users\uyplayer\.conda\envs\freqtrade\lib\site-packages\urllib3\connection.py", line 358, in connect
    conn = self._new_conn()
  File "C:\Users\uyplayer\.conda\envs\freqtrade\lib\site-packages\urllib3\connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x000001F0980025F0>, 'Connection to api.binance.com timed out. (connect timeout=10)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\uyplayer\.conda\envs\freqtrade\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "C:\Users\uyplayer\.conda\envs\freqtrade\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "C:\Users\uyplayer\.conda\envs\freqtrade\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/exchangeInfo (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001F0980025F0>, 'Connection to api.binance.com timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\uyplayer\AppData\Roaming\Python\Python310\site-packages\ccxt\base\exchange.py", line 533, in fetch
    response = self.session.request(
  File "C:\Users\uyplayer\.conda\envs\freqtrade\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\uyplayer\.conda\envs\freqtrade\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\uyplayer\.conda\envs\freqtrade\lib\site-packages\requests\adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/exchangeInfo (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001F0980025F0>, 'Connection to api.binance.com timed out. (connect timeout=10)'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Quantification\TradingBots\freqtrade\freqtrade\exchange\exchange.py", line 492, in _load_markets
    self._markets = self._api.load_markets(params={})
  File "C:\Users\uyplayer\AppData\Roaming\Python\Python310\site-packages\ccxt\base\exchange.py", line 1391, in load_markets
    markets = self.fetch_markets(params)
  File "C:\Users\uyplayer\AppData\Roaming\Python\Python310\site-packages\ccxt\binance.py", line 1808, in fetch_markets
    promisesRaw.append(self.publicGetExchangeInfo(params))
  File "C:\Users\uyplayer\AppData\Roaming\Python\Python310\site-packages\ccxt\base\types.py", line 25, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
  File "C:\Users\uyplayer\AppData\Roaming\Python\Python310\site-packages\ccxt\binance.py", line 7208, in request
    response = self.fetch2(path, api, method, params, headers, body, config)
  File "C:\Users\uyplayer\AppData\Roaming\Python\Python310\site-packages\ccxt\base\exchange.py", line 2860, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\uyplayer\AppData\Roaming\Python\Python310\site-packages\ccxt\base\exchange.py", line 563, in fetch
    raise RequestTimeout(details) from e
ccxt.base.errors.RequestTimeout: binance GET https://api.binance.com/api/v3/exchangeInfo
2023-07-31 14:19:10,903 - freqtrade.commands.trade_commands - ERROR - Could not load markets, therefore cannot start. Please investigate the above error for more details.
2023-07-31 14:19:10,904 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "D:\Quantification\TradingBots\freqtrade\freqtrade\commands\trade_commands.py", line 24, in start_trading
    worker = Worker(args)
  File "D:\Quantification\TradingBots\freqtrade\freqtrade\worker.py", line 37, in __init__
    self._init(False)
  File "D:\Quantification\TradingBots\freqtrade\freqtrade\worker.py", line 53, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "D:\Quantification\TradingBots\freqtrade\freqtrade\freqtradebot.py", line 76, in __init__
    self.exchange = ExchangeResolver.load_exchange(
  File "D:\Quantification\TradingBots\freqtrade\freqtrade\resolvers\exchange_resolver.py", line 36, in load_exchange
    exchange = ExchangeResolver._load_exchange(
  File "D:\Quantification\TradingBots\freqtrade\freqtrade\resolvers\exchange_resolver.py", line 63, in _load_exchange
    exchange = ex_class(**kwargs)
  File "D:\Quantification\TradingBots\freqtrade\freqtrade\exchange\exchange.py", line 187, in __init__
    self.validate_config(config)
  File "D:\Quantification\TradingBots\freqtrade\freqtrade\exchange\exchange.py", line 225, in validate_config
    self.validate_stakecurrency(config['stake_currency'])
  File "D:\Quantification\TradingBots\freqtrade\freqtrade\exchange\exchange.py", line 526, in validate_stakecurrency
    raise OperationalException(
freqtrade.exceptions.OperationalException: Could not load markets, therefore cannot start. Please investigate the above error for more details.

```

**Comment by uyplayer** [comment]
curl commnad : `curl api.binance.com/api/v3/exchangeInfo`
and it's result :  
```
StatusCode        : 200
StatusDescription : OK
Content           : {"timezone":"UTC","serverTime":1690785995611,"rateLimits":[{"rateLimitType":"REQUEST_WEIGHT","interval":"MINUTE","intervalNum":1,"limit":1200},{"rateLimitType":"ORDERS","interval":"SECOND","intervalNu...
RawContent        : HTTP/1.1 200 OK
                    Connection: keep-alive
                    Vary: Accept-Encoding
                    x-mbx-uuid: 935c0d0c-d39b-4302-ad76-6e30dd54f7ff
                    x-mbx-used-weight: 10
                    x-mbx-used-weight-1m: 10
                    Strict-Transport-Security: max-age=31...
Forms             : {}
Headers           : {[Connection, keep-alive], [Vary, Accept-Encoding], [x-mbx-uuid, 935c0d0c-d39b-4302-ad76-6e30dd54f7ff], [x-mbx-used-weight, 10]...}
Images            : {}
InputFields       : {}
Links             : {}
ParsedHtml        : mshtml.HTMLDocumentClass
RawContentLength  : 3657409

```

**Comment by xmatthias** [comment]
your curl command doesn't specify an explicit proxy - are you sure a proxy is actually used in that configuration?
An error in the proxy (say, proxy not reachable) would look identical afaik.


---


Aside from that - i think your config is wrong for the version you're using.
Versions prior to 2023.7 required a different configuration - the use of `httpProxy` and `httpsProxy` as supported methods have only been added recently.
Please either update to the latest version - or use the [corresponding documentation](https://www.freqtrade.io/en/2023.6/configuration/#using-proxy-with-freqtrade) for pre-2023.7 proxy configurations.

**Comment by uyplayer** [comment]
yes   i am sure the proxy is working  and the proxy is configurated in Windows network settings. also i configure the docker with proxy , it works

**Comment by xmatthias** [comment]
then the 2nd part fo the comment does apply :)

**Comment by RidiculousDoge** [comment]
> yes i am sure the proxy is working and the proxy is configurated in Windows network settings. also i configure the docker with proxy , it works

Hii, I am facing similar problem as you do. Do you have a solution now? I am sure when I use 
```bash
curl -x 127.0.0.1:7890  https://api.binance.com/api/v3/exchangeInfo
```
the proxy works. However, freqtrade gives me error report 
```
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.12/site-packages/ccxt/base/exchange.py", line 604, in fetch
    response = self.session.request(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/requests/adapters.py", line 513, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/exchangeInfo (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3b6f8a5cd0>: Failed to establish a new connection: [Errno 111] Connection refused')))
```

**Comment by xmatthias** [comment]
@RidiculousDoge please don't highjack issues that have been closed a year ago.

So far, all cases of "proxy error" i've seen have been caused by either a malfunctioning / malconfigured proxy - or by misconfiguration (more frequent).
Please open a new issue, filling out the issue template and providing the parts of the configuration relevant (proxy settings) - so we can have a look at your issue - with your environment and all - without creating pointless noise for everyone involved in this issue so far.
thanks for your understanding.
