### ISSUE TITLE
Using the latest stable version of freqtrade via docker, the proxy settings don't seem to work!

### ISSUE THREAD

**Issue by Jerryyuanyuan** [freqtrade/freqtrade#8996]
## Describe  environment

  * Operating system: Manjaro 22.1.1 Talos
  * Python Version: python3.11
  * CCXT version: CCXT 4.0.36
  * Freqtrade Version: freqtrade 2023.7
  
## Question

When using the latest stable version of freqtrade via docker, the proxy settings don't seem to work in the config.json

`ccxt_config`:
``` 
    	"ccxt_config": {
            "httpProxy":"172.17.0.1:7890",
            "httpProxys":"172.17.0.1:7890"
    	}
```

command :
>`sudo  docker compose run --rm freqtrade backtesting --config user_data/config.json --strategy StrategyCustom  --timerange 20230201-20230801 -i 15m`

output is :
```
2023-08-01 02:06:39,540 - freqtrade - INFO - freqtrade 2023.7
2023-08-01 02:06:39,556 - freqtrade.configuration.load_config - INFO - Using config: user_data/config.json ...
2023-08-01 02:06:39,557 - freqtrade.loggers - INFO - Verbosity set to 0
2023-08-01 02:06:39,558 - freqtrade.configuration.configuration - INFO - Parameter -i/--timeframe detected ... Using timeframe: 15m ...
2023-08-01 02:06:39,558 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 10 ...
2023-08-01 02:06:39,558 - freqtrade.configuration.configuration - INFO - Parameter --timerange detected: 20230201-20230801 ...
2023-08-01 02:06:39,573 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2023-08-01 02:06:39,573 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/binance ...
2023-08-01 02:06:39,573 - freqtrade.configuration.configuration - INFO - Overriding timeframe with Command line argument
2023-08-01 02:06:39,574 - freqtrade.configuration.configuration - INFO - Parameter --cache=day detected ...
2023-08-01 02:06:39,574 - freqtrade.configuration.configuration - INFO - Filter trades by timerange: 20230201-20230801
2023-08-01 02:06:39,575 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2023-08-01 02:06:39,591 - freqtrade.exchange.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2023-08-01 02:06:39,591 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2023-08-01 02:06:39,591 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2023-08-01 02:06:39,596 - freqtrade.commands.optimize_commands - INFO - Starting freqtrade in Backtesting mode
2023-08-01 02:06:39,597 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2023-08-01 02:06:39,597 - freqtrade.exchange.exchange - INFO - Using CCXT 4.0.36
2023-08-01 02:06:39,597 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}, 'httpProxy': '172.17.0.1:7890', 'httpProxys': '172.17.0.1:7890'}
2023-08-01 02:06:39,611 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}, 'httpProxy': '172.17.0.1:7890', 'httpProxys': '172.17.0.1:7890'}
2023-08-01 02:06:39,621 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2023-08-01 02:06:39,694 - freqtrade.exchange.exchange - ERROR - Unable to initialize markets.
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/home/ftuser/.local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/home/ftuser/.local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1092, in _validate_conn
    conn.connect()
  File "/home/ftuser/.local/lib/python3.11/site-packages/urllib3/connection.py", line 642, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/urllib3/connection.py", line 783, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 469, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 513, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ssl.py", line 1075, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.11/ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/ftuser/.local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/home/ftuser/.local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/home/ftuser/.local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1092, in _validate_conn
    conn.connect()
  File "/home/ftuser/.local/lib/python3.11/site-packages/urllib3/connection.py", line 642, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/urllib3/connection.py", line 783, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 469, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 513, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ssl.py", line 1075, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.11/ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/base/exchange.py", line 574, in fetch
    response = self.session.request(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/exchange.py", line 491, in _load_markets
    self._markets = self._api.load_markets(params={})
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/base/exchange.py", line 1434, in load_markets
    markets = self.fetch_markets(params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/binance.py", line 1943, in fetch_markets
    promisesRaw.append(self.publicGetExchangeInfo(params))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/base/types.py", line 26, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/binance.py", line 7489, in request
    response = self.fetch2(path, api, method, params, headers, body, config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/base/exchange.py", line 2986, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/base/exchange.py", line 627, in fetch
    raise NetworkError(details) from e
ccxt.base.errors.NetworkError: binance GET https://api.binance.com/api/v3/exchangeInfo
2023-08-01 02:06:39,704 - freqtrade - ERROR - Could not load markets, therefore cannot start. Please investigate the above error for more details.
```
---

But if you use this:
```
        "ccxt_config": {
		"aiohttp_proxy":"http://172.17.0.1:7890",
		"proxies":{
			"http":"http://172.17.0.1:7890",
			"https":"http://172.17.0.1:7890"
		}
```
 I can see log output like this:
```
INFO[91570] [TCP] 172.19.0.2:49322 --> fapi.binance.com:443 match DomainSuffix(binance.com) using Proxy[V2-889|x2.0] 
```
This proves that the proxy settings are in effect.

## By the way 
ccxt supports socks proxy, but when I set it in `config.json`, freqtrade prompts me to install `pysocks` package, if this is a problem, please fix it. Thank you!

**Comment by xmatthias** [comment]
Your configuration is wrong for the new version (both).
Please refer to the [corresponding documentation](https://www.freqtrade.io/en/stable/configuration/#proxy-exchange-requests) for proper configuration.

Your first version is using `httpProxy` - and `httpProxys` - the first will only cover http calls, while the latter is not a valid key and is therefore ignored.
the ONLY setting / key you should need is `httpsProxy`.

This changed in the release of 2023.7 - and was explicitly highlighted in the [release notes](https://github.com/freqtrade/freqtrade/releases/tag/2023.7) for this version.

You also shouldn't set both values - but just the https version. 
While i'm not entirely sure how ccxt will handle the case of setting both - i know it works with just httpsProxy, as that's a configuration i need to use myself from time to time.

**Comment by Jerryyuanyuan** [comment]
> Your configuration is wrong for the new version. Please refer to the [corresponding documentation](https://www.freqtrade.io/en/stable/configuration/#proxy-exchange-requests) for proper configuration.
> 
> This changed in the release of 2023.7 - and was explicitly highlighted in the [release notes](https://github.com/freqtrade/freqtrade/releases/tag/2023.7) for this version.
> 
> You also shouldn't set both values - but just the https version. While i'm not entirely sure how ccxt will handle the case of setting both - i know it works with just httpsProxy, as that's a configuration i need to use myself from time to time.
---
Thanks for answering my question.
ccxt set proxy:
![image](https://github.com/freqtrade/freqtrade/assets/18299433/66f40d78-2c82-41ab-8350-d0c79eab3c20)
Well, I have corrected the configuration and tested it according to what you said. Really only supports configuring https proxy?

It is my habit to set two agents, such as the environment variables declared in docker-compose.yml.
![image](https://github.com/freqtrade/freqtrade/assets/18299433/bbec07ea-9fd9-41a3-a100-a542d0323705)

However, I think socks proxies are more versatile than https proxies.
Thanks again for your reply!

**Comment by xmatthias** [comment]
ccxt does no longer support environment variables as proxies (and only did so partially in the past). As such, we'll also not be supporting this.

You should be able to use socks proxies, too - at least for the exchange part (we only really pass these settings to ccxt).

It may require additional dependencies, which in a docker environment, you can quite easily [add](https://www.freqtrade.io/en/stable/docker_quickstart/#additional-dependencies-with-docker).
