### ISSUE TITLE
An error occurred

### ISSUE THREAD

**Issue by sdasdasddaaaa** [freqtrade/freqtrade#9017]
When running the backtest command, this error occurred, how to solve it? Thanks
```
Traceback (most recent call last):
  File "E:\anaconda\envs\Freqtrade\lib\asyncio\proactor_events.py", line 116, in __del__
    self. close()
  File "E:\anaconda\envs\Freqtrade\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "E:\anaconda\envs\Freqtrade\lib\asyncio\base_events.py", line 719, in call_soon
    self._check_closed()
  File "E:\anaconda\envs\Freqtrade\lib\asyncio\base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000026685FEB4C0>
Traceback (most recent call last):
  File "E:\anaconda\envs\Freqtrade\lib\asyncio\proactor_events.py", line 116, in __del__
    self. close()
  File "E:\anaconda\envs\Freqtrade\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "E:\anaconda\envs\Freqtrade\lib\asyncio\base_events.py", line 719, in call_soon
    self._check_closed()
  File "E:\anaconda\envs\Freqtrade\lib\asyncio\base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000026685FEB4C0>
Traceback (most recent call last):
  File "E:\anaconda\envs\Freqtrade\lib\asyncio\proactor_events.py", line 116, in __del__
    self. close()
  File "E:\anaconda\envs\Freqtrade\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "E:\anaconda\envs\Freqtrade\lib\asyncio\base_events.py", line 719, in call_soon
    self._check_closed()
  File "E:\anaconda\envs\Freqtrade\lib\asyncio\base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

**Comment by xmatthias** [comment]
As no verision has been provided, i'll be closing this with the assumption that you're using an outdated version.

Feel free to comment below if you are still enocuntering this issue after updating.
