### ISSUE TITLE
freqtrade - Error - Could not load market

### ISSUE THREAD

**Issue by sdasdasddaaaa** [freqtrade/freqtrade#9019]
freqtrade is installed normally, my system is win10, python=3.8, I encountered when running the backtesting command freqtrade backtesting --config config_examples/config.json --strategy-path config_examples --strategy my_awesome_strategy --timerange=20180101-20181231 to the error, the error is displayed as
```
Traceback (most recent call last):
  File "D:\freqtrade\freqtrade\freqtrade\exchange\exchange.py", line 491, in _load_markets
    self._markets = self._api.load_markets(params={})
  File "E:\anaconda\envs\Freqtrade\lib\site-packages\ccxt\base\exchange.py", line 1434, in load_markets
    markets = self.fetch_markets(params)
  File "E:\anaconda\envs\Freqtrade\lib\site-packages\ccxt\binance.py", line 1947, in fetch_markets
    promisesRaw.append(self.publicGetExchangeInfo(params))
  File "E:\anaconda\envs\Freqtrade\lib\site-packages\ccxt\base\types.py", line 26, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
  File "E:\anaconda\envs\Freqtrade\lib\site-packages\ccxt\binance.py", line 7476, in request
    response = self.fetch2(path, api, method, params, headers, body, config)
  File "E:\anaconda\envs\Freqtrade\lib\site-packages\ccxt\base\exchange.py", line 2991, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "E:\anaconda\envs\Freqtrade\lib\site-packages\ccxt\base\exchange.py", line 604, in fetch
    raise RequestTimeout(details) from e
2023-08-06 15:54:37,665 - freqtrade - ERROR - Could not load markets, therefore cannot start. Please investigate the above error for more details
```
How should this error be resolved? Thanks!

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

The error is a RequestTimeout - which means the bot could not connect to the exchange.

That can have many reasons, like (from most likely to most unlikely)
* you're using an outdated version (no version was provided, so this is the most likely reason)
* your internet is unstable
* your location/country is blocked by the exchange selected
* the exchange had some downtime

**Comment by xmatthias** [comment]
Assuming the above explanations were sufficient to have you work this out.

feel free to comment below if it's still a problem and you suspect is not one of the above reasons (which is unlikely).
