### ISSUE TITLE
Freqtrade dies when using force_exit from UI

### ISSUE THREAD

**Issue by Mandark-droid** [freqtrade/freqtrade#9025]
Freqtrade Dies when using force_exit from the FreqUI for version  docker-2023.8.dev-3612956b. 

Please fix it and let me know if any additional info is required.

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

to be quite frank, this issue should be closed without further comment (not gonna do this for now, ...).
All it says is "Fix it" - without providing ANY information whatsoever.

To look at this - you'll definitely have to provide us with the logs of what's happening.

Please make sure to have
* the full stacktrace of the exception
* At least a few lines before that exception
* Information about the strategy / exchange  used (if it's live or dry, ...).

**Comment by Mandark-droid** [comment]
1.Logs are in info mode and don't see any error/exception stack trace in the logs the process just dies and get a notification on telegram that the process died.
2. Using multiple strategies (NFIX3/SMAOffset_Hippocritical_dca/Private Custom Strategies) and facing this issue across them so its not an issue with the strategy. And if you are active in the NFIX3 group there are others also facing same issue.
3. This is happening in live mode. Since am running FT on docker currently have handled it by adding  --restart=always flag to the docker  run command which restarts the container when this happens but its an issue with FT.

**Comment by xmatthias** [comment]
There must be a stacktrace of what's happening (python doesn't crash without stacktrace, unless it's an out of memory error, in which case the system logs would contain hints about that).

Without stacktrace / error logs, it's not something i can have a look at.

**Comment by Mandark-droid** [comment]
Did a force exit now and found following stack trace.

[SMAOffset_kucoin_usdt_live.log](https://github.com/freqtrade/freqtrade/files/12275010/SMAOffset_kucoin_usdt_live.log)

**Comment by xmatthias** [comment]
extracting the error here to have it easily referencable (and also searchable).

```
2023-08-07 10:00:25,690 - freqtrade.wallets - INFO - Wallets synced.
2023-08-07 10:00:25,929 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': exit, 'trade_id': 94, 'exchange': 'Kucoin', 'pair': 'TARA/USDT', 'leverage': 1.0, 'direction': 'Long', 'gain': 'profit', 'limit': 0.0084501, 'order_rate': 0.0084501, 'order_type': 'limit', 'amount': 222.4425, 'open_rate': 0.0082628, 'close_rate': 0.0084501, 'current_rate': 0.0084501, 'profit_amount': 0.03422816, 'profit_ratio': 0.01858535, 'buy_tag': None, 'enter_tag': None, 'sell_reason': 'force_exit', 'exit_reason': 'force_exit', 'open_date': datetime.datetime(2023, 8, 7, 9, 50, 28, 743038, tzinfo=datetime.timezone.utc), 'close_date': datetime.datetime(2023, 8, 7, 10, 0, 25, 929811, tzinfo=datetime.timezone.utc), 'stake_amount': 1.837997889, 'stake_currency': 'USDT', 'base_currency': 'TARA', 'fiat_currency': 'USD', 'sub_trade': False, 'cumulative_profit': 0.0}
2023-08-07 10:00:26,118 - freqtrade.wallets - INFO - Wallets synced.
2023-08-07 10:00:54,354 - uvicorn.error - INFO - connection closed
2023-08-07 10:00:54,355 - freqtrade.rpc.api_server.ws.channel - INFO - Disconnected from channel - WebSocketChannel(a2fae2f2, ('49.36.11.11', 62399))
2023-08-07 10:00:54,502 - freqtrade.wallets - INFO - Wallets synced.
2023-08-07 10:00:54,502 - freqtrade.freqtradebot - WARNING - Not enough TARA in wallet to exit Trade(id=94, pair=TARA/USDT, amount=222.44250000, is_short=False, leverage=1.0, open_rate=0.00826280, open_since=2023-08-07 09:50:28). Trying to recover.
2023-08-07 10:00:54,874 - freqtrade.freqtradebot - INFO - Found previously unknown order 64d0c0b9c6ddab0001c71c1d for TARA/USDT.
2023-08-07 10:00:54,877 - freqtrade.commands.trade_commands - ERROR - (sqlite3.IntegrityError) UNIQUE constraint failed: orders.ft_pair, orders.order_id
[SQL: INSERT INTO orders (ft_trade_id, ft_order_side, ft_pair, ft_is_open, ft_amount, ft_price, order_id, status, symbol, order_type, side, price, average, amount, filled, remaining, cost, stop_price, order_date, order_filled_date, order_update_date, funding_fee, ft_fee_base) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: (94, 'sell', 'TARA/USDT', 0, 222.4425, 0.0084501, '64d0c0b9c6ddab0001c71c1d', 'closed', 'TARA/USDT', 'limit', 'sell', 0.0084501, 0.0084501, 222.4425, 222.4425, 0.0, 1.87966136925, 0.0, '2023-08-07 10:00:25.819000', '2023-08-07 10:00:25.000000', '2023-08-07 10:00:54.874591', None, None)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2023-08-07 10:00:54,877 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/home/ftuser/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: orders.ft_pair, orders.order_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 25, in start_trading
    worker.run()
  File "/freqtrade/freqtrade/worker.py", line 75, in run
    state = self._worker(old_state=state)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/worker.py", line 116, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs,
  File "/freqtrade/freqtrade/worker.py", line 147, in _throttle
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/worker.py", line 180, in _process_running
    self.freqtrade.process()
  File "/freqtrade/freqtrade/freqtradebot.py", line 239, in process
    self.exit_positions(trades)
  File "/freqtrade/freqtrade/freqtradebot.py", line 1082, in exit_positions
    self.handle_onexchange_order(trade)
  File "/freqtrade/freqtrade/freqtradebot.py", line 477, in handle_onexchange_order
    Trade.commit()
  File "/freqtrade/freqtrade/persistence/trade_model.py", line 1337, in commit
    Trade.session.commit()
  File "/home/ftuser/.local/lib/python3.11/site-packages/sqlalchemy/orm/scoping.py", line 552, in commit
    return self._proxied.commit()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1920, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/ftuser/.local/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1236, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/ftuser/.local/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1211, in _prepare_impl
    self.session.flush()
  File "/home/ftuser/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4163, in flush
    self._flush(objects)
  File "/home/ftuser/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4298, in _flush
    with util.safe_reraise():
  File "/home/ftuser/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/ftuser/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4259, in _flush
    flush_context.execute()
  File "/home/ftuser/.local/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/ftuser/.local/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/ftuser/.local/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/ftuser/.local/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 1226, in _emit_insert_statements
    result = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
           ^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 483, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/ftuser/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/ftuser/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/home/ftuser/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: orders.ft_pair, orders.order_id
[SQL: INSERT INTO orders (ft_trade_id, ft_order_side, ft_pair, ft_is_open, ft_amount, ft_price, order_id, status, symbol, order_type, side, price, average, amount, filled, remaining, cost, stop_price, order_date, order_filled_date, order_update_date, funding_fee, ft_fee_base) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: (94, 'sell', 'TARA/USDT', 0, 222.4425, 0.0084501, '64d0c0b9c6ddab0001c71c1d', 'closed', 'TARA/USDT', 'limit', 'sell', 0.0084501, 0.0084501, 222.4425, 222.4425, 0.0, 1.87966136925, 0.0, '2023-08-07 10:00:25.819000', '2023-08-07 10:00:25.000000', '2023-08-07 10:00:54.874591', None, None)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2023-08-07 10:00:54,910 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2023-08-07 10:00:54,910 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2023-08-07 10:00:54,912 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2023-08-07 10:00:54,914 - freqtrade.freqtradebot - WARNING - Exception during cleanup: PendingRollbackError This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.IntegrityError) UNIQUE constraint failed: orders.ft_pair, orders.order_id
[SQL: INSERT INTO orders (ft_trade_id, ft_order_side, ft_pair, ft_is_open, ft_amount, ft_price, order_id, status, symbol, order_type, side, price, average, amount, filled, remaining, cost, stop_price, order_date, order_filled_date, order_update_date, funding_fee, ft_fee_base) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: (94, 'sell', 'TARA/USDT', 0, 222.4425, 0.0084501, '64d0c0b9c6ddab0001c71c1d', 'closed', 'TARA/USDT', 'limit', 'sell', 0.0084501, 0.0084501, 222.4425, 222.4425, 0.0, 1.87966136925, 0.0, '2023-08-07 10:00:25.819000', '2023-08-07 10:00:25.000000', '2023-08-07 10:00:54.874591', None, None)]
(Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)
2023-08-07 10:00:54,914 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
2023-08-07 10:00:54,914 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.apiserver ...
2023-08-07 10:00:54,915 - freqtrade.rpc.api_server.webserver - INFO - Stopping API Server
2023-08-07 10:00:54,995 - uvicorn.error - INFO - Shutting down
2023-08-07 10:00:55,097 - uvicorn.error - INFO - Waiting for application shutdown.

```

**Comment by xmatthias** [comment]
@Mandark-droid what's the following query in your database yield?

```
select * from orders where order_id = '64d0c0b9c6ddab0001c71c1d';
```

I'm mainly interested in all dates - but who knows what else can yield some result.


---

side note:
I've tried to replicate this behavior now - but it's not happening to me (though i've tried with several supported exchanges - as i don't have any balance on kucoin ATM).


It'd be great to have some logs from one of the supported exchange. You mentioned others having this problem too - if that's with a proper exchange (not kucoin) - then i'd like to see their logs.

I can't exclude that it's (yet another) oddity of kucoin . . .

**Comment by Mandark-droid** [comment]
> 

Am using the SQL Lite DB not really sure how to query it. If your question is that if the bot reported the trade as exited post reboot then the Answer is yes the very first message on telegram after reboot of the bot is that it exited the trade and same is also updated in the FreqUI as well post reboot.

**Comment by xmatthias** [comment]
you can use sqlite3 to query the database from a server - or sqlitebrowser when running locally.

No, my question isn't about that - the error is that the same orderid is already in the database. This can have multiple reasons, therefore the timing of when that order was inserted (compared to the logs) is important.

**Comment by Mandark-droid** [comment]
Below is the query output.

```
id	ft_trade_id	ft_order_side	ft_pair	ft_is_open	ft_amount	ft_price	order_id	status	symbol	order_type	side	price	average	amount	filled	remaining	cost	stop_price	order_date	order_filled_date	order_update_date	funding_fee	ft_fee_base
273	94	sell	TARA/USDT	0	222.4425	0.0084501	64d0c0b9c6ddab0001c71c1d	closed	TARA/USDT	limit	sell	0.0084501	0.0084501	222.4425	222.4425	0	1.87966136925	0	2023-08-07 10:00:25.819000	2023-08-07 10:02:25.273545	2023-08-07 10:02:25.273550	0	null
```

**Comment by xmatthias** [comment]
Well it's not what i suspected (a race condition).
First off - all code involved in this is properly mutexed - and the time distance between "insert order" to "constraint error" is almost ~20 seconds (logs had this info, but i wanted the DB to confirm this).


Please enable `"log_responses": true` in the `exchange` section of your configuration and provide us with the logs once the error repeates.
I hope these logs contain more information.


It'd also be great/necessary (unless the above logs turn out to be more conclusive than what i have so far) to have non-kucoin logs (mainly as confirmation that this is not a "Kucoin only" issue).

**Comment by Mandark-droid** [comment]
Well I have added the param you suggested in the config.json in the exchange section and restarted the bot. But at this moment all my funds are locked in few trades due to https://github.com/hippocritical/strategies/issues/3 which relates to  https://github.com/freqtrade/freqtrade/pull/8909 issue and have dropped note in the NFIX3 discord group to others who may be facing this issue to share the logs on this issue, so that you could look into it.  So it could take me sometime to get back unless the funds are released.

**Comment by rmtucker** [comment]
Just had the same problem on Kucoin if it is of any help?
[Kucoin.txt](https://github.com/freqtrade/freqtrade/files/12312081/Kucoin.txt)

**Comment by xmatthias** [comment]
> Just had the same problem on Kucoin if it is of any help?

Thanks for this.
unfortunately it doesn't really help - it contains the same info than the logs above (though in a more concise way) - without further details (log_responses) - or from a different exchange (showing it's not a "kucoin only" problem) - which would be the details that I'm looking for at the moment.

**Comment by xmatthias** [comment]
@Mandark-droid any news on this?

if it didn't happen again with the additional logs again (it's now 3 weeks later), then i'm not sure we'll be able to assist here... and i'm also not sure if it's not been a "temporary kucoin oddity" ...

**Comment by Mandark-droid** [comment]
Hey @xmatthias  Recently due to the given market situation not been getting many trades. But Yeah since last 3 weeks Not seen this issue happen again and I have setup a job to pull the latest dev docker image and apply it to all my bots. And also tried to do some force exit on Binance for 2 trades last week and didnt see this issue happen again.

**Comment by rmtucker** [comment]
Unfortunately i had this issue again 2-3 days ago but this time on OKX,But forgot to record the logs.So i can not be of much help there either.But i will be honest,this was a Force partial exit and it restarted the bot again.
