### ISSUE TITLE
COBINHOOD - fails to update db when cancel unfilled buy order

### ISSUE THREAD

**Issue by iliecosmin** [freqtrade/freqtrade#904]
## Step 1: Have you search for this issue before posting it?

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/freqtrade/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

  * Python Version: 3.6 (`python -V`)
  * Branch: Develop
  * Last Commit ID: 3aff67605e81e0836f7e74c5abbdf24fb5c863c1 (`git log --format="%H" -n 1`)
 
## Step 3: Describe the problem: COBINHOOD - fails to update db when cancel unfilled buy order
Whenever tries to cancel the buy order process dies with the below error:
2018-06-11 22:15:03,552 - freqtrade.rpc.rpc_manager - INFO - *COBINHOOD:* Buying [CMT/ETH](https://cobinhood.com/trade/CMT-ETH) with limit `0.00045866 (0.040000 ETH, 21.042 USD)`
2018-06-11 22:15:04,347 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=2, pair=CMT/ETH, amount=87.21056992, open_rate=0.00045866, open_since=just now)
...
2018-06-11 22:25:05,528 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=2, pair=CMT/ETH, amount=87.21056992, open_rate=0.00045866, open_since=10 minutes ago)
2018-06-11 22:25:05,791 - freqtrade.freqtradebot - INFO - Checking buy signals to create a new trade with stake_amount: 0.040000 ...
2018-06-11 22:25:06,059 - freqtrade.freqtradebot - WARNING - Unable to create trade: stake amount is not fulfilled (currency=ETH)
2018-06-11 22:25:06,602 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 48, in main
    state = freqtrade.worker(old_state=state)
  File "/freqtrade/freqtrade/freqtradebot.py", line 112, in worker
    nb_assets=nb_assets)
  File "/freqtrade/freqtrade/freqtradebot.py", line 124, in _throttle
    result = func(*args, **kwargs)
  File "/freqtrade/freqtrade/freqtradebot.py", line 164, in _process
    self.check_handle_timedout(self.config['unfilledtimeout'])
  File "/freqtrade/freqtrade/freqtradebot.py", line 466, in check_handle_timedout
    self.handle_timedout_limit_buy(trade, order)
  File "/freqtrade/freqtrade/freqtradebot.py", line 478, in handle_timedout_limit_buy
    exchange.cancel_order(trade.open_order_id, trade.pair)
  File "/freqtrade/freqtrade/exchange/__init__.py", line 39, in wrapper
    return f(*args, **kwargs)
  File "/freqtrade/freqtrade/exchange/__init__.py", line 335, in cancel_order
    return _API.cancel_order(order_id, pair)
  File "/usr/local/lib/python3.6/site-packages/ccxt/cobinhood.py", line 465, in cancel_order
    return self.parse_order(response)
  File "/usr/local/lib/python3.6/site-packages/ccxt/cobinhood.py", line 404, in parse_order
    market = self.markets_by_id[marketId]
KeyError: None
2018-06-11 22:25:06,625 - freqtrade.rpc.rpc_manager - INFO - *Status:* `Process died ...`
2018-06-11 22:25:07,183 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2018-06-11 22:25:07,183 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.telegram ...
### Steps to reproduce:

  1. set buy with  "ask_last_balance": 0.6 and "unfilledtimeout": 10
  2. wait to trigger a buy
  3. whenever will cancel buy order
sqlite> select * from trades
   ...> ;
id|exchange|pair|is_open|fee_open|fee_close|open_rate|open_rate_requested|close_rate|close_rate_requested|close_profit|stake_amount|amount|open_date|close_date|open_order_id
1|cobinhood|FXT/ETH|0|0.0|0.0|6.6e-05|6.6e-05|7.0e-05|7.0e-05|0.06060605|0.04|606.060606|2018-06-11 16:25:04.880235|2018-06-11 17:50:05.179910|
2|cobinhood|CMT/ETH|1|0.0|0.0|0.00045866|0.00045866||||0.04|87.2105699210744|2018-06-11 20:15:03.808848||bbdf053c-884f-4b44-827f-54249aa3c0b1

  
### Observed Results:

  * What happened?
  * What did you expect to happen? to corectly update the db as the buy order cancels correctly in cobinhood platform.

### Relevant code exceptions or logs:

  ```
  // paste your log here
  ```

**Comment by xmatthias** [comment]
as bad as it may sound ... Cobinhood is not one of the officially supported exchanges, which means it may (or may not) work.

The problem originates from CCXT - which receives a key-error (either they have a bug - or coinhood returns an unexpected result.
```
File "/usr/local/lib/python3.6/site-packages/ccxt/cobinhood.py", line 404, in parse_order
market = self.markets_by_id[marketId]
```

the ccxt object itself seems to support cancel_order (it's in the ccxt object's "has" object) - but that does not exclude a bug there.

the only thing you could try is to check wether ccxt is updated to the latest version (they update multiple times per day).

**Comment by iliecosmin** [comment]
Tks! Yeah i know is noy a supported one, the bad news is that was working great with an older version of ccxt. I was imagining ccxt is to blame but I was hopping for a fix.



Enviado desde mi smartphone Samsung Galaxy.


-------- Mensaje original --------
De: Matthias <notifications@github.com>
Fecha: 12/6/18 6:58 (GMT+01:00)
Para: freqtrade/freqtrade <freqtrade@noreply.github.com>
Cc: iliecosmin <iliecosmin@hotmail.com>, Author <author@noreply.github.com>
Asunto: Re: [freqtrade/freqtrade] COBINHOOD - fails to update db when cancel unfilled buy order (#904)


as bad as it may sound ... Cobinhood is not one of the officially supported exchanges, which means it may (or may not) work.

The problem originates from CCXT - which receives a key-error (either they have a bug - or coinhood returns an unexpected result.

File "/usr/local/lib/python3.6/site-packages/ccxt/cobinhood.py", line 404, in parse_order
market = self.markets_by_id[marketId]


the ccxt object itself seems to support cancel_order (it's in the ccxt object's "has" object) - but that does not exclude a bug there.

the only thing you could try is to check wether ccxt is updated to the latest version (they update multiple times per day).

**Comment by xmatthias** [comment]
If you still remember that version, you could try to revert to that ccxt version.

it's a risk - but if you are sure it worked before ... 

there is no "new" feature of ccxt we rely on that i'd know off, so it might as well work (but unsupported, of course)

**Comment by gcarq** [comment]
@iliecosmin Please retry with latest develop branch. If it still doesn't work report this to ccxt, I'm sure they will fix it.

**Comment by iliecosmin** [comment]
Solved.
