### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'predict'  during training while backtesting 

### ISSUE THREAD

**Issue by S-shekharDuggal** [freqtrade/freqtrade#9102]
## Describe your environment

  * Operating system: Windows 10
  * Python Version:3.11.4
  * CCXT version: 4.0.36
  * Freqtrade Version: 2023,7
  
Q1 I'm getting this error whenever I choose "backtest_period_days" to be smaller than 2 days why is this happening and what could be solution? right now value is "backtest_period_days": 0.25,
what else I have observed is if I skip few days for time period it work well but it always happen for the same period its like data is corrupted or leads to condition where sample array does not have any value its really annoying as don't want to  sit in front of system to skip time for get it going any suggestions.

2023-08-24 04:34:49,244 - freqtrade.freqai.freqai_interface - INFO - Training BTC/USDT:USDT, 1/1 pairs from 2020-09-25 00:00:00 to 2020-10-01 00:00:00, 65/424 trains
2023-08-24 04:34:49,254 - freqtrade.freqai.data_kitchen - INFO - Could not find backtesting prediction file at /freqtrade/user_data/models/myAI3/backtesting_predictions/cb_btc_1601510400_prediction.feather
2023-08-24 04:34:49,392 - freqtrade.freqai.freqai_interface - INFO - Could not find model at /freqtrade/user_data/models/myAI3/sub-train-BTC_1601510400/cb_btc_1601510400
2023-08-24 04:34:49,393 - freqtrade.freqai.base_models.BaseRegressionModel - INFO - -------------------- Starting training BTC/USDT:USDT --------------------
2023-08-24 04:34:49,424 - freqtrade.freqai.data_kitchen - INFO - BTC/USDT:USDT: dropped 20 training points due to NaNs in populated dataset 2880.
2023-08-24 04:34:49,424 - freqtrade.freqai.base_models.BaseRegressionModel - INFO - -------------------- Training on data from 2020-09-25 to 2020-09-30 --------------------
2023-08-24 04:34:49,694 - datasieve.pipeline - INFO - reduced feature dimension by 510
2023-08-24 04:34:49,694 - datasieve.pipeline - INFO - explained variance 0.9990203974961234
2023-08-24 04:34:49,721 - datasieve.pipeline - INFO - SVM detected 67 data points as outliers.
2023-08-24 04:34:50,039 - datasieve.pipeline - INFO - SVM detected 586 data points as outliers.
2023-08-24 04:34:50,063 - datasieve.pipeline - INFO - DI tossed 358 predictions for being too far from training data.
2023-08-24 04:34:50,065 - freqtrade.freqai.freqai_interface - WARNING - Training BTC/USDT:USDT raised exception ValueError. Message: Found array with 0 sample(s) (shape=(0, 1)) while a minimum of 1 is required by MinMaxScaler., skipping.
Traceback (most recent call last):
  File "/freqtrade/freqtrade/freqai/freqai_interface.py", line 352, in start_backtesting
    self.model = self.train(dataframe_train, pair, dk)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/freqai/base_models/BaseRegressionModel.py", line 71, in train
    dd["test_labels"], _, _ = dk.label_pipeline.transform(dd["test_labels"])
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/datasieve/pipeline.py", line 99, in transform
    X, y, sample_weight, feature_list = trans.transform(
                                        ^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/datasieve/transforms/sklearn_wrapper.py", line 28, in transform
    X = self._skl.transform(X)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/sklearn/preprocessing/_data.py", line 499, in transform
    X = self._validate_data(
        ^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/sklearn/base.py", line 577, in _validate_data
    X = check_array(X, input_name="X", **check_params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/sklearn/utils/validation.py", line 909, in check_array
    raise ValueError(
ValueError: Found array with 0 sample(s) (shape=(0, 1)) while a minimum of 1 is required by MinMaxScaler.
2023-08-24 04:34:50,077 - freqtrade.freqai.freqai_interface - INFO - Saving metadata to disk.
2023-08-24 04:34:50,175 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 42, in main
    return_code = args['func'](args)
                  ^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 58, in start_backtesting
    backtesting.start()
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 1356, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 1273, in backtest_one_strategy
    preprocessed = self.strategy.advise_all_indicators(data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/strategy/interface.py", line 1322, in advise_all_indicators
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/strategy/interface.py", line 1322, in <dictcomp>
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/strategy/interface.py", line 1354, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/user_data/strategies/myAI3.py", line 563, in populate_indicators
    dataframe = self.freqai.start(dataframe, metadata, self)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/freqai/freqai_interface.py", line 162, in start
    dk = self.start_backtesting(dataframe, metadata, self.dk, strategy)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/freqai/freqai_interface.py", line 373, in start_backtesting
    pred_df, do_preds = self.predict(dataframe_backtest, dk)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/freqai/base_models/BaseRegressionModel.py", line 107, in predict
    predictions = self.model.predict(dk.data_dictionary["prediction_features"])
                  ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'predict'
PS C:\freq>

**Comment by froggleston** [comment]
It looks like your training data is just too small to normalise, maybe through the data that it's dropping (which makes sense if the data are NaNs or outliers). As the error says, you can't normalise an empty array. Does it work if you increase the timerange?

**Comment by S-shekharDuggal** [comment]
for the above time range 2020-09-25 00:00:00 to 2020-10-01 00:00:00 where error pop if I change date of starting 2020-10-1 and ending data whatever i used at first place it works but only once it also didn't worked then I changed that start date by adding 6 days that is 2020-10-7  keeping the end date same as first place then it works 
I added 6 days because I'm using my training period

**Comment by robcaulk** [comment]
If you change the timerange, you should probably also change the `identifier` or delete the `user_data/model/unique-id` folder.

As @froggleston said, your test or train data doesnt have any points after all the outliers and NaNs are extracted. You can reduce the sensitivity of outlier detection by modifying `svm_params` and/or increasing `DI_threshold`. Or you can deactivate outlier methods if you are unsure how to properly use them by setting `DI_threshold: 0` and `use_SVM_to_remove_outliers: false`.

**Comment by S-shekharDuggal** [comment]
that I know but only delete / create new identifier if I use same time range.  if use different time range than I don't.

can you suggest how much minimum training is sufficient enough for AI to work well as we are purging previous models and using adaptive technique then there is no need to train it from long time range as most of the knowledge gonna lost during the transitions

**Comment by S-shekharDuggal** [comment]
or can you tell how much %age of its been passed to new model and how can increase the model retention life is it only by adjusting training period only or something else also and is it possible to pass Boolean values with svm or not if yes then how

**Comment by robcaulk** [comment]
Hello, 

If you change the backtesting timerange, you need to change the identifier.

Choosing hyperparameters, such as the `training_period_days`, depends on a variety of factors related to your strategy entry/exit criteria, your computational resources, your desired trade frequency, your desired trade duration, the types of assets you are trading...etc etc. 

You can control the retrain frequency by setting `live_retrain_hours`. Have a look at our parameter table, you will find many options that may be of use to your particular requirements https://www.freqtrade.io/en/stable/freqai-parameter-table/. You will even find descriptions for `svm_params` and what types are taken for these parameters.

It would appear that your question has been answered so I am closing this issue. If you for some reason require assistance on the original question, feel free to comment below. If you need assistance with other points of FreqAI (which appears to be the case) then open separate issues for each question or visit the Freqtrade/FreqAI discords.

Cheers,

Robert

**Comment by S-shekharDuggal** [comment]
okay thanks
