### ISSUE TITLE
Exception: input_arrays parameter missing required data key: ema1 ... TA-Lib issue?

### ISSUE THREAD

**Issue by tomjrtsmith** [freqtrade/freqtrade#9108]
## Describe your environment

  * Operating system: Ubuntu
  * Python Version: _____ (`python -V`) 3.10.12
  * CCXT version: _____ (`pip freeze | grep ccxt`) ccxt==4.0.12
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker) freqtrade 2023.8.dev-15dd8bec1
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

Unsure what is happening here but from looking at these issues there would appear to be a problem with TA_Lib is this correct? There's no references to ema1 anywhere in the code

https://github.com/freqtrade/freqtrade/pull/7337
https://github.com/freqtrade/freqtrade/issues/5455

### Steps to reproduce:

  1. place ema indicators in strategy
  2. run strategy
  3. _____
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
Aug 27 00:50:42 instance-20221222-1628 freqtrade_ft8b[2586652]: 2023-08-27 00:50:42,772 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error input_arrays parameter missing required data key: ema1 calling <bound method IStrategy._analyze_ticker_internal of <TS_Predict_BTC_Safe.TS_Predict_BTC_Safe object at 0xfffef8113430>>
Aug 27 00:50:42 instance-20221222-1628 freqtrade_ft8b[2586652]: Traceback (most recent call last):
Aug 27 00:50:42 instance-20221222-1628 freqtrade_ft8b[2586652]:   File "/home/ubuntu/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 27, in wrapper
Aug 27 00:50:42 instance-20221222-1628 freqtrade_ft8b[2586652]:     return f(*args, **kwargs)
Aug 27 00:50:42 instance-20221222-1628 freqtrade_ft8b[2586652]:   File "/home/ubuntu/freqtrade/freqtrade/strategy/interface.py", line 856, in _analyze_ticker_internal
Aug 27 00:50:42 instance-20221222-1628 freqtrade_ft8b[2586652]:     dataframe = self.analyze_ticker(dataframe, metadata)
Aug 27 00:50:42 instance-20221222-1628 freqtrade_ft8b[2586652]:   File "/home/ubuntu/freqtrade/freqtrade/strategy/interface.py", line 834, in analyze_ticker
Aug 27 00:50:42 instance-20221222-1628 freqtrade_ft8b[2586652]:     dataframe = self.advise_indicators(dataframe, metadata)
Aug 27 00:50:42 instance-20221222-1628 freqtrade_ft8b[2586652]:   File "/home/ubuntu/freqtrade/freqtrade/strategy/interface.py", line 1354, in advise_indicators
Aug 27 00:50:42 instance-20221222-1628 freqtrade_ft8b[2586652]:     return self.populate_indicators(dataframe, metadata)
Aug 27 00:50:42 instance-20221222-1628 freqtrade_ft8b[2586652]:   File "/home/ubuntu/freqtrade/user_data/strategies/nateemadev/TSPredict/TS_Predict_BTC_Safe.py", line 373, in populate_indicators
Aug 27 00:50:42 instance-20221222-1628 freqtrade_ft8b[2586652]:     dataframe['ema_4'] = ta.EMA(dataframe, timeperiod=4)
Aug 27 00:50:42 instance-20221222-1628 freqtrade_ft8b[2586652]:   File "talib/_abstract.pxi", line 444, in talib._ta_lib.Function.__call__
Aug 27 00:50:42 instance-20221222-1628 freqtrade_ft8b[2586652]:   File "talib/_abstract.pxi", line 303, in talib._ta_lib.Function.set_function_args
Aug 27 00:50:42 instance-20221222-1628 freqtrade_ft8b[2586652]:   File "talib/_abstract.pxi", line 251, in talib._ta_lib.Function.set_input_arrays
Aug 27 00:50:42 instance-20221222-1628 freqtrade_ft8b[2586652]: Exception: input_arrays parameter missing required data key: ema1
Aug 27 00:50:42 instance-20221222-1628 freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error input_arrays parameter missing required data key: ema1 calling <bound method IStrategy._analyze_ticker_internal of <TS_Predict_BTC_Safe.TS_Predict_BTC_Safe object at 0xfffef8113430>>#012Traceback (most recent call last):#012  File "/home/ubuntu/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 27, in wrapper#012    return f(*args, **kwargs)#012  File "/home/ubuntu/freqtrade/freqtrade/strategy/interface.py", line 856, in _analyze_ticker_internal#012    dataframe = self.analyze_ticker(dataframe, metadata)#012  File "/home/ubuntu/freqtrade/freqtrade/strategy/interface.py", line 834, in analyze_ticker#012    dataframe = self.advise_indicators(dataframe, metadata)#012  File "/home/ubuntu/freqtrade/freqtrade/strategy/interface.py", line 1354, in advise_indicators#012    return self.populate_indicators(dataframe, metadata)#012  File "/home/ubuntu/freqtrade/user_data/strategies/nateemadev/TSPredict/TS_Predict_BTC_Safe.py", line 373, in populate_indicators#012    dataframe['ema_4'] = ta.EMA(dataframe, timeperiod=4)#012  File "talib/_abstract.pxi", line 444, in talib._ta_lib.Function.__call__#012  File "talib/_abstract.pxi", line 303, in talib._ta_lib.Function.set_function_args#012  File "talib/_abstract.pxi", line 251, in talib._ta_lib.Function.set_input_arrays#012Exception: input_arrays parameter missing required data key: ema1
  ```

**Comment by xmatthias** [comment]
the error / line sems odd - but i suspect it's due to the stat the dataframe is in when you call ta-lib (you either import ta-lib wrong, or the dataframe doesn't have the required columns).

both suggest an error somewhere in the strategy (most likely NOT in the line that's pointed out).

However, without having the code (or better yet, a minimal reproduction of the error) - there'll nothing further to help you with.
