### ISSUE TITLE
SHIB has a wrong entry value

### ISSUE THREAD

**Issue by Johan1974** [freqtrade/freqtrade#9124]
## Describe your environment

  * Operating system: ubuntu 22
  * Python Version: 3.10.12
  * CCXT version: 4.0.58
  * Freqtrade Version: 2023.7
  
## Your question

I noticed SHIB/EUR has a weird entry point. and starts immediately with a 23% loss. Could this be a bug or am i misunderstanding the this? 

![Knipsel](https://github.com/freqtrade/freqtrade/assets/8274075/e38d23e7-ac07-4787-969c-41dbcb036308)

If i understand correctly this blue long marker should point to whre i started the trade. And i see this with every coin happening but not for the shib. 

Greetings,

Johan

**Comment by xmatthias** [comment]
Well that's just a plot.

Please provide the logs for this entry (and best at least a few log lines before / after that entry - more is usually better).

**Comment by Johan1974** [comment]
Hello,

I found the following lines 

```
2023-08-29 21:11:12,161 - freqtrade.freqtradebot - INFO - Long signal found: about create a new trade for SHIB/EUR with stake_amount: 50.861257423515 ...
2023-08-29 21:11:12,213 - freqtrade.exchange.exchange - INFO - Converted order SHIB/EUR to market order due to price 1e-05 crossing spread by more than 3.00%.
2023-08-29 21:11:12,214 - freqtrade.freqtradebot - INFO - Order #dry_run_buy_1693336272.161774 was created for SHIB/EUR and status is closed.
2023-08-29 21:11:12,226 - freqtrade.wallets - INFO - Wallets synced.
2023-08-29 21:11:12,227 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'trade_id': 43, 'type': entry, 'buy_tag': '3 red candles and one green', 'enter_tag': '3 red candles and one green', 'exchange': 'Bitvavo', 'pair': 'SHIB/EUR', 'leverage': 1.0, 'direction': 'Long', 'limit': 1e-05, 'open_rate': 1e-05, 'order_type': 'limit', 'stake_amount': 66.267012, 'stake_currency': 'EUR', 'base_currency': 'SHIB', 'fiat_currency': 'EUR', 'amount': 6626701.2, 'open_date': datetime.datetime(2023, 8, 29, 19, 11, 12, 214514, tzinfo=datetime.timezone.utc), 'current_rate': 7.6752e-06, 'sub_trade': False}
2023-08-29 21:11:12,228 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=43, pair=SHIB/EUR, amount=6626701.20000000, is_short=False, leverage=1.0, open_rate=0.00001000, open_since=2023-08-29 19:11:12)
2023-08-29 21:11:12,235 - freqtrade.freqtradebot - INFO - Fee for Trade Trade(id=43, pair=SHIB/EUR, amount=6626701.20000000, is_short=False, leverage=1.0, open_rate=0.00001000, open_since=2023-08-29 19:11:12) [buy]: 0.16566753 EUR - rate: 0.0025
2023-08-29 21:11:12,236 - freqtrade.persistence.trade_model - INFO - Updating trade (id=43) ...
2023-08-29 21:11:12,236 - freqtrade.persistence.trade_model - INFO - MARKET_BUY has been fulfilled for Trade(id=43, pair=SHIB/EUR, amount=6626701.20000000, is_short=False, leverage=1.0, open_rate=0.00001000, open_since=2023-08-29 19:11:12).
2023-08-29 21:11:12,247 - freqtrade.wallets - INFO - Wallets synced.
2023-08-29 21:11:12,252 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'trade_id': 43, 'type': entry_fill, 'buy_tag': '3 red candles and one green', 'enter_tag': '3 red candles and one green', 'exchange': 'Bitvavo', 'pair': 'SHIB/EUR', 'leverage': 1.0, 'direction': 'Long', 'limit': 1e-05, 'open_rate': 1e-05, 'order_type': 'market', 'stake_amount': 66.267012, 'stake_currency': 'EUR', 'base_currency': 'SHIB', 'fiat_currency': 'EUR', 'amount': 6626701.2, 'open_date': datetime.datetime(2023, 8, 29, 19, 11, 12, 214514, tzinfo=datetime.timezone.utc), 'current_rate': 7.6752e-06, 'sub_trade': False}
2023-08-29 21:11:12,252 - freqtrade.rpc.telegram - INFO - Notification 'entry_fill' not sent.
```

I see this only happening with the Combination SHIB/EUR. Open rate starts allways at 0.00001

![image](https://github.com/freqtrade/freqtrade/assets/8274075/30a8ed61-a9b7-4ef0-b8cc-c081a53592c9)

Hope this is more clear,

Johan

**Comment by Johan1974** [comment]
Found also more like an error in the logfile that might have anything to do with this.
Although it is not near the SHIB/EUR pair.
 

```
2023-08-29 22:13:23 - freqtrade.data.converter - INFO - Missing data fillup for EOS/EUR: before: 1439 - after: 7176 - 398.68%
2023-08-29 22:13:32 - uvicorn.error - ERROR - Exception in ASGI application

Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/fastapi/applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ftuser/.local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ftuser/.local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/ftuser/.local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/ftuser/.local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/home/ftuser/.local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/ftuser/.local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/ftuser/.local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/ftuser/.local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/ftuser/.local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/ftuser/.local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/ftuser/.local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/fastapi/routing.py", line 192, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/rpc/api_server/api_v1.py", line 86, in performance
    return rpc._rpc_performance()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/rpc/rpc.py", line 978, in _rpc_performance
    pair_rates = Trade.get_overall_performance()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/persistence/trade_model.py", line 1496, in get_overall_performance
    return [
           ^
  File "/freqtrade/freqtrade/persistence/trade_model.py", line 1500, in <listcomp>
    'profit': round(profit * 100, 2),  # Compatibility mode
                    ~~~~~~~^~~~~
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
2023-08-29 22:13:32 - freqtrade.data.converter - INFO - Missing data fillup for ONT/EUR: before: 1439 - after: 9601 - 567.20%
```

**Comment by xmatthias** [comment]
that SHIB/EUR problem is an interesting problem indeed - and caused by the fact that bitvavo uses an exotic rounding method (in the sense of - almost no other exchange uses this).

They specify "pricePrecision 5" - which in their case means "5 significant digits".
As we didn't have an exchange with this kind of behavior before, code around this was not 100% tested (the problem also only shows wiht VERY low-value assets, otherwise both rounding methods are roughly identical).
this caused price to be "rounded" to 5 decimals (0.00001) - and in some other cases, maybe even to 0.00000 (which would explain the 2nd problem).

I've updated the calculations for this (including a ton of tests) - so in my tests, SHIB/EUR (and BTT/EUR, which is even lower priced) do work fine with the latest develop version.

![image](https://github.com/freqtrade/freqtrade/assets/5024695/d5a0701d-573e-4730-8c24-fb3a02d3b896)

**Comment by Johan1974** [comment]
That was a quick fix. 

I will include SHIB/EUR again and see if no problems arise anymore. 
Is the last error i send also related to this or is this something else?

Otherwise i can first check and if i still see this error with the dev version. 
If so i will repost back to you.

Thanks!

**Comment by xmatthias** [comment]
might be - it's an ... oddity - but can be caused by this - as it efectively only says "you had an open trade with no profit assigned" ... in theory, this could've happened if a trade opens, and immediately closes for some odd reason (like, being heavily mispriced).

**Comment by Johan1974** [comment]
I am working with the develop image now and it looks like SHIB is now working as it should be.

Thanks!
