### ISSUE TITLE
Error in ARIMA Model Backtesting

### ISSUE THREAD

**Issue by hamidreza07** [freqtrade/freqtrade#9165]
**Description:**
I encountered an issue while trying to backtest my ARIMA model in Freqtrade. The backtesting process resulted in the following error:

```python
Traceback (most recent call last):
  File "/home/arad/miniconda3/envs/freq/lib/python3.8/site-packages/freqtrade-2023.8-py3.8.egg/freqtrade/main.py", line 42, in main
    return_code = args['func'](args)
  File "/home/arad/miniconda3/envs/freq/lib/python3.8/site-packages/freqtrade-2023.8-py3.8.egg/freqtrade/commands/optimize_commands.py", line 58, in start_backtesting
    backtesting.start()
  File "/home/arad/miniconda3/envs/freq/lib/python3.8/site-packages/freqtrade-2023.8-py3.8.egg/freqtrade/optimize/backtesting.py", line 1366, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
  File "/home/arad/miniconda3/envs/freq/lib/python3.8/site-packages/freqtrade-2023.8-py3.8.egg/freqtrade/optimize/backtesting.py", line 1283, in backtest_one_strategy
    preprocessed = self.strategy.advise_all_indicators(data)
  File "/home/arad/miniconda3/envs/freq/lib/python3.8/site-packages/freqtrade-2023.8-py3.8.egg/freqtrade/strategy/interface.py", line 1323, in advise_all_indicators
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "/home/arad/miniconda3/envs/freq/lib/python3.8/site-packages/freqtrade-2023.8-py3.8.egg/freqtrade/strategy/interface.py", line 1323, in <dictcomp>
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "/home/arad/miniconda3/envs/freq/lib/python3.8/site-packages/freqtrade-2023.8-py3.8.egg/freqtrade/strategy/interface.py", line 1355, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/home/arad/Documents/GitHub/freqtrade/freqtrade/templates/FreqaiExampleStrategy.py", line 240, in populate_indicators
    dataframe = self.freqai.start(dataframe, metadata, self)
  File "/home/arad/miniconda3/envs/freq/lib/python3.8/site-packages/freqtrade-2023.8-py3.8.egg/freqtrade/freqai/freqai_interface.py", line 162, in start
    dk = self.start_backtesting(dataframe, metadata, self.dk, strategy)
  File "/home/arad/miniconda3/envs/freq/lib/python3.8/site-packages/freqtrade-2023.8-py3.8.egg/freqtrade/freqai/freqai_interface.py", line 374, in start_backtesting
    append_df = dk.get_predictions_to_append(pred_df, do_preds, dataframe_backtest)
  File "/home/arad/miniconda3/envs/freq/lib/python3.8/site-packages/freqtrade-2023.8-py3.8.egg/freqtrade/freqai/data_kitchen.py", line 423, in get_predictions_to_append
    append_df["do_predict"] = do_predict
  File "/home/arad/miniconda3/envs/freq/lib/python3.8/site-packages/pandas/core/frame.py", line 3950, in __setitem__
    self._set_item(key, value)
  File "/home/arad/miniconda3/envs/freq/lib/python3.8/site-packages/pandas/core/frame.py", line 4143, in _set_item
    value = self._sanitize_column(value)
  File "/home/arad/miniconda3/envs/freq/lib/python3.8/site-packages/pandas/core/frame.py", line 4870, in _sanitize_column
    com.require_length_match(value, self.index)
  File "/home/arad/miniconda3/envs/freq/lib/python3.8/site-packages/pandas/core/common.py", line 576, in require_length_match
    raise ValueError(
ValueError: Length of values (4320) does not match length of index (4279)

```

**Context:**
I am using an ARIMA model for time series forecasting in Freqtrade. The issue occurs during backtesting, and it seems to be related to the length of values not matching the length of the index. 

**Code:**
I am using the following ARIMA model code:

```python
import logging
from typing import Any, Dict
import pandas as pd
from pandas import DataFrame
import numpy as np
from statsmodels.tsa.arima.model import ARIMA

from numpy.typing import NDArray
from typing import Tuple
from freqtrade.freqai.base_models.BaseRegressionModel import BaseRegressionModel
from freqtrade.freqai.data_kitchen import FreqaiDataKitchen
import numpy.typing as npt

logger = logging.getLogger(__name__)

class ARIMAModel(BaseRegressionModel):
    """
    User-created prediction model using ARIMA for time series forecasting.
    """
    def __init__(self, **kwargs) -> None:
        super().__init__(**kwargs)
        self.model = None 
    def fit(self, data_dictionary: Dict, dk: FreqaiDataKitchen, **kwargs) -> Any:
        """
        Fit an ARIMA model to the training data.
        :param data_dictionary: The dictionary holding all data for train, test, labels, and weights.
        :param dk: The data kitchen object for the current coin/model.
        :param kwargs: Additional keyword arguments.
        :return: Trained ARIMA model.
        """


    
        X = data_dictionary["train_features"]
        y = data_dictionary["train_labels"]


        # Fit an ARIMA model (you can adjust the order and other parameters)
        config = self.freqai_info.get("model_training_parameters", {})
        p,d,q = config.get("p",1),config.get("d",0),config.get("q",1)
        basemodel = ARIMA(endog=y,exog=X, order=(p, d, q))
        model = basemodel.fit()
        self.model = model
        return model
    def predict(
        self, unfiltered_df: DataFrame, dk: FreqaiDataKitchen, **kwargs
    ) -> Tuple[DataFrame, npt.NDArray[np.int_]]:
        """
        Filter the prediction features data and predict with it.
        :param unfiltered_df: Full dataframe for the current backtest period.
        :return:
        :pred_df: dataframe containing the predictions
        :do_predict: np.array of 1s and 0s to indicate places where freqai needed to remove
        data (NaNs) or felt uncertain about data (PCA and DI index)
        """

        dk.find_features(unfiltered_df)
        dk.data_dictionary["prediction_features"], _ = dk.filter_features(
            unfiltered_df, dk.training_features_list, training_filter=False
        )

        dk.data_dictionary["prediction_features"], outliers, _ = dk.feature_pipeline.transform(
            dk.data_dictionary["prediction_features"], outlier_check=True)
        exog=dk.data_dictionary["prediction_features"]
        
        predictions = self.model.forecast(steps=len(exog),exog =exog)
        if self.CONV_WIDTH == 1:
            predictions = np.reshape(predictions, (-1, len(dk.label_list)))
        pred_df = DataFrame(predictions, columns=dk.label_list)

        pred_df, _, _ = dk.label_pipeline.inverse_transform(pred_df)
        if dk.feature_pipeline["di"]:
            dk.DI_values = dk.feature_pipeline["di"].di_values
        else:
            dk.DI_values = np.zeros(outliers.shape[0])
        dk.do_predict = outliers

        return (pred_df, dk.do_predict)

```

**Expected Behavior:**
I expected the ARIMA model to backtest without errors and provide valid results.

**Actual Behavior:**
The backtesting process throws an error, as mentioned above.

**Comment by xmatthias** [comment]
well the error hints at the fact that your model somehow changes the length of the dataframe.

this then results in a (subsequent) error in assignment  - but the error really happens wherever you're adding additional rows (i suspect it's your model doing that?)
The message ` Length of values (4320) does not match length of index (4279)` simply means that wherever we try to append the result, the existing (passed in) dataframe has 4279 rows - where the response from the model has 4320 rows.
now if these rows are added at the beginning or at the end is unclear - but that's up to the model author to figure out an fix.

**Comment by hamidreza07** [comment]
**Thank you for your response!**

I appreciate your help in identifying the issue with the model that caused the error. It makes sense that the error is related to the difference in the number of rows between the model's output and the input dataframe.

Now, I have another question regarding hyperparameter tuning. I would like to optimize the parameters inside the `model_training_parameters` section in the `config.json` file using Hyperopt. Could you please provide guidance on how to set up hyperparameter tuning for these parameters using Hyperopt?

Here's a snippet of the `config.json` file for reference:

```json
"model_training_parameters": {
    "p": 1,
    "d": 0,
    "q": 1
},
```

Any advice or examples on how to configure Hyperopt for this purpose would be greatly appreciated!

Thank you in advance for your assistance.

**Comment by xmatthias** [comment]
You can hyperopt only parameters that are available in the strategy.

You can't use it for random config options - as it'll heavily depend on where initialization happens if modification to these would even take effect.

**Comment by DragonBtc93** [comment]
Did you get any further on this. Been working on same thing but didn't find it in your github. Can you please share.
