### ISSUE TITLE
plot informative error

### ISSUE THREAD

**Issue by zhihuba** [freqtrade/freqtrade#9208]
# version
```bash
(freqtrade) macdeMacBook-Pro freqtrade % pip freeze | grep ccxt
ccxt==4.0.76
(freqtrade) macdeMacBook-Pro freqtrade % python -V
Python 3.11.4
(freqtrade) macdeMacBook-Pro freqtrade % freqtrade -V
freqtrade 2023.9-dev-c894843d0
os mac m1
```
# problem code
```python
# pragma pylint: disable=missing-docstring, invalid-name, pointless-string-statement
# flake8: noqa: F401
# isort: skip_file
# --- Do not remove these libs ---
import numpy as np
import pandas as pd
from pandas import DataFrame
from datetime import datetime
from typing import Optional, Union

from freqtrade.strategy import (BooleanParameter, CategoricalParameter, DecimalParameter,
                                IntParameter, IStrategy, merge_informative_pair, informative)

# --------------------------------
# Add your lib to import here
import talib.abstract as ta
import pandas_ta as pta
from technical import qtpylib,pivots_points

class MyBoot(IStrategy):
  
    INTERFACE_VERSION = 3

    # Optimal timeframe for the strategy.
    timeframe = '5m'

    # Can this strategy go short?
    can_short: bool = False

    # Minimal ROI designed for the strategy.
    # This attribute will be overridden if the config file contains "minimal_roi".
    minimal_roi = {
        "60": 0.01,
        "30": 0.02,
        "0": 0.04
    }

    # Optimal stoploss designed for the strategy.
    # This attribute will be overridden if the config file contains "stoploss".
    stoploss = -0.10

    # Trailing stoploss
    trailing_stop = False
    # trailing_only_offset_is_reached = False
    # trailing_stop_positive = 0.01
    # trailing_stop_positive_offset = 0.0  # Disabled / not configured

    # Run "populate_indicators()" only for new candle.
    process_only_new_candles = True

    # These values can be overridden in the config.
    use_exit_signal = True
    exit_profit_only = False
    ignore_roi_if_entry_signal = False

    # Number of candles the strategy requires before producing valid signals
    startup_candle_count: int = 30

    # Strategy parameters
    buy_rsi = IntParameter(10, 40, default=30, space="buy")
    sell_rsi = IntParameter(60, 90, default=70, space="sell")

    # Optional order type mapping.
    order_types = {
        'entry': 'limit',
        'exit': 'limit',
        'stoploss': 'market',
        'stoploss_on_exchange': False
    }

    # Optional order time in force.
    order_time_in_force = {
        'entry': 'GTC',
        'exit': 'GTC'
    }

    @property
    def plot_config(self):
        return {
            # Main plot indicators (Moving averages, ...)
            'main_plot': {
                'sar': {'color': 'white'}
            },
        }

    @informative('8h')
    def populate_indicators_1h(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe['rsi'] = ta.RSI(dataframe, timeperiod=14)
        return dataframe
    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe['rsi'] = ta.RSI(dataframe, timeperiod=14)
        return dataframe
    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        return dataframe
    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        return dataframe
```
# log
```python
/Users/root/miniconda3/envs/freqtrade/bin/python /Users/root/Desktop/source_code/freqtrade/freqtrade/main.py plot-dataframe -p BTC/USDT:USDT --strategy MyBoot --no-trades -i 5m --datadir user_data/data/binance/ 
2023-09-21 13:07:50,155 - freqtrade - INFO - freqtrade 2023.9-dev-c894843d0
2023-09-21 13:07:50,160 - freqtrade.configuration.load_config - INFO - Using config: user_data/config.json ...
2023-09-21 13:07:50,160 - freqtrade.loggers - INFO - Verbosity set to 0
2023-09-21 13:07:50,160 - freqtrade.configuration.configuration - INFO - Parameter -i/--timeframe detected ... Using timeframe: 5m ...
2023-09-21 13:07:50,160 - freqtrade.configuration.configuration - INFO - Using user-data directory: /Users/root/Desktop/source_code/freqtrade/user_data ...
2023-09-21 13:07:50,160 - freqtrade.configuration.configuration - INFO - Using data directory: user_data/data/binance ...
2023-09-21 13:07:50,160 - freqtrade.configuration.configuration - INFO - Overriding timeframe with Command line argument
2023-09-21 13:07:50,160 - freqtrade.configuration.configuration - INFO - Using pairs ['BTC/USDT:USDT']
2023-09-21 13:07:50,160 - freqtrade.configuration.configuration - INFO - Limiting plot to: 750
2023-09-21 13:07:50,160 - freqtrade.configuration.configuration - INFO - Using trades from: file
2023-09-21 13:07:50,160 - freqtrade.configuration.configuration - INFO - Parameter --no-trades detected.
2023-09-21 13:07:50,161 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2023-09-21 13:07:50,163 - freqtrade.exchange.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2023-09-21 13:07:50,164 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2023-09-21 13:07:50,222 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy MyBoot from '/Users/root/Desktop/source_code/freqtrade/user_data/strategies/MyBoot.py'...
2023-09-21 13:07:50,222 - freqtrade.strategy.hyper - INFO - Found no parameter file.
2023-09-21 13:07:50,222 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 5m.
2023-09-21 13:07:50,222 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2023-09-21 13:07:50,222 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: unlimited.
2023-09-21 13:07:50,222 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}.
2023-09-21 13:07:50,222 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'max_open_trades' with value in config file: 3.
2023-09-21 13:07:50,222 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'60': 0.01, '30': 0.02, '0': 0.04}
2023-09-21 13:07:50,222 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 5m
2023-09-21 13:07:50,222 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.1
2023-09-21 13:07:50,222 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2023-09-21 13:07:50,222 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2023-09-21 13:07:50,222 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2023-09-21 13:07:50,222 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2023-09-21 13:07:50,222 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: True
2023-09-21 13:07:50,222 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'entry': 'limit', 'exit': 'limit', 'stoploss': 'market', 'stoploss_on_exchange': False}
2023-09-21 13:07:50,222 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'entry': 'GTC', 'exit': 'GTC'}
2023-09-21 13:07:50,222 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2023-09-21 13:07:50,222 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: unlimited
2023-09-21 13:07:50,222 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2023-09-21 13:07:50,222 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 30
2023-09-21 13:07:50,222 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}
2023-09-21 13:07:50,222 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_exit_signal: True
2023-09-21 13:07:50,222 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_only: False
2023-09-21 13:07:50,222 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_entry_signal: False
2023-09-21 13:07:50,222 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_offset: 0.0
2023-09-21 13:07:50,222 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2023-09-21 13:07:50,222 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2023-09-21 13:07:50,222 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: False
2023-09-21 13:07:50,222 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1
2023-09-21 13:07:50,222 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_open_trades: 3
2023-09-21 13:07:50,222 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2023-09-21 13:07:50,222 - freqtrade.exchange.exchange - INFO - Using CCXT 4.0.76
2023-09-21 13:07:50,222 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}}
2023-09-21 13:07:50,225 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}}
2023-09-21 13:07:50,228 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2023-09-21 13:07:53,786 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2023-09-21 13:07:53,786 - freqtrade.strategy.hyper - INFO - No params for buy found, using default values.
2023-09-21 13:07:53,786 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): buy_rsi = 30
2023-09-21 13:07:53,786 - freqtrade.strategy.hyper - INFO - No params for sell found, using default values.
2023-09-21 13:07:53,786 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): sell_rsi = 70
2023-09-21 13:07:53,786 - freqtrade.strategy.hyper - INFO - No params for protection found, using default values.
2023-09-21 13:07:53,787 - freqtrade.data.history.history_utils - INFO - Using indicator startup period: 30 ...
2023-09-21 13:07:53,802 - freqtrade.plot.plotting - INFO - Loading data from 2023-08-09 11:15:00+00:00 to 2023-09-20 15:00:00+00:00
2023-09-21 13:07:53,802 - freqtrade.configuration.timerange - WARNING - Moving start-date by 30 candles to account for startup time.
2023-09-21 13:07:53,802 - freqtrade.plot.plotting - INFO - analyse pair BTC/USDT:USDT
2023-09-21 13:07:53,803 - freqtrade.data.history.idatahandler - WARNING - No history for BTC/USDT:USDT, futures, 8h found. Use `freqtrade download-data` to download the data
2023-09-21 13:07:53,803 - freqtrade.data.dataprovider - WARNING - No data found for (BTC/USDT:USDT, 8h, futures).
2023-09-21 13:07:53,803 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/Users/root/Desktop/source_code/freqtrade/freqtrade/main.py", line 42, in main
    return_code = args['func'](args)
                  ^^^^^^^^^^^^^^^^^^
  File "/Users/root/Desktop/source_code/freqtrade/freqtrade/commands/plot_commands.py", line 24, in start_plot_dataframe
    load_and_plot_trades(config)
  File "/Users/root/Desktop/source_code/freqtrade/freqtrade/plot/plotting.py", line 648, in load_and_plot_trades
    df_analyzed = strategy.analyze_ticker(data, {'pair': pair})
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/root/Desktop/source_code/freqtrade/freqtrade/strategy/interface.py", line 837, in analyze_ticker
    dataframe = self.advise_indicators(dataframe, metadata)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/root/Desktop/source_code/freqtrade/freqtrade/strategy/interface.py", line 1361, in advise_indicators
    dataframe = _create_and_merge_informative_pair(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/root/Desktop/source_code/freqtrade/freqtrade/strategy/informative_decorator.py", line 134, in _create_and_merge_informative_pair
    dataframe = merge_informative_pair(dataframe, inf_dataframe, strategy.timeframe, timeframe,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/root/Desktop/source_code/freqtrade/freqtrade/strategy/strategy_helper.py", line 49, in merge_informative_pair
    informative[date_column] + pd.to_timedelta(minutes_inf, 'm') -
  File "/Users/root/miniconda3/envs/freqtrade/lib/python3.11/site-packages/pandas/core/ops/common.py", line 81, in new_method
    return method(self, other)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/root/miniconda3/envs/freqtrade/lib/python3.11/site-packages/pandas/core/arraylike.py", line 194, in __sub__
    return self._arith_method(other, operator.sub)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/root/miniconda3/envs/freqtrade/lib/python3.11/site-packages/pandas/core/series.py", line 6112, in _arith_method
    return base.IndexOpsMixin._arith_method(self, other, op)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/root/miniconda3/envs/freqtrade/lib/python3.11/site-packages/pandas/core/base.py", line 1348, in _arith_method
    result = ops.arithmetic_op(lvalues, rvalues, op)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/root/miniconda3/envs/freqtrade/lib/python3.11/site-packages/pandas/core/ops/array_ops.py", line 224, in arithmetic_op
    res_values = op(left, right)
                 ^^^^^^^^^^^^^^^
TypeError: unsupported operand type(s) for -: 'numpy.ndarray' and 'Timedelta'
```
- I checked the table of contents. I have the corresponding data files. It seems that the data cannot be found. Is there any example?
<img width="406" alt="image" src="https://github.com/freqtrade/freqtrade/assets/22538559/8a7b2ea9-856f-49fc-bd54-144da82023a2">

**Comment by xmatthias** [comment]
The message is pretty clear - `2023-09-21 13:07:53,803 - freqtrade.data.history.idatahandler - WARNING - No history for BTC/USDT:USDT, futures, 8h found. Use `freqtrade download-data` to download the data`.

The screenshot also shows that you don't seem to have 8h futures data (there's no file for `8h-futures`), confirming the log message.
the 8h data you got is mark / funding rate - which is not the same as futures data (this data is downloaded automatically, as it's required for linquidation / funding rate calculations).

You can use `freqtrade download-data -t 8h` (make sure to specify corresponding timeranges) to download 8h futures data.
in general, you should always download all data you need at once (for example `freqtrade download-data -t 5m 8h`).

**Comment by zhihuba** [comment]
Delete original data. Re-download 
```bash
rm user_data/data
freqtrade download-data --exchange binance -p ETH/USDT:USDT BTC/USDT:USDT TRX/USDT:USDT -t 5m 8h
```

**Comment by xmatthias** [comment]
While i don't really see why you'd delete the data (download-data will only download the data missing) - glad this helped.

**Comment by zhihuba** [comment]
Trying to download directly doesn't work. Delete the directory. Just download again
