### ISSUE TITLE
Failing to put stoploss on exchange for bybit future contract

### ISSUE THREAD

**Issue by Axel-CH** [freqtrade/freqtrade#9210]
## Describe your environment

  * Operating system: linux
  * Python Version: 3.9.18 (`python -V`)
  * CCXT version: 4.0.101 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2023.9-dev-6eed7a342 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
 

## Describe the problem:
The bot is unable to place stoploss on exchange order

*Explain the problem you have encountered*

### Steps to reproduce:

  1. set a custom entry price entry
  2. wait for the fill
  3.once filled the position is open
  4. the bot try to open a stoploss on exchange order but fail
  
### Observed Results:

  * What happened?
  Not stoploss on exchange created
  * What did you expect to happen?
  A stoploss on exchange order created and active

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
2023-09-21 13:32:18,295 - freqtrade.exchange.common - WARNING - create_stoploss() returned exception: "Could not place stoploss order due to BadRequest. Message: bybit {"retCode":10001,"retMsg":"params error: TriggerDirection invalid","result":{},"retExtInfo":{},"time":1695317538174}". Giving up.
2023-09-21 13:32:18,295 - freqtrade.freqtradebot - ERROR - Unable to place a stoploss order on exchange.
Traceback (most recent call last):
  File "/home/user1/dev/pj1/framework-dev/private/prod/freqtrade/freqtrade/exchange/exchange.py", line 1221, in create_stoploss
    order = self._api.create_order(symbol=pair, type=ordertype, side=side,
  File "/home/user1/anaconda3/envs/freqprod/lib/python3.9/site-packages/ccxt/bybit.py", line 3579, in create_order
    response = self.privatePostV5OrderCreate(self.extend(request, params))
  File "/home/user1/anaconda3/envs/freqprod/lib/python3.9/site-packages/ccxt/base/types.py", line 26, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
  File "/home/user1/anaconda3/envs/freqprod/lib/python3.9/site-packages/ccxt/base/exchange.py", line 3051, in request
    return self.fetch2(path, api, method, params, headers, body, config)
  File "/home/user1/anaconda3/envs/freqprod/lib/python3.9/site-packages/ccxt/base/exchange.py", line 3048, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/user1/anaconda3/envs/freqprod/lib/python3.9/site-packages/ccxt/base/exchange.py", line 654, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/user1/anaconda3/envs/freqprod/lib/python3.9/site-packages/ccxt/bybit.py", line 6917, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)
  File "/home/user1/anaconda3/envs/freqprod/lib/python3.9/site-packages/ccxt/base/exchange.py", line 3414, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.BadRequest: bybit {"retCode":10001,"retMsg":"params error: TriggerDirection invalid","result":{},"retExtInfo":{},"time":1695317538174}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user1/dev/pj1/framework-dev/private/prod/freqtrade/freqtrade/freqtradebot.py", line 1185, in create_stoploss_order
    stoploss_order = self.exchange.create_stoploss(
  File "/home/user1/dev/pj1/framework-dev/private/prod/freqtrade/freqtrade/exchange/common.py", line 182, in wrapper
    raise ex
  File "/home/user1/dev/pj1/framework-dev/private/prod/freqtrade/freqtrade/exchange/common.py", line 167, in wrapper
    return f(*args, **kwargs)
  File "/home/user1/dev/pj1/framework-dev/private/prod/freqtrade/freqtrade/exchange/exchange.py", line 1243, in create_stoploss
    raise TemporaryError(
freqtrade.exceptions.TemporaryError: Could not place stoploss order due to BadRequest. Message: bybit {"retCode":10001,"retMsg":"params error: TriggerDirection invalid","result":{},"retExtInfo":{},"time":1695317538174}
  ```

### Working fix:
add this to bybit.py:

```
    def _get_stop_params(self, side: BuySell, ordertype: str, stop_price: float) -> Dict:

        params = self._params.copy()
        params.update({
            "stopLossPrice": stop_price
        })
        return params
```

**Comment by Axel-CH** [comment]
With that fix, I have observed that if the custom entry price order is not filled, and the stop loss is already placed.
If finally the entry signal expire the stoploss order will stay on exchange, with no position or open order.

**Comment by xmatthias** [comment]
you can get the same with `"stop_price_param": "stopLossPrice",` in the ft_has setting (this is actually a setting, not something we need to explicitly code)

That said - can you try (without this fix) with the prior ccxt versin? (4.0.88)? There's been quite some updates around this recently - so it's within possibility that behavior changed in this regards.

**Comment by xmatthias** [comment]
You can't really change this at the moment, as ccxt has some bug in there, causing quite inconsistent behavior.

https://github.com/ccxt/ccxt/issues/19362

**Comment by Axel-CH** [comment]
Thank you @xmatthias I will keep an eye on your issue

**Comment by xmatthias** [comment]
For now, you'll be fine with develop - since i've downgraded ccxt to the pre-v5 update (#9213 ).

**Comment by Axel-CH** [comment]
Thank you for your help 👍🏽
