### ISSUE TITLE
After update, I can't use `freqtrade trade` with freqai strategies

### ISSUE THREAD

**Issue by BuddhiLW** [freqtrade/freqtrade#9239]
## Describe your environment

  * Operating system: Ubuntu
  * Python Version: Python 3.11.4 (`python -V`)
  * CCXT version: ccxt==3.1.44 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2023.8 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Describe the problem:

After updating freqtrade today, I can't run `freqtrade trade --strategy FreqaiExampleHyridStrategy --strategy-path freqtrade/templates    --freqaimodel CatboostClassifier --config config_examples/config_freqai.example.json`.

It throws an error - see below, for the log.

### Steps to reproduce:

  1. Update freqtrade.
  2. Start the environment.
  3. Try to run the freqtrade example, which uses `freqai`.
  
### Relevant code exceptions or logs

```bash
freqtrade trade --strategy FreqaiExampleHyridStrategy --strategy-path freqtrade/templates    --freqaimodel CatboostClassifier --config config_examples/config_freqai.example.json
```

```bash
2023-09-28 18:12:08,014 - freqtrade - INFO - freqtrade 2023.8
2023-09-28 18:12:08,089 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/lw/PP/freqtrade/freqtrade/main.py", line 42, in main
    return_code = args['func'](args)
                  ^^^^^^^^^^^^^^^^^^
  File "/home/lw/PP/freqtrade/freqtrade/commands/trade_commands.py", line 14, in start_trading
    from freqtrade.worker import Worker
  File "/home/lw/PP/freqtrade/freqtrade/worker.py", line 18, in <module>
    from freqtrade.freqtradebot import FreqtradeBot
  File "/home/lw/PP/freqtrade/freqtrade/freqtradebot.py", line 35, in <module>
    from freqtrade.rpc.external_message_consumer import ExternalMessageConsumer
  File "/home/lw/PP/freqtrade/freqtrade/rpc/external_message_consumer.py", line 20, in <module>
    from freqtrade.rpc.api_server.ws.channel import WebSocketChannel, create_channel
  File "/home/lw/PP/freqtrade/freqtrade/rpc/api_server/__init__.py", line 1, in <module>
    from .webserver import ApiServer  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lw/PP/freqtrade/freqtrade/rpc/api_server/webserver.py", line 15, in <module>
    from freqtrade.rpc.api_server.ws.message_stream import MessageStream
  File "/home/lw/PP/freqtrade/freqtrade/rpc/api_server/ws/__init__.py", line 4, in <module>
    from freqtrade.rpc.api_server.ws.serializer import HybridJSONWebSocketSerializer  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lw/PP/freqtrade/freqtrade/rpc/api_server/ws/serializer.py", line 11, in <module>
    from freqtrade.rpc.api_server.ws_schemas import WSMessageSchemaType
  File "/home/lw/PP/freqtrade/freqtrade/rpc/api_server/ws_schemas.py", line 57, in <module>
    class WSAnalyzedDFMessage(WSMessageSchema):
  File "/home/lw/PP/freqtrade/freqtrade/rpc/api_server/ws_schemas.py", line 58, in WSAnalyzedDFMessage
    class AnalyzedDFData(BaseArbitraryModel):
  File "pydantic/main.py", line 197, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 557, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 831, in pydantic.fields.ModelField.populate_validators
  File "pydantic/validators.py", line 765, in find_validators
RuntimeError: no validator found for <class 'pandas.core.frame.DataFrame'>, see `arbitrary_types_allowed` in Config
  ```

**Comment by BuddhiLW** [comment]
I used `./setup.sh -i`, and using the new environment, everything worked fine.
