### ISSUE TITLE
custom_entry_price works good until...None?

### ISSUE THREAD

**Issue by sandervdhave** [freqtrade/freqtrade#9323]
Operating system: Ventura 13.4.1
Python Version: 3.11
CCXT version: 3.1.44
Freqtrade Version: freqtrade docker-2023.6.dev-c5510491

In Dry-Run i can see that my order gets filled way lower or higher than the close of the signal_candle.  I get problems during the trade because is i calculate my stoploss and takeprofit from the value of the close of the signal_candle. In a bad situation my trade even gets filled below the calculated stoploss.

So now i want to set my entry_price to the last_candle 'close' (signal_candle). I do this with the code below and for a lot of trades this will work.

```
def custom_entry_price(self, pair: str, current_time: datetime, proposed_rate: float,
                           entry_tag: Optional[str], side: str, **kwargs) -> float:

        # get dataframe
        dataframe, _ = self.dp.get_analyzed_dataframe(pair=pair, timeframe=self.timeframe)
        # get the last candle
        last_candle = dataframe.iloc[-1].squeeze()
        previous_candle = dataframe.iloc[-2].squeeze()

        new_entryprice = None  # Set a default value

        if last_candle['enter_long'] == 1 and previous_candle['enter_long'] != 1:
            logger.info(f">> LONG Last_candle CLOSE: {last_candle['close']}")
            new_entryprice = last_candle['close']
        
        elif last_candle['enter_short'] ==1 and previous_candle['enter_short'] != 1:
            logger.info(f">> SHORT Last_candle CLOSE: {last_candle['close']}")
            new_entryprice = last_candle['close']

        print (new_entryprice)
        return new_entryprice
```

But i get a error that i don't understand:

```
2023-10-19 19:52:33,111 - freqtrade.optimize.backtesting - INFO - Backtesting with data from 2023-01-01 00:00:00 up to 2023-10-15 21:10:00 (287 days).
2023-10-19 19:52:37,263 - ClucMay2 - INFO - >> SHORT Last_candle CLOSE: 11.64
11.64
2023-10-19 19:52:37,310 - ClucMay2 - INFO - >> SHORT Last_candle CLOSE: 13.32
13.32
2023-10-19 19:52:37,341 - ClucMay2 - INFO - >> LONG Last_candle CLOSE: 40.25
40.25
2023-10-19 19:52:37,384 - ClucMay2 - INFO - >> SHORT Last_candle CLOSE: 1.2555
1.2555
2023-10-19 19:52:37,407 - ClucMay2 - INFO - >> SHORT Last_candle CLOSE: 3.38
3.38
2023-10-19 19:52:37,528 - ClucMay2 - INFO - >> SHORT Last_candle CLOSE: 6.955
6.955
2023-10-19 19:52:37,562 - ClucMay2 - INFO - >> SHORT Last_candle CLOSE: 19.66
19.66
2023-10-19 19:52:37,593 - ClucMay2 - INFO - >> SHORT Last_candle CLOSE: 1.5575
1.5575
2023-10-19 19:52:37,614 - ClucMay2 - INFO - >> SHORT Last_candle CLOSE: 1.125
1.125
2023-10-19 19:52:37,626 - ClucMay2 - INFO - >> SHORT Last_candle CLOSE: 7.075
7.075
2023-10-19 19:52:37,704 - ClucMay2 - INFO - >> SHORT Last_candle CLOSE: 1.705
1.705
2023-10-19 19:52:37,706 - ClucMay2 - INFO - >> SHORT Last_candle CLOSE: 1.1725
1.1725
2023-10-19 19:52:37,715 - ClucMay2 - INFO - >> SHORT Last_candle CLOSE: 14.835
14.835
2023-10-19 19:52:37,722 - ClucMay2 - INFO - >> SHORT Last_candle CLOSE: 21.365
21.365
2023-10-19 19:52:37,733 - ClucMay2 - INFO - >> SHORT Last_candle CLOSE: 4.641
4.641
2023-10-19 19:52:37,739 - ClucMay2 - INFO - >> SHORT Last_candle CLOSE: 4.135
4.135
2023-10-19 19:52:37,772 - ClucMay2 - INFO - >> SHORT Last_candle CLOSE: 1.327
1.327
2023-10-19 19:52:37,959 - ClucMay2 - INFO - >> SHORT Last_candle CLOSE: 4.605
4.605
2023-10-19 19:52:37,962 - ClucMay2 - INFO - >> SHORT Last_candle CLOSE: 1.365
1.365
2023-10-19 19:52:37,968 - ClucMay2 - INFO - >> SHORT Last_candle CLOSE: 5.285
5.285
2023-10-19 19:52:38,051 - ClucMay2 - INFO - >> SHORT Last_candle CLOSE: 0.462
0.462
2023-10-19 19:52:38,076 - ClucMay2 - INFO - >> LONG Last_candle CLOSE: 12.94
12.94
2023-10-19 19:52:38,078 - ClucMay2 - INFO - >> LONG Last_candle CLOSE: 4.0445
4.0445
2023-10-19 19:52:38,078 - ClucMay2 - INFO - >> LONG Last_candle CLOSE: 1.216
1.216
2023-10-19 19:52:38,078 - ClucMay2 - INFO - >> LONG Last_candle CLOSE: 7.17
7.17
2023-10-19 19:52:38,079 - ClucMay2 - INFO - >> LONG Last_candle CLOSE: 4.827
4.827
2023-10-19 19:52:38,080 - ClucMay2 - INFO - >> LONG Last_candle CLOSE: 3.66
3.66
2023-10-19 19:52:38,081 - ClucMay2 - INFO - >> LONG Last_candle CLOSE: 1.8965
1.8965
2023-10-19 19:52:38,112 - ClucMay2 - INFO - >> SHORT Last_candle CLOSE: 5.695
5.695
2023-10-19 19:52:38,129 - ClucMay2 - INFO - >> SHORT Last_candle CLOSE: 1.405
1.405
2023-10-19 19:52:38,152 - ClucMay2 - INFO - >> SHORT Last_candle CLOSE: 5.042
5.042
2023-10-19 19:52:38,270 - ClucMay2 - INFO - >> LONG Last_candle CLOSE: 41.65
41.65
2023-10-19 19:52:38,275 - ClucMay2 - INFO - >> SHORT Last_candle CLOSE: 12.905
12.905
2023-10-19 19:52:38,279 - ClucMay2 - INFO - >> SHORT Last_candle CLOSE: 13.92
13.92
2023-10-19 19:52:38,285 - ClucMay2 - INFO - >> SHORT Last_candle CLOSE: 5.165
5.165
2023-10-19 19:52:38,305 - ClucMay2 - INFO - >> SHORT Last_candle CLOSE: 15.635
15.635
2023-10-19 19:52:38,310 - ClucMay2 - INFO - >> SHORT Last_candle CLOSE: 1395.1
1395.1
2023-10-19 19:52:38,319 - ClucMay2 - INFO - >> SHORT Last_candle CLOSE: 1.336
1.336
2023-10-19 19:52:38,321 - ClucMay2 - INFO - >> SHORT Last_candle CLOSE: 7.91
7.91
None
2023-10-19 19:52:38,323 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 42, in main
    return_code = args['func'](args)
                  ^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 58, in start_backtesting
    backtesting.start()
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 1357, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 1291, in backtest_one_strategy
    results = self.backtest(
              ^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 1234, in backtest
    open_trade_count_start = self.backtest_loop(
                             ^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 1110, in backtest_loop
    trade = self._enter_trade(pair, row, trade_dir)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 801, in _enter_trade
    propose_rate, stake_amount, leverage, min_stake_amount = self.get_valid_price_and_stake(
                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 730, in get_valid_price_and_stake
    propose_rate = price_to_precision(new_rate, price_precision,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/exchange/exchange_utils.py", line 276, in price_to_precision
    ticks = price / price_precision
            ~~~~~~^~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'

```

You can see with the Logger and Print the custom_entry_price is working good with a few trades. But it seems that the propose_rate being passed to this function is None at some point during the backtesting. This could be due to a situation where new_rate (which i am using to set propose_rate in my custom_entry_price function) is not being correctly assigned a value.

But why is this this not working in one trade, when the other trades do work? Why is the None being passed?

**Comment by xmatthias** [comment]
well your logic clearly allows the return of None (it's quite easy to fall through your if logic - for every entry signal that's not the first of a series of sticking signals in either direction).
This could happen for example if your trade slots have been filled - or if you had colliding (and therefore ignored) signals - with one of these disappearing thereafter.

instead of returning (or assigning) None to new_entryprice, you should instead assign proposed_rate - so if your logic doesn't work - you'll not end up with a completely wrong price.

in trade mode (and from now on also in backtesting) - returning None will be interpreted as "proposed rate was fine" - though it's still technically a strategy bug, returning a wrong result by returning None.

> So now i want to set my entry_price to the last_candle 'close' (signal_candle). I do this with the code below and for a lot of trades this will work.

I've explained this (i think twice) already - you may be able to do this in backtesting - but in live, it will either result in timeouts - or in orders that anyway fill at a different price, as the prior close is across the spread (you buy for 100, but current best ask is 95 - the order will fill at 95).

**Comment by sandervdhave** [comment]
Thanks for your fast reply!

The proposed_rate fixed the error. That's a good thing!

> I've explained this (i think twice) already - you may be able to do this in backtesting - but in live, it will either result in timeouts - or in orders that anyway fill at a different price, as the prior close is across the spread (you buy for 100, but current best ask is 95 - the order will fill at 95).

I was thinking the custom_entry_price would work like a limit order. If i but for 100, but the current best ask is 95 - the order will not fill (timeouts). I'd rather have a timeout than a entry_price below the stoploss. Does custom_entry_price not work like that?

**Comment by xmatthias** [comment]
in backtesting it will (unless your price is outside of the candle).

but what you're trying to do is force the market to behave the way you like - not the way it actually behaves.

it's basic market understanding, really.
Take the following orderbook (shamelessly copied from our documentation)

```
...
103
102
101  # ask
-------------Current spread
99   # bid
98
97
...
```


a buy order placed at a limit price of 100$ will be placed and will wait for the best ask (to come "down" to your rate).
It's in the middle of the spread - so it's quite likely that it's actually being filled (not guaranteed, mind you).

If you place the order at 98$ - you're below the best bid - but it's a buy order - so it'll behave the same and wait for the ask (the seller with the best price) to "come down" to your price (that's against the will of the seller - which aims to sell at a higher price).
essentially, you're in line, in line behind the guy with the 99$ buy order, potentially in line behind someone else occupying the 98$ spot - but once it's your turn, you'll be filled _before_ the guy with the 97$ order.

this can have the following reasons:
* the buyer at 99 cancels his order
* a seller sells for 99 (or a market order) with enough volume to remove the 99$ volume - comming down to you

If you however place your buy order at 103$ - then you're crossing the spread.
Your buy order limit is above the spread, and will have an immediate seller to be matched with.

You can't however "pick and choose" the seller and say "i'll take the one at 103$" - you have to follow the sequence, and will be filled by the seller with the lowest price first, which in the above case, is 101$.
Now depending on the volume - you may be "eating" into the orderbook, wiping out the first level, maybe also the 2nd - so your average rate may be anything between 101$ to 103$.

If volume is very light - your order will stop filling at 103 (your limit order specified that that's the worst price acceptable for you), and potentially end up partially filled.

the market won't cares that you would like to buy at 103$ - the price is in your favor, so you've been filled.

From a fee perspective, this will usually behave like a market order, and exchanges often refer to this as "marketable limit order".
But it's a market fact you can't really change by using freqtrade.

---

I'd strongly suggest to try this manually on an exchange to get a better understanding.
On most exchanges, you'll even see the location of your order in the orderbook (unless it fills immediately).

**Comment by sandervdhave** [comment]
Thanks for your explanation. I know the workings of a orderbook, but your step by step explanation is really clear!

If i have your orderbook example and my custom_stake_order proposed rate is passing a $98. Then i will have to wait in line before the $98 and $99 are fully filled for other people. Am i correct? As long as my entry price is at $98 i am ok with a few trades that will not be filled. As long as there are enough trades that are being filled.

This is the experiment i was looking for. I am going to test this for my strategy. Thanks again!
