### ISSUE TITLE
dry run, Process died ...

### ISSUE THREAD

**Issue by yaotian** [freqtrade/freqtrade#934]
## Step 1: Have you search for this issue before posting it?
yes
## Step 2: Describe your environment

  * Python Version: _____ (`python -V`):3
  * CCXT version: _____ (`pip freeze | grep ccxt`):1.14.224
  * Branch: Develop
  * Last Commit ID: _____ (`git log --format="%H" -n 1`)
  
## Step 3: Describe the problem:
dry run, when making order, the process died.

### Steps to reproduce:

  1. dry run_____
  2. when order was made, the issue will happen _____
  3. _____
  
### Relevant code exceptions or logs:

  ```
  // paste your log here
2018-06-20 16:28:16,966 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "./freqtrade/main.py", line 48, in main
    state = freqtrade.worker(old_state=state)
  File "/home/yaotian/app/freqtrade/freqtrade/freqtradebot.py", line 112, in worker
    nb_assets=nb_assets)
  File "/home/yaotian/app/freqtrade/freqtrade/freqtradebot.py", line 124, in _throttle
    result = func(*args, **kwargs)
  File "/home/yaotian/app/freqtrade/freqtrade/freqtradebot.py", line 164, in _process
    self.check_handle_timedout(self.config['unfilledtimeout'])
  File "/home/yaotian/app/freqtrade/freqtrade/freqtradebot.py", line 452, in check_handle_timedout
    order = exchange.get_order(trade.open_order_id, trade.pair)
  File "/home/yaotian/app/freqtrade/freqtrade/exchange/__init__.py", line 37, in wrapper
    return f(*args, **kwargs)
  File "/home/yaotian/app/freqtrade/freqtrade/exchange/__init__.py", line 347, in get_order
    order = _DRY_RUN_OPEN_ORDERS[order_id]
KeyError: 'dry_run_sell_278629'
2018-06-20 16:28:16,967 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: *Status:* `Process died ...`
  ```

**Comment by xmatthias** [comment]
this will be very hard to verify / recreate - seems like something in dry-run went wrong (it did not find a dry-run trade anymore).

currently would not know how to recreate this problem so we can work on a fix

**Comment by shusso** [comment]
feel free to re open if still persists
