### ISSUE TITLE
get error `okx {"msg":"Timestamp request expired","code":"50102"}` when run the docker

### ISSUE THREAD

**Issue by Mingzefei** [freqtrade/freqtrade#9340]
## Describe your environment

  * Operating system: WSL2
  * Python Version: python3.11
  * CCXT version: 4.0.105
  * Freqtrade Version: 2023.9
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

### Steps to reproduce:

  1. run the docker step by step from [Using Freqtrade with Docker](https://www.freqtrade.io/en/stable/docker_quickstart/#using-freqtrade-with-docker).
  2. set `"dry_run": false`, exchange key and others in the config.
  
### Observed Results:

The container does not work.

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
2023-10-25 13:54:42 freqtrade  | 2023-10-25 05:54:42,491 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2023-10-25 13:54:42 freqtrade  | 2023-10-25 05:54:42,494 - freqtrade.exchange.exchange - INFO - Using CCXT 4.0.105
2023-10-25 13:54:42 freqtrade  | 2023-10-25 05:54:42,494 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}}
2023-10-25 13:54:42 freqtrade  | 2023-10-25 05:54:42,497 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}}
2023-10-25 13:54:42 freqtrade  | 2023-10-25 05:54:42,501 - freqtrade.exchange.exchange - INFO - Using Exchange "OKX"
2023-10-25 13:54:43 freqtrade  | 2023-10-25 05:54:43,074 - freqtrade.exchange.exchange - ERROR - Unable to initialize markets.
2023-10-25 13:54:43 freqtrade  | Traceback (most recent call last):
2023-10-25 13:54:43 freqtrade  |   File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/base/exchange.py", line 610, in fetch
2023-10-25 13:54:43 freqtrade  |     response.raise_for_status()
2023-10-25 13:54:43 freqtrade  |   File "/home/ftuser/.local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
2023-10-25 13:54:43 freqtrade  |     raise HTTPError(http_error_msg, response=self)
2023-10-25 13:54:43 freqtrade  | requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://www.okx.com/api/v5/asset/currencies
2023-10-25 13:54:43 freqtrade  | 
2023-10-25 13:54:43 freqtrade  | During handling of the above exception, another exception occurred:
2023-10-25 13:54:43 freqtrade  | 
2023-10-25 13:54:43 freqtrade  | Traceback (most recent call last):
2023-10-25 13:54:43 freqtrade  |   File "/freqtrade/freqtrade/exchange/exchange.py", line 480, in _load_markets
2023-10-25 13:54:43 freqtrade  |     self._markets = self._api.load_markets(params={})
2023-10-25 13:54:43 freqtrade  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-25 13:54:43 freqtrade  |   File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/base/exchange.py", line 1443, in load_markets
2023-10-25 13:54:43 freqtrade  |     currencies = self.fetch_currencies()
2023-10-25 13:54:43 freqtrade  |                  ^^^^^^^^^^^^^^^^^^^^^^^
2023-10-25 13:54:43 freqtrade  |   File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/okx.py", line 1494, in fetch_currencies
2023-10-25 13:54:43 freqtrade  |     response = self.privateGetAssetCurrencies(params)
2023-10-25 13:54:43 freqtrade  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-25 13:54:43 freqtrade  |   File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/base/types.py", line 26, in unbound_method
2023-10-25 13:54:43 freqtrade  |     return _self.request(self.path, self.api, self.method, params, config=self.config)
2023-10-25 13:54:43 freqtrade  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-25 13:54:43 freqtrade  |   File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/base/exchange.py", line 3051, in request
2023-10-25 13:54:43 freqtrade  |     return self.fetch2(path, api, method, params, headers, body, config)
2023-10-25 13:54:43 freqtrade  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-25 13:54:43 freqtrade  |   File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/base/exchange.py", line 3048, in fetch2
2023-10-25 13:54:43 freqtrade  |     return self.fetch(request['url'], request['method'], request['headers'], request['body'])
2023-10-25 13:54:43 freqtrade  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-25 13:54:43 freqtrade  |   File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/base/exchange.py", line 626, in fetch
2023-10-25 13:54:43 freqtrade  |     skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
2023-10-25 13:54:43 freqtrade  |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-25 13:54:43 freqtrade  |   File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/okx.py", line 6357, in handle_errors
2023-10-25 13:54:43 freqtrade  |     self.throw_exactly_matched_exception(self.exceptions['exact'], code, feedback)
2023-10-25 13:54:43 freqtrade  |   File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/base/exchange.py", line 3414, in throw_exactly_matched_exception
2023-10-25 13:54:43 freqtrade  |     raise exact[string](message)
2023-10-25 13:54:43 freqtrade  | ccxt.base.errors.InvalidNonce: okx {"msg":"Timestamp request expired","code":"50102"}
2023-10-25 13:54:43 freqtrade  | 2023-10-25 05:54:43,082 - freqtrade.commands.trade_commands - ERROR - Could not load markets, therefore cannot start. Please investigate the above error for more details.
2023-10-25 13:54:43 freqtrade  | 2023-10-25 05:54:43,082 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
2023-10-25 13:54:43 freqtrade  | Traceback (most recent call last):
2023-10-25 13:54:43 freqtrade  |   File "/freqtrade/freqtrade/commands/trade_commands.py", line 24, in start_trading
2023-10-25 13:54:43 freqtrade  |     worker = Worker(args)
2023-10-25 13:54:43 freqtrade  |              ^^^^^^^^^^^^
2023-10-25 13:54:43 freqtrade  |   File "/freqtrade/freqtrade/worker.py", line 37, in __init__
2023-10-25 13:54:43 freqtrade  |     self._init(False)
2023-10-25 13:54:43 freqtrade  |   File "/freqtrade/freqtrade/worker.py", line 53, in _init
2023-10-25 13:54:43 freqtrade  |     self.freqtrade = FreqtradeBot(self._config)
2023-10-25 13:54:43 freqtrade  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-25 13:54:43 freqtrade  |   File "/freqtrade/freqtrade/freqtradebot.py", line 76, in __init__
2023-10-25 13:54:43 freqtrade  |     self.exchange = ExchangeResolver.load_exchange(
2023-10-25 13:54:43 freqtrade  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-25 13:54:43 freqtrade  |   File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 37, in load_exchange
2023-10-25 13:54:43 freqtrade  |     exchange = ExchangeResolver._load_exchange(
2023-10-25 13:54:43 freqtrade  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-25 13:54:43 freqtrade  |   File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 64, in _load_exchange
2023-10-25 13:54:43 freqtrade  |     exchange = ex_class(**kwargs)
2023-10-25 13:54:43 freqtrade  |                ^^^^^^^^^^^^^^^^^^
2023-10-25 13:54:43 freqtrade  |   File "/freqtrade/freqtrade/exchange/exchange.py", line 187, in __init__
2023-10-25 13:54:43 freqtrade  |     self.validate_config(config)
2023-10-25 13:54:43 freqtrade  |   File "/freqtrade/freqtrade/exchange/exchange.py", line 225, in validate_config
2023-10-25 13:54:43 freqtrade  |     self.validate_stakecurrency(config['stake_currency'])
2023-10-25 13:54:43 freqtrade  |   File "/freqtrade/freqtrade/exchange/exchange.py", line 514, in validate_stakecurrency
2023-10-25 13:54:43 freqtrade  |     raise OperationalException(
2023-10-25 13:54:43 freqtrade  | freqtrade.exceptions.OperationalException: Could not load markets, therefore cannot start. Please investigate the above error for more details.
  ```

**Comment by Mingzefei** [comment]
I find a similar situation on stackoverflow, but I don't know if freqtrade uses the same code as him.
https://stackoverflow.com/questions/76623046/timestamp-request-expired-code-50102

**Comment by stash86** [comment]
Try syncing your wsl clock

**Comment by Mingzefei** [comment]
@stash86  I did it, but it returns the same error.
```
PS C:\Users\30577> date ; wsl date

2023年10月25日 15:42:03
Wed 25 Oct 2023 03:42:03 PM CST
```

**Comment by xmatthias** [comment]
it's clearly a "timestamp in Docker / wsl" problem ... 
How are you configuring the WSL clock to sync? (this is not "sync your windows clock" - it's a separate step that will be required for this to work properly).

Obviously if the time is "incorrect" - then the exchange will reject (authenticated) requests - as that's a sign of impersonation (or request replay).

**Comment by Mingzefei** [comment]
Thanks for your reply!
I figure it out. At the begin, I only synced WSL2 clock with Win10, but the timestamp of Win10 was incorrect. So it remained the "Timestamp request expired" error. After I checked the Win10 clock and synced it, docker run without error.
