### ISSUE TITLE
Error when creating a Trailing Stop Loss on Binance API

### ISSUE THREAD

**Issue by escanoro** [freqtrade/freqtrade#9342]
## Describe your environment

  * Operating system: Linux Ubuntu 22
  * Python Version: N/A  i'm using Last Docker Image
  * CCXT version: i'm using Last Docker Image
  * Freqtrade Version: freqtrade 2023.8 (Via the Stable Docker Image)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

  1. Run a Strategy using the Binance Exchange (Live not Dry)
  2. The Strategy uses Trailing Stop
  
  
### Observed Results:

  * Logs show an error looks like the Bot is not able to place a Trailing Stop
  * Expectations: No erros, a Trailing Stop/Order is created on the Exchange

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  File "/freqtrade/freqtrade/exchange/exchange.py", line 1237, in create_stoploss
freqtrade-sar_v1_with_ma_live  |     raise TemporaryError(
freqtrade-sar_v1_with_ma_live  | freqtrade.exceptions.TemporaryError: Could not place stoploss order due to AuthenticationError. Message: binance {"code":-4013,"msg":"Price less than min price."}
freqtrade-sar_v1_with_ma_live  | 2023-10-26 17:24:59,192 - freqtrade.exchange.common - WARNING - create_stoploss() returned exception: "Could not place stoploss order due to AuthenticationError. Message: binance {"code":-4013,"msg":"Price less than min price."}". Giving up.
freqtrade-sar_v1_with_ma_live  | 2023-10-26 17:24:59,192 - freqtrade.freqtradebot - ERROR - Unable to place a stoploss order on exchange.
freqtrade-sar_v1_with_ma_live  | Traceback (most recent call last):
freqtrade-sar_v1_with_ma_live  |   File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/base/exchange.py", line 600, in fetch
freqtrade-sar_v1_with_ma_live  |     response.raise_for_status()
freqtrade-sar_v1_with_ma_live  |   File "/home/ftuser/.local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
freqtrade-sar_v1_with_ma_live  |     raise HTTPError(http_error_msg, response=self)
freqtrade-sar_v1_with_ma_live  | requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://fapi.binance.com/fapi/v1/order
freqtrade-sar_v1_with_ma_live  | 
freqtrade-sar_v1_with_ma_live  | During handling of the above exception, another exception occurred:
freqtrade-sar_v1_with_ma_live  | 
freqtrade-sar_v1_with_ma_live  | Traceback (most recent call last):
freqtrade-sar_v1_with_ma_live  |   File "/freqtrade/freqtrade/exchange/exchange.py", line 1215, in create_stoploss
freqtrade-sar_v1_with_ma_live  |     order = self._api.create_order(symbol=pair, type=ordertype, side=side,
freqtrade-sar_v1_with_ma_live  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
freqtrade-sar_v1_with_ma_live  |   File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/binance.py", line 4095, in create_order
freqtrade-sar_v1_with_ma_live  |     response = getattr(self, method)(request)
freqtrade-sar_v1_with_ma_live  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
freqtrade-sar_v1_with_ma_live  |   File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/base/types.py", line 26, in unbound_method
freqtrade-sar_v1_with_ma_live  |     return _self.request(self.path, self.api, self.method, params, config=self.config)
freqtrade-sar_v1_with_ma_live  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
freqtrade-sar_v1_with_ma_live  |   File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/binance.py", line 7493, in request
freqtrade-sar_v1_with_ma_live  |     response = self.fetch2(path, api, method, params, headers, body, config)
freqtrade-sar_v1_with_ma_live  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
freqtrade-sar_v1_with_ma_live  |   File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/base/exchange.py", line 3016, in fetch2
freqtrade-sar_v1_with_ma_live  |     return self.fetch(request['url'], request['method'], request['headers'], request['body'])
freqtrade-sar_v1_with_ma_live  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
freqtrade-sar_v1_with_ma_live  |   File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/base/exchange.py", line 616, in fetch
freqtrade-sar_v1_with_ma_live  |     skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  ```

**Comment by escanoro** [comment]
Just to mention something: The bot was active previously, i can see on the Exchange that ~~a Stop loss~~ an ROI order has been created after the first trade (Static Stop Loss created after each trade)

The Bot Server crashed due to memory issues

Now, i have started the bot (Restarted to be precise)

So i don't know if this is related or if this is a temporary issue

(I have many trades active when restarting the bot)

**Comment by xmatthias** [comment]
are you sure that the tracelog is complete?

also, please post a few lines prior to the exception of the log - that usually helps, too.

---

It should also be noted that 2023.8 is not "last docker image" - but is what debian would call "oldstable" - but is basically 1 version behind.
assuming that's not intentional, you might need to do `docker compose pull` to update your image (followed by the regular `up` command) to get the latest version.

**Comment by escanoro** [comment]
Looks like i understood the issue, i will try to fix it and report back in few days or weeks.

Binance Perpetual futures market has some trading rules, where Limit orders price value cannot have an X percentage gap comparing to the current price.

https://www.binance.com/en/futures/trading-rules

I think that the Stop Loss order made by freqtrade is a Limit order, and since it's lower than (current price - 5%) in case of long or higher than (current price + 5%) in case of short, it fails.

Is the Stop Loss order (Stoploss in Exchange) is a Limit Order?

I suppose yes.

**Comment by xmatthias** [comment]
Fthe effective order type does depend on your configuration. 
binance futures does support both limit and market stop orders.

I don't think the 5% rule applies to stoploss orders though - as it would only be convered once your trigger price is reached. 
If your trigger price would have to be within 5% - then it would no longer be an effective stoploss.

As such, i don't really see what you're "fixing".

That said - there's nothing to conclude from the logs above (they're incomplete and missing context).
Without the full exception trace and context (as requested above) - i'll have to conclude this issue as invalid.

**Comment by escanoro** [comment]
I will post the complete logs soon

**Comment by escanoro** [comment]
Here the complete log (It's circular):

 ```
freqtrade.exceptions.TemporaryError: Could not place stoploss order due to AuthenticationError. Message: binance {"code":-4013,"msg":"Price less than min price."}
2023-10-25 10:05:09,842 - uvicorn.access - INFO - 63.147.23.14:61742 - "GET /api/v1/status HTTP/1.1" 200
2023-10-25 10:05:09,844 - uvicorn.access - INFO - 63.147.23.14:61742  - "GET /api/v1/ping HTTP/1.1" 200
2023-10-25 10:05:09,975 - uvicorn.access - INFO - 63.147.23.14:61742  - "GET /api/v1/locks HTTP/1.1" 200
2023-10-25 10:05:14,490 - freqtrade.exchange.common - WARNING - create_stoploss() returned exception: "Could not place stoploss order due to AuthenticationError. Message: binance {"code":-4013,"msg":"Price less than min price."}". Giving up.
2023-10-25 10:05:14,490 - freqtrade.freqtradebot - ERROR - Unable to place a stoploss order on exchange.
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/base/exchange.py", line 600, in fetch
    response.raise_for_status()
  File "/home/ftuser/.local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://fapi.binance.com/fapi/v1/order

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/exchange.py", line 1215, in create_stoploss
    order = self._api.create_order(symbol=pair, type=ordertype, side=side,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/binance.py", line 4095, in create_order
    response = getattr(self, method)(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/base/types.py", line 26, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/binance.py", line 7493, in request
    response = self.fetch2(path, api, method, params, headers, body, config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/base/exchange.py", line 3016, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/base/exchange.py", line 616, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/binance.py", line 7470, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
  File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/base/exchange.py", line 3382, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.AuthenticationError: binance {"code":-4013,"msg":"Price less than min price."}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/freqtradebot.py", line 1176, in create_stoploss_order
    stoploss_order = self.exchange.create_stoploss(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/exchange/common.py", line 182, in wrapper
    raise ex
  File "/freqtrade/freqtrade/exchange/common.py", line 167, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/exchange/exchange.py", line 1237, in create_stoploss
    raise TemporaryError(
freqtrade.exceptions.TemporaryError: Could not place stoploss order due to AuthenticationError. Message: binance {"code":-4013,"msg":"Price less than min price."}
2023-10-25 10:05:17,880 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2023.8', state='RUNNING'
2023-10-25 10:05:19,493 - freqtrade.exchange.common - WARNING - create_stoploss() returned exception: "Could not place stoploss order due to AuthenticationError. Message: binance {"code":-4013,"msg":"Price less than min price."}". Giving up.
 ```

**Comment by xmatthias** [comment]
well what's your stoploss at (at what value would the bot try to place it)?

based on the exchange docs - this error means that your trigger price is below the minimum allowed price.
This can happen for example if you use an exagerated stoploss value - while still using stoploss on exchange.

As we don't know the price, i'll assume BTC for now (just to make an example).
BTC's price is currently "around" 30.000$ (depending on when you look at).
The limit you're surpassing is defined in the "load_markets" structure - and for BTC/USDT:USDT - it's currently `'price': {'min': 556.8, 'max': 4529764.0},`.
Trying to place a stoploss order at below 550$ would therefore fail.

As this seems to be a repeating error on an open trade, please provide the output of the following command for the affected trade:
`freqtrade show-trades --db-url sqlite:///<trades.sqlite> --print-json --trade-ids <tradeid>` 
Please use a "details block" to keep the issue itself kindof readable (see below for details on how to do that). 

<details>
<summary>Expand to see how to do details blocks</summary>

```
<details>
<summary>Expand full </summary>
(wrap in tripple ticks `)
Trades output ...
</details>
```
</details>

this should contain the details needed - including the pair and price it aims to place a stoploss at..

**Comment by xmatthias** [comment]
Closing this as without the requested details, there's nothing for us to analyze.

Feel free to comment below with the details asked above if you're still encountering this problem, so we can reopen this and actually look at it in detail.
