### ISSUE TITLE
assert precision is not None

### ISSUE THREAD

**Issue by Johan1974** [freqtrade/freqtrade#9430]
Hello,

I have an issue with the freqtrade bot that i can not seem to solve. I keep getting the blow error with a strategy that used to work fine before.  The error is givng me an assertion error , see full logg below.

## Describe your environment

  * Operating system: Linux
  * Python Version: Python 3.11.6
  * CCXT version: ccxt==4.1.53
  * Freqtrade Version: freqtrade docker-2023.11-dev-835cb548
  * Exchange Bitvavo
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

When running my bot and it arrives at an exit point i get an assertion error. I am not sure if this is a freqtrade issue or an issue with bitvavo. They had some kind of network error last week. I did ask them too if something has changed on their side maybe.

''
### Relevant code exceptions or logs

```
2023-11-15 15:54:05,464 - freqtrade.freqtradebot - INFO - Exit for ANT/EUR detected. Reason: exit_signal
2023-11-15 15:54:05,791 - freqtrade.wallets - INFO - Wallets synced.
2023-11-15 15:54:05,792 - freqtrade.commands.trade_commands - ERROR - 
2023-11-15 15:54:05,793 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 25, in start_trading
    worker.run()
  File "/freqtrade/freqtrade/worker.py", line 75, in run
    state = self._worker(old_state=state)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/worker.py", line 116, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs,
  File "/freqtrade/freqtrade/worker.py", line 147, in _throttle
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/worker.py", line 180, in _process_running
    self.freqtrade.process()
  File "/freqtrade/freqtrade/freqtradebot.py", line 240, in process
    self.exit_positions(trades)
  File "/freqtrade/freqtrade/freqtradebot.py", line 1109, in exit_positions
    if not trade.has_open_orders and trade.is_open and self.handle_trade(trade):
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/freqtradebot.py", line 1150, in handle_trade
    if self._check_and_execute_exit(trade, exit_rate, enter, exit_, exit_tag):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/freqtradebot.py", line 1174, in _check_and_execute_exit
    exited = self.execute_trade_exit(trade, exit_rate, should_exit, exit_tag=exit_tag1)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/freqtradebot.py", line 1744, in execute_trade_exit
    order = self.exchange.create_order(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/exchange/exchange.py", line 1075, in create_order
    order = self._api.create_order(
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/bitvavo.py", line 1020, in create_order
    request['amount'] = self.amount_to_precision(symbol, amount)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/bitvavo.py", line 300, in amount_to_precision
    return self.decimal_to_precision(amount, TRUNCATE, self.markets[symbol]['precision']['amount'], DECIMAL_PLACES)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/base/decimal_to_precision.py", line 37, in decimal_to_precision
    assert precision is not None
           ^^^^^^^^^^^^^^^^^^^^^
AssertionError
2023-11-15 15:54:05,799 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2023-11-15 15:54:05,799 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}`

'
```

**Comment by froggleston** [comment]
Answered in https://github.com/ccxt/ccxt/issues/19991

**Comment by Johan1974** [comment]
Just to let you know, Found a way to run previous versions and ended with 4.1.39 that seems to be working fine for the moment.
