### ISSUE TITLE
WARNING - Empty candle (OHLCV) data for pair FITFI/USDT....with all pairs

### ISSUE THREAD

**Issue by shotuhhh** [freqtrade/freqtrade#9487]
* Operating system: ____Windows
  * Python Version: _____3.9
  * Freqtrade Version: ___Last version
  

Hello, Please help, how I can to fix this error and warning.?
I connect Huobi exchange.

[499 rows x 8 columns]
2023-11-30 12:05:32,846 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error 'NoneType' object has no attribute 'columns' calling <bound method IStrategy._analyze_ticker_internal of <NekStrategy.NekStrategy object at 0x0000000019CA7460>>
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda33\lib\site-packages\freqtrade\strategy\strategy_wrapper.py", line 27, in wrapper
    return f(*args, **kwargs)
  File "C:\ProgramData\Anaconda33\lib\site-packages\freqtrade\strategy\interface.py", line 862, in _analyze_ticker_internal
    dataframe = self.analyze_ticker(dataframe, metadata)
  File "C:\ProgramData\Anaconda33\lib\site-packages\freqtrade\strategy\interface.py", line 842, in analyze_ticker
    dataframe = self.advise_exit(dataframe, metadata)
  File "C:\ProgramData\Anaconda33\lib\site-packages\freqtrade\strategy\interface.py", line 1398, in advise_exit
    if 'exit_long' not in df.columns:
AttributeError: 'NoneType' object has no attribute 'columns'
2023-11-30 12:05:32,853 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair STORJ/USDT: 'NoneType' object has no attribute 'columns'
2023-11-30 12:05:32,864 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair BTC/USDT
2023-11-30 12:05:32,867 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair XRP/USDT
2023-11-30 12:05:32,869 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair ARB/USDT
2023-11-30 12:05:32,870 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair AAVE/USDT
2023-11-30 12:05:32,871 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair CRV/USDT
2023-11-30 12:05:32,873 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair SEI/USDT
2023-11-30 12:05:32,875 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair DOGE/USDT
2023-11-30 12:05:32,876 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair ETC/USDT
2023-11-30 12:05:32,879 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair SUI/USDT
2023-11-30 12:05:32,880 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair XMR/USDT
2023-11-30 12:05:32,882 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair STF/USDT
2023-11-30 12:05:32,884 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair ETH/USDT
2023-11-30 12:05:32,885 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair WAXL/USDT
2023-11-30 12:05:32,887 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair MASK/USDT
2023-11-30 12:05:32,889 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair MATIC/USDT
2023-11-30 12:05:32,891 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair AVAX/USDT
2023-11-30 12:05:32,891 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair BLUR/USDT
2023-11-30 12:05:32,893 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair APT/USDT
2023-11-30 12:05:32,894 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair CORE/USDT
2023-11-30 12:05:32,896 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair MAGIC/USDT
2023-11-30 12:05:32,897 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair NEXT/USDT
2023-11-30 12:05:32,898 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair TON/USDT
2023-11-30 12:05:32,899 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair JST/USDT
2023-11-30 12:05:32,902 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair MKR/USDT
2023-11-30 12:05:32,903 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair FITFI/USDT
2023-11-30 12:05:32,905 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV)

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

Sounds like you're not returning the dataframe in one of the `populate_*` methods - most likely in `populate_exit_trend`.

**Comment by shotuhhh** [comment]
> trend.

This is my strategy.


```
# pragma pylint: disable=missing-docstring, invalid-name, pointless-string-statement
# flake8: noqa: F401
# isort: skip_file
# --- Do not remove these libs ---
import numpy as np  # noqa
import pandas as pd  # noqa
from pandas import DataFrame
from typing import Optional, Union

from freqtrade.strategy import (BooleanParameter, CategoricalParameter, DecimalParameter,
                                IStrategy, IntParameter)

# --------------------------------
# Add your lib to import here
import talib.abstract as ta
import freqtrade.vendor.qtpylib.indicators as qtpylib

# This class is a sample. Feel free to customize it.
class NekStrategy(IStrategy):
    INTERFACE_VERSION = 2
    
    # Determine timeframe and # of candles before strategysignals becomes valid
    timeframe = '5m'
    startup_candle_count: int = 100

    # Determine roi take profit and stop loss points
    minimal_roi = {
        "0": 0.01,
        "1": 0.005,
        "2": 0.002,
        "3": 0
    }

    stoploss = -0.05
    stop_loss_range = (-0.05, -0.01)  # Stop loss range from -5% to -1
   

    take_profit = 0.02
    takeprofit_range = (0.02, 0.05)  # Take profit range from 2% to 5%

    trailing_stop = False
    use_sell_signal = True
    sell_profit_only = False
    sell_profit_offset = 0.0
    ignore_roi_if_buy_signal = False

    # --- Plotting ---
    plot_config = {
        'main_plot': {
            'SMA': {'color': 'blue'},
        },
        'subplots': {
            "RSI": {
                'rsi': {'color': 'red'},
            }
        }
    }

    # --- Used indicators of strategy code ---
    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe['rsi'] = ta.RSI(dataframe)
        dataframe['sma21'] = ta.SMA(dataframe, timeperiod=21)
        
        print(metadata)
        print(dataframe)
        return dataframe

    # --- Buy settings ---
    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                (dataframe['rsi'] > 50) &
                (qtpylib.crossed_above(dataframe['close'], dataframe['sma21']))
            ),
            'buy'] = 1

        return dataframe

    # --- Sell settings ---
    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                (dataframe['rsi'] < 50) &
                (qtpylib.crossed_below(dataframe['close'], dataframe['sma21']))
            ),
            'sell'] = 1
          return dataframe 

        # Stop loss condition
        stop_loss_condition = dataframe['close'] * (1 + self.stoploss)
        dataframe.loc[dataframe['close'] < stop_loss_condition, 'stop_loss'] = 1

        # Take profit condition
        take_profit_condition = dataframe['close'] * (1 + self.take_profit)
        dataframe.loc[dataframe['close'] > take_profit_condition, 'take_profit'] = 1
```

**Comment by xmatthias** [comment]
Aside from the strategy using the old interface (we have a [migration guide](https://www.freqtrade.io/en/stable/strategy_migration/) - as well as an automated [strategy updater command](https://www.freqtrade.io/en/stable/utils/#strategy-updater) you could try (it'll do the conversion from old to new, but won't save you from having a working strategy in the first place) - it's doing exactly what i suspected above - it's missing the `return` statement in the `populate_sell` method.

**Comment by shotuhhh** [comment]
Thank you...
