### ISSUE TITLE
bingx: Freqtrade instance crashing when a new trade is opened

### ISSUE THREAD

**Issue by xnivecompany** [freqtrade/freqtrade#9491]
## Describe your environment

  * Operating system: Ubuntu 22.04
  * Python Version: 3.10.12 
  * CCXT version: 4.1.66 
  * Freqtrade Version: 2023.11
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

The bot crashed when the trade in the exchange was opened 

### Steps to reproduce:

  1. Fresh installation of freqtrade
  2. Start with freqtrade trade --strategy name of the strategy
  3. Crash happen when the bot opens a trade
  
### Observed Results:

  * What happened? The freqtrade bot crashed
  * What did you expect to happen? To continue running

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
2023-12-02 14:00:58,723 - freqtrade.freqtradebot - INFO - Long signal found: about create a new trade for LUNC/USDT with stake_amount: 10 ...
2023-12-02 14:01:01,805 - freqtrade.freqtradebot - INFO - Order 1730950199259430912 was created for LUNC/USDT and status is open.
2023-12-02 14:01:01,806 - freqtrade.commands.trade_commands - ERROR - invalid literal for int() with base 10: ''
2023-12-02 14:01:01,807 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/root/freqtrade/freqtrade/commands/trade_commands.py", line 25, in start_trading
    worker.run()
  File "/root/freqtrade/freqtrade/worker.py", line 75, in run
    state = self._worker(old_state=state)
  File "/root/freqtrade/freqtrade/worker.py", line 116, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs,
  File "/root/freqtrade/freqtrade/worker.py", line 147, in _throttle
    result = func(*args, **kwargs)
  File "/root/freqtrade/freqtrade/worker.py", line 180, in _process_running
    self.freqtrade.process()
  File "/root/freqtrade/freqtrade/freqtradebot.py", line 249, in process
    self.enter_positions()
  File "/root/freqtrade/freqtrade/freqtradebot.py", line 536, in enter_positions
    trades_created += self.create_trade(pair)
  File "/root/freqtrade/freqtrade/freqtradebot.py", line 598, in create_trade
    return self.execute_entry(
  File "/root/freqtrade/freqtrade/freqtradebot.py", line 843, in execute_entry
    trade = Trade(
  File "<string>", line 4, in __init__
  File "/root/freqtrade/.venv/lib/python3.10/site-packages/sqlalchemy/orm/state.py", line 566, in _initialize_instance
    with util.safe_reraise():
  File "/root/freqtrade/.venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/root/freqtrade/.venv/lib/python3.10/site-packages/sqlalchemy/orm/state.py", line 564, in _initialize_instance
    manager.original_init(*mixed[1:], **kwargs)
  File "/root/freqtrade/freqtrade/persistence/trade_model.py", line 1513, in __init__
    self.recalc_open_trade_value()
  File "/root/freqtrade/freqtrade/persistence/trade_model.py", line 870, in recalc_open_trade_value
    self.open_trade_value = self._calc_open_trade_value(self.amount, self.open_rate)
  File "/root/freqtrade/freqtrade/persistence/trade_model.py", line 859, in _calc_open_trade_value
    fees = open_trade * FtPrecise(self.fee_open)
  File "/root/freqtrade/freqtrade/util/ft_precise.py", line 12, in __init__
    super().__init__(number, decimals)
  File "/root/freqtrade/.venv/lib/python3.10/site-packages/ccxt/base/precise.py", line 21, in __init__
    modifier = int(modifier)
ValueError: invalid literal for int() with base 10: ''
2023-12-02 14:01:01,810 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2023-12-02 14:01:01,811 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2023-12-02 14:01:01,811 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2023-12-02 14:01:01,815 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
2023-12-02 14:01:01,816 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.apiserver ...
2023-12-02 14:01:01,816 - freqtrade.rpc.api_server.webserver - INFO - Stopping API Server
2023-12-02 14:01:01,833 - uvicorn.error - INFO - Shutting down
2023-12-02 14:01:01,934 - uvicorn.error - INFO - Waiting for application shutdown.
2023-12-02 14:01:01,935 - uvicorn.error - INFO - Application shutdown complete.
2023-12-02 14:01:01,935 - uvicorn.error - INFO - Finished server process [34096]
2023-12-02 14:01:01,936 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.telegram ...
2023-12-02 14:01:01,990 - telegram.ext.Application - INFO - Application is stopping. This might take a moment.
2023-12-02 14:01:01,991 - telegram.ext.Application - INFO - Application.stop() complete
  ```

**Comment by xmatthias** [comment]
which exchange is this happening with?

**Comment by xnivecompany** [comment]
> which exchange is this happening with?

The example is with bingx that is supported with the cctx library

**Comment by xmatthias** [comment]
Supported by ccxt doesn't automatically mean it's supported by freqtrade.
in theory, these should work - but there's no guarantee, and you're probably the first to use bingx (at least the first i hear about).


By the looks of it (more logs would probably probably contain earlier errors) it seems like there's no fee returned by ccxt (just a suspicion though) in an expected field - which then leads to calculation problems down the road.

the fix from a freqtrade perspective will most likely be to have the trade creation fail earlier (or block bingx completely, depending on what other errors occur).

I'll eventually look at it, but this is very far down the line - and the fix will most likely not be to your liking unless it's a minor thing, with all other things working fine (which i doubt - as this is something pretty basic).

**Comment by xmatthias** [comment]
I've raised https://github.com/ccxt/ccxt/issues/20214 for this issue.

Before that is (positively) resolved, don't expect bingx to work with freqtrade (even after that, this is not guaranteed to be the only issue).

**Comment by xmatthias** [comment]
ccxt 4.1.76 will fix this particular issue.

it's not guaranteed you'll not encounter further issues though - keep in mind, you're probably the first to use bingx with freqtrade.

**Comment by xnivecompany** [comment]
> ccxt 4.1.76 will fix this particular issue.
> 
> it's not guaranteed you'll not encounter further issues though - keep in mind, you're probably the first to use bingx with freqtrade.

Thank you so much, when the pull request for the new version of cctx is going to be accepted?
