### ISSUE TITLE
Backtesting AI Model Catboost

### ISSUE THREAD

**Issue by LAMBOBLACK666** [freqtrade/freqtrade#9520]
Hello guys, iam training model catboost config file. Data 09.12.2023
```
{
    "trading_mode": "futures",
    "margin_mode": "isolated",
    "max_open_trades": 10,
    "stake_currency": "USDT",
    "stake_amount": 200,
    "tradable_balance_ratio": 1,
    "fiat_display_currency": "USD",
    "dry_run": true,
    "timeframe": "5m",
    "dry_run_wallet": 2000,
    "cancel_open_orders_on_exit": true,
    "unfilledtimeout": {
        "entry": 10,
        "exit": 30
    },
    "exchange": {
        "name": "binance",
        "key": "",
        "secret": "",
        "ccxt_config": {},
        "ccxt_async_config": {},
        "pair_whitelist": [
            "MATIC/USDT:USDT"
        ],
        "pair_blacklist": []
    },
    "entry_pricing": {
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1,
        "price_last_balance": 0.0,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "exit_pricing": {
        "price_side": "other",
        "use_order_book": true,
        "order_book_top": 1
    },
    "pairlists": [
        {
            "method": "StaticPairList"
        }
    ],
    "freqai": {
        "enabled": true,
        "purge_old_models": 2,
        "train_period_days": 30,
        "backtest_period_days": 30,
        "live_retrain_hours": 0,
        "identifier": "CatboostClassifier",
        "feature_parameters": {
            "include_timeframes": [
                "5m"
            ],
            "include_corr_pairlist": [
                "BTC/USDT:USDT"
            ],
            "label_period_candles": 20,
            "include_shifted_candles": 2,
            "DI_threshold": 0.9,
            "weight_factor": 0.9,
            "principal_component_analysis": false,
            "use_SVM_to_remove_outliers": true,
            "indicator_periods_candles": [
                10,
                20
            ],
            "plot_feature_importances": 0
        },
        "data_split_parameters": {
            "test_size": 0.33,
            "random_state": 1
        },
        "model_training_parameters": {
            "n_estimators": 800
        }
    },
    "bot_name": "",
    "force_entry_enable": true,
    "initial_state": "running",
    "internals": {
        "process_throttle_secs": 5
    }
}
```
FreqaiExampleHybridStrategy
startup_candle_count: int = 30
error back testing.
```

(.venv) (base) lamba666@DESKTOP-GU0RE7U:~/freqtrade$ freqtrade backtesting --strategy FreqaiExampleHybridStrategy --strategy-path freqtrade/templates --config config_freqai.example.json --freqaimodel CatboostClassifier --timerange 20231120-20231208
2023-12-10 12:19:33,726 - freqtrade - INFO - freqtrade 2023.12-dev-4c25e9d21
2023-12-10 12:19:33,728 - freqtrade.configuration.load_config - INFO - Using config: config_freqai.example.json ...
2023-12-10 12:19:33,729 - freqtrade.loggers - INFO - Verbosity set to 0
2023-12-10 12:19:33,730 - freqtrade.configuration.configuration - INFO - Using additional Strategy lookup path: freqtrade/templates
2023-12-10 12:19:33,730 - freqtrade.configuration.configuration - WARNING - `force_entry_enable` RPC message enabled.
2023-12-10 12:19:33,730 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 10 ...
2023-12-10 12:19:33,730 - freqtrade.configuration.configuration - INFO - Parameter --timerange detected: 20231120-20231208 ...
2023-12-10 12:19:33,730 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/lamba666/freqtrade/user_data ...
2023-12-10 12:19:33,731 - freqtrade.configuration.configuration - INFO - Using data directory: /home/lamba666/freqtrade/user_data/data/binance ...
2023-12-10 12:19:33,731 - freqtrade.configuration.configuration - INFO - Parameter --cache=day detected ...
2023-12-10 12:19:33,731 - freqtrade.configuration.configuration - INFO - Filter trades by timerange: 20231120-20231208
2023-12-10 12:19:33,731 - freqtrade.configuration.configuration - INFO - Using freqaimodel class name: CatboostClassifier
2023-12-10 12:19:33,731 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2023-12-10 12:19:33,741 - freqtrade.exchange.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2023-12-10 12:19:33,741 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2023-12-10 12:19:33,741 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2023-12-10 12:19:33,743 - freqtrade.commands.optimize_commands - INFO - Starting freqtrade in Backtesting mode
2023-12-10 12:19:33,743 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2023-12-10 12:19:33,743 - freqtrade.exchange.exchange - INFO - Using CCXT 4.1.76
2023-12-10 12:19:33,743 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}}
2023-12-10 12:19:33,754 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}}
2023-12-10 12:19:33,763 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2023-12-10 12:19:40,372 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2023-12-10 12:19:40,383 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy FreqaiExampleHybridStrategy from '/home/lamba666/freqtrade/freqtrade/templates/FreqaiExampleHybridStrategy.py'...
2023-12-10 12:19:40,383 - freqtrade.strategy.hyper - INFO - Found no parameter file.
2023-12-10 12:19:40,384 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 5m.
2023-12-10 12:19:40,384 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2023-12-10 12:19:40,384 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 200.
2023-12-10 12:19:40,384 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'entry': 10, 'exit': 30, 'exit_timeout_count': 0, 'unit': 'minutes'}.
2023-12-10 12:19:40,384 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'max_open_trades' with value in config file: 10.
2023-12-10 12:19:40,384 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'60': 0.01, '30': 0.02, '0': 0.04}
2023-12-10 12:19:40,384 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 5m
2023-12-10 12:19:40,384 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.05
2023-12-10 12:19:40,384 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2023-12-10 12:19:40,385 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2023-12-10 12:19:40,385 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2023-12-10 12:19:40,385 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2023-12-10 12:19:40,385 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: True
2023-12-10 12:19:40,385 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'entry': 'limit', 'exit': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False, 'stoploss_on_exchange_interval': 60}
2023-12-10 12:19:40,385 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'entry': 'GTC', 'exit': 'GTC'}
2023-12-10 12:19:40,385 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2023-12-10 12:19:40,385 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 200
2023-12-10 12:19:40,385 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2023-12-10 12:19:40,385 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 30
2023-12-10 12:19:40,385 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'entry': 10, 'exit': 30, 'exit_timeout_count': 0, 'unit': 'minutes'}
2023-12-10 12:19:40,385 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_exit_signal: True
2023-12-10 12:19:40,386 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_only: False
2023-12-10 12:19:40,386 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_entry_signal: False
2023-12-10 12:19:40,386 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_offset: 0.0
2023-12-10 12:19:40,386 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2023-12-10 12:19:40,386 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2023-12-10 12:19:40,386 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: False
2023-12-10 12:19:40,386 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1
2023-12-10 12:19:40,386 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_open_trades: 10
2023-12-10 12:19:40,386 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2023-12-10 12:19:40,395 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from '/home/lamba666/freqtrade/freqtrade/plugins/pairlist/StaticPairList.py'...
2023-12-10 12:19:40,403 - freqtrade.data.dataprovider - INFO - Increasing startup_candle_count for freqai to 8670
2023-12-10 12:19:40,406 - freqtrade.data.history.history_utils - INFO - Using indicator startup period: 8670 ...
2023-12-10 12:19:40,457 - freqtrade.optimize.backtesting - INFO - Loading data from 2023-10-20 21:30:00 up to 2023-12-08 00:00:00 (48 days).
2023-12-10 12:19:40,495 - freqtrade.optimize.backtesting - INFO - Dataload complete. Calculating indicators
2023-12-10 12:19:40,496 - freqtrade.optimize.backtesting - INFO - Running backtesting for Strategy FreqaiExampleHybridStrategy
2023-12-10 12:19:40,553 - freqtrade.resolvers.iresolver - INFO - Using resolved freqaimodel CatboostClassifier from '/home/lamba666/freqtrade/freqtrade/freqai/prediction_models/CatboostClassifier.py'...
2023-12-10 12:19:40,553 - freqtrade.freqai.freqai_interface - INFO - Backtesting module configured to save all models.
2023-12-10 12:19:40,555 - freqtrade.freqai.data_drawer - INFO - Found existing historic predictions at /home/lamba666/freqtrade/user_data/models/CatboostClassifier, but beware that statistics may be inaccurate if the bot has been offline for an extended period of time.
2023-12-10 12:19:40,556 - freqtrade.freqai.freqai_interface - INFO - Set existing queue from trained timestamps. Best approximation queue: deque(['MATIC/USDT:USDT'])
2023-12-10 12:19:40,556 - freqtrade.strategy.hyper - INFO - No params for buy found, using default values.
2023-12-10 12:19:40,556 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): buy_rsi = 30
2023-12-10 12:19:40,556 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): exit_short_rsi = 30
2023-12-10 12:19:40,557 - freqtrade.strategy.hyper - INFO - No params for sell found, using default values.
2023-12-10 12:19:40,557 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): sell_rsi = 70
2023-12-10 12:19:40,557 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): short_rsi = 70
2023-12-10 12:19:40,557 - freqtrade.strategy.hyper - INFO - No params for protection found, using default values.
2023-12-10 12:19:40,559 - freqtrade.freqai.freqai_interface - INFO - Training 1 timeranges
2023-12-10 12:19:40,560 - freqtrade.freqai.freqai_interface - INFO - Training MATIC/USDT:USDT, 1/1 pairs from 2023-10-21 00:00:00 to 2023-11-20 00:00:00, 1/1 trains
2023-12-10 12:19:40,560 - freqtrade.freqai.data_kitchen - INFO - Could not find backtesting prediction file at /home/lamba666/freqtrade/user_data/models/CatboostClassifier/backtesting_predictions/cb_matic_1700438400_prediction.feather
2023-12-10 12:19:40,563 - freqtrade.data.dataprovider - INFO - Increasing startup_candle_count for freqai to 30
2023-12-10 12:19:40,687 - freqtrade.data.dataprovider - INFO - Increasing startup_candle_count for freqai to 30
2023-12-10 12:19:40,809 - freqtrade.freqai.freqai_interface - INFO - Could not find model at /home/lamba666/freqtrade/user_data/models/CatboostClassifier/sub-train-MATIC_1700438400/cb_matic_1700438400
2023-12-10 12:19:42,195 - freqtrade.freqai.base_models.BaseClassifierModel - INFO - -------------------- Starting training MATIC/USDT:USDT --------------------
2023-12-10 12:19:42,235 - freqtrade.freqai.data_kitchen - INFO - MATIC/USDT:USDT: dropped 8640 training points due to NaNs in populated dataset 8640.
2023-12-10 12:19:42,236 - freqtrade.freqai.base_models.BaseClassifierModel - INFO - -------------------- Training on data from 2023-10-21 to 2023-11-19 --------------------
2023-12-10 12:19:42,236 - freqtrade.freqai.freqai_interface - WARNING - Training MATIC/USDT:USDT raised exception ValueError. Message: With n_samples=0, test_size=0.33 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters., skipping.
Traceback (most recent call last):
  File "/home/lamba666/freqtrade/freqtrade/freqai/freqai_interface.py", line 351, in start_backtesting
    self.model = self.train(dataframe_train, pair, dk)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lamba666/freqtrade/freqtrade/freqai/base_models/BaseClassifierModel.py", line 53, in train
    dd = dk.make_train_test_datasets(features_filtered, labels_filtered)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lamba666/freqtrade/freqtrade/freqai/data_kitchen.py", line 156, in make_train_test_datasets
    ) = train_test_split(
        ^^^^^^^^^^^^^^^^^
  File "/home/lamba666/freqtrade/.venv/lib/python3.11/site-packages/sklearn/utils/_param_validation.py", line 214, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/lamba666/freqtrade/.venv/lib/python3.11/site-packages/sklearn/model_selection/_split.py", line 2649, in train_test_split
    n_train, n_test = _validate_shuffle_split(
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lamba666/freqtrade/.venv/lib/python3.11/site-packages/sklearn/model_selection/_split.py", line 2305, in _validate_shuffle_split
    raise ValueError(
ValueError: With n_samples=0, test_size=0.33 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
2023-12-10 12:19:42,238 - freqtrade.freqai.freqai_interface - INFO - Saving metadata to disk.
2023-12-10 12:19:42,238 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/lamba666/freqtrade/freqtrade/main.py", line 42, in main
    return_code = args['func'](args)
                  ^^^^^^^^^^^^^^^^^^
  File "/home/lamba666/freqtrade/freqtrade/commands/optimize_commands.py", line 58, in start_backtesting
    backtesting.start()
  File "/home/lamba666/freqtrade/freqtrade/optimize/backtesting.py", line 1384, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lamba666/freqtrade/freqtrade/optimize/backtesting.py", line 1301, in backtest_one_strategy
    preprocessed = self.strategy.advise_all_indicators(data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lamba666/freqtrade/freqtrade/strategy/interface.py", line 1346, in advise_all_indicators
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lamba666/freqtrade/freqtrade/strategy/interface.py", line 1346, in <dictcomp>
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lamba666/freqtrade/freqtrade/strategy/interface.py", line 1378, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lamba666/freqtrade/freqtrade/templates/FreqaiExampleHybridStrategy.py", line 239, in populate_indicators
    dataframe = self.freqai.start(dataframe, metadata, self)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lamba666/freqtrade/freqtrade/freqai/freqai_interface.py", line 161, in start
    dk = self.start_backtesting(dataframe, metadata, self.dk, strategy)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lamba666/freqtrade/freqtrade/freqai/freqai_interface.py", line 368, in start_backtesting
    self.dd.save_metadata(dk)
  File "/home/lamba666/freqtrade/freqtrade/freqai/data_drawer.py", line 457, in save_metadata
    dk.data["training_features_list"] = list(dk.data_dictionary["train_features"].columns)
                                             ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'train_features'
(.venv) (base) lamba666@DESKTOP-GU0RE7U:~/freqtrade$ 
```

**Comment by robcaulk** [comment]
Hello,

I reckon you have problems because you are dropping 8640 out of 8640 points. Nothing to backtest!

`2023-12-10 12:19:42,235 - freqtrade.freqai.data_kitchen - INFO - MATIC/USDT:USDT: dropped 8640 training points due to NaNs in populated dataset 8640`

You haven't downloaded sufficient data: 

https://www.freqtrade.io/en/stable/freqai-running/#downloading-data-to-cover-the-full-backtest-period

Thank you for reading the documentation,

Robert

**Comment by LAMBOBLACK666** [comment]
No matter how many times I read it, I can’t understand it takes the date from the config when I initially launch it. Then I load the data, but I just can’t figure out how to calculate it correctly, I need a time frame of, for example, 1 minute. strange, but when there were catbust runs he seemed to be training or 1 minute is not suitable?

**Comment by robcaulk** [comment]
You want to train a model to make a prediction on the first point in your requested timerange. Therefore, you need to have additional data available for FreqAI to build a model for you to make a prediction on the first point of your requested timerange.

I don't understand what this has to do with 1m timeframes.

**Comment by LAMBOBLACK666** [comment]
a thousand times I checked a thousand times I made a clean installation a thousand times I unloaded all timeframes a thousand times I unloaded the data, I took only the default configs exclusively for the guide, it seems to me that I already know by heart what was written in the documentation BUT I didn't start anything.
KeyError: 'train_features'
neither training nor bektesting nor hooper wholesale. error in training occurs in the data and loss of all data. KeyError error occurs in bectesting and hooper wholesale: 'train _ features'

**Comment by robcaulk** [comment]
Hello,

Please download `train_period_days` additional data *prior* to the beginning of your desired backtesting timerange. 

I cannot distill the documentation more than this,

Rob

**Comment by LAMBOBLACK666** [comment]
first doc quick start! all exaple settings. clean start!
```
freqtrade trade --config config_examples/config_freqai.example.json --strategy FreqaiExampleStrategy --freqaimodel LightGBMRegressor --strategy-path freqtrade/templates
```

```
[LightGBM] [Info] Total Bins 138156
[LightGBM] [Info] Number of data points in the train set: 4266, number of used features: 569
[LightGBM] [Info] Start training from score 0.080441
2023-12-11 21:01:05,796 - freqtrade.freqai.base_models.BaseRegressionModel - INFO - -------------------- Done training 1INCH/USDT:USDT (8.01 secs) --------------------
2023-12-11 21:01:05,828 - freqtrade.freqai.data_drawer - INFO - Freqai purging old model file /home/lamba666/freqtrade/user_data/models/uniqe-id/sub-train-1INCH_1702317616
2023-12-11 21:01:06,218 - freqtrade.freqai.freqai_interface - INFO - Total time spent inferencing pairlist 0.44 seconds
2023-12-11 21:01:06,219 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error unsupported operand type(s) for *: 'builtin_function_or_method' and 'float' calling <bound method IStrategy._analyze_ticker_internal of <FreqaiExampleStrategy.FreqaiExampleStrategy object at 0x7f491e39af10>>
Traceback (most recent call last):
  File "/home/lamba666/freqtrade/.venv/lib/python3.11/site-packages/pandas/core/ops/array_ops.py", line 220, in _na_arithmetic_op
    result = func(left, right)
             ^^^^^^^^^^^^^^^^^
  File "/home/lamba666/freqtrade/.venv/lib/python3.11/site-packages/pandas/core/computation/expressions.py", line 242, in evaluate
    return _evaluate(op, op_str, a, b)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lamba666/freqtrade/.venv/lib/python3.11/site-packages/pandas/core/computation/expressions.py", line 131, in _evaluate_numexpr
    result = _evaluate_standard(op, op_str, a, b)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lamba666/freqtrade/.venv/lib/python3.11/site-packages/pandas/core/computation/expressions.py", line 73, in _evaluate_standard
    return op(a, b)
           ^^^^^^^^
TypeError: unsupported operand type(s) for *: 'builtin_function_or_method' and 'float'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lamba666/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 27, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/lamba666/freqtrade/freqtrade/strategy/interface.py", line 873, in _analyze_ticker_internal
    dataframe = self.analyze_ticker(dataframe, metadata)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lamba666/freqtrade/freqtrade/strategy/interface.py", line 851, in analyze_ticker
    dataframe = self.advise_indicators(dataframe, metadata)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lamba666/freqtrade/freqtrade/strategy/interface.py", line 1378, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lamba666/freqtrade/freqtrade/templates/FreqaiExampleStrategy.py", line 244, in populate_indicators
    dataframe["&-s_close_mean"] + dataframe["&-s_close_std"] * val
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
  File "/home/lamba666/freqtrade/.venv/lib/python3.11/site-packages/pandas/core/ops/common.py", line 76, in new_method
    return method(self, other)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/lamba666/freqtrade/.venv/lib/python3.11/site-packages/pandas/core/arraylike.py", line 202, in __mul__
    return self._arith_method(other, operator.mul)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lamba666/freqtrade/.venv/lib/python3.11/site-packages/pandas/core/series.py", line 5815, in _arith_method
    return base.IndexOpsMixin._arith_method(self, other, op)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lamba666/freqtrade/.venv/lib/python3.11/site-packages/pandas/core/base.py", line 1381, in _arith_method
    result = ops.arithmetic_op(lvalues, rvalues, op)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lamba666/freqtrade/.venv/lib/python3.11/site-packages/pandas/core/ops/array_ops.py", line 285, in arithmetic_op
    res_values = _na_arithmetic_op(left, right, op)  # type: ignore[arg-type]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lamba666/freqtrade/.venv/lib/python3.11/site-packages/pandas/core/ops/array_ops.py", line 229, in _na_arithmetic_op
    result = _masked_arith_op(left, right, op)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lamba666/freqtrade/.venv/lib/python3.11/site-packages/pandas/core/ops/array_ops.py", line 184, in _masked_arith_op
    result[mask] = op(xrav[mask], y)
                   ^^^^^^^^^^^^^^^^^
TypeError: unsupported operand type(s) for *: 'builtin_function_or_method' and 'float'
2023-12-11 21:01:06,220 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair 1INCH/USDT:USDT: unsupported operand type(s) for *: 'builtin_function_or_method' and 'float'
2023-12-11 21:01:06,403 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error unsupported operand type(s) for *: 'builtin_function_or_method' and 'float' calling <bound method IStrategy._analyze_ticker_internal of <FreqaiExampleStrategy.FreqaiExampleStrategy object at 0x7f491e39af10>>
Traceback (most recent call last):
  File "/home/lamba666/freqtrade/.venv/lib/python3.11/site-packages/pandas/core/ops/array_ops.py", line 220, in _na_arithmetic_op
    result = func(left, right)
             ^^^^^^^^^^^^^^^^^
  File "/home/lamba666/freqtrade/.venv/lib/python3.11/site-packages/pandas/core/computation/expressions.py", line 242, in evaluate
    return _evaluate(op, op_str, a, b)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lamba666/freqtrade/.venv/lib/python3.11/site-packages/pandas/core/computation/expressions.py", line 131, in _evaluate_numexpr
    result = _evaluate_standard(op, op_str, a, b)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lamba666/freqtrade/.venv/lib/python3.11/site-packages/pandas/core/computation/expressions.py", line 73, in _evaluate_standard
    return op(a, b)
           ^^^^^^^^
TypeError: unsupported operand type(s) for *: 'builtin_function_or_method' and 'float'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lamba666/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 27, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/lamba666/freqtrade/freqtrade/strategy/interface.py", line 873, in _analyze_ticker_internal
    dataframe = self.analyze_ticker(dataframe, metadata)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lamba666/freqtrade/freqtrade/strategy/interface.py", line 851, in analyze_ticker
    dataframe = self.advise_indicators(dataframe, metadata)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lamba666/freqtrade/freqtrade/strategy/interface.py", line 1378, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lamba666/freqtrade/freqtrade/templates/FreqaiExampleStrategy.py", line 244, in populate_indicators
    dataframe["&-s_close_mean"] + dataframe["&-s_close_std"] * val
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
  File "/home/lamba666/freqtrade/.venv/lib/python3.11/site-packages/pandas/core/ops/common.py", line 76, in new_method
    return method(self, other)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/lamba666/freqtrade/.venv/lib/python3.11/site-packages/pandas/core/arraylike.py", line 202, in __mul__
    return self._arith_method(other, operator.mul)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lamba666/freqtrade/.venv/lib/python3.11/site-packages/pandas/core/series.py", line 5815, in _arith_method
    return base.IndexOpsMixin._arith_method(self, other, op)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lamba666/freqtrade/.venv/lib/python3.11/site-packages/pandas/core/base.py", line 1381, in _arith_method
    result = ops.arithmetic_op(lvalues, rvalues, op)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lamba666/freqtrade/.venv/lib/python3.11/site-packages/pandas/core/ops/array_ops.py", line 285, in arithmetic_op
    res_values = _na_arithmetic_op(left, right, op)  # type: ignore[arg-type]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lamba666/freqtrade/.venv/lib/python3.11/site-packages/pandas/core/ops/array_ops.py", line 229, in _na_arithmetic_op
    result = _masked_arith_op(left, right, op)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lamba666/freqtrade/.venv/lib/python3.11/site-packages/pandas/core/ops/array_ops.py", line 184, in _masked_arith_op
    result[mask] = op(xrav[mask], y)
                   ^^^^^^^^^^^^^^^^^
```

**Comment by ccode124** [comment]
i downloaded data from 2023-01-01 till now, still the same issue

**Comment by robcaulk** [comment]
Please use the stable version of Freqtrade while we work on solving this bug.

**Comment by bonze82** [comment]
I'm running stable xgboost on binanceus (spot) and having the same issue nan's in the dataset during training. Also found another bug you have to delete a coin from the models/xgboost/backtesting_predictions for all coins predicted prior to the coin in question or it errors out, last run only for each coin.
