### ISSUE TITLE
freqtrade webserver + no config.json timeframe configured defaults timeframe to 5m

### ISSUE THREAD

**Issue by hippocritical** [freqtrade/freqtrade#9538]
I could make a PR if you say in which direction the issue should be solved. contemplated several ways but there was no quick+easy way without maybe screwing with something else.  

## Describe your environment
reliable reproduction at freqtrade stable 2023.11 for docker and for bare metal
 

## Describe the problem:

*Explain the problem you have encountered*
not having timeframe configured in the config.json but always in the strategy.py file
when using webserver the webserver reads the config file and if it sees no configured timeframe in the config.json it defaults to 5m and pretends there would be stated it would be 5m.

### Steps to reproduce:

  1. make webserver start with your usual config but dont have timeframe configured in there
  2. start a backtest (any strategy would suffice) that is NOT 5m and have something like 1h configured in the strategy
  3. see in the config that it uses the 5m default since the config-reading was done and if none then it defaults back to 5m
  even overriding the strategy-file since config>strategy
  
### Observed Results:

not having timeframe configured in the config.json but in the strategy works when a backtest is done in terminal, but not from webserver.
Webserver reads the config previously already and defaults to 5m after writing the timeframes' default value to 5m despite in the strategy being something else like 1h

### Relevant code exceptions or logs

![image](https://github.com/freqtrade/freqtrade/assets/41228167/71e5ea6a-ee14-4b85-a150-f578c4200731)
2023-12-11 19:25:00,135 - freqtrade.rpc.api_server.webserver - INFO - Starting Local Rest Server.
2023-12-11 19:25:00,151 - uvicorn.error - INFO - Started server process [114914]
2023-12-11 19:25:00,151 - uvicorn.error - INFO - Waiting for application startup.
2023-12-11 19:25:00,151 - uvicorn.error - INFO - Application startup complete.
2023-12-11 19:25:00,152 - uvicorn.error - INFO - Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)

![image](https://github.com/freqtrade/freqtrade/assets/41228167/be963595-545e-421a-a62c-fead8d9893a5)

2023-12-11 19:26:03,766 - freqtrade.rpc.api_server.api_backtest - ERROR - Backtesting caused an error: Main timeframe of 1h must be smaller or equal to FreqAI `include_timeframes`.Offending include-timeframes: 5m
Traceback (most recent call last):
  File "/media/Daten_1TB/Programming/freqtrade_suite/freqtrade/rpc/api_server/api_backtest.py", line 42, in __run_backtest_bg
    validate_config_consistency(btconfig)
  File "/media/Daten_1TB/Programming/freqtrade_suite/freqtrade/configuration/config_validation.py", line 89, in validate_config_consistency
    _validate_freqai_include_timeframes(conf)
  File "/media/Daten_1TB/Programming/freqtrade_suite/freqtrade/configuration/config_validation.py", line 353, in _validate_freqai_include_timeframes
    raise OperationalException(
freqtrade.exceptions.OperationalException: Main timeframe of 1h must be smaller or equal to FreqAI `include_timeframes`.Offending include-timeframes: 5m

On a 2nd pass it pretends freqai inserted 5m as timeframe but as the 1st picture says it isnt.

The configuration directly from terminal works - the strategy and config itself is not relevant since this happens at anything if you don't have timeframe configured to something in your config.json used.

configuration used including model + strategy
https://drive.google.com/file/d/1ldHnZBSKn6OsrjyKLUF4X9v9zfqZOLo0/view?usp=sharing

webserver-command:

webserver --config=user_data/fullConfig_freqaiIssue.json --config=user_data/configs_drylive/config_QuickAdapterV3_1h.json

**Comment by hippocritical** [comment]
hey,

the backtest itself fails now (which still succeeds on the stable branch)

**stable branch:**
posting the logs of the stable branch just to prove it works and as a sanity check
2023-12-11 21:38:23,199 - freqtrade.freqai.freqai_interface - INFO - Training SOL/USDT:USDT, 1/30 pairs from 2023-07-30 00:00:00 to 2023-08-13 00:00:00, 7/7 trains

**newest fork:**
logs:
2023-12-11 21:34:52,278 - freqtrade.freqai.base_models.BaseRegressionModel - INFO - -------------------- Starting training SOL/USDT:USDT --------------------
2023-12-11 21:34:52,283 - freqtrade.freqai.data_kitchen - INFO - SOL/USDT:USDT: dropped 136 training points due to NaNs in populated dataset 136.
2023-12-11 21:34:52,283 - freqtrade.freqai.freqai_interface - WARNING - Training SOL/USDT:USDT raised exception OperationalException. Message: SOL/USDT:USDT: all training data dropped due to NaNs. You likely did not download enough training data prior to your backtest timerange. Hint:
https://www.freqtrade.io/en/stable/freqai-running/#downloading-data-to-cover-the-full-backtest-period, skipping.
Traceback (most recent call last):
  File "/media/Daten_1TB/Programming/freqtrade_suite/freqtrade/freqai/freqai_interface.py", line 351, in start_backtesting
    self.model = self.train(dataframe_train, pair, dk)
  File "/media/Daten_1TB/Programming/freqtrade_suite/freqtrade/freqai/base_models/BaseRegressionModel.py", line 40, in train
    features_filtered, labels_filtered = dk.filter_features(
  File "/media/Daten_1TB/Programming/freqtrade_suite/freqtrade/freqai/data_kitchen.py", line 248, in filter_features
    raise OperationalException(
freqtrade.exceptions.OperationalException: SOL/USDT:USDT: all training data dropped due to NaNs. You likely did not download enough training data prior to your backtest timerange. Hint:
https://www.freqtrade.io/en/stable/freqai-running/#downloading-data-to-cover-the-full-backtest-period
2023-12-11 21:34:52,283 - freqtrade.freqai.freqai_interface - INFO - Saving metadata to disk.
2023-12-11 21:34:52,283 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/media/Daten_1TB/Programming/freqtrade_suite/freqtrade/main.py", line 42, in main
    return_code = args['func'](args)
  File "/media/Daten_1TB/Programming/freqtrade_suite/freqtrade/commands/optimize_commands.py", line 58, in start_backtesting
    backtesting.start()
  File "/media/Daten_1TB/Programming/freqtrade_suite/freqtrade/optimize/backtesting.py", line 1384, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
  File "/media/Daten_1TB/Programming/freqtrade_suite/freqtrade/optimize/backtesting.py", line 1301, in backtest_one_strategy
    preprocessed = self.strategy.advise_all_indicators(data)
  File "/media/Daten_1TB/Programming/freqtrade_suite/freqtrade/strategy/interface.py", line 1346, in advise_all_indicators
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "/media/Daten_1TB/Programming/freqtrade_suite/freqtrade/strategy/interface.py", line 1346, in <dictcomp>
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "/media/Daten_1TB/Programming/freqtrade_suite/freqtrade/strategy/interface.py", line 1378, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/media/Daten_1TB/Programming/freqtrade_suite/user_data/strategies/QuickAdapterV3_1h.py", line 238, in populate_indicators
    dataframe = self.freqai.start(dataframe, metadata, self)
  File "/media/Daten_1TB/Programming/freqtrade_suite/freqtrade/freqai/freqai_interface.py", line 161, in start
    dk = self.start_backtesting(dataframe, metadata, self.dk, strategy)
  File "/media/Daten_1TB/Programming/freqtrade_suite/freqtrade/freqai/freqai_interface.py", line 368, in start_backtesting
    self.dd.save_metadata(dk)
  File "/media/Daten_1TB/Programming/freqtrade_suite/freqtrade/freqai/data_drawer.py", line 457, in save_metadata
    dk.data["training_features_list"] = list(dk.data_dictionary["train_features"].columns)
KeyError: 'train_features'

Process finished with exit code 1

**Comment by xmatthias** [comment]
> SOL/USDT:USDT: all training data dropped due to NaNs

that got nothing to do with any change i'm afraid (i'd at least not know what would cause this) - but _either_ with data loading itself - or with some other parameters that turned sour / different by executing it differently.

if you search for exactly this error, then it's one of the most common errors - usually happening if "some" data is missing (obviously there can also be other problems that lead to that - i'm no freqAI expert).

I at least do get the same error "whenever" - on develop (make sure to update - this area was changed 1-2 days ago), on the fix branch - as well as when using the webserver (so the error is aligned).

I downloaded the data from 20230801 for 1h and 4h - which should suffice for this test (essentially this on a clean directory): 

```
freqtrade download-data --config=user_data/issue_9538/fullConfig_freqaiIssue.json --config=user_data/issue_9538//config_QuickAdapterV3_1h.json --timerange 20230801- -t 1h 4h
```


**edit** you can get around this by setting a higher startup candle count (i increased mine to 180).
There's no real reason to use 180 for this strategy though - at last not as far as i can see.

in my opinion, that's caused by the "fix" in #9450 (i'm not convinced that fixed anything other than hide the actual problem, but that's a different story) - which is now no longer loading sufficient startup data to actualy train the "pre" models during backtesting.

![image](https://github.com/freqtrade/freqtrade/assets/5024695/77d26f1e-3ade-4fe3-9a14-c9674bead27f)
(screenshot in from backtesting ...)

I'd however like to treat that as a separate issue eliminating webserver / freqUI from the discussion, as it's something rob should have a look at - but favorably independent of the webserver (as i can fully reproduce this with a regular backtesting command on develop)

**Comment by hippocritical** [comment]
the change to 180 candles startup solved it, just not sure why it would now need that suddenly
seeing you stated that fix #9450 will check it out to see what it does :)
other than that ... it s aligned now and works

**Comment by xmatthias** [comment]
> seeing you stated that fix https://github.com/freqtrade/freqtrade/pull/9450 will check it out to see what it does :)

The point is - the calculation of startup-candles for freqAI changed. Previously, backtesting did increase the startup-candle-count depending on freqAI settings - now it no longer does, and simply uses the value given to load the main timeframe (so if that says 80 candles, it'll load 80 candles in the main timeframe).

In my opinion, this tried to fix some odd behavior, while really introducing a different bug - but i did lack the time to look at it in detail, therefore it's a suspicion after looking at this strategy - but not something i can currently proof.

**Comment by robcaulk** [comment]
Let's revert #9450 . The percentage of people it helped was near 0 (only people using big timeframes and trying to backtest multiple years). 

But @xmatthias is right, it ended up inadvertently causing other issues.
