### ISSUE TITLE
Back testing and export file error due to Nan values (Out of range float values are not JSON compliant)

### ISSUE THREAD

**Issue by gaugau3000** [freqtrade/freqtrade#9550]
Hi

Freqtrade version : freqtrade 2023.12-dev

When my export has Nan values it raise error :

```
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 42, in main
    return_code = args['func'](args)
                  ^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 58, in start_backtesting
    backtesting.start()
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 1415, in start
    store_backtest_stats(self.config['exportfilename'], self.results, dt_appendix)
  File "/freqtrade/freqtrade/optimize/optimize_reports/bt_storage.py", line 38, in store_backtest_stats
    file_dump_json(filename, stats_copy)
  File "/freqtrade/freqtrade/misc.py", line 72, in file_dump_json
    rapidjson.dump(data, fp, default=str, number_mode=rapidjson.NM_NATIVE)
ValueError: Out of range float values are not JSON compliant

```

in file_dump_json (https://github.com/freqtrade/freqtrade/blob/62667d123f7a82cc5c0eda6849ec95fb2b7cb88c/freqtrade/misc.py#L49) if I add :

`rapidjson.dump(sanitize_data(data), fp, default=str, number_mode=rapidjson.NM_NATIVE)`

with

```
def sanitize_data(data, path=""):
    """
    Recursively inspect data and replace non-compliant float values
    (NaN, Infinity, -Infinity) with a compliant value (e.g., None).
    Log each replacement.
    """
    if isinstance(data, dict):
        return {k: sanitize_data(v, path + f".{k}") for k, v in data.items()}
    elif isinstance(data, list):
        return [sanitize_data(item, path + f"[{index}]") for index, item in enumerate(data)]
    elif isinstance(data, float):
        if math.isnan(data) or math.isinf(data):
            print(f"Replacing non-compliant value at {path}: {data} with None")
            return None  # Replace with None or a compliant float value like 0.0
        else:
            return data
    else:
        return data
```
Ouput :

> Replacing non-compliant value at .strategy.Rsi.trades[1786].profit_ratio: nan with None
> Replacing non-compliant value at .strategy.Rsi.trades[1786].profit_abs: nan with None
> Replacing non-compliant value at .strategy.Rsi.trades[1794].profit_ratio: nan with None
> Replacing non-compliant value at .strategy.Rsi.trades[1794].profit_abs: nan with None
> Replacing non-compliant value at .strategy.Rsi.cagr: nan with None
> Replacing non-compliant value at .strategy.Rsi.final_balance: nan with None

It fixes the problem, but maybe it should never render a "Nan" and manage earlier.

Many TKS.

See you !

**Comment by gaugau3000** [comment]
I close for now has it seems to be corrupted backtest candles that lead to that.
