### ISSUE TITLE
telegram.ext.Updater - ERROR - Error while getting Updates: Bad Gateway?

### ISSUE THREAD

**Issue by csquan** [freqtrade/freqtrade#9553]
hi,guys,when I run second bot on same ecs,use different tele config,
 like this

"telegram": {
        "enabled": true,
        "token": "6641110923:AAEJF7VTJ7Einj5XNia3cnUBVkzynmWQbIU",
。。。
token  in config is different ,then log show "telegram.ext.Updater - ERROR - Error while getting Updates: Bad Gateway",
I had google it,say that "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running",
refer to url:https://github.com/python-telegram-bot/python-telegram-bot/issues/1821,why?

**Comment by stash86** [comment]
are you sure you put different tokens for bot 1 and bot 2?

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

I'm not entirely sure that's the case.

the error seems to come from google, not from the logs.
Freqtrade though will NOT issue a "BadRequest" in this case - but the following error:

`telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running`

Which suggests that we're either dealing 
* with an outdated version (older telegram versions may have behaved differently) - 
* or a different problem - most likely one where telegram is  blocked from the source IP / country
* or a "i got this error, but am not running a freqtrade bot" situation, which means this repo was found through google (in which case, you're in the wrong place for help, sorry).

**Comment by csquan** [comment]
> are you sure you put different tokens for bot 1 and bot 2?

yes，use different config file,different token.

code:

config1.json

    "telegram": {
        "enabled": true,
        "token": "6723******:AAEJAHSr45nu2k8PDR9GTdz2na-jvo7cntA",
        "chat_id": "xxx",...
config2.json:
    
   "telegram": {
        "enabled": true,
        "token": "66411*****:AAEJF7VTJ7Einj5XNia3cnUBVkzynmWQbIU",
        "chat_id": "xxx",...

**Comment by xmatthias** [comment]
Please share the actual logs that you're seeing - so we can determine at what stage in the startup the bot is showing this error (and what error precisely).

**Comment by csquan** [comment]
```
2023-12-15 01:09:57,619 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2023.9, strategy_version: v12.0.284', state='RUNNING'
2023-12-15 01:10:21,124 - telegram.ext.Updater - ERROR - Error while getting Updates: Bad Gateway
2023-12-15 01:10:21,124 - telegram.ext.Updater - ERROR - Exception happened while polling for updates.
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.11/site-packages/telegram/ext/_updater.py", line 628, in _network_loop_retry
    if not await action_cb():
           ^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/telegram/ext/_updater.py", line 333, in polling_action_cb
    raise exc
  File "/home/ftuser/.local/lib/python3.11/site-packages/telegram/ext/_updater.py", line 322, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 553, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/telegram/_bot.py", line 394, in decorator
    result = await func(self, *args, **kwargs)  # skipcq: PYL-E1102
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/telegram/_bot.py", line 3542, in get_updates
    await self._post(
  File "/home/ftuser/.local/lib/python3.11/site-packages/telegram/_bot.py", line 482, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 335, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/telegram/_bot.py", line 510, in _do_post
    return await request.post(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 168, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 329, in _request_wrapper
    raise NetworkError(description or "Bad Gateway")
telegram.error.NetworkError: Bad Gateway
2023-12-15 01:10:22,422 - telegram.ext.Updater - ERROR - Error while getting Updates: Bad Gateway
2023-12-15 01:10:22,423 - telegram.ext.Updater - ERROR - Exception happened while polling for updates.
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.11/site-packages/telegram/ext/_updater.py", line 628, in _network_loop_retry
    if not await action_cb():
           ^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/telegram/ext/_updater.py", line 333, in polling_action_cb
    raise exc
  File "/home/ftuser/.local/lib/python3.11/site-packages/telegram/ext/_updater.py", line 322, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 553, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/telegram/_bot.py", line 394, in decorator
    result = await func(self, *args, **kwargs)  # skipcq: PYL-E1102
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/telegram/_bot.py", line 3542, in get_updates
    await self._post(
  File "/home/ftuser/.local/lib/python3.11/site-packages/telegram/_bot.py", line 482, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 335, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/telegram/_bot.py", line 510, in _do_post
    return await request.post(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 168, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 329, in _request_wrapper
    raise NetworkError(description or "Bad Gateway")
telegram.error.NetworkError: Bad Gateway
2023-12-15 01:11:02,157 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2023.9, strategy_version: v12.0.284', state='RUNNING'
```

**Comment by xmatthias** [comment]
Well based on the code in the telegram library - the error is exactly what it says - a Bad Gateway error (http errorcode 502).

That can have many reasons, like
* no network connection
* telegram is blocked in your country
* telegram had problems in your region
* an invalid proxy configuration
* an outdated library version (which you're for sure using, based on the freqtrade version).

None of which are things freqtrade can control or help you with beyond some initial pointers.

---


Please try with one of the supported versions of freqtrade (2023.9 is not).
Please make sure to follow the [updating](https://www.freqtrade.io/en/stable/updating/) instructions for your installation method to also have dependencies updated.

**Comment by xmatthias** [comment]
Closing this with the assumption that one of the above recommendation did help.

**Comment by Kaki-In** [comment]
Hello, 

My telegram bot works succesfully, else sometimes, when I check the logs, I discover that, after a bad gateway error, it does nothing (the error blocks him or something like that). When I ^C it and rerun it, all is fine. What can I do?

**Comment by xmatthias** [comment]
@Kaki-In well the tips above won't change - it'll be either of these points.

all are either related to telegram servers - or to your network configuration. There's nothing we can do other than point these out ... as they're out of our control.

**Comment by Faso-main** [comment]
oh telegram servers, to hell with you................
