### ISSUE TITLE
plot-dataframe  error

### ISSUE THREAD

**Issue by maddrid** [freqtrade/freqtrade#9562]
## Describe your environment

  * Operating system: Ubuntu 20
  * Python Version:Python 3.9.5
   * CCXT version: =4.1.66
    * Freqtrade Version: freqtrade 2023.11

  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:
```
(.venv) master@freqtrade:~/freqtrade$ freqtrade plot-dataframe -s  StrategyX-p ETH/USDT:USDT
2023-12-17 22:19:32,322 - freqtrade - INFO - freqtrade 2023.11
2023-12-17 22:19:32,566 - freqtrade.configuration.load_config - INFO - Using config: user_data/config.json ...
2023-12-17 22:19:32,567 - freqtrade.loggers - INFO - Verbosity set to 0
2023-12-17 22:19:32,568 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/master/freqtrade/user_data ...
2023-12-17 22:19:32,568 - freqtrade.configuration.configuration - INFO - Using data directory: /home/master/freqtrade/user_data/data/binance ...
2023-12-17 22:19:32,568 - freqtrade.configuration.configuration - INFO - Using pairs ['ETH/USDT:USDT']
2023-12-17 22:19:32,568 - freqtrade.configuration.configuration - INFO - Limiting plot to: 750
2023-12-17 22:19:32,568 - freqtrade.configuration.configuration - INFO - Using trades from: file
2023-12-17 22:19:32,569 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2023-12-17 22:19:32,581 - freqtrade.exchange.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2023-12-17 22:19:32,582 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
Exception ignored in: <function Exchange.__del__ at 0x7f1b491d69d0>
Traceback (most recent call last):
  File "/home/master/freqtrade/freqtrade/exchange/exchange.py", line 204, in __del__
  File "/home/master/freqtrade/freqtrade/exchange/exchange.py", line 207, in close
  File "/usr/lib/python3.9/logging/__init__.py", line 1434, in debug
  File "/usr/lib/python3.9/logging/__init__.py", line 1589, in _log
  File "/usr/lib/python3.9/logging/__init__.py", line 1599, in handle
  File "/usr/lib/python3.9/logging/__init__.py", line 1661, in callHandlers
  File "/usr/lib/python3.9/logging/__init__.py", line 952, in handle
  File "/usr/lib/python3.9/logging/__init__.py", line 1186, in emit
  File "/usr/lib/python3.9/logging/__init__.py", line 1175, in _open
NameError: name 'open' is not defined
Exception ignored in: <function Exchange.__del__ at 0x7f1b4990cee0>
Traceback (most recent call last):
  File "/home/master/freqtrade/.venv/lib/python3.9/site-packages/ccxt/async_support/base/exchange.py", line 93, in __del__
  File "/usr/lib/python3.9/logging/__init__.py", line 1458, in warning
  File "/usr/lib/python3.9/logging/__init__.py", line 1589, in _log
  File "/usr/lib/python3.9/logging/__init__.py", line 1599, in handle
  File "/usr/lib/python3.9/logging/__init__.py", line 1661, in callHandlers
  File "/usr/lib/python3.9/logging/__init__.py", line 952, in handle
  File "/usr/lib/python3.9/logging/__init__.py", line 1186, in emit
  File "/usr/lib/python3.9/logging/__init__.py", line 1175, in _open
NameError: name 'open' is not defined
Exception ignored in: <function ClientSession.__del__ at 0x7f1b498f7f70>
Traceback (most recent call last):
  File "/home/master/freqtrade/.venv/lib/python3.9/site-packages/aiohttp/client.py", line 363, in __del__
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1771, in call_exception_handler
  File "/usr/lib/python3.9/logging/__init__.py", line 1475, in error
  File "/usr/lib/python3.9/logging/__init__.py", line 1589, in _log
  File "/usr/lib/python3.9/logging/__init__.py", line 1599, in handle
  File "/usr/lib/python3.9/logging/__init__.py", line 1661, in callHandlers
  File "/usr/lib/python3.9/logging/__init__.py", line 952, in handle
  File "/usr/lib/python3.9/logging/__init__.py", line 1186, in emit
  File "/usr/lib/python3.9/logging/__init__.py", line 1175, in _open
NameError: name 'open' is not defined
Exception ignored in: <function BaseConnector.__del__ at 0x7f1b49aebb80>
Traceback (most recent call last):
  File "/home/master/freqtrade/.venv/lib/python3.9/site-packages/aiohttp/connector.py", line 285, in __del__
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1771, in call_exception_handler
  File "/usr/lib/python3.9/logging/__init__.py", line 1475, in error
  File "/usr/lib/python3.9/logging/__init__.py", line 1589, in _log
  File "/usr/lib/python3.9/logging/__init__.py", line 1599, in handle
  File "/usr/lib/python3.9/logging/__init__.py", line 1661, in callHandlers
  File "/usr/lib/python3.9/logging/__init__.py", line 952, in handle
  File "/usr/lib/python3.9/logging/__init__.py", line 1186, in emit
  File "/usr/lib/python3.9/logging/__init__.py", line 1175, in _open
```

### Relevant code exceptions or logs

 commenting  the  logger  in  /home/master/freqtrade/freqtrade/exchange/exchange.py  line 206 will not   throw  error

  ```
  def close(self):
        #logger.debug("Exchange object destroyed, closing async loop")
        if (self._api_async and inspect.iscoroutinefunction(self._api_async.close)
                and self._api_async.session):
           # logger.debug("Closing async ccxt session.")
            self.loop.run_until_complete(self._api_async.close())
        if self.loop and not self.loop.is_closed():
            self.loop.close()
  ```
 related   to  this 
 [https://stackoverflow.com/questions/64679139/nameerror-name-open-is-not-defined-when-trying-to-log-to-files](https://stackoverflow.com/questions/64679139/nameerror-name-open-is-not-defined-when-trying-to-log-to-files)

**Comment by xmatthias** [comment]
as the stackoverflow post suggests, you can quite easily work around this by updating your python to 3.10.
At any rate, you should update to the latest 3.9.x (3.9.18 at this point) and re-test with that.
We'll not be supporting outdated python versions.

---

I've actually never seen this trigger in anything other than tests - and the log looks ... oddly short (at this point, there is no shutdown happening).
Are you sure the log is not truncated / missing some parts ? 

As a sidenote - i can run the command above (obviously with my strategy) just fine - though i'm on 3.11 (but as said, there is not eardown happening at this point, there's at least 4-6 other log-lines between).

**Comment by xmatthias** [comment]
I've just given this a try with python 3.9.18 (the latest 3.9 version available) - and can't recreate this.

As such - i'll assume this is due to the outdated python version.
Let me know below if updating python doesn't fix this so we can have a look at it again, for now, i consider this an issue that's caused by an outdated python version.
