### ISSUE TITLE
Freqtrade is potentially stuck with an old strategy class

### ISSUE THREAD

**Issue by spidersecurity** [freqtrade/freqtrade#9578]
## My environment

Operating system: Ubuntu 22.04, Running in docker (Docker version 24.0.5, build 24.0.5-0ubuntu1~22.04.1)
CCXT version: _____ 4.1.84
Freqtrade Version: ____ freqtrade 2023.11 (Also tried with 2023.12-dev-4cc4f0ff)

## Your question

While backtesting it has observed that Freqtrade is potentially stuck with an old strategy I've used in the past. As per the error showed below, _Mynewstrategy1.py_ is the one I've used before but not with the current command. Tried changing the command with multiple strategy classes and also used the below commands to rerun docker with latest images – no luck. Am I missing something?

docker-compose down
docker-compose pull
docker-compose up -d

## Error

2023-12-19 12:23:43,074 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Bitvavo'...
2023-12-19 12:23:43,183 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 42, in main
    return_code = args['func'](args)
                  ^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 57, in start_backtesting
    backtesting = Backtesting(config)
                  ^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 112, in __init__
    self.strategylist.append(StrategyResolver.load_strategy(self.config))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 48, in load_strategy
    strategy: IStrategy = StrategyResolver._load_strategy(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 269, in _load_strategy
    strategy = StrategyResolver._load_object(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/resolvers/iresolver.py", line 149, in _load_object
    (module, module_path) = cls._search_object(directory=_path,
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/resolvers/iresolver.py", line 131, in _search_object
    obj = next(cls._get_valid_object(module_path, object_name), None)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/resolvers/iresolver.py", line 91, in _get_valid_object
    spec.loader.exec_module(module)  # type: ignore # importlib does not use typehints
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/freqtrade/user_data/strategies/Mynewstrategy1.py", line 61, in <module>
    my_strategy = MyStrategy()
                  ^^^^^^^^^^^^
TypeError: IStrategy.__init__() missing 1 required positional argument: 'config'
ERROR: 1

**Comment by froggleston** [comment]
Freqtrade will try to load all strategies within the user_data/strategies folder. If any fail, even one you're not intending to use for a command, FT will complain. I suggest moving the problematic strategy into another folder, and then it should hopefully work.

**Comment by spidersecurity** [comment]
Thanks @froggleston That worked!
