### ISSUE TITLE
exit_fill webhook causes exception

### ISSUE THREAD

**Issue by t-pohl** [freqtrade/freqtrade#9581]
## Describe your environment

  * Operating system: Ubuntu 22.04.3 LTS
  * Python Version: 3.11.6
  * CCXT version: 4.1.66
  * Freqtrade Version: freqtrade 2023.11
  
## Describe the problem:

I started freqtrade using the :stable docker container (see version above) with webhooks via REST enabled ( see webhook config below). 
When I get the first trades everything is fine for entrys and exits. Only `exit_fill` seems to be broken. The error log (see below) indicates that something with the message format itself seems to be broken.

### Steps to reproduce:

  1. Start the freqtrade :stable container with the provided webhook config.
  2. Wait for the first trade to be exited.
  3. Check the logs for exit_fill to see the error.
  
### Observed Results:

  * The webhook for exit_fill was not invoked but instead I got an error.
  * A successful POST call against my webhook url for the exit_fill case.

### Relevant code exceptions or logs

The webhook setting from my config file:

```
"webhook": {
  "url": "<MY BACKEND URL>",
  "format": "json",
  "enabled": true,
  "entry": {
    "trade_id": "{trade_id}",
    "exchange": "{exchange}",
    "pair": "{pair}",
    "direction": "{direction}",
    "leverage": "{leverage:8f}",
    "open_rate": "{open_rate:8f}",
    "amount": "{amount:8f}",
    "open_date": "{open_date}",
    "stake_amount": "{stake_amount:8f}",
    "stake_currency": "{stake_currency}",
    "base_currency": "{base_currency}",
    "fiat_currency": "{fiat_currency}",
    "order_type": "{order_type}",
    "current_rate": "{current_rate:8f}",
    "enter_tag": "{enter_tag}",
    "type": "entry"
  },
  "entry_cancel": {
    "trade_id": "{trade_id}",
    "exchange": "{exchange}",
    "pair": "{pair}",
    "direction": "{direction}",
    "leverage": "{leverage:8f}",
    "limit": "{limit:8f}",
    "amount": "{amount:8f}",
    "open_date": "{open_date}",
    "stake_amount": "{stake_amount:8f}",
    "stake_currency": "{stake_currency}",
    "base_currency": "{base_currency}",
    "fiat_currency": "{fiat_currency}",
    "order_type": "{order_type}",
    "current_rate": "{current_rate:8f}",
    "enter_tag": "{enter_tag}",
    "open_rate": "{open_rate:8f}",
    "type": "entry_cancel"
  },
  "entry_fill": {
    "trade_id": "{trade_id}",
    "exchange": "{exchange}",
    "pair": "{pair}",
    "direction": "{direction}",
    "leverage": "{leverage:8f}",
    "open_rate": "{open_rate:8f}",
    "amount": "{amount:8f}",
    "open_date": "{open_date}",
    "stake_amount": "{stake_amount:8f}",
    "stake_currency": "{stake_currency}",
    "base_currency": "{base_currency}",
    "fiat_currency": "{fiat_currency}",
    "order_type": "{order_type}",
    "current_rate": "{current_rate:8f}",
    "enter_tag": "{enter_tag}",
    "type": "entry_fill"
  },
  "exit": {
    "trade_id": "{trade_id}",
    "exchange": "{exchange}",
    "pair": "{pair}",
    "direction": "{direction}",
    "leverage": "{leverage:8f}",
    "gain": "{gain}",
    "limit": "{limit:8f}",
    "amount": "{amount:8f}",
    "open_rate": "{open_rate:8f}",
    "profit_amount": "{profit_amount:8f}",
    "profit_ratio": "{profit_ratio:8f}",
    "stake_currency": "{stake_currency}",
    "base_currency": "{base_currency}",
    "fiat_currency": "{fiat_currency}",
    "exit_reason": "{exit_reason}",
    "order_type": "{order_type}",
    "open_date": "{open_date}",
    "close_date": "{close_date}",
    "type": "exit"
  },
  "exit_cancel": {
    "trade_id": "{trade_id}",
    "exchange": "{exchange}",
    "pair": "{pair}",
    "direction": "{direction}",
    "leverage": "{leverage:8f}",
    "gain": "{gain}",
    "limit": "{limit:8f}",
    "amount": "{amount:8f}",
    "open_rate": "{open_rate:8f}",
    "current_rate": "{current_rate:8f}",
    "profit_amount": "{profit_amount:8f}",
    "profit_ratio": "{profit_ratio:8f}",
    "stake_currency": "{stake_currency}",
    "base_currency": "{base_currency}",
    "fiat_currency": "{fiat_currency}",
    "exit_reason": "{exit_reason}",
    "order_type": "{order_type}",
    "open_date": "{open_date}",
    "close_date": "{close_date}",
    "type": "exit_cancel"
  },
  "exit_fill": {
    "trade_id": "{trade_id}",
    "exchange": "{exchange}",
    "pair": "{pair}",
    "direction": "{direction}",
    "leverage": "{leverage:8f}",
    "gain": "{gain}",
    "close_rate": "{close_rate:8f}",
    "amount": "{amount:8f}",
    "open_rate": "{open_rate:8f}",
    "current_rate": "{current_rate:8f}",
    "profit_amount": "{profit_amount:8f}",
    "profit_ratio": "{profit_ratio:8f}",
    "stake_currency": "{stake_currency}",
    "base_currency": "{base_currency}",
    "fiat_currency": "{fiat_currency}",
    "exit_reason": "{exit_reason}",
    "order_type": "{order_type}",
    "open_date": "{open_date}",
    "close_date": "{close_date}",
    "type": "exit_fill"
  }
},
```
 

Of course `MY BACKEND URL` is replaced in the real running config.

The error log from the container:

```
2023-12-21T09:35:19.015151208Z 2023-12-21 09:35:11,626 - freqtrade.persistence.trade_model - INFO - Marking Trade(id=17, pair=XMR/USDT, amount=0.22800000, is_short=False, leverage=1.0, open_rate=175.10000000, open_since=closed) as closed as the trade is fulfilled and found no open orders for it.

2023-12-21T09:35:19.328060854Z 2023-12-21 09:35:11,639 - freqtrade.wallets - INFO - Wallets synced.

2023-12-21T09:35:19.669405153Z 2023-12-21 09:35:11,642 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': exit_fill, 'trade_id': 17, 'exchange': 'Binance', 'pair': 'XMR/USDT', 'leverage': 1.0, 'direction': 'Long', 'gain': 'profit', 'limit': 175.7, 'order_rate': 175.7, 'order_type': '', 'amount': 0.228, 'open_rate': 175.1, 'close_rate': 175.7, 'current_rate': None, 'profit_amount': 0.0568176, 'profit_ratio': 0.00142176, 'buy_tag': None, 'enter_tag': None, 'sell_reason': 'exit_signal', 'exit_reason': 'exit_signal', 'open_date': datetime.datetime(2023, 12, 21, 9, 29, 13, 591088, tzinfo=datetime.timezone.utc), 'close_date': datetime.datetime(2023, 12, 21, 9, 35, 10, 551000, tzinfo=datetime.timezone.utc), 'stake_amount': 39.9228, 'stake_currency': 'USDT', 'base_currency': 'XMR', 'fiat_currency': 'USD', 'sub_trade': False, 'cumulative_profit': 0.0568176}

2023-12-21T09:35:20.009194607Z 2023-12-21 09:35:11,642 - freqtrade.rpc.rpc_manager - ERROR - Exception occurred within RPC module webhook

2023-12-21T09:35:20.343242100Z Traceback (most recent call last):

2023-12-21T09:35:20.677887514Z File "/freqtrade/freqtrade/rpc/rpc_manager.py", line 76, in send_msg

2023-12-21T09:35:20.992371853Z mod.send_msg(msg)

2023-12-21T09:35:21.305205438Z File "/freqtrade/freqtrade/rpc/webhook.py", line 90, in send_msg

2023-12-21T09:35:21.618513915Z payload = {key: value.format(**msg) for (key, value) in valuedict.items()}

2023-12-21T09:35:21.951702115Z ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-12-21T09:35:22.290981859Z File "/freqtrade/freqtrade/rpc/webhook.py", line 90, in <dictcomp>

2023-12-21T09:35:22.631173985Z payload = {key: value.format(**msg) for (key, value) in valuedict.items()}

2023-12-21T09:35:22.967509282Z ^^^^^^^^^^^^^^^^^^^

2023-12-21T09:35:23.280321718Z TypeError: unsupported format string passed to NoneType.__format__
```

**Comment by xmatthias** [comment]
The exception that's thrown is properly handled, and the bot does continue to work just fine.

That's not a bug - but simply a misconfiguration on your side / in your configuration.

Not sure where you got the configuration values for this from (not from the docs ...), but you're trying to format a value that either doesn't exist, or isn't guaranteed to be filled.

You're taking assumptions (value is a float) for most values - which is neither documented this way, nor guaranteed to be the case (some/most values may be None in some messagetypes).

I'll leave it up to you to figure out which field is causing it for your particular case.
you can either omit the formatting (`:8f`) - or remove the individual fields until you figure out the ACTUAL field that's causing the problem.

**Comment by t-pohl** [comment]
Thank you very much for the fast reply :+1: 
Removing the `:8f` formatter everywhere fixed the problem and it does not seem to do anything.
