### ISSUE TITLE
Validation Error while fetching Order from Bitstamp "Input should be a valid string", order not showing as open on UI

### ISSUE THREAD

**Issue by treeol** [freqtrade/freqtrade#9591]
## Describe your environment

  * Operating system: docker container from freqtrade
ftuser@4e1141a45ecd:/freqtrade$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
  * Python Version: **Python 3.11.6**
  * CCXT version: **ccxt==4.1.66**
  * Freqtrade Version: **freqtrade 2023.11**
  * Used Exchange: **Bitstamp**

## Describe the problem:

Bot was working perfectly fine and opened up the trade at given buy-signal, once trade happened, it tried to open more trades but failed due to lack of liquidity in base account.

Now I get every couple of seconds/minutes the following error:

```
2023-12-24 10:17:10,393 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ftuser/.local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ftuser/.local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/ftuser/.local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/ftuser/.local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/home/ftuser/.local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/ftuser/.local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/ftuser/.local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/ftuser/.local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/ftuser/.local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/ftuser/.local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/ftuser/.local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/fastapi/routing.py", line 292, in app
    content = await serialize_response(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/fastapi/routing.py", line 155, in serialize_response
    raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError: 1 validation errors:
  {'type': 'string_type', 'loc': ('response', 0, 'orders', 0, 'order_type'), 'msg': 'Input should be a valid string', 'input': None, 'url': 'https://errors.pydantic.dev/2.5/v/string_type'}
```

And the order which was executed is not visible as open in the ui, currently not sure if it will exit like defined.

### Steps to reproduce:

  1. Setup sub-account on Bitstamp
  2. Create API Key for Sub Account
  3. Configure fq-trade with Bitstamp as exchange and add API Key/Secret
  4. A trade needs to be triggered (or maybe opened manually is already enough)
  
### Observed Results:

  * What happened?
The order was execute successfully but it's not showing as an open order on freqtrade UI and I'm not sure if freqtrade will exit at given signal. It also is constantly showing the error above.

But, I can see the trade/order with Telegram and it shows that it's open. It might just be an error which is only limited to the UI and not trading engine itself.

  * What did you expect to happen?
The order gets executed and will be visible availbe in the UI + showing the current roi until sell signal will be executed.

### Relevant code exceptions or logs

  ```
2023-12-24 05:45:26,056 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=1, pair=SECURITYREASONS/USD, amount=1465.12990819, is_short=False, leverage=1.0, open_rate=0.61428000, open_since=2023-12-24 05:45:06)
2023-12-24 05:45:26,081 - freqtrade.freqtradebot - INFO - Fee for Trade Trade(id=1, pair=SECURITYREASONS/USD, amount=1465.12990819, is_short=False, leverage=1.0, open_rate=0.61428000, open_since=2023-12-24 05:45:06) [buy]: 2.7 USD - rate: 0.003
2023-12-24 05:45:26,082 - freqtrade.persistence.trade_model - INFO - Updating trade (id=1) ...
2023-12-24 05:45:26,083 - freqtrade.commands.trade_commands - ERROR - 'NoneType' object has no attribute 'upper'
2023-12-24 05:45:26,084 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 25, in start_trading
    worker.run()
  File "/freqtrade/freqtrade/worker.py", line 75, in run
    state = self._worker(old_state=state)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/worker.py", line 116, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs,
  File "/freqtrade/freqtrade/worker.py", line 147, in _throttle
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/worker.py", line 180, in _process_running
    self.freqtrade.process()
  File "/freqtrade/freqtrade/freqtradebot.py", line 232, in process
    self.manage_open_orders()
  File "/freqtrade/freqtrade/freqtradebot.py", line 1346, in manage_open_orders
    fully_cancelled = self.update_trade_state(trade, open_order.order_id, order)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/freqtradebot.py", line 1931, in update_trade_state
    trade.update_trade(order_obj, not send_msg)
  File "/freqtrade/freqtrade/persistence/trade_model.py", line 767, in update_trade
    logger.info(f'{order.order_type.upper()}_{payment} has been fulfilled for {self}.')
                   ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'upper'
2023-12-24 05:45:26,085 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2023-12-24 05:45:26,086 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}

`2023-12-24 10:17:10,393 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ftuser/.local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ftuser/.local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/ftuser/.local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/ftuser/.local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/home/ftuser/.local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/ftuser/.local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/ftuser/.local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/ftuser/.local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/ftuser/.local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/ftuser/.local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/ftuser/.local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/fastapi/routing.py", line 292, in app
    content = await serialize_response(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/fastapi/routing.py", line 155, in serialize_response
    raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError: 1 validation errors:
  {'type': 'string_type', 'loc': ('response', 0, 'orders', 0, 'order_type'), 'msg': 'Input should be a valid string', 'input': None, 'url': 'https://errors.pydantic.dev/2.5/v/string_type'}`
  ```

**Comment by xmatthias** [comment]
first off - bitstamp is not a supported exchange.
We can provide some hints for resolution, and eventually provide some minor fixes if necessary - but ultimately, testing on the exchange is up to you (otherwise, please use one of the supported exchanges).
I do not have an account on bitstamp, and do not currently plan on creating one, either.

---

The log itself unfortunately doesn't really contain much info. What you're seeing is a simple validation error from the API, as the order is missing some required fields.
The problem however happens way earlier, essentially when the order is created / placed.


To get (hopefully) "useful" logs - please enable `exchange.log_responses` - restart the bot (ideally with a new database) - and create an entry (as you mention, a force-enter should most likely work).

My assumption is that this will create the same problem - but then we'll have logs (the interesting things are the logs UP to that point - not necessarily the validation error that happens from the RPC module).

**Comment by treeol** [comment]
Hi @xmatthias thanks for answering.

Yes I am aware that Bitstamp is not supported, altough I feel like it should, as it's one of the oldest around, anyway.

I updated the config.json and added the log_responses in the exchange section, here is the log after force_entry:

```
2023-12-24 12:19:48,994 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=1, pair=SECURITYREASONS/USD, amount=161.75994824, is_short=False, leverage=1.0, open_rate=0.61820000, open_since=2023-12-24 12:19:48)
2023-12-24 12:19:49,022 - freqtrade.freqtradebot - INFO - Fee for Trade Trade(id=1, pair=SECURITYREASONS/USD, amount=161.75994824, is_short=False, leverage=1.0, open_rate=0.61820000, open_since=2023-12-24 12:19:48) [buy]: 0.39995 USD - rate: 0.00400002
2023-12-24 12:19:49,023 - freqtrade.persistence.trade_model - INFO - Updating trade (id=1) ...
2023-12-24 12:19:49,024 - freqtrade.commands.trade_commands - ERROR - 'NoneType' object has no attribute 'upper'
2023-12-24 12:19:49,025 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 25, in start_trading
    worker.run()
  File "/freqtrade/freqtrade/worker.py", line 75, in run
    state = self._worker(old_state=state)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/worker.py", line 116, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs,
  File "/freqtrade/freqtrade/worker.py", line 147, in _throttle
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/worker.py", line 180, in _process_running
    self.freqtrade.process()
  File "/freqtrade/freqtrade/freqtradebot.py", line 232, in process
    self.manage_open_orders()
  File "/freqtrade/freqtrade/freqtradebot.py", line 1346, in manage_open_orders
    fully_cancelled = self.update_trade_state(trade, open_order.order_id, order)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/freqtradebot.py", line 1931, in update_trade_state
    trade.update_trade(order_obj, not send_msg)
  File "/freqtrade/freqtrade/persistence/trade_model.py", line 767, in update_trade
    logger.info(f'{order.order_type.upper()}_{payment} has been fulfilled for {self}.')
                   ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'upper'
2023-12-24 12:19:49,027 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2023-12-24 12:19:49,028 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2023-12-24 12:19:49,029 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2023-12-24 12:19:49,036 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': warning, 'status': "1 open trades active.\n\nHandle these trades manually on Bitstamp, or '/start' the bot again and use '/stopentry' to handle open trades gracefully. \n"}
2023-12-24 12:19:49,037 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
2023-12-24 12:19:49,038 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.apiserver ...
2023-12-24 12:19:49,039 - freqtrade.rpc.api_server.webserver - INFO - Stopping API Server
2023-12-24 12:19:49,089 - uvicorn.error - INFO - Shutting down
2023-12-24 12:19:49,090 - uvicorn.error - INFO - connection closed
2023-12-24 12:19:49,091 - uvicorn.error - INFO - connection closed
2023-12-24 12:19:49,092 - freqtrade.rpc.api_server.ws.channel - INFO - Disconnected from channel - WebSocketChannel(0edf6462, ('10.11.0.32', 37450))
2023-12-24 12:19:49,093 - freqtrade.rpc.api_server.ws.channel - INFO - Disconnected from channel - WebSocketChannel(8281a1cf, ('10.11.41.154', 53766))
2023-12-24 12:19:49,191 - uvicorn.error - INFO - Waiting for application shutdown.
2023-12-24 12:19:49,192 - uvicorn.error - INFO - Application shutdown complete.
2023-12-24 12:19:49,194 - uvicorn.error - INFO - Finished server process [1]
2023-12-24 12:19:49,196 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.telegram ...
2023-12-24 12:19:59,098 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Application:SECURITYREASONS:update_fetcher' coro=<Application._update_fetcher() running at /home/ftuser/.local/lib/python3.11/site-packages/telegram/ext/_application.py:1110> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Exception ignored in: <coroutine object Application._update_fetcher at 0x7fd7789024d0>
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.11/site-packages/telegram/ext/_application.py", line 1110, in _update_fetcher
    update = await self.update_queue.get()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/queues.py", line 160, in get
    getter.cancel()  # Just in case getter is not done yet.
    ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 761, in call_soon
    self._check_closed()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 519, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by xmatthias** [comment]
are you sure that the log_responses has been set to true - and that it's in the exchange section of the config?

i'm kindof missing it's output - which i'd expect to be right before `2023-12-24 12:19:49,024 - freqtrade.commands.trade_commands ` (or 1-2 lines prior to that).

> Yes I am aware that Bitstamp is not supported, altough I feel like it should, as it's one of the oldest around, anyway.

It's a question of resources. Actively supporting an exchange can be timeconsuming, depending on how stable it's API is.
You're more than welcome to "adopt" bitstamp if you can make it work ...

This implies
* running the [tests listed in the developer section](https://www.freqtrade.io/en/latest/developer/#implement-a-new-exchange-wip) 
* helping users both in github issues and on discord if they have problems with this particular exchange

As a part of that process - you'll also eventually learn a some about freqtrade internals ... :)

**Comment by treeol** [comment]
> are you sure that the log_responses has been set to true - and that it's in the exchange section of the config?
> 
> i'm kindof missing it's output - which i'd expect to be right before `2023-12-24 12:19:49,024 - freqtrade.commands.trade_commands ` (or 1-2 lines prior to that).

Sorry thought only the errors ones are important, here are the lines prior to that event. 

```
2023-12-24 12:19:47,936 - freqtrade.freqtradebot - INFO - Long signal found: about create a new trade for SECURITYREASONS/USD with stake_amount: 100.0 ...
2023-12-24 12:19:48,007 - freqtrade.exchange.exchange - INFO - API create_order: {'id': '000000000000', 'clientOrderId': None, 'datetime': '2023-12-24T12:19:47.995Z', 'timestamp': 1703420387995, 'lastTradeTimestamp': None, 'status': 'open', 'symbol': 'SECURITYREASONS/USD', 'type': 'limit', 'timeInForce': None, 'postOnly': None, 'side': 'buy', 'price': 0.6182, 'stopPrice': None, 'triggerPrice': None, 'cost': None, 'amount': 161.75994823, 'filled': None, 'remaining': None, 'trades': [], 'fee': None, 'info': {'id': '1698141853028352', 'market': 'SECURITYREASONS/USD', 'datetime': '2023-12-24 12:19:47.995000', 'type': '0', 'amount': '161.75994823', 'price': '0.61820'}, 'average': None, 'fees': [], 'lastUpdateTimestamp': None, 'reduceOnly': None, 'takeProfitPrice': None, 'stopLossPrice': None}
2023-12-24 12:19:48,008 - freqtrade.freqtradebot - INFO - Order 1698141853028352 was created for SECURITYREASONS/USD and status is open.
2023-12-24 12:19:48,090 - freqtrade.wallets - INFO - Wallets synced.
2023-12-24 12:19:48,139 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'trade_id': 1, 'type': entry, 'buy_tag': 'force_entry', 'enter_tag': 'force_entry', 'exchange': 'Bitstamp', 'pair': 'SECURITYREASONS/USD', 'leverage': 1.0, 'direction': 'Long', 'limit': 0.6182, 'open_rate': 0.6182, 'order_type': 'limit', 'stake_amount': 100.0, 'stake_currency': 'USD', 'base_currency': 'SECURITYREASONS', 'fiat_currency': 'USD', 'amount': 161.75994823, 'open_date': datetime.datetime(2023, 12, 24, 12, 19, 48, 9565, tzinfo=datetime.timezone.utc), 'current_rate': 0.6179, 'sub_trade': False}
2023-12-24 12:19:48,992 - freqtrade.exchange.exchange - INFO - API fetch_order: {'id': 'SECURITYREASONS', 'clientOrderId': None, 'datetime': '2023-12-24T12:19:47.000Z', 'timestamp': SECURITYREASONS, 'lastTradeTimestamp': SECURITYREASONS, 'status': 'closed', 'symbol': 'SECURITYREASONS/USD', 'type': None, 'timeInForce': None, 'postOnly': None, 'side': 'buy', 'price': None, 'stopPrice': None, 'triggerPrice': None, 'cost': 99.9870592, 'amount': 161.75994823, 'filled': 161.75994823, 'remaining': 0.0, 'trades': [{'id': '311910415', 'info': {'tid': '311910415', 'price': '0.61812', 'SECURITYREASONS': '161.75994823', 'usd': '99.9870592', 'fee': '0.39995', 'datetime': '2023-12-24 12:19:47.995000', 'type': '2'}, 'timestamp': SECURITYREASONS, 'datetime': '2023-12-24T12:19:47.995Z', 'symbol': 'SECURITYREASONS/USD', 'order': None, 'type': None, 'side': None, 'takerOrMaker': None, 'price': SECURITYREASONS, 'amount': 161.75994823, 'cost': 99.9870592, 'fee': {'cost': 0.39995, 'currency': 'USD'}, 'fees': [{'cost': '0.39995', 'currency': 'USD'}]}], 'fee': {'currency': 'USD', 'cost': 0.39995}, 'info': {'id': 'SECURITYREASONS', 'market': 'SECURITYREASONS/USD', 'transactions': [{'tid': '311910415', 'price': '0.61812', 'SECURITYREASONS': '161.75994823', 'usd': '99.9870592', 'fee': '0.39995', 'datetime': '2023-12-24 12:19:47.995000', 'type': '2'}], 'status': 'Finished', 'amount_remaining': '0.00000000', 'datetime': '2023-12-24 12:19:47', 'type': '0'}, 'average': 0.6181200000004475, 'fees': [{'currency': 'USD', 'cost': 0.39995}], 'lastUpdateTimestamp': None, 'reduceOnly': None, 'takeProfitPrice': None, 'stopLossPrice': None}
2023-12-24 12:19:48,994 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=1, pair=SECURITYREASONS/USD, amount=161.75994824, is_short=False, leverage=1.0, open_rate=0.61820000, open_since=2023-12-24 12:19:48)
2023-12-24 12:19:49,022 - freqtrade.freqtradebot - INFO - Fee for Trade Trade(id=1, pair=SECURITYREASONS/USD, amount=161.75994824, is_short=False, leverage=1.0, open_rate=0.61820000, open_since=2023-12-24 12:19:48) [buy]: 0.39995 USD - rate: 0.00400002
2023-12-24 12:19:49,023 - freqtrade.persistence.trade_model - INFO - Updating trade (id=1) ...
2023-12-24 12:19:49,024 - freqtrade.commands.trade_commands - ERROR - 'NoneType' object has no attribute 'upper'
2023-12-24 12:19:49,025 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 25, in start_trading
    worker.run()
  File "/freqtrade/freqtrade/worker.py", line 75, in run
    state = self._worker(old_state=state)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/worker.py", line 116, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs,
  File "/freqtrade/freqtrade/worker.py", line 147, in _throttle
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/worker.py", line 180, in _process_running
    self.freqtrade.process()
  File "/freqtrade/freqtrade/freqtradebot.py", line 232, in process
    self.manage_open_orders()
  File "/freqtrade/freqtrade/freqtradebot.py", line 1346, in manage_open_orders
    fully_cancelled = self.update_trade_state(trade, open_order.order_id, order)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/freqtradebot.py", line 1931, in update_trade_state
    trade.update_trade(order_obj, not send_msg)
  File "/freqtrade/freqtrade/persistence/trade_model.py", line 767, in update_trade
    logger.info(f'{order.order_type.upper()}_{payment} has been fulfilled for {self}.')
                   ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'upper'
2023-12-24 12:19:49,027 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2023-12-24 12:19:49,028 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2023-12-24 12:19:49,029 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2023-12-24 12:19:49,036 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': warning, 'status': "1 open trades active.\n\nHandle these trades manually on Bitstamp, or '/start' the bot again and use '/stopentry' to handle open trades gracefully. \n"}
2023-12-24 12:19:49,037 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
2023-12-24 12:19:49,038 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.apiserver ...
2023-12-24 12:19:49,039 - freqtrade.rpc.api_server.webserver - INFO - Stopping API Server
2023-12-24 12:19:49,089 - uvicorn.error - INFO - Shutting down
2023-12-24 12:19:49,090 - uvicorn.error - INFO - connection closed
2023-12-24 12:19:49,091 - uvicorn.error - INFO - connection closed
2023-12-24 12:19:49,092 - freqtrade.rpc.api_server.ws.channel - INFO - Disconnected from channel - WebSocketChannel(0edf6462, ('10.11.0.32', 37450))
2023-12-24 12:19:49,093 - freqtrade.rpc.api_server.ws.channel - INFO - Disconnected from channel - WebSocketChannel(8281a1cf, ('10.11.41.154', 53766))
2023-12-24 12:19:49,191 - uvicorn.error - INFO - Waiting for application shutdown.
2023-12-24 12:19:49,192 - uvicorn.error - INFO - Application shutdown complete.
2023-12-24 12:19:49,194 - uvicorn.error - INFO - Finished server process [1]
2023-12-24 12:19:49,196 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.telegram ...
2023-12-24 12:19:59,098 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Application:6932598557:update_fetcher' coro=<Application._update_fetcher() running at /home/ftuser/.local/lib/python3.11/site-packages/telegram/ext/_application.py:1110> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Exception ignored in: <coroutine object Application._update_fetcher at 0x7fd7789024d0>
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.11/site-packages/telegram/ext/_application.py", line 1110, in _update_fetcher
    update = await self.update_queue.get()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/queues.py", line 160, in get
    getter.cancel()  # Just in case getter is not done yet.
    ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 761, in call_soon
    self._check_closed()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 519, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

> > Yes I am aware that Bitstamp is not supported, altough I feel like it should, as it's one of the oldest around, anyway.
> 
> It's a question of resources. Actively supporting an exchange can be timeconsuming, depending on how stable it's API is. You're more than welcome to "adopt" bitstamp if you can make it work ...
> 
> This implies
> 
> * running the [tests listed in the developer section](https://www.freqtrade.io/en/latest/developer/#implement-a-new-exchange-wip)
> * helping users both in github issues and on discord if they have problems with this particular exchange
> 
> As a part of that process - you'll also eventually learn a some about freqtrade internals ... :)

Well true, I probably will as soon as I get more involved into freqtrade. :)

**Comment by xmatthias** [comment]
Well no, then activating `log_responses` wouldn't make sense :laughing: 

The problem is the fact that the fetch_order response does not contain the order type (`"type": None,`) (which i suspected, but needs confirmation, obviously).

From afar, i'd say that the response itself MIGHT contain this in `"type": "0"` - but there's no real guarantee - and i somehow did struggle to actually find "type" means in the bitstamp API.

At any rate - for now, i see this as something that needs fixing at the ccxt level ... but without the documentation reference for what "type" actually refers to, this might be difficult.

Seems like ccxt is simply never setting the order type (https://github.com/ccxt/ccxt/blob/96175dae15ae7fe3d284598cb9955957d9368212/ts/src/bitstamp.ts#L1820) ... which makes this exchange currently one we should put on the blacklist.

**Comment by xmatthias** [comment]
Please repeat your test with the very latest version (make sure it includes the linked commit).

In theory, it should fix your problem - at least if it occurs in exactly this circumstance.
If you're however having problems at this step - i doubt bitstamp will be an easy exchange to use...

**Comment by treeol** [comment]
Oh wow, thank you very much and sorry for the late reply, will try it asap and post the results.

**Comment by treeol** [comment]
> Please repeat your test with the very latest version (make sure it includes the linked commit).
> 
> In theory, it should fix your problem - at least if it occurs in exactly this circumstance. If you're however having problems at this step - i doubt bitstamp will be an easy exchange to use...

I started a new instance with the patch (and the same freqtrade version as stated above), it worked perfectly 🎉

The force entry and exit were executed without any error and it's displaying everything correct till now.

Thank you very much, that truly saved my day!

**Comment by treeol** [comment]
@xmatthias 

Unfortunately, there was another error when an entry signal tried to trigger a trade:

```
2023-12-27 04:10:06,180 - freqtrade.exchange.exchange - INFO - API cancel_order: {'id': 'SECURITYREASONS', 'amount': '4.21528292', 'price': '42.70176', 'type': '0'}
2023-12-27 04:10:06,251 - freqtrade.exchange.exchange - INFO - API fetch_order: {'id': 'SECURITYREASONS', 'clientOrderId': None, 'datetime': '2023-12-27T04:10:06.000Z', 'timestamp': 1703650206000, 'lastTradeTimestamp': None, 'status': 'canceled', 'symbol': 'AVAX/USD', 'type': None, 'timeInForce': None, 'postOnly': None, 'side': 'buy', 'price': None, 'stopPrice': None, 'triggerPrice': None, 'cost': None, 'amount': None, 'filled': None, 'remaining': None, 'trades': [], 'fee': None, 'info': {'id': 'SECURITYREASONS', 'market': 'AVAX/USD', 'transactions': [], 'status': 'Canceled', 'amount_remaining': '4.21528292', 'datetime': '2023-12-27 04:10:06', 'type': '0'}, 'average': None, 'fees': [], 'lastUpdateTimestamp': None, 'reduceOnly': None, 'takeProfitPrice': None, 'stopLossPrice': None}
2023-12-27 04:10:06,252 - freqtrade.freqtradebot - INFO - Buy order cancelled due to timeout for Trade(id=2, pair=AVAX/USD, amount=4.21528293, is_short=False, leverage=1.0, open_rate=42.70176000, open_since=2023-12-27 04:00:06).
2023-12-27 04:10:06,254 - freqtrade.commands.trade_commands - ERROR - must be real number, not NoneType
2023-12-27 04:10:06,255 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 25, in start_trading
    worker.run()
  File "/freqtrade/freqtrade/worker.py", line 75, in run
    state = self._worker(old_state=state)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/worker.py", line 116, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs,
  File "/freqtrade/freqtrade/worker.py", line 147, in _throttle
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/worker.py", line 180, in _process_running
    self.freqtrade.process()
  File "/freqtrade/freqtrade/freqtradebot.py", line 232, in process
    self.manage_open_orders()
  File "/freqtrade/freqtrade/freqtradebot.py", line 1355, in manage_open_orders
    self.handle_cancel_order(
  File "/freqtrade/freqtrade/freqtradebot.py", line 1370, in handle_cancel_order
    self.handle_cancel_enter(trade, order, order_obj, reason)
  File "/freqtrade/freqtrade/freqtradebot.py", line 1550, in handle_cancel_enter
    if isclose(filled_amount, 0.0, abs_tol=constants.MATH_CLOSE_PREC):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: must be real number, not NoneType
2023-12-27 04:10:06,256 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2023-12-27 04:10:06,258 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2023-12-27 04:10:06,259 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
```

//Edit: 

Just entered again manually, worked perfectly fine. 

Looks like error only comes when entering the trade automatically.

**Comment by xmatthias** [comment]
The error will probably happen when an order is canceled (try to place an order "way" off price and wait for the timeout).

This is now a ccxt problem (amount_remaining is simply ignored in the response). Please open an issue against ccxt with the information you see after `API fetch_order:`.
