### ISSUE TITLE
Coinbase advanced trading integration

### ISSUE THREAD

**Issue by mupett** [freqtrade/freqtrade#9606]
## Describe your environment

  * Operating system: docker latest image
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Is Coinbase advanced trading integration implemented?
If I use coinbasepro it ask me for a passprase wich is anymore not requested
If I use coinbase it cannot open the orderbook.

Kind Regards

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

As you failed to fill out the issue template, i'll simply assume you're on an outdated version.

Freqtrade is using ccxt for connection to the exchange. if ccxt supports this - freqtrade will, too, once you update to a recent version.
For information IF ccxt supports this, please ask in appropriate ccxt help channels.

If you think ccxt supports this already, then we'll need 
* a PROPERLY filled out issue template
* Logs which show your actual problem

**Comment by mupett** [comment]
docker images
REPOSITORY                   TAG       IMAGE ID       CREATED       SIZE
freqtradeorg/freqtrade       latest    e85796cec8e5   2 days ago    1.05GB

Operating system: docker latest image based on Linux d4a9f09433ef 5.14.0-391.el9.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Nov 28 20:35:49 UTC 2023 x86_64 GNU/Linux

Python Version: Python 3.11.6 (python -V)

CCXT version: ccxt==4.1.98(pip freeze | grep ccxt)

Freqtrade Version: freqtrade docker-2023.12-dev-d2820278 (freqtrade -V or docker compose run --rm freqtrade -V for Freqtrade running in docker)

-------------------------------------------

023-12-27 17:12:07,808 - freqtrade.exchange.exchange - INFO - Using CCXT 4.1.98
2023-12-27 17:12:07,812 - freqtrade.exchange.exchange - INFO - Using Exchange "Coinbase Pro"
2023-12-27 17:12:08,441 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Coinbasepro'...
2023-12-27 17:12:08,475 - freqtrade.exchange.common - WARNING - get_balances() returned exception: "Could not get balance due to AuthenticationError. Message: coinbasepro requires "password" credential". Retrying still for 4 times.
2023-12-27 17:12:08,575 - freqtrade.exchange.common - WARNING - get_balances() returned exception: "Could not get balance due to AuthenticationError. Message: coinbasepro requires "password" credential". Retrying still for 3 times.
2023-12-27 17:12:08,675 - freqtrade.exchange.common - WARNING - get_balances() returned exception: "Could not get balance due to AuthenticationError. Message: coinbasepro requires "password" credential". Retrying still for 2 times.
2023-12-27 17:12:08,775 - freqtrade.exchange.common - WARNING - get_balances() returned exception: "Could not get balance due to AuthenticationError. Message: coinbasepro requires "password" credential". Retrying still for 1 times.
2023-12-27 17:12:08,876 - freqtrade.exchange.common - WARNING - get_balances() returned exception: "Could not get balance due to AuthenticationError. Message: coinbasepro requires "password" credential". Giving up.
2023-12-27 17:12:08,876 - freqtrade.commands.trade_commands - ERROR - Could not get balance due to AuthenticationError. Message: coinbasepro requires "password" credential
2023-12-27 17:12:08,876 - freqtrade.commands.trade_commands - ERROR - Fatal exception!

OR ----------------------------------------------

2023-12-27 17:11:26,077 - freqtrade.exchange.exchange - INFO - Using CCXT 4.1.98
2023-12-27 17:11:26,083 - freqtrade.exchange.exchange - INFO - Using Exchange "Coinbase"
2023-12-27 17:11:29,990 - freqtrade.commands.trade_commands - ERROR - Orderbook not available for Coinbase.
2023-12-27 17:11:29,991 - freqtrade.commands.trade_commands - ERROR - Fatal exception!

**Comment by xmatthias** [comment]
for Coinbase - the message seems correct / aligned to what ccxt reports (https://github.com/ccxt/ccxt/blob/b7d8b79bcf4f4a832a155c0255d4b8a8ba23c0ad/ts/src/coinbase.ts#L75).

If that's correct or not is beyond me - but usually it is / will be.

I also don't think you can use them interchangably, you'll EITHER be using coinbase, or coinbasePro (independent of freqtrade) ...
so, coinbase != coinbasePro iirc - with coinbase using `https://api.coinbase.com` as API base - and coinbasePro using `https://api.pro.coinbase.com`.

---

The error on coinbasePro seems to come from ccxt - and seems intentional (assuming it's caused by these settings):
https://github.com/ccxt/ccxt/blob/b7d8b79bcf4f4a832a155c0255d4b8a8ba23c0ad/ts/src/coinbasepro.ts#L94-L98

If these are actually required for the actual call to the exchange is not even relevant.
ccxt requires it and actively checks for it, if it's not present, you get an error (the call is never even reaching the exchange, at least as far as i can tell).
(reference: 
https://github.com/ccxt/ccxt/blob/b7d8b79bcf4f4a832a155c0255d4b8a8ba23c0ad/python/ccxt/base/exchange.py#L3503C32-L3512).

concluding - ccxt's coinbasePro implementation will currently require a password credential to work (as well as the apikey 
and secret).
If that's correct - please check with ccxt support channels. Feel free to link and/or quote issue / comment, so people assisting you on the ccxt side can have a look at this comment.


---

I would also like to highlight that coinbase / coinbasePro are not exchanges we officially support.

It's quite likely that you're the first to run freqtrade on coinbase / coinbasePro.
we have a rough guideline on things to check in the [contributors section of the documentation](https://www.freqtrade.io/en/latest/developer/#implement-a-new-exchange-wip).
While it's probably not complete, it should give you a good idea if the exchange will work for spot trading.

If you encounter _specific_ problems, we're happy to assist up to a certain point - but the expectation for new exchanges is that the user interested is doing the legwork / most of the testing work - which also assumes a somewhat familiarity with python / testing/debugging things in python.

If you're new to python / development - you're almost certainly better of with one of the supported exchanges.

**Comment by mupett** [comment]
Thank you I will ask to cctx channel.

Kind regards

**Comment by mupett** [comment]
Hello,
here is the feedback from Dan:
Hi @mupett the advanced trade endpoints are supported through the coinbase class:

coinbase.fetchOrderBook (BTC/USDT, 3)
2024-01-03T04:04:43.096Z iteration 0 passed in 540 ms

{
  symbol: 'BTC/USDT',
  bids: [
    [ 45227.7, 0.0552517 ],
    [ 45226.88, 0.05525221 ],
    [ 45225.29, 0.22101863 ]
  ],
  asks: [
    [ 45232.04, 0.05524641 ],
    [ 45232.89, 0.04576791 ],
    [ 45232.9, 0.02103489 ]
  ],
  timestamp: 1704254683848,
  datetime: '2024-01-03T04:04:43.848Z'
}
Let me know if you have any other questions

I still get this error:
2024-01-06 09:54:19,946 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2024-01-06 09:54:19,948 - freqtrade.resolvers.exchange_resolver - INFO - No Coinbase specific subclass found. Using the generic class instead.
2024-01-06 09:54:19,949 - freqtrade.exchange.exchange - INFO - Using CCXT 4.2.2
2024-01-06 09:54:19,954 - freqtrade.exchange.exchange - INFO - Using Exchange "Coinbase"
2024-01-06 09:54:23,911 - freqtrade.commands.trade_commands - ERROR - Orderbook not available for Coinbase.
2024-01-06 09:54:23,911 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 24, in start_trading
    worker = Worker(args)
             ^^^^^^^^^^^^
  File "/freqtrade/freqtrade/worker.py", line 37, in __init__
    self._init(False)
  File "/freqtrade/freqtrade/worker.py", line 53, in _init
    self.freqtrade = FreqtradeBot(self._config)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/freqtradebot.py", line 76, in __init__
    self.exchange = ExchangeResolver.load_exchange(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 49, in load_exchange
    exchange = Exchange(config, validate=validate, exchange_config=exchange_config,)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/exchange/exchange.py", line 189, in __init__
    self.validate_config(config)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 233, in validate_config
    self.validate_pricing(config['exit_pricing'])
  File "/freqtrade/freqtrade/exchange/exchange.py", line 633, in validate_pricing
    raise OperationalException(f'Orderbook not available for {self.name}.')
freqtrade.exceptions.OperationalException: Orderbook not available for Coinbase.

Any clue to solve this?

Regards

**Comment by xmatthias** [comment]
he will be using coinbasepro, not coinbase - where orderbook is available :) 

Aside from that - we're talking l2 orderbook - which is a different ccxt method than fetchOrderBook.

**Comment by mupett** [comment]
I think my question to them was clear. coinbasepro is not going to working anymore as they change to other platform/apis.
Passprhrase is not asked anymore.

Regards

**Comment by xmatthias** [comment]
Let me repeat what i said above.
this is not a freqtrade issue - but a ccxt issue.

coinbase does not have the orderbook method required (l2 orderbook) -though you can disable orderbook and revert to ticker pricing - which can however be slightly delayed in my experience.

coinbasepro does have L2 orderbook - but apparently (what you claim, however without real source), ccxt is implementing it wrongly and is requiring a passphrase (as pointed out in the above linked code-lines in ccxt).

**Comment by mupett** [comment]
https://github.com/ccxt/ccxt/issues/20583

**Comment by xmatthias** [comment]
As mentioned above - coinbase does NOT have the required method for orderbook pricing.

you can check this yourself via `freqtrade list-exchanges`.

orderbook is however optional, and you can change the configuration to NOT use the orderbook to price your orders / check for current prices - though this can have drawbacks in the speed you get prices.


---

I'd however advise you to stick to supported exchanges.

we have a rough guideline on things to check in the [contributors section of the documentation](https://www.freqtrade.io/en/latest/developer/#implement-a-new-exchange-wip).
While it's probably not complete, it should give you a good idea if the exchange will work for spot trading.

If you encounter specific problems, we're happy to assist up to a certain point - but the expectation for new exchanges is that the user interested is doing the legwork / most of the testing work - which also assumes a somewhat familiarity with python / testing/debugging things in python.

If you're new to python / development - you're almost certainly better of with one of the supported exchanges.

**Comment by mupett** [comment]
ok I'll try: "orderbook is however optional, and you can change the configuration to NOT use the orderbook to price your orders / check for current prices - though this can have drawbacks in the speed you get prices."

thanks and regards
