### ISSUE TITLE
Operational exception with new config file created

### ISSUE THREAD

**Issue by spidersecurity** [freqtrade/freqtrade#9641]
## Describe your environment

  * Operating system: Ubuntu 22.04
  * Python Version: Docker version 24.0.5, build 24.0.5-0ubuntu1~22.04.1
  * CCXT version: 
  * Freqtrade Version: 2023.12
  
## ISSUE
OperationalException as: _Config file "confignew.json" not found! Please create a config file or check whether it exists_. I have created a new config file under user_data directory named confignew.json followed by executing the below two commands (ran from user_data directory):

1. docker-compose up -d (load the default config.json)
2. docker-compose run --rm freqtrade trade -s mynewstrategy -c ./confignew.json

Attaching the screenshot of user_data directory.
<img width="1349" alt="Screenshot 2024-01-05 at 23 31 52" src="https://github.com/freqtrade/freqtrade/assets/3382846/918ccda4-d6e9-4211-bb5b-8712244de35e">

**Comment by stash86** [comment]
Have you mount the folder to the docker? Copy your docker-compose.yml here

**Comment by stash86** [comment]
Docker will always assume it's running from the main folder. So your command should be `-c user_data/confignew.json`

**Comment by spidersecurity** [comment]
> Have you mount the folder to the docker? Copy your docker-compose.yml here
Here's the docker-compose.yml:

```
services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # # Enable GPU Image and GPU Resources (only relevant for freqAI)
    # # Make sure to uncomment the whole deploy section
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/stable/rest-api/ documentation
    # for more information.
    ports:
      - "127.0.0.1:8080:8080"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy SampleStrategy
```

**Comment by spidersecurity** [comment]
@stash86 I've already tried with -c user_data/confignew.json, but the error exists. Pls note: the error is same even if I select -c user_data/config.json, but "docker-compose up" works okay.

**Comment by stash86** [comment]
Copy the full logs when you run the command

**Comment by spidersecurity** [comment]
> Copy the full logs when you run the command

Creating network "ft_userdata_default" with the default driver
Creating ft_userdata_freqtrade_run ... done
2024-01-05 22:49:32,524 - freqtrade - INFO - freqtrade 2023.12
2024-01-05 22:49:33,132 - freqtrade.worker - INFO - Starting worker 2023.12
2024-01-05 22:49:33,133 - freqtrade.configuration.load_config - INFO - Using config: ./confignew.json ...
2024-01-05 22:49:33,133 - freqtrade.commands.trade_commands - ERROR - Config file "confignew.json" not found! Please create a config file or check whether it exists.
2024-01-05 22:49:33,134 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/configuration/load_config.py", line 61, in load_config_file
    with Path(path).open() if path != '-' else sys.stdin as file:
         ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'confignew.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 24, in start_trading
    worker = Worker(args)
             ^^^^^^^^^^^^
  File "/freqtrade/freqtrade/worker.py", line 37, in __init__
    self._init(False)
  File "/freqtrade/freqtrade/worker.py", line 50, in _init
    self._config = Configuration(self._args, None).get_config()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/configuration/configuration.py", line 42, in get_config
    self.config = self.load_config()
                  ^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/configuration/configuration.py", line 68, in load_config
    config: Config = load_from_files(self.args.get("config", []))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/configuration/load_config.py", line 102, in load_from_files
    config_tmp = load_config_file(str(file))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/configuration/load_config.py", line 64, in load_config_file
    raise OperationalException(
freqtrade.exceptions.OperationalException: Config file "confignew.json" not found! Please create a config file or check whether it exists.

**Comment by stash86** [comment]
And the logs if you use my suggestion?

**Comment by spidersecurity** [comment]
> use my suggestion

Creating ft_userdata_freqtrade_run ... done
2024-01-05 22:54:52,188 - freqtrade - INFO - freqtrade 2023.12
2024-01-05 22:54:52,791 - freqtrade.worker - INFO - Starting worker 2023.12
2024-01-05 22:54:52,792 - freqtrade.configuration.load_config - INFO - Using config: user_data/comfignew.json ...
2024-01-05 22:54:52,793 - freqtrade.commands.trade_commands - ERROR - Config file "user_data/comfignew.json" not found! Please create a config file or check whether it exists.
2024-01-05 22:54:52,793 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/configuration/load_config.py", line 61, in load_config_file
    with Path(path).open() if path != '-' else sys.stdin as file:
         ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'user_data/comfignew.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 24, in start_trading
    worker = Worker(args)
             ^^^^^^^^^^^^
  File "/freqtrade/freqtrade/worker.py", line 37, in __init__
    self._init(False)
  File "/freqtrade/freqtrade/worker.py", line 50, in _init
    self._config = Configuration(self._args, None).get_config()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/configuration/configuration.py", line 42, in get_config
    self.config = self.load_config()
                  ^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/configuration/configuration.py", line 68, in load_config
    config: Config = load_from_files(self.args.get("config", []))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/configuration/load_config.py", line 102, in load_from_files
    config_tmp = load_config_file(str(file))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/configuration/load_config.py", line 64, in load_config_file
    raise OperationalException(
freqtrade.exceptions.OperationalException: Config file "user_data/comfignew.json" not found! Please create a config file or check whether it exists.

**Comment by stash86** [comment]
You have typo there on the config name

**Comment by spidersecurity** [comment]
huhhhhh! yess. Sorry about that!! I guess my brain isn't working correctly!!

**Comment by spidersecurity** [comment]
Thanks @stash86. closing this thread!
