### ISSUE TITLE
Freqtrade Futures: No pairs in whitelist

### ISSUE THREAD

**Issue by mpaya5** [freqtrade/freqtrade#9676]
## Describe your environment

  * Operating system: ____ python:3.10.10-slim-bullseye (Dockerfile)
  * Python Version: _____ 3.10.10
  * CCXT version: _____ 3.0.37
  * Freqtrade Version: ____ freqtrade 2023.4.dev

## Describe the problem:

I am trying to run Freqtrade with Futures in Binance. But whenever I run a command to try the backtesting I receive the same error: `2024-01-12 12:43:56,070 - freqtrade.rpc.api_server.api_backtest - ERROR - Backtesting caused an error: No pair in whitelist.`

### Steps to reproduce:
I have added a Log to show the command the backtesting is using when trying to run the backtest:
`freqtrade download-data  --config /user_data/config.json --pairs BTC/USDT --timerange 20231130-20240112 -t 5m`
  
### Observed Results:

  * What happened?
  I received an error:
  ```
  2024-01-12 12:43:56,070 - freqtrade.rpc.api_server.api_backtest - ERROR - Backtesting caused an error: No pair in whitelist.Traceback (most recent call last):  File "/freqtrade/freqtrade/rpc/api_server/api_backtest.py", line 99, in run_backtest    ApiServer._bt['bt'] = Backtesting(btconfig)  File "/freqtrade/freqtrade/optimize/backtesting.py", line 132, in __init__    raise OperationalException("No pair in whitelist.")freqtrade.exceptions.OperationalException: No pair in whitelist.
  ```
  * What did you expect to happen?
  I was waiting to receive the results of the backtesting correctly.

### Relevant code exceptions or logs

This is my config.json (without relevant information):
```
{
  "api_server": {
    "CORS_origins": [
      "{SOME URL}"
    ],
    "enable_openapi": false,
    "enabled": true,
    "jwt_secret_key": "1111111111111111",
    "listen_ip_address": "0.0.0.0",
    "listen_port": 111111111111,
    "password": "111111111111111",
    "username": "111111111111",
    "verbosity": "error",
    "ws_token": "111111111111111"
  },
  "bot_name": "freqtrade",
  "cancel_open_orders_on_exit": false,
  "dry_run": true,
  "dry_run_wallet": 10000,
  "edge": {
    "allowed_risk": 0.01,
    "calculate_since_number_of_days": 7,
    "enabled": false,
    "max_trade_duration_minute": 1440,
    "min_trade_number": 10,
    "minimum_expectancy": 0.2,
    "minimum_winrate": 0.6,
    "process_throttle_secs": 3600,
    "remove_pumps": false,
    "stoploss_range_max": -0.1,
    "stoploss_range_min": -0.01,
    "stoploss_range_step": -0.01
  },
  "entry_pricing": {
    "check_depth_of_market": {
      "bids_to_ask_delta": 1,
      "enabled": false
    },
    "order_book_top": 1,
    "price_last_balance": 0,
    "price_side": "same",
    "use_order_book": true
  },
  "exchange": {
    "ccxt_async_config": {
      "enableRateLimit": true,
      "options": {
        "defaultType": "future"
      },
      "rateLimit": 200
    },
    "ccxt_config": {
      "enableRateLimit": true,
      "options": {
        "defaultType": "future"
      }
    },
    "key": "",
    "name": "binance",
    "pair_blacklist": [
      "BNB/.*"
    ],
    "pair_whitelist": [
      "BTC/USDT",
      "ETH/USDT",
      "BNB/USDT",
      "XRP/USDT",
      "DOGE/USDT",
      "ADA/USDT",
      "SOL/USDT",
      "TRX/USDT",
      "LTC/USDT",
      "MATIC/USDT",
      "DOT/USDT",
      "BCH/USDT",
      "SHIB/USDT",
      "AVAX/USDT",
      "XLM/USDT",
      "LINK/USDT",
      "UNI/USDT",
      "ATOM/USDT",
      "XMR/USDT",
      "ARB/USDT"
    ],
    "password": "",
    "secret": ""
  },
  "exit_pricing": {
    "order_book_top": 1,
    "price_side": "same",
    "use_order_book": true
  },
  "fiat_display_currency": "USD",
  "force_entry_enable": false,
  "initial_state": "running",
  "internals": {
    "process_throttle_secs": 5
  },
  "margin_mode": "isolated",
  "max_open_trades": -1,
  "pairlists": [
    {
      "method": "StaticPairList"
    }
  ],
  "stake_amount": 100,
  "stake_currency": "USDT",
  "strategy_path": "/user_data/",
  "telegram": {
    "chat_id": "",
    "enabled": false,
    "token": ""
  },
  "tradable_balance_ratio": 0.99,
  "trading_mode": "futures",
  "unfilledtimeout": {
    "entry": 10,
    "exit": 10,
    "exit_timeout_count": 0,
    "unit": "minutes"
  },
  "user_data_dir": "/user_data/"
}

```

For that config.json I decided to use the config.json described [here](https://github.com/freqtrade/freqtrade-strategies/tree/main/user_data/strategies/futures) and for the strategy I copy/pasted the [FReinforcedStrategy.py](https://github.com/freqtrade/freqtrade-strategies/blob/main/user_data/strategies/futures/FReinforcedStrategy.py) 

The full log when the backtest start to run is the following:
  ```
2024-01-12 12:43:19,948 - freqtrade.rpc.api_server.api_backtest - INFO - COMMAND TO USE: freqtrade download-data  --config /user_data//config.json --pairs BTC/USDT --timerange 20231130-20240112 -t 5m
2024-01-12 12:43:23,725 - freqtrade - INFO - freqtrade 2023.4.dev
2024-01-12 12:43:23,725 - freqtrade.configuration.load_config - INFO - Using config: /user_data//config.json ...
2024-01-12 12:43:23,731 - freqtrade.loggers - INFO - Verbosity set to 0
2024-01-12 12:43:23,731 - freqtrade.configuration.configuration - INFO - Parameter --timerange detected: 20231130-20240112 ...
2024-01-12 12:43:24,900 - freqtrade.configuration.configuration - INFO - Using user-data directory: /user_data ...
2024-01-12 12:43:24,904 - freqtrade.configuration.configuration - INFO - Using data directory: /user_data/data/binance ...
2024-01-12 12:43:24,905 - freqtrade.configuration.configuration - INFO - Using pairs ['BTC/USDT']
2024-01-12 12:43:24,906 - freqtrade.configuration.configuration - INFO - timeframes --timeframes: ['5m']
2024-01-12 12:43:24,907 - freqtrade.configuration.configuration - INFO - Filter trades by timerange: 20231130-20240112
2024-01-12 12:43:24,909 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2024-01-12 12:43:24,923 - freqtrade.exchange.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2024-01-12 12:43:24,923 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2024-01-12 12:43:24,932 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2024-01-12 12:43:24,932 - freqtrade.exchange.exchange - INFO - Using CCXT 3.0.37
2024-01-12 12:43:24,932 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'future'}, 'enableRateLimit': True}
2024-01-12 12:43:24,946 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'future'}, 'enableRateLimit': True, 'rateLimit': 200}
2024-01-12 12:43:24,959 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2024-01-12 12:43:24,959 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2024-01-12 12:43:24,959 - freqtrade.exchange.exchange - INFO - Markets were not loaded. Loading them now..
2024-01-12 12:43:30,807 - freqtrade.commands.data_commands - INFO - About to download pairs: ['BTC/USDT'], intervals: ['5m'] to /user_data/data/binance
2024-01-12 12:43:30,813 - freqtrade.data.history.history_utils - INFO - Downloading pair BTC/USDT, interval 5m.
2024-01-12 12:43:30,816 - freqtrade.data.history.history_utils - INFO - (1/1) - Download history data for "BTC/USDT", 5m, futures and store in /user_data/data/binance. From 2023-11-30T00:00:00 to 2024-01-12T00:00:00
2024-01-12 12:43:44,796 - freqtrade.exchange.exchange - INFO - Downloaded data for BTC/USDT with length 12537.
2024-01-12 12:43:44,916 - freqtrade.data.history.history_utils - INFO - (1/1) - Download history data for "BTC/USDT", 8h, funding_rate and store in /user_data/data/binance. From 2023-11-30T00:00:00 to 2024-01-12T00:00:00
2024-01-12 12:43:46,660 - freqtrade.exchange.exchange - INFO - Downloaded data for BTC/USDT with length 131.
2024-01-12 12:43:46,691 - freqtrade.data.history.history_utils - INFO - (1/1) - Download history data for "BTC/USDT", 8h, mark and store in /user_data/data/binance. From 2023-11-30T00:00:00 to 2024-01-12T00:00:00
2024-01-12 12:43:48,415 - freqtrade.exchange.exchange - INFO - Downloaded data for BTC/USDT with length 131.
2024-01-12 12:43:49,153 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy FReinforcedStrategy from '/user_data/strategies/FReinforcedStrategy.py'...
2024-01-12 12:43:49,156 - freqtrade.strategy.hyper - INFO - Found no parameter file.
2024-01-12 12:43:49,157 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 5m.
2024-01-12 12:43:49,158 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2024-01-12 12:43:49,159 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 10000.0.
2024-01-12 12:43:49,160 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}.
2024-01-12 12:43:49,160 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'max_open_trades' with value in config file: -1.0.
2024-01-12 12:43:49,161 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'60': 0.075, '30': 0.1, '0': 0.05}
2024-01-12 12:43:49,161 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 5m
2024-01-12 12:43:49,161 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.05
2024-01-12 12:43:49,161 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2024-01-12 12:43:49,162 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2024-01-12 12:43:49,162 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2024-01-12 12:43:49,162 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2024-01-12 12:43:49,162 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: True
2024-01-12 12:43:49,162 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'entry': 'limit', 'exit': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False, 'stoploss_on_exchange_interval': 60}
2024-01-12 12:43:49,163 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'entry': 'GTC', 'exit': 'GTC'}
2024-01-12 12:43:49,163 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2024-01-12 12:43:49,163 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 10000.0
2024-01-12 12:43:49,163 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2024-01-12 12:43:49,164 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 14
2024-01-12 12:43:49,164 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}
2024-01-12 12:43:49,164 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_exit_signal: True
2024-01-12 12:43:49,164 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_only: False
2024-01-12 12:43:49,165 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_entry_signal: False
2024-01-12 12:43:49,165 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_offset: 0.0
2024-01-12 12:43:49,165 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2024-01-12 12:43:49,165 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2024-01-12 12:43:49,165 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: False
2024-01-12 12:43:49,166 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1
2024-01-12 12:43:49,166 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_open_trades: -1.0
2024-01-12 12:43:49,166 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2024-01-12 12:43:49,186 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2024-01-12 12:43:49,186 - freqtrade.exchange.exchange - INFO - Using CCXT 3.0.37
2024-01-12 12:43:49,187 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'future'}, 'enableRateLimit': True}
2024-01-12 12:43:49,200 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'future'}, 'enableRateLimit': True, 'rateLimit': 200}
2024-01-12 12:43:49,213 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2024-01-12 12:43:56,015 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2024-01-12 12:43:56,035 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy FReinforcedStrategy from '/user_data/strategies/FReinforcedStrategy.py'...
2024-01-12 12:43:56,036 - freqtrade.strategy.hyper - INFO - Found no parameter file.
2024-01-12 12:43:56,037 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'minimal_roi' with value in config file: {'60': 0.075, '30': 0.1, '0': 0.05}.
2024-01-12 12:43:56,037 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 5m.
2024-01-12 12:43:56,037 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stoploss' with value in config file: -0.05.
2024-01-12 12:43:56,037 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'trailing_stop' with value in config file: False.
2024-01-12 12:43:56,037 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'trailing_stop_positive_offset' with value in config file: 0.0.
2024-01-12 12:43:56,037 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'trailing_only_offset_is_reached' with value in config file: False.
2024-01-12 12:43:56,037 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'use_custom_stoploss' with value in config file: False.
2024-01-12 12:43:56,037 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'process_only_new_candles' with value in config file: True.
2024-01-12 12:43:56,037 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'order_types' with value in config file: {'entry': 'limit', 'exit': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False, 'stoploss_on_exchange_interval': 60, 'emergency_exit': 'market'}.
2024-01-12 12:43:56,037 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'order_time_in_force' with value in config file: {'entry': 'GTC', 'exit': 'GTC'}.
2024-01-12 12:43:56,037 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2024-01-12 12:43:56,037 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 10000.0.
2024-01-12 12:43:56,037 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'protections' with value in config file: [].
2024-01-12 12:43:56,037 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'startup_candle_count' with value in config file: 14.
2024-01-12 12:43:56,038 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}.
2024-01-12 12:43:56,038 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'use_exit_signal' with value in config file: True.
2024-01-12 12:43:56,038 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'exit_profit_only' with value in config file: False.
2024-01-12 12:43:56,038 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ignore_roi_if_entry_signal' with value in config file: False.
2024-01-12 12:43:56,038 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'exit_profit_offset' with value in config file: 0.0.
2024-01-12 12:43:56,038 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'disable_dataframe_checks' with value in config file: False.
2024-01-12 12:43:56,038 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ignore_buying_expired_candle_after' with value in config file: 0.
2024-01-12 12:43:56,038 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'position_adjustment_enable' with value in config file: False.
2024-01-12 12:43:56,038 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'max_entry_position_adjustment' with value in config file: -1.
2024-01-12 12:43:56,038 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'max_open_trades' with value in config file: -1.0.
2024-01-12 12:43:56,038 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'60': 0.075, '30': 0.1, '0': 0.05}
2024-01-12 12:43:56,038 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 5m
2024-01-12 12:43:56,038 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.05
2024-01-12 12:43:56,038 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2024-01-12 12:43:56,038 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2024-01-12 12:43:56,038 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2024-01-12 12:43:56,039 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2024-01-12 12:43:56,039 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: True
2024-01-12 12:43:56,039 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'entry': 'limit', 'exit': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False, 'stoploss_on_exchange_interval': 60, 'emergency_exit': 'market'}
2024-01-12 12:43:56,039 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'entry': 'GTC', 'exit': 'GTC'}
2024-01-12 12:43:56,039 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2024-01-12 12:43:56,039 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 10000.0
2024-01-12 12:43:56,039 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2024-01-12 12:43:56,039 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 14
2024-01-12 12:43:56,039 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}
2024-01-12 12:43:56,039 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_exit_signal: True
2024-01-12 12:43:56,039 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_only: False
2024-01-12 12:43:56,039 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_entry_signal: False
2024-01-12 12:43:56,040 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_offset: 0.0
2024-01-12 12:43:56,040 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2024-01-12 12:43:56,041 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2024-01-12 12:43:56,041 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: False
2024-01-12 12:43:56,041 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1
2024-01-12 12:43:56,041 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_open_trades: -1.0
2024-01-12 12:43:56,041 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2024-01-12 12:43:56,059 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from '/freqtrade/freqtrade/plugins/pairlist/StaticPairList.py'...
2024-01-12 12:43:56,070 - freqtrade.rpc.api_server.api_backtest - ERROR - Backtesting caused an error: No pair in whitelist.
Traceback (most recent call last):
  File "/freqtrade/freqtrade/rpc/api_server/api_backtest.py", line 99, in run_backtest
    ApiServer._bt['bt'] = Backtesting(btconfig)
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 132, in __init__
    raise OperationalException("No pair in whitelist.")
freqtrade.exceptions.OperationalException: No pair in whitelist.

  ```

**Comment by mpaya5** [comment]
Even I tried to use `BTC/USDT:USDT` as mentioned in [Pair naming](https://www.freqtrade.io/en/stable/bot-basics/#pair-naming), changing my config.json:
```
2024-01-12 13:23:03,298 - freqtrade.rpc.api_server.api_backtest - INFO - COMMAND TO USE: freqtrade download-data  --config /user_data/config.json --pairs BTC/USDT:USDT --timerange 20231130-20240101 -t 5m
2024-01-12 13:23:06,841 - freqtrade - INFO - freqtrade 2023.4.dev
2024-01-12 13:23:06,841 - freqtrade.configuration.load_config - INFO - Using config: /user_data/config.json ...
2024-01-12 13:23:06,843 - freqtrade.loggers - INFO - Verbosity set to 0
2024-01-12 13:23:06,844 - freqtrade.configuration.configuration - INFO - Parameter --timerange detected: 20231130-20240101 ...
2024-01-12 13:23:08,093 - freqtrade.configuration.configuration - INFO - Using user-data directory: /user_data ...
2024-01-12 13:23:08,096 - freqtrade.configuration.configuration - INFO - Using data directory: /user_data/data/binance ...
2024-01-12 13:23:08,096 - freqtrade.configuration.configuration - INFO - Using pairs ['BTC/USDT:USDT']
2024-01-12 13:23:08,097 - freqtrade.configuration.configuration - INFO - timeframes --timeframes: ['5m']
2024-01-12 13:23:08,097 - freqtrade.configuration.configuration - INFO - Filter trades by timerange: 20231130-20240101
2024-01-12 13:23:08,098 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2024-01-12 13:23:08,111 - freqtrade.exchange.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2024-01-12 13:23:08,111 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2024-01-12 13:23:08,118 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2024-01-12 13:23:08,118 - freqtrade.exchange.exchange - INFO - Using CCXT 3.0.37
2024-01-12 13:23:08,119 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'future'}, 'enableRateLimit': True}
2024-01-12 13:23:08,132 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'future'}, 'enableRateLimit': True, 'rateLimit': 200}
2024-01-12 13:23:08,144 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2024-01-12 13:23:08,144 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2024-01-12 13:23:08,144 - freqtrade.exchange.exchange - INFO - Markets were not loaded. Loading them now..
2024-01-12 13:23:15,093 - freqtrade.commands.data_commands - INFO - About to download pairs: ['BTC/USDT:USDT'], intervals: ['5m'] to /user_data/data/binance
2024-01-12 13:23:15,127 - freqtrade.data.history.history_utils - INFO - Downloading pair BTC/USDT:USDT, interval 5m.
2024-01-12 13:23:15,132 - freqtrade.data.history.history_utils - INFO - (1/1) - Download history data for "BTC/USDT:USDT", 5m, futures and store in /user_data/data/binance. From 2023-11-30T00:00:00 to 2024-01-01T00:00:00
2024-01-12 13:23:26,133 - freqtrade.exchange.exchange - INFO - Downloaded data for BTC/USDT:USDT with length 10000.
2024-01-12 13:23:26,224 - freqtrade.data.history.history_utils - INFO - (1/1) - Download history data for "BTC/USDT:USDT", 8h, funding_rate and store in /user_data/data/binance. From 2023-11-30T00:00:00 to 2024-01-01T00:00:00
2024-01-12 13:23:27,962 - freqtrade.exchange.exchange - INFO - Downloaded data for BTC/USDT:USDT with length 131.
2024-01-12 13:23:28,020 - freqtrade.data.history.history_utils - INFO - (1/1) - Download history data for "BTC/USDT:USDT", 8h, mark and store in /user_data/data/binance. From 2023-11-30T00:00:00 to 2024-01-01T00:00:00
2024-01-12 13:23:29,753 - freqtrade.exchange.exchange - INFO - Downloaded data for BTC/USDT:USDT with length 131.
2024-01-12 13:23:30,488 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy FReinforcedStrategy from '/user_data/strategies/FReinforcedStrategy.py'...
2024-01-12 13:23:30,492 - freqtrade.strategy.hyper - INFO - Found no parameter file.
2024-01-12 13:23:30,494 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 5m.
2024-01-12 13:23:30,495 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2024-01-12 13:23:30,497 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 10000.0.
2024-01-12 13:23:30,497 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}.
2024-01-12 13:23:30,499 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'max_open_trades' with value in config file: -1.0.
2024-01-12 13:23:30,499 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'60': 0.075, '30': 0.1, '0': 0.05}
2024-01-12 13:23:30,500 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 5m
2024-01-12 13:23:30,501 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.05
2024-01-12 13:23:30,501 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2024-01-12 13:23:30,502 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2024-01-12 13:23:30,503 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2024-01-12 13:23:30,504 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2024-01-12 13:23:30,504 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: True
2024-01-12 13:23:30,505 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'entry': 'limit', 'exit': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False, 'stoploss_on_exchange_interval': 60}
2024-01-12 13:23:30,505 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'entry': 'GTC', 'exit': 'GTC'}
2024-01-12 13:23:30,505 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2024-01-12 13:23:30,507 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 10000.0
2024-01-12 13:23:30,507 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2024-01-12 13:23:30,508 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 14
2024-01-12 13:23:30,508 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}
2024-01-12 13:23:30,510 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_exit_signal: True
2024-01-12 13:23:30,510 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_only: False
2024-01-12 13:23:30,511 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_entry_signal: False
2024-01-12 13:23:30,511 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_offset: 0.0
2024-01-12 13:23:30,513 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2024-01-12 13:23:30,513 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2024-01-12 13:23:30,515 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: False
2024-01-12 13:23:30,515 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1
2024-01-12 13:23:30,517 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_open_trades: -1.0
2024-01-12 13:23:30,518 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2024-01-12 13:23:30,539 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2024-01-12 13:23:30,539 - freqtrade.exchange.exchange - INFO - Using CCXT 3.0.37
2024-01-12 13:23:30,540 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'future'}, 'enableRateLimit': True}
2024-01-12 13:23:30,564 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'future'}, 'enableRateLimit': True, 'rateLimit': 200}
2024-01-12 13:23:30,579 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2024-01-12 13:23:37,518 - freqtrade.rpc.api_server.api_backtest - ERROR - Backtesting caused an error: Pair BTC/USDTUSDT is not available on Binance futures. Please remove BTC/USDTUSDT from your whitelist.
Traceback (most recent call last):
  File "/freqtrade/freqtrade/rpc/api_server/api_backtest.py", line 99, in run_backtest
    ApiServer._bt['bt'] = Backtesting(btconfig)
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 90, in __init__
    self.exchange = ExchangeResolver.load_exchange(
  File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 34, in load_exchange
    exchange = ExchangeResolver._load_exchange(
  File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 60, in _load_exchange
    exchange = ex_class(**kwargs)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 186, in __init__
    self.validate_config(config)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 221, in validate_config
    self.validate_pairs(config['exchange']['pair_whitelist'])
  File "/freqtrade/freqtrade/exchange/exchange.py", line 547, in validate_pairs
    raise OperationalException(
freqtrade.exceptions.OperationalException: Pair BTC/USDTUSDT is not available on Binance futures. Please remove BTC/USDTUSDT from your whitelist.
```

**Comment by xmatthias** [comment]
Your pairs are spot pairs - not futures pairs - and in your second attempt - it's resolving to BTC/USDTUSDT - which is clearly not a pair, either.


`--pairs BTC/USDT:USDT` does work for me just fine.

It appears to be an environment / terminal problem. it's removing the `:`, then that's terminal-specific - and you should be able to get around that by either using `BTC/USDT\:USDT` - or quotes (`"BTC/USDT:USDT"` (one pair of quotes per pair).

I'd however recommend to use the configuration for pair configuration - where such escaping problems are not really a thing.


---

You're also on an old, unsupported version - so i'd strongly suggest to update to the latest version as we only support the current release and develop version.
