### ISSUE TITLE
No module named 'datasieve'

### ISSUE THREAD

**Issue by jonny190** [freqtrade/freqtrade#9696]
## Describe your environment

  * Operating system: Ubuntu server 
  * Python Version: 3.11.6
  * CCXT version: 4.1.98
  * Freqtrade Version: 2023.12
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

When trying to use the FreqAI it fails to start from the example

### Steps to reproduce:

  1.  freqtrade trade --config config_examples/config_freqai.example.json --strategy FreqaiExampleStrategy --freqaimodel LightGBMRegressor --strategy-path freqtrade/templates

  
### Observed Results:

  * What happened?
ModuleNotFoundError: No module named 'datasieve'
`
  * What did you expect to happen?
  * Unsure as never used it before

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  2024-01-17 20:09:28,476 - freqtrade.plugins.pairlistmanager - INFO - Whitelist with 2 pairs: ['1INCH/USDT:USDT', 'ALGO/USDT:USDT']
2024-01-17 20:09:28,497 - freqtrade.commands.trade_commands - ERROR - No module named 'datasieve'
2024-01-17 20:09:28,497 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 24, in start_trading
    worker = Worker(args)
             ^^^^^^^^^^^^
  File "/freqtrade/freqtrade/worker.py", line 37, in __init__
    self._init(False)
  File "/freqtrade/freqtrade/worker.py", line 53, in _init
    self.freqtrade = FreqtradeBot(self._config)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/freqtradebot.py", line 140, in __init__
    self.strategy.ft_bot_start()
  File "/freqtrade/freqtrade/strategy/interface.py", line 187, in ft_bot_start
    self.load_freqAI_model()
  File "/freqtrade/freqtrade/strategy/interface.py", line 156, in load_freqAI_model
    from freqtrade.freqai.utils import download_all_data_for_training
  File "/freqtrade/freqtrade/freqai/utils.py", line 17, in <module>
    from freqtrade.freqai.data_drawer import FreqaiDataDrawer
  File "/freqtrade/freqtrade/freqai/data_drawer.py", line 24, in <module>
    from freqtrade.freqai.data_kitchen import FreqaiDataKitchen
  File "/freqtrade/freqtrade/freqai/data_kitchen.py", line 14, in <module>
    from datasieve.pipeline import Pipeline
ModuleNotFoundError: No module named 'datasieve'

  ```

**Comment by xmatthias** [comment]
Sounds a lot like you didn't install the freqai dependencies.

Depending on your install method, this is either
* say **yes** to  "Do you want to install dependencies for freqai" (install script)
* use the `*_freqai` image
* manually install `requirements-freqai.txt` (only if you installed manually without the installation script).

**Comment by jonny190** [comment]
That'll be it, i was using the latest tag rather then a *_freqai tag.

I've reconfigured and all is good
