### ISSUE TITLE
Network error with docker in windows 11

### ISSUE THREAD

**Issue by Javajava1** [freqtrade/freqtrade#9855]
## Describe your environment

  * Operating system: __windows 11__
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: __freqtrade 2024.1__ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:
I followed the“quickstart with docker”  steps .All is right until I used "docker compose up -d"  to start the image. The log shows " ERROR - Unable to initialize markets".

*Explain the problem you have encountered*

### Steps to reproduce:

  1. _Install the docker in windows 11_(including installing wsl and opening the Hyper-V)___
  2. _follow the step__giving in the _“quickstart with docker”.All is right until I used "docker compose up -d"  to start the image _
  3. _____
  
### Observed Results:

  * What happened?
  * freqUI doesn't work
  * What did you expect to happen?
  * I want to use freqUI.

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
2024-02-22 20:58:11 freqtrade  | 2024-02-22 12:58:11,154 - freqtrade - INFO - freqtrade 2024.1
2024-02-22 20:58:11 freqtrade  | 2024-02-22 12:58:11,598 - freqtrade.worker - INFO - Starting worker 2024.1
2024-02-22 20:58:11 freqtrade  | 2024-02-22 12:58:11,598 - freqtrade.configuration.load_config - INFO - Using config: /freqtrade/user_data/config.json ...
2024-02-22 20:58:11 freqtrade  | 2024-02-22 12:58:11,601 - freqtrade.loggers - INFO - Verbosity set to 0
2024-02-22 20:58:11 freqtrade  | 2024-02-22 12:58:11,602 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
2024-02-22 20:58:11 freqtrade  | 2024-02-22 12:58:11,602 - freqtrade.configuration.configuration - INFO - Parameter --db-url detected ...
2024-02-22 20:58:11 freqtrade  | 2024-02-22 12:58:11,603 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2024-02-22 20:58:11 freqtrade  | 2024-02-22 12:58:11,603 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:////freqtrade/user_data/tradesv3.sqlite"
2024-02-22 20:58:11 freqtrade  | 2024-02-22 12:58:11,604 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 3 ...
2024-02-22 20:58:11 freqtrade  | 2024-02-22 12:58:11,643 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2024-02-22 20:58:11 freqtrade  | 2024-02-22 12:58:11,644 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/binance ...
2024-02-22 20:58:11 freqtrade  | 2024-02-22 12:58:11,645 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2024-02-22 20:58:11 freqtrade  | 2024-02-22 12:58:11,652 - freqtrade.exchange.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2024-02-22 20:58:11 freqtrade  | 2024-02-22 12:58:11,653 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2024-02-22 20:58:11 freqtrade  | 2024-02-22 12:58:11,680 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy SampleStrategy from '/freqtrade/user_data/strategies/sample_strategy.py'...
2024-02-22 20:58:11 freqtrade  | 2024-02-22 12:58:11,681 - freqtrade.strategy.hyper - INFO - Found no parameter file.
2024-02-22 20:58:11 freqtrade  | 2024-02-22 12:58:11,682 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2024-02-22 20:58:11 freqtrade  | 2024-02-22 12:58:11,682 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 10000.
2024-02-22 20:58:11 freqtrade  | 2024-02-22 12:58:11,683 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}.
2024-02-22 20:58:11 freqtrade  | 2024-02-22 12:58:11,683 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'max_open_trades' with value in config file: 3.
2024-02-22 20:58:11 freqtrade  | 2024-02-22 12:58:11,684 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'60': 0.01, '30': 0.02, '0': 0.04}
2024-02-22 20:58:11 freqtrade  | 2024-02-22 12:58:11,684 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 5m
2024-02-22 20:58:11 freqtrade  | 2024-02-22 12:58:11,685 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.1
2024-02-22 20:58:11 freqtrade  | 2024-02-22 12:58:11,685 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2024-02-22 20:58:11 freqtrade  | 2024-02-22 12:58:11,686 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2024-02-22 20:58:11 freqtrade  | 2024-02-22 12:58:11,686 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2024-02-22 20:58:11 freqtrade  | 2024-02-22 12:58:11,687 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2024-02-22 20:58:11 freqtrade  | 2024-02-22 12:58:11,687 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: True
2024-02-22 20:58:11 freqtrade  | 2024-02-22 12:58:11,688 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'entry': 'limit', 'exit': 'limit', 'stoploss': 'market', 'stoploss_on_exchange': False}
2024-02-22 20:58:11 freqtrade  | 2024-02-22 12:58:11,688 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'entry': 'GTC', 'exit': 'GTC'}
2024-02-22 20:58:11 freqtrade  | 2024-02-22 12:58:11,688 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2024-02-22 20:58:11 freqtrade  | 2024-02-22 12:58:11,689 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 10000
2024-02-22 20:58:11 freqtrade  | 2024-02-22 12:58:11,689 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2024-02-22 20:58:11 freqtrade  | 2024-02-22 12:58:11,690 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 200
2024-02-22 20:58:11 freqtrade  | 2024-02-22 12:58:11,690 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}
2024-02-22 20:58:11 freqtrade  | 2024-02-22 12:58:11,691 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_exit_signal: True
2024-02-22 20:58:11 freqtrade  | 2024-02-22 12:58:11,691 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_only: False
2024-02-22 20:58:11 freqtrade  | 2024-02-22 12:58:11,692 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_entry_signal: False
2024-02-22 20:58:11 freqtrade  | 2024-02-22 12:58:11,692 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_offset: 0.0
2024-02-22 20:58:11 freqtrade  | 2024-02-22 12:58:11,693 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2024-02-22 20:58:11 freqtrade  | 2024-02-22 12:58:11,693 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2024-02-22 20:58:11 freqtrade  | 2024-02-22 12:58:11,694 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: False
2024-02-22 20:58:11 freqtrade  | 2024-02-22 12:58:11,694 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1
2024-02-22 20:58:11 freqtrade  | 2024-02-22 12:58:11,694 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_open_trades: 3
2024-02-22 20:58:11 freqtrade  | 2024-02-22 12:58:11,695 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2024-02-22 20:58:11 freqtrade  | 2024-02-22 12:58:11,698 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2024-02-22 20:58:11 freqtrade  | 2024-02-22 12:58:11,698 - freqtrade.exchange.exchange - INFO - Using CCXT 4.2.25
2024-02-22 20:58:11 freqtrade  | 2024-02-22 12:58:11,712 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2024-02-22 20:58:21 freqtrade  | 2024-02-22 12:58:21,718 - freqtrade.exchange.exchange - ERROR - Unable to initialize markets.
2024-02-22 20:58:21 freqtrade  | Traceback (most recent call last):
2024-02-22 20:58:21 freqtrade  |   File "/home/ftuser/.local/lib/python3.11/site-packages/urllib3/connection.py", line 203, in _new_conn
2024-02-22 20:58:21 freqtrade  |     sock = connection.create_connection(
2024-02-22 20:58:21 freqtrade  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-22 20:58:21 freqtrade  |   File "/home/ftuser/.local/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
2024-02-22 20:58:21 freqtrade  |     raise err
2024-02-22 20:58:21 freqtrade  |   File "/home/ftuser/.local/lib/python3.11/site-packages/urllib3/util/connection.py", line 73, in create_connection
2024-02-22 20:58:21 freqtrade  |     sock.connect(sa)
2024-02-22 20:58:21 freqtrade  | TimeoutError: timed out
2024-02-22 20:58:21 freqtrade  | 
2024-02-22 20:58:21 freqtrade  | The above exception was the direct cause of the following exception:
2024-02-22 20:58:21 freqtrade  | 
2024-02-22 20:58:21 freqtrade  | Traceback (most recent call last):
2024-02-22 20:58:21 freqtrade  |   File "/home/ftuser/.local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 790, in urlopen
2024-02-22 20:58:21 freqtrade  |     response = self._make_request(
2024-02-22 20:58:21 freqtrade  |                ^^^^^^^^^^^^^^^^^^^
2024-02-22 20:58:21 freqtrade  |   File "/home/ftuser/.local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 491, in _make_request
2024-02-22 20:58:21 freqtrade  |     raise new_e
2024-02-22 20:58:21 freqtrade  |   File "/home/ftuser/.local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 467, in _make_request
2024-02-22 20:58:21 freqtrade  |     self._validate_conn(conn)
2024-02-22 20:58:21 freqtrade  |   File "/home/ftuser/.local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1096, in _validate_conn
2024-02-22 20:58:21 freqtrade  |     conn.connect()
2024-02-22 20:58:21 freqtrade  |   File "/home/ftuser/.local/lib/python3.11/site-packages/urllib3/connection.py", line 611, in connect
2024-02-22 20:58:21 freqtrade  |     self.sock = sock = self._new_conn()
2024-02-22 20:58:21 freqtrade  |                        ^^^^^^^^^^^^^^^^
2024-02-22 20:58:21 freqtrade  |   File "/home/ftuser/.local/lib/python3.11/site-packages/urllib3/connection.py", line 212, in _new_conn
2024-02-22 20:58:21 freqtrade  |     raise ConnectTimeoutError(
2024-02-22 20:58:21 freqtrade  | urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f617289ef90>, 'Connection to api.binance.com timed out. (connect timeout=10.0)')
2024-02-22 20:58:21 freqtrade  | 
2024-02-22 20:58:21 freqtrade  | The above exception was the direct cause of the following exception:
2024-02-22 20:58:21 freqtrade  | 
2024-02-22 20:58:21 freqtrade  | Traceback (most recent call last):
2024-02-22 20:58:21 freqtrade  |   File "/home/ftuser/.local/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
2024-02-22 20:58:21 freqtrade  |     resp = conn.urlopen(
2024-02-22 20:58:21 freqtrade  |            ^^^^^^^^^^^^^
2024-02-22 20:58:21 freqtrade  |   File "/home/ftuser/.local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 844, in urlopen
2024-02-22 20:58:21 freqtrade  |     retries = retries.increment(
2024-02-22 20:58:21 freqtrade  |               ^^^^^^^^^^^^^^^^^^
2024-02-22 20:58:21 freqtrade  |   File "/home/ftuser/.local/lib/python3.11/site-packages/urllib3/util/retry.py", line 515, in increment
2024-02-22 20:58:21 freqtrade  |     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
2024-02-22 20:58:21 freqtrade  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-22 20:58:21 freqtrade  | urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/exchangeInfo (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f617289ef90>, 'Connection to api.binance.com timed out. (connect timeout=10.0)'))
2024-02-22 20:58:21 freqtrade  | 
2024-02-22 20:58:21 freqtrade  | During handling of the above exception, another exception occurred:
2024-02-22 20:58:21 freqtrade  | 
2024-02-22 20:58:21 freqtrade  | Traceback (most recent call last):
2024-02-22 20:58:21 freqtrade  |   File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/base/exchange.py", line 596, in fetch
2024-02-22 20:58:21 freqtrade  |     response = self.session.request(
2024-02-22 20:58:21 freqtrade  |                ^^^^^^^^^^^^^^^^^^^^^
2024-02-22 20:58:21 freqtrade  |   File "/home/ftuser/.local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
2024-02-22 20:58:21 freqtrade  |     resp = self.send(prep, **send_kwargs)
2024-02-22 20:58:21 freqtrade  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-22 20:58:21 freqtrade  |   File "/home/ftuser/.local/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
2024-02-22 20:58:21 freqtrade  |     r = adapter.send(request, **kwargs)
2024-02-22 20:58:21 freqtrade  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-22 20:58:21 freqtrade  |   File "/home/ftuser/.local/lib/python3.11/site-packages/requests/adapters.py", line 507, in send
2024-02-22 20:58:21 freqtrade  |     raise ConnectTimeout(e, request=request)
2024-02-22 20:58:21 freqtrade  | requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/exchangeInfo (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f617289ef90>, 'Connection to api.binance.com timed out. (connect timeout=10.0)'))
2024-02-22 20:58:21 freqtrade  | 
2024-02-22 20:58:21 freqtrade  | The above exception was the direct cause of the following exception:
2024-02-22 20:58:21 freqtrade  | 
2024-02-22 20:58:21 freqtrade  | Traceback (most recent call last):
2024-02-22 20:58:21 freqtrade  |   File "/freqtrade/freqtrade/exchange/exchange.py", line 484, in _load_markets
2024-02-22 20:58:21 freqtrade  |     self._markets = self._api.load_markets(params={})
2024-02-22 20:58:21 freqtrade  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-22 20:58:21 freqtrade  |   File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/base/exchange.py", line 1464, in load_markets
2024-02-22 20:58:21 freqtrade  |     markets = self.fetch_markets(params)
2024-02-22 20:58:21 freqtrade  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-22 20:58:21 freqtrade  |   File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/binance.py", line 2052, in fetch_markets
2024-02-22 20:58:21 freqtrade  |     promisesRaw.append(self.publicGetExchangeInfo(params))
2024-02-22 20:58:21 freqtrade  |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-22 20:58:21 freqtrade  |   File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/base/types.py", line 34, in unbound_method
2024-02-22 20:58:21 freqtrade  |     return _self.request(self.path, self.api, self.method, params, config=self.config)
2024-02-22 20:58:21 freqtrade  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-22 20:58:21 freqtrade  |   File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/binance.py", line 8177, in request
2024-02-22 20:58:21 freqtrade  |     response = self.fetch2(path, api, method, params, headers, body, config)
2024-02-22 20:58:21 freqtrade  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-22 20:58:21 freqtrade  |   File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/base/exchange.py", line 3350, in fetch2
2024-02-22 20:58:21 freqtrade  |     return self.fetch(request['url'], request['method'], request['headers'], request['body'])
2024-02-22 20:58:21 freqtrade  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-22 20:58:21 freqtrade  |   File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/base/exchange.py", line 626, in fetch
2024-02-22 20:58:21 freqtrade  |     raise RequestTimeout(details) from e
2024-02-22 20:58:21 freqtrade  | ccxt.base.errors.RequestTimeout: binance GET https://api.binance.com/api/v3/exchangeInfo
2024-02-22 20:58:21 freqtrade  | 2024-02-22 12:58:21,723 - freqtrade.commands.trade_commands - ERROR - Could not load markets, therefore cannot start. Please investigate the above error for more details.
2024-02-22 20:58:21 freqtrade  | 2024-02-22 12:58:21,724 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
2024-02-22 20:58:21 freqtrade  | Traceback (most recent call last):
2024-02-22 20:58:21 freqtrade  |   File "/freqtrade/freqtrade/commands/trade_commands.py", line 24, in start_trading
2024-02-22 20:58:21 freqtrade  |     worker = Worker(args)
2024-02-22 20:58:21 freqtrade  |              ^^^^^^^^^^^^
2024-02-22 20:58:21 freqtrade  |   File "/freqtrade/freqtrade/worker.py", line 37, in __init__
2024-02-22 20:58:21 freqtrade  |     self._init(False)
2024-02-22 20:58:21 freqtrade  |   File "/freqtrade/freqtrade/worker.py", line 53, in _init
2024-02-22 20:58:21 freqtrade  |     self.freqtrade = FreqtradeBot(self._config)
2024-02-22 20:58:21 freqtrade  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-22 20:58:21 freqtrade  |   File "/freqtrade/freqtrade/freqtradebot.py", line 76, in __init__
2024-02-22 20:58:21 freqtrade  |     self.exchange = ExchangeResolver.load_exchange(
2024-02-22 20:58:21 freqtrade  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-22 20:58:21 freqtrade  |   File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 37, in load_exchange
2024-02-22 20:58:21 freqtrade  |     exchange = ExchangeResolver._load_exchange(
2024-02-22 20:58:21 freqtrade  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-22 20:58:21 freqtrade  |   File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 64, in _load_exchange
2024-02-22 20:58:21 freqtrade  |     exchange = ex_class(**kwargs)
2024-02-22 20:58:21 freqtrade  |                ^^^^^^^^^^^^^^^^^^
2024-02-22 20:58:21 freqtrade  |   File "/freqtrade/freqtrade/exchange/exchange.py", line 189, in __init__
2024-02-22 20:58:21 freqtrade  |     self.validate_config(config)
2024-02-22 20:58:21 freqtrade  |   File "/freqtrade/freqtrade/exchange/exchange.py", line 227, in validate_config
2024-02-22 20:58:21 freqtrade  |     self.validate_stakecurrency(config['stake_currency'])
2024-02-22 20:58:21 freqtrade  |   File "/freqtrade/freqtrade/exchange/exchange.py", line 521, in validate_stakecurrency
2024-02-22 20:58:21 freqtrade  |     raise OperationalException(
2024-02-22 20:58:21 freqtrade  | freqtrade.exceptions.OperationalException: Could not load markets, therefore cannot start. Please investigate the above error for more details.
2024-02-22 20:58:24 freqtrade  | 2024-02-22 12:58:24,787 - freqtrade - INFO - freqtrade 2024.1
2024-02-22 20:58:25 freqtrade  | 2024-02-22 12:58:25,216 - freqtrade.worker - INFO - Starting worker 2024.1
2024-02-22 20:58:25 freqtrade  | 2024-02-22 12:58:25,216 - freqtrade.configuration.load_config - INFO - Using config: /freqtrade/user_data/config.json ...
2024-02-22 20:58:25 freqtrade  | 2024-02-22 12:58:25,219 - freqtrade.loggers - INFO - Verbosity set to 0
2024-02-22 20:58:25 freqtrade  | 2024-02-22 12:58:25,220 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
2024-02-22 20:58:25 freqtrade  | 2024-02-22 12:58:25,221 - freqtrade.configuration.configuration - INFO - Parameter --db-url detected ...
2024-02-22 20:58:25 freqtrade  | 2024-02-22 12:58:25,221 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2024-02-22 20:58:25 freqtrade  | 2024-02-22 12:58:25,222 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:////freqtrade/user_data/tradesv3.sqlite"
2024-02-22 20:58:25 freqtrade  | 2024-02-22 12:58:25,222 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 3 ...
2024-02-22 20:58:25 freqtrade  | 2024-02-22 12:58:25,258 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2024-02-22 20:58:25 freqtrade  | 2024-02-22 12:58:25,260 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/binance ...
2024-02-22 20:58:25 freqtrade  | 2024-02-22 12:58:25,261 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2024-02-22 20:58:25 freqtrade  | 2024-02-22 12:58:25,268 - freqtrade.exchange.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2024-02-22 20:58:25 freqtrade  | 2024-02-22 12:58:25,269 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2024-02-22 20:58:25 freqtrade  | 2024-02-22 12:58:25,295 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy SampleStrategy from '/freqtrade/user_data/strategies/sample_strategy.py'...
2024-02-22 20:58:25 freqtrade  | 2024-02-22 12:58:25,296 - freqtrade.strategy.hyper - INFO - Found no parameter file.
2024-02-22 20:58:25 freqtrade  | 2024-02-22 12:58:25,297 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2024-02-22 20:58:25 freqtrade  | 2024-02-22 12:58:25,297 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 10000.
2024-02-22 20:58:25 freqtrade  | 2024-02-22 12:58:25,298 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}.
2024-02-22 20:58:25 freqtrade  | 2024-02-22 12:58:25,298 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'max_open_trades' with value in config file: 3.
2024-02-22 20:58:25 freqtrade  | 2024-02-22 12:58:25,299 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'60': 0.01, '30': 0.02, '0': 0.04}
2024-02-22 20:58:25 freqtrade  | 2024-02-22 12:58:25,299 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 5m
2024-02-22 20:58:25 freqtrade  | 2024-02-22 12:58:25,300 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.1
2024-02-22 20:58:25 freqtrade  | 2024-02-22 12:58:25,300 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2024-02-22 20:58:25 freqtrade  | 2024-02-22 12:58:25,301 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2024-02-22 20:58:25 freqtrade  | 2024-02-22 12:58:25,301 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2024-02-22 20:58:25 freqtrade  | 2024-02-22 12:58:25,302 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2024-02-22 20:58:25 freqtrade  | 2024-02-22 12:58:25,303 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: True
2024-02-22 20:58:25 freqtrade  | 2024-02-22 12:58:25,303 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'entry': 'limit', 'exit': 'limit', 'stoploss': 'market', 'stoploss_on_exchange': False}
2024-02-22 20:58:25 freqtrade  | 2024-02-22 12:58:25,303 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'entry': 'GTC', 'exit': 'GTC'}
2024-02-22 20:58:25 freqtrade  | 2024-02-22 12:58:25,304 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2024-02-22 20:58:25 freqtrade  | 2024-02-22 12:58:25,304 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 10000
2024-02-22 20:58:25 freqtrade  | 2024-02-22 12:58:25,305 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2024-02-22 20:58:25 freqtrade  | 2024-02-22 12:58:25,306 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 200
2024-02-22 20:58:25 freqtrade  | 2024-02-22 12:58:25,306 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}
2024-02-22 20:58:25 freqtrade  | 2024-02-22 12:58:25,307 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_exit_signal: True
2024-02-22 20:58:25 freqtrade  | 2024-02-22 12:58:25,307 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_only: False
2024-02-22 20:58:25 freqtrade  | 2024-02-22 12:58:25,308 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_entry_signal: False
2024-02-22 20:58:25 freqtrade  | 2024-02-22 12:58:25,308 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_offset: 0.0
2024-02-22 20:58:25 freqtrade  | 2024-02-22 12:58:25,308 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2024-02-22 20:58:25 freqtrade  | 2024-02-22 12:58:25,309 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2024-02-22 20:58:25 freqtrade  | 2024-02-22 12:58:25,309 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: False
2024-02-22 20:58:25 freqtrade  | 2024-02-22 12:58:25,310 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1
2024-02-22 20:58:25 freqtrade  | 2024-02-22 12:58:25,310 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_open_trades: 3
2024-02-22 20:58:25 freqtrade  | 2024-02-22 12:58:25,311 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2024-02-22 20:58:25 freqtrade  | 2024-02-22 12:58:25,314 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2024-02-22 20:58:25 freqtrade  | 2024-02-22 12:58:25,314 - freqtrade.exchange.exchange - INFO - Using CCXT 4.2.25
2024-02-22 20:58:25 freqtrade  | 2024-02-22 12:58:25,329 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"

  ```

**Comment by xmatthias** [comment]
This looks like a quite simple network connection error.
Unfortunately, docker on windows is kinda known to show this behavior - which can usually be fixed by doing a restart of the host machine.
We've got about 5 tickets all showing similar behavior - with usually the fix being - restart the machine.

It's not directly a freqtrade problem - but a docker on windows issue ... but unfortunately nothing we can influence directly (no network -> no requests to the exchange -> no freqtrade bot).
