### ISSUE TITLE
OpenBLAS errors in combination with Docker on Ubuntu 18.04

### ISSUE THREAD

**Issue by Javajava1** [freqtrade/freqtrade#9856]
## Describe your environment

  * Operating system: Ubuntu 18.04
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: _it cannot be see.___ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

  1. Download the freqtrade image._____
  2. _Create user directory structure__using "docker compose run --rm freqtrade create-userdir --userdir user_data"_command_
  3. _____
  
### Observed Results:

  * What happened?
  * The "docker compose run --rm freqtrade create-userdir --userdir user_data" command doesnot work.
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
Creating ft_userdata_freqtrade_run ... done
OpenBLAS blas_thread_init: pthread_create failed for thread 1 of 16: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 2 of 16: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 3 of 16: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 4 of 16: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 5 of 16: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 6 of 16: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 7 of 16: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 8 of 16: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 9 of 16: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 10 of 16: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 11 of 16: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 12 of 16: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 13 of 16: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 14 of 16: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 15 of 16: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
Traceback (most recent call last):
  File "/home/ftuser/.local/bin/freqtrade", line 5, in <module>
    from freqtrade.main import main
  File "/freqtrade/freqtrade/main.py", line 18, in <module>
    from freqtrade.commands import Arguments
  File "/freqtrade/freqtrade/commands/__init__.py", line 9, in <module>
    from freqtrade.commands.analyze_commands import start_analysis_entries_exits
  File "/freqtrade/freqtrade/commands/analyze_commands.py", line 5, in <module>
    from freqtrade.configuration import setup_utils_configuration
  File "/freqtrade/freqtrade/configuration/__init__.py", line 3, in <module>
    from freqtrade.configuration.config_setup import setup_utils_configuration
  File "/freqtrade/freqtrade/configuration/config_setup.py", line 7, in <module>
    from .configuration import Configuration
  File "/freqtrade/freqtrade/configuration/configuration.py", line 13, in <module>
    from freqtrade.configuration.environment_vars import enironment_vars_to_dict
  File "/freqtrade/freqtrade/configuration/environment_vars.py", line 6, in <module>
    from freqtrade.misc import deep_merge_dicts
  File "/freqtrade/freqtrade/misc.py", line 11, in <module>
    import pandas as pd
  File "/home/ftuser/.local/lib/python3.11/site-packages/pandas/__init__.py", line 11, in <module>
    __import__(_dependency)
  File "/home/ftuser/.local/lib/python3.11/site-packages/numpy/__init__.py", line 130, in <module>
    from numpy.__config__ import show as show_config
  File "/home/ftuser/.local/lib/python3.11/site-packages/numpy/__config__.py", line 4, in <module>
    from numpy.core._multiarray_umath import (
  File "/home/ftuser/.local/lib/python3.11/site-packages/numpy/core/__init__.py", line 24, in <module>
    from . import multiarray
  File "/home/ftuser/.local/lib/python3.11/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/home/ftuser/.local/lib/python3.11/site-packages/numpy/core/overrides.py", line 8, in <module>
    from numpy.core._multiarray_umath import (
  File "<frozen importlib._bootstrap>", line 216, in _lock_unlock_module
KeyboardInterrupt
ERROR: 130

  ```

**Comment by xmatthias** [comment]
based on https://github.com/abetlen/llama-cpp-python/issues/450 (more specifically https://github.com/abetlen/llama-cpp-python/issues/450#issuecomment-1764392270 and https://github.com/abetlen/llama-cpp-python/issues/450#issuecomment-1788273700) - this seems to originate from an old docker version.

combining this with the use of ubuntu 18.04 (which i'd consider as outdated, and is currently in "extended security maintenance" mode) - the explanation in the above linked issue make sense.

Best make sure to use an uptodate version of docker - best combined with an actively supported version of the underlying operating system (ubuntu 20.04 and up should work - though newer is usually better).
