### ISSUE TITLE
Kraken live trading - invalid literal for int()

### ISSUE THREAD

**Issue by fritz-fritz** [freqtrade/freqtrade#9864]
## Describe your environment

  * Operating system: Docker 20.10.25
  * CCXT version: 4.2.25
  * Freqtrade Version: 2024.1
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

Attempting to get started using freqtrade, decided to test the API integration with Kraken by starting in live mode. The process dies and the docker container restarts.

### Steps to reproduce:

  1. fresh configuration per docs
  2. configure live with appropriate keys
  3. `docker-compose up -d`
  
### Observed Results:

  * What happened?
      * `docker logs freqtrade` reveals `ValueError: invalid literal for int() with base 10: '+90000%'`
  * What did you expect to happen?
      * freqtrade to connect to Kraken and reflect current balance and positions

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
2024-02-25 16:36:20,827 - freqtrade - INFO - freqtrade 2024.1
2024-02-25 16:36:21,200 - freqtrade.worker - INFO - Starting worker 2024.1
2024-02-25 16:36:21,200 - freqtrade.configuration.load_config - INFO - Using config: /freqtrade/user_data/config.json ...
2024-02-25 16:36:21,201 - freqtrade.loggers - INFO - Verbosity set to 0
2024-02-25 16:36:21,201 - freqtrade.configuration.configuration - INFO - Runmode set to live.
2024-02-25 16:36:21,201 - freqtrade.configuration.configuration - INFO - Parameter --db-url detected ...
2024-02-25 16:36:21,201 - freqtrade.configuration.configuration - INFO - Dry run is disabled
2024-02-25 16:36:21,201 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:////freqtrade/user_data/tradesv3.sqlite"
2024-02-25 16:36:21,201 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 10 ...
2024-02-25 16:36:21,208 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2024-02-25 16:36:21,209 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/kraken ...
2024-02-25 16:36:21,209 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2024-02-25 16:36:21,211 - freqtrade.exchange.check_exchange - INFO - Exchange "kraken" is officially supported by the Freqtrade development team.
2024-02-25 16:36:21,211 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2024-02-25 16:36:21,222 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy SampleStrategy from '/freqtrade/user_data/strategies/sample_strategy.py'...
2024-02-25 16:36:21,222 - freqtrade.strategy.hyper - INFO - Found no parameter file.
2024-02-25 16:36:21,223 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USD.
2024-02-25 16:36:21,223 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: unlimited.
2024-02-25 16:36:21,223 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}.
2024-02-25 16:36:21,223 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'max_open_trades' with value in config file: 10.
2024-02-25 16:36:21,223 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'60': 0.01, '30': 0.02, '0': 0.04}
2024-02-25 16:36:21,223 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 5m
2024-02-25 16:36:21,223 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.1
2024-02-25 16:36:21,223 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2024-02-25 16:36:21,223 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2024-02-25 16:36:21,223 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2024-02-25 16:36:21,223 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2024-02-25 16:36:21,223 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: True
2024-02-25 16:36:21,223 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'entry': 'limit', 'exit': 'limit', 'stoploss': 'market', 'stoploss_on_exchange': False}
2024-02-25 16:36:21,223 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'entry': 'GTC', 'exit': 'GTC'}
2024-02-25 16:36:21,223 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USD
2024-02-25 16:36:21,223 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: unlimited
2024-02-25 16:36:21,224 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2024-02-25 16:36:21,224 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 200
2024-02-25 16:36:21,224 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}
2024-02-25 16:36:21,224 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_exit_signal: True
2024-02-25 16:36:21,224 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_only: False
2024-02-25 16:36:21,224 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_entry_signal: False
2024-02-25 16:36:21,224 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_offset: 0.0
2024-02-25 16:36:21,224 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2024-02-25 16:36:21,224 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2024-02-25 16:36:21,224 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: False
2024-02-25 16:36:21,224 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1
2024-02-25 16:36:21,224 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_open_trades: 10
2024-02-25 16:36:21,224 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2024-02-25 16:36:21,226 - freqtrade.exchange.exchange - INFO - Using CCXT 4.2.25
2024-02-25 16:36:21,229 - freqtrade.exchange.exchange - INFO - Using Exchange "Kraken"
2024-02-25 16:36:30,516 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Kraken'...
2024-02-25 16:36:34,351 - freqtrade.commands.trade_commands - ERROR - invalid literal for int() with base 10: '+90000%'
2024-02-25 16:36:34,351 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 24, in start_trading
    worker = Worker(args)
             ^^^^^^^^^^^^
  File "/freqtrade/freqtrade/worker.py", line 37, in __init__
    self._init(False)
  File "/freqtrade/freqtrade/worker.py", line 53, in _init
    self.freqtrade = FreqtradeBot(self._config)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/freqtradebot.py", line 81, in __init__
    self.wallets = Wallets(self.config, self.exchange)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/wallets.py", line 47, in __init__
    self.update()
  File "/freqtrade/freqtrade/wallets.py", line 177, in update
    self._update_live()
  File "/freqtrade/freqtrade/wallets.py", line 130, in _update_live
    balances = self._exchange.get_balances()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/exchange/common.py", line 168, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/exchange/kraken.py", line 72, in get_balances
    orders = self._api.fetch_open_orders()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/kraken.py", line 1979, in fetch_open_orders
    return self.parse_orders(orders, market, since, limit)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/base/exchange.py", line 2636, in parse_orders
    order = self.extend(self.parse_order(self.extend({'id': id}, orders[id]), market), params)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/kraken.py", line 1495, in parse_order
    if (price is None) or Precise.string_equals(price, '0'):
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/base/precise.py", line 245, in string_equals
    return Precise(string1).equals(Precise(string2))
           ^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/base/precise.py", line 25, in __init__
    self.integer = int(number.replace('.', ''))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '+90000%'
                                                  
  ```
___
Judging by the traceback, I suspect the Kraken API is returning a result that ccxt isn't expecting? I am aware if that is indeed the case that the issue should be filed upstream at ccxt but seeing as this was using the packaged docker image and an officially supported exchange it seemed important to raise the issue here.

**Comment by xmatthias** [comment]
well the error raises directly from the communication between ccxt and Kraken, so yes, it's a ccxt issue.

It's however a known (and fixed) issue (https://github.com/ccxt/ccxt/issues/21063) - so an update to the develop image (or waiting for the next stable release, which if time allows, should happen sometime this week) will fix this automatically.

Alternatively, you can also simply close your open, relative stoploss order (see my comment on that issue) - which is for sure an issue freqtrade did not create - and is currently causing this problem.

**Comment by fritz-fritz** [comment]
Ah gotcha, hadn't dug into ccxt to interpret where it was going wrong. That makes a ton of sense and indeed did resolve the problem.
