### ISSUE TITLE
"Error in additional_exchange_init due to RequestTimeout" when performing live run on exchange "Bybit"

### ISSUE THREAD

**Issue by wine10001** [freqtrade/freqtrade#9877]
## Describe your environment

  * Operating system: Windows 10
  * Python Version: 3.10.11
  * CCXT version: 3.0.85
  * Freqtrade Version: freqtrade docker-2023.5.dev-081a8b0e
  
## Your question

*
I executed the following command in Docker:
```properties
docker compose run --rm freqtrade trade --config user_data/config.json --strategy SampleStrategy_BTC --db-url sqlite:///tradesv3.sqlite
```
However, I encountered an error message related to a request timeout with the Bybit exchange:
```properties
2024-02-27 07:53:49,683 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2024-02-27 07:53:49,688 - freqtrade.exchange.exchange - INFO - Using CCXT 3.0.85
2024-02-27 07:53:49,688 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}, 'enableRateLimit': False}
2024-02-27 07:53:49,698 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}, 'enableRateLimit': False}
2024-02-27 07:53:49,707 - freqtrade.exchange.exchange - INFO - Using Exchange "Bybit"
2024-02-27 07:53:50,789 - freqtrade.exchange.exchange - INFO - Using cached leverage_tiers.
2024-02-27 07:53:50,789 - freqtrade.exchange.exchange - INFO - Done initializing 316 markets.
2024-02-27 07:53:53,358 - freqtrade.exchange.common - WARNING - additional_exchange_init() returned exception: "Error in additional_exchange_init due to RequestTimeout. Message: bybit {"retCode":10016,"retMsg":"Request timeout, please try again later","result":{},"retExtInfo":{},"time":1709020433520}". Retrying still for 4 times.
2024-02-27 07:53:55,924 - freqtrade.exchange.common - WARNING - additional_exchange_init() returned exception: "Error in additional_exchange_init due to RequestTimeout. Message: bybit {"retCode":10016,"retMsg":"Request timeout, please try again later","result":{},"retExtInfo":{},"time":1709020436093}". Retrying still for 3 times.
2024-02-27 07:53:58,487 - freqtrade.exchange.common - WARNING - additional_exchange_init() returned exception: "Error in additional_exchange_init due to RequestTimeout. Message: bybit {"retCode":10016,"retMsg":"Request timeout, please try again later","result":{},"retExtInfo":{},"time":1709020438656}". Retrying still for 2 times.
2024-02-27 07:54:01,064 - freqtrade.exchange.common - WARNING - additional_exchange_init() returned exception: "Error in additional_exchange_init due to RequestTimeout. Message: bybit {"retCode":10016,"retMsg":"Request timeout, please try again later","result":{},"retExtInfo":{},"time":1709020441233}". Retrying still for 1 times.
2024-02-27 07:54:03,623 - freqtrade.exchange.common - WARNING - additional_exchange_init() returned exception: "Error in additional_exchange_init due to RequestTimeout. Message: bybit {"retCode":10016,"retMsg":"Request timeout, please try again later","result":{},"retExtInfo":{},"time":1709020443792}". Giving up.
2024-02-27 07:54:03,624 - freqtrade.commands.trade_commands - ERROR - Error in additional_exchange_init due to RequestTimeout. Message: bybit {"retCode":10016,"retMsg":"Request timeout, please try again later","result":{},"retExtInfo":{},"time":1709020443792}
2024-02-27 07:54:03,624 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/bybit.py", line 83, in additional_exchange_init
    position_mode = self._api.set_position_mode(False)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/bybit.py", line 7064, in set_position_mode
    return self.privatePostContractV3PrivatePositionSwitchMode(self.extend(request, params))
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 507, in inner
    return entry(_self, **inner_kwargs)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2882, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2879, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 669, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/bybit.py", line 7889, in handle_errors
    self.throw_broadly_matched_exception(self.exceptions['broad'], body, feedback)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 3193, in throw_broadly_matched_exception
    raise broad[broadKey](message)
ccxt.base.errors.RequestTimeout: bybit {"retCode":10016,"retMsg":"Request timeout, please try again later","result":{},"retExtInfo":{},"time":1709020433520}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/common.py", line 164, in wrapper
    return f(*args, **kwargs)
  File "/freqtrade/freqtrade/exchange/bybit.py", line 88, in additional_exchange_init
    raise TemporaryError(
freqtrade.exceptions.TemporaryError: Error in additional_exchange_init due to RequestTimeout. Message: bybit {"retCode":10016,"retMsg":"Request timeout, please try again later","result":{},"retExtInfo":{},"time":1709020433520}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/bybit.py", line 83, in additional_exchange_init
    position_mode = self._api.set_position_mode(False)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/bybit.py", line 7064, in set_position_mode
    return self.privatePostContractV3PrivatePositionSwitchMode(self.extend(request, params))
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 507, in inner
    return entry(_self, **inner_kwargs)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2882, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2879, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 669, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/bybit.py", line 7889, in handle_errors
    self.throw_broadly_matched_exception(self.exceptions['broad'], body, feedback)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 3193, in throw_broadly_matched_exception
    raise broad[broadKey](message)
ccxt.base.errors.RequestTimeout: bybit {"retCode":10016,"retMsg":"Request timeout, please try again later","result":{},"retExtInfo":{},"time":1709020436093}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/common.py", line 164, in wrapper
    return f(*args, **kwargs)
  File "/freqtrade/freqtrade/exchange/bybit.py", line 88, in additional_exchange_init
    raise TemporaryError(
freqtrade.exceptions.TemporaryError: Error in additional_exchange_init due to RequestTimeout. Message: bybit {"retCode":10016,"retMsg":"Request timeout, please try again later","result":{},"retExtInfo":{},"time":1709020436093}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/bybit.py", line 83, in additional_exchange_init
    position_mode = self._api.set_position_mode(False)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/bybit.py", line 7064, in set_position_mode
    return self.privatePostContractV3PrivatePositionSwitchMode(self.extend(request, params))
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 507, in inner
    return entry(_self, **inner_kwargs)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2882, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2879, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 669, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/bybit.py", line 7889, in handle_errors
    self.throw_broadly_matched_exception(self.exceptions['broad'], body, feedback)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 3193, in throw_broadly_matched_exception
    raise broad[broadKey](message)
ccxt.base.errors.RequestTimeout: bybit {"retCode":10016,"retMsg":"Request timeout, please try again later","result":{},"retExtInfo":{},"time":1709020438656}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/common.py", line 164, in wrapper
    return f(*args, **kwargs)
  File "/freqtrade/freqtrade/exchange/bybit.py", line 88, in additional_exchange_init
    raise TemporaryError(
freqtrade.exceptions.TemporaryError: Error in additional_exchange_init due to RequestTimeout. Message: bybit {"retCode":10016,"retMsg":"Request timeout, please try again later","result":{},"retExtInfo":{},"time":1709020438656}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/bybit.py", line 83, in additional_exchange_init
    position_mode = self._api.set_position_mode(False)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/bybit.py", line 7064, in set_position_mode
    return self.privatePostContractV3PrivatePositionSwitchMode(self.extend(request, params))
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 507, in inner
    return entry(_self, **inner_kwargs)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2882, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2879, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 669, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/bybit.py", line 7889, in handle_errors
    self.throw_broadly_matched_exception(self.exceptions['broad'], body, feedback)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 3193, in throw_broadly_matched_exception
    raise broad[broadKey](message)
ccxt.base.errors.RequestTimeout: bybit {"retCode":10016,"retMsg":"Request timeout, please try again later","result":{},"retExtInfo":{},"time":1709020441233}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/common.py", line 164, in wrapper
    return f(*args, **kwargs)
  File "/freqtrade/freqtrade/exchange/bybit.py", line 88, in additional_exchange_init
    raise TemporaryError(
freqtrade.exceptions.TemporaryError: Error in additional_exchange_init due to RequestTimeout. Message: bybit {"retCode":10016,"retMsg":"Request timeout, please try again later","result":{},"retExtInfo":{},"time":1709020441233}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/bybit.py", line 83, in additional_exchange_init
    position_mode = self._api.set_position_mode(False)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/bybit.py", line 7064, in set_position_mode
    return self.privatePostContractV3PrivatePositionSwitchMode(self.extend(request, params))
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 507, in inner
    return entry(_self, **inner_kwargs)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2882, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2879, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 669, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/bybit.py", line 7889, in handle_errors
    self.throw_broadly_matched_exception(self.exceptions['broad'], body, feedback)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 3193, in throw_broadly_matched_exception
    raise broad[broadKey](message)
ccxt.base.errors.RequestTimeout: bybit {"retCode":10016,"retMsg":"Request timeout, please try again later","result":{},"retExtInfo":{},"time":1709020443792}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 24, in start_trading
    worker = Worker(args)
  File "/freqtrade/freqtrade/worker.py", line 37, in __init__
    self._init(False)
  File "/freqtrade/freqtrade/worker.py", line 53, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/freqtrade/freqtrade/freqtradebot.py", line 72, in __init__
    self.exchange = ExchangeResolver.load_exchange(
  File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 34, in load_exchange
    exchange = ExchangeResolver._load_exchange(
  File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 60, in _load_exchange
    exchange = ex_class(**kwargs)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 197, in __init__
    self.additional_exchange_init()
  File "/freqtrade/freqtrade/exchange/common.py", line 176, in wrapper
    return wrapper(*args, **kwargs)
  File "/freqtrade/freqtrade/exchange/common.py", line 176, in wrapper
    return wrapper(*args, **kwargs)
  File "/freqtrade/freqtrade/exchange/common.py", line 176, in wrapper
    return wrapper(*args, **kwargs)
  [Previous line repeated 1 more time]
  File "/freqtrade/freqtrade/exchange/common.py", line 179, in wrapper
    raise ex
  File "/freqtrade/freqtrade/exchange/common.py", line 164, in wrapper
    return f(*args, **kwargs)
  File "/freqtrade/freqtrade/exchange/bybit.py", line 88, in additional_exchange_init
    raise TemporaryError(
freqtrade.exceptions.TemporaryError: Error in additional_exchange_init due to RequestTimeout. Message: bybit {"retCode":10016,"retMsg":"Request timeout, please try again later","result":{},"retExtInfo":{},"time":1709020443792}
```

The configuration for the exchange in my `config.json` is as follows:
```properties
"exchange": {
        "name": "bybit",
        "key": "masked",
        "secret": "masked"",
        "ccxt_config": {"enableRateLimit": true},
        "ccxt_async_config": {
            "enableRateLimit": true,
            "rateLimit": 3000
        },
        "pair_whitelist": [
            "BTC/USDT:USDT",
            "ETH/USDT:USDT",
            "SOL/USDT:USDT",
            "ADA/USDT:USDT",
            "DOGE/USDT:USDT",
            "LTC/USDT:USDT",
            "EOS/USDT:USDT",
            "DOT/USDT:USDT",
            "1INCH/USDT:USDT",
            "MATIC/USDT:USDT"
        ],
        "pair_blacklist": [
            "BTC/USDT:USDT",
            "BNB/.*"
        ]
    },
    "pairlists": [
        {
            "method": "StaticPairList",
            "mode": "whitelist"
        }
    ]
```
I have attempted to modify the `rateLimit` value, but the same error persists.

*

**Comment by xmatthias** [comment]
Exchange API's change all the time, therefore please understand that we'll not be able to assist you with a nearly one year old version.
From the looks of it, it looks like that version is using an endpoint that no longer exists (probably the old API version).

Please follow the [update guide](https://www.freqtrade.io/en/stable/updating/) corresponding to your installation method to update freqtrade including dependencies.
