### ISSUE TITLE
Ticker pricing not available for binance futures

### ISSUE THREAD

**Issue by zoknoteplus** [freqtrade/freqtrade#9883]
## Describe your environment

  * Operating system: ____Ubuntu
  * Python Version: _____ (`python -V`)
  * CCXT version: _____4.2.51 (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____2024.02 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
When i start docker image i get this:

2024-02-28 20:59:48,489 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2024-02-28 20:59:48,489 - freqtrade.exchange.exchange - INFO - Using CCXT 4.2.47
2024-02-28 20:59:48,489 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}}
2024-02-28 20:59:48,510 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}}
2024-02-28 20:59:48,529 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2024-02-28 20:59:56,949 - freqtrade.commands.trade_commands - ERROR - Ticker pricing not available for Binance.
2024-02-28 20:59:56,949 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/mojubuntu/ft_userdata/freqtrade/freqtrade/commands/trade_commands.py", line 24, in start_trading
    worker = Worker(args)
  File "/home/mojubuntu/ft_userdata/freqtrade/freqtrade/worker.py", line 37, in __init__
    self._init(False)
  File "/home/mojubuntu/ft_userdata/freqtrade/freqtrade/worker.py", line 53, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/home/mojubuntu/ft_userdata/freqtrade/freqtrade/freqtradebot.py", line 76, in __init__
    self.exchange = ExchangeResolver.load_exchange(
  File "/home/mojubuntu/ft_userdata/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 37, in load_exchange
    exchange = ExchangeResolver._load_exchange(
  File "/home/mojubuntu/ft_userdata/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 64, in _load_exchange
    exchange = ex_class(**kwargs)
  File "/home/mojubuntu/ft_userdata/freqtrade/freqtrade/exchange/exchange.py", line 191, in __init__
    self.validate_config(config)
  File "/home/mojubuntu/ft_userdata/freqtrade/freqtrade/exchange/exchange.py", line 236, in validate_config
    self.validate_pricing(config['entry_pricing'])
  File "/home/mojubuntu/ft_userdata/freqtrade/freqtrade/exchange/exchange.py", line 643, in validate_pricing
    raise OperationalException(f'Ticker pricing not available for {self.name}.')
freqtrade.exceptions.OperationalException: Ticker pricing not available for Binance.

This is new!

**Comment by xmatthias** [comment]
well the name of the exception says it all i'd say - ticker pricing is not available on binance futures.
While the endpoint for that exists - it doesn't include prices - and is therefore unsuited to determine entry and exit prices.

Instead, you'll have to change your configuration to use [orderbook pricing](https://www.freqtrade.io/en/latest/configuration/#prices-used-for-orders) for both entry and exit pricing (`"use_order_book": true`).
This is also the default if you're using the `new-config` method.
