### ISSUE TITLE
lookahead error exception ValueError identically-labeled objects

### ISSUE THREAD

**Issue by IgnacioGoldman** [freqtrade/freqtrade#9888]
## Describe your environment

  * Operating system: Sonoma 14.2 (mac)
  * Python Version: 3.11
  * CCXT version: 4.1.98
  * Freqtrade Version: freqtrade 2023.12
  
## Describe the problem:

When running my lookahead analysis:

``` bash
docker-compose run freqtrade lookahead-analysis --timerange="20220601-20231227" --data-format-ohlcv=hdf5 --config="user_data/mlstrategy.json" --strategy MLStrategy_supres --enable-protections
``` 

I'm getting the following exception:

``` log
2024-03-01 10:52:21,250 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 42, in main
    return_code = args['func'](args)
                  ^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 146, in start_lookahead_analysis
    LookaheadAnalysisSubFunctions.start(config)
  File "/freqtrade/freqtrade/optimize/analysis/lookahead_helpers.py", line 201, in start
    LookaheadAnalysisSubFunctions.initialize_single_lookahead_analysis(
  File "/freqtrade/freqtrade/optimize/analysis/lookahead_helpers.py", line 171, in initialize_single_lookahead_analysis
    current_instance.start()
  File "/freqtrade/freqtrade/optimize/analysis/lookahead.py", line 248, in start
    self.analyze_row(idx, result_row)
  File "/freqtrade/freqtrade/optimize/analysis/lookahead.py", line 203, in analyze_row
    self.analyze_indicators(self.full_varHolder, self.entry_varHolders[idx], result_row['pair'])
  File "/freqtrade/freqtrade/optimize/analysis/lookahead.py", line 88, in analyze_indicators
    compare_df = full_df_cut.compare(cut_df_cut)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/pandas/core/frame.py", line 8296, in compare
    return super().compare(
           ^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/pandas/core/generic.py", line 9789, in compare
    mask = ~((self == other) | (self.isna() & other.isna()))
              ^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/pandas/core/ops/common.py", line 76, in new_method
    return method(self, other)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/pandas/core/arraylike.py", line 40, in __eq__
    return self._cmp_method(other, operator.eq)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/pandas/core/frame.py", line 7628, in _cmp_method
    self, other = self._align_for_op(other, axis, flex=False, level=None)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/pandas/core/frame.py", line 7927, in _align_for_op
    raise ValueError(
ValueError: Can only compare identically-labeled (both index and columns) DataFrame objects
```

**Comment by AndreyMashukov** [comment]
Write tests guys like here https://github.com/AndreyMashukov/go-crypto-bot

**Comment by xmatthias** [comment]
well there's little info for this (too little to try anything useful).
Trying this with a few strategies of my own works just fine - so it's clearly related to your setup somehow.

Maybe full logs would help already (the error is almost never the most important point) - but i suspect, to actually even try to analyze what's happening, we'll need a full reproduction (config, minimal strategy combination that's causing this).

**Comment by xmatthias** [comment]
Closing as we didn't get any further feedback or additional logs - hence there's not enough info to try and analyze this.

If you're still facing this problem, best comment below with the requested info so we can reopen and take a proper look.
