### ISSUE TITLE
left_indexer cannot be None

### ISSUE THREAD

**Issue by cliverenwood** [freqtrade/freqtrade#9892]
* Operating system: MacOS 14.3.1 (23D60)
  * Python Version: Python 3.11.8
  * CCXT version: 4.2.51
  * Freqtrade Version: 2024.2
  
*Explain the problem you have encountered*
The command 

`freqtrade backtesting --strategy FreqaiExampleHybridStrategy --strategy-path freqtrade/templates --config config_examples/config_freqai.json --freqaimodel LightGBMRegressor --timerange 20230401-20240201
`

throws an error 
### Steps to reproduce:

  1. Config for Freqai 
  ```
  {
	"trading_mode": "futures",
	"margin_mode": "isolated",
	"max_open_trades": 5,
	"stake_currency": "USDT",
	"stake_amount": 100,
	"tradable_balance_ratio": 1,
	"fiat_display_currency": "USD",
	"dry_run": true,
	"timeframe": "1m",
	"dry_run_wallet": 1000,
	"cancel_open_orders_on_exit": true,
	"unfilledtimeout": {
		"entry": 10,
		"exit": 30
	},
	"exchange": {
		"name": "bybit",
		"key": "",
		"secret": "",
		"ccxt_config": {},
		"ccxt_async_config": {},
		"pair_whitelist": [
			"BTC/USDT:USDT",
			"BCH/USDT:USDT",
			"ETH/USDT:USDT",
			"LINK/USDT:USDT",
			"LTC/USDT:USDT",
			"SOL/USDT:USDT",
			"BNB/USDT:USDT",
			"XRP/USDT:USDT",
			"ADA/USDT:USDT",
			"DOT/USDT:USDT",
			"ETC/USDT:USDT",
			"ALGO/USDT:USDT",
			"ZETA/USDT:USDT",
			"PYTH/USDT:USDT"
		],
		"pair_blacklist": []
	},
	"entry_pricing": {
		"price_side": "other",
		"use_order_book": true,
		"order_book_top": 1,
		"price_last_balance": 0.0,
		"check_depth_of_market": {
			"enabled": false,
			"bids_to_ask_delta": 1
		}
	},
	"exit_pricing": {
		"price_side": "other",
		"use_order_book": true,
		"order_book_top": 1
	},
	"pairlists": [
		{
			"method": "StaticPairList"
		}
	],
	"freqai": {
		"enabled": true,
		"purge_old_models": 4,
		"train_period_days": 15,
		"backtest_period_days": 7,
		"live_retrain_hours": 0,
		"identifier": "unique-id",
		"feature_parameters": {
			"include_timeframes": [
				"1m",
				"5m",
				"15m"
			],
			"include_corr_pairlist": [
				"BTC/USDT:USDT",
				"ETH/USDT:USDT"
			],
			"label_period_candles": 20,
			"include_shifted_candles": 2,
			"DI_threshold": 0.9,
			"weight_factor": 0.9,
			"principal_component_analysis": false,
			"use_SVM_to_remove_outliers": true,
			"indicator_periods_candles": [
				10,
				20
			],
			"plot_feature_importances": 0
		},
		"data_split_parameters": {
			"test_size": 0.33,
			"random_state": 1
		},
		"model_training_parameters": {}
	},
	"bot_name": "",
	"force_entry_enable": true,
	"initial_state": "running",
	"internals": {
		"process_throttle_secs": 5
	}
}
```
  2. Config for Freqtrade 
  ```{
	"max_open_trades": 5,
	"stake_currency": "USDT",
	"stake_amount": "unlimited",
	"tradable_balance_ratio": 0.99,
	"fiat_display_currency": "EUR",
	"dry_run": true,
	"amend_last_stake_amount": true,
	"dry_run_wallet": 100,
	"cancel_open_orders_on_exit": false,
	"trading_mode": "futures",
	"margin_mode": "",
	"unfilledtimeout": {
		"entry": 10,
		"exit": 10,
		"exit_timeout_count": 0,
		"unit": "minutes"
	},
	"entry_pricing": {
		"price_side": "other",
		"use_order_book": true,
		"order_book_top": 1,
		"price_last_balance": 0.0,
		"check_depth_of_market": {
			"enabled": false,
			"bids_to_ask_delta": 1
		}
	},
	"exit_pricing": {
		"price_side": "other",
		"use_order_book": true,
		"order_book_top": 1
	},
	"exchange": {
		"name": "bybit",
		"key": "",
		"secret": "",
		"ccxt_config": {},
		"ccxt_async_config": {},
		"pair_whitelist": [
			"BTC/USDT:USDT",
			"BCH/USDT:USDT",
			"ETH/USDT:USDT",
			"LINK/USDT:USDT",
			"LTC/USDT:USDT",
			"SOL/USDT:USDT",
			"BNB/USDT:USDT",
			"XRP/USDT:USDT",
			"ADA/USDT:USDT",
			"DOT/USDT:USDT",
			"ETC/USDT:USDT",
			"ALGO/USDT:USDT",
			"ZETA/USDT:USDT",
			"PYTH/USDT:USDT"
		],
		"pair_blacklist": []
	},
	"pairlists": [
		{
			"method": "StaticPairList"
		}
	],
	"telegram": {
		"enabled": false,
		"token": "",
		"chat_id": ""
	},
	"api_server": {
		"enabled": true,
		"listen_ip_address": "127.0.0.1",
		"listen_port": 8080,
		"verbosity": "error",
		"enable_openapi": false,
		"jwt_secret_key": "",
		"ws_token": "KYzfT_AAqNAux6AwqFaDSMvCLo_VYYFjig",
		"CORS_origins": [],
		"username": "freqtrader",
		"password": "12345"
	},
	"bot_name": "freqtrade",
	"initial_state": "running",
	"force_entry_enable": false,
	"internals": {
		"process_throttle_secs": 5
	}
}
```
  3. Download Data `freqtrade download-data --config config.json --days 300 -t 1m 5m 15m 30m `
  4. Backtest with the command above
  
### Observed Results:

  * Fatal Error was thrown
  * Backtesting Results was expected

### Relevant code exceptions or logs
```
2024-03-02 19:35:14,651 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/freqtrade/main.py", line 42, in main
    return_code = args['func'](args)
                  ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/freqtrade/commands/optimize_commands.py", line 58, in start_backtesting
    backtesting.start()
  File "/opt/homebrew/lib/python3.11/site-packages/freqtrade/optimize/backtesting.py", line 1401, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/freqtrade/optimize/backtesting.py", line 1318, in backtest_one_strategy
    preprocessed = self.strategy.advise_all_indicators(data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/freqtrade/strategy/interface.py", line 1378, in advise_all_indicators
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/freqtrade/strategy/interface.py", line 1378, in <dictcomp>
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/freqtrade/strategy/interface.py", line 1410, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sorenhahnert/Documents/freqtrade/freqtrade/templates/FreqaiExampleHybridStrategy.py", line 239, in populate_indicators
    dataframe = self.freqai.start(dataframe, metadata, self)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/freqtrade/freqai/freqai_interface.py", line 161, in start
    dk = self.start_backtesting(dataframe, metadata, self.dk, strategy)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/freqtrade/freqai/freqai_interface.py", line 323, in start_backtesting
    dataframe = self.dk.use_strategy_to_populate_indicators(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/freqtrade/freqai/data_kitchen.py", line 804, in use_strategy_to_populate_indicators
    dataframe = self.populate_features(dataframe.copy(), pair, strategy,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/freqtrade/freqai/data_kitchen.py", line 723, in populate_features
    informative_df = self.merge_features(informative_df, df_features, tf, tf, suffix)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/freqtrade/freqai/data_kitchen.py", line 688, in merge_features
    dataframe = merge_informative_pair(df_main, df_to_merge, tf, timeframe_inf=timeframe_inf,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/freqtrade/strategy/strategy_helper.py", line 82, in merge_informative_pair
    dataframe = pd.merge_ordered(dataframe, informative, fill_method="ffill", left_on='date',
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pandas/core/reshape/merge.py", line 436, in merge_ordered
    result = _merger(left, right)
             ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pandas/core/reshape/merge.py", line 415, in _merger
    return op.get_result()
           ^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pandas/core/reshape/merge.py", line 1933, in get_result
    raise TypeError("left_indexer cannot be None")
TypeError: left_indexer cannot be None
```

**Comment by cliverenwood** [comment]
Can be closed. I missed installing requirements for freqai.

**Comment by cliverenwood** [comment]
Close myself

**Comment by xmatthias** [comment]
@cliverenwood please make sure to **IMMEDIATELY** revoke your exchange keys and generate new ones (also, hope you had IP whitelisting enabled - so you're at least protected to some degree).

You've posted them in the above message (twice). 
Whilst i did remove them ... they're still in the message history - so it's still a pretty easy find if someone were to look for these.

**Comment by cliverenwood** [comment]
Oh damn! Thanks. Maybe put a hint in the preconfigured text for idiots like
me. Thanks.

Matthias ***@***.***> schrieb am So. 3. März 2024 um 11:52:
