### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'predict'

### ISSUE THREAD

**Issue by cliverenwood** [freqtrade/freqtrade#9893]
## Describe your environment

Operating system: MacOS 14.3.1 (23D60)
Python Version: Python 3.11.8
CCXT version: 4.2.51
Freqtrade Version: 2024.2

## Describe the problem:

I get an error with backtesting

### Steps to reproduce:

  1. freqtrade download-data --config config_examples/config_freqai.json --days 300 -t 1m 5m 15m 30m
  2. freqtrade backtesting --strategy FreqaiExampleHybridStrategy --strategy-path freqtrade/templates --config config_examples/config_freqai.json --freqaimodel LightGBMRegressor --timerange 20230508-20240301
  
### Observed Results:

  * Error is thrown
  * Backtest results where expected

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.
```
(.venv) sorenhahnert@MBP-von-Soren freqtrade % freqtrade backtesting --strategy FreqaiExampleHybridStrategy --strategy-path freqtrade/templates --config config_examples/config_freqai.json --freqaimodel LightGBMRegressor --timerange 20230508-20240301
2024-03-02 20:22:33,539 - freqtrade - INFO - freqtrade 2024.2
2024-03-02 20:22:33,541 - freqtrade.configuration.load_config - INFO - Using config: config_examples/config_freqai.json ...
2024-03-02 20:22:33,541 - freqtrade.loggers - INFO - Verbosity set to 0
2024-03-02 20:22:33,541 - freqtrade.configuration.configuration - INFO - Using additional Strategy lookup path: freqtrade/templates
2024-03-02 20:22:33,541 - freqtrade.configuration.configuration - WARNING - `force_entry_enable` RPC message enabled.
2024-03-02 20:22:33,541 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 5 ...
2024-03-02 20:22:33,541 - freqtrade.configuration.configuration - INFO - Parameter --timerange detected: 20230508-20240301 ...
2024-03-02 20:22:33,541 - freqtrade.configuration.configuration - INFO - Using user-data directory: /Users/sorenhahnert/Documents/freqtrade/user_data ...
2024-03-02 20:22:33,541 - freqtrade.configuration.configuration - INFO - Using data directory: /Users/sorenhahnert/Documents/freqtrade/user_data/data/bybit ...
2024-03-02 20:22:33,541 - freqtrade.configuration.configuration - INFO - Parameter --cache=day detected ...
2024-03-02 20:22:33,541 - freqtrade.configuration.configuration - INFO - Filter trades by timerange: 20230508-20240301
2024-03-02 20:22:33,541 - freqtrade.configuration.configuration - INFO - Using freqaimodel class name: LightGBMRegressor
2024-03-02 20:22:33,542 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2024-03-02 20:22:33,544 - freqtrade.exchange.check_exchange - WARNING - Exchange "bybit" is known to the the ccxt library, available for the bot, but not officially supported by the Freqtrade development team. It may work flawlessly (please report back) or have serious issues. Use it at your own discretion.
2024-03-02 20:22:33,544 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2024-03-02 20:22:33,544 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2024-03-02 20:22:33,545 - freqtrade.commands.optimize_commands - INFO - Starting freqtrade in Backtesting mode
2024-03-02 20:22:33,545 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2024-03-02 20:22:33,545 - freqtrade.exchange.exchange - INFO - Using CCXT 4.2.51
2024-03-02 20:22:33,545 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}}
2024-03-02 20:22:33,547 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}}
2024-03-02 20:22:33,550 - freqtrade.exchange.exchange - INFO - Using Exchange "Bybit"
2024-03-02 20:22:40,255 - freqtrade.exchange.exchange - INFO - Using cached leverage_tiers.
2024-03-02 20:22:40,256 - freqtrade.exchange.exchange - INFO - Done initializing 318 markets.
2024-03-02 20:22:40,258 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Bybit'...
2024-03-02 20:22:40,284 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy FreqaiExampleHybridStrategy from '/Users/sorenhahnert/Documents/freqtrade/freqtrade/templates/FreqaiExampleHybridStrategy.py'...
2024-03-02 20:22:40,284 - freqtrade.strategy.hyper - INFO - Found no parameter file.
2024-03-02 20:22:40,284 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 1m.
2024-03-02 20:22:40,284 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2024-03-02 20:22:40,284 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 100.
2024-03-02 20:22:40,284 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'entry': 10, 'exit': 30, 'exit_timeout_count': 0, 'unit': 'minutes'}.
2024-03-02 20:22:40,284 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'max_open_trades' with value in config file: 5.
2024-03-02 20:22:40,284 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'60': 0.01, '30': 0.02, '0': 0.04}
2024-03-02 20:22:40,284 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 1m
2024-03-02 20:22:40,284 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.05
2024-03-02 20:22:40,284 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2024-03-02 20:22:40,284 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2024-03-02 20:22:40,284 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2024-03-02 20:22:40,284 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2024-03-02 20:22:40,284 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: True
2024-03-02 20:22:40,284 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'entry': 'limit', 'exit': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False, 'stoploss_on_exchange_interval': 60}
2024-03-02 20:22:40,284 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'entry': 'GTC', 'exit': 'GTC'}
2024-03-02 20:22:40,284 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2024-03-02 20:22:40,284 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 100
2024-03-02 20:22:40,284 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2024-03-02 20:22:40,284 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 30
2024-03-02 20:22:40,284 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'entry': 10, 'exit': 30, 'exit_timeout_count': 0, 'unit': 'minutes'}
2024-03-02 20:22:40,284 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_exit_signal: True
2024-03-02 20:22:40,284 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_only: False
2024-03-02 20:22:40,284 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_entry_signal: False
2024-03-02 20:22:40,284 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_offset: 0.0
2024-03-02 20:22:40,284 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2024-03-02 20:22:40,284 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2024-03-02 20:22:40,284 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: False
2024-03-02 20:22:40,284 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1
2024-03-02 20:22:40,284 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_open_trades: 5
2024-03-02 20:22:40,284 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2024-03-02 20:22:40,288 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from '/opt/homebrew/lib/python3.11/site-packages/freqtrade/plugins/pairlist/StaticPairList.py'...
2024-03-02 20:22:40,292 - freqtrade.data.dataprovider - INFO - Increasing startup_candle_count for freqai on 1m to 21630
2024-03-02 20:22:40,294 - freqtrade.data.history.history_utils - INFO - Using indicator startup period: 21630 ...
2024-03-02 20:22:40,312 - freqtrade.data.history.idatahandler - WARNING - BTC/USDT:USDT, futures, 1m, data starts at 2023-05-07 00:00:00
2024-03-02 20:22:40,439 - freqtrade.data.history.idatahandler - WARNING - BCH/USDT:USDT, futures, 1m, data starts at 2023-05-07 00:00:00
2024-03-02 20:22:40,563 - freqtrade.data.history.idatahandler - WARNING - ETH/USDT:USDT, futures, 1m, data starts at 2023-05-07 00:00:00
2024-03-02 20:22:40,689 - freqtrade.data.history.idatahandler - WARNING - LINK/USDT:USDT, futures, 1m, data starts at 2023-05-07 00:00:00
2024-03-02 20:22:40,813 - freqtrade.data.history.idatahandler - WARNING - LTC/USDT:USDT, futures, 1m, data starts at 2023-05-07 00:00:00
2024-03-02 20:22:40,936 - freqtrade.data.history.idatahandler - WARNING - SOL/USDT:USDT, futures, 1m, data starts at 2023-05-07 00:00:00
2024-03-02 20:22:41,064 - freqtrade.data.history.idatahandler - WARNING - BNB/USDT:USDT, futures, 1m, data starts at 2023-05-07 00:00:00
2024-03-02 20:22:41,183 - freqtrade.data.history.idatahandler - WARNING - XRP/USDT:USDT, futures, 1m, data starts at 2023-05-07 00:00:00
2024-03-02 20:22:41,304 - freqtrade.data.history.idatahandler - WARNING - ADA/USDT:USDT, futures, 1m, data starts at 2023-05-07 00:00:00
2024-03-02 20:22:41,422 - freqtrade.data.history.idatahandler - WARNING - DOT/USDT:USDT, futures, 1m, data starts at 2023-05-07 00:00:00
2024-03-02 20:22:41,540 - freqtrade.data.history.idatahandler - WARNING - ETC/USDT:USDT, futures, 1m, data starts at 2023-05-07 00:00:00
2024-03-02 20:22:41,655 - freqtrade.data.history.idatahandler - WARNING - ALGO/USDT:USDT, futures, 1m, data starts at 2023-05-07 00:00:00
2024-03-02 20:22:41,764 - freqtrade.data.history.idatahandler - WARNING - ZETA/USDT:USDT, futures, 1m, data starts at 2024-02-01 06:00:00
2024-03-02 20:22:41,783 - freqtrade.data.history.idatahandler - WARNING - PYTH/USDT:USDT, futures, 1m, data starts at 2023-11-21 07:27:00
2024-03-02 20:22:41,822 - freqtrade.optimize.backtesting - INFO - Loading data from 2023-05-07 00:00:00 up to 2024-03-01 00:00:00 (299 days).
2024-03-02 20:22:41,875 - freqtrade.data.history.idatahandler - WARNING - ZETA/USDT:USDT, funding_rate, 8h, data starts at 2024-02-01 00:00:00
2024-03-02 20:22:41,879 - freqtrade.data.history.idatahandler - WARNING - PYTH/USDT:USDT, funding_rate, 8h, data starts at 2023-11-21 00:00:00
2024-03-02 20:22:41,941 - freqtrade.data.history.idatahandler - WARNING - ZETA/USDT:USDT, mark, 4h, data starts at 2024-02-01 04:00:00
2024-03-02 20:22:41,945 - freqtrade.data.history.idatahandler - WARNING - PYTH/USDT:USDT, mark, 4h, data starts at 2023-11-21 04:00:00
2024-03-02 20:22:41,955 - freqtrade.optimize.backtesting - INFO - Dataload complete. Calculating indicators
2024-03-02 20:22:41,957 - freqtrade.optimize.backtesting - INFO - Running backtesting for Strategy FreqaiExampleHybridStrategy
2024-03-02 20:22:42,412 - freqtrade.resolvers.iresolver - WARNING - Could not import /opt/homebrew/lib/python3.11/site-packages/freqtrade/freqai/prediction_models/ReinforcementLearner_multiproc.py due to 'No module named 'sb3_contrib''
2024-03-02 20:22:42,413 - freqtrade.resolvers.iresolver - WARNING - Could not import /opt/homebrew/lib/python3.11/site-packages/freqtrade/freqai/prediction_models/CatboostClassifierMultiTarget.py due to 'No module named 'catboost''
2024-03-02 20:22:42,425 - freqtrade.resolvers.iresolver - WARNING - Could not import /opt/homebrew/lib/python3.11/site-packages/freqtrade/freqai/prediction_models/CatboostRegressor.py due to 'No module named 'catboost''
2024-03-02 20:22:42,425 - freqtrade.resolvers.iresolver - WARNING - Could not import /opt/homebrew/lib/python3.11/site-packages/freqtrade/freqai/prediction_models/CatboostClassifier.py due to 'No module named 'catboost''
2024-03-02 20:22:42,426 - freqtrade.resolvers.iresolver - WARNING - Could not import /opt/homebrew/lib/python3.11/site-packages/freqtrade/freqai/prediction_models/PyTorchMLPClassifier.py due to 'No module named 'torch''
2024-03-02 20:22:42,427 - freqtrade.resolvers.iresolver - WARNING - Could not import /opt/homebrew/lib/python3.11/site-packages/freqtrade/freqai/prediction_models/PyTorchTransformerRegressor.py due to 'No module named 'torch''
2024-03-02 20:22:42,427 - freqtrade.resolvers.iresolver - INFO - Using resolved freqaimodel LightGBMRegressor from '/opt/homebrew/lib/python3.11/site-packages/freqtrade/freqai/prediction_models/LightGBMRegressor.py'...
2024-03-02 20:22:42,427 - freqtrade.freqai.freqai_interface - INFO - Backtesting module configured to save all models.
2024-03-02 20:22:42,427 - freqtrade.freqai.data_drawer - INFO - Could not find existing datadrawer, starting from scratch
2024-03-02 20:22:42,427 - freqtrade.freqai.data_drawer - INFO - Could not find existing historic_predictions, starting from scratch
2024-03-02 20:22:42,427 - freqtrade.freqai.freqai_interface - INFO - Set fresh train queue from whitelist. Queue: ['BTC/USDT:USDT', 'BCH/USDT:USDT', 'ETH/USDT:USDT', 'LINK/USDT:USDT', 'LTC/USDT:USDT', 'SOL/USDT:USDT', 'BNB/USDT:USDT', 'XRP/USDT:USDT', 'ADA/USDT:USDT', 'DOT/USDT:USDT', 'ETC/USDT:USDT', 'ALGO/USDT:USDT', 'ZETA/USDT:USDT', 'PYTH/USDT:USDT']
2024-03-02 20:22:42,428 - freqtrade.strategy.hyper - INFO - No params for buy found, using default values.
2024-03-02 20:22:42,428 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): buy_rsi = 30
2024-03-02 20:22:42,428 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): exit_short_rsi = 30
2024-03-02 20:22:42,428 - freqtrade.strategy.hyper - INFO - No params for sell found, using default values.
2024-03-02 20:22:42,428 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): sell_rsi = 70
2024-03-02 20:22:42,428 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): short_rsi = 70
2024-03-02 20:22:42,428 - freqtrade.strategy.hyper - INFO - No params for protection found, using default values.
2024-03-02 20:22:42,437 - freqtrade.freqai.freqai_interface - INFO - Training 43 timeranges
2024-03-02 20:22:42,439 - freqtrade.freqai.freqai_interface - INFO - Training BTC/USDT:USDT, 1/14 pairs from 2023-04-23 00:00:00 to 2023-05-08 00:00:00, 1/43 trains
2024-03-02 20:22:42,439 - freqtrade.freqai.data_kitchen - INFO - Could not find backtesting prediction file at /Users/sorenhahnert/Documents/freqtrade/user_data/models/unique-id/backtesting_predictions/cb_btc_1683504000_prediction.feather
2024-03-02 20:22:43,273 - freqtrade.data.dataprovider - INFO - Increasing startup_candle_count for freqai on 5m to 4350
2024-03-02 20:22:43,273 - freqtrade.data.dataprovider - INFO - Loading data for BTC/USDT:USDT 5m from 2023-04-22 21:30:00 to 2024-03-01 00:00:00
2024-03-02 20:22:43,280 - freqtrade.data.history.idatahandler - WARNING - BTC/USDT:USDT, futures, 5m, data starts at 2023-05-07 00:00:00
2024-03-02 20:22:43,832 - freqtrade.data.dataprovider - INFO - Increasing startup_candle_count for freqai on 15m to 1470
2024-03-02 20:22:43,832 - freqtrade.data.dataprovider - INFO - Loading data for BTC/USDT:USDT 15m from 2023-04-22 16:30:00 to 2024-03-01 00:00:00
2024-03-02 20:22:43,838 - freqtrade.data.history.idatahandler - WARNING - BTC/USDT:USDT, futures, 15m, data starts at 2023-05-07 00:00:00
2024-03-02 20:22:44,967 - freqtrade.data.dataprovider - INFO - Increasing startup_candle_count for freqai on 1m to 21630
2024-03-02 20:22:44,968 - freqtrade.data.dataprovider - INFO - Loading data for ETH/USDT:USDT 1m from 2023-04-22 23:30:00 to 2024-03-01 00:00:00
2024-03-02 20:22:44,985 - freqtrade.data.history.idatahandler - WARNING - ETH/USDT:USDT, futures, 1m, data starts at 2023-05-07 00:00:00
2024-03-02 20:22:47,639 - freqtrade.data.dataprovider - INFO - Increasing startup_candle_count for freqai on 5m to 4350
2024-03-02 20:22:47,639 - freqtrade.data.dataprovider - INFO - Loading data for ETH/USDT:USDT 5m from 2023-04-22 21:30:00 to 2024-03-01 00:00:00
2024-03-02 20:22:47,650 - freqtrade.data.history.idatahandler - WARNING - ETH/USDT:USDT, futures, 5m, data starts at 2023-05-07 00:00:00
2024-03-02 20:22:50,274 - freqtrade.data.dataprovider - INFO - Increasing startup_candle_count for freqai on 15m to 1470
2024-03-02 20:22:50,275 - freqtrade.data.dataprovider - INFO - Loading data for ETH/USDT:USDT 15m from 2023-04-22 16:30:00 to 2024-03-01 00:00:00
2024-03-02 20:22:50,284 - freqtrade.data.history.idatahandler - WARNING - ETH/USDT:USDT, futures, 15m, data starts at 2023-05-07 00:00:00
2024-03-02 20:22:53,353 - freqtrade.freqai.freqai_interface - INFO - Could not find model at /Users/sorenhahnert/Documents/freqtrade/user_data/models/unique-id/sub-train-BTC_1683504000/cb_btc_1683504000
2024-03-02 20:22:53,354 - freqtrade.freqai.base_models.BaseRegressionModel - INFO - -------------------- Starting training BTC/USDT:USDT --------------------
2024-03-02 20:22:53,359 - freqtrade.freqai.data_kitchen - INFO - BTC/USDT:USDT: dropped 629 training points due to NaNs in populated dataset 1440.
2024-03-02 20:22:53,359 - freqtrade.freqai.base_models.BaseRegressionModel - INFO - -------------------- Training on data from 2023-05-07 to 2023-05-07 --------------------
2024-03-02 20:22:53,362 - datasieve.pipeline - INFO - VarianceThreshold will remove 1 features from the dataset.on transform. ['%-day_of_week']
2024-03-02 20:22:53,368 - datasieve.pipeline - INFO - SVM detected 17 data points as outliers.
2024-03-02 20:22:53,456 - freqtrade.freqai.freqai_interface - WARNING - Training BTC/USDT:USDT raised exception ValueError. Message: could not convert string to float: 'down', skipping.
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/freqtrade/freqai/freqai_interface.py", line 351, in start_backtesting
    self.model = self.train(dataframe_train, pair, dk)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/freqtrade/freqai/base_models/BaseRegressionModel.py", line 63, in train
    dd["train_labels"], _, _ = dk.label_pipeline.fit_transform(dd["train_labels"])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/datasieve/pipeline.py", line 77, in fit_transform
    X, y, sample_weight, feature_list = trans.fit_transform(
                                        ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/datasieve/transforms/base_transform.py", line 62, in fit_transform
    self.fit(X, y, sample_weight, feature_list)
  File "/opt/homebrew/lib/python3.11/site-packages/datasieve/transforms/sklearn_wrapper.py", line 22, in fit
    self._skl = self._skl.fit(X, y=y)
                ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/sklearn/preprocessing/_data.py", line 450, in fit
    return self.partial_fit(X, y)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/sklearn/preprocessing/_data.py", line 490, in partial_fit
    X = self._validate_data(
        ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/sklearn/base.py", line 633, in _validate_data
    out = check_array(X, input_name="X", **check_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/sklearn/utils/validation.py", line 997, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/sklearn/utils/_array_api.py", line 521, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'down'
2024-03-02 20:22:53,463 - freqtrade.freqai.freqai_interface - INFO - Saving metadata to disk.
2024-03-02 20:22:53,617 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/freqtrade/main.py", line 42, in main
    return_code = args['func'](args)
                  ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/freqtrade/commands/optimize_commands.py", line 58, in start_backtesting
    backtesting.start()
  File "/opt/homebrew/lib/python3.11/site-packages/freqtrade/optimize/backtesting.py", line 1401, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/freqtrade/optimize/backtesting.py", line 1318, in backtest_one_strategy
    preprocessed = self.strategy.advise_all_indicators(data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/freqtrade/strategy/interface.py", line 1378, in advise_all_indicators
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/freqtrade/strategy/interface.py", line 1378, in <dictcomp>
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/freqtrade/strategy/interface.py", line 1410, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sorenhahnert/Documents/freqtrade/freqtrade/templates/FreqaiExampleHybridStrategy.py", line 239, in populate_indicators
    dataframe = self.freqai.start(dataframe, metadata, self)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/freqtrade/freqai/freqai_interface.py", line 161, in start
    dk = self.start_backtesting(dataframe, metadata, self.dk, strategy)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/freqtrade/freqai/freqai_interface.py", line 372, in start_backtesting
    pred_df, do_preds = self.predict(dataframe_backtest, dk)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/freqtrade/freqai/base_models/BaseRegressionModel.py", line 107, in predict
    predictions = self.model.predict(dk.data_dictionary["prediction_features"])
                  ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'predict'
```

```
{
	"trading_mode": "futures",
	"margin_mode": "isolated",
	"max_open_trades": 5,
	"stake_currency": "USDT",
	"stake_amount": 100,
	"tradable_balance_ratio": 1,
	"fiat_display_currency": "USD",
	"dry_run": true,
	"timeframe": "1m",
	"dry_run_wallet": 1000,
	"cancel_open_orders_on_exit": true,
	"unfilledtimeout": {
		"entry": 10,
		"exit": 30
	},
	"exchange": {
		"name": "bybit",
		"key": "",
		"secret": "",
		"ccxt_config": {},
		"ccxt_async_config": {},
		"pair_whitelist": [
			"BTC/USDT:USDT",
			"BCH/USDT:USDT",
			"ETH/USDT:USDT",
			"LINK/USDT:USDT",
			"LTC/USDT:USDT",
			"SOL/USDT:USDT",
			"BNB/USDT:USDT",
			"XRP/USDT:USDT",
			"ADA/USDT:USDT",
			"DOT/USDT:USDT",
			"ETC/USDT:USDT",
			"ALGO/USDT:USDT",
			"ZETA/USDT:USDT",
			"PYTH/USDT:USDT"
		],
		"pair_blacklist": []
	},
	"entry_pricing": {
		"price_side": "other",
		"use_order_book": true,
		"order_book_top": 1,
		"price_last_balance": 0.0,
		"check_depth_of_market": {
			"enabled": false,
			"bids_to_ask_delta": 1
		}
	},
	"exit_pricing": {
		"price_side": "other",
		"use_order_book": true,
		"order_book_top": 1
	},
	"pairlists": [
		{
			"method": "StaticPairList"
		}
	],
	"freqai": {
		"enabled": true,
		"purge_old_models": 4,
		"train_period_days": 15,
		"backtest_period_days": 7,
		"live_retrain_hours": 0,
		"identifier": "unique-id",
		"feature_parameters": {
			"include_timeframes": [
				"1m",
				"5m",
				"15m"
			],
			"include_corr_pairlist": [
				"BTC/USDT:USDT",
				"ETH/USDT:USDT"
			],
			"label_period_candles": 20,
			"include_shifted_candles": 2,
			"DI_threshold": 0.9,
			"weight_factor": 0.9,
			"principal_component_analysis": false,
			"use_SVM_to_remove_outliers": true,
			"indicator_periods_candles": [
				10,
				20
			],
			"plot_feature_importances": 0,
			"data_kitchen_thread_count": 64
		},
		"data_split_parameters": {
			"test_size": 0.33,
			"random_state": 1
		},
		"model_training_parameters": {}
	},
	"bot_name": "soerens_bot",
	"force_entry_enable": true,
	"initial_state": "running",
	"internals": {
		"process_throttle_secs": 5
	}
}
```

**Comment by cliverenwood** [comment]
Managed it. Can be closed.

**Comment by xmatthias** [comment]
As posted in the other issue ... please make sure to revoke your API keys - and for future issues - make sure to remove them before posting your configuration!

we'll NEVER need YOUR exchange keys ... and if you're asked for them - then you're talking to a scammer.

**Comment by amrabdalbadee** [comment]
> Managed it. Can be closed.

How did you manage it ?

**Comment by FunkerBunker** [comment]
How?

**Comment by stash86** [comment]
@amrabdalbadee @FunkerBunker please open a new issue instead. Remember to fill in the template that we asked.
