### ISSUE TITLE
Not useable this bot and "Config file not found"

### ISSUE THREAD

**Issue by oti5** [freqtrade/freqtrade#9951]
## Describe your environment

  * Operating system: Ubuntu 22.04 (Zorin OS 17.1 Pro)
  * Python Version: Pyzhon 3.10 (`python -V`)
  * CCXT version: ccxt==4.2.51 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2024.2 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

  1. I did configure this bot
  2. wrote ```freqtrade trade --config config_examples/config_freqai.example.json --strategy FreqaiExampleStrategy --freqaimodel LightGBMRegressor --strategy-path freqtrade/templates``` (or simply ```freqtrade trade```)
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
freqtrade trade --config config_examples/config_freqai.example.json --strategy FreqaiExampleStrategy --freqaimodel LightGBMRegressor --strategy-path freqtrade/templates
2024-03-15 11:02:09,723 - freqtrade - INFO - freqtrade 2024.2
2024-03-15 11:02:10,171 - freqtrade.worker - INFO - Starting worker 2024.2
2024-03-15 11:02:10,171 - freqtrade.configuration.load_config - INFO - Using config: config_examples/config_freqai.example.json ...
2024-03-15 11:02:10,171 - freqtrade.commands.trade_commands - ERROR - Config file "config_examples/config_freqai.example.json" not found! Please create a config file or check whether it exists.
2024-03-15 11:02:10,171 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/farcry/freqtrade/freqtrade/configuration/load_config.py", line 61, in load_config_file
    with Path(path).open() if path != '-' else sys.stdin as file:
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: 'config_examples/config_freqai.example.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/farcry/freqtrade/freqtrade/commands/trade_commands.py", line 24, in start_trading
    worker = Worker(args)
  File "/home/farcry/freqtrade/freqtrade/worker.py", line 37, in __init__
    self._init(False)
  File "/home/farcry/freqtrade/freqtrade/worker.py", line 50, in _init
    self._config = Configuration(self._args, None).get_config()
  File "/home/farcry/freqtrade/freqtrade/configuration/configuration.py", line 42, in get_config
    self.config = self.load_config()
  File "/home/farcry/freqtrade/freqtrade/configuration/configuration.py", line 68, in load_config
    config: Config = load_from_files(self.args.get("config", []))
  File "/home/farcry/freqtrade/freqtrade/configuration/load_config.py", line 102, in load_from_files
    config_tmp = load_config_file(str(file))
  File "/home/farcry/freqtrade/freqtrade/configuration/load_config.py", line 64, in load_config_file
    raise OperationalException(
freqtrade.exceptions.OperationalException: Config file "config_examples/config_freqai.example.json" not found! Please create a config file or check whether it exists.

  ```

**Comment by xmatthias** [comment]
well the file does not exist.

what does `ls -l config_examples/config_freqai.example.json` give you? (or `ls -l config_examples/`)?
also - what does `git status` show?

There can be many reasons - the most likely one is that you're not at the root of the repository (in your case most likely `/home/farcry/freqtrade/`) - or that you installed freqtrade directly from pip - not via github (which means example files will not be available) - or that the files were deleted or moved.
