### ISSUE TITLE
In Docker container: ERROR - Fatal exception! 

### ISSUE THREAD

**Issue by oti5** [freqtrade/freqtrade#9952]
## Describe your environment

  * Operating system: Ubuntu 22.04 (Zorin OS 17.1 Pro)
  * Python Version: 3.10.12 (`python -V`)
  * CCXT version: ? (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2024.2 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

  1. Just configured this freqtrad (dockerized) based from https://www.freqtrade.io/en/stable/docker_quickstart/ guide
  2. just start with ```docker compose up -d```
   
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
2024-03-15 10:13:20,468 - freqtrade - INFO - freqtrade 2024.2
2024-03-15 10:13:20,824 - freqtrade.worker - INFO - Starting worker 2024.2
2024-03-15 10:13:20,825 - freqtrade.configuration.load_config - INFO - Using config: /freqtrade/user_data/config.json ...
2024-03-15 10:13:20,825 - freqtrade.loggers - INFO - Verbosity set to 0
2024-03-15 10:13:20,825 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
2024-03-15 10:13:20,826 - freqtrade.configuration.configuration - INFO - Parameter --db-url detected ...
2024-03-15 10:13:20,826 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2024-03-15 10:13:20,826 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:////freqtrade/user_data/tradesv3.sqlite"
2024-03-15 10:13:20,826 - freqtrade.configuration.configuration - INFO - Using max_open_trades: -1 ...
2024-03-15 10:13:20,833 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2024-03-15 10:13:20,833 - freqtrade.configuration.directory_operations - INFO - Created data directory: None
2024-03-15 10:13:20,833 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/coinex ...
2024-03-15 10:13:20,834 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2024-03-15 10:13:20,836 - freqtrade.exchange.check_exchange - WARNING - Exchange "coinex" is known to the the ccxt library, available for the bot, but not officially supported by the Freqtrade development team. It may work flawlessly (please report back) or have serious issues. Use it at your own discretion.
2024-03-15 10:13:20,836 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2024-03-15 10:13:20,847 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy SampleStrategy from '/freqtrade/user_data/strategies/sample_strategy.py'...
2024-03-15 10:13:20,847 - freqtrade.strategy.hyper - INFO - Found no parameter file.
2024-03-15 10:13:20,847 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: BTC.
2024-03-15 10:13:20,847 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: unlimited.
2024-03-15 10:13:20,847 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}.
2024-03-15 10:13:20,847 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'max_open_trades' with value in config file: inf.
2024-03-15 10:13:20,848 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'60': 0.01, '30': 0.02, '0': 0.04}
2024-03-15 10:13:20,848 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 5m
2024-03-15 10:13:20,848 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.1
2024-03-15 10:13:20,848 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2024-03-15 10:13:20,848 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2024-03-15 10:13:20,848 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2024-03-15 10:13:20,848 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2024-03-15 10:13:20,848 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: True
2024-03-15 10:13:20,848 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'entry': 'limit', 'exit': 'limit', 'stoploss': 'market', 'stoploss_on_exchange': False}
2024-03-15 10:13:20,848 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'entry': 'GTC', 'exit': 'GTC'}
2024-03-15 10:13:20,848 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: BTC
2024-03-15 10:13:20,848 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: unlimited
2024-03-15 10:13:20,848 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2024-03-15 10:13:20,848 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 200
2024-03-15 10:13:20,848 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}
2024-03-15 10:13:20,848 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_exit_signal: True
2024-03-15 10:13:20,848 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_only: False
2024-03-15 10:13:20,848 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_entry_signal: False
2024-03-15 10:13:20,848 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_offset: 0.0
2024-03-15 10:13:20,848 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2024-03-15 10:13:20,848 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2024-03-15 10:13:20,848 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: False
2024-03-15 10:13:20,848 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1
2024-03-15 10:13:20,849 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_open_trades: inf
2024-03-15 10:13:20,849 - freqtrade.commands.trade_commands - ERROR - `max_open_trades` and `stake_amount` cannot both be unlimited.
2024-03-15 10:13:20,849 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 24, in start_trading
    worker = Worker(args)
             ^^^^^^^^^^^^
  File "/freqtrade/freqtrade/worker.py", line 37, in __init__
    self._init(False)
  File "/freqtrade/freqtrade/worker.py", line 53, in _init
    self.freqtrade = FreqtradeBot(self._config)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/freqtradebot.py", line 74, in __init__
    validate_config_consistency(config)
  File "/freqtrade/freqtrade/configuration/config_validation.py", line 85, in validate_config_consistency
    _validate_unlimited_amount(conf)
  File "/freqtrade/freqtrade/configuration/config_validation.py", line 106, in _validate_unlimited_amount
    raise OperationalException("`max_open_trades` and `stake_amount` cannot both be unlimited.")
freqtrade.exceptions.OperationalException: `max_open_trades` and `stake_amount` cannot both be unlimited.

  ```

**Comment by stash86** [comment]
well, the last line tells you what the issue is. Please learn how to read, then fix the issue

**Comment by xmatthias** [comment]
>  `max_open_trades` and `stake_amount` cannot both be unlimited.

Exactly this  - there's nothing further to add - fix your configuration, and it'll work.
