### ISSUE TITLE
ERROR - Unexpected error <class 'builtin_function_or_method'> is not convertible to datetime

### ISSUE THREAD

**Issue by peasant-try** [freqtrade/freqtrade#9960]
My environment:
  * Operating system: Windows 11
  * Python Version: 3.11.5
  * CCXT version: 4.1.76
  * Freqtrade Version: freqtrade 2023.12-dev-7d281602f
  
## Your question

I'm getting a very weird error when trying to dry run my Reinforced Learning based strategy. I'm out of ideas so i decided to open a ticket here hoping to get an insight of what's happening or how to solve it. Here's the error i'm getting:
```2024-03-17 00:50:01,104 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error <class 'builtin_function_or_method'> is not convertible to datetime, 
at position 1028 calling <bound method IStrategy._analyze_ticker_internal of <saturnRsiPivot.saturnRsiPivot object at 0x0000021B8412AB50>>
Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Documents\Trading\Freqtrade\freqtrade\freqtrade\strategy\strategy_wrapper.py", line 27, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Documents\Trading\Freqtrade\freqtrade\freqtrade\strategy\interface.py", line 873, in _analyze_ticker_internal
    dataframe = self.analyze_ticker(dataframe, metadata)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Documents\Trading\Freqtrade\freqtrade\freqtrade\strategy\interface.py", line 851, in analyze_ticker
    dataframe = self.advise_indicators(dataframe, metadata)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Documents\Trading\Freqtrade\freqtrade\freqtrade\strategy\interface.py", line 1378, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Documents\Trading\Freqtrade\freqtrade\user_data\strategies\saturnRsiPivot.py", line 399, in populate_indicators
    dataframe = self.freqai.start(dataframe, metadata, self)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Documents\Trading\Freqtrade\freqtrade\freqtrade\freqai\freqai_interface.py", line 149, in start
    dk = self.start_live(dataframe, metadata, strategy, self.dk)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Documents\Trading\Freqtrade\freqtrade\freqtrade\freqai\freqai_interface.py", line 443, in start_live
    self.build_strategy_return_arrays(dataframe, dk, metadata["pair"], trained_timestamp)
  File "C:\Users\user\OneDrive\Documents\Trading\Freqtrade\freqtrade\freqtrade\freqai\freqai_interface.py", line 460, in build_strategy_return_arrays        
    self.dd.set_initial_return_values(pair, pred_df, dataframe)
  File "C:\Users\user\OneDrive\Documents\Trading\Freqtrade\freqtrade\freqtrade\freqai\data_drawer.py", line 293, in set_initial_return_values
    hist_preds["date_pred"] = pd.to_datetime(hist_preds["date_pred"])
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\miniconda3\envs\freqtrade\Lib\site-packages\pandas\core\tools\datetimes.py", line 1112, in to_datetime
    values = convert_listlike(arg._values, format)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\miniconda3\envs\freqtrade\Lib\site-packages\pandas\core\tools\datetimes.py", line 490, in _convert_listlike_datetimes
    result, tz_parsed = objects_to_datetime64ns(
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\miniconda3\envs\freqtrade\Lib\site-packages\pandas\core\arrays\datetimes.py", line 2346, in objects_to_datetime64ns
    result, tz_parsed = tslib.array_to_datetime(
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "tslib.pyx", line 403, in pandas._libs.tslib.array_to_datetime
  File "tslib.pyx", line 552, in pandas._libs.tslib.array_to_datetime
  File "tslib.pyx", line 541, in pandas._libs.tslib.array_to_datetime
TypeError: <class 'builtin_function_or_method'> is not convertible to datetime, at position 1028
2024-03-17 00:50:01,113 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair BTC/USDT:USDT: <class
'builtin_function_or_method'> is not convertible to datetime, at position 1028
```
Also, here's my config.json file (I redacted my keys and sensible data):
```
{
    "max_open_trades": 10,
    "stake_currency": "USDT",
    "stake_amount": "unlimited",
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "dry_run": true,
    "dry_run_wallet": 20000,
    "cancel_open_orders_on_exit": false,
    "trading_mode": "futures",
    "margin_mode": "isolated",
    "unfilledtimeout": {
        "entry": 10,
        "exit": 10,
        "exit_timeout_count": 0,
        "unit": "minutes"
    },
    "freqai": {
        "enabled": true,
        "purge_old_models": 2,
        "train_period_days": 30,
        "backtest_period_days": 7,
        "identifier" : "saturn-dev",
        "feature_parameters" : {
            "include_timeframes": ["1h","1d","3d"],
            "include_corr_pairlist": [
            ],
            "label_period_candles": 24,
            "include_shifted_candles": 2,
            "indicator_periods_candles": [7, 14]
        },
        "data_split_parameters" : {
            "test_size": 0.2
        },
        "rl_config": {
            "train_cycles": 25,
            "max_trade_duration_candles": 300,
            "max_training_drawdown_pct": 0.02,
            "cpu_count": 8,
            "model_type": "DQN",
            "policy_type": "MlpPolicy",
            "model_reward_parameters": {
                "rr": 1,
                "profit_aim": 0.025
            }
        }
    },
    "entry_pricing": {
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1,
        "price_last_balance": 0.0,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "exit_pricing":{
        "price_side": "other",
        "use_order_book": true,
        "order_book_top": 1
    },
    "exchange": {
        "name": "binance",
        "key": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        "secret": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        "ccxt_config": {},
        "ccxt_async_config": {},
        "pair_whitelist": [
            "LINK/USDT:USDT",
            "BTC/USDT:USDT",
            "ETH/USDT:USDT"
        ],
        "pair_blacklist": [
            "BNB/.*"
        ]
    },
    "pairlists": [
        {
            "method": "StaticPairList",
            "number_assets": 20,
            "sort_key": "quoteVolume",
            "min_value": 0,
            "refresh_period": 1800
        }
    ],
    "telegram": {
        "enabled": true,
        "token": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        "chat_id": "AAAAAAAAAAA"
    },
    "api_server": {
        "enabled": true,
        "listen_ip_address": "127.0.0.1",
        "listen_port": 8080,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        "ws_token": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        "CORS_origins": [],
        "username": "AAAAAAAAAAAAAAAA",
        "password": "AAAAAAAAAAAAAA"
    },
    "bot_name": "freqtrade",
    "initial_state": "running",
    "force_entry_enable": false,
    "internals": {
        "process_throttle_secs": 5
    },
    "logging": {
        "version": 1,
        "root": {
            "level": "INFO",
            "handlers": ["console", "file"]
        },
        "handlers": {
            "console": {
                "class": "logging.StreamHandler",
                "level": "INFO",
                "formatter": "simple"
            },
            "file": {
                "class": "logging.FileHandler",
                "filename": "freqtrade.log",
                "level": "DEBUG",
                "formatter": "simple"
            }
        },
        "formatters": {
            "simple": {
                "format": "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
            }
        }
    }
}
```
And finally, here's my strategy code:
```python 
# pragma pylint: disable=missing-docstring, invalid-name, pointless-string-statement
# flake8: noqa: F401
# isort: skip_file
# --- Do not remove these libs ---
import numpy as np
import pandas as pd
from pandas import DataFrame
from datetime import datetime
from typing import Optional
from functools import reduce
from freqtrade.strategy import (IStrategy, CategoricalParameter)
# --------------------------------
# Add your lib to import here
import talib.abstract as ta
from freqtrade.optimize.space import Categorical, Dimension, Integer, SKDecimal


class saturnRsiPivot(IStrategy):
    class HyperOpt:
        # Define a custom stoploss space.
        def stoploss_space(self):
            return [SKDecimal(-1, -0.01, decimals=2, name='stoploss')]

        # Define custom ROI space
        def roi_space(self) -> list[Dimension]:
            return [
                Integer(10, 60000, name='roi_t1'),
                Integer(10, 30000, name='roi_t2'),
                Integer(10, 15000, name='roi_t3'),
                Integer(10, 7500, name='roi_t4'),
                Integer(10, 3000, name='roi_t5'),
                SKDecimal(0.2, 3, decimals=2, name='roi_p1'),
                SKDecimal(0.1, 1.4, decimals=2, name='roi_p2'),
                SKDecimal(0.05, 0.7, decimals=2, name='roi_p3'),
                SKDecimal(0.03, 0.5, decimals=2, name='roi_p4'),
                SKDecimal(0.01, 0.25, decimals=2, name='roi_p5'),
            ]

        def generate_roi_table(self,params: dict) -> dict[int, float]:

            roi_table = {}
            roi_table[0] = params['roi_p1'] + params['roi_p2'] + params['roi_p3']
            roi_table[params['roi_t3']] = params['roi_p1'] + params['roi_p2']
            roi_table[params['roi_t3'] + params['roi_t2']] = params['roi_p1']
            roi_table[params['roi_t3'] + params['roi_t2'] + params['roi_t1']] = 0

            return roi_table

        def trailing_space(self) -> list[Dimension]:
            # All parameters here are mandatory, you can only modify their type or the range.
            return [
                # Fixed to true, if optimizing trailing_stop we assume to use trailing stop
                # at all times.
                Categorical([True], name='trailing_stop'),

                SKDecimal(0.01, 1, decimals=3, name='trailing_stop_positive'),
                # 'trailing_stop_positive_offset' should be greater than 'trailing_stop_positive',
                # so this intermediate parameter is used as the value of the difference between
                # them. The value of the 'trailing_stop_positive_offset' is constructed in the
                # generate_trailing_params() method.
                # This is similar to the hyperspace dimensions used for constructing the ROI tables.
                SKDecimal(0.001, 1, decimals=3, name='trailing_stop_positive_offset_p1'),

                Categorical([True, False], name='trailing_only_offset_is_reached'),
        ]

        # Define a custom max_open_trades space
        def max_open_trades_space(self) -> list[Dimension]:
            return [
                Integer(-1, 10, name='max_open_trades'),
            ]
    """
    This is a strategy template to get you started.
    More information in https://www.freqtrade.io/en/latest/strategy-customization/

    You can:
        :return: a Dataframe with all mandatory indicators for the strategies
    - Rename the class name (Do not forget to update class_name)
    - Add any methods you want to build your strategy
    - Add any lib you need to build your strategy

    You must keep:
    - the lib in the section "Do not remove these libs"
    - the methods: populate_indicators, populate_entry_trend, populate_exit_trend
    You should keep:
    - timeframe, minimal_roi, stoploss, trailing_*
    """
    # Strategy interface version - allow new iterations of the strategy interface.
    # Check the documentation or the Sample strategy to get the latest version.
    INTERFACE_VERSION = 3

    # Optimal timeframe for the strategy.
    timeframe = '1h'

    # Can this strategy go short?
    can_short: bool = True

    # Minimal ROI designed for the strategy.
    # This attribute will be overridden if the config file contains "minimal_roi".
    #minimal_roi = {
    #    "7200": 1,
    #    "3000": 3,
    #    "0": 5
    #}
    minimal_roi = {
        "0": 0.8,
        "1440": 0.6,
        "4320": 0.4,
        "10080": 0
    }

    # Optimal stoploss designed for the strategy.
    # This attribute will be overridden if the config file contains "stoploss".
    stoploss = -0.15
    use_custom_stoploss = False
    # Trailing stoploss
    #trailing_stop = True
    # trailing_only_offset_is_reached = False
    # trailing_stop_positive = 0.01
    # trailing_stop_positive_offset = 0.0  # Disabled / not configured

    # Run "populate_indicators()" only for new candle.
    process_only_new_candles = True

    # These values can be overridden in the config.
    use_exit_signal = True
    exit_profit_only = False
    ignore_roi_if_entry_signal = False

    # Number of candles the strategy requires before producing valid signals
    startup_candle_count: int = 40

    # Strategy parameters
    #atr_factor = 0.012
    #buy_rsi = 30
    #sell_rsi = 70
    #inf_tf = '3d'
    #rsi_period = IntParameter(8, 30, default=30,optimize=True, space="buy")
    #rsi_signal_roll = IntParameter(8, 30, default=15,optimize=True, space="buy")
    #ewma_rate = IntParameter(2,20,default=8, optimize=True,space='buy')
    std_dev_multiplier_buy = CategoricalParameter(
        [0.75, 1, 1.25, 1.5, 1.75], default=1.25, space="buy", optimize=True)
    std_dev_multiplier_sell = CategoricalParameter(
        [0.75, 1, 1.25, 1.5, 1.75], space="sell", default=1.25, optimize=True)

    # Optional order type mapping.
    order_types = {
        'entry': 'limit',
        'exit': 'limit',
        'stoploss': 'market',
        'stoploss_on_exchange': False
    }

    # Optional order time in force.
    order_time_in_force = {
        'entry': 'GTC',
        'exit': 'GTC'
    }

    @property
    def plot_config(self):
        return {
            # Main plot indicators (Moving averages, ...)
            'main_plot': {
                'tema': {},
                'sar': {'color': 'white'},
            },
            'subplots': {
                # Subplots - each dict defines one additional plot
                #"MACD": {
                #    'macd': {'color': 'blue'},
                #    'macdsignal': {'color': 'orange'},
                #},
                "RSI": {
                    'rsi': {'color': 'red'},
                    '%-smoothed_rsi': {'color':'blue'}
                }
            }
        }
    # user should define the maximum startup candle count (the largest number of candles
    # passed to any single indicator)
    startup_candle_count: int = 20

    def feature_engineering_expand_all(self, dataframe: DataFrame, period: int,
                                       metadata: dict, **kwargs) -> DataFrame:
        """
        *Only functional with FreqAI enabled strategies*
        This function will automatically expand the defined features on the config defined
        `indicator_periods_candles`, `include_timeframes`, `include_shifted_candles`, and
        `include_corr_pairs`. In other words, a single feature defined in this function
        will automatically expand to a total of
        `indicator_periods_candles` * `include_timeframes` * `include_shifted_candles` *
        `include_corr_pairs` numbers of features added to the model.

        All features must be prepended with `%` to be recognized by FreqAI internals.

        Access metadata such as the current pair/timeframe with:

        `metadata["pair"]` `metadata["tf"]`

        More details on how these config defined parameters accelerate feature engineering
        in the documentation at:

        https://www.freqtrade.io/en/latest/freqai-parameter-table/#feature-parameters

        https://www.freqtrade.io/en/latest/freqai-feature-engineering/#defining-the-features

        :param dataframe: strategy dataframe which will receive the features
        :param period: period of the indicator - usage example:
        :param metadata: metadata of current pair
        dataframe["%-ema-period"] = ta.EMA(dataframe, timeperiod=period)
        """
        #def trend_of_values(values):
        #    if all(x < y for x, y in zip(values, values[1:])):
        #        return 1
        #    elif all(x > y for x, y in zip(values, values[1:])):
        #        return -1
        #    return 0


        #def min_2(series):
        #    return trend_of_values(
        #        series[series.nsmallest(2).index.sort_values(ascending=True).values])
        #def max_2(series):
        #    return trend_of_values(
        #        series[series.nlargest(2).index.sort_values(ascending=True).values])

        #RSI_DIV
        #Bullish
        #dataframe['trend_rsi_bull'] = dataframe['smoothed_rsi'].rolling(
        #    window=self.rsi_signal_roll.value).apply(min_2, raw=False)
        #dataframe.loc[find_peaks(-1*dataframe['smoothed_close'],
        #            distance=self.rsi_signal_roll.value,width=3,
        #            prominence=dataframe['atr'].iloc[-1])[0],'price_peaks'] = 1
        #dataframe['trend_price_bull'] = (
        #    dataframe[dataframe['price_peaks'] == 1]['close']).rolling(2).apply(min_2,raw=False)
        ##Bearish
        #dataframe['trend_rsi_bear'] = dataframe['rsi'].rolling(
        #    window=self.rsi_signal_roll.value).apply(max_2, raw=False)
        #dataframe.loc[find_peaks(dataframe['smoothed_close'],
        #            distance=self.rsi_signal_roll.value,width=3,
        #            prominence=dataframe['atr'].iloc[-1])[0],'price_troughs'] = -1
        #dataframe['trend_price_bear'] = (
        #    dataframe[dataframe['price_troughs'] == -1]['close']).rolling(2).apply(max_2,raw=False)
        # # Pivot Points
        # # -------------------------------------
        # # Pivot Points
        # # Colnames: "pivot", "s1", "s2","s3","r1","r2","r3"

        # Get the informative pair

        # RSI
        dataframe['rsi'] = ta.RSI(dataframe,period)
        dataframe['%-smoothed_rsi-period'] = ta.SMA(dataframe['rsi'], timeperiod=14)

        #Smoothed price
        dataframe['%-smoothed_close-period'] = ta.WMA(2 * ta.WMA(dataframe['close'],
            timeperiod=int(period/2)) - ta.WMA(dataframe['close'],
             timeperiod=period), timeperiod=int(np.sqrt(period)))

        def pivot_points(dataframe,timeperiod,pivot_num):
            dataframe['pivot'] = (dataframe['low'].rolling(timeperiod).min().shift(1)
                                  +dataframe['high'].rolling(timeperiod).max().shift(1)+
                                  dataframe['close'].rolling(timeperiod).mean().shift(1))/3
            dataframe['s1'] = dataframe['pivot']*2 - dataframe['high'].rolling(
                                    timeperiod).max().shift(1)
            dataframe['r1'] = dataframe['pivot']*2 - dataframe['low'].rolling(
                                    timeperiod).min().shift(1)
            dataframe['s2'] = dataframe['pivot'] - (dataframe['high'].rolling(
                                    timeperiod).max().shift(1) - dataframe['low'].rolling(
                                    timeperiod).min().shift(1))
            dataframe['r2'] = dataframe['pivot'] + (dataframe['high'].rolling(
                                timeperiod).max().shift(1) - dataframe['low'].rolling(
                                timeperiod).min().shift(1))
            for i in range(3, pivot_num + 1):
                dataframe[f's{i}'] = dataframe['pivot'] - i*(dataframe['pivot'] - dataframe['low']
                                .rolling(timeperiod).min().shift(1))
                dataframe[f'r{i}'] = dataframe['pivot'] + i*(dataframe['high'].rolling(
                                    timeperiod).max().shift(1) - dataframe['pivot'])
            return dataframe
        piv_num = 3
        if metadata["tf"] == '3d':
            dataframe = pivot_points(dataframe,period,piv_num)
            for j in ['r','s']:
                for i in range(piv_num):
                    dataframe[f'%-{j}{i+1}_bull-period'] = (
                        (dataframe['%-smoothed_close-period'].shift(1) >
                        dataframe[f'{j}{i+1}']) &
                        (dataframe['%-smoothed_close-period'].shift(3) <=
                        dataframe[f'{j}{i+1}'])
                    )
                    dataframe[f'%-{j}{i+1}_bear-period'] = (
                        (dataframe['%-smoothed_close-period'].shift(1) <
                        dataframe[f'{j}{i+1}']) &
                        (dataframe['%-smoothed_close-period'].shift(3) >=
                        dataframe[f'{j}{i+1}'])
                    )
            dataframe['%-pivot_bull-period'] = (
                        (dataframe['%-smoothed_close-period'].shift(1) >
                        dataframe['pivot']) &
                        (dataframe['%-smoothed_close-period'].shift(3) <=
                        dataframe['pivot'])
                    )
            dataframe['%-pivot_bear'] = (
                        (dataframe['%-smoothed_close-period'].shift(1) <
                        dataframe['pivot']) &
                        (dataframe['%-smoothed_close-period'].shift(3) >=
                        dataframe['pivot'])
                    )


        dataframe["%-relative_volume-period"] = (
            dataframe["volume"] / dataframe["volume"].rolling(period).mean()
        )
        return dataframe

    def feature_engineering_expand_basic(
            self, dataframe: DataFrame, metadata: dict, **kwargs) -> DataFrame:
        """
        *Only functional with FreqAI enabled strategies*
        This function will automatically expand the defined features on the config defined
        `include_timeframes`, `include_shifted_candles`, and `include_corr_pairs`.
        In other words, a single feature defined in this function
        will automatically expand to a total of
        `include_timeframes` * `include_shifted_candles` * `include_corr_pairs`
        numbers of features added to the model.

        Features defined here will *not* be automatically duplicated on user defined
        `indicator_periods_candles`

        All features must be prepended with `%` to be recognized by FreqAI internals.

        Access metadata such as the current pair/timeframe with:

        `metadata["pair"]` `metadata["tf"]`

        More details on how these config defined parameters accelerate feature engineering
        in the documentation at:

        https://www.freqtrade.io/en/latest/freqai-parameter-table/#feature-parameters

        https://www.freqtrade.io/en/latest/freqai-feature-engineering/#defining-the-features

        :param dataframe: strategy dataframe which will receive the features
        :param metadata: metadata of current pair
        dataframe["%-pct-change"] = dataframe["close"].pct_change()
        dataframe["%-ema-200"] = ta.EMA(dataframe, timeperiod=200)
        """
        dataframe["%-pct-change"] = dataframe["close"].pct_change()
        dataframe["%-raw_volume"] = dataframe["volume"]
        return dataframe

    def feature_engineering_standard(
            self, dataframe: DataFrame, metadata: dict, **kwargs) -> DataFrame:
        """
        *Only functional with FreqAI enabled strategies*
        This optional function will be called once with the dataframe of the base timeframe.
        This is the final function to be called, which means that the dataframe entering this
        function will contain all the features and columns created by all other
        freqai_feature_engineering_* functions.

        This function is a good place to do custom exotic feature extractions (e.g. tsfresh).
        This function is a good place for any feature that should not be auto-expanded upon
        (e.g. day of the week).

        All features must be prepended with `%` to be recognized by FreqAI internals.

        Access metadata such as the current pair with:

        `metadata["pair"]`

        More details about feature engineering available:

        https://www.freqtrade.io/en/latest/freqai-feature-engineering

        :param dataframe: strategy dataframe which will receive the features
        :param metadata: metadata of current pair
        usage example: dataframe["%-day_of_week"] = (dataframe["date"].dt.dayofweek + 1) / 7
        """
        dataframe["%-raw_close"] = dataframe["close"]
        dataframe["%-raw_open"] = dataframe["open"]
        dataframe["%-raw_high"] = dataframe["high"]
        dataframe["%-raw_low"] = dataframe["low"]
        dataframe["%-day_of_week"] = dataframe["date"].dt.dayofweek
        dataframe["%-hour_of_day"] = dataframe["date"].dt.hour
        return dataframe

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Adds several different TA indicators to the given DataFrame

        Performance Note: For the best performance be frugal on the number of indicators
        you are using. Let uncomment only the indicator you are using in your strategies
        or your hyperopt configuration, otherwise you will waste your memory and CPU usage.
        :param dataframe: Dataframe with data from the exchange
        :param metadata: Additional information, like the currently traded pair
        :return: a Dataframe with all mandatory indicators for the strategies
        """
        dataframe = self.freqai.start(dataframe, metadata, self)
        # ------------------------------------
        # first check if dataprovider is available
        #if self.dp:
        #    if self.dp.runmode.value in ('live', 'dry_run'):
        #        ob = self.dp.orderbook(metadata['pair'], 1)
        #        dataframe['best_bid'] = ob['bids'][0][0]
        #        dataframe['best_ask'] = ob['asks'][0][0]
        return dataframe


    def populate_entry_trend(self, df: DataFrame, metadata: dict) -> DataFrame:

        enter_long_conditions = [df["do_predict"] == 1, df["&-action"] == 1]

        if enter_long_conditions:
            df.loc[
                reduce(lambda x, y: x & y, enter_long_conditions), ["enter_long", "enter_tag"]
            ] = (1, "long")

        enter_short_conditions = [df["do_predict"] == 1, df["&-action"] == 3]

        if enter_short_conditions:
            df.loc[
                reduce(lambda x, y: x & y, enter_short_conditions), ["enter_short", "enter_tag"]
            ] = (1, "short")
        return df

    def populate_exit_trend(self, df: DataFrame, metadata: dict) -> DataFrame:
        exit_long_conditions = [df["do_predict"] == 1, df["&-action"] == 2]
        if exit_long_conditions:
            df.loc[reduce(lambda x, y: x & y, exit_long_conditions), "exit_long"] = 1

        exit_short_conditions = [df["do_predict"] == 1, df["&-action"] == 4]
        if exit_short_conditions:
            df.loc[reduce(lambda x, y: x & y, exit_short_conditions), "exit_short"] = 1
        return df

    def set_freqai_targets(self, dataframe: DataFrame, metadata: dict, **kwargs):

        dataframe["&-action"] = 0

        return dataframe

    def confirm_trade_entry(
        self,
        pair: str,
        order_type: str,
        amount: float,
        rate: float,
        time_in_force: str,
        current_time,
        entry_tag,
        side: str,
        **kwargs,
    ) -> bool:

        df, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)
        last_candle = df.iloc[-1].squeeze()

        if side == "long":
            if rate > (last_candle["close"] * (1 + 0.0025)):
                return False
        else:
            if rate < (last_candle["close"] * (1 - 0.0025)):
                return False

        return True

    def leverage(self, pair: str, current_time: datetime, current_rate: float,
                 proposed_leverage: float, max_leverage: float, entry_tag: Optional[str],
                 side: str, **kwargs) -> float:

        max_leverage = 10

        return max_leverage
```
Thanks in advanced, i really want this to work, and i think i tried everything the official documentation has to offer.

**Comment by peasant-try** [comment]
Can anyone help me with this please? or at least tell me how can i debug the freqtrade module that is referenced in the error? since i don't know the architecture of this framework, and neither prints or logs show in the command prompt, thanks in advanced.

**Comment by xmatthias** [comment]
well the error says that there is a datetime method (not an object, but the method to create a datetime) assigned to a dataframe.

This will not fail on assignment - but when it's trying to be used.
essentially - something around this: `dataframe['date'] = datetime` (though most likely not directly, but somehow hidden / nested from within a function or similar).

I'm pretty certain that freqtrade doesn't have such an assignment.

Your strategy doesn't seem to show signs of this - so it might be a "fragment" from prior tries - which you can probably fix by using a new freqAI identifier.

It might also be caused by the freqAI model used - which obviously get's the dataframe, and can / should modify it to some degree - though we can't control if it's modified in a correct or incorrect manner.

**Comment by peasant-try** [comment]
I changed the identifier value, deleted the model data from previous attempts and it worked like a charm. Thank you very much!
