### ISSUE TITLE
Freqtrade: This class does not exist or contains Python code errors.

### ISSUE THREAD

**Issue by carlos306** [freqtrade/freqtrade#9969]
Hello, can you please help me with this freqtrade issue?

I'm trying to implement new strategies but it always display the same error: "This class does not exist or contains Python code errors.".

I changed the name of the strategy where it says "SampleStrategy" and search for any errors that may be in a line, but i found nothing

![image](https://github.com/freqtrade/freqtrade/assets/71940068/3af685bf-e421-46d2-a27e-4410491491e1)

This is the strategy i'm trying to implement:

```
# --- Do not remove these libs ---
from freqtrade.strategy import IStrategy
from typing import Dict, List
from functools import reduce
from pandas import DataFrame
# --------------------------------

import talib.abstract as ta
import freqtrade.vendor.qtpylib.indicators as qtpylib


class Strategy001(IStrategy):
    """
    Strategy 001
    author@: Gerald Lonlas
    github@: https://github.com/freqtrade/freqtrade-strategies

    How to use it?
    > python3 ./freqtrade/main.py -s Strategy001
    """

    INTERFACE_VERSION: int = 3
    # Minimal ROI designed for the strategy.
    # This attribute will be overridden if the config file contains "minimal_roi"
    minimal_roi = {
        "60":  0.01,
        "30":  0.03,
        "20":  0.04,
        "0":  0.05
    }

    # Optimal stoploss designed for the strategy
    # This attribute will be overridden if the config file contains "stoploss"
    stoploss = -0.10

    # Optimal timeframe for the strategy
    timeframe = '5m'

    # trailing stoploss
    trailing_stop = False
    trailing_stop_positive = 0.01
    trailing_stop_positive_offset = 0.02

    # run "populate_indicators" only for new candle
    process_only_new_candles = True

    # Experimental settings (configuration will overide these if set)
    use_exit_signal = True
    exit_profit_only = True
    ignore_roi_if_entry_signal = False

    # Optional order type mapping
    order_types = {
        'entry': 'limit',
        'exit': 'limit',
        'stoploss': 'market',
        'stoploss_on_exchange': False
    }

    def informative_pairs(self):
        """
        Define additional, informative pair/interval combinations to be cached from the exchange.
        These pair/interval combinations are non-tradeable, unless they are part
        of the whitelist as well.
        For more information, please consult the documentation
        :return: List of tuples in the format (pair, interval)
            Sample: return [("ETH/USDT", "5m"),
                            ("BTC/USDT", "15m"),
                            ]
        """
        return []

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Adds several different TA indicators to the given DataFrame

        Performance Note: For the best performance be frugal on the number of indicators
        you are using. Let uncomment only the indicator you are using in your strategies
        or your hyperopt configuration, otherwise you will waste your memory and CPU usage.
        """

        dataframe['ema20'] = ta.EMA(dataframe, timeperiod=20)
        dataframe['ema50'] = ta.EMA(dataframe, timeperiod=50)
        dataframe['ema100'] = ta.EMA(dataframe, timeperiod=100)

        heikinashi = qtpylib.heikinashi(dataframe)
        dataframe['ha_open'] = heikinashi['open']
        dataframe['ha_close'] = heikinashi['close']

        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators, populates the buy signal for the given dataframe
        :param dataframe: DataFrame
        :return: DataFrame with buy column
        """
        dataframe.loc[
            (
                qtpylib.crossed_above(dataframe['ema20'], dataframe['ema50']) &
                (dataframe['ha_close'] > dataframe['ema20']) &
                (dataframe['ha_open'] < dataframe['ha_close'])  # green bar
            ),
            'enter_long'] = 1

        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators, populates the sell signal for the given dataframe
        :param dataframe: DataFrame
        :return: DataFrame with buy column
        """
        dataframe.loc[
            (
                qtpylib.crossed_above(dataframe['ema50'], dataframe['ema100']) &
                (dataframe['ha_close'] < dataframe['ema20']) &
                (dataframe['ha_open'] > dataframe['ha_close'])  # red bar
            ),
            'exit_long'] = 1
        return dataframe
```

Docker displays this messages: 
```
2024-03-18 10:17:09 freqtrade  | 2024-03-18 15:17:09,828 - freqtrade - INFO - freqtrade 2024.2
2024-03-18 10:17:11 freqtrade  | 2024-03-18 15:17:11,566 - freqtrade.worker - INFO - Starting worker 2024.2
2024-03-18 10:17:11 freqtrade  | 2024-03-18 15:17:11,567 - freqtrade.configuration.load_config - INFO - Using config: /freqtrade/user_data/config.json ...
2024-03-18 10:17:11 freqtrade  | 2024-03-18 15:17:11,601 - freqtrade.loggers - INFO - Verbosity set to 0
2024-03-18 10:17:11 freqtrade  | 2024-03-18 15:17:11,607 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
2024-03-18 10:17:11 freqtrade  | 2024-03-18 15:17:11,613 - freqtrade.configuration.configuration - INFO - Parameter --db-url detected ...
2024-03-18 10:17:11 freqtrade  | 2024-03-18 15:17:11,620 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2024-03-18 10:17:11 freqtrade  | 2024-03-18 15:17:11,627 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:////freqtrade/user_data/tradesv3.sqlite"
2024-03-18 10:17:11 freqtrade  | 2024-03-18 15:17:11,632 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 10 ...
2024-03-18 10:17:11 freqtrade  | 2024-03-18 15:17:11,981 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2024-03-18 10:17:11 freqtrade  | 2024-03-18 15:17:11,998 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/binance ...
2024-03-18 10:17:12 freqtrade  | 2024-03-18 15:17:12,009 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2024-03-18 10:17:12 freqtrade  | 2024-03-18 15:17:12,075 - freqtrade.exchange.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2024-03-18 10:17:12 freqtrade  | 2024-03-18 15:17:12,082 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2024-03-18 10:17:12 freqtrade  | 2024-03-18 15:17:12,305 - freqtrade.commands.trade_commands - ERROR - Impossible to load Strategy 'Strategy001'. This class does not exist or contains Python code errors.
2024-03-18 10:17:12 freqtrade  | 2024-03-18 15:17:12,311 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
2024-03-18 10:17:12 freqtrade  | Traceback (most recent call last):
2024-03-18 10:17:12 freqtrade  |   File "/freqtrade/freqtrade/commands/trade_commands.py", line 24, in start_trading
2024-03-18 10:17:12 freqtrade  |     worker = Worker(args)
2024-03-18 10:17:12 freqtrade  |              ^^^^^^^^^^^^
2024-03-18 10:17:12 freqtrade  |   File "/freqtrade/freqtrade/worker.py", line 37, in __init__
2024-03-18 10:17:12 freqtrade  |     self._init(False)
2024-03-18 10:17:12 freqtrade  |   File "/freqtrade/freqtrade/worker.py", line 53, in _init
2024-03-18 10:17:12 freqtrade  |     self.freqtrade = FreqtradeBot(self._config)
2024-03-18 10:17:12 freqtrade  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-18 10:17:12 freqtrade  |   File "/freqtrade/freqtrade/freqtradebot.py", line 71, in __init__
2024-03-18 10:17:12 freqtrade  |     self.strategy: IStrategy = StrategyResolver.load_strategy(self.config)
2024-03-18 10:17:12 freqtrade  |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-18 10:17:12 freqtrade  |   File "/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 48, in load_strategy
2024-03-18 10:17:12 freqtrade  |     strategy: IStrategy = StrategyResolver._load_strategy(
2024-03-18 10:17:12 freqtrade  |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-18 10:17:12 freqtrade  |   File "/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 280, in _load_strategy
2024-03-18 10:17:12 freqtrade  |     raise OperationalException(
2024-03-18 10:17:12 freqtrade  | freqtrade.exceptions.OperationalException: Impossible to load Strategy 'Strategy001'. This class does not exist or contains Python code errors.
```

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that. 

---

well the error is pretty clear - can't load strategy `Strategy001`.

Most likely, that's a "where is the strategy file saved" problem (it should be in `user_data/strategies/` - in a file with extension `.py`) - or a "the file wasn't saved" problem.

**Comment by carlos306** [comment]
Sorry about filling the template, I'm new with GitHub.


I have the strategy file in the right folder and name, but it always show me the same error (with all the strategies I've tried)

**Comment by xmatthias** [comment]
> Sorry about filling the template, I'm new with GitHub.

it's a default template - aimed to educate for next time - don't worry too much ;) 

well assuming you didn't modify the docker-compose file - what does `ls -l user_data/freqtrade` show?

**Comment by carlos306** [comment]
![image](https://github.com/freqtrade/freqtrade/assets/71940068/c1f50a2a-b6ce-4e32-a322-25e92f017247)

I'm using windows, "ls -l" does not work, is this what you asked me?

**Comment by xmatthias** [comment]
well on windows, it should be something around `dir user_data\strategies\` ...

**Comment by carlos306** [comment]
![image](https://github.com/freqtrade/freqtrade/assets/71940068/669a2609-0c44-4120-8e6d-b09c8b8b427a)

**Comment by xmatthias** [comment]
Well the file `strategy_001` is not a python file (it lacks the extension - hence freqtrade doesn't even try to read this file).

Please rename it to `strategy_001.py` - and you'll see that it'll work. (you can enable your explorer to show file extensions in the "view" options in the top panel of the explorer).

**Comment by carlos306** [comment]
Thak you very much
